CALYPSO: t_read_sph_spectra Module Reference
t_read_sph_spectra Module Reference
Time average spherical harmonics spectrum data.
Data Types
type read_sph_spectr_data
Functions/Subroutines
subroutine alloc_sph_espec_name (sph_IN)
subroutine alloc_sph_spectr_data (ltr, sph_IN)
subroutine dealloc_sph_espec_data (sph_IN)
subroutine copy_read_ene_params_4_sum (sph_IN, sph_OUT)
subroutine copy_read_ene_step_data (sph_IN, sph_OUT)
subroutine copy_ene_spectr_data_to_io (nri_sph, ltr_sph, ncomp, spectr_l, sph_OUT)
subroutine select_sph_ene_spec_data_file (sph_IN, input_header)
Detailed Description
Time average spherical harmonics spectrum data.
      subroutine alloc_sph_espec_name(sph_IN)
      subroutine alloc_sph_spectr_data(ltr, sph_IN)
      subroutine dealloc_sph_espec_data(sph_IN)
      subroutine copy_read_ene_params_4_sum(sph_IN, sph_OUT)
      subroutine copy_read_ene_step_data(sph_IN, sph_OUT)
      subroutine copy_ene_spectr_data_to_IO(nri_sph, ltr_sph, ncomp,  &
     &          spectr_l, sph_OUT)
      subroutine select_sph_ene_spec_data_file(sph_IN, input_header)
Function/Subroutine Documentation
alloc_sph_espec_name()
subroutine t_read_sph_spectra::alloc_sph_espec_name (type(read_sph_spectr_data), intent(inout) sph_IN)
Definition at line 60 of file t_read_sph_spectra.f90.
Referenced by copy_read_ene_params_4_sum(), simple_sph_spectr_head_io::input_sph_pwr_layer_head(), simple_sph_spectr_head_io::input_sph_pwr_layer_head_old(), simple_sph_spectr_head_io::input_sph_pwr_vol_head(), simple_sph_spectr_head_io::input_sph_pwr_vol_head_old(), simple_sph_spectr_head_io::input_sph_spectr_layer_head(), simple_sph_spectr_head_io::input_sph_spectr_layer_head_old(), simple_sph_spectr_head_io::input_sph_spectr_vol_head(), and simple_sph_spectr_head_io::input_sph_spectr_vol_head_old().
alloc_sph_spectr_data()
subroutine t_read_sph_spectra::alloc_sph_spectr_data (integer(kind = kint), intent(in) ltr, type(read_sph_spectr_data), intent(inout) sph_IN)
Definition at line 74 of file t_read_sph_spectra.f90.
References m_constants::izero, and m_constants::zero.
Referenced by copy_read_ene_params_4_sum(), simple_sph_spectr_head_io::input_sph_pwr_layer_head(), simple_sph_spectr_head_io::input_sph_pwr_layer_head_old(), simple_sph_spectr_head_io::input_sph_pwr_vol_head(), simple_sph_spectr_head_io::input_sph_pwr_vol_head_old(), simple_sph_spectr_head_io::input_sph_spectr_layer_head(), simple_sph_spectr_head_io::input_sph_spectr_layer_head_old(), simple_sph_spectr_head_io::input_sph_spectr_vol_head(), and simple_sph_spectr_head_io::input_sph_spectr_vol_head_old().
copy_ene_spectr_data_to_io()
subroutine t_read_sph_spectra::copy_ene_spectr_data_to_io (integer(kind = kint), intent(in) nri_sph, integer(kind = kint), intent(in) ltr_sph, integer(kind = kint), intent(in) ncomp, real(kind = kreal), dimension(ncomp, 0:ltr_sph, nri_sph), intent(in) spectr_l, type(read_sph_spectr_data), intent(inout) sph_OUT)
Definition at line 172 of file t_read_sph_spectra.f90.
copy_read_ene_params_4_sum()
subroutine t_read_sph_spectra::copy_read_ene_params_4_sum (type(read_sph_spectr_data), intent(in) sph_IN, type(read_sph_spectr_data), intent(inout) sph_OUT)
Definition at line 110 of file t_read_sph_spectra.f90.
References alloc_sph_espec_name(), alloc_sph_spectr_data(), and m_constants::izero.
copy_read_ene_step_data()
subroutine t_read_sph_spectra::copy_read_ene_step_data (type(read_sph_spectr_data), intent(in) sph_IN, type(read_sph_spectr_data), intent(inout) sph_OUT)
Definition at line 155 of file t_read_sph_spectra.f90.
dealloc_sph_espec_data()
subroutine t_read_sph_spectra::dealloc_sph_espec_data (type(read_sph_spectr_data), intent(inout) sph_IN)
Definition at line 97 of file t_read_sph_spectra.f90.
Referenced by m_tave_sph_ene_spectr::sph_spectr_average(), and m_tave_sph_ene_spectr::sph_spectr_std_deviation().
select_sph_ene_spec_data_file()
subroutine t_read_sph_spectra::select_sph_ene_spec_data_file (type(read_sph_spectr_data), intent(inout) sph_IN, character(len = kchara), intent(inout) input_header)
Definition at line 192 of file t_read_sph_spectra.f90.
Referenced by t_average_sph_ene_spec().