CALYPSO: t_control_data_4_iso Module Reference
t_control_data_4_iso Module Reference
control data for each isosurface
Data Types
type iso_ctl
Functions/Subroutines
subroutine init_iso_ctl_stract (iso_c)
subroutine dealloc_cont_dat_4_iso (iso_c)
subroutine dup_control_4_iso (org_iso_c, new_iso_c)
subroutine read_iso_control_data (id_control, hd_block, iso_c, c_buf)
subroutine bcast_iso_control_data (iso_c)
integer(kind=kint) function num_label_iso_ctl ()
integer(kind=kint) function num_label_iso_ctl_w_dpl ()
subroutine set_label_iso_ctl (names)
subroutine set_label_iso_ctl_w_dpl (names)
Variables
character(len=kchara), parameter, private hd_isosurf_prefix = 'isosurface_file_prefix'
character(len=kchara), parameter, private hd_iso_out_type = 'iso_output_type'
character(len=kchara), parameter, private hd_iso_define = 'isosurf_define'
character(len=kchara), parameter, private hd_field_on_iso = 'field_on_isosurf'
character(len=kchara), parameter, private hd_iso_file_head = 'iso_file_head'
character(len=kchara), parameter, private hd_iso_result = 'isosurf_result_define'
integer(kind=kint), parameter, private n_label_iso_ctl = 4
integer(kind=kint), parameter, private n_label_iso_ctl_w_dpl = 6
Detailed Description
control data for each isosurface
      subroutine init_iso_ctl_stract(iso_c)
      subroutine dealloc_cont_dat_4_iso(iso_c)
        type(iso_ctl), intent(inout) :: iso_c
      subroutine dup_control_4_iso(org_iso_c, new_iso_c)
        type(iso_ctl), intent(in) :: org_iso_c
        type(iso_ctl), intent(inout) :: new_iso_c
      subroutine read_iso_control_data                                &
     &         (id_control, hd_block, iso_c, c_buf)
      subroutine bcast_iso_control_data(iso_c)
        type(iso_ctl), intent(inout) :: iso_c
      integer(kind = kint) function num_label_iso_ctl()
      integer(kind = kint) function num_label_iso_ctl_w_dpl()
      subroutine set_label_iso_ctl(names)
      subroutine set_label_iso_ctl_w_dpl(names)
     example of control for Kemo's surface rendering
  begin isosurface_ctl
    isosurface_file_prefix    'psf'
    iso_output_type            ucd
    begin isosurf_define
      isosurf_field        pressure
      isosurf_component      scalar
      isosurf_value            4000.0
      array isosurf_area_ctl   2
        isosurf_area_ctl   inner_core   end
        isosurf_area_ctl   outer_core   end
      end array isosurf_area_ctl
    end isosurf_define
    begin field_on_isosurf
      result_type      constant
      result_value     0.7
      array output_field   2
        output_field    velocity         vector   end
        output_field    magnetic_field   radial   end
      end array output_field
    end field_on_isosurf
  end isosurface_ctl
    iso_output_type:
           ucd, ucd_gz, iso
    result_type:  (Original name: display_method)
                   specified_fields
                   constant
    num_result_comp: number of fields
    output_field: (Original name: color_comp and color_subcomp)
         field and componenet name for output
           x, y, z, radial, elevation, azimuth, cylinder_r
           norm, vector, tensor, spherical_vector, cylindrical_vector
    result_value: (Original name: specified_color)
    isosurf_data: field for isosurface
    isosurf_comp: component for isosurface
           x, y, z, radial, elevation, azimuth, cylinder_r, norm
    isosurf_value:  value for isosurface
Function/Subroutine Documentation
bcast_iso_control_data()
subroutine t_control_data_4_iso::bcast_iso_control_data (type(iso_ctl), intent(inout) iso_c)
Definition at line 225 of file t_control_data_4_iso.f90.
References bcast_control_arrays::bcast_ctl_type_c1(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by t_control_data_isosurfaces::bcast_files_4_iso_ctl().
dealloc_cont_dat_4_iso()
subroutine t_control_data_4_iso::dealloc_cont_dat_4_iso (type(iso_ctl), intent(inout) iso_c)
Definition at line 148 of file t_control_data_4_iso.f90.
Referenced by set_psf_iso_control::set_iso_control().
dup_control_4_iso()
subroutine t_control_data_4_iso::dup_control_4_iso (type(iso_ctl), intent(in) org_iso_c, type(iso_ctl), intent(inout) new_iso_c)
Definition at line 165 of file t_control_data_4_iso.f90.
init_iso_ctl_stract()
subroutine t_control_data_4_iso::init_iso_ctl_stract (type(iso_ctl), intent(inout) iso_c)
Definition at line 136 of file t_control_data_4_iso.f90.
num_label_iso_ctl()
integer(kind = kint) function t_control_data_4_iso::num_label_iso_ctl
Definition at line 248 of file t_control_data_4_iso.f90.
References n_label_iso_ctl.
num_label_iso_ctl_w_dpl()
integer(kind = kint) function t_control_data_4_iso::num_label_iso_ctl_w_dpl
Definition at line 255 of file t_control_data_4_iso.f90.
References n_label_iso_ctl_w_dpl.
read_iso_control_data()
subroutine t_control_data_4_iso::read_iso_control_data (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(iso_ctl), intent(inout) iso_c, type(buffer_for_control), intent(inout) c_buf)
Definition at line 188 of file t_control_data_4_iso.f90.
References hd_field_on_iso, hd_iso_define, hd_iso_file_head, hd_iso_out_type, hd_iso_result, and hd_isosurf_prefix.
Referenced by t_control_data_isosurfaces::read_control_4_iso_file().
set_label_iso_ctl()
subroutine t_control_data_4_iso::set_label_iso_ctl (character(len = kchara), dimension(n_label_iso_ctl), intent(inout) names)
Definition at line 262 of file t_control_data_4_iso.f90.
References hd_field_on_iso, hd_iso_define, hd_iso_out_type, and hd_isosurf_prefix.
Referenced by set_label_iso_ctl_w_dpl().
set_label_iso_ctl_w_dpl()
subroutine t_control_data_4_iso::set_label_iso_ctl_w_dpl (character(len = kchara), dimension(n_label_iso_ctl_w_dpl), intent(inout) names)
Definition at line 277 of file t_control_data_4_iso.f90.
References hd_iso_file_head, hd_iso_result, and set_label_iso_ctl().
Variable Documentation
hd_field_on_iso
character(len=kchara), parameter, private t_control_data_4_iso::hd_field_on_iso = 'field_on_isosurf' private
Definition at line 112 of file t_control_data_4_iso.f90.
Referenced by read_iso_control_data(), and set_label_iso_ctl().
hd_iso_define
character(len=kchara), parameter, private t_control_data_4_iso::hd_iso_define = 'isosurf_define' private
Definition at line 110 of file t_control_data_4_iso.f90.
Referenced by read_iso_control_data(), and set_label_iso_ctl().
hd_iso_file_head
character(len=kchara), parameter, private t_control_data_4_iso::hd_iso_file_head = 'iso_file_head' private
Definition at line 117 of file t_control_data_4_iso.f90.
Referenced by read_iso_control_data(), and set_label_iso_ctl_w_dpl().
hd_iso_out_type
character(len=kchara), parameter, private t_control_data_4_iso::hd_iso_out_type = 'iso_output_type' private
Definition at line 108 of file t_control_data_4_iso.f90.
Referenced by read_iso_control_data(), and set_label_iso_ctl().
hd_iso_result
character(len=kchara), parameter, private t_control_data_4_iso::hd_iso_result = 'isosurf_result_define' private
Definition at line 119 of file t_control_data_4_iso.f90.
Referenced by read_iso_control_data(), and set_label_iso_ctl_w_dpl().
hd_isosurf_prefix
character(len=kchara), parameter, private t_control_data_4_iso::hd_isosurf_prefix = 'isosurface_file_prefix' private
Definition at line 106 of file t_control_data_4_iso.f90.
Referenced by read_iso_control_data(), and set_label_iso_ctl().
n_label_iso_ctl
integer(kind = kint), parameter, private t_control_data_4_iso::n_label_iso_ctl = 4 private
Definition at line 122 of file t_control_data_4_iso.f90.
Referenced by num_label_iso_ctl().
n_label_iso_ctl_w_dpl
integer(kind = kint), parameter, private t_control_data_4_iso::n_label_iso_ctl_w_dpl = 6 private
Definition at line 123 of file t_control_data_4_iso.f90.
Referenced by num_label_iso_ctl_w_dpl().