CALYPSO: gz_field_file_mpi_io Module Reference
gz_field_file_mpi_io Module Reference
Output merged VTK file usgin MPI-IO.
Functions/Subroutines
subroutine write_gz_step_field_file_mpi (file_name, t_IO, fld_IO)
subroutine read_step_field_file_gz_mpi (file_name, num_pe, id_rank, t_IO, fld_IO)
subroutine read_alloc_stp_fld_file_gz_mpi (file_name, num_pe, id_rank, t_IO, fld_IO)
subroutine read_alloc_stp_fld_head_gz_mpi (file_name, num_pe, id_rank, t_IO, fld_IO)
Detailed Description
Output merged VTK file usgin MPI-IO.
      subroutine write_gz_step_field_file_mpi(file_name, t_IO, fld_IO)
        type(time_data), intent(in) :: t_IO
        type(field_IO), intent(in) :: fld_IO
      subroutine read_step_field_file_gz_mpi                          &
     &         (file_name, num_pe, id_rank, t_IO, fld_IO)
      subroutine read_alloc_stp_fld_file_gz_mpi                       &
     &         (file_name, num_pe, id_rank, t_IO, fld_IO)
        type(time_data), intent(inout) :: t_IO
        type(field_IO), intent(inout) :: fld_IO
      subroutine read_alloc_stp_fld_head_gz_mpi                       &
     &         (file_name, num_pe, id_rank, t_IO, fld_IO)
   Data format for the merged ascii field data
     1.   Number of process
     2.   Time step
     3.   Time, Delta t
     4.   Stacks of numbe of data points
     5.   Number of fields
     6.   List of number of components
     7.   Each field data  (Itarate 7.1 - 7.3)
      7.1   Field name
      7.2   List of data size (Byte, after compressed)
      7.3   Field data
Function/Subroutine Documentation
read_alloc_stp_fld_file_gz_mpi()
subroutine gz_field_file_mpi_io::read_alloc_stp_fld_file_gz_mpi (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO)
Definition at line 135 of file gz_field_file_MPI_IO.f90.
References t_field_data_io::alloc_merged_field_stack(), t_field_data_io::alloc_phys_data_io(), t_field_data_io::alloc_phys_name_io(), t_field_data_io::cal_istack_phys_comp_io(), m_calypso_mpi_io::calypso_close_mpi_file(), m_calypso_mpi_io::calypso_mpi_read_file_open(), transfer_to_long_integers::cast_long(), t_field_data_io::dealloc_merged_field_stack(), t_field_data_io::dealloc_phys_data_io(), t_field_data_io::dealloc_phys_name_io(), calypso_mpi::my_rank, gz_field_block_mpi_io::read_field_data_gz_mpi(), gz_field_block_mpi_io::read_field_header_gz_mpi(), gz_field_block_mpi_io::read_field_num_gz_mpi(), and gz_field_block_mpi_io::read_field_step_gz_mpi().
Referenced by field_io_select::sel_read_alloc_step_field_file().
read_alloc_stp_fld_head_gz_mpi()
subroutine gz_field_file_mpi_io::read_alloc_stp_fld_head_gz_mpi (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO)
Definition at line 192 of file gz_field_file_MPI_IO.f90.
References t_field_data_io::alloc_merged_field_stack(), t_field_data_io::alloc_phys_data_io(), t_field_data_io::alloc_phys_name_io(), t_field_data_io::cal_istack_phys_comp_io(), m_calypso_mpi_io::calypso_close_mpi_file(), m_calypso_mpi_io::calypso_mpi_read_file_open(), t_field_data_io::dealloc_merged_field_stack(), t_field_data_io::dealloc_phys_name_io(), calypso_mpi::my_rank, gz_field_block_mpi_io::read_field_header_gz_mpi(), gz_field_block_mpi_io::read_field_names_gz_mpi(), gz_field_block_mpi_io::read_field_num_gz_mpi(), and gz_field_block_mpi_io::read_field_step_gz_mpi().
Referenced by field_io_select::sel_read_alloc_field_head().
read_step_field_file_gz_mpi()
subroutine gz_field_file_mpi_io::read_step_field_file_gz_mpi (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO)
Definition at line 89 of file gz_field_file_MPI_IO.f90.
References m_calypso_mpi_io::calypso_close_mpi_file(), m_calypso_mpi_io::calypso_mpi_read_file_open(), transfer_to_long_integers::cast_long(), t_field_data_io::dealloc_merged_field_stack(), calypso_mpi::my_rank, gz_field_block_mpi_io::read_field_data_gz_mpi(), gz_field_block_mpi_io::read_field_header_gz_mpi(), gz_field_block_mpi_io::read_field_num_gz_mpi(), and gz_field_block_mpi_io::read_field_step_gz_mpi().
Referenced by field_io_select::sel_read_step_field_file().
write_gz_step_field_file_mpi()
subroutine gz_field_file_mpi_io::write_gz_step_field_file_mpi (character(len=kchara), intent(in) file_name, type(time_data), intent(in) t_IO, type(field_io), intent(in) fld_IO)
Definition at line 55 of file gz_field_file_MPI_IO.f90.
References m_calypso_mpi_io::calypso_close_mpi_file(), m_calypso_mpi_io::calypso_mpi_write_file_open(), transfer_to_long_integers::cast_long(), calypso_mpi::my_rank, calypso_mpi::nprocs, gz_field_block_mpi_io::write_field_data_gz_mpi(), and gz_field_block_mpi_io::write_field_head_gz_mpi().
Referenced by field_io_select::sel_write_step_field_file().