CALYPSO: t_ctl_data_mhd_evolution Module Reference
t_ctl_data_mhd_evolution Module Reference
Control data of time integration flags.
Data Types
type mhd_evo_area_control
type mhd_evolution_control
Functions/Subroutines
subroutine dealloc_t_evo_name_ctl (evo_ctl)
subroutine dealloc_ele_area_grp_ctl (earea_ctl)
subroutine read_mhd_time_evo_ctl (id_control, hd_block, evo_ctl, c_buf)
subroutine read_mhd_layer_ctl (id_control, hd_block, earea_ctl, c_buf)
subroutine bcast_mhd_time_evo_ctl (evo_ctl)
subroutine bcast_mhd_layer_ctl (earea_ctl)
Variables
character(len=kchara), parameter, private hd_t_evo_field = 'time_evo_ctl'
character(len=kchara), parameter, private hd_fluid_grp = 'fluid_ele_grp'
character(len=kchara), parameter, private hd_conduct_grp = 'conduct_ele_grp'
Detailed Description
Control data of time integration flags.
      subroutine dealloc_t_evo_name_ctl(evo_ctl)
      subroutine read_mhd_time_evo_ctl                                &
     &         (id_control, hd_block, evo_ctl, c_buf)
      subroutine bcast_mhd_time_evo_ctl(hd_block, iflag, evo_ctl)
      subroutine bcast_mhd_time_evo_ctl(evo_ctl)
        type(mhd_evolution_control), intent(inout) :: evo_ctl
      subroutine dealloc_ele_area_grp_ctl(earea_ctl)
      subroutine read_mhd_layer_ctl                                   &
     &         (id_control, hd_block, earea_ctl, c_buf)
      subroutine bcast_mhd_layer_ctl(earea_ctl)
        type(mhd_evo_area_control), intent(inout) :: earea_ctl
 ----------------------------------------------------------------------
  physical values for time evolution !!!!!!!!!!!!!!!!!!
 aviable valuables: velocity, temperature, magnetic_field
                    vector_potential, composition
    begin time_evolution_ctl
      array time_evo_ctl   4
        time_evo_ctl  temperature
        time_evo_ctl  velocity
        time_evo_ctl  vector_potential
        time_evo_ctl  composition
      end array time_evo_ctl
    end  time_evolution_ctl
 !!!  setting for layers
    begin layers_ctl
      array fluid_ele_grp    1
        fluid_ele_grp    outer_core
      end array fluid_ele_grp
      array conduct_ele_grp    2
         conduct_ele_grp    inner_core
         conduct_ele_grp    outer_core
      end array conduct_ele_grp
    end  layers_ctl
Function/Subroutine Documentation
bcast_mhd_layer_ctl()
subroutine t_ctl_data_mhd_evolution::bcast_mhd_layer_ctl (type(mhd_evo_area_control), intent(inout) earea_ctl)
Definition at line 205 of file t_ctl_data_mhd_evolution.f90.
References bcast_control_arrays::bcast_ctl_array_c1(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by t_ctl_data_mhd_model::bcast_sph_mhd_model().
bcast_mhd_time_evo_ctl()
subroutine t_ctl_data_mhd_evolution::bcast_mhd_time_evo_ctl (type(mhd_evolution_control), intent(inout) evo_ctl)
Definition at line 189 of file t_ctl_data_mhd_evolution.f90.
References bcast_control_arrays::bcast_ctl_array_c1(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by t_ctl_data_mhd_model::bcast_sph_mhd_model().
dealloc_ele_area_grp_ctl()
subroutine t_ctl_data_mhd_evolution::dealloc_ele_area_grp_ctl (type(mhd_evo_area_control), intent(inout) earea_ctl)
Definition at line 123 of file t_ctl_data_mhd_evolution.f90.
References t_control_array_character::dealloc_control_array_chara().
Referenced by t_ctl_data_mhd_model::dealloc_sph_mhd_model().
dealloc_t_evo_name_ctl()
subroutine t_ctl_data_mhd_evolution::dealloc_t_evo_name_ctl (type(mhd_evolution_control), intent(inout) evo_ctl)
Definition at line 112 of file t_ctl_data_mhd_evolution.f90.
References t_control_array_character::dealloc_control_array_chara().
Referenced by t_ctl_data_mhd_model::dealloc_sph_mhd_model().
read_mhd_layer_ctl()
subroutine t_ctl_data_mhd_evolution::read_mhd_layer_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(mhd_evo_area_control), intent(inout) earea_ctl, type(buffer_for_control), intent(inout) c_buf)
Definition at line 161 of file t_ctl_data_mhd_evolution.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_conduct_grp, hd_fluid_grp, t_read_control_elements::load_one_line_from_control(), and t_control_array_character::read_control_array_c1().
Referenced by t_ctl_data_mhd_model::read_sph_mhd_model().
read_mhd_time_evo_ctl()
subroutine t_ctl_data_mhd_evolution::read_mhd_time_evo_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(mhd_evolution_control), intent(inout) evo_ctl, type(buffer_for_control), intent(inout) c_buf)
Definition at line 136 of file t_ctl_data_mhd_evolution.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_t_evo_field, t_read_control_elements::load_one_line_from_control(), and t_control_array_character::read_control_array_c1().
Referenced by t_ctl_data_mhd_model::read_sph_mhd_model().
Variable Documentation
hd_conduct_grp
character(len=kchara), parameter, private t_ctl_data_mhd_evolution::hd_conduct_grp = 'conduct_ele_grp' private
Definition at line 101 of file t_ctl_data_mhd_evolution.f90.
Referenced by read_mhd_layer_ctl().
hd_fluid_grp
character(len=kchara), parameter, private t_ctl_data_mhd_evolution::hd_fluid_grp = 'fluid_ele_grp' private
Definition at line 99 of file t_ctl_data_mhd_evolution.f90.
Referenced by read_mhd_layer_ctl().
hd_t_evo_field
character(len=kchara), parameter, private t_ctl_data_mhd_evolution::hd_t_evo_field = 'time_evo_ctl' private
Definition at line 94 of file t_ctl_data_mhd_evolution.f90.
Referenced by read_mhd_time_evo_ctl().