CALYPSO: ludcmp_357band_mul Module Reference
ludcmp_357band_mul Module Reference
LU decomposition of 3, 5, or 7 band matrices at once.
Functions/Subroutines
subroutine ludcmp_3band_mul (Msmp, Msmp_stack, mcomp, n, band_a, band_lu, i_pivot, d)
subroutine ludcmp_5band_mul (Msmp, Msmp_stack, mcomp, n, band_a, band_lu, i_pivot, d)
subroutine ludcmp_7band_mul (Msmp, Msmp_stack, mcomp, n, band_a, band_lu, i_pivot, d)
Detailed Description
LU decomposition of 3, 5, or 7 band matrices at once.
------------------------------------------------------------------&mdash;
      subroutine ludcmp_3band_mul(Msmp, Msmp_stack, mcomp, n,         &
     &          band_a, band_lu, i_pivot, d)
      subroutine ludcmp_5band_mul(Msmp, Msmp_stack, mcomp, n,         &
     &          band_a, band_lu, i_pivot, d)
      subroutine ludcmp_7band_mul(Msmp, Msmp_stack, mcomp, n,         &
     &          band_a, band_lu, i_pivot, d)
 Given a matrix a(1:n,1:n), with physical dimension np by np,
 this routine replaces it by the LU decomposition of a rowwise
 permutation of itself. a and n are input.
 a is output, arranged as in equation (2.3.14) above; index(1:n)
 is an output vector that records the row permutation effected by
 partial povoting; dis output as +/- 1 depending on whether
 the number of row interchanges was even or odd, respectively.
 This routine is used in combination with lubksb to solve
 linear equations or ivert a matrix.
Function/Subroutine Documentation
ludcmp_3band_mul()
subroutine ludcmp_357band_mul::ludcmp_3band_mul (integer (kind = kint), intent(in) Msmp, integer (kind = kint), dimension(0:msmp), intent(in) Msmp_stack, integer (kind = kint), intent(in) mcomp, integer (kind = kint), intent(in) n, real(kind = kreal), dimension(3,n,mcomp), intent(in) band_a, real(kind = kreal), dimension(5,n,mcomp), intent(inout) band_lu, integer(kind = kint), dimension(n,mcomp), intent(inout) i_pivot, real(kind = kreal), dimension(mcomp), intent(inout) d)
Definition at line 77 of file ludcmp_357band_mul.f90.
References m_ludcmp_3band::ludcmp_3band().
Referenced by t_sph_matrices::ludcmp_3band_mul_t().
ludcmp_5band_mul()
subroutine ludcmp_357band_mul::ludcmp_5band_mul (integer (kind = kint), intent(in) Msmp, integer (kind = kint), dimension(0:msmp), intent(in) Msmp_stack, integer (kind = kint), intent(in) mcomp, integer (kind = kint), intent(in) n, real(kind = kreal), dimension(5,n,mcomp), intent(in) band_a, real(kind = kreal), dimension(9,n,mcomp), intent(inout) band_lu, integer (kind = kint), dimension(n,mcomp), intent(inout) i_pivot, real(kind = kreal), dimension(mcomp), intent(inout) d)
Definition at line 111 of file ludcmp_357band_mul.f90.
References m_constants::ifive, and m_ludcmp_band::ludcmp_band().
Referenced by t_sph_matrices::ludcmp_5band_mul_t().
ludcmp_7band_mul()
subroutine ludcmp_357band_mul::ludcmp_7band_mul (integer (kind = kint), intent(in) Msmp, integer (kind = kint), dimension(0:msmp), intent(in) Msmp_stack, integer (kind = kint), intent(in) mcomp, integer (kind = kint), intent(in) n, real(kind = kreal), dimension(7,n,mcomp), intent(in) band_a, real(kind = kreal), dimension(13,n,mcomp), intent(inout) band_lu, integer (kind = kint), dimension(n,mcomp), intent(inout) i_pivot, real(kind = kreal), dimension(mcomp), intent(inout) d)
Definition at line 142 of file ludcmp_357band_mul.f90.
References m_constants::iseven, and m_ludcmp_band::ludcmp_band().
Referenced by t_sph_matrices::ludcmp_7band_mul_t().