CALYPSO: check_read_bc_file Module Reference
check_read_bc_file Module Reference
Decide if boundary condition data field is read.
Functions/Subroutines
integer(kind=kint) function check_read_boundary_files (MHD_prop, MHD_BC)
integer(kind=kint) function, private chk_read_boundary_files (fl_prop, cd_prop, ht_prop, cp_prop, MHD_BC)
subroutine, private set_serch_boundary_file_flag (iflag, bc_list)
Variables
integer(kind=kint), parameter id_no_boundary_file = 0
ID not to read external boundary condition file.
integer(kind=kint), parameter id_read_boundary_file = 1
ID to read external boundary condition file.
Detailed Description
Decide if boundary condition data field is read.
      integer(kind=kint) function check_read_boundary_files           &
     &                          (MHD_prop, MHD_BC)
        type(MHD_evolution_param), intent(in) :: MHD_prop
        type(MHD_BC_lists), intent(in) :: MHD_BC
Function/Subroutine Documentation
check_read_boundary_files()
integer(kind=kint) function check_read_bc_file::check_read_boundary_files (type(mhd_evolution_param), intent(in) MHD_prop, type(mhd_bc_lists), intent(in) MHD_BC)
Definition at line 37 of file check_read_bc_file.f90.
References chk_read_boundary_files().
Referenced by set_control_4_sph_to_fem::sph_boundary_io_control().
chk_read_boundary_files()
integer(kind = kint) function, private check_read_bc_file::chk_read_boundary_files (type(fluid_property), intent(in) fl_prop, type(conductive_property), intent(in) cd_prop, type(scalar_property), intent(in) ht_prop, type(scalar_property), intent(in) cp_prop, type(mhd_bc_lists), intent(in) MHD_BC) private
Definition at line 56 of file check_read_bc_file.f90.
References t_physical_property::id_no_evolution, and set_serch_boundary_file_flag().
Referenced by check_read_boundary_files().
set_serch_boundary_file_flag()
subroutine, private check_read_bc_file::set_serch_boundary_file_flag (integer (kind = kint), intent(inout) iflag, type(boundary_condition_list), intent(in) bc_list) private
Definition at line 151 of file check_read_bc_file.f90.
Referenced by chk_read_boundary_files().
Variable Documentation
id_no_boundary_file
integer (kind=kint), parameter check_read_bc_file::id_no_boundary_file = 0
ID not to read external boundary condition file.
Definition at line 24 of file check_read_bc_file.f90.
Referenced by set_control_4_sph_to_fem::sph_boundary_io_control().
id_read_boundary_file
integer (kind=kint), parameter check_read_bc_file::id_read_boundary_file = 1
ID to read external boundary condition file.
Definition at line 26 of file check_read_bc_file.f90.