CALYPSO: legendre_fwd_sym_matmul Module Reference
legendre_fwd_sym_matmul Module Reference
forward Legendre transform useing mat multi
data are strored communication buffer
Functions/Subroutines
subroutine leg_f_trans_vec_sym_matmul (iflag_matmul, ncomp, nvector, sph_rtm, sph_rlm, comm_rtm, comm_rlm, idx_trns, asin_theta_1d_rtm, g_sph_rlm, weight_rtm, n_WR, n_WS, WR, WS, WK_l_sml)
subroutine leg_f_trans_scl_sym_matmul (iflag_matmul, ncomp, nvector, nscalar, sph_rtm, sph_rlm, comm_rtm, comm_rlm, idx_trns, g_sph_rlm, weight_rtm, n_WR, n_WS, WR, WS, WK_l_sml)
Variables
real(kind=kreal), private st_elapsed
real(kind=kreal), dimension(4), private elaps
integer, external omp_get_max_threads
Detailed Description
forward Legendre transform useing mat multi
data are strored communication buffer
      subroutine leg_f_trans_vec_sym_matmul                           &
     &         (iflag_matmul, ncomp, nvector,                         &
     &          sph_rtm, sph_rlm, comm_rtm, comm_rlm, idx_trns,       &
     &          asin_theta_1d_rtm, g_sph_rlm, weight_rtm,             &
     &          n_WR, n_WS, WR, WS, WK_l_sml)
      subroutine leg_f_trans_scl_sym_matmul                           &
     &         (iflag_matmul, ncomp, nvector, nscalar,                &
     &          sph_rtm, sph_rlm, comm_rtm, comm_rlm, idx_trns,       &
     &          g_sph_rlm, weight_rtm, n_WR, n_WS, WR, WS, WK_l_sml)
        type(sph_rtm_grid), intent(in) :: sph_rtm
        type(sph_rlm_grid), intent(in) :: sph_rlm
        type(sph_comm_tbl), intent(in) :: comm_rtm, comm_rlm
        type(index_4_sph_trans), intent(in) :: idx_trns
        type(leg_trns_sym_mul_work), intent(inout) :: WK_l_sml
        Input:  vr_rtm
        Output: sp_rlm
     field data for Legendre transform
       original layout: vr_rtm(l_rtm,m_rtm,k_rtm,icomp)
       size: vr_rtm(nidx_rtm(2),nidx_rtm(1)*ncomp,nidx_rtm(3))
      real(kind = kreal), allocatable :: vr_rtm(:,:,:)
     spectr data for Legendre transform
       original layout: sp_rlm(j_rlm,k_rtm,icomp)
        size: sp_rlm(nidx_rlm(2),nidx_rtm(1)*ncomp)
      real(kind = kreal), allocatable :: sp_rlm(:,:)
Parameters
ncomp Total number of components for spherical transform
nvector Number of vector for spherical transform
nscalar Number of scalar (including tensor components) for spherical transform
Function/Subroutine Documentation
leg_f_trans_scl_sym_matmul()
subroutine legendre_fwd_sym_matmul::leg_f_trans_scl_sym_matmul (integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_comm_tbl), intent(in) comm_rtm, type(sph_comm_tbl), intent(in) comm_rlm, type(index_4_sph_trans), intent(in) idx_trns, real(kind = kreal), dimension(sph_rlm%nidx_rlm(2),17), intent(in) g_sph_rlm, real(kind = kreal), dimension(sph_rtm%nidx_rtm(2)), intent(in) weight_rtm, integer(kind = kint), intent(in) n_WR, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_wr), intent(inout) WR, real (kind=kreal), dimension(n_ws), intent(inout) WS, type(leg_trns_sym_mul_work), intent(inout) WK_l_sml)
Definition at line 215 of file legendre_fwd_sym_matmul.f90.
References set_sp_rlm_leg_sym_matmul::cal_sp_rlm_scalar_sym_matmul(), elaps, matmul_for_legendre_trans::matmul_fwd_leg_trans(), and set_vr_rtm_leg_sym_matmul::set_vr_rtm_scalar_sym_matmul().
Referenced by legendre_trans_sym_matmul::leg_forward_trans_sym_matmul().
leg_f_trans_vec_sym_matmul()
subroutine legendre_fwd_sym_matmul::leg_f_trans_vec_sym_matmul (integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_comm_tbl), intent(in) comm_rtm, type(sph_comm_tbl), intent(in) comm_rlm, type(index_4_sph_trans), intent(in) idx_trns, real(kind = kreal), dimension(sph_rtm%nidx_rtm(2)), intent(in) asin_theta_1d_rtm, real(kind = kreal), dimension(sph_rlm%nidx_rlm(2),17), intent(in) g_sph_rlm, real(kind = kreal), dimension(sph_rtm%nidx_rtm(2)), intent(in) weight_rtm, integer(kind = kint), intent(in) n_WR, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_wr), intent(inout) WR, real (kind=kreal), dimension(n_ws), intent(inout) WS, type(leg_trns_sym_mul_work), intent(inout) WK_l_sml)
Definition at line 74 of file legendre_fwd_sym_matmul.f90.
References set_sp_rlm_leg_sym_matmul::cal_sp_rlm_vector_sym_matmul(), elaps, matmul_for_legendre_trans::matmul_fwd_leg_trans(), and set_vr_rtm_leg_sym_matmul::set_vr_rtm_vector_sym_matmul().
Referenced by legendre_trans_sym_matmul::leg_forward_trans_sym_matmul().
Variable Documentation
elaps
real(kind = kreal), dimension(4), private legendre_fwd_sym_matmul::elaps private
Definition at line 65 of file legendre_fwd_sym_matmul.f90.
Referenced by leg_f_trans_scl_sym_matmul(), and leg_f_trans_vec_sym_matmul().
omp_get_max_threads
integer, external legendre_fwd_sym_matmul::omp_get_max_threads
Definition at line 66 of file legendre_fwd_sym_matmul.f90.
st_elapsed
real(kind = kreal), private legendre_fwd_sym_matmul::st_elapsed private
Definition at line 64 of file legendre_fwd_sym_matmul.f90.