CALYPSO: quicksort Module Reference
quicksort Module Reference
Functions/Subroutines
recursive subroutine quicksort_int (n, ix, l, r)
recursive subroutine quicksort_w_index (n, ix, l, r, idx)
recursive subroutine quicksort_int8_w_index (n, i8x, l, r, idx)
recursive subroutine quicksort_real_w_index (n, x, l, r, idx)
subroutine, private swap (a, b)
subroutine, private swap_real (a, b)
subroutine swap_i8 (a, b)
subroutine swap_coord (a, b)
integer(kind=kint) function, private comp_coord (a, b)
recursive subroutine quicksort_coord_w_index (n, xx, l, r, idx)
Function/Subroutine Documentation
comp_coord()
integer(kind = kint) function, private quicksort::comp_coord (real(kind = kreal), dimension(3), intent(in) a, real(kind = kreal), dimension(3), intent(in) b) private
Definition at line 211 of file quicksort.f90.
Referenced by quicksort_coord_w_index().
quicksort_coord_w_index()
recursive subroutine quicksort::quicksort_coord_w_index (integer (kind=kint), intent(in) n, real (kind=kreal), dimension(n,3), intent(inout) xx, integer (kind=kint), intent(in) l, integer (kind=kint), intent(in) r, integer (kind=kint), dimension(n), intent(inout) idx)
Definition at line 233 of file quicksort.f90.
References comp_coord(), quicksort_real_w_index(), swap(), and swap_coord().
quicksort_int()
recursive subroutine quicksort::quicksort_int (integer (kind=kint), intent(in) n, integer (kind=kint), dimension(n), intent(inout) ix, integer (kind=kint), intent(in) l, integer (kind=kint), intent(in) r)
Definition at line 39 of file quicksort.f90.
References swap().
Referenced by normgi_by_primes::conut_prims_normgi(), normgi_by_fact::gs_fact(), normgi_by_fact::gs_mul_fact(), normgi_by_primes::gs_prime(), cal_rms_fields_by_sph::init_rms_4_sph_spectr(), and pickup_sph_coefs::init_sph_radial_monitor_list().
quicksort_int8_w_index()
recursive subroutine quicksort::quicksort_int8_w_index (integer (kind=kint), intent(in) n, integer (kind=kint_gl), dimension(n), intent(inout) i8x, integer (kind=kint), intent(in) l, integer (kind=kint), intent(in) r, integer (kind=kint), dimension(n), intent(inout) idx)
Definition at line 95 of file quicksort.f90.
References swap(), and swap_i8().
quicksort_real_w_index()
recursive subroutine quicksort::quicksort_real_w_index (integer (kind=kint), intent(in) n, real (kind=kreal), dimension(n), intent(inout) x, integer (kind=kint), intent(in) l, integer (kind=kint), intent(in) r, integer (kind=kint), dimension(n), intent(inout) idx)
Definition at line 125 of file quicksort.f90.
References swap(), and swap_real().
Referenced by quicksort_coord_w_index(), and t_belonged_element_4_node::sort_inod_4_ele_by_position().
quicksort_w_index()
recursive subroutine quicksort::quicksort_w_index (integer (kind=kint), intent(in) n, integer (kind=kint), dimension(n), intent(inout) ix, integer (kind=kint), intent(in) l, integer (kind=kint), intent(in) r, integer (kind=kint), dimension(n), intent(inout) idx)
Definition at line 65 of file quicksort.f90.
References swap().
Referenced by find_element_id_4_node::set_iele_4_node(), pickup_sph_spectr::set_picked_sph_address(), and find_node_4_group::sort_next_node_list_by_weight().
swap()
subroutine, private quicksort::swap (integer(kind = kint), intent(inout) a, integer(kind = kint), intent(inout) b) private
Definition at line 156 of file quicksort.f90.
Referenced by quicksort_coord_w_index(), quicksort_int(), quicksort_int8_w_index(), quicksort_real_w_index(), and quicksort_w_index().
swap_coord()
subroutine quicksort::swap_coord (real(kind = kreal), dimension(3), intent(inout) a, real(kind = kreal), dimension(3), intent(inout) b)
Definition at line 195 of file quicksort.f90.
Referenced by quicksort_coord_w_index().
swap_i8()
subroutine quicksort::swap_i8 (integer(kind = kint_gl), intent(inout) a, integer(kind = kint_gl), intent(inout) b)
Definition at line 182 of file quicksort.f90.
Referenced by quicksort_int8_w_index().
swap_real()
subroutine, private quicksort::swap_real (real(kind = kreal), intent(inout) a, real(kind = kreal), intent(inout) b) private
Definition at line 169 of file quicksort.f90.
Referenced by quicksort_real_w_index().