CALYPSO: const_grp_edge_4_viewer Module Reference
const_grp_edge_4_viewer Module Reference
Functions/Subroutines
subroutine construct_edge_4_ele_grp (nnod_4_surf, view_mesh, ngrp_ele_sf, ele_surf_grp, ele_edge_grp, edge_sf_tbl)
subroutine construct_edge_4_surf_grp (nnod_4_surf, view_mesh, ngrp_surf_sf, sf_surf_grp, sf_edge_grp, edge_sf_tbl)
subroutine, private allocate_ele_edge_item_tmp (ele_edge_grp)
subroutine, private allocate_sf_edge_item_tmp (sf_edge_grp)
subroutine, private deallocate_ele_edge_item_tmp
subroutine, private deallocate_sf_edge_item_tmp
Variables
integer(kind=kint), dimension(:), allocatable, private ele_edge_item_tmp
integer(kind=kint), dimension(:), allocatable, private surf_edge_item_tmp
Function/Subroutine Documentation
allocate_ele_edge_item_tmp()
subroutine, private const_grp_edge_4_viewer::allocate_ele_edge_item_tmp (type(viewer_group_data), intent(in) ele_edge_grp) private
Definition at line 178 of file const_grp_edge_4_viewer.f90.
References ele_edge_item_tmp.
Referenced by construct_edge_4_ele_grp().
allocate_sf_edge_item_tmp()
subroutine, private const_grp_edge_4_viewer::allocate_sf_edge_item_tmp (type(viewer_group_data), intent(in) sf_edge_grp) private
Definition at line 189 of file const_grp_edge_4_viewer.f90.
References surf_edge_item_tmp.
Referenced by construct_edge_4_surf_grp().
construct_edge_4_ele_grp()
subroutine const_grp_edge_4_viewer::construct_edge_4_ele_grp (integer(kind = kint), intent(in) nnod_4_surf, type(viewer_mesh_data), intent(in) view_mesh, integer(kind = kint), intent(in) ngrp_ele_sf, type(viewer_group_data), intent(in) ele_surf_grp, type(viewer_group_data), intent(inout) ele_edge_grp, type(sum_hash_tbl), intent(inout) edge_sf_tbl)
Definition at line 44 of file const_grp_edge_4_viewer.f90.
References t_viewer_group::alloc_merged_group_item(), allocate_ele_edge_item_tmp(), t_sum_hash::clear_sum_hash(), set_edge_hash_by_sf::const_part_edge_hash_4_sf(), set_edge_data_by_sf::count_num_edges_by_sf(), t_viewer_group::dealloc_merged_group_item(), deallocate_ele_edge_item_tmp(), ele_edge_item_tmp, and set_edge_data_by_sf::set_part_edges_4_sf().
Referenced by const_edge_4_viewer::construct_edge_4_viewer().
construct_edge_4_surf_grp()
subroutine const_grp_edge_4_viewer::construct_edge_4_surf_grp (integer(kind = kint), intent(in) nnod_4_surf, type(viewer_mesh_data), intent(in) view_mesh, integer(kind = kint), intent(in) ngrp_surf_sf, type(viewer_group_data), intent(in) sf_surf_grp, type(viewer_group_data), intent(inout) sf_edge_grp, type(sum_hash_tbl), intent(inout) edge_sf_tbl)
Definition at line 113 of file const_grp_edge_4_viewer.f90.
References t_viewer_group::alloc_merged_group_item(), allocate_sf_edge_item_tmp(), t_sum_hash::clear_sum_hash(), set_edge_hash_by_sf::const_part_edge_hash_4_sf(), set_edge_data_by_sf::count_num_edges_by_sf(), t_viewer_group::dealloc_merged_group_item(), deallocate_sf_edge_item_tmp(), set_edge_data_by_sf::set_part_edges_4_sf(), and surf_edge_item_tmp.
Referenced by const_edge_4_viewer::construct_edge_4_viewer().
deallocate_ele_edge_item_tmp()
subroutine, private const_grp_edge_4_viewer::deallocate_ele_edge_item_tmp private
Definition at line 200 of file const_grp_edge_4_viewer.f90.
References ele_edge_item_tmp.
Referenced by construct_edge_4_ele_grp().
deallocate_sf_edge_item_tmp()
subroutine, private const_grp_edge_4_viewer::deallocate_sf_edge_item_tmp private
Definition at line 208 of file const_grp_edge_4_viewer.f90.
References surf_edge_item_tmp.
Referenced by construct_edge_4_surf_grp().
Variable Documentation
ele_edge_item_tmp
integer(kind=kint), dimension(:), allocatable, private const_grp_edge_4_viewer::ele_edge_item_tmp private
Definition at line 29 of file const_grp_edge_4_viewer.f90.
Referenced by allocate_ele_edge_item_tmp(), construct_edge_4_ele_grp(), and deallocate_ele_edge_item_tmp().
surf_edge_item_tmp
integer(kind=kint), dimension(:), allocatable, private const_grp_edge_4_viewer::surf_edge_item_tmp private
Definition at line 30 of file const_grp_edge_4_viewer.f90.
Referenced by allocate_sf_edge_item_tmp(), construct_edge_4_surf_grp(), and deallocate_sf_edge_item_tmp().