CALYPSO: set_surf_connect_4_viewer Module Reference
set_surf_connect_4_viewer Module Reference
Functions/Subroutines
subroutine s_set_surf_connect_4_viewer (group, surf, mgd_sf_grp, view_mesh, domain_grps, view_ele_grps, view_sf_grps)
subroutine, private s_set_groups_4_viewer_surface (group, surf, mgd_sf_grp, nsurf_viewer, domain_grps, view_ele_grps, view_sf_grps)
Function/Subroutine Documentation
s_set_groups_4_viewer_surface()
subroutine, private set_surf_connect_4_viewer::s_set_groups_4_viewer_surface (type(mesh_groups), intent(in) group, type(surface_data), intent(in) surf, type(viewer_ele_grp_surface), intent(in) mgd_sf_grp, integer(kind = kint), intent(in) nsurf_viewer, type(viewer_surface_groups), intent(inout) domain_grps, type(viewer_surface_groups), intent(inout) view_ele_grps, type(viewer_surface_groups), intent(inout) view_sf_grps) private
Definition at line 77 of file set_surf_connect_4_viewer.f90.
References pickup_surface_4_viewer::set_element_group_item_viewer(), renumber_surface_4_viewer::set_element_group_stack_viewer(), pickup_surface_4_viewer::set_surf_domain_item_viewer(), renumber_surface_4_viewer::set_surf_domain_stack_viewer(), pickup_surface_4_viewer::set_surface_group_item_viewer(), and renumber_surface_4_viewer::set_surface_group_stack_viewer().
Referenced by s_set_surf_connect_4_viewer().
s_set_surf_connect_4_viewer()
subroutine set_surf_connect_4_viewer::s_set_surf_connect_4_viewer (type(mesh_groups), intent(in) group, type(surface_data), intent(inout) surf, type(viewer_ele_grp_surface), intent(inout) mgd_sf_grp, type(viewer_mesh_data), intent(inout) view_mesh, type(viewer_surface_groups), intent(inout) domain_grps, type(viewer_surface_groups), intent(inout) view_ele_grps, type(viewer_surface_groups), intent(inout) view_sf_grps)
Definition at line 34 of file set_surf_connect_4_viewer.f90.
References t_viewer_mesh::alloc_surf_connect_viewer(), pickup_surface_4_viewer::allocate_imark_surf(), pickup_surface_4_viewer::allocate_sf_cvt_table_viewer(), pickup_surface_4_viewer::count_used_surface_4_viewer(), pickup_surface_4_viewer::deallocate_imark_surf(), pickup_surface_4_viewer::deallocate_sf_cvt_table_viewer(), pickup_surface_4_viewer::mark_used_surface_4_viewer(), s_set_groups_4_viewer_surface(), pickup_surface_4_viewer::set_surf_connect_viewer(), and pickup_surface_4_viewer::set_surf_cvt_table_viewer().
Referenced by const_kemoview_mesh::const_surf_mesh_4_viewer().