CALYPSO: set_surface_group_types Module Reference
set_surface_group_types Module Reference
set surface boundary condition flags from conterol input
Functions/Subroutines
subroutine set_surf_group_types_scalar (bc_type_ctl, ibc_type)
subroutine set_surf_group_types_vector (bc_type_ctl, ibc_type)
subroutine set_stress_free_group_types (bc_type_ctl, ibc_type)
subroutine set_surf_wall_group_types (bc_type_ctl, ibc_type)
subroutine set_pseudo_vacuum_group_types (bc_type_ctl, ibc_type)
subroutine set_surf_infty_group_types (bc_type_ctl, ibc_type)
Variables
character(len=kchara), parameter, private grad_sf = 'grad'
control name for fixed normal gradient by control
character(len=kchara), parameter, private gradient_sf = 'gradient'
control name for fixed normal gradient by control
character(len=kchara), parameter grad_ctl = 'grad_ctl'
control name for fixed normal gradient by control
character(len=kchara), parameter, private grad_file = 'grad_file'
control name for fixed normal gradient by external file
character(len=kchara), parameter, private grad_lead = 'lead_grad'
control name for fixed normal gradient by program
character(len=kchara), parameter fixed_norm = 'fix_norm'
control name for fixed normal gradient by control
character(len=kchara), parameter norm_ctl = 'fix_norm_ctl'
control name for fixed normal gradient by control
character(len=kchara), parameter norm_file = 'fix_norm_dat'
control name for fixed normal gradient by external file
character(len=kchara), parameter, private fixed_grad_x = 'grad_x'
control name for fixed gradient of x-componenet by control
character(len=kchara), parameter, private fixed_grad_y = 'grad_y'
control name for fixed gradient of y-componenet by control
character(len=kchara), parameter, private fixed_grad_z = 'grad_z'
control name for fixed gradient of z-componenet by control
character(len=kchara), parameter, private grad_ctl_x = 'grad_ctl_x'
control name for fixed gradient of x-componenet by control
character(len=kchara), parameter, private grad_ctl_y = 'grad_ctl_y'
control name for fixed gradient of y-componenet by control
character(len=kchara), parameter, private grad_ctl_z = 'grad_ctl_z'
control name for fixed gradient of z-componenet by control
character(len=kchara), parameter, private grad_file_x = 'grad_file_x'
control name for fixed gradient of x-componenet by external file
character(len=kchara), parameter, private grad_file_y = 'grad_file_y'
control name for fixed gradient of y-componenet by external file
character(len=kchara), parameter, private grad_file_z = 'grad_file_z'
control name for fixed gradient of z-componenet by external file
character(len=kchara), parameter, private grad_lead_x = 'lead_grad_x'
control name for fixed gradient of x-componenet by program
character(len=kchara), parameter, private grad_lead_y = 'lead_grad_y'
control name for fixed gradient of y-componenet by program
character(len=kchara), parameter, private grad_lead_z = 'lead_grad_z'
control name for fixed gradient of z-componenet by program
character(len=kchara), parameter, private free_sph_in = 'free_shell_in'
control name for inner sphere boundary
character(len=kchara), parameter, private free_sph_out = 'free_shell_out'
control name for outer sphere boundary
character(len=kchara), parameter, private wall_surf = 'wall'
control name for wall boundary
character(len=kchara), parameter, private sphere_in = 'sph_in'
control name for inner sphere boundary
character(len=kchara), parameter, private sphere_out = 'sph_out'
control name for outer sphere boundary
character(len=kchara), parameter, private pseudo_in = 'pseudo_vacuum_in'
control name for inner pseduo vacuum boundary
character(len=kchara), parameter, private pseudo_out = 'pseudo_vacuum_out'
control name for outer pseduo vacuum boundary
character(len=kchara), parameter, private infty_surf = 'infinity'
control name for infinity surface
Detailed Description
set surface boundary condition flags from conterol input
      subroutine set_surf_group_types_scalar(bc_type_ctl, ibc_type)
      subroutine set_surf_group_types_vector(bc_type_ctl, ibc_type)
      subroutine set_stress_free_group_types(bc_type_ctl, ibc_type)
      subroutine set_pseudo_vacuum_group_types(bc_type_ctl, ibc_type)
      subroutine set_surf_wall_group_types(bc_type_ctl, ibc_type)
      subroutine set_surf_infty_group_types(bc_type_ctl, ibc_type)
Function/Subroutine Documentation
set_pseudo_vacuum_group_types()
subroutine set_surface_group_types::set_pseudo_vacuum_group_types (character (len=kchara), intent(in) bc_type_ctl, integer(kind = kint), intent(inout) ibc_type)
Definition at line 210 of file set_surface_group_types.f90.
References skip_comment_f::cmp_no_case(), m_boundary_condition_ids::iflag_surf_qvc_sph_in, m_boundary_condition_ids::iflag_surf_qvc_sph_out, pseudo_in, and pseudo_out.
set_stress_free_group_types()
subroutine set_surface_group_types::set_stress_free_group_types (character (len=kchara), intent(in) bc_type_ctl, integer(kind = kint), intent(inout) ibc_type)
Definition at line 176 of file set_surface_group_types.f90.
References skip_comment_f::cmp_no_case(), free_sph_in, free_sph_out, m_boundary_condition_ids::iflag_surf_free_sph_in, and m_boundary_condition_ids::iflag_surf_free_sph_out.
Referenced by set_control_4_velo::s_set_control_4_velo().
set_surf_group_types_scalar()
subroutine set_surface_group_types::set_surf_group_types_scalar (character (len=kchara), intent(in) bc_type_ctl, integer(kind = kint), intent(inout) ibc_type)
Definition at line 109 of file set_surface_group_types.f90.
References skip_comment_f::cmp_no_case(), grad_ctl, grad_file, grad_lead, grad_sf, gradient_sf, m_boundary_condition_ids::iflag_fixed_grad_s, m_boundary_condition_ids::iflag_lead_grad_s, set_node_group_types::set_bc_group_types_scalar(), and set_node_group_types::set_bc_group_types_sgs_scalar().
Referenced by set_control_4_composition::s_set_control_4_composition(), set_control_4_press::s_set_control_4_press(), and set_control_4_temp::s_set_control_4_temp().
set_surf_group_types_vector()
subroutine set_surface_group_types::set_surf_group_types_vector (character (len=kchara), intent(in) bc_type_ctl, integer(kind = kint), intent(inout) ibc_type)
Definition at line 133 of file set_surface_group_types.f90.
References skip_comment_f::cmp_no_case(), fixed_grad_x, fixed_grad_y, fixed_grad_z, fixed_norm, grad_ctl_x, grad_ctl_y, grad_ctl_z, grad_file_x, grad_file_y, grad_file_z, grad_lead_x, grad_lead_y, grad_lead_z, m_boundary_condition_ids::iflag_fixed_grad_x, m_boundary_condition_ids::iflag_fixed_grad_y, m_boundary_condition_ids::iflag_fixed_grad_z, m_boundary_condition_ids::iflag_fixed_norm, m_boundary_condition_ids::iflag_lead_grad_x, m_boundary_condition_ids::iflag_lead_grad_y, m_boundary_condition_ids::iflag_lead_grad_z, norm_ctl, norm_file, set_node_group_types::set_bc_group_types_sgs_vect(), and set_node_group_types::set_bc_group_types_vector().
Referenced by set_control_4_magne::s_set_control_4_magne(), and set_control_4_velo::s_set_control_4_velo().
set_surf_infty_group_types()
subroutine set_surface_group_types::set_surf_infty_group_types (character (len=kchara), intent(in) bc_type_ctl, integer(kind = kint), intent(inout) ibc_type)
Definition at line 226 of file set_surface_group_types.f90.
References skip_comment_f::cmp_no_case(), m_boundary_condition_ids::iflag_surf_infty, and infty_surf.
set_surf_wall_group_types()
subroutine set_surface_group_types::set_surf_wall_group_types (character (len=kchara), intent(in) bc_type_ctl, integer(kind = kint), intent(inout) ibc_type)
Definition at line 192 of file set_surface_group_types.f90.
References skip_comment_f::cmp_no_case(), m_boundary_condition_ids::iflag_surf_sph_in, m_boundary_condition_ids::iflag_surf_sph_out, m_boundary_condition_ids::iflag_surf_wall, sphere_in, sphere_out, and wall_surf.
Referenced by set_control_4_press::s_set_control_4_press().
Variable Documentation
fixed_grad_x
character(len = kchara), parameter, private set_surface_group_types::fixed_grad_x = 'grad_x' private
control name for fixed gradient of x-componenet by control
Definition at line 46 of file set_surface_group_types.f90.
Referenced by set_surf_group_types_vector().
fixed_grad_y
character(len = kchara), parameter, private set_surface_group_types::fixed_grad_y = 'grad_y' private
control name for fixed gradient of y-componenet by control
Definition at line 48 of file set_surface_group_types.f90.
Referenced by set_surf_group_types_vector().
fixed_grad_z
character(len = kchara), parameter, private set_surface_group_types::fixed_grad_z = 'grad_z' private
control name for fixed gradient of z-componenet by control
Definition at line 50 of file set_surface_group_types.f90.
Referenced by set_surf_group_types_vector().
fixed_norm
character(len = kchara), parameter set_surface_group_types::fixed_norm = 'fix_norm'
control name for fixed normal gradient by control
Definition at line 39 of file set_surface_group_types.f90.
Referenced by set_surf_group_types_vector().
free_sph_in
character(len = kchara), parameter, private set_surface_group_types::free_sph_in = 'free_shell_in' private
control name for inner sphere boundary
Definition at line 73 of file set_surface_group_types.f90.
Referenced by set_stress_free_group_types().
free_sph_out
character(len = kchara), parameter, private set_surface_group_types::free_sph_out = 'free_shell_out' private
control name for outer sphere boundary
Definition at line 76 of file set_surface_group_types.f90.
Referenced by set_stress_free_group_types().
grad_ctl
character(len = kchara), parameter set_surface_group_types::grad_ctl = 'grad_ctl'
control name for fixed normal gradient by control
Definition at line 32 of file set_surface_group_types.f90.
Referenced by set_surf_group_types_scalar().
grad_ctl_x
character(len = kchara), parameter, private set_surface_group_types::grad_ctl_x = 'grad_ctl_x' private
control name for fixed gradient of x-componenet by control
Definition at line 52 of file set_surface_group_types.f90.
Referenced by set_surf_group_types_vector().
grad_ctl_y
character(len = kchara), parameter, private set_surface_group_types::grad_ctl_y = 'grad_ctl_y' private
control name for fixed gradient of y-componenet by control
Definition at line 54 of file set_surface_group_types.f90.
Referenced by set_surf_group_types_vector().
grad_ctl_z
character(len = kchara), parameter, private set_surface_group_types::grad_ctl_z = 'grad_ctl_z' private
control name for fixed gradient of z-componenet by control
Definition at line 56 of file set_surface_group_types.f90.
Referenced by set_surf_group_types_vector().
grad_file
character(len = kchara), parameter, private set_surface_group_types::grad_file = 'grad_file' private
control name for fixed normal gradient by external file
Definition at line 34 of file set_surface_group_types.f90.
Referenced by set_surf_group_types_scalar().
grad_file_x
character(len = kchara), parameter, private set_surface_group_types::grad_file_x = 'grad_file_x' private
control name for fixed gradient of x-componenet by external file
Definition at line 59 of file set_surface_group_types.f90.
Referenced by set_surf_group_types_vector().
grad_file_y
character(len = kchara), parameter, private set_surface_group_types::grad_file_y = 'grad_file_y' private
control name for fixed gradient of y-componenet by external file
Definition at line 61 of file set_surface_group_types.f90.
Referenced by set_surf_group_types_vector().
grad_file_z
character(len = kchara), parameter, private set_surface_group_types::grad_file_z = 'grad_file_z' private
control name for fixed gradient of z-componenet by external file
Definition at line 63 of file set_surface_group_types.f90.
Referenced by set_surf_group_types_vector().
grad_lead
character(len = kchara), parameter, private set_surface_group_types::grad_lead = 'lead_grad' private
control name for fixed normal gradient by program
Definition at line 36 of file set_surface_group_types.f90.
Referenced by set_surf_group_types_scalar().
grad_lead_x
character(len = kchara), parameter, private set_surface_group_types::grad_lead_x = 'lead_grad_x' private
control name for fixed gradient of x-componenet by program
Definition at line 66 of file set_surface_group_types.f90.
Referenced by set_surf_group_types_vector().
grad_lead_y
character(len = kchara), parameter, private set_surface_group_types::grad_lead_y = 'lead_grad_y' private
control name for fixed gradient of y-componenet by program
Definition at line 68 of file set_surface_group_types.f90.
Referenced by set_surf_group_types_vector().
grad_lead_z
character(len = kchara), parameter, private set_surface_group_types::grad_lead_z = 'lead_grad_z' private
control name for fixed gradient of z-componenet by program
Definition at line 70 of file set_surface_group_types.f90.
Referenced by set_surf_group_types_vector().
grad_sf
character(len = kchara), parameter, private set_surface_group_types::grad_sf = 'grad' private
control name for fixed normal gradient by control
Definition at line 28 of file set_surface_group_types.f90.
Referenced by set_surf_group_types_scalar().
gradient_sf
character(len = kchara), parameter, private set_surface_group_types::gradient_sf = 'gradient' private
control name for fixed normal gradient by control
Definition at line 30 of file set_surface_group_types.f90.
Referenced by set_surf_group_types_scalar().
infty_surf
character(len = kchara), parameter, private set_surface_group_types::infty_surf = 'infinity' private
control name for infinity surface
Definition at line 94 of file set_surface_group_types.f90.
Referenced by set_surf_infty_group_types().
norm_ctl
character(len = kchara), parameter set_surface_group_types::norm_ctl = 'fix_norm_ctl'
control name for fixed normal gradient by control
Definition at line 41 of file set_surface_group_types.f90.
Referenced by set_surf_group_types_vector().
norm_file
character(len = kchara), parameter set_surface_group_types::norm_file = 'fix_norm_dat'
control name for fixed normal gradient by external file
Definition at line 43 of file set_surface_group_types.f90.
Referenced by set_surf_group_types_vector().
pseudo_in
character(len = kchara), parameter, private set_surface_group_types::pseudo_in = 'pseudo_vacuum_in' private
control name for inner pseduo vacuum boundary
Definition at line 87 of file set_surface_group_types.f90.
Referenced by set_pseudo_vacuum_group_types().
pseudo_out
character(len = kchara), parameter, private set_surface_group_types::pseudo_out = 'pseudo_vacuum_out' private
control name for outer pseduo vacuum boundary
Definition at line 90 of file set_surface_group_types.f90.
Referenced by set_pseudo_vacuum_group_types().
sphere_in
character(len = kchara), parameter, private set_surface_group_types::sphere_in = 'sph_in' private
control name for inner sphere boundary
Definition at line 82 of file set_surface_group_types.f90.
Referenced by set_surf_wall_group_types().
sphere_out
character(len = kchara), parameter, private set_surface_group_types::sphere_out = 'sph_out' private
control name for outer sphere boundary
Definition at line 84 of file set_surface_group_types.f90.
Referenced by set_surf_wall_group_types().
wall_surf
character(len = kchara), parameter, private set_surface_group_types::wall_surf = 'wall' private
control name for wall boundary
Definition at line 80 of file set_surface_group_types.f90.
Referenced by set_surf_wall_group_types().