CALYPSO: cal_explicit_terms Module Reference
cal_explicit_terms Module Reference
Evaluate time evolution of induction by explicit scheme.
Functions/Subroutines
subroutine cal_diff_induction_mhd_adams (cd_prop, ipol_base, ipol_exp, ipol_frc, ipol_dif, dt, nnod_rj, ntot_phys_rj, d_rj)
subroutine cal_diff_induction_mhd_euler (cd_prop, ipol_base, ipol_frc, ipol_dif, dt, nnod_rj, ntot_phys_rj, d_rj)
subroutine set_ini_adams_mag_induct (ipol_exp, ipol_frc, nnod_rj, ntot_phys_rj, d_rj)
Detailed Description
Evaluate time evolution of induction by explicit scheme.
      subroutine cal_diff_induction_MHD_adams                         &
     &         (cd_prop, ipol_base, ipol_exp, ipol_frc, ipol_dif, dt, &
     &          nnod_rj, ntot_phys_rj, d_rj)
      subroutine cal_diff_induction_MHD_euler                         &
     &         (cd_prop, ipol_base, ipol_frc, ipol_dif, dt,           &
     &          nnod_rj, ntot_phys_rj, d_rj)
      subroutine set_ini_adams_mag_induct                             &
     &         (ipol_exp, ipol_frc, nnod_rj, ntot_phys_rj, d_rj)
        type(conductive_property), intent(in) :: cd_prop
        type(base_field_address), intent(in) :: ipol_base
        type(explicit_term_address), intent(in) :: ipol_exp
        type(base_force_address), intent(in) :: ipol_frc
        type(diffusion_address), intent(in) :: ipol_dif
Function/Subroutine Documentation
cal_diff_induction_mhd_adams()
subroutine cal_explicit_terms::cal_diff_induction_mhd_adams (type(conductive_property), intent(in) cd_prop, type(base_field_address), intent(in) ipol_base, type(explicit_term_address), intent(in) ipol_exp, type(base_force_address), intent(in) ipol_frc, type(diffusion_address), intent(in) ipol_dif, real(kind = kreal), intent(in) dt, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 44 of file cal_explicit_terms.f90.
References m_t_step_parameter::adam_0, and m_t_step_parameter::adam_1.
Referenced by cal_momentum_eq_explicit::cal_explicit_sph_adams().
cal_diff_induction_mhd_euler()
subroutine cal_explicit_terms::cal_diff_induction_mhd_euler (type(conductive_property), intent(in) cd_prop, type(base_field_address), intent(in) ipol_base, type(base_force_address), intent(in) ipol_frc, type(diffusion_address), intent(in) ipol_dif, real(kind = kreal), intent(in) dt, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 82 of file cal_explicit_terms.f90.
Referenced by cal_momentum_eq_explicit::cal_explicit_sph_euler().
set_ini_adams_mag_induct()
subroutine cal_explicit_terms::set_ini_adams_mag_induct (type(explicit_term_address), intent(in) ipol_exp, type(base_force_address), intent(in) ipol_frc, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 113 of file cal_explicit_terms.f90.
Referenced by cal_momentum_eq_explicit::cal_first_prev_step_adams().