CALYPSO: t_ctl_data_mhd_model Module Reference
t_ctl_data_mhd_model Module Reference
Data Types
type mhd_dns_model_control
Functions/Subroutines
subroutine read_sph_mhd_model (id_control, hd_block, Dmodel_ctl, c_buf)
subroutine bcast_sph_mhd_model (Dmodel_ctl)
subroutine dealloc_sph_mhd_model (Dmodel_ctl)
Variables
character(len=kchara), parameter, private hd_phys_values = 'phys_values_ctl'
character(len=kchara), parameter, private hd_time_evo = 'time_evolution_ctl'
character(len=kchara), parameter, private hd_layers_ctl = 'layers_ctl'
character(len=kchara), parameter, private hd_bc_4_node = 'bc_4_node'
character(len=kchara), parameter, private hd_boundary_condition = 'boundary_condition'
character(len=kchara), parameter, private hd_dimless_ctl = 'dimensionless_ctl'
character(len=kchara), parameter, private hd_coef_term_ctl ='coefficients_ctl'
character(len=kchara), parameter, private hd_forces_ctl = 'forces_define'
character(len=kchara), parameter, private hd_gravity_ctl = 'gravity_define'
character(len=kchara), parameter, private hd_coriolis_ctl = 'Coriolis_define'
character(len=kchara), parameter, private hd_induction_ctl = 'magnetic_induciton_ctl'
character(len=kchara), parameter, private hd_magneto_ctl = 'Magneto_convection_def'
character(len=kchara), parameter, private hd_temp_def = 'temperature_define'
character(len=kchara), parameter, private hd_comp_def = 'composition_define'
character(len=kchara), parameter, private hd_bc_4_surf = 'bc_4_surface'
Function/Subroutine Documentation
bcast_sph_mhd_model()
subroutine t_ctl_data_mhd_model::bcast_sph_mhd_model (type(mhd_dns_model_control), intent(inout) Dmodel_ctl)
Definition at line 189 of file t_ctl_data_MHD_model.f90.
References t_ctl_data_node_boundary::bcast_bc_4_node_ctl(), t_ctl_data_surf_boundary::bcast_bc_4_surf_ctl(), t_ctl_data_mhd_normalize::bcast_coef_term_ctl(), t_ctl_data_mhd_forces::bcast_coriolis_ctl(), t_ctl_data_mhd_normalize::bcast_dimless_ctl(), t_ctl_data_mhd_forces::bcast_forces_ctl(), t_ctl_data_mhd_forces::bcast_gravity_ctl(), t_ctl_data_mhd_forces::bcast_magneto_ctl(), t_ctl_data_mhd_evolution::bcast_mhd_layer_ctl(), t_ctl_data_mhd_evolution::bcast_mhd_time_evo_ctl(), bcast_4_field_ctl::bcast_phys_data_ctl(), t_ctl_data_temp_model::bcast_ref_scalar_ctl(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by t_ctl_data_mhd::bcast_sph_mhd_ctl_data().
dealloc_sph_mhd_model()
subroutine t_ctl_data_mhd_model::dealloc_sph_mhd_model (type(mhd_dns_model_control), intent(inout) Dmodel_ctl)
Definition at line 219 of file t_ctl_data_MHD_model.f90.
References t_ctl_data_node_boundary::dealloc_bc_4_node_ctl(), t_ctl_data_surf_boundary::dealloc_bc_4_surf_ctl(), t_ctl_data_mhd_normalize::dealloc_coef_term_ctl(), t_ctl_data_mhd_forces::dealloc_coriolis_ctl(), t_ctl_data_mhd_normalize::dealloc_dimless_ctl(), t_ctl_data_mhd_evolution::dealloc_ele_area_grp_ctl(), t_ctl_data_mhd_forces::dealloc_gravity_ctl(), t_ctl_data_mhd_forces::dealloc_magneto_ctl(), t_ctl_data_mhd_forces::dealloc_name_force_ctl(), t_ctl_data_4_fields::dealloc_phys_control(), and t_ctl_data_mhd_evolution::dealloc_t_evo_name_ctl().
Referenced by t_ctl_data_mhd::dealloc_sph_mhd_ctl_data().
read_sph_mhd_model()
subroutine t_ctl_data_mhd_model::read_sph_mhd_model (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(mhd_dns_model_control), intent(inout) Dmodel_ctl, type(buffer_for_control), intent(inout) c_buf)
Definition at line 129 of file t_ctl_data_MHD_model.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_bc_4_node, hd_bc_4_surf, hd_boundary_condition, hd_coef_term_ctl, hd_comp_def, hd_coriolis_ctl, hd_dimless_ctl, hd_forces_ctl, hd_gravity_ctl, hd_induction_ctl, hd_layers_ctl, hd_magneto_ctl, hd_phys_values, hd_temp_def, hd_time_evo, t_read_control_elements::load_one_line_from_control(), t_ctl_data_node_boundary::read_bc_4_node_ctl(), t_ctl_data_surf_boundary::read_bc_4_surf_ctl(), t_ctl_data_mhd_normalize::read_coef_term_ctl(), t_ctl_data_mhd_forces::read_coriolis_ctl(), t_ctl_data_mhd_normalize::read_dimless_ctl(), t_ctl_data_mhd_forces::read_forces_ctl(), t_ctl_data_mhd_forces::read_gravity_ctl(), t_ctl_data_mhd_forces::read_magneto_ctl(), t_ctl_data_mhd_evolution::read_mhd_layer_ctl(), t_ctl_data_mhd_evolution::read_mhd_time_evo_ctl(), t_ctl_data_4_fields::read_phys_data_control(), t_ctl_data_temp_model::read_refcomp_ctl(), and t_ctl_data_temp_model::read_reftemp_ctl().
Referenced by t_ctl_data_mhd::read_sph_mhd_ctl_noviz(), and t_ctl_data_mhd::read_sph_mhd_ctl_w_psf().
Variable Documentation
hd_bc_4_node
character(len=kchara), parameter, private t_ctl_data_mhd_model::hd_bc_4_node = 'bc_4_node' private
Definition at line 85 of file t_ctl_data_MHD_model.f90.
Referenced by read_sph_mhd_model().
hd_bc_4_surf
character(len=kchara), parameter, private t_ctl_data_mhd_model::hd_bc_4_surf = 'bc_4_surface' private
Definition at line 111 of file t_ctl_data_MHD_model.f90.
Referenced by read_sph_mhd_model().
hd_boundary_condition
character(len=kchara), parameter, private t_ctl_data_mhd_model::hd_boundary_condition = 'boundary_condition' private
Definition at line 87 of file t_ctl_data_MHD_model.f90.
Referenced by read_sph_mhd_model().
hd_coef_term_ctl
character(len=kchara), parameter, private t_ctl_data_mhd_model::hd_coef_term_ctl ='coefficients_ctl' private
Definition at line 92 of file t_ctl_data_MHD_model.f90.
Referenced by read_sph_mhd_model().
hd_comp_def
character(len=kchara), parameter, private t_ctl_data_mhd_model::hd_comp_def = 'composition_define' private
Definition at line 109 of file t_ctl_data_MHD_model.f90.
Referenced by read_sph_mhd_model().
hd_coriolis_ctl
character(len=kchara), parameter, private t_ctl_data_mhd_model::hd_coriolis_ctl = 'Coriolis_define' private
Definition at line 99 of file t_ctl_data_MHD_model.f90.
Referenced by read_sph_mhd_model().
hd_dimless_ctl
character(len=kchara), parameter, private t_ctl_data_mhd_model::hd_dimless_ctl = 'dimensionless_ctl' private
Definition at line 90 of file t_ctl_data_MHD_model.f90.
Referenced by read_sph_mhd_model().
hd_forces_ctl
character(len=kchara), parameter, private t_ctl_data_mhd_model::hd_forces_ctl = 'forces_define' private
Definition at line 95 of file t_ctl_data_MHD_model.f90.
Referenced by read_sph_mhd_model().
hd_gravity_ctl
character(len=kchara), parameter, private t_ctl_data_mhd_model::hd_gravity_ctl = 'gravity_define' private
Definition at line 97 of file t_ctl_data_MHD_model.f90.
Referenced by read_sph_mhd_model().
hd_induction_ctl
character(len=kchara), parameter, private t_ctl_data_mhd_model::hd_induction_ctl = 'magnetic_induciton_ctl' private
Definition at line 102 of file t_ctl_data_MHD_model.f90.
Referenced by read_sph_mhd_model().
hd_layers_ctl
character(len=kchara), parameter, private t_ctl_data_mhd_model::hd_layers_ctl = 'layers_ctl' private
Definition at line 83 of file t_ctl_data_MHD_model.f90.
Referenced by read_sph_mhd_model().
hd_magneto_ctl
character(len=kchara), parameter, private t_ctl_data_mhd_model::hd_magneto_ctl = 'Magneto_convection_def' private
Definition at line 104 of file t_ctl_data_MHD_model.f90.
Referenced by read_sph_mhd_model().
hd_phys_values
character(len=kchara), parameter, private t_ctl_data_mhd_model::hd_phys_values = 'phys_values_ctl' private
Definition at line 78 of file t_ctl_data_MHD_model.f90.
Referenced by read_sph_mhd_model().
hd_temp_def
character(len=kchara), parameter, private t_ctl_data_mhd_model::hd_temp_def = 'temperature_define' private
Definition at line 107 of file t_ctl_data_MHD_model.f90.
Referenced by read_sph_mhd_model().
hd_time_evo
character(len=kchara), parameter, private t_ctl_data_mhd_model::hd_time_evo = 'time_evolution_ctl' private
Definition at line 81 of file t_ctl_data_MHD_model.f90.
Referenced by read_sph_mhd_model().