CALYPSO: select_diff_adv_source Module Reference
select_diff_adv_source Module Reference
Evaluate time evolution explicitly.
Functions/Subroutines
subroutine sel_scalar_diff_adv_src_adams (kr_st, kr_ed, ipol_diffuse, ipol_advect, ipol_source, ipol_scalar, ipol_pre, dt, coef_exp, coef_src, sph_rj, rj_fld)
subroutine sel_scalar_diff_adv_src_euler (kr_st, kr_ed, ipol_diffuse, ipol_advect, ipol_source, ipol_scalar, dt, coef_exp, coef_adv, coef_src, sph_rj, rj_fld)
subroutine sel_ini_adams_scalar_w_src (kr_st, kr_ed, ipol_advect, ipol_source, ipol_pre, coef_src, sph_rj, rj_fld)
subroutine sel_ctr_scl_diff_adv_src_adams (ipol_diffuse, ipol_advect, ipol_source, ipol_scalar, ipol_pre, dt, coef_exp, coef_src, sph_rj, rj_fld)
subroutine sel_ctr_scl_diff_adv_src_euler (ipol_diffuse, ipol_advect, ipol_source, ipol_scalar, dt, coef_exp, coef_adv, coef_src, sph_rj, rj_fld)
Detailed Description
Evaluate time evolution explicitly.
      subroutine sel_scalar_diff_adv_src_adams(kr_st, kr_ed,          &
     &          ipol_diffuse, ipol_advect, ipol_source, ipol_scalar,  &
     &          ipol_pre, dt, coef_exp, coef_src, sph_rj, rj_fld)
      subroutine sel_scalar_diff_adv_src_euler(kr_st, kr_ed,          &
     &          ipol_diffuse, ipol_advect, ipol_source, ipol_scalar,  &
     &          dt, coef_exp, coef_adv, coef_src, sph_rj, rj_fld)
      subroutine sel_ini_adams_scalar_w_src                           &
     &         (kr_st, kr_ed, ipol_advect, ipol_source, ipol_pre,     &
     &          coef_src, sph_rj, rj_fld)
      subroutine sel_ctr_scl_diff_adv_src_adams                       &
     &         (ipol_diffuse, ipol_advect, ipol_source, ipol_scalar,  &
     &          ipol_pre, dt, coef_exp, coef_src, sph_rj, rj_fld)
      subroutine sel_ctr_scl_diff_adv_src_euler                       &
     &         (ipol_diffuse, ipol_advect, ipol_source, ipol_scalar,  &
     &          dt, coef_exp, coef_adv, coef_src, sph_rj, rj_fld)
        type(sph_rj_grid), intent(in) :: sph_rj
        type(phys_data), intent(inout) :: rj_fld
Parameters
kr_st Radial address for inner boundary
kr_ed Radial address for outer boundary
ipol_diffuse address for diffusion term
ipol_advect address for advection term
ipol_source address for source term
ipol_scalar address for scalar field to update
ipol_pre address for storeing previous evolution
coef_exp coeefient for expilict evolution for diffusion
coef_src coefficient for source term
Function/Subroutine Documentation
sel_ctr_scl_diff_adv_src_adams()
subroutine select_diff_adv_source::sel_ctr_scl_diff_adv_src_adams (integer(kind = kint), intent(in) ipol_diffuse, integer(kind = kint), intent(in) ipol_advect, integer(kind = kint), intent(in) ipol_source, integer(kind = kint), intent(in) ipol_scalar, integer(kind = kint), intent(in) ipol_pre, real(kind = kreal), intent(in) dt, real(kind = kreal), intent(in) coef_exp, real(kind = kreal), intent(in) coef_src, type(sph_rj_grid), intent(in) sph_rj, type(phys_data), intent(inout) rj_fld)
Definition at line 176 of file select_diff_adv_source.f90.
References cal_diff_adv_src_explicit::center_scl_diff_adv_src_adams(), and m_constants::izero.
Referenced by explicit_scalars_sph::explicit_scalars_sph_adams().
sel_ctr_scl_diff_adv_src_euler()
subroutine select_diff_adv_source::sel_ctr_scl_diff_adv_src_euler (integer(kind = kint), intent(in) ipol_diffuse, integer(kind = kint), intent(in) ipol_advect, integer(kind = kint), intent(in) ipol_source, integer(kind = kint), intent(in) ipol_scalar, real(kind = kreal), intent(in) dt, real(kind = kreal), intent(in) coef_exp, real(kind = kreal), intent(in) coef_adv, real(kind = kreal), intent(in) coef_src, type(sph_rj_grid), intent(in) sph_rj, type(phys_data), intent(inout) rj_fld)
Definition at line 200 of file select_diff_adv_source.f90.
References cal_diff_adv_src_explicit::center_scl_diff_adv_src_euler(), m_constants::izero, and m_constants::zero.
Referenced by explicit_scalars_sph::explicit_scalars_sph_euler().
sel_ini_adams_scalar_w_src()
subroutine select_diff_adv_source::sel_ini_adams_scalar_w_src (integer(kind = kint), intent(in) kr_st, integer(kind = kint), intent(in) kr_ed, integer(kind = kint), intent(in) ipol_advect, integer(kind = kint), intent(in) ipol_source, integer(kind = kint), intent(in) ipol_pre, real(kind = kreal), intent(in) coef_src, type(sph_rj_grid), intent(in) sph_rj, type(phys_data), intent(inout) rj_fld)
Definition at line 141 of file select_diff_adv_source.f90.
References cal_diff_adv_src_explicit::center_ini_adams_scalar_w_src(), m_constants::izero, cal_diff_adv_src_explicit::set_ini_adams_scalar(), and cal_diff_adv_src_explicit::set_ini_adams_scalar_w_src().
Referenced by explicit_scalars_sph::first_scalars_prev_step_adams().
sel_scalar_diff_adv_src_adams()
subroutine select_diff_adv_source::sel_scalar_diff_adv_src_adams (integer(kind = kint), intent(in) kr_st, integer(kind = kint), intent(in) kr_ed, integer(kind = kint), intent(in) ipol_diffuse, integer(kind = kint), intent(in) ipol_advect, integer(kind = kint), intent(in) ipol_source, integer(kind = kint), intent(in) ipol_scalar, integer(kind = kint), intent(in) ipol_pre, real(kind = kreal), intent(in) dt, real(kind = kreal), intent(in) coef_exp, real(kind = kreal), intent(in) coef_src, type(sph_rj_grid), intent(in) sph_rj, type(phys_data), intent(inout) rj_fld)
Definition at line 58 of file select_diff_adv_source.f90.
References m_constants::izero, cal_diff_adv_src_explicit::scalar_diff_adv_src_adams(), and cal_diff_adv_src_explicit::scalar_diff_advect_adams().
Referenced by explicit_scalars_sph::explicit_scalars_sph_adams().
sel_scalar_diff_adv_src_euler()
subroutine select_diff_adv_source::sel_scalar_diff_adv_src_euler (integer(kind = kint), intent(in) kr_st, integer(kind = kint), intent(in) kr_ed, integer(kind = kint), intent(in) ipol_diffuse, integer(kind = kint), intent(in) ipol_advect, integer(kind = kint), intent(in) ipol_source, integer(kind = kint), intent(in) ipol_scalar, real(kind = kreal), intent(in) dt, real(kind = kreal), intent(in) coef_exp, real(kind = kreal), intent(in) coef_adv, real(kind = kreal), intent(in) coef_src, type(sph_rj_grid), intent(in) sph_rj, type(phys_data), intent(inout) rj_fld)
Definition at line 93 of file select_diff_adv_source.f90.
References m_constants::izero, cal_diff_adv_src_explicit::scalar_diff_adv_src_euler(), cal_diff_adv_src_explicit::scalar_diff_advect_euler(), cal_diff_adv_src_explicit::stable_scalar_diff_src(), cal_diff_adv_src_explicit::stable_scalar_diffusion(), and m_constants::zero.
Referenced by explicit_scalars_sph::explicit_scalars_sph_euler().