CALYPSO: pole_energy_flux_sph Module Reference
pole_energy_flux_sph Module Reference
Evaluate nonlinear terms at poles.
Functions/Subroutines
subroutine pole_nonlinear_sph_mhd (sph_rtp, node, fl_prop, cd_prop, ht_prop, cp_prop, iphys, nod_fld)
subroutine pole_energy_flux_rtp (sph_rtp, node, fl_prop, cd_prop, ref_param_T, ref_param_C, iphys, nod_fld)
subroutine pole_sph_buoyancy_flux (numnod, internal_node, xx, nnod_rtp, nidx_rtp_r, coef, ncomp_nod, i_temp, i_velo, i_buo_flux, d_nod)
Detailed Description
Evaluate nonlinear terms at poles.
      subroutine pole_nonlinear_sph_MHD(sph_rtp, node,                &
     &          fl_prop, cd_prop, ht_prop, cp_prop, iphys, nod_fld)
      subroutine pole_energy_flux_rtp(sph_rtp, node,                  &
     &          fl_prop, cd_prop, ref_param_T, ref_param_C,           &
     &         iphys, nod_fld)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(node_data), intent(in) :: node
        type(fluid_property), intent(in) :: fl_prop
        type(conductive_property), intent(in) :: cd_prop
        type(scalar_property), intent(in) :: ht_prop, cp_prop
        type(reference_scalar_param), intent(in) :: ref_param_T
        type(reference_scalar_param), intent(in) :: ref_param_C
        type(phys_address), intent(in) :: iphys
        type(phys_data), intent(inout) :: nod_fld
      subroutine pole_sph_buoyancy_flux                               &
     &        (numnod, internal_node, xx, nnod_rtp, nidx_rtp_r, coef, &
     &         ncomp_nod, i_temp, i_velo, i_buo_flux, d_nod)
Function/Subroutine Documentation
pole_energy_flux_rtp()
subroutine pole_energy_flux_sph::pole_energy_flux_rtp (type(sph_rtp_grid), intent(in) sph_rtp, type(node_data), intent(in) node, type(fluid_property), intent(in) fl_prop, type(conductive_property), intent(in) cd_prop, type(reference_scalar_param), intent(in) ref_param_T, type(reference_scalar_param), intent(in) ref_param_C, type(phys_address), intent(in) iphys, type(phys_data), intent(inout) nod_fld)
Definition at line 113 of file pole_energy_flux_sph.f90.
References pole_poynting_flux_smp::cal_pole_electric_field_smp(), pole_poynting_flux_smp::cal_pole_poynting_flux_smp(), m_constants::dminus, t_reference_scalar_param::id_sphere_ref_temp, t_reference_scalar_param::id_takepiro_temp, m_constants::one, products_at_poles::pole_fld_cst_dot_prod(), and pole_sph_buoyancy_flux().
pole_nonlinear_sph_mhd()
subroutine pole_energy_flux_sph::pole_nonlinear_sph_mhd (type(sph_rtp_grid), intent(in) sph_rtp, type(node_data), intent(in) node, type(fluid_property), intent(in) fl_prop, type(conductive_property), intent(in) cd_prop, type(scalar_property), intent(in) ht_prop, type(scalar_property), intent(in) cp_prop, type(phys_address), intent(in) iphys, type(phys_data), intent(inout) nod_fld)
Definition at line 49 of file pole_energy_flux_sph.f90.
References products_at_poles::pole_fld_cst_cross_prod(), and products_at_poles::pole_fld_cst_vec_scalar_prod().
pole_sph_buoyancy_flux()
subroutine pole_energy_flux_sph::pole_sph_buoyancy_flux (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) internal_node, real(kind = kreal), dimension(numnod,3), intent(in) xx, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) nidx_rtp_r, real(kind = kreal), intent(in) coef, integer(kind = kint), intent(in) ncomp_nod, integer(kind = kint), intent(in) i_temp, integer(kind = kint), intent(in) i_velo, integer(kind = kint), intent(in) i_buo_flux, real(kind = kreal), dimension(numnod, ncomp_nod), intent(inout) d_nod)
Definition at line 222 of file pole_energy_flux_sph.f90.
References m_constants::zero.
Referenced by pole_energy_flux_rtp().