CALYPSO: find_element_id_4_node Module Reference
find_element_id_4_node Module Reference
Search belonged element list for each node.
Functions/Subroutines
subroutine count_iele_4_node (numnod, numele, nnod_4_ele, ie, iele_st, iele_ed, nele_4_node)
subroutine set_iele_4_node (numnod, numele, nnod_4_ele, ie, iele_st, iele_ed, ntot_ele_4_node, iele_stack_4_node, nele_4_node, iele_4_node, iconn_4_node)
subroutine count_belonged_ele_4_node (numnod, numele, nnod_4_ele, ie, iele_st, iele_ed, nele_4_node)
subroutine set_belonged_ele_4_node (numnod, numele, nnod_4_ele, ie, iele_st, iele_ed, ntot_ele_4_node, iele_stack_4_node, nele_4_node, iele_4_node, iconn_4_node)
Detailed Description
Search belonged element list for each node.
      subroutine count_iele_4_node(numnod, numele, nnod_4_ele, ie,    &
     &          iele_st, iele_ed, nele_4_node)
      subroutine set_iele_4_node(numnod, numele, nnod_4_ele, ie,      &
     &          iele_st, iele_ed, ntot_ele_4_node, iele_stack_4_node, &
     &          nele_4_node, iele_4_node, iconn_4_node)
      subroutine count_belonged_ele_4_node(numnod, numele, nnod_4_ele,&
     &          ie, iele_st, iele_ed, nele_4_node)
      subroutine set_belonged_ele_4_node(numnod, numele, nnod_4_ele,  &
     &          ie, iele_st, iele_ed, ntot_ele_4_node,                &
     &          iele_stack_4_node, nele_4_node, iele_4_node,          &
     &          iconn_4_node)
Function/Subroutine Documentation
count_belonged_ele_4_node()
subroutine find_element_id_4_node::count_belonged_ele_4_node (integer (kind=kint), intent(in) numnod, integer (kind=kint), intent(in) numele, integer (kind=kint), intent(in) nnod_4_ele, integer (kind=kint), dimension(numele,nnod_4_ele), intent(in) ie, integer (kind=kint), intent(in) iele_st, integer (kind=kint), intent(in) iele_ed, integer (kind=kint), dimension(numnod), intent(inout) nele_4_node)
Definition at line 114 of file find_element_id_4_node.f90.
References count_iele_4_node(), and m_constants::ione.
Referenced by t_belonged_element_4_node::belonged_edge_id_4_node(), t_belonged_element_4_node::belonged_ele_id_4_node(), and t_belonged_element_4_node::belonged_surf_id_4_node().
count_iele_4_node()
subroutine find_element_id_4_node::count_iele_4_node (integer (kind=kint), intent(in) numnod, integer (kind=kint), intent(in) numele, integer (kind=kint), intent(in) nnod_4_ele, integer (kind=kint), dimension(numele,nnod_4_ele), intent(in) ie, integer (kind=kint), intent(in) iele_st, integer (kind=kint), intent(in) iele_ed, integer (kind=kint), dimension(numnod), intent(inout) nele_4_node)
Definition at line 37 of file find_element_id_4_node.f90.
Referenced by count_belonged_ele_4_node(), set_ele_id_4_node_type::set_edge_id_4_node(), set_ele_id_4_node_type::set_ele_id_4_node(), set_ele_id_4_node_type::set_layerd_ele_id_4_node(), and set_ele_id_4_node_type::set_surf_id_4_node().
set_belonged_ele_4_node()
subroutine find_element_id_4_node::set_belonged_ele_4_node (integer (kind=kint), intent(in) numnod, integer (kind=kint), intent(in) numele, integer (kind=kint), intent(in) nnod_4_ele, integer (kind=kint), dimension(numele,nnod_4_ele), intent(in) ie, integer (kind=kint), intent(in) iele_st, integer (kind=kint), intent(in) iele_ed, integer (kind=kint), intent(in) ntot_ele_4_node, integer (kind=kint), dimension(0:numnod), intent(in) iele_stack_4_node, integer (kind=kint), dimension(numnod), intent(inout) nele_4_node, integer (kind=kint), dimension(ntot_ele_4_node), intent(inout) iele_4_node, integer (kind=kint), dimension(ntot_ele_4_node), intent(inout) iconn_4_node)
Definition at line 131 of file find_element_id_4_node.f90.
References m_constants::ione, and set_iele_4_node().
Referenced by t_belonged_element_4_node::belonged_edge_id_4_node(), t_belonged_element_4_node::belonged_ele_id_4_node(), and t_belonged_element_4_node::belonged_surf_id_4_node().
set_iele_4_node()
subroutine find_element_id_4_node::set_iele_4_node (integer (kind=kint), intent(in) numnod, integer (kind=kint), intent(in) numele, integer (kind=kint), intent(in) nnod_4_ele, integer (kind=kint), dimension(numele,nnod_4_ele), intent(in) ie, integer (kind=kint), intent(in) iele_st, integer (kind=kint), intent(in) iele_ed, integer (kind=kint), intent(in) ntot_ele_4_node, integer (kind=kint), dimension(0:numnod), intent(in) iele_stack_4_node, integer (kind=kint), dimension(numnod), intent(inout) nele_4_node, integer (kind=kint), dimension(ntot_ele_4_node), intent(inout) iele_4_node, integer (kind=kint), dimension(ntot_ele_4_node), intent(inout) iconn_4_node)
Definition at line 64 of file find_element_id_4_node.f90.
References m_constants::ione, and quicksort::quicksort_w_index().
Referenced by set_belonged_ele_4_node(), set_ele_id_4_node_type::set_edge_id_4_node(), set_ele_id_4_node_type::set_ele_id_4_node(), set_ele_id_4_node_type::set_layerd_ele_id_4_node(), and set_ele_id_4_node_type::set_surf_id_4_node().