CALYPSO: const_mesh_information Module Reference
const_mesh_information Module Reference
Construct mesh strucuture informations.
Functions/Subroutines
subroutine empty_mesh_info (mesh, group)
subroutine const_mesh_infos (id_rank, mesh, group)
subroutine const_nod_ele_infos (id_rank, node, ele, nod_grp, ele_grp, surf_grp)
subroutine set_local_element_info (surf, edge)
subroutine set_nod_and_ele_infos (node, ele)
subroutine empty_nod_and_ele_type_infos (geom)
subroutine const_group_type_info (node, ele, surf, edge, ele_grp, surf_grp, tbls_ele_grp, tbls_surf_grp)
Detailed Description
Construct mesh strucuture informations.
      subroutine empty_mesh_info(mesh, group)
        type(mesh_geometry), intent(inout) :: mesh
        type(mesh_groups), intent(inout) ::   group
      subroutine const_mesh_infos(id_rank, mesh, group)
      subroutine const_nod_ele_infos                                  &
     &         (id_rank, node, ele, nod_grp, ele_grp, surf_grp)
      subroutine set_local_element_info(surf, edge)
      subroutine set_nod_and_ele_infosiflag_ele_mesh, (node, ele)
        type(mesh_geometry), intent(inout) :: mesh
        type(mesh_groups), intent(inout) ::   group
        type(node_data), intent(inout) :: node
        type(element_data), intent(inout) :: ele
        type(surface_data), intent(inout) :: surf
        type(edge_data),    intent(inout) :: edge
        type(group_data), intent(inout) :: nod_grp
        type(group_data), intent(inout) :: ele_grp
        type(surface_group_data), intent(inout) :: surf_grp
        type(element_group_table), intent(inout) :: tbls_ele_grp
        type(surface_group_table), intent(inout) :: tbls_sf_grp
      subroutine empty_nod_and_ele_type_infos(geom)
        type(mesh_geometry), intent(inout) :: geom
      subroutine const_group_type_info                                &
     &         (node, ele, surf, edge, ele_grp, surf_grp,             &
     &          tbls_ele_grp, tbls_surf_grp)
        type(node_data), intent(in) :: node
        type(element_data), intent(in) :: ele
        type(surface_data), intent(inout) :: surf
        type(edge_data),    intent(inout) :: edge
        type(group_data), intent(in) ::         ele_grp
        type(surface_group_data), intent(in) :: surf_grp
        type (element_group_table), intent(inout) :: tbls_ele_grp
        type (surface_group_table), intent(inout) :: tbls_surf_grp
Function/Subroutine Documentation
const_group_type_info()
subroutine const_mesh_information::const_group_type_info (type(node_data), intent(in) node, type(element_data), intent(in) ele, type(surface_data), intent(in) surf, type(edge_data), intent(in) edge, type(group_data), intent(in) ele_grp, type(surface_group_data), intent(in) surf_grp, type (element_group_table), intent(inout) tbls_ele_grp, type (surface_group_table), intent(inout) tbls_surf_grp)
Definition at line 272 of file const_mesh_information.f90.
References m_machine_parameter::iflag_debug, set_connects_4_ele_group::set_edge_4_ele_group(), set_connects_4_surf_group::set_edge_4_surf_group(), set_connects_4_ele_group::set_node_4_ele_group(), set_connects_4_ele_group::set_surf_4_ele_group(), and set_connects_4_surf_group::set_surf_id_4_surf_group().
Referenced by const_mesh_infos().
const_mesh_infos()
subroutine const_mesh_information::const_mesh_infos (integer, intent(in) id_rank, type(mesh_geometry), intent(inout) mesh, type(mesh_groups), intent(inout) group)
Definition at line 111 of file const_mesh_information.f90.
References const_surface_data::const_ele_list_4_surface(), const_group_type_info(), const_nod_ele_infos(), m_machine_parameter::iflag_debug, set_local_element_info(), set_connects_4_surf_group::set_node_4_surf_group(), and set_surf_edge_mesh::set_surface_and_edge().
Referenced by parallel_fem_mesh_init::fem_mesh_initialization().
const_nod_ele_infos()
subroutine const_mesh_information::const_nod_ele_infos (integer, intent(in) id_rank, type(node_data), intent(inout) node, type(element_data), intent(inout) ele, type(group_data), intent(inout) nod_grp, type(group_data), intent(inout) ele_grp, type(surface_group_data), intent(inout) surf_grp)
Definition at line 165 of file const_mesh_information.f90.
References set_smp_4_group_types::count_num_groups_smp(), m_machine_parameter::iflag_debug, and set_nod_and_ele_infos().
Referenced by const_mesh_infos().
empty_mesh_info()
subroutine const_mesh_information::empty_mesh_info (type(mesh_geometry), intent(inout) mesh, type(mesh_groups), intent(inout) group)
Definition at line 70 of file const_mesh_information.f90.
References set_smp_4_group_types::count_num_groups_smp(), empty_nod_and_ele_type_infos(), set_connects_4_ele_group::empty_sf_ed_nod_ele_grp_type(), set_connects_4_surf_group::empty_sf_ed_nod_surf_grp_type(), set_surf_edge_mesh::empty_surface_and_edge(), set_connects_4_surf_group::empty_surface_node_grp_type(), and m_machine_parameter::iflag_debug.
empty_nod_and_ele_type_infos()
subroutine const_mesh_information::empty_nod_and_ele_type_infos (type(mesh_geometry), intent(inout) geom)
Definition at line 255 of file const_mesh_information.f90.
References t_geometry_data::alloc_ele_geometry(), t_geometry_data::allocate_ele_param_smp_type(), t_geometry_data::allocate_node_param_smp_type(), and m_machine_parameter::iflag_debug.
Referenced by empty_mesh_info().
set_local_element_info()
subroutine const_mesh_information::set_local_element_info (type(surface_data), intent(inout) surf, type(edge_data), intent(inout) edge)
Definition at line 198 of file const_mesh_information.f90.
References t_edge_data::alloc_inod_in_edge(), t_surface_data::allocate_inod_in_surf(), set_local_id_table_4_1ele::copy_inod_in_edge(), m_machine_parameter::iflag_debug, and set_local_id_table_4_1ele::set_inod_in_surf().
Referenced by const_mesh_infos(), and const_kemoview_mesh::const_surf_mesh_4_viewer().
set_nod_and_ele_infos()
subroutine const_mesh_information::set_nod_and_ele_infos (type(node_data), intent(inout) node, type(element_data), intent(inout) ele)
Definition at line 220 of file const_mesh_information.f90.
References t_geometry_data::alloc_ele_geometry(), set_size_4_smp_types::count_overlap_ele(), set_size_4_smp_types::count_size_4_smp_mesh_type(), cal_mesh_position::find_subdomain_position_range(), m_machine_parameter::iflag_debug, cal_mesh_position::set_center_of_element(), and cal_mesh_position::set_spherical_position().
Referenced by const_nod_ele_infos().