CALYPSO: cal_inner_core_rotation Module Reference
cal_inner_core_rotation Module Reference
Evaluate torques for inner core rotation.
Functions/Subroutines
subroutine set_inner_core_rotation (kr_in, sph_rj, ipol_base, rj_fld)
subroutine set_icore_viscous_matrix (kr_in, fdm1_fix_fld_ICB, dt, sph_rj, fl_prop, band_vt_evo)
subroutine cal_icore_viscous_drag_explicit (kr_in, fdm1_fix_fld_ICB, sph_rj, coef_d, it_velo, it_viscous, rj_fld)
subroutine copy_icore_rot_to_tor_coriolis (sph_bc_U, sph_rj, ipol_frc, ipol_rot_frc, rj_fld)
subroutine inner_core_coriolis_rj (kr_in, idx_rj_degree_one, nri, jmax, radius_1d_rj_r, omega_rj, coef_cor, ipol_base, ipol_rot_frc, n_point, ntot_phys_rj, d_rj)
subroutine int_icore_toroidal_lorentz (kr_in, sph_rj, ipol_frc, ipol_rot_frc, rj_fld)
subroutine, private set_rotate_icb_vt_sph_mat (dt, idx_rj_l0, kr_in, nri, jmax, ar_1d_rj, fdm1_fix_fld_ICB, coef_imp, coef_d, vt_evo_mat)
subroutine, private set_inner_core_rot_l1 (ipol_base, idx_rj_l0, kr_in, nri, jmax, radius_1d_rj_r, ar_1d_rj, nnod_rj, ntot_phys_rj, d_rj)
subroutine, private cal_icore_viscous_drag_l1 (idx_rj_l0, kr_in, fdm1_fix_fld_ICB, coef_d, it_velo, it_viscous, nri, jmax, ar_1d_rj, n_point, ntot_phys_rj, d_rj)
subroutine, private int_icore_tor_lorentz_l1 (ipol_frc, ipol_rot_frc, idx_rj_l0, kr_in, nri, jmax, radius_1d_rj_r, ar_1d_rj, nnod_rj, ntot_phys_rj, d_rj)
Detailed Description
Evaluate torques for inner core rotation.
      subroutine set_inner_core_rotation                              &
     &         (kr_in, sph_rj, ipol_base, rj_fld)
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(base_field_address), intent(in) :: ipol_base
        type(phys_data), intent(inout) :: rj_fld
      subroutine set_icore_viscous_matrix(kr_in, fdm1_fix_fld_ICB,    &
     &          dt, sph_rj, fl_prop, band_vt_evo)
      subroutine cal_icore_viscous_drag_explicit                      &
     &         (kr_in, fdm1_fix_fld_ICB, sph_rj, coef_d,              &
     &          it_velo, it_viscous, rj_fld)
      subroutine copy_icore_rot_to_tor_coriolis                       &
     &         (sph_bc_U, sph_rj, ipol_frc, ipol_rot_frc, rj_fld)
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(base_force_address), intent(in) :: ipol_frc
        type(base_force_address), intent(in) :: ipol_rot_frc
        type(sph_boundary_type), intent(in) :: sph_bc_U
        type(phys_data), intent(inout) :: rj_fld
      subroutine inner_core_coriolis_rj                               &
     &         (kr_in, idx_rj_degree_one,  nri, jmax, radius_1d_rj_r, &
     &          omega_rj, coef_cor, ipol_base, ipol_rot_frc,          &
     &          n_point, ntot_phys_rj, d_rj)
      subroutine int_icore_toroidal_lorentz                           &
     &         (kr_in, sph_rj, ipol_frc, ipol_rot_frc, rj_fld)
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(base_field_address), intent(in) :: ipol_base
        type(base_force_address), intent(in) :: ipol_frc
        type(base_force_address), intent(in) :: ipol_rot_frc
        type(fluid_property), intent(in) :: fl_prop
        type(phys_data), intent(inout) :: rj_fld
        type(band_matrices_type), intent(inout) :: band_vt_evo
Parameters
coef_d Coefficient for diffusion term
it_velo Field address for toroidal velocity
it_viscous Field address for toroidal viscous dissipation
Function/Subroutine Documentation
cal_icore_viscous_drag_explicit()
subroutine cal_inner_core_rotation::cal_icore_viscous_drag_explicit (integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(0:1,2), intent(in) fdm1_fix_fld_ICB, type(sph_rj_grid), intent(in) sph_rj, real(kind = kreal), intent(in) coef_d, integer(kind = kint), intent(in) it_velo, integer(kind = kint), intent(in) it_viscous, type(phys_data), intent(inout) rj_fld)
Definition at line 131 of file cal_inner_core_rotation.f90.
References cal_icore_viscous_drag_l1().
Referenced by select_exp_velocity_icb::sel_icb_sph_viscous_diffusion(), and select_exp_velocity_icb::sel_icb_sph_vort_diffusion().
cal_icore_viscous_drag_l1()
subroutine, private cal_inner_core_rotation::cal_icore_viscous_drag_l1 (integer(kind = kint), intent(in) idx_rj_l0, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(0:1,2), intent(in) fdm1_fix_fld_ICB, real(kind = kreal), intent(in) coef_d, integer(kind = kint), intent(in) it_velo, integer(kind = kint), intent(in) it_viscous, integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, real(kind= kreal), dimension(nri,3), intent(in) ar_1d_rj, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj) private
Definition at line 346 of file cal_inner_core_rotation.f90.
References m_constants::five, and m_constants::two.
Referenced by cal_icore_viscous_drag_explicit().
copy_icore_rot_to_tor_coriolis()
subroutine cal_inner_core_rotation::copy_icore_rot_to_tor_coriolis (type(sph_boundary_type), intent(in) sph_bc_U, type(sph_rj_grid), intent(in) sph_rj, type(base_force_address), intent(in) ipol_frc, type(base_force_address), intent(in) ipol_rot_frc, type(phys_data), intent(inout) rj_fld)
Definition at line 162 of file cal_inner_core_rotation.f90.
References t_boundary_params_sph_mhd::iflag_rotatable_ic.
Referenced by cal_nonlinear::nonlinear().
inner_core_coriolis_rj()
subroutine cal_inner_core_rotation::inner_core_coriolis_rj (integer(kind = kint), intent(in) kr_in, integer(kind = kint), dimension(-1:1), intent(in) idx_rj_degree_one, integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(nri), intent(in) radius_1d_rj_r, real(kind = kreal), dimension(nri,0:2,3), intent(in) omega_rj, real(kind = kreal), intent(in) coef_cor, type(base_field_address), intent(in) ipol_base, type(base_force_address), intent(in) ipol_rot_frc, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 190 of file cal_inner_core_rotation.f90.
References m_constants::two.
int_icore_tor_lorentz_l1()
subroutine, private cal_inner_core_rotation::int_icore_tor_lorentz_l1 (type(base_force_address), intent(in) ipol_frc, type(base_force_address), intent(in) ipol_rot_frc, integer(kind = kint), intent(in) idx_rj_l0, integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, real(kind= kreal), dimension(nri), intent(in) radius_1d_rj_r, real(kind= kreal), dimension(nri,3), intent(in) ar_1d_rj, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj) private
Definition at line 381 of file cal_inner_core_rotation.f90.
References m_constants::five, and m_constants::half.
Referenced by int_icore_toroidal_lorentz().
int_icore_toroidal_lorentz()
subroutine cal_inner_core_rotation::int_icore_toroidal_lorentz (integer(kind = kint), intent(in) kr_in, type(sph_rj_grid), intent(in) sph_rj, type(base_force_address), intent(in) ipol_frc, type(base_force_address), intent(in) ipol_rot_frc, type(phys_data), intent(inout) rj_fld)
Definition at line 241 of file cal_inner_core_rotation.f90.
References int_icore_tor_lorentz_l1().
Referenced by cal_sph_field_by_rotation::cal_rot_of_forces_sph_2().
set_icore_viscous_matrix()
subroutine cal_inner_core_rotation::set_icore_viscous_matrix (integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(0:1,2), intent(in) fdm1_fix_fld_ICB, real(kind = kreal), intent(in) dt, type(sph_rj_grid), intent(in) sph_rj, type(fluid_property), intent(in) fl_prop, type(band_matrices_type), intent(inout) band_vt_evo)
Definition at line 98 of file cal_inner_core_rotation.f90.
References set_rotate_icb_vt_sph_mat().
Referenced by const_r_mat_4_vector_sph::const_radial_mat_vort_2step().
set_inner_core_rot_l1()
subroutine, private cal_inner_core_rotation::set_inner_core_rot_l1 (type(base_field_address), intent(in) ipol_base, integer(kind = kint), intent(in) idx_rj_l0, integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, real(kind= kreal), dimension(nri), intent(in) radius_1d_rj_r, real(kind= kreal), dimension(nri,3), intent(in) ar_1d_rj, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj) private
Definition at line 301 of file cal_inner_core_rotation.f90.
References m_constants::two.
Referenced by set_inner_core_rotation().
set_inner_core_rotation()
subroutine cal_inner_core_rotation::set_inner_core_rotation (integer(kind = kint), intent(in) kr_in, type(sph_rj_grid), intent(in) sph_rj, type(base_field_address), intent(in) ipol_base, type(phys_data), intent(inout) rj_fld)
Definition at line 68 of file cal_inner_core_rotation.f90.
References set_inner_core_rot_l1().
Referenced by cal_sol_sph_mhd_crank::update_after_vorticity_sph().
set_rotate_icb_vt_sph_mat()
subroutine, private cal_inner_core_rotation::set_rotate_icb_vt_sph_mat (real(kind = kreal), intent(in) dt, integer(kind = kint), intent(in) idx_rj_l0, integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(nri,3), intent(in) ar_1d_rj, real(kind = kreal), dimension(0:1,2), intent(in) fdm1_fix_fld_ICB, real(kind = kreal), intent(in) coef_imp, real(kind = kreal), intent(in) coef_d, real(kind = kreal), dimension(3,nri,jmax), intent(inout) vt_evo_mat) private
Definition at line 272 of file cal_inner_core_rotation.f90.
References m_constants::five, m_constants::one, and m_constants::two.
Referenced by set_icore_viscous_matrix().