CALYPSO: output_4_psf Module Reference
output_4_psf Module Reference
Output routines for surfacing module.
Functions/Subroutines
subroutine output_section_mesh (num_psf, psf_file_IO, psf_mesh, psf_out)
subroutine output_section_data (num_psf, psf_file_IO, istep_psf, time_d, t_IO, psf_out)
subroutine output_isosurface (num_iso, iso_file_IO, istep_iso, time_d, iso_mesh, t_IO, iso_out)
Detailed Description
Output routines for surfacing module.
      subroutine output_section_mesh                                  &
     &         (num_psf, psf_file_IO, psf_mesh, psf_out)
      subroutine output_section_data(num_psf, psf_file_IO, istep_psf, &
     &          time_d, t_IO, psf_out)
        type(time_data), intent(in) :: time_d
        type(psf_local_data), intent(in) :: psf_mesh(num_psf)
        type(field_IO_params), intent(in) :: ucd_param(num_psf)
        type(time_data), intent(inout) :: t_IO
        type(ucd_data), intent(inout) ::        psf_out(num_psf)
      subroutine output_isosurface(num_iso, iso_file_IO, istep_iso,   &
     &          time_d, iso_mesh, t_IO, iso_out)
        type(time_data), intent(in) :: time_d
        type(psf_local_data), intent(in) :: iso_mesh(num_iso)
        type(field_IO_params), intent(in) :: iso_file_IO(num_iso)
        type(time_data), intent(inout) :: t_IO
        type(ucd_data), intent(inout) :: iso_out(num_iso)
Function/Subroutine Documentation
output_isosurface()
subroutine output_4_psf::output_isosurface (integer(kind= kint), intent(in) num_iso, type(field_io_params), dimension(num_iso), intent(in) iso_file_IO, integer(kind= kint), intent(in) istep_iso, type(time_data), intent(in) time_d, type(psf_local_data), dimension(num_iso), intent(in) iso_mesh, type(time_data), intent(inout) t_IO, type(ucd_data), dimension(num_iso), intent(inout) iso_out)
Parameters
[in] iso_file_io Structure for isosurface output (used by master process)
Definition at line 120 of file output_4_psf.f90.
References calypso_mpi::calypso_mpi_barrier(), t_time_data::copy_time_step_size_data(), t_ucd_data::disconnect_merged_ucd_mesh(), set_ucd_data_to_type::link_ele_data_2_ucd(), set_ucd_data_to_type::link_field_data_to_ucd(), set_ucd_data_to_type::link_nele_stacks_2_ucd(), set_ucd_data_to_type::link_nnod_stacks_2_ucd(), set_ucd_data_to_type::link_node_data_2_ucd(), calypso_mpi::nprocs, and parallel_ucd_io_select::sel_write_parallel_ucd_file().
Referenced by t_isosurface::isosurf_visualize().
output_section_data()
subroutine output_4_psf::output_section_data (integer(kind= kint), intent(in) num_psf, type(field_io_params), dimension(num_psf), intent(in) psf_file_IO, integer(kind= kint), intent(in) istep_psf, type(time_data), intent(in) time_d, type(time_data), intent(inout) t_IO, type(ucd_data), dimension(num_psf), intent(inout) psf_out)
Definition at line 89 of file output_4_psf.f90.
References calypso_mpi::calypso_mpi_barrier(), t_time_data::copy_time_step_size_data(), and parallel_ucd_io_select::sel_write_parallel_ucd_file().
Referenced by t_cross_section::sectioning_visualize().
output_section_mesh()
subroutine output_4_psf::output_section_mesh (integer(kind= kint), intent(in) num_psf, type(field_io_params), dimension(num_psf), intent(in) psf_file_IO, type(psf_local_data), dimension(num_psf), intent(in) psf_mesh, type(ucd_data), dimension(num_psf), intent(inout) psf_out)
Definition at line 49 of file output_4_psf.f90.
References calypso_mpi::calypso_mpi_barrier(), set_ucd_data_to_type::link_ele_data_2_ucd(), set_ucd_data_to_type::link_field_data_to_ucd(), set_ucd_data_to_type::link_nele_stacks_2_ucd(), set_ucd_data_to_type::link_nnod_stacks_2_ucd(), set_ucd_data_to_type::link_node_data_2_ucd(), calypso_mpi::nprocs, and parallel_ucd_io_select::sel_write_parallel_ucd_mesh().
Referenced by t_cross_section::sectioning_initialize().