CALYPSO: select_exp_velocity_icb Module Reference
select_exp_velocity_icb Module Reference
Select boundary condition routines for velocity.
Functions/Subroutines
subroutine sel_icb_grad_vp_and_vorticity (sph_rj, r_2nd, sph_bc_U, ICB_Uspec, fdm2_free_ICB, g_sph_rj, is_velo, is_vort, rj_fld)
subroutine sel_icb_grad_poloidal_moment (sph_rj, r_2nd, sph_bc_U, ICB_Uspec, fdm2_free_ICB, is_fld, rj_fld)
subroutine sel_icb_sph_vorticity (sph_rj, r_2nd, sph_bc_U, fdm2_free_ICB, g_sph_rj, is_fld, is_rot, rj_fld)
subroutine sel_icb_sph_viscous_diffusion (sph_rj, r_2nd, sph_bc_U, fdm2_free_ICB, g_sph_rj, coef_diffuse, is_velo, is_viscous, rj_fld)
subroutine sel_icb_sph_vort_diffusion (sph_rj, r_2nd, sph_bc_U, fdm2_free_ICB, g_sph_rj, coef_diffuse, is_vort, is_w_diffuse, rj_fld)
Detailed Description
Select boundary condition routines for velocity.
      subroutine sel_ICB_grad_vp_and_vorticity(sph_rj, r_2nd,         &
     &          sph_bc_U, ICB_Uspec, fdm2_free_ICB, g_sph_rj,         &
     &          is_velo, is_vort, rj_fld)
        Address for input:    is_velo, is_velo+2
        Address for solution: is_velo+1,
                              is_vort, is_vort+2, is_vort+1
      subroutine sel_ICB_grad_poloidal_moment                         &
     &         (sph_rj, r_2nd, sph_bc_U, ICB_Uspec, fdm2_free_ICB,    &
     &          is_fld, rj_fld)
        Address for input:    is_fld, is_fld+2
        Address for solution: is_fld+1
      subroutine sel_ICB_sph_vorticity                                &
     &         (sph_rj, r_2nd, sph_bc_U, fdm2_free_ICB, g_sph_rj,     &
     &          is_fld, is_rot, rj_fld)
        Address for input:    is_fld, is_fld+2
        Address for solution: is_rot, is_rot+2, is_rot+1
      subroutine sel_ICB_sph_viscous_diffusion(sph_rj, r_2nd,         &
     &          sph_bc_U, fdm2_free_ICB, g_sph_rj, coef_diffuse,      &
     &          is_velo, is_viscous, rj_fld)
        Address for input:    is_velo, is_velo+2
        Address for solution: is_viscous, is_viscous+2, is_viscous+1
      subroutine sel_ICB_sph_vort_diffusion(sph_rj, r_2nd,            &
     &          sph_bc_U, fdm2_free_ICB, g_sph_rj, coef_diffuse,      &
     &          is_vort, is_w_diffuse, rj_fld)
        Address for input:    is_vort, is_vort+2
        Address for solution: is_w_diffuse, is_w_diffuse+2,
                              is_w_diffuse+1
          type(sph_rj_grid), intent(in) :: sph_rj
          type(sph_boundary_type), intent(in) :: sph_bc_U
          type(sph_vector_BC_coef), intent(in) :: ICB_Uspec
          type(fdm2_free_slip), intent(in) :: fdm2_free_ICB
          type(fdm_matrices), intent(in) :: r_2nd
          type(phys_data), intent(inout) :: rj_fld
Function/Subroutine Documentation
sel_icb_grad_poloidal_moment()
subroutine select_exp_velocity_icb::sel_icb_grad_poloidal_moment (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc_U, type(sph_vector_bc_coef), intent(in) ICB_Uspec, type(fdm2_free_slip), intent(in) fdm2_free_ICB, integer(kind = kint), intent(in) is_fld, type(phys_data), intent(inout) rj_fld)
Definition at line 140 of file select_exp_velocity_ICB.f90.
References set_sph_exp_nod_center::cal_dsdr_sph_center_2(), set_sph_exp_free_icb::cal_sph_nod_icb_free_vpol2(), set_sph_exp_fix_vector_icb::cal_sph_nod_icb_rigid_vect(), set_sph_exp_rigid_icb::cal_sph_nod_icb_rigid_velo2(), set_sph_exp_rigid_icb::cal_sph_nod_icb_rotate_velo2(), t_boundary_params_sph_mhd::iflag_evolve_field, t_boundary_params_sph_mhd::iflag_fixed_field, t_boundary_params_sph_mhd::iflag_free_slip, t_boundary_params_sph_mhd::iflag_rotatable_ic, and t_boundary_params_sph_mhd::iflag_sph_fill_center.
Referenced by cal_sol_sph_fluid_crank::cal_sol_velo_by_vort_sph_crank(), and const_sph_radial_grad::const_grad_poloidal_moment().
sel_icb_grad_vp_and_vorticity()
subroutine select_exp_velocity_icb::sel_icb_grad_vp_and_vorticity (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc_U, type(sph_vector_bc_coef), intent(in) ICB_Uspec, type(fdm2_free_slip), intent(in) fdm2_free_ICB, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, integer(kind = kint), intent(in) is_velo, integer(kind = kint), intent(in) is_vort, type(phys_data), intent(inout) rj_fld)
Definition at line 73 of file select_exp_velocity_ICB.f90.
References set_sph_exp_fix_vector_icb::cal_sph_nod_icb_fixed_rot2(), set_sph_exp_free_icb::cal_sph_nod_icb_free_v_and_w(), set_sph_exp_rigid_icb::cal_sph_nod_icb_rigid_rot2(), set_sph_exp_fix_vector_icb::cal_sph_nod_icb_rigid_vect(), set_sph_exp_rigid_icb::cal_sph_nod_icb_rigid_velo2(), set_sph_exp_rigid_icb::cal_sph_nod_icb_rotate_velo2(), t_boundary_params_sph_mhd::iflag_evolve_field, t_boundary_params_sph_mhd::iflag_fixed_field, t_boundary_params_sph_mhd::iflag_free_slip, t_boundary_params_sph_mhd::iflag_rotatable_ic, t_boundary_params_sph_mhd::iflag_sph_fill_center, and set_sph_exp_nod_center::sph_center_fld_and_curl().
Referenced by const_sph_radial_grad::const_grad_vp_and_vorticity().
sel_icb_sph_viscous_diffusion()
subroutine select_exp_velocity_icb::sel_icb_sph_viscous_diffusion (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc_U, type(fdm2_free_slip), intent(in) fdm2_free_ICB, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, real(kind = kreal), intent(in) coef_diffuse, integer(kind = kint), intent(in) is_velo, integer(kind = kint), intent(in) is_viscous, type(phys_data), intent(inout) rj_fld)
Definition at line 235 of file select_exp_velocity_ICB.f90.
References set_sph_exp_nod_center::cal_dsdr_sph_center_2(), cal_sph_exp_fixed_scalar::cal_dsdr_sph_no_bc_in_2(), cal_inner_core_rotation::cal_icore_viscous_drag_explicit(), set_sph_exp_nod_center::cal_sph_nod_center_diffuse2(), set_sph_exp_fix_vector_icb::cal_sph_nod_icb_fixed_diffuse2(), set_sph_exp_free_icb::cal_sph_nod_icb_free_diffuse2(), set_sph_exp_rigid_icb::cal_sph_nod_icb_rigid_diffuse2(), t_boundary_params_sph_mhd::iflag_evolve_field, t_boundary_params_sph_mhd::iflag_fixed_field, t_boundary_params_sph_mhd::iflag_free_slip, t_boundary_params_sph_mhd::iflag_rotatable_ic, and t_boundary_params_sph_mhd::iflag_sph_fill_center.
Referenced by const_sph_rotation::const_sph_viscous_by_vort2(), and const_sph_diffusion::const_sph_viscous_diffusion().
sel_icb_sph_vort_diffusion()
subroutine select_exp_velocity_icb::sel_icb_sph_vort_diffusion (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc_U, type(fdm2_free_slip), intent(in) fdm2_free_ICB, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, real(kind = kreal), intent(in) coef_diffuse, integer(kind = kint), intent(in) is_vort, integer(kind = kint), intent(in) is_w_diffuse, type(phys_data), intent(inout) rj_fld)
Definition at line 309 of file select_exp_velocity_ICB.f90.
References set_sph_exp_nod_center::cal_dsdr_sph_center_2(), cal_inner_core_rotation::cal_icore_viscous_drag_explicit(), set_sph_exp_nod_center::cal_sph_nod_center_diffuse2(), set_sph_exp_fix_vector_icb::cal_sph_nod_icb_fixed_diffuse2(), set_sph_exp_free_icb::cal_sph_nod_icb_free_w_diffuse2(), t_boundary_params_sph_mhd::iflag_free_slip, t_boundary_params_sph_mhd::iflag_rotatable_ic, and t_boundary_params_sph_mhd::iflag_sph_fill_center.
Referenced by const_sph_diffusion::const_sph_vorticirty_diffusion().
sel_icb_sph_vorticity()
subroutine select_exp_velocity_icb::sel_icb_sph_vorticity (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc_U, type(fdm2_free_slip), intent(in) fdm2_free_ICB, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_rot, type(phys_data), intent(inout) rj_fld)
Definition at line 187 of file select_exp_velocity_ICB.f90.
References set_sph_exp_nod_center::cal_sph_nod_center_rot2(), set_sph_exp_fix_vector_icb::cal_sph_nod_icb_fixed_rot2(), set_sph_exp_free_icb::cal_sph_nod_icb_free_rot2(), set_sph_exp_rigid_icb::cal_sph_nod_icb_rigid_rot2(), t_boundary_params_sph_mhd::iflag_evolve_field, t_boundary_params_sph_mhd::iflag_fixed_field, t_boundary_params_sph_mhd::iflag_free_slip, and t_boundary_params_sph_mhd::iflag_sph_fill_center.
Referenced by const_sph_rotation::const_sph_force_rot2(), and const_sph_rotation::const_sph_vorticity().