CALYPSO: t_bc_data_list Module Reference
t_bc_data_list Module Reference
Boundary condition lists for MHD dynamo model.
Data Types
type boundary_condition_list
Structure for boundary condition list.
type boundary_condition_lists
Structure for boundary group data list.
type mhd_bc_lists
Structure for boundary condition lists for MHD.
Functions/Subroutines
subroutine alloc_bc_type_ctl (bc_list)
subroutine dealloc_bc_type_ctl (bc_list)
subroutine deallocate_surf_bc_lists (MHD_prop, MHD_BC)
subroutine alloc_nod_bc_list (fld_BC)
subroutine alloc_surf_bc_list (fld_BC)
subroutine dealloc_nod_bc_list (fld_BC)
subroutine dealloc_surf_bc_list (fld_BC)
Detailed Description
Boundary condition lists for MHD dynamo model.
      subroutine alloc_bc_type_ctl(bc_list)
      subroutine dealloc_bc_type_ctl(bc_list)
        type(boundary_condition_list), intent(inout) :: bc_list
      subroutine alloc_nod_bc_list(fld_BC)
      subroutine alloc_surf_bc_list(fld_BC)
      subroutine dealloc_nod_bc_list(fld_BC)
      subroutine dealloc_surf_bc_list(fld_BC)
        type(boundary_condition_lists), intent(inout) :: fld_BC
      subroutine deallocate_surf_bc_lists(MHD_prop, MHD_BC)
Function/Subroutine Documentation
alloc_bc_type_ctl()
subroutine t_bc_data_list::alloc_bc_type_ctl (type(boundary_condition_list), intent(inout) bc_list)
Definition at line 80 of file t_bc_data_list.f90.
Referenced by alloc_nod_bc_list(), alloc_surf_bc_list(), set_control_4_composition::s_set_control_4_composition(), set_control_4_magne::s_set_control_4_magne(), set_control_4_press::s_set_control_4_press(), set_control_4_temp::s_set_control_4_temp(), and set_control_4_velo::s_set_control_4_velo().
alloc_nod_bc_list()
subroutine t_bc_data_list::alloc_nod_bc_list (type(boundary_condition_lists), intent(inout) fld_BC)
Definition at line 158 of file t_bc_data_list.f90.
References alloc_bc_type_ctl().
alloc_surf_bc_list()
subroutine t_bc_data_list::alloc_surf_bc_list (type(boundary_condition_lists), intent(inout) fld_BC)
Definition at line 168 of file t_bc_data_list.f90.
References alloc_bc_type_ctl().
dealloc_bc_type_ctl()
subroutine t_bc_data_list::dealloc_bc_type_ctl (type(boundary_condition_list), intent(inout) bc_list)
Definition at line 98 of file t_bc_data_list.f90.
Referenced by dealloc_nod_bc_list(), and dealloc_surf_bc_list().
dealloc_nod_bc_list()
subroutine t_bc_data_list::dealloc_nod_bc_list (type(boundary_condition_lists), intent(inout) fld_BC)
Definition at line 179 of file t_bc_data_list.f90.
References dealloc_bc_type_ctl().
dealloc_surf_bc_list()
subroutine t_bc_data_list::dealloc_surf_bc_list (type(boundary_condition_lists), intent(inout) fld_BC)
Definition at line 189 of file t_bc_data_list.f90.
References dealloc_bc_type_ctl().
Referenced by deallocate_surf_bc_lists().
deallocate_surf_bc_lists()
subroutine t_bc_data_list::deallocate_surf_bc_lists (type(mhd_evolution_param), intent(in) MHD_prop, type(mhd_bc_lists), intent(inout) MHD_BC)
Definition at line 112 of file t_bc_data_list.f90.
References dealloc_surf_bc_list().