CALYPSO: mpi_load_mesh_data Module Reference
mpi_load_mesh_data Module Reference
Copy FEM mesh data from IO structure.
Functions/Subroutines
subroutine mpi_input_mesh (mesh_file, num_pe, fem)
subroutine mpi_input_mesh_geometry (mesh_file, num_pe, mesh)
subroutine mpi_input_node_geometry (mesh_file, num_pe, node)
subroutine sync_group_name_4_empty (num_pe, nod_grp, ele_grp, sf_grp)
subroutine mpi_output_mesh (mesh_file, mesh, group)
Detailed Description
Copy FEM mesh data from IO structure.
      subroutine mpi_input_mesh(mesh_file, num_pe, fem)
        type(mesh_data), intent(inout) :: fem
      subroutine mpi_input_mesh_geometry(mesh_file, num_pe, mesh)
        type(field_IO_params), intent(in) ::  mesh_file
        type(mesh_geometry), intent(inout) :: mesh
      subroutine mpi_input_node_geometry(mesh_file, num_pe, node)
        type(field_IO_params), intent(in) ::  mesh_file
        type(node_data), intent(inout) :: node
      subroutine sync_group_name_4_empty                              &
     &         (num_pe, nod_grp, ele_grp, sf_grp)
      subroutine mpi_output_mesh(mesh_file, mesh, group)
        type(field_IO_params), intent(in) ::  mesh_file
        type(mesh_geometry), intent(inout) :: mesh
        type(mesh_groups), intent(inout) ::   group
Function/Subroutine Documentation
mpi_input_mesh()
subroutine mpi_load_mesh_data::mpi_input_mesh (type(field_io_params), intent(in) mesh_file, integer, intent(in) num_pe, type(mesh_data), intent(inout) fem)
Definition at line 51 of file mpi_load_mesh_data.f90.
References calypso_mpi::my_rank, calypso_mpi::nprocs, mesh_mpi_io_select::sel_mpi_read_mesh(), load_mesh_data::set_mesh(), load_mesh_data::set_zero_mesh_data(), and sync_group_name_4_empty().
Referenced by t_check_and_make_sph_mesh::load_para_sph_and_fem_mesh(), load_mesh_and_field_4_viz::mesh_setup_4_viz(), and para_const_kemoview_mesh::pickup_surface_mesh().
mpi_input_mesh_geometry()
subroutine mpi_load_mesh_data::mpi_input_mesh_geometry (type(field_io_params), intent(in) mesh_file, integer, intent(in) num_pe, type(mesh_geometry), intent(inout) mesh)
Definition at line 84 of file mpi_load_mesh_data.f90.
References calypso_mpi::my_rank, calypso_mpi::nprocs, mesh_mpi_io_select::sel_mpi_read_mesh_geometry(), load_mesh_data::set_mesh_geometry_data(), and load_mesh_data::set_zero_mesh_data().
mpi_input_node_geometry()
subroutine mpi_load_mesh_data::mpi_input_node_geometry (type(field_io_params), intent(in) mesh_file, integer, intent(in) num_pe, type(node_data), intent(inout) node)
Definition at line 111 of file mpi_load_mesh_data.f90.
References calypso_mpi::my_rank, calypso_mpi::nprocs, mesh_mpi_io_select::sel_mpi_read_geometry_size(), load_mesh_data::set_node_geometry_data(), and load_mesh_data::set_zero_node_data().
mpi_output_mesh()
subroutine mpi_load_mesh_data::mpi_output_mesh (type(field_io_params), intent(in) mesh_file, type(mesh_geometry), intent(inout) mesh, type(mesh_groups), intent(inout) group)
Definition at line 214 of file mpi_load_mesh_data.f90.
References t_comm_table::copy_comm_tbl_type(), set_element_data_4_io::copy_ele_connect_to_io(), copy_mesh_structures::copy_node_geometry_types(), t_mesh_data::dealloc_groups_data(), t_mesh_data::dealloc_mesh_geometry_base(), mesh_mpi_io_select::sel_mpi_write_mesh_file(), and load_mesh_data::set_grp_data_to_io().
Referenced by const_fem_mesh_sph_mhd::const_fem_mesh_4_sph_mhd().
sync_group_name_4_empty()
subroutine mpi_load_mesh_data::sync_group_name_4_empty (integer, intent(in) num_pe, type(group_data), intent(inout) nod_grp, type(group_data), intent(inout) ele_grp, type(surface_group_data), intent(inout) sf_grp)
Definition at line 137 of file mpi_load_mesh_data.f90.
References t_group_data::alloc_group_item(), t_group_data::alloc_group_num(), t_group_data::alloc_sf_group_item(), t_group_data::alloc_sf_group_num(), calypso_mpi_char::calypso_mpi_bcast_character(), calypso_mpi_int::calypso_mpi_bcast_int(), transfer_to_long_integers::cast_long(), m_precision::kchara, and calypso_mpi::my_rank.
Referenced by mpi_input_mesh().