CALYPSO: gz_field_data_io Module Reference
gz_field_data_io Module Reference
Functions/Subroutines
subroutine write_gz_step_data (id_rank, i_time_step_IO, time_IO, delta_t_IO, zbuf)
subroutine read_gz_step_data (id_rank, i_time_step_IO, time_IO, delta_t_IO, zbuf, ierr_IO)
subroutine write_gz_field_data (nnod64, num_field, ntot_comp, ncomp_field, field_name, field_data, zbuf)
subroutine read_gz_field_data (nnod64, num_field, ntot_comp, ncomp_field, field_name, field_data, zbuf)
subroutine read_gz_field_name (nnod64, num_field, ncomp_field, field_name, zbuf)
subroutine, private write_gz_field_vect (d_name, nnod64, ndir, vector, zbuf)
subroutine, private read_gz_field_vect (nnod64, ndir, vector, zbuf)
subroutine, private skip_gz_field_vect (nnod64, ndir, zbuf)
Function/Subroutine Documentation
read_gz_field_data()
subroutine gz_field_data_io::read_gz_field_data (integer(kind=kint_gl), intent(in) nnod64, integer(kind=kint), intent(in) num_field, integer(kind=kint), intent(in) ntot_comp, integer(kind=kint), dimension(num_field), intent(in) ncomp_field, character(len=kchara), dimension(num_field), intent(inout) field_name, real(kind = kreal), dimension(nnod64,ntot_comp), intent(inout) field_data, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 152 of file gz_field_data_IO.f90.
References read_gz_field_vect(), and skip_gz_comment::skip_gz_comment_chara().
Referenced by gz_ucd_field_file_io::gz_read_alloc_ucd_2_ld_file(), gz_ucd_field_file_io::gz_read_ucd_2_fld_file(), gz_field_file_io::read_alloc_gz_field_file(), gz_field_file_io::read_alloc_gz_step_field_file(), gz_rst_data_io_by_fld::read_gz_rst_file(), and gz_field_file_io::read_gz_step_field_file().
read_gz_field_name()
subroutine gz_field_data_io::read_gz_field_name (integer(kind=kint_gl), intent(in) nnod64, integer(kind=kint), intent(in) num_field, integer(kind=kint), dimension(num_field), intent(in) ncomp_field, character(len=kchara), dimension(num_field), intent(inout) field_name, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 181 of file gz_field_data_IO.f90.
References skip_gz_comment::skip_gz_comment_chara(), and skip_gz_field_vect().
Referenced by gz_field_file_io::read_alloc_gz_step_field_head().
read_gz_field_vect()
subroutine, private gz_field_data_io::read_gz_field_vect (integer(kind=kint_gl), intent(in) nnod64, integer(kind=kint), intent(in) ndir, real(kind = kreal), dimension(nnod64,ndir), intent(inout) vector, type(buffer_4_gzip), intent(inout) zbuf) private
Definition at line 240 of file gz_field_data_IO.f90.
References gzip_file_access::get_one_line_text_from_gz().
Referenced by read_gz_field_data().
read_gz_step_data()
subroutine gz_field_data_io::read_gz_step_data (integer, intent(in) id_rank, integer(kind = kint), intent(inout) i_time_step_IO, real(kind = kreal), intent(inout) time_IO, real(kind = kreal), intent(inout) delta_t_IO, type(buffer_4_gzip), intent(inout) zbuf, integer(kind = kint), intent(inout) ierr_IO)
Definition at line 74 of file gz_field_data_IO.f90.
References skip_gz_comment::skip_gz_comment_chara(), and skip_gz_comment::skip_gz_comment_int().
Referenced by gz_ucd_field_file_io::gz_read_alloc_ucd_2_ld_file(), gz_ucd_field_file_io::gz_read_ucd_2_fld_file(), gz_field_file_io::read_alloc_gz_step_field_file(), gz_field_file_io::read_alloc_gz_step_field_head(), gz_rst_data_io_by_fld::read_gz_rst_comps(), gz_rst_data_io_by_fld::read_gz_rst_file(), and gz_field_file_io::read_gz_step_field_file().
skip_gz_field_vect()
subroutine, private gz_field_data_io::skip_gz_field_vect (integer(kind=kint_gl), intent(in) nnod64, integer(kind=kint), intent(in) ndir, type(buffer_4_gzip), intent(inout) zbuf) private
Definition at line 261 of file gz_field_data_IO.f90.
References gzip_file_access::get_one_line_text_from_gz().
Referenced by read_gz_field_name().
write_gz_field_data()
subroutine gz_field_data_io::write_gz_field_data (integer(kind=kint_gl), intent(in) nnod64, integer(kind=kint), intent(in) num_field, integer(kind=kint), intent(in) ntot_comp, integer(kind=kint), dimension(num_field), intent(in) ncomp_field, character(len=kchara), dimension(num_field), intent(in) field_name, real(kind = kreal), dimension(nnod64,ntot_comp), intent(in) field_data, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 111 of file gz_field_data_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf(), and write_gz_field_vect().
Referenced by gz_ucd_field_file_io::gz_write_ucd_2_fld_file(), and gz_field_file_io::write_gz_step_field_file().
write_gz_field_vect()
subroutine, private gz_field_data_io::write_gz_field_vect (character(len=kchara), intent(in) d_name, integer(kind=kint_gl), intent(in) nnod64, integer(kind=kint), intent(in) ndir, real(kind = kreal), dimension(nnod64,ndir), intent(in) vector, type(buffer_4_gzip), intent(inout) zbuf) private
Definition at line 209 of file gz_field_data_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf().
Referenced by write_gz_field_data().
write_gz_step_data()
subroutine gz_field_data_io::write_gz_step_data (integer, intent(in) id_rank, integer(kind=kint), intent(in) i_time_step_IO, real(kind = kreal), intent(in) time_IO, real(kind = kreal), intent(in) delta_t_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 40 of file gz_field_data_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf().
Referenced by gz_ucd_field_file_io::gz_write_ucd_2_fld_file(), and gz_field_file_io::write_gz_step_field_file().