CALYPSO: t_viz_vtk_convert Module Reference
t_viz_vtk_convert Module Reference
Top routine for VTK convert.
Functions/Subroutines
subroutine init_visualize_convert_vtk (geofem, nod_fld, ucd_step, output_vtk_fmt_ctl, ucd_file_IO, vtk_file_IO, vtk_out)
subroutine visualize_convert_vtk (i_step, istep_ucd, time_d, vtk_file_IO, vtk_out)
Detailed Description
Top routine for VTK convert.
      subroutine init_visualize_surface                               &
     &         (geofem, nod_fld, ucd_step, output_vtk_fmt_ctl,        &
     &          ucd_file_IO, vtk_file_IO, vtk_out)
        type(mesh_data), intent(in) :: geofem
        type(phys_data), intent(in) :: nod_fld
        type(IO_step_param), intent(in) :: ucd_step
        type(field_IO_params), intent(in) :: ucd_file_IO
        type(read_character_item), intent(in) :: output_vtk_fmt_ctl
        type(field_IO_params), intent(inout) :: vtk_file_IO
        type(ucd_data), intent(inout) :: vtk_out
      subroutine visualize_convert_vtk                                &
     &         (i_step, istep_ucd, time_d, vtk_file_IO, vtk_out)
        type(time_data), intent(in) :: time_d
        type(field_IO_params), intent(in) :: vtk_file_IO
        type(ucd_data), intent(in) :: vtk_out
Function/Subroutine Documentation
init_visualize_convert_vtk()
subroutine t_viz_vtk_convert::init_visualize_convert_vtk (type(mesh_data), intent(in) geofem, type(phys_data), intent(in) nod_fld, type(io_step_param), intent(in) ucd_step, type(read_character_item), intent(in) output_vtk_fmt_ctl, type(field_io_params), intent(in) ucd_file_IO, type(field_io_params), intent(inout) vtk_file_IO, type(ucd_data), intent(inout) vtk_out)
Definition at line 55 of file t_viz_VTK_convert.f90.
References calypso_mpi::calypso_mpi_abort(), m_field_file_format::choose_para_fld_file_format(), m_field_file_format::iflag_sgl_hdf5, m_field_file_format::iflag_sgl_vtk, m_field_file_format::iflag_sgl_vtk_gz, m_field_file_format::iflag_vtk, m_field_file_format::iflag_vtk_gz, and output_parallel_ucd_file::link_output_grd_file().
Referenced by analyzer_vtk_convert::init_analyzer_vtk_convert().
visualize_convert_vtk()
subroutine t_viz_vtk_convert::visualize_convert_vtk (integer(kind = kint), intent(in) i_step, integer(kind = kint), intent(in) istep_ucd, type(time_data), intent(in) time_d, type(field_io_params), intent(in) vtk_file_IO, type(ucd_data), intent(in) vtk_out)
Definition at line 102 of file t_viz_VTK_convert.f90.
References m_work_time::end_elapsed_time(), m_elapsed_labels_4_viz::iflag_viz_time, m_elapsed_labels_4_viz::ist_elapsed_viz, parallel_ucd_io_select::sel_write_parallel_ucd_file(), and m_work_time::start_elapsed_time().
Referenced by analyzer_vtk_convert::analyze_vtk_convert().