CALYPSO: set_control_4_temp Module Reference
set_control_4_temp Module Reference
set boundary conditions for temperature from control data
Functions/Subroutines
subroutine s_set_control_4_temp (ht_prop, node_bc_T_ctl, surf_bc_HF_ctl, temp_nod, h_flux_surf)
Detailed Description
set boundary conditions for temperature from control data
      subroutine s_set_control_4_temp                                 &
     &         (ht_prop, node_bc_T_ctl, surf_bc_HF_ctl,               &
     &          temp_nod, h_flux_surf)
        type(scalar_property), intent(in) :: ht_prop
        type(ctl_array_c2r), intent(in) :: node_bc_T_ctl
        type(ctl_array_c2r), intent(in) :: surf_bc_HF_ctl
        type(boundary_condition_list), intent(inout) :: temp_nod
        type(boundary_condition_list), intent(inout) :: h_flux_surf
Function/Subroutine Documentation
s_set_control_4_temp()
subroutine set_control_4_temp::s_set_control_4_temp (type(scalar_property), intent(in) ht_prop, type(ctl_array_c2r), intent(in) node_bc_T_ctl, type(ctl_array_c2r), intent(in) surf_bc_HF_ctl, type(boundary_condition_list), intent(inout) temp_nod, type(boundary_condition_list), intent(inout) h_flux_surf)
Definition at line 34 of file set_control_4_temp.f90.
References t_bc_data_list::alloc_bc_type_ctl(), t_physical_property::id_no_evolution, m_machine_parameter::iflag_debug, m_machine_parameter::iflag_full_msg, set_node_group_types::set_bc_group_types_fluxes(), set_node_group_types::set_bc_group_types_scalar(), set_node_group_types::set_bc_group_types_sgs_scalar(), set_node_group_types::set_bc_group_types_sph_center(), and set_surface_group_types::set_surf_group_types_scalar().
Referenced by set_control_sph_mhd::set_control_sph_mhd_bcs().