CALYPSO: set_radius_4_sph_dynamo Module Reference
set_radius_4_sph_dynamo Module Reference
Set radial information.
Functions/Subroutines
subroutine set_radius_dat_4_sph_dynamo (nri, radius_1d_rj_r, radial_rj_grp, iflag_radial_grid, nlayer_ICB, nlayer_CMB, nlayer_2_center, ar_1d_rj, r_ele_rj, ar_ele_rj, r_ICB, r_CMB, R_earth)
Detailed Description
Set radial information.
      Programmed by H. Matsui on June., 1994
      modified by H. Matsui on Apr., 2009
      subroutine set_radius_dat_4_sph_dynamo                          &
     &         (nri, radius_1d_rj_r, radial_rj_grp, iflag_radial_grid,&
     &          nlayer_ICB, nlayer_CMB, nlayer_2_center,              &
     &          ar_1d_rj, r_ele_rj, ar_ele_rj, r_ICB, r_CMB, R_earth)
        type(group_data), intent(in) :: radial_rj_grp
***********************************************************************
*
*       ar_1d_rj(k,1)   : 1 / r
*       ar_1d_rj(k,2)   : 1 / r**2
*       ar_1d_rj(k,3)   : 1 / r**3
*
***********************************************************************
Function/Subroutine Documentation
set_radius_dat_4_sph_dynamo()
subroutine set_radius_4_sph_dynamo::set_radius_dat_4_sph_dynamo (integer(kind = kint), intent(in) nri, real(kind = kreal), dimension(nri), intent(in) radius_1d_rj_r, type(group_data), intent(in) radial_rj_grp, integer(kind = kint), intent(inout) iflag_radial_grid, integer(kind = kint), intent(inout) nlayer_ICB, integer(kind = kint), intent(inout) nlayer_CMB, integer(kind = kint), intent(inout) nlayer_2_center, real(kind = kreal), dimension(nri,3), intent(inout) ar_1d_rj, real(kind = kreal), dimension(nri), intent(inout) r_ele_rj, real(kind = kreal), dimension(nri,3), intent(inout) ar_ele_rj, real(kind = kreal), intent(inout) r_ICB, real(kind = kreal), intent(inout) r_CMB, real(kind = kreal), dimension(0:2), intent(inout) R_earth)
Definition at line 47 of file set_radius_4_sph_dynamo.f90.
References t_spheric_parameter::cmb_nod_grp_name, skip_comment_f::cmp_no_case(), t_spheric_parameter::ctr_nod_grp_name, m_constants::half, t_spheric_parameter::icb_nod_grp_name, m_machine_parameter::iflag_debug, m_constants::one, and set_radial_grid_sph_shell::set_radial_distance_flag().
Referenced by parallel_load_data_4_sph::set_radius_dat_sph_mhd().