CALYPSO: m_section_file_extensions Module Reference
m_section_file_extensions Module Reference
Integer flags for field data file format.
Data Types
type psf_extensions
Functions/Subroutines
integer(kind=kint) function section_format_id_from_input ()
integer(kind=kint) function psf_to_vtk_format_id_from_input ()
character(len=6 *(3+6+4)) function psf_extension_list ()
character(len=4 *(3+6+4)) function, private psf_to_vtk_format_list ()
integer(kind=kint) function, private section_format_id_from_ext (file_ext, psf_exts)
subroutine, private set_psf_extensions (psf_exts)
Detailed Description
Integer flags for field data file format.
      integer(kind = kint) function                                   &
     &                    section_format_id_from_input()
      integer(kind = kint) function                                   &
     &                    psf_to_vtk_format_id_from_input()
      function psf_extension_list()
        character(len= 6*(3+6+5)) :: psf_extension_list
      integer(kind = kint) function                                   &
     &                    section_format_id_from_ext(file_ext)
      subroutine set_psf_extensions(psf_exts)
        type(psf_extensions), intent(inout) :: psf_exts
Function/Subroutine Documentation
psf_extension_list()
character(len= 6*(3+6+4)) function m_section_file_extensions::psf_extension_list
Definition at line 93 of file m_section_file_extensions.f90.
References set_psf_extensions().
Referenced by section_format_id_from_input().
psf_to_vtk_format_id_from_input()
integer(kind = kint) function m_section_file_extensions::psf_to_vtk_format_id_from_input
Definition at line 73 of file m_section_file_extensions.f90.
References psf_to_vtk_format_list(), section_format_id_from_ext(), and set_psf_extensions().
Referenced by psf_file_to_vtk().
psf_to_vtk_format_list()
character(len= 4*(3+6+4)) function, private m_section_file_extensions::psf_to_vtk_format_list private
Definition at line 114 of file m_section_file_extensions.f90.
References set_psf_extensions().
Referenced by psf_to_vtk_format_id_from_input().
section_format_id_from_ext()
integer(kind = kint) function, private m_section_file_extensions::section_format_id_from_ext (character(len = kchara), intent(in) file_ext, type(psf_extensions), intent(in) psf_exts) private
Definition at line 134 of file m_section_file_extensions.f90.
References skip_comment_f::cmp_no_case().
Referenced by psf_to_vtk_format_id_from_input(), and section_format_id_from_input().
section_format_id_from_input()
integer(kind = kint) function m_section_file_extensions::section_format_id_from_input
Definition at line 54 of file m_section_file_extensions.f90.
References psf_extension_list(), section_format_id_from_ext(), and set_psf_extensions().
set_psf_extensions()
subroutine, private m_section_file_extensions::set_psf_extensions (type(psf_extensions), intent(inout) psf_exts) private
Definition at line 175 of file m_section_file_extensions.f90.
References set_parallel_file_name::gz_ext, set_ucd_extensions::inp_ext, set_ucd_extensions::sdt_ext, set_ucd_extensions::sfm_ext, set_ucd_extensions::udt_ext, set_ucd_extensions::vtd_ext, and set_ucd_extensions::vtk_ext.
Referenced by psf_extension_list(), psf_to_vtk_format_id_from_input(), psf_to_vtk_format_list(), and section_format_id_from_input().