CALYPSO: set_nodal_field_name Module Reference
set_nodal_field_name Module Reference
Set field names from control data.
Functions/Subroutines
subroutine ordering_field_by_viz (field_ctl, fld)
subroutine ordering_field_by_comp_viz (field_ctl, fld)
subroutine count_field_4_monitor (fld, num_field_monitor, ntot_comp_monitor)
subroutine, private set_vector_field_name (phys_name_ctl, flag_viz, flag_monitor, fld, flag)
subroutine, private set_scalar_field_name (phys_name_ctl, flag_viz, flag_monitor, fld, flag)
subroutine, private set_tensor_field_name (phys_name_ctl, flag_viz, flag_monitor, fld, flag)
logical function check_vis_control_flag (visualize_ctl)
logical function check_monitor_control_flag (monitor_ctl)
subroutine set_vis_control_flag (iflag_viz, visualize_ctl)
subroutine set_monitor_control_flag (iflag_fld_monitor, monitor_ctl)
Variables
character(len=kchara), parameter cflag_viz_on = 'Viz_On'
character(len=kchara), parameter cflag_viz_off = 'Viz_Off'
character(len=kchara), parameter cflag_monitor_on = 'Monitor_On'
character(len=kchara), parameter cflag_monitor_off = 'Monitor_Off'
Detailed Description
Set field names from control data.
      subroutine ordering_field_by_viz(field_ctl, fld)
      subroutine ordering_field_by_comp_viz(field_ctl, fld)
        type(ctl_array_c3), intent(in) :: field_ctl
        type(phys_data), intent(inout) :: fld
      subroutine count_field_4_monitor                                &
     &         (fld, num_field_monitor, ntot_comp_monitor)
        type(phys_data), intent(in) :: fld
      logical function check_vis_control_flag(visualize_ctl)
      logical function check_monitor_control_flag(monitor_ctl)
      subroutine set_vis_control_flag(iflag_viz, visualize_ctl)
      subroutine set_monitor_control_flag                             &
     &         (iflag_fld_monitor, monitor_ctl)
Function/Subroutine Documentation
check_monitor_control_flag()
logical function set_nodal_field_name::check_monitor_control_flag (character(len = kchara), intent(in) monitor_ctl)
Definition at line 252 of file set_nodal_field_name.f90.
References cflag_monitor_on, and skip_comment_f::cmp_no_case().
Referenced by ordering_field_by_comp_viz(), and ordering_field_by_viz().
check_vis_control_flag()
logical function set_nodal_field_name::check_vis_control_flag (character(len = kchara), intent(in) visualize_ctl)
Definition at line 240 of file set_nodal_field_name.f90.
References cflag_viz_on, and skip_comment_f::cmp_no_case().
Referenced by ordering_field_by_comp_viz(), and ordering_field_by_viz().
count_field_4_monitor()
subroutine set_nodal_field_name::count_field_4_monitor (type(phys_data), intent(in) fld, integer(kind = kint), intent(inout) num_field_monitor, integer(kind = kint), intent(inout) ntot_comp_monitor)
Definition at line 122 of file set_nodal_field_name.f90.
Referenced by set_control_sph_mhd::set_control_sph_mhd_w_viz().
ordering_field_by_comp_viz()
subroutine set_nodal_field_name::ordering_field_by_comp_viz (type(ctl_array_c3), intent(in) field_ctl, type(phys_data), intent(inout) fld)
Definition at line 85 of file set_nodal_field_name.f90.
References t_phys_data::alloc_phys_name_type(), check_monitor_control_flag(), check_vis_control_flag(), set_scalar_field_name(), set_tensor_field_name(), and set_vector_field_name().
Referenced by set_control_field_data::set_control_field_by_comp_viz().
ordering_field_by_viz()
subroutine set_nodal_field_name::ordering_field_by_viz (type(ctl_array_c3), intent(in) field_ctl, type(phys_data), intent(inout) fld)
Definition at line 53 of file set_nodal_field_name.f90.
References t_phys_data::alloc_phys_name_type(), check_monitor_control_flag(), check_vis_control_flag(), set_scalar_field_name(), set_tensor_field_name(), and set_vector_field_name().
Referenced by set_control_field_data::s_set_control_field_data().
set_monitor_control_flag()
subroutine set_nodal_field_name::set_monitor_control_flag (integer (kind = kint), intent(in) iflag_fld_monitor, character(len = kchara), intent(inout) monitor_ctl)
Definition at line 281 of file set_nodal_field_name.f90.
References cflag_monitor_off, and cflag_monitor_on.
set_scalar_field_name()
subroutine, private set_nodal_field_name::set_scalar_field_name (character(len = kchara), intent(in) phys_name_ctl, logical, intent(in) flag_viz, logical, intent(in) flag_monitor, type(phys_data), intent(inout) fld, logical, intent(inout) flag) private
Definition at line 179 of file set_nodal_field_name.f90.
References t_phys_data::append_field_name_list(), m_energy_flux_labels::buoyancy_flux, m_energy_flux_labels::buoyancy_work, and set_mhd_field_address::check_scalar_fields().
Referenced by ordering_field_by_comp_viz(), and ordering_field_by_viz().
set_tensor_field_name()
subroutine, private set_nodal_field_name::set_tensor_field_name (character(len = kchara), intent(in) phys_name_ctl, logical, intent(in) flag_viz, logical, intent(in) flag_monitor, type(phys_data), intent(inout) fld, logical, intent(inout) flag) private
Definition at line 210 of file set_nodal_field_name.f90.
References t_phys_data::append_field_name_list(), set_mhd_field_address::check_asym_tensor_fields(), and set_mhd_field_address::check_sym_tensor_fields().
Referenced by ordering_field_by_comp_viz(), and ordering_field_by_viz().
set_vector_field_name()
subroutine, private set_nodal_field_name::set_vector_field_name (character(len = kchara), intent(in) phys_name_ctl, logical, intent(in) flag_viz, logical, intent(in) flag_monitor, type(phys_data), intent(inout) fld, logical, intent(inout) flag) private
Definition at line 148 of file set_nodal_field_name.f90.
References t_phys_data::append_field_name_list(), set_mhd_field_address::check_vector_fields(), m_field_product_labels::geostrophic_balance, and m_field_product_labels::rest_of_geostrophic.
Referenced by ordering_field_by_comp_viz(), and ordering_field_by_viz().
set_vis_control_flag()
subroutine set_nodal_field_name::set_vis_control_flag (integer (kind = kint), intent(in) iflag_viz, character(len = kchara), intent(inout) visualize_ctl)
Definition at line 266 of file set_nodal_field_name.f90.
References cflag_viz_off, and cflag_viz_on.
Variable Documentation
cflag_monitor_off
character(len = kchara), parameter set_nodal_field_name::cflag_monitor_off = 'Monitor_Off'
Definition at line 41 of file set_nodal_field_name.f90.
Referenced by set_monitor_control_flag().
cflag_monitor_on
character(len = kchara), parameter set_nodal_field_name::cflag_monitor_on = 'Monitor_On'
Definition at line 39 of file set_nodal_field_name.f90.
Referenced by check_monitor_control_flag(), and set_monitor_control_flag().
cflag_viz_off
character(len = kchara), parameter set_nodal_field_name::cflag_viz_off = 'Viz_Off'
Definition at line 37 of file set_nodal_field_name.f90.
Referenced by set_vis_control_flag().
cflag_viz_on
character(len = kchara), parameter set_nodal_field_name::cflag_viz_on = 'Viz_On'
Definition at line 36 of file set_nodal_field_name.f90.
Referenced by check_vis_control_flag(), and set_vis_control_flag().