CALYPSO: set_edge_hash_by_sf Module Reference
set_edge_hash_by_sf Module Reference
Hash table using sum of local node ID.
Functions/Subroutines
subroutine const_edge_hash_4_sf (numsurf, nnod_4_surf, ie_surf, ed_sf_tbl)
subroutine const_part_edge_hash_4_sf (numsurf, nnod_4_surf, ie_surf, numsurf_part, isf_part, ed_sf_tbl)
subroutine, private set_edge_hash_4_sf (numsurf, nnod_4_surf, ie_surf, ntot_id, ntot_list, num_edge_hash, istack_edge_hash, iend_edge_hash, iedge_hash)
subroutine, private set_part_edge_hash_4_sf (numsurf, nnod_4_surf, ie_surf, numsurf_part, isf_part, ntot_id, ntot_list, num_edge_hash, istack_edge_hash, iend_edge_hash, iedge_hash)
subroutine, private mark_all_edges_by_sf (numsurf, nnod_4_surf, ie_surf, ntot_id, ntot_list, istack_edge_hash, iend_edge_hash, iedge_hash, iedge_flag)
Detailed Description
Hash table using sum of local node ID.
      subroutine const_edge_hash_4_sf                                 &
     &         (numsurf, nnod_4_surf, ie_surf, ed_sf_tbl)
      subroutine const_part_edge_hash_4_sf                            &
     &         (numsurf, nnod_4_surf, ie_surf,                        &
     &          numsurf_part, isf_part, ed_sf_tbl)
        type(sum_hash_tbl), intent(inout) :: ed_sf_tbl
Function/Subroutine Documentation
const_edge_hash_4_sf()
subroutine set_edge_hash_by_sf::const_edge_hash_4_sf (integer(kind = kint), intent(in) numsurf, integer(kind = kint), intent(in) nnod_4_surf, integer(kind = kint), dimension(numsurf,nnod_4_surf), intent(in) ie_surf, type(sum_hash_tbl), intent(inout) ed_sf_tbl)
Definition at line 35 of file set_edge_hash_by_sf.f90.
References mark_all_edges_by_sf(), and set_edge_hash_4_sf().
Referenced by const_edge_4_viewer::const_all_edge_4_viewer().
const_part_edge_hash_4_sf()
subroutine set_edge_hash_by_sf::const_part_edge_hash_4_sf (integer(kind = kint), intent(in) numsurf, integer(kind = kint), intent(in) nnod_4_surf, integer(kind = kint), dimension(numsurf,nnod_4_surf), intent(in) ie_surf, integer(kind = kint), intent(in) numsurf_part, integer(kind = kint), dimension(numsurf_part), intent(in) isf_part, type(sum_hash_tbl), intent(inout) ed_sf_tbl)
Definition at line 61 of file set_edge_hash_by_sf.f90.
References mark_all_edges_by_sf(), and set_part_edge_hash_4_sf().
Referenced by const_edge_4_viewer::construct_edge_4_domain(), const_grp_edge_4_viewer::construct_edge_4_ele_grp(), and const_grp_edge_4_viewer::construct_edge_4_surf_grp().
mark_all_edges_by_sf()
subroutine, private set_edge_hash_by_sf::mark_all_edges_by_sf (integer(kind = kint), intent(in) numsurf, integer(kind = kint), intent(in) nnod_4_surf, integer(kind = kint), dimension(numsurf,nnod_4_surf), intent(in) ie_surf, integer(kind = kint_gl), intent(in) ntot_id, integer(kind = kint_gl), intent(in) ntot_list, integer(kind = kint_gl), dimension(0:ntot_id), intent(in) istack_edge_hash, integer(kind = kint_gl), intent(in) iend_edge_hash, integer(kind = kint), dimension(ntot_list,2), intent(in) iedge_hash, integer(kind = kint_gl), dimension(ntot_list), intent(inout) iedge_flag) private
Definition at line 218 of file set_edge_hash_by_sf.f90.
References m_geometry_constants::node_on_edge_sf_l.
Referenced by const_edge_hash_4_sf(), and const_part_edge_hash_4_sf().
set_edge_hash_4_sf()
subroutine, private set_edge_hash_by_sf::set_edge_hash_4_sf (integer(kind = kint), intent(in) numsurf, integer(kind = kint), intent(in) nnod_4_surf, integer(kind = kint), dimension(numsurf,nnod_4_surf), intent(in) ie_surf, integer(kind = kint_gl), intent(in) ntot_id, integer(kind = kint_gl), intent(in) ntot_list, integer(kind = kint_gl), dimension(ntot_id), intent(inout) num_edge_hash, integer(kind = kint_gl), dimension(0:ntot_id), intent(inout) istack_edge_hash, integer(kind = kint_gl), intent(inout) iend_edge_hash, integer(kind = kint), dimension(ntot_list,2), intent(inout) iedge_hash) private
Definition at line 91 of file set_edge_hash_by_sf.f90.
References m_geometry_constants::nedge_4_surf, and m_geometry_constants::node_on_edge_sf_l.
Referenced by const_edge_hash_4_sf().
set_part_edge_hash_4_sf()
subroutine, private set_edge_hash_by_sf::set_part_edge_hash_4_sf (integer(kind = kint), intent(in) numsurf, integer(kind = kint), intent(in) nnod_4_surf, integer(kind = kint), dimension(numsurf,nnod_4_surf), intent(in) ie_surf, integer(kind = kint), intent(in) numsurf_part, integer(kind = kint), dimension(numsurf_part), intent(in) isf_part, integer(kind = kint_gl), intent(in) ntot_id, integer(kind = kint_gl), intent(in) ntot_list, integer(kind = kint_gl), dimension(ntot_id), intent(inout) num_edge_hash, integer(kind = kint_gl), dimension(0:ntot_id), intent(inout) istack_edge_hash, integer(kind = kint_gl), intent(inout) iend_edge_hash, integer(kind = kint), dimension(ntot_list,2), intent(inout) iedge_hash) private
Definition at line 153 of file set_edge_hash_by_sf.f90.
References m_geometry_constants::nedge_4_surf, and m_geometry_constants::node_on_edge_sf_l.
Referenced by const_part_edge_hash_4_sf().