CALYPSO: set_from_recv_buf_rev_tri Module Reference
set_from_recv_buf_rev_tri Module Reference
Arbitrary components data communication.
Functions/Subroutines
subroutine set_from_recv_buf_rev_3x1 (nnod_new, nnod_recv, irev_import, WR, X1_new, X2_new, X3_new)
subroutine set_from_recv_buf_rev_3x2 (nnod_new, nnod_recv, irev_import, WR, X1_new, X2_new, X3_new)
subroutine set_from_recv_buf_rev_3x3 (nnod_new, nnod_recv, irev_import, WR, X1_new, X2_new, X3_new)
subroutine set_from_recv_buf_rev_3x6 (nnod_new, nnod_recv, irev_import, WR, X1_new, X2_new, X3_new)
subroutine set_from_recv_buf_rev_3xn (NB, nnod_new, nnod_recv, irev_import, WR, X1_new, X2_new, X3_new)
Detailed Description
Arbitrary components data communication.
      subroutine set_from_recv_buf_rev_3x1(nnod_new,                  &
     &          nnod_recv, irev_import, WR, X1_new, X2_new, X3_new)
      subroutine set_from_recv_buf_rev_3x2(nnod_new,                  &
     &          nnod_recv, irev_import, WR, X1_new, X2_new, X3_new)
      subroutine set_from_recv_buf_rev_3x3(nnod_new,                  &
     &          nnod_recv, irev_import, WR, X1_new, X2_new, X3_new)
      subroutine set_from_recv_buf_rev_3x6(nnod_new,                  &
     &          nnod_recv, irev_import, WR, X1_new, X2_new, X3_new)
      subroutine set_from_recv_buf_rev_3xN(NB, nnod_new,              &
     &          nnod_recv, irev_import, WR, X1_new, X2_new, X3_new)
Parameters
NB Number of components for communication
nnod_new Number of components for destination
Parameters
irecv_self Integer flag to copy within own process
nnod_recv Number of data points to receive
irev_import(nnod_new) import buffer ID for each data point
X_new(NB*nnod_new) Received data
Function/Subroutine Documentation
set_from_recv_buf_rev_3x1()
subroutine set_from_recv_buf_rev_tri::set_from_recv_buf_rev_3x1 (integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) nnod_recv, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, real (kind=kreal), dimension(3*(nnod_recv+1)), intent(inout) WR, real (kind=kreal), dimension(nnod_new), intent(inout) X1_new, real (kind=kreal), dimension(nnod_new), intent(inout) X2_new, real (kind=kreal), dimension(nnod_new), intent(inout) X3_new)
Definition at line 44 of file set_from_recv_buf_rev_tri.f90.
Referenced by select_copy_from_recv::sel_cppy_from_recv_buf_3x1().
set_from_recv_buf_rev_3x2()
subroutine set_from_recv_buf_rev_tri::set_from_recv_buf_rev_3x2 (integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) nnod_recv, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, real (kind=kreal), dimension(6*(nnod_recv+1)), intent(inout) WR, real (kind=kreal), dimension(2*nnod_new), intent(inout) X1_new, real (kind=kreal), dimension(2*nnod_new), intent(inout) X2_new, real (kind=kreal), dimension(2*nnod_new), intent(inout) X3_new)
Definition at line 76 of file set_from_recv_buf_rev_tri.f90.
Referenced by select_copy_from_recv::sel_cppy_from_recv_buf_3x2().
set_from_recv_buf_rev_3x3()
subroutine set_from_recv_buf_rev_tri::set_from_recv_buf_rev_3x3 (integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) nnod_recv, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, real (kind=kreal), dimension(9*(nnod_recv+1)), intent(inout) WR, real (kind=kreal), dimension(3*nnod_new), intent(inout) X1_new, real (kind=kreal), dimension(3*nnod_new), intent(inout) X2_new, real (kind=kreal), dimension(3*nnod_new), intent(inout) X3_new)
Definition at line 111 of file set_from_recv_buf_rev_tri.f90.
Referenced by select_copy_from_recv::sel_cppy_from_recv_buf_3x3().
set_from_recv_buf_rev_3x6()
subroutine set_from_recv_buf_rev_tri::set_from_recv_buf_rev_3x6 (integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) nnod_recv, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, real (kind=kreal), dimension(18*(nnod_recv+1)), intent(inout) WR, real (kind=kreal), dimension(6*nnod_new), intent(inout) X1_new, real (kind=kreal), dimension(6*nnod_new), intent(inout) X2_new, real (kind=kreal), dimension(6*nnod_new), intent(inout) X3_new)
Definition at line 149 of file set_from_recv_buf_rev_tri.f90.
Referenced by select_copy_from_recv::sel_cppy_from_recv_buf_3x6().
set_from_recv_buf_rev_3xn()
subroutine set_from_recv_buf_rev_tri::set_from_recv_buf_rev_3xn (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) nnod_recv, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, real (kind=kreal), dimension(3*nb*(nnod_recv+1)), intent(inout) WR, real (kind=kreal), dimension(nb*nnod_new), intent(inout) X1_new, real (kind=kreal), dimension(nb*nnod_new), intent(inout) X2_new, real (kind=kreal), dimension(nb*nnod_new), intent(inout) X3_new)
Definition at line 196 of file set_from_recv_buf_rev_tri.f90.
Referenced by select_copy_from_recv::sel_cppy_from_recv_buf_3xn().