CALYPSO: t_ctl_data_4_time_steps Module Reference
t_ctl_data_4_time_steps Module Reference
Data Types
type time_data_control
Structure of time stepping controls.
Functions/Subroutines
subroutine read_control_time_step_data (id_control, hd_block, tctl, c_buf)
subroutine write_control_time_step_data (id_control, hd_block, tctl, level)
integer(kind=kint) function num_label_time_step_ctl ()
integer(kind=kint) function num_label_time_step_ctl_w_dep ()
subroutine set_label_time_step_ctl (names)
Variables
character(len=kchara), parameter, private hd_elapsed_time = 'elapsed_time_ctl'
character(len=kchara), parameter, private hd_dt = 'dt_ctl'
character(len=kchara), parameter, private hd_time_init = 'time_init_ctl'
character(len=kchara), parameter, private hd_flexible_step = 'flexible_step_ctl'
character(len=kchara), parameter, private hd_min_delta_t = 'min_delta_t_ctl'
character(len=kchara), parameter, private hd_max_delta_t = 'max_delta_t_ctl'
character(len=kchara), parameter, private hd_max_eps_to_shrink = 'max_eps_to_shrink_ctl'
character(len=kchara), parameter, private hd_min_eps_to_expand = 'min_eps_to_expand_ctl'
character(len=kchara), parameter, private hd_ratio_to_cfl = 'ratio_to_CFL_ctl'
character(len=kchara), parameter, private hd_start_rst_step = 'start_rst_step_ctl'
character(len=kchara), parameter, private hd_end_rst_step = 'end_rst_step_ctl'
character(len=kchara), parameter, private hd_delta_t_check = 'delta_t_check_ctl'
character(len=kchara), parameter, private hd_delta_t_rst = 'delta_t_rst_ctl'
character(len=kchara), parameter, private hd_delta_t_section = 'delta_t_sectioning_ctl'
character(len=kchara), parameter, private hd_delta_t_isosurf = 'delta_t_isosurface_ctl'
character(len=kchara), parameter, private hd_delta_t_pvr = 'delta_t_pvr_ctl'
character(len=kchara), parameter, private hd_delta_t_lic = 'delta_t_LIC_ctl'
character(len=kchara), parameter, private hd_delta_t_fline = 'delta_t_fline_ctl'
character(len=kchara), parameter, private hd_delta_t_ucd = 'delta_t_field_ctl'
character(len=kchara), parameter, private hd_delta_t_monitor = 'delta_t_monitor_ctl'
character(len=kchara), parameter, private hd_delta_t_sgs_coefs = 'delta_t_sgs_coefs_ctl'
character(len=kchara), parameter, private hd_delta_t_boundary = 'delta_t_boundary_ctl'
character(len=kchara), parameter, private hd_i_step_init = 'i_step_init_ctl'
character(len=kchara), parameter, private hd_i_finish_number = 'i_step_finish_ctl'
character(len=kchara), parameter, private hd_i_step_check = 'i_step_check_ctl'
character(len=kchara), parameter, private hd_i_step_rst = 'i_step_rst_ctl'
character(len=kchara), parameter, private hd_i_step_section = 'i_step_sectioning_ctl'
character(len=kchara), parameter, private hd_i_step_isosurf = 'i_step_isosurface_ctl'
character(len=kchara), parameter, private hd_i_step_pvr = 'i_step_pvr_ctl'
character(len=kchara), parameter, private hd_i_step_fline = 'i_step_fline_ctl'
character(len=kchara), parameter, private hd_i_step_lic = 'i_step_LIC_ctl'
character(len=kchara), parameter, private hd_i_step_ucd = 'i_step_field_ctl'
character(len=kchara), parameter, private hd_i_step_monitor = 'i_step_monitor_ctl'
character(len=kchara), parameter, private hd_i_step_sgs_coefs = 'i_step_sgs_coefs_ctl'
character(len=kchara), parameter, private hd_i_step_boundary = 'i_step_boundary_ctl'
character(len=kchara), parameter, private hd_i_diff_steps = 'i_diff_steps_ctl'
character(len=kchara), parameter, private hd_i_step_number = 'i_step_number_ctl'
character(len=kchara), parameter, private hd_i_step_psf = 'i_step_psf_ctl'
character(len=kchara), parameter, private hd_i_step_iso = 'i_step_iso_ctl'
integer(kind=kint), parameter, private n_label_time_step_ctl = 36
integer(kind=kint), parameter, private n_label_time_step_ctl_w_dep = 39
Detailed Description
Parameters
flexible_step_ctl Flexible time step switch ('On' or 'Off')
dt_ctl time step
min_delta_t_ctl minimum time step length
max_delta_t_ctl maximum time step length
max_eps_to_shrink_ctl maximum threshold to shrink time step
min_eps_to_expand_ctl minimum threshold to expand time step
ratio_to_CFL_ctl Ratio to CFL condition
start_rst_step_ctl Increment time for volume integrated data output
end_rst_step_ctl Increment time for restart data output
delta_t_check_ctl Increment time for volume integrated data output
delta_t_rst_ctl Increment time for restart data output
delta_t_psf_ctl Increment time for surface rendering data output
delta_t_iso_ctl Increment time for isosurface rendering data output
delta_t_pvr_ctl Increment time for volume rendering data output
delta_t_fline_ctl Increment time for field line data output
delta_t_lic_ctl Increment time for LIC rendering output
delta_t_field_ctl Increment time for whole field data output
delta_t_monitor_ctl Increment time for monotoring on nodes data output
delta_t_sgs_coefs_ctl Increment time for SGS model parameters data output
delta_t_boundary_ctl Increment time for boundary data output
i_step_init_ctl start time step
i_step_number_ctl or i_step_finish_ctl end time step
i_step_check_ctl Increment step for volume integrated data output
i_step_rst_ctl Increment step for restart data output
i_step_sectioning_ctl Increment step for surface rendering data output
i_step_pvr_ctl Increment step for volume rendering data output
i_step_fline_ctl Increment step for field line data output
i_step_lic_ctl Increment step for LIC rendering data output
i_step_field_ctl or i_step_snapshot_ctl Increment step for whole field data output
i_step_monitor_ctl Increment step for monotoring on nodes data output
i_step_sgs_coefs_ctl Increment step for SGS model parameters data output
i_step_boundary_ctl Increment step for boundary data output
time_init_ctl Initial time
Function/Subroutine Documentation
num_label_time_step_ctl()
integer(kind = kint) function t_ctl_data_4_time_steps::num_label_time_step_ctl
Definition at line 649 of file t_ctl_data_4_time_steps.f90.
References n_label_time_step_ctl.
num_label_time_step_ctl_w_dep()
integer(kind = kint) function t_ctl_data_4_time_steps::num_label_time_step_ctl_w_dep
Definition at line 656 of file t_ctl_data_4_time_steps.f90.
References n_label_time_step_ctl_w_dep.
read_control_time_step_data()
subroutine t_ctl_data_4_time_steps::read_control_time_step_data (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(time_data_control), intent(inout) tctl, type(buffer_for_control), intent(inout) c_buf)
Definition at line 368 of file t_ctl_data_4_time_steps.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_delta_t_boundary, hd_delta_t_check, hd_delta_t_fline, hd_delta_t_isosurf, hd_delta_t_lic, hd_delta_t_monitor, hd_delta_t_pvr, hd_delta_t_rst, hd_delta_t_section, hd_delta_t_sgs_coefs, hd_delta_t_ucd, hd_dt, hd_elapsed_time, hd_end_rst_step, hd_flexible_step, hd_i_diff_steps, hd_i_finish_number, hd_i_step_boundary, hd_i_step_check, hd_i_step_fline, hd_i_step_init, hd_i_step_iso, hd_i_step_isosurf, hd_i_step_lic, hd_i_step_monitor, hd_i_step_number, hd_i_step_psf, hd_i_step_pvr, hd_i_step_rst, hd_i_step_section, hd_i_step_sgs_coefs, hd_i_step_ucd, hd_max_delta_t, hd_max_eps_to_shrink, hd_min_delta_t, hd_min_eps_to_expand, hd_ratio_to_cfl, hd_start_rst_step, hd_time_init, t_read_control_elements::load_one_line_from_control(), t_control_array_character::read_chara_ctl_type(), t_control_array_integer::read_integer_ctl_type(), and t_control_array_real::read_real_ctl_type().
Referenced by t_control_data_4_merge::read_merge_step_data(), t_control_data_section_only::read_section_control_data(), and t_ctl_data_sph_mhd_control::read_sph_mhd_control().
set_label_time_step_ctl()
subroutine t_ctl_data_4_time_steps::set_label_time_step_ctl (character(len = kchara), dimension(n_label_time_step_ctl_w_dep), intent(inout) names)
Definition at line 663 of file t_ctl_data_4_time_steps.f90.
References hd_delta_t_boundary, hd_delta_t_check, hd_delta_t_fline, hd_delta_t_isosurf, hd_delta_t_lic, hd_delta_t_monitor, hd_delta_t_pvr, hd_delta_t_rst, hd_delta_t_section, hd_delta_t_sgs_coefs, hd_delta_t_ucd, hd_dt, hd_elapsed_time, hd_end_rst_step, hd_flexible_step, hd_i_diff_steps, hd_i_finish_number, hd_i_step_boundary, hd_i_step_check, hd_i_step_fline, hd_i_step_init, hd_i_step_iso, hd_i_step_isosurf, hd_i_step_lic, hd_i_step_monitor, hd_i_step_number, hd_i_step_psf, hd_i_step_pvr, hd_i_step_rst, hd_i_step_section, hd_i_step_sgs_coefs, hd_i_step_ucd, hd_max_delta_t, hd_max_eps_to_shrink, hd_min_delta_t, hd_min_eps_to_expand, hd_ratio_to_cfl, hd_start_rst_step, hd_time_init, and t_read_control_elements::set_control_labels().
write_control_time_step_data()
subroutine t_ctl_data_4_time_steps::write_control_time_step_data (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(time_data_control), intent(in) tctl, integer(kind = kint), intent(inout) level)
Definition at line 487 of file t_ctl_data_4_time_steps.f90.
References hd_delta_t_boundary, hd_delta_t_check, hd_delta_t_fline, hd_delta_t_isosurf, hd_delta_t_lic, hd_delta_t_monitor, hd_delta_t_pvr, hd_delta_t_rst, hd_delta_t_section, hd_delta_t_sgs_coefs, hd_delta_t_ucd, hd_dt, hd_elapsed_time, hd_end_rst_step, hd_flexible_step, hd_i_diff_steps, hd_i_finish_number, hd_i_step_boundary, hd_i_step_check, hd_i_step_fline, hd_i_step_init, hd_i_step_iso, hd_i_step_isosurf, hd_i_step_lic, hd_i_step_monitor, hd_i_step_number, hd_i_step_psf, hd_i_step_pvr, hd_i_step_rst, hd_i_step_section, hd_i_step_sgs_coefs, hd_i_step_ucd, hd_max_delta_t, hd_max_eps_to_shrink, hd_min_delta_t, hd_min_eps_to_expand, hd_ratio_to_cfl, hd_start_rst_step, hd_time_init, write_control_elements::write_begin_flag_for_ctl(), t_control_array_character::write_chara_ctl_type(), write_control_elements::write_end_flag_for_ctl(), t_control_array_integer::write_integer_ctl_type(), and t_control_array_real::write_real_ctl_type().
Variable Documentation
hd_delta_t_boundary
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_delta_t_boundary = 'delta_t_boundary_ctl' private
Definition at line 315 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_delta_t_check
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_delta_t_check = 'delta_t_check_ctl' private
Definition at line 294 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_delta_t_fline
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_delta_t_fline = 'delta_t_fline_ctl' private
Definition at line 306 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_delta_t_isosurf
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_delta_t_isosurf = 'delta_t_isosurface_ctl' private
Definition at line 300 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_delta_t_lic
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_delta_t_lic = 'delta_t_LIC_ctl' private
Definition at line 304 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_delta_t_monitor
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_delta_t_monitor = 'delta_t_monitor_ctl' private
Definition at line 311 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_delta_t_pvr
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_delta_t_pvr = 'delta_t_pvr_ctl' private
Definition at line 302 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_delta_t_rst
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_delta_t_rst = 'delta_t_rst_ctl' private
Definition at line 296 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_delta_t_section
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_delta_t_section = 'delta_t_sectioning_ctl' private
Definition at line 298 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_delta_t_sgs_coefs
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_delta_t_sgs_coefs = 'delta_t_sgs_coefs_ctl' private
Definition at line 313 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_delta_t_ucd
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_delta_t_ucd = 'delta_t_field_ctl' private
Definition at line 309 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_dt
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_dt = 'dt_ctl' private
Definition at line 269 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_elapsed_time
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_elapsed_time = 'elapsed_time_ctl' private
Definition at line 267 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_end_rst_step
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_end_rst_step = 'end_rst_step_ctl' private
Definition at line 291 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_flexible_step
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_flexible_step = 'flexible_step_ctl' private
Definition at line 274 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_i_diff_steps
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_i_diff_steps = 'i_diff_steps_ctl' private
Definition at line 346 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_i_finish_number
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_i_finish_number = 'i_step_finish_ctl' private
Definition at line 320 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_i_step_boundary
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_i_step_boundary = 'i_step_boundary_ctl' private
Definition at line 344 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_i_step_check
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_i_step_check = 'i_step_check_ctl' private
Definition at line 322 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_i_step_fline
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_i_step_fline = 'i_step_fline_ctl' private
Definition at line 333 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_i_step_init
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_i_step_init = 'i_step_init_ctl' private
Definition at line 318 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_i_step_iso
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_i_step_iso = 'i_step_iso_ctl' private
Definition at line 354 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_i_step_isosurf
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_i_step_isosurf = 'i_step_isosurface_ctl' private
Definition at line 329 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_i_step_lic
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_i_step_lic = 'i_step_LIC_ctl' private
Definition at line 335 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_i_step_monitor
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_i_step_monitor = 'i_step_monitor_ctl' private
Definition at line 340 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_i_step_number
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_i_step_number = 'i_step_number_ctl' private
Definition at line 350 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_i_step_psf
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_i_step_psf = 'i_step_psf_ctl' private
Definition at line 352 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_i_step_pvr
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_i_step_pvr = 'i_step_pvr_ctl' private
Definition at line 331 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_i_step_rst
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_i_step_rst = 'i_step_rst_ctl' private
Definition at line 324 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_i_step_section
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_i_step_section = 'i_step_sectioning_ctl' private
Definition at line 327 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_i_step_sgs_coefs
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_i_step_sgs_coefs = 'i_step_sgs_coefs_ctl' private
Definition at line 342 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_i_step_ucd
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_i_step_ucd = 'i_step_field_ctl' private
Definition at line 338 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_max_delta_t
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_max_delta_t = 'max_delta_t_ctl' private
Definition at line 279 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_max_eps_to_shrink
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_max_eps_to_shrink = 'max_eps_to_shrink_ctl' private
Definition at line 281 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_min_delta_t
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_min_delta_t = 'min_delta_t_ctl' private
Definition at line 277 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_min_eps_to_expand
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_min_eps_to_expand = 'min_eps_to_expand_ctl' private
Definition at line 283 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_ratio_to_cfl
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_ratio_to_cfl = 'ratio_to_CFL_ctl' private
Definition at line 286 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_start_rst_step
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_start_rst_step = 'start_rst_step_ctl' private
Definition at line 289 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
hd_time_init
character(len=kchara), parameter, private t_ctl_data_4_time_steps::hd_time_init = 'time_init_ctl' private
Definition at line 271 of file t_ctl_data_4_time_steps.f90.
Referenced by read_control_time_step_data(), set_label_time_step_ctl(), and write_control_time_step_data().
n_label_time_step_ctl
integer(kind = kint), parameter, private t_ctl_data_4_time_steps::n_label_time_step_ctl = 36 private
Definition at line 357 of file t_ctl_data_4_time_steps.f90.
Referenced by num_label_time_step_ctl().
n_label_time_step_ctl_w_dep
integer(kind = kint), parameter, private t_ctl_data_4_time_steps::n_label_time_step_ctl_w_dep = 39 private
Definition at line 359 of file t_ctl_data_4_time_steps.f90.
Referenced by num_label_time_step_ctl_w_dep().