CALYPSO: t_sum_hash Module Reference
t_sum_hash Module Reference
Hash table using sum of local node ID.
Data Types
type sum_hash_tbl
Structure for hash table.
Functions/Subroutines
subroutine alloc_sum_hash (numnod, nele, num_4_ele, nnod_4_edge, h_tbl)
subroutine clear_sum_hash (h_tbl)
subroutine dealloc_sum_hash (h_tbl)
Detailed Description
Hash table using sum of local node ID.
      subroutine alloc_sum_hash                                       &
     &         (numnod, nele, num_4_ele, nnod_4_edge, h_tbl)
      subroutine clear_sum_hash(h_tbl)
      subroutine dealloc_sum_hash(h_tbl)
Function/Subroutine Documentation
alloc_sum_hash()
subroutine t_sum_hash::alloc_sum_hash (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) nele, integer(kind = kint), intent(in) num_4_ele, integer(kind = kint), intent(in) nnod_4_edge, type(sum_hash_tbl), intent(inout) h_tbl)
Definition at line 47 of file t_sum_hash.f90.
References clear_sum_hash().
Referenced by const_merged_surf_4_group::const_merged_surface_4_ele_grp(), const_edge_4_viewer::construct_edge_4_viewer(), const_edge_data::construct_edge_data(), and const_surface_data::construct_surface_data().
clear_sum_hash()
subroutine t_sum_hash::clear_sum_hash (type(sum_hash_tbl), intent(inout) h_tbl)
Definition at line 71 of file t_sum_hash.f90.
Referenced by alloc_sum_hash(), const_edge_4_viewer::const_all_edge_4_viewer(), const_edge_4_viewer::construct_edge_4_domain(), const_grp_edge_4_viewer::construct_edge_4_ele_grp(), and const_grp_edge_4_viewer::construct_edge_4_surf_grp().
dealloc_sum_hash()
subroutine t_sum_hash::dealloc_sum_hash (type(sum_hash_tbl), intent(inout) h_tbl)
Definition at line 85 of file t_sum_hash.f90.
Referenced by const_merged_surf_4_group::const_merged_surface_4_ele_grp(), const_edge_4_viewer::construct_edge_4_viewer(), const_edge_data::construct_edge_data(), and const_surface_data::construct_surface_data().