CALYPSO: add_field_to_sph_trans_list Module Reference
add_field_to_sph_trans_list Module Reference
Field addresses for spherical harmonics transform in MHD dynamo simulation.
Functions/Subroutines
subroutine add_field_4_sph_trns_by_pol (d_rj, i_pol, irtp, i_trns, each_trns)
subroutine add_field_name_4_sph_trns_snap (d_rj, i_pol, irtp, i_trns, each_trns)
subroutine add_scalar_4_sph_trns_by_pol (d_rj, i_pol, irtp, i_trns, each_trns)
subroutine add_scalar_4_sph_trns_snap (d_rj, i_pol, irtp, i_trns, each_trns)
subroutine add_field_name_4_sph_trns (iflag_add, field_name, num_component, i_pol, irtp, i_trns, each_trns)
Detailed Description
Field addresses for spherical harmonics transform in MHD dynamo simulation.
      subroutine add_field_4_sph_trns_by_pol                          &
     &         (d_rj, i_pol, irtp, i_trns, each_trns)
        type(phys_data), intent(in) :: d_rj
        type(spherical_transform_data), intent(inout) :: each_trns
      subroutine add_field_name_4_sph_trns_snap                       &
     &         (d_rj, i_pol, irtp, i_trns, each_trns)
        type(phys_data), intent(in) :: d_rj
        type(spherical_transform_data), intent(inout) :: each_trns
      subroutine add_scalar_4_sph_trns_by_pol                         &
     &         (d_rj, i_pol, irtp, i_trns, each_trns)
        type(phys_data), intent(in) :: d_rj
        type(spherical_transform_data), intent(inout) :: each_trns
      subroutine add_scalar_4_sph_trns_snap                           &
     &         (d_rj, i_pol, irtp, i_trns, each_trns)
        type(phys_data), intent(in) :: d_rj
        type(spherical_transform_data), intent(inout) :: each_trns
      subroutine add_field_name_4_sph_trns                            &
     &         (iflag_add, field_name, num_component,                 &
     &          i_pol, irtp, i_trns, each_trns)
        type(spherical_transform_data), intent(inout) :: each_trns
Function/Subroutine Documentation
add_field_4_sph_trns_by_pol()
subroutine add_field_to_sph_trans_list::add_field_4_sph_trns_by_pol (type(phys_data), intent(in) d_rj, integer(kind = kint), intent(in) i_pol, integer(kind = kint), intent(in) irtp, integer(kind = kint), intent(inout) i_trns, type(spherical_transform_data), intent(inout) each_trns)
Definition at line 49 of file add_field_to_sph_trans_list.f90.
References add_field_name_4_sph_trns(), and t_phys_data::field_id_by_address().
Referenced by add_base_force_4_sph_trns::add_base_force_4_mhd_sph_trns(), add_base_force_4_sph_trns::add_base_force_sph_trns_snap(), add_base_field_4_sph_trns::add_base_scalar_4_mhd_sph_trns(), add_base_field_4_sph_trns::add_base_scalar_sph_trns_snap(), add_base_field_4_sph_trns::add_base_vector_4_mhd_sph_trns(), add_diff_vect_to_sph_trans::add_diff_vect_sph_trns_by_pol(), add_base_force_4_sph_trns::add_div_coriolis_mhd_sph_trns(), add_diff_vect_to_sph_trans::add_grad_4_sph_trns_by_pol(), and add_base_force_4_sph_trns::add_rot_coriolis_mhd_sph_trns().
add_field_name_4_sph_trns()
subroutine add_field_to_sph_trans_list::add_field_name_4_sph_trns (integer(kind = kint), intent(in) iflag_add, character(len = kchara), intent(in) field_name, integer(kind = kint), intent(in) num_component, integer(kind = kint), intent(in) i_pol, integer(kind = kint), intent(in) irtp, integer(kind = kint), intent(inout) i_trns, type(spherical_transform_data), intent(inout) each_trns)
Definition at line 135 of file add_field_to_sph_trans_list.f90.
References t_addresses_sph_transform::alloc_sph_trns_field_name(), t_addresses_sph_transform::copy_field_name_4_sph_trns(), t_addresses_sph_transform::dealloc_sph_trns_field_name(), and m_machine_parameter::iflag_debug.
Referenced by add_field_4_sph_trns_by_pol(), add_field_name_4_sph_trns_snap(), add_scalar_4_sph_trns_by_pol(), and add_scalar_4_sph_trns_snap().
add_field_name_4_sph_trns_snap()
subroutine add_field_to_sph_trans_list::add_field_name_4_sph_trns_snap (type(phys_data), intent(in) d_rj, integer(kind = kint), intent(in) i_pol, integer(kind = kint), intent(in) irtp, integer(kind = kint), intent(inout) i_trns, type(spherical_transform_data), intent(inout) each_trns)
Definition at line 70 of file add_field_to_sph_trans_list.f90.
References add_field_name_4_sph_trns(), and t_phys_data::field_id_by_address().
Referenced by add_base_force_4_sph_trns::add_base_force_bwd_trns_snap(), add_base_force_4_sph_trns::add_base_force_fwd_trns_snap(), add_base_force_4_sph_trns::add_div_force_4_sph_trns_snap(), add_energy_flux_4_sph_trns::add_ene_flux_4_sph_trns_snap(), add_diff_vect_to_sph_trans::add_grad_4_sph_trns_snap(), add_prod_field_4_sph_trns::add_prod_scalar_sph_trns_snap(), add_prod_field_4_sph_trns::add_prod_vector_sph_trns_snap(), add_base_force_4_sph_trns::add_rot_force_4_sph_trns_snap(), add_diffusion_4_sph_trns::add_scalar_diffusion_sph_trns(), add_base_force_4_sph_trns::add_scalar_flux_bwd_trns_snap(), add_prod_field_4_sph_trns::add_subtracted_sph_trns_snap(), and add_diffusion_4_sph_trns::add_vector_diffusion_sph_trns().
add_scalar_4_sph_trns_by_pol()
subroutine add_field_to_sph_trans_list::add_scalar_4_sph_trns_by_pol (type(phys_data), intent(in) d_rj, integer(kind = kint), intent(in) i_pol, integer(kind = kint), intent(in) irtp, integer(kind = kint), intent(inout) i_trns, type(spherical_transform_data), intent(inout) each_trns)
Definition at line 93 of file add_field_to_sph_trans_list.f90.
References add_field_name_4_sph_trns(), and t_phys_data::field_id_by_address().
Referenced by add_diff_vect_to_sph_trans::add_diff_vect_scalar_trns_bpol().
add_scalar_4_sph_trns_snap()
subroutine add_field_to_sph_trans_list::add_scalar_4_sph_trns_snap (type(phys_data), intent(in) d_rj, integer(kind = kint), intent(in) i_pol, integer(kind = kint), intent(in) irtp, integer(kind = kint), intent(inout) i_trns, type(spherical_transform_data), intent(inout) each_trns)
Definition at line 113 of file add_field_to_sph_trans_list.f90.
References add_field_name_4_sph_trns(), and t_phys_data::field_id_by_address().