CALYPSO: load_element_mesh_data Module Reference
load_element_mesh_data Module Reference
Copy FEM mesh data from IO structure.
Functions/Subroutines
subroutine set_surface_mesh_from_io (ele, surf, surf_mesh_IO)
subroutine set_edge_mesh_from_io (ele, surf, edge, edge_mesh_IO)
subroutine set_surface_mesh_to_io (ele, surf, surf_mesh_IO)
subroutine set_edge_mesh_to_io (ele, surf, edge, edge_mesh_IO)
Detailed Description
Copy FEM mesh data from IO structure.
      subroutine set_surface_mesh_from_IO(ele, surf, surf_mesh_IO)
      subroutine set_edge_mesh_from_IO(ele, surf, edge, edge_mesh_IO)
        type(surf_edge_IO_file), intent(inout) :: ele_mesh_IO
        type(element_data), intent(inout) :: ele
        type(surface_data), intent(inout) :: surf
        type(edge_data), intent(inout) :: edge
        type(communication_table), intent(inout) :: ele_comm
        type(surf_edge_IO_file), intent(inout) :: ele_mesh_IO
        type(surf_edge_IO_file), intent(inout) :: surf_mesh_IO
        type(surf_edge_IO_file), intent(inout) :: edge_mesh_IO
      subroutine set_surface_mesh_to_IO(ele, surf, surf_mesh_IO)
      subroutine set_edge_mesh_to_IO                                  &
     &         (ele, surf, edge, edge_mesh_IO)
Function/Subroutine Documentation
set_edge_mesh_from_io()
subroutine load_element_mesh_data::set_edge_mesh_from_io (type(element_data), intent(in) ele, type(surface_data), intent(in) surf, type(edge_data), intent(inout) edge, type(surf_edge_io_file), intent(inout) edge_mesh_IO)
Definition at line 74 of file load_element_mesh_data.f90.
References set_edge_data_4_io::copy_edge_connect_from_io(), and t_read_mesh_data::dealloc_edge_mesh_io().
set_edge_mesh_to_io()
subroutine load_element_mesh_data::set_edge_mesh_to_io (type(element_data), intent(in) ele, type(surface_data), intent(in) surf, type(edge_data), intent(in) edge, type(surf_edge_io_file), intent(inout) edge_mesh_IO)
Definition at line 121 of file load_element_mesh_data.f90.
References set_edge_data_4_io::copy_edge_connect_to_io().
set_surface_mesh_from_io()
subroutine load_element_mesh_data::set_surface_mesh_from_io (type(element_data), intent(in) ele, type(surface_data), intent(inout) surf, type(surf_edge_io_file), intent(inout) surf_mesh_IO)
Definition at line 44 of file load_element_mesh_data.f90.
References set_surface_data_4_io::copy_surf_connect_from_io(), t_read_mesh_data::dealloc_surface_mesh_io(), m_machine_parameter::iflag_debug, and set_surface_data::set_surf_rotation_flag().
set_surface_mesh_to_io()
subroutine load_element_mesh_data::set_surface_mesh_to_io (type(element_data), intent(in) ele, type(surface_data), intent(in) surf, type(surf_edge_io_file), intent(inout) surf_mesh_IO)
Definition at line 100 of file load_element_mesh_data.f90.
References set_surface_data_4_io::copy_surf_connect_to_io().