CALYPSO: write_control_elements Module Reference
write_control_elements Module Reference
Subroutines to write control data.
Functions/Subroutines
integer(kind=kint) function write_begin_flag_for_ctl (id_file, level, label)
integer(kind=kint) function write_end_flag_for_ctl (id_file, level, label)
subroutine write_array_flag_for_ctl (id_file, level, label, num)
subroutine write_end_array_flag_for_ctl (id_file, level, label)
subroutine write_real_ctl_item (id_file, level, maxlen, label, real_data)
subroutine write_integer_ctl_item (id_file, level, maxlen, label, int_data)
subroutine write_character_ctl_item (id_file, level, maxlen, label, chara_data)
subroutine write_real2_ctl_item (id_file, level, label, real1, real2)
subroutine write_real3_ctl_item (id_file, level, label, real1, real2, real3)
subroutine write_int_real_ctl_item (id_file, level, label, int_data, real_data)
subroutine write_integer2_ctl_item (id_file, level, label, int1, int2)
subroutine write_integer3_ctl_item (id_file, level, label, int1, int2, int3)
subroutine write_chara_real_ctl_item (id_file, level, label, chara_data, real_data)
subroutine write_chara_real2_ctl_item (id_file, level, label, chara_data, real1, real2)
subroutine write_chara2_real_ctl_item (id_file, level, label, chara1, chara2, real_data)
subroutine write_chara_int_ctl_item (id_file, level, label, chara_data, int_data)
subroutine write_i2_r_ctl_item (id_file, level, label, int1, int2, real_data)
subroutine write_i2_r2_ctl_item (id_file, level, label, int1, int2, real1, real2)
subroutine write_i_c_r_ctl_item (id_file, level, label, int_data, chara_data, real_data)
subroutine write_character2_ctl_item (id_file, level, label, maxlen, chara1, chara2)
subroutine write_character3_ctl_item (id_file, level, label, maxlen, chara1, chara2, chara3)
subroutine write_chara_int3_ctl_item (id_file, level, label, chara_data, ivec1, ivec2, ivec3)
subroutine write_file_name_for_ctl_line (id_file, level, label, fname)
subroutine write_file_names_from_ctl_line (id_file, level, label, num, fname)
Variables
character(len=kchara), parameter hd_begin = 'begin'
Label to start a control block.
character(len=kchara), parameter hd_end = 'end'
Label to end a control block.
character(len=kchara), parameter hd_array = 'array'
Label for an array control block.
character(len=kchara), parameter hd_file = 'file'
Label for an array control block.
Detailed Description
Subroutines to write control data.
      integer(kind = kint) function write_begin_flag_for_ctl          &
     &                            (id_file, level, label)
      integer(kind = kint) function write_end_flag_for_ctl            &
     &                            (id_file, level, label)
      subroutine write_array_flag_for_ctl(id_file, level, label, num)
      subroutine write_end_array_flag_for_ctl(id_file, level, label)
      subroutine write_real_ctl_item                                  &
     &         (id_file, level, maxlen, label, real_data)
      subroutine write_integer_ctl_item                               &
     &          (id_file, level, maxlen, label, int_data)
      subroutine write_character_ctl_item                             &
     &         (id_file, level, maxlen, label, chara_data)
      subroutine write_real2_ctl_item                                 &
     &         (id_file, level, label, real1, real2)
      subroutine write_real3_ctl_item                                 &
     &         (id_file, level, label, real1, real2, real3)
       subroutine write_int_real_ctl_item                             &
     &          (id_file, level, label, int_data, real_data)
      subroutine write_integer2_ctl_item                              &
     &         (id_file, level, label, int1, int2)
      subroutine write_integer3_ctl_item                              &
     &         (id_file, level, label, int1, int2, int3)
       subroutine write_chara_real_ctl_item                           &
     &          (id_file, level, label, chara_data, real_data)
       subroutine write_chara_real2_ctl_item                          &
     &          (id_file, level, label, chara_data, real1, real2)
       subroutine write_chara2_real_ctl_item                          &
     &          (id_file, level, label, chara1, chara2, real_data)
       subroutine write_chara_int_ctl_item                            &
     &          (id_file, level, label, chara_data, int_data)
       subroutine write_i2_r_ctl_item                                 &
     &          (id_file, level, label, int1, int2, real_data)
       subroutine write_i2_r2_ctl_item                                &
     &          (id_file, level, label, int1, int2, real1, real2)
       subroutine write_i_c_r_ctl_item(id_file, level, label,         &
     &           int_data, chara_data, real_data)
      subroutine write_character2_ctl_item                            &
     &         (id_file, level, label, maxlen, chara1, chara2)
      subroutine write_character3_ctl_item                            &
     &         (id_file, level, label, maxlen, chara1, chara2, chara3)
       subroutine write_chara_int3_ctl_item(id_file, level, label,    &
     &           chara_data, ivec1, ivec2, ivec3)
      subroutine write_file_name_for_ctl_line                         &
     &         (id_file, level, label, fname)
      subroutine write_file_names_from_ctl_line                       &
     &         (id_file, level, label, num, fname)
Parameters
ctl_name label for control block
label label for control items
iflag_end integer flag for reading block
iflag_dat integer flag for reading block
num_array size of array block
num number of blocks already read
icou counter for reading array
Parameters
real_data read real data
int_data read integre data
chara_data read character data
Parameters
ivect integer array data
int1 integer array data
int2 integer array data
vect real array data
vec1 real array data
vec2 real array data
vec3 real array data
c_tbl character array data
c1_tbl character array data
c2_tbl character array data
c3_tbl character array data
Function/Subroutine Documentation
write_array_flag_for_ctl()
subroutine write_control_elements::write_array_flag_for_ctl (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, integer (kind=kint), intent(in) num)
Definition at line 146 of file write_control_elements.f90.
References hd_array, skip_comment_f::write_ctl_chara_cont(), and skip_comment_f::write_space_4_parse().
Referenced by t_control_array_character::write_control_array_c1(), t_control_array_character2::write_control_array_c2(), t_control_array_chara2real::write_control_array_c2_r(), t_control_array_character3::write_control_array_c3(), t_control_array_charaint::write_control_array_c_i(), t_control_array_charaint3::write_control_array_c_i3(), t_control_array_charareal::write_control_array_c_r(), t_control_array_charareal2::write_control_array_c_r2(), t_control_array_integer::write_control_array_i1(), t_control_array_integer2::write_control_array_i2(), t_control_array_int2real::write_control_array_i2_r(), t_control_array_int2real2::write_control_array_i2_r2(), t_control_array_integer3::write_control_array_i3(), t_control_array_intcharreal::write_control_array_i_c_r(), t_control_array_intreal::write_control_array_i_r(), t_control_array_real::write_control_array_r1(), t_control_array_real2::write_control_array_r2(), t_control_array_real3::write_control_array_r3(), and write_file_names_from_ctl_line().
write_begin_flag_for_ctl()
integer(kind = kint) function write_control_elements::write_begin_flag_for_ctl (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label)
Definition at line 108 of file write_control_elements.f90.
References hd_begin, skip_comment_f::write_ctl_chara_cont(), and skip_comment_f::write_space_4_parse().
Referenced by t_ctl_data_4_platforms::write_control_platforms(), t_ctl_data_4_divide_sphere::write_control_shell_domain(), t_ctl_data_4_time_steps::write_control_time_step_data(), and t_ctl_data_4_fields::write_phys_data_control().
write_chara2_real_ctl_item()
subroutine write_control_elements::write_chara2_real_ctl_item (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, character(len=kchara), intent(in) chara1, character(len=kchara), intent(in) chara2, real(kind = kreal), intent(in) real_data)
Definition at line 359 of file write_control_elements.f90.
References skip_comment_f::write_ctl_chara_cont(), and skip_comment_f::write_space_4_parse().
Referenced by t_control_array_chara2real::write_char2real_ctl_type(), and t_control_array_chara2real::write_control_array_c2_r().
write_chara_int3_ctl_item()
subroutine write_control_elements::write_chara_int3_ctl_item (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, character(len=kchara), intent(in) chara_data, integer (kind=kint), intent(in) ivec1, integer (kind=kint), intent(in) ivec2, integer (kind=kint), intent(in) ivec3)
Definition at line 499 of file write_control_elements.f90.
References skip_comment_f::write_ctl_chara_cont(), and skip_comment_f::write_space_4_parse().
Referenced by t_control_array_charaint3::write_charaint3_ctl_type(), and t_control_array_charaint3::write_control_array_c_i3().
write_chara_int_ctl_item()
subroutine write_control_elements::write_chara_int_ctl_item (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, character(len=kchara), intent(in) chara_data, integer (kind=kint), intent(in) int_data)
Definition at line 378 of file write_control_elements.f90.
References skip_comment_f::write_ctl_chara_cont(), and skip_comment_f::write_space_4_parse().
Referenced by t_control_array_charaint::write_charaint_ctl_type(), and t_control_array_charaint::write_control_array_c_i().
write_chara_real2_ctl_item()
subroutine write_control_elements::write_chara_real2_ctl_item (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, character(len=kchara), intent(in) chara_data, real(kind = kreal), intent(in) real1, real(kind = kreal), intent(in) real2)
Definition at line 341 of file write_control_elements.f90.
References skip_comment_f::write_ctl_chara_cont(), and skip_comment_f::write_space_4_parse().
Referenced by t_control_array_charareal2::write_charreal2_ctl_type(), and t_control_array_charareal2::write_control_array_c_r2().
write_chara_real_ctl_item()
subroutine write_control_elements::write_chara_real_ctl_item (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, character(len=kchara), intent(in) chara_data, real(kind = kreal), intent(in) real_data)
Definition at line 323 of file write_control_elements.f90.
References skip_comment_f::write_ctl_chara_cont(), and skip_comment_f::write_space_4_parse().
Referenced by t_control_array_charareal::write_charareal_ctl_type(), and t_control_array_charareal::write_control_array_c_r().
write_character2_ctl_item()
subroutine write_control_elements::write_character2_ctl_item (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, integer(kind = kint), dimension(0:1), intent(in) maxlen, character(len=kchara), intent(in) chara1, character(len=kchara), intent(in) chara2)
Definition at line 449 of file write_control_elements.f90.
References skip_comment_f::iflag_divide(), skip_comment_f::write_ctl_chara_cont(), skip_comment_f::write_ctl_chara_lf(), skip_comment_f::write_space_4_parse(), and skip_comment_f::write_spaces().
Referenced by t_control_array_character2::write_character2_ctl_type(), and t_control_array_character2::write_control_array_c2().
write_character3_ctl_item()
subroutine write_control_elements::write_character3_ctl_item (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, integer(kind = kint), dimension(0:2), intent(in) maxlen, character(len=kchara), intent(in) chara1, character(len=kchara), intent(in) chara2, character(len=kchara), intent(in) chara3)
Definition at line 473 of file write_control_elements.f90.
References skip_comment_f::iflag_divide(), skip_comment_f::write_ctl_chara_cont(), skip_comment_f::write_ctl_chara_lf(), skip_comment_f::write_space_4_parse(), and skip_comment_f::write_spaces().
Referenced by t_control_array_character3::write_character3_ctl_type(), and t_control_array_character3::write_control_array_c3().
write_character_ctl_item()
subroutine write_control_elements::write_character_ctl_item (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, integer(kind = kint), intent(in) maxlen, character(len=kchara), intent(in) label, character(len=kchara), intent(in) chara_data)
Definition at line 222 of file write_control_elements.f90.
References skip_comment_f::write_ctl_chara_cont(), skip_comment_f::write_ctl_chara_lf(), skip_comment_f::write_space_4_parse(), and skip_comment_f::write_spaces().
Referenced by t_control_array_character::write_chara_ctl_type(), and t_control_array_character::write_control_array_c1().
write_end_array_flag_for_ctl()
subroutine write_control_elements::write_end_array_flag_for_ctl (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label)
Definition at line 162 of file write_control_elements.f90.
References hd_array, hd_end, skip_comment_f::write_ctl_chara_cont(), skip_comment_f::write_ctl_chara_lf(), and skip_comment_f::write_space_4_parse().
Referenced by t_control_array_character::write_control_array_c1(), t_control_array_character2::write_control_array_c2(), t_control_array_chara2real::write_control_array_c2_r(), t_control_array_character3::write_control_array_c3(), t_control_array_charaint::write_control_array_c_i(), t_control_array_charaint3::write_control_array_c_i3(), t_control_array_charareal::write_control_array_c_r(), t_control_array_charareal2::write_control_array_c_r2(), t_control_array_integer::write_control_array_i1(), t_control_array_integer2::write_control_array_i2(), t_control_array_int2real::write_control_array_i2_r(), t_control_array_int2real2::write_control_array_i2_r2(), t_control_array_integer3::write_control_array_i3(), t_control_array_intcharreal::write_control_array_i_c_r(), t_control_array_intreal::write_control_array_i_r(), t_control_array_real::write_control_array_r1(), t_control_array_real2::write_control_array_r2(), t_control_array_real3::write_control_array_r3(), and write_file_names_from_ctl_line().
write_end_flag_for_ctl()
integer(kind = kint) function write_control_elements::write_end_flag_for_ctl (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label)
Definition at line 125 of file write_control_elements.f90.
References hd_end, skip_comment_f::write_ctl_chara_cont(), skip_comment_f::write_ctl_chara_lf(), and skip_comment_f::write_space_4_parse().
Referenced by t_ctl_data_4_platforms::write_control_platforms(), t_ctl_data_4_divide_sphere::write_control_shell_domain(), t_ctl_data_4_time_steps::write_control_time_step_data(), t_ctl_data_4_fem_mesh::write_fem_mesh_control(), and t_ctl_data_4_fields::write_phys_data_control().
write_file_name_for_ctl_line()
subroutine write_control_elements::write_file_name_for_ctl_line (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, character(len=kchara), intent(in) fname)
Definition at line 518 of file write_control_elements.f90.
References skip_comment_f::write_space_4_parse().
Referenced by write_file_names_from_ctl_line().
write_file_names_from_ctl_line()
subroutine write_control_elements::write_file_names_from_ctl_line (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, integer (kind=kint), intent(in) num, character(len=kchara), dimension(num), intent(in) fname)
Definition at line 534 of file write_control_elements.f90.
References write_array_flag_for_ctl(), write_end_array_flag_for_ctl(), and write_file_name_for_ctl_line().
write_i2_r2_ctl_item()
subroutine write_control_elements::write_i2_r2_ctl_item (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, integer(kind = kint), intent(in) int1, integer(kind = kint), intent(in) int2, real(kind = kreal), intent(in) real1, real(kind = kreal), intent(in) real2)
Definition at line 413 of file write_control_elements.f90.
References skip_comment_f::write_ctl_chara_cont(), and skip_comment_f::write_space_4_parse().
Referenced by t_control_array_int2real2::write_control_array_i2_r2(), and t_control_array_int2real2::write_int2real2_ctl_type().
write_i2_r_ctl_item()
subroutine write_control_elements::write_i2_r_ctl_item (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, integer(kind = kint), intent(in) int1, integer(kind = kint), intent(in) int2, real(kind = kreal), intent(in) real_data)
Definition at line 396 of file write_control_elements.f90.
References skip_comment_f::write_ctl_chara_cont(), and skip_comment_f::write_space_4_parse().
Referenced by t_control_array_int2real::write_control_array_i2_r(), and t_control_array_int2real::write_int2real_ctl_type().
write_i_c_r_ctl_item()
subroutine write_control_elements::write_i_c_r_ctl_item (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, integer(kind = kint), intent(in) int_data, character(len=kchara), intent(in) chara_data, real(kind = kreal), intent(in) real_data)
Definition at line 430 of file write_control_elements.f90.
References skip_comment_f::write_ctl_chara_cont(), and skip_comment_f::write_space_4_parse().
Referenced by t_control_array_intcharreal::write_control_array_i_c_r(), and t_control_array_intcharreal::write_intcharreal_ctl_type().
write_int_real_ctl_item()
subroutine write_control_elements::write_int_real_ctl_item (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, integer (kind=kint), intent(in) int_data, real(kind = kreal), intent(in) real_data)
Definition at line 276 of file write_control_elements.f90.
References skip_comment_f::write_space_4_parse().
Referenced by t_control_array_intreal::write_control_array_i_r(), and t_control_array_intreal::write_intreal_ctl_type().
write_integer2_ctl_item()
subroutine write_control_elements::write_integer2_ctl_item (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, integer (kind=kint), intent(in) int1, integer (kind=kint), intent(in) int2)
Definition at line 293 of file write_control_elements.f90.
References skip_comment_f::write_space_4_parse().
Referenced by t_control_array_integer2::write_control_array_i2(), and t_control_array_integer2::write_integer2_ctl_type().
write_integer3_ctl_item()
subroutine write_control_elements::write_integer3_ctl_item (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, integer (kind=kint), intent(in) int1, integer (kind=kint), intent(in) int2, integer (kind=kint), intent(in) int3)
Definition at line 308 of file write_control_elements.f90.
References skip_comment_f::write_space_4_parse().
Referenced by t_control_array_integer3::write_control_array_i3(), and t_control_array_integer3::write_integer3_ctl_type().
write_integer_ctl_item()
subroutine write_control_elements::write_integer_ctl_item (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, integer(kind = kint), intent(in) maxlen, character(len=kchara), intent(in) label, integer (kind=kint), intent(in) int_data)
Definition at line 200 of file write_control_elements.f90.
References skip_comment_f::write_ctl_chara_cont(), skip_comment_f::write_space_4_parse(), and skip_comment_f::write_spaces().
Referenced by t_control_array_integer::write_control_array_i1(), and t_control_array_integer::write_integer_ctl_type().
write_real2_ctl_item()
subroutine write_control_elements::write_real2_ctl_item (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, real(kind = kreal), intent(in) real1, real(kind = kreal), intent(in) real2)
Definition at line 244 of file write_control_elements.f90.
References skip_comment_f::write_space_4_parse().
Referenced by t_control_array_real2::write_control_array_r2(), and t_control_array_real2::write_real2_ctl_type().
write_real3_ctl_item()
subroutine write_control_elements::write_real3_ctl_item (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, real(kind = kreal), intent(in) real1, real(kind = kreal), intent(in) real2, real(kind = kreal), intent(in) real3)
Definition at line 260 of file write_control_elements.f90.
References skip_comment_f::write_space_4_parse().
Referenced by t_control_array_real3::write_control_array_r3(), and t_control_array_real3::write_real3_ctl_type().
write_real_ctl_item()
subroutine write_control_elements::write_real_ctl_item (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, integer(kind = kint), intent(in) maxlen, character(len=kchara), intent(in) label, real(kind = kreal), intent(in) real_data)
Definition at line 178 of file write_control_elements.f90.
References skip_comment_f::write_ctl_chara_cont(), skip_comment_f::write_space_4_parse(), and skip_comment_f::write_spaces().
Referenced by t_control_array_real::write_control_array_r1(), and t_control_array_real::write_real_ctl_type().
Variable Documentation
hd_array
character(len=kchara), parameter write_control_elements::hd_array = 'array'
Label for an array control block.
Definition at line 98 of file write_control_elements.f90.
Referenced by write_array_flag_for_ctl(), and write_end_array_flag_for_ctl().
hd_begin
character(len=kchara), parameter write_control_elements::hd_begin = 'begin'
Label to start a control block.
Definition at line 94 of file write_control_elements.f90.
Referenced by write_begin_flag_for_ctl().
hd_end
character(len=kchara), parameter write_control_elements::hd_end = 'end'
Label to end a control block.
Definition at line 96 of file write_control_elements.f90.
Referenced by write_end_array_flag_for_ctl(), and write_end_flag_for_ctl().
hd_file
character(len=kchara), parameter write_control_elements::hd_file = 'file'
Label for an array control block.
Definition at line 100 of file write_control_elements.f90.