CALYPSO: t_sph_mhd_zonal_mean_viz Module Reference
t_sph_mhd_zonal_mean_viz Module Reference
Make zonal mean sections.
Data Types
type sph_zonal_mean_sectioning
Structures of zonal mean controls.
Functions/Subroutines
subroutine init_zonal_mean_sections (geofem, nod_fld, zm_ctls, zmeans)
subroutine sph_mhd_zmean_sections (istep_psf, time_d, sph, geofem, WK, nod_fld, zmeans)
subroutine sph_mhd_zonal_mean_section (istep_psf, time_d, sph, geofem, nod_fld, zm_psf)
subroutine, private sph_mhd_zonal_rms_section (istep_psf, time_d, sph, geofem, WK, nod_fld, zrms_psf)
Detailed Description
Make zonal mean sections.
      subroutine init_zonal_mean_sections                             &
     &         (geofem, nod_fld, zm_ctls, zmeans)
        type(mesh_data), intent(in) :: geofem
        type(phys_data), intent(in) :: nod_fld
        type(sph_dynamo_viz_controls), intent(inout) :: zm_ctls
        type(sph_zonal_mean_sectioning), intent(inout) :: zmeans
      subroutine SPH_MHD_zmean_sections(istep_psf, time_d,            &
     &          sph, geofem, WK, nod_fld, zmeans)
        type(sph_grids), intent(in) :: sph
        type(time_data), intent(in) :: time_d
        type(mesh_data), intent(in) :: geofem
        type(works_4_sph_trans_MHD), intent(in) :: WK
        type(phys_data), intent(inout) :: nod_fld
        type(sph_zonal_mean_sectioning), intent(inout) :: zmeans
      subroutine SPH_MHD_zonal_mean_section(istep_psf, time_d,        &
     &          sph, geofem, nod_fld, zm_psf)
        type(sph_grids), intent(in) :: sph
        type(time_data), intent(in) :: time_d
        type(mesh_data), intent(in) :: geofem
        type(phys_data), intent(inout) :: nod_fld
        type(sectioning_module), intent(inout) :: zm_psf
Function/Subroutine Documentation
init_zonal_mean_sections()
subroutine t_sph_mhd_zonal_mean_viz::init_zonal_mean_sections (type(mesh_data), intent(in) geofem, type(phys_data), intent(in) nod_fld, type(sph_dynamo_viz_controls), intent(inout) zm_ctls, type(sph_zonal_mean_sectioning), intent(inout) zmeans)
Definition at line 68 of file t_SPH_MHD_zonal_mean_viz.f90.
References m_work_time::end_elapsed_time(), m_elapsed_labels_4_viz::iflag_viz_time, m_elapsed_labels_4_viz::ist_elapsed_viz, t_cross_section::sectioning_initialize(), and m_work_time::start_elapsed_time().
Referenced by analyzer_sph_mhd_w_psf::initialize_sph_mhd_w_psf(), and analyzer_sph_snap_w_psf::initialize_sph_snap_w_psf().
sph_mhd_zmean_sections()
subroutine t_sph_mhd_zonal_mean_viz::sph_mhd_zmean_sections (integer(kind = kint), intent(in) istep_psf, type(time_data), intent(in) time_d, type(sph_grids), intent(in) sph, type(mesh_data), intent(in) geofem, type(works_4_sph_trans_mhd), intent(in) WK, type(phys_data), intent(inout) nod_fld, type(sph_zonal_mean_sectioning), intent(inout) zmeans)
Definition at line 91 of file t_SPH_MHD_zonal_mean_viz.f90.
References sph_mhd_zonal_mean_section(), and sph_mhd_zonal_rms_section().
Referenced by analyzer_sph_mhd_w_psf::evolution_sph_mhd_w_psf(), and analyzer_sph_snap_w_psf::evolution_sph_snap_w_psf().
sph_mhd_zonal_mean_section()
subroutine t_sph_mhd_zonal_mean_viz::sph_mhd_zonal_mean_section (integer(kind = kint), intent(in) istep_psf, type(time_data), intent(in) time_d, type(sph_grids), intent(in) sph, type(mesh_data), intent(in) geofem, type(phys_data), intent(inout) nod_fld, type(sectioning_module), intent(inout) zm_psf)
Definition at line 118 of file t_SPH_MHD_zonal_mean_viz.f90.
References m_work_time::end_elapsed_time(), m_machine_parameter::iflag_debug, m_elapsed_labels_4_viz::iflag_viz_time, m_elapsed_labels_4_viz::ist_elapsed_viz, nod_phys_send_recv::nod_fields_send_recv(), t_cross_section::sectioning_visualize(), m_work_time::start_elapsed_time(), and sph_rtp_zonal_rms_data::zonal_mean_all_rtp_field().
Referenced by sph_mhd_zmean_sections().
sph_mhd_zonal_rms_section()
subroutine, private t_sph_mhd_zonal_mean_viz::sph_mhd_zonal_rms_section (integer(kind = kint), intent(in) istep_psf, type(time_data), intent(in) time_d, type(sph_grids), intent(in) sph, type(mesh_data), intent(in) geofem, type(works_4_sph_trans_mhd), intent(in) WK, type(phys_data), intent(inout) nod_fld, type(sectioning_module), intent(inout) zrms_psf) private
Definition at line 154 of file t_SPH_MHD_zonal_mean_viz.f90.
References m_work_time::end_elapsed_time(), m_machine_parameter::iflag_debug, m_elapsed_labels_4_viz::iflag_viz_time, m_elapsed_labels_4_viz::ist_elapsed_viz, nod_phys_send_recv::nod_fields_send_recv(), t_cross_section::sectioning_visualize(), fem_analyzer_sph_mhd::sph_to_fem_bridge_mhd(), m_work_time::start_elapsed_time(), and sph_rtp_zonal_rms_data::zonal_rms_all_rtp_field().
Referenced by sph_mhd_zmean_sections().