CALYPSO: m_merged_field_fmt_labels Module Reference
m_merged_field_fmt_labels Module Reference
Integer flags for field data file format.
Functions/Subroutines
subroutine init_mgd_field_type_flags ()
subroutine dealloc_mgd_field_type_flags ()
Variables
character(len=kchara), dimension(3), parameter hdf5_names = (/'HDF5 ', 'merged_HDF5 ', 'single_HDF5 '/)
flag parts for HDF data
type(multi_flag_labels), save mgd_fld_ascii_labels
type(multi_flag_labels), save mgd_fld_bin_labels
type(multi_flag_labels), save mgd_fld_gz_labels
type(multi_flag_labels), save mgd_fbin_gz_labels
type(multi_flag_labels), save mgd_ucd_labels
Character lables for merged UCD 'merged_UCD', 'single_UCD', 'UCD_merged', 'UCD_single'.
type(multi_flag_labels), save mgd_udt_labels
Character lables for merged splitted UCD into mesh and data 'merged_UDT', 'single_UDT', 'UDT_merged', 'UDT_single',.
type(multi_flag_labels), save mgd_vtk_labels
Character lables for merged VTK 'merged_VTK', 'single_VTK', 'VTK_merged', 'VTK_single'.
type(multi_flag_labels), save mgd_vtd_labels
Character lables for merged splitted VTK mesh and data 'merged_VTD', 'single_VTD', 'VTD_merged', 'VTD_single'.
type(multi_flag_labels), save mgd_iso_labels
Character lables for merged isosurface binary 'merged_ISO', 'single_ISO', 'ISO_merged', 'ISO_single'.
type(multi_flag_labels), save mgd_psf_labels
Character lables for merged sections binary 'merged_PSF', 'single_PSF', 'PSF_merged', 'PSF_single'.
type(multi_flag_labels), save mgd_udt_gz_labels
Character lables for gzipped merged splitted UCD into mesh and data 'merged_UDT_gzip', 'merged_UDT_gz', 'single_UDT_gzip', 'single_UDT_gz', 'UDT_merged_gzip', 'UDT_merged_gz', 'UDT_single_gzip', 'UDT_single_gz', 'gzip_merged_UDT', 'gzip_single_UDT', 'gzip_UDT_merged', 'gzip_UDT_single', 'gz_merged_UDT', 'gz_single_UDT', 'gz_UDT_merged',
'gz_UDT_single',.
type(multi_flag_labels), save mgd_ucd_gz_labels
Character lables for gzipped merged UCD 'merged_UCD_gzip', 'merged_UCD_gz', 'single_UCD_gzip', 'single_UCD_gz', 'UCD_merged_gzip', 'UCD_merged_gz', 'UCD_single_gzip', 'UCD_single_gz', 'gzip_merged_UCD', 'gzip_single_UCD', 'gzip_UCD_merged', 'gzip_UCD_single', 'gz_merged_UCD', 'gz_single_UCD', 'gz_UCD_merged', 'gz_UCD_single'.
type(multi_flag_labels), save mgd_vtk_gz_labels
Character lables for gzipped merged VTK 'merged_VTK_gzip', 'merged_VTK_gz', 'single_VTK_gzip', 'single_VTK_gz', 'VTK_merged_gzip', 'VTK_merged_gz', 'VTK_single_gzip', 'VTK_single_gz', 'gzip_merged_VTK', 'gzip_single_VTK', 'gzip_VTK_merged', 'gzip_VTK_single', 'gz_merged_VTK', 'gz_single_VTK', 'gz_VTK_merged', 'gz_VTK_single'.
type(multi_flag_labels), save mgd_vtd_gz_labels
Character lables for gzipped merged splitted VTK mesh and data 'merged_VTD_gzip', 'merged_VTD_gz', 'single_VTD_gzip', 'single_VTD_gz', 'VTD_merged_gzip', 'VTD_merged_gz', 'VTD_single_gzip', 'VTD_single_gz', 'gzip_merged_VTD', 'gzip_single_VTD', 'gzip_VTD_merged', 'gzip_VTD_single', 'gz_merged_VTD', 'gz_single_VTD', 'gz_VTD_merged', 'gz_VTD_single'.
type(multi_flag_labels), save mgd_iso_gz_labels
Character lables for gzipped merged isosurface binary 'merged_ISO_gzip', 'merged_ISO_gz', 'single_ISO_gzip', 'single_ISO_gz', 'ISO_merged_gzip', 'ISO_merged_gz', 'ISO_single_gzip', 'ISO_single_gz', 'gzip_merged_ISO', 'gzip_single_ISO', 'gzip_ISO_merged', 'gzip_ISO_single', 'gz_merged_ISO', 'gz_single_ISO', 'gz_ISO_merged', 'gz_ISO_single'.
type(multi_flag_labels), save mgd_psf_gz_labels
Character lables for gzipped merged sections binary 'merged_PSF_gzip', 'merged_PSF_gz', 'single_PSF_gzip', 'single_PSF_gz', 'PSF_merged_gzip', 'PSF_merged_gz', 'PSF_single_gzip', 'PSF_single_gz', 'gzip_merged_PSF', 'gzip_single_PSF', 'gzip_PSF_merged', 'gzip_PSF_single', 'gz_merged_PSF', 'gz_single_PSF', 'gz_PSF_merged', 'gz_PSF_single'.
type(multi_flag_labels), save mgd_hdf_labels
Character lables for parallel HDF5 'HDF5', 'merged_HDF5', 'single_HDF5'.
Detailed Description
Integer flags for field data file format.
      subroutine init_mgd_field_type_flags()
      subroutine dealloc_mgd_field_type_flags()
Function/Subroutine Documentation
dealloc_mgd_field_type_flags()
subroutine m_merged_field_fmt_labels::dealloc_mgd_field_type_flags
Definition at line 178 of file m_merged_field_fmt_labels.f90.
References m_field_file_format_labels::dealloc_field_type_flags(), t_multi_flag_labels::dealloc_multi_flags(), mgd_fbin_gz_labels, mgd_fld_ascii_labels, mgd_fld_bin_labels, mgd_fld_gz_labels, mgd_hdf_labels, mgd_iso_gz_labels, mgd_iso_labels, mgd_psf_gz_labels, mgd_psf_labels, mgd_ucd_gz_labels, mgd_ucd_labels, mgd_udt_gz_labels, mgd_udt_labels, mgd_vtd_gz_labels, mgd_vtd_labels, mgd_vtk_gz_labels, and mgd_vtk_labels.
Referenced by m_field_file_format::choose_para_fld_file_format(), t_control_params_4_iso::sel_iso_file_format(), and t_control_params_4_psf::sel_psf_file_format().
init_mgd_field_type_flags()
subroutine m_merged_field_fmt_labels::init_mgd_field_type_flags
Definition at line 127 of file m_merged_field_fmt_labels.f90.
References t_multi_flag_labels::append_multi_flag_labels(), m_field_file_format_labels::fbin_gz_labels, m_field_file_format_labels::field_ascii_labels, m_field_file_format_labels::field_bin_labels, m_field_file_format_labels::field_gz_labels, m_file_format_labels::gzip_flags, hdf5_names, m_field_file_format_labels::init_field_type_flags(), t_multi_flag_labels::init_from_two_kinds_flags(), t_multi_flag_labels::init_multi_flags_by_labels(), m_field_file_format_labels::iso_flags, m_file_format_labels::merged_flags, mgd_fbin_gz_labels, mgd_fld_ascii_labels, mgd_fld_bin_labels, mgd_fld_gz_labels, mgd_hdf_labels, mgd_iso_gz_labels, mgd_iso_labels, mgd_psf_gz_labels, mgd_psf_labels, mgd_ucd_gz_labels, mgd_ucd_labels, mgd_udt_gz_labels, mgd_udt_labels, mgd_vtd_gz_labels, mgd_vtd_labels, mgd_vtk_gz_labels, mgd_vtk_labels, m_field_file_format_labels::psf_flags, m_field_file_format_labels::ucd_flags, m_field_file_format_labels::udt_flags, m_field_file_format_labels::vtd_flags, and m_field_file_format_labels::vtk_flags.
Referenced by m_field_file_format::choose_para_fld_file_format(), t_control_params_4_iso::sel_iso_file_format(), and t_control_params_4_psf::sel_psf_file_format().
Variable Documentation
hdf5_names
character(len = kchara), dimension(3), parameter m_merged_field_fmt_labels::hdf5_names = (/'HDF5 ', 'merged_HDF5 ', 'single_HDF5 '/)
flag parts for HDF data
Definition at line 27 of file m_merged_field_fmt_labels.f90.
Referenced by init_mgd_field_type_flags().
mgd_fbin_gz_labels
type(multi_flag_labels), save m_merged_field_fmt_labels::mgd_fbin_gz_labels
Definition at line 34 of file m_merged_field_fmt_labels.f90.
Referenced by m_field_file_format::choose_para_fld_file_format(), dealloc_mgd_field_type_flags(), init_mgd_field_type_flags(), t_control_params_4_iso::sel_iso_file_format(), and t_control_params_4_psf::sel_psf_file_format().
mgd_fld_ascii_labels
type(multi_flag_labels), save m_merged_field_fmt_labels::mgd_fld_ascii_labels
Definition at line 31 of file m_merged_field_fmt_labels.f90.
Referenced by m_field_file_format::choose_para_fld_file_format(), dealloc_mgd_field_type_flags(), init_mgd_field_type_flags(), t_control_params_4_iso::sel_iso_file_format(), and t_control_params_4_psf::sel_psf_file_format().
mgd_fld_bin_labels
type(multi_flag_labels), save m_merged_field_fmt_labels::mgd_fld_bin_labels
Definition at line 32 of file m_merged_field_fmt_labels.f90.
Referenced by m_field_file_format::choose_para_fld_file_format(), dealloc_mgd_field_type_flags(), init_mgd_field_type_flags(), t_control_params_4_iso::sel_iso_file_format(), and t_control_params_4_psf::sel_psf_file_format().
mgd_fld_gz_labels
type(multi_flag_labels), save m_merged_field_fmt_labels::mgd_fld_gz_labels
Definition at line 33 of file m_merged_field_fmt_labels.f90.
Referenced by m_field_file_format::choose_para_fld_file_format(), dealloc_mgd_field_type_flags(), init_mgd_field_type_flags(), t_control_params_4_iso::sel_iso_file_format(), and t_control_params_4_psf::sel_psf_file_format().
mgd_hdf_labels
type(multi_flag_labels), save m_merged_field_fmt_labels::mgd_hdf_labels
Character lables for parallel HDF5 'HDF5', 'merged_HDF5', 'single_HDF5'.
Definition at line 119 of file m_merged_field_fmt_labels.f90.
Referenced by m_field_file_format::choose_para_fld_file_format(), dealloc_mgd_field_type_flags(), and init_mgd_field_type_flags().
mgd_iso_gz_labels
type(multi_flag_labels), save m_merged_field_fmt_labels::mgd_iso_gz_labels
Character lables for gzipped merged isosurface binary 'merged_ISO_gzip', 'merged_ISO_gz', 'single_ISO_gzip', 'single_ISO_gz', 'ISO_merged_gzip', 'ISO_merged_gz', 'ISO_single_gzip', 'ISO_single_gz', 'gzip_merged_ISO', 'gzip_single_ISO', 'gzip_ISO_merged', 'gzip_ISO_single', 'gz_merged_ISO', 'gz_single_ISO', 'gz_ISO_merged', 'gz_ISO_single'.
Definition at line 105 of file m_merged_field_fmt_labels.f90.
Referenced by dealloc_mgd_field_type_flags(), init_mgd_field_type_flags(), t_control_params_4_iso::sel_iso_file_format(), and t_control_params_4_psf::sel_psf_file_format().
mgd_iso_labels
type(multi_flag_labels), save m_merged_field_fmt_labels::mgd_iso_labels
Character lables for merged isosurface binary 'merged_ISO', 'single_ISO', 'ISO_merged', 'ISO_single'.
Definition at line 54 of file m_merged_field_fmt_labels.f90.
Referenced by dealloc_mgd_field_type_flags(), init_mgd_field_type_flags(), t_control_params_4_iso::sel_iso_file_format(), and t_control_params_4_psf::sel_psf_file_format().
mgd_psf_gz_labels
type(multi_flag_labels), save m_merged_field_fmt_labels::mgd_psf_gz_labels
Character lables for gzipped merged sections binary 'merged_PSF_gzip', 'merged_PSF_gz', 'single_PSF_gzip', 'single_PSF_gz', 'PSF_merged_gzip', 'PSF_merged_gz', 'PSF_single_gzip', 'PSF_single_gz', 'gzip_merged_PSF', 'gzip_single_PSF', 'gzip_PSF_merged', 'gzip_PSF_single', 'gz_merged_PSF', 'gz_single_PSF', 'gz_PSF_merged', 'gz_PSF_single'.
Definition at line 114 of file m_merged_field_fmt_labels.f90.
Referenced by dealloc_mgd_field_type_flags(), init_mgd_field_type_flags(), t_control_params_4_iso::sel_iso_file_format(), and t_control_params_4_psf::sel_psf_file_format().
mgd_psf_labels
type(multi_flag_labels), save m_merged_field_fmt_labels::mgd_psf_labels
Character lables for merged sections binary 'merged_PSF', 'single_PSF', 'PSF_merged', 'PSF_single'.
Definition at line 58 of file m_merged_field_fmt_labels.f90.
Referenced by dealloc_mgd_field_type_flags(), init_mgd_field_type_flags(), t_control_params_4_iso::sel_iso_file_format(), and t_control_params_4_psf::sel_psf_file_format().
mgd_ucd_gz_labels
type(multi_flag_labels), save m_merged_field_fmt_labels::mgd_ucd_gz_labels
Character lables for gzipped merged UCD 'merged_UCD_gzip', 'merged_UCD_gz', 'single_UCD_gzip', 'single_UCD_gz', 'UCD_merged_gzip', 'UCD_merged_gz', 'UCD_single_gzip', 'UCD_single_gz', 'gzip_merged_UCD', 'gzip_single_UCD', 'gzip_UCD_merged', 'gzip_UCD_single', 'gz_merged_UCD', 'gz_single_UCD', 'gz_UCD_merged', 'gz_UCD_single'.
Definition at line 78 of file m_merged_field_fmt_labels.f90.
Referenced by m_field_file_format::choose_para_fld_file_format(), dealloc_mgd_field_type_flags(), init_mgd_field_type_flags(), t_control_params_4_iso::sel_iso_file_format(), and t_control_params_4_psf::sel_psf_file_format().
mgd_ucd_labels
type(multi_flag_labels), save m_merged_field_fmt_labels::mgd_ucd_labels
Character lables for merged UCD 'merged_UCD', 'single_UCD', 'UCD_merged', 'UCD_single'.
Definition at line 38 of file m_merged_field_fmt_labels.f90.
Referenced by m_field_file_format::choose_para_fld_file_format(), dealloc_mgd_field_type_flags(), init_mgd_field_type_flags(), t_control_params_4_iso::sel_iso_file_format(), and t_control_params_4_psf::sel_psf_file_format().
mgd_udt_gz_labels
type(multi_flag_labels), save m_merged_field_fmt_labels::mgd_udt_gz_labels
Character lables for gzipped merged splitted UCD into mesh and data 'merged_UDT_gzip', 'merged_UDT_gz', 'single_UDT_gzip', 'single_UDT_gz', 'UDT_merged_gzip', 'UDT_merged_gz', 'UDT_single_gzip', 'UDT_single_gz', 'gzip_merged_UDT', 'gzip_single_UDT', 'gzip_UDT_merged', 'gzip_UDT_single', 'gz_merged_UDT', 'gz_single_UDT', 'gz_UDT_merged',
'gz_UDT_single',.
Definition at line 69 of file m_merged_field_fmt_labels.f90.
Referenced by m_field_file_format::choose_para_fld_file_format(), dealloc_mgd_field_type_flags(), init_mgd_field_type_flags(), t_control_params_4_iso::sel_iso_file_format(), and t_control_params_4_psf::sel_psf_file_format().
mgd_udt_labels
type(multi_flag_labels), save m_merged_field_fmt_labels::mgd_udt_labels
Character lables for merged splitted UCD into mesh and data 'merged_UDT', 'single_UDT', 'UDT_merged', 'UDT_single',.
Definition at line 42 of file m_merged_field_fmt_labels.f90.
Referenced by m_field_file_format::choose_para_fld_file_format(), dealloc_mgd_field_type_flags(), init_mgd_field_type_flags(), t_control_params_4_iso::sel_iso_file_format(), and t_control_params_4_psf::sel_psf_file_format().
mgd_vtd_gz_labels
type(multi_flag_labels), save m_merged_field_fmt_labels::mgd_vtd_gz_labels
Character lables for gzipped merged splitted VTK mesh and data 'merged_VTD_gzip', 'merged_VTD_gz', 'single_VTD_gzip', 'single_VTD_gz', 'VTD_merged_gzip', 'VTD_merged_gz', 'VTD_single_gzip', 'VTD_single_gz', 'gzip_merged_VTD', 'gzip_single_VTD', 'gzip_VTD_merged', 'gzip_VTD_single', 'gz_merged_VTD', 'gz_single_VTD', 'gz_VTD_merged', 'gz_VTD_single'.
Definition at line 96 of file m_merged_field_fmt_labels.f90.
Referenced by m_field_file_format::choose_para_fld_file_format(), dealloc_mgd_field_type_flags(), init_mgd_field_type_flags(), t_control_params_4_iso::sel_iso_file_format(), and t_control_params_4_psf::sel_psf_file_format().
mgd_vtd_labels
type(multi_flag_labels), save m_merged_field_fmt_labels::mgd_vtd_labels
Character lables for merged splitted VTK mesh and data 'merged_VTD', 'single_VTD', 'VTD_merged', 'VTD_single'.
Definition at line 50 of file m_merged_field_fmt_labels.f90.
Referenced by m_field_file_format::choose_para_fld_file_format(), dealloc_mgd_field_type_flags(), init_mgd_field_type_flags(), t_control_params_4_iso::sel_iso_file_format(), and t_control_params_4_psf::sel_psf_file_format().
mgd_vtk_gz_labels
type(multi_flag_labels), save m_merged_field_fmt_labels::mgd_vtk_gz_labels
Character lables for gzipped merged VTK 'merged_VTK_gzip', 'merged_VTK_gz', 'single_VTK_gzip', 'single_VTK_gz', 'VTK_merged_gzip', 'VTK_merged_gz', 'VTK_single_gzip', 'VTK_single_gz', 'gzip_merged_VTK', 'gzip_single_VTK', 'gzip_VTK_merged', 'gzip_VTK_single', 'gz_merged_VTK', 'gz_single_VTK', 'gz_VTK_merged', 'gz_VTK_single'.
Definition at line 87 of file m_merged_field_fmt_labels.f90.
Referenced by m_field_file_format::choose_para_fld_file_format(), dealloc_mgd_field_type_flags(), init_mgd_field_type_flags(), t_control_params_4_iso::sel_iso_file_format(), and t_control_params_4_psf::sel_psf_file_format().
mgd_vtk_labels
type(multi_flag_labels), save m_merged_field_fmt_labels::mgd_vtk_labels
Character lables for merged VTK 'merged_VTK', 'single_VTK', 'VTK_merged', 'VTK_single'.
Definition at line 46 of file m_merged_field_fmt_labels.f90.
Referenced by m_field_file_format::choose_para_fld_file_format(), dealloc_mgd_field_type_flags(), init_mgd_field_type_flags(), t_control_params_4_iso::sel_iso_file_format(), and t_control_params_4_psf::sel_psf_file_format().