CALYPSO: matmul_for_legendre_trans Module Reference
matmul_for_legendre_trans Module Reference
Matrix products for Legendre transforms.
Functions/Subroutines
subroutine matmul_fwd_leg_trans (iflag_matmul, nkr, n_jk, nl_rtm, V_kl, P_lj, S_kj)
subroutine matmul_bwd_leg_trans (iflag_matmul, nl_rtm, nkr, n_jk, P_lj, S_jk, V_lk)
subroutine matmul_fwd_leg_trans_pjl (iflag_matmul, n_jk, nkr, nl_rtm, P_jl, V_lk, S_jk)
subroutine matmul_bwd_leg_trans_pjl (iflag_matmul, nkr, nl_rtm, n_jk, S_kj, P_jl, V_kl)
subroutine add_matmul_fwd_leg_trans (iflag_matmul, nkr, n_jk, nl_rtm, V_kl, P_lj, coef, S_kj)
subroutine add_matmul_bwd_leg_trans (iflag_matmul, nl_rtm, nkr, n_jk, P_lj, S_jk, coef, V_lk)
subroutine matmat_leg_trans (np1, np2, nab, Amat, Bmat, Prod)
subroutine, private add_matmat_leg_trans (np1, np2, nab, Amat, Bmat, coef, Prod)
Variables
integer(kind=kint), parameter iflag_intrinsic = 1
integer(kind=kint), parameter iflag_dgemm = 2
integer(kind=kint), parameter iflag_matprod = 3
Detailed Description
Matrix products for Legendre transforms.
      subroutine matmul_fwd_leg_trans(iflag_matmul, nkr, n_jk, nl_rtm,&
     &          V_kl, P_lj, S_kj)
      subroutine matmul_bwd_leg_trans(iflag_matmul, nl_rtm, nkr, n_jk,&
     &          P_lj, S_jk, V_lk)
      subroutine matmul_fwd_leg_trans_Pjl(iflag_matmul,               &
     &          n_jk, nkr, nl_rtm, P_jl, V_lk, S_jk)
      subroutine matmul_bwd_leg_trans_Pjl(iflag_matmul,               &
     &          nkr, nl_rtm, n_jk, S_kj, P_jl, V_kl)
      subroutine add_matmul_fwd_leg_trans(iflag_matmul,               &
     &          nkr, n_jk, nl_rtm, V_kl, P_lj, coef, S_kj)
      subroutine add_matmul_bwd_leg_trans(iflag_matmul,               &
     &          nl_rtm, nkr, n_jk, P_lj, S_jk, coef, V_lk)
      subroutine matmat_leg_trans(np1, np2, nab, Amat, Bmat, Prod)
Parameters
nkr Number of radial grid and field
n_jk Number of spherical harmonic degree for transform
nl_rtm Number of meridional grids
P_lj Matrix for Legendre polynomials
V_kl field data \(f(r,\theta,m) \) with V_kl(r,theta)
S_kj spectrum data \(f(r,l,m) \) with S_kj(r,l)
V_lk field data \(f(r,\theta,m) \) with V_kl(theta,r)
S_jk spectrum data \(f(r,l,m) \) with S_jk(l,r)
Function/Subroutine Documentation
add_matmat_leg_trans()
subroutine, private matmul_for_legendre_trans::add_matmat_leg_trans (integer(kind = kint), intent(in) np1, integer(kind = kint), intent(in) np2, integer(kind = kint), intent(in) nab, real(kind = kreal), dimension(np1,nab), intent(in) Amat, real(kind = kreal), dimension(nab,np2), intent(in) Bmat, real(kind = kreal), intent(in) coef, real(kind = kreal), dimension(np1,np2), intent(inout) Prod) private
Definition at line 292 of file matmul_for_legendre_trans.F90.
Referenced by add_matmul_bwd_leg_trans(), and add_matmul_fwd_leg_trans().
add_matmul_bwd_leg_trans()
subroutine matmul_for_legendre_trans::add_matmul_bwd_leg_trans (integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) nl_rtm, integer(kind = kint), intent(in) nkr, integer(kind = kint), intent(in) n_jk, real(kind = kreal), dimension(nl_rtm,n_jk), intent(in) P_lj, real(kind = kreal), dimension(n_jk,nkr), intent(in) S_jk, real(kind = kreal), intent(in) coef, real(kind = kreal), dimension(nl_rtm,nkr), intent(inout) V_lk)
Definition at line 228 of file matmul_for_legendre_trans.F90.
References add_matmat_leg_trans(), iflag_dgemm, iflag_intrinsic, and m_constants::one.
add_matmul_fwd_leg_trans()
subroutine matmul_for_legendre_trans::add_matmul_fwd_leg_trans (integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) nkr, integer(kind = kint), intent(in) n_jk, integer(kind = kint), intent(in) nl_rtm, real(kind = kreal), dimension(nkr,nl_rtm), intent(in) V_kl, real(kind = kreal), dimension(nl_rtm,n_jk), intent(in) P_lj, real(kind = kreal), intent(in) coef, real(kind = kreal), dimension(nkr,n_jk), intent(inout) S_kj)
Definition at line 193 of file matmul_for_legendre_trans.F90.
References add_matmat_leg_trans(), iflag_dgemm, iflag_intrinsic, and m_constants::one.
matmat_leg_trans()
subroutine matmul_for_legendre_trans::matmat_leg_trans (integer(kind = kint), intent(in) np1, integer(kind = kint), intent(in) np2, integer(kind = kint), intent(in) nab, real(kind = kreal), dimension(np1,nab), intent(in) Amat, real(kind = kreal), dimension(nab,np2), intent(in) Bmat, real(kind = kreal), dimension(np1,np2), intent(inout) Prod)
Definition at line 266 of file matmul_for_legendre_trans.F90.
Referenced by matmul_bwd_leg_trans(), matmul_bwd_leg_trans_pjl(), matmul_fwd_leg_trans(), and matmul_fwd_leg_trans_pjl().
matmul_bwd_leg_trans()
subroutine matmul_for_legendre_trans::matmul_bwd_leg_trans (integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) nl_rtm, integer(kind = kint), intent(in) nkr, integer(kind = kint), intent(in) n_jk, real(kind = kreal), dimension(nl_rtm,n_jk), intent(in) P_lj, real(kind = kreal), dimension(n_jk,nkr), intent(in) S_jk, real(kind = kreal), dimension(nl_rtm,nkr), intent(inout) V_lk)
Definition at line 90 of file matmul_for_legendre_trans.F90.
References iflag_dgemm, iflag_intrinsic, matmat_leg_trans(), m_constants::one, and m_constants::zero.
Referenced by legendre_bwd_sym_matmul::leg_b_trans_scl_sym_matmul(), legendre_bwd_sym_matmul::leg_b_trans_vec_sym_matmul(), leg_b_trans_sym_matmul_big::leg_bwd_trans_sym_matmul_big(), and leg_bwd_trans_sym_mat_tj::legendre_b_trans_sym_mat_tj().
matmul_bwd_leg_trans_pjl()
subroutine matmul_for_legendre_trans::matmul_bwd_leg_trans_pjl (integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) nkr, integer(kind = kint), intent(in) nl_rtm, integer(kind = kint), intent(in) n_jk, real(kind = kreal), dimension(nkr,n_jk), intent(in) S_kj, real(kind = kreal), dimension(n_jk,nl_rtm), intent(in) P_jl, real(kind = kreal), dimension(nkr,nl_rtm), intent(inout) V_kl)
Definition at line 157 of file matmul_for_legendre_trans.F90.
References iflag_dgemm, iflag_intrinsic, matmat_leg_trans(), m_constants::one, and m_constants::zero.
Referenced by leg_bwd_trans_sym_mat_jt::legendre_b_trans_sym_mat_jt().
matmul_fwd_leg_trans()
subroutine matmul_for_legendre_trans::matmul_fwd_leg_trans (integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) nkr, integer(kind = kint), intent(in) n_jk, integer(kind = kint), intent(in) nl_rtm, real(kind = kreal), dimension(nkr,nl_rtm), intent(in) V_kl, real(kind = kreal), dimension(nl_rtm,n_jk), intent(in) P_lj, real(kind = kreal), dimension(nkr,n_jk), intent(inout) S_kj)
Definition at line 57 of file matmul_for_legendre_trans.F90.
References iflag_dgemm, iflag_intrinsic, matmat_leg_trans(), m_constants::one, and m_constants::zero.
Referenced by legendre_fwd_sym_matmul::leg_f_trans_scl_sym_matmul(), legendre_fwd_sym_matmul::leg_f_trans_vec_sym_matmul(), leg_f_trans_sym_matmul_big::leg_fwd_trans_sym_matmul_big(), and leg_fwd_trans_sym_mat_tj::legendre_f_trans_sym_mat_tj().
matmul_fwd_leg_trans_pjl()
subroutine matmul_for_legendre_trans::matmul_fwd_leg_trans_pjl (integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) n_jk, integer(kind = kint), intent(in) nkr, integer(kind = kint), intent(in) nl_rtm, real(kind = kreal), dimension(n_jk,nl_rtm), intent(in) P_jl, real(kind = kreal), dimension(nl_rtm,nkr), intent(in) V_lk, real(kind = kreal), dimension(n_jk,nkr), intent(inout) S_jk)
Definition at line 126 of file matmul_for_legendre_trans.F90.
References iflag_dgemm, iflag_intrinsic, matmat_leg_trans(), m_constants::one, and m_constants::zero.
Referenced by leg_fwd_trans_sym_mat_jt::legendre_f_trans_sym_mat_jt().
Variable Documentation
iflag_dgemm
integer(kind = kint), parameter matmul_for_legendre_trans::iflag_dgemm = 2
Definition at line 46 of file matmul_for_legendre_trans.F90.
Referenced by add_matmul_bwd_leg_trans(), add_matmul_fwd_leg_trans(), small_matmul_leg_trans_krin::matmul2_bwd_leg_trans_pjt(), small_matmul_leg_trans_krin::matmul2_fwd_leg_trans_ptj(), small_matmul_leg_trans_krin::matmul4_bwd_leg_trans_pjt(), small_matmul_leg_trans_krin::matmul4_fwd_leg_trans_ptj(), small_matmul_leg_trans_krin::matmul8_bwd_leg_trans_pjt(), small_matmul_leg_trans_krin::matmul8_fwd_leg_trans_ptj(), matmul_bwd_leg_trans(), matmul_bwd_leg_trans_pjl(), matmul_fwd_leg_trans(), matmul_fwd_leg_trans_pjl(), t_legendre_trans_select::sel_backward_legendre_trans(), and t_legendre_trans_select::sel_forward_legendre_trans().
iflag_intrinsic
integer(kind = kint), parameter matmul_for_legendre_trans::iflag_intrinsic = 1
Definition at line 45 of file matmul_for_legendre_trans.F90.
Referenced by add_matmul_bwd_leg_trans(), add_matmul_fwd_leg_trans(), legendre_transform_testloop::leg_backward_trans_test(), small_matmul_leg_trans_krin::matmul2_bwd_leg_trans_pjt(), small_matmul_leg_trans_krin::matmul2_fwd_leg_trans_ptj(), small_matmul_leg_trans_krin::matmul4_bwd_leg_trans_pjt(), small_matmul_leg_trans_krin::matmul4_fwd_leg_trans_ptj(), small_matmul_leg_trans_krin::matmul8_bwd_leg_trans_pjt(), small_matmul_leg_trans_krin::matmul8_fwd_leg_trans_ptj(), matmul_bwd_leg_trans(), matmul_bwd_leg_trans_pjl(), matmul_fwd_leg_trans(), matmul_fwd_leg_trans_pjl(), small_matmul_leg_trans_krin::matvec_bwd_leg_trans_pj(), t_legendre_trans_select::sel_backward_legendre_trans(), and t_legendre_trans_select::sel_forward_legendre_trans().
iflag_matprod
integer(kind = kint), parameter matmul_for_legendre_trans::iflag_matprod = 3
Definition at line 47 of file matmul_for_legendre_trans.F90.
Referenced by legendre_transform_testloop::leg_forward_trans_test(), t_legendre_trans_select::sel_backward_legendre_trans(), and t_legendre_trans_select::sel_forward_legendre_trans().