CALYPSO: cal_nonlinear Module Reference
cal_nonlinear Module Reference
Evaluate nonlinear terms by pseudo spectram scheme.
Functions/Subroutines
subroutine nonlinear (r_2nd, SPH_model, trans_p, WK, SPH_MHD)
subroutine nonlinear_by_pseudo_sph (sph, comms_sph, omega_sph, r_2nd, MHD_prop, sph_MHD_bc, trans_p, gt_cor, trns_MHD, WK_leg, WK_FFTs_MHD, cor_rlm, ipol, rj_fld)
subroutine licv_exp (ref_temp, ref_comp, MHD_prop, sph_MHD_bc, sph, comms_sph, omega_sph, trans_p, ipol, WK, rj_fld)
Detailed Description
Evaluate nonlinear terms by pseudo spectram scheme.
      subroutine nonlinear(r_2nd, SPH_model, trans_p, WK, SPH_MHD)
        type(fdm_matrices), intent(in) :: r_2nd
        type(SGS_model_control_params), intent(in) :: SGS_param
        type(works_4_sph_trans_MHD), intent(inout) :: WK
        type(SPH_mesh_field_data), intent(inout) :: SPH_MHD
      subroutine nonlinear_by_pseudo_sph                              &
     &         (sph, comms_sph, omega_sph, r_2nd, MHD_prop,           &
     &          sph_MHD_bc, trans_p, gt_cor, trns_MHD,                &
     &          WK_leg, WK_FFTs_MHD, cor_rlm, ipol, rj_fld)
        type(sph_grids), intent(in) :: sph
        type(sph_comm_tables), intent(in) :: comms_sph
        type(fdm_matrices), intent(in) :: r_2nd
        type(sph_rotation), intent(in) :: omega_sph
        type(MHD_evolution_param), intent(in) :: MHD_prop
        type(sph_MHD_boundary_data), intent(in) :: sph_MHD_bc
        type(parameters_4_sph_trans), intent(in) :: trans_p
        type(gaunt_coriolis_rlm), intent(in) :: gt_cor
        type(phys_address), intent(in) :: ipol
        type(address_4_sph_trans), intent(inout) :: trns_MHD
        type(legendre_trns_works), intent(inout) :: WK_leg
        type(work_for_FFTs), intent(inout) :: WK_FFTs_MHD
        type(coriolis_rlm_data), intent(inout) :: cor_rlm
        type(phys_data), intent(inout) :: rj_fld
      subroutine licv_exp(ref_temp, ref_comp, MHD_prop, sph_MHD_bc,   &
     &          sph, comms_sph, omega_sph, trans_p, ipol, WK, rj_fld)
        type(SGS_model_control_params), intent(in) :: SGS_param
        type(sph_grids), intent(in) :: sph
        type(sph_comm_tables), intent(in) :: comms_sph
        type(sph_rotation), intent(in) :: omega_sph
        type(fdm_matrices), intent(in) :: r_2nd
        type(parameters_4_sph_trans), intent(in) :: trans_p
        type(phys_address), intent(in) :: ipol
        type(works_4_sph_trans_MHD), intent(inout) :: WK
        type(phys_data), intent(inout) :: rj_fld
        type(reference_field), intent(in) :: ref_temp
        type(reference_field), intent(in) :: ref_comp
        type(MHD_evolution_param), intent(in) :: MHD_prop
        type(sph_MHD_boundary_data), intent(in) :: sph_MHD_bc
Function/Subroutine Documentation
licv_exp()
subroutine cal_nonlinear::licv_exp (type(reference_field), intent(in) ref_temp, type(reference_field), intent(in) ref_comp, type(mhd_evolution_param), intent(in) MHD_prop, type(sph_mhd_boundary_data), intent(in) sph_MHD_bc, type(sph_grids), intent(in) sph, type(sph_comm_tables), intent(in) comms_sph, type(sph_rotation), intent(in) omega_sph, type(parameters_4_sph_trans), intent(in) trans_p, type(phys_address), intent(in) ipol, type(works_4_sph_trans_mhd), intent(inout) WK, type(phys_data), intent(inout) rj_fld)
Definition at line 209 of file cal_nonlinear.f90.
References cal_nonlinear_sph_mhd::add_ref_advect_sph_mhd(), copy_nodal_fields::clear_field_data(), t_physical_property::id_no_evolution, m_machine_parameter::iflag_debug, sum_rotation_of_forces::licv_forces_to_explicit(), m_phys_constants::n_scalar, m_phys_constants::n_vector, rot_self_buoyancies_sph::sel_rot_self_buoyancy_sph(), and sph_transforms_4_mhd::sph_transform_4_licv().
nonlinear()
subroutine cal_nonlinear::nonlinear (type(fdm_matrices), intent(in) r_2nd, type(sph_mhd_model_data), intent(in) SPH_model, type(parameters_4_sph_trans), intent(in) trans_p, type(works_4_sph_trans_mhd), intent(inout) WK, type(sph_mesh_field_data), intent(inout) SPH_MHD)
Definition at line 82 of file cal_nonlinear.f90.
References cal_nonlinear_sph_mhd::add_ref_advect_sph_mhd(), cal_inner_core_rotation::copy_icore_rot_to_tor_coriolis(), m_work_time::end_elapsed_time(), t_physical_property::id_no_evolution, m_machine_parameter::iflag_debug, m_elapsed_labels_4_mhd::iflag_smhd_time, m_elapsed_labels_4_mhd::ist_elapsed_smhd, nonlinear_by_pseudo_sph(), rot_self_buoyancies_sph::sel_rot_self_buoyancy_sph(), m_work_time::start_elapsed_time(), and sum_rotation_of_forces::sum_forces_to_explicit().
Referenced by sph_analyzer_mhd::sph_analyze_mhd(), sph_analyzer_snap_w_psf::sph_analyze_snap_psf(), and sph_analyzer_mhd::sph_initialize_mhd().
nonlinear_by_pseudo_sph()
subroutine cal_nonlinear::nonlinear_by_pseudo_sph (type(sph_grids), intent(in) sph, type(sph_comm_tables), intent(in) comms_sph, type(sph_rotation), intent(in) omega_sph, type(fdm_matrices), intent(in) r_2nd, type(mhd_evolution_param), intent(in) MHD_prop, type(sph_mhd_boundary_data), intent(in) sph_MHD_bc, type(parameters_4_sph_trans), intent(in) trans_p, type(gaunt_coriolis_rlm), intent(in) gt_cor, type(address_4_sph_trans), intent(inout) trns_MHD, type(legendre_trns_works), intent(inout) WK_leg, type(work_for_ffts), intent(inout) WK_FFTs_MHD, type(coriolis_rlm_data), intent(inout) cor_rlm, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld)
Definition at line 144 of file cal_nonlinear.f90.
References m_work_time::end_elapsed_time(), m_machine_parameter::iflag_debug, m_elapsed_labels_4_mhd::iflag_smhd_time, m_elapsed_labels_4_mhd::ist_elapsed_smhd, cal_nonlinear_sph_mhd::nonlinear_terms_in_rtp(), cal_sph_field_by_rotation::rot_momentum_eq_exp_sph(), sph_transforms_4_mhd::sph_back_trans_4_mhd(), sph_transforms_4_mhd::sph_forward_trans_4_mhd(), and m_work_time::start_elapsed_time().
Referenced by nonlinear().