CALYPSO: set_control_4_press Module Reference
set_control_4_press Module Reference
set boundary conditions for pressure from control data
Functions/Subroutines
subroutine s_set_control_4_press (fl_prop, node_bc_P_ctl, surf_bc_PN_ctl, press_nod, wall_surf)
Detailed Description
set boundary conditions for pressure from control data
      subroutine s_set_control_4_press                                &
     &         (fl_prop, node_bc_P_ctl, surf_bc_PN_ctl,               &
     &          press_nod, wall_surf)
        type(fluid_property), intent(in) :: fl_prop
        type(ctl_array_c2r), intent(in) :: node_bc_P_ctl
        type(ctl_array_c2r), intent(in) :: surf_bc_PN_ctl
        type(boundary_condition_list), intent(inout) :: press_nod
        type(boundary_condition_list), intent(inout) :: wall_surf
Function/Subroutine Documentation
s_set_control_4_press()
subroutine set_control_4_press::s_set_control_4_press (type(fluid_property), intent(in) fl_prop, type(ctl_array_c2r), intent(in) node_bc_P_ctl, type(ctl_array_c2r), intent(in) surf_bc_PN_ctl, type(boundary_condition_list), intent(inout) press_nod, type(boundary_condition_list), intent(inout) wall_surf)
Definition at line 34 of file set_control_4_press.f90.
References t_bc_data_list::alloc_bc_type_ctl(), t_physical_property::id_no_evolution, m_machine_parameter::iflag_debug, m_machine_parameter::iflag_full_msg, set_node_group_types::set_bc_group_types_scalar(), set_node_group_types::set_bc_group_types_sgs_scalar(), set_surface_group_types::set_surf_group_types_scalar(), and set_surface_group_types::set_surf_wall_group_types().
Referenced by set_control_sph_mhd::set_control_sph_mhd_bcs().