CALYPSO: t_sph_local_index Module Reference
t_sph_local_index Module Reference
Data Types
type sph_local_1d_index_rj
type sph_local_1d_index_rlm
type sph_local_1d_index_rtm
type sph_local_1d_index_rtp
Functions/Subroutines
subroutine, private alloc_rtp_1d_local_idx (sph_rtp, sph_lcx_rtp)
subroutine, private alloc_rj_1d_local_idx (sph_rj, sph_lcx_rj)
subroutine, private alloc_rtm_1d_local_idx (sph_rtm, sph_lcx_rtm)
subroutine, private alloc_rlm_1d_local_idx (sph_rlm, sph_lcx_rlm)
subroutine init_local_idx_table_rtp (sph_rtp, sph_lcx_rtp)
subroutine init_local_idx_table_rtm (sph_rtm, sph_lcx_rtm)
subroutine init_local_idx_table_rlm (sph_rlm, sph_lcx_rlm)
subroutine init_local_idx_table_rj (sph_rj, sph_lcx_rj)
subroutine dealloc_rtp_1d_local_idx (sph_lcx_rtp)
subroutine dealloc_rj_1d_local_idx (sph_lcx_rj)
subroutine dealloc_rtm_1d_local_idx (sph_lcx_rtm)
subroutine dealloc_rlm_1d_local_idx (sph_lcx_rlm)
Function/Subroutine Documentation
alloc_rj_1d_local_idx()
subroutine, private t_sph_local_index::alloc_rj_1d_local_idx (type(sph_rj_grid), intent(in) sph_rj, type(sph_local_1d_index_rj), intent(inout) sph_lcx_rj) private
Definition at line 89 of file t_sph_local_index.f90.
Referenced by init_local_idx_table_rj().
alloc_rlm_1d_local_idx()
subroutine, private t_sph_local_index::alloc_rlm_1d_local_idx (type(sph_rlm_grid), intent(in) sph_rlm, type(sph_local_1d_index_rlm), intent(inout) sph_lcx_rlm) private
Definition at line 129 of file t_sph_local_index.f90.
Referenced by init_local_idx_table_rlm().
alloc_rtm_1d_local_idx()
subroutine, private t_sph_local_index::alloc_rtm_1d_local_idx (type(sph_rtm_grid), intent(in) sph_rtm, type(sph_local_1d_index_rtm), intent(inout) sph_lcx_rtm) private
Definition at line 108 of file t_sph_local_index.f90.
Referenced by init_local_idx_table_rtm().
alloc_rtp_1d_local_idx()
subroutine, private t_sph_local_index::alloc_rtp_1d_local_idx (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_local_1d_index_rtp), intent(inout) sph_lcx_rtp) private
Definition at line 67 of file t_sph_local_index.f90.
Referenced by init_local_idx_table_rtp().
dealloc_rj_1d_local_idx()
subroutine t_sph_local_index::dealloc_rj_1d_local_idx (type(sph_local_1d_index_rj), intent(inout) sph_lcx_rj)
Definition at line 268 of file t_sph_local_index.f90.
Referenced by set_comm_table_rtp_rj::set_comm_table_4_rj().
dealloc_rlm_1d_local_idx()
subroutine t_sph_local_index::dealloc_rlm_1d_local_idx (type(sph_local_1d_index_rlm), intent(inout) sph_lcx_rlm)
Definition at line 290 of file t_sph_local_index.f90.
dealloc_rtm_1d_local_idx()
subroutine t_sph_local_index::dealloc_rtm_1d_local_idx (type(sph_local_1d_index_rtm), intent(inout) sph_lcx_rtm)
Definition at line 279 of file t_sph_local_index.f90.
dealloc_rtp_1d_local_idx()
subroutine t_sph_local_index::dealloc_rtp_1d_local_idx (type(sph_local_1d_index_rtp), intent(inout) sph_lcx_rtp)
Definition at line 257 of file t_sph_local_index.f90.
Referenced by set_comm_table_rtp_rj::set_comm_table_4_rtp().
init_local_idx_table_rj()
subroutine t_sph_local_index::init_local_idx_table_rj (type(sph_rj_grid), intent(in) sph_rj, type(sph_local_1d_index_rj), intent(inout) sph_lcx_rj)
Definition at line 232 of file t_sph_local_index.f90.
References alloc_rj_1d_local_idx().
Referenced by set_comm_table_rtp_rj::set_comm_table_4_rj().
init_local_idx_table_rlm()
subroutine t_sph_local_index::init_local_idx_table_rlm (type(sph_rlm_grid), intent(in) sph_rlm, type(sph_local_1d_index_rlm), intent(inout) sph_lcx_rlm)
Definition at line 208 of file t_sph_local_index.f90.
References alloc_rlm_1d_local_idx().
init_local_idx_table_rtm()
subroutine t_sph_local_index::init_local_idx_table_rtm (type(sph_rtm_grid), intent(in) sph_rtm, type(sph_local_1d_index_rtm), intent(inout) sph_lcx_rtm)
Definition at line 179 of file t_sph_local_index.f90.
References alloc_rtm_1d_local_idx().
init_local_idx_table_rtp()
subroutine t_sph_local_index::init_local_idx_table_rtp (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_local_1d_index_rtp), intent(inout) sph_lcx_rtp)
Definition at line 150 of file t_sph_local_index.f90.
References alloc_rtp_1d_local_idx().
Referenced by set_comm_table_rtp_rj::set_comm_table_4_rtp().