CALYPSO: add_base_force_4_sph_trns Module Reference
add_base_force_4_sph_trns Module Reference
Force addresses for spherical harmonics transform in MHD dynamo simulation.
Functions/Subroutines
subroutine add_base_force_4_mhd_sph_trns (d_rj, ipol_frc, iphys_frc, f_trns_frc, trns)
subroutine add_base_force_sph_trns_snap (d_rj, ipol_frc, iphys_frc, f_trns_frc, trns)
subroutine add_rot_coriolis_mhd_sph_trns (d_rj, ipol_rot_frc, iphys_rot_frc, f_trns_rot_frc, trns)
subroutine add_div_coriolis_mhd_sph_trns (d_rj, ipol_div_frc, iphys_div_frc, f_trns_div_frc, trns)
subroutine add_base_force_fwd_trns_snap (d_rj, ipol_frc, iphys_frc, f_trns_frc, trns)
subroutine add_base_force_bwd_trns_snap (d_rj, ipol_frc, iphys_frc, b_trns_frc, trns)
subroutine add_scalar_flux_bwd_trns_snap (d_rj, ipol_frc, iphys_frc, b_trns_frc, trns)
subroutine add_rot_force_4_sph_trns_snap (d_rj, ipol_rot_frc, iphys_rot_frc, b_trns_rot_frc, trns)
subroutine add_div_force_4_sph_trns_snap (d_rj, ipol_div_frc, iphys_div_frc, b_trns_div_frc, trns)
Detailed Description
Force addresses for spherical harmonics transform in MHD dynamo simulation.
      subroutine add_base_force_4_MHD_sph_trns                        &
     &         (d_rj, ipol_frc, iphys_frc, f_trns_frc, trns)
      subroutine add_base_force_sph_trns_snap                         &
     &         (d_rj, ipol_frc, iphys_frc, f_trns_frc, trns)
        type(fluid_property), intent(in) :: fl_prop
        type(conductive_property), intent(in) :: cd_prop
        type(scalar_property), intent(in) :: ht_prop, cp_prop
        type(phys_data), intent(in) :: d_rj
        type(base_force_address), intent(in) :: ipol_frc, iphys_frc
        type(base_force_address), intent(inout) :: f_trns_frc
        type(spherical_transform_data), intent(inout) :: trns
      subroutine add_rot_coriolis_MHD_sph_trns(d_rj,                  &
     &          ipol_rot_frc, iphys_rot_frc, f_trns_rot_frc, trns)
        type(fluid_property), intent(in) :: fl_prop
        type(phys_data), intent(in) :: d_rj
        type(base_force_address), intent(in) :: ipol_rot_frc
        type(base_force_address), intent(in) :: iphys_rot_frc
        type(base_force_address), intent(inout) :: f_trns_rot_frc
        type(spherical_transform_data), intent(inout) :: trns
      subroutine add_div_coriolis_MHD_sph_trns(d_rj,                  &
     &          ipol_div_frc, iphys_div_frc, f_trns_div_frc, trns)
        type(phys_data), intent(in) :: d_rj
        type(base_force_address), intent(in) :: ipol_div_frc
        type(base_force_address), intent(in) :: iphys_div_frc
        type(base_force_address), intent(inout) :: f_trns_div_frc
        type(spherical_transform_data), intent(inout) :: trns
      subroutine add_base_force_fwd_trns_snap                         &
     &         (d_rj, ipol_frc, iphys_frc, f_trns_frc, trns)
        type(phys_data), intent(in) :: d_rj
        type(base_force_address), intent(in) :: ipol_frc, iphys_frc
        type(base_force_address), intent(inout) :: f_trns_frc
        type(spherical_transform_data), intent(inout) :: trns
      subroutine add_base_force_bwd_trns_snap                         &
     &         (d_rj, ipol_frc, iphys_frc, b_trns_frc, trns)
      subroutine add_scalar_flux_bwd_trns_snap                        &
     &         (d_rj, ipol_frc, iphys_frc, b_trns_frc, trns)
        type(phys_data), intent(in) :: d_rj
        type(base_force_address), intent(in) :: ipol_frc, iphys_frc
        type(base_force_address), intent(inout) :: b_trns_frc
        type(spherical_transform_data), intent(inout) :: trns
      subroutine add_rot_force_4_sph_trns_snap(d_rj,                  &
     &          ipol_rot_frc, iphys_rot_frc, b_trns_rot_frc, trns)
        type(phys_data), intent(in) :: d_rj
        type(base_force_address), intent(in) :: ipol_rot_frc
        type(base_force_address), intent(in) :: iphys_rot_frc
        type(base_force_address), intent(inout) :: b_trns_rot_frc
        type(spherical_transform_data), intent(inout) :: trns
      subroutine add_div_force_4_sph_trns_snap(d_rj,                  &
     &          ipol_div_frc, iphys_div_frc, b_trns_div_frc, trns)
        type(phys_data), intent(in) :: d_rj
        type(base_force_address), intent(in) :: ipol_div_frc
        type(base_force_address), intent(in) :: iphys_div_frc
        type(base_force_address), intent(inout) :: b_trns_div_frc
        type(spherical_transform_data), intent(inout) :: trns
Function/Subroutine Documentation
add_base_force_4_mhd_sph_trns()
subroutine add_base_force_4_sph_trns::add_base_force_4_mhd_sph_trns (type(phys_data), intent(in) d_rj, type(base_force_address), intent(in) ipol_frc, type(base_force_address), intent(in) iphys_frc, type(base_force_address), intent(inout) f_trns_frc, type(spherical_transform_data), intent(inout) trns)
Definition at line 87 of file add_base_force_4_sph_trns.f90.
References add_field_to_sph_trans_list::add_field_4_sph_trns_by_pol().
Referenced by address_sph_trans_mhd::fwd_trans_address_mhd().
add_base_force_bwd_trns_snap()
subroutine add_base_force_4_sph_trns::add_base_force_bwd_trns_snap (type(phys_data), intent(in) d_rj, type(base_force_address), intent(in) ipol_frc, type(base_force_address), intent(in) iphys_frc, type(base_force_address), intent(inout) b_trns_frc, type(spherical_transform_data), intent(inout) trns)
Definition at line 245 of file add_base_force_4_sph_trns.f90.
References add_field_to_sph_trans_list::add_field_name_4_sph_trns_snap().
Referenced by address_sph_trans_snap::bwd_trans_address_ene_flux().
add_base_force_fwd_trns_snap()
subroutine add_base_force_4_sph_trns::add_base_force_fwd_trns_snap (type(phys_data), intent(in) d_rj, type(base_force_address), intent(in) ipol_frc, type(base_force_address), intent(in) iphys_frc, type(base_force_address), intent(inout) f_trns_frc, type(spherical_transform_data), intent(inout) trns)
Definition at line 222 of file add_base_force_4_sph_trns.f90.
References add_field_to_sph_trans_list::add_field_name_4_sph_trns_snap().
Referenced by address_sph_trans_snap::fwd_trans_address_ene_flux().
add_base_force_sph_trns_snap()
subroutine add_base_force_4_sph_trns::add_base_force_sph_trns_snap (type(phys_data), intent(in) d_rj, type(base_force_address), intent(in) ipol_frc, type(base_force_address), intent(in) iphys_frc, type(base_force_address), intent(inout) f_trns_frc, type(spherical_transform_data), intent(inout) trns)
Definition at line 151 of file add_base_force_4_sph_trns.f90.
References add_field_to_sph_trans_list::add_field_4_sph_trns_by_pol().
Referenced by address_sph_trans_snap::fwd_trans_address_snap().
add_div_coriolis_mhd_sph_trns()
subroutine add_base_force_4_sph_trns::add_div_coriolis_mhd_sph_trns (type(phys_data), intent(in) d_rj, type(base_force_address), intent(in) ipol_div_frc, type(base_force_address), intent(in) iphys_div_frc, type(base_force_address), intent(inout) f_trns_div_frc, type(spherical_transform_data), intent(inout) trns)
Definition at line 201 of file add_base_force_4_sph_trns.f90.
References add_field_to_sph_trans_list::add_field_4_sph_trns_by_pol().
Referenced by address_sph_trans_mhd::fwd_trans_address_mhd(), and address_sph_trans_snap::fwd_trans_address_snap().
add_div_force_4_sph_trns_snap()
subroutine add_base_force_4_sph_trns::add_div_force_4_sph_trns_snap (type(phys_data), intent(in) d_rj, type(base_force_address), intent(in) ipol_div_frc, type(base_force_address), intent(in) iphys_div_frc, type(base_force_address), intent(inout) b_trns_div_frc, type(spherical_transform_data), intent(inout) trns)
Definition at line 331 of file add_base_force_4_sph_trns.f90.
References add_field_to_sph_trans_list::add_field_name_4_sph_trns_snap().
Referenced by address_sph_trans_snap::bwd_trans_address_ene_flux().
add_rot_coriolis_mhd_sph_trns()
subroutine add_base_force_4_sph_trns::add_rot_coriolis_mhd_sph_trns (type(phys_data), intent(in) d_rj, type(base_force_address), intent(in) ipol_rot_frc, type(base_force_address), intent(in) iphys_rot_frc, type(base_force_address), intent(inout) f_trns_rot_frc, type(spherical_transform_data), intent(inout) trns)
Definition at line 175 of file add_base_force_4_sph_trns.f90.
References add_field_to_sph_trans_list::add_field_4_sph_trns_by_pol().
Referenced by address_sph_trans_mhd::fwd_trans_address_mhd().
add_rot_force_4_sph_trns_snap()
subroutine add_base_force_4_sph_trns::add_rot_force_4_sph_trns_snap (type(phys_data), intent(in) d_rj, type(base_force_address), intent(in) ipol_rot_frc, type(base_force_address), intent(in) iphys_rot_frc, type(base_force_address), intent(inout) b_trns_rot_frc, type(spherical_transform_data), intent(inout) trns)
Definition at line 298 of file add_base_force_4_sph_trns.f90.
References add_field_to_sph_trans_list::add_field_name_4_sph_trns_snap().
Referenced by address_sph_trans_snap::bwd_trans_address_ene_flux().
add_scalar_flux_bwd_trns_snap()
subroutine add_base_force_4_sph_trns::add_scalar_flux_bwd_trns_snap (type(phys_data), intent(in) d_rj, type(base_force_address), intent(in) ipol_frc, type(base_force_address), intent(in) iphys_frc, type(base_force_address), intent(inout) b_trns_frc, type(spherical_transform_data), intent(inout) trns)
Definition at line 275 of file add_base_force_4_sph_trns.f90.
References add_field_to_sph_trans_list::add_field_name_4_sph_trns_snap().
Referenced by address_sph_trans_snap::bwd_trans_address_ene_flux().