CALYPSO: gz_mesh_file_io_b Module Reference
gz_mesh_file_io_b Module Reference
gzipped binary mesh file IO routines
Functions/Subroutines
subroutine gz_read_mesh_file_b (id_rank, file_name, mesh_IO, group_IO, ierr)
subroutine gz_read_mesh_geometry_b (id_rank, file_name, mesh_IO, ierr)
subroutine gz_read_node_size_b (id_rank, file_name, mesh_IO, ierr)
subroutine gz_read_geometry_size_b (id_rank, file_name, mesh_IO, ierr)
subroutine gz_write_mesh_file_b (id_rank, file_name, mesh_IO, group_IO)
Variables
type(buffer_4_gzip), private zbuf_mesh
Detailed Description
gzipped binary mesh file IO routines
      subroutine gz_read_mesh_file_b                                  &
     &         (id_rank, file_name, mesh_IO, group_IO, ierr)
        type(mesh_geometry), intent(inout) :: mesh_IO
        type(mesh_groups), intent(inout) ::   group_IO
      subroutine gz_read_mesh_geometry_b                              &
     &         (id_rank, file_name, mesh_IO, ierr)
      subroutine gz_read_node_size_b                                  &
     &         (id_rank, file_name, mesh_IO, ierr)
      subroutine gz_read_geometry_size_b                              &
     &         (id_rank, file_name, mesh_IO, ierr)
        type(mesh_geometry), intent(inout) :: mesh_IO
      subroutine gz_write_mesh_file_b                                 &
     &         (id_rank, file_name, mesh_IO, group_IO)
        type(mesh_geometry), intent(in) :: mesh_IO
        type(mesh_groups), intent(in) ::   group_IO
Function/Subroutine Documentation
gz_read_geometry_size_b()
subroutine gz_mesh_file_io_b::gz_read_geometry_size_b (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(inout) mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 142 of file gz_mesh_file_IO_b.f90.
References gzip_file_access::close_gzfile_b(), gz_mesh_data_io_b::gz_read_num_node_ele_b(), m_machine_parameter::i_debug, gz_binary_io::open_rd_gzfile_b(), and zbuf_mesh.
Referenced by mesh_io_select::sel_read_geometry_size().
gz_read_mesh_file_b()
subroutine gz_mesh_file_io_b::gz_read_mesh_file_b (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(inout) mesh_IO, type(mesh_groups), intent(inout) group_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 55 of file gz_mesh_file_IO_b.f90.
References gzip_file_access::close_gzfile_b(), gz_mesh_data_io_b::gz_read_geometry_data_b(), gz_mesh_data_io_b::gz_read_mesh_groups_b(), m_machine_parameter::i_debug, gz_binary_io::open_rd_gzfile_b(), and zbuf_mesh.
Referenced by mesh_io_select::sel_read_mesh().
gz_read_mesh_geometry_b()
subroutine gz_mesh_file_io_b::gz_read_mesh_geometry_b (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(inout) mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 86 of file gz_mesh_file_IO_b.f90.
References gzip_file_access::close_gzfile_b(), gz_mesh_data_io_b::gz_read_geometry_data_b(), m_machine_parameter::i_debug, gz_binary_io::open_rd_gzfile_b(), and zbuf_mesh.
Referenced by mesh_io_select::sel_read_mesh_geometry().
gz_read_node_size_b()
subroutine gz_mesh_file_io_b::gz_read_node_size_b (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(inout) mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 114 of file gz_mesh_file_IO_b.f90.
References gzip_file_access::close_gzfile_b(), gz_mesh_data_io_b::gz_read_num_node_b(), m_machine_parameter::i_debug, gz_binary_io::open_rd_gzfile_b(), and zbuf_mesh.
Referenced by mesh_io_select::sel_read_node_size().
gz_write_mesh_file_b()
subroutine gz_mesh_file_io_b::gz_write_mesh_file_b (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(in) mesh_IO, type(mesh_groups), intent(in) group_IO)
Definition at line 171 of file gz_mesh_file_IO_b.f90.
References gzip_file_access::close_gzfile_b(), gz_mesh_data_io_b::gz_write_geometry_data_b(), gz_mesh_data_io_b::gz_write_mesh_groups_b(), m_machine_parameter::i_debug, gz_binary_io::open_wt_gzfile_b(), and zbuf_mesh.
Referenced by mesh_io_select::sel_write_mesh_file().
Variable Documentation
zbuf_mesh
type(buffer_4_gzip), private gz_mesh_file_io_b::zbuf_mesh private
Definition at line 47 of file gz_mesh_file_IO_b.f90.
Referenced by gz_read_geometry_size_b(), gz_read_mesh_file_b(), gz_read_mesh_geometry_b(), gz_read_node_size_b(), and gz_write_mesh_file_b().