CALYPSO: t_ctl_data_4_sph_monitor Module Reference
t_ctl_data_4_sph_monitor Module Reference
Data Types
type sph_monitor_control
Functions/Subroutines
subroutine read_sph_monitoring_ctl (id_control, hd_block, smonitor_ctl, c_buf)
subroutine, private read_volume_spectr_ctl (id_control, hd_block, smonitor_ctl, c_buf)
subroutine dealloc_sph_monitoring_ctl (smonitor_ctl)
subroutine, private append_volume_spectr_ctls (add_vpwr, smonitor_ctl)
subroutine, private alloc_volume_spectr_control (smonitor_ctl)
subroutine, private dealloc_volume_spectr_control (smonitor_ctl)
Variables
character(len=kchara), parameter, private hd_vol_spec_block = 'volume_spectrum_ctl'
character(len=kchara), parameter, private hd_layer_spec_block = 'layered_spectrum_ctl'
character(len=kchara), parameter, private hd_gauss_spec_block = 'gauss_coefficient_ctl'
character(len=kchara), parameter, private hd_pick_sph_ctl = 'pickup_spectr_ctl'
character(len=kchara), parameter, private hd_mid_eq_monitor_ctl = 'mid_equator_monitor_ctl'
integer(kind=kint), private i_layer_spectr_ctl = 0
integer(kind=kint), private i_gauss_pwr_ctl = 0
integer(kind=kint), private i_pick_sph_ctl = 0
integer(kind=kint), private i_mid_eq_monitor_ctl = 0
character(len=kchara), parameter, private hd_voume_ave_head = 'volume_average_prefix'
character(len=kchara), parameter, private hd_voume_rms_head = 'volume_pwr_spectr_prefix'
character(len=kchara), parameter, private hd_nusselt_file_head = 'nusselt_number_prefix'
Function/Subroutine Documentation
alloc_volume_spectr_control()
subroutine, private t_ctl_data_4_sph_monitor::alloc_volume_spectr_control (type(sph_monitor_control), intent(inout) smonitor_ctl) private
Definition at line 277 of file t_ctl_data_4_sph_monitor.f90.
Referenced by append_volume_spectr_ctls(), and read_volume_spectr_ctl().
append_volume_spectr_ctls()
subroutine, private t_ctl_data_4_sph_monitor::append_volume_spectr_ctls (type(volume_spectr_control), intent(inout) add_vpwr, type(sph_monitor_control), intent(inout) smonitor_ctl) private
Definition at line 246 of file t_ctl_data_4_sph_monitor.f90.
References alloc_volume_spectr_control(), t_ctl_data_sph_vol_spectr::copy_volume_spectr_control(), t_ctl_data_sph_vol_spectr::copy_volume_spectr_ctls(), dealloc_volume_spectr_control(), and t_ctl_data_sph_vol_spectr::reset_volume_spectr_control().
Referenced by read_volume_spectr_ctl().
dealloc_sph_monitoring_ctl()
subroutine t_ctl_data_4_sph_monitor::dealloc_sph_monitoring_ctl (type(sph_monitor_control), intent(inout) smonitor_ctl)
Definition at line 216 of file t_ctl_data_4_sph_monitor.f90.
References t_ctl_data_pick_sph_spectr::dealloc_gauss_spectr_control(), t_ctl_data_sph_vol_spectr::dealloc_num_spec_layer_ctl(), t_ctl_data_pick_sph_spectr::dealloc_pick_spectr_control(), dealloc_volume_spectr_control(), t_mid_equator_control::reset_mid_equator_control(), and t_ctl_data_sph_vol_spectr::reset_volume_spectr_control().
Referenced by t_ctl_data_mhd::dealloc_sph_mhd_ctl_data().
dealloc_volume_spectr_control()
subroutine, private t_ctl_data_4_sph_monitor::dealloc_volume_spectr_control (type(sph_monitor_control), intent(inout) smonitor_ctl) private
Definition at line 287 of file t_ctl_data_4_sph_monitor.f90.
Referenced by append_volume_spectr_ctls(), and dealloc_sph_monitoring_ctl().
read_sph_monitoring_ctl()
subroutine t_ctl_data_4_sph_monitor::read_sph_monitoring_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(sph_monitor_control), intent(inout) smonitor_ctl, type(buffer_for_control), intent(inout) c_buf)
Definition at line 136 of file t_ctl_data_4_sph_monitor.f90.
References t_read_control_elements::check_array_flag(), t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_gauss_spec_block, hd_layer_spec_block, hd_mid_eq_monitor_ctl, hd_nusselt_file_head, hd_pick_sph_ctl, hd_vol_spec_block, hd_voume_ave_head, hd_voume_rms_head, i_gauss_pwr_ctl, i_layer_spectr_ctl, i_mid_eq_monitor_ctl, i_pick_sph_ctl, t_read_control_elements::load_one_line_from_control(), t_control_array_character::read_chara_ctl_type(), t_ctl_data_pick_sph_spectr::read_gauss_spectr_ctl(), t_ctl_data_sph_vol_spectr::read_layerd_spectr_ctl(), t_mid_equator_control::read_mid_eq_monitor_ctl(), t_ctl_data_pick_sph_spectr::read_pickup_spectr_ctl(), and read_volume_spectr_ctl().
Referenced by t_ctl_data_mhd::read_sph_mhd_ctl_noviz(), and t_ctl_data_mhd::read_sph_mhd_ctl_w_psf().
read_volume_spectr_ctl()
subroutine, private t_ctl_data_4_sph_monitor::read_volume_spectr_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(sph_monitor_control), intent(inout) smonitor_ctl, type(buffer_for_control), intent(inout) c_buf) private
Definition at line 183 of file t_ctl_data_4_sph_monitor.f90.
References alloc_volume_spectr_control(), append_volume_spectr_ctls(), t_read_control_elements::check_end_array_flag(), t_read_control_elements::load_one_line_from_control(), and t_ctl_data_sph_vol_spectr::read_each_vol_spectr_ctl().
Referenced by read_sph_monitoring_ctl().
Variable Documentation
hd_gauss_spec_block
character(len=kchara), parameter, private t_ctl_data_4_sph_monitor::hd_gauss_spec_block = 'gauss_coefficient_ctl' private
Definition at line 96 of file t_ctl_data_4_sph_monitor.f90.
Referenced by read_sph_monitoring_ctl().
hd_layer_spec_block
character(len=kchara), parameter, private t_ctl_data_4_sph_monitor::hd_layer_spec_block = 'layered_spectrum_ctl' private
Definition at line 94 of file t_ctl_data_4_sph_monitor.f90.
Referenced by read_sph_monitoring_ctl().
hd_mid_eq_monitor_ctl
character(len=kchara), parameter, private t_ctl_data_4_sph_monitor::hd_mid_eq_monitor_ctl = 'mid_equator_monitor_ctl' private
Definition at line 100 of file t_ctl_data_4_sph_monitor.f90.
Referenced by read_sph_monitoring_ctl().
hd_nusselt_file_head
character(len=kchara), parameter, private t_ctl_data_4_sph_monitor::hd_nusselt_file_head = 'nusselt_number_prefix' private
Definition at line 113 of file t_ctl_data_4_sph_monitor.f90.
Referenced by read_sph_monitoring_ctl().
hd_pick_sph_ctl
character(len=kchara), parameter, private t_ctl_data_4_sph_monitor::hd_pick_sph_ctl = 'pickup_spectr_ctl' private
Definition at line 98 of file t_ctl_data_4_sph_monitor.f90.
Referenced by read_sph_monitoring_ctl().
hd_vol_spec_block
character(len=kchara), parameter, private t_ctl_data_4_sph_monitor::hd_vol_spec_block = 'volume_spectrum_ctl' private
Definition at line 92 of file t_ctl_data_4_sph_monitor.f90.
Referenced by read_sph_monitoring_ctl().
hd_voume_ave_head
character(len=kchara), parameter, private t_ctl_data_4_sph_monitor::hd_voume_ave_head = 'volume_average_prefix' private
Definition at line 109 of file t_ctl_data_4_sph_monitor.f90.
Referenced by read_sph_monitoring_ctl().
hd_voume_rms_head
character(len=kchara), parameter, private t_ctl_data_4_sph_monitor::hd_voume_rms_head = 'volume_pwr_spectr_prefix' private
Definition at line 111 of file t_ctl_data_4_sph_monitor.f90.
Referenced by read_sph_monitoring_ctl().
i_gauss_pwr_ctl
integer(kind = kint), private t_ctl_data_4_sph_monitor::i_gauss_pwr_ctl = 0 private
Definition at line 103 of file t_ctl_data_4_sph_monitor.f90.
Referenced by read_sph_monitoring_ctl().
i_layer_spectr_ctl
integer(kind = kint), private t_ctl_data_4_sph_monitor::i_layer_spectr_ctl = 0 private
Definition at line 102 of file t_ctl_data_4_sph_monitor.f90.
Referenced by read_sph_monitoring_ctl().
i_mid_eq_monitor_ctl
integer(kind = kint), private t_ctl_data_4_sph_monitor::i_mid_eq_monitor_ctl = 0 private
Definition at line 105 of file t_ctl_data_4_sph_monitor.f90.
Referenced by read_sph_monitoring_ctl().
i_pick_sph_ctl
integer(kind = kint), private t_ctl_data_4_sph_monitor::i_pick_sph_ctl = 0 private
Definition at line 104 of file t_ctl_data_4_sph_monitor.f90.
Referenced by read_sph_monitoring_ctl().