CALYPSO: t_flex_delta_t_parameter Module Reference
t_flex_delta_t_parameter Module Reference
Parameteres for flexible time steppings.
Data Types
type flexible_stepping_parameter
Functions/Subroutines
subroutine set_flex_time_step_params (tctl, flex_p, init_d, finish_d, rst_step)
subroutine set_control_flex_time_steps (tctl, init_d, flex_p)
Variables
integer(kind=kint), parameter iflag_fixed_step = 0
Fixed time step flag.
integer(kind=kint), parameter iflag_flex_step = 1
Flexible time step flag.
Detailed Description
Parameteres for flexible time steppings.
Function/Subroutine Documentation
set_control_flex_time_steps()
subroutine t_flex_delta_t_parameter::set_control_flex_time_steps (type(time_data_control), intent(in) tctl, type(time_data), intent(in) init_d, type(flexible_stepping_parameter), intent(inout) flex_p)
Definition at line 139 of file t_flex_delta_t_parameter.f90.
References cal_num_digits::cal_num_digit_real(), calypso_mpi::calypso_mpi_abort(), m_error_ids::ierr_evo, iflag_flex_step, m_constants::ione, m_constants::izero, and m_constants::zero.
Referenced by t_mhd_step_parameter::s_set_control_4_time_steps().
set_flex_time_step_params()
subroutine t_flex_delta_t_parameter::set_flex_time_step_params (type(time_data_control), intent(in) tctl, type(flexible_stepping_parameter), intent(inout) flex_p, type(time_data), intent(inout) init_d, type(finish_data), intent(inout) finish_d, type(io_step_param), intent(inout) rst_step)
Start step for restarting file
Definition at line 85 of file t_flex_delta_t_parameter.f90.
References calypso_mpi::calypso_mpi_abort(), m_error_ids::ierr_evo, m_constants::ione, and t_io_step_parameter::output_step_4_flex_step_ctl().
Referenced by t_mhd_step_parameter::set_flex_time_step_controls().
Variable Documentation
iflag_fixed_step
integer(kind=kint), parameter t_flex_delta_t_parameter::iflag_fixed_step = 0
Fixed time step flag.
Definition at line 38 of file t_flex_delta_t_parameter.f90.
Referenced by t_mhd_step_parameter::s_set_control_4_time_steps().
iflag_flex_step
integer(kind=kint), parameter t_flex_delta_t_parameter::iflag_flex_step = 1
Flexible time step flag.
Definition at line 40 of file t_flex_delta_t_parameter.f90.
Referenced by output_viz_file_control::iflag_viz_output(), output_viz_file_control::mhd_viz_routine_flag(), output_viz_file_control::mhd_viz_routine_step(), t_mhd_step_parameter::s_set_control_4_time_steps(), set_control_flex_time_steps(), and output_viz_file_control::viz_time_step().