CALYPSO: m_field_file_format_labels Module Reference
m_field_file_format_labels Module Reference
Integer flags for field data file format.
Functions/Subroutines
subroutine init_field_type_flags ()
subroutine dealloc_field_type_flags ()
Variables
character(len=kchara), dimension(1), parameter ucd_name = (/'UCD'/)
flag for UCD
character(len=kchara), dimension(1), parameter udt_name = (/'UDT'/)
flag for Splitted UCD
character(len=kchara), dimension(1), parameter vtk_name = (/'VTK'/)
flag for VTK
character(len=kchara), dimension(1), parameter vtd_name = (/'VTD'/)
flag for Splitted VTK
character(len=kchara), dimension(1), parameter iso_name = (/'ISO'/)
flag for binary data for Isosurfacing
character(len=kchara), dimension(1), parameter psf_name = (/'PSF'/)
flag for binary data for Sectioning
character(len=kchara), dimension(2), parameter field_flg = (/'field ', 'fld '/)
flag parts for field data
type(multi_flag_labels), save field_labels
flag parts for field data format 'field', 'fld '
type(multi_flag_labels), save field_ascii_labels
flag parts for field data format 'field', 'fld', 'ascii', 'text', 'field_ascii', 'field_text', 'fld_ascii', 'fld_text', 'ascii_field', 'ascii_fld', 'text_field', 'text_fld'
type(multi_flag_labels), save field_bin_labels
flag parts for field data format 'field', 'fld', 'ascii', 'text', 'field_ascii', 'field_text', 'fld_ascii', 'fld_text', 'ascii_field', 'ascii_fld', 'text_field', 'text_fld'
type(multi_flag_labels), save ucd_flags
flag parts for field data format 'field', 'fld', 'ascii', 'text', 'field_ascii', 'field_text', 'fld_ascii', 'fld_text', 'ascii_field', 'ascii_fld', 'text_field', 'text_fld'
type(multi_flag_labels), save udt_flags
Character lables for splitted UCD mesh and data 'UDT'.
type(multi_flag_labels), save vtk_flags
Character lables for VTK 'VTK'.
type(multi_flag_labels), save vtd_flags
Character lables for splitted VTK mesh and data 'VTD'.
type(multi_flag_labels), save iso_flags
Character lables for isosurface binary 'ISO'.
type(multi_flag_labels), save psf_flags
Character lables for sections binary 'PSF'.
type(multi_flag_labels), save field_gz_labels
flag parts for gzipped field data format 'gzip', 'gz', 'field_gzip', 'field_gz', 'fld_gzip', 'fld_gz', 'gzip_field', 'gzip_fld', 'gz_field', 'gz_fld'
type(multi_flag_labels), save fbin_gz_labels
flag parts for gzipped field data format
type(multi_flag_labels), save ucd_gz_flags
Character lables for gzipped UCD 'UCD_gzip', 'UCD_gz', 'gzip_UCD', 'gz_UCD'.
type(multi_flag_labels), save udt_gz_flags
Character lables for gzipped splitted UCD 'UDT_gzip', 'UDT_gz', 'gzip_UDT', 'gz_UDT'.
type(multi_flag_labels), save vtk_gz_flags
Character lables for gzipped VTK 'VTK_gzip', 'VTK_gz', 'gzip_VTK', 'gz_VTK'.
type(multi_flag_labels), save vtd_gz_flags
Character lables for gzipped splitted VTK 'VTD_gzip', 'VTD_gz', 'gzip_VTD', 'gz_VTD'.
type(multi_flag_labels), save iso_gz_flags
Character lables for gzipped isosurface binary 'ISO_gzip', 'ISO_gz', 'gzip_ISO', 'gz_ISO'.
type(multi_flag_labels), save psf_gz_flags
Character lables for gzipped sections binary 'PSF_gzip', 'PSF_gz', 'gzip_PSF', 'gz_PSF'.
Detailed Description
Integer flags for field data file format.
      subroutine init_field_type_flags()
      subroutine dealloc_field_type_flags()
 ------------------------------------------------------------------
   flag lists for field data
  Distributed data file
   ASCII   data file
     UCD file:                ucd
     splitted UCD file:       udt
     VTK file:                vtk
     splitted VTK file:       vtd
     Binary file:             iso
     splitted Binary file:    psf
   GZIPPED data file
     UCD file:             ucd_gzip
     splitted UCD file:    udt_gzip
     VTK file:             vtk_gzip
     splitted VTK file:    vtd_gzip
     Binary file:          iso_gzip
     splitted Binary file: psf_gzip
 ------------------------------------------------------------------
Function/Subroutine Documentation
dealloc_field_type_flags()
subroutine m_field_file_format_labels::dealloc_field_type_flags
Definition at line 190 of file m_field_file_format_labels.f90.
References m_file_format_labels::dealloc_file_format_flags(), t_multi_flag_labels::dealloc_multi_flags(), fbin_gz_labels, field_ascii_labels, field_bin_labels, field_gz_labels, field_labels, iso_flags, iso_gz_flags, psf_flags, psf_gz_flags, ucd_flags, ucd_gz_flags, udt_flags, udt_gz_flags, vtd_flags, vtd_gz_flags, vtk_flags, and vtk_gz_flags.
Referenced by m_merged_field_fmt_labels::dealloc_mgd_field_type_flags().
init_field_type_flags()
subroutine m_field_file_format_labels::init_field_type_flags
Definition at line 141 of file m_field_file_format_labels.f90.
References t_multi_flag_labels::append_multi_flag_labels(), m_file_format_labels::ascii_flags, m_file_format_labels::binary_flags, fbin_gz_labels, field_ascii_labels, field_bin_labels, field_flg, field_gz_labels, field_labels, m_file_format_labels::gzip_bin_flags, m_file_format_labels::gzip_flags, m_file_format_labels::init_file_format_flags(), t_multi_flag_labels::init_from_two_kinds_flags(), t_multi_flag_labels::init_multi_flags_by_labels(), m_constants::ione, iso_flags, iso_gz_flags, iso_name, m_constants::itwo, psf_flags, psf_gz_flags, psf_name, ucd_flags, ucd_gz_flags, ucd_name, udt_flags, udt_gz_flags, udt_name, vtd_flags, vtd_gz_flags, vtd_name, vtk_flags, vtk_gz_flags, and vtk_name.
Referenced by m_merged_field_fmt_labels::init_mgd_field_type_flags().
Variable Documentation
fbin_gz_labels
type(multi_flag_labels), save m_field_file_format_labels::fbin_gz_labels
flag parts for gzipped field data format
Definition at line 109 of file m_field_file_format_labels.f90.
Referenced by m_field_file_format::choose_ucd_file_format(), dealloc_field_type_flags(), init_field_type_flags(), and m_merged_field_fmt_labels::init_mgd_field_type_flags().
field_ascii_labels
type(multi_flag_labels), save m_field_file_format_labels::field_ascii_labels
flag parts for field data format 'field', 'fld', 'ascii', 'text', 'field_ascii', 'field_text', 'fld_ascii', 'fld_text', 'ascii_field', 'ascii_fld', 'text_field', 'text_fld'
Definition at line 74 of file m_field_file_format_labels.f90.
Referenced by m_field_file_format::choose_ucd_file_format(), dealloc_field_type_flags(), init_field_type_flags(), and m_merged_field_fmt_labels::init_mgd_field_type_flags().
field_bin_labels
type(multi_flag_labels), save m_field_file_format_labels::field_bin_labels
flag parts for field data format 'field', 'fld', 'ascii', 'text', 'field_ascii', 'field_text', 'fld_ascii', 'fld_text', 'ascii_field', 'ascii_fld', 'text_field', 'text_fld'
Definition at line 79 of file m_field_file_format_labels.f90.
Referenced by m_field_file_format::choose_ucd_file_format(), dealloc_field_type_flags(), init_field_type_flags(), and m_merged_field_fmt_labels::init_mgd_field_type_flags().
field_flg
character(len = kchara), dimension(2), parameter m_field_file_format_labels::field_flg = (/'field ', 'fld '/)
flag parts for field data
Definition at line 62 of file m_field_file_format_labels.f90.
Referenced by init_field_type_flags().
field_gz_labels
type(multi_flag_labels), save m_field_file_format_labels::field_gz_labels
flag parts for gzipped field data format 'gzip', 'gz', 'field_gzip', 'field_gz', 'fld_gzip', 'fld_gz', 'gzip_field', 'gzip_fld', 'gz_field', 'gz_fld'
Definition at line 107 of file m_field_file_format_labels.f90.
Referenced by m_field_file_format::choose_ucd_file_format(), dealloc_field_type_flags(), init_field_type_flags(), and m_merged_field_fmt_labels::init_mgd_field_type_flags().
field_labels
type(multi_flag_labels), save m_field_file_format_labels::field_labels
flag parts for field data format 'field', 'fld '
Definition at line 68 of file m_field_file_format_labels.f90.
Referenced by dealloc_field_type_flags(), and init_field_type_flags().
iso_flags
type(multi_flag_labels), save m_field_file_format_labels::iso_flags
Character lables for isosurface binary 'ISO'.
Definition at line 99 of file m_field_file_format_labels.f90.
Referenced by dealloc_field_type_flags(), init_field_type_flags(), and m_merged_field_fmt_labels::init_mgd_field_type_flags().
iso_gz_flags
type(multi_flag_labels), save m_field_file_format_labels::iso_gz_flags
Character lables for gzipped isosurface binary 'ISO_gzip', 'ISO_gz', 'gzip_ISO', 'gz_ISO'.
Definition at line 129 of file m_field_file_format_labels.f90.
Referenced by dealloc_field_type_flags(), and init_field_type_flags().
iso_name
character(len = kchara), dimension(1), parameter m_field_file_format_labels::iso_name = (/'ISO'/)
flag for binary data for Isosurfacing
Definition at line 57 of file m_field_file_format_labels.f90.
Referenced by init_field_type_flags().
psf_flags
type(multi_flag_labels), save m_field_file_format_labels::psf_flags
Character lables for sections binary 'PSF'.
Definition at line 102 of file m_field_file_format_labels.f90.
Referenced by dealloc_field_type_flags(), init_field_type_flags(), and m_merged_field_fmt_labels::init_mgd_field_type_flags().
psf_gz_flags
type(multi_flag_labels), save m_field_file_format_labels::psf_gz_flags
Character lables for gzipped sections binary 'PSF_gzip', 'PSF_gz', 'gzip_PSF', 'gz_PSF'.
Definition at line 133 of file m_field_file_format_labels.f90.
Referenced by dealloc_field_type_flags(), and init_field_type_flags().
psf_name
character(len = kchara), dimension(1), parameter m_field_file_format_labels::psf_name = (/'PSF'/)
flag for binary data for Sectioning
Definition at line 59 of file m_field_file_format_labels.f90.
Referenced by init_field_type_flags().
ucd_flags
type(multi_flag_labels), save m_field_file_format_labels::ucd_flags
flag parts for field data format 'field', 'fld', 'ascii', 'text', 'field_ascii', 'field_text', 'fld_ascii', 'fld_text', 'ascii_field', 'ascii_fld', 'text_field', 'text_fld'
Character lables for UCD 'UCD'
Definition at line 87 of file m_field_file_format_labels.f90.
Referenced by m_field_file_format::choose_ucd_file_format(), dealloc_field_type_flags(), init_field_type_flags(), and m_merged_field_fmt_labels::init_mgd_field_type_flags().
ucd_gz_flags
type(multi_flag_labels), save m_field_file_format_labels::ucd_gz_flags
Character lables for gzipped UCD 'UCD_gzip', 'UCD_gz', 'gzip_UCD', 'gz_UCD'.
Definition at line 113 of file m_field_file_format_labels.f90.
Referenced by m_field_file_format::choose_ucd_file_format(), dealloc_field_type_flags(), and init_field_type_flags().
ucd_name
character(len = kchara), dimension(1), parameter m_field_file_format_labels::ucd_name = (/'UCD'/)
flag for UCD
Definition at line 49 of file m_field_file_format_labels.f90.
Referenced by init_field_type_flags().
udt_flags
type(multi_flag_labels), save m_field_file_format_labels::udt_flags
Character lables for splitted UCD mesh and data 'UDT'.
Definition at line 90 of file m_field_file_format_labels.f90.
Referenced by m_field_file_format::choose_ucd_file_format(), dealloc_field_type_flags(), init_field_type_flags(), and m_merged_field_fmt_labels::init_mgd_field_type_flags().
udt_gz_flags
type(multi_flag_labels), save m_field_file_format_labels::udt_gz_flags
Character lables for gzipped splitted UCD 'UDT_gzip', 'UDT_gz', 'gzip_UDT', 'gz_UDT'.
Definition at line 117 of file m_field_file_format_labels.f90.
Referenced by m_field_file_format::choose_ucd_file_format(), dealloc_field_type_flags(), and init_field_type_flags().
udt_name
character(len = kchara), dimension(1), parameter m_field_file_format_labels::udt_name = (/'UDT'/)
flag for Splitted UCD
Definition at line 51 of file m_field_file_format_labels.f90.
Referenced by init_field_type_flags().
vtd_flags
type(multi_flag_labels), save m_field_file_format_labels::vtd_flags
Character lables for splitted VTK mesh and data 'VTD'.
Definition at line 96 of file m_field_file_format_labels.f90.
Referenced by m_field_file_format::choose_ucd_file_format(), dealloc_field_type_flags(), init_field_type_flags(), and m_merged_field_fmt_labels::init_mgd_field_type_flags().
vtd_gz_flags
type(multi_flag_labels), save m_field_file_format_labels::vtd_gz_flags
Character lables for gzipped splitted VTK 'VTD_gzip', 'VTD_gz', 'gzip_VTD', 'gz_VTD'.
Definition at line 125 of file m_field_file_format_labels.f90.
Referenced by m_field_file_format::choose_ucd_file_format(), dealloc_field_type_flags(), and init_field_type_flags().
vtd_name
character(len = kchara), dimension(1), parameter m_field_file_format_labels::vtd_name = (/'VTD'/)
flag for Splitted VTK
Definition at line 55 of file m_field_file_format_labels.f90.
Referenced by init_field_type_flags().
vtk_flags
type(multi_flag_labels), save m_field_file_format_labels::vtk_flags
Character lables for VTK 'VTK'.
Definition at line 93 of file m_field_file_format_labels.f90.
Referenced by m_field_file_format::choose_ucd_file_format(), dealloc_field_type_flags(), init_field_type_flags(), and m_merged_field_fmt_labels::init_mgd_field_type_flags().
vtk_gz_flags
type(multi_flag_labels), save m_field_file_format_labels::vtk_gz_flags
Character lables for gzipped VTK 'VTK_gzip', 'VTK_gz', 'gzip_VTK', 'gz_VTK'.
Definition at line 121 of file m_field_file_format_labels.f90.
Referenced by m_field_file_format::choose_ucd_file_format(), dealloc_field_type_flags(), and init_field_type_flags().
vtk_name
character(len = kchara), dimension(1), parameter m_field_file_format_labels::vtk_name = (/'VTK'/)
flag for VTK
Definition at line 53 of file m_field_file_format_labels.f90.
Referenced by init_field_type_flags().