CALYPSO: gzip_defleate Module Reference
gzip_defleate Module Reference
Data Types
interface gzip_defleat_begin
interface gzip_defleat_cont
interface gzip_defleat_last
interface gzip_defleat_once
Functions/Subroutines
subroutine gzip_defleat_real_once (num, data, len_gzipbuf, zbuf, gzipbuf)
subroutine gzip_defleat_int8_once (num, int8_dat, len_gzipbuf, zbuf, gzipbuf)
subroutine gzip_defleat_int4_once (num, int4_dat, len_gzipbuf, zbuf, gzipbuf)
subroutine gzip_defleat_char_once (len_buf, textbuf, len_gzipbuf, zbuf, gzipbuf)
subroutine gzip_defleat_char_begin (len_buf, textbuf, len_gzipbuf, zbuf, gzipbuf)
subroutine gzip_defleat_char_cont (len_buf, textbuf, zbuf)
subroutine gzip_defleat_char_last (len_buf, textbuf, zbuf)
Function/Subroutine Documentation
gzip_defleat_char_begin()
subroutine gzip_defleate::gzip_defleat_char_begin (integer, intent(in) len_buf, character(len=1), dimension(len_buf), intent(in), target textbuf, integer, intent(in) len_gzipbuf, type(buffer_4_gzip), intent(inout) zbuf, character(len=1), dimension(len_gzipbuf), intent(inout), target gzipbuf)
Definition at line 198 of file gzip_defleate.f90.
References t_buffer_4_gzip::link_compressed_buffer(), and t_buffer_4_gzip::link_text_buffer_for_zlib().
Referenced by zlib_cvt_ascii_ele_connect::defleate_1d_global_address(), zlib_cvt_ascii_comm_tbl::defleate_comm_table(), zlib_cvt_ascii_ele_connect::defleate_ele_connect(), zlib_cvt_ascii_ele_connect::defleate_ele_int_list(), zlib_cvt_ascii_comm_tbl::defleate_element_type(), zlib_convert_ascii_vector::defleate_node_position(), zlib_cvt_ucd_data::defleate_ucd_connect(), zlib_cvt_ucd_data::defleate_ucd_vector(), zlib_convert_ascii_vector::defleate_vector_txt(), zlib_cvt_vtk_data::defleate_vtk_celltype(), zlib_cvt_vtk_data::defleate_vtk_connect(), zlib_cvt_vtk_data::defleate_vtk_scalar(), zlib_cvt_vtk_data::defleate_vtk_tensor(), and zlib_cvt_vtk_data::defleate_vtk_vector().
gzip_defleat_char_cont()
subroutine gzip_defleate::gzip_defleat_char_cont (integer, intent(in) len_buf, character(len=1), dimension(len_buf), intent(in), target textbuf, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 217 of file gzip_defleate.f90.
References t_buffer_4_gzip::link_text_buffer_for_zlib().
Referenced by zlib_cvt_ascii_ele_connect::defleate_1d_global_address(), zlib_cvt_ascii_comm_tbl::defleate_comm_table(), zlib_cvt_ascii_ele_connect::defleate_ele_connect(), zlib_cvt_ascii_ele_connect::defleate_ele_int_list(), zlib_cvt_ascii_comm_tbl::defleate_element_type(), zlib_convert_ascii_vector::defleate_node_position(), zlib_cvt_ucd_data::defleate_ucd_connect(), zlib_cvt_ucd_data::defleate_ucd_vector(), zlib_convert_ascii_vector::defleate_vector_txt(), zlib_cvt_vtk_data::defleate_vtk_celltype(), zlib_cvt_vtk_data::defleate_vtk_connect(), zlib_cvt_vtk_data::defleate_vtk_scalar(), zlib_cvt_vtk_data::defleate_vtk_tensor(), and zlib_cvt_vtk_data::defleate_vtk_vector().
gzip_defleat_char_last()
subroutine gzip_defleate::gzip_defleat_char_last (integer, intent(in) len_buf, character(len=1), dimension(len_buf), intent(in), target textbuf, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 232 of file gzip_defleate.f90.
References t_buffer_4_gzip::link_text_buffer_for_zlib(), and t_buffer_4_gzip::unlink_pointer_for_zlib_buffer().
Referenced by zlib_cvt_ascii_ele_connect::defleate_1d_global_address(), zlib_cvt_ascii_comm_tbl::defleate_comm_table(), zlib_cvt_ascii_ele_connect::defleate_ele_connect(), zlib_cvt_ascii_ele_connect::defleate_ele_int_list(), zlib_cvt_ascii_comm_tbl::defleate_element_type(), zlib_convert_ascii_vector::defleate_node_position(), zlib_cvt_ucd_data::defleate_ucd_connect(), zlib_cvt_ucd_data::defleate_ucd_vector(), zlib_convert_ascii_vector::defleate_vector_txt(), zlib_cvt_vtk_data::defleate_vtk_celltype(), zlib_cvt_vtk_data::defleate_vtk_connect(), zlib_cvt_vtk_data::defleate_vtk_scalar(), zlib_cvt_vtk_data::defleate_vtk_tensor(), and zlib_cvt_vtk_data::defleate_vtk_vector().
gzip_defleat_char_once()
subroutine gzip_defleate::gzip_defleat_char_once (integer, intent(in) len_buf, character(len=1), dimension(len_buf), intent(in), target textbuf, integer, intent(in) len_gzipbuf, type(buffer_4_gzip), intent(inout) zbuf, character(len=1), dimension(len_gzipbuf), intent(inout), target gzipbuf)
Definition at line 175 of file gzip_defleate.f90.
References t_buffer_4_gzip::link_compressed_buffer(), and t_buffer_4_gzip::link_text_buffer_for_zlib().
Referenced by data_convert_by_zlib::defleate_1d_character_b(), zlib_cvt_ascii_ele_connect::defleate_1d_global_address(), zlib_convert_text::defleate_characters(), zlib_cvt_ascii_comm_tbl::defleate_comm_table(), zlib_cvt_ascii_ele_connect::defleate_ele_connect(), zlib_cvt_ascii_ele_connect::defleate_ele_int_list(), zlib_cvt_ascii_comm_tbl::defleate_element_type(), zlib_convert_ascii_vector::defleate_node_position(), zlib_cvt_ucd_data::defleate_ucd_connect(), zlib_cvt_ucd_data::defleate_ucd_vector(), zlib_convert_ascii_vector::defleate_vector_txt(), zlib_cvt_vtk_data::defleate_vtk_celltype(), zlib_cvt_vtk_data::defleate_vtk_connect(), zlib_cvt_vtk_data::defleate_vtk_scalar(), and zlib_cvt_vtk_data::defleate_vtk_vector().
gzip_defleat_int4_once()
subroutine gzip_defleate::gzip_defleat_int4_once (integer, intent(in) num, integer(kind = 4), dimension(num), intent(in), target int4_dat, integer, intent(in) len_gzipbuf, type(buffer_4_gzip), intent(inout) zbuf, character(len=1), dimension(len_gzipbuf), intent(inout), target gzipbuf)
Definition at line 152 of file gzip_defleate.f90.
References t_buffer_4_gzip::link_compressed_buffer(), and t_buffer_4_gzip::link_int4_buffer_for_zlib().
Referenced by data_convert_by_zlib::defleate_endian_flag().
gzip_defleat_int8_once()
subroutine gzip_defleate::gzip_defleat_int8_once (integer, intent(in) num, integer(kind = kint_gl), dimension(num), intent(in), target int8_dat, integer, intent(in) len_gzipbuf, type(buffer_4_gzip), intent(inout) zbuf, character(len=1), dimension(len_gzipbuf), intent(inout), target gzipbuf)
Definition at line 130 of file gzip_defleate.f90.
References t_buffer_4_gzip::link_compressed_buffer(), and t_buffer_4_gzip::link_int8_buffer_for_zlib().
Referenced by data_convert_by_zlib::defleate_int8_vector_b().
gzip_defleat_real_once()
subroutine gzip_defleate::gzip_defleat_real_once (integer, intent(in) num, real(kind = kreal), dimension(num), intent(in), target data, integer, intent(in) len_gzipbuf, type(buffer_4_gzip), intent(inout) zbuf, character(len=1), dimension(len_gzipbuf), intent(inout), target gzipbuf)
Definition at line 108 of file gzip_defleate.f90.
References t_buffer_4_gzip::link_compressed_buffer(), and t_buffer_4_gzip::link_real_buffer_for_zlib().
Referenced by data_convert_by_zlib::defleate_1d_vector_b().