CALYPSO: const_wz_coriolis_rtp Module Reference
const_wz_coriolis_rtp Module Reference
Evaluate Coriolis term on spherical grid.
Functions/Subroutines
subroutine sel_wz_coriolis_rtp (sph_rtp, leg, coef_cor, velo_rtp, coriolis_rtp)
subroutine sel_wz_div_coriolis_rtp (sph_rtp, leg, coef_cor, velo_rtp, coriolis_rtp)
subroutine cal_wz_coriolis_pole (nnod_pole, coef_cor, velo_pole, coriolis_pole)
subroutine, private cal_wz_coriolis_rtp (sph_rtp, leg, coef_cor, velo_rtp, coriolis_rtp)
subroutine, private cal_wz_coriolis_prt (sph_rtp, leg, coef_cor, velo_rtp, coriolis_rtp)
subroutine, private cal_wz_div_coriolis_rtp (sph_rtp, leg, coef_cor, velo_rtp, div_coriolis_rtp)
subroutine, private cal_wz_div_coriolis_prt (sph_rtp, leg, coef_cor, velo_rtp, div_coriolis_rtp)
Detailed Description
Evaluate Coriolis term on spherical grid.
      subroutine sel_wz_coriolis_rtp                                  &
     &         (sph_rtp, leg, coef_cor, velo_rtp, coriolis_rtp)
      subroutine sel_wz_div_coriolis_rtp                              &
     &         (sph_rtp, leg, coef_cor, velo_rtp, coriolis_rtp)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(legendre_4_sph_trans), intent(in) :: leg
      subroutine cal_wz_coriolis_pole                                 &
     &         (nnod_pole, coef_cor, velo_pole, coriolis_pole)
Parameters
irj_fld Address for spectr data
Function/Subroutine Documentation
cal_wz_coriolis_pole()
subroutine const_wz_coriolis_rtp::cal_wz_coriolis_pole (integer(kind = kint), intent(in) nnod_pole, real(kind = kreal), intent(in) coef_cor, real(kind = kreal), dimension(nnod_pole,3), intent(in) velo_pole, real(kind = kreal), dimension(nnod_pole,3), intent(inout) coriolis_pole)
Definition at line 92 of file const_wz_coriolis_rtp.f90.
References m_constants::one, and m_constants::zero.
Referenced by cal_nonlinear_sph_mhd::cal_nonlinear_pole_mhd().
cal_wz_coriolis_prt()
subroutine, private const_wz_coriolis_rtp::cal_wz_coriolis_prt (type(sph_rtp_grid), intent(in) sph_rtp, type(legendre_4_sph_trans), intent(in) leg, real(kind = kreal), intent(in) coef_cor, real(kind = kreal), dimension(sph_rtp%nnod_rtp,3), intent(in) velo_rtp, real(kind = kreal), dimension(sph_rtp%nnod_rtp,3), intent(inout) coriolis_rtp) private
Definition at line 169 of file const_wz_coriolis_rtp.f90.
References m_constants::zero.
Referenced by sel_wz_coriolis_rtp().
cal_wz_coriolis_rtp()
subroutine, private const_wz_coriolis_rtp::cal_wz_coriolis_rtp (type(sph_rtp_grid), intent(in) sph_rtp, type(legendre_4_sph_trans), intent(in) leg, real(kind = kreal), intent(in) coef_cor, real(kind = kreal), dimension(sph_rtp%nnod_rtp,3), intent(in) velo_rtp, real(kind = kreal), dimension(sph_rtp%nnod_rtp,3), intent(inout) coriolis_rtp) private
Definition at line 125 of file const_wz_coriolis_rtp.f90.
References m_constants::zero.
Referenced by sel_wz_coriolis_rtp().
cal_wz_div_coriolis_prt()
subroutine, private const_wz_coriolis_rtp::cal_wz_div_coriolis_prt (type(sph_rtp_grid), intent(in) sph_rtp, type(legendre_4_sph_trans), intent(in) leg, real(kind = kreal), intent(in) coef_cor, real(kind = kreal), dimension(sph_rtp%nnod_rtp,3), intent(in) velo_rtp, real(kind = kreal), dimension(sph_rtp%nnod_rtp), intent(inout) div_coriolis_rtp) private
Definition at line 252 of file const_wz_coriolis_rtp.f90.
References m_constants::zero.
Referenced by sel_wz_div_coriolis_rtp().
cal_wz_div_coriolis_rtp()
subroutine, private const_wz_coriolis_rtp::cal_wz_div_coriolis_rtp (type(sph_rtp_grid), intent(in) sph_rtp, type(legendre_4_sph_trans), intent(in) leg, real(kind = kreal), intent(in) coef_cor, real(kind = kreal), dimension(sph_rtp%nnod_rtp,3), intent(in) velo_rtp, real(kind = kreal), dimension(sph_rtp%nnod_rtp), intent(inout) div_coriolis_rtp) private
Definition at line 214 of file const_wz_coriolis_rtp.f90.
References m_constants::zero.
Referenced by sel_wz_div_coriolis_rtp().
sel_wz_coriolis_rtp()
subroutine const_wz_coriolis_rtp::sel_wz_coriolis_rtp (type(sph_rtp_grid), intent(in) sph_rtp, type(legendre_4_sph_trans), intent(in) leg, real(kind = kreal), intent(in) coef_cor, real(kind = kreal), dimension(sph_rtp%nnod_rtp,3), intent(in) velo_rtp, real(kind = kreal), dimension(sph_rtp%nnod_rtp,3), intent(inout) coriolis_rtp)
Definition at line 43 of file const_wz_coriolis_rtp.f90.
References cal_wz_coriolis_prt(), and cal_wz_coriolis_rtp().
Referenced by cal_nonlinear_sph_mhd::nonlinear_terms_in_rtp(), and cal_energy_flux_rtp::s_cal_energy_flux_rtp().
sel_wz_div_coriolis_rtp()
subroutine const_wz_coriolis_rtp::sel_wz_div_coriolis_rtp (type(sph_rtp_grid), intent(in) sph_rtp, type(legendre_4_sph_trans), intent(in) leg, real(kind = kreal), intent(in) coef_cor, real(kind = kreal), dimension(sph_rtp%nnod_rtp,3), intent(in) velo_rtp, real(kind = kreal), dimension(sph_rtp%nnod_rtp,3), intent(inout) coriolis_rtp)
Definition at line 67 of file const_wz_coriolis_rtp.f90.
References cal_wz_div_coriolis_prt(), and cal_wz_div_coriolis_rtp().