CALYPSO: poynting_flux_smp Module Reference
poynting_flux_smp Module Reference
Evaluate poynting flux in physical space
$omp parallel is required to use these routines.
Functions/Subroutines
subroutine cal_electric_field_smp (nnod, coef_d, current, uxb, e_field)
subroutine cal_poynting_flux_smp (nnod, coef_d, current, uxb, b_field, poynting)
subroutine cal_rtp_magnetic_streach (nnod, nri, nth, a_r_1d_rtp_r, cot_theta_1d_rtp, b_field, u_field, grad_ux, grad_uy, grad_uz, magne_streach)
subroutine cal_xyz_magnetic_streach (nnod, b_field, grad_ux, grad_uy, grad_uz, magne_streach)
subroutine cal_rtp_magnetic_streach_tmp (nnod, nri, nth, a_r_1d_rtp_r, cot_theta_1d_rtp, b_field, u_field, grad_ux, grad_uy, grad_uz, magne_streach)
Detailed Description
Evaluate poynting flux in physical space
$omp parallel is required to use these routines.
      subroutine cal_electric_field_smp                               &
     &         (nnod, coef_d, current, uxb, e_field)
      subroutine cal_poynting_flux_smp                                &
     &         (nnod, coef_d, current, uxb, b_field, poynting)
      subroutine cal_rtp_magnetic_streach                             &
     &         (nnod, nri, nth, a_r_1d_rtp_r, cot_theta_1d_rtp,       &
     &          b_field, u_field, grad_ux, grad_uy, grad_uz,          &
     &          magne_streach)
      subroutine cal_xyz_magnetic_streach(nnod, b_field,              &
     &          grad_ux, grad_uy, grad_uz, magne_streach)
      subroutine cal_rtp_magnetic_streach_tmp                         &
     &         (nnod, nri, nth, a_r_1d_rtp_r, cot_theta_1d_rtp,       &
     &          b_field, u_field, grad_ux, grad_uy, grad_uz,          &
     &          magne_streach)
Parameters
np_smp Number of SMP processes
nnod Number of data points
inod_smp_stack(0:np_smp) End address of each SMP process
coef_d Coefficient for magnetic diffusion
Parameters
b_field(nnod,3) Magnetic field \(B_{i} \)
current(nnod,3) Current density \(e_{ijk) \partial_{j} B_{k})\)
uxb(nnod,3) Induction \((e_{ijk) u{j} B_{k})\)
e_field(nnod,3) Electric field \(E_{i} = \sigma^{-1} J_{i} - (e_{ijk) u{j} B_{k})\)
poynting(nnod,3) Poynting flux \((e_{ijk) E{j} B_{k})\)
Function/Subroutine Documentation
cal_electric_field_smp()
subroutine poynting_flux_smp::cal_electric_field_smp (integer (kind=kint), intent(in) nnod, real (kind=kreal), intent(in) coef_d, real (kind=kreal), dimension(nnod,3), intent(in) current, real (kind=kreal), dimension(nnod,3), intent(in) uxb, real (kind=kreal), dimension(nnod,3), intent(inout) e_field)
Definition at line 53 of file poynting_flux_smp.f90.
Referenced by cal_energy_flux_rtp::cal_magnetic_fluxes_pole(), and cal_energy_flux_rtp::cal_magnetic_fluxes_rtp().
cal_poynting_flux_smp()
subroutine poynting_flux_smp::cal_poynting_flux_smp (integer (kind=kint), intent(in) nnod, real (kind=kreal), intent(in) coef_d, real (kind=kreal), dimension(nnod,3), intent(in) current, real (kind=kreal), dimension(nnod,3), intent(in) uxb, real (kind=kreal), dimension(nnod,3), intent(in) b_field, real (kind=kreal), dimension(nnod,3), intent(inout) poynting)
Definition at line 75 of file poynting_flux_smp.f90.
Referenced by cal_energy_flux_rtp::cal_magnetic_fluxes_pole(), and cal_energy_flux_rtp::cal_magnetic_fluxes_rtp().
cal_rtp_magnetic_streach()
subroutine poynting_flux_smp::cal_rtp_magnetic_streach (integer (kind=kint), intent(in) nnod, integer (kind=kint), intent(in) nri, integer (kind=kint), intent(in) nth, real (kind=kreal), dimension(nri), intent(in) a_r_1d_rtp_r, real (kind=kreal), dimension(nth), intent(in) cot_theta_1d_rtp, real (kind=kreal), dimension(nnod,3), intent(in) b_field, real (kind=kreal), dimension(nnod,3), intent(in) u_field, real (kind=kreal), dimension(nnod,3), intent(in) grad_ux, real (kind=kreal), dimension(nnod,3), intent(in) grad_uy, real (kind=kreal), dimension(nnod,3), intent(in) grad_uz, real (kind=kreal), dimension(nnod,3), intent(inout) magne_streach)
Definition at line 107 of file poynting_flux_smp.f90.
References m_constants::ione.
Referenced by cal_energy_flux_rtp::cal_magnetic_fluxes_rtp().
cal_rtp_magnetic_streach_tmp()
subroutine poynting_flux_smp::cal_rtp_magnetic_streach_tmp (integer (kind=kint), intent(in) nnod, integer (kind=kint), intent(in) nri, integer (kind=kint), intent(in) nth, real (kind=kreal), dimension(nri), intent(in) a_r_1d_rtp_r, real (kind=kreal), dimension(nth), intent(in) cot_theta_1d_rtp, real (kind=kreal), dimension(nnod,3), intent(in) b_field, real (kind=kreal), dimension(nnod,3), intent(in) u_field, real (kind=kreal), dimension(nnod,3), intent(in) grad_ux, real (kind=kreal), dimension(nnod,3), intent(in) grad_uy, real (kind=kreal), dimension(nnod,3), intent(in) grad_uz, real (kind=kreal), dimension(nnod,3), intent(inout) magne_streach)
Definition at line 186 of file poynting_flux_smp.f90.
References m_constants::ione, and m_constants::zero.
cal_xyz_magnetic_streach()
subroutine poynting_flux_smp::cal_xyz_magnetic_streach (integer (kind=kint), intent(in) nnod, real (kind=kreal), dimension(nnod,3), intent(in) b_field, real (kind=kreal), dimension(nnod,3), intent(in) grad_ux, real (kind=kreal), dimension(nnod,3), intent(in) grad_uy, real (kind=kreal), dimension(nnod,3), intent(in) grad_uz, real (kind=kreal), dimension(nnod,3), intent(inout) magne_streach)
Definition at line 155 of file poynting_flux_smp.f90.
Referenced by cal_energy_flux_rtp::cal_magnetic_fluxes_pole().