CALYPSO: viewer_mesh_data_io Module Reference
viewer_mesh_data_io Module Reference
Functions/Subroutines
subroutine write_sgl_domain_data_viewer (view_mesh)
subroutine write_node_data_viewer (view_mesh)
subroutine write_surf_connect_viewer (num_pe, isurf_sf_stack, view_mesh)
subroutine write_edge_connect_viewer (view_mesh)
Function/Subroutine Documentation
write_edge_connect_viewer()
subroutine viewer_mesh_data_io::write_edge_connect_viewer (type(viewer_mesh_data), intent(in) view_mesh)
Definition at line 98 of file viewer_mesh_data_IO.f90.
References m_viewer_mesh_labels::hd_edge_on_sf_viewer(), m_viewer_mesh_labels::hd_edge_viewer(), and t_viewer_mesh::surface_id.
Referenced by viewer_file_io::output_single_surface_grid().
write_node_data_viewer()
subroutine viewer_mesh_data_io::write_node_data_viewer (type(viewer_mesh_data), intent(in) view_mesh)
Definition at line 49 of file viewer_mesh_data_IO.f90.
References m_viewer_mesh_labels::hd_node_viewer(), and t_viewer_mesh::surface_id.
Referenced by viewer_file_io::output_single_surface_grid().
write_sgl_domain_data_viewer()
subroutine viewer_mesh_data_io::write_sgl_domain_data_viewer (type(viewer_mesh_data), intent(in) view_mesh)
Definition at line 32 of file viewer_mesh_data_IO.f90.
References m_viewer_mesh_labels::hd_ndomain_viewer(), m_constants::ione, and t_viewer_mesh::surface_id.
Referenced by viewer_file_io::output_single_surface_grid().
write_surf_connect_viewer()
subroutine viewer_mesh_data_io::write_surf_connect_viewer (integer, intent(in) num_pe, integer(kind = kint), dimension(0:num_pe), intent(in) isurf_sf_stack, type(viewer_mesh_data), intent(in) view_mesh)
Definition at line 67 of file viewer_mesh_data_IO.f90.
References m_viewer_mesh_labels::hd_surf_viewer(), and t_viewer_mesh::surface_id.
Referenced by viewer_file_io::output_single_surface_grid().