CALYPSO: const_surface_data Module Reference
const_surface_data Module Reference
Construct surface information form element connectivity.
Functions/Subroutines
subroutine construct_surface_data (nod, ele, surf)
subroutine const_ele_list_4_surface (ele, surf)
subroutine empty_surface_connect (ele, surf)
subroutine, private const_surface_hash (ele, sf_ele_tbl)
subroutine const_part_surface_hash (ele, nele_grp, item_grp, sf_ele_tbl)
subroutine, private const_all_surface_data (ele, surf, sf_ele_tbl)
subroutine, private const_external_surface_data (nod, ele, surf, sf_ele_tbl)
subroutine const_isolate_surface_data (ele, surf, sf_ele_tbl)
Variables
type(sum_hash_tbl), save, private surf_ele_tbl
Detailed Description
Construct surface information form element connectivity.
      subroutine construct_surface_data(nod, ele, surf)
      subroutine const_surface_hash(nod, ele, surf, sf_ele_tbl)
      subroutine const_part_surface_hash(ele, nele_grp, item_grp,     &
     &          sf_ele_tbl)
        integer(kind = kint) :: nele_grp
        integer(kind = kint) :: item_grp(nele_grp)
        type(node_data),    intent(in) :: nod
        type(element_data), intent(in) :: ele
        type(surface_data), intent(inout) :: surf
        type(sum_hash_tbl), intent(inout) :: sf_ele_tbl
      subroutine const_ele_list_4_surface(ele, surf)
      subroutine empty_surface_connect(ele, surf)
        type(node_data),    intent(in) :: nod
        type(element_data), intent(in) :: ele
        type(surface_data), intent(inout) :: surf
Function/Subroutine Documentation
const_all_surface_data()
subroutine, private const_surface_data::const_all_surface_data (type(element_data), intent(in) ele, type(surface_data), intent(inout) surf, type(sum_hash_tbl), intent(inout) sf_ele_tbl) private
Definition at line 171 of file const_surface_data.f90.
References t_surface_data::allocate_surface_connect_type(), set_surface_data::count_all_surfaces(), m_machine_parameter::iflag_debug, mark_surf_hash::mark_all_surfaces(), set_surface_data::set_all_surfaces(), and set_surface_data::set_surf_rotation_flag().
Referenced by construct_surface_data().
const_ele_list_4_surface()
subroutine const_surface_data::const_ele_list_4_surface (type(element_data), intent(in) ele, type(surface_data), intent(inout) surf)
Definition at line 84 of file const_surface_data.f90.
References t_surface_data::alloc_ele_4_surf_type(), m_geometry_constants::nsurf_4_ele, and set_element_list_4_surface::set_ele_list_4_surf().
Referenced by const_mesh_information::const_mesh_infos().
const_external_surface_data()
subroutine, private const_surface_data::const_external_surface_data (type(node_data), intent(in) nod, type(element_data), intent(in) ele, type(surface_data), intent(inout) surf, type(sum_hash_tbl), intent(inout) sf_ele_tbl) private
Definition at line 214 of file const_surface_data.f90.
References t_surface_data::allocate_ext_surface_type(), set_surface_data::count_part_surface(), m_machine_parameter::iflag_debug, mark_surf_hash::mark_external_surface(), mark_surf_hash::mark_independent_surface(), and set_surface_data::set_part_surface().
Referenced by construct_surface_data().
const_isolate_surface_data()
subroutine const_surface_data::const_isolate_surface_data (type(element_data), intent(in) ele, type(surface_data), intent(inout) surf, type(sum_hash_tbl), intent(inout) sf_ele_tbl)
Definition at line 259 of file const_surface_data.f90.
References t_surface_data::allocate_iso_surface_type(), set_surface_data::count_part_surface(), m_machine_parameter::iflag_debug, mark_surf_hash::mark_independent_surface(), set_surface_data::set_part_surface(), and surf_ele_tbl.
Referenced by construct_surface_data().
const_part_surface_hash()
subroutine const_surface_data::const_part_surface_hash (type(element_data), intent(in) ele, integer(kind = kint) nele_grp, integer(kind = kint), dimension(nele_grp) item_grp, type(sum_hash_tbl), intent(inout) sf_ele_tbl)
Definition at line 143 of file const_surface_data.f90.
References set_surface_hash::count_part_surface_hash(), and set_surface_hash::set_part_surf_hash().
Referenced by const_merged_surf_4_group::const_merged_surface_4_ele_grp().
const_surface_hash()
subroutine, private const_surface_data::const_surface_hash (type(element_data), intent(in) ele, type(sum_hash_tbl), intent(inout) sf_ele_tbl) private
Definition at line 119 of file const_surface_data.f90.
References set_surface_hash::count_surface_hash(), set_surface_hash::set_surf_hash(), and surf_ele_tbl.
Referenced by construct_surface_data().
construct_surface_data()
subroutine const_surface_data::construct_surface_data (type(node_data), intent(in) nod, type(element_data), intent(in) ele, type(surface_data), intent(inout) surf)
Definition at line 53 of file const_surface_data.f90.
References t_sum_hash::alloc_sum_hash(), const_all_surface_data(), const_external_surface_data(), const_isolate_surface_data(), const_surface_hash(), t_sum_hash::dealloc_sum_hash(), m_machine_parameter::iflag_debug, m_geometry_constants::nsurf_4_ele, and surf_ele_tbl.
Referenced by const_kemoview_mesh::const_surf_mesh_4_viewer(), and set_surf_edge_mesh::set_surf_connectivity().
empty_surface_connect()
subroutine const_surface_data::empty_surface_connect (type(element_data), intent(in) ele, type(surface_data), intent(inout) surf)
Definition at line 101 of file const_surface_data.f90.
References t_surface_data::allocate_surf_param_smp_type(), t_surface_data::allocate_surface_connect_type(), and m_machine_parameter::iflag_debug.
Referenced by set_surf_edge_mesh::empty_surface_and_edge().
Variable Documentation
surf_ele_tbl
type(sum_hash_tbl), save, private const_surface_data::surf_ele_tbl private
Definition at line 41 of file const_surface_data.f90.
Referenced by const_isolate_surface_data(), const_surface_hash(), and construct_surface_data().