CALYPSO: mpi_position_io Module Reference
mpi_position_io Module Reference
Mesh file IO for gxipped format.
Functions/Subroutines
subroutine mpi_read_node_position (IO_param, nnod, numdir, id_global, xx)
subroutine mpi_read_radial_position (IO_param, nri, id_r_global, rr)
subroutine mpi_write_node_position (IO_param, nnod, numdir, id_global, xx)
subroutine mpi_write_radial_position (IO_param, nri, id_r_global, rr)
Detailed Description
Mesh file IO for gxipped format.
      subroutine mpi_read_node_position                               &
     &         (IO_param, nnod, numdir, id_global, xx)
      subroutine mpi_read_radial_position                             &
     &         (IO_param, nri, id_r_global, rr)
      subroutine mpi_write_node_position                              &
     &         (IO_param, nnod, numdir, id_global, xx)
      subroutine mpi_write_radial_position                            &
     &         (IO_param, nri, id_r_global, rr)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
Function/Subroutine Documentation
mpi_read_node_position()
subroutine mpi_position_io::mpi_read_node_position (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint_gl), intent(in) nnod, integer(kind = kint), intent(in) numdir, integer(kind = kint_gl), dimension(nnod), intent(inout) id_global, real(kind=kreal), dimension(nnod, numdir), intent(inout) xx)
Definition at line 38 of file MPI_position_IO.f90.
References m_constants::ione, and mpi_ascii_data_io::mpi_skip_read().
Referenced by mpi_node_geometry_io::mpi_read_geometry_info().
mpi_read_radial_position()
subroutine mpi_position_io::mpi_read_radial_position (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) nri, integer(kind=kint), dimension(nri), intent(inout) id_r_global, real(kind=kreal), dimension(nri), intent(inout) rr)
Definition at line 94 of file MPI_position_IO.f90.
References m_constants::ione, and mpi_ascii_data_io::mpi_skip_read().
Referenced by mpi_sph_gl_1d_idx_io::mpi_read_rj_gl_1d_table(), and mpi_sph_gl_1d_idx_io::mpi_read_rtp_gl_1d_table().
mpi_write_node_position()
subroutine mpi_position_io::mpi_write_node_position (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint_gl), intent(in) nnod, integer(kind = kint), intent(in) numdir, integer(kind = kint_gl), dimension(nnod), intent(in) id_global, real(kind=kreal), dimension(nnod, numdir), intent(in) xx)
Definition at line 147 of file MPI_position_IO.f90.
References mpi_ascii_data_io::mpi_write_stack_over_domain().
Referenced by mpi_node_geometry_io::mpi_write_geometry_info().
mpi_write_radial_position()
subroutine mpi_position_io::mpi_write_radial_position (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) nri, integer(kind=kint), dimension(nri), intent(in) id_r_global, real(kind=kreal), dimension(nri), intent(in) rr)
Definition at line 189 of file MPI_position_IO.f90.
References m_constants::ione, and mpi_ascii_data_io::mpi_write_stack_over_domain().
Referenced by mpi_sph_gl_1d_idx_io::mpi_write_rj_gl_1d_table(), and mpi_sph_gl_1d_idx_io::mpi_write_rtp_gl_1d_table().