CALYPSO: set_surface_position Module Reference
set_surface_position Module Reference
Functions/Subroutines
subroutine set_linear_surf_position (numnod, numsurf, ie_surf, xx, x_surf)
subroutine set_quad_surf_position (numnod, numsurf, ie_surf, xx, x_surf)
subroutine set_lag_surf_position (numnod, numsurf, ie_surf, xx, x_surf)
subroutine set_triangle_surf_position (numnod, numsurf, ie_surf, xx, x_surf)
Function/Subroutine Documentation
set_lag_surf_position()
subroutine set_surface_position::set_lag_surf_position (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) numsurf, integer(kind = kint), dimension(numsurf,9), intent(in) ie_surf, real(kind=kreal), dimension(numnod,3), intent(in) xx, real(kind=kreal), dimension(numsurf,3), intent(inout) x_surf)
Definition at line 102 of file set_surface_position.f90.
Referenced by cal_mesh_position::set_center_of_surface().
set_linear_surf_position()
subroutine set_surface_position::set_linear_surf_position (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) numsurf, integer(kind = kint), dimension(numsurf,4), intent(in) ie_surf, real(kind=kreal), dimension(numnod,3), intent(in) xx, real(kind=kreal), dimension(numsurf,3), intent(inout) x_surf)
Definition at line 29 of file set_surface_position.f90.
References m_constants::quad.
Referenced by cal_mesh_position::set_center_of_surface().
set_quad_surf_position()
subroutine set_surface_position::set_quad_surf_position (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) numsurf, integer(kind = kint), dimension(numsurf,8), intent(in) ie_surf, real(kind=kreal), dimension(numnod,3), intent(in) xx, real(kind=kreal), dimension(numsurf,3), intent(inout) x_surf)
Definition at line 62 of file set_surface_position.f90.
References m_constants::half, and m_constants::quad.
Referenced by cal_mesh_position::set_center_of_surface().
set_triangle_surf_position()
subroutine set_surface_position::set_triangle_surf_position (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) numsurf, integer(kind = kint), dimension(numsurf,3), intent(in) ie_surf, real(kind=kreal), dimension(numnod,3), intent(in) xx, real(kind=kreal), dimension(numsurf,3), intent(inout) x_surf)
Definition at line 129 of file set_surface_position.f90.
References m_constants::third.