CALYPSO: set_element_data_4_io Module Reference
set_element_data_4_io Module Reference
Functions/Subroutines
subroutine copy_ele_connect_to_io (ele, ele_IO)
subroutine copy_ele_connect_from_io (ele_IO, ele)
subroutine copy_ele_geometry_to_io (ele, nod_IO, sfed_IO)
subroutine copy_ele_sph_geom_to_io (ele, nod_IO, sfed_IO)
subroutine copy_ele_cyl_geom_to_io (ele, nod_IO, sfed_IO)
subroutine copy_ele_geometry_from_io (nod_IO, sfed_IO, ele)
Function/Subroutine Documentation
copy_ele_connect_from_io()
subroutine set_element_data_4_io::copy_ele_connect_from_io (type(element_data), intent(inout) ele_IO, type(element_data), intent(inout) ele)
Definition at line 75 of file set_element_data_4_IO.f90.
References t_geometry_data::allocate_ele_connect_type(), t_geometry_data::deallocate_ele_connect_type(), and set_nnod_4_ele_by_type::set_nnod_4_ele_by_eletype().
Referenced by load_mesh_data::set_mesh_geometry_data().
copy_ele_connect_to_io()
subroutine set_element_data_4_io::copy_ele_connect_to_io (type(element_data), intent(in) ele, type(element_data), intent(inout) ele_IO)
Definition at line 41 of file set_element_data_4_IO.f90.
References t_geometry_data::allocate_ele_connect_type().
Referenced by mpi_load_mesh_data::mpi_output_mesh(), and load_mesh_data::output_mesh().
copy_ele_cyl_geom_to_io()
subroutine set_element_data_4_io::copy_ele_cyl_geom_to_io (type(element_data), intent(in) ele, type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 180 of file set_element_data_4_IO.f90.
References t_surf_edge_io::alloc_ele_scalar_io(), and t_geometry_data::alloc_node_geometry_base().
copy_ele_geometry_from_io()
subroutine set_element_data_4_io::copy_ele_geometry_from_io (type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO, type(element_data), intent(inout) ele)
Definition at line 211 of file set_element_data_4_IO.f90.
References t_geometry_data::alloc_ele_geometry().
copy_ele_geometry_to_io()
subroutine set_element_data_4_io::copy_ele_geometry_to_io (type(element_data), intent(in) ele, type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 121 of file set_element_data_4_IO.f90.
References t_surf_edge_io::alloc_ele_scalar_io(), and t_geometry_data::alloc_node_geometry_base().
copy_ele_sph_geom_to_io()
subroutine set_element_data_4_io::copy_ele_sph_geom_to_io (type(element_data), intent(in) ele, type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 150 of file set_element_data_4_IO.f90.
References t_surf_edge_io::alloc_ele_scalar_io(), and t_geometry_data::alloc_node_geometry_base().