CALYPSO: t_addresses_sph_transform Module Reference
t_addresses_sph_transform Module Reference
Field addresses for spherical harmonics transform in MHD dynamo simulation.
Data Types
type spherical_transform_data
strucutre of spherical transform data addresses
Functions/Subroutines
subroutine alloc_sph_trns_field_name (each_trns)
subroutine alloc_sph_trns_field_data (sph_rtp, each_trns)
subroutine alloc_sph_trns_pole_data (sph_rtp, each_trns)
subroutine dealloc_sph_trns_field_name (each_trns)
subroutine dealloc_sph_trns_field_dats (each_trns)
subroutine dealloc_sph_trns_pole_data (each_trns)
subroutine count_num_fields_each_trans (each_trns, ncomp_sph_trans, nvector_sph_trans, nscalar_sph_trans)
subroutine copy_field_name_4_sph_trns (num_copy, etrns_org, etrns_new)
Detailed Description
Field addresses for spherical harmonics transform in MHD dynamo simulation.
      subroutine alloc_sph_trns_field_name(each_trns)
      subroutine alloc_sph_trns_field_data(sph_rtp, each_trns)
      subroutine alloc_sph_trns_pole_data(sph_rtp, each_trns)
        type(spherical_transform_data), intent(inout) :: each_trns
      subroutine dealloc_sph_trns_field_name(each_trns)
      subroutine dealloc_sph_trns_field_dats(each_trns)
      subroutine dealloc_sph_trns_pole_data(each_trns)
        type(spherical_transform_data), intent(inout) :: each_trns
      subroutine count_num_fields_each_trans(each_trns,               &
     &          ncomp_sph_trans, nvector_sph_trans, nscalar_sph_trans)
        type(spherical_transform_data), intent(inout) :: each_trns
      subroutine copy_field_name_4_sph_trns                           &
     &         (num_copy, etrns_org, etrns_new)
        type(spherical_transform_data), intent(in) :: etrns_org
        type(spherical_transform_data), intent(inout) :: etrns_new
Function/Subroutine Documentation
alloc_sph_trns_field_data()
subroutine t_addresses_sph_transform::alloc_sph_trns_field_data (type(sph_rtp_grid), intent(in) sph_rtp, type(spherical_transform_data), intent(inout) each_trns)
Definition at line 91 of file t_addresses_sph_transform.f90.
Referenced by t_sph_trans_arrays_mhd::alloc_nonlinear_data().
alloc_sph_trns_field_name()
subroutine t_addresses_sph_transform::alloc_sph_trns_field_name (type(spherical_transform_data), intent(inout) each_trns)
Definition at line 73 of file t_addresses_sph_transform.f90.
Referenced by add_field_to_sph_trans_list::add_field_name_4_sph_trns(), address_sph_trans_snap::bwd_trans_address_diff_vect(), address_sph_trans_snap::bwd_trans_address_ene_flux(), address_sph_trans_mhd::bwd_trans_address_mhd(), address_sph_trans_snap::bwd_trans_address_snap(), address_sph_trans_snap::fwd_trans_address_diff_vect(), address_sph_trans_snap::fwd_trans_address_ene_flux(), address_sph_trans_mhd::fwd_trans_address_mhd(), and address_sph_trans_snap::fwd_trans_address_snap().
alloc_sph_trns_pole_data()
subroutine t_addresses_sph_transform::alloc_sph_trns_pole_data (type(sph_rtp_grid), intent(in) sph_rtp, type(spherical_transform_data), intent(inout) each_trns)
Definition at line 104 of file t_addresses_sph_transform.f90.
Referenced by t_sph_trans_arrays_mhd::alloc_nonlinear_pole().
copy_field_name_4_sph_trns()
subroutine t_addresses_sph_transform::copy_field_name_4_sph_trns (integer(kind = kint), intent(in) num_copy, type(spherical_transform_data), intent(in) etrns_org, type(spherical_transform_data), intent(inout) etrns_new)
Definition at line 179 of file t_addresses_sph_transform.f90.
Referenced by add_field_to_sph_trans_list::add_field_name_4_sph_trns().
count_num_fields_each_trans()
subroutine t_addresses_sph_transform::count_num_fields_each_trans (type(spherical_transform_data), intent(inout) each_trns, integer(kind = kint), intent(inout) ncomp_sph_trans, integer(kind = kint), intent(inout) nvector_sph_trans, integer(kind = kint), intent(inout) nscalar_sph_trans)
Definition at line 157 of file t_addresses_sph_transform.f90.
dealloc_sph_trns_field_dats()
subroutine t_addresses_sph_transform::dealloc_sph_trns_field_dats (type(spherical_transform_data), intent(inout) each_trns)
Definition at line 134 of file t_addresses_sph_transform.f90.
Referenced by t_sph_trans_arrays_mhd::dealloc_nonlinear_data().
dealloc_sph_trns_field_name()
subroutine t_addresses_sph_transform::dealloc_sph_trns_field_name (type(spherical_transform_data), intent(inout) each_trns)
Definition at line 122 of file t_addresses_sph_transform.f90.
Referenced by add_field_to_sph_trans_list::add_field_name_4_sph_trns().
dealloc_sph_trns_pole_data()
subroutine t_addresses_sph_transform::dealloc_sph_trns_pole_data (type(spherical_transform_data), intent(inout) each_trns)
Definition at line 145 of file t_addresses_sph_transform.f90.
Referenced by t_sph_trans_arrays_mhd::dealloc_nonlinear_pole().