CALYPSO: gz_sph_modes_grids_file_io Module Reference
gz_sph_modes_grids_file_io Module Reference
Spectr data IO routines using zlib.
Functions/Subroutines
subroutine gz_read_geom_rtp_file (file_name, id_rank, sph_file, ierr)
subroutine gz_read_spectr_modes_rj_file (file_name, id_rank, sph_file, ierr)
subroutine gz_read_geom_rtm_file (file_name, id_rank, sph_file, ierr)
subroutine gz_read_modes_rlm_file (file_name, id_rank, sph_file, ierr)
subroutine gz_write_geom_rtp_file (file_name, id_rank, sph_file)
subroutine gz_write_spectr_modes_rj_file (file_name, id_rank, sph_file)
subroutine gz_write_geom_rtm_file (file_name, id_rank, sph_file)
subroutine gz_write_modes_rlm_file (file_name, id_rank, sph_file)
Variables
type(buffer_4_gzip), private zbuf_s
Detailed Description
Spectr data IO routines using zlib.
      subroutine gz_read_geom_rtp_file                                &
     &         (file_name, id_rank, sph_file, ierr)
      subroutine gz_read_spectr_modes_rj_file                         &
     &         (file_name, id_rank, sph_file, ierr)
      subroutine gz_read_geom_rtm_file                                &
     &         (file_name, id_rank, sph_file, ierr)
      subroutine gz_read_modes_rlm_file                               &
     &         (file_name, id_rank, sph_file, ierr)
        type(sph_file_data_type), intent(inout) :: sph_file
      subroutine gz_write_geom_rtp_file                               &
     &         (file_name, id_rank, sph_file)
      subroutine gz_write_spectr_modes_rj_file                        &
     &         (file_name, id_rank, sph_file)
      subroutine gz_write_geom_rtm_file                               &
     &         (file_name, id_rank, sph_file)
      subroutine gz_write_modes_rlm_file                              &
     &         (file_name, id_rank, sph_file)
        type(sph_file_data_type), intent(in) :: sph_file
Parameters
id_rank Process ID
file_name file name for IO (.gz is appended in this module)
Function/Subroutine Documentation
gz_read_geom_rtm_file()
subroutine gz_sph_modes_grids_file_io::gz_read_geom_rtm_file (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(sph_file_data_type), intent(inout) sph_file, integer(kind = kint), intent(inout) ierr)
Definition at line 103 of file gz_sph_modes_grids_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_rd_gzfile_a(), gz_sph_modes_grids_data_io::read_geom_rtm_data_gz(), and zbuf_s.
Referenced by sph_file_io_select::sel_read_geom_rtm_file().
gz_read_geom_rtp_file()
subroutine gz_sph_modes_grids_file_io::gz_read_geom_rtp_file (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(sph_file_data_type), intent(inout) sph_file, integer(kind = kint), intent(inout) ierr)
Definition at line 53 of file gz_sph_modes_grids_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_rd_gzfile_a(), gz_sph_modes_grids_data_io::read_geom_rtp_data_gz(), and zbuf_s.
Referenced by sph_file_io_select::sel_read_geom_rtp_file().
gz_read_modes_rlm_file()
subroutine gz_sph_modes_grids_file_io::gz_read_modes_rlm_file (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(sph_file_data_type), intent(inout) sph_file, integer(kind = kint), intent(inout) ierr)
Definition at line 127 of file gz_sph_modes_grids_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_rd_gzfile_a(), gz_sph_modes_grids_data_io::read_spectr_modes_rlm_data_gz(), and zbuf_s.
Referenced by sph_file_io_select::sel_read_modes_rlm_file().
gz_read_spectr_modes_rj_file()
subroutine gz_sph_modes_grids_file_io::gz_read_spectr_modes_rj_file (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(sph_file_data_type), intent(inout) sph_file, integer(kind = kint), intent(inout) ierr)
Definition at line 78 of file gz_sph_modes_grids_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_rd_gzfile_a(), gz_sph_modes_grids_data_io::read_spectr_modes_rj_data_gz(), and zbuf_s.
Referenced by sph_file_io_select::sel_read_spectr_rj_file().
gz_write_geom_rtm_file()
subroutine gz_sph_modes_grids_file_io::gz_write_geom_rtm_file (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(sph_file_data_type), intent(in) sph_file)
Definition at line 198 of file gz_sph_modes_grids_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_wt_gzfile_a(), gz_sph_modes_grids_data_io::write_geom_rtm_data_gz(), and zbuf_s.
Referenced by sph_file_io_select::sel_write_geom_rtm_file().
gz_write_geom_rtp_file()
subroutine gz_sph_modes_grids_file_io::gz_write_geom_rtp_file (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(sph_file_data_type), intent(in) sph_file)
Definition at line 152 of file gz_sph_modes_grids_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_wt_gzfile_a(), gz_sph_modes_grids_data_io::write_geom_rtp_data_gz(), and zbuf_s.
Referenced by sph_file_io_select::sel_write_geom_rtp_file().
gz_write_modes_rlm_file()
subroutine gz_sph_modes_grids_file_io::gz_write_modes_rlm_file (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(sph_file_data_type), intent(in) sph_file)
Definition at line 220 of file gz_sph_modes_grids_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_wt_gzfile_a(), gz_sph_modes_grids_data_io::write_modes_rlm_data_gz(), and zbuf_s.
Referenced by sph_file_io_select::sel_write_modes_rlm_file().
gz_write_spectr_modes_rj_file()
subroutine gz_sph_modes_grids_file_io::gz_write_spectr_modes_rj_file (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(sph_file_data_type), intent(in) sph_file)
Definition at line 175 of file gz_sph_modes_grids_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_wt_gzfile_a(), gz_sph_modes_grids_data_io::write_spectr_modes_rj_data_gz(), and zbuf_s.
Referenced by sph_file_io_select::sel_write_spectr_modes_rj_file().
Variable Documentation
zbuf_s
type(buffer_4_gzip), private gz_sph_modes_grids_file_io::zbuf_s private
Definition at line 45 of file gz_sph_modes_grids_file_IO.f90.
Referenced by gz_read_geom_rtm_file(), gz_read_geom_rtp_file(), gz_read_modes_rlm_file(), gz_read_spectr_modes_rj_file(), gz_write_geom_rtm_file(), gz_write_geom_rtp_file(), gz_write_modes_rlm_file(), and gz_write_spectr_modes_rj_file().