CALYPSO: sph_modes_grids_file_io Module Reference
sph_modes_grids_file_io Module Reference
ASCII spectr data IO routines.
Functions/Subroutines
subroutine read_geom_rtp_file (file_name, id_file, id_rank, sph_file, ierr)
subroutine read_spectr_modes_rj_file (file_name, id_file, id_rank, sph_file, ierr)
subroutine read_geom_rtm_file (file_name, id_file, id_rank, sph_file, ierr)
subroutine read_modes_rlm_file (file_name, id_file, id_rank, sph_file, ierr)
subroutine write_geom_rtp_file (file_name, id_file, id_rank, sph_file)
subroutine write_spectr_modes_rj_file (file_name, id_file, id_rank, sph_file)
subroutine write_geom_rtm_file (file_name, id_file, id_rank, sph_file)
subroutine write_modes_rlm_file (file_name, id_file, id_rank, sph_file)
Detailed Description
ASCII spectr data IO routines.
      subroutine read_geom_rtp_file                                   &
     &         (file_name, id_file, id_rank, sph_file)
      subroutine read_spectr_modes_rj_file                            &
     &         (file_name, id_rank, sph_file)
      subroutine read_geom_rtm_file                                   &
     &         (file_name, id_file, id_rank, sph_file)
      subroutine read_modes_rlm_file                                  &
     &         (file_name, id_file, id_rank, sph_file)
        type(sph_file_data_type), intent(inout) :: sph_file
      subroutine write_geom_rtp_file                                  &
     &         (file_name, id_file, id_rank, sph_file)
      subroutine write_spectr_modes_rj_file                           &
     &         (file_name, id_rank, sph_file)
      subroutine write_geom_rtm_file                                  &
     &         (file_name, id_file, id_rank, sph_file)
      subroutine write_modes_rlm_file                                 &
     &         (file_name, id_file, id_rank, sph_file)
        type(sph_file_data_type), intent(in) :: sph_file
Parameters
id_rank Process ID
file_name file name for IO (.gz is appended in this module)
Function/Subroutine Documentation
read_geom_rtm_file()
subroutine sph_modes_grids_file_io::read_geom_rtm_file (character(len=kchara), intent(in) file_name, integer(kind = kint), intent(in) id_file, integer, intent(in) id_rank, type(sph_file_data_type), intent(inout) sph_file, integer(kind = kint), intent(inout) ierr)
Definition at line 95 of file sph_modes_grids_file_IO.f90.
References m_machine_parameter::i_debug, and sph_modes_grids_data_io::read_geom_rtm_data().
Referenced by sph_file_io_select::sel_read_geom_rtm_file().
read_geom_rtp_file()
subroutine sph_modes_grids_file_io::read_geom_rtp_file (character(len=kchara), intent(in) file_name, integer(kind = kint), intent(in) id_file, integer, intent(in) id_rank, type(sph_file_data_type), intent(inout) sph_file, integer(kind = kint), intent(inout) ierr)
Definition at line 51 of file sph_modes_grids_file_IO.f90.
References m_machine_parameter::i_debug, and sph_modes_grids_data_io::read_geom_rtp_data().
Referenced by sph_file_io_select::sel_read_geom_rtp_file().
read_modes_rlm_file()
subroutine sph_modes_grids_file_io::read_modes_rlm_file (character(len=kchara), intent(in) file_name, integer(kind = kint), intent(in) id_file, integer, intent(in) id_rank, type(sph_file_data_type), intent(inout) sph_file, integer(kind = kint), intent(inout) ierr)
Definition at line 117 of file sph_modes_grids_file_IO.f90.
References m_machine_parameter::i_debug, and sph_modes_grids_data_io::read_spectr_modes_rlm_data().
Referenced by sph_file_io_select::sel_read_modes_rlm_file().
read_spectr_modes_rj_file()
subroutine sph_modes_grids_file_io::read_spectr_modes_rj_file (character(len=kchara), intent(in) file_name, integer(kind = kint), intent(in) id_file, integer, intent(in) id_rank, type(sph_file_data_type), intent(inout) sph_file, integer(kind = kint), intent(inout) ierr)
Definition at line 73 of file sph_modes_grids_file_IO.f90.
References m_machine_parameter::i_debug, and sph_modes_grids_data_io::read_spectr_modes_rj_data().
Referenced by sph_file_io_select::sel_read_spectr_rj_file().
write_geom_rtm_file()
subroutine sph_modes_grids_file_io::write_geom_rtm_file (character(len=kchara), intent(in) file_name, integer(kind = kint), intent(in) id_file, integer, intent(in) id_rank, type(sph_file_data_type), intent(in) sph_file)
Definition at line 181 of file sph_modes_grids_file_IO.f90.
References m_machine_parameter::i_debug, and sph_modes_grids_data_io::write_geom_rtm_data().
Referenced by sph_file_io_select::sel_write_geom_rtm_file().
write_geom_rtp_file()
subroutine sph_modes_grids_file_io::write_geom_rtp_file (character(len=kchara), intent(in) file_name, integer(kind = kint), intent(in) id_file, integer, intent(in) id_rank, type(sph_file_data_type), intent(in) sph_file)
Definition at line 141 of file sph_modes_grids_file_IO.f90.
References m_machine_parameter::i_debug, and sph_modes_grids_data_io::write_geom_rtp_data().
Referenced by sph_file_io_select::sel_write_geom_rtp_file().
write_modes_rlm_file()
subroutine sph_modes_grids_file_io::write_modes_rlm_file (character(len=kchara), intent(in) file_name, integer(kind = kint), intent(in) id_file, integer, intent(in) id_rank, type(sph_file_data_type), intent(in) sph_file)
Definition at line 201 of file sph_modes_grids_file_IO.f90.
References m_machine_parameter::i_debug, and sph_modes_grids_data_io::write_modes_rlm_data().
Referenced by sph_file_io_select::sel_write_modes_rlm_file().
write_spectr_modes_rj_file()
subroutine sph_modes_grids_file_io::write_spectr_modes_rj_file (character(len=kchara), intent(in) file_name, integer(kind = kint), intent(in) id_file, integer, intent(in) id_rank, type(sph_file_data_type), intent(in) sph_file)
Definition at line 161 of file sph_modes_grids_file_IO.f90.
References m_machine_parameter::i_debug, and sph_modes_grids_data_io::write_spectr_modes_rj_data().
Referenced by sph_file_io_select::sel_write_spectr_modes_rj_file().