CALYPSO: coef_fdm2_free_cmb Module Reference
coef_fdm2_free_cmb Module Reference
Matrix to evaluate poloidal velocity and toroidal vorticity at CMB with free slip boundary.
Functions/Subroutines
subroutine cal_fdm2_cmb_free_vp (r_from_CMB, fdm2_free_CMB)
subroutine cal_fdm2_cmb_free_vt (r_from_CMB, fdm2_free_CMB)
subroutine check_coef_fdm_free_cmb (fdm2_free_CMB)
Variables
real(kind=kreal), dimension(3, 3), private mat_fdm_cmb_free_vp
Work matrix to evaluate fdm2_free_CMBdmat_vp(-1:1,3)
real(kind=kreal), dimension(3, 3), private mat_fdm_cmb_free_vt
Work matrix to evaluate fdm2_free_CMBdmat_vt(-1:1,3)
Detailed Description
Matrix to evaluate poloidal velocity and toroidal vorticity at CMB with free slip boundary.
      subroutine cal_fdm2_CMB_free_vp(r_from_CMB, fdm2_free_CMB)
      subroutine cal_fdm2_CMB_free_vt(r_from_CMB, fdm2_free_CMB)
        type(fdm2_free_slip), intent(inout) :: fdm2_free_CMB
      subroutine check_coef_fdm_free_CMB(fdm2_free_CMB)
        type(fdm2_free_slip), intent(in) :: fdm2_free_CMB
    Matrix to evaluate radial derivative of poloidal velocity
    at CMB with free slip boundary
      dfdr =    fdm2_free_CMB%dmat_vp(-1,2) * d_rj(CMB-1)
              + fdm2_free_CMB%dmat_vp( 0,2) * d_rj(CMB  )
      d2fdr2 =  fdm2_free_CMB%dmat_vp(-1,3) * d_rj(CMB-1)
              + fdm2_free_CMB%dmat_vp( 0,3) * d_rj(CMB  )
    Matrix to evaluate radial derivative of toroidal vorticity
    at CMB with free slip boundary
      dfdr =    fdm2_free_CMB%dmat_vt( 0,2) * d_rj(CMB  )
      d2fdr2 =  fdm2_free_CMB%dmat_vt(-1,3) * d_rj(CMB-1)
              + fdm2_free_CMB%dmat_vt( 0,3) * d_rj(CMB  )
    Taylor expansion of free slip boundary at CMB
      dfdr =    mat_fdm_2(2,1) * d_rj(CMB  )
              + mat_fdm_2(2,2)
                 * (-2*dfdr(CMB) + r(CMB) * d2fdr2(CMB))
              + mat_fdm_2(2,3) * d_rj(CMB-1)
      d2fdr2 =  mat_fdm_2(3,1) * d_rj(CMB  )
              + mat_fdm_2(3,2)
                 * (-2*dfdr(CMB) + r(CMB) * d2fdr2(CMB))
              + mat_fdm_2(3,3) * d_rj(CMB-1)
Parameters
r_from_CMB(-3:0) radius from next points of CMB
Function/Subroutine Documentation
cal_fdm2_cmb_free_vp()
subroutine coef_fdm2_free_cmb::cal_fdm2_cmb_free_vp (real(kind = kreal), dimension(-1:0), intent(in) r_from_CMB, type(fdm2_free_slip), intent(inout) fdm2_free_CMB)
Definition at line 80 of file coef_fdm2_free_CMB.f90.
References cal_inverse_small_matrix::cal_inverse_33_matrix(), m_constants::half, mat_fdm_cmb_free_vp, m_constants::one, and m_constants::zero.
Referenced by set_bc_sph_mhd::s_set_bc_sph_mhd().
cal_fdm2_cmb_free_vt()
subroutine coef_fdm2_free_cmb::cal_fdm2_cmb_free_vt (real(kind = kreal), dimension(-1:0), intent(in) r_from_CMB, type(fdm2_free_slip), intent(inout) fdm2_free_CMB)
Definition at line 128 of file coef_fdm2_free_CMB.f90.
References cal_inverse_small_matrix::cal_inverse_33_matrix(), m_constants::half, mat_fdm_cmb_free_vt, m_constants::one, m_constants::two, and m_constants::zero.
Referenced by set_bc_sph_mhd::s_set_bc_sph_mhd().
check_coef_fdm_free_cmb()
subroutine coef_fdm2_free_cmb::check_coef_fdm_free_cmb (type(fdm2_free_slip), intent(in) fdm2_free_CMB)
Definition at line 176 of file coef_fdm2_free_CMB.f90.
References t_coef_fdm2_mhd_boundaries::check_coef_fdm_free_slip().
Referenced by set_bc_sph_mhd::s_set_bc_sph_mhd().
Variable Documentation
mat_fdm_cmb_free_vp
real(kind = kreal), dimension(3,3), private coef_fdm2_free_cmb::mat_fdm_cmb_free_vp private
Work matrix to evaluate fdm2_free_CMBdmat_vp(-1:1,3)
      dsdr =    mat_fdm_CMB_free_vp(2,1) * d_rj(ICB  )
              + mat_fdm_CMB_free_vp(2,3) * d_rj(ICB+1)
      dsfdr2 =  mat_fdm_CMB_free_vp(3,1) * d_rj(ICB  )
              + mat_fdm_CMB_free_vp(3,3) * d_rj(ICB+1)
Definition at line 61 of file coef_fdm2_free_CMB.f90.
Referenced by cal_fdm2_cmb_free_vp().
mat_fdm_cmb_free_vt
real(kind = kreal), dimension(3,3), private coef_fdm2_free_cmb::mat_fdm_cmb_free_vt private
Work matrix to evaluate fdm2_free_CMBdmat_vt(-1:1,3)
      dtdr =    mat_fdm_CMB_free_vt(2,1) * d_rj(ICB  )
              + mat_fdm_CMB_free_vt(2,3) * d_rj(ICB+1)
      dtfdr2 =  mat_fdm_CMB_free_vt(3,1) * d_rj(ICB  )
              + mat_fdm_CMB_free_vt(3,3) * d_rj(ICB+1)
Definition at line 70 of file coef_fdm2_free_CMB.f90.
Referenced by cal_fdm2_cmb_free_vt().