CALYPSO: t_read_control_elements Module Reference
t_read_control_elements Module Reference
Data Types
type buffer_for_control
Functions/Subroutines
subroutine load_one_line_from_control (id_control, c_buf)
character(len=kchara) function first_word (c_buf)
character(len=kchara) function second_word (c_buf)
character(len=kchara) function third_word (c_buf)
logical function check_begin_flag (c_buf, label)
logical function check_file_flag (c_buf, label)
logical function check_end_flag (c_buf, label)
logical function check_array_flag (c_buf, label)
logical function check_end_array_flag (c_buf, label)
subroutine monitor_read_control_label (c_buf)
subroutine monitor_read_control_buffer (c_buf)
subroutine set_control_labels (label_f, label_c)
Variables
character(len=kchara), parameter hd_begin = 'Begin'
Label to start a control block.
character(len=kchara), parameter hd_end = 'End'
Label to end a control block.
character(len=kchara), parameter hd_array = 'Array'
Label for an array control block.
character(len=kchara), parameter hd_file = 'File'
Label for an array control block.
Function/Subroutine Documentation
check_array_flag()
logical function t_read_control_elements::check_array_flag (type(buffer_for_control), intent(in) c_buf, character(len=kchara), intent(in) label)
Definition at line 175 of file t_read_control_elements.f90.
References skip_comment_f::cmp_no_case(), first_word(), hd_array, and second_word().
Referenced by t_control_array_character::read_control_array_c1(), t_control_array_character2::read_control_array_c2(), t_control_array_chara2real::read_control_array_c2_r(), t_control_array_character3::read_control_array_c3(), t_control_array_charaint::read_control_array_c_i(), t_control_array_charaint3::read_control_array_c_i3(), t_control_array_charareal::read_control_array_c_r(), t_control_array_charareal2::read_control_array_c_r2(), t_control_array_integer::read_control_array_i1(), t_control_array_integer2::read_control_array_i2(), t_control_array_int2real::read_control_array_i2_r(), t_control_array_int2real2::read_control_array_i2_r2(), t_control_array_integer3::read_control_array_i3(), t_control_array_intcharreal::read_control_array_i_c_r(), t_control_array_intreal::read_control_array_i_r(), t_control_array_real::read_control_array_r1(), t_control_array_real2::read_control_array_r2(), t_control_array_real3::read_control_array_r3(), t_ctl_data_4_sph_monitor::read_sph_monitoring_ctl(), and t_control_data_surfacings::read_surfacing_controls().
check_begin_flag()
logical function t_read_control_elements::check_begin_flag (type(buffer_for_control), intent(in) c_buf, character(len=kchara), intent(in) label)
Definition at line 124 of file t_read_control_elements.f90.
References skip_comment_f::cmp_no_case(), first_word(), hd_begin, and second_word().
Referenced by t_ctl_data_node_boundary::read_bc_4_node_ctl(), t_ctl_data_surf_boundary::read_bc_4_surf_ctl(), t_ctl_data_mhd_normalize::read_coef_term_ctl(), t_ctl_data_termal_norm::read_composition_eq_ctl(), t_ctl_data_4_platforms::read_control_platforms(), t_ctl_data_4_sphere_model::read_control_shell_define(), t_ctl_data_4_divide_sphere::read_control_shell_domain(), t_ctl_data_4_time_steps::read_control_time_step_data(), t_ctl_data_mhd_forces::read_coriolis_ctl(), t_ctl_data_crust_filter::read_crustal_filtering_ctl(), t_ctl_data_gen_sph_shell::read_ctl_file_gen_shell_grids(), t_ctl_data_mhd_normalize::read_dimless_ctl(), t_control_data_dynamo_vizs::read_dynamo_viz_control(), t_ctl_data_sph_vol_spectr::read_each_vol_spectr_ctl(), t_ctl_data_4_fem_mesh::read_fem_mesh_control(), t_control_data_isosurfaces::read_files_4_iso_ctl(), t_control_data_sections::read_files_4_psf_ctl(), t_control_data_4_fld_on_psf::read_fld_on_psf_control(), t_ctl_data_mhd_forces::read_forces_ctl(), t_ctl_data_pick_sph_spectr::read_gauss_spectr_ctl(), t_ctl_data_mhd_forces::read_gravity_ctl(), t_ctl_data_induct_norm::read_induction_ctl(), t_ctl_data_sph_vol_spectr::read_layerd_spectr_ctl(), t_ctl_data_mhd_forces::read_magneto_ctl(), t_control_data_4_merge::read_merge_control_data(), t_control_data_4_merge::read_merge_field_data(), t_control_data_4_merge::read_merge_step_data(), t_ctl_data_mhd_evolution::read_mhd_layer_ctl(), t_ctl_data_mhd_evolution::read_mhd_time_evo_ctl(), t_mid_equator_control::read_mid_eq_monitor_ctl(), t_ctl_data_momentum_norm::read_momentum_ctl(), t_ctl_data_node_monitor::read_monitor_data_ctl(), t_control_data_4_merge::read_newrst_control(), t_ctl_data_gen_sph_shell::read_parallel_shell_in_mhd_ctl(), t_ctl_data_4_fields::read_phys_data_control(), t_ctl_data_pick_sph_spectr::read_pickup_spectr_ctl(), t_control_data_4_psf::read_psf_control_data(), t_ctl_data_temp_model::read_ref_comp_ctl(), t_ctl_data_temp_model::read_ref_temp_ctl(), t_ctl_data_temp_model::read_refcomp_ctl(), t_ctl_data_temp_model::read_reftemp_ctl(), t_ctl_data_mhd_evo_scheme::read_restart_ctl(), t_control_data_section_only::read_section_control_data(), t_control_data_dynamo_vizs::read_single_section_ctl(), t_ctl_data_sph_mhd_control::read_sph_mhd_control(), t_ctl_data_mhd::read_sph_mhd_ctl_noviz(), t_ctl_data_mhd::read_sph_mhd_ctl_w_psf(), t_ctl_data_mhd_model::read_sph_mhd_model(), t_ctl_data_4_sph_monitor::read_sph_monitoring_ctl(), t_ctl_data_const_sph_mesh::read_sph_shell_define_ctl(), t_control_data_surfacings::read_surfacing_controls(), t_ctl_data_temp_model::read_takepiro_ctl(), t_ctl_data_termal_norm::read_thermal_ctl(), and t_ctl_data_mhd_evo_scheme::read_time_loop_ctl().
check_end_array_flag()
logical function t_read_control_elements::check_end_array_flag (type(buffer_for_control), intent(in) c_buf, character(len=kchara), intent(in) label)
Definition at line 199 of file t_read_control_elements.f90.
References skip_comment_f::cmp_no_case(), first_word(), hd_array, hd_end, second_word(), and third_word().
Referenced by t_control_array_character::read_control_array_c1(), t_control_array_character2::read_control_array_c2(), t_control_array_chara2real::read_control_array_c2_r(), t_control_array_character3::read_control_array_c3(), t_control_array_charaint::read_control_array_c_i(), t_control_array_charaint3::read_control_array_c_i3(), t_control_array_charareal::read_control_array_c_r(), t_control_array_charareal2::read_control_array_c_r2(), t_control_array_integer::read_control_array_i1(), t_control_array_integer2::read_control_array_i2(), t_control_array_int2real::read_control_array_i2_r(), t_control_array_int2real2::read_control_array_i2_r2(), t_control_array_integer3::read_control_array_i3(), t_control_array_intcharreal::read_control_array_i_c_r(), t_control_array_intreal::read_control_array_i_r(), t_control_array_real::read_control_array_r1(), t_control_array_real2::read_control_array_r2(), t_control_array_real3::read_control_array_r3(), t_control_data_isosurfaces::read_files_4_iso_ctl(), t_control_data_sections::read_files_4_psf_ctl(), and t_ctl_data_4_sph_monitor::read_volume_spectr_ctl().
check_end_flag()
logical function t_read_control_elements::check_end_flag (type(buffer_for_control), intent(in) c_buf, character(len=kchara), intent(in) label)
Definition at line 158 of file t_read_control_elements.f90.
References skip_comment_f::cmp_no_case(), first_word(), hd_end, and second_word().
Referenced by t_ctl_data_node_boundary::read_bc_4_node_ctl(), t_ctl_data_surf_boundary::read_bc_4_surf_ctl(), t_ctl_data_mhd_normalize::read_coef_term_ctl(), t_ctl_data_termal_norm::read_composition_eq_ctl(), t_ctl_data_4_platforms::read_control_platforms(), t_ctl_data_4_sphere_model::read_control_shell_define(), t_ctl_data_4_divide_sphere::read_control_shell_domain(), t_ctl_data_4_time_steps::read_control_time_step_data(), t_ctl_data_mhd_forces::read_coriolis_ctl(), t_ctl_data_crust_filter::read_crustal_filtering_ctl(), t_ctl_data_mhd_normalize::read_dimless_ctl(), t_control_data_dynamo_vizs::read_dynamo_viz_control(), t_ctl_data_sph_vol_spectr::read_each_vol_spectr_ctl(), t_ctl_data_4_fem_mesh::read_fem_mesh_control(), t_control_data_4_fld_on_psf::read_fld_on_psf_control(), t_ctl_data_mhd_forces::read_forces_ctl(), t_ctl_data_pick_sph_spectr::read_gauss_spectr_ctl(), t_ctl_data_mhd_forces::read_gravity_ctl(), t_ctl_data_induct_norm::read_induction_ctl(), t_ctl_data_sph_vol_spectr::read_layerd_spectr_ctl(), t_ctl_data_mhd_forces::read_magneto_ctl(), t_control_data_4_merge::read_merge_control_data(), t_control_data_4_merge::read_merge_field_data(), t_control_data_4_merge::read_merge_step_data(), t_ctl_data_mhd_evolution::read_mhd_layer_ctl(), t_ctl_data_mhd_evolution::read_mhd_time_evo_ctl(), t_mid_equator_control::read_mid_eq_monitor_ctl(), t_ctl_data_momentum_norm::read_momentum_ctl(), t_ctl_data_node_monitor::read_monitor_data_ctl(), t_control_data_4_merge::read_newrst_control(), t_ctl_data_gen_sph_shell::read_parallel_shell_ctl(), t_ctl_data_4_fields::read_phys_data_control(), t_ctl_data_pick_sph_spectr::read_pickup_spectr_ctl(), t_control_data_4_psf::read_psf_control_data(), t_ctl_data_temp_model::read_ref_comp_ctl(), t_ctl_data_temp_model::read_ref_temp_ctl(), t_ctl_data_temp_model::read_refcomp_ctl(), t_ctl_data_temp_model::read_reftemp_ctl(), t_ctl_data_mhd_evo_scheme::read_restart_ctl(), t_control_data_section_only::read_section_control_data(), t_control_data_4_psf_def::read_section_def_control(), t_ctl_data_sph_mhd_control::read_sph_mhd_control(), t_ctl_data_mhd::read_sph_mhd_ctl_noviz(), t_ctl_data_mhd::read_sph_mhd_ctl_w_psf(), t_ctl_data_mhd_model::read_sph_mhd_model(), t_ctl_data_4_sph_monitor::read_sph_monitoring_ctl(), t_ctl_data_const_sph_mesh::read_sph_shell_define_ctl(), t_control_data_surfacings::read_surfacing_controls(), t_ctl_data_temp_model::read_takepiro_ctl(), t_ctl_data_termal_norm::read_thermal_ctl(), and t_ctl_data_mhd_evo_scheme::read_time_loop_ctl().
check_file_flag()
logical function t_read_control_elements::check_file_flag (type(buffer_for_control), intent(in) c_buf, character(len=kchara), intent(in) label)
Definition at line 141 of file t_read_control_elements.f90.
References skip_comment_f::cmp_no_case(), first_word(), hd_file, and second_word().
Referenced by t_control_data_isosurfaces::read_files_4_iso_ctl(), t_control_data_sections::read_files_4_psf_ctl(), t_ctl_data_gen_sph_shell::read_parallel_shell_in_mhd_ctl(), and t_control_data_dynamo_vizs::read_single_section_ctl().
first_word()
character(len = kchara) function t_read_control_elements::first_word (type(buffer_for_control), intent(in) c_buf)
Definition at line 76 of file t_read_control_elements.f90.
Referenced by check_array_flag(), check_begin_flag(), check_end_array_flag(), check_end_flag(), check_file_flag(), and load_one_line_from_control().
load_one_line_from_control()
subroutine t_read_control_elements::load_one_line_from_control (integer(kind = kint), intent(in) id_control, type(buffer_for_control), intent(inout) c_buf)
Definition at line 60 of file t_read_control_elements.f90.
References first_word(), and skip_comment_f::skip_comment().
Referenced by t_ctl_data_node_boundary::read_bc_4_node_ctl(), t_ctl_data_surf_boundary::read_bc_4_surf_ctl(), t_ctl_data_mhd_normalize::read_coef_term_ctl(), t_ctl_data_termal_norm::read_composition_eq_ctl(), t_ctl_data_const_sph_mesh::read_control_4_const_shell(), t_control_data_isosurfaces::read_control_4_iso_file(), t_control_data_4_merge::read_control_4_merge(), t_control_data_sections::read_control_4_psf_file(), t_ctl_data_sph_mhd_psf::read_control_4_sph_mhd_noviz(), t_ctl_data_sph_mhd_psf::read_control_4_sph_mhd_w_psf(), t_control_array_character::read_control_array_c1(), t_control_array_character2::read_control_array_c2(), t_control_array_chara2real::read_control_array_c2_r(), t_control_array_character3::read_control_array_c3(), t_control_array_charaint::read_control_array_c_i(), t_control_array_charaint3::read_control_array_c_i3(), t_control_array_charareal::read_control_array_c_r(), t_control_array_charareal2::read_control_array_c_r2(), t_control_array_integer::read_control_array_i1(), t_control_array_integer2::read_control_array_i2(), t_control_array_int2real::read_control_array_i2_r(), t_control_array_int2real2::read_control_array_i2_r2(), t_control_array_integer3::read_control_array_i3(), t_control_array_intcharreal::read_control_array_i_c_r(), t_control_array_intreal::read_control_array_i_r(), t_control_array_real::read_control_array_r1(), t_control_array_real2::read_control_array_r2(), t_control_array_real3::read_control_array_r3(), t_control_data_4_merge::read_control_assemble_sph(), t_control_data_section_only::read_control_data_section_only(), t_ctl_data_4_platforms::read_control_platforms(), t_ctl_data_4_sphere_model::read_control_shell_define(), t_ctl_data_4_divide_sphere::read_control_shell_domain(), t_ctl_data_4_time_steps::read_control_time_step_data(), t_ctl_data_mhd_forces::read_coriolis_ctl(), t_ctl_data_crust_filter::read_crustal_filtering_ctl(), t_ctl_data_gen_sph_shell::read_ctl_file_gen_shell_grids(), t_ctl_data_mhd_normalize::read_dimless_ctl(), t_control_data_dynamo_vizs::read_dynamo_viz_control(), t_ctl_data_sph_vol_spectr::read_each_vol_spectr_ctl(), t_ctl_data_4_fem_mesh::read_fem_mesh_control(), t_control_data_isosurfaces::read_files_4_iso_ctl(), t_control_data_sections::read_files_4_psf_ctl(), t_control_data_4_fld_on_psf::read_fld_on_psf_control(), t_ctl_data_mhd_forces::read_forces_ctl(), t_ctl_data_pick_sph_spectr::read_gauss_spectr_ctl(), t_ctl_data_mhd_forces::read_gravity_ctl(), t_ctl_data_induct_norm::read_induction_ctl(), t_ctl_data_sph_vol_spectr::read_layerd_spectr_ctl(), t_ctl_data_mhd_forces::read_magneto_ctl(), t_control_data_4_merge::read_merge_control_data(), t_control_data_4_merge::read_merge_field_data(), t_control_data_4_merge::read_merge_step_data(), t_ctl_data_mhd_evolution::read_mhd_layer_ctl(), t_ctl_data_mhd_evolution::read_mhd_time_evo_ctl(), t_mid_equator_control::read_mid_eq_monitor_ctl(), t_ctl_data_momentum_norm::read_momentum_ctl(), t_ctl_data_node_monitor::read_monitor_data_ctl(), t_control_data_4_merge::read_newrst_control(), t_ctl_data_gen_sph_shell::read_parallel_shell_ctl(), t_ctl_data_4_fields::read_phys_data_control(), t_ctl_data_pick_sph_spectr::read_pickup_spectr_ctl(), t_control_data_4_psf::read_psf_control_data(), t_ctl_data_temp_model::read_ref_comp_ctl(), t_ctl_data_temp_model::read_ref_temp_ctl(), t_ctl_data_temp_model::read_refcomp_ctl(), t_ctl_data_temp_model::read_reftemp_ctl(), t_ctl_data_mhd_evo_scheme::read_restart_ctl(), t_control_data_section_only::read_section_control_data(), t_control_data_4_psf_def::read_section_def_control(), t_ctl_data_sph_mhd_control::read_sph_mhd_control(), t_ctl_data_mhd::read_sph_mhd_ctl_noviz(), t_ctl_data_mhd::read_sph_mhd_ctl_w_psf(), t_ctl_data_mhd_model::read_sph_mhd_model(), t_ctl_data_4_sph_monitor::read_sph_monitoring_ctl(), t_ctl_data_const_sph_mesh::read_sph_shell_define_ctl(), t_control_data_surfacings::read_surfacing_controls(), t_ctl_data_temp_model::read_takepiro_ctl(), t_ctl_data_termal_norm::read_thermal_ctl(), t_ctl_data_mhd_evo_scheme::read_time_loop_ctl(), and t_ctl_data_4_sph_monitor::read_volume_spectr_ctl().
monitor_read_control_buffer()
subroutine t_read_control_elements::monitor_read_control_buffer (type(buffer_for_control), intent(in) c_buf)
Definition at line 230 of file t_read_control_elements.f90.
monitor_read_control_label()
subroutine t_read_control_elements::monitor_read_control_label (type(buffer_for_control), intent(in) c_buf)
Definition at line 219 of file t_read_control_elements.f90.
second_word()
character(len = kchara) function t_read_control_elements::second_word (type(buffer_for_control), intent(in) c_buf)
Definition at line 91 of file t_read_control_elements.f90.
Referenced by check_array_flag(), check_begin_flag(), check_end_array_flag(), check_end_flag(), and check_file_flag().
set_control_labels()
subroutine t_read_control_elements::set_control_labels (character(len = kchara), intent(in) label_f, character(len = kchara), intent(inout) label_c)
Definition at line 242 of file t_read_control_elements.f90.
Referenced by m_file_format_labels::set_label_file_fmt(), t_control_data_4_fld_on_psf::set_label_fld_on_psf_control(), t_control_params_4_iso::set_label_iso_type(), m_section_coef_flags::set_label_psf_coefs(), t_control_data_4_psf::set_label_psf_ctl(), t_control_data_4_psf::set_label_psf_ctl_w_dpl(), set_coefs_of_sections::set_label_psf_def_type_grp(), t_control_data_4_psf_def::set_label_psf_define_control(), m_section_coef_flags::set_label_psf_dirs(), and t_ctl_data_4_time_steps::set_label_time_step_ctl().
third_word()
character(len = kchara) function t_read_control_elements::third_word (type(buffer_for_control), intent(in) c_buf)
Definition at line 107 of file t_read_control_elements.f90.
Referenced by check_end_array_flag(), t_control_data_isosurfaces::read_files_4_iso_ctl(), t_control_data_sections::read_files_4_psf_ctl(), t_ctl_data_gen_sph_shell::read_parallel_shell_in_mhd_ctl(), and t_control_data_dynamo_vizs::read_single_section_ctl().
Variable Documentation
hd_array
character(len=kchara), parameter t_read_control_elements::hd_array = 'Array'
Label for an array control block.
Definition at line 43 of file t_read_control_elements.f90.
Referenced by check_array_flag(), and check_end_array_flag().
hd_begin
character(len=kchara), parameter t_read_control_elements::hd_begin = 'Begin'
Label to start a control block.
Definition at line 39 of file t_read_control_elements.f90.
Referenced by check_begin_flag().
hd_end
character(len=kchara), parameter t_read_control_elements::hd_end = 'End'
Label to end a control block.
Definition at line 41 of file t_read_control_elements.f90.
Referenced by check_end_array_flag(), and check_end_flag().
hd_file
character(len=kchara), parameter t_read_control_elements::hd_file = 'File'
Label for an array control block.
Definition at line 45 of file t_read_control_elements.f90.
Referenced by check_file_flag().