CALYPSO: mpi_gen_sph_grids_modes Module Reference
mpi_gen_sph_grids_modes Module Reference
Main loop to generate spherical harmonics indices.
Functions/Subroutines
subroutine const_sph_global_parameters (gen_sph, sph)
subroutine mpi_gen_sph_grids (gen_sph, sph_tmp, sph, comms_sph, sph_grp)
subroutine mpi_gen_sph_rj_mode (gen_sph, sph_tmp, sph, comms_sph, sph_grp)
Detailed Description
Main loop to generate spherical harmonics indices.
      subroutine const_sph_global_parameters(gen_sph, sph)
        type(construct_spherical_grid), intent(inout) :: gen_sph
        type(sph_grids), intent(inout) :: sph
      subroutine mpi_gen_sph_grids(gen_sph, sph, comms_sph, sph_grp)
      subroutine mpi_gen_sph_rj_mode(gen_sph, sph, comms_sph, sph_grp)
        type(construct_spherical_grid), intent(inout) :: gen_sph
        type(sph_grids), intent(inout) :: sph
        type(sph_comm_tables), intent(inout) :: comms_sph
        type(sph_group_data), intent(inout) :: sph_grp
Function/Subroutine Documentation
const_sph_global_parameters()
subroutine mpi_gen_sph_grids_modes::const_sph_global_parameters (type(construct_spherical_grid), intent(inout) gen_sph, type(sph_grids), intent(inout) sph)
Parameters
[in,out] sph Structure of grid and spectr data for spherical spectr method
Definition at line 44 of file mpi_gen_sph_grids_modes.f90.
References t_spheric_parameter::check_global_spheric_parameter(), calypso_mpi::my_rank, const_sph_radial_grid::output_set_radial_grid(), const_global_sph_grids_modes::s_const_global_sph_grids_modes(), and set_global_spherical_param::set_global_sph_resolution().
Referenced by mpi_gen_sph_grids(), mpi_gen_sph_rj_mode(), parallel_gen_sph_grids::para_gen_sph_grids(), and parallel_gen_sph_grids::para_gen_sph_rj_mode().
mpi_gen_sph_grids()
subroutine mpi_gen_sph_grids_modes::mpi_gen_sph_grids (type(construct_spherical_grid), intent(inout) gen_sph, type(sph_grids), intent(inout) sph_tmp, type(sph_grids), intent(inout) sph, type(sph_comm_tables), intent(inout) comms_sph, type(sph_group_data), intent(inout) sph_grp)
Parameters
[in,out] sph_tmp Structure of grid and spectr data for spherical spectr method
[in,out] sph Structure of grid and spectr data for spherical spectr method
[in,out] comms_sph Structure of communication table for spherical spectr method
[in,out] sph_grp Structure of group data for spherical spectr method
Structure for parallel spherical mesh table
Structure for parallel spherical mesh table
Definition at line 79 of file mpi_gen_sph_grids_modes.f90.
References calypso_mpi::calypso_mpi_barrier(), const_sph_global_parameters(), set_comm_table_rtp_rj::const_sph_rj_modes(), gen_sph_grids_modes::const_sph_rlm_modes(), gen_sph_grids_modes::const_sph_rtm_grids(), set_comm_table_rtp_rj::const_sph_rtp_grids(), copy_para_sph_global_params::copy_each_global_sph_resolution(), copy_para_sph_global_params::copy_each_sph_param_from_ctl(), t_sph_trans_comm_tbl::copy_sph_comm_neib(), bcast_comm_stacks_sph::dealloc_comm_stacks_sph(), t_const_spherical_grid::dealloc_gen_mesh_params(), m_work_time::end_elapsed_time(), m_machine_parameter::iflag_debug, m_elapsed_labels_gen_sph::iflag_gsp_time, m_elapsed_labels_gen_sph::ist_elapsed_gsp, bcast_comm_stacks_sph::mpi_bcast_comm_stacks_sph(), calypso_mpi::my_rank, calypso_mpi::nprocs, and m_work_time::start_elapsed_time().
Referenced by analyzer_check_sph_grids::analyze_check_sph_grids(), analyzer_gen_sph_grids::analyze_gen_sph_grids(), t_check_and_make_sph_mesh::check_and_make_sph_mesh(), and t_check_and_make_sph_mesh::check_and_make_sph_rj_mode().
mpi_gen_sph_rj_mode()
subroutine mpi_gen_sph_grids_modes::mpi_gen_sph_rj_mode (type(construct_spherical_grid), intent(inout) gen_sph, type(sph_grids), intent(inout) sph_tmp, type(sph_grids), intent(inout) sph, type(sph_comm_tables), intent(inout) comms_sph, type(sph_group_data), intent(inout) sph_grp)
Parameters
[in,out] sph_tmp Structure of grid and spectr data for spherical spectr method
[in,out] sph Structure of grid and spectr data for spherical spectr method
[in,out] comms_sph Structure of communication table for spherical spectr method
[in,out] sph_grp Structure of group data for spherical spectr method
Structure for parallel spherical mesh table
Definition at line 190 of file mpi_gen_sph_grids_modes.f90.
References const_sph_global_parameters(), set_comm_table_rtp_rj::const_sph_rj_modes(), gen_sph_grids_modes::const_sph_rlm_modes(), copy_para_sph_global_params::copy_each_global_sph_resolution(), copy_para_sph_global_params::copy_each_sph_param_from_ctl(), t_sph_trans_comm_tbl::copy_sph_comm_neib(), bcast_comm_stacks_sph::dealloc_comm_stacks_sph(), t_const_spherical_grid::dealloc_gen_mesh_params(), m_work_time::end_elapsed_time(), m_machine_parameter::iflag_debug, m_elapsed_labels_gen_sph::iflag_gsp_time, m_elapsed_labels_gen_sph::ist_elapsed_gsp, bcast_comm_stacks_sph::mpi_bcast_comm_stacks_sph(), calypso_mpi::my_rank, calypso_mpi::nprocs, and m_work_time::start_elapsed_time().