CALYPSO: t_set_legendre_4_sph_trans Module Reference
t_set_legendre_4_sph_trans Module Reference
Set Legendre polynomials into matrix.
Data Types
type work_make_legendre
Functions/Subroutines
subroutine alloc_cal_legendre_work (l_truncation, wk_plm)
subroutine dealloc_cal_legendre_work (wk_plm)
subroutine set_each_sym_leg_omp_mat_tj (sph_rlm, mm, jst_rlm, nlt, g_colat_rtm, n_jk_e, n_jk_o, Pse_tj, dPsedt_tj, Pso_tj, dPsodt_tj, wk_plm)
subroutine set_each_sym_leg_omp_mat_jt (sph_rlm, mm, jst_rlm, nlt, g_colat_rtm, n_jk_e, n_jk_o, Pse_jt, dPsedt_jt, Pso_jt, dPsodt_jt, wk_plm)
subroutine set_each_sym_leg_omp_mat_j1 (sph_rlm, mm, jst_rlm, g_colat_rtm, n_jk_e, n_jk_o, Pse_jt, dPsedt_jt, Pso_jt, dPsodt_jt, wk_plm)
subroutine copy_each_sym_leg_omp_mat_jt (nth_rtm, jmax_rlm, jst_rlm, P_rtm, dPdt_rtm, lst_rtm, nle_rtm, n_jk_e, n_jk_o, Pse_jt, dPsedt_jt, Pso_jt, dPsodt_jt)
subroutine copy_each_sym_leg_omp_mat_tj (nth_rtm, jmax_rlm, jst_rlm, P_rtm, dPdt_rtm, lst_rtm, nle_rtm, n_jk_e, n_jk_o, Pse_tj, dPsedt_tj, Pso_tj, dPsodt_tj)
Detailed Description
Set Legendre polynomials into matrix.
      subroutine alloc_cal_legendre_work(l_truncation, wk_plm)
      subroutine dealloc_cal_legendre_work(wk_plm)
        type(work_make_legendre), intent(inout) :: wk_plm
      subroutine set_each_sym_leg_omp_mat_tj                          &
     &        (sph_rlm, mm, jst_rlm, nlt, g_colat_rtm, n_jk_e, n_jk_o,&
     &         Pse_tj, dPsedt_tj, Pso_tj, dPsodt_tj, wk_plm)
        type(sph_rlm_grid), intent(in) :: sph_rlm
        type(work_make_legendre), intent(inout) :: wk_plm
      subroutine set_each_sym_leg_omp_mat_jt                          &
     &        (sph_rlm, mm, jst_rlm, nlt, g_colat_rtm, n_jk_e, n_jk_o,&
     &         Pse_jt, dPsedt_jt, Pso_jt, dPsodt_jt, wk_plm)
        type(sph_rlm_grid), intent(in) :: sph_rlm
        type(work_make_legendre), intent(inout) :: wk_plm
      subroutine set_each_sym_leg_omp_mat_j1                          &
     &        (sph_rlm, mm, jst_rlm, g_colat_rtm, n_jk_e, n_jk_o,     &
     &         Pse_jt, dPsedt_jt, Pso_jt, dPsodt_jt, wk_plm)
        type(sph_rlm_grid), intent(in) :: sph_rlm
        type(work_make_legendre), intent(inout) :: wk_plm
      subroutine copy_each_sym_leg_omp_mat_jt                         &
     &         (nth_rtm, jmax_rlm, jst_rlm, P_rtm, dPdt_rtm,          &
     &          lst_rtm, nle_rtm, n_jk_e, n_jk_o,                     &
     &          Pse_jt, dPsedt_jt, Pso_jt, dPsodt_jt)
      subroutine copy_each_sym_leg_omp_mat_tj                         &
     &         (nth_rtm, jmax_rlm, jst_rlm, P_rtm, dPdt_rtm,          &
     &          lst_rtm, nle_rtm, n_jk_e, n_jk_o,                     &
     &          Pse_tj, dPsedt_tj, Pso_tj, dPsodt_tj)
Function/Subroutine Documentation
alloc_cal_legendre_work()
subroutine t_set_legendre_4_sph_trans::alloc_cal_legendre_work (integer(kind = kint), intent(in) l_truncation, type(work_make_legendre), intent(inout) wk_plm)
Definition at line 69 of file t_set_legendre_4_sph_trans.f90.
Referenced by t_legendre_work_testlooop::init_legendre_sym_mat_both(), and t_legendre_work_on_the_fly::init_legendre_sym_mat_otfly().
copy_each_sym_leg_omp_mat_jt()
subroutine t_set_legendre_4_sph_trans::copy_each_sym_leg_omp_mat_jt (integer(kind = kint), intent(in) nth_rtm, integer(kind = kint), intent(in) jmax_rlm, integer(kind = kint), intent(in) jst_rlm, real(kind= kreal), dimension(nth_rtm,jmax_rlm), intent(in) P_rtm, real(kind= kreal), dimension(nth_rtm,jmax_rlm), intent(in) dPdt_rtm, integer(kind = kint), intent(in) lst_rtm, integer(kind = kint), intent(in) nle_rtm, integer(kind = kint), intent(in) n_jk_e, integer(kind = kint), intent(in) n_jk_o, real(kind = kreal), dimension(n_jk_e,nle_rtm), intent(inout) Pse_jt, real(kind = kreal), dimension(n_jk_e,nle_rtm), intent(inout) dPsedt_jt, real(kind = kreal), dimension(n_jk_o,nle_rtm), intent(inout) Pso_jt, real(kind = kreal), dimension(n_jk_o,nle_rtm), intent(inout) dPsodt_jt)
Definition at line 246 of file t_set_legendre_4_sph_trans.f90.
Referenced by t_legendre_work_sym_mat_jt::init_each_sym_leg_omp_mat_jt().
copy_each_sym_leg_omp_mat_tj()
subroutine t_set_legendre_4_sph_trans::copy_each_sym_leg_omp_mat_tj (integer(kind = kint), intent(in) nth_rtm, integer(kind = kint), intent(in) jmax_rlm, integer(kind = kint), intent(in) jst_rlm, real(kind= kreal), dimension(nth_rtm,jmax_rlm), intent(in) P_rtm, real(kind= kreal), dimension(nth_rtm,jmax_rlm), intent(in) dPdt_rtm, integer(kind = kint), intent(in) lst_rtm, integer(kind = kint), intent(in) nle_rtm, integer(kind = kint), intent(in) n_jk_e, integer(kind = kint), intent(in) n_jk_o, real(kind = kreal), dimension(nle_rtm,n_jk_e), intent(inout) Pse_tj, real(kind = kreal), dimension(nle_rtm,n_jk_e), intent(inout) dPsedt_tj, real(kind = kreal), dimension(nle_rtm,n_jk_o), intent(inout) Pso_tj, real(kind = kreal), dimension(nle_rtm,n_jk_o), intent(inout) dPsodt_tj)
Definition at line 288 of file t_set_legendre_4_sph_trans.f90.
Referenced by t_legendre_work_sym_mat_jt::init_each_sym_leg_omp_mat_tj().
dealloc_cal_legendre_work()
subroutine t_set_legendre_4_sph_trans::dealloc_cal_legendre_work (type(work_make_legendre), intent(inout) wk_plm)
Definition at line 94 of file t_set_legendre_4_sph_trans.f90.
Referenced by t_legendre_work_testlooop::dealloc_leg_sym_mat_both(), and t_legendre_work_on_the_fly::dealloc_leg_sym_mat_otfly().
set_each_sym_leg_omp_mat_j1()
subroutine t_set_legendre_4_sph_trans::set_each_sym_leg_omp_mat_j1 (type(sph_rlm_grid), intent(in) sph_rlm, integer(kind = kint), intent(in) mm, integer(kind = kint), intent(in) jst_rlm, real(kind= kreal), intent(in) g_colat_rtm, integer(kind = kint), intent(in) n_jk_e, integer(kind = kint), intent(in) n_jk_o, real(kind = kreal), dimension(n_jk_e), intent(inout) Pse_jt, real(kind = kreal), dimension(n_jk_e), intent(inout) dPsedt_jt, real(kind = kreal), dimension(n_jk_o), intent(inout) Pso_jt, real(kind = kreal), dimension(n_jk_o), intent(inout) dPsodt_jt, type(work_make_legendre), intent(inout) wk_plm)
Definition at line 200 of file t_set_legendre_4_sph_trans.f90.
References schmidt_fix_m::schmidt_legendres_m().
Referenced by leg_fwd_trans_on_the_fly::leg_fwd_trans_1latitude(), legendre_fwd_trans_testloop::leg_fwd_trans_1latitude(), leg_fwd_trans_on_the_fly::leg_fwd_trans_at_equator(), and legendre_fwd_trans_testloop::leg_fwd_trans_at_equator().
set_each_sym_leg_omp_mat_jt()
subroutine t_set_legendre_4_sph_trans::set_each_sym_leg_omp_mat_jt (type(sph_rlm_grid), intent(in) sph_rlm, integer(kind = kint), intent(in) mm, integer(kind = kint), intent(in) jst_rlm, integer(kind = kint), intent(in) nlt, real(kind= kreal), dimension(nlt), intent(in) g_colat_rtm, integer(kind = kint), intent(in) n_jk_e, integer(kind = kint), intent(in) n_jk_o, real(kind = kreal), dimension(n_jk_e,nlt), intent(inout) Pse_jt, real(kind = kreal), dimension(n_jk_e,nlt), intent(inout) dPsedt_jt, real(kind = kreal), dimension(n_jk_o,nlt), intent(inout) Pso_jt, real(kind = kreal), dimension(n_jk_o,nlt), intent(inout) dPsodt_jt, type(work_make_legendre), intent(inout) wk_plm)
Definition at line 153 of file t_set_legendre_4_sph_trans.f90.
References schmidt_fix_m::schmidt_legendres_m().
set_each_sym_leg_omp_mat_tj()
subroutine t_set_legendre_4_sph_trans::set_each_sym_leg_omp_mat_tj (type(sph_rlm_grid), intent(in) sph_rlm, integer(kind = kint), intent(in) mm, integer(kind = kint), intent(in) jst_rlm, integer(kind = kint), intent(in) nlt, real(kind= kreal), dimension(nlt), intent(in) g_colat_rtm, integer(kind = kint), intent(in) n_jk_e, integer(kind = kint), intent(in) n_jk_o, real(kind = kreal), dimension(nlt,n_jk_e), intent(inout) Pse_tj, real(kind = kreal), dimension(nlt,n_jk_e), intent(inout) dPsedt_tj, real(kind = kreal), dimension(nlt,n_jk_o), intent(inout) Pso_tj, real(kind = kreal), dimension(nlt,n_jk_o), intent(inout) dPsodt_tj, type(work_make_legendre), intent(inout) wk_plm)
Definition at line 106 of file t_set_legendre_4_sph_trans.f90.
References schmidt_fix_m::schmidt_legendres_m().
Referenced by leg_fwd_trans_on_the_fly::leg_fwd_trans_2latitude(), legendre_fwd_trans_testloop::leg_fwd_trans_2latitude(), leg_fwd_trans_on_the_fly::leg_fwd_trans_4latitude(), legendre_fwd_trans_testloop::leg_fwd_trans_4latitude(), leg_fwd_trans_on_the_fly::leg_fwd_trans_8latitude(), and legendre_fwd_trans_testloop::leg_fwd_trans_8latitude().