CALYPSO: set_sp_rlm_leg_sym_matmul Module Reference
set_sp_rlm_leg_sym_matmul Module Reference
Set spectrum data for backward Legendre transform.
Functions/Subroutines
subroutine set_sp_rlm_vector_sym_matmul (nnod_rlm, nidx_rlm, istep_rlm, idx_gl_1d_rlm_j, a_r_1d_rlm_r, g_sph_rlm, kst, nkr, jst, n_jk_e, n_jk_o, ncomp, irev_sr_rlm, n_WR, WR, pol_e, dpoldt_e, dpoldp_e, dtordt_e, dtordp_e, pol_o, dpoldt_o, dpoldp_o, dtordt_o, dtordp_o)
subroutine set_sp_rlm_scalar_sym_matmul (nnod_rlm, nidx_rlm, istep_rlm, kst, nkr, jst, n_jk_e, n_jk_o, ncomp, nvector, irev_sr_rlm, n_WR, WR, scl_e, scl_o)
subroutine cal_sp_rlm_vector_sym_matmul (nnod_rlm, nidx_rlm, istep_rlm, idx_gl_1d_rlm_j, radius_1d_rlm_r, g_sph_rlm, kst, nkr, jst, n_jk_o, n_jk_e, pol_e, pol_o, dpoldt_e, dpoldp_e, dpoldt_o, dpoldp_o, dtordt_e, dtordp_e, dtordt_o, dtordp_o, ncomp, irev_sr_rlm, n_WS, WS)
subroutine cal_sp_rlm_scalar_sym_matmul (nnod_rlm, nidx_rlm, istep_rlm, g_sph_rlm, kst, nkr, jst, n_jk_o, n_jk_e, scl_e, scl_o, ncomp, nvector, irev_sr_rlm, n_WS, WS)
Detailed Description
Set spectrum data for backward Legendre transform.
      subroutine set_sp_rlm_vector_sym_matmul(nnod_rlm, nidx_rlm,     &
     &          istep_rlm, idx_gl_1d_rlm_j, a_r_1d_rlm_r, g_sph_rlm,  &
     &          kst, nkr, jst,  n_jk_e, n_jk_o,                       &
     &          ncomp, irev_sr_rlm, n_WR, WR,                         &
     &          pol_e, dpoldt_e, dpoldp_e, dtordt_e, dtordp_e,        &
     &          pol_o, dpoldt_o, dpoldp_o, dtordt_o, dtordp_o)
      subroutine set_sp_rlm_scalar_sym_matmul                         &
     &         (nnod_rlm, nidx_rlm, istep_rlm,                        &
     &          kst, nkr, jst, n_jk_e, n_jk_o,                        &
     &          ncomp, nvector, irev_sr_rlm, n_WR, WR, scl_e, scl_o)
      subroutine cal_sp_rlm_vector_sym_matmul(nnod_rlm, nidx_rlm,     &
     &         istep_rlm, idx_gl_1d_rlm_j, radius_1d_rlm_r, g_sph_rlm,&
     &         kst, nkr, jst, n_jk_o, n_jk_e,                         &
     &         pol_e, pol_o, dpoldt_e, dpoldp_e, dpoldt_o, dpoldp_o,  &
     &         dtordt_e, dtordp_e, dtordt_o, dtordp_o,                &
     &         ncomp, irev_sr_rlm, n_WS, WS)
      subroutine cal_sp_rlm_scalar_sym_matmul                         &
     &         (nnod_rlm, nidx_rlm, istep_rlm, g_sph_rlm,             &
     &          kst, nkr, jst, n_jk_o, n_jk_e, scl_e, scl_o,          &
     &          ncomp, nvector, irev_sr_rlm, n_WS, WS)
Function/Subroutine Documentation
cal_sp_rlm_scalar_sym_matmul()
subroutine set_sp_rlm_leg_sym_matmul::cal_sp_rlm_scalar_sym_matmul (integer(kind = kint), intent(in) nnod_rlm, integer(kind = kint), dimension(2), intent(in) nidx_rlm, integer(kind = kint), dimension(2), intent(in) istep_rlm, real(kind = kreal), dimension(nidx_rlm(2),17), intent(in) g_sph_rlm, integer(kind = kint), intent(in) kst, integer(kind = kint), intent(in) nkr, integer(kind = kint), intent(in) jst, integer(kind = kint), intent(in) n_jk_o, integer(kind = kint), intent(in) n_jk_e, real(kind = kreal), dimension(nkr,n_jk_e), intent(inout) scl_e, real(kind = kreal), dimension(nkr,n_jk_o), intent(inout) scl_o, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), dimension(nnod_rlm), intent(in) irev_sr_rlm, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 298 of file set_sp_rlm_leg_sym_matmul.f90.
Referenced by legendre_fwd_sym_matmul::leg_f_trans_scl_sym_matmul().
cal_sp_rlm_vector_sym_matmul()
subroutine set_sp_rlm_leg_sym_matmul::cal_sp_rlm_vector_sym_matmul (integer(kind = kint), intent(in) nnod_rlm, integer(kind = kint), dimension(2), intent(in) nidx_rlm, integer(kind = kint), dimension(2), intent(in) istep_rlm, integer(kind = kint), dimension(nidx_rlm(2),3), intent(in) idx_gl_1d_rlm_j, real(kind = kreal), dimension(nidx_rlm(1)), intent(in) radius_1d_rlm_r, real(kind = kreal), dimension(nidx_rlm(2),17), intent(in) g_sph_rlm, integer(kind = kint), intent(in) kst, integer(kind = kint), intent(in) nkr, integer(kind = kint), intent(in) jst, integer(kind = kint), intent(in) n_jk_o, integer(kind = kint), intent(in) n_jk_e, real(kind = kreal), dimension(nkr,n_jk_e), intent(inout) pol_e, real(kind = kreal), dimension(nkr,n_jk_o), intent(inout) pol_o, real(kind = kreal), dimension(nkr,n_jk_e), intent(inout) dpoldt_e, real(kind = kreal), dimension(nkr,n_jk_e), intent(inout) dpoldp_e, real(kind = kreal), dimension(nkr,n_jk_o), intent(inout) dpoldt_o, real(kind = kreal), dimension(nkr,n_jk_o), intent(inout) dpoldp_o, real(kind = kreal), dimension(nkr,n_jk_e), intent(inout) dtordt_e, real(kind = kreal), dimension(nkr,n_jk_e), intent(inout) dtordp_e, real(kind = kreal), dimension(nkr,n_jk_o), intent(inout) dtordt_o, real(kind = kreal), dimension(nkr,n_jk_o), intent(inout) dtordp_o, integer(kind = kint), intent(in) ncomp, integer(kind = kint), dimension(nnod_rlm), intent(in) irev_sr_rlm, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 174 of file set_sp_rlm_leg_sym_matmul.f90.
Referenced by legendre_fwd_sym_matmul::leg_f_trans_vec_sym_matmul().
set_sp_rlm_scalar_sym_matmul()
subroutine set_sp_rlm_leg_sym_matmul::set_sp_rlm_scalar_sym_matmul (integer(kind = kint), intent(in) nnod_rlm, integer(kind = kint), dimension(2), intent(in) nidx_rlm, integer(kind = kint), dimension(2), intent(in) istep_rlm, integer(kind = kint), intent(in) kst, integer(kind = kint), intent(in) nkr, integer(kind = kint), intent(in) jst, integer(kind = kint), intent(in) n_jk_e, integer(kind = kint), intent(in) n_jk_o, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), dimension(nnod_rlm), intent(in) irev_sr_rlm, integer(kind = kint), intent(in) n_WR, real(kind = kreal), dimension(n_wr), intent(in) WR, real(kind = kreal), dimension(n_jk_e,nkr), intent(inout) scl_e, real(kind = kreal), dimension(n_jk_o,nkr), intent(inout) scl_o)
Definition at line 126 of file set_sp_rlm_leg_sym_matmul.f90.
Referenced by legendre_bwd_sym_matmul::leg_b_trans_scl_sym_matmul().
set_sp_rlm_vector_sym_matmul()
subroutine set_sp_rlm_leg_sym_matmul::set_sp_rlm_vector_sym_matmul (integer(kind = kint), intent(in) nnod_rlm, integer(kind = kint), dimension(2), intent(in) nidx_rlm, integer(kind = kint), dimension(2), intent(in) istep_rlm, integer(kind = kint), dimension(nidx_rlm(2),3), intent(in) idx_gl_1d_rlm_j, real(kind = kreal), dimension(nidx_rlm(1)), intent(in) a_r_1d_rlm_r, real(kind = kreal), dimension(nidx_rlm(2),17), intent(in) g_sph_rlm, integer(kind = kint), intent(in) kst, integer(kind = kint), intent(in) nkr, integer(kind = kint), intent(in) jst, integer(kind = kint), intent(in) n_jk_e, integer(kind = kint), intent(in) n_jk_o, integer(kind = kint), intent(in) ncomp, integer(kind = kint), dimension(nnod_rlm), intent(in) irev_sr_rlm, integer(kind = kint), intent(in) n_WR, real(kind = kreal), dimension(n_wr), intent(in) WR, real(kind = kreal), dimension(n_jk_e,nkr), intent(inout) pol_e, real(kind = kreal), dimension(n_jk_e,nkr), intent(inout) dpoldt_e, real(kind = kreal), dimension(n_jk_e,nkr), intent(inout) dpoldp_e, real(kind = kreal), dimension(n_jk_e,nkr), intent(inout) dtordt_e, real(kind = kreal), dimension(n_jk_e,nkr), intent(inout) dtordp_e, real(kind = kreal), dimension(n_jk_o,nkr), intent(inout) pol_o, real(kind = kreal), dimension(n_jk_o,nkr), intent(inout) dpoldt_o, real(kind = kreal), dimension(n_jk_o,nkr), intent(inout) dpoldp_o, real(kind = kreal), dimension(n_jk_o,nkr), intent(inout) dtordt_o, real(kind = kreal), dimension(n_jk_o,nkr), intent(inout) dtordp_o)
Definition at line 46 of file set_sp_rlm_leg_sym_matmul.f90.
Referenced by legendre_bwd_sym_matmul::leg_b_trans_vec_sym_matmul().