CALYPSO: set_sph_bc_data_by_file Module Reference
set_sph_bc_data_by_file Module Reference
Boundary condition data from external file.
Functions/Subroutines
subroutine set_fixed_vector_bc_by_file (field, sph_rj, bc_IO, ref_grp, iflag_bc_vector, bc_Vspec)
subroutine set_evolved_vector_bc_by_file (field, sph_rj, bc_IO, ref_grp, iflag_bc_vector, bc_Vevo)
subroutine set_fixed_scalar_bc_by_file (field, sph_rj, bc_IO, ref_grp, iflag_bc_scalar, bc_Sspec)
subroutine set_evolved_scalar_bc_by_file (field, sph_rj, bc_IO, ref_grp, iflag_bc_scalar, bc_Sevo)
subroutine set_fixed_grad_bc_by_file (flux, sph_rj, bc_IO, ref_grp, iflag_bc_scalar, bc_Sspec)
subroutine set_evolved_grad_bc_by_file (flux, sph_rj, bc_IO, ref_grp, iflag_bc_scalar, bc_Sevo)
Detailed Description
Boundary condition data from external file.
      subroutine set_fixed_vector_bc_by_file(field, sph_rj,           &
     &          bc_IO, ref_grp, iflag_bc_vector, bc_Vspec)
      subroutine set_evolved_vector_bc_by_file(field, sph_rj, bc_IO,  &
     &          ref_grp, iflag_bc_vector, bc_Vevo)
              type(boundary_spectra), intent(in) :: bc_IO
              type(sph_rj_grid), intent(in) :: sph_rj
              type(field_def), intent(in) :: field
      subroutine set_fixed_scalar_bc_by_file(field, sph_rj, bc_IO,    &
     &          ref_grp, iflag_bc_scalar, bc_Sspec)
      subroutine set_evolved_scalar_bc_by_file(field, sph_rj, bc_IO,  &
     &          ref_grp, iflag_bc_scalar, bc_Sevo)
              type(boundary_spectra), intent(in) :: bc_IO
              type(sph_rj_grid), intent(in) :: sph_rj
              type(field_def), intent(in) :: field
      subroutine set_fixed_grad_bc_by_file(flux, sph_rj, bc_IO,       &
     &          ref_grp, iflag_bc_scalar, bc_Sspec)
      subroutine set_evolved_grad_bc_by_file(flux, sph_rj, bc_IO,     &
     &          ref_grp, iflag_bc_scalar, bc_Sevo)
        type(boundary_spectra), intent(in) :: bc_IO
        type(sph_rj_grid), intent(in) :: sph_rj
        type(field_def), intent(in) :: flux
        type(sph_vector_BC_coef), intent(inout) :: bc_Vspec
        type(sph_vector_BC_evo), intent(inout) :: bc_Vevo
        type(sph_scalar_BC_coef), intent(inout) :: bc_Sspec
        type(sph_scalar_BC_evo), intent(inout) :: bc_Sevo
Function/Subroutine Documentation
set_evolved_grad_bc_by_file()
subroutine set_sph_bc_data_by_file::set_evolved_grad_bc_by_file (type(field_def), intent(in) flux, type(sph_rj_grid), intent(in) sph_rj, type(boundary_spectra), intent(in) bc_IO, character(len=kchara), intent(in) ref_grp, integer(kind = kint), intent(inout) iflag_bc_scalar, type(sph_scalar_bc_evo), intent(inout) bc_Sevo)
Definition at line 251 of file set_sph_bc_data_by_file.f90.
References t_each_sph_boundary_io_data::bc_4_evo_scalar_sph_by_file(), skip_comment_f::cmp_no_case(), set_sph_boundary_from_file::find_bc_label(), set_sph_boundary_from_file::freq1_label, set_sph_boundary_from_file::freq2_label, set_sph_boundary_from_file::mag_label, and set_sph_boundary_from_file::phase_label.
Referenced by set_bc_sph_scalars::inner_sph_bc_scalar_sph(), and set_bc_sph_scalars::outer_sph_bc_scalar_sph().
set_evolved_scalar_bc_by_file()
subroutine set_sph_bc_data_by_file::set_evolved_scalar_bc_by_file (type(field_def), intent(in) field, type(sph_rj_grid), intent(in) sph_rj, type(boundary_spectra), intent(in) bc_IO, character(len=kchara), intent(in) ref_grp, integer(kind = kint), intent(inout) iflag_bc_scalar, type(sph_scalar_bc_evo), intent(inout) bc_Sevo)
Definition at line 170 of file set_sph_bc_data_by_file.f90.
References t_each_sph_boundary_io_data::bc_4_evo_scalar_sph_by_file(), skip_comment_f::cmp_no_case(), set_sph_boundary_from_file::find_bc_label(), set_sph_boundary_from_file::freq1_label, set_sph_boundary_from_file::freq2_label, set_sph_boundary_from_file::mag_label, and set_sph_boundary_from_file::phase_label.
Referenced by set_bc_sph_scalars::inner_sph_bc_scalar_sph(), and set_bc_sph_scalars::outer_sph_bc_scalar_sph().
set_evolved_vector_bc_by_file()
subroutine set_sph_bc_data_by_file::set_evolved_vector_bc_by_file (type(field_def), intent(in) field, type(sph_rj_grid), intent(in) sph_rj, type(boundary_spectra), intent(in) bc_IO, character(len=kchara), intent(in) ref_grp, integer(kind = kint), intent(inout) iflag_bc_vector, type(sph_vector_bc_evo), intent(inout) bc_Vevo)
Definition at line 88 of file set_sph_bc_data_by_file.f90.
References t_each_sph_boundary_io_data::bc_4_evo_vect2_sph_by_file(), t_each_sph_boundary_io_data::bc_4_evo_vector_sph_by_file(), skip_comment_f::cmp_no_case(), set_sph_boundary_from_file::find_bc_label(), set_sph_boundary_from_file::freq1_label, set_sph_boundary_from_file::freq2_label, set_sph_boundary_from_file::mag_label, and set_sph_boundary_from_file::phase_label.
Referenced by set_bc_sph_mhd::set_sph_bc_magne_sph(), set_bc_flag_sph_velo::set_sph_velo_cmb_flag(), and set_bc_flag_sph_velo::set_sph_velo_icb_flag().
set_fixed_grad_bc_by_file()
subroutine set_sph_bc_data_by_file::set_fixed_grad_bc_by_file (type(field_def), intent(in) flux, type(sph_rj_grid), intent(in) sph_rj, type(boundary_spectra), intent(in) bc_IO, character(len=kchara), intent(in) ref_grp, integer(kind = kint), intent(inout) iflag_bc_scalar, type(sph_scalar_bc_coef), intent(inout) bc_Sspec)
Definition at line 218 of file set_sph_bc_data_by_file.f90.
References skip_comment_f::cmp_no_case(), and t_each_sph_boundary_io_data::set_bc_4_sph_scalar_by_file().
Referenced by set_bc_sph_scalars::inner_sph_bc_scalar_sph(), and set_bc_sph_scalars::outer_sph_bc_scalar_sph().
set_fixed_scalar_bc_by_file()
subroutine set_sph_bc_data_by_file::set_fixed_scalar_bc_by_file (type(field_def), intent(in) field, type(sph_rj_grid), intent(in) sph_rj, type(boundary_spectra), intent(in) bc_IO, character(len=kchara), intent(in) ref_grp, integer(kind = kint), intent(inout) iflag_bc_scalar, type(sph_scalar_bc_coef), intent(inout) bc_Sspec)
Definition at line 137 of file set_sph_bc_data_by_file.f90.
References skip_comment_f::cmp_no_case(), and t_each_sph_boundary_io_data::set_bc_4_sph_scalar_by_file().
Referenced by set_bc_sph_scalars::inner_sph_bc_scalar_sph(), and set_bc_sph_scalars::outer_sph_bc_scalar_sph().
set_fixed_vector_bc_by_file()
subroutine set_sph_bc_data_by_file::set_fixed_vector_bc_by_file (type(field_def), intent(in) field, type(sph_rj_grid), intent(in) sph_rj, type(boundary_spectra), intent(in) bc_IO, character(len=kchara), intent(in) ref_grp, integer(kind = kint), intent(inout) iflag_bc_vector, type(sph_vector_bc_coef), intent(inout) bc_Vspec)
Definition at line 55 of file set_sph_bc_data_by_file.f90.
References skip_comment_f::cmp_no_case(), and t_each_sph_boundary_io_data::set_bc_4_sph_vector_by_file().
Referenced by set_bc_sph_mhd::set_sph_bc_magne_sph(), set_bc_flag_sph_velo::set_sph_velo_cmb_flag(), and set_bc_flag_sph_velo::set_sph_velo_icb_flag().