CALYPSO: check_base_field Module Reference
check_base_field Module Reference
Functions/Subroutines
subroutine add_field_ctl_4_base_field (field_ctl)
subroutine add_field_ctl_4_grad_field (field_ctl)
subroutine add_field_ctl_4_diff_vector (field_ctl)
Function/Subroutine Documentation
add_field_ctl_4_base_field()
subroutine check_base_field::add_field_ctl_4_base_field (type(ctl_array_c3), intent(inout) field_ctl)
Definition at line 32 of file check_base_field.f90.
References add_nodal_fields_ctl::add_phys_name_ctl(), add_nodal_fields_ctl::check_field_list_ctl(), m_base_field_labels::composition, m_base_field_labels::composition_source, m_base_field_labels::current_density, m_base_field_labels::density, m_base_field_labels::entropy, m_base_field_labels::entropy_source, m_base_field_labels::heat_source, m_base_field_labels::magnetic_field, m_base_field_labels::magnetic_potential, m_base_field_labels::perturbation_composition, m_base_field_labels::perturbation_density, m_base_field_labels::perturbation_entropy, m_base_field_labels::perturbation_temp, m_base_field_labels::pressure, m_base_field_labels::reference_composition, m_base_field_labels::reference_density, m_base_field_labels::reference_entropy, m_base_field_labels::reference_temperature, m_base_field_labels::scalar_potential, m_base_field_labels::temperature, m_base_field_labels::vector_potential, m_base_field_labels::velocity, and m_base_field_labels::vorticity.
Referenced by add_nodal_fields_4_mhd::add_dependent_field().
add_field_ctl_4_diff_vector()
subroutine check_base_field::add_field_ctl_4_diff_vector (type(ctl_array_c3), intent(inout) field_ctl)
Definition at line 149 of file check_base_field.f90.
References add_nodal_fields_ctl::add_phys_name_ctl(), add_nodal_fields_ctl::check_field_list_ctl(), m_base_field_labels::current_density, m_diff_vector_labels::grad_a_1, m_diff_vector_labels::grad_a_2, m_diff_vector_labels::grad_a_3, m_diff_vector_labels::grad_b_1, m_diff_vector_labels::grad_b_2, m_diff_vector_labels::grad_b_3, m_diff_vector_labels::grad_j_1, m_diff_vector_labels::grad_j_2, m_diff_vector_labels::grad_j_3, m_diff_vector_labels::grad_v_1, m_diff_vector_labels::grad_v_2, m_diff_vector_labels::grad_v_3, m_diff_vector_labels::grad_w_1, m_diff_vector_labels::grad_w_2, m_diff_vector_labels::grad_w_3, m_base_field_labels::magnetic_field, m_base_field_labels::vector_potential, m_base_field_labels::velocity, and m_base_field_labels::vorticity.
Referenced by add_nodal_fields_4_mhd::add_dependent_field().
add_field_ctl_4_grad_field()
subroutine check_base_field::add_field_ctl_4_grad_field (type(ctl_array_c3), intent(inout) field_ctl)
Definition at line 101 of file check_base_field.f90.
References add_nodal_fields_ctl::add_phys_name_ctl(), add_nodal_fields_ctl::check_field_list_ctl(), m_base_field_labels::composition, m_base_field_labels::density, m_grad_field_labels::div_magnetic, m_grad_field_labels::div_vector_potential, m_grad_field_labels::div_velocity, m_base_field_labels::entropy, m_grad_field_labels::grad_composition, m_grad_field_labels::grad_density, m_grad_field_labels::grad_entropy, m_grad_field_labels::grad_pert_composition, m_grad_field_labels::grad_pert_density, m_grad_field_labels::grad_pert_entropy, m_grad_field_labels::grad_pert_temp, m_grad_field_labels::grad_reference_composition, m_grad_field_labels::grad_reference_density, m_grad_field_labels::grad_reference_entropy, m_grad_field_labels::grad_reference_temp, m_grad_field_labels::grad_temp, m_base_field_labels::magnetic_field, m_base_field_labels::perturbation_composition, m_base_field_labels::perturbation_density, m_base_field_labels::perturbation_entropy, m_base_field_labels::perturbation_temp, m_base_field_labels::reference_composition, m_base_field_labels::reference_density, m_base_field_labels::reference_entropy, m_base_field_labels::reference_temperature, m_base_field_labels::temperature, m_base_field_labels::vector_potential, and m_base_field_labels::velocity.
Referenced by add_nodal_fields_4_mhd::add_dependent_field().