CALYPSO: t_cross_section Module Reference
t_cross_section Module Reference
Structure for cross sectioning.
Data Types
type sectioning_module
Functions/Subroutines
subroutine sectioning_initialize (fem, nod_fld, psf_ctls, psf)
subroutine sectioning_visualize (istep_psf, time_d, fem, nod_fld, psf)
subroutine, private alloc_psf_field_type (psf)
subroutine dealloc_psf_field_type (psf)
Detailed Description
Structure for cross sectioning.
      subroutine SECTIONING_initialize(fem, nod_fld, psf_ctls, psf)
        type(mesh_data), intent(in) :: fem
        type(phys_data), intent(in) :: nod_fld
      subroutine SECTIONING_visualize                                 &
     &         (istep_psf, time_d, fem, nod_fld, psf)
        type(time_data), intent(in) :: time_d
        type(mesh_data), intent(in) :: fem
        type(phys_data), intent(in) :: nod_fld
      subroutine dealloc_psf_field_type(psf)
Function/Subroutine Documentation
alloc_psf_field_type()
subroutine, private t_cross_section::alloc_psf_field_type (type(sectioning_module), intent(inout) psf) private
Definition at line 194 of file t_cross_section.f90.
References t_control_params_4_psf::alloc_coefficients_4_psf(), and m_field_file_format::iflag_sgl_udt.
Referenced by sectioning_initialize().
dealloc_psf_field_type()
subroutine t_cross_section::dealloc_psf_field_type (type(sectioning_module), intent(inout) psf)
Definition at line 222 of file t_cross_section.f90.
References t_control_params_4_psf::dealloc_coefficients_4_psf(), t_psf_geometry_list::dealloc_inod_grp_psf(), t_psf_case_table::dealloc_psf_case_table(), set_fields_for_psf::dealloc_psf_field_data(), set_psf_iso_control::dealloc_psf_field_name(), find_node_and_patch_psf::dealloc_psf_node_and_patch(), and t_ucd_data::disconnect_merged_ucd_mesh().
sectioning_initialize()
subroutine t_cross_section::sectioning_initialize (type(mesh_data), intent(in) fem, type(phys_data), intent(in) nod_fld, type(section_controls), intent(inout) psf_ctls, type(sectioning_module), intent(inout) psf)
Definition at line 87 of file t_cross_section.f90.
References set_fields_for_psf::alloc_psf_field_data(), alloc_psf_field_type(), t_psf_geometry_list::alloc_ref_field_4_psf(), m_work_time::end_elapsed_time(), m_machine_parameter::iflag_debug, m_elapsed_labels_4_viz::iflag_psf_time, t_psf_case_table::init_psf_case_tables(), m_elapsed_labels_4_viz::ist_elapsed_psf, output_4_psf::output_section_mesh(), set_const_4_sections::set_const_4_crossections(), find_node_and_patch_psf::set_node_and_patch_psf(), set_psf_iso_control::set_psf_control(), search_ele_list_for_psf::set_search_mesh_list_4_psf(), and m_work_time::start_elapsed_time().
Referenced by t_viz_sections::init_visualize_surface(), and t_sph_mhd_zonal_mean_viz::init_zonal_mean_sections().
sectioning_visualize()
subroutine t_cross_section::sectioning_visualize (integer(kind = kint), intent(in) istep_psf, type(time_data), intent(in) time_d, type(mesh_data), intent(in) fem, type(phys_data), intent(in) nod_fld, type(sectioning_module), intent(inout) psf)
Definition at line 158 of file t_cross_section.f90.
References m_work_time::end_elapsed_time(), m_machine_parameter::iflag_debug, m_elapsed_labels_4_viz::iflag_psf_time, m_elapsed_labels_4_viz::ist_elapsed_psf, output_4_psf::output_section_data(), set_fields_for_psf::set_field_4_psf(), and m_work_time::start_elapsed_time().
Referenced by t_sph_mhd_zonal_mean_viz::sph_mhd_zonal_mean_section(), t_sph_mhd_zonal_mean_viz::sph_mhd_zonal_rms_section(), and t_viz_sections::visualize_surface().