CALYPSO: t_rayleigh_restart_io Module Reference
t_rayleigh_restart_io Module Reference
Structure of Rayleigh paramters.
Data Types
type rayleigh_restart
Structure for Rayleigh restart data.
Functions/Subroutines
subroutine alloc_rayleigh_radial_grid (ra_rst)
subroutine dealloc_rayleigh_radial_grid (ra_rst)
subroutine check_rayleigh_rst_params (id_file, ra_rst)
subroutine read_rayleigh_restart_params (dir, i_step, ra_rst)
character(len=kchara) function set_rayleigh_file_name (dir, int_id, postfix)
Variables
character(len=kchara), parameter paramchar = "grid_etc"
character(len=kchara), parameter wchar = "W"
character(len=kchara), parameter zchar = "Z"
character(len=kchara), parameter pchar = "P"
character(len=kchara), parameter tchar = "T"
character(len=kchara), parameter cchar = "C"
character(len=kchara), parameter achar = "A"
character(len=kchara), parameter wabchar = "WAB"
character(len=kchara), parameter zabchar = "ZAB"
character(len=kchara), parameter pabchar = "PAB"
character(len=kchara), parameter tabchar = "TAB"
character(len=kchara), parameter cabchar = "CAB"
character(len=kchara), parameter aabchar = "AAB"
Detailed Description
Structure of Rayleigh paramters.
      subroutine alloc_rayleigh_radial_grid(ra_rst)
      subroutine dealloc_rayleigh_radial_grid(ra_rst)
        type(rayleigh_restart), intent(inout) :: ra_rst
      subroutine check_rayleigh_rst_params(id_file, ra_rst)
        type(rayleigh_restart), intent(in) :: ra_rst
      subroutine read_rayleigh_restart_params(dir, i_step, ra_rst)
        type(rayleigh_restart), intent(inout) :: ra_rst
      character(len = kchara) function set_rayleigh_file_name         &
     &                               (dir, int_id, postfix)
          Version 1.x:  "[dir]/[int_id]/[field_flag]"
Function/Subroutine Documentation
alloc_rayleigh_radial_grid()
subroutine t_rayleigh_restart_io::alloc_rayleigh_radial_grid (type(rayleigh_restart), intent(inout) ra_rst)
Definition at line 93 of file t_rayleigh_restart_IO.f90.
Referenced by read_rayleigh_restart_params().
check_rayleigh_rst_params()
subroutine t_rayleigh_restart_io::check_rayleigh_rst_params (integer, intent(in) id_file, type(rayleigh_restart), intent(in) ra_rst)
Definition at line 114 of file t_rayleigh_restart_IO.f90.
dealloc_rayleigh_radial_grid()
subroutine t_rayleigh_restart_io::dealloc_rayleigh_radial_grid (type(rayleigh_restart), intent(inout) ra_rst)
Definition at line 104 of file t_rayleigh_restart_IO.f90.
read_rayleigh_restart_params()
subroutine t_rayleigh_restart_io::read_rayleigh_restart_params (character(len = kchara), intent(in) dir, integer(kind = kint), intent(in) i_step, type(rayleigh_restart), intent(inout) ra_rst)
Definition at line 141 of file t_rayleigh_restart_IO.f90.
References alloc_rayleigh_radial_grid(), byte_swap_f::byte_swap_int4_f(), byte_swap_f::byte_swap_real_f(), m_machine_parameter::iendian_flip, m_machine_parameter::iendian_keep, paramchar, and set_rayleigh_file_name().
Referenced by rayleigh_restart_io::sel_read_rayleigh_rst_params().
set_rayleigh_file_name()
character(len = kchara) function t_rayleigh_restart_io::set_rayleigh_file_name (character(len=kchara), intent(in) dir, integer(kind = kint), intent(in) int_id, character(len=kchara), intent(in) postfix)
Definition at line 222 of file t_rayleigh_restart_IO.f90.
Referenced by read_rayleigh_restart_params(), and rayleigh_restart_io::sel_rayleigh_file_name().
Variable Documentation
aabchar
character(len = kchara), parameter t_rayleigh_restart_io::aabchar = "AAB"
Definition at line 49 of file t_rayleigh_restart_IO.f90.
Referenced by rayleigh_restart_io::set_rayleigh_restart_field(), and rayleigh_restart_io::set_rayleigh_rst_file_name().
achar
character(len = kchara), parameter t_rayleigh_restart_io::achar = "A"
Definition at line 41 of file t_rayleigh_restart_IO.f90.
Referenced by rayleigh_restart_io::set_rayleigh_restart_field(), and rayleigh_restart_io::set_rayleigh_rst_file_name().
cabchar
character(len = kchara), parameter t_rayleigh_restart_io::cabchar = "CAB"
Definition at line 48 of file t_rayleigh_restart_IO.f90.
Referenced by rayleigh_restart_io::set_rayleigh_restart_field(), and rayleigh_restart_io::set_rayleigh_rst_file_name().
cchar
character(len = kchara), parameter t_rayleigh_restart_io::cchar = "C"
Definition at line 40 of file t_rayleigh_restart_IO.f90.
Referenced by rayleigh_restart_io::set_rayleigh_restart_field(), and rayleigh_restart_io::set_rayleigh_rst_file_name().
pabchar
character(len = kchara), parameter t_rayleigh_restart_io::pabchar = "PAB"
Definition at line 45 of file t_rayleigh_restart_IO.f90.
paramchar
character(len = kchara), parameter t_rayleigh_restart_io::paramchar = "grid_etc"
Definition at line 33 of file t_rayleigh_restart_IO.f90.
Referenced by read_rayleigh_restart_params().
pchar
character(len = kchara), parameter t_rayleigh_restart_io::pchar = "P"
Definition at line 37 of file t_rayleigh_restart_IO.f90.
Referenced by rayleigh_restart_io::set_rayleigh_restart_field(), and rayleigh_restart_io::set_rayleigh_rst_file_name().
tabchar
character(len = kchara), parameter t_rayleigh_restart_io::tabchar = "TAB"
Definition at line 46 of file t_rayleigh_restart_IO.f90.
Referenced by rayleigh_restart_io::set_rayleigh_restart_field(), and rayleigh_restart_io::set_rayleigh_rst_file_name().
tchar
character(len = kchara), parameter t_rayleigh_restart_io::tchar = "T"
Definition at line 38 of file t_rayleigh_restart_IO.f90.
Referenced by rayleigh_restart_io::set_rayleigh_restart_field(), and rayleigh_restart_io::set_rayleigh_rst_file_name().
wabchar
character(len = kchara), parameter t_rayleigh_restart_io::wabchar = "WAB"
Definition at line 43 of file t_rayleigh_restart_IO.f90.
Referenced by rayleigh_restart_io::set_rayleigh_restart_field(), and rayleigh_restart_io::set_rayleigh_rst_file_name().
wchar
character(len = kchara), parameter t_rayleigh_restart_io::wchar = "W"
Definition at line 35 of file t_rayleigh_restart_IO.f90.
Referenced by rayleigh_restart_io::set_rayleigh_restart_field(), and rayleigh_restart_io::set_rayleigh_rst_file_name().
zabchar
character(len = kchara), parameter t_rayleigh_restart_io::zabchar = "ZAB"
Definition at line 44 of file t_rayleigh_restart_IO.f90.
Referenced by rayleigh_restart_io::set_rayleigh_restart_field(), and rayleigh_restart_io::set_rayleigh_rst_file_name().
zchar
character(len = kchara), parameter t_rayleigh_restart_io::zchar = "Z"
Definition at line 36 of file t_rayleigh_restart_IO.f90.
Referenced by rayleigh_restart_io::set_rayleigh_restart_field(), and rayleigh_restart_io::set_rayleigh_rst_file_name().