CALYPSO: gz_mesh_data_io Module Reference
gz_mesh_data_io Module Reference
gzipped mesh data IO routines
Functions/Subroutines
subroutine gz_write_geometry_data (id_rank, mesh_IO, zbuf)
subroutine gz_write_mesh_groups (mesh_group_IO, zbuf)
subroutine gz_write_filter_geometry (id_rank, comm_IO, nod_IO, zbuf)
subroutine gz_read_num_node (id_rank, mesh_IO, zbuf, ierr)
subroutine gz_read_num_node_ele (id_rank, mesh_IO, zbuf, ierr)
subroutine gz_read_geometry_data (id_rank, mesh_IO, zbuf, ierr)
subroutine gz_read_mesh_groups (mesh_group_IO, zbuf)
subroutine gz_read_filter_geometry (id_rank, comm_IO, nod_IO, zbuf, ierr)
Detailed Description
gzipped mesh data IO routines
      subroutine gz_write_geometry_data(id_rank, mesh_IO, zbuf)
      subroutine gz_write_mesh_groups(mesh_group_IO, zbuf)
        type(mesh_geometry), intent(in) :: mesh_IO
        type(mesh_groups), intent(in) ::   mesh_group_IO
        type(buffer_4_gzip), intent(inout) :: zbuf
      subroutine gz_read_num_node(id_rank, mesh_IO, zbuf, ierr)
      subroutine gz_read_num_node_ele(id_rank, mesh_IO, zbuf, ierr)
      subroutine gz_read_geometry_data(id_rank, mesh_IO, zbuf, ierr)
      subroutine gz_read_mesh_groups(mesh_group_IO, zbuf)
        type(mesh_geometry), intent(inout) :: mesh_IO
        type(mesh_groups), intent(inout) ::   mesh_group_IO
        type(buffer_4_gzip), intent(inout) :: zbuf
      subroutine gz_write_filter_geometry                             &
     &         (id_rank, comm_IO, nod_IO, zbuf)
        type(communication_table), intent(in) :: comm_IO
        type(node_data), intent(in) :: nod_IO
        type(buffer_4_gzip), intent(inout) :: zbuf
      subroutine gz_read_filter_geometry                              &
      &         (id_rank, comm_IO, nod_IO, zbuf, ierr)
        type(communication_table), intent(inout) :: comm_IO
        type(node_data), intent(inout) :: nod_IO
        type(buffer_4_gzip), intent(inout) :: zbuf
Function/Subroutine Documentation
gz_read_filter_geometry()
subroutine gz_mesh_data_io::gz_read_filter_geometry (integer, intent(in) id_rank, type(communication_table), intent(inout) comm_IO, type(node_data), intent(inout) nod_IO, type(buffer_4_gzip), intent(inout) zbuf, integer(kind = kint), intent(inout) ierr)
Definition at line 257 of file gz_mesh_data_IO.f90.
References gz_domain_data_io::gz_read_domain_info(), gz_domain_data_io::gz_read_export_data(), gz_node_geometry_io::gz_read_geometry_info(), gz_domain_data_io::gz_read_import_data(), and gz_node_geometry_io::gz_read_number_of_node().
gz_read_geometry_data()
subroutine gz_mesh_data_io::gz_read_geometry_data (integer, intent(in) id_rank, type(mesh_geometry), intent(inout) mesh_IO, type(buffer_4_gzip), intent(inout) zbuf, integer(kind = kint), intent(inout) ierr)
Definition at line 209 of file gz_mesh_data_IO.f90.
References gz_element_connect_io::gz_read_element_info(), gz_domain_data_io::gz_read_export_data(), gz_domain_data_io::gz_read_import_data(), and gz_read_num_node_ele().
Referenced by gz_mesh_file_io::gz_read_mesh(), and gz_mesh_file_io::gz_read_mesh_geometry().
gz_read_mesh_groups()
subroutine gz_mesh_data_io::gz_read_mesh_groups (type(mesh_groups), intent(inout) mesh_group_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 236 of file gz_mesh_data_IO.f90.
References gz_group_data_io::read_group_data_gz(), and gz_group_data_io::read_surface_group_data_gz().
Referenced by gz_mesh_file_io::gz_read_mesh().
gz_read_num_node()
subroutine gz_mesh_data_io::gz_read_num_node (integer, intent(in) id_rank, type(mesh_geometry), intent(inout) mesh_IO, type(buffer_4_gzip), intent(inout) zbuf, integer(kind = kint), intent(inout) ierr)
Definition at line 169 of file gz_mesh_data_IO.f90.
References gz_domain_data_io::gz_read_domain_info(), and gz_node_geometry_io::gz_read_number_of_node().
Referenced by gz_mesh_file_io::gz_read_node_size(), and gz_read_num_node_ele().
gz_read_num_node_ele()
subroutine gz_mesh_data_io::gz_read_num_node_ele (integer, intent(in) id_rank, type(mesh_geometry), intent(inout) mesh_IO, type(buffer_4_gzip), intent(inout) zbuf, integer(kind = kint), intent(inout) ierr)
Definition at line 187 of file gz_mesh_data_IO.f90.
References gz_node_geometry_io::gz_read_geometry_info(), gz_read_num_node(), and gz_element_connect_io::gz_read_number_of_element().
Referenced by gz_read_geometry_data(), and gz_mesh_file_io::gz_read_geometry_size().
gz_write_filter_geometry()
subroutine gz_mesh_data_io::gz_write_filter_geometry (integer, intent(in) id_rank, type(communication_table), intent(in) comm_IO, type(node_data), intent(in) nod_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 129 of file gz_mesh_data_IO.f90.
References gz_domain_data_io::gz_write_domain_info(), gz_domain_data_io::gz_write_export_data(), gz_node_geometry_io::gz_write_geometry_info(), gz_domain_data_io::gz_write_import_data(), gzip_file_access::gz_write_textbuf_no_lf(), m_fem_mesh_labels::hd_fem_export(), m_fem_mesh_labels::hd_fem_import(), m_fem_mesh_labels::hd_fem_node(), and m_fem_mesh_labels::hd_fem_para().
gz_write_geometry_data()
subroutine gz_mesh_data_io::gz_write_geometry_data (integer, intent(in) id_rank, type(mesh_geometry), intent(in) mesh_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 57 of file gz_mesh_data_IO.f90.
References gz_domain_data_io::gz_write_domain_info(), gz_element_connect_io::gz_write_element_info(), gz_domain_data_io::gz_write_export_data(), gz_node_geometry_io::gz_write_geometry_info(), gz_domain_data_io::gz_write_import_data(), gzip_file_access::gz_write_textbuf_no_lf(), m_fem_mesh_labels::hd_fem_elem(), m_fem_mesh_labels::hd_fem_export(), m_fem_mesh_labels::hd_fem_import(), m_fem_mesh_labels::hd_fem_node(), and m_fem_mesh_labels::hd_fem_para().
Referenced by gz_mesh_file_io::gz_write_mesh_file().
gz_write_mesh_groups()
subroutine gz_mesh_data_io::gz_write_mesh_groups (type(mesh_groups), intent(in) mesh_group_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 100 of file gz_mesh_data_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf(), m_fem_mesh_labels::hd_fem_elegrp(), m_fem_mesh_labels::hd_fem_nodgrp(), m_fem_mesh_labels::hd_fem_sfgrp(), gz_group_data_io::write_group_data_gz(), and gz_group_data_io::write_surf_group_data_gz().
Referenced by gz_mesh_file_io::gz_write_mesh_file().