CALYPSO: t_ctl_data_sph_mhd_psf Module Reference
t_ctl_data_sph_mhd_psf Module Reference
Functions/Subroutines
subroutine read_control_4_sph_mhd_w_psf (file_name, DMHD_ctl)
subroutine read_control_4_sph_mhd_noviz (file_name, DMHD_ctl)
Variables
integer(kind=kint), parameter, private ctl_file_code = 11
character(len=kchara), private hd_mhd_ctl = 'MHD_control'
Function/Subroutine Documentation
read_control_4_sph_mhd_noviz()
subroutine t_ctl_data_sph_mhd_psf::read_control_4_sph_mhd_noviz (character(len=kchara), intent(in) file_name, type(dns_mhd_simulation_control), intent(inout) DMHD_ctl)
Definition at line 77 of file t_ctl_data_sph_MHD_psf.f90.
References t_ctl_data_mhd::bcast_sph_mhd_ctl_data(), ctl_file_code, hd_mhd_ctl, t_read_control_elements::load_one_line_from_control(), calypso_mpi::my_rank, and t_ctl_data_mhd::read_sph_mhd_ctl_noviz().
Referenced by sph_analyzer_add_initial::initialize_add_sph_initial(), sph_analyzer_const_initial::initialize_const_sph_initial(), and analyzer_sph_dynamobench::initialize_sph_dynamobench().
read_control_4_sph_mhd_w_psf()
subroutine t_ctl_data_sph_mhd_psf::read_control_4_sph_mhd_w_psf (character(len=kchara), intent(in) file_name, type(dns_mhd_simulation_control), intent(inout) DMHD_ctl)
Definition at line 46 of file t_ctl_data_sph_MHD_psf.f90.
References t_ctl_data_mhd::bcast_sph_mhd_ctl_w_psf(), ctl_file_code, hd_mhd_ctl, t_read_control_elements::load_one_line_from_control(), calypso_mpi::my_rank, t_ctl_data_mhd::read_sph_mhd_ctl_w_psf(), and t_control_data_surfacings::section_step_ctls_to_time_ctl().
Referenced by analyzer_sph_mhd_w_psf::initialize_sph_mhd_w_psf(), and analyzer_sph_snap_w_psf::initialize_sph_snap_w_psf().
Variable Documentation
ctl_file_code
integer(kind=kint), parameter, private t_ctl_data_sph_mhd_psf::ctl_file_code = 11 private
Definition at line 31 of file t_ctl_data_sph_MHD_psf.f90.
Referenced by read_control_4_sph_mhd_noviz(), and read_control_4_sph_mhd_w_psf().
hd_mhd_ctl
character(len=kchara), private t_ctl_data_sph_mhd_psf::hd_mhd_ctl = 'MHD_control' private
Definition at line 35 of file t_ctl_data_sph_MHD_psf.f90.
Referenced by read_control_4_sph_mhd_noviz(), and read_control_4_sph_mhd_w_psf().