CALYPSO: t_check_and_make_sph_mesh Module Reference
t_check_and_make_sph_mesh Module Reference
Main loop to generate spherical harmonics indices.
Data Types
type sph_grid_maker_in_sim
Structure to check and construct spherical shell mesh.
Functions/Subroutines
subroutine load_para_sph_and_fem_mesh (FEM_mesh_flags, sph_file_param, sph, comms_sph, sph_grps, geofem, mesh_file, sph_maker)
subroutine const_fem_mesh_4_sph (FEM_mesh_flags, sph_file_param, sph, comms_sph, sph_grps, geofem, mesh_file, sph_maker)
subroutine check_and_make_sph_mesh (sph_file_param, sph_maker, sph, comms_sph, sph_grps)
subroutine check_and_make_sph_rj_mode (sph_file_param, sph_maker, sph, comms_sph, sph_grps)
subroutine, private load_fem_mesh_4_sph (FEM_mesh_flags, mesh_file, sph_params, sph_rtp, sph_rj, geofem, gen_sph)
Detailed Description
Main loop to generate spherical harmonics indices.
      subroutine load_para_SPH_and_FEM_mesh(FEM_mesh_flags,           &
     &          sph_file_param, sph, comms_sph, sph_grps, geofem,     &
     &          mesh_file, sph_maker)
      subroutine const_FEM_mesh_4_SPH(FEM_mesh_flags,                 &
     &          sph_file_param, sph, comms_sph, sph_grps, geofem,     &
     &          mesh_file, sph_maker)
        type(FEM_file_IO_flags), intent(in) :: FEM_mesh_flags
        type(field_IO_params), intent(in) ::  sph_file_param
        type(sph_grids), intent(inout) :: sph
        type(sph_comm_tables), intent(inout) :: comms_sph
        type(sph_group_data), intent(inout) ::  sph_grps
        type(mesh_data), intent(inout) :: geofem
        type(field_IO_params), intent(inout) ::  mesh_file
        type(sph_grid_maker_in_sim), intent(inout) :: sph_maker
      subroutine check_and_make_SPH_mesh(sph_file_param, sph_maker,   &
     &          sph, comms_sph, sph_grps)
        type(field_IO_params), intent(in) :: sph_file_param
        type(sph_grid_maker_in_sim), intent(inout) :: sph_maker
        type(sph_grids), intent(inout) :: sph
        type(sph_comm_tables), intent(inout) :: comms_sph
        type(sph_group_data), intent(inout) :: sph_grps
      subroutine check_and_make_SPH_rj_mode(sph_file_param, sph_maker,&
     &          sph, comms_sph, sph_grps)
        type(field_IO_params), intent(in) :: sph_file_param
        type(sph_grid_maker_in_sim), intent(inout) :: sph_maker
        type(sph_grids), intent(inout) :: sph
        type(sph_comm_tables), intent(inout) :: comms_sph
        type(sph_group_data), intent(inout) :: sph_grps
Function/Subroutine Documentation
check_and_make_sph_mesh()
subroutine t_check_and_make_sph_mesh::check_and_make_sph_mesh (type(field_io_params), intent(in) sph_file_param, type(sph_grid_maker_in_sim), intent(inout) sph_maker, type(sph_grids), intent(inout) sph, type(sph_comm_tables), intent(inout) comms_sph, type(sph_group_data), intent(inout) sph_grps)
Definition at line 161 of file t_check_and_make_SPH_mesh.f90.
References calypso_mpi::calypso_mpi_abort(), calypso_mpi::calypso_mpi_barrier(), calypso_mpi_logical::calypso_mpi_bcast_one_logical(), sph_file_io_select::check_exsist_rj_file(), sph_file_io_select::check_exsist_rlm_file(), sph_file_io_select::check_exsist_rtm_file(), sph_file_io_select::check_exsist_rtp_file(), m_work_time::end_elapsed_time(), m_error_ids::ierr_file, m_machine_parameter::iflag_debug, m_elapsed_labels_gen_sph::iflag_gsp_time, m_elapsed_labels_gen_sph::ist_elapsed_gsp, m_constants::izero, parallel_load_data_4_sph::load_sph_mesh(), mpi_gen_sph_grids_modes::mpi_gen_sph_grids(), calypso_mpi::my_rank, parallel_load_data_4_sph::output_sph_mesh(), check_sph_mhd_openmp_size::s_check_sph_mhd_openmp_size(), parallel_load_data_4_sph::sph_index_flags_and_params(), and m_work_time::start_elapsed_time().
Referenced by analyzer_test_sph::init_test_sph(), input_control_sph_mhd::input_control_4_sph_mhd_nosnap(), and load_para_sph_and_fem_mesh().
check_and_make_sph_rj_mode()
subroutine t_check_and_make_sph_mesh::check_and_make_sph_rj_mode (type(field_io_params), intent(in) sph_file_param, type(sph_grid_maker_in_sim), intent(inout) sph_maker, type(sph_grids), intent(inout) sph, type(sph_comm_tables), intent(inout) comms_sph, type(sph_group_data), intent(inout) sph_grps)
Definition at line 221 of file t_check_and_make_SPH_mesh.f90.
References calypso_mpi::calypso_mpi_abort(), calypso_mpi::calypso_mpi_barrier(), calypso_mpi_logical::calypso_mpi_bcast_one_logical(), sph_file_io_select::check_exsist_rj_file(), sph_file_io_select::check_exsist_rlm_file(), sph_file_io_select::check_exsist_rtm_file(), sph_file_io_select::check_exsist_rtp_file(), m_work_time::end_elapsed_time(), m_error_ids::ierr_file, m_elapsed_labels_gen_sph::iflag_gsp_time, m_elapsed_labels_gen_sph::ist_elapsed_gsp, m_constants::izero, parallel_load_data_4_sph::load_sph_rj_mesh(), mpi_gen_sph_grids_modes::mpi_gen_sph_grids(), calypso_mpi::my_rank, parallel_load_data_4_sph::output_sph_mesh(), parallel_load_data_4_sph::sph_rj_index_flags_and_params(), and m_work_time::start_elapsed_time().
Referenced by analyzer_assemble_sph::init_assemble_sph(), analyzer_compare_sph_rst::init_compare_sph_restart(), and analyzer_rayleigh_cvt_sph::init_cvt_rayleigh_sph().
const_fem_mesh_4_sph()
subroutine t_check_and_make_sph_mesh::const_fem_mesh_4_sph (type(fem_file_io_flags), intent(in) FEM_mesh_flags, type(field_io_params), intent(in) sph_file_param, type(sph_grids), intent(inout) sph, type(sph_comm_tables), intent(in) comms_sph, type(sph_group_data), intent(in) sph_grps, type(mesh_data), intent(inout) geofem, type(field_io_params), intent(inout) mesh_file, type(sph_grid_maker_in_sim), intent(inout) sph_maker)
Definition at line 126 of file t_check_and_make_SPH_mesh.f90.
References t_const_spherical_grid::copy_sph_radial_groups(), t_const_spherical_grid::dealloc_gen_sph_radial_groups(), and load_fem_mesh_4_sph().
Referenced by analyzer_gen_sph_grids::analyze_gen_sph_grids().
load_fem_mesh_4_sph()
subroutine, private t_check_and_make_sph_mesh::load_fem_mesh_4_sph (type(fem_file_io_flags), intent(in) FEM_mesh_flags, type(field_io_params), intent(in) mesh_file, type(sph_shell_parameters), intent(inout) sph_params, type(sph_rtp_grid), intent(in) sph_rtp, type(sph_rj_grid), intent(in) sph_rj, type(mesh_data), intent(inout) geofem, type(construct_spherical_grid), intent(inout) gen_sph) private
Definition at line 282 of file t_check_and_make_SPH_mesh.f90.
References const_fem_mesh_sph_mhd::const_fem_mesh_4_sph_mhd(), m_machine_parameter::iflag_debug, m_spheric_constants::iflag_mesh_same, m_spheric_constants::iflag_mesh_w_center, m_spheric_constants::iflag_no_femmesh, set_nnod_4_ele_by_type::set_cube_eletype_from_num(), and copy_mesh_structures::set_mesh_data_from_type().
Referenced by const_fem_mesh_4_sph(), and load_para_sph_and_fem_mesh().
load_para_sph_and_fem_mesh()
subroutine t_check_and_make_sph_mesh::load_para_sph_and_fem_mesh (type(fem_file_io_flags), intent(in) FEM_mesh_flags, type(field_io_params), intent(in) sph_file_param, type(sph_grids), intent(inout) sph, type(sph_comm_tables), intent(inout) comms_sph, type(sph_group_data), intent(inout) sph_grps, type(mesh_data), intent(inout) geofem, type(field_io_params), intent(inout) mesh_file, type(sph_grid_maker_in_sim), intent(inout) sph_maker)
Definition at line 79 of file t_check_and_make_SPH_mesh.f90.
References check_and_make_sph_mesh(), mesh_file_name_by_param::check_exist_mesh(), t_const_spherical_grid::copy_sph_radial_groups(), t_const_spherical_grid::dealloc_gen_sph_radial_groups(), m_machine_parameter::iflag_debug, load_fem_mesh_4_sph(), mpi_load_mesh_data::mpi_input_mesh(), calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by input_control_sph_mhd::input_control_4_sph_make_init(), and input_control_sph_mhd::input_control_sph_mhd_psf().