CALYPSO: gz_sph_global_1d_idx_io_b Module Reference
gz_sph_global_1d_idx_io_b Module Reference
Mesh file IO for gxipped format.
Functions/Subroutines
subroutine gz_read_rtp_gl_1d_table_b (zbuf, sph_IO)
subroutine gz_read_rj_gl_1d_table_b (zbuf, sph_IO)
subroutine gz_write_rtp_gl_1d_table_b (sph_IO, zbuf)
subroutine gz_write_rj_gl_1d_table_b (sph_IO, zbuf)
Detailed Description
Mesh file IO for gxipped format.
      subroutine gz_read_rtp_gl_1d_table_b(zbuf, sph_IO)
      subroutine gz_read_rj_gl_1d_table_b(zbuf, sph_IO)
        type(buffer_4_gzip), intent(inout) :: zbuf
        type(sph_IO_data), intent(inout) :: sph_IO
      subroutine gz_write_rtp_gl_1d_table_b(sph_IO, zbuf)
      subroutine gz_write_rj_gl_1d_table_b(sph_IO, zbuf)
        type(sph_IO_data), intent(in) :: sph_IO
        type(buffer_4_gzip), intent(inout) :: zbuf
Function/Subroutine Documentation
gz_read_rj_gl_1d_table_b()
subroutine gz_sph_global_1d_idx_io_b::gz_read_rj_gl_1d_table_b (type(buffer_4_gzip), intent(inout) zbuf, type(sph_io_data), intent(inout) sph_IO)
Definition at line 91 of file gz_sph_global_1d_idx_IO_b.f90.
References t_node_id_spherical_io::alloc_idx_sph_1d1_io(), t_node_id_spherical_io::alloc_idx_sph_1d2_io(), t_node_id_spherical_io::alloc_num_idx_sph_io(), transfer_to_long_integers::cast_long(), gz_binary_io::gz_read_1d_vector_b(), and gz_binary_io::gz_read_mul_integer_b().
Referenced by gz_sph_modes_data_io_b::gz_read_modes_rlm_data_b(), and gz_sph_modes_data_io_b::gz_read_spectr_modes_rj_data_b().
gz_read_rtp_gl_1d_table_b()
subroutine gz_sph_global_1d_idx_io_b::gz_read_rtp_gl_1d_table_b (type(buffer_4_gzip), intent(inout) zbuf, type(sph_io_data), intent(inout) sph_IO)
Definition at line 39 of file gz_sph_global_1d_idx_IO_b.f90.
References t_node_id_spherical_io::alloc_idx_sph_1d1_io(), t_node_id_spherical_io::alloc_idx_sph_1d2_io(), t_node_id_spherical_io::alloc_idx_sph_1d3_io(), t_node_id_spherical_io::alloc_num_idx_sph_io(), transfer_to_long_integers::cast_long(), gz_binary_io::gz_read_1d_vector_b(), and gz_binary_io::gz_read_mul_integer_b().
Referenced by gz_sph_modes_data_io_b::gz_read_geom_rtm_data_b(), and gz_sph_modes_data_io_b::gz_read_geom_rtp_data_b().
gz_write_rj_gl_1d_table_b()
subroutine gz_sph_global_1d_idx_io_b::gz_write_rj_gl_1d_table_b (type(sph_io_data), intent(in) sph_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 175 of file gz_sph_global_1d_idx_IO_b.f90.
References transfer_to_long_integers::cast_long(), gz_binary_io::gz_write_1d_vector_b(), and gz_binary_io::gz_write_mul_integer_b().
Referenced by gz_sph_modes_data_io_b::gz_write_modes_rlm_data_b(), and gz_sph_modes_data_io_b::gz_write_spectr_modes_rj_data_b().
gz_write_rtp_gl_1d_table_b()
subroutine gz_sph_global_1d_idx_io_b::gz_write_rtp_gl_1d_table_b (type(sph_io_data), intent(in) sph_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 138 of file gz_sph_global_1d_idx_IO_b.f90.
References transfer_to_long_integers::cast_long(), gz_binary_io::gz_write_1d_vector_b(), and gz_binary_io::gz_write_mul_integer_b().
Referenced by gz_sph_modes_data_io_b::gz_write_geom_rtm_data_b(), and gz_sph_modes_data_io_b::gz_write_geom_rtp_data_b().