CALYPSO: simple_sph_spectr_head_io Module Reference
simple_sph_spectr_head_io Module Reference
Header output for spectrum data.
Functions/Subroutines
subroutine, private read_sph_pwr_vol_head (id_file, sph_IN)
subroutine, private read_sph_pwr_layer_head (id_file, sph_IN)
subroutine write_sph_pwr_vol_head (id_file, sph_IN)
subroutine write_sph_pwr_layer_head (id_file, sph_IN)
subroutine, private read_sph_spectr_name (id_file, sph_IN)
subroutine input_sph_pwr_vol_head (id_file, sph_IN)
subroutine input_sph_spectr_vol_head (id_file, sph_IN)
subroutine input_sph_pwr_layer_head (id_file, sph_IN)
subroutine input_sph_spectr_layer_head (id_file, sph_IN)
subroutine input_sph_pwr_vol_head_old (id_file, sph_IN)
subroutine input_sph_spectr_vol_head_old (id_file, sph_IN)
subroutine input_sph_pwr_layer_head_old (id_file, sph_IN)
subroutine input_sph_spectr_layer_head_old (id_file, sph_IN)
Detailed Description
Header output for spectrum data.
      subroutine input_sph_pwr_vol_head(id_file, sph_IN)
      subroutine input_sph_spectr_vol_head(id_file, sph_IN)
      subroutine input_sph_pwr_layer_head(id_file, sph_IN)
      subroutine input_sph_spectr_layer_head(id_file, sph_IN)
      subroutine input_sph_pwr_vol_head_old(id_file, sph_IN)
      subroutine input_sph_spectr_vol_head_old(id_file, sph_IN)
      subroutine input_sph_pwr_layer_head_old(id_file, sph_IN)
      subroutine input_sph_spectr_layer_head_old(id_file, sph_IN)
      subroutine write_sph_pwr_vol_head(id_file, sph_IN)
      subroutine write_sph_pwr_layer_head(id_file, sph_IN)
Function/Subroutine Documentation
input_sph_pwr_layer_head()
subroutine simple_sph_spectr_head_io::input_sph_pwr_layer_head (integer(kind = kint), intent(in) id_file, type(read_sph_spectr_data), intent(inout) sph_IN)
Definition at line 203 of file simple_sph_spectr_head_IO.f90.
References t_read_sph_spectra::alloc_sph_espec_name(), t_read_sph_spectra::alloc_sph_spectr_data(), m_constants::izero, read_sph_pwr_layer_head(), and read_sph_spectr_name().
Referenced by sph_mean_square_io_select::select_input_sph_pwr_head().
input_sph_pwr_layer_head_old()
subroutine simple_sph_spectr_head_io::input_sph_pwr_layer_head_old (integer(kind = kint), intent(in) id_file, type(read_sph_spectr_data), intent(inout) sph_IN)
Definition at line 278 of file simple_sph_spectr_head_IO.f90.
References t_read_sph_spectra::alloc_sph_espec_name(), t_read_sph_spectra::alloc_sph_spectr_data(), m_constants::izero, read_sph_pwr_layer_head(), and read_sph_spectr_name().
Referenced by sph_mean_square_io_select::select_input_sph_pwr_head().
input_sph_pwr_vol_head()
subroutine simple_sph_spectr_head_io::input_sph_pwr_vol_head (integer(kind = kint), intent(in) id_file, type(read_sph_spectr_data), intent(inout) sph_IN)
Definition at line 165 of file simple_sph_spectr_head_IO.f90.
References t_read_sph_spectra::alloc_sph_espec_name(), t_read_sph_spectra::alloc_sph_spectr_data(), m_constants::izero, read_sph_pwr_vol_head(), and read_sph_spectr_name().
Referenced by sph_mean_square_io_select::select_input_sph_pwr_head().
input_sph_pwr_vol_head_old()
subroutine simple_sph_spectr_head_io::input_sph_pwr_vol_head_old (integer(kind = kint), intent(in) id_file, type(read_sph_spectr_data), intent(inout) sph_IN)
Definition at line 240 of file simple_sph_spectr_head_IO.f90.
References t_read_sph_spectra::alloc_sph_espec_name(), t_read_sph_spectra::alloc_sph_spectr_data(), m_constants::izero, read_sph_pwr_layer_head(), and read_sph_spectr_name().
Referenced by sph_mean_square_io_select::select_input_sph_pwr_head().
input_sph_spectr_layer_head()
subroutine simple_sph_spectr_head_io::input_sph_spectr_layer_head (integer(kind = kint), intent(in) id_file, type(read_sph_spectr_data), intent(inout) sph_IN)
Definition at line 221 of file simple_sph_spectr_head_IO.f90.
References t_read_sph_spectra::alloc_sph_espec_name(), t_read_sph_spectra::alloc_sph_spectr_data(), read_sph_pwr_layer_head(), and read_sph_spectr_name().
Referenced by sph_mean_square_io_select::select_input_sph_pwr_head().
input_sph_spectr_layer_head_old()
subroutine simple_sph_spectr_head_io::input_sph_spectr_layer_head_old (integer(kind = kint), intent(in) id_file, type(read_sph_spectr_data), intent(inout) sph_IN)
Definition at line 296 of file simple_sph_spectr_head_IO.f90.
References t_read_sph_spectra::alloc_sph_espec_name(), t_read_sph_spectra::alloc_sph_spectr_data(), read_sph_pwr_layer_head(), and read_sph_spectr_name().
Referenced by sph_mean_square_io_select::select_input_sph_pwr_head().
input_sph_spectr_vol_head()
subroutine simple_sph_spectr_head_io::input_sph_spectr_vol_head (integer(kind = kint), intent(in) id_file, type(read_sph_spectr_data), intent(inout) sph_IN)
Definition at line 184 of file simple_sph_spectr_head_IO.f90.
References t_read_sph_spectra::alloc_sph_espec_name(), t_read_sph_spectra::alloc_sph_spectr_data(), read_sph_pwr_vol_head(), and read_sph_spectr_name().
Referenced by sph_mean_square_io_select::select_input_sph_pwr_head().
input_sph_spectr_vol_head_old()
subroutine simple_sph_spectr_head_io::input_sph_spectr_vol_head_old (integer(kind = kint), intent(in) id_file, type(read_sph_spectr_data), intent(inout) sph_IN)
Definition at line 259 of file simple_sph_spectr_head_IO.f90.
References t_read_sph_spectra::alloc_sph_espec_name(), t_read_sph_spectra::alloc_sph_spectr_data(), read_sph_pwr_layer_head(), and read_sph_spectr_name().
Referenced by sph_mean_square_io_select::select_input_sph_pwr_head().
read_sph_pwr_layer_head()
subroutine, private simple_sph_spectr_head_io::read_sph_pwr_layer_head (integer(kind = kint), intent(in) id_file, type(read_sph_spectr_data), intent(inout) sph_IN) private
Definition at line 66 of file simple_sph_spectr_head_IO.f90.
References skip_comment_f::skip_comment().
Referenced by input_sph_pwr_layer_head(), input_sph_pwr_layer_head_old(), input_sph_pwr_vol_head_old(), input_sph_spectr_layer_head(), input_sph_spectr_layer_head_old(), and input_sph_spectr_vol_head_old().
read_sph_pwr_vol_head()
subroutine, private simple_sph_spectr_head_io::read_sph_pwr_vol_head (integer(kind = kint), intent(in) id_file, type(read_sph_spectr_data), intent(inout) sph_IN) private
Definition at line 41 of file simple_sph_spectr_head_IO.f90.
References skip_comment_f::skip_comment().
Referenced by input_sph_pwr_vol_head(), and input_sph_spectr_vol_head().
read_sph_spectr_name()
subroutine, private simple_sph_spectr_head_io::read_sph_spectr_name (integer(kind = kint), intent(in) id_file, type(read_sph_spectr_data), intent(inout) sph_IN) private
Definition at line 147 of file simple_sph_spectr_head_IO.f90.
Referenced by input_sph_pwr_layer_head(), input_sph_pwr_layer_head_old(), input_sph_pwr_vol_head(), input_sph_pwr_vol_head_old(), input_sph_spectr_layer_head(), input_sph_spectr_layer_head_old(), input_sph_spectr_vol_head(), and input_sph_spectr_vol_head_old().
write_sph_pwr_layer_head()
subroutine simple_sph_spectr_head_io::write_sph_pwr_layer_head (integer(kind = kint), intent(in) id_file, type(read_sph_spectr_data), intent(in) sph_IN)
Definition at line 118 of file simple_sph_spectr_head_IO.f90.
Referenced by sph_mean_square_io_select::select_output_sph_pwr_head().
write_sph_pwr_vol_head()
subroutine simple_sph_spectr_head_io::write_sph_pwr_vol_head (integer(kind = kint), intent(in) id_file, type(read_sph_spectr_data), intent(in) sph_IN)
Definition at line 88 of file simple_sph_spectr_head_IO.f90.
Referenced by sph_mean_square_io_select::select_output_sph_pwr_head().