CALYPSO: sum_rotation_of_forces Module Reference
sum_rotation_of_forces Module Reference
Evaluate nonlinear terms by pseudo spectram scheme.
Functions/Subroutines
subroutine sum_forces_to_explicit (fl_prop, ipol_exp, ipol_rot_frc, rj_fld)
subroutine licv_forces_to_explicit (fl_prop, ipol_exp, ipol_rot_frc, rj_fld)
Detailed Description
Evaluate nonlinear terms by pseudo spectram scheme.
      subroutine sum_forces_to_explicit                               &
     &         (fl_prop, ipol_exp, ipol_rot_frc, rj_fld)
      subroutine licv_forces_to_explicit                              &
     &         (fl_prop, ipol_exp, ipol_rot_frc, rj_fld)
        type(fluid_property), intent(in) :: fl_prop
        type(explicit_term_address), intent(in) :: ipol_exp
        type(base_force_address), intent(in) :: ipol_rot_frc
        type(phys_data), intent(inout) :: rj_fld
Function/Subroutine Documentation
licv_forces_to_explicit()
subroutine sum_rotation_of_forces::licv_forces_to_explicit (type(fluid_property), intent(in) fl_prop, type(explicit_term_address), intent(in) ipol_exp, type(base_force_address), intent(in) ipol_rot_frc, type(phys_data), intent(inout) rj_fld)
Definition at line 125 of file sum_rotation_of_forces.f90.
References cal_vorticity_terms_adams::add_buoyancy_to_vort_force(), and cal_vorticity_terms_adams::add_each_force_to_rot_forces().
Referenced by cal_nonlinear::licv_exp().
sum_forces_to_explicit()
subroutine sum_rotation_of_forces::sum_forces_to_explicit (type(fluid_property), intent(in) fl_prop, type(explicit_term_address), intent(in) ipol_exp, type(base_force_address), intent(in) ipol_rot_frc, type(phys_data), intent(inout) rj_fld)
Definition at line 43 of file sum_rotation_of_forces.f90.
References cal_vorticity_terms_adams::add_buoyancy_to_vort_force(), cal_vorticity_terms_adams::add_each_force_to_rot_forces(), cal_vorticity_terms_adams::add_rot_advection_to_force(), copy_nodal_fields::clear_field_data(), cal_vorticity_terms_adams::set_mhd_terms_to_force(), and cal_vorticity_terms_adams::set_rot_cv_terms_to_force().
Referenced by cal_nonlinear::nonlinear().