CALYPSO: output_parallel_ucd_file Module Reference
output_parallel_ucd_file Module Reference
parallel UCD file output routines
Functions/Subroutines
subroutine link_output_grd_file (node, ele, nod_comm, nod_fld, ucd_param, ucd)
subroutine output_udt_one_snapshot (istep_ucd, ucd_param, time_d, node, ele, nod_comm, nod_fld)
subroutine link_output_ucd_file_once (istep_ucd, nod_fld, ucd_param, t_IO)
subroutine finalize_ucd_file_output (ucd_param, ucd)
subroutine set_data_by_read_ucd (istep_ucd, ucd_param, t_IO, ucd, nod_fld)
subroutine set_data_by_read_ucd_once (id_rank, istep_ucd, ucd_param, nod_fld, t_IO)
subroutine add_ucd_to_data (id_rank, istep_ucd, ucd_param, nod_fld)
subroutine subtract_by_ucd_data (id_rank, istep_ucd, ucd_param, nod_fld)
Detailed Description
parallel UCD file output routines
      subroutine link_output_grd_file                                 &
     &         (node, ele, nod_comm, nod_fld, ucd_param, ucd)
      subroutine output_udt_one_snapshot(istep_ucd, ucd_param, time_d,&
     &          node, ele, nod_comm, nod_fld)
        type(field_IO_params), intent(in) :: ucd_param
        type(time_data), intent(in) :: time_d
        type(node_data), intent(in) :: node
        type(element_data), intent(in) :: ele
        type(communication_table), intent(in) :: nod_comm
        type(phys_data), intent(in) :: nod_fld
      subroutine link_output_ucd_file_once                            &
     &         (istep_ucd, nod_fld, ucd_param, t_IO)
        type(field_IO_params), intent(in) :: ucd_param
        type(phys_data), intent(in) :: nod_fld
        type(time_data), intent(in) :: t_IO
      subroutine finalize_ucd_file_output(ucd_param)
        type(field_IO_params), intent(in) :: ucd_param
      subroutine set_data_by_read_ucd                                 &
     &         (id_rank, istep_ucd, ucd_param, t_IO, ucd, nod_fld)
        type(field_IO_params), intent(in) :: ucd_param
        type(time_data), intent(inout) :: t_IO
        type(ucd_data), intent(inout) :: ucd
        type(phys_data), intent(inout) :: nod_fld
      subroutine set_data_by_read_ucd_once(id_rank, istep_ucd,        &
     &          ucd_param, nod_fld, t_IO)
      subroutine add_ucd_to_data                                      &
     &         (id_rank, istep_ucd, ucd_param, nod_fld)
      subroutine subtract_by_ucd_data                                 &
     &         (id_rank, istep_ucd, ucd_param, nod_fld)
        type(field_IO_params), intent(in) :: ucd_param
        type(phys_data), intent(inout) :: nod_fld
Function/Subroutine Documentation
add_ucd_to_data()
subroutine output_parallel_ucd_file::add_ucd_to_data (integer, intent(in) id_rank, integer(kind = kint), intent(in) istep_ucd, type(field_io_params), intent(in) ucd_param, type(phys_data), intent(inout) nod_fld)
Definition at line 248 of file output_parallel_ucd_file.f90.
References set_and_cal_udt_data::add_field_by_udt_data(), t_ucd_data::deallocate_ucd_data(), and parallel_ucd_io_select::sel_read_alloc_para_udt_file().
finalize_ucd_file_output()
subroutine output_parallel_ucd_file::finalize_ucd_file_output (type(field_io_params), intent(in) ucd_param, type(ucd_data), intent(inout) ucd)
Definition at line 180 of file output_parallel_ucd_file.f90.
References merged_udt_vtk_file_io::finalize_merged_ucd().
Referenced by t_ucd_file::finalize_output_ucd().
link_output_grd_file()
subroutine output_parallel_ucd_file::link_output_grd_file (type(node_data), intent(in) node, type(element_data), intent(in) ele, type(communication_table), intent(in) nod_comm, type(phys_data), intent(in) nod_fld, type(field_io_params), intent(in) ucd_param, type(ucd_data), intent(inout) ucd)
Definition at line 67 of file output_parallel_ucd_file.f90.
References t_ucd_data::deallocate_ucd_ele(), t_ucd_data::deallocate_ucd_node(), m_field_file_format::iflag_udt, m_field_file_format::iflag_vtd, merged_udt_vtk_file_io::init_merged_ucd(), set_ucd_data_to_type::link_field_data_to_ucd(), set_ucd_data_to_type::link_local_mesh_2_ucd(), set_ucd_data_to_type::link_num_field_2_ucd(), and parallel_ucd_io_select::sel_write_parallel_ucd_mesh().
Referenced by t_viz_vtk_convert::init_visualize_convert_vtk(), and t_ucd_file::output_grd_file_4_snapshot().
link_output_ucd_file_once()
subroutine output_parallel_ucd_file::link_output_ucd_file_once (integer(kind = kint), intent(in) istep_ucd, type(phys_data), intent(in) nod_fld, type(field_io_params), intent(in) ucd_param, type(time_data), intent(in) t_IO)
Definition at line 154 of file output_parallel_ucd_file.f90.
References t_ucd_data::disconnect_ucd_data(), set_ucd_data_to_type::link_field_data_to_ucd(), and parallel_ucd_io_select::sel_write_parallel_ucd_file().
output_udt_one_snapshot()
subroutine output_parallel_ucd_file::output_udt_one_snapshot (integer(kind = kint), intent(in) istep_ucd, type(field_io_params), intent(in) ucd_param, type(time_data), intent(in) time_d, type(node_data), intent(in) node, type(element_data), intent(in) ele, type(communication_table), intent(in) nod_comm, type(phys_data), intent(in) nod_fld)
Definition at line 109 of file output_parallel_ucd_file.f90.
References t_time_data::copy_time_step_size_data(), t_ucd_data::deallocate_ucd_ele(), t_ucd_data::deallocate_ucd_node(), t_ucd_data::disconnect_ucd_data(), merged_udt_vtk_file_io::finalize_merged_ucd(), merged_udt_vtk_file_io::init_merged_ucd(), set_ucd_data_to_type::link_field_data_to_ucd(), set_ucd_data_to_type::link_local_mesh_2_ucd(), set_ucd_data_to_type::link_num_field_2_ucd(), and parallel_ucd_io_select::sel_write_parallel_ucd_file().
set_data_by_read_ucd()
subroutine output_parallel_ucd_file::set_data_by_read_ucd (integer(kind = kint), intent(in) istep_ucd, type(field_io_params), intent(in) ucd_param, type(time_data), intent(inout) t_IO, type(ucd_data), intent(inout) ucd, type(phys_data), intent(inout) nod_fld)
Definition at line 197 of file output_parallel_ucd_file.f90.
References parallel_ucd_io_select::sel_read_parallel_udt_file(), and set_and_cal_udt_data::set_field_by_udt_data().
Referenced by load_mesh_and_field_4_viz::set_field_data_4_viz().
set_data_by_read_ucd_once()
subroutine output_parallel_ucd_file::set_data_by_read_ucd_once (integer, intent(in) id_rank, integer(kind = kint), intent(in) istep_ucd, type(field_io_params), intent(in) ucd_param, type(phys_data), intent(inout) nod_fld, type(time_data), intent(inout) t_IO)
Definition at line 220 of file output_parallel_ucd_file.f90.
References t_ucd_data::deallocate_ucd_data(), parallel_ucd_io_select::sel_read_alloc_para_udt_file(), and set_and_cal_udt_data::set_field_by_udt_data().
Referenced by t_ucd_file::read_udt_4_snap().
subtract_by_ucd_data()
subroutine output_parallel_ucd_file::subtract_by_ucd_data (integer, intent(in) id_rank, integer(kind = kint), intent(in) istep_ucd, type(field_io_params), intent(in) ucd_param, type(phys_data), intent(inout) nod_fld)
Definition at line 276 of file output_parallel_ucd_file.f90.
References t_ucd_data::deallocate_ucd_data(), parallel_ucd_io_select::sel_read_alloc_para_udt_file(), and set_and_cal_udt_data::subtract_field_by_udt_data().