CALYPSO: zlib_cvt_ascii_ele_connect Module Reference
zlib_cvt_ascii_ele_connect Module Reference
Data IO routines for spectrum data.
Functions/Subroutines
subroutine defleate_ele_connect (nele, nnod_4_ele, id_global, ie, zbuf)
subroutine infleate_ele_connect (nele, nnod_4_ele, id_global, ie, zbuf)
subroutine defleate_ele_int_list (nele, ncomp, ivect, zbuf)
subroutine infleate_ele_int_list (nele, ncomp, ivect, zbuf)
subroutine defleate_1d_global_address (nnod, numdir, idx, zbuf)
subroutine infleate_1d_global_address (nnod, numdir, idx, zbuf)
Detailed Description
Data IO routines for spectrum data.
      subroutine defleate_ele_connect                                 &
     &         (nele, nnod_4_ele, id_global, ie, zbuf)
      subroutine infleate_ele_connect                                 &
     &         (nele, nnod_4_ele, id_global, ie, zbuf)
        type(buffer_4_gzip), intent(inout) :: zbuf
      subroutine defleate_ele_int_list(nele, ncomp, ivect, zbuf)
      subroutine infleate_ele_int_list(nele, ncomp, ivect, zbuf)
        type(buffer_4_gzip), intent(inout) :: zbuf
      subroutine defleate_1d_global_address(nnod, numdir, idx, zbuf)
      subroutine infleate_1d_global_address(nnod, numdir, idx, zbuf)
        type(buffer_4_gzip), intent(inout) :: zbuf
Function/Subroutine Documentation
defleate_1d_global_address()
subroutine zlib_cvt_ascii_ele_connect::defleate_1d_global_address (integer(kind = kint_gl), intent(in) nnod, integer(kind = kint), intent(in) numdir, integer(kind = kint), dimension(nnod, numdir), intent(in) idx, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 324 of file zlib_cvt_ascii_ele_connect.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), gzip_defleate::gzip_defleat_char_begin(), gzip_defleate::gzip_defleat_char_cont(), gzip_defleate::gzip_defleat_char_last(), gzip_defleate::gzip_defleat_char_once(), data_io_to_textline::len_multi_int_textline(), and data_io_to_textline::multi_int_textline().
Referenced by gz_mpi_sph_gl_1d_idx_io::gz_mpi_write_1d_gl_address().
defleate_ele_connect()
subroutine zlib_cvt_ascii_ele_connect::defleate_ele_connect (integer(kind = kint_gl), intent(in) nele, integer(kind = kint), intent(in) nnod_4_ele, integer(kind = kint_gl), dimension(nele), intent(in) id_global, integer(kind = kint), dimension(nele,nnod_4_ele), intent(in) ie, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 40 of file zlib_cvt_ascii_ele_connect.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), gzip_defleate::gzip_defleat_char_begin(), gzip_defleate::gzip_defleat_char_cont(), gzip_defleate::gzip_defleat_char_last(), gzip_defleate::gzip_defleat_char_once(), data_io_to_textline::int8_and_mul_int8_textline(), and data_io_to_textline::len_int8_and_mul_int8_textline().
Referenced by gz_mpi_integer_list_io::gz_mpi_write_ele_connect().
defleate_ele_int_list()
subroutine zlib_cvt_ascii_ele_connect::defleate_ele_int_list (integer(kind = kint_gl), intent(in) nele, integer(kind = kint), intent(in) ncomp, integer(kind = kint), dimension(nele,ncomp), intent(in) ivect, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 190 of file zlib_cvt_ascii_ele_connect.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), gzip_defleate::gzip_defleat_char_begin(), gzip_defleate::gzip_defleat_char_cont(), gzip_defleate::gzip_defleat_char_last(), gzip_defleate::gzip_defleat_char_once(), data_io_to_textline::len_multi_int_textline(), and data_io_to_textline::multi_int_textline().
Referenced by gz_mpi_integer_list_io::gz_mpi_write_int_list().
infleate_1d_global_address()
subroutine zlib_cvt_ascii_ele_connect::infleate_1d_global_address (integer(kind = kint_gl), intent(in) nnod, integer(kind = kint), intent(in) numdir, integer(kind = kint), dimension(nnod, numdir), intent(inout) idx, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 371 of file zlib_cvt_ascii_ele_connect.f90.
References t_buffer_4_gzip::alloc_textbuffer_for_zlib(), t_buffer_4_gzip::dealloc_textbuffer_for_zlib(), t_buffer_4_gzip::dealloc_zip_buffer(), gzip_infleate::gzip_infleat_char_begin(), gzip_infleate::gzip_infleat_char_cont(), gzip_infleate::gzip_infleat_char_last(), gzip_infleate::gzip_infleat_char_once(), data_io_to_textline::len_multi_int_textline(), t_buffer_4_gzip::link_pointer_for_zlib_buffer(), data_io_to_textline::read_multi_int_textline(), and t_buffer_4_gzip::unlink_pointer_for_zlib_buffer().
Referenced by gz_mpi_sph_gl_1d_idx_io::gz_mpi_read_1d_gl_address().
infleate_ele_connect()
subroutine zlib_cvt_ascii_ele_connect::infleate_ele_connect (integer(kind = kint_gl), intent(in) nele, integer(kind = kint), intent(in) nnod_4_ele, integer(kind = kint_gl), dimension(nele), intent(inout) id_global, integer(kind = kint), dimension(nele, nnod_4_ele), intent(inout) ie, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 109 of file zlib_cvt_ascii_ele_connect.f90.
References t_buffer_4_gzip::alloc_textbuffer_for_zlib(), t_buffer_4_gzip::dealloc_textbuffer_for_zlib(), t_buffer_4_gzip::dealloc_zip_buffer(), gzip_infleate::gzip_infleat_char_begin(), gzip_infleate::gzip_infleat_char_cont(), gzip_infleate::gzip_infleat_char_last(), gzip_infleate::gzip_infleat_char_once(), data_io_to_textline::len_int8_and_mul_int8_textline(), t_buffer_4_gzip::link_pointer_for_zlib_buffer(), data_io_to_textline::read_int8_and_mul_int8_textline(), and t_buffer_4_gzip::unlink_pointer_for_zlib_buffer().
Referenced by gz_mpi_integer_list_io::gz_mpi_read_ele_connect().
infleate_ele_int_list()
subroutine zlib_cvt_ascii_ele_connect::infleate_ele_int_list (integer(kind = kint_gl), intent(in) nele, integer(kind = kint), intent(in) ncomp, integer(kind = kint), dimension(nele, ncomp), intent(inout) ivect, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 252 of file zlib_cvt_ascii_ele_connect.f90.
References t_buffer_4_gzip::alloc_textbuffer_for_zlib(), t_buffer_4_gzip::dealloc_textbuffer_for_zlib(), t_buffer_4_gzip::dealloc_zip_buffer(), gzip_infleate::gzip_infleat_char_begin(), gzip_infleate::gzip_infleat_char_cont(), gzip_infleate::gzip_infleat_char_last(), gzip_infleate::gzip_infleat_char_once(), data_io_to_textline::len_multi_int_textline(), t_buffer_4_gzip::link_pointer_for_zlib_buffer(), data_io_to_textline::read_multi_int_textline(), and t_buffer_4_gzip::unlink_pointer_for_zlib_buffer().
Referenced by gz_mpi_integer_list_io::gz_mpi_read_int_list().