CALYPSO: cal_momentum_eq_explicit Module Reference
cal_momentum_eq_explicit Module Reference
Time integration for momentum equation by explicit scheme.
Functions/Subroutines
subroutine sel_explicit_sph (i_step, dt, MHD_prop, sph_MHD_bc, sph_rj, ipol, rj_fld)
subroutine, private cal_explicit_sph_adams (dt, sph_rj, MHD_prop, sph_MHD_bc, ipol, rj_fld)
subroutine, private cal_explicit_sph_euler (dt, sph_rj, MHD_prop, sph_MHD_bc, ipol, rj_fld)
subroutine, private cal_first_prev_step_adams (sph_rj, MHD_prop, sph_MHD_bc, ipol, rj_fld)
Detailed Description
Time integration for momentum equation by explicit scheme.
      subroutine sel_explicit_sph(i_step, dt, MHD_prop, sph_MHD_bc,   &
     &          sph_rj, ipol, rj_fld)
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(fdm_matrices), intent(in) :: r_2nd
        type(MHD_evolution_param), intent(in) :: MHD_prop
        type(sph_MHD_boundary_data), intent(in) :: sph_MHD_bc
        type(legendre_4_sph_trans), intent(in) :: leg
        type(phys_address), intent(in) :: ipol
        type(phys_data), intent(inout) :: rj_fld
Parameters
i_step time step
Function/Subroutine Documentation
cal_explicit_sph_adams()
subroutine, private cal_momentum_eq_explicit::cal_explicit_sph_adams (real(kind = kreal), intent(in) dt, type(sph_rj_grid), intent(in) sph_rj, type(mhd_evolution_param), intent(in) MHD_prop, type(sph_mhd_boundary_data), intent(in) sph_MHD_bc, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld) private
Definition at line 82 of file cal_momentum_eq_explicit.f90.
References cal_explicit_terms::cal_diff_induction_mhd_adams(), cal_vorticity_terms_adams::cal_vorticity_eq_adams(), explicit_scalars_sph::explicit_scalars_sph_adams(), and t_physical_property::id_no_evolution.
Referenced by sel_explicit_sph().
cal_explicit_sph_euler()
subroutine, private cal_momentum_eq_explicit::cal_explicit_sph_euler (real(kind = kreal), intent(in) dt, type(sph_rj_grid), intent(in) sph_rj, type(mhd_evolution_param), intent(in) MHD_prop, type(sph_mhd_boundary_data), intent(in) sph_MHD_bc, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld) private
Definition at line 122 of file cal_momentum_eq_explicit.f90.
References cal_explicit_terms::cal_diff_induction_mhd_euler(), cal_vorticity_terms_adams::cal_vorticity_eq_euler(), explicit_scalars_sph::explicit_scalars_sph_euler(), and t_physical_property::id_no_evolution.
Referenced by sel_explicit_sph().
cal_first_prev_step_adams()
subroutine, private cal_momentum_eq_explicit::cal_first_prev_step_adams (type(sph_rj_grid), intent(in) sph_rj, type(mhd_evolution_param), intent(in) MHD_prop, type(sph_mhd_boundary_data), intent(in) sph_MHD_bc, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld) private
Definition at line 160 of file cal_momentum_eq_explicit.f90.
References explicit_scalars_sph::first_scalars_prev_step_adams(), t_physical_property::id_no_evolution, cal_vorticity_terms_adams::set_ini_adams_inertia(), and cal_explicit_terms::set_ini_adams_mag_induct().
Referenced by sel_explicit_sph().
sel_explicit_sph()
subroutine cal_momentum_eq_explicit::sel_explicit_sph (integer(kind = kint), intent(in) i_step, real(kind = kreal), intent(in) dt, type(mhd_evolution_param), intent(in) MHD_prop, type(sph_mhd_boundary_data), intent(in) sph_MHD_bc, type(sph_rj_grid), intent(in) sph_rj, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld)
Definition at line 49 of file cal_momentum_eq_explicit.f90.
References cal_explicit_sph_adams(), cal_explicit_sph_euler(), cal_first_prev_step_adams(), and t_physical_property::id_explicit_euler.
Referenced by sph_analyzer_mhd::sph_analyze_mhd().