CALYPSO: /home/takumi kera/calypso/src/programs/data_utilities/VIZ_only/main_surface_rendering.f90 File Reference
main_surface_rendering.f90 File Reference
Functions/Subroutines
program kemorin_surface_rendering
Function/Subroutine Documentation
kemorin_surface_rendering()
program kemorin_surface_rendering
Definition at line 10 of file main_surface_rendering.f90.
References analyzer_psf::analyze_psf(), calypso_mpi::calypso_mpi_finalize(), calypso_mpi::calypso_mpi_init(), and analyzer_psf::init_analyzer_psf().