CALYPSO: set_global_spherical_param Module Reference
set_global_spherical_param Module Reference
Set global resolution of spherical hermonics.
Functions/Subroutines
subroutine set_global_sph_resolution (l_truncation, m_folding, sph_rtp, sph_rtm, sph_rlm, sph_rj)
subroutine set_global_rtm_resolution (l_truncation, m_folding, sph_rtp, sph_rtm)
subroutine set_global_rlm_resolution (l_truncation, m_folding, nidx_global_rtp_r, sph_rlm)
subroutine set_gl_nnod_spherical (nproc, ndomain_1, ndomain_2, ndomain_3, id_gl_rank, nidx_local_1, nidx_local_2, nidx_local_3, nidx_local, nnod_local)
subroutine set_gl_nnod_spheric_rj (nproc, ndomain_1, ndomain_2, id_gl_rank, nidx_local_1, nidx_local_2, nidx_local, nnod_local)
subroutine set_gl_rank_3d (inner_r_flag, nproc, ndomain_3d, id_gl_rank)
subroutine set_gl_rank_2d (inner_r_flag, nproc, ndomain_2d, id_gl_rank)
integer(kind=kint) function set_rank_by_1b_sph_rank (inner_r_flag, ndomain_3d, ip_r, ip_t, ip_p)
integer(kind=kint) function set_rank_by_1b_rj_rank (inner_r_flag, ndomain_2d, ip_r, ip_j)
subroutine check_spheric_global_numnod (id_rank, sph_rtp, sph_rtm, sph_rlm, sph_rj)
Detailed Description
Set global resolution of spherical hermonics.
      subroutine set_global_sph_resolution(l_truncation, m_folding,   &
     &          sph_rtp, sph_rtm, sph_rlm, sph_rj)
      subroutine set_global_rtm_resolution(l_truncation, m_folding,   &
     &                                     sph_rtp, sph_rtm)
      subroutine set_global_rlm_resolution(l_truncation, m_folding,   &
     &                                     nidx_global_rtp_r, sph_rlm)
        type(sph_rtp_grid), intent(inout) :: sph_rtp
        type(sph_rtm_grid), intent(inout) :: sph_rtm
        type(sph_rlm_grid), intent(inout) :: sph_rlm
        type(sph_rj_grid), intent(inout) :: sph_rj
        required resoplution:  nidx_global_rtp(1)
                               nidx_global_rtp(2)
        required resolution:  l_truncation
      subroutine set_gl_nnod_spherical(nproc,                         &
     &          ndomain_1, ndomain_2, ndomain_3, id_gl_rank,          &
     &          nidx_local_1, nidx_local_2, nidx_local_3,             &
     &          nidx_local, nnod_local)
      subroutine set_gl_nnod_spheric_rj(nproc, ndomain_1, ndomain_2,  &
     &          id_gl_rank, nidx_local_1, nidx_local_2,               &
     &          nidx_local, nnod_local)
      subroutine set_gl_rank_3d                                       &
     &         (inner_r_flag, nproc, ndomain_3d, id_gl_rank)
      subroutine set_gl_rank_2d                                       &
     &         (inner_r_flag, nproc, ndomain_2d, id_gl_rank)
      integer(kind = kint) function set_rank_by_1b_sph_rank            &
     &                  (inner_r_flag, ndomain_3d, ip_r, ip_t, ip_p)
      integer(kind = kint) function set_rank_by_1b_rj_rank             &
     &                  (inner_r_flag, ndomain_2d, ip_r, ip_j)
      subroutine check_spheric_global_numnod(id_rank)
Function/Subroutine Documentation
check_spheric_global_numnod()
subroutine set_global_spherical_param::check_spheric_global_numnod (integer, intent(in) id_rank, type(sph_rtp_grid), intent(in) sph_rtp, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_rj_grid), intent(in) sph_rj)
Definition at line 294 of file set_global_spherical_param.f90.
set_gl_nnod_spheric_rj()
subroutine set_global_spherical_param::set_gl_nnod_spheric_rj (integer(kind = kint), intent(in) nproc, integer(kind = kint), intent(in) ndomain_1, integer(kind = kint), intent(in) ndomain_2, integer(kind = kint), dimension(2,0:(nproc-1)), intent(in) id_gl_rank, integer(kind = kint), dimension(ndomain_1), intent(in) nidx_local_1, integer(kind = kint), dimension(ndomain_2), intent(in) nidx_local_2, integer(kind = kint), dimension(nproc,2), intent(inout) nidx_local, integer(kind = kint), dimension(nproc), intent(inout) nnod_local)
Definition at line 161 of file set_global_spherical_param.f90.
Referenced by const_each_global_sph_list::const_global_rj_modes_by_rlm(), and const_each_global_sph_list::const_global_rlm_modes().
set_gl_nnod_spherical()
subroutine set_global_spherical_param::set_gl_nnod_spherical (integer(kind = kint), intent(in) nproc, integer(kind = kint), intent(in) ndomain_1, integer(kind = kint), intent(in) ndomain_2, integer(kind = kint), intent(in) ndomain_3, integer(kind = kint), dimension(3,0:(nproc-1)), intent(in) id_gl_rank, integer(kind = kint), dimension(ndomain_1), intent(in) nidx_local_1, integer(kind = kint), dimension(ndomain_2), intent(in) nidx_local_2, integer(kind = kint), dimension(ndomain_3), intent(in) nidx_local_3, integer(kind = kint), dimension(nproc,3), intent(inout) nidx_local, integer(kind = kint), dimension(nproc), intent(inout) nnod_local)
Definition at line 125 of file set_global_spherical_param.f90.
Referenced by const_each_global_sph_list::const_global_rtm_grids(), const_each_global_sph_list::const_global_rtp_grids(), and const_fem_mesh_sph_mhd::const_global_rtp_mesh().
set_gl_rank_2d()
subroutine set_global_spherical_param::set_gl_rank_2d (logical, intent(in) inner_r_flag, integer(kind = kint), intent(in) nproc, integer(kind = kint), dimension(2), intent(in) ndomain_2d, integer(kind = kint), dimension(2,0:(nproc-1)), intent(inout) id_gl_rank)
Definition at line 225 of file set_global_spherical_param.f90.
Referenced by const_each_global_sph_list::const_global_rj_modes_by_rlm(), and const_each_global_sph_list::const_global_rlm_modes().
set_gl_rank_3d()
subroutine set_global_spherical_param::set_gl_rank_3d (logical, intent(in) inner_r_flag, integer(kind = kint), intent(in) nproc, integer(kind = kint), dimension(3), intent(in) ndomain_3d, integer(kind = kint), dimension(3,0:(nproc-1)), intent(inout) id_gl_rank)
Definition at line 192 of file set_global_spherical_param.f90.
Referenced by const_each_global_sph_list::const_global_rtm_grids(), and const_each_global_sph_list::const_global_rtp_grids().
set_global_rlm_resolution()
subroutine set_global_spherical_param::set_global_rlm_resolution (integer(kind = kint), intent(in) l_truncation, integer(kind = kint), intent(in) m_folding, integer(kind = kint), intent(in) nidx_global_rtp_r, type(sph_rlm_grid), intent(inout) sph_rlm)
Definition at line 106 of file set_global_spherical_param.f90.
Referenced by set_comm_table_rtp_rj::set_comm_table_4_rj(), and set_global_sph_resolution().
set_global_rtm_resolution()
subroutine set_global_spherical_param::set_global_rtm_resolution (integer(kind = kint), intent(in) l_truncation, integer(kind = kint), intent(in) m_folding, type(sph_rtp_grid), intent(in) sph_rtp, type(sph_rtm_grid), intent(inout) sph_rtm)
Definition at line 89 of file set_global_spherical_param.f90.
Referenced by set_comm_table_rtp_rj::set_comm_table_4_rtp(), and set_global_sph_resolution().
set_global_sph_resolution()
subroutine set_global_spherical_param::set_global_sph_resolution (integer(kind = kint), intent(in) l_truncation, integer(kind = kint), intent(in) m_folding, type(sph_rtp_grid), intent(inout) sph_rtp, type(sph_rtm_grid), intent(inout) sph_rtm, type(sph_rlm_grid), intent(inout) sph_rlm, type(sph_rj_grid), intent(inout) sph_rj)
Definition at line 58 of file set_global_spherical_param.f90.
References set_global_rlm_resolution(), and set_global_rtm_resolution().
Referenced by mpi_gen_sph_grids_modes::const_sph_global_parameters().
set_rank_by_1b_rj_rank()
integer(kind = kint) function set_global_spherical_param::set_rank_by_1b_rj_rank (logical, intent(in) inner_r_flag, integer(kind = kint), dimension(2), intent(in) ndomain_2d, integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_j)
Definition at line 275 of file set_global_spherical_param.f90.
Referenced by set_comm_table_rtm_rlm::count_comm_table_4_rlm(), and set_comm_table_rtm_rlm::set_comm_table_4_rlm().
set_rank_by_1b_sph_rank()
integer(kind = kint) function set_global_spherical_param::set_rank_by_1b_sph_rank (logical, intent(in) inner_r_flag, integer(kind = kint), dimension(3), intent(in) ndomain_3d, integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, integer(kind = kint), intent(in) ip_p)
Definition at line 253 of file set_global_spherical_param.f90.
Referenced by set_comm_table_rtm_rlm::count_comm_table_4_rtm(), and set_comm_table_rtm_rlm::set_comm_table_4_rtm().