CALYPSO: output_viz_file_control Module Reference
output_viz_file_control Module Reference
Functions/Subroutines
logical function lead_field_data_flag (i_step, MHD_step)
logical function mhd_viz_routine_flag (flex_p, time_d, viz_step)
subroutine mhd_viz_routine_step (flex_p, time_d, viz_step)
logical function iflag_viz_output (iflag_flexible_step, i_step_fix, time_d, IO_step)
integer(kind=kint) function viz_time_step (iflag_flexible_step, i_step_fix, time_d, IO_step)
Function/Subroutine Documentation
iflag_viz_output()
logical function output_viz_file_control::iflag_viz_output (integer(kind = kint), intent(in) iflag_flexible_step, integer(kind = kint), intent(in) i_step_fix, type(time_data), intent(in) time_d, type(io_step_param), intent(in) IO_step)
Definition at line 100 of file output_viz_file_control.f90.
References t_flex_delta_t_parameter::iflag_flex_step, t_io_step_parameter::iflag_viz_flex_step(), and t_io_step_parameter::output_io_flag().
lead_field_data_flag()
logical function output_viz_file_control::lead_field_data_flag (integer(kind = kint), intent(in) i_step, type(mhd_step_param), intent(in) MHD_step)
Definition at line 32 of file output_viz_file_control.f90.
References m_machine_parameter::iflag_debug, and t_io_step_parameter::output_io_flag().
Referenced by analyzer_sph_dynamobench::evolution_sph_dynamobench(), analyzer_sph_mhd_w_psf::evolution_sph_mhd_w_psf(), analyzer_sph_snap_w_psf::evolution_sph_snap_w_psf(), fem_analyzer_sph_mhd::fem_analyze_sph_mhd(), sph_analyzer_d_bench::sph_analyze_dbench(), sph_analyzer_mhd::sph_analyze_mhd(), and sph_analyzer_snap_w_psf::sph_analyze_snap_psf().
mhd_viz_routine_flag()
logical function output_viz_file_control::mhd_viz_routine_flag (type(flexible_stepping_parameter), intent(in) flex_p, type(time_data), intent(in) time_d, type(viz_step_params), intent(inout) viz_step)
Definition at line 60 of file output_viz_file_control.f90.
References t_flex_delta_t_parameter::iflag_flex_step.
mhd_viz_routine_step()
subroutine output_viz_file_control::mhd_viz_routine_step (type(flexible_stepping_parameter), intent(in) flex_p, type(time_data), intent(in) time_d, type(viz_step_params), intent(inout) viz_step)
Definition at line 80 of file output_viz_file_control.f90.
References t_flex_delta_t_parameter::iflag_flex_step.
viz_time_step()
integer(kind = kint) function output_viz_file_control::viz_time_step (integer(kind = kint), intent(in) iflag_flexible_step, integer(kind = kint), intent(in) i_step_fix, type(time_data), intent(in) time_d, type(io_step_param), intent(in) IO_step)
Definition at line 123 of file output_viz_file_control.f90.
References t_flex_delta_t_parameter::iflag_flex_step, t_io_step_parameter::istep_file_w_fix_dt(), and t_io_step_parameter::istep_file_w_flex_dt().