CALYPSO: sph_rtp_fftw Module Reference
sph_rtp_fftw Module Reference
Fourier transform using FFTW Ver.3.
Functions/Subroutines
subroutine init_rtp_fftw (sph_rtp, comm_rtp, ncomp_bwd, ncomp_fwd, FFTW_f)
subroutine verify_rtp_fftw (sph_rtp, comm_rtp, ncomp_bwd, ncomp_fwd, FFTW_f)
subroutine rtp_fwd_fftw_to_send (sph_rtp, comm_rtp, ncomp_fwd, n_WS, X_rtp, WS, FFTW_f)
subroutine rtp_back_fftw_from_recv (sph_rtp, comm_rtp, ncomp_bwd, n_WR, WR, X_rtp, FFTW_f)
Detailed Description
Fourier transform using FFTW Ver.3.
 ------------------------------------------------------------------
      subroutine init_rtp_FFTW(sph_rtp, comm_rtp,                     &
     &                         ncomp_bwd, ncomp_fwd, FFTW_f)
      subroutine verify_rtp_FFTW(sph_rtp, comm_rtp,                   &
     &                           ncomp_bwd, ncomp_fwd, FFTW_f)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_comm_tbl), intent(in)  :: comm_rtp
   wrapper subroutine for initierize FFT by FFTW
 ------------------------------------------------------------------
      subroutine rtp_fwd_FFTW_to_send                                 &
     &         (sph_rtp, comm_rtp, ncomp_fwd, n_WS, X_rtp, WS, FFTW_f)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_comm_tbl), intent(in)  :: comm_rtp
 ------------------------------------------------------------------
 wrapper subroutine for forward Fourier transform by FFTW3
   a_{k} = \frac{2}{Nfft} \sum_{j=0}^{Nfft-1} x_{j} \cos (\frac{2\pi j k}{Nfft})
   b_{k} = \frac{2}{Nfft} \sum_{j=0}^{Nfft-1} x_{j} \cos (\frac{2\pi j k}{Nfft})
   a_{0} = \frac{1}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
    K = Nfft/2....
   a_{k} = \frac{1}{Nfft} \sum_{j=0}^{Nfft-1} x_{j} \cos (\frac{2\pi j k}{Nfft})
 ------------------------------------------------------------------
      subroutine rtp_back_FFTW_from_recv                              &
     &         (sph_rtp, comm_rtp, ncomp_bwd, n_WR, WR, X_rtp, FFTW_f)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_comm_tbl), intent(in)  :: comm_rtp
 ------------------------------------------------------------------
 wrapper subroutine for backward Fourier transform by FFTW3
   x_{k} = a_{0} + (-1)^{j} a_{Nfft/2} + sum_{k=1}^{Nfft/2-1}
          (a_{k} \cos(2\pijk/Nfft) + b_{k} \sin(2\pijk/Nfft))
 ------------------------------------------------------------------
       i = 1:     a_{0}
       i = 2:     a_{Nfft/2}
       i = 3:     a_{1}
       i = 4:     b_{1}
       ...
       i = 2*k+1: a_{k}
       i = 2*k+2: b_{k}
       ...
       i = Nfft-1:   a_{Nfft/2-1}
       i = Nfft:     b_{Nfft/2-1}
 ------------------------------------------------------------------
Parameters
Nstacksmp(0:np_smp) End number for each SMP process
Ncomp Number of components for Fourier transforms
Nfft Data length for eadh FFT
X(Ncomp,Nfft) Data for Fourier transform
Function/Subroutine Documentation
init_rtp_fftw()
subroutine sph_rtp_fftw::init_rtp_fftw (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), intent(in) ncomp_fwd, type(work_for_field_fftw), intent(inout) FFTW_f)
Definition at line 94 of file sph_rtp_FFTW.f90.
References t_sph_comm_table_from_fftw::alloc_comm_table_sph_fftw(), t_sph_field_fftw::alloc_whole_fftw_plan(), m_fftw_parameters::fftw_estimate, m_machine_parameter::np_smp, m_constants::one, and set_comm_table_rtp_fftw::set_comm_item_rtp_4_fftw().
Referenced by t_sph_fft_selector::init_sph_fft_select(), and verify_rtp_fftw().
rtp_back_fftw_from_recv()
subroutine sph_rtp_fftw::rtp_back_fftw_from_recv (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(in) WR, real(kind = kreal), dimension(sph_rtp%nnod_rtp,ncomp_bwd), intent(inout) X_rtp, type(work_for_field_fftw), intent(inout) FFTW_f)
Definition at line 234 of file sph_rtp_FFTW.f90.
References copy_rtp_data_to_fftpack::copy_fftpack_to_rtp_field(), set_comm_table_rtp_fftw::copy_rtp_fftw_field_from_recv(), m_elapsed_labels_sph_trns::iflag_fft_time, m_elapsed_labels_sph_trns::ist_elapsed_fft, and m_machine_parameter::np_smp.
Referenced by t_sph_fft_selector::back_fft_select_from_recv().
rtp_fwd_fftw_to_send()
subroutine sph_rtp_fftw::rtp_fwd_fftw_to_send (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, integer(kind = kint), intent(in) ncomp_fwd, integer(kind = kint), intent(in) n_WS, real(kind = kreal), dimension(sph_rtp%nnod_rtp,ncomp_fwd), intent(in) X_rtp, real (kind=kreal), dimension(n_ws), intent(inout) WS, type(work_for_field_fftw), intent(inout) FFTW_f)
Definition at line 181 of file sph_rtp_FFTW.f90.
References t_sph_comm_table_from_fftw::copy_all_rtp_fftw_to_send_smp(), copy_rtp_data_to_fftpack::copy_fftpack_from_rtp_field(), m_elapsed_labels_sph_trns::iflag_fft_time, m_elapsed_labels_sph_trns::ist_elapsed_fft, and m_machine_parameter::np_smp.
Referenced by t_sph_fft_selector::fwd_fft_select_to_send().
verify_rtp_fftw()
subroutine sph_rtp_fftw::verify_rtp_fftw (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), intent(in) ncomp_fwd, type(work_for_field_fftw), intent(inout) FFTW_f)
Definition at line 154 of file sph_rtp_FFTW.f90.
References t_sph_field_fftw::finalize_sph_field_fftw(), and init_rtp_fftw().
Referenced by t_sph_fft_selector::verify_sph_fft_select().