CALYPSO: t_ctl_data_4_platforms Module Reference
t_ctl_data_4_platforms Module Reference
Data Types
type platform_data_control
Structure of parallel and file information.
Functions/Subroutines
subroutine read_control_platforms (id_control, hd_block, plt, c_buf)
subroutine write_control_platforms (id_control, hd_block, plt, level)
subroutine reset_control_platforms (plt)
Variables
character(len=kchara), parameter, private hd_num_subdomain = 'num_subdomain_ctl'
character(len=kchara), parameter, private hd_num_smp = 'num_smp_ctl'
character(len=kchara), parameter, private hd_mesh_header = 'mesh_file_prefix'
character(len=kchara), parameter, private hd_udt_header = 'field_file_prefix'
character(len=kchara), parameter, private hd_rst_header = 'restart_file_prefix'
character(len=kchara), parameter, private hd_spectr_header = 'spectr_field_file_prefix'
character(len=kchara), parameter, private hd_sph_files_header = 'sph_file_prefix'
character(len=kchara), parameter, private hd_rayleigh_spectr_dir = 'rayleigh_spectr_dir'
character(len=kchara), parameter, private hd_rayleigh_field_dir = 'rayleigh_field_dir'
character(len=kchara), parameter, private hd_coriolis_tri_int_name = 'coriolis_int_file_name'
character(len=kchara), parameter, private hd_bc_data_file_name = 'boundary_data_file_name'
character(len=kchara), parameter, private hd_itp_sph_to_fem = 'interpolate_sph_to_fem_ctl'
character(len=kchara), parameter, private hd_itp_fem_to_sph = 'interpolate_fem_to_sph_ctl'
character(len=kchara), parameter, private hd_mesh_file_fmt = 'mesh_file_fmt_ctl'
character(len=kchara), parameter, private hd_rst_files_fmt = 'restart_file_fmt_ctl'
character(len=kchara), parameter, private hd_udt_files_fmt = 'field_file_fmt_ctl'
character(len=kchara), parameter, private hd_sph_files_fmt = 'sph_file_fmt_ctl'
character(len=kchara), parameter, private hd_itp_files_fmt = 'itp_file_fmt_ctl'
character(len=kchara), parameter, private hd_spect_field_fmt = 'spectr_field_fmt_ctl'
character(len=kchara), parameter, private hd_coriolis_file_fmt = 'coriolis_file_fmt_ctl'
character(len=kchara), parameter, private hd_debug_flag_ctl = 'debug_flag_ctl'
character(len=kchara), parameter, private hd_del_org_data = 'delete_original_data_flag'
Function/Subroutine Documentation
read_control_platforms()
subroutine t_ctl_data_4_platforms::read_control_platforms (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(platform_data_control), intent(inout) plt, type(buffer_for_control), intent(inout) c_buf)
Definition at line 224 of file t_ctl_data_4_platforms.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_bc_data_file_name, hd_coriolis_file_fmt, hd_coriolis_tri_int_name, hd_debug_flag_ctl, hd_del_org_data, hd_itp_fem_to_sph, hd_itp_files_fmt, hd_itp_sph_to_fem, hd_mesh_file_fmt, hd_mesh_header, hd_num_smp, hd_num_subdomain, hd_rayleigh_field_dir, hd_rayleigh_spectr_dir, hd_rst_files_fmt, hd_rst_header, hd_spect_field_fmt, hd_spectr_header, hd_sph_files_fmt, hd_sph_files_header, hd_udt_files_fmt, hd_udt_header, t_read_control_elements::load_one_line_from_control(), t_control_array_character::read_chara_ctl_type(), and t_control_array_integer::read_integer_ctl_type().
Referenced by t_control_data_4_merge::read_merge_control_data(), t_control_data_section_only::read_section_control_data(), t_ctl_data_mhd::read_sph_mhd_ctl_noviz(), t_ctl_data_mhd::read_sph_mhd_ctl_w_psf(), and t_ctl_data_const_sph_mesh::read_sph_shell_define_ctl().
reset_control_platforms()
subroutine t_ctl_data_4_platforms::reset_control_platforms (type(platform_data_control), intent(inout) plt)
Definition at line 403 of file t_ctl_data_4_platforms.f90.
Referenced by t_control_data_4_merge::reset_merge_control_data(), and t_control_data_section_only::reset_section_control_data().
write_control_platforms()
subroutine t_ctl_data_4_platforms::write_control_platforms (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(platform_data_control), intent(in) plt, integer(kind = kint), intent(inout) level)
Definition at line 304 of file t_ctl_data_4_platforms.f90.
References hd_bc_data_file_name, hd_coriolis_file_fmt, hd_coriolis_tri_int_name, hd_debug_flag_ctl, hd_del_org_data, hd_itp_fem_to_sph, hd_itp_files_fmt, hd_itp_sph_to_fem, hd_mesh_file_fmt, hd_mesh_header, hd_num_smp, hd_num_subdomain, hd_rayleigh_field_dir, hd_rayleigh_spectr_dir, hd_rst_files_fmt, hd_rst_header, hd_spect_field_fmt, hd_spectr_header, hd_sph_files_fmt, hd_sph_files_header, hd_udt_files_fmt, hd_udt_header, write_control_elements::write_begin_flag_for_ctl(), t_control_array_character::write_chara_ctl_type(), write_control_elements::write_end_flag_for_ctl(), and t_control_array_integer::write_integer_ctl_type().
Variable Documentation
hd_bc_data_file_name
character(len=kchara), parameter, private t_ctl_data_4_platforms::hd_bc_data_file_name = 'boundary_data_file_name' private
Definition at line 190 of file t_ctl_data_4_platforms.f90.
Referenced by read_control_platforms(), and write_control_platforms().
hd_coriolis_file_fmt
character(len=kchara), parameter, private t_ctl_data_4_platforms::hd_coriolis_file_fmt = 'coriolis_file_fmt_ctl' private
Definition at line 209 of file t_ctl_data_4_platforms.f90.
Referenced by read_control_platforms(), and write_control_platforms().
hd_coriolis_tri_int_name
character(len=kchara), parameter, private t_ctl_data_4_platforms::hd_coriolis_tri_int_name = 'coriolis_int_file_name' private
Definition at line 188 of file t_ctl_data_4_platforms.f90.
Referenced by read_control_platforms(), and write_control_platforms().
hd_debug_flag_ctl
character(len=kchara), parameter, private t_ctl_data_4_platforms::hd_debug_flag_ctl = 'debug_flag_ctl' private
Definition at line 212 of file t_ctl_data_4_platforms.f90.
Referenced by read_control_platforms(), and write_control_platforms().
hd_del_org_data
character(len=kchara), parameter, private t_ctl_data_4_platforms::hd_del_org_data = 'delete_original_data_flag' private
Definition at line 215 of file t_ctl_data_4_platforms.f90.
Referenced by read_control_platforms(), and write_control_platforms().
hd_itp_fem_to_sph
character(len=kchara), parameter, private t_ctl_data_4_platforms::hd_itp_fem_to_sph = 'interpolate_fem_to_sph_ctl' private
Definition at line 194 of file t_ctl_data_4_platforms.f90.
Referenced by read_control_platforms(), and write_control_platforms().
hd_itp_files_fmt
character(len=kchara), parameter, private t_ctl_data_4_platforms::hd_itp_files_fmt = 'itp_file_fmt_ctl' private
Definition at line 205 of file t_ctl_data_4_platforms.f90.
Referenced by read_control_platforms(), and write_control_platforms().
hd_itp_sph_to_fem
character(len=kchara), parameter, private t_ctl_data_4_platforms::hd_itp_sph_to_fem = 'interpolate_sph_to_fem_ctl' private
Definition at line 192 of file t_ctl_data_4_platforms.f90.
Referenced by read_control_platforms(), and write_control_platforms().
hd_mesh_file_fmt
character(len=kchara), parameter, private t_ctl_data_4_platforms::hd_mesh_file_fmt = 'mesh_file_fmt_ctl' private
Definition at line 197 of file t_ctl_data_4_platforms.f90.
Referenced by read_control_platforms(), and write_control_platforms().
hd_mesh_header
character(len=kchara), parameter, private t_ctl_data_4_platforms::hd_mesh_header = 'mesh_file_prefix' private
Definition at line 170 of file t_ctl_data_4_platforms.f90.
Referenced by read_control_platforms(), and write_control_platforms().
hd_num_smp
character(len=kchara), parameter, private t_ctl_data_4_platforms::hd_num_smp = 'num_smp_ctl' private
Definition at line 167 of file t_ctl_data_4_platforms.f90.
Referenced by read_control_platforms(), and write_control_platforms().
hd_num_subdomain
character(len=kchara), parameter, private t_ctl_data_4_platforms::hd_num_subdomain = 'num_subdomain_ctl' private
Definition at line 165 of file t_ctl_data_4_platforms.f90.
Referenced by read_control_platforms(), and write_control_platforms().
hd_rayleigh_field_dir
character(len=kchara), parameter, private t_ctl_data_4_platforms::hd_rayleigh_field_dir = 'rayleigh_field_dir' private
Definition at line 185 of file t_ctl_data_4_platforms.f90.
Referenced by read_control_platforms(), and write_control_platforms().
hd_rayleigh_spectr_dir
character(len=kchara), parameter, private t_ctl_data_4_platforms::hd_rayleigh_spectr_dir = 'rayleigh_spectr_dir' private
Definition at line 183 of file t_ctl_data_4_platforms.f90.
Referenced by read_control_platforms(), and write_control_platforms().
hd_rst_files_fmt
character(len=kchara), parameter, private t_ctl_data_4_platforms::hd_rst_files_fmt = 'restart_file_fmt_ctl' private
Definition at line 199 of file t_ctl_data_4_platforms.f90.
Referenced by read_control_platforms(), and write_control_platforms().
hd_rst_header
character(len=kchara), parameter, private t_ctl_data_4_platforms::hd_rst_header = 'restart_file_prefix' private
Definition at line 175 of file t_ctl_data_4_platforms.f90.
Referenced by read_control_platforms(), and write_control_platforms().
hd_spect_field_fmt
character(len=kchara), parameter, private t_ctl_data_4_platforms::hd_spect_field_fmt = 'spectr_field_fmt_ctl' private
Definition at line 207 of file t_ctl_data_4_platforms.f90.
Referenced by read_control_platforms(), and write_control_platforms().
hd_spectr_header
character(len=kchara), parameter, private t_ctl_data_4_platforms::hd_spectr_header = 'spectr_field_file_prefix' private
Definition at line 177 of file t_ctl_data_4_platforms.f90.
Referenced by read_control_platforms(), and write_control_platforms().
hd_sph_files_fmt
character(len=kchara), parameter, private t_ctl_data_4_platforms::hd_sph_files_fmt = 'sph_file_fmt_ctl' private
Definition at line 203 of file t_ctl_data_4_platforms.f90.
Referenced by read_control_platforms(), and write_control_platforms().
hd_sph_files_header
character(len=kchara), parameter, private t_ctl_data_4_platforms::hd_sph_files_header = 'sph_file_prefix' private
Definition at line 180 of file t_ctl_data_4_platforms.f90.
Referenced by read_control_platforms(), and write_control_platforms().
hd_udt_files_fmt
character(len=kchara), parameter, private t_ctl_data_4_platforms::hd_udt_files_fmt = 'field_file_fmt_ctl' private
Definition at line 201 of file t_ctl_data_4_platforms.f90.
Referenced by read_control_platforms(), and write_control_platforms().
hd_udt_header
character(len=kchara), parameter, private t_ctl_data_4_platforms::hd_udt_header = 'field_file_prefix' private
Definition at line 173 of file t_ctl_data_4_platforms.f90.
Referenced by read_control_platforms(), and write_control_platforms().