CALYPSO: mpi_mesh_data_io Module Reference
mpi_mesh_data_io Module Reference
Routines for gzipped binary mesh data IO.
Functions/Subroutines
subroutine mpi_write_geometry_data (IO_param, mesh_IO)
subroutine mpi_write_mesh_groups (IO_param, mesh_group_IO)
subroutine mpi_read_num_node (IO_param, mesh_IO)
subroutine mpi_read_num_node_ele (IO_param, mesh_IO)
subroutine mpi_read_geometry_data (IO_param, mesh_IO)
subroutine mpi_read_mesh_groups (IO_param, mesh_group_IO)
Detailed Description
Routines for gzipped binary mesh data IO.
      subroutine mpi_write_geometry_data(IO_param, mesh_IO)
      subroutine mpi_write_mesh_groups(IO_param, mesh_group_IO)
        type(mesh_geometry), intent(in) :: mesh_IO
        type(mesh_groups), intent(in) ::   mesh_group_IO
      subroutine mpi_read_num_node(IO_param, mesh_IO)
      subroutine mpi_read_num_node_ele(IO_param, mesh_IO)
      subroutine mpi_read_geometry_data(IO_param, mesh_IO)
      subroutine mpi_read_mesh_groups(IO_param, mesh_group_IO)
        type(mesh_geometry), intent(inout) :: mesh_IO
        type(mesh_groups), intent(inout) ::   mesh_group_IO
Function/Subroutine Documentation
mpi_read_geometry_data()
subroutine mpi_mesh_data_io::mpi_read_geometry_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 140 of file MPI_mesh_data_IO.f90.
References m_fem_mesh_labels::hd_fem_export(), m_fem_mesh_labels::hd_fem_import(), mpi_element_connect_io::mpi_read_element_info(), mpi_domain_data_io::mpi_read_export_data(), mpi_domain_data_io::mpi_read_import_data(), mpi_read_num_node_ele(), and mpi_ascii_data_io::mpi_skip_read().
Referenced by mpi_mesh_file_io::mpi_read_mesh_file(), and mpi_mesh_file_io::mpi_read_mesh_geometry().
mpi_read_mesh_groups()
subroutine mpi_mesh_data_io::mpi_read_mesh_groups (type(calypso_mpi_io_params), intent(inout) IO_param, type(mesh_groups), intent(inout) mesh_group_IO)
Definition at line 161 of file MPI_mesh_data_IO.f90.
References m_fem_mesh_labels::hd_fem_elegrp(), m_fem_mesh_labels::hd_fem_nodgrp(), m_fem_mesh_labels::hd_fem_sfgrp(), mpi_groups_io::mpi_read_group_data(), mpi_groups_io::mpi_read_surf_grp_data(), and mpi_ascii_data_io::mpi_skip_read().
Referenced by mpi_mesh_file_io::mpi_read_mesh_file().
mpi_read_num_node()
subroutine mpi_mesh_data_io::mpi_read_num_node (type(calypso_mpi_io_params), intent(inout) IO_param, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 106 of file MPI_mesh_data_IO.f90.
References m_fem_mesh_labels::hd_fem_node(), m_fem_mesh_labels::hd_fem_para(), mpi_domain_data_io::mpi_read_domain_info(), mpi_node_geometry_io::mpi_read_number_of_node(), and mpi_ascii_data_io::mpi_skip_read().
Referenced by mpi_mesh_file_io::mpi_read_node_size(), and mpi_read_num_node_ele().
mpi_read_num_node_ele()
subroutine mpi_mesh_data_io::mpi_read_num_node_ele (type(calypso_mpi_io_params), intent(inout) IO_param, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 122 of file MPI_mesh_data_IO.f90.
References m_fem_mesh_labels::hd_fem_elem(), mpi_node_geometry_io::mpi_read_geometry_info(), mpi_element_connect_io::mpi_read_num_element(), mpi_read_num_node(), and mpi_ascii_data_io::mpi_skip_read().
Referenced by mpi_read_geometry_data(), and mpi_mesh_file_io::mpi_read_geometry_size().
mpi_write_geometry_data()
subroutine mpi_mesh_data_io::mpi_write_geometry_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(mesh_geometry), intent(in) mesh_IO)
Definition at line 48 of file MPI_mesh_data_IO.f90.
References m_fem_mesh_labels::hd_fem_elem(), m_fem_mesh_labels::hd_fem_export(), m_fem_mesh_labels::hd_fem_import(), m_fem_mesh_labels::hd_fem_node(), m_fem_mesh_labels::hd_fem_para(), mpi_ascii_data_io::mpi_write_charahead(), mpi_domain_data_io::mpi_write_domain_info(), mpi_element_connect_io::mpi_write_element_info(), mpi_domain_data_io::mpi_write_export_data(), mpi_node_geometry_io::mpi_write_geometry_info(), and mpi_domain_data_io::mpi_write_import_data().
Referenced by mpi_mesh_file_io::mpi_write_mesh_file().
mpi_write_mesh_groups()
subroutine mpi_mesh_data_io::mpi_write_mesh_groups (type(calypso_mpi_io_params), intent(inout) IO_param, type(mesh_groups), intent(in) mesh_group_IO)
Definition at line 78 of file MPI_mesh_data_IO.f90.
References m_fem_mesh_labels::hd_fem_elegrp(), m_fem_mesh_labels::hd_fem_nodgrp(), m_fem_mesh_labels::hd_fem_sfgrp(), mpi_ascii_data_io::mpi_write_charahead(), mpi_groups_io::mpi_write_grp_data(), and mpi_groups_io::mpi_write_surf_grp_data().
Referenced by mpi_mesh_file_io::mpi_write_mesh_file().