CALYPSO: solver_sr_int Module Reference
solver_sr_int Module Reference
MPI SEND and RECEIVE routine for integer field in overlapped partitioning.
Functions/Subroutines
subroutine calypso_send_recv_intcore (npe_send, isend_self, id_pe_send, istack_send, npe_recv, irecv_self, id_pe_recv, istack_recv, SR_sig, SR_i)
subroutine calypso_alltoallv_intcore (npe_sr, istack_send, istack_recv, CALYPSO_SUB_COMM, SR_i)
subroutine calypso_alltoall_intcore (nitem_SR, CALYPSO_SUB_COMM, SR_i)
subroutine solver_send_recv_i (NP, NEIBPETOT, NEIBPE, STACK_IMPORT, NOD_IMPORT, STACK_EXPORT, NOD_EXPORT, SR_sig, SR_i, ix)
subroutine solver_send_recv_num (NEIBPETOT, NEIBPE, nSEND, nRECV, SR_sig)
Detailed Description
MPI SEND and RECEIVE routine for integer field in overlapped partitioning.
      subroutine calypso_send_recv_intcore                            &
     &         (npe_send, isend_self, id_pe_send, istack_send,        &
     &          npe_recv, irecv_self, id_pe_recv, istack_recv,        &
     &          SR_sig, SR_i)
      subroutine calypso_AllToAllv_intcore                            &
     &         (npe_sr, istack_send, istack_recv,                     &
     &          CALYPSO_SUB_COMM, SR_i)
      subroutine calypso_AllToAll_intcore                             &
     &         (nitem_SR, CALYPSO_SUB_COMM, SR_i)
        type(send_recv_status), intent(inout) :: SR_sig
        type(send_recv_int_buffer), intent(inout) :: SR_i
      subroutine  solver_send_recv_i                                  &
     &          (NP, NEIBPETOT, NEIBPE, STACK_IMPORT, NOD_IMPORT,     &
     &           STACK_EXPORT, NOD_EXPORT, SR_sig, SR_i, ix)
        type(send_recv_status), intent(inout) :: SR_sig
        type(send_recv_int_buffer), intent(inout) :: SR_i
      subroutine  solver_send_recv_num                                &
     &          (NEIBPETOT, NEIBPE, nSEND, nRECV, SR_sig)
        type(send_recv_status), intent(inout) :: SR_sig
Parameters
NP Number of data points
Parameters
NEIBPETOT Number of processses to communicate
NEIBPE(NEIBPETOT) Process ID to communicate
STACK_IMPORT(0:NEIBPETOT) End points of import buffer for each process
NOD_IMPORT(STACK_IMPORT(NEIBPETOT)) local node ID to copy in import buffer
STACK_EXPORT(0:NEIBPETOT) End points of export buffer for each process
NOD_EXPORT(STACK_IMPORT(NEIBPETOT)) local node ID to copy in export buffer
Parameters
ix(N) integer data with NB components
ix8(N) 8 byte integer data with NB components
Parameters
nSEND(NEIBPETOT) Number of component to send
nRECV(NEIBPETOT) Number of component to recv
Function/Subroutine Documentation
calypso_alltoall_intcore()
subroutine solver_sr_int::calypso_alltoall_intcore (integer(kind = kint), intent(in) nitem_SR, integer, intent(in) CALYPSO_SUB_COMM, type(send_recv_int_buffer), intent(inout) SR_i)
Definition at line 166 of file solver_SR_int.f90.
References calypso_mpi::calypso_integer, and calypso_mpi::ierr_mpi.
calypso_alltoallv_intcore()
subroutine solver_sr_int::calypso_alltoallv_intcore (integer(kind = kint), intent(in) npe_sr, integer(kind = kint), dimension(0:npe_sr), intent(in) istack_send, integer(kind = kint), dimension(0:npe_sr), intent(in) istack_recv, integer, intent(in) CALYPSO_SUB_COMM, type(send_recv_int_buffer), intent(inout) SR_i)
Parameters
[in,out] sr_i Structure of communication buffer for integer
Definition at line 135 of file solver_SR_int.f90.
References calypso_mpi::calypso_integer, and calypso_mpi::ierr_mpi.
calypso_send_recv_intcore()
subroutine solver_sr_int::calypso_send_recv_intcore (integer(kind = kint), intent(in) npe_send, integer(kind = kint), intent(in) isend_self, integer(kind = kint), dimension(npe_send), intent(in) id_pe_send, integer(kind = kint), dimension(0:npe_send), intent(in) istack_send, integer(kind = kint), intent(in) npe_recv, integer(kind = kint), intent(in) irecv_self, integer(kind = kint), dimension(npe_recv), intent(in) id_pe_recv, integer(kind = kint), dimension(0:npe_recv), intent(in) istack_recv, type(send_recv_status), intent(inout) SR_sig, type(send_recv_int_buffer), intent(inout) SR_i)
Definition at line 71 of file solver_SR_int.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_integer, and calypso_mpi::ierr_mpi.
Referenced by calypso_sr_int::calypso_send_recv_int().
solver_send_recv_i()
subroutine solver_sr_int::solver_send_recv_i (integer(kind=kint), intent(in) NP, integer(kind=kint), intent(in) NEIBPETOT, integer(kind=kint), dimension(neibpetot) NEIBPE, integer(kind=kint), dimension(0:neibpetot) STACK_IMPORT, integer(kind=kint), dimension(stack_import(neibpetot)) NOD_IMPORT, integer(kind=kint), dimension(0:neibpetot) STACK_EXPORT, integer(kind=kint), dimension(stack_export(neibpetot)) NOD_EXPORT, type(send_recv_status), intent(inout) SR_sig, type(send_recv_int_buffer), intent(inout) SR_i, integer (kind=kint), dimension(np), intent(inout) ix)
Parameters
[in] np number of nodes
[in] neibpetot total neighboring pe count
neibpe neighboring pe id (i-th pe)
stack_import imported node count for each neighbor pe (i-th pe)
nod_import imported node (i-th dof)
stack_export exported node count for each neighbor pe (i-th pe)
nod_export exported node (i-th dof)
[in,out] ix communicated result vector
[in,out] sr_sig Structure of communication flags
[in,out] sr_i Structure of communication buffer for integer
Definition at line 186 of file solver_SR_int.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_integer, calypso_mpi::ierr_mpi, and t_solver_sr_int::resize_iwork_sr_t().
Referenced by solver_sr_type::solver_send_recv_int_type().
solver_send_recv_num()
subroutine solver_sr_int::solver_send_recv_num (integer(kind=kint), intent(in) NEIBPETOT, integer(kind=kint), dimension(neibpetot) NEIBPE, integer (kind=kint), dimension(neibpetot), intent(in) nSEND, integer (kind=kint), dimension(neibpetot), intent(inout) nRECV, type(send_recv_status), intent(inout) SR_sig)
Parameters
[in] neibpetot total neighboring pe count
neibpe neighboring pe id (i-th pe)
[in] nsend Number of componennt to send
[in,out] nrecv Number of componennt to recv
[in,out] sr_sig Structure of communication flags
Definition at line 273 of file solver_SR_int.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_integer, calypso_mpi::ierr_mpi, and t_solver_sr::resize_sr_flag().
Referenced by solver_sr_type::solver_send_recv_num_type().