CALYPSO: domain_data_io Module Reference
domain_data_io Module Reference
Routine for doimain data IO.
Functions/Subroutines
subroutine read_domain_info (id_file, id_rank, comm_IO, ierr)
subroutine read_import_data (id_file, comm_IO)
subroutine read_export_data (id_file, comm_IO)
subroutine write_domain_info (id_file, id_rank, comm_IO)
subroutine write_import_data (id_file, comm_IO)
subroutine write_export_data (id_file, comm_IO)
Detailed Description
Routine for doimain data IO.
      subroutine read_domain_info(id_file, id_rank, comm_IO, ierr)
      subroutine read_import_data(id_file, comm_IO)
      subroutine read_export_data(id_file, comm_IO)
        type(communication_table), intent(inout) :: comm_IO
      subroutine write_domain_info(id_file, id_rank, comm_IO)
      subroutine write_import_data(id_file, comm_IO)
      subroutine write_export_data(id_file, comm_IO)
        type(communication_table), intent(in) :: comm_IO
Function/Subroutine Documentation
read_domain_info()
subroutine domain_data_io::read_domain_info (integer(kind = kint), intent(in) id_file, integer, intent(in) id_rank, type(communication_table), intent(inout) comm_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 40 of file domain_data_IO.f90.
References t_comm_table::alloc_neighbouring_id(), m_error_ids::ierr_mesh, and skip_comment_f::skip_comment().
Referenced by edge_data_io::read_edge_connection(), element_data_io::read_element_comm_table(), mesh_data_io::read_filter_geometry(), sph_modes_grids_data_io::read_geom_rtm_data(), sph_modes_grids_data_io::read_geom_rtp_data(), mesh_data_io::read_num_node(), sph_modes_grids_data_io::read_spectr_modes_rj_data(), sph_modes_grids_data_io::read_spectr_modes_rlm_data(), and surface_data_io::read_surface_connection().
read_export_data()
subroutine domain_data_io::read_export_data (integer(kind = kint), intent(in) id_file, type(communication_table), intent(inout) comm_IO)
Definition at line 101 of file domain_data_IO.f90.
References t_comm_table::alloc_export_item(), t_comm_table::alloc_export_num(), m_constants::izero, field_data_io::read_arrays_for_stacks(), and comm_table_io::read_send_recv_item().
Referenced by edge_data_io::read_edge_connection(), element_data_io::read_element_comm_table(), mesh_data_io::read_filter_geometry(), mesh_data_io::read_geometry_data(), and surface_data_io::read_surface_connection().
read_import_data()
subroutine domain_data_io::read_import_data (integer(kind = kint), intent(in) id_file, type(communication_table), intent(inout) comm_IO)
Definition at line 76 of file domain_data_IO.f90.
References t_comm_table::alloc_import_item(), t_comm_table::alloc_import_num(), m_constants::izero, field_data_io::read_arrays_for_stacks(), and comm_table_io::read_send_recv_item().
Referenced by edge_data_io::read_edge_connection(), element_data_io::read_element_comm_table(), mesh_data_io::read_filter_geometry(), sph_modes_grids_data_io::read_geom_rtm_data(), sph_modes_grids_data_io::read_geom_rtp_data(), mesh_data_io::read_geometry_data(), sph_modes_grids_data_io::read_spectr_modes_rj_data(), sph_modes_grids_data_io::read_spectr_modes_rlm_data(), and surface_data_io::read_surface_connection().
write_domain_info()
subroutine domain_data_io::write_domain_info (integer(kind = kint), intent(in) id_file, integer, intent(in) id_rank, type(communication_table), intent(in) comm_IO)
Definition at line 126 of file domain_data_IO.f90.
Referenced by mesh_data_io::output_node_cyl_geometry(), mesh_data_io::output_node_sph_geometry(), edge_data_io::write_edge_connection(), element_data_io::write_element_comm_table(), mesh_data_io::write_filter_geometry(), sph_modes_grids_data_io::write_geom_rtm_data(), sph_modes_grids_data_io::write_geom_rtp_data(), mesh_data_io::write_geometry_data(), sph_modes_grids_data_io::write_modes_rlm_data(), sph_modes_grids_data_io::write_spectr_modes_rj_data(), and surface_data_io::write_surface_connection().
write_export_data()
subroutine domain_data_io::write_export_data (integer(kind = kint), intent(in) id_file, type(communication_table), intent(in) comm_IO)
Definition at line 168 of file domain_data_IO.f90.
References comm_table_io::write_send_recv_data().
Referenced by edge_data_io::write_edge_connection(), element_data_io::write_element_comm_table(), mesh_data_io::write_filter_geometry(), mesh_data_io::write_geometry_data(), and surface_data_io::write_surface_connection().
write_import_data()
subroutine domain_data_io::write_import_data (integer(kind = kint), intent(in) id_file, type(communication_table), intent(in) comm_IO)
Definition at line 154 of file domain_data_IO.f90.
References comm_table_io::write_send_recv_data().
Referenced by edge_data_io::write_edge_connection(), element_data_io::write_element_comm_table(), mesh_data_io::write_filter_geometry(), sph_modes_grids_data_io::write_geom_rtm_data(), sph_modes_grids_data_io::write_geom_rtp_data(), mesh_data_io::write_geometry_data(), sph_modes_grids_data_io::write_modes_rlm_data(), sph_modes_grids_data_io::write_spectr_modes_rj_data(), and surface_data_io::write_surface_connection().