CALYPSO: add_diff_vect_to_sph_trans Module Reference
add_diff_vect_to_sph_trans Module Reference
Add field addresses of difference of fields for spherical harmonics transform.
Functions/Subroutines
subroutine add_grad_4_sph_trns_by_pol (d_rj, ipol_grd, iphys_grd, b_trns_grd, trns)
subroutine add_grad_4_sph_trns_snap (d_rj, ipol_grd, iphys_grd, b_trns_grd, trns)
subroutine add_diff_vect_sph_trns_by_pol (d_rj, ipol_dv, iphys_dv, b_trns_dv, trns)
subroutine add_diff_vect_scalar_trns_bpol (d_rj, ipol_dv, iphys_dv, f_trns_dv, trns)
Detailed Description
Add field addresses of difference of fields for spherical harmonics transform.
      subroutine add_grad_4_sph_trns_by_pol                           &
     &         (d_rj, ipol_grd, iphys_grd, b_trns_grd, trns)
      subroutine add_grad_4_sph_trns_snap                             &
     &         (d_rj, ipol_grd, iphys_grd, b_trns_grd, trns)
        type(phys_data), intent(in) :: d_rj
        type(gradient_field_address), intent(in) :: ipol_grd
        type(gradient_field_address), intent(in) :: iphys_grd
        type(gradient_field_address), intent(inout) :: b_trns_grd
        type(spherical_transform_data), intent(inout) :: trns
      subroutine add_diff_vect_sph_trns_by_pol                        &
     &         (d_rj, ipol_dv, iphys_dv, b_trns_dv, trns)
      subroutine add_diff_vect_scalar_trns_bpol                       &
     &         (d_rj, ipol_dv, iphys_dv, f_trns_dv, trns)
        type(phys_data), intent(in) :: d_rj
        type(diff_vector_address), intent(in) :: ipol_dv, iphys_dv
        type(diff_vector_address), intent(inout) :: b_trns_dv
        type(spherical_transform_data), intent(inout) :: trns
Function/Subroutine Documentation
add_diff_vect_scalar_trns_bpol()
subroutine add_diff_vect_to_sph_trans::add_diff_vect_scalar_trns_bpol (type(phys_data), intent(in) d_rj, type(diff_vector_address), intent(in) ipol_dv, type(diff_vector_address), intent(in) iphys_dv, type(diff_vector_address), intent(inout) f_trns_dv, type(spherical_transform_data), intent(inout) trns)
Definition at line 180 of file add_diff_vect_to_sph_trans.f90.
References add_field_to_sph_trans_list::add_scalar_4_sph_trns_by_pol().
Referenced by address_sph_trans_snap::fwd_trans_address_diff_vect().
add_diff_vect_sph_trns_by_pol()
subroutine add_diff_vect_to_sph_trans::add_diff_vect_sph_trns_by_pol (type(phys_data), intent(in) d_rj, type(diff_vector_address), intent(in) ipol_dv, type(diff_vector_address), intent(in) iphys_dv, type(diff_vector_address), intent(inout) b_trns_dv, type(spherical_transform_data), intent(inout) trns)
Definition at line 100 of file add_diff_vect_to_sph_trans.f90.
References add_field_to_sph_trans_list::add_field_4_sph_trns_by_pol().
Referenced by address_sph_trans_snap::bwd_trans_address_diff_vect().
add_grad_4_sph_trns_by_pol()
subroutine add_diff_vect_to_sph_trans::add_grad_4_sph_trns_by_pol (type(phys_data), intent(in) d_rj, type(gradient_field_address), intent(in) ipol_grd, type(gradient_field_address), intent(in) iphys_grd, type(gradient_field_address), intent(inout) b_trns_grd, type(spherical_transform_data), intent(inout) trns)
Definition at line 47 of file add_diff_vect_to_sph_trans.f90.
References add_field_to_sph_trans_list::add_field_4_sph_trns_by_pol().
add_grad_4_sph_trns_snap()
subroutine add_diff_vect_to_sph_trans::add_grad_4_sph_trns_snap (type(phys_data), intent(in) d_rj, type(gradient_field_address), intent(in) ipol_grd, type(gradient_field_address), intent(in) iphys_grd, type(gradient_field_address), intent(inout) b_trns_grd, type(spherical_transform_data), intent(inout) trns)
Definition at line 73 of file add_diff_vect_to_sph_trans.f90.
References add_field_to_sph_trans_list::add_field_name_4_sph_trns_snap().
Referenced by address_sph_trans_snap::bwd_trans_address_ene_flux().