CALYPSO: gz_mpi_element_connect_io_b Module Reference
gz_mpi_element_connect_io_b Module Reference
Data IO routines for element connectivity.
Functions/Subroutines
subroutine gz_mpi_write_element_info_b (IO_param, ele_IO)
subroutine gz_mpi_write_surf_4_ele_b (IO_param, sfed_IO)
subroutine gz_mpi_write_edge_4_ele_b (IO_param, sfed_IO)
subroutine gz_mpi_read_num_element_b (IO_param, ele_IO)
subroutine gz_mpi_read_ele_info_b (IO_param, ele_IO)
subroutine gz_mpi_read_surf_4_elem_b (IO_param, sfed_IO)
subroutine gz_mpi_read_edge_4_element_b (IO_param, sfed_IO)
Detailed Description
Data IO routines for element connectivity.
      subroutine gz_mpi_write_element_info_b(IO_param, ele_IO)
      subroutine gz_mpi_write_surf_4_ele_b(IO_param, sfed_IO)
      subroutine gz_mpi_write_edge_4_ele_b(IO_param, sfed_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(element_data), intent(in) :: ele_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
      subroutine gz_mpi_read_num_element_b(IO_param, ele_IO)
      subroutine gz_mpi_read_ele_info_b(IO_param, ele_IO)
      subroutine gz_mpi_read_surf_4_elem_b(IO_param, sfed_IO)
      subroutine gz_mpi_read_edge_4_element_b(IO_param, sfed_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(element_data), intent(inout) :: ele_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
Function/Subroutine Documentation
gz_mpi_read_edge_4_element_b()
subroutine gz_mpi_element_connect_io_b::gz_mpi_read_edge_4_element_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 179 of file gz_MPI_element_connect_IO_b.f90.
References t_surf_edge_io::alloc_edge_connect_io(), gz_mpi_binary_data_io::gz_mpi_read_int_vector_b(), and gz_mpi_binary_datum_io::gz_mpi_read_one_integer_b().
Referenced by gz_mpi_edge_data_io_b::gz_mpi_read_edge_connect_b().
gz_mpi_read_ele_info_b()
subroutine gz_mpi_element_connect_io_b::gz_mpi_read_ele_info_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(element_data), intent(inout) ele_IO)
Definition at line 121 of file gz_MPI_element_connect_IO_b.f90.
References t_geometry_data::alloc_ele_connectivity(), t_geometry_data::alloc_element_types(), gz_mpi_binary_data_io::gz_mpi_read_int8_vector_b(), gz_mpi_binary_data_io::gz_mpi_read_int_vector_b(), and set_nnod_4_ele_by_type::s_set_nnod_4_ele_by_type().
Referenced by gz_mpi_edge_data_io_b::gz_mpi_read_edge_connect_b(), gz_mpi_mesh_data_io_b::gz_mpi_read_geometry_data_b(), and gz_mpi_surface_data_io_b::gz_mpi_read_surf_connect_b().
gz_mpi_read_num_element_b()
subroutine gz_mpi_element_connect_io_b::gz_mpi_read_num_element_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(element_data), intent(inout) ele_IO)
Definition at line 109 of file gz_MPI_element_connect_IO_b.f90.
References gz_mpi_binary_datum_io::gz_mpi_read_one_integer_b().
Referenced by gz_mpi_edge_data_io_b::gz_mpi_read_edge_connect_b(), gz_mpi_mesh_data_io_b::gz_mpi_read_num_node_ele_b(), and gz_mpi_surface_data_io_b::gz_mpi_read_surf_connect_b().
gz_mpi_read_surf_4_elem_b()
subroutine gz_mpi_element_connect_io_b::gz_mpi_read_surf_4_elem_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 158 of file gz_MPI_element_connect_IO_b.f90.
References t_surf_edge_io::alloc_surface_connect_io(), gz_mpi_binary_data_io::gz_mpi_read_int_vector_b(), and gz_mpi_binary_datum_io::gz_mpi_read_one_integer_b().
Referenced by gz_mpi_edge_data_io_b::gz_mpi_read_edge_connect_b(), and gz_mpi_surface_data_io_b::gz_mpi_read_surf_connect_b().
gz_mpi_write_edge_4_ele_b()
subroutine gz_mpi_element_connect_io_b::gz_mpi_write_edge_4_ele_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 89 of file gz_MPI_element_connect_IO_b.f90.
References gz_mpi_binary_data_io::gz_mpi_write_int_vector_b(), and gz_mpi_binary_datum_io::gz_mpi_write_one_integer_b().
Referenced by gz_mpi_edge_data_io_b::gz_mpi_write_edge_connect_b().
gz_mpi_write_element_info_b()
subroutine gz_mpi_element_connect_io_b::gz_mpi_write_element_info_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(element_data), intent(in) ele_IO)
Definition at line 47 of file gz_MPI_element_connect_IO_b.f90.
References gz_mpi_binary_data_io::gz_mpi_write_int8_vector_b(), gz_mpi_binary_data_io::gz_mpi_write_int_vector_b(), and gz_mpi_binary_datum_io::gz_mpi_write_one_integer_b().
Referenced by gz_mpi_edge_data_io_b::gz_mpi_write_edge_connect_b(), gz_mpi_mesh_data_io_b::gz_mpi_write_geometry_data_b(), and gz_mpi_surface_data_io_b::gz_mpi_write_surf_connect_b().
gz_mpi_write_surf_4_ele_b()
subroutine gz_mpi_element_connect_io_b::gz_mpi_write_surf_4_ele_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 70 of file gz_MPI_element_connect_IO_b.f90.
References gz_mpi_binary_data_io::gz_mpi_write_int_vector_b(), and gz_mpi_binary_datum_io::gz_mpi_write_one_integer_b().
Referenced by gz_mpi_edge_data_io_b::gz_mpi_write_edge_connect_b(), and gz_mpi_surface_data_io_b::gz_mpi_write_surf_connect_b().