CALYPSO: t_field_on_circle Module Reference
t_field_on_circle Module Reference
field data on specific circle at (s,z)
Data Types
type circle_fld_maker
Functions/Subroutines
subroutine sph_transfer_on_circle (iflag_FFT, sph_rj, rj_fld, cdat)
subroutine const_circle_point_global (iflag_FFT, l_truncation, sph_rtp, sph_rj, cdat)
subroutine, private set_circle_point_global (nri, radius_1d_rj_r, circ_spec, circle)
subroutine, private collect_spectr_for_circle (jmax, nidx_global_rj, idx_gl_1d_rj_j, nnod_rj, num_phys_rj, ntot_phys_rj, istack_phys_comp_rj, phys_name_rj, d_rj, d_circle, circle)
Detailed Description
field data on specific circle at (s,z)
      subroutine sph_transfer_on_circle                               &
     &         (iflag_FFT, sph_rj, rj_fld, cdat)
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(phys_data), intent(in) :: rj_fld
        type(circle_fld_maker), intent(inout) :: cdat
      subroutine const_circle_point_global                            &
     &         (iflag_FFT, l_truncation, sph_rtp, sph_rj, cdat)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(circle_fld_maker), intent(inout) :: cdat
Function/Subroutine Documentation
collect_spectr_for_circle()
subroutine, private t_field_on_circle::collect_spectr_for_circle (integer(kind = kint), intent(in) jmax, integer(kind = kint), dimension(2), intent(in) nidx_global_rj, integer(kind = kint), dimension(jmax,3), intent(in) idx_gl_1d_rj_j, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) num_phys_rj, integer(kind = kint), intent(in) ntot_phys_rj, integer(kind = kint), dimension(0:num_phys_rj), intent(in) istack_phys_comp_rj, character (len=kchara), dimension(num_phys_rj), intent(in) phys_name_rj, real (kind=kreal), dimension(nnod_rj,ntot_phys_rj), intent(in) d_rj, type(phys_data), intent(in) d_circle, type(fields_on_circle), intent(inout) circle) private
Definition at line 179 of file t_field_on_circle.f90.
References calypso_mpi_real::calypso_mpi_reduce_real(), m_machine_parameter::iflag_debug, calypso_mpi::my_rank, and m_constants::zero.
Referenced by sph_transfer_on_circle().
const_circle_point_global()
subroutine t_field_on_circle::const_circle_point_global (integer(kind = kint), intent(in) iflag_FFT, integer(kind = kint), intent(in) l_truncation, type(sph_rtp_grid), intent(in) sph_rtp, type(sph_rj_grid), intent(in) sph_rj, type(circle_fld_maker), intent(inout) cdat)
Definition at line 111 of file t_field_on_circle.f90.
References t_circle_transform::alloc_circle_field(), t_circle_transform::alloc_circle_transform(), circle_transform_single::initialize_circle_transform(), and set_circle_point_global().
Referenced by field_at_mid_equator::set_mid_equator_point_global().
set_circle_point_global()
subroutine, private t_field_on_circle::set_circle_point_global (integer(kind = kint), intent(in) nri, real(kind = kreal), dimension(nri), intent(in) radius_1d_rj_r, type(circle_transform_spetr), intent(in) circ_spec, type(fields_on_circle), intent(inout) circle) private
Definition at line 141 of file t_field_on_circle.f90.
References m_constants::izero, m_constants::one, and m_constants::zero.
Referenced by const_circle_point_global().
sph_transfer_on_circle()
subroutine t_field_on_circle::sph_transfer_on_circle (integer(kind = kint), intent(in) iflag_FFT, type(sph_rj_grid), intent(in) sph_rj, type(phys_data), intent(in) rj_fld, type(circle_fld_maker), intent(inout) cdat)
Definition at line 55 of file t_field_on_circle.f90.
References circle_transform_single::circle_transfer_scalar(), circle_transform_single::circle_transfer_sym_tensor(), circle_transform_single::circle_transfer_vector(), collect_spectr_for_circle(), calypso_mpi::my_rank, m_phys_constants::n_sym_tensor, and m_phys_constants::n_vector.
Referenced by const_data_4_dynamobench::mid_eq_transfer_dynamobench().