CALYPSO: cvt_xyz_vector_2_cyl_smp Module Reference
cvt_xyz_vector_2_cyl_smp Module Reference
Functions/Subroutines
subroutine cvt_vector_2_cyl_smp (np_smp, numnod, inod_smp_stack, vect, v_cyl, xx, yy, rs, a_s)
subroutine overwrite_vector_2_cyl_smp (np_smp, numnod, inod_smp_stack, vect, xx, yy, rs, a_s)
subroutine cal_cylinder_r_comp_smp (np_smp, numnod, inod_smp_stack, vect, v_s, xx, yy, rs, a_s)
Function/Subroutine Documentation
cal_cylinder_r_comp_smp()
subroutine cvt_xyz_vector_2_cyl_smp::cal_cylinder_r_comp_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,3), intent(in) vect, real(kind=kreal), dimension(numnod), intent(inout) v_s, real(kind=kreal), dimension(numnod), intent(in) xx, real(kind=kreal), dimension(numnod), intent(in) yy, real(kind=kreal), dimension(numnod), intent(in) rs, real(kind=kreal), dimension(numnod), intent(in) a_s)
Definition at line 140 of file cvt_xyz_vector_2_cyl_smp.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and set_const_4_sections::set_constant_4_iso().
cvt_vector_2_cyl_smp()
subroutine cvt_xyz_vector_2_cyl_smp::cvt_vector_2_cyl_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,3), intent(in) vect, real(kind=kreal), dimension(numnod,3), intent(inout) v_cyl, real(kind=kreal), dimension(numnod), intent(in) xx, real(kind=kreal), dimension(numnod), intent(in) yy, real(kind=kreal), dimension(numnod), intent(in) rs, real(kind=kreal), dimension(numnod), intent(in) a_s)
Definition at line 58 of file cvt_xyz_vector_2_cyl_smp.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz().
overwrite_vector_2_cyl_smp()
subroutine cvt_xyz_vector_2_cyl_smp::overwrite_vector_2_cyl_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,3), intent(inout) vect, real(kind=kreal), dimension(numnod), intent(in) xx, real(kind=kreal), dimension(numnod), intent(in) yy, real(kind=kreal), dimension(numnod), intent(in) rs, real(kind=kreal), dimension(numnod), intent(in) a_s)
Definition at line 100 of file cvt_xyz_vector_2_cyl_smp.f90.
Referenced by coordinate_convert_4_sph::overwrite_nodal_xyz_2_cyl_smp().