CALYPSO: t_explicit_term_labels Module Reference
t_explicit_term_labels Module Reference
Data Types
type explicit_term_address
Work area for explicit terms.
Functions/Subroutines
subroutine set_work_field_addresses (i_phys, field_name, exp_work, flag)
subroutine set_check_field_addresses (i_phys, field_name, check_fld1, check_fld2, flag)
Function/Subroutine Documentation
set_check_field_addresses()
subroutine t_explicit_term_labels::set_check_field_addresses (integer(kind = kint), intent(in) i_phys, character(len = kchara), intent(in) field_name, type(explicit_term_address), intent(inout) check_fld1, type(explicit_term_address), intent(inout) check_fld2, logical, intent(inout) flag)
Definition at line 154 of file t_explicit_term_labels.f90.
References m_explicit_term_labels::check_composition, m_explicit_term_labels::check_composition_2, m_explicit_term_labels::check_heat, m_explicit_term_labels::check_heat_2, m_explicit_term_labels::check_induction, m_explicit_term_labels::check_induction_2, m_explicit_term_labels::check_momentum, m_explicit_term_labels::check_momentum_2, m_explicit_term_labels::check_potential, m_explicit_term_labels::check_potential_2, m_explicit_term_labels::check_pressure, m_explicit_term_labels::check_pressure_2, m_explicit_term_labels::check_scalar_check_field(), and m_explicit_term_labels::check_vector_check_field().
Referenced by set_mhd_field_address::set_mhd_field_addresses().
set_work_field_addresses()
subroutine t_explicit_term_labels::set_work_field_addresses (integer(kind = kint), intent(in) i_phys, character(len = kchara), intent(in) field_name, type(explicit_term_address), intent(inout) exp_work, logical, intent(inout) flag)
Definition at line 105 of file t_explicit_term_labels.f90.
References m_explicit_term_labels::check_scalar_work_field(), m_explicit_term_labels::check_vector_work_field(), m_explicit_term_labels::check_work_4_poisson(), m_explicit_term_labels::div_sum_forces, m_explicit_term_labels::m_potential_work, m_explicit_term_labels::pressure_work, m_explicit_term_labels::previous_composition, m_explicit_term_labels::previous_heat, m_explicit_term_labels::previous_induction, m_explicit_term_labels::previous_momentum, m_explicit_term_labels::previous_potential, m_explicit_term_labels::previous_pressure, m_explicit_term_labels::rot_sum_forces, and m_explicit_term_labels::sum_forces.
Referenced by set_mhd_field_address::set_mhd_field_addresses().