CALYPSO: cal_rms_by_sph_spectr Module Reference
cal_rms_by_sph_spectr Module Reference
Evaluate mean square data for each spherical harmonics mode.
Functions/Subroutines
subroutine cal_rms_sph_spec_one_mode (j, sph_rj, ipol, ncomp_rj, g_sph_rj, icomp_rj, n_point, ntot_phys_rj, d_rj, rms_sph_r)
subroutine cal_rms_sph_spec_one_field (sph_rj, ipol, ncomp_rj, g_sph_rj, icomp_rj, n_point, ntot_phys_rj, d_rj, rms_sph_rj)
subroutine cvt_mag_or_kin_ene_one_point (ipol_base, i_fld, rms_out)
subroutine cvt_mag_or_kin_ene_one_mode (sph_rj, ipol_base, icomp_rj, rms_sph_r)
subroutine cvt_mag_or_kin_ene_spectr (sph_rj, ipol_base, icomp_rj, rms_sph_rj)
Detailed Description
Evaluate mean square data for each spherical harmonics mode.
      subroutine cal_rms_sph_spec_one_mode                            &
     &         (j, sph_rj, ipol, ncomp_rj, g_sph_rj, icomp_rj,        &
     &          n_point, ntot_phys_rj, d_rj, rms_sph_r)
      subroutine cal_rms_sph_spec_one_field                           &
     &         (sph_rj, ipol, ncomp_rj, g_sph_rj, icomp_rj,           &
     &          n_point, ntot_phys_rj, d_rj, rms_sph_rj)
        type(sph_rj_grid), intent(in) :: sph_rj
        (1/4\pi) \int (\bf{u}_{l}^{m})^2 sin \theta d\theta d\phi
          = r^{-2} [ l(l+1) / (2l+1)
           ( l(l+1)/r^2 (S_{l}^{m})^2 + (dS_{l}^{m}/dr)^2)
            + (T_{l}^{m})^2 ) ]
      subroutine cvt_mag_or_kin_ene_one_point                         &
     &         (ipol_base, i_fld, rms_out)
      subroutine cvt_mag_or_kin_ene_one_mode                          &
     &         (sph_rj, ipol_base, icomp_rj, rms_sph_r)
      subroutine cvt_mag_or_kin_ene_spectr                            &
     &         (sph_rj, ipol_base, icomp_rj, rms_sph_rj)
        type(sph_rj_grid), intent(in) :: sph_rj
        type(base_field_address), intent(in) :: ipol_base
Parameters
d_rj spectrum data
rms_sph_rj mean square data
Function/Subroutine Documentation
cal_rms_sph_spec_one_field()
subroutine cal_rms_by_sph_spectr::cal_rms_sph_spec_one_field (type(sph_rj_grid), intent(in) sph_rj, type(phys_address), intent(in) ipol, integer(kind = kint), intent(in) ncomp_rj, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, integer(kind = kint), intent(in) icomp_rj, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(n_point,ntot_phys_rj), intent(in) d_rj, real(kind = kreal), dimension(0:sph_rj%nidx_rj(1),sph_rj%nidx_rj(2),ncomp_rj), intent(inout) rms_sph_rj)
Definition at line 97 of file cal_rms_by_sph_spectr.f90.
References cvt_mag_or_kin_ene_spectr(), cal_sph_mean_square::each_scalar_sph_spec(), cal_sph_mean_square::each_vector_sph_spec(), m_phys_constants::n_scalar, and m_phys_constants::n_vector.
Referenced by sum_sph_rms_data::sum_sph_layerd_rms().
cal_rms_sph_spec_one_mode()
subroutine cal_rms_by_sph_spectr::cal_rms_sph_spec_one_mode (integer(kind = kint), intent(in) j, type(sph_rj_grid), intent(in) sph_rj, type(phys_address), intent(in) ipol, integer(kind = kint), intent(in) ncomp_rj, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, integer(kind = kint), intent(in) icomp_rj, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(n_point,ntot_phys_rj), intent(in) d_rj, real(kind = kreal), dimension(0:sph_rj%nidx_rj(1),ncomp_rj), intent(inout) rms_sph_r)
Definition at line 49 of file cal_rms_by_sph_spectr.f90.
References cvt_mag_or_kin_ene_one_mode(), cal_sph_mean_square::degree_zero_vector_mean_square(), m_phys_constants::n_scalar, m_phys_constants::n_vector, cal_sph_mean_square::one_mode_scalar_mean_square(), and cal_sph_mean_square::one_mode_vector_mean_square().
cvt_mag_or_kin_ene_one_mode()
subroutine cal_rms_by_sph_spectr::cvt_mag_or_kin_ene_one_mode (type(sph_rj_grid), intent(in) sph_rj, type(base_field_address), intent(in) ipol_base, integer(kind = kint), intent(in) icomp_rj, real(kind = kreal), dimension(0:sph_rj%nidx_rj(1),3), intent(inout) rms_sph_r)
Definition at line 158 of file cal_rms_by_sph_spectr.f90.
References cal_sph_mean_square::one_mode_mean_sq_to_energy().
Referenced by cal_rms_sph_spec_one_mode().
cvt_mag_or_kin_ene_one_point()
subroutine cal_rms_by_sph_spectr::cvt_mag_or_kin_ene_one_point (type(base_field_address), intent(in) ipol_base, integer(kind = kint), intent(in) i_fld, real(kind=kreal), dimension(3), intent(inout) rms_out)
Definition at line 137 of file cal_rms_by_sph_spectr.f90.
References single_pt_sph_mean_square::one_point_mean_sq_to_energy().
cvt_mag_or_kin_ene_spectr()
subroutine cal_rms_by_sph_spectr::cvt_mag_or_kin_ene_spectr (type(sph_rj_grid), intent(in) sph_rj, type(base_field_address), intent(in) ipol_base, integer(kind = kint), intent(in) icomp_rj, real(kind = kreal), dimension(0:sph_rj%nidx_rj(1),sph_rj%nidx_rj(2),3), intent(inout) rms_sph_rj)
Definition at line 183 of file cal_rms_by_sph_spectr.f90.
References cal_sph_mean_square::one_field_mean_sq_to_energy().
Referenced by cal_rms_sph_spec_one_field().