CALYPSO: cal_sph_node_addresses Module Reference
cal_sph_node_addresses Module Reference
Functions/Subroutines
subroutine reset_local_sph_node_constants
subroutine set_intnod_shell (stbl)
subroutine set_intnod_spole (stbl)
subroutine set_intnod_npole (stbl)
subroutine set_intnod_center
subroutine set_nnod_lc_shell (ip_r, ip_t, stbl)
subroutine set_nnod_lc_spole (intnod_input)
subroutine set_nnod_lc_npole (intnod_input)
subroutine set_nnod_lc_center (intnod_input)
subroutine set_nnod_lc_ctr_sph (nnod_sph_ct, stbl)
subroutine set_nnod_lc_ctr_np (intnod_input)
subroutine set_nnod_gl_shell (stbl)
subroutine set_nnod_gl_spole (stbl)
subroutine set_nnod_gl_npole (stbl)
subroutine set_nnod_gl_center
subroutine cal_sph_local_numnod (numnod, internal_node)
subroutine check_local_sph_node_constants
integer(kind=kint) function sph_shell_node_id (ip_r, ip_t, kr, lt, mp, stbl)
integer(kind=kint) function sph_s_pole_node_id (kr)
integer(kind=kint) function sph_n_pole_node_id (kr)
integer(kind=kint) function sph_center_node_id ()
integer(kind=kint) function sph_ctr_shell_node_id (nnod_ct, lt, mp)
integer(kind=kint) function sph_center_np_node_id ()
integer(kind=kint) function global_sph_shell_node_id (kr, lt, mp, stbl)
integer(kind=kint) function global_sph_s_pole_node_id (kr)
integer(kind=kint) function global_sph_n_pole_node_id (kr)
integer(kind=kint) function global_sph_center_node_id ()
Variables
integer(kind=kint), private intnod_shell = 0
integer(kind=kint), private intnod_spole = 0
integer(kind=kint), private intnod_npole = 0
integer(kind=kint), private intnod_center = 0
integer(kind=kint), private nnod_lc_shell = 0
integer(kind=kint), private nnod_lc_spole = 0
integer(kind=kint), private nnod_lc_npole = 0
integer(kind=kint), private nnod_lc_center = 0
integer(kind=kint), private nnod_lc_ctr_sph = 0
integer(kind=kint), private nnod_lc_ctr_np = 0
integer(kind=kint), private nnod_gl_shell = 0
integer(kind=kint), private nnod_gl_spole = 0
integer(kind=kint), private nnod_gl_npole = 0
integer(kind=kint), private nnod_gl_center = 0
Function/Subroutine Documentation
cal_sph_local_numnod()
subroutine cal_sph_node_addresses::cal_sph_local_numnod (integer(kind = kint), intent(inout) numnod, integer(kind = kint), intent(inout) internal_node)
Definition at line 265 of file cal_sph_node_addresses.f90.
References intnod_center, intnod_npole, intnod_shell, intnod_spole, nnod_lc_center, nnod_lc_ctr_np, nnod_lc_ctr_sph, nnod_lc_npole, nnod_lc_shell, and nnod_lc_spole.
Referenced by set_sph_local_node::count_numnod_local_sph_mesh().
check_local_sph_node_constants()
subroutine cal_sph_node_addresses::check_local_sph_node_constants
Definition at line 279 of file cal_sph_node_addresses.f90.
References intnod_center, intnod_npole, intnod_shell, intnod_spole, nnod_gl_center, nnod_gl_npole, nnod_gl_shell, nnod_gl_spole, nnod_lc_center, nnod_lc_ctr_np, nnod_lc_ctr_sph, nnod_lc_npole, nnod_lc_shell, and nnod_lc_spole.
Referenced by set_sph_local_node::count_numnod_local_sph_mesh().
global_sph_center_node_id()
integer(kind = kint) function cal_sph_node_addresses::global_sph_center_node_id
Definition at line 408 of file cal_sph_node_addresses.f90.
References nnod_gl_npole, nnod_gl_shell, and nnod_gl_spole.
Referenced by set_sph_local_node::set_local_nodes_sph_mesh().
global_sph_n_pole_node_id()
integer(kind = kint) function cal_sph_node_addresses::global_sph_n_pole_node_id (integer(kind = kint), intent(in) kr)
Definition at line 397 of file cal_sph_node_addresses.f90.
References nnod_gl_shell, and nnod_gl_spole.
Referenced by set_sph_local_node::set_local_nodes_sph_mesh().
global_sph_s_pole_node_id()
integer(kind = kint) function cal_sph_node_addresses::global_sph_s_pole_node_id (integer(kind = kint), intent(in) kr)
Definition at line 386 of file cal_sph_node_addresses.f90.
References nnod_gl_shell.
Referenced by set_sph_local_node::set_local_nodes_sph_mesh().
global_sph_shell_node_id()
integer(kind = kint) function cal_sph_node_addresses::global_sph_shell_node_id (integer(kind = kint), intent(in) kr, integer(kind = kint), intent(in) lt, integer(kind = kint), intent(in) mp, type(comm_table_make_sph), intent(in) stbl)
Definition at line 370 of file cal_sph_node_addresses.f90.
Referenced by set_sph_local_node::set_local_nodes_sph_mesh().
reset_local_sph_node_constants()
subroutine cal_sph_node_addresses::reset_local_sph_node_constants
Definition at line 84 of file cal_sph_node_addresses.f90.
References intnod_center, intnod_npole, intnod_shell, intnod_spole, nnod_gl_center, nnod_gl_npole, nnod_gl_shell, nnod_gl_spole, nnod_lc_center, nnod_lc_ctr_np, nnod_lc_ctr_sph, nnod_lc_npole, nnod_lc_shell, and nnod_lc_spole.
Referenced by set_sph_local_node::count_numnod_local_sph_mesh().
set_intnod_center()
subroutine cal_sph_node_addresses::set_intnod_center
Definition at line 144 of file cal_sph_node_addresses.f90.
References intnod_center, and m_constants::ione.
Referenced by set_sph_local_node::count_numnod_local_sph_mesh().
set_intnod_npole()
subroutine cal_sph_node_addresses::set_intnod_npole (type(comm_table_make_sph), intent(in) stbl)
Definition at line 133 of file cal_sph_node_addresses.f90.
References intnod_npole.
Referenced by set_sph_local_node::count_numnod_local_sph_mesh().
set_intnod_shell()
subroutine cal_sph_node_addresses::set_intnod_shell (type(comm_table_make_sph), intent(in) stbl)
Definition at line 109 of file cal_sph_node_addresses.f90.
References intnod_shell.
Referenced by set_sph_local_node::count_numnod_local_sph_mesh().
set_intnod_spole()
subroutine cal_sph_node_addresses::set_intnod_spole (type(comm_table_make_sph), intent(in) stbl)
Definition at line 122 of file cal_sph_node_addresses.f90.
References intnod_spole.
Referenced by set_sph_local_node::count_numnod_local_sph_mesh().
set_nnod_gl_center()
subroutine cal_sph_node_addresses::set_nnod_gl_center
Definition at line 255 of file cal_sph_node_addresses.f90.
References m_constants::ione, and nnod_gl_center.
Referenced by set_sph_local_node::count_numnod_local_sph_mesh().
set_nnod_gl_npole()
subroutine cal_sph_node_addresses::set_nnod_gl_npole (type(comm_table_make_sph), intent(in) stbl)
Definition at line 244 of file cal_sph_node_addresses.f90.
References nnod_gl_npole.
Referenced by set_sph_local_node::count_numnod_local_sph_mesh().
set_nnod_gl_shell()
subroutine cal_sph_node_addresses::set_nnod_gl_shell (type(comm_table_make_sph), intent(in) stbl)
Definition at line 220 of file cal_sph_node_addresses.f90.
References nnod_gl_shell.
Referenced by set_sph_local_node::count_numnod_local_sph_mesh().
set_nnod_gl_spole()
subroutine cal_sph_node_addresses::set_nnod_gl_spole (type(comm_table_make_sph), intent(in) stbl)
Definition at line 233 of file cal_sph_node_addresses.f90.
References nnod_gl_spole.
Referenced by set_sph_local_node::count_numnod_local_sph_mesh().
set_nnod_lc_center()
subroutine cal_sph_node_addresses::set_nnod_lc_center (integer(kind = kint), intent(in) intnod_input)
Definition at line 187 of file cal_sph_node_addresses.f90.
References nnod_lc_center.
Referenced by set_sph_local_node::count_numnod_local_sph_mesh().
set_nnod_lc_ctr_np()
subroutine cal_sph_node_addresses::set_nnod_lc_ctr_np (integer(kind = kint), intent(in) intnod_input)
Definition at line 209 of file cal_sph_node_addresses.f90.
References nnod_lc_ctr_np.
Referenced by set_sph_local_node::count_numnod_local_sph_mesh().
set_nnod_lc_ctr_sph()
subroutine cal_sph_node_addresses::set_nnod_lc_ctr_sph (integer(kind = kint), intent(in) nnod_sph_ct, type(comm_table_make_sph), intent(in) stbl)
Definition at line 197 of file cal_sph_node_addresses.f90.
References nnod_lc_ctr_sph.
Referenced by set_sph_local_node::count_numnod_local_sph_mesh().
set_nnod_lc_npole()
subroutine cal_sph_node_addresses::set_nnod_lc_npole (integer(kind = kint), intent(in) intnod_input)
Definition at line 177 of file cal_sph_node_addresses.f90.
References nnod_lc_npole.
Referenced by set_sph_local_node::count_numnod_local_sph_mesh().
set_nnod_lc_shell()
subroutine cal_sph_node_addresses::set_nnod_lc_shell (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, type(comm_table_make_sph), intent(in) stbl)
Definition at line 154 of file cal_sph_node_addresses.f90.
References nnod_lc_shell.
Referenced by set_sph_local_node::count_numnod_local_sph_mesh().
set_nnod_lc_spole()
subroutine cal_sph_node_addresses::set_nnod_lc_spole (integer(kind = kint), intent(in) intnod_input)
Definition at line 167 of file cal_sph_node_addresses.f90.
References nnod_lc_spole.
Referenced by set_sph_local_node::count_numnod_local_sph_mesh().
sph_center_node_id()
integer(kind = kint) function cal_sph_node_addresses::sph_center_node_id
Definition at line 334 of file cal_sph_node_addresses.f90.
References nnod_lc_npole, nnod_lc_shell, and nnod_lc_spole.
Referenced by set_export_sph_center_mesh::set_export_rtp_center_mesh(), cal_sph_ele_connects::set_exter_center_n_pole_ele(), cal_sph_ele_connects::set_exter_center_shell_ele(), set_import_sph_center_mesh::set_import_rtp_center_mesh(), cal_sph_ele_connects::set_inter_center_n_pole_ele(), cal_sph_ele_connects::set_inter_center_s_pole_ele(), cal_sph_ele_connects::set_inter_center_shell_ele(), set_sph_local_node::set_local_nodes_sph_mesh(), and set_sph_node_group::set_sph_local_node_grp_item().
sph_center_np_node_id()
integer(kind = kint) function cal_sph_node_addresses::sph_center_np_node_id
Definition at line 358 of file cal_sph_node_addresses.f90.
References nnod_lc_center, nnod_lc_ctr_sph, nnod_lc_npole, nnod_lc_shell, and nnod_lc_spole.
Referenced by set_import_sph_center_mesh::set_import_rtp_ctr_npole_mesh(), cal_sph_ele_connects::set_inter_center_n_pole_ele(), set_sph_local_node::set_local_nodes_sph_mesh(), set_sph_node_group::set_node_grp_item_on_sphere(), and set_sph_node_group::set_sph_local_node_grp_item().
sph_ctr_shell_node_id()
integer(kind = kint) function cal_sph_node_addresses::sph_ctr_shell_node_id (integer(kind = kint), intent(in) nnod_ct, integer(kind = kint), intent(in) lt, integer(kind = kint), intent(in) mp)
Definition at line 344 of file cal_sph_node_addresses.f90.
References nnod_lc_center, nnod_lc_npole, nnod_lc_shell, and nnod_lc_spole.
Referenced by set_import_sph_center_mesh::set_import_rtp_ctr_shell_mesh(), cal_sph_ele_connects::set_inter_center_n_pole_ele(), cal_sph_ele_connects::set_inter_center_shell_ele(), set_sph_local_node::set_local_nodes_sph_mesh(), and set_sph_node_group::set_node_grp_item_on_sphere().
sph_n_pole_node_id()
integer(kind = kint) function cal_sph_node_addresses::sph_n_pole_node_id (integer(kind = kint), intent(in) kr)
Definition at line 323 of file cal_sph_node_addresses.f90.
References nnod_lc_shell, and nnod_lc_spole.
Referenced by set_export_sph_center_mesh::set_export_rtp_ctr_npole_mesh(), set_comm_tbl_4_pole_mesh::set_export_rtp_npole_mesh(), cal_sph_ele_connects::set_exter_center_n_pole_ele(), set_comm_tbl_4_pole_mesh::set_import_rtp_npole_mesh(), cal_sph_ele_connects::set_inter_center_n_pole_ele(), set_sph_local_node::set_local_nodes_sph_mesh(), set_sph_node_group::set_node_grp_item_on_sphere(), cal_sph_ele_connects::set_north_pole_element(), and set_sph_node_group::set_sph_local_node_grp_item().
sph_s_pole_node_id()
integer(kind = kint) function cal_sph_node_addresses::sph_s_pole_node_id (integer(kind = kint), intent(in) kr)
Definition at line 312 of file cal_sph_node_addresses.f90.
References nnod_lc_shell.
Referenced by set_comm_tbl_4_pole_mesh::set_export_rtp_spole_mesh(), set_comm_tbl_4_pole_mesh::set_import_rtp_spole_mesh(), cal_sph_ele_connects::set_inter_center_s_pole_ele(), set_sph_local_node::set_local_nodes_sph_mesh(), set_sph_node_group::set_node_grp_item_on_sphere(), cal_sph_ele_connects::set_south_pole_element(), and set_sph_node_group::set_sph_local_node_grp_item().
sph_shell_node_id()
integer(kind = kint) function cal_sph_node_addresses::sph_shell_node_id (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, integer(kind = kint), intent(in) kr, integer(kind = kint), intent(in) lt, integer(kind = kint), intent(in) mp, type(comm_table_make_sph), intent(in) stbl)
Definition at line 295 of file cal_sph_node_addresses.f90.
Referenced by ordering_sph_mesh_to_rtp::ordering_sph_mesh_for_prt(), ordering_sph_mesh_to_rtp::ordering_sph_mesh_for_rtp(), set_export_sph_center_mesh::set_export_rtp_ctr_shell_mesh(), set_comm_tbl_4_sph_mesh::set_export_rtp_shell_mesh(), cal_sph_ele_connects::set_exter_center_n_pole_ele(), cal_sph_ele_connects::set_exter_center_shell_ele(), set_comm_tbl_4_sph_mesh::set_import_rtp_shell_mesh(), cal_sph_ele_connects::set_inter_center_n_pole_ele(), cal_sph_ele_connects::set_inter_center_s_pole_ele(), cal_sph_ele_connects::set_inter_center_shell_ele(), set_sph_local_node::set_local_nodes_sph_mesh(), set_sph_node_group::set_node_grp_item_on_sphere(), cal_sph_ele_connects::set_north_pole_element(), cal_sph_ele_connects::set_south_pole_element(), and cal_sph_ele_connects::set_spherical_shell_element().
Variable Documentation
intnod_center
integer(kind = kint), private cal_sph_node_addresses::intnod_center = 0 private
Definition at line 57 of file cal_sph_node_addresses.f90.
Referenced by cal_sph_local_numnod(), check_local_sph_node_constants(), reset_local_sph_node_constants(), and set_intnod_center().
intnod_npole
integer(kind = kint), private cal_sph_node_addresses::intnod_npole = 0 private
Definition at line 56 of file cal_sph_node_addresses.f90.
Referenced by cal_sph_local_numnod(), check_local_sph_node_constants(), reset_local_sph_node_constants(), and set_intnod_npole().
intnod_shell
integer(kind = kint), private cal_sph_node_addresses::intnod_shell = 0 private
Definition at line 54 of file cal_sph_node_addresses.f90.
Referenced by cal_sph_local_numnod(), check_local_sph_node_constants(), reset_local_sph_node_constants(), and set_intnod_shell().
intnod_spole
integer(kind = kint), private cal_sph_node_addresses::intnod_spole = 0 private
Definition at line 55 of file cal_sph_node_addresses.f90.
Referenced by cal_sph_local_numnod(), check_local_sph_node_constants(), reset_local_sph_node_constants(), and set_intnod_spole().
nnod_gl_center
integer(kind = kint), private cal_sph_node_addresses::nnod_gl_center = 0 private
Definition at line 69 of file cal_sph_node_addresses.f90.
Referenced by check_local_sph_node_constants(), reset_local_sph_node_constants(), and set_nnod_gl_center().
nnod_gl_npole
integer(kind = kint), private cal_sph_node_addresses::nnod_gl_npole = 0 private
Definition at line 68 of file cal_sph_node_addresses.f90.
Referenced by check_local_sph_node_constants(), global_sph_center_node_id(), reset_local_sph_node_constants(), and set_nnod_gl_npole().
nnod_gl_shell
integer(kind = kint), private cal_sph_node_addresses::nnod_gl_shell = 0 private
Definition at line 66 of file cal_sph_node_addresses.f90.
Referenced by check_local_sph_node_constants(), global_sph_center_node_id(), global_sph_n_pole_node_id(), global_sph_s_pole_node_id(), reset_local_sph_node_constants(), and set_nnod_gl_shell().
nnod_gl_spole
integer(kind = kint), private cal_sph_node_addresses::nnod_gl_spole = 0 private
Definition at line 67 of file cal_sph_node_addresses.f90.
Referenced by check_local_sph_node_constants(), global_sph_center_node_id(), global_sph_n_pole_node_id(), reset_local_sph_node_constants(), and set_nnod_gl_spole().
nnod_lc_center
integer(kind = kint), private cal_sph_node_addresses::nnod_lc_center = 0 private
Definition at line 62 of file cal_sph_node_addresses.f90.
Referenced by cal_sph_local_numnod(), check_local_sph_node_constants(), reset_local_sph_node_constants(), set_nnod_lc_center(), sph_center_np_node_id(), and sph_ctr_shell_node_id().
nnod_lc_ctr_np
integer(kind = kint), private cal_sph_node_addresses::nnod_lc_ctr_np = 0 private
Definition at line 64 of file cal_sph_node_addresses.f90.
Referenced by cal_sph_local_numnod(), check_local_sph_node_constants(), reset_local_sph_node_constants(), and set_nnod_lc_ctr_np().
nnod_lc_ctr_sph
integer(kind = kint), private cal_sph_node_addresses::nnod_lc_ctr_sph = 0 private
Definition at line 63 of file cal_sph_node_addresses.f90.
Referenced by cal_sph_local_numnod(), check_local_sph_node_constants(), reset_local_sph_node_constants(), set_nnod_lc_ctr_sph(), and sph_center_np_node_id().
nnod_lc_npole
integer(kind = kint), private cal_sph_node_addresses::nnod_lc_npole = 0 private
Definition at line 61 of file cal_sph_node_addresses.f90.
Referenced by cal_sph_local_numnod(), check_local_sph_node_constants(), reset_local_sph_node_constants(), set_nnod_lc_npole(), sph_center_node_id(), sph_center_np_node_id(), and sph_ctr_shell_node_id().
nnod_lc_shell
integer(kind = kint), private cal_sph_node_addresses::nnod_lc_shell = 0 private
Definition at line 59 of file cal_sph_node_addresses.f90.
Referenced by cal_sph_local_numnod(), check_local_sph_node_constants(), reset_local_sph_node_constants(), set_nnod_lc_shell(), sph_center_node_id(), sph_center_np_node_id(), sph_ctr_shell_node_id(), sph_n_pole_node_id(), and sph_s_pole_node_id().
nnod_lc_spole
integer(kind = kint), private cal_sph_node_addresses::nnod_lc_spole = 0 private
Definition at line 60 of file cal_sph_node_addresses.f90.
Referenced by cal_sph_local_numnod(), check_local_sph_node_constants(), reset_local_sph_node_constants(), set_nnod_lc_spole(), sph_center_node_id(), sph_center_np_node_id(), sph_ctr_shell_node_id(), and sph_n_pole_node_id().