CALYPSO: set_vr_rtm_sym_mat_tsmp Module Reference
set_vr_rtm_sym_mat_tsmp Module Reference
forward Legendre transform (Blocked loop version)
Functions/Subroutines
subroutine set_vr_rtm_sym_mat_rout (nnod_rtm, nidx_rtm, istep_rtm, nidx_rlm, asin_theta_1d_rtm, weight_rtm, mp_rlm, mn_rlm, lst_rtm, nle_rtm, nlo_rtm, ncomp_recv, nvector, nscalar, irev_sr_rtm, n_WR, WR, symp_r, asmp_p, asmp_r, symp_p)
subroutine set_vr_rtm_sym_mat_rin (nnod_rtm, nidx_rtm, istep_rtm, nidx_rlm, asin_theta_1d_rtm, weight_rtm, mp_rlm, mn_rlm, lst_rtm, nle_rtm, nlo_rtm, ncomp_recv, nvector, nscalar, irev_sr_rtm, n_WR, WR, symp_r, asmp_p, asmp_r, symp_p)
subroutine set_vr_rtm_lt_sym_mat_rin (lp_rtm, ln_rtm, nnod_rtm, istep_rtm, nidx_rlm, asin_rtm, wp_rtm, mp_rlm, mn_rlm, ncomp_recv, nvector, nscalar, irev_sr_rtm, n_WR, WR, symp_r, asmp_p, asmp_r, symp_p)
subroutine set_vr_rtm_eq_sym_mat_rin (lp_rtm, nnod_rtm, istep_rtm, nidx_rlm, asin_rtm, wp_rtm, mp_rlm, mn_rlm, ncomp_recv, nvector, nscalar, irev_sr_rtm, n_WR, WR, symp_r, asmp_p, asmp_r, symp_p)
Variables
integer, external omp_get_max_threads
Detailed Description
forward Legendre transform (Blocked loop version)
      subroutine set_vr_rtm_sym_mat_rout(nnod_rtm, nidx_rtm,          &
     &         istep_rtm, nidx_rlm, asin_theta_1d_rtm, weight_rtm,    &
     &         mp_rlm, mn_rlm, lst_rtm, nle_rtm, nlo_rtm,             &
     &         ncomp_recv, nvector, nscalar, irev_sr_rtm, n_WR, WR,   &
     &         symp_r, asmp_p, asmp_r, symp_p)
      subroutine set_vr_rtm_sym_mat_rin(nnod_rtm, nidx_rtm,           &
     &         istep_rtm, nidx_rlm, asin_theta_1d_rtm, weight_rtm,    &
     &         mp_rlm, mn_rlm, lst_rtm, nle_rtm, nlo_rtm,             &
     &         ncomp_recv, nvector, nscalar, irev_sr_rtm, n_WR, WR,   &
     &         symp_r, asmp_p, asmp_r, symp_p)
Function/Subroutine Documentation
set_vr_rtm_eq_sym_mat_rin()
subroutine set_vr_rtm_sym_mat_tsmp::set_vr_rtm_eq_sym_mat_rin (integer(kind = kint), intent(in) lp_rtm, integer(kind = kint), intent(in) nnod_rtm, integer(kind = kint), dimension(3), intent(in) istep_rtm, integer(kind = kint), dimension(2), intent(in) nidx_rlm, real(kind = kreal), intent(in) asin_rtm, real(kind = kreal), intent(in) wp_rtm, integer(kind = kint), intent(in) mp_rlm, integer(kind = kint), intent(in) mn_rlm, integer(kind = kint), intent(in) ncomp_recv, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, integer(kind = kint), dimension(nnod_rtm), intent(in) irev_sr_rtm, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(in) WR, real(kind=kreal), dimension(3*nvector+nscalar,nidx_rlm(1)), intent(inout) symp_r, real(kind=kreal), dimension(2*nvector,nidx_rlm(1)), intent(inout) asmp_p, real(kind=kreal), dimension(3*nvector+nscalar,nidx_rlm(1)), intent(inout) asmp_r, real(kind=kreal), dimension(2*nvector,nidx_rlm(1)), intent(inout) symp_p)
Definition at line 386 of file set_vr_rtm_sym_mat_tsmp.f90.
Referenced by leg_fwd_trans_on_the_fly::leg_fwd_trans_at_equator(), legendre_fwd_trans_testloop::leg_fwd_trans_at_equator(), and set_vr_rtm_sym_mat_rin().
set_vr_rtm_lt_sym_mat_rin()
subroutine set_vr_rtm_sym_mat_tsmp::set_vr_rtm_lt_sym_mat_rin (integer(kind = kint), intent(in) lp_rtm, integer(kind = kint), intent(in) ln_rtm, integer(kind = kint), intent(in) nnod_rtm, integer(kind = kint), dimension(3), intent(in) istep_rtm, integer(kind = kint), dimension(2), intent(in) nidx_rlm, real(kind = kreal), intent(in) asin_rtm, real(kind = kreal), intent(in) wp_rtm, integer(kind = kint), intent(in) mp_rlm, integer(kind = kint), intent(in) mn_rlm, integer(kind = kint), intent(in) ncomp_recv, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, integer(kind = kint), dimension(nnod_rtm), intent(in) irev_sr_rtm, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(in) WR, real(kind=kreal), dimension(3*nvector+nscalar,nidx_rlm(1)), intent(inout) symp_r, real(kind=kreal), dimension(2*nvector,nidx_rlm(1)), intent(inout) asmp_p, real(kind=kreal), dimension(3*nvector+nscalar,nidx_rlm(1)), intent(inout) asmp_r, real(kind=kreal), dimension(2*nvector,nidx_rlm(1)), intent(inout) symp_p)
Definition at line 282 of file set_vr_rtm_sym_mat_tsmp.f90.
Referenced by leg_fwd_trans_on_the_fly::leg_fwd_trans_1latitude(), legendre_fwd_trans_testloop::leg_fwd_trans_1latitude(), leg_fwd_trans_on_the_fly::leg_fwd_trans_2latitude(), legendre_fwd_trans_testloop::leg_fwd_trans_2latitude(), leg_fwd_trans_on_the_fly::leg_fwd_trans_4latitude(), legendre_fwd_trans_testloop::leg_fwd_trans_4latitude(), leg_fwd_trans_on_the_fly::leg_fwd_trans_8latitude(), legendre_fwd_trans_testloop::leg_fwd_trans_8latitude(), and set_vr_rtm_sym_mat_rin().
set_vr_rtm_sym_mat_rin()
subroutine set_vr_rtm_sym_mat_tsmp::set_vr_rtm_sym_mat_rin (integer(kind = kint), intent(in) nnod_rtm, integer(kind = kint), dimension(3), intent(in) nidx_rtm, integer(kind = kint), dimension(3), intent(in) istep_rtm, integer(kind = kint), dimension(2), intent(in) nidx_rlm, real(kind = kreal), dimension(nidx_rtm(2)), intent(in) asin_theta_1d_rtm, real(kind = kreal), dimension(nidx_rtm(2)), intent(in) weight_rtm, integer(kind = kint), intent(in) mp_rlm, integer(kind = kint), intent(in) mn_rlm, integer(kind = kint), intent(in) lst_rtm, integer(kind = kint), intent(in) nle_rtm, integer(kind = kint), intent(in) nlo_rtm, integer(kind = kint), intent(in) ncomp_recv, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, integer(kind = kint), dimension(nnod_rtm), intent(in) irev_sr_rtm, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(in) WR, real(kind=kreal), dimension(3*nvector+nscalar,nidx_rlm(1),nle_rtm), intent(inout) symp_r, real(kind=kreal), dimension(2*nvector,nidx_rlm(1),nle_rtm), intent(inout) asmp_p, real(kind=kreal), dimension(3*nvector+nscalar,nidx_rlm(1),nle_rtm), intent(inout) asmp_r, real(kind=kreal), dimension(2*nvector,nidx_rlm(1),nle_rtm), intent(inout) symp_p)
Definition at line 221 of file set_vr_rtm_sym_mat_tsmp.f90.
References set_vr_rtm_eq_sym_mat_rin(), and set_vr_rtm_lt_sym_mat_rin().
Referenced by leg_fwd_trans_sym_mat_tj::legendre_f_trans_sym_mat_tj().
set_vr_rtm_sym_mat_rout()
subroutine set_vr_rtm_sym_mat_tsmp::set_vr_rtm_sym_mat_rout (integer(kind = kint), intent(in) nnod_rtm, integer(kind = kint), dimension(3), intent(in) nidx_rtm, integer(kind = kint), dimension(3), intent(in) istep_rtm, integer(kind = kint), dimension(2), intent(in) nidx_rlm, real(kind = kreal), dimension(nidx_rtm(2)), intent(in) asin_theta_1d_rtm, real(kind = kreal), dimension(nidx_rtm(2)), intent(in) weight_rtm, integer(kind = kint), intent(in) mp_rlm, integer(kind = kint), intent(in) mn_rlm, integer(kind = kint), intent(in) lst_rtm, integer(kind = kint), intent(in) nle_rtm, integer(kind = kint), intent(in) nlo_rtm, integer(kind = kint), intent(in) ncomp_recv, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, integer(kind = kint), dimension(nnod_rtm), intent(in) irev_sr_rtm, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(in) WR, real(kind=kreal), dimension(nle_rtm,nidx_rlm(1),3*nvector+nscalar), intent(inout) symp_r, real(kind=kreal), dimension(nle_rtm,nidx_rlm(1),2*nvector), intent(inout) asmp_p, real(kind=kreal), dimension(nle_rtm,nidx_rlm(1),3*nvector+nscalar), intent(inout) asmp_r, real(kind=kreal), dimension(nle_rtm,nidx_rlm(1),2*nvector), intent(inout) symp_p)
Definition at line 41 of file set_vr_rtm_sym_mat_tsmp.f90.
Referenced by leg_fwd_trans_sym_mat_jt::legendre_f_trans_sym_mat_jt().
Variable Documentation
omp_get_max_threads
integer, external set_vr_rtm_sym_mat_tsmp::omp_get_max_threads
Definition at line 33 of file set_vr_rtm_sym_mat_tsmp.f90.