CALYPSO: domain_data_io_b Module Reference
domain_data_io_b Module Reference
Routine for doimain data IO.
Functions/Subroutines
subroutine read_domain_info_b (id_rank, bbuf, comm_IO)
subroutine read_import_data_b (bbuf, comm_IO)
subroutine read_export_data_b (bbuf, comm_IO)
subroutine write_domain_info_b (id_rank, comm_IO, bbuf)
subroutine write_import_data_b (comm_IO, bbuf)
subroutine write_export_data_b (comm_IO, bbuf)
Detailed Description
Routine for doimain data IO.
      subroutine read_domain_info_b(id_rank, bbuf, comm_IO)
      subroutine read_import_data_b(bbuf, comm_IO)
      subroutine read_export_data_b(bbuf, comm_IO)
        type(binary_IO_buffer), intent(inout) :: bbuf
        type(communication_table), intent(inout) :: comm_IO
      subroutine write_domain_info_b(id_rank, comm_IO, bbuf)
      subroutine write_import_data_b(comm_IO, bbuf)
      subroutine write_export_data_b(comm_IO, bbuf)
        type(binary_IO_buffer), intent(inout) :: bbuf
        type(communicatiole), intent(in) :: comm_IO
Function/Subroutine Documentation
read_domain_info_b()
subroutine domain_data_io_b::read_domain_info_b (integer, intent(in) id_rank, type(binary_io_buffer), intent(inout) bbuf, type(communication_table), intent(inout) comm_IO)
Definition at line 42 of file domain_data_IO_b.f90.
References t_comm_table::alloc_neighbouring_id(), transfer_to_long_integers::cast_long(), m_error_ids::ierr_mesh, binary_io::read_mul_integer_b(), and binary_io::read_one_integer_b().
Referenced by edge_data_io_b::read_edge_connection_b(), element_data_io_b::read_element_comm_table_b(), mesh_data_io_b::read_filter_geometry_b(), sph_modes_grids_data_io_b::read_geom_rtm_data_b(), sph_modes_grids_data_io_b::read_geom_rtp_data_b(), sph_modes_grids_data_io_b::read_modes_rlm_data_b(), mesh_data_io_b::read_num_node_b(), sph_modes_grids_data_io_b::read_spectr_modes_rj_data_b(), and surface_data_io_b::read_surface_connection_b().
read_export_data_b()
subroutine domain_data_io_b::read_export_data_b (type(binary_io_buffer), intent(inout) bbuf, type(communication_table), intent(inout) comm_IO)
Definition at line 101 of file domain_data_IO_b.f90.
References t_comm_table::alloc_export_item(), t_comm_table::alloc_export_num(), transfer_to_long_integers::cast_long(), binary_io::read_integer_stack_b(), and binary_io::read_mul_integer_b().
Referenced by edge_data_io_b::read_edge_connection_b(), element_data_io_b::read_element_comm_table_b(), mesh_data_io_b::read_filter_geometry_b(), mesh_data_io_b::read_geometry_data_b(), and surface_data_io_b::read_surface_connection_b().
read_import_data_b()
subroutine domain_data_io_b::read_import_data_b (type(binary_io_buffer), intent(inout) bbuf, type(communication_table), intent(inout) comm_IO)
Definition at line 76 of file domain_data_IO_b.f90.
References t_comm_table::alloc_import_item(), t_comm_table::alloc_import_num(), transfer_to_long_integers::cast_long(), binary_io::read_integer_stack_b(), and binary_io::read_mul_integer_b().
Referenced by edge_data_io_b::read_edge_connection_b(), element_data_io_b::read_element_comm_table_b(), mesh_data_io_b::read_filter_geometry_b(), sph_modes_grids_data_io_b::read_geom_rtm_data_b(), sph_modes_grids_data_io_b::read_geom_rtp_data_b(), mesh_data_io_b::read_geometry_data_b(), sph_modes_grids_data_io_b::read_modes_rlm_data_b(), sph_modes_grids_data_io_b::read_spectr_modes_rj_data_b(), and surface_data_io_b::read_surface_connection_b().
write_domain_info_b()
subroutine domain_data_io_b::write_domain_info_b (integer, intent(in) id_rank, type(communication_table), intent(in) comm_IO, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 127 of file domain_data_IO_b.f90.
References transfer_to_long_integers::cast_long(), binary_io::write_mul_integer_b(), and binary_io::write_one_integer_b().
Referenced by edge_data_io_b::write_edge_connection_b(), element_data_io_b::write_element_comm_table_b(), mesh_data_io_b::write_filter_geometry_b(), sph_modes_grids_data_io_b::write_geom_rtm_data_b(), sph_modes_grids_data_io_b::write_geom_rtp_data_b(), mesh_data_io_b::write_geometry_data_b(), sph_modes_grids_data_io_b::write_modes_rlm_data_b(), sph_modes_grids_data_io_b::write_spectr_modes_rj_data_b(), and surface_data_io_b::write_surface_connection_b().
write_export_data_b()
subroutine domain_data_io_b::write_export_data_b (type(communication_table), intent(in) comm_IO, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 169 of file domain_data_IO_b.f90.
References transfer_to_long_integers::cast_long(), binary_io::write_integer_stack_b(), and binary_io::write_mul_integer_b().
Referenced by edge_data_io_b::write_edge_connection_b(), element_data_io_b::write_element_comm_table_b(), mesh_data_io_b::write_filter_geometry_b(), mesh_data_io_b::write_geometry_data_b(), and surface_data_io_b::write_surface_connection_b().
write_import_data_b()
subroutine domain_data_io_b::write_import_data_b (type(communication_table), intent(in) comm_IO, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 151 of file domain_data_IO_b.f90.
References transfer_to_long_integers::cast_long(), binary_io::write_integer_stack_b(), and binary_io::write_mul_integer_b().
Referenced by edge_data_io_b::write_edge_connection_b(), element_data_io_b::write_element_comm_table_b(), mesh_data_io_b::write_filter_geometry_b(), sph_modes_grids_data_io_b::write_geom_rtm_data_b(), sph_modes_grids_data_io_b::write_geom_rtp_data_b(), mesh_data_io_b::write_geometry_data_b(), sph_modes_grids_data_io_b::write_modes_rlm_data_b(), sph_modes_grids_data_io_b::write_spectr_modes_rj_data_b(), and surface_data_io_b::write_surface_connection_b().