CALYPSO: viewer_file_io Module Reference
viewer_file_io Module Reference
ASCII viewer mesh file IO.
Functions/Subroutines
subroutine sel_output_single_surface_grid (id_rank, mesh_file, view_mesh, domain_grps, view_nod_grps, view_ele_grps, view_sf_grps)
subroutine, private output_single_surface_grid (file_name, isurf_sf_stack, view_mesh, domain_grps, view_nod_grps, view_ele_grps, view_sf_grps)
Detailed Description
ASCII viewer mesh file IO.
      subroutine output_single_surface_grid                           &
     &         (file_name, isurf_sf_stack, view_mesh, domain_grps,    &
     &          view_nod_grps, view_ele_grps, view_sf_grps)
        type(viewer_mesh_data), intent(in) :: view_mesh
        type(viewer_surface_groups), intent(in) :: domain_grps
        type(viewer_node_groups), intent(in) :: view_nod_grps
        type(viewer_surface_groups), intent(in) :: view_ele_grps
        type(viewer_surface_groups), intent(in) :: view_sf_grps
Function/Subroutine Documentation
output_single_surface_grid()
subroutine, private viewer_file_io::output_single_surface_grid (character(len = kchara), intent(in) file_name, integer(kind = kint), dimension(0:1), intent(in) isurf_sf_stack, type(viewer_mesh_data), intent(in) view_mesh, type(viewer_surface_groups), intent(in) domain_grps, type(viewer_node_groups), intent(in) view_nod_grps, type(viewer_surface_groups), intent(in) view_ele_grps, type(viewer_surface_groups), intent(in) view_sf_grps) private
Definition at line 75 of file viewer_file_IO.f90.
References viewer_group_data_io::write_domain_group_viewer(), viewer_mesh_data_io::write_edge_connect_viewer(), viewer_group_data_io::write_ele_group_viewer(), viewer_group_data_io::write_nod_group_viewer(), viewer_mesh_data_io::write_node_data_viewer(), viewer_mesh_data_io::write_sgl_domain_data_viewer(), viewer_mesh_data_io::write_surf_connect_viewer(), and viewer_group_data_io::write_surf_group_viewer().
Referenced by sel_output_single_surface_grid().
sel_output_single_surface_grid()
subroutine viewer_file_io::sel_output_single_surface_grid (integer, intent(in) id_rank, type(field_io_params), intent(in) mesh_file, type(viewer_mesh_data), intent(in) view_mesh, type(viewer_surface_groups), intent(in) domain_grps, type(viewer_node_groups), intent(in) view_nod_grps, type(viewer_surface_groups), intent(in) view_ele_grps, type(viewer_surface_groups), intent(in) view_sf_grps)
Definition at line 41 of file viewer_file_IO.f90.
References set_mesh_extensions::add_ksm_extension(), set_parallel_file_name::add_process_id(), and output_single_surface_grid().
Referenced by para_const_kemoview_mesh::pickup_surface_mesh().