CALYPSO: gz_sph_modes_grids_data_io Module Reference
gz_sph_modes_grids_data_io Module Reference
gzipped spectr data IO routines
Functions/Subroutines
subroutine read_geom_rtp_data_gz (id_rank, comm_IO, sph_IO, sph_grps_IO, zbuf, ierr)
subroutine read_spectr_modes_rj_data_gz (id_rank, comm_IO, sph_IO, sph_grps_IO, zbuf, ierr)
subroutine read_geom_rtm_data_gz (id_rank, comm_IO, sph_IO, zbuf, ierr)
subroutine read_spectr_modes_rlm_data_gz (id_rank, comm_IO, sph_IO, zbuf, ierr)
subroutine write_geom_rtp_data_gz (id_rank, comm_IO, sph_IO, sph_grps_IO, zbuf)
subroutine write_spectr_modes_rj_data_gz (id_rank, comm_IO, sph_IO, sph_grps_IO, zbuf)
subroutine write_geom_rtm_data_gz (id_rank, comm_IO, sph_IO, zbuf)
subroutine write_modes_rlm_data_gz (id_rank, comm_IO, sph_IO, zbuf)
Detailed Description
gzipped spectr data IO routines
      subroutine read_geom_rtp_data_gz                                &
     &         (id_rank, comm_IO, sph_IO, sph_grps_IO, zbuf, ierr)
      subroutine read_spectr_modes_rj_data_gz                         &
     &         (id_rank, comm_IO, sph_IO, sph_grps_IO, zbuf, ierr)
      subroutine read_geom_rtm_data_gz                                &
     &         (id_rank, comm_IO, sph_IO, zbuf, ierr)
      subroutine read_spectr_modes_rlm_data_gz                        &
     &         (id_rank, comm_IO, sph_IO, zbuf, ierr)
        type(communication_table), intent(inout) :: comm_IO
        type(sph_IO_data), intent(inout) :: sph_IO
        type(sph_group_data), intent(inout) :: sph_grps_IO
        type(buffer_4_gzip), intent(inout) :: zbuf
      subroutine write_geom_rtp_data_gz                               &
     &         (id_rank, comm_IO, sph_IO, sph_grps_IO, zbuf)
      subroutine write_spectr_modes_rj_data_gz                        &
     &         (id_rank, comm_IO, sph_IO, sph_grps_IO, zbuf)
      subroutine write_geom_rtm_data_gz                               &
     &         (id_rank, comm_IO, sph_IO, zbuf)
      subroutine write_modes_rlm_data_gz                              &
     &         (id_rank, comm_IO, sph_IO, zbuf)
        type(communication_table), intent(in) :: comm_IO
        type(sph_IO_data), intent(in) :: sph_IO
        type(sph_group_data), intent(in) :: sph_grps_IO
        type(buffer_4_gzip), intent(inout) :: zbuf
Parameters
file_name file name for IO (.gz is appended in this module)
Function/Subroutine Documentation
read_geom_rtm_data_gz()
subroutine gz_sph_modes_grids_data_io::read_geom_rtm_data_gz (integer, intent(in) id_rank, type(communication_table), intent(inout) comm_IO, type(sph_io_data), intent(inout) sph_IO, type(buffer_4_gzip), intent(inout) zbuf, integer(kind = kint), intent(inout) ierr)
Definition at line 148 of file gz_sph_modes_grids_data_IO.f90.
References gz_domain_data_io::gz_read_domain_info(), gz_domain_data_io::gz_read_import_data(), gz_spherical_model_io::read_gl_nodes_sph_gz(), gz_spherical_model_io::read_gl_resolution_sph_gz(), gz_spherical_model_io::read_rank_4_sph_gz(), and gz_sph_global_1d_idx_io::read_rtp_gl_1d_table_gz().
Referenced by gz_sph_modes_grids_file_io::gz_read_geom_rtm_file().
read_geom_rtp_data_gz()
subroutine gz_sph_modes_grids_data_io::read_geom_rtp_data_gz (integer, intent(in) id_rank, type(communication_table), intent(inout) comm_IO, type(sph_io_data), intent(inout) sph_IO, type(sph_group_data), intent(inout) sph_grps_IO, type(buffer_4_gzip), intent(inout) zbuf, integer(kind = kint), intent(inout) ierr)
Definition at line 61 of file gz_sph_modes_grids_data_IO.f90.
References gz_domain_data_io::gz_read_domain_info(), gz_domain_data_io::gz_read_import_data(), gz_spherical_model_io::read_gl_nodes_sph_gz(), gz_spherical_model_io::read_gl_resolution_sph_gz(), gz_group_data_io::read_group_data_gz(), gz_spherical_model_io::read_rank_4_sph_gz(), and gz_sph_global_1d_idx_io::read_rtp_gl_1d_table_gz().
Referenced by gz_sph_modes_grids_file_io::gz_read_geom_rtp_file().
read_spectr_modes_rj_data_gz()
subroutine gz_sph_modes_grids_data_io::read_spectr_modes_rj_data_gz (integer, intent(in) id_rank, type(communication_table), intent(inout) comm_IO, type(sph_io_data), intent(inout) sph_IO, type(sph_group_data), intent(inout) sph_grps_IO, type(buffer_4_gzip), intent(inout) zbuf, integer(kind = kint), intent(inout) ierr)
Definition at line 107 of file gz_sph_modes_grids_data_IO.f90.
References gz_domain_data_io::gz_read_domain_info(), gz_domain_data_io::gz_read_import_data(), gz_spherical_model_io::read_gl_nodes_sph_gz(), gz_spherical_model_io::read_gl_resolution_sph_gz(), gz_group_data_io::read_group_data_gz(), gz_spherical_model_io::read_rank_4_sph_gz(), and gz_sph_global_1d_idx_io::read_rj_gl_1d_table_gz().
Referenced by gz_sph_modes_grids_file_io::gz_read_spectr_modes_rj_file().
read_spectr_modes_rlm_data_gz()
subroutine gz_sph_modes_grids_data_io::read_spectr_modes_rlm_data_gz (integer, intent(in) id_rank, type(communication_table), intent(inout) comm_IO, type(sph_io_data), intent(inout) sph_IO, type(buffer_4_gzip), intent(inout) zbuf, integer(kind = kint), intent(inout) ierr)
Definition at line 173 of file gz_sph_modes_grids_data_IO.f90.
References gz_domain_data_io::gz_read_domain_info(), gz_domain_data_io::gz_read_import_data(), gz_spherical_model_io::read_gl_nodes_sph_gz(), gz_spherical_model_io::read_gl_resolution_sph_gz(), gz_spherical_model_io::read_rank_4_sph_gz(), and gz_sph_global_1d_idx_io::read_rj_gl_1d_table_gz().
Referenced by gz_sph_modes_grids_file_io::gz_read_modes_rlm_file().
write_geom_rtm_data_gz()
subroutine gz_sph_modes_grids_data_io::write_geom_rtm_data_gz (integer, intent(in) id_rank, type(communication_table), intent(in) comm_IO, type(sph_io_data), intent(in) sph_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 305 of file gz_sph_modes_grids_data_IO.f90.
References gz_domain_data_io::gz_write_domain_info(), gz_domain_data_io::gz_write_import_data(), gzip_file_access::gz_write_textbuf_no_lf(), m_sph_modes_grid_labels::hd_rtp_comm(), m_sph_modes_grid_labels::hd_rtp_glbl(), m_sph_modes_grid_labels::hd_sph_para(), gz_spherical_model_io::write_gl_nodes_sph_gz(), gz_spherical_model_io::write_gl_resolution_sph_gz(), gz_spherical_model_io::write_rank_4_sph_gz(), and gz_sph_global_1d_idx_io::write_rtp_gl_1d_table_gz().
Referenced by gz_sph_modes_grids_file_io::gz_write_geom_rtm_file().
write_geom_rtp_data_gz()
subroutine gz_sph_modes_grids_data_io::write_geom_rtp_data_gz (integer, intent(in) id_rank, type(communication_table), intent(in) comm_IO, type(sph_io_data), intent(in) sph_IO, type(sph_group_data), intent(in) sph_grps_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 199 of file gz_sph_modes_grids_data_IO.f90.
References gz_domain_data_io::gz_write_domain_info(), gz_domain_data_io::gz_write_import_data(), gzip_file_access::gz_write_textbuf_no_lf(), m_sph_modes_grid_labels::hd_grphd(), m_sph_modes_grid_labels::hd_ngrphd(), m_sph_modes_grid_labels::hd_pgrphd(), m_sph_modes_grid_labels::hd_rgrphd(), m_sph_modes_grid_labels::hd_rtp_comm(), m_sph_modes_grid_labels::hd_rtp_glbl(), m_sph_modes_grid_labels::hd_sph_para(), m_sph_modes_grid_labels::hd_tgrphd(), gz_spherical_model_io::write_gl_nodes_sph_gz(), gz_spherical_model_io::write_gl_resolution_sph_gz(), gz_group_data_io::write_group_data_gz(), gz_spherical_model_io::write_rank_4_sph_gz(), and gz_sph_global_1d_idx_io::write_rtp_gl_1d_table_gz().
Referenced by gz_sph_modes_grids_file_io::gz_write_geom_rtp_file().
write_modes_rlm_data_gz()
subroutine gz_sph_modes_grids_data_io::write_modes_rlm_data_gz (integer, intent(in) id_rank, type(communication_table), intent(in) comm_IO, type(sph_io_data), intent(in) sph_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 340 of file gz_sph_modes_grids_data_IO.f90.
References gz_domain_data_io::gz_write_domain_info(), gz_domain_data_io::gz_write_import_data(), gzip_file_access::gz_write_textbuf_no_lf(), m_sph_modes_grid_labels::hd_rj_comm(), m_sph_modes_grid_labels::hd_rlm_glbl(), m_sph_modes_grid_labels::hd_sph_para(), gz_spherical_model_io::write_gl_nodes_sph_gz(), gz_spherical_model_io::write_gl_resolution_sph_gz(), gz_spherical_model_io::write_rank_4_sph_gz(), and gz_sph_global_1d_idx_io::write_rj_gl_1d_table_gz().
Referenced by gz_sph_modes_grids_file_io::gz_write_modes_rlm_file().
write_spectr_modes_rj_data_gz()
subroutine gz_sph_modes_grids_data_io::write_spectr_modes_rj_data_gz (integer, intent(in) id_rank, type(communication_table), intent(in) comm_IO, type(sph_io_data), intent(in) sph_IO, type(sph_group_data), intent(in) sph_grps_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 256 of file gz_sph_modes_grids_data_IO.f90.
References gz_domain_data_io::gz_write_domain_info(), gz_domain_data_io::gz_write_import_data(), gzip_file_access::gz_write_textbuf_no_lf(), m_sph_modes_grid_labels::hd_grphd(), m_sph_modes_grid_labels::hd_jgrphd(), m_sph_modes_grid_labels::hd_kgrphd(), m_sph_modes_grid_labels::hd_rj_comm(), m_sph_modes_grid_labels::hd_rj_glbl(), m_sph_modes_grid_labels::hd_sph_para(), gz_spherical_model_io::write_gl_nodes_sph_gz(), gz_spherical_model_io::write_gl_resolution_sph_gz(), gz_group_data_io::write_group_data_gz(), gz_spherical_model_io::write_rank_4_sph_gz(), and gz_sph_global_1d_idx_io::write_rj_gl_1d_table_gz().
Referenced by gz_sph_modes_grids_file_io::gz_write_spectr_modes_rj_file().