CALYPSO: address_sph_trans_snap Module Reference
address_sph_trans_snap Module Reference
Field addresses for spherical harmonics transform in MHD dynamo simulation.
Functions/Subroutines
subroutine bwd_trans_address_snap (d_rj, ipol, iphys, b_trns, trns_back)
subroutine fwd_trans_address_snap (d_rj, ipol, iphys, f_trns, trns_fwd)
subroutine bwd_trans_address_ene_flux (d_rj, ipol, iphys, b_trns, trns_back)
subroutine fwd_trans_address_ene_flux (d_rj, ipol, iphys, f_trns, trns_fwd)
subroutine bwd_trans_address_diff_vect (d_rj, ipol, iphys, b_trns, trns_back)
subroutine fwd_trans_address_diff_vect (d_rj, ipol, iphys, f_trns, trns_fwd)
Detailed Description
Field addresses for spherical harmonics transform in MHD dynamo simulation.
      subroutine bwd_trans_address_snap                               &
     &         (d_rj, ipol, iphys, b_trns, trns_back)
        type(phys_data), intent(in) :: d_rj
        type(phys_address), intent(in) :: ipol, iphys
        type(phys_address), intent(inout) :: b_trns
        type(spherical_transform_data), intent(inout) :: trns_back
      subroutine fwd_trans_address_snap                               &
     &         (d_rj, ipol, iphys, f_trns, trns_fwd)
        type(phys_data), intent(in) :: d_rj
        type(phys_address), intent(in) :: ipol, iphys
        type(spherical_transform_data), intent(inout) :: trns_fwd
        type(phys_address), intent(inout) :: f_trns
      subroutine bwd_trans_address_ene_flux                           &
     &         (d_rj, ipol, iphys, b_trns, trns_back)
        type(phys_data), intent(in) :: d_rj
        type(phys_address), intent(in) :: ipol, iphys
        type(spherical_transform_data), intent(inout) :: trns_back
        type(phys_address), intent(inout) :: b_trns
      subroutine fwd_trans_address_ene_flux                           &
     &         (d_rj, ipol, iphys, f_trns, trns_fwd)
        type(phys_data), intent(in) :: d_rj
        type(phys_address), intent(in) :: ipol, iphys
        type(spherical_transform_data), intent(inout) :: trns_fwd
        type(phys_address), intent(inout) :: f_trns
      subroutine bwd_trans_address_diff_vect                          &
     &         (d_rj, ipol, iphys, b_trns, trns_back)
        type(phys_address), intent(in) :: ipol, iphys
        type(phys_address), intent(inout) :: b_trns
        type(spherical_transform_data), intent(inout) :: trns_back
      subroutine fwd_trans_address_diff_vect                          &
     &         (d_rj, ipol, iphys, f_trns, trns_fwd)
        type(phys_data), intent(in) :: d_rj
        type(phys_address), intent(in) :: ipol, iphys
        type(phys_address), intent(inout) :: f_trns
        type(spherical_transform_data), intent(inout) :: trns_fwd
Function/Subroutine Documentation
bwd_trans_address_diff_vect()
subroutine address_sph_trans_snap::bwd_trans_address_diff_vect (type(phys_data), intent(in) d_rj, type(phys_address), intent(in) ipol, type(phys_address), intent(in) iphys, type(phys_address), intent(inout) b_trns, type(spherical_transform_data), intent(inout) trns_back)
Definition at line 238 of file address_sph_trans_snap.f90.
References add_diff_vect_to_sph_trans::add_diff_vect_sph_trns_by_pol(), t_addresses_sph_transform::alloc_sph_trns_field_name(), and m_machine_parameter::iflag_debug.
Referenced by set_address_sph_trans_snap::set_addresses_diff_vect_trans().
bwd_trans_address_ene_flux()
subroutine address_sph_trans_snap::bwd_trans_address_ene_flux (type(phys_data), intent(in) d_rj, type(phys_address), intent(in) ipol, type(phys_address), intent(in) iphys, type(phys_address), intent(inout) b_trns, type(spherical_transform_data), intent(inout) trns_back)
Definition at line 135 of file address_sph_trans_snap.f90.
References add_base_force_4_sph_trns::add_base_force_bwd_trns_snap(), add_base_force_4_sph_trns::add_div_force_4_sph_trns_snap(), add_diff_vect_to_sph_trans::add_grad_4_sph_trns_snap(), add_base_force_4_sph_trns::add_rot_force_4_sph_trns_snap(), add_diffusion_4_sph_trns::add_scalar_diffusion_sph_trns(), add_base_force_4_sph_trns::add_scalar_flux_bwd_trns_snap(), add_prod_field_4_sph_trns::add_subtracted_sph_trns_snap(), add_diffusion_4_sph_trns::add_vector_diffusion_sph_trns(), t_addresses_sph_transform::alloc_sph_trns_field_name(), and m_machine_parameter::iflag_debug.
Referenced by set_address_sph_trans_snap::set_addresses_ene_flux_trans().
bwd_trans_address_snap()
subroutine address_sph_trans_snap::bwd_trans_address_snap (type(phys_data), intent(in) d_rj, type(phys_address), intent(in) ipol, type(phys_address), intent(in) iphys, type(phys_address), intent(inout) b_trns, type(spherical_transform_data), intent(inout) trns_back)
Definition at line 67 of file address_sph_trans_snap.f90.
References add_base_field_4_sph_trns::add_base_scalar_sph_trns_snap(), add_base_field_4_sph_trns::add_base_vector_sph_trns_snap(), t_addresses_sph_transform::alloc_sph_trns_field_name(), and m_machine_parameter::iflag_debug.
Referenced by set_address_sph_trans_snap::set_addresses_snapshot_trans().
fwd_trans_address_diff_vect()
subroutine address_sph_trans_snap::fwd_trans_address_diff_vect (type(phys_data), intent(in) d_rj, type(phys_address), intent(in) ipol, type(phys_address), intent(in) iphys, type(phys_address), intent(inout) f_trns, type(spherical_transform_data), intent(inout) trns_fwd)
Definition at line 268 of file address_sph_trans_snap.f90.
References add_diff_vect_to_sph_trans::add_diff_vect_scalar_trns_bpol(), t_addresses_sph_transform::alloc_sph_trns_field_name(), and m_machine_parameter::iflag_debug.
Referenced by set_address_sph_trans_snap::set_addresses_diff_vect_trans().
fwd_trans_address_ene_flux()
subroutine address_sph_trans_snap::fwd_trans_address_ene_flux (type(phys_data), intent(in) d_rj, type(phys_address), intent(in) ipol, type(phys_address), intent(in) iphys, type(phys_address), intent(inout) f_trns, type(spherical_transform_data), intent(inout) trns_fwd)
Definition at line 196 of file address_sph_trans_snap.f90.
References add_base_force_4_sph_trns::add_base_force_fwd_trns_snap(), add_energy_flux_4_sph_trns::add_ene_flux_4_sph_trns_snap(), add_prod_field_4_sph_trns::add_prod_scalar_sph_trns_snap(), add_prod_field_4_sph_trns::add_prod_vector_sph_trns_snap(), t_addresses_sph_transform::alloc_sph_trns_field_name(), and m_machine_parameter::iflag_debug.
Referenced by set_address_sph_trans_snap::set_addresses_ene_flux_trans().
fwd_trans_address_snap()
subroutine address_sph_trans_snap::fwd_trans_address_snap (type(phys_data), intent(in) d_rj, type(phys_address), intent(in) ipol, type(phys_address), intent(in) iphys, type(phys_address), intent(inout) f_trns, type(spherical_transform_data), intent(inout) trns_fwd)
Definition at line 100 of file address_sph_trans_snap.f90.
References add_base_force_4_sph_trns::add_base_force_sph_trns_snap(), add_base_force_4_sph_trns::add_div_coriolis_mhd_sph_trns(), t_addresses_sph_transform::alloc_sph_trns_field_name(), and m_machine_parameter::iflag_debug.
Referenced by set_address_sph_trans_snap::set_addresses_snapshot_trans().