CALYPSO: sph_rtp_zonal_rms_data Module Reference
sph_rtp_zonal_rms_data Module Reference
Get zonal mean and RMS fields in spherical grid.
Functions/Subroutines
subroutine zonal_mean_all_rtp_field (sph_rtp, node, nod_fld)
subroutine zonal_rms_all_rtp_field (sph_rtp, node, nod_fld)
subroutine zonal_cyl_rms_all_rtp_field (sph_rtp, node, nod_fld)
Detailed Description
Get zonal mean and RMS fields in spherical grid.
      subroutine zonal_mean_all_rtp_field(sph_rtp, node, nod_fld)
      subroutine zonal_rms_all_rtp_field(sph_rtp, node, nod_fld)
      subroutine zonal_cyl_rms_all_rtp_field(sph_rtp, node, nod_fld)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(node_data), intent(in) :: node
        type(phys_data),intent(inout) :: nod_fld
Parameters
numdir Number of component of field
irtp_fld Start address for field \(f(\r,\theta\phi) \)
Function/Subroutine Documentation
zonal_cyl_rms_all_rtp_field()
subroutine sph_rtp_zonal_rms_data::zonal_cyl_rms_all_rtp_field (type(sph_rtp_grid), intent(in) sph_rtp, type(node_data), intent(in) node, type(phys_data), intent(inout) nod_fld)
Definition at line 94 of file sph_rtp_zonal_rms_data.f90.
References cal_sph_zonal_ave_rms_data::cal_sph_zonal_rms_data_pin(), cal_sph_zonal_ave_rms_data::cal_sph_zonal_rms_data_rin(), m_constants::ione, coordinate_convert_4_sph::overwrite_nodal_cyl_2_xyz(), and coordinate_convert_4_sph::overwrite_nodal_xyz_2_cyl().
zonal_mean_all_rtp_field()
subroutine sph_rtp_zonal_rms_data::zonal_mean_all_rtp_field (type(sph_rtp_grid), intent(in) sph_rtp, type(node_data), intent(in) node, type(phys_data), intent(inout) nod_fld)
Definition at line 35 of file sph_rtp_zonal_rms_data.f90.
References cal_sph_zonal_ave_rms_data::cal_sph_zonal_ave_data_pin(), cal_sph_zonal_ave_rms_data::cal_sph_zonal_ave_data_rin(), m_constants::ione, coordinate_convert_4_sph::overwrite_nodal_sph_2_xyz(), and coordinate_convert_4_sph::overwrite_nodal_xyz_2_sph().
Referenced by t_sph_mhd_zonal_mean_viz::sph_mhd_zonal_mean_section().
zonal_rms_all_rtp_field()
subroutine sph_rtp_zonal_rms_data::zonal_rms_all_rtp_field (type(sph_rtp_grid), intent(in) sph_rtp, type(node_data), intent(in) node, type(phys_data), intent(inout) nod_fld)
Definition at line 64 of file sph_rtp_zonal_rms_data.f90.
References cal_sph_zonal_ave_rms_data::cal_sph_zonal_rms_data_pin(), cal_sph_zonal_ave_rms_data::cal_sph_zonal_rms_data_rin(), m_constants::ione, coordinate_convert_4_sph::overwrite_nodal_sph_2_xyz(), and coordinate_convert_4_sph::overwrite_nodal_xyz_2_sph().
Referenced by t_sph_mhd_zonal_mean_viz::sph_mhd_zonal_rms_section().