CALYPSO: calypso_sr_n Module Reference
calypso_sr_n Module Reference
Arbitrary components data communication.
Functions/Subroutines
subroutine calypso_send_recv_n (iflag_recv, NB, nnod_org, nnod_new, npe_send, isend_self, id_pe_send, istack_send, inod_export, npe_recv, irecv_self, id_pe_recv, istack_recv, inod_import, irev_import, SR_sig, SR_r, X_org, X_new)
subroutine calypso_send_recv_3xn (iflag_recv, NB, nnod_org, nnod_new, npe_send, isend_self, id_pe_send, istack_send, inod_export, npe_recv, irecv_self, id_pe_recv, istack_recv, inod_import, irev_import, SR_sig, SR_r, X1_org, X2_org, X3_org, X1_new, X2_new, X3_new)
Detailed Description
Arbitrary components data communication.
      subroutine calypso_send_recv_N                                  &
     &                          (iflag_recv, NB, nnod_org, nnod_new,  &
     &                           npe_send, isend_self,                &
     &                           id_pe_send, istack_send, inod_export,&
     &                           npe_recv, irecv_self,                &
     &                           id_pe_recv, istack_recv, inod_import,&
     &                           irev_import, SR_sig, SR_r,           &
     &                           X_org, X_new)
      subroutine calypso_send_recv_3xN                                &
     &                          (iflag_recv, NB, nnod_org, nnod_new,  &
     &                           npe_send, isend_self,                &
     &                           id_pe_send, istack_send, inod_export,&
     &                           npe_recv, irecv_self,                &
     &                           id_pe_recv, istack_recv, inod_import,&
     &                           irev_import, SR_sig, SR_r,           &
     &                           X1_org, X2_org, X3_org,              &
     &                           X1_new, X2_new, X3_new)
        type(send_recv_status), intent(inout) :: SR_sig
        type(send_recv_real_buffer), intent(inout) :: SR_r
Parameters
NB Number of components for communication
nnod_org Number of data points for origin
nnod_new Number of components for destination
npe_send Number of processses to send
isend_self Integer flag to copy within own process
id_pe_send(npe_send) Process ID to send
istack_send(0:npe_send) End points of send buffer for each process
inod_export(istack_send(npe_send)) local node ID to copy in send buffer
npe_recv Number of processses to receive
irecv_self Integer flag to copy within own process
id_pe_recv(npe_send) Process ID to receive
istack_recv(0:npe_send) End points of receive buffer for each process
inod_import(istack_recv(npe_recv)) local node ID to copy from receive buffer
X_org(NB*nnod_org) Send data
X_new(NB*nnod_new) Received data
Function/Subroutine Documentation
calypso_send_recv_3xn()
subroutine calypso_sr_n::calypso_send_recv_3xn (integer(kind = kint), intent(in) iflag_recv, integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) npe_send, integer(kind = kint), intent(in) isend_self, integer(kind = kint), dimension(npe_send), intent(in) id_pe_send, integer(kind = kint), dimension(0:npe_send), intent(in) istack_send, integer(kind = kint), dimension(istack_send(npe_send)), intent(in) inod_export, integer(kind = kint), intent(in) npe_recv, integer(kind = kint), intent(in) irecv_self, integer(kind = kint), dimension(npe_recv), intent(in) id_pe_recv, integer(kind = kint), dimension(0:npe_recv), intent(in) istack_recv, integer(kind = kint), dimension(istack_recv(npe_recv)), intent(in) inod_import, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, type(send_recv_status), intent(inout) SR_sig, type(send_recv_real_buffer), intent(inout) SR_r, real (kind=kreal), dimension(nb*nnod_org), intent(in) X1_org, real (kind=kreal), dimension(nb*nnod_org), intent(in) X2_org, real (kind=kreal), dimension(nb*nnod_org), intent(in) X3_org, real (kind=kreal), dimension(nb*nnod_new), intent(inout) X1_new, real (kind=kreal), dimension(nb*nnod_new), intent(inout) X2_new, real (kind=kreal), dimension(nb*nnod_new), intent(inout) X3_new)
Parameters
[in,out] sr_sig Structure of communication flags
[in,out] sr_r Structure of communication buffer for 8-byte real
Definition at line 137 of file calypso_SR_N.f90.
References calypso_sr_core::calypso_send_recv_core(), t_solver_sr::calypso_send_recv_fin(), t_solver_sr::resize_work_sr(), select_copy_from_recv::sel_cppy_from_recv_buf_3xn(), and set_to_send_buf_tri::set_to_send_buf_3xn_mod().
calypso_send_recv_n()
subroutine calypso_sr_n::calypso_send_recv_n (integer(kind = kint), intent(in) iflag_recv, integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) npe_send, integer(kind = kint), intent(in) isend_self, integer(kind = kint), dimension(npe_send), intent(in) id_pe_send, integer(kind = kint), dimension(0:npe_send), intent(in) istack_send, integer(kind = kint), dimension(istack_send(npe_send)), intent(in) inod_export, integer(kind = kint), intent(in) npe_recv, integer(kind = kint), intent(in) irecv_self, integer(kind = kint), dimension(npe_recv), intent(in) id_pe_recv, integer(kind = kint), dimension(0:npe_recv), intent(in) istack_recv, integer(kind = kint), dimension(istack_recv(npe_recv)), intent(in) inod_import, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, type(send_recv_status), intent(inout) SR_sig, type(send_recv_real_buffer), intent(inout) SR_r, real (kind=kreal), dimension(nb*nnod_org), intent(in) X_org, real (kind=kreal), dimension(nb*nnod_new), intent(inout) X_new)
Parameters
[in,out] sr_sig Structure of communication flags
[in,out] sr_r Structure of communication buffer for 8-byte real
Definition at line 68 of file calypso_SR_N.f90.
References calypso_sr_core::calypso_send_recv_core(), t_solver_sr::calypso_send_recv_fin(), t_solver_sr::resize_work_sr(), select_copy_from_recv::sel_cppy_from_recv_buf_n(), and select_copy_from_recv::sel_cppy_to_send_buf_n().