CALYPSO: binary_io Module Reference
binary_io Module Reference
Core routines for binary IO.
Functions/Subroutines
subroutine open_write_binary_file (file_name, bbuf)
subroutine open_append_binary_file (file_name, bbuf)
subroutine open_read_binary_file (file_name, id_rank, bbuf)
subroutine close_binary_file (bbuf)
subroutine seek_forward_binary_file (len_byte, bbuf)
subroutine, private write_endian_flag (bbuf)
subroutine write_one_integer_to_32bit (int_dat, bbuf)
subroutine write_one_integer_b (int_dat, bbuf)
subroutine write_one_real_b (real_dat, bbuf)
subroutine write_mul_int_to_32bit (num, int4_dat, bbuf)
subroutine write_mul_int8_b (num, int_gl_dat, bbuf)
subroutine write_mul_integer_b (num, int_dat, bbuf)
subroutine write_integer_stack_b (num, istack, bbuf)
subroutine write_mul_character_b (num, chara_dat, bbuf)
subroutine write_mul_one_character_b (num, chara_dat, bbuf)
subroutine write_1d_vector_b (num, real_dat, bbuf)
subroutine write_2d_vector_b (n1, n2, real_dat, bbuf)
integer function endian_check (id_rank, int_dat)
subroutine, private read_endian_flag (bbuf, id_rank)
subroutine read_one_integer_from_32bit (bbuf, int_dat)
subroutine read_one_integer_b (bbuf, int_dat)
subroutine read_one_real_b (bbuf, real_dat)
subroutine read_mul_int_from_32bit (bbuf, num, int_dat)
subroutine read_mul_int8_b (bbuf, num, int_gl_dat)
subroutine read_mul_integer_b (bbuf, num, int_dat)
subroutine read_integer_stack_b (bbuf, num, istack, ntot)
subroutine read_mul_character_b (bbuf, num, chara_dat)
subroutine read_mul_one_character_b (bbuf, num, chara_dat)
subroutine read_1d_vector_b (bbuf, num, real_dat)
subroutine read_2d_vector_b (bbuf, n1, n2, real_dat)
Detailed Description
Core routines for binary IO.
      subroutine open_write_binary_file(file_name, bbuf)
      subroutine open_append_binary_file(file_name, bbuf)
      subroutine open_read_binary_file(file_name, id_rank, bbuf)
      subroutine close_binary_file
      subroutine seek_forward_binary_file(len_byte, bbuf)
        type(binary_IO_buffer), intent(inout) :: bbuf
      subroutine write_endian_flag(bbuf)
      subroutine write_one_integer_to_32bit(int_dat, bbuf)
      subroutine write_one_integer_b(int_dat, bbuf)
      subroutine write_one_real_b(real_dat, bbuf)
      subroutine write_mul_int_to_32bit(num, int4_dat, bbuf)
      subroutine write_mul_int8_b(num, int_gl_dat, bbuf)
      subroutine write_mul_integer_b(num, int_dat, bbuf)
      subroutine write_integer_stack_b(num, istack, bbuf)
      subroutine write_mul_character_b(num, chara_dat, bbuf)
      subroutine write_mul_one_character_b(num, chara_dat, bbuf)
      subroutine write_1d_vector_b(num, real_dat, bbuf)
      subroutine write_2d_vector_b(n1, n2, real_dat, bbuf)
        type(binary_IO_buffer), intent(inout) :: bbuf
      integer function endian_check(id_rank, int_dat)
      subroutine read_one_integer_from_32bit(bbuf, int_dat)
      subroutine read_one_integer_b(bbuf, int_dat)
      subroutine read_one_real_b(bbuf, real_dat)
      subroutine read_mul_int_from_32bit(bbuf, num, int_dat)
      subroutine read_mul_int8_b(bbuf, num, int_gl_dat)
      subroutine read_mul_integer_b(bbuf, num, int_dat)
      subroutine read_integer_stack_b(bbuf, num, istack, ntot)
      subroutine read_mul_character_b(bbuf, num, chara_dat)
      subroutine read_mul_one_character_b(bbuf, num, chara_dat)
      subroutine read_1d_vector_b(bbuf, num, real_dat)
      subroutine read_2d_vector_b(bbuf, n1, n2, real_dat)
        type(binary_IO_buffer), intent(inout) :: bbuf
        type(binary_IO_buffer), intent(inout) :: bbuf
Function/Subroutine Documentation
close_binary_file()
subroutine binary_io::close_binary_file (type(binary_io_buffer), intent(in) bbuf)
Definition at line 114 of file binary_IO.F90.
Referenced by element_file_io_b::input_edge_file_b(), element_file_io_b::input_element_file_b(), element_file_io_b::input_surface_file_b(), element_file_io_b::output_edge_file_b(), element_file_io_b::output_element_file_b(), element_file_io_b::output_surface_file_b(), read_psf_binary_file::read_alloc_iso_bin_file(), read_psf_binary_file::read_alloc_nostep_iso_bin_file(), read_psf_binary_file::read_alloc_nostep_psf_bin_file(), read_psf_binary_file::read_alloc_psf_bin_file(), read_psf_binary_file::read_alloc_psf_bin_grid(), ucd_field_file_io_b::read_alloc_ucd_2_fld_file_b(), ucd_field_file_io_b::read_alloc_ucd_2_fld_header_b(), field_file_io_b::read_and_allocate_step_field_b(), field_file_io_b::read_and_allocate_step_head_b(), sph_modes_grids_file_io_b::read_geom_rtm_file_b(), sph_modes_grids_file_io_b::read_geom_rtp_file_b(), mesh_file_io_b::read_geometry_size_b(), read_psf_binary_file::read_iso_bin_file(), mesh_file_io_b::read_mesh_file_b(), mesh_file_io_b::read_mesh_geometry_b(), sph_modes_grids_file_io_b::read_modes_rlm_file_b(), mesh_file_io_b::read_node_size_b(), read_psf_binary_file::read_psf_bin_file(), read_psf_binary_file::read_psf_bin_grid(), sph_modes_grids_file_io_b::read_spectr_modes_rj_file_b(), field_file_io_b::read_step_field_file_b(), ucd_field_file_io_b::read_ucd_2_fld_file_b(), sph_modes_grids_file_io_b::write_geom_rtm_file_b(), sph_modes_grids_file_io_b::write_geom_rtp_file_b(), mesh_file_io_b::write_mesh_file_b(), sph_modes_grids_file_io_b::write_modes_rlm_file_b(), sph_modes_grids_file_io_b::write_spectr_modes_rj_file_b(), field_file_io_b::write_step_field_file_b(), and ucd_field_file_io_b::write_ucd_2_fld_file_b().
endian_check()
integer function binary_io::endian_check (integer, intent(in) id_rank, integer, intent(in) int_dat)
Definition at line 324 of file binary_IO.F90.
References m_machine_parameter::i_unix, m_machine_parameter::i_xinu, m_machine_parameter::iendian_flip, and m_machine_parameter::iendian_keep.
Referenced by gz_binary_io::gz_read_endian_flag(), data_convert_by_zlib::infleate_endian_flag(), m_calypso_mpi_io::mpi_read_set_endian_flag(), and read_endian_flag().
open_append_binary_file()
subroutine binary_io::open_append_binary_file (character(len=kchara), intent(in) file_name, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 81 of file binary_IO.F90.
open_read_binary_file()
subroutine binary_io::open_read_binary_file (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 96 of file binary_IO.F90.
References read_endian_flag().
Referenced by element_file_io_b::input_edge_file_b(), element_file_io_b::input_element_file_b(), element_file_io_b::input_surface_file_b(), read_psf_binary_file::read_alloc_iso_bin_file(), read_psf_binary_file::read_alloc_nostep_iso_bin_file(), read_psf_binary_file::read_alloc_nostep_psf_bin_file(), read_psf_binary_file::read_alloc_psf_bin_file(), read_psf_binary_file::read_alloc_psf_bin_grid(), ucd_field_file_io_b::read_alloc_ucd_2_fld_file_b(), ucd_field_file_io_b::read_alloc_ucd_2_fld_header_b(), field_file_io_b::read_and_allocate_step_field_b(), field_file_io_b::read_and_allocate_step_head_b(), sph_modes_grids_file_io_b::read_geom_rtm_file_b(), sph_modes_grids_file_io_b::read_geom_rtp_file_b(), mesh_file_io_b::read_geometry_size_b(), read_psf_binary_file::read_iso_bin_file(), mesh_file_io_b::read_mesh_file_b(), mesh_file_io_b::read_mesh_geometry_b(), sph_modes_grids_file_io_b::read_modes_rlm_file_b(), mesh_file_io_b::read_node_size_b(), read_psf_binary_file::read_psf_bin_file(), read_psf_binary_file::read_psf_bin_grid(), sph_modes_grids_file_io_b::read_spectr_modes_rj_file_b(), field_file_io_b::read_step_field_file_b(), and ucd_field_file_io_b::read_ucd_2_fld_file_b().
open_write_binary_file()
subroutine binary_io::open_write_binary_file (character(len=kchara), intent(in) file_name, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 65 of file binary_IO.F90.
References write_endian_flag().
Referenced by element_file_io_b::output_edge_file_b(), element_file_io_b::output_element_file_b(), element_file_io_b::output_surface_file_b(), sph_modes_grids_file_io_b::write_geom_rtm_file_b(), sph_modes_grids_file_io_b::write_geom_rtp_file_b(), mesh_file_io_b::write_mesh_file_b(), sph_modes_grids_file_io_b::write_modes_rlm_file_b(), sph_modes_grids_file_io_b::write_spectr_modes_rj_file_b(), field_file_io_b::write_step_field_file_b(), and ucd_field_file_io_b::write_ucd_2_fld_file_b().
read_1d_vector_b()
subroutine binary_io::read_1d_vector_b (type(binary_io_buffer), intent(inout) bbuf, integer(kind = kint_gl), intent(in) num, real(kind = kreal), dimension(num), intent(inout) real_dat)
Definition at line 537 of file binary_IO.F90.
Referenced by read_2d_vector_b(), read_one_real_b(), read_psf_binary_data::read_psf_phys_data_bin(), sph_global_1d_idx_io_b::read_rj_gl_1d_table_b(), sph_global_1d_idx_io_b::read_rtp_gl_1d_table_b(), and node_geometry_io_b::read_scalar_in_element_b().
read_2d_vector_b()
subroutine binary_io::read_2d_vector_b (type(binary_io_buffer), intent(inout) bbuf, integer(kind = kint_gl), intent(in) n1, integer(kind = kint), intent(in) n2, real(kind = kreal), dimension(n1,n2), intent(inout) real_dat)
Definition at line 561 of file binary_IO.F90.
References transfer_to_long_integers::cast_long(), and read_1d_vector_b().
Referenced by field_data_io_b::read_field_data_b(), node_geometry_io_b::read_geometry_info_b(), and node_geometry_io_b::read_vector_in_element_b().
read_endian_flag()
subroutine, private binary_io::read_endian_flag (type(binary_io_buffer), intent(inout) bbuf, integer, intent(in) id_rank) private
Definition at line 346 of file binary_IO.F90.
References endian_check(), m_machine_parameter::iendian_keep, and m_error_ids::ierr_file.
Referenced by open_read_binary_file().
read_integer_stack_b()
subroutine binary_io::read_integer_stack_b (type(binary_io_buffer), intent(inout) bbuf, integer(kind = kint_gl), intent(in) num, integer(kind = kint), dimension(0:num), intent(inout) istack, integer(kind = kint), intent(inout) ntot)
Definition at line 484 of file binary_IO.F90.
References read_mul_integer_b().
Referenced by domain_data_io_b::read_export_data_b(), groups_io_b::read_group_data_b(), domain_data_io_b::read_import_data_b(), and groups_io_b::read_surf_grp_data_b().
read_mul_character_b()
subroutine binary_io::read_mul_character_b (type(binary_io_buffer), intent(inout) bbuf, integer(kind = kint), intent(in) num, character(len=kchara), dimension(num), intent(inout) chara_dat)
Definition at line 501 of file binary_IO.F90.
Referenced by field_data_io_b::read_field_data_b(), groups_io_b::read_group_data_b(), read_psf_binary_data::read_psf_phys_name_bin(), and groups_io_b::read_surf_grp_data_b().
read_mul_int8_b()
subroutine binary_io::read_mul_int8_b (type(binary_io_buffer), intent(inout) bbuf, integer(kind = kint_gl), intent(in) num, integer(kind = kint_gl), dimension(num), intent(inout) int_gl_dat)
Definition at line 438 of file binary_IO.F90.
Referenced by element_connect_io_b::read_element_info_b(), node_geometry_io_b::read_geometry_info_b(), spherical_model_io_b::read_gl_nodes_sph_b(), read_mul_integer_b(), read_one_integer_b(), read_one_integer_from_32bit(), read_psf_binary_data::read_psf_ele_connect_bin(), read_psf_binary_data::read_psf_ele_num_bin(), read_psf_binary_data::read_psf_node_num_bin(), read_psf_binary_data::read_psf_phys_data_bin(), and field_data_io_b::read_step_data_b().
read_mul_int_from_32bit()
subroutine binary_io::read_mul_int_from_32bit (type(binary_io_buffer), intent(inout) bbuf, integer(kind = kint_gl), intent(in) num, integer(kind = kint_4b), dimension(num), intent(inout) int_dat)
Definition at line 414 of file binary_IO.F90.
read_mul_integer_b()
subroutine binary_io::read_mul_integer_b (type(binary_io_buffer), intent(inout) bbuf, integer(kind = kint_gl), intent(in) num, integer(kind = kint), dimension(num), intent(inout) int_dat)
Definition at line 462 of file binary_IO.F90.
References transfer_to_long_integers::alloc_1d_i8array(), transfer_to_long_integers::dup_to_short_array(), and read_mul_int8_b().
Referenced by ucd_field_file_io_b::read_alloc_ucd_2_fld_file_b(), ucd_field_file_io_b::read_alloc_ucd_2_fld_header_b(), field_file_io_b::read_and_allocate_step_b(), domain_data_io_b::read_domain_info_b(), element_connect_io_b::read_edge_4_element_b(), element_connect_io_b::read_element_info_b(), domain_data_io_b::read_export_data_b(), spherical_model_io_b::read_gl_nodes_sph_b(), spherical_model_io_b::read_gl_resolution_sph_b(), groups_io_b::read_group_data_b(), domain_data_io_b::read_import_data_b(), read_integer_stack_b(), read_psf_binary_data::read_psf_phys_name_bin(), spherical_model_io_b::read_rank_4_sph_b(), sph_global_1d_idx_io_b::read_rj_gl_1d_table_b(), sph_global_1d_idx_io_b::read_rtp_gl_1d_table_b(), field_file_io_b::read_step_field_file_b(), groups_io_b::read_surf_grp_data_b(), element_connect_io_b::read_surface_4_element_b(), and ucd_field_file_io_b::read_ucd_2_fld_file_b().
read_mul_one_character_b()
subroutine binary_io::read_mul_one_character_b (type(binary_io_buffer), intent(inout) bbuf, integer(kind = kint_gl), intent(in) num, character(len=1), dimension(num), intent(inout) chara_dat)
Definition at line 519 of file binary_IO.F90.
read_one_integer_b()
subroutine binary_io::read_one_integer_b (type(binary_io_buffer), intent(inout) bbuf, integer(kind = kint), intent(inout) int_dat)
Definition at line 382 of file binary_IO.F90.
References read_mul_int8_b().
Referenced by read_psf_binary_file::read_alloc_iso_bin_file(), read_psf_binary_file::read_alloc_nostep_iso_bin_file(), read_psf_binary_file::read_alloc_nostep_psf_bin_file(), read_psf_binary_file::read_alloc_psf_bin_grid(), domain_data_io_b::read_domain_info_b(), element_connect_io_b::read_edge_4_element_b(), spherical_model_io_b::read_gl_nodes_sph_b(), spherical_model_io_b::read_gl_resolution_sph_b(), groups_io_b::read_group_data_b(), read_psf_binary_file::read_iso_bin_file(), element_connect_io_b::read_number_of_element_b(), node_geometry_io_b::read_number_of_node_b(), read_psf_binary_file::read_psf_bin_grid(), read_udt_from_bindary_data::read_psf_bin_time_data(), read_psf_binary_data::read_psf_phys_num_bin(), node_geometry_io_b::read_scalar_in_element_b(), field_data_io_b::read_step_data_b(), groups_io_b::read_surf_grp_data_b(), element_connect_io_b::read_surface_4_element_b(), and node_geometry_io_b::read_vector_in_element_b().
read_one_integer_from_32bit()
subroutine binary_io::read_one_integer_from_32bit (type(binary_io_buffer), intent(inout) bbuf, integer(kind = kint_4b), intent(inout) int_dat)
Definition at line 366 of file binary_IO.F90.
References read_mul_int8_b().
read_one_real_b()
subroutine binary_io::read_one_real_b (type(binary_io_buffer), intent(inout) bbuf, real(kind = kreal), intent(inout) real_dat)
Definition at line 398 of file binary_IO.F90.
References read_1d_vector_b().
Referenced by read_udt_from_bindary_data::read_psf_bin_time_data(), and field_data_io_b::read_step_data_b().
seek_forward_binary_file()
subroutine binary_io::seek_forward_binary_file (integer(kind = kint_gl), intent(in) len_byte, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 124 of file binary_IO.F90.
write_1d_vector_b()
subroutine binary_io::write_1d_vector_b (integer(kind = kint_gl), intent(in) num, real(kind = kreal), dimension(num), intent(in) real_dat, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 290 of file binary_IO.F90.
Referenced by write_2d_vector_b(), write_one_real_b(), sph_global_1d_idx_io_b::write_rj_gl_1d_table_b(), sph_global_1d_idx_io_b::write_rtp_gl_1d_table_b(), and node_geometry_io_b::write_scalar_in_element_b().
write_2d_vector_b()
subroutine binary_io::write_2d_vector_b (integer(kind = kint_gl), intent(in) n1, integer(kind = kint), intent(in) n2, real(kind = kreal), dimension(n1,n2), intent(in) real_dat, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 303 of file binary_IO.F90.
References transfer_to_long_integers::cast_long(), and write_1d_vector_b().
Referenced by field_data_io_b::write_field_data_b(), node_geometry_io_b::write_geometry_info_b(), and node_geometry_io_b::write_vector_in_element_b().
write_endian_flag()
subroutine, private binary_io::write_endian_flag (type(binary_io_buffer), intent(inout) bbuf) private
Definition at line 139 of file binary_IO.F90.
References m_machine_parameter::i_unix, and write_mul_int_to_32bit().
Referenced by open_write_binary_file().
write_integer_stack_b()
subroutine binary_io::write_integer_stack_b (integer(kind = kint_gl), intent(in) num, integer(kind = kint), dimension(0:num), intent(in) istack, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 251 of file binary_IO.F90.
References write_mul_integer_b().
Referenced by domain_data_io_b::write_export_data_b(), groups_io_b::write_grp_data_b(), domain_data_io_b::write_import_data_b(), and groups_io_b::write_surf_grp_data_b().
write_mul_character_b()
subroutine binary_io::write_mul_character_b (integer(kind = kint), intent(in) num, character(len=kchara), dimension(num), intent(in) chara_dat, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 264 of file binary_IO.F90.
Referenced by field_data_io_b::write_field_data_b(), groups_io_b::write_grp_data_b(), and groups_io_b::write_surf_grp_data_b().
write_mul_int8_b()
subroutine binary_io::write_mul_int8_b (integer(kind = kint_gl), intent(in) num, integer(kind = kint_gl), dimension(num), intent(in) int_gl_dat, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 218 of file binary_IO.F90.
Referenced by element_connect_io_b::write_element_info_b(), field_data_io_b::write_field_data_b(), node_geometry_io_b::write_geometry_info_b(), spherical_model_io_b::write_gl_nodes_sph_b(), write_mul_integer_b(), write_one_integer_b(), and write_one_integer_to_32bit().
write_mul_int_to_32bit()
subroutine binary_io::write_mul_int_to_32bit (integer(kind = kint_gl), intent(in) num, integer(kind = kint_4b), dimension(num), intent(in) int4_dat, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 205 of file binary_IO.F90.
Referenced by write_endian_flag().
write_mul_integer_b()
subroutine binary_io::write_mul_integer_b (integer(kind = kint_gl), intent(in) num, integer(kind = kint), dimension(num), intent(in) int_dat, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 231 of file binary_IO.F90.
References transfer_to_long_integers::dealloc_1d_i8array(), transfer_to_long_integers::dup_from_short_array(), and write_mul_int8_b().
Referenced by domain_data_io_b::write_domain_info_b(), element_connect_io_b::write_edge_4_element_b(), element_connect_io_b::write_element_info_b(), domain_data_io_b::write_export_data_b(), field_data_io_b::write_field_data_b(), spherical_model_io_b::write_gl_nodes_sph_b(), spherical_model_io_b::write_gl_resolution_sph_b(), groups_io_b::write_grp_data_b(), domain_data_io_b::write_import_data_b(), write_integer_stack_b(), spherical_model_io_b::write_rank_4_sph_b(), sph_global_1d_idx_io_b::write_rj_gl_1d_table_b(), sph_global_1d_idx_io_b::write_rtp_gl_1d_table_b(), groups_io_b::write_surf_grp_data_b(), and element_connect_io_b::write_surface_4_element_b().
write_mul_one_character_b()
subroutine binary_io::write_mul_one_character_b (integer(kind = kint_gl), intent(in) num, character(len=1), dimension(num), intent(in) chara_dat, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 277 of file binary_IO.F90.
write_one_integer_b()
subroutine binary_io::write_one_integer_b (integer(kind = kint), intent(in) int_dat, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 171 of file binary_IO.F90.
References transfer_to_long_integers::cast_long(), and write_mul_int8_b().
Referenced by domain_data_io_b::write_domain_info_b(), element_connect_io_b::write_edge_4_element_b(), element_connect_io_b::write_element_info_b(), field_data_io_b::write_field_data_b(), node_geometry_io_b::write_geometry_info_b(), spherical_model_io_b::write_gl_nodes_sph_b(), spherical_model_io_b::write_gl_resolution_sph_b(), groups_io_b::write_grp_data_b(), node_geometry_io_b::write_scalar_in_element_b(), field_data_io_b::write_step_data_b(), groups_io_b::write_surf_grp_data_b(), element_connect_io_b::write_surface_4_element_b(), and node_geometry_io_b::write_vector_in_element_b().
write_one_integer_to_32bit()
subroutine binary_io::write_one_integer_to_32bit (integer(kind = kint_4b), intent(in) int_dat, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 153 of file binary_IO.F90.
References transfer_to_long_integers::cast_long(), and write_mul_int8_b().
write_one_real_b()
subroutine binary_io::write_one_real_b (real(kind = kreal), intent(in) real_dat, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 189 of file binary_IO.F90.
References write_1d_vector_b().
Referenced by field_data_io_b::write_step_data_b().