CALYPSO: copy_pole_field_sph_trans Module Reference
copy_pole_field_sph_trans Module Reference
copy field data from spherical transform for poles
Functions/Subroutines
subroutine copy_pole_vec_fld_from_trans (m_folding, sph_rtp, node, v_pole, i_fld, nod_fld)
subroutine copy_pole_scl_fld_from_trans (m_folding, sph_rtp, node, v_pole, i_fld, nod_fld)
subroutine copy_pole_tsr_fld_from_trans (m_folding, sph_rtp, node, v_pole, i_fld, nod_fld)
subroutine, private copy_pole_vector_from_trans (numnod, internal_node, xx, ntot_phys, nnod_rtp, nnod_pole, m_folding, nidx_rtp_r, nidx_rtp_gl_r, idx_gl_rtp_r, v_pole, i_fld, d_nod)
subroutine, private copy_pole_scalar_from_trans (numnod, internal_node, xx, ntot_phys, nnod_rtp, nnod_pole, m_folding, nidx_rtp_r, nidx_rtp_gl_r, idx_gl_rtp_r, v_pole, i_fld, d_nod)
subroutine, private copy_pole_tensor_from_trans (numnod, internal_node, xx, ntot_phys, nnod_rtp, nnod_pole, m_folding, nidx_rtp_r, nidx_rtp_gl_r, idx_gl_rtp_r, v_pole, i_fld, d_nod)
Detailed Description
copy field data from spherical transform for poles
      subroutine copy_pole_vec_fld_from_trans(m_folding,              &
     &          sph_rtp, node, v_pole, i_fld, nod_fld)
      subroutine copy_pole_scl_fld_from_trans(m_folding,              &
     &          sph_rtp, node, v_pole, i_fld, nod_fld)
      subroutine copy_pole_tsr_fld_from_trans(m_folding,              &
     &          sph_rtp, node, v_pole, i_fld, nod_fld)
        type(node_data), intent(in) :: node
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(phys_data),intent(inout) :: nod_fld
Function/Subroutine Documentation
copy_pole_scalar_from_trans()
subroutine, private copy_pole_field_sph_trans::copy_pole_scalar_from_trans (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) internal_node, real(kind = kreal), dimension(numnod,3), intent(in) xx, integer(kind = kint), intent(in) ntot_phys, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) nnod_pole, integer(kind = kint), intent(in) m_folding, integer(kind = kint), intent(in) nidx_rtp_r, integer(kind = kint), intent(in) nidx_rtp_gl_r, integer(kind = kint), dimension(nidx_rtp_gl_r), intent(in) idx_gl_rtp_r, real(kind = kreal), dimension(nnod_pole), intent(in) v_pole, integer(kind = kint), intent(in) i_fld, real(kind = kreal), dimension(numnod, ntot_phys), intent(inout) d_nod) private
Definition at line 187 of file copy_pole_field_sph_trans.f90.
References m_constants::zero.
Referenced by copy_pole_scl_fld_from_trans().
copy_pole_scl_fld_from_trans()
subroutine copy_pole_field_sph_trans::copy_pole_scl_fld_from_trans (integer(kind = kint), intent(in) m_folding, type(sph_rtp_grid), intent(in) sph_rtp, type(node_data), intent(in) node, real(kind = kreal), dimension(sph_rtp%nnod_pole), intent(in) v_pole, integer(kind = kint), intent(in) i_fld, type(phys_data), intent(inout) nod_fld)
Definition at line 71 of file copy_pole_field_sph_trans.f90.
References copy_pole_scalar_from_trans().
Referenced by copy_nodal_fld_4_sph_trans::copy_nod_scl_from_trans_wpole(), and copy_mhd_4_pole_trans::copy_snap_vec_from_pole_trans().
copy_pole_tensor_from_trans()
subroutine, private copy_pole_field_sph_trans::copy_pole_tensor_from_trans (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) internal_node, real(kind = kreal), dimension(numnod,3), intent(in) xx, integer(kind = kint), intent(in) ntot_phys, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) nnod_pole, integer(kind = kint), intent(in) m_folding, integer(kind = kint), intent(in) nidx_rtp_r, integer(kind = kint), intent(in) nidx_rtp_gl_r, integer(kind = kint), dimension(nidx_rtp_gl_r), intent(in) idx_gl_rtp_r, real(kind = kreal), dimension(nnod_pole,6), intent(in) v_pole, integer(kind = kint), intent(in) i_fld, real(kind = kreal), dimension(numnod, ntot_phys), intent(inout) d_nod) private
Definition at line 242 of file copy_pole_field_sph_trans.f90.
References m_constants::zero.
Referenced by copy_pole_tsr_fld_from_trans().
copy_pole_tsr_fld_from_trans()
subroutine copy_pole_field_sph_trans::copy_pole_tsr_fld_from_trans (integer(kind = kint), intent(in) m_folding, type(sph_rtp_grid), intent(in) sph_rtp, type(node_data), intent(in) node, real(kind = kreal), dimension(sph_rtp%nnod_pole,6), intent(in) v_pole, integer(kind = kint), intent(in) i_fld, type(phys_data), intent(inout) nod_fld)
Definition at line 99 of file copy_pole_field_sph_trans.f90.
References copy_pole_tensor_from_trans().
Referenced by copy_nodal_fld_4_sph_trans::copy_nod_tsr_from_trans_wpole().
copy_pole_vec_fld_from_trans()
subroutine copy_pole_field_sph_trans::copy_pole_vec_fld_from_trans (integer(kind = kint), intent(in) m_folding, type(sph_rtp_grid), intent(in) sph_rtp, type(node_data), intent(in) node, real(kind = kreal), dimension(sph_rtp%nnod_pole,3), intent(in) v_pole, integer(kind = kint), intent(in) i_fld, type(phys_data), intent(inout) nod_fld)
Definition at line 43 of file copy_pole_field_sph_trans.f90.
References copy_pole_vector_from_trans().
Referenced by copy_nodal_fld_4_sph_trans::copy_nod_vec_from_trans_wpole(), and copy_mhd_4_pole_trans::copy_snap_vec_from_pole_trans().
copy_pole_vector_from_trans()
subroutine, private copy_pole_field_sph_trans::copy_pole_vector_from_trans (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) internal_node, real(kind = kreal), dimension(numnod,3), intent(in) xx, integer(kind = kint), intent(in) ntot_phys, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) nnod_pole, integer(kind = kint), intent(in) m_folding, integer(kind = kint), intent(in) nidx_rtp_r, integer(kind = kint), intent(in) nidx_rtp_gl_r, integer(kind = kint), dimension(nidx_rtp_gl_r), intent(in) idx_gl_rtp_r, real(kind = kreal), dimension(nnod_pole,3), intent(in) v_pole, integer(kind = kint), intent(in) i_fld, real(kind = kreal), dimension(numnod, ntot_phys), intent(inout) d_nod) private
Definition at line 128 of file copy_pole_field_sph_trans.f90.
References m_constants::zero.
Referenced by copy_pole_vec_fld_from_trans().