CALYPSO: solve_sph_fluid_crank Module Reference
solve_sph_fluid_crank Module Reference
Update each field for MHD dynamo model.
Functions/Subroutines
subroutine solve_velo_by_vort_sph_crank (sph_rj, band_vp_evo, band_vt_evo, is_velo, n_point, ntot_phys_rj, d_rj)
subroutine solve_pressure_by_div_v (sph_rj, band_p_poisson, is_press, n_point, ntot_phys_rj, d_rj)
subroutine solve_magne_sph_crank (sph_rj, band_bp_evo, band_bt_evo, is_magne, n_point, ntot_phys_rj, d_rj)
subroutine solve_scalar_sph_crank (sph_rj, band_s_evo, band_s00_evo, is_field, n_point, ntot_phys_rj, d_rj, sol_00)
subroutine, private check_scalar_coefs (id_file, l, m, sph_rj, is_field, n_point, ntot_phys_rj, d_rj)
subroutine, private check_nan_temperature (is_field, sph_rj, n_point, ntot_phys_rj, d_rj)
Detailed Description
Update each field for MHD dynamo model.
      subroutine solve_velo_by_vort_sph_crank                         &
     &         (sph_rj, band_vp_evo, band_vt_evo,                     &
     &          is_velo, n_point, ntot_phys_rj, d_rj)
        Input address:    is_velo, is_velo+2
        Solution address: is_velo, is_velo+2
      subroutine solve_pressure_by_div_v(sph_rj, band_p_poisson,      &
     &          is_press, n_point, ntot_phys_rj, d_rj)
      subroutine solve_magne_sph_crank                                &
     &         (sph_rj, band_bp_evo, band_bt_evo, is_magne,           &
     &          n_point, ntot_phys_rj, d_rj)
        Input address:    is_magne, is_magne+2
        Solution address: is_magne, is_magne+2
      subroutine solve_scalar_sph_crank                               &
     &         (sph_rj, band_s_evo, band_s00_evo, is_field,           &
     &          n_point, ntot_phys_rj, d_rj, sol_00)
        Input address:    is_field
        Solution address: is_field
Parameters
ntot_phys_rj Total number of components
d_rj Spectrum data
Function/Subroutine Documentation
check_nan_temperature()
subroutine, private solve_sph_fluid_crank::check_nan_temperature (integer(kind = kint), intent(in) is_field, type(sph_rj_grid), intent(in) sph_rj, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj) private
Definition at line 256 of file solve_sph_fluid_crank.f90.
References spherical_harmonics::get_degree_order_by_full_j(), and calypso_mpi::my_rank.
check_scalar_coefs()
subroutine, private solve_sph_fluid_crank::check_scalar_coefs (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) l, integer(kind = kint), intent(in) m, type(sph_rj_grid), intent(in) sph_rj, integer(kind = kint), intent(in) is_field, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj) private
Definition at line 228 of file solve_sph_fluid_crank.f90.
References t_spheric_rj_data::find_local_sph_address().
Referenced by solve_pressure_by_div_v().
solve_magne_sph_crank()
subroutine solve_sph_fluid_crank::solve_magne_sph_crank (type(sph_rj_grid), intent(in) sph_rj, type(band_matrices_type), intent(in) band_bp_evo, type(band_matrices_type), intent(in) band_bt_evo, integer(kind = kint), intent(in) is_magne, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 141 of file solve_sph_fluid_crank.f90.
References t_sph_matrices::lubksb_3band_mul_t(), and m_machine_parameter::np_smp.
Referenced by cal_sol_sph_fluid_crank::cal_sol_magne_sph_crank().
solve_pressure_by_div_v()
subroutine solve_sph_fluid_crank::solve_pressure_by_div_v (type(sph_rj_grid), intent(in) sph_rj, type(band_matrices_type), intent(in) band_p_poisson, integer(kind = kint), intent(in) is_press, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 93 of file solve_sph_fluid_crank.f90.
References check_scalar_coefs(), check_sph_radial_mat::check_single_radial_3band_mat(), check_sph_radial_mat::check_single_radial_5band_mat(), t_spheric_rj_data::find_local_sph_address(), m_machine_parameter::i_debug, t_sph_matrices::lubksb_3band_mul_t(), and m_machine_parameter::np_smp.
Referenced by cal_sol_sph_fluid_crank::cal_sol_pressure_by_div_v().
solve_scalar_sph_crank()
subroutine solve_sph_fluid_crank::solve_scalar_sph_crank (type(sph_rj_grid), intent(in) sph_rj, type(band_matrices_type), intent(in) band_s_evo, type(band_matrix_type), intent(in) band_s00_evo, integer(kind = kint), intent(in) is_field, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj, real(kind = kreal), dimension(0:sph_rj%nidx_rj(1)), intent(inout) sol_00)
Definition at line 164 of file solve_sph_fluid_crank.f90.
References fill_scalar_field::copy_degree0_comps_from_sol(), fill_scalar_field::copy_degree0_comps_to_sol(), t_sph_center_matrix::lubksb_3band_ctr(), t_sph_matrices::lubksb_3band_mul_t(), and m_machine_parameter::np_smp.
Referenced by cal_sol_sph_fluid_crank::cal_sol_scalar_sph_crank().
solve_velo_by_vort_sph_crank()
subroutine solve_sph_fluid_crank::solve_velo_by_vort_sph_crank (type(sph_rj_grid), intent(in) sph_rj, type(band_matrices_type), intent(in) band_vp_evo, type(band_matrices_type), intent(in) band_vt_evo, integer(kind = kint), intent(in) is_velo, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 57 of file solve_sph_fluid_crank.f90.
References t_sph_matrices::lubksb_3band_mul_t(), t_sph_matrices::lubksb_5band_mul_t(), and m_machine_parameter::np_smp.
Referenced by cal_sol_sph_fluid_crank::cal_sol_velo_by_vort_sph_crank().