CALYPSO: initial_magne_dynamobench Module Reference
initial_magne_dynamobench Module Reference
Set initial magnetic field for pseudo vacuume boundary banchmark.
Functions/Subroutines
subroutine initial_b_dynamobench_1 (sph_rj, ipol, r_ICB, r_CMB, nlayer_ICB, nlayer_CMB, n_point, ntot_phys_rj, d_rj)
subroutine initial_b_dynamobench_2 (sph_rj, ipol, nlayer_CMB, r_CMB, n_point, ntot_phys_rj, d_rj)
Detailed Description
Set initial magnetic field for pseudo vacuume boundary banchmark.
      subroutine initial_b_dynamobench_1                              &
     &         (sph_rj, ipol, r_ICB, r_CMB, nlayer_ICB, nlayer_CMB,   &
     &          n_point, ntot_phys_rj, d_rj)
        type(sph_rj_grid), intent(in) :: sph_rj
        type(phys_address), intent(in) :: ipol
      subroutine initial_b_dynamobench_2(sph_rj, ipol,                &
     &          nlayer_CMB, r_CMB, n_point, ntot_phys_rj, d_rj)
        type(sph_rj_grid), intent(in) :: sph_rj
        type(phys_address), intent(in) :: ipol
Function/Subroutine Documentation
initial_b_dynamobench_1()
subroutine initial_magne_dynamobench::initial_b_dynamobench_1 (type(sph_rj_grid), intent(in) sph_rj, type(phys_address), intent(in) ipol, real(kind = kreal), intent(in) r_ICB, real(kind = kreal), intent(in) r_CMB, integer(kind = kint), intent(in) nlayer_ICB, integer(kind = kint), intent(in) nlayer_CMB, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 38 of file initial_magne_dynamobench.f90.
References m_constants::dnine, m_constants::eight, t_spheric_rj_data::find_local_sph_address(), m_constants::five, m_constants::four, m_constants::one, m_constants::ten, m_constants::three, m_constants::two, and m_constants::zero.
Referenced by set_initial_sph_dynamo::sph_initial_data_4_benchmarks().
initial_b_dynamobench_2()
subroutine initial_magne_dynamobench::initial_b_dynamobench_2 (type(sph_rj_grid), intent(in) sph_rj, type(phys_address), intent(in) ipol, integer(kind = kint), intent(in) nlayer_CMB, real(kind = kreal), intent(in) r_CMB, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 102 of file initial_magne_dynamobench.f90.
References m_constants::dnine, m_constants::eight, t_spheric_rj_data::find_local_sph_address(), m_constants::five, m_constants::four, m_constants::one, m_constants::six, m_constants::ten, m_constants::three, m_constants::two, and m_constants::zero.
Referenced by set_initial_sph_dynamo::sph_initial_data_4_benchmarks().