CALYPSO: gz_ucd_field_mpi_io_b Module Reference
gz_ucd_field_mpi_io_b Module Reference
Output ucd data into gzipped binary field file using MPI-IO.
Functions/Subroutines
subroutine gz_write_ucd_field_file_mpi_b (file_name, t_IO, ucd)
subroutine gz_read_ucd_field_file_mpi_b (file_name, num_pe, id_rank, t_IO, ucd)
subroutine gz_rd_alloc_ucd_fld_file_mpi_b (file_name, num_pe, id_rank, t_IO, ucd)
Variables
type(calypso_mpi_io_params), save, private io_param
Detailed Description
Output ucd data into gzipped binary field file using MPI-IO.
      subroutine gz_write_ucd_field_file_mpi_b(file_name, t_IO, ucd)
        type(time_data), intent(in) :: t_IO
        type(ucd_data), intent(in) :: ucd
      subroutine gz_read_ucd_field_file_mpi_b                         &
     &         (file_name, num_pe, id_rank, t_IO, ucd)
      subroutine gz_rd_alloc_ucd_fld_file_mpi_b                       &
     &         (file_name, num_pe, id_rank, t_IO, ucd)
        type(time_data), intent(inout) :: t_IO
        type(ucd_data), intent(inout) :: ucd
Function/Subroutine Documentation
gz_rd_alloc_ucd_fld_file_mpi_b()
subroutine gz_ucd_field_mpi_io_b::gz_rd_alloc_ucd_fld_file_mpi_b (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, type(time_data), intent(inout) t_IO, type(ucd_data), intent(inout) ucd)
Definition at line 118 of file gz_ucd_field_MPI_IO_b.f90.
References t_ucd_data::allocate_ucd_phys_data(), t_ucd_data::allocate_ucd_phys_name(), t_ucd_data::cal_istack_ucd_component(), mpi_ascii_data_io::close_mpi_file(), t_ucd_data::deallocate_ucd_phys_data(), t_ucd_data::deallocate_ucd_phys_name(), gz_mpi_binary_data_io::gz_mpi_read_2d_vector_b(), gz_mpi_binary_head_io::gz_mpi_read_mul_charahead_b(), gz_mpi_binary_head_io::gz_mpi_read_mul_inthead_b(), gz_field_block_mpi_io_b::gz_read_field_header_mpi_b(), gz_field_block_mpi_io_b::gz_read_step_data_mpi_b(), io_param, calypso_mpi::my_rank, and gz_mpi_binary_datum_io::open_read_gz_mpi_file_b().
Referenced by parallel_ucd_io_select::sel_read_alloc_para_udt_file().
gz_read_ucd_field_file_mpi_b()
subroutine gz_ucd_field_mpi_io_b::gz_read_ucd_field_file_mpi_b (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, type(time_data), intent(inout) t_IO, type(ucd_data), intent(inout) ucd)
Definition at line 75 of file gz_ucd_field_MPI_IO_b.f90.
References mpi_ascii_data_io::close_mpi_file(), gz_mpi_binary_data_io::gz_mpi_read_2d_vector_b(), gz_mpi_binary_head_io::gz_mpi_read_mul_charahead_b(), gz_mpi_binary_head_io::gz_mpi_read_mul_inthead_b(), gz_field_block_mpi_io_b::gz_read_field_header_mpi_b(), gz_field_block_mpi_io_b::gz_read_step_data_mpi_b(), io_param, calypso_mpi::my_rank, and gz_mpi_binary_datum_io::open_read_gz_mpi_file_b().
Referenced by parallel_ucd_io_select::sel_read_parallel_udt_file().
gz_write_ucd_field_file_mpi_b()
subroutine gz_ucd_field_mpi_io_b::gz_write_ucd_field_file_mpi_b (character(len=kchara), intent(in) file_name, type(time_data), intent(in) t_IO, type(ucd_data), intent(in) ucd)
Definition at line 44 of file gz_ucd_field_MPI_IO_b.f90.
References mpi_ascii_data_io::close_mpi_file(), gz_field_block_mpi_io_b::gz_write_field_data_mpi_b(), gz_field_block_mpi_io_b::gz_write_field_time_mpi_b(), io_param, calypso_mpi::my_rank, and gz_mpi_binary_datum_io::open_write_gz_mpi_file_b().
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_file().
Variable Documentation
io_param
type(calypso_mpi_io_params), save, private gz_ucd_field_mpi_io_b::io_param private
Definition at line 36 of file gz_ucd_field_MPI_IO_b.f90.
Referenced by gz_rd_alloc_ucd_fld_file_mpi_b(), gz_read_ucd_field_file_mpi_b(), and gz_write_ucd_field_file_mpi_b().