CALYPSO: share_spectr_index_data Module Reference
share_spectr_index_data Module Reference
routines for parallel spectr data assemble
Functions/Subroutines
subroutine share_sph_rj_data (ip_org, sph_mesh)
Detailed Description
routines for parallel spectr data assemble
      subroutine share_sph_rj_data(ip_org, sph_mesh)
        type(sph_mesh_data), intent(inout) :: sph_mesh
Function/Subroutine Documentation
share_sph_rj_data()
subroutine share_spectr_index_data::share_sph_rj_data (integer(kind = kint), intent(in) ip_org, type(sph_mesh_data), intent(inout) sph_mesh)
Definition at line 31 of file share_spectr_index_data.f90.
References calypso_mpi_int::calypso_mpi_bcast_int(), calypso_mpi_int::calypso_mpi_bcast_one_int(), calypso_mpi_real::calypso_mpi_bcast_real(), transfer_to_long_integers::cast_long(), calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by assemble_sph_fields::share_org_sph_rj_data().