CALYPSO: cal_gaunt_itgs Module Reference
cal_gaunt_itgs Module Reference
Functions/Subroutines
double precision function leadki (l1, m1, l2, m2, l3, m3)
double precision function leadli (l1, m1, l2, m2, l3, m3)
double precision function, private normki (gi, m1, m2, m3)
double precision function, private normli (ei, m1, m2, m3, mm1)
Function/Subroutine Documentation
leadki()
double precision function cal_gaunt_itgs::leadki (integer(kind = kint), intent(in) l1, integer(kind = kint), intent(in) m1, integer(kind = kint), intent(in) l2, integer(kind = kint), intent(in) m2, integer(kind = kint), intent(in) l3, integer(kind = kint), intent(in) m3)
Definition at line 84 of file cal_gaunt_itgs.f90.
References normgi::gs(), m_constants::itwo, m_constants::izero, normki(), and m_constants::zero.
Referenced by interact_coriolis_rlm::cal_gaunt_coriolis_rlm().
leadli()
double precision function cal_gaunt_itgs::leadli (integer(kind = kint), intent(in) l1, integer(kind = kint), intent(in) m1, integer(kind = kint), intent(in) l2, integer(kind = kint), intent(in) m2, integer(kind = kint), intent(in) l3, integer(kind = kint), intent(in) m3)
Definition at line 126 of file cal_gaunt_itgs.f90.
References m_constants::dminus, m_constants::ione, m_constants::itwo, normli(), normei::setei(), and m_constants::zero.
Referenced by interact_coriolis_rlm::cal_gaunt_coriolis_rlm().
normki()
double precision function, private cal_gaunt_itgs::normki (real(kind = kreal), intent(in) gi, integer(kind = kint), intent(in) m1, integer(kind = kint), intent(in) m2, integer(kind = kint), intent(in) m3) private
Definition at line 169 of file cal_gaunt_itgs.f90.
References m_constants::half, m_constants::two, and m_constants::zero.
Referenced by leadki().
normli()
double precision function, private cal_gaunt_itgs::normli (real(kind = kreal), intent(in) ei, integer(kind = kint), intent(in) m1, integer(kind = kint), intent(in) m2, integer(kind = kint), intent(in) m3, integer(kind = kint), intent(in) mm1) private
Definition at line 198 of file cal_gaunt_itgs.f90.
References m_constants::half, and m_constants::zero.
Referenced by leadli().