CALYPSO: t_ctl_data_node_monitor Module Reference
t_ctl_data_node_monitor Module Reference
Control data of node monitoring.
Data Types
type node_monitor_control
Functions/Subroutines
subroutine read_monitor_data_ctl (id_control, hd_block, nmtr_ctl, c_buf)
subroutine bcast_monitor_data_ctl (nmtr_ctl)
subroutine dealloc_monitor_data_ctl (nmtr_ctl)
Variables
character(len=kchara), private hd_monitor_position = 'monitor_position_list'
character(len=kchara), private hd_monitor_node = 'monitor_node_list'
character(len=kchara), private hd_monitor_grp = 'monitor_grp_ctl'
Detailed Description
Control data of node monitoring.
      subroutine read_monitor_data_ctl                                &
     &         (id_control, hd_block, nmtr_ctl, c_buf)
      subroutine bcast_monitor_data_ctl(nmtr_ctl)
      subroutine dealloc_monitor_data_ctl(nmtr_ctl)
        type(node_monitor_control), intent(inout) :: nmtr_ctl
   --------------------------------------------------------------------
   control for monitor nodal data
  begin monitor_data_ctl
    array monitor_position_list   1
      monitor_position_list     1.038e0  0.0e0   0.0e0
    end array monitor_position_list
    array monitor_node_list   1
      monitor_node_list          2   132
    end array monitor_node_list
    array monitor_grp_ctl   1
      monitor_grp_ctl     mid_equator
    end array monitor_grp_ctl
  end  monitor_data_ctl
   --------------------------------------------------------------------
Function/Subroutine Documentation
bcast_monitor_data_ctl()
subroutine t_ctl_data_node_monitor::bcast_monitor_data_ctl (type(node_monitor_control), intent(inout) nmtr_ctl)
Definition at line 112 of file t_ctl_data_node_monitor.f90.
References bcast_control_arrays::bcast_ctl_array_c1(), bcast_control_arrays::bcast_ctl_array_i2(), bcast_control_arrays::bcast_ctl_array_r3(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by t_ctl_data_mhd::bcast_sph_mhd_ctl_data().
dealloc_monitor_data_ctl()
subroutine t_ctl_data_node_monitor::dealloc_monitor_data_ctl (type(node_monitor_control), intent(inout) nmtr_ctl)
Definition at line 130 of file t_ctl_data_node_monitor.f90.
References t_control_array_character::dealloc_control_array_chara(), t_control_array_integer2::dealloc_control_array_i2(), and t_control_array_real3::dealloc_control_array_r3().
Referenced by t_ctl_data_mhd::dealloc_sph_mhd_ctl_data().
read_monitor_data_ctl()
subroutine t_ctl_data_node_monitor::read_monitor_data_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(node_monitor_control), intent(inout) nmtr_ctl, type(buffer_for_control), intent(inout) c_buf)
Definition at line 80 of file t_ctl_data_node_monitor.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_monitor_grp, hd_monitor_node, hd_monitor_position, t_read_control_elements::load_one_line_from_control(), t_control_array_character::read_control_array_c1(), t_control_array_integer2::read_control_array_i2(), and t_control_array_real3::read_control_array_r3().
Referenced by t_ctl_data_mhd::read_sph_mhd_ctl_noviz(), and t_ctl_data_mhd::read_sph_mhd_ctl_w_psf().
Variable Documentation
hd_monitor_grp
character(len=kchara), private t_ctl_data_node_monitor::hd_monitor_grp = 'monitor_grp_ctl' private
Definition at line 70 of file t_ctl_data_node_monitor.f90.
Referenced by read_monitor_data_ctl().
hd_monitor_node
character(len=kchara), private t_ctl_data_node_monitor::hd_monitor_node = 'monitor_node_list' private
Definition at line 69 of file t_ctl_data_node_monitor.f90.
Referenced by read_monitor_data_ctl().
hd_monitor_position
character(len=kchara), private t_ctl_data_node_monitor::hd_monitor_position = 'monitor_position_list' private
Definition at line 67 of file t_ctl_data_node_monitor.f90.
Referenced by read_monitor_data_ctl().