CALYPSO: t_para_double_numbering Module Reference
t_para_double_numbering Module Reference
Data for merged UCD file output.
Data Types
type parallel_double_numbering
Structure of double numbering.
Functions/Subroutines
subroutine alloc_double_numbering (numnod, dbl_id)
subroutine dealloc_double_numbering (dbl_id)
subroutine set_para_double_numbering (internal_node, nod_comm, dbl_id)
subroutine set_para_ele_double_numbering (internal_node, ele_comm, ele, dbl_id)
Detailed Description
Data for merged UCD file output.
      subroutine alloc_double_numbering(numnod, dbl_id)
      subroutine dealloc_double_numbering(dbl_id)
        type(parallel_double_numbering), intent(inout) :: dbl_id
      subroutine set_para_double_numbering                            &
     &         (internal_node, nod_comm, dbl_id)
        type(communication_table), intent(in) :: nod_comm
        type(parallel_double_numbering), intent(inout) :: dbl_id
      subroutine set_para_ele_double_numbering                        &
     &         (internal_node, ele_comm, ele, dbl_id)
        type(communication_table), intent(in) :: ele_comm
        type(element_data), intent(in) :: ele
        type(parallel_double_numbering), intent(inout) :: dbl_id
Function/Subroutine Documentation
alloc_double_numbering()
subroutine t_para_double_numbering::alloc_double_numbering (integer(kind = kint), intent(in) numnod, type(parallel_double_numbering), intent(inout) dbl_id)
Definition at line 50 of file t_para_double_numbering.f90.
Referenced by merged_udt_vtk_file_io::init_merged_ucd().
dealloc_double_numbering()
subroutine t_para_double_numbering::dealloc_double_numbering (type(parallel_double_numbering), intent(inout) dbl_id)
Definition at line 68 of file t_para_double_numbering.f90.
Referenced by merged_udt_vtk_file_io::init_merged_ucd().
set_para_double_numbering()
subroutine t_para_double_numbering::set_para_double_numbering (integer(kind = kint), intent(in) internal_node, type(communication_table), intent(in) nod_comm, type(parallel_double_numbering), intent(inout) dbl_id)
Definition at line 80 of file t_para_double_numbering.f90.
References calypso_mpi::my_rank, and solver_sr_type::solver_send_recv_int_type().
Referenced by merged_udt_vtk_file_io::init_merged_ucd().
set_para_ele_double_numbering()
subroutine t_para_double_numbering::set_para_ele_double_numbering (integer(kind = kint), intent(in) internal_node, type(communication_table), intent(in) ele_comm, type(element_data), intent(in) ele, type(parallel_double_numbering), intent(inout) dbl_id)
Definition at line 115 of file t_para_double_numbering.f90.
References calypso_mpi::my_rank, and solver_sr_type::solver_send_recv_int_type().