CALYPSO: set_coefs_of_sections Module Reference
set_coefs_of_sections Module Reference
Construct equation for cross section.
Functions/Subroutines
subroutine s_set_coefs_of_sections (psf_def_c, id_section_method, const_psf, ierr)
real(kind=kreal) function side_of_plane (const_psf, xx)
subroutine cal_normal_of_plane (const_psf, xx, normal)
integer(kind=kint) function num_label_psf_def_type ()
integer(kind=kint) function num_label_psf_def_type_grp ()
subroutine set_label_psf_def_type_grp (names)
Variables
character(len=kchara), parameter cflag_eq = 'equation'
character(len=kchara), parameter, private cflag_pln = 'plane'
character(len=kchara), parameter, private cflag_sph = 'sphere'
character(len=kchara), parameter, private cflag_elp = 'ellipsoid'
character(len=kchara), parameter, private cflag_hyp = 'hyperboloid'
character(len=kchara), parameter, private cflag_prb = 'paraboloid'
character(len=kchara), parameter cflag_grp = 'group'
integer(kind=kint), parameter n_label_psf_def_type = 6
integer(kind=kint), parameter n_label_psf_def_type_grp = 7
Detailed Description
Construct equation for cross section.
      subroutine s_set_coefs_of_sections                              &
     &         (psf_c, id_section_method, const_psf, ierr)
        type(psf_define_ctl), intent(in) :: psf_def_c
        real(kind = kreal) function side_of_plane(const_psf, xx)
      subroutine cal_normal_of_plane(const_psf, xx, normal)
      integer(kind = kint) function num_label_psf_def_type()
      integer(kind = kint) function num_label_psf_def_type_grp()
      subroutine set_label_psf_def_type_grp(names)
Function/Subroutine Documentation
cal_normal_of_plane()
subroutine set_coefs_of_sections::cal_normal_of_plane (real(kind = kreal), dimension(10), intent(in) const_psf, real(kind = kreal), dimension(3), intent(in) xx, real(kind = kreal), dimension(3), intent(inout) normal)
Definition at line 126 of file set_coefs_of_sections.f90.
References m_constants::two.
num_label_psf_def_type()
integer(kind = kint) function set_coefs_of_sections::num_label_psf_def_type
Definition at line 154 of file set_coefs_of_sections.f90.
References n_label_psf_def_type.
num_label_psf_def_type_grp()
integer(kind = kint) function set_coefs_of_sections::num_label_psf_def_type_grp
Definition at line 161 of file set_coefs_of_sections.f90.
References n_label_psf_def_type_grp.
s_set_coefs_of_sections()
subroutine set_coefs_of_sections::s_set_coefs_of_sections (type(psf_define_ctl), intent(in) psf_def_c, integer(kind = kint), intent(inout) id_section_method, real(kind = kreal), dimension(10), intent(inout) const_psf, integer(kind = kint), intent(inout) ierr)
Definition at line 48 of file set_coefs_of_sections.f90.
References cflag_elp, cflag_eq, cflag_hyp, cflag_pln, cflag_prb, cflag_sph, m_error_ids::ierr_viz, set_cross_section_coefs::set_coefs_4_ellipsode(), set_cross_section_coefs::set_coefs_4_hyperboloide(), set_cross_section_coefs::set_coefs_4_parabolic(), set_cross_section_coefs::set_coefs_4_plane(), m_section_coef_flags::set_coefs_4_psf(), and set_cross_section_coefs::set_coefs_4_sphere().
Referenced by t_control_params_4_psf::set_control_psf_define().
set_label_psf_def_type_grp()
subroutine set_coefs_of_sections::set_label_psf_def_type_grp (character(len = kchara), dimension(n_label_psf_def_type_grp), intent(inout) names)
Definition at line 168 of file set_coefs_of_sections.f90.
References cflag_elp, cflag_eq, cflag_grp, cflag_hyp, cflag_pln, cflag_prb, cflag_sph, and t_read_control_elements::set_control_labels().
side_of_plane()
real(kind = kreal) function set_coefs_of_sections::side_of_plane (real(kind = kreal), dimension(10), intent(in) const_psf, real(kind = kreal), dimension(3), intent(in) xx)
Definition at line 105 of file set_coefs_of_sections.f90.
Variable Documentation
cflag_elp
character(len = kchara), parameter, private set_coefs_of_sections::cflag_elp = 'ellipsoid' private
Definition at line 31 of file set_coefs_of_sections.f90.
Referenced by s_set_coefs_of_sections(), and set_label_psf_def_type_grp().
cflag_eq
character(len = kchara), parameter set_coefs_of_sections::cflag_eq = 'equation'
Definition at line 28 of file set_coefs_of_sections.f90.
Referenced by s_set_coefs_of_sections(), and set_label_psf_def_type_grp().
cflag_grp
character(len = kchara), parameter set_coefs_of_sections::cflag_grp = 'group'
Definition at line 34 of file set_coefs_of_sections.f90.
Referenced by t_control_params_4_psf::set_control_psf_define(), and set_label_psf_def_type_grp().
cflag_hyp
character(len = kchara), parameter, private set_coefs_of_sections::cflag_hyp = 'hyperboloid' private
Definition at line 32 of file set_coefs_of_sections.f90.
Referenced by s_set_coefs_of_sections(), and set_label_psf_def_type_grp().
cflag_pln
character(len = kchara), parameter, private set_coefs_of_sections::cflag_pln = 'plane' private
Definition at line 29 of file set_coefs_of_sections.f90.
Referenced by s_set_coefs_of_sections(), and set_label_psf_def_type_grp().
cflag_prb
character(len = kchara), parameter, private set_coefs_of_sections::cflag_prb = 'paraboloid' private
Definition at line 33 of file set_coefs_of_sections.f90.
Referenced by s_set_coefs_of_sections(), and set_label_psf_def_type_grp().
cflag_sph
character(len = kchara), parameter, private set_coefs_of_sections::cflag_sph = 'sphere' private
Definition at line 30 of file set_coefs_of_sections.f90.
Referenced by s_set_coefs_of_sections(), and set_label_psf_def_type_grp().
n_label_psf_def_type
integer(kind = kint), parameter set_coefs_of_sections::n_label_psf_def_type = 6
Definition at line 36 of file set_coefs_of_sections.f90.
Referenced by num_label_psf_def_type().
n_label_psf_def_type_grp
integer(kind = kint), parameter set_coefs_of_sections::n_label_psf_def_type_grp = 7
Definition at line 37 of file set_coefs_of_sections.f90.
Referenced by num_label_psf_def_type_grp().