CALYPSO: mesh_file_io_b Module Reference
mesh_file_io_b Module Reference
Mesh file IO for binary format.
Functions/Subroutines
subroutine read_mesh_file_b (id_rank, file_name, mesh_IO, group_IO, ierr)
subroutine read_mesh_geometry_b (id_rank, file_name, mesh_IO, ierr)
subroutine read_node_size_b (id_rank, file_name, mesh_IO, ierr)
subroutine read_geometry_size_b (id_rank, file_name, mesh_IO, ierr)
subroutine write_mesh_file_b (id_rank, file_name, mesh_IO, group_IO, ierr)
Variables
integer(kind=kint), parameter, private id_read_mesh = 21
integer(kind=kint), parameter, private id_write_mesh = 22
type(binary_io_buffer), private bbuf_mesh
Detailed Description
Mesh file IO for binary format.
      subroutine read_mesh_file_b                                     &
     &         (id_rank, file_name, mesh_IO, group_IO, ierr)
        type(mesh_geometry), intent(inout) :: mesh_IO
        type(mesh_groups), intent(inout) ::   group_IO
      subroutine read_mesh_geometry_b                                 &
     &         (id_rank, file_name, mesh_IO, ierr)
      subroutine read_node_size_b                                     &
     &         (id_rank, file_name, mesh_IO, ierr)
      subroutine read_geometry_size_b                                 &
     &         (id_rank, file_name, mesh_IO, ierr)
        type(mesh_geometry), intent(inout) :: mesh_IO
      subroutine write_mesh_file_b                                    &
     &         (id_rank, file_name, mesh_IO, group_IO, ierr)
        type(mesh_geometry), intent(in) :: mesh_IO
        type(mesh_groups), intent(in) ::   group_IO
Function/Subroutine Documentation
read_geometry_size_b()
subroutine mesh_file_io_b::read_geometry_size_b (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(inout) mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 135 of file mesh_file_IO_b.f90.
References bbuf_mesh, binary_io::close_binary_file(), m_machine_parameter::i_debug, id_read_mesh, binary_io::open_read_binary_file(), and mesh_data_io_b::read_num_node_ele_b().
Referenced by mesh_io_select::sel_read_geometry_size().
read_mesh_file_b()
subroutine mesh_file_io_b::read_mesh_file_b (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(inout) mesh_IO, type(mesh_groups), intent(inout) group_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 52 of file mesh_file_IO_b.f90.
References bbuf_mesh, binary_io::close_binary_file(), m_machine_parameter::i_debug, id_read_mesh, binary_io::open_read_binary_file(), mesh_data_io_b::read_geometry_data_b(), and mesh_data_io_b::read_mesh_groups_b().
Referenced by mesh_io_select::sel_read_mesh().
read_mesh_geometry_b()
subroutine mesh_file_io_b::read_mesh_geometry_b (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(inout) mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 83 of file mesh_file_IO_b.f90.
References bbuf_mesh, binary_io::close_binary_file(), m_machine_parameter::i_debug, id_read_mesh, binary_io::open_read_binary_file(), and mesh_data_io_b::read_geometry_data_b().
Referenced by mesh_io_select::sel_read_mesh_geometry().
read_node_size_b()
subroutine mesh_file_io_b::read_node_size_b (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(inout) mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 109 of file mesh_file_IO_b.f90.
References bbuf_mesh, binary_io::close_binary_file(), m_machine_parameter::i_debug, id_read_mesh, binary_io::open_read_binary_file(), and mesh_data_io_b::read_num_node_b().
Referenced by mesh_io_select::sel_read_node_size().
write_mesh_file_b()
subroutine mesh_file_io_b::write_mesh_file_b (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(in) mesh_IO, type(mesh_groups), intent(in) group_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 162 of file mesh_file_IO_b.f90.
References bbuf_mesh, binary_io::close_binary_file(), m_machine_parameter::i_debug, id_write_mesh, binary_io::open_write_binary_file(), mesh_data_io_b::write_geometry_data_b(), and mesh_data_io_b::write_mesh_groups_b().
Referenced by mesh_io_select::sel_write_mesh_file().
Variable Documentation
bbuf_mesh
type(binary_io_buffer), private mesh_file_io_b::bbuf_mesh private
Definition at line 43 of file mesh_file_IO_b.f90.
Referenced by read_geometry_size_b(), read_mesh_file_b(), read_mesh_geometry_b(), read_node_size_b(), and write_mesh_file_b().
id_read_mesh
integer(kind = kint), parameter, private mesh_file_io_b::id_read_mesh = 21 private
Definition at line 41 of file mesh_file_IO_b.f90.
Referenced by read_geometry_size_b(), read_mesh_file_b(), read_mesh_geometry_b(), and read_node_size_b().
id_write_mesh
integer(kind = kint), parameter, private mesh_file_io_b::id_write_mesh = 22 private
Definition at line 42 of file mesh_file_IO_b.f90.
Referenced by write_mesh_file_b().