CALYPSO: set_stack_4_sph_groups Module Reference
set_stack_4_sph_groups Module Reference
Make group informations for spherical shell model.
Functions/Subroutines
subroutine set_stack_rtp_radial_grp (sph_param, sph_rtp, r_layer_grp, added_radial_grp, radial_rtp_grp)
subroutine set_stack_rj_radial_grp (sph_param, sph_rj, added_radial_grp, radial_rj_grp)
subroutine set_stack_rtp_meridional_grp (sph_rtp, med_layer_grp, theta_rtp_grp)
subroutine set_stack_rj_spectr_grp (sph_rj, sphere_rj_grp)
subroutine, private set_stack_sph_grp_by_list (icou, nlayer_st, nlayer_ed, nidx, idx_gl_1d, grp_name, num_grp, istack_grp, name_grp)
subroutine, private set_stack_sph_grp_direct (icou, nlayer_st, nlayer_ed, ist_domain, ied_domain, grp_name, num_grp, istack_grp, name_grp)
Variables
character(len=kchara), parameter, private name_mid = 'Mid_OC'
character(len=kchara), parameter name_ed = 'Outmost_of_Shell'
character(len=kchara), parameter, private name_y00 = 'Y_0_0'
character(len=kchara), parameter, private name_y10 = 'Y_1_0'
character(len=kchara), parameter, private name_y11s = 'Y_1_1s'
character(len=kchara), parameter, private name_y11c = 'Y_1_1c'
Detailed Description
Make group informations for spherical shell model.
      subroutine set_stack_rtp_radial_grp(sph_param, sph_rtp,         &
     &          r_layer_grp, added_radial_grp, radial_rtp_grp)
      subroutine set_stack_rtp_meridional_grp                         &
     &         (sph_rtp, med_layer_grp, theta_rtp_grp)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(layering_group_list), intent(in) :: med_layer_grp
        type(group_data), intent(inout) :: theta_rtp_grp
      subroutine set_stack_rj_radial_grp                              &
     &        (sph_param, sph_rj, added_radial_grp, radial_rj_grp)
      subroutine set_stack_rj_spectr_grp(sph_rj, sphere_rj_grp)
        type(sph_shell_parameters), intent(in) :: sph_param
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_rj_grid), intent(in) :: sph_rj
        type(layering_group_list), intent(in) :: added_radial_grp
        type(group_data), intent(inout) :: radial_rtp_grp
        type(group_data), intent(inout) :: radial_rj_grp
        type(group_data), intent(inout) :: sphere_rj_grp
        type(group_data), intent(inout) :: theta_rtp_grp
Function/Subroutine Documentation
set_stack_rj_radial_grp()
subroutine set_stack_4_sph_groups::set_stack_rj_radial_grp (type(sph_shell_parameters), intent(in) sph_param, type(sph_rj_grid), intent(in) sph_rj, type(layering_group_list), intent(in) added_radial_grp, type(group_data), intent(inout) radial_rj_grp)
Definition at line 144 of file set_stack_4_sph_groups.f90.
References t_spheric_parameter::cmb_nod_grp_name, t_spheric_parameter::ctr_nod_grp_name, t_spheric_parameter::ic_ele_grp_name, t_spheric_parameter::icb_nod_grp_name, name_ed, name_mid, t_spheric_parameter::oc_ele_grp_name, and set_stack_sph_grp_direct().
Referenced by set_sph_groups::set_rj_radial_grp().
set_stack_rj_spectr_grp()
subroutine set_stack_4_sph_groups::set_stack_rj_spectr_grp (type(sph_rj_grid), intent(in) sph_rj, type(group_data), intent(inout) sphere_rj_grp)
Definition at line 243 of file set_stack_4_sph_groups.f90.
References m_constants::ione, m_constants::ithree, m_constants::itwo, m_constants::izero, name_y00, name_y10, name_y11c, name_y11s, and set_stack_sph_grp_direct().
Referenced by set_sph_groups::set_rj_spectr_grp().
set_stack_rtp_meridional_grp()
subroutine set_stack_4_sph_groups::set_stack_rtp_meridional_grp (type(sph_rtp_grid), intent(in) sph_rtp, type(layering_group_list), intent(in) med_layer_grp, type(group_data), intent(inout) theta_rtp_grp)
Definition at line 218 of file set_stack_4_sph_groups.f90.
References set_stack_sph_grp_direct().
Referenced by set_sph_groups::set_rtp_meridional_grp().
set_stack_rtp_radial_grp()
subroutine set_stack_4_sph_groups::set_stack_rtp_radial_grp (type(sph_shell_parameters), intent(in) sph_param, type(sph_rtp_grid), intent(in) sph_rtp, type(layering_group_list), intent(in) r_layer_grp, type(layering_group_list), intent(in) added_radial_grp, type(group_data), intent(inout) radial_rtp_grp)
Definition at line 60 of file set_stack_4_sph_groups.f90.
References t_spheric_parameter::cmb_nod_grp_name, t_spheric_parameter::ctr_nod_grp_name, t_spheric_parameter::ic_ele_grp_name, t_spheric_parameter::icb_nod_grp_name, name_ed, name_mid, t_spheric_parameter::oc_ele_grp_name, and set_stack_sph_grp_by_list().
Referenced by set_sph_groups::set_rtp_radial_grp().
set_stack_sph_grp_by_list()
subroutine, private set_stack_4_sph_groups::set_stack_sph_grp_by_list (integer(kind = kint), intent(inout) icou, integer(kind = kint), intent(in) nlayer_st, integer(kind = kint), intent(in) nlayer_ed, integer(kind = kint), intent(in) nidx, integer(kind = kint), dimension(nidx), intent(in) idx_gl_1d, character(len = kchara), intent(in) grp_name, integer(kind = kint), intent(in) num_grp, integer(kind = kint), dimension(0:num_grp), intent(inout) istack_grp, character(len = kchara), dimension(num_grp), intent(inout) name_grp) private
Definition at line 279 of file set_stack_4_sph_groups.f90.
Referenced by set_stack_rtp_radial_grp().
set_stack_sph_grp_direct()
subroutine, private set_stack_4_sph_groups::set_stack_sph_grp_direct (integer(kind = kint), intent(inout) icou, integer(kind = kint), intent(in) nlayer_st, integer(kind = kint), intent(in) nlayer_ed, integer(kind = kint), intent(in) ist_domain, integer(kind = kint), intent(in) ied_domain, character(len = kchara), intent(in) grp_name, integer(kind = kint), intent(in) num_grp, integer(kind = kint), dimension(0:num_grp), intent(inout) istack_grp, character(len = kchara), dimension(num_grp), intent(inout) name_grp) private
Definition at line 311 of file set_stack_4_sph_groups.f90.
Referenced by set_stack_rj_radial_grp(), set_stack_rj_spectr_grp(), and set_stack_rtp_meridional_grp().
Variable Documentation
name_ed
character(len = kchara), parameter set_stack_4_sph_groups::name_ed = 'Outmost_of_Shell'
Definition at line 43 of file set_stack_4_sph_groups.f90.
Referenced by set_stack_rj_radial_grp(), and set_stack_rtp_radial_grp().
name_mid
character(len = kchara), parameter, private set_stack_4_sph_groups::name_mid = 'Mid_OC' private
Definition at line 42 of file set_stack_4_sph_groups.f90.
Referenced by set_stack_rj_radial_grp(), and set_stack_rtp_radial_grp().
name_y00
character(len = kchara), parameter, private set_stack_4_sph_groups::name_y00 = 'Y_0_0' private
Definition at line 45 of file set_stack_4_sph_groups.f90.
Referenced by set_stack_rj_spectr_grp().
name_y10
character(len = kchara), parameter, private set_stack_4_sph_groups::name_y10 = 'Y_1_0' private
Definition at line 46 of file set_stack_4_sph_groups.f90.
Referenced by set_stack_rj_spectr_grp().
name_y11c
character(len = kchara), parameter, private set_stack_4_sph_groups::name_y11c = 'Y_1_1c' private
Definition at line 48 of file set_stack_4_sph_groups.f90.
Referenced by set_stack_rj_spectr_grp().
name_y11s
character(len = kchara), parameter, private set_stack_4_sph_groups::name_y11s = 'Y_1_1s' private
Definition at line 47 of file set_stack_4_sph_groups.f90.
Referenced by set_stack_rj_spectr_grp().