CALYPSO: t_control_array_character2 Module Reference
t_control_array_character2 Module Reference
Data Types
type ctl_array_c2
Structure for three charactors control array.
type read_chara2_item
structure of control item with three characters
Functions/Subroutines
subroutine read_character2_ctl_type (c_buf, label, chara2_item)
subroutine write_character2_ctl_type (id_file, level, label, chara2_item)
subroutine copy_character2_ctl (org_c2, new_c2)
subroutine alloc_control_array_c2 (array_c2)
subroutine dealloc_control_array_c2 (array_c2)
subroutine read_control_array_c2 (id_control, label, array_c2, c_buf)
subroutine write_control_array_c2 (id_control, level, label, array_c2)
subroutine append_control_array_c2 (read_c2, array_c2)
subroutine dup_control_array_c2 (org_c2, tgt_c2)
subroutine copy_control_array_c2 (num_copy, org_c2, tgt_c2)
subroutine append_control_item_c2 (read_c2, array_c2)
Function/Subroutine Documentation
alloc_control_array_c2()
subroutine t_control_array_character2::alloc_control_array_c2 (type(ctl_array_c2), intent(inout) array_c2)
Definition at line 139 of file t_control_array_character2.f90.
Referenced by append_control_array_c2(), bcast_control_arrays::bcast_ctl_array_c2(), dup_control_array_c2(), and read_control_array_c2().
append_control_array_c2()
subroutine t_control_array_character2::append_control_array_c2 (type(read_chara2_item), intent(inout) read_c2, type(ctl_array_c2), intent(inout) array_c2)
Definition at line 232 of file t_control_array_character2.f90.
References alloc_control_array_c2(), append_control_item_c2(), copy_control_array_c2(), and dealloc_control_array_c2().
Referenced by read_control_array_c2().
append_control_item_c2()
subroutine t_control_array_character2::append_control_item_c2 (type(read_chara2_item), intent(in) read_c2, type(ctl_array_c2), intent(inout) array_c2)
Definition at line 287 of file t_control_array_character2.f90.
Referenced by append_control_array_c2().
copy_character2_ctl()
subroutine t_control_array_character2::copy_character2_ctl (type(read_chara2_item), intent(in) org_c2, type(read_chara2_item), intent(inout) new_c2)
Definition at line 125 of file t_control_array_character2.f90.
copy_control_array_c2()
subroutine t_control_array_character2::copy_control_array_c2 (integer(kind = kint), intent(in) num_copy, type(ctl_array_c2), intent(in) org_c2, type(ctl_array_c2), intent(inout) tgt_c2)
Definition at line 271 of file t_control_array_character2.f90.
Referenced by append_control_array_c2(), and dup_control_array_c2().
dealloc_control_array_c2()
subroutine t_control_array_character2::dealloc_control_array_c2 (type(ctl_array_c2), intent(inout) array_c2)
Definition at line 151 of file t_control_array_character2.f90.
Referenced by append_control_array_c2(), and t_control_data_4_fld_on_psf::dealloc_fld_on_psf_control().
dup_control_array_c2()
subroutine t_control_array_character2::dup_control_array_c2 (type(ctl_array_c2), intent(in) org_c2, type(ctl_array_c2), intent(inout) tgt_c2)
Definition at line 257 of file t_control_array_character2.f90.
References alloc_control_array_c2(), and copy_control_array_c2().
Referenced by t_control_data_4_fld_on_psf::dup_fld_on_psf_control().
read_character2_ctl_type()
subroutine t_control_array_character2::read_character2_ctl_type (type(buffer_for_control), intent(in) c_buf, character(len=kchara), intent(in) label, type(read_chara2_item), intent(inout) chara2_item)
Definition at line 76 of file t_control_array_character2.f90.
References m_machine_parameter::iflag_debug.
Referenced by read_control_array_c2().
read_control_array_c2()
subroutine t_control_array_character2::read_control_array_c2 (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) label, type(ctl_array_c2), intent(inout) array_c2, type(buffer_for_control), intent(inout) c_buf)
Definition at line 165 of file t_control_array_character2.f90.
References alloc_control_array_c2(), append_control_array_c2(), t_read_control_elements::check_array_flag(), t_read_control_elements::check_end_array_flag(), t_read_control_elements::load_one_line_from_control(), and read_character2_ctl_type().
Referenced by t_control_data_4_fld_on_psf::read_fld_on_psf_control().
write_character2_ctl_type()
subroutine t_control_array_character2::write_character2_ctl_type (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, type(read_chara2_item), intent(in) chara2_item)
Definition at line 100 of file t_control_array_character2.f90.
References m_constants::ione, skip_comment_f::max_len_of_charaarray(), and write_control_elements::write_character2_ctl_item().
write_control_array_c2()
subroutine t_control_array_character2::write_control_array_c2 (integer(kind = kint), intent(in) id_control, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, type(ctl_array_c2), intent(in) array_c2)
Definition at line 199 of file t_control_array_character2.f90.
References skip_comment_f::max_len_of_charaarray(), write_control_elements::write_array_flag_for_ctl(), write_control_elements::write_character2_ctl_item(), and write_control_elements::write_end_array_flag_for_ctl().