CALYPSO: set_legendre_matrices Module Reference
set_legendre_matrices Module Reference
set legendre polynomials into matrices
Functions/Subroutines
subroutine set_trans_legendre_rtm (nth_rtm, jmax_rlm, P_rtm, dPdt_rtm, P_jl, dPdt_jl)
subroutine set_sym_legendre_stack (mphi_rtm, lstack_rlm, lstack_even_rlm)
subroutine set_symmetric_legendre_lj (nth_rtm, mphi_rtm, jmax_rlm, nth_hemi_rtm, lstack_rlm, lstack_even_rlm, P_rtm, dPdt_rtm, Ps_rtm, dPsdt_rtm)
subroutine set_symmetric_legendre_jl (nth_rtm, mphi_rtm, jmax_rlm, nth_hemi_rtm, lstack_rlm, lstack_even_rlm, P_rtm, dPdt_rtm, Ps_jl, dPsdt_jl)
Detailed Description
set legendre polynomials into matrices
      subroutine set_trans_legendre_rtm(nth_rtm, jmax_rlm,            &
     &          P_rtm, dPdt_rtm, P_jl, dPdt_jl)
      subroutine set_sym_legendre_stack                               &
     &         (mphi_rtm, lstack_rlm, lstack_even_rlm)
      subroutine set_symmetric_legendre_lj(nth_rtm, mphi_rtm,         &
     &           jmax_rlm, nth_hemi_rtm, lstack_rlm, lstack_even_rlm, &
     &           P_rtm, dPdt_rtm, Ps_rtm, dPsdt_rtm)
      subroutine set_symmetric_legendre_jl(nth_rtm, mphi_rtm,         &
     &           jmax_rlm, nth_hemi_rtm, lstack_rlm, lstack_even_rlm, &
     &           P_rtm, dPdt_rtm, Ps_jl, dPsdt_jl)
Function/Subroutine Documentation
set_sym_legendre_stack()
subroutine set_legendre_matrices::set_sym_legendre_stack (integer(kind = kint), intent(in) mphi_rtm, integer(kind = kint), dimension(0:mphi_rtm), intent(in) lstack_rlm, integer(kind = kint), dimension(0:mphi_rtm), intent(inout) lstack_even_rlm)
Definition at line 64 of file set_legendre_matrices.f90.
Referenced by init_sph_trans::initialize_legendre_trans().
set_symmetric_legendre_jl()
subroutine set_legendre_matrices::set_symmetric_legendre_jl (integer(kind = kint), intent(in) nth_rtm, integer(kind = kint), intent(in) mphi_rtm, integer(kind = kint), intent(in) jmax_rlm, integer(kind = kint), intent(in) nth_hemi_rtm, integer(kind = kint), dimension(0:mphi_rtm), intent(in) lstack_rlm, integer(kind = kint), dimension(0:mphi_rtm), intent(in) lstack_even_rlm, real(kind= kreal), dimension(nth_rtm,jmax_rlm), intent(in) P_rtm, real(kind= kreal), dimension(nth_rtm,jmax_rlm), intent(in) dPdt_rtm, real(kind= kreal), dimension(jmax_rlm,nth_hemi_rtm), intent(inout) Ps_jl, real(kind= kreal), dimension(jmax_rlm,nth_hemi_rtm), intent(inout) dPsdt_jl)
Definition at line 134 of file set_legendre_matrices.f90.
Referenced by t_legendre_work_sym_matmul::const_symmetric_legendres().
set_symmetric_legendre_lj()
subroutine set_legendre_matrices::set_symmetric_legendre_lj (integer(kind = kint), intent(in) nth_rtm, integer(kind = kint), intent(in) mphi_rtm, integer(kind = kint), intent(in) jmax_rlm, integer(kind = kint), intent(in) nth_hemi_rtm, integer(kind = kint), dimension(0:mphi_rtm), intent(in) lstack_rlm, integer(kind = kint), dimension(0:mphi_rtm), intent(in) lstack_even_rlm, real(kind= kreal), dimension(nth_rtm,jmax_rlm), intent(in) P_rtm, real(kind= kreal), dimension(nth_rtm,jmax_rlm), intent(in) dPdt_rtm, real(kind= kreal), dimension(nth_hemi_rtm,jmax_rlm), intent(inout) Ps_rtm, real(kind= kreal), dimension(nth_hemi_rtm,jmax_rlm), intent(inout) dPsdt_rtm)
Definition at line 86 of file set_legendre_matrices.f90.
Referenced by t_leg_trans_sym_matmul_big::const_symmetric_legendre_lj(), and t_legendre_work_sym_matmul::const_symmetric_legendres().
set_trans_legendre_rtm()
subroutine set_legendre_matrices::set_trans_legendre_rtm (integer(kind = kint), intent(in) nth_rtm, integer(kind = kint), intent(in) jmax_rlm, real(kind= kreal), dimension(nth_rtm,jmax_rlm), intent(in) P_rtm, real(kind= kreal), dimension(nth_rtm,jmax_rlm), intent(in) dPdt_rtm, real(kind= kreal), dimension(jmax_rlm,nth_rtm), intent(inout) P_jl, real(kind= kreal), dimension(jmax_rlm,nth_rtm), intent(inout) dPdt_jl)
Definition at line 36 of file set_legendre_matrices.f90.
Referenced by init_sph_trans::init_legendre_rtm().