CALYPSO: gz_mpi_position_io Module Reference
gz_mpi_position_io Module Reference
Mesh file IO for gxipped format.
Functions/Subroutines
subroutine gz_mpi_read_radial_position (IO_param, nnod, id_r_global, rr)
subroutine gz_mpi_read_node_position (IO_param, nnod64, numdir, id_global, xx)
subroutine gz_mpi_write_radial_position (IO_param, nnod, id_r_global, rr)
subroutine gz_mpi_write_node_position (IO_param, nnod64, numdir, id_global, xx)
Variables
type(buffer_4_gzip), private zbuf
Detailed Description
Mesh file IO for gxipped format.
      subroutine gz_mpi_read_radial_position                          &
     &         (IO_param, nnod64, id_global, rr)
      subroutine gz_mpi_read_node_position                            &
     &         (IO_param, nnod, numdir, id_global, xx)
      subroutine gz_mpi_write_radial_position                         &
     &         (IO_param, nnod64, id_global, rr)
      subroutine gz_mpi_write_node_position                           &
     &         (IO_param, nnod, numdir, id_global, xx)
Function/Subroutine Documentation
gz_mpi_read_node_position()
subroutine gz_mpi_position_io::gz_mpi_read_node_position (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint_gl), intent(in) nnod64, integer(kind = kint), intent(in) numdir, integer(kind = kint_gl), dimension(nnod64), intent(inout) id_global, real(kind=kreal), dimension(nnod64, numdir), intent(inout) xx)
Definition at line 68 of file gz_MPI_position_IO.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), gz_mpi_ascii_data_io::gz_mpi_read_charahead(), zlib_convert_ascii_vector::infleate_node_position(), and gz_mpi_domain_data_io::zbuf.
Referenced by gz_mpi_node_geometry_io::gz_mpi_read_geometry_info(), and gz_mpi_read_radial_position().
gz_mpi_read_radial_position()
subroutine gz_mpi_position_io::gz_mpi_read_radial_position (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint), intent(in) nnod, integer(kind = kint), dimension(nnod), intent(inout) id_r_global, real(kind = kreal), dimension(nnod), intent(inout) rr)
Definition at line 42 of file gz_MPI_position_IO.f90.
References gz_mpi_read_node_position(), and m_constants::ione.
Referenced by gz_mpi_sph_gl_1d_idx_io::gz_mpi_read_rj_gl_1d_table(), and gz_mpi_sph_gl_1d_idx_io::gz_mpi_read_rtp_gl_1d_table().
gz_mpi_write_node_position()
subroutine gz_mpi_position_io::gz_mpi_write_node_position (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint_gl), intent(in) nnod64, integer(kind = kint), intent(in) numdir, integer(kind = kint_gl), dimension(nnod64), intent(in) id_global, real(kind = kreal), dimension(nnod64, numdir), intent(in) xx)
Definition at line 132 of file gz_MPI_position_IO.f90.
References t_buffer_4_gzip::dealloc_zip_buffer(), zlib_convert_ascii_vector::defleate_node_position(), gz_mpi_ascii_data_io::gz_mpi_write_stack_over_domain(), and gz_mpi_domain_data_io::zbuf.
Referenced by gz_mpi_node_geometry_io::gz_mpi_write_geometry_info(), and gz_mpi_write_radial_position().
gz_mpi_write_radial_position()
subroutine gz_mpi_position_io::gz_mpi_write_radial_position (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint), intent(in) nnod, integer(kind = kint), dimension(nnod), intent(in) id_r_global, real(kind = kreal), dimension(nnod), intent(in) rr)
Definition at line 107 of file gz_MPI_position_IO.f90.
References gz_mpi_write_node_position(), and m_constants::ione.
Referenced by gz_mpi_sph_gl_1d_idx_io::gz_mpi_write_rj_gl_1d_table(), and gz_mpi_sph_gl_1d_idx_io::gz_mpi_write_rtp_gl_1d_table().
Variable Documentation
zbuf
type(buffer_4_gzip), private gz_mpi_position_io::zbuf private
Definition at line 34 of file gz_MPI_position_IO.f90.