CALYPSO: m_component_flags Module Reference
m_component_flags Module Reference
Functions/Subroutines
integer(kind=kint) function num_flag_scalar_comp ()
integer(kind=kint) function num_flag_vector_comp ()
integer(kind=kint) function num_flag_sym_tensor_comp ()
integer(kind=kint) function num_flag_asym_tensor_comp ()
subroutine set_flag_scalar_comp (n_comps, names, maths)
subroutine set_flag_vector_comp (n_comps, names, maths)
subroutine set_flag_sym_tensor_comp (n_comps, names, maths)
subroutine set_flag_asym_tensor_comp (n_comps, names, maths)
Variables
integer(kind=kint), parameter, private ntype_scalar = 1
integer(kind=kint), parameter, private ntype_vector = 11
integer(kind=kint), parameter, private ntype_tensor = 22
integer(kind=kint), parameter, private ntype_as_tsr = 13
type(field_def), parameter scalar = field_def(n_comp = n_scalar, name = 'scalar', math = '$ S $')
Field label for scalar \(S \).
type(field_def), parameter vector = field_def(n_comp = n_vector, name = 'vector', math = '$ (V_{x}, V_{y}, V_{z}) $')
Field label for vector \((V_{x}, V_{y}, V_{z}) \).
type(field_def), parameter spherical_vector = field_def(n_comp = n_vector, name = 'spherical_vector', math = '$ (V_{r}, V_{\\theta}, V_{\\phi}) $')
Field label for vector on spherical coordinate \((V_{r}, V_{\\theta}, V_{\\phi}) \).
type(field_def), parameter cylindrical_vector = field_def(n_comp = n_vector, name = 'cylindrical_vector', math = '$ (V_{s}, V_{\\phi}, V_{z}) $')
Field label for vector on cylindrical coordinate \((V_{s}, V_{\\phi}, V_{z}) \).
type(field_def), parameter magnitude = field_def(n_comp = n_scalar, name = 'magnitude', math = '$ |V| $')
Field label for magnitude of vector \(|V| \).
type(field_def), parameter v_x = field_def(n_comp = n_scalar, name = 'x', math = '$ V_{x} $')
Field label for x-component \(V_{x} \).
type(field_def), parameter v_y = field_def(n_comp = n_scalar, name = 'y', math = '$ V_{y} $')
Field label for y-component \(V_{y} \).
type(field_def), parameter v_z = field_def(n_comp = n_scalar, name = 'z', math = '$ V_{z} $')
Field label for z-component \(V_{z} \).
type(field_def), parameter v_r = field_def(n_comp = n_scalar, name = 'r', math = '$ V_{r} $')
Field label for radial component \(V_{r} \).
type(field_def), parameter v_theta = field_def(n_comp = n_scalar, name = 'theta', math = '$ V_{\theta} $')
Field label for elevation component \(V_{\theta} \).
type(field_def), parameter v_phi = field_def(n_comp = n_scalar, name = 'phi', math = '$ V_{\phi} $')
Field label for azimuthal component \(V_{\phi} \).
type(field_def), parameter v_s = field_def(n_comp = n_scalar, name = 's', math = '$ V_{s} $')
Field label for cylindrical radius component \(V_{s} \).
type(field_def), parameter sym_tensor = field_def(n_comp = n_sym_tensor, name = 'sym_tensor', math = '$ (T_{xx}, T_{xy}, T_{xz},' // ' T_{yy}, T_{yz}, T_{zz}) $')
Field label for symmetric tensor \((T_{xx}, T_{xy}, T_{xz}, T_{yy}, T_{yz}, T_{zz}) \).
type(field_def), parameter spherical_sym_tensor = field_def(n_comp = n_sym_tensor, name = 'spherical_sym_tensor', math = '$ (T_{rr}, T_{r \theta}, T_{r \phi},' // ' T_{\theta \theta}, T_{\theta \phi},' // ' T_{\phi \phi}) $')
Field label for symmetric tensor on spherical coordinate \((T_{rr}, T_{r \theta}, T_{r \phi}, T_{\theta \theta}, T_{\theta \phi}, T_{\phi \phi}) \).
type(field_def), parameter cylindrical_sym_tensor = field_def(n_comp = n_sym_tensor, name = 'cylindrical_sym_tensor', math = '$ (T_{ss}, T_{s \phi}, T_{sz},' // ' T_{\phi \phi}, T_{\phi z}, T_{zz}) $')
Field label for symmetric tensor on cylindrical coordinate \((T_{ss}, T_{s \phi}, T_{sz}, T_{\phi \phi}, T_{\phi z}, T_{zz}) \).
type(field_def), parameter t_xx = field_def(n_comp = n_scalar, name = 'xx', math = '$ T_{xx} $')
Field label for xx-component \(T_{xx} \).
type(field_def), parameter t_xy = field_def(n_comp = n_scalar, name = 'xy', math = '$ T_{xy} $')
Field label for xy-component \(T_{xy} \).
type(field_def), parameter t_xz = field_def(n_comp = n_scalar, name = 'xz', math = '$ T_{xz} $')
Field label for xz-component \(T_{xz} \).
type(field_def), parameter t_yy = field_def(n_comp = n_scalar, name = 'yy', math = '$ T_{yy} $')
Field label for yy-component \(T_{yy} \).
type(field_def), parameter t_yz = field_def(n_comp = n_scalar, name = 'yz', math = '$ T_{yz} $')
Field label for yz-component \(T_{yz} \).
type(field_def), parameter t_zz = field_def(n_comp = n_scalar, name = 'zz', math = '$ T_{zz} $')
Field label for zz-component \(T_{zz} \).
type(field_def), parameter t_rr = field_def(n_comp = n_scalar, name = 'rr', math = '$ T_{rr} $')
Field label for rr component \(T_{rr} \).
type(field_def), parameter t_rt = field_def(n_comp = n_scalar, name = 'rt', math = '$ T_{r \theta} $')
Field label for r-theta component \(T_{r \theta} \).
type(field_def), parameter t_rp = field_def(n_comp = n_scalar, name = 'rp', math = '$ T_{r \phi} $')
Field label for r-phi component \(T_{r \phi} \).
type(field_def), parameter t_tt = field_def(n_comp = n_scalar, name = 'tt', math = '$ T_{\theta \theta} $')
Field label for theta-theta component \(T_{\theta \theta} \).
type(field_def), parameter t_tp = field_def(n_comp = n_scalar, name = 'tp', math = '$ T_{\theta \phi} $')
Field label for theta-phi component \(T_{\theta \phi} \).
type(field_def), parameter t_pp = field_def(n_comp = n_scalar, name = 'pp', math = '$ T_{\phi \phi} $')
Field label for phi-phi component \(T_{\phi \phi} \).
type(field_def), parameter t_ss = field_def(n_comp = n_scalar, name = 'ss', math = '$ T_{ss} $')
Field label for ss-component \(T_{ss} \).
type(field_def), parameter t_sp = field_def(n_comp = n_scalar, name = 'sp', math = '$ T_{s \phi} $')
Field label for s-phi-component \(T_{s \phi} \).
type(field_def), parameter t_sz = field_def(n_comp = n_scalar, name = 'sz', math = '$ T_{sz} $')
Field label for sz-component \(T_{sz} \).
type(field_def), parameter t_pz = field_def(n_comp = n_scalar, name = 'pz', math = '$ T_{\phi z} $')
Field label for phi-z-component \(T_{\phi z} \).
type(field_def), parameter asym_tensor = field_def(n_comp = n_vector, name = 'asym_tensor', math = '$ (T_{xy}, T_{xz}, T_{yz}) $')
Field label for asymmetric tensor \((T_{xy}, T_{xz}, T_{yz}) \).
type(field_def), parameter spherical_asym_tensor = field_def(n_comp = n_vector, name = 'spherical_asym_tensor', math = '$ (T_{r \theta}, T_{r \phi},' // ' T_{\phi \phi}) $')
Field label for symmetric tensor on spherical coordinate \((T_{r \theta}, T_{r \phi}, T_{\theta \phi}) \).
type(field_def), parameter cylindrical_asym_tensor = field_def(n_comp = n_vector, name = 'cylindrical_asym_tensor', math = '$ (T_{s \phi}, T_{sz}, T_{\phi z}) $')
Field label for symmetric tensor on cylindrical coordinate \((T_{s \phi}, T_{sz}, T_{\phi z}) \).
Function/Subroutine Documentation
num_flag_asym_tensor_comp()
integer(kind = kint) function m_component_flags::num_flag_asym_tensor_comp
Definition at line 373 of file m_component_flags.f90.
References ntype_as_tsr.
num_flag_scalar_comp()
integer(kind = kint) function m_component_flags::num_flag_scalar_comp
Definition at line 352 of file m_component_flags.f90.
References ntype_scalar.
num_flag_sym_tensor_comp()
integer(kind = kint) function m_component_flags::num_flag_sym_tensor_comp
Definition at line 366 of file m_component_flags.f90.
References ntype_tensor.
num_flag_vector_comp()
integer(kind = kint) function m_component_flags::num_flag_vector_comp
Definition at line 359 of file m_component_flags.f90.
References ntype_vector.
set_flag_asym_tensor_comp()
subroutine m_component_flags::set_flag_asym_tensor_comp (integer(kind = kint_4b), dimension(ntype_as_tsr), intent(inout) n_comps, character(len = kchara), dimension(ntype_as_tsr), intent(inout) names, character(len = kchara), dimension(ntype_as_tsr), intent(inout) maths)
Definition at line 492 of file m_component_flags.f90.
References asym_tensor, cylindrical_asym_tensor, magnitude, t_field_labels::set_field_labels(), spherical_asym_tensor, t_pz, t_rp, t_rt, t_sp, t_sz, t_tp, t_xy, t_xz, and t_yz.
set_flag_scalar_comp()
subroutine m_component_flags::set_flag_scalar_comp (integer(kind = kint_4b), dimension(ntype_scalar), intent(inout) n_comps, character(len = kchara), dimension(ntype_scalar), intent(inout) names, character(len = kchara), dimension(ntype_scalar), intent(inout) maths)
Definition at line 381 of file m_component_flags.f90.
References scalar, and t_field_labels::set_field_labels().
set_flag_sym_tensor_comp()
subroutine m_component_flags::set_flag_sym_tensor_comp (integer(kind = kint_4b), dimension(ntype_tensor), intent(inout) n_comps, character(len = kchara), dimension(ntype_tensor), intent(inout) names, character(len = kchara), dimension(ntype_tensor), intent(inout) maths)
Definition at line 432 of file m_component_flags.f90.
References cylindrical_sym_tensor, magnitude, t_field_labels::set_field_labels(), spherical_sym_tensor, sym_tensor, t_pp, t_pz, t_rp, t_rr, t_rt, t_sp, t_ss, t_sz, t_tp, t_tt, t_xx, t_xy, t_xz, t_yy, t_yz, and t_zz.
set_flag_vector_comp()
subroutine m_component_flags::set_flag_vector_comp (integer(kind = kint_4b), dimension(ntype_vector), intent(inout) n_comps, character(len = kchara), dimension(ntype_vector), intent(inout) names, character(len = kchara), dimension(ntype_vector), intent(inout) maths)
Definition at line 395 of file m_component_flags.f90.
References cylindrical_vector, magnitude, t_field_labels::set_field_labels(), spherical_vector, v_phi, v_r, v_s, v_theta, v_x, v_y, v_z, and vector.
Variable Documentation
asym_tensor
type(field_def), parameter m_component_flags::asym_tensor = field_def(n_comp = n_vector, name = 'asym_tensor', math = '$ (T_{xy}, T_{xz}, T_{yz}) $')
Field label for asymmetric tensor \((T_{xy}, T_{xz}, T_{yz}) \).
Definition at line 327 of file m_component_flags.f90.
Referenced by set_components_flags::s_set_components_flags(), and set_flag_asym_tensor_comp().
cylindrical_asym_tensor
type(field_def), parameter m_component_flags::cylindrical_asym_tensor = field_def(n_comp = n_vector, name = 'cylindrical_asym_tensor', math = '$ (T_{s \phi}, T_{sz}, T_{\phi z}) $')
Field label for symmetric tensor on cylindrical coordinate \((T_{s \phi}, T_{sz}, T_{\phi z}) \).
Definition at line 340 of file m_component_flags.f90.
Referenced by set_flag_asym_tensor_comp().
cylindrical_sym_tensor
type(field_def), parameter m_component_flags::cylindrical_sym_tensor = field_def(n_comp = n_sym_tensor, name = 'cylindrical_sym_tensor', math = '$ (T_{ss}, T_{s \phi}, T_{sz},' // ' T_{\phi \phi}, T_{\phi z}, T_{zz}) $')
Field label for symmetric tensor on cylindrical coordinate \((T_{ss}, T_{s \phi}, T_{sz}, T_{\phi \phi}, T_{\phi z}, T_{zz}) \).
Definition at line 219 of file m_component_flags.f90.
Referenced by set_components_flags::s_set_components_flags(), and set_flag_sym_tensor_comp().
cylindrical_vector
type(field_def), parameter m_component_flags::cylindrical_vector = field_def(n_comp = n_vector, name = 'cylindrical_vector', math = '$ (V_{s}, V_{\\phi}, V_{z}) $')
Field label for vector on cylindrical coordinate \((V_{s}, V_{\\phi}, V_{z}) \).
Definition at line 143 of file m_component_flags.f90.
Referenced by set_components_flags::s_set_components_flags(), and set_flag_vector_comp().
magnitude
type(field_def), parameter m_component_flags::magnitude = field_def(n_comp = n_scalar, name = 'magnitude', math = '$ |V| $')
Field label for magnitude of vector \(|V| \).
Definition at line 150 of file m_component_flags.f90.
Referenced by set_flag_asym_tensor_comp(), set_flag_sym_tensor_comp(), set_flag_vector_comp(), and m_more_component_flags::set_primary_componnet_flag().
ntype_as_tsr
integer(kind = kint), parameter, private m_component_flags::ntype_as_tsr = 13 private
Definition at line 120 of file m_component_flags.f90.
Referenced by num_flag_asym_tensor_comp().
ntype_scalar
integer(kind = kint), parameter, private m_component_flags::ntype_scalar = 1 private
Definition at line 117 of file m_component_flags.f90.
Referenced by num_flag_scalar_comp().
ntype_tensor
integer(kind = kint), parameter, private m_component_flags::ntype_tensor = 22 private
Definition at line 119 of file m_component_flags.f90.
Referenced by num_flag_sym_tensor_comp().
ntype_vector
integer(kind = kint), parameter, private m_component_flags::ntype_vector = 11 private
Definition at line 118 of file m_component_flags.f90.
Referenced by num_flag_vector_comp().
scalar
type(field_def), parameter m_component_flags::scalar = field_def(n_comp = n_scalar, name = 'scalar', math = '$ S $')
Field label for scalar \(S \).
Definition at line 124 of file m_component_flags.f90.
Referenced by set_components_flags::s_set_components_flags(), and set_flag_scalar_comp().
spherical_asym_tensor
type(field_def), parameter m_component_flags::spherical_asym_tensor = field_def(n_comp = n_vector, name = 'spherical_asym_tensor', math = '$ (T_{r \theta}, T_{r \phi},' // ' T_{\phi \phi}) $')
Field label for symmetric tensor on spherical coordinate \((T_{r \theta}, T_{r \phi}, T_{\theta \phi}) \).
Definition at line 333 of file m_component_flags.f90.
Referenced by set_flag_asym_tensor_comp().
spherical_sym_tensor
type(field_def), parameter m_component_flags::spherical_sym_tensor = field_def(n_comp = n_sym_tensor, name = 'spherical_sym_tensor', math = '$ (T_{rr}, T_{r \theta}, T_{r \phi},' // ' T_{\theta \theta}, T_{\theta \phi},' // ' T_{\phi \phi}) $')
Field label for symmetric tensor on spherical coordinate \((T_{rr}, T_{r \theta}, T_{r \phi}, T_{\theta \theta}, T_{\theta \phi}, T_{\phi \phi}) \).
Definition at line 210 of file m_component_flags.f90.
Referenced by set_components_flags::s_set_components_flags(), and set_flag_sym_tensor_comp().
spherical_vector
type(field_def), parameter m_component_flags::spherical_vector = field_def(n_comp = n_vector, name = 'spherical_vector', math = '$ (V_{r}, V_{\\theta}, V_{\\phi}) $')
Field label for vector on spherical coordinate \((V_{r}, V_{\\theta}, V_{\\phi}) \).
Definition at line 137 of file m_component_flags.f90.
Referenced by set_components_flags::s_set_components_flags(), and set_flag_vector_comp().
sym_tensor
type(field_def), parameter m_component_flags::sym_tensor = field_def(n_comp = n_sym_tensor, name = 'sym_tensor', math = '$ (T_{xx}, T_{xy}, T_{xz},' // ' T_{yy}, T_{yz}, T_{zz}) $')
Field label for symmetric tensor \((T_{xx}, T_{xy}, T_{xz}, T_{yy}, T_{yz}, T_{zz}) \).
Definition at line 202 of file m_component_flags.f90.
Referenced by set_components_flags::s_set_components_flags(), and set_flag_sym_tensor_comp().
t_pp
type(field_def), parameter m_component_flags::t_pp = field_def(n_comp = n_scalar, name = 'pp', math = '$ T_{\phi \phi} $')
Field label for phi-phi component \(T_{\phi \phi} \).
Definition at line 294 of file m_component_flags.f90.
Referenced by set_components_flags::s_set_components_flags(), and set_flag_sym_tensor_comp().
t_pz
type(field_def), parameter m_component_flags::t_pz = field_def(n_comp = n_scalar, name = 'pz', math = '$ T_{\phi z} $')
Field label for phi-z-component \(T_{\phi z} \).
Definition at line 319 of file m_component_flags.f90.
Referenced by set_components_flags::s_set_components_flags(), set_flag_asym_tensor_comp(), and set_flag_sym_tensor_comp().
t_rp
type(field_def), parameter m_component_flags::t_rp = field_def(n_comp = n_scalar, name = 'rp', math = '$ T_{r \phi} $')
Field label for r-phi component \(T_{r \phi} \).
Definition at line 276 of file m_component_flags.f90.
Referenced by set_components_flags::s_set_components_flags(), set_flag_asym_tensor_comp(), and set_flag_sym_tensor_comp().
t_rr
type(field_def), parameter m_component_flags::t_rr = field_def(n_comp = n_scalar, name = 'rr', math = '$ T_{rr} $')
Field label for rr component \(T_{rr} \).
Definition at line 264 of file m_component_flags.f90.
Referenced by set_components_flags::s_set_components_flags(), and set_flag_sym_tensor_comp().
t_rt
type(field_def), parameter m_component_flags::t_rt = field_def(n_comp = n_scalar, name = 'rt', math = '$ T_{r \theta} $')
Field label for r-theta component \(T_{r \theta} \).
Definition at line 270 of file m_component_flags.f90.
Referenced by set_components_flags::s_set_components_flags(), set_flag_asym_tensor_comp(), and set_flag_sym_tensor_comp().
t_sp
type(field_def), parameter m_component_flags::t_sp = field_def(n_comp = n_scalar, name = 'sp', math = '$ T_{s \phi} $')
Field label for s-phi-component \(T_{s \phi} \).
Definition at line 307 of file m_component_flags.f90.
Referenced by set_components_flags::s_set_components_flags(), set_flag_asym_tensor_comp(), and set_flag_sym_tensor_comp().
t_ss
type(field_def), parameter m_component_flags::t_ss = field_def(n_comp = n_scalar, name = 'ss', math = '$ T_{ss} $')
Field label for ss-component \(T_{ss} \).
Definition at line 301 of file m_component_flags.f90.
Referenced by set_components_flags::s_set_components_flags(), and set_flag_sym_tensor_comp().
t_sz
type(field_def), parameter m_component_flags::t_sz = field_def(n_comp = n_scalar, name = 'sz', math = '$ T_{sz} $')
Field label for sz-component \(T_{sz} \).
Definition at line 313 of file m_component_flags.f90.
Referenced by set_components_flags::s_set_components_flags(), set_flag_asym_tensor_comp(), and set_flag_sym_tensor_comp().
t_tp
type(field_def), parameter m_component_flags::t_tp = field_def(n_comp = n_scalar, name = 'tp', math = '$ T_{\theta \phi} $')
Field label for theta-phi component \(T_{\theta \phi} \).
Definition at line 288 of file m_component_flags.f90.
Referenced by set_components_flags::s_set_components_flags(), set_flag_asym_tensor_comp(), and set_flag_sym_tensor_comp().
t_tt
type(field_def), parameter m_component_flags::t_tt = field_def(n_comp = n_scalar, name = 'tt', math = '$ T_{\theta \theta} $')
Field label for theta-theta component \(T_{\theta \theta} \).
Definition at line 282 of file m_component_flags.f90.
Referenced by set_components_flags::s_set_components_flags(), and set_flag_sym_tensor_comp().
t_xx
type(field_def), parameter m_component_flags::t_xx = field_def(n_comp = n_scalar, name = 'xx', math = '$ T_{xx} $')
Field label for xx-component \(T_{xx} \).
Definition at line 227 of file m_component_flags.f90.
Referenced by set_components_flags::s_set_components_flags(), and set_flag_sym_tensor_comp().
t_xy
type(field_def), parameter m_component_flags::t_xy = field_def(n_comp = n_scalar, name = 'xy', math = '$ T_{xy} $')
Field label for xy-component \(T_{xy} \).
Definition at line 233 of file m_component_flags.f90.
Referenced by set_components_flags::s_set_components_flags(), set_flag_asym_tensor_comp(), and set_flag_sym_tensor_comp().
t_xz
type(field_def), parameter m_component_flags::t_xz = field_def(n_comp = n_scalar, name = 'xz', math = '$ T_{xz} $')
Field label for xz-component \(T_{xz} \).
Definition at line 239 of file m_component_flags.f90.
Referenced by set_components_flags::s_set_components_flags(), set_flag_asym_tensor_comp(), and set_flag_sym_tensor_comp().
t_yy
type(field_def), parameter m_component_flags::t_yy = field_def(n_comp = n_scalar, name = 'yy', math = '$ T_{yy} $')
Field label for yy-component \(T_{yy} \).
Definition at line 245 of file m_component_flags.f90.
Referenced by set_components_flags::s_set_components_flags(), and set_flag_sym_tensor_comp().
t_yz
type(field_def), parameter m_component_flags::t_yz = field_def(n_comp = n_scalar, name = 'yz', math = '$ T_{yz} $')
Field label for yz-component \(T_{yz} \).
Definition at line 251 of file m_component_flags.f90.
Referenced by set_components_flags::s_set_components_flags(), set_flag_asym_tensor_comp(), and set_flag_sym_tensor_comp().
t_zz
type(field_def), parameter m_component_flags::t_zz = field_def(n_comp = n_scalar, name = 'zz', math = '$ T_{zz} $')
Field label for zz-component \(T_{zz} \).
Definition at line 257 of file m_component_flags.f90.
Referenced by set_components_flags::s_set_components_flags(), and set_flag_sym_tensor_comp().
v_phi
type(field_def), parameter m_component_flags::v_phi = field_def(n_comp = n_scalar, name = 'phi', math = '$ V_{\phi} $')
Field label for azimuthal component \(V_{\phi} \).
Definition at line 188 of file m_component_flags.f90.
Referenced by set_flag_vector_comp(), and m_more_component_flags::set_primary_componnet_flag().
v_r
type(field_def), parameter m_component_flags::v_r = field_def(n_comp = n_scalar, name = 'r', math = '$ V_{r} $')
Field label for radial component \(V_{r} \).
Definition at line 176 of file m_component_flags.f90.
Referenced by set_flag_vector_comp(), and m_more_component_flags::set_primary_componnet_flag().
v_s
type(field_def), parameter m_component_flags::v_s = field_def(n_comp = n_scalar, name = 's', math = '$ V_{s} $')
Field label for cylindrical radius component \(V_{s} \).
Definition at line 194 of file m_component_flags.f90.
Referenced by set_flag_vector_comp(), and m_more_component_flags::set_primary_componnet_flag().
v_theta
type(field_def), parameter m_component_flags::v_theta = field_def(n_comp = n_scalar, name = 'theta', math = '$ V_{\theta} $')
Field label for elevation component \(V_{\theta} \).
Definition at line 182 of file m_component_flags.f90.
Referenced by set_flag_vector_comp(), and m_more_component_flags::set_primary_componnet_flag().
v_x
type(field_def), parameter m_component_flags::v_x = field_def(n_comp = n_scalar, name = 'x', math = '$ V_{x} $')
Field label for x-component \(V_{x} \).
Definition at line 157 of file m_component_flags.f90.
Referenced by set_components_flags::s_set_components_flags(), and set_flag_vector_comp().
v_y
type(field_def), parameter m_component_flags::v_y = field_def(n_comp = n_scalar, name = 'y', math = '$ V_{y} $')
Field label for y-component \(V_{y} \).
Definition at line 163 of file m_component_flags.f90.
Referenced by set_components_flags::s_set_components_flags(), and set_flag_vector_comp().
v_z
type(field_def), parameter m_component_flags::v_z = field_def(n_comp = n_scalar, name = 'z', math = '$ V_{z} $')
Field label for z-component \(V_{z} \).
Definition at line 169 of file m_component_flags.f90.
Referenced by set_components_flags::s_set_components_flags(), and set_flag_vector_comp().
vector
type(field_def), parameter m_component_flags::vector = field_def(n_comp = n_vector, name = 'vector', math = '$ (V_{x}, V_{y}, V_{z}) $')
Field label for vector \((V_{x}, V_{y}, V_{z}) \).
Definition at line 131 of file m_component_flags.f90.
Referenced by set_components_flags::s_set_components_flags(), and set_flag_vector_comp().