CALYPSO: m_calypso_mpi_io Module Reference
m_calypso_mpi_io Module Reference
Base routines for MPI-IO.
Functions/Subroutines
subroutine, private init_mpi_io_status
subroutine deallocate_mpi_io_status
subroutine calypso_mpi_write_file_open (file_name, num_pe, id_mpi_file)
subroutine calypso_mpi_append_file_open (file_name, num_pe, id_mpi_file, ioffset)
subroutine calypso_mpi_read_file_open (file_name, id_mpi_file)
subroutine calypso_close_mpi_file (id_mpi_file)
subroutine mpi_write_one_chara_b (id_mpi_file, ioffset, ilength, textbuf)
subroutine mpi_write_mul_chara_b (id_mpi_file, ioffset, ilength, nline, textbuf)
subroutine mpi_write_real_b (id_mpi_file, ioffset, num, vector)
subroutine mpi_write_int_b (id_mpi_file, ioffset, num, i_vector)
subroutine mpi_write_int8_b (id_mpi_file, ioffset, num, i8_vector)
subroutine mpi_write_int4_b (id_mpi_file, ioffset, num, i4_vector)
subroutine calypso_mpi_seek_write_head_c (id_mpi_file, ioffset, textbuf)
subroutine mpi_write_endian_flag (id_mpi_file, ioffset)
subroutine mpi_read_set_endian_flag (id_mpi_file, iflag_bin_swap, ioffset)
subroutine mpi_read_one_chara_b (id_mpi_file, ioffset, ilength, charabuf)
character(len=ilength) function calypso_mpi_seek_read_chara (id_mpi_file, ioffset, ilength)
subroutine mpi_read_mul_chara_b (id_mpi_file, ioffset, ilength, nline, textbuf)
subroutine mpi_read_real_b (id_mpi_file, iflag_bin_swap, ioffset, num, vector)
subroutine mpi_read_int_b (id_mpi_file, iflag_bin_swap, ioffset, num, i_vector)
subroutine mpi_read_int8_b (id_mpi_file, iflag_bin_swap, ioffset, num, i8_vector)
subroutine mpi_read_int4_b (id_mpi_file, iflag_bin_swap, ioffset, num, i4_vector)
subroutine calypso_mpi_seek_write_gz (id_mpi_file, ioffset, zbuf)
subroutine calypso_mpi_seek_read_gz (id_mpi_file, ioffset, zbuf)
subroutine calypso_gz_mpi_seek_write (id_mpi_file, ioff_gl, zbuf)
Variables
integer, dimension(:), allocatable sta1_io
status flag for sending
Detailed Description
Base routines for MPI-IO.
      subroutine deallocate_mpi_IO_status
      subroutine calypso_mpi_write_file_open                          &
     &         (file_name, num_pe, id_mpi_file)
      subroutine calypso_mpi_append_file_open                         &
     &         (file_name, num_pe, id_mpi_file, ioffset)
      subroutine calypso_mpi_read_file_open(file_name, id_mpi_file)
      subroutine calypso_close_mpi_file(id_mpi_file)
      subroutine mpi_write_endian_flag(id_mpi_file, ioffset)
      subroutine mpi_write_one_chara_b                                &
     &         (id_mpi_file, ioffset, ilength, textbuf)
      subroutine mpi_write_mul_chara_b                                &
     &         (id_mpi_file, ioffset, ilength, nline, textbuf)
      subroutine mpi_write_real_b                                     &
     &         (id_mpi_file, ioffset, num, vector)
      subroutine mpi_write_int_b                                      &
     &         (id_mpi_file, ioffset, num, i_vector)
      subroutine mpi_write_int8_b                                     &
     &         (id_mpi_file, ioffset, num, i8_vector)
      subroutine mpi_write_int4_b                                     &
     &         (id_mpi_file, ioffset, num, i4_vector)
      subroutine calypso_mpi_seek_write_head_c                        &
     &         (id_mpi_file, ioffset, textbuf)
      subroutine mpi_read_set_endian_flag                             &
     &         (id_mpi_file, iflag_bin_swap, ioffset)
      subroutine mpi_read_one_chara_b                                 &
     &         (id_mpi_file, ioffset, ilength, charabuf)
      function calypso_mpi_seek_read_chara                            &
     &       (id_mpi_file, ioffset, ilength)
        character(len=ilength) :: calypso_mpi_seek_read_chara
      subroutine mpi_read_mul_chara_b                                 &
     &         (id_mpi_file, ioffset, ilength, nline, textbuf)
      subroutine mpi_read_real_b                                      &
     &         (id_mpi_file, iflag_bin_swap, ioffset, num, vector)
      subroutine mpi_read_int_b                                       &
     &         (id_mpi_file, iflag_bin_swap, ioffset, num, i_vector)
      subroutine mpi_read_int8_b                                      &
     &         (id_mpi_file, iflag_bin_swap, ioffset, num, i8_vector)
      subroutine mpi_read_int4_b                                      &
     &         (id_mpi_file, iflag_bin_swap, ioffset, num, i4_vector)
      subroutine calypso_mpi_seek_write_gz(id_mpi_file, ioffset, zbuf)
      subroutine calypso_mpi_seek_read_gz(id_mpi_file, ioffset, zbuf)
        type(buffer_4_gzip), intent(inout) :: zbuf
      subroutine calypso_gz_mpi_seek_write(id_mpi_file, ioff_gl, zbuf)
        type(buffer_4_gzip), intent(in) :: zbuf
    calypso_gz_mpi_seek_write only work correctly when number of
   subdomain is equal to number of threads
Function/Subroutine Documentation
calypso_close_mpi_file()
subroutine m_calypso_mpi_io::calypso_close_mpi_file (integer, intent(in) id_mpi_file)
Definition at line 160 of file m_calypso_mpi_IO.f90.
References deallocate_mpi_io_status(), and calypso_mpi::ierr_mpi.
Referenced by mpi_ascii_data_io::close_mpi_file(), convert_from_rayleigh_rst::cvt_each_field_from_rayleigh(), gz_ucd_field_mpi_io::gz_read_alloc_ucd_fld_file_mpi(), gz_ucd_field_mpi_io::gz_read_ucd_field_file_mpi(), gz_ucd_field_mpi_io::gz_write_ucd_field_file_mpi(), field_file_mpi_io::read_alloc_step_fld_file_mpi(), field_file_mpi_io::read_alloc_step_fld_head_mpi(), gz_field_file_mpi_io::read_alloc_stp_fld_file_gz_mpi(), gz_field_file_mpi_io::read_alloc_stp_fld_head_gz_mpi(), ucd_field_mpi_io::read_alloc_ucd_fld_file_mpi(), gz_field_file_mpi_io::read_step_field_file_gz_mpi(), field_file_mpi_io::read_step_field_file_mpi(), ucd_field_mpi_io::read_ucd_field_file_mpi(), gz_field_file_mpi_io::write_gz_step_field_file_mpi(), field_file_mpi_io::write_step_field_file_mpi(), and ucd_field_mpi_io::write_ucd_field_file_mpi().
calypso_gz_mpi_seek_write()
subroutine m_calypso_mpi_io::calypso_gz_mpi_seek_write (integer, intent(in) id_mpi_file, integer(kind = kint_gl), intent(inout) ioff_gl, type(buffer_4_gzip), intent(in) zbuf)
Definition at line 545 of file m_calypso_mpi_IO.f90.
References calypso_mpi_int8::calypso_mpi_allgather_one_int8(), calypso_mpi_seek_write_gz(), and calypso_mpi::my_rank.
Referenced by gz_ucd_file_mpi_io::gz_write_ucd_mesh_mpi(), gz_ucd_file_mpi_io::gz_write_ucd_vecotr_mpi(), gz_vtk_file_mpi_io::gz_write_vtk_mesh_mpi(), gz_vtk_file_mpi_io::gz_write_vtk_scalar_mpi(), and gz_vtk_file_mpi_io::gz_write_vtk_vecotr_mpi().
calypso_mpi_append_file_open()
subroutine m_calypso_mpi_io::calypso_mpi_append_file_open (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(inout) id_mpi_file, integer(kind = kint_gl), intent(inout) ioffset)
Definition at line 124 of file m_calypso_mpi_IO.f90.
References calypso_mpi::calypso_comm, calypso_mpi::ierr_mpi, and init_mpi_io_status().
Referenced by mpi_ascii_data_io::open_append_mpi_file().
calypso_mpi_read_file_open()
subroutine m_calypso_mpi_io::calypso_mpi_read_file_open (character(len=kchara), intent(in) file_name, integer, intent(inout) id_mpi_file)
Definition at line 144 of file m_calypso_mpi_IO.f90.
References calypso_mpi::calypso_comm, calypso_mpi::ierr_mpi, and init_mpi_io_status().
Referenced by convert_from_rayleigh_rst::cvt_each_field_from_rayleigh(), gz_ucd_field_mpi_io::gz_read_alloc_ucd_fld_file_mpi(), gz_ucd_field_mpi_io::gz_read_ucd_field_file_mpi(), mpi_ascii_data_io::open_read_mpi_file(), field_file_mpi_io::read_alloc_step_fld_file_mpi(), field_file_mpi_io::read_alloc_step_fld_head_mpi(), gz_field_file_mpi_io::read_alloc_stp_fld_file_gz_mpi(), gz_field_file_mpi_io::read_alloc_stp_fld_head_gz_mpi(), ucd_field_mpi_io::read_alloc_ucd_fld_file_mpi(), gz_field_file_mpi_io::read_step_field_file_gz_mpi(), field_file_mpi_io::read_step_field_file_mpi(), and ucd_field_mpi_io::read_ucd_field_file_mpi().
calypso_mpi_seek_read_chara()
character(len=ilength) function m_calypso_mpi_io::calypso_mpi_seek_read_chara (integer, intent(in) id_mpi_file, integer(kind = mpi_offset_kind), intent(inout) ioffset, integer, intent(in) ilength)
Definition at line 372 of file m_calypso_mpi_IO.f90.
References calypso_mpi_char::calypso_mpi_seek_read_one_chara(), and sta1_io.
Referenced by mpi_ascii_data_io::mpi_read_characters(), and mpi_ascii_data_io::mpi_read_charahead().
calypso_mpi_seek_read_gz()
subroutine m_calypso_mpi_io::calypso_mpi_seek_read_gz (integer, intent(in) id_mpi_file, integer(kind = mpi_offset_kind), intent(inout) ioffset, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 526 of file m_calypso_mpi_IO.f90.
References calypso_mpi_char::calypso_mpi_seek_read_mul_chara(), and sta1_io.
Referenced by gz_mpi_binary_data_io::gz_mpi_read_1d_vector_b(), gz_mpi_binary_head_io::gz_mpi_read_byte_check(), gz_mpi_ascii_data_io::gz_mpi_read_characters(), gz_mpi_ascii_data_io::gz_mpi_read_charahead(), gz_mpi_binary_data_io::gz_mpi_read_int8_vector_b(), gz_mpi_binary_head_io::gz_mpi_read_mul_charahead_b(), gz_mpi_binary_head_io::gz_mpi_read_mul_int8head_b(), gz_mpi_binary_head_io::gz_mpi_read_mul_realhead_b(), gz_mpi_ascii_data_io::gz_mpi_skip_header(), gz_field_data_mpi_io::gz_read_each_field_mpi(), gz_field_data_mpi_io::gz_read_fld_1word_mpi(), and gz_field_data_mpi_io::gz_read_fld_charhead_mpi().
calypso_mpi_seek_write_gz()
subroutine m_calypso_mpi_io::calypso_mpi_seek_write_gz (integer, intent(in) id_mpi_file, integer(kind = mpi_offset_kind), intent(inout) ioffset, type(buffer_4_gzip), intent(in) zbuf)
Definition at line 508 of file m_calypso_mpi_IO.f90.
References calypso_mpi_char::calypso_mpi_seek_wrt_mul_chara(), and sta1_io.
Referenced by calypso_gz_mpi_seek_write(), gz_mpi_binary_data_io::gz_mpi_write_1d_vector_b(), gz_mpi_binary_head_io::gz_mpi_write_byte_flag(), gz_mpi_ascii_data_io::gz_mpi_write_characters(), gz_mpi_ascii_data_io::gz_mpi_write_charahead(), gz_mpi_binary_data_io::gz_mpi_write_int8_vector_b(), gz_mpi_binary_head_io::gz_mpi_write_mul_charahead_b(), gz_mpi_binary_head_io::gz_mpi_write_mul_int8head_b(), gz_mpi_binary_head_io::gz_mpi_write_mul_realhead_b(), gz_field_data_mpi_io::gz_write_fld_header_mpi(), gz_field_data_mpi_io::gz_write_fld_vecotr_mpi(), gz_vtk_file_mpi_io::gz_write_vtk_header_mpi(), and gz_vtk_file_mpi_io::gz_write_vtk_tensor_mpi().
calypso_mpi_seek_write_head_c()
subroutine m_calypso_mpi_io::calypso_mpi_seek_write_head_c (integer, intent(in) id_mpi_file, integer(kind = kint_gl), intent(inout) ioffset, character(len=*), intent(in) textbuf)
Definition at line 284 of file m_calypso_mpi_IO.f90.
References calypso_mpi_char::calypso_mpi_seek_wrt_one_chara(), calypso_mpi::my_rank, and sta1_io.
Referenced by field_block_mpi_io::write_field_data_mpi(), field_data_mpi_io::write_field_name_mpi(), field_block_mpi_io::write_fld_vecotr_mpi(), ucd_file_mpi_io::write_ucd_data_mpi(), ucd_file_mpi_io::write_ucd_node_mpi(), vtk_file_mpi_io::write_vtk_data_mpi(), and vtk_file_mpi_io::write_vtk_mesh_mpi().
calypso_mpi_write_file_open()
subroutine m_calypso_mpi_io::calypso_mpi_write_file_open (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(inout) id_mpi_file)
Definition at line 102 of file m_calypso_mpi_IO.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_mpi_barrier(), calypso_mpi::ierr_mpi, and init_mpi_io_status().
Referenced by gz_ucd_field_mpi_io::gz_write_ucd_field_file_mpi(), mpi_ascii_data_io::open_write_mpi_file(), gz_field_file_mpi_io::write_gz_step_field_file_mpi(), field_file_mpi_io::write_step_field_file_mpi(), and ucd_field_mpi_io::write_ucd_field_file_mpi().
deallocate_mpi_io_status()
subroutine m_calypso_mpi_io::deallocate_mpi_io_status
Definition at line 93 of file m_calypso_mpi_IO.f90.
References sta1_io.
Referenced by calypso_close_mpi_file().
init_mpi_io_status()
subroutine, private m_calypso_mpi_io::init_mpi_io_status private
Definition at line 84 of file m_calypso_mpi_IO.f90.
References sta1_io.
Referenced by calypso_mpi_append_file_open(), calypso_mpi_read_file_open(), and calypso_mpi_write_file_open().
mpi_read_int4_b()
subroutine m_calypso_mpi_io::mpi_read_int4_b (integer, intent(in) id_mpi_file, integer, intent(in) iflag_bin_swap, integer(kind = mpi_offset_kind), intent(in) ioffset, integer(kind = kint_gl), intent(in) num, integer, dimension(num), intent(inout) i4_vector)
Definition at line 483 of file m_calypso_mpi_IO.f90.
References byte_swap_f::byte_swap_int4_f(), calypso_mpi_int4::calypso_mpi_seek_read_int4(), m_machine_parameter::iendian_flip, and sta1_io.
mpi_read_int8_b()
subroutine m_calypso_mpi_io::mpi_read_int8_b (integer, intent(in) id_mpi_file, integer, intent(in) iflag_bin_swap, integer(kind = mpi_offset_kind), intent(in) ioffset, integer(kind = kint_gl), intent(in) num, integer(kind = kint_gl), dimension(num), intent(inout) i8_vector)
Definition at line 459 of file m_calypso_mpi_IO.f90.
References byte_swap_f::byte_swap_int8_f(), calypso_mpi_int8::calypso_mpi_seek_read_int8(), m_machine_parameter::iendian_flip, and sta1_io.
Referenced by mpi_binary_data_io::mpi_read_int8_vector_b(), and mpi_binary_head_io::mpi_read_mul_int8head_b().
mpi_read_int_b()
subroutine m_calypso_mpi_io::mpi_read_int_b (integer, intent(in) id_mpi_file, integer, intent(in) iflag_bin_swap, integer(kind = mpi_offset_kind), intent(in) ioffset, integer(kind = kint_gl), intent(in) num, integer(kind = kint), dimension(num), intent(inout) i_vector)
Definition at line 435 of file m_calypso_mpi_IO.f90.
References byte_swap_f::byte_swap_int_f(), calypso_mpi_int::calypso_mpi_seek_read_int(), m_machine_parameter::iendian_flip, and sta1_io.
mpi_read_mul_chara_b()
subroutine m_calypso_mpi_io::mpi_read_mul_chara_b (integer, intent(in) id_mpi_file, integer(kind = mpi_offset_kind), intent(in) ioffset, integer, intent(in) ilength, integer(kind = kint_gl), intent(in) nline, character(len=ilength), dimension(nline), intent(inout) textbuf)
Definition at line 392 of file m_calypso_mpi_IO.f90.
References calypso_mpi_char::calypso_mpi_seek_read_mul_chara(), and sta1_io.
Referenced by mpi_binary_head_io::mpi_read_mul_charahead_b().
mpi_read_one_chara_b()
subroutine m_calypso_mpi_io::mpi_read_one_chara_b (integer, intent(in) id_mpi_file, integer(kind = mpi_offset_kind), intent(inout) ioffset, integer, intent(in) ilength, character(len=ilength), intent(inout) charabuf)
Definition at line 353 of file m_calypso_mpi_IO.f90.
References calypso_mpi_char::calypso_mpi_seek_read_one_chara(), and sta1_io.
Referenced by field_data_mpi_io::read_field_header_mpi(), field_data_mpi_io::read_field_name_mpi(), field_data_mpi_io::read_field_num_mpi(), field_data_mpi_io::read_field_time_mpi(), and field_block_mpi_io::read_fld_vecotr_mpi().
mpi_read_real_b()
subroutine m_calypso_mpi_io::mpi_read_real_b (integer, intent(in) id_mpi_file, integer, intent(in) iflag_bin_swap, integer(kind = mpi_offset_kind), intent(in) ioffset, integer(kind = kint_gl), intent(in) num, real(kind = kreal), dimension(num), intent(inout) vector)
Definition at line 411 of file m_calypso_mpi_IO.f90.
References byte_swap_f::byte_swap_real_f(), calypso_mpi_real::calypso_mpi_seek_read_real(), m_machine_parameter::iendian_flip, and sta1_io.
Referenced by mpi_binary_data_io::mpi_read_1d_vector_b(), and mpi_binary_head_io::mpi_read_mul_realhead_b().
mpi_read_set_endian_flag()
subroutine m_calypso_mpi_io::mpi_read_set_endian_flag (integer, intent(in) id_mpi_file, integer, intent(inout) iflag_bin_swap, integer(kind = kint_gl), intent(inout) ioffset)
Definition at line 326 of file m_calypso_mpi_IO.f90.
References calypso_mpi_int4::calypso_mpi_bcast_one_int4(), calypso_mpi_int4::calypso_mpi_seek_read_one_int4(), binary_io::endian_check(), m_constants::ifour, calypso_mpi::my_rank, and sta1_io.
Referenced by mpi_binary_head_io::open_read_mpi_file_b().
mpi_write_endian_flag()
subroutine m_calypso_mpi_io::mpi_write_endian_flag (integer, intent(in) id_mpi_file, integer(kind = kint_gl), intent(inout) ioffset)
Definition at line 307 of file m_calypso_mpi_IO.f90.
References calypso_mpi_int4::calypso_mpi_seek_write_one_int4(), m_machine_parameter::i_unix, m_constants::ifour, calypso_mpi::my_rank, and sta1_io.
Referenced by mpi_binary_head_io::open_write_mpi_file_b().
mpi_write_int4_b()
subroutine m_calypso_mpi_io::mpi_write_int4_b (integer, intent(in) id_mpi_file, integer(kind = mpi_offset_kind), intent(in) ioffset, integer(kind = kint_gl), intent(in) num, integer, dimension(num), intent(in) i4_vector)
Definition at line 265 of file m_calypso_mpi_IO.f90.
References calypso_mpi_int4::calypso_mpi_seek_write_int4(), and sta1_io.
mpi_write_int8_b()
subroutine m_calypso_mpi_io::mpi_write_int8_b (integer, intent(in) id_mpi_file, integer(kind = mpi_offset_kind), intent(in) ioffset, integer(kind = kint_gl), intent(in) num, integer(kind = kint_gl), dimension(num), intent(in) i8_vector)
Definition at line 247 of file m_calypso_mpi_IO.f90.
References calypso_mpi_int8::calypso_mpi_seek_write_int8(), and sta1_io.
Referenced by mpi_binary_data_io::mpi_write_int8_vector_b(), and mpi_binary_head_io::mpi_write_mul_int8head_b().
mpi_write_int_b()
subroutine m_calypso_mpi_io::mpi_write_int_b (integer, intent(in) id_mpi_file, integer(kind = mpi_offset_kind), intent(in) ioffset, integer(kind = kint_gl), intent(in) num, integer(kind = kint), dimension(num), intent(in) i_vector)
Definition at line 229 of file m_calypso_mpi_IO.f90.
References calypso_mpi_int::calypso_mpi_seek_write_int(), and sta1_io.
mpi_write_mul_chara_b()
subroutine m_calypso_mpi_io::mpi_write_mul_chara_b (integer, intent(in) id_mpi_file, integer(kind = mpi_offset_kind), intent(in) ioffset, integer, intent(in) ilength, integer(kind = kint_gl), intent(in) nline, character(len=ilength), dimension(nline), intent(in) textbuf)
Definition at line 192 of file m_calypso_mpi_IO.f90.
References calypso_mpi_char::calypso_mpi_seek_wrt_mul_chara(), and sta1_io.
Referenced by mpi_binary_head_io::mpi_write_mul_charahead_b(), mpi_picked_sph_spectr_io::write_picked_specr_data_mpi(), mpi_sph_gauss_coefs_io::write_sph_gauss_coefes_mpi(), ucd_file_mpi_io::write_ucd_connect_mpi(), ucd_file_mpi_io::write_ucd_data_mpi(), ucd_file_mpi_io::write_ucd_node_mpi(), vtk_file_mpi_io::write_vtk_celltype_mpi(), vtk_file_mpi_io::write_vtk_connect_mpi(), vtk_file_mpi_io::write_vtk_field_mpi(), and vtk_file_mpi_io::write_vtk_tensor_mpi().
mpi_write_one_chara_b()
subroutine m_calypso_mpi_io::mpi_write_one_chara_b (integer, intent(in) id_mpi_file, integer(kind = mpi_offset_kind), intent(inout) ioffset, integer, intent(in) ilength, character(len=ilength), intent(in) textbuf)
Definition at line 173 of file m_calypso_mpi_IO.f90.
References calypso_mpi_char::calypso_mpi_seek_wrt_one_chara(), and sta1_io.
Referenced by mpi_ascii_data_io::mpi_write_charahead(), field_block_mpi_io::write_fld_vecotr_mpi(), mpi_picked_sph_spectr_io::write_picked_specr_head_mpi(), mpi_sph_gauss_coefs_io::write_sph_gauss_coefes_mpi(), and mpi_sph_gauss_coefs_io::write_sph_gauss_header_mpi().
mpi_write_real_b()
subroutine m_calypso_mpi_io::mpi_write_real_b (integer, intent(in) id_mpi_file, integer(kind = mpi_offset_kind), intent(in) ioffset, integer(kind = kint_gl), intent(in) num, real(kind = kreal), dimension(num), intent(in) vector)
Definition at line 211 of file m_calypso_mpi_IO.f90.
References calypso_mpi_real::calypso_mpi_seek_write_real(), and sta1_io.
Referenced by mpi_binary_data_io::mpi_write_1d_vector_b(), and mpi_binary_head_io::mpi_write_mul_realhead_b().
Variable Documentation
sta1_io
integer, dimension(:), allocatable m_calypso_mpi_io::sta1_io
status flag for sending
Definition at line 74 of file m_calypso_mpi_IO.f90.
Referenced by calypso_mpi_seek_read_chara(), calypso_mpi_seek_read_gz(), calypso_mpi_seek_write_gz(), calypso_mpi_seek_write_head_c(), deallocate_mpi_io_status(), init_mpi_io_status(), mpi_read_int4_b(), mpi_read_int8_b(), mpi_read_int_b(), mpi_read_mul_chara_b(), mpi_read_one_chara_b(), mpi_read_real_b(), mpi_read_set_endian_flag(), mpi_write_endian_flag(), mpi_write_int4_b(), mpi_write_int8_b(), mpi_write_int_b(), mpi_write_mul_chara_b(), mpi_write_one_chara_b(), and mpi_write_real_b().