CALYPSO: t_radial_matrices_sph_mhd Module Reference
t_radial_matrices_sph_mhd Module Reference
Radial band matrix for time evolutions.
Data Types
type mhd_radial_matrices
Structure of band matrices for dynamo simulation.
Functions/Subroutines
subroutine, private alloc_press_vpol_mat_sph (sph_rj, smat)
subroutine alloc_average_w_center (sph_rj, sph_MHD_mat)
subroutine dealloc_average_w_center (sph_MHD_mat)
subroutine allocate_press_vpol_mat_sph (sph_rj, sph_MHD_mat)
subroutine check_velocity_matrices_sph (id_rank, sph_rj, sph_MHD_mat)
Detailed Description
Radial band matrix for time evolutions.
      subroutine alloc_average_w_center(sph_rj, sph_MHD_mat)
      subroutine dealloc_average_w_center(sph_MHD_mat)
      subroutine allocate_press_vpol_mat_sph(sph_rj, sph_MHD_mat)
      subroutine check_velocity_matrices_sph                          &
     &         (id_rank, sph_rj, sph_MHD_mat)
        type(MHD_radial_matrices), intent(inout) :: sph_MHD_mat
Function/Subroutine Documentation
alloc_average_w_center()
subroutine t_radial_matrices_sph_mhd::alloc_average_w_center (type(sph_rj_grid), intent(in) sph_rj, type(mhd_radial_matrices), intent(inout) sph_MHD_mat)
Definition at line 102 of file t_radial_matrices_sph_MHD.f90.
Referenced by const_radial_mat_4_sph::const_radial_mat_sph_w_center().
alloc_press_vpol_mat_sph()
subroutine, private t_radial_matrices_sph_mhd::alloc_press_vpol_mat_sph (type(sph_rj_grid), intent(in) sph_rj, type(band_matrices_type), intent(inout) smat) private
Definition at line 74 of file t_radial_matrices_sph_MHD.f90.
Referenced by allocate_press_vpol_mat_sph().
allocate_press_vpol_mat_sph()
subroutine t_radial_matrices_sph_mhd::allocate_press_vpol_mat_sph (type(sph_rj_grid), intent(in) sph_rj, type(mhd_radial_matrices), intent(inout) sph_MHD_mat)
Definition at line 127 of file t_radial_matrices_sph_MHD.f90.
References alloc_press_vpol_mat_sph().
check_velocity_matrices_sph()
subroutine t_radial_matrices_sph_mhd::check_velocity_matrices_sph (integer, intent(in) id_rank, type(sph_rj_grid), intent(in) sph_rj, type(mhd_radial_matrices), intent(in) sph_MHD_mat)
Definition at line 139 of file t_radial_matrices_sph_MHD.f90.
References check_sph_radial_mat::check_radial_7band_mat(), and t_sph_matrices::check_radial_band_mat().
dealloc_average_w_center()
subroutine t_radial_matrices_sph_mhd::dealloc_average_w_center (type(mhd_radial_matrices), intent(inout) sph_MHD_mat)
Definition at line 115 of file t_radial_matrices_sph_MHD.f90.