CALYPSO: t_read_mesh_data Module Reference
t_read_mesh_data Module Reference
Data arry for mesh_data_IO.
Data Types
type mul_mesh_data
Structure for mesh data (position, connectivity, group, and communication)
type mul_mesh_geometry
Structure for grid data (position, connectivity, and communication)
type mul_mesh_groups
Structure for group data (node, element, surface, and infinity)
type surf_edge_io_file
Functions/Subroutines
subroutine dealloc_surface_mesh_io (surf_mesh_IO)
subroutine dealloc_edge_mesh_io (edge_mesh_IO)
subroutine dealloc_ele_geometry_data (ele_mesh_IO)
subroutine dealloc_surf_geometry_data (surf_mesh_IO)
subroutine alloc_multi_mesh_data_io (nloop, mesh_IO)
subroutine alloc_multi_mesh_group_io (mesh_IO, mesh_grp_IO)
subroutine dealloc_multi_mesh_data_io (mesh_IO)
subroutine dealloc_multi_mesh_group_io (mesh_grp_IO)
Detailed Description
Data arry for mesh_data_IO.
      subroutine dealloc_surface_mesh_IO(surf_mesh_IO)
        type(surf_edge_IO_file), intent(inout) :: surf_mesh_IO
      subroutine dealloc_edge_mesh_IO(edge_mesh_IO)
        type(surf_edge_IO_file), intent(inout) :: edge_mesh_IO
      subroutine dealloc_ele_geometry_data(ele_mesh_IO)
        type(surf_edge_IO_file), intent(inout) :: ele_mesh_IO
      subroutine dealloc_surf_geometry_data(surf_mesh_IO)
        type(surf_edge_IO_file), intent(inout) :: surf_mesh_IO
      subroutine alloc_multi_mesh_data_IO(nloop, mesh_IO)
      subroutine alloc_multi_mesh_group_IO(mesh_IO, mesh_grp_IO)
      subroutine dealloc_multi_mesh_data_IO(mesh_IO)
      subroutine dealloc_multi_mesh_group_IO(mesh_grp_IO)
        type(mul_mesh_geometry), intent(inout) :: mesh_IO
        type(mul_mesh_data), intent(inout) :: mesh_grp_IO
Function/Subroutine Documentation
alloc_multi_mesh_data_io()
subroutine t_read_mesh_data::alloc_multi_mesh_data_io (integer(kind = kint), intent(in) nloop, type(mul_mesh_geometry), intent(inout) mesh_IO)
Definition at line 142 of file t_read_mesh_data.f90.
alloc_multi_mesh_group_io()
subroutine t_read_mesh_data::alloc_multi_mesh_group_io (type(mul_mesh_geometry), intent(in) mesh_IO, type(mul_mesh_groups), intent(inout) mesh_grp_IO)
Definition at line 156 of file t_read_mesh_data.f90.
dealloc_edge_mesh_io()
subroutine t_read_mesh_data::dealloc_edge_mesh_io (type(surf_edge_io_file), intent(inout) edge_mesh_IO)
Definition at line 102 of file t_read_mesh_data.f90.
References t_comm_table::dealloc_comm_table(), t_surf_edge_io::dealloc_edge_connect_io(), t_surf_edge_io::dealloc_surface_connect_io(), and t_geometry_data::deallocate_ele_connect_type().
Referenced by load_element_mesh_data::set_edge_mesh_from_io().
dealloc_ele_geometry_data()
subroutine t_read_mesh_data::dealloc_ele_geometry_data (type(surf_edge_io_file), intent(inout) ele_mesh_IO)
Definition at line 117 of file t_read_mesh_data.f90.
References t_surf_edge_io::dealloc_ele_scalar_io(), and t_geometry_data::dealloc_node_geometry_base().
dealloc_multi_mesh_data_io()
subroutine t_read_mesh_data::dealloc_multi_mesh_data_io (type(mul_mesh_geometry), intent(inout) mesh_IO)
Definition at line 170 of file t_read_mesh_data.f90.
dealloc_multi_mesh_group_io()
subroutine t_read_mesh_data::dealloc_multi_mesh_group_io (type(mul_mesh_groups), intent(inout) mesh_grp_IO)
Definition at line 182 of file t_read_mesh_data.f90.
dealloc_surf_geometry_data()
subroutine t_read_mesh_data::dealloc_surf_geometry_data (type(surf_edge_io_file), intent(inout) surf_mesh_IO)
Definition at line 129 of file t_read_mesh_data.f90.
References t_surf_edge_io::dealloc_ele_scalar_io(), t_surf_edge_io::dealloc_ele_vector_io(), and t_geometry_data::dealloc_node_geometry_base().
dealloc_surface_mesh_io()
subroutine t_read_mesh_data::dealloc_surface_mesh_io (type(surf_edge_io_file), intent(inout) surf_mesh_IO)
Definition at line 89 of file t_read_mesh_data.f90.
References t_comm_table::dealloc_comm_table(), t_surf_edge_io::dealloc_surface_connect_io(), and t_geometry_data::deallocate_ele_connect_type().
Referenced by load_element_mesh_data::set_surface_mesh_from_io().