CALYPSO: set_node_on_edge_quad_psf Module Reference
set_node_on_edge_quad_psf Module Reference
Functions/Subroutines
subroutine set_node_on_edge_int_quad_psf (numnod, numedge, nnod_4_edge, ie_edge, xx, const_psf, psf_list)
subroutine set_node_on_edge_int_linear_psf (numnod, numedge, nnod_4_edge, ie_edge, psf_list)
subroutine, private set_node_on_edge_4_linear_psf (numnod, numedge, nnod_4_edge, ie_edge, ref_fld, nnod_on_edge, istack_n_on_e_smp, iedge_4_nod, coef_on_edge)
subroutine set_node_on_edge_4_quad_psf (numnod, numedge, nnod_4_edge, ie_edge, xx, const_psf, ref_fld, nnod_on_edge, istack_n_on_e_smp, iedge_4_nod, coef_on_edge)
Function/Subroutine Documentation
set_node_on_edge_4_linear_psf()
subroutine, private set_node_on_edge_quad_psf::set_node_on_edge_4_linear_psf (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) numedge, integer(kind = kint), intent(in) nnod_4_edge, integer(kind = kint), dimension(numedge,nnod_4_edge), intent(in) ie_edge, real(kind= kreal), dimension(numnod), intent(in) ref_fld, integer(kind = kint), intent(in) nnod_on_edge, integer(kind = kint), dimension(0:np_smp), intent(in) istack_n_on_e_smp, integer(kind = kint), dimension(nnod_on_edge), intent(in) iedge_4_nod, real(kind= kreal), dimension(nnod_on_edge,2), intent(inout) coef_on_edge) private
Definition at line 85 of file set_node_on_edge_quad_psf.f90.
References m_machine_parameter::np_smp.
Referenced by set_node_on_edge_int_linear_psf().
set_node_on_edge_4_quad_psf()
subroutine set_node_on_edge_quad_psf::set_node_on_edge_4_quad_psf (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) numedge, integer(kind = kint), intent(in) nnod_4_edge, integer(kind = kint), dimension(numedge,nnod_4_edge), intent(in) ie_edge, real(kind = kreal), dimension(numnod,3), intent(in) xx, real(kind = kreal), dimension(10), intent(in) const_psf, real(kind= kreal), dimension(numnod), intent(in) ref_fld, integer(kind = kint), intent(in) nnod_on_edge, integer(kind = kint), dimension(0:np_smp), intent(in) istack_n_on_e_smp, integer(kind = kint), dimension(nnod_on_edge), intent(in) iedge_4_nod, real(kind= kreal), dimension(nnod_on_edge,2), intent(inout) coef_on_edge)
Definition at line 126 of file set_node_on_edge_quad_psf.f90.
References m_constants::four, m_constants::half, m_constants::one, m_constants::two, and m_constants::zero.
Referenced by set_node_on_edge_int_quad_psf().
set_node_on_edge_int_linear_psf()
subroutine set_node_on_edge_quad_psf::set_node_on_edge_int_linear_psf (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) numedge, integer(kind = kint), intent(in) nnod_4_edge, integer(kind = kint), dimension(numedge,nnod_4_edge), intent(in) ie_edge, type(sectioning_list), intent(inout) psf_list)
Definition at line 57 of file set_node_on_edge_quad_psf.f90.
References set_node_on_edge_4_linear_psf().
Referenced by set_nodes_for_psf::set_nodes_4_iso().
set_node_on_edge_int_quad_psf()
subroutine set_node_on_edge_quad_psf::set_node_on_edge_int_quad_psf (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) numedge, integer(kind = kint), intent(in) nnod_4_edge, integer(kind = kint), dimension(numedge,nnod_4_edge), intent(in) ie_edge, real(kind = kreal), dimension(numnod,3), intent(in) xx, real(kind = kreal), dimension(10), intent(in) const_psf, type(sectioning_list), intent(inout) psf_list)
Definition at line 29 of file set_node_on_edge_quad_psf.f90.
References set_node_on_edge_4_quad_psf().
Referenced by set_nodes_for_psf::set_nodes_4_psf().