CALYPSO: gz_ucd_field_file_io_b Module Reference
gz_ucd_field_file_io_b Module Reference
gzipped UCD ascii data IO
Functions/Subroutines
subroutine gz_write_ucd_2_fld_file_b (id_rank, gzip_name, t_IO, ucd)
subroutine gz_read_ucd_2_fld_file_b (id_rank, gzip_name, t_IO, ucd, ierr_IO)
subroutine gz_read_alloc_ucd_2_fld_file_b (id_rank, gzip_name, t_IO, ucd, ierr_IO)
Variables
type(buffer_4_gzip), private zbuf_fu
Detailed Description
gzipped UCD ascii data IO
      subroutine gz_write_ucd_2_fld_file_b                            &
     &         (id_rank, gzip_name, t_IO, ucd)
        type(time_data), intent(in) :: t_IO
        type(ucd_data), intent(in) :: ucd
      subroutine gz_read_ucd_2_fld_file_b                             &
     &         (id_rank, gzip_name, t_IO, ucd, ierr_IO)
      subroutine gz_read_alloc_ucd_2_fld_file_b                       &
     &         (id_rank, gzip_name, t_IO, ucd, ierr)
        type(time_data), intent(inout) :: t_IO
        type(ucd_data), intent(inout) :: ucd
Parameters
id_rank process ID
gzip_name File name
ucd Structure for FEM field data IO
Function/Subroutine Documentation
gz_read_alloc_ucd_2_fld_file_b()
subroutine gz_ucd_field_file_io_b::gz_read_alloc_ucd_2_fld_file_b (integer, intent(in) id_rank, character(len=kchara), intent(in) gzip_name, type(time_data), intent(inout) t_IO, type(ucd_data), intent(inout) ucd, integer(kind = kint), intent(inout) ierr_IO)
Definition at line 128 of file gz_ucd_field_file_IO_b.f90.
References t_ucd_data::allocate_ucd_phys_data(), t_ucd_data::allocate_ucd_phys_name(), t_ucd_data::cal_istack_ucd_component(), gzip_file_access::close_gzfile_b(), gz_field_data_io_b::gz_read_field_data_b(), gz_field_data_io_b::gz_read_step_data_b(), m_machine_parameter::i_debug, and zbuf_fu.
Referenced by ucd_io_select::sel_read_alloc_udt_file(), and ucd_io_select::sel_read_udt_param().
gz_read_ucd_2_fld_file_b()
subroutine gz_ucd_field_file_io_b::gz_read_ucd_2_fld_file_b (integer, intent(in) id_rank, character(len=kchara), intent(in) gzip_name, type(time_data), intent(inout) t_IO, type(ucd_data), intent(inout) ucd, integer(kind = kint), intent(inout) ierr_IO)
Definition at line 82 of file gz_ucd_field_file_IO_b.f90.
References gzip_file_access::close_gzfile_b(), gz_field_data_io_b::gz_read_field_data_b(), gz_field_data_io_b::gz_read_step_data_b(), m_machine_parameter::i_debug, and zbuf_fu.
Referenced by ucd_io_select::sel_read_udt_file().
gz_write_ucd_2_fld_file_b()
subroutine gz_ucd_field_file_io_b::gz_write_ucd_2_fld_file_b (integer, intent(in) id_rank, character(len=kchara), intent(in) gzip_name, type(time_data), intent(in) t_IO, type(ucd_data), intent(in) ucd)
Definition at line 50 of file gz_ucd_field_file_IO_b.f90.
References gzip_file_access::close_gzfile_b(), gz_field_data_io_b::gz_write_field_data_b(), gz_field_data_io_b::gz_write_step_data_b(), m_machine_parameter::i_debug, and zbuf_fu.
Referenced by ucd_io_select::sel_write_ucd_file(), and ucd_io_select::sel_write_udt_file().
Variable Documentation
zbuf_fu
type(buffer_4_gzip), private gz_ucd_field_file_io_b::zbuf_fu private
Definition at line 42 of file gz_ucd_field_file_IO_b.f90.
Referenced by gz_read_alloc_ucd_2_fld_file_b(), gz_read_ucd_2_fld_file_b(), and gz_write_ucd_2_fld_file_b().