CALYPSO: /home/takumi kera/calypso/src/programs/data_utilities/MERGE/main_assemble_sph.f90 File Reference
main_assemble_sph.f90 File Reference
program assemble_sph
Functions/Subroutines
program assemble_sph
Main program for assemble spectr data.
Detailed Description
program assemble_sph
Author
H. Matsui
Date
Programmed by H. Matsui in July 2014
Definition in file main_assemble_sph.f90.
Function/Subroutine Documentation
assemble_sph()
program assemble_sph
Main program for assemble spectr data.
Definition at line 9 of file main_assemble_sph.f90.
References analyzer_assemble_sph::analyze_assemble_sph(), calypso_mpi::calypso_mpi_finalize(), calypso_mpi::calypso_mpi_init(), and analyzer_assemble_sph::init_assemble_sph().