CALYPSO: t_pickup_sph_spectr_data Module Reference
t_pickup_sph_spectr_data Module Reference
Data arrays to monitoring spectrum data.
Data Types
type picked_spectrum_data
Structure for picked spectr data.
type pickup_mode_list
Structure for pickup list.
Functions/Subroutines
subroutine alloc_pick_sph_mode (list_pick)
subroutine alloc_pick_sph_l (list_pick)
subroutine alloc_pick_sph_m (list_pick)
subroutine alloc_num_pick_layer (picked)
subroutine alloc_pickup_sph_spec_local (nprocs, picked)
subroutine dealloc_pickup_sph_spec_local (picked)
subroutine alloc_pick_sph_monitor (picked)
subroutine alloc_gauss_coef_monitor_lc (gauss)
subroutine dealloc_gauss_coef_monitor_lc (gauss)
subroutine dealloc_pick_sph_mode (list_pick)
subroutine dealloc_num_pick_layer (picked)
subroutine dealloc_pick_sph_monitor (picked)
subroutine write_pick_sph_file_header (id_file, picked)
character(len=len_head) function pick_sph_header_no_field (picked)
Detailed Description
Data arrays to monitoring spectrum data.
      subroutine alloc_pick_sph_mode(list_pick)
      subroutine alloc_pick_sph_l(list_pick)
      subroutine alloc_pick_sph_m(list_pick)
      subroutine alloc_num_pick_layer(picked)
      subroutine alloc_pick_sph_monitor(picked)
      subroutine dealloc_pick_sph_mode(list_pick)
      subroutine dealloc_num_pick_layer(picked)
      subroutine dealloc_pick_sph_monitor(picked)
Parameters
i_step time step
time time
id_pick file ID
ierr Error flag (0:success, 1:error)
Function/Subroutine Documentation
alloc_gauss_coef_monitor_lc()
subroutine t_pickup_sph_spectr_data::alloc_gauss_coef_monitor_lc (type(picked_spectrum_data), intent(inout) gauss)
Definition at line 203 of file t_pickup_sph_spectr_data.f90.
Referenced by pickup_gauss_coefficients::init_gauss_coefs_4_monitor().
alloc_num_pick_layer()
subroutine t_pickup_sph_spectr_data::alloc_num_pick_layer (type(picked_spectrum_data), intent(inout) picked)
Definition at line 135 of file t_pickup_sph_spectr_data.f90.
Referenced by pickup_sph_coefs::init_sph_radial_monitor_list(), set_control_4_pickup_sph::set_ctl_params_pick_gauss(), and set_control_4_pickup_sph::set_ctl_params_pick_sph().
alloc_pick_sph_l()
subroutine t_pickup_sph_spectr_data::alloc_pick_sph_l (type(pickup_mode_list), intent(inout) list_pick)
Definition at line 111 of file t_pickup_sph_spectr_data.f90.
Referenced by pickup_gauss_coefficients::init_gauss_coefs_4_monitor(), pickup_sph_spectr_data::init_sph_spec_4_monitor(), set_control_4_pickup_sph::set_ctl_params_pick_gauss(), and set_control_4_pickup_sph::set_ctl_params_pick_sph().
alloc_pick_sph_m()
subroutine t_pickup_sph_spectr_data::alloc_pick_sph_m (type(pickup_mode_list), intent(inout) list_pick)
Definition at line 123 of file t_pickup_sph_spectr_data.f90.
Referenced by set_control_4_pickup_sph::set_ctl_params_pick_gauss(), and set_control_4_pickup_sph::set_ctl_params_pick_sph().
alloc_pick_sph_mode()
subroutine t_pickup_sph_spectr_data::alloc_pick_sph_mode (type(pickup_mode_list), intent(inout) list_pick)
Definition at line 99 of file t_pickup_sph_spectr_data.f90.
Referenced by set_control_4_pickup_sph::set_ctl_params_pick_gauss(), and set_control_4_pickup_sph::set_ctl_params_pick_sph().
alloc_pick_sph_monitor()
subroutine t_pickup_sph_spectr_data::alloc_pick_sph_monitor (type(picked_spectrum_data), intent(inout) picked)
Definition at line 185 of file t_pickup_sph_spectr_data.f90.
Referenced by pickup_sph_spectr::const_picked_sph_address(), and pickup_gauss_coefficients::init_gauss_coefs_4_monitor().
alloc_pickup_sph_spec_local()
subroutine t_pickup_sph_spectr_data::alloc_pickup_sph_spec_local (integer, intent(in) nprocs, type(picked_spectrum_data), intent(inout) picked)
Definition at line 151 of file t_pickup_sph_spectr_data.f90.
Referenced by pickup_sph_spectr::const_picked_sph_address().
dealloc_gauss_coef_monitor_lc()
subroutine t_pickup_sph_spectr_data::dealloc_gauss_coef_monitor_lc (type(picked_spectrum_data), intent(inout) gauss)
Definition at line 214 of file t_pickup_sph_spectr_data.f90.
dealloc_num_pick_layer()
subroutine t_pickup_sph_spectr_data::dealloc_num_pick_layer (type(picked_spectrum_data), intent(inout) picked)
Definition at line 238 of file t_pickup_sph_spectr_data.f90.
dealloc_pick_sph_mode()
subroutine t_pickup_sph_spectr_data::dealloc_pick_sph_mode (type(pickup_mode_list), intent(inout) list_pick)
Definition at line 226 of file t_pickup_sph_spectr_data.f90.
Referenced by pickup_sph_spectr::const_picked_sph_address(), and pickup_gauss_coefficients::init_gauss_coefs_4_monitor().
dealloc_pick_sph_monitor()
subroutine t_pickup_sph_spectr_data::dealloc_pick_sph_monitor (type(picked_spectrum_data), intent(inout) picked)
Definition at line 249 of file t_pickup_sph_spectr_data.f90.
dealloc_pickup_sph_spec_local()
subroutine t_pickup_sph_spectr_data::dealloc_pickup_sph_spec_local (type(picked_spectrum_data), intent(inout) picked)
Definition at line 173 of file t_pickup_sph_spectr_data.f90.
pick_sph_header_no_field()
character(len = len_head) function t_pickup_sph_spectr_data::pick_sph_header_no_field (type(picked_spectrum_data), intent(in) picked)
Definition at line 289 of file t_pickup_sph_spectr_data.f90.
References m_monitor_file_labels::hd_pick_sph_head(), m_monitor_file_labels::hd_pick_sph_num(), and m_monitor_file_labels::hd_time_sph_label().
Referenced by mpi_picked_sph_spectr_io::write_picked_specr_head_mpi().
write_pick_sph_file_header()
subroutine t_pickup_sph_spectr_data::write_pick_sph_file_header (integer(kind = kint), intent(in) id_file, type(picked_spectrum_data), intent(in) picked)
Definition at line 262 of file t_pickup_sph_spectr_data.f90.
References write_field_labels::write_multi_labels().
Referenced by mpi_picked_sph_spectr_io::write_picked_spectr_header_only().