CALYPSO: set_control_field_data Module Reference
set_control_field_data Module Reference
Ordering field data by visualization flag.
Functions/Subroutines
subroutine s_set_control_field_data (field_ctl, fld, ierr)
subroutine set_control_field_by_comp_viz (field_ctl, fld, ierr)
subroutine init_field_data (n_point, fld, iphys)
Variables
integer(kind=kint), parameter, private id_std = 6
Detailed Description
Ordering field data by visualization flag.
      subroutine s_set_control_field_data(field_ctl, fld, ierr)
      subroutine set_control_field_by_comp_viz(field_ctl, fld, ierr)
        type(ctl_array_c3), intent(in) :: field_ctl
        type(phys_data), intent(inout) :: fld
      subroutine init_field_data(n_point, fld, iphys)
        type(phys_data), intent(inout) :: fld
        type(phys_address), intent(inout) :: iphys
        type(SGS_model_addresses), intent(inout) :: iphys_LES
Parameters
fld structure of field data
iphys structure of field addresses
Function/Subroutine Documentation
init_field_data()
subroutine set_control_field_data::init_field_data (integer(kind = kint), intent(in) n_point, type(phys_data), intent(inout) fld, type(phys_address), intent(inout) iphys)
Definition at line 108 of file set_control_field_data.f90.
References t_phys_data::alloc_phys_data_type(), set_mhd_field_address::set_mhd_field_addresses(), and set_mhd_field_address::set_old_mhd_field_addresses().
Referenced by fem_analyzer_sph_mhd::fem_initialize_sph_mhd(), check_dependency_for_mhd::set_sph_mhd_sprctr_data(), and sph_analyzer_add_initial::sph_add_initial_field().
s_set_control_field_data()
subroutine set_control_field_data::s_set_control_field_data (type(ctl_array_c3), intent(in) field_ctl, type(phys_data), intent(inout) fld, integer (kind = kint), intent(inout) ierr)
Definition at line 47 of file set_control_field_data.f90.
References t_phys_data::check_nodal_field_name(), m_machine_parameter::e_message, id_std, m_error_ids::ierr_file, m_machine_parameter::iflag_debug, m_machine_parameter::iflag_routine_msg, and set_nodal_field_name::ordering_field_by_viz().
Referenced by set_control_sph_data_mhd::set_control_sph_mhd_fields(), and set_control_sph_mhd::set_control_sph_mhd_w_viz().
set_control_field_by_comp_viz()
subroutine set_control_field_data::set_control_field_by_comp_viz (type(ctl_array_c3), intent(in) field_ctl, type(phys_data), intent(inout) fld, integer (kind = kint), intent(inout) ierr)
Definition at line 77 of file set_control_field_data.f90.
References t_phys_data::check_nodal_field_name(), m_machine_parameter::e_message, id_std, m_error_ids::ierr_file, m_machine_parameter::iflag_debug, m_machine_parameter::iflag_routine_msg, and set_nodal_field_name::ordering_field_by_comp_viz().
Variable Documentation
id_std
integer(kind = kint), parameter, private set_control_field_data::id_std = 6 private
Definition at line 39 of file set_control_field_data.f90.
Referenced by s_set_control_field_data(), and set_control_field_by_comp_viz().