CALYPSO: t_mhd_step_parameter Module Reference
t_mhd_step_parameter Module Reference
Parameteres for time steppings.
Data Types
type mhd_step_param
Functions/Subroutines
subroutine s_set_control_4_time_steps (mr_ctl, tctl, MHD_step)
subroutine set_fixed_time_step_controls (tctl, MHD_step)
subroutine set_flex_time_step_controls (tctl, MHD_step)
Detailed Description
Parameteres for time steppings.
Function/Subroutine Documentation
s_set_control_4_time_steps()
subroutine t_mhd_step_parameter::s_set_control_4_time_steps (type(mhd_restart_control), intent(in) mr_ctl, type(time_data_control), intent(in) tctl, type(mhd_step_param), intent(inout) MHD_step)
Definition at line 68 of file t_MHD_step_parameter.f90.
References t_flex_delta_t_parameter::iflag_fixed_step, t_flex_delta_t_parameter::iflag_flex_step, t_flex_delta_t_parameter::set_control_flex_time_steps(), set_fixed_time_step_controls(), set_flex_time_step_controls(), m_initial_field_control::set_initial_field_id(), and skip_comment_f::yes_flag().
Referenced by set_control_sph_mhd::set_control_4_sph_mhd().
set_fixed_time_step_controls()
subroutine t_mhd_step_parameter::set_fixed_time_step_controls (type(time_data_control), intent(in) tctl, type(mhd_step_param), intent(inout) MHD_step)
Definition at line 140 of file t_MHD_step_parameter.f90.
References t_io_step_parameter::output_step_4_fixed_step_ctl(), set_time_step_params::s_set_fixed_time_step_params(), and t_viz_step_parameter::viz_fixed_time_step_params().
Referenced by s_set_control_4_time_steps().
set_flex_time_step_controls()
subroutine t_mhd_step_parameter::set_flex_time_step_controls (type(time_data_control), intent(in) tctl, type(mhd_step_param), intent(inout) MHD_step)
Definition at line 183 of file t_MHD_step_parameter.f90.
References t_io_step_parameter::output_step_4_flex_step_ctl(), t_flex_delta_t_parameter::set_flex_time_step_params(), and t_viz_step_parameter::viz_flex_time_step_controls().
Referenced by s_set_control_4_time_steps().