CALYPSO: t_ctl_data_4_sphere_model Module Reference
t_ctl_data_4_sphere_model Module Reference
Data Types
type sphere_data_control
control data structure for spherical shell
Functions/Subroutines
subroutine read_control_shell_define (id_control, hd_block, spctl, c_buf)
subroutine dealloc_control_shell_define (spctl)
subroutine reset_control_shell_define (spctl)
Variables
character(len=kchara), parameter, private hd_numlayer_shell = 'r_layer'
character(len=kchara), parameter, private hd_ntheta_shell = 'ngrid_meridonal_ctl'
character(len=kchara), parameter, private hd_nphi_shell = 'ngrid_zonal_ctl'
character(len=kchara), parameter, private hd_sph_truncate = 'truncation_level_ctl'
character(len=kchara), parameter, private hd_phi_symmetry = 'longitude_symmetry_ctl'
character(len=kchara), parameter, private hd_sph_c_type = 'sph_coef_type_ctl'
character(len=kchara), parameter hd_sph_g_type = 'sph_grid_type_ctl'
character(len=kchara), parameter, private hd_r_grid_type = 'radial_grid_type_ctl'
character(len=kchara), parameter, private hd_n_fluid_grid = 'num_fluid_grid_ctl'
character(len=kchara), parameter hd_cheby_increment = 'increment_of_chebyshev'
character(len=kchara), parameter, private hd_min_radius = 'Min_radius_ctl'
character(len=kchara), parameter, private hd_icb_radius = 'ICB_radius_ctl'
character(len=kchara), parameter, private hd_cmb_radius = 'CMB_radius_ctl'
character(len=kchara), parameter, private hd_max_radius = 'Max_radius_ctl'
character(len=kchara), parameter, private hd_shell_size = 'fluid_core_size_ctl'
character(len=kchara), parameter, private hd_shell_ratio = 'ICB_to_CMB_ratio_ctl'
character(len=kchara), parameter, private hd_bc_sph = 'boundaries_ctl'
character(len=kchara), parameter hd_num_radial_grp = 'num_radial_layering_ctl'
character(len=kchara), parameter hd_num_med_grp = 'num_meridional_layering_ctl'
character(len=kchara), parameter hd_list_radial_grp = 'radial_layering_ctl'
character(len=kchara), parameter hd_list_med_grp = 'meridional_layering_ctl'
Function/Subroutine Documentation
dealloc_control_shell_define()
subroutine t_ctl_data_4_sphere_model::dealloc_control_shell_define (type(sphere_data_control), intent(inout) spctl)
Definition at line 303 of file t_ctl_data_4_sphere_model.f90.
References t_control_array_charaint::dealloc_control_array_c_i(), t_control_array_integer2::dealloc_control_array_i2(), and t_control_array_intreal::dealloc_control_array_i_r().
Referenced by t_ctl_data_gen_sph_shell::dealloc_parallel_shell_ctl().
read_control_shell_define()
subroutine t_ctl_data_4_sphere_model::read_control_shell_define (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(sphere_data_control), intent(inout) spctl, type(buffer_for_control), intent(inout) c_buf)
Definition at line 223 of file t_ctl_data_4_sphere_model.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_bc_sph, hd_cheby_increment, hd_cmb_radius, hd_icb_radius, hd_list_med_grp, hd_list_radial_grp, hd_max_radius, hd_min_radius, hd_n_fluid_grid, hd_nphi_shell, hd_ntheta_shell, hd_num_med_grp, hd_num_radial_grp, hd_numlayer_shell, hd_phi_symmetry, hd_r_grid_type, hd_shell_ratio, hd_shell_size, hd_sph_c_type, hd_sph_g_type, hd_sph_truncate, t_read_control_elements::load_one_line_from_control(), t_control_array_character::read_chara_ctl_type(), t_control_array_charaint::read_control_array_c_i(), t_control_array_integer2::read_control_array_i2(), t_control_array_intreal::read_control_array_i_r(), t_control_array_integer::read_integer_ctl_type(), and t_control_array_real::read_real_ctl_type().
Referenced by t_ctl_data_gen_sph_shell::read_parallel_shell_ctl().
reset_control_shell_define()
subroutine t_ctl_data_4_sphere_model::reset_control_shell_define (type(sphere_data_control), intent(inout) spctl)
Definition at line 317 of file t_ctl_data_4_sphere_model.f90.
Referenced by t_ctl_params_gen_sph_shell::set_control_4_gen_shell_grids().
Variable Documentation
hd_bc_sph
character(len=kchara), parameter, private t_ctl_data_4_sphere_model::hd_bc_sph = 'boundaries_ctl' private
Definition at line 199 of file t_ctl_data_4_sphere_model.f90.
Referenced by read_control_shell_define().
hd_cheby_increment
character(len=kchara), parameter t_ctl_data_4_sphere_model::hd_cheby_increment = 'increment_of_chebyshev'
Definition at line 184 of file t_ctl_data_4_sphere_model.f90.
Referenced by read_control_shell_define().
hd_cmb_radius
character(len=kchara), parameter, private t_ctl_data_4_sphere_model::hd_cmb_radius = 'CMB_radius_ctl' private
Definition at line 190 of file t_ctl_data_4_sphere_model.f90.
Referenced by read_control_shell_define().
hd_icb_radius
character(len=kchara), parameter, private t_ctl_data_4_sphere_model::hd_icb_radius = 'ICB_radius_ctl' private
Definition at line 188 of file t_ctl_data_4_sphere_model.f90.
Referenced by read_control_shell_define().
hd_list_med_grp
character(len=kchara), parameter t_ctl_data_4_sphere_model::hd_list_med_grp = 'meridional_layering_ctl'
Definition at line 208 of file t_ctl_data_4_sphere_model.f90.
Referenced by read_control_shell_define().
hd_list_radial_grp
character(len=kchara), parameter t_ctl_data_4_sphere_model::hd_list_radial_grp = 'radial_layering_ctl'
Definition at line 206 of file t_ctl_data_4_sphere_model.f90.
Referenced by read_control_shell_define().
hd_max_radius
character(len=kchara), parameter, private t_ctl_data_4_sphere_model::hd_max_radius = 'Max_radius_ctl' private
Definition at line 192 of file t_ctl_data_4_sphere_model.f90.
Referenced by read_control_shell_define().
hd_min_radius
character(len=kchara), parameter, private t_ctl_data_4_sphere_model::hd_min_radius = 'Min_radius_ctl' private
Definition at line 186 of file t_ctl_data_4_sphere_model.f90.
Referenced by read_control_shell_define().
hd_n_fluid_grid
character(len=kchara), parameter, private t_ctl_data_4_sphere_model::hd_n_fluid_grid = 'num_fluid_grid_ctl' private
Definition at line 182 of file t_ctl_data_4_sphere_model.f90.
Referenced by read_control_shell_define().
hd_nphi_shell
character(len=kchara), parameter, private t_ctl_data_4_sphere_model::hd_nphi_shell = 'ngrid_zonal_ctl' private
Definition at line 169 of file t_ctl_data_4_sphere_model.f90.
Referenced by read_control_shell_define().
hd_ntheta_shell
character(len=kchara), parameter, private t_ctl_data_4_sphere_model::hd_ntheta_shell = 'ngrid_meridonal_ctl' private
Definition at line 167 of file t_ctl_data_4_sphere_model.f90.
Referenced by read_control_shell_define().
hd_num_med_grp
character(len=kchara), parameter t_ctl_data_4_sphere_model::hd_num_med_grp = 'num_meridional_layering_ctl'
Definition at line 204 of file t_ctl_data_4_sphere_model.f90.
Referenced by read_control_shell_define().
hd_num_radial_grp
character(len=kchara), parameter t_ctl_data_4_sphere_model::hd_num_radial_grp = 'num_radial_layering_ctl'
Definition at line 202 of file t_ctl_data_4_sphere_model.f90.
Referenced by read_control_shell_define().
hd_numlayer_shell
character(len=kchara), parameter, private t_ctl_data_4_sphere_model::hd_numlayer_shell = 'r_layer' private
Definition at line 164 of file t_ctl_data_4_sphere_model.f90.
Referenced by read_control_shell_define().
hd_phi_symmetry
character(len=kchara), parameter, private t_ctl_data_4_sphere_model::hd_phi_symmetry = 'longitude_symmetry_ctl' private
Definition at line 173 of file t_ctl_data_4_sphere_model.f90.
Referenced by read_control_shell_define().
hd_r_grid_type
character(len=kchara), parameter, private t_ctl_data_4_sphere_model::hd_r_grid_type = 'radial_grid_type_ctl' private
Definition at line 180 of file t_ctl_data_4_sphere_model.f90.
Referenced by read_control_shell_define().
hd_shell_ratio
character(len=kchara), parameter, private t_ctl_data_4_sphere_model::hd_shell_ratio = 'ICB_to_CMB_ratio_ctl' private
Definition at line 196 of file t_ctl_data_4_sphere_model.f90.
Referenced by read_control_shell_define().
hd_shell_size
character(len=kchara), parameter, private t_ctl_data_4_sphere_model::hd_shell_size = 'fluid_core_size_ctl' private
Definition at line 194 of file t_ctl_data_4_sphere_model.f90.
Referenced by read_control_shell_define().
hd_sph_c_type
character(len=kchara), parameter, private t_ctl_data_4_sphere_model::hd_sph_c_type = 'sph_coef_type_ctl' private
Definition at line 175 of file t_ctl_data_4_sphere_model.f90.
Referenced by read_control_shell_define().
hd_sph_g_type
character(len=kchara), parameter t_ctl_data_4_sphere_model::hd_sph_g_type = 'sph_grid_type_ctl'
Definition at line 177 of file t_ctl_data_4_sphere_model.f90.
Referenced by read_control_shell_define().
hd_sph_truncate
character(len=kchara), parameter, private t_ctl_data_4_sphere_model::hd_sph_truncate = 'truncation_level_ctl' private
Definition at line 171 of file t_ctl_data_4_sphere_model.f90.
Referenced by read_control_shell_define().