CALYPSO: share_field_data Module Reference
share_field_data Module Reference
Construct spectrum data for new spectrum domain.
Functions/Subroutines
subroutine share_time_step_data (time_d)
subroutine share_phys_field_names (fld)
subroutine share_each_field_data (ip_org, fld)
subroutine share_field_io_names (ip_org, fld_IO)
subroutine share_each_field_io_data (ip_org, fld_IO)
subroutine share_field_num (num_field, ntot_component)
subroutine share_field_stack (num_field, istack_comp, fld_name)
Detailed Description
Construct spectrum data for new spectrum domain.
      subroutine share_time_step_data(time_d)
        type(time_data), intent(inout) :: time_d
      subroutine share_phys_field_names(fld)
      subroutine share_each_field_data(ip_org, fld)
        type(phys_data), intent(inout) :: fld
      subroutine share_field_IO_names(fld_IO)
      subroutine share_each_field_IO_data(ip_org, fld_IO)
        type(field_IO), intent(inout) :: fld_IO
Function/Subroutine Documentation
share_each_field_data()
subroutine share_field_data::share_each_field_data (integer(kind = kint), intent(in) ip_org, type(phys_data), intent(inout) fld)
Definition at line 80 of file share_field_data.f90.
References t_phys_data::alloc_phys_data_type(), calypso_mpi_int::calypso_mpi_bcast_one_int(), calypso_mpi_real::calypso_mpi_bcast_real(), calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by analyzer_assemble_sph::analyze_assemble_sph(), and analyzer_compare_sph_rst::analyze_compare_sph_restart().
share_each_field_io_data()
subroutine share_field_data::share_each_field_io_data (integer(kind = kint), intent(in) ip_org, type(field_io), intent(inout) fld_IO)
Definition at line 145 of file share_field_data.f90.
References t_field_data_io::alloc_phys_data_io(), calypso_mpi_int::calypso_mpi_bcast_one_int(), calypso_mpi_real::calypso_mpi_bcast_real(), calypso_mpi::my_rank, and calypso_mpi::nprocs.
share_field_io_names()
subroutine share_field_data::share_field_io_names (integer(kind = kint), intent(in) ip_org, type(field_io), intent(inout) fld_IO)
Definition at line 109 of file share_field_data.f90.
References t_field_data_io::alloc_phys_name_io(), calypso_mpi_char::calypso_mpi_bcast_character(), calypso_mpi_int::calypso_mpi_bcast_int(), calypso_mpi_int::calypso_mpi_bcast_one_int(), transfer_to_long_integers::cast_long(), m_precision::kchara, calypso_mpi::my_rank, calypso_mpi::nprocs, and cal_minmax_and_stacks::s_cal_numbers_from_stack().
share_field_num()
subroutine share_field_data::share_field_num (integer(kind = kint), intent(inout) num_field, integer(kind = kint), intent(inout) ntot_component)
Definition at line 173 of file share_field_data.f90.
References calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by share_phys_field_names().
share_field_stack()
subroutine share_field_data::share_field_stack (integer(kind = kint), intent(in) num_field, integer(kind = kint), dimension(0:num_field), intent(inout) istack_comp, character(len=kchara), dimension(num_field), intent(inout) fld_name)
Definition at line 187 of file share_field_data.f90.
References calypso_mpi_char::calypso_mpi_bcast_character(), calypso_mpi_int::calypso_mpi_bcast_int(), transfer_to_long_integers::cast_long(), and m_precision::kchara.
Referenced by share_phys_field_names().
share_phys_field_names()
subroutine share_field_data::share_phys_field_names (type(phys_data), intent(inout) fld)
Definition at line 55 of file share_field_data.f90.
References t_phys_data::alloc_phys_name_type(), calypso_mpi_logical::calypso_mpi_bcast_logical(), transfer_to_long_integers::cast_long(), calypso_mpi::my_rank, cal_minmax_and_stacks::s_cal_numbers_from_stack(), share_field_num(), and share_field_stack().
Referenced by assemble_sph_fields::share_new_spectr_field_names(), and assemble_sph_fields::share_org_spectr_field_names().
share_time_step_data()
subroutine share_field_data::share_time_step_data (type(time_data), intent(inout) time_d)
Definition at line 37 of file share_field_data.f90.
References calypso_mpi_int::calypso_mpi_bcast_one_int(), and calypso_mpi_real::calypso_mpi_bcast_one_real().
Referenced by analyzer_assemble_sph::analyze_assemble_sph(), analyzer_compare_sph_rst::analyze_compare_sph_restart(), and analyzer_rayleigh_cvt_sph::analyze_cvt_rayleigh_sph().