CALYPSO: select_calypso_sr Module Reference
select_calypso_sr Module Reference
Select communication routines for spherical harmonics transform.
Functions/Subroutines
subroutine sel_calypso_send_recv_n (iflag_SR, NB, nnod_org, nnod_new, npe_send, isend_self, id_pe_send, istack_send, inod_export, npe_recv, irecv_self, id_pe_recv, istack_recv, inod_import, irev_import, X_org, X_new)
subroutine sel_calypso_send_recv_3xn (iflag_SR, NB, nnod_org, nnod_new, npe_send, isend_self, id_pe_send, istack_send, inod_export, npe_recv, irecv_self, id_pe_recv, istack_recv, inod_import, irev_import, X1_org, X2_org, X3_org, X1_new, X2_new, X3_new)
subroutine finish_calypso_send_recv (npe_send, isend_self)
subroutine check_calypso_send_recv_n (NB, npe_send, isend_self, istack_send, npe_recv, irecv_self, istack_recv)
Detailed Description
Select communication routines for spherical harmonics transform.
      subroutine sel_calypso_send_recv_N(iflag_SR,                    &
     &                         NB, nnod_org, nnod_new,                &
     &                         npe_send, isend_self,                  &
     &                         id_pe_send, istack_send, inod_export,  &
     &                         npe_recv, irecv_self,                  &
     &                         id_pe_recv, istack_recv, inod_import,  &
     &                         irev_import, X_org, X_new)
      subroutine sel_calypso_send_recv_3xN(iflag_SR,                  &
     &                         NB, nnod_org, nnod_new,                &
     &                         npe_send, isend_self,                  &
     &                         id_pe_send, istack_send, inod_export,  &
     &                         npe_recv, irecv_self,                  &
     &                         id_pe_recv, istack_recv, inod_import,  &
     &                         irev_import, X1_org, X2_org, X3_org,   &
     &                                      X1_new, X2_new, X3_new)
      subroutine finish_calypso_send_recv(npe_send, isend_self)
      subroutine check_calypso_send_recv_N                            &
     &         (NB, npe_send, isend_self, istack_send,                &
     &              npe_recv, irecv_self, istack_recv)
Parameters
NB Number of components for communication
nnod_org Number of data points for origin
nnod_new Number of components for destination
npe_send Number of processses to send
isend_self Integer flag to copy within own process
id_pe_send(npe_send) Process ID to send
istack_send(0:npe_send) End points of send buffer for each process
inod_export(istack_send(npe_send)) local node ID to copy in send buffer
npe_recv Number of processses to receive
irecv_self Integer flag to copy within own process
id_pe_recv(npe_send) Process ID to receive
istack_recv(0:npe_send) End points of receive buffer for each process
inod_import(istack_recv(npe_recv)) local node ID to copy from receive buffer
irev_import(nnod_new) import buffer ID for each data point
X_org(NB*nnod_org) Arbitrary components of send data
X_new(NB*nnod_new) Arbitrary components of received data
X_org(6*nnod_org) Six components of send data
X_new(6*nnod_new) Six components of received data
X_org(3*nnod_org) Three components of send data
X_new(3*nnod_new) Three components of received data
X_org(2*nnod_org) Two components of send data
X_new(2*nnod_new) Two components of received data
X_org(nnod_org) Scalar send data
X_new(nnod_new) Scalar received data
iX_org(nnod_org) Integer send data
iX_new(nnod_new) Integer received data
Function/Subroutine Documentation
check_calypso_send_recv_n()
subroutine select_calypso_sr::check_calypso_send_recv_n (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) npe_send, integer(kind = kint), intent(in) isend_self, integer(kind = kint), dimension(0:npe_send), intent(in) istack_send, integer(kind = kint), intent(in) npe_recv, integer(kind = kint), intent(in) irecv_self, integer(kind = kint), dimension(0:npe_recv), intent(in) istack_recv)
Definition at line 231 of file select_calypso_SR.f90.
References calypso_sr_core::calypso_send_recv_check(), and m_solver_sr::resize_work_4_sr().
finish_calypso_send_recv()
subroutine select_calypso_sr::finish_calypso_send_recv (integer(kind = kint), intent(in) npe_send, integer(kind = kint), intent(in) isend_self)
Definition at line 216 of file select_calypso_SR.f90.
References calypso_sr_core::calypso_send_recv_fin().
Referenced by spherical_srs_n::finish_send_recv_sph(), sel_calypso_send_recv_3xn(), and calypso_solver_sr::solver_send_recv_n().
sel_calypso_send_recv_3xn()
subroutine select_calypso_sr::sel_calypso_send_recv_3xn (integer(kind = kint), intent(in) iflag_SR, integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) npe_send, integer(kind = kint), intent(in) isend_self, integer(kind = kint), dimension(npe_send), intent(in) id_pe_send, integer(kind = kint), dimension(0:npe_send), intent(in) istack_send, integer(kind = kint), dimension(istack_send(npe_send)), intent(in) inod_export, integer(kind = kint), intent(in) npe_recv, integer(kind = kint), intent(in) irecv_self, integer(kind = kint), dimension(npe_recv), intent(in) id_pe_recv, integer(kind = kint), dimension(0:npe_recv), intent(in) istack_recv, integer(kind = kint), dimension(istack_recv(npe_recv)), intent(in) inod_import, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, real (kind=kreal), dimension(nb*nnod_org), intent(in) X1_org, real (kind=kreal), dimension(nb*nnod_org), intent(in) X2_org, real (kind=kreal), dimension(nb*nnod_org), intent(in) X3_org, real (kind=kreal), dimension(nb*nnod_new), intent(inout) X1_new, real (kind=kreal), dimension(nb*nnod_new), intent(inout) X2_new, real (kind=kreal), dimension(nb*nnod_new), intent(inout) X3_new)
Definition at line 146 of file select_calypso_SR.f90.
References calypso_sr_n::calypso_send_recv_3xn(), calypso_sr_rev_n::calypso_send_recv_rev_3xn(), finish_calypso_send_recv(), select_copy_from_recv::iflag_import_rev, and m_solver_sr::resize_work_4_sr().
sel_calypso_send_recv_n()
subroutine select_calypso_sr::sel_calypso_send_recv_n (integer(kind = kint), intent(in) iflag_SR, integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) npe_send, integer(kind = kint), intent(in) isend_self, integer(kind = kint), dimension(npe_send), intent(in) id_pe_send, integer(kind = kint), dimension(0:npe_send), intent(in) istack_send, integer(kind = kint), dimension(istack_send(npe_send)), intent(in) inod_export, integer(kind = kint), intent(in) npe_recv, integer(kind = kint), intent(in) irecv_self, integer(kind = kint), dimension(npe_recv), intent(in) id_pe_recv, integer(kind = kint), dimension(0:npe_recv), intent(in) istack_recv, integer(kind = kint), dimension(istack_recv(npe_recv)), intent(in) inod_import, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, real (kind=kreal), dimension(nb*nnod_org), intent(in) X_org, real (kind=kreal), dimension(nb*nnod_new), intent(inout) X_new)
Definition at line 86 of file select_calypso_SR.f90.
References calypso_sr_n::calypso_send_recv_n(), calypso_sr_rev_n::calypso_send_recv_rev_n(), select_copy_from_recv::iflag_import_rev, and m_solver_sr::resize_work_4_sr().
Referenced by calypso_solver_sr::solver_send_recv_n().