CALYPSO: patch_4_psf Module Reference
patch_4_psf Module Reference
Routines to make triangle patich list.
Functions/Subroutines
subroutine set_psf_type_id (ele, numnod, ele_search, mark_ele, c_ref)
subroutine count_num_patch_4_psf (edge, psf_list, ele_search, mark_ele, num_case_tbl, psf_case_tbl, istack_patch_smp, ntot_failed)
subroutine set_patch_4_psf (edge, psf_list, ele_search, mark_ele, num_case_tbl, psf_case_tbl, istack_numele, npatch_tot, istack_patch_smp, iele_global, ie_patch)
Detailed Description
Routines to make triangle patich list.
      subroutine set_psf_type_id                                      &
     &         (ele, numnod, ele_search, mark_ele, c_ref)
      subroutine count_num_patch_4_psf(edge, psf_list,                &
     &          ele_search, mark_ele, num_case_tbl, psf_case_tbl,     &
     &          istack_patch_smp, ntot_failed)
      subroutine set_patch_4_psf(edge, psf_list, ele_search, mark_ele,&
     &          num_case_tbl, psf_case_tbl, istack_numele,            &
     &          npatch_tot, istack_patch_smp, iele_global, ie_patch)
        type(element_data), intent(in) :: ele
        type(edge_data), intent(in) :: edge
        type(sectioning_list), intent(in) :: psf_list
        type(psf_each_case), intent(in) :: psf_case_tbl(num_case_tbl)
        type(sect_search_list), intent(in) :: ele_search
Function/Subroutine Documentation
count_num_patch_4_psf()
subroutine patch_4_psf::count_num_patch_4_psf (type(edge_data), intent(in) edge, type(sectioning_list), intent(in) psf_list, type(sect_search_list), intent(in) ele_search, integer(kind = kint), dimension(ele_search%num_search), intent(in) mark_ele, integer(kind=kint), intent(in) num_case_tbl, type(psf_each_case), dimension(0:num_case_tbl), intent(in) psf_case_tbl, integer(kind = kint), dimension(0:np_smp), intent(inout) istack_patch_smp, integer(kind = kint), intent(inout) ntot_failed)
Definition at line 96 of file patch_4_psf.f90.
References m_machine_parameter::i_debug, and calypso_mpi::my_rank.
Referenced by set_patches_for_psf::count_iso_patches(), and set_patches_for_psf::count_psf_patches().
set_patch_4_psf()
subroutine patch_4_psf::set_patch_4_psf (type(edge_data), intent(in) edge, type(sectioning_list), intent(in) psf_list, type(sect_search_list), intent(in) ele_search, integer(kind = kint), dimension(ele_search%num_search), intent(in) mark_ele, integer(kind=kint), intent(in) num_case_tbl, type(psf_each_case), dimension(0:num_case_tbl), intent(in) psf_case_tbl, integer(kind = kint_gl), intent(in) istack_numele, integer(kind = kint), intent(in) npatch_tot, integer(kind = kint), dimension(0:np_smp), intent(in) istack_patch_smp, integer(kind = kint_gl), dimension(npatch_tot), intent(inout) iele_global, integer(kind = kint_gl), dimension(npatch_tot,num_triangle), intent(inout) ie_patch)
Definition at line 176 of file patch_4_psf.f90.
References m_machine_parameter::np_smp.
Referenced by set_patches_for_psf::set_iso_patches(), and set_patches_for_psf::set_psf_patches().
set_psf_type_id()
subroutine patch_4_psf::set_psf_type_id (type(element_data), intent(in) ele, integer(kind = kint), intent(in) numnod, type(sect_search_list), intent(in) ele_search, integer(kind = kint), dimension(ele_search%num_search), intent(inout) mark_ele, real(kind= kreal), dimension(numnod), intent(in) c_ref)
Definition at line 41 of file patch_4_psf.f90.
References m_constants::ione, m_constants::itwo, m_machine_parameter::np_smp, and m_constants::one.
Referenced by set_patches_for_psf::count_iso_patches(), and set_patches_for_psf::count_psf_patches().