CALYPSO: sph_mhd_rst_io_control Module Reference
sph_mhd_rst_io_control Module Reference
I/O routines for restart data.
Functions/Subroutines
subroutine output_sph_restart_control (i_step, fst_file_IO, time_d, rj_fld, rst_step, sph_fst_IO)
subroutine read_alloc_sph_restart_data (fst_file_IO, init_d, rj_fld, rst_step, sph_fst_IO)
subroutine init_radial_sph_interpolation (rj_file_param, sph_params, sph_rj)
subroutine read_alloc_sph_rst_4_snap (i_step, rj_file_param, fst_file_IO, rst_step, sph, ipol, rj_fld, time_d)
subroutine output_spectr_4_snap (i_step, time_d, sph_file_IO, rj_fld, ucd_step)
subroutine read_alloc_sph_spectr (i_step, ucd_step, rj_file_param, sph_file_IO, sph_rj, ipol, rj_fld, time_d)
Variables
type(time_data), save, private sph_time_io
Detailed Description
I/O routines for restart data.
      subroutine output_sph_restart_control(i_step, fst_file_IO,      &
     &         time_d, rj_fld, rst_step, sph_fst_IO)
        type(field_IO_params), intent(in) :: fst_file_IO
        type(phys_data), intent(in) :: rj_fld
        type(IO_step_param), intent(in) :: rst_step
        type(field_IO), intent(in) :: sph_fst_IO
      subroutine read_alloc_sph_restart_data                          &
     &         (fst_file_IO, init_d, rj_fld, rst_step, sph_fst_IO)
        type(time_data), intent(inout) :: init_d
        type(phys_data), intent(inout) :: rj_fld
        type(IO_step_param), intent(inout) :: rst_step
      subroutine init_radial_sph_interpolation                        &
     &         (rj_file_param, sph_params, sph_rj)
      subroutine read_alloc_sph_rst_4_snap(i_step, rj_file_param,     &
     &          fst_file_IO, rst_step, sph, ipol, rj_fld, time_d)
        type(field_IO_params), intent(in) :: rj_file_param
        type(IO_step_param), intent(in) :: rst_step
        type(phys_data), intent(inout) :: rj_fld
      subroutine output_spectr_4_snap(i_step, time_d,                 &
     &          sph_file_IO, rj_fld, ucd_step)
      subroutine read_alloc_sph_spectr                                &
     &         (i_step, ucd_step, rj_file_param, sph_file_IO,         &
     &          sph_rj, ipol, rj_fld, time_d)
        type(field_IO_params), intent(in) :: rj_file_param
        type(field_IO_params), intent(in) :: sph_file_IO
        type(phys_data), intent(in) :: rj_fld
Parameters
i_step time step
Function/Subroutine Documentation
init_radial_sph_interpolation()
subroutine sph_mhd_rst_io_control::init_radial_sph_interpolation (type(field_io_params), intent(in) rj_file_param, type(sph_shell_parameters), intent(inout) sph_params, type(sph_rj_grid), intent(inout) sph_rj)
Definition at line 132 of file sph_mhd_rst_IO_control.f90.
References r_interpolate_sph_data::copy_cmb_icb_radial_point(), m_machine_parameter::iflag_debug, and r_interpolate_sph_data::input_old_rj_sph_trans().
Referenced by sph_analyzer_d_bench::sph_init_sph_dbench(), and sph_analyzer_snap_w_psf::sph_init_sph_snap_psf().
output_spectr_4_snap()
subroutine sph_mhd_rst_io_control::output_spectr_4_snap (integer(kind = kint), intent(in) i_step, type(time_data), intent(in) time_d, type(field_io_params), intent(in) sph_file_IO, type(phys_data), intent(in) rj_fld, type(io_step_param), intent(in) ucd_step)
Definition at line 200 of file sph_mhd_rst_IO_control.f90.
References t_field_data_io::alloc_merged_field_stack(), t_field_data_io::alloc_phys_data_io(), copy_rj_phys_data_4_io::copy_rj_phys_data_to_io(), copy_rj_phys_data_4_io::copy_rj_phys_name_to_io(), t_time_data::copy_time_step_size_data(), const_global_element_ids::count_number_of_node_stack(), t_field_data_io::dealloc_merged_field_stack(), t_field_data_io::dealloc_phys_data_io(), t_field_data_io::dealloc_phys_name_io(), calypso_mpi::nprocs, t_io_step_parameter::output_io_flag(), field_io_select::sel_write_step_sph_field_file(), t_io_step_parameter::set_io_step(), and sph_time_io.
Referenced by sph_analyzer_snap_w_psf::sph_analyze_snap_psf().
output_sph_restart_control()
subroutine sph_mhd_rst_io_control::output_sph_restart_control (integer(kind = kint), intent(in) i_step, type(field_io_params), intent(in) fst_file_IO, type(time_data), intent(in) time_d, type(phys_data), intent(in) rj_fld, type(io_step_param), intent(in) rst_step, type(field_io), intent(inout) sph_fst_IO)
Definition at line 73 of file sph_mhd_rst_IO_control.f90.
References t_time_data::copy_time_step_size_data(), field_io_select::sel_write_step_sph_field_file(), t_io_step_parameter::set_io_step(), set_sph_restart_io::set_sph_restart_data_to_io(), and sph_time_io.
Referenced by sph_analyzer_mhd::sph_analyze_mhd(), set_initial_sph_dynamo::sph_initial_data_control(), and const_sph_initial_spectr::sph_initial_spectrum().
read_alloc_sph_restart_data()
subroutine sph_mhd_rst_io_control::read_alloc_sph_restart_data (type(field_io_params), intent(in) fst_file_IO, type(time_data), intent(inout) init_d, type(phys_data), intent(inout) rj_fld, type(io_step_param), intent(inout) rst_step, type(field_io), intent(inout) sph_fst_IO)
Definition at line 101 of file sph_mhd_rst_IO_control.f90.
References t_time_data::copy_time_step_data(), t_field_data_io::dealloc_phys_data_io(), t_field_data_io::dealloc_phys_name_io(), calypso_mpi::my_rank, calypso_mpi::nprocs, field_io_select::sel_read_alloc_step_sph_file(), t_io_step_parameter::set_io_step(), set_sph_restart_io::set_sph_restart_from_io(), and sph_time_io.
Referenced by sph_analyzer_add_initial::sph_add_initial_field(), and set_initial_sph_dynamo::sph_initial_data_control().
read_alloc_sph_rst_4_snap()
subroutine sph_mhd_rst_io_control::read_alloc_sph_rst_4_snap (integer(kind = kint), intent(in) i_step, type(field_io_params), intent(in) rj_file_param, type(field_io_params), intent(in) fst_file_IO, type(io_step_param), intent(in) rst_step, type(sph_grids), intent(in) sph, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld, type(time_data), intent(inout) time_d)
Definition at line 156 of file sph_mhd_rst_IO_control.f90.
References t_time_data::copy_time_step_data(), t_field_data_io::dealloc_phys_data_io(), t_field_data_io::dealloc_phys_name_io(), m_machine_parameter::iflag_debug, calypso_mpi::my_rank, calypso_mpi::nprocs, r_interpolate_sph_data::r_interpolate_sph_rst_from_io(), field_io_select::sel_read_alloc_step_sph_file(), t_io_step_parameter::set_io_step(), set_sph_restart_io::set_sph_restart_from_io(), and sph_time_io.
Referenced by sph_analyzer_d_bench::sph_analyze_dbench(), and sph_analyzer_snap_w_psf::sph_analyze_snap_psf().
read_alloc_sph_spectr()
subroutine sph_mhd_rst_io_control::read_alloc_sph_spectr (integer(kind = kint), intent(in) i_step, type(io_step_param), intent(in) ucd_step, type(field_io_params), intent(in) rj_file_param, type(field_io_params), intent(in) sph_file_IO, type(sph_rj_grid), intent(in) sph_rj, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld, type(time_data), intent(inout) time_d)
Definition at line 242 of file sph_mhd_rst_IO_control.f90.
References t_time_data::copy_time_step_data(), t_field_data_io::dealloc_phys_data_io(), t_field_data_io::dealloc_phys_name_io(), m_machine_parameter::iflag_debug, calypso_mpi::my_rank, calypso_mpi::nprocs, r_interpolate_sph_data::r_interpolate_sph_fld_from_io(), field_io_select::sel_read_alloc_step_sph_file(), t_io_step_parameter::set_io_step(), copy_rj_phys_data_4_io::set_rj_phys_data_from_io(), and sph_time_io.
Variable Documentation
sph_time_io
type(time_data), save, private sph_mhd_rst_io_control::sph_time_io private
Definition at line 65 of file sph_mhd_rst_IO_control.f90.
Referenced by output_spectr_4_snap(), output_sph_restart_control(), read_alloc_sph_restart_data(), read_alloc_sph_rst_4_snap(), and read_alloc_sph_spectr().