CALYPSO: edge_data_io Module Reference
edge_data_io Module Reference
data IO orutines for edge
Functions/Subroutines
subroutine read_edge_connection (id_file, id_rank, comm_IO, ele_IO, sfed_IO, ierr)
subroutine write_edge_connection (id_file, id_rank, comm_IO, ele_IO, sfed_IO)
subroutine read_edge_geometry (id_file, nod_IO, sfed_IO)
subroutine write_edge_geometry (id_file, nod_IO, sfed_IO)
subroutine write_edge_geometry_sph (id_file, nod_IO, sfed_IO)
subroutine write_edge_geometry_cyl (id_file, nod_IO, sfed_IO)
Detailed Description
data IO orutines for edge
      subroutine read_edge_connection                                 &
     &         (id_file, id_rank, comm_IO, ele_IO, sfed_IO, ierr)
        type(communication_table), intent(inout) :: comm_IO
        type(element_data), intent(inout) :: ele_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
      subroutine write_edge_connection                                &
     &         (id_file, id_rank, comm_IO, ele_IO, sfed_IO)
        type(communication_table), intent(in) :: comm_IO
        type(element_data), intent(in) :: ele_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
      subroutine read_edge_geometry(id_file, nod_IO, sfed_IO)
        type(communication_table), intent(inout) :: comm_IO
        type(node_data), intent(inout) :: nod_IO
        type(element_data), intent(inout) :: ele_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
      subroutine write_edge_geometry(id_file, nod_IO, sfed_IO)
      subroutine write_edge_geometry_sph(id_file, nod_IO, sfed_IO)
      subroutine write_edge_geometry_cyl(id_file, nod_IO, sfed_IO)
        type(communication_table), intent(in) :: comm_IO
        type(node_data), intent(in) :: nod_IO
        type(element_data), intent(in) :: ele_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
Function/Subroutine Documentation
read_edge_connection()
subroutine edge_data_io::read_edge_connection (integer (kind = kint), intent(in) id_file, integer, intent(in) id_rank, type(communication_table), intent(inout) comm_IO, type(element_data), intent(inout) ele_IO, type(surf_edge_io_data), intent(inout) sfed_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 54 of file edge_data_IO.f90.
References domain_data_io::read_domain_info(), element_connect_io::read_edge_4_element(), element_connect_io::read_element_info(), domain_data_io::read_export_data(), domain_data_io::read_import_data(), element_connect_io::read_number_of_element(), and element_connect_io::read_surface_4_element().
Referenced by element_file_io::input_edge_file().
read_edge_geometry()
subroutine edge_data_io::read_edge_geometry (integer (kind = kint), intent(in) id_file, type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 155 of file edge_data_IO.f90.
References node_geometry_io::read_geometry_info(), node_geometry_io::read_number_of_node(), node_geometry_io::read_scalar_in_element(), and node_geometry_io::read_vector_in_element().
write_edge_connection()
subroutine edge_data_io::write_edge_connection (integer (kind = kint), intent(in) id_file, integer, intent(in) id_rank, type(communication_table), intent(in) comm_IO, type(element_data), intent(in) ele_IO, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 116 of file edge_data_IO.f90.
References m_fem_surface_labels::hd_edge_connect(), m_fem_surface_labels::hd_edge_export(), m_fem_surface_labels::hd_edge_import(), m_fem_surface_labels::hd_edge_on_ele(), m_fem_surface_labels::hd_edge_on_surf(), m_fem_surface_labels::hd_edge_para(), m_fem_mesh_labels::hd_fem_para(), domain_data_io::write_domain_info(), element_connect_io::write_edge_4_element(), element_connect_io::write_element_info(), domain_data_io::write_export_data(), domain_data_io::write_import_data(), and element_connect_io::write_surface_4_element().
Referenced by element_file_io::output_edge_file().
write_edge_geometry()
subroutine edge_data_io::write_edge_geometry (integer (kind = kint), intent(in) id_file, type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 189 of file edge_data_IO.f90.
References m_fem_surface_labels::hd_edge_dir(), m_fem_surface_labels::hd_edge_length(), m_fem_surface_labels::hd_edge_point(), node_geometry_io::write_geometry_info(), node_geometry_io::write_scalar_in_element(), and node_geometry_io::write_vector_in_element().
write_edge_geometry_cyl()
subroutine edge_data_io::write_edge_geometry_cyl (integer (kind = kint), intent(in) id_file, type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 238 of file edge_data_IO.f90.
References m_fem_surface_labels::hd_edge_dir(), m_fem_surface_labels::hd_edge_length(), node_geometry_io::write_geometry_info(), node_geometry_io::write_scalar_in_element(), and node_geometry_io::write_vector_in_element().
write_edge_geometry_sph()
subroutine edge_data_io::write_edge_geometry_sph (integer (kind = kint), intent(in) id_file, type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 211 of file edge_data_IO.f90.
References m_fem_surface_labels::hd_edge_dir(), m_fem_surface_labels::hd_edge_length(), node_geometry_io::write_geometry_info(), node_geometry_io::write_scalar_in_element(), and node_geometry_io::write_vector_in_element().