CALYPSO: gz_mpi_node_geometry_io Module Reference
gz_mpi_node_geometry_io Module Reference
routines for ASCII data IO for mesh geometry
Functions/Subroutines
subroutine gz_mpi_write_geometry_info (IO_param, nod_IO)
subroutine gz_mpi_write_scl_in_ele (IO_param, nod_IO, sfed_IO)
subroutine gz_mpi_write_vect_in_ele (IO_param, nod_IO, sfed_IO)
subroutine gz_mpi_read_number_of_node (IO_param, nod_IO)
subroutine gz_mpi_read_geometry_info (IO_param, nod_IO)
subroutine gz_mpi_read_scl_in_ele (IO_param, nod_IO, sfed_IO)
subroutine gz_mpi_read_vect_in_ele (IO_param, nod_IO, sfed_IO)
Detailed Description
routines for ASCII data IO for mesh geometry
      subroutine gz_mpi_write_geometry_info(IO_param, nod_IO)
      subroutine gz_mpi_write_scl_in_ele(IO_param, nod_IO, sfed_IO)
      subroutine gz_mpi_write_vect_in_ele(IO_param, nod_IO, sfed_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(node_data), intent(in) :: nod_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
      subroutine gz_mpi_read_number_of_node(IO_param, nod_IO)
      subroutine gz_mpi_read_geometry_info(IO_param, nod_IO)
      subroutine gz_mpi_read_scl_in_ele(IO_param, nod_IO, sfed_IO)
      subroutine gz_mpi_read_vect_in_ele(IO_param, nod_IO, sfed_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(node_data), intent(inout) :: nod_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
Function/Subroutine Documentation
gz_mpi_read_geometry_info()
subroutine gz_mpi_node_geometry_io::gz_mpi_read_geometry_info (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(inout) nod_IO)
Definition at line 112 of file gz_MPI_node_geometry_IO.f90.
References t_geometry_data::alloc_node_geometry_base(), transfer_to_long_integers::cast_long(), gz_mpi_position_io::gz_mpi_read_node_position(), and m_phys_constants::n_vector.
Referenced by gz_mpi_edge_data_io::gz_mpi_read_edge_geometry(), gz_mpi_element_data_io::gz_mpi_read_ele_geometry(), gz_mpi_mesh_data_io::gz_mpi_read_num_node_ele(), and gz_mpi_surface_data_io::gz_mpi_read_surf_geometry().
gz_mpi_read_number_of_node()
subroutine gz_mpi_node_geometry_io::gz_mpi_read_number_of_node (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(inout) nod_IO)
Definition at line 99 of file gz_MPI_node_geometry_IO.f90.
Referenced by gz_mpi_edge_data_io::gz_mpi_read_edge_geometry(), gz_mpi_element_data_io::gz_mpi_read_ele_geometry(), gz_mpi_mesh_data_io::gz_mpi_read_num_node(), gz_mpi_read_scl_in_ele(), gz_mpi_surface_data_io::gz_mpi_read_surf_geometry(), and gz_mpi_read_vect_in_ele().
gz_mpi_read_scl_in_ele()
subroutine gz_mpi_node_geometry_io::gz_mpi_read_scl_in_ele (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 128 of file gz_MPI_node_geometry_IO.f90.
References t_surf_edge_io::alloc_ele_scalar_io(), transfer_to_long_integers::cast_long(), gz_mpi_read_number_of_node(), and gz_mpi_vectors_io::gz_mpi_read_scalar().
Referenced by gz_mpi_edge_data_io::gz_mpi_read_edge_geometry(), gz_mpi_element_data_io::gz_mpi_read_ele_geometry(), and gz_mpi_surface_data_io::gz_mpi_read_surf_geometry().
gz_mpi_read_vect_in_ele()
subroutine gz_mpi_node_geometry_io::gz_mpi_read_vect_in_ele (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 145 of file gz_MPI_node_geometry_IO.f90.
References t_surf_edge_io::alloc_ele_vector_io(), transfer_to_long_integers::cast_long(), gz_mpi_read_number_of_node(), gz_mpi_vectors_io::gz_mpi_read_vector(), and m_phys_constants::n_vector.
Referenced by gz_mpi_edge_data_io::gz_mpi_read_edge_geometry(), and gz_mpi_surface_data_io::gz_mpi_read_surf_geometry().
gz_mpi_write_geometry_info()
subroutine gz_mpi_node_geometry_io::gz_mpi_write_geometry_info (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(in) nod_IO)
Definition at line 49 of file gz_MPI_node_geometry_IO.f90.
References transfer_to_long_integers::cast_long(), and gz_mpi_position_io::gz_mpi_write_node_position().
Referenced by gz_mpi_edge_data_io::gz_mpi_write_edge_geometry(), gz_mpi_element_data_io::gz_mpi_write_ele_geometry(), gz_mpi_mesh_data_io::gz_mpi_write_geometry_data(), and gz_mpi_surface_data_io::gz_mpi_write_surf_geometry().
gz_mpi_write_scl_in_ele()
subroutine gz_mpi_node_geometry_io::gz_mpi_write_scl_in_ele (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 66 of file gz_MPI_node_geometry_IO.f90.
References transfer_to_long_integers::cast_long(), and gz_mpi_vectors_io::gz_mpi_write_scalar().
Referenced by gz_mpi_edge_data_io::gz_mpi_write_edge_geometry(), gz_mpi_element_data_io::gz_mpi_write_ele_geometry(), and gz_mpi_surface_data_io::gz_mpi_write_surf_geometry().
gz_mpi_write_vect_in_ele()
subroutine gz_mpi_node_geometry_io::gz_mpi_write_vect_in_ele (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 82 of file gz_MPI_node_geometry_IO.f90.
References transfer_to_long_integers::cast_long(), gz_mpi_vectors_io::gz_mpi_write_vector(), and m_phys_constants::n_vector.
Referenced by gz_mpi_edge_data_io::gz_mpi_write_edge_geometry(), and gz_mpi_surface_data_io::gz_mpi_write_surf_geometry().