CALYPSO: analyzer_sph_dynamobench Module Reference
analyzer_sph_dynamobench Module Reference
Initialzation and evolution loop for dynamo benchmark check.
Functions/Subroutines
subroutine initialize_sph_dynamobench
subroutine evolution_sph_dynamobench
Variables
character(len=kchara), parameter, private snap_ctl_name = 'control_snapshot'
File name for control file.
type(dns_mhd_simulation_control), save, private dns_mhd_ctl1
Control struture for MHD simulation.
type(sph_mesh_field_data), save, private sph_mhd1
Structure of spectr grid and data.
type(circle_fld_maker), save, private cdat1
Structure of field on mid-depth and equator.
type(dynamobench_monitor), save, private bench1
Structure of benchmark result data.
Detailed Description
Initialzation and evolution loop for dynamo benchmark check.
      subroutine initialize_sph_dynamobench
      subroutine evolution_sph_dynamobench
Function/Subroutine Documentation
evolution_sph_dynamobench()
subroutine analyzer_sph_dynamobench::evolution_sph_dynamobench
Definition at line 102 of file analyzer_sph_dynamobench.f90.
References t_sph_trans_arrays_mhd::alloc_sph_trans_area_snap(), bench1, calypso_mpi::calypso_mpi_barrier(), cdat1, t_sph_trans_arrays_mhd::dealloc_sph_trans_area_snap(), m_work_time::end_elapsed_time(), m_work_time::ied_total_elapsed, m_machine_parameter::iflag_debug, m_elapsed_labels_4_mhd::iflag_mhd_time, m_work_time::iflag_tot_time, m_elapsed_labels_4_mhd::ist_elapsed_mhd, output_viz_file_control::lead_field_data_flag(), m_work_time::output_elapsed_times(), set_time_step_params::set_from_initial_step(), sph_analyzer_d_bench::sph_analyze_dbench(), sph_mhd1, m_sph_mhd_model_data::sph_model1, m_sph_mhd_model_data::sph_wk1, and m_work_time::start_elapsed_time().
Referenced by sph_dynamobench().
initialize_sph_dynamobench()
subroutine analyzer_sph_dynamobench::initialize_sph_dynamobench
Definition at line 56 of file analyzer_sph_dynamobench.f90.
References bench1, calypso_mpi::calypso_mpi_barrier(), cdat1, dns_mhd_ctl1, m_elapsed_labels_send_recv::elpsed_label_field_send_recv(), m_work_time::end_elapsed_time(), m_sph_mhd_model_data::fem_d1, m_work_time::ied_total_elapsed, m_machine_parameter::iflag_debug, m_elapsed_labels_4_mhd::iflag_mhd_time, m_work_time::iflag_tot_time, m_work_time::init_elapse_time_by_total(), input_control_dynamobench::input_control_sph_dynamobench(), m_elapsed_labels_4_mhd::ist_elapsed_mhd, calypso_mpi::my_rank, t_ctl_data_sph_mhd_psf::read_control_4_sph_mhd_noviz(), init_sph_mhd_elapsed_label::reset_elapse_4_init_sph_mhd(), init_sph_mhd_elapsed_label::set_sph_mhd_elapsed_label(), snap_ctl_name, sph_analyzer_d_bench::sph_init_sph_dbench(), sph_mhd1, m_sph_mhd_model_data::sph_model1, m_sph_mhd_model_data::sph_wk1, and m_work_time::start_elapsed_time().
Referenced by sph_dynamobench().
Variable Documentation
bench1
type(dynamobench_monitor), save, private analyzer_sph_dynamobench::bench1 private
Structure of benchmark result data.
Definition at line 48 of file analyzer_sph_dynamobench.f90.
Referenced by evolution_sph_dynamobench(), and initialize_sph_dynamobench().
cdat1
type(circle_fld_maker), save, private analyzer_sph_dynamobench::cdat1 private
Structure of field on mid-depth and equator.
Definition at line 46 of file analyzer_sph_dynamobench.f90.
Referenced by evolution_sph_dynamobench(), and initialize_sph_dynamobench().
dns_mhd_ctl1
type(dns_mhd_simulation_control), save, private analyzer_sph_dynamobench::dns_mhd_ctl1 private
Control struture for MHD simulation.
Definition at line 39 of file analyzer_sph_dynamobench.f90.
Referenced by initialize_sph_dynamobench().
snap_ctl_name
character(len=kchara), parameter, private analyzer_sph_dynamobench::snap_ctl_name = 'control_snapshot' private
File name for control file.
Definition at line 36 of file analyzer_sph_dynamobench.f90.
Referenced by initialize_sph_dynamobench().
sph_mhd1
type(sph_mesh_field_data), save, private analyzer_sph_dynamobench::sph_mhd1 private
Structure of spectr grid and data.
Definition at line 43 of file analyzer_sph_dynamobench.f90.
Referenced by evolution_sph_dynamobench(), and initialize_sph_dynamobench().