CALYPSO: m_diff_vector_labels Module Reference
m_diff_vector_labels Module Reference
Functions/Subroutines
logical function check_difference_vectors (field_name)
integer(kind=kint) function num_difference_vector ()
subroutine set_differnce_vector_labels (n_comps, names, maths)
Variables
integer(kind=kint), parameter, private ngrad_vector = 15
type(field_def), parameter grad_v_1 = field_def(n_comp = n_vector, name = 'grad_v_1', math = '$ \partial_{i} u_{1} $')
Field label for gradient of velocity \(\partial_{i} u_{x} \).
type(field_def), parameter grad_v_2 = field_def(n_comp = n_vector, name = 'grad_v_2', math = '$ \partial_{i} u_{2} $')
Field label for gradient of velocity \(\partial_{i} u_{y} \).
type(field_def), parameter grad_v_3 = field_def(n_comp = n_vector, name = 'grad_v_3', math = '$ \partial_{i} u_{3} $')
Field label for gradient of velocity \(\partial_{i} u_{z} \).
type(field_def), parameter grad_w_1 = field_def(n_comp = n_vector, name = 'grad_w_1', math = '$ \partial_{i} \omega_{1} $')
Field label for gradient of vorticity \(\partial_{i} \omega_{x} \).
type(field_def), parameter grad_w_2 = field_def(n_comp = n_vector, name = 'grad_w_2', math = '$ \partial_{i} \omega_{2} $')
Field label for gradient of vorticity \(\partial_{i} \omega_{y} \).
type(field_def), parameter grad_w_3 = field_def(n_comp = n_vector, name = 'grad_w_3', math = '$ \partial_{i} \omega_{3} $')
Field label for gradient of vorticity \(\partial_{i} \omega_{z} \).
type(field_def), parameter grad_a_1 = field_def(n_comp = n_vector, name = 'grad_a_1', math = '$ \partial_{i} A_{1} $')
Field label for gradient of vector potential \(\partial_{i} A_{x} \).
type(field_def), parameter grad_a_2 = field_def(n_comp = n_vector, name = 'grad_a_2', math = '$ \partial_{i} A_{2} $')
Field label for gradient of vector potential \(\partial_{i} A_{y} \).
type(field_def), parameter grad_a_3 = field_def(n_comp = n_vector, name = 'grad_a_3', math = '$ \partial_{i} A_{3} $')
Field label for gradient of vector potential \(\partial_{i} A_{z} \).
type(field_def), parameter grad_b_1 = field_def(n_comp = n_vector, name = 'grad_b_1', math = '$ \partial_{i} B_{1} $')
Field label for gradient of magnetic field \(\partial_{i} B_{x} \).
type(field_def), parameter grad_b_2 = field_def(n_comp = n_vector, name = 'grad_b_2', math = '$ \partial_{i} B_{2} $')
Field label for gradient of magnetic field \(\partial_{i} B_{y} \).
type(field_def), parameter grad_b_3 = field_def(n_comp = n_vector, name = 'grad_b_3', math = '$ \partial_{i} B_{3} $')
Field label for gradient of magnetic field \(\partial_{i} B_{z} \).
type(field_def), parameter grad_j_1 = field_def(n_comp = n_vector, name = 'grad_j_1', math = '$ \partial_{i} J_{1} $')
Field label for gradient of current density \(\partial_{i} J_{x} \).
type(field_def), parameter grad_j_2 = field_def(n_comp = n_vector, name = 'grad_j_2', math = '$ \partial_{i} J_{2} $')
Field label for gradient of current density \(\partial_{i} J_{y} \).
type(field_def), parameter grad_j_3 = field_def(n_comp = n_vector, name = 'grad_j_3', math = '$ \partial_{i} J_{3} $')
Field label for gradient of current density \(\partial_{i} J_{z} \).
Function/Subroutine Documentation
check_difference_vectors()
logical function m_diff_vector_labels::check_difference_vectors (character(len = kchara), intent(in) field_name)
Definition at line 146 of file m_diff_vector_labels.f90.
References grad_a_1, grad_a_2, grad_a_3, grad_b_1, grad_b_2, grad_b_3, grad_j_1, grad_j_2, grad_j_3, grad_v_1, grad_v_2, grad_v_3, grad_w_1, grad_w_2, and grad_w_3.
Referenced by set_mhd_field_address::check_vector_fields(), and t_diff_vector_labels::set_diff_vector_addresses().
num_difference_vector()
integer(kind = kint) function m_diff_vector_labels::num_difference_vector
Definition at line 177 of file m_diff_vector_labels.f90.
References ngrad_vector.
set_differnce_vector_labels()
subroutine m_diff_vector_labels::set_differnce_vector_labels (integer(kind = kint_4b), dimension(ngrad_vector), intent(inout) n_comps, character(len = kchara), dimension(ngrad_vector), intent(inout) names, character(len = kchara), dimension(ngrad_vector), intent(inout) maths)
Definition at line 184 of file m_diff_vector_labels.f90.
References grad_a_1, grad_a_2, grad_a_3, grad_b_1, grad_b_2, grad_b_3, grad_j_1, grad_j_2, grad_j_3, grad_v_1, grad_v_2, grad_v_3, grad_w_1, grad_w_2, grad_w_3, and t_field_labels::set_field_labels().
Variable Documentation
grad_a_1
type(field_def), parameter m_diff_vector_labels::grad_a_1 = field_def(n_comp = n_vector, name = 'grad_a_1', math = '$ \partial_{i} A_{1} $')
Field label for gradient of vector potential \(\partial_{i} A_{x} \).
Definition at line 85 of file m_diff_vector_labels.f90.
Referenced by check_base_field::add_field_ctl_4_diff_vector(), check_difference_vectors(), t_diff_vector_labels::set_diff_vector_addresses(), and set_differnce_vector_labels().
grad_a_2
type(field_def), parameter m_diff_vector_labels::grad_a_2 = field_def(n_comp = n_vector, name = 'grad_a_2', math = '$ \partial_{i} A_{2} $')
Field label for gradient of vector potential \(\partial_{i} A_{y} \).
Definition at line 91 of file m_diff_vector_labels.f90.
Referenced by check_base_field::add_field_ctl_4_diff_vector(), check_difference_vectors(), t_diff_vector_labels::set_diff_vector_addresses(), and set_differnce_vector_labels().
grad_a_3
type(field_def), parameter m_diff_vector_labels::grad_a_3 = field_def(n_comp = n_vector, name = 'grad_a_3', math = '$ \partial_{i} A_{3} $')
Field label for gradient of vector potential \(\partial_{i} A_{z} \).
Definition at line 97 of file m_diff_vector_labels.f90.
Referenced by check_base_field::add_field_ctl_4_diff_vector(), check_difference_vectors(), t_diff_vector_labels::set_diff_vector_addresses(), and set_differnce_vector_labels().
grad_b_1
type(field_def), parameter m_diff_vector_labels::grad_b_1 = field_def(n_comp = n_vector, name = 'grad_b_1', math = '$ \partial_{i} B_{1} $')
Field label for gradient of magnetic field \(\partial_{i} B_{x} \).
Definition at line 104 of file m_diff_vector_labels.f90.
Referenced by check_base_field::add_field_ctl_4_diff_vector(), check_difference_vectors(), t_diff_vector_labels::set_diff_vector_addresses(), and set_differnce_vector_labels().
grad_b_2
type(field_def), parameter m_diff_vector_labels::grad_b_2 = field_def(n_comp = n_vector, name = 'grad_b_2', math = '$ \partial_{i} B_{2} $')
Field label for gradient of magnetic field \(\partial_{i} B_{y} \).
Definition at line 110 of file m_diff_vector_labels.f90.
Referenced by check_base_field::add_field_ctl_4_diff_vector(), check_difference_vectors(), t_diff_vector_labels::set_diff_vector_addresses(), and set_differnce_vector_labels().
grad_b_3
type(field_def), parameter m_diff_vector_labels::grad_b_3 = field_def(n_comp = n_vector, name = 'grad_b_3', math = '$ \partial_{i} B_{3} $')
Field label for gradient of magnetic field \(\partial_{i} B_{z} \).
Definition at line 116 of file m_diff_vector_labels.f90.
Referenced by check_base_field::add_field_ctl_4_diff_vector(), check_difference_vectors(), t_diff_vector_labels::set_diff_vector_addresses(), and set_differnce_vector_labels().
grad_j_1
type(field_def), parameter m_diff_vector_labels::grad_j_1 = field_def(n_comp = n_vector, name = 'grad_j_1', math = '$ \partial_{i} J_{1} $')
Field label for gradient of current density \(\partial_{i} J_{x} \).
Definition at line 123 of file m_diff_vector_labels.f90.
Referenced by check_base_field::add_field_ctl_4_diff_vector(), check_difference_vectors(), t_diff_vector_labels::set_diff_vector_addresses(), and set_differnce_vector_labels().
grad_j_2
type(field_def), parameter m_diff_vector_labels::grad_j_2 = field_def(n_comp = n_vector, name = 'grad_j_2', math = '$ \partial_{i} J_{2} $')
Field label for gradient of current density \(\partial_{i} J_{y} \).
Definition at line 129 of file m_diff_vector_labels.f90.
Referenced by check_base_field::add_field_ctl_4_diff_vector(), check_difference_vectors(), t_diff_vector_labels::set_diff_vector_addresses(), and set_differnce_vector_labels().
grad_j_3
type(field_def), parameter m_diff_vector_labels::grad_j_3 = field_def(n_comp = n_vector, name = 'grad_j_3', math = '$ \partial_{i} J_{3} $')
Field label for gradient of current density \(\partial_{i} J_{z} \).
Definition at line 135 of file m_diff_vector_labels.f90.
Referenced by check_base_field::add_field_ctl_4_diff_vector(), check_difference_vectors(), t_diff_vector_labels::set_diff_vector_addresses(), and set_differnce_vector_labels().
grad_v_1
type(field_def), parameter m_diff_vector_labels::grad_v_1 = field_def(n_comp = n_vector, name = 'grad_v_1', math = '$ \partial_{i} u_{1} $')
Field label for gradient of velocity \(\partial_{i} u_{x} \).
Definition at line 47 of file m_diff_vector_labels.f90.
Referenced by check_base_field::add_field_ctl_4_diff_vector(), check_base_forces::add_field_ctl_4_forces(), check_difference_vectors(), t_diff_vector_labels::set_diff_vector_addresses(), and set_differnce_vector_labels().
grad_v_2
type(field_def), parameter m_diff_vector_labels::grad_v_2 = field_def(n_comp = n_vector, name = 'grad_v_2', math = '$ \partial_{i} u_{2} $')
Field label for gradient of velocity \(\partial_{i} u_{y} \).
Definition at line 53 of file m_diff_vector_labels.f90.
Referenced by check_base_field::add_field_ctl_4_diff_vector(), check_base_forces::add_field_ctl_4_forces(), check_difference_vectors(), t_diff_vector_labels::set_diff_vector_addresses(), and set_differnce_vector_labels().
grad_v_3
type(field_def), parameter m_diff_vector_labels::grad_v_3 = field_def(n_comp = n_vector, name = 'grad_v_3', math = '$ \partial_{i} u_{3} $')
Field label for gradient of velocity \(\partial_{i} u_{z} \).
Definition at line 59 of file m_diff_vector_labels.f90.
Referenced by check_base_field::add_field_ctl_4_diff_vector(), check_base_forces::add_field_ctl_4_forces(), check_difference_vectors(), t_diff_vector_labels::set_diff_vector_addresses(), and set_differnce_vector_labels().
grad_w_1
type(field_def), parameter m_diff_vector_labels::grad_w_1 = field_def(n_comp = n_vector, name = 'grad_w_1', math = '$ \partial_{i} \omega_{1} $')
Field label for gradient of vorticity \(\partial_{i} \omega_{x} \).
Definition at line 66 of file m_diff_vector_labels.f90.
Referenced by check_base_field::add_field_ctl_4_diff_vector(), check_difference_vectors(), t_diff_vector_labels::set_diff_vector_addresses(), and set_differnce_vector_labels().
grad_w_2
type(field_def), parameter m_diff_vector_labels::grad_w_2 = field_def(n_comp = n_vector, name = 'grad_w_2', math = '$ \partial_{i} \omega_{2} $')
Field label for gradient of vorticity \(\partial_{i} \omega_{y} \).
Definition at line 72 of file m_diff_vector_labels.f90.
Referenced by check_base_field::add_field_ctl_4_diff_vector(), check_difference_vectors(), t_diff_vector_labels::set_diff_vector_addresses(), and set_differnce_vector_labels().
grad_w_3
type(field_def), parameter m_diff_vector_labels::grad_w_3 = field_def(n_comp = n_vector, name = 'grad_w_3', math = '$ \partial_{i} \omega_{3} $')
Field label for gradient of vorticity \(\partial_{i} \omega_{z} \).
Definition at line 78 of file m_diff_vector_labels.f90.
Referenced by check_base_field::add_field_ctl_4_diff_vector(), check_difference_vectors(), t_diff_vector_labels::set_diff_vector_addresses(), and set_differnce_vector_labels().
ngrad_vector
integer(kind = kint), parameter, private m_diff_vector_labels::ngrad_vector = 15 private
Definition at line 41 of file m_diff_vector_labels.f90.
Referenced by num_difference_vector().