CALYPSO: set_element_position Module Reference
set_element_position Module Reference
Functions/Subroutines
subroutine set_linear_ele_position (numnod, numele, ie, xx, x_ele)
subroutine set_quad_ele_position (numnod, numele, ie, xx, x_ele)
subroutine set_lag_ele_position (numnod, numele, ie, xx, x_ele)
Function/Subroutine Documentation
set_lag_ele_position()
subroutine set_element_position::set_lag_ele_position (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) numele, integer(kind = kint), dimension(numele,27), intent(in) ie, real(kind=kreal), dimension(numnod,3), intent(in) xx, real(kind=kreal), dimension(numele,3), intent(inout) x_ele)
Definition at line 128 of file set_element_position.f90.
Referenced by cal_mesh_position::set_center_of_element().
set_linear_ele_position()
subroutine set_element_position::set_linear_ele_position (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) numele, integer(kind = kint), dimension(numele,8), intent(in) ie, real(kind=kreal), dimension(numnod,3), intent(in) xx, real(kind=kreal), dimension(numele,3), intent(inout) x_ele)
Definition at line 22 of file set_element_position.f90.
Referenced by cal_mesh_position::set_center_of_element().
set_quad_ele_position()
subroutine set_element_position::set_quad_ele_position (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) numele, integer(kind = kint), dimension(numele,20), intent(in) ie, real(kind=kreal), dimension(numnod,3), intent(in) xx, real(kind=kreal), dimension(numele,3), intent(inout) x_ele)
Definition at line 63 of file set_element_position.f90.
Referenced by cal_mesh_position::set_center_of_element().