CALYPSO: analyzer_psf Module Reference
analyzer_psf Module Reference
Functions/Subroutines
subroutine init_analyzer_psf
subroutine analyze_psf
Variables
type(time_step_param_w_viz), save t_viz2
Structure for time stepping parameters with field and visualization.
type(control_data_section_only), save sec_viz_ctl2
Structure of control data for sectioning only.
type(fem_mesh_field_4_surfacing), save sfcing2
Structure of mesh and field for sectioning only.
type(surfacing_modules), save viz_psfs2
Structure of sectioning and isosurfaceing modules.
Function/Subroutine Documentation
analyze_psf()
subroutine analyzer_psf::analyze_psf
Definition at line 73 of file analyzer_psf.f90.
References m_work_time::end_elapsed_time(), fem_analyzer_viz_surf::fem_analyze_surface(), m_work_time::ied_total_elapsed, m_work_time::iflag_tot_time, m_work_time::output_elapsed_times(), sfcing2, t_viz2, t_viz_sections::visualize_surface(), and viz_psfs2.
Referenced by kemorin_surface_rendering().
init_analyzer_psf()
subroutine analyzer_psf::init_analyzer_psf
Definition at line 38 of file analyzer_psf.f90.
References calypso_mpi::calypso_mpi_abort(), m_elapsed_labels_4_viz::elpsed_label_4_viz(), m_elapsed_labels_send_recv::elpsed_label_field_send_recv(), fem_analyzer_viz_surf::fem_initialize_surface(), m_work_time::ied_total_elapsed, m_work_time::iflag_tot_time, m_work_time::init_elapse_time_by_total(), t_viz_sections::init_visualize_surface(), t_control_data_section_only::read_control_data_section_only(), sec_viz_ctl2, load_mesh_and_field_4_viz::set_control_params_4_viz(), sfcing2, m_work_time::start_elapsed_time(), t_viz2, and viz_psfs2.
Referenced by kemorin_surface_rendering().
Variable Documentation
sec_viz_ctl2
type(control_data_section_only), save analyzer_psf::sec_viz_ctl2
Structure of control data for sectioning only.
Definition at line 26 of file analyzer_psf.f90.
Referenced by init_analyzer_psf().
sfcing2
type(fem_mesh_field_4_surfacing), save analyzer_psf::sfcing2
Structure of mesh and field for sectioning only.
Definition at line 28 of file analyzer_psf.f90.
Referenced by analyze_psf(), and init_analyzer_psf().
t_viz2
type(time_step_param_w_viz), save analyzer_psf::t_viz2
Structure for time stepping parameters with field and visualization.
Definition at line 24 of file analyzer_psf.f90.
Referenced by analyze_psf(), and init_analyzer_psf().
viz_psfs2
type(surfacing_modules), save analyzer_psf::viz_psfs2
Structure of sectioning and isosurfaceing modules.
Definition at line 30 of file analyzer_psf.f90.
Referenced by analyze_psf(), and init_analyzer_psf().