CALYPSO: t_coriolis_terms_rlm Module Reference
t_coriolis_terms_rlm Module Reference
Coriolis terms array.
Data Types
type coriolis_rlm_data
Structure of Coriolis terms in \(f(r,l,m) \).
Functions/Subroutines
subroutine init_sum_coriolis_rlm (l_truncation, sph_rlm, sph_bc_U, leg, gt_cor, cor_rlm)
subroutine sum_coriolis_rlm (ncomp_trans, sph_rlm, comm_rlm, fl_prop, sph_bc_U, omega_sph, b_trns, leg, gt_cor, n_WR, WR, cor_rlm)
subroutine copy_coriolis_terms_rlm (ncomp_trans, sph_rlm, comm_rlm, fl_prop, f_trns, cor_rlm, n_WS, WS)
subroutine, private alloc_d_coriolis_rlm (nnod_rlm, jmax_rlm, cor_rlm)
subroutine dealloc_d_coriolis_rlm (cor_rlm)
Detailed Description
Coriolis terms array.
************************************************
      subroutine init_sum_coriolis_rlm                                &
     &         (l_truncation, sph_rlm, sph_bc_U, leg, gt_cor, cor_rlm)
      subroutine sum_coriolis_rlm(ncomp_trans, sph_rlm, comm_rlm,     &
     &          fl_prop, sph_bc_U, omega_sph, b_trns, leg, gt_cor,    &
     &          n_WR, WR, cor_rlm)
        type(phys_address), intent(in) :: b_trns
      subroutine copy_coriolis_terms_rlm                              &
     &         (ncomp_trans, sph_rlm, comm_rlm, fl_prop,              &
     &          f_trns, cor_rlm, n_WS, WS)
        type(phys_address), intent(in) :: f_trns
      subroutine dealloc_d_coriolis_rlm(cor_rlm)
************************************************
  Rotation of the Coriolos term
     (wss) = wss(jc,1,j3)*w*dyb/r**2
            + wss(jc,2,j3)*dw*yb/r**2
     (wts) = wts(j3)*w*yb/r**2
     (wst) = wst(1,j3)*( dw*dyb/r**2 + w*d2yb/r**2 - 2*w*dyb/r**3 )
            + wst(2,j3)*( d2w/r**2 - 2*dw/r**3 )*yb
     (wtt) = wtt(jc,1,j3)*dw*yb/r**2
            + wtt(jc,2,j3)*w*( dyb/r**2 - 2*yb/r**3 )
   Divergence of the Coriolis term
     (wsd) = wsd(jc,1,j3)*w*wsb/r**4
            + wsd(jc,2,j3)*dw*dwsb/r**2
     (wtd) = wtd(j3)*dw*dwtb/r**2
  Radial componenet of the Coriolis term
     (wsr) = wsr(jc,1,j3)*dw*dusb/r**2
     (wtr) = wtr(j3)*dw*wtb/r**2
************************************************
************************************************
     wss(jc,1,j3) = sw_rj(jc,1,j3)
     wss(jc,2,j3) = sw_rj(jc,2,j3)
     wts(jc,j3)   = sw_rj(jc,3,j3)
     wst(jc,1,j3) = tw_rj(jc,1,j3)
     wst(jc,2,j3) = tw_rj(jc,2,j3)
     wtt(jc,1,j3) = tw_rj(jc,3,j3)
     wtt(jc,2,j3) = tw_rj(jc,4,j3)
     wsd(jc,1,j3) = sd_rj(jc,1,j3)
     wsd(jc,2,j3) = sd_rj(jc,2,j3)
     wtd(jc,j3)   = td_rj(jc,j3)
     wsr(jc,j3) =   sr_rj(jc,j3)
     wtr(jc,j3) =   tr_rj(jc,j3)
************************************************
Function/Subroutine Documentation
alloc_d_coriolis_rlm()
subroutine, private t_coriolis_terms_rlm::alloc_d_coriolis_rlm (integer(kind = kint), intent(in) nnod_rlm, integer(kind = kint), intent(in) jmax_rlm, type(coriolis_rlm_data), intent(inout) cor_rlm) private
Definition at line 322 of file t_coriolis_terms_rlm.f90.
Referenced by init_sum_coriolis_rlm().
copy_coriolis_terms_rlm()
subroutine t_coriolis_terms_rlm::copy_coriolis_terms_rlm (integer(kind = kint), intent(in) ncomp_trans, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_comm_tbl), intent(in) comm_rlm, type(fluid_property), intent(in) fl_prop, type(phys_address), intent(in) f_trns, type(coriolis_rlm_data), intent(in) cor_rlm, integer(kind = kint), intent(in) n_WS, real(kind = kreal), dimension(n_ws), intent(inout) WS)
Definition at line 285 of file t_coriolis_terms_rlm.f90.
References sel_spherical_srs::sel_calypso_to_send_scalar().
Referenced by sph_trans_w_coriols::sph_f_trans_licv(), and sph_trans_w_coriols::sph_f_trans_w_coriolis().
dealloc_d_coriolis_rlm()
subroutine t_coriolis_terms_rlm::dealloc_d_coriolis_rlm (type(coriolis_rlm_data), intent(inout) cor_rlm)
Definition at line 348 of file t_coriolis_terms_rlm.f90.
init_sum_coriolis_rlm()
subroutine t_coriolis_terms_rlm::init_sum_coriolis_rlm (integer(kind = kint), intent(in) l_truncation, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_boundary_type), intent(in) sph_bc_U, type(legendre_4_sph_trans), intent(in) leg, type(gaunt_coriolis_rlm), intent(inout) gt_cor, type(coriolis_rlm_data), intent(inout) cor_rlm)
Definition at line 139 of file t_coriolis_terms_rlm.f90.
References t_gaunt_coriolis_rlm::alloc_coriolis_coef_tri_rlm(), alloc_d_coriolis_rlm(), t_gaunt_coriolis_rlm::alloc_gaunt_coriolis_rlm(), interact_coriolis_rlm::cal_gaunt_coriolis_rlm(), t_gaunt_coriolis_rlm::find_local_radius_rlm_address(), t_gaunt_coriolis_rlm::find_local_sph_rlm_address(), m_machine_parameter::iflag_debug, interact_coriolis_rlm::interact_rot_coriolis_rlm(), m_constants::ione, and m_constants::izero.
Referenced by init_sphrical_transform_mhd::init_work_4_coriolis().
sum_coriolis_rlm()
subroutine t_coriolis_terms_rlm::sum_coriolis_rlm (integer(kind = kint), intent(in) ncomp_trans, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_comm_tbl), intent(in) comm_rlm, type(fluid_property), intent(in) fl_prop, type(sph_boundary_type), intent(in) sph_bc_U, type(sph_rotation), intent(in) omega_sph, type(phys_address), intent(in) b_trns, type(legendre_4_sph_trans), intent(in) leg, type(gaunt_coriolis_rlm), intent(in) gt_cor, integer(kind = kint), intent(in) n_WR, real(kind = kreal), dimension(n_wr), intent(in) WR, type(coriolis_rlm_data), intent(inout) cor_rlm)
Definition at line 192 of file t_coriolis_terms_rlm.f90.
References t_boundary_params_sph_mhd::iflag_rotatable_ic, sum_coriolis_terms_rlm::inner_core_rot_z_coriolis_rlm(), sum_rot_coriolis_terms_rlm::sum_rot_coriolis_lrm_10(), and sum_rot_coriolis_terms_rlm::sum_rot_coriolis_rlm_10().
Referenced by sph_trans_w_coriols::sph_b_trans_licv(), and sph_trans_w_coriols::sph_b_trans_w_coriolis().