CALYPSO: t_control_array_int2real2 Module Reference
t_control_array_int2real2 Module Reference
Data Types
type ctl_array_i2r2
Structure for 2 reals and 2 integeres control array.
type read_int2_real2_item
structure of control item with three characters
Functions/Subroutines
subroutine read_int2real2_ctl_type (c_buf, label, i2r2_item)
subroutine write_int2real2_ctl_type (id_file, level, label, i2r2_item)
subroutine copy_int2real2_ctl (org_i2r2, new_i2r2)
subroutine alloc_control_array_i2_r2 (array_i2r2)
subroutine dealloc_control_array_i2_r2 (array_i2r2)
subroutine read_control_array_i2_r2 (id_control, label, array_i2r2, c_buf)
subroutine write_control_array_i2_r2 (id_control, level, label, array_i2r2)
subroutine append_control_array_i2_r2 (read_i2r2, array_i2r2)
subroutine copy_control_array_i2_r2 (num_copy, org_i2r2, tgt_i2r2)
subroutine append_control_item_i2_r2 (read_i2r2, array_i2r2)
Function/Subroutine Documentation
alloc_control_array_i2_r2()
subroutine t_control_array_int2real2::alloc_control_array_i2_r2 (type(ctl_array_i2r2), intent(inout) array_i2r2)
Definition at line 142 of file t_control_array_int2real2.f90.
Referenced by append_control_array_i2_r2(), bcast_control_arrays::bcast_ctl_array_i2r2(), and read_control_array_i2_r2().
append_control_array_i2_r2()
subroutine t_control_array_int2real2::append_control_array_i2_r2 (type(read_int2_real2_item), intent(inout) read_i2r2, type(ctl_array_i2r2), intent(inout) array_i2r2)
Definition at line 241 of file t_control_array_int2real2.f90.
References alloc_control_array_i2_r2(), append_control_item_i2_r2(), copy_control_array_i2_r2(), and dealloc_control_array_i2_r2().
Referenced by read_control_array_i2_r2().
append_control_item_i2_r2()
subroutine t_control_array_int2real2::append_control_item_i2_r2 (type(read_int2_real2_item), intent(in) read_i2r2, type(ctl_array_i2r2), intent(inout) array_i2r2)
Definition at line 285 of file t_control_array_int2real2.f90.
Referenced by append_control_array_i2_r2().
copy_control_array_i2_r2()
subroutine t_control_array_int2real2::copy_control_array_i2_r2 (integer(kind = kint), intent(in) num_copy, type(ctl_array_i2r2), intent(in) org_i2r2, type(ctl_array_i2r2), intent(inout) tgt_i2r2)
Definition at line 266 of file t_control_array_int2real2.f90.
Referenced by append_control_array_i2_r2().
copy_int2real2_ctl()
subroutine t_control_array_int2real2::copy_int2real2_ctl (type(read_int2_real2_item), intent(in) org_i2r2, type(read_int2_real2_item), intent(inout) new_i2r2)
Definition at line 127 of file t_control_array_int2real2.f90.
dealloc_control_array_i2_r2()
subroutine t_control_array_int2real2::dealloc_control_array_i2_r2 (type(ctl_array_i2r2), intent(inout) array_i2r2)
Definition at line 162 of file t_control_array_int2real2.f90.
Referenced by append_control_array_i2_r2().
read_control_array_i2_r2()
subroutine t_control_array_int2real2::read_control_array_i2_r2 (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) label, type(ctl_array_i2r2), intent(inout) array_i2r2, type(buffer_for_control), intent(inout) c_buf)
Definition at line 177 of file t_control_array_int2real2.f90.
References alloc_control_array_i2_r2(), append_control_array_i2_r2(), t_read_control_elements::check_array_flag(), t_read_control_elements::check_end_array_flag(), t_read_control_elements::load_one_line_from_control(), and read_int2real2_ctl_type().
read_int2real2_ctl_type()
subroutine t_control_array_int2real2::read_int2real2_ctl_type (type(buffer_for_control), intent(in) c_buf, character(len=kchara), intent(in) label, type(read_int2_real2_item), intent(inout) i2r2_item)
Definition at line 82 of file t_control_array_int2real2.f90.
References m_machine_parameter::iflag_debug.
Referenced by read_control_array_i2_r2().
write_control_array_i2_r2()
subroutine t_control_array_int2real2::write_control_array_i2_r2 (integer(kind = kint), intent(in) id_control, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, type(ctl_array_i2r2), intent(in) array_i2r2)
Definition at line 211 of file t_control_array_int2real2.f90.
References write_control_elements::write_array_flag_for_ctl(), write_control_elements::write_end_array_flag_for_ctl(), and write_control_elements::write_i2_r2_ctl_item().
write_int2real2_ctl_type()
subroutine t_control_array_int2real2::write_int2real2_ctl_type (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, type(read_int2_real2_item), intent(in) i2r2_item)
Definition at line 107 of file t_control_array_int2real2.f90.
References write_control_elements::write_i2_r2_ctl_item().