CALYPSO: t_mid_equator_control Module Reference
t_mid_equator_control Module Reference
Data Types
type mid_equator_control
Functions/Subroutines
subroutine reset_mid_equator_control (meq_ctl)
subroutine read_mid_eq_monitor_ctl (id_control, hd_block, iflag, meq_ctl, c_buf)
Variables
character(len=kchara), parameter, private hd_nphi_mid_eq = 'nphi_mid_eq_ctl'
character(len=kchara), parameter, private hd_pick_s_ctl = 'pick_cylindrical_radius_ctl'
character(len=kchara), parameter, private hd_pick_z_ctl = 'pick_vertical_position_ctl'
character(len=kchara), parameter, private hd_circle_coord = 'pick_circle_coord_ctl'
Function/Subroutine Documentation
read_mid_eq_monitor_ctl()
subroutine t_mid_equator_control::read_mid_eq_monitor_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, integer(kind = kint), intent(inout) iflag, type(mid_equator_control), intent(inout) meq_ctl, type(buffer_for_control), intent(inout) c_buf)
Definition at line 92 of file t_mid_equator_control.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_circle_coord, hd_nphi_mid_eq, hd_pick_s_ctl, hd_pick_z_ctl, t_read_control_elements::load_one_line_from_control(), t_control_array_character::read_chara_ctl_type(), t_control_array_integer::read_integer_ctl_type(), and t_control_array_real::read_real_ctl_type().
Referenced by t_ctl_data_4_sph_monitor::read_sph_monitoring_ctl().
reset_mid_equator_control()
subroutine t_mid_equator_control::reset_mid_equator_control (type(mid_equator_control), intent(inout) meq_ctl)
Definition at line 78 of file t_mid_equator_control.f90.
Referenced by t_ctl_data_4_sph_monitor::dealloc_sph_monitoring_ctl().
Variable Documentation
hd_circle_coord
character(len=kchara), parameter, private t_mid_equator_control::hd_circle_coord = 'pick_circle_coord_ctl' private
Definition at line 66 of file t_mid_equator_control.f90.
Referenced by read_mid_eq_monitor_ctl().
hd_nphi_mid_eq
character(len=kchara), parameter, private t_mid_equator_control::hd_nphi_mid_eq = 'nphi_mid_eq_ctl' private
Definition at line 60 of file t_mid_equator_control.f90.
Referenced by read_mid_eq_monitor_ctl().
hd_pick_s_ctl
character(len=kchara), parameter, private t_mid_equator_control::hd_pick_s_ctl = 'pick_cylindrical_radius_ctl' private
Definition at line 62 of file t_mid_equator_control.f90.
Referenced by read_mid_eq_monitor_ctl().
hd_pick_z_ctl
character(len=kchara), parameter, private t_mid_equator_control::hd_pick_z_ctl = 'pick_vertical_position_ctl' private
Definition at line 64 of file t_mid_equator_control.f90.
Referenced by read_mid_eq_monitor_ctl().