CALYPSO: /home/takumi kera/calypso/src/programs/data_utilities/TIME_HISTORIES/tave_picked_sph_spec_data.f90 File Reference
tave_picked_sph_spec_data.f90 File Reference
Functions/Subroutines
program tave_picked_sph_spec_data
Function/Subroutine Documentation
tave_picked_sph_spec_data()
program tave_picked_sph_spec_data
Definition at line 6 of file tave_picked_sph_spec_data.f90.
References t_picked_sph_spectr_data_io::dealloc_pick_sph_monitor_io(), m_constants::half, m_constants::one, t_picked_sph_spectr_data_io::open_sph_spec_read(), t_picked_sph_spectr_data_io::read_sph_spec_monitor(), and t_picked_sph_spectr_data_io::write_tave_sph_spec_monitor().