CALYPSO: set_surface_data_4_io Module Reference
set_surface_data_4_io Module Reference
Surface data transfer for IO.
Functions/Subroutines
subroutine copy_surf_connect_to_io (surf, nele, ele_IO, sfed_IO)
subroutine copy_surf_geometry_to_io (surf, nod_IO, sfed_IO)
subroutine copy_surf_connect_from_io (ele_IO, sfed_IO, surf, nele)
subroutine copy_surf_geometry_from_io (nod_IO, sfed_IO, surf)
Detailed Description
Surface data transfer for IO.
      subroutine copy_surf_connect_to_IO(surf, nele, ele_IO, sfed_IO)
      subroutine copy_surf_geometry_to_IO(surf, nod_IO, sfed_IO)
        type(surface_data), intent(inout) :: surf
        type(node_data), intent(inout) :: nod_IO
        type(element_data), intent(inout) :: ele_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
      subroutine copy_surf_connect_from_IO                            &
     &         (ele_IO, sfed_IO, surf, nele)
      subroutine copy_surf_geometry_from_IO(nod_IO, sfed_IO, surf)
        integer(kind = kint), intent(in) :: nele
        type(element_data), intent(in) :: ele_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
        type(surface_data), intent(inout) :: surf
Function/Subroutine Documentation
copy_surf_connect_from_io()
subroutine set_surface_data_4_io::copy_surf_connect_from_io (type(element_data), intent(in) ele_IO, type(surf_edge_io_data), intent(in) sfed_IO, type(surface_data), intent(inout) surf, integer(kind = kint), intent(in) nele)
Definition at line 124 of file set_surface_data_4_IO.f90.
References t_surface_data::allocate_surface_connect_type(), and m_geometry_constants::nsurf_4_ele.
Referenced by load_element_mesh_data::set_surface_mesh_from_io().
copy_surf_connect_to_io()
subroutine set_surface_data_4_io::copy_surf_connect_to_io (type(surface_data), intent(in) surf, integer(kind = kint), intent(in) nele, type(element_data), intent(inout) ele_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 44 of file set_surface_data_4_IO.f90.
References t_surf_edge_io::alloc_surface_connect_io(), t_geometry_data::allocate_ele_connect_type(), m_geometry_constants::nsurf_4_ele, m_geometry_constants::num_lag_sf, m_geometry_constants::num_linear_sf, and m_geometry_constants::num_quad_sf.
Referenced by load_element_mesh_data::set_surface_mesh_to_io().
copy_surf_geometry_from_io()
subroutine set_surface_data_4_io::copy_surf_geometry_from_io (type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO, type(surface_data), intent(inout) surf)
Definition at line 157 of file set_surface_data_4_IO.f90.
References t_surface_data::allocate_normal_vect_type(), and t_surface_data::allocate_surface_geom_type().
copy_surf_geometry_to_io()
subroutine set_surface_data_4_io::copy_surf_geometry_to_io (type(surface_data), intent(in) surf, type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 88 of file set_surface_data_4_IO.f90.
References t_surf_edge_io::alloc_ele_scalar_io(), t_surf_edge_io::alloc_ele_vector_io(), and t_geometry_data::alloc_node_geometry_base().