CALYPSO: r_interpolate_sph_data Module Reference
r_interpolate_sph_data Module Reference
Functions/Subroutines
subroutine copy_cmb_icb_radial_point (nlayer_ICB, nlayer_CMB)
subroutine set_cmb_icb_radial_point (cmb_r_grp, icb_r_grp, radial_rj_grp)
subroutine, private allocate_original_sph_data
subroutine deallocate_original_sph_data
subroutine set_sph_magne_address (rj_fld, ipol)
subroutine input_old_rj_sph_trans (rj_file_param, l_truncation, sph_rj)
subroutine r_interpolate_sph_rst_from_io (fld_IO, sph_rj, ipol, rj_fld)
subroutine r_interpolate_sph_fld_from_io (fld_IO, sph_rj, ipol, rj_fld)
subroutine set_poloidal_b_by_gauss_coefs (sph_rj, ipol, d_gauss, rj_fld)
subroutine, private copy_original_sph_rj_from_io (l_truncation, sph_rj, sph_IO)
Variables
integer(kind=kint) kr_inside
integer(kind=kint) kr_outside
integer(kind=kint) nri_org
integer(kind=kint) n_rj_org
integer(kind=kint), dimension(:,:), allocatable k_inter
real(kind=kreal), dimension(:,:), allocatable rcoef_inter
real(kind=kreal), dimension(:), allocatable r_org
integer(kind=kint) ntot_phys_rj_itp
real(kind=kreal), dimension(:,:), allocatable d_rj_org
Function/Subroutine Documentation
allocate_original_sph_data()
subroutine, private r_interpolate_sph_data::allocate_original_sph_data private
Definition at line 110 of file r_interpolate_sph_data.f90.
References d_rj_org, m_constants::izero, k_inter, n_rj_org, nri_org, r_org, rcoef_inter, and m_constants::zero.
Referenced by copy_original_sph_rj_from_io().
copy_cmb_icb_radial_point()
subroutine r_interpolate_sph_data::copy_cmb_icb_radial_point (integer(kind = kint), intent(in) nlayer_ICB, integer(kind = kint), intent(in) nlayer_CMB)
Definition at line 64 of file r_interpolate_sph_data.f90.
References kr_inside, and kr_outside.
Referenced by sph_mhd_rst_io_control::init_radial_sph_interpolation().
copy_original_sph_rj_from_io()
subroutine, private r_interpolate_sph_data::copy_original_sph_rj_from_io (integer(kind = kint), intent(in) l_truncation, type(sph_rj_grid), intent(in) sph_rj, type(sph_io_data), intent(in) sph_IO) private
Definition at line 333 of file r_interpolate_sph_data.f90.
References allocate_original_sph_data(), calypso_mpi::calypso_mpi_abort(), m_error_ids::ierr_sph, n_rj_org, nri_org, and r_org.
Referenced by input_old_rj_sph_trans().
deallocate_original_sph_data()
subroutine r_interpolate_sph_data::deallocate_original_sph_data
Definition at line 128 of file r_interpolate_sph_data.f90.
References d_rj_org, k_inter, r_org, and rcoef_inter.
input_old_rj_sph_trans()
subroutine r_interpolate_sph_data::input_old_rj_sph_trans (type(field_io_params), intent(in) rj_file_param, integer(kind = kint), intent(inout) l_truncation, type(sph_rj_grid), intent(inout) sph_rj)
Definition at line 158 of file r_interpolate_sph_data.f90.
References radial_interpolation::const_radial_itp_table(), copy_original_sph_rj_from_io(), t_spheric_data_io::dealloc_rj_mode_io(), k_inter, kr_inside, kr_outside, calypso_mpi::my_rank, calypso_mpi::nprocs, nri_org, r_org, rcoef_inter, and sph_file_mpi_io_select::sel_mpi_read_spectr_rj_file().
Referenced by sph_mhd_rst_io_control::init_radial_sph_interpolation().
r_interpolate_sph_fld_from_io()
subroutine r_interpolate_sph_data::r_interpolate_sph_fld_from_io (type(field_io), intent(in) fld_IO, type(sph_rj_grid), intent(in) sph_rj, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld)
Definition at line 257 of file r_interpolate_sph_data.f90.
References d_rj_org, extend_potential_field::ext_inside_potential(), extend_potential_field::ext_outside_potential(), k_inter, kr_inside, kr_outside, n_rj_org, nri_org, radial_interpolation::r_interpolate_sph_vector(), rcoef_inter, and radial_interpolation::set_org_rj_phys_data_from_io().
Referenced by sph_mhd_rst_io_control::read_alloc_sph_spectr().
r_interpolate_sph_rst_from_io()
subroutine r_interpolate_sph_data::r_interpolate_sph_rst_from_io (type(field_io), intent(in) fld_IO, type(sph_rj_grid), intent(in) sph_rj, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld)
Definition at line 191 of file r_interpolate_sph_data.f90.
References m_base_field_labels::composition, m_base_field_labels::composition_source, d_rj_org, m_base_field_labels::entropy, m_base_field_labels::entropy_source, extend_potential_field::ext_inside_potential(), extend_potential_field::ext_outside_potential(), m_base_field_labels::heat_source, k_inter, kr_inside, kr_outside, m_base_field_labels::magnetic_field, m_base_field_labels::magnetic_potential, n_rj_org, nri_org, m_base_field_labels::pressure, m_explicit_term_labels::previous_composition, m_explicit_term_labels::previous_heat, m_explicit_term_labels::previous_induction, m_explicit_term_labels::previous_momentum, radial_interpolation::r_interpolate_sph_vector(), rcoef_inter, radial_interpolation::set_org_rj_phys_data_from_io(), m_base_field_labels::temperature, m_base_field_labels::velocity, and m_base_field_labels::vorticity.
Referenced by sph_mhd_rst_io_control::read_alloc_sph_rst_4_snap().
set_cmb_icb_radial_point()
subroutine r_interpolate_sph_data::set_cmb_icb_radial_point (character(len = kchara), intent(in) cmb_r_grp, character(len = kchara), intent(in) icb_r_grp, type(group_data), intent(in) radial_rj_grp)
Definition at line 76 of file r_interpolate_sph_data.f90.
References kr_inside, and kr_outside.
set_poloidal_b_by_gauss_coefs()
subroutine r_interpolate_sph_data::set_poloidal_b_by_gauss_coefs (type(sph_rj_grid), intent(in) sph_rj, type(phys_address), intent(in) ipol, type(global_gauss_points), intent(in) d_gauss, type(phys_data), intent(inout) rj_fld)
Definition at line 303 of file r_interpolate_sph_data.f90.
References extend_potential_field::gauss_to_poloidal_in(), extend_potential_field::gauss_to_poloidal_out(), kr_inside, and kr_outside.
set_sph_magne_address()
subroutine r_interpolate_sph_data::set_sph_magne_address (type(phys_data), intent(in) rj_fld, type(phys_address), intent(inout) ipol)
Definition at line 138 of file r_interpolate_sph_data.f90.
References m_base_field_labels::magnetic_field.
Variable Documentation
d_rj_org
real(kind = kreal), dimension(:,:), allocatable r_interpolate_sph_data::d_rj_org
Definition at line 53 of file r_interpolate_sph_data.f90.
Referenced by allocate_original_sph_data(), deallocate_original_sph_data(), r_interpolate_sph_fld_from_io(), and r_interpolate_sph_rst_from_io().
k_inter
integer(kind = kint), dimension(:,:), allocatable r_interpolate_sph_data::k_inter
Definition at line 47 of file r_interpolate_sph_data.f90.
Referenced by allocate_original_sph_data(), deallocate_original_sph_data(), input_old_rj_sph_trans(), r_interpolate_sph_fld_from_io(), and r_interpolate_sph_rst_from_io().
kr_inside
integer(kind = kint) r_interpolate_sph_data::kr_inside
Definition at line 44 of file r_interpolate_sph_data.f90.
Referenced by copy_cmb_icb_radial_point(), input_old_rj_sph_trans(), r_interpolate_sph_fld_from_io(), r_interpolate_sph_rst_from_io(), set_cmb_icb_radial_point(), and set_poloidal_b_by_gauss_coefs().
kr_outside
integer(kind = kint) r_interpolate_sph_data::kr_outside
Definition at line 44 of file r_interpolate_sph_data.f90.
Referenced by copy_cmb_icb_radial_point(), input_old_rj_sph_trans(), r_interpolate_sph_fld_from_io(), r_interpolate_sph_rst_from_io(), set_cmb_icb_radial_point(), and set_poloidal_b_by_gauss_coefs().
n_rj_org
integer(kind = kint) r_interpolate_sph_data::n_rj_org
Definition at line 46 of file r_interpolate_sph_data.f90.
Referenced by allocate_original_sph_data(), copy_original_sph_rj_from_io(), r_interpolate_sph_fld_from_io(), and r_interpolate_sph_rst_from_io().
nri_org
integer(kind = kint) r_interpolate_sph_data::nri_org
Definition at line 46 of file r_interpolate_sph_data.f90.
Referenced by allocate_original_sph_data(), copy_original_sph_rj_from_io(), input_old_rj_sph_trans(), r_interpolate_sph_fld_from_io(), and r_interpolate_sph_rst_from_io().
ntot_phys_rj_itp
integer(kind = kint) r_interpolate_sph_data::ntot_phys_rj_itp
Definition at line 52 of file r_interpolate_sph_data.f90.
r_org
real(kind = kreal), dimension(:), allocatable r_interpolate_sph_data::r_org
Definition at line 50 of file r_interpolate_sph_data.f90.
Referenced by allocate_original_sph_data(), copy_original_sph_rj_from_io(), deallocate_original_sph_data(), and input_old_rj_sph_trans().
rcoef_inter
real(kind = kreal), dimension(:,:), allocatable r_interpolate_sph_data::rcoef_inter
Definition at line 48 of file r_interpolate_sph_data.f90.
Referenced by allocate_original_sph_data(), deallocate_original_sph_data(), input_old_rj_sph_trans(), r_interpolate_sph_fld_from_io(), and r_interpolate_sph_rst_from_io().