CALYPSO: const_merged_surf_4_group Module Reference
const_merged_surf_4_group Module Reference
Functions/Subroutines
subroutine, private allocate_iso_surf_4_egrp_tmp (ntot)
subroutine, private deallocate_iso_surf_4_egrp_tmp
subroutine const_merged_surface_4_ele_grp (node, ele, group, surf, mgd_sf_grp)
subroutine const_merged_surface_4_sf_grp (group, surf, mgd_sf_grp)
Variables
type(sum_hash_tbl), save, private surf_ele_tbl
integer(kind=kint), dimension(:), allocatable, private isf_isolate_ele_grp_tmp
Function/Subroutine Documentation
allocate_iso_surf_4_egrp_tmp()
subroutine, private const_merged_surf_4_group::allocate_iso_surf_4_egrp_tmp (integer(kind = kint), intent(in) ntot) private
Definition at line 38 of file const_merged_surf_4_group.f90.
References isf_isolate_ele_grp_tmp.
Referenced by const_merged_surface_4_ele_grp().
const_merged_surface_4_ele_grp()
subroutine const_merged_surf_4_group::const_merged_surface_4_ele_grp (type(node_data), intent(in) node, type(element_data), intent(in) ele, type(mesh_groups), intent(in) group, type(surface_data), intent(inout) surf, type(viewer_ele_grp_surface), intent(inout) mgd_sf_grp)
Definition at line 58 of file const_merged_surf_4_group.f90.
References t_viewer_ele_grp_surface::alloc_iso_surf_4_egrp_m(), t_viewer_ele_grp_surface::alloc_n_iso_surf_4_ele_grp(), t_sum_hash::alloc_sum_hash(), allocate_iso_surf_4_egrp_tmp(), const_surface_data::const_part_surface_hash(), set_surface_data::count_part_surface(), t_viewer_ele_grp_surface::dealloc_iso_surf_4_egrp_m(), t_sum_hash::dealloc_sum_hash(), deallocate_iso_surf_4_egrp_tmp(), isf_isolate_ele_grp_tmp, mark_surf_hash::mark_independent_surface(), set_surface_data::set_part_surface(), and surf_ele_tbl.
Referenced by const_kemoview_mesh::const_surf_mesh_4_viewer().
const_merged_surface_4_sf_grp()
subroutine const_merged_surf_4_group::const_merged_surface_4_sf_grp (type(mesh_groups), intent(in) group, type(surface_data), intent(in) surf, type(viewer_ele_grp_surface), intent(inout) mgd_sf_grp)
Definition at line 149 of file const_merged_surf_4_group.f90.
References t_viewer_ele_grp_surface::alloc_iso_surf_4_sgrp_m().
Referenced by const_kemoview_mesh::const_surf_mesh_4_viewer().
deallocate_iso_surf_4_egrp_tmp()
subroutine, private const_merged_surf_4_group::deallocate_iso_surf_4_egrp_tmp private
Definition at line 49 of file const_merged_surf_4_group.f90.
References isf_isolate_ele_grp_tmp.
Referenced by const_merged_surface_4_ele_grp().
Variable Documentation
isf_isolate_ele_grp_tmp
integer(kind=kint), dimension(:), allocatable, private const_merged_surf_4_group::isf_isolate_ele_grp_tmp private
Definition at line 26 of file const_merged_surf_4_group.f90.
Referenced by allocate_iso_surf_4_egrp_tmp(), const_merged_surface_4_ele_grp(), and deallocate_iso_surf_4_egrp_tmp().
surf_ele_tbl
type(sum_hash_tbl), save, private const_merged_surf_4_group::surf_ele_tbl private
Definition at line 25 of file const_merged_surf_4_group.f90.
Referenced by const_merged_surface_4_ele_grp().