CALYPSO: construct_mhd_coefficient Module Reference
construct_mhd_coefficient Module Reference
Subroutine to construct coeeficient from dimansionless numbers.
Functions/Subroutines
subroutine construct_coefficient (coef, dless_list, power_list, r_low_t, r_high_t)
subroutine set_implicit_4_inf_viscous (coef_field, coef_imp, coef_exp)
Detailed Description
Subroutine to construct coeeficient from dimansionless numbers.
      subroutine construct_coefficient                                &
     &         (coef, dless_list, power_list, r_low_t, r_high_t)
        type(list_of_dimless), intent(in) :: dless_list
        type(powers_4_coefficients), intent(inout) :: power_list
      subroutine set_implicit_4_inf_viscous(coef_field,               &
     &          coef_imp, coef_exp)
Parameters
coef Coefficient of term (output)
Parameters
dimless_list List of dimensionless numbers
Parameters
num_coef Number of dimensionless number to construct
coef_name(num_coef) Name of dimensionless number to construct
coef_power(num_coef) Power of dimensionless number to construct
Parameters
r_low_t Radius at low reference tomperature
r_high_t Radius at high reference tomperature
Parameters
coef_field Coefficient for evolution of field
coef_imp Contribution of implicit term
coef_exp Contribution of explicit term
Function/Subroutine Documentation
construct_coefficient()
subroutine construct_mhd_coefficient::construct_coefficient (real(kind = kreal), intent(inout) coef, type(list_of_dimless), intent(in) dless_list, type(powers_4_coefficients), intent(inout) power_list, real(kind = kreal), intent(in) r_low_t, real(kind = kreal), intent(in) r_high_t)
Definition at line 50 of file construct_MHD_coefficient.f90.
References calypso_mpi::calypso_mpi_abort(), skip_comment_f::cmp_no_case(), t_normalize_parameter::dealloc_coef_power_list(), m_machine_parameter::e_message, m_error_ids::ierr_dless, m_constants::one, m_constants::two, and m_constants::zero.
Referenced by material_property::set_composition_property(), material_property::set_conductive_property(), material_property::set_fluid_property(), and material_property::set_thermal_property().
set_implicit_4_inf_viscous()
subroutine construct_mhd_coefficient::set_implicit_4_inf_viscous (real(kind = kreal), intent(in) coef_field, real(kind = kreal), intent(inout) coef_imp, real(kind = kreal), intent(inout) coef_exp)
Definition at line 100 of file construct_MHD_coefficient.f90.
References m_constants::one, and m_constants::zero.
Referenced by material_property::set_composition_property(), material_property::set_conductive_property(), material_property::set_fluid_property(), and material_property::set_thermal_property().