CALYPSO: t_normalize_parameter Module Reference
t_normalize_parameter Module Reference
dimensionless number list for each term
Data Types
type coef_parameters_list
List of parameters to construct coefficients.
type list_of_dimless
Structure of dimensionless numbers.
type powers_4_coefficients
Structure of powers for coefficients.
Functions/Subroutines
subroutine alloc_dimless_list (dimless_list)
subroutine alloc_coef_power_list (coefs_list)
subroutine dealloc_dimless_list (dimless_list)
subroutine dealloc_coef_power_list (coefs_list)
Detailed Description
dimensionless number list for each term
      subroutine alloc_dimless_list(dimless_list)
      subroutine dealloc_dimless_list(dimless_list)
        type(list_of_dimless), intent(inout) :: dimless_list
      subroutine alloc_coef_power_list(coefs_list)
      subroutine dealloc_coef_power_list(coefs_list)
        type(powers_4_coefficients), intent(inout) :: coefs_list
Function/Subroutine Documentation
alloc_coef_power_list()
subroutine t_normalize_parameter::alloc_coef_power_list (type(powers_4_coefficients), intent(inout) coefs_list)
Definition at line 110 of file t_normalize_parameter.f90.
Referenced by set_control_4_normalize::copy_power_and_names_from_ctl().
alloc_dimless_list()
subroutine t_normalize_parameter::alloc_dimless_list (type(list_of_dimless), intent(inout) dimless_list)
Definition at line 97 of file t_normalize_parameter.f90.
Referenced by set_control_4_normalize::copy_dimless_from_ctl().
dealloc_coef_power_list()
subroutine t_normalize_parameter::dealloc_coef_power_list (type(powers_4_coefficients), intent(inout) coefs_list)
Definition at line 135 of file t_normalize_parameter.f90.
Referenced by construct_mhd_coefficient::construct_coefficient().
dealloc_dimless_list()
subroutine t_normalize_parameter::dealloc_dimless_list (type(list_of_dimless), intent(inout) dimless_list)
Definition at line 124 of file t_normalize_parameter.f90.