CALYPSO: mpi_element_connect_io_b Module Reference
mpi_element_connect_io_b Module Reference
Data IO routines for element connectivity.
Functions/Subroutines
subroutine mpi_write_element_info_b (IO_param, ele_IO)
subroutine mpi_write_surface_4_element_b (IO_param, sfed_IO)
subroutine mpi_write_edge_4_element_b (IO_param, sfed_IO)
subroutine mpi_read_number_of_element_b (IO_param, ele_IO)
subroutine mpi_read_element_info_b (IO_param, ele_IO)
subroutine mpi_read_surface_4_element_b (IO_param, sfed_IO)
subroutine mpi_read_edge_4_element_b (IO_param, sfed_IO)
Detailed Description
Data IO routines for element connectivity.
      subroutine mpi_write_element_info_b(IO_param, ele_IO)
      subroutine mpi_write_surface_4_element_b(IO_param, sfed_IO)
      subroutine mpi_write_edge_4_element_b(IO_param, sfed_IO)
        type(element_data), intent(in) :: ele_IO
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(surf_edge_IO_data), intent(in) :: sfed_IO
      subroutine mpi_read_element_info_b(IO_param, ele_IO)
      subroutine mpi_read_surface_4_element_b(IO_param, sfed_IO)
      subroutine mpi_read_edge_4_element_b(IO_param, sfed_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(element_data), intent(inout) :: ele_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
Function/Subroutine Documentation
mpi_read_edge_4_element_b()
subroutine mpi_element_connect_io_b::mpi_read_edge_4_element_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 179 of file MPI_element_connect_IO_b.f90.
References t_surf_edge_io::alloc_edge_connect_io(), mpi_binary_data_io::mpi_read_int_vector_b(), and mpi_binary_data_io::mpi_read_one_integer_b().
Referenced by mpi_edge_data_io_b::mpi_read_edge_connection_b().
mpi_read_element_info_b()
subroutine mpi_element_connect_io_b::mpi_read_element_info_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(element_data), intent(inout) ele_IO)
Definition at line 122 of file MPI_element_connect_IO_b.f90.
References t_geometry_data::alloc_ele_connectivity(), t_geometry_data::alloc_element_types(), mpi_binary_data_io::mpi_read_int8_vector_b(), mpi_binary_data_io::mpi_read_int_vector_b(), and set_nnod_4_ele_by_type::s_set_nnod_4_ele_by_type().
Referenced by mpi_edge_data_io_b::mpi_read_edge_connection_b(), and mpi_surface_data_io_b::mpi_read_surface_connection_b().
mpi_read_number_of_element_b()
subroutine mpi_element_connect_io_b::mpi_read_number_of_element_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(element_data), intent(inout) ele_IO)
Definition at line 110 of file MPI_element_connect_IO_b.f90.
References mpi_binary_data_io::mpi_read_one_integer_b().
Referenced by mpi_edge_data_io_b::mpi_read_edge_connection_b(), and mpi_surface_data_io_b::mpi_read_surface_connection_b().
mpi_read_surface_4_element_b()
subroutine mpi_element_connect_io_b::mpi_read_surface_4_element_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 158 of file MPI_element_connect_IO_b.f90.
References t_surf_edge_io::alloc_surface_connect_io(), mpi_binary_data_io::mpi_read_int_vector_b(), and mpi_binary_data_io::mpi_read_one_integer_b().
Referenced by mpi_edge_data_io_b::mpi_read_edge_connection_b(), and mpi_surface_data_io_b::mpi_read_surface_connection_b().
mpi_write_edge_4_element_b()
subroutine mpi_element_connect_io_b::mpi_write_edge_4_element_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 89 of file MPI_element_connect_IO_b.f90.
References t_calypso_mpi_io_param::istack64_4_parallel_data(), mpi_binary_data_io::mpi_write_int_vector_b(), and mpi_binary_data_io::mpi_write_one_integer_b().
Referenced by mpi_edge_data_io_b::mpi_write_edge_connection_b().
mpi_write_element_info_b()
subroutine mpi_element_connect_io_b::mpi_write_element_info_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(element_data), intent(in) ele_IO)
Definition at line 46 of file MPI_element_connect_IO_b.f90.
References t_calypso_mpi_io_param::istack64_4_parallel_data(), mpi_binary_data_io::mpi_write_int8_vector_b(), mpi_binary_data_io::mpi_write_int_vector_b(), mpi_binary_data_io::mpi_write_one_integer_b(), and t_calypso_mpi_io_param::mul_istack_4_parallell_vect().
Referenced by mpi_edge_data_io_b::mpi_write_edge_connection_b(), and mpi_surface_data_io_b::mpi_write_surface_connection_b().
mpi_write_surface_4_element_b()
subroutine mpi_element_connect_io_b::mpi_write_surface_4_element_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 70 of file MPI_element_connect_IO_b.f90.
References t_calypso_mpi_io_param::istack64_4_parallel_data(), mpi_binary_data_io::mpi_write_int_vector_b(), and mpi_binary_data_io::mpi_write_one_integer_b().
Referenced by mpi_edge_data_io_b::mpi_write_edge_connection_b(), and mpi_surface_data_io_b::mpi_write_surface_connection_b().