CALYPSO: transfer_to_long_integers Module Reference
transfer_to_long_integers Module Reference
Data Types
type tmp_i8_2darray
type tmp_i8_array
Functions/Subroutines
integer(kind=kint_gl) function cast_long (i_in)
integer(kind=kint) function cast_short (i8_in)
integer(kind=kint) function cast_kint (i4_in)
subroutine alloc_1d_i8array (n1, tmp)
subroutine dealloc_1d_i8array (tmp)
subroutine dup_from_short_array (n1, i4_out, tmp)
subroutine dup_to_short_array (tmp, i4_out)
subroutine alloc_2d_i8array (n1, n2, tmp)
subroutine dealloc_2d_i8array (tmp)
subroutine dup_from_short_darray (n1, n2, i4_out, tmp)
subroutine dup_to_short_darray (tmp, i4_out)
Function/Subroutine Documentation
alloc_1d_i8array()
subroutine transfer_to_long_integers::alloc_1d_i8array (integer(kind = kint_gl), intent(in) n1, type(tmp_i8_array), intent(inout) tmp)
Definition at line 81 of file transfer_to_long_integers.f90.
Referenced by dup_from_short_array(), gz_mpi_binary_data_io::gz_mpi_read_int_vector_b(), gz_mpi_binary_head_io::gz_mpi_read_mul_inthead_b(), gz_binary_io::gz_read_mul_integer_b(), mpi_binary_data_io::mpi_read_int_vector_b(), mpi_binary_head_io::mpi_read_mul_inthead_b(), mpi_binary_data_io::mpi_read_one_integer_b(), and binary_io::read_mul_integer_b().
alloc_2d_i8array()
subroutine transfer_to_long_integers::alloc_2d_i8array (integer(kind = kint_gl), intent(in) n1, integer(kind = kint_gl), intent(in) n2, type(tmp_i8_2darray), intent(inout) tmp)
Definition at line 142 of file transfer_to_long_integers.f90.
Referenced by dup_from_short_darray(), set_patches_for_psf::set_iso_patches(), and set_patches_for_psf::set_psf_patches().
cast_kint()
integer(kind = kint) function transfer_to_long_integers::cast_kint (integer i4_in)
Definition at line 70 of file transfer_to_long_integers.f90.
cast_long()
integer(kind = kint_gl) function transfer_to_long_integers::cast_long (integer(kind = kint), intent(in) i_in)
Definition at line 50 of file transfer_to_long_integers.f90.
Referenced by bcast_control_arrays::bcast_ctl_array_c1(), bcast_control_arrays::bcast_ctl_array_c2(), bcast_control_arrays::bcast_ctl_array_c2r(), bcast_control_arrays::bcast_ctl_array_c3(), bcast_control_arrays::bcast_ctl_array_ci(), bcast_control_arrays::bcast_ctl_array_ci3(), bcast_control_arrays::bcast_ctl_array_cr(), bcast_control_arrays::bcast_ctl_array_cr2(), bcast_control_arrays::bcast_ctl_array_i1(), bcast_control_arrays::bcast_ctl_array_i2(), bcast_control_arrays::bcast_ctl_array_i2r(), bcast_control_arrays::bcast_ctl_array_i2r2(), bcast_control_arrays::bcast_ctl_array_i3(), bcast_control_arrays::bcast_ctl_array_icr(), bcast_control_arrays::bcast_ctl_array_ir(), bcast_control_arrays::bcast_ctl_array_r1(), bcast_control_arrays::bcast_ctl_array_r2(), bcast_control_arrays::bcast_ctl_array_r3(), bcast_control_arrays::bcast_ctl_type_c1(), bcast_control_arrays::bcast_ctl_type_c3(), bcast_control_arrays::bcast_ctl_type_c_i3(), bcast_control_arrays::bcast_ctl_type_i2(), bcast_control_arrays::bcast_ctl_type_i3(), bcast_control_arrays::bcast_ctl_type_r2(), bcast_control_arrays::bcast_ctl_type_r3(), t_each_sph_boundary_io_data::bcast_each_bc_item_ctl(), t_each_sph_boundary_io_data::bcast_each_bc_item_num(), bcast_file_io_parameter::bcast_field_io_parameter(), t_control_data_isosurfaces::bcast_files_4_iso_ctl(), t_control_data_sections::bcast_files_4_psf_ctl(), t_ctl_data_gen_sph_shell::bcast_parallel_shell_ctl(), init_sph_mhd_elapsed_label::check_num_of_process_4_sph(), const_fem_mesh_sph_mhd::const_global_rtp_mesh(), data_convert_by_zlib::defleate_1d_character_b(), data_convert_by_zlib::defleate_1d_vector_b(), data_convert_by_zlib::defleate_int8_vector_b(), const_element_comm_tables::find_position_range(), gz_mpi_ascii_data_io::gz_mpi_read_charahead(), gz_mpi_node_geometry_io::gz_mpi_read_geometry_info(), gz_mpi_binary_head_io::gz_mpi_read_mul_charahead_b(), gz_mpi_binary_head_io::gz_mpi_read_mul_inthead_b(), gz_mpi_binary_head_io::gz_mpi_read_mul_realhead_b(), gz_mpi_node_geometry_io::gz_mpi_read_scl_in_ele(), gz_mpi_node_geometry_io::gz_mpi_read_vect_in_ele(), gz_mpi_node_geometry_io::gz_mpi_write_geometry_info(), gz_mpi_binary_head_io::gz_mpi_write_mul_inthead_b(), gz_mpi_node_geometry_io::gz_mpi_write_scl_in_ele(), gz_mpi_node_geometry_io::gz_mpi_write_vect_in_ele(), gz_mpi_viewer_mesh_io::gz_mpi_write_viewer_grp_data(), gz_field_file_io_b::gz_rd_alloc_st_fld_file_b(), gz_field_file_io_b::gz_rd_alloc_st_fld_head_b(), gz_domain_data_io_b::gz_read_domain_info_b(), gz_field_data_mpi_io::gz_read_each_field_mpi(), gz_element_connect_io_b::gz_read_edge_4_element_b(), gz_element_connect_io_b::gz_read_element_info_b(), gz_domain_data_io_b::gz_read_export_data_b(), gz_field_data_io_b::gz_read_field_data_b(), gz_node_geometry_io_b::gz_read_geometry_info_b(), gz_spherical_model_io_b::gz_read_gl_nodes_sph_b(), gz_spherical_model_io_b::gz_read_gl_resolution_sph_b(), gz_groups_io_b::gz_read_group_data_b(), gz_domain_data_io_b::gz_read_import_data_b(), gz_spherical_model_io_b::gz_read_rank_4_sph_b(), gz_sph_global_1d_idx_io_b::gz_read_rj_gl_1d_table_b(), gz_sph_global_1d_idx_io_b::gz_read_rtp_gl_1d_table_b(), gz_node_geometry_io_b::gz_read_scalar_in_element_b(), gz_field_file_io_b::gz_read_step_field_file_b(), gz_groups_io_b::gz_read_surf_grp_data_b(), gz_element_connect_io_b::gz_read_surface_4_element_b(), gz_node_geometry_io_b::gz_read_vector_in_element_b(), gz_field_data_mpi_io::gz_skip_each_field_mpi(), gz_domain_data_io_b::gz_write_domain_info_b(), gz_element_connect_io_b::gz_write_edge_4_element_b(), gz_element_connect_io_b::gz_write_element_info_b(), gz_domain_data_io_b::gz_write_export_data_b(), gz_field_data_io_b::gz_write_field_data_b(), gz_node_geometry_io_b::gz_write_geometry_info_b(), gz_spherical_model_io_b::gz_write_gl_nodes_sph_b(), gz_spherical_model_io_b::gz_write_gl_resolution_sph_b(), gz_groups_io_b::gz_write_grp_data_b(), gz_domain_data_io_b::gz_write_import_data_b(), gz_binary_io::gz_write_one_integer_b(), gz_spherical_model_io_b::gz_write_rank_4_sph_b(), gz_sph_global_1d_idx_io_b::gz_write_rj_gl_1d_table_b(), gz_sph_global_1d_idx_io_b::gz_write_rtp_gl_1d_table_b(), gz_node_geometry_io_b::gz_write_scalar_in_element_b(), gz_field_file_io_b::gz_write_step_fld_file_b(), gz_field_file_mpi_io_b::gz_write_step_fld_file_mpi_b(), gz_groups_io_b::gz_write_surf_grp_data_b(), gz_element_connect_io_b::gz_write_surface_4_element_b(), gz_node_geometry_io_b::gz_write_vector_in_element_b(), gz_mpi_viewer_mesh_file_io::gz_write_viewer_mesh_infos(), data_convert_by_zlib::infleate_1d_character_b(), data_convert_by_zlib::infleate_1d_vector_b(), data_convert_by_zlib::infleate_int8_vector_b(), rayleigh_restart_io::init_rayleigh_restart_input(), mpi_ascii_data_io::mpi_read_charahead(), mpi_binary_head_io::mpi_read_mul_charahead_b(), mpi_binary_data_io::mpi_read_one_integer_b(), mpi_domain_data_io_b::mpi_write_export_data_b(), mpi_groups_io_b::mpi_write_grp_data_b(), mpi_domain_data_io_b::mpi_write_import_data_b(), mpi_binary_head_io::mpi_write_mul_inthead_b(), mpi_binary_data_io::mpi_write_one_integer_b(), mpi_groups_io_b::mpi_write_surf_grp_data_b(), mpi_viewer_mesh_io::mpi_write_viewer_grp_data(), global_field_4_dynamobench::pick_inner_core_rotation(), global_field_4_dynamobench::pick_mag_torque_inner_core(), binary_io::read_2d_vector_b(), gz_field_file_io::read_alloc_gz_field_file(), gz_field_file_io::read_alloc_gz_step_field_file(), gz_field_file_io::read_alloc_gz_step_field_head(), field_file_mpi_io::read_alloc_step_fld_file_mpi(), gz_field_file_mpi_io::read_alloc_stp_fld_file_gz_mpi(), ucd_field_file_io_b::read_alloc_ucd_2_fld_file_b(), ucd_field_file_io_b::read_alloc_ucd_2_fld_header_b(), field_file_io::read_and_alloc_step_field(), field_file_io::read_and_allocate_field_file(), field_file_io_b::read_and_allocate_step_b(), field_file_io_b::read_and_allocate_step_field_b(), field_file_io::read_and_allocate_step_head(), domain_data_io_b::read_domain_info_b(), element_connect_io_b::read_element_info_b(), domain_data_io_b::read_export_data_b(), gz_field_block_mpi_io::read_field_header_gz_mpi(), field_block_mpi_io_b::read_field_header_mpi_b(), gz_field_block_mpi_io::read_field_num_gz_mpi(), field_data_mpi_io::read_field_num_mpi(), spherical_model_io_b::read_gl_nodes_sph_b(), spherical_model_io_b::read_gl_resolution_sph_b(), groups_io_b::read_group_data_b(), gz_rst_data_io_by_fld::read_gz_rst_file(), gz_field_file_io::read_gz_step_field_file(), domain_data_io_b::read_import_data_b(), read_psf_binary_data::read_psf_ele_connect_bin(), gz_read_psf_binary_data::read_psf_ele_connect_bin_gz(), read_psf_binary_data::read_psf_ele_num_bin(), gz_read_psf_binary_data::read_psf_ele_num_bin_gz(), read_psf_binary_data::read_psf_node_num_bin(), gz_read_psf_binary_data::read_psf_node_num_bin_gz(), read_psf_binary_data::read_psf_phys_data_bin(), gz_read_psf_binary_data::read_psf_phys_data_bin_gz(), read_psf_binary_data::read_psf_phys_name_bin(), gz_read_psf_binary_data::read_psf_phys_name_bin_gz(), spherical_model_io_b::read_rank_4_sph_b(), rst_data_io_by_fld::read_rst_file(), node_geometry_io_b::read_scalar_in_element_b(), field_file_io::read_step_field_file(), field_file_io_b::read_step_field_file_b(), gz_field_file_mpi_io::read_step_field_file_gz_mpi(), field_file_mpi_io::read_step_field_file_mpi(), groups_io_b::read_surf_grp_data_b(), ucd_field_file_io_b::read_ucd_2_fld_file_b(), node_geometry_io_b::read_vector_in_element_b(), test_legendre_transforms::s_test_legendre_transforms(), init_spherical_srs::sel_sph_import_table(), bcast_comm_stacks_sph::set_bcast_comm_stacks_sph(), set_patches_for_psf::set_iso_patches(), set_patches_for_psf::set_psf_patches(), share_field_data::share_field_io_names(), share_field_data::share_field_stack(), share_field_data::share_phys_field_names(), r_interpolate_marged_sph::share_r_interpolation_tbl(), share_spectr_index_data::share_sph_rj_data(), field_data_mpi_io::sync_field_name_mpi(), field_data_mpi_io::sync_field_names_mpi(), mpi_load_mesh_data::sync_group_name_4_empty(), binary_io::write_2d_vector_b(), domain_data_io_b::write_domain_info_b(), domain_data_io_b::write_export_data_b(), field_data_io_b::write_field_data_b(), field_block_mpi_io_b::write_field_data_mpi_b(), spherical_model_io_b::write_gl_nodes_sph_b(), spherical_model_io_b::write_gl_resolution_sph_b(), groups_io_b::write_grp_data_b(), gz_field_file_io::write_gz_step_field_file(), gz_field_file_mpi_io::write_gz_step_field_file_mpi(), domain_data_io_b::write_import_data_b(), binary_io::write_one_integer_b(), binary_io::write_one_integer_to_32bit(), spherical_model_io_b::write_rank_4_sph_b(), node_geometry_io_b::write_scalar_in_element_b(), mpi_sph_gauss_coefs_io::write_sph_gauss_header_mpi(), field_file_io::write_step_field_file(), field_file_io_b::write_step_field_file_b(), field_file_mpi_io::write_step_field_file_mpi(), field_file_mpi_io_b::write_step_field_file_mpi_b(), groups_io_b::write_surf_grp_data_b(), and node_geometry_io_b::write_vector_in_element_b().
cast_short()
integer(kind = kint) function transfer_to_long_integers::cast_short (integer(kind = kint_gl) i8_in)
Definition at line 60 of file transfer_to_long_integers.f90.
dealloc_1d_i8array()
subroutine transfer_to_long_integers::dealloc_1d_i8array (type(tmp_i8_array), intent(inout) tmp)
Definition at line 94 of file transfer_to_long_integers.f90.
Referenced by dup_to_short_array(), gz_mpi_binary_data_io::gz_mpi_write_int_vector_b(), gz_mpi_binary_head_io::gz_mpi_write_mul_inthead_b(), gz_binary_io::gz_write_mul_integer_b(), mpi_binary_data_io::mpi_write_int_vector_b(), mpi_binary_head_io::mpi_write_mul_inthead_b(), mpi_binary_data_io::mpi_write_one_integer_b(), and binary_io::write_mul_integer_b().
dealloc_2d_i8array()
subroutine transfer_to_long_integers::dealloc_2d_i8array (type(tmp_i8_2darray), intent(inout) tmp)
Definition at line 156 of file transfer_to_long_integers.f90.
Referenced by dup_to_short_darray().
dup_from_short_array()
subroutine transfer_to_long_integers::dup_from_short_array (integer(kind = kint_gl), intent(in) n1, integer(kind = kint), dimension(n1), intent(in) i4_out, type(tmp_i8_array), intent(inout) tmp)
Definition at line 105 of file transfer_to_long_integers.f90.
References alloc_1d_i8array().
Referenced by gz_mpi_binary_data_io::gz_mpi_write_int_vector_b(), gz_mpi_binary_head_io::gz_mpi_write_mul_inthead_b(), gz_binary_io::gz_write_mul_integer_b(), mpi_binary_data_io::mpi_write_int_vector_b(), mpi_binary_head_io::mpi_write_mul_inthead_b(), mpi_binary_data_io::mpi_write_one_integer_b(), and binary_io::write_mul_integer_b().
dup_from_short_darray()
subroutine transfer_to_long_integers::dup_from_short_darray (integer(kind = kint_gl), intent(in) n1, integer(kind = kint_gl), intent(in) n2, integer(kind = kint), dimension(n1,n2), intent(in) i4_out, type(tmp_i8_2darray), intent(inout) tmp)
Definition at line 167 of file transfer_to_long_integers.f90.
References alloc_2d_i8array().
dup_to_short_array()
subroutine transfer_to_long_integers::dup_to_short_array (type(tmp_i8_array), intent(inout) tmp, integer(kind = kint), dimension(tmp%n1), intent(inout) i4_out)
Definition at line 123 of file transfer_to_long_integers.f90.
References dealloc_1d_i8array().
Referenced by gz_mpi_binary_data_io::gz_mpi_read_int_vector_b(), gz_mpi_binary_head_io::gz_mpi_read_mul_inthead_b(), gz_binary_io::gz_read_mul_integer_b(), mpi_binary_data_io::mpi_read_int_vector_b(), mpi_binary_head_io::mpi_read_mul_inthead_b(), mpi_binary_data_io::mpi_read_one_integer_b(), and binary_io::read_mul_integer_b().
dup_to_short_darray()
subroutine transfer_to_long_integers::dup_to_short_darray (type(tmp_i8_2darray), intent(inout) tmp, integer(kind = kint), dimension(tmp%n1,tmp%n2), intent(inout) i4_out)
Definition at line 186 of file transfer_to_long_integers.f90.
References dealloc_2d_i8array().
Referenced by set_patches_for_psf::set_iso_patches(), and set_patches_for_psf::set_psf_patches().