CALYPSO: t_2d_sph_trans_table Module Reference
t_2d_sph_trans_table Module Reference
Indices of spherical transform for second harmonics.
Data Types
type sph_trans_2d_table
Functions/Subroutines
subroutine alloc_2d_sph_trans_table (sph_rtp, sph_rj, s2d_tbl)
subroutine dealloc_2d_sph_trans_table (s2d_tbl)
subroutine check_2d_sph_indices (id_rank, nphi, ltr, jmax, s2d_tbl)
subroutine check_2d_sph_trans_table (id_rank, ntheta, nphi, s2d_tbl)
Detailed Description
Indices of spherical transform for second harmonics.
      subroutine alloc_2d_sph_trans_table(sph_rtp, sph_rj, s2d_tbl)
      subroutine dealloc_2d_sph_trans_table(s2d_tbl)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_rj_grid), intent(in) :: sph_rj
        type(sph_trans_2d_table), intent(inout) :: s2d_tbl
      subroutine check_2d_sph_indices                                 &
     &         (id_rank, nphi, ltr, jmax, s2d_tbl)
      subroutine check_2d_sph_trans_table                             &
     &         (id_rank, ntheta, nphi, s2d_tbl)
Parameters
id_rank Process ID
ntheta Number of meridional grids
nphi Number of zonal grids
ltr Truncation degree
jmax Number of spherical harmonics modes
Function/Subroutine Documentation
alloc_2d_sph_trans_table()
subroutine t_2d_sph_trans_table::alloc_2d_sph_trans_table (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_rj_grid), intent(in) sph_rj, type(sph_trans_2d_table), intent(inout) s2d_tbl)
Definition at line 54 of file t_2d_sph_trans_table.f90.
Referenced by const_global_sph_grids_modes::const_global_sph_fem_grid(), and const_global_sph_grids_modes::s_const_global_sph_grids_modes().
check_2d_sph_indices()
subroutine t_2d_sph_trans_table::check_2d_sph_indices (integer, intent(in) id_rank, integer(kind = kint), intent(in) nphi, integer(kind = kint), intent(in) ltr, integer(kind = kint), intent(in) jmax, type(sph_trans_2d_table), intent(in) s2d_tbl)
Definition at line 109 of file t_2d_sph_trans_table.f90.
check_2d_sph_trans_table()
subroutine t_2d_sph_trans_table::check_2d_sph_trans_table (integer, intent(in) id_rank, integer(kind = kint), intent(in) ntheta, integer(kind = kint), intent(in) nphi, type(sph_trans_2d_table), intent(in) s2d_tbl)
Definition at line 156 of file t_2d_sph_trans_table.f90.
dealloc_2d_sph_trans_table()
subroutine t_2d_sph_trans_table::dealloc_2d_sph_trans_table (type(sph_trans_2d_table), intent(inout) s2d_tbl)
Definition at line 92 of file t_2d_sph_trans_table.f90.
Referenced by const_global_sph_grids_modes::const_global_sph_fem_grid(), and const_global_sph_grids_modes::s_const_global_sph_grids_modes().