CALYPSO: set_ucd_extensions Module Reference
set_ucd_extensions Module Reference
Set file extension.
Functions/Subroutines
character(len=kchara) function add_ucd_extension (file_head)
character(len=kchara) function add_udt_extension (file_head)
character(len=kchara) function add_grd_extension (file_head)
character(len=kchara) function add_sdt_extension (file_head)
character(len=kchara) function add_sfm_extension (file_head)
character(len=kchara) function add_sgd_extension (file_head)
character(len=kchara) function add_pvtk_extension (file_head)
character(len=kchara) function add_vtk_extension (file_head)
character(len=kchara) function add_vtd_extension (file_head)
character(len=kchara) function add_vtg_extension (file_head)
character(len=kchara) function add_xdmf_extension (file_head)
character(len=kchara) function add_hdf_extension (file_head)
character(len=kchara) function add_mesh_suffix (file_head)
character(len=kchara) function add_field_suffix (file_head)
character(len=kchara) function add_solution_suffix (file_head)
character(len=kchara) function add_node_extension (file_head)
character(len=kchara) function add_connect_extension (file_head)
character(len=kchara) function add_dx_extension (file_head)
Variables
character(len=3), parameter inp_ext = "inp"
character(len=3), parameter udt_ext = "udt"
character(len=3), parameter grd_ext = "grd"
character(len=3), parameter sfm_ext = "sfm"
character(len=3), parameter sdt_ext = "sdt"
character(len=3), parameter sgd_ext = "sgd"
character(len=3), parameter vtk_ext = "vtk"
character(len=3), parameter vtd_ext = "vtd"
character(len=3), parameter vtg_ext = "vtg"
Detailed Description
Set file extension.
      character(len = kchara) function add_ucd_extension(file_head)
                put ".inp" at the end
      character(len = kchara) function add_udt_extension(file_head)
                put ".udt" at the end
      character(len = kchara) function add_grd_extension(file_head)
                put ".grd" at the end
      character(len = kchara) function add_sdt_extension(file_head)
                put ".sdt" at the end
      character(len = kchara) function add_sfm_extension(file_head)
                put ".sfm" at the end
      character(len = kchara) function add_sgd_extension(file_head)
                put ".sgd" at the end
      character(len = kchara) function add_pvtk_extension(file_head)
                put ".pvtk" at the end
      character(len = kchara) function add_vtk_extension(file_head)
                put ".vtk" at the end
      character(len = kchara) function add_vtd_extension(file_head)
                put ".vtd" at the end
      character(len = kchara) function add_vtg_extension(file_head)
                put ".vtg" at the end
      character(len = kchara) function add_xdmf_extension(file_head)
                put ".xdmf" at the end
      character(len = kchara) function add_hdf_extension(file_head)
                put ".h5" at the end
      character(len = kchara) function add_mesh_suffix(file_head)
                put ".mesh" at the end
      character(len = kchara) function add_field_suffix(file_head)
                put ".field" at the end
      character(len = kchara) function add_solution_suffix(file_head)
                put ".solution" at the end
      character(len = kchara) function add_node_extension(file_head)
                put ".node.dat" at the end
      character(len = kchara) function add_connect_extension(file_head)
                put ".connect.dat" at the end
      character(len = kchara) function add_dx_extension(file_head)
                put ".dx" at the end
Parameters
file_head file prefix
Function/Subroutine Documentation
add_connect_extension()
character(len = kchara) function set_ucd_extensions::add_connect_extension (character(len=kchara), intent(in) file_head)
Definition at line 249 of file set_ucd_extensions.f90.
add_dx_extension()
character(len = kchara) function set_ucd_extensions::add_dx_extension (character(len=kchara), intent(in) file_head)
Definition at line 261 of file set_ucd_extensions.f90.
add_field_suffix()
character(len = kchara) function set_ucd_extensions::add_field_suffix (character(len=kchara), intent(in) file_head)
Definition at line 216 of file set_ucd_extensions.f90.
Referenced by set_ucd_file_names::set_merged_hdf_field_file_name().
add_grd_extension()
character(len = kchara) function set_ucd_extensions::add_grd_extension (character(len=kchara), intent(in) file_head)
Definition at line 99 of file set_ucd_extensions.f90.
References set_parallel_file_name::add_3chara_extension(), and grd_ext.
Referenced by set_ucd_file_names::set_parallel_grd_file_name(), and set_ucd_file_names::set_single_grd_file_name().
add_hdf_extension()
character(len = kchara) function set_ucd_extensions::add_hdf_extension (character(len=kchara), intent(in) file_head)
Definition at line 194 of file set_ucd_extensions.f90.
Referenced by set_ucd_file_names::set_merged_hdf_field_file_name(), and set_ucd_file_names::set_merged_hdf_mesh_file_name().
add_mesh_suffix()
character(len = kchara) function set_ucd_extensions::add_mesh_suffix (character(len=kchara), intent(in) file_head)
Definition at line 205 of file set_ucd_extensions.f90.
Referenced by set_ucd_file_names::set_merged_hdf_mesh_file_name().
add_node_extension()
character(len = kchara) function set_ucd_extensions::add_node_extension (character(len=kchara), intent(in) file_head)
Definition at line 238 of file set_ucd_extensions.f90.
add_pvtk_extension()
character(len = kchara) function set_ucd_extensions::add_pvtk_extension (character(len=kchara), intent(in) file_head)
Definition at line 141 of file set_ucd_extensions.f90.
Referenced by gz_vtk_file_io::write_gz_parallel_vtk_file(), and vtk_file_io::write_parallel_vtk_file().
add_sdt_extension()
character(len = kchara) function set_ucd_extensions::add_sdt_extension (character(len=kchara), intent(in) file_head)
Definition at line 110 of file set_ucd_extensions.f90.
References set_parallel_file_name::add_3chara_extension(), and sdt_ext.
Referenced by set_ucd_file_names::set_parallel_ucd_file_name(), and set_ucd_file_names::set_single_ucd_file_name().
add_sfm_extension()
character(len = kchara) function set_ucd_extensions::add_sfm_extension (character(len=kchara), intent(in) file_head)
Definition at line 120 of file set_ucd_extensions.f90.
References set_parallel_file_name::add_3chara_extension(), and sfm_ext.
Referenced by set_ucd_file_names::set_parallel_ucd_file_name(), and set_ucd_file_names::set_single_ucd_file_name().
add_sgd_extension()
character(len = kchara) function set_ucd_extensions::add_sgd_extension (character(len=kchara), intent(in) file_head)
Definition at line 130 of file set_ucd_extensions.f90.
References set_parallel_file_name::add_3chara_extension(), and sgd_ext.
Referenced by set_ucd_file_names::set_parallel_grd_file_name(), and set_ucd_file_names::set_single_grd_file_name().
add_solution_suffix()
character(len = kchara) function set_ucd_extensions::add_solution_suffix (character(len=kchara), intent(in) file_head)
Definition at line 227 of file set_ucd_extensions.f90.
Referenced by set_ucd_file_names::set_merged_xdmf_file_name().
add_ucd_extension()
character(len = kchara) function set_ucd_extensions::add_ucd_extension (character(len=kchara), intent(in) file_head)
Definition at line 79 of file set_ucd_extensions.f90.
References set_parallel_file_name::add_3chara_extension(), and inp_ext.
Referenced by set_ucd_file_names::set_parallel_ucd_file_name(), and set_ucd_file_names::set_single_ucd_file_name().
add_udt_extension()
character(len = kchara) function set_ucd_extensions::add_udt_extension (character(len=kchara), intent(in) file_head)
Definition at line 89 of file set_ucd_extensions.f90.
References set_parallel_file_name::add_3chara_extension(), and udt_ext.
Referenced by set_ucd_file_names::set_parallel_ucd_file_name(), and set_ucd_file_names::set_single_ucd_file_name().
add_vtd_extension()
character(len = kchara) function set_ucd_extensions::add_vtd_extension (character(len=kchara), intent(in) file_head)
Definition at line 162 of file set_ucd_extensions.f90.
References set_parallel_file_name::add_3chara_extension(), and vtd_ext.
Referenced by set_ucd_file_names::set_parallel_ucd_file_name(), and set_ucd_file_names::set_single_ucd_file_name().
add_vtg_extension()
character(len = kchara) function set_ucd_extensions::add_vtg_extension (character(len=kchara), intent(in) file_head)
Definition at line 172 of file set_ucd_extensions.f90.
References set_parallel_file_name::add_3chara_extension(), and vtg_ext.
Referenced by set_ucd_file_names::set_parallel_grd_file_name(), and set_ucd_file_names::set_single_grd_file_name().
add_vtk_extension()
character(len = kchara) function set_ucd_extensions::add_vtk_extension (character(len=kchara), intent(in) file_head)
Definition at line 152 of file set_ucd_extensions.f90.
References set_parallel_file_name::add_3chara_extension(), and vtk_ext.
Referenced by set_ucd_file_names::set_parallel_ucd_file_name(), set_ucd_file_names::set_parallel_vtk_file_name(), and set_ucd_file_names::set_single_ucd_file_name().
add_xdmf_extension()
character(len = kchara) function set_ucd_extensions::add_xdmf_extension (character(len=kchara), intent(in) file_head)
Definition at line 183 of file set_ucd_extensions.f90.
Referenced by set_ucd_file_names::set_merged_snap_xdmf_file_name(), and set_ucd_file_names::set_merged_xdmf_file_name().
Variable Documentation
grd_ext
character(len=3), parameter set_ucd_extensions::grd_ext = "grd"
Definition at line 63 of file set_ucd_extensions.f90.
Referenced by add_grd_extension().
inp_ext
character(len=3), parameter set_ucd_extensions::inp_ext = "inp"
Definition at line 61 of file set_ucd_extensions.f90.
Referenced by add_ucd_extension(), and m_section_file_extensions::set_psf_extensions().
sdt_ext
character(len=3), parameter set_ucd_extensions::sdt_ext = "sdt"
Definition at line 66 of file set_ucd_extensions.f90.
Referenced by add_sdt_extension(), and m_section_file_extensions::set_psf_extensions().
sfm_ext
character(len=3), parameter set_ucd_extensions::sfm_ext = "sfm"
Definition at line 65 of file set_ucd_extensions.f90.
Referenced by add_sfm_extension(), and m_section_file_extensions::set_psf_extensions().
sgd_ext
character(len=3), parameter set_ucd_extensions::sgd_ext = "sgd"
Definition at line 67 of file set_ucd_extensions.f90.
Referenced by add_sgd_extension().
udt_ext
character(len=3), parameter set_ucd_extensions::udt_ext = "udt"
Definition at line 62 of file set_ucd_extensions.f90.
Referenced by add_udt_extension(), and m_section_file_extensions::set_psf_extensions().
vtd_ext
character(len=3), parameter set_ucd_extensions::vtd_ext = "vtd"
Definition at line 70 of file set_ucd_extensions.f90.
Referenced by add_vtd_extension(), and m_section_file_extensions::set_psf_extensions().
vtg_ext
character(len=3), parameter set_ucd_extensions::vtg_ext = "vtg"
Definition at line 71 of file set_ucd_extensions.f90.
Referenced by add_vtg_extension().
vtk_ext
character(len=3), parameter set_ucd_extensions::vtk_ext = "vtk"
Definition at line 69 of file set_ucd_extensions.f90.
Referenced by add_vtk_extension(), and m_section_file_extensions::set_psf_extensions().