CALYPSO: set_mhd_field_address Module Reference
set_mhd_field_address Module Reference
Functions/Subroutines
logical function check_vector_fields (phys_name_ctl)
logical function check_scalar_fields (phys_name_ctl)
logical function check_sym_tensor_fields (phys_name_ctl)
logical function check_asym_tensor_fields (phys_name_ctl)
subroutine set_mhd_field_addresses (i_fld, field_name, iphys, flag)
subroutine set_old_mhd_field_addresses (i_fld, field_name, iphys, flag)
Function/Subroutine Documentation
check_asym_tensor_fields()
logical function set_mhd_field_address::check_asym_tensor_fields (character(len = kchara), intent(in) phys_name_ctl)
Definition at line 121 of file set_MHD_field_address.f90.
References m_base_force_labels::check_asym_flux_tensors().
Referenced by set_nodal_field_name::set_tensor_field_name().
check_scalar_fields()
logical function set_mhd_field_address::check_scalar_fields (character(len = kchara), intent(in) phys_name_ctl)
Definition at line 77 of file set_MHD_field_address.f90.
References m_base_field_labels::check_base_scalar(), m_div_force_labels::check_div_force(), m_div_force_labels::check_div_scalar_flux(), m_grad_field_labels::check_divergence_field(), m_energy_flux_labels::check_enegy_fluxes(), m_field_product_labels::check_field_product_scalars(), m_base_force_labels::check_scalar_advection(), m_explicit_term_labels::check_scalar_check_field(), m_diffusion_term_labels::check_scalar_diffusion(), m_explicit_term_labels::check_scalar_work_field(), and m_explicit_term_labels::check_work_4_poisson().
Referenced by set_nodal_field_name::set_scalar_field_name().
check_sym_tensor_fields()
logical function set_mhd_field_address::check_sym_tensor_fields (character(len = kchara), intent(in) phys_name_ctl)
Definition at line 109 of file set_MHD_field_address.f90.
References m_base_force_labels::check_flux_tensors().
Referenced by set_nodal_field_name::set_tensor_field_name().
check_vector_fields()
logical function set_mhd_field_address::check_vector_fields (character(len = kchara), intent(in) phys_name_ctl)
Definition at line 45 of file set_MHD_field_address.f90.
References m_base_field_labels::check_base_vector(), m_diff_vector_labels::check_difference_vectors(), m_div_force_labels::check_div_flux_tensor(), m_field_product_labels::check_field_product_vectors(), m_base_force_labels::check_force_vectors(), m_grad_field_labels::check_gradient_field(), m_rot_force_labels::check_rot_force(), m_explicit_term_labels::check_vector_check_field(), m_diffusion_term_labels::check_vector_diffusion(), and m_explicit_term_labels::check_vector_work_field().
Referenced by set_nodal_field_name::set_vector_field_name().
set_mhd_field_addresses()
subroutine set_mhd_field_address::set_mhd_field_addresses (integer(kind = kint), intent(in) i_fld, character(len = kchara), intent(in) field_name, type(phys_address), intent(inout) iphys, logical, intent(inout) flag)
Definition at line 134 of file set_MHD_field_address.f90.
References t_diffusion_term_labels::set_base_diffusion_addresses(), t_base_force_labels::set_base_force_addresses(), t_base_field_labels::set_base_scalar_addresses(), t_base_field_labels::set_base_vector_addresses(), t_explicit_term_labels::set_check_field_addresses(), t_diff_vector_labels::set_diff_vector_addresses(), t_base_force_labels::set_div_force_addresses(), t_field_product_labels::set_field_product_addresses(), t_base_force_labels::set_rot_force_addresses(), and t_explicit_term_labels::set_work_field_addresses().
Referenced by set_control_field_data::init_field_data().
set_old_mhd_field_addresses()
subroutine set_mhd_field_address::set_old_mhd_field_addresses (integer(kind = kint), intent(in) i_fld, character(len = kchara), intent(in) field_name, type(phys_address), intent(inout) iphys, logical, intent(inout) flag)
Definition at line 196 of file set_MHD_field_address.f90.
References m_energy_flux_labels::buoyancy_work, and m_field_product_labels::geostrophic_balance.
Referenced by set_control_field_data::init_field_data().