CALYPSO: delete_field_smp Module Reference
delete_field_smp Module Reference
Functions/Subroutines
subroutine delete_phys_data_smp (numnod, ist, ied, ntot_comp, numdir, i_field, field)
subroutine, private delete_scalar_smp (numnod, ist, ied, scalar)
subroutine, private delete_vector_smp (numnod, ist, ied, vector)
subroutine, private delete_sym_tensor_smp (numnod, ist, ied, tensor)
subroutine, private delete_arb_vect_smp (numnod, ist, ied, numdir, vector)
Function/Subroutine Documentation
delete_arb_vect_smp()
subroutine, private delete_field_smp::delete_arb_vect_smp (integer (kind=kint), intent(in) numnod, integer (kind=kint), intent(in) ist, integer (kind=kint), intent(in) ied, integer (kind=kint), intent(in) numdir, real (kind=kreal), dimension(numnod,numdir), intent(inout) vector) private
Definition at line 126 of file delete_field_smp.f90.
References m_constants::zero.
Referenced by delete_phys_data_smp().
delete_phys_data_smp()
subroutine delete_field_smp::delete_phys_data_smp (integer (kind=kint), intent(in) numnod, integer (kind=kint), intent(in) ist, integer (kind=kint), intent(in) ied, integer (kind=kint), intent(in) ntot_comp, integer (kind=kint), intent(in) numdir, integer (kind=kint), intent(in) i_field, real (kind=kreal), dimension(numnod,ntot_comp), intent(inout) field)
Definition at line 52 of file delete_field_smp.f90.
References delete_arb_vect_smp(), delete_scalar_smp(), delete_sym_tensor_smp(), delete_vector_smp(), m_constants::ione, m_constants::isix, and m_constants::ithree.
Referenced by copy_nodal_fields::clear_field_data().
delete_scalar_smp()
subroutine, private delete_field_smp::delete_scalar_smp (integer (kind=kint), intent(in) numnod, integer (kind=kint), intent(in) ist, integer (kind=kint), intent(in) ied, real (kind=kreal), dimension(numnod), intent(inout) scalar) private
Definition at line 77 of file delete_field_smp.f90.
References m_constants::zero.
Referenced by delete_phys_data_smp().
delete_sym_tensor_smp()
subroutine, private delete_field_smp::delete_sym_tensor_smp (integer (kind=kint), intent(in) numnod, integer (kind=kint), intent(in) ist, integer (kind=kint), intent(in) ied, real (kind=kreal), dimension(numnod,6), intent(inout) tensor) private
Definition at line 106 of file delete_field_smp.f90.
References m_constants::zero.
Referenced by delete_phys_data_smp().
delete_vector_smp()
subroutine, private delete_field_smp::delete_vector_smp (integer (kind=kint), intent(in) numnod, integer (kind=kint), intent(in) ist, integer (kind=kint), intent(in) ied, real (kind=kreal), dimension(numnod,3), intent(inout) vector) private
Definition at line 90 of file delete_field_smp.f90.
References m_constants::zero.
Referenced by delete_phys_data_smp().