CALYPSO: set_sph_exp_rigid_icb Module Reference
set_sph_exp_rigid_icb Module Reference
Evaluate velocity with non-slip boundary at ICB.
Functions/Subroutines
subroutine cal_sph_nod_icb_rigid_velo2 (jmax, kr_in, is_fld, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_nod_icb_rotate_velo2 (idx_rj_degree_zero, idx_rj_degree_one, nidx_rj, kr_in, r_ICB, radius_rj, is_fld, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_nod_icb_rigid_rot2 (jmax, g_sph_rj, kr_in, r_ICB, fdm2_fix_fld_ICB, fdm2_fix_dr_ICB, is_fld, is_rot, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_nod_icb_rigid_diffuse2 (jmax, g_sph_rj, kr_in, r_ICB, fdm2_fix_fld_ICB, fdm2_fix_dr_ICB, coef_d, is_fld, is_diffuse, n_point, ntot_phys_rj, d_rj)
Detailed Description
Evaluate velocity with non-slip boundary at ICB.
      subroutine cal_sph_nod_icb_rigid_velo2(jmax, kr_in,             &
     &          is_fld, n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_nod_icb_rotate_velo2(idx_rj_degree_zero,     &
     &          idx_rj_degree_one, nidx_rj, kr_in, r_ICB, radius_rj,  &
     &          is_fld, n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_nod_icb_rigid_rot2(jmax, g_sph_rj,           &
     &          kr_in, r_ICB, fdm2_fix_fld_ICB, fdm2_fix_dr_ICB,      &
     &          is_fld, is_rot, n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_nod_icb_rigid_diffuse2(jmax, g_sph_rj, kr_in,&
     &          r_ICB, fdm2_fix_fld_ICB, fdm2_fix_dr_ICB, coef_d,     &
     &          is_fld, is_diffuse, n_point, ntot_phys_rj, d_rj)
Parameters
n_point Number of points for spectrum data
idx_rj_degree_zero Local address for degree 0
idx_rj_degree_one(-1:1) Local address for degree 1
jmax Number of modes for spherical harmonics \(L*(L+2)\)
kr_in Radial ID for inner boundary
r_ICB(0:2) Radius at ICB
Parameters
fdm2_fix_fld_ICB(0:2,3) Matrix to evaluate radial derivative at ICB with fixed field
fdm2_fix_dr_ICB(-1:1,3) Matrix to evaluate field at ICB with fixed radial derivative
Parameters
coef_d Coefficient for diffusion term
is_fld Address of poloidal velocity in d_rj
is_rot Address of poloidal vorticity in d_rj
is_diffuse Address of poloidal viscousity in d_rj
Parameters
ntot_phys_rj Total number of components
d_rj Spectrum data
Function/Subroutine Documentation
cal_sph_nod_icb_rigid_diffuse2()
subroutine set_sph_exp_rigid_icb::cal_sph_nod_icb_rigid_diffuse2 (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(0:2), intent(in) r_ICB, real(kind = kreal), dimension(0:2,3), intent(in) fdm2_fix_fld_ICB, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_fix_dr_ICB, real(kind = kreal), intent(in) coef_d, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_diffuse, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 179 of file set_sph_exp_rigid_ICB.f90.
Referenced by select_exp_velocity_icb::sel_icb_sph_viscous_diffusion().
cal_sph_nod_icb_rigid_rot2()
subroutine set_sph_exp_rigid_icb::cal_sph_nod_icb_rigid_rot2 (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(0:2), intent(in) r_ICB, real(kind = kreal), dimension(0:2,3), intent(in) fdm2_fix_fld_ICB, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_fix_dr_ICB, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_rot, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 137 of file set_sph_exp_rigid_ICB.f90.
Referenced by select_exp_velocity_icb::sel_icb_grad_vp_and_vorticity(), and select_exp_velocity_icb::sel_icb_sph_vorticity().
cal_sph_nod_icb_rigid_velo2()
subroutine set_sph_exp_rigid_icb::cal_sph_nod_icb_rigid_velo2 (integer(kind = kint), intent(in) jmax, integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 56 of file set_sph_exp_rigid_ICB.f90.
References m_constants::zero.
Referenced by select_exp_velocity_icb::sel_icb_grad_poloidal_moment(), and select_exp_velocity_icb::sel_icb_grad_vp_and_vorticity().
cal_sph_nod_icb_rotate_velo2()
subroutine set_sph_exp_rigid_icb::cal_sph_nod_icb_rotate_velo2 (integer(kind = kint), intent(in) idx_rj_degree_zero, integer(kind = kint), dimension(-1:1), intent(in) idx_rj_degree_one, integer(kind = kint), dimension(2), intent(in) nidx_rj, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(0:2), intent(in) r_ICB, real(kind = kreal), dimension(nidx_rj(1)), intent(in) radius_rj, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 83 of file set_sph_exp_rigid_ICB.f90.
References m_constants::zero.
Referenced by select_exp_velocity_icb::sel_icb_grad_poloidal_moment(), and select_exp_velocity_icb::sel_icb_grad_vp_and_vorticity().