CALYPSO: set_sp_rlm_sym_mat_tsmp Module Reference
set_sp_rlm_sym_mat_tsmp Module Reference
forward Legendre transform (Blocked loop version)
Functions/Subroutines
subroutine set_sp_rlm_sym_mat_rin (nnod_rlm, nidx_rlm, istep_rlm, idx_gl_1d_rlm_j, a_r_1d_rlm_r, g_sph_rlm, jst, n_jk_e, n_jk_o, ncomp_recv, nvector, nscalar, irev_sr_rlm, n_WR, WR, pol_e, tor_e, pol_o, tor_o)
subroutine set_sp_rlm_sym_mat_rout (nnod_rlm, nidx_rlm, istep_rlm, idx_gl_1d_rlm_j, a_r_1d_rlm_r, g_sph_rlm, jst, n_jk_e, n_jk_o, ncomp_recv, nvector, nscalar, irev_sr_rlm, n_WR, WR, pol_e, tor_e, pol_o, tor_o)
Variables
integer, external omp_get_max_threads
Detailed Description
forward Legendre transform (Blocked loop version)
      subroutine set_sp_rlm_sym_mat_rin(nnod_rlm, nidx_rlm,           &
     &          istep_rlm, idx_gl_1d_rlm_j, a_r_1d_rlm_r, g_sph_rlm,  &
     &          jst, n_jk_e, n_jk_o, ncomp_recv, nvector, nscalar,    &
     &          irev_sr_rlm, n_WR, WR,  pol_e, tor_e, pol_o, tor_o)
      subroutine set_sp_rlm_sym_mat_rout(nnod_rlm, nidx_rlm,          &
     &          istep_rlm, idx_gl_1d_rlm_j, a_r_1d_rlm_r, g_sph_rlm,  &
     &          jst, n_jk_e, n_jk_o, ncomp_recv, nvector, nscalar,    &
     &          irev_sr_rlm, n_WR, WR,  pol_e, tor_e, pol_o, tor_o)
Function/Subroutine Documentation
set_sp_rlm_sym_mat_rin()
subroutine set_sp_rlm_sym_mat_tsmp::set_sp_rlm_sym_mat_rin (integer(kind = kint), intent(in) nnod_rlm, integer(kind = kint), dimension(2), intent(in) nidx_rlm, integer(kind = kint), dimension(2), intent(in) istep_rlm, integer(kind = kint), dimension(nidx_rlm(2),3), intent(in) idx_gl_1d_rlm_j, real(kind = kreal), dimension(nidx_rlm(1)), intent(in) a_r_1d_rlm_r, real(kind = kreal), dimension(nidx_rlm(2),17), intent(in) g_sph_rlm, integer(kind = kint), intent(in) jst, integer(kind = kint), intent(in) n_jk_e, integer(kind = kint), intent(in) n_jk_o, integer(kind = kint), intent(in) ncomp_recv, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, integer(kind = kint), dimension(nnod_rlm), intent(in) irev_sr_rlm, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(in) WR, real(kind = kreal), dimension(3*nvector+nscalar,nidx_rlm(1),n_jk_e), intent(inout) pol_e, real(kind = kreal), dimension(2*nvector,nidx_rlm(1),n_jk_e), intent(inout) tor_e, real(kind = kreal), dimension(3*nvector+nscalar,nidx_rlm(1),n_jk_o), intent(inout) pol_o, real(kind = kreal), dimension(2*nvector,nidx_rlm(1),n_jk_o), intent(inout) tor_o)
Definition at line 39 of file set_sp_rlm_sym_mat_tsmp.f90.
Referenced by leg_bwd_trans_on_the_fly::legendre_b_trans_on_the_fly(), leg_bwd_trans_sym_mat_jt::legendre_b_trans_sym_mat_jt(), and legendre_bwd_trans_testloop::legendre_b_trans_vector_test().
set_sp_rlm_sym_mat_rout()
subroutine set_sp_rlm_sym_mat_tsmp::set_sp_rlm_sym_mat_rout (integer(kind = kint), intent(in) nnod_rlm, integer(kind = kint), dimension(2), intent(in) nidx_rlm, integer(kind = kint), dimension(2), intent(in) istep_rlm, integer(kind = kint), dimension(nidx_rlm(2),3), intent(in) idx_gl_1d_rlm_j, real(kind = kreal), dimension(nidx_rlm(1)), intent(in) a_r_1d_rlm_r, real(kind = kreal), dimension(nidx_rlm(2),17), intent(in) g_sph_rlm, integer(kind = kint), intent(in) jst, integer(kind = kint), intent(in) n_jk_e, integer(kind = kint), intent(in) n_jk_o, integer(kind = kint), intent(in) ncomp_recv, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, integer(kind = kint), dimension(nnod_rlm), intent(in) irev_sr_rlm, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(in) WR, real(kind = kreal), dimension(n_jk_e,nidx_rlm(1),3*nvector+nscalar), intent(inout) pol_e, real(kind = kreal), dimension(n_jk_e,nidx_rlm(1),2*nvector), intent(inout) tor_e, real(kind = kreal), dimension(n_jk_o,nidx_rlm(1),3*nvector+nscalar), intent(inout) pol_o, real(kind = kreal), dimension(n_jk_o,nidx_rlm(1),2*nvector), intent(inout) tor_o)
Definition at line 156 of file set_sp_rlm_sym_mat_tsmp.f90.
Referenced by leg_bwd_trans_sym_mat_tj::legendre_b_trans_sym_mat_tj().
Variable Documentation
omp_get_max_threads
integer, external set_sp_rlm_sym_mat_tsmp::omp_get_max_threads
Definition at line 31 of file set_sp_rlm_sym_mat_tsmp.f90.