CALYPSO: cal_energy_flux_rtp Module Reference
cal_energy_flux_rtp Module Reference
Evaluate energy fluxes for MHD dynamo in physical space.
Functions/Subroutines
subroutine s_cal_energy_flux_rtp (sph_rtp, fl_prop, cd_prop, ref_param_T, ref_param_C, leg, f_trns, bs_trns, be_trns, bs_difv, fe_trns, trns_f_MHD, trns_b_snap, trns_b_eflux, trns_b_difv, trns_f_eflux)
subroutine cal_energy_fluxes_on_node (bs_trns_base, f_trns_frc, be_trns_frc, fs_trns_eflux, nnod, ntot_comp_fld, fld_rtp, ntot_comp_frc, frc_rtp, ntot_comp_uxb, fub_rtp, ntot_comp_flx, flx_rtp)
subroutine cal_magnetic_fluxes_rtp (sph_rtp, cd_prop, f_trns_frc, bs_trns_base, bs_trns_diff_v, fe_trns_frc, fe_trns_prod, trns_f_MHD, trns_b_snap, trns_b_difv, trns_f_eflux)
subroutine cal_magnetic_fluxes_pole (sph_rtp, cd_prop, f_trns_frc, bs_trns_base, bs_trns_diff_v, fe_trns_frc, fe_trns_prod, trns_f_MHD, trns_b_snap, trns_b_difv, trns_f_eflux)
subroutine cal_helicity_on_node (bs_trns_base, fe_trns_prod, nnod, ntot_comp_fld, fld_rtp, ntot_comp_hls, fhls_rtp)
subroutine, private cal_square_vector_on_node (bs_trns_base, fe_trns_prod, nnod, ntot_comp_fld, fld_rtp, ntot_comp_fmg, fmag_rtp)
subroutine, private cal_lengh_scale_rtp (sph_rtp, bs_trns_base, bs_trns_dif, fe_trns_prod, trns_b_snap, trns_b_eflux, trns_f_eflux)
Detailed Description
Evaluate energy fluxes for MHD dynamo in physical space.
      subroutine s_cal_energy_flux_rtp(sph_rtp,                       &
     &          fl_prop, cd_prop, ref_param_T, ref_param_C, leg,      &
     &          f_trns, bs_trns, be_trns, bs_difv, fe_trns,           &
     &          trns_f_MHD, trns_b_snap, trns_b_eflux, trns_b_difv,   &
     &          trns_f_eflux)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(MHD_evolution_param), intent(in) :: MHD_prop
        type(fluid_property), intent(in) :: fl_prop
        type(conductive_property), intent(in) :: cd_prop
        type(reference_scalar_param), intent(in) :: ref_param_T
        type(reference_scalar_param), intent(in) :: ref_param_C
        type(scalar_property), intent(in) :: ht_prop, cp_prop
        type(legendre_4_sph_trans), intent(in) :: leg
        type(phys_address), intent(in) :: f_trns
        type(phys_address), intent(in) :: bs_trns, bs_difv
        type(phys_address), intent(in) :: be_trns, fe_trns
        type(spherical_transform_data), intent(in) :: trns_f_MHD
        type(spherical_transform_data), intent(in) :: trns_b_snap
        type(spherical_transform_data), intent(in) :: trns_b_eflux
        type(spherical_transform_data), intent(inout) :: trns_f_eflux
      subroutine cal_energy_fluxes_on_node                            &
     &         (bs_trns_base, f_trns_frc, be_trns_frc, fs_trns_eflux, &
     &          nnod, ntot_comp_fld, fld_rtp, ntot_comp_frc, frc_rtp, &
     &          ntot_comp_uxb, fub_rtp, ntot_comp_flx, flx_rtp)
        type(base_field_address), intent(in) :: bs_trns_base
        type(base_force_address), intent(in) :: f_trns_frc
        type(base_force_address), intent(in) :: be_trns_frc
        type(energy_flux_address), intent(in) :: fs_trns_eflux
Function/Subroutine Documentation
cal_energy_fluxes_on_node()
subroutine cal_energy_flux_rtp::cal_energy_fluxes_on_node (type(base_field_address), intent(in) bs_trns_base, type(base_force_address), intent(in) f_trns_frc, type(base_force_address), intent(in) be_trns_frc, type(energy_flux_address), intent(in) fs_trns_eflux, integer(kind = kint), intent(in) nnod, integer(kind = kint), intent(in) ntot_comp_fld, real(kind = kreal), dimension(nnod,ntot_comp_fld), intent(in) fld_rtp, integer(kind = kint), intent(in) ntot_comp_frc, real(kind = kreal), dimension(nnod,ntot_comp_frc), intent(in) frc_rtp, integer(kind = kint), intent(in) ntot_comp_uxb, real(kind = kreal), dimension(nnod,ntot_comp_uxb), intent(in) fub_rtp, integer(kind = kint), intent(in) ntot_comp_flx, real(kind = kreal), dimension(nnod,ntot_comp_flx), intent(inout) flx_rtp)
Definition at line 160 of file cal_energy_flux_rtp.f90.
References cal_products_smp::cal_dot_prod_no_coef_smp(), cal_products_smp::cal_dot_prod_w_coef_smp(), and m_constants::dminus.
Referenced by s_cal_energy_flux_rtp().
cal_helicity_on_node()
subroutine cal_energy_flux_rtp::cal_helicity_on_node (type(base_field_address), intent(in) bs_trns_base, type(phys_products_address), intent(in) fe_trns_prod, integer(kind = kint), intent(in) nnod, integer(kind = kint), intent(in) ntot_comp_fld, real(kind = kreal), dimension(nnod,ntot_comp_fld), intent(in) fld_rtp, integer(kind = kint), intent(in) ntot_comp_hls, real(kind = kreal), dimension(nnod,ntot_comp_hls), intent(inout) fhls_rtp)
Definition at line 319 of file cal_energy_flux_rtp.f90.
References cal_products_smp::cal_dot_prod_no_coef_smp().
Referenced by s_cal_energy_flux_rtp().
cal_lengh_scale_rtp()
subroutine, private cal_energy_flux_rtp::cal_lengh_scale_rtp (type(sph_rtp_grid), intent(in) sph_rtp, type(base_field_address), intent(in) bs_trns_base, type(diffusion_address), intent(in) bs_trns_dif, type(phys_products_address), intent(in) fe_trns_prod, type(spherical_transform_data), intent(in) trns_b_snap, type(spherical_transform_data), intent(in) trns_b_eflux, type(spherical_transform_data), intent(inout) trns_f_eflux) private
Definition at line 425 of file cal_energy_flux_rtp.f90.
References mag_of_field_smp::cal_len_scale_by_diffuse_smp(), mag_of_field_smp::cal_len_scale_by_rot_smp(), and m_machine_parameter::np_smp.
Referenced by s_cal_energy_flux_rtp().
cal_magnetic_fluxes_pole()
subroutine cal_energy_flux_rtp::cal_magnetic_fluxes_pole (type(sph_rtp_grid), intent(in) sph_rtp, type(conductive_property), intent(in) cd_prop, type(base_force_address), intent(in) f_trns_frc, type(base_field_address), intent(in) bs_trns_base, type(diff_vector_address), intent(in) bs_trns_diff_v, type(base_force_address), intent(in) fe_trns_frc, type(phys_products_address), intent(in) fe_trns_prod, type(spherical_transform_data), intent(in) trns_f_MHD, type(spherical_transform_data), intent(in) trns_b_snap, type(spherical_transform_data), intent(in) trns_b_difv, type(spherical_transform_data), intent(inout) trns_f_eflux)
Definition at line 265 of file cal_energy_flux_rtp.f90.
References poynting_flux_smp::cal_electric_field_smp(), poynting_flux_smp::cal_poynting_flux_smp(), and poynting_flux_smp::cal_xyz_magnetic_streach().
Referenced by s_cal_energy_flux_rtp().
cal_magnetic_fluxes_rtp()
subroutine cal_energy_flux_rtp::cal_magnetic_fluxes_rtp (type(sph_rtp_grid), intent(in) sph_rtp, type(conductive_property), intent(in) cd_prop, type(base_force_address), intent(in) f_trns_frc, type(base_field_address), intent(in) bs_trns_base, type(diff_vector_address), intent(in) bs_trns_diff_v, type(base_force_address), intent(in) fe_trns_frc, type(phys_products_address), intent(in) fe_trns_prod, type(spherical_transform_data), intent(in) trns_f_MHD, type(spherical_transform_data), intent(in) trns_b_snap, type(spherical_transform_data), intent(in) trns_b_difv, type(spherical_transform_data), intent(inout) trns_f_eflux)
Definition at line 209 of file cal_energy_flux_rtp.f90.
References poynting_flux_smp::cal_electric_field_smp(), poynting_flux_smp::cal_poynting_flux_smp(), and poynting_flux_smp::cal_rtp_magnetic_streach().
Referenced by s_cal_energy_flux_rtp().
cal_square_vector_on_node()
subroutine, private cal_energy_flux_rtp::cal_square_vector_on_node (type(base_field_address), intent(in) bs_trns_base, type(phys_products_address), intent(in) fe_trns_prod, integer(kind = kint), intent(in) nnod, integer(kind = kint), intent(in) ntot_comp_fld, real(kind = kreal), dimension(nnod,ntot_comp_fld), intent(in) fld_rtp, integer(kind = kint), intent(in) ntot_comp_fmg, real(kind = kreal), dimension(nnod,ntot_comp_fmg), intent(inout) fmag_rtp) private
Definition at line 360 of file cal_energy_flux_rtp.f90.
References cal_products_smp::cal_scalar_prod_no_coef_smp(), and cal_products_smp::vector_vector_prod_smp().
Referenced by s_cal_energy_flux_rtp().
s_cal_energy_flux_rtp()
subroutine cal_energy_flux_rtp::s_cal_energy_flux_rtp (type(sph_rtp_grid), intent(in) sph_rtp, type(fluid_property), intent(in) fl_prop, type(conductive_property), intent(in) cd_prop, type(reference_scalar_param), intent(in) ref_param_T, type(reference_scalar_param), intent(in) ref_param_C, type(legendre_4_sph_trans), intent(in) leg, type(phys_address), intent(in) f_trns, type(phys_address), intent(in) bs_trns, type(phys_address), intent(in) be_trns, type(phys_address), intent(in) bs_difv, type(phys_address), intent(in) fe_trns, type(spherical_transform_data), intent(in) trns_f_MHD, type(spherical_transform_data), intent(in) trns_b_snap, type(spherical_transform_data), intent(in) trns_b_eflux, type(spherical_transform_data), intent(in) trns_b_difv, type(spherical_transform_data), intent(inout) trns_f_eflux)
Definition at line 66 of file cal_energy_flux_rtp.f90.
References cal_buoyancy_flux_sph::cal_buoyancy_flux_rtp(), cal_energy_fluxes_on_node(), cal_helicity_on_node(), cal_lengh_scale_rtp(), cal_magnetic_fluxes_pole(), cal_magnetic_fluxes_rtp(), cal_square_vector_on_node(), cal_buoyancy_flux_sph::pole_buoyancy_flux_rtp(), and const_wz_coriolis_rtp::sel_wz_coriolis_rtp().
Referenced by lead_fields_4_sph_mhd::cal_sph_enegy_fluxes().