CALYPSO: analyzer_check_sph_grids Module Reference
analyzer_check_sph_grids Module Reference
Main loop to generate spherical harmonics indices.
Functions/Subroutines
subroutine init_check_sph_grids
subroutine analyze_check_sph_grids
Variables
character(len=kchara), private control_file_name = 'control_sph_shell'
type(sph_mesh_generation_ctl), save, private sph_make_ctl
Structure for file settings.
type(sph_grids), save, private sph_const
Structure of grid and spectr data for spherical spectr method.
type(sph_comm_tables), save comms_sph_const
Structure of communication table for spherical spectr method.
type(sph_group_data), save sph_grp_const
Structure of group data for spherical spectr method.
type(gen_sph_file_io_params), save sph_files1
Structure of mesh file name and formats.
type(sph_grid_maker_in_sim), save sph_maker_g
Structure to check and construct spherical shell mesh.
Detailed Description
Main loop to generate spherical harmonics indices.
      subroutine init_check_sph_grids
      subroutine analyze_check_sph_grids
Function/Subroutine Documentation
analyze_check_sph_grids()
subroutine analyzer_check_sph_grids::analyze_check_sph_grids
Definition at line 95 of file analyzer_check_sph_grids.f90.
References calypso_mpi::calypso_mpi_abort(), calypso_mpi_int::calypso_mpi_allreduce_one_int(), calypso_mpi::calypso_mpi_barrier(), comms_sph_const, parallel_load_data_4_sph::dealloc_sph_modes(), m_machine_parameter::e_message, m_work_time::end_elapsed_time(), m_error_ids::ierr_p_mpi, m_machine_parameter::iflag_debug, m_elapsed_labels_gen_sph::iflag_gsp_time, m_elapsed_labels_gen_sph::ist_elapsed_gsp, mpi_gen_sph_grids_modes::mpi_gen_sph_grids(), calypso_mpi::my_rank, compare_sph_with_io::s_compare_sph_with_io(), sph_const, sph_files1, sph_grp_const, sph_maker_g, and m_work_time::start_elapsed_time().
Referenced by check_sph_grids().
init_check_sph_grids()
subroutine analyzer_check_sph_grids::init_check_sph_grids
Definition at line 65 of file analyzer_check_sph_grids.f90.
References calypso_mpi::calypso_mpi_abort(), control_file_name, m_machine_parameter::e_message, m_elapsed_labels_gen_sph::elpsed_label_gen_sph_grid(), m_work_time::ied_total_elapsed, m_error_ids::ierr_p_mpi, m_work_time::init_elapse_time_by_total(), calypso_mpi::my_rank, calypso_mpi::nprocs, t_ctl_data_const_sph_mesh::read_control_4_const_shell(), t_ctl_params_gen_sph_shell::set_control_4_gen_shell_grids(), sph_files1, sph_make_ctl, sph_maker_g, and m_work_time::start_elapsed_time().
Referenced by check_sph_grids().
Variable Documentation
comms_sph_const
type(sph_comm_tables), save analyzer_check_sph_grids::comms_sph_const
Structure of communication table for spherical spectr method.
Definition at line 47 of file analyzer_check_sph_grids.f90.
Referenced by analyze_check_sph_grids().
control_file_name
character (len = kchara), private analyzer_check_sph_grids::control_file_name = 'control_sph_shell' private
Definition at line 37 of file analyzer_check_sph_grids.f90.
Referenced by init_check_sph_grids().
sph_const
type(sph_grids), save, private analyzer_check_sph_grids::sph_const private
Structure of grid and spectr data for spherical spectr method.
Definition at line 45 of file analyzer_check_sph_grids.f90.
Referenced by analyze_check_sph_grids().
sph_files1
type(gen_sph_file_io_params), save analyzer_check_sph_grids::sph_files1
Structure of mesh file name and formats.
Definition at line 51 of file analyzer_check_sph_grids.f90.
Referenced by analyze_check_sph_grids(), and init_check_sph_grids().
sph_grp_const
type(sph_group_data), save analyzer_check_sph_grids::sph_grp_const
Structure of group data for spherical spectr method.
Definition at line 49 of file analyzer_check_sph_grids.f90.
Referenced by analyze_check_sph_grids().
sph_make_ctl
type(sph_mesh_generation_ctl), save, private analyzer_check_sph_grids::sph_make_ctl private
Structure for file settings.
Definition at line 42 of file analyzer_check_sph_grids.f90.
Referenced by init_check_sph_grids().
sph_maker_g
type(sph_grid_maker_in_sim), save analyzer_check_sph_grids::sph_maker_g
Structure to check and construct spherical shell mesh.
Definition at line 54 of file analyzer_check_sph_grids.f90.
Referenced by analyze_check_sph_grids(), and init_check_sph_grids().