CALYPSO: interact_coriolis_rlm Module Reference
interact_coriolis_rlm Module Reference
Evaluate Adams-Gaunt integrals for Coriolis term and coefficients for Coriolis term on f(r,l,m)
Functions/Subroutines
subroutine cal_gaunt_coriolis_rlm (l_truncation, jmax_rlm, idx_gl_1d_rlm_j, jgi_cor_rlm, jei_cor_rlm, gi_cor_rlm, ei_cor_rlm)
subroutine interact_rot_coriolis_rlm (jmax_rlm, g_sph_rlm, gi_cor_rlm, ei_cor_rlm, sw_rlm, tw_rlm, sd_rlm, td_rlm, sr_rlm, tr_rlm)
Detailed Description
Evaluate Adams-Gaunt integrals for Coriolis term and coefficients for Coriolis term on f(r,l,m)
      subroutine cal_gaunt_coriolis_rlm(l_truncation,                 &
     &         (l_truncation, jmax_rlm, idx_gl_1d_rlm_j,              &
     &          jgi_cor_rlm, jei_cor_rlm, gi_cor_rlm, ei_cor_rlm)
      subroutine interact_rot_coriolis_rlm                            &
     &         (jmax_rlm, g_sph_rlm, gi_cor_rlm, ei_cor_rlm,          &
     &          sw_rlm, tw_rlm, sd_rlm, td_rlm, sr_rlm, tr_rlm)
Parameters
l_truncation Truncation level
jmax_rlm Number of local hermonics modes
idx_gl_1d_rlm_j(jmax_rlm,3) Spherical harmonics modes list
Function/Subroutine Documentation
cal_gaunt_coriolis_rlm()
subroutine interact_coriolis_rlm::cal_gaunt_coriolis_rlm (integer(kind = kint), intent(in) l_truncation, integer(kind = kint), intent(in) jmax_rlm, integer(kind = kint), dimension(jmax_rlm,3), intent(in) idx_gl_1d_rlm_j, integer(kind = kint), dimension(jmax_rlm,2), intent(inout) jgi_cor_rlm, integer(kind = kint), dimension(jmax_rlm,1), intent(inout) jei_cor_rlm, real(kind = kreal), dimension(jmax_rlm,2), intent(inout) gi_cor_rlm, real(kind = kreal), dimension(jmax_rlm,1), intent(inout) ei_cor_rlm)
Definition at line 39 of file interact_coriolis_rlm.f90.
References t_gaunt_coriolis_rlm::find_local_sph_rlm_address(), m_constants::ione, m_constants::izero, cal_gaunt_itgs::leadki(), cal_gaunt_itgs::leadli(), and m_constants::zero.
Referenced by t_coriolis_terms_rlm::init_sum_coriolis_rlm().
interact_rot_coriolis_rlm()
subroutine interact_coriolis_rlm::interact_rot_coriolis_rlm (integer(kind = kint), intent(in) jmax_rlm, real(kind = kreal), dimension(jmax_rlm,17), intent(in) g_sph_rlm, real(kind = kreal), dimension(jmax_rlm,2), intent(in) gi_cor_rlm, real(kind = kreal), dimension(jmax_rlm,1), intent(in) ei_cor_rlm, real(kind = kreal), dimension(2,3,jmax_rlm), intent(inout) sw_rlm, real(kind = kreal), dimension(2,4,jmax_rlm), intent(inout) tw_rlm, real(kind = kreal), dimension(2,2,jmax_rlm), intent(inout) sd_rlm, real(kind = kreal), dimension(2,jmax_rlm), intent(inout) td_rlm, real(kind = kreal), dimension(2,jmax_rlm), intent(inout) sr_rlm, real(kind = kreal), dimension(2,jmax_rlm), intent(inout) tr_rlm)
Definition at line 116 of file interact_coriolis_rlm.f90.
References m_constants::half, m_constants::two, and m_constants::zero.
Referenced by t_coriolis_terms_rlm::init_sum_coriolis_rlm().