CALYPSO: t_control_param_assemble Module Reference
t_control_param_assemble Module Reference
Data Types
type control_param_assemble
Functions/Subroutines
subroutine set_assemble_rst_file_param (source_plt, assemble_plt, asbl_param)
subroutine set_assemble_ucd_file_param (source_plt, assemble_plt, asbl_param)
subroutine set_assemble_step_4_rst (t_mge_ctl, asbl_param)
subroutine set_assemble_step_4_ucd (t_mge_ctl, asbl_param)
subroutine set_control_new_step (t2_mge_ctl, asbl_param)
subroutine set_delete_flag_4_assemble (assemble_plt, asbl_param)
subroutine set_magnetic_ratio_4_assemble (magnetic_ratio_ctl, asbl_param)
Variables
character(len=kchara), parameter, private def_org_sph_fst = "restart/rst"
File prefix for new restart data.
character(len=kchara), parameter, private def_new_sph_fst = "rst_new/rst"
File prefix for new restart data.
character(len=kchara), parameter, private def_org_udt_head = 'field/out'
File prefix for original field data.
character(len=kchara), parameter, private def_new_udt_head = 'field_new/out'
File prefix for new field data.
Function/Subroutine Documentation
set_assemble_rst_file_param()
subroutine t_control_param_assemble::set_assemble_rst_file_param (type(platform_data_control), intent(in) source_plt, type(platform_data_control), intent(in) assemble_plt, type(control_param_assemble), intent(inout) asbl_param)
Definition at line 87 of file t_control_param_assemble.f90.
References def_new_sph_fst, def_org_sph_fst, and set_control_platform_data::set_parallel_file_ctl_params().
Referenced by set_control_newsph::set_control_4_newsph().
set_assemble_step_4_rst()
subroutine t_control_param_assemble::set_assemble_step_4_rst (type(time_data_control), intent(in) t_mge_ctl, type(control_param_assemble), intent(inout) asbl_param)
Definition at line 132 of file t_control_param_assemble.f90.
Referenced by set_control_newsph::set_control_4_newsph().
set_assemble_step_4_ucd()
subroutine t_control_param_assemble::set_assemble_step_4_ucd (type(time_data_control), intent(in) t_mge_ctl, type(control_param_assemble), intent(inout) asbl_param)
Definition at line 159 of file t_control_param_assemble.f90.
set_assemble_ucd_file_param()
subroutine t_control_param_assemble::set_assemble_ucd_file_param (type(platform_data_control), intent(in) source_plt, type(platform_data_control), intent(in) assemble_plt, type(control_param_assemble), intent(inout) asbl_param)
Definition at line 109 of file t_control_param_assemble.f90.
References def_new_udt_head, def_org_udt_head, and parallel_ucd_io_select::set_merged_ucd_file_ctl().
set_control_new_step()
subroutine t_control_param_assemble::set_control_new_step (type(time_data_control), intent(in) t2_mge_ctl, type(control_param_assemble), intent(inout) asbl_param)
Definition at line 186 of file t_control_param_assemble.f90.
Referenced by set_control_newsph::set_control_4_newsph().
set_delete_flag_4_assemble()
subroutine t_control_param_assemble::set_delete_flag_4_assemble (type(platform_data_control), intent(in) assemble_plt, type(control_param_assemble), intent(inout) asbl_param)
Definition at line 226 of file t_control_param_assemble.f90.
References skip_comment_f::yes_flag().
Referenced by set_control_newsph::set_control_4_newsph().
set_magnetic_ratio_4_assemble()
subroutine t_control_param_assemble::set_magnetic_ratio_4_assemble (type(read_real_item), intent(in) magnetic_ratio_ctl, type(control_param_assemble), intent(inout) asbl_param)
Definition at line 246 of file t_control_param_assemble.f90.
Referenced by set_control_newsph::set_control_4_newsph().
Variable Documentation
def_new_sph_fst
character(len=kchara), parameter, private t_control_param_assemble::def_new_sph_fst = "rst_new/rst" private
File prefix for new restart data.
Definition at line 71 of file t_control_param_assemble.f90.
Referenced by set_assemble_rst_file_param().
def_new_udt_head
character(len=kchara), parameter, private t_control_param_assemble::def_new_udt_head = 'field_new/out' private
File prefix for new field data.
Definition at line 78 of file t_control_param_assemble.f90.
Referenced by set_assemble_ucd_file_param().
def_org_sph_fst
character(len=kchara), parameter, private t_control_param_assemble::def_org_sph_fst = "restart/rst" private
File prefix for new restart data.
Definition at line 68 of file t_control_param_assemble.f90.
Referenced by set_assemble_rst_file_param().
def_org_udt_head
character(len=kchara), parameter, private t_control_param_assemble::def_org_udt_head = 'field/out' private
File prefix for original field data.
Definition at line 75 of file t_control_param_assemble.f90.
Referenced by set_assemble_ucd_file_param().