CALYPSO: gz_element_connect_io_b Module Reference
gz_element_connect_io_b Module Reference
Element data IO using zlib.
Functions/Subroutines
subroutine gz_write_element_info_b (ele_IO, zbuf)
subroutine gz_write_surface_4_element_b (sfed_IO, zbuf)
subroutine gz_write_edge_4_element_b (sfed_IO, zbuf)
subroutine gz_read_number_of_element_b (zbuf, ele_IO)
subroutine gz_read_element_info_b (zbuf, ele_IO)
subroutine gz_read_surface_4_element_b (zbuf, sfed_IO)
subroutine gz_read_edge_4_element_b (zbuf, sfed_IO)
Variables
integer(kind=kint), dimension(:), allocatable, private ie_tmp
Detailed Description
Element data IO using zlib.
      subroutine gz_write_element_info_b(ele_IO, zbuf)
      subroutine gz_write_surface_4_element_b(sfed_IO, zbuf)
      subroutine gz_write_edge_4_element_b(zbuf)
        type(element_data), intent(in) :: ele_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
        type(buffer_4_gzip), intent(inout) :: zbuf
      subroutine gz_read_number_of_element_b(zbuf, ele_IO)
      subroutine gz_read_element_info_b(zbuf, ele_IO)
        type(buffer_4_gzip), intent(inout) :: zbuf
        type(element_data), intent(inout) :: ele_IO
      subroutine gz_read_surface_4_element_b(zbuf, sfed_IO)
      subroutine gz_read_edge_4_element_b(zbuf, sfed_IO)
        type(buffer_4_gzip), intent(inout) :: zbuf
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
Function/Subroutine Documentation
gz_read_edge_4_element_b()
subroutine gz_element_connect_io_b::gz_read_edge_4_element_b (type(buffer_4_gzip), intent(inout) zbuf, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 229 of file gz_element_connect_IO_b.f90.
References t_surf_edge_io::alloc_edge_connect_io(), transfer_to_long_integers::cast_long(), gz_binary_io::gz_read_mul_integer_b(), gz_binary_io::gz_read_one_integer_b(), and ie_tmp.
Referenced by gz_edge_data_io_b::gz_read_edge_connection_b().
gz_read_element_info_b()
subroutine gz_element_connect_io_b::gz_read_element_info_b (type(buffer_4_gzip), intent(inout) zbuf, type(element_data), intent(inout) ele_IO)
Definition at line 153 of file gz_element_connect_IO_b.f90.
References t_geometry_data::alloc_ele_connectivity(), t_geometry_data::alloc_element_types(), transfer_to_long_integers::cast_long(), gz_binary_io::gz_read_mul_int8_b(), gz_binary_io::gz_read_mul_integer_b(), ie_tmp, and set_nnod_4_ele_by_type::s_set_nnod_4_ele_by_type().
Referenced by gz_edge_data_io_b::gz_read_edge_connection_b(), gz_mesh_data_io_b::gz_read_geometry_data_b(), and gz_surface_data_io_b::gz_read_surface_connection_b().
gz_read_number_of_element_b()
subroutine gz_element_connect_io_b::gz_read_number_of_element_b (type(buffer_4_gzip), intent(inout) zbuf, type(element_data), intent(inout) ele_IO)
Definition at line 138 of file gz_element_connect_IO_b.f90.
References gz_binary_io::gz_read_one_integer_b().
Referenced by gz_edge_data_io_b::gz_read_edge_connection_b(), gz_mesh_data_io_b::gz_read_num_node_ele_b(), and gz_surface_data_io_b::gz_read_surface_connection_b().
gz_read_surface_4_element_b()
subroutine gz_element_connect_io_b::gz_read_surface_4_element_b (type(buffer_4_gzip), intent(inout) zbuf, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 196 of file gz_element_connect_IO_b.f90.
References t_surf_edge_io::alloc_surface_connect_io(), transfer_to_long_integers::cast_long(), gz_binary_io::gz_read_mul_integer_b(), gz_binary_io::gz_read_one_integer_b(), and ie_tmp.
Referenced by gz_edge_data_io_b::gz_read_edge_connection_b(), and gz_surface_data_io_b::gz_read_surface_connection_b().
gz_write_edge_4_element_b()
subroutine gz_element_connect_io_b::gz_write_edge_4_element_b (type(surf_edge_io_data), intent(in) sfed_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 108 of file gz_element_connect_IO_b.f90.
References transfer_to_long_integers::cast_long(), gz_binary_io::gz_write_mul_integer_b(), gz_binary_io::gz_write_one_integer_b(), and ie_tmp.
Referenced by gz_edge_data_io_b::gz_write_edge_connection_b().
gz_write_element_info_b()
subroutine gz_element_connect_io_b::gz_write_element_info_b (type(element_data), intent(in) ele_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 47 of file gz_element_connect_IO_b.f90.
References transfer_to_long_integers::cast_long(), gz_binary_io::gz_write_mul_int8_b(), gz_binary_io::gz_write_mul_integer_b(), gz_binary_io::gz_write_one_integer_b(), and ie_tmp.
Referenced by gz_edge_data_io_b::gz_write_edge_connection_b(), gz_mesh_data_io_b::gz_write_geometry_data_b(), and gz_surface_data_io_b::gz_write_surface_connection_b().
gz_write_surface_4_element_b()
subroutine gz_element_connect_io_b::gz_write_surface_4_element_b (type(surf_edge_io_data), intent(in) sfed_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 80 of file gz_element_connect_IO_b.f90.
References transfer_to_long_integers::cast_long(), gz_binary_io::gz_write_mul_integer_b(), gz_binary_io::gz_write_one_integer_b(), and ie_tmp.
Referenced by gz_edge_data_io_b::gz_write_edge_connection_b(), and gz_surface_data_io_b::gz_write_surface_connection_b().
Variable Documentation
ie_tmp
integer (kind = kint), dimension(:), allocatable, private gz_element_connect_io_b::ie_tmp private
Definition at line 39 of file gz_element_connect_IO_b.f90.
Referenced by gz_read_edge_4_element_b(), gz_read_element_info_b(), gz_read_surface_4_element_b(), gz_write_edge_4_element_b(), gz_write_element_info_b(), and gz_write_surface_4_element_b().