CALYPSO: set_field_file_names Module Reference
set_field_file_names Module Reference
Set file names for field data file.
Functions/Subroutines
subroutine delete_fem_fld_file (file_param, num_pe, istep_fld)
subroutine delete_sph_fld_file (file_param, num_pe, istep_fld)
character(len=kchara) function set_fem_fld_file_name (file_header, itype_file, id_rank, istep_fld)
character(len=kchara) function set_sph_fld_file_name (file_header, itype_file, id_rank, istep_fld)
Detailed Description
Set file names for field data file.
      subroutine delete_FEM_fld_file                                  &
     &         (file_param, num_pe, istep_fld)
        type(field_IO_params), intent(in) :: file_param
      subroutine delete_SPH_fld_file                                  &
     &         (file_param, num_pe, istep_fld)
        type(field_IO_params), intent(in) :: file_param
      subroutine delete_SPH_fld_file(itype_file, num_pe, istep_fld)
      character(len=kchara) function set_FEM_fld_file_name            &
     &                   (file_header, itype_file, id_rank, istep_fld)
      character(len=kchara) function set_SPH_fld_file_name            &
     &                   (file_header, itype_file, id_rank, istep_fld)
Function/Subroutine Documentation
delete_fem_fld_file()
subroutine set_field_file_names::delete_fem_fld_file (type(field_io_params), intent(in) file_param, integer, intent(in) num_pe, integer(kind=kint), intent(in) istep_fld)
Definition at line 39 of file set_field_file_names.f90.
References delete_data_files::delete_file_by_f(), and set_fem_fld_file_name().
delete_sph_fld_file()
subroutine set_field_file_names::delete_sph_fld_file (type(field_io_params), intent(in) file_param, integer, intent(in) num_pe, integer(kind=kint), intent(in) istep_fld)
Definition at line 67 of file set_field_file_names.f90.
References delete_data_files::delete_file_by_f(), and set_sph_fld_file_name().
Referenced by analyzer_assemble_sph::analyze_assemble_sph().
set_fem_fld_file_name()
character(len=kchara) function set_field_file_names::set_fem_fld_file_name (character(len=kchara), intent(in) file_header, integer(kind=kint), intent(in) itype_file, integer, intent(in) id_rank, integer(kind=kint), intent(in) istep_fld)
Definition at line 96 of file set_field_file_names.f90.
References set_parallel_file_name::add_elaps_postfix(), set_mesh_extensions::add_flb_extension(), set_mesh_extensions::add_fld_extension(), set_parallel_file_name::add_gzip_extension(), set_parallel_file_name::add_int_suffix(), set_parallel_file_name::add_process_id(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, m_file_format_switch::iflag_single, m_constants::iminus, and m_constants::iten.
Referenced by field_io_select::check_step_fem_field_file(), delete_fem_fld_file(), field_io_select::sel_read_alloc_fem_fld_head(), input_old_file_sel_4_zlib::sel_read_alloc_field_file(), field_io_select::sel_read_alloc_step_fem_file(), field_io_select::sel_read_step_fem_field_file(), and field_io_select::sel_write_step_fem_field_file().
set_sph_fld_file_name()
character(len=kchara) function set_field_file_names::set_sph_fld_file_name (character(len=kchara), intent(in) file_header, integer(kind=kint), intent(in) itype_file, integer, intent(in) id_rank, integer(kind=kint), intent(in) istep_fld)
Definition at line 140 of file set_field_file_names.f90.
References set_parallel_file_name::add_elaps_postfix(), set_sph_extensions::add_fsb_extension(), set_sph_extensions::add_fst_extension(), set_parallel_file_name::add_gzip_extension(), set_parallel_file_name::add_int_suffix(), set_parallel_file_name::add_process_id(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, m_file_format_switch::iflag_single, m_constants::iminus, and m_constants::iten.
Referenced by delete_sph_fld_file(), field_io_select::sel_read_alloc_sph_fld_head(), field_io_select::sel_read_alloc_step_sph_file(), field_io_select::sel_read_step_sph_field_file(), and field_io_select::sel_write_step_sph_field_file().