CALYPSO: m_node_quad_2_linear_sf Module Reference
m_node_quad_2_linear_sf Module Reference
Functions/Subroutines
subroutine allocate_quad4_2_linear (nnod_4_ele)
subroutine deallocate_quad4_2_linear
subroutine, private allocate_quad4_2_linear_tri
subroutine, private allocate_quad8_2_linear_tri
subroutine, private allocate_quad9_2_linear_tri
Variables
integer(kind=kint) num_quad_2_tri
integer(kind=kint), dimension(:,:), allocatable node_quad_2_tri
integer(kind=kint), dimension(3, 2), parameter, private nod_quad4_2_2tris = reshape((/1, 2, 3, 3, 4, 1/), shape=(/3,2/))
integer(kind=kint), dimension(3, 6), parameter, private nod_quad8_2_6tris = reshape((/5, 6, 7, 7, 8, 5, 1, 5, 8, 2, 6, 5, 3, 7, 6, 4, 8, 7/), shape=(/3,6/))
integer(kind=kint), dimension(3, 8), parameter, private nod_quad9_2_8tris = reshape((/1, 5, 9, 9, 8, 1, 5, 2, 6, 6, 9, 5, 9, 6, 3, 3, 7, 9, 8, 9, 7, 7, 4, 8/), shape=(/3,8/))
Function/Subroutine Documentation
allocate_quad4_2_linear()
subroutine m_node_quad_2_linear_sf::allocate_quad4_2_linear (integer(kind = kint), intent(in) nnod_4_ele)
Definition at line 45 of file m_node_quad_2_linear_sf.f90.
References allocate_quad4_2_linear_tri(), allocate_quad8_2_linear_tri(), allocate_quad9_2_linear_tri(), m_geometry_constants::num_t_lag, m_geometry_constants::num_t_linear, and m_geometry_constants::num_t_quad.
Referenced by para_const_kemoview_mesh::pickup_surface_mesh().
allocate_quad4_2_linear_tri()
subroutine, private m_node_quad_2_linear_sf::allocate_quad4_2_linear_tri private
Definition at line 72 of file m_node_quad_2_linear_sf.f90.
References nod_quad4_2_2tris, node_quad_2_tri, num_quad_2_tri, and m_geometry_constants::num_triangle.
Referenced by allocate_quad4_2_linear().
allocate_quad8_2_linear_tri()
subroutine, private m_node_quad_2_linear_sf::allocate_quad8_2_linear_tri private
Definition at line 84 of file m_node_quad_2_linear_sf.f90.
References nod_quad8_2_6tris, node_quad_2_tri, num_quad_2_tri, and m_geometry_constants::num_triangle.
Referenced by allocate_quad4_2_linear().
allocate_quad9_2_linear_tri()
subroutine, private m_node_quad_2_linear_sf::allocate_quad9_2_linear_tri private
Definition at line 96 of file m_node_quad_2_linear_sf.f90.
References nod_quad9_2_8tris, node_quad_2_tri, num_quad_2_tri, and m_geometry_constants::num_triangle.
Referenced by allocate_quad4_2_linear().
deallocate_quad4_2_linear()
subroutine m_node_quad_2_linear_sf::deallocate_quad4_2_linear
Definition at line 62 of file m_node_quad_2_linear_sf.f90.
References node_quad_2_tri.
Referenced by para_const_kemoview_mesh::pickup_surface_mesh().
Variable Documentation
nod_quad4_2_2tris
integer(kind = kint), dimension(3,2), parameter, private m_node_quad_2_linear_sf::nod_quad4_2_2tris = reshape((/1, 2, 3, 3, 4, 1/), shape=(/3,2/)) private
Definition at line 22 of file m_node_quad_2_linear_sf.f90.
Referenced by allocate_quad4_2_linear_tri().
nod_quad8_2_6tris
integer(kind = kint), dimension(3,6), parameter, private m_node_quad_2_linear_sf::nod_quad8_2_6tris = reshape((/5, 6, 7, 7, 8, 5, 1, 5, 8, 2, 6, 5, 3, 7, 6, 4, 8, 7/), shape=(/3,6/)) private
Definition at line 25 of file m_node_quad_2_linear_sf.f90.
Referenced by allocate_quad8_2_linear_tri().
nod_quad9_2_8tris
integer(kind = kint), dimension(3,8), parameter, private m_node_quad_2_linear_sf::nod_quad9_2_8tris = reshape((/1, 5, 9, 9, 8, 1, 5, 2, 6, 6, 9, 5, 9, 6, 3, 3, 7, 9, 8, 9, 7, 7, 4, 8/), shape=(/3,8/)) private
Definition at line 29 of file m_node_quad_2_linear_sf.f90.
Referenced by allocate_quad9_2_linear_tri().
node_quad_2_tri
integer (kind=kint), dimension(:,:), allocatable m_node_quad_2_linear_sf::node_quad_2_tri
Definition at line 20 of file m_node_quad_2_linear_sf.f90.
Referenced by allocate_quad4_2_linear_tri(), allocate_quad8_2_linear_tri(), allocate_quad9_2_linear_tri(), and deallocate_quad4_2_linear().
num_quad_2_tri
integer (kind=kint) m_node_quad_2_linear_sf::num_quad_2_tri
Definition at line 19 of file m_node_quad_2_linear_sf.f90.
Referenced by allocate_quad4_2_linear_tri(), allocate_quad8_2_linear_tri(), and allocate_quad9_2_linear_tri().