CALYPSO: make_element_comm_table_sr Module Reference
make_element_comm_table_sr Module Reference
Routines to construca element communication table.
Functions/Subroutines
subroutine element_data_reverse_sr (num_neib_e, id_neib_e, istack_import_e, istack_export_e, inod_import_e, inod_import_l, xe_import, inod_export_e, inod_export_l, xe_export)
Detailed Description
Routines to construca element communication table.
      subroutine element_data_reverse_SR(num_neib_e, id_neib_e,       &
     &          istack_import_e, istack_export_e,                     &
     &          inod_import_e, inod_import_l, xe_import,              &
     &          inod_export_e, inod_export_l, xe_export)
Function/Subroutine Documentation
element_data_reverse_sr()
subroutine make_element_comm_table_sr::element_data_reverse_sr (integer(kind = kint), intent(in) num_neib_e, integer(kind = kint), dimension(num_neib_e), intent(in) id_neib_e, integer(kind = kint), dimension(0:num_neib_e), intent(in) istack_import_e, integer(kind = kint), dimension(0:num_neib_e), intent(in) istack_export_e, integer(kind = kint_gl), dimension(istack_import_e(num_neib_e)), intent(in) inod_import_e, integer(kind = kint), dimension(istack_import_e(num_neib_e)), intent(in) inod_import_l, real(kind = kreal), dimension(3*istack_import_e(num_neib_e)), intent(in) xe_import, integer(kind = kint_gl), dimension(istack_export_e(num_neib_e)), intent(inout) inod_export_e, integer(kind = kint), dimension(istack_export_e(num_neib_e)), intent(inout) inod_export_l, real(kind = kreal), dimension(3*istack_export_e(num_neib_e)), intent(inout) xe_export)
Definition at line 31 of file make_element_comm_table_SR.f90.
References reverse_sr_real::reverse_send_recv_3(), reverse_sr_int::reverse_send_recv_int(), reverse_sr_int8::reverse_send_recv_int8(), and m_solver_sr::sr_sig1.
Referenced by const_element_comm_table::const_comm_table_by_connenct().