CALYPSO: set_control_4_velo Module Reference
set_control_4_velo Module Reference
set boundary conditions for velocity from control data
Functions/Subroutines
subroutine s_set_control_4_velo (fl_prop, node_bc_U_ctl, surf_bc_ST_ctl, velo_nod, torque_surf)
Detailed Description
set boundary conditions for velocity from control data
      subroutine s_set_control_4_velo                                 &
     &         (fl_prop, node_bc_U_ctl, surf_bc_ST_ctl,               &
     &          velo_nod, torque_surf)
        type(fluid_property), intent(in) :: fl_prop
        type(ctl_array_c2r), intent(in) :: node_bc_U_ctl
        type(ctl_array_c2r), intent(in) :: surf_bc_ST_ctl
        type(boundary_condition_list), intent(inout) :: velo_nod
        type(boundary_condition_list), intent(inout) :: torque_surf
Function/Subroutine Documentation
s_set_control_4_velo()
subroutine set_control_4_velo::s_set_control_4_velo (type(fluid_property), intent(in) fl_prop, type(ctl_array_c2r), intent(in) node_bc_U_ctl, type(ctl_array_c2r), intent(in) surf_bc_ST_ctl, type(boundary_condition_list), intent(inout) velo_nod, type(boundary_condition_list), intent(inout) torque_surf)
Definition at line 34 of file set_control_4_velo.f90.
References t_bc_data_list::alloc_bc_type_ctl(), skip_comment_f::cmp_no_case(), t_physical_property::id_no_evolution, m_machine_parameter::iflag_debug, m_machine_parameter::iflag_full_msg, set_node_group_types::set_bc_group_types_rotation(), set_node_group_types::set_bc_group_types_sgs_vect(), set_node_group_types::set_bc_group_types_sph_center(), set_node_group_types::set_bc_group_types_sph_velo(), set_node_group_types::set_bc_group_types_vector(), set_surface_group_types::set_stress_free_group_types(), and set_surface_group_types::set_surf_group_types_vector().
Referenced by set_control_sph_mhd::set_control_sph_mhd_bcs().