CALYPSO: swap_phi_order_4_sph_trans Module Reference
swap_phi_order_4_sph_trans Module Reference
Swap array for phi componene.
Functions/Subroutines
subroutine swap_phi_from_mhd_trans (sph_rtp, trns_b_MHD, trns_f_MHD)
subroutine swap_phi_to_mhd_trans (sph_rtp, trns_b_MHD, trns_f_MHD)
Detailed Description
Swap array for phi componene.
      subroutine swap_phi_from_MHD_trans                              &
     &         (sph_rtp, trns_b_MHD, trns_f_MHD)
      subroutine swap_phi_to_MHD_trans                                &
     &         (sph_rtp, trns_b_MHD, trns_f_MHD)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(spherical_transform_data), intent(inout) :: trns_b_MHD
        type(spherical_transform_data), intent(inout) :: trns_f_MHD
Function/Subroutine Documentation
swap_phi_from_mhd_trans()
subroutine swap_phi_order_4_sph_trans::swap_phi_from_mhd_trans (type(sph_rtp_grid), intent(in) sph_rtp, type(spherical_transform_data), intent(inout) trns_b_MHD, type(spherical_transform_data), intent(inout) trns_f_MHD)
Definition at line 35 of file swap_phi_order_4_sph_trans.f90.
References m_fft_selector::iflag_fft, m_fft_selector::iflag_fftw, and swap_phi_4_sph_trans::swap_phi_order_from_trans().
Referenced by lead_fields_4_sph_mhd::lead_fields_by_sph_trans().
swap_phi_to_mhd_trans()
subroutine swap_phi_order_4_sph_trans::swap_phi_to_mhd_trans (type(sph_rtp_grid), intent(in) sph_rtp, type(spherical_transform_data), intent(inout) trns_b_MHD, type(spherical_transform_data), intent(inout) trns_f_MHD)
Definition at line 57 of file swap_phi_order_4_sph_trans.f90.
References m_fft_selector::iflag_fft, m_fft_selector::iflag_fftw, and swap_phi_4_sph_trans::swap_phi_order_to_trans().