CALYPSO: t_sph_trans_arrays_mhd Module Reference
t_sph_trans_arrays_mhd Module Reference
Field addresses for spherical harmonics transform in MHD dynamo simulation.
Data Types
type address_4_sph_trans
strucutre of spherical transform data addresses
type works_4_sph_trans_mhd
strucutres for spherical transform for MHD dynamo
Functions/Subroutines
subroutine alloc_sph_trans_address (sph_rtp, WK)
subroutine dealloc_sph_trans_address (WK)
subroutine alloc_sph_trans_area_snap (sph_rtp, WK)
subroutine dealloc_sph_trans_area_snap (WK)
subroutine, private alloc_nonlinear_data (sph_rtp, trns)
subroutine, private alloc_nonlinear_pole (sph_rtp, trns)
subroutine, private dealloc_nonlinear_data (trns)
subroutine, private dealloc_nonlinear_pole (trns)
Detailed Description
Field addresses for spherical harmonics transform in MHD dynamo simulation.
Function/Subroutine Documentation
alloc_nonlinear_data()
subroutine, private t_sph_trans_arrays_mhd::alloc_nonlinear_data (type(sph_rtp_grid), intent(in) sph_rtp, type(address_4_sph_trans), intent(inout) trns) private
Definition at line 150 of file t_sph_trans_arrays_MHD.f90.
References t_addresses_sph_transform::alloc_sph_trns_field_data().
Referenced by alloc_sph_trans_address(), and alloc_sph_trans_area_snap().
alloc_nonlinear_pole()
subroutine, private t_sph_trans_arrays_mhd::alloc_nonlinear_pole (type(sph_rtp_grid), intent(in) sph_rtp, type(address_4_sph_trans), intent(inout) trns) private
Definition at line 163 of file t_sph_trans_arrays_MHD.f90.
References t_addresses_sph_transform::alloc_sph_trns_pole_data().
Referenced by alloc_sph_trans_address(), and alloc_sph_trans_area_snap().
alloc_sph_trans_address()
subroutine t_sph_trans_arrays_mhd::alloc_sph_trans_address (type(sph_rtp_grid), intent(in) sph_rtp, type(works_4_sph_trans_mhd), intent(inout) WK)
Definition at line 87 of file t_sph_trans_arrays_MHD.f90.
References alloc_nonlinear_data(), and alloc_nonlinear_pole().
Referenced by init_sphrical_transform_mhd::init_sph_transform_mhd().
alloc_sph_trans_area_snap()
subroutine t_sph_trans_arrays_mhd::alloc_sph_trans_area_snap (type(sph_rtp_grid), intent(in) sph_rtp, type(works_4_sph_trans_mhd), intent(inout) WK)
Definition at line 112 of file t_sph_trans_arrays_MHD.f90.
References alloc_nonlinear_data(), and alloc_nonlinear_pole().
Referenced by analyzer_sph_dynamobench::evolution_sph_dynamobench(), analyzer_sph_mhd_w_psf::evolution_sph_mhd_w_psf(), and analyzer_sph_snap_w_psf::evolution_sph_snap_w_psf().
dealloc_nonlinear_data()
subroutine, private t_sph_trans_arrays_mhd::dealloc_nonlinear_data (type(address_4_sph_trans), intent(inout) trns) private
Definition at line 176 of file t_sph_trans_arrays_MHD.f90.
References t_addresses_sph_transform::dealloc_sph_trns_field_dats().
Referenced by dealloc_sph_trans_address(), and dealloc_sph_trans_area_snap().
dealloc_nonlinear_pole()
subroutine, private t_sph_trans_arrays_mhd::dealloc_nonlinear_pole (type(address_4_sph_trans), intent(inout) trns) private
Definition at line 188 of file t_sph_trans_arrays_MHD.f90.
References t_addresses_sph_transform::dealloc_sph_trns_pole_data().
Referenced by dealloc_sph_trans_address(), and dealloc_sph_trans_area_snap().
dealloc_sph_trans_address()
subroutine t_sph_trans_arrays_mhd::dealloc_sph_trans_address (type(works_4_sph_trans_mhd), intent(inout) WK)
Definition at line 100 of file t_sph_trans_arrays_MHD.f90.
References dealloc_nonlinear_data(), and dealloc_nonlinear_pole().
dealloc_sph_trans_area_snap()
subroutine t_sph_trans_arrays_mhd::dealloc_sph_trans_area_snap (type(works_4_sph_trans_mhd), intent(inout) WK)
Definition at line 131 of file t_sph_trans_arrays_MHD.f90.
References dealloc_nonlinear_data(), and dealloc_nonlinear_pole().
Referenced by analyzer_sph_dynamobench::evolution_sph_dynamobench(), analyzer_sph_mhd_w_psf::evolution_sph_mhd_w_psf(), and analyzer_sph_snap_w_psf::evolution_sph_snap_w_psf().