CALYPSO: t_work_4_sph_trans Module Reference
t_work_4_sph_trans Module Reference
global addresses for spherical transform communication test
Data Types
type index_4_sph_trans
Structure of indices for spherical transforms.
type parameters_4_sph_trans
Structures of parameters for spherical transform.
Functions/Subroutines
subroutine alloc_work_4_sph_trans (nidx_rtm, nidx_rlm, idx_trns)
subroutine alloc_l_rtm_block (idx_trns)
subroutine dealloc_work_4_sph_trans (idx_trns)
subroutine dealloc_l_rtm_block (idx_trns)
subroutine set_import_table_ctl (import_ctl, trans_p)
subroutine write_import_table_mode (trans_p)
subroutine check_mdx_pn_rlm_rtm (id_file, nidx_rlm, nidx_rtm, idx_trns)
Variables
character(len=kchara), parameter hd_import_item = 'regular_table'
Character flag to use import table.
character(len=kchara), parameter hd_import_rev = 'reversed_table'
Character flag to use reverse import table.
Detailed Description
global addresses for spherical transform communication test
      subroutine alloc_work_4_sph_trans(nidx_rtm, nidx_rlm, idx_trns)
      subroutine alloc_l_rtm_block(idx_trns)
        type(index_4_sph_trans), intent(inout) :: idx_trns
      subroutine dealloc_work_4_sph_trans(idx_trns)
      subroutine dealloc_l_rtm_block(idx_trns)
        type(index_4_sph_trans), intent(inout) :: idx_trns
      subroutine set_import_table_ctl(import_ctl, trans_p)
        type(parameters_4_sph_trans), intent(inout) :: trans_p
      subroutine write_import_table_mode(trans_p)
        type(parameters_4_sph_trans), intent(in) :: trans_p
      subroutine check_mdx_pn_rlm_rtm                                 &
     &        (id_file, nidx_rlm, nidx_rtm, idx_trns)
        type(index_4_sph_trans), intent(in) :: idx_trns
Function/Subroutine Documentation
alloc_l_rtm_block()
subroutine t_work_4_sph_trans::alloc_l_rtm_block (type(index_4_sph_trans), intent(inout) idx_trns)
Definition at line 132 of file t_work_4_sph_trans.f90.
Referenced by init_sph_trans::set_blocks_4_leg_trans().
alloc_work_4_sph_trans()
subroutine t_work_4_sph_trans::alloc_work_4_sph_trans (integer(kind = kint), dimension(3), intent(in) nidx_rtm, integer(kind = kint), dimension(2), intent(in) nidx_rlm, type(index_4_sph_trans), intent(inout) idx_trns)
Definition at line 99 of file t_work_4_sph_trans.f90.
Referenced by init_sph_trans::initialize_legendre_trans().
check_mdx_pn_rlm_rtm()
subroutine t_work_4_sph_trans::check_mdx_pn_rlm_rtm (integer(kind = kint), intent(in) id_file, integer(kind = kint), dimension(2), intent(in) nidx_rlm, integer(kind = kint), dimension(3), intent(in) nidx_rtm, type(index_4_sph_trans), intent(in) idx_trns)
Definition at line 211 of file t_work_4_sph_trans.f90.
dealloc_l_rtm_block()
subroutine t_work_4_sph_trans::dealloc_l_rtm_block (type(index_4_sph_trans), intent(inout) idx_trns)
Definition at line 161 of file t_work_4_sph_trans.f90.
dealloc_work_4_sph_trans()
subroutine t_work_4_sph_trans::dealloc_work_4_sph_trans (type(index_4_sph_trans), intent(inout) idx_trns)
Definition at line 145 of file t_work_4_sph_trans.f90.
set_import_table_ctl()
subroutine t_work_4_sph_trans::set_import_table_ctl (character(len = kchara), intent(in) import_ctl, type(parameters_4_sph_trans), intent(inout) trans_p)
Definition at line 173 of file t_work_4_sph_trans.f90.
References skip_comment_f::cmp_no_case(), hd_import_item, hd_import_rev, select_copy_from_recv::iflag_import_item, select_copy_from_recv::iflag_import_rev, and select_copy_from_recv::iflag_import_undefined.
Referenced by set_control_sph_data_mhd::s_set_control_sph_data_mhd().
write_import_table_mode()
subroutine t_work_4_sph_trans::write_import_table_mode (type(parameters_4_sph_trans), intent(in) trans_p)
Definition at line 193 of file t_work_4_sph_trans.f90.
References hd_import_item, hd_import_rev, select_copy_from_recv::iflag_import_item, and select_copy_from_recv::iflag_import_rev.
Referenced by init_sphrical_transform_mhd::init_leg_fourier_trans_mhd(), and init_sph_trans::initialize_sph_trans().
Variable Documentation
hd_import_item
character(len = kchara), parameter t_work_4_sph_trans::hd_import_item = 'regular_table'
Character flag to use import table.
Definition at line 39 of file t_work_4_sph_trans.f90.
Referenced by set_import_table_ctl(), and write_import_table_mode().
hd_import_rev
character(len = kchara), parameter t_work_4_sph_trans::hd_import_rev = 'reversed_table'
Character flag to use reverse import table.
Definition at line 42 of file t_work_4_sph_trans.f90.
Referenced by set_import_table_ctl(), and write_import_table_mode().