CALYPSO: zlib_cvt_vtk_data Module Reference
zlib_cvt_vtk_data Module Reference
Output merged VTK file usging MPI-IO.
Functions/Subroutines
subroutine defleate_vtk_scalar (nnod, num, vect, zbuf)
subroutine defleate_vtk_vector (nnod, num, vect, zbuf)
subroutine defleate_vtk_tensor (nnod, num, vect, zbuf)
subroutine defleate_vtk_connect (nele, ie, nnod_ele, zbuf)
subroutine defleate_vtk_celltype (nele, nnod_ele, zbuf)
Detailed Description
Output merged VTK file usging MPI-IO.
      subroutine defleate_vtk_scalar(nnod, num, vect, zbuf)
      subroutine defleate_vtk_vector(nnod, num, vect, zbuf)
      subroutine defleate_vtk_tensor(nnod, num, vect, zbuf)
      subroutine defleate_vtk_celltype(nele, nnod_ele, zbuf)
        type(buffer_4_gzip), intent(inout) :: zbuf
Function/Subroutine Documentation
defleate_vtk_celltype()
subroutine zlib_cvt_vtk_data::defleate_vtk_celltype (integer(kind = kint_gl), intent(in) nele, integer(kind = kint), intent(in) nnod_ele, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 287 of file zlib_cvt_vtk_data.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), gzip_defleate::gzip_defleat_char_begin(), gzip_defleate::gzip_defleat_char_cont(), gzip_defleate::gzip_defleat_char_last(), gzip_defleate::gzip_defleat_char_once(), m_constants::huge_30, vtk_data_to_buffer::vtk_cell_type(), and vtk_data_to_buffer::vtk_each_cell_type().
Referenced by gz_vtk_file_mpi_io::gz_write_vtk_mesh_mpi().
defleate_vtk_connect()
subroutine zlib_cvt_vtk_data::defleate_vtk_connect (integer(kind = kint_gl), intent(in) nele, integer(kind = kint_gl), dimension(nele,nnod_ele), intent(in) ie, integer(kind = kint), intent(in) nnod_ele, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 228 of file zlib_cvt_vtk_data.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), gzip_defleate::gzip_defleat_char_begin(), gzip_defleate::gzip_defleat_char_cont(), gzip_defleate::gzip_defleat_char_last(), gzip_defleate::gzip_defleat_char_once(), m_constants::huge_30, and vtk_data_to_buffer::vtk_each_connect().
Referenced by gz_vtk_file_mpi_io::gz_write_vtk_mesh_mpi().
defleate_vtk_scalar()
subroutine zlib_cvt_vtk_data::defleate_vtk_scalar (integer(kind = kint_gl), intent(in) nnod, integer(kind = kint_gl), intent(in) num, real(kind = kreal), dimension(nnod), intent(in) vect, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 33 of file zlib_cvt_vtk_data.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), gzip_defleate::gzip_defleat_char_begin(), gzip_defleate::gzip_defleat_char_cont(), gzip_defleate::gzip_defleat_char_last(), gzip_defleate::gzip_defleat_char_once(), m_constants::huge_30, vtk_data_to_buffer::vtk_each_scalar(), and m_constants::zero.
Referenced by gz_vtk_file_mpi_io::gz_write_vtk_scalar_mpi().
defleate_vtk_tensor()
subroutine zlib_cvt_vtk_data::defleate_vtk_tensor (integer(kind = kint_gl), intent(in) nnod, integer(kind = kint_gl), intent(in) num, real(kind = kreal), dimension(nnod,6), intent(in) vect, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 144 of file zlib_cvt_vtk_data.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), gzip_defleate::gzip_defleat_char_begin(), gzip_defleate::gzip_defleat_char_cont(), gzip_defleate::gzip_defleat_char_last(), m_constants::huge_30, vtk_data_to_buffer::vtk_each_vector(), and m_constants::zero.
Referenced by gz_vtk_file_mpi_io::gz_write_vtk_tensor_mpi().
defleate_vtk_vector()
subroutine zlib_cvt_vtk_data::defleate_vtk_vector (integer(kind = kint_gl), intent(in) nnod, integer(kind = kint_gl), intent(in) num, real(kind = kreal), dimension(nnod,3), intent(in) vect, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 87 of file zlib_cvt_vtk_data.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), gzip_defleate::gzip_defleat_char_begin(), gzip_defleate::gzip_defleat_char_cont(), gzip_defleate::gzip_defleat_char_last(), gzip_defleate::gzip_defleat_char_once(), m_constants::huge_30, vtk_data_to_buffer::vtk_each_vector(), and m_constants::zero.
Referenced by gz_vtk_file_mpi_io::gz_write_vtk_vecotr_mpi().