CALYPSO: gz_udt_to_vtk_data_io Module Reference
gz_udt_to_vtk_data_io Module Reference
ucd data into VTK format IO
Functions/Subroutines
subroutine write_gz_ucd_field_to_vtk (ucd, zbuf)
subroutine write_gz_ucd_mesh_to_vtk (ucd, zbuf)
subroutine read_gz_udt_field_from_vtk (ucd, zbuf)
subroutine read_alloc_gz_udt_fld_from_vtk (ucd, zbuf)
subroutine read_gz_ucd_grd_from_vtk (ucd, zbuf)
subroutine read_alloc_gz_ucd_grd_from_vtk (ucd, zbuf)
Detailed Description
ucd data into VTK format IO
      subroutine write_gz_ucd_field_to_VTK(ucd, zbuf)
      subroutine write_gz_ucd_mesh_to_VTK(ucd, zbuf)
        type(ucd_data), intent(in) :: ucd
        type(buffer_4_gzip), intent(inout) :: zbuf
      subroutine read_gz_udt_field_from_VTK(ucd, zbuf)
      subroutine read_alloc_gz_udt_fld_from_VTK(ucd, zbuf)
      subroutine read_gz_ucd_grd_from_VTK(ucd, zbuf)
      subroutine read_alloc_gz_ucd_grd_from_VTK(ucd, zbuf)
        type(ucd_data), intent(inout) :: ucd
        type(buffer_4_gzip), intent(inout) :: zbuf
Function/Subroutine Documentation
read_alloc_gz_ucd_grd_from_vtk()
subroutine gz_udt_to_vtk_data_io::read_alloc_gz_ucd_grd_from_vtk (type(ucd_data), intent(inout) ucd, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 218 of file gz_udt_to_VTK_data_IO.f90.
References t_ucd_data::allocate_ucd_ele(), t_ucd_data::allocate_ucd_node(), m_constants::ithree, gz_vtk_data_io::read_gz_vtk_cell_type(), gz_vtk_data_io::read_gz_vtk_connect_data(), gz_vtk_data_io::read_gz_vtk_connect_head(), gz_vtk_data_io::read_gz_vtk_each_field(), and gz_vtk_data_io::read_gz_vtk_node_head().
Referenced by gz_vtk_file_io::read_alloc_gz_vtk_file(), and gz_vtk_file_io::read_alloc_gz_vtk_grid().
read_alloc_gz_udt_fld_from_vtk()
subroutine gz_udt_to_vtk_data_io::read_alloc_gz_udt_fld_from_vtk (type(ucd_data), intent(inout) ucd, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 126 of file gz_udt_to_VTK_data_IO.f90.
References t_ucd_data::allocate_ucd_phys_data(), t_ucd_data::allocate_ucd_phys_name(), t_ucd_data::append_new_ucd_field_data(), t_ucd_data::append_new_ucd_field_name(), t_ucd_data::deallocate_ucd_data(), m_constants::izero, gz_vtk_data_io::read_gz_vtk_each_field(), gz_vtk_data_io::read_gz_vtk_each_field_head(), and gz_vtk_data_io::read_gz_vtk_fields_head().
Referenced by gz_vtk_file_io::read_alloc_gz_vtk_file(), and gz_vtk_file_io::read_alloc_gz_vtk_phys().
read_gz_ucd_grd_from_vtk()
subroutine gz_udt_to_vtk_data_io::read_gz_ucd_grd_from_vtk (type(ucd_data), intent(inout) ucd, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 177 of file gz_udt_to_VTK_data_IO.f90.
References m_constants::ithree, gz_vtk_data_io::read_gz_vtk_cell_type(), gz_vtk_data_io::read_gz_vtk_connect_data(), gz_vtk_data_io::read_gz_vtk_connect_head(), gz_vtk_data_io::read_gz_vtk_each_field(), and gz_vtk_data_io::read_gz_vtk_node_head().
Referenced by gz_vtk_file_io::read_gz_vtk_file(), and gz_vtk_file_io::read_gz_vtk_grid().
read_gz_udt_field_from_vtk()
subroutine gz_udt_to_vtk_data_io::read_gz_udt_field_from_vtk (type(ucd_data), intent(inout) ucd, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 77 of file gz_udt_to_VTK_data_IO.f90.
References skip_comment_f::cmp_no_case(), copy_between_two_fields::copy_fields_2_fields(), m_constants::ione, m_constants::izero, gz_vtk_data_io::read_gz_vtk_each_field(), gz_vtk_data_io::read_gz_vtk_each_field_head(), and gz_vtk_data_io::read_gz_vtk_fields_head().
Referenced by gz_vtk_file_io::read_gz_vtk_file(), and gz_vtk_file_io::read_gz_vtk_phys().
write_gz_ucd_field_to_vtk()
subroutine gz_udt_to_vtk_data_io::write_gz_ucd_field_to_vtk (type(ucd_data), intent(in) ucd, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 42 of file gz_udt_to_VTK_data_IO.f90.
References gz_vtk_data_io::write_gz_vtk_data(), and gz_vtk_data_io::write_gz_vtk_fields_head().
Referenced by gz_vtk_file_io::write_gz_vtk_file(), and gz_vtk_file_io::write_gz_vtk_phys().
write_gz_ucd_mesh_to_vtk()
subroutine gz_udt_to_vtk_data_io::write_gz_ucd_mesh_to_vtk (type(ucd_data), intent(in) ucd, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 56 of file gz_udt_to_VTK_data_IO.f90.
References gz_vtk_data_io::write_gz_vtk_cell_type(), gz_vtk_data_io::write_gz_vtk_connect_data(), gz_vtk_data_io::write_gz_vtk_connect_head(), gz_vtk_data_io::write_gz_vtk_each_field(), and gz_vtk_data_io::write_gz_vtk_node_head().
Referenced by gz_vtk_file_io::write_gz_vtk_file(), and gz_vtk_file_io::write_gz_vtk_grid().