CALYPSO: half_chebyshev_radial_grid Module Reference
half_chebyshev_radial_grid Module Reference
Set radial grid data.
Functions/Subroutines
subroutine half_chebyshev_distance_shell (num_layer, nlayer_CMB, r_CMB, r_grid)
subroutine count_half_chebyshev_external (nri, r_CMB, r_max, ntot_shell, nlayer_ICB, nlayer_CMB)
Detailed Description
Set radial grid data.
      subroutine half_chebyshev_distance_shell                        &
     &         (num_layer, nlayer_CMB, r_CMB, r_grid)
      subroutine count_half_chebyshev_external(nri, r_CMB, r_max,     &
     &          ntot_shell, nlayer_ICB, nlayer_CMB)
Function/Subroutine Documentation
count_half_chebyshev_external()
subroutine half_chebyshev_radial_grid::count_half_chebyshev_external (integer(kind = kint), intent(in) nri, real(kind = kreal), intent(in) r_CMB, real(kind = kreal), intent(in) r_max, integer(kind = kint), intent(inout) ntot_shell, integer(kind = kint), intent(inout) nlayer_ICB, integer(kind = kint), intent(inout) nlayer_CMB)
Definition at line 68 of file half_chebyshev_radial_grid.f90.
References m_constants::four, m_constants::half, and m_constants::one.
Referenced by const_sph_radial_grid::count_set_radial_grid().
half_chebyshev_distance_shell()
subroutine half_chebyshev_radial_grid::half_chebyshev_distance_shell (integer(kind = kint), intent(in) num_layer, integer(kind = kint), intent(in) nlayer_CMB, real(kind = kreal), intent(in) r_CMB, real(kind = kreal), dimension(num_layer), intent(inout) r_grid)
Definition at line 29 of file half_chebyshev_radial_grid.f90.
References m_constants::four, m_constants::half, and m_constants::one.
Referenced by const_sph_radial_grid::count_set_radial_grid(), and set_radial_grid_sph_shell::set_radial_distance_flag().