CALYPSO: t_group_data Module Reference
t_group_data Module Reference
Structure of group data.
Data Types
type group_data
Structure for node and element group.
type surface_group_data
Structure for surfacet group.
Functions/Subroutines
subroutine alloc_group_num (grp)
subroutine alloc_group_item (grp)
subroutine alloc_group_smp (grp)
subroutine alloc_sf_group_num (sf_grp)
subroutine alloc_sf_group_item (sf_grp)
subroutine alloc_sf_group_smp (sf_grp)
subroutine dealloc_group (grp)
subroutine dealloc_group_num (grp)
subroutine dealloc_group_item (grp)
subroutine dealloc_group_smp (grp)
subroutine dealloc_sf_group (sf_grp)
subroutine dealloc_sf_group_num (sf_grp)
subroutine dealloc_sf_group_item (sf_grp)
subroutine dealloc_sf_group_smp (sf_grp)
subroutine check_group_type_data (id_rank, grp)
subroutine check_surf_grp_type_data (id_rank, sf_grp)
subroutine compare_group_types (id_rank, grp_ref, grp)
subroutine compare_surface_grp_types (id_rank, sf_grp_ref, sf_grp)
subroutine check_grp_4_sheard_para (id_rank, grp)
subroutine check_surf_grp_4_sheard_para (id_rank, sf_grp)
Detailed Description
Structure of group data.
Function/Subroutine Documentation
alloc_group_item()
subroutine t_group_data::alloc_group_item (type(group_data), intent(inout) grp)
Definition at line 119 of file t_group_data.f90.
Referenced by add_comm_table_in_node_grp::add_comm_table_in_node_group(), copy_mesh_structures::copy_group_data(), t_const_spherical_grid::empty_theta_rtp_grp(), gz_mpi_groups_io::gz_mpi_read_group_data(), gz_mpi_groups_io_b::gz_mpi_read_group_data_b(), gz_groups_io_b::gz_read_group_data_b(), mpi_groups_io::mpi_read_group_data(), mpi_groups_io_b::mpi_read_group_data_b(), groups_io::read_group_data(), groups_io_b::read_group_data_b(), gz_group_data_io::read_group_data_gz(), set_group_types_4_io::set_gruop_stracture(), set_sph_groups::set_no_rtp_meridian_grp(), set_sph_groups::set_no_rtp_node_grp(), set_sph_groups::set_no_rtp_zonal_grp(), set_sph_groups::set_rj_radial_grp(), set_sph_groups::set_rj_spectr_grp(), set_sph_groups::set_rtp_meridional_grp(), set_sph_groups::set_rtp_radial_grp(), and mpi_load_mesh_data::sync_group_name_4_empty().
alloc_group_num()
subroutine t_group_data::alloc_group_num (type(group_data), intent(inout) grp)
Definition at line 104 of file t_group_data.f90.
Referenced by add_comm_table_in_node_grp::add_comm_table_in_node_group(), copy_mesh_structures::copy_group_data(), t_const_spherical_grid::empty_theta_rtp_grp(), gz_mpi_groups_io::gz_mpi_read_group_data(), gz_mpi_groups_io_b::gz_mpi_read_group_data_b(), gz_groups_io_b::gz_read_group_data_b(), mpi_groups_io::mpi_read_group_data(), mpi_groups_io_b::mpi_read_group_data_b(), groups_io::read_group_data(), groups_io_b::read_group_data_b(), gz_group_data_io::read_group_data_gz(), set_group_types_4_io::set_gruop_stracture(), set_sph_groups::set_no_rtp_meridian_grp(), set_sph_groups::set_no_rtp_node_grp(), set_sph_groups::set_no_rtp_zonal_grp(), set_sph_groups::set_rj_radial_grp(), set_sph_groups::set_rj_spectr_grp(), set_sph_groups::set_rtp_meridional_grp(), set_sph_groups::set_rtp_radial_grp(), and mpi_load_mesh_data::sync_group_name_4_empty().
alloc_group_smp()
subroutine t_group_data::alloc_group_smp (type(group_data), intent(inout) grp)
Definition at line 132 of file t_group_data.f90.
Referenced by set_smp_4_group_types::count_grp_type_smp().
alloc_sf_group_item()
subroutine t_group_data::alloc_sf_group_item (type(surface_group_data), intent(inout) sf_grp)
Definition at line 159 of file t_group_data.f90.
Referenced by copy_mesh_structures::copy_surface_group(), gz_mpi_groups_io::gz_mpi_read_surf_grp_data(), gz_mpi_groups_io_b::gz_mpi_read_surf_grp_data_b(), gz_groups_io_b::gz_read_surf_grp_data_b(), mpi_groups_io::mpi_read_surf_grp_data(), mpi_groups_io_b::mpi_read_surf_grp_data_b(), groups_io::read_surf_grp_data(), groups_io_b::read_surf_grp_data_b(), gz_group_data_io::read_surface_group_data_gz(), set_group_types_4_io::set_surf_grp_stracture(), and mpi_load_mesh_data::sync_group_name_4_empty().
alloc_sf_group_num()
subroutine t_group_data::alloc_sf_group_num (type(surface_group_data), intent(inout) sf_grp)
Definition at line 144 of file t_group_data.f90.
Referenced by copy_mesh_structures::copy_surface_group(), gz_mpi_groups_io::gz_mpi_read_surf_grp_data(), gz_mpi_groups_io_b::gz_mpi_read_surf_grp_data_b(), gz_groups_io_b::gz_read_surf_grp_data_b(), mpi_groups_io::mpi_read_surf_grp_data(), mpi_groups_io_b::mpi_read_surf_grp_data_b(), groups_io::read_surf_grp_data(), groups_io_b::read_surf_grp_data_b(), gz_group_data_io::read_surface_group_data_gz(), set_group_types_4_io::set_surf_grp_stracture(), and mpi_load_mesh_data::sync_group_name_4_empty().
alloc_sf_group_smp()
subroutine t_group_data::alloc_sf_group_smp (type(surface_group_data), intent(inout) sf_grp)
Definition at line 172 of file t_group_data.f90.
Referenced by set_smp_4_group_types::count_surf_grp_type_smp().
check_group_type_data()
subroutine t_group_data::check_group_type_data (integer, intent(in) id_rank, type(group_data), intent(in) grp)
Definition at line 272 of file t_group_data.f90.
check_grp_4_sheard_para()
subroutine t_group_data::check_grp_4_sheard_para (integer, intent(in) id_rank, type(group_data), intent(in) grp)
Definition at line 379 of file t_group_data.f90.
check_surf_grp_4_sheard_para()
subroutine t_group_data::check_surf_grp_4_sheard_para (integer, intent(in) id_rank, type(surface_group_data), intent(in) sf_grp)
Definition at line 393 of file t_group_data.f90.
check_surf_grp_type_data()
subroutine t_group_data::check_surf_grp_type_data (integer, intent(in) id_rank, type(surface_group_data), intent(in) sf_grp)
Definition at line 292 of file t_group_data.f90.
compare_group_types()
subroutine t_group_data::compare_group_types (integer, intent(in) id_rank, type(group_data), intent(in) grp_ref, type(group_data), intent(in) grp)
Definition at line 314 of file t_group_data.f90.
Referenced by t_mesh_data::compare_mesh_groups().
compare_surface_grp_types()
subroutine t_group_data::compare_surface_grp_types (integer, intent(in) id_rank, type(surface_group_data), intent(in) sf_grp_ref, type(surface_group_data), intent(in) sf_grp)
Definition at line 345 of file t_group_data.f90.
Referenced by t_mesh_data::compare_mesh_groups().
dealloc_group()
subroutine t_group_data::dealloc_group (type(group_data), intent(inout) grp)
Definition at line 184 of file t_group_data.f90.
References dealloc_group_item(), and dealloc_group_num().
Referenced by add_comm_table_in_node_grp::add_comm_tbl_in_node_grp_mesh(), t_const_spherical_grid::dealloc_gen_sph_radial_groups(), t_mesh_data::dealloc_groups_data(), t_spheric_group::dealloc_sph_grid_group(), and t_spheric_group::dealloc_sph_mode_group().
dealloc_group_item()
subroutine t_group_data::dealloc_group_item (type(group_data), intent(inout) grp)
Definition at line 207 of file t_group_data.f90.
Referenced by dealloc_group().
dealloc_group_num()
subroutine t_group_data::dealloc_group_num (type(group_data), intent(inout) grp)
Definition at line 195 of file t_group_data.f90.
Referenced by dealloc_group().
dealloc_group_smp()
subroutine t_group_data::dealloc_group_smp (type(group_data), intent(inout) grp)
Definition at line 217 of file t_group_data.f90.
Referenced by t_mesh_data::dealloc_nod_ele_infos().
dealloc_sf_group()
subroutine t_group_data::dealloc_sf_group (type(surface_group_data), intent(inout) sf_grp)
Definition at line 228 of file t_group_data.f90.
References dealloc_sf_group_item(), and dealloc_sf_group_num().
Referenced by t_mesh_data::dealloc_groups_data().
dealloc_sf_group_item()
subroutine t_group_data::dealloc_sf_group_item (type(surface_group_data), intent(inout) sf_grp)
Definition at line 251 of file t_group_data.f90.
Referenced by dealloc_sf_group().
dealloc_sf_group_num()
subroutine t_group_data::dealloc_sf_group_num (type(surface_group_data), intent(inout) sf_grp)
Definition at line 239 of file t_group_data.f90.
Referenced by dealloc_sf_group().
dealloc_sf_group_smp()
subroutine t_group_data::dealloc_sf_group_smp (type(surface_group_data), intent(inout) sf_grp)
Definition at line 261 of file t_group_data.f90.
Referenced by t_mesh_data::dealloc_nod_ele_infos().