CALYPSO: const_kemoview_mesh Module Reference
const_kemoview_mesh Module Reference
Surface mesh data generator for kemoviewer.
Functions/Subroutines
subroutine const_surf_mesh_4_viewer (group, mesh, view_mesh, domain_grps, view_nod_grps, view_ele_grps, view_sf_grps)
subroutine, private set_surf_domain_id_viewer (merged_surf, view_mesh)
Detailed Description
Surface mesh data generator for kemoviewer.
      subroutine const_surf_mesh_4_viewer                             &
     &       (group, mesh, view_mesh, domain_grps,                    &
     &        view_nod_grps, view_ele_grps, view_sf_grps)
        type(mesh_groups), intent(in) :: group
        type(mesh_geometry), intent(inout) :: mesh
        type(viewer_mesh_data), intent(inout) :: view_mesh
        type(viewer_surface_groups), intent(inout) :: domain_grps
        type(viewer_node_groups), intent(inout) :: view_nod_grps
        type(viewer_surface_groups), intent(inout) :: view_ele_grps
        type(viewer_surface_groups), intent(inout) :: view_sf_grps
Function/Subroutine Documentation
const_surf_mesh_4_viewer()
subroutine const_kemoview_mesh::const_surf_mesh_4_viewer (type(mesh_groups), intent(in) group, type(mesh_geometry), intent(inout) mesh, type(viewer_mesh_data), intent(inout) view_mesh, type(viewer_surface_groups), intent(inout) domain_grps, type(viewer_node_groups), intent(inout) view_nod_grps, type(viewer_surface_groups), intent(inout) view_ele_grps, type(viewer_surface_groups), intent(inout) view_sf_grps)
Definition at line 45 of file const_kemoview_mesh.f90.
References const_merged_surf_4_group::const_merged_surface_4_ele_grp(), const_merged_surf_4_group::const_merged_surface_4_sf_grp(), const_edge_4_viewer::construct_edge_4_viewer(), const_surface_data::construct_surface_data(), t_viewer_ele_grp_surface::dealloc_iso_surf_4_egrp_m(), t_viewer_ele_grp_surface::dealloc_iso_surf_4_sgrp_m(), t_viewer_ele_grp_surface::dealloc_n_iso_surf_4_ele_grp(), set_nodes_4_groups_viewer::s_set_nodes_4_groups_viewer(), set_nodes_4_viewer::s_set_nodes_4_viewer(), set_surf_connect_4_viewer::s_set_surf_connect_4_viewer(), const_mesh_information::set_local_element_info(), and set_surf_domain_id_viewer().
Referenced by para_const_kemoview_mesh::pickup_surface_mesh().
set_surf_domain_id_viewer()
subroutine, private const_kemoview_mesh::set_surf_domain_id_viewer (type(surface_data), intent(in) merged_surf, type(viewer_mesh_data), intent(inout) view_mesh) private
Definition at line 109 of file const_kemoview_mesh.f90.
References t_viewer_mesh::alloc_surf_type_viewer().
Referenced by const_surf_mesh_4_viewer().