CALYPSO: fem_analyzer_viz_surf Module Reference
fem_analyzer_viz_surf Module Reference
FEM top routines for surfacing.
Functions/Subroutines
subroutine fem_initialize_surface (ucd_step, init_d, sfcing)
subroutine fem_analyze_surface (i_step, ucd_step, time_d, sfcing)
Detailed Description
FEM top routines for surfacing.
      subroutine FEM_initialize_surface(ucd_step, init_d, sfcing)
        type(IO_step_param), intent(in) :: ucd_step
        type(time_data), intent(in) :: init_d
        type(FEM_mesh_field_4_surfacing), intent(inout) :: sfcing
      subroutine FEM_analyze_surface(i_step, ucd_step, time_d, sfcing)
        type(IO_step_param), intent(in) :: ucd_step
        type(field_IO_params), intent(in) :: ucd_param
        type(time_data), intent(inout) :: time_d
        type(ucd_data), intent(inout) :: ucd
Function/Subroutine Documentation
fem_analyze_surface()
subroutine fem_analyzer_viz_surf::fem_analyze_surface (integer (kind =kint), intent(in) i_step, type(io_step_param), intent(in) ucd_step, type(time_data), intent(inout) time_d, type(fem_mesh_field_4_surfacing), intent(inout) sfcing)
Definition at line 64 of file FEM_analyzer_viz_surf.f90.
References load_mesh_and_field_4_viz::set_field_data_4_viz().
Referenced by analyzer_psf::analyze_psf().
fem_initialize_surface()
subroutine fem_analyzer_viz_surf::fem_initialize_surface (type(io_step_param), intent(in) ucd_step, type(time_data), intent(in) init_d, type(fem_mesh_field_4_surfacing), intent(inout) sfcing)
Definition at line 42 of file FEM_analyzer_viz_surf.f90.
References load_mesh_and_field_4_viz::mesh_setup_4_viz().
Referenced by analyzer_psf::init_analyzer_psf().