CALYPSO: set_sph_1d_global_index Module Reference
set_sph_1d_global_index Module Reference
Set global indices for spherical harominics transform.
Functions/Subroutines
subroutine set_sph_1d_global_idx_rtp (m_folding, nphi, mdx_ispack, s3d_ranks, sph_dbc, stk_lc1d, sph_gl1d)
subroutine set_sph_1d_global_idx_rtm (m_folding, nphi, mtbl_fft_2_lgd, mdx_4_lgd, s3d_ranks, sph_dbc, stk_lc1d, sph_gl1d)
subroutine set_sph_1d_global_idx_rlm (jmax, jtbl_fsph, sph_gl1d)
subroutine set_sph_1d_global_idx_rj (jmax, jtbl_rj, sph_gl1d)
Detailed Description
Set global indices for spherical harominics transform.
      subroutine set_sph_1d_global_idx_rtp                            &
     &         (m_folding, nphi, mdx_ispack,                          &
     &          s3d_ranks, sph_dbc, stk_lc1d, sph_gl1d)
      subroutine set_sph_1d_global_idx_rtm                            &
     &         (m_folding, nphi, mtbl_fft_2_lgd, mdx_4_lgd,           &
     &          s3d_ranks, sph_dbc, stk_lc1d, sph_gl1d)
      subroutine set_sph_1d_global_idx_rlm(jmax, jtbl_fsph, sph_gl1d)
      subroutine set_sph_1d_global_idx_rj(jmax, jtbl_rj, sph_gl1d)
        type(spheric_global_rank), intent(in) :: s3d_ranks
        type(sph_local_default_BC), intent(in) :: sph_dbc
        type(sph_1d_index_stack), intent(in) :: stk_lc1d
        type(sph_1d_global_index), intent(inout) :: sph_gl1d
Function/Subroutine Documentation
set_sph_1d_global_idx_rj()
subroutine set_sph_1d_global_index::set_sph_1d_global_idx_rj (integer(kind = kint), intent(in) jmax, integer(kind = kint), dimension(0:jmax,3), intent(in) jtbl_rj, type(sph_1d_global_index), intent(inout) sph_gl1d)
Definition at line 197 of file set_sph_1d_global_index.f90.
Referenced by const_global_sph_grids_modes::s_const_global_sph_grids_modes().
set_sph_1d_global_idx_rlm()
subroutine set_sph_1d_global_index::set_sph_1d_global_idx_rlm (integer(kind = kint), intent(in) jmax, integer(kind = kint), dimension(0:jmax,3), intent(in) jtbl_fsph, type(sph_1d_global_index), intent(inout) sph_gl1d)
Definition at line 168 of file set_sph_1d_global_index.f90.
Referenced by const_global_sph_grids_modes::s_const_global_sph_grids_modes().
set_sph_1d_global_idx_rtm()
subroutine set_sph_1d_global_index::set_sph_1d_global_idx_rtm (integer(kind = kint), intent(in) m_folding, integer(kind = kint), intent(in) nphi, integer(kind = kint), dimension(0:nphi), intent(in) mtbl_fft_2_lgd, integer(kind = kint), dimension(0:nphi), intent(in) mdx_4_lgd, type(spheric_global_rank), intent(in) s3d_ranks, type(sph_local_default_bc), intent(in) sph_dbc, type(sph_1d_index_stack), intent(in) stk_lc1d, type(sph_1d_global_index), intent(inout) sph_gl1d)
Definition at line 105 of file set_sph_1d_global_index.f90.
Referenced by const_global_sph_grids_modes::s_const_global_sph_grids_modes().
set_sph_1d_global_idx_rtp()
subroutine set_sph_1d_global_index::set_sph_1d_global_idx_rtp (integer(kind = kint), intent(in) m_folding, integer(kind = kint), intent(in) nphi, integer(kind = kint), dimension(nphi), intent(in) mdx_ispack, type(spheric_global_rank), intent(in) s3d_ranks, type(sph_local_default_bc), intent(in) sph_dbc, type(sph_1d_index_stack), intent(in) stk_lc1d, type(sph_1d_global_index), intent(inout) sph_gl1d)
Definition at line 45 of file set_sph_1d_global_index.f90.
Referenced by const_global_sph_grids_modes::const_global_sph_fem_grid(), and const_global_sph_grids_modes::s_const_global_sph_grids_modes().