CALYPSO: cal_sph_exp_rotation Module Reference
cal_sph_exp_rotation Module Reference
Evaluate derivatives explicitly.
Functions/Subroutines
subroutine cal_sph_diff_pol_and_rot2 (kr_in, kr_out, nidx_rj, ar_1d_rj, g_sph_rj, d1nod_mat_fdm_2, d2nod_mat_fdm_2, is_fld, is_rot, nnod_rj, ntot_phys_rj, d_rj)
subroutine cal_sph_diff_poloidal2 (kr_in, kr_out, nidx_rj, d1nod_mat_fdm_2, is_fld, nnod_rj, ntot_phys_rj, d_rj)
subroutine cal_sph_nod_vect_rot2 (kr_in, kr_out, nidx_rj, ar_1d_rj, g_sph_rj, d1nod_mat_fdm_2, d2nod_mat_fdm_2, is_fld, is_rot, nnod_rj, ntot_phys_rj, d_rj)
subroutine cal_sph_nod_vect_w_div_rot2 (kr_in, kr_out, nidx_rj, ar_1d_rj, g_sph_rj, d1nod_mat_fdm_2, is_fld, is_rot, nnod_rj, ntot_phys_rj, d_rj)
subroutine cal_sph_nod_vect_div2 (kr_in, kr_out, nidx_rj, ar_1d_rj, g_sph_rj, d1nod_mat_fdm_2, is_fld, is_div, nnod_rj, ntot_phys_rj, d_rj)
subroutine cal_sph_nod_diffuse_by_rot2 (kr_in, kr_out, nidx_rj, ar_1d_rj, g_sph_rj, d1nod_mat_fdm_2, d2nod_mat_fdm_2, coef_d, is_fld, is_rot, nnod_rj, ntot_phys_rj, d_rj)
Detailed Description
Evaluate derivatives explicitly.
      subroutine cal_sph_diff_pol_and_rot2(kr_in, kr_out, nidx_rj,    &
     &          ar_1d_rj, g_sph_rj, d1nod_mat_fdm_2, d2nod_mat_fdm_2, &
     &          is_fld, is_rot, nnod_rj, ntot_phys_rj, d_rj)
        input:  d_rj(:,is_fld),   d_rj(:,is_fld+2)
        output: d_rj(:,is_fld+1), d_rj(:,is_rot:is_rot+2)
      subroutine cal_sph_diff_poloidal2(kr_in, kr_out, nidx_rj,       &
     &          d1nod_mat_fdm_2, is_fld, nnod_rj, ntot_phys_rj, d_rj)
        input:  d_rj(:,is_fld)
        output: d_rj(:,is_fld+1)
      subroutine cal_sph_nod_vect_rot2                                &
     &         (kr_in, kr_out, nidx_rj, ar_1d_rj, g_sph_rj,           &
     &          d1nod_mat_fdm_2, d2nod_mat_fdm_2, is_fld, is_rot,     &
     &          nnod_rj, ntot_phys_rj, d_rj)
        input:  d_rj(:,is_fld),   d_rj(:,is_fld+2)
        output: d_rj(:,is_rot:is_rot+2)
      subroutine cal_sph_nod_vect_w_div_rot2(kr_in, kr_out,           &
     &          nidx_rj, ar_1d_rj, g_sph_rj, d1nod_mat_fdm_2,         &
     &          is_fld, is_rot, nnod_rj, ntot_phys_rj, d_rj)
      subroutine cal_sph_nod_vect_div2(kr_in, kr_out,                 &
     &          nidx_rj, ar_1d_rj, g_sph_rj, d1nod_mat_fdm_2,         &
     &          is_fld, is_div, nnod_rj, ntot_phys_rj, d_rj)
      subroutine cal_sph_nod_diffuse_by_rot2(kr_in, kr_out, nidx_rj,  &
     &          ar_1d_rj, g_sph_rj, d1nod_mat_fdm_2, d2nod_mat_fdm_2, &
     &          coef_d, is_fld, is_rot, nnod_rj, ntot_phys_rj, d_rj)
Parameters
kr_in Radial ID for inner boundary
kr_out Radial ID for outer boundary
coef_d Coefficient for diffusion term
Parameters
is_fld Field address of input field
is_rot Field address of curl of field
is_div Field address of divergence of field
is_diffuse Field address for diffusion of field
Parameters
ntot_phys_rj Total number of components
d_rj Spectrum data
Function/Subroutine Documentation
cal_sph_diff_pol_and_rot2()
subroutine cal_sph_exp_rotation::cal_sph_diff_pol_and_rot2 (integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) kr_out, integer(kind = kint), dimension(2), intent(in) nidx_rj, real(kind = kreal), dimension(nidx_rj(1),3), intent(in) ar_1d_rj, real(kind = kreal), dimension(nidx_rj(2),13), intent(in) g_sph_rj, real(kind = kreal), dimension(nidx_rj(1),-1:1), intent(in) d1nod_mat_fdm_2, real(kind = kreal), dimension(nidx_rj(1),-1:1), intent(in) d2nod_mat_fdm_2, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_rot, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 65 of file cal_sph_exp_rotation.f90.
Referenced by const_sph_radial_grad::const_grad_bp_and_current(), and const_sph_radial_grad::const_grad_vp_and_vorticity().
cal_sph_diff_poloidal2()
subroutine cal_sph_exp_rotation::cal_sph_diff_poloidal2 (integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) kr_out, integer(kind = kint), dimension(2), intent(in) nidx_rj, real(kind = kreal), dimension(nidx_rj(1),-1:1), intent(in) d1nod_mat_fdm_2, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 119 of file cal_sph_exp_rotation.f90.
Referenced by const_sph_radial_grad::const_grad_poloidal_magne(), and const_sph_radial_grad::const_grad_poloidal_moment().
cal_sph_nod_diffuse_by_rot2()
subroutine cal_sph_exp_rotation::cal_sph_nod_diffuse_by_rot2 (integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) kr_out, integer(kind = kint), dimension(2), intent(in) nidx_rj, real(kind = kreal), dimension(nidx_rj(1),3), intent(in) ar_1d_rj, real(kind = kreal), dimension(nidx_rj(2),13), intent(in) g_sph_rj, real(kind = kreal), dimension(nidx_rj(1),-1:1), intent(in) d1nod_mat_fdm_2, real(kind = kreal), dimension(nidx_rj(1),-1:1), intent(in) d2nod_mat_fdm_2, real(kind = kreal), intent(in) coef_d, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_rot, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 297 of file cal_sph_exp_rotation.f90.
Referenced by const_sph_rotation::const_sph_mag_diffuse_by_j(), and const_sph_rotation::const_sph_viscous_by_vort2().
cal_sph_nod_vect_div2()
subroutine cal_sph_exp_rotation::cal_sph_nod_vect_div2 (integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) kr_out, integer(kind = kint), dimension(2), intent(in) nidx_rj, real(kind = kreal), dimension(nidx_rj(1),3), intent(in) ar_1d_rj, real(kind = kreal), dimension(nidx_rj(2),13), intent(in) g_sph_rj, real(kind = kreal), dimension(nidx_rj(1),-1:1), intent(in) d1nod_mat_fdm_2, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_div, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 254 of file cal_sph_exp_rotation.f90.
References m_constants::half.
Referenced by const_sph_divergence::const_sph_div_force(), and const_sph_divergence::const_sph_scalar_advect().
cal_sph_nod_vect_rot2()
subroutine cal_sph_exp_rotation::cal_sph_nod_vect_rot2 (integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) kr_out, integer(kind = kint), dimension(2), intent(in) nidx_rj, real(kind = kreal), dimension(nidx_rj(1),3), intent(in) ar_1d_rj, real(kind = kreal), dimension(nidx_rj(2),13), intent(in) g_sph_rj, real(kind = kreal), dimension(nidx_rj(1),-1:1), intent(in) d1nod_mat_fdm_2, real(kind = kreal), dimension(nidx_rj(1),-1:1), intent(in) d2nod_mat_fdm_2, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_rot, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 157 of file cal_sph_exp_rotation.f90.
Referenced by const_sph_rotation::const_sph_current(), const_sph_rotation::const_sph_rotation_no_bc(), and const_sph_rotation::const_sph_vorticity().
cal_sph_nod_vect_w_div_rot2()
subroutine cal_sph_exp_rotation::cal_sph_nod_vect_w_div_rot2 (integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) kr_out, integer(kind = kint), dimension(2), intent(in) nidx_rj, real(kind = kreal), dimension(nidx_rj(1),3), intent(in) ar_1d_rj, real(kind = kreal), dimension(nidx_rj(2),13), intent(in) g_sph_rj, real(kind = kreal), dimension(nidx_rj(1),-1:1), intent(in) d1nod_mat_fdm_2, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_rot, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 207 of file cal_sph_exp_rotation.f90.
Referenced by const_sph_rotation::const_sph_force_rot2(), and const_sph_rotation::const_sph_rotation_uxb().