CALYPSO: copy_rj_phys_data_4_io Module Reference
copy_rj_phys_data_4_io Module Reference
Copy between field data and IO data.
Functions/Subroutines
subroutine copy_rj_phys_name_to_io (num_fld, rj_fld, fld_IO)
subroutine copy_rj_phys_data_to_io (num_fld, rj_fld, fld_IO)
subroutine copy_rj_phys_name_from_io (fld_IO, rj_fld)
subroutine copy_rj_phys_data_from_io (fld_IO, rj_fld)
subroutine set_rj_phys_data_from_io (fld_IO, rj_fld)
subroutine copy_each_sph_solenoid_to_io (rj_fld, fld_IO, i_fld, j_IO)
subroutine copy_each_sph_vector_to_io (rj_fld, fld_IO, i_fld, j_IO)
subroutine copy_each_sph_field_to_io (rj_fld, fld_IO, i_fld, j_IO)
subroutine, private copy_each_sph_solenoid_from_io (fld_IO, rj_fld, i_fld, j_IO)
subroutine copy_each_sph_vector_from_io (fld_IO, rj_fld, i_fld, j_IO)
subroutine copy_each_sph_field_from_io (fld_IO, rj_fld, i_fld, j_IO)
Detailed Description
Copy between field data and IO data.
      subroutine copy_rj_phys_name_to_IO(num_fld, rj_fld, fld_IO)
      subroutine copy_rj_phys_data_to_IO(num_fld, rj_fld, fld_IO)
      subroutine copy_rj_phys_name_from_IO(fld_IO, rj_fld)
      subroutine copy_rj_phys_data_from_IO(fld_IO, rj_fld)
      subroutine set_rj_phys_data_from_IO(fld_IO, rj_fld)
      subroutine copy_each_sph_solenoid_to_IO                         &
     &         (rj_fld, fld_IO, i_fld, j_IO)
      subroutine copy_each_sph_vector_to_IO                           &
     &         (rj_fld, fld_IO, i_fld, j_IO)
      subroutine copy_each_sph_field_to_IO                            &
     &         (rj_fld, fld_IO, i_fld, j_IO)
      subroutine copy_each_sph_solenoid_from_IO                       &
     &         (fld_IO, rj_fld, i_fld, j_IO)
      subroutine copy_each_sph_vector_from_IO                         &
     &         (fld_IO, rj_fld, i_fld, j_IO)
      subroutine copy_each_sph_field_from_IO                          &
     &         (fld_IO, rj_fld, i_fld, j_IO)
Function/Subroutine Documentation
copy_each_sph_field_from_io()
subroutine copy_rj_phys_data_4_io::copy_each_sph_field_from_io (type(field_io), intent(in) fld_IO, type(phys_data), intent(inout) rj_fld, integer(kind = kint), intent(in) i_fld, integer(kind = kint), intent(in) j_IO)
Definition at line 301 of file copy_rj_phys_data_4_IO.f90.
Referenced by copy_rj_phys_data_from_io(), set_rj_phys_data_from_io(), and set_sph_restart_io::set_sph_restart_from_io().
copy_each_sph_field_to_io()
subroutine copy_rj_phys_data_4_io::copy_each_sph_field_to_io (type(phys_data), intent(in) rj_fld, type(field_io), intent(inout) fld_IO, integer(kind = kint), intent(in) i_fld, integer(kind = kint), intent(in) j_IO)
Definition at line 230 of file copy_rj_phys_data_4_IO.f90.
Referenced by copy_rj_phys_data_to_io(), and set_sph_restart_io::set_sph_restart_data_to_io().
copy_each_sph_solenoid_from_io()
subroutine, private copy_rj_phys_data_4_io::copy_each_sph_solenoid_from_io (type(field_io), intent(in) fld_IO, type(phys_data), intent(inout) rj_fld, integer(kind = kint), intent(in) i_fld, integer(kind = kint), intent(in) j_IO) private
Definition at line 256 of file copy_rj_phys_data_4_IO.f90.
Referenced by set_rj_phys_data_from_io().
copy_each_sph_solenoid_to_io()
subroutine copy_rj_phys_data_4_io::copy_each_sph_solenoid_to_io (type(phys_data), intent(in) rj_fld, type(field_io), intent(inout) fld_IO, integer(kind = kint), intent(in) i_fld, integer(kind = kint), intent(in) j_IO)
Definition at line 185 of file copy_rj_phys_data_4_IO.f90.
copy_each_sph_vector_from_io()
subroutine copy_rj_phys_data_4_io::copy_each_sph_vector_from_io (type(field_io), intent(in) fld_IO, type(phys_data), intent(inout) rj_fld, integer(kind = kint), intent(in) i_fld, integer(kind = kint), intent(in) j_IO)
Definition at line 278 of file copy_rj_phys_data_4_IO.f90.
Referenced by copy_rj_phys_data_from_io(), set_rj_phys_data_from_io(), and set_sph_restart_io::set_sph_restart_from_io().
copy_each_sph_vector_to_io()
subroutine copy_rj_phys_data_4_io::copy_each_sph_vector_to_io (type(phys_data), intent(in) rj_fld, type(field_io), intent(inout) fld_IO, integer(kind = kint), intent(in) i_fld, integer(kind = kint), intent(in) j_IO)
Definition at line 207 of file copy_rj_phys_data_4_IO.f90.
Referenced by copy_rj_phys_data_to_io(), and set_sph_restart_io::set_sph_restart_data_to_io().
copy_rj_phys_data_from_io()
subroutine copy_rj_phys_data_4_io::copy_rj_phys_data_from_io (type(field_io), intent(in) fld_IO, type(phys_data), intent(inout) rj_fld)
Definition at line 135 of file copy_rj_phys_data_4_IO.f90.
References copy_each_sph_field_from_io(), and copy_each_sph_vector_from_io().
Referenced by new_sph_restart::load_old_fmt_sph_data(), and new_sph_restart::load_org_sph_data().
copy_rj_phys_data_to_io()
subroutine copy_rj_phys_data_4_io::copy_rj_phys_data_to_io (integer(kind = kint), intent(in) num_fld, type(phys_data), intent(in) rj_fld, type(field_io), intent(inout) fld_IO)
Definition at line 75 of file copy_rj_phys_data_4_IO.f90.
References copy_each_sph_field_to_io(), copy_each_sph_vector_to_io(), and m_phys_constants::n_vector.
Referenced by new_sph_restart::const_assembled_sph_data(), and sph_mhd_rst_io_control::output_spectr_4_snap().
copy_rj_phys_name_from_io()
subroutine copy_rj_phys_data_4_io::copy_rj_phys_name_from_io (type(field_io), intent(in) fld_IO, type(phys_data), intent(inout) rj_fld)
Definition at line 99 of file copy_rj_phys_data_4_IO.f90.
Referenced by analyzer_rayleigh_cvt_sph::init_cvt_rayleigh_sph(), and new_sph_restart::load_field_name_assemble_sph().
copy_rj_phys_name_to_io()
subroutine copy_rj_phys_data_4_io::copy_rj_phys_name_to_io (integer(kind = kint), intent(in) num_fld, type(phys_data), intent(in) rj_fld, type(field_io), intent(inout) fld_IO)
Definition at line 51 of file copy_rj_phys_data_4_IO.f90.
References t_field_data_io::alloc_phys_name_io().
Referenced by new_sph_restart::const_assembled_sph_data(), and sph_mhd_rst_io_control::output_spectr_4_snap().
set_rj_phys_data_from_io()
subroutine copy_rj_phys_data_4_io::set_rj_phys_data_from_io (type(field_io), intent(in) fld_IO, type(phys_data), intent(inout) rj_fld)
Definition at line 156 of file copy_rj_phys_data_4_IO.f90.
References copy_each_sph_field_from_io(), copy_each_sph_solenoid_from_io(), and copy_each_sph_vector_from_io().
Referenced by sph_mhd_rst_io_control::read_alloc_sph_spectr().