CALYPSO: copy_sph_1d_global_index Module Reference
copy_sph_1d_global_index Module Reference
Copy global spherical harmonics indices in local array.
Functions/Subroutines
subroutine copy_sph_1d_gl_idx_rtp (s3d_radius, sph_gl1d, sph_rtp)
subroutine copy_sph_1d_gl_idx_rtm (s3d_radius, sph_gl1d, sph_rtm)
subroutine copy_sph_1d_gl_idx_rlm (s3d_radius, sph_gl1d, sph_rlm)
subroutine copy_sph_1d_gl_idx_rj (s3d_radius, sph_gl1d, sph_rj)
subroutine add_center_mode_rj (id_rank, sph_gl1d, sph_rj)
Detailed Description
Copy global spherical harmonics indices in local array.
      subroutine copy_sph_1d_gl_idx_rtp                               &
     &         (s3d_radius, sph_gl1d, sph_rtp)
        type(spheric_global_radius), intent(in) :: s3d_radius
        type(sph_1d_global_index), intent(in) :: sph_gl1d
        type(sph_rtp_grid), intent(inout) :: sph_rtp
      subroutine copy_sph_1d_gl_idx_rtm                               &
     &         (s3d_radius, sph_gl1d, sph_rtm)
        type(spheric_global_radius), intent(in) :: s3d_radius
        type(sph_1d_global_index), intent(in) :: sph_gl1d
        type(sph_rtm_grid), intent(inout) :: sph_rtm
      subroutine copy_sph_1d_gl_idx_rlm                               &
     &         (s3d_radius, sph_gl1d, sph_rlm)
        type(spheric_global_radius), intent(in) :: s3d_radius
        type(sph_1d_global_index), intent(in) :: sph_gl1d
        type(sph_rlm_grid), intent(inout) :: sph_rlm
      subroutine copy_sph_1d_gl_idx_rj                                &
     &         (s3d_radius, sph_gl1d, sph_rj)
        type(spheric_global_radius), intent(in) :: s3d_radius
        type(sph_1d_global_index), intent(in) :: sph_gl1d
        type(sph_rj_grid), intent(inout) :: sph_rj
      subroutine add_center_mode_rj(id_rank, sph_gl1d, sph_rj)
        type(sph_1d_global_index), intent(in) :: sph_gl1d
        type(sph_rj_grid), intent(inout) :: sph_rj
Function/Subroutine Documentation
add_center_mode_rj()
subroutine copy_sph_1d_global_index::add_center_mode_rj (integer, intent(in) id_rank, type(sph_1d_global_index), intent(in) sph_gl1d, type(sph_rj_grid), intent(inout) sph_rj)
Definition at line 208 of file copy_sph_1d_global_index.f90.
References m_constants::izero.
Referenced by set_comm_table_rtp_rj::const_sph_rj_modes().
copy_sph_1d_gl_idx_rj()
subroutine copy_sph_1d_global_index::copy_sph_1d_gl_idx_rj (type(spheric_global_radius), intent(in) s3d_radius, type(sph_1d_global_index), intent(in) sph_gl1d, type(sph_rj_grid), intent(inout) sph_rj)
Definition at line 156 of file copy_sph_1d_global_index.f90.
Referenced by set_comm_table_rtp_rj::const_sph_rj_modes().
copy_sph_1d_gl_idx_rlm()
subroutine copy_sph_1d_global_index::copy_sph_1d_gl_idx_rlm (type(spheric_global_radius), intent(in) s3d_radius, type(sph_1d_global_index), intent(in) sph_gl1d, type(sph_rlm_grid), intent(inout) sph_rlm)
Definition at line 126 of file copy_sph_1d_global_index.f90.
Referenced by gen_sph_grids_modes::const_sph_rlm_modes().
copy_sph_1d_gl_idx_rtm()
subroutine copy_sph_1d_global_index::copy_sph_1d_gl_idx_rtm (type(spheric_global_radius), intent(in) s3d_radius, type(sph_1d_global_index), intent(in) sph_gl1d, type(sph_rtm_grid), intent(inout) sph_rtm)
Definition at line 92 of file copy_sph_1d_global_index.f90.
Referenced by gen_sph_grids_modes::const_sph_rtm_grids().
copy_sph_1d_gl_idx_rtp()
subroutine copy_sph_1d_global_index::copy_sph_1d_gl_idx_rtp (type(spheric_global_radius), intent(in) s3d_radius, type(sph_1d_global_index), intent(in) sph_gl1d, type(sph_rtp_grid), intent(inout) sph_rtp)
Definition at line 58 of file copy_sph_1d_global_index.f90.
Referenced by set_comm_table_rtp_rj::const_sph_rtp_grids().