CALYPSO: field_file_io_b Module Reference
field_file_io_b Module Reference
Output merged binary field file using MPI-IO.
Functions/Subroutines
subroutine write_step_field_file_b (file_name, id_rank, t_IO, fld_IO, ierr)
subroutine read_step_field_file_b (file_name, id_rank, t_IO, fld_IO, ierr)
subroutine read_and_allocate_step_field_b (file_name, id_rank, t_IO, fld_IO, ierr)
subroutine read_and_allocate_step_head_b (file_name, id_rank, t_IO, fld_IO, ierr)
subroutine, private read_and_allocate_step_b (bbuf, t_IO, fld_IO)
Variables
integer(kind=kint), parameter, private id_read_fld = 21
integer(kind=kint), parameter, private id_write_fld = 22
type(binary_io_buffer), private bbuf_fld
Detailed Description
Output merged binary field file using MPI-IO.
      subroutine write_step_field_file_b                              &
     &         (file_name, id_rank, t_IO, fld_IO, ierr)
        type(time_data), intent(in) :: t_IO
        type(field_IO), intent(in) :: fld_IO
      subroutine read_step_field_file_b                               &
     &         (file_name, id_rank, t_IO, fld_IO, ierr)
      subroutine read_and_allocate_step_field_b                       &
     &         (file_name, id_rank, t_IO, fld_IO, ierr)
      subroutine read_and_allocate_step_head_b                        &
     &         (file_name, id_rank, t_IO, fld_IO, ierr)
        type(time_data), intent(inout) :: t_IO
        type(field_IO), intent(inout) :: fld_IO
Function/Subroutine Documentation
read_and_allocate_step_b()
subroutine, private field_file_io_b::read_and_allocate_step_b (type(binary_io_buffer), intent(inout) bbuf, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO) private
Definition at line 194 of file field_file_IO_b.f90.
References t_field_data_io::alloc_phys_name_io(), t_field_data_io::cal_istack_phys_comp_io(), transfer_to_long_integers::cast_long(), binary_io::read_mul_integer_b(), and field_data_io_b::read_step_data_b().
Referenced by read_and_allocate_step_field_b(), and read_and_allocate_step_head_b().
read_and_allocate_step_field_b()
subroutine field_file_io_b::read_and_allocate_step_field_b (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 130 of file field_file_IO_b.f90.
References t_field_data_io::alloc_phys_data_io(), bbuf_fld, transfer_to_long_integers::cast_long(), binary_io::close_binary_file(), m_machine_parameter::i_debug, id_read_fld, binary_io::open_read_binary_file(), read_and_allocate_step_b(), and field_data_io_b::read_field_data_b().
Referenced by field_io_select::sel_read_alloc_step_field_file().
read_and_allocate_step_head_b()
subroutine field_file_io_b::read_and_allocate_step_head_b (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 166 of file field_file_IO_b.f90.
References bbuf_fld, binary_io::close_binary_file(), m_machine_parameter::i_debug, id_read_fld, binary_io::open_read_binary_file(), and read_and_allocate_step_b().
Referenced by field_io_select::sel_read_alloc_field_head().
read_step_field_file_b()
subroutine field_file_io_b::read_step_field_file_b (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 89 of file field_file_IO_b.f90.
References bbuf_fld, transfer_to_long_integers::cast_long(), binary_io::close_binary_file(), m_machine_parameter::i_debug, id_read_fld, binary_io::open_read_binary_file(), field_data_io_b::read_field_data_b(), binary_io::read_mul_integer_b(), and field_data_io_b::read_step_data_b().
Referenced by field_io_select::sel_read_step_field_file().
write_step_field_file_b()
subroutine field_file_io_b::write_step_field_file_b (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(time_data), intent(in) t_IO, type(field_io), intent(in) fld_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 52 of file field_file_IO_b.f90.
References bbuf_fld, transfer_to_long_integers::cast_long(), binary_io::close_binary_file(), m_machine_parameter::i_debug, id_write_fld, binary_io::open_write_binary_file(), field_data_io_b::write_field_data_b(), and field_data_io_b::write_step_data_b().
Referenced by field_io_select::sel_write_step_field_file().
Variable Documentation
bbuf_fld
type(binary_io_buffer), private field_file_io_b::bbuf_fld private
Definition at line 41 of file field_file_IO_b.f90.
Referenced by read_and_allocate_step_field_b(), read_and_allocate_step_head_b(), read_step_field_file_b(), and write_step_field_file_b().
id_read_fld
integer(kind = kint), parameter, private field_file_io_b::id_read_fld = 21 private
Definition at line 39 of file field_file_IO_b.f90.
Referenced by read_and_allocate_step_field_b(), read_and_allocate_step_head_b(), and read_step_field_file_b().
id_write_fld
integer(kind = kint), parameter, private field_file_io_b::id_write_fld = 22 private
Definition at line 40 of file field_file_IO_b.f90.
Referenced by write_step_field_file_b().