CALYPSO: t_isosurface Module Reference
t_isosurface Module Reference
Structure for isosurfacing.
Data Types
type isosurface_module
Functions/Subroutines
subroutine isosurf_initialize (fem, nod_fld, iso_ctls, iso)
subroutine isosurf_visualize (istep_iso, time_d, fem, nod_fld, iso)
subroutine dealloc_iso_field_type (iso)
subroutine, private alloc_iso_field_type (iso)
Detailed Description
Structure for isosurfacing.
      subroutine ISOSURF_initialize(fem, nod_fld, iso_ctls, iso)
        type(mesh_data), intent(in) :: fem
        type(isosurf_controls), intent(inout) :: iso_ctls
        type(isosurface_module), intent(inout) :: iso
        type(phys_data), intent(in) :: nod_fld
      subroutine ISOSURF_visualize                                    &
     &         (istep_iso, time_d, fem, nod_fld, iso)
        type(time_data), intent(in) :: time_d
        type(mesh_data), intent(in) :: fem
        type(phys_data), intent(in) :: nod_fld
        type(isosurface_module), intent(inout) :: iso
      subroutine dealloc_iso_field_type(iso)
Function/Subroutine Documentation
alloc_iso_field_type()
subroutine, private t_isosurface::alloc_iso_field_type (type(isosurface_module), intent(inout) iso) private
Definition at line 205 of file t_isosurface.f90.
References m_field_file_format::iflag_sgl_ucd.
Referenced by isosurf_initialize().
dealloc_iso_field_type()
subroutine t_isosurface::dealloc_iso_field_type (type(isosurface_module), intent(inout) iso)
Definition at line 186 of file t_isosurface.f90.
References set_psf_iso_control::dealloc_psf_field_name().
isosurf_initialize()
subroutine t_isosurface::isosurf_initialize (type(mesh_data), intent(in) fem, type(phys_data), intent(in) nod_fld, type(isosurf_controls), intent(inout) iso_ctls, type(isosurface_module), intent(inout) iso)
Definition at line 83 of file t_isosurface.f90.
References alloc_iso_field_type(), set_psf_iso_control::set_iso_control(), and search_ele_list_for_psf::set_search_mesh_list_4_psf().
Referenced by t_viz_sections::init_visualize_surface().
isosurf_visualize()
subroutine t_isosurface::isosurf_visualize (integer(kind = kint), intent(in) istep_iso, type(time_data), intent(in) time_d, type(mesh_data), intent(in) fem, type(phys_data), intent(in) nod_fld, type(isosurface_module), intent(inout) iso)
Definition at line 128 of file t_isosurface.f90.
References set_fields_for_psf::alloc_psf_field_data(), set_fields_for_psf::dealloc_psf_field_data(), find_node_and_patch_psf::dealloc_psf_node_and_patch(), m_work_time::end_elapsed_time(), m_elapsed_labels_4_viz::iflag_iso_time, m_elapsed_labels_4_viz::ist_elapsed_iso, output_4_psf::output_isosurface(), set_const_4_sections::set_const_4_isosurfaces(), set_fields_for_psf::set_field_4_iso(), find_node_and_patch_psf::set_node_and_patch_iso(), and m_work_time::start_elapsed_time().
Referenced by t_viz_sections::visualize_surface().