CALYPSO: ucd_io_select Module Reference
ucd_io_select Module Reference
UCD data IO selector.
Functions/Subroutines
subroutine set_ucd_file_define (plt, ucd_param)
subroutine sel_write_ucd_file (id_rank, istep_ucd, ucd_param, t_IO, ucd)
subroutine sel_write_udt_file (id_rank, istep_ucd, ucd_param, t_IO, ucd)
subroutine sel_write_grd_file (id_rank, ucd_param, ucd)
subroutine sel_read_udt_param (id_rank, istep_ucd, ucd_param, t_IO, ucd)
subroutine sel_read_alloc_udt_file (id_rank, istep_ucd, ucd_param, t_IO, ucd)
subroutine sel_read_alloc_ucd_file (id_rank, istep_ucd, ucd_param, t_IO, ucd)
subroutine sel_read_udt_file (id_rank, istep_ucd, ucd_param, t_IO, ucd)
subroutine sel_read_ucd_file (id_rank, istep_ucd, ucd_param, t_IO, ucd)
Detailed Description
UCD data IO selector.
      subroutine set_ucd_file_define(plt, ucd_param)
        type(platform_data_control), intent(in) :: plt
        type(field_IO_params), intent(inout) :: ucd_param
      subroutine sel_write_ucd_file                                   &
     &         (id_rank, istep_ucd, ucd_param, t_IO, ucd)
      subroutine sel_write_udt_file                                   &
     &         (id_rank, istep_ucd, ucd_param, t_IO, ucd)
      subroutine sel_write_grd_file(id_rank, ucd_param, ucd)
      subroutine sel_read_udt_param                                   &
     &         (id_rank, istep_ucd, ucd_param, t_IO, ucd)
      subroutine sel_read_alloc_udt_file                              &
     &         (id_rank, istep_ucd, ucd_param, t_IO, ucd)
      subroutine sel_read_alloc_ucd_file                              &
     &         (id_rank, istep_ucd, ucd_param, t_IO, ucd)
      subroutine sel_read_udt_file                                    &
     &         (id_rank, istep_ucd, ucd_param, t_IO, ucd)
      subroutine sel_read_ucd_file                                    &
     &         (id_rank, istep_ucd, ucd_param, t_IO, ucd)
        type(field_IO_params), intent(in) :: ucd_param
        type(ucd_data), intent(inout) :: ucd
Parameters
id_rank process ID
istep_ucd step number for output
Function/Subroutine Documentation
sel_read_alloc_ucd_file()
subroutine ucd_io_select::sel_read_alloc_ucd_file (integer, intent(in) id_rank, integer(kind = kint), intent(in) istep_ucd, type(field_io_params), intent(in) ucd_param, type(time_data), intent(inout) t_IO, type(ucd_data), intent(inout) ucd)
Definition at line 350 of file ucd_IO_select.F90.
References gz_read_psf_binary_file::gz_read_alloc_iso_bin_file(), gz_read_psf_binary_file::gz_read_alloc_psf_bin_file(), gz_read_psf_binary_file::gz_read_alloc_psf_bin_grid(), m_field_file_format::iflag_ucd, m_field_file_format::iflag_ucd_bin, m_field_file_format::iflag_ucd_bin_gz, m_field_file_format::iflag_ucd_gz, m_field_file_format::iflag_udt, m_field_file_format::iflag_udt_bin, m_field_file_format::iflag_udt_bin_gz, m_field_file_format::iflag_udt_gz, m_field_file_format::iflag_vtd, m_field_file_format::iflag_vtd_gz, m_field_file_format::iflag_vtk, m_field_file_format::iflag_vtk_gz, udt_file_io::read_alloc_grd_file(), gz_udt_file_io::read_alloc_gz_ucd_file(), gz_udt_file_io::read_alloc_gz_ucd_grd(), gz_udt_file_io::read_alloc_gz_udt_file(), gz_vtk_file_io::read_alloc_gz_vtk_file(), gz_vtk_file_io::read_alloc_gz_vtk_grid(), gz_vtk_file_io::read_alloc_gz_vtk_phys(), read_psf_binary_file::read_alloc_iso_bin_file(), read_psf_binary_file::read_alloc_psf_bin_file(), read_psf_binary_file::read_alloc_psf_bin_grid(), udt_file_io::read_alloc_ucd_file(), udt_file_io::read_alloc_udt_file(), vtk_file_io::read_alloc_vtk_file(), vtk_file_io::read_alloc_vtk_grid(), vtk_file_io::read_alloc_vtk_phys(), set_ucd_file_names::set_parallel_grd_file_name(), and set_ucd_file_names::set_parallel_ucd_file_name().
Referenced by psf_file_to_vtk().
sel_read_alloc_udt_file()
subroutine ucd_io_select::sel_read_alloc_udt_file (integer, intent(in) id_rank, integer(kind = kint), intent(in) istep_ucd, type(field_io_params), intent(in) ucd_param, type(time_data), intent(inout) t_IO, type(ucd_data), intent(inout) ucd)
Definition at line 293 of file ucd_IO_select.F90.
References gz_read_psf_binary_file::gz_read_alloc_psf_bin_file(), gz_ucd_field_file_io_b::gz_read_alloc_ucd_2_fld_file_b(), gz_ucd_field_file_io::gz_read_alloc_ucd_2_ld_file(), m_field_file_format::iflag_bin, m_field_file_format::iflag_bin_gz, m_field_file_format::iflag_fld_gz, m_field_file_format::iflag_udt, m_field_file_format::iflag_udt_bin, m_field_file_format::iflag_udt_bin_gz, m_field_file_format::iflag_udt_gz, m_field_file_format::iflag_vtd, m_field_file_format::iflag_vtd_gz, gz_udt_file_io::read_alloc_gz_udt_file(), gz_vtk_file_io::read_alloc_gz_vtk_phys(), read_psf_binary_file::read_alloc_psf_bin_file(), ucd_field_file_io::read_alloc_ucd_2_fld_file(), ucd_field_file_io_b::read_alloc_ucd_2_fld_file_b(), udt_file_io::read_alloc_udt_file(), vtk_file_io::read_alloc_vtk_phys(), and set_ucd_file_names::set_parallel_ucd_file_name().
Referenced by parallel_ucd_io_select::sel_read_alloc_para_udt_file().
sel_read_ucd_file()
subroutine ucd_io_select::sel_read_ucd_file (integer, intent(in) id_rank, integer(kind = kint), intent(in) istep_ucd, type(field_io_params), intent(in) ucd_param, type(time_data), intent(inout) t_IO, type(ucd_data), intent(inout) ucd)
Definition at line 475 of file ucd_IO_select.F90.
References gz_read_psf_binary_file::gz_read_iso_bin_file(), gz_read_psf_binary_file::gz_read_psf_bin_file(), gz_read_psf_binary_file::gz_read_psf_bin_grid(), m_field_file_format::iflag_ucd, m_field_file_format::iflag_ucd_bin, m_field_file_format::iflag_ucd_bin_gz, m_field_file_format::iflag_ucd_gz, m_field_file_format::iflag_udt, m_field_file_format::iflag_udt_bin, m_field_file_format::iflag_udt_bin_gz, m_field_file_format::iflag_udt_gz, m_field_file_format::iflag_vtd, m_field_file_format::iflag_vtd_gz, m_field_file_format::iflag_vtk, m_field_file_format::iflag_vtk_gz, udt_file_io::read_grd_file(), gz_udt_file_io::read_gz_ucd_file(), gz_udt_file_io::read_gz_ucd_grd(), gz_udt_file_io::read_gz_udt_file(), gz_vtk_file_io::read_gz_vtk_file(), gz_vtk_file_io::read_gz_vtk_grid(), gz_vtk_file_io::read_gz_vtk_phys(), read_psf_binary_file::read_iso_bin_file(), read_psf_binary_file::read_psf_bin_file(), read_psf_binary_file::read_psf_bin_grid(), udt_file_io::read_ucd_file(), udt_file_io::read_udt_file(), vtk_file_io::read_vtk_file(), vtk_file_io::read_vtk_grid(), vtk_file_io::read_vtk_phys(), set_ucd_file_names::set_parallel_grd_file_name(), and set_ucd_file_names::set_parallel_ucd_file_name().
sel_read_udt_file()
subroutine ucd_io_select::sel_read_udt_file (integer, intent(in) id_rank, integer(kind = kint), intent(in) istep_ucd, type(field_io_params), intent(in) ucd_param, type(time_data), intent(inout) t_IO, type(ucd_data), intent(inout) ucd)
Definition at line 420 of file ucd_IO_select.F90.
References gz_read_psf_binary_file::gz_read_psf_bin_file(), gz_ucd_field_file_io::gz_read_ucd_2_fld_file(), gz_ucd_field_file_io_b::gz_read_ucd_2_fld_file_b(), m_field_file_format::iflag_bin, m_field_file_format::iflag_bin_gz, m_field_file_format::iflag_fld_gz, m_field_file_format::iflag_udt, m_field_file_format::iflag_udt_bin, m_field_file_format::iflag_udt_bin_gz, m_field_file_format::iflag_udt_gz, m_field_file_format::iflag_vtd, m_field_file_format::iflag_vtd_gz, gz_udt_file_io::read_gz_udt_file(), gz_vtk_file_io::read_gz_vtk_phys(), read_psf_binary_file::read_psf_bin_file(), ucd_field_file_io::read_ucd_2_fld_file(), ucd_field_file_io_b::read_ucd_2_fld_file_b(), udt_file_io::read_udt_file(), vtk_file_io::read_vtk_phys(), and set_ucd_file_names::set_parallel_ucd_file_name().
Referenced by parallel_ucd_io_select::sel_read_parallel_udt_file().
sel_read_udt_param()
subroutine ucd_io_select::sel_read_udt_param (integer, intent(in) id_rank, integer(kind = kint), intent(in) istep_ucd, type(field_io_params), intent(in) ucd_param, type(time_data), intent(inout) t_IO, type(ucd_data), intent(inout) ucd)
Definition at line 236 of file ucd_IO_select.F90.
References gz_read_psf_binary_file::gz_read_alloc_psf_bin_file(), gz_ucd_field_file_io_b::gz_read_alloc_ucd_2_fld_file_b(), gz_ucd_field_file_io::gz_read_alloc_ucd_2_ld_file(), m_field_file_format::iflag_bin, m_field_file_format::iflag_bin_gz, m_field_file_format::iflag_fld_gz, m_field_file_format::iflag_udt, m_field_file_format::iflag_udt_bin, m_field_file_format::iflag_udt_bin_gz, m_field_file_format::iflag_udt_gz, m_field_file_format::iflag_vtd, m_field_file_format::iflag_vtd_gz, gz_udt_file_io::read_alloc_gz_udt_params(), gz_vtk_file_io::read_alloc_gz_vtk_phys(), read_psf_binary_file::read_alloc_psf_bin_file(), ucd_field_file_io::read_alloc_ucd_2_fld_file(), ucd_field_file_io_b::read_alloc_ucd_2_fld_header_b(), udt_file_io::read_alloc_udt_params(), vtk_file_io::read_alloc_vtk_phys(), and set_ucd_file_names::set_parallel_ucd_file_name().
Referenced by load_mesh_and_field_4_viz::mesh_setup_4_viz().
sel_write_grd_file()
subroutine ucd_io_select::sel_write_grd_file (integer, intent(in) id_rank, type(field_io_params), intent(in) ucd_param, type(ucd_data), intent(in) ucd)
Definition at line 199 of file ucd_IO_select.F90.
References m_field_file_format::iflag_ascii, m_field_file_format::iflag_bin, m_field_file_format::iflag_bin_gz, m_field_file_format::iflag_fld_gz, m_field_file_format::iflag_udt, m_field_file_format::iflag_udt_gz, m_field_file_format::iflag_vtd, m_field_file_format::iflag_vtd_gz, set_ucd_file_names::set_parallel_grd_file_name(), udt_file_io::write_grd_file(), gz_udt_file_io::write_gz_grd_file(), gz_vtk_file_io::write_gz_vtk_grid(), and vtk_file_io::write_vtk_grid().
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_mesh().
sel_write_ucd_file()
subroutine ucd_io_select::sel_write_ucd_file (integer, intent(in) id_rank, integer(kind = kint), intent(in) istep_ucd, type(field_io_params), intent(in) ucd_param, type(time_data), intent(in) t_IO, type(ucd_data), intent(in) ucd)
Definition at line 94 of file ucd_IO_select.F90.
References gz_ucd_field_file_io::gz_write_ucd_2_fld_file(), gz_ucd_field_file_io_b::gz_write_ucd_2_fld_file_b(), m_field_file_format::iflag_bin, m_field_file_format::iflag_bin_gz, m_field_file_format::iflag_fld_gz, m_field_file_format::iflag_ucd, m_field_file_format::iflag_ucd_gz, m_field_file_format::iflag_udt, m_field_file_format::iflag_udt_gz, m_field_file_format::iflag_vtd, m_field_file_format::iflag_vtd_gz, m_field_file_format::iflag_vtk, m_field_file_format::iflag_vtk_gz, set_ucd_file_names::set_parallel_ucd_file_name(), gz_udt_file_io::write_gz_ucd_file(), gz_udt_file_io::write_gz_udt_file(), gz_vtk_file_io::write_gz_vtk_file(), gz_vtk_file_io::write_gz_vtk_phys(), ucd_field_file_io::write_ucd_2_fld_file(), ucd_field_file_io_b::write_ucd_2_fld_file_b(), udt_file_io::write_ucd_file(), udt_file_io::write_udt_file(), vtk_file_io::write_vtk_file(), and vtk_file_io::write_vtk_phys().
Referenced by psf_file_to_vtk(), and parallel_ucd_io_select::sel_write_parallel_ucd_file().
sel_write_udt_file()
subroutine ucd_io_select::sel_write_udt_file (integer, intent(in) id_rank, integer(kind = kint), intent(in) istep_ucd, type(field_io_params), intent(in) ucd_param, type(time_data), intent(in) t_IO, type(ucd_data), intent(in) ucd)
Definition at line 146 of file ucd_IO_select.F90.
References gz_ucd_field_file_io::gz_write_ucd_2_fld_file(), gz_ucd_field_file_io_b::gz_write_ucd_2_fld_file_b(), m_field_file_format::iflag_bin, m_field_file_format::iflag_bin_gz, m_field_file_format::iflag_fld_gz, m_field_file_format::iflag_ucd, m_field_file_format::iflag_ucd_gz, m_field_file_format::iflag_udt, m_field_file_format::iflag_udt_gz, m_field_file_format::iflag_vtd, m_field_file_format::iflag_vtd_gz, m_field_file_format::iflag_vtk, m_field_file_format::iflag_vtk_gz, set_ucd_file_names::set_parallel_ucd_file_name(), gz_udt_file_io::write_gz_ucd_file(), gz_udt_file_io::write_gz_udt_file(), gz_vtk_file_io::write_gz_vtk_file(), gz_vtk_file_io::write_gz_vtk_phys(), ucd_field_file_io::write_ucd_2_fld_file(), ucd_field_file_io_b::write_ucd_2_fld_file_b(), udt_file_io::write_ucd_file(), udt_file_io::write_udt_file(), vtk_file_io::write_vtk_file(), and vtk_file_io::write_vtk_phys().
set_ucd_file_define()
subroutine ucd_io_select::set_ucd_file_define (type(platform_data_control), intent(in) plt, type(field_io_params), intent(inout) ucd_param)
Definition at line 72 of file ucd_IO_select.F90.
References m_field_file_format::choose_ucd_file_format().
Referenced by load_mesh_and_field_4_viz::set_control_params_4_viz().