CALYPSO: /home/takumi kera/calypso/src/programs/mesh_utilities/main_check_sph_grids.f90 File Reference
main_check_sph_grids.f90 File Reference
program check_sph_grids
Functions/Subroutines
program check_sph_grids
Main program generate spherical harmonics indices.
Detailed Description
program check_sph_grids
Author
H. Matsui
Date
Programmed by H. Matsui in Feb., 2015
Definition in file main_check_sph_grids.f90.
Function/Subroutine Documentation
check_sph_grids()
program check_sph_grids
Main program generate spherical harmonics indices.
Definition at line 9 of file main_check_sph_grids.f90.
References analyzer_check_sph_grids::analyze_check_sph_grids(), calypso_mpi::calypso_mpi_finalize(), calypso_mpi::calypso_mpi_init(), and analyzer_check_sph_grids::init_check_sph_grids().