CALYPSO: t_multi_fftw_wrapper Module Reference
t_multi_fftw_wrapper Module Reference
Fourier transform using FFTW Ver.3.
Data Types
type working_mul_fftw
structure for working data for FFTW
Functions/Subroutines
subroutine init_fftw_mul_type (Nsmp, Nstacksmp, Nfft, WK)
subroutine finalize_fftw_mul_type (Nsmp, WK)
subroutine verify_wk_fftw_mul_type (Nsmp, Nstacksmp, Nfft, WK)
subroutine fftw_mul_forward_type (Nsmp, Nstacksmp, Ncomp, Nfft, X, WK)
subroutine fftw_mul_backward_type (Nsmp, Nstacksmp, Ncomp, Nfft, X, WK)
subroutine, private alloc_mul_fftw_plan_t (Nplan, Ncomp, Nfft, WK)
subroutine, private dealloc_mul_fftw_plan_t (WK)
Detailed Description
Fourier transform using FFTW Ver.3.
 ------------------------------------------------------------------
      subroutine init_FFTW_type(Ncomp, Nfft, WK)
      subroutine finalize_FFTW_type(Ncomp, WK)
      subroutine verify_wk_FFTW_type(Ncomp, Nfft, WK)
      subroutine init_FFTW_mul_type(Nsmp, Nstacksmp, Nfft, WK)
      subroutine finalize_FFTW_mul_type(Nsmp, WK)
      subroutine verify_wk_FFTW_mul_type(Nsmp, Nstacksmp, Nfft, WK)
   wrapper subroutine for initierize FFT by FFTW
 ------------------------------------------------------------------
      subroutine FFTW_mul_forward_type(Nsmp, Nstacksmp, Ncomp, Nfft,  &
     &          X, WK)
 ------------------------------------------------------------------
 wrapper subroutine for forward Fourier transform by FFTW3
   a_{k} = \frac{2}{Nfft} \sum_{j=0}^{Nfft-1} x_{j} \cos (\frac{2\pi j k}{Nfft})
   b_{k} = \frac{2}{Nfft} \sum_{j=0}^{Nfft-1} x_{j} \cos (\frac{2\pi j k}{Nfft})
   a_{0} = \frac{1}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
    K = Nfft/2....
   a_{k} = \frac{1}{Nfft} \sum_{j=0}^{Nfft-1} x_{j} \cos (\frac{2\pi j k}{Nfft})
 ------------------------------------------------------------------
      subroutine FFTW_mul_backward_type(Nsmp, Nstacksmp, Ncomp, Nfft, &
     &          X, WK)
 ------------------------------------------------------------------
 wrapper subroutine for backward Fourier transform by FFTW3
   x_{k} = a_{0} + (-1)^{j} a_{Nfft/2} + sum_{k=1}^{Nfft/2-1}
          (a_{k} \cos(2\pijk/Nfft) + b_{k} \sin(2\pijk/Nfft))
 ------------------------------------------------------------------
       i = 1:     a_{0}
       i = 2:     a_{Nfft/2}
       i = 3:     a_{1}
       i = 4:     b_{1}
       ...
       i = 2*k+1: a_{k}
       i = 2*k+2: b_{k}
       ...
       i = Nfft-1:   a_{Nfft/2-1}
       i = Nfft:     b_{Nfft/2-1}
 ------------------------------------------------------------------
Parameters
Nsmp Number of SMP processors
Nstacksmp(0:Nsmp) End number for each SMP process
Ncomp Number of components for Fourier transforms
Nfft Data length for eadh FFT
X(Ncomp,Nfft) Data for Fourier transform
WK Work structure for FFTW3
Function/Subroutine Documentation
alloc_mul_fftw_plan_t()
subroutine, private t_multi_fftw_wrapper::alloc_mul_fftw_plan_t (integer(kind = kint), intent(in) Nplan, integer(kind = kint), intent(in) Ncomp, integer(kind = kint), intent(in) Nfft, type(working_mul_fftw), intent(inout) WK) private
Definition at line 194 of file t_multi_FFTW_wrapper.f90.
Referenced by init_fftw_mul_type().
dealloc_mul_fftw_plan_t()
subroutine, private t_multi_fftw_wrapper::dealloc_mul_fftw_plan_t (type(working_mul_fftw), intent(inout) WK) private
Definition at line 213 of file t_multi_FFTW_wrapper.f90.
Referenced by finalize_fftw_mul_type().
fftw_mul_backward_type()
subroutine t_multi_fftw_wrapper::fftw_mul_backward_type (integer(kind = kint), intent(in) Nsmp, integer(kind = kint), dimension(0:nsmp), intent(in) Nstacksmp, integer(kind = kint), intent(in) Ncomp, integer(kind = kint), intent(in) Nfft, real(kind = kreal), dimension(ncomp,nfft), intent(inout) X, type(working_mul_fftw), intent(inout) WK)
Definition at line 176 of file t_multi_FFTW_wrapper.f90.
References fftw3_multi_wrapper::fftw_mul_backward_smp().
Referenced by t_fft_selector::backward_fft_select(), and test_fftw3().
fftw_mul_forward_type()
subroutine t_multi_fftw_wrapper::fftw_mul_forward_type (integer(kind = kint), intent(in) Nsmp, integer(kind = kint), dimension(0:nsmp), intent(in) Nstacksmp, integer(kind = kint), intent(in) Ncomp, integer(kind = kint), intent(in) Nfft, real(kind = kreal), dimension(ncomp, nfft), intent(inout) X, type(working_mul_fftw), intent(inout) WK)
Definition at line 159 of file t_multi_FFTW_wrapper.f90.
References fftw3_multi_wrapper::fftw_mul_forward_smp().
Referenced by t_fft_selector::forward_fft_select(), and test_fftw3().
finalize_fftw_mul_type()
subroutine t_multi_fftw_wrapper::finalize_fftw_mul_type (integer(kind = kint), intent(in) Nsmp, type(working_mul_fftw), intent(inout) WK)
Definition at line 121 of file t_multi_FFTW_wrapper.f90.
References dealloc_mul_fftw_plan_t(), and fftw3_multi_wrapper::destroy_fftw_mul_smp().
Referenced by t_fft_selector::finalize_fft_sel_t(), and verify_wk_fftw_mul_type().
init_fftw_mul_type()
subroutine t_multi_fftw_wrapper::init_fftw_mul_type (integer(kind = kint), intent(in) Nsmp, integer(kind = kint), dimension(0:nsmp), intent(in) Nstacksmp, integer(kind = kint), intent(in) Nfft, type(working_mul_fftw), intent(inout) WK)
Definition at line 104 of file t_multi_FFTW_wrapper.f90.
References alloc_mul_fftw_plan_t(), and fftw3_multi_wrapper::init_4_fftw_mul_smp().
Referenced by t_fft_selector::initialize_fft_select(), test_fftw3(), and verify_wk_fftw_mul_type().
verify_wk_fftw_mul_type()
subroutine t_multi_fftw_wrapper::verify_wk_fftw_mul_type (integer(kind = kint), intent(in) Nsmp, integer(kind = kint), dimension(0:nsmp), intent(in) Nstacksmp, integer(kind = kint), intent(in) Nfft, type(working_mul_fftw), intent(inout) WK)
Definition at line 136 of file t_multi_FFTW_wrapper.f90.
References finalize_fftw_mul_type(), and init_fftw_mul_type().
Referenced by t_fft_selector::verify_fft_select().