CALYPSO: legendre_bwd_trans_sym_spin Module Reference
legendre_bwd_trans_sym_spin Module Reference
backward Legendre transform considering symmetry
Functions/Subroutines
subroutine leg_bwd_trans_vector_sym_spin (ncomp, nvector, sph_rlm, sph_rtm, comm_rlm, comm_rtm, idx_trns, asin_theta_1d_rtm, g_sph_rlm, n_WR, n_WS, WR, WS, WK_l_sml)
subroutine leg_bwd_trans_scalar_sym_spin (ncomp, nvector, nscalar, sph_rlm, sph_rtm, comm_rlm, comm_rtm, idx_trns, n_WR, n_WS, WR, WS, WK_l_sml)
Detailed Description
backward Legendre transform considering symmetry
      subroutine leg_bwd_trans_vector_sym_spin(ncomp, nvector,        &
     &          sph_rlm, sph_rtm, comm_rlm, comm_rtm, idx_trns,       &
     &          asin_theta_1d_rtm, g_sph_rlm,                         &
     &          n_WR, n_WS, WR, WS, WK_l_sml)
          Input:  vr_rtm   (Order: radius,theta,phi)
          Output: sp_rlm   (Order: poloidal,diff_poloidal,toroidal)
      subroutine leg_bwd_trans_scalar_sym_spin                        &
     &         (ncomp, nvector, nscalar,                              &
     &          sph_rlm, sph_rtm, comm_rlm, comm_rtm, idx_trns,       &
     &          n_WR, n_WS, WR, WS, WK_l_sml)
          Input:  vr_rtm
          Output: sp_rlm
        type(sph_rlm_grid), intent(in) :: sph_rlm
        type(sph_rtm_grid), intent(in) :: sph_rtm
        type(sph_comm_tbl), intent(in) :: comm_rlm, comm_rtm
        type(index_4_sph_trans), intent(in) :: idx_trns
        type(leg_trns_sym_mul_work), intent(inout) :: WK_l_sml
Parameters
ncomp Total number of components for spherical transform
nvector Number of vector for spherical transform
nscalar Number of scalar (including tensor components) for spherical transform
Function/Subroutine Documentation
leg_bwd_trans_scalar_sym_spin()
subroutine legendre_bwd_trans_sym_spin::leg_bwd_trans_scalar_sym_spin (integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_comm_tbl), intent(in) comm_rlm, type(sph_comm_tbl), intent(in) comm_rtm, type(index_4_sph_trans), intent(in) idx_trns, integer(kind = kint), intent(in) n_WR, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_wr), intent(inout) WR, real (kind=kreal), dimension(n_ws), intent(inout) WS, type(leg_trns_sym_mul_work), intent(inout) WK_l_sml)
Definition at line 227 of file legendre_bwd_trans_sym_spin.f90.
References cal_vr_rtm_by_vecprod::cal_vr_rtm_scalar_equator(), cal_vr_rtm_by_vecprod::cal_vr_rtm_scalar_symmetry(), m_machine_parameter::np_smp, set_sp_rlm_for_leg_vecprod::set_sp_rlm_scalar_equator(), and set_sp_rlm_for_leg_vecprod::set_sp_rlm_scalar_symmetry().
Referenced by legendre_transform_spin::leg_backward_trans_sym_spin().
leg_bwd_trans_vector_sym_spin()
subroutine legendre_bwd_trans_sym_spin::leg_bwd_trans_vector_sym_spin (integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_comm_tbl), intent(in) comm_rlm, type(sph_comm_tbl), intent(in) comm_rtm, type(index_4_sph_trans), intent(in) idx_trns, real(kind = kreal), dimension(sph_rtm%nidx_rtm(2)), intent(in) asin_theta_1d_rtm, real(kind = kreal), dimension(sph_rlm%nidx_rlm(2),17), intent(in) g_sph_rlm, integer(kind = kint), intent(in) n_WR, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_wr), intent(inout) WR, real (kind=kreal), dimension(n_ws), intent(inout) WS, type(leg_trns_sym_mul_work), intent(inout) WK_l_sml)
Definition at line 55 of file legendre_bwd_trans_sym_spin.f90.
References cal_vr_rtm_by_vecprod::cal_vr_rtm_dydphi_equator(), cal_vr_rtm_by_vecprod::cal_vr_rtm_dydphi_symmetry(), cal_vr_rtm_by_vecprod::cal_vr_rtm_dydtheta_equator(), cal_vr_rtm_by_vecprod::cal_vr_rtm_dydtheta_symmetry(), m_machine_parameter::np_smp, set_sp_rlm_for_leg_vecprod::set_sp_rlm_vector_equator(), and set_sp_rlm_for_leg_vecprod::set_sp_rlm_vector_symmetry().
Referenced by legendre_transform_spin::leg_backward_trans_sym_spin().