CALYPSO: sph_transforms_snapshot Module Reference
sph_transforms_snapshot Module Reference
Perform spherical harmonics transform for MHD dynamo model.
Functions/Subroutines
subroutine sph_back_trans_snapshot_mhd (sph, comms_sph, trans_p, rj_fld, trns_bwd, WK_leg, WK_FFTs)
subroutine sph_forward_trans_snapshot_mhd (sph, comms_sph, trans_p, trns_fwd, WK_leg, WK_FFTs, rj_fld)
Detailed Description
Perform spherical harmonics transform for MHD dynamo model.
      subroutine sph_back_trans_snapshot_MHD(sph, comms_sph, trans_p, &
     &          rj_fld, trns_bwd, WK_leg, WK_FFTs)
        type(sph_grids), intent(in) :: sph
        type(sph_comm_tables), intent(in) :: comms_sph
        type(parameters_4_sph_trans), intent(in) :: trans_p
        type(phys_data), intent(inout) :: rj_fld
        type(spherical_transform_data), intent(inout) :: trns_bwd
        type(legendre_trns_works), intent(inout) :: WK_leg
        type(work_for_FFTs), intent(inout) :: WK_FFTs
      subroutine sph_forward_trans_snapshot_MHD                       &
     &         (sph, comms_sph, trans_p, trns_fwd, WK_leg, WK_FFTs,   &
     &          rj_fld)
        type(sph_grids), intent(in) :: sph
        type(sph_comm_tables), intent(in) :: comms_sph
        type(spherical_transform_data), intent(in) :: trns_fwd
        type(phys_data), intent(inout) :: rj_fld
        type(legendre_trns_works), intent(inout) :: WK_leg
        type(work_for_FFTs), intent(inout) :: WK_FFTs
Function/Subroutine Documentation
sph_back_trans_snapshot_mhd()
subroutine sph_transforms_snapshot::sph_back_trans_snapshot_mhd (type(sph_grids), intent(in) sph, type(sph_comm_tables), intent(in) comms_sph, type(parameters_4_sph_trans), intent(in) trans_p, type(phys_data), intent(inout) rj_fld, type(spherical_transform_data), intent(inout) trns_bwd, type(legendre_trns_works), intent(inout) WK_leg, type(work_for_ffts), intent(inout) WK_FFTs)
Definition at line 62 of file sph_transforms_snapshot.f90.
References spherical_srs_n::check_calypso_sph_comm_buf_n(), set_address_sph_trans_mhd::mhd_spectr_to_sendbuf_wpole(), t_sph_transforms::sph_b_trans_w_poles(), and m_solver_sr::sr_r1.
Referenced by lead_fields_4_sph_mhd::cal_sph_enegy_fluxes(), lead_fields_4_sph_mhd::gradients_of_vectors_sph(), and lead_fields_4_sph_mhd::lead_fields_by_sph_trans().
sph_forward_trans_snapshot_mhd()
subroutine sph_transforms_snapshot::sph_forward_trans_snapshot_mhd (type(sph_grids), intent(in) sph, type(sph_comm_tables), intent(in) comms_sph, type(parameters_4_sph_trans), intent(in) trans_p, type(spherical_transform_data), intent(in) trns_fwd, type(legendre_trns_works), intent(inout) WK_leg, type(work_for_ffts), intent(inout) WK_FFTs, type(phys_data), intent(inout) rj_fld)
Definition at line 103 of file sph_transforms_snapshot.f90.
References spherical_srs_n::check_calypso_sph_comm_buf_n(), set_address_sph_trans_mhd::mhd_spectr_from_recvbuf(), t_sph_transforms::sph_forward_transforms(), and m_solver_sr::sr_r1.
Referenced by lead_fields_4_sph_mhd::enegy_fluxes_4_sph_mhd(), and lead_fields_4_sph_mhd::gradients_of_vectors_sph().