CALYPSO: set_surface_list_for_psf Module Reference
set_surface_list_for_psf Module Reference
Functions/Subroutines
subroutine allocate_work_4_mark_surf_psf (numsurf)
subroutine deallocate_work_4_mark_surf_psf
subroutine mark_surface_list_4_psf (numele, numsurf, isf_4_ele, ele_search)
subroutine count_surf_list_4_psf (isurf_smp_stack, surf_search)
subroutine set_surface_list_4_psf (isurf_smp_stack, surf_search)
Variables
integer(kind=kint), dimension(:), allocatable, private imark_surf
integer(kind=kint), dimension(:,:), allocatable imark_surf_smp
integer(kind=kint), dimension(:), allocatable, private nsurf_search_smp
Function/Subroutine Documentation
allocate_work_4_mark_surf_psf()
subroutine set_surface_list_for_psf::allocate_work_4_mark_surf_psf (integer(kind = kint), intent(in) numsurf)
Definition at line 35 of file set_surface_list_for_psf.f90.
References imark_surf, imark_surf_smp, m_machine_parameter::np_smp, and nsurf_search_smp.
Referenced by search_ele_list_for_psf::set_searched_surface_list_4_psf().
count_surf_list_4_psf()
subroutine set_surface_list_for_psf::count_surf_list_4_psf (integer(kind=kint), dimension(0:np_smp), intent(in) isurf_smp_stack, type(sect_search_list), intent(inout) surf_search)
Definition at line 122 of file set_surface_list_for_psf.f90.
References imark_surf, and nsurf_search_smp.
Referenced by search_ele_list_for_psf::set_searched_surface_list_4_psf().
deallocate_work_4_mark_surf_psf()
subroutine set_surface_list_for_psf::deallocate_work_4_mark_surf_psf
Definition at line 54 of file set_surface_list_for_psf.f90.
References imark_surf, imark_surf_smp, and nsurf_search_smp.
Referenced by search_ele_list_for_psf::set_searched_surface_list_4_psf().
mark_surface_list_4_psf()
subroutine set_surface_list_for_psf::mark_surface_list_4_psf (integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) numsurf, integer(kind = kint), dimension(numele,nsurf_4_ele), intent(in) isf_4_ele, type(sect_search_list), intent(inout) ele_search)
Definition at line 63 of file set_surface_list_for_psf.f90.
References imark_surf, imark_surf_smp, and m_machine_parameter::np_smp.
Referenced by search_ele_list_for_psf::set_searched_surface_list_4_psf().
set_surface_list_4_psf()
subroutine set_surface_list_for_psf::set_surface_list_4_psf (integer(kind = kint), dimension(0:np_smp), intent(in) isurf_smp_stack, type(sect_search_list), intent(inout) surf_search)
Definition at line 155 of file set_surface_list_for_psf.f90.
References imark_surf.
Referenced by search_ele_list_for_psf::set_searched_surface_list_4_psf().
Variable Documentation
imark_surf
integer(kind = kint), dimension(:), allocatable, private set_surface_list_for_psf::imark_surf private
Definition at line 22 of file set_surface_list_for_psf.f90.
Referenced by allocate_work_4_mark_surf_psf(), count_surf_list_4_psf(), deallocate_work_4_mark_surf_psf(), mark_surface_list_4_psf(), and set_surface_list_4_psf().
imark_surf_smp
integer(kind = kint), dimension(:,:), allocatable set_surface_list_for_psf::imark_surf_smp
Definition at line 23 of file set_surface_list_for_psf.f90.
Referenced by allocate_work_4_mark_surf_psf(), deallocate_work_4_mark_surf_psf(), and mark_surface_list_4_psf().
nsurf_search_smp
integer(kind = kint), dimension(:), allocatable, private set_surface_list_for_psf::nsurf_search_smp private
Definition at line 25 of file set_surface_list_for_psf.f90.
Referenced by allocate_work_4_mark_surf_psf(), count_surf_list_4_psf(), and deallocate_work_4_mark_surf_psf().