CALYPSO: t_solver_sr_int Module Reference
t_solver_sr_int Module Reference
Work area for data communications.
Data Types
type send_recv_int_buffer
Structure of communication buffer for integer.
Functions/Subroutines
subroutine resize_iwork_sr_t (NPE_SEND, NPE_RECV, NTOT_SEND, NTOT_RECV, SR_sig, SR_i)
subroutine resize_iwork_itp_sr (NPE_SEND, NPE_RECV, NTOT_RECV, SR_sig, SR_i)
subroutine, private resize_isend_sr (NTOT_SEND, SR_i)
subroutine, private resize_irecv_sr (NTOT_RECV, SR_i)
Detailed Description
Work area for data communications.
      subroutine resize_iwork_SR_t(NPE_SEND, NPE_RECV,                &
     &          NTOT_SEND, NTOT_RECV, SR_sig, SR_i)
        type(send_recv_status), intent(inout) :: SR_sig
        type(send_recv_real_buffer), intent(inout) :: SR_r
        type(send_recv_int_buffer), intent(inout) :: SR_i
      subroutine resize_iwork_itp_SR                                  &
     &         (NPE_SEND, NPE_RECV, NTOT_RECV, SR_sig, SR_i)
        type(send_recv_status), intent(inout) :: SR_sig
        type(send_recv_real_buffer), intent(inout) :: SR_r
        type(send_recv_int_buffer), intent(inout) :: SR_i
Parameters
NB Number of components
NTOT_SEND Total number of data points for export
NTOT_RECV Total number of data points for import
NPE_SEND Number of processses to receive
NPE_RECV Number of processses to send
Parameters
N_SHIFT number of shifting of the reversed import table
ITEM_IMPORT import table
REV_IMPORT reversed import table
Function/Subroutine Documentation
resize_irecv_sr()
subroutine, private t_solver_sr_int::resize_irecv_sr (integer(kind=kint), intent(in) NTOT_RECV, type(send_recv_int_buffer), intent(inout) SR_i) private
Definition at line 121 of file t_solver_SR_int.f90.
Referenced by resize_iwork_itp_sr(), and resize_iwork_sr_t().
resize_isend_sr()
subroutine, private t_solver_sr_int::resize_isend_sr (integer(kind=kint), intent(in) NTOT_SEND, type(send_recv_int_buffer), intent(inout) SR_i) private
Definition at line 101 of file t_solver_SR_int.f90.
Referenced by resize_iwork_sr_t().
resize_iwork_itp_sr()
subroutine t_solver_sr_int::resize_iwork_itp_sr (integer(kind = kint), intent(in) NPE_SEND, integer(kind = kint), intent(in) NPE_RECV, integer(kind = kint), intent(in) NTOT_RECV, type(send_recv_status), intent(inout) SR_sig, type(send_recv_int_buffer), intent(inout) SR_i)
Definition at line 84 of file t_solver_SR_int.f90.
References resize_irecv_sr(), and t_solver_sr::resize_sr_flag().
resize_iwork_sr_t()
subroutine t_solver_sr_int::resize_iwork_sr_t (integer(kind = kint), intent(in) NPE_SEND, integer(kind = kint), intent(in) NPE_RECV, integer(kind = kint), intent(in) NTOT_SEND, integer(kind = kint), intent(in) NTOT_RECV, type(send_recv_status), intent(inout) SR_sig, type(send_recv_int_buffer), intent(inout) SR_i)
Definition at line 66 of file t_solver_SR_int.f90.
References resize_irecv_sr(), resize_isend_sr(), and t_solver_sr::resize_sr_flag().
Referenced by calypso_sr_int::calypso_send_recv_int(), and solver_sr_int::solver_send_recv_i().