CALYPSO: mpi_integer_list_io Module Reference
mpi_integer_list_io Module Reference
Data IO routines for spectrum data.
Functions/Subroutines
subroutine mpi_read_ele_connect (IO_param, nele, nnod_4_ele, id_global, ie)
subroutine mpi_read_element_type (IO_param, ncolumn, num, int_dat)
subroutine mpi_read_int_list (IO_param, nele, ncomp, ivect)
subroutine mpi_write_ele_connect (IO_param, nele, nnod_4_ele, id_global, ie)
subroutine mpi_write_element_type (IO_param, ncolumn, num, int_dat)
subroutine mpi_write_int_list (IO_param, nele, ncomp, ivect)
Detailed Description
Data IO routines for spectrum data.
      subroutine mpi_read_ele_connect                                 &
     &         (IO_param, nele, nnod_4_ele, id_global, ie)
      subroutine mpi_read_element_type                                &
     &         (IO_param, ncolumn, num, int_dat)
      subroutine mpi_read_int_list(IO_param, nele, ncomp, ivect)
      subroutine mpi_write_ele_connect                                &
     &         (IO_param, nele, nnod_4_ele, id_global, ie)
      subroutine mpi_write_element_type                               &
     &         (IO_param, ncolumn, num, int_dat)
      subroutine mpi_write_int_list(IO_param, nele, ncomp, ivect)
Function/Subroutine Documentation
mpi_read_ele_connect()
subroutine mpi_integer_list_io::mpi_read_ele_connect (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) nele, integer(kind=kint), intent(in) nnod_4_ele, integer(kind=kint_gl), dimension(nele), intent(inout) id_global, integer(kind=kint), dimension(nele, nnod_4_ele), intent(inout) ie)
Definition at line 39 of file MPI_integer_list_IO.f90.
References data_io_to_textline::len_int8_and_mul_int_textline(), data_io_to_textline::len_multi_int_textline(), mpi_ascii_data_io::mpi_skip_read(), and data_io_to_textline::read_int8_and_mul_int_textline().
Referenced by mpi_element_connect_io::mpi_read_element_info(), and mpi_spherical_model_io::mpi_read_gl_nodes_sph().
mpi_read_element_type()
subroutine mpi_integer_list_io::mpi_read_element_type (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) ncolumn, integer(kind=kint), intent(in) num, integer(kind=kint), dimension(num), intent(inout) int_dat)
Definition at line 92 of file MPI_integer_list_IO.f90.
References data_io_to_textline::len_multi_6digit_line(), data_io_to_textline::len_multi_int_textline(), mpi_ascii_data_io::mpi_skip_read(), and data_io_to_textline::read_mul_6digit_int_line().
Referenced by mpi_element_connect_io::mpi_read_element_info().
mpi_read_int_list()
subroutine mpi_integer_list_io::mpi_read_int_list (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) nele, integer(kind=kint), intent(in) ncomp, integer(kind=kint), dimension(nele, ncomp), intent(inout) ivect)
Definition at line 154 of file MPI_integer_list_IO.f90.
References data_io_to_textline::len_multi_int_textline(), mpi_ascii_data_io::mpi_skip_read(), and data_io_to_textline::read_multi_int_textline().
Referenced by mpi_element_connect_io::mpi_read_edge_4_element(), and mpi_element_connect_io::mpi_read_surface_4_element().
mpi_write_ele_connect()
subroutine mpi_integer_list_io::mpi_write_ele_connect (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) nele, integer(kind=kint), intent(in) nnod_4_ele, integer(kind=kint_gl), dimension(nele), intent(in) id_global, integer(kind=kint), dimension(nele,nnod_4_ele), intent(in) ie)
Definition at line 205 of file MPI_integer_list_IO.f90.
References data_io_to_textline::int8_and_mul_int_textline(), data_io_to_textline::len_int8_and_mul_int_textline(), and mpi_ascii_data_io::mpi_write_stack_over_domain().
Referenced by mpi_element_connect_io::mpi_write_element_info(), and mpi_spherical_model_io::mpi_write_gl_nodes_sph().
mpi_write_element_type()
subroutine mpi_integer_list_io::mpi_write_element_type (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) ncolumn, integer(kind=kint), intent(in) num, integer(kind=kint), dimension(num), intent(in) int_dat)
Definition at line 253 of file MPI_integer_list_IO.f90.
References data_io_to_textline::len_multi_6digit_line(), mpi_ascii_data_io::mpi_write_stack_over_domain(), and data_io_to_textline::mul_6digit_int_line().
Referenced by mpi_element_connect_io::mpi_write_element_info().
mpi_write_int_list()
subroutine mpi_integer_list_io::mpi_write_int_list (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) nele, integer(kind=kint), intent(in) ncomp, integer(kind=kint), dimension(nele,ncomp), intent(in) ivect)
Definition at line 301 of file MPI_integer_list_IO.f90.
References data_io_to_textline::len_multi_int_textline(), mpi_ascii_data_io::mpi_write_stack_over_domain(), and data_io_to_textline::multi_int_textline().
Referenced by mpi_element_connect_io::mpi_write_edge_4_element(), and mpi_element_connect_io::mpi_write_surface_4_element().