CALYPSO: zlib_convert_text Module Reference
zlib_convert_text Module Reference
Output merged binary field file using MPI-IO.
Functions/Subroutines
subroutine defleate_characters (ilength, chara_dat, zbuf)
subroutine infleate_characters (ilength, text, zbuf)
subroutine infleate_1word (ilength, word, zbuf)
subroutine infleate_skip_header (ilength, zbuf)
Detailed Description
Output merged binary field file using MPI-IO.
      subroutine defleate_characters(ilength, chara_dat, zbuf)
      subroutine infleate_characters(ilength, text, zbuf)
      subroutine infleate_1word(ilength, word, zbuf)
      subroutine infleate_skip_header(ilength, zbuf)
        type(buffer_4_gzip), intent(inout) :: zbuf
Function/Subroutine Documentation
defleate_characters()
subroutine zlib_convert_text::defleate_characters (integer, intent(in) ilength, character(len=ilength), intent(in) chara_dat, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 35 of file zlib_convert_text.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), and gzip_defleate::gzip_defleat_char_once().
Referenced by gz_mpi_ascii_data_io::gz_mpi_write_characters(), gz_mpi_ascii_data_io::gz_mpi_write_charahead(), gz_field_data_mpi_io::gz_write_fld_header_mpi(), and gz_vtk_file_mpi_io::gz_write_vtk_header_mpi().
infleate_1word()
subroutine zlib_convert_text::infleate_1word (integer, intent(inout) ilength, character(len=kchara), intent(inout) word, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 84 of file zlib_convert_text.f90.
References t_buffer_4_gzip::alloc_textbuffer_for_zlib(), t_buffer_4_gzip::dealloc_textbuffer_for_zlib(), t_buffer_4_gzip::dealloc_zip_buffer(), gzip_infleate::gzip_infleat_char_once(), m_precision::kchara, field_data_io::read_each_field_name_buffer(), and t_buffer_4_gzip::unlink_pointer_for_zlib_buffer().
Referenced by gz_field_data_mpi_io::gz_read_fld_1word_mpi().
infleate_characters()
subroutine zlib_convert_text::infleate_characters (integer, intent(in) ilength, character(len=ilength), intent(inout) text, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 60 of file zlib_convert_text.f90.
References t_buffer_4_gzip::dealloc_zip_buffer(), gzip_infleate::gzip_infleat_char_once(), and t_buffer_4_gzip::unlink_pointer_for_zlib_buffer().
Referenced by gz_mpi_ascii_data_io::gz_mpi_read_characters(), gz_mpi_ascii_data_io::gz_mpi_read_charahead(), and gz_field_data_mpi_io::gz_read_fld_charhead_mpi().
infleate_skip_header()
subroutine zlib_convert_text::infleate_skip_header (integer, intent(in) ilength, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 129 of file zlib_convert_text.f90.
References t_buffer_4_gzip::alloc_textbuffer_for_zlib(), t_buffer_4_gzip::dealloc_textbuffer_for_zlib(), t_buffer_4_gzip::dealloc_zip_buffer(), gzip_infleate::gzip_infleat_char_once(), and t_buffer_4_gzip::unlink_pointer_for_zlib_buffer().
Referenced by gz_mpi_ascii_data_io::gz_mpi_skip_header().