CALYPSO: calypso_mpi_int8 Module Reference
calypso_mpi_int8 Module Reference
MPI communication routines for 8-byte integer in Calypso.
Functions/Subroutines
subroutine calypso_mpi_bcast_one_int8 (buffer, root)
subroutine calypso_mpi_bcast_int8 (buffer, count, root)
subroutine calypso_mpi_reduce_one_int8 (i8_local, i8_global, operation, destination)
subroutine calypso_mpi_reduce_int8 (i8_local, i8_global, count, operation, destination)
subroutine calypso_mpi_allreduce_one_int8 (i8_local, i8_global, operation)
subroutine calypso_mpi_allreduce_int8 (i8_local, i8_global, count, operation)
subroutine calypso_mpi_allgather_one_int8 (i8sendbuf, i8recvbuf)
subroutine calypso_mpi_allgather_int8 (i8sendbuf, n_send, i8recvbuf, n_recv)
subroutine calypso_mpi_seek_write_int8 (id_mpi_file, ioffset, num, i8_vector, sta_IO)
subroutine calypso_mpi_seek_read_int8 (id_mpi_file, ioffset, num, i8_vector, sta_IO)
Detailed Description
MPI communication routines for 8-byte integer in Calypso.
      subroutine calypso_mpi_bcast_one_int8(buffer, root)
        integer, intent(in) :: root
        integer(kind = kint_gl), intent(inout) :: buffer
      subroutine calypso_mpi_bcast_int8(buffer, count, root)
        integer, intent(in) :: root
        integer(kind = kint_gl), intent(in) :: count
        integer(kind = kint_gl), intent(inout) :: buffer(count)
      subroutine calypso_mpi_reduce_one_int8                          &
     &         (i8_local, i8_global, operation, destination)
        integer, intent(in) :: operation, destination
        integer(kind = kint_gl), intent(in) ::    i8_local
        integer(kind = kint_gl), intent(inout) :: i8_global
      subroutine calypso_mpi_reduce_int8                              &
     &         (i8_local, i8_global, count, operation, destination)
        integer, intent(in) :: operation, destination
        integer(kind = kint_gl), intent(in) :: count
        integer(kind = kint_gl), intent(in) ::    i8_local(count)
        integer(kind = kint_gl), intent(inout) :: i8_global(count)
      subroutine calypso_mpi_allreduce_one_int8                       &
     &         (i8_local, i8_global, operation)
        integer, intent(in) :: operation
        integer(kind = kint_gl), intent(in) ::    i8_local
        integer(kind = kint_gl), intent(inout) :: i8_global
      subroutine calypso_mpi_allreduce_int8                           &
     &         (i8_local, i8_global, count, operation)
        integer, intent(in) :: operation
        integer(kind = kint_gl), intent(in) :: count
        integer(kind = kint_gl), intent(in) ::    i8_local(count)
        integer(kind = kint_gl), intent(inout) :: i8_global(count)
      subroutine calypso_mpi_allgather_one_int8(i8sendbuf, i8recvbuf)
        integer(kind = kint_gl), intent(in) :: i8sendbuf
        integer(kind = kint_gl), intent(inout) :: i8recvbuf(nprocs)
      subroutine calypso_mpi_allgather_int8                           &
     &         (i8sendbuf, n_send, i8recvbuf, n_recv)
        integer(kind = kint), intent(in) :: n_send, n_recv
        integer(kind = kint_gl), intent(in) ::    i8sendbuf(n_send)
        integer(kind = kint_gl), intent(inout)                        &
     &                        :: i8recvbuf(nprocs*n_recv)
      subroutine calypso_mpi_seek_write_int8                          &
     &         (id_mpi_file, ioffset, num, i8_vector, sta_IO)
        integer, intent(in) ::  id_mpi_file
        integer(kind = MPI_OFFSET_KIND), intent(in) :: ioffset
        integer(kind = kint_gl), intent(in) :: num
        integer(kind = kint_gl), intent(in) :: i8_vector(num)
        integer, intent(inout) :: sta_IO(MPI_STATUS_SIZE)
      subroutine calypso_mpi_seek_read_int8                           &
     &         (id_mpi_file, ioffset, num, i8_vector, sta_IO)
        integer, intent(in) ::  id_mpi_file
        integer(kind = MPI_OFFSET_KIND), intent(in) :: ioffset
        integer(kind = kint_gl), intent(in) :: num
        integer(kind = kint_gl), intent(inout) :: i8_vector(num)
        integer, intent(inout) :: sta_IO(MPI_STATUS_SIZE)
Function/Subroutine Documentation
calypso_mpi_allgather_int8()
subroutine calypso_mpi_int8::calypso_mpi_allgather_int8 (integer(kind = kint_gl), dimension(n_send), intent(in) i8sendbuf, integer(kind = kint), intent(in) n_send, integer(kind = kint_gl), dimension(nprocs*n_recv), intent(inout) i8recvbuf, integer(kind = kint), intent(in) n_recv)
Definition at line 233 of file calypso_mpi_int8.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_global_int, and calypso_mpi::ierr_mpi.
calypso_mpi_allgather_one_int8()
subroutine calypso_mpi_int8::calypso_mpi_allgather_one_int8 (integer(kind = kint_gl), intent(in) i8sendbuf, integer(kind = kint_gl), dimension(nprocs), intent(inout) i8recvbuf)
Definition at line 216 of file calypso_mpi_int8.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_global_int, and calypso_mpi::ierr_mpi.
Referenced by m_calypso_mpi_io::calypso_gz_mpi_seek_write(), gz_field_data_mpi_io::gz_write_fld_vecotr_mpi(), gz_vtk_file_mpi_io::gz_write_vtk_tensor_mpi(), and t_calypso_mpi_io_param::istack64_4_parallel_data().
calypso_mpi_allreduce_int8()
subroutine calypso_mpi_int8::calypso_mpi_allreduce_int8 (integer(kind = kint_gl), dimension(count), intent(in) i8_local, integer(kind = kint_gl), dimension(count), intent(inout) i8_global, integer(kind = kint_gl), intent(in) count, integer, intent(in) operation)
Definition at line 190 of file calypso_mpi_int8.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_global_int, m_constants::huge_20, and calypso_mpi::ierr_mpi.
Referenced by t_cal_max_indices::cal_max_indices(), and t_calypso_mpi_io_param::set_istack_over_subdomains().
calypso_mpi_allreduce_one_int8()
subroutine calypso_mpi_int8::calypso_mpi_allreduce_one_int8 (integer(kind = kint_gl), intent(in) i8_local, integer(kind = kint_gl), intent(inout) i8_global, integer, intent(in) operation)
Definition at line 171 of file calypso_mpi_int8.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_global_int, and calypso_mpi::ierr_mpi.
calypso_mpi_bcast_int8()
subroutine calypso_mpi_int8::calypso_mpi_bcast_int8 (integer(kind = kint_gl), dimension(count), intent(inout) buffer, integer(kind = kint_gl), intent(in) count, integer, intent(in) root)
Definition at line 100 of file calypso_mpi_int8.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_global_int, m_constants::huge_20, and calypso_mpi::ierr_mpi.
Referenced by gz_mpi_binary_head_io::gz_mpi_read_mul_int8head_b(), gz_field_data_mpi_io::gz_read_each_field_mpi(), gz_field_data_mpi_io::gz_skip_each_field_mpi(), mpi_binary_head_io::mpi_read_mul_int8head_b(), gz_field_block_mpi_io::read_field_header_gz_mpi(), and field_data_mpi_io::read_field_header_mpi().
calypso_mpi_bcast_one_int8()
subroutine calypso_mpi_int8::calypso_mpi_bcast_one_int8 (integer(kind = kint_gl), intent(inout) buffer, integer, intent(in) root)
Definition at line 83 of file calypso_mpi_int8.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_global_int, and calypso_mpi::ierr_mpi.
Referenced by gz_mpi_binary_head_io::gz_mpi_read_byte_check(), gz_mpi_ascii_data_io::gz_mpi_read_charahead(), gz_mpi_binary_head_io::gz_mpi_read_mul_charahead_b(), gz_mpi_binary_head_io::gz_mpi_read_mul_int8head_b(), gz_mpi_binary_head_io::gz_mpi_read_mul_realhead_b(), gz_mpi_ascii_data_io::gz_mpi_skip_header(), gz_mpi_binary_head_io::gz_mpi_write_byte_flag(), gz_mpi_ascii_data_io::gz_mpi_write_charahead(), gz_mpi_binary_head_io::gz_mpi_write_mul_charahead_b(), gz_mpi_binary_head_io::gz_mpi_write_mul_int8head_b(), gz_mpi_binary_head_io::gz_mpi_write_mul_realhead_b(), gz_field_data_mpi_io::gz_read_fld_1word_mpi(), gz_field_data_mpi_io::gz_read_fld_charhead_mpi(), gz_field_data_mpi_io::gz_write_fld_header_mpi(), and gz_vtk_file_mpi_io::gz_write_vtk_header_mpi().
calypso_mpi_reduce_int8()
subroutine calypso_mpi_int8::calypso_mpi_reduce_int8 (integer(kind = kint_gl), dimension(count), intent(in) i8_local, integer(kind = kint_gl), dimension(count), intent(inout) i8_global, integer(kind = kint_gl), intent(in) count, integer, intent(in) operation, integer, intent(in) destination)
Definition at line 144 of file calypso_mpi_int8.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_global_int, m_constants::huge_20, and calypso_mpi::ierr_mpi.
calypso_mpi_reduce_one_int8()
subroutine calypso_mpi_int8::calypso_mpi_reduce_one_int8 (integer(kind = kint_gl), intent(in) i8_local, integer(kind = kint_gl), intent(inout) i8_global, integer, intent(in) operation, integer, intent(in) destination)
Definition at line 124 of file calypso_mpi_int8.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_global_int, and calypso_mpi::ierr_mpi.
calypso_mpi_seek_read_int8()
subroutine calypso_mpi_int8::calypso_mpi_seek_read_int8 (integer, intent(in) id_mpi_file, integer(kind = mpi_offset_kind), intent(in) ioffset, integer(kind = kint_gl), intent(in) num, integer(kind = kint_gl), dimension(num), intent(inout) i8_vector, integer, dimension(mpi_status_size), intent(inout) sta_IO)
Definition at line 281 of file calypso_mpi_int8.f90.
References calypso_mpi::calypso_global_int, m_constants::huge_20, calypso_mpi::ierr_mpi, and m_precision::kint_gl.
Referenced by m_calypso_mpi_io::mpi_read_int8_b().
calypso_mpi_seek_write_int8()
subroutine calypso_mpi_int8::calypso_mpi_seek_write_int8 (integer, intent(in) id_mpi_file, integer(kind = mpi_offset_kind), intent(in) ioffset, integer(kind = kint_gl), intent(in) num, integer(kind = kint_gl), dimension(num), intent(in) i8_vector, integer, dimension(mpi_status_size), intent(inout) sta_IO)
Definition at line 251 of file calypso_mpi_int8.f90.
References calypso_mpi::calypso_global_int, m_constants::huge_20, calypso_mpi::ierr_mpi, and m_precision::kint_gl.
Referenced by m_calypso_mpi_io::mpi_write_int8_b().