CALYPSO: cal_sol_sph_fluid_crank Module Reference
cal_sol_sph_fluid_crank Module Reference
Update each field for MHD dynamo model.
Functions/Subroutines
subroutine cal_sol_velo_by_vort_sph_crank (sph_rj, r_2nd, sph_bc_U, bcs_U, fdm2_free_ICB, fdm2_free_CMB, band_vp_evo, band_vt_evo, ipol, rj_fld)
subroutine cal_sol_pressure_by_div_v (sph_rj, sph_bc_U, band_p_poisson, ipol, rj_fld)
subroutine cal_sol_magne_sph_crank (sph_rj, r_2nd, sph_bc_B, bcs_B, band_bp_evo, band_bt_evo, g_sph_rj, ipol, rj_fld)
subroutine cal_sol_scalar_sph_crank (dt, sph_rj, property, sph_bc, bcs_S, band_s_evo, band_s00_evo, is_scalar, rj_fld, x00_w_center)
Detailed Description
Update each field for MHD dynamo model.
      subroutine cal_sol_velo_by_vort_sph_crank(sph_rj, r_2nd,        &
     &          sph_bc_U, bcs_U, fdm2_free_ICB, fdm2_free_CMB,        &
     &          band_vp_evo, band_vt_evo, ipol, rj_fld)
        Input address:    ipol%base%i_vort, ipol%base%i_vort+2
        Solution address: ipol%base%i_velo, ipol%base%i_velo+2
        type(sph_boundary_type), intent(in) :: sph_bc_U
        type(sph_scalar_boundary_data), intent(in) :: bcs_U
      subroutine cal_sol_pressure_by_div_v                            &
     &         (sph_rj, sph_bc_U, band_p_poisson, ipol, rj_fld)
        Solution address: ipol%base%i_press
      subroutine cal_sol_magne_sph_crank(sph_rj, r_2nd,               &
     &          sph_bc_B, bcs_B, band_bp_evo, band_bt_evo,            &
     &          g_sph_rj, ipol, rj_fld)
        Input address:    ipol%base%i_magne, ipol%base%i_magne+2
        Solution address: ipol%base%i_magne, ipol%base%i_magne+2
        type(sph_boundary_type), intent(in) :: sph_bc_B
        type(sph_vector_boundary_data), intent(in) :: bcs_B
      subroutine cal_sol_scalar_sph_crank(dt, sph_rj, property,       &
     &         sph_bc, bcs_S, band_s_evo, band_s00_evo,               &
     &         is_scalar, rj_fld, x00_w_center)
        type(sph_rj_grid), intent(in) :: sph_rj
        type(sph_boundary_type), intent(in) :: sph_bc
        type(sph_scalar_boundary_data), intent(in) :: bcs_S
        type(scalar_property), intent(in) :: cp_prop
        type(band_matrices_type), intent(in) :: band_comp_evo
        type(phys_address), intent(in) :: ipol
        type(phys_data), intent(inout) :: rj_fld
        Input address:    ipol%base%i_light
        Solution address: ipol%base%i_light
Parameters
ntot_phys_rj Total number of components
d_rj Spectrum data
Function/Subroutine Documentation
cal_sol_magne_sph_crank()
subroutine cal_sol_sph_fluid_crank::cal_sol_magne_sph_crank (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc_B, type(sph_vector_boundary_data), intent(in) bcs_B, type(band_matrices_type), intent(in) band_bp_evo, type(band_matrices_type), intent(in) band_bt_evo, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld)
Definition at line 153 of file cal_sol_sph_fluid_crank.f90.
References set_reference_sph_mhd::delete_zero_degree_vect(), select_exp_magne_cmb::sel_cmb_grad_poloidal_magne(), select_exp_magne_icb::sel_icb_grad_poloidal_magne(), and solve_sph_fluid_crank::solve_magne_sph_crank().
Referenced by cal_sol_sph_mhd_crank::s_cal_sol_sph_mhd_crank().
cal_sol_pressure_by_div_v()
subroutine cal_sol_sph_fluid_crank::cal_sol_pressure_by_div_v (type(sph_rj_grid), intent(in) sph_rj, type(sph_boundary_type), intent(in) sph_bc_U, type(band_matrices_type), intent(in) band_p_poisson, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld)
Definition at line 126 of file cal_sol_sph_fluid_crank.f90.
References set_reference_sph_mhd::adjust_by_ave_pressure_on_cmb(), and solve_sph_fluid_crank::solve_pressure_by_div_v().
Referenced by lead_fields_4_sph_mhd::pressure_4_sph_mhd().
cal_sol_scalar_sph_crank()
subroutine cal_sol_sph_fluid_crank::cal_sol_scalar_sph_crank (real(kind = kreal), intent(in) dt, type(sph_rj_grid), intent(in) sph_rj, type(scalar_property), intent(in) property, type(sph_boundary_type), intent(in) sph_bc, type(sph_scalar_boundary_data), intent(in) bcs_S, type(band_matrices_type), intent(in) band_s_evo, type(band_matrix_type), intent(in) band_s00_evo, integer(kind = kint), intent(in) is_scalar, type(phys_data), intent(inout) rj_fld, real(kind = kreal), dimension(0:sph_rj%nidx_rj(1)), intent(inout) x00_w_center)
Definition at line 194 of file cal_sol_sph_fluid_crank.f90.
References fill_scalar_field::fill_scalar_at_external(), select_exp_scalar_cmb::set_cmb_scalar_sph_crank(), select_exp_scalar_icb::set_icb_scalar_sph_crank(), and solve_sph_fluid_crank::solve_scalar_sph_crank().
Referenced by cal_sol_sph_mhd_crank::s_cal_sol_sph_mhd_crank().
cal_sol_velo_by_vort_sph_crank()
subroutine cal_sol_sph_fluid_crank::cal_sol_velo_by_vort_sph_crank (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc_U, type(sph_vector_boundary_data), intent(in) bcs_U, type(fdm2_free_slip), intent(in) fdm2_free_ICB, type(fdm2_free_slip), intent(in) fdm2_free_CMB, type(band_matrices_type), intent(in) band_vp_evo, type(band_matrices_type), intent(in) band_vt_evo, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld)
Definition at line 75 of file cal_sol_sph_fluid_crank.f90.
References copy_field_smp::copy_nod_scalar_smp(), set_reference_sph_mhd::delete_zero_degree_vect(), select_exp_velocity_cmb::sel_cmb_grad_poloidal_moment(), select_exp_velocity_icb::sel_icb_grad_poloidal_moment(), and solve_sph_fluid_crank::solve_velo_by_vort_sph_crank().
Referenced by cal_sol_sph_mhd_crank::s_cal_sol_sph_mhd_crank().