CALYPSO: m_viewer_mesh_labels Module Reference
m_viewer_mesh_labels Module Reference
Comments for viewer mesh data.
Functions/Subroutines
character(len=ilen_ndomain_viewer) function hd_ndomain_viewer ()
character(len=ilen_node_viewer) function hd_node_viewer ()
character(len=ilen_surf_viewer) function hd_surf_viewer ()
character(len=ilen_edge_viewer) function hd_edge_viewer ()
character(len=ilen_edge_on_sf_viewer) function hd_edge_on_sf_viewer ()
character(len=ilen_domain_nod_grp) function hd_domain_nod_grp ()
character(len=ilen_domain_surf_grp) function hd_domain_surf_grp ()
character(len=ilen_domain_edge_grp) function hd_domain_edge_grp ()
character(len=ilen_ele_surf_grp) function hd_ele_surf_grp ()
character(len=ilen_ele_nod_grp) function hd_ele_nod_grp ()
character(len=ilen_ele_edge_grp) function hd_ele_edge_grp ()
character(len=ilen_surf_surf_grp) function hd_surf_surf_grp ()
character(len=ilen_surf_nod_grp) function hd_surf_nod_grp ()
character(len=ilen_surf_edge_grp) function hd_surf_edge_grp ()
Variables
integer(kind=kint), parameter ilen_ndomain_viewer = 1+21+31+31+31+1+6
length of ilen_ndomain_viewer
integer(kind=kint), parameter ilen_node_viewer = 1+21+21+21+1+5
length of hd_node_viewer
integer(kind=kint), parameter ilen_surf_viewer = 1+25+25+25+1+5
length of hd_surf_viewer
integer(kind=kint), parameter ilen_edge_viewer = 1+25+25+25+1+5
length of hd_edge_viewer
integer(kind=kint), parameter ilen_edge_on_sf_viewer = 1+26+1+3
length of hd_edge_on_sf_viewer
integer(kind=kint), parameter ilen_domain_nod_grp = 1+36+1+3
length of hd_domain_nod_grp
integer(kind=kint), parameter ilen_domain_surf_grp = 1+36+1+3
length of hd_domain_surf_grp
integer(kind=kint), parameter ilen_domain_edge_grp = 1+36+1+3
length of hd_domain_edge_grp
integer(kind=kint), parameter ilen_ele_surf_grp = 20+1+2
length of hd_ele_surf_grp
integer(kind=kint), parameter ilen_ele_nod_grp = 20+1+2
length of hd_ele_nod_grp
integer(kind=kint), parameter ilen_ele_edge_grp = 20+1+2
length of hd_ele_edge_grp
integer(kind=kint), parameter ilen_surf_surf_grp = 20+1+2
length of hd_surf_surf_grp
integer(kind=kint), parameter ilen_surf_nod_grp = 20+1+2
length of hd_surf_nod_grp
integer(kind=kint), parameter ilen_surf_edge_grp = 20+1+2
length of hd_surf_edge_grp
Detailed Description
Comments for viewer mesh data.
      character(len=ilen_ndomain_viewer) function hd_ndomain_viewer()
      character(len=ilen_node_viewer) function hd_node_viewer()
      character(len=ilen_surf_viewer) function hd_surf_viewer()
      character(len=ilen_edge_viewer) function hd_edge_viewer()
      character(len=ilen_edge_on_sf_viewer)                           &
     &                        function hd_edge_on_sf_viewer()
      character(len=ilen_domain_nod_grp) function hd_domain_nod_grp()
      character(len=ilen_domain_surf_grp)                             &
     &             function hd_domain_surf_grp()
      character(len=ilen_domain_edge_grp)                             &
     &             function hd_domain_edge_grp()
      character(len=ilen_ele_surf_grp) function hd_ele_surf_grp()
      character(len=ilen_ele_nod_grp) function hd_ele_nod_grp()
      character(len=ilen_ele_edge_grp) function hd_ele_edge_grp()
      character(len=ilen_surf_surf_grp) function hd_surf_surf_grp()
      character(len=ilen_surf_nod_grp) function hd_edge_nod_grp()
      character(len=ilen_surf_edge_grp) function hd_surf_edge_grp()
Function/Subroutine Documentation
hd_domain_edge_grp()
character(len=ilen_domain_edge_grp) function m_viewer_mesh_labels::hd_domain_edge_grp
Definition at line 178 of file m_viewer_mesh_labels.f90.
Referenced by gz_mpi_viewer_mesh_file_io::gz_write_viewer_mesh_infos(), viewer_group_data_io::write_domain_group_viewer(), and mpi_viewer_mesh_file_io::write_viewer_mesh_infos().
hd_domain_nod_grp()
character(len=ilen_domain_nod_grp) function m_viewer_mesh_labels::hd_domain_nod_grp
Definition at line 155 of file m_viewer_mesh_labels.f90.
Referenced by gz_mpi_viewer_mesh_file_io::gz_write_viewer_mesh_infos(), viewer_group_data_io::write_domain_group_viewer(), and mpi_viewer_mesh_file_io::write_viewer_mesh_infos().
hd_domain_surf_grp()
character(len=ilen_domain_surf_grp) function m_viewer_mesh_labels::hd_domain_surf_grp
Definition at line 166 of file m_viewer_mesh_labels.f90.
Referenced by gz_mpi_viewer_mesh_file_io::gz_write_viewer_mesh_infos(), viewer_group_data_io::write_domain_group_viewer(), and mpi_viewer_mesh_file_io::write_viewer_mesh_infos().
hd_edge_on_sf_viewer()
character(len=ilen_edge_on_sf_viewer) function m_viewer_mesh_labels::hd_edge_on_sf_viewer
Definition at line 142 of file m_viewer_mesh_labels.f90.
Referenced by gz_mpi_viewer_mesh_file_io::gz_write_viewer_mesh_infos(), viewer_mesh_data_io::write_edge_connect_viewer(), and mpi_viewer_mesh_file_io::write_viewer_mesh_infos().
hd_edge_viewer()
character(len=ilen_edge_viewer) function m_viewer_mesh_labels::hd_edge_viewer
Definition at line 129 of file m_viewer_mesh_labels.f90.
Referenced by gz_mpi_viewer_mesh_file_io::gz_write_viewer_mesh_infos(), viewer_mesh_data_io::write_edge_connect_viewer(), and mpi_viewer_mesh_file_io::write_viewer_mesh_infos().
hd_ele_edge_grp()
character(len=ilen_ele_edge_grp) function m_viewer_mesh_labels::hd_ele_edge_grp
Definition at line 211 of file m_viewer_mesh_labels.f90.
Referenced by gz_mpi_viewer_mesh_file_io::gz_write_viewer_mesh_infos(), viewer_group_data_io::write_ele_group_viewer(), and mpi_viewer_mesh_file_io::write_viewer_mesh_infos().
hd_ele_nod_grp()
character(len=ilen_ele_nod_grp) function m_viewer_mesh_labels::hd_ele_nod_grp
Definition at line 201 of file m_viewer_mesh_labels.f90.
Referenced by gz_mpi_viewer_mesh_file_io::gz_write_viewer_mesh_infos(), viewer_group_data_io::write_ele_group_viewer(), and mpi_viewer_mesh_file_io::write_viewer_mesh_infos().
hd_ele_surf_grp()
character(len=ilen_ele_surf_grp) function m_viewer_mesh_labels::hd_ele_surf_grp
Definition at line 191 of file m_viewer_mesh_labels.f90.
Referenced by gz_mpi_viewer_mesh_file_io::gz_write_viewer_mesh_infos(), viewer_group_data_io::write_ele_group_viewer(), and mpi_viewer_mesh_file_io::write_viewer_mesh_infos().
hd_ndomain_viewer()
character(len=ilen_ndomain_viewer) function m_viewer_mesh_labels::hd_ndomain_viewer
Definition at line 89 of file m_viewer_mesh_labels.f90.
Referenced by gz_mpi_viewer_mesh_file_io::gz_write_viewer_mesh_infos(), viewer_mesh_data_io::write_sgl_domain_data_viewer(), and mpi_viewer_mesh_file_io::write_viewer_mesh_infos().
hd_node_viewer()
character(len=ilen_node_viewer) function m_viewer_mesh_labels::hd_node_viewer
Definition at line 103 of file m_viewer_mesh_labels.f90.
Referenced by gz_mpi_viewer_mesh_file_io::gz_write_viewer_mesh_infos(), viewer_mesh_data_io::write_node_data_viewer(), and mpi_viewer_mesh_file_io::write_viewer_mesh_infos().
hd_surf_edge_grp()
character(len=ilen_surf_edge_grp) function m_viewer_mesh_labels::hd_surf_edge_grp
Definition at line 242 of file m_viewer_mesh_labels.f90.
Referenced by gz_mpi_viewer_mesh_file_io::gz_write_viewer_mesh_infos(), viewer_group_data_io::write_surf_group_viewer(), and mpi_viewer_mesh_file_io::write_viewer_mesh_infos().
hd_surf_nod_grp()
character(len=ilen_surf_nod_grp) function m_viewer_mesh_labels::hd_surf_nod_grp
Definition at line 232 of file m_viewer_mesh_labels.f90.
Referenced by gz_mpi_viewer_mesh_file_io::gz_write_viewer_mesh_infos(), viewer_group_data_io::write_surf_group_viewer(), and mpi_viewer_mesh_file_io::write_viewer_mesh_infos().
hd_surf_surf_grp()
character(len=ilen_surf_surf_grp) function m_viewer_mesh_labels::hd_surf_surf_grp
Definition at line 222 of file m_viewer_mesh_labels.f90.
Referenced by gz_mpi_viewer_mesh_file_io::gz_write_viewer_mesh_infos(), viewer_group_data_io::write_surf_group_viewer(), and mpi_viewer_mesh_file_io::write_viewer_mesh_infos().
hd_surf_viewer()
character(len=ilen_surf_viewer) function m_viewer_mesh_labels::hd_surf_viewer
Definition at line 116 of file m_viewer_mesh_labels.f90.
Referenced by gz_mpi_viewer_mesh_file_io::gz_write_viewer_mesh_infos(), viewer_mesh_data_io::write_surf_connect_viewer(), and mpi_viewer_mesh_file_io::write_viewer_mesh_infos().
Variable Documentation
ilen_domain_edge_grp
integer(kind = kint), parameter m_viewer_mesh_labels::ilen_domain_edge_grp = 1+36+1+3
length of hd_domain_edge_grp
Definition at line 60 of file m_viewer_mesh_labels.f90.
ilen_domain_nod_grp
integer(kind = kint), parameter m_viewer_mesh_labels::ilen_domain_nod_grp = 1+36+1+3
length of hd_domain_nod_grp
Definition at line 54 of file m_viewer_mesh_labels.f90.
ilen_domain_surf_grp
integer(kind = kint), parameter m_viewer_mesh_labels::ilen_domain_surf_grp = 1+36+1+3
length of hd_domain_surf_grp
Definition at line 57 of file m_viewer_mesh_labels.f90.
ilen_edge_on_sf_viewer
integer(kind = kint), parameter m_viewer_mesh_labels::ilen_edge_on_sf_viewer = 1+26+1+3
length of hd_edge_on_sf_viewer
Definition at line 50 of file m_viewer_mesh_labels.f90.
ilen_edge_viewer
integer(kind = kint), parameter m_viewer_mesh_labels::ilen_edge_viewer = 1+25+25+25+1+5
length of hd_edge_viewer
Definition at line 47 of file m_viewer_mesh_labels.f90.
ilen_ele_edge_grp
integer(kind = kint), parameter m_viewer_mesh_labels::ilen_ele_edge_grp = 20+1+2
length of hd_ele_edge_grp
Definition at line 70 of file m_viewer_mesh_labels.f90.
ilen_ele_nod_grp
integer(kind = kint), parameter m_viewer_mesh_labels::ilen_ele_nod_grp = 20+1+2
length of hd_ele_nod_grp
Definition at line 67 of file m_viewer_mesh_labels.f90.
ilen_ele_surf_grp
integer(kind = kint), parameter m_viewer_mesh_labels::ilen_ele_surf_grp = 20+1+2
length of hd_ele_surf_grp
Definition at line 64 of file m_viewer_mesh_labels.f90.
ilen_ndomain_viewer
integer(kind = kint), parameter m_viewer_mesh_labels::ilen_ndomain_viewer = 1+21+31+31+31+1+6
length of ilen_ndomain_viewer
Definition at line 38 of file m_viewer_mesh_labels.f90.
ilen_node_viewer
integer(kind = kint), parameter m_viewer_mesh_labels::ilen_node_viewer = 1+21+21+21+1+5
length of hd_node_viewer
Definition at line 41 of file m_viewer_mesh_labels.f90.
ilen_surf_edge_grp
integer(kind = kint), parameter m_viewer_mesh_labels::ilen_surf_edge_grp = 20+1+2
length of hd_surf_edge_grp
Definition at line 80 of file m_viewer_mesh_labels.f90.
ilen_surf_nod_grp
integer(kind = kint), parameter m_viewer_mesh_labels::ilen_surf_nod_grp = 20+1+2
length of hd_surf_nod_grp
Definition at line 77 of file m_viewer_mesh_labels.f90.
ilen_surf_surf_grp
integer(kind = kint), parameter m_viewer_mesh_labels::ilen_surf_surf_grp = 20+1+2
length of hd_surf_surf_grp
Definition at line 74 of file m_viewer_mesh_labels.f90.
ilen_surf_viewer
integer(kind = kint), parameter m_viewer_mesh_labels::ilen_surf_viewer = 1+25+25+25+1+5
length of hd_surf_viewer
Definition at line 44 of file m_viewer_mesh_labels.f90.