CALYPSO: vtk_data_io Module Reference
vtk_data_io Module Reference
Output routine for VTK data segments.
Functions/Subroutines
subroutine write_vtk_fields_head (id_vtk, nnod)
subroutine, private write_vtk_each_field_head (id_vtk, ncomp_field, field_name)
subroutine write_vtk_each_field (id_vtk, ntot_nod, ncomp_field, nnod, d_nod)
subroutine write_vtk_node_head (id_vtk, nnod)
subroutine write_vtk_connect_data (id_vtk, ntot_ele, nnod_ele, nele, ie)
subroutine write_vtk_data (id_vtk, nnod, num_field, ntot_comp, ncomp_field, field_name, d_nod)
subroutine read_vtk_fields_head (id_vtk, nnod)
subroutine read_vtk_each_field_head (id_vtk, iflag_end, ncomp_field, field_name)
subroutine read_vtk_each_field (id_vtk, ntot_nod, ncomp_field, nnod, d_nod)
subroutine read_vtk_node_head (id_vtk, nnod)
subroutine read_vtk_connect_head (id_vtk, nele, nnod_ele)
subroutine read_vtk_cell_type (id_vtk, nele)
subroutine read_vtk_connect_data (id_vtk, ntot_ele, nnod_ele, nele, ie)
Detailed Description
Output routine for VTK data segments.
      subroutine write_vtk_fields_head(id_vtk, nnod)
      subroutine write_vtk_each_field                                 &
     &         (id_vtk, ntot_nod, ncomp_field, nnod, d_nod)
      subroutine write_vtk_data(id_vtk, nnod, num_field, ntot_comp,   &
     &          ncomp_field, field_name, d_nod)
      subroutine write_vtk_node_head(id_vtk, nnod)
      subroutine write_vtk_connect_data                               &
     &         (id_vtk, ntot_ele, nnod_ele, nele, ie)
      subroutine read_vtk_fields_head(id_vtk, nnod)
      subroutine read_vtk_each_field_head                             &
     &         (id_vtk, iflag_end, ncomp_field, field_name)
      subroutine read_vtk_each_field                                  &
     &         (id_vtk, ntot_nod, ncomp_field, nnod, d_nod)
      subroutine read_vtk_node_head(id_vtk, nnod)
      subroutine read_vtk_connect_head(id_vtk, nele, nnod_ele)
      subroutine read_vtk_cell_type(id_vtk, nele)
      subroutine read_vtk_connect_data                                &
     &         (id_vtk, ntot_ele, nnod_ele, nele, ie)
Parameters
id_vtk file ID for VTK data file
nnod Number of nodes
nele Number of elements
nnod_ele Number of nodes for each element
xx(nnod,3) position of nodes
nnod_ele number of nodes for each element
ie(nele,nnod_ele) element connectivity
ntot_comp total number of components
ncomp_field(num_field) number of components
field_name(num_field) list of field names
d_nod(nnod,ntot_comp) field data
Function/Subroutine Documentation
read_vtk_cell_type()
subroutine vtk_data_io::read_vtk_cell_type (integer(kind = kint), intent(in) id_vtk, integer(kind = kint_gl), intent(in) nele)
Definition at line 320 of file vtk_data_IO.f90.
Referenced by udt_to_vtk_data_io::read_alloc_ucd_mesh_from_vtk(), and udt_to_vtk_data_io::read_ucd_mesh_from_vtk().
read_vtk_connect_data()
subroutine vtk_data_io::read_vtk_connect_data (integer(kind = kint), intent(in) id_vtk, integer(kind = kint_gl), intent(in) ntot_ele, integer(kind = kint), intent(in) nnod_ele, integer(kind = kint_gl), intent(in) nele, integer(kind = kint_gl), dimension(ntot_ele,nnod_ele), intent(inout) ie)
Definition at line 339 of file vtk_data_IO.f90.
Referenced by udt_to_vtk_data_io::read_alloc_ucd_mesh_from_vtk(), and udt_to_vtk_data_io::read_ucd_mesh_from_vtk().
read_vtk_connect_head()
subroutine vtk_data_io::read_vtk_connect_head (integer(kind = kint), intent(in) id_vtk, integer(kind = kint_gl), intent(inout) nele, integer(kind = kint), intent(inout) nnod_ele)
Definition at line 303 of file vtk_data_IO.f90.
Referenced by udt_to_vtk_data_io::read_alloc_ucd_mesh_from_vtk(), and udt_to_vtk_data_io::read_ucd_mesh_from_vtk().
read_vtk_each_field()
subroutine vtk_data_io::read_vtk_each_field (integer(kind = kint), intent(in) id_vtk, integer(kind=kint_gl), intent(in) ntot_nod, integer(kind = kint), intent(in) ncomp_field, integer(kind=kint_gl), intent(in) nnod, real(kind = kreal), dimension(ntot_nod,ncomp_field), intent(inout) d_nod)
Definition at line 255 of file vtk_data_IO.f90.
References m_phys_constants::n_sym_tensor.
Referenced by udt_to_vtk_data_io::read_alloc_ucd_mesh_from_vtk(), udt_to_vtk_data_io::read_alloc_udt_field_from_vtk(), udt_to_vtk_data_io::read_ucd_mesh_from_vtk(), and udt_to_vtk_data_io::read_udt_field_from_vtk().
read_vtk_each_field_head()
subroutine vtk_data_io::read_vtk_each_field_head (integer(kind = kint), intent(in) id_vtk, integer(kind=kint), intent(inout) iflag_end, integer(kind=kint), intent(inout) ncomp_field, character(len=kchara), intent(inout) field_name)
Definition at line 225 of file vtk_data_IO.f90.
References m_phys_constants::n_scalar, m_phys_constants::n_sym_tensor, and m_phys_constants::n_vector.
Referenced by udt_to_vtk_data_io::read_alloc_udt_field_from_vtk(), and udt_to_vtk_data_io::read_udt_field_from_vtk().
read_vtk_fields_head()
subroutine vtk_data_io::read_vtk_fields_head (integer(kind = kint), intent(in) id_vtk, integer(kind=kint_gl), intent(inout) nnod)
Definition at line 208 of file vtk_data_IO.f90.
References skip_comment_f::skip_comment().
Referenced by udt_to_vtk_data_io::read_alloc_udt_field_from_vtk(), and udt_to_vtk_data_io::read_udt_field_from_vtk().
read_vtk_node_head()
subroutine vtk_data_io::read_vtk_node_head (integer(kind = kint), intent(in) id_vtk, integer(kind = kint_gl), intent(inout) nnod)
Definition at line 284 of file vtk_data_IO.f90.
Referenced by udt_to_vtk_data_io::read_alloc_ucd_mesh_from_vtk(), and udt_to_vtk_data_io::read_ucd_mesh_from_vtk().
write_vtk_connect_data()
subroutine vtk_data_io::write_vtk_connect_data (integer(kind = kint), intent(in) id_vtk, integer(kind = kint_gl), intent(in) ntot_ele, integer(kind = kint), intent(in) nnod_ele, integer(kind = kint_gl), intent(in) nele, integer(kind = kint_gl), dimension(ntot_ele,nnod_ele), intent(in) ie)
Definition at line 145 of file vtk_data_IO.f90.
References vtk_data_to_buffer::vtk_cell_type(), vtk_data_to_buffer::vtk_cell_type_head(), vtk_data_to_buffer::vtk_connect_head(), vtk_data_to_buffer::vtk_each_cell_type(), and vtk_data_to_buffer::vtk_each_connect().
Referenced by udt_to_vtk_data_io::write_ucd_mesh_to_vtk().
write_vtk_data()
subroutine vtk_data_io::write_vtk_data (integer(kind = kint), intent(in) id_vtk, integer(kind=kint_gl), intent(in) nnod, integer(kind=kint), intent(in) num_field, integer(kind=kint), intent(in) ntot_comp, integer(kind=kint), dimension(num_field), intent(in) ncomp_field, character(len=kchara), dimension(num_field), intent(in) field_name, real(kind = kreal), dimension(nnod,ntot_comp), intent(in) d_nod)
Definition at line 179 of file vtk_data_IO.f90.
References write_vtk_each_field(), and write_vtk_each_field_head().
Referenced by udt_to_vtk_data_io::write_ucd_field_to_vtk().
write_vtk_each_field()
subroutine vtk_data_io::write_vtk_each_field (integer(kind = kint), intent(in) id_vtk, integer(kind=kint_gl), intent(in) ntot_nod, integer(kind=kint), intent(in) ncomp_field, integer(kind=kint_gl), intent(in) nnod, real(kind = kreal), dimension(ntot_nod,ncomp_field), intent(in) d_nod)
Definition at line 95 of file vtk_data_IO.f90.
References m_phys_constants::n_sym_tensor, and m_phys_constants::n_vector.
Referenced by udt_to_vtk_data_io::write_ucd_mesh_to_vtk(), and write_vtk_data().
write_vtk_each_field_head()
subroutine, private vtk_data_io::write_vtk_each_field_head (integer(kind = kint), intent(in) id_vtk, integer(kind=kint), intent(in) ncomp_field, character(len=kchara), intent(in) field_name) private
Definition at line 74 of file vtk_data_IO.f90.
References m_phys_constants::n_scalar, m_phys_constants::n_sym_tensor, m_phys_constants::n_vector, vtk_data_to_buffer::vtk_scalar_head(), vtk_data_to_buffer::vtk_tensor_head(), and vtk_data_to_buffer::vtk_vector_head().
Referenced by write_vtk_data().
write_vtk_fields_head()
subroutine vtk_data_io::write_vtk_fields_head (integer(kind = kint), intent(in) id_vtk, integer(kind=kint_gl), intent(in) nnod)
Definition at line 62 of file vtk_data_IO.f90.
References vtk_data_to_buffer::vtk_fields_head().
Referenced by udt_to_vtk_data_io::write_ucd_field_to_vtk().
write_vtk_node_head()
subroutine vtk_data_io::write_vtk_node_head (integer(kind = kint), intent(in) id_vtk, integer(kind = kint_gl), intent(in) nnod)
Definition at line 132 of file vtk_data_IO.f90.
References vtk_data_to_buffer::vtk_node_head().
Referenced by udt_to_vtk_data_io::write_ucd_mesh_to_vtk().