CALYPSO: node_monitor_io Module Reference
node_monitor_io Module Reference
Functions/Subroutines
subroutine set_local_nod_4_monitor (mesh, group)
subroutine output_monitor_control (istep, point_step, time_d, mesh, nod_fld)
subroutine allocate_monitor_group
subroutine, private allocate_monitor_local
subroutine deallocate_monitor_local
subroutine, private open_node_monitor_file (id_rank, nod_fld)
subroutine set_local_node_id_4_monitor (node, nod_grp)
subroutine, private output_nodal_monitor_data (time_d, node, nod_fld)
subroutine skip_monitor_data (i_step_init)
Variables
integer(kind=kint), parameter, private id_monitor_file = 47
character(len=kchara), parameter, private node_monitor_head = 'node'
integer(kind=kint) num_monitor
character(len=kchara), dimension(:), allocatable monitor_grp
integer(kind=kint), private num_monitor_local
integer(kind=kint), dimension(:), allocatable, private monitor_local
integer(kind=kint) num_field_monitor
integer(kind=kint) ntot_comp_monitor
integer(kind=kint), dimension(:), allocatable, private num_comp_phys_monitor
character(len=kchara), dimension(:), allocatable, private phys_name_monitor
Function/Subroutine Documentation
allocate_monitor_group()
subroutine node_monitor_io::allocate_monitor_group
Definition at line 98 of file node_monitor_IO.f90.
References monitor_grp, and num_monitor.
Referenced by set_control_4_model::s_set_control_4_model().
allocate_monitor_local()
subroutine, private node_monitor_io::allocate_monitor_local private
Definition at line 107 of file node_monitor_IO.f90.
References monitor_local, and num_monitor_local.
Referenced by set_local_node_id_4_monitor().
deallocate_monitor_local()
subroutine node_monitor_io::deallocate_monitor_local
Definition at line 117 of file node_monitor_IO.f90.
References monitor_grp, and monitor_local.
open_node_monitor_file()
subroutine, private node_monitor_io::open_node_monitor_file (integer, intent(in) id_rank, type(phys_data), intent(in) nod_fld) private
Definition at line 127 of file node_monitor_IO.f90.
References set_parallel_file_name::add_dat_extension(), set_parallel_file_name::add_process_id(), id_monitor_file, node_monitor_head, num_comp_phys_monitor, num_field_monitor, num_monitor_local, and phys_name_monitor.
Referenced by output_nodal_monitor_data().
output_monitor_control()
subroutine node_monitor_io::output_monitor_control (integer(kind = kint), intent(in) istep, type(io_step_param), intent(in) point_step, type(time_data), intent(in) time_d, type(mesh_geometry), intent(in) mesh, type(phys_data), intent(in) nod_fld)
Definition at line 73 of file node_monitor_IO.f90.
References m_machine_parameter::iflag_debug, num_monitor, num_monitor_local, t_io_step_parameter::output_io_flag(), and output_nodal_monitor_data().
output_nodal_monitor_data()
subroutine, private node_monitor_io::output_nodal_monitor_data (type(time_data), intent(in) time_d, type(node_data), intent(in) node, type(phys_data), intent(in) nod_fld) private
Definition at line 232 of file node_monitor_IO.f90.
References id_monitor_file, monitor_local, calypso_mpi::my_rank, num_monitor_local, and open_node_monitor_file().
Referenced by output_monitor_control().
set_local_nod_4_monitor()
subroutine node_monitor_io::set_local_nod_4_monitor (type(mesh_geometry), intent(in) mesh, type(mesh_groups), intent(in) group)
Definition at line 61 of file node_monitor_IO.f90.
References set_local_node_id_4_monitor().
Referenced by fem_analyzer_sph_mhd::fem_initialize_sph_mhd().
set_local_node_id_4_monitor()
subroutine node_monitor_io::set_local_node_id_4_monitor (type(node_data), intent(in) node, type(group_data), intent(in) nod_grp)
Definition at line 179 of file node_monitor_IO.f90.
References allocate_monitor_local(), monitor_grp, monitor_local, num_monitor, and num_monitor_local.
Referenced by set_local_nod_4_monitor().
skip_monitor_data()
subroutine node_monitor_io::skip_monitor_data (integer(kind=kint), intent(in) i_step_init)
Definition at line 269 of file node_monitor_IO.f90.
References id_monitor_file, ntot_comp_monitor, num_monitor, and num_monitor_local.
Variable Documentation
id_monitor_file
integer(kind=kint), parameter, private node_monitor_io::id_monitor_file = 47 private
Definition at line 35 of file node_monitor_IO.f90.
Referenced by open_node_monitor_file(), output_nodal_monitor_data(), and skip_monitor_data().
monitor_grp
character (len=kchara), dimension(:), allocatable node_monitor_io::monitor_grp
Definition at line 39 of file node_monitor_IO.f90.
Referenced by allocate_monitor_group(), deallocate_monitor_local(), set_control_4_model::s_set_control_4_model(), and set_local_node_id_4_monitor().
monitor_local
integer (kind=kint), dimension(:), allocatable, private node_monitor_io::monitor_local private
Definition at line 42 of file node_monitor_IO.f90.
Referenced by allocate_monitor_local(), deallocate_monitor_local(), output_nodal_monitor_data(), and set_local_node_id_4_monitor().
node_monitor_head
character(len=kchara), parameter, private node_monitor_io::node_monitor_head = 'node' private
Definition at line 36 of file node_monitor_IO.f90.
Referenced by open_node_monitor_file().
ntot_comp_monitor
integer (kind = kint) node_monitor_io::ntot_comp_monitor
Definition at line 45 of file node_monitor_IO.f90.
Referenced by set_control_sph_mhd::set_control_sph_mhd_w_viz(), and skip_monitor_data().
num_comp_phys_monitor
integer (kind = kint), dimension(:), allocatable, private node_monitor_io::num_comp_phys_monitor private
Definition at line 46 of file node_monitor_IO.f90.
Referenced by open_node_monitor_file().
num_field_monitor
integer (kind = kint) node_monitor_io::num_field_monitor
Definition at line 44 of file node_monitor_IO.f90.
Referenced by open_node_monitor_file(), and set_control_sph_mhd::set_control_sph_mhd_w_viz().
num_monitor
integer (kind=kint) node_monitor_io::num_monitor
Definition at line 38 of file node_monitor_IO.f90.
Referenced by allocate_monitor_group(), output_monitor_control(), set_control_4_model::s_set_control_4_model(), set_local_node_id_4_monitor(), and skip_monitor_data().
num_monitor_local
integer (kind=kint), private node_monitor_io::num_monitor_local private
Definition at line 41 of file node_monitor_IO.f90.
Referenced by allocate_monitor_local(), open_node_monitor_file(), output_monitor_control(), output_nodal_monitor_data(), set_local_node_id_4_monitor(), and skip_monitor_data().
phys_name_monitor
character (len = kchara), dimension(:), allocatable, private node_monitor_io::phys_name_monitor private
Definition at line 47 of file node_monitor_IO.f90.
Referenced by open_node_monitor_file().