CALYPSO: copy_nodal_fields Module Reference
copy_nodal_fields Module Reference
Functions/Subroutines
subroutine clear_field_data (fld, numdir, i_target)
subroutine copy_scalar_component (fld, i_org, i_target)
subroutine copy_vector_component (fld, i_org, i_target)
subroutine copy_tensor_component (fld, i_org, i_target)
subroutine add_2_nod_scalars (fld, i_v1, i_v2, i_r)
subroutine add_2_nod_vectors (fld, i_v1, i_v2, i_r)
subroutine add_2_nod_tensors (fld, i_v1, i_v2, i_r)
subroutine subtract_2_nod_scalars (fld, i_v1, i_v2, i_r)
subroutine subtract_2_nod_vectors (fld, i_v1, i_v2, i_r)
subroutine subtract_2_nod_tensors (fld, i_v1, i_v2, i_r)
Function/Subroutine Documentation
add_2_nod_scalars()
subroutine copy_nodal_fields::add_2_nod_scalars (type(phys_data), intent(inout) fld, integer(kind = kint), intent(in) i_v1, integer(kind = kint), intent(in) i_v2, integer(kind = kint), intent(in) i_r)
Definition at line 118 of file copy_nodal_fields.f90.
References cal_add_smp::add_scalars_smp().
add_2_nod_tensors()
subroutine copy_nodal_fields::add_2_nod_tensors (type(phys_data), intent(inout) fld, integer(kind = kint), intent(in) i_v1, integer(kind = kint), intent(in) i_v2, integer(kind = kint), intent(in) i_r)
Definition at line 152 of file copy_nodal_fields.f90.
References cal_add_smp::add_tensors_smp().
add_2_nod_vectors()
subroutine copy_nodal_fields::add_2_nod_vectors (type(phys_data), intent(inout) fld, integer(kind = kint), intent(in) i_v1, integer(kind = kint), intent(in) i_v2, integer(kind = kint), intent(in) i_r)
Definition at line 135 of file copy_nodal_fields.f90.
References cal_add_smp::add_vectors_smp().
Referenced by cal_energy_flux_rj::s_cal_energy_flux_rj().
clear_field_data()
subroutine copy_nodal_fields::clear_field_data (type(phys_data), intent(inout) fld, integer (kind = kint), intent(in) numdir, integer (kind = kint), intent(in) i_target)
Definition at line 48 of file copy_nodal_fields.f90.
References delete_field_smp::delete_phys_data_smp().
Referenced by cal_nonlinear::licv_exp(), cal_div_of_forces::sum_div_of_forces(), and sum_rotation_of_forces::sum_forces_to_explicit().
copy_scalar_component()
subroutine copy_nodal_fields::copy_scalar_component (type(phys_data), intent(inout) fld, integer (kind = kint), intent(in) i_org, integer (kind = kint), intent(in) i_target)
Definition at line 66 of file copy_nodal_fields.f90.
References copy_field_smp::copy_nod_scalar_smp().
Referenced by copy_field_data_4_dt_check::s_copy_field_data_for_dt_check().
copy_tensor_component()
subroutine copy_nodal_fields::copy_tensor_component (type(phys_data), intent(inout) fld, integer (kind = kint), intent(in) i_org, integer (kind = kint), intent(in) i_target)
Definition at line 100 of file copy_nodal_fields.f90.
References copy_field_smp::copy_nod_sym_tensor_smp().
copy_vector_component()
subroutine copy_nodal_fields::copy_vector_component (type(phys_data), intent(inout) fld, integer (kind = kint), intent(in) i_org, integer (kind = kint), intent(in) i_target)
Definition at line 83 of file copy_nodal_fields.f90.
References copy_field_smp::copy_nod_vector_smp().
Referenced by copy_field_data_4_dt_check::s_copy_field_data_for_dt_check().
subtract_2_nod_scalars()
subroutine copy_nodal_fields::subtract_2_nod_scalars (type(phys_data), intent(inout) fld, integer(kind = kint), intent(in) i_v1, integer(kind = kint), intent(in) i_v2, integer(kind = kint), intent(in) i_r)
Definition at line 170 of file copy_nodal_fields.f90.
References cal_subtract_smp::subtract_scalars_smp().
subtract_2_nod_tensors()
subroutine copy_nodal_fields::subtract_2_nod_tensors (type(phys_data), intent(inout) fld, integer(kind = kint), intent(in) i_v1, integer(kind = kint), intent(in) i_v2, integer(kind = kint), intent(in) i_r)
Definition at line 204 of file copy_nodal_fields.f90.
References cal_subtract_smp::subtract_tensors_smp().
subtract_2_nod_vectors()
subroutine copy_nodal_fields::subtract_2_nod_vectors (type(phys_data), intent(inout) fld, integer(kind = kint), intent(in) i_v1, integer(kind = kint), intent(in) i_v2, integer(kind = kint), intent(in) i_r)
Definition at line 187 of file copy_nodal_fields.f90.
References cal_subtract_smp::subtract_vectors_smp().