CALYPSO: count_overlap Module Reference
count_overlap Module Reference
Check overlapped element.
Functions/Subroutines
integer(kind=kint) function count_interier_element (internal_node, numele, ie)
subroutine set_overlap_flag (np_smp, inum_smp_stack, internal_node, numele, ie, internal_n, interior_flag)
subroutine set_original_domiain_by_comm (id_rank, nnod, num_neib, ntot_import, id_neib, istack_import, item_import, idomain_nod)
subroutine set_original_domiain_by_node (nnod, nele, ie, idomain_nod, idomain_ele)
Detailed Description
Check overlapped element.
      integer(kind = kint) function count_interier_element            &
     &                            (internal_node, numele, ie)
      subroutine set_overlap_flag(np_smp, inum_smp_stack,             &
     &          internal_node, numele, ie, internal_n, interior_flag)
      subroutine set_original_domiain_by_comm(id_rank, nnod,          &
     &          num_neib, ntot_import, id_neib, istack_import,        &
     &          item_import, idomain_nod)
      subroutine set_original_domiain_by_node(nnod, nele, ie,         &
     &          idomain_nod, idomain_ele)
Function/Subroutine Documentation
count_interier_element()
integer(kind = kint) function count_overlap::count_interier_element (integer(kind = kint), intent(in) internal_node, integer(kind = kint), intent(in) numele, integer(kind = kint), dimension(numele,1), intent(in) ie)
Definition at line 34 of file count_overlap.f90.
Referenced by set_and_cal_udt_data::const_udt_global_connect(), and set_and_cal_udt_data::const_udt_local_connect().
set_original_domiain_by_comm()
subroutine count_overlap::set_original_domiain_by_comm (integer, intent(in) id_rank, integer(kind = kint), intent(in) nnod, integer(kind = kint), intent(in) num_neib, integer(kind = kint), intent(in) ntot_import, integer(kind = kint), dimension(num_neib), intent(in) id_neib, integer(kind = kint), dimension(0:num_neib), intent(in) istack_import, integer(kind = kint), dimension(ntot_import), intent(in) item_import, integer(kind = kint), dimension(nnod), intent(inout) idomain_nod)
Definition at line 91 of file count_overlap.f90.
set_original_domiain_by_node()
subroutine count_overlap::set_original_domiain_by_node (integer(kind = kint), intent(in) nnod, integer(kind = kint), intent(in) nele, integer(kind = kint), dimension(nele,1), intent(in) ie, integer(kind = kint), dimension(nnod), intent(in) idomain_nod, integer(kind = kint), dimension(nele), intent(inout) idomain_ele)
Definition at line 126 of file count_overlap.f90.
set_overlap_flag()
subroutine count_overlap::set_overlap_flag (integer(kind = kint), intent(in) np_smp, integer(kind = kint), dimension(0:np_smp), intent(in) inum_smp_stack, integer(kind = kint), intent(in) internal_node, integer(kind = kint), intent(in) numele, integer(kind = kint), dimension(numele,1), intent(in) ie, integer(kind = kint), intent(inout) internal_n, integer(kind = kint), dimension(numele), intent(inout) interior_flag)
Definition at line 55 of file count_overlap.f90.
Referenced by set_size_4_smp_types::count_overlap_edge(), set_size_4_smp_types::count_overlap_ele(), and set_size_4_smp_types::count_overlap_surf().