CALYPSO: gz_vtk_file_mpi_io Module Reference
gz_vtk_file_mpi_io Module Reference
Output merged VTK file usging MPI-IO.
Functions/Subroutines
subroutine gz_write_vtk_data_mpi (id_vtk, ioff_gl, nnod, num_field, ntot_comp, ncomp_field, field_name, d_nod, istack_merged_intnod)
subroutine gz_write_vtk_mesh_mpi (id_vtk, ioff_gl, nnod, nele, nnod_ele, xx, ie, istack_merged_intnod, istack_merged_ele)
subroutine gz_write_vtk_header_mpi (id_vtk, ioff_gl, header_txt)
subroutine, private gz_write_vtk_scalar_mpi (id_vtk, ioff_gl, nnod, vect, istack_merged_intnod)
subroutine, private gz_write_vtk_vecotr_mpi (id_vtk, ioff_gl, nnod, vect, istack_merged_intnod)
subroutine, private gz_write_vtk_tensor_mpi (id_vtk, ioff_gl, nnod, vect, istack_merged_intnod)
Detailed Description
Output merged VTK file usging MPI-IO.
      subroutine gz_write_vtk_data_mpi(id_vtk, ioff_gl,               &
     &          nnod, num_field, ntot_comp, ncomp_field,              &
     &          field_name, d_nod, istack_merged_intnod)
      subroutine gz_write_vtk_mesh_mpi(id_vtk, ioff_gl,               &
     &          nnod, nele, nnod_ele, xx, ie,                         &
     &          istack_merged_intnod, istack_merged_ele)
Function/Subroutine Documentation
gz_write_vtk_data_mpi()
subroutine gz_vtk_file_mpi_io::gz_write_vtk_data_mpi (integer, intent(in) id_vtk, integer(kind = kint_gl), intent(inout) ioff_gl, integer(kind=kint_gl), intent(in) nnod, integer(kind=kint), intent(in) num_field, integer(kind=kint), intent(in) ntot_comp, integer(kind=kint), dimension(num_field), intent(in) ncomp_field, character(len=kchara), dimension(num_field), intent(in) field_name, real(kind = kreal), dimension(nnod,ntot_comp), intent(in) d_nod, integer(kind = kint_gl), dimension(0:nprocs), intent(in) istack_merged_intnod)
Definition at line 39 of file gz_vtk_file_MPI_IO.f90.
References gz_write_vtk_header_mpi(), gz_write_vtk_scalar_mpi(), gz_write_vtk_tensor_mpi(), gz_write_vtk_vecotr_mpi(), m_phys_constants::n_scalar, m_phys_constants::n_sym_tensor, m_phys_constants::n_vector, calypso_mpi::nprocs, vtk_data_to_buffer::vtk_fields_head(), vtk_data_to_buffer::vtk_scalar_head(), vtk_data_to_buffer::vtk_tensor_head(), and vtk_data_to_buffer::vtk_vector_head().
Referenced by gz_merged_udt_vtk_file_io::gz_write_vtk_file_mpi(), and gz_merged_udt_vtk_file_io::gz_write_vtk_phys_mpi().
gz_write_vtk_header_mpi()
subroutine gz_vtk_file_mpi_io::gz_write_vtk_header_mpi (integer, intent(in) id_vtk, integer(kind = kint_gl), intent(inout) ioff_gl, character(len=*), intent(in) header_txt)
Definition at line 161 of file gz_vtk_file_MPI_IO.f90.
References calypso_mpi_int8::calypso_mpi_bcast_one_int8(), m_calypso_mpi_io::calypso_mpi_seek_write_gz(), t_buffer_4_gzip::dealloc_zip_buffer(), zlib_convert_text::defleate_characters(), and calypso_mpi::my_rank.
Referenced by gz_ucd_file_mpi_io::gz_write_ucd_data_mpi(), gz_ucd_file_mpi_io::gz_write_ucd_mesh_mpi(), gz_write_vtk_data_mpi(), and gz_write_vtk_mesh_mpi().
gz_write_vtk_mesh_mpi()
subroutine gz_vtk_file_mpi_io::gz_write_vtk_mesh_mpi (integer, intent(in) id_vtk, integer(kind = kint_gl), intent(inout) ioff_gl, integer(kind = kint_gl), intent(in) nnod, integer(kind = kint_gl), intent(in) nele, integer(kind = kint), intent(in) nnod_ele, real(kind = kreal), dimension(nnod,3), intent(in) xx, integer(kind = kint_gl), dimension(nele,nnod_ele), intent(in) ie, integer(kind = kint_gl), dimension(0:nprocs), intent(in) istack_merged_intnod, integer(kind = kint_gl), dimension(0:nprocs), intent(in) istack_merged_ele)
Definition at line 102 of file gz_vtk_file_MPI_IO.f90.
References m_calypso_mpi_io::calypso_gz_mpi_seek_write(), t_buffer_4_gzip::dealloc_zip_buffer(), zlib_cvt_vtk_data::defleate_vtk_celltype(), zlib_cvt_vtk_data::defleate_vtk_connect(), gz_write_vtk_header_mpi(), gz_write_vtk_vecotr_mpi(), calypso_mpi::nprocs, vtk_data_to_buffer::vtk_cell_type_head(), vtk_data_to_buffer::vtk_connect_head(), and vtk_data_to_buffer::vtk_node_head().
Referenced by gz_merged_udt_vtk_file_io::gz_write_vtk_file_mpi(), and gz_merged_udt_vtk_file_io::gz_write_vtk_grid_mpi().
gz_write_vtk_scalar_mpi()
subroutine, private gz_vtk_file_mpi_io::gz_write_vtk_scalar_mpi (integer, intent(in) id_vtk, integer(kind = kint_gl), intent(inout) ioff_gl, integer(kind = kint_gl), intent(in) nnod, real(kind = kreal), dimension(nnod), intent(in) vect, integer(kind = kint_gl), dimension(0:nprocs), intent(in) istack_merged_intnod) private
Definition at line 190 of file gz_vtk_file_MPI_IO.f90.
References m_calypso_mpi_io::calypso_gz_mpi_seek_write(), t_buffer_4_gzip::dealloc_zip_buffer(), zlib_cvt_vtk_data::defleate_vtk_scalar(), and calypso_mpi::my_rank.
Referenced by gz_write_vtk_data_mpi().
gz_write_vtk_tensor_mpi()
subroutine, private gz_vtk_file_mpi_io::gz_write_vtk_tensor_mpi (integer, intent(in) id_vtk, integer(kind = kint_gl), intent(inout) ioff_gl, integer(kind = kint_gl), intent(in) nnod, real(kind = kreal), dimension(nnod,6), intent(in) vect, integer(kind = kint_gl), dimension(0:nprocs), intent(in) istack_merged_intnod) private
Definition at line 249 of file gz_vtk_file_MPI_IO.f90.
References calypso_mpi_int8::calypso_mpi_allgather_one_int8(), m_calypso_mpi_io::calypso_mpi_seek_write_gz(), t_buffer_4_gzip::dealloc_zip_buffer(), zlib_cvt_vtk_data::defleate_vtk_tensor(), calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by gz_write_vtk_data_mpi().
gz_write_vtk_vecotr_mpi()
subroutine, private gz_vtk_file_mpi_io::gz_write_vtk_vecotr_mpi (integer, intent(in) id_vtk, integer(kind = kint_gl), intent(inout) ioff_gl, integer(kind = kint_gl), intent(in) nnod, real(kind = kreal), dimension(nnod,3), intent(in) vect, integer(kind = kint_gl), dimension(0:nprocs), intent(in) istack_merged_intnod) private
Definition at line 219 of file gz_vtk_file_MPI_IO.f90.
References m_calypso_mpi_io::calypso_gz_mpi_seek_write(), t_buffer_4_gzip::dealloc_zip_buffer(), zlib_cvt_vtk_data::defleate_vtk_vector(), and calypso_mpi::my_rank.
Referenced by gz_write_vtk_data_mpi(), and gz_write_vtk_mesh_mpi().