CALYPSO: gz_node_geometry_io Module Reference
gz_node_geometry_io Module Reference
Node data IO using zlib.
Functions/Subroutines
subroutine gz_write_geometry_info (nod_IO, zbuf)
subroutine gz_write_scalar_in_element (nod_IO, sfed_IO, zbuf)
subroutine gz_write_vector_in_element (nod_IO, sfed_IO, zbuf)
subroutine gz_read_number_of_node (nod_IO, zbuf)
subroutine gz_read_geometry_info (nod_IO, zbuf)
subroutine gz_read_scalar_in_element (nod_IO, sfed_IO, zbuf)
subroutine gz_read_vector_in_element (nod_IO, sfed_IO, zbuf)
Detailed Description
Node data IO using zlib.
      subroutine gz_write_geometry_info(nod_IO, zbuf)
      subroutine gz_write_scalar_in_element(nod_IO, sfed_IO, zbuf)
      subroutine gz_write_vector_in_element(nod_IO, sfed_IO, zbuf)
        type(node_data), intent(in) :: nod_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
        type(buffer_4_gzip) , intent(inout) :: zbuf
      subroutine gz_read_number_of_node(nod_IO, zbuf)
      subroutine gz_read_geometry_info(nod_IO, zbuf)
      subroutine gz_read_scalar_in_element(nod_IO, sfed_IO, zbuf)
      subroutine gz_read_vector_in_element(nod_IO, sfed_IO, zbuf)
        type(node_data), intent(inout) :: nod_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
        type(buffer_4_gzip) , intent(inout) :: zbuf
Function/Subroutine Documentation
gz_read_geometry_info()
subroutine gz_node_geometry_io::gz_read_geometry_info (type(node_data), intent(inout) nod_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 130 of file gz_node_geometry_IO.f90.
References t_geometry_data::alloc_node_geometry_base(), and gzip_file_access::get_one_line_text_from_gz().
Referenced by gz_edge_data_io::gz_read_edge_geometry(), gz_element_data_io::gz_read_element_geometry(), gz_mesh_data_io::gz_read_filter_geometry(), gz_mesh_data_io::gz_read_num_node_ele(), and gz_surface_data_io::gz_read_surface_geometry().
gz_read_number_of_node()
subroutine gz_node_geometry_io::gz_read_number_of_node (type(node_data), intent(inout) nod_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 115 of file gz_node_geometry_IO.f90.
References skip_gz_comment::skip_gz_comment_int().
Referenced by gz_edge_data_io::gz_read_edge_geometry(), gz_element_data_io::gz_read_element_geometry(), gz_mesh_data_io::gz_read_filter_geometry(), gz_mesh_data_io::gz_read_num_node(), and gz_surface_data_io::gz_read_surface_geometry().
gz_read_scalar_in_element()
subroutine gz_node_geometry_io::gz_read_scalar_in_element (type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 152 of file gz_node_geometry_IO.f90.
References t_surf_edge_io::alloc_ele_scalar_io(), gzip_file_access::get_one_line_text_from_gz(), and skip_gz_comment::skip_gz_comment_int().
Referenced by gz_edge_data_io::gz_read_edge_geometry(), gz_element_data_io::gz_read_element_geometry(), and gz_surface_data_io::gz_read_surface_geometry().
gz_read_vector_in_element()
subroutine gz_node_geometry_io::gz_read_vector_in_element (type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 177 of file gz_node_geometry_IO.f90.
References t_surf_edge_io::alloc_ele_vector_io(), gzip_file_access::get_one_line_text_from_gz(), and skip_gz_comment::skip_gz_comment_int().
Referenced by gz_edge_data_io::gz_read_edge_geometry(), and gz_surface_data_io::gz_read_surface_geometry().
gz_write_geometry_info()
subroutine gz_node_geometry_io::gz_write_geometry_info (type(node_data), intent(in) nod_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 42 of file gz_node_geometry_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf().
Referenced by gz_edge_data_io::gz_write_edge_geometry(), gz_element_data_io::gz_write_element_geometry(), gz_mesh_data_io::gz_write_filter_geometry(), gz_mesh_data_io::gz_write_geometry_data(), and gz_surface_data_io::gz_write_surface_geometry().
gz_write_scalar_in_element()
subroutine gz_node_geometry_io::gz_write_scalar_in_element (type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 66 of file gz_node_geometry_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf().
Referenced by gz_edge_data_io::gz_write_edge_geometry(), gz_element_data_io::gz_write_element_geometry(), and gz_surface_data_io::gz_write_surface_geometry().
gz_write_vector_in_element()
subroutine gz_node_geometry_io::gz_write_vector_in_element (type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 90 of file gz_node_geometry_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf().
Referenced by gz_edge_data_io::gz_write_edge_geometry(), and gz_surface_data_io::gz_write_surface_geometry().