CALYPSO: cal_sph_exp_center Module Reference
cal_sph_exp_center Module Reference
Set center fields by explicit method.
Functions/Subroutines
subroutine cal_sph_fixed_center (inod_rj_center, CTR_fld, is_fld, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_center1_grad22 (jmax, r_CTR1, g_sph_rj, fdm2_fix_fld_ctr1, is_fld, is_grd, n_point, ntot_phys_rj, d_rj)
subroutine sph0_scalar_fill_ctr_grad2 (inod_rj_center, idx_rj_degree_zero, jmax, fdm2_fix_fld_ctr1, is_fld, is_grd, n_point, ntot_phys_rj, d_rj)
subroutine dsdr_sph_lm0_fixed_ctr_2 (inod_rj_center, idx_rj_degree_zero, jmax, r_CTR1, g_sph_rj, d_center, fdm2_fix_fld_ctr1, fdm2_fixed_center, is_fld, is_grd, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_div_flux_4_fix_ctr (jmax, r_CTR1, g_sph_rj, fix_ICB, fdm2_fix_fld_ctr1, is_fld, is_div, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_fixed_center1_diffuse2 (jmax, r_CTR1, g_sph_rj, fdm2_fix_fld_ctr1, fix_CTR, coef_d, is_fld, is_diffuse, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_filled_center_diffuse2 (inod_rj_center, idx_rj_degree_zero, jmax, r_CTR1, g_sph_rj, fdm2_fix_fld_ctr1, fdm2_fix_dr_center, coef_d, is_fld, is_diffuse, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_fixed_center_diffuse2 (inod_rj_center, idx_rj_degree_zero, is_diffuse, n_point, ntot_phys_rj, d_rj)
Detailed Description
Set center fields by explicit method.
      subroutine cal_sph_fixed_center(inod_rj_center, CTR_fld, is_fld,&
     &          n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_center1_grad22(jmax, r_CTR1, g_sph_rj,       &
     &          fdm2_fix_fld_ctr1, is_fld, is_grd,                    &
     &          n_point, ntot_phys_rj, d_rj)
      subroutine sph0_scalar_fill_ctr_grad2                           &
     &         (inod_rj_center, idx_rj_degree_zero, jmax,             &
     &          fdm2_fix_fld_ctr1, is_fld, is_grd,                    &
     &          n_point, ntot_phys_rj, d_rj)
      subroutine dsdr_sph_lm0_fixed_ctr_2                             &
     &        (inod_rj_center, idx_rj_degree_zero, jmax, r_CTR1,      &
     &         g_sph_rj, d_center, fdm2_fix_fld_ctr1,                 &
     &         fdm2_fixed_center, is_fld, is_grd,                     &
     &         n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_div_flux_4_fix_ctr(jmax, r_CTR1, g_sph_rj,   &
     &          fix_ICB, fdm2_fix_fld_ctr1, is_fld, is_div,           &
     &          n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_fixed_center1_diffuse2(jmax, r_CTR1,         &
     &          g_sph_rj, fdm2_fix_fld_ctr1, fix_CTR, coef_d,         &
     &          is_fld, is_diffuse, n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_filled_center_diffuse2                       &
     &         (inod_rj_center, idx_rj_degree_zero, jmax, r_CTR1,     &
     &          g_sph_rj, fdm2_fix_fld_ctr1, fdm2_fix_dr_center,      &
     &          coef_d, is_fld, is_diffuse,                           &
     &          n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_fixed_center_diffuse2                        &
     &          (inod_rj_center, idx_rj_degree_zero,                  &
     &           is_diffuse, n_point, ntot_phys_rj, d_rj)
Parameters
inod_rj_center Local address for center
idx_rj_degree_zero Local address for degree 0
jmax Number of local spherical harmonics mode
r_CTR1(0:2) Radius at innermost point
fdm2_fix_fld_ctr1(-1:1,3) Matrix to evaluate radial derivative for center with fixed field
fdm2_fixed_center(0:2,3) Matrix to evaluate radial derivative for center with fixed field
fix_CTR(jmax) Spectr data for fixed scalar at center
coef_d Coefficient for diffusion term
Parameters
is_fld Field address of input field
is_grd Field address of radial gradient of field
is_diffuse Field address for diffusion of field
Function/Subroutine Documentation
cal_sph_center1_grad22()
subroutine cal_sph_exp_center::cal_sph_center1_grad22 (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(0:2), intent(in) r_CTR1, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_fix_fld_ctr1, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_grd, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 90 of file cal_sph_exp_center.f90.
References m_constants::zero.
Referenced by select_exp_scalar_icb::sel_icb_radial_grad_scalar().
cal_sph_div_flux_4_fix_ctr()
subroutine cal_sph_exp_center::cal_sph_div_flux_4_fix_ctr (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(0:2), intent(in) r_CTR1, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, real(kind = kreal), dimension(jmax), intent(in) fix_ICB, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_fix_fld_ctr1, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_div, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 213 of file cal_sph_exp_center.f90.
References m_constants::half.
Referenced by select_exp_scalar_icb::sel_icb_sph_scalar_advect().
cal_sph_filled_center_diffuse2()
subroutine cal_sph_exp_center::cal_sph_filled_center_diffuse2 (integer(kind = kint), intent(in) inod_rj_center, integer(kind = kint), intent(in) idx_rj_degree_zero, integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(0:2), intent(in) r_CTR1, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_fix_fld_ctr1, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_fix_dr_center, real(kind = kreal), intent(in) coef_d, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_diffuse, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 290 of file cal_sph_exp_center.f90.
References m_constants::two.
Referenced by select_exp_scalar_icb::sel_icb_sph_scalar_advect(), and select_exp_scalar_icb::sel_icb_sph_scalar_diffusion().
cal_sph_fixed_center()
subroutine cal_sph_exp_center::cal_sph_fixed_center (integer(kind = kint), intent(in) inod_rj_center, real(kind = kreal), intent(in) CTR_fld, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 72 of file cal_sph_exp_center.f90.
Referenced by select_exp_scalar_icb::set_icb_scalar_sph_crank().
cal_sph_fixed_center1_diffuse2()
subroutine cal_sph_exp_center::cal_sph_fixed_center1_diffuse2 (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(0:2), intent(in) r_CTR1, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_fix_fld_ctr1, real(kind = kreal), dimension(jmax), intent(in) fix_CTR, real(kind = kreal), intent(in) coef_d, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_diffuse, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 249 of file cal_sph_exp_center.f90.
References m_constants::two.
Referenced by select_exp_scalar_icb::sel_icb_sph_scalar_diffusion().
cal_sph_fixed_center_diffuse2()
subroutine cal_sph_exp_center::cal_sph_fixed_center_diffuse2 (integer(kind = kint), intent(in) inod_rj_center, integer(kind = kint), intent(in) idx_rj_degree_zero, integer(kind = kint), intent(in) is_diffuse, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 355 of file cal_sph_exp_center.f90.
Referenced by select_exp_scalar_icb::sel_icb_sph_scalar_advect(), and select_exp_scalar_icb::sel_icb_sph_scalar_diffusion().
dsdr_sph_lm0_fixed_ctr_2()
subroutine cal_sph_exp_center::dsdr_sph_lm0_fixed_ctr_2 (integer(kind = kint), intent(in) inod_rj_center, integer(kind = kint), intent(in) idx_rj_degree_zero, integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(0:2), intent(in) r_CTR1, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, real(kind = kreal), intent(in) d_center, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_fix_fld_ctr1, real(kind = kreal), dimension(0:2,3), intent(in) fdm2_fixed_center, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_grd, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 163 of file cal_sph_exp_center.f90.
References m_constants::zero.
Referenced by select_exp_scalar_icb::sel_icb_radial_grad_scalar().
sph0_scalar_fill_ctr_grad2()
subroutine cal_sph_exp_center::sph0_scalar_fill_ctr_grad2 (integer(kind = kint), intent(in) inod_rj_center, integer(kind = kint), intent(in) idx_rj_degree_zero, integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_fix_fld_ctr1, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_grd, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 124 of file cal_sph_exp_center.f90.
References m_constants::zero.
Referenced by select_exp_scalar_icb::sel_icb_radial_grad_scalar().