CALYPSO: t_sph_center_matrix Module Reference
t_sph_center_matrix Module Reference
structures of radial matrix
Functions/Subroutines
subroutine alloc_ctr_band_mat (nband, sph_rj, smat)
subroutine set_unit_ctr_single_mat (smat)
subroutine ludcmp_3band_ctr (smat)
subroutine ludcmp_5band_ctr (smat)
subroutine ludcmp_7band_ctr (smat)
subroutine lubksb_3band_ctr (smat, x)
subroutine lubksb_5band_ctr (smat, x)
subroutine lubksb_7band_ctr (smat, x)
subroutine check_center_band_matrix (id_rank, sph_rj, smat)
Detailed Description
structures of radial matrix
      subroutine alloc_ctr_band_mat(nband, sph_rj, smat)
      subroutine set_unit_ctr_single_mat(smat)
      subroutine ludcmp_3band_ctr(smat)
      subroutine ludcmp_5band_ctr(smat)
      subroutine ludcmp_7band_ctr(smat)
      subroutine lubksb_3band_ctr(smat, x)
      subroutine lubksb_5band_ctr(smat, x)
      subroutine lubksb_7band_ctr(smat, x)
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(band_matrix_type), intent(inout) :: smat
      subroutine check_center_band_matrix(id_rank, sph_rj, smat)
Function/Subroutine Documentation
alloc_ctr_band_mat()
subroutine t_sph_center_matrix::alloc_ctr_band_mat (integer(kind = kint), intent(in) nband, type(sph_rj_grid), intent(in) sph_rj, type(band_matrix_type), intent(inout) smat)
Definition at line 40 of file t_sph_center_matrix.f90.
Referenced by const_r_mat_w_center_sph::const_rmat_press00_sph(), and const_r_mat_w_center_sph::const_rmat_scalar00_sph().
check_center_band_matrix()
subroutine t_sph_center_matrix::check_center_band_matrix (integer, intent(in) id_rank, type(sph_rj_grid), intent(in) sph_rj, type(band_matrix_type), intent(in) smat)
Definition at line 186 of file t_sph_center_matrix.f90.
References check_sph_radial_mat::check_radial_3band_mat_w_ctr().
Referenced by const_r_mat_w_center_sph::const_rmat_press00_sph(), and const_r_mat_w_center_sph::const_rmat_scalar00_sph().
lubksb_3band_ctr()
subroutine t_sph_center_matrix::lubksb_3band_ctr (type(band_matrix_type), intent(in) smat, real(kind = kreal), dimension(0:smat%n_vect), intent(inout) x)
Definition at line 131 of file t_sph_center_matrix.f90.
References lubksb_357band::lubksb_3band().
Referenced by solve_sph_fluid_crank::solve_scalar_sph_crank().
lubksb_5band_ctr()
subroutine t_sph_center_matrix::lubksb_5band_ctr (type(band_matrix_type), intent(in) smat, real(kind = kreal), dimension(0:smat%n_vect), intent(inout) x)
Definition at line 149 of file t_sph_center_matrix.f90.
References lubksb_357band::lubksb_5band().
lubksb_7band_ctr()
subroutine t_sph_center_matrix::lubksb_7band_ctr (type(band_matrix_type), intent(in) smat, real(kind = kreal), dimension(0:smat%n_vect), intent(inout) x)
Definition at line 167 of file t_sph_center_matrix.f90.
References lubksb_357band::lubksb_7band().
ludcmp_3band_ctr()
subroutine t_sph_center_matrix::ludcmp_3band_ctr (type(band_matrix_type), intent(inout) smat)
Definition at line 82 of file t_sph_center_matrix.f90.
References m_ludcmp_3band::ludcmp_3band().
Referenced by const_r_mat_w_center_sph::const_rmat_press00_sph(), and const_r_mat_w_center_sph::const_rmat_scalar00_sph().
ludcmp_5band_ctr()
subroutine t_sph_center_matrix::ludcmp_5band_ctr (type(band_matrix_type), intent(inout) smat)
Definition at line 98 of file t_sph_center_matrix.f90.
References m_ludcmp_band::ludcmp_band().
ludcmp_7band_ctr()
subroutine t_sph_center_matrix::ludcmp_7band_ctr (type(band_matrix_type), intent(inout) smat)
Definition at line 114 of file t_sph_center_matrix.f90.
References m_ludcmp_band::ludcmp_band().
set_unit_ctr_single_mat()
subroutine t_sph_center_matrix::set_unit_ctr_single_mat (type(band_matrix_type), intent(inout) smat)
Definition at line 67 of file t_sph_center_matrix.f90.
Referenced by const_r_mat_w_center_sph::const_rmat_scalar00_sph().