CALYPSO: input_old_file_sel_4_zlib Module Reference
input_old_file_sel_4_zlib Module Reference
Selector for old restart data reading.
Functions/Subroutines
subroutine sel_read_alloc_field_file (id_rank, istep_fld, file_IO, fld_IO)
subroutine sel_read_rst_file (id_rank, istep_fld, file_IO, t_IO, fld_IO)
subroutine sel_read_rst_comps (id_rank, istep_fld, file_IO, t_IO, fld_IO)
Detailed Description
Selector for old restart data reading.
      subroutine sel_read_alloc_field_file                            &
     &         (id_rank, istep_fld, file_IO, fld_IO)
      subroutine sel_read_rst_file                                    &
     &         (id_rank, istep_fld, file_IO, t_IO, fld_IO)
      subroutine sel_read_rst_comps                                   &
     &         (id_rank, istep_fld, file_IO, t_IO, fld_IO)
        type(field_IO_params), intent(in) :: file_IO
        type(time_data), intent(inout) :: t_IO
        type(field_IO), intent(inout) :: fld_IO
Function/Subroutine Documentation
sel_read_alloc_field_file()
subroutine input_old_file_sel_4_zlib::sel_read_alloc_field_file (integer, intent(in) id_rank, integer(kind = kint), intent(in) istep_fld, type(field_io_params), intent(in) file_IO, type(field_io), intent(inout) fld_IO)
Definition at line 46 of file input_old_file_sel_4_zlib.F90.
References m_file_format_switch::id_gzip_txt_file_fmt, gz_field_file_io::read_alloc_gz_field_file(), field_file_io::read_and_allocate_field_file(), and set_field_file_names::set_fem_fld_file_name().
Referenced by new_sph_restart::load_old_fmt_sph_data().
sel_read_rst_comps()
subroutine input_old_file_sel_4_zlib::sel_read_rst_comps (integer, intent(in) id_rank, integer(kind = kint), intent(in) istep_fld, type(field_io_params), intent(in) file_IO, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO)
Definition at line 116 of file input_old_file_sel_4_zlib.F90.
References set_parallel_file_name::add_elaps_postfix(), set_parallel_file_name::add_int_suffix(), set_parallel_file_name::add_process_id(), m_file_format_switch::id_gzip_txt_file_fmt, gz_rst_data_io_by_fld::read_gz_rst_comps(), and rst_data_io_by_fld::read_rst_data_comps().
sel_read_rst_file()
subroutine input_old_file_sel_4_zlib::sel_read_rst_file (integer, intent(in) id_rank, integer(kind = kint), intent(in) istep_fld, type(field_io_params), intent(in) file_IO, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO)
Definition at line 77 of file input_old_file_sel_4_zlib.F90.
References set_parallel_file_name::add_elaps_postfix(), set_parallel_file_name::add_int_suffix(), set_parallel_file_name::add_process_id(), m_file_format_switch::id_gzip_txt_file_fmt, gz_rst_data_io_by_fld::read_gz_rst_file(), and rst_data_io_by_fld::read_rst_file().