CALYPSO: cal_minmax_and_stacks Module Reference
cal_minmax_and_stacks Module Reference
Functions/Subroutines
subroutine cal_divide_and_rest (i_quot, i_rest, i_org, i_divide)
subroutine set_number_of_segments (i_divide, i_quot, i_rest, num_l)
subroutine set_stack_of_segments (i_divide, i_quot, i_rest, istart, istack)
subroutine s_cal_numbers_from_stack (num, num_grp, istack_grp)
subroutine s_cal_total_and_stacks (num, num_grp, istack_begin, istack_grp, ntot_grp)
subroutine s_cal_minmax_and_stacks (num, num_grp, istack_begin, istack_grp, ntot_grp, max_grp, min_grp)
subroutine s_cal_dbl_minmax_and_stacks (num_out, num_in, num_grp, istack_begin, istack_grp, ntot_grp, max_grp, min_grp)
subroutine count_number_4_smp (np_smp, istart, iend, i_smp_stack, max_4_smp)
subroutine set_group_size_4_smp (np_smp, num_group, istack_group, istack_group_smp, max_4_smp)
Function/Subroutine Documentation
cal_divide_and_rest()
subroutine cal_minmax_and_stacks::cal_divide_and_rest (integer(kind= kint), intent(inout) i_quot, integer(kind= kint), intent(inout) i_rest, integer(kind= kint), intent(in) i_org, integer(kind= kint), intent(in) i_divide)
Definition at line 49 of file cal_minmax_and_stacks.f90.
Referenced by count_number_4_smp().
count_number_4_smp()
subroutine cal_minmax_and_stacks::count_number_4_smp (integer(kind = kint), intent(in) np_smp, integer(kind = kint), intent(in) istart, integer(kind = kint), intent(in) iend, integer(kind = kint), dimension(0:np_smp), intent(inout) i_smp_stack, integer(kind = kint), intent(inout) max_4_smp)
Definition at line 217 of file cal_minmax_and_stacks.f90.
References cal_divide_and_rest(), and set_stack_of_segments().
Referenced by set_size_4_smp_types::count_edge_size_smp_type(), set_size_4_smp_types::count_ele_4_smp_mesh_type(), set_size_4_smp_types::count_node_4_smp_mesh_type(), set_psf_nodes_4_by_surf_grp::count_node_at_node_on_grp(), set_psf_patch_4_by_surf_grp::count_num_patch_4_grp(), count_num_sph_smp::count_num_rj_smp(), count_num_sph_smp::count_num_rlm_smp(), count_num_sph_smp::count_num_rtm_smp(), count_num_sph_smp::count_num_rtp_smp(), set_nodal_field_for_psf::count_position_4_psf(), set_psf_nodes_4_by_surf_grp::count_position_4_psf_grp(), set_size_4_smp_types::count_surf_size_smp_type(), pole_sph_transform::init_pole_grids(), init_sph_trans::set_blocks_4_leg_trans(), t_control_1d_layering::set_group_by_equidivide(), and set_group_size_4_smp().
s_cal_dbl_minmax_and_stacks()
subroutine cal_minmax_and_stacks::s_cal_dbl_minmax_and_stacks (integer(kind = kint), intent(in) num_out, integer(kind = kint), intent(in) num_in, integer(kind = kint), dimension(num_in*num_out), intent(in) num_grp, integer(kind = kint), intent(in) istack_begin, integer(kind = kint), dimension(0:num_in*num_out), intent(inout) istack_grp, integer(kind = kint), intent(inout) ntot_grp, integer(kind = kint), intent(inout) max_grp, integer(kind = kint), intent(inout) min_grp)
Definition at line 177 of file cal_minmax_and_stacks.f90.
References s_cal_minmax_and_stacks().
s_cal_minmax_and_stacks()
subroutine cal_minmax_and_stacks::s_cal_minmax_and_stacks (integer(kind = kint), intent(in) num, integer(kind = kint), dimension(num), intent(in) num_grp, integer(kind = kint), intent(in) istack_begin, integer(kind = kint), dimension(0:num), intent(inout) istack_grp, integer(kind = kint), intent(inout) ntot_grp, integer(kind = kint), intent(inout) max_grp, integer(kind = kint), intent(inout) min_grp)
Definition at line 146 of file cal_minmax_and_stacks.f90.
Referenced by t_belonged_element_4_node::belonged_edge_id_4_node(), t_belonged_element_4_node::belonged_ele_id_4_node(), t_belonged_element_4_node::belonged_surf_id_4_node(), set_ele_id_4_node_type::const_next_nod_id_4_node(), s_cal_dbl_minmax_and_stacks(), set_ele_id_4_node_type::set_edge_id_4_node(), set_ele_id_4_node_type::set_ele_id_4_node(), set_ele_id_4_node_type::set_grouped_ele_id_4_node(), set_ele_id_4_node_type::set_layerd_ele_id_4_node(), and set_ele_id_4_node_type::set_surf_id_4_node().
s_cal_numbers_from_stack()
subroutine cal_minmax_and_stacks::s_cal_numbers_from_stack (integer(kind = kint), intent(in) num, integer(kind = kint), dimension(num), intent(inout) num_grp, integer(kind = kint), dimension(0:num), intent(in) istack_grp)
Definition at line 104 of file cal_minmax_and_stacks.f90.
Referenced by t_comm_table::copy_export_table_type(), t_comm_table::copy_import_table_type(), load_mesh_data::input_mesh(), share_field_data::share_field_io_names(), and share_field_data::share_phys_field_names().
s_cal_total_and_stacks()
subroutine cal_minmax_and_stacks::s_cal_total_and_stacks (integer(kind = kint), intent(in) num, integer(kind = kint), dimension(num), intent(in) num_grp, integer(kind = kint), intent(in) istack_begin, integer(kind = kint), dimension(0:num), intent(inout) istack_grp, integer(kind = kint), intent(inout) ntot_grp)
Definition at line 123 of file cal_minmax_and_stacks.f90.
Referenced by set_ucd_data_to_type::alloc_phys_name_type_by_output(), set_fem_mesh_4_sph::const_fem_groups_for_sph(), const_comm_tbl_4_sph_mesh::count_export_4_sph_mesh(), and const_comm_tbl_4_sph_mesh::count_import_4_sph_mesh().
set_group_size_4_smp()
subroutine cal_minmax_and_stacks::set_group_size_4_smp (integer(kind = kint), intent(in) np_smp, integer(kind = kint), intent(in) num_group, integer(kind = kint), dimension(0:num_group), intent(in) istack_group, integer(kind = kint), dimension(0:np_smp*num_group), intent(inout) istack_group_smp, integer(kind = kint), intent(inout) max_4_smp)
Definition at line 239 of file cal_minmax_and_stacks.f90.
References count_number_4_smp().
Referenced by set_smp_4_group_types::count_grp_type_smp(), set_smp_4_group_types::count_surf_grp_type_smp(), and set_connects_4_surf_group::set_node_4_surf_group().
set_number_of_segments()
subroutine cal_minmax_and_stacks::set_number_of_segments (integer(kind= kint), intent(in) i_divide, integer(kind= kint), intent(in) i_quot, integer(kind= kint), intent(in) i_rest, integer(kind= kint), dimension(i_divide), intent(inout) num_l)
Definition at line 61 of file cal_minmax_and_stacks.f90.
set_stack_of_segments()
subroutine cal_minmax_and_stacks::set_stack_of_segments (integer(kind= kint), intent(in) i_divide, integer(kind= kint), intent(in) i_quot, integer(kind= kint), intent(in) i_rest, integer(kind= kint), intent(in) istart, integer(kind= kint), dimension(0:i_divide), intent(inout) istack)
Definition at line 81 of file cal_minmax_and_stacks.f90.
Referenced by count_number_4_smp().