CALYPSO: gz_mpi_groups_io_b Module Reference
gz_mpi_groups_io_b Module Reference
Binary output routines for group data.
Functions/Subroutines
subroutine gz_mpi_read_group_data_b (IO_param, group_IO)
subroutine gz_mpi_read_surf_grp_data_b (IO_param, surf_grp_IO)
subroutine gz_mpi_write_grp_data_b (IO_param, group_IO)
subroutine gz_mpi_write_surf_grp_data_b (IO_param, surf_grp_IO)
Detailed Description
Binary output routines for group data.
      subroutine gz_mpi_read_group_data_b(IO_param, group_IO)
      subroutine gz_mpi_read_surf_grp_data_b(IO_param, surf_grp_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(group_data), intent(inout) :: group_IO
        type(surface_group_data), intent(inout) :: surf_grp_IO
      subroutine gz_mpi_write_grp_data_b(IO_param, group_IO)
      subroutine gz_mpi_write_surf_grp_data_b(IO_param, surf_grp_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(group_data), intent(in) :: group_IO
        type(surface_group_data), intent(in) :: surf_grp_IO
Function/Subroutine Documentation
gz_mpi_read_group_data_b()
subroutine gz_mpi_groups_io_b::gz_mpi_read_group_data_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(group_data), intent(inout) group_IO)
Definition at line 43 of file gz_MPI_groups_IO_b.f90.
References t_group_data::alloc_group_item(), t_group_data::alloc_group_num(), gz_mpi_binary_data_io::gz_mpi_read_int_vector_b(), gz_mpi_binary_data_io::gz_mpi_read_integer_stack_b(), gz_mpi_binary_head_io::gz_mpi_read_mul_charahead_b(), and gz_mpi_binary_datum_io::gz_mpi_read_one_inthead_b().
Referenced by gz_mpi_sph_modes_data_io_b::gz_mpi_read_geom_rtp_data_b(), gz_mpi_mesh_data_io_b::gz_mpi_read_mesh_groups_b(), and gz_mpi_sph_modes_data_io_b::gz_mpi_read_spectr_rj_data_b().
gz_mpi_read_surf_grp_data_b()
subroutine gz_mpi_groups_io_b::gz_mpi_read_surf_grp_data_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(surface_group_data), intent(inout) surf_grp_IO)
Definition at line 70 of file gz_MPI_groups_IO_b.f90.
References t_group_data::alloc_sf_group_item(), t_group_data::alloc_sf_group_num(), gz_mpi_binary_data_io::gz_mpi_read_int_vector_b(), gz_mpi_binary_data_io::gz_mpi_read_integer_stack_b(), gz_mpi_binary_head_io::gz_mpi_read_mul_charahead_b(), and gz_mpi_binary_datum_io::gz_mpi_read_one_inthead_b().
Referenced by gz_mpi_mesh_data_io_b::gz_mpi_read_mesh_groups_b().
gz_mpi_write_grp_data_b()
subroutine gz_mpi_groups_io_b::gz_mpi_write_grp_data_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(group_data), intent(in) group_IO)
Definition at line 98 of file gz_MPI_groups_IO_b.f90.
References gz_mpi_binary_data_io::gz_mpi_write_int_vector_b(), gz_mpi_binary_data_io::gz_mpi_write_integer_stack_b(), gz_mpi_binary_head_io::gz_mpi_write_mul_charahead_b(), and gz_mpi_binary_datum_io::gz_mpi_write_one_inthead_b().
Referenced by gz_mpi_sph_modes_data_io_b::gz_mpi_write_geom_rtp_data_b(), gz_mpi_mesh_data_io_b::gz_mpi_write_mesh_groups_b(), and gz_mpi_sph_modes_data_io_b::gz_mpi_write_spectr_rj_data_b().
gz_mpi_write_surf_grp_data_b()
subroutine gz_mpi_groups_io_b::gz_mpi_write_surf_grp_data_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(surface_group_data), intent(in) surf_grp_IO)
Definition at line 122 of file gz_MPI_groups_IO_b.f90.
References gz_mpi_binary_data_io::gz_mpi_write_int_vector_b(), gz_mpi_binary_data_io::gz_mpi_write_integer_stack_b(), gz_mpi_binary_head_io::gz_mpi_write_mul_charahead_b(), and gz_mpi_binary_datum_io::gz_mpi_write_one_inthead_b().
Referenced by gz_mpi_mesh_data_io_b::gz_mpi_write_mesh_groups_b().