CALYPSO: m_div_force_labels Module Reference
m_div_force_labels Module Reference
Functions/Subroutines
logical function check_div_force (field_name)
logical function check_div_flux_tensor (field_name)
logical function check_div_scalar_flux (field_name)
integer(kind=kint) function num_div_forces ()
subroutine set_div_force_labels (n_comps, names, maths)
Variables
integer(kind=kint), parameter, private ndiv_force = 12
Number of field labels.
type(field_def), parameter div_inertia = field_def(n_comp = n_scalar, name = 'div_inertia', math = '$ \partial_{i}' // '(e_{ijk} \omega_{j} u_{k})$')
Field label for divergence of advection \(- \partial_{i} \left(e_{ijk} \omega_{j} u_{k} \right) \).
type(field_def), parameter div_coriolis_force = field_def(n_comp = n_scalar, name = 'div_Coriolis_force', math = '$ -2 \partial_{i}' // '(e_{ijk} \Omega_{j} u_{k})$')
Field label for divergence of Lorentz force \(\partial_{i} \left(e_{ijk} J_{j} B_{k} \right) \).
type(field_def), parameter div_lorentz_force = field_def(n_comp = n_scalar, name = 'div_Lorentz_force', math = '$ \partial_{i}' // '(e_{ijk} J_{j} B_{k})$')
Field label for divergence of Lorentz force \(\partial_{i} \left(e_{ijk} J_{j} B_{k} \right) \).
type(field_def), parameter div_buoyancy = field_def(n_comp = n_scalar, name = 'div_buoyancy', math = '$-\partial_{i} \alpha_{T} T g_{i}$')
Field label for divergence of filtered buoyancy \(-\partial_{i} \alpha_{T} g_{i} T \).
type(field_def), parameter div_composite_buoyancy = field_def(n_comp = n_scalar, name = 'div_composite_buoyancy', math = '$-\partial_{i} \alpha_{C} C g_{i}$')
Field label for divergence of filtered compositional buoyancy \(-\partial_{i} \alpha_{C} g_{i} C \).
type(field_def), parameter div_momentum_flux = field_def(n_comp = n_vector, name = 'div_momentum_flux', math = '$-\partial_{j} (u_{i} u_{j})$')
Field label for divergence of momentum flux \(\partial_{j} (u_{i} u_{j}) \).
type(field_def), parameter div_maxwell_tensor = field_def(n_comp = n_vector, name = 'div_maxwell_tensor', math = '$ \partial_{j} (B_{i} B_{j})$')
Field label for divergence of Maxwell stress \(\partial_{j} (B_{i} B_{j}) \).
type(field_def), parameter div_induction_tensor = field_def(n_comp = n_vector, name = 'div_induction_tensor', math = '$ \partial_{i} (u_{i} B_{j}' //' - B_{i} u_{J})$')
Field label for divergence of magnetic induction \(\partial_{i} (u_{i} B_{j} - B_{i} u]_{J}) \).
type(field_def), parameter div_heat_flux = field_def(n_comp = n_scalar, name = 'div_heat_flux', math = '$-\partial_{i} u_{i} T $')
Field label for divergence of heat flux \(\partial_{i} (u_{i} T) \).
type(field_def), parameter div_pert_heat_flux = field_def(n_comp = n_scalar, name = 'div_pert_heat_flux', math = '$-\partial_{i} u_{i} \Therta $')
Field label for divergence of perturbation of heat flux \(\partial_{i} (u_{i} \Theta) \).
type(field_def), parameter div_composition_flux = field_def(n_comp = n_scalar, name = 'div_composition_flux', math = '$-\partial_{i} u_{i} C $')
Field label for divergence of composition flux \(-\partial_{i} u_{i} C \).
type(field_def), parameter div_pert_composition_flux = field_def(n_comp = n_scalar, name = 'div_pert_composition_flux', math = '$-\partial_{i} u_{i} \Theta_{C} $')
Field label for divergence of perturbation of compopstion flux \(-\partial_{i} u_{i} \Theta_{C} \).
Function/Subroutine Documentation
check_div_flux_tensor()
logical function m_div_force_labels::check_div_flux_tensor (character(len = kchara), intent(in) field_name)
Definition at line 155 of file m_div_force_labels.f90.
References div_induction_tensor, div_maxwell_tensor, and div_momentum_flux.
Referenced by set_mhd_field_address::check_vector_fields(), and t_base_force_labels::set_div_force_addresses().
check_div_force()
logical function m_div_force_labels::check_div_force (character(len = kchara), intent(in) field_name)
Definition at line 139 of file m_div_force_labels.f90.
References div_buoyancy, div_composite_buoyancy, div_coriolis_force, div_inertia, and div_lorentz_force.
Referenced by set_mhd_field_address::check_scalar_fields(), and t_base_force_labels::set_div_force_addresses().
check_div_scalar_flux()
logical function m_div_force_labels::check_div_scalar_flux (character(len = kchara), intent(in) field_name)
Definition at line 169 of file m_div_force_labels.f90.
References div_composition_flux, div_heat_flux, div_pert_composition_flux, and div_pert_heat_flux.
Referenced by set_mhd_field_address::check_scalar_fields(), and t_base_force_labels::set_div_force_addresses().
num_div_forces()
integer(kind = kint) function m_div_force_labels::num_div_forces
Definition at line 185 of file m_div_force_labels.f90.
References ndiv_force.
set_div_force_labels()
subroutine m_div_force_labels::set_div_force_labels (integer(kind = kint_4b), dimension(ndiv_force), intent(inout) n_comps, character(len = kchara), dimension(ndiv_force), intent(inout) names, character(len = kchara), dimension(ndiv_force), intent(inout) maths)
Definition at line 192 of file m_div_force_labels.f90.
References div_buoyancy, div_composite_buoyancy, div_composition_flux, div_coriolis_force, div_heat_flux, div_induction_tensor, div_inertia, div_lorentz_force, div_maxwell_tensor, div_momentum_flux, div_pert_composition_flux, div_pert_heat_flux, and t_field_labels::set_field_labels().
Variable Documentation
div_buoyancy
type(field_def), parameter m_div_force_labels::div_buoyancy = field_def(n_comp = n_scalar, name = 'div_buoyancy', math = '$-\partial_{i} \alpha_{T} T g_{i}$')
Field label for divergence of filtered buoyancy \(-\partial_{i} \alpha_{T} g_{i} T \).
Definition at line 76 of file m_div_force_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_div_forces(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_div_force(), t_base_force_labels::set_div_force_addresses(), and set_div_force_labels().
div_composite_buoyancy
type(field_def), parameter m_div_force_labels::div_composite_buoyancy = field_def(n_comp = n_scalar, name = 'div_composite_buoyancy', math = '$-\partial_{i} \alpha_{C} C g_{i}$')
Field label for divergence of filtered compositional buoyancy \(-\partial_{i} \alpha_{C} g_{i} C \).
Definition at line 82 of file m_div_force_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_div_forces(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_div_force(), t_base_force_labels::set_div_force_addresses(), and set_div_force_labels().
div_composition_flux
type(field_def), parameter m_div_force_labels::div_composition_flux = field_def(n_comp = n_scalar, name = 'div_composition_flux', math = '$-\partial_{i} u_{i} C $')
Field label for divergence of composition flux \(-\partial_{i} u_{i} C \).
Definition at line 122 of file m_div_force_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_div_forces(), check_div_scalar_flux(), t_base_force_labels::set_div_force_addresses(), and set_div_force_labels().
div_coriolis_force
type(field_def), parameter m_div_force_labels::div_coriolis_force = field_def(n_comp = n_scalar, name = 'div_Coriolis_force', math = '$ -2 \partial_{i}' // '(e_{ijk} \Omega_{j} u_{k})$')
Field label for divergence of Lorentz force \(\partial_{i} \left(e_{ijk} J_{j} B_{k} \right) \).
Definition at line 60 of file m_div_force_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_div_forces(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_div_force(), t_base_force_labels::set_div_force_addresses(), and set_div_force_labels().
div_heat_flux
type(field_def), parameter m_div_force_labels::div_heat_flux = field_def(n_comp = n_scalar, name = 'div_heat_flux', math = '$-\partial_{i} u_{i} T $')
Field label for divergence of heat flux \(\partial_{i} (u_{i} T) \).
Definition at line 109 of file m_div_force_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_div_forces(), check_div_scalar_flux(), t_base_force_labels::set_div_force_addresses(), and set_div_force_labels().
div_induction_tensor
type(field_def), parameter m_div_force_labels::div_induction_tensor = field_def(n_comp = n_vector, name = 'div_induction_tensor', math = '$ \partial_{i} (u_{i} B_{j}' //' - B_{i} u_{J})$')
Field label for divergence of magnetic induction \(\partial_{i} (u_{i} B_{j} - B_{i} u]_{J}) \).
Definition at line 101 of file m_div_force_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_div_forces(), check_div_flux_tensor(), t_base_force_labels::set_div_force_addresses(), and set_div_force_labels().
div_inertia
type(field_def), parameter m_div_force_labels::div_inertia = field_def(n_comp = n_scalar, name = 'div_inertia', math = '$ \partial_{i}' // '(e_{ijk} \omega_{j} u_{k})$')
Field label for divergence of advection \(- \partial_{i} \left(e_{ijk} \omega_{j} u_{k} \right) \).
Definition at line 52 of file m_div_force_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_div_forces(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_div_force(), t_base_force_labels::set_div_force_addresses(), and set_div_force_labels().
div_lorentz_force
type(field_def), parameter m_div_force_labels::div_lorentz_force = field_def(n_comp = n_scalar, name = 'div_Lorentz_force', math = '$ \partial_{i}' // '(e_{ijk} J_{j} B_{k})$')
Field label for divergence of Lorentz force \(\partial_{i} \left(e_{ijk} J_{j} B_{k} \right) \).
Definition at line 68 of file m_div_force_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_div_forces(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_div_force(), t_base_force_labels::set_div_force_addresses(), and set_div_force_labels().
div_maxwell_tensor
type(field_def), parameter m_div_force_labels::div_maxwell_tensor = field_def(n_comp = n_vector, name = 'div_maxwell_tensor', math = '$ \partial_{j} (B_{i} B_{j})$')
Field label for divergence of Maxwell stress \(\partial_{j} (B_{i} B_{j}) \).
Definition at line 95 of file m_div_force_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_div_forces(), check_div_flux_tensor(), t_base_force_labels::set_div_force_addresses(), and set_div_force_labels().
div_momentum_flux
type(field_def), parameter m_div_force_labels::div_momentum_flux = field_def(n_comp = n_vector, name = 'div_momentum_flux', math = '$-\partial_{j} (u_{i} u_{j})$')
Field label for divergence of momentum flux \(\partial_{j} (u_{i} u_{j}) \).
Definition at line 89 of file m_div_force_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_div_forces(), check_div_flux_tensor(), t_base_force_labels::set_div_force_addresses(), and set_div_force_labels().
div_pert_composition_flux
type(field_def), parameter m_div_force_labels::div_pert_composition_flux = field_def(n_comp = n_scalar, name = 'div_pert_composition_flux', math = '$-\partial_{i} u_{i} \Theta_{C} $')
Field label for divergence of perturbation of compopstion flux \(-\partial_{i} u_{i} \Theta_{C} \).
Definition at line 128 of file m_div_force_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_div_forces(), check_div_scalar_flux(), t_base_force_labels::set_div_force_addresses(), and set_div_force_labels().
div_pert_heat_flux
type(field_def), parameter m_div_force_labels::div_pert_heat_flux = field_def(n_comp = n_scalar, name = 'div_pert_heat_flux', math = '$-\partial_{i} u_{i} \Therta $')
Field label for divergence of perturbation of heat flux \(\partial_{i} (u_{i} \Theta) \).
Definition at line 115 of file m_div_force_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_div_forces(), check_div_scalar_flux(), t_base_force_labels::set_div_force_addresses(), and set_div_force_labels().
ndiv_force
integer(kind = kint), parameter, private m_div_force_labels::ndiv_force = 12 private
Number of field labels.
Definition at line 46 of file m_div_force_labels.f90.
Referenced by num_div_forces().