CALYPSO: mpi_element_connect_io Module Reference
mpi_element_connect_io Module Reference
Data IO routines for element connectivity.
Functions/Subroutines
subroutine mpi_write_element_info (IO_param, ele_IO)
subroutine mpi_write_surface_4_element (IO_param, sfed_IO)
subroutine mpi_write_edge_4_element (IO_param, sfed_IO)
subroutine mpi_read_num_element (IO_param, ele_IO)
subroutine mpi_read_element_info (IO_param, ele_IO)
subroutine mpi_read_surface_4_element (IO_param, sfed_IO)
subroutine mpi_read_edge_4_element (IO_param, sfed_IO)
Detailed Description
Data IO routines for element connectivity.
      subroutine mpi_write_element_info(IO_param, ele_IO)
      subroutine mpi_write_surface_4_element(IO_param, sfed_IO)
      subroutine mpi_write_edge_4_element(IO_param, sfed_IO)
        type(element_data), intent(in) :: ele_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
      subroutine mpi_read_num_element(IO_param, ele_IO)
      subroutine mpi_read_element_info(IO_param, ele_IO)
        type(element_data), intent(inout) :: ele_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
      subroutine mpi_read_surface_4_element(IO_param, sfed_IO)
      subroutine mpi_read_edge_4_element(IO_param, sfed_IO)
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
Function/Subroutine Documentation
mpi_read_edge_4_element()
subroutine mpi_element_connect_io::mpi_read_edge_4_element (type(calypso_mpi_io_params), intent(inout) IO_param, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 162 of file MPI_element_connect_IO.f90.
References t_surf_edge_io::alloc_edge_connect_io(), mpi_integer_list_io::mpi_read_int_list(), and mpi_ascii_data_io::mpi_read_num_of_data().
Referenced by mpi_edge_data_io::mpi_read_edge_connection().
mpi_read_element_info()
subroutine mpi_element_connect_io::mpi_read_element_info (type(calypso_mpi_io_params), intent(inout) IO_param, type(element_data), intent(inout) ele_IO)
Definition at line 110 of file MPI_element_connect_IO.f90.
References t_geometry_data::alloc_ele_connectivity(), t_geometry_data::alloc_element_types(), m_constants::iten, mpi_integer_list_io::mpi_read_ele_connect(), mpi_integer_list_io::mpi_read_element_type(), mpi_ascii_data_io::mpi_read_num_of_data(), and set_nnod_4_ele_by_type::s_set_nnod_4_ele_by_type().
Referenced by mpi_edge_data_io::mpi_read_edge_connection(), mpi_mesh_data_io::mpi_read_geometry_data(), and mpi_surface_data_io::mpi_read_surface_connection().
mpi_read_num_element()
subroutine mpi_element_connect_io::mpi_read_num_element (type(calypso_mpi_io_params), intent(inout) IO_param, type(element_data), intent(inout) ele_IO)
Definition at line 98 of file MPI_element_connect_IO.f90.
References mpi_ascii_data_io::mpi_read_num_of_data().
Referenced by mpi_edge_data_io::mpi_read_edge_connection(), mpi_mesh_data_io::mpi_read_num_node_ele(), and mpi_surface_data_io::mpi_read_surface_connection().
mpi_read_surface_4_element()
subroutine mpi_element_connect_io::mpi_read_surface_4_element (type(calypso_mpi_io_params), intent(inout) IO_param, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 143 of file MPI_element_connect_IO.f90.
References t_surf_edge_io::alloc_surface_connect_io(), mpi_integer_list_io::mpi_read_int_list(), and mpi_ascii_data_io::mpi_read_num_of_data().
Referenced by mpi_edge_data_io::mpi_read_edge_connection(), and mpi_surface_data_io::mpi_read_surface_connection().
mpi_write_edge_4_element()
subroutine mpi_element_connect_io::mpi_write_edge_4_element (type(calypso_mpi_io_params), intent(inout) IO_param, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 81 of file MPI_element_connect_IO.f90.
References mpi_integer_list_io::mpi_write_int_list(), and mpi_ascii_data_io::mpi_write_num_of_data().
Referenced by mpi_edge_data_io::mpi_write_edge_connection().
mpi_write_element_info()
subroutine mpi_element_connect_io::mpi_write_element_info (type(calypso_mpi_io_params), intent(inout) IO_param, type(element_data), intent(in) ele_IO)
Definition at line 46 of file MPI_element_connect_IO.f90.
References m_constants::iten, mpi_integer_list_io::mpi_write_ele_connect(), mpi_integer_list_io::mpi_write_element_type(), and mpi_ascii_data_io::mpi_write_num_of_data().
Referenced by mpi_edge_data_io::mpi_write_edge_connection(), mpi_mesh_data_io::mpi_write_geometry_data(), and mpi_surface_data_io::mpi_write_surface_connection().
mpi_write_surface_4_element()
subroutine mpi_element_connect_io::mpi_write_surface_4_element (type(calypso_mpi_io_params), intent(inout) IO_param, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 65 of file MPI_element_connect_IO.f90.
References mpi_integer_list_io::mpi_write_int_list(), and mpi_ascii_data_io::mpi_write_num_of_data().
Referenced by mpi_edge_data_io::mpi_write_edge_connection(), and mpi_surface_data_io::mpi_write_surface_connection().