CALYPSO: m_monitor_file_labels Module Reference
m_monitor_file_labels Module Reference
Comments for mesh data.
Functions/Subroutines
character(len=ilen_time_label) function hd_time_label ()
character(len=ilen_time_sph_label) function hd_time_sph_label ()
character(len=ilen_pick_sph_head) function hd_pick_sph_head ()
character(len=ilen_pick_sph_num) function hd_pick_sph_num ()
character(len=ilen_pk_gauss_head) function hd_pick_gauss_head ()
Variables
integer(kind=kint), parameter ilen_time_label = 18
length of hd_fem_para
integer(kind=kint), parameter ilen_time_sph_label = 18+23+19
length of hd_fem_para
integer(kind=kint), parameter ilen_pick_sph_head = 1+24+2
length of hd_fem_para
integer(kind=kint), parameter ilen_pick_sph_num = 21+1
length of hd_fem_para
integer(kind=kint), parameter ilen_pk_gauss_head = 28+1
length of hd_fem_para
Detailed Description
Comments for mesh data.
      character(len=ilen_time_label) function hd_time_label()
      character(len=ilen_time_sph_label) function hd_time_sph_label()
      character(len=ilen_pick_sph_head) function hd_pick_sph_head()
      character(len=ilen_pick_sph_num) function hd_pick_sph_num()
      character(len=ilen_pk_gauss_head) function hd_pick_gauss_head()
Function/Subroutine Documentation
hd_pick_gauss_head()
character(len=ilen_pk_gauss_head) function m_monitor_file_labels::hd_pick_gauss_head
Definition at line 74 of file m_monitor_file_labels.f90.
Referenced by mpi_sph_gauss_coefs_io::write_sph_gauss_header_mpi().
hd_pick_sph_head()
character(len=ilen_pick_sph_head) function m_monitor_file_labels::hd_pick_sph_head
Definition at line 57 of file m_monitor_file_labels.f90.
Referenced by t_pickup_sph_spectr_data::pick_sph_header_no_field(), and t_picked_sph_spectr_data_io::write_tave_sph_spec_monitor().
hd_pick_sph_num()
character(len=ilen_pick_sph_num) function m_monitor_file_labels::hd_pick_sph_num
Definition at line 66 of file m_monitor_file_labels.f90.
Referenced by t_pickup_sph_spectr_data::pick_sph_header_no_field(), and t_picked_sph_spectr_data_io::write_tave_sph_spec_monitor().
hd_time_label()
character(len=ilen_time_label) function m_monitor_file_labels::hd_time_label
Definition at line 39 of file m_monitor_file_labels.f90.
Referenced by mpi_sph_gauss_coefs_io::write_sph_gauss_header_mpi().
hd_time_sph_label()
character(len=ilen_time_sph_label) function m_monitor_file_labels::hd_time_sph_label
Definition at line 47 of file m_monitor_file_labels.f90.
Referenced by t_pickup_sph_spectr_data::pick_sph_header_no_field().
Variable Documentation
ilen_pick_sph_head
integer(kind = kint), parameter m_monitor_file_labels::ilen_pick_sph_head = 1+24+2
length of hd_fem_para
Definition at line 26 of file m_monitor_file_labels.f90.
ilen_pick_sph_num
integer(kind = kint), parameter m_monitor_file_labels::ilen_pick_sph_num = 21+1
length of hd_fem_para
Definition at line 28 of file m_monitor_file_labels.f90.
ilen_pk_gauss_head
integer(kind = kint), parameter m_monitor_file_labels::ilen_pk_gauss_head = 28+1
length of hd_fem_para
Definition at line 30 of file m_monitor_file_labels.f90.
ilen_time_label
integer(kind = kint), parameter m_monitor_file_labels::ilen_time_label = 18
length of hd_fem_para
Definition at line 22 of file m_monitor_file_labels.f90.
ilen_time_sph_label
integer(kind = kint), parameter m_monitor_file_labels::ilen_time_sph_label = 18+23+19
length of hd_fem_para
Definition at line 24 of file m_monitor_file_labels.f90.