CALYPSO: pickup_sph_spectr Module Reference
pickup_sph_spectr Module Reference
Make spectrum data list.
Functions/Subroutines
subroutine const_picked_sph_address (iflag_center, l_truncation, sph_rj, pick_list, picked)
subroutine allocate_iflag_pick_sph (l_truncation)
subroutine deallocate_iflag_pick_sph
subroutine, private count_picked_sph_adrress (l_truncation, sph_rj, num_pick_sph, num_pick_sph_l, num_pick_sph_m, idx_pick_sph, idx_pick_sph_l, idx_pick_sph_m, num_pickup, num_pickup_lc)
subroutine, private set_picked_sph_address (iflag_center, l_truncation, sph_rj, num_pick_sph, num_pick_sph_l, num_pick_sph_m, idx_pick_sph, idx_pick_sph_l, idx_pick_sph_m, num_pickup_lc, idx_pickup)
subroutine set_scale_4_vect_l0 (num_pickup, idx_pick_gl, scale_for_zero)
Variables
integer(kind=kint), dimension(:), allocatable, private iflag_picked_sph
Detailed Description
Make spectrum data list.
      subroutine const_picked_sph_address                             &
     &         (l_truncation, sph_rj, pick_list, picked)
        type(sph_rj_grid), intent(in) :: sph_rj
        type(pickup_mode_list), intent(inout) :: pick_list
        type(picked_spectrum_data), intent(inout) :: picked
      subroutine allocate_iflag_pick_sph(l_truncation)
      subroutine deallocate_iflag_pick_sph
        type(sph_rj_grid), intent(in) :: sph_rj
      subroutine set_scale_4_vect_l0(num_pickup,                      &
     &          idx_pick_gl, scale_for_zero)
Function/Subroutine Documentation
allocate_iflag_pick_sph()
subroutine pickup_sph_spectr::allocate_iflag_pick_sph (integer(kind = kint), intent(in) l_truncation)
Definition at line 101 of file pickup_sph_spectr.f90.
References iflag_picked_sph.
Referenced by const_picked_sph_address().
const_picked_sph_address()
subroutine pickup_sph_spectr::const_picked_sph_address (integer(kind = kint), intent(in) iflag_center, integer(kind = kint), intent(in) l_truncation, type(sph_rj_grid), intent(in) sph_rj, type(pickup_mode_list), intent(inout) pick_list, type(picked_spectrum_data), intent(inout) picked)
Definition at line 44 of file pickup_sph_spectr.f90.
References t_pickup_sph_spectr_data::alloc_pick_sph_monitor(), t_pickup_sph_spectr_data::alloc_pickup_sph_spec_local(), allocate_iflag_pick_sph(), calypso_mpi_int::calypso_mpi_allgather_one_int(), count_picked_sph_adrress(), t_pickup_sph_spectr_data::dealloc_pick_sph_mode(), deallocate_iflag_pick_sph(), calypso_mpi::nprocs, and set_picked_sph_address().
Referenced by pickup_gauss_coefficients::init_gauss_coefs_4_monitor().
count_picked_sph_adrress()
subroutine, private pickup_sph_spectr::count_picked_sph_adrress (integer(kind = kint), intent(in) l_truncation, type(sph_rj_grid), intent(in) sph_rj, integer(kind = kint), intent(in) num_pick_sph, integer(kind = kint), intent(in) num_pick_sph_l, integer(kind = kint), intent(in) num_pick_sph_m, integer(kind = kint), dimension(num_pick_sph,2), intent(in) idx_pick_sph, integer(kind = kint), dimension(num_pick_sph_l), intent(in) idx_pick_sph_l, integer(kind = kint), dimension(num_pick_sph_m), intent(in) idx_pick_sph_m, integer(kind = kint), intent(inout) num_pickup, integer(kind = kint), intent(inout) num_pickup_lc) private
Definition at line 124 of file pickup_sph_spectr.f90.
References t_spheric_rj_data::find_local_sph_address(), spherical_harmonics::get_idx_by_full_degree_order(), iflag_picked_sph, and m_constants::izero.
Referenced by const_picked_sph_address().
deallocate_iflag_pick_sph()
subroutine pickup_sph_spectr::deallocate_iflag_pick_sph
Definition at line 115 of file pickup_sph_spectr.f90.
References iflag_picked_sph.
Referenced by const_picked_sph_address().
set_picked_sph_address()
subroutine, private pickup_sph_spectr::set_picked_sph_address (integer(kind = kint), intent(in) iflag_center, integer(kind = kint), intent(in) l_truncation, type(sph_rj_grid), intent(in) sph_rj, integer(kind = kint), intent(in) num_pick_sph, integer(kind = kint), intent(in) num_pick_sph_l, integer(kind = kint), intent(in) num_pick_sph_m, integer(kind = kint), dimension(num_pick_sph,2), intent(in) idx_pick_sph, integer(kind = kint), dimension(num_pick_sph_l), intent(in) idx_pick_sph_l, integer(kind = kint), dimension(num_pick_sph_m), intent(in) idx_pick_sph_m, integer(kind = kint), intent(in) num_pickup_lc, integer(kind = kint), dimension(0:num_pickup_lc,4), intent(inout) idx_pickup) private
Definition at line 199 of file pickup_sph_spectr.f90.
References t_spheric_rj_data::find_local_sph_address(), spherical_harmonics::get_degree_order_by_full_j(), spherical_harmonics::get_idx_by_full_degree_order(), iflag_picked_sph, m_constants::ione, m_constants::izero, and quicksort::quicksort_w_index().
Referenced by const_picked_sph_address().
set_scale_4_vect_l0()
subroutine pickup_sph_spectr::set_scale_4_vect_l0 (integer(kind = kint), intent(in) num_pickup, integer(kind = kint), dimension(num_pickup,3), intent(in) idx_pick_gl, real(kind = kreal), dimension(num_pickup), intent(inout) scale_for_zero)
Definition at line 309 of file pickup_sph_spectr.f90.
References m_constants::half, and m_constants::one.
Variable Documentation
iflag_picked_sph
integer(kind = kint), dimension(:), allocatable, private pickup_sph_spectr::iflag_picked_sph private
Definition at line 33 of file pickup_sph_spectr.f90.
Referenced by allocate_iflag_pick_sph(), count_picked_sph_adrress(), deallocate_iflag_pick_sph(), and set_picked_sph_address().