CALYPSO: t_control_array_chara2real Module Reference
t_control_array_chara2real Module Reference
Data Types
type ctl_array_c2r
Structure for two charactors and real control array.
type read_chara2_real_item
structure of control item with three characters
Functions/Subroutines
subroutine read_char2real_ctl_type (c_buf, label, c2r_item)
subroutine write_char2real_ctl_type (id_file, level, label, c2r_item)
subroutine copy_char2real_ctl (org_c2r, new_c2r)
subroutine alloc_control_array_c2_r (array_c2r)
subroutine dealloc_control_array_c2_r (array_c2r)
subroutine read_control_array_c2_r (id_control, label, array_c2r, c_buf)
subroutine write_control_array_c2_r (id_control, level, label, array_c2r)
subroutine append_control_array_c2_r (read_c2r, array_c2r)
subroutine dup_control_array_c2_r (org_c2r, tgt_c2r)
subroutine copy_control_array_c2_r (num_copy, org_c2r, tgt_c2r)
subroutine append_control_item_c2_r (read_c2r, array_c2r)
Function/Subroutine Documentation
alloc_control_array_c2_r()
subroutine t_control_array_chara2real::alloc_control_array_c2_r (type(ctl_array_c2r), intent(inout) array_c2r)
Definition at line 142 of file t_control_array_chara2real.f90.
Referenced by append_control_array_c2_r(), bcast_control_arrays::bcast_ctl_array_c2r(), dup_control_array_c2_r(), and read_control_array_c2_r().
append_control_array_c2_r()
subroutine t_control_array_chara2real::append_control_array_c2_r (type(read_chara2_real_item), intent(inout) read_c2r, type(ctl_array_c2r), intent(inout) array_c2r)
Definition at line 235 of file t_control_array_chara2real.f90.
References alloc_control_array_c2_r(), append_control_item_c2_r(), copy_control_array_c2_r(), and dealloc_control_array_c2_r().
Referenced by read_control_array_c2_r().
append_control_item_c2_r()
subroutine t_control_array_chara2real::append_control_item_c2_r (type(read_chara2_real_item), intent(in) read_c2r, type(ctl_array_c2r), intent(inout) array_c2r)
Definition at line 291 of file t_control_array_chara2real.f90.
Referenced by append_control_array_c2_r().
copy_char2real_ctl()
subroutine t_control_array_chara2real::copy_char2real_ctl (type(read_chara2_real_item), intent(in) org_c2r, type(read_chara2_real_item), intent(inout) new_c2r)
Definition at line 127 of file t_control_array_chara2real.f90.
copy_control_array_c2_r()
subroutine t_control_array_chara2real::copy_control_array_c2_r (integer(kind = kint), intent(in) num_copy, type(ctl_array_c2r), intent(in) org_c2r, type(ctl_array_c2r), intent(inout) tgt_c2r)
Definition at line 274 of file t_control_array_chara2real.f90.
Referenced by append_control_array_c2_r(), and dup_control_array_c2_r().
dealloc_control_array_c2_r()
subroutine t_control_array_chara2real::dealloc_control_array_c2_r (type(ctl_array_c2r), intent(inout) array_c2r)
Definition at line 158 of file t_control_array_chara2real.f90.
Referenced by append_control_array_c2_r(), t_ctl_data_node_boundary::dealloc_bc_4_node_ctl(), and t_ctl_data_surf_boundary::dealloc_bc_4_surf_ctl().
dup_control_array_c2_r()
subroutine t_control_array_chara2real::dup_control_array_c2_r (type(ctl_array_c2r), intent(in) org_c2r, type(ctl_array_c2r), intent(inout) tgt_c2r)
Definition at line 260 of file t_control_array_chara2real.f90.
References alloc_control_array_c2_r(), and copy_control_array_c2_r().
read_char2real_ctl_type()
subroutine t_control_array_chara2real::read_char2real_ctl_type (type(buffer_for_control), intent(in) c_buf, character(len=kchara), intent(in) label, type(read_chara2_real_item), intent(inout) c2r_item)
Definition at line 80 of file t_control_array_chara2real.f90.
References m_machine_parameter::iflag_debug.
Referenced by read_control_array_c2_r().
read_control_array_c2_r()
subroutine t_control_array_chara2real::read_control_array_c2_r (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) label, type(ctl_array_c2r), intent(inout) array_c2r, type(buffer_for_control), intent(inout) c_buf)
Definition at line 172 of file t_control_array_chara2real.f90.
References alloc_control_array_c2_r(), append_control_array_c2_r(), t_read_control_elements::check_array_flag(), t_read_control_elements::check_end_array_flag(), t_read_control_elements::load_one_line_from_control(), and read_char2real_ctl_type().
Referenced by t_ctl_data_node_boundary::read_bc_4_node_ctl(), and t_ctl_data_surf_boundary::read_bc_4_surf_ctl().
write_char2real_ctl_type()
subroutine t_control_array_chara2real::write_char2real_ctl_type (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, type(read_chara2_real_item), intent(in) c2r_item)
Definition at line 107 of file t_control_array_chara2real.f90.
References write_control_elements::write_chara2_real_ctl_item().
write_control_array_c2_r()
subroutine t_control_array_chara2real::write_control_array_c2_r (integer(kind = kint), intent(in) id_control, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, type(ctl_array_c2r), intent(in) array_c2r)
Definition at line 206 of file t_control_array_chara2real.f90.
References write_control_elements::write_array_flag_for_ctl(), write_control_elements::write_chara2_real_ctl_item(), and write_control_elements::write_end_array_flag_for_ctl().