CALYPSO: calypso_solver_sr Module Reference
calypso_solver_sr Module Reference
Select communication routines for spherical harmonics transform.
Functions/Subroutines
subroutine init_solver_send_recv (NP, N, NEIBPETOT, STACK_IMPORT, NOD_IMPORT, REV_IMPORT)
subroutine finalize_solver_send_recv (N, NEIBPETOT, STACK_IMPORT, NOD_IMPORT)
subroutine solver_send_recv_n (iflag_SR, NP, N, NB, NEIBPETOT, NEIBPE, STACK_IMPORT, NOD_IMPORT, REV_IMPORT, STACK_EXPORT, NOD_EXPORT, X)
subroutine solver_send_recv_6 (iflag_SR, NP, N, NEIBPETOT, NEIBPE, STACK_IMPORT, NOD_IMPORT, REV_IMPORT, STACK_EXPORT, NOD_EXPORT, X)
subroutine solver_send_recv_3 (iflag_SR, NP, N, NEIBPETOT, NEIBPE, STACK_IMPORT, NOD_IMPORT, REV_IMPORT, STACK_EXPORT, NOD_EXPORT, X)
subroutine solver_send_recv_2 (iflag_SR, NP, N, NEIBPETOT, NEIBPE, STACK_IMPORT, NOD_IMPORT, REV_IMPORT, STACK_EXPORT, NOD_EXPORT, X)
subroutine solver_send_recv (iflag_SR, NP, N, NEIBPETOT, NEIBPE, STACK_IMPORT, NOD_IMPORT, REV_IMPORT, STACK_EXPORT, NOD_EXPORT, X)
subroutine solver_send_recv_int (iflag_SR, NP, N, NEIBPETOT, NEIBPE, STACK_IMPORT, NOD_IMPORT, REV_IMPORT, STACK_EXPORT, NOD_EXPORT, iX)
Detailed Description
Select communication routines for spherical harmonics transform.
      subroutine init_solver_send_recv(NP, N, NEIBPETOT,              &
     &                 STACK_IMPORT, NOD_IMPORT, REV_IMPORT)
      subroutine finalize_solver_send_recv(N, NEIBPETOT,              &
     &                 STACK_IMPORT, NOD_IMPORT)
      subroutine solver_send_recv_N(iflag_SR, NP, N, NB, NEIBPETOT,   &
     &                 NEIBPE, STACK_IMPORT, NOD_IMPORT, REV_IMPORT,  &
     &                         STACK_EXPORT, NOD_EXPORT, X)
      subroutine solver_send_recv_6(iflag_SR, NP, N, NEIBPETOT,       &
     &                 NEIBPE, STACK_IMPORT, NOD_IMPORT, REV_IMPORT,  &
     &                         STACK_EXPORT, NOD_EXPORT, X)
      subroutine solver_send_recv_3(iflag_SR, NP, N, NEIBPETOT,       &
     &                 NEIBPE, STACK_IMPORT, NOD_IMPORT, REV_IMPORT,  &
     &                         STACK_EXPORT, NOD_EXPORT, X)
      subroutine solver_send_recv_2(iflag_SR, NP, N, NEIBPETOT,       &
     &                 NEIBPE, STACK_IMPORT, NOD_IMPORT, REV_IMPORT,  &
     &                         STACK_EXPORT, NOD_EXPORT, X)
      subroutine solver_send_recv(iflag_SR, NP, N, NEIBPETOT,         &
     &                 NEIBPE, STACK_IMPORT, NOD_IMPORT, REV_IMPORT,  &
     &                         STACK_EXPORT, NOD_EXPORT, X)
      subroutine solver_send_recv_int(iflag_SR, NP, N, NEIBPETOT,     &
     &                 NEIBPE, STACK_IMPORT, NOD_IMPORT, REV_IMPORT,  &
     &                         STACK_EXPORT, NOD_EXPORT, iX)
Parameters
NB Number of components for communication
NP Number of node
N Number of internal node
NEIBPETOT Number of processses to send
NEIBPE(NEIBPETOT) Process ID to communicate
STACK_EXPORT(0:NEIBPETOT) End points of send buffer for each process
NOD_EXPORT(STACK_EXPORT(NEIBPETOT)) local node ID to copy in send buffer
STACK_IMPORT(0:NEIBPETOT) End points of receive buffer for each process
NOD_IMPORT(STACK_IMPORT(NEIBPETOT)) local node ID to copy from receive buffer
REV_IMPORT(NP-N) import buffer ID for each data point
X(NB*NP) vector to syncronize
X(6*NP) Six components of received data
X(3*NP) Three components of received data
X(2*NP) Two components of received data
X(NP) Scalar received data
iX(NP) Integer received data
Function/Subroutine Documentation
finalize_solver_send_recv()
subroutine calypso_solver_sr::finalize_solver_send_recv (integer(kind = kint), intent(in) N, integer(kind = kint), intent(in) NEIBPETOT, integer(kind = kint), dimension(0:neibpetot), intent(in) STACK_IMPORT, integer(kind = kint), dimension(stack_import(neibpetot)), intent(inout) NOD_IMPORT)
Definition at line 110 of file calypso_solver_SR.f90.
init_solver_send_recv()
subroutine calypso_solver_sr::init_solver_send_recv (integer(kind = kint), intent(in) NP, integer(kind = kint), intent(in) N, integer(kind = kint), intent(in) NEIBPETOT, integer(kind = kint), dimension(0:neibpetot), intent(in) STACK_IMPORT, integer(kind = kint), dimension(stack_import(neibpetot)), intent(inout) NOD_IMPORT, integer(kind = kint), dimension(np-n), intent(inout) REV_IMPORT)
Definition at line 79 of file calypso_solver_SR.f90.
References set_from_recv_buf_rev::set_reverse_import_table().
solver_send_recv()
subroutine calypso_solver_sr::solver_send_recv (integer(kind = kint), intent(in) iflag_SR, integer(kind = kint), intent(in) NP, integer(kind = kint), intent(in) N, integer(kind = kint), intent(in) NEIBPETOT, integer(kind = kint), dimension(neibpetot), intent(in) NEIBPE, integer(kind = kint), dimension(0:neibpetot), intent(in) STACK_IMPORT, integer(kind = kint), dimension(stack_import(neibpetot)), intent(in) NOD_IMPORT, integer(kind = kint), dimension(np-n), intent(in) REV_IMPORT, integer(kind = kint), dimension(0:neibpetot), intent(in) STACK_EXPORT, integer(kind = kint), dimension(stack_export(neibpetot)), intent(in) NOD_EXPORT, real (kind=kreal), dimension(np), intent(inout) X)
Definition at line 278 of file calypso_solver_SR.f90.
References calypso_sr::calypso_send_recv(), and m_constants::izero.
solver_send_recv_2()
subroutine calypso_solver_sr::solver_send_recv_2 (integer(kind = kint), intent(in) iflag_SR, integer(kind = kint), intent(in) NP, integer(kind = kint), intent(in) N, integer(kind = kint), intent(in) NEIBPETOT, integer(kind = kint), dimension(neibpetot), intent(in) NEIBPE, integer(kind = kint), dimension(0:neibpetot), intent(in) STACK_IMPORT, integer(kind = kint), dimension(stack_import(neibpetot)), intent(in) NOD_IMPORT, integer(kind = kint), dimension(np-n), intent(in) REV_IMPORT, integer(kind = kint), dimension(0:neibpetot), intent(in) STACK_EXPORT, integer(kind = kint), dimension(stack_export(neibpetot)), intent(in) NOD_EXPORT, real (kind=kreal), dimension(itwo*np), intent(inout) X)
Definition at line 242 of file calypso_solver_SR.f90.
References calypso_sr_2::calypso_send_recv_2(), m_constants::itwo, and m_constants::izero.
solver_send_recv_3()
subroutine calypso_solver_sr::solver_send_recv_3 (integer(kind = kint), intent(in) iflag_SR, integer(kind = kint), intent(in) NP, integer(kind = kint), intent(in) N, integer(kind = kint), intent(in) NEIBPETOT, integer(kind = kint), dimension(neibpetot), intent(in) NEIBPE, integer(kind = kint), dimension(0:neibpetot), intent(in) STACK_IMPORT, integer(kind = kint), dimension(stack_import(neibpetot)), intent(in) NOD_IMPORT, integer(kind = kint), dimension(np-n), intent(in) REV_IMPORT, integer(kind = kint), dimension(0:neibpetot), intent(in) STACK_EXPORT, integer(kind = kint), dimension(stack_export(neibpetot)), intent(in) NOD_EXPORT, real (kind=kreal), dimension(ithree*np), intent(inout) X)
Definition at line 206 of file calypso_solver_SR.f90.
References calypso_sr_3::calypso_send_recv_3(), m_constants::ithree, and m_constants::izero.
solver_send_recv_6()
subroutine calypso_solver_sr::solver_send_recv_6 (integer(kind = kint), intent(in) iflag_SR, integer(kind = kint), intent(in) NP, integer(kind = kint), intent(in) N, integer(kind = kint), intent(in) NEIBPETOT, integer(kind = kint), dimension(neibpetot), intent(in) NEIBPE, integer(kind = kint), dimension(0:neibpetot), intent(in) STACK_IMPORT, integer(kind = kint), dimension(stack_import(neibpetot)), intent(in) NOD_IMPORT, integer(kind = kint), dimension(np-n), intent(in) REV_IMPORT, integer(kind = kint), dimension(0:neibpetot), intent(in) STACK_EXPORT, integer(kind = kint), dimension(stack_export(neibpetot)), intent(in) NOD_EXPORT, real (kind=kreal), dimension(isix*np), intent(inout) X)
Definition at line 170 of file calypso_solver_SR.f90.
References calypso_sr_6::calypso_send_recv_6(), m_constants::isix, and m_constants::izero.
solver_send_recv_int()
subroutine calypso_solver_sr::solver_send_recv_int (integer(kind = kint), intent(in) iflag_SR, integer(kind = kint), intent(in) NP, integer(kind = kint), intent(in) N, integer(kind = kint), intent(in) NEIBPETOT, integer(kind = kint), dimension(neibpetot), intent(in) NEIBPE, integer(kind = kint), dimension(0:neibpetot), intent(in) STACK_IMPORT, integer(kind = kint), dimension(stack_import(neibpetot)), intent(in) NOD_IMPORT, integer(kind = kint), dimension(np-n), intent(in) REV_IMPORT, integer(kind = kint), dimension(0:neibpetot), intent(in) STACK_EXPORT, integer(kind = kint), dimension(stack_export(neibpetot)), intent(in) NOD_EXPORT, integer (kind=kint), dimension(np), intent(inout) iX)
Definition at line 315 of file calypso_solver_SR.f90.
References calypso_sr_int::calypso_send_recv_int(), and m_constants::izero.
solver_send_recv_n()
subroutine calypso_solver_sr::solver_send_recv_n (integer(kind = kint), intent(in) iflag_SR, integer(kind = kint), intent(in) NP, integer(kind = kint), intent(in) N, integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) NEIBPETOT, integer(kind = kint), dimension(neibpetot), intent(in) NEIBPE, integer(kind = kint), dimension(0:neibpetot), intent(in) STACK_IMPORT, integer(kind = kint), dimension(stack_import(neibpetot)), intent(in) NOD_IMPORT, integer(kind = kint), dimension(np-n), intent(in) REV_IMPORT, integer(kind = kint), dimension(0:neibpetot), intent(in) STACK_EXPORT, integer(kind = kint), dimension(stack_export(neibpetot)), intent(in) NOD_EXPORT, real (kind=kreal), dimension(nb*np), intent(inout) X)
Definition at line 132 of file calypso_solver_SR.f90.
References select_calypso_sr::finish_calypso_send_recv(), m_constants::izero, and select_calypso_sr::sel_calypso_send_recv_n().