CALYPSO: set_sph_local_node Module Reference
set_sph_local_node Module Reference
Functions/Subroutines
subroutine count_numnod_local_sph_mesh (iflag_shell_mode, ip_r, ip_t, stbl, node)
subroutine set_local_nodes_sph_mesh (iflag_shell_mode, ip_r, ip_t, num_colat, r_global, colat_gl, stbl, node)
Function/Subroutine Documentation
count_numnod_local_sph_mesh()
subroutine set_sph_local_node::count_numnod_local_sph_mesh (integer(kind = kint), intent(in) iflag_shell_mode, integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, type(comm_table_make_sph), intent(in) stbl, type(node_data), intent(inout) node)
Definition at line 33 of file set_sph_local_node.f90.
References cal_sph_node_addresses::cal_sph_local_numnod(), cal_sph_node_addresses::check_local_sph_node_constants(), m_machine_parameter::iflag_debug, m_spheric_constants::iflag_mesh_w_center, m_spheric_constants::iflag_mesh_w_pole, m_constants::ione, cal_sph_node_addresses::reset_local_sph_node_constants(), cal_sph_node_addresses::set_intnod_center(), cal_sph_node_addresses::set_intnod_npole(), cal_sph_node_addresses::set_intnod_shell(), cal_sph_node_addresses::set_intnod_spole(), cal_sph_node_addresses::set_nnod_gl_center(), cal_sph_node_addresses::set_nnod_gl_npole(), cal_sph_node_addresses::set_nnod_gl_shell(), cal_sph_node_addresses::set_nnod_gl_spole(), cal_sph_node_addresses::set_nnod_lc_center(), cal_sph_node_addresses::set_nnod_lc_ctr_np(), cal_sph_node_addresses::set_nnod_lc_ctr_sph(), cal_sph_node_addresses::set_nnod_lc_npole(), cal_sph_node_addresses::set_nnod_lc_shell(), and cal_sph_node_addresses::set_nnod_lc_spole().
Referenced by set_fem_mesh_4_sph::const_fem_geometry_for_sph().
set_local_nodes_sph_mesh()
subroutine set_sph_local_node::set_local_nodes_sph_mesh (integer(kind = kint), intent(in) iflag_shell_mode, integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, integer(kind = kint), intent(in) num_colat, real(kind= kreal), dimension(stbl%nidx_global_fem(1)), intent(in) r_global, real(kind= kreal), dimension(num_colat), intent(in) colat_gl, type(comm_table_make_sph), intent(in) stbl, type(node_data), intent(inout) node)
Definition at line 89 of file set_sph_local_node.f90.
References m_constants::four, cal_sph_node_addresses::global_sph_center_node_id(), cal_sph_node_addresses::global_sph_n_pole_node_id(), cal_sph_node_addresses::global_sph_s_pole_node_id(), cal_sph_node_addresses::global_sph_shell_node_id(), m_spheric_constants::iflag_mesh_w_center, m_spheric_constants::iflag_mesh_w_pole, m_constants::ione, m_constants::one, cal_sph_node_addresses::sph_center_node_id(), cal_sph_node_addresses::sph_center_np_node_id(), cal_sph_node_addresses::sph_ctr_shell_node_id(), cal_sph_node_addresses::sph_n_pole_node_id(), cal_sph_node_addresses::sph_s_pole_node_id(), cal_sph_node_addresses::sph_shell_node_id(), m_constants::two, and m_constants::zero.
Referenced by set_fem_mesh_4_sph::const_fem_geometry_for_sph().