CALYPSO: t_fftpack5_wrapper Module Reference
t_fftpack5_wrapper Module Reference
Fourier transform using FFTPACK5.
Data Types
type working_fftpack
structure for working data for FFTPACK5
Functions/Subroutines
subroutine init_wk_fftpack_t (Nsmp, Nstacksmp, Nfft, WK)
subroutine finalize_wk_fftpack_t (WK)
subroutine verify_wk_fftpack_t (Nsmp, Nstacksmp, Nfft, WK)
subroutine calypso_rfftmf_t (Nsmp, Nstacksmp, M, Nfft, X, WK)
subroutine calypso_rfftmb_t (Nsmp, Nstacksmp, M, Nfft, X, WK)
subroutine, private alloc_work_4_fftpack_t (Nsmp, Nfft, WK)
subroutine, private alloc_const_4_fftpack_t (nfft, WK)
subroutine, private dealloc_work_4_fftpack_t (WK)
subroutine, private dealloc_const_fftpack_t (WK)
Detailed Description
Fourier transform using FFTPACK5.
  ------------------------------------------------------------------
      subroutine init_WK_FFTPACK_t(Nsmp, Nstacksmp, Nfft, WK)
      subroutine finalize_WK_FFTPACK_t(WK)
      subroutine verify_wk_FFTPACK_t(Nsmp, Nstacksmp, Nfft, WK)
 ------------------------------------------------------------------
   wrapper subroutine for initierize FFT
 ------------------------------------------------------------------
      subroutine CALYPSO_RFFTMF_t(Nsmp, Nstacksmp, M, Nfft, X, WK)
 ------------------------------------------------------------------
 wrapper subroutine for forward Fourier transform by FFTPACK5
   a_{k} = \frac{2}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
          *  \cos (\frac{2\pi j k}{Nfft})
   b_{k} = \frac{2}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
          *  \cos (\frac{2\pi j k}{Nfft})
   a_{0} = \frac{1}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
    K = Nfft/2....
   a_{k} = \frac{1}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
          * \cos (\frac{2\pi j k}{Nfft})
 ------------------------------------------------------------------
      subroutine CALYPSO_RFFTMB_t(Nsmp, Nstacksmp, M, Nfft, X, WK)
 ------------------------------------------------------------------
 wrapper subroutine for backward Fourier transform by FFTPACK5
   x_{k} = a_{0} + (-1)^{j} a_{Nfft/2} + sum_{k=1}^{Nfft/2-1}
          (a_{k} \cos(2\pijk/Nfft) + b_{k} \sin(2\pijk/Nfft))
 ------------------------------------------------------------------
       i = 1:     a_{0}
       i = 2:     a_{Nfft/2}
       i = 3:     a_{1}
       i = 4:     b_{1}
       ...
       i = 2*k+1: a_{k}
       i = 2*k+2: b_{k}
       ...
       i = Nfft-1:   a_{Nfft/2-1}
       i = Nfft:     b_{Nfft/2-1}
 ------------------------------------------------------------------
Parameters
Nsmp Number of SMP processors
Nstacksmp(0:Nsmp) End number for each SMP process
M Number of components for Fourier transforms
Nfft Data length for eadh FFT
X(M,Nfft) Data for Fourier transform
WK Work structure for FFTPACK5
Function/Subroutine Documentation
alloc_const_4_fftpack_t()
subroutine, private t_fftpack5_wrapper::alloc_const_4_fftpack_t (integer(kind = kint), intent(in) nfft, type(working_fftpack), intent(inout) WK) private
Definition at line 239 of file t_FFTPACK5_wrapper.f90.
References m_constants::ifour, and m_constants::two.
Referenced by init_wk_fftpack_t(), and verify_wk_fftpack_t().
alloc_work_4_fftpack_t()
subroutine, private t_fftpack5_wrapper::alloc_work_4_fftpack_t (integer(kind = kint), intent(in) Nsmp, integer(kind = kint), intent(in) Nfft, type(working_fftpack), intent(inout) WK) private
Definition at line 224 of file t_FFTPACK5_wrapper.f90.
Referenced by init_wk_fftpack_t(), and verify_wk_fftpack_t().
calypso_rfftmb_t()
subroutine t_fftpack5_wrapper::calypso_rfftmb_t (integer(kind = kint), intent(in) Nsmp, integer(kind = kint), dimension(0:nsmp), intent(in) Nstacksmp, integer(kind = kint), intent(in) M, integer(kind = kint), intent(in) Nfft, real(kind = kreal), dimension(m,nfft), intent(inout) X, type(working_fftpack), intent(inout) WK)
Definition at line 204 of file t_FFTPACK5_wrapper.f90.
References fftpack5_wrapper::calypso_rfftmb_smp().
Referenced by t_fft_selector::backward_fft_select(), and test_fftpack5().
calypso_rfftmf_t()
subroutine t_fftpack5_wrapper::calypso_rfftmf_t (integer(kind = kint), intent(in) Nsmp, integer(kind = kint), dimension(0:nsmp), intent(in) Nstacksmp, integer(kind = kint), intent(in) M, integer(kind = kint), intent(in) Nfft, real(kind = kreal), dimension(m, nfft), intent(inout) X, type(working_fftpack), intent(inout) WK)
Definition at line 185 of file t_FFTPACK5_wrapper.f90.
References fftpack5_wrapper::calypso_rfftmf_smp().
Referenced by t_fft_selector::forward_fft_select(), and test_fftpack5().
dealloc_const_fftpack_t()
subroutine, private t_fftpack5_wrapper::dealloc_const_fftpack_t (type(working_fftpack), intent(inout) WK) private
Definition at line 268 of file t_FFTPACK5_wrapper.f90.
Referenced by finalize_wk_fftpack_t(), and verify_wk_fftpack_t().
dealloc_work_4_fftpack_t()
subroutine, private t_fftpack5_wrapper::dealloc_work_4_fftpack_t (type(working_fftpack), intent(inout) WK) private
Definition at line 256 of file t_FFTPACK5_wrapper.f90.
Referenced by finalize_wk_fftpack_t(), and verify_wk_fftpack_t().
finalize_wk_fftpack_t()
subroutine t_fftpack5_wrapper::finalize_wk_fftpack_t (type(working_fftpack), intent(inout) WK)
Definition at line 130 of file t_FFTPACK5_wrapper.f90.
References dealloc_const_fftpack_t(), and dealloc_work_4_fftpack_t().
Referenced by t_fft_selector::finalize_fft_sel_t().
init_wk_fftpack_t()
subroutine t_fftpack5_wrapper::init_wk_fftpack_t (integer(kind = kint), intent(in) Nsmp, integer(kind = kint), dimension(0:nsmp), intent(in) Nstacksmp, integer(kind = kint), intent(in) Nfft, type(working_fftpack), intent(inout) WK)
Definition at line 102 of file t_FFTPACK5_wrapper.f90.
References alloc_const_4_fftpack_t(), alloc_work_4_fftpack_t(), and fftpack5_wrapper::init_calypso_fftpack().
Referenced by t_fft_selector::initialize_fft_select(), and test_fftpack5().
verify_wk_fftpack_t()
subroutine t_fftpack5_wrapper::verify_wk_fftpack_t (integer(kind = kint), intent(in) Nsmp, integer(kind = kint), dimension(0:nsmp), intent(in) Nstacksmp, integer(kind = kint), intent(in) Nfft, type(working_fftpack), intent(inout) WK)
Definition at line 142 of file t_FFTPACK5_wrapper.f90.
References alloc_const_4_fftpack_t(), alloc_work_4_fftpack_t(), dealloc_const_fftpack_t(), dealloc_work_4_fftpack_t(), and fftpack5_wrapper::init_calypso_fftpack().
Referenced by t_fft_selector::verify_fft_select().