CALYPSO: t_control_array_real Module Reference
t_control_array_real Module Reference
Data Types
type ctl_array_real
Structure for real control array.
type read_real_item
structure of control real item
Functions/Subroutines
subroutine read_real_ctl_type (c_buf, label, real_item)
subroutine write_real_ctl_type (id_file, level, maxlen, label, real_item)
subroutine copy_real_ctl (org_r1, new_r1)
subroutine alloc_control_array_real (array_real)
subroutine dealloc_control_array_real (array_real)
subroutine read_control_array_r1 (id_control, label, array_real, c_buf)
subroutine write_control_array_r1 (id_control, level, label, array_real)
subroutine append_control_array_real (read_r1, array_r1)
subroutine copy_control_array_real (num_copy, org_r1, tgt_r1)
subroutine append_control_item_real (read_r1, array_r1)
Function/Subroutine Documentation
alloc_control_array_real()
subroutine t_control_array_real::alloc_control_array_real (type(ctl_array_real), intent(inout) array_real)
Definition at line 128 of file t_control_array_real.f90.
Referenced by append_control_array_real(), bcast_control_arrays::bcast_ctl_array_r1(), and read_control_array_r1().
append_control_array_real()
subroutine t_control_array_real::append_control_array_real (type(read_real_item), intent(inout) read_r1, type(ctl_array_real), intent(inout) array_r1)
Definition at line 220 of file t_control_array_real.f90.
References alloc_control_array_real(), append_control_item_real(), copy_control_array_real(), and dealloc_control_array_real().
Referenced by read_control_array_r1().
append_control_item_real()
subroutine t_control_array_real::append_control_item_real (type(read_real_item), intent(in) read_r1, type(ctl_array_real), intent(inout) array_r1)
Definition at line 260 of file t_control_array_real.f90.
Referenced by append_control_array_real().
copy_control_array_real()
subroutine t_control_array_real::copy_control_array_real (integer(kind = kint), intent(in) num_copy, type(ctl_array_real), intent(in) org_r1, type(ctl_array_real), intent(inout) tgt_r1)
Definition at line 245 of file t_control_array_real.f90.
Referenced by append_control_array_real().
copy_real_ctl()
subroutine t_control_array_real::copy_real_ctl (type(read_real_item), intent(in) org_r1, type(read_real_item), intent(inout) new_r1)
Definition at line 114 of file t_control_array_real.f90.
Referenced by t_ctl_data_sph_vol_spectr::copy_volume_spectr_control(), t_control_data_4_psf_def::dup_control_4_psf_def(), t_control_data_4_fld_on_psf::dup_fld_on_psf_control(), and t_control_data_surfacings::section_step_ctls_to_time_ctl().
dealloc_control_array_real()
subroutine t_control_array_real::dealloc_control_array_real (type(ctl_array_real), intent(inout) array_real)
Definition at line 142 of file t_control_array_real.f90.
Referenced by append_control_array_real().
read_control_array_r1()
subroutine t_control_array_real::read_control_array_r1 (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) label, type(ctl_array_real), intent(inout) array_real, type(buffer_for_control), intent(inout) c_buf)
Definition at line 156 of file t_control_array_real.f90.
References alloc_control_array_real(), append_control_array_real(), t_read_control_elements::check_array_flag(), t_read_control_elements::check_end_array_flag(), t_read_control_elements::load_one_line_from_control(), and read_real_ctl_type().
read_real_ctl_type()
subroutine t_control_array_real::read_real_ctl_type (type(buffer_for_control), intent(in) c_buf, character(len=kchara), intent(in) label, type(read_real_item), intent(inout) real_item)
Definition at line 73 of file t_control_array_real.f90.
References m_machine_parameter::iflag_debug.
Referenced by read_control_array_r1(), t_ctl_data_4_sphere_model::read_control_shell_define(), t_ctl_data_4_time_steps::read_control_time_step_data(), t_ctl_data_sph_vol_spectr::read_each_vol_spectr_ctl(), t_control_data_4_fld_on_psf::read_fld_on_psf_control(), t_ctl_data_pick_sph_spectr::read_gauss_spectr_ctl(), t_mid_equator_control::read_mid_eq_monitor_ctl(), t_control_data_4_merge::read_newrst_control(), t_ctl_data_temp_model::read_ref_comp_ctl(), t_ctl_data_temp_model::read_ref_temp_ctl(), t_control_data_4_psf_def::read_section_def_control(), t_control_data_surfacings::read_surfacing_controls(), t_ctl_data_temp_model::read_takepiro_ctl(), and t_ctl_data_mhd_evo_scheme::read_time_loop_ctl().
write_control_array_r1()
subroutine t_control_array_real::write_control_array_r1 (integer(kind = kint), intent(in) id_control, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, type(ctl_array_real), intent(in) array_real)
Definition at line 190 of file t_control_array_real.f90.
References write_control_elements::write_array_flag_for_ctl(), write_control_elements::write_end_array_flag_for_ctl(), and write_control_elements::write_real_ctl_item().
write_real_ctl_type()
subroutine t_control_array_real::write_real_ctl_type (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, integer(kind = kint), intent(in) maxlen, character(len=kchara), intent(in) label, type(read_real_item), intent(in) real_item)
Definition at line 95 of file t_control_array_real.f90.
References write_control_elements::write_real_ctl_item().
Referenced by t_ctl_data_4_time_steps::write_control_time_step_data().