CALYPSO: set_control_sph_data_mhd Module Reference
set_control_sph_data_mhd Module Reference
Set control parameters for spherical harmonics dynamo from IO.
Functions/Subroutines
subroutine set_control_sph_mhd_fields (MHD_prop, field_ctl, rj_fld)
subroutine s_set_control_sph_data_mhd (plt, mevo_ctl, rj_org_param, rst_org_param, fst_file_IO, bc_IO, trans_p, WK_leg)
Detailed Description
Set control parameters for spherical harmonics dynamo from IO.
      subroutine set_control_sph_mhd_fields                           &
     &        (MHD_prop, field_ctl, rj_fld)
      subroutine s_set_control_sph_data_MHD                           &
     &         (plt, mevo_ctl, rj_org_param, rst_org_param,           &
     &          fst_file_IO, bc_IO, trans_p, WK_leg)
        type(fluid_property), intent(in) :: fl_prop
        type(MHD_evolution_param), intent(in) :: MHD_prop
        type(platform_data_control), intent(in) :: plt
        type(ctl_array_c3), intent(inout) :: field_ctl
        type(field_IO_params), intent(in) :: rj_org_param
        type(field_IO_params), intent(in) :: rst_org_param
        type(field_IO_params), intent(inout) :: fst_file_IO
        type(boundary_spectra), intent(inout) :: bc_IO
        type(phys_data), intent(inout) :: rj_fld
        type(parameters_4_sph_trans), intent(inout) :: trans_p
        type(legendre_trns_works), intent(inout) :: WK_leg
Function/Subroutine Documentation
s_set_control_sph_data_mhd()
subroutine set_control_sph_data_mhd::s_set_control_sph_data_mhd (type(platform_data_control), intent(in) plt, type(mhd_evo_scheme_control), intent(in) mevo_ctl, type(field_io_params), intent(in) rj_org_param, type(field_io_params), intent(in) rst_org_param, type(field_io_params), intent(inout) fst_file_IO, type(boundary_spectra), intent(inout) bc_IO, type(parameters_4_sph_trans), intent(inout) trans_p, type(legendre_trns_works), intent(inout) WK_leg)
Definition at line 89 of file set_control_sph_data_MHD.f90.
References m_fft_selector::set_fft_library_ctl(), t_work_4_sph_trans::set_import_table_ctl(), and m_legendre_transform_list::set_legendre_trans_mode_ctl().
Referenced by set_control_sph_mhd::set_control_4_sph_mhd().
set_control_sph_mhd_fields()
subroutine set_control_sph_data_mhd::set_control_sph_mhd_fields (type(mhd_evolution_param), intent(in) MHD_prop, type(ctl_array_c3), intent(inout) field_ctl, type(phys_data), intent(inout) rj_fld)
Definition at line 40 of file set_control_sph_data_MHD.f90.
References add_nodal_fields_4_mhd::add_dependent_field(), add_nodal_fields_4_mhd::add_field_name_4_mhd(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), calypso_mpi::calypso_mpi_abort(), m_error_ids::ierr_fld, m_machine_parameter::iflag_debug, and set_control_field_data::s_set_control_field_data().
Referenced by set_control_sph_mhd::set_control_sph_mhd_noviz(), and set_control_sph_mhd::set_control_sph_mhd_w_viz().