CALYPSO: select_exp_velocity_cmb Module Reference
select_exp_velocity_cmb Module Reference
Select boundary condition routines for velocity.
Functions/Subroutines
subroutine sel_cmb_grad_vp_and_vorticity (sph_rj, sph_bc_U, CMB_Uspec, fdm2_free_CMB, g_sph_rj, is_velo, is_vort, rj_fld)
subroutine sel_cmb_grad_poloidal_moment (sph_rj, sph_bc_U, CMB_Uspec, fdm2_free_CMB, is_fld, rj_fld)
subroutine sel_cmb_sph_vorticity (sph_rj, sph_bc_U, fdm2_free_CMB, g_sph_rj, is_fld, is_rot, rj_fld)
subroutine sel_cmb_sph_viscous_diffusion (sph_rj, sph_bc_U, fdm2_free_CMB, g_sph_rj, coef_diffuse, is_velo, is_viscous, rj_fld)
subroutine sel_cmb_sph_vort_diffusion (sph_rj, sph_bc_U, fdm2_free_CMB, g_sph_rj, coef_diffuse, is_vort, is_w_diffuse, rj_fld)
Detailed Description
Select boundary condition routines for velocity.
      subroutine sel_CMB_grad_vp_and_vorticity                        &
     &         (sph_rj, sph_bc_U, CMB_Uspec, fdm2_free_CMB, g_sph_rj, &
     &          is_velo, is_vort, rj_fld)
        Address for input:    is_velo
        Address for solution: is_velo+1,
                              is_vort, is_vort+2, is_vort+1
      subroutine sel_CMB_grad_poloidal_moment                         &
     &         (sph_rj, sph_bc_U, CMB_Uspec, fdm2_free_CMB,           &
     &          is_fld, rj_fld)
        Address for input:    is_fld, is_fld+2
        Address for solution: is_fld+1
      subroutine sel_CMB_sph_vorticity                                &
     &         (sph_rj, sph_bc_U, fdm2_free_CMB, g_sph_rj,            &
     &          is_fld, is_rot, rj_fld)
        Address for input:    is_fld, is_fld+2
        Address for solution: is_rot, is_rot+2, is_rot+1
      subroutine sel_CMB_sph_viscous_diffusion(sph_rj, sph_bc_U,      &
     &          fdm2_free_CMB, g_sph_rj, coef_diffuse,                &
     &          is_velo, is_viscous, rj_fld)
        Address for input:    is_velo, is_velo+2, is_velo+1
        Address for solution: is_viscous, is_viscous+2, is_viscous+1
      subroutine sel_CMB_sph_vort_diffusion(sph_rj, sph_bc_U,         &
     &          fdm2_free_CMB, g_sph_rj, coef_diffuse,                &
     &          is_vort, is_w_diffuse, rj_fld)
        Address for input:    is_vort, is_vort+2
        Address for solution: is_w_diffuse, is_w_diffuse+2,
                              is_w_diffuse+1
          type(sph_rj_grid), intent(in) :: sph_rj
          type(sph_boundary_type), intent(in) :: sph_bc_U
          type(sph_vector_BC_coef), intent(in) :: CMB_Uspec
          type(fdm2_free_slip), intent(in) :: fdm2_free_ICB
          type(fdm_matrices), intent(in) :: r_2nd
          type(phys_data), intent(inout) :: rj_fld
Function/Subroutine Documentation
sel_cmb_grad_poloidal_moment()
subroutine select_exp_velocity_cmb::sel_cmb_grad_poloidal_moment (type(sph_rj_grid), intent(in) sph_rj, type(sph_boundary_type), intent(in) sph_bc_U, type(sph_vector_bc_coef), intent(in) CMB_Uspec, type(fdm2_free_slip), intent(in) fdm2_free_CMB, integer(kind = kint), intent(in) is_fld, type(phys_data), intent(inout) rj_fld)
Definition at line 117 of file select_exp_velocity_CMB.f90.
References set_sph_exp_free_cmb::cal_sph_nod_cmb_free_vpol2(), set_sph_exp_fix_vector_cmb::cal_sph_nod_cmb_rigid_vect(), set_sph_exp_rigid_cmb::cal_sph_nod_cmb_rigid_velo(), t_boundary_params_sph_mhd::iflag_evolve_field, t_boundary_params_sph_mhd::iflag_fixed_field, and t_boundary_params_sph_mhd::iflag_free_slip.
Referenced by cal_sol_sph_fluid_crank::cal_sol_velo_by_vort_sph_crank(), and const_sph_radial_grad::const_grad_poloidal_moment().
sel_cmb_grad_vp_and_vorticity()
subroutine select_exp_velocity_cmb::sel_cmb_grad_vp_and_vorticity (type(sph_rj_grid), intent(in) sph_rj, type(sph_boundary_type), intent(in) sph_bc_U, type(sph_vector_bc_coef), intent(in) CMB_Uspec, type(fdm2_free_slip), intent(in) fdm2_free_CMB, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, integer(kind = kint), intent(in) is_velo, integer(kind = kint), intent(in) is_vort, type(phys_data), intent(inout) rj_fld)
Definition at line 72 of file select_exp_velocity_CMB.f90.
References set_sph_exp_fix_vector_cmb::cal_sph_nod_cmb_fixed_rot2(), set_sph_exp_free_cmb::cal_sph_nod_cmb_free_v_and_w(), set_sph_exp_rigid_cmb::cal_sph_nod_cmb_rigid_v_and_w(), set_sph_exp_fix_vector_cmb::cal_sph_nod_cmb_rigid_vect(), t_boundary_params_sph_mhd::iflag_evolve_field, t_boundary_params_sph_mhd::iflag_fixed_field, and t_boundary_params_sph_mhd::iflag_free_slip.
Referenced by const_sph_radial_grad::const_grad_vp_and_vorticity().
sel_cmb_sph_viscous_diffusion()
subroutine select_exp_velocity_cmb::sel_cmb_sph_viscous_diffusion (type(sph_rj_grid), intent(in) sph_rj, type(sph_boundary_type), intent(in) sph_bc_U, type(fdm2_free_slip), intent(in) fdm2_free_CMB, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, real(kind = kreal), intent(in) coef_diffuse, integer(kind = kint), intent(in) is_velo, integer(kind = kint), intent(in) is_viscous, type(phys_data), intent(inout) rj_fld)
Definition at line 193 of file select_exp_velocity_CMB.f90.
References cal_sph_exp_fixed_scalar::cal_dsdr_sph_no_bc_out_2(), set_sph_exp_fix_vector_cmb::cal_sph_nod_cmb_fixed_diffuse2(), set_sph_exp_free_cmb::cal_sph_nod_cmb_free_diffuse2(), set_sph_exp_rigid_cmb::cal_sph_nod_cmb_rigid_diffuse2(), t_boundary_params_sph_mhd::iflag_evolve_field, t_boundary_params_sph_mhd::iflag_fixed_field, and t_boundary_params_sph_mhd::iflag_free_slip.
Referenced by const_sph_rotation::const_sph_viscous_by_vort2(), and const_sph_diffusion::const_sph_viscous_diffusion().
sel_cmb_sph_vort_diffusion()
subroutine select_exp_velocity_cmb::sel_cmb_sph_vort_diffusion (type(sph_rj_grid), intent(in) sph_rj, type(sph_boundary_type), intent(in) sph_bc_U, type(fdm2_free_slip), intent(in) fdm2_free_CMB, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, real(kind = kreal), intent(in) coef_diffuse, integer(kind = kint), intent(in) is_vort, integer(kind = kint), intent(in) is_w_diffuse, type(phys_data), intent(inout) rj_fld)
Definition at line 245 of file select_exp_velocity_CMB.f90.
References cal_sph_exp_fixed_scalar::cal_dsdr_sph_no_bc_in_2(), cal_sph_exp_fixed_scalar::cal_dsdr_sph_no_bc_out_2(), set_sph_exp_fix_vector_cmb::cal_sph_nod_cmb_fixed_diffuse2(), set_sph_exp_free_cmb::cal_sph_nod_cmb_free_w_diffuse2(), and t_boundary_params_sph_mhd::iflag_free_slip.
Referenced by const_sph_diffusion::const_sph_vorticirty_diffusion().
sel_cmb_sph_vorticity()
subroutine select_exp_velocity_cmb::sel_cmb_sph_vorticity (type(sph_rj_grid), intent(in) sph_rj, type(sph_boundary_type), intent(in) sph_bc_U, type(fdm2_free_slip), intent(in) fdm2_free_CMB, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_rot, type(phys_data), intent(inout) rj_fld)
Definition at line 152 of file select_exp_velocity_CMB.f90.
References set_sph_exp_fix_vector_cmb::cal_sph_nod_cmb_fixed_rot2(), set_sph_exp_free_cmb::cal_sph_nod_cmb_free_rot2(), set_sph_exp_rigid_cmb::cal_sph_nod_cmb_rigid_rot2(), t_boundary_params_sph_mhd::iflag_evolve_field, t_boundary_params_sph_mhd::iflag_fixed_field, and t_boundary_params_sph_mhd::iflag_free_slip.
Referenced by const_sph_rotation::const_sph_force_rot2(), and const_sph_rotation::const_sph_vorticity().