CALYPSO: t_sph_1d_global_index Module Reference
t_sph_1d_global_index Module Reference
Global addresses for soherical harmonics indices.
Data Types
type sph_1d_global_index
type sph_1d_index_stack
Functions/Subroutines
subroutine alloc_sph_1d_global_stack (s3d_ranks, stk_lc1d)
subroutine alloc_sph_1d_global_idx (s3d_ranks, stk_lc1d, sph_gl1d)
subroutine dealloc_sph_1d_global_stack (stk_lc1d)
subroutine dealloc_sph_1d_global_idx (sph_gl1d)
subroutine check_spheric_global_stack (id_rank, stk_lc1d)
Detailed Description
Global addresses for soherical harmonics indices.
      subroutine alloc_sph_1d_global_stack(s3d_ranks, stk_lc1d)
        type(sph_1d_index_stack), intent(inout) :: stk_lc1d
      subroutine alloc_sph_1d_global_idx                              &
     &         (s3d_ranks, stk_lc1d, sph_gl1d)
        type(sph_1d_index_stack), intent(in) :: stk_lc1d
        type(sph_1d_global_index), intent(inout) :: sph_gl1d
      subroutine dealloc_sph_1d_global_stack(stk_lc1d)
        type(sph_1d_index_stack), intent(inout) :: stk_lc1d
      subroutine dealloc_sph_1d_global_idx(sph_gl1d)
        type(sph_1d_global_index), intent(inout) :: sph_gl1d
      subroutine check_spheric_global_stack(ip_rank, stk_lc1d)
Function/Subroutine Documentation
alloc_sph_1d_global_idx()
subroutine t_sph_1d_global_index::alloc_sph_1d_global_idx (type(spheric_global_rank), intent(in) s3d_ranks, type(sph_1d_index_stack), intent(in) stk_lc1d, type(sph_1d_global_index), intent(inout) sph_gl1d)
Definition at line 157 of file t_sph_1d_global_index.f90.
Referenced by const_global_sph_grids_modes::const_global_sph_fem_grid(), and const_global_sph_grids_modes::s_const_global_sph_grids_modes().
alloc_sph_1d_global_stack()
subroutine t_sph_1d_global_index::alloc_sph_1d_global_stack (type(spheric_global_rank), intent(in) s3d_ranks, type(sph_1d_index_stack), intent(inout) stk_lc1d)
Definition at line 111 of file t_sph_1d_global_index.f90.
Referenced by const_global_sph_grids_modes::const_global_sph_fem_grid(), and const_global_sph_grids_modes::s_const_global_sph_grids_modes().
check_spheric_global_stack()
subroutine t_sph_1d_global_index::check_spheric_global_stack (integer, intent(in) id_rank, type(sph_1d_index_stack), intent(in) stk_lc1d)
Definition at line 267 of file t_sph_1d_global_index.f90.
dealloc_sph_1d_global_idx()
subroutine t_sph_1d_global_index::dealloc_sph_1d_global_idx (type(sph_1d_global_index), intent(inout) sph_gl1d)
Definition at line 250 of file t_sph_1d_global_index.f90.
Referenced by t_const_spherical_grid::dealloc_gen_mesh_params().
dealloc_sph_1d_global_stack()
subroutine t_sph_1d_global_index::dealloc_sph_1d_global_stack (type(sph_1d_index_stack), intent(inout) stk_lc1d)
Definition at line 227 of file t_sph_1d_global_index.f90.
Referenced by t_const_spherical_grid::dealloc_gen_mesh_params().