CALYPSO: /home/takumi kera/calypso/src/programs/TESTS/FFT_test/test_FFTPACK5.f90 File Reference
test_FFTPACK5.f90 File Reference
Functions/Subroutines
program test_fftpack5
Function/Subroutine Documentation
test_fftpack5()
program test_fftpack5
Definition at line 2 of file test_FFTPACK5.f90.
References t_fftpack5_wrapper::calypso_rfftmb_t(), t_fftpack5_wrapper::calypso_rfftmf_t(), t_fft_test_data::dealloc_fft_test_data(), t_fft_test_data::init_fft_test_data(), t_fftpack5_wrapper::init_wk_fftpack_t(), m_machine_parameter::np_smp, and t_fft_test_data::write_fft_test_data().