CALYPSO: set_time_step_params Module Reference
set_time_step_params Module Reference
Parameteres for time steppings.
Functions/Subroutines
subroutine set_from_initial_step (init_d, time_d)
subroutine s_set_fixed_time_step_params (tctl, init_d, finish_d, ierr, errmsg)
Detailed Description
Parameteres for time steppings.
Function/Subroutine Documentation
s_set_fixed_time_step_params()
subroutine set_time_step_params::s_set_fixed_time_step_params (type(time_data_control), intent(in) tctl, type(time_data), intent(inout) init_d, type(finish_data), intent(inout) finish_d, integer(kind = kint), intent(inout) ierr, character(len=kchara), intent(inout) errmsg)
Definition at line 46 of file set_time_step_params.f90.
References m_error_ids::ierr_evo.
Referenced by t_viz_only_step_parameter::set_fixed_t_step_params_w_viz(), t_mhd_step_parameter::set_fixed_time_step_controls(), and t_step_parameter::set_fixed_time_step_params().
set_from_initial_step()
subroutine set_time_step_params::set_from_initial_step (type(time_data), intent(in) init_d, type(time_data), intent(inout) time_d)
Definition at line 34 of file set_time_step_params.f90.
Referenced by analyzer_sph_dynamobench::evolution_sph_dynamobench(), and analyzer_sph_snap_w_psf::evolution_sph_snap_w_psf().