CALYPSO: t_control_params_4_psf Module Reference
t_control_params_4_psf Module Reference
Data Types
type section_define
Functions/Subroutines
subroutine alloc_coefficients_4_psf (psf_def)
subroutine dealloc_coefficients_4_psf (psf_def)
subroutine count_control_4_psf (psf_c, ele_grp, num_nod_phys, phys_nod_name, psf_fld, psf_param, psf_file_IO, ierr)
subroutine set_control_4_psf (psf_c, ele_grp, sf_grp, num_nod_phys, phys_nod_name, psf_fld, psf_param, psf_def, ierr)
subroutine, private count_control_4_psf_define (psf_def_c, ele_grp, psf_param, ierr)
subroutine, private set_control_psf_define (psf_def_c, ele_grp, sf_grp, psf_param, psf_def, ierr)
subroutine, private count_control_4_field_on_psf (fld_on_psf_c, num_nod_phys, phys_nod_name, psf_fld)
subroutine, private set_control_4_field_on_psf (fld_on_psf_c, num_nod_phys, phys_nod_name, psf_fld, psf_param)
subroutine, private set_merged_psf_file_ctl (default_prefix, file_prefix_ctl, file_format_ctl, ucd_param)
integer(kind=kint) function sel_psf_file_format (file_fmt_ctl)
Variables
character(len=kchara), parameter, private default_psf_prefix = 'psf'
Function/Subroutine Documentation
alloc_coefficients_4_psf()
subroutine t_control_params_4_psf::alloc_coefficients_4_psf (type(section_define), intent(inout) psf_def)
Definition at line 57 of file t_control_params_4_psf.f90.
Referenced by t_cross_section::alloc_psf_field_type().
count_control_4_field_on_psf()
subroutine, private t_control_params_4_psf::count_control_4_field_on_psf (type(field_on_psf_ctl), intent(in) fld_on_psf_c, integer(kind = kint), intent(in) num_nod_phys, character(len=kchara), dimension(num_nod_phys), intent(in) phys_nod_name, type(phys_data), intent(inout) psf_fld) private
Definition at line 236 of file t_control_params_4_psf.f90.
References set_field_comp_for_viz::check_field_4_viz().
Referenced by count_control_4_psf().
count_control_4_psf()
subroutine t_control_params_4_psf::count_control_4_psf (type(psf_ctl), intent(in) psf_c, type(group_data), intent(in) ele_grp, integer(kind = kint), intent(in) num_nod_phys, character(len=kchara), dimension(num_nod_phys), intent(in) phys_nod_name, type(phys_data), intent(inout) psf_fld, type(psf_parameters), intent(inout) psf_param, type(field_io_params), intent(inout) psf_file_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 81 of file t_control_params_4_psf.f90.
References count_control_4_field_on_psf(), count_control_4_psf_define(), default_psf_prefix, m_file_format_switch::iflag_single, and set_merged_psf_file_ctl().
Referenced by set_psf_iso_control::set_psf_control().
count_control_4_psf_define()
subroutine, private t_control_params_4_psf::count_control_4_psf_define (type(psf_define_ctl), intent(in) psf_def_c, type(group_data), intent(in) ele_grp, type(psf_parameters), intent(inout) psf_param, integer(kind = kint), intent(inout) ierr) private
Definition at line 161 of file t_control_params_4_psf.f90.
References set_area_4_viz::count_area_4_viz(), and m_error_ids::ierr_viz.
Referenced by count_control_4_psf().
dealloc_coefficients_4_psf()
subroutine t_control_params_4_psf::dealloc_coefficients_4_psf (type(section_define), intent(inout) psf_def)
Definition at line 69 of file t_control_params_4_psf.f90.
Referenced by t_cross_section::dealloc_psf_field_type().
sel_psf_file_format()
integer(kind = kint) function t_control_params_4_psf::sel_psf_file_format (character(len=kchara), intent(in) file_fmt_ctl)
Definition at line 324 of file t_control_params_4_psf.f90.
References t_multi_flag_labels::check_mul_flags(), m_merged_field_fmt_labels::dealloc_mgd_field_type_flags(), m_field_file_format::iflag_sgl_ucd, m_field_file_format::iflag_sgl_ucd_bin, m_field_file_format::iflag_sgl_ucd_bin_gz, m_field_file_format::iflag_sgl_ucd_gz, m_field_file_format::iflag_sgl_udt, m_field_file_format::iflag_sgl_udt_bin, m_field_file_format::iflag_sgl_udt_bin_gz, m_field_file_format::iflag_sgl_udt_gz, m_field_file_format::iflag_sgl_vtd, m_field_file_format::iflag_sgl_vtd_gz, m_field_file_format::iflag_sgl_vtk, m_field_file_format::iflag_sgl_vtk_gz, m_merged_field_fmt_labels::init_mgd_field_type_flags(), m_merged_field_fmt_labels::mgd_fbin_gz_labels, m_merged_field_fmt_labels::mgd_fld_ascii_labels, m_merged_field_fmt_labels::mgd_fld_bin_labels, m_merged_field_fmt_labels::mgd_fld_gz_labels, m_merged_field_fmt_labels::mgd_iso_gz_labels, m_merged_field_fmt_labels::mgd_iso_labels, m_merged_field_fmt_labels::mgd_psf_gz_labels, m_merged_field_fmt_labels::mgd_psf_labels, m_merged_field_fmt_labels::mgd_ucd_gz_labels, m_merged_field_fmt_labels::mgd_ucd_labels, m_merged_field_fmt_labels::mgd_udt_gz_labels, m_merged_field_fmt_labels::mgd_udt_labels, m_merged_field_fmt_labels::mgd_vtd_gz_labels, m_merged_field_fmt_labels::mgd_vtd_labels, m_merged_field_fmt_labels::mgd_vtk_gz_labels, and m_merged_field_fmt_labels::mgd_vtk_labels.
Referenced by set_merged_psf_file_ctl().
set_control_4_field_on_psf()
subroutine, private t_control_params_4_psf::set_control_4_field_on_psf (type(field_on_psf_ctl), intent(in) fld_on_psf_c, integer(kind = kint), intent(in) num_nod_phys, character(len=kchara), dimension(num_nod_phys), intent(in) phys_nod_name, type(phys_data), intent(inout) psf_fld, type(psf_parameters), intent(inout) psf_param) private
Definition at line 260 of file t_control_params_4_psf.f90.
References set_field_comp_for_viz::set_components_4_viz().
Referenced by set_control_4_psf().
set_control_4_psf()
subroutine t_control_params_4_psf::set_control_4_psf (type(psf_ctl), intent(in) psf_c, type(group_data), intent(in) ele_grp, type(surface_group_data), intent(in) sf_grp, integer(kind = kint), intent(in) num_nod_phys, character(len=kchara), dimension(num_nod_phys), intent(in) phys_nod_name, type(phys_data), intent(inout) psf_fld, type(psf_parameters), intent(inout) psf_param, type(section_define), intent(inout) psf_def, integer(kind = kint), intent(inout) ierr)
Definition at line 126 of file t_control_params_4_psf.f90.
References t_psf_patch_data::alloc_area_group_psf(), t_psf_patch_data::alloc_output_comps_psf(), set_control_4_field_on_psf(), and set_control_psf_define().
Referenced by set_psf_iso_control::set_psf_control().
set_control_psf_define()
subroutine, private t_control_params_4_psf::set_control_psf_define (type(psf_define_ctl), intent(in) psf_def_c, type(group_data), intent(in) ele_grp, type(surface_group_data), intent(in) sf_grp, type(psf_parameters), intent(inout) psf_param, type(section_define), intent(inout) psf_def, integer(kind = kint), intent(inout) ierr) private
Definition at line 192 of file t_control_params_4_psf.f90.
References set_coefs_of_sections::cflag_grp, set_area_4_viz::s_set_area_4_viz(), set_coefs_of_sections::s_set_coefs_of_sections(), and set_area_4_viz::set_surf_grp_id_4_viz().
Referenced by set_control_4_psf().
set_merged_psf_file_ctl()
subroutine, private t_control_params_4_psf::set_merged_psf_file_ctl (character(len = kchara), intent(in) default_prefix, type(read_character_item), intent(in) file_prefix_ctl, type(read_character_item), intent(in) file_format_ctl, type(field_io_params), intent(inout) ucd_param) private
Definition at line 291 of file t_control_params_4_psf.f90.
References m_field_file_format::iflag_sgl_vtk, and sel_psf_file_format().
Referenced by count_control_4_psf().
Variable Documentation
default_psf_prefix
character(len=kchara), parameter, private t_control_params_4_psf::default_psf_prefix = 'psf' private
Definition at line 34 of file t_control_params_4_psf.f90.
Referenced by count_control_4_psf().