CALYPSO: cal_sph_exp_diffusion Module Reference
cal_sph_exp_diffusion Module Reference
Evaluate diffusion term.
Functions/Subroutines
subroutine cal_sph_nod_scalar_diffuse2 (kr_in, kr_out, coef_d, is_fld, is_diffuse, nidx_rj, ar_1d_rj, g_sph_rj, d1nod_mat_fdm_2, d2nod_mat_fdm_2, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_nod_vect_diffuse2 (kr_in, kr_out, coef_d, is_fld, is_diffuse, nidx_rj, ar_1d_rj, g_sph_rj, d2nod_mat_fdm_2, n_point, ntot_phys_rj, d_rj)
Detailed Description
Evaluate diffusion term.
      subroutine cal_sph_nod_scalar_diffuse2(kr_in, kr_out, coef_d,   &
     &          is_fld, is_diffuse, nidx_rj, ar_1d_rj, g_sph_rj,      &
     &          d1nod_mat_fdm_2, d2nod_mat_fdm_2,                     &
     &          n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_nod_vect_diffuse2(kr_in, kr_out, coef_d,     &
     &          is_fld, is_diffuse, nidx_rj, ar_1d_rj, g_sph_rj,      &
     &          d2nod_mat_fdm_2, n_point, ntot_phys_rj, d_rj)
Parameters
kr_in radial ID for inner boundary
kr_out radial ID for outer boundary
coef_d Coefficient for diffusion term
Parameters
is_fld Input field address for d_rj
is_diffuse Diffusion term address for d_rj
Parameters
ntot_phys_rj Total number of components
d_rj Spectrum data
Function/Subroutine Documentation
cal_sph_nod_scalar_diffuse2()
subroutine cal_sph_exp_diffusion::cal_sph_nod_scalar_diffuse2 (integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) kr_out, real(kind = kreal), intent(in) coef_d, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_diffuse, integer(kind = kint), dimension(2), intent(in) nidx_rj, real(kind = kreal), dimension(nidx_rj(1),3), intent(in) ar_1d_rj, real(kind = kreal), dimension(nidx_rj(2),13), intent(in) g_sph_rj, real(kind = kreal), dimension(nidx_rj(1),-1:1), intent(in) d1nod_mat_fdm_2, real(kind = kreal), dimension(nidx_rj(1),-1:1), intent(in) d2nod_mat_fdm_2, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 42 of file cal_sph_exp_diffusion.f90.
References m_constants::two.
Referenced by const_sph_diffusion::const_sph_scalar_diffusion().
cal_sph_nod_vect_diffuse2()
subroutine cal_sph_exp_diffusion::cal_sph_nod_vect_diffuse2 (integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) kr_out, real(kind = kreal), intent(in) coef_d, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_diffuse, integer(kind = kint), dimension(2), intent(in) nidx_rj, real(kind = kreal), dimension(nidx_rj(1),3), intent(in) ar_1d_rj, real(kind = kreal), dimension(nidx_rj(2),13), intent(in) g_sph_rj, real(kind = kreal), dimension(nidx_rj(1),-1:1), intent(in) d2nod_mat_fdm_2, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 96 of file cal_sph_exp_diffusion.f90.
Referenced by const_sph_diffusion::const_sph_magnetic_diffusion(), const_sph_diffusion::const_sph_viscous_diffusion(), and const_sph_diffusion::const_sph_vorticirty_diffusion().