CALYPSO: gz_write_udt_file_io_b Module Reference
gz_write_udt_file_io_b Module Reference
Output merged VTK or UCD file usging MPI-IO.
Functions/Subroutines
subroutine gz_write_ucd_file_mpi_b (gzip_name, t_IO, ucd)
subroutine gz_write_ucd_phys_mpi_b (gzip_name, t_IO, ucd)
subroutine gz_write_ucd_grid_mpi_b (gzip_name, ucd)
Variables
type(calypso_mpi_io_params), private io_param
Detailed Description
Output merged VTK or UCD file usging MPI-IO.
      subroutine gz_write_ucd_file_mpi_b(gzip_name, t_IO, ucd)
      subroutine gz_write_ucd_phys_mpi_b(gzip_name, t_IO, ucd)
      subroutine gz_write_ucd_grid_mpi_b(gzip_name, ucd)
        type(time_data), intent(in) :: t_IO
        type(ucd_data), intent(in) :: ucd
Function/Subroutine Documentation
gz_write_ucd_file_mpi_b()
subroutine gz_write_udt_file_io_b::gz_write_ucd_file_mpi_b (character(len=kchara), intent(in) gzip_name, type(time_data), intent(in) t_IO, type(ucd_data), intent(in) ucd)
Definition at line 41 of file gz_write_udt_file_IO_b.f90.
References mpi_ascii_data_io::close_mpi_file(), gz_ucd_file_mpi_io::gz_mpi_write_ucd_mesh_data_b(), gz_field_block_mpi_io_b::gz_write_field_time_mpi_b(), gz_ucd_file_mpi_io::gz_write_ucd_data_mpi_b(), io_param, calypso_mpi::my_rank, and gz_mpi_binary_datum_io::open_write_gz_mpi_file_b().
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_file().
gz_write_ucd_grid_mpi_b()
subroutine gz_write_udt_file_io_b::gz_write_ucd_grid_mpi_b (character(len=kchara), intent(in) gzip_name, type(ucd_data), intent(in) ucd)
Definition at line 110 of file gz_write_udt_file_IO_b.f90.
References gz_ucd_file_mpi_io::gz_mpi_write_ucd_mesh_data_b(), m_machine_parameter::i_debug, io_param, calypso_mpi::my_rank, and gz_mpi_binary_datum_io::open_write_gz_mpi_file_b().
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_mesh().
gz_write_ucd_phys_mpi_b()
subroutine gz_write_udt_file_io_b::gz_write_ucd_phys_mpi_b (character(len=kchara), intent(in) gzip_name, type(time_data), intent(in) t_IO, type(ucd_data), intent(in) ucd)
Definition at line 78 of file gz_write_udt_file_IO_b.f90.
References mpi_ascii_data_io::close_mpi_file(), gz_field_block_mpi_io_b::gz_write_field_time_mpi_b(), gz_ucd_file_mpi_io::gz_write_ucd_data_mpi_b(), io_param, calypso_mpi::my_rank, and gz_mpi_binary_datum_io::open_write_gz_mpi_file_b().
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_file().
Variable Documentation
io_param
type(calypso_mpi_io_params), private gz_write_udt_file_io_b::io_param private
Definition at line 33 of file gz_write_udt_file_IO_b.f90.
Referenced by gz_write_ucd_file_mpi_b(), gz_write_ucd_grid_mpi_b(), and gz_write_ucd_phys_mpi_b().