CALYPSO: udt_data_io Module Reference
udt_data_io Module Reference
Output routine for UCD data segments.
Functions/Subroutines
subroutine write_udt_field_header (id_ucd, num_output, ncomp_out, name_out)
subroutine write_ucd_field_data (id_ucd, ntot_out, ncomp_dat, nnod, inod_out, dat_out)
subroutine write_udt_mesh_header (id_ucd, nnod_output, nele_out, ncomp_output)
subroutine write_ucd_mesh_connect (id_ucd, ntot_ele, nnod_ele, nele, iele_gl, ie_gl)
subroutine read_udt_field_num (id_ucd, num_input)
subroutine read_udt_field_name (id_ucd, num_input, ncomp_in, name_in)
subroutine read_ucd_field_data (id_ucd, nnod_in, ncomp_dat, dat_in)
subroutine read_ucd_mesh_header (id_ucd, nnod_in, nele_in, ntot_comp)
subroutine read_ucd_node_data (id_ucd, nnod_in, inod_gl, xx_in)
subroutine read_ucd_ele_connect (id_ucd, nele_in, nnod_ele, iele_gl, ie_in)
Detailed Description
Output routine for UCD data segments.
      subroutine write_udt_field_header                               &
     &         (id_ucd, num_output, ncomp_out, name_out)
      subroutine write_ucd_field_data                                 &
     &         (id_ucd, ntot_out, ncomp_dat, nnod, inod_out, dat_out)
      subroutine write_udt_mesh_header                                &
     &         (id_ucd, nnod_output, nele_out, ncomp_output)
      subroutine write_ucd_mesh_connect                               &
     &         (id_ucd, ntot_ele, nnod_ele, nele, iele_gl, ie_gl)
      subroutine read_udt_field_num(id_ucd, num_input)
      subroutine read_udt_field_name                                  &
     &         (id_ucd, num_input, ncomp_in, name_in)
      subroutine read_ucd_field_data                                  &
     &         (id_ucd, nnod_in, ncomp_dat, dat_in)
      subroutine read_ucd_mesh_header                                 &
     &         (id_ucd, nnod_in, nele_in, ntot_comp)
      subroutine read_ucd_node_data(id_ucd, nnod_in, inod_gl, xx_in)
      subroutine read_ucd_ele_connect                                 &
     &         (id_ucd, nele_in, nnod_ele, iele_gl, ie_in)
Function/Subroutine Documentation
read_ucd_ele_connect()
subroutine udt_data_io::read_ucd_ele_connect (integer(kind=kint), intent(in) id_ucd, integer(kind=kint_gl), intent(in) nele_in, integer(kind=kint), intent(in) nnod_ele, integer(kind=kint_gl), dimension(nele_in), intent(inout) iele_gl, integer(kind=kint_gl), dimension(nele_in,nnod_ele), intent(inout) ie_in)
Definition at line 220 of file udt_data_IO.f90.
References ucd_data_to_buffer::nnod_ele_by_ucd_eletype().
Referenced by udt_type_data_io::read_ucd_mesh_data().
read_ucd_field_data()
subroutine udt_data_io::read_ucd_field_data (integer(kind = kint), intent(in) id_ucd, integer(kind = kint_gl), intent(in) nnod_in, integer(kind = kint), intent(in) ncomp_dat, real(kind = kreal), dimension(nnod_in, ncomp_dat), intent(inout) dat_in)
Definition at line 168 of file udt_data_IO.f90.
Referenced by udt_file_io::read_alloc_ucd_file(), udt_file_io::read_alloc_udt_file(), and udt_type_data_io::read_udt_field().
read_ucd_mesh_header()
subroutine udt_data_io::read_ucd_mesh_header (integer(kind = kint), intent(in) id_ucd, integer(kind = kint_gl), intent(inout) nnod_in, integer(kind = kint_gl), intent(inout) nele_in, integer(kind = kint), intent(inout) ntot_comp)
Definition at line 187 of file udt_data_IO.f90.
Referenced by udt_type_data_io::read_alloc_ucd_mesh_data(), and udt_type_data_io::read_ucd_mesh_data().
read_ucd_node_data()
subroutine udt_data_io::read_ucd_node_data (integer(kind=kint), intent(in) id_ucd, integer(kind=kint_gl), intent(in) nnod_in, integer(kind=kint_gl), dimension(nnod_in), intent(inout) inod_gl, real(kind = kreal), dimension(nnod_in,3), intent(inout) xx_in)
Definition at line 202 of file udt_data_IO.f90.
Referenced by udt_type_data_io::read_alloc_ucd_mesh_data(), and udt_type_data_io::read_ucd_mesh_data().
read_udt_field_name()
subroutine udt_data_io::read_udt_field_name (integer(kind = kint), intent(in) id_ucd, integer(kind = kint), intent(in) num_input, integer(kind = kint), dimension(num_input), intent(inout) ncomp_in, character(len = kchara), dimension(num_input), intent(inout) name_in)
Definition at line 145 of file udt_data_IO.f90.
Referenced by udt_type_data_io::read_alloc_udt_field(), and udt_type_data_io::read_udt_field().
read_udt_field_num()
subroutine udt_data_io::read_udt_field_num (integer(kind = kint), intent(in) id_ucd, integer(kind = kint), intent(inout) num_input)
Definition at line 131 of file udt_data_IO.f90.
Referenced by udt_type_data_io::read_alloc_udt_field().
write_ucd_field_data()
subroutine udt_data_io::write_ucd_field_data (integer(kind = kint), intent(in) id_ucd, integer(kind = kint_gl), intent(in) ntot_out, integer(kind = kint), intent(in) ncomp_dat, integer(kind = kint_gl), intent(in) nnod, integer(kind = kint_gl), dimension(ntot_out), intent(in) inod_out, real(kind = kreal), dimension(ntot_out, ncomp_dat), intent(in) dat_out)
Definition at line 66 of file udt_data_IO.f90.
Referenced by udt_type_data_io::write_ucd_type_mesh(), and udt_type_data_io::write_udt_type_fields().
write_ucd_mesh_connect()
subroutine udt_data_io::write_ucd_mesh_connect (integer(kind = kint), intent(in) id_ucd, integer(kind = kint_gl), intent(in) ntot_ele, integer(kind = kint), intent(in) nnod_ele, integer(kind = kint_gl), intent(in) nele, integer(kind = kint_gl), dimension(ntot_ele), intent(in) iele_gl, integer(kind = kint_gl), dimension(ntot_ele,nnod_ele), intent(in) ie_gl)
Definition at line 105 of file udt_data_IO.f90.
References m_constants::ione, and ucd_data_to_buffer::ucd_eletype().
Referenced by udt_type_data_io::write_ucd_type_mesh().
write_udt_field_header()
subroutine udt_data_io::write_udt_field_header (integer(kind = kint), intent(in) id_ucd, integer(kind = kint), intent(in) num_output, integer(kind = kint), dimension(num_output), intent(in) ncomp_out, character(len = kchara), dimension(num_output), intent(in) name_out)
Definition at line 45 of file udt_data_IO.f90.
References ucd_data_to_buffer::ucd_field_name(), and ucd_data_to_buffer::ucd_num_comps().
Referenced by udt_type_data_io::write_udt_type_fields().
write_udt_mesh_header()
subroutine udt_data_io::write_udt_mesh_header (integer(kind = kint), intent(in) id_ucd, integer(kind = kint_gl), intent(in) nnod_output, integer(kind = kint_gl), intent(in) nele_out, integer(kind = kint), intent(in) ncomp_output)
Definition at line 90 of file udt_data_IO.f90.
References m_constants::izero.
Referenced by udt_type_data_io::write_ucd_type_mesh().