CALYPSO: cal_sph_exp_fixed_flux Module Reference
cal_sph_exp_fixed_flux Module Reference
Evaluate scalar fields using fixed flux condition.
Functions/Subroutines
subroutine dsdr_sph_in_fix_flux_2 (jmax, g_sph_rj, kr_in, r_ICB, flux_ICB, is_fld, is_grd, n_point, ntot_phys_rj, d_rj)
subroutine dsdr_sph_lm0_in_fix_flux_2 (idx_rj_degree_zero, jmax, kr_in, r_ICB, flux_ICB, is_grd, n_point, ntot_phys_rj, d_rj)
subroutine cal_div_sph_in_fix_flux_2 (jmax, g_sph_rj, kr_in, r_ICB, flux_ICB, is_fld, is_div, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_in_fix_flux_diffuse2 (jmax, g_sph_rj, kr_in, r_ICB, fdm2_fix_dr_ICB, flux_ICB, coef_d, is_fld, is_diffuse, n_point, ntot_phys_rj, d_rj)
subroutine dsdr_sph_out_fix_flux_2 (jmax, g_sph_rj, kr_out, r_CMB, flux_CMB, is_fld, is_grd, n_point, ntot_phys_rj, d_rj)
subroutine dsdr_sph_lm0_out_fix_flux_2 (idx_rj_degree_zero, jmax, kr_out, r_CMB, flux_CMB, is_grd, n_point, ntot_phys_rj, d_rj)
subroutine cal_div_sph_out_fix_flux_2 (jmax, g_sph_rj, kr_out, r_CMB, flux_CMB, is_fld, is_div, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_out_fix_flux_diffuse2 (jmax, g_sph_rj, kr_out, r_CMB, fdm2_fix_dr_CMB, flux_OUT, coef_d, is_fld, is_diffuse, n_point, ntot_phys_rj, d_rj)
Detailed Description
Evaluate scalar fields using fixed flux condition.
      subroutine dsdr_sph_in_fix_flux_2                               &
     &         (jmax, g_sph_rj, kr_in, r_ICB, flux_ICB,               &
     &          is_fld, is_grd, n_point, ntot_phys_rj, d_rj)
      subroutine dsdr_sph_lm0_in_fix_flux_2(idx_rj_degree_zero,       &
     &          jmax, kr_in, r_ICB, flux_ICB, is_grd,                 &
     &          n_point, ntot_phys_rj, d_rj)
      subroutine cal_div_sph_in_fix_flux_2                            &
     &         (jmax, g_sph_rj, kr_in, r_ICB, flux_ICB,               &
     &          is_fld, is_div, n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_in_fix_flux_diffuse2(jmax, g_sph_rj,         &
     &          kr_in, r_ICB, fdm2_fix_dr_ICB, flux_ICB, coef_d,      &
     &          is_fld, is_diffuse, n_point, ntot_phys_rj, d_rj)
      subroutine dsdr_sph_out_fix_flux_2(jmax, g_sph_rj,              &
     &          kr_out, r_CMB, flux_CMB, is_fld, is_grd,              &
     &          n_point, ntot_phys_rj, d_rj)
      subroutine dsdr_sph_lm0_out_fix_flux_2(idx_rj_degree_zero,      &
     &          jmax, kr_out, r_CMB, flux_CMB, is_grd,                &
     &          n_point, ntot_phys_rj, d_rj)
      subroutine cal_div_sph_out_fix_flux_2(jmax, g_sph_rj,           &
     &          kr_out, r_CMB, flux_CMB, is_fld, is_div,              &
     &          n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_out_fix_flux_diffuse2(jmax, g_sph_rj,        &
     &          kr_out, r_CMB, fdm2_fix_dr_CMB, flux_OUT, coef_d,     &
     &          is_fld, is_diffuse, n_point, ntot_phys_rj, d_rj)
Parameters
idx_rj_degree_zero Local address for degree 0
n_point Number of points for spectrum data
jmax Number of modes for spherical harmonics \(L*(L+2)\)
g_sph_rj(jmax,13) Normalization coefficients
j0 Local harmonics mode address for l = m = 0
kr_in Radial ID for inner boundary
kr_out Radial ID for outer boundary
r_ICB(0:2) Radius at ICB
r_CMB(0:2) Radius at CMB
r_CTR1(0:2) Radius at innermost point
flux_ICB(jamx) Spectrum of fixed flux at ICB
flux_CMB(jamx) Spectrum of fixed flux at CMB
fdm2_fix_dr_ICB(-1:1,3) Matrix to evaluate field at ICB with fixed radial derivative
fdm2_fix_dr_CMB(-1:1,3) Matrix to evaluate field at CMB with fixed radial derivative
Parameters
coef_d Coefficient for diffusion term
Parameters
is_fld Address of spectrum data d_rj (poloidal component for vector)
is_grd Address of gradient of spectrum data d_rj (poloidal component)
is_div Address of divergence of spectrum data d_rj
is_diffuse Address of divergence of spectrum data d_rj (poloidal component for vector)
Parameters
ntot_phys_rj Total number of components
d_rj Spectrum data
Function/Subroutine Documentation
cal_div_sph_in_fix_flux_2()
subroutine cal_sph_exp_fixed_flux::cal_div_sph_in_fix_flux_2 (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(0:2), intent(in) r_ICB, real(kind = kreal), dimension(jmax), intent(in) flux_ICB, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_div, integer (kind = kint), intent(in) n_point, integer (kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 134 of file cal_sph_exp_fixed_flux.f90.
References m_constants::half.
Referenced by select_exp_scalar_icb::sel_icb_sph_scalar_advect().
cal_div_sph_out_fix_flux_2()
subroutine cal_sph_exp_fixed_flux::cal_div_sph_out_fix_flux_2 (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_out, real(kind = kreal), dimension(0:2), intent(in) r_CMB, real(kind = kreal), dimension(jmax), intent(in) flux_CMB, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_div, integer (kind = kint), intent(in) n_point, integer (kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 253 of file cal_sph_exp_fixed_flux.f90.
References m_constants::half.
Referenced by select_exp_scalar_cmb::sel_cmb_sph_scalar_advect().
cal_sph_in_fix_flux_diffuse2()
subroutine cal_sph_exp_fixed_flux::cal_sph_in_fix_flux_diffuse2 (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(0:2), intent(in) r_ICB, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_fix_dr_ICB, real(kind = kreal), dimension(jmax), intent(in) flux_ICB, real(kind = kreal), intent(in) coef_d, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_diffuse, integer (kind = kint), intent(in) n_point, integer (kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 161 of file cal_sph_exp_fixed_flux.f90.
References m_constants::two.
Referenced by select_exp_scalar_icb::sel_icb_sph_scalar_diffusion().
cal_sph_out_fix_flux_diffuse2()
subroutine cal_sph_exp_fixed_flux::cal_sph_out_fix_flux_diffuse2 (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_out, real(kind = kreal), dimension(0:2), intent(in) r_CMB, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_fix_dr_CMB, real(kind = kreal), dimension(jmax), intent(in) flux_OUT, real(kind = kreal), intent(in) coef_d, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_diffuse, integer (kind = kint), intent(in) n_point, integer (kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 280 of file cal_sph_exp_fixed_flux.f90.
References m_constants::two.
Referenced by select_exp_scalar_cmb::sel_cmb_sph_scalar_diffusion().
dsdr_sph_in_fix_flux_2()
subroutine cal_sph_exp_fixed_flux::dsdr_sph_in_fix_flux_2 (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(0:2), intent(in) r_ICB, real(kind = kreal), dimension(jmax), intent(in) flux_ICB, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_grd, integer (kind = kint), intent(in) n_point, integer (kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 81 of file cal_sph_exp_fixed_flux.f90.
References m_constants::zero.
Referenced by select_exp_scalar_icb::sel_icb_radial_grad_scalar().
dsdr_sph_lm0_in_fix_flux_2()
subroutine cal_sph_exp_fixed_flux::dsdr_sph_lm0_in_fix_flux_2 (integer(kind = kint), intent(in) idx_rj_degree_zero, integer(kind = kint), intent(in) jmax, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(0:2), intent(in) r_ICB, real(kind = kreal), dimension(jmax), intent(in) flux_ICB, integer(kind = kint), intent(in) is_grd, integer (kind = kint), intent(in) n_point, integer (kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 109 of file cal_sph_exp_fixed_flux.f90.
References m_constants::zero.
Referenced by select_exp_scalar_icb::sel_icb_radial_grad_scalar().
dsdr_sph_lm0_out_fix_flux_2()
subroutine cal_sph_exp_fixed_flux::dsdr_sph_lm0_out_fix_flux_2 (integer(kind = kint), intent(in) idx_rj_degree_zero, integer(kind = kint), intent(in) jmax, integer(kind = kint), intent(in) kr_out, real(kind = kreal), dimension(0:2), intent(in) r_CMB, real(kind = kreal), dimension(jmax), intent(in) flux_CMB, integer(kind = kint), intent(in) is_grd, integer (kind = kint), intent(in) n_point, integer (kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 228 of file cal_sph_exp_fixed_flux.f90.
References m_constants::zero.
Referenced by select_exp_scalar_cmb::sel_cmb_radial_grad_scalar().
dsdr_sph_out_fix_flux_2()
subroutine cal_sph_exp_fixed_flux::dsdr_sph_out_fix_flux_2 (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_out, real(kind = kreal), dimension(0:2), intent(in) r_CMB, real(kind = kreal), dimension(jmax), intent(in) flux_CMB, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_grd, integer (kind = kint), intent(in) n_point, integer (kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 200 of file cal_sph_exp_fixed_flux.f90.
References m_constants::zero.
Referenced by select_exp_scalar_cmb::sel_cmb_radial_grad_scalar().