CALYPSO: mpi_ascii_data_io Module Reference
mpi_ascii_data_io Module Reference
Output merged binary field file using MPI-IO.
Functions/Subroutines
subroutine open_write_mpi_file (file_name, IO_param)
subroutine open_append_mpi_file (file_name, IO_param)
subroutine open_read_mpi_file (file_name, num_pe, id_rank, IO_param)
subroutine close_mpi_file (IO_param)
subroutine mpi_write_charahead (IO_param, ilength, chara_dat)
subroutine mpi_write_num_of_data (IO_param, num)
subroutine mpi_write_stack_over_domain (IO_param, num)
subroutine mpi_read_num_of_data (IO_param, num)
character(len=ilength) function mpi_read_charahead (IO_param, ilength)
character(len=ilength) function mpi_read_characters (IO_param, ilength)
subroutine mpi_skip_read (IO_param, ilength)
Detailed Description
Output merged binary field file using MPI-IO.
      subroutine open_write_mpi_file(file_name, IO_param)
      subroutine open_append_mpi_file(file_name, IO_param)
      subroutine open_read_mpi_file                                   &
     &         (file_name, num_pe, id_rank, IO_param)
        Substitution of open_rd_gzfile_b
      subroutine close_mpi_file(IO_param)
      subroutine mpi_write_charahead(IO_param, ilength, chara_dat)
      subroutine mpi_write_num_of_data(IO_param, num)
      subroutine mpi_write_stack_over_domain(IO_param, num)
      subroutine mpi_read_num_of_data(IO_param, num)
      function  mpi_read_charahead(IO_param, ilength)
        character(len=ilength) :: mpi_read_charahead
      function mpi_read_characters(IO_param, ilength)
        character(len=ilength) :: mpi_read_characters
      subroutine mpi_skip_read(IO_param, ilength)
Function/Subroutine Documentation
close_mpi_file()
subroutine mpi_ascii_data_io::close_mpi_file (type(calypso_mpi_io_params), intent(inout) IO_param)
Definition at line 95 of file MPI_ascii_data_IO.f90.
References m_calypso_mpi_io::calypso_close_mpi_file(), and t_calypso_mpi_io_param::dealloc_istack_merge().
Referenced by mpi_picked_sph_spectr_io::append_picked_spectrum_file(), mpi_sph_gauss_coefs_io::append_sph_gauss_coefs_file(), gz_mpi_sph_modes_file_io::gz_mpi_read_geom_rtm_file(), gz_mpi_sph_modes_file_io_b::gz_mpi_read_geom_rtm_file_b(), gz_mpi_sph_modes_file_io::gz_mpi_read_geom_rtp_file(), gz_mpi_sph_modes_file_io_b::gz_mpi_read_geom_rtp_file_b(), gz_mpi_mesh_file_io::gz_mpi_read_geometry_size(), gz_mpi_mesh_file_io_b::gz_mpi_read_geometry_size_b(), gz_mpi_mesh_file_io::gz_mpi_read_mesh(), gz_mpi_mesh_file_io_b::gz_mpi_read_mesh_file_b(), gz_mpi_mesh_file_io::gz_mpi_read_mesh_geometry(), gz_mpi_mesh_file_io_b::gz_mpi_read_mesh_geometry_b(), gz_mpi_sph_modes_file_io::gz_mpi_read_modes_rlm_file(), gz_mpi_sph_modes_file_io_b::gz_mpi_read_modes_rlm_file_b(), gz_mpi_mesh_file_io::gz_mpi_read_node_size(), gz_mpi_mesh_file_io_b::gz_mpi_read_node_size_b(), gz_mpi_sph_modes_file_io::gz_mpi_read_spectr_rj_file(), gz_mpi_sph_modes_file_io_b::gz_mpi_read_spectr_rj_file_b(), gz_mpi_sph_modes_file_io::gz_mpi_write_geom_rtm_file(), gz_mpi_sph_modes_file_io_b::gz_mpi_write_geom_rtm_file_b(), gz_mpi_sph_modes_file_io::gz_mpi_write_geom_rtp_file(), gz_mpi_sph_modes_file_io_b::gz_mpi_write_geom_rtp_file_b(), gz_mpi_mesh_file_io::gz_mpi_write_mesh_file(), gz_mpi_mesh_file_io_b::gz_mpi_write_mesh_file_b(), gz_mpi_sph_modes_file_io::gz_mpi_write_modes_rlm_file(), gz_mpi_sph_modes_file_io_b::gz_mpi_write_modes_rlm_file_b(), gz_mpi_sph_modes_file_io::gz_mpi_write_spectr_rj_file(), gz_mpi_sph_modes_file_io_b::gz_mpi_write_spectr_rj_file_b(), gz_mpi_viewer_mesh_file_io::gz_mpi_write_viewer_mesh_file(), gz_field_file_mpi_io_b::gz_rd_alloc_st_fld_file_mpi_b(), gz_field_file_mpi_io_b::gz_rd_alloc_st_fld_head_mpi_b(), gz_ucd_field_mpi_io_b::gz_rd_alloc_ucd_fld_file_mpi_b(), gz_field_file_mpi_io_b::gz_read_step_field_file_mpi_b(), gz_ucd_field_mpi_io_b::gz_read_ucd_field_file_mpi_b(), gz_field_file_mpi_io_b::gz_write_step_fld_file_mpi_b(), gz_ucd_field_mpi_io_b::gz_write_ucd_field_file_mpi_b(), gz_write_udt_file_io_b::gz_write_ucd_file_mpi_b(), gz_write_udt_file_io_b::gz_write_ucd_phys_mpi_b(), mpi_sph_modes_file_io::mpi_read_geom_rtm_file(), mpi_sph_modes_file_io_b::mpi_read_geom_rtm_file_b(), mpi_sph_modes_file_io::mpi_read_geom_rtp_file(), mpi_sph_modes_file_io_b::mpi_read_geom_rtp_file_b(), mpi_mesh_file_io::mpi_read_geometry_size(), mpi_mesh_file_io_b::mpi_read_geometry_size_b(), mpi_mesh_file_io::mpi_read_mesh_file(), mpi_mesh_file_io_b::mpi_read_mesh_file_b(), mpi_mesh_file_io::mpi_read_mesh_geometry(), mpi_mesh_file_io_b::mpi_read_mesh_geometry_b(), mpi_sph_modes_file_io::mpi_read_modes_rlm_file(), mpi_sph_modes_file_io_b::mpi_read_modes_rlm_file_b(), mpi_mesh_file_io::mpi_read_node_size(), mpi_mesh_file_io_b::mpi_read_node_size_b(), mpi_sph_modes_file_io::mpi_read_spectr_rj_file(), mpi_sph_modes_file_io_b::mpi_read_spectr_rj_file_b(), mpi_sph_modes_file_io::mpi_write_geom_rtm_file(), mpi_sph_modes_file_io_b::mpi_write_geom_rtm_file_b(), mpi_sph_modes_file_io::mpi_write_geom_rtp_file(), mpi_sph_modes_file_io_b::mpi_write_geom_rtp_file_b(), mpi_mesh_file_io::mpi_write_mesh_file(), mpi_mesh_file_io_b::mpi_write_mesh_file_b(), mpi_sph_modes_file_io::mpi_write_modes_rlm_file(), mpi_sph_modes_file_io_b::mpi_write_modes_rlm_file_b(), mpi_sph_modes_file_io::mpi_write_spectr_rj_file(), mpi_sph_modes_file_io_b::mpi_write_spectr_rj_file_b(), mpi_viewer_mesh_file_io::mpi_write_viewer_mesh_file(), field_file_mpi_io_b::read_alloc_stp_fld_file_mpi_b(), field_file_mpi_io_b::read_alloc_stp_fld_head_mpi_b(), ucd_field_mpi_io_b::read_alloc_ucd_fld_file_mpi_b(), field_file_mpi_io_b::read_step_field_file_mpi_b(), ucd_field_mpi_io_b::read_ucd_field_file_mpi_b(), field_file_mpi_io_b::write_step_field_file_mpi_b(), ucd_field_mpi_io_b::write_ucd_field_file_mpi_b(), write_udt_file_io_b::write_ucd_file_mpi_b(), write_udt_file_io_b::write_ucd_grid_mpi_b(), and write_udt_file_io_b::write_ucd_phys_mpi_b().
mpi_read_characters()
character(len=ilength) function mpi_ascii_data_io::mpi_read_characters (type(calypso_mpi_io_params), intent(inout) IO_param, integer, intent(in) ilength)
Definition at line 211 of file MPI_ascii_data_IO.f90.
References m_calypso_mpi_io::calypso_mpi_seek_read_chara().
Referenced by mpi_domain_data_io::mpi_read_int_vector().
mpi_read_charahead()
character(len=ilength) function mpi_ascii_data_io::mpi_read_charahead (type(calypso_mpi_io_params), intent(inout) IO_param, integer, intent(in) ilength)
Definition at line 185 of file MPI_ascii_data_IO.f90.
References calypso_mpi_char::calypso_mpi_bcast_character(), m_calypso_mpi_io::calypso_mpi_seek_read_chara(), transfer_to_long_integers::cast_long(), and calypso_mpi::my_rank.
Referenced by mpi_domain_data_io::mpi_check_num_of_domains(), mpi_spherical_model_io::mpi_read_gl_reso_sph(), mpi_groups_io::mpi_read_group_data(), mpi_read_num_of_data(), and mpi_groups_io::mpi_read_surf_grp_data().
mpi_read_num_of_data()
subroutine mpi_ascii_data_io::mpi_read_num_of_data (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(inout) num)
Definition at line 162 of file MPI_ascii_data_IO.f90.
References data_io_to_textline::len_byte_stack_textline(), mpi_read_charahead(), and data_io_to_textline::read_byte_stack_textline().
Referenced by mpi_domain_data_io::mpi_read_domain_info(), mpi_element_connect_io::mpi_read_edge_4_element(), mpi_element_connect_io::mpi_read_element_info(), mpi_domain_data_io::mpi_read_export_data(), mpi_spherical_model_io::mpi_read_gl_nodes_sph(), mpi_spherical_model_io::mpi_read_gl_reso_sph(), mpi_groups_io::mpi_read_group_data(), mpi_domain_data_io::mpi_read_import_data(), mpi_element_connect_io::mpi_read_num_element(), mpi_spherical_model_io::mpi_read_rank_4_sph(), mpi_sph_gl_1d_idx_io::mpi_read_rj_gl_1d_table(), mpi_sph_gl_1d_idx_io::mpi_read_rtp_gl_1d_table(), mpi_groups_io::mpi_read_surf_grp_data(), mpi_groups_io::mpi_read_surf_grp_item(), and mpi_element_connect_io::mpi_read_surface_4_element().
mpi_skip_read()
subroutine mpi_ascii_data_io::mpi_skip_read (type(calypso_mpi_io_params), intent(inout) IO_param, integer, intent(in) ilength)
Definition at line 233 of file MPI_ascii_data_IO.f90.
Referenced by mpi_sph_gl_1d_idx_io::mpi_read_1d_gl_address(), mpi_domain_data_io::mpi_read_comm_table(), mpi_edge_data_io::mpi_read_edge_connection(), mpi_edge_data_io::mpi_read_edge_geometry(), mpi_integer_list_io::mpi_read_ele_connect(), mpi_element_data_io::mpi_read_element_comm_table(), mpi_element_data_io::mpi_read_element_geometry(), mpi_integer_list_io::mpi_read_element_type(), mpi_sph_modes_data_io::mpi_read_geom_rtm_data(), mpi_sph_modes_data_io::mpi_read_geom_rtp_data(), mpi_mesh_data_io::mpi_read_geometry_data(), mpi_spherical_model_io::mpi_read_gl_reso_sph(), mpi_integer_list_io::mpi_read_int_list(), mpi_domain_data_io::mpi_read_int_vector(), mpi_mesh_data_io::mpi_read_mesh_groups(), mpi_sph_modes_data_io::mpi_read_modes_rlm_data(), mpi_position_io::mpi_read_node_position(), mpi_mesh_data_io::mpi_read_num_node(), mpi_mesh_data_io::mpi_read_num_node_ele(), mpi_position_io::mpi_read_radial_position(), mpi_spherical_model_io::mpi_read_rank_4_sph(), mpi_sph_gl_1d_idx_io::mpi_read_rj_gl_1d_table(), mpi_sph_gl_1d_idx_io::mpi_read_rtp_gl_1d_table(), mpi_vectors_io::mpi_read_scalar(), mpi_sph_modes_data_io::mpi_read_spectr_rj_data(), mpi_surface_data_io::mpi_read_surface_connection(), mpi_surface_data_io::mpi_read_surface_geometry(), and mpi_vectors_io::mpi_read_vector().
mpi_write_charahead()
subroutine mpi_ascii_data_io::mpi_write_charahead (type(calypso_mpi_io_params), intent(inout) IO_param, integer, intent(in) ilength, character(len=ilength), intent(in) chara_dat)
Definition at line 108 of file MPI_ascii_data_IO.f90.
References m_calypso_mpi_io::mpi_write_one_chara_b(), and calypso_mpi::my_rank.
Referenced by mpi_viewer_mesh_io::mpi_write_domain_grp_data(), mpi_domain_data_io::mpi_write_domain_info(), mpi_edge_data_io::mpi_write_edge_connection(), mpi_edge_data_io::mpi_write_edge_geometry(), mpi_element_data_io::mpi_write_element_comm_table(), mpi_element_data_io::mpi_write_element_geometry(), mpi_sph_modes_data_io::mpi_write_geom_rtm_data(), mpi_sph_modes_data_io::mpi_write_geom_rtp_data(), mpi_mesh_data_io::mpi_write_geometry_data(), mpi_spherical_model_io::mpi_write_gl_reso_sph(), mpi_groups_io::mpi_write_grp_data(), mpi_domain_data_io::mpi_write_int_vector(), mpi_mesh_data_io::mpi_write_mesh_groups(), mpi_sph_modes_data_io::mpi_write_modes_rlm_data(), mpi_write_num_of_data(), mpi_spherical_model_io::mpi_write_rank_4_sph(), mpi_sph_gl_1d_idx_io::mpi_write_rj_gl_1d_table(), mpi_sph_gl_1d_idx_io::mpi_write_rtp_gl_1d_table(), mpi_sph_modes_data_io::mpi_write_spectr_rj_data(), mpi_write_stack_over_domain(), mpi_groups_io::mpi_write_surf_grp_data(), mpi_surface_data_io::mpi_write_surface_connection(), mpi_surface_data_io::mpi_write_surface_geometry(), mpi_viewer_mesh_io::mpi_write_viewer_grp_data(), and mpi_viewer_mesh_file_io::write_viewer_mesh_infos().
mpi_write_num_of_data()
subroutine mpi_ascii_data_io::mpi_write_num_of_data (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) num)
Definition at line 129 of file MPI_ascii_data_IO.f90.
References data_io_to_textline::byte_stack_textline(), data_io_to_textline::len_byte_stack_textline(), mpi_write_charahead(), and t_calypso_mpi_io_param::set_numbers_2_head_node().
Referenced by mpi_sph_gl_1d_idx_io::mpi_write_1d_gl_address(), mpi_domain_data_io::mpi_write_comm_table(), mpi_element_connect_io::mpi_write_edge_4_element(), mpi_element_connect_io::mpi_write_element_info(), mpi_spherical_model_io::mpi_write_gl_nodes_sph(), mpi_domain_data_io::mpi_write_int_vector(), mpi_sph_gl_1d_idx_io::mpi_write_rj_gl_1d_table(), mpi_sph_gl_1d_idx_io::mpi_write_rtp_gl_1d_table(), mpi_vectors_io::mpi_write_scalar(), mpi_element_connect_io::mpi_write_surface_4_element(), and mpi_vectors_io::mpi_write_vector().
mpi_write_stack_over_domain()
subroutine mpi_ascii_data_io::mpi_write_stack_over_domain (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint_gl), intent(in) num)
Definition at line 145 of file MPI_ascii_data_IO.f90.
References data_io_to_textline::byte_stack_textline(), t_calypso_mpi_io_param::istack64_4_parallel_data(), data_io_to_textline::len_byte_stack_textline(), and mpi_write_charahead().
Referenced by mpi_sph_gl_1d_idx_io::mpi_write_1d_gl_address(), mpi_domain_data_io::mpi_write_comm_table(), mpi_viewer_mesh_io::mpi_write_domain_grp_data(), mpi_integer_list_io::mpi_write_ele_connect(), mpi_integer_list_io::mpi_write_element_type(), mpi_integer_list_io::mpi_write_int_list(), mpi_position_io::mpi_write_node_position(), mpi_position_io::mpi_write_radial_position(), mpi_vectors_io::mpi_write_scalar(), mpi_vectors_io::mpi_write_vector(), mpi_viewer_mesh_io::mpi_write_viewer_connect(), mpi_viewer_mesh_io::mpi_write_viewer_element_type(), mpi_viewer_mesh_io::mpi_write_viewer_grp_data(), mpi_viewer_mesh_io::mpi_write_viewer_grp_item(), mpi_viewer_mesh_io::mpi_write_viewer_position(), and mpi_viewer_mesh_file_io::write_viewer_mesh_infos().
open_append_mpi_file()
subroutine mpi_ascii_data_io::open_append_mpi_file (character(len=kchara), intent(in) file_name, type(calypso_mpi_io_params), intent(inout) IO_param)
Definition at line 64 of file MPI_ascii_data_IO.f90.
References t_calypso_mpi_io_param::alloc_istack_merge(), m_calypso_mpi_io::calypso_mpi_append_file_open(), calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by mpi_picked_sph_spectr_io::append_picked_spectrum_file(), and mpi_sph_gauss_coefs_io::append_sph_gauss_coefs_file().
open_read_mpi_file()
subroutine mpi_ascii_data_io::open_read_mpi_file (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, type(calypso_mpi_io_params), intent(inout) IO_param)
Definition at line 79 of file MPI_ascii_data_IO.f90.
References t_calypso_mpi_io_param::alloc_istack_merge(), m_calypso_mpi_io::calypso_mpi_read_file_open(), and m_constants::izero.
Referenced by gz_mpi_sph_modes_file_io::gz_mpi_read_geom_rtm_file(), gz_mpi_sph_modes_file_io::gz_mpi_read_geom_rtp_file(), gz_mpi_mesh_file_io::gz_mpi_read_geometry_size(), gz_mpi_mesh_file_io::gz_mpi_read_mesh(), gz_mpi_mesh_file_io::gz_mpi_read_mesh_geometry(), gz_mpi_sph_modes_file_io::gz_mpi_read_modes_rlm_file(), gz_mpi_mesh_file_io::gz_mpi_read_node_size(), gz_mpi_sph_modes_file_io::gz_mpi_read_spectr_rj_file(), mpi_sph_modes_file_io::mpi_read_geom_rtm_file(), mpi_sph_modes_file_io::mpi_read_geom_rtp_file(), mpi_mesh_file_io::mpi_read_geometry_size(), mpi_mesh_file_io::mpi_read_mesh_file(), mpi_mesh_file_io::mpi_read_mesh_geometry(), mpi_sph_modes_file_io::mpi_read_modes_rlm_file(), mpi_mesh_file_io::mpi_read_node_size(), mpi_sph_modes_file_io::mpi_read_spectr_rj_file(), gz_mpi_binary_datum_io::open_read_gz_mpi_file_b(), and mpi_binary_head_io::open_read_mpi_file_b().
open_write_mpi_file()
subroutine mpi_ascii_data_io::open_write_mpi_file (character(len=kchara), intent(in) file_name, type(calypso_mpi_io_params), intent(inout) IO_param)
Definition at line 48 of file MPI_ascii_data_IO.f90.
References t_calypso_mpi_io_param::alloc_istack_merge(), m_calypso_mpi_io::calypso_mpi_write_file_open(), m_constants::izero, calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by gz_mpi_sph_modes_file_io::gz_mpi_write_geom_rtm_file(), gz_mpi_sph_modes_file_io::gz_mpi_write_geom_rtp_file(), gz_mpi_mesh_file_io::gz_mpi_write_mesh_file(), gz_mpi_sph_modes_file_io::gz_mpi_write_modes_rlm_file(), gz_mpi_sph_modes_file_io::gz_mpi_write_spectr_rj_file(), gz_mpi_viewer_mesh_file_io::gz_mpi_write_viewer_mesh_file(), mpi_sph_modes_file_io::mpi_write_geom_rtm_file(), mpi_sph_modes_file_io::mpi_write_geom_rtp_file(), mpi_mesh_file_io::mpi_write_mesh_file(), mpi_sph_modes_file_io::mpi_write_modes_rlm_file(), mpi_sph_modes_file_io::mpi_write_spectr_rj_file(), mpi_viewer_mesh_file_io::mpi_write_viewer_mesh_file(), gz_mpi_binary_datum_io::open_write_gz_mpi_file_b(), and mpi_binary_head_io::open_write_mpi_file_b().