CALYPSO: set_scalar_boundary_sph Module Reference
set_scalar_boundary_sph Module Reference
Evaluate scalar fields at boundaries
Adjust temperature and composition boundary conditions if perturbation is solved.
Functions/Subroutines
subroutine set_fixed_scalar_sph (jmax, inod_rj_center, idx_rj_degree_zero, kr_bc_st, kr_bc_ed, is_fld, fixed_bc, S_CTR, n_point, ntot_phys_rj, d_rj)
subroutine adjust_in_fixed_flux_sph (jmax, kr_in, r_ICB, fdm2_fix_dr_ICB, flux_ICB, coef_d, coef_imp, dt, is_fld, n_point, ntot_phys_rj, d_rj)
subroutine adjust_out_fixed_flux_sph (jmax, kr_out, r_CMB, fdm2_fix_dr_CMB, flux_CMB, coef_d, coef_imp, dt, is_fld, n_point, ntot_phys_rj, d_rj)
subroutine poisson_in_fixed_flux_sph (jmax, kr_in, r_ICB, fdm2_fix_dr_ICB, flux_ICB, is_fld, n_point, ntot_phys_rj, d_rj)
subroutine poisson_out_fixed_flux_sph (jmax, kr_out, r_CMB, fdm2_fix_dr_CMB, flux_CMB, is_fld, n_point, ntot_phys_rj, d_rj)
Detailed Description
Evaluate scalar fields at boundaries
Adjust temperature and composition boundary conditions if perturbation is solved.
      subroutine set_fixed_scalar_sph(n_point, jmax,                  &
     &          kr_bc_st, kr_bc_ed, is_fld, fixed_bc, S_CTR,          &
     &          ntot_phys_rj, d_rj)
      subroutine adjust_in_fixed_flux_sph                             &
     &       (jmax, kr_in, r_ICB, fdm2_fix_dr_ICB, flux_ICB, coef_d,  &
     &        coef_imp, dt, is_fld, n_point, ntot_phys_rj, d_rj)
      subroutine adjust_out_fixed_flux_sph                            &
     &       (jmax, kr_out, r_CMB, fdm2_fix_dr_CMB, flux_CMB, coef_d, &
     &        coef_imp, dt, is_fld, n_point, ntot_phys_rj, d_rj)
      subroutine poisson_in_fixed_flux_sph                            &
     &       (jmax, kr_in, r_ICB, fdm2_fix_dr_ICB, flux_ICB, is_fld,  &
     &        n_point, ntot_phys_rj, d_rj)
      subroutine poisson_out_fixed_flux_sph                           &
     &       (jmax, kr_out, r_CMB, fdm2_fix_dr_CMB, flux_CMB, is_fld, &
     &        n_point, ntot_phys_rj, d_rj)
Parameters
n_point Number of points for spectrum data
jmax Number of modes for local spectrum
kr_bc_st Start radial address to set fixed field
kr_bc_ed End radial address to set fixed field
fixed_bc(jmax) Boundary condition spectrum
kr_in Radial ID for inner boundary
kr_out Radial ID for outer boundary
r_ICB(0:2) Radius at ICB
r_CMB(0:2) Radius at CMB
fdm2_fix_dr_ICB(-1:1,3) Matrix to evaluate field at ICB with fixed radial derivative
fdm2_fix_dr_CMB(-1:1,3) Matrix to evaluate field at CMB with fixed radial derivative
flux_ICB(jamx) Spectrum of fixed flux at ICB
flux_CMB(jamx) Spectrum of fixed flux at CMB
coef_imp Coefficient for contribution of implicit term
coef_d Coefficient for magnetic diffusion
is_fld Input field address for d_rj
ntot_phys_rj Total number of components
d_rj Spectrum data
Function/Subroutine Documentation
adjust_in_fixed_flux_sph()
subroutine set_scalar_boundary_sph::adjust_in_fixed_flux_sph (integer(kind = kint), intent(in) jmax, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(0:2), intent(in) r_ICB, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_fix_dr_ICB, real(kind = kreal), dimension(jmax), intent(in) flux_ICB, real(kind = kreal), intent(in) coef_d, real(kind = kreal), intent(in) coef_imp, real(kind = kreal), intent(in) dt, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 107 of file set_scalar_boundary_sph.f90.
References m_constants::two.
Referenced by select_exp_scalar_icb::set_icb_scalar_sph_crank().
adjust_out_fixed_flux_sph()
subroutine set_scalar_boundary_sph::adjust_out_fixed_flux_sph (integer(kind = kint), intent(in) jmax, integer(kind = kint), intent(in) kr_out, real(kind = kreal), dimension(0:2), intent(in) r_CMB, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_fix_dr_CMB, real(kind = kreal), dimension(jmax), intent(in) flux_CMB, real(kind = kreal), intent(in) coef_d, real(kind = kreal), intent(in) coef_imp, real(kind = kreal), intent(in) dt, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 139 of file set_scalar_boundary_sph.f90.
References m_constants::two.
Referenced by select_exp_scalar_cmb::set_cmb_scalar_sph_crank().
poisson_in_fixed_flux_sph()
subroutine set_scalar_boundary_sph::poisson_in_fixed_flux_sph (integer(kind = kint), intent(in) jmax, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(0:1), intent(in) r_ICB, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_fix_dr_ICB, real(kind = kreal), dimension(jmax), intent(in) flux_ICB, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 172 of file set_scalar_boundary_sph.f90.
References m_constants::two.
Referenced by select_exp_scalar_icb::set_icb_scalar_sph_crank().
poisson_out_fixed_flux_sph()
subroutine set_scalar_boundary_sph::poisson_out_fixed_flux_sph (integer(kind = kint), intent(in) jmax, integer(kind = kint), intent(in) kr_out, real(kind = kreal), dimension(0:1), intent(in) r_CMB, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_fix_dr_CMB, real(kind = kreal), dimension(jmax), intent(in) flux_CMB, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 201 of file set_scalar_boundary_sph.f90.
References m_constants::two.
Referenced by select_exp_scalar_cmb::set_cmb_scalar_sph_crank().
set_fixed_scalar_sph()
subroutine set_scalar_boundary_sph::set_fixed_scalar_sph (integer(kind = kint), intent(in) jmax, integer(kind = kint), intent(in) inod_rj_center, integer(kind = kint), intent(in) idx_rj_degree_zero, integer(kind = kint), intent(in) kr_bc_st, integer(kind = kint), intent(in) kr_bc_ed, integer(kind = kint), intent(in) is_fld, real(kind = kreal), dimension(jmax), intent(in) fixed_bc, real(kind = kreal), intent(in) S_CTR, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 69 of file set_scalar_boundary_sph.f90.
References m_constants::ione.
Referenced by select_exp_scalar_cmb::set_cmb_scalar_sph_crank(), and select_exp_scalar_icb::set_icb_scalar_sph_crank().