CALYPSO: gz_mpi_element_data_io Module Reference
gz_mpi_element_data_io Module Reference
Data IO routines for element data.
Functions/Subroutines
subroutine gz_mpi_read_ele_comm_table (IO_param, comm_IO)
subroutine gz_mpi_write_ele_comm_table (IO_param, comm_IO)
subroutine gz_mpi_read_ele_geometry (IO_param, nod_IO, sfed_IO)
subroutine gz_mpi_write_ele_geometry (IO_param, nod_IO, sfed_IO)
Detailed Description
Data IO routines for element data.
      subroutine gz_mpi_read_ele_comm_table(IO_param, comm_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(communication_table), intent(inout) :: comm_IO
      subroutine gz_mpi_write_ele_comm_table(IO_param, comm_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(communication_table), intent(in) :: comm_IO
      subroutine gz_mpi_read_ele_geometry(IO_param, nod_IO, sfed_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(node_data), intent(inout) :: nod_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
      subroutine gz_mpi_write_ele_geometry(IO_param, nod_IO, sfed_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(node_data), intent(in) :: nod_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
Function/Subroutine Documentation
gz_mpi_read_ele_comm_table()
subroutine gz_mpi_element_data_io::gz_mpi_read_ele_comm_table (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(inout) comm_IO)
Definition at line 50 of file gz_MPI_element_data_IO.f90.
References gz_mpi_domain_data_io::gz_mpi_read_domain_info(), gz_mpi_domain_data_io::gz_mpi_read_export_data(), gz_mpi_domain_data_io::gz_mpi_read_import_data(), gz_mpi_ascii_data_io::gz_mpi_skip_header(), m_fem_surface_labels::hd_ecomm_export(), m_fem_surface_labels::hd_ecomm_import(), m_fem_surface_labels::hd_ecomm_para(), and m_fem_mesh_labels::hd_fem_para().
Referenced by gz_mpi_element_file_io::gz_mpi_input_element_file().
gz_mpi_read_ele_geometry()
subroutine gz_mpi_element_data_io::gz_mpi_read_ele_geometry (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 99 of file gz_MPI_element_data_IO.f90.
References gz_mpi_node_geometry_io::gz_mpi_read_geometry_info(), gz_mpi_node_geometry_io::gz_mpi_read_number_of_node(), gz_mpi_node_geometry_io::gz_mpi_read_scl_in_ele(), gz_mpi_ascii_data_io::gz_mpi_skip_header(), m_fem_surface_labels::hd_ecomm_point(), and m_fem_surface_labels::hd_ecomm_vol().
gz_mpi_write_ele_comm_table()
subroutine gz_mpi_element_data_io::gz_mpi_write_ele_comm_table (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(in) comm_IO)
Definition at line 72 of file gz_MPI_element_data_IO.f90.
References gz_mpi_ascii_data_io::gz_mpi_write_charahead(), gz_mpi_domain_data_io::gz_mpi_write_domain_info(), gz_mpi_domain_data_io::gz_mpi_write_export_data(), gz_mpi_domain_data_io::gz_mpi_write_import_data(), m_fem_surface_labels::hd_ecomm_export(), m_fem_surface_labels::hd_ecomm_import(), m_fem_surface_labels::hd_ecomm_para(), and m_fem_mesh_labels::hd_fem_para().
Referenced by gz_mpi_element_file_io::gz_mpi_output_element_file().
gz_mpi_write_ele_geometry()
subroutine gz_mpi_element_data_io::gz_mpi_write_ele_geometry (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 117 of file gz_MPI_element_data_IO.f90.
References gz_mpi_ascii_data_io::gz_mpi_write_charahead(), gz_mpi_node_geometry_io::gz_mpi_write_geometry_info(), gz_mpi_node_geometry_io::gz_mpi_write_scl_in_ele(), m_fem_surface_labels::hd_ecomm_point(), and m_fem_surface_labels::hd_ecomm_vol().