CALYPSO: gauss_points_io Module Reference
gauss_points_io Module Reference
Functions/Subroutines
subroutine write_gauss_points (file_name, gauss)
Check Gauss points.
subroutine read_alloc_gauss_points (file_name, gauss)
Check Gauss points.
integer(kind=kint) function compare_gauss_point_data (gauss_1, gauss_2)
Check Gauss points.
Function/Subroutine Documentation
compare_gauss_point_data()
integer(kind = kint) function gauss_points_io::compare_gauss_point_data (type(gauss_points), intent(in) gauss_1, type(gauss_points), intent(in) gauss_2)
Check Gauss points.
Definition at line 112 of file gauss_points_IO.f90.
References m_constants::tiny.
Referenced by compare_gauss_points().
read_alloc_gauss_points()
subroutine gauss_points_io::read_alloc_gauss_points (character(len=kchara), intent(in) file_name, type(gauss_points), intent(inout) gauss)
Check Gauss points.
Definition at line 72 of file gauss_points_IO.f90.
References t_gauss_points::alloc_gauss_colatitude(), and t_gauss_points::alloc_gauss_points().
Referenced by compare_gauss_points().
write_gauss_points()
subroutine gauss_points_io::write_gauss_points (character(len=kchara), intent(in) file_name, type(gauss_points), intent(in) gauss)
Check Gauss points.
Definition at line 36 of file gauss_points_IO.f90.
Referenced by test_gauss_points().