CALYPSO: pole_sph_transform Module Reference
pole_sph_transform Module Reference
Spherical transform for poles.
Functions/Subroutines
subroutine init_pole_grids (sph_rtp)
subroutine pole_backward_transforms (ncomp, nvector, nscalar, sph_params, sph_rtp, sph_rtm, sph_rlm, comm_rlm, leg, n_WR, WR, v_pl_local)
Detailed Description
Spherical transform for poles.
      subroutine init_pole_grids(sph_rtp)
      subroutine pole_backward_transforms(ncomp, nvector, nscalar,    &
     &          sph_params, sph_rtp, sph_rtm, sph_rlm, comm_rlm, leg, &
     &          n_WR, WR, v_pl_local)
        type(sph_shell_parameters), intent(in) :: sph_params
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_rtm_grid), intent(in) :: sph_rtm
        type(sph_rlm_grid), intent(in) :: sph_rlm
        type(sph_comm_tbl), intent(in) :: comm_rlm
        type(legendre_4_sph_trans), intent(inout) :: leg
------------------------------------------------------------------
      vr =  l*(l+1)*Y(l,0)* S(l,0) / r**2
      vt =  (dYdt(l,1s)*dSdr(l,1s)
           + dYdt(l,1c)*dSdr(l,1c))  / r
         + cos(theta) * (d2Ydtdp(l,1s)*T(l,1s)
                       + d2Ydtdp(l,1c)*T(l,1c))  / r
      vp = cos(theta) * (d2Ydtdp(l,1s)*dSdr(l,1s)
                       + d2Ydtdp(l,1c)*dSdr(l,1c))  / r
           -(dYdt(l,1s)*T(l,1s)
           + dYdt(l,1c)*T(l,1c))  / r
  if phi = 0
      vr =  l*(l+1)*P(l,0)* S(l,0) / r**2
      vt =  dPdt(l,1)*dSdr(l,1c)  / r
         + cos(theta) * dPdt(l,1)*T(l,1s) / r
      vp = cos(theta) * dPdt(l,1)*dSdr(l,1s) / r
           - dPdt(l,1)*T(l,1c)  / r
 if z > 0 (North pole)
      vx = vt
      vy = vp
      vz = vr
 if z < 0 (South pole)
      vx = -vt
      vy =  vp
      vz = -vr
------------------------------------------------------------------
------------------------------------------------------------------
 if r= 0 (Center)
      vz =  2 * P(1,0) * S(1,0) / r_c**2
         =  2 * S(1,0) / r_c**2
      vx =  2 * dPdt(l,1) * S(1,1c) / r_c**2
         = - 2 * S(1,1c) / r_c**2
      vy =  2 * dPdt(l,1) * S(1,1s) / r_c**2
         = - 2 * S(1,1s) / r_c**2
------------------------------------------------------------------
Parameters
ncomp Number of components for transform
Function/Subroutine Documentation
init_pole_grids()
subroutine pole_sph_transform::init_pole_grids (type(sph_rtp_grid), intent(inout) sph_rtp)
Definition at line 90 of file pole_sph_transform.f90.
References cal_minmax_and_stacks::count_number_4_smp(), m_constants::ione, and m_machine_parameter::np_smp.
Referenced by parallel_load_data_4_sph::sph_index_flags_and_params().
pole_backward_transforms()
subroutine pole_sph_transform::pole_backward_transforms (integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_shell_parameters), intent(in) sph_params, type(sph_rtp_grid), intent(in) sph_rtp, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_comm_tbl), intent(in) comm_rlm, type(legendre_4_sph_trans), intent(in) leg, integer(kind = kint), intent(in) n_WR, real(kind = kreal), dimension(n_wr), intent(in) WR, real(kind = kreal), dimension(sph_rtp%nnod_pole,ncomp), intent(inout) v_pl_local)
Definition at line 107 of file pole_sph_transform.f90.
References m_machine_parameter::iflag_debug, m_spheric_constants::iflag_mesh_same, m_spheric_constants::iflag_mesh_w_center, m_spheric_constants::iflag_no_femmesh, schmidt_b_trans_at_center::schmidt_b_trans_center_scalar(), schmidt_b_trans_at_center::schmidt_b_trans_center_vect(), schmidt_b_trans_at_pole::schmidt_b_trans_pole_scalar(), and schmidt_b_trans_at_pole::schmidt_b_trans_pole_vect().
Referenced by t_sph_transforms::pole_b_transform(), and t_sph_transforms::sph_b_trans_w_poles().