CALYPSO: check_base_forces Module Reference
check_base_forces Module Reference
Functions/Subroutines
subroutine add_field_ctl_4_forces (field_ctl)
subroutine add_field_ctl_4_rot_forces (field_ctl)
subroutine add_field_ctl_4_div_forces (field_ctl)
subroutine add_field_ctl_4_field_products (field_ctl)
subroutine add_field_ctl_4_diffusions (field_ctl)
Function/Subroutine Documentation
add_field_ctl_4_diffusions()
subroutine check_base_forces::add_field_ctl_4_diffusions (type(ctl_array_c3), intent(inout) field_ctl)
Definition at line 251 of file check_base_forces.f90.
References add_nodal_fields_ctl::add_phys_name_ctl(), add_nodal_fields_ctl::check_field_list_ctl(), m_base_field_labels::composition, m_diffusion_term_labels::composition_diffusion, m_diffusion_term_labels::div_viscousity, m_diffusion_term_labels::magnetic_diffusion, m_base_field_labels::magnetic_field, m_base_field_labels::temperature, m_diffusion_term_labels::thermal_diffusion, m_base_field_labels::vector_potential, m_diffusion_term_labels::vector_potential_diffusion, m_base_field_labels::velocity, m_diffusion_term_labels::viscous_diffusion, m_base_field_labels::vorticity, and m_diffusion_term_labels::vorticity_diffusion.
Referenced by add_nodal_fields_4_mhd::add_dependent_field().
add_field_ctl_4_div_forces()
subroutine check_base_forces::add_field_ctl_4_div_forces (type(ctl_array_c3), intent(inout) field_ctl)
Definition at line 139 of file check_base_forces.f90.
References add_nodal_fields_ctl::add_phys_name_ctl(), m_base_force_labels::buoyancy, add_nodal_fields_ctl::check_field_list_ctl(), m_base_force_labels::composite_buoyancy, m_base_force_labels::composite_flux, m_base_force_labels::coriolis_force, m_div_force_labels::div_buoyancy, m_div_force_labels::div_composite_buoyancy, m_div_force_labels::div_composition_flux, m_div_force_labels::div_coriolis_force, m_div_force_labels::div_heat_flux, m_div_force_labels::div_induction_tensor, m_div_force_labels::div_inertia, m_div_force_labels::div_lorentz_force, m_div_force_labels::div_maxwell_tensor, m_div_force_labels::div_momentum_flux, m_div_force_labels::div_pert_composition_flux, m_div_force_labels::div_pert_heat_flux, m_base_force_labels::induction_tensor, m_base_force_labels::inertia, m_base_force_labels::lorentz_force, m_base_force_labels::maxwell_tensor, m_base_force_labels::momentum_flux, m_base_force_labels::pert_comp_flux, and m_base_force_labels::pert_heat_flux.
Referenced by add_nodal_fields_4_mhd::add_dependent_field().
add_field_ctl_4_field_products()
subroutine check_base_forces::add_field_ctl_4_field_products (type(ctl_array_c3), intent(inout) field_ctl)
Definition at line 181 of file check_base_forces.f90.
References add_nodal_fields_ctl::add_phys_name_ctl(), add_nodal_fields_ctl::check_field_list_ctl(), m_base_field_labels::composition, m_field_product_labels::composition_scale, m_base_force_labels::coriolis_force, m_field_product_labels::cross_helicity, m_base_field_labels::current_density, m_field_product_labels::current_helicity, m_field_product_labels::electric_field, m_field_product_labels::kinetic_helicity, m_base_field_labels::magnetic_field, m_field_product_labels::magnetic_helicity, m_field_product_labels::magnetic_scale, m_field_product_labels::poynting_flux, m_base_force_labels::pressure_gradient, m_field_product_labels::rest_of_geostrophic, m_field_product_labels::square_composition, m_field_product_labels::square_current, m_field_product_labels::square_magne, m_field_product_labels::square_temperature, m_field_product_labels::square_vector_potential, m_field_product_labels::square_velocity, m_field_product_labels::square_vorticity, m_field_product_labels::stream_pol_velocity, m_base_field_labels::temperature, m_field_product_labels::temperature_scale, m_field_product_labels::truncated_magnetic_field, m_base_force_labels::vecp_induction, m_base_field_labels::vector_potential, m_base_field_labels::velocity, m_field_product_labels::velocity_scale, and m_base_field_labels::vorticity.
Referenced by add_nodal_fields_4_mhd::add_dependent_field().
add_field_ctl_4_forces()
subroutine check_base_forces::add_field_ctl_4_forces (type(ctl_array_c3), intent(inout) field_ctl)
Definition at line 35 of file check_base_forces.f90.
References add_nodal_fields_ctl::add_phys_name_ctl(), m_base_force_labels::buoyancy, add_nodal_fields_ctl::check_field_list_ctl(), m_base_force_labels::composite_buoyancy, m_base_force_labels::composite_flux, m_base_field_labels::composition, m_base_force_labels::composition_advect, m_base_force_labels::coriolis_force, m_base_field_labels::current_density, m_diff_vector_labels::grad_v_1, m_diff_vector_labels::grad_v_2, m_diff_vector_labels::grad_v_3, m_base_force_labels::heat_advect, m_base_force_labels::heat_flux, m_base_force_labels::induction_tensor, m_base_force_labels::inertia, m_base_force_labels::lorentz_force, m_base_field_labels::magnetic_field, m_base_force_labels::magnetic_induction, m_base_force_labels::magnetic_stretch, m_base_force_labels::magnetic_tension, m_base_force_labels::maxwell_tensor, m_base_force_labels::momentum_flux, m_base_force_labels::pert_comp_advect, m_base_force_labels::pert_comp_flux, m_base_force_labels::pert_heat_advect, m_base_force_labels::pert_heat_flux, m_base_field_labels::perturbation_composition, m_base_field_labels::perturbation_temp, m_base_field_labels::pressure, m_base_force_labels::pressure_gradient, m_base_field_labels::temperature, m_base_force_labels::vecp_induction, m_base_field_labels::velocity, and m_base_field_labels::vorticity.
Referenced by add_nodal_fields_4_mhd::add_dependent_field().
add_field_ctl_4_rot_forces()
subroutine check_base_forces::add_field_ctl_4_rot_forces (type(ctl_array_c3), intent(inout) field_ctl)
Definition at line 114 of file check_base_forces.f90.
References add_nodal_fields_ctl::add_phys_name_ctl(), m_base_force_labels::buoyancy, add_nodal_fields_ctl::check_field_list_ctl(), m_base_force_labels::composite_buoyancy, m_base_force_labels::coriolis_force, m_base_force_labels::inertia, m_base_force_labels::lorentz_force, m_rot_force_labels::rot_buoyancy, m_rot_force_labels::rot_composite_buoyancy, m_rot_force_labels::rot_coriolis_force, m_rot_force_labels::rot_inertia, and m_rot_force_labels::rot_lorentz_force.
Referenced by add_nodal_fields_4_mhd::add_dependent_field().