CALYPSO: t_control_data_isosurfaces Module Reference
t_control_data_isosurfaces Module Reference
control data for isosurfaces
Data Types
type isosurf_controls
Functions/Subroutines
subroutine read_files_4_iso_ctl (id_control, hd_block, iso_ctls, c_buf)
subroutine bcast_files_4_iso_ctl (iso_ctls)
subroutine dealloc_iso_ctl_stract (iso_ctls)
subroutine, private append_new_isosurface_control (iso_ctls)
subroutine, private dup_control_4_isos (num_iso, org_iso_ctls, new_iso_ctls)
subroutine, private alloc_iso_ctl_stract (iso_ctls)
subroutine, private dealloc_cont_dat_4_isos (num_iso, iso_c)
subroutine, private read_control_4_iso_file (id_control, fname_iso_ctl, iso_ctl_struct)
Variables
character(len=kchara), parameter, private hd_isosurf_ctl = 'isosurface_ctl'
character(len=kchara), parameter, private hd_iso_ctl = 'isosurf_rendering'
Detailed Description
control data for isosurfaces
      subroutine read_files_4_iso_ctl                                 &
     &         (id_control, hd_block, iso_ctls, c_buf)
        type(isosurf_controls), intent(inout) :: iso_ctls
        type(buffer_for_control), intent(inout)  :: c_buf
      subroutine bcast_files_4_iso_ctl(iso_ctls)
        type(isosurf_controls), intent(inout) :: iso_ctls
      subroutine dealloc_iso_ctl_stract(iso_ctls)
        type(isosurf_controls), intent(inout) :: iso_ctls
    array isosurface_ctl     2
      file   isosurface_ctl   'ctl_iso_p_n1e4'
      file   isosurface_ctl   'ctl_iso_p_p1e4'
    end array isosurface_ctl
Function/Subroutine Documentation
alloc_iso_ctl_stract()
subroutine, private t_control_data_isosurfaces::alloc_iso_ctl_stract (type(isosurf_controls), intent(inout) iso_ctls) private
Definition at line 196 of file t_control_data_isosurfaces.f90.
Referenced by append_new_isosurface_control(), bcast_files_4_iso_ctl(), and read_files_4_iso_ctl().
append_new_isosurface_control()
subroutine, private t_control_data_isosurfaces::append_new_isosurface_control (type(isosurf_controls), intent(inout) iso_ctls) private
Definition at line 147 of file t_control_data_isosurfaces.f90.
References alloc_iso_ctl_stract(), dealloc_cont_dat_4_isos(), dealloc_iso_ctl_stract(), and dup_control_4_isos().
Referenced by read_files_4_iso_ctl().
bcast_files_4_iso_ctl()
subroutine t_control_data_isosurfaces::bcast_files_4_iso_ctl (type(isosurf_controls), intent(inout) iso_ctls)
Definition at line 105 of file t_control_data_isosurfaces.f90.
References alloc_iso_ctl_stract(), t_control_data_4_iso::bcast_iso_control_data(), calypso_mpi_char::calypso_mpi_bcast_character(), calypso_mpi_int::calypso_mpi_bcast_one_int(), transfer_to_long_integers::cast_long(), and calypso_mpi::my_rank.
Referenced by t_control_data_surfacings::bcast_surfacing_controls().
dealloc_cont_dat_4_isos()
subroutine, private t_control_data_isosurfaces::dealloc_cont_dat_4_isos (integer(kind = kint), intent(in) num_iso, type(iso_ctl), dimension(num_iso), intent(inout) iso_c) private
Definition at line 207 of file t_control_data_isosurfaces.f90.
Referenced by append_new_isosurface_control().
dealloc_iso_ctl_stract()
subroutine t_control_data_isosurfaces::dealloc_iso_ctl_stract (type(isosurf_controls), intent(inout) iso_ctls)
Definition at line 132 of file t_control_data_isosurfaces.f90.
Referenced by append_new_isosurface_control(), t_control_data_surfacings::dealloc_surfacing_controls(), and set_psf_iso_control::set_iso_control().
dup_control_4_isos()
subroutine, private t_control_data_isosurfaces::dup_control_4_isos (integer(kind = kint), intent(in) num_iso, type(isosurf_controls), intent(in) org_iso_ctls, type(isosurf_controls), intent(inout) new_iso_ctls) private
Definition at line 177 of file t_control_data_isosurfaces.f90.
Referenced by append_new_isosurface_control().
read_control_4_iso_file()
subroutine, private t_control_data_isosurfaces::read_control_4_iso_file (integer(kind = kint), intent(in) id_control, character(len = kchara), intent(in) fname_iso_ctl, type(iso_ctl), intent(inout) iso_ctl_struct) private
Definition at line 222 of file t_control_data_isosurfaces.f90.
References hd_iso_ctl, hd_isosurf_ctl, t_read_control_elements::load_one_line_from_control(), and t_control_data_4_iso::read_iso_control_data().
Referenced by read_files_4_iso_ctl().
read_files_4_iso_ctl()
subroutine t_control_data_isosurfaces::read_files_4_iso_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(isosurf_controls), intent(inout) iso_ctls, type(buffer_for_control), intent(inout) c_buf)
Definition at line 61 of file t_control_data_isosurfaces.f90.
References alloc_iso_ctl_stract(), append_new_isosurface_control(), t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_array_flag(), t_read_control_elements::check_file_flag(), t_read_control_elements::load_one_line_from_control(), read_control_4_iso_file(), and t_read_control_elements::third_word().
Referenced by t_control_data_surfacings::read_surfacing_controls().
Variable Documentation
hd_iso_ctl
character(len=kchara), parameter, private t_control_data_isosurfaces::hd_iso_ctl = 'isosurf_rendering' private
Definition at line 45 of file t_control_data_isosurfaces.f90.
Referenced by read_control_4_iso_file().
hd_isosurf_ctl
character(len=kchara), parameter, private t_control_data_isosurfaces::hd_isosurf_ctl = 'isosurface_ctl' private
Definition at line 43 of file t_control_data_isosurfaces.f90.
Referenced by read_control_4_iso_file(), t_control_data_surfacings::read_surfacing_controls(), and t_control_data_surfacings::set_label_surfacings().