CALYPSO: t_convert_from_rayleigh Module Reference
t_convert_from_rayleigh Module Reference
Main loop to assemble spectr data.
Data Types
type work_fftpack_chebyshev
type work_rayleigh_checkpoint
Functions/Subroutines
subroutine alloc_work_rayleigh_restart (nri_org, r_itp, rayleigh_WK)
subroutine init_fftpack_4_cheby (nri_tgt, fcheby_WK, ierr)
subroutine dealloc_work_rayleigh_restart (rayleigh_WK)
subroutine dealloc_fftpack_4_cheby (fcheby_WK)
subroutine init_rayleigh_restart_params (istep_start, org_fld_file, ra_rst)
subroutine copy_rayleigh_radial_data (ra_rst, org_sph_mesh)
subroutine chebyshev_fwd_mat_4_rayleigh (new_sph_mesh, r_itp, ra_rst)
subroutine rescaling_from_rayleigh (l, m, nri_org, rayleigh_in)
subroutine rescaling_for_chebyshev_fft (nri_org, rayleigh_in, nri_tgt, rayleigh_tg)
subroutine radial_interpolation_rayleigh (r_itp, nri_org, rayleigh_in, nri_tgt, rayleigh_tg)
subroutine copy_from_chebyshev_trans (sph_rj, r_itp, j, i_comp, nri_tgt, rayleigh_tg, new_sph_phys)
Detailed Description
Main loop to assemble spectr data.
      subroutine alloc_work_rayleigh_restart                          &
     &         (nri_org, r_itp, rayleigh_WK)
        type(sph_radial_itp_data), intent(in) :: r_itp
        type(work_rayleigh_checkpoint), intent(inout) :: rayleigh_WK
      subroutine init_fftpack_4_cheby(nri_tgt, fcheby_WK, ierr)
        type(work_fftpack_chebyshev), intent(inout) :: fcheby_WK
      subroutine dealloc_work_rayleigh_restart(rayleigh_WK)
        type(work_rayleigh_checkpoint), intent(inout) :: rayleigh_WK
      subroutine dealloc_fftpack_4_cheby(fcheby_WK)
        type(work_fftpack_chebyshev), intent(inout) :: fcheby_WK
      subroutine init_rayleigh_restart_params                         &
     &         (istep_start, org_fld_file, ra_rst)
      subroutine copy_rayleigh_radial_data(ra_rst, org_sph_mesh)
        type(rayleigh_restart), intent(in) :: ra_rst
        type(sph_mesh_data), intent(inout) :: org_sph_mesh
      subroutine chebyshev_fwd_mat_4_rayleigh                         &
     &         (new_sph_mesh, r_itp, ra_rst)
        type(sph_mesh_data), intent(in) :: new_sph_mesh
        type(sph_radial_itp_data), intent(in) :: r_itp
        type(rayleigh_restart), intent(inout) :: ra_rst
      subroutine rescaling_from_rayleigh(l, m, nri_org, rayleigh_in)
      subroutine rescaling_for_chebyshev_FFT                          &
     &         (nri_org, rayleigh_in, nri_tgt, rayleigh_tg)
      subroutine radial_interpolation_rayleigh                        &
     &         (r_itp, nri_org, rayleigh_in, nri_tgt, rayleigh_tg)
      subroutine copy_from_chebyshev_trans(sph_rj, r_itp, j, i_comp,  &
     &          nri_tgt, rayleigh_tg, new_sph_phys)
Function/Subroutine Documentation
alloc_work_rayleigh_restart()
subroutine t_convert_from_rayleigh::alloc_work_rayleigh_restart (integer(kind = kint), intent(in) nri_org, type(sph_radial_itp_data), intent(in) r_itp, type(work_rayleigh_checkpoint), intent(inout) rayleigh_WK)
Definition at line 88 of file t_convert_from_rayleigh.f90.
Referenced by convert_from_rayleigh_rst::convert_fields_from_rayleigh().
chebyshev_fwd_mat_4_rayleigh()
subroutine t_convert_from_rayleigh::chebyshev_fwd_mat_4_rayleigh (type(sph_mesh_data), intent(in) new_sph_mesh, type(sph_radial_itp_data), intent(in) r_itp, type(rayleigh_restart), intent(inout) ra_rst)
Definition at line 197 of file t_convert_from_rayleigh.f90.
References calypso_mpi_real::calypso_mpi_bcast_real(), calypso_mpi::my_rank, m_constants::one, and m_constants::two.
copy_from_chebyshev_trans()
subroutine t_convert_from_rayleigh::copy_from_chebyshev_trans (type(sph_rj_grid), intent(in) sph_rj, type(sph_radial_itp_data), intent(in) r_itp, integer(kind = kint), intent(in) j, integer(kind = kint), intent(in) i_comp, integer(kind = kint), intent(in) nri_tgt, real(kind = kreal), dimension(nri_tgt+1,1), intent(in) rayleigh_tg, type(phys_data), intent(inout) new_sph_phys)
Definition at line 332 of file t_convert_from_rayleigh.f90.
Referenced by convert_from_rayleigh_rst::cvt_each_field_from_rayleigh().
copy_rayleigh_radial_data()
subroutine t_convert_from_rayleigh::copy_rayleigh_radial_data (type(rayleigh_restart), intent(in) ra_rst, type(sph_mesh_data), intent(inout) org_sph_mesh)
Definition at line 177 of file t_convert_from_rayleigh.f90.
Referenced by analyzer_rayleigh_cvt_sph::init_cvt_rayleigh_sph().
dealloc_fftpack_4_cheby()
subroutine t_convert_from_rayleigh::dealloc_fftpack_4_cheby (type(work_fftpack_chebyshev), intent(inout) fcheby_WK)
Definition at line 141 of file t_convert_from_rayleigh.f90.
Referenced by convert_from_rayleigh_rst::convert_fields_from_rayleigh().
dealloc_work_rayleigh_restart()
subroutine t_convert_from_rayleigh::dealloc_work_rayleigh_restart (type(work_rayleigh_checkpoint), intent(inout) rayleigh_WK)
Definition at line 129 of file t_convert_from_rayleigh.f90.
Referenced by convert_from_rayleigh_rst::convert_fields_from_rayleigh().
init_fftpack_4_cheby()
subroutine t_convert_from_rayleigh::init_fftpack_4_cheby (integer(kind = kint), intent(in) nri_tgt, type(work_fftpack_chebyshev), intent(inout) fcheby_WK, integer(kind = kint), intent(inout) ierr)
Definition at line 110 of file t_convert_from_rayleigh.f90.
References cost1i().
Referenced by convert_from_rayleigh_rst::convert_fields_from_rayleigh().
init_rayleigh_restart_params()
subroutine t_convert_from_rayleigh::init_rayleigh_restart_params (integer(kind = kint), intent(in) istep_start, type(field_io_params), intent(in) org_fld_file, type(rayleigh_restart), intent(inout) ra_rst)
Definition at line 153 of file t_convert_from_rayleigh.f90.
References calypso_mpi::calypso_mpi_barrier(), calypso_mpi::my_rank, and rayleigh_restart_io::sel_read_rayleigh_rst_params().
Referenced by analyzer_rayleigh_cvt_sph::analyze_cvt_rayleigh_sph(), and analyzer_rayleigh_cvt_sph::init_cvt_rayleigh_sph().
radial_interpolation_rayleigh()
subroutine t_convert_from_rayleigh::radial_interpolation_rayleigh (type(sph_radial_itp_data), intent(in) r_itp, integer(kind = kint), intent(in) nri_org, real(kind = kreal), dimension(nri_org), intent(in) rayleigh_in, integer(kind = kint), intent(in) nri_tgt, real(kind = kreal), dimension(nri_tgt+1), intent(inout) rayleigh_tg)
Definition at line 308 of file t_convert_from_rayleigh.f90.
Referenced by convert_from_rayleigh_rst::cvt_each_field_from_rayleigh().
rescaling_for_chebyshev_fft()
subroutine t_convert_from_rayleigh::rescaling_for_chebyshev_fft (integer(kind = kint), intent(in) nri_org, real(kind = kreal), dimension(nri_org), intent(in) rayleigh_in, integer(kind = kint), intent(in) nri_tgt, real(kind = kreal), dimension(nri_tgt+1), intent(inout) rayleigh_tg)
Definition at line 283 of file t_convert_from_rayleigh.f90.
References m_constants::half, and m_constants::one.
Referenced by convert_from_rayleigh_rst::cvt_each_field_from_rayleigh().
rescaling_from_rayleigh()
subroutine t_convert_from_rayleigh::rescaling_from_rayleigh (integer(kind = kint), intent(in) l, integer(kind = kint), intent(in) m, integer(kind = kint), intent(in) nri_org, real(kind = kreal), dimension(nri_org,2), intent(inout) rayleigh_in)
Definition at line 251 of file t_convert_from_rayleigh.f90.
References m_constants::four, m_constants::one, and m_constants::two.
Referenced by convert_from_rayleigh_rst::cvt_each_field_from_rayleigh().