CALYPSO: field_to_send_buffer Module Reference
field_to_send_buffer Module Reference
Arbitrary components data communication.
Functions/Subroutines
subroutine set_to_send_buf_vector (NB, nnod_org, nnod_send, inod_export, ncomp_X, i_fld_X, i_fld_WS, d_org, WS)
subroutine set_to_send_buf_scalar (NB, nnod_org, nnod_send, inod_export, ncomp_X, i_fld_X, i_fld_WS, d_org, WS)
subroutine set_to_send_buf_tensor (NB, nnod_org, nnod_send, inod_export, ncomp_X, i_fld_X, i_fld_WS, d_org, WS)
subroutine set_from_recv_buf_vector (NB, nnod_new, nnod_recv, inod_import, ncomp_X, i_fld_X, i_fld_WR, WR, d_new)
subroutine set_from_recv_buf_scalar (NB, nnod_new, nnod_recv, inod_import, ncomp_X, i_fld_X, i_fld_WR, WR, d_new)
subroutine set_from_recv_buf_tensor (NB, nnod_new, nnod_recv, inod_import, ncomp_X, i_fld_X, i_fld_WR, WR, d_new)
subroutine set_from_recv_buf_rev_vector (NB, nnod_new, nnod_recv, irev_import, ncomp_X, i_fld_X, i_fld_WR, WR, d_new)
subroutine set_from_recv_buf_rev_scalar (NB, nnod_new, nnod_recv, irev_import, ncomp_X, i_fld_X, i_fld_WR, WR, d_new)
subroutine set_from_recv_buf_rev_tensor (NB, nnod_new, nnod_recv, irev_import, ncomp_X, i_fld_X, i_fld_WR, WR, d_new)
Detailed Description
Arbitrary components data communication.
      subroutine set_to_send_buf_vector(NB, nnod_org, nnod_send,      &
     &          inod_export, ncomp_X, i_fld_X, i_fld_WS, d_org, WS)
      subroutine set_to_send_buf_scalar(NB, nnod_org, nnod_send,      &
     &          inod_export, ncomp_X, i_fld_X, i_fld_WS, d_org, WS)
      subroutine set_to_send_buf_tensor(NB, nnod_org, nnod_send,      &
     &          inod_export, ncomp_X, i_fld_X, i_fld_WS, d_org, WS)
Parameters
NB Number of components for communication
nnod_org Number of data points for origin
npe_send Number of processses to send
isend_self Integer flag to copy within own process
nnod_send Number of data points to send
istack_send(0:npe_send) End points of send buffer for each process
inod_export(nnod_send) local node ID to copy in send buffer
d_org(nnod_org,NB) Send data
Function/Subroutine Documentation
set_from_recv_buf_rev_scalar()
subroutine field_to_send_buffer::set_from_recv_buf_rev_scalar (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) nnod_recv, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, integer(kind = kint), intent(in) ncomp_X, integer(kind = kint), intent(in) i_fld_X, integer(kind = kint), intent(in) i_fld_WR, real (kind=kreal), dimension(nb*(nnod_recv+1)), intent(inout) WR, real (kind=kreal), dimension(nnod_new,ncomp_x), intent(inout) d_new)
Definition at line 278 of file field_to_send_buffer.f90.
Referenced by sel_spherical_srs::sel_sph_scalar_from_recv().
set_from_recv_buf_rev_tensor()
subroutine field_to_send_buffer::set_from_recv_buf_rev_tensor (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) nnod_recv, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, integer(kind = kint), intent(in) ncomp_X, integer(kind = kint), intent(in) i_fld_X, integer(kind = kint), intent(in) i_fld_WR, real (kind=kreal), dimension(nb*(nnod_recv+1)), intent(inout) WR, real (kind=kreal), dimension(nnod_new,ncomp_x), intent(inout) d_new)
Definition at line 306 of file field_to_send_buffer.f90.
Referenced by sel_spherical_srs::sel_sph_tensor_from_recv().
set_from_recv_buf_rev_vector()
subroutine field_to_send_buffer::set_from_recv_buf_rev_vector (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) nnod_recv, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, integer(kind = kint), intent(in) ncomp_X, integer(kind = kint), intent(in) i_fld_X, integer(kind = kint), intent(in) i_fld_WR, real (kind=kreal), dimension(nb*(nnod_recv+1)), intent(inout) WR, real (kind=kreal), dimension(nnod_new,ncomp_x), intent(inout) d_new)
Definition at line 246 of file field_to_send_buffer.f90.
Referenced by sel_spherical_srs::sel_sph_vector_from_recv().
set_from_recv_buf_scalar()
subroutine field_to_send_buffer::set_from_recv_buf_scalar (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) nnod_recv, integer(kind = kint), dimension(nnod_recv), intent(in) inod_import, integer(kind = kint), intent(in) ncomp_X, integer(kind = kint), intent(in) i_fld_X, integer(kind = kint), intent(in) i_fld_WR, real (kind=kreal), dimension(nb*nnod_recv), intent(in) WR, real (kind=kreal), dimension(nnod_new,ncomp_x), intent(inout) d_new)
Definition at line 169 of file field_to_send_buffer.f90.
Referenced by sel_spherical_srs::sel_sph_scalar_from_recv().
set_from_recv_buf_tensor()
subroutine field_to_send_buffer::set_from_recv_buf_tensor (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) nnod_recv, integer(kind = kint), dimension(nnod_recv), intent(in) inod_import, integer(kind = kint), intent(in) ncomp_X, integer(kind = kint), intent(in) i_fld_X, integer(kind = kint), intent(in) i_fld_WR, real (kind=kreal), dimension(nb*nnod_recv), intent(in) WR, real (kind=kreal), dimension(nnod_new,ncomp_x), intent(inout) d_new)
Definition at line 202 of file field_to_send_buffer.f90.
Referenced by sel_spherical_srs::sel_sph_tensor_from_recv().
set_from_recv_buf_vector()
subroutine field_to_send_buffer::set_from_recv_buf_vector (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) nnod_recv, integer(kind = kint), dimension(nnod_recv), intent(in) inod_import, integer(kind = kint), intent(in) ncomp_X, integer(kind = kint), intent(in) i_fld_X, integer(kind = kint), intent(in) i_fld_WR, real (kind=kreal), dimension(nb*nnod_recv), intent(in) WR, real (kind=kreal), dimension(nnod_new,ncomp_x), intent(inout) d_new)
Definition at line 132 of file field_to_send_buffer.f90.
Referenced by sel_spherical_srs::sel_sph_vector_from_recv().
set_to_send_buf_scalar()
subroutine field_to_send_buffer::set_to_send_buf_scalar (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) nnod_send, integer(kind = kint), dimension(nnod_send), intent(in) inod_export, integer(kind = kint), intent(in) ncomp_X, integer(kind = kint), intent(in) i_fld_X, integer(kind = kint), intent(in) i_fld_WS, real (kind=kreal), dimension(nnod_org,ncomp_x), intent(in) d_org, real (kind=kreal), dimension(nb*nnod_send), intent(inout) WS)
Definition at line 72 of file field_to_send_buffer.f90.
Referenced by sel_spherical_srs::sel_calypso_to_send_scalar().
set_to_send_buf_tensor()
subroutine field_to_send_buffer::set_to_send_buf_tensor (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) nnod_send, integer(kind = kint), dimension(nnod_send), intent(in) inod_export, integer(kind = kint), intent(in) ncomp_X, integer(kind = kint), intent(in) i_fld_X, integer(kind = kint), intent(in) i_fld_WS, real (kind=kreal), dimension(nnod_org,ncomp_x), intent(in) d_org, real (kind=kreal), dimension(nb*nnod_send), intent(inout) WS)
Definition at line 99 of file field_to_send_buffer.f90.
Referenced by sel_spherical_srs::sel_calypso_to_send_tensor().
set_to_send_buf_vector()
subroutine field_to_send_buffer::set_to_send_buf_vector (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) nnod_send, integer(kind = kint), dimension(nnod_send), intent(in) inod_export, integer(kind = kint), intent(in) ncomp_X, integer(kind = kint), intent(in) i_fld_X, integer(kind = kint), intent(in) i_fld_WS, real (kind=kreal), dimension(nnod_org,ncomp_x), intent(in) d_org, real (kind=kreal), dimension(nb*nnod_send), intent(inout) WS)
Definition at line 43 of file field_to_send_buffer.f90.
Referenced by sel_spherical_srs::sel_calypso_to_send_vector().