CALYPSO: copy_fields_from_sph_trans Module Reference
copy_fields_from_sph_trans Module Reference
Copy data from/to sphrical transform buffer for snapshots.
Functions/Subroutines
subroutine copy_scalar_from_snap_trans (i_trns, i_field, m_folding, sph_rtp, backward, node, nod_fld)
subroutine copy_vector_from_snap_trans (i_trns, i_field, m_folding, sph_rtp, backward, node, nod_fld)
subroutine copy_tensor_from_snap_trans (i_trns, i_field, m_folding, sph_rtp, backward, node, nod_fld)
subroutine copy_scalar_from_snap_force (i_trns, i_field, m_folding, sph_rtp, forward, node, nod_fld)
subroutine copy_vector_from_snap_force (i_trns, i_field, m_folding, sph_rtp, forward, node, nod_fld)
subroutine copy_tensor_from_snap_force (i_trns, i_field, m_folding, sph_rtp, forward, node, nod_fld)
Detailed Description
Copy data from/to sphrical transform buffer for snapshots.
      subroutine copy_scalar_from_snap_trans(i_trns, i_field,         &
     &          m_folding, sph_rtp, backward, node, nod_fld)
      subroutine copy_vector_from_snap_trans(i_trns, i_field,         &
     &          m_folding, sph_rtp, backward, node, nod_fld)
      subroutine copy_tensor_from_snap_trans(i_trns, i_field,         &
     &          m_folding, sph_rtp, backward, node, nod_fld)
      subroutine copy_scalar_from_snap_force(i_trns, i_field,         &
     &          m_folding, sph_rtp, forward, node, nod_fld)
      subroutine copy_vector_from_snap_force(i_trns, i_field,         &
     &          m_folding, sph_rtp, forward, node, nod_fld)
      subroutine copy_tensor_from_snap_force(i_trns, i_field,         &
     &          m_folding, sph_rtp, forward, node, nod_fld)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(spherical_transform_data), intent(in) :: forward
        type(node_data), intent(in) :: node
        type(phys_data), intent(inout) :: nod_fld
Function/Subroutine Documentation
copy_scalar_from_snap_force()
subroutine copy_fields_from_sph_trans::copy_scalar_from_snap_force (integer(kind = kint), intent(in) i_trns, integer(kind = kint), intent(in) i_field, integer(kind = kint), intent(in) m_folding, type(sph_rtp_grid), intent(in) sph_rtp, type(spherical_transform_data), intent(in) forward, type(node_data), intent(in) node, type(phys_data), intent(inout) nod_fld)
Definition at line 115 of file copy_fields_from_sph_trans.f90.
References copy_nodal_fld_4_sph_trans::copy_nod_scl_from_trans_wpole().
Referenced by set_address_sph_trans_snap::copy_force_from_transform().
copy_scalar_from_snap_trans()
subroutine copy_fields_from_sph_trans::copy_scalar_from_snap_trans (integer(kind = kint), intent(in) i_trns, integer(kind = kint), intent(in) i_field, integer(kind = kint), intent(in) m_folding, type(sph_rtp_grid), intent(in) sph_rtp, type(spherical_transform_data), intent(in) backward, type(node_data), intent(in) node, type(phys_data), intent(inout) nod_fld)
Definition at line 48 of file copy_fields_from_sph_trans.f90.
References copy_nodal_fld_4_sph_trans::copy_nod_scl_from_trans_wpole().
Referenced by set_address_sph_trans_snap::copy_field_from_transform().
copy_tensor_from_snap_force()
subroutine copy_fields_from_sph_trans::copy_tensor_from_snap_force (integer(kind = kint), intent(in) i_trns, integer(kind = kint), intent(in) i_field, integer(kind = kint), intent(in) m_folding, type(sph_rtp_grid), intent(in) sph_rtp, type(spherical_transform_data), intent(in) forward, type(node_data), intent(in) node, type(phys_data), intent(inout) nod_fld)
Definition at line 159 of file copy_fields_from_sph_trans.f90.
References copy_nodal_fld_4_sph_trans::copy_nod_tsr_from_trans_wpole().
copy_tensor_from_snap_trans()
subroutine copy_fields_from_sph_trans::copy_tensor_from_snap_trans (integer(kind = kint), intent(in) i_trns, integer(kind = kint), intent(in) i_field, integer(kind = kint), intent(in) m_folding, type(sph_rtp_grid), intent(in) sph_rtp, type(spherical_transform_data), intent(in) backward, type(node_data), intent(in) node, type(phys_data), intent(inout) nod_fld)
Definition at line 92 of file copy_fields_from_sph_trans.f90.
References copy_nodal_fld_4_sph_trans::copy_nod_tsr_from_trans_wpole().
copy_vector_from_snap_force()
subroutine copy_fields_from_sph_trans::copy_vector_from_snap_force (integer(kind = kint), intent(in) i_trns, integer(kind = kint), intent(in) i_field, integer(kind = kint), intent(in) m_folding, type(sph_rtp_grid), intent(in) sph_rtp, type(spherical_transform_data), intent(in) forward, type(node_data), intent(in) node, type(phys_data), intent(inout) nod_fld)
Definition at line 137 of file copy_fields_from_sph_trans.f90.
References copy_nodal_fld_4_sph_trans::copy_nod_vec_from_trans_wpole().
Referenced by set_address_sph_trans_snap::copy_force_from_transform().
copy_vector_from_snap_trans()
subroutine copy_fields_from_sph_trans::copy_vector_from_snap_trans (integer(kind = kint), intent(in) i_trns, integer(kind = kint), intent(in) i_field, integer(kind = kint), intent(in) m_folding, type(sph_rtp_grid), intent(in) sph_rtp, type(spherical_transform_data), intent(in) backward, type(node_data), intent(in) node, type(phys_data), intent(inout) nod_fld)
Definition at line 70 of file copy_fields_from_sph_trans.f90.
References copy_nodal_fld_4_sph_trans::copy_nod_vec_from_trans_wpole().
Referenced by set_address_sph_trans_snap::copy_field_from_transform().