CALYPSO: lubksb_357band_mul Module Reference
lubksb_357band_mul Module Reference
Solve more than one 3, 5, or 7 band matriox at once after LU decomposition.
Functions/Subroutines
subroutine lubksb_3band_mul (Msmp, Msmp_stack, mcomp, n, band_lu, i_pivot, x)
subroutine lubksb_5band_mul (Msmp, Msmp_stack, mcomp, n, band_lu, i_pivot, x)
subroutine lubksb_7band_mul (Msmp, Msmp_stack, mcomp, n, band_lu, i_pivot, x)
Detailed Description
Solve more than one 3, 5, or 7 band matriox at once after LU decomposition.
---------------------------------------------------------------------
      subroutine lubksb_3band_mul(Msmp, Msmp_stack, mcomp, n,         &
     &          band_lu, i_pivot, x)
      subroutine lubksb_5band_mul(Msmp, Msmp_stack, mcomp, n,         &
     &          band_lu, i_pivot, x)
      subroutine lubksb_7band_mul(Msmp, Msmp_stack, mcomp, n,         &
     &          band_lu, i_pivot, x)
 solve the set of n linear equations Ax=b. Here is band_lu input
 matrix after LU decompsition, determined by the routine ludcmp_band.
 i_pivot is input as the
 permutation vector returned by ludcmp. b(1:n) is input
 as the right-hand side vectror b, and returns with the
 solution vector x.
 band_lu, n, np and i_pivot are not modified by this routine
 and be left in place for successive calls with different
 right hand sides b. This routine takes into account
 the possibility that b will begin with many zero elements,
 so it is efficient for use in matrix inversion.
   Format of band matrix
               | a(2,1)  a(1,2)  ........     0         0     |
               | a(3,1)  a(2,2)  ........     .         .     |
               |   0     a(3,2)  ........     .         .     |
    a(i,j)  =  |   .       0     ........     0         .     |
               | ...... a(3,k-1)  a(2,k)  a(1,k+1) .......... |
               |   .       .     ........  a(1,N-2)     0     |
               |   .       .     ........  a(2,N-2)  a(1,N-1) |
               |   0       0     ........  a(3,N-2)  a(2,N-1) |
   Arbitorary band matrix
      band_a(i-j+iband+1,j) = a(i,j)
      band_a(k,j) = a(k+j-iband-1,j)
   3-band matrix
      band_a(i-j+2,j) = a(i,j)
      band_a(k,j) = a(k+j-2,j)
   5-band matrix
      band_lu(i-j+3,j) = a(i,j)
      band_lu(k,j) = a(k+j-3,j)
   7-band matrix
      band_lu(i-j+4,j) = a(i,j)
      band_lu(k,j) = a(k+j-4,j)
   9-band matrix
      band_lu(i-j+5,j) = a(i,j)
      band_lu(k,j) = a(k+j-5,j)
---------------------------------------------------------------------
Function/Subroutine Documentation
lubksb_3band_mul()
subroutine lubksb_357band_mul::lubksb_3band_mul (integer (kind = kint), intent(in) Msmp, integer (kind = kint), dimension(0:msmp), intent(in) Msmp_stack, integer (kind = kint), intent(in) mcomp, integer (kind = kint), intent(in) n, real(kind = kreal), dimension(5,n,mcomp), intent(in) band_lu, integer (kind = kint), dimension(n,mcomp), intent(in) i_pivot, real(kind = kreal), dimension(mcomp,n), intent(inout) x)
Definition at line 73 of file lubksb_357band_mul.f90.
Referenced by t_sph_matrices::lubksb_3band_mul_t().
lubksb_5band_mul()
subroutine lubksb_357band_mul::lubksb_5band_mul (integer (kind = kint), intent(in) Msmp, integer (kind = kint), dimension(0:msmp), intent(in) Msmp_stack, integer (kind = kint), intent(in) mcomp, integer (kind = kint), intent(in) n, real(kind = kreal), dimension(9,n,mcomp), intent(in) band_lu, integer (kind = kint), dimension(n,mcomp), intent(in) i_pivot, real(kind = kreal), dimension(mcomp,n), intent(inout) x)
Definition at line 128 of file lubksb_357band_mul.f90.
Referenced by t_sph_matrices::lubksb_5band_mul_t().
lubksb_7band_mul()
subroutine lubksb_357band_mul::lubksb_7band_mul (integer (kind = kint), intent(in) Msmp, integer (kind = kint), dimension(0:msmp), intent(in) Msmp_stack, integer (kind = kint), intent(in) mcomp, integer (kind = kint), intent(in) n, real(kind = kreal), dimension(13,n,mcomp), intent(in) band_lu, integer (kind = kint), dimension(n,mcomp), intent(in) i_pivot, real(kind = kreal), dimension(mcomp,n), intent(inout) x)
Definition at line 199 of file lubksb_357band_mul.f90.
Referenced by t_sph_matrices::lubksb_7band_mul_t().