CALYPSO: copy_sph_rtp_node_4_io Module Reference
copy_sph_rtp_node_4_io Module Reference
Copy sphectr indices structure between IO buffer.
Functions/Subroutines
subroutine copy_sph_node_4_rtp_from_io (sph_IO, rtp, l_truncation)
subroutine copy_sph_node_4_rtp_to_io (l_truncation, rtp, sph_IO)
integer(kind=kint) function compare_sph_rtp_node_with_io (l_truncation, rtp, sph_IO)
Detailed Description
Copy sphectr indices structure between IO buffer.
      subroutine copy_sph_node_4_rtp_from_IO(sph_IO, rtp, l_truncation)
        integer(kind = kint), intent(inout) :: l_truncation
        type(sph_rtp_grid), intent(inout) :: rtp
        type(sph_IO_data), intent(in) :: sph_IO
      subroutine copy_sph_node_4_rtp_to_IO(l_truncation, rtp, sph_IO)
        integer(kind = kint), intent(in) :: l_truncation
        type(sph_rtp_grid), intent(in) :: rtp
        type(sph_IO_data), intent(inout) :: sph_IO
      integer(kind = kint) function compare_sph_rtp_node_with_IO      &
     &                            (l_truncation, rtp, sph_IO)
        type(sph_rtp_grid), intent(in) :: rtp
        type(sph_IO_data), intent(in) :: sph_IO
Function/Subroutine Documentation
compare_sph_rtp_node_with_io()
integer(kind = kint) function copy_sph_rtp_node_4_io::compare_sph_rtp_node_with_io (integer(kind = kint), intent(in) l_truncation, type(sph_rtp_grid), intent(in) rtp, type(sph_io_data), intent(in) sph_IO)
Definition at line 161 of file copy_sph_rtp_node_4_IO.f90.
References m_constants::ithree.
Referenced by compare_sph_with_io::compare_sph_rtp_with_io().
copy_sph_node_4_rtp_from_io()
subroutine copy_sph_rtp_node_4_io::copy_sph_node_4_rtp_from_io (type(sph_io_data), intent(in) sph_IO, type(sph_rtp_grid), intent(inout) rtp, integer(kind = kint), intent(inout) l_truncation)
Definition at line 41 of file copy_sph_rtp_node_4_IO.f90.
References t_spheric_rtp_data::alloc_sph_1d_index_rtp(), t_spheric_rtp_data::alloc_spheric_param_rtp(), and m_constants::ithree.
Referenced by load_data_for_sph_io::copy_sph_trans_rtp_from_io().
copy_sph_node_4_rtp_to_io()
subroutine copy_sph_rtp_node_4_io::copy_sph_node_4_rtp_to_io (integer(kind = kint), intent(in) l_truncation, type(sph_rtp_grid), intent(in) rtp, type(sph_io_data), intent(inout) sph_IO)
Definition at line 91 of file copy_sph_rtp_node_4_IO.f90.
References t_node_id_spherical_io::alloc_idx_sph_1d1_io(), t_node_id_spherical_io::alloc_idx_sph_1d2_io(), t_node_id_spherical_io::alloc_idx_sph_1d3_io(), t_node_id_spherical_io::alloc_nod_id_sph_io(), t_node_id_spherical_io::alloc_num_idx_sph_io(), m_constants::ione, m_constants::ithree, and m_constants::itwo.
Referenced by load_data_for_sph_io::copy_sph_trans_rtp_to_io().