CALYPSO: m_diffusion_term_labels Module Reference
m_diffusion_term_labels Module Reference
Functions/Subroutines
logical function check_vector_diffusion (field_name)
logical function check_scalar_diffusion (field_name)
logical function check_diffusivity (field_name)
integer(kind=kint) function num_base_diffusions ()
integer(kind=kint) function num_base_diffusivities ()
subroutine set_base_diffusion_labels (n_comps, names, maths)
subroutine set_base_diffusivity_labels (n_comps, names, maths)
Variables
integer(kind=kint), parameter, private ndiffusion = 7
Numbder of diffusion terms.
integer(kind=kint), parameter, private ndiffusivities = 7
Numbder of diffusivities.
type(field_def), parameter viscous_diffusion = field_def(n_comp = n_vector, name = 'viscous_diffusion', math = '$ \nu \partial_{j}\partial_{j} u_{i} $')
Field label for viscous diffusion \(\nu \partial_{j}\partial_{j} u_{i} \).
type(field_def), parameter vorticity_diffusion = field_def(n_comp = n_vector, name = 'vorticity_diffusion', math = '$ \nu \partial_{j}\partial_{j}' // ' \omega_{i} $')
Field label for diffusion of vorticity \(\nu \partial_{j}\partial_{j} \omega_{i} \).
type(field_def), parameter vector_potential_diffusion = field_def(n_comp = n_vector, name = 'vector_potential_diffusion', math = '$ -J_{i}' // ' = \eta \partial_{j}\partial_{j} A_{i} $')
Field label for diffusion of vetor potential \(-J_{i} = \eta \partial_{j}\partial_{j} A_{i} \).
type(field_def), parameter magnetic_diffusion = field_def(n_comp = n_vector, name = 'magnetic_diffusion', math = '$ \eta \partial_{j}\partial_{j} B_{i} $')
Field label for magnetic diffusion \(\nu \partial_{j}\partial_{j} B_{i} \).
type(field_def), parameter thermal_diffusion = field_def(n_comp = n_scalar, name = 'thermal_diffusion', math = '$ \kappa_{T} \partial_{j}\partial_{j} T $')
Field label for thermal diffusion \(\kappa \partial_{i}\partial_{i} T \).
type(field_def), parameter composition_diffusion = field_def(n_comp = n_scalar, name = 'composition_diffusion', math = '$ \kappa_{C} \partial_{j}\partial_{j} C $')
Field label for compositional diffusion \(\kappa \partial_{i}\partial_{i} C \).
type(field_def), parameter div_viscousity = field_def(n_comp = n_scalar, name = 'div_viscousity', math = '$ \nu \partial_{i}' // ' \partial_{j}\partial_{j} u_{i} $')
Field label for divergence of viscousity \(\nu \partial_{i} \partial_{j}\partial_{j} u_{i} \).
type(field_def), parameter kinetic_viscosity = field_def(n_comp = n_vector, name = 'kinetic_viscosity', math = '$ \nu = \mu / \bar{\rho} $')
Field label for kinetic viscosity \(\nu = \mu / \bar{\rho} \).
type(field_def), parameter magnetic_diffusivity = field_def(n_comp = n_vector, name = 'magnetic_diffusivity', math = '$ \eta $')
Field label for magnetic diffusivity \(\eta \).
type(field_def), parameter thermal_diffusivity = field_def(n_comp = n_vector, name = 'thermal_diffusivity', math = '$ \kappa_{T} = k / \bar{\rho} $')
Field label for thermal diffusivity \(\kappa_{T} = k / \bar{\rho} \).
type(field_def), parameter chemical_diffusivity = field_def(n_comp = n_vector, name = 'chemical_diffusivity', math = '$ \kappa_{C} $')
Field label for chemical diffusivity \(\kappa_{C} \).
type(field_def), parameter viscosity = field_def(n_comp = n_vector, name = 'viscosity', math = '$ \mu $')
Field label for viscosity \(\mu \).
type(field_def), parameter thermal_conductivity = field_def(n_comp = n_vector, name = 'thermal_conductivity', math = '$ k_{T} $')
Field label for thermal diffusivity \(k_{T} \).
type(field_def), parameter chemical_conductivity = field_def(n_comp = n_vector, name = 'chemical_conductivity', math = '$ k_{C} $')
Field label for chemical diffusivity \(k_{C} \).
Function/Subroutine Documentation
check_diffusivity()
logical function m_diffusion_term_labels::check_diffusivity (character(len = kchara), intent(in) field_name)
Definition at line 185 of file m_diffusion_term_labels.f90.
References chemical_conductivity, chemical_diffusivity, kinetic_viscosity, magnetic_diffusivity, thermal_conductivity, thermal_diffusivity, and viscosity.
Referenced by t_diffusion_term_labels::set_diffusivity_addresses().
check_scalar_diffusion()
logical function m_diffusion_term_labels::check_scalar_diffusion (character(len = kchara), intent(in) field_name)
Definition at line 171 of file m_diffusion_term_labels.f90.
References composition_diffusion, div_viscousity, and thermal_diffusion.
Referenced by set_mhd_field_address::check_scalar_fields(), and t_diffusion_term_labels::set_base_diffusion_addresses().
check_vector_diffusion()
logical function m_diffusion_term_labels::check_vector_diffusion (character(len = kchara), intent(in) field_name)
Definition at line 156 of file m_diffusion_term_labels.f90.
References magnetic_diffusion, vector_potential_diffusion, viscous_diffusion, and vorticity_diffusion.
Referenced by set_mhd_field_address::check_vector_fields(), and t_diffusion_term_labels::set_base_diffusion_addresses().
num_base_diffusions()
integer(kind = kint) function m_diffusion_term_labels::num_base_diffusions
Definition at line 204 of file m_diffusion_term_labels.f90.
References ndiffusion.
num_base_diffusivities()
integer(kind = kint) function m_diffusion_term_labels::num_base_diffusivities
Definition at line 211 of file m_diffusion_term_labels.f90.
References ndiffusivities.
set_base_diffusion_labels()
subroutine m_diffusion_term_labels::set_base_diffusion_labels (integer(kind = kint_4b), dimension(ndiffusion), intent(inout) n_comps, character(len = kchara), dimension(ndiffusion), intent(inout) names, character(len = kchara), dimension(ndiffusion), intent(inout) maths)
Definition at line 218 of file m_diffusion_term_labels.f90.
References composition_diffusion, div_viscousity, magnetic_diffusion, t_field_labels::set_field_labels(), thermal_diffusion, vector_potential_diffusion, viscous_diffusion, and vorticity_diffusion.
set_base_diffusivity_labels()
subroutine m_diffusion_term_labels::set_base_diffusivity_labels (integer(kind = kint_4b), dimension(ndiffusivities), intent(inout) n_comps, character(len = kchara), dimension(ndiffusivities), intent(inout) names, character(len = kchara), dimension(ndiffusivities), intent(inout) maths)
Definition at line 246 of file m_diffusion_term_labels.f90.
References chemical_conductivity, chemical_diffusivity, kinetic_viscosity, magnetic_diffusivity, t_field_labels::set_field_labels(), thermal_conductivity, thermal_diffusivity, and viscosity.
Variable Documentation
chemical_conductivity
type(field_def), parameter m_diffusion_term_labels::chemical_conductivity = field_def(n_comp = n_vector, name = 'chemical_conductivity', math = '$ k_{C} $')
Field label for chemical diffusivity \(k_{C} \).
Definition at line 145 of file m_diffusion_term_labels.f90.
Referenced by check_diffusivity(), set_base_diffusivity_labels(), and t_diffusion_term_labels::set_diffusivity_addresses().
chemical_diffusivity
type(field_def), parameter m_diffusion_term_labels::chemical_diffusivity = field_def(n_comp = n_vector, name = 'chemical_diffusivity', math = '$ \kappa_{C} $')
Field label for chemical diffusivity \(\kappa_{C} \).
Definition at line 129 of file m_diffusion_term_labels.f90.
Referenced by check_diffusivity(), set_base_diffusivity_labels(), and t_diffusion_term_labels::set_diffusivity_addresses().
composition_diffusion
type(field_def), parameter m_diffusion_term_labels::composition_diffusion = field_def(n_comp = n_scalar, name = 'composition_diffusion', math = '$ \kappa_{C} \partial_{j}\partial_{j} C $')
Field label for compositional diffusion \(\kappa \partial_{i}\partial_{i} C \).
Definition at line 93 of file m_diffusion_term_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_diffusions(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_scalar_diffusion(), t_diffusion_term_labels::set_base_diffusion_addresses(), and set_base_diffusion_labels().
div_viscousity
type(field_def), parameter m_diffusion_term_labels::div_viscousity = field_def(n_comp = n_scalar, name = 'div_viscousity', math = '$ \nu \partial_{i}' // ' \partial_{j}\partial_{j} u_{i} $')
Field label for divergence of viscousity \(\nu \partial_{i} \partial_{j}\partial_{j} u_{i} \).
Definition at line 101 of file m_diffusion_term_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_diffusions(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_scalar_diffusion(), t_diffusion_term_labels::set_base_diffusion_addresses(), and set_base_diffusion_labels().
kinetic_viscosity
type(field_def), parameter m_diffusion_term_labels::kinetic_viscosity = field_def(n_comp = n_vector, name = 'kinetic_viscosity', math = '$ \nu = \mu / \bar{\rho} $')
Field label for kinetic viscosity \(\nu = \mu / \bar{\rho} \).
Definition at line 111 of file m_diffusion_term_labels.f90.
Referenced by check_diffusivity(), set_base_diffusivity_labels(), and t_diffusion_term_labels::set_diffusivity_addresses().
magnetic_diffusion
type(field_def), parameter m_diffusion_term_labels::magnetic_diffusion = field_def(n_comp = n_vector, name = 'magnetic_diffusion', math = '$ \eta \partial_{j}\partial_{j} B_{i} $')
Field label for magnetic diffusion \(\nu \partial_{j}\partial_{j} B_{i} \).
Definition at line 81 of file m_diffusion_term_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_diffusions(), check_energy_fluxes::add_field_ctl_4_ene_flux(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_vector_diffusion(), t_diffusion_term_labels::set_base_diffusion_addresses(), and set_base_diffusion_labels().
magnetic_diffusivity
type(field_def), parameter m_diffusion_term_labels::magnetic_diffusivity = field_def(n_comp = n_vector, name = 'magnetic_diffusivity', math = '$ \eta $')
Field label for magnetic diffusivity \(\eta \).
Definition at line 117 of file m_diffusion_term_labels.f90.
Referenced by check_diffusivity(), set_base_diffusivity_labels(), and t_diffusion_term_labels::set_diffusivity_addresses().
ndiffusion
integer(kind = kint), parameter, private m_diffusion_term_labels::ndiffusion = 7 private
Numbder of diffusion terms.
Definition at line 54 of file m_diffusion_term_labels.f90.
Referenced by num_base_diffusions().
ndiffusivities
integer(kind = kint), parameter, private m_diffusion_term_labels::ndiffusivities = 7 private
Numbder of diffusivities.
Definition at line 56 of file m_diffusion_term_labels.f90.
Referenced by num_base_diffusivities().
thermal_conductivity
type(field_def), parameter m_diffusion_term_labels::thermal_conductivity = field_def(n_comp = n_vector, name = 'thermal_conductivity', math = '$ k_{T} $')
Field label for thermal diffusivity \(k_{T} \).
Definition at line 140 of file m_diffusion_term_labels.f90.
Referenced by check_diffusivity(), set_base_diffusivity_labels(), and t_diffusion_term_labels::set_diffusivity_addresses().
thermal_diffusion
type(field_def), parameter m_diffusion_term_labels::thermal_diffusion = field_def(n_comp = n_scalar, name = 'thermal_diffusion', math = '$ \kappa_{T} \partial_{j}\partial_{j} T $')
Field label for thermal diffusion \(\kappa \partial_{i}\partial_{i} T \).
Definition at line 87 of file m_diffusion_term_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_diffusions(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_scalar_diffusion(), t_diffusion_term_labels::set_base_diffusion_addresses(), and set_base_diffusion_labels().
thermal_diffusivity
type(field_def), parameter m_diffusion_term_labels::thermal_diffusivity = field_def(n_comp = n_vector, name = 'thermal_diffusivity', math = '$ \kappa_{T} = k / \bar{\rho} $')
Field label for thermal diffusivity \(\kappa_{T} = k / \bar{\rho} \).
Definition at line 124 of file m_diffusion_term_labels.f90.
Referenced by check_diffusivity(), set_base_diffusivity_labels(), and t_diffusion_term_labels::set_diffusivity_addresses().
vector_potential_diffusion
type(field_def), parameter m_diffusion_term_labels::vector_potential_diffusion = field_def(n_comp = n_vector, name = 'vector_potential_diffusion', math = '$ -J_{i}' // ' = \eta \partial_{j}\partial_{j} A_{i} $')
Field label for diffusion of vetor potential \(-J_{i} = \eta \partial_{j}\partial_{j} A_{i} \).
Definition at line 74 of file m_diffusion_term_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_diffusions(), check_vector_diffusion(), t_diffusion_term_labels::set_base_diffusion_addresses(), and set_base_diffusion_labels().
viscosity
type(field_def), parameter m_diffusion_term_labels::viscosity = field_def(n_comp = n_vector, name = 'viscosity', math = '$ \mu $')
Field label for viscosity \(\mu \).
Definition at line 135 of file m_diffusion_term_labels.f90.
Referenced by check_diffusivity(), set_base_diffusivity_labels(), and t_diffusion_term_labels::set_diffusivity_addresses().
viscous_diffusion
type(field_def), parameter m_diffusion_term_labels::viscous_diffusion = field_def(n_comp = n_vector, name = 'viscous_diffusion', math = '$ \nu \partial_{j}\partial_{j} u_{i} $')
Field label for viscous diffusion \(\nu \partial_{j}\partial_{j} u_{i} \).
Definition at line 61 of file m_diffusion_term_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_diffusions(), check_energy_fluxes::add_field_ctl_4_ene_flux(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_vector_diffusion(), t_diffusion_term_labels::set_base_diffusion_addresses(), and set_base_diffusion_labels().
vorticity_diffusion
type(field_def), parameter m_diffusion_term_labels::vorticity_diffusion = field_def(n_comp = n_vector, name = 'vorticity_diffusion', math = '$ \nu \partial_{j}\partial_{j}' // ' \omega_{i} $')
Field label for diffusion of vorticity \(\nu \partial_{j}\partial_{j} \omega_{i} \).
Definition at line 67 of file m_diffusion_term_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_diffusions(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_vector_diffusion(), t_diffusion_term_labels::set_base_diffusion_addresses(), and set_base_diffusion_labels().