CALYPSO: field_at_mid_equator Module Reference
field_at_mid_equator Module Reference
data at mid-depth of the shell at equator for dynamo benchmark
Functions/Subroutines
subroutine set_mid_equator_point_global (trans_p, sph_params, sph_rtp, sph_rj, cdat)
subroutine cal_drift_by_v44 (time, circle, ibench_velo, t_prev, phase_vm4, phase_vm4_prev, omega_vm4)
subroutine cal_field_4_dynamobench (circle, d_circle, ibench_velo, phi_zero, phi_prev, d_zero)
Detailed Description
data at mid-depth of the shell at equator for dynamo benchmark
      subroutine set_mid_equator_point_global                         &
     &         (trans_p, sph_params, sph_rtp, sph_rj, cdat)
        type(parameters_4_sph_trans), intent(in) :: trans_p
        type(sph_shell_parameters), intent(in) :: sph_params
        type(sph_rj_grid), intent(in) :: sph_rj
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(phys_data), intent(in) :: rj_fld
        type(circle_fld_maker), intent(inout) :: cdat
      subroutine cal_drift_by_v44(time, circle, ibench_velo,          &
     &          t_prev, phase_vm4, phase_vm4_prev, omega_vm4)
      subroutine cal_field_4_dynamobench(circle, d_circle,            &
     &          ibench_velo, phi_zero, phi_prev, d_zero)
Function/Subroutine Documentation
cal_drift_by_v44()
subroutine field_at_mid_equator::cal_drift_by_v44 (real(kind=kreal), intent(in) time, type(fields_on_circle), intent(in) circle, integer(kind = kint), intent(in) ibench_velo, real(kind = kreal), intent(inout) t_prev, real(kind = kreal), dimension(2), intent(inout) phase_vm4, real(kind = kreal), dimension(2), intent(inout) phase_vm4_prev, real(kind = kreal), dimension(2), intent(inout) omega_vm4)
Definition at line 72 of file field_at_mid_equator.f90.
References m_constants::ifive, m_constants::ifour, and m_constants::quad.
Referenced by const_data_4_dynamobench::mid_eq_transfer_dynamobench().
cal_field_4_dynamobench()
subroutine field_at_mid_equator::cal_field_4_dynamobench (type(fields_on_circle), intent(in) circle, type(phys_data), intent(in) d_circle, integer(kind = kint), intent(in) ibench_velo, real(kind = kreal), dimension(4), intent(inout) phi_zero, real(kind = kreal), dimension(4), intent(inout) phi_prev, real(kind = kreal), dimension(0:4,7), intent(inout) d_zero)
Definition at line 116 of file field_at_mid_equator.f90.
References m_constants::four, m_constants::one, m_constants::quad, m_constants::two, and m_constants::zero.
Referenced by const_data_4_dynamobench::mid_eq_transfer_dynamobench().
set_mid_equator_point_global()
subroutine field_at_mid_equator::set_mid_equator_point_global (type(parameters_4_sph_trans), intent(in) trans_p, type(sph_shell_parameters), intent(in) sph_params, type(sph_rtp_grid), intent(in) sph_rtp, type(sph_rj_grid), intent(in) sph_rj, type(circle_fld_maker), intent(inout) cdat)
Definition at line 43 of file field_at_mid_equator.f90.
References t_field_on_circle::const_circle_point_global(), m_constants::half, and m_constants::zero.
Referenced by sph_analyzer_d_bench::sph_init_sph_dbench().