CALYPSO: gz_groups_io_b Module Reference
gz_groups_io_b Module Reference
Binary output routines for group data.
Functions/Subroutines
subroutine gz_read_group_data_b (zbuf, group_IO)
subroutine gz_read_surf_grp_data_b (zbuf, surf_grp_IO)
subroutine gz_write_grp_data_b (group_IO, zbuf)
subroutine gz_write_surf_grp_data_b (surf_grp_IO, zbuf)
Detailed Description
Binary output routines for group data.
      subroutine gz_read_group_data_b(zbuf, group_IO)
      subroutine gz_read_surf_grp_data_b(zbuf, surf_grp_IO)
        type(buffer_4_gzip), intent(inout) :: zbuf
        type(group_data), intent(inout) :: group_IO
        type(surface_group_data), intent(inout) :: surf_grp_IO
      subroutine gz_write_grp_data_b(group_IO, zbuf)
      subroutine gz_write_surf_grp_data_b(surf_grp_IO, zbuf)
        type(group_data), intent(in) :: group_IO
        type(surface_group_data), intent(in) :: surf_grp_IO
        type(buffer_4_gzip), intent(inout) :: zbuf
Function/Subroutine Documentation
gz_read_group_data_b()
subroutine gz_groups_io_b::gz_read_group_data_b (type(buffer_4_gzip), intent(inout) zbuf, type(group_data), intent(inout) group_IO)
Definition at line 43 of file gz_groups_IO_b.f90.
References t_group_data::alloc_group_item(), t_group_data::alloc_group_num(), transfer_to_long_integers::cast_long(), gz_binary_io::gz_read_integer_stack_b(), gz_binary_io::gz_read_mul_character_b(), gz_binary_io::gz_read_mul_integer_b(), and gz_binary_io::gz_read_one_integer_b().
Referenced by gz_sph_modes_data_io_b::gz_read_geom_rtp_data_b(), gz_mesh_data_io_b::gz_read_mesh_groups_b(), and gz_sph_modes_data_io_b::gz_read_spectr_modes_rj_data_b().
gz_read_surf_grp_data_b()
subroutine gz_groups_io_b::gz_read_surf_grp_data_b (type(buffer_4_gzip), intent(inout) zbuf, type(surface_group_data), intent(inout) surf_grp_IO)
Definition at line 78 of file gz_groups_IO_b.f90.
References t_group_data::alloc_sf_group_item(), t_group_data::alloc_sf_group_num(), transfer_to_long_integers::cast_long(), gz_binary_io::gz_read_integer_stack_b(), gz_binary_io::gz_read_mul_character_b(), gz_binary_io::gz_read_mul_integer_b(), and gz_binary_io::gz_read_one_integer_b().
Referenced by gz_mesh_data_io_b::gz_read_mesh_groups_b().
gz_write_grp_data_b()
subroutine gz_groups_io_b::gz_write_grp_data_b (type(group_data), intent(in) group_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 116 of file gz_groups_IO_b.f90.
References transfer_to_long_integers::cast_long(), gz_binary_io::gz_write_integer_stack_b(), gz_binary_io::gz_write_mul_character_b(), gz_binary_io::gz_write_mul_integer_b(), and gz_binary_io::gz_write_one_integer_b().
Referenced by gz_sph_modes_data_io_b::gz_write_geom_rtp_data_b(), gz_mesh_data_io_b::gz_write_mesh_groups_b(), and gz_sph_modes_data_io_b::gz_write_spectr_modes_rj_data_b().
gz_write_surf_grp_data_b()
subroutine gz_groups_io_b::gz_write_surf_grp_data_b (type(surface_group_data), intent(in) surf_grp_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 139 of file gz_groups_IO_b.f90.
References transfer_to_long_integers::cast_long(), gz_binary_io::gz_write_integer_stack_b(), gz_binary_io::gz_write_mul_character_b(), gz_binary_io::gz_write_mul_integer_b(), and gz_binary_io::gz_write_one_integer_b().
Referenced by gz_mesh_data_io_b::gz_write_mesh_groups_b().