CALYPSO: legendre_trans_sym_matmul Module Reference
legendre_trans_sym_matmul Module Reference
Legendre transforms (longest loop version)
Functions/Subroutines
subroutine leg_backward_trans_sym_matmul (iflag_matmul, ncomp, nvector, nscalar, sph_rlm, sph_rtm, comm_rlm, comm_rtm, leg, idx_trns, n_WR, n_WS, WR, WS, WK_l_sml)
subroutine leg_forward_trans_sym_matmul (iflag_matmul, ncomp, nvector, nscalar, sph_rtm, sph_rlm, comm_rtm, comm_rlm, leg, idx_trns, n_WR, n_WS, WR, WS, WK_l_sml)
Detailed Description
Legendre transforms (longest loop version)
      subroutine leg_backward_trans_sym_matmul                        &
     &         (iflag_matmul, ncomp, nvector, nscalar,                &
     &          sph_rlm, sph_rtm, comm_rlm, comm_rtm, leg, idx_trns,  &
     &          n_WR, n_WS, WR, WS, WK_l_sml)
        Input:  sp_rlm   (Order: poloidal,diff_poloidal,toroidal)
        Output: vr_rtm   (Order: radius,theta,phi)
        type(sph_rlm_grid), intent(in) :: sph_rlm
        type(sph_rtm_grid), intent(in) :: sph_rtm
        type(sph_comm_tbl), intent(in) :: comm_rlm, comm_rtm
        type(legendre_4_sph_trans), intent(in) :: leg
        type(index_4_sph_trans), intent(in) :: idx_trns
    Forward transforms
      subroutine leg_forward_trans_sym_matmul                         &
     &         (iflag_matmul, ncomp, nvector, nscalar,                &
     &          sph_rtm, sph_rlm, comm_rtm, comm_rlm, leg, idx_trns,  &
     &          n_WR, n_WS, WR, WS, WK_l_sml)
        Input:  vr_rtm   (Order: radius,theta,phi)
        Output: sp_rlm   (Order: poloidal,diff_poloidal,toroidal)
        type(sph_rtm_grid), intent(in) :: sph_rtm
        type(sph_rlm_grid), intent(in) :: sph_rlm
        type(sph_comm_tbl), intent(in) :: comm_rtm, comm_rlm
        type(legendre_4_sph_trans), intent(in) :: leg
        type(index_4_sph_trans), intent(in) :: idx_trns
Parameters
ncomp Total number of components for spherical transform
nvector Number of vector for spherical transform
nscalar Number of scalar (including tensor components) for spherical transform
Function/Subroutine Documentation
leg_backward_trans_sym_matmul()
subroutine legendre_trans_sym_matmul::leg_backward_trans_sym_matmul (integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_comm_tbl), intent(in) comm_rlm, type(sph_comm_tbl), intent(in) comm_rtm, type(legendre_4_sph_trans), intent(in) leg, type(index_4_sph_trans), intent(in) idx_trns, integer(kind = kint), intent(in) n_WR, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_wr), intent(inout) WR, real (kind=kreal), dimension(n_ws), intent(inout) WS, type(leg_trns_sym_mul_work), intent(inout) WK_l_sml)
Definition at line 65 of file legendre_trans_sym_matmul.f90.
References legendre_bwd_sym_matmul::leg_b_trans_scl_sym_matmul(), and legendre_bwd_sym_matmul::leg_b_trans_vec_sym_matmul().
Referenced by t_legendre_trans_select::sel_backward_legendre_trans().
leg_forward_trans_sym_matmul()
subroutine legendre_trans_sym_matmul::leg_forward_trans_sym_matmul (integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_comm_tbl), intent(in) comm_rtm, type(sph_comm_tbl), intent(in) comm_rlm, type(legendre_4_sph_trans), intent(in) leg, type(index_4_sph_trans), intent(in) idx_trns, integer(kind = kint), intent(in) n_WR, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_wr), intent(inout) WR, real (kind=kreal), dimension(n_ws), intent(inout) WS, type(leg_trns_sym_mul_work), intent(inout) WK_l_sml)
Definition at line 98 of file legendre_trans_sym_matmul.f90.
References legendre_fwd_sym_matmul::leg_f_trans_scl_sym_matmul(), and legendre_fwd_sym_matmul::leg_f_trans_vec_sym_matmul().
Referenced by t_legendre_trans_select::sel_forward_legendre_trans().