CALYPSO: m_force_control_labels Module Reference
m_force_control_labels Module Reference
Functions/Subroutines
integer(kind=kint) function num_advection_controls ()
integer(kind=kint) function num_force_controls ()
subroutine set_advection_control_labels (n_comps, names, maths)
subroutine set_force_control_labels (n_comps, names, maths)
Variables
integer(kind=kint), parameter, private nadvect_label = 4
integer(kind=kint), parameter, private nforce_label = 4
character(len=kchara), parameter induction_1 = 'induction'
Term label for induction term.
character(len=kchara), parameter heat_flux_1 = 'heat'
Term label for heat equation.
character(len=kchara), parameter comp_flux_1 = 'comp_flux'
Term label for cpmpositional flux term.
character(len=kchara), parameter coriolis_e1 = 'Coriolis'
Coriolis force label.
character(len=kchara), parameter coriolis_n1 = 'Coriolis_node'
character(len=kchara), parameter coriolis_i1 = 'Coriolis_imp'
character(len=kchara), parameter lorentz_label = 'Lorentz'
Lorentz force label.
character(len=kchara), parameter gravity_label = 'Thermal_buoyancy'
Thermal buoyancy label.
character(len=kchara), parameter gravity_e1 = 'gravity'
character(len=kchara), parameter gravity_e2 = 'buoyancy'
character(len=kchara), parameter gravity_e5 = 'Thermal_gravity'
character(len=kchara), parameter comp_gravity_label = 'Compositional_buoyancy'
Compositional buoyancy label.
character(len=kchara), parameter comp_gravity_e1 = 'Compositional_gravity'
character(len=kchara), parameter comp_gravity_e5 = 'Composite_gravity'
character(len=kchara), parameter comp_gravity_e6 = 'Composite_buoyancy'
Function/Subroutine Documentation
num_advection_controls()
integer(kind = kint) function m_force_control_labels::num_advection_controls
Definition at line 92 of file m_force_control_labels.f90.
References nadvect_label.
num_force_controls()
integer(kind = kint) function m_force_control_labels::num_force_controls
Definition at line 99 of file m_force_control_labels.f90.
References nforce_label.
set_advection_control_labels()
subroutine m_force_control_labels::set_advection_control_labels (integer(kind = kint_4b), dimension(nadvect_label), intent(inout) n_comps, character(len = kchara), dimension(nadvect_label), intent(inout) names, character(len = kchara), dimension(nadvect_label), intent(inout) maths)
Definition at line 106 of file m_force_control_labels.f90.
References m_base_force_labels::composition_advect, m_base_force_labels::heat_advect, m_base_force_labels::inertia, and m_base_force_labels::magnetic_induction.
set_force_control_labels()
subroutine m_force_control_labels::set_force_control_labels (integer(kind = kint_4b), dimension(nforce_label), intent(inout) n_comps, character(len = kchara), dimension(nforce_label), intent(inout) names, character(len = kchara), dimension(nforce_label), intent(inout) maths)
Definition at line 129 of file m_force_control_labels.f90.
References m_base_force_labels::buoyancy, m_base_force_labels::composite_buoyancy, m_base_force_labels::coriolis_force, and m_base_force_labels::lorentz_force.
Variable Documentation
comp_flux_1
character(len=kchara), parameter m_force_control_labels::comp_flux_1 = 'comp_flux'
Term label for cpmpositional flux term.
Definition at line 55 of file m_force_control_labels.f90.
comp_gravity_e1
character(len=kchara), parameter m_force_control_labels::comp_gravity_e1 = 'Compositional_gravity'
Definition at line 79 of file m_force_control_labels.f90.
Referenced by set_control_4_force::set_control_force_flags().
comp_gravity_e5
character(len=kchara), parameter m_force_control_labels::comp_gravity_e5 = 'Composite_gravity'
Definition at line 81 of file m_force_control_labels.f90.
Referenced by set_control_4_force::set_control_force_flags().
comp_gravity_e6
character(len=kchara), parameter m_force_control_labels::comp_gravity_e6 = 'Composite_buoyancy'
Definition at line 83 of file m_force_control_labels.f90.
Referenced by set_control_4_force::set_control_force_flags().
comp_gravity_label
character(len=kchara), parameter m_force_control_labels::comp_gravity_label = 'Compositional_buoyancy'
Compositional buoyancy label.
Definition at line 76 of file m_force_control_labels.f90.
Referenced by set_control_4_force::set_control_force_flags().
coriolis_e1
character(len=kchara), parameter m_force_control_labels::coriolis_e1 = 'Coriolis'
Coriolis force label.
Definition at line 58 of file m_force_control_labels.f90.
coriolis_i1
character(len=kchara), parameter m_force_control_labels::coriolis_i1 = 'Coriolis_imp'
Definition at line 60 of file m_force_control_labels.f90.
coriolis_n1
character(len=kchara), parameter m_force_control_labels::coriolis_n1 = 'Coriolis_node'
Definition at line 59 of file m_force_control_labels.f90.
gravity_e1
character(len=kchara), parameter m_force_control_labels::gravity_e1 = 'gravity'
Definition at line 69 of file m_force_control_labels.f90.
Referenced by set_control_4_force::set_control_force_flags().
gravity_e2
character(len=kchara), parameter m_force_control_labels::gravity_e2 = 'buoyancy'
Definition at line 70 of file m_force_control_labels.f90.
Referenced by set_control_4_force::set_control_force_flags().
gravity_e5
character(len=kchara), parameter m_force_control_labels::gravity_e5 = 'Thermal_gravity'
Definition at line 71 of file m_force_control_labels.f90.
Referenced by set_control_4_force::set_control_force_flags().
gravity_label
character(len=kchara), parameter m_force_control_labels::gravity_label = 'Thermal_buoyancy'
Thermal buoyancy label.
Definition at line 66 of file m_force_control_labels.f90.
Referenced by set_control_4_force::set_control_force_flags().
heat_flux_1
character(len=kchara), parameter m_force_control_labels::heat_flux_1 = 'heat'
Term label for heat equation.
Definition at line 53 of file m_force_control_labels.f90.
induction_1
character(len=kchara), parameter m_force_control_labels::induction_1 = 'induction'
Term label for induction term.
Definition at line 51 of file m_force_control_labels.f90.
lorentz_label
character(len=kchara), parameter m_force_control_labels::lorentz_label = 'Lorentz'
Lorentz force label.
Definition at line 63 of file m_force_control_labels.f90.
Referenced by set_control_4_force::set_control_force_flags().
nadvect_label
integer(kind = kint), parameter, private m_force_control_labels::nadvect_label = 4 private
Definition at line 45 of file m_force_control_labels.f90.
Referenced by num_advection_controls().
nforce_label
integer(kind = kint), parameter, private m_force_control_labels::nforce_label = 4 private
Definition at line 46 of file m_force_control_labels.f90.
Referenced by num_force_controls().