CALYPSO: set_size_4_smp_types Module Reference
set_size_4_smp_types Module Reference
set numbers for SMP parallelization
Functions/Subroutines
subroutine count_size_4_smp_mesh_type (nod, ele)
subroutine count_node_4_smp_mesh_type (nod)
subroutine count_ele_4_smp_mesh_type (ele)
subroutine count_surf_size_smp_type (surf)
subroutine count_edge_size_smp_type (edge)
subroutine count_overlap_ele (nod, ele)
subroutine count_overlap_surf (nod, surf)
subroutine count_overlap_edge (nod, edge)
Detailed Description
set numbers for SMP parallelization
      subroutine count_size_4_smp_mesh_type(nod, ele)
        type(node_data),    intent(inout) :: nod
        type(element_data), intent(inout) :: ele
      subroutine count_node_4_smp_mesh_type(nod)
        type(node_data),    intent(inout) :: nod
      subroutine count_ele_4_smp_mesh_type(ele)
        type(element_data), intent(inout) :: ele
      subroutine count_surf_size_smp_type(surf)
        type(surface_data), intent(inout) :: surf
      subroutine count_edge_size_smp_type(edge)
        type(edge_data),    intent(inout) :: edge
      subroutine count_overlap_ele(nod, ele)
        type(node_data),    intent(in) :: nod
        type(element_data), intent(inout) :: ele
      subroutine count_overlap_surf(nod, surf)
        type(node_data),    intent(in) :: nod
        type(surface_data), intent(inout) :: surf
      subroutine count_overlap_edge(nod, edge)
        type(node_data),    intent(in) :: nod
        type(edge_data),    intent(inout) :: edge
Function/Subroutine Documentation
count_edge_size_smp_type()
subroutine set_size_4_smp_types::count_edge_size_smp_type (type(edge_data), intent(inout) edge)
Definition at line 118 of file set_size_4_smp_types.f90.
References t_edge_data::alloc_edge_param_smp(), cal_minmax_and_stacks::count_number_4_smp(), m_constants::ione, and m_machine_parameter::np_smp.
Referenced by set_surf_edge_mesh::set_edge_connectivity().
count_ele_4_smp_mesh_type()
subroutine set_size_4_smp_types::count_ele_4_smp_mesh_type (type(element_data), intent(inout) ele)
Definition at line 84 of file set_size_4_smp_types.f90.
References t_geometry_data::allocate_ele_param_smp_type(), cal_minmax_and_stacks::count_number_4_smp(), m_constants::ione, and m_machine_parameter::np_smp.
Referenced by count_size_4_smp_mesh_type().
count_node_4_smp_mesh_type()
subroutine set_size_4_smp_types::count_node_4_smp_mesh_type (type(node_data), intent(inout) nod)
Definition at line 64 of file set_size_4_smp_types.f90.
References t_geometry_data::allocate_node_param_smp_type(), cal_minmax_and_stacks::count_number_4_smp(), m_constants::ione, and m_machine_parameter::np_smp.
Referenced by count_size_4_smp_mesh_type().
count_overlap_edge()
subroutine set_size_4_smp_types::count_overlap_edge (type(node_data), intent(in) nod, type(edge_data), intent(inout) edge)
Definition at line 172 of file set_size_4_smp_types.f90.
References m_machine_parameter::np_smp, and count_overlap::set_overlap_flag().
Referenced by set_surf_edge_mesh::set_edge_connectivity().
count_overlap_ele()
subroutine set_size_4_smp_types::count_overlap_ele (type(node_data), intent(in) nod, type(element_data), intent(inout) ele)
Definition at line 136 of file set_size_4_smp_types.f90.
References m_machine_parameter::np_smp, and count_overlap::set_overlap_flag().
Referenced by const_mesh_information::set_nod_and_ele_infos().
count_overlap_surf()
subroutine set_size_4_smp_types::count_overlap_surf (type(node_data), intent(in) nod, type(surface_data), intent(inout) surf)
Definition at line 153 of file set_size_4_smp_types.f90.
References m_machine_parameter::np_smp, and count_overlap::set_overlap_flag().
Referenced by set_surf_edge_mesh::set_surf_connectivity().
count_size_4_smp_mesh_type()
subroutine set_size_4_smp_types::count_size_4_smp_mesh_type (type(node_data), intent(inout) nod, type(element_data), intent(inout) ele)
Definition at line 48 of file set_size_4_smp_types.f90.
References count_ele_4_smp_mesh_type(), and count_node_4_smp_mesh_type().
Referenced by const_mesh_information::set_nod_and_ele_infos().
count_surf_size_smp_type()
subroutine set_size_4_smp_types::count_surf_size_smp_type (type(surface_data), intent(inout) surf)
Definition at line 101 of file set_size_4_smp_types.f90.
References t_surface_data::allocate_surf_param_smp_type(), cal_minmax_and_stacks::count_number_4_smp(), m_constants::ione, and m_machine_parameter::np_smp.
Referenced by set_surf_edge_mesh::set_surf_connectivity().