CALYPSO: parallel_gen_sph_grids Module Reference
parallel_gen_sph_grids Module Reference
Main loop to generate spherical harmonics indices.
Functions/Subroutines
subroutine check_and_make_para_sph_mesh (sph_file_param, num_pe, sph_mesh, sph_maker)
subroutine, private para_gen_sph_grids (num_pe, sph_mesh, sph_maker)
subroutine check_and_make_para_rj_mode (sph_file_param, num_pe, sph_mesh, sph_maker)
subroutine, private para_gen_sph_rj_mode (num_pe, sph_mesh, sph_maker)
Detailed Description
Main loop to generate spherical harmonics indices.
      subroutine check_and_make_para_SPH_mesh                         &
     &         (sph_file_param, num_pe, sph_mesh, sph_maker)
      subroutine check_and_make_para_rj_mode                          &
     &         (sph_file_param, num_pe, sph_mesh, sph_maker)
        integer(kind = kint), intent(in) :: num_pe
        type(field_IO_params), intent(in) :: sph_file_param
        type(sph_grid_maker_in_sim), intent(inout) :: sph_maker
        type(sph_mesh_data), intent(inout) :: sph_mesh(num_pe)
Function/Subroutine Documentation
check_and_make_para_rj_mode()
subroutine parallel_gen_sph_grids::check_and_make_para_rj_mode (type(field_io_params), intent(in) sph_file_param, integer(kind = kint), intent(in) num_pe, type(sph_mesh_data), dimension(num_pe), intent(inout) sph_mesh, type(sph_grid_maker_in_sim), intent(inout) sph_maker)
Definition at line 127 of file parallel_gen_sph_grids.f90.
References calypso_mpi::calypso_mpi_abort(), calypso_mpi::calypso_mpi_barrier(), calypso_mpi_logical::calypso_mpi_bcast_one_logical(), sph_file_io_select::check_exsist_rj_file(), m_error_ids::ierr_file, m_machine_parameter::iflag_debug, m_constants::izero, output_gen_sph_grid_modes::load_local_rj_mesh_4_merge(), calypso_mpi::my_rank, para_gen_sph_rj_mode(), and output_gen_sph_grid_modes::para_output_sph_rj_modes().
Referenced by analyzer_assemble_sph::init_assemble_sph(), and analyzer_compare_sph_rst::init_compare_sph_restart().
check_and_make_para_sph_mesh()
subroutine parallel_gen_sph_grids::check_and_make_para_sph_mesh (type(field_io_params), intent(in) sph_file_param, integer(kind = kint), intent(in) num_pe, type(sph_mesh_data), dimension(num_pe), intent(inout) sph_mesh, type(sph_grid_maker_in_sim), intent(inout) sph_maker)
Definition at line 45 of file parallel_gen_sph_grids.f90.
References calypso_mpi::calypso_mpi_abort(), m_error_ids::ierr_file, m_machine_parameter::iflag_debug, calypso_mpi::my_rank, para_gen_sph_grids(), and output_gen_sph_grid_modes::para_output_sph_mode_grids().
para_gen_sph_grids()
subroutine, private parallel_gen_sph_grids::para_gen_sph_grids (integer(kind = kint), intent(in) num_pe, type(sph_mesh_data), dimension(num_pe), intent(inout) sph_mesh, type(sph_grid_maker_in_sim), intent(inout) sph_maker) private
Definition at line 88 of file parallel_gen_sph_grids.f90.
References mpi_gen_sph_grids_modes::const_sph_global_parameters(), copy_para_sph_global_params::copy_para_global_sph_resolution(), copy_para_sph_global_params::copy_para_sph_param_from_ctl(), t_const_spherical_grid::dealloc_gen_mesh_params(), m_machine_parameter::iflag_debug, t_parai_gen_sph_grids_modes::para_gen_sph_rlm_rj_modes(), and t_parai_gen_sph_grids_modes::para_gen_sph_rtm_rtp_grids().
Referenced by check_and_make_para_sph_mesh().
para_gen_sph_rj_mode()
subroutine, private parallel_gen_sph_grids::para_gen_sph_rj_mode (integer(kind = kint), intent(in) num_pe, type(sph_mesh_data), dimension(num_pe), intent(inout) sph_mesh, type(sph_grid_maker_in_sim), intent(inout) sph_maker) private
Definition at line 180 of file parallel_gen_sph_grids.f90.
References mpi_gen_sph_grids_modes::const_sph_global_parameters(), copy_para_sph_global_params::copy_para_global_sph_resolution(), copy_para_sph_global_params::copy_para_sph_param_from_ctl(), t_const_spherical_grid::dealloc_gen_mesh_params(), m_machine_parameter::iflag_debug, and t_parai_gen_sph_grids_modes::para_gen_sph_rlm_rj_modes().
Referenced by check_and_make_para_rj_mode().