CALYPSO: gz_mpi_groups_io Module Reference
gz_mpi_groups_io Module Reference
Binary output routines for group data.
Functions/Subroutines
subroutine gz_mpi_read_group_data (IO_param, group_IO)
subroutine gz_mpi_read_surf_grp_data (IO_param, surf_grp_IO)
subroutine gz_mpi_write_grp_data (IO_param, group_IO)
subroutine gz_mpi_write_surf_grp_data (IO_param, surf_grp_IO)
subroutine, private gz_mpi_read_surf_grp_item (IO_param, ncolumn, ntot, ist, num, int_dat)
subroutine, private gz_mpi_write_surf_grp_item (IO_param, ncolumn, ntot, ist, num, int_dat)
Detailed Description
Binary output routines for group data.
      subroutine gz_mpi_read_group_data(IO_param, group_IO)
      subroutine gz_mpi_read_surf_grp_data(IO_param, surf_grp_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(group_data), intent(inout) :: group_IO
        type(surface_group_data), intent(inout) :: surf_grp_IO
      subroutine gz_mpi_write_grp_data(IO_param, group_IO)
      subroutine gz_mpi_write_surf_grp_data(IO_param, surf_grp_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(group_data), intent(in) :: group_IO
        type(surface_group_data), intent(in) :: surf_grp_IO
Function/Subroutine Documentation
gz_mpi_read_group_data()
subroutine gz_mpi_groups_io::gz_mpi_read_group_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(group_data), intent(inout) group_IO)
Definition at line 47 of file gz_MPI_groups_IO.f90.
References t_group_data::alloc_group_item(), t_group_data::alloc_group_num(), gz_mpi_ascii_data_io::gz_mpi_read_charahead(), gz_mpi_domain_data_io::gz_mpi_read_comm_table(), gz_mpi_domain_data_io::gz_mpi_read_int_stack(), gz_mpi_ascii_data_io::gz_mpi_read_num_of_data(), and gz_field_data_mpi_io::gz_read_fld_1word_mpi().
Referenced by gz_mpi_sph_modes_data_io::gz_mpi_read_geom_rtp_data(), gz_mpi_mesh_data_io::gz_mpi_read_mesh_groups(), and gz_mpi_sph_modes_data_io::gz_mpi_read_spectr_rj_data().
gz_mpi_read_surf_grp_data()
subroutine gz_mpi_groups_io::gz_mpi_read_surf_grp_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(surface_group_data), intent(inout) surf_grp_IO)
Definition at line 89 of file gz_MPI_groups_IO.f90.
References t_group_data::alloc_sf_group_item(), t_group_data::alloc_sf_group_num(), gz_mpi_ascii_data_io::gz_mpi_read_charahead(), gz_mpi_domain_data_io::gz_mpi_read_int_stack(), gz_mpi_ascii_data_io::gz_mpi_read_num_of_data(), gz_mpi_read_surf_grp_item(), and gz_field_data_mpi_io::gz_read_fld_1word_mpi().
Referenced by gz_mpi_mesh_data_io::gz_mpi_read_mesh_groups().
gz_mpi_read_surf_grp_item()
subroutine, private gz_mpi_groups_io::gz_mpi_read_surf_grp_item (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) ncolumn, integer(kind=kint), intent(in) ntot, integer(kind=kint), intent(in) ist, integer(kind=kint), intent(in) num, integer(kind=kint), dimension(2,ntot), intent(inout) int_dat) private
Definition at line 189 of file gz_MPI_groups_IO.f90.
References gz_mpi_domain_data_io::gz_mpi_read_comm_table(), and gz_mpi_ascii_data_io::gz_mpi_read_num_of_data().
Referenced by gz_mpi_read_surf_grp_data().
gz_mpi_write_grp_data()
subroutine gz_mpi_groups_io::gz_mpi_write_grp_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(group_data), intent(in) group_IO)
Definition at line 130 of file gz_MPI_groups_IO.f90.
References gz_mpi_ascii_data_io::gz_mpi_write_charahead(), gz_mpi_domain_data_io::gz_mpi_write_comm_table(), and gz_mpi_domain_data_io::gz_mpi_write_int_stack().
Referenced by gz_mpi_sph_modes_data_io::gz_mpi_write_geom_rtp_data(), gz_mpi_mesh_data_io::gz_mpi_write_mesh_groups(), and gz_mpi_sph_modes_data_io::gz_mpi_write_spectr_rj_data().
gz_mpi_write_surf_grp_data()
subroutine gz_mpi_groups_io::gz_mpi_write_surf_grp_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(surface_group_data), intent(in) surf_grp_IO)
Definition at line 160 of file gz_MPI_groups_IO.f90.
References gz_mpi_ascii_data_io::gz_mpi_write_charahead(), gz_mpi_domain_data_io::gz_mpi_write_int_stack(), and gz_mpi_write_surf_grp_item().
Referenced by gz_mpi_mesh_data_io::gz_mpi_write_mesh_groups().
gz_mpi_write_surf_grp_item()
subroutine, private gz_mpi_groups_io::gz_mpi_write_surf_grp_item (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) ncolumn, integer(kind=kint), intent(in) ntot, integer(kind=kint), intent(in) ist, integer(kind=kint), intent(in) num, integer(kind=kint), dimension(2,ntot), intent(in) int_dat) private
Definition at line 216 of file gz_MPI_groups_IO.f90.
References gz_mpi_domain_data_io::gz_mpi_write_comm_table().
Referenced by gz_mpi_write_surf_grp_data().