CALYPSO: t_field_matrices_4_legendre Module Reference
t_field_matrices_4_legendre Module Reference
Work array for forward Legendre transform useing mat multi
data are strored communication buffer.
Data Types
type field_matrix_omp
type spectr_matrix_omp
Functions/Subroutines
subroutine count_size_of_field_mat_omp (np_smp, nri_rtm, istack_rtm_lt_smp, nvector, nscalar, lst_rtm, nle_rtm, nlo_rtm, Fmat)
subroutine alloc_field_mat_omp (np_smp, Fmat)
subroutine dealloc_field_mat_omp (np_smp, Fmat)
subroutine alloc_spectr_mat_omp (n_pol_e, n_tor_e, np_smp, Smat)
subroutine dealloc_spectr_mat_omp (np_smp, Smat)
Detailed Description
Work array for forward Legendre transform useing mat multi
data are strored communication buffer.
      subroutine count_size_of_field_mat_omp                          &
     &         (np_smp, nri_rtm, istack_rtm_lt_smp, nvector, nscalar, &
     &          lst_rtm, nle_rtm, nlo_rtm, Fmat)
      subroutine alloc_field_mat_omp(np_smp, Fmat)
      subroutine dealloc_field_mat_omp(np_smp, Fmat)
        type(field_matrix_omp), intent(inout) :: Fmat(np_smp)
      subroutine alloc_spectr_mat_omp                                 &
     &          (n_pol_e, n_tor_e, np_smp, Smat)
      subroutine dealloc_spectr_mat_omp(np_smp, Smat)
        type(spectr_matrix_omp), intent(inout) :: Smat(np_smp)
Parameters
ncomp Total number of components for spherical transform
nvector Number of vector for spherical transform
nscalar Number of scalar (including tensor components) for spherical transform
Function/Subroutine Documentation
alloc_field_mat_omp()
subroutine t_field_matrices_4_legendre::alloc_field_mat_omp (integer(kind = kint), intent(in) np_smp, type(field_matrix_omp), dimension(np_smp), intent(inout) Fmat)
Definition at line 192 of file t_field_matrices_4_legendre.f90.
Referenced by t_legendre_work_testlooop::init_legendre_sym_mat_both(), t_legendre_work_sym_mat_jt::init_legendre_sym_mat_jt(), t_legendre_work_on_the_fly::init_legendre_sym_mat_otfly(), and t_legendre_work_sym_mat_jt::init_legendre_sym_mat_tj().
alloc_spectr_mat_omp()
subroutine t_field_matrices_4_legendre::alloc_spectr_mat_omp (integer(kind = kint), intent(in) n_pol_e, integer(kind = kint), intent(in) n_tor_e, integer(kind = kint), intent(in) np_smp, type(spectr_matrix_omp), dimension(np_smp), intent(inout) Smat)
Definition at line 238 of file t_field_matrices_4_legendre.f90.
References m_machine_parameter::np_smp.
Referenced by t_legendre_work_testlooop::init_legendre_sym_mat_both(), t_legendre_work_sym_mat_jt::init_legendre_sym_mat_jt(), t_legendre_work_on_the_fly::init_legendre_sym_mat_otfly(), and t_legendre_work_sym_mat_jt::init_legendre_sym_mat_tj().
count_size_of_field_mat_omp()
subroutine t_field_matrices_4_legendre::count_size_of_field_mat_omp (integer(kind = kint), intent(in) np_smp, integer(kind = kint), intent(in) nri_rtm, integer(kind = kint), dimension(0:np_smp), intent(in) istack_rtm_lt_smp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, integer(kind = kint), dimension(np_smp), intent(inout) lst_rtm, integer(kind = kint), dimension(np_smp), intent(inout) nle_rtm, integer(kind = kint), dimension(np_smp), intent(inout) nlo_rtm, type(field_matrix_omp), dimension(np_smp), intent(inout) Fmat)
Definition at line 154 of file t_field_matrices_4_legendre.f90.
References m_machine_parameter::np_smp.
Referenced by t_legendre_work_sym_mat_jt::init_legendre_sym_mat_jt(), and t_legendre_work_sym_mat_jt::init_legendre_sym_mat_tj().
dealloc_field_mat_omp()
subroutine t_field_matrices_4_legendre::dealloc_field_mat_omp (integer(kind = kint), intent(in) np_smp, type(field_matrix_omp), dimension(np_smp), intent(inout) Fmat)
Definition at line 220 of file t_field_matrices_4_legendre.f90.
Referenced by t_legendre_work_testlooop::dealloc_leg_sym_mat_both(), t_legendre_work_sym_mat_jt::dealloc_leg_sym_mat_jt(), t_legendre_work_on_the_fly::dealloc_leg_sym_mat_otfly(), and t_legendre_work_sym_mat_jt::dealloc_leg_sym_mat_tj().
dealloc_spectr_mat_omp()
subroutine t_field_matrices_4_legendre::dealloc_spectr_mat_omp (integer(kind = kint), intent(in) np_smp, type(spectr_matrix_omp), dimension(np_smp), intent(inout) Smat)
Definition at line 269 of file t_field_matrices_4_legendre.f90.
Referenced by t_legendre_work_testlooop::dealloc_leg_sym_mat_both(), t_legendre_work_sym_mat_jt::dealloc_leg_sym_mat_jt(), t_legendre_work_on_the_fly::dealloc_leg_sym_mat_otfly(), and t_legendre_work_sym_mat_jt::dealloc_leg_sym_mat_tj().