CALYPSO: t_control_array_character Module Reference
t_control_array_character Module Reference
Data Types
type ctl_array_chara
Structure for character control array.
type read_character_item
structure of control character item
Functions/Subroutines
subroutine read_chara_ctl_type (c_buf, label, chara_item)
subroutine write_chara_ctl_type (id_file, level, maxlen, label, chara_item)
subroutine copy_chara_ctl (org_c1, new_c1)
subroutine alloc_control_array_chara (array_chara)
subroutine dealloc_control_array_chara (array_chara)
subroutine read_control_array_c1 (id_control, label, array_chara, c_buf)
subroutine write_control_array_c1 (id_control, level, label, array_chara)
subroutine append_control_array_c1 (read_c1, array_c1)
subroutine dup_control_array_c1 (org_c1, tgt_c1)
subroutine copy_control_array_c1 (num_copy, org_c1, tgt_c1)
subroutine append_control_item_c1 (read_c1, array_c1)
Function/Subroutine Documentation
alloc_control_array_chara()
subroutine t_control_array_character::alloc_control_array_chara (type(ctl_array_chara), intent(inout) array_chara)
Definition at line 129 of file t_control_array_character.f90.
Referenced by append_control_array_c1(), bcast_control_arrays::bcast_ctl_array_c1(), dup_control_array_c1(), and read_control_array_c1().
append_control_array_c1()
subroutine t_control_array_character::append_control_array_c1 (type(read_character_item), intent(inout) read_c1, type(ctl_array_chara), intent(inout) array_c1)
Definition at line 218 of file t_control_array_character.f90.
References alloc_control_array_chara(), append_control_item_c1(), copy_control_array_c1(), and dealloc_control_array_chara().
Referenced by read_control_array_c1().
append_control_item_c1()
subroutine t_control_array_character::append_control_item_c1 (type(read_character_item), intent(in) read_c1, type(ctl_array_chara), intent(inout) array_c1)
Definition at line 272 of file t_control_array_character.f90.
Referenced by append_control_array_c1().
copy_chara_ctl()
subroutine t_control_array_character::copy_chara_ctl (type(read_character_item), intent(in) org_c1, type(read_character_item), intent(inout) new_c1)
Definition at line 115 of file t_control_array_character.f90.
Referenced by t_ctl_data_sph_vol_spectr::copy_volume_spectr_control(), t_control_data_4_psf::dup_control_4_psf(), t_control_data_4_psf_def::dup_control_4_psf_def(), and t_control_data_4_fld_on_psf::dup_fld_on_psf_control().
copy_control_array_c1()
subroutine t_control_array_character::copy_control_array_c1 (integer(kind = kint), intent(in) num_copy, type(ctl_array_chara), intent(in) org_c1, type(ctl_array_chara), intent(inout) tgt_c1)
Definition at line 257 of file t_control_array_character.f90.
Referenced by append_control_array_c1(), and dup_control_array_c1().
dealloc_control_array_chara()
subroutine t_control_array_character::dealloc_control_array_chara (type(ctl_array_chara), intent(inout) array_chara)
Definition at line 140 of file t_control_array_character.f90.
Referenced by append_control_array_c1(), t_control_data_4_psf_def::dealloc_cont_dat_4_psf_def(), t_ctl_data_mhd_evolution::dealloc_ele_area_grp_ctl(), t_ctl_data_node_monitor::dealloc_monitor_data_ctl(), t_ctl_data_mhd_forces::dealloc_name_force_ctl(), t_ctl_data_4_fields::dealloc_phys_control(), and t_ctl_data_mhd_evolution::dealloc_t_evo_name_ctl().
dup_control_array_c1()
subroutine t_control_array_character::dup_control_array_c1 (type(ctl_array_chara), intent(in) org_c1, type(ctl_array_chara), intent(inout) tgt_c1)
Definition at line 243 of file t_control_array_character.f90.
References alloc_control_array_chara(), and copy_control_array_c1().
Referenced by t_control_data_4_psf_def::dup_control_4_psf_def().
read_chara_ctl_type()
subroutine t_control_array_character::read_chara_ctl_type (type(buffer_for_control), intent(in) c_buf, character(len=kchara), intent(in) label, type(read_character_item), intent(inout) chara_item)
Definition at line 74 of file t_control_array_character.f90.
References m_machine_parameter::iflag_debug.
Referenced by read_control_array_c1(), t_ctl_data_4_platforms::read_control_platforms(), t_ctl_data_4_sphere_model::read_control_shell_define(), t_ctl_data_4_divide_sphere::read_control_shell_domain(), t_ctl_data_4_time_steps::read_control_time_step_data(), t_ctl_data_mhd_forces::read_coriolis_ctl(), t_ctl_data_sph_vol_spectr::read_each_vol_spectr_ctl(), t_ctl_data_4_fem_mesh::read_fem_mesh_control(), t_control_data_4_fld_on_psf::read_fld_on_psf_control(), t_ctl_data_pick_sph_spectr::read_gauss_spectr_ctl(), t_ctl_data_mhd_forces::read_gravity_ctl(), t_ctl_data_sph_vol_spectr::read_layerd_spectr_ctl(), t_ctl_data_mhd_forces::read_magneto_ctl(), t_mid_equator_control::read_mid_eq_monitor_ctl(), t_ctl_data_pick_sph_spectr::read_pickup_spectr_ctl(), t_control_data_4_psf::read_psf_control_data(), t_ctl_data_temp_model::read_refcomp_ctl(), t_ctl_data_temp_model::read_reftemp_ctl(), t_ctl_data_mhd_evo_scheme::read_restart_ctl(), t_control_data_4_psf_def::read_section_def_control(), t_ctl_data_4_sph_monitor::read_sph_monitoring_ctl(), t_control_data_surfacings::read_surfacing_controls(), and t_ctl_data_mhd_evo_scheme::read_time_loop_ctl().
read_control_array_c1()
subroutine t_control_array_character::read_control_array_c1 (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) label, type(ctl_array_chara), intent(inout) array_chara, type(buffer_for_control), intent(inout) c_buf)
Definition at line 154 of file t_control_array_character.f90.
References alloc_control_array_chara(), append_control_array_c1(), t_read_control_elements::check_array_flag(), t_read_control_elements::check_end_array_flag(), t_read_control_elements::load_one_line_from_control(), and read_chara_ctl_type().
Referenced by t_ctl_data_mhd_forces::read_forces_ctl(), t_ctl_data_mhd_evolution::read_mhd_layer_ctl(), t_ctl_data_mhd_evolution::read_mhd_time_evo_ctl(), t_ctl_data_node_monitor::read_monitor_data_ctl(), t_ctl_data_4_fields::read_phys_data_control(), and t_control_data_4_psf_def::read_section_def_control().
write_chara_ctl_type()
subroutine t_control_array_character::write_chara_ctl_type (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, integer(kind = kint), intent(in) maxlen, character(len=kchara), intent(in) label, type(read_character_item), intent(in) chara_item)
Definition at line 96 of file t_control_array_character.f90.
References write_control_elements::write_character_ctl_item().
Referenced by t_ctl_data_4_platforms::write_control_platforms(), t_ctl_data_4_divide_sphere::write_control_shell_domain(), t_ctl_data_4_time_steps::write_control_time_step_data(), and t_ctl_data_4_fem_mesh::write_fem_mesh_control().
write_control_array_c1()
subroutine t_control_array_character::write_control_array_c1 (integer(kind = kint), intent(in) id_control, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, type(ctl_array_chara), intent(in) array_chara)
Definition at line 188 of file t_control_array_character.f90.
References write_control_elements::write_array_flag_for_ctl(), write_control_elements::write_character_ctl_item(), and write_control_elements::write_end_array_flag_for_ctl().
Referenced by t_ctl_data_4_fields::write_phys_data_control().