CALYPSO: zlib_cvt_ascii_comm_tbl Module Reference
zlib_cvt_ascii_comm_tbl Module Reference
Routine for gzipped binary doimain data IO.
Functions/Subroutines
subroutine defleate_comm_table (ncolumn, num, int_dat, zbuf)
subroutine infleate_comm_table (ncolumn, num, int_dat, zbuf)
subroutine defleate_element_type (ncolumn, num, int_dat, zbuf)
subroutine infleate_element_type (ncolumn, num, int_dat, zbuf)
Detailed Description
Routine for gzipped binary doimain data IO.
      subroutine defleate_comm_table(ncolumn, num, int_dat, zbuf)
      subroutine infleate_comm_table(ncolumn, num, int_dat, zbuf)
        type(buffer_4_gzip), intent(inout) :: zbuf
      subroutine defleate_element_type(ncolumn, num, int_dat, zbuf)
      subroutine infleate_element_type(ncolumn, num, int_dat, zbuf)
        type(buffer_4_gzip), intent(inout) :: zbuf
Function/Subroutine Documentation
defleate_comm_table()
subroutine zlib_cvt_ascii_comm_tbl::defleate_comm_table (integer(kind = kint), intent(in) ncolumn, integer(kind = kint_gl), intent(in) num, integer(kind = kint), dimension(num), intent(in) int_dat, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 35 of file zlib_cvt_ascii_comm_tbl.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), gzip_defleate::gzip_defleat_char_begin(), gzip_defleate::gzip_defleat_char_cont(), gzip_defleate::gzip_defleat_char_last(), gzip_defleate::gzip_defleat_char_once(), m_constants::huge_30, m_constants::ione, data_io_to_textline::len_int_txt, data_io_to_textline::len_multi_int_textline(), and data_io_to_textline::multi_int_textline().
Referenced by gz_mpi_domain_data_io::gz_mpi_write_comm_table(), and gz_mpi_viewer_mesh_io::gz_mpi_write_viewer_grp_item().
defleate_element_type()
subroutine zlib_cvt_ascii_comm_tbl::defleate_element_type (integer(kind = kint), intent(in) ncolumn, integer(kind = kint_gl), intent(in) num, integer(kind = kint), dimension(num), intent(in) int_dat, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 189 of file zlib_cvt_ascii_comm_tbl.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), gzip_defleate::gzip_defleat_char_begin(), gzip_defleate::gzip_defleat_char_cont(), gzip_defleate::gzip_defleat_char_last(), gzip_defleate::gzip_defleat_char_once(), m_constants::huge_30, m_constants::ione, data_io_to_textline::len_6digit_txt, data_io_to_textline::len_multi_6digit_line(), and data_io_to_textline::mul_6digit_int_line().
Referenced by gz_mpi_integer_list_io::gz_mpi_write_element_type().
infleate_comm_table()
subroutine zlib_cvt_ascii_comm_tbl::infleate_comm_table (integer(kind=kint), intent(in) ncolumn, integer(kind = kint_gl), intent(in) num, integer(kind=kint), dimension(num), intent(inout) int_dat, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 109 of file zlib_cvt_ascii_comm_tbl.f90.
References t_buffer_4_gzip::alloc_textbuffer_for_zlib(), t_buffer_4_gzip::dealloc_textbuffer_for_zlib(), t_buffer_4_gzip::dealloc_zip_buffer(), gzip_infleate::gzip_infleat_char_begin(), gzip_infleate::gzip_infleat_char_cont(), gzip_infleate::gzip_infleat_char_last(), gzip_infleate::gzip_infleat_char_once(), m_constants::huge_30, m_constants::ione, data_io_to_textline::len_multi_int_textline(), t_buffer_4_gzip::link_pointer_for_zlib_buffer(), data_io_to_textline::read_multi_int_textline(), and t_buffer_4_gzip::unlink_pointer_for_zlib_buffer().
Referenced by gz_mpi_domain_data_io::gz_mpi_read_comm_table().
infleate_element_type()
subroutine zlib_cvt_ascii_comm_tbl::infleate_element_type (integer(kind=kint), intent(in) ncolumn, integer(kind = kint_gl), intent(in) num, integer(kind = kint), dimension(num), intent(inout) int_dat, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 262 of file zlib_cvt_ascii_comm_tbl.f90.
References t_buffer_4_gzip::alloc_textbuffer_for_zlib(), t_buffer_4_gzip::dealloc_textbuffer_for_zlib(), t_buffer_4_gzip::dealloc_zip_buffer(), gzip_infleate::gzip_infleat_char_begin(), gzip_infleate::gzip_infleat_char_cont(), gzip_infleate::gzip_infleat_char_last(), gzip_infleate::gzip_infleat_char_once(), m_constants::huge_30, m_constants::ione, data_io_to_textline::len_multi_6digit_line(), t_buffer_4_gzip::link_pointer_for_zlib_buffer(), data_io_to_textline::read_mul_6digit_int_line(), and t_buffer_4_gzip::unlink_pointer_for_zlib_buffer().
Referenced by gz_mpi_integer_list_io::gz_mpi_read_element_type().