CALYPSO: gz_field_file_io_b Module Reference
gz_field_file_io_b Module Reference
Output merged binary field file using MPI-IO.
Functions/Subroutines
subroutine gz_write_step_fld_file_b (gzip_name, id_rank, t_IO, fld_IO)
subroutine gz_read_step_field_file_b (gzip_name, id_rank, t_IO, fld_IO)
subroutine gz_rd_alloc_st_fld_file_b (gzip_name, id_rank, t_IO, fld_IO)
subroutine gz_rd_alloc_st_fld_head_b (gzip_name, id_rank, t_IO, fld_IO)
Variables
type(buffer_4_gzip), private zbuf_fld
Detailed Description
Output merged binary field file using MPI-IO.
      subroutine gz_write_step_fld_file_b                             &
     &         (gzip_name, id_rank, t_IO, fld_IO)
        type(time_data), intent(in) :: t_IO
        type(field_IO), intent(in) :: fld_IO
      subroutine gz_read_step_field_file_b                            &
     &         (gzip_name, id_rank, t_IO, fld_IO)
      subroutine gz_rd_alloc_st_fld_file_b                            &
     &         (gzip_name, id_rank, t_IO, fld_IO)
        type(time_data), intent(inout) :: t_IO
        type(field_IO), intent(inout) :: fld_IO
      subroutine gz_rd_alloc_st_fld_head_b                            &
     &         (gzip_name, id_rank, t_IO, fld_IO)
        type(time_data), intent(inout) :: t_IO
        type(field_IO), intent(inout) :: fld_IO
Function/Subroutine Documentation
gz_rd_alloc_st_fld_file_b()
subroutine gz_field_file_io_b::gz_rd_alloc_st_fld_file_b (character(len=kchara), intent(in) gzip_name, integer, intent(in) id_rank, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO)
Definition at line 126 of file gz_field_file_IO_b.f90.
References t_field_data_io::alloc_phys_data_io(), t_field_data_io::alloc_phys_name_io(), t_field_data_io::cal_istack_phys_comp_io(), transfer_to_long_integers::cast_long(), gzip_file_access::close_gzfile_b(), gz_field_data_io_b::gz_read_field_data_b(), gz_binary_io::gz_read_mul_integer_b(), gz_field_data_io_b::gz_read_step_data_b(), m_machine_parameter::i_debug, gz_binary_io::open_rd_gzfile_b(), and zbuf_fld.
Referenced by field_io_select::sel_read_alloc_step_field_file().
gz_rd_alloc_st_fld_head_b()
subroutine gz_field_file_io_b::gz_rd_alloc_st_fld_head_b (character(len=kchara), intent(in) gzip_name, integer, intent(in) id_rank, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO)
Definition at line 174 of file gz_field_file_IO_b.f90.
References t_field_data_io::alloc_phys_name_io(), t_field_data_io::cal_istack_phys_comp_io(), transfer_to_long_integers::cast_long(), gzip_file_access::close_gzfile_b(), gz_binary_io::gz_read_mul_integer_b(), gz_field_data_io_b::gz_read_step_data_b(), m_machine_parameter::i_debug, gz_binary_io::open_rd_gzfile_b(), and zbuf_fld.
Referenced by field_io_select::sel_read_alloc_field_head().
gz_read_step_field_file_b()
subroutine gz_field_file_io_b::gz_read_step_field_file_b (character(len=kchara), intent(in) gzip_name, integer, intent(in) id_rank, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO)
Definition at line 82 of file gz_field_file_IO_b.f90.
References transfer_to_long_integers::cast_long(), gzip_file_access::close_gzfile_b(), gz_field_data_io_b::gz_read_field_data_b(), gz_binary_io::gz_read_mul_integer_b(), gz_field_data_io_b::gz_read_step_data_b(), m_machine_parameter::i_debug, gz_binary_io::open_rd_gzfile_b(), and zbuf_fld.
Referenced by field_io_select::sel_read_step_field_file().
gz_write_step_fld_file_b()
subroutine gz_field_file_io_b::gz_write_step_fld_file_b (character(len=kchara), intent(in) gzip_name, integer, intent(in) id_rank, type(time_data), intent(in) t_IO, type(field_io), intent(in) fld_IO)
Definition at line 52 of file gz_field_file_IO_b.f90.
References transfer_to_long_integers::cast_long(), gzip_file_access::close_gzfile_b(), gz_field_data_io_b::gz_write_field_data_b(), gz_field_data_io_b::gz_write_step_data_b(), m_machine_parameter::i_debug, gz_binary_io::open_wt_gzfile_b(), and zbuf_fld.
Referenced by field_io_select::sel_write_step_field_file().
Variable Documentation
zbuf_fld
type(buffer_4_gzip), private gz_field_file_io_b::zbuf_fld private
Definition at line 44 of file gz_field_file_IO_b.f90.
Referenced by gz_rd_alloc_st_fld_file_b(), gz_rd_alloc_st_fld_head_b(), gz_read_step_field_file_b(), and gz_write_step_fld_file_b().