CALYPSO: cal_inverse_small_matrix Module Reference
cal_inverse_small_matrix Module Reference
Functions/Subroutines
subroutine cal_det_22_matrix (a, det_a)
subroutine cal_det_33_matrix (a, det_a)
subroutine cal_det_44_matrix (a, det_a)
recursive subroutine cal_det_nn_matrix (nsize, a, det_a)
subroutine cal_inverse_22_matrix (a, a_inv, ierr)
subroutine cal_inverse_33_matrix (a, a_inv, ierr)
subroutine cal_inverse_44_matrix (a, a_inv, ierr)
subroutine cal_inverse_nn_matrix (nsize, a, a_inv, ierr)
Variables
real(kind=kreal), parameter, private eps = 1.0e-40
Function/Subroutine Documentation
cal_det_22_matrix()
subroutine cal_inverse_small_matrix::cal_det_22_matrix (real(kind= kreal), dimension(2,2), intent(in) a, real(kind= kreal), intent(inout) det_a)
Definition at line 45 of file cal_inverse_small_matrix.f90.
Referenced by cal_det_33_matrix(), cal_det_nn_matrix(), cal_inverse_22_matrix(), and cal_inverse_33_matrix().
cal_det_33_matrix()
subroutine cal_inverse_small_matrix::cal_det_33_matrix (real(kind= kreal), dimension(3,3), intent(in) a, real(kind= kreal), intent(inout) det_a)
Definition at line 57 of file cal_inverse_small_matrix.f90.
References cal_det_22_matrix().
Referenced by cal_det_44_matrix(), cal_inverse_33_matrix(), and cal_inverse_44_matrix().
cal_det_44_matrix()
subroutine cal_inverse_small_matrix::cal_det_44_matrix (real(kind= kreal), dimension(4,4), intent(in) a, real(kind= kreal), intent(inout) det_a)
Definition at line 84 of file cal_inverse_small_matrix.f90.
References cal_det_33_matrix().
Referenced by cal_inverse_44_matrix().
cal_det_nn_matrix()
recursive subroutine cal_inverse_small_matrix::cal_det_nn_matrix (integer(kind = kint), intent(in) nsize, real(kind= kreal), dimension(nsize,nsize), intent(in) a, real(kind= kreal), intent(inout) det_a)
Definition at line 113 of file cal_inverse_small_matrix.f90.
References cal_det_22_matrix().
Referenced by cal_inverse_nn_matrix().
cal_inverse_22_matrix()
subroutine cal_inverse_small_matrix::cal_inverse_22_matrix (real(kind= kreal), dimension(2,2), intent(in) a, real(kind= kreal), dimension(2,2), intent(inout) a_inv, integer(kind = kint), intent(inout) ierr)
Definition at line 149 of file cal_inverse_small_matrix.f90.
References cal_det_22_matrix(), and eps.
Referenced by cal_sph_exp_1st_diff_ele::cal_2nd_ele_r_fdm_coefs().
cal_inverse_33_matrix()
subroutine cal_inverse_small_matrix::cal_inverse_33_matrix (real(kind= kreal), dimension(3,3), intent(in) a, real(kind= kreal), dimension(3,3), intent(inout) a_inv, integer(kind = kint), intent(inout) ierr)
Definition at line 176 of file cal_inverse_small_matrix.f90.
References cal_det_22_matrix(), cal_det_33_matrix(), and eps.
Referenced by coef_fdm2_to_center::cal_2nd_center_fix_df_fdm(), coef_fdm2_to_center::cal_2nd_center_fixed_fdm(), coef_fdm2_to_center::cal_2nd_to_center_fixed_fdm(), coef_fdm2_free_cmb::cal_fdm2_cmb_free_vp(), coef_fdm2_free_cmb::cal_fdm2_cmb_free_vt(), cal_fdm_coefs_4_boundaries::cal_fdm2_coef_fix_df_cmb(), cal_fdm_coefs_4_boundaries::cal_fdm2_coef_fix_df_icb(), cal_fdm_coefs_4_boundaries::cal_fdm2_coef_fix_fld_cmb(), cal_fdm_coefs_4_boundaries::cal_fdm2_coef_fix_fld_icb(), coef_fdm2_free_icb::cal_fdm2_icb_free_vp(), coef_fdm2_free_icb::cal_fdm2_icb_free_vt(), and set_radius_func_noequi::nod_r_2nd_fdm_coef_noequi().
cal_inverse_44_matrix()
subroutine cal_inverse_small_matrix::cal_inverse_44_matrix (real(kind= kreal), dimension(4,4), intent(in) a, real(kind= kreal), dimension(4,4), intent(inout) a_inv, integer(kind = kint), intent(inout) ierr)
Definition at line 222 of file cal_inverse_small_matrix.f90.
References cal_det_33_matrix(), cal_det_44_matrix(), and eps.
cal_inverse_nn_matrix()
subroutine cal_inverse_small_matrix::cal_inverse_nn_matrix (integer(kind = kint), intent(in) nsize, real(kind= kreal), dimension(nsize,nsize), intent(in) a, real(kind= kreal), dimension(nsize,nsize), intent(inout) a_inv, integer(kind = kint), intent(inout) ierr)
Definition at line 268 of file cal_inverse_small_matrix.f90.
References cal_det_nn_matrix(), and eps.
Referenced by const_radial_4th_fdm_noequi::nod_r_4th_fdm_coef_noequi().
Variable Documentation
eps
real(kind = kreal), parameter, private cal_inverse_small_matrix::eps = 1.0e-40 private
Definition at line 37 of file cal_inverse_small_matrix.f90.
Referenced by cal_inverse_22_matrix(), cal_inverse_33_matrix(), cal_inverse_44_matrix(), and cal_inverse_nn_matrix().