CALYPSO: cal_vr_rtm_sym_mat_tsmp Module Reference
cal_vr_rtm_sym_mat_tsmp Module Reference
forward Legendre transform (Blocked loop version)
Functions/Subroutines
subroutine cal_vr_rtm_sym_mat_rin (nnod_rtm, nidx_rtm, istep_rtm, nidx_rlm, asin_theta_1d_rtm, mp_rlm, mn_rlm, lst_rtm, nle_rtm, nlo_rtm, symp_r, asmp_p, asmp_r, symp_p, ncomp_send, nvector, nscalar, irev_sr_rtm, n_WS, WS)
subroutine cal_vr_rtm_sym_mat_rout (nnod_rtm, nidx_rtm, istep_rtm, nidx_rlm, asin_theta_1d_rtm, mp_rlm, mn_rlm, lst_rtm, nle_rtm, nlo_rtm, symp_r, asmp_p, asmp_r, symp_p, ncomp_send, nvector, nscalar, irev_sr_rtm, n_WS, WS)
subroutine cal_vr_rtm_sym_mat_lt_rin (lp_rtm, nnod_rtm, nidx_rtm, istep_rtm, nidx_rlm, asin_theta_1d_rtm, mp_rlm, mn_rlm, symp_r, asmp_p, asmp_r, symp_p, ncomp_send, nvector, nscalar, irev_sr_rtm, n_WS, WS)
subroutine cal_vr_rtm_sym_mat_eq_rin (lp_rtm, nnod_rtm, nidx_rtm, istep_rtm, nidx_rlm, asin_theta_1d_rtm, mp_rlm, mn_rlm, symp_r, asmp_r, symp_p, ncomp_send, nvector, nscalar, irev_sr_rtm, n_WS, WS)
Variables
integer, external omp_get_max_threads
Detailed Description
forward Legendre transform (Blocked loop version)
      subroutine cal_vr_rtm_sym_mat_rin(nnod_rtm, nidx_rtm,           &
     &          istep_rtm, nidx_rlm, asin_theta_1d_rtm,               &
     &          mp_rlm, mn_rlm, lst_rtm, nle_rtm, nlo_rtm,            &
     &          symp_r, asmp_p, asmp_r, symp_p, ncomp_send,           &
     &          nvector, nscalar, irev_sr_rtm, n_WS, WS)
      subroutine cal_vr_rtm_sym_mat_rout(nnod_rtm, nidx_rtm,          &
     &          istep_rtm, nidx_rlm, asin_theta_1d_rtm,               &
     &          mp_rlm, mn_rlm, lst_rtm, nle_rtm, nlo_rtm,            &
     &          symp_r, asmp_p, asmp_r, symp_p, ncomp_send,           &
     &          nvector, nscalar, irev_sr_rtm, n_WS, WS)
Function/Subroutine Documentation
cal_vr_rtm_sym_mat_eq_rin()
subroutine cal_vr_rtm_sym_mat_tsmp::cal_vr_rtm_sym_mat_eq_rin (integer(kind = kint), intent(in) lp_rtm, integer(kind = kint), intent(in) nnod_rtm, integer(kind = kint), dimension(3), intent(in) nidx_rtm, integer(kind = kint), dimension(3), intent(in) istep_rtm, integer(kind = kint), dimension(2), intent(in) nidx_rlm, real(kind = kreal), dimension(nidx_rtm(2)), intent(in) asin_theta_1d_rtm, integer(kind = kint), intent(in) mp_rlm, integer(kind = kint), intent(in) mn_rlm, real(kind = kreal), dimension(3*nvector+nscalar,nidx_rlm(1)), intent(inout) symp_r, real(kind = kreal), dimension(3*nvector+nscalar,nidx_rlm(1)), intent(inout) asmp_r, real(kind = kreal), dimension(2*nvector,nidx_rlm(1)), intent(in) symp_p, integer(kind = kint), intent(in) ncomp_send, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, integer(kind = kint), dimension(nnod_rtm), intent(in) irev_sr_rtm, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 403 of file cal_vr_rtm_sym_mat_tsmp.f90.
Referenced by cal_vr_rtm_sym_mat_rin(), leg_bwd_trans_on_the_fly::leg_bwd_trans_at_equator(), and legendre_bwd_trans_testloop::leg_bwd_trans_at_equator().
cal_vr_rtm_sym_mat_lt_rin()
subroutine cal_vr_rtm_sym_mat_tsmp::cal_vr_rtm_sym_mat_lt_rin (integer(kind = kint), intent(in) lp_rtm, integer(kind = kint), intent(in) nnod_rtm, integer(kind = kint), dimension(3), intent(in) nidx_rtm, integer(kind = kint), dimension(3), intent(in) istep_rtm, integer(kind = kint), dimension(2), intent(in) nidx_rlm, real(kind = kreal), dimension(nidx_rtm(2)), intent(in) asin_theta_1d_rtm, integer(kind = kint), intent(in) mp_rlm, integer(kind = kint), intent(in) mn_rlm, real(kind = kreal), dimension(3*nvector+nscalar,nidx_rlm(1)), intent(inout) symp_r, real(kind = kreal), dimension(2*nvector,nidx_rlm(1)), intent(in) asmp_p, real(kind = kreal), dimension(3*nvector+nscalar,nidx_rlm(1)), intent(inout) asmp_r, real(kind = kreal), dimension(2*nvector,nidx_rlm(1)), intent(in) symp_p, integer(kind = kint), intent(in) ncomp_send, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, integer(kind = kint), dimension(nnod_rtm), intent(in) irev_sr_rtm, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 290 of file cal_vr_rtm_sym_mat_tsmp.f90.
Referenced by cal_vr_rtm_sym_mat_rin(), leg_bwd_trans_on_the_fly::leg_bwd_trans_1latitude(), and legendre_bwd_trans_testloop::leg_bwd_trans_1latitude().
cal_vr_rtm_sym_mat_rin()
subroutine cal_vr_rtm_sym_mat_tsmp::cal_vr_rtm_sym_mat_rin (integer(kind = kint), intent(in) nnod_rtm, integer(kind = kint), dimension(3), intent(in) nidx_rtm, integer(kind = kint), dimension(3), intent(in) istep_rtm, integer(kind = kint), dimension(2), intent(in) nidx_rlm, real(kind = kreal), dimension(nidx_rtm(2)), intent(in) asin_theta_1d_rtm, integer(kind = kint), intent(in) mp_rlm, integer(kind = kint), intent(in) mn_rlm, integer(kind = kint), intent(in) lst_rtm, integer(kind = kint), intent(in) nle_rtm, integer(kind = kint), intent(in) nlo_rtm, real(kind = kreal), dimension(3*nvector+nscalar,nidx_rlm(1),nle_rtm), intent(inout) symp_r, real(kind = kreal), dimension(2*nvector,nidx_rlm(1),nle_rtm), intent(in) asmp_p, real(kind = kreal), dimension(3*nvector+nscalar,nidx_rlm(1),nle_rtm), intent(inout) asmp_r, real(kind = kreal), dimension(2*nvector,nidx_rlm(1),nle_rtm), intent(in) symp_p, integer(kind = kint), intent(in) ncomp_send, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, integer(kind = kint), dimension(nnod_rtm), intent(in) irev_sr_rtm, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 41 of file cal_vr_rtm_sym_mat_tsmp.f90.
References cal_vr_rtm_sym_mat_eq_rin(), and cal_vr_rtm_sym_mat_lt_rin().
Referenced by leg_bwd_trans_sym_mat_jt::legendre_b_trans_sym_mat_jt().
cal_vr_rtm_sym_mat_rout()
subroutine cal_vr_rtm_sym_mat_tsmp::cal_vr_rtm_sym_mat_rout (integer(kind = kint), intent(in) nnod_rtm, integer(kind = kint), dimension(3), intent(in) nidx_rtm, integer(kind = kint), dimension(3), intent(in) istep_rtm, integer(kind = kint), dimension(2), intent(in) nidx_rlm, real(kind = kreal), dimension(nidx_rtm(2)), intent(in) asin_theta_1d_rtm, integer(kind = kint), intent(in) mp_rlm, integer(kind = kint), intent(in) mn_rlm, integer(kind = kint), intent(in) lst_rtm, integer(kind = kint), intent(in) nle_rtm, integer(kind = kint), intent(in) nlo_rtm, real(kind = kreal), dimension(nle_rtm,nidx_rlm(1),3*nvector+nscalar), intent(inout) symp_r, real(kind = kreal), dimension(nle_rtm,nidx_rlm(1),2*nvector), intent(in) asmp_p, real(kind = kreal), dimension(nle_rtm,nidx_rlm(1),3*nvector+nscalar), intent(inout) asmp_r, real(kind = kreal), dimension(nle_rtm,nidx_rlm(1),2*nvector), intent(in) symp_p, integer(kind = kint), intent(in) ncomp_send, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, integer(kind = kint), dimension(nnod_rtm), intent(in) irev_sr_rtm, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 97 of file cal_vr_rtm_sym_mat_tsmp.f90.
Referenced by leg_bwd_trans_sym_mat_tj::legendre_b_trans_sym_mat_tj().
Variable Documentation
omp_get_max_threads
integer, external cal_vr_rtm_sym_mat_tsmp::omp_get_max_threads
Definition at line 33 of file cal_vr_rtm_sym_mat_tsmp.f90.