CALYPSO: t_ctl_data_pick_sph_spectr Module Reference
t_ctl_data_pick_sph_spectr Module Reference
Data Types
type gauss_spectr_control
type pick_spectr_control
Structure for spectr data pickup.
Functions/Subroutines
subroutine dealloc_pick_spectr_control (pspec_ctl)
subroutine dealloc_gauss_spectr_control (g_pwr)
subroutine read_pickup_spectr_ctl (id_control, hd_block, iflag, pspec_ctl, c_buf)
subroutine read_gauss_spectr_ctl (id_control, hd_block, iflag, g_pwr, c_buf)
Variables
character(len=kchara), parameter, private hd_picked_mode_head = 'picked_sph_prefix'
character(len=kchara), parameter, private hd_pick_layer = 'pick_layer_ctl'
character(len=kchara), parameter, private hd_pick_sph_lm = 'pick_sph_spectr_ctl'
character(len=kchara), parameter, private hd_pick_sph_l = 'pick_sph_degree_ctl'
character(len=kchara), parameter, private hd_pick_sph_m = 'pick_sph_order_ctl'
character(len=kchara), parameter, private hd_gauss_coefs_head = 'gauss_coefs_prefix'
character(len=kchara), parameter, private hd_gauss_coefs_r = 'gauss_coefs_radius_ctl'
character(len=kchara), parameter, private hd_pick_gauss_lm = 'pick_gauss_coefs_ctl'
character(len=kchara), parameter, private hd_pick_gauss_l = 'pick_gauss_coef_degree_ctl'
character(len=kchara), parameter, private hd_pick_gauss_m = 'pick_gauss_coef_order_ctl'
Function/Subroutine Documentation
dealloc_gauss_spectr_control()
subroutine t_ctl_data_pick_sph_spectr::dealloc_gauss_spectr_control (type(gauss_spectr_control), intent(inout) g_pwr)
Definition at line 195 of file t_ctl_data_pick_sph_spectr.f90.
References t_control_array_integer2::dealloc_control_array_i2(), and t_control_array_integer::dealloc_control_array_int().
Referenced by t_ctl_data_4_sph_monitor::dealloc_sph_monitoring_ctl().
dealloc_pick_spectr_control()
subroutine t_ctl_data_pick_sph_spectr::dealloc_pick_spectr_control (type(pick_spectr_control), intent(inout) pspec_ctl)
Definition at line 179 of file t_ctl_data_pick_sph_spectr.f90.
References t_control_array_integer2::dealloc_control_array_i2(), and t_control_array_integer::dealloc_control_array_int().
Referenced by t_ctl_data_4_sph_monitor::dealloc_sph_monitoring_ctl().
read_gauss_spectr_ctl()
subroutine t_ctl_data_pick_sph_spectr::read_gauss_spectr_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, integer(kind = kint), intent(inout) iflag, type(gauss_spectr_control), intent(inout) g_pwr, type(buffer_for_control), intent(inout) c_buf)
Definition at line 249 of file t_ctl_data_pick_sph_spectr.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_gauss_coefs_head, hd_gauss_coefs_r, hd_pick_gauss_l, hd_pick_gauss_lm, hd_pick_gauss_m, t_read_control_elements::load_one_line_from_control(), t_control_array_character::read_chara_ctl_type(), t_control_array_integer::read_control_array_i1(), t_control_array_integer2::read_control_array_i2(), and t_control_array_real::read_real_ctl_type().
Referenced by t_ctl_data_4_sph_monitor::read_sph_monitoring_ctl().
read_pickup_spectr_ctl()
subroutine t_ctl_data_pick_sph_spectr::read_pickup_spectr_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, integer(kind = kint), intent(inout) iflag, type(pick_spectr_control), intent(inout) pspec_ctl, type(buffer_for_control), intent(inout) c_buf)
Definition at line 212 of file t_ctl_data_pick_sph_spectr.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_pick_layer, hd_pick_sph_l, hd_pick_sph_lm, hd_pick_sph_m, hd_picked_mode_head, t_read_control_elements::load_one_line_from_control(), t_control_array_character::read_chara_ctl_type(), t_control_array_integer::read_control_array_i1(), and t_control_array_integer2::read_control_array_i2().
Referenced by t_ctl_data_4_sph_monitor::read_sph_monitoring_ctl().
Variable Documentation
hd_gauss_coefs_head
character(len=kchara), parameter, private t_ctl_data_pick_sph_spectr::hd_gauss_coefs_head = 'gauss_coefs_prefix' private
Definition at line 156 of file t_ctl_data_pick_sph_spectr.f90.
Referenced by read_gauss_spectr_ctl().
hd_gauss_coefs_r
character(len=kchara), parameter, private t_ctl_data_pick_sph_spectr::hd_gauss_coefs_r = 'gauss_coefs_radius_ctl' private
Definition at line 158 of file t_ctl_data_pick_sph_spectr.f90.
Referenced by read_gauss_spectr_ctl().
hd_pick_gauss_l
character(len=kchara), parameter, private t_ctl_data_pick_sph_spectr::hd_pick_gauss_l = 'pick_gauss_coef_degree_ctl' private
Definition at line 162 of file t_ctl_data_pick_sph_spectr.f90.
Referenced by read_gauss_spectr_ctl().
hd_pick_gauss_lm
character(len=kchara), parameter, private t_ctl_data_pick_sph_spectr::hd_pick_gauss_lm = 'pick_gauss_coefs_ctl' private
Definition at line 160 of file t_ctl_data_pick_sph_spectr.f90.
Referenced by read_gauss_spectr_ctl().
hd_pick_gauss_m
character(len=kchara), parameter, private t_ctl_data_pick_sph_spectr::hd_pick_gauss_m = 'pick_gauss_coef_order_ctl' private
Definition at line 164 of file t_ctl_data_pick_sph_spectr.f90.
Referenced by read_gauss_spectr_ctl().
hd_pick_layer
character(len=kchara), parameter, private t_ctl_data_pick_sph_spectr::hd_pick_layer = 'pick_layer_ctl' private
Definition at line 146 of file t_ctl_data_pick_sph_spectr.f90.
Referenced by read_pickup_spectr_ctl().
hd_pick_sph_l
character(len=kchara), parameter, private t_ctl_data_pick_sph_spectr::hd_pick_sph_l = 'pick_sph_degree_ctl' private
Definition at line 151 of file t_ctl_data_pick_sph_spectr.f90.
Referenced by read_pickup_spectr_ctl().
hd_pick_sph_lm
character(len=kchara), parameter, private t_ctl_data_pick_sph_spectr::hd_pick_sph_lm = 'pick_sph_spectr_ctl' private
Definition at line 149 of file t_ctl_data_pick_sph_spectr.f90.
Referenced by read_pickup_spectr_ctl().
hd_pick_sph_m
character(len=kchara), parameter, private t_ctl_data_pick_sph_spectr::hd_pick_sph_m = 'pick_sph_order_ctl' private
Definition at line 153 of file t_ctl_data_pick_sph_spectr.f90.
Referenced by read_pickup_spectr_ctl().
hd_picked_mode_head
character(len=kchara), parameter, private t_ctl_data_pick_sph_spectr::hd_picked_mode_head = 'picked_sph_prefix' private
Definition at line 143 of file t_ctl_data_pick_sph_spectr.f90.
Referenced by read_pickup_spectr_ctl().