CALYPSO: set_mesh_file_names Module Reference
set_mesh_file_names Module Reference
Set file names for field data file.
Functions/Subroutines
character(len=kchara) function set_mesh_file_name (file_header, itype_file, id_rank)
character(len=kchara) function set_sph_rtp_file_name (file_header, itype_file, id_rank)
character(len=kchara) function set_sph_rtm_file_name (file_header, itype_file, id_rank)
character(len=kchara) function set_sph_rlm_file_name (file_header, itype_file, id_rank)
character(len=kchara) function set_sph_rj_file_name (file_header, itype_file, id_rank)
character(len=kchara) function set_ele_comm_file_name (file_header, itype_file, id_rank)
character(len=kchara) function set_surf_mesh_file_name (file_header, itype_file, id_rank)
character(len=kchara) function set_edge_mesh_file_name (file_header, itype_file, id_rank)
Detailed Description
Set file names for field data file.
      character(len=kchara) function                                  &
     &       set_mesh_file_name(file_header, itype_file, id_rank)
      character(len=kchara) function                                  &
     &       set_sph_rtp_file_name(file_header, itype_file, id_rank)
      character(len=kchara) function                                  &
     &       set_sph_rtm_file_name(file_header, itype_file, id_rank)
      character(len=kchara) function                                  &
     &       set_sph_rlm_file_name(file_header, itype_file, id_rank)
      character(len=kchara) function                                  &
     &       set_sph_rj_file_name(file_header, itype_file, id_rank)
      character(len=kchara) function                                  &
     &       set_ele_comm_file_name(file_header, itype_file, id_rank)
      character(len=kchara) function                                  &
     &       set_surf_mesh_file_name(file_header, itype_file, id_rank)
      character(len=kchara) function                                  &
     &       set_edge_mesh_file_name(file_header, itype_file, id_rank)
Function/Subroutine Documentation
set_edge_mesh_file_name()
character(len=kchara) function set_mesh_file_names::set_edge_mesh_file_name (character(len=kchara), intent(in) file_header, integer(kind=kint), intent(in) itype_file, integer, intent(in) id_rank)
Definition at line 299 of file set_mesh_file_names.f90.
References set_mesh_extensions::add_edb_extension(), and set_mesh_extensions::add_ged_extension().
Referenced by mesh_file_name_by_param::check_exist_edge_mesh(), element_mesh_mpi_io_select::sel_mpi_read_edge_mesh(), element_mesh_mpi_io_select::sel_mpi_write_edge_mesh_file(), element_mesh_io_select::sel_read_edge_mesh(), and element_mesh_io_select::sel_write_edge_mesh_file().
set_ele_comm_file_name()
character(len=kchara) function set_mesh_file_names::set_ele_comm_file_name (character(len=kchara), intent(in) file_header, integer(kind=kint), intent(in) itype_file, integer, intent(in) id_rank)
Definition at line 227 of file set_mesh_file_names.f90.
References set_mesh_extensions::add_elb_extension(), and set_mesh_extensions::add_gel_extension().
Referenced by mesh_file_name_by_param::check_exist_ele_mesh(), element_mesh_mpi_io_select::sel_mpi_read_ele_mesh(), element_mesh_mpi_io_select::sel_mpi_write_ele_mesh_file(), element_mesh_io_select::sel_read_ele_mesh(), and element_mesh_io_select::sel_write_ele_mesh_file().
set_mesh_file_name()
character(len=kchara) function set_mesh_file_names::set_mesh_file_name (character(len=kchara), intent(in) file_header, integer(kind=kint), intent(in) itype_file, integer, intent(in) id_rank)
Definition at line 46 of file set_mesh_file_names.f90.
References set_mesh_extensions::add_gfb_extension(), set_mesh_extensions::add_gfm_extension(), set_parallel_file_name::add_gzip_extension(), set_parallel_file_name::add_process_id(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, m_file_format_switch::iflag_single, and m_constants::iten.
Referenced by mesh_file_name_by_param::check_exist_mesh(), mesh_mpi_io_select::sel_mpi_read_geometry_size(), mesh_mpi_io_select::sel_mpi_read_mesh(), mesh_mpi_io_select::sel_mpi_read_mesh_geometry(), mesh_mpi_io_select::sel_mpi_read_node_size(), mesh_mpi_io_select::sel_mpi_write_mesh_file(), mesh_io_select::sel_read_geometry_size(), mesh_io_select::sel_read_mesh(), mesh_io_select::sel_read_mesh_geometry(), mesh_io_select::sel_read_node_size(), and mesh_io_select::sel_write_mesh_file().
set_sph_rj_file_name()
character(len=kchara) function set_mesh_file_names::set_sph_rj_file_name (character(len=kchara), intent(in) file_header, integer(kind=kint), intent(in) itype_file, integer, intent(in) id_rank)
Definition at line 190 of file set_mesh_file_names.f90.
References set_sph_extensions::add_brj_extension(), and set_sph_extensions::add_rj_extension().
Referenced by sph_file_io_select::check_exsist_rj_file(), sph_file_mpi_io_select::sel_mpi_read_spectr_rj_file(), sph_file_mpi_io_select::sel_mpi_write_spectr_rj_file(), sph_file_io_select::sel_read_spectr_rj_file(), and sph_file_io_select::sel_write_spectr_modes_rj_file().
set_sph_rlm_file_name()
character(len=kchara) function set_mesh_file_names::set_sph_rlm_file_name (character(len=kchara), intent(in) file_header, integer(kind=kint), intent(in) itype_file, integer, intent(in) id_rank)
Definition at line 154 of file set_mesh_file_names.f90.
References set_sph_extensions::add_blm_extension(), and set_sph_extensions::add_rlm_extension().
Referenced by sph_file_io_select::check_exsist_rlm_file(), sph_file_mpi_io_select::sel_mpi_read_modes_rlm_file(), sph_file_mpi_io_select::sel_mpi_write_modes_rlm_file(), sph_file_io_select::sel_read_modes_rlm_file(), and sph_file_io_select::sel_write_modes_rlm_file().
set_sph_rtm_file_name()
character(len=kchara) function set_mesh_file_names::set_sph_rtm_file_name (character(len=kchara), intent(in) file_header, integer(kind=kint), intent(in) itype_file, integer, intent(in) id_rank)
Definition at line 118 of file set_mesh_file_names.f90.
References set_sph_extensions::add_btm_extension(), and set_sph_extensions::add_rtm_extension().
Referenced by sph_file_io_select::check_exsist_rtm_file(), sph_file_mpi_io_select::sel_mpi_read_geom_rtm_file(), sph_file_mpi_io_select::sel_mpi_write_geom_rtm_file(), sph_file_io_select::sel_read_geom_rtm_file(), and sph_file_io_select::sel_write_geom_rtm_file().
set_sph_rtp_file_name()
character(len=kchara) function set_mesh_file_names::set_sph_rtp_file_name (character(len=kchara), intent(in) file_header, integer(kind=kint), intent(in) itype_file, integer, intent(in) id_rank)
Definition at line 82 of file set_mesh_file_names.f90.
References set_sph_extensions::add_btp_extension(), and set_sph_extensions::add_rtp_extension().
Referenced by sph_file_io_select::check_exsist_rtp_file(), sph_file_mpi_io_select::sel_mpi_read_geom_rtp_file(), sph_file_mpi_io_select::sel_mpi_write_geom_rtp_file(), sph_file_io_select::sel_read_geom_rtp_file(), and sph_file_io_select::sel_write_geom_rtp_file().
set_surf_mesh_file_name()
character(len=kchara) function set_mesh_file_names::set_surf_mesh_file_name (character(len=kchara), intent(in) file_header, integer(kind=kint), intent(in) itype_file, integer, intent(in) id_rank)
Definition at line 263 of file set_mesh_file_names.f90.
References set_mesh_extensions::add_gsf_extension(), and set_mesh_extensions::add_sfb_extension().
Referenced by mesh_file_name_by_param::check_exist_surf_mesh(), element_mesh_mpi_io_select::sel_mpi_read_surf_mesh(), element_mesh_mpi_io_select::sel_mpi_write_surf_mesh_file(), element_mesh_io_select::sel_read_surf_mesh(), and element_mesh_io_select::sel_write_surf_mesh_file().