CALYPSO: element_file_io Module Reference
element_file_io Module Reference
File IO for element communication table.
Functions/Subroutines
subroutine input_element_file (id_rank, file_name, ele_mesh_IO, ierr)
subroutine input_surface_file (id_rank, file_name, surf_mesh_IO, ierr)
subroutine input_edge_file (id_rank, file_name, edge_mesh_IO, ierr)
subroutine output_element_file (id_rank, file_name, ele_mesh_IO)
subroutine output_surface_file (id_rank, file_name, surf_mesh_IO)
subroutine output_edge_file (id_rank, file_name, edge_mesh_IO)
Variables
integer(kind=kint), parameter, private input_file_code = 14
Detailed Description
File IO for element communication table.
      subroutine input_element_file                                   &
     &         (id_rank, file_name, ele_mesh_IO, ierr)
      subroutine input_surface_file                                   &
     &         (id_rank, file_name, surf_mesh_IO, ierr)
      subroutine input_edge_file                                      &
     &         (id_rank, file_name, edge_mesh_IO, ierr)
        type(surf_edge_IO_file), intent(inout) :: ele_mesh_IO
        type(surf_edge_IO_file), intent(inout) :: surf_mesh_IO
        type(surf_edge_IO_file), intent(inout) :: edge_mesh_IO
      subroutine output_element_file                                  &
     &         (id_rank, file_name, ele_mesh_IO)
      subroutine output_surface_file                                  &
     &         (id_rank, file_name, surf_mesh_IO)
      subroutine output_edge_file                                     &
     &         (id_rank, file_name, edge_mesh_IO)
        type(surf_edge_IO_file), intent(in) :: ele_mesh_IO
        type(surf_edge_IO_file), intent(in) :: surf_mesh_IO
        type(surf_edge_IO_file), intent(in) :: edge_mesh_IO
Parameters
id_rank MPI rank
Function/Subroutine Documentation
input_edge_file()
subroutine element_file_io::input_edge_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(inout) edge_mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 106 of file element_file_IO.f90.
References m_machine_parameter::i_debug, input_file_code, and edge_data_io::read_edge_connection().
Referenced by element_mesh_io_select::sel_read_edge_mesh().
input_element_file()
subroutine element_file_io::input_element_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(inout) ele_mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 55 of file element_file_IO.f90.
References m_machine_parameter::i_debug, input_file_code, and element_data_io::read_element_comm_table().
Referenced by element_mesh_io_select::sel_read_ele_mesh().
input_surface_file()
subroutine element_file_io::input_surface_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(inout) surf_mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 80 of file element_file_IO.f90.
References m_machine_parameter::i_debug, input_file_code, and surface_data_io::read_surface_connection().
Referenced by element_mesh_io_select::sel_read_surf_mesh().
output_edge_file()
subroutine element_file_io::output_edge_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(in) edge_mesh_IO)
Definition at line 182 of file element_file_IO.f90.
References m_machine_parameter::i_debug, input_file_code, and edge_data_io::write_edge_connection().
Referenced by element_mesh_io_select::sel_write_edge_mesh_file().
output_element_file()
subroutine element_file_io::output_element_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(in) ele_mesh_IO)
Definition at line 133 of file element_file_IO.f90.
References m_machine_parameter::i_debug, input_file_code, and element_data_io::write_element_comm_table().
Referenced by element_mesh_io_select::sel_write_ele_mesh_file().
output_surface_file()
subroutine element_file_io::output_surface_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(in) surf_mesh_IO)
Definition at line 157 of file element_file_IO.f90.
References m_machine_parameter::i_debug, input_file_code, and surface_data_io::write_surface_connection().
Referenced by element_mesh_io_select::sel_write_surf_mesh_file().
Variable Documentation
input_file_code
integer(kind = kint), parameter, private element_file_io::input_file_code = 14 private
Definition at line 45 of file element_file_IO.f90.
Referenced by input_edge_file(), input_element_file(), input_surface_file(), output_edge_file(), output_element_file(), and output_surface_file().