CALYPSO: set_vr_rtm_leg_sym_matmul Module Reference
set_vr_rtm_leg_sym_matmul Module Reference
Backward Legendre transform after mat multi.
Functions/Subroutines
subroutine set_vr_rtm_vector_sym_matmul (nnod_rtm, nidx_rtm, istep_rtm, nidx_rlm, asin_theta_1d_rtm, weight_rtm, kst, nkr, mp_rlm, mn_rlm, nle_rtm, nlo_rtm, ncomp, irev_sr_rtm, n_WR, WR, symp_r, asmp_t, asmp_p, symn_t, symn_p, asmp_r, symp_t, symp_p, asmn_t, asmn_p)
subroutine set_vr_rtm_scalar_sym_matmul (nnod_rtm, nidx_rtm, istep_rtm, nidx_rlm, weight_rtm, kst, nkr, mp_rlm, nle_rtm, nlo_rtm, ncomp, nvector, irev_sr_rtm, n_WR, WR, symp, asmp)
subroutine cal_vr_rtm_vector_sym_matmul (nnod_rtm, nidx_rtm, istep_rtm, nidx_rlm, asin_theta_1d_rtm, kst, nkr, mp_rlm, mn_rlm, nl_rtm, symp_r, asmp_t, asmp_p, symn_t, symn_p, asmp_r, symp_t, symp_p, asmn_t, asmn_p, ncomp, irev_sr_rtm, n_WS, WS)
subroutine cal_vr_rtm_scalar_sym_matmul (nnod_rtm, nidx_rtm, istep_rtm, nidx_rlm, kst, nkr, mp_rlm, nl_rtm, symp, asmp, ncomp, nvector, irev_sr_rtm, n_WS, WS)
Detailed Description
Backward Legendre transform after mat multi.
      subroutine set_vr_rtm_vector_sym_matmul(nnod_rtm, nidx_rtm,     &
     &          istep_rtm, nidx_rlm, asin_theta_1d_rtm, weight_rtm,   &
     &          kst, nkr, mp_rlm, mn_rlm, nle_rtm, nlo_rtm,           &
     &          ncomp, irev_sr_rtm, n_WR, WR,                         &
     &          symp_r, asmp_t, asmp_p, symn_t, symn_p,               &
     &          asmp_r, symp_t, symp_p, asmn_t, asmn_p)
      subroutine set_vr_rtm_scalar_sym_matmul                         &
     &        (nnod_rtm, nidx_rtm, istep_rtm, nidx_rlm, weight_rtm,   &
     &         kst, nkr, mp_rlm, nle_rtm, nlo_rtm,                    &
     &         ncomp, nvector, irev_sr_rtm, n_WR, WR, symp, asmp)
      subroutine cal_vr_rtm_vector_sym_matmul(nnod_rtm, nidx_rtm,     &
     &        istep_rtm, nidx_rlm, asin_theta_1d_rtm,                 &
     &        kst, nkr, mp_rlm, mn_rlm, nl_rtm,                       &
     &        symp_r, asmp_t, asmp_p, symn_t, symn_p,                 &
     &        asmp_r, symp_t, symp_p, asmn_t, asmn_p,                 &
     &        ncomp, irev_sr_rtm, n_WS, WS)
      subroutine cal_vr_rtm_scalar_sym_matmul                         &
     &         (nnod_rtm, nidx_rtm, istep_rtm, nidx_rlm, kst, nkr,    &
     &          mp_rlm, nl_rtm, symp, asmp, ncomp, nvector,           &
     &          irev_sr_rtm, n_WS, WS)
Function/Subroutine Documentation
cal_vr_rtm_scalar_sym_matmul()
subroutine set_vr_rtm_leg_sym_matmul::cal_vr_rtm_scalar_sym_matmul (integer(kind = kint), intent(in) nnod_rtm, integer(kind = kint), dimension(3), intent(in) nidx_rtm, integer(kind = kint), dimension(3), intent(in) istep_rtm, integer(kind = kint), dimension(2), intent(in) nidx_rlm, integer(kind = kint), intent(in) kst, integer(kind = kint), intent(in) nkr, integer(kind = kint), intent(in) mp_rlm, integer(kind = kint), intent(in) nl_rtm, real(kind = kreal), dimension(nl_rtm,nkr), intent(in) symp, real(kind = kreal), dimension(nl_rtm,nkr), intent(in) asmp, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), dimension(nnod_rtm), intent(in) irev_sr_rtm, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 373 of file set_vr_rtm_leg_sym_matmul.f90.
Referenced by legendre_bwd_sym_matmul::leg_b_trans_scl_sym_matmul().
cal_vr_rtm_vector_sym_matmul()
subroutine set_vr_rtm_leg_sym_matmul::cal_vr_rtm_vector_sym_matmul (integer(kind = kint), intent(in) nnod_rtm, integer(kind = kint), dimension(3), intent(in) nidx_rtm, integer(kind = kint), dimension(3), intent(in) istep_rtm, integer(kind = kint), dimension(2), intent(in) nidx_rlm, real(kind = kreal), dimension(nidx_rtm(2)), intent(in) asin_theta_1d_rtm, integer(kind = kint), intent(in) kst, integer(kind = kint), intent(in) nkr, integer(kind = kint), intent(in) mp_rlm, integer(kind = kint), intent(in) mn_rlm, integer(kind = kint), intent(in) nl_rtm, real(kind = kreal), dimension(nl_rtm,nkr), intent(in) symp_r, real(kind = kreal), dimension(nl_rtm,nkr), intent(in) asmp_t, real(kind = kreal), dimension(nl_rtm,nkr), intent(in) asmp_p, real(kind = kreal), dimension(nl_rtm,nkr), intent(inout) symn_t, real(kind = kreal), dimension(nl_rtm,nkr), intent(inout) symn_p, real(kind = kreal), dimension(nl_rtm,nkr), intent(in) asmp_r, real(kind = kreal), dimension(nl_rtm,nkr), intent(in) symp_t, real(kind = kreal), dimension(nl_rtm,nkr), intent(in) symp_p, real(kind = kreal), dimension(nl_rtm,nkr), intent(inout) asmn_t, real(kind = kreal), dimension(nl_rtm,nkr), intent(inout) asmn_p, integer(kind = kint), intent(in) ncomp, integer(kind = kint), dimension(nnod_rtm), intent(in) irev_sr_rtm, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 246 of file set_vr_rtm_leg_sym_matmul.f90.
Referenced by legendre_bwd_sym_matmul::leg_b_trans_vec_sym_matmul().
set_vr_rtm_scalar_sym_matmul()
subroutine set_vr_rtm_leg_sym_matmul::set_vr_rtm_scalar_sym_matmul (integer(kind = kint), intent(in) nnod_rtm, integer(kind = kint), dimension(3), intent(in) nidx_rtm, integer(kind = kint), dimension(3), intent(in) istep_rtm, integer(kind = kint), dimension(2), intent(in) nidx_rlm, real(kind = kreal), dimension(nidx_rtm(2)), intent(in) weight_rtm, integer(kind = kint), intent(in) kst, integer(kind = kint), intent(in) nkr, integer(kind = kint), intent(in) mp_rlm, integer(kind = kint), intent(in) nle_rtm, integer(kind = kint), intent(in) nlo_rtm, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), dimension(nnod_rtm), intent(in) irev_sr_rtm, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(in) WR, real(kind = kreal), dimension(nkr,nle_rtm), intent(inout) symp, real(kind = kreal), dimension(nkr,nle_rtm), intent(inout) asmp)
Definition at line 172 of file set_vr_rtm_leg_sym_matmul.f90.
Referenced by legendre_fwd_sym_matmul::leg_f_trans_scl_sym_matmul().
set_vr_rtm_vector_sym_matmul()
subroutine set_vr_rtm_leg_sym_matmul::set_vr_rtm_vector_sym_matmul (integer(kind = kint), intent(in) nnod_rtm, integer(kind = kint), dimension(3), intent(in) nidx_rtm, integer(kind = kint), dimension(3), intent(in) istep_rtm, integer(kind = kint), dimension(2), intent(in) nidx_rlm, real(kind = kreal), dimension(nidx_rtm(2)), intent(in) asin_theta_1d_rtm, real(kind = kreal), dimension(nidx_rtm(2)), intent(in) weight_rtm, integer(kind = kint), intent(in) kst, integer(kind = kint), intent(in) nkr, integer(kind = kint), intent(in) mp_rlm, integer(kind = kint), intent(in) mn_rlm, integer(kind = kint), intent(in) nle_rtm, integer(kind = kint), intent(in) nlo_rtm, integer(kind = kint), intent(in) ncomp, integer(kind = kint), dimension(nnod_rtm), intent(in) irev_sr_rtm, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(in) WR, real(kind = kreal), dimension(nkr,nle_rtm), intent(inout) symp_r, real(kind = kreal), dimension(nkr,nle_rtm), intent(inout) asmp_t, real(kind = kreal), dimension(nkr,nle_rtm), intent(inout) asmp_p, real(kind = kreal), dimension(nkr,nle_rtm), intent(inout) symn_t, real(kind = kreal), dimension(nkr,nle_rtm), intent(inout) symn_p, real(kind = kreal), dimension(nkr,nle_rtm), intent(inout) asmp_r, real(kind = kreal), dimension(nkr,nle_rtm), intent(inout) symp_t, real(kind = kreal), dimension(nkr,nle_rtm), intent(inout) symp_p, real(kind = kreal), dimension(nkr,nle_rtm), intent(inout) asmn_t, real(kind = kreal), dimension(nkr,nle_rtm), intent(inout) asmn_p)
Definition at line 47 of file set_vr_rtm_leg_sym_matmul.f90.
Referenced by legendre_fwd_sym_matmul::leg_f_trans_vec_sym_matmul().