CALYPSO: m_mhd_step_parameter Module Reference
m_mhd_step_parameter Module Reference
Parameteres for time steppings.
Variables
type(mhd_step_param), save mhd_step1
type(mhd_file_io_params), save mhd_files1
Structure of file name and format for MHD.
type(mhd_io_data), save mhd_io1
Detailed Description
Parameteres for time steppings.
Variable Documentation
mhd_files1
type(mhd_file_io_params), save m_mhd_step_parameter::mhd_files1
Structure of file name and format for MHD.
Definition at line 25 of file m_MHD_step_parameter.f90.
Referenced by analyzer_sph_mhd_w_psf::evolution_sph_mhd_w_psf(), analyzer_sph_snap_w_psf::evolution_sph_snap_w_psf(), sph_analyzer_add_initial::initialize_add_sph_initial(), sph_analyzer_const_initial::initialize_const_sph_initial(), analyzer_sph_mhd_w_psf::initialize_sph_mhd_w_psf(), analyzer_sph_snap_w_psf::initialize_sph_snap_w_psf(), sph_analyzer_add_initial::sph_add_initial_field(), and sph_analyzer_const_initial::sph_const_initial_field().
mhd_io1
type(mhd_io_data), save m_mhd_step_parameter::mhd_io1
Definition at line 27 of file m_MHD_step_parameter.f90.
Referenced by analyzer_sph_mhd_w_psf::evolution_sph_mhd_w_psf(), analyzer_sph_snap_w_psf::evolution_sph_snap_w_psf(), analyzer_sph_mhd_w_psf::initialize_sph_mhd_w_psf(), and analyzer_sph_snap_w_psf::initialize_sph_snap_w_psf().
mhd_step1
type(mhd_step_param), save m_mhd_step_parameter::mhd_step1
Definition at line 22 of file m_MHD_step_parameter.f90.
Referenced by analyzer_sph_mhd_w_psf::evolution_sph_mhd_w_psf(), analyzer_sph_snap_w_psf::evolution_sph_snap_w_psf(), sph_analyzer_add_initial::initialize_add_sph_initial(), sph_analyzer_const_initial::initialize_const_sph_initial(), analyzer_sph_mhd_w_psf::initialize_sph_mhd_w_psf(), analyzer_sph_snap_w_psf::initialize_sph_snap_w_psf(), sph_analyzer_add_initial::sph_add_initial_field(), sph_analyzer_d_bench::sph_analyze_dbench(), sph_analyzer_const_initial::sph_const_initial_field(), and const_sph_initial_spectr::sph_initial_spectrum().