CALYPSO: t_ctl_data_mhd_evo_scheme Module Reference
t_ctl_data_mhd_evo_scheme Module Reference
Set initial data for spectrum dynamos.
Data Types
type mhd_evo_scheme_control
type mhd_restart_control
control flage for restart data
Functions/Subroutines
subroutine read_restart_ctl (id_control, hd_block, mr_ctl, c_buf)
subroutine read_time_loop_ctl (id_control, hd_block, mevo_ctl, c_buf)
subroutine bcast_restart_ctl (mr_ctl)
subroutine bcast_time_loop_ctl (mevo_ctl)
Variables
character(len=kchara), parameter, private hd_rst_flag = 'rst_ctl'
character(len=kchara), parameter, private hd_iflag_supg = 'iflag_supg_ctl'
character(len=kchara), parameter, private hd_iflag_v_supg = 'iflag_supg_v_ctl'
character(len=kchara), parameter, private hd_iflag_t_supg = 'iflag_supg_t_ctl'
character(len=kchara), parameter, private hd_iflag_b_supg = 'iflag_supg_b_ctl'
character(len=kchara), parameter, private hd_iflag_c_supg = 'iflag_supg_c_ctl'
character(len=kchara), parameter, private hd_num_multi_pass = 'num_multi_pass_ctl'
character(len=kchara), parameter, private hd_maxiter = 'maxiter_ctl'
character(len=kchara), parameter, private hd_eps_4_velo = 'eps_4_velo_ctl'
character(len=kchara), parameter, private hd_eps_4_magne = 'eps_4_magne_ctl'
character(len=kchara), parameter, private hd_scheme = 'scheme_ctl'
character(len=kchara), parameter, private hd_diff_correct = 'diffuse_correct_ctl'
character(len=kchara), parameter, private hd_coef_imp_v = 'coef_imp_v_ctl'
character(len=kchara), parameter, private hd_coef_imp_t = 'coef_imp_t_ctl'
character(len=kchara), parameter, private hd_coef_imp_b = 'coef_imp_b_ctl'
character(len=kchara), parameter, private hd_coef_imp_c = 'coef_imp_c_ctl'
character(len=kchara), parameter, private hd_eps_crank = 'eps_crank_ctl'
character(len=kchara), parameter, private hd_eps_b_crank = 'eps_B_solver_ctl'
character(len=kchara), parameter, private hd_method_4_velo = 'method_4_velo_ctl'
character(len=kchara), parameter, private hd_precond_4_crank = 'precond_4_crank_ctl'
character(len=kchara), parameter, private hd_sph_transform_mode = 'Legendre_trans_loop_ctl'
character(len=kchara), parameter, private hd_fft_package = 'FFT_library_ctl'
character(len=kchara), parameter, private hd_import_mode = 'import_table_mode_ctl'
character(len=kchara), parameter, private hd_legendre_vect_len = 'Legendre_vector_length_ctl'
Detailed Description
Set initial data for spectrum dynamos.
      subroutine read_restart_ctl(id_control, hd_block, mr_ctl, c_buf)
      subroutine read_time_loop_ctl                                   &
     &         (id_control, hd_block, mevo_ctl, c_buf)
        type(mhd_restart_control), intent(inout) :: mr_ctl
        type(mhd_evo_scheme_control), intent(inout) :: mevo_ctl
        type(buffer_for_control), intent(inout)  :: c_buf
      subroutine bcast_restart_ctl(mr_ctl)
        type(mhd_restart_control), intent(inout) :: mr_ctl
      subroutine bcast_time_loop_ctl(mevo_ctl)
        type(mhd_evo_scheme_control), intent(inout) :: mevo_ctl
 !!!!  control for initial and restart data  !!!!!!!!!!!!!!!!!!!!!!!!!!
   no_data:             No initial values
   start_from_rst_file: Read restart data as initial values
   dynamo_benchmark_0: Initial values for dynamo benchmark Case 0
   dynamo_benchmark_1: Initial values for dynamo benchmark Case 1
   dynamo_benchmark_2: Initial values for dynamo benchmark Case 1
   pseudo_vacuum_benchmark: Initial values for pseudo vacuum benchmark
   rotate_x: rotate around x-axis
   rotate_y: rotate around y-axis
   rotate_z: rotate around z-axis
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    begin restart_file_ctl
     rst_ctl                start_from_rst_file
    end restart_file_ctl
 !!!   method for time evolution  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
   iflag_supg_ctl:      0...no SUPG 1...SUPG
   iflag_supg_v_ctl           Off
   iflag_supg_t_ctl           Off
   iflag_supg_b_ctl           Off
   iflag_supg_c_ctl           Off
   num_multi_pass_ctl:  iteration counts for multi pass
   maxiter_ctl:         maximum iteration number for correction
   eps_4_velo_ctl:      ||div v||_{n} / ||div v||_{n-1}
   eps_4_magne_ctl:     ||div B||_{n} / ||div B||_{n-1}
   scheme_ctl:          Scheme for time evolution
                 explicit_Euler...explicit_Euler
                 2nd_Adams_Bashforth...2nd_Adams_Bashforth
                 Crank_Nicolson...Crank_Nicolson with 2nd_Adams_Bashforth
                 Crank_Nicolson_consist...Crank_Nicolson
                                         with consistent mass matrix
   eps_crank_ctl:
   method_4_velo_ctl:    method for Crank Nicolson Scheme
   precond_4_crank_ctl:  preconditioning method for Crank Nicolson Scheme
   Legendre_trans_loop_ctl: Legendre_transform loop type
                   ('inner_radial_loop' 'outer_radial_loop' 'long_loop')
   FFT_library_ctl:  Selection of FFT librarry  ('FFTW3' or 'FFTPACK')
   import_table_mode_ctl:   Selection of import mode
                     ('regular_table' or 'reversed_table')
   send_recv_routine_ctl:    Selection of send_recv_routines
                     ('SEND_RECV', 'AllToAllv', or 'AllToAll')
   Legendre_vector_length_ctl:  vector length for Legendre transform
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    begin time_loop_ctl
      iflag_supg_ctl           0
      num_multi_pass_ctl       1
      maxiter_ctl              1
      eps_4_velo_ctl           5.0e-1
      eps_4_magne_ctl          5.0e-1
      scheme_ctl              Crank_Nicolson
      diffuse_correct_ctl     On
      coef_imp_v_ctl          5.0e-1
      coef_imp_t_ctl          5.0e-1
      coef_imp_b_ctl          5.0e-1
      coef_imp_c_ctl          5.0e-1
      eps_crank_ctl           1.0e-6
      eps_B_solver_ctl        1.0e-6
      method_4_velo_ctl      CG
      precond_4_crank_ctl     SSOR
      Legendre_trans_loop_ctl   'inner_radial_loop'
      FFT_library_ctl           'FFTW'
      Legendre_vector_length_ctl    2
    end time_loop_ctl
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Function/Subroutine Documentation
bcast_restart_ctl()
subroutine t_ctl_data_mhd_evo_scheme::bcast_restart_ctl (type(mhd_restart_control), intent(inout) mr_ctl)
Definition at line 329 of file t_ctl_data_mhd_evo_scheme.f90.
References bcast_control_arrays::bcast_ctl_type_c1(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by t_ctl_data_sph_mhd_control::bcast_sph_mhd_control().
bcast_time_loop_ctl()
subroutine t_ctl_data_mhd_evo_scheme::bcast_time_loop_ctl (type(mhd_evo_scheme_control), intent(inout) mevo_ctl)
Definition at line 345 of file t_ctl_data_mhd_evo_scheme.f90.
References bcast_control_arrays::bcast_ctl_type_c1(), bcast_control_arrays::bcast_ctl_type_i1(), bcast_control_arrays::bcast_ctl_type_r1(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by t_ctl_data_sph_mhd_control::bcast_sph_mhd_control().
read_restart_ctl()
subroutine t_ctl_data_mhd_evo_scheme::read_restart_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(mhd_restart_control), intent(inout) mr_ctl, type(buffer_for_control), intent(inout) c_buf)
Definition at line 226 of file t_ctl_data_mhd_evo_scheme.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_rst_flag, t_read_control_elements::load_one_line_from_control(), and t_control_array_character::read_chara_ctl_type().
Referenced by t_ctl_data_sph_mhd_control::read_sph_mhd_control().
read_time_loop_ctl()
subroutine t_ctl_data_mhd_evo_scheme::read_time_loop_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(mhd_evo_scheme_control), intent(inout) mevo_ctl, type(buffer_for_control), intent(inout) c_buf)
Definition at line 253 of file t_ctl_data_mhd_evo_scheme.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_coef_imp_b, hd_coef_imp_c, hd_coef_imp_t, hd_coef_imp_v, hd_diff_correct, hd_eps_4_magne, hd_eps_4_velo, hd_eps_b_crank, hd_eps_crank, hd_fft_package, hd_iflag_b_supg, hd_iflag_c_supg, hd_iflag_supg, hd_iflag_t_supg, hd_iflag_v_supg, hd_import_mode, hd_legendre_vect_len, hd_maxiter, hd_method_4_velo, hd_num_multi_pass, hd_precond_4_crank, hd_scheme, hd_sph_transform_mode, t_read_control_elements::load_one_line_from_control(), t_control_array_character::read_chara_ctl_type(), t_control_array_integer::read_integer_ctl_type(), and t_control_array_real::read_real_ctl_type().
Referenced by t_ctl_data_sph_mhd_control::read_sph_mhd_control().
Variable Documentation
hd_coef_imp_b
character(len=kchara), parameter, private t_ctl_data_mhd_evo_scheme::hd_coef_imp_b = 'coef_imp_b_ctl' private
Definition at line 188 of file t_ctl_data_mhd_evo_scheme.f90.
Referenced by read_time_loop_ctl().
hd_coef_imp_c
character(len=kchara), parameter, private t_ctl_data_mhd_evo_scheme::hd_coef_imp_c = 'coef_imp_c_ctl' private
Definition at line 190 of file t_ctl_data_mhd_evo_scheme.f90.
Referenced by read_time_loop_ctl().
hd_coef_imp_t
character(len=kchara), parameter, private t_ctl_data_mhd_evo_scheme::hd_coef_imp_t = 'coef_imp_t_ctl' private
Definition at line 186 of file t_ctl_data_mhd_evo_scheme.f90.
Referenced by read_time_loop_ctl().
hd_coef_imp_v
character(len=kchara), parameter, private t_ctl_data_mhd_evo_scheme::hd_coef_imp_v = 'coef_imp_v_ctl' private
Definition at line 184 of file t_ctl_data_mhd_evo_scheme.f90.
Referenced by read_time_loop_ctl().
hd_diff_correct
character(len=kchara), parameter, private t_ctl_data_mhd_evo_scheme::hd_diff_correct = 'diffuse_correct_ctl' private
Definition at line 182 of file t_ctl_data_mhd_evo_scheme.f90.
Referenced by read_time_loop_ctl().
hd_eps_4_magne
character(len=kchara), parameter, private t_ctl_data_mhd_evo_scheme::hd_eps_4_magne = 'eps_4_magne_ctl' private
Definition at line 178 of file t_ctl_data_mhd_evo_scheme.f90.
Referenced by read_time_loop_ctl().
hd_eps_4_velo
character(len=kchara), parameter, private t_ctl_data_mhd_evo_scheme::hd_eps_4_velo = 'eps_4_velo_ctl' private
Definition at line 176 of file t_ctl_data_mhd_evo_scheme.f90.
Referenced by read_time_loop_ctl().
hd_eps_b_crank
character(len=kchara), parameter, private t_ctl_data_mhd_evo_scheme::hd_eps_b_crank = 'eps_B_solver_ctl' private
Definition at line 194 of file t_ctl_data_mhd_evo_scheme.f90.
Referenced by read_time_loop_ctl().
hd_eps_crank
character(len=kchara), parameter, private t_ctl_data_mhd_evo_scheme::hd_eps_crank = 'eps_crank_ctl' private
Definition at line 192 of file t_ctl_data_mhd_evo_scheme.f90.
Referenced by read_time_loop_ctl().
hd_fft_package
character(len=kchara), parameter, private t_ctl_data_mhd_evo_scheme::hd_fft_package = 'FFT_library_ctl' private
Definition at line 202 of file t_ctl_data_mhd_evo_scheme.f90.
Referenced by read_time_loop_ctl().
hd_iflag_b_supg
character(len=kchara), parameter, private t_ctl_data_mhd_evo_scheme::hd_iflag_b_supg = 'iflag_supg_b_ctl' private
Definition at line 167 of file t_ctl_data_mhd_evo_scheme.f90.
Referenced by read_time_loop_ctl().
hd_iflag_c_supg
character(len=kchara), parameter, private t_ctl_data_mhd_evo_scheme::hd_iflag_c_supg = 'iflag_supg_c_ctl' private
Definition at line 169 of file t_ctl_data_mhd_evo_scheme.f90.
Referenced by read_time_loop_ctl().
hd_iflag_supg
character(len=kchara), parameter, private t_ctl_data_mhd_evo_scheme::hd_iflag_supg = 'iflag_supg_ctl' private
Definition at line 161 of file t_ctl_data_mhd_evo_scheme.f90.
Referenced by read_time_loop_ctl().
hd_iflag_t_supg
character(len=kchara), parameter, private t_ctl_data_mhd_evo_scheme::hd_iflag_t_supg = 'iflag_supg_t_ctl' private
Definition at line 165 of file t_ctl_data_mhd_evo_scheme.f90.
Referenced by read_time_loop_ctl().
hd_iflag_v_supg
character(len=kchara), parameter, private t_ctl_data_mhd_evo_scheme::hd_iflag_v_supg = 'iflag_supg_v_ctl' private
Definition at line 163 of file t_ctl_data_mhd_evo_scheme.f90.
Referenced by read_time_loop_ctl().
hd_import_mode
character(len=kchara), parameter, private t_ctl_data_mhd_evo_scheme::hd_import_mode = 'import_table_mode_ctl' private
Definition at line 204 of file t_ctl_data_mhd_evo_scheme.f90.
Referenced by read_time_loop_ctl().
hd_legendre_vect_len
character(len=kchara), parameter, private t_ctl_data_mhd_evo_scheme::hd_legendre_vect_len = 'Legendre_vector_length_ctl' private
Definition at line 206 of file t_ctl_data_mhd_evo_scheme.f90.
Referenced by read_time_loop_ctl().
hd_maxiter
character(len=kchara), parameter, private t_ctl_data_mhd_evo_scheme::hd_maxiter = 'maxiter_ctl' private
Definition at line 174 of file t_ctl_data_mhd_evo_scheme.f90.
Referenced by read_time_loop_ctl().
hd_method_4_velo
character(len=kchara), parameter, private t_ctl_data_mhd_evo_scheme::hd_method_4_velo = 'method_4_velo_ctl' private
Definition at line 196 of file t_ctl_data_mhd_evo_scheme.f90.
Referenced by read_time_loop_ctl().
hd_num_multi_pass
character(len=kchara), parameter, private t_ctl_data_mhd_evo_scheme::hd_num_multi_pass = 'num_multi_pass_ctl' private
Definition at line 172 of file t_ctl_data_mhd_evo_scheme.f90.
Referenced by read_time_loop_ctl().
hd_precond_4_crank
character(len=kchara), parameter, private t_ctl_data_mhd_evo_scheme::hd_precond_4_crank = 'precond_4_crank_ctl' private
Definition at line 198 of file t_ctl_data_mhd_evo_scheme.f90.
Referenced by read_time_loop_ctl().
hd_rst_flag
character(len=kchara), parameter, private t_ctl_data_mhd_evo_scheme::hd_rst_flag = 'rst_ctl' private
Definition at line 157 of file t_ctl_data_mhd_evo_scheme.f90.
Referenced by read_restart_ctl().
hd_scheme
character(len=kchara), parameter, private t_ctl_data_mhd_evo_scheme::hd_scheme = 'scheme_ctl' private
Definition at line 180 of file t_ctl_data_mhd_evo_scheme.f90.
Referenced by read_time_loop_ctl().
hd_sph_transform_mode
character(len=kchara), parameter, private t_ctl_data_mhd_evo_scheme::hd_sph_transform_mode = 'Legendre_trans_loop_ctl' private
Definition at line 200 of file t_ctl_data_mhd_evo_scheme.f90.
Referenced by read_time_loop_ctl().