CALYPSO: t_sph_mesh_1d_connect Module Reference
t_sph_mesh_1d_connect Module Reference
One-dimmentional connectivity list for spherical shell.
Data Types
type comm_table_make_sph
Functions/Subroutines
subroutine alloc_nnod_nele_sph_mesh (ndomain_sph, ndomain_rtp, nidx_global_rtp, m_folding, stbl)
subroutine alloc_iele_sph_mesh (stbl)
subroutine alloc_1d_comm_tbl_4_sph (ntot_import, ntot_export, stbl)
subroutine dealloc_nnod_nele_sph_mesh (stbl)
subroutine dealloc_1d_comm_tbl_4_sph (stbl)
subroutine check_iele_4_sph_connects (stbl)
Detailed Description
One-dimmentional connectivity list for spherical shell.
      subroutine alloc_nnod_nele_sph_mesh(ndomain_sph, ndomain_rtp,&
     &          nidx_global_rtp, m_folding, stbl)
      subroutine alloc_iele_sph_mesh(stbl)
      subroutine alloc_1d_comm_tbl_4_sph                              &
     &         (ntot_import, ntot_export, stbl)
      subroutine dealloc_nnod_nele_sph_mesh(stbl)
      subroutine dealloc_1d_comm_tbl_4_sph(stbl)
      subroutine check_iele_4_sph_connects(stbl)
Function/Subroutine Documentation
alloc_1d_comm_tbl_4_sph()
subroutine t_sph_mesh_1d_connect::alloc_1d_comm_tbl_4_sph (integer(kind = kint), intent(in) ntot_import, integer(kind = kint), intent(in) ntot_export, type(comm_table_make_sph), intent(inout) stbl)
Definition at line 217 of file t_sph_mesh_1d_connect.f90.
Referenced by set_fem_mesh_4_sph::const_nod_comm_table_for_sph().
alloc_iele_sph_mesh()
subroutine t_sph_mesh_1d_connect::alloc_iele_sph_mesh (type(comm_table_make_sph), intent(inout) stbl)
Definition at line 166 of file t_sph_mesh_1d_connect.f90.
Referenced by const_1d_ele_connect_4_sph::s_const_1d_ele_connect_4_sph().
alloc_nnod_nele_sph_mesh()
subroutine t_sph_mesh_1d_connect::alloc_nnod_nele_sph_mesh (integer(kind = kint), intent(in) ndomain_sph, integer(kind = kint), dimension(3), intent(in) ndomain_rtp, integer(kind = kint), dimension(3), intent(in) nidx_global_rtp, integer(kind = kint), intent(in) m_folding, type(comm_table_make_sph), intent(inout) stbl)
Definition at line 99 of file t_sph_mesh_1d_connect.f90.
Referenced by const_1d_ele_connect_4_sph::s_const_1d_ele_connect_4_sph().
check_iele_4_sph_connects()
subroutine t_sph_mesh_1d_connect::check_iele_4_sph_connects (type(comm_table_make_sph), intent(in) stbl)
Definition at line 276 of file t_sph_mesh_1d_connect.f90.
Referenced by const_1d_ele_connect_4_sph::s_const_1d_ele_connect_4_sph().
dealloc_1d_comm_tbl_4_sph()
subroutine t_sph_mesh_1d_connect::dealloc_1d_comm_tbl_4_sph (type(comm_table_make_sph), intent(inout) stbl)
Definition at line 263 of file t_sph_mesh_1d_connect.f90.
Referenced by set_fem_mesh_4_sph::const_nod_comm_table_for_sph().
dealloc_nnod_nele_sph_mesh()
subroutine t_sph_mesh_1d_connect::dealloc_nnod_nele_sph_mesh (type(comm_table_make_sph), intent(inout) stbl)
Definition at line 238 of file t_sph_mesh_1d_connect.f90.
Referenced by const_fem_mesh_sph_mhd::base_fem_mesh_sph_mhd().