CALYPSO: sum_spectr_over_smp_segment Module Reference
sum_spectr_over_smp_segment Module Reference
forward Legendre transform (Blocked loop version)
Functions/Subroutines
subroutine sum_spectr_over_smp_in (nkrs, nkrt, n_jk_e, n_jk_o, Smat)
subroutine sum_spectr_over_kr_in (nkrs, nkrt, n_jk_e, n_jk_o, Smat)
subroutine sum_spectr_over_smp_out (nkrs, nkrt, n_jk_e, n_jk_o, Smat)
Variables
integer, external omp_get_max_threads
Detailed Description
forward Legendre transform (Blocked loop version)
      subroutine sum_spectr_over_smp_in                             &
     &         (nkrs, nkrt, n_jk_e, n_jk_o, Smat)
      subroutine sum_spectr_over_kr_in                              &
     &         (nkrs, nkrt, n_jk_e, n_jk_o, Smat)
      subroutine sum_spectr_over_smp_out                            &
     &         (nkrs, nkrt, n_jk_e, n_jk_o, Smat)
        type(spectr_matrix_omp), intent(inout) :: Smat(np_smp)
Function/Subroutine Documentation
sum_spectr_over_kr_in()
subroutine sum_spectr_over_smp_segment::sum_spectr_over_kr_in (integer(kind = kint), intent(in) nkrs, integer(kind = kint), intent(in) nkrt, integer(kind = kint), intent(in) n_jk_e, integer(kind = kint), intent(in) n_jk_o, type(spectr_matrix_omp), dimension(np_smp), intent(inout) Smat)
Definition at line 84 of file sum_spectr_over_smp_segment.f90.
Referenced by leg_fwd_trans_on_the_fly::legendre_f_trans_on_the_fly(), leg_fwd_trans_sym_mat_jt::legendre_f_trans_sym_mat_jt(), and leg_fwd_trans_sym_mat_tj::legendre_f_trans_sym_mat_tj().
sum_spectr_over_smp_in()
subroutine sum_spectr_over_smp_segment::sum_spectr_over_smp_in (integer(kind = kint), intent(in) nkrs, integer(kind = kint), intent(in) nkrt, integer(kind = kint), intent(in) n_jk_e, integer(kind = kint), intent(in) n_jk_o, type(spectr_matrix_omp), dimension(np_smp), intent(inout) Smat)
Definition at line 39 of file sum_spectr_over_smp_segment.f90.
sum_spectr_over_smp_out()
subroutine sum_spectr_over_smp_segment::sum_spectr_over_smp_out (integer(kind = kint), intent(in) nkrs, integer(kind = kint), intent(in) nkrt, integer(kind = kint), intent(in) n_jk_e, integer(kind = kint), intent(in) n_jk_o, type(spectr_matrix_omp), dimension(np_smp), intent(inout) Smat)
Definition at line 141 of file sum_spectr_over_smp_segment.f90.
Variable Documentation
omp_get_max_threads
integer, external sum_spectr_over_smp_segment::omp_get_max_threads
Definition at line 31 of file sum_spectr_over_smp_segment.f90.