CALYPSO: m_base_force_labels Module Reference
m_base_force_labels Module Reference
Functions/Subroutines
logical function check_scalar_advection (field_name)
logical function check_force_vectors (field_name)
logical function check_flux_tensors (field_name)
logical function check_asym_flux_tensors (field_name)
integer(kind=kint) function num_base_forces ()
subroutine set_base_force_labels (n_comps, names, maths)
Variables
integer(kind=kint), parameter, private nforce_base = 21
type(field_def), parameter pressure_gradient = field_def(n_comp = n_vector, name = 'pressure_gradient', math = '$ \partial_{i} p $')
Field label for pressure gradient \(\partial_{i} p \).
type(field_def), parameter inertia = field_def(n_comp = n_vector, name = 'inertia', math = '$ e_{ijk} \omega_{j} u_{k} $')
Field label for advection for momentum \(e_{ijk} \omega_{j} u_{k} \) or \(u_{j} \partial_{j} u_{i} \).
type(field_def), parameter lorentz_force = field_def(n_comp = n_vector, name = 'Lorentz_force', math = '$ e_{ijk} J{j} B_{k} $')
Field label for Lorentz force \(e_{ijk} J_{j} B_{k} \).
type(field_def), parameter magnetic_tension = field_def(n_comp = n_vector, name = 'magnetic_tension', math = '$ B_{j} \partial_{j} B_{i} $')
start address for magnetic tension \(B_{j} \partial_{j} B_{i} \)
type(field_def), parameter coriolis_force = field_def(n_comp = n_vector, name = 'Coriolis_force', math = '$ -2 e_{ijk} \Omega_{j} u_{k} $')
Field label for Coriolis force \(-2 e_{ijk} \Omega_{j} u_{k} \).
type(field_def), parameter buoyancy = field_def(n_comp = n_vector, name = 'buoyancy', math = '$ -\alpha_{T} g_{i} T $')
Field label for buoyancy \(-\alpha_{T} g_{i} T \).
type(field_def), parameter composite_buoyancy = field_def(n_comp = n_vector, name = 'composite_buoyancy', math = '$ -\alpha_{C} g_{i} C $')
Field label for compositional buoyancy \(-\alpha_{C} g_{i} C \).
type(field_def), parameter vecp_induction = field_def(n_comp = n_vector, name = 'vecp_induction', math = '$ e_{ijk} u_{j} B_{k} $')
Field label for induction for vector potential \(e_{ijk} u_{j} B_{k} \).
type(field_def), parameter magnetic_induction = field_def(n_comp = n_vector, name = 'magnetic_induction', math = '$ e_{ijk} \partial_{j} ' // ' (e_{ijk} u_{j} B_{k})$')
Field label for magnetic induction \(e_{ijk} \partial_{j}\left(e_{klm}u_{l}B_{m} \right)\).
type(field_def), parameter magnetic_stretch = field_def(n_comp = n_vector, name = 'magnetic_stretch', math = '$ B_{j} \partial_{j} u_{i} $')
Field label for magnetic stretch term \(B_{j} \partial_{j} u_{i} \).
type(field_def), parameter heat_advect = field_def(n_comp = n_scalar, name = 'heat_advect', math = '$ u_{i} \partial_{i} T $')
Field label for advection for temperature \(u_{i} \partial_{i} T \).
type(field_def), parameter pert_heat_advect = field_def(n_comp = n_scalar, name = 'pert_heat_advect', math = '$ u_{i} \partial_{i} \Theta $')
Field label for advection for perturbation of temperature \(u_{i} \partial_{i} \Theta \).
type(field_def), parameter composition_advect = field_def(n_comp = n_scalar, name = 'composition_advect', math = '$ u_{i} \partial_{i} C $')
Field label for advection for composition \(u_{i} \partial_{i} C \).
type(field_def), parameter pert_comp_advect = field_def(n_comp = n_scalar, name = 'pert_comp_advect', math = '$ u_{i} \partial_{i} \Theta_{C} $')
Field label for advection for perturbation of composition \(u_{i} \partial_{i} \Theta_{C} \).
type(field_def), parameter momentum_flux = field_def(n_comp = n_sym_tensor, name = 'momentum_flux', math = '$ u_{i} u_{j} $')
Field label for momentum flux \(u_{i} u_{j} \).
type(field_def), parameter maxwell_tensor = field_def(n_comp = n_sym_tensor, name = 'maxwell_tensor', math = '$ B_{i} B_{j} $')
Field label for Maxwell tensor \(B_{i} B_{j} \).
type(field_def), parameter induction_tensor = field_def(n_comp = n_vector, name = 'induction_tensor', math = '$ u_{i} B_{j} - B_{i} u_{J} $')
Field label of tensor for magnetic induction \(u_{i} B_{j} - B_{i} u_{J} \).
type(field_def), parameter heat_flux = field_def(n_comp = n_vector, name = 'heat_flux', math = '$ u_{i} T $')
Field label for heat flux \(u_{i} T \).
type(field_def), parameter pert_heat_flux = field_def(n_comp = n_vector, name = 'pert_heat_flux', math = '$ u_{i} \Theta $')
Field label for perturbation of heat flux \(u_{i} \Theta \).
type(field_def), parameter composite_flux = field_def(n_comp = n_vector, name = 'composite_flux', math = '$ u_{i} C $')
Field label for compositinoal flux \(u_{i} C \).
type(field_def), parameter pert_comp_flux = field_def(n_comp = n_vector, name = 'pert_comp_flux', math = '$ u_{i} \Theta_{C} $')
Field label for perturbation of composition flux \(u_{i} \Theta_{C} \).
Function/Subroutine Documentation
check_asym_flux_tensors()
logical function m_base_force_labels::check_asym_flux_tensors (character(len = kchara), intent(in) field_name)
Definition at line 268 of file m_base_force_labels.f90.
References induction_tensor.
Referenced by set_mhd_field_address::check_asym_tensor_fields(), and t_base_force_labels::set_base_force_addresses().
check_flux_tensors()
logical function m_base_force_labels::check_flux_tensors (character(len = kchara), intent(in) field_name)
Definition at line 255 of file m_base_force_labels.f90.
References maxwell_tensor, and momentum_flux.
Referenced by set_mhd_field_address::check_sym_tensor_fields(), and t_base_force_labels::set_base_force_addresses().
check_force_vectors()
logical function m_base_force_labels::check_force_vectors (character(len = kchara), intent(in) field_name)
Definition at line 229 of file m_base_force_labels.f90.
References buoyancy, composite_buoyancy, composite_flux, coriolis_force, heat_flux, inertia, lorentz_force, magnetic_induction, magnetic_stretch, magnetic_tension, pert_comp_flux, pert_heat_flux, pressure_gradient, and vecp_induction.
Referenced by set_mhd_field_address::check_vector_fields(), and t_base_force_labels::set_base_force_addresses().
check_scalar_advection()
logical function m_base_force_labels::check_scalar_advection (character(len = kchara), intent(in) field_name)
Definition at line 214 of file m_base_force_labels.f90.
References composition_advect, heat_advect, pert_comp_advect, and pert_heat_advect.
Referenced by set_mhd_field_address::check_scalar_fields(), and t_base_force_labels::set_base_force_addresses().
num_base_forces()
integer(kind = kint) function m_base_force_labels::num_base_forces
Definition at line 280 of file m_base_force_labels.f90.
References nforce_base.
set_base_force_labels()
subroutine m_base_force_labels::set_base_force_labels (integer(kind = kint_4b), dimension(nforce_base), intent(inout) n_comps, character(len = kchara), dimension(nforce_base), intent(inout) names, character(len = kchara), dimension(nforce_base), intent(inout) maths)
Definition at line 287 of file m_base_force_labels.f90.
References buoyancy, composite_buoyancy, composite_flux, composition_advect, coriolis_force, heat_advect, heat_flux, induction_tensor, inertia, lorentz_force, magnetic_induction, magnetic_stretch, magnetic_tension, maxwell_tensor, momentum_flux, pert_comp_advect, pert_comp_flux, pert_heat_advect, pert_heat_flux, pressure_gradient, t_field_labels::set_field_labels(), and vecp_induction.
Variable Documentation
buoyancy
type(field_def), parameter m_base_force_labels::buoyancy = field_def(n_comp = n_vector, name = 'buoyancy', math = '$ -\alpha_{T} g_{i} T $')
Field label for buoyancy \(-\alpha_{T} g_{i} T \).
Definition at line 105 of file m_base_force_labels.f90.
Referenced by add_nodal_fields_4_mhd::add_ctl_4_forces(), check_base_forces::add_field_ctl_4_div_forces(), check_energy_fluxes::add_field_ctl_4_ene_flux(), check_base_forces::add_field_ctl_4_forces(), check_base_forces::add_field_ctl_4_rot_forces(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_force_vectors(), t_base_force_labels::set_base_force_addresses(), set_base_force_labels(), and m_force_control_labels::set_force_control_labels().
composite_buoyancy
type(field_def), parameter m_base_force_labels::composite_buoyancy = field_def(n_comp = n_vector, name = 'composite_buoyancy', math = '$ -\alpha_{C} g_{i} C $')
Field label for compositional buoyancy \(-\alpha_{C} g_{i} C \).
Definition at line 111 of file m_base_force_labels.f90.
Referenced by add_nodal_fields_4_mhd::add_ctl_4_forces(), check_base_forces::add_field_ctl_4_div_forces(), check_energy_fluxes::add_field_ctl_4_ene_flux(), check_base_forces::add_field_ctl_4_forces(), check_base_forces::add_field_ctl_4_rot_forces(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_force_vectors(), t_base_force_labels::set_base_force_addresses(), set_base_force_labels(), and m_force_control_labels::set_force_control_labels().
composite_flux
type(field_def), parameter m_base_force_labels::composite_flux = field_def(n_comp = n_vector, name = 'composite_flux', math = '$ u_{i} C $')
Field label for compositinoal flux \(u_{i} C \).
Definition at line 197 of file m_base_force_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_div_forces(), check_base_forces::add_field_ctl_4_forces(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_force_vectors(), set_sph_boundary_from_file::find_scalar_bc_label(), set_sph_boundary_from_file::num_comp_bc_data(), t_base_force_labels::set_base_force_addresses(), set_base_force_labels(), and set_bc_sph_scalars::set_sph_bc_composition_sph().
composition_advect
type(field_def), parameter m_base_force_labels::composition_advect = field_def(n_comp = n_scalar, name = 'composition_advect', math = '$ u_{i} \partial_{i} C $')
Field label for advection for composition \(u_{i} \partial_{i} C \).
Definition at line 152 of file m_base_force_labels.f90.
Referenced by check_energy_fluxes::add_field_ctl_4_ene_flux(), check_base_forces::add_field_ctl_4_forces(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_scalar_advection(), m_force_control_labels::set_advection_control_labels(), t_base_force_labels::set_base_force_addresses(), and set_base_force_labels().
coriolis_force
type(field_def), parameter m_base_force_labels::coriolis_force = field_def(n_comp = n_vector, name = 'Coriolis_force', math = '$ -2 e_{ijk} \Omega_{j} u_{k} $')
Field label for Coriolis force \(-2 e_{ijk} \Omega_{j} u_{k} \).
Definition at line 99 of file m_base_force_labels.f90.
Referenced by add_nodal_fields_4_mhd::add_ctl_4_forces(), check_base_forces::add_field_ctl_4_div_forces(), check_base_forces::add_field_ctl_4_field_products(), check_base_forces::add_field_ctl_4_forces(), check_base_forces::add_field_ctl_4_rot_forces(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_force_vectors(), t_base_force_labels::set_base_force_addresses(), set_base_force_labels(), and m_force_control_labels::set_force_control_labels().
heat_advect
type(field_def), parameter m_base_force_labels::heat_advect = field_def(n_comp = n_scalar, name = 'heat_advect', math = '$ u_{i} \partial_{i} T $')
Field label for advection for temperature \(u_{i} \partial_{i} T \).
Definition at line 139 of file m_base_force_labels.f90.
Referenced by check_energy_fluxes::add_field_ctl_4_ene_flux(), check_base_forces::add_field_ctl_4_forces(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_scalar_advection(), m_force_control_labels::set_advection_control_labels(), t_base_force_labels::set_base_force_addresses(), and set_base_force_labels().
heat_flux
type(field_def), parameter m_base_force_labels::heat_flux = field_def(n_comp = n_vector, name = 'heat_flux', math = '$ u_{i} T $')
Field label for heat flux \(u_{i} T \).
Definition at line 185 of file m_base_force_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_forces(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_force_vectors(), set_sph_boundary_from_file::find_scalar_bc_label(), set_sph_boundary_from_file::num_comp_bc_data(), t_base_force_labels::set_base_force_addresses(), set_base_force_labels(), and set_bc_sph_scalars::set_sph_bc_temp_sph().
induction_tensor
type(field_def), parameter m_base_force_labels::induction_tensor = field_def(n_comp = n_vector, name = 'induction_tensor', math = '$ u_{i} B_{j} - B_{i} u_{J} $')
Field label of tensor for magnetic induction \(u_{i} B_{j} - B_{i} u_{J} \).
Definition at line 178 of file m_base_force_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_div_forces(), check_base_forces::add_field_ctl_4_forces(), check_asym_flux_tensors(), t_base_force_labels::set_base_force_addresses(), and set_base_force_labels().
inertia
type(field_def), parameter m_base_force_labels::inertia = field_def(n_comp = n_vector, name = 'inertia', math = '$ e_{ijk} \omega_{j} u_{k} $')
Field label for advection for momentum \(e_{ijk} \omega_{j} u_{k} \) or \(u_{j} \partial_{j} u_{i} \).
Definition at line 81 of file m_base_force_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_div_forces(), check_energy_fluxes::add_field_ctl_4_ene_flux(), check_base_forces::add_field_ctl_4_forces(), check_base_forces::add_field_ctl_4_rot_forces(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_force_vectors(), m_force_control_labels::set_advection_control_labels(), t_base_force_labels::set_base_force_addresses(), and set_base_force_labels().
lorentz_force
type(field_def), parameter m_base_force_labels::lorentz_force = field_def(n_comp = n_vector, name = 'Lorentz_force', math = '$ e_{ijk} J{j} B_{k} $')
Field label for Lorentz force \(e_{ijk} J_{j} B_{k} \).
Definition at line 87 of file m_base_force_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_div_forces(), check_energy_fluxes::add_field_ctl_4_ene_flux(), check_base_forces::add_field_ctl_4_forces(), check_base_forces::add_field_ctl_4_rot_forces(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_force_vectors(), t_base_force_labels::set_base_force_addresses(), set_base_force_labels(), and m_force_control_labels::set_force_control_labels().
magnetic_induction
type(field_def), parameter m_base_force_labels::magnetic_induction = field_def(n_comp = n_vector, name = 'magnetic_induction', math = '$ e_{ijk} \partial_{j} ' // ' (e_{ijk} u_{j} B_{k})$')
Field label for magnetic induction \(e_{ijk} \partial_{j}\left(e_{klm}u_{l}B_{m} \right)\).
Definition at line 124 of file m_base_force_labels.f90.
Referenced by check_energy_fluxes::add_field_ctl_4_ene_flux(), check_base_forces::add_field_ctl_4_forces(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_force_vectors(), m_force_control_labels::set_advection_control_labels(), t_base_force_labels::set_base_force_addresses(), and set_base_force_labels().
magnetic_stretch
type(field_def), parameter m_base_force_labels::magnetic_stretch = field_def(n_comp = n_vector, name = 'magnetic_stretch', math = '$ B_{j} \partial_{j} u_{i} $')
Field label for magnetic stretch term \(B_{j} \partial_{j} u_{i} \).
Definition at line 131 of file m_base_force_labels.f90.
Referenced by check_energy_fluxes::add_field_ctl_4_ene_flux(), check_base_forces::add_field_ctl_4_forces(), check_force_vectors(), t_base_force_labels::set_base_force_addresses(), and set_base_force_labels().
magnetic_tension
type(field_def), parameter m_base_force_labels::magnetic_tension = field_def(n_comp = n_vector, name = 'magnetic_tension', math = '$ B_{j} \partial_{j} B_{i} $')
start address for magnetic tension \(B_{j} \partial_{j} B_{i} \)
Definition at line 93 of file m_base_force_labels.f90.
Referenced by check_energy_fluxes::add_field_ctl_4_ene_flux(), check_base_forces::add_field_ctl_4_forces(), check_force_vectors(), t_base_force_labels::set_base_force_addresses(), and set_base_force_labels().
maxwell_tensor
type(field_def), parameter m_base_force_labels::maxwell_tensor = field_def(n_comp = n_sym_tensor, name = 'maxwell_tensor', math = '$ B_{i} B_{j} $')
Field label for Maxwell tensor \(B_{i} B_{j} \).
Definition at line 172 of file m_base_force_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_div_forces(), check_base_forces::add_field_ctl_4_forces(), check_flux_tensors(), t_base_force_labels::set_base_force_addresses(), and set_base_force_labels().
momentum_flux
type(field_def), parameter m_base_force_labels::momentum_flux = field_def(n_comp = n_sym_tensor, name = 'momentum_flux', math = '$ u_{i} u_{j} $')
Field label for momentum flux \(u_{i} u_{j} \).
Definition at line 166 of file m_base_force_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_div_forces(), check_base_forces::add_field_ctl_4_forces(), check_flux_tensors(), t_base_force_labels::set_base_force_addresses(), and set_base_force_labels().
nforce_base
integer(kind = kint), parameter, private m_base_force_labels::nforce_base = 21 private
Definition at line 70 of file m_base_force_labels.f90.
Referenced by num_base_forces().
pert_comp_advect
type(field_def), parameter m_base_force_labels::pert_comp_advect = field_def(n_comp = n_scalar, name = 'pert_comp_advect', math = '$ u_{i} \partial_{i} \Theta_{C} $')
Field label for advection for perturbation of composition \(u_{i} \partial_{i} \Theta_{C} \).
Definition at line 158 of file m_base_force_labels.f90.
Referenced by check_energy_fluxes::add_field_ctl_4_ene_flux(), check_base_forces::add_field_ctl_4_forces(), check_scalar_advection(), t_base_force_labels::set_base_force_addresses(), and set_base_force_labels().
pert_comp_flux
type(field_def), parameter m_base_force_labels::pert_comp_flux = field_def(n_comp = n_vector, name = 'pert_comp_flux', math = '$ u_{i} \Theta_{C} $')
Field label for perturbation of composition flux \(u_{i} \Theta_{C} \).
Definition at line 203 of file m_base_force_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_div_forces(), check_base_forces::add_field_ctl_4_forces(), check_force_vectors(), t_base_force_labels::set_base_force_addresses(), and set_base_force_labels().
pert_heat_advect
type(field_def), parameter m_base_force_labels::pert_heat_advect = field_def(n_comp = n_scalar, name = 'pert_heat_advect', math = '$ u_{i} \partial_{i} \Theta $')
Field label for advection for perturbation of temperature \(u_{i} \partial_{i} \Theta \).
Definition at line 145 of file m_base_force_labels.f90.
Referenced by check_energy_fluxes::add_field_ctl_4_ene_flux(), check_base_forces::add_field_ctl_4_forces(), check_scalar_advection(), t_base_force_labels::set_base_force_addresses(), and set_base_force_labels().
pert_heat_flux
type(field_def), parameter m_base_force_labels::pert_heat_flux = field_def(n_comp = n_vector, name = 'pert_heat_flux', math = '$ u_{i} \Theta $')
Field label for perturbation of heat flux \(u_{i} \Theta \).
Definition at line 191 of file m_base_force_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_div_forces(), check_base_forces::add_field_ctl_4_forces(), check_force_vectors(), t_base_force_labels::set_base_force_addresses(), and set_base_force_labels().
pressure_gradient
type(field_def), parameter m_base_force_labels::pressure_gradient = field_def(n_comp = n_vector, name = 'pressure_gradient', math = '$ \partial_{i} p $')
Field label for pressure gradient \(\partial_{i} p \).
Definition at line 74 of file m_base_force_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_field_products(), check_base_forces::add_field_ctl_4_forces(), check_force_vectors(), t_base_force_labels::set_base_force_addresses(), and set_base_force_labels().
vecp_induction
type(field_def), parameter m_base_force_labels::vecp_induction = field_def(n_comp = n_vector, name = 'vecp_induction', math = '$ e_{ijk} u_{j} B_{k} $')
Field label for induction for vector potential \(e_{ijk} u_{j} B_{k} \).
Definition at line 118 of file m_base_force_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_field_products(), check_base_forces::add_field_ctl_4_forces(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_force_vectors(), t_base_force_labels::set_base_force_addresses(), and set_base_force_labels().