CALYPSO: solver_sr_n Module Reference
solver_sr_n Module Reference
MPI SEND and RECEIVE routine for arbitrary components fields in overlapped partitioning.
Functions/Subroutines
subroutine solver_send_recv_n (N, NB, NEIBPETOT, NEIBPE, STACK_IMPORT, NOD_IMPORT, STACK_EXPORT, NOD_EXPORT, SR_sig, SR_r, X)
subroutine solver_send_recv_nx3 (N, NB, NEIBPETOT, NEIBPE, STACK_IMPORT, NOD_IMPORT, STACK_EXPORT, NOD_EXPORT, SR_sig, SR_r, X1, X2, X3)
Detailed Description
MPI SEND and RECEIVE routine for arbitrary components fields in overlapped partitioning.
      subroutine  SOLVER_SEND_RECV_N(N, NB, NEIBPETOT, NEIBPE,        &
     &                               STACK_IMPORT, NOD_IMPORT,        &
     &                               STACK_EXPORT, NOD_EXPORT,        &
     &                               SR_sig, SR_r, X)
      subroutine  SOLVER_SEND_RECV_Nx3(N, NB, NEIBPETOT, NEIBPE,      &
     &                                STACK_IMPORT, NOD_IMPORT,       &
     &                                STACK_EXPORT, NOD_EXPORT,       &
     &                                SR_sig, SR_r, X1, X2, X3)
        type(send_recv_status), intent(inout) :: SR_sig
        type(send_recv_real_buffer), intent(inout) :: SR_r
Parameters
N Number of data points
NB Number of components for communication
Parameters
NEIBPETOT Number of processses to communicate
NEIBPE(NEIBPETOT) Process ID to communicate
STACK_IMPORT(0:NEIBPETOT) End points of import buffer for each process
NOD_IMPORT(STACK_IMPORT(NEIBPETOT)) local node ID to copy in import buffer
STACK_EXPORT(0:NEIBPETOT) End points of export buffer for each process
NOD_EXPORT(STACK_IMPORT(NEIBPETOT)) local node ID to copy in export buffer
Parameters
X(NB*N) field data with NB components
X1(NB*N) 1st field data with NB components
X2(NB*N) 2nd field data with NB components
X3(NB*N) 3rd field data with NB components
Function/Subroutine Documentation
solver_send_recv_n()
subroutine solver_sr_n::solver_send_recv_n (integer(kind=kint), intent(in) N, integer(kind=kint), intent(in) NB, integer(kind=kint), intent(in) NEIBPETOT, integer(kind=kint), dimension(neibpetot), intent(in) NEIBPE, integer(kind=kint), dimension(0:neibpetot), intent(in) STACK_IMPORT, integer(kind=kint), dimension(stack_import(neibpetot)), intent(in) NOD_IMPORT, integer(kind=kint), dimension(0:neibpetot), intent(in) STACK_EXPORT, integer(kind=kint), dimension(stack_export(neibpetot)), intent(in) NOD_EXPORT, type(send_recv_status), intent(inout) SR_sig, type(send_recv_real_buffer), intent(inout) SR_r, real (kind=kreal), dimension(nb*n), intent(inout) X)
Parameters
[in] n number of nodes and number of components
[in] nb number of nodes and number of components
[in] neibpetot total neighboring pe count
[in] neibpe neighboring pe id (i-th pe)
[in] stack_import imported node count for each neighbor pe (i-th pe)
[in] nod_import imported node (i-th dof)
[in] stack_export exported node count for each neighbor pe (i-th pe)
[in] nod_export exported node (i-th dof)
[in,out] x communicated result vector
[in,out] sr_sig Structure of communication flags
[in,out] sr_r Structure of communication buffer for 8-byte real
Definition at line 57 of file solver_SR_N.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_real, calypso_mpi::ierr_mpi, and t_solver_sr::resize_work_sr().
Referenced by solver_sr_type::solver_send_recv_n_type().
solver_send_recv_nx3()
subroutine solver_sr_n::solver_send_recv_nx3 (integer(kind=kint), intent(in) N, integer(kind=kint), intent(in) NB, integer(kind=kint), intent(in) NEIBPETOT, integer(kind=kint), dimension(neibpetot), intent(in) NEIBPE, integer(kind=kint), dimension(0:neibpetot), intent(in) STACK_IMPORT, integer(kind=kint), dimension(stack_import(neibpetot)), intent(in) NOD_IMPORT, integer(kind=kint), dimension(0:neibpetot), intent(in) STACK_EXPORT, integer(kind=kint), dimension(stack_export(neibpetot)), intent(in) NOD_EXPORT, type(send_recv_status), intent(inout) SR_sig, type(send_recv_real_buffer), intent(inout) SR_r, real (kind=kreal), dimension(nb*n), intent(inout) X1, real (kind=kreal), dimension(nb*n), intent(inout) X2, real (kind=kreal), dimension(nb*n), intent(inout) X3)
Parameters
[in,out] sr_sig Structure of communication flags
[in,out] sr_r Structure of communication buffer for 8-byte real
Definition at line 147 of file solver_SR_N.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_real, calypso_mpi::ierr_mpi, and t_solver_sr::resize_work_sr().
Referenced by solver_sr_type::solver_send_recv_nx3_type().