CALYPSO: const_fdm_coefs Module Reference
const_fdm_coefs Module Reference
Coefficients to obtain radial derivatives by finite difference method.
Functions/Subroutines
subroutine const_2nd_fdm_matrices (sph_params, sph_rj, r_2nd)
subroutine const_4th_fdm_coefs (nlayer_ICB, sph_rj, r_4th)
subroutine const_2e_fdm_coefs (nlayer_ICB, sph_rj, r_2nd_ele)
Detailed Description
Coefficients to obtain radial derivatives by finite difference method.
      subroutine const_2nd_fdm_matrices(sph_params, sph_rj, r_2nd)
        type(sph_rj_grid), intent(in) :: sph_rj
        type(fdm_matrices), intent(inout) :: r_2nd
 -------------------------------------------------------------------&mdash;
      Coeeficients for derivatives by 1d finite difference method
    2nd order derivatives on node by nodal field
      dfdr =    r_2nd%fdm(1)%dmat(-1) * d_nod(k-1)
              + r_2nd%fdm(1)%dmat( 0) * d_nod(k  )
              + r_2nd%fdm(1)%dmat( 1) * d_nod(k+1)
      d2fdr2 =  r_2nd%fdm(2)%dmat(-1) * d_nod(k-1)
              + r_2nd%fdm(2)%dmat( 0) * d_nod(k  )
              + r_2nd%fdm(2)%dmat( 1) * d_nod(k+1)
       r_2nd%fdm(1)%dmat = d1nod_mat_fdm_2
       r_2nd%fdm(2)%dmat = d2nod_mat_fdm_2
Function/Subroutine Documentation
const_2e_fdm_coefs()
subroutine const_fdm_coefs::const_2e_fdm_coefs (integer(kind = kint), intent(in) nlayer_ICB, type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(inout) r_2nd_ele)
Definition at line 209 of file const_fdm_coefs.f90.
References t_fdm_coefs::alloc_fdm_work(), t_fdm_coefs::alloc_nod_fdm_matrices(), cal_sph_exp_1st_diff_ele::cal_2nd_ele_r_fdm_coefs(), t_fdm_coefs::copy_fdm2_ele_coefs_from_mat(), t_fdm_coefs::dealloc_fdm_work(), and m_constants::ione.
const_2nd_fdm_matrices()
subroutine const_fdm_coefs::const_2nd_fdm_matrices (type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(inout) r_2nd)
Definition at line 151 of file const_fdm_coefs.f90.
References t_fdm_coefs::alloc_fdm_work(), t_fdm_coefs::alloc_nod_fdm_matrices(), t_fdm_coefs::check_fdm_coefs(), t_fdm_coefs::copy_fdm2_nod_coefs_from_mat(), t_fdm_coefs::dealloc_fdm_work(), set_radius_func_noequi::deallocate_dr_rj_noequi(), m_constants::itwo, and set_radius_func_noequi::nod_r_2nd_fdm_coefs_nonequi().
Referenced by init_radial_infos_sph_mhd::init_r_infos_sph_mhd_evo().
const_4th_fdm_coefs()
subroutine const_fdm_coefs::const_4th_fdm_coefs (integer(kind = kint), intent(in) nlayer_ICB, type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(inout) r_4th)
Definition at line 180 of file const_fdm_coefs.f90.
References t_fdm_coefs::alloc_fdm_work(), t_fdm_coefs::alloc_nod_fdm_matrices(), t_fdm_coefs::check_fdm_coefs(), t_fdm_coefs::copy_fdm4_nod_coefs_from_mat(), t_fdm_coefs::dealloc_fdm_work(), m_constants::ifour, and const_radial_4th_fdm_noequi::nod_r_4th_fdm_coefs_nonequi().