CALYPSO: rot_self_buoyancies_sph Module Reference
rot_self_buoyancies_sph Module Reference
Evaluate rotation of buoyancy.
Functions/Subroutines
subroutine sel_rot_self_buoyancy_sph (sph_rj, ipol_base, ipol_rot_frc, fl_prop, sph_bc_U, rj_fld)
subroutine, private cal_rot_double_buoyancy_sph_mhd (kr_in, kr_out, coef_t_buo, is_t, coef_c_buo, is_c, it_res, nidx_rj, radius_1d_rj_r, nnod_rj, ntot_phys_rj, d_rj)
subroutine cal_rot_buoyancy_sph_mhd (kr_in, kr_out, coef, is_fld, it_res, nidx_rj, radius_1d_rj_r, nnod_rj, ntot_phys_rj, d_rj)
subroutine cal_boussinesq_density_sph (ipol, kr_in, kr_out, coef_buo, coef_comp_buo, nidx_rj, nnod_rj, ntot_phys_rj, d_rj)
Detailed Description
Evaluate rotation of buoyancy.
      subroutine sel_rot_self_buoyancy_sph(sph_rj,                    &
     &          ipol_base, ipol_rot_frc, fl_prop, sph_bc_U, rj_fld)
        type(fluid_property), intent(in) :: fl_prop
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(base_field_address), intent(in) :: ipol_base
        type(base_force_address), intent(in) :: ipol_rot_frc
        type(sph_boundary_type), intent(in) :: sph_bc_U
        type(phys_data), intent(inout) :: rj_fld
      subroutine cal_rot_radial_self_gravity                          &
     &         (sph_rj, ipol, fl_prop, sph_bc_U, rj_fld)
        type(fluid_property), intent(in) :: fl_prop
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(phys_address), intent(in) :: ipol
        type(sph_boundary_type), intent(in) :: sph_bc_U
        type(phys_data), intent(inout) :: rj_fld
      subroutine cal_rot_buoyancy_sph_MHD(kr_in, kr_out, coef,        &
     &          is_fld, it_res, nidx_rj, radius_1d_rj_r,              &
     &          nnod_rj, ntot_phys_rj, d_rj)
      subroutine cal_boussinesq_density_sph                           &
     &         (ipol, kr_in, kr_out, coef_buo, coef_comp_buo,         &
     &          nidx_rj, nnod_rj, ntot_phys_rj, d_rj)
        type(phys_address), intent(in) :: ipol
Parameters
sph_bc_U Structure for basic velocity boundary condition parameters
kr_in Radial ID for inner boundary
kr_out Radial ID for outer boundary
Function/Subroutine Documentation
cal_boussinesq_density_sph()
subroutine rot_self_buoyancies_sph::cal_boussinesq_density_sph (type(phys_address), intent(in) ipol, integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) kr_out, real(kind = kreal), intent(in) coef_buo, real(kind = kreal), intent(in) coef_comp_buo, integer(kind = kint), dimension(2), intent(in) nidx_rj, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 179 of file rot_self_buoyancies_sph.f90.
cal_rot_buoyancy_sph_mhd()
subroutine rot_self_buoyancies_sph::cal_rot_buoyancy_sph_mhd (integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) kr_out, real(kind = kreal), intent(in) coef, integer(kind= kint), intent(in) is_fld, integer(kind= kint), intent(in) it_res, integer(kind = kint), dimension(2), intent(in) nidx_rj, real(kind = kreal), dimension(nidx_rj(1)), intent(in) radius_1d_rj_r, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 148 of file rot_self_buoyancies_sph.f90.
Referenced by sel_rot_self_buoyancy_sph().
cal_rot_double_buoyancy_sph_mhd()
subroutine, private rot_self_buoyancies_sph::cal_rot_double_buoyancy_sph_mhd (integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) kr_out, real(kind = kreal), intent(in) coef_t_buo, integer(kind= kint), intent(in) is_t, real(kind = kreal), intent(in) coef_c_buo, integer(kind= kint), intent(in) is_c, integer(kind= kint), intent(in) it_res, integer(kind = kint), dimension(2), intent(in) nidx_rj, real(kind = kreal), dimension(nidx_rj(1)), intent(in) radius_1d_rj_r, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj) private
Definition at line 115 of file rot_self_buoyancies_sph.f90.
Referenced by sel_rot_self_buoyancy_sph().
sel_rot_self_buoyancy_sph()
subroutine rot_self_buoyancies_sph::sel_rot_self_buoyancy_sph (type(sph_rj_grid), intent(in) sph_rj, type(base_field_address), intent(in) ipol_base, type(base_force_address), intent(in) ipol_rot_frc, type(fluid_property), intent(in) fl_prop, type(sph_boundary_type), intent(in) sph_bc_U, type(phys_data), intent(inout) rj_fld)
Definition at line 57 of file rot_self_buoyancies_sph.f90.
References cal_rot_buoyancy_sph_mhd(), cal_rot_double_buoyancy_sph_mhd(), and m_machine_parameter::iflag_debug.
Referenced by cal_nonlinear::licv_exp(), and cal_nonlinear::nonlinear().