CALYPSO: analyzer_gen_sph_grids Module Reference
analyzer_gen_sph_grids Module Reference
Main loop to generate spherical harmonics indices.
Functions/Subroutines
subroutine init_gen_sph_grids
subroutine analyze_gen_sph_grids
Variables
character(len=kchara), parameter, private control_file_name = 'control_sph_shell'
type(sph_mesh_generation_ctl), save, private sph_make_ctl
Structure for file settings.
type(sph_grids), save, private sph_const
Structure of grid and spectr data for spherical spectr method.
type(sph_comm_tables), save, private comms_sph_const
Structure of communication table for spherical spectr method.
type(sph_group_data), save, private sph_grp_const
Structure of group data for spherical spectr method.
type(gen_sph_file_io_params), save sph_files1
Structure of mesh file name and formats.
type(sph_grid_maker_in_sim), save sph_maker_g
Structure to check and construct spherical shell mesh.
type(mesh_data), save, private geofem
Structure of FEM mesh.
type(parallel_make_vierwer_mesh), save, private para_v1
Detailed Description
Main loop to generate spherical harmonics indices.
      subroutine init_gen_sph_grids
      subroutine analyze_gen_sph_grids
Function/Subroutine Documentation
analyze_gen_sph_grids()
subroutine analyzer_gen_sph_grids::analyze_gen_sph_grids
Definition at line 98 of file analyzer_gen_sph_grids.f90.
References calypso_mpi::calypso_mpi_barrier(), comms_sph_const, t_check_and_make_sph_mesh::const_fem_mesh_4_sph(), parallel_load_data_4_sph::dealloc_sph_modes(), m_work_time::end_elapsed_time(), geofem, m_work_time::ied_total_elapsed, m_machine_parameter::iflag_debug, m_elapsed_labels_gen_sph::iflag_gsp_time, m_elapsed_labels_gen_sph::ist_elapsed_gsp, mpi_gen_sph_grids_modes::mpi_gen_sph_grids(), m_work_time::output_elapsed_times(), parallel_load_data_4_sph::output_sph_mesh(), para_v1, para_const_kemoview_mesh::pickup_surface_mesh(), sph_const, sph_files1, sph_grp_const, parallel_load_data_4_sph::sph_index_flags_and_params(), sph_maker_g, and m_work_time::start_elapsed_time().
Referenced by generate_sph_grids().
init_gen_sph_grids()
subroutine analyzer_gen_sph_grids::init_gen_sph_grids
Definition at line 67 of file analyzer_gen_sph_grids.f90.
References calypso_mpi::calypso_mpi_abort(), control_file_name, m_machine_parameter::e_message, m_elapsed_labels_gen_sph::elpsed_label_gen_sph_grid(), m_work_time::ied_total_elapsed, m_error_ids::ierr_p_mpi, m_work_time::init_elapse_time_by_total(), calypso_mpi::my_rank, calypso_mpi::nprocs, t_ctl_data_const_sph_mesh::read_control_4_const_shell(), t_ctl_params_gen_sph_shell::set_control_4_gen_shell_grids(), sph_files1, sph_make_ctl, sph_maker_g, and m_work_time::start_elapsed_time().
Referenced by generate_sph_grids().
Variable Documentation
comms_sph_const
type(sph_comm_tables), save, private analyzer_gen_sph_grids::comms_sph_const private
Structure of communication table for spherical spectr method.
Definition at line 47 of file analyzer_gen_sph_grids.f90.
Referenced by analyze_gen_sph_grids().
control_file_name
character (len = kchara), parameter, private analyzer_gen_sph_grids::control_file_name = 'control_sph_shell' private
Definition at line 37 of file analyzer_gen_sph_grids.f90.
Referenced by init_gen_sph_grids().
geofem
type(mesh_data), save, private analyzer_gen_sph_grids::geofem private
Structure of FEM mesh.
Definition at line 57 of file analyzer_gen_sph_grids.f90.
Referenced by analyze_gen_sph_grids().
para_v1
type(parallel_make_vierwer_mesh), save, private analyzer_gen_sph_grids::para_v1 private
Definition at line 59 of file analyzer_gen_sph_grids.f90.
Referenced by analyze_gen_sph_grids().
sph_const
type(sph_grids), save, private analyzer_gen_sph_grids::sph_const private
Structure of grid and spectr data for spherical spectr method.
Definition at line 45 of file analyzer_gen_sph_grids.f90.
Referenced by analyze_gen_sph_grids().
sph_files1
type(gen_sph_file_io_params), save analyzer_gen_sph_grids::sph_files1
Structure of mesh file name and formats.
Definition at line 51 of file analyzer_gen_sph_grids.f90.
Referenced by analyze_gen_sph_grids(), and init_gen_sph_grids().
sph_grp_const
type(sph_group_data), save, private analyzer_gen_sph_grids::sph_grp_const private
Structure of group data for spherical spectr method.
Definition at line 49 of file analyzer_gen_sph_grids.f90.
Referenced by analyze_gen_sph_grids().
sph_make_ctl
type(sph_mesh_generation_ctl), save, private analyzer_gen_sph_grids::sph_make_ctl private
Structure for file settings.
Definition at line 42 of file analyzer_gen_sph_grids.f90.
Referenced by init_gen_sph_grids().
sph_maker_g
type(sph_grid_maker_in_sim), save analyzer_gen_sph_grids::sph_maker_g
Structure to check and construct spherical shell mesh.
Definition at line 54 of file analyzer_gen_sph_grids.f90.
Referenced by analyze_gen_sph_grids(), and init_gen_sph_grids().