CALYPSO: m_t_step_parameter Module Reference
m_t_step_parameter Module Reference
Variables
real(kind=kreal), parameter adam_0 = three / two
Coefficient of terms at current step for Adams-Bashforth.
real(kind=kreal), parameter adam_1 = -one / two
Coefficient of terms at previous step for Adams-Bashforth.
real(kind=kreal), parameter adam_r = two / three
1 / adam_0
Variable Documentation
adam_0
real(kind=kreal), parameter m_t_step_parameter::adam_0 = three / two
Coefficient of terms at current step for Adams-Bashforth.
Definition at line 20 of file m_t_step_parameter.f90.
Referenced by cal_explicit_terms::cal_diff_induction_mhd_adams(), cal_vorticity_terms_adams::cal_vorticity_eq_adams(), cal_diff_adv_src_explicit::center_scl_diff_adv_src_adams(), cal_diff_adv_src_explicit::scalar_diff_adv_src_adams(), and cal_diff_adv_src_explicit::scalar_diff_advect_adams().
adam_1
real(kind=kreal), parameter m_t_step_parameter::adam_1 = -one / two
Coefficient of terms at previous step for Adams-Bashforth.
Definition at line 22 of file m_t_step_parameter.f90.
Referenced by cal_explicit_terms::cal_diff_induction_mhd_adams(), cal_vorticity_terms_adams::cal_vorticity_eq_adams(), cal_diff_adv_src_explicit::center_scl_diff_adv_src_adams(), cal_diff_adv_src_explicit::scalar_diff_adv_src_adams(), and cal_diff_adv_src_explicit::scalar_diff_advect_adams().
adam_r
real(kind=kreal), parameter m_t_step_parameter::adam_r = two / three
1 / adam_0
Definition at line 24 of file m_t_step_parameter.f90.