CALYPSO: calypso_sr Module Reference
calypso_sr Module Reference
scalar components data communication
Functions/Subroutines
subroutine calypso_send_recv (iflag_recv, nnod_org, nnod_new, npe_send, isend_self, id_pe_send, istack_send, inod_export, npe_recv, irecv_self, id_pe_recv, istack_recv, inod_import, irev_import, SR_sig, SR_r, X_org, X_new)
subroutine calypso_send_recv_3x1 (iflag_recv, nnod_org, nnod_new, npe_send, isend_self, id_pe_send, istack_send, inod_export, npe_recv, irecv_self, id_pe_recv, istack_recv, inod_import, irev_import, SR_sig, SR_r, X1_org, X2_org, X3_org, X1_new, X2_new, X3_new)
Detailed Description
scalar components data communication
      subroutine calypso_send_recv(iflag_recv, nnod_org, nnod_new,    &
     &                         npe_send, isend_self,                  &
     &                         id_pe_send, istack_send, inod_export,  &
     &                         npe_recv, irecv_self,                  &
     &                         id_pe_recv, istack_recv, inod_import,  &
     &                         irev_import, SR_sig, SR_r,             &
     &                         X_org, X_new)
      subroutine calypso_send_recv_3x1(iflag_recv, nnod_org, nnod_new,&
     &                         npe_send, isend_self,                  &
     &                         id_pe_send, istack_send, inod_export,  &
     &                         npe_recv, irecv_self,                  &
     &                         id_pe_recv, istack_recv, inod_import,  &
     &                         irev_import, SR_sig, SR_r,             &
     &                         X1_org, X2_org, X3_org,                &
     &                         X1_new, X2_new, X3_new)
        type(send_recv_status), intent(inout) :: SR_sig
        type(send_recv_real_buffer), intent(inout) :: SR_r
Parameters
nnod_org Number of data points for origin
nnod_new Number of components for destination
npe_send Number of processses to send
isend_self Integer flag to copy within own process
id_pe_send(npe_send) Process ID to send
istack_send(0:npe_send) End points of send buffer for each process
inod_export(istack_send(npe_send)) local node ID to copy in send buffer
npe_recv Number of processses to receive
irecv_self Integer flag to copy within own process
id_pe_recv(npe_send) Process ID to receive
istack_recv(0:npe_send) End points of receive buffer for each process
inod_import(istack_recv(npe_recv)) local node ID to copy from receive buffer
irev_import(nnod_new) import buffer ID for each data point
X_org(nnod_org) Send data
X_new(nnod_new) Received data
Function/Subroutine Documentation
calypso_send_recv()
subroutine calypso_sr::calypso_send_recv (integer(kind = kint), intent(in) iflag_recv, integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) npe_send, integer(kind = kint), intent(in) isend_self, integer(kind = kint), dimension(npe_send), intent(in) id_pe_send, integer(kind = kint), dimension(0:npe_send), intent(in) istack_send, integer(kind = kint), dimension(istack_send(npe_send)), intent(in) inod_export, integer(kind = kint), intent(in) npe_recv, integer(kind = kint), intent(in) irecv_self, integer(kind = kint), dimension(npe_recv), intent(in) id_pe_recv, integer(kind = kint), dimension(0:npe_recv), intent(in) istack_recv, integer(kind = kint), dimension(istack_recv(npe_recv)), intent(in) inod_import, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, type(send_recv_status), intent(inout) SR_sig, type(send_recv_real_buffer), intent(inout) SR_r, real (kind=kreal), dimension(nnod_org), intent(in) X_org, real (kind=kreal), dimension(nnod_new), intent(inout) X_new)
Parameters
[in,out] sr_sig Structure of communication flags
[in,out] sr_r Structure of communication buffer for 8-byte real
Definition at line 68 of file calypso_SR.f90.
References calypso_sr_core::calypso_send_recv_core(), t_solver_sr::calypso_send_recv_fin(), m_constants::ione, t_solver_sr::resize_work_sr(), select_copy_from_recv::sel_cppy_from_recv_buf_1(), and set_to_send_buffer::set_to_send_buf_1().
Referenced by spherical_srs_n::send_recv_sph_trans().
calypso_send_recv_3x1()
subroutine calypso_sr::calypso_send_recv_3x1 (integer(kind = kint), intent(in) iflag_recv, integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) npe_send, integer(kind = kint), intent(in) isend_self, integer(kind = kint), dimension(npe_send), intent(in) id_pe_send, integer(kind = kint), dimension(0:npe_send), intent(in) istack_send, integer(kind = kint), dimension(istack_send(npe_send)), intent(in) inod_export, integer(kind = kint), intent(in) npe_recv, integer(kind = kint), intent(in) irecv_self, integer(kind = kint), dimension(npe_recv), intent(in) id_pe_recv, integer(kind = kint), dimension(0:npe_recv), intent(in) istack_recv, integer(kind = kint), dimension(istack_recv(npe_recv)), intent(in) inod_import, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, type(send_recv_status), intent(inout) SR_sig, type(send_recv_real_buffer), intent(inout) SR_r, real (kind=kreal), dimension(nnod_org), intent(in) X1_org, real (kind=kreal), dimension(nnod_org), intent(in) X2_org, real (kind=kreal), dimension(nnod_org), intent(in) X3_org, real (kind=kreal), dimension(nnod_new), intent(inout) X1_new, real (kind=kreal), dimension(nnod_new), intent(inout) X2_new, real (kind=kreal), dimension(nnod_new), intent(inout) X3_new)
Parameters
[in,out] sr_sig Structure of communication flags
[in,out] sr_r Structure of communication buffer for 8-byte real
Definition at line 132 of file calypso_SR.f90.
References calypso_sr_core::calypso_send_recv_core(), t_solver_sr::calypso_send_recv_fin(), m_constants::ithree, t_solver_sr::resize_work_sr(), select_copy_from_recv::sel_cppy_from_recv_buf_3x1(), and set_to_send_buf_tri::set_to_send_buf_3x1().