CALYPSO: output_sph_m_square_file Module Reference
output_sph_m_square_file Module Reference
Output mean square of spectr data.
Functions/Subroutines
subroutine write_total_energy_to_screen (id_rank, time_d, pwr)
subroutine write_sph_vol_ave_file (ene_labels, time_d, sph_params, sph_rj, pwr)
integer(kind=kint) function check_sph_vol_ms_file (id_rank, ene_labels, sph_params, sph_rj, pwr)
subroutine write_sph_vol_ms_file (id_rank, ene_labels, time_d, sph_params, sph_rj, pwr)
subroutine write_sph_vol_ms_spectr_file (id_rank, ene_labels, time_d, sph_params, sph_rj, pwr)
subroutine write_sph_layer_ms_file (id_rank, ene_labels, time_d, sph_params, pwr)
subroutine write_sph_layer_spectr_file (id_rank, ene_labels, time_d, sph_params, pwr)
subroutine, private write_sph_volume_spec_file (fname_rms, mode_label, ene_labels, time_d, sph_params, sph_rj, v_pwr, rms_sph_x)
subroutine, private write_sph_volume_pwr_file (fname_rms, mode_label, ene_labels, time_d, sph_params, sph_rj, v_pwr, rms_sph_v)
subroutine, private write_sph_layer_pwr_file (fname_rms, mode_label, ene_labels, time_d, ltr, nlayer_ICB, nlayer_CMB, pwr, rms_sph)
subroutine, private write_sph_layer_spec_file (fname_rms, mode_label, ene_labels, time_d, ltr, nlayer_ICB, nlayer_CMB, pwr, rms_sph_x)
Variables
integer(kind=kint), parameter, private id_file_rms = 34
File ID for mean square data.
Detailed Description
Output mean square of spectr data.
      subroutine write_total_energy_to_screen(id_rank, time_d, pwr)
      subroutine write_sph_vol_ave_file                               &
     &         (ene_labels, time_d, sph_params, sph_rj, pwr)
        type(energy_label_param), intent(in) :: ene_labels
        type(time_data), intent(in) :: time_d
        type(sph_shell_parameters), intent(in) :: sph_params
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(sph_mean_squares), intent(in) :: pwr
      integer(kind = kint) function check_sph_vol_ms_file             &
     &             (id_rank, ene_labels, sph_params, sph_rj, pwr)
      subroutine write_sph_vol_ms_file                                &
     &         (id_rank, ene_labels, time_d, sph_params, sph_rj, pwr)
      subroutine write_sph_vol_ms_spectr_file                         &
     &         (id_rank, ene_labels, time_d, sph_params, sph_rj, pwr)
      subroutine write_sph_layer_ms_file                              &
     &         (id_rank, ene_labels, time_d, sph_params, pwr)
      subroutine write_sph_layer_spectr_file                          &
     &         (id_rank, ene_labels, time_d, sph_params, pwr)
        type(energy_label_param), intent(in) :: ene_labels
        type(time_data), intent(in) :: time_d
        type(sph_shell_parameters), intent(in) :: sph_params
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(sph_mean_squares), intent(in) :: pwr
Parameters
id_rank Process ID
istep time step number
time time
Function/Subroutine Documentation
check_sph_vol_ms_file()
integer(kind = kint) function output_sph_m_square_file::check_sph_vol_ms_file (integer, intent(in) id_rank, type(energy_label_param), intent(in) ene_labels, type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(sph_mean_squares), intent(in) pwr)
Definition at line 145 of file output_sph_m_square_file.f90.
References sph_mean_spectr_io::check_sph_vol_mean_sq_file(), and id_file_rms.
Referenced by t_sph_mhd_monitor_data_io::open_sph_vol_rms_file_mhd().
write_sph_layer_ms_file()
subroutine output_sph_m_square_file::write_sph_layer_ms_file (integer, intent(in) id_rank, type(energy_label_param), intent(in) ene_labels, type(time_data), intent(in) time_d, type(sph_shell_parameters), intent(in) sph_params, type(sph_mean_squares), intent(in) pwr)
Definition at line 280 of file output_sph_m_square_file.f90.
References m_constants::izero, and write_sph_layer_pwr_file().
Referenced by cal_write_sph_monitor_data::output_sph_mean_square_files().
write_sph_layer_pwr_file()
subroutine, private output_sph_m_square_file::write_sph_layer_pwr_file (character(len=kchara), intent(in) fname_rms, character(len=kchara), intent(in) mode_label, type(energy_label_param), intent(in) ene_labels, type(time_data), intent(in) time_d, integer(kind = kint), intent(in) ltr, integer(kind = kint), intent(in) nlayer_ICB, integer(kind = kint), intent(in) nlayer_CMB, type(sph_mean_squares), intent(in) pwr, real(kind = kreal), dimension(pwr%nri_rms,pwr%ntot_comp_sq), intent(in) rms_sph) private
Definition at line 431 of file output_sph_m_square_file.f90.
References id_file_rms, sph_mean_spectr_io::open_sph_mean_sq_file(), and sph_mean_spectr_io::write_sph_layerd_power().
Referenced by write_sph_layer_ms_file(), and write_sph_layer_spectr_file().
write_sph_layer_spec_file()
subroutine, private output_sph_m_square_file::write_sph_layer_spec_file (character(len=kchara), intent(in) fname_rms, character(len=kchara), intent(in) mode_label, type(energy_label_param), intent(in) ene_labels, type(time_data), intent(in) time_d, integer(kind = kint), intent(in) ltr, integer(kind = kint), intent(in) nlayer_ICB, integer(kind = kint), intent(in) nlayer_CMB, type(sph_mean_squares), intent(in) pwr, real(kind = kreal), dimension(pwr%nri_rms,0:ltr,pwr%ntot_comp_sq), intent(in) rms_sph_x) private
Definition at line 456 of file output_sph_m_square_file.f90.
References id_file_rms, sph_mean_spectr_io::open_sph_mean_sq_file(), and sph_mean_spectr_io::write_sph_layer_data().
Referenced by write_sph_layer_spectr_file().
write_sph_layer_spectr_file()
subroutine output_sph_m_square_file::write_sph_layer_spectr_file (integer, intent(in) id_rank, type(energy_label_param), intent(in) ene_labels, type(time_data), intent(in) time_d, type(sph_shell_parameters), intent(in) sph_params, type(sph_mean_squares), intent(in) pwr)
Definition at line 313 of file output_sph_m_square_file.f90.
References m_constants::izero, write_sph_layer_pwr_file(), and write_sph_layer_spec_file().
Referenced by cal_write_sph_monitor_data::output_sph_mean_square_files().
write_sph_vol_ave_file()
subroutine output_sph_m_square_file::write_sph_vol_ave_file (type(energy_label_param), intent(in) ene_labels, type(time_data), intent(in) time_d, type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(sph_mean_squares), intent(in) pwr)
Definition at line 105 of file output_sph_m_square_file.f90.
References set_parallel_file_name::add_dat_extension(), id_file_rms, and sph_mean_spectr_io::open_sph_vol_mean_sq_file().
Referenced by cal_write_sph_monitor_data::output_sph_mean_square_files().
write_sph_vol_ms_file()
subroutine output_sph_m_square_file::write_sph_vol_ms_file (integer, intent(in) id_rank, type(energy_label_param), intent(in) ene_labels, type(time_data), intent(in) time_d, type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(sph_mean_squares), intent(in) pwr)
Definition at line 177 of file output_sph_m_square_file.f90.
References write_sph_volume_pwr_file().
Referenced by cal_write_sph_monitor_data::output_sph_mean_square_files().
write_sph_vol_ms_spectr_file()
subroutine output_sph_m_square_file::write_sph_vol_ms_spectr_file (integer, intent(in) id_rank, type(energy_label_param), intent(in) ene_labels, type(time_data), intent(in) time_d, type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(sph_mean_squares), intent(in) pwr)
Definition at line 213 of file output_sph_m_square_file.f90.
References write_sph_volume_pwr_file(), and write_sph_volume_spec_file().
Referenced by cal_write_sph_monitor_data::output_sph_mean_square_files().
write_sph_volume_pwr_file()
subroutine, private output_sph_m_square_file::write_sph_volume_pwr_file (character(len=kchara), intent(in) fname_rms, character(len=kchara), intent(in) mode_label, type(energy_label_param), intent(in) ene_labels, type(time_data), intent(in) time_d, type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(sph_vol_mean_squares), intent(in) v_pwr, real(kind = kreal), dimension(v_pwr%ntot_comp_sq), intent(in) rms_sph_v) private
Definition at line 402 of file output_sph_m_square_file.f90.
References id_file_rms, and sph_mean_spectr_io::open_sph_vol_mean_sq_file().
Referenced by write_sph_vol_ms_file(), and write_sph_vol_ms_spectr_file().
write_sph_volume_spec_file()
subroutine, private output_sph_m_square_file::write_sph_volume_spec_file (character(len=kchara), intent(in) fname_rms, character(len=kchara), intent(in) mode_label, type(energy_label_param), intent(in) ene_labels, type(time_data), intent(in) time_d, type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(sph_vol_mean_squares), intent(in) v_pwr, real(kind = kreal), dimension(0:sph_params%l_truncation, v_pwr%ntot_comp_sq), intent(in) rms_sph_x) private
Definition at line 374 of file output_sph_m_square_file.f90.
References id_file_rms, sph_mean_spectr_io::open_sph_vol_mean_sq_file(), and sph_mean_spectr_io::write_sph_volume_data().
Referenced by write_sph_vol_ms_spectr_file().
write_total_energy_to_screen()
subroutine output_sph_m_square_file::write_total_energy_to_screen (integer, intent(in) id_rank, type(time_data), intent(in) time_d, type(sph_mean_squares), intent(in) pwr)
Definition at line 65 of file output_sph_m_square_file.f90.
References m_base_field_labels::magnetic_field, and m_base_field_labels::velocity.
Referenced by cal_write_sph_monitor_data::output_sph_monitor_data().
Variable Documentation
id_file_rms
integer(kind = kint), parameter, private output_sph_m_square_file::id_file_rms = 34 private
File ID for mean square data.
Definition at line 54 of file output_sph_m_square_file.f90.
Referenced by check_sph_vol_ms_file(), write_sph_layer_pwr_file(), write_sph_layer_spec_file(), write_sph_vol_ave_file(), write_sph_volume_pwr_file(), and write_sph_volume_spec_file().