CALYPSO: set_connects_4_surf_group Module Reference
set_connects_4_surf_group Module Reference
Functions/Subroutines
subroutine set_surf_id_4_surf_group (ele, surf, surf_grp, sf_grp_tbl)
subroutine set_edge_4_surf_group (surf, edge, surf_grp, sf_grp_tbl)
subroutine set_node_4_surf_group (nod, ele, surf, sf_grp, sf_nod)
subroutine cal_surf_normal_at_nod (node, ele, surf, sf_grp, sf_grp_v, sf_nod)
subroutine empty_sf_ed_nod_surf_grp_type (surf_grp, sf_grp_tbl)
subroutine empty_surface_node_grp_type (sf_grp, sf_nod)
Function/Subroutine Documentation
cal_surf_normal_at_nod()
subroutine set_connects_4_surf_group::cal_surf_normal_at_nod (type(node_data), intent(in) node, type(element_data), intent(in) ele, type(surface_data), intent(in) surf, type(surface_group_data), intent(in) sf_grp, type(surface_group_geometry), intent(in) sf_grp_v, type(surface_node_grp_data), intent(inout) sf_nod)
Definition at line 183 of file set_connects_4_surf_group.f90.
References t_surface_group_connect::alloc_vect_surf_grp_nod(), set_norm_nod_4_surf_grp::allocate_work_norm_nod(), set_norm_nod_4_surf_grp::cal_surf_grp_norm_node(), and set_norm_nod_4_surf_grp::deallocate_work_norm_nod().
empty_sf_ed_nod_surf_grp_type()
subroutine set_connects_4_surf_group::empty_sf_ed_nod_surf_grp_type (type(surface_group_data), intent(in) surf_grp, type(surface_group_table), intent(inout) sf_grp_tbl)
Definition at line 219 of file set_connects_4_surf_group.f90.
References t_group_connects::alloc_item_other_grp(), t_group_connects::alloc_num_other_grp(), and t_group_connects::alloc_surf_item_sf_grp_type().
Referenced by const_mesh_information::empty_mesh_info().
empty_surface_node_grp_type()
subroutine set_connects_4_surf_group::empty_surface_node_grp_type (type(surface_group_data), intent(in) sf_grp, type(surface_node_grp_data), intent(inout) sf_nod)
Definition at line 238 of file set_connects_4_surf_group.f90.
References t_surface_group_connect::alloc_item_surf_grp_nod(), and t_surface_group_connect::alloc_num_surf_grp_nod().
Referenced by const_mesh_information::empty_mesh_info().
set_edge_4_surf_group()
subroutine set_connects_4_surf_group::set_edge_4_surf_group (type(surface_data), intent(in) surf, type(edge_data), intent(in) edge, type(surface_group_data), intent(in) surf_grp, type(surface_group_table), intent(inout) sf_grp_tbl)
Definition at line 82 of file set_connects_4_surf_group.f90.
References t_group_connects::alloc_item_other_grp(), t_group_connects::alloc_num_other_grp(), set_node_4_group::count_nod_4_ele_grp(), m_geometry_constants::nedge_4_surf, and set_node_4_group::set_nod_4_ele_grp().
Referenced by const_mesh_information::const_group_type_info().
set_node_4_surf_group()
subroutine set_connects_4_surf_group::set_node_4_surf_group (type(node_data), intent(in) nod, type(element_data), intent(in) ele, type(surface_data), intent(in) surf, type(surface_group_data), intent(in) sf_grp, type(surface_node_grp_data), intent(inout) sf_nod)
Definition at line 128 of file set_connects_4_surf_group.f90.
References t_surface_group_connect::alloc_item_surf_grp_nod(), t_surface_group_connect::alloc_num_surf_grp_nod(), t_surface_group_connect::alloc_num_surf_grp_nod_smp(), set_surface_node::allocate_make_4_surf_nod_grp(), set_surface_node::count_surf_nod_grp_stack(), set_surface_node::deallocate_make_4_surf_nod_grp(), m_machine_parameter::np_smp, cal_minmax_and_stacks::set_group_size_4_smp(), and set_surface_node::set_surf_nod_grp_item().
Referenced by const_mesh_information::const_mesh_infos().
set_surf_id_4_surf_group()
subroutine set_connects_4_surf_group::set_surf_id_4_surf_group (type(element_data), intent(in) ele, type(surface_data), intent(in) surf, type(surface_group_data), intent(in) surf_grp, type(surface_group_table), intent(inout) sf_grp_tbl)
Definition at line 56 of file set_connects_4_surf_group.f90.
References t_group_connects::alloc_surf_item_sf_grp_type(), and set_surface_id_4_surf_grp::set_surface_id_4_surf_group().
Referenced by const_mesh_information::const_group_type_info().