CALYPSO: test_legendre_transforms Module Reference
test_legendre_transforms Module Reference
Perform spherical harmonics transform for MHD dynamo model.
Functions/Subroutines
subroutine s_test_legendre_transforms (sph, comms_sph, fl_prop, sph_bc_U, omega_sph, trans_p, gt_cor, ncomp_max_trans, nvector_max_trans, nscalar_max_trans, rj_fld, trns_MHD, WK_leg, WK_FFTs_MHD, cor_rlm)
Variables
integer(kind=kint), parameter, private num_test = 5
integer(kind=kint), dimension(num_test), parameter, private list_test = (/iflag_leg_symmetry, iflag_leg_sym_spin_loop, iflag_leg_sym_matmul, iflag_leg_sym_matmul_big, iflag_on_the_fly_matprod/)
Detailed Description
Perform spherical harmonics transform for MHD dynamo model.
      subroutine s_test_legendre_transforms(sph, comms_sph,           &
     &          fl_prop, sph_bc_U, omega_sph, trans_p, gt_cor,        &
     &          ncomp_max_trans, nvector_max_trans, nscalar_max_trans,&
     &          rj_fld, trns_MHD, WK_leg, WK_FFTs_MHD, cor_rlm)
        type(sph_grids), intent(in) :: sph
        type(sph_comm_tables), intent(in) :: comms_sph
        type(fluid_property), intent(in) :: fl_prop
        type(sph_boundary_type), intent(in) :: sph_bc_U
        type(sph_rotation), intent(in) :: omega_sph
        type(parameters_4_sph_trans), intent(in) :: trans_p
        type(gaunt_coriolis_rlm), intent(in) :: gt_cor
        type(address_4_sph_trans), intent(inout) :: trns_MHD
        type(legendre_trns_works), intent(inout) :: WK_leg
        type(work_for_FFTs), intent(inout) :: WK_FFTs_MHD
        type(coriolis_rlm_data), intent(inout) :: cor_rlm
        type(phys_data), intent(inout) :: rj_fld
Function/Subroutine Documentation
s_test_legendre_transforms()
subroutine test_legendre_transforms::s_test_legendre_transforms (type(sph_grids), intent(in) sph, type(sph_comm_tables), intent(in) comms_sph, type(fluid_property), intent(in) fl_prop, type(sph_boundary_type), intent(in) sph_bc_U, type(sph_rotation), intent(in) omega_sph, type(parameters_4_sph_trans), intent(in) trans_p, type(gaunt_coriolis_rlm), intent(in) gt_cor, integer(kind = kint), intent(in) ncomp_max_trans, integer(kind = kint), intent(in) nvector_max_trans, integer(kind = kint), intent(in) nscalar_max_trans, type(phys_data), intent(inout) rj_fld, type(address_4_sph_trans), intent(inout) trns_MHD, type(legendre_trns_works), intent(inout) WK_leg, type(work_for_ffts), intent(inout) WK_FFTs_MHD, type(coriolis_rlm_data), intent(inout) cor_rlm)
Definition at line 78 of file test_legendre_transforms.F90.
References calypso_mpi_real::calypso_mpi_allreduce_real(), transfer_to_long_integers::cast_long(), list_test, calypso_mpi::my_rank, calypso_mpi::nprocs, t_legendre_trans_select::sel_finalize_legendre_trans(), t_legendre_trans_select::sel_init_legendre_trans(), sph_transforms_4_mhd::sph_back_trans_4_mhd(), sph_transforms_4_mhd::sph_forward_trans_4_mhd(), and m_constants::zero.
Referenced by init_sphrical_transform_mhd::sel_sph_transform_mhd().
Variable Documentation
list_test
integer(kind = kint), dimension(num_test), parameter, private test_legendre_transforms::list_test = (/iflag_leg_symmetry, iflag_leg_sym_spin_loop, iflag_leg_sym_matmul, iflag_leg_sym_matmul_big, iflag_on_the_fly_matprod/) private
Definition at line 60 of file test_legendre_transforms.F90.
Referenced by s_test_legendre_transforms().
num_test
integer(kind = kint), parameter, private test_legendre_transforms::num_test = 5 private
Definition at line 57 of file test_legendre_transforms.F90.