CALYPSO: hdf5_file_io Module Reference
hdf5_file_io Module Reference
Functions/Subroutines
subroutine parallel_init_hdf5
subroutine parallel_finalize_hdf5
subroutine, private copy_ele_connect_for_hdf5 (ucd, ie_swap)
subroutine, private copy_node_position_for_hdf5 (intnod, ucd, fld_swap)
subroutine, private copy_scalar_field_for_hdf5 (intnod, ist_fld, ucd, fld_swap)
subroutine, private copy_vector_field_for_hdf5 (intnod, ist_fld, ucd, fld_swap)
subroutine, private copy_sym_tensor_field_for_hdf5 (intnod, ist_fld, ucd, fld_swap)
subroutine parallel_write_hdf5_mesh_file (file_prefix, ucd)
subroutine parallel_write_hdf5_field_file (file_prefix, cur_step, ucd)
subroutine parallel_write_xdmf_snap_file (file_prefix, istep_hdf5, t_IO, ucd)
subroutine parallel_write_xdmf_evo_file (file_prefix, istep_hdf5, t_IO, ucd)
subroutine, private parallel_write_xdmf_file (file_prefix, xdmf_dir_file, istep_hdf5, t_IO, ucd)
Variables
integer(kind=kint), private ncomp_hdf5
number of components for HDF data output
real(kind=kreal), dimension(:), allocatable, private fld_hdf5
Real work array for HDF data output.
integer(kind=kint_4b), dimension(:), allocatable, private ie_hdf5
Integer array for HDF data output.
Function/Subroutine Documentation
copy_ele_connect_for_hdf5()
subroutine, private hdf5_file_io::copy_ele_connect_for_hdf5 (type(ucd_data), intent(in) ucd, integer(kind = kint_4b), dimension(ucd%nnod_4_ele*ucd%nele), intent(inout) ie_swap) private
Definition at line 88 of file hdf5_file_IO.F90.
Referenced by parallel_write_hdf5_mesh_file().
copy_node_position_for_hdf5()
subroutine, private hdf5_file_io::copy_node_position_for_hdf5 (integer(kind = kint), intent(in) intnod, type(ucd_data), intent(in) ucd, real(kind = kreal), dimension(3*intnod), intent(inout) fld_swap) private
Definition at line 111 of file hdf5_file_IO.F90.
Referenced by parallel_write_hdf5_mesh_file().
copy_scalar_field_for_hdf5()
subroutine, private hdf5_file_io::copy_scalar_field_for_hdf5 (integer(kind = kint), intent(in) intnod, integer(kind = kint), intent(in) ist_fld, type(ucd_data), intent(in) ucd, real(kind = kreal), dimension(intnod), intent(inout) fld_swap) private
Definition at line 133 of file hdf5_file_IO.F90.
Referenced by parallel_write_hdf5_field_file().
copy_sym_tensor_field_for_hdf5()
subroutine, private hdf5_file_io::copy_sym_tensor_field_for_hdf5 (integer(kind = kint), intent(in) intnod, integer(kind = kint), intent(in) ist_fld, type(ucd_data), intent(in) ucd, real(kind = kreal), dimension(9*intnod), intent(inout) fld_swap) private
Definition at line 176 of file hdf5_file_IO.F90.
Referenced by parallel_write_hdf5_field_file().
copy_vector_field_for_hdf5()
subroutine, private hdf5_file_io::copy_vector_field_for_hdf5 (integer(kind = kint), intent(in) intnod, integer(kind = kint), intent(in) ist_fld, type(ucd_data), intent(in) ucd, real(kind = kreal), dimension(3*intnod), intent(inout) fld_swap) private
Definition at line 154 of file hdf5_file_IO.F90.
Referenced by parallel_write_hdf5_field_file().
parallel_finalize_hdf5()
subroutine hdf5_file_io::parallel_finalize_hdf5
Definition at line 73 of file hdf5_file_IO.F90.
Referenced by merged_udt_vtk_file_io::finalize_merged_ucd().
parallel_init_hdf5()
subroutine hdf5_file_io::parallel_init_hdf5
Definition at line 58 of file hdf5_file_IO.F90.
Referenced by merged_udt_vtk_file_io::init_merged_ucd().
parallel_write_hdf5_field_file()
subroutine hdf5_file_io::parallel_write_hdf5_field_file (character(len = kchara), intent(in) file_prefix, integer(kind=kint), intent(in) cur_step, type(ucd_data), intent(in) ucd)
Definition at line 372 of file hdf5_file_IO.F90.
References calypso_mpi::calypso_comm, copy_scalar_field_for_hdf5(), copy_sym_tensor_field_for_hdf5(), copy_vector_field_for_hdf5(), fld_hdf5, calypso_mpi::my_rank, m_phys_constants::n_scalar, m_phys_constants::n_vector, ncomp_hdf5, calypso_mpi::nprocs, and set_ucd_file_names::set_merged_hdf_field_file_name().
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_file().
parallel_write_hdf5_mesh_file()
subroutine hdf5_file_io::parallel_write_hdf5_mesh_file (character(len = kchara), intent(in) file_prefix, type(ucd_data), intent(in) ucd)
Definition at line 206 of file hdf5_file_IO.F90.
References calypso_mpi::calypso_comm, copy_ele_connect_for_hdf5(), copy_node_position_for_hdf5(), fld_hdf5, ie_hdf5, calypso_mpi::my_rank, m_phys_constants::n_vector, calypso_mpi::nprocs, and set_ucd_file_names::set_merged_hdf_mesh_file_name().
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_mesh().
parallel_write_xdmf_evo_file()
subroutine hdf5_file_io::parallel_write_xdmf_evo_file (character(len = kchara), intent(in) file_prefix, integer(kind=kint), intent(in) istep_hdf5, type(time_data), intent(in) t_IO, type(ucd_data), intent(in) ucd)
Definition at line 544 of file hdf5_file_IO.F90.
References calypso_mpi::my_rank, parallel_write_xdmf_file(), and set_ucd_file_names::set_merged_xdmf_file_name().
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_file().
parallel_write_xdmf_file()
subroutine, private hdf5_file_io::parallel_write_xdmf_file (character(len = kchara), intent(in) file_prefix, character(len = kchara), intent(in) xdmf_dir_file, integer(kind=kint), intent(in) istep_hdf5, type(time_data), intent(in) t_IO, type(ucd_data), intent(in) ucd) private
Definition at line 568 of file hdf5_file_IO.F90.
References set_parallel_file_name::delete_directory_name(), set_parallel_file_name::int_to_str(), m_constants::ithree, m_precision::kreal, set_parallel_file_name::lint_to_str(), calypso_mpi::my_rank, calypso_mpi::nprocs, set_parallel_file_name::real_to_str(), set_ucd_file_names::set_merged_hdf_field_file_name(), and set_ucd_file_names::set_merged_hdf_mesh_file_name().
Referenced by parallel_write_xdmf_evo_file(), and parallel_write_xdmf_snap_file().
parallel_write_xdmf_snap_file()
subroutine hdf5_file_io::parallel_write_xdmf_snap_file (character(len = kchara), intent(in) file_prefix, integer(kind=kint), intent(in) istep_hdf5, type(time_data), intent(in) t_IO, type(ucd_data), intent(in) ucd)
Definition at line 520 of file hdf5_file_IO.F90.
References calypso_mpi::my_rank, parallel_write_xdmf_file(), and set_ucd_file_names::set_merged_snap_xdmf_file_name().
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_file().
Variable Documentation
fld_hdf5
real(kind = kreal), dimension(:), allocatable, private hdf5_file_io::fld_hdf5 private
Real work array for HDF data output.
Definition at line 43 of file hdf5_file_IO.F90.
Referenced by parallel_write_hdf5_field_file(), and parallel_write_hdf5_mesh_file().
ie_hdf5
integer(kind = kint_4b), dimension(:), allocatable, private hdf5_file_io::ie_hdf5 private
Integer array for HDF data output.
Definition at line 45 of file hdf5_file_IO.F90.
Referenced by parallel_write_hdf5_mesh_file().
ncomp_hdf5
integer(kind = kint), private hdf5_file_io::ncomp_hdf5 private
number of components for HDF data output
Definition at line 41 of file hdf5_file_IO.F90.
Referenced by parallel_write_hdf5_field_file().