CALYPSO: m_ludcmp_3band Module Reference
m_ludcmp_3band Module Reference
Functions/Subroutines
subroutine ludcmp_3band (n, band_a, i_pivot, ierr, band_lu, d)
Function/Subroutine Documentation
ludcmp_3band()
subroutine m_ludcmp_3band::ludcmp_3band (integer (kind = kint), intent(in) n, real(kind = kreal), dimension(3,n), intent(in) band_a, integer(kind = kint), dimension(n), intent(inout) i_pivot, integer(kind = kint), intent(inout) ierr, real(kind = kreal), dimension(5,n), intent(inout) band_lu, real(kind = kreal), intent(inout) d)
Definition at line 74 of file m_ludcmp_3band.f90.
References m_constants::ifour, m_constants::ione, m_constants::itwo, and m_constants::tiny.
Referenced by t_sph_center_matrix::ludcmp_3band_ctr(), ludcmp_357band_mul::ludcmp_3band_mul(), and t_sph_matrix::ludcmp_3band_type().