CALYPSO: cal_vr_rtm_by_vecprod Module Reference
cal_vr_rtm_by_vecprod Module Reference
Backward Legendre transform after vector product.
Functions/Subroutines
subroutine cal_vr_rtm_dydtheta_vector (nj_rlm, Pg3_je, dPdt_je, pol_e, dpoldt_e, dtordt_e, vr_pp)
subroutine cal_vr_rtm_dydphi_vector (nj_rlm, Pg3_je, asin_t, dpoldp_e, dtordp_e, vr_np)
subroutine cal_vr_rtm_scalar_blocked (nj_rlm, P_je, scl_e, vr_p)
subroutine cal_vr_rtm_dydtheta_symmetry (nj_rlm, Pg3_je, dPdt_je, Pg3_jo, dPdt_jo, pol_e, dpoldt_e, dtordt_e, pol_o, dpoldt_o, dtordt_o, vr_pp, vr_pn)
subroutine cal_vr_rtm_dydphi_symmetry (nj_rlm, Pg3_je, Pg3_jo, asin_t, dpoldp_e, dtordp_e, dpoldp_o, dtordp_o, vr_np, vr_nn)
subroutine cal_vr_rtm_scalar_symmetry (nj_rlm, P_je, P_jo, scl_e, scl_o, vr_p, vr_n)
subroutine cal_vr_rtm_dydtheta_equator (nj_rlm, Pg3_je, dPdt_jo, pol_e, dpoldt_o, dtordt_o, vr_pp)
subroutine cal_vr_rtm_dydphi_equator (nj_rlm, Pg3_je, dpoldp_e, dtordp_e, vr_np)
subroutine cal_vr_rtm_scalar_equator (nj_rlm, P_je, scl_e, vr_p)
Detailed Description
Backward Legendre transform after vector product.
      subroutine cal_vr_rtm_dydtheta_vector                           &
     &      (nj_rlm, Pg3_je, dPdt_je, pol_e, dpoldt_e, dtordt_e, vr_pp)
      subroutine cal_vr_rtm_dydphi_vector                             &
     &         (nj_rlm, Pg3_je, asin_t, dpoldp_e, dtordp_e, vr_np)
      subroutine cal_vr_rtm_scalar_blocked(nj_rlm, P_je, scl_e, vr_p)
      subroutine cal_vr_rtm_dydtheta_symmetry                         &
     &       (nj_rlm, Pg3_je, dPdt_je, Pg3_jo, dPdt_jo,               &
     &        pol_e, dpoldt_e, dtordt_e, pol_o, dpoldt_o, dtordt_o,   &
     &        vr_pp, vr_pn)
      subroutine cal_vr_rtm_dydphi_symmetry                           &
     &       (nj_rlm, Pg3_je, Pg3_jo, asin_t,                         &
     &        dpoldp_e, dtordp_e, dpoldp_o, dtordp_o, vr_np, vr_nn)
      subroutine cal_vr_rtm_scalar_symmetry(nj_rlm, P_je, P_jo,       &
     &          scl_e, scl_o, vr_p, vr_n)
      subroutine cal_vr_rtm_dydtheta_equator(nj_rlm, Pg3_je, dPdt_jo, &
     &          pol_e, dpoldt_o, dtordt_o, vr_pp)
      subroutine cal_vr_rtm_dydphi_equator                            &
     &       (nj_rlm, Pg3_je, dpoldp_e, dtordp_e, vr_np)
      subroutine cal_vr_rtm_scalar_equator(nj_rlm, P_je, scl_e, vr_p)
Function/Subroutine Documentation
cal_vr_rtm_dydphi_equator()
subroutine cal_vr_rtm_by_vecprod::cal_vr_rtm_dydphi_equator (integer(kind = kint), intent(in) nj_rlm, real(kind = kreal), dimension((nj_rlm+1)/2), intent(in) Pg3_je, real(kind = kreal), dimension((nj_rlm+1)/2), intent(in) dpoldp_e, real(kind = kreal), dimension((nj_rlm+1)/2), intent(in) dtordp_e, real(kind = kreal), dimension(3), intent(inout) vr_np)
Definition at line 264 of file cal_vr_rtm_by_vecprod.f90.
Referenced by legendre_bwd_trans_symmetry::leg_bwd_trans_vector_sym_org(), and legendre_bwd_trans_sym_spin::leg_bwd_trans_vector_sym_spin().
cal_vr_rtm_dydphi_symmetry()
subroutine cal_vr_rtm_by_vecprod::cal_vr_rtm_dydphi_symmetry (integer(kind = kint), intent(in) nj_rlm, real(kind = kreal), dimension((nj_rlm+1)/2), intent(in) Pg3_je, real(kind = kreal), dimension(nj_rlm/2), intent(in) Pg3_jo, real(kind = kreal), intent(in) asin_t, real(kind = kreal), dimension((nj_rlm+1)/2), intent(in) dpoldp_e, real(kind = kreal), dimension((nj_rlm+1)/2), intent(in) dtordp_e, real(kind = kreal), dimension(nj_rlm/2), intent(in) dpoldp_o, real(kind = kreal), dimension(nj_rlm/2), intent(in) dtordp_o, real(kind = kreal), dimension(3), intent(inout) vr_np, real(kind = kreal), dimension(3), intent(inout) vr_nn)
Definition at line 165 of file cal_vr_rtm_by_vecprod.f90.
Referenced by legendre_bwd_trans_symmetry::leg_bwd_trans_vector_sym_org(), and legendre_bwd_trans_sym_spin::leg_bwd_trans_vector_sym_spin().
cal_vr_rtm_dydphi_vector()
subroutine cal_vr_rtm_by_vecprod::cal_vr_rtm_dydphi_vector (integer(kind = kint), intent(in) nj_rlm, real(kind = kreal), dimension(nj_rlm), intent(in) Pg3_je, real(kind = kreal), intent(in) asin_t, real(kind = kreal), dimension(nj_rlm), intent(in) dpoldp_e, real(kind = kreal), dimension(nj_rlm), intent(in) dtordp_e, real(kind = kreal), dimension(3), intent(inout) vr_np)
Definition at line 75 of file cal_vr_rtm_by_vecprod.f90.
cal_vr_rtm_dydtheta_equator()
subroutine cal_vr_rtm_by_vecprod::cal_vr_rtm_dydtheta_equator (integer(kind = kint), intent(in) nj_rlm, real(kind = kreal), dimension((nj_rlm+1)/2), intent(in) Pg3_je, real(kind = kreal), dimension(nj_rlm/2), intent(in) dPdt_jo, real(kind = kreal), dimension((nj_rlm+1)/2), intent(in) pol_e, real(kind = kreal), dimension(nj_rlm/2), intent(in) dpoldt_o, real(kind = kreal), dimension(nj_rlm/2), intent(in) dtordt_o, real(kind = kreal), dimension(3), intent(inout) vr_pp)
Definition at line 233 of file cal_vr_rtm_by_vecprod.f90.
Referenced by legendre_bwd_trans_symmetry::leg_bwd_trans_vector_sym_org(), and legendre_bwd_trans_sym_spin::leg_bwd_trans_vector_sym_spin().
cal_vr_rtm_dydtheta_symmetry()
subroutine cal_vr_rtm_by_vecprod::cal_vr_rtm_dydtheta_symmetry (integer(kind = kint), intent(in) nj_rlm, real(kind = kreal), dimension((nj_rlm+1)/2), intent(in) Pg3_je, real(kind = kreal), dimension((nj_rlm+1)/2), intent(in) dPdt_je, real(kind = kreal), dimension(nj_rlm/2), intent(in) Pg3_jo, real(kind = kreal), dimension(nj_rlm/2), intent(in) dPdt_jo, real(kind = kreal), dimension((nj_rlm+1)/2), intent(in) pol_e, real(kind = kreal), dimension((nj_rlm+1)/2), intent(in) dpoldt_e, real(kind = kreal), dimension((nj_rlm+1)/2), intent(in) dtordt_e, real(kind = kreal), dimension(nj_rlm/2), intent(in) pol_o, real(kind = kreal), dimension(nj_rlm/2), intent(in) dpoldt_o, real(kind = kreal), dimension(nj_rlm/2), intent(in) dtordt_o, real(kind = kreal), dimension(3), intent(inout) vr_pp, real(kind = kreal), dimension(3), intent(inout) vr_pn)
Definition at line 119 of file cal_vr_rtm_by_vecprod.f90.
Referenced by legendre_bwd_trans_symmetry::leg_bwd_trans_vector_sym_org(), and legendre_bwd_trans_sym_spin::leg_bwd_trans_vector_sym_spin().
cal_vr_rtm_dydtheta_vector()
subroutine cal_vr_rtm_by_vecprod::cal_vr_rtm_dydtheta_vector (integer(kind = kint), intent(in) nj_rlm, real(kind = kreal), dimension(nj_rlm), intent(in) Pg3_je, real(kind = kreal), dimension(nj_rlm), intent(in) dPdt_je, real(kind = kreal), dimension(nj_rlm), intent(in) pol_e, real(kind = kreal), dimension(nj_rlm), intent(in) dpoldt_e, real(kind = kreal), dimension(nj_rlm), intent(in) dtordt_e, real(kind = kreal), dimension(3), intent(inout) vr_pp)
Definition at line 47 of file cal_vr_rtm_by_vecprod.f90.
cal_vr_rtm_scalar_blocked()
subroutine cal_vr_rtm_by_vecprod::cal_vr_rtm_scalar_blocked (integer(kind = kint), intent(in) nj_rlm, real(kind = kreal), dimension(nj_rlm), intent(in) P_je, real(kind = kreal), dimension(nj_rlm), intent(in) scl_e, real(kind = kreal), intent(inout) vr_p)
Definition at line 100 of file cal_vr_rtm_by_vecprod.f90.
cal_vr_rtm_scalar_equator()
subroutine cal_vr_rtm_by_vecprod::cal_vr_rtm_scalar_equator (integer(kind = kint), intent(in) nj_rlm, real(kind = kreal), dimension((nj_rlm+1)/2), intent(in) P_je, real(kind = kreal), dimension((nj_rlm+1)/2), intent(in) scl_e, real(kind = kreal), intent(inout) vr_p)
Definition at line 289 of file cal_vr_rtm_by_vecprod.f90.
Referenced by legendre_bwd_trans_symmetry::leg_bwd_trans_scalar_sym_org(), and legendre_bwd_trans_sym_spin::leg_bwd_trans_scalar_sym_spin().
cal_vr_rtm_scalar_symmetry()
subroutine cal_vr_rtm_by_vecprod::cal_vr_rtm_scalar_symmetry (integer(kind = kint), intent(in) nj_rlm, real(kind = kreal), dimension((nj_rlm+1)/2), intent(in) P_je, real(kind = kreal), dimension(nj_rlm/2), intent(in) P_jo, real(kind = kreal), dimension((nj_rlm+1)/2), intent(in) scl_e, real(kind = kreal), dimension(nj_rlm/2), intent(in) scl_o, real(kind = kreal), intent(inout) vr_p, real(kind = kreal), intent(inout) vr_n)
Definition at line 206 of file cal_vr_rtm_by_vecprod.f90.
Referenced by legendre_bwd_trans_symmetry::leg_bwd_trans_scalar_sym_org(), and legendre_bwd_trans_sym_spin::leg_bwd_trans_scalar_sym_spin().