CALYPSO: m_intersection_data_8 Module Reference
m_intersection_data_8 Module Reference
Variables
integer(kind=kint), parameter, private nnod_tri = 3
integer(kind=kint), parameter, private nnod_quad = 4
integer(kind=kint), parameter nkind_etype_8 = 6
integer(kind=kint), parameter num_patch_8 = 2
integer(kind=kint), dimension(6), parameter itri_2_patch_8 = (/2, 3, 1, 1, 3, 4/)
integer(kind=kint), dimension(nkind_etype_8), parameter iflag_psf_etype_8 = (/153, 102, 51, 204, 15, 240/)
integer(kind=kint), dimension(nnod_quad, nkind_etype_8), parameter iedge_quad_8 = reshape((/1, 5, 7, 3, 1, 3, 7, 5, 4, 2, 6, 8, 4, 8, 6, 2, 9, 12, 11, 10, 9, 10, 11, 12/), shape=(/nnod_quad, nkind_etype_8/))
integer(kind=kint), dimension(nnod_tri, num_patch_8, nkind_etype_8), parameter iedge_4_patch_8 = reshape((/ 5, 7, 1, 1, 7, 3, 3, 7, 1, 1, 7, 5, 2, 6, 4, 4, 6, 8, 8, 6, 4, 4, 6, 2, 12, 11, 9, 9, 11, 10, 10, 11, 9, 9, 11, 12/), shape=(/nnod_tri,num_patch_8,nkind_etype_8/))
Variable Documentation
iedge_4_patch_8
integer(kind = kint), dimension(nnod_tri,num_patch_8,nkind_etype_8), parameter m_intersection_data_8::iedge_4_patch_8 = reshape((/ 5, 7, 1, 1, 7, 3, 3, 7, 1, 1, 7, 5, 2, 6, 4, 4, 6, 8, 8, 6, 4, 4, 6, 2, 12, 11, 9, 9, 11, 10, 10, 11, 9, 9, 11, 12/), shape=(/nnod_tri,num_patch_8,nkind_etype_8/))
Definition at line 47 of file m_intersection_data_8.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
iedge_quad_8
integer(kind = kint), dimension(nnod_quad, nkind_etype_8), parameter m_intersection_data_8::iedge_quad_8 = reshape((/1, 5, 7, 3, 1, 3, 7, 5, 4, 2, 6, 8, 4, 8, 6, 2, 9, 12, 11, 10, 9, 10, 11, 12/), shape=(/nnod_quad, nkind_etype_8/))
Definition at line 40 of file m_intersection_data_8.f90.
iflag_psf_etype_8
integer(kind = kint), dimension(nkind_etype_8), parameter m_intersection_data_8::iflag_psf_etype_8 = (/153, 102, 51, 204, 15, 240/)
Definition at line 35 of file m_intersection_data_8.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
itri_2_patch_8
integer(kind = kint), dimension(6), parameter m_intersection_data_8::itri_2_patch_8 = (/2, 3, 1, 1, 3, 4/)
Definition at line 32 of file m_intersection_data_8.f90.
nkind_etype_8
integer(kind = kint), parameter m_intersection_data_8::nkind_etype_8 = 6
Definition at line 30 of file m_intersection_data_8.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
nnod_quad
integer(kind = kint), parameter, private m_intersection_data_8::nnod_quad = 4 private
Definition at line 28 of file m_intersection_data_8.f90.
nnod_tri
integer(kind = kint), parameter, private m_intersection_data_8::nnod_tri = 3 private
Definition at line 27 of file m_intersection_data_8.f90.
num_patch_8
integer(kind = kint), parameter m_intersection_data_8::num_patch_8 = 2
Definition at line 31 of file m_intersection_data_8.f90.
Referenced by t_psf_case_table::init_psf_case_tables().