CALYPSO: mark_surf_hash Module Reference
mark_surf_hash Module Reference
Functions/Subroutines
subroutine mark_all_surfaces (numele, nnod_4_ele, ie, ntot_id, ntot_list, istack_surf_hash, iend_surf_hash, isurf_hash, isurf_flag)
subroutine mark_independent_surface (numele, nnod_4_ele, ie, ntot_id, ntot_list, istack_surf_hash, iend_surf_hash, isurf_hash, isurf_flag)
subroutine mark_external_surface (internal_node, numele, nnod_4_ele, ie, ntot_id, ntot_list, istack_surf_hash, iend_surf_hash, isurf_hash, isurf_flag)
subroutine set_4nodes_id_on_surf (iele, is, numele, nnod_4_ele, ie, inod)
Function/Subroutine Documentation
mark_all_surfaces()
subroutine mark_surf_hash::mark_all_surfaces (integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) nnod_4_ele, integer(kind = kint), dimension(numele,nnod_4_ele), intent(in) ie, integer(kind = kint_gl), intent(in) ntot_id, integer(kind = kint_gl), intent(in) ntot_list, integer(kind = kint_gl), dimension(0:ntot_id), intent(in) istack_surf_hash, integer(kind = kint_gl), intent(in) iend_surf_hash, integer(kind = kint), dimension(ntot_list,2), intent(in) isurf_hash, integer(kind = kint_gl), dimension(ntot_list), intent(inout) isurf_flag)
Definition at line 31 of file mark_surf_hash.f90.
References compare_indices::check_4_on_3(), and set_4nodes_id_on_surf().
Referenced by const_surface_data::const_all_surface_data().
mark_external_surface()
subroutine mark_surf_hash::mark_external_surface (integer(kind = kint), intent(in) internal_node, integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) nnod_4_ele, integer(kind = kint), dimension(numele,nnod_4_ele), intent(in) ie, integer(kind = kint_gl), intent(in) ntot_id, integer(kind = kint_gl), intent(in) ntot_list, integer(kind = kint_gl), dimension(0:ntot_id), intent(in) istack_surf_hash, integer(kind = kint_gl), intent(in) iend_surf_hash, integer(kind = kint), dimension(ntot_list,2), intent(in) isurf_hash, integer(kind = kint_gl), dimension(ntot_list), intent(inout) isurf_flag)
Definition at line 208 of file mark_surf_hash.f90.
References set_4nodes_id_on_surf().
Referenced by const_surface_data::const_external_surface_data().
mark_independent_surface()
subroutine mark_surf_hash::mark_independent_surface (integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) nnod_4_ele, integer(kind = kint), dimension(numele,nnod_4_ele), intent(in) ie, integer(kind = kint_gl), intent(in) ntot_id, integer(kind = kint_gl), intent(in) ntot_list, integer(kind = kint_gl), dimension(0:ntot_id), intent(in) istack_surf_hash, integer(kind = kint_gl), intent(in) iend_surf_hash, integer(kind = kint), dimension(ntot_list,2), intent(in) isurf_hash, integer(kind = kint_gl), dimension(ntot_list), intent(inout) isurf_flag)
Definition at line 120 of file mark_surf_hash.f90.
References compare_indices::check_4_on_3(), and set_4nodes_id_on_surf().
Referenced by const_surface_data::const_external_surface_data(), const_surface_data::const_isolate_surface_data(), and const_merged_surf_4_group::const_merged_surface_4_ele_grp().
set_4nodes_id_on_surf()
subroutine mark_surf_hash::set_4nodes_id_on_surf (integer(kind = kint), intent(in) iele, integer(kind = kint), intent(in) is, integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) nnod_4_ele, integer(kind = kint), dimension(numele,nnod_4_ele), intent(in) ie, integer(kind = kint), dimension(4), intent(inout) inod)
Definition at line 262 of file mark_surf_hash.f90.
References m_geometry_constants::node_on_sf_4.
Referenced by mark_all_surfaces(), mark_external_surface(), and mark_independent_surface().