CALYPSO: m_error_ids Module Reference
m_error_ids Module Reference
Variables
integer(kind=kint), parameter ierr_p_mpi = 1
Error ID for MPI related.
integer(kind=kint), parameter ierr_p_smp = 2
Error ID for MPI related.
integer(kind=kint), parameter ierr_file = 100
Error ID for missing file.
integer(kind=kint), parameter ierr_mesh = 101
Error ID for FEM mesh.
integer(kind=kint), parameter ierr_cg = 102
Error ID for linear solver.
integer(kind=kint), parameter ierr_sph = 111
Error ID for Spherical harmonics transform method.
integer(kind=kint), parameter ierr_fem = 112
Error ID for FEM.
integer(kind=kint), parameter ierr_fld = 201
Error ID for field definition.
integer(kind=kint), parameter ierr_bc = 211
Error ID for field definition.
integer(kind=kint), parameter ierr_force = 251
Error ID for force definition.
integer(kind=kint), parameter ierr_dless = 301
Error ID for normalization.
integer(kind=kint), parameter ierr_evo = 401
Error ID for Time integration.
integer(kind=kint), parameter ierr_sgs = 501
Error ID for SGS model.
integer(kind=kint), parameter ierr_viz = 601
Error ID in visualizer module.
integer(kind=kint), parameter ierr_pvr = 621
Error ID in PVR module.
integer(kind=kint), parameter ierr_lic = 631
Error ID in LIC PVR module.
integer(kind=kint), parameter ierr_ele = 1001
Error ID for FEM element.
integer(kind=kint), parameter ierr_ngrp = 1002
Error ID for FEM number of groups.
integer(kind=kint), parameter ierr_grp = 1003
Error ID for FEM grouping.
integer(kind=kint), parameter ierr_etype = 1004
Error ID for FEM element type.
integer(kind=kint), parameter ierr_econ = 1005
Error ID for FEM element connectivity.
integer(kind=kint), parameter ierr_ovnod = 2001
Error ID for overflow of FEM node.
integer(kind=kint), parameter ierr_ov_grp = 2002
Error ID for overflow of FEM group.
integer(kind=kint), parameter ierr_sf_grp = 2003
Error ID for surface group.
integer(kind=kint), parameter ierr_metisfile = 7001
Error ID for MeTiS input.
integer(kind=kint), parameter ierr_metisdata = 7002
Error ID for MeTiS input.
Variable Documentation
ierr_bc
integer(kind = kint), parameter m_error_ids::ierr_bc = 211
Error ID for field definition.
Definition at line 36 of file m_error_IDs.f90.
Referenced by set_bc_sph_scalars::find_both_sides_of_boundaries(), set_bc_sph_scalars::set_sph_bc_composition_sph(), and set_bc_sph_scalars::set_sph_bc_temp_sph().
ierr_cg
integer(kind = kint), parameter m_error_ids::ierr_cg = 102
Error ID for linear solver.
Definition at line 26 of file m_error_IDs.f90.
ierr_dless
integer(kind = kint), parameter m_error_ids::ierr_dless = 301
Error ID for normalization.
Definition at line 42 of file m_error_IDs.f90.
Referenced by construct_mhd_coefficient::construct_coefficient(), set_control_4_normalize::set_coefs_4_composition_eq(), set_control_4_normalize::set_coefs_4_induction_eq(), set_control_4_normalize::set_coefs_4_momentum_eq(), set_control_4_normalize::set_coefs_4_thermal_eq(), and set_control_4_normalize::set_dimensionless_numbers().
ierr_econ
integer(kind = kint), parameter m_error_ids::ierr_econ = 1005
Error ID for FEM element connectivity.
Definition at line 70 of file m_error_IDs.f90.
ierr_ele
integer(kind = kint), parameter m_error_ids::ierr_ele = 1001
Error ID for FEM element.
Definition at line 62 of file m_error_IDs.f90.
ierr_etype
integer(kind = kint), parameter m_error_ids::ierr_etype = 1004
Error ID for FEM element type.
Definition at line 68 of file m_error_IDs.f90.
ierr_evo
integer(kind = kint), parameter m_error_ids::ierr_evo = 401
Error ID for Time integration.
Definition at line 45 of file m_error_IDs.f90.
Referenced by set_control_4_model::s_set_control_4_model(), set_time_step_params::s_set_fixed_time_step_params(), t_flex_delta_t_parameter::set_control_flex_time_steps(), t_flex_delta_t_parameter::set_flex_time_step_params(), and m_initial_field_control::set_initial_field_id().
ierr_fem
integer(kind = kint), parameter m_error_ids::ierr_fem = 112
Error ID for FEM.
Definition at line 31 of file m_error_IDs.f90.
ierr_file
integer(kind = kint), parameter m_error_ids::ierr_file = 100
Error ID for missing file.
Definition at line 22 of file m_error_IDs.f90.
Referenced by parallel_gen_sph_grids::check_and_make_para_rj_mode(), parallel_gen_sph_grids::check_and_make_para_sph_mesh(), t_check_and_make_sph_mesh::check_and_make_sph_mesh(), t_check_and_make_sph_mesh::check_and_make_sph_rj_mode(), gz_mpi_domain_data_io::gz_mpi_check_num_of_domains(), gz_mpi_binary_datum_io::gz_mpi_read_process_id_b(), gz_field_data_io_b::gz_read_step_data_b(), mpi_domain_data_io::mpi_check_num_of_domains(), mpi_binary_head_io::mpi_read_process_id_b(), gz_binary_io::open_rd_gzfile_b(), t_sph_mhd_monitor_data_io::open_sph_vol_rms_file_mhd(), binary_io::read_endian_flag(), set_control_field_data::s_set_control_field_data(), set_control_newsph::set_control_4_newsph(), and set_control_field_data::set_control_field_by_comp_viz().
ierr_fld
integer(kind = kint), parameter m_error_ids::ierr_fld = 201
Error ID for field definition.
Definition at line 34 of file m_error_IDs.f90.
Referenced by check_dependency_for_mhd::check_field_dependencies(), check_dependency_for_mhd::check_missing_field_w_msg(), gz_field_block_mpi_io::read_field_step_gz_mpi(), field_data_mpi_io::read_field_time_mpi(), field_io_select::sel_write_step_field_file(), set_control_sph_data_mhd::set_control_sph_mhd_fields(), t_reference_scalar_param::set_linear_ref_scalar_ctl(), and t_reference_scalar_param::set_takepiro_scalar_ctl().
ierr_force
integer(kind = kint), parameter m_error_ids::ierr_force = 251
Error ID for force definition.
Definition at line 39 of file m_error_IDs.f90.
Referenced by set_control_4_force::set_control_4_gravity(), and set_control_4_force::set_control_4_induction().
ierr_grp
integer(kind = kint), parameter m_error_ids::ierr_grp = 1003
Error ID for FEM grouping.
Definition at line 66 of file m_error_IDs.f90.
ierr_lic
integer(kind = kint), parameter m_error_ids::ierr_lic = 631
Error ID in LIC PVR module.
Definition at line 57 of file m_error_IDs.f90.
ierr_mesh
integer(kind = kint), parameter m_error_ids::ierr_mesh = 101
Error ID for FEM mesh.
Definition at line 24 of file m_error_IDs.f90.
Referenced by t_spheric_global_ranks::check_sph_domains(), gz_domain_data_io::gz_read_domain_info(), gz_domain_data_io_b::gz_read_domain_info_b(), domain_data_io::read_domain_info(), domain_data_io_b::read_domain_info_b(), t_ctl_params_gen_sph_shell::set_control_4_shell_grids(), t_ctl_params_gen_sph_shell::set_ctl_radius_4_shell(), and set_control_sph_subdomains::set_subdomains_4_sph_shell().
ierr_metisdata
integer(kind = kint), parameter m_error_ids::ierr_metisdata = 7002
Error ID for MeTiS input.
Definition at line 82 of file m_error_IDs.f90.
ierr_metisfile
integer(kind = kint), parameter m_error_ids::ierr_metisfile = 7001
Error ID for MeTiS input.
Definition at line 80 of file m_error_IDs.f90.
ierr_ngrp
integer(kind = kint), parameter m_error_ids::ierr_ngrp = 1002
Error ID for FEM number of groups.
Definition at line 64 of file m_error_IDs.f90.
ierr_ov_grp
integer(kind = kint), parameter m_error_ids::ierr_ov_grp = 2002
Error ID for overflow of FEM group.
Definition at line 75 of file m_error_IDs.f90.
ierr_ovnod
integer(kind = kint), parameter m_error_ids::ierr_ovnod = 2001
Error ID for overflow of FEM node.
Definition at line 73 of file m_error_IDs.f90.
ierr_p_mpi
integer(kind = kint), parameter m_error_ids::ierr_p_mpi = 1
Error ID for MPI related.
Definition at line 17 of file m_error_IDs.f90.
Referenced by analyzer_check_sph_grids::analyze_check_sph_grids(), set_ctl_parallel_platform::check_control_num_domains(), analyzer_check_sph_grids::init_check_sph_grids(), analyzer_gen_sph_grids::init_gen_sph_grids(), and set_control_newsph::set_control_4_newsph().
ierr_p_smp
integer(kind = kint), parameter m_error_ids::ierr_p_smp = 2
Error ID for MPI related.
Definition at line 19 of file m_error_IDs.f90.
Referenced by check_sph_mhd_openmp_size::s_check_sph_mhd_openmp_size().
ierr_pvr
integer(kind = kint), parameter m_error_ids::ierr_pvr = 621
Error ID in PVR module.
Definition at line 54 of file m_error_IDs.f90.
ierr_sf_grp
integer(kind = kint), parameter m_error_ids::ierr_sf_grp = 2003
Error ID for surface group.
Definition at line 77 of file m_error_IDs.f90.
ierr_sgs
integer(kind = kint), parameter m_error_ids::ierr_sgs = 501
Error ID for SGS model.
Definition at line 48 of file m_error_IDs.f90.
ierr_sph
integer(kind = kint), parameter m_error_ids::ierr_sph = 111
Error ID for Spherical harmonics transform method.
Definition at line 29 of file m_error_IDs.f90.
Referenced by r_interpolate_sph_data::copy_original_sph_rj_from_io().
ierr_viz
integer(kind = kint), parameter m_error_ids::ierr_viz = 601
Error ID in visualizer module.
Definition at line 51 of file m_error_IDs.f90.
Referenced by t_control_params_4_psf::count_control_4_psf_define(), and set_coefs_of_sections::s_set_coefs_of_sections().