CALYPSO: cal_mesh_position Module Reference
cal_mesh_position Module Reference
Functions/Subroutines
subroutine set_spherical_position (nod)
subroutine set_center_of_element (nod, ele)
subroutine set_center_of_surface (nod, surf)
subroutine set_center_of_edge (nod, edge)
subroutine find_subdomain_position_range (nod)
Function/Subroutine Documentation
find_subdomain_position_range()
subroutine cal_mesh_position::find_subdomain_position_range (type(node_data), intent(inout) nod)
Definition at line 127 of file cal_mesh_position.f90.
Referenced by const_mesh_information::set_nod_and_ele_infos().
set_center_of_edge()
subroutine cal_mesh_position::set_center_of_edge (type(node_data), intent(in) nod, type(edge_data), intent(inout) edge)
Definition at line 104 of file cal_mesh_position.f90.
References m_geometry_constants::num_linear_edge, m_geometry_constants::num_quad_edge, set_edge_position::set_linear_edge_position(), and set_edge_position::set_quad_edge_position().
Referenced by set_surf_edge_mesh::set_edge_geometry().
set_center_of_element()
subroutine cal_mesh_position::set_center_of_element (type(node_data), intent(in) nod, type(element_data), intent(inout) ele)
Definition at line 47 of file cal_mesh_position.f90.
References m_geometry_constants::num_t_lag, m_geometry_constants::num_t_linear, m_geometry_constants::num_t_quad, coordinate_converter::position_2_sph(), set_element_position::set_lag_ele_position(), set_element_position::set_linear_ele_position(), and set_element_position::set_quad_ele_position().
Referenced by const_mesh_information::set_nod_and_ele_infos().
set_center_of_surface()
subroutine cal_mesh_position::set_center_of_surface (type(node_data), intent(in) nod, type(surface_data), intent(inout) surf)
Definition at line 77 of file cal_mesh_position.f90.
References m_geometry_constants::num_lag_sf, m_geometry_constants::num_linear_sf, m_geometry_constants::num_quad_sf, set_surface_position::set_lag_surf_position(), set_surface_position::set_linear_surf_position(), and set_surface_position::set_quad_surf_position().
Referenced by set_surf_edge_mesh::set_surf_geometry().
set_spherical_position()
subroutine cal_mesh_position::set_spherical_position (type(node_data), intent(inout) nod)
Definition at line 32 of file cal_mesh_position.f90.
References coordinate_converter::position_2_sph().
Referenced by const_mesh_information::set_nod_and_ele_infos(), set_nodes_for_psf::set_nodes_4_iso(), and set_nodes_for_psf::set_nodes_4_psf().