CALYPSO: const_sph_divergence Module Reference
const_sph_divergence Module Reference
Evaluate divergence of forces.
Functions/Subroutines
subroutine const_sph_scalar_advect (sph_rj, r_2nd, sph_bc, bcs_S, fdm2_center, g_sph_rj, is_flux, is_advect, rj_fld)
subroutine const_sph_div_force (sph_rj, r_2nd, sph_bc_U, g_sph_rj, is_fld, is_div, rj_fld)
Detailed Description
Evaluate divergence of forces.
      subroutine const_sph_scalar_advect                              &
     &         (sph_rj, r_2nd, sph_bc, bcs_S, fdm2_center, g_sph_rj,  &
     &          is_flux, is_advect, rj_fld)
      subroutine const_sph_div_force(sph_rj, r_2nd, sph_bc_U,         &
     &          g_sph_rj, is_fld, is_div, rj_fld)
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(fdm_matrices), intent(in) :: r_2nd
        type(sph_boundary_type), intent(in) :: sph_bc
        type(sph_boundary_type), intent(in) :: sph_bc_U
        type(sph_scalar_boundary_data), intent(in) :: bcs_S
        type(fdm2_center_mat), intent(in) :: fdm2_center
        type(phys_data), intent(inout) :: rj_fld
Parameters
sph_bc Structure for basic boundary condition parameters
is_flux Spherical hermonics data address for input flux
is_advect Spherical hermonics data address for advection
is_fld Spherical hermonics data address for input vector
is_div Spherical hermonics data address for divergence
Function/Subroutine Documentation
const_sph_div_force()
subroutine const_sph_divergence::const_sph_div_force (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc_U, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_div, type(phys_data), intent(inout) rj_fld)
Definition at line 86 of file const_sph_divergence.f90.
References cal_sph_exp_nod_none_bc::cal_sph_nod_nobc_in_div2(), cal_sph_exp_nod_none_bc::cal_sph_nod_nobc_out_div2(), and cal_sph_exp_rotation::cal_sph_nod_vect_div2().
Referenced by cal_sph_divergence_of_force::cal_div_of_buoyancies_sph_2(), and cal_sph_divergence_of_force::cal_div_of_forces_sph_2().
const_sph_scalar_advect()
subroutine const_sph_divergence::const_sph_scalar_advect (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc, type(sph_scalar_boundary_data), intent(in) bcs_S, type(fdm2_center_mat), intent(in) fdm2_center, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, integer(kind = kint), intent(in) is_flux, integer(kind = kint), intent(in) is_advect, type(phys_data), intent(inout) rj_fld)
Definition at line 51 of file const_sph_divergence.f90.
References cal_sph_exp_rotation::cal_sph_nod_vect_div2(), select_exp_scalar_cmb::sel_cmb_sph_scalar_advect(), and select_exp_scalar_icb::sel_icb_sph_scalar_advect().
Referenced by cal_sph_field_by_rotation::cal_div_of_fluxes_sph().