CALYPSO: /home/takumi kera/calypso/src/External_libs/FFTPACK5.1D/fftpack5.1d.f90 File Reference
fftpack5.1d.f90 File Reference
Functions/Subroutines
subroutine c1f2kb (ido, l1, na, cc, in1, ch, in2, wa)
subroutine c1f2kf (ido, l1, na, cc, in1, ch, in2, wa)
subroutine c1f3kb (ido, l1, na, cc, in1, ch, in2, wa)
subroutine c1f3kf (ido, l1, na, cc, in1, ch, in2, wa)
subroutine c1f4kb (ido, l1, na, cc, in1, ch, in2, wa)
subroutine c1f4kf (ido, l1, na, cc, in1, ch, in2, wa)
subroutine c1f5kb (ido, l1, na, cc, in1, ch, in2, wa)
subroutine c1f5kf (ido, l1, na, cc, in1, ch, in2, wa)
subroutine c1fgkb (ido, ip, l1, lid, na, cc, cc1, in1, ch, ch1, in2, wa)
subroutine c1fgkf (ido, ip, l1, lid, na, cc, cc1, in1, ch, ch1, in2, wa)
subroutine c1fm1b (n, inc, c, ch, wa, fnf, fac)
subroutine c1fm1f (n, inc, c, ch, wa, fnf, fac)
subroutine cfft1b (n, inc, c, lenc, wsave, lensav, work, lenwrk, ier)
subroutine cfft1f (n, inc, c, lenc, wsave, lensav, work, lenwrk, ier)
subroutine cfft1i (n, wsave, lensav, ier)
subroutine cfft2b (ldim, l, m, c, wsave, lensav, work, lenwrk, ier)
subroutine cfft2f (ldim, l, m, c, wsave, lensav, work, lenwrk, ier)
subroutine cfft2i (l, m, wsave, lensav, ier)
subroutine cfftmb (lot, jump, n, inc, c, lenc, wsave, lensav, work, lenwrk, ier)
subroutine cfftmf (lot, jump, n, inc, c, lenc, wsave, lensav, work, lenwrk, ier)
subroutine cfftmi (n, wsave, lensav, ier)
subroutine cmf2kb (lot, ido, l1, na, cc, im1, in1, ch, im2, in2, wa)
subroutine cmf2kf (lot, ido, l1, na, cc, im1, in1, ch, im2, in2, wa)
subroutine cmf3kb (lot, ido, l1, na, cc, im1, in1, ch, im2, in2, wa)
subroutine cmf3kf (lot, ido, l1, na, cc, im1, in1, ch, im2, in2, wa)
subroutine cmf4kb (lot, ido, l1, na, cc, im1, in1, ch, im2, in2, wa)
subroutine cmf4kf (lot, ido, l1, na, cc, im1, in1, ch, im2, in2, wa)
subroutine cmf5kb (lot, ido, l1, na, cc, im1, in1, ch, im2, in2, wa)
subroutine cmf5kf (lot, ido, l1, na, cc, im1, in1, ch, im2, in2, wa)
subroutine cmfgkb (lot, ido, ip, l1, lid, na, cc, cc1, im1, in1, ch, ch1, im2, in2, wa)
subroutine cmfgkf (lot, ido, ip, l1, lid, na, cc, cc1, im1, in1, ch, ch1, im2, in2, wa)
subroutine cmfm1b (lot, jump, n, inc, c, ch, wa, fnf, fac)
subroutine cmfm1f (lot, jump, n, inc, c, ch, wa, fnf, fac)
subroutine cosq1b (n, inc, x, lenx, wsave, lensav, work, lenwrk, ier)
subroutine cosq1f (n, inc, x, lenx, wsave, lensav, work, lenwrk, ier)
subroutine cosq1i (n, wsave, lensav, ier)
subroutine cosqb1 (n, inc, x, wsave, work, ier)
subroutine cosqf1 (n, inc, x, wsave, work, ier)
subroutine cosqmb (lot, jump, n, inc, x, lenx, wsave, lensav, work, lenwrk, ier)
subroutine cosqmf (lot, jump, n, inc, x, lenx, wsave, lensav, work, lenwrk, ier)
subroutine cosqmi (n, wsave, lensav, ier)
subroutine cost1b (n, inc, x, lenx, wsave, lensav, work, lenwrk, ier)
subroutine cost1f (n, inc, x, lenx, wsave, lensav, work, lenwrk, ier)
subroutine cost1i (n, wsave, lensav, ier)
subroutine costb1 (n, inc, x, wsave, work, ier)
subroutine costf1 (n, inc, x, wsave, work, ier)
subroutine costmb (lot, jump, n, inc, x, lenx, wsave, lensav, work, lenwrk, ier)
subroutine costmf (lot, jump, n, inc, x, lenx, wsave, lensav, work, lenwrk, ier)
subroutine costmi (n, wsave, lensav, ier)
subroutine mcsqb1 (lot, jump, n, inc, x, wsave, work, ier)
subroutine mcsqf1 (lot, jump, n, inc, x, wsave, work, ier)
subroutine mcstb1 (lot, jump, n, inc, x, wsave, dsum, work, ier)
subroutine mcstf1 (lot, jump, n, inc, x, wsave, dsum, work, ier)
subroutine mradb2 (m, ido, l1, cc, im1, in1, ch, im2, in2, wa1)
subroutine mradb3 (m, ido, l1, cc, im1, in1, ch, im2, in2, wa1, wa2)
subroutine mradb4 (m, ido, l1, cc, im1, in1, ch, im2, in2, wa1, wa2, wa3)
subroutine mradb5 (m, ido, l1, cc, im1, in1, ch, im2, in2, wa1, wa2, wa3, wa4)
subroutine mradbg (m, ido, ip, l1, idl1, cc, c1, c2, im1, in1, ch, ch2, im2, in2, wa)
subroutine mradf2 (m, ido, l1, cc, im1, in1, ch, im2, in2, wa1)
subroutine mradf3 (m, ido, l1, cc, im1, in1, ch, im2, in2, wa1, wa2)
subroutine mradf4 (m, ido, l1, cc, im1, in1, ch, im2, in2, wa1, wa2, wa3)
subroutine mradf5 (m, ido, l1, cc, im1, in1, ch, im2, in2, wa1, wa2, wa3, wa4)
subroutine mradfg (m, ido, ip, l1, idl1, cc, c1, c2, im1, in1, ch, ch2, im2, in2, wa)
subroutine mrftb1 (m, im, n, in, c, ch, wa, fac)
subroutine mrftf1 (m, im, n, in, c, ch, wa, fac)
subroutine mrfti1 (n, wa, fac)
subroutine msntb1 (lot, jump, n, inc, x, wsave, dsum, xh, work, ier)
subroutine msntf1 (lot, jump, n, inc, x, wsave, dsum, xh, work, ier)
subroutine r1f2kb (ido, l1, cc, in1, ch, in2, wa1)
subroutine r1f2kf (ido, l1, cc, in1, ch, in2, wa1)
subroutine r1f3kb (ido, l1, cc, in1, ch, in2, wa1, wa2)
subroutine r1f3kf (ido, l1, cc, in1, ch, in2, wa1, wa2)
subroutine r1f4kb (ido, l1, cc, in1, ch, in2, wa1, wa2, wa3)
subroutine r1f4kf (ido, l1, cc, in1, ch, in2, wa1, wa2, wa3)
subroutine r1f5kb (ido, l1, cc, in1, ch, in2, wa1, wa2, wa3, wa4)
subroutine r1f5kf (ido, l1, cc, in1, ch, in2, wa1, wa2, wa3, wa4)
subroutine r1fgkb (ido, ip, l1, idl1, cc, c1, c2, in1, ch, ch2, in2, wa)
subroutine r1fgkf (ido, ip, l1, idl1, cc, c1, c2, in1, ch, ch2, in2, wa)
subroutine r2w (ldr, ldw, l, m, r, w)
subroutine r4_factor (n, nf, fac)
subroutine r4_mcfti1 (n, wa, fnf, fac)
subroutine r4_tables (ido, ip, wa)
subroutine r8_factor (n, nf, fac)
subroutine r8_mcfti1 (n, wa, fnf, fac)
subroutine r8_tables (ido, ip, wa)
subroutine rfft1b (n, inc, r, lenr, wsave, lensav, work, lenwrk, ier)
subroutine rfft1f (n, inc, r, lenr, wsave, lensav, work, lenwrk, ier)
subroutine rfft1i (n, wsave, lensav, ier)
subroutine rfft2b (ldim, l, m, r, wsave, lensav, work, lenwrk, ier)
subroutine rfft2f (ldim, l, m, r, wsave, lensav, work, lenwrk, ier)
subroutine rfft2i (l, m, wsave, lensav, ier)
subroutine rfftb1 (n, in, c, ch, wa, fac)
subroutine rfftf1 (n, in, c, ch, wa, fac)
subroutine rffti1 (n, wa, fac)
subroutine rfftmb (lot, jump, n, inc, r, lenr, wsave, lensav, work, lenwrk, ier)
subroutine rfftmf (lot, jump, n, inc, r, lenr, wsave, lensav, work, lenwrk, ier)
subroutine rfftmi (n, wsave, lensav, ier)
subroutine sinq1b (n, inc, x, lenx, wsave, lensav, work, lenwrk, ier)
subroutine sinq1f (n, inc, x, lenx, wsave, lensav, work, lenwrk, ier)
subroutine sinq1i (n, wsave, lensav, ier)
subroutine sinqmb (lot, jump, n, inc, x, lenx, wsave, lensav, work, lenwrk, ier)
subroutine sinqmf (lot, jump, n, inc, x, lenx, wsave, lensav, work, lenwrk, ier)
subroutine sinqmi (n, wsave, lensav, ier)
subroutine sint1b (n, inc, x, lenx, wsave, lensav, work, lenwrk, ier)
subroutine sint1f (n, inc, x, lenx, wsave, lensav, work, lenwrk, ier)
subroutine sint1i (n, wsave, lensav, ier)
subroutine sintb1 (n, inc, x, wsave, xh, work, ier)
subroutine sintf1 (n, inc, x, wsave, xh, work, ier)
subroutine sintmb (lot, jump, n, inc, x, lenx, wsave, lensav, work, lenwrk, ier)
subroutine sintmf (lot, jump, n, inc, x, lenx, wsave, lensav, work, lenwrk, ier)
subroutine sintmi (n, wsave, lensav, ier)
subroutine w2r (ldr, ldw, l, m, r, w)
logical function xercon (inc, jump, n, lot)
subroutine xerfft (srname, info)
Function/Subroutine Documentation
c1f2kb()
subroutine c1f2kb (integer (kind = 4) ido, integer (kind = 4) l1, integer (kind = 4) na, real (kind = 8), dimension(in1,l1,ido,2) cc, integer (kind = 4) in1, real (kind = 8), dimension(in2,l1,2,ido) ch, integer (kind = 4) in2, real (kind = 8), dimension(ido,1,2) wa)
Definition at line 1 of file fftpack5.1d.f90.
Referenced by c1fm1b().
c1f2kf()
subroutine c1f2kf (integer (kind = 4) ido, integer (kind = 4) l1, integer (kind = 4) na, real (kind = 8), dimension(in1,l1,ido,2) cc, integer (kind = 4) in1, real (kind = 8), dimension(in2,l1,2,ido) ch, integer (kind = 4) in2, real (kind = 8), dimension(ido,1,2) wa)
Definition at line 89 of file fftpack5.1d.f90.
Referenced by c1fm1f().
c1f3kb()
subroutine c1f3kb (integer (kind = 4) ido, integer (kind = 4) l1, integer (kind = 4) na, real (kind = 8), dimension(in1,l1,ido,3) cc, integer (kind = 4) in1, real (kind = 8), dimension(in2,l1,3,ido) ch, integer (kind = 4) in2, real (kind = 8), dimension(ido,2,2) wa)
Definition at line 189 of file fftpack5.1d.f90.
Referenced by c1fm1b().
c1f3kf()
subroutine c1f3kf (integer (kind = 4) ido, integer (kind = 4) l1, integer (kind = 4) na, real (kind = 8), dimension(in1,l1,ido,3) cc, integer (kind = 4) in1, real (kind = 8), dimension(in2,l1,3,ido) ch, integer (kind = 4) in2, real (kind = 8), dimension(ido,2,2) wa)
Definition at line 309 of file fftpack5.1d.f90.
Referenced by c1fm1f().
c1f4kb()
subroutine c1f4kb (integer (kind = 4) ido, integer (kind = 4) l1, integer (kind = 4) na, real (kind = 8), dimension(in1,l1,ido,4) cc, integer (kind = 4) in1, real (kind = 8), dimension(in2,l1,4,ido) ch, integer (kind = 4) in2, real (kind = 8), dimension(ido,3,2) wa)
Definition at line 447 of file fftpack5.1d.f90.
Referenced by c1fm1b().
c1f4kf()
subroutine c1f4kf (integer (kind = 4) ido, integer (kind = 4) l1, integer (kind = 4) na, real (kind = 8), dimension(in1,l1,ido,4) cc, integer (kind = 4) in1, real (kind = 8), dimension(in2,l1,4,ido) ch, integer (kind = 4) in2, real (kind = 8), dimension(ido,3,2) wa)
Definition at line 581 of file fftpack5.1d.f90.
Referenced by c1fm1f().
c1f5kb()
subroutine c1f5kb (integer (kind = 4) ido, integer (kind = 4) l1, integer (kind = 4) na, real (kind = 8), dimension(in1,l1,ido,5) cc, integer (kind = 4) in1, real (kind = 8), dimension(in2,l1,5,ido) ch, integer (kind = 4) in2, real (kind = 8), dimension(ido,4,2) wa)
Definition at line 738 of file fftpack5.1d.f90.
Referenced by c1fm1b().
c1f5kf()
subroutine c1f5kf (integer (kind = 4) ido, integer (kind = 4) l1, integer (kind = 4) na, real (kind = 8), dimension(in1,l1,ido,5) cc, integer (kind = 4) in1, real (kind = 8), dimension(in2,l1,5,ido) ch, integer (kind = 4) in2, real (kind = 8), dimension(ido,4,2) wa)
Definition at line 922 of file fftpack5.1d.f90.
Referenced by c1fm1f().
c1fgkb()
subroutine c1fgkb (integer (kind = 4) ido, integer (kind = 4) ip, integer (kind = 4) l1, integer (kind = 4) lid, integer (kind = 4) na, real (kind = 8), dimension(in1,l1,ip,ido) cc, real (kind = 8), dimension(in1,lid,ip) cc1, integer (kind = 4) in1, real (kind = 8), dimension(in2,l1,ido,ip) ch, real (kind = 8), dimension(in2,lid,ip) ch1, integer (kind = 4) in2, real (kind = 8), dimension(ido,ip-1,2) wa)
Definition at line 1140 of file fftpack5.1d.f90.
Referenced by c1fm1b().
c1fgkf()
subroutine c1fgkf (integer (kind = 4) ido, integer (kind = 4) ip, integer (kind = 4) l1, integer (kind = 4) lid, integer (kind = 4) na, real (kind = 8), dimension(in1,l1,ip,ido) cc, real (kind = 8), dimension(in1,lid,ip) cc1, integer (kind = 4) in1, real (kind = 8), dimension(in2,l1,ido,ip) ch, real (kind = 8), dimension(in2,lid,ip) ch1, integer (kind = 4) in2, real (kind = 8), dimension(ido,ip-1,2) wa)
Definition at line 1313 of file fftpack5.1d.f90.
Referenced by c1fm1f().
c1fm1b()
subroutine c1fm1b (integer (kind = 4) n, integer (kind = 4) inc, complex (kind = 8), dimension(*) c, real (kind = 8), dimension(*) ch, real (kind = 8), dimension(*) wa, real (kind = 8) fnf, real (kind = 8), dimension(*) fac)
Definition at line 1498 of file fftpack5.1d.f90.
References c1f2kb(), c1f3kb(), c1f4kb(), c1f5kb(), and c1fgkb().
Referenced by cfft1b().
c1fm1f()
subroutine c1fm1f (integer (kind = 4) n, integer (kind = 4) inc, complex (kind = 8), dimension(*) c, real (kind = 8), dimension(*) ch, real (kind = 8), dimension(*) wa, real (kind = 8) fnf, real (kind = 8), dimension(*) fac)
Definition at line 1594 of file fftpack5.1d.f90.
References c1f2kf(), c1f3kf(), c1f4kf(), c1f5kf(), and c1fgkf().
Referenced by cfft1f().
cfft1b()
subroutine cfft1b (integer (kind = 4) n, integer (kind = 4) inc, complex (kind = 8), dimension(lenc) c, integer (kind = 4) lenc, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, real (kind = 8), dimension(lenwrk) work, integer (kind = 4) lenwrk, integer (kind = 4) ier)
Definition at line 1690 of file fftpack5.1d.f90.
References c1fm1b(), and xerfft().
Referenced by test01().
cfft1f()
subroutine cfft1f (integer (kind = 4) n, integer (kind = 4) inc, complex (kind = 8), dimension(lenc) c, integer (kind = 4) lenc, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, real (kind = 8), dimension(lenwrk) work, integer (kind = 4) lenwrk, integer (kind = 4) ier)
Definition at line 1807 of file fftpack5.1d.f90.
References c1fm1f(), and xerfft().
Referenced by test01().
cfft1i()
subroutine cfft1i (integer (kind = 4) n, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, integer (kind = 4) ier)
Definition at line 1922 of file fftpack5.1d.f90.
References r4_mcfti1(), and xerfft().
Referenced by test01().
cfft2b()
subroutine cfft2b (integer (kind = 4) ldim, integer (kind = 4) l, integer (kind = 4) m, complex (kind = 8), dimension(ldim,m) c, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, real (kind = 8), dimension(lenwrk) work, integer (kind = 4) lenwrk, integer (kind = 4) ier)
Definition at line 2005 of file fftpack5.1d.f90.
References cfftmb(), and xerfft().
Referenced by test02().
cfft2f()
subroutine cfft2f (integer (kind = 4) ldim, integer (kind = 4) l, integer (kind = 4) m, complex (kind = 8), dimension(ldim,m) c, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, real (kind = 8), dimension(lenwrk) work, integer (kind = 4) lenwrk, integer (kind = 4) ier)
Definition at line 2150 of file fftpack5.1d.f90.
References cfftmf(), and xerfft().
Referenced by test02().
cfft2i()
subroutine cfft2i (integer (kind = 4) l, integer (kind = 4) m, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, integer (kind = 4) ier)
Definition at line 2296 of file fftpack5.1d.f90.
References cfftmi(), and xerfft().
Referenced by test02().
cfftmb()
subroutine cfftmb (integer (kind = 4) lot, integer (kind = 4) jump, integer (kind = 4) n, integer (kind = 4) inc, complex (kind = 8), dimension(lenc) c, integer (kind = 4) lenc, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, real (kind = 8), dimension(lenwrk) work, integer (kind = 4) lenwrk, integer (kind = 4) ier)
Definition at line 2404 of file fftpack5.1d.f90.
References cmfm1b(), and xerfft().
Referenced by cfft2b(), rfft2b(), and test03().
cfftmf()
subroutine cfftmf (integer (kind = 4) lot, integer (kind = 4) jump, integer (kind = 4) n, integer (kind = 4) inc, complex (kind = 8), dimension(lenc) c, integer (kind = 4) lenc, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, real (kind = 8), dimension(lenwrk) work, integer (kind = 4) lenwrk, integer (kind = 4) ier)
Definition at line 2540 of file fftpack5.1d.f90.
References cmfm1f(), and xerfft().
Referenced by cfft2f(), rfft2f(), and test03().
cfftmi()
subroutine cfftmi (integer (kind = 4) n, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, integer (kind = 4) ier)
Definition at line 2675 of file fftpack5.1d.f90.
References r4_mcfti1(), and xerfft().
Referenced by cfft2i(), rfft2i(), and test03().
cmf2kb()
subroutine cmf2kb (integer (kind = 4) lot, integer (kind = 4) ido, integer (kind = 4) l1, integer (kind = 4) na, real (kind = 8), dimension(2,in1,l1,ido,2) cc, integer (kind = 4) im1, integer (kind = 4) in1, real (kind = 8), dimension(2,in2,l1,2,ido) ch, integer (kind = 4) im2, integer (kind = 4) in2, real (kind = 8), dimension(ido,1,2) wa)
Definition at line 2756 of file fftpack5.1d.f90.
Referenced by cmfm1b().
cmf2kf()
subroutine cmf2kf (integer (kind = 4) lot, integer (kind = 4) ido, integer (kind = 4) l1, integer (kind = 4) na, real (kind = 8), dimension(2,in1,l1,ido,2) cc, integer (kind = 4) im1, integer (kind = 4) in1, real (kind = 8), dimension(2,in2,l1,2,ido) ch, integer (kind = 4) im2, integer (kind = 4) in2, real (kind = 8), dimension(ido,1,2) wa)
Definition at line 2864 of file fftpack5.1d.f90.
Referenced by cmfm1f().
cmf3kb()
subroutine cmf3kb (integer (kind = 4) lot, integer (kind = 4) ido, integer (kind = 4) l1, integer (kind = 4) na, real (kind = 8), dimension(2,in1,l1,ido,3) cc, integer (kind = 4) im1, integer (kind = 4) in1, real (kind = 8), dimension(2,in2,l1,3,ido) ch, integer (kind = 4) im2, integer (kind = 4) in2, real (kind = 8), dimension(ido,2,2) wa)
Definition at line 2986 of file fftpack5.1d.f90.
Referenced by cmfm1b().
cmf3kf()
subroutine cmf3kf (integer (kind = 4) lot, integer (kind = 4) ido, integer (kind = 4) l1, integer (kind = 4) na, real (kind = 8), dimension(2,in1,l1,ido,3) cc, integer (kind = 4) im1, integer (kind = 4) in1, real (kind = 8), dimension(2,in2,l1,3,ido) ch, integer (kind = 4) im2, integer (kind = 4) in2, real (kind = 8), dimension(ido,2,2) wa)
Definition at line 3122 of file fftpack5.1d.f90.
Referenced by cmfm1f().
cmf4kb()
subroutine cmf4kb (integer (kind = 4) lot, integer (kind = 4) ido, integer (kind = 4) l1, integer (kind = 4) na, real (kind = 8), dimension(2,in1,l1,ido,4) cc, integer (kind = 4) im1, integer (kind = 4) in1, real (kind = 8), dimension(2,in2,l1,4,ido) ch, integer (kind = 4) im2, integer (kind = 4) in2, real (kind = 8), dimension(ido,3,2) wa)
Definition at line 3278 of file fftpack5.1d.f90.
Referenced by cmfm1b().
cmf4kf()
subroutine cmf4kf (integer (kind = 4) lot, integer (kind = 4) ido, integer (kind = 4) l1, integer (kind = 4) na, real (kind = 8), dimension(2,in1,l1,ido,4) cc, integer (kind = 4) im1, integer (kind = 4) in1, real (kind = 8), dimension(2,in2,l1,4,ido) ch, integer (kind = 4) im2, integer (kind = 4) in2, real (kind = 8), dimension(ido,3,2) wa)
Definition at line 3432 of file fftpack5.1d.f90.
Referenced by cmfm1f().
cmf5kb()
subroutine cmf5kb (integer (kind = 4) lot, integer (kind = 4) ido, integer (kind = 4) l1, integer (kind = 4) na, real (kind = 8), dimension(2,in1,l1,ido,5) cc, integer (kind = 4) im1, integer (kind = 4) in1, real (kind = 8), dimension(2,in2,l1,5,ido) ch, integer (kind = 4) im2, integer (kind = 4) in2, real (kind = 8), dimension(ido,4,2) wa)
Definition at line 3608 of file fftpack5.1d.f90.
Referenced by cmfm1b().
cmf5kf()
subroutine cmf5kf (integer (kind = 4) lot, integer (kind = 4) ido, integer (kind = 4) l1, integer (kind = 4) na, real (kind = 8), dimension(2,in1,l1,ido,5) cc, integer (kind = 4) im1, integer (kind = 4) in1, real (kind = 8), dimension(2,in2,l1,5,ido) ch, integer (kind = 4) im2, integer (kind = 4) in2, real (kind = 8), dimension(ido,4,2) wa)
Definition at line 3808 of file fftpack5.1d.f90.
Referenced by cmfm1f().
cmfgkb()
subroutine cmfgkb (integer (kind = 4) lot, integer (kind = 4) ido, integer (kind = 4) ip, integer (kind = 4) l1, integer (kind = 4) lid, integer (kind = 4) na, real (kind = 8), dimension(2,in1,l1,ip,ido) cc, real (kind = 8), dimension(2,in1,lid,ip) cc1, integer (kind = 4) im1, integer (kind = 4) in1, real (kind = 8), dimension(2,in2,l1,ido,ip) ch, real (kind = 8), dimension(2,in2,lid,ip) ch1, integer (kind = 4) im2, integer (kind = 4) in2, real (kind = 8), dimension(ido,ip-1,2) wa)
Definition at line 4044 of file fftpack5.1d.f90.
Referenced by cmfm1b().
cmfgkf()
subroutine cmfgkf (integer (kind = 4) lot, integer (kind = 4) ido, integer (kind = 4) ip, integer (kind = 4) l1, integer (kind = 4) lid, integer (kind = 4) na, real (kind = 8), dimension(2,in1,l1,ip,ido) cc, real (kind = 8), dimension(2,in1,lid,ip) cc1, integer (kind = 4) im1, integer (kind = 4) in1, real (kind = 8), dimension(2,in2,l1,ido,ip) ch, real (kind = 8), dimension(2,in2,lid,ip) ch1, integer (kind = 4) im2, integer (kind = 4) in2, real (kind = 8), dimension(ido,ip-1,2) wa)
Definition at line 4263 of file fftpack5.1d.f90.
Referenced by cmfm1f().
cmfm1b()
subroutine cmfm1b (integer (kind = 4) lot, integer (kind = 4) jump, integer (kind = 4) n, integer (kind = 4) inc, complex (kind = 8), dimension(*) c, real (kind = 8), dimension(*) ch, real (kind = 8), dimension(*) wa, real (kind = 8) fnf, real (kind = 8), dimension(*) fac)
Definition at line 4497 of file fftpack5.1d.f90.
References cmf2kb(), cmf3kb(), cmf4kb(), cmf5kb(), and cmfgkb().
Referenced by cfftmb().
cmfm1f()
subroutine cmfm1f (integer (kind = 4) lot, integer (kind = 4) jump, integer (kind = 4) n, integer (kind = 4) inc, complex (kind = 8), dimension(*) c, real (kind = 8), dimension(*) ch, real (kind = 8), dimension(*) wa, real (kind = 8) fnf, real (kind = 8), dimension(*) fac)
Definition at line 4592 of file fftpack5.1d.f90.
References cmf2kf(), cmf3kf(), cmf4kf(), cmf5kf(), and cmfgkf().
Referenced by cfftmf().
cosq1b()
subroutine cosq1b (integer (kind = 4) n, integer (kind = 4) inc, real (kind = 8), dimension(inc,*) x, integer (kind = 4) lenx, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, real (kind = 8), dimension(lenwrk) work, integer (kind = 4) lenwrk, integer (kind = 4) ier)
Definition at line 4687 of file fftpack5.1d.f90.
References cosqb1(), and xerfft().
Referenced by sinq1b(), and test04().
cosq1f()
subroutine cosq1f (integer (kind = 4) n, integer (kind = 4) inc, real (kind = 8), dimension(inc,*) x, integer (kind = 4) lenx, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, real (kind = 8), dimension(lenwrk) work, integer (kind = 4) lenwrk, integer (kind = 4) ier)
Definition at line 4818 of file fftpack5.1d.f90.
References cosqf1(), and xerfft().
Referenced by sinq1f(), and test04().
cosq1i()
subroutine cosq1i (integer (kind = 4) n, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, integer (kind = 4) ier)
Definition at line 4944 of file fftpack5.1d.f90.
References rfft1i(), and xerfft().
Referenced by sinq1i(), and test04().
cosqb1()
subroutine cosqb1 (integer (kind = 4) n, integer (kind = 4) inc, real (kind = 8), dimension(inc,*) x, real (kind = 8), dimension(*) wsave, real (kind = 8), dimension(*) work, integer (kind = 4) ier)
Definition at line 5044 of file fftpack5.1d.f90.
References rfft1b(), and xerfft().
Referenced by cosq1b().
cosqf1()
subroutine cosqf1 (integer (kind = 4) n, integer (kind = 4) inc, real (kind = 8), dimension(inc,*) x, real (kind = 8), dimension(*) wsave, real (kind = 8), dimension(*) work, integer (kind = 4) ier)
Definition at line 5149 of file fftpack5.1d.f90.
References rfft1f(), and xerfft().
Referenced by cosq1f().
cosqmb()
subroutine cosqmb (integer (kind = 4) lot, integer (kind = 4) jump, integer (kind = 4) n, integer (kind = 4) inc, real (kind = 8), dimension(inc,*) x, integer (kind = 4) lenx, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, real (kind = 8), dimension(lenwrk) work, integer (kind = 4) lenwrk, integer (kind = 4) ier)
Definition at line 5251 of file fftpack5.1d.f90.
References mcsqb1(), and xerfft().
Referenced by sinqmb(), and test05().
cosqmf()
subroutine cosqmf (integer (kind = 4) lot, integer (kind = 4) jump, integer (kind = 4) n, integer (kind = 4) inc, real (kind = 8), dimension(inc,*) x, integer (kind = 4) lenx, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, real (kind = 8), dimension(lenwrk) work, integer (kind = 4) lenwrk, integer (kind = 4) ier)
Definition at line 5406 of file fftpack5.1d.f90.
References mcsqf1(), and xerfft().
Referenced by sinqmf(), and test05().
cosqmi()
subroutine cosqmi (integer (kind = 4) n, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, integer (kind = 4) ier)
Definition at line 5561 of file fftpack5.1d.f90.
References rfftmi(), and xerfft().
Referenced by sinqmi(), and test05().
cost1b()
subroutine cost1b (integer (kind = 4) n, integer (kind = 4) inc, real (kind = 8), dimension(inc,*) x, integer (kind = 4) lenx, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, real (kind = 8), dimension(lenwrk) work, integer (kind = 4) lenwrk, integer (kind = 4) ier)
Definition at line 5662 of file fftpack5.1d.f90.
References costb1(), and xerfft().
Referenced by convert_from_rayleigh_rst::cvt_each_field_from_rayleigh(), and test06().
cost1f()
subroutine cost1f (integer (kind = 4) n, integer (kind = 4) inc, real (kind = 8), dimension(inc,*) x, integer (kind = 4) lenx, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, real (kind = 8), dimension(lenwrk) work, integer (kind = 4) lenwrk, integer (kind = 4) ier)
Definition at line 5784 of file fftpack5.1d.f90.
References costf1(), and xerfft().
Referenced by test06().
cost1i()
subroutine cost1i (integer (kind = 4) n, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, integer (kind = 4) ier)
Definition at line 5906 of file fftpack5.1d.f90.
References rfft1i(), and xerfft().
Referenced by t_convert_from_rayleigh::init_fftpack_4_cheby(), and test06().
costb1()
subroutine costb1 (integer (kind = 4) n, integer (kind = 4) inc, real (kind = 8), dimension(inc,*) x, real (kind = 8), dimension(*) wsave, real (kind = 8), dimension(*) work, integer (kind = 4) ier)
Definition at line 6020 of file fftpack5.1d.f90.
References rfft1f(), and xerfft().
Referenced by cost1b().
costf1()
subroutine costf1 (integer (kind = 4) n, integer (kind = 4) inc, real (kind = 8), dimension(inc,*) x, real (kind = 8), dimension(*) wsave, real (kind = 8), dimension(*) work, integer (kind = 4) ier)
Definition at line 6153 of file fftpack5.1d.f90.
References rfft1f(), and xerfft().
Referenced by cost1f().
costmb()
subroutine costmb (integer (kind = 4) lot, integer (kind = 4) jump, integer (kind = 4) n, integer (kind = 4) inc, real (kind = 8), dimension(inc,*) x, integer (kind = 4) lenx, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, real (kind = 8), dimension(lenwrk) work, integer (kind = 4) lenwrk, integer (kind = 4) ier)
Definition at line 6279 of file fftpack5.1d.f90.
References mcstb1(), and xerfft().
Referenced by test07().
costmf()
subroutine costmf (integer (kind = 4) lot, integer (kind = 4) jump, integer (kind = 4) n, integer (kind = 4) inc, real (kind = 8), dimension(inc,*) x, integer (kind = 4) lenx, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, real (kind = 8), dimension(lenwrk) work, integer (kind = 4) lenwrk, integer (kind = 4) ier)
Definition at line 6418 of file fftpack5.1d.f90.
References mcstf1(), and xerfft().
Referenced by test07().
costmi()
subroutine costmi (integer (kind = 4) n, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, integer (kind = 4) ier)
Definition at line 6557 of file fftpack5.1d.f90.
References rfftmi(), and xerfft().
Referenced by test07().
mcsqb1()
subroutine mcsqb1 (integer (kind = 4) lot, integer (kind = 4) jump, integer (kind = 4) n, integer (kind = 4) inc, real (kind = 8), dimension(inc,*) x, real (kind = 8), dimension(*) wsave, real (kind = 8), dimension(lot,*) work, integer (kind = 4) ier)
Definition at line 6671 of file fftpack5.1d.f90.
References rfftmb(), and xerfft().
Referenced by cosqmb().
mcsqf1()
subroutine mcsqf1 (integer (kind = 4) lot, integer (kind = 4) jump, integer (kind = 4) n, integer (kind = 4) inc, real (kind = 8), dimension(inc,*) x, real (kind = 8), dimension(*) wsave, real (kind = 8), dimension(lot,*) work, integer (kind = 4) ier)
Definition at line 6800 of file fftpack5.1d.f90.
References rfftmf(), and xerfft().
Referenced by cosqmf().
mcstb1()
subroutine mcstb1 (integer (kind = 4) lot, integer (kind = 4) jump, integer (kind = 4) n, integer (kind = 4) inc, real (kind = 8), dimension(inc,*) x, real (kind = 8), dimension(*) wsave, real (kind = 8), dimension(*) dsum, real (kind = 8), dimension(*) work, integer (kind = 4) ier)
Definition at line 6928 of file fftpack5.1d.f90.
References rfftmf(), and xerfft().
Referenced by costmb().
mcstf1()
subroutine mcstf1 (integer (kind = 4) lot, integer (kind = 4) jump, integer (kind = 4) n, integer (kind = 4) inc, real (kind = 8), dimension(inc,*) x, real (kind = 8), dimension(*) wsave, real (kind = 8), dimension(*) dsum, real (kind = 8), dimension(*) work, integer (kind = 4) ier)
Definition at line 7102 of file fftpack5.1d.f90.
References rfftmf(), and xerfft().
Referenced by costmf().
mradb2()
subroutine mradb2 (integer (kind = 4) m, integer (kind = 4) ido, integer (kind = 4) l1, real (kind = 8), dimension(in1,ido,2,l1) cc, integer (kind = 4) im1, integer (kind = 4) in1, real (kind = 8), dimension(in2,ido,l1,2) ch, integer (kind = 4) im2, integer (kind = 4) in2, real (kind = 8), dimension(ido) wa1)
Definition at line 7268 of file fftpack5.1d.f90.
Referenced by mrftb1().
mradb3()
subroutine mradb3 (integer (kind = 4) m, integer (kind = 4) ido, integer (kind = 4) l1, real (kind = 8), dimension(in1,ido,3,l1) cc, integer (kind = 4) im1, integer (kind = 4) in1, real (kind = 8), dimension(in2,ido,l1,3) ch, integer (kind = 4) im2, integer (kind = 4) in2, real (kind = 8), dimension(ido) wa1, real (kind = 8), dimension(ido) wa2)
Definition at line 7369 of file fftpack5.1d.f90.
Referenced by mrftb1().
mradb4()
subroutine mradb4 (integer (kind = 4) m, integer (kind = 4) ido, integer (kind = 4) l1, real (kind = 8), dimension(in1,ido,4,l1) cc, integer (kind = 4) im1, integer (kind = 4) in1, real (kind = 8), dimension(in2,ido,l1,4) ch, integer (kind = 4) im2, integer (kind = 4) in2, real (kind = 8), dimension(ido) wa1, real (kind = 8), dimension(ido) wa2, real (kind = 8), dimension(ido) wa3)
Definition at line 7497 of file fftpack5.1d.f90.
Referenced by mrftb1().
mradb5()
subroutine mradb5 (integer (kind = 4) m, integer (kind = 4) ido, integer (kind = 4) l1, real (kind = 8), dimension(in1,ido,5,l1) cc, integer (kind = 4) im1, integer (kind = 4) in1, real (kind = 8), dimension(in2,ido,l1,5) ch, integer (kind = 4) im2, integer (kind = 4) in2, real (kind = 8), dimension(ido) wa1, real (kind = 8), dimension(ido) wa2, real (kind = 8), dimension(ido) wa3, real (kind = 8), dimension(ido) wa4)
Definition at line 7628 of file fftpack5.1d.f90.
Referenced by mrftb1().
mradbg()
subroutine mradbg (integer (kind = 4) m, integer (kind = 4) ido, integer (kind = 4) ip, integer (kind = 4) l1, integer (kind = 4) idl1, real (kind = 8), dimension(in1,ido,ip,l1) cc, real (kind = 8), dimension(in1,ido,l1,ip) c1, real (kind = 8), dimension(in1,idl1,ip) c2, integer (kind = 4) im1, integer (kind = 4) in1, real (kind = 8), dimension(in2,ido,l1,ip) ch, real (kind = 8), dimension(in2,idl1,ip) ch2, integer (kind = 4) im2, integer (kind = 4) in2, real (kind = 8), dimension(ido) wa)
Definition at line 7813 of file fftpack5.1d.f90.
Referenced by mrftb1().
mradf2()
subroutine mradf2 (integer (kind = 4) m, integer (kind = 4) ido, integer (kind = 4) l1, real (kind = 8), dimension(in1,ido,l1,2) cc, integer (kind = 4) im1, integer (kind = 4) in1, real (kind = 8), dimension(in2,ido,2,l1) ch, integer (kind = 4) im2, integer (kind = 4) in2, real (kind = 8), dimension(ido) wa1)
Definition at line 8122 of file fftpack5.1d.f90.
Referenced by mrftf1().
mradf3()
subroutine mradf3 (integer (kind = 4) m, integer (kind = 4) ido, integer (kind = 4) l1, real (kind = 8), dimension(in1,ido,l1,3) cc, integer (kind = 4) im1, integer (kind = 4) in1, real (kind = 8), dimension(in2,ido,3,l1) ch, integer (kind = 4) im2, integer (kind = 4) in2, real (kind = 8), dimension(ido) wa1, real (kind = 8), dimension(ido) wa2)
Definition at line 8223 of file fftpack5.1d.f90.
Referenced by mrftf1().
mradf4()
subroutine mradf4 (integer (kind = 4) m, integer (kind = 4) ido, integer (kind = 4) l1, real (kind = 8), dimension(in1,ido,l1,4) cc, integer (kind = 4) im1, integer (kind = 4) in1, real (kind = 8), dimension(in2,ido,4,l1) ch, integer (kind = 4) im2, integer (kind = 4) in2, real (kind = 8), dimension(ido) wa1, real (kind = 8), dimension(ido) wa2, real (kind = 8), dimension(ido) wa3)
Definition at line 8348 of file fftpack5.1d.f90.
Referenced by mrftf1().
mradf5()
subroutine mradf5 (integer (kind = 4) m, integer (kind = 4) ido, integer (kind = 4) l1, real (kind = 8), dimension(in1,ido,l1,5) cc, integer (kind = 4) im1, integer (kind = 4) in1, real (kind = 8), dimension(in2,ido,5,l1) ch, integer (kind = 4) im2, integer (kind = 4) in2, real (kind = 8), dimension(ido) wa1, real (kind = 8), dimension(ido) wa2, real (kind = 8), dimension(ido) wa3, real (kind = 8), dimension(ido) wa4)
Definition at line 8496 of file fftpack5.1d.f90.
Referenced by mrftf1().
mradfg()
subroutine mradfg (integer (kind = 4) m, integer (kind = 4) ido, integer (kind = 4) ip, integer (kind = 4) l1, integer (kind = 4) idl1, real (kind = 8), dimension(in1,ido,ip,l1) cc, real (kind = 8), dimension(in1,ido,l1,ip) c1, real (kind = 8), dimension(in1,idl1,ip) c2, integer (kind = 4) im1, integer (kind = 4) in1, real (kind = 8), dimension(in2,ido,l1,ip) ch, real (kind = 8), dimension(in2,idl1,ip) ch2, integer (kind = 4) im2, integer (kind = 4) in2, real (kind = 8), dimension(ido) wa)
Definition at line 8692 of file fftpack5.1d.f90.
Referenced by mrftf1().
mrftb1()
subroutine mrftb1 (integer (kind = 4) m, integer (kind = 4) im, integer (kind = 4) n, integer (kind = 4) in, real (kind = 8), dimension(in,*) c, real (kind = 8), dimension(m,*) ch, real (kind = 8), dimension(n) wa, real (kind = 8), dimension(15) fac)
Definition at line 9009 of file fftpack5.1d.f90.
References mradb2(), mradb3(), mradb4(), mradb5(), and mradbg().
Referenced by rfftmb().
mrftf1()
subroutine mrftf1 (integer (kind = 4) m, integer (kind = 4) im, integer (kind = 4) n, integer (kind = 4) in, real (kind = 8), dimension(in,*) c, real (kind = 8), dimension(m,*) ch, real (kind = 8), dimension(n) wa, real (kind = 8), dimension(15) fac)
Definition at line 9167 of file fftpack5.1d.f90.
References mradf2(), mradf3(), mradf4(), mradf5(), and mradfg().
Referenced by rfftmf().
mrfti1()
subroutine mrfti1 (integer (kind = 4) n, real (kind = 8), dimension(n) wa, real (kind = 8), dimension(15) fac)
Definition at line 9339 of file fftpack5.1d.f90.
Referenced by rfftmi().
msntb1()
subroutine msntb1 (integer (kind = 4) lot, integer (kind = 4) jump, integer (kind = 4) n, integer (kind = 4) inc, real (kind = 8), dimension(inc,*) x, real (kind = 8), dimension(*) wsave, real (kind = 8), dimension(*) dsum, real (kind = 8), dimension(lot,*) xh, real (kind = 8), dimension(*) work, integer (kind = 4) ier)
Definition at line 9472 of file fftpack5.1d.f90.
References rfftmf(), and xerfft().
Referenced by sintmb().
msntf1()
subroutine msntf1 (integer (kind = 4) lot, integer (kind = 4) jump, integer (kind = 4) n, integer (kind = 4) inc, real (kind = 8), dimension(inc,*) x, real (kind = 8), dimension(*) wsave, real (kind = 8), dimension(*) dsum, real (kind = 8), dimension(lot,*) xh, real (kind = 8), dimension(*) work, integer (kind = 4) ier)
Definition at line 9619 of file fftpack5.1d.f90.
References rfftmf(), and xerfft().
Referenced by sintmf().
r1f2kb()
subroutine r1f2kb (integer (kind = 4) ido, integer (kind = 4) l1, real (kind = 8), dimension(in1,ido,2,l1) cc, integer (kind = 4) in1, real (kind = 8), dimension(in2,ido,l1,2) ch, integer (kind = 4) in2, real (kind = 8), dimension(ido) wa1)
Definition at line 9765 of file fftpack5.1d.f90.
Referenced by rfftb1().
r1f2kf()
subroutine r1f2kf (integer (kind = 4) ido, integer (kind = 4) l1, real (kind = 8), dimension(in1,ido,l1,2) cc, integer (kind = 4) in1, real (kind = 8), dimension(in2,ido,2,l1) ch, integer (kind = 4) in2, real (kind = 8), dimension(ido) wa1)
Definition at line 9845 of file fftpack5.1d.f90.
Referenced by rfftf1().
r1f3kb()
subroutine r1f3kb (integer (kind = 4) ido, integer (kind = 4) l1, real (kind = 8), dimension(in1,ido,3,l1) cc, integer (kind = 4) in1, real (kind = 8), dimension(in2,ido,l1,3) ch, integer (kind = 4) in2, real (kind = 8), dimension(ido) wa1, real (kind = 8), dimension(ido) wa2)
Definition at line 9924 of file fftpack5.1d.f90.
Referenced by rfftb1().
r1f3kf()
subroutine r1f3kf (integer (kind = 4) ido, integer (kind = 4) l1, real (kind = 8), dimension(in1,ido,l1,3) cc, integer (kind = 4) in1, real (kind = 8), dimension(in2,ido,3,l1) ch, integer (kind = 4) in2, real (kind = 8), dimension(ido) wa1, real (kind = 8), dimension(ido) wa2)
Definition at line 10035 of file fftpack5.1d.f90.
Referenced by rfftf1().
r1f4kb()
subroutine r1f4kb (integer (kind = 4) ido, integer (kind = 4) l1, real (kind = 8), dimension(in1,ido,4,l1) cc, integer (kind = 4) in1, real (kind = 8), dimension(in2,ido,l1,4) ch, integer (kind = 4) in2, real (kind = 8), dimension(ido) wa1, real (kind = 8), dimension(ido) wa2, real (kind = 8), dimension(ido) wa3)
Definition at line 10144 of file fftpack5.1d.f90.
Referenced by rfftb1().
r1f4kf()
subroutine r1f4kf (integer (kind = 4) ido, integer (kind = 4) l1, real (kind = 8), dimension(in1,ido,l1,4) cc, integer (kind = 4) in1, real (kind = 8), dimension(in2,ido,4,l1) ch, integer (kind = 4) in2, real (kind = 8), dimension(ido) wa1, real (kind = 8), dimension(ido) wa2, real (kind = 8), dimension(ido) wa3)
Definition at line 10257 of file fftpack5.1d.f90.
Referenced by rfftf1().
r1f5kb()
subroutine r1f5kb (integer (kind = 4) ido, integer (kind = 4) l1, real (kind = 8), dimension(in1,ido,5,l1) cc, integer (kind = 4) in1, real (kind = 8), dimension(in2,ido,l1,5) ch, integer (kind = 4) in2, real (kind = 8), dimension(ido) wa1, real (kind = 8), dimension(ido) wa2, real (kind = 8), dimension(ido) wa3, real (kind = 8), dimension(ido) wa4)
Definition at line 10370 of file fftpack5.1d.f90.
Referenced by rfftb1().
r1f5kf()
subroutine r1f5kf (integer (kind = 4) ido, integer (kind = 4) l1, real (kind = 8), dimension(in1,ido,l1,5) cc, integer (kind = 4) in1, real (kind = 8), dimension(in2,ido,5,l1) ch, integer (kind = 4) in2, real (kind = 8), dimension(ido) wa1, real (kind = 8), dimension(ido) wa2, real (kind = 8), dimension(ido) wa3, real (kind = 8), dimension(ido) wa4)
Definition at line 10540 of file fftpack5.1d.f90.
Referenced by rfftf1().
r1fgkb()
subroutine r1fgkb (integer (kind = 4) ido, integer (kind = 4) ip, integer (kind = 4) l1, integer (kind = 4) idl1, real (kind = 8), dimension(in1,ido,ip,l1) cc, real (kind = 8), dimension(in1,ido,l1,ip) c1, real (kind = 8), dimension(in1,idl1,ip) c2, integer (kind = 4) in1, real (kind = 8), dimension(in2,ido,l1,ip) ch, real (kind = 8), dimension(in2,idl1,ip) ch2, integer (kind = 4) in2, real (kind = 8), dimension(ido) wa)
Definition at line 10721 of file fftpack5.1d.f90.
Referenced by rfftb1().
r1fgkf()
subroutine r1fgkf (integer (kind = 4) ido, integer (kind = 4) ip, integer (kind = 4) l1, integer (kind = 4) idl1, real (kind = 8), dimension(in1,ido,ip,l1) cc, real (kind = 8), dimension(in1,ido,l1,ip) c1, real (kind = 8), dimension(in1,idl1,ip) c2, integer (kind = 4) in1, real (kind = 8), dimension(in2,ido,l1,ip) ch, real (kind = 8), dimension(in2,idl1,ip) ch2, integer (kind = 4) in2, real (kind = 8), dimension(ido) wa)
Definition at line 10965 of file fftpack5.1d.f90.
Referenced by rfftf1().
r2w()
subroutine r2w (integer ldr, integer ldw, integer l, integer m, real, dimension(ldr,m) r, real, dimension(ldw,m) w)
Definition at line 11210 of file fftpack5.1d.f90.
Referenced by rfft2b(), and rfft2f().
r4_factor()
subroutine r4_factor (integer (kind = 4) n, integer (kind = 4) nf, real (kind = 8), dimension(*) fac)
Definition at line 11259 of file fftpack5.1d.f90.
Referenced by r4_mcfti1().
r4_mcfti1()
subroutine r4_mcfti1 (integer (kind = 4) n, real (kind = 8), dimension(*) wa, real (kind = 8) fnf, real (kind = 8), dimension(*) fac)
Definition at line 11351 of file fftpack5.1d.f90.
References r4_factor(), and r4_tables().
Referenced by cfft1i(), and cfftmi().
r4_tables()
subroutine r4_tables (integer (kind = 4) ido, integer (kind = 4) ip, real (kind = 8), dimension(ido,ip-1,2) wa)
Definition at line 11420 of file fftpack5.1d.f90.
Referenced by r4_mcfti1().
r8_factor()
subroutine r8_factor (integer (kind = 4) n, integer (kind = 4) nf, real (kind = 8), dimension(*) fac)
Definition at line 11494 of file fftpack5.1d.f90.
Referenced by r8_mcfti1().
r8_mcfti1()
subroutine r8_mcfti1 (integer (kind = 4) n, real (kind = 8), dimension(*) wa, real (kind = 8) fnf, real (kind = 8), dimension(*) fac)
Definition at line 11584 of file fftpack5.1d.f90.
References r8_factor(), and r8_tables().
r8_tables()
subroutine r8_tables (integer (kind = 4) ido, integer (kind = 4) ip, real (kind = 8), dimension(ido,ip-1,2) wa)
Definition at line 11651 of file fftpack5.1d.f90.
Referenced by r8_mcfti1().
rfft1b()
subroutine rfft1b (integer (kind = 4) n, integer (kind = 4) inc, real (kind = 8), dimension(lenr) r, integer (kind = 4) lenr, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, real (kind = 8), dimension(lenwrk) work, integer (kind = 4) lenwrk, integer (kind = 4) ier)
Definition at line 11723 of file fftpack5.1d.f90.
References rfftb1(), and xerfft().
Referenced by cosqb1(), and test09().
rfft1f()
subroutine rfft1f (integer (kind = 4) n, integer (kind = 4) inc, real (kind = 8), dimension(lenr) r, integer (kind = 4) lenr, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, real (kind = 8), dimension(lenwrk) work, integer (kind = 4) lenwrk, integer (kind = 4) ier)
Definition at line 11832 of file fftpack5.1d.f90.
References rfftf1(), and xerfft().
Referenced by cosqf1(), costb1(), costf1(), sintb1(), sintf1(), and test09().
rfft1i()
subroutine rfft1i (integer (kind = 4) n, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, integer (kind = 4) ier)
Definition at line 11941 of file fftpack5.1d.f90.
References rffti1(), and xerfft().
Referenced by cosq1i(), cost1i(), sint1i(), and test09().
rfft2b()
subroutine rfft2b (integer (kind = 4) ldim, integer (kind = 4) l, integer (kind = 4) m, real (kind = 8), dimension(ldim,m) r, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, real (kind = 8), dimension(lenwrk) work, integer (kind = 4) lenwrk, integer (kind = 4) ier)
Definition at line 12022 of file fftpack5.1d.f90.
References cfftmb(), r2w(), rfftmb(), w2r(), and xerfft().
Referenced by test10().
rfft2f()
subroutine rfft2f (integer (kind = 4) ldim, integer (kind = 4) l, integer (kind = 4) m, real (kind = 8), dimension(ldim,m) r, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, real (kind = 8), dimension(lenwrk) work, integer (kind = 4) lenwrk, integer (kind = 4) ier)
Definition at line 12234 of file fftpack5.1d.f90.
References cfftmf(), r2w(), rfftmf(), w2r(), and xerfft().
Referenced by test10().
rfft2i()
subroutine rfft2i (integer (kind = 4) l, integer (kind = 4) m, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, integer (kind = 4) ier)
Definition at line 12449 of file fftpack5.1d.f90.
References cfftmi(), rfftmi(), and xerfft().
Referenced by test10().
rfftb1()
subroutine rfftb1 (integer (kind = 4) n, integer (kind = 4) in, real (kind = 8), dimension(in,*) c, real (kind = 8), dimension(*) ch, real (kind = 8), dimension(n) wa, real (kind = 8), dimension(15) fac)
Definition at line 12570 of file fftpack5.1d.f90.
References r1f2kb(), r1f3kb(), r1f4kb(), r1f5kb(), and r1fgkb().
Referenced by rfft1b().
rfftf1()
subroutine rfftf1 (integer (kind = 4) n, integer (kind = 4) in, real (kind = 8), dimension(in,*) c, real (kind = 8), dimension(*) ch, real (kind = 8), dimension(n) wa, real (kind = 8), dimension(15) fac)
Definition at line 12712 of file fftpack5.1d.f90.
References r1f2kf(), r1f3kf(), r1f4kf(), r1f5kf(), and r1fgkf().
Referenced by rfft1f().
rffti1()
subroutine rffti1 (integer (kind = 4) n, real (kind = 8), dimension(n) wa, real (kind = 8), dimension(15) fac)
Definition at line 12854 of file fftpack5.1d.f90.
Referenced by rfft1i().
rfftmb()
subroutine rfftmb (integer (kind = 4) lot, integer (kind = 4) jump, integer (kind = 4) n, integer (kind = 4) inc, real (kind = 8), dimension(lenr) r, integer (kind = 4) lenr, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, real (kind = 8), dimension(lenwrk) work, integer (kind = 4) lenwrk, integer (kind = 4) ier)
Definition at line 12988 of file fftpack5.1d.f90.
References mrftb1(), and xerfft().
Referenced by fftpack5_wrapper::calypso_rfftmb_smp(), mcsqb1(), sph_prt_domain_fftpack5::prt_domain_rfftmb_from_recv(), sph_prt_fftpack5::prt_rfftmb_from_recv(), rfft2b(), sph_rtp_domain_fftpack5::rtp_domain_rfftmb_from_recv(), sph_rtp_fftpack5::rtp_rfftmb_from_recv(), t_sph_component_fftpack5::sph_comp_rfftmb_from_recv(), t_sph_single_fftpack5::sph_single_rfftmb_from_recv(), and test11().
rfftmf()
subroutine rfftmf (integer (kind = 4) lot, integer (kind = 4) jump, integer (kind = 4) n, integer (kind = 4) inc, real (kind = 8), dimension(lenr) r, integer (kind = 4) lenr, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, real (kind = 8), dimension(lenwrk) work, integer (kind = 4) lenwrk, integer (kind = 4) ier)
Definition at line 13120 of file fftpack5.1d.f90.
References mrftf1(), and xerfft().
Referenced by fftpack5_wrapper::calypso_rfftmf_smp(), mcsqf1(), mcstb1(), mcstf1(), msntb1(), msntf1(), sph_prt_domain_fftpack5::prt_domain_rfftmf_to_send(), sph_prt_fftpack5::prt_rfftmf_to_send(), rfft2f(), sph_rtp_domain_fftpack5::rtp_domain_rfftmf_to_send(), sph_rtp_fftpack5::rtp_rfftmf_to_send(), t_sph_component_fftpack5::sph_comp_rfftmf_to_send(), t_sph_single_fftpack5::sph_single_rfftmf_to_send(), and test11().
rfftmi()
subroutine rfftmi (integer (kind = 4) n, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, integer (kind = 4) ier)
Definition at line 13252 of file fftpack5.1d.f90.
References mrfti1(), and xerfft().
Referenced by cosqmi(), costmi(), fftpack5_wrapper::init_calypso_fftpack(), t_sph_component_fftpack5::init_sph_comp_fftpack5(), t_sph_domain_fftpack5::init_sph_domain_fftpack5(), t_sph_fftpack5::init_sph_fftpack5(), t_sph_single_fftpack5::init_sph_single_fftpack5(), rfft2i(), sintmi(), test11(), t_sph_component_fftpack5::verify_sph_comp_fftpack5(), t_sph_domain_fftpack5::verify_sph_domain_fftpack5(), t_sph_fftpack5::verify_sph_fftpack5(), and t_sph_single_fftpack5::verify_sph_single_fftpack5().
sinq1b()
subroutine sinq1b (integer (kind = 4) n, integer (kind = 4) inc, real (kind = 8), dimension(inc,*) x, integer (kind = 4) lenx, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, real (kind = 8), dimension(lenwrk) work, integer (kind = 4) lenwrk, integer (kind = 4) ier)
Definition at line 13334 of file fftpack5.1d.f90.
References cosq1b(), and xerfft().
Referenced by test12().
sinq1f()
subroutine sinq1f (integer (kind = 4) n, integer (kind = 4) inc, real (kind = 8), dimension(inc,*) x, integer (kind = 4) lenx, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, real (kind = 8), dimension(lenwrk) work, integer (kind = 4) lenwrk, integer (kind = 4) ier)
Definition at line 13470 of file fftpack5.1d.f90.
References cosq1f(), and xerfft().
Referenced by test12().
sinq1i()
subroutine sinq1i (integer (kind = 4) n, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, integer (kind = 4) ier)
Definition at line 13604 of file fftpack5.1d.f90.
References cosq1i(), and xerfft().
Referenced by test12().
sinqmb()
subroutine sinqmb (integer (kind = 4) lot, integer (kind = 4) jump, integer (kind = 4) n, integer (kind = 4) inc, real (kind = 8), dimension(inc,*) x, integer (kind = 4) lenx, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, real (kind = 8), dimension(lenwrk) work, integer (kind = 4) lenwrk, integer (kind = 4) ier)
Definition at line 13689 of file fftpack5.1d.f90.
References cosqmb(), and xerfft().
Referenced by test13().
sinqmf()
subroutine sinqmf (integer (kind = 4) lot, integer (kind = 4) jump, integer (kind = 4) n, integer (kind = 4) inc, real (kind = 8), dimension(inc,*) x, integer (kind = 4) lenx, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, real (kind = 8), dimension(lenwrk) work, integer (kind = 4) lenwrk, integer (kind = 4) ier)
Definition at line 13853 of file fftpack5.1d.f90.
References cosqmf(), and xerfft().
Referenced by test13().
sinqmi()
subroutine sinqmi (integer (kind = 4) n, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, integer (kind = 4) ier)
Definition at line 14019 of file fftpack5.1d.f90.
References cosqmi(), and xerfft().
Referenced by test13().
sint1b()
subroutine sint1b (integer (kind = 4) n, integer (kind = 4) inc, real (kind = 8), dimension(inc,*) x, integer (kind = 4) lenx, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, real (kind = 8), dimension(lenwrk) work, integer (kind = 4) lenwrk, integer (kind = 4) ier)
Definition at line 14104 of file fftpack5.1d.f90.
References sintb1(), and xerfft().
Referenced by test14().
sint1f()
subroutine sint1f (integer (kind = 4) n, integer (kind = 4) inc, real (kind = 8), dimension(inc,*) x, integer (kind = 4) lenx, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, real (kind = 8), dimension(lenwrk) work, integer (kind = 4) lenwrk, integer (kind = 4) ier)
Definition at line 14223 of file fftpack5.1d.f90.
References sintf1(), and xerfft().
Referenced by test14().
sint1i()
subroutine sint1i (integer (kind = 4) n, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, integer (kind = 4) ier)
Definition at line 14341 of file fftpack5.1d.f90.
References rfft1i(), and xerfft().
Referenced by test14().
sintb1()
subroutine sintb1 (integer (kind = 4) n, integer (kind = 4) inc, real (kind = 8), dimension(inc,*) x, real (kind = 8), dimension(*) wsave, real (kind = 8), dimension(*) xh, real (kind = 8), dimension(*) work, integer (kind = 4) ier)
Definition at line 14448 of file fftpack5.1d.f90.
References rfft1f(), and xerfft().
Referenced by sint1b().
sintf1()
subroutine sintf1 (integer (kind = 4) n, integer (kind = 4) inc, real (kind = 8), dimension(inc,*) x, real (kind = 8), dimension(*) wsave, real (kind = 8), dimension(*) xh, real (kind = 8), dimension(*) work, integer (kind = 4) ier)
Definition at line 14562 of file fftpack5.1d.f90.
References rfft1f(), and xerfft().
Referenced by sint1f().
sintmb()
subroutine sintmb (integer (kind = 4) lot, integer (kind = 4) jump, integer (kind = 4) n, integer (kind = 4) inc, real (kind = 8), dimension(inc,*) x, integer (kind = 4) lenx, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, real (kind = 8), dimension(lenwrk) work, integer (kind = 4) lenwrk, integer (kind = 4) ier)
Definition at line 14674 of file fftpack5.1d.f90.
References msntb1(), and xerfft().
Referenced by test15().
sintmf()
subroutine sintmf (integer (kind = 4) lot, integer (kind = 4) jump, integer (kind = 4) n, integer (kind = 4) inc, real (kind = 8), dimension(inc,*) x, integer (kind = 4) lenx, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, real (kind = 8), dimension(lenwrk) work, integer (kind = 4) lenwrk, integer (kind = 4) ier)
Definition at line 14816 of file fftpack5.1d.f90.
References msntf1(), and xerfft().
Referenced by test15().
sintmi()
subroutine sintmi (integer (kind = 4) n, real (kind = 8), dimension(lensav) wsave, integer (kind = 4) lensav, integer (kind = 4) ier)
Definition at line 14956 of file fftpack5.1d.f90.
References rfftmi(), and xerfft().
Referenced by test15().
w2r()
subroutine w2r (integer ldr, integer ldw, integer l, integer m, real, dimension(ldr,m) r, real, dimension(ldw,m) w)
Definition at line 15063 of file fftpack5.1d.f90.
Referenced by rfft2b(), and rfft2f().
xercon()
logical function xercon (integer (kind = 4) inc, integer (kind = 4) jump, integer (kind = 4) n, integer (kind = 4) lot)
Definition at line 15118 of file fftpack5.1d.f90.
xerfft()
subroutine xerfft (character (len = *) srname, integer (kind = 4) info)
Definition at line 15203 of file fftpack5.1d.f90.
Referenced by cfft1b(), cfft1f(), cfft1i(), cfft2b(), cfft2f(), cfft2i(), cfftmb(), cfftmf(), cfftmi(), cosq1b(), cosq1f(), cosq1i(), cosqb1(), cosqf1(), cosqmb(), cosqmf(), cosqmi(), cost1b(), cost1f(), cost1i(), costb1(), costf1(), costmb(), costmf(), costmi(), mcsqb1(), mcsqf1(), mcstb1(), mcstf1(), msntb1(), msntf1(), rfft1b(), rfft1f(), rfft1i(), rfft2b(), rfft2f(), rfft2i(), rfftmb(), rfftmf(), rfftmi(), sinq1b(), sinq1f(), sinq1i(), sinqmb(), sinqmf(), sinqmi(), sint1b(), sint1f(), sint1i(), sintb1(), sintf1(), sintmb(), sintmf(), and sintmi().