CALYPSO: self_buoyancy_on_sphere Module Reference
self_buoyancy_on_sphere Module Reference
Evaluate buoyancy at specific radius.
Functions/Subroutines
subroutine r_buoyancy_on_sphere (iflag_4_gravity, iflag_4_composit_buo, kr, sph_rj, ipol_base, ipol_div_frc, coef_buo, coef_comp_buo, ref_param_T, ref_param_C, rj_fld)
subroutine, private cal_r_double_buo_on_sphere (kr, coef_buo, coef_comp_buo, is_t, is_c, is_fr, nidx_rj, radius_1d_rj_r, nnod_rj, ntot_phys_rj, d_rj)
subroutine cal_r_buoyancy_on_sphere (kr, coef, is_fld, is_fr, nidx_rj, radius_1d_rj_r, nnod_rj, ntot_phys_rj, d_rj)
Detailed Description
Evaluate buoyancy at specific radius.
      subroutine r_buoyancy_on_sphere                                 &
     &         (iflag_4_gravity, iflag_4_composit_buo, kr, sph_rj,    &
     &          ipol_base, ipol_div_frc, coef_buo, coef_comp_buo,     &
     &          ref_param_T, ref_param_C, rj_fld)
        type(fluid_property), intent(in) :: fl_prop
        type(reference_scalar_param), intent(in) :: ref_param_T
        type(reference_scalar_param), intent(in) :: ref_param_C
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(base_field_address), intent(in) :: ipol_base
        type(base_force_address), intent(in) :: ipol_div_frc
        type(phys_data), intent(inout) :: rj_fld
      subroutine cal_r_buoyancy_on_sphere(kr, coef, is_fld, is_fr,    &
     &          nidx_rj, radius_1d_rj_r, nnod_rj, ntot_phys_rj, d_rj)
Parameters
kr Radial grid ID
Function/Subroutine Documentation
cal_r_buoyancy_on_sphere()
subroutine self_buoyancy_on_sphere::cal_r_buoyancy_on_sphere (integer(kind= kint), intent(in) kr, real(kind = kreal), intent(in) coef, integer(kind= kint), intent(in) is_fld, integer(kind= kint), intent(in) is_fr, integer(kind = kint), dimension(2), intent(in) nidx_rj, real(kind = kreal), dimension(nidx_rj(1)), intent(in) radius_1d_rj_r, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 142 of file self_buoyancy_on_sphere.f90.
Referenced by r_buoyancy_on_sphere().
cal_r_double_buo_on_sphere()
subroutine, private self_buoyancy_on_sphere::cal_r_double_buo_on_sphere (integer(kind= kint), intent(in) kr, real(kind = kreal), intent(in) coef_buo, real(kind = kreal), intent(in) coef_comp_buo, integer(kind= kint), intent(in) is_t, integer(kind= kint), intent(in) is_c, integer(kind= kint), intent(in) is_fr, integer(kind = kint), dimension(2), intent(in) nidx_rj, real(kind = kreal), dimension(nidx_rj(1)), intent(in) radius_1d_rj_r, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj) private
Definition at line 115 of file self_buoyancy_on_sphere.f90.
Referenced by r_buoyancy_on_sphere().
r_buoyancy_on_sphere()
subroutine self_buoyancy_on_sphere::r_buoyancy_on_sphere (logical, intent(in) iflag_4_gravity, logical, intent(in) iflag_4_composit_buo, integer(kind= kint), intent(in) kr, type(sph_rj_grid), intent(in) sph_rj, type(base_field_address), intent(in) ipol_base, type(base_force_address), intent(in) ipol_div_frc, real(kind = kreal), intent(in) coef_buo, real(kind = kreal), intent(in) coef_comp_buo, type(reference_scalar_param), intent(in) ref_param_T, type(reference_scalar_param), intent(in) ref_param_C, type(phys_data), intent(inout) rj_fld)
Definition at line 45 of file self_buoyancy_on_sphere.f90.
References cal_r_buoyancy_on_sphere(), cal_r_double_buo_on_sphere(), t_reference_scalar_param::id_sphere_ref_temp, t_reference_scalar_param::id_takepiro_temp, and m_machine_parameter::iflag_debug.
Referenced by const_radial_forces_on_bc::s_const_radial_forces_on_bc().