CALYPSO: udt_type_data_io Module Reference
udt_type_data_io Module Reference
UCD format data IO.
Functions/Subroutines
subroutine write_udt_type_fields (id_ucd, ucd)
subroutine write_ucd_type_mesh (id_ucd, ucd)
subroutine read_udt_field (id_ucd, ucd)
subroutine read_alloc_udt_field (id_ucd, ucd)
subroutine read_ucd_mesh_data (id_ucd, ucd)
subroutine read_alloc_ucd_mesh_data (id_ucd, ucd)
Detailed Description
UCD format data IO.
      subroutine write_udt_type_fields(id_ucd, ucd)
      subroutine write_ucd_type_mesh(id_ucd, ucd)
        type(ucd_data), intent(in) :: ucd
      subroutine read_udt_field(id_ucd, ucd)
      subroutine read_alloc_udt_field(id_ucd, ucd)
      subroutine read_ucd_mesh_data(id_ucd, ucd)
      subroutine read_alloc_ucd_mesh_data(id_ucd, ucd)
        type(ucd_data), intent(inout) :: ucd
Function/Subroutine Documentation
read_alloc_ucd_mesh_data()
subroutine udt_type_data_io::read_alloc_ucd_mesh_data (integer(kind = kint), intent(in) id_ucd, type(ucd_data), intent(inout) ucd)
Definition at line 165 of file udt_type_data_IO.f90.
References t_ucd_data::allocate_ucd_ele(), t_ucd_data::allocate_ucd_node(), ucd_data_to_buffer::nnod_ele_by_ucd_eletype(), udt_data_io::read_ucd_mesh_header(), and udt_data_io::read_ucd_node_data().
Referenced by udt_file_io::read_alloc_grd_file(), and udt_file_io::read_alloc_ucd_file().
read_alloc_udt_field()
subroutine udt_type_data_io::read_alloc_udt_field (integer(kind = kint), intent(in) id_ucd, type(ucd_data), intent(inout) ucd)
Definition at line 123 of file udt_type_data_IO.f90.
References t_ucd_data::allocate_ucd_phys_data(), t_ucd_data::allocate_ucd_phys_name(), t_ucd_data::cal_istack_ucd_component(), udt_data_io::read_udt_field_name(), and udt_data_io::read_udt_field_num().
Referenced by udt_file_io::read_alloc_ucd_file(), udt_file_io::read_alloc_udt_file(), and udt_file_io::read_alloc_udt_params().
read_ucd_mesh_data()
subroutine udt_type_data_io::read_ucd_mesh_data (integer(kind = kint), intent(in) id_ucd, type(ucd_data), intent(inout) ucd)
Definition at line 143 of file udt_type_data_IO.f90.
References udt_data_io::read_ucd_ele_connect(), udt_data_io::read_ucd_mesh_header(), and udt_data_io::read_ucd_node_data().
Referenced by udt_file_io::read_grd_file(), and udt_file_io::read_ucd_file().
read_udt_field()
subroutine udt_type_data_io::read_udt_field (integer(kind = kint), intent(in) id_ucd, type(ucd_data), intent(inout) ucd)
Definition at line 106 of file udt_type_data_IO.f90.
References t_ucd_data::cal_istack_ucd_component(), udt_data_io::read_ucd_field_data(), and udt_data_io::read_udt_field_name().
Referenced by udt_file_io::read_ucd_file(), and udt_file_io::read_udt_file().
write_ucd_type_mesh()
subroutine udt_type_data_io::write_ucd_type_mesh (integer(kind = kint), intent(in) id_ucd, type(ucd_data), intent(in) ucd)
Definition at line 69 of file udt_type_data_IO.f90.
References m_constants::ithree, udt_data_io::write_ucd_field_data(), udt_data_io::write_ucd_mesh_connect(), and udt_data_io::write_udt_mesh_header().
Referenced by udt_file_io::write_grd_file(), and udt_file_io::write_ucd_file().
write_udt_type_fields()
subroutine udt_type_data_io::write_udt_type_fields (integer(kind = kint), intent(in) id_ucd, type(ucd_data), intent(in) ucd)
Definition at line 41 of file udt_type_data_IO.f90.
References udt_data_io::write_ucd_field_data(), and udt_data_io::write_udt_field_header().
Referenced by udt_file_io::write_ucd_file(), and udt_file_io::write_udt_file().