CALYPSO: schmidt_fix_m Module Reference
schmidt_fix_m Module Reference
module for Legendre polynomials with Schmidt normalization
Functions/Subroutines
subroutine schmidt_legendres_m (ltr, m, theta, p, dp, pmn1, pmp1, df)
subroutine schmidt_legendre_m (ltr, m, theta, p, df)
subroutine diff_schmidt_legendre_m (ltr, m, pmn1, pmp1, dp)
subroutine full_normalize_from_smdt_m (ltr, m, p, dp)
Detailed Description
module for Legendre polynomials with Schmidt normalization
 subroutine schmidt_legendres_m(ltr, m, theta, p, dp,            &
& pmp1, pmp1, df)
subroutine schmidt_legendre_m(ltr, m, theta, p, df)
*************************************************************
* Legendre and adjoint Legendle Polynomial for order m
*
* p(l) : Schmidt Polynomial
* Normalization...
* P_{l}^{0} = P_{l,0}
* P_{l}^{m} = sqrt(2(l-m)! / (l+m)!) * P_{l,m}
* theta : input colatitude (0 =< theta <= pi)
*
* df(l) : work area
*
*************************************************************
subroutine diff_schmidt_legendre_m(ltr, m, pmn1, pmp1, dp)
*************************************************************
* lead difference of Schmidt Polynomial
*
* pmp1 = p(m+1,l) : Schmidt Polynomial (input)
* pmn1 = p(m-1,l) : Schmidt Polynomial (input)
* Normalization...
* P_{l}^{0} = P_{l,0}
* P_{l}^{m} = sqrt(2(l-m)! / (l+m)!) * P_{l,m}
* dp(l) : diffrential of Schmidt Polynomial dp/dtheta
*
*************************************************************
subroutine full_normalize_from_smdt_m(ltr, m, p, dp)
Parameters
ltr Truncation level for the polynomial
theta Input degree (\(0 \le \theta \le \pi \))
p(l) Schmidt Polynomial for order m \(P_{l}^{m} \)
dp(l) diffrence of Schmidt Polynomial for order m \(d P_{l}^{m} / d\theta \)
df(l) work area
Function/Subroutine Documentation
diff_schmidt_legendre_m()
subroutine schmidt_fix_m::diff_schmidt_legendre_m (integer(kind = kint), intent(in) ltr, integer(kind = kint), intent(in) m, real(kind = kreal), dimension(0:ltr), intent(in) pmn1, real(kind = kreal), dimension(0:ltr), intent(in) pmp1, real(kind = kreal), dimension(0:ltr), intent(inout) dp)
Definition at line 145 of file schmidt_fix_m.f90.
References m_constants::half, and m_constants::zero.
Referenced by schmidt_legendres_m().
full_normalize_from_smdt_m()
subroutine schmidt_fix_m::full_normalize_from_smdt_m (integer(kind = kint), intent(in) ltr, integer(kind = kint), intent(in) m, real(kind = kreal), dimension(0:ltr), intent(inout) p, real(kind = kreal), dimension(0:ltr), intent(inout) dp)
Definition at line 179 of file schmidt_fix_m.f90.
schmidt_legendre_m()
subroutine schmidt_fix_m::schmidt_legendre_m (integer(kind = kint), intent(in) ltr, integer(kind = kint), intent(in) m, real(kind = kreal), intent(in) theta, real(kind = kreal), dimension(0:ltr), intent(inout) p, real(kind = kreal), dimension(0:ltr+2), intent(inout) df)
Definition at line 89 of file schmidt_fix_m.f90.
References m_constants::one, m_constants::two, and m_constants::zero.
Referenced by schmidt_legendres_m().
schmidt_legendres_m()
subroutine schmidt_fix_m::schmidt_legendres_m (integer(kind = kint), intent(in) ltr, integer(kind = kint), intent(in) m, real(kind = kreal), intent(in) theta, real(kind = kreal), dimension(0:ltr), intent(inout) p, real(kind = kreal), dimension(0:ltr), intent(inout) dp, real(kind = kreal), dimension(0:ltr), intent(inout) pmn1, real(kind = kreal), dimension(0:ltr), intent(inout) pmp1, real(kind = kreal), dimension(0:ltr+2), intent(inout) df)
Definition at line 62 of file schmidt_fix_m.f90.
References diff_schmidt_legendre_m(), and schmidt_legendre_m().
Referenced by t_set_legendre_4_sph_trans::set_each_sym_leg_omp_mat_j1(), t_set_legendre_4_sph_trans::set_each_sym_leg_omp_mat_jt(), t_set_legendre_4_sph_trans::set_each_sym_leg_omp_mat_tj(), schmidt_poly_on_rtm_grid::set_lagender_4_rlm(), and schmidt_poly_on_rtm_grid::set_lagender_pole_rlm().