CALYPSO: gz_vtk_data_io Module Reference
gz_vtk_data_io Module Reference
Output routine for gzipped VTK data segments.
Functions/Subroutines
subroutine write_gz_vtk_fields_head (nnod, zbuf)
subroutine, private write_gz_vtk_each_field_head (ncomp_field, field_name, zbuf)
subroutine write_gz_vtk_each_field (ntot_nod, ncomp_field, nnod, d_nod, zbuf)
subroutine write_gz_vtk_node_head (nnod, zbuf)
subroutine write_gz_vtk_connect_head (nele, nnod_ele, zbuf)
subroutine write_gz_vtk_cell_type (nele, nnod_ele, zbuf)
subroutine write_gz_vtk_connect_data (ntot_ele, nnod_ele, nele, ie, zbuf)
subroutine write_gz_vtk_data (nnod, num_field, ntot_comp, ncomp_field, field_name, d_nod, zbuf)
subroutine read_gz_vtk_fields_head (nnod, zbuf)
subroutine read_gz_vtk_each_field_head (iflag_end, ncomp_field, field_name, zbuf)
subroutine read_gz_vtk_each_field (ntot_nod, ncomp_field, nnod, d_nod, zbuf)
subroutine read_gz_vtk_node_head (nnod, zbuf)
subroutine read_gz_vtk_connect_head (nele, nnod_ele, zbuf)
subroutine read_gz_vtk_cell_type (nele, zbuf)
subroutine read_gz_vtk_connect_data (ntot_ele, nnod_ele, nele, ie, zbuf)
Detailed Description
Output routine for gzipped VTK data segments.
      subroutine write_gz_vtk_fields_head(nnod, zbuf)
      subroutine write_gz_vtk_each_field                              &
     &         (ntot_nod, ncomp_field, nnod, d_nod, zbuf)
      subroutine write_gz_vtk_data(nnod, num_field, ntot_comp,        &
     &          ncomp_field, field_name, d_nod, zbuf)
       type(buffer_4_gzip), intent(inout) :: zbuf
      subroutine write_gz_vtk_node_head(nnod, zbuf)
      subroutine write_gz_vtk_connect_head(nele, nnod_ele, zbuf)
      subroutine write_gz_vtk_cell_type(nele, nnod_ele, zbuf)
      subroutine write_gz_vtk_connect_data                            &
     &         (ntot_ele, nnod_ele, nele, ie, zbuf)
      subroutine read_gz_vtk_fields_head(nnod, zbuf)
      subroutine read_gz_vtk_each_field_head                          &
     &         (iflag_end, ncomp_field, field_name, zbuf)
      subroutine read_gz_vtk_each_field                               &
     &         (ntot_nod, ncomp_field, nnod, d_nod, zbuf)
      subroutine read_gz_vtk_node_head(nnod, zbuf)
      subroutine read_gz_vtk_connect_head(nele, nnod_ele, zbuf)
      subroutine read_gz_vtk_cell_type(nele, zbuf)
      subroutine read_gz_vtk_connect_data                             &
     &         (ntot_ele, nnod_ele, nele, ie, zbuf)
        type(buffer_4_gzip), intent(inout) :: zbuf
Parameters
iflag_end Integer flag for the end of file
nnod Number of nodes
nele Number of elements
nnod_ele Number of nodes for each element
xx(nnod,3) position of nodes
nnod_ele number of nodes for each element
ie(nele,nnod_ele) element connectivity
ntot_comp total number of components
ncomp_field(num_field) number of components
field_name(num_field) list of field names
d_nod(nnod,ntot_comp) field data
Function/Subroutine Documentation
read_gz_vtk_cell_type()
subroutine gz_vtk_data_io::read_gz_vtk_cell_type (integer(kind = kint_gl), intent(in) nele, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 400 of file gz_vtk_data_IO.f90.
References gzip_file_access::get_one_line_text_from_gz().
Referenced by gz_udt_to_vtk_data_io::read_alloc_gz_ucd_grd_from_vtk(), and gz_udt_to_vtk_data_io::read_gz_ucd_grd_from_vtk().
read_gz_vtk_connect_data()
subroutine gz_vtk_data_io::read_gz_vtk_connect_data (integer(kind = kint_gl), intent(in) ntot_ele, integer(kind = kint), intent(in) nnod_ele, integer(kind = kint_gl), intent(in) nele, integer(kind = kint_gl), dimension(ntot_ele,nnod_ele), intent(inout) ie, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 420 of file gz_vtk_data_IO.f90.
References gzip_file_access::get_one_line_text_from_gz().
Referenced by gz_udt_to_vtk_data_io::read_alloc_gz_ucd_grd_from_vtk(), and gz_udt_to_vtk_data_io::read_gz_ucd_grd_from_vtk().
read_gz_vtk_connect_head()
subroutine gz_vtk_data_io::read_gz_vtk_connect_head (integer(kind = kint_gl), intent(inout) nele, integer(kind = kint), intent(inout) nnod_ele, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 380 of file gz_vtk_data_IO.f90.
References gzip_file_access::get_one_line_text_from_gz().
Referenced by gz_udt_to_vtk_data_io::read_alloc_gz_ucd_grd_from_vtk(), and gz_udt_to_vtk_data_io::read_gz_ucd_grd_from_vtk().
read_gz_vtk_each_field()
subroutine gz_vtk_data_io::read_gz_vtk_each_field (integer(kind=kint_gl), intent(in) ntot_nod, integer(kind=kint), intent(in) ncomp_field, integer(kind=kint_gl), intent(in) nnod, real(kind = kreal), dimension(ntot_nod,ncomp_field), intent(inout) d_nod, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 320 of file gz_vtk_data_IO.f90.
References gzip_file_access::get_one_line_text_from_gz(), and m_phys_constants::n_sym_tensor.
Referenced by gz_udt_to_vtk_data_io::read_alloc_gz_ucd_grd_from_vtk(), gz_udt_to_vtk_data_io::read_alloc_gz_udt_fld_from_vtk(), gz_udt_to_vtk_data_io::read_gz_ucd_grd_from_vtk(), and gz_udt_to_vtk_data_io::read_gz_udt_field_from_vtk().
read_gz_vtk_each_field_head()
subroutine gz_vtk_data_io::read_gz_vtk_each_field_head (integer(kind=kint), intent(inout) iflag_end, integer(kind=kint), intent(inout) ncomp_field, character(len=kchara), intent(inout) field_name, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 284 of file gz_vtk_data_IO.f90.
References gzip_file_access::get_one_line_text_from_gz(), m_constants::ione, m_constants::izero, m_phys_constants::n_scalar, m_phys_constants::n_sym_tensor, and m_phys_constants::n_vector.
Referenced by gz_udt_to_vtk_data_io::read_alloc_gz_udt_fld_from_vtk(), and gz_udt_to_vtk_data_io::read_gz_udt_field_from_vtk().
read_gz_vtk_fields_head()
subroutine gz_vtk_data_io::read_gz_vtk_fields_head (integer(kind=kint_gl), intent(inout) nnod, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 268 of file gz_vtk_data_IO.f90.
References skip_gz_comment::skip_gz_comment_chara_lint().
Referenced by gz_udt_to_vtk_data_io::read_alloc_gz_udt_fld_from_vtk(), and gz_udt_to_vtk_data_io::read_gz_udt_field_from_vtk().
read_gz_vtk_node_head()
subroutine gz_vtk_data_io::read_gz_vtk_node_head (integer(kind = kint_gl), intent(inout) nnod, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 357 of file gz_vtk_data_IO.f90.
References gzip_file_access::get_one_line_text_from_gz(), and skip_gz_comment::skip_gz_comment_chara().
Referenced by gz_udt_to_vtk_data_io::read_alloc_gz_ucd_grd_from_vtk(), and gz_udt_to_vtk_data_io::read_gz_ucd_grd_from_vtk().
write_gz_vtk_cell_type()
subroutine gz_vtk_data_io::write_gz_vtk_cell_type (integer(kind = kint_gl), intent(in) nele, integer(kind = kint), intent(in) nnod_ele, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 184 of file gz_vtk_data_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf(), vtk_data_to_buffer::vtk_cell_type(), vtk_data_to_buffer::vtk_cell_type_head(), and vtk_data_to_buffer::vtk_each_cell_type().
Referenced by gz_udt_to_vtk_data_io::write_gz_ucd_mesh_to_vtk().
write_gz_vtk_connect_data()
subroutine gz_vtk_data_io::write_gz_vtk_connect_data (integer(kind = kint_gl), intent(in) ntot_ele, integer(kind = kint), intent(in) nnod_ele, integer(kind = kint_gl), intent(in) nele, integer(kind = kint_gl), dimension(ntot_ele,nnod_ele), intent(in) ie, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 212 of file gz_vtk_data_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf(), and vtk_data_to_buffer::vtk_each_connect().
Referenced by gz_udt_to_vtk_data_io::write_gz_ucd_mesh_to_vtk().
write_gz_vtk_connect_head()
subroutine gz_vtk_data_io::write_gz_vtk_connect_head (integer(kind = kint_gl), intent(in) nele, integer(kind = kint), intent(in) nnod_ele, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 167 of file gz_vtk_data_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf(), and vtk_data_to_buffer::vtk_connect_head().
Referenced by gz_udt_to_vtk_data_io::write_gz_ucd_mesh_to_vtk().
write_gz_vtk_data()
subroutine gz_vtk_data_io::write_gz_vtk_data (integer(kind=kint_gl), intent(in) nnod, integer(kind=kint), intent(in) num_field, integer(kind=kint), intent(in) ntot_comp, integer(kind=kint), dimension(num_field), intent(in) ncomp_field, character(len=kchara), dimension(num_field), intent(in) field_name, real(kind = kreal), dimension(nnod,ntot_comp), intent(in) d_nod, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 238 of file gz_vtk_data_IO.f90.
References write_gz_vtk_each_field(), and write_gz_vtk_each_field_head().
Referenced by gz_udt_to_vtk_data_io::write_gz_ucd_field_to_vtk().
write_gz_vtk_each_field()
subroutine gz_vtk_data_io::write_gz_vtk_each_field (integer(kind=kint_gl), intent(in) ntot_nod, integer(kind=kint), intent(in) ncomp_field, integer(kind=kint_gl), intent(in) nnod, real(kind = kreal), dimension(ntot_nod,ncomp_field), intent(in) d_nod, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 107 of file gz_vtk_data_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf(), m_phys_constants::n_sym_tensor, m_phys_constants::n_vector, vtk_data_to_buffer::vtk_each_scalar(), and vtk_data_to_buffer::vtk_each_vector().
Referenced by gz_udt_to_vtk_data_io::write_gz_ucd_mesh_to_vtk(), and write_gz_vtk_data().
write_gz_vtk_each_field_head()
subroutine, private gz_vtk_data_io::write_gz_vtk_each_field_head (integer(kind=kint), intent(in) ncomp_field, character(len=kchara), intent(in) field_name, type(buffer_4_gzip), intent(inout) zbuf) private
Definition at line 82 of file gz_vtk_data_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf(), m_phys_constants::n_scalar, m_phys_constants::n_sym_tensor, m_phys_constants::n_vector, vtk_data_to_buffer::vtk_scalar_head(), vtk_data_to_buffer::vtk_tensor_head(), and vtk_data_to_buffer::vtk_vector_head().
Referenced by write_gz_vtk_data().
write_gz_vtk_fields_head()
subroutine gz_vtk_data_io::write_gz_vtk_fields_head (integer(kind=kint_gl), intent(in) nnod, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 67 of file gz_vtk_data_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf(), and vtk_data_to_buffer::vtk_fields_head().
Referenced by gz_udt_to_vtk_data_io::write_gz_ucd_field_to_vtk().
write_gz_vtk_node_head()
subroutine gz_vtk_data_io::write_gz_vtk_node_head (integer(kind = kint_gl), intent(in) nnod, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 150 of file gz_vtk_data_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf(), and vtk_data_to_buffer::vtk_node_head().
Referenced by gz_udt_to_vtk_data_io::write_gz_ucd_mesh_to_vtk().