CALYPSO: gz_spherical_model_io_b Module Reference
gz_spherical_model_io_b Module Reference
Data IO routines for spectrum data.
Functions/Subroutines
subroutine gz_read_rank_4_sph_b (zbuf, sph_IO)
subroutine gz_read_gl_resolution_sph_b (zbuf, sph_IO)
subroutine gz_read_gl_nodes_sph_b (zbuf, sph_IO)
subroutine gz_write_rank_4_sph_b (sph_IO, zbuf)
subroutine gz_write_gl_resolution_sph_b (sph_IO, zbuf)
subroutine gz_write_gl_nodes_sph_b (sph_IO, zbuf)
Detailed Description
Data IO routines for spectrum data.
      subroutine gz_read_rank_4_sph_b(zbuf, sph_IO)
      subroutine gz_read_gl_resolution_sph_b(zbuf, sph_IO)
      subroutine gz_read_gl_nodes_sph_b(zbuf, sph_IO)
        type(buffer_4_gzip), intent(inout) :: zbuf
        type(sph_IO_data), intent(inout) :: sph_IO
      subroutine gz_write_rank_4_sph_b(sph_IO, zbuf)
      subroutine gz_write_gl_resolution_sph_b(sph_IO, zbuf)
      subroutine gz_write_gl_nodes_sph_b(sph_IO, zbuf)
        type(sph_IO_data), intent(in) :: sph_IO
        type(buffer_4_gzip), intent(inout) :: zbuf
Function/Subroutine Documentation
gz_read_gl_nodes_sph_b()
subroutine gz_spherical_model_io_b::gz_read_gl_nodes_sph_b (type(buffer_4_gzip), intent(inout) zbuf, type(sph_io_data), intent(inout) sph_IO)
Definition at line 72 of file gz_spherical_model_IO_b.f90.
References t_node_id_spherical_io::alloc_nod_id_sph_io(), transfer_to_long_integers::cast_long(), gz_binary_io::gz_read_mul_int8_b(), gz_binary_io::gz_read_mul_integer_b(), and gz_binary_io::gz_read_one_integer_b().
Referenced by gz_sph_modes_data_io_b::gz_read_geom_rtm_data_b(), gz_sph_modes_data_io_b::gz_read_geom_rtp_data_b(), gz_sph_modes_data_io_b::gz_read_modes_rlm_data_b(), and gz_sph_modes_data_io_b::gz_read_spectr_modes_rj_data_b().
gz_read_gl_resolution_sph_b()
subroutine gz_spherical_model_io_b::gz_read_gl_resolution_sph_b (type(buffer_4_gzip), intent(inout) zbuf, type(sph_io_data), intent(inout) sph_IO)
Definition at line 55 of file gz_spherical_model_IO_b.f90.
References transfer_to_long_integers::cast_long(), gz_binary_io::gz_read_mul_integer_b(), and gz_binary_io::gz_read_one_integer_b().
Referenced by gz_sph_modes_data_io_b::gz_read_geom_rtm_data_b(), gz_sph_modes_data_io_b::gz_read_geom_rtp_data_b(), gz_sph_modes_data_io_b::gz_read_modes_rlm_data_b(), and gz_sph_modes_data_io_b::gz_read_spectr_modes_rj_data_b().
gz_read_rank_4_sph_b()
subroutine gz_spherical_model_io_b::gz_read_rank_4_sph_b (type(buffer_4_gzip), intent(inout) zbuf, type(sph_io_data), intent(inout) sph_IO)
Definition at line 41 of file gz_spherical_model_IO_b.f90.
References transfer_to_long_integers::cast_long(), and gz_binary_io::gz_read_mul_integer_b().
Referenced by gz_sph_modes_data_io_b::gz_read_geom_rtm_data_b(), gz_sph_modes_data_io_b::gz_read_geom_rtp_data_b(), gz_sph_modes_data_io_b::gz_read_modes_rlm_data_b(), and gz_sph_modes_data_io_b::gz_read_spectr_modes_rj_data_b().
gz_write_gl_nodes_sph_b()
subroutine gz_spherical_model_io_b::gz_write_gl_nodes_sph_b (type(sph_io_data), intent(in) sph_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 128 of file gz_spherical_model_IO_b.f90.
References transfer_to_long_integers::cast_long(), gz_binary_io::gz_write_mul_int8_b(), gz_binary_io::gz_write_mul_integer_b(), and gz_binary_io::gz_write_one_integer_b().
Referenced by gz_sph_modes_data_io_b::gz_write_geom_rtm_data_b(), gz_sph_modes_data_io_b::gz_write_geom_rtp_data_b(), gz_sph_modes_data_io_b::gz_write_modes_rlm_data_b(), and gz_sph_modes_data_io_b::gz_write_spectr_modes_rj_data_b().
gz_write_gl_resolution_sph_b()
subroutine gz_spherical_model_io_b::gz_write_gl_resolution_sph_b (type(sph_io_data), intent(in) sph_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 112 of file gz_spherical_model_IO_b.f90.
References transfer_to_long_integers::cast_long(), gz_binary_io::gz_write_mul_integer_b(), and gz_binary_io::gz_write_one_integer_b().
Referenced by gz_sph_modes_data_io_b::gz_write_geom_rtm_data_b(), gz_sph_modes_data_io_b::gz_write_geom_rtp_data_b(), gz_sph_modes_data_io_b::gz_write_modes_rlm_data_b(), and gz_sph_modes_data_io_b::gz_write_spectr_modes_rj_data_b().
gz_write_rank_4_sph_b()
subroutine gz_spherical_model_io_b::gz_write_rank_4_sph_b (type(sph_io_data), intent(in) sph_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 98 of file gz_spherical_model_IO_b.f90.
References transfer_to_long_integers::cast_long(), and gz_binary_io::gz_write_mul_integer_b().
Referenced by gz_sph_modes_data_io_b::gz_write_geom_rtm_data_b(), gz_sph_modes_data_io_b::gz_write_geom_rtp_data_b(), gz_sph_modes_data_io_b::gz_write_modes_rlm_data_b(), and gz_sph_modes_data_io_b::gz_write_spectr_modes_rj_data_b().