CALYPSO: t_control_data_section_only Module Reference
t_control_data_section_only Module Reference
Data Types
type control_data_section_only
Structure of control data for sectioning only.
Functions/Subroutines
subroutine read_control_data_section_only (sec_viz_ctl)
subroutine, private read_section_control_data (id_control, hd_block, sec_viz_ctl, c_buf)
subroutine, private bcast_section_control_data (sec_viz_ctl)
subroutine reset_section_control_data (sec_viz_ctl)
Variables
integer(kind=kint), parameter, private viz_ctl_file_code = 11
character(len=kchara), parameter, private fname_viz_ctl = "control_viz"
character(len=kchara), parameter, private hd_viz_only_file = 'visualizer'
character(len=kchara), parameter, private hd_platform = 'data_files_def'
character(len=kchara), parameter, private hd_time_step = 'time_step_ctl'
character(len=kchara), parameter, private hd_viz_ctl = 'visual_control'
Function/Subroutine Documentation
bcast_section_control_data()
subroutine, private t_control_data_section_only::bcast_section_control_data (type(control_data_section_only), intent(inout) sec_viz_ctl) private
Definition at line 146 of file t_control_data_section_only.f90.
References bcast_4_platform_ctl::bcast_ctl_data_4_platform(), bcast_4_time_step_ctl::bcast_ctl_data_4_time_step(), t_control_data_surfacings::bcast_surfacing_controls(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by read_control_data_section_only().
read_control_data_section_only()
subroutine t_control_data_section_only::read_control_data_section_only (type(control_data_section_only), intent(inout) sec_viz_ctl)
Definition at line 84 of file t_control_data_section_only.f90.
References bcast_section_control_data(), fname_viz_ctl, hd_viz_only_file, t_read_control_elements::load_one_line_from_control(), calypso_mpi::my_rank, read_section_control_data(), t_control_data_surfacings::section_step_ctls_to_time_ctl(), and viz_ctl_file_code.
Referenced by analyzer_psf::init_analyzer_psf(), and analyzer_vtk_convert::init_analyzer_vtk_convert().
read_section_control_data()
subroutine, private t_control_data_section_only::read_section_control_data (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(control_data_section_only), intent(inout) sec_viz_ctl, type(buffer_for_control), intent(inout) c_buf) private
Definition at line 114 of file t_control_data_section_only.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_platform, hd_time_step, hd_viz_ctl, t_read_control_elements::load_one_line_from_control(), t_ctl_data_4_platforms::read_control_platforms(), t_ctl_data_4_time_steps::read_control_time_step_data(), and t_control_data_surfacings::read_surfacing_controls().
Referenced by read_control_data_section_only().
reset_section_control_data()
subroutine t_control_data_section_only::reset_section_control_data (type(control_data_section_only), intent(inout) sec_viz_ctl)
Definition at line 165 of file t_control_data_section_only.f90.
References t_control_data_surfacings::bcast_surfacing_controls(), and t_ctl_data_4_platforms::reset_control_platforms().
Variable Documentation
fname_viz_ctl
character(len = kchara), parameter, private t_control_data_section_only::fname_viz_ctl = "control_viz" private
Definition at line 44 of file t_control_data_section_only.f90.
Referenced by read_control_data_section_only().
hd_platform
character(len=kchara), parameter, private t_control_data_section_only::hd_platform = 'data_files_def' private
Definition at line 65 of file t_control_data_section_only.f90.
Referenced by read_section_control_data().
hd_time_step
character(len=kchara), parameter, private t_control_data_section_only::hd_time_step = 'time_step_ctl' private
Definition at line 67 of file t_control_data_section_only.f90.
Referenced by read_section_control_data().
hd_viz_ctl
character(len=kchara), parameter, private t_control_data_section_only::hd_viz_ctl = 'visual_control' private
Definition at line 69 of file t_control_data_section_only.f90.
Referenced by read_section_control_data().
hd_viz_only_file
character(len=kchara), parameter, private t_control_data_section_only::hd_viz_only_file = 'visualizer' private
Definition at line 62 of file t_control_data_section_only.f90.
Referenced by read_control_data_section_only().
viz_ctl_file_code
integer(kind = kint), parameter, private t_control_data_section_only::viz_ctl_file_code = 11 private
Definition at line 43 of file t_control_data_section_only.f90.
Referenced by read_control_data_section_only().