CALYPSO: /home/takumi kera/calypso/src/programs/TESTS/Gauss_point_test/test_gauss_points.f90 File Reference
test_gauss_points.f90 File Reference
Functions/Subroutines
program test_gauss_points
Function/Subroutine Documentation
test_gauss_points()
program test_gauss_points
Definition at line 4 of file test_gauss_points.f90.
References t_gauss_points::const_gauss_colatitude(), t_gauss_points::dealloc_gauss_colatitude(), and gauss_points_io::write_gauss_points().