CALYPSO: const_r_mat_4_vector_sph Module Reference
const_r_mat_4_vector_sph Module Reference
Construct matrix for time evolution of vector fields.
Functions/Subroutines
subroutine const_radial_mat_vort_2step (dt, sph_rj, r_2nd, fl_prop, sph_bc_U, fdm2_center, fdm2_free_ICB, fdm2_free_CMB, g_sph_rj, band_vs_poisson, band_vp_evo, band_vt_evo, band_wt_evo)
subroutine const_radial_mat_4_magne_sph (dt, sph_rj, r_2nd, cd_prop, sph_bc_B, fdm2_center, g_sph_rj, band_bp_evo, band_bt_evo)
Detailed Description
Construct matrix for time evolution of vector fields.
      subroutine const_radial_mat_vort_2step                          &
     &        (dt, sph_rj, r_2nd, fl_prop, sph_bc_U,                  &
     &         fdm2_center, fdm2_free_ICB, fdm2_free_CMB, g_sph_rj,   &
     &         band_vs_poisson, band_vp_evo, band_vt_evo, band_wt_evo)
      subroutine const_radial_mat_4_magne_sph                         &
     &         (dt, sph_rj, r_2nd, cd_prop, sph_bc_B, fdm2_center,    &
     &          g_sph_rj, band_bp_evo, band_bt_evo)
        type(sph_rj_grid), intent(in) :: sph_rj
        type(fdm_matrices), intent(in) :: r_2nd
        type(fluid_property), intent(in) :: fl_prop
        type(conductive_property), intent(in) :: cd_prop
        type(sph_boundary_type), intent(in) :: sph_bc_U
        type(sph_boundary_type), intent(in) :: sph_bc_B
        type(fdm2_center_mat), intent(in) :: fdm2_center
        type(fdm2_free_slip), intent(in) :: fdm2_free_ICB
        type(fdm2_free_slip), intent(in) :: fdm2_free_CMB
        type(band_matrices_type), intent(inout) :: band_vp_evo
        type(band_matrices_type), intent(inout) :: band_vt_evo
        type(band_matrices_type), intent(inout) :: band_wt_evo
        type(band_matrices_type), intent(inout) :: band_vs_poisson
        type(band_matrices_type), intent(inout) :: band_bp_evo
        type(band_matrices_type), intent(inout) :: band_bt_evo
Function/Subroutine Documentation
const_radial_mat_4_magne_sph()
subroutine const_r_mat_4_vector_sph::const_radial_mat_4_magne_sph (real(kind = kreal), intent(in) dt, type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(conductive_property), intent(in) cd_prop, type(sph_boundary_type), intent(in) sph_bc_B, type(fdm2_center_mat), intent(in) fdm2_center, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, type(band_matrices_type), intent(inout) band_bp_evo, type(band_matrices_type), intent(inout) band_bt_evo)
Definition at line 253 of file const_r_mat_4_vector_sph.f90.
References set_sph_scalar_mat_bc::add_fix_flux_cmb_poisson_mat(), set_sph_scalar_mat_bc::add_fix_flux_icb_poisson_mat(), center_sph_matrices::add_vector_poisson_mat_center(), set_radial_mat_sph::add_vector_poisson_mat_sph(), t_sph_matrices::alloc_band_mat_sph(), t_sph_matrices::check_radial_band_mat(), m_machine_parameter::i_debug, t_physical_property::id_crank_nicolson, t_boundary_params_sph_mhd::iflag_evolve_field, m_machine_parameter::iflag_full_msg, t_boundary_params_sph_mhd::iflag_radial_magne, t_boundary_params_sph_mhd::iflag_sph_fill_center, m_constants::ithree, t_sph_matrices::ludcmp_3band_mul_t(), calypso_mpi::my_rank, m_machine_parameter::np_smp, m_constants::one, set_sph_scalar_mat_bc::set_fix_fld_cmb_poisson_mat(), set_sph_scalar_mat_bc::set_fix_fld_icb_poisson_mat(), set_sph_magne_mat_bc::set_ins_magne_cmb_rmat_sph(), set_sph_magne_mat_bc::set_ins_magne_icb_rmat_sph(), set_radial_mat_sph::set_unit_mat_4_poisson(), set_radial_mat_sph::set_unit_mat_4_time_evo(), t_sph_matrices::set_unit_on_diag(), and m_constants::zero.
Referenced by const_radial_mat_4_sph::const_radial_matrices_sph().
const_radial_mat_vort_2step()
subroutine const_r_mat_4_vector_sph::const_radial_mat_vort_2step (real(kind = kreal), intent(in) dt, type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(fluid_property), intent(in) fl_prop, type(sph_boundary_type), intent(in) sph_bc_U, type(fdm2_center_mat), intent(in) fdm2_center, type(fdm2_free_slip), intent(in) fdm2_free_ICB, type(fdm2_free_slip), intent(in) fdm2_free_CMB, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, type(band_matrices_type), intent(inout) band_vs_poisson, type(band_matrices_type), intent(inout) band_vp_evo, type(band_matrices_type), intent(inout) band_vt_evo, type(band_matrices_type), intent(inout) band_wt_evo)
Definition at line 59 of file const_r_mat_4_vector_sph.f90.
References set_sph_scalar_mat_bc::add_fix_flux_cmb_poisson_mat(), set_sph_scalar_mat_bc::add_fix_flux_icb_poisson_mat(), center_sph_matrices::add_vector_poisson_mat_center(), set_radial_mat_sph::add_vector_poisson_mat_sph(), t_sph_matrices::alloc_band_mat_sph(), mat_product_3band_mul::cal_mat_product_3band_mul(), t_sph_matrices::check_radial_band_mat(), m_machine_parameter::i_debug, m_constants::ifive, t_boundary_params_sph_mhd::iflag_free_slip, m_machine_parameter::iflag_full_msg, t_boundary_params_sph_mhd::iflag_rotatable_ic, t_boundary_params_sph_mhd::iflag_sph_fill_center, m_constants::ithree, t_sph_matrices::ludcmp_3band_mul_t(), t_sph_matrices::ludcmp_5band_mul_t(), calypso_mpi::my_rank, m_machine_parameter::np_smp, m_constants::one, set_sph_scalar_mat_bc::set_fix_fld_cmb_poisson_mat(), set_sph_scalar_mat_bc::set_fix_fld_icb_poisson_mat(), cal_inner_core_rotation::set_icore_viscous_matrix(), set_radial_mat_sph::set_unit_mat_4_poisson(), set_radial_mat_sph::set_unit_mat_4_time_evo(), t_sph_matrices::set_unit_on_diag(), and m_constants::zero.
Referenced by const_radial_mat_4_sph::const_radial_matrices_sph().