CALYPSO: cal_sph_exp_nod_none_bc Module Reference
cal_sph_exp_nod_none_bc Module Reference
Evaluate derivatives with no boundary conditions.
Functions/Subroutines
subroutine cal_sph_nod_nobc_in_grad2 (jmax, g_sph_rj, kr_in, r_ICB, fdm2_fix_fld_ICB, is_fld, is_grad, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_nod_nobc_in_rot2 (jmax, g_sph_rj, kr_in, r_ICB, fdm2_fix_fld_ICB, is_fld, is_rot, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_nod_nobc_in_div2 (jmax, g_sph_rj, kr_in, r_ICB, fdm2_fix_fld_ICB, is_fld, is_div, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_nod_nobc_in_diffuse2 (jmax, g_sph_rj, kr_in, r_ICB, fdm2_fix_fld_ICB, is_fld, is_diffuse, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_nod_nobc_out_grad2 (jmax, g_sph_rj, kr_out, r_CMB, fdm2_fix_fld_CMB, is_fld, is_grad, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_nod_nobc_out_rot2 (jmax, g_sph_rj, kr_out, r_CMB, fdm2_fix_fld_CMB, is_fld, is_rot, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_nod_nobc_out_div2 (jmax, g_sph_rj, kr_out, r_CMB, fdm2_fix_fld_CMB, is_fld, is_div, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_nod_nobc_out_diffuse2 (jmax, g_sph_rj, kr_out, r_CMB, fdm2_fix_fld_CMB, is_fld, is_diffuse, n_point, ntot_phys_rj, d_rj)
subroutine delete_bc_rj_vector (jmax, kr_bc, is_fld, n_point, ntot_phys_rj, d_rj)
Detailed Description
Evaluate derivatives with no boundary conditions.
      subroutine cal_sph_nod_nobc_in_grad2(jmax, g_sph_rj,            &
     &          kr_in, r_ICB, fdm2_fix_fld_ICB, is_fld, is_grad,      &
     &          n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_nod_nobc_in_rot2(jmax, g_sph_rj,             &
     &          kr_in, r_ICB, fdm2_fix_fld_ICB, is_fld, is_rot,       &
     &          n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_nod_nobc_in_div2(jmax, g_sph_rj,             &
     &          kr_in, r_ICB, fdm2_fix_fld_ICB, is_fld, is_div,       &
     &          n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_nod_nobc_in_diffuse2(jmax, g_sph_rj,         &
     &          kr_in, r_ICB, fdm2_fix_fld_ICB, is_fld, is_diffuse,   &
     &          n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_nod_nobc_out_grad2(jmax, g_sph_rj,           &
     &          kr_out, r_CMB, fdm2_fix_fld_CMB, is_fld, is_grad,     &
     &          n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_nod_nobc_out_rot2(jmax, g_sph_rj,            &
     &          kr_out, r_CMB, fdm2_fix_fld_CMB, is_fld, is_rot,      &
     &          n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_nod_nobc_out_div2(jmax, g_sph_rj,            &
     &          kr_out, r_CMB, fdm2_fix_fld_CMB, is_fld, is_div,      &
     &          n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_nod_nobc_out_diffuse2(jmax, g_sph_rj,        &
     &          kr_out, r_CMB, fdm2_fix_fld_CMB, is_fld, is_diffuse,  &
     &          n_point, ntot_phys_rj, d_rj)
      subroutine delete_bc_rj_vector                                  &
     &         (jmax, kr_bc, is_fld, n_point, ntot_phys_rj, d_rj)
Parameters
fdm2_fix_fld_ICB(0:2,3) Finite difference matrix for ICB with no boundary condition
fdm2_fix_fld_CMB(0:2,3) Finite difference matrix for CMB with no boundary condition
Parameters
n_point Number of points for spectrum data
jmax Number of local spherical harmonics mode
kr_in Radial ID for inner boundary
kr_out Radial ID for outer boundary
r_ICB(0:2) Radius at ICB
r_CMB(0:2) Radius at CMB
kr_bc radial ID to be deleted
Parameters
is_fld Field address of input field
is_grad Field address for gradient of field
is_div Field address for divergence of field
is_rot Field address for curl of field
is_diffuse Field address for diffusion of field
Parameters
ntot_phys_rj Total number of components
d_rj Spectrum data
Function/Subroutine Documentation
cal_sph_nod_nobc_in_diffuse2()
subroutine cal_sph_exp_nod_none_bc::cal_sph_nod_nobc_in_diffuse2 (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(0:2), intent(in) r_ICB, real(kind = kreal), dimension(0:2,3), intent(in) fdm2_fix_fld_ICB, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_diffuse, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 197 of file cal_sph_exp_nod_none_bc.f90.
cal_sph_nod_nobc_in_div2()
subroutine cal_sph_exp_nod_none_bc::cal_sph_nod_nobc_in_div2 (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(0:2), intent(in) r_ICB, real(kind = kreal), dimension(0:2,3), intent(in) fdm2_fix_fld_ICB, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_div, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 161 of file cal_sph_exp_nod_none_bc.f90.
References m_constants::half.
Referenced by const_sph_divergence::const_sph_div_force().
cal_sph_nod_nobc_in_grad2()
subroutine cal_sph_exp_nod_none_bc::cal_sph_nod_nobc_in_grad2 (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(0:2), intent(in) r_ICB, real(kind = kreal), dimension(0:2,3), intent(in) fdm2_fix_fld_ICB, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_grad, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 75 of file cal_sph_exp_nod_none_bc.f90.
References m_constants::zero.
Referenced by const_sph_radial_grad::const_sph_gradient_no_bc().
cal_sph_nod_nobc_in_rot2()
subroutine cal_sph_exp_nod_none_bc::cal_sph_nod_nobc_in_rot2 (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(0:2), intent(in) r_ICB, real(kind = kreal), dimension(0:2,3), intent(in) fdm2_fix_fld_ICB, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_rot, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 120 of file cal_sph_exp_nod_none_bc.f90.
Referenced by const_sph_rotation::const_sph_rotation_no_bc().
cal_sph_nod_nobc_out_diffuse2()
subroutine cal_sph_exp_nod_none_bc::cal_sph_nod_nobc_out_diffuse2 (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_out, real(kind = kreal), dimension(0:2), intent(in) r_CMB, real(kind = kreal), dimension(0:2,3), intent(in) fdm2_fix_fld_CMB, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_diffuse, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 361 of file cal_sph_exp_nod_none_bc.f90.
cal_sph_nod_nobc_out_div2()
subroutine cal_sph_exp_nod_none_bc::cal_sph_nod_nobc_out_div2 (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_out, real(kind = kreal), dimension(0:2), intent(in) r_CMB, real(kind = kreal), dimension(0:2,3), intent(in) fdm2_fix_fld_CMB, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_div, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 325 of file cal_sph_exp_nod_none_bc.f90.
References m_constants::half.
Referenced by const_sph_divergence::const_sph_div_force().
cal_sph_nod_nobc_out_grad2()
subroutine cal_sph_exp_nod_none_bc::cal_sph_nod_nobc_out_grad2 (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_out, real(kind = kreal), dimension(0:2), intent(in) r_CMB, real(kind = kreal), dimension(0:2,3), intent(in) fdm2_fix_fld_CMB, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_grad, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 239 of file cal_sph_exp_nod_none_bc.f90.
References m_constants::zero.
Referenced by const_sph_radial_grad::const_sph_gradient_no_bc().
cal_sph_nod_nobc_out_rot2()
subroutine cal_sph_exp_nod_none_bc::cal_sph_nod_nobc_out_rot2 (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_out, real(kind = kreal), dimension(0:2), intent(in) r_CMB, real(kind = kreal), dimension(0:2,3), intent(in) fdm2_fix_fld_CMB, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_rot, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 284 of file cal_sph_exp_nod_none_bc.f90.
Referenced by const_sph_rotation::const_sph_rotation_no_bc().
delete_bc_rj_vector()
subroutine cal_sph_exp_nod_none_bc::delete_bc_rj_vector (integer(kind = kint), intent(in) jmax, integer(kind = kint), intent(in) kr_bc, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 402 of file cal_sph_exp_nod_none_bc.f90.
Referenced by const_sph_radial_grad::const_pressure_gradient().