CALYPSO: t_ctl_data_4_divide_sphere Module Reference
t_ctl_data_4_divide_sphere Module Reference
Data Types
type sphere_domain_control
control data structure for spherical shell parallelization
Functions/Subroutines
subroutine dealloc_ndomain_rtp_ctl (sdctl)
subroutine read_control_shell_domain (id_control, hd_block, sdctl, c_buf)
subroutine write_control_shell_domain (id_file, hd_block, sdctl, level)
Variables
character(len=kchara), parameter, private hd_inner_decomp = 'inner_decomp_direction'
character(len=kchara), parameter, private hd_rj_inner_loop = 'rj_inner_loop_direction'
character(len=kchara), parameter, private hd_rlm_inner_loop = 'rlm_inner_loop_direction'
character(len=kchara), parameter, private hd_rtm_inner_loop = 'rtm_inner_loop_direction'
character(len=kchara), parameter, private hd_rtp_inner_loop = 'rtp_inner_loop_direction'
character(len=kchara), parameter hd_indices_ordering_set = 'ordering_set_ctl'
character(len=kchara), parameter hd_rlm_order_dist = 'rlm_order_distribution'
character(len=kchara), parameter, private hd_num_radial_domain = 'num_radial_domain_ctl'
character(len=kchara), parameter, private hd_num_horiz_domain = 'num_horizontal_domain_ctl'
character(len=kchara), parameter, private hd_ndomain_rtp = 'num_domain_sph_grid'
character(len=kchara), parameter, private hd_ndomain_rtm = 'num_domain_legendre'
character(len=kchara), parameter, private hd_ndomain_rj = 'num_domain_spectr'
Function/Subroutine Documentation
dealloc_ndomain_rtp_ctl()
subroutine t_ctl_data_4_divide_sphere::dealloc_ndomain_rtp_ctl (type(sphere_domain_control), intent(inout) sdctl)
Definition at line 153 of file t_ctl_data_4_divide_sphere.f90.
References t_control_array_charaint::dealloc_control_array_c_i().
Referenced by t_ctl_data_gen_sph_shell::dealloc_parallel_shell_ctl().
read_control_shell_domain()
subroutine t_ctl_data_4_divide_sphere::read_control_shell_domain (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(sphere_domain_control), intent(inout) sdctl, type(buffer_for_control), intent(inout) c_buf)
Definition at line 167 of file t_ctl_data_4_divide_sphere.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_indices_ordering_set, hd_inner_decomp, hd_ndomain_rj, hd_ndomain_rtm, hd_ndomain_rtp, hd_num_horiz_domain, hd_num_radial_domain, hd_rj_inner_loop, hd_rlm_inner_loop, hd_rlm_order_dist, hd_rtm_inner_loop, hd_rtp_inner_loop, t_read_control_elements::load_one_line_from_control(), t_control_array_character::read_chara_ctl_type(), t_control_array_charaint::read_control_array_c_i(), and t_control_array_integer::read_integer_ctl_type().
Referenced by t_ctl_data_gen_sph_shell::read_parallel_shell_ctl().
write_control_shell_domain()
subroutine t_ctl_data_4_divide_sphere::write_control_shell_domain (integer(kind = kint), intent(in) id_file, character(len=kchara), intent(in) hd_block, type(sphere_domain_control), intent(in) sdctl, integer(kind = kint), intent(inout) level)
Definition at line 222 of file t_ctl_data_4_divide_sphere.f90.
References hd_inner_decomp, hd_ndomain_rj, hd_ndomain_rtm, hd_ndomain_rtp, hd_num_horiz_domain, hd_num_radial_domain, write_control_elements::write_begin_flag_for_ctl(), t_control_array_character::write_chara_ctl_type(), t_control_array_charaint::write_control_array_c_i(), write_control_elements::write_end_flag_for_ctl(), and t_control_array_integer::write_integer_ctl_type().
Variable Documentation
hd_indices_ordering_set
character(len=kchara), parameter t_ctl_data_4_divide_sphere::hd_indices_ordering_set = 'ordering_set_ctl'
Definition at line 123 of file t_ctl_data_4_divide_sphere.f90.
Referenced by read_control_shell_domain().
hd_inner_decomp
character(len=kchara), parameter, private t_ctl_data_4_divide_sphere::hd_inner_decomp = 'inner_decomp_direction' private
Definition at line 112 of file t_ctl_data_4_divide_sphere.f90.
Referenced by read_control_shell_domain(), and write_control_shell_domain().
hd_ndomain_rj
character(len=kchara), parameter, private t_ctl_data_4_divide_sphere::hd_ndomain_rj = 'num_domain_spectr' private
Definition at line 138 of file t_ctl_data_4_divide_sphere.f90.
Referenced by read_control_shell_domain(), and write_control_shell_domain().
hd_ndomain_rtm
character(len=kchara), parameter, private t_ctl_data_4_divide_sphere::hd_ndomain_rtm = 'num_domain_legendre' private
Definition at line 136 of file t_ctl_data_4_divide_sphere.f90.
Referenced by read_control_shell_domain(), and write_control_shell_domain().
hd_ndomain_rtp
character(len=kchara), parameter, private t_ctl_data_4_divide_sphere::hd_ndomain_rtp = 'num_domain_sph_grid' private
Definition at line 134 of file t_ctl_data_4_divide_sphere.f90.
Referenced by read_control_shell_domain(), and write_control_shell_domain().
hd_num_horiz_domain
character(len=kchara), parameter, private t_ctl_data_4_divide_sphere::hd_num_horiz_domain = 'num_horizontal_domain_ctl' private
Definition at line 131 of file t_ctl_data_4_divide_sphere.f90.
Referenced by read_control_shell_domain(), and write_control_shell_domain().
hd_num_radial_domain
character(len=kchara), parameter, private t_ctl_data_4_divide_sphere::hd_num_radial_domain = 'num_radial_domain_ctl' private
Definition at line 129 of file t_ctl_data_4_divide_sphere.f90.
Referenced by read_control_shell_domain(), and write_control_shell_domain().
hd_rj_inner_loop
character(len=kchara), parameter, private t_ctl_data_4_divide_sphere::hd_rj_inner_loop = 'rj_inner_loop_direction' private
Definition at line 115 of file t_ctl_data_4_divide_sphere.f90.
Referenced by read_control_shell_domain().
hd_rlm_inner_loop
character(len=kchara), parameter, private t_ctl_data_4_divide_sphere::hd_rlm_inner_loop = 'rlm_inner_loop_direction' private
Definition at line 117 of file t_ctl_data_4_divide_sphere.f90.
Referenced by read_control_shell_domain().
hd_rlm_order_dist
character(len=kchara), parameter t_ctl_data_4_divide_sphere::hd_rlm_order_dist = 'rlm_order_distribution'
Definition at line 126 of file t_ctl_data_4_divide_sphere.f90.
Referenced by read_control_shell_domain().
hd_rtm_inner_loop
character(len=kchara), parameter, private t_ctl_data_4_divide_sphere::hd_rtm_inner_loop = 'rtm_inner_loop_direction' private
Definition at line 119 of file t_ctl_data_4_divide_sphere.f90.
Referenced by read_control_shell_domain().
hd_rtp_inner_loop
character(len=kchara), parameter, private t_ctl_data_4_divide_sphere::hd_rtp_inner_loop = 'rtp_inner_loop_direction' private
Definition at line 121 of file t_ctl_data_4_divide_sphere.f90.
Referenced by read_control_shell_domain().