CALYPSO: set_evoluved_boundaries Module Reference
set_evoluved_boundaries Module Reference
Evaluate velocity with non-slip boundary at CMB.
Functions/Subroutines
subroutine set_evo_scalar_boundaries (time, sph_rj, sph_bc, bcs_S)
subroutine set_evo_vector_boundaries (time, sph_rj, sph_bc, bcs_V)
subroutine, private cal_sph_nod_evo_scalar_bc (time, sph_rj, BC_Sevo, BC_Sspec)
subroutine, private cal_sph_nod_evo_vector_bc (time, sph_rj, BC_Vevo, BC_Vspec)
Detailed Description
Evaluate velocity with non-slip boundary at CMB.
      subroutine set_evo_scalar_boundaries                            &
     &         (time, sph_rj, sph_bc, bcs_S)
      subroutine set_evo_vector_boundaries                            &
     &         (time, sph_rj, sph_bc, bcs_V)
        type(sph_rj_grid), intent(in) :: sph_rj
        type(sph_boundary_type), intent(in) :: sph_bc
        type(sph_scalar_boundary_data), intent(inout) :: bcs_S
        type(sph_vector_boundary_data), intent(inout) :: bcs_V
Function/Subroutine Documentation
cal_sph_nod_evo_scalar_bc()
subroutine, private set_evoluved_boundaries::cal_sph_nod_evo_scalar_bc (real(kind = kreal), intent(in) time, type(sph_rj_grid), intent(in) sph_rj, type(sph_scalar_bc_evo), intent(in) BC_Sevo, type(sph_scalar_bc_coef), intent(inout) BC_Sspec) private
Definition at line 95 of file set_evoluved_boundaries.f90.
References m_constants::one.
Referenced by set_evo_scalar_boundaries().
cal_sph_nod_evo_vector_bc()
subroutine, private set_evoluved_boundaries::cal_sph_nod_evo_vector_bc (real(kind = kreal), intent(in) time, type(sph_rj_grid), intent(in) sph_rj, type(sph_vector_bc_evo), intent(in) BC_Vevo, type(sph_vector_bc_coef), intent(inout) BC_Vspec) private
Definition at line 123 of file set_evoluved_boundaries.f90.
References m_constants::one.
Referenced by set_evo_vector_boundaries().
set_evo_scalar_boundaries()
subroutine set_evoluved_boundaries::set_evo_scalar_boundaries (real(kind = kreal), intent(in) time, type(sph_rj_grid), intent(in) sph_rj, type(sph_boundary_type), intent(in) sph_bc, type(sph_scalar_boundary_data), intent(inout) bcs_S)
Definition at line 39 of file set_evoluved_boundaries.f90.
References cal_sph_nod_evo_scalar_bc(), t_boundary_params_sph_mhd::iflag_evolve_field, and t_boundary_params_sph_mhd::iflag_evolve_flux.
Referenced by t_boundary_data_sph_mhd::set_cv_evolved_boundaries().
set_evo_vector_boundaries()
subroutine set_evoluved_boundaries::set_evo_vector_boundaries (real(kind = kreal), intent(in) time, type(sph_rj_grid), intent(in) sph_rj, type(sph_boundary_type), intent(in) sph_bc, type(sph_vector_boundary_data), intent(inout) bcs_V)
Definition at line 64 of file set_evoluved_boundaries.f90.
References cal_sph_nod_evo_vector_bc(), t_boundary_params_sph_mhd::iflag_evolve_field, and t_boundary_params_sph_mhd::iflag_evolve_flux.
Referenced by t_boundary_data_sph_mhd::set_cv_evolved_boundaries(), and t_boundary_data_sph_mhd::set_mhd_evolved_boundaries().