CALYPSO: write_udt_file_io_b Module Reference
write_udt_file_io_b Module Reference
Output merged VTK file usgin MPI-IO.
Functions/Subroutines
subroutine write_ucd_file_mpi_b (file_name, t_IO, ucd)
subroutine write_ucd_phys_mpi_b (file_name, t_IO, ucd)
subroutine write_ucd_grid_mpi_b (file_name, ucd)
Variables
type(calypso_mpi_io_params), save, private io_param
Detailed Description
Output merged VTK file usgin MPI-IO.
      subroutine write_ucd_file_mpi_b(file_name, t_IO, ucd)
      subroutine write_ucd_phys_mpi_b(file_name, t_IO, ucd)
      subroutine write_ucd_grid_mpi_b(file_name, ucd)
        type(time_data), intent(in) :: t_IO
        type(ucd_data), intent(in) :: ucd
Function/Subroutine Documentation
write_ucd_file_mpi_b()
subroutine write_udt_file_io_b::write_ucd_file_mpi_b (character(len=kchara), intent(in) file_name, type(time_data), intent(in) t_IO, type(ucd_data), intent(in) ucd)
Definition at line 42 of file write_udt_file_IO_b.f90.
References mpi_ascii_data_io::close_mpi_file(), io_param, calypso_mpi::my_rank, mpi_binary_head_io::open_write_mpi_file_b(), field_block_mpi_io_b::write_field_time_mpi_b(), ucd_file_mpi_io::write_ucd_data_mpi_b(), and ucd_file_mpi_io::write_ucd_mesh_data_mpi_b().
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_file().
write_ucd_grid_mpi_b()
subroutine write_udt_file_io_b::write_ucd_grid_mpi_b (character(len=kchara), intent(in) file_name, type(ucd_data), intent(in) ucd)
Definition at line 103 of file write_udt_file_IO_b.f90.
References mpi_ascii_data_io::close_mpi_file(), calypso_mpi::my_rank, mpi_binary_head_io::open_write_mpi_file_b(), and ucd_file_mpi_io::write_ucd_mesh_data_mpi_b().
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_mesh().
write_ucd_phys_mpi_b()
subroutine write_udt_file_io_b::write_ucd_phys_mpi_b (character(len=kchara), intent(in) file_name, type(time_data), intent(in) t_IO, type(ucd_data), intent(in) ucd)
Definition at line 74 of file write_udt_file_IO_b.f90.
References mpi_ascii_data_io::close_mpi_file(), io_param, calypso_mpi::my_rank, mpi_binary_head_io::open_write_mpi_file_b(), field_block_mpi_io_b::write_field_time_mpi_b(), and ucd_file_mpi_io::write_ucd_data_mpi_b().
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_file().
Variable Documentation
io_param
type(calypso_mpi_io_params), save, private write_udt_file_io_b::io_param private
Definition at line 34 of file write_udt_file_IO_b.f90.
Referenced by write_ucd_file_mpi_b(), and write_ucd_phys_mpi_b().