CALYPSO: t_assembled_field_io Module Reference
t_assembled_field_io Module Reference
gzipped data IO for
Functions/Subroutines
subroutine sel_write_sph_assemble_field (num_pe, istep_fld, nloop, fst_IO_param, t_IO, fld_IO)
Detailed Description
gzipped data IO for
      subroutine sel_write_SPH_assemble_field(num_pe, istep_fld,      &
     &          nloop, fst_IO_param, t_IO, fld_IO)
        type(field_IO_params), intent(in) :: fst_IO_param
        type(time_data), intent(inout) :: t_IO
        type(field_IO), intent(inout) :: fld_IO(nloop)
   Data format for the merged ascii field data
     1.   Number of process
     2.   Time step
     3.   Time, Delta t
     4.   Stacks of numbe of data points
     5.   Number of fields
     6.   List of number of components
     7.   Each field data  (Itarate 7.1 - 7.3)
      7.1   Field name
      7.2   List of data size (Byte)
      7.3   Field data
   Data format for the merged binary field data
     1.   Number of process
     2.   Time step
     3.   Time, Delta t
     4.   Stacks of numbe of data points
     5.   Number of fields
     6.   List of number of components
     7.   Field names
     8.   List of data size (Byte)
     9.   All Field data
Function/Subroutine Documentation
sel_write_sph_assemble_field()
subroutine t_assembled_field_io::sel_write_sph_assemble_field (integer, intent(in) num_pe, integer(kind = kint), intent(in) istep_fld, integer(kind = kint), intent(in) nloop, type(field_io_params), intent(in) fst_IO_param, type(time_data), intent(in) t_IO, type(field_io), dimension(nloop), intent(in) fld_IO)
Definition at line 59 of file t_assembled_field_IO.F90.
References gz_assembled_field_mpi_io::gz_write_step_asbl_fld_mpi(), gz_assembled_field_mpi_io::gz_write_step_asbl_fld_mpi_b(), calypso_mpi::my_rank, calypso_mpi::nprocs, field_io_select::sel_write_step_sph_field_file(), and set_field_file_names::set_sph_fld_file_name().