CALYPSO: t_ctl_data_gen_sph_shell Module Reference
t_ctl_data_gen_sph_shell Module Reference
control data for resolutions of spherical shell
Data Types
type parallel_sph_shell_control
structure of parallel spherical shell data
Functions/Subroutines
subroutine, private read_ctl_file_gen_shell_grids (id_control, psph_ctl)
subroutine read_parallel_shell_in_mhd_ctl (id_control, hd_block, psph_ctl, c_buf)
subroutine, private read_parallel_shell_ctl (id_control, hd_block, psph_ctl, c_buf)
subroutine bcast_parallel_shell_ctl (psph_ctl)
subroutine dealloc_parallel_shell_ctl (psph_ctl)
Variables
character(len=kchara), parameter, private hd_sph_shell = 'spherical_shell_ctl'
character(len=kchara), parameter, private hd_fem_mesh = 'FEM_mesh_ctl'
character(len=kchara), parameter, private hd_sph_def = 'shell_define_ctl'
character(len=kchara), parameter, private hd_domains_sph = 'num_domain_ctl'
character(len=kchara), parameter, private hd_shell_def = 'num_grid_sph'
Detailed Description
control data for resolutions of spherical shell
      subroutine read_parallel_shell_in_MHD_ctl                       &
     &         (id_control, hd_block, psph_ctl, c_buf)
      subroutine bcast_parallel_shell_ctl(psph_ctl)
        type(platform_data_control), intent(inout) :: plt
        type(parallel_sph_shell_control), intent(inout) :: psph_ctl
 =======================================================
    example of control section
    begin FEM_mesh_ctl
      memory_conservation_ctl        'YES'
      FEM_mesh_output_switch         'NO'
      FEM_surface_output_switch      'NO'
      FEM_viewer_mesh_output_switch  'NO'
      sleeve_level_ctl            2
      element_overlap_ctl        ON
    end FEM_mesh_ctl
    begin num_domain_ctl
      num_radial_domain_ctl         2
      num_horizontal_domain_ctl     2
      ...
    end num_domain_ctl
    begin num_grid_sph
      sph_coef_type_ctl       no_pole
      sph_grid_type_ctl       no_pole
      truncation_level_ctl     4
      longitude_symmetry_ctl   2
      ngrid_meridonal_ctl     12
      ngrid_zonal_ctl         24
      ...
    end num_grid_sph
 =======================================================
Function/Subroutine Documentation
bcast_parallel_shell_ctl()
subroutine t_ctl_data_gen_sph_shell::bcast_parallel_shell_ctl (type(parallel_sph_shell_control), intent(inout) psph_ctl)
Definition at line 199 of file t_ctl_data_gen_sph_shell.f90.
References bcast_4_sphere_ctl::bcast_ctl_4_shell_define(), bcast_4_sphere_ctl::bcast_ctl_ndomain_4_shell(), bcast_4_platform_ctl::bcast_fem_mesh_control(), calypso_mpi_char::calypso_mpi_bcast_character(), calypso_mpi_int::calypso_mpi_bcast_one_int(), transfer_to_long_integers::cast_long(), and m_precision::kchara.
Referenced by bcast_4_assemble_sph_ctl::bcast_merge_control_data(), t_ctl_data_mhd::bcast_sph_mhd_ctl_data(), and t_ctl_data_const_sph_mesh::bcast_sph_shell_define_ctl().
dealloc_parallel_shell_ctl()
subroutine t_ctl_data_gen_sph_shell::dealloc_parallel_shell_ctl (type(parallel_sph_shell_control), intent(inout) psph_ctl)
Definition at line 226 of file t_ctl_data_gen_sph_shell.f90.
References t_ctl_data_4_sphere_model::dealloc_control_shell_define(), t_ctl_data_4_divide_sphere::dealloc_ndomain_rtp_ctl(), and t_ctl_data_4_fem_mesh::reset_fem_mesh_control().
Referenced by t_ctl_data_mhd::dealloc_sph_mhd_ctl_data(), t_control_data_4_merge::reset_merge_control_data(), and t_ctl_params_gen_sph_shell::set_control_4_gen_shell_grids().
read_ctl_file_gen_shell_grids()
subroutine, private t_ctl_data_gen_sph_shell::read_ctl_file_gen_shell_grids (integer(kind = kint), intent(in) id_control, type(parallel_sph_shell_control), intent(inout) psph_ctl) private
Definition at line 109 of file t_ctl_data_gen_sph_shell.f90.
References t_read_control_elements::check_begin_flag(), hd_sph_shell, t_read_control_elements::load_one_line_from_control(), and read_parallel_shell_ctl().
Referenced by read_parallel_shell_in_mhd_ctl().
read_parallel_shell_ctl()
subroutine, private t_ctl_data_gen_sph_shell::read_parallel_shell_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(parallel_sph_shell_control), intent(inout) psph_ctl, type(buffer_for_control), intent(inout) c_buf) private
Definition at line 167 of file t_ctl_data_gen_sph_shell.f90.
References t_read_control_elements::check_end_flag(), hd_domains_sph, hd_fem_mesh, hd_shell_def, hd_sph_def, t_read_control_elements::load_one_line_from_control(), t_ctl_data_4_sphere_model::read_control_shell_define(), t_ctl_data_4_divide_sphere::read_control_shell_domain(), and t_ctl_data_4_fem_mesh::read_fem_mesh_control().
Referenced by read_ctl_file_gen_shell_grids(), and read_parallel_shell_in_mhd_ctl().
read_parallel_shell_in_mhd_ctl()
subroutine t_ctl_data_gen_sph_shell::read_parallel_shell_in_mhd_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(parallel_sph_shell_control), intent(inout) psph_ctl, type(buffer_for_control), intent(inout) c_buf)
Definition at line 138 of file t_ctl_data_gen_sph_shell.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_file_flag(), read_ctl_file_gen_shell_grids(), read_parallel_shell_ctl(), and t_read_control_elements::third_word().
Referenced by t_control_data_4_merge::read_merge_control_data(), t_ctl_data_mhd::read_sph_mhd_ctl_noviz(), t_ctl_data_mhd::read_sph_mhd_ctl_w_psf(), and t_ctl_data_const_sph_mesh::read_sph_shell_define_ctl().
Variable Documentation
hd_domains_sph
character(len=kchara), parameter, private t_ctl_data_gen_sph_shell::hd_domains_sph = 'num_domain_ctl' private
Definition at line 93 of file t_ctl_data_gen_sph_shell.f90.
Referenced by read_parallel_shell_ctl().
hd_fem_mesh
character(len=kchara), parameter, private t_ctl_data_gen_sph_shell::hd_fem_mesh = 'FEM_mesh_ctl' private
Definition at line 89 of file t_ctl_data_gen_sph_shell.f90.
Referenced by read_parallel_shell_ctl().
hd_shell_def
character(len=kchara), parameter, private t_ctl_data_gen_sph_shell::hd_shell_def = 'num_grid_sph' private
Definition at line 97 of file t_ctl_data_gen_sph_shell.f90.
Referenced by read_parallel_shell_ctl().
hd_sph_def
character(len=kchara), parameter, private t_ctl_data_gen_sph_shell::hd_sph_def = 'shell_define_ctl' private
Definition at line 91 of file t_ctl_data_gen_sph_shell.f90.
Referenced by read_parallel_shell_ctl().
hd_sph_shell
character(len=kchara), parameter, private t_ctl_data_gen_sph_shell::hd_sph_shell = 'spherical_shell_ctl' private
Definition at line 84 of file t_ctl_data_gen_sph_shell.f90.
Referenced by read_ctl_file_gen_shell_grids().