CALYPSO: m_more_component_flags Module Reference
m_more_component_flags Module Reference
Functions/Subroutines
subroutine set_primary_componnet_flag (input_flag)
subroutine init_more_componnet_flags ()
subroutine dealloc_more_componnet_flags ()
Variables
character(len=kchara), dimension(3), parameter mag_flags = (/'amplitude ', 'magnitude ', 'norm ' /)
character(len=kchara), dimension(2), parameter r_flags = (/'r ', 'radial '/)
character(len=kchara), dimension(2), parameter t_flags = (/'theta ', 'elevation '/)
character(len=kchara), dimension(2), parameter p_flags = (/'phi ', 'azimuth '/)
character(len=kchara), dimension(2), parameter s_flags = (/'s ', 'cylinder_r '/)
character(len=kchara), dimension(3), parameter mag_sym_tsr_flags = (/'magnitude ', 'norm_sym_tensor ', 'mag_sym_tensor '/)
character(len=kchara), dimension(3), parameter mag_asym_tsr_flags = (/'magnitude ', 'norm_asym_tensor ', 'mag_asym_tensor '/)
type(multi_flag_labels), save magnitude_flags
flags for amplitude of vector 'amplitude ', 'magnitude ', 'norm '
type(multi_flag_labels), save radial_flags
flags for radial component 'r ', 'radial '
type(multi_flag_labels), save theta_flags
flags for theta component 'theta ', 'elevation '
type(multi_flag_labels), save phi_flags
flags for phi component 'phi ', 'azimuth '
type(multi_flag_labels), save cyrindrical_r_flags
flags for cytrindrical radius component 's ', 'cylinder_r '
type(multi_flag_labels), save sym_tensor_magnitude_flags
flags for amplitude of symmetric tensor 'magnitude ', 'norm_sym_tensor ', 'mag_sym_tensor '
type(multi_flag_labels), save asym_tensor_magnitude_flags
flags for amplitude of asymmetric tensor 'magnitude ', 'norm_asym_tensor ', 'mag_asym_tensor '
Function/Subroutine Documentation
dealloc_more_componnet_flags()
subroutine m_more_component_flags::dealloc_more_componnet_flags
Definition at line 135 of file m_more_component_flags.f90.
References asym_tensor_magnitude_flags, cyrindrical_r_flags, t_multi_flag_labels::dealloc_multi_flags(), magnitude_flags, phi_flags, radial_flags, sym_tensor_magnitude_flags, and theta_flags.
Referenced by set_components_flags::s_set_components_flags(), and set_primary_componnet_flag().
init_more_componnet_flags()
subroutine m_more_component_flags::init_more_componnet_flags
Definition at line 112 of file m_more_component_flags.f90.
References asym_tensor_magnitude_flags, cyrindrical_r_flags, t_multi_flag_labels::init_multi_flags_by_labels(), mag_asym_tsr_flags, mag_flags, mag_sym_tsr_flags, magnitude_flags, p_flags, phi_flags, r_flags, radial_flags, s_flags, sym_tensor_magnitude_flags, t_flags, and theta_flags.
Referenced by set_components_flags::s_set_components_flags(), and set_primary_componnet_flag().
set_primary_componnet_flag()
subroutine m_more_component_flags::set_primary_componnet_flag (character(len=kchara), intent(inout) input_flag)
Definition at line 75 of file m_more_component_flags.f90.
References asym_tensor_magnitude_flags, t_multi_flag_labels::check_mul_flags(), cyrindrical_r_flags, dealloc_more_componnet_flags(), init_more_componnet_flags(), m_component_flags::magnitude, magnitude_flags, phi_flags, radial_flags, sym_tensor_magnitude_flags, theta_flags, m_component_flags::v_phi, m_component_flags::v_r, m_component_flags::v_s, and m_component_flags::v_theta.
Variable Documentation
asym_tensor_magnitude_flags
type(multi_flag_labels), save m_more_component_flags::asym_tensor_magnitude_flags
flags for amplitude of asymmetric tensor 'magnitude ', 'norm_asym_tensor ', 'mag_asym_tensor '
Definition at line 67 of file m_more_component_flags.f90.
Referenced by dealloc_more_componnet_flags(), init_more_componnet_flags(), set_components_flags::s_set_components_flags(), and set_primary_componnet_flag().
cyrindrical_r_flags
type(multi_flag_labels), save m_more_component_flags::cyrindrical_r_flags
flags for cytrindrical radius component 's ', 'cylinder_r '
Definition at line 60 of file m_more_component_flags.f90.
Referenced by dealloc_more_componnet_flags(), init_more_componnet_flags(), set_components_flags::s_set_components_flags(), and set_primary_componnet_flag().
mag_asym_tsr_flags
character(len=kchara), dimension(3), parameter m_more_component_flags::mag_asym_tsr_flags = (/'magnitude ', 'norm_asym_tensor ', 'mag_asym_tensor '/)
Definition at line 41 of file m_more_component_flags.f90.
Referenced by init_more_componnet_flags().
mag_flags
character(len=kchara), dimension(3), parameter m_more_component_flags::mag_flags = (/'amplitude ', 'magnitude ', 'norm ' /)
Definition at line 26 of file m_more_component_flags.f90.
Referenced by init_more_componnet_flags().
mag_sym_tsr_flags
character(len=kchara), dimension(3), parameter m_more_component_flags::mag_sym_tsr_flags = (/'magnitude ', 'norm_sym_tensor ', 'mag_sym_tensor '/)
Definition at line 38 of file m_more_component_flags.f90.
Referenced by init_more_componnet_flags().
magnitude_flags
type(multi_flag_labels), save m_more_component_flags::magnitude_flags
flags for amplitude of vector 'amplitude ', 'magnitude ', 'norm '
Definition at line 47 of file m_more_component_flags.f90.
Referenced by dealloc_more_componnet_flags(), init_more_componnet_flags(), set_components_flags::s_set_components_flags(), and set_primary_componnet_flag().
p_flags
character(len=kchara), dimension(2), parameter m_more_component_flags::p_flags = (/'phi ', 'azimuth '/)
Definition at line 33 of file m_more_component_flags.f90.
Referenced by init_more_componnet_flags().
phi_flags
type(multi_flag_labels), save m_more_component_flags::phi_flags
flags for phi component 'phi ', 'azimuth '
Definition at line 57 of file m_more_component_flags.f90.
Referenced by dealloc_more_componnet_flags(), init_more_componnet_flags(), set_components_flags::s_set_components_flags(), and set_primary_componnet_flag().
r_flags
character(len=kchara), dimension(2), parameter m_more_component_flags::r_flags = (/'r ', 'radial '/)
Definition at line 29 of file m_more_component_flags.f90.
Referenced by init_more_componnet_flags().
radial_flags
type(multi_flag_labels), save m_more_component_flags::radial_flags
flags for radial component 'r ', 'radial '
Definition at line 51 of file m_more_component_flags.f90.
Referenced by dealloc_more_componnet_flags(), init_more_componnet_flags(), set_components_flags::s_set_components_flags(), and set_primary_componnet_flag().
s_flags
character(len=kchara), dimension(2), parameter m_more_component_flags::s_flags = (/'s ', 'cylinder_r '/)
Definition at line 35 of file m_more_component_flags.f90.
Referenced by init_more_componnet_flags().
sym_tensor_magnitude_flags
type(multi_flag_labels), save m_more_component_flags::sym_tensor_magnitude_flags
flags for amplitude of symmetric tensor 'magnitude ', 'norm_sym_tensor ', 'mag_sym_tensor '
Definition at line 64 of file m_more_component_flags.f90.
Referenced by dealloc_more_componnet_flags(), init_more_componnet_flags(), set_components_flags::s_set_components_flags(), and set_primary_componnet_flag().
t_flags
character(len=kchara), dimension(2), parameter m_more_component_flags::t_flags = (/'theta ', 'elevation '/)
Definition at line 31 of file m_more_component_flags.f90.
Referenced by init_more_componnet_flags().
theta_flags
type(multi_flag_labels), save m_more_component_flags::theta_flags
flags for theta component 'theta ', 'elevation '
Definition at line 54 of file m_more_component_flags.f90.
Referenced by dealloc_more_componnet_flags(), init_more_componnet_flags(), set_components_flags::s_set_components_flags(), and set_primary_componnet_flag().