CALYPSO: copy_field_smp Module Reference
copy_field_smp Module Reference
Functions/Subroutines
subroutine copy_nod_scalar_smp (nnod, scalar, copied)
subroutine copy_nod_vector_smp (nnod, vector, copied)
subroutine copy_nod_sym_tensor_smp (nnod, tensor, copied)
subroutine copy_all_field_smp (nnod, ntot_comp, vector, copied)
subroutine copy_nod_integer_smp (nnod, int_scalar, int_copied)
Function/Subroutine Documentation
copy_all_field_smp()
subroutine copy_field_smp::copy_all_field_smp (integer (kind = kint) nnod, integer (kind = kint) ntot_comp, real(kind=kreal), dimension(nnod,ntot_comp), intent(in) vector, real(kind=kreal), dimension(nnod,ntot_comp), intent(inout) copied)
Definition at line 92 of file copy_field_smp.f90.
copy_nod_integer_smp()
subroutine copy_field_smp::copy_nod_integer_smp (integer (kind = kint) nnod, integer (kind = kint), dimension(nnod), intent(in) int_scalar, integer (kind = kint), dimension(nnod), intent(inout) int_copied)
Definition at line 108 of file copy_field_smp.f90.
copy_nod_scalar_smp()
subroutine copy_field_smp::copy_nod_scalar_smp (integer (kind = kint) nnod, real(kind=kreal), dimension(nnod), intent(in) scalar, real(kind=kreal), dimension(nnod), intent(inout) copied)
Definition at line 40 of file copy_field_smp.f90.
Referenced by cal_sol_sph_fluid_crank::cal_sol_velo_by_vort_sph_crank(), convert_components_4_viz::convert_comps_4_viz(), copy_nodal_fields::copy_scalar_component(), and set_const_4_sections::set_constant_4_iso().
copy_nod_sym_tensor_smp()
subroutine copy_field_smp::copy_nod_sym_tensor_smp (integer (kind = kint) nnod, real(kind=kreal), dimension(nnod,6), intent(in) tensor, real(kind=kreal), dimension(nnod,6), intent(inout) copied)
Definition at line 72 of file copy_field_smp.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and copy_nodal_fields::copy_tensor_component().
copy_nod_vector_smp()
subroutine copy_field_smp::copy_nod_vector_smp (integer (kind = kint) nnod, real(kind=kreal), dimension(nnod,3), intent(in) vector, real(kind=kreal), dimension(nnod,3), intent(inout) copied)
Definition at line 55 of file copy_field_smp.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and copy_nodal_fields::copy_vector_component().