CALYPSO: gz_mpi_ascii_data_io Module Reference
gz_mpi_ascii_data_io Module Reference
Output merged binary field file using MPI-IO.
Functions/Subroutines
subroutine gz_mpi_write_charahead (IO_param, ilength, chara_dat)
subroutine gz_mpi_write_num_of_data (IO_param, num)
subroutine gz_mpi_write_stack_over_domain (IO_param, ilength)
subroutine gz_mpi_write_characters (IO_param, ilength, chara_dat)
subroutine gz_mpi_read_num_of_data (IO_param, num)
character(len=ilength) function gz_mpi_read_charahead (IO_param, ilength)
character(len=ilength) function gz_mpi_read_characters (IO_param, ilength)
subroutine gz_mpi_skip_header (IO_param, ilength)
Detailed Description
Output merged binary field file using MPI-IO.
      subroutine gz_mpi_write_charahead(IO_param, ilength, chara_dat)
      subroutine gz_mpi_write_num_of_data(IO_param, num)
      subroutine gz_mpi_write_stack_over_domain(IO_param, ilength)
      subroutine gz_mpi_write_characters(IO_param, ilength, chara_dat)
      subroutine gz_mpi_read_num_of_data(IO_param, num)
      function gz_mpi_read_charahead(IO_param, ilength)
        character(len=ilength) :: gz_mpi_read_charahead
      function gz_mpi_read_characters(IO_param, ilength)
        character(len=ilength) :: gz_mpi_read_characters
      subroutine gz_mpi_skip_header(IO_param, ilength)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
Function/Subroutine Documentation
gz_mpi_read_characters()
character(len=ilength) function gz_mpi_ascii_data_io::gz_mpi_read_characters (type(calypso_mpi_io_params), intent(inout) IO_param, integer, intent(in) ilength)
Definition at line 192 of file gz_MPI_ascii_data_IO.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), m_calypso_mpi_io::calypso_mpi_seek_read_gz(), and zlib_convert_text::infleate_characters().
Referenced by gz_mpi_domain_data_io::gz_mpi_read_int_vector().
gz_mpi_read_charahead()
character(len=ilength) function gz_mpi_ascii_data_io::gz_mpi_read_charahead (type(calypso_mpi_io_params), intent(inout) IO_param, integer, intent(in) ilength)
Definition at line 159 of file gz_MPI_ascii_data_IO.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), calypso_mpi_char::calypso_mpi_bcast_character(), calypso_mpi_int8::calypso_mpi_bcast_one_int8(), m_calypso_mpi_io::calypso_mpi_seek_read_gz(), transfer_to_long_integers::cast_long(), zlib_convert_text::infleate_characters(), and calypso_mpi::my_rank.
Referenced by gz_mpi_domain_data_io::gz_mpi_check_num_of_domains(), gz_mpi_sph_gl_1d_idx_io::gz_mpi_read_1d_gl_address(), gz_mpi_domain_data_io::gz_mpi_read_comm_table(), gz_mpi_integer_list_io::gz_mpi_read_ele_connect(), gz_mpi_integer_list_io::gz_mpi_read_element_type(), gz_mpi_spherical_model_io::gz_mpi_read_gl_reso_sph(), gz_mpi_groups_io::gz_mpi_read_group_data(), gz_mpi_integer_list_io::gz_mpi_read_int_list(), gz_mpi_domain_data_io::gz_mpi_read_int_vector(), gz_mpi_position_io::gz_mpi_read_node_position(), gz_mpi_read_num_of_data(), gz_mpi_groups_io::gz_mpi_read_surf_grp_data(), and gz_mpi_vectors_io::gz_mpi_read_vector().
gz_mpi_read_num_of_data()
subroutine gz_mpi_ascii_data_io::gz_mpi_read_num_of_data (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(inout) num)
Definition at line 136 of file gz_MPI_ascii_data_IO.f90.
References gz_mpi_read_charahead(), data_io_to_textline::len_byte_stack_textline(), and data_io_to_textline::read_byte_stack_textline().
Referenced by gz_mpi_domain_data_io::gz_mpi_read_domain_info(), gz_mpi_element_connect_io::gz_mpi_read_edge_4_element(), gz_mpi_element_connect_io::gz_mpi_read_element_info(), gz_mpi_domain_data_io::gz_mpi_read_export_data(), gz_mpi_spherical_model_io::gz_mpi_read_gl_nodes_sph(), gz_mpi_spherical_model_io::gz_mpi_read_gl_reso_sph(), gz_mpi_groups_io::gz_mpi_read_group_data(), gz_mpi_domain_data_io::gz_mpi_read_import_data(), gz_mpi_element_connect_io::gz_mpi_read_num_element(), gz_mpi_spherical_model_io::gz_mpi_read_rank_4_sph(), gz_mpi_sph_gl_1d_idx_io::gz_mpi_read_rj_gl_1d_table(), gz_mpi_sph_gl_1d_idx_io::gz_mpi_read_rtp_gl_1d_table(), gz_mpi_groups_io::gz_mpi_read_surf_grp_data(), gz_mpi_groups_io::gz_mpi_read_surf_grp_item(), and gz_mpi_element_connect_io::gz_mpi_read_surface_4_element().
gz_mpi_skip_header()
subroutine gz_mpi_ascii_data_io::gz_mpi_skip_header (type(calypso_mpi_io_params), intent(inout) IO_param, integer, intent(in) ilength)
Definition at line 222 of file gz_MPI_ascii_data_IO.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), calypso_mpi_int8::calypso_mpi_bcast_one_int8(), m_calypso_mpi_io::calypso_mpi_seek_read_gz(), zlib_convert_text::infleate_skip_header(), and calypso_mpi::my_rank.
Referenced by gz_mpi_edge_data_io::gz_mpi_read_edge_connect(), gz_mpi_edge_data_io::gz_mpi_read_edge_geometry(), gz_mpi_element_data_io::gz_mpi_read_ele_comm_table(), gz_mpi_element_data_io::gz_mpi_read_ele_geometry(), gz_mpi_sph_modes_data_io::gz_mpi_read_geom_rtm_data(), gz_mpi_sph_modes_data_io::gz_mpi_read_geom_rtp_data(), gz_mpi_mesh_data_io::gz_mpi_read_geometry_data(), gz_mpi_spherical_model_io::gz_mpi_read_gl_reso_sph(), gz_mpi_mesh_data_io::gz_mpi_read_mesh_groups(), gz_mpi_sph_modes_data_io::gz_mpi_read_modes_rlm_data(), gz_mpi_mesh_data_io::gz_mpi_read_num_node(), gz_mpi_mesh_data_io::gz_mpi_read_num_node_ele(), gz_mpi_spherical_model_io::gz_mpi_read_rank_4_sph(), gz_mpi_sph_gl_1d_idx_io::gz_mpi_read_rj_gl_1d_table(), gz_mpi_sph_gl_1d_idx_io::gz_mpi_read_rtp_gl_1d_table(), gz_mpi_sph_modes_data_io::gz_mpi_read_spectr_rj_data(), gz_mpi_surface_data_io::gz_mpi_read_surf_connect(), and gz_mpi_surface_data_io::gz_mpi_read_surf_geometry().
gz_mpi_write_characters()
subroutine gz_mpi_ascii_data_io::gz_mpi_write_characters (type(calypso_mpi_io_params), intent(inout) IO_param, integer, intent(in) ilength, character(len=ilength), intent(in) chara_dat)
Definition at line 105 of file gz_MPI_ascii_data_IO.f90.
References m_calypso_mpi_io::calypso_mpi_seek_write_gz(), t_buffer_4_gzip::dealloc_zip_buffer(), zlib_convert_text::defleate_characters(), gz_mpi_write_stack_over_domain(), and calypso_mpi::my_rank.
Referenced by gz_mpi_domain_data_io::gz_mpi_write_int_vector().
gz_mpi_write_charahead()
subroutine gz_mpi_ascii_data_io::gz_mpi_write_charahead (type(calypso_mpi_io_params), intent(inout) IO_param, integer, intent(in) ilength, character(len=ilength), intent(in) chara_dat)
Definition at line 45 of file gz_MPI_ascii_data_IO.f90.
References calypso_mpi_int8::calypso_mpi_bcast_one_int8(), m_calypso_mpi_io::calypso_mpi_seek_write_gz(), t_buffer_4_gzip::dealloc_zip_buffer(), zlib_convert_text::defleate_characters(), and calypso_mpi::my_rank.
Referenced by gz_mpi_viewer_mesh_io::gz_mpi_write_domain_grp_data(), gz_mpi_domain_data_io::gz_mpi_write_domain_info(), gz_mpi_edge_data_io::gz_mpi_write_edge_connect(), gz_mpi_edge_data_io::gz_mpi_write_edge_geometry(), gz_mpi_element_data_io::gz_mpi_write_ele_comm_table(), gz_mpi_element_data_io::gz_mpi_write_ele_geometry(), gz_mpi_sph_modes_data_io::gz_mpi_write_geom_rtm_data(), gz_mpi_sph_modes_data_io::gz_mpi_write_geom_rtp_data(), gz_mpi_mesh_data_io::gz_mpi_write_geometry_data(), gz_mpi_spherical_model_io::gz_mpi_write_gl_reso_sph(), gz_mpi_groups_io::gz_mpi_write_grp_data(), gz_mpi_mesh_data_io::gz_mpi_write_mesh_groups(), gz_mpi_sph_modes_data_io::gz_mpi_write_modes_rlm_data(), gz_mpi_write_num_of_data(), gz_mpi_spherical_model_io::gz_mpi_write_rank_4_sph(), gz_mpi_sph_gl_1d_idx_io::gz_mpi_write_rj_gl_1d_table(), gz_mpi_sph_gl_1d_idx_io::gz_mpi_write_rtp_gl_1d_table(), gz_mpi_sph_modes_data_io::gz_mpi_write_spectr_rj_data(), gz_mpi_write_stack_over_domain(), gz_mpi_surface_data_io::gz_mpi_write_surf_connect(), gz_mpi_surface_data_io::gz_mpi_write_surf_geometry(), gz_mpi_groups_io::gz_mpi_write_surf_grp_data(), gz_mpi_viewer_mesh_io::gz_mpi_write_viewer_grp_data(), and gz_mpi_viewer_mesh_file_io::gz_write_viewer_mesh_infos().
gz_mpi_write_num_of_data()
subroutine gz_mpi_ascii_data_io::gz_mpi_write_num_of_data (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) num)
Definition at line 73 of file gz_MPI_ascii_data_IO.f90.
References data_io_to_textline::byte_stack_textline(), gz_mpi_write_charahead(), data_io_to_textline::len_byte_stack_textline(), and t_calypso_mpi_io_param::set_numbers_2_head_node().
Referenced by gz_mpi_sph_gl_1d_idx_io::gz_mpi_write_1d_gl_address(), gz_mpi_domain_data_io::gz_mpi_write_comm_table(), gz_mpi_element_connect_io::gz_mpi_write_edge_4_element(), gz_mpi_element_connect_io::gz_mpi_write_element_info(), gz_mpi_spherical_model_io::gz_mpi_write_gl_nodes_sph(), gz_mpi_domain_data_io::gz_mpi_write_int_vector(), gz_mpi_sph_gl_1d_idx_io::gz_mpi_write_rj_gl_1d_table(), gz_mpi_sph_gl_1d_idx_io::gz_mpi_write_rtp_gl_1d_table(), and gz_mpi_element_connect_io::gz_mpi_write_surface_4_element().
gz_mpi_write_stack_over_domain()
subroutine gz_mpi_ascii_data_io::gz_mpi_write_stack_over_domain (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint_gl), intent(in) ilength)
Definition at line 89 of file gz_MPI_ascii_data_IO.f90.
References data_io_to_textline::byte_stack_textline(), gz_mpi_write_charahead(), t_calypso_mpi_io_param::istack64_4_parallel_data(), and data_io_to_textline::len_byte_stack_textline().
Referenced by gz_mpi_sph_gl_1d_idx_io::gz_mpi_write_1d_gl_address(), gz_mpi_write_characters(), gz_mpi_domain_data_io::gz_mpi_write_comm_table(), gz_mpi_viewer_mesh_io::gz_mpi_write_domain_grp_data(), gz_mpi_integer_list_io::gz_mpi_write_ele_connect(), gz_mpi_integer_list_io::gz_mpi_write_element_type(), gz_mpi_integer_list_io::gz_mpi_write_int_list(), gz_mpi_position_io::gz_mpi_write_node_position(), gz_mpi_vectors_io::gz_mpi_write_vector(), gz_mpi_viewer_mesh_io::gz_mpi_write_viewer_grp_data(), gz_mpi_viewer_mesh_io::gz_mpi_write_viewer_grp_item(), gz_mpi_viewer_mesh_io::gz_mpi_write_viewer_position(), and gz_mpi_viewer_mesh_file_io::gz_write_viewer_mesh_infos().