CALYPSO: set_control_sph_subdomains Module Reference
set_control_sph_subdomains Module Reference
Set control data for domain decomposition for spherical transform.
Functions/Subroutines
subroutine set_inner_loop_4_sph_shell (sdctl, s3d_ranks)
subroutine set_subdomains_4_sph_shell (nprocs_check, sdctl, s3d_ranks, ierr, e_message)
subroutine, private full_subdomains_4_sph_shell (sdctl, s3d_ranks)
subroutine, private simple_subdomains_4_sph_shell (sdctl, s3d_ranks)
Variables
character(len=kchara), parameter, private radius1 = 'r'
character(len=kchara), parameter, private radius2 = 'radial'
character(len=kchara), parameter radius3 = 'radius'
character(len=kchara), parameter, private theta1 = 'theta'
character(len=kchara), parameter, private theta2 = 'meridional'
character(len=kchara), parameter, private phi1 = 'phi'
character(len=kchara), parameter, private phi2 = 'zonal'
character(len=kchara), parameter, private mode1 = 'degree_order'
character(len=kchara), parameter, private mode2 = 'modes'
character(len=kchara), parameter, private horiz1 = 'horizontal'
character(len=kchara), parameter, private original = 'original'
character(len=kchara), parameter, private simple = 'simple'
character(len=kchara), parameter, private cyclic_mode = 'cyclic_eq_mode'
character(len=kchara), parameter, private cyclic_trns = 'cyclic_eq_trans'
character(len=kchara), parameter, private cyclic_neib_mode = 'cyclic_neib_eq_mode'
character(len=kchara), parameter, private cyclic_neib_trns = 'cyclic_neib_eq_trans'
character(len=kchara), parameter, private test_ditribution = 'test'
character(len=kchara), parameter, private hd_ver_1 = 'Ver_1'
character(len=kchara), parameter, private hd_ver_2 = 'Ver_2'
Detailed Description
Set control data for domain decomposition for spherical transform.
      subroutine set_inner_loop_4_sph_shell(sdctl, s3d_ranks)
        type(sphere_domain_control), intent(in) :: sdctl
        type(spheric_global_rank), intent(inout) :: s3d_ranks
      subroutine set_subdomains_4_sph_shell                           &
     &         (nprocs_check, sdctl, s3d_ranks, ierr, e_message)
        type(sphere_domain_control), intent(in) :: sdctl
        type(spheric_global_rank), intent(inout) :: s3d_ranks
Function/Subroutine Documentation
full_subdomains_4_sph_shell()
subroutine, private set_control_sph_subdomains::full_subdomains_4_sph_shell (type(sphere_domain_control), intent(in) sdctl, type(spheric_global_rank), intent(inout) s3d_ranks) private
Definition at line 226 of file set_control_sph_subdomains.f90.
References skip_comment_f::cmp_no_case(), mode1, mode2, phi1, phi2, radius1, radius2, theta1, and theta2.
Referenced by set_subdomains_4_sph_shell().
set_inner_loop_4_sph_shell()
subroutine set_control_sph_subdomains::set_inner_loop_4_sph_shell (type(sphere_domain_control), intent(in) sdctl, type(spheric_global_rank), intent(inout) s3d_ranks)
Definition at line 82 of file set_control_sph_subdomains.f90.
References skip_comment_f::cmp_no_case(), cyclic_mode, cyclic_neib_mode, hd_ver_1, hd_ver_2, horiz1, select_zonal_4_legendre::id_cyclic_eq_mode, select_zonal_4_legendre::id_cyclic_eq_mode_neib, select_zonal_4_legendre::id_simple_rlm_distribute, select_zonal_4_legendre::id_test_distribute, select_zonal_4_legendre::id_v1_rlm_distribute, original, phi1, phi2, radius1, radius2, radius3, simple, and test_ditribution.
Referenced by t_ctl_params_gen_sph_shell::set_control_4_shell_grids().
set_subdomains_4_sph_shell()
subroutine set_control_sph_subdomains::set_subdomains_4_sph_shell (integer, intent(in) nprocs_check, type(sphere_domain_control), intent(in) sdctl, type(spheric_global_rank), intent(inout) s3d_ranks, integer(kind = kint), intent(inout) ierr, character(len = kchara), intent(inout) e_message)
Definition at line 179 of file set_control_sph_subdomains.f90.
References t_spheric_global_ranks::check_sph_domains(), skip_comment_f::cmp_no_case(), full_subdomains_4_sph_shell(), m_error_ids::ierr_mesh, radius1, radius2, radius3, and simple_subdomains_4_sph_shell().
Referenced by t_ctl_params_gen_sph_shell::set_control_4_shell_grids().
simple_subdomains_4_sph_shell()
subroutine, private set_control_sph_subdomains::simple_subdomains_4_sph_shell (type(sphere_domain_control), intent(in) sdctl, type(spheric_global_rank), intent(inout) s3d_ranks) private
Definition at line 292 of file set_control_sph_subdomains.f90.
Referenced by set_subdomains_4_sph_shell().
Variable Documentation
cyclic_mode
character(len = kchara), parameter, private set_control_sph_subdomains::cyclic_mode = 'cyclic_eq_mode' private
Definition at line 48 of file set_control_sph_subdomains.f90.
Referenced by set_inner_loop_4_sph_shell().
cyclic_neib_mode
character(len = kchara), parameter, private set_control_sph_subdomains::cyclic_neib_mode = 'cyclic_neib_eq_mode' private
Definition at line 53 of file set_control_sph_subdomains.f90.
Referenced by set_inner_loop_4_sph_shell().
cyclic_neib_trns
character(len = kchara), parameter, private set_control_sph_subdomains::cyclic_neib_trns = 'cyclic_neib_eq_trans' private
Definition at line 55 of file set_control_sph_subdomains.f90.
cyclic_trns
character(len = kchara), parameter, private set_control_sph_subdomains::cyclic_trns = 'cyclic_eq_trans' private
Definition at line 50 of file set_control_sph_subdomains.f90.
hd_ver_1
character(len = kchara), parameter, private set_control_sph_subdomains::hd_ver_1 = 'Ver_1' private
Definition at line 61 of file set_control_sph_subdomains.f90.
Referenced by set_inner_loop_4_sph_shell().
hd_ver_2
character(len = kchara), parameter, private set_control_sph_subdomains::hd_ver_2 = 'Ver_2' private
Definition at line 63 of file set_control_sph_subdomains.f90.
Referenced by set_inner_loop_4_sph_shell().
horiz1
character(len=kchara), parameter, private set_control_sph_subdomains::horiz1 = 'horizontal' private
Definition at line 42 of file set_control_sph_subdomains.f90.
Referenced by set_inner_loop_4_sph_shell().
mode1
character(len=kchara), parameter, private set_control_sph_subdomains::mode1 = 'degree_order' private
Definition at line 39 of file set_control_sph_subdomains.f90.
Referenced by full_subdomains_4_sph_shell().
mode2
character(len=kchara), parameter, private set_control_sph_subdomains::mode2 = 'modes' private
Definition at line 40 of file set_control_sph_subdomains.f90.
Referenced by full_subdomains_4_sph_shell().
original
character(len = kchara), parameter, private set_control_sph_subdomains::original = 'original' private
Definition at line 45 of file set_control_sph_subdomains.f90.
Referenced by set_inner_loop_4_sph_shell().
phi1
character(len=kchara), parameter, private set_control_sph_subdomains::phi1 = 'phi' private
Definition at line 36 of file set_control_sph_subdomains.f90.
Referenced by full_subdomains_4_sph_shell(), and set_inner_loop_4_sph_shell().
phi2
character(len=kchara), parameter, private set_control_sph_subdomains::phi2 = 'zonal' private
Definition at line 37 of file set_control_sph_subdomains.f90.
Referenced by full_subdomains_4_sph_shell(), and set_inner_loop_4_sph_shell().
radius1
character(len=kchara), parameter, private set_control_sph_subdomains::radius1 = 'r' private
Definition at line 29 of file set_control_sph_subdomains.f90.
Referenced by full_subdomains_4_sph_shell(), set_inner_loop_4_sph_shell(), and set_subdomains_4_sph_shell().
radius2
character(len=kchara), parameter, private set_control_sph_subdomains::radius2 = 'radial' private
Definition at line 30 of file set_control_sph_subdomains.f90.
Referenced by full_subdomains_4_sph_shell(), set_inner_loop_4_sph_shell(), and set_subdomains_4_sph_shell().
radius3
character(len=kchara), parameter set_control_sph_subdomains::radius3 = 'radius'
Definition at line 31 of file set_control_sph_subdomains.f90.
Referenced by set_inner_loop_4_sph_shell(), and set_subdomains_4_sph_shell().
simple
character(len = kchara), parameter, private set_control_sph_subdomains::simple = 'simple' private
Definition at line 46 of file set_control_sph_subdomains.f90.
Referenced by set_inner_loop_4_sph_shell().
test_ditribution
character(len = kchara), parameter, private set_control_sph_subdomains::test_ditribution = 'test' private
Definition at line 58 of file set_control_sph_subdomains.f90.
Referenced by set_inner_loop_4_sph_shell().
theta1
character(len=kchara), parameter, private set_control_sph_subdomains::theta1 = 'theta' private
Definition at line 33 of file set_control_sph_subdomains.f90.
Referenced by full_subdomains_4_sph_shell().
theta2
character(len=kchara), parameter, private set_control_sph_subdomains::theta2 = 'meridional' private
Definition at line 34 of file set_control_sph_subdomains.f90.
Referenced by full_subdomains_4_sph_shell().