CALYPSO: gz_domain_data_io_b Module Reference
gz_domain_data_io_b Module Reference
Routine for gzipped binary doimain data IO.
Functions/Subroutines
subroutine gz_read_domain_info_b (id_rank, zbuf, comm_IO)
subroutine gz_read_import_data_b (zbuf, comm_IO)
subroutine gz_read_export_data_b (zbuf, comm_IO)
subroutine gz_write_domain_info_b (id_rank, comm_IO, zbuf)
subroutine gz_write_import_data_b (comm_IO, zbuf)
subroutine gz_write_export_data_b (comm_IO, zbuf)
Detailed Description
Routine for gzipped binary doimain data IO.
      subroutine gz_read_domain_info_b(id_rank, zbuf, comm_IO)
      subroutine gz_read_import_data_b(zbuf, comm_IO)
      subroutine gz_read_export_data_b(zbuf, comm_IO)
        type(buffer_4_gzip), intent(inout) :: zbuf
        type(communication_table), intent(inout) :: comm_IO
      subroutine gz_write_domain_info_b(id_rank, comm_IO, zbuf)
      subroutine gz_write_import_data_b(comm_IO, zbuf)
      subroutine gz_write_export_data_b(comm_IO, zbuf)
        type(communication_table), intent(in) :: comm_IO
        type(buffer_4_gzip), intent(inout) :: zbuf
Function/Subroutine Documentation
gz_read_domain_info_b()
subroutine gz_domain_data_io_b::gz_read_domain_info_b (integer, intent(in) id_rank, type(buffer_4_gzip), intent(inout) zbuf, type(communication_table), intent(inout) comm_IO)
Definition at line 43 of file gz_domain_data_IO_b.f90.
References t_comm_table::alloc_neighbouring_id(), transfer_to_long_integers::cast_long(), gz_binary_io::gz_read_mul_integer_b(), gz_binary_io::gz_read_one_integer_b(), and m_error_ids::ierr_mesh.
Referenced by gz_edge_data_io_b::gz_read_edge_connection_b(), gz_element_data_io_b::gz_read_element_comm_table_b(), gz_sph_modes_data_io_b::gz_read_geom_rtm_data_b(), gz_sph_modes_data_io_b::gz_read_geom_rtp_data_b(), gz_sph_modes_data_io_b::gz_read_modes_rlm_data_b(), gz_mesh_data_io_b::gz_read_num_node_b(), gz_sph_modes_data_io_b::gz_read_spectr_modes_rj_data_b(), and gz_surface_data_io_b::gz_read_surface_connection_b().
gz_read_export_data_b()
subroutine gz_domain_data_io_b::gz_read_export_data_b (type(buffer_4_gzip), intent(inout) zbuf, type(communication_table), intent(inout) comm_IO)
Definition at line 106 of file gz_domain_data_IO_b.f90.
References t_comm_table::alloc_export_item(), t_comm_table::alloc_export_num(), transfer_to_long_integers::cast_long(), gz_binary_io::gz_read_integer_stack_b(), and gz_binary_io::gz_read_mul_integer_b().
Referenced by gz_edge_data_io_b::gz_read_edge_connection_b(), gz_element_data_io_b::gz_read_element_comm_table_b(), gz_mesh_data_io_b::gz_read_geometry_data_b(), and gz_surface_data_io_b::gz_read_surface_connection_b().
gz_read_import_data_b()
subroutine gz_domain_data_io_b::gz_read_import_data_b (type(buffer_4_gzip), intent(inout) zbuf, type(communication_table), intent(inout) comm_IO)
Definition at line 78 of file gz_domain_data_IO_b.f90.
References t_comm_table::alloc_import_item(), t_comm_table::alloc_import_num(), transfer_to_long_integers::cast_long(), gz_binary_io::gz_read_integer_stack_b(), and gz_binary_io::gz_read_mul_integer_b().
Referenced by gz_edge_data_io_b::gz_read_edge_connection_b(), gz_element_data_io_b::gz_read_element_comm_table_b(), gz_sph_modes_data_io_b::gz_read_geom_rtm_data_b(), gz_sph_modes_data_io_b::gz_read_geom_rtp_data_b(), gz_mesh_data_io_b::gz_read_geometry_data_b(), gz_sph_modes_data_io_b::gz_read_modes_rlm_data_b(), gz_sph_modes_data_io_b::gz_read_spectr_modes_rj_data_b(), and gz_surface_data_io_b::gz_read_surface_connection_b().
gz_write_domain_info_b()
subroutine gz_domain_data_io_b::gz_write_domain_info_b (integer, intent(in) id_rank, type(communication_table), intent(in) comm_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 133 of file gz_domain_data_IO_b.f90.
References transfer_to_long_integers::cast_long(), gz_binary_io::gz_write_mul_integer_b(), and gz_binary_io::gz_write_one_integer_b().
Referenced by gz_edge_data_io_b::gz_write_edge_connection_b(), gz_element_data_io_b::gz_write_element_comm_table_b(), gz_sph_modes_data_io_b::gz_write_geom_rtm_data_b(), gz_sph_modes_data_io_b::gz_write_geom_rtp_data_b(), gz_mesh_data_io_b::gz_write_geometry_data_b(), gz_sph_modes_data_io_b::gz_write_modes_rlm_data_b(), gz_sph_modes_data_io_b::gz_write_spectr_modes_rj_data_b(), and gz_surface_data_io_b::gz_write_surface_connection_b().
gz_write_export_data_b()
subroutine gz_domain_data_io_b::gz_write_export_data_b (type(communication_table), intent(in) comm_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 174 of file gz_domain_data_IO_b.f90.
References transfer_to_long_integers::cast_long(), gz_binary_io::gz_write_integer_stack_b(), and gz_binary_io::gz_write_mul_integer_b().
Referenced by gz_edge_data_io_b::gz_write_edge_connection_b(), gz_element_data_io_b::gz_write_element_comm_table_b(), gz_mesh_data_io_b::gz_write_geometry_data_b(), and gz_surface_data_io_b::gz_write_surface_connection_b().
gz_write_import_data_b()
subroutine gz_domain_data_io_b::gz_write_import_data_b (type(communication_table), intent(in) comm_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 157 of file gz_domain_data_IO_b.f90.
References transfer_to_long_integers::cast_long(), gz_binary_io::gz_write_integer_stack_b(), and gz_binary_io::gz_write_mul_integer_b().
Referenced by gz_edge_data_io_b::gz_write_edge_connection_b(), gz_element_data_io_b::gz_write_element_comm_table_b(), gz_sph_modes_data_io_b::gz_write_geom_rtm_data_b(), gz_sph_modes_data_io_b::gz_write_geom_rtp_data_b(), gz_mesh_data_io_b::gz_write_geometry_data_b(), gz_sph_modes_data_io_b::gz_write_modes_rlm_data_b(), gz_sph_modes_data_io_b::gz_write_spectr_modes_rj_data_b(), and gz_surface_data_io_b::gz_write_surface_connection_b().