CALYPSO: t_ctl_data_4_fields Module Reference
t_ctl_data_4_fields Module Reference
Data Types
type field_control
Structure of field information control.
Functions/Subroutines
subroutine dealloc_phys_control (fld_ctl)
subroutine read_phys_data_control (id_control, hd_block, fld_ctl, c_buf)
subroutine write_phys_data_control (id_control, hd_block, fld_ctl, level)
Variables
character(len=kchara), parameter, private hd_field_list = 'nod_value_ctl'
character(len=kchara), parameter, private hd_quad_field = 'quad_field_name_ctl'
character(len=kchara), parameter hd_scalar_field = 'scalar_field_ctl'
character(len=kchara), parameter hd_vector_field = 'vector_field_ctl'
Function/Subroutine Documentation
dealloc_phys_control()
subroutine t_ctl_data_4_fields::dealloc_phys_control (type(field_control), intent(inout) fld_ctl)
Definition at line 127 of file t_ctl_data_4_fields.f90.
References t_control_array_character3::dealloc_control_array_c3(), t_control_array_charaint::dealloc_control_array_c_i(), t_control_array_charaint3::dealloc_control_array_c_i3(), and t_control_array_character::dealloc_control_array_chara().
Referenced by t_ctl_data_mhd_model::dealloc_sph_mhd_model(), and t_control_data_4_merge::reset_merge_field_data().
read_phys_data_control()
subroutine t_ctl_data_4_fields::read_phys_data_control (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(field_control), intent(inout) fld_ctl, type(buffer_for_control), intent(inout) c_buf)
Definition at line 142 of file t_ctl_data_4_fields.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_field_list, hd_quad_field, hd_scalar_field, hd_vector_field, t_read_control_elements::load_one_line_from_control(), t_control_array_character::read_control_array_c1(), t_control_array_character3::read_control_array_c3(), t_control_array_charaint::read_control_array_c_i(), and t_control_array_charaint3::read_control_array_c_i3().
Referenced by t_control_data_4_merge::read_merge_field_data(), and t_ctl_data_mhd_model::read_sph_mhd_model().
write_phys_data_control()
subroutine t_ctl_data_4_fields::write_phys_data_control (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(field_control), intent(in) fld_ctl, integer(kind = kint), intent(inout) level)
Definition at line 177 of file t_ctl_data_4_fields.f90.
References hd_field_list, hd_quad_field, hd_scalar_field, hd_vector_field, write_control_elements::write_begin_flag_for_ctl(), t_control_array_character::write_control_array_c1(), t_control_array_character3::write_control_array_c3(), t_control_array_charaint::write_control_array_c_i(), t_control_array_charaint3::write_control_array_c_i3(), and write_control_elements::write_end_flag_for_ctl().
Variable Documentation
hd_field_list
character(len=kchara), parameter, private t_ctl_data_4_fields::hd_field_list = 'nod_value_ctl' private
Definition at line 106 of file t_ctl_data_4_fields.f90.
Referenced by read_phys_data_control(), and write_phys_data_control().
hd_quad_field
character(len=kchara), parameter, private t_ctl_data_4_fields::hd_quad_field = 'quad_field_name_ctl' private
Definition at line 111 of file t_ctl_data_4_fields.f90.
Referenced by read_phys_data_control(), and write_phys_data_control().
hd_scalar_field
character(len=kchara), parameter t_ctl_data_4_fields::hd_scalar_field = 'scalar_field_ctl'
Definition at line 114 of file t_ctl_data_4_fields.f90.
Referenced by read_phys_data_control(), and write_phys_data_control().
hd_vector_field
character(len=kchara), parameter t_ctl_data_4_fields::hd_vector_field = 'vector_field_ctl'
Definition at line 116 of file t_ctl_data_4_fields.f90.
Referenced by read_phys_data_control(), and write_phys_data_control().