CALYPSO: set_psf_patch_4_by_surf_grp Module Reference
set_psf_patch_4_by_surf_grp Module Reference
Functions/Subroutines
subroutine count_num_patch_4_grp (sf_grp, igrp, istack_patch_smp)
subroutine set_patch_4_grp (ele, sf_grp, psf_grp_list, igrp, istack_numele, npatch_tot, istack_patch_smp, iele_global, ie_patch)
Function/Subroutine Documentation
count_num_patch_4_grp()
subroutine set_psf_patch_4_by_surf_grp::count_num_patch_4_grp (type(surface_group_data), intent(in) sf_grp, integer(kind = kint), intent(in) igrp, integer(kind = kint), dimension(0:np_smp), intent(inout) istack_patch_smp)
Definition at line 27 of file set_psf_patch_4_by_surf_grp.f90.
References cal_minmax_and_stacks::count_number_4_smp().
Referenced by set_patches_for_psf::count_psf_patches().
set_patch_4_grp()
subroutine set_psf_patch_4_by_surf_grp::set_patch_4_grp (type(element_data), intent(in) ele, type(surface_group_data), intent(in) sf_grp, type(grp_section_list), intent(in) psf_grp_list, integer(kind = kint), intent(in) igrp, integer(kind = kint_gl), intent(in) istack_numele, integer(kind = kint), intent(in) npatch_tot, integer(kind = kint), dimension(0:np_smp), intent(in) istack_patch_smp, integer(kind = kint_gl), dimension(npatch_tot), intent(inout) iele_global, integer(kind = kint_gl), dimension(npatch_tot,num_triangle), intent(inout) ie_patch)
Definition at line 51 of file set_psf_patch_4_by_surf_grp.f90.
References m_quad_2_triangle::ie_quad_2_tri, and m_geometry_constants::node_on_sf_4.
Referenced by set_patches_for_psf::set_psf_patches().