CALYPSO: /home/takumi kera/calypso/src/programs/data_utilities/TIME_HISTORIES/t_average_sph_ene_spec.f90 File Reference
t_average_sph_ene_spec.f90 File Reference
program t_average_sph_ene_spec
Functions/Subroutines
program t_average_sph_ene_spec
Evaluate time average and standard deviation from spherical harmonics spectrum data.
Detailed Description
program t_average_sph_ene_spec
Author
H. Matsui
Date
Programmed in Nov., 2007
Definition in file t_average_sph_ene_spec.f90.
Function/Subroutine Documentation
t_average_sph_ene_spec()
program t_average_sph_ene_spec
Evaluate time average and standard deviation from spherical harmonics spectrum data.
Definition at line 11 of file t_average_sph_ene_spec.f90.
References set_parallel_file_name::add_dat_extension(), t_read_sph_spectra::select_sph_ene_spec_data_file(), m_tave_sph_ene_spectr::sph_spectr_average(), and m_tave_sph_ene_spectr::sph_spectr_std_deviation().