CALYPSO: ucd_field_file_io_b Module Reference
ucd_field_file_io_b Module Reference
binary format data IO
Functions/Subroutines
subroutine write_ucd_2_fld_file_b (id_rank, file_name, t_IO, ucd, ierr)
subroutine read_ucd_2_fld_file_b (id_rank, file_name, t_IO, ucd, ierr)
subroutine read_alloc_ucd_2_fld_file_b (id_rank, file_name, t_IO, ucd, ierr)
subroutine read_alloc_ucd_2_fld_header_b (id_rank, file_name, t_IO, ucd, ierr)
Variables
integer(kind=kint), parameter, private id_read_fld = 21
integer(kind=kint), parameter, private id_write_fld = 22
type(binary_io_buffer), private bbuf_ucd
Detailed Description
binary format data IO
      subroutine write_ucd_2_fld_file_b                               &
     &         (id_rank, file_name, t_IO, ucd, ierr)
      subroutine read_ucd_2_fld_file_b                                &
     &         (id_rank, file_name, t_IO, ucd, ierr)
      subroutine read_alloc_ucd_2_fld_file_b                          &
     &         (id_rank, file_name, t_IO, ucd, ierr)
      subroutine read_alloc_ucd_2_fld_header_b                        &
     &         (id_rank, file_name, t_IO, ucd, ierr)
        type(time_data), intent(inout) :: t_IO
        type(ucd_data), intent(inout) :: ucd
Parameters
id_rank process ID
file_name file name
ucd Structure for FEM field data IO
Function/Subroutine Documentation
read_alloc_ucd_2_fld_file_b()
subroutine ucd_field_file_io_b::read_alloc_ucd_2_fld_file_b (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(time_data), intent(inout) t_IO, type(ucd_data), intent(inout) ucd, integer(kind=kint), intent(inout) ierr)
Definition at line 133 of file ucd_field_file_IO_b.f90.
References t_ucd_data::allocate_ucd_phys_data(), t_ucd_data::allocate_ucd_phys_name(), bbuf_ucd, t_ucd_data::cal_istack_ucd_component(), transfer_to_long_integers::cast_long(), binary_io::close_binary_file(), m_machine_parameter::i_debug, id_read_fld, binary_io::open_read_binary_file(), field_data_io_b::read_field_data_b(), binary_io::read_mul_integer_b(), and field_data_io_b::read_step_data_b().
Referenced by ucd_io_select::sel_read_alloc_udt_file().
read_alloc_ucd_2_fld_header_b()
subroutine ucd_field_file_io_b::read_alloc_ucd_2_fld_header_b (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(time_data), intent(inout) t_IO, type(ucd_data), intent(inout) ucd, integer(kind=kint), intent(inout) ierr)
Definition at line 182 of file ucd_field_file_IO_b.f90.
References t_ucd_data::allocate_ucd_phys_data(), t_ucd_data::allocate_ucd_phys_name(), bbuf_ucd, t_ucd_data::cal_istack_ucd_component(), transfer_to_long_integers::cast_long(), binary_io::close_binary_file(), m_machine_parameter::i_debug, id_read_fld, binary_io::open_read_binary_file(), binary_io::read_mul_integer_b(), and field_data_io_b::read_step_data_b().
Referenced by ucd_io_select::sel_read_udt_param().
read_ucd_2_fld_file_b()
subroutine ucd_field_file_io_b::read_ucd_2_fld_file_b (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(time_data), intent(inout) t_IO, type(ucd_data), intent(inout) ucd, integer(kind=kint), intent(inout) ierr)
Definition at line 90 of file ucd_field_file_IO_b.f90.
References bbuf_ucd, transfer_to_long_integers::cast_long(), binary_io::close_binary_file(), m_machine_parameter::i_debug, id_read_fld, binary_io::open_read_binary_file(), field_data_io_b::read_field_data_b(), binary_io::read_mul_integer_b(), and field_data_io_b::read_step_data_b().
Referenced by ucd_io_select::sel_read_udt_file().
write_ucd_2_fld_file_b()
subroutine ucd_field_file_io_b::write_ucd_2_fld_file_b (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(time_data), intent(in) t_IO, type(ucd_data), intent(in) ucd, integer(kind=kint), intent(inout) ierr)
Definition at line 57 of file ucd_field_file_IO_b.f90.
References bbuf_ucd, binary_io::close_binary_file(), m_machine_parameter::i_debug, id_write_fld, binary_io::open_write_binary_file(), field_data_io_b::write_field_data_b(), and field_data_io_b::write_step_data_b().
Referenced by ucd_io_select::sel_write_ucd_file(), and ucd_io_select::sel_write_udt_file().
Variable Documentation
bbuf_ucd
type(binary_io_buffer), private ucd_field_file_io_b::bbuf_ucd private
Definition at line 48 of file ucd_field_file_IO_b.f90.
Referenced by read_alloc_ucd_2_fld_file_b(), read_alloc_ucd_2_fld_header_b(), read_ucd_2_fld_file_b(), and write_ucd_2_fld_file_b().
id_read_fld
integer(kind = kint), parameter, private ucd_field_file_io_b::id_read_fld = 21 private
Definition at line 46 of file ucd_field_file_IO_b.f90.
Referenced by read_alloc_ucd_2_fld_file_b(), read_alloc_ucd_2_fld_header_b(), and read_ucd_2_fld_file_b().
id_write_fld
integer(kind = kint), parameter, private ucd_field_file_io_b::id_write_fld = 22 private
Definition at line 47 of file ucd_field_file_IO_b.f90.
Referenced by write_ucd_2_fld_file_b().