CALYPSO: search_ele_list_for_psf Module Reference
search_ele_list_for_psf Module Reference
set elememnt list for sections
Functions/Subroutines
subroutine set_search_mesh_list_4_psf (num_psf, mesh, group, psf_param, psf_search)
subroutine, private set_searched_element_list_4_psf (num_psf, ele, ele_grp, psf_param, psf_search)
subroutine, private set_searched_surface_list_4_psf (num_psf, ele, surf, psf_search)
subroutine, private set_searched_edge_list_4_psf (num_psf, surf, edge, psf_search)
subroutine, private set_searched_node_list_4_psf (num_psf, node, edge, psf_search)
Detailed Description
set elememnt list for sections
      subroutine set_search_mesh_list_4_psf                           &
     &         (num_psf, mesh, group, psf_param, psf_search)
        type(mesh_geometry), intent(in) :: mesh
        type(mesh_groups), intent(in) :: group
        type(psf_parameters), intent(in) :: psf_param(num_psf)
        type(psf_search_lists), intent(inout) :: psf_search(num_psf)
Function/Subroutine Documentation
set_search_mesh_list_4_psf()
subroutine search_ele_list_for_psf::set_search_mesh_list_4_psf (integer(kind = kint), intent(in) num_psf, type(mesh_geometry), intent(in) mesh, type(mesh_groups), intent(in) group, type(psf_parameters), dimension(num_psf), intent(in) psf_param, type(psf_search_lists), dimension(num_psf), intent(inout) psf_search)
Definition at line 42 of file search_ele_list_for_psf.f90.
References set_searched_edge_list_4_psf(), set_searched_element_list_4_psf(), set_searched_node_list_4_psf(), and set_searched_surface_list_4_psf().
Referenced by t_isosurface::isosurf_initialize(), and t_cross_section::sectioning_initialize().
set_searched_edge_list_4_psf()
subroutine, private search_ele_list_for_psf::set_searched_edge_list_4_psf (integer(kind = kint), intent(in) num_psf, type(surface_data), intent(in) surf, type(edge_data), intent(in) edge, type(psf_search_lists), dimension(num_psf), intent(inout) psf_search) private
Definition at line 151 of file search_ele_list_for_psf.f90.
References t_psf_geometry_list::alloc_num_psf_search_list(), t_psf_geometry_list::alloc_psf_search_list(), set_edge_list_for_psf::allocate_work_4_mark_edge_psf(), set_edge_list_for_psf::count_edge_list_4_psf(), set_edge_list_for_psf::deallocate_work_4_mark_edge_psf(), set_edge_list_for_psf::mark_edge_list_4_psf(), m_machine_parameter::np_smp, and set_edge_list_for_psf::set_edge_list_4_psf().
Referenced by set_search_mesh_list_4_psf().
set_searched_element_list_4_psf()
subroutine, private search_ele_list_for_psf::set_searched_element_list_4_psf (integer(kind = kint), intent(in) num_psf, type(element_data), intent(in) ele, type(group_data), intent(in) ele_grp, type(psf_parameters), dimension(num_psf), intent(in) psf_param, type(psf_search_lists), dimension(num_psf), intent(inout) psf_search) private
Definition at line 74 of file search_ele_list_for_psf.f90.
References t_psf_geometry_list::alloc_num_psf_search_list(), t_psf_geometry_list::alloc_psf_search_list(), set_element_list_for_psf::allocate_work_4_mark_psf(), set_element_list_for_psf::count_element_list_4_psf(), set_element_list_for_psf::deallocate_work_4_mark_psf(), set_element_list_for_psf::mark_element_list_4_psf(), m_machine_parameter::np_smp, and set_element_list_for_psf::set_element_list_4_psf().
Referenced by set_search_mesh_list_4_psf().
set_searched_node_list_4_psf()
subroutine, private search_ele_list_for_psf::set_searched_node_list_4_psf (integer(kind = kint), intent(in) num_psf, type(node_data), intent(in) node, type(edge_data), intent(in) edge, type(psf_search_lists), dimension(num_psf), intent(inout) psf_search) private
Definition at line 188 of file search_ele_list_for_psf.f90.
References t_psf_geometry_list::alloc_num_psf_search_list(), t_psf_geometry_list::alloc_psf_search_list(), set_node_list_for_psf::allocate_work_4_mark_node_psf(), set_node_list_for_psf::count_node_list_4_psf(), set_node_list_for_psf::deallocate_work_4_mark_node_psf(), set_node_list_for_psf::mark_node_list_4_psf(), m_machine_parameter::np_smp, and set_node_list_for_psf::set_node_list_4_psf().
Referenced by set_search_mesh_list_4_psf().
set_searched_surface_list_4_psf()
subroutine, private search_ele_list_for_psf::set_searched_surface_list_4_psf (integer(kind = kint), intent(in) num_psf, type(element_data), intent(in) ele, type(surface_data), intent(in) surf, type(psf_search_lists), dimension(num_psf), intent(inout) psf_search) private
Definition at line 114 of file search_ele_list_for_psf.f90.
References t_psf_geometry_list::alloc_num_psf_search_list(), t_psf_geometry_list::alloc_psf_search_list(), set_surface_list_for_psf::allocate_work_4_mark_surf_psf(), set_surface_list_for_psf::count_surf_list_4_psf(), set_surface_list_for_psf::deallocate_work_4_mark_surf_psf(), set_surface_list_for_psf::mark_surface_list_4_psf(), m_machine_parameter::np_smp, and set_surface_list_for_psf::set_surface_list_4_psf().
Referenced by set_search_mesh_list_4_psf().