CALYPSO: t_multi_flag_labels Module Reference
t_multi_flag_labels Module Reference
Structure for mutilple flag lists.
Data Types
type multi_flag_labels
Structure of multiple label lists.
Functions/Subroutines
subroutine init_multi_flags_by_labels (num, names, mul_flags)
subroutine init_from_two_kinds_flags (in_flags1, in_flags2, out_flags, icou)
subroutine append_multi_flag_labels (add_flags, mul_flags)
subroutine alloc_multi_flags (mul_flags)
subroutine dealloc_multi_flags (mul_flags)
subroutine copy_multi_flag_labels (num, in_flags, out_flags)
subroutine connect_two_mul_flags (in_flags1, in_flags2, out_flags, icou)
logical function check_mul_flags (input_flag, mul_flags)
subroutine write_multi_flags (id_file, title, mul_flags)
integer(kind=kint) function num_multi_flags (mul_flags)
subroutine set_multi_flags (mul_flags, flags)
Detailed Description
Structure for mutilple flag lists.
      subroutine init_multi_flags_by_labels(num, names, mul_flags)
        type(multi_flag_labels), intent(inout) :: mul_flags
      subroutine init_from_two_kinds_flags                            &
     &         (in_flags1, in_flags2, out_flags, icou)
        type(multi_flag_labels), intent(in) :: in_flags1
        type(multi_flag_labels), intent(in) :: in_flags2
        type(multi_flag_labels), intent(inout) :: out_flags
      subroutine append_multi_flag_labels(add_flags, mul_flags)
        type(multi_flag_labels), intent(in) :: add_flags
        type(multi_flag_labels), intent(inout) :: mul_flags
      subroutine alloc_multi_flags(mul_flags)
      subroutine dealloc_multi_flags(mul_flags)
        type(multi_flag_labels), intent(inout) :: mul_flags
      subroutine copy_multi_flag_labels(num, in_flags, out_flags)
        type(multi_flag_labels), intent(in) :: in_flags
        type(multi_flag_labels), intent(inout) :: out_flags
      subroutine connect_two_mul_flags                                &
     &         (in_flags1, in_flags2, out_flags, icou)
        type(multi_flag_labels), intent(in) :: in_flags1
        type(multi_flag_labels), intent(in) :: in_flags2
        type(multi_flag_labels), intent(inout) :: out_flags
      logical function check_mul_flags(input_flag, mul_flags)
        type(multi_flag_labels), intent(in) :: mul_flags
      integer(kind = kint) function num_multi_flags(mul_flags)
      subroutine set_multi_flags(mul_flags, flags)
      subroutine write_multi_flags(id_file, title, mul_flags)
        type(multi_flag_labels), intent(in) :: mul_flags
Function/Subroutine Documentation
alloc_multi_flags()
subroutine t_multi_flag_labels::alloc_multi_flags (type(multi_flag_labels), intent(inout) mul_flags)
Definition at line 133 of file t_multi_flag_labels.f90.
Referenced by append_multi_flag_labels(), init_from_two_kinds_flags(), and init_multi_flags_by_labels().
append_multi_flag_labels()
subroutine t_multi_flag_labels::append_multi_flag_labels (type(multi_flag_labels), intent(in) add_flags, type(multi_flag_labels), intent(inout) mul_flags)
Definition at line 103 of file t_multi_flag_labels.f90.
References alloc_multi_flags(), copy_multi_flag_labels(), and dealloc_multi_flags().
Referenced by m_field_file_format_labels::init_field_type_flags(), m_file_format_labels::init_file_format_flags(), and m_merged_field_fmt_labels::init_mgd_field_type_flags().
check_mul_flags()
logical function t_multi_flag_labels::check_mul_flags (character(len=kchara), intent(in) input_flag, type(multi_flag_labels), intent(in) mul_flags)
Definition at line 192 of file t_multi_flag_labels.f90.
References skip_comment_f::cmp_no_case().
Referenced by m_field_file_format::choose_para_fld_file_format(), m_field_file_format::choose_ucd_file_format(), m_file_format_labels::cvt_default_field_format_flag(), set_components_flags::s_set_components_flags(), t_control_params_4_iso::sel_iso_file_format(), t_control_params_4_psf::sel_psf_file_format(), m_section_coef_flags::set_each_coef_4_psf(), m_file_format_switch::set_file_format(), m_file_format_switch::set_parallel_file_format(), m_more_component_flags::set_primary_componnet_flag(), and m_section_coef_flags::set_primary_section_coef_flag().
connect_two_mul_flags()
subroutine t_multi_flag_labels::connect_two_mul_flags (type(multi_flag_labels), intent(in) in_flags1, type(multi_flag_labels), intent(in) in_flags2, type(multi_flag_labels), intent(inout) out_flags, integer(kind = kint), intent(inout) icou)
Definition at line 169 of file t_multi_flag_labels.f90.
Referenced by init_from_two_kinds_flags().
copy_multi_flag_labels()
subroutine t_multi_flag_labels::copy_multi_flag_labels (integer(kind = kint), intent(in) num, type(multi_flag_labels), intent(in) in_flags, type(multi_flag_labels), intent(inout) out_flags)
Definition at line 156 of file t_multi_flag_labels.f90.
Referenced by append_multi_flag_labels().
dealloc_multi_flags()
subroutine t_multi_flag_labels::dealloc_multi_flags (type(multi_flag_labels), intent(inout) mul_flags)
Definition at line 145 of file t_multi_flag_labels.f90.
Referenced by append_multi_flag_labels(), m_field_file_format_labels::dealloc_field_type_flags(), m_file_format_labels::dealloc_file_format_flags(), m_merged_field_fmt_labels::dealloc_mgd_field_type_flags(), m_more_component_flags::dealloc_more_componnet_flags(), and m_section_coef_flags::dealloc_section_coef_flags().
init_from_two_kinds_flags()
subroutine t_multi_flag_labels::init_from_two_kinds_flags (type(multi_flag_labels), intent(in) in_flags1, type(multi_flag_labels), intent(in) in_flags2, type(multi_flag_labels), intent(inout) out_flags, integer(kind = kint), intent(inout) icou)
Definition at line 83 of file t_multi_flag_labels.f90.
References alloc_multi_flags(), and connect_two_mul_flags().
Referenced by m_field_file_format_labels::init_field_type_flags(), m_file_format_labels::init_file_format_flags(), and m_merged_field_fmt_labels::init_mgd_field_type_flags().
init_multi_flags_by_labels()
subroutine t_multi_flag_labels::init_multi_flags_by_labels (integer(kind = kint), intent(in) num, character(len = kchara), dimension(num), intent(in) names, type(multi_flag_labels), intent(inout) mul_flags)
Definition at line 64 of file t_multi_flag_labels.f90.
References alloc_multi_flags().
Referenced by m_field_file_format_labels::init_field_type_flags(), m_file_format_labels::init_file_format_flags(), m_merged_field_fmt_labels::init_mgd_field_type_flags(), m_more_component_flags::init_more_componnet_flags(), and m_section_coef_flags::init_section_coef_flags().
num_multi_flags()
integer(kind = kint) function t_multi_flag_labels::num_multi_flags (type(multi_flag_labels), intent(in) mul_flags)
Definition at line 234 of file t_multi_flag_labels.f90.
set_multi_flags()
subroutine t_multi_flag_labels::set_multi_flags (type(multi_flag_labels), intent(in) mul_flags, character(len = kchara), dimension(mul_flags%n_flag), intent(inout) flags)
Definition at line 244 of file t_multi_flag_labels.f90.
write_multi_flags()
subroutine t_multi_flag_labels::write_multi_flags (integer(kind= kint), intent(in) id_file, character(len=kchara), intent(in) title, type(multi_flag_labels), intent(in) mul_flags)
Definition at line 212 of file t_multi_flag_labels.f90.