CALYPSO: delete_data_files Module Reference
delete_data_files Module Reference
Delete data files use close command.
Functions/Subroutines
subroutine delete_file_if_exist (file_name)
subroutine delete_file_by_f (file_name)
subroutine delete_parallel_files (iflag_fmt, nprocs, file_head)
logical function check_file_exist (file_name)
Detailed Description
Delete data files use close command.
      subroutine delete_file_if_exist(file_name)
      subroutine delete_file_by_f(file_name)
      subroutine delete_parallel_files(iflag_fmt, nprocs, file_head)
      logical function check_file_exist(file_name)
Parameters
file_name file name
file_head file header to delete
iflag_fmt file format flag
nprocs number of subdomains
Function/Subroutine Documentation
check_file_exist()
logical function delete_data_files::check_file_exist (character(len=kchara), intent(in) file_name)
Definition at line 93 of file delete_data_files.F90.
Referenced by mesh_file_name_by_param::check_exist_edge_mesh(), mesh_file_name_by_param::check_exist_ele_mesh(), mesh_file_name_by_param::check_exist_mesh(), mesh_file_name_by_param::check_exist_surf_mesh(), sph_file_io_select::check_exsist_rj_file(), sph_file_io_select::check_exsist_rlm_file(), sph_file_io_select::check_exsist_rtm_file(), sph_file_io_select::check_exsist_rtp_file(), rayleigh_restart_io::check_raylegh_rst_field(), and field_io_select::check_step_fem_field_file().
delete_file_by_f()
subroutine delete_data_files::delete_file_by_f (character(len=kchara), intent(in) file_name)
Definition at line 51 of file delete_data_files.F90.
Referenced by analyzer_test_sph::analyze_test_sph(), set_field_file_names::delete_fem_fld_file(), set_ucd_file_names::delete_para_ucd_file(), delete_parallel_files(), and set_field_file_names::delete_sph_fld_file().
delete_file_if_exist()
subroutine delete_data_files::delete_file_if_exist (character(len=kchara), intent(in) file_name)
Definition at line 36 of file delete_data_files.F90.
delete_parallel_files()
subroutine delete_data_files::delete_parallel_files (integer(kind=kint), intent(in) iflag_fmt, integer(kind=kint), intent(in) nprocs, character(len=kchara), intent(in) file_head)
Definition at line 64 of file delete_data_files.F90.
References set_parallel_file_name::add_gzip_extension(), set_parallel_file_name::add_process_id(), delete_file_by_f(), and m_file_format_switch::id_gzip_txt_file_fmt.