CALYPSO: legendre_fwd_trans_testloop Module Reference
legendre_fwd_trans_testloop Module Reference
forward Legendre transform (Blocked loop version)
Functions/Subroutines
subroutine legendre_f_trans_vector_test (iflag_matmul, ncomp, nvector, nscalar, sph_rtm, sph_rlm, comm_rtm, comm_rlm, idx_trns, leg, n_WR, n_WS, WR, WS, WK_l_tst)
subroutine, private leg_fwd_trans_8latitude (lt2, jst, mm, mp_rlm, mn_rlm, nkrs, nkrt, iflag_matmul, ncomp, nvector, nscalar, sph_rtm, sph_rlm, comm_rtm, leg, n_WR, WR, n_jk_e, n_jk_o, lst_rtm, Fmat, Ptj_mat, Smat, wk_plm)
subroutine, private leg_fwd_trans_4latitude (lt2, jst, mm, mp_rlm, mn_rlm, nkrs, nkrt, iflag_matmul, ncomp, nvector, nscalar, sph_rtm, sph_rlm, comm_rtm, leg, n_WR, WR, n_jk_e, n_jk_o, lst_rtm, Fmat, Ptj_mat, Smat, wk_plm)
subroutine, private leg_fwd_trans_2latitude (lt2, jst, mm, mp_rlm, mn_rlm, nkrs, nkrt, iflag_matmul, ncomp, nvector, nscalar, sph_rtm, sph_rlm, comm_rtm, leg, n_WR, WR, n_jk_e, n_jk_o, lst_rtm, Fmat, Ptj_mat, Smat, wk_plm)
subroutine, private leg_fwd_trans_1latitude (lp_rtm, ln_rtm, jst, mm, mp_rlm, mn_rlm, nkrs, nkrt, iflag_matmul, ncomp, nvector, nscalar, sph_rtm, sph_rlm, comm_rtm, leg, n_WR, WR, n_jk_e, n_jk_o, Fmat, Pjt_mat, Smat, wk_plm)
subroutine, private leg_fwd_trans_at_equator (lp_rtm, jst, mm, mp_rlm, mn_rlm, nkrs, nkrt, iflag_matmul, ncomp, nvector, nscalar, sph_rtm, sph_rlm, comm_rtm, leg, n_WR, WR, n_jk_e, n_jk_o, Fmat, Pjt_mat, Smat, wk_plm)
Variables
integer, external omp_get_max_threads
Detailed Description
forward Legendre transform (Blocked loop version)
      subroutine legendre_f_trans_vector_test(ncomp, nvector, nscalar,&
     &          sph_rtm, sph_rlm, comm_rtm, comm_rlm, idx_trns,       &
     &          asin_theta_1d_rtm, g_sph_rlm, weight_rtm,             &
     &          n_WR, n_WS, WR, WS, WK_l_tst)
        Input:  vr_rtm   (Order: radius,theta,phi)
        Output: sp_rlm   (Order: poloidal,diff_poloidal,toroidal)
        type(sph_rlm_grid), intent(in) :: sph_rlm
        type(sph_rtm_grid), intent(in) :: sph_rtm
        type(sph_comm_tbl), intent(in) :: comm_rlm, comm_rtm
        type(index_4_sph_trans), intent(in) :: idx_trns
        type(leg_trns_testloop_work), intent(inout) :: WK_l_tst
Parameters
ncomp Total number of components for spherical transform
nvector Number of vector for spherical transform
nscalar Number of scalar (including tensor components) for spherical transform
Function/Subroutine Documentation
leg_fwd_trans_1latitude()
subroutine, private legendre_fwd_trans_testloop::leg_fwd_trans_1latitude (integer(kind = kint), intent(in) lp_rtm, integer(kind = kint), intent(in) ln_rtm, integer(kind = kint), intent(in) jst, integer(kind = kint), intent(in) mm, integer(kind = kint), intent(in) mp_rlm, integer(kind = kint), intent(in) mn_rlm, integer(kind = kint), intent(in) nkrs, integer(kind = kint), intent(in) nkrt, integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_comm_tbl), intent(in) comm_rtm, type(legendre_4_sph_trans), intent(in) leg, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(inout) WR, integer(kind = kint), intent(in) n_jk_e, integer(kind = kint), intent(in) n_jk_o, type(field_matrix_omp), intent(inout) Fmat, type(leg_jt_omp_matrix), intent(inout) Pjt_mat, type(spectr_matrix_omp), intent(inout) Smat, type(work_make_legendre), intent(inout) wk_plm) private
Definition at line 494 of file legendre_fwd_trans_testloop.f90.
References small_matmul_leg_trans_krin::matvec_fwd_leg_trans_pj(), t_set_legendre_4_sph_trans::set_each_sym_leg_omp_mat_j1(), and set_vr_rtm_sym_mat_tsmp::set_vr_rtm_lt_sym_mat_rin().
Referenced by legendre_f_trans_vector_test().
leg_fwd_trans_2latitude()
subroutine, private legendre_fwd_trans_testloop::leg_fwd_trans_2latitude (integer(kind = kint), intent(in) lt2, integer(kind = kint), intent(in) jst, integer(kind = kint), intent(in) mm, integer(kind = kint), intent(in) mp_rlm, integer(kind = kint), intent(in) mn_rlm, integer(kind = kint), intent(in) nkrs, integer(kind = kint), intent(in) nkrt, integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_comm_tbl), intent(in) comm_rtm, type(legendre_4_sph_trans), intent(in) leg, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(inout) WR, integer(kind = kint), intent(in) n_jk_e, integer(kind = kint), intent(in) n_jk_o, integer(kind = kint), intent(in) lst_rtm, type(field_matrix_omp), intent(inout) Fmat, type(leg_tj_omp_matrix), intent(inout) Ptj_mat, type(spectr_matrix_omp), intent(inout) Smat, type(work_make_legendre), intent(inout) wk_plm) private
Definition at line 410 of file legendre_fwd_trans_testloop.f90.
References small_matmul_leg_trans_krin::matmul2_fwd_leg_trans_ptj(), t_legendre_work_testlooop::n_sse2, t_set_legendre_4_sph_trans::set_each_sym_leg_omp_mat_tj(), and set_vr_rtm_sym_mat_tsmp::set_vr_rtm_lt_sym_mat_rin().
Referenced by legendre_f_trans_vector_test().
leg_fwd_trans_4latitude()
subroutine, private legendre_fwd_trans_testloop::leg_fwd_trans_4latitude (integer(kind = kint), intent(in) lt2, integer(kind = kint), intent(in) jst, integer(kind = kint), intent(in) mm, integer(kind = kint), intent(in) mp_rlm, integer(kind = kint), intent(in) mn_rlm, integer(kind = kint), intent(in) nkrs, integer(kind = kint), intent(in) nkrt, integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_comm_tbl), intent(in) comm_rtm, type(legendre_4_sph_trans), intent(in) leg, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(inout) WR, integer(kind = kint), intent(in) n_jk_e, integer(kind = kint), intent(in) n_jk_o, integer(kind = kint), intent(in) lst_rtm, type(field_matrix_omp), intent(inout) Fmat, type(leg_tj_omp_matrix), intent(inout) Ptj_mat, type(spectr_matrix_omp), intent(inout) Smat, type(work_make_legendre), intent(inout) wk_plm) private
Definition at line 326 of file legendre_fwd_trans_testloop.f90.
References small_matmul_leg_trans_krin::matmul4_fwd_leg_trans_ptj(), t_legendre_work_testlooop::n_avx, t_set_legendre_4_sph_trans::set_each_sym_leg_omp_mat_tj(), and set_vr_rtm_sym_mat_tsmp::set_vr_rtm_lt_sym_mat_rin().
Referenced by legendre_f_trans_vector_test().
leg_fwd_trans_8latitude()
subroutine, private legendre_fwd_trans_testloop::leg_fwd_trans_8latitude (integer(kind = kint), intent(in) lt2, integer(kind = kint), intent(in) jst, integer(kind = kint), intent(in) mm, integer(kind = kint), intent(in) mp_rlm, integer(kind = kint), intent(in) mn_rlm, integer(kind = kint), intent(in) nkrs, integer(kind = kint), intent(in) nkrt, integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_comm_tbl), intent(in) comm_rtm, type(legendre_4_sph_trans), intent(in) leg, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(inout) WR, integer(kind = kint), intent(in) n_jk_e, integer(kind = kint), intent(in) n_jk_o, integer(kind = kint), intent(in) lst_rtm, type(field_matrix_omp), intent(inout) Fmat, type(leg_tj_omp_matrix), intent(inout) Ptj_mat, type(spectr_matrix_omp), intent(inout) Smat, type(work_make_legendre), intent(inout) wk_plm) private
Definition at line 242 of file legendre_fwd_trans_testloop.f90.
References small_matmul_leg_trans_krin::matmul8_fwd_leg_trans_ptj(), t_legendre_work_testlooop::n_avx512, t_set_legendre_4_sph_trans::set_each_sym_leg_omp_mat_tj(), and set_vr_rtm_sym_mat_tsmp::set_vr_rtm_lt_sym_mat_rin().
Referenced by legendre_f_trans_vector_test().
leg_fwd_trans_at_equator()
subroutine, private legendre_fwd_trans_testloop::leg_fwd_trans_at_equator (integer(kind = kint), intent(in) lp_rtm, integer(kind = kint), intent(in) jst, integer(kind = kint), intent(in) mm, integer(kind = kint), intent(in) mp_rlm, integer(kind = kint), intent(in) mn_rlm, integer(kind = kint), intent(in) nkrs, integer(kind = kint), intent(in) nkrt, integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_comm_tbl), intent(in) comm_rtm, type(legendre_4_sph_trans), intent(in) leg, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(inout) WR, integer(kind = kint), intent(in) n_jk_e, integer(kind = kint), intent(in) n_jk_o, type(field_matrix_omp), intent(inout) Fmat, type(leg_jt_omp_matrix), intent(inout) Pjt_mat, type(spectr_matrix_omp), intent(inout) Smat, type(work_make_legendre), intent(inout) wk_plm) private
Definition at line 568 of file legendre_fwd_trans_testloop.f90.
References small_matmul_leg_trans_krin::matvec_fwd_leg_trans_pj(), t_set_legendre_4_sph_trans::set_each_sym_leg_omp_mat_j1(), and set_vr_rtm_sym_mat_tsmp::set_vr_rtm_eq_sym_mat_rin().
Referenced by legendre_f_trans_vector_test().
legendre_f_trans_vector_test()
subroutine legendre_fwd_trans_testloop::legendre_f_trans_vector_test (integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_comm_tbl), intent(in) comm_rtm, type(sph_comm_tbl), intent(in) comm_rlm, type(index_4_sph_trans), intent(in) idx_trns, type(legendre_4_sph_trans), intent(in) leg, integer(kind = kint), intent(in) n_WR, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_wr), intent(inout) WR, real (kind=kreal), dimension(n_ws), intent(inout) WS, type(leg_trns_testloop_work), intent(inout) WK_l_tst)
Definition at line 63 of file legendre_fwd_trans_testloop.f90.
References cal_sp_rlm_sym_mat_tsmp::cal_sp_rlm_sym_mat_rin(), m_work_time::elps1, m_work_time::end_elapsed_time(), m_elapsed_labels_sph_trns::iflag_sdt_time, m_elapsed_labels_sph_trns::ist_elapsed_sdt, leg_fwd_trans_1latitude(), leg_fwd_trans_2latitude(), leg_fwd_trans_4latitude(), leg_fwd_trans_8latitude(), leg_fwd_trans_at_equator(), m_machine_parameter::np_smp, and m_work_time::start_elapsed_time().
Referenced by legendre_transform_testloop::leg_forward_trans_test().
Variable Documentation
omp_get_max_threads
integer, external legendre_fwd_trans_testloop::omp_get_max_threads
Definition at line 51 of file legendre_fwd_trans_testloop.f90.