CALYPSO: /home/takumi kera/calypso/src/C_libraries/BASE/calypso_zlib_io_c.c File Reference
calypso_zlib_io_c.c File Reference
#include <string.h>
#include "calypso_zlib_io_c.h"
Macros
#define CALL_ZLIB(x)
Functions
void open_wt_rawfile (const char *file_name, int *ierr)
void open_ad_rawfile (const char *file_name, int *ierr)
void open_rd_rawfile (const char *file_name, int *ierr)
void close_rawfile (void)
void rawseek_go_fwd (int *ioffset, int *ierr)
void rawread_32bit (int *iflag_swap, int *ilength, void *buf, int *lenchara)
void rawread_64bit (int *iflag_swap, int *ilength, void *buf, int *lenchara)
void rawwrite (int *ilength, void *buf, int *lenchara)
void open_wt_gzfile (const char *gz_file_name)
void open_ad_gzfile (const char *gz_file_name)
void open_rd_gzfile (const char *gz_file_name)
void close_gzfile (void)
int open_rd_gzfile_w_flag (const char *gz_file_name)
int check_gzfile_eof (void)
void write_compress_txt (int *nchara, char *input_txt)
void write_compress_txt_nolf (int *nchara, char *input_txt)
static void strm_deflate_init (z_stream *strm)
static void strm_inflate_init (z_stream *strm)
void gzip_defleat_once (const int *len_buf, const void *buf, const int *len_gzipbuf, int *len_gzipped, char *gzipbuf)
void gzip_defleat_begin (const int *len_buf, const void *buf, const int *len_gzipbuf, int *len_gzipped, char *gzipbuf)
void gzip_defleat_cont (const int *len_buf, const void *buf, const int *len_gzipbuf, int *len_gzipped)
void gzip_defleat_last (const int *len_buf, const void *buf, const int *len_gzipbuf, int *len_gzipped)
void gzip_infleat_once (const int *len_gzipbuf, const char *gzipbuf, const int *len_buf, void *buf, int *len_gzipped)
void gzip_infleat_begin (const int *len_gzipbuf, const char *gzipbuf, const int *len_buf, void *buf, int *len_gzipped)
void gzip_infleat_cont (const int *len_gzipbuf, const int *len_buf, void *buf, int *len_gzipped)
void gzip_infleat_last (const int *len_gzipbuf, const int *len_buf, void *buf, int *len_gzipped)
static int count_linechara (int num_buffer, const char *line_buf)
static int count_words (int nchara_l, const char *line_buf)
static void get_one_line_by_zlib (int *num_buffer, int *num_word, int *nchara, char *line_buf)
void gzseek_go_fwd_f (int *ioffset, int *ierr)
void gzread_32bit_f (const int *iflag_swap, int *ilength, char *textbuf, int *ierr)
void gzread_64bit_f (const int *iflag_swap, int *ilength, char *textbuf, int *ierr)
void gzwrite_f (int *ilength, void *buf, int *ierr)
void get_one_line_from_gz (int *num_buffer, int *num_word, int *nchara, char *line_buf)
int skip_comment_gz_c (int *num_buffer, char *buf)
void compress_file (const char *txt_file_name, const char *gz_file_name)
void decompress_file (const char *gz_file_name, const char *txt_file_name)
Variables
FILE * fp_z
gzFile file_gz
z_stream strm_gl
Macro Definition Documentation
CALL_ZLIB
#define CALL_ZLIB (x)
Value:
{                                                  \
int status;                                                     \
status = x;                                                     \
if (status < 0) {                                               \
fprintf (stderr,                                            \
"%s:%d: %s returned a bad status of %d.\n",        \
__FILE__, __LINE__, #x, status);                   \
exit (EXIT_FAILURE);                                        \
}                                                               \
}
Definition at line 19 of file calypso_zlib_io_c.c.
Function Documentation
check_gzfile_eof()
int check_gzfile_eof (void)
Definition at line 157 of file calypso_zlib_io_c.c.
References file_gz.
close_gzfile()
void close_gzfile (void)
Definition at line 137 of file calypso_zlib_io_c.c.
References file_gz.
close_rawfile()
void close_rawfile (void)
Definition at line 58 of file calypso_zlib_io_c.c.
References fp_z.
compress_file()
void compress_file (const char * txt_file_name, const char * gz_file_name)
Definition at line 450 of file calypso_zlib_io_c.c.
References INBUFSIZ, OUTBUFSIZ, and Z_DEFAULT_MEMLEVEL.
count_linechara()
static int count_linechara (int num_buffer, const char * line_buf) static
Definition at line 340 of file calypso_zlib_io_c.c.
Referenced by get_one_line_by_zlib().
count_words()
static int count_words (int nchara_l, const char * line_buf) static
Definition at line 370 of file calypso_zlib_io_c.c.
Referenced by get_one_line_by_zlib().
decompress_file()
void decompress_file (const char * gz_file_name, const char * txt_file_name)
Definition at line 550 of file calypso_zlib_io_c.c.
References INBUFSIZ, and OUTBUFSIZ.
get_one_line_by_zlib()
static void get_one_line_by_zlib (int * num_buffer, int * num_word, int * nchara, char * line_buf) static
Definition at line 385 of file calypso_zlib_io_c.c.
References count_linechara(), count_words(), and file_gz.
Referenced by get_one_line_from_gz().
get_one_line_from_gz()
void get_one_line_from_gz (int * num_buffer, int * num_word, int * nchara, char * line_buf)
Definition at line 430 of file calypso_zlib_io_c.c.
References get_one_line_by_zlib().
Referenced by skip_comment_gz_c().
gzip_defleat_begin()
void gzip_defleat_begin (const int * len_buf, const void * buf, const int * len_gzipbuf, int * len_gzipped, char * gzipbuf)
Definition at line 234 of file calypso_zlib_io_c.c.
References CALL_ZLIB, strm_deflate_init(), and strm_gl.
gzip_defleat_cont()
void gzip_defleat_cont (const int * len_buf, const void * buf, const int * len_gzipbuf, int * len_gzipped)
Definition at line 248 of file calypso_zlib_io_c.c.
References CALL_ZLIB, and strm_gl.
gzip_defleat_last()
void gzip_defleat_last (const int * len_buf, const void * buf, const int * len_gzipbuf, int * len_gzipped)
Definition at line 262 of file calypso_zlib_io_c.c.
References CALL_ZLIB, and strm_gl.
gzip_defleat_once()
void gzip_defleat_once (const int * len_buf, const void * buf, const int * len_gzipbuf, int * len_gzipped, char * gzipbuf)
Definition at line 217 of file calypso_zlib_io_c.c.
References CALL_ZLIB, and strm_deflate_init().
gzip_infleat_begin()
void gzip_infleat_begin (const int * len_gzipbuf, const char * gzipbuf, const int * len_buf, void * buf, int * len_gzipped)
Definition at line 295 of file calypso_zlib_io_c.c.
References CALL_ZLIB, strm_gl, and strm_inflate_init().
gzip_infleat_cont()
void gzip_infleat_cont (const int * len_gzipbuf, const int * len_buf, void * buf, int * len_gzipped)
Definition at line 309 of file calypso_zlib_io_c.c.
References CALL_ZLIB, and strm_gl.
gzip_infleat_last()
void gzip_infleat_last (const int * len_gzipbuf, const int * len_buf, void * buf, int * len_gzipped)
Definition at line 324 of file calypso_zlib_io_c.c.
References CALL_ZLIB, and strm_gl.
gzip_infleat_once()
void gzip_infleat_once (const int * len_gzipbuf, const char * gzipbuf, const int * len_buf, void * buf, int * len_gzipped)
Definition at line 278 of file calypso_zlib_io_c.c.
References CALL_ZLIB, and strm_inflate_init().
gzread_32bit_f()
void gzread_32bit_f (const int * iflag_swap, int * ilength, char * textbuf, int * ierr)
Definition at line 410 of file calypso_zlib_io_c.c.
References byte_swap_4(), file_gz, and IFLAG_SWAP.
gzread_64bit_f()
void gzread_64bit_f (const int * iflag_swap, int * ilength, char * textbuf, int * ierr)
Definition at line 417 of file calypso_zlib_io_c.c.
References byte_swap_8(), file_gz, and IFLAG_SWAP.
gzseek_go_fwd_f()
void gzseek_go_fwd_f (int * ioffset, int * ierr)
Definition at line 404 of file calypso_zlib_io_c.c.
References file_gz.
gzwrite_f()
void gzwrite_f (int * ilength, void * buf, int * ierr)
Definition at line 424 of file calypso_zlib_io_c.c.
References file_gz.
open_ad_gzfile()
void open_ad_gzfile (const char * gz_file_name)
Definition at line 120 of file calypso_zlib_io_c.c.
References file_gz, and GZ_AD_MODE.
open_ad_rawfile()
void open_ad_rawfile (const char * file_name, int * ierr)
Definition at line 40 of file calypso_zlib_io_c.c.
References element_mesh_mpi_io_select::file_name, and fp_z.
open_rd_gzfile()
void open_rd_gzfile (const char * gz_file_name)
Definition at line 128 of file calypso_zlib_io_c.c.
References file_gz, and GZ_RD_MODE.
open_rd_gzfile_w_flag()
int open_rd_gzfile_w_flag (const char * gz_file_name)
Definition at line 148 of file calypso_zlib_io_c.c.
References file_gz, and GZ_RD_MODE.
open_rd_rawfile()
void open_rd_rawfile (const char * file_name, int * ierr)
Definition at line 49 of file calypso_zlib_io_c.c.
References element_mesh_mpi_io_select::file_name, and fp_z.
open_wt_gzfile()
void open_wt_gzfile (const char * gz_file_name)
Definition at line 111 of file calypso_zlib_io_c.c.
References file_gz, and GZ_WT_MODE.
open_wt_rawfile()
void open_wt_rawfile (const char * file_name, int * ierr)
Definition at line 31 of file calypso_zlib_io_c.c.
References element_mesh_mpi_io_select::file_name, and fp_z.
rawread_32bit()
void rawread_32bit (int * iflag_swap, int * ilength, void * buf, int * lenchara)
Definition at line 68 of file calypso_zlib_io_c.c.
References byte_swap_4(), fp_z, and IFLAG_SWAP.
rawread_64bit()
void rawread_64bit (int * iflag_swap, int * ilength, void * buf, int * lenchara)
Definition at line 86 of file calypso_zlib_io_c.c.
References byte_swap_8(), fp_z, and IFLAG_SWAP.
rawseek_go_fwd()
void rawseek_go_fwd (int * ioffset, int * ierr)
Definition at line 63 of file calypso_zlib_io_c.c.
References fp_z.
rawwrite()
void rawwrite (int * ilength, void * buf, int * lenchara)
Definition at line 104 of file calypso_zlib_io_c.c.
References fp_z.
skip_comment_gz_c()
int skip_comment_gz_c (int * num_buffer, char * buf)
Definition at line 438 of file calypso_zlib_io_c.c.
References get_one_line_from_gz().
strm_deflate_init()
static void strm_deflate_init (z_stream * strm) static
Definition at line 198 of file calypso_zlib_io_c.c.
References CALL_ZLIB, GZIP_ENCODING, and windowBits.
Referenced by gzip_defleat_begin(), and gzip_defleat_once().
strm_inflate_init()
static void strm_inflate_init (z_stream * strm) static
Definition at line 208 of file calypso_zlib_io_c.c.
References CALL_ZLIB, GZIP_AUTODETECT, GZIP_ENCODING, and windowBits.
Referenced by gzip_infleat_begin(), and gzip_infleat_once().
write_compress_txt()
void write_compress_txt (int * nchara, char * input_txt)
Definition at line 161 of file calypso_zlib_io_c.c.
References file_gz.
write_compress_txt_nolf()
void write_compress_txt_nolf (int * nchara, char * input_txt)
Definition at line 183 of file calypso_zlib_io_c.c.
References file_gz.
Variable Documentation
file_gz
gzFile file_gz
Definition at line 10 of file calypso_zlib_io_c.c.
Referenced by check_gzfile_eof(), close_gzfile(), get_one_line_by_zlib(), gzread_32bit_f(), gzread_64bit_f(), gzseek_go_fwd_f(), gzwrite_f(), open_ad_gzfile(), open_rd_gzfile(), open_rd_gzfile_w_flag(), open_wt_gzfile(), write_compress_txt(), and write_compress_txt_nolf().
fp_z
FILE* fp_z
Definition at line 9 of file calypso_zlib_io_c.c.
Referenced by close_rawfile(), open_ad_rawfile(), open_rd_rawfile(), open_wt_rawfile(), rawread_32bit(), rawread_64bit(), rawseek_go_fwd(), and rawwrite().
strm_gl
z_stream strm_gl
Definition at line 12 of file calypso_zlib_io_c.c.
Referenced by gzip_defleat_begin(), gzip_defleat_cont(), gzip_defleat_last(), gzip_infleat_begin(), gzip_infleat_cont(), and gzip_infleat_last().