CALYPSO: groups_io_b Module Reference
groups_io_b Module Reference
Binary output routines for group data.
Functions/Subroutines
subroutine read_group_data_b (bbuf, group_IO)
subroutine read_surf_grp_data_b (bbuf, surf_grp_IO)
subroutine write_grp_data_b (group_IO, bbuf)
subroutine write_surf_grp_data_b (surf_grp_IO, bbuf)
Detailed Description
Binary output routines for group data.
      subroutine read_group_data_b(bbuf, group_IO)
      subroutine read_surf_grp_data_b(bbuf, surf_grp_IO)
        type(binary_IO_buffer), intent(inout) :: bbuf
        type(group_data), intent(inout) :: group_IO
        type(surface_group_data), intent(inout) :: surf_grp_IO
      subroutine write_grp_data_b(group_IO, bbuf)
      subroutine write_surf_grp_data_b(surf_grp_IO, bbuf)
        type(group_data), intent(in) :: group_IO
        type(surface_group_data), intent(in) :: surf_grp_IO
        type(binary_IO_buffer), intent(inout) :: bbuf
Function/Subroutine Documentation
read_group_data_b()
subroutine groups_io_b::read_group_data_b (type(binary_io_buffer), intent(inout) bbuf, type(group_data), intent(inout) group_IO)
Definition at line 42 of file groups_IO_b.f90.
References t_group_data::alloc_group_item(), t_group_data::alloc_group_num(), transfer_to_long_integers::cast_long(), binary_io::read_integer_stack_b(), binary_io::read_mul_character_b(), binary_io::read_mul_integer_b(), and binary_io::read_one_integer_b().
Referenced by sph_modes_grids_data_io_b::read_geom_rtp_data_b(), mesh_data_io_b::read_mesh_groups_b(), and sph_modes_grids_data_io_b::read_spectr_modes_rj_data_b().
read_surf_grp_data_b()
subroutine groups_io_b::read_surf_grp_data_b (type(binary_io_buffer), intent(inout) bbuf, type(surface_group_data), intent(inout) surf_grp_IO)
Definition at line 76 of file groups_IO_b.f90.
References t_group_data::alloc_sf_group_item(), t_group_data::alloc_sf_group_num(), transfer_to_long_integers::cast_long(), binary_io::read_integer_stack_b(), binary_io::read_mul_character_b(), binary_io::read_mul_integer_b(), and binary_io::read_one_integer_b().
Referenced by mesh_data_io_b::read_mesh_groups_b().
write_grp_data_b()
subroutine groups_io_b::write_grp_data_b (type(group_data), intent(in) group_IO, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 113 of file groups_IO_b.f90.
References transfer_to_long_integers::cast_long(), binary_io::write_integer_stack_b(), binary_io::write_mul_character_b(), binary_io::write_mul_integer_b(), and binary_io::write_one_integer_b().
Referenced by sph_modes_grids_data_io_b::write_geom_rtp_data_b(), mesh_data_io_b::write_mesh_groups_b(), and sph_modes_grids_data_io_b::write_spectr_modes_rj_data_b().
write_surf_grp_data_b()
subroutine groups_io_b::write_surf_grp_data_b (type(surface_group_data), intent(in) surf_grp_IO, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 136 of file groups_IO_b.f90.
References transfer_to_long_integers::cast_long(), binary_io::write_integer_stack_b(), binary_io::write_mul_character_b(), binary_io::write_mul_integer_b(), and binary_io::write_one_integer_b().
Referenced by mesh_data_io_b::write_mesh_groups_b().