CALYPSO: mpi_sph_modes_file_io Module Reference
mpi_sph_modes_file_io Module Reference
merged ASCII spectr data IO routines
Functions/Subroutines
subroutine mpi_read_geom_rtp_file (file_name, num_pe, id_rank, sph_file)
subroutine mpi_read_spectr_rj_file (file_name, num_pe, id_rank, sph_file)
subroutine mpi_read_geom_rtm_file (file_name, num_pe, id_rank, sph_file)
subroutine mpi_read_modes_rlm_file (file_name, num_pe, id_rank, sph_file)
subroutine mpi_write_geom_rtp_file (file_name, sph_file)
subroutine mpi_write_spectr_rj_file (file_name, sph_file)
subroutine mpi_write_geom_rtm_file (file_name, sph_file)
subroutine mpi_write_modes_rlm_file (file_name, sph_file)
Variables
type(calypso_mpi_io_params), save, private io_param
Detailed Description
merged ASCII spectr data IO routines
      subroutine mpi_read_geom_rtp_file                               &
     &         (file_name, num_pe, id_rank, sph_file)
      subroutine mpi_read_spectr_rj_file                              &
     &         (file_name, num_pe, id_rank, sph_file)
      subroutine mpi_read_geom_rtm_file                               &
     &         (file_name, num_pe, id_rank, sph_file)
      subroutine mpi_read_modes_rlm_file                              &
     &         (file_name, num_pe, id_rank, sph_file)
        type(sph_file_data_type), intent(inout) :: sph_file
      subroutine mpi_write_geom_rtp_file(file_name, sph_file)
      subroutine mpi_write_spectr_rj_file(file_name, sph_file)
      subroutine mpi_write_geom_rtm_file(file_name, sph_file)
      subroutine mpi_write_modes_rlm_file(file_name, sph_file)
        type(sph_file_data_type), intent(in) :: sph_file
Parameters
id_rank Process ID
file_name file name for IO (.gz is appended in this module)
Function/Subroutine Documentation
mpi_read_geom_rtm_file()
subroutine mpi_sph_modes_file_io::mpi_read_geom_rtm_file (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, type(sph_file_data_type), intent(inout) sph_file)
Definition at line 93 of file MPI_sph_modes_file_IO.f90.
References mpi_ascii_data_io::close_mpi_file(), m_machine_parameter::i_debug, io_param, mpi_sph_modes_data_io::mpi_read_geom_rtm_data(), and mpi_ascii_data_io::open_read_mpi_file().
Referenced by sph_file_mpi_io_select::sel_mpi_read_geom_rtm_file().
mpi_read_geom_rtp_file()
subroutine mpi_sph_modes_file_io::mpi_read_geom_rtp_file (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, type(sph_file_data_type), intent(inout) sph_file)
Definition at line 49 of file MPI_sph_modes_file_IO.f90.
References mpi_ascii_data_io::close_mpi_file(), m_machine_parameter::i_debug, io_param, mpi_sph_modes_data_io::mpi_read_geom_rtp_data(), and mpi_ascii_data_io::open_read_mpi_file().
Referenced by sph_file_mpi_io_select::sel_mpi_read_geom_rtp_file().
mpi_read_modes_rlm_file()
subroutine mpi_sph_modes_file_io::mpi_read_modes_rlm_file (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, type(sph_file_data_type), intent(inout) sph_file)
Definition at line 115 of file MPI_sph_modes_file_IO.f90.
References mpi_ascii_data_io::close_mpi_file(), m_machine_parameter::i_debug, io_param, mpi_sph_modes_data_io::mpi_read_modes_rlm_data(), and mpi_ascii_data_io::open_read_mpi_file().
Referenced by sph_file_mpi_io_select::sel_mpi_read_modes_rlm_file().
mpi_read_spectr_rj_file()
subroutine mpi_sph_modes_file_io::mpi_read_spectr_rj_file (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, type(sph_file_data_type), intent(inout) sph_file)
Definition at line 71 of file MPI_sph_modes_file_IO.f90.
References mpi_ascii_data_io::close_mpi_file(), m_machine_parameter::i_debug, io_param, mpi_sph_modes_data_io::mpi_read_spectr_rj_data(), and mpi_ascii_data_io::open_read_mpi_file().
Referenced by sph_file_mpi_io_select::sel_mpi_read_spectr_rj_file().
mpi_write_geom_rtm_file()
subroutine mpi_sph_modes_file_io::mpi_write_geom_rtm_file (character(len=kchara), intent(in) file_name, type(sph_file_data_type), intent(in) sph_file)
Definition at line 174 of file MPI_sph_modes_file_IO.f90.
References mpi_ascii_data_io::close_mpi_file(), m_machine_parameter::i_debug, io_param, mpi_sph_modes_data_io::mpi_write_geom_rtm_data(), and mpi_ascii_data_io::open_write_mpi_file().
Referenced by sph_file_mpi_io_select::sel_mpi_write_geom_rtm_file().
mpi_write_geom_rtp_file()
subroutine mpi_sph_modes_file_io::mpi_write_geom_rtp_file (character(len=kchara), intent(in) file_name, type(sph_file_data_type), intent(in) sph_file)
Definition at line 138 of file MPI_sph_modes_file_IO.f90.
References mpi_ascii_data_io::close_mpi_file(), m_machine_parameter::i_debug, io_param, mpi_sph_modes_data_io::mpi_write_geom_rtp_data(), and mpi_ascii_data_io::open_write_mpi_file().
Referenced by sph_file_mpi_io_select::sel_mpi_write_geom_rtp_file().
mpi_write_modes_rlm_file()
subroutine mpi_sph_modes_file_io::mpi_write_modes_rlm_file (character(len=kchara), intent(in) file_name, type(sph_file_data_type), intent(in) sph_file)
Definition at line 192 of file MPI_sph_modes_file_IO.f90.
References mpi_ascii_data_io::close_mpi_file(), m_machine_parameter::i_debug, io_param, mpi_sph_modes_data_io::mpi_write_modes_rlm_data(), and mpi_ascii_data_io::open_write_mpi_file().
Referenced by sph_file_mpi_io_select::sel_mpi_write_modes_rlm_file().
mpi_write_spectr_rj_file()
subroutine mpi_sph_modes_file_io::mpi_write_spectr_rj_file (character(len=kchara), intent(in) file_name, type(sph_file_data_type), intent(in) sph_file)
Definition at line 156 of file MPI_sph_modes_file_IO.f90.
References mpi_ascii_data_io::close_mpi_file(), m_machine_parameter::i_debug, io_param, mpi_sph_modes_data_io::mpi_write_spectr_rj_data(), and mpi_ascii_data_io::open_write_mpi_file().
Referenced by sph_file_mpi_io_select::sel_mpi_write_spectr_rj_file().
Variable Documentation
io_param
type(calypso_mpi_io_params), save, private mpi_sph_modes_file_io::io_param private
Definition at line 41 of file MPI_sph_modes_file_IO.f90.
Referenced by mpi_read_geom_rtm_file(), mpi_read_geom_rtp_file(), mpi_read_modes_rlm_file(), mpi_read_spectr_rj_file(), mpi_write_geom_rtm_file(), mpi_write_geom_rtp_file(), mpi_write_modes_rlm_file(), and mpi_write_spectr_rj_file().