CALYPSO: set_item_4_sph_groups Module Reference
set_item_4_sph_groups Module Reference
Make group informations for spherical shell model.
Functions/Subroutines
subroutine set_item_rtp_radial_grp (sph_params, sph_rtp, r_layer_grp, added_radial_grp, radial_rtp_grp)
subroutine set_item_rj_radial_grp (sph_params, sph_rj, added_radial_grp, radial_rj_grp)
subroutine set_item_rtp_meridional_grp (sph_rtp, med_layer_grp, theta_rtp_grp)
subroutine set_item_rj_spectr_grp (sph_rj, sphere_rj_grp)
subroutine, private set_item_sph_grp_by_list (icou, nlayer_st, nlayer_ed, nidx, idx_gl_1d, ntot_grp, item_grp)
subroutine, private set_item_sph_grp_direct (icou, nlayer_st, nlayer_ed, ist_domain, ied_domain, ntot_grp, item_grp)
Detailed Description
Make group informations for spherical shell model.
      subroutine set_item_rtp_radial_grp(sph_params, sph_rtp,         &
     &          r_layer_grp, added_radial_grp, radial_rtp_grp)
      subroutine set_item_rj_radial_grp                               &
     &         (sph_params, sph_rj, added_radial_grp, radial_rj_grp)
      subroutine set_item_rtp_meridional_grp                          &
     &         (sph_rtp, med_layer_grp, theta_rtp_grp)
      subroutine set_item_rj_spectr_grp(sph_rj, sphere_rj_grp)
        type(sph_shell_parameters) :: sph_params
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(layering_group_list), intent(in) :: r_layer_grp
        type(layering_group_list), intent(in) :: added_radial_grp
        type(layering_group_list), intent(in) :: med_layer_grp
        type(group_data), intent(inout) :: radial_rtp_grp
        type(group_data), intent(inout) :: theta_rtp_grp
        type(sph_rj_grid), intent(in) :: sph_rj
        type(group_data), intent(inout) :: radial_rj_grp
        type(group_data), intent(inout) :: sphere_rj_grp
Function/Subroutine Documentation
set_item_rj_radial_grp()
subroutine set_item_4_sph_groups::set_item_rj_radial_grp (type(sph_shell_parameters) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(layering_group_list), intent(in) added_radial_grp, type(group_data), intent(inout) radial_rj_grp)
Definition at line 125 of file set_item_4_sph_groups.f90.
References set_item_sph_grp_direct().
Referenced by set_sph_groups::set_rj_radial_grp().
set_item_rj_spectr_grp()
subroutine set_item_4_sph_groups::set_item_rj_spectr_grp (type(sph_rj_grid), intent(in) sph_rj, type(group_data), intent(inout) sphere_rj_grp)
Definition at line 210 of file set_item_4_sph_groups.f90.
References m_constants::ione, m_constants::ithree, m_constants::itwo, m_constants::izero, and set_item_sph_grp_direct().
Referenced by set_sph_groups::set_rj_spectr_grp().
set_item_rtp_meridional_grp()
subroutine set_item_4_sph_groups::set_item_rtp_meridional_grp (type(sph_rtp_grid), intent(in) sph_rtp, type(layering_group_list), intent(in) med_layer_grp, type(group_data), intent(inout) theta_rtp_grp)
Definition at line 188 of file set_item_4_sph_groups.f90.
References set_item_sph_grp_direct().
Referenced by set_sph_groups::set_rtp_meridional_grp().
set_item_rtp_radial_grp()
subroutine set_item_4_sph_groups::set_item_rtp_radial_grp (type(sph_shell_parameters) sph_params, type(sph_rtp_grid), intent(in) sph_rtp, type(layering_group_list), intent(in) r_layer_grp, type(layering_group_list), intent(in) added_radial_grp, type(group_data), intent(inout) radial_rtp_grp)
Definition at line 53 of file set_item_4_sph_groups.f90.
References set_item_sph_grp_by_list().
Referenced by set_sph_groups::set_rtp_radial_grp().
set_item_sph_grp_by_list()
subroutine, private set_item_4_sph_groups::set_item_sph_grp_by_list (integer(kind = kint), intent(inout) icou, integer(kind = kint), intent(in) nlayer_st, integer(kind = kint), intent(in) nlayer_ed, integer(kind = kint), intent(in) nidx, integer(kind = kint), dimension(nidx), intent(in) idx_gl_1d, integer(kind = kint), intent(in) ntot_grp, integer(kind = kint), dimension(ntot_grp), intent(inout) item_grp) private
Definition at line 239 of file set_item_4_sph_groups.f90.
Referenced by set_item_rtp_radial_grp().
set_item_sph_grp_direct()
subroutine, private set_item_4_sph_groups::set_item_sph_grp_direct (integer(kind = kint), intent(inout) icou, integer(kind = kint), intent(in) nlayer_st, integer(kind = kint), intent(in) nlayer_ed, integer(kind = kint), intent(in) ist_domain, integer(kind = kint), intent(in) ied_domain, integer(kind = kint), intent(in) ntot_grp, integer(kind = kint), dimension(ntot_grp), intent(inout) item_grp) private
Definition at line 266 of file set_item_4_sph_groups.f90.
Referenced by set_item_rj_radial_grp(), set_item_rj_spectr_grp(), and set_item_rtp_meridional_grp().