CALYPSO: t_sph_fft_selector Module Reference
t_sph_fft_selector Module Reference
Selector of Fourier transform.
Data Types
type work_for_ffts
Structure for work area of FFTs.
Functions/Subroutines
subroutine init_sph_fft_select (id_rank, iflag_FFT_in, sph_rtp, comm_rtp, ncomp_bwd, ncomp_fwd, WK_FFTs)
subroutine finalize_sph_fft_select (sph_rtp, WK_FFTs)
subroutine verify_sph_fft_select (sph_rtp, comm_rtp, ncomp_bwd, ncomp_fwd, WK_FFTs)
subroutine fwd_fft_select_to_send (sph_rtp, comm_rtp, ncomp_fwd, n_WS, v_rtp, WS, WK_FFTs)
subroutine back_fft_select_from_recv (sph_rtp, comm_rtp, ncomp_bwd, n_WR, WR, v_rtp, WK_FFTs)
Detailed Description
Selector of Fourier transform.
      subroutine init_sph_FFT_select(id_rank, iflag_FFT_in,           &
     &         sph_rtp, comm_rtp, ncomp_bwd, ncomp_fwd, WK_FFTs)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_comm_tbl), intent(in) :: comm_rtp
        type(work_for_FFTs), intent(inout) :: WK_FFTs
      subroutine finalize_sph_FFT_select(sph_rtp, WK_FFTs)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(work_for_FFTs), intent(inout) :: WK_FFTs
      subroutine verify_sph_FFT_select                                &
     &         (sph_rtp, comm_rtp, ncomp_bwd, ncomp_fwd, WK_FFTs)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(work_for_FFTs), intent(inout) :: WK_FFTs
 ------------------------------------------------------------------
   wrapper subroutine for initierize FFT for ISPACK
 ------------------------------------------------------------------
      subroutine fwd_FFT_select_to_send(sph_rtp, comm_rtp, ncomp_fwd, &
     &                                  n_WS, v_rtp, WS, WK_FFTs)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_comm_tbl), intent(in)  :: comm_rtp
        type(work_for_FFTs), intent(inout) :: WK_FFTs
 ------------------------------------------------------------------
   wrapper subroutine for FFT in ISPACK
   a_{k} = \frac{2}{Nfft} \sum_{j=0}^{Nfft-1} x_{j} \cos (\frac{2\pi j k}{Nfft})
   b_{k} = \frac{2}{Nfft} \sum_{j=0}^{Nfft-1} x_{j} \cos (\frac{2\pi j k}{Nfft})
   a_{0} = \frac{1}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
    K = Nfft/2....
   a_{k} = \frac{1}{Nfft} \sum_{j=0}^{Nfft-1} x_{j} \cos (\frac{2\pi j k}{Nfft})
 ------------------------------------------------------------------
      subroutine back_FFT_select_from_recv                            &
     &        (sph_rtp, comm_rtp, ncomp_bwd, n_WR, WR, v_rtp, WK_FFTs)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_comm_tbl), intent(in)  :: comm_rtp
        type(work_for_FFTs), intent(inout) :: WK_FFTs
 ------------------------------------------------------------------
   wrapper subroutine for backward FFT
   x_{k} = a_{0} + (-1)^{j} a_{Nfft/2} + sum_{k=1}^{Nfft/2-1}
          (a_{k} \cos(2\pijk/Nfft) + b_{k} \sin(2\pijk/Nfft))
 ------------------------------------------------------------------
       i = 1:     a_{0}
       i = 2:     a_{Nfft/2}
       i = 3:     a_{1}
       i = 4:     b_{1}
       ...
       i = 2*k+1: a_{k}
       i = 2*k+2: b_{k}
       ...
       i = Nfft-1:   a_{Nfft/2-1}
       i = Nfft:     b_{Nfft/2-1}
 ------------------------------------------------------------------
Parameters
my_rank Procdess ID
Nsmp Number of SMP processors
Nstacksmp(0:Nsmp) End number for each SMP process
M Number of components for Fourier transforms
Nfft Data length for eadh FFT
X(M,Nfft) Data for Fourier transform
Function/Subroutine Documentation
back_fft_select_from_recv()
subroutine t_sph_fft_selector::back_fft_select_from_recv (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(inout) WR, real (kind=kreal), dimension(sph_rtp%nnod_rtp,ncomp_bwd), intent(inout) v_rtp, type(work_for_ffts), intent(inout) WK_FFTs)
Definition at line 400 of file t_sph_FFT_selector.F90.
References m_fft_selector::iflag_fftpack_component, m_fft_selector::iflag_fftpack_domain, m_fft_selector::iflag_fftpack_single, m_fft_selector::iflag_fftw, m_fft_selector::iflag_fftw_component, m_fft_selector::iflag_fftw_domain, m_fft_selector::iflag_fftw_single, sph_prt_fftw::prt_back_fftw_from_recv(), sph_prt_domain_fftpack5::prt_domain_rfftmb_from_recv(), sph_prt_domain_fftw::prt_field_back_fftw_from_recv(), sph_prt_fftpack5::prt_rfftmb_from_recv(), sph_rtp_fftw::rtp_back_fftw_from_recv(), sph_rtp_domain_fftpack5::rtp_domain_rfftmb_from_recv(), sph_rtp_domain_fftw::rtp_field_back_fftw_from_recv(), sph_rtp_fftpack5::rtp_rfftmb_from_recv(), t_sph_component_fftw::sph_comp_back_fftw_from_recv(), t_sph_component_fftpack5::sph_comp_rfftmb_from_recv(), t_sph_single_fftw::sph_single_back_fftw_from_recv(), and t_sph_single_fftpack5::sph_single_rfftmb_from_recv().
Referenced by sph_trans_w_coriols::sph_b_trans_w_coriolis(), t_sph_transforms::sph_b_trans_w_poles(), t_sph_transforms::sph_backward_transforms(), init_fft_4_mhd::test_fourier_trans_4_mhd(), and init_fft_4_sph::test_fourier_trans_vector().
finalize_sph_fft_select()
subroutine t_sph_fft_selector::finalize_sph_fft_select (type(sph_rtp_grid), intent(in) sph_rtp, type(work_for_ffts), intent(inout) WK_FFTs)
Definition at line 212 of file t_sph_FFT_selector.F90.
References t_sph_component_fftpack5::finalize_sph_comp_fftpack5(), t_sph_component_fftw::finalize_sph_component_fftw(), t_sph_domain_fftpack5::finalize_sph_domain_fftpack5(), t_sph_fftpack5::finalize_sph_fftpack5(), t_sph_field_fftw::finalize_sph_field_fftw(), t_sph_single_fftpack5::finalize_sph_single_fftpack5(), t_sph_single_fftw::finalize_sph_single_fftw(), m_machine_parameter::iflag_debug, m_fft_selector::iflag_fftpack_component, m_fft_selector::iflag_fftpack_domain, m_fft_selector::iflag_fftpack_single, m_fft_selector::iflag_fftw, m_fft_selector::iflag_fftw_component, m_fft_selector::iflag_fftw_domain, and m_fft_selector::iflag_fftw_single.
Referenced by init_fft_4_mhd::test_fourier_trans_4_mhd(), and init_fft_4_sph::test_fourier_trans_vector().
fwd_fft_select_to_send()
subroutine t_sph_fft_selector::fwd_fft_select_to_send (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, integer(kind = kint), intent(in) ncomp_fwd, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(sph_rtp%nnod_rtp,ncomp_fwd), intent(in) v_rtp, real (kind=kreal), dimension(n_ws), intent(inout) WS, type(work_for_ffts), intent(inout) WK_FFTs)
Definition at line 332 of file t_sph_FFT_selector.F90.
References m_fft_selector::iflag_fftpack_component, m_fft_selector::iflag_fftpack_domain, m_fft_selector::iflag_fftpack_single, m_fft_selector::iflag_fftw, m_fft_selector::iflag_fftw_component, m_fft_selector::iflag_fftw_domain, m_fft_selector::iflag_fftw_single, sph_prt_domain_fftpack5::prt_domain_rfftmf_to_send(), sph_prt_domain_fftw::prt_field_fwd_fftw_to_send(), sph_prt_fftw::prt_fwd_fftw_to_send(), sph_prt_fftpack5::prt_rfftmf_to_send(), sph_rtp_domain_fftpack5::rtp_domain_rfftmf_to_send(), sph_rtp_domain_fftw::rtp_field_fwd_fftw_to_send(), sph_rtp_fftw::rtp_fwd_fftw_to_send(), sph_rtp_fftpack5::rtp_rfftmf_to_send(), t_sph_component_fftw::sph_comp_fwd_fftw_to_send(), t_sph_component_fftpack5::sph_comp_rfftmf_to_send(), t_sph_single_fftw::sph_single_fwd_fftw_to_send(), and t_sph_single_fftpack5::sph_single_rfftmf_to_send().
Referenced by sph_trans_w_coriols::sph_f_trans_w_coriolis(), t_sph_transforms::sph_forward_transforms(), init_fft_4_mhd::test_fourier_trans_4_mhd(), and init_fft_4_sph::test_fourier_trans_vector().
init_sph_fft_select()
subroutine t_sph_fft_selector::init_sph_fft_select (integer, intent(in) id_rank, integer(kind = kint) iflag_FFT_in, type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), intent(in) ncomp_fwd, type(work_for_ffts), intent(inout) WK_FFTs)
Definition at line 135 of file t_sph_FFT_selector.F90.
References m_fft_selector::iflag_fftpack_component, m_fft_selector::iflag_fftpack_domain, m_fft_selector::iflag_fftpack_single, m_fft_selector::iflag_fftw, m_fft_selector::iflag_fftw_component, m_fft_selector::iflag_fftw_domain, m_fft_selector::iflag_fftw_single, sph_prt_domain_fftpack5::init_prt_domain_fftpack5(), sph_prt_fftpack5::init_prt_fftpack5(), sph_prt_fftw::init_prt_fftw(), sph_prt_domain_fftw::init_prt_field_fftw(), sph_rtp_domain_fftpack5::init_rtp_domain_fftpack5(), sph_rtp_fftpack5::init_rtp_fftpack5(), sph_rtp_fftw::init_rtp_fftw(), sph_rtp_domain_fftw::init_rtp_field_fftw(), t_sph_component_fftpack5::init_sph_comp_fftpack5(), t_sph_component_fftw::init_sph_component_fftw(), t_sph_single_fftpack5::init_sph_single_fftpack5(), and t_sph_single_fftw::init_sph_single_fftw().
Referenced by init_fft_4_mhd::init_fourier_transform_4_mhd(), init_fft_4_sph::init_fourier_transform_4_sph(), init_sphrical_transform_mhd::init_leg_fourier_trans_mhd(), init_fft_4_mhd::test_fourier_trans_4_mhd(), and init_fft_4_sph::test_fourier_trans_vector().
verify_sph_fft_select()
subroutine t_sph_fft_selector::verify_sph_fft_select (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), intent(in) ncomp_fwd, type(work_for_ffts), intent(inout) WK_FFTs)
Definition at line 254 of file t_sph_FFT_selector.F90.
References m_machine_parameter::iflag_debug, m_fft_selector::iflag_fftpack_component, m_fft_selector::iflag_fftpack_domain, m_fft_selector::iflag_fftpack_single, m_fft_selector::iflag_fftw, m_fft_selector::iflag_fftw_component, m_fft_selector::iflag_fftw_domain, m_fft_selector::iflag_fftw_single, sph_prt_domain_fftpack5::verify_prt_domain_fftpack5(), sph_prt_fftpack5::verify_prt_fftpack5(), sph_prt_fftw::verify_prt_fftw(), sph_prt_domain_fftw::verify_prt_field_fftw(), sph_rtp_domain_fftpack5::verify_rtp_domain_fftpack5(), sph_rtp_fftpack5::verify_rtp_fftpack5(), sph_rtp_fftw::verify_rtp_fftw(), sph_rtp_domain_fftw::verify_rtp_field_fftw(), t_sph_component_fftpack5::verify_sph_comp_fftpack5(), t_sph_component_fftw::verify_sph_component_fftw(), t_sph_single_fftpack5::verify_sph_single_fftpack5(), and t_sph_single_fftw::verify_sph_single_fftw().