CALYPSO: t_spheric_parameter Module Reference
t_spheric_parameter Module Reference
Structure for indexing table of speherical harmonics transform.
Data Types
type sph_grids
Structure of grid and spectr data for spherical spectr method.
type sph_shell_parameters
Structure for spherical shell paramteres.
Functions/Subroutines
subroutine alloc_spheric_parameter (sph)
subroutine dealloc_spheric_parameter (sph)
subroutine dealloc_sph_1d_indices (sph)
subroutine check_global_spheric_parameter (sph_params, sph_rtp)
subroutine check_spheric_para_gl_part (sph)
subroutine check_spheric_parameter (id_rank, sph)
Variables
character(len=kchara), parameter icb_nod_grp_name = 'ICB'
Group name for ICB.
character(len=kchara), parameter cmb_nod_grp_name = 'CMB'
Group name for CMB.
character(len=kchara), parameter ctr_nod_grp_name = 'to_Center'
Group name for innermost radius.
character(len=kchara), parameter ic_ele_grp_name = 'inner_core'
Element Group name for inner core.
character(len=kchara), parameter oc_ele_grp_name = 'outer_core'
Element Group name for outer core.
character(len=kchara), parameter mt_ele_grp_name = 'external'
Element Group name for outer core.
character(len=kchara), parameter icb_sf_grp_name = 'ICB_surf'
Surface Group name for ICB.
character(len=kchara), parameter cmb_sf_grp_name = 'CMB_surf'
Surface Group name for CMB.
character(len=kchara), parameter ctr_sf_grp_name = 'to_Center_surf'
Group name for innermost radius.
Detailed Description
Structure for indexing table of speherical harmonics transform.
      iflag_radial_grid:: radial grid type
        igrid_Chebyshev =    2 :: Chebyshev collocation points
        igrid_non_equidist = 1 :: non-equi-distance
        igrid_equidistance = 0 :: equi-distance
      subroutine alloc_spheric_parameter(sph)
      subroutine dealloc_spheric_parameter(sph)
      subroutine dealloc_sph_1d_indices(sph)
        type(sph_grids), intent(inout) :: sph
      subroutine check_global_spheric_parameter(sph_params, sph_rtp)
        type(sph_shell_parameters), intent(in) :: sph_params
        type(sph_rtp_grid), intent(in)  :: sph_rtp
      subroutine check_spheric_para_gl_part(sph)
        type(sph_grids), intent(in) :: sph
      subroutine check_spheric_parameter(id_rank, sph)
        integer, intent(in) :: id_rank
        type(sph_grids), intent(in) :: sph
Parameters
id_rank Running rank ID
Function/Subroutine Documentation
alloc_spheric_parameter()
subroutine t_spheric_parameter::alloc_spheric_parameter (type(sph_grids), intent(inout) sph)
Definition at line 131 of file t_spheric_parameter.f90.
References t_spheric_rj_data::alloc_spheric_param_rj(), t_spheric_rlm_data::alloc_spheric_param_rlm(), t_spheric_rtm_data::alloc_spheric_param_rtm(), and t_spheric_rtp_data::alloc_spheric_param_rtp().
check_global_spheric_parameter()
subroutine t_spheric_parameter::check_global_spheric_parameter (type(sph_shell_parameters), intent(in) sph_params, type(sph_rtp_grid), intent(in) sph_rtp)
Definition at line 174 of file t_spheric_parameter.f90.
Referenced by mpi_gen_sph_grids_modes::const_sph_global_parameters().
check_spheric_para_gl_part()
subroutine t_spheric_parameter::check_spheric_para_gl_part (type(sph_grids), intent(in) sph)
Definition at line 189 of file t_spheric_parameter.f90.
check_spheric_parameter()
subroutine t_spheric_parameter::check_spheric_parameter (integer, intent(in) id_rank, type(sph_grids), intent(in) sph)
Definition at line 204 of file t_spheric_parameter.f90.
References t_spheric_rj_data::check_spheric_param_rj(), t_spheric_rlm_data::check_spheric_param_rlm(), t_spheric_rtm_data::check_spheric_param_rtm(), and t_spheric_rtp_data::check_spheric_param_rtp().
dealloc_sph_1d_indices()
subroutine t_spheric_parameter::dealloc_sph_1d_indices (type(sph_grids), intent(inout) sph)
Definition at line 159 of file t_spheric_parameter.f90.
References t_spheric_rj_data::dealloc_sph_1d_index_rj(), t_spheric_rlm_data::dealloc_sph_1d_index_rlm(), t_spheric_rtm_data::dealloc_sph_1d_index_rtm(), and t_spheric_rtp_data::dealloc_sph_1d_index_rtp().
Referenced by parallel_load_data_4_sph::dealloc_sph_modes().
dealloc_spheric_parameter()
subroutine t_spheric_parameter::dealloc_spheric_parameter (type(sph_grids), intent(inout) sph)
Definition at line 145 of file t_spheric_parameter.f90.
References t_spheric_rj_data::dealloc_spheric_param_rj(), t_spheric_rlm_data::dealloc_spheric_param_rlm(), t_spheric_rtm_data::dealloc_spheric_param_rtm(), and t_spheric_rtp_data::dealloc_spheric_param_rtp().
Referenced by parallel_load_data_4_sph::dealloc_sph_modes().
Variable Documentation
cmb_nod_grp_name
character(len=kchara), parameter t_spheric_parameter::cmb_nod_grp_name = 'CMB'
Group name for CMB.
Definition at line 49 of file t_spheric_parameter.f90.
Referenced by t_ctl_params_gen_sph_shell::set_ctl_radius_4_shell(), set_radius_4_sph_dynamo::set_radius_dat_4_sph_dynamo(), r_interpolate_marged_sph::set_sph_boundary_4_merge(), set_stack_4_sph_groups::set_stack_rj_radial_grp(), and set_stack_4_sph_groups::set_stack_rtp_radial_grp().
cmb_sf_grp_name
character(len=kchara), parameter t_spheric_parameter::cmb_sf_grp_name = 'CMB_surf'
Surface Group name for CMB.
Definition at line 67 of file t_spheric_parameter.f90.
ctr_nod_grp_name
character(len=kchara), parameter t_spheric_parameter::ctr_nod_grp_name = 'to_Center'
Group name for innermost radius.
Definition at line 51 of file t_spheric_parameter.f90.
Referenced by set_sph_surf_group::count_sph_local_surf_grp_item(), set_bc_sph_mhd::s_set_bc_sph_mhd(), t_ctl_params_gen_sph_shell::set_ctl_radius_4_shell(), set_radius_4_sph_dynamo::set_radius_dat_4_sph_dynamo(), set_bc_sph_mhd::set_sph_bc_magne_sph(), set_sph_surf_group::set_sph_local_surf_grp_item(), set_stack_4_sph_groups::set_stack_rj_radial_grp(), and set_stack_4_sph_groups::set_stack_rtp_radial_grp().
ctr_sf_grp_name
character(len=kchara), parameter t_spheric_parameter::ctr_sf_grp_name = 'to_Center_surf'
Group name for innermost radius.
Definition at line 69 of file t_spheric_parameter.f90.
Referenced by set_bc_sph_mhd::s_set_bc_sph_mhd(), and set_bc_sph_mhd::set_sph_bc_magne_sph().
ic_ele_grp_name
character(len=kchara), parameter t_spheric_parameter::ic_ele_grp_name = 'inner_core'
Element Group name for inner core.
Definition at line 55 of file t_spheric_parameter.f90.
Referenced by const_fem_mesh_sph_mhd::const_global_rtp_mesh(), set_sph_ele_group::count_sph_local_ele_grp_item(), set_sph_ele_group::set_sph_local_ele_grp_item(), set_stack_4_sph_groups::set_stack_rj_radial_grp(), and set_stack_4_sph_groups::set_stack_rtp_radial_grp().
icb_nod_grp_name
character(len=kchara), parameter t_spheric_parameter::icb_nod_grp_name = 'ICB'
Group name for ICB.
Definition at line 47 of file t_spheric_parameter.f90.
Referenced by set_sph_surf_group::count_sph_local_surf_grp_item(), t_ctl_params_gen_sph_shell::set_ctl_radius_4_shell(), set_radius_4_sph_dynamo::set_radius_dat_4_sph_dynamo(), r_interpolate_marged_sph::set_sph_boundary_4_merge(), set_sph_surf_group::set_sph_local_surf_grp_item(), set_stack_4_sph_groups::set_stack_rj_radial_grp(), and set_stack_4_sph_groups::set_stack_rtp_radial_grp().
icb_sf_grp_name
character(len=kchara), parameter t_spheric_parameter::icb_sf_grp_name = 'ICB_surf'
Surface Group name for ICB.
Definition at line 65 of file t_spheric_parameter.f90.
mt_ele_grp_name
character(len=kchara), parameter t_spheric_parameter::mt_ele_grp_name = 'external'
Element Group name for outer core.
Definition at line 61 of file t_spheric_parameter.f90.
oc_ele_grp_name
character(len=kchara), parameter t_spheric_parameter::oc_ele_grp_name = 'outer_core'
Element Group name for outer core.
Definition at line 58 of file t_spheric_parameter.f90.
Referenced by const_fem_mesh_sph_mhd::const_global_rtp_mesh(), set_stack_4_sph_groups::set_stack_rj_radial_grp(), and set_stack_4_sph_groups::set_stack_rtp_radial_grp().