CALYPSO: cal_sph_divergence_of_force Module Reference
cal_sph_divergence_of_force Module Reference
Evaluate curl or divergence of forces.
Functions/Subroutines
subroutine cal_div_of_forces_sph_2 (sph_rj, r_2nd, MHD_prop, sph_MHD_bc, g_sph_rj, ipol_frc, ipol_div_frc, rj_fld)
subroutine cal_div_of_buoyancies_sph_2 (iflag_4_gravity, iflag_4_composit_buo, sph_rj, r_2nd, sph_MHD_bc, g_sph_rj, ipol_frc, ipol_div_frc, rj_fld)
Detailed Description
Evaluate curl or divergence of forces.
      subroutine cal_div_of_forces_sph_2                              &
     &         (sph_rj, r_2nd, MHD_prop, sph_MHD_bc, g_sph_rj,        &
     &          ipol_frc, ipol_div_frc, rj_fld)
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(fdm_matrices), intent(in) :: r_2nd
        type(MHD_evolution_param), intent(in) :: MHD_prop
        type(sph_MHD_boundary_data), intent(in) :: sph_MHD_bc
        type(phys_address), intent(in) :: ipol
        type(base_force_address), intent(in) :: ipol_frc
        type(base_force_address), intent(in) :: ipol_rot_frc
        type(base_force_address), intent(in) :: ipol_div_frc
        type(phys_data), intent(inout) :: rj_fld
      subroutine cal_div_of_buoyancies_sph_2                          &
     &         (iflag_4_gravity, iflag_4_composit_buo,                &
     &          sph_rj, r_2nd, sph_MHD_bc, g_sph_rj,                  &
     &          ipol_frc, ipol_div_frc, rj_fld)
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(fdm_matrices), intent(in) :: r_2nd
        type(sph_MHD_boundary_data), intent(in) :: sph_MHD_bc
        type(base_force_address), intent(in) :: ipol_frc
        type(base_force_address), intent(in) :: ipol_div_frc
        type(phys_data), intent(inout) :: rj_fld
Function/Subroutine Documentation
cal_div_of_buoyancies_sph_2()
subroutine cal_sph_divergence_of_force::cal_div_of_buoyancies_sph_2 (logical, intent(in) iflag_4_gravity, logical, intent(in) iflag_4_composit_buo, type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_mhd_boundary_data), intent(in) sph_MHD_bc, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, type(base_force_address), intent(in) ipol_frc, type(base_force_address), intent(in) ipol_div_frc, type(phys_data), intent(inout) rj_fld)
Definition at line 119 of file cal_sph_divergence_of_force.f90.
References const_sph_divergence::const_sph_div_force().
Referenced by cal_div_of_forces_sph_2().
cal_div_of_forces_sph_2()
subroutine cal_sph_divergence_of_force::cal_div_of_forces_sph_2 (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(mhd_evolution_param), intent(in) MHD_prop, type(sph_mhd_boundary_data), intent(in) sph_MHD_bc, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, type(base_force_address), intent(in) ipol_frc, type(base_force_address), intent(in) ipol_div_frc, type(phys_data), intent(inout) rj_fld)
Definition at line 61 of file cal_sph_divergence_of_force.f90.
References cal_div_of_buoyancies_sph_2(), and const_sph_divergence::const_sph_div_force().
Referenced by lead_fields_4_sph_mhd::pressure_4_sph_mhd().