CALYPSO: analyzer_sph_snap_w_psf Module Reference
analyzer_sph_snap_w_psf Module Reference
Main loop to evaluate snapshots from spectr data.
Functions/Subroutines
subroutine initialize_sph_snap_w_psf
subroutine evolution_sph_snap_w_psf
Variables
character(len=kchara), parameter, private snap_ctl_name = 'control_snapshot'
File name for control file.
type(dns_mhd_simulation_control), save, private dns_mhd_ctl1
Control struture for MHD simulation.
type(sph_mesh_field_data), save, private sph_mhd1
Structure of spectr grid and data.
type(surfacing_modules), save, private viz_psfs1
Structure of sectioning and isosurfaceing modules.
real(kind=kreal), private total_start
Detailed Description
Main loop to evaluate snapshots from spectr data.
      subroutine initialize_sph_snap_w_psf
      subroutine evolution_sph_snap_w_psf
Function/Subroutine Documentation
evolution_sph_snap_w_psf()
subroutine analyzer_sph_snap_w_psf::evolution_sph_snap_w_psf
Definition at line 109 of file analyzer_sph_snap_w_psf.f90.
References t_sph_trans_arrays_mhd::alloc_sph_trans_area_snap(), calypso_mpi::calypso_mpi_barrier(), t_sph_trans_arrays_mhd::dealloc_sph_trans_area_snap(), m_work_time::end_elapsed_time(), fem_analyzer_sph_mhd::fem_analyze_sph_mhd(), m_sph_mhd_model_data::fem_d1, fem_analyzer_sph_mhd::fem_finalize(), m_work_time::ied_total_elapsed, m_machine_parameter::iflag_debug, m_elapsed_labels_4_mhd::iflag_mhd_time, m_work_time::iflag_tot_time, m_elapsed_labels_4_mhd::ist_elapsed_mhd, output_viz_file_control::lead_field_data_flag(), m_mhd_step_parameter::mhd_files1, m_mhd_step_parameter::mhd_io1, m_mhd_step_parameter::mhd_step1, m_work_time::output_elapsed_times(), set_time_step_params::set_from_initial_step(), sph_analyzer_snap_w_psf::sph_analyze_snap_psf(), sph_mhd1, t_sph_mhd_zonal_mean_viz::sph_mhd_zmean_sections(), m_sph_mhd_model_data::sph_model1, fem_analyzer_sph_mhd::sph_to_fem_bridge_mhd(), m_sph_mhd_model_data::sph_wk1, m_work_time::start_elapsed_time(), t_viz_sections::visualize_surface(), viz_psfs1, and m_sph_mhd_model_data::zmeans1.
Referenced by sph_snapshot_w_psf().
initialize_sph_snap_w_psf()
subroutine analyzer_sph_snap_w_psf::initialize_sph_snap_w_psf
Definition at line 56 of file analyzer_sph_snap_w_psf.f90.
References calypso_mpi::calypso_mpi_barrier(), dns_mhd_ctl1, m_elapsed_labels_send_recv::elpsed_label_field_send_recv(), m_work_time::end_elapsed_time(), m_sph_mhd_model_data::fem_d1, fem_analyzer_sph_mhd::fem_initialize_sph_mhd(), m_work_time::ied_total_elapsed, m_machine_parameter::iflag_debug, m_elapsed_labels_4_mhd::iflag_mhd_time, m_work_time::iflag_tot_time, m_work_time::init_elapse_time_by_total(), t_viz_sections::init_visualize_surface(), t_sph_mhd_zonal_mean_viz::init_zonal_mean_sections(), input_control_sph_mhd::input_control_sph_mhd_psf(), m_elapsed_labels_4_mhd::ist_elapsed_mhd, m_mhd_step_parameter::mhd_files1, m_mhd_step_parameter::mhd_io1, m_mhd_step_parameter::mhd_step1, calypso_mpi::my_rank, t_ctl_data_sph_mhd_psf::read_control_4_sph_mhd_w_psf(), init_sph_mhd_elapsed_label::reset_elapse_4_init_sph_mhd(), init_sph_mhd_elapsed_label::set_sph_mhd_elapsed_label(), snap_ctl_name, sph_analyzer_snap_w_psf::sph_init_sph_snap_psf(), sph_mhd1, m_sph_mhd_model_data::sph_model1, m_sph_mhd_model_data::sph_wk1, m_work_time::start_elapsed_time(), total_start, viz_psfs1, and m_sph_mhd_model_data::zmeans1.
Referenced by sph_snapshot_w_psf().
Variable Documentation
dns_mhd_ctl1
type(dns_mhd_simulation_control), save, private analyzer_sph_snap_w_psf::dns_mhd_ctl1 private
Control struture for MHD simulation.
Definition at line 41 of file analyzer_sph_snap_w_psf.f90.
Referenced by initialize_sph_snap_w_psf().
snap_ctl_name
character(len=kchara), parameter, private analyzer_sph_snap_w_psf::snap_ctl_name = 'control_snapshot' private
File name for control file.
Definition at line 38 of file analyzer_sph_snap_w_psf.f90.
Referenced by initialize_sph_snap_w_psf().
sph_mhd1
type(sph_mesh_field_data), save, private analyzer_sph_snap_w_psf::sph_mhd1 private
Structure of spectr grid and data.
Definition at line 44 of file analyzer_sph_snap_w_psf.f90.
Referenced by evolution_sph_snap_w_psf(), and initialize_sph_snap_w_psf().
total_start
real (kind=kreal), private analyzer_sph_snap_w_psf::total_start private
Definition at line 48 of file analyzer_sph_snap_w_psf.f90.
Referenced by initialize_sph_snap_w_psf().
viz_psfs1
type(surfacing_modules), save, private analyzer_sph_snap_w_psf::viz_psfs1 private
Structure of sectioning and isosurfaceing modules.
Definition at line 46 of file analyzer_sph_snap_w_psf.f90.
Referenced by evolution_sph_snap_w_psf(), and initialize_sph_snap_w_psf().