CALYPSO: set_sp_rlm_for_leg_vecprod Module Reference
set_sp_rlm_for_leg_vecprod Module Reference
Set spectrum data for backward Legendre transform.
Functions/Subroutines
subroutine set_sp_rlm_vector_blocked (nnod_rlm, nidx_rlm, istep_rlm, idx_gl_1d_rlm_j, g_sph_rlm, jst, nd, k_rlm, a1r_1d_rlm_r, a2r_1d_rlm_r, ncomp, n_WR, irev_sr_rlm, WR, nj_rlm, pol_e, dpoldt_e, dpoldp_e, dtordt_e, dtordp_e)
subroutine set_sp_rlm_scalar_blocked (nnod_rlm, istep_rlm, jst, nd, k_rlm, ncomp, nvector, n_WR, irev_sr_rlm, WR, nj_rlm, scl_e)
subroutine set_sp_rlm_vector_symmetry (nnod_rlm, nidx_rlm, istep_rlm, idx_gl_1d_rlm_j, g_sph_rlm, jst, nd, k_rlm, a1r_1d_rlm_r, a2r_1d_rlm_r, ncomp, n_WR, irev_sr_rlm, WR, nj_rlm, pol_e, dpoldt_e, dpoldp_e, dtordt_e, dtordp_e, pol_o, dpoldt_o, dpoldp_o, dtordt_o, dtordp_o)
subroutine set_sp_rlm_scalar_symmetry (nnod_rlm, istep_rlm, jst, nd, k_rlm, ncomp, nvector, n_WR, irev_sr_rlm, WR, nj_rlm, scl_e, scl_o)
subroutine set_sp_rlm_vector_equator (nnod_rlm, nidx_rlm, istep_rlm, idx_gl_1d_rlm_j, g_sph_rlm, jst, nd, k_rlm, a1r_1d_rlm_r, a2r_1d_rlm_r, ncomp, n_WR, irev_sr_rlm, WR, nj_rlm, pol_e, dpoldp_e, dtordp_e, dpoldt_o, dtordt_o)
subroutine set_sp_rlm_scalar_equator (nnod_rlm, istep_rlm, jst, nd, k_rlm, ncomp, nvector, n_WR, irev_sr_rlm, WR, nj_rlm, scl_e)
Detailed Description
Set spectrum data for backward Legendre transform.
      subroutine set_sp_rlm_vector_blocked                            &
     &       (nnod_rlm, nidx_rlm, istep_rlm, idx_gl_1d_rlm_j,         &
     &        g_sph_rlm, jst, nd, k_rlm, a1r_1d_rlm_r, a2r_1d_rlm_r,  &
     &        ncomp, n_WR, irev_sr_rlm, WR, nj_rlm,                   &
     &        pol_e, dpoldt_e, dpoldp_e, dtordt_e, dtordp_e)
      subroutine set_sp_rlm_scalar_blocked(nnod_rlm, istep_rlm,       &
     &          jst, nd, k_rlm, ncomp, nvector, n_WR, irev_sr_rlm, WR,&
     &          nj_rlm, scl_e)
      subroutine set_sp_rlm_vector_symmetry                           &
     &       (nnod_rlm, nidx_rlm, istep_rlm, idx_gl_1d_rlm_j,         &
     &        g_sph_rlm, jst, nd, k_rlm, a1r_1d_rlm_r, a2r_1d_rlm_r,  &
     &        ncomp, n_WR, irev_sr_rlm, WR, nj_rlm,                   &
     &        pol_e, dpoldt_e, dpoldp_e, dtordt_e, dtordp_e,          &
     &        pol_o, dpoldt_o, dpoldp_o, dtordt_o, dtordp_o)
      subroutine set_sp_rlm_scalar_symmetry(nnod_rlm, istep_rlm,      &
     &          jst, nd, k_rlm, ncomp, nvector, n_WR, irev_sr_rlm, WR,&
     &          nj_rlm, scl_e, scl_o)
      subroutine set_sp_rlm_vector_equator                            &
     &       (nnod_rlm, nidx_rlm, istep_rlm, idx_gl_1d_rlm_j,         &
     &        g_sph_rlm, jst, nd, k_rlm, a1r_1d_rlm_r, a2r_1d_rlm_r,  &
     &        ncomp, n_WR, irev_sr_rlm, WR, nj_rlm,                   &
     &        pol_e, dpoldp_e, dtordp_e, dpoldt_o, dtordt_o)
      subroutine set_sp_rlm_scalar_equator(nnod_rlm, istep_rlm,       &
     &          jst, nd, k_rlm, ncomp, nvector, n_WR, irev_sr_rlm, WR,&
     &          nj_rlm, scl_e)
Function/Subroutine Documentation
set_sp_rlm_scalar_blocked()
subroutine set_sp_rlm_for_leg_vecprod::set_sp_rlm_scalar_blocked (integer(kind = kint), intent(in) nnod_rlm, integer(kind = kint), dimension(2), intent(in) istep_rlm, integer(kind = kint), intent(in) jst, integer(kind = kint), intent(in) nd, integer(kind = kint), intent(in) k_rlm, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) n_WR, integer(kind = kint), dimension(nnod_rlm), intent(in) irev_sr_rlm, real (kind=kreal), dimension(n_wr), intent(inout) WR, integer(kind = kint), intent(in) nj_rlm, real(kind = kreal), dimension(nj_rlm), intent(inout) scl_e)
Definition at line 100 of file set_sp_rlm_for_leg_vecprod.f90.
set_sp_rlm_scalar_equator()
subroutine set_sp_rlm_for_leg_vecprod::set_sp_rlm_scalar_equator (integer(kind = kint), intent(in) nnod_rlm, integer(kind = kint), dimension(2), intent(in) istep_rlm, integer(kind = kint), intent(in) jst, integer(kind = kint), intent(in) nd, integer(kind = kint), intent(in) k_rlm, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) n_WR, integer(kind = kint), dimension(nnod_rlm), intent(in) irev_sr_rlm, real (kind=kreal), dimension(n_wr), intent(inout) WR, integer(kind = kint), intent(in) nj_rlm, real(kind = kreal), dimension((nj_rlm+1)/2), intent(inout) scl_e)
Definition at line 300 of file set_sp_rlm_for_leg_vecprod.f90.
Referenced by legendre_bwd_trans_symmetry::leg_bwd_trans_scalar_sym_org(), and legendre_bwd_trans_sym_spin::leg_bwd_trans_scalar_sym_spin().
set_sp_rlm_scalar_symmetry()
subroutine set_sp_rlm_for_leg_vecprod::set_sp_rlm_scalar_symmetry (integer(kind = kint), intent(in) nnod_rlm, integer(kind = kint), dimension(2), intent(in) istep_rlm, integer(kind = kint), intent(in) jst, integer(kind = kint), intent(in) nd, integer(kind = kint), intent(in) k_rlm, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) n_WR, integer(kind = kint), dimension(nnod_rlm), intent(in) irev_sr_rlm, real (kind=kreal), dimension(n_wr), intent(inout) WR, integer(kind = kint), intent(in) nj_rlm, real(kind = kreal), dimension((nj_rlm+1)/2), intent(inout) scl_e, real(kind = kreal), dimension(nj_rlm/2), intent(inout) scl_o)
Definition at line 201 of file set_sp_rlm_for_leg_vecprod.f90.
Referenced by legendre_bwd_trans_symmetry::leg_bwd_trans_scalar_sym_org(), and legendre_bwd_trans_sym_spin::leg_bwd_trans_scalar_sym_spin().
set_sp_rlm_vector_blocked()
subroutine set_sp_rlm_for_leg_vecprod::set_sp_rlm_vector_blocked (integer(kind = kint), intent(in) nnod_rlm, integer(kind = kint), dimension(2), intent(in) nidx_rlm, integer(kind = kint), dimension(2), intent(in) istep_rlm, integer(kind = kint), dimension(nidx_rlm(2),3), intent(in) idx_gl_1d_rlm_j, real(kind = kreal), dimension(nidx_rlm(2),17), intent(in) g_sph_rlm, integer(kind = kint), intent(in) jst, integer(kind = kint), intent(in) nd, integer(kind = kint), intent(in) k_rlm, real(kind = kreal), intent(in) a1r_1d_rlm_r, real(kind = kreal), intent(in) a2r_1d_rlm_r, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) n_WR, integer(kind = kint), dimension(nnod_rlm), intent(in) irev_sr_rlm, real (kind=kreal), dimension(n_wr), intent(inout) WR, integer(kind = kint), intent(in) nj_rlm, real(kind = kreal), dimension(nj_rlm), intent(inout) pol_e, real(kind = kreal), dimension(nj_rlm), intent(inout) dpoldt_e, real(kind = kreal), dimension(nj_rlm), intent(inout) dpoldp_e, real(kind = kreal), dimension(nj_rlm), intent(inout) dtordt_e, real(kind = kreal), dimension(nj_rlm), intent(inout) dtordp_e)
Definition at line 51 of file set_sp_rlm_for_leg_vecprod.f90.
set_sp_rlm_vector_equator()
subroutine set_sp_rlm_for_leg_vecprod::set_sp_rlm_vector_equator (integer(kind = kint), intent(in) nnod_rlm, integer(kind = kint), dimension(2), intent(in) nidx_rlm, integer(kind = kint), dimension(2), intent(in) istep_rlm, integer(kind = kint), dimension(nidx_rlm(2),3), intent(in) idx_gl_1d_rlm_j, real(kind = kreal), dimension(nidx_rlm(2),17), intent(in) g_sph_rlm, integer(kind = kint), intent(in) jst, integer(kind = kint), intent(in) nd, integer(kind = kint), intent(in) k_rlm, real(kind = kreal), intent(in) a1r_1d_rlm_r, real(kind = kreal), intent(in) a2r_1d_rlm_r, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) n_WR, integer(kind = kint), dimension(nnod_rlm), intent(in) irev_sr_rlm, real (kind=kreal), dimension(n_wr), intent(inout) WR, integer(kind = kint), intent(in) nj_rlm, real(kind = kreal), dimension((nj_rlm+1)/2), intent(inout) pol_e, real(kind = kreal), dimension((nj_rlm+1)/2), intent(inout) dpoldp_e, real(kind = kreal), dimension((nj_rlm+1)/2), intent(inout) dtordp_e, real(kind = kreal), dimension(nj_rlm/2), intent(inout) dpoldt_o, real(kind = kreal), dimension(nj_rlm/2), intent(inout) dtordt_o)
Definition at line 242 of file set_sp_rlm_for_leg_vecprod.f90.
Referenced by legendre_bwd_trans_symmetry::leg_bwd_trans_vector_sym_org(), and legendre_bwd_trans_sym_spin::leg_bwd_trans_vector_sym_spin().
set_sp_rlm_vector_symmetry()
subroutine set_sp_rlm_for_leg_vecprod::set_sp_rlm_vector_symmetry (integer(kind = kint), intent(in) nnod_rlm, integer(kind = kint), dimension(2), intent(in) nidx_rlm, integer(kind = kint), dimension(2), intent(in) istep_rlm, integer(kind = kint), dimension(nidx_rlm(2),3), intent(in) idx_gl_1d_rlm_j, real(kind = kreal), dimension(nidx_rlm(2),17), intent(in) g_sph_rlm, integer(kind = kint), intent(in) jst, integer(kind = kint), intent(in) nd, integer(kind = kint), intent(in) k_rlm, real(kind = kreal), intent(in) a1r_1d_rlm_r, real(kind = kreal), intent(in) a2r_1d_rlm_r, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) n_WR, integer(kind = kint), dimension(nnod_rlm), intent(in) irev_sr_rlm, real (kind=kreal), dimension(n_wr), intent(inout) WR, integer(kind = kint), intent(in) nj_rlm, real(kind = kreal), dimension((nj_rlm+1)/2), intent(inout) pol_e, real(kind = kreal), dimension((nj_rlm+1)/2), intent(inout) dpoldt_e, real(kind = kreal), dimension((nj_rlm+1)/2), intent(inout) dpoldp_e, real(kind = kreal), dimension((nj_rlm+1)/2), intent(inout) dtordt_e, real(kind = kreal), dimension((nj_rlm+1)/2), intent(inout) dtordp_e, real(kind = kreal), dimension(nj_rlm/2), intent(inout) pol_o, real(kind = kreal), dimension(nj_rlm/2), intent(inout) dpoldt_o, real(kind = kreal), dimension(nj_rlm/2), intent(inout) dpoldp_o, real(kind = kreal), dimension(nj_rlm/2), intent(inout) dtordt_o, real(kind = kreal), dimension(nj_rlm/2), intent(inout) dtordp_o)
Definition at line 132 of file set_sp_rlm_for_leg_vecprod.f90.
Referenced by legendre_bwd_trans_symmetry::leg_bwd_trans_vector_sym_org(), and legendre_bwd_trans_sym_spin::leg_bwd_trans_vector_sym_spin().