CALYPSO: cal_sp_rlm_sym_mat_tsmp Module Reference
cal_sp_rlm_sym_mat_tsmp Module Reference
forward Legendre transform (Blocked loop version)
Functions/Subroutines
subroutine cal_sp_rlm_sym_mat_rout (nnod_rlm, nidx_rlm, istep_rlm, idx_gl_1d_rlm_j, radius_1d_rlm_r, g_sph_rlm, jst, n_jk_o, n_jk_e, pol_e, pol_o, tor_e, tor_o, ncomp_send, nvector, nscalar, irev_sr_rlm, n_WS, WS)
subroutine cal_sp_rlm_sym_mat_rin (nnod_rlm, nidx_rlm, istep_rlm, idx_gl_1d_rlm_j, radius_1d_rlm_r, g_sph_rlm, jst, n_jk_o, n_jk_e, pol_e, pol_o, tor_e, tor_o, ncomp_send, nvector, nscalar, irev_sr_rlm, n_WS, WS)
Variables
integer, external omp_get_max_threads
Detailed Description
forward Legendre transform (Blocked loop version)
      subroutine cal_sp_rlm_sym_mat_rout(nnod_rlm, nidx_rlm,          &
     &         istep_rlm, idx_gl_1d_rlm_j, radius_1d_rlm_r, g_sph_rlm,&
     &         jst, n_jk_o, n_jk_e, pol_e, pol_o, tor_e, tor_o,       &
     &         ncomp_send, nvector, nscalar, irev_sr_rlm, n_WS, WS)
      subroutine cal_sp_rlm_sym_mat_rin(nnod_rlm, nidx_rlm,           &
     &         istep_rlm, idx_gl_1d_rlm_j, radius_1d_rlm_r, g_sph_rlm,&
     &         jst, n_jk_o, n_jk_e, pol_e, pol_o, tor_e, tor_o,       &
     &         ncomp_send, nvector, nscalar, irev_sr_rlm, n_WS, WS)
Function/Subroutine Documentation
cal_sp_rlm_sym_mat_rin()
subroutine cal_sp_rlm_sym_mat_tsmp::cal_sp_rlm_sym_mat_rin (integer(kind = kint), intent(in) nnod_rlm, integer(kind = kint), dimension(2), intent(in) nidx_rlm, integer(kind = kint), dimension(2), intent(in) istep_rlm, integer(kind = kint), dimension(nidx_rlm(2),3), intent(in) idx_gl_1d_rlm_j, real(kind = kreal), dimension(nidx_rlm(1)), intent(in) radius_1d_rlm_r, real(kind = kreal), dimension(nidx_rlm(2),17), intent(in) g_sph_rlm, integer(kind = kint), intent(in) jst, integer(kind = kint), intent(in) n_jk_o, integer(kind = kint), intent(in) n_jk_e, real(kind = kreal), dimension(3*nvector+nscalar,nidx_rlm(1),n_jk_e), intent(inout) pol_e, real(kind = kreal), dimension(3*nvector+nscalar,nidx_rlm(1),n_jk_o), intent(inout) pol_o, real(kind = kreal), dimension(2*nvector,nidx_rlm(1),n_jk_e), intent(inout) tor_e, real(kind = kreal), dimension(2*nvector,nidx_rlm(1),n_jk_o), intent(inout) tor_o, integer(kind = kint), intent(in) ncomp_send, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, integer(kind = kint), dimension(nnod_rlm), intent(in) irev_sr_rlm, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 245 of file cal_sp_rlm_sym_mat_tsmp.f90.
References m_work_time::end_elapsed_time(), m_elapsed_labels_sph_trns::iflag_leg_time, m_elapsed_labels_sph_trns::ist_elapsed_leg, and m_work_time::start_elapsed_time().
Referenced by leg_fwd_trans_on_the_fly::legendre_f_trans_on_the_fly(), leg_fwd_trans_sym_mat_tj::legendre_f_trans_sym_mat_tj(), and legendre_fwd_trans_testloop::legendre_f_trans_vector_test().
cal_sp_rlm_sym_mat_rout()
subroutine cal_sp_rlm_sym_mat_tsmp::cal_sp_rlm_sym_mat_rout (integer(kind = kint), intent(in) nnod_rlm, integer(kind = kint), dimension(2), intent(in) nidx_rlm, integer(kind = kint), dimension(2), intent(in) istep_rlm, integer(kind = kint), dimension(nidx_rlm(2),3), intent(in) idx_gl_1d_rlm_j, real(kind = kreal), dimension(nidx_rlm(1)), intent(in) radius_1d_rlm_r, real(kind = kreal), dimension(nidx_rlm(2),17), intent(in) g_sph_rlm, integer(kind = kint), intent(in) jst, integer(kind = kint), intent(in) n_jk_o, integer(kind = kint), intent(in) n_jk_e, real(kind = kreal), dimension(n_jk_e,nidx_rlm(1),3*nvector+nscalar), intent(inout) pol_e, real(kind = kreal), dimension(n_jk_o,nidx_rlm(1),3*nvector+nscalar), intent(inout) pol_o, real(kind = kreal), dimension(n_jk_e,nidx_rlm(1),2*nvector), intent(inout) tor_e, real(kind = kreal), dimension(n_jk_o,nidx_rlm(1),2*nvector), intent(inout) tor_o, integer(kind = kint), intent(in) ncomp_send, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, integer(kind = kint), dimension(nnod_rlm), intent(in) irev_sr_rlm, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 41 of file cal_sp_rlm_sym_mat_tsmp.f90.
Referenced by leg_fwd_trans_sym_mat_jt::legendre_f_trans_sym_mat_jt().
Variable Documentation
omp_get_max_threads
integer, external cal_sp_rlm_sym_mat_tsmp::omp_get_max_threads
Definition at line 33 of file cal_sp_rlm_sym_mat_tsmp.f90.