CALYPSO: t_field_4_dynamobench Module Reference
t_field_4_dynamobench Module Reference
Dynamo benchmark results.
Data Types
type dynamobench_monitor
Functions/Subroutines
subroutine, private open_dynamobench_monitor_file (sph_bc_U, sph_bc_B, ipol)
subroutine output_field_4_dynamobench (i_step, time, sph_MHD_bc, ipol, bench)
Variables
integer(kind=kint), parameter, private id_dynamobench = 41
file ID for benchmark output file
character(len=kchara), parameter, private dynamobench_field_name = 'dynamobench_field.dat'
file name for benchmark output file
Detailed Description
Dynamo benchmark results.
      subroutine open_dynamobench_monitor_file                        &
     &         (sph_bc_U, sph_bc_B, ipol)
      subroutine output_field_4_dynamobench                           &
     &          (i_step, time, sph_bc_U, sph_bc_B, ipol, bench)
        type(sph_MHD_boundary_data), intent(in) :: sph_MHD_bc
        type(phys_address), intent(in) :: ipol
        type(dynamobench_monitor), intent(in) :: bench
Parameters
i_step time step
time time
Function/Subroutine Documentation
open_dynamobench_monitor_file()
subroutine, private t_field_4_dynamobench::open_dynamobench_monitor_file (type(sph_boundary_type), intent(in) sph_bc_U, type(sph_boundary_type), intent(in) sph_bc_B, type(phys_address), intent(in) ipol) private
Definition at line 87 of file t_field_4_dynamobench.f90.
References dynamobench_field_name, and id_dynamobench.
Referenced by output_field_4_dynamobench().
output_field_4_dynamobench()
subroutine t_field_4_dynamobench::output_field_4_dynamobench (integer(kind = kint), intent(in) i_step, real(kind = kreal), intent(in) time, type(sph_mhd_boundary_data), intent(in) sph_MHD_bc, type(phys_address), intent(in) ipol, type(dynamobench_monitor), intent(in) bench)
Definition at line 140 of file t_field_4_dynamobench.f90.
References id_dynamobench, calypso_mpi::my_rank, and open_dynamobench_monitor_file().
Referenced by sph_analyzer_d_bench::sph_analyze_dbench().
Variable Documentation
dynamobench_field_name
character(len=kchara), parameter, private t_field_4_dynamobench::dynamobench_field_name = 'dynamobench_field.dat' private
file name for benchmark output file
Definition at line 35 of file t_field_4_dynamobench.f90.
Referenced by open_dynamobench_monitor_file().
id_dynamobench
integer(kind=kint), parameter, private t_field_4_dynamobench::id_dynamobench = 41 private
file ID for benchmark output file
Definition at line 33 of file t_field_4_dynamobench.f90.
Referenced by open_dynamobench_monitor_file(), and output_field_4_dynamobench().