CALYPSO: set_loaded_data_4_sph Module Reference
set_loaded_data_4_sph Module Reference
Load spherical harmonics indexing data on multiple processes.
Functions/Subroutines
subroutine set_index_flags_4_sph (sph_param, sph_rtp, sph_rtm, sph_rlm, sph_rj, comm_rtp, comm_rtm, comm_rlm, comm_rj)
subroutine set_index_flags_4_rj (sph_rj, comm_rj)
subroutine set_fem_center_mode_4_sph (internal_node, sph_rtp, sph_param)
subroutine, private count_interval_4_each_dir (numdir, nnod, idx_global, istep)
integer function, private self_comm_flag (num_neib, id_neib)
Detailed Description
Load spherical harmonics indexing data on multiple processes.
      subroutine set_index_flags_4_SPH                                &
     &         (sph_param, sph_rtp, sph_rtm, sph_rlm, sph_rj,         &
     &          comm_rtp, comm_rtm, comm_rlm, comm_rj)
      subroutine set_index_flags_4_rj(sph_rj, comm_rj)
        type(sph_shell_parameters), intent(inout) :: sph_param
        type(sph_rtp_grid), intent(inout) :: sph_rtp
        type(sph_rtm_grid), intent(inout) :: sph_rtm
        type(sph_rlm_grid), intent(inout) :: sph_rlm
        type(sph_rj_grid), intent(inout) :: sph_rj
        type(sph_comm_tbl), intent(inout) :: comm_rtp
        type(sph_comm_tbl), intent(inout) :: comm_rtm
        type(sph_comm_tbl), intent(inout) :: comm_rlm
        type(sph_comm_tbl), intent(inout) :: comm_rj
      subroutine set_fem_center_mode_4_SPH                            &
     &         (internal_node, sph_rtp, sph_param)
        type(sph_rtp_grid), intent(in) :: sph_rtp
      type(sph_shell_parameters), intent(inout) :: sph_param
Function/Subroutine Documentation
count_interval_4_each_dir()
subroutine, private set_loaded_data_4_sph::count_interval_4_each_dir (integer(kind = kint), intent(in) numdir, integer(kind = kint), intent(in) nnod, integer(kind = kint), dimension(nnod,numdir), intent(in) idx_global, integer(kind = kint), dimension(numdir), intent(inout) istep) private
Definition at line 195 of file set_loaded_data_4_sph.f90.
Referenced by set_index_flags_4_rj(), and set_index_flags_4_sph().
self_comm_flag()
integer function, private set_loaded_data_4_sph::self_comm_flag (integer(kind = kint), intent(in) num_neib, integer(kind = kint), dimension(num_neib), intent(in) id_neib) private
Definition at line 222 of file set_loaded_data_4_sph.f90.
References calypso_mpi::my_rank.
Referenced by set_index_flags_4_rj(), and set_index_flags_4_sph().
set_fem_center_mode_4_sph()
subroutine set_loaded_data_4_sph::set_fem_center_mode_4_sph (integer(kind = kint), intent(in) internal_node, type(sph_rtp_grid), intent(in) sph_rtp, type(sph_shell_parameters), intent(inout) sph_param)
Definition at line 145 of file set_loaded_data_4_sph.f90.
References calypso_mpi_int::calypso_mpi_allreduce_one_int(), m_machine_parameter::i_debug, m_machine_parameter::iflag_full_msg, m_spheric_constants::iflag_mesh_same, m_spheric_constants::iflag_mesh_w_center, m_spheric_constants::iflag_mesh_w_pole, and calypso_mpi::my_rank.
set_index_flags_4_rj()
subroutine set_loaded_data_4_sph::set_index_flags_4_rj (type(sph_rj_grid), intent(inout) sph_rj, type(sph_comm_tbl), intent(inout) comm_rj)
Definition at line 113 of file set_loaded_data_4_sph.f90.
References calypso_mpi_int::calypso_mpi_allreduce_one_int(), count_interval_4_each_dir(), m_constants::itwo, self_comm_flag(), and set_special_sph_lm_flags::set_sph_rj_center_flag().
Referenced by parallel_load_data_4_sph::sph_rj_index_flags_and_params().
set_index_flags_4_sph()
subroutine set_loaded_data_4_sph::set_index_flags_4_sph (type(sph_shell_parameters), intent(inout) sph_param, type(sph_rtp_grid), intent(inout) sph_rtp, type(sph_rtm_grid), intent(inout) sph_rtm, type(sph_rlm_grid), intent(inout) sph_rlm, type(sph_rj_grid), intent(inout) sph_rj, type(sph_comm_tbl), intent(inout) comm_rtp, type(sph_comm_tbl), intent(inout) comm_rtm, type(sph_comm_tbl), intent(inout) comm_rlm, type(sph_comm_tbl), intent(inout) comm_rj)
Definition at line 47 of file set_loaded_data_4_sph.f90.
References calypso_mpi_int::calypso_mpi_allreduce_one_int(), count_interval_4_each_dir(), m_constants::ithree, m_constants::itwo, self_comm_flag(), set_special_sph_lm_flags::set_special_degree_order_flags(), and set_special_sph_lm_flags::set_sph_rj_center_flag().
Referenced by parallel_load_data_4_sph::sph_index_flags_and_params().