CALYPSO: set_smp_4_group_types Module Reference
set_smp_4_group_types Module Reference
Functions/Subroutines
subroutine count_num_groups_smp (nod_grp, ele_grp, surf_grp)
subroutine, private count_grp_type_smp (grp)
subroutine, private count_surf_grp_type_smp (sf_grp)
Function/Subroutine Documentation
count_grp_type_smp()
subroutine, private set_smp_4_group_types::count_grp_type_smp (type(group_data), intent(inout) grp) private
Definition at line 42 of file set_smp_4_group_types.f90.
References t_group_data::alloc_group_smp(), m_machine_parameter::np_smp, and cal_minmax_and_stacks::set_group_size_4_smp().
Referenced by count_num_groups_smp().
count_num_groups_smp()
subroutine set_smp_4_group_types::count_num_groups_smp (type(group_data), intent(inout) nod_grp, type(group_data), intent(inout) ele_grp, type(surface_group_data), intent(inout) surf_grp)
Definition at line 26 of file set_smp_4_group_types.f90.
References count_grp_type_smp(), and count_surf_grp_type_smp().
Referenced by const_mesh_information::const_nod_ele_infos(), and const_mesh_information::empty_mesh_info().
count_surf_grp_type_smp()
subroutine, private set_smp_4_group_types::count_surf_grp_type_smp (type(surface_group_data), intent(inout) sf_grp) private
Definition at line 60 of file set_smp_4_group_types.f90.
References t_group_data::alloc_sf_group_smp(), m_machine_parameter::np_smp, and cal_minmax_and_stacks::set_group_size_4_smp().
Referenced by count_num_groups_smp().