CALYPSO: cal_sph_exp_nod_icb_ins Module Reference
cal_sph_exp_nod_icb_ins Module Reference
Set insulated magnetic boundary condition for ICB.
Functions/Subroutines
subroutine cal_sph_nod_icb_ins_b_and_j (jmax, g_sph_rj, kr_in, r_ICB, fdm2_fix_fld_ICB, fdm2_fix_dr_ICB, is_fld, is_rot, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_nod_icb_ins_mag2 (jmax, g_sph_rj, kr_in, r_ICB, is_fld, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_nod_icb_ins_vp_rot2 (jmax, g_sph_rj, kr_in, r_ICB, is_fld, is_rot, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_nod_icb_ins_rot2 (jmax, g_sph_rj, kr_in, r_ICB, fdm2_fix_fld_ICB, fdm2_fix_dr_ICB, is_fld, is_rot, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_nod_icb_ins_diffuse2 (jmax, g_sph_rj, kr_in, r_ICB, fdm2_fix_fld_ICB, fdm2_fix_dr_ICB, coef_d, is_fld, is_diffuse, n_point, ntot_phys_rj, d_rj)
Detailed Description
Set insulated magnetic boundary condition for ICB.
      subroutine cal_sph_nod_icb_ins_b_and_j(jmax, g_sph_rj,          &
     &           kr_in, r_ICB, fdm2_fix_fld_ICB, fdm2_fix_dr_ICB,     &
     &           is_fld, is_rot, n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_nod_icb_ins_mag2(jmax, g_sph_rj,             &
     &           kr_in, r_ICB, is_fld, n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_nod_icb_ins_vp_rot2(jmax, g_sph_rj,          &
     &          kr_in, r_ICB, is_fld, is_rot,                         &
     &          n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_nod_icb_ins_rot2(jmax, g_sph_rj,             &
     &          kr_in, r_ICB, fdm2_fix_fld_ICB, fdm2_fix_dr_ICB,      &
     &          is_fld, is_rot, n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_nod_icb_ins_diffuse2(jmax, g_sph_rj,         &
     &          kr_in, r_ICB, fdm2_fix_fld_ICB, fdm2_fix_dr_ICB,      &
     &          coef_d, is_fld, is_diffuse,                           &
     &          n_point, ntot_phys_rj, d_rj)
Parameters
n_point Number of points for spectrum data
jmax Number of modes for spherical harmonics \(L*(L+2)\)
kr_in Radial ID for inner boundary
r_ICB(0:2) Radius at ICB
fdm2_fix_fld_ICB(0:2,3) Matrix to evaluate radial derivative at ICB with fixed field
fdm2_fix_dr_ICB(-1:1,3) Matrix to evaluate field at ICB with fixed radial derivative
Parameters
coef_d Coefficient for diffusion term
is_fld Field address of input field
is_rot Field address for curl of field
is_diffuse Field address for diffusion of field
Parameters
ntot_phys_rj Total number of components
d_rj Spectrum data
Function/Subroutine Documentation
cal_sph_nod_icb_ins_b_and_j()
subroutine cal_sph_exp_nod_icb_ins::cal_sph_nod_icb_ins_b_and_j (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(0:2), intent(in) r_ICB, real(kind = kreal), dimension(0:2,3), intent(in) fdm2_fix_fld_ICB, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_fix_dr_ICB, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_rot, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 59 of file cal_sph_exp_nod_icb_ins.f90.
References m_constants::one, and m_constants::zero.
Referenced by select_exp_magne_icb::sel_icb_grad_bp_and_current().
cal_sph_nod_icb_ins_diffuse2()
subroutine cal_sph_exp_nod_icb_ins::cal_sph_nod_icb_ins_diffuse2 (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(0:2), intent(in) r_ICB, real(kind = kreal), dimension(0:2,3), intent(in) fdm2_fix_fld_ICB, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_fix_dr_ICB, real(kind = kreal), intent(in) coef_d, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_diffuse, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 209 of file cal_sph_exp_nod_icb_ins.f90.
References m_constants::one.
Referenced by select_exp_magne_icb::sel_icb_sph_magnetic_diffusion().
cal_sph_nod_icb_ins_mag2()
subroutine cal_sph_exp_nod_icb_ins::cal_sph_nod_icb_ins_mag2 (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(0:2), intent(in) r_ICB, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 105 of file cal_sph_exp_nod_icb_ins.f90.
References m_constants::one, and m_constants::zero.
Referenced by select_exp_magne_icb::sel_icb_grad_poloidal_magne().
cal_sph_nod_icb_ins_rot2()
subroutine cal_sph_exp_nod_icb_ins::cal_sph_nod_icb_ins_rot2 (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(0:2), intent(in) r_ICB, real(kind = kreal), dimension(0:2,3), intent(in) fdm2_fix_fld_ICB, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_fix_dr_ICB, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_rot, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 166 of file cal_sph_exp_nod_icb_ins.f90.
References m_constants::one.
Referenced by select_exp_magne_icb::sel_icb_sph_current().
cal_sph_nod_icb_ins_vp_rot2()
subroutine cal_sph_exp_nod_icb_ins::cal_sph_nod_icb_ins_vp_rot2 (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(0:2), intent(in) r_ICB, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_rot, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 135 of file cal_sph_exp_nod_icb_ins.f90.
References m_constants::one, and m_constants::zero.
Referenced by select_exp_magne_icb::sel_icb_sph_rotation_uxb().