CALYPSO: read_udt_from_bindary_data Module Reference
read_udt_from_bindary_data Module Reference
read binary section file
Functions/Subroutines
subroutine read_psf_bin_time_data (nprocs, i_time_step_IO, time_IO, delta_t_IO, bbuf)
subroutine read_psf_bin_field_data (nprocs, ucd_b, bbuf, itmp1_mp)
subroutine read_alloc_psf_bin_field_data (nprocs, ucd_b, bbuf, itmp1_mp)
subroutine read_psf_bin_grid_data (nprocs, ucd_b, bbuf, itmp1_mp)
subroutine read_alloc_psf_bin_grid_data (nprocs, ucd_b, bbuf, itmp1_mp)
Detailed Description
read binary section file
      subroutine read_psf_bin_time_data                               &
     &         (nprocs, i_time_step_IO, time_IO, delta_t_IO, bbuf)
      subroutine read_psf_bin_field_data                              &
     &         (nprocs, ucd_b, bbuf, itmp1_mp)
      subroutine read_alloc_psf_bin_field_data                        &
     &         (nprocs, ucd_b, bbuf, itmp1_mp)
      subroutine read_psf_bin_grid_data(nprocs, ucd_b, bbuf, itmp1_mp)
      subroutine read_alloc_psf_bin_grid_data                         &
        type(ucd_data), intent(inout) :: ucd_b
        type(binary_IO_buffer), intent(inout) :: bbuf
Function/Subroutine Documentation
read_alloc_psf_bin_field_data()
subroutine read_udt_from_bindary_data::read_alloc_psf_bin_field_data (integer, intent(in) nprocs, type(ucd_data), intent(inout) ucd_b, type(binary_io_buffer), intent(inout) bbuf, integer(kind = kint_gl), dimension(nprocs), intent(inout) itmp1_mp)
Definition at line 99 of file read_udt_from_bindary_data.f90.
References t_ucd_data::allocate_ucd_phys_data(), t_ucd_data::allocate_ucd_phys_name(), read_psf_binary_data::read_psf_phys_data_bin(), read_psf_binary_data::read_psf_phys_name_bin(), and read_psf_binary_data::read_psf_phys_num_bin().
Referenced by read_psf_binary_file::read_alloc_iso_bin_file(), read_psf_binary_file::read_alloc_nostep_iso_bin_file(), read_psf_binary_file::read_alloc_nostep_psf_bin_file(), and read_psf_binary_file::read_alloc_psf_bin_file().
read_alloc_psf_bin_grid_data()
subroutine read_udt_from_bindary_data::read_alloc_psf_bin_grid_data (integer, intent(inout) nprocs, type(ucd_data), intent(inout) ucd_b, type(binary_io_buffer), intent(inout) bbuf, integer(kind = kint_gl), dimension(nprocs), intent(inout) itmp1_mp)
Definition at line 166 of file read_udt_from_bindary_data.f90.
References t_ucd_data::allocate_ucd_ele(), t_ucd_data::allocate_ucd_node(), read_psf_binary_data::read_psf_ele_connect_bin(), read_psf_binary_data::read_psf_ele_num_bin(), read_psf_binary_data::read_psf_node_data_bin(), and read_psf_binary_data::read_psf_node_num_bin().
Referenced by read_psf_binary_file::read_alloc_iso_bin_file(), read_psf_binary_file::read_alloc_nostep_iso_bin_file(), and read_psf_binary_file::read_alloc_psf_bin_grid().
read_psf_bin_field_data()
subroutine read_udt_from_bindary_data::read_psf_bin_field_data (integer, intent(in) nprocs, type(ucd_data), intent(inout) ucd_b, type(binary_io_buffer), intent(inout) bbuf, integer(kind = kint_gl), dimension(nprocs), intent(inout) itmp1_mp)
Definition at line 65 of file read_udt_from_bindary_data.f90.
References read_psf_binary_data::read_psf_phys_data_bin(), read_psf_binary_data::read_psf_phys_name_bin(), and read_psf_binary_data::read_psf_phys_num_bin().
Referenced by read_psf_binary_file::read_iso_bin_file(), and read_psf_binary_file::read_psf_bin_file().
read_psf_bin_grid_data()
subroutine read_udt_from_bindary_data::read_psf_bin_grid_data (integer, intent(inout) nprocs, type(ucd_data), intent(inout) ucd_b, type(binary_io_buffer), intent(inout) bbuf, integer(kind = kint_gl), dimension(nprocs), intent(inout) itmp1_mp)
Definition at line 131 of file read_udt_from_bindary_data.f90.
References read_psf_binary_data::read_psf_ele_connect_bin(), read_psf_binary_data::read_psf_ele_num_bin(), read_psf_binary_data::read_psf_node_data_bin(), and read_psf_binary_data::read_psf_node_num_bin().
Referenced by read_psf_binary_file::read_iso_bin_file(), and read_psf_binary_file::read_psf_bin_grid().
read_psf_bin_time_data()
subroutine read_udt_from_bindary_data::read_psf_bin_time_data (integer, intent(in) nprocs, integer(kind=kint), intent(inout) i_time_step_IO, real(kind = kreal), intent(inout) time_IO, real(kind = kreal), intent(inout) delta_t_IO, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 39 of file read_udt_from_bindary_data.f90.
References binary_io::read_one_integer_b(), and binary_io::read_one_real_b().
Referenced by read_psf_binary_file::read_alloc_iso_bin_file(), read_psf_binary_file::read_alloc_psf_bin_file(), read_psf_binary_file::read_iso_bin_file(), and read_psf_binary_file::read_psf_bin_file().