CALYPSO: binary_file_access Module Reference
binary_file_access Module Reference
Data Types
interface close_rawfile
interface open_ad_rawfile
interface open_rd_rawfile
interface open_wt_rawfile
interface rawread_32bit
interface rawread_64bit
interface rawseek_go_fwd
interface rawwrite
Functions/Subroutines
subroutine open_wt_rawfile_f (file_name, bbuf)
subroutine open_ad_rawfile_f (file_name, bbuf)
subroutine open_rd_rawfile_f (file_name, bbuf)
subroutine close_rawfile_f ()
subroutine rawread_real_f (num, data, bbuf)
subroutine rawread_int8_f (num, int8_dat, bbuf)
subroutine rawread_int4_f (num, int4_dat, bbuf)
subroutine rawread_chara_f (len_buf, textbuf, bbuf)
subroutine rawwrite_real_f (num, data, bbuf)
subroutine rawwrite_int8_f (num, int8_dat, bbuf)
subroutine rawwrite_int4_f (num, int4_dat, bbuf)
subroutine rawwrite_chara_f (len_buf, textbuf, bbuf)
subroutine rawseek_go_fwd_f (ioffset, bbuf)
Function/Subroutine Documentation
close_rawfile_f()
subroutine binary_file_access::close_rawfile_f
Definition at line 169 of file binary_file_access.f90.
open_ad_rawfile_f()
subroutine binary_file_access::open_ad_rawfile_f (character(len = kchara), intent(in) file_name, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 135 of file binary_file_access.f90.
References set_parallel_file_name::add_null_character(), m_precision::kchara, t_binary_io_buffer::link_text_buffer_for_bin(), and t_binary_io_buffer::unlink_text_buffer_for_bin().
open_rd_rawfile_f()
subroutine binary_file_access::open_rd_rawfile_f (character(len = kchara), intent(in) file_name, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 152 of file binary_file_access.f90.
References set_parallel_file_name::add_null_character(), m_precision::kchara, t_binary_io_buffer::link_text_buffer_for_bin(), and t_binary_io_buffer::unlink_text_buffer_for_bin().
open_wt_rawfile_f()
subroutine binary_file_access::open_wt_rawfile_f (character(len = kchara), intent(in) file_name, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 118 of file binary_file_access.f90.
References set_parallel_file_name::add_null_character(), m_precision::kchara, t_binary_io_buffer::link_text_buffer_for_bin(), and t_binary_io_buffer::unlink_text_buffer_for_bin().
rawread_chara_f()
subroutine binary_file_access::rawread_chara_f (integer, intent(in) len_buf, character(len=1), dimension(len_buf), intent(in), target textbuf, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 231 of file binary_file_access.f90.
References t_binary_io_buffer::link_text_buffer_for_bin(), and t_binary_io_buffer::unlink_text_buffer_for_bin().
rawread_int4_f()
subroutine binary_file_access::rawread_int4_f (integer, intent(in) num, integer, dimension(num), intent(inout), target int4_dat, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 213 of file binary_file_access.f90.
References t_binary_io_buffer::link_int4_buffer_for_bin(), and t_binary_io_buffer::unlink_int4_buffer_for_bin().
rawread_int8_f()
subroutine binary_file_access::rawread_int8_f (integer, intent(in) num, integer(kind = kint_gl), dimension(num), intent(inout) int8_dat, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 196 of file binary_file_access.f90.
References t_binary_io_buffer::link_int8_buffer_for_bin(), and t_binary_io_buffer::unlink_int8_buffer_for_bin().
rawread_real_f()
subroutine binary_file_access::rawread_real_f (integer, intent(in) num, real(kind = kreal), dimension(num), intent(inout), target data, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 179 of file binary_file_access.f90.
References t_binary_io_buffer::link_real_buffer_for_bin(), and t_binary_io_buffer::unlink_real_buffer_for_bin().
rawseek_go_fwd_f()
subroutine binary_file_access::rawseek_go_fwd_f (integer, intent(in) ioffset, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 324 of file binary_file_access.f90.
rawwrite_chara_f()
subroutine binary_file_access::rawwrite_chara_f (integer, intent(in) len_buf, character(len=1), dimension(len_buf), intent(in), target textbuf, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 306 of file binary_file_access.f90.
References t_binary_io_buffer::link_text_buffer_for_bin(), and t_binary_io_buffer::unlink_text_buffer_for_bin().
rawwrite_int4_f()
subroutine binary_file_access::rawwrite_int4_f (integer, intent(in) num, integer(kind = 4), dimension(num), intent(in), target int4_dat, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 288 of file binary_file_access.f90.
References t_binary_io_buffer::link_int4_buffer_for_bin(), and t_binary_io_buffer::unlink_int4_buffer_for_bin().
rawwrite_int8_f()
subroutine binary_file_access::rawwrite_int8_f (integer, intent(in) num, integer(kind = kint_gl), dimension(num), intent(in) int8_dat, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 270 of file binary_file_access.f90.
References t_binary_io_buffer::link_int8_buffer_for_bin(), and t_binary_io_buffer::unlink_int8_buffer_for_bin().
rawwrite_real_f()
subroutine binary_file_access::rawwrite_real_f (integer, intent(in) num, real(kind = kreal), dimension(num), intent(in), target data, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 253 of file binary_file_access.f90.
References t_binary_io_buffer::link_real_buffer_for_bin(), and t_binary_io_buffer::unlink_real_buffer_for_bin().