CALYPSO: normei Module Reference
normei Module Reference
Functions/Subroutines
double precision function setei (l1, m1, l2, m2, l3, m3)
double precision function, private leades (m2, l2, m3, l3, gg)
Function/Subroutine Documentation
leades()
double precision function, private normei::leades (integer(kind = kint), intent(in) m2, integer(kind = kint), intent(in) l2, integer(kind = kint), intent(in) m3, integer(kind = kint), intent(in) l3, real(kind = kreal), dimension(4), intent(in) gg) private
Definition at line 121 of file normei.f90.
References m_constants::half, m_constants::ione, and m_constants::two.
Referenced by setei().
setei()
double precision function normei::setei (integer(kind = kint), intent(in) l1, integer(kind = kint), intent(in) m1, integer(kind = kint), intent(in) l2, integer(kind = kint), intent(in) m2, integer(kind = kint), intent(in) l3, integer(kind = kint), intent(in) m3)
Definition at line 72 of file normei.f90.
References normgi::gs(), m_constants::ione, leades(), and m_constants::zero.
Referenced by cal_gaunt_itgs::leadli().