CALYPSO: gzip_file_access Module Reference
gzip_file_access Module Reference
Data Types
interface close_gzfile
interface get_one_line_from_gz
interface gzread_32bit_f
interface gzread_64bit_f
interface gzwrite_f
interface open_ad_gzfile
interface open_rd_gzfile
interface open_wt_gzfile
interface write_compress_txt_nolf
Functions/Subroutines
subroutine open_wt_gzfile_f (gzip_name, zbuf)
subroutine open_ad_gzfile_f (gzip_name, zbuf)
subroutine open_rd_gzfile_f (gzip_name, zbuf)
subroutine close_gzfile_b ()
subroutine get_one_line_text_from_gz (zbuf)
subroutine gz_write_textbuf_no_lf (zbuf)
subroutine gzread_real_f (num, data, zbuf)
subroutine gzread_int8_f (num, int8_dat, zbuf)
subroutine gzread_int4_f (num, int4_dat, zbuf)
subroutine gzread_chara_f (len_buf, textbuf, zbuf)
subroutine gzwrite_real_f (num, data, zbuf)
subroutine gzwrite_int8_f (num, int8_dat, zbuf)
subroutine gzwrite_int4_f (num, int4_dat, zbuf)
subroutine gzwrite_chara_f (len_buf, textbuf, zbuf)
Function/Subroutine Documentation
close_gzfile_b()
subroutine gzip_file_access::close_gzfile_b
Definition at line 179 of file gzip_file_access.f90.
Referenced by skip_gz_comment::close_gzfile_a(), gz_element_file_io_b::gz_input_edge_file_b(), gz_element_file_io_b::gz_input_element_file_b(), gz_element_file_io_b::gz_input_surface_file_b(), gz_element_file_io_b::gz_output_edge_file_b(), gz_element_file_io_b::gz_output_element_file_b(), gz_element_file_io_b::gz_output_surface_file_b(), gz_field_file_io_b::gz_rd_alloc_st_fld_file_b(), gz_field_file_io_b::gz_rd_alloc_st_fld_head_b(), gz_read_psf_binary_file::gz_read_alloc_iso_bin_file(), gz_read_psf_binary_file::gz_read_alloc_psf_bin_file(), gz_read_psf_binary_file::gz_read_alloc_psf_bin_grid(), gz_ucd_field_file_io_b::gz_read_alloc_ucd_2_fld_file_b(), gz_sph_modes_file_io_b::gz_read_geom_rtm_file_b(), gz_sph_modes_file_io_b::gz_read_geom_rtp_file_b(), gz_mesh_file_io_b::gz_read_geometry_size_b(), gz_read_psf_binary_file::gz_read_iso_bin_file(), gz_mesh_file_io_b::gz_read_mesh_file_b(), gz_mesh_file_io_b::gz_read_mesh_geometry_b(), gz_sph_modes_file_io_b::gz_read_modes_rlm_file_b(), gz_mesh_file_io_b::gz_read_node_size_b(), gz_read_psf_binary_file::gz_read_psf_bin_file(), gz_read_psf_binary_file::gz_read_psf_bin_grid(), gz_sph_modes_file_io_b::gz_read_spectr_modes_rj_file_b(), gz_field_file_io_b::gz_read_step_field_file_b(), gz_ucd_field_file_io_b::gz_read_ucd_2_fld_file_b(), gz_sph_modes_file_io_b::gz_write_geom_rtm_file_b(), gz_sph_modes_file_io_b::gz_write_geom_rtp_file_b(), gz_mesh_file_io_b::gz_write_mesh_file_b(), gz_sph_modes_file_io_b::gz_write_modes_rlm_file_b(), gz_sph_modes_file_io_b::gz_write_spectr_modes_rj_file_b(), gz_field_file_io_b::gz_write_step_fld_file_b(), and gz_ucd_field_file_io_b::gz_write_ucd_2_fld_file_b().
get_one_line_text_from_gz()
subroutine gzip_file_access::get_one_line_text_from_gz (type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 188 of file gzip_file_access.f90.
References t_buffer_4_gzip::link_text_buffer_for_zlib(), and t_buffer_4_gzip::unlink_text_buffer_for_zlib().
Referenced by gz_domain_data_io::gz_read_domain_info(), gz_element_connect_io::gz_read_edge_4_element(), gz_element_connect_io::gz_read_element_info(), gz_node_geometry_io::gz_read_geometry_info(), gz_node_geometry_io::gz_read_scalar_in_element(), gz_element_connect_io::gz_read_surface_4_element(), gz_node_geometry_io::gz_read_vector_in_element(), gz_udt_type_data_io::read_alloc_gz_ucd_mesh_data(), gz_spherical_model_io::read_gl_nodes_sph_gz(), gz_field_data_io::read_gz_field_vect(), gz_data_io::read_gz_multi_int(), gz_data_io::read_gz_multi_int8(), gz_data_io::read_gz_multi_real(), gz_rst_data_io_by_fld::read_gz_rst_field_comps(), gz_data_io::read_gz_surf_group(), gz_ucd_data_io::read_gz_ucd_ele_connect(), gz_ucd_data_io::read_gz_ucd_node_data(), gz_ucd_data_io::read_gz_udt_field_data(), gz_ucd_data_io::read_gz_udt_field_name(), gz_ucd_data_io::read_gz_udt_field_num(), gz_ucd_data_io::read_gz_udt_mesh_header(), gz_vtk_data_io::read_gz_vtk_cell_type(), gz_vtk_data_io::read_gz_vtk_connect_data(), gz_vtk_data_io::read_gz_vtk_connect_head(), gz_vtk_data_io::read_gz_vtk_each_field(), gz_vtk_data_io::read_gz_vtk_each_field_head(), gz_vtk_data_io::read_gz_vtk_node_head(), gz_sph_global_1d_idx_io::read_rj_gl_1d_table_gz(), gz_sph_global_1d_idx_io::read_rtp_gl_1d_table_gz(), gz_domain_data_io::read_send_recv_item_gz(), skip_gz_comment::skip_gz_comment_get_nword(), and gz_field_data_io::skip_gz_field_vect().
gz_write_textbuf_no_lf()
subroutine gzip_file_access::gz_write_textbuf_no_lf (type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 203 of file gzip_file_access.f90.
References t_buffer_4_gzip::link_text_buffer_for_zlib(), and t_buffer_4_gzip::unlink_text_buffer_for_zlib().
Referenced by gz_data_io::gz_write_chara_nolf(), gz_domain_data_io::gz_write_domain_info(), gz_element_connect_io::gz_write_edge_4_element(), gz_edge_data_io::gz_write_edge_connection(), gz_edge_data_io::gz_write_edge_geometry(), gz_element_data_io::gz_write_element_comm_table(), gz_element_data_io::gz_write_element_geometry(), gz_element_connect_io::gz_write_element_info(), gz_mesh_data_io::gz_write_filter_geometry(), gz_mesh_data_io::gz_write_geometry_data(), gz_node_geometry_io::gz_write_geometry_info(), gz_mesh_data_io::gz_write_mesh_groups(), gz_node_geometry_io::gz_write_scalar_in_element(), gz_element_connect_io::gz_write_surface_4_element(), gz_surface_data_io::gz_write_surface_connection(), gz_surface_data_io::gz_write_surface_geometry(), gz_node_geometry_io::gz_write_vector_in_element(), gz_sph_modes_grids_data_io::write_geom_rtm_data_gz(), gz_sph_modes_grids_data_io::write_geom_rtp_data_gz(), gz_spherical_model_io::write_gl_nodes_sph_gz(), gz_spherical_model_io::write_gl_resolution_sph_gz(), gz_group_data_io::write_group_data_gz(), gz_data_io::write_gz_comment_string(), gz_field_data_io::write_gz_field_data(), gz_field_data_io::write_gz_field_vect(), gz_data_io::write_gz_multi_int_10i12(), gz_data_io::write_gz_multi_int_10i8(), gz_data_io::write_gz_multi_int_8i16(), gz_vtk_file_io::write_gz_parallel_vtk_file(), gz_field_data_io::write_gz_step_data(), gz_data_io::write_gz_surf_group(), gz_ucd_data_io::write_gz_ucd_field_data(), gz_ucd_data_io::write_gz_ucd_mesh_connect(), gz_ucd_data_io::write_gz_udt_field_header(), gz_ucd_data_io::write_gz_udt_mesh_header(), gz_vtk_data_io::write_gz_vtk_cell_type(), gz_vtk_data_io::write_gz_vtk_connect_data(), gz_vtk_data_io::write_gz_vtk_connect_head(), gz_vtk_data_io::write_gz_vtk_each_field(), gz_vtk_data_io::write_gz_vtk_each_field_head(), gz_vtk_data_io::write_gz_vtk_fields_head(), gz_vtk_data_io::write_gz_vtk_node_head(), gz_sph_modes_grids_data_io::write_modes_rlm_data_gz(), gz_spherical_model_io::write_rank_4_sph_gz(), gz_sph_global_1d_idx_io::write_rj_gl_1d_table_gz(), gz_sph_global_1d_idx_io::write_rtp_gl_1d_table_gz(), gz_domain_data_io::write_send_recv_data_gz(), gz_sph_modes_grids_data_io::write_spectr_modes_rj_data_gz(), and gz_group_data_io::write_surf_group_data_gz().
gzread_chara_f()
subroutine gzip_file_access::gzread_chara_f (integer, intent(in) len_buf, character(len=1), dimension(len_buf), intent(in), target textbuf, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 269 of file gzip_file_access.f90.
References t_buffer_4_gzip::link_text_buffer_for_zlib(), and t_buffer_4_gzip::unlink_text_buffer_for_zlib().
Referenced by gz_binary_io::gz_read_mul_character_b(), and gz_binary_io::gz_read_mul_one_character_b().
gzread_int4_f()
subroutine gzip_file_access::gzread_int4_f (integer, intent(in) num, integer, dimension(num), intent(inout), target int4_dat, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 252 of file gzip_file_access.f90.
References t_buffer_4_gzip::link_int4_buffer_for_zlib(), and t_buffer_4_gzip::unlink_int4_buffer_for_zlib().
Referenced by gz_binary_io::gz_read_endian_flag().
gzread_int8_f()
subroutine gzip_file_access::gzread_int8_f (integer, intent(in) num, integer(kind = kint_gl), dimension(num), intent(inout) int8_dat, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 235 of file gzip_file_access.f90.
References t_buffer_4_gzip::link_int8_buffer_for_zlib(), and t_buffer_4_gzip::unlink_int8_buffer_for_zlib().
Referenced by gz_binary_io::gz_read_mul_int8_b().
gzread_real_f()
subroutine gzip_file_access::gzread_real_f (integer, intent(in) num, real(kind = kreal), dimension(num), intent(inout), target data, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 218 of file gzip_file_access.f90.
References t_buffer_4_gzip::link_real_buffer_for_zlib(), and t_buffer_4_gzip::unlink_real_buffer_for_zlib().
Referenced by gz_binary_io::gz_read_1d_vector_b().
gzwrite_chara_f()
subroutine gzip_file_access::gzwrite_chara_f (integer, intent(in) len_buf, character(len=1), dimension(len_buf), intent(in), target textbuf, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 341 of file gzip_file_access.f90.
References t_buffer_4_gzip::link_text_buffer_for_zlib(), and t_buffer_4_gzip::unlink_text_buffer_for_zlib().
Referenced by gz_binary_io::gz_write_mul_character_b(), and gz_binary_io::gz_write_mul_one_character_b().
gzwrite_int4_f()
subroutine gzip_file_access::gzwrite_int4_f (integer, intent(in) num, integer(kind = 4), dimension(num), intent(in), target int4_dat, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 324 of file gzip_file_access.f90.
References t_buffer_4_gzip::link_int4_buffer_for_zlib(), and t_buffer_4_gzip::unlink_int4_buffer_for_zlib().
Referenced by gz_binary_io::gz_write_endian_flag().
gzwrite_int8_f()
subroutine gzip_file_access::gzwrite_int8_f (integer, intent(in) num, integer(kind = kint_gl), dimension(num), intent(in) int8_dat, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 307 of file gzip_file_access.f90.
References t_buffer_4_gzip::link_int8_buffer_for_zlib(), and t_buffer_4_gzip::unlink_int8_buffer_for_zlib().
Referenced by gz_binary_io::gz_write_mul_int8_b().
gzwrite_real_f()
subroutine gzip_file_access::gzwrite_real_f (integer, intent(in) num, real(kind = kreal), dimension(num), intent(in), target data, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 290 of file gzip_file_access.f90.
References t_buffer_4_gzip::link_real_buffer_for_zlib(), and t_buffer_4_gzip::unlink_real_buffer_for_zlib().
Referenced by gz_binary_io::gz_write_1d_vector_b().
open_ad_gzfile_f()
subroutine gzip_file_access::open_ad_gzfile_f (character(len = kchara), intent(in) gzip_name, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 145 of file gzip_file_access.f90.
References set_parallel_file_name::add_null_character(), m_precision::kchara, t_buffer_4_gzip::link_text_buffer_for_zlib(), and t_buffer_4_gzip::unlink_text_buffer_for_zlib().
Referenced by skip_gz_comment::open_ad_gzfile_a().
open_rd_gzfile_f()
subroutine gzip_file_access::open_rd_gzfile_f (character(len = kchara), intent(in) gzip_name, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 162 of file gzip_file_access.f90.
References set_parallel_file_name::add_null_character(), m_precision::kchara, t_buffer_4_gzip::link_text_buffer_for_zlib(), and t_buffer_4_gzip::unlink_text_buffer_for_zlib().
Referenced by skip_gz_comment::open_rd_gzfile_a(), and gz_binary_io::open_rd_gzfile_b().
open_wt_gzfile_f()
subroutine gzip_file_access::open_wt_gzfile_f (character(len = kchara), intent(in) gzip_name, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 128 of file gzip_file_access.f90.
References set_parallel_file_name::add_null_character(), m_precision::kchara, t_buffer_4_gzip::link_text_buffer_for_zlib(), and t_buffer_4_gzip::unlink_text_buffer_for_zlib().
Referenced by skip_gz_comment::open_wt_gzfile_a(), and gz_binary_io::open_wt_gzfile_b().