CALYPSO: t_sph_mhd_monitor_data_io Module Reference
t_sph_mhd_monitor_data_io Module Reference
I/O routines for mean square and averaga data.
Data Types
type sph_mhd_monitor_data
Functions/Subroutines
subroutine open_sph_vol_rms_file_mhd (sph, ipol, rj_fld, monitor)
subroutine output_rms_sph_mhd_control (time_d, SPH_MHD, sph_MHD_bc, leg, monitor)
subroutine init_rms_4_sph_spectr_4_mhd (sph, rj_fld, monitor)
Detailed Description
I/O routines for mean square and averaga data.
      subroutine open_sph_vol_rms_file_mhd(sph, ipol, rj_fld, monitor)
      subroutine output_rms_sph_mhd_control                           &
     &         (time_d, SPH_MHD, sph_MHD_bc, leg, monitor)
      subroutine init_rms_4_sph_spectr_4_mhd(sph, rj_fld, monitor)
        type(energy_label_param), intent(in) :: ene_labels
        type(time_data), intent(in) :: time_d
        type(sph_boundary_type), intent(in) :: sph_bc_U
        type(legendre_4_sph_trans), intent(in) :: leg
        type(SPH_mesh_field_data), intent(in) :: SPH_MHD
        type(sph_mhd_monitor_data), intent(inout) :: monitor
Function/Subroutine Documentation
init_rms_4_sph_spectr_4_mhd()
subroutine t_sph_mhd_monitor_data_io::init_rms_4_sph_spectr_4_mhd (type(sph_grids), intent(in) sph, type(phys_data), intent(inout) rj_fld, type(sph_mhd_monitor_data), intent(inout) monitor)
Definition at line 166 of file t_sph_mhd_monitor_data_IO.f90.
References m_machine_parameter::iflag_debug, t_energy_label_parameters::init_energy_labels_base(), and cal_rms_fields_by_sph::init_rms_4_sph_spectr().
Referenced by open_sph_vol_rms_file_mhd().
open_sph_vol_rms_file_mhd()
subroutine t_sph_mhd_monitor_data_io::open_sph_vol_rms_file_mhd (type(sph_grids), intent(in) sph, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld, type(sph_mhd_monitor_data), intent(inout) monitor)
Definition at line 80 of file t_sph_mhd_monitor_data_IO.f90.
References calypso_mpi::calypso_mpi_abort(), calypso_mpi::calypso_mpi_barrier(), calypso_mpi_int::calypso_mpi_bcast_one_int(), mpi_sph_gauss_coefs_io::check_gauss_coefs_num(), output_sph_m_square_file::check_sph_vol_ms_file(), m_error_ids::ierr_file, m_machine_parameter::iflag_debug, pickup_gauss_coefficients::init_gauss_coefs_4_monitor(), init_rms_4_sph_spectr_4_mhd(), pickup_sph_spectr_data::init_sph_spec_4_monitor(), and calypso_mpi::my_rank.
Referenced by sph_analyzer_snap_w_psf::sph_init_sph_snap_psf().
output_rms_sph_mhd_control()
subroutine t_sph_mhd_monitor_data_io::output_rms_sph_mhd_control (type(time_data), intent(in) time_d, type(sph_mesh_field_data), intent(in) SPH_MHD, type(sph_mhd_boundary_data), intent(in) sph_MHD_bc, type(legendre_4_sph_trans), intent(in) leg, type(sph_mhd_monitor_data), intent(inout) monitor)
Definition at line 133 of file t_sph_mhd_monitor_data_IO.f90.
References cal_write_sph_monitor_data::cal_sph_monitor_data(), and cal_write_sph_monitor_data::output_sph_monitor_data().
Referenced by sph_analyzer_snap_w_psf::sph_analyze_snap_psf().