CALYPSO: m_geometry_constants Module Reference
m_geometry_constants Module Reference
Constants for geometry data.
Variables
integer(kind=kint), parameter iflag_certecian = 0
integer flag for certecian coordinate \((x,y,z) \)
integer(kind=kint), parameter iflag_spherical = 1
integer flag for spherical coordinate \((r,\theta,\phi) \)
integer(kind=kint), parameter iflag_cylindrical = 2
integer flag for Cylindrical coordinate \((s,\phi,z) \)
integer(kind=kint), parameter num_t_lag = 27
number of nodes in each Lagrange element
integer(kind=kint), parameter num_t_quad = 20
number of nodes in each quadrature element
integer(kind=kint), parameter num_t_linear = 8
number of nodes in each linear element
integer(kind=kint), parameter num_lag_sf = 9
number of nodes in each Lagrange surface
integer(kind=kint), parameter num_quad_sf = 8
number of nodes in each quadrature surface
integer(kind=kint), parameter num_linear_sf = 4
number of nodes in each linear surface
integer(kind=kint), parameter num_triangle = 3
number of nodes in each triangle
integer(kind=kint), parameter num_quad_edge = 3
number of nodes in quadrature edge
integer(kind=kint), parameter num_linear_edge = 2
number of nodes in linear edge
integer(kind=kint), parameter nsurf_4_ele = 6
number of surface in each element
integer(kind=kint), parameter nedge_4_ele = 12
number of edge in each element
integer(kind=kint), parameter nedge_4_surf = 4
number of edge in each surface
integer(kind=kint), parameter nend_4_edge = 2
number of end point for edge
integer(kind=kint), dimension(4, 6), parameter node_on_sf_4 = reshape((/ 1, 5, 8, 4, 2, 3, 7, 6, 1, 2, 6, 5, 4, 8, 7, 3, 1, 4, 3, 2, 5, 6, 7, 8/), shape=(/4,6/))
local node id for surface in one element for linear element (node index,surface index)
integer(kind=kint), dimension(4, 6), parameter node_on_sf_n_4 = reshape((/ 2, 6, 7, 3, 1, 4, 8, 5, 4, 3, 7, 8, 1, 5, 6, 2, 5, 8, 7, 6, 1, 2, 3, 4/), shape=(/4,6/))
local node id for opposit surface in one element for linear element (node index,surface index)
integer(kind=kint), dimension(8, 6), parameter node_on_sf_8 = reshape((/ 1, 5, 8, 4, 17, 16, 20, 12, 2, 3, 7, 6, 10, 19, 14, 18, 1, 2, 6, 5, 9, 18, 13, 17, 4, 8, 7, 3, 20, 15, 19, 11, 1, 4, 3, 2, 12, 11, 10, 9, 5, 6, 7, 8, 13, 14, 15, 16/), shape=(/8,6/))
local node id for surface in one element for quadrature element (node index,surface index)
integer(kind=kint), dimension(8, 6), parameter node_on_sf_n_8 = reshape((/ 2, 6, 7, 3, 18, 14, 19, 10, 1, 4, 8, 5, 12, 20, 16, 17, 4, 3, 7, 8, 11, 19, 15, 20, 1, 5, 6, 2, 17, 13, 18, 9, 5, 8, 7, 6, 16, 15, 14, 13, 1, 2, 3, 4, 9, 10, 11, 12/), shape=(/8,6/))
local node id for opposit surface in one element for quadrature element (node index,surface index)
integer(kind=kint), dimension(9, 6), parameter node_on_sf_9 = reshape((/ 1, 5, 8, 4, 17, 16, 20, 12, 21, 2, 3, 7, 6, 10, 19, 14, 18, 22, 1, 2, 6, 5, 9, 18, 13, 17, 23, 4, 8, 7, 3, 20, 15, 19, 11, 24, 1, 4, 3, 2, 12, 11, 10, 9, 25, 5, 6, 7, 8, 13, 14, 15, 16, 26/), shape=(/9,6/))
local node id for surface in one element for lagrande element (node index,surface index)
integer(kind=kint), dimension(9, 6), parameter node_on_sf_n_9 = reshape((/ 2, 6, 7, 3, 18, 14, 19, 10, 22, 1, 4, 8, 5, 12, 20, 16, 17, 21, 4, 3, 7, 8, 11, 19, 15, 20, 24, 1, 5, 6, 2, 17, 13, 18, 9, 23, 5, 8, 7, 6, 16, 15, 14, 13, 26, 1, 2, 3, 4, 9, 10, 11, 12, 25/), shape=(/9,6/))
local node id for opposit surface in one element for lagrande element (node index,surface index)
integer(kind=kint), dimension(2, 12), parameter node_on_edge_l = reshape((/ 1, 2, 2, 3, 4, 3, 1, 4, 5, 6, 6, 7, 8, 7, 5, 8, 1, 5, 2, 6, 3, 7, 4, 8/), shape=(/2,12/))
local node id for edge in one element for linear element (node index,edge index)
integer(kind=kint), dimension(3, 12), parameter node_on_edge_q = reshape((/ 1, 9, 2, 2, 10, 3, 4, 11, 3, 1, 12, 4, 5, 13, 6, 6, 14, 7, 8, 15, 7, 5, 16, 8, 1, 17, 5, 2, 18, 6, 3, 19, 7, 4, 20, 8/), shape=(/3,12/))
local node id for edge in one element for quadrature element (node index,edge index)
integer(kind=kint), dimension(2, 6), parameter ishape_dir_surf = reshape((/ 3, 2, 2, 3, 1, 3, 3, 1, 2, 1, 1, 2/), shape=(/2,6/))
local surface axis in one element (surface index)
integer(kind=kint), dimension(2, 4), parameter node_on_edge_sf_l = reshape((/ 1, 2, 2, 3, 4, 3, 1, 4/), shape=(/2,4/))
local node id for edge in one surface for linear element (node index,edge index)
integer(kind=kint), dimension(3, 4), parameter node_on_edge_sf_q = reshape((/ 1, 5, 2, 2, 6, 3, 4, 7, 3, 1, 8, 4/), shape=(/3,4/))
local node id for edge in one surface for quadrature element (node index,edge index)
integer(kind=kint), dimension(12), parameter ishape_dir_edge = (/ 1, 2, 1, 2, 1, 2, 1, 2, 3, 3, 3, 3/)
local edge direction in one element (edge index)
Detailed Description
Constants for geometry data.
Variable Documentation
iflag_certecian
integer(kind=kint), parameter m_geometry_constants::iflag_certecian = 0
integer flag for certecian coordinate \((x,y,z) \)
Definition at line 17 of file m_geometry_constants.f90.
iflag_cylindrical
integer(kind=kint), parameter m_geometry_constants::iflag_cylindrical = 2
integer flag for Cylindrical coordinate \((s,\phi,z) \)
Definition at line 21 of file m_geometry_constants.f90.
Referenced by sel_comp_labels_by_coord::sel_coord_tensor_comp_labels(), and sel_comp_labels_by_coord::sel_coord_vector_comp_labels().
iflag_spherical
integer(kind=kint), parameter m_geometry_constants::iflag_spherical = 1
integer flag for spherical coordinate \((r,\theta,\phi) \)
Definition at line 19 of file m_geometry_constants.f90.
Referenced by sel_comp_labels_by_coord::sel_coord_tensor_comp_labels(), and sel_comp_labels_by_coord::sel_coord_vector_comp_labels().
ishape_dir_edge
integer (kind = kint), dimension(12), parameter m_geometry_constants::ishape_dir_edge = (/ 1, 2, 1, 2, 1, 2, 1, 2, 3, 3, 3, 3/)
local edge direction in one element (edge index)
Definition at line 163 of file m_geometry_constants.f90.
ishape_dir_surf
integer (kind = kint), dimension(2,6), parameter m_geometry_constants::ishape_dir_surf = reshape((/ 3, 2, 2, 3, 1, 3, 3, 1, 2, 1, 1, 2/), shape=(/2,6/))
local surface axis in one element (surface index)
Definition at line 140 of file m_geometry_constants.f90.
nedge_4_ele
integer(kind=kint), parameter m_geometry_constants::nedge_4_ele = 12
number of edge in each element
Definition at line 48 of file m_geometry_constants.f90.
Referenced by t_edge_data::alloc_edge_4_ele(), t_edge_data::alloc_inod_in_edge(), check_geometries::check_edge_hexa_data(), const_edge_data::construct_edge_data(), set_edge_data_4_io::copy_edge_connect_from_io(), set_edge_data_4_io::copy_edge_connect_to_io(), set_local_id_table_4_1ele::copy_inod_in_edge(), set_edge_hash_by_ele::count_edge_hash_4_ele(), set_edge_hash_by_ele::count_part_edge_hash_4_ele(), set_connects_4_ele_group::set_edge_4_ele_group(), set_edge_hash_by_ele::set_edge_hash_4_ele(), set_edge_data_by_sf::set_edges_connect_4_ele(), and set_edge_hash_by_ele::set_part_edge_hash_4_ele().
nedge_4_surf
integer(kind=kint), parameter m_geometry_constants::nedge_4_surf = 4
number of edge in each surface
Definition at line 50 of file m_geometry_constants.f90.
Referenced by t_edge_data::alloc_edge_connect(), t_viewer_mesh::alloc_edge_data_4_sf(), t_edge_data::alloc_inod_in_edge(), check_geometries::check_edge_data(), const_edge_4_viewer::construct_edge_4_viewer(), set_edge_data_4_io::copy_edge_connect_from_io(), set_edge_data_4_io::copy_edge_connect_to_io(), set_edge_list_for_psf::mark_edge_list_4_psf(), set_connects_4_surf_group::set_edge_4_surf_group(), set_edge_hash_by_sf::set_edge_hash_4_sf(), set_edge_data_by_ele::set_edges_connect_4_sf(), renumber_para_viewer_mesh::set_global_edge_info_4_viewer(), and set_edge_hash_by_sf::set_part_edge_hash_4_sf().
nend_4_edge
integer(kind=kint), parameter m_geometry_constants::nend_4_edge = 2
number of end point for edge
Definition at line 52 of file m_geometry_constants.f90.
node_on_edge_l
integer (kind=kint), dimension(2,12), parameter m_geometry_constants::node_on_edge_l = reshape((/ 1, 2, 2, 3, 4, 3, 1, 4, 5, 6, 6, 7, 8, 7, 5, 8, 1, 5, 2, 6, 3, 7, 4, 8/), shape=(/2,12/))
local node id for edge in one element for linear element (node index,edge index)
Definition at line 123 of file m_geometry_constants.f90.
Referenced by set_local_id_table_4_1ele::copy_inod_in_edge(), set_edge_hash_by_ele::count_edge_hash_4_ele(), set_edge_hash_by_ele::count_part_edge_hash_4_ele(), set_edge_hash_by_ele::set_2nodes_id_on_edge(), set_edge_hash_by_ele::set_edge_hash_4_ele(), set_edge_data_by_sf::set_edges_connect_4_ele(), and set_edge_hash_by_ele::set_part_edge_hash_4_ele().
node_on_edge_q
integer (kind=kint), dimension(3,12), parameter m_geometry_constants::node_on_edge_q = reshape((/ 1, 9, 2, 2, 10, 3, 4, 11, 3, 1, 12, 4, 5, 13, 6, 6, 14, 7, 8, 15, 7, 5, 16, 8, 1, 17, 5, 2, 18, 6, 3, 19, 7, 4, 20, 8/), shape=(/3,12/))
local node id for edge in one element for quadrature element (node index,edge index)
Definition at line 132 of file m_geometry_constants.f90.
Referenced by set_local_id_table_4_1ele::copy_inod_in_edge().
node_on_edge_sf_l
integer (kind=kint), dimension(2,4), parameter m_geometry_constants::node_on_edge_sf_l = reshape((/ 1, 2, 2, 3, 4, 3, 1, 4/), shape=(/2,4/))
local node id for edge in one surface for linear element (node index,edge index)
Definition at line 149 of file m_geometry_constants.f90.
Referenced by set_local_id_table_4_1ele::copy_inod_in_edge(), set_edge_hash_by_sf::mark_all_edges_by_sf(), set_edge_hash_by_sf::set_edge_hash_4_sf(), set_edge_data_by_ele::set_edges_connect_4_sf(), and set_edge_hash_by_sf::set_part_edge_hash_4_sf().
node_on_edge_sf_q
integer (kind=kint), dimension(3,4), parameter m_geometry_constants::node_on_edge_sf_q = reshape((/ 1, 5, 2, 2, 6, 3, 4, 7, 3, 1, 8, 4/), shape=(/3,4/))
local node id for edge in one surface for quadrature element (node index,edge index)
Definition at line 156 of file m_geometry_constants.f90.
Referenced by set_local_id_table_4_1ele::copy_inod_in_edge().
node_on_sf_4
integer (kind=kint), dimension(4,6), parameter m_geometry_constants::node_on_sf_4 = reshape((/ 1, 5, 8, 4, 2, 3, 7, 6, 1, 2, 6, 5, 4, 8, 7, 3, 1, 4, 3, 2, 5, 6, 7, 8/), shape=(/4,6/))
local node id for surface in one element for linear element (node index,surface index)
Definition at line 58 of file m_geometry_constants.f90.
Referenced by set_surface_hash::count_part_surface_hash(), set_surface_hash::count_surface_hash(), mark_surf_hash::set_4nodes_id_on_surf(), set_surface_hash::set_part_surf_hash(), set_psf_patch_4_by_surf_grp::set_patch_4_grp(), set_surface_hash::set_surf_hash(), and set_surface_data::set_surf_rotation_flag().
node_on_sf_8
integer (kind=kint), dimension(8,6), parameter m_geometry_constants::node_on_sf_8 = reshape((/ 1, 5, 8, 4, 17, 16, 20, 12, 2, 3, 7, 6, 10, 19, 14, 18, 1, 2, 6, 5, 9, 18, 13, 17, 4, 8, 7, 3, 20, 15, 19, 11, 1, 4, 3, 2, 12, 11, 10, 9, 5, 6, 7, 8, 13, 14, 15, 16/), shape=(/8,6/))
local node id for surface in one element for quadrature element (node index,surface index)
Definition at line 75 of file m_geometry_constants.f90.
node_on_sf_9
integer (kind=kint), dimension(9,6), parameter m_geometry_constants::node_on_sf_9 = reshape((/ 1, 5, 8, 4, 17, 16, 20, 12, 21, 2, 3, 7, 6, 10, 19, 14, 18, 22, 1, 2, 6, 5, 9, 18, 13, 17, 23, 4, 8, 7, 3, 20, 15, 19, 11, 24, 1, 4, 3, 2, 12, 11, 10, 9, 25, 5, 6, 7, 8, 13, 14, 15, 16, 26/), shape=(/9,6/))
local node id for surface in one element for lagrande element (node index,surface index)
Definition at line 98 of file m_geometry_constants.f90.
Referenced by set_local_id_table_4_1ele::set_inod_in_surf().
node_on_sf_n_4
integer (kind=kint), dimension(4,6), parameter m_geometry_constants::node_on_sf_n_4 = reshape((/ 2, 6, 7, 3, 1, 4, 8, 5, 4, 3, 7, 8, 1, 5, 6, 2, 5, 8, 7, 6, 1, 2, 3, 4/), shape=(/4,6/))
local node id for opposit surface in one element for linear element (node index,surface index)
Definition at line 67 of file m_geometry_constants.f90.
node_on_sf_n_8
integer (kind=kint), dimension(8,6), parameter m_geometry_constants::node_on_sf_n_8 = reshape((/ 2, 6, 7, 3, 18, 14, 19, 10, 1, 4, 8, 5, 12, 20, 16, 17, 4, 3, 7, 8, 11, 19, 15, 20, 1, 5, 6, 2, 17, 13, 18, 9, 5, 8, 7, 6, 16, 15, 14, 13, 1, 2, 3, 4, 9, 10, 11, 12/), shape=(/8,6/))
local node id for opposit surface in one element for quadrature element (node index,surface index)
Definition at line 87 of file m_geometry_constants.f90.
node_on_sf_n_9
integer (kind=kint), dimension(9,6), parameter m_geometry_constants::node_on_sf_n_9 = reshape((/ 2, 6, 7, 3, 18, 14, 19, 10, 22, 1, 4, 8, 5, 12, 20, 16, 17, 21, 4, 3, 7, 8, 11, 19, 15, 20, 24, 1, 5, 6, 2, 17, 13, 18, 9, 23, 5, 8, 7, 6, 16, 15, 14, 13, 26, 1, 2, 3, 4, 9, 10, 11, 12, 25/), shape=(/9,6/))
local node id for opposit surface in one element for lagrande element (node index,surface index)
Definition at line 110 of file m_geometry_constants.f90.
Referenced by set_local_id_table_4_1ele::set_inod_in_surf().
nsurf_4_ele
integer(kind=kint), parameter m_geometry_constants::nsurf_4_ele = 6
number of surface in each element
Definition at line 46 of file m_geometry_constants.f90.
Referenced by t_surface_data::allocate_inod_in_surf(), t_surface_data::allocate_surface_connect_type(), set_norm_nod_4_surf_grp::cal_surf_grp_norm_node(), check_geometries::check_surface_data(), const_surface_data::const_ele_list_4_surface(), const_surface_data::construct_surface_data(), set_surface_data_4_io::copy_surf_connect_from_io(), set_surface_data_4_io::copy_surf_connect_to_io(), set_surface_data::count_part_surface(), set_surface_hash::count_part_surface_hash(), set_surface_hash::count_surface_hash(), set_local_id_table_4_1ele::set_inod_in_surf(), set_surface_hash::set_part_surf_hash(), set_connects_4_ele_group::set_surf_4_ele_group(), and set_surface_hash::set_surf_hash().
num_lag_sf
integer(kind=kint), parameter m_geometry_constants::num_lag_sf = 9
number of nodes in each Lagrange surface
Definition at line 32 of file m_geometry_constants.f90.
Referenced by set_surface_data_4_io::copy_surf_connect_to_io(), const_node_list_4_viewer::mark_node_4_domain_viewer(), const_node_list_4_viewer::mark_node_4_ele_grp_viewer(), const_node_list_4_viewer::mark_node_4_surf_grp_viewer(), set_nnod_4_ele_by_type::s_set_nnod_4_ele_by_type(), set_nnod_4_ele_by_type::set_3d_nnod_4_sfed_by_ele(), and cal_mesh_position::set_center_of_surface().
num_linear_edge
integer(kind=kint), parameter m_geometry_constants::num_linear_edge = 2
number of nodes in linear edge
Definition at line 43 of file m_geometry_constants.f90.
Referenced by psf_global_nod_id::const_edge_comm_table_4_psf(), set_edge_data_4_io::copy_edge_connect_to_io(), set_nnod_4_ele_by_type::linear_eletype_from_num(), ucd_data_to_buffer::nnod_ele_by_ucd_eletype(), set_nnod_4_ele_by_type::s_set_nnod_4_ele_by_type(), set_nnod_4_ele_by_type::set_3d_nnod_4_sfed_by_ele(), cal_mesh_position::set_center_of_edge(), ucd_data_to_buffer::ucd_eletype(), and vtk_data_to_buffer::vtk_cell_type().
num_linear_sf
integer(kind=kint), parameter m_geometry_constants::num_linear_sf = 4
number of nodes in each linear surface
Definition at line 36 of file m_geometry_constants.f90.
Referenced by set_surface_data_4_io::copy_surf_connect_to_io(), set_nnod_4_ele_by_type::linear_eletype_from_num(), set_nnod_4_ele_by_type::s_set_nnod_4_ele_by_type(), set_nnod_4_ele_by_type::set_3d_nnod_4_sfed_by_ele(), and cal_mesh_position::set_center_of_surface().
num_quad_edge
integer(kind=kint), parameter m_geometry_constants::num_quad_edge = 3
number of nodes in quadrature edge
Definition at line 41 of file m_geometry_constants.f90.
Referenced by set_edge_data_4_io::copy_edge_connect_to_io(), set_nnod_4_ele_by_type::s_set_nnod_4_ele_by_type(), set_nnod_4_ele_by_type::set_3d_nnod_4_sfed_by_ele(), and cal_mesh_position::set_center_of_edge().
num_quad_sf
integer(kind=kint), parameter m_geometry_constants::num_quad_sf = 8
number of nodes in each quadrature surface
Definition at line 34 of file m_geometry_constants.f90.
Referenced by set_surface_data_4_io::copy_surf_connect_to_io(), set_nnod_4_ele_by_type::s_set_nnod_4_ele_by_type(), set_nnod_4_ele_by_type::set_3d_nnod_4_sfed_by_ele(), and cal_mesh_position::set_center_of_surface().
num_t_lag
integer(kind=kint), parameter m_geometry_constants::num_t_lag = 27
number of nodes in each Lagrange element
Definition at line 25 of file m_geometry_constants.f90.
Referenced by m_node_quad_2_linear_sf::allocate_quad4_2_linear(), set_nnod_4_ele_by_type::s_set_nnod_4_ele_by_type(), set_nnod_4_ele_by_type::set_3d_nnod_4_sfed_by_ele(), cal_mesh_position::set_center_of_element(), set_nnod_4_ele_by_type::set_cube_eletype_from_num(), and set_nnod_4_ele_by_type::set_nnod_4_ele_by_eletype().
num_t_linear
integer(kind=kint), parameter m_geometry_constants::num_t_linear = 8
number of nodes in each linear element
Definition at line 29 of file m_geometry_constants.f90.
Referenced by m_node_quad_2_linear_sf::allocate_quad4_2_linear(), set_sph_local_element::count_local_elements_sph_mesh(), set_nnod_4_ele_by_type::linear_eletype_from_num(), ucd_data_to_buffer::nnod_ele_by_ucd_eletype(), set_nnod_4_ele_by_type::s_set_nnod_4_ele_by_type(), set_nnod_4_ele_by_type::set_3d_nnod_4_sfed_by_ele(), cal_mesh_position::set_center_of_element(), set_nnod_4_ele_by_type::set_cube_eletype_from_num(), set_nnod_4_ele_by_type::set_nnod_4_ele_by_eletype(), ucd_data_to_buffer::ucd_eletype(), and vtk_data_to_buffer::vtk_cell_type().
num_t_quad
integer(kind=kint), parameter m_geometry_constants::num_t_quad = 20
number of nodes in each quadrature element
Definition at line 27 of file m_geometry_constants.f90.
Referenced by m_node_quad_2_linear_sf::allocate_quad4_2_linear(), set_nnod_4_ele_by_type::s_set_nnod_4_ele_by_type(), set_nnod_4_ele_by_type::set_3d_nnod_4_sfed_by_ele(), cal_mesh_position::set_center_of_element(), set_nnod_4_ele_by_type::set_cube_eletype_from_num(), set_nnod_4_ele_by_type::set_nnod_4_ele_by_eletype(), and vtk_data_to_buffer::vtk_cell_type().
num_triangle
integer(kind=kint), parameter m_geometry_constants::num_triangle = 3
number of nodes in each triangle
Definition at line 38 of file m_geometry_constants.f90.
Referenced by m_node_quad_2_linear_sf::allocate_quad4_2_linear_tri(), m_node_quad_2_linear_sf::allocate_quad8_2_linear_tri(), m_node_quad_2_linear_sf::allocate_quad9_2_linear_tri(), set_patches_for_psf::count_iso_patches(), set_patches_for_psf::count_psf_patches(), set_nnod_4_ele_by_type::linear_eletype_from_num(), ucd_data_to_buffer::nnod_ele_by_ucd_eletype(), set_patches_for_psf::set_iso_patches(), set_patches_for_psf::set_psf_patches(), t_psf_case_table::set_psf_table_4_each_case(), ucd_data_to_buffer::ucd_eletype(), and vtk_data_to_buffer::vtk_cell_type().