CALYPSO: mesh_data_io_b Module Reference
mesh_data_io_b Module Reference
Routines for Binary mesh data IO.
Functions/Subroutines
subroutine write_geometry_data_b (id_rank, mesh_IO, bbuf)
subroutine write_mesh_groups_b (mesh_group_IO, bbuf)
subroutine write_filter_geometry_b (id_rank, comm_IO, nod_IO, bbuf)
subroutine read_num_node_b (id_rank, bbuf, mesh_IO)
subroutine read_num_node_ele_b (id_rank, bbuf, mesh_IO)
subroutine read_geometry_data_b (id_rank, bbuf, mesh_IO)
subroutine read_mesh_groups_b (bbuf, mesh_group_IO)
subroutine read_filter_geometry_b (id_rank, bbuf, comm_IO, nod_IO)
Detailed Description
Routines for Binary mesh data IO.
      subroutine write_geometry_data_b(id_rank, mesh_IO, bbuf)
      subroutine write_mesh_groups_b(mesh_group_IO, bbuf)
        type(mesh_geometry), intent(in) :: mesh_IO
        type(mesh_groups), intent(in) ::   mesh_group_IO
        type(binary_IO_buffer), intent(inout) :: bbuf
      subroutine read_num_node_b(id_rank, bbuf, mesh_IO)
      subroutine read_num_node_ele_b(id_rank, bbuf, mesh_IO)
      subroutine read_geometry_data_b(id_rank, bbuf, mesh_IO)
        type(binary_IO_buffer), intent(inout) :: bbuf
        type(mesh_geometry), intent(inout) :: mesh_IO
      subroutine read_mesh_groups_b(bbuf, mesh_group_IO)
        type(binary_IO_buffer), intent(inout) :: bbuf
        type(mesh_geometry), intent(inout) :: mesh_IO
        type(mesh_groups), intent(inout) ::   mesh_group_IO
      subroutine write_filter_geometry_b                              &
     &         (id_rank, comm_IO, nod_IO, bbuf)
        type(binary_IO_buffer), intent(inout) :: bbuf
        type(communication_table), intent(in) :: comm_IO
        type(node_data), intent(in) :: nod_IO
      subroutine read_filter_geometry_b                               &
     &         (id_rank, bbuf, comm_IO, nod_IO)
        type(binary_IO_buffer), intent(inout) :: bbuf
        type(communication_table), intent(inout) :: comm_IO
        type(node_data), intent(inout) :: nod_IO
Function/Subroutine Documentation
read_filter_geometry_b()
subroutine mesh_data_io_b::read_filter_geometry_b (integer, intent(in) id_rank, type(binary_io_buffer), intent(inout) bbuf, type(communication_table), intent(inout) comm_IO, type(node_data), intent(inout) nod_IO)
Definition at line 231 of file mesh_data_IO_b.f90.
References domain_data_io_b::read_domain_info_b(), domain_data_io_b::read_export_data_b(), node_geometry_io_b::read_geometry_info_b(), domain_data_io_b::read_import_data_b(), and node_geometry_io_b::read_number_of_node_b().
read_geometry_data_b()
subroutine mesh_data_io_b::read_geometry_data_b (integer, intent(in) id_rank, type(binary_io_buffer), intent(inout) bbuf, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 179 of file mesh_data_IO_b.f90.
References element_connect_io_b::read_element_info_b(), domain_data_io_b::read_export_data_b(), domain_data_io_b::read_import_data_b(), and read_num_node_ele_b().
Referenced by mesh_file_io_b::read_mesh_file_b(), and mesh_file_io_b::read_mesh_geometry_b().
read_mesh_groups_b()
subroutine mesh_data_io_b::read_mesh_groups_b (type(binary_io_buffer), intent(inout) bbuf, type(mesh_groups), intent(inout) mesh_group_IO)
Definition at line 210 of file mesh_data_IO_b.f90.
References groups_io_b::read_group_data_b(), and groups_io_b::read_surf_grp_data_b().
Referenced by mesh_file_io_b::read_mesh_file_b().
read_num_node_b()
subroutine mesh_data_io_b::read_num_node_b (integer, intent(in) id_rank, type(binary_io_buffer), intent(inout) bbuf, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 133 of file mesh_data_IO_b.f90.
References domain_data_io_b::read_domain_info_b(), and node_geometry_io_b::read_number_of_node_b().
Referenced by mesh_file_io_b::read_node_size_b(), and read_num_node_ele_b().
read_num_node_ele_b()
subroutine mesh_data_io_b::read_num_node_ele_b (integer, intent(in) id_rank, type(binary_io_buffer), intent(inout) bbuf, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 153 of file mesh_data_IO_b.f90.
References node_geometry_io_b::read_geometry_info_b(), read_num_node_b(), and element_connect_io_b::read_number_of_element_b().
Referenced by read_geometry_data_b(), and mesh_file_io_b::read_geometry_size_b().
write_filter_geometry_b()
subroutine mesh_data_io_b::write_filter_geometry_b (integer, intent(in) id_rank, type(communication_table), intent(in) comm_IO, type(node_data), intent(in) nod_IO, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 106 of file mesh_data_IO_b.f90.
References domain_data_io_b::write_domain_info_b(), domain_data_io_b::write_export_data_b(), node_geometry_io_b::write_geometry_info_b(), and domain_data_io_b::write_import_data_b().
write_geometry_data_b()
subroutine mesh_data_io_b::write_geometry_data_b (integer, intent(in) id_rank, type(mesh_geometry), intent(in) mesh_IO, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 58 of file mesh_data_IO_b.f90.
References domain_data_io_b::write_domain_info_b(), element_connect_io_b::write_element_info_b(), domain_data_io_b::write_export_data_b(), node_geometry_io_b::write_geometry_info_b(), and domain_data_io_b::write_import_data_b().
Referenced by mesh_file_io_b::write_mesh_file_b().
write_mesh_groups_b()
subroutine mesh_data_io_b::write_mesh_groups_b (type(mesh_groups), intent(in) mesh_group_IO, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 85 of file mesh_data_IO_b.f90.
References groups_io_b::write_grp_data_b(), and groups_io_b::write_surf_grp_data_b().
Referenced by mesh_file_io_b::write_mesh_file_b().