CALYPSO: gz_field_block_mpi_io_b Module Reference
gz_field_block_mpi_io_b Module Reference
Output merged binary field file using MPI-IO.
Functions/Subroutines
subroutine gz_write_field_time_mpi_b (IO_param_l, i_time_step_IO, time_IO, delta_t_IO)
subroutine gz_write_field_data_mpi_b (IO_param_l, nnod, num_field, ntot_comp, ncomp_field, field_name, istack_merged, d_nod)
subroutine gz_read_step_data_mpi_b (IO_param_l, i_time_step_IO, time_IO, delta_t_IO)
subroutine gz_read_field_header_mpi_b (IO_param_l, nnod, num_field)
Detailed Description
Output merged binary field file using MPI-IO.
      subroutine gz_write_field_time_mpi_b                            &
     &         (IO_param_l, i_time_step_IO, time_IO, delta_t_IO)
      subroutine gz_write_field_data_mpi_b(IO_param_l,                &
     &          nnod, num_field, ntot_comp, field_name, d_nod)
      subroutine gz_read_step_data_mpi_b                              &
     &         (IO_param_l, i_time_step_IO, time_IO, delta_t_IO)
Function/Subroutine Documentation
gz_read_field_header_mpi_b()
subroutine gz_field_block_mpi_io_b::gz_read_field_header_mpi_b (type(calypso_mpi_io_params), intent(inout) IO_param_l, integer(kind = kint_gl), intent(inout) nnod, integer(kind = kint), intent(inout) num_field)
Definition at line 121 of file gz_field_block_MPI_IO_b.f90.
References gz_mpi_binary_head_io::gz_mpi_read_merged_stack_b(), and gz_mpi_binary_datum_io::gz_mpi_read_one_inthead_b().
Referenced by gz_field_file_mpi_io_b::gz_rd_alloc_st_fld_file_mpi_b(), gz_field_file_mpi_io_b::gz_rd_alloc_st_fld_head_mpi_b(), gz_ucd_field_mpi_io_b::gz_rd_alloc_ucd_fld_file_mpi_b(), gz_field_file_mpi_io_b::gz_read_step_field_file_mpi_b(), and gz_ucd_field_mpi_io_b::gz_read_ucd_field_file_mpi_b().
gz_read_step_data_mpi_b()
subroutine gz_field_block_mpi_io_b::gz_read_step_data_mpi_b (type(calypso_mpi_io_params), intent(inout) IO_param_l, integer(kind=kint), intent(inout) i_time_step_IO, real(kind = kreal), intent(inout) time_IO, real(kind = kreal), intent(inout) delta_t_IO)
Definition at line 98 of file gz_field_block_MPI_IO_b.f90.
References gz_mpi_binary_datum_io::gz_mpi_read_one_inthead_b(), gz_mpi_binary_datum_io::gz_mpi_read_one_realhead_b(), and gz_mpi_binary_datum_io::gz_mpi_read_process_id_b().
Referenced by gz_field_file_mpi_io_b::gz_rd_alloc_st_fld_file_mpi_b(), gz_field_file_mpi_io_b::gz_rd_alloc_st_fld_head_mpi_b(), gz_ucd_field_mpi_io_b::gz_rd_alloc_ucd_fld_file_mpi_b(), gz_field_file_mpi_io_b::gz_read_step_field_file_mpi_b(), and gz_ucd_field_mpi_io_b::gz_read_ucd_field_file_mpi_b().
gz_write_field_data_mpi_b()
subroutine gz_field_block_mpi_io_b::gz_write_field_data_mpi_b (type(calypso_mpi_io_params), intent(inout) IO_param_l, integer(kind = kint_gl), intent(in) nnod, integer(kind = kint), intent(in) num_field, integer(kind = kint), intent(in) ntot_comp, integer(kind=kint), dimension(num_field), intent(in) ncomp_field, character(len = kchara), dimension(num_field), intent(in) field_name, integer(kind = kint_gl), dimension(0:nprocs), intent(in) istack_merged, real(kind = kreal), dimension(nnod,ntot_comp), intent(in) d_nod)
Definition at line 61 of file gz_field_block_MPI_IO_b.f90.
References gz_mpi_binary_data_io::gz_mpi_write_2d_vector_b(), gz_mpi_binary_head_io::gz_mpi_write_merged_stack_b(), gz_mpi_binary_head_io::gz_mpi_write_mul_charahead_b(), gz_mpi_binary_head_io::gz_mpi_write_mul_inthead_b(), and gz_mpi_binary_datum_io::gz_mpi_write_one_inthead_b().
Referenced by gz_field_file_mpi_io_b::gz_write_step_fld_file_mpi_b(), and gz_ucd_field_mpi_io_b::gz_write_ucd_field_file_mpi_b().
gz_write_field_time_mpi_b()
subroutine gz_field_block_mpi_io_b::gz_write_field_time_mpi_b (type(calypso_mpi_io_params), intent(inout) IO_param_l, integer(kind=kint), intent(in) i_time_step_IO, real(kind = kreal), intent(in) time_IO, real(kind = kreal), intent(in) delta_t_IO)
Definition at line 38 of file gz_field_block_MPI_IO_b.f90.
References gz_mpi_binary_datum_io::gz_mpi_write_one_inthead_b(), gz_mpi_binary_datum_io::gz_mpi_write_one_realhead_b(), and gz_mpi_binary_datum_io::gz_mpi_write_process_id_b().
Referenced by gz_field_file_mpi_io_b::gz_write_step_fld_file_mpi_b(), gz_ucd_field_mpi_io_b::gz_write_ucd_field_file_mpi_b(), gz_write_udt_file_io_b::gz_write_ucd_file_mpi_b(), and gz_write_udt_file_io_b::gz_write_ucd_phys_mpi_b().