CALYPSO: /home/takumi kera/calypso/src/programs/data_utilities/Rayleigh_link/main_cvt_from_rayleigh_sph.f90 File Reference
main_cvt_from_rayleigh_sph.f90 File Reference
program convert_rayleigh_cvt
Functions/Subroutines
program convert_rayleigh_cvt
Main program for assemble spectr data.
Detailed Description
program convert_rayleigh_cvt
Author
H. Matsui
Date
Programmed by H. Matsui in July 2014
Definition in file main_cvt_from_rayleigh_sph.f90.
Function/Subroutine Documentation
convert_rayleigh_cvt()
program convert_rayleigh_cvt
Main program for assemble spectr data.
Definition at line 9 of file main_cvt_from_rayleigh_sph.f90.
References analyzer_rayleigh_cvt_sph::analyze_cvt_rayleigh_sph(), calypso_mpi::calypso_mpi_finalize(), calypso_mpi::calypso_mpi_init(), and analyzer_rayleigh_cvt_sph::init_cvt_rayleigh_sph().