CALYPSO: set_surface_hash Module Reference
set_surface_hash Module Reference
Functions/Subroutines
subroutine count_surface_hash (numele, nnod_4_ele, ie, ntot_id, num_surf_hash, istack_surf_hash, iend_surf_hash)
subroutine set_surf_hash (numele, nnod_4_ele, ie, ntot_id, ntot_list, num_surf_hash, istack_surf_hash, isurf_hash)
subroutine count_part_surface_hash (numele, nnod_4_ele, ie, numele_part, iele_part, ntot_id, num_surf_hash, istack_surf_hash, iend_surf_hash)
subroutine set_part_surf_hash (numele, nnod_4_ele, ie, numele_part, iele_part, ntot_id, ntot_list, num_surf_hash, istack_surf_hash, isurf_hash)
Function/Subroutine Documentation
count_part_surface_hash()
subroutine set_surface_hash::count_part_surface_hash (integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) nnod_4_ele, integer(kind = kint), dimension(numele,nnod_4_ele), intent(in) ie, integer(kind = kint), intent(in) numele_part, integer(kind = kint), dimension(numele_part), intent(in) iele_part, integer(kind = kint_gl), intent(in) ntot_id, integer(kind = kint_gl), dimension(ntot_id), intent(inout) num_surf_hash, integer(kind = kint_gl), dimension(0:ntot_id), intent(inout) istack_surf_hash, integer(kind = kint_gl), intent(inout) iend_surf_hash)
Definition at line 129 of file set_surface_hash.f90.
References m_geometry_constants::node_on_sf_4, and m_geometry_constants::nsurf_4_ele.
Referenced by const_surface_data::const_part_surface_hash().
count_surface_hash()
subroutine set_surface_hash::count_surface_hash (integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) nnod_4_ele, integer(kind = kint), dimension(numele,nnod_4_ele), intent(in) ie, integer(kind = kint_gl), intent(in) ntot_id, integer(kind = kint_gl), dimension(ntot_id), intent(inout) num_surf_hash, integer(kind = kint_gl), dimension(0:ntot_id), intent(inout) istack_surf_hash, integer(kind = kint_gl), intent(inout) iend_surf_hash)
Definition at line 32 of file set_surface_hash.f90.
References m_geometry_constants::node_on_sf_4, and m_geometry_constants::nsurf_4_ele.
Referenced by const_surface_data::const_surface_hash().
set_part_surf_hash()
subroutine set_surface_hash::set_part_surf_hash (integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) nnod_4_ele, integer(kind = kint), dimension(numele,nnod_4_ele), intent(in) ie, integer(kind = kint), intent(in) numele_part, integer(kind = kint), dimension(numele_part), intent(in) iele_part, integer(kind = kint_gl), intent(in) ntot_id, integer(kind = kint_gl), intent(in) ntot_list, integer(kind = kint_gl), dimension(ntot_id), intent(inout) num_surf_hash, integer(kind = kint_gl), dimension(0:ntot_id), intent(inout) istack_surf_hash, integer(kind = kint), dimension(ntot_list,2), intent(inout) isurf_hash)
Definition at line 184 of file set_surface_hash.f90.
References m_geometry_constants::node_on_sf_4, and m_geometry_constants::nsurf_4_ele.
Referenced by const_surface_data::const_part_surface_hash().
set_surf_hash()
subroutine set_surface_hash::set_surf_hash (integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) nnod_4_ele, integer(kind = kint), dimension(numele,nnod_4_ele), intent(in) ie, integer(kind = kint_gl), intent(in) ntot_id, integer(kind = kint_gl), intent(in) ntot_list, integer(kind = kint_gl), dimension(ntot_id), intent(inout) num_surf_hash, integer(kind = kint_gl), dimension(0:ntot_id), intent(inout) istack_surf_hash, integer(kind = kint), dimension(ntot_list,2), intent(inout) isurf_hash)
Definition at line 82 of file set_surface_hash.f90.
References m_geometry_constants::node_on_sf_4, and m_geometry_constants::nsurf_4_ele.
Referenced by const_surface_data::const_surface_hash().