CALYPSO: t_legendre_matrix_4_trns Module Reference
t_legendre_matrix_4_trns Module Reference
Work array for forward Legendre transform useing mat multi
data are strored communication buffer.
Data Types
type leg_jt_omp_matrix
Structure of Legendre polynomial P(l, \theta)
type leg_tj_omp_matrix
Structure of Legendre polynomial P(\theta, l)
Functions/Subroutines
subroutine alloc_each_sym_leg_omp_mat_jt (nle_rtm, n_jk_e, n_jk_o, Pjt_mat)
subroutine alloc_each_sym_leg_omp_mat_tj (nle_rtm, n_jk_e, n_jk_o, Ptj_mat)
subroutine dealloc_each_sym_leg_mat_jt (Pjt_mat)
subroutine dealloc_each_sym_leg_mat_tj (Ptj_mat)
Detailed Description
Work array for forward Legendre transform useing mat multi
data are strored communication buffer.
      subroutine alloc_each_sym_leg_omp_mat_jt                        &
     &         (nle_rtm, n_jk_e, n_jk_o, Pjt_mat)
        type(leg_jt_omp_matrix), intent(inout) :: Pjt_mat
      subroutine alloc_each_sym_leg_omp_mat_tj                        &
     &         (nle_rtm, n_jk_e, n_jk_o, Ptj_mat)
        type(leg_tj_omp_matrix), intent(inout) :: Ptj_mat
      subroutine dealloc_each_sym_leg_mat_jt(Pjt_mat)
        type(leg_jt_omp_matrix), intent(inout) :: Pjt_mat
      subroutine dealloc_each_sym_leg_mat_tj(Ptj_mat)
        type(leg_tj_omp_matrix), intent(inout) :: Ptj_mat
Parameters
ncomp Total number of components for spherical transform
nvector Number of vector for spherical transform
nscalar Number of scalar (including tensor components) for spherical transform
Function/Subroutine Documentation
alloc_each_sym_leg_omp_mat_jt()
subroutine t_legendre_matrix_4_trns::alloc_each_sym_leg_omp_mat_jt (integer(kind = kint), intent(in) nle_rtm, integer(kind = kint), intent(in) n_jk_e, integer(kind = kint), intent(in) n_jk_o, type(leg_jt_omp_matrix), intent(inout) Pjt_mat)
Definition at line 86 of file t_legendre_matrix_4_trns.f90.
Referenced by t_legendre_work_sym_mat_jt::init_each_sym_leg_omp_mat_jt(), t_legendre_work_testlooop::init_legendre_sym_mat_both(), and t_legendre_work_on_the_fly::init_legendre_sym_mat_otfly().
alloc_each_sym_leg_omp_mat_tj()
subroutine t_legendre_matrix_4_trns::alloc_each_sym_leg_omp_mat_tj (integer(kind = kint), intent(in) nle_rtm, integer(kind = kint), intent(in) n_jk_e, integer(kind = kint), intent(in) n_jk_o, type(leg_tj_omp_matrix), intent(inout) Ptj_mat)
Definition at line 115 of file t_legendre_matrix_4_trns.f90.
Referenced by t_legendre_work_sym_mat_jt::init_each_sym_leg_omp_mat_tj(), t_legendre_work_testlooop::init_legendre_sym_mat_both(), and t_legendre_work_on_the_fly::init_legendre_sym_mat_otfly().
dealloc_each_sym_leg_mat_jt()
subroutine t_legendre_matrix_4_trns::dealloc_each_sym_leg_mat_jt (type(leg_jt_omp_matrix), intent(inout) Pjt_mat)
Definition at line 145 of file t_legendre_matrix_4_trns.f90.
Referenced by t_legendre_work_testlooop::dealloc_leg_sym_mat_both(), t_legendre_work_on_the_fly::dealloc_leg_sym_mat_otfly(), and t_legendre_work_sym_mat_jt::dealloc_sym_leg_omp_mat_jt().
dealloc_each_sym_leg_mat_tj()
subroutine t_legendre_matrix_4_trns::dealloc_each_sym_leg_mat_tj (type(leg_tj_omp_matrix), intent(inout) Ptj_mat)
Definition at line 157 of file t_legendre_matrix_4_trns.f90.
Referenced by t_legendre_work_testlooop::dealloc_leg_sym_mat_both(), t_legendre_work_on_the_fly::dealloc_leg_sym_mat_otfly(), and t_legendre_work_sym_mat_jt::dealloc_sym_leg_omp_mat_tj().