CALYPSO: t_fdm_coefs Module Reference
t_fdm_coefs Module Reference
Coefficients to obtain radial derivatives by finite difference method.
Data Types
type fdm_matrices
Structure of FDM matrices.
type fdm_matrix
Structure of FDM matrix.
Functions/Subroutines
subroutine alloc_nod_fdm_matrices (nri, num_order, fdmn_nod)
subroutine alloc_fdm_work (nri, fdmn_nod)
subroutine dealloc_nod_fdm_matrices (fdmn_nod)
subroutine dealloc_fdm_work (fdmn_nod)
subroutine copy_fdm2_nod_coefs_from_mat (nri, fdm2_nod)
subroutine copy_fdm4_nod_coefs_from_mat (nri, fdm4_nod)
subroutine copy_fdm2_ele_coefs_from_mat (nri, fdm2_ele)
subroutine check_fdm_coefs (nri, r, fdmn_nod)
subroutine check_fdm_mat (nri, r, fdmn_nod)
subroutine, private alloc_fdm_matrix (nri, n_order, fdm)
subroutine, private dealloc_fdm_matrix (fdm)
subroutine, private check_fdm_coef (nri, r, fdm)
Detailed Description
Coefficients to obtain radial derivatives by finite difference method.
 ----------------------------------------------------------------------
      Coeeficients for derivatives by 1d finite difference method
     define of elemental field
       r_ele(k) = half *(r_nod(k-1) + r_nod(k))
       d_ele(k) = half *(d_nod(k-1) + d_nod(k))
    2nd order derivatives on node by nodal field
      dfdr =    fdmn_nod%fdm(1)%dmat(k,-1) * d_nod(k-1)
              + fdmn_nod%fdm(1)%dmat(k, 0) * d_nod(k  )
              + fdmn_nod%fdm(1)%dmat(k, 1) * d_nod(k+1)
      d2fdr2 =  fdmn_nod%fdm(2)%dmat(k,-1) * d_nod(k-1)
              + fdmn_nod%fdm(2)%dmat(k, 0) * d_nod(k  )
              + fdmn_nod%fdm(2)%dmat(k, 1) * d_nod(k+1)
 ----------------------------------------------------------------------
      subroutine alloc_nod_fdm_matrices(nri, num_order, fdm)
      subroutine alloc_fdm_work(nri, fdmn_nod)
      subroutine dealloc_nod_fdm_matrices(fdmn_nod)
      subroutine dealloc_fdm_work(fdmn_nod)
      subroutine copy_fdm2_nod_coefs_from_mat(nri, fdm2_nod)
      subroutine copy_fdm4_nod_coefs_from_mat(nri, fdm4_nod)
      subroutine copy_fdm2_ele_coefs_from_mat(nri, fdm2_ele)
      subroutine check_fdm_coefs(nri, r, fdmn_nod)
      subroutine check_fdm_mat(nri, r, fdmn_nod)
Parameters
nri number of radial grid points
r(nri) radius
Function/Subroutine Documentation
alloc_fdm_matrix()
subroutine, private t_fdm_coefs::alloc_fdm_matrix (integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) n_order, type(fdm_matrix), intent(inout) fdm) private
Definition at line 254 of file t_fdm_coefs.f90.
Referenced by alloc_nod_fdm_matrices().
alloc_fdm_work()
subroutine t_fdm_coefs::alloc_fdm_work (integer(kind = kint), intent(in) nri, type(fdm_matrices), intent(inout) fdmn_nod)
Definition at line 101 of file t_fdm_coefs.f90.
Referenced by const_fdm_coefs::const_2e_fdm_coefs(), const_fdm_coefs::const_2nd_fdm_matrices(), and const_fdm_coefs::const_4th_fdm_coefs().
alloc_nod_fdm_matrices()
subroutine t_fdm_coefs::alloc_nod_fdm_matrices (integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) num_order, type(fdm_matrices), intent(inout) fdmn_nod)
Definition at line 82 of file t_fdm_coefs.f90.
References alloc_fdm_matrix().
Referenced by const_fdm_coefs::const_2e_fdm_coefs(), const_fdm_coefs::const_2nd_fdm_matrices(), and const_fdm_coefs::const_4th_fdm_coefs().
check_fdm_coef()
subroutine, private t_fdm_coefs::check_fdm_coef (integer(kind = kint), intent(in) nri, real(kind = kreal), dimension(nri), intent(in) r, type(fdm_matrix), intent(in) fdm) private
Definition at line 281 of file t_fdm_coefs.f90.
Referenced by check_fdm_coefs().
check_fdm_coefs()
subroutine t_fdm_coefs::check_fdm_coefs (integer(kind = kint), intent(in) nri, real(kind = kreal), dimension(nri), intent(in) r, type(fdm_matrices), intent(in) fdmn_nod)
Definition at line 215 of file t_fdm_coefs.f90.
References check_fdm_coef().
Referenced by const_fdm_coefs::const_2nd_fdm_matrices(), and const_fdm_coefs::const_4th_fdm_coefs().
check_fdm_mat()
subroutine t_fdm_coefs::check_fdm_mat (integer(kind = kint), intent(in) nri, real(kind = kreal), dimension(nri), intent(in) r, type(fdm_matrices), intent(in) fdmn_nod)
Definition at line 233 of file t_fdm_coefs.f90.
copy_fdm2_ele_coefs_from_mat()
subroutine t_fdm_coefs::copy_fdm2_ele_coefs_from_mat (integer(kind = kint), intent(in) nri, type(fdm_matrices), intent(inout) fdm2_ele)
Definition at line 195 of file t_fdm_coefs.f90.
Referenced by const_fdm_coefs::const_2e_fdm_coefs().
copy_fdm2_nod_coefs_from_mat()
subroutine t_fdm_coefs::copy_fdm2_nod_coefs_from_mat (integer(kind = kint), intent(in) nri, type(fdm_matrices), intent(inout) fdm2_nod)
Definition at line 146 of file t_fdm_coefs.f90.
Referenced by const_fdm_coefs::const_2nd_fdm_matrices().
copy_fdm4_nod_coefs_from_mat()
subroutine t_fdm_coefs::copy_fdm4_nod_coefs_from_mat (integer(kind = kint), intent(in) nri, type(fdm_matrices), intent(inout) fdm4_nod)
Definition at line 170 of file t_fdm_coefs.f90.
Referenced by const_fdm_coefs::const_4th_fdm_coefs().
dealloc_fdm_matrix()
subroutine, private t_fdm_coefs::dealloc_fdm_matrix (type(fdm_matrix), intent(inout) fdm) private
Definition at line 270 of file t_fdm_coefs.f90.
Referenced by dealloc_nod_fdm_matrices().
dealloc_fdm_work()
subroutine t_fdm_coefs::dealloc_fdm_work (type(fdm_matrices), intent(inout) fdmn_nod)
Definition at line 134 of file t_fdm_coefs.f90.
Referenced by const_fdm_coefs::const_2e_fdm_coefs(), const_fdm_coefs::const_2nd_fdm_matrices(), and const_fdm_coefs::const_4th_fdm_coefs().
dealloc_nod_fdm_matrices()
subroutine t_fdm_coefs::dealloc_nod_fdm_matrices (type(fdm_matrices), intent(inout) fdmn_nod)
Definition at line 117 of file t_fdm_coefs.f90.
References dealloc_fdm_matrix().