CALYPSO: gen_sph_grids_modes Module Reference
gen_sph_grids_modes Module Reference
Set global spherical harmonics indices in local array (Serial version)
Functions/Subroutines
subroutine const_sph_rlm_modes (id_rank, s3d_ranks, s3d_radius, sph_lcp, stk_lc1d, sph_gl1d, sph_rlm, comm_rlm)
subroutine const_sph_rtm_grids (id_rank, s3d_ranks, s3d_radius, sph_lcp, stk_lc1d, sph_gl1d, sph_rtm, comm_rtm)
subroutine, private const_comm_table_4_rlm (id_rank, s3d_ranks, sph_rlm, comm_rlm)
subroutine, private const_comm_table_4_rtm (id_rank, s3d_ranks, sph_rtm, comm_rtm)
Detailed Description
Set global spherical harmonics indices in local array (Serial version)
      subroutine const_sph_rlm_modes                                  &
     &         (id_rank, s3d_ranks, s3d_radius, sph_lcp, stk_lc1d,    &
     &          sph_gl1d,  sph_rlm, comm_rlm)
        type(spheric_global_rank), intent(in) :: s3d_ranks
        type(spheric_global_radius), intent(in) :: s3d_radius
        type(sph_local_parameters), intent(in) :: sph_lcp
        type(sph_1d_index_stack), intent(in)  :: stk_lc1d
        type(sph_1d_global_index), intent(in)  :: sph_gl1d
        type(sph_rlm_grid), intent(inout) :: sph_rlm
        type(sph_comm_tbl), intent(inout) :: comm_rlm
      subroutine const_sph_rtm_grids                                  &
     &         (id_rank, s3d_ranks, s3d_radius, sph_lcp, stk_lc1d,    &
     &          sph_gl1d, sph_rtm, comm_rtm)
        type(spheric_global_rank), intent(in) :: s3d_ranks
        type(spheric_global_radius), intent(in) :: s3d_radius
        type(sph_local_parameters), intent(in) :: sph_lcp
        type(sph_1d_index_stack), intent(in)  :: stk_lc1d
        type(sph_1d_global_index), intent(in)  :: sph_gl1d
        type(sph_rtm_grid), intent(inout) :: sph_rtm
        type(sph_comm_tbl), intent(inout) :: comm_rtm
Function/Subroutine Documentation
const_comm_table_4_rlm()
subroutine, private gen_sph_grids_modes::const_comm_table_4_rlm (integer, intent(in) id_rank, type(spheric_global_rank), intent(in) s3d_ranks, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_comm_tbl), intent(inout) comm_rlm) private
Definition at line 161 of file gen_sph_grids_modes.f90.
References t_sph_trans_comm_tbl::alloc_sph_comm_item(), t_sph_trans_comm_tbl::alloc_sph_comm_stack(), set_comm_table_rtm_rlm::allocate_ncomm(), set_comm_table_rtm_rlm::count_comm_table_4_rlm(), set_comm_table_rtm_rlm::count_num_domain_rtm_rlm(), set_comm_table_rtm_rlm::deallocate_ncomm(), m_machine_parameter::iflag_debug, set_comm_table_rtm_rlm::set_comm_stack_rtm_rlm(), and set_comm_table_rtm_rlm::set_comm_table_4_rlm().
Referenced by const_sph_rlm_modes().
const_comm_table_4_rtm()
subroutine, private gen_sph_grids_modes::const_comm_table_4_rtm (integer, intent(in) id_rank, type(spheric_global_rank), intent(in) s3d_ranks, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_comm_tbl), intent(inout) comm_rtm) private
Definition at line 212 of file gen_sph_grids_modes.f90.
References t_sph_trans_comm_tbl::alloc_sph_comm_item(), t_sph_trans_comm_tbl::alloc_sph_comm_stack(), set_comm_table_rtm_rlm::allocate_ncomm(), set_comm_table_rtm_rlm::count_comm_table_4_rtm(), set_comm_table_rtm_rlm::count_num_domain_rtm_rlm(), set_comm_table_rtm_rlm::deallocate_ncomm(), set_comm_table_rtm_rlm::set_comm_stack_rtm_rlm(), and set_comm_table_rtm_rlm::set_comm_table_4_rtm().
Referenced by const_sph_rtm_grids().
const_sph_rlm_modes()
subroutine gen_sph_grids_modes::const_sph_rlm_modes (integer, intent(in) id_rank, type(spheric_global_rank), intent(in) s3d_ranks, type(spheric_global_radius), intent(in) s3d_radius, type(sph_local_parameters), intent(in) sph_lcp, type(sph_1d_index_stack), intent(in) stk_lc1d, type(sph_1d_global_index), intent(in) sph_gl1d, type(sph_rlm_grid), intent(inout) sph_rlm, type(sph_comm_tbl), intent(inout) comm_rlm)
Definition at line 48 of file gen_sph_grids_modes.f90.
References t_spheric_rlm_data::alloc_sph_1d_index_rlm(), t_spheric_rlm_data::alloc_spheric_param_rlm(), t_spheric_rlm_data::check_spheric_param_rlm(), const_comm_table_4_rlm(), set_local_sphere_by_global::copy_gl_2_local_rlm_param(), copy_sph_1d_global_index::copy_sph_1d_gl_idx_rlm(), m_machine_parameter::iflag_debug, set_local_sphere_param::set_global_sph_4_lmr(), and set_local_sphere_param::set_global_sph_4_rlm().
Referenced by mpi_gen_sph_grids_modes::mpi_gen_sph_grids(), mpi_gen_sph_grids_modes::mpi_gen_sph_rj_mode(), t_parai_gen_sph_grids_modes::para_gen_sph_rlm_rj_modes(), and set_comm_table_rtp_rj::set_comm_table_4_rj().
const_sph_rtm_grids()
subroutine gen_sph_grids_modes::const_sph_rtm_grids (integer, intent(in) id_rank, type(spheric_global_rank), intent(in) s3d_ranks, type(spheric_global_radius), intent(in) s3d_radius, type(sph_local_parameters), intent(in) sph_lcp, type(sph_1d_index_stack), intent(in) stk_lc1d, type(sph_1d_global_index), intent(in) sph_gl1d, type(sph_rtm_grid), intent(inout) sph_rtm, type(sph_comm_tbl), intent(inout) comm_rtm)
Definition at line 104 of file gen_sph_grids_modes.f90.
References t_spheric_rtm_data::alloc_sph_1d_index_rtm(), t_spheric_rtm_data::alloc_spheric_param_rtm(), t_spheric_rtm_data::check_spheric_param_rtm(), const_comm_table_4_rtm(), set_local_sphere_by_global::copy_gl_2_local_rtm_param(), copy_sph_1d_global_index::copy_sph_1d_gl_idx_rtm(), m_machine_parameter::iflag_debug, set_local_sphere_param::set_global_sph_4_rtm(), and set_local_sphere_param::set_global_sph_4_trm().
Referenced by mpi_gen_sph_grids_modes::mpi_gen_sph_grids(), t_parai_gen_sph_grids_modes::para_gen_sph_rtm_rtp_grids(), and set_comm_table_rtp_rj::set_comm_table_4_rtp().