CALYPSO: t_spheric_rj_data Module Reference
t_spheric_rj_data Module Reference
Structure for indexing table of speherical harmonic oefficients.
Data Types
type sph_rj_grid
structure of index table for \(f(r,j) \)
Functions/Subroutines
subroutine alloc_spheric_param_rj (rj)
subroutine alloc_sph_1d_index_rj (rj)
subroutine alloc_rj_param_smp (rj)
subroutine dealloc_spheric_param_rj (rj)
subroutine dealloc_sph_1d_index_rj (rj)
subroutine dealloc_rj_param_smp (rj)
subroutine copy_spheric_rj_data (ltr_org, rj_org, ltr_new, rj_new)
subroutine check_spheric_param_rj (id_rank, rj)
integer(kind=kint) function find_local_sph_address (rj, l, m)
integer(kind=kint) function local_sph_node_address (rj, kr, j_lc)
Detailed Description
Structure for indexing table of speherical harmonic oefficients.
      subroutine alloc_spheric_param_rj(rj)
      subroutine alloc_sph_1d_index_rj(rj)
      subroutine alloc_rj_param_smp(rj)
        type(sph_rj_grid), intent(inout) :: rj
      subroutine dealloc_spheric_param_rj(rj)
      subroutine dealloc_sph_1d_index_rj(rj)
      subroutine dealloc_rj_param_smp(rj)
        type(sph_rj_grid), intent(inout) :: rj
      subroutine copy_spheric_rj_data                                 &
     &         (ltr_org, rj_org, ltr_new, rj_new)
        type(sph_rj_grid), intent(in) :: rj_org
        type(sph_rj_grid), intent(inout) :: rj_new
      subroutine check_spheric_param_rj(id_rank, rj)
        integer, intent(in) :: id_rank
        type(sph_rj_grid), intent(in) :: rj
      integer(kind = kint) function find_local_sph_address(rj, l, m)
        type(sph_rj_grid), intent(in) :: rj
        integer(kind = 4), intent(in) :: l, m
      integer(kind = kint) function local_sph_node_address            &
     &                            (rj, kr, j_lc)
        type(sph_rj_grid), intent(in) :: rj
Parameters
id_rank Running rank ID
Function/Subroutine Documentation
alloc_rj_param_smp()
subroutine t_spheric_rj_data::alloc_rj_param_smp (type(sph_rj_grid), intent(inout) rj)
Definition at line 173 of file t_spheric_rj_data.f90.
References m_machine_parameter::np_smp.
Referenced by count_num_sph_smp::count_num_rj_smp().
alloc_sph_1d_index_rj()
subroutine t_spheric_rj_data::alloc_sph_1d_index_rj (type(sph_rj_grid), intent(inout) rj)
Definition at line 138 of file t_spheric_rj_data.f90.
Referenced by copy_sph_rj_mode_4_io::copy_sph_node_4_rj_from_io(), and copy_spheric_rj_data().
alloc_spheric_param_rj()
subroutine t_spheric_rj_data::alloc_spheric_param_rj (type(sph_rj_grid), intent(inout) rj)
Definition at line 126 of file t_spheric_rj_data.f90.
Referenced by t_spheric_parameter::alloc_spheric_parameter(), copy_sph_rj_mode_4_io::copy_sph_node_4_rj_from_io(), and copy_spheric_rj_data().
check_spheric_param_rj()
subroutine t_spheric_rj_data::check_spheric_param_rj (integer, intent(in) id_rank, type(sph_rj_grid), intent(in) rj)
Definition at line 279 of file t_spheric_rj_data.f90.
Referenced by t_spheric_parameter::check_spheric_parameter().
copy_spheric_rj_data()
subroutine t_spheric_rj_data::copy_spheric_rj_data (integer(kind = kint), intent(in) ltr_org, type(sph_rj_grid), intent(in) rj_org, integer(kind = kint), intent(inout) ltr_new, type(sph_rj_grid), intent(inout) rj_new)
Definition at line 231 of file t_spheric_rj_data.f90.
References alloc_sph_1d_index_rj(), alloc_spheric_param_rj(), and m_constants::itwo.
dealloc_rj_param_smp()
subroutine t_spheric_rj_data::dealloc_rj_param_smp (type(sph_rj_grid), intent(inout) rj)
Definition at line 218 of file t_spheric_rj_data.f90.
dealloc_sph_1d_index_rj()
subroutine t_spheric_rj_data::dealloc_sph_1d_index_rj (type(sph_rj_grid), intent(inout) rj)
Definition at line 205 of file t_spheric_rj_data.f90.
Referenced by t_spheric_parameter::dealloc_sph_1d_indices().
dealloc_spheric_param_rj()
subroutine t_spheric_rj_data::dealloc_spheric_param_rj (type(sph_rj_grid), intent(inout) rj)
Definition at line 195 of file t_spheric_rj_data.f90.
Referenced by t_spheric_parameter::dealloc_spheric_parameter().
find_local_sph_address()
integer(kind = kint) function t_spheric_rj_data::find_local_sph_address (type(sph_rj_grid), intent(in) rj, integer, intent(in) l, integer, intent(in) m)
Definition at line 300 of file t_spheric_rj_data.f90.
Referenced by t_each_sph_boundary_io_data::bc_4_evo_scalar_sph_by_file(), t_each_sph_boundary_io_data::bc_4_evo_vect2_sph_by_file(), t_each_sph_boundary_io_data::bc_4_evo_vector_sph_by_file(), solve_sph_fluid_crank::check_scalar_coefs(), pickup_sph_spectr::count_picked_sph_adrress(), extend_potential_field::gauss_to_poloidal_in(), extend_potential_field_t::gauss_to_poloidal_in_t(), extend_potential_field::gauss_to_poloidal_out(), extend_potential_field_t::gauss_to_poloidal_out_t(), initial_magne_dynamobench::initial_b_dynamobench_1(), initial_magne_dynamobench::initial_b_dynamobench_2(), initial_magne_dbench_qvc::initial_b_dynamobench_qcv(), t_each_sph_boundary_io_data::set_bc_4_sph_scalar_by_file(), t_each_sph_boundary_io_data::set_bc_4_sph_vector_by_file(), parallel_assemble_sph::set_mode_table_4_assemble(), pickup_sph_spectr::set_picked_sph_address(), and solve_sph_fluid_crank::solve_pressure_by_div_v().
local_sph_node_address()
integer(kind = kint) function t_spheric_rj_data::local_sph_node_address (type(sph_rj_grid), intent(in) rj, integer, intent(in) kr, integer, intent(in) j_lc)
Definition at line 321 of file t_spheric_rj_data.f90.