CALYPSO: bcast_4_sphere_ctl Module Reference
bcast_4_sphere_ctl Module Reference
control data for resolutions of spherical shell
Functions/Subroutines
subroutine bcast_ctl_4_shell_define (spctl)
subroutine bcast_ctl_ndomain_4_shell (sdctl)
Detailed Description
control data for resolutions of spherical shell
      subroutine bcast_ctl_4_shell_define(spctl)
        type(sphere_data_control), intent(inout) :: spctl
      subroutine bcast_ctl_ndomain_4_shell(sdctl)
        type(sphere_domain_control), intent(inout) :: sdctl
Function/Subroutine Documentation
bcast_ctl_4_shell_define()
subroutine bcast_4_sphere_ctl::bcast_ctl_4_shell_define (type(sphere_data_control), intent(inout) spctl)
Definition at line 30 of file bcast_4_sphere_ctl.f90.
References bcast_control_arrays::bcast_ctl_array_ci(), bcast_control_arrays::bcast_ctl_array_i2(), bcast_control_arrays::bcast_ctl_array_ir(), bcast_control_arrays::bcast_ctl_type_c1(), bcast_control_arrays::bcast_ctl_type_i1(), and bcast_control_arrays::bcast_ctl_type_r1().
Referenced by t_ctl_data_gen_sph_shell::bcast_parallel_shell_ctl().
bcast_ctl_ndomain_4_shell()
subroutine bcast_4_sphere_ctl::bcast_ctl_ndomain_4_shell (type(sphere_domain_control), intent(inout) sdctl)
Definition at line 74 of file bcast_4_sphere_ctl.f90.
References bcast_control_arrays::bcast_ctl_array_ci(), bcast_control_arrays::bcast_ctl_type_c1(), and bcast_control_arrays::bcast_ctl_type_i1().
Referenced by t_ctl_data_gen_sph_shell::bcast_parallel_shell_ctl().