CALYPSO: t_spheric_rtm_data Module Reference
t_spheric_rtm_data Module Reference
Structure for indexing table of speherical harmonics transform.
Data Types
type sph_rtm_grid
structure of index table for \(f(r,\theta,m) \)
Functions/Subroutines
subroutine alloc_spheric_param_rtm (sph_rtm)
subroutine alloc_sph_1d_index_rtm (sph_rtm)
subroutine alloc_rtm_param_smp (sph_rtm)
subroutine dealloc_spheric_param_rtm (sph_rtm)
subroutine dealloc_sph_1d_index_rtm (sph_rtm)
subroutine dealloc_rtm_param_smp (sph_rtm)
subroutine copy_spheric_rtm_data (ltr_org, rtm_org, ltr_new, rtm_new)
subroutine check_spheric_param_rtm (id_rank, sph_rtm)
Detailed Description
Structure for indexing table of speherical harmonics transform.
      subroutine alloc_spheric_param_rtm(sph_rtm)
      subroutine alloc_sph_1d_index_rtm(sph_rtm)
      subroutine alloc_rtm_param_smp(sph_rtm)
        type(sph_rtm_grid), intent(inout) :: sph_rtm
      subroutine dealloc_spheric_param_rtm(sph_rtm)
      subroutine dealloc_sph_1d_index_rtm(sph_rtm)
      subroutine dealloc_rtm_param_smp(sph_rtm)
        type(sph_rtm_grid), intent(inout) :: sph_rtm
      subroutine copy_spheric_rtm_data                                &
     &         (ltr_org, rtm_org, ltr_new, rtm_new)
      type(sph_rtm_grid), intent(in) :: rtm_org
      type(sph_rtm_grid), intent(inout) :: rtm_new
      subroutine check_spheric_param_rtm(id_rank, sph_rtm)
        integer, intent(in) :: id_rank
        type(sph_rtm_grid), intent(in) :: sph_rtm
Parameters
id_rank Running rank ID
Function/Subroutine Documentation
alloc_rtm_param_smp()
subroutine t_spheric_rtm_data::alloc_rtm_param_smp (type(sph_rtm_grid), intent(inout) sph_rtm)
Definition at line 142 of file t_spheric_rtm_data.f90.
References m_machine_parameter::np_smp.
Referenced by count_num_sph_smp::count_num_rtm_smp().
alloc_sph_1d_index_rtm()
subroutine t_spheric_rtm_data::alloc_sph_1d_index_rtm (type(sph_rtm_grid), intent(inout) sph_rtm)
Definition at line 116 of file t_spheric_rtm_data.f90.
Referenced by gen_sph_grids_modes::const_sph_rtm_grids(), copy_sph_rtm_node_4_io::copy_sph_node_4_rtm_from_io(), and copy_spheric_rtm_data().
alloc_spheric_param_rtm()
subroutine t_spheric_rtm_data::alloc_spheric_param_rtm (type(sph_rtm_grid), intent(inout) sph_rtm)
Definition at line 104 of file t_spheric_rtm_data.f90.
Referenced by t_spheric_parameter::alloc_spheric_parameter(), gen_sph_grids_modes::const_sph_rtm_grids(), copy_sph_rtm_node_4_io::copy_sph_node_4_rtm_from_io(), and copy_spheric_rtm_data().
check_spheric_param_rtm()
subroutine t_spheric_rtm_data::check_spheric_param_rtm (integer, intent(in) id_rank, type(sph_rtm_grid), intent(in) sph_rtm)
Definition at line 259 of file t_spheric_rtm_data.f90.
Referenced by t_spheric_parameter::check_spheric_parameter(), and gen_sph_grids_modes::const_sph_rtm_grids().
copy_spheric_rtm_data()
subroutine t_spheric_rtm_data::copy_spheric_rtm_data (integer(kind = kint), intent(in) ltr_org, type(sph_rtm_grid), intent(in) rtm_org, integer(kind = kint), intent(inout) ltr_new, type(sph_rtm_grid), intent(inout) rtm_new)
Definition at line 210 of file t_spheric_rtm_data.f90.
References alloc_sph_1d_index_rtm(), alloc_spheric_param_rtm(), and m_constants::ithree.
dealloc_rtm_param_smp()
subroutine t_spheric_rtm_data::dealloc_rtm_param_smp (type(sph_rtm_grid), intent(inout) sph_rtm)
Definition at line 195 of file t_spheric_rtm_data.f90.
dealloc_sph_1d_index_rtm()
subroutine t_spheric_rtm_data::dealloc_sph_1d_index_rtm (type(sph_rtm_grid), intent(inout) sph_rtm)
Definition at line 180 of file t_spheric_rtm_data.f90.
Referenced by t_spheric_parameter::dealloc_sph_1d_indices().
dealloc_spheric_param_rtm()
subroutine t_spheric_rtm_data::dealloc_spheric_param_rtm (type(sph_rtm_grid), intent(inout) sph_rtm)
Definition at line 170 of file t_spheric_rtm_data.f90.
Referenced by t_spheric_parameter::dealloc_spheric_parameter().