CALYPSO: extend_potential_field Module Reference
extend_potential_field Module Reference
Extend magnetic field by potential field.
Functions/Subroutines
subroutine ext_outside_scalar (kr_out, is_fld, nidx_rj, idx_gl_1d_rj_j, radius_1d_rj_r, a_r_1d_rj_r, nnod_rj, ntot_phys_rj, d_rj)
subroutine ext_inside_scalar (kr_in, is_fld, nidx_rj, idx_gl_1d_rj_j, radius_1d_rj_r, a_r_1d_rj_r, nnod_rj, ntot_phys_rj, d_rj)
subroutine ext_outside_potential (kr_out, is_fld, nidx_rj, idx_gl_1d_rj_j, radius_1d_rj_r, a_r_1d_rj_r, nnod_rj, ntot_phys_rj, d_rj)
subroutine ext_inside_potential (kr_in, is_fld, nidx_rj, idx_gl_1d_rj_j, radius_1d_rj_r, a_r_1d_rj_r, nnod_rj, ntot_phys_rj, d_rj)
subroutine ext_outside_potential_with_j (kr_out, is_magne, is_current, nidx_rj, idx_gl_1d_rj_j, radius_1d_rj_r, a_r_1d_rj_r, nnod_rj, ntot_phys_rj, d_rj)
subroutine ext_inside_potential_with_j (kr_in, is_magne, is_current, nidx_rj, idx_gl_1d_rj_j, radius_1d_rj_r, a_r_1d_rj_r, nnod_rj, ntot_phys_rj, d_rj)
subroutine gauss_to_poloidal_out (kr_out, ltr_w, r_gauss, w_gauss, index_w, is_fld, sph_rj, n_point, ntot_phys_rj, d_rj)
subroutine gauss_to_poloidal_in (kr_in, ltr_w, r_gauss, w_gauss, index_w, is_fld, sph_rj, n_point, ntot_phys_rj, d_rj)
Detailed Description
Extend magnetic field by potential field.
      subroutine ext_outside_scalar(kr_out, is_fld,                   &
     &          nidx_rj, idx_gl_1d_rj_j, radius_1d_rj_r, a_r_1d_rj_r, &
     &          nnod_rj, ntot_phys_rj, d_rj)
      subroutine ext_inside_scalar(kr_in, is_fld,                     &
     &          nidx_rj, idx_gl_1d_rj_j, radius_1d_rj_r, a_r_1d_rj_r, &
     &          nnod_rj, ntot_phys_rj, d_rj)
      subroutine ext_outside_potential(kr_out, is_fld,                &
     &          nidx_rj, idx_gl_1d_rj_j, radius_1d_rj_r, a_r_1d_rj_r, &
     &          nnod_rj, ntot_phys_rj, d_rj)
     &         (kr_out, is_fld, ntot_phys_rj, d_rj)
        Output: d_rj(kr_out+1:,is_fld)
      subroutine ext_inside_potential(kr_in, is_fld, nidx_rj,         &
     &         idx_gl_1d_rj_j, radius_1d_rj_r, a_r_1d_rj_r,           &
     &         nnod_rj, ntot_phys_rj, d_rj)
        Output: d_rj(1:kr_in,is_fld)
      subroutine ext_outside_potential_with_j(kr_out,                 &
     &          is_magne, is_current, nidx_rj, idx_gl_1d_rj_j,        &
     &          radius_1d_rj_r, a_r_1d_rj_r, nnod_rj,                 &
     &          ntot_phys_rj, d_rj)
        Output: d_rj(1:kr_in,is_magne)
        Output: d_rj(1:kr_in,is_current)
      subroutine ext_inside_potential_with_j(kr_in,                   &
     &          is_magne, is_current, nidx_rj, idx_gl_1d_rj_j,        &
     &          radius_1d_rj_r, a_r_1d_rj_r, nnod_rj,                 &
     &          ntot_phys_rj, d_rj)
        Output: d_rj(1:kr_in,is_magne)
        Output: d_rj(1:kr_in,is_current)
      subroutine gauss_to_poloidal_out(kr_out, ltr_w, r_gauss,        &
     &          w_gauss, index_w, is_fld, sph_rj,                     &
     &          n_point, ntot_phys_rj, d_rj)
      subroutine gauss_to_poloidal_in(kr_in, ltr_w, r_gauss,          &
     &          w_gauss, index_w, is_fld, sph_rj,                     &
     &          n_point, ntot_phys_rj, d_rj)
        type(sph_rj_grid), intent(in) :: sph_rj
Function/Subroutine Documentation
ext_inside_potential()
subroutine extend_potential_field::ext_inside_potential (integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) is_fld, integer(kind = kint), dimension(2), intent(in) nidx_rj, integer(kind = kint), dimension(nidx_rj(2),3), intent(in) idx_gl_1d_rj_j, real(kind = kreal), dimension(nidx_rj(1)), intent(in) radius_1d_rj_r, real(kind = kreal), dimension(nidx_rj(1)), intent(in) a_r_1d_rj_r, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 179 of file extend_potential_field.f90.
References m_constants::zero.
Referenced by const_sph_radial_grad::const_grad_poloidal_magne(), r_interpolate_sph_data::r_interpolate_sph_fld_from_io(), and r_interpolate_sph_data::r_interpolate_sph_rst_from_io().
ext_inside_potential_with_j()
subroutine extend_potential_field::ext_inside_potential_with_j (integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) is_magne, integer(kind = kint), intent(in) is_current, integer(kind = kint), dimension(2), intent(in) nidx_rj, integer(kind = kint), dimension(nidx_rj(2),3), intent(in) idx_gl_1d_rj_j, real(kind = kreal), dimension(nidx_rj(1)), intent(in) radius_1d_rj_r, real(kind = kreal), dimension(nidx_rj(1)), intent(in) a_r_1d_rj_r, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 269 of file extend_potential_field.f90.
References m_constants::zero.
Referenced by const_sph_radial_grad::const_grad_bp_and_current().
ext_inside_scalar()
subroutine extend_potential_field::ext_inside_scalar (integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) is_fld, integer(kind = kint), dimension(2), intent(in) nidx_rj, integer(kind = kint), dimension(nidx_rj(2),3), intent(in) idx_gl_1d_rj_j, real(kind = kreal), dimension(nidx_rj(1)), intent(in) radius_1d_rj_r, real(kind = kreal), dimension(nidx_rj(1)), intent(in) a_r_1d_rj_r, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 100 of file extend_potential_field.f90.
ext_outside_potential()
subroutine extend_potential_field::ext_outside_potential (integer(kind = kint), intent(in) kr_out, integer(kind = kint), intent(in) is_fld, integer(kind = kint), dimension(2), intent(in) nidx_rj, integer(kind = kint), dimension(nidx_rj(2),3), intent(in) idx_gl_1d_rj_j, real(kind = kreal), dimension(nidx_rj(1)), intent(in) radius_1d_rj_r, real(kind = kreal), dimension(nidx_rj(1)), intent(in) a_r_1d_rj_r, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 138 of file extend_potential_field.f90.
References m_constants::zero.
Referenced by const_sph_radial_grad::const_grad_poloidal_magne(), r_interpolate_sph_data::r_interpolate_sph_fld_from_io(), and r_interpolate_sph_data::r_interpolate_sph_rst_from_io().
ext_outside_potential_with_j()
subroutine extend_potential_field::ext_outside_potential_with_j (integer(kind = kint), intent(in) kr_out, integer(kind = kint), intent(in) is_magne, integer(kind = kint), intent(in) is_current, integer(kind = kint), dimension(2), intent(in) nidx_rj, integer(kind = kint), dimension(nidx_rj(2),3), intent(in) idx_gl_1d_rj_j, real(kind = kreal), dimension(nidx_rj(1)), intent(in) radius_1d_rj_r, real(kind = kreal), dimension(nidx_rj(1)), intent(in) a_r_1d_rj_r, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 221 of file extend_potential_field.f90.
References m_constants::zero.
Referenced by const_sph_radial_grad::const_grad_bp_and_current().
ext_outside_scalar()
subroutine extend_potential_field::ext_outside_scalar (integer(kind = kint), intent(in) kr_out, integer(kind = kint), intent(in) is_fld, integer(kind = kint), dimension(2), intent(in) nidx_rj, integer(kind = kint), dimension(nidx_rj(2),3), intent(in) idx_gl_1d_rj_j, real(kind = kreal), dimension(nidx_rj(1)), intent(in) radius_1d_rj_r, real(kind = kreal), dimension(nidx_rj(1)), intent(in) a_r_1d_rj_r, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 62 of file extend_potential_field.f90.
gauss_to_poloidal_in()
subroutine extend_potential_field::gauss_to_poloidal_in (integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) ltr_w, real(kind = kreal), intent(in) r_gauss, real(kind = kreal), dimension(ltr_w*(ltr_w+2)), intent(in) w_gauss, integer(kind = kint), dimension(ltr_w*(ltr_w+2),2), intent(in) index_w, integer(kind = kint), intent(in) is_fld, type(sph_rj_grid), intent(in) sph_rj, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 363 of file extend_potential_field.f90.
References t_spheric_rj_data::find_local_sph_address(), m_constants::one, and m_constants::zero.
Referenced by r_interpolate_sph_data::set_poloidal_b_by_gauss_coefs().
gauss_to_poloidal_out()
subroutine extend_potential_field::gauss_to_poloidal_out (integer(kind = kint), intent(in) kr_out, integer(kind = kint), intent(in) ltr_w, real(kind = kreal), intent(in) r_gauss, real(kind = kreal), dimension(ltr_w*(ltr_w+2)), intent(in) w_gauss, integer(kind = kint), dimension(ltr_w*(ltr_w+2),2), intent(in) index_w, integer(kind = kint), intent(in) is_fld, type(sph_rj_grid), intent(in) sph_rj, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 317 of file extend_potential_field.f90.
References t_spheric_rj_data::find_local_sph_address(), m_constants::one, and m_constants::zero.
Referenced by r_interpolate_sph_data::set_poloidal_b_by_gauss_coefs().