CALYPSO: coordinate_convert_4_sph Module Reference
coordinate_convert_4_sph Module Reference
Get zonal mean and RMS fields in spherical grid.
Functions/Subroutines
subroutine overwrite_nodal_sph_2_xyz (node, nod_fld)
subroutine overwrite_nodal_cyl_2_xyz (node, nod_fld)
subroutine overwrite_nodal_xyz_2_sph (node, nod_fld)
subroutine overwrite_nodal_xyz_2_cyl (node, nod_fld)
subroutine overwrite_nodal_sph_2_cyl (node, nod_fld)
subroutine overwrite_nodal_sph_2_xyz_smp (node, ntot_comp, i_fld, numdir, d_nod)
subroutine, private overwrite_nodal_cyl_2_xyz_smp (node, ntot_comp, i_fld, numdir, d_nod)
subroutine overwrite_nodal_xyz_2_sph_smp (node, ntot_comp, i_fld, numdir, d_nod)
subroutine overwrite_nodal_xyz_2_cyl_smp (node, ntot_comp, i_fld, numdir, d_nod)
subroutine, private overwrite_nodal_sph_2_cyl_smp (node, ntot_comp, i_fld, numdir, d_nod)
Detailed Description
Get zonal mean and RMS fields in spherical grid.
      subroutine overwrite_nodal_sph_2_xyz(node, nod_fld)
      subroutine overwrite_nodal_cyl_2_xyz(node, nod_fld)
      subroutine overwrite_nodal_xyz_2_sph(node, nod_fld)
      subroutine overwrite_nodal_xyz_2_cyl(node, nod_fld)
      subroutine overwrite_nodal_sph_2_cyl(node, nod_fld)
        type(node_data), intent(in) ::    node
        type(phys_data), intent(inout) :: nod_fld
Parameters
numdir Number of component of field
irtp_fld Start address for field \(f(\r,\theta\phi) \)
Function/Subroutine Documentation
overwrite_nodal_cyl_2_xyz()
subroutine coordinate_convert_4_sph::overwrite_nodal_cyl_2_xyz (type(node_data), intent(in) node, type(phys_data), intent(inout) nod_fld)
Definition at line 65 of file coordinate_convert_4_sph.f90.
References overwrite_nodal_cyl_2_xyz_smp().
Referenced by sph_rtp_zonal_rms_data::zonal_cyl_rms_all_rtp_field().
overwrite_nodal_cyl_2_xyz_smp()
subroutine, private coordinate_convert_4_sph::overwrite_nodal_cyl_2_xyz_smp (type(node_data), intent(in) node, integer(kind = kint), intent(in) ntot_comp, integer(kind = kint), intent(in) i_fld, integer(kind = kint), intent(in) numdir, real(kind = kreal), dimension(node%numnod,ntot_comp), intent(inout) d_nod) private
Definition at line 193 of file coordinate_convert_4_sph.f90.
References m_machine_parameter::np_smp, cvt_cyl_vector_2_xyz_smp::overwrite_cyl_vect_2_xyz_smp(), and cvt_cyl_tensor_2_xyz_smp::overwrite_xyz_tensor_by_cyl_smp().
Referenced by overwrite_nodal_cyl_2_xyz().
overwrite_nodal_sph_2_cyl()
subroutine coordinate_convert_4_sph::overwrite_nodal_sph_2_cyl (type(node_data), intent(in) node, type(phys_data), intent(inout) nod_fld)
Definition at line 139 of file coordinate_convert_4_sph.f90.
References overwrite_nodal_sph_2_cyl_smp().
overwrite_nodal_sph_2_cyl_smp()
subroutine, private coordinate_convert_4_sph::overwrite_nodal_sph_2_cyl_smp (type(node_data), intent(in) node, integer(kind = kint), intent(in) ntot_comp, integer(kind = kint), intent(in) i_fld, integer(kind = kint), intent(in) numdir, real(kind = kreal), dimension(node%numnod,ntot_comp), intent(inout) d_nod) private
Definition at line 283 of file coordinate_convert_4_sph.f90.
References m_machine_parameter::np_smp, cvt_sph_tensor_2_cyl_smp::overwrite_cyl_tensor_by_sph_smp(), and cvt_sph_vector_2_cyl_smp::overwrite_sph_vect_2_cyl_smp().
Referenced by overwrite_nodal_sph_2_cyl().
overwrite_nodal_sph_2_xyz()
subroutine coordinate_convert_4_sph::overwrite_nodal_sph_2_xyz (type(node_data), intent(in) node, type(phys_data), intent(inout) nod_fld)
Definition at line 41 of file coordinate_convert_4_sph.f90.
References overwrite_nodal_sph_2_xyz_smp().
Referenced by sph_rtp_zonal_rms_data::zonal_mean_all_rtp_field(), and sph_rtp_zonal_rms_data::zonal_rms_all_rtp_field().
overwrite_nodal_sph_2_xyz_smp()
subroutine coordinate_convert_4_sph::overwrite_nodal_sph_2_xyz_smp (type(node_data), intent(in) node, integer(kind = kint), intent(in) ntot_comp, integer(kind = kint), intent(in) i_fld, integer(kind = kint), intent(in) numdir, real(kind = kreal), dimension(node%numnod,ntot_comp), intent(inout) d_nod)
Definition at line 164 of file coordinate_convert_4_sph.f90.
References m_machine_parameter::np_smp, cvt_sph_vector_2_xyz_smp::overwrite_sph_vect_2_xyz_smp(), and cvt_sph_tensor_2_xyz_smp::overwrite_xyz_tensor_by_sph_smp().
Referenced by overwrite_nodal_sph_2_xyz().
overwrite_nodal_xyz_2_cyl()
subroutine coordinate_convert_4_sph::overwrite_nodal_xyz_2_cyl (type(node_data), intent(in) node, type(phys_data), intent(inout) nod_fld)
Definition at line 114 of file coordinate_convert_4_sph.f90.
References overwrite_nodal_xyz_2_cyl_smp().
Referenced by sph_rtp_zonal_rms_data::zonal_cyl_rms_all_rtp_field().
overwrite_nodal_xyz_2_cyl_smp()
subroutine coordinate_convert_4_sph::overwrite_nodal_xyz_2_cyl_smp (type(node_data), intent(in) node, integer(kind = kint), intent(in) ntot_comp, integer(kind = kint), intent(in) i_fld, integer(kind = kint), intent(in) numdir, real(kind = kreal), dimension(node%numnod,ntot_comp), intent(inout) d_nod)
Definition at line 253 of file coordinate_convert_4_sph.f90.
References m_machine_parameter::np_smp, cvt_xyz_tensor_2_cyl_smp::overwrite_cyl_tensor_smp(), and cvt_xyz_vector_2_cyl_smp::overwrite_vector_2_cyl_smp().
Referenced by overwrite_nodal_xyz_2_cyl().
overwrite_nodal_xyz_2_sph()
subroutine coordinate_convert_4_sph::overwrite_nodal_xyz_2_sph (type(node_data), intent(in) node, type(phys_data), intent(inout) nod_fld)
Definition at line 90 of file coordinate_convert_4_sph.f90.
References overwrite_nodal_xyz_2_sph_smp().
Referenced by sph_rtp_zonal_rms_data::zonal_mean_all_rtp_field(), and sph_rtp_zonal_rms_data::zonal_rms_all_rtp_field().
overwrite_nodal_xyz_2_sph_smp()
subroutine coordinate_convert_4_sph::overwrite_nodal_xyz_2_sph_smp (type(node_data), intent(in) node, integer(kind = kint), intent(in) ntot_comp, integer(kind = kint), intent(in) i_fld, integer(kind = kint), intent(in) numdir, real(kind = kreal), dimension(node%numnod,ntot_comp), intent(inout) d_nod)
Definition at line 222 of file coordinate_convert_4_sph.f90.
References m_machine_parameter::np_smp, cvt_xyz_tensor_2_sph_smp::overwrite_sph_tensor_smp(), and cvt_xyz_vector_2_sph_smp::overwrite_vector_2_sph_smp().
Referenced by overwrite_nodal_xyz_2_sph().