CALYPSO: t_mesh_data Module Reference
t_mesh_data Module Reference
Structure for mesh data including geometry, connectivity, and groups.
Data Types
type mesh_data
Structure for mesh data (position, connectivity, group, and communication)
type mesh_geometry
Structure for grid data (position, connectivity, and communication)
type mesh_groups
Structure for group data (node, element, surface, and infinity)
Functions/Subroutines
subroutine dealloc_mesh_infos_w_normal (mesh, group)
subroutine dealloc_mesh_infomations (mesh, group)
subroutine dealloc_nod_ele_infos (mesh, group)
subroutine dealloc_mesh_infos (mesh, group)
subroutine dealloc_groups_data (group)
subroutine dealloc_mesh_type (mesh)
subroutine dealloc_mesh_geometry_base (mesh)
subroutine dealloc_node_geometry_io (mesh)
subroutine dealloc_ele_surf_edge_type (mesh)
subroutine check_mesh_smp_size (id_rank, mesh)
subroutine check_surf_edge_smp_size (mesh)
subroutine compare_mesh_groups (id_rank, group_ref, group)
Detailed Description
Structure for mesh data including geometry, connectivity, and groups.
Function/Subroutine Documentation
check_mesh_smp_size()
subroutine t_mesh_data::check_mesh_smp_size (integer, intent(in) id_rank, type(mesh_geometry), intent(in) mesh)
Definition at line 253 of file t_mesh_data.f90.
check_surf_edge_smp_size()
subroutine t_mesh_data::check_surf_edge_smp_size (type(mesh_geometry), intent(in) mesh)
Definition at line 270 of file t_mesh_data.f90.
compare_mesh_groups()
subroutine t_mesh_data::compare_mesh_groups (integer, intent(in) id_rank, type(mesh_groups), intent(in) group_ref, type(mesh_groups), intent(in) group)
Definition at line 285 of file t_mesh_data.f90.
References t_group_data::compare_group_types(), and t_group_data::compare_surface_grp_types().
dealloc_ele_surf_edge_type()
subroutine t_mesh_data::dealloc_ele_surf_edge_type (type(mesh_geometry), intent(inout) mesh)
Definition at line 238 of file t_mesh_data.f90.
References t_edge_data::dealloc_edge_4_ele(), t_edge_data::dealloc_edge_connect(), and t_surface_data::deallocate_surface_connect_type().
dealloc_groups_data()
subroutine t_mesh_data::dealloc_groups_data (type(mesh_groups), intent(inout) group)
Definition at line 186 of file t_mesh_data.f90.
References t_group_data::dealloc_group(), and t_group_data::dealloc_sf_group().
Referenced by dealloc_mesh_infos(), mpi_load_mesh_data::mpi_output_mesh(), load_mesh_data::output_mesh(), load_mesh_data::set_mesh(), and copy_mesh_structures::set_mesh_data_from_type().
dealloc_mesh_geometry_base()
subroutine t_mesh_data::dealloc_mesh_geometry_base (type(mesh_geometry), intent(inout) mesh)
Definition at line 213 of file t_mesh_data.f90.
References t_comm_table::dealloc_comm_table(), t_geometry_data::dealloc_node_geometry_base(), and t_geometry_data::deallocate_ele_connect_type().
Referenced by mpi_load_mesh_data::mpi_output_mesh(), load_mesh_data::output_mesh(), copy_mesh_structures::set_mesh_data_from_type(), and load_mesh_data::set_mesh_geometry_data().
dealloc_mesh_infomations()
subroutine t_mesh_data::dealloc_mesh_infomations (type(mesh_geometry), intent(inout) mesh, type(mesh_groups), intent(inout) group)
Definition at line 113 of file t_mesh_data.f90.
References t_edge_data::dealloc_edge_4_ele(), t_edge_data::dealloc_edge_connect(), t_edge_data::dealloc_edge_geometory(), t_edge_data::dealloc_edge_param_smp(), t_surface_data::dealloc_ele_4_surf_type(), t_group_connects::dealloc_grp_connect(), dealloc_nod_ele_infos(), t_surface_group_connect::dealloc_num_surf_grp_nod_smp(), t_surface_group_connect::dealloc_surf_grp_nod(), t_group_connects::dealloc_surf_item_sf_grp_type(), t_surface_data::deallocate_ext_surface_type(), t_surface_data::deallocate_iso_surface_type(), t_surface_data::deallocate_surf_param_smp_type(), t_surface_data::deallocate_surface_connect_type(), and t_surface_data::deallocate_surface_geom_type().
Referenced by dealloc_mesh_infos_w_normal().
dealloc_mesh_infos()
subroutine t_mesh_data::dealloc_mesh_infos (type(mesh_geometry), intent(inout) mesh, type(mesh_groups), intent(inout) group)
Definition at line 172 of file t_mesh_data.f90.
References dealloc_groups_data(), and dealloc_mesh_type().
Referenced by dealloc_nod_ele_infos(), and para_const_kemoview_mesh::pickup_surface_mesh().
dealloc_mesh_infos_w_normal()
subroutine t_mesh_data::dealloc_mesh_infos_w_normal (type(mesh_geometry), intent(inout) mesh, type(mesh_groups), intent(inout) group)
Definition at line 99 of file t_mesh_data.f90.
References dealloc_mesh_infomations(), and t_surface_group_connect::dealloc_vect_surf_grp_nod().
dealloc_mesh_type()
subroutine t_mesh_data::dealloc_mesh_type (type(mesh_geometry), intent(inout) mesh)
Definition at line 200 of file t_mesh_data.f90.
References t_comm_table::dealloc_comm_table(), t_geometry_data::dealloc_node_geometry_w_sph(), and t_geometry_data::deallocate_ele_connect_type().
Referenced by dealloc_mesh_infos().
dealloc_nod_ele_infos()
subroutine t_mesh_data::dealloc_nod_ele_infos (type(mesh_geometry), intent(inout) mesh, type(mesh_groups), intent(inout) group)
Definition at line 149 of file t_mesh_data.f90.
References t_group_data::dealloc_group_smp(), t_edge_data::dealloc_inod_in_edge(), dealloc_mesh_infos(), t_group_data::dealloc_sf_group_smp(), t_geometry_data::deallocate_ele_geometry_type(), t_geometry_data::deallocate_ele_param_smp_type(), t_surface_data::deallocate_inod_in_surf_type(), and t_geometry_data::deallocate_node_param_smp_type().
Referenced by dealloc_mesh_infomations().
dealloc_node_geometry_io()
subroutine t_mesh_data::dealloc_node_geometry_io (type(mesh_geometry), intent(inout) mesh)
Definition at line 226 of file t_mesh_data.f90.
References t_comm_table::dealloc_neib_id(), and t_geometry_data::dealloc_node_geometry_base().
Referenced by load_mesh_data::set_node_geometry_data(), mesh_file_io::write_node_position_cyl(), and mesh_file_io::write_node_position_sph().