CALYPSO: t_viewer_mesh Module Reference
t_viewer_mesh Module Reference
Structure of surface information for pickup surface.
Data Types
type viewer_mesh_data
Functions/Subroutines
subroutine alloc_nod_position_viewer (view_mesh)
subroutine alloc_surf_type_viewer (view_mesh)
subroutine alloc_edge_type_viewer (view_mesh)
subroutine alloc_surf_connect_viewer (nnod_4_surf, view_mesh)
subroutine alloc_edge_data_4_sf (nnod_4_edge, view_mesh)
subroutine dealloc_nod_position_viewer (view_mesh)
subroutine dealloc_surf_type_viewer (view_mesh)
subroutine dealloc_edge_type_viewer (view_mesh)
subroutine dealloc_surf_connect_viewer (view_mesh)
subroutine dealloc_edge_data_4_sf (view_mesh)
Variables
integer(kind=kint), parameter surface_id = 15
Detailed Description
Structure of surface information for pickup surface.
      subroutine alloc_nod_position_viewer(view_mesh)
      subroutine alloc_surf_type_viewer(view_mesh)
      subroutine alloc_edge_type_viewer(view_mesh)
      subroutine alloc_surf_connect_viewer(nnod_4_surf, view_mesh)
      subroutine alloc_edge_data_4_sf(nnod_4_edge, view_mesh)
        type(viewer_mesh_data), intent(inout) :: view_mesh
      subroutine dealloc_nod_position_viewer(view_mesh)
      subroutine dealloc_surf_type_viewer(view_mesh)
      subroutine dealloc_edge_type_viewer(view_mesh)
      subroutine dealloc_surf_connect_viewer(view_mesh)
      subroutine dealloc_edge_data_4_sf(view_mesh)
        type(viewer_mesh_data), intent(inout) :: view_mesh
Function/Subroutine Documentation
alloc_edge_data_4_sf()
subroutine t_viewer_mesh::alloc_edge_data_4_sf (integer(kind = kint), intent(in) nnod_4_edge, type(viewer_mesh_data), intent(inout) view_mesh)
Definition at line 121 of file t_viewer_mesh.f90.
References m_geometry_constants::nedge_4_surf.
Referenced by const_edge_4_viewer::const_all_edge_4_viewer().
alloc_edge_type_viewer()
subroutine t_viewer_mesh::alloc_edge_type_viewer (type(viewer_mesh_data), intent(inout) view_mesh)
Definition at line 89 of file t_viewer_mesh.f90.
alloc_nod_position_viewer()
subroutine t_viewer_mesh::alloc_nod_position_viewer (type(viewer_mesh_data), intent(inout) view_mesh)
Definition at line 63 of file t_viewer_mesh.f90.
Referenced by set_nodes_4_viewer::s_set_nodes_4_viewer().
alloc_surf_connect_viewer()
subroutine t_viewer_mesh::alloc_surf_connect_viewer (integer(kind = kint), intent(in) nnod_4_surf, type(viewer_mesh_data), intent(inout) view_mesh)
Definition at line 103 of file t_viewer_mesh.f90.
Referenced by set_surf_connect_4_viewer::s_set_surf_connect_4_viewer().
alloc_surf_type_viewer()
subroutine t_viewer_mesh::alloc_surf_type_viewer (type(viewer_mesh_data), intent(inout) view_mesh)
Definition at line 76 of file t_viewer_mesh.f90.
Referenced by const_kemoview_mesh::set_surf_domain_id_viewer().
dealloc_edge_data_4_sf()
subroutine t_viewer_mesh::dealloc_edge_data_4_sf (type(viewer_mesh_data), intent(inout) view_mesh)
Definition at line 186 of file t_viewer_mesh.f90.
dealloc_edge_type_viewer()
subroutine t_viewer_mesh::dealloc_edge_type_viewer (type(viewer_mesh_data), intent(inout) view_mesh)
Definition at line 165 of file t_viewer_mesh.f90.
dealloc_nod_position_viewer()
subroutine t_viewer_mesh::dealloc_nod_position_viewer (type(viewer_mesh_data), intent(inout) view_mesh)
Definition at line 145 of file t_viewer_mesh.f90.
dealloc_surf_connect_viewer()
subroutine t_viewer_mesh::dealloc_surf_connect_viewer (type(viewer_mesh_data), intent(inout) view_mesh)
Definition at line 176 of file t_viewer_mesh.f90.
dealloc_surf_type_viewer()
subroutine t_viewer_mesh::dealloc_surf_type_viewer (type(viewer_mesh_data), intent(inout) view_mesh)
Definition at line 155 of file t_viewer_mesh.f90.
Variable Documentation
surface_id
integer (kind = kint), parameter t_viewer_mesh::surface_id = 15
Definition at line 33 of file t_viewer_mesh.f90.
Referenced by viewer_group_data_io::write_domain_group_viewer(), viewer_mesh_data_io::write_edge_connect_viewer(), viewer_group_data_io::write_ele_group_viewer(), viewer_group_data_io::write_nod_group_viewer(), viewer_mesh_data_io::write_node_data_viewer(), viewer_mesh_data_io::write_sgl_domain_data_viewer(), viewer_mesh_data_io::write_surf_connect_viewer(), and viewer_group_data_io::write_surf_group_viewer().