CALYPSO: m_intersection_data_6 Module Reference
m_intersection_data_6 Module Reference
Variables
integer(kind=kint), parameter, private nnod_tri = 3
integer(kind=kint), parameter, private nnod_sep = 7
integer(kind=kint), parameter nkind_etype_6 = 24
integer(kind=kint), parameter num_patch_6 = 5
integer(kind=kint), dimension(15), parameter itri_2_patch_6 = (/6, 7, 5, 5, 7, 1, 5, 1, 4, 4, 1, 2, 4, 2, 3/)
integer(kind=kint), dimension(nkind_etype_6), parameter iflag_psf_etype_6p = (/131, 22, 44, 73, 56, 97, 194, 148, 21, 42, 69, 138, 67, 134, 28, 41, 52, 104, 193, 146, 81, 162, 84, 168/)
integer(kind=kint), dimension(nkind_etype_6), parameter iflag_psf_etype_6n = (/124, 233, 211, 182, 199, 158, 61, 107, 234, 213, 186, 117, 188, 121, 227, 214, 203, 151, 62, 109, 174, 93, 171, 87/)
integer(kind=kint), dimension(nnod_sep, nkind_etype_6), parameter iedge_sep_6p = reshape((/ 7,12, 4, 2,10, 9, 8, 8, 9, 1, 3,11,10, 5, 5,10, 2, 4,12,11, 6, 6,11, 3, 1, 9,12, 7, 3, 4, 9,10, 6, 8,12, 4, 1,10,11, 7, 5, 9, 1, 2,11,12, 8, 6,10, 2, 3,12, 9, 5, 7,11, 11, 2, 1, 5, 8, 4, 3, 12, 3, 2, 6, 5, 1, 4, 9, 4, 3, 7, 6, 2, 1, 10, 1, 4, 8, 7, 3, 2, 7, 6,10, 9, 4, 2,11, 8, 7,11,10, 1, 3,12, 5, 8,12,11, 2, 4, 9, 6, 5, 9,12, 3, 1,10, 3,11, 6, 8, 9,10, 2, 4,12, 7, 5,10,11, 3, 1, 9, 8, 6,11,12, 4, 2,10, 5, 7,12, 9, 1, 11, 7, 8, 4, 1, 5, 6, 12, 8, 5, 1, 2, 6, 7, 9, 5, 6, 2, 3, 7, 8, 10, 6, 7, 3, 4, 8, 5/), shape=(/nnod_sep, nkind_etype_6/))
integer(kind=kint), dimension(nnod_sep, nkind_etype_6), parameter iedge_sep_6n = reshape((/ 7, 8, 9,10, 2, 4,12, 8, 5,10,11, 3, 1, 9, 5, 6,11,12, 4, 2,10, 6, 7,12, 9, 1, 3,11, 3,12, 8, 6,10, 9, 4, 4, 9, 5, 7,11,10, 1, 1,10, 6, 8,12,11, 2, 2,11, 7, 5, 9,12, 3, 11, 3, 4, 8, 5, 1, 2, 12, 4, 1, 5, 6, 2, 3, 9, 1, 2, 6, 7, 3, 4, 10, 2, 3, 7, 8, 4, 1, 7,11, 2, 4, 9,10, 6, 8,12, 3, 1,10,11, 7, 5, 9, 4, 2,11,12, 8, 6,10, 1, 3,12, 9, 5, 3, 2,10, 9, 8, 6,11, 4, 3,11,10, 5, 7,12, 1, 4,12,11, 6, 8, 9, 2, 1, 9,12, 7, 5,10, 11, 6, 5, 1, 4, 8, 7, 12, 7, 6, 2, 1, 5, 8, 9, 8, 7, 3, 2, 6, 5, 10, 5, 8, 4, 3, 7, 6 /), shape=(/nnod_sep, nkind_etype_6/))
integer(kind=kint), dimension(nnod_tri, num_patch_6, nkind_etype_6), parameter iedge_4_patch_6p = reshape((/ 9, 8,10, 10, 8, 7, 10, 7, 2, 2, 7,12, 2,12, 4, 10, 5,11, 11, 5, 8, 11, 8, 3, 3, 8, 9, 3, 9, 1, 11, 6,12, 12, 6, 5, 12, 5, 4, 4, 5,10, 4,10, 2, 12, 7, 9, 9, 7, 6, 9, 6, 1, 1, 6,11, 1,11, 3, 8,12, 6, 6,12, 3, 6, 3,10, 10, 3, 4, 10, 4, 9, 5, 9, 7, 7, 9, 4, 7, 4,11, 11, 4, 1, 11, 1,10, 6,10, 8, 8,10, 1, 8, 1,12, 12, 1, 2, 12, 2,11, 7,11, 5, 5,11, 2, 5, 2, 9, 9, 2, 3, 9, 3,12, 4, 3, 8, 8, 3,11, 8,11, 5, 5,11, 2, 5, 2, 1, 1, 4, 5, 5, 4,12, 5,12, 6, 6,12, 3, 6, 3, 2, 2, 1, 6, 6, 1, 9, 6, 9, 7, 7, 9, 4, 7, 4, 3, 3, 2, 7, 7, 2,10, 7,10, 8, 8,10, 1, 8, 1, 4, 2,11, 4, 4,11, 7, 4, 7, 9, 9, 7, 6, 9, 6,10, 3,12, 1, 1,12, 8, 1, 8,10, 10, 8, 7, 10, 7,11, 4, 9, 2, 2, 9, 5, 2, 5,11, 11, 5, 8, 11, 8,12, 1,10, 3, 3,10, 6, 3, 6,12, 12, 6, 5, 12, 5, 9, 10, 2, 9, 9, 2, 3, 9, 3, 8, 8, 3,11, 8,11, 6, 11, 3,10, 10, 3, 4, 10, 4, 5, 5, 4,12, 5,12, 7, 12, 4,11, 11, 4, 1, 11, 1, 6, 6, 1, 9, 6, 9, 8, 9, 1,12, 12, 1, 2, 12, 2, 7, 7, 2,10, 7,10, 5, 5, 6, 1, 1, 6,11, 1,11, 4, 4,11, 7, 4, 7, 8, 6, 7, 2, 2, 7,12, 2,12, 1, 1,12, 8, 1, 8, 5, 7, 8, 3, 3, 8, 9, 3, 9, 2, 2, 9, 5, 2, 5, 6, 8, 5, 4, 4, 5,10, 4,10, 3, 3,10, 6, 3, 6, 7/), shape=(/nnod_tri,num_patch_6,nkind_etype_6/))
integer(kind=kint), dimension(nnod_tri, num_patch_6, nkind_etype_6), parameter iedge_4_patch_6n = reshape((/ 4,12, 2, 2,12, 7, 2, 7,10, 10, 7, 8, 10, 8, 9, 1, 9, 3, 3, 9, 8, 3, 8,11, 11, 8, 5, 11, 5,10, 2,10, 4, 4,10, 5, 4, 5,12, 12, 5, 6, 12, 6,11, 3,11, 1, 1,11, 6, 1, 6, 9, 9, 6, 7, 9, 7,12, 9, 4,10, 10, 4, 3, 10, 3, 6, 6, 3,12, 6,12, 8, 10, 1,11, 11, 1, 4, 11, 4, 7, 7, 4, 9, 7, 9, 5, 11, 2,12, 12, 2, 1, 12, 1, 8, 8, 1,10, 8,10, 6, 12, 3, 9, 9, 3, 2, 9, 2, 5, 5, 2,11, 5,11, 7, 1, 2, 5, 5, 2,11, 5,11, 8, 8,11, 3, 8, 3, 4, 2, 3, 6, 6, 3,12, 6,12, 5, 5,12, 4, 5, 4, 1, 3, 4, 7, 7, 4, 9, 7, 9, 6, 6, 9, 1, 6, 1, 2, 4, 1, 8, 8, 1,10, 8,10, 7, 7,10, 2, 7, 2, 3, 10, 6, 9, 9, 6, 7, 9, 7, 4, 4, 7,11, 4,11, 2, 11, 7,10, 10, 7, 8, 10, 8, 1, 1, 8,12, 1,12, 3, 12, 8,11, 11, 8, 5, 11, 5, 2, 2, 5, 9, 2, 9, 4, 9, 5,12, 12, 5, 6, 12, 6, 3, 3, 6,10, 3,10, 1, 6,11, 8, 8,11, 3, 8, 3, 9, 9, 3, 2, 9, 2,10, 7,12, 5, 5,12, 4, 5, 4,10, 10, 4, 3, 10, 3,11, 8, 9, 6, 6, 9, 1, 6, 1,11, 11, 1, 4, 11, 4,12, 5,10, 7, 7,10, 2, 7, 2,12, 12, 2, 1, 12, 1, 9, 8, 7, 4, 4, 7,11, 4,11, 1, 1,11, 6, 1, 6, 5, 5, 8, 1, 1, 8,12, 1,12, 2, 2,12, 7, 2, 7, 6, 6, 5, 2, 2, 5, 9, 2, 9, 3, 3, 9, 8, 3, 8, 7, 7, 6, 3, 3, 6,10, 3,10, 4, 4,10, 5, 4, 5, 8/), shape=(/nnod_tri,num_patch_6,nkind_etype_6/))
Variable Documentation
iedge_4_patch_6n
integer(kind = kint), dimension(nnod_tri,num_patch_6,nkind_etype_6), parameter m_intersection_data_6::iedge_4_patch_6n = reshape((/ 4,12, 2, 2,12, 7, 2, 7,10, 10, 7, 8, 10, 8, 9, 1, 9, 3, 3, 9, 8, 3, 8,11, 11, 8, 5, 11, 5,10, 2,10, 4, 4,10, 5, 4, 5,12, 12, 5, 6, 12, 6,11, 3,11, 1, 1,11, 6, 1, 6, 9, 9, 6, 7, 9, 7,12, 9, 4,10, 10, 4, 3, 10, 3, 6, 6, 3,12, 6,12, 8, 10, 1,11, 11, 1, 4, 11, 4, 7, 7, 4, 9, 7, 9, 5, 11, 2,12, 12, 2, 1, 12, 1, 8, 8, 1,10, 8,10, 6, 12, 3, 9, 9, 3, 2, 9, 2, 5, 5, 2,11, 5,11, 7, 1, 2, 5, 5, 2,11, 5,11, 8, 8,11, 3, 8, 3, 4, 2, 3, 6, 6, 3,12, 6,12, 5, 5,12, 4, 5, 4, 1, 3, 4, 7, 7, 4, 9, 7, 9, 6, 6, 9, 1, 6, 1, 2, 4, 1, 8, 8, 1,10, 8,10, 7, 7,10, 2, 7, 2, 3, 10, 6, 9, 9, 6, 7, 9, 7, 4, 4, 7,11, 4,11, 2, 11, 7,10, 10, 7, 8, 10, 8, 1, 1, 8,12, 1,12, 3, 12, 8,11, 11, 8, 5, 11, 5, 2, 2, 5, 9, 2, 9, 4, 9, 5,12, 12, 5, 6, 12, 6, 3, 3, 6,10, 3,10, 1, 6,11, 8, 8,11, 3, 8, 3, 9, 9, 3, 2, 9, 2,10, 7,12, 5, 5,12, 4, 5, 4,10, 10, 4, 3, 10, 3,11, 8, 9, 6, 6, 9, 1, 6, 1,11, 11, 1, 4, 11, 4,12, 5,10, 7, 7,10, 2, 7, 2,12, 12, 2, 1, 12, 1, 9, 8, 7, 4, 4, 7,11, 4,11, 1, 1,11, 6, 1, 6, 5, 5, 8, 1, 1, 8,12, 1,12, 2, 2,12, 7, 2, 7, 6, 6, 5, 2, 2, 5, 9, 2, 9, 3, 3, 9, 8, 3, 8, 7, 7, 6, 3, 3, 6,10, 3,10, 4, 4,10, 5, 4, 5, 8/), shape=(/nnod_tri,num_patch_6,nkind_etype_6/))
Definition at line 218 of file m_intersection_data_6.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
iedge_4_patch_6p
integer(kind = kint), dimension(nnod_tri,num_patch_6,nkind_etype_6), parameter m_intersection_data_6::iedge_4_patch_6p = reshape((/ 9, 8,10, 10, 8, 7, 10, 7, 2, 2, 7,12, 2,12, 4, 10, 5,11, 11, 5, 8, 11, 8, 3, 3, 8, 9, 3, 9, 1, 11, 6,12, 12, 6, 5, 12, 5, 4, 4, 5,10, 4,10, 2, 12, 7, 9, 9, 7, 6, 9, 6, 1, 1, 6,11, 1,11, 3, 8,12, 6, 6,12, 3, 6, 3,10, 10, 3, 4, 10, 4, 9, 5, 9, 7, 7, 9, 4, 7, 4,11, 11, 4, 1, 11, 1,10, 6,10, 8, 8,10, 1, 8, 1,12, 12, 1, 2, 12, 2,11, 7,11, 5, 5,11, 2, 5, 2, 9, 9, 2, 3, 9, 3,12, 4, 3, 8, 8, 3,11, 8,11, 5, 5,11, 2, 5, 2, 1, 1, 4, 5, 5, 4,12, 5,12, 6, 6,12, 3, 6, 3, 2, 2, 1, 6, 6, 1, 9, 6, 9, 7, 7, 9, 4, 7, 4, 3, 3, 2, 7, 7, 2,10, 7,10, 8, 8,10, 1, 8, 1, 4, 2,11, 4, 4,11, 7, 4, 7, 9, 9, 7, 6, 9, 6,10, 3,12, 1, 1,12, 8, 1, 8,10, 10, 8, 7, 10, 7,11, 4, 9, 2, 2, 9, 5, 2, 5,11, 11, 5, 8, 11, 8,12, 1,10, 3, 3,10, 6, 3, 6,12, 12, 6, 5, 12, 5, 9, 10, 2, 9, 9, 2, 3, 9, 3, 8, 8, 3,11, 8,11, 6, 11, 3,10, 10, 3, 4, 10, 4, 5, 5, 4,12, 5,12, 7, 12, 4,11, 11, 4, 1, 11, 1, 6, 6, 1, 9, 6, 9, 8, 9, 1,12, 12, 1, 2, 12, 2, 7, 7, 2,10, 7,10, 5, 5, 6, 1, 1, 6,11, 1,11, 4, 4,11, 7, 4, 7, 8, 6, 7, 2, 2, 7,12, 2,12, 1, 1,12, 8, 1, 8, 5, 7, 8, 3, 3, 8, 9, 3, 9, 2, 2, 9, 5, 2, 5, 6, 8, 5, 4, 4, 5,10, 4,10, 3, 3,10, 6, 3, 6, 7/), shape=(/nnod_tri,num_patch_6,nkind_etype_6/))
Definition at line 189 of file m_intersection_data_6.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
iedge_sep_6n
integer(kind = kint), dimension(nnod_sep, nkind_etype_6), parameter m_intersection_data_6::iedge_sep_6n = reshape((/ 7, 8, 9,10, 2, 4,12, 8, 5,10,11, 3, 1, 9, 5, 6,11,12, 4, 2,10, 6, 7,12, 9, 1, 3,11, 3,12, 8, 6,10, 9, 4, 4, 9, 5, 7,11,10, 1, 1,10, 6, 8,12,11, 2, 2,11, 7, 5, 9,12, 3, 11, 3, 4, 8, 5, 1, 2, 12, 4, 1, 5, 6, 2, 3, 9, 1, 2, 6, 7, 3, 4, 10, 2, 3, 7, 8, 4, 1, 7,11, 2, 4, 9,10, 6, 8,12, 3, 1,10,11, 7, 5, 9, 4, 2,11,12, 8, 6,10, 1, 3,12, 9, 5, 3, 2,10, 9, 8, 6,11, 4, 3,11,10, 5, 7,12, 1, 4,12,11, 6, 8, 9, 2, 1, 9,12, 7, 5,10, 11, 6, 5, 1, 4, 8, 7, 12, 7, 6, 2, 1, 5, 8, 9, 8, 7, 3, 2, 6, 5, 10, 5, 8, 4, 3, 7, 6 /), shape=(/nnod_sep, nkind_etype_6/))
Definition at line 171 of file m_intersection_data_6.f90.
iedge_sep_6p
integer(kind = kint), dimension(nnod_sep, nkind_etype_6), parameter m_intersection_data_6::iedge_sep_6p = reshape((/ 7,12, 4, 2,10, 9, 8, 8, 9, 1, 3,11,10, 5, 5,10, 2, 4,12,11, 6, 6,11, 3, 1, 9,12, 7, 3, 4, 9,10, 6, 8,12, 4, 1,10,11, 7, 5, 9, 1, 2,11,12, 8, 6,10, 2, 3,12, 9, 5, 7,11, 11, 2, 1, 5, 8, 4, 3, 12, 3, 2, 6, 5, 1, 4, 9, 4, 3, 7, 6, 2, 1, 10, 1, 4, 8, 7, 3, 2, 7, 6,10, 9, 4, 2,11, 8, 7,11,10, 1, 3,12, 5, 8,12,11, 2, 4, 9, 6, 5, 9,12, 3, 1,10, 3,11, 6, 8, 9,10, 2, 4,12, 7, 5,10,11, 3, 1, 9, 8, 6,11,12, 4, 2,10, 5, 7,12, 9, 1, 11, 7, 8, 4, 1, 5, 6, 12, 8, 5, 1, 2, 6, 7, 9, 5, 6, 2, 3, 7, 8, 10, 6, 7, 3, 4, 8, 5/), shape=(/nnod_sep, nkind_etype_6/))
Definition at line 154 of file m_intersection_data_6.f90.
iflag_psf_etype_6n
integer(kind = kint), dimension(nkind_etype_6), parameter m_intersection_data_6::iflag_psf_etype_6n = (/124, 233, 211, 182, 199, 158, 61, 107, 234, 213, 186, 117, 188, 121, 227, 214, 203, 151, 62, 109, 174, 93, 171, 87/)
Definition at line 147 of file m_intersection_data_6.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
iflag_psf_etype_6p
integer(kind = kint), dimension(nkind_etype_6), parameter m_intersection_data_6::iflag_psf_etype_6p = (/131, 22, 44, 73, 56, 97, 194, 148, 21, 42, 69, 138, 67, 134, 28, 41, 52, 104, 193, 146, 81, 162, 84, 168/)
Definition at line 142 of file m_intersection_data_6.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
itri_2_patch_6
integer(kind = kint), dimension(15), parameter m_intersection_data_6::itri_2_patch_6 = (/6, 7, 5, 5, 7, 1, 5, 1, 4, 4, 1, 2, 4, 2, 3/)
Definition at line 24 of file m_intersection_data_6.f90.
nkind_etype_6
integer(kind = kint), parameter m_intersection_data_6::nkind_etype_6 = 24
Definition at line 22 of file m_intersection_data_6.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
nnod_sep
integer(kind = kint), parameter, private m_intersection_data_6::nnod_sep = 7 private
Definition at line 20 of file m_intersection_data_6.f90.
nnod_tri
integer(kind = kint), parameter, private m_intersection_data_6::nnod_tri = 3 private
Definition at line 19 of file m_intersection_data_6.f90.
num_patch_6
integer(kind = kint), parameter m_intersection_data_6::num_patch_6 = 5
Definition at line 23 of file m_intersection_data_6.f90.
Referenced by t_psf_case_table::init_psf_case_tables().