CALYPSO: parallel_load_data_4_sph Module Reference
parallel_load_data_4_sph Module Reference
Load spherical harmonics indexing data on multiple processes.
Functions/Subroutines
subroutine load_sph_mesh (sph_file_param, sph, comms_sph, sph_grps)
subroutine load_sph_rj_mesh (sph_file_param, sph_params, sph_rj, comm_rj, sph_grps)
subroutine output_sph_mesh (sph_file_param, sph, comms_sph, sph_grps)
subroutine output_sph_rj_mesh (sph_file_param, sph, comms_sph, sph_grps)
subroutine sph_index_flags_and_params (sph_grps, sph, comms_sph)
subroutine sph_rj_index_flags_and_params (sph_grps, sph_params, sph_rj, comm_rj)
subroutine, private set_radius_dat_sph_mhd (radial_rj_grp, sph_params, sph_rj)
subroutine dealloc_sph_modes (sph, comms_sph, sph_grps)
Variables
type(sph_file_data_type), save, private sph_file_l
Detailed Description
Load spherical harmonics indexing data on multiple processes.
      subroutine load_sph_mesh                                        &
     &         (sph_file_param, sph, comms_sph, sph_grps)
        type(field_IO_params), intent(in) ::  sph_file_param
        type(sph_grids), intent(inout) :: sph
        type(sph_comm_tables), intent(inout) :: comms_sph
        type(sph_group_data), intent(inout) ::  sph_grps
      subroutine load_sph_rj_mesh                                     &
     &         (sph_file_param, sph_params, sph_rj, comm_rj, sph_grps)
        type(field_IO_params), intent(in) :: sph_file_param
        type(sph_shell_parameters), intent(inout) :: sph_params
        type(sph_rj_grid), intent(inout) :: sph_rj
        type(sph_comm_tbl), intent(inout) :: comm_rj
        type(sph_group_data), intent(inout) ::  sph_grps
      subroutine output_sph_mesh                                      &
     &         (sph_file_param, sph, comms_sph, sph_grps)
      subroutine output_sph_rj_mesh                                   &
     &         (sph_file_param, sph, comms_sph, sph_grps)
        type(field_IO_params), intent(in) :: sph_file_param
        type(sph_grids), intent(inout) :: sph
        type(sph_comm_tables), intent(inout) :: comms_sph
        type(sph_group_data), intent(inout) :: sph_grps
      subroutine sph_index_flags_and_params(sph_grps, sph, comms_sph)
        type(sph_group_data), intent(in) ::  sph_grps
        type(sph_grids), intent(inout) :: sph
        type(sph_comm_tables), intent(inout) :: comms_sph
      subroutine sph_rj_index_flags_and_params                        &
     &         (sph_grps, sph_params, sph_rj, comm_rj)
        type(sph_group_data), intent(in) ::  sph_grps
        type(sph_shell_parameters), intent(inout) :: sph_params
        type(sph_rj_grid), intent(inout) :: sph_rj
        type(sph_comm_tbl), intent(inout) :: comm_rj
      subroutine dealloc_sph_modes(sph, comms_sph, sph_grps)
        type(sph_grids), intent(inout) :: sph
        type(sph_comm_tables), intent(inout) :: comms_sph
        type(sph_group_data), intent(inout) :: sph_grps
Function/Subroutine Documentation
dealloc_sph_modes()
subroutine parallel_load_data_4_sph::dealloc_sph_modes (type(sph_grids), intent(inout) sph, type(sph_comm_tables), intent(inout) comms_sph, type(sph_group_data), intent(inout) sph_grps)
Definition at line 329 of file parallel_load_data_4_sph.f90.
References t_spheric_parameter::dealloc_sph_1d_indices(), t_sph_trans_comm_tbl::dealloc_sph_comms_item(), t_spheric_group::dealloc_sph_grid_group(), t_spheric_group::dealloc_sph_mode_group(), and t_spheric_parameter::dealloc_spheric_parameter().
Referenced by analyzer_check_sph_grids::analyze_check_sph_grids(), analyzer_gen_sph_grids::analyze_gen_sph_grids(), and output_gen_sph_grid_modes::para_output_sph_mode_grids().
load_sph_mesh()
subroutine parallel_load_data_4_sph::load_sph_mesh (type(field_io_params), intent(in) sph_file_param, type(sph_grids), intent(inout) sph, type(sph_comm_tables), intent(inout) comms_sph, type(sph_group_data), intent(inout) sph_grps)
Definition at line 79 of file parallel_load_data_4_sph.f90.
References load_data_for_sph_io::copy_sph_trans_rj_from_io(), load_data_for_sph_io::copy_sph_trans_rlm_from_io(), load_data_for_sph_io::copy_sph_trans_rtm_from_io(), load_data_for_sph_io::copy_sph_trans_rtp_from_io(), t_spheric_data_io::dealloc_rj_mode_io(), t_spheric_data_io::dealloc_rlm_mode_io(), t_spheric_data_io::dealloc_rtm_grid_io(), t_spheric_data_io::dealloc_rtp_grid_io(), m_machine_parameter::iflag_debug, calypso_mpi::my_rank, calypso_mpi::nprocs, sph_file_mpi_io_select::sel_mpi_read_geom_rtm_file(), sph_file_mpi_io_select::sel_mpi_read_geom_rtp_file(), sph_file_mpi_io_select::sel_mpi_read_modes_rlm_file(), sph_file_mpi_io_select::sel_mpi_read_spectr_rj_file(), and sph_file_l.
Referenced by t_check_and_make_sph_mesh::check_and_make_sph_mesh(), and input_control_dynamobench::input_control_sph_dynamobench().
load_sph_rj_mesh()
subroutine parallel_load_data_4_sph::load_sph_rj_mesh (type(field_io_params), intent(in) sph_file_param, type(sph_shell_parameters), intent(inout) sph_params, type(sph_rj_grid), intent(inout) sph_rj, type(sph_comm_tbl), intent(inout) comm_rj, type(sph_group_data), intent(inout) sph_grps)
Definition at line 122 of file parallel_load_data_4_sph.f90.
References load_data_for_sph_io::copy_sph_trans_rj_from_io(), t_spheric_data_io::dealloc_rj_mode_io(), m_machine_parameter::iflag_debug, calypso_mpi::my_rank, calypso_mpi::nprocs, sph_file_mpi_io_select::sel_mpi_read_spectr_rj_file(), and sph_file_l.
Referenced by t_check_and_make_sph_mesh::check_and_make_sph_rj_mode().
output_sph_mesh()
subroutine parallel_load_data_4_sph::output_sph_mesh (type(field_io_params), intent(in) sph_file_param, type(sph_grids), intent(inout) sph, type(sph_comm_tables), intent(inout) comms_sph, type(sph_group_data), intent(inout) sph_grps)
Definition at line 146 of file parallel_load_data_4_sph.f90.
References load_data_for_sph_io::copy_sph_trans_rj_to_io(), load_data_for_sph_io::copy_sph_trans_rlm_to_io(), load_data_for_sph_io::copy_sph_trans_rtm_to_io(), load_data_for_sph_io::copy_sph_trans_rtp_to_io(), t_spheric_data_io::dealloc_rj_mode_io(), t_spheric_data_io::dealloc_rlm_mode_io(), t_spheric_data_io::dealloc_rtm_grid_io(), t_spheric_data_io::dealloc_rtp_grid_io(), m_machine_parameter::iflag_debug, calypso_mpi::my_rank, sph_file_mpi_io_select::sel_mpi_write_geom_rtm_file(), sph_file_mpi_io_select::sel_mpi_write_geom_rtp_file(), sph_file_mpi_io_select::sel_mpi_write_modes_rlm_file(), sph_file_mpi_io_select::sel_mpi_write_spectr_rj_file(), and sph_file_l.
Referenced by analyzer_gen_sph_grids::analyze_gen_sph_grids(), t_check_and_make_sph_mesh::check_and_make_sph_mesh(), and t_check_and_make_sph_mesh::check_and_make_sph_rj_mode().
output_sph_rj_mesh()
subroutine parallel_load_data_4_sph::output_sph_rj_mesh (type(field_io_params), intent(in) sph_file_param, type(sph_grids), intent(inout) sph, type(sph_comm_tables), intent(inout) comms_sph, type(sph_group_data), intent(inout) sph_grps)
Definition at line 196 of file parallel_load_data_4_sph.f90.
References load_data_for_sph_io::copy_sph_trans_rj_to_io(), t_spheric_data_io::dealloc_rj_mode_io(), m_machine_parameter::iflag_debug, calypso_mpi::my_rank, sph_file_mpi_io_select::sel_mpi_write_spectr_rj_file(), and sph_file_l.
set_radius_dat_sph_mhd()
subroutine, private parallel_load_data_4_sph::set_radius_dat_sph_mhd (type(group_data), intent(in) radial_rj_grp, type(sph_shell_parameters), intent(inout) sph_params, type(sph_rj_grid), intent(inout) sph_rj) private
Definition at line 302 of file parallel_load_data_4_sph.f90.
References m_machine_parameter::iflag_debug, m_machine_parameter::iflag_routine_msg, and set_radius_4_sph_dynamo::set_radius_dat_4_sph_dynamo().
Referenced by sph_index_flags_and_params(), and sph_rj_index_flags_and_params().
sph_index_flags_and_params()
subroutine parallel_load_data_4_sph::sph_index_flags_and_params (type(sph_group_data), intent(in) sph_grps, type(sph_grids), intent(inout) sph, type(sph_comm_tables), intent(inout) comms_sph)
Definition at line 222 of file parallel_load_data_4_sph.f90.
References count_num_sph_smp::count_num_rj_smp(), count_num_sph_smp::count_num_rlm_smp(), count_num_sph_smp::count_num_rtm_smp(), count_num_sph_smp::count_num_rtp_smp(), m_machine_parameter::iflag_debug, pole_sph_transform::init_pole_grids(), set_loaded_data_4_sph::set_index_flags_4_sph(), set_radius_dat_sph_mhd(), and set_from_recv_buf_rev::set_reverse_import_table().
Referenced by analyzer_gen_sph_grids::analyze_gen_sph_grids(), t_check_and_make_sph_mesh::check_and_make_sph_mesh(), and input_control_dynamobench::input_control_sph_dynamobench().
sph_rj_index_flags_and_params()
subroutine parallel_load_data_4_sph::sph_rj_index_flags_and_params (type(sph_group_data), intent(in) sph_grps, type(sph_shell_parameters), intent(inout) sph_params, type(sph_rj_grid), intent(inout) sph_rj, type(sph_comm_tbl), intent(inout) comm_rj)
Definition at line 270 of file parallel_load_data_4_sph.f90.
References count_num_sph_smp::count_num_rj_smp(), set_loaded_data_4_sph::set_index_flags_4_rj(), set_radius_dat_sph_mhd(), and set_from_recv_buf_rev::set_reverse_import_table().
Referenced by t_check_and_make_sph_mesh::check_and_make_sph_rj_mode().
Variable Documentation
sph_file_l
type(sph_file_data_type), save, private parallel_load_data_4_sph::sph_file_l private
Definition at line 69 of file parallel_load_data_4_sph.f90.
Referenced by load_sph_mesh(), load_sph_rj_mesh(), output_sph_mesh(), and output_sph_rj_mesh().