CALYPSO: set_sph_groups Module Reference
set_sph_groups Module Reference
Set groups for spherical harmonics indexing.
Functions/Subroutines
subroutine set_sph_rtp_groups (sph_param, sph_rtp, added_radial_grp, r_layer_grp, med_layer_grp, bc_rtp_grp, radial_rtp_grp, theta_rtp_grp, zonal_rtp_grp)
subroutine set_sph_rj_groups (sph_param, sph_rj, added_radial_grp, radial_rj_grp, sphere_rj_grp)
subroutine, private set_rtp_radial_grp (sph_param, sph_rtp, added_radial_grp, r_layer_grp, radial_rtp_grp)
subroutine, private set_rtp_meridional_grp (sph_rtp, med_layer_grp, theta_rtp_grp)
subroutine set_rj_radial_grp (sph_param, sph_rj, added_radial_grp, radial_rj_grp)
subroutine, private set_rj_spectr_grp (sph_rj, sphere_rj_grp)
subroutine, private set_no_rtp_node_grp (bc_rtp_grp)
subroutine, private set_no_rtp_meridian_grp (theta_rtp_grp)
subroutine, private set_no_rtp_zonal_grp (zonal_rtp_grp)
subroutine, private count_sph_radial_group (num_grp, sph_param, added_radial_grp, nidx_global_r)
subroutine, private add_sph_sgs_radial_group (r_layer_grp, num_grp)
Detailed Description
Set groups for spherical harmonics indexing.
      subroutine set_sph_rtp_groups(sph_param, sph_rtp,               &
     &          added_radial_grp, r_layer_grp, med_layer_grp,         &
     &          bc_rtp_grp, radial_rtp_grp, theta_rtp_grp,            &
     &          zonal_rtp_grp)
        type(sph_shell_parameters), intent(in) :: sph_param
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(group_data), intent(inout) :: bc_rtp_grp
        type(group_data), intent(inout) :: radial_rtp_grp
        type(group_data), intent(inout) :: theta_rtp_grp
        type(group_data), intent(inout) :: zonal_rtp_grp
      subroutine set_sph_rj_groups                                    &
     &         (sph_param, sph_rj, added_radial_grp,                  &
     &          radial_rj_grp, sphere_rj_grp)
        type(sph_shell_parameters), intent(in) :: sph_param
        type(sph_rj_grid), intent(in) :: sph_rj
        type(group_data), intent(inout) :: radial_rj_grp
        type(group_data), intent(inout) :: sphere_rj_grp
      subroutine set_rj_radial_grp                                    &
     &         (sph_param, sph_rj, added_radial_grp, radial_rj_grp)
        type(sph_rj_grid), intent(in) :: sph_rj
        type(group_data), intent(inout) :: radial_rj_grp
        type(group_data), intent(inout) :: sphere_rj_grp
Function/Subroutine Documentation
add_sph_sgs_radial_group()
subroutine, private set_sph_groups::add_sph_sgs_radial_group (type(layering_group_list), intent(in) r_layer_grp, integer(kind = kint), intent(inout) num_grp) private
Definition at line 281 of file set_sph_groups.f90.
Referenced by set_rtp_radial_grp().
count_sph_radial_group()
subroutine, private set_sph_groups::count_sph_radial_group (integer(kind = kint), intent(inout) num_grp, type(sph_shell_parameters), intent(in) sph_param, type(layering_group_list), intent(in) added_radial_grp, integer(kind = kint), intent(in) nidx_global_r) private
Definition at line 263 of file set_sph_groups.f90.
Referenced by set_rj_radial_grp(), and set_rtp_radial_grp().
set_no_rtp_meridian_grp()
subroutine, private set_sph_groups::set_no_rtp_meridian_grp (type(group_data), intent(inout) theta_rtp_grp) private
Definition at line 235 of file set_sph_groups.f90.
References t_group_data::alloc_group_item(), and t_group_data::alloc_group_num().
set_no_rtp_node_grp()
subroutine, private set_sph_groups::set_no_rtp_node_grp (type(group_data), intent(inout) bc_rtp_grp) private
Definition at line 222 of file set_sph_groups.f90.
References t_group_data::alloc_group_item(), and t_group_data::alloc_group_num().
Referenced by set_sph_rtp_groups().
set_no_rtp_zonal_grp()
subroutine, private set_sph_groups::set_no_rtp_zonal_grp (type(group_data), intent(inout) zonal_rtp_grp) private
Definition at line 248 of file set_sph_groups.f90.
References t_group_data::alloc_group_item(), and t_group_data::alloc_group_num().
Referenced by set_sph_rtp_groups().
set_rj_radial_grp()
subroutine set_sph_groups::set_rj_radial_grp (type(sph_shell_parameters), intent(in) sph_param, type(sph_rj_grid), intent(in) sph_rj, type(layering_group_list), intent(in) added_radial_grp, type(group_data), intent(inout) radial_rj_grp)
Definition at line 170 of file set_sph_groups.f90.
References t_group_data::alloc_group_item(), t_group_data::alloc_group_num(), count_sph_radial_group(), set_item_4_sph_groups::set_item_rj_radial_grp(), and set_stack_4_sph_groups::set_stack_rj_radial_grp().
Referenced by set_sph_rj_groups().
set_rj_spectr_grp()
subroutine, private set_sph_groups::set_rj_spectr_grp (type(sph_rj_grid), intent(in) sph_rj, type(group_data), intent(inout) sphere_rj_grp) private
Definition at line 197 of file set_sph_groups.f90.
References t_group_data::alloc_group_item(), t_group_data::alloc_group_num(), set_item_4_sph_groups::set_item_rj_spectr_grp(), and set_stack_4_sph_groups::set_stack_rj_spectr_grp().
Referenced by set_sph_rj_groups().
set_rtp_meridional_grp()
subroutine, private set_sph_groups::set_rtp_meridional_grp (type(sph_rtp_grid), intent(in) sph_rtp, type(layering_group_list), intent(in) med_layer_grp, type(group_data), intent(inout) theta_rtp_grp) private
Definition at line 144 of file set_sph_groups.f90.
References t_group_data::alloc_group_item(), t_group_data::alloc_group_num(), set_item_4_sph_groups::set_item_rtp_meridional_grp(), and set_stack_4_sph_groups::set_stack_rtp_meridional_grp().
Referenced by set_sph_rtp_groups().
set_rtp_radial_grp()
subroutine, private set_sph_groups::set_rtp_radial_grp (type(sph_shell_parameters), intent(in) sph_param, type(sph_rtp_grid), intent(in) sph_rtp, type(layering_group_list), intent(in) added_radial_grp, type(layering_group_list), intent(in) r_layer_grp, type(group_data), intent(inout) radial_rtp_grp) private
Definition at line 113 of file set_sph_groups.f90.
References add_sph_sgs_radial_group(), t_group_data::alloc_group_item(), t_group_data::alloc_group_num(), count_sph_radial_group(), set_item_4_sph_groups::set_item_rtp_radial_grp(), and set_stack_4_sph_groups::set_stack_rtp_radial_grp().
Referenced by set_sph_rtp_groups().
set_sph_rj_groups()
subroutine set_sph_groups::set_sph_rj_groups (type(sph_shell_parameters), intent(in) sph_param, type(sph_rj_grid), intent(in) sph_rj, type(layering_group_list), intent(in) added_radial_grp, type(group_data), intent(inout) radial_rj_grp, type(group_data), intent(inout) sphere_rj_grp)
Definition at line 90 of file set_sph_groups.f90.
References set_rj_radial_grp(), and set_rj_spectr_grp().
Referenced by set_comm_table_rtp_rj::const_sph_rj_modes().
set_sph_rtp_groups()
subroutine set_sph_groups::set_sph_rtp_groups (type(sph_shell_parameters), intent(in) sph_param, type(sph_rtp_grid), intent(in) sph_rtp, type(layering_group_list), intent(in) added_radial_grp, type(layering_group_list), intent(in) r_layer_grp, type(layering_group_list), intent(in) med_layer_grp, type(group_data), intent(inout) bc_rtp_grp, type(group_data), intent(inout) radial_rtp_grp, type(group_data), intent(inout) theta_rtp_grp, type(group_data), intent(inout) zonal_rtp_grp)
Definition at line 57 of file set_sph_groups.f90.
References set_no_rtp_node_grp(), set_no_rtp_zonal_grp(), set_rtp_meridional_grp(), and set_rtp_radial_grp().
Referenced by set_comm_table_rtp_rj::const_sph_rtp_grids().