CALYPSO: mpi_node_geometry_io Module Reference
mpi_node_geometry_io Module Reference
routines for ASCII data IO for mesh geometry
Functions/Subroutines
subroutine mpi_write_geometry_info (IO_param, nod_IO)
subroutine mpi_write_scl_in_ele (IO_param, nod_IO, sfed_IO)
subroutine mpi_write_vect_in_ele (IO_param, nod_IO, sfed_IO)
subroutine mpi_read_number_of_node (IO_param, nod_IO)
subroutine mpi_read_geometry_info (IO_param, nod_IO)
subroutine mpi_read_scl_in_ele (IO_param, nod_IO, sfed_IO)
subroutine mpi_read_vect_in_ele (IO_param, nod_IO, sfed_IO)
Detailed Description
routines for ASCII data IO for mesh geometry
      subroutine mpi_write_geometry_info(IO_param, nod_IO)
      subroutine mpi_write_scl_in_ele(IO_param, nod_IO, sfed_IO)
      subroutine mpi_write_vect_in_ele(IO_param, nod_IO, sfed_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(node_data), intent(in) :: nod_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
      subroutine mpi_read_number_of_node(IO_param, nod_IO)
      subroutine mpi_read_geometry_info(IO_param, nod_IO)
      subroutine mpi_read_scl_in_ele(IO_param, nod_IO, sfed_IO)
      subroutine mpi_read_vect_in_ele(IO_param, nod_IO, sfed_IO)
        type(node_data), intent(inout) :: nod_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
Function/Subroutine Documentation
mpi_read_geometry_info()
subroutine mpi_node_geometry_io::mpi_read_geometry_info (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(inout) nod_IO)
Definition at line 108 of file MPI_node_geometry_IO.f90.
References t_geometry_data::alloc_node_geometry_base(), mpi_position_io::mpi_read_node_position(), and m_phys_constants::n_vector.
Referenced by mpi_edge_data_io::mpi_read_edge_geometry(), mpi_element_data_io::mpi_read_element_geometry(), mpi_mesh_data_io::mpi_read_num_node_ele(), and mpi_surface_data_io::mpi_read_surface_geometry().
mpi_read_number_of_node()
subroutine mpi_node_geometry_io::mpi_read_number_of_node (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(inout) nod_IO)
Definition at line 95 of file MPI_node_geometry_IO.f90.
Referenced by mpi_edge_data_io::mpi_read_edge_geometry(), mpi_element_data_io::mpi_read_element_geometry(), mpi_mesh_data_io::mpi_read_num_node(), mpi_read_scl_in_ele(), mpi_surface_data_io::mpi_read_surface_geometry(), and mpi_read_vect_in_ele().
mpi_read_scl_in_ele()
subroutine mpi_node_geometry_io::mpi_read_scl_in_ele (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 126 of file MPI_node_geometry_IO.f90.
References t_surf_edge_io::alloc_ele_scalar_io(), mpi_read_number_of_node(), and mpi_vectors_io::mpi_read_scalar().
Referenced by mpi_edge_data_io::mpi_read_edge_geometry(), mpi_element_data_io::mpi_read_element_geometry(), and mpi_surface_data_io::mpi_read_surface_geometry().
mpi_read_vect_in_ele()
subroutine mpi_node_geometry_io::mpi_read_vect_in_ele (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 142 of file MPI_node_geometry_IO.f90.
References t_surf_edge_io::alloc_ele_vector_io(), mpi_read_number_of_node(), mpi_vectors_io::mpi_read_vector(), and m_phys_constants::n_vector.
Referenced by mpi_edge_data_io::mpi_read_edge_geometry(), and mpi_surface_data_io::mpi_read_surface_geometry().
mpi_write_geometry_info()
subroutine mpi_node_geometry_io::mpi_write_geometry_info (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(in) nod_IO)
Definition at line 45 of file MPI_node_geometry_IO.f90.
References mpi_position_io::mpi_write_node_position().
Referenced by mpi_edge_data_io::mpi_write_edge_geometry(), mpi_element_data_io::mpi_write_element_geometry(), mpi_mesh_data_io::mpi_write_geometry_data(), and mpi_surface_data_io::mpi_write_surface_geometry().
mpi_write_scl_in_ele()
subroutine mpi_node_geometry_io::mpi_write_scl_in_ele (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 64 of file MPI_node_geometry_IO.f90.
References mpi_vectors_io::mpi_write_scalar().
Referenced by mpi_edge_data_io::mpi_write_edge_geometry(), mpi_element_data_io::mpi_write_element_geometry(), and mpi_surface_data_io::mpi_write_surface_geometry().
mpi_write_vect_in_ele()
subroutine mpi_node_geometry_io::mpi_write_vect_in_ele (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 79 of file MPI_node_geometry_IO.f90.
References mpi_vectors_io::mpi_write_vector(), and m_phys_constants::n_vector.
Referenced by mpi_edge_data_io::mpi_write_edge_geometry(), and mpi_surface_data_io::mpi_write_surface_geometry().