CALYPSO: calypso_sr_rev_n Module Reference
calypso_sr_rev_n Module Reference
Arbitrary components data communication
using reverse import table.
Functions/Subroutines
subroutine calypso_send_recv_rev_n (NB, nnod_org, nnod_new, npe_send, isend_self, id_pe_send, istack_send, inod_export, npe_recv, irecv_self, id_pe_recv, istack_recv, irev_import, X_org, X_new)
subroutine calypso_send_recv_rev_3xn (NB, nnod_org, nnod_new, npe_send, isend_self, id_pe_send, istack_send, inod_export, npe_recv, irecv_self, id_pe_recv, istack_recv, irev_import, X1_org, X2_org, X3_org, X1_new, X2_new, X3_new)
Detailed Description
Arbitrary components data communication
using reverse import table.
      subroutine calypso_send_recv_rev_N(NB, nnod_org, nnod_new,      &
     &                           npe_send, isend_self,                &
     &                           id_pe_send, istack_send, inod_export,&
     &                           npe_recv, irecv_self,                &
     &                           id_pe_recv, istack_recv, irev_import,&
     &                           X_org, X_new)
      subroutine calypso_send_recv_rev_3xN(NB, nnod_org, nnod_new,    &
     &                           npe_send, isend_self,                &
     &                           id_pe_send, istack_send, inod_export,&
     &                           npe_recv, irecv_self,                &
     &                           id_pe_recv, istack_recv, irev_import,&
     &                           X1_org, X2_org, X3_org,              &
     &                           X1_new, X2_new, X3_new)
Parameters
NB Number of components for communication
nnod_org Number of data points for origin
nnod_new Number of components for destination
npe_send Number of processses to send
isend_self Integer flag to copy within own process
id_pe_send(npe_send) Process ID to send
istack_send(0:npe_send) End points of send buffer for each process
inod_export(istack_send(npe_send)) local node ID to copy in send buffer
npe_recv Number of processses to receive
irecv_self Integer flag to copy within own process
id_pe_recv(npe_send) Process ID to receive
istack_recv(0:npe_send) End points of receive buffer for each process
irev_import(nnod_new) import buffer ID for each data point
X_org(NB*nnod_org) Send data
X_new(NB*nnod_new) Received data
Function/Subroutine Documentation
calypso_send_recv_rev_3xn()
subroutine calypso_sr_rev_n::calypso_send_recv_rev_3xn (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) npe_send, integer(kind = kint), intent(in) isend_self, integer(kind = kint), dimension(npe_send), intent(in) id_pe_send, integer(kind = kint), dimension(0:npe_send), intent(in) istack_send, integer(kind = kint), dimension(istack_send(npe_send)), intent(in) inod_export, integer(kind = kint), intent(in) npe_recv, integer(kind = kint), intent(in) irecv_self, integer(kind = kint), dimension(npe_recv), intent(in) id_pe_recv, integer(kind = kint), dimension(0:npe_recv), intent(in) istack_recv, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, real (kind=kreal), dimension(nb*nnod_org), intent(in) X1_org, real (kind=kreal), dimension(nb*nnod_org), intent(in) X2_org, real (kind=kreal), dimension(nb*nnod_org), intent(in) X3_org, real (kind=kreal), dimension(nb*nnod_new), intent(inout) X1_new, real (kind=kreal), dimension(nb*nnod_new), intent(inout) X2_new, real (kind=kreal), dimension(nb*nnod_new), intent(inout) X3_new)
Definition at line 120 of file calypso_SR_rev_N.f90.
References calypso_sr_core::calypso_send_recv_core(), set_from_recv_buf_rev_tri::set_from_recv_buf_rev_3xn(), set_to_send_buf_tri::set_to_send_buf_3xn(), m_solver_sr::wr, and m_solver_sr::ws.
Referenced by select_calypso_sr::sel_calypso_send_recv_3xn().
calypso_send_recv_rev_n()
subroutine calypso_sr_rev_n::calypso_send_recv_rev_n (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) npe_send, integer(kind = kint), intent(in) isend_self, integer(kind = kint), dimension(npe_send), intent(in) id_pe_send, integer(kind = kint), dimension(0:npe_send), intent(in) istack_send, integer(kind = kint), dimension(istack_send(npe_send)), intent(in) inod_export, integer(kind = kint), intent(in) npe_recv, integer(kind = kint), intent(in) irecv_self, integer(kind = kint), dimension(npe_recv), intent(in) id_pe_recv, integer(kind = kint), dimension(0:npe_recv), intent(in) istack_recv, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, real (kind=kreal), dimension(nb*nnod_org), intent(in) X_org, real (kind=kreal), dimension(nb*nnod_new), intent(inout) X_new)
Definition at line 62 of file calypso_SR_rev_N.f90.
References calypso_sr_core::calypso_send_recv_core(), m_work_time::end_elapsed_time(), m_elapsed_labels_send_recv::iflag_csr_time, m_elapsed_labels_send_recv::ist_elapsed_csr, set_from_recv_buf_rev::set_from_recv_buf_rev_n(), set_to_send_buffer::set_to_send_buf_n(), m_work_time::start_elapsed_time(), m_solver_sr::wr, and m_solver_sr::ws.
Referenced by select_calypso_sr::sel_calypso_send_recv_n().