CALYPSO: set_sph_tranform_ordering Module Reference
set_sph_tranform_ordering Module Reference
Set order of spheherical harmonics modes.
Functions/Subroutines
subroutine set_wavenumber_4_ispack_fft (nth, nph, m_folding, mspec_4_ispack, mdx_ispack)
subroutine set_zonal_wavenum_4_legendre (ndomain_m, ltr, m_folding, nth, nph, jdx_fsph, mdx_4_lgd)
subroutine set_merged_index_4_sph_trans (ndomain_m, ltr, jmax, nph, m_folding, istack_m, mdx_4_lgd, nidx_ml, istack_ml, jdx_lag)
subroutine set_merged_index_4_sph_rj (ndomain_r, ndomain_m, ndomain_rj, jmax, istack_ml, jdx_lag, nidx_j, istack_j, jdx_rj)
subroutine set_trans_table_fft_2_lgd (ltr, nth, nph, m_folding, mspec_4_ispack, jdx_fsph, mtbl_fft_2_lgd)
Detailed Description
Set order of spheherical harmonics modes.
      subroutine set_wavenumber_4_ispack_fft(nth, nph, m_folding,     &
     &          mspec_4_ispack, mdx_ispack)
        output: mspec_4_ispack, mdx_ispack
      subroutine set_zonal_wavenum_4_legendre(ndomain_m,              &
     &          ltr, m_folding, nth, nph, jdx_fsph, mdx_4_lgd)
        output: jdx_fsph, mdx_4_lgd
      subroutine set_merged_index_4_sph_trans(ndomain_m, ltr, jmax,   &
     &          nph, m_folding, istack_m, mdx_4_lgd, nidx_ml,         &
     &          istack_ml, jdx_lag)
        output: nidx_ml, istack_ml, jdx_lag
      subroutine set_merged_index_4_sph_rj(ndomain_r, ndomain_m,      &
     &          ndomain_rj, jmax, istack_ml, jdx_lag,                 &
     &          nidx_j, istack_j, jdx_rj)
        output:  nidx_j, istack_j, jdx_rj
      subroutine set_trans_table_fft_2_lgd(ltr, nth, nph, m_folding,  &
     &          mspec_4_ispack, jdx_fsph, mtbl_fft_2_lgd)
        output: mtbl_fft_2_lgd
Function/Subroutine Documentation
set_merged_index_4_sph_rj()
subroutine set_sph_tranform_ordering::set_merged_index_4_sph_rj (integer(kind = kint), intent(in) ndomain_r, integer(kind = kint), intent(in) ndomain_m, integer(kind = kint), intent(in) ndomain_rj, integer(kind = kint), intent(in) jmax, integer(kind = kint), dimension(0:ndomain_m), intent(inout) istack_ml, integer(kind = kint), dimension(0:jmax,3), intent(in) jdx_lag, integer(kind = kint), dimension(ndomain_rj), intent(inout) nidx_j, integer(kind = kint), dimension(0:ndomain_rj), intent(inout) istack_j, integer(kind = kint), dimension(0:jmax,3), intent(inout) jdx_rj)
Definition at line 210 of file set_sph_tranform_ordering.f90.
References set_indices_4_sph_tranform::cal_local_nums().
Referenced by const_each_global_sph_list::const_global_rj_modes_by_rlm().
set_merged_index_4_sph_trans()
subroutine set_sph_tranform_ordering::set_merged_index_4_sph_trans (integer(kind = kint), intent(in) ndomain_m, integer(kind = kint), intent(in) ltr, integer(kind = kint), intent(in) jmax, integer(kind = kint), intent(in) nph, integer(kind = kint), intent(in) m_folding, integer(kind = kint), dimension(0:ndomain_m), intent(in) istack_m, integer(kind = kint), dimension(0:nph), intent(in) mdx_4_lgd, integer(kind = kint), dimension(ndomain_m), intent(inout) nidx_ml, integer(kind = kint), dimension(0:ndomain_m), intent(inout) istack_ml, integer(kind = kint), dimension(0:jmax,3), intent(inout) jdx_lag)
Definition at line 163 of file set_sph_tranform_ordering.f90.
Referenced by const_each_global_sph_list::const_global_rlm_modes().
set_trans_table_fft_2_lgd()
subroutine set_sph_tranform_ordering::set_trans_table_fft_2_lgd (integer(kind = kint), intent(in) ltr, integer(kind = kint), intent(in) nth, integer(kind = kint), intent(in) nph, integer(kind = kint), intent(in) m_folding, integer(kind = kint), dimension(-nth:nth), intent(in) mspec_4_ispack, integer(kind = kint), dimension(-nth:nth), intent(in) jdx_fsph, integer(kind = kint), dimension(0:nph), intent(inout) mtbl_fft_2_lgd)
Definition at line 276 of file set_sph_tranform_ordering.f90.
Referenced by const_global_sph_grids_modes::const_global_sph_fem_grid(), and const_global_sph_grids_modes::s_const_global_sph_grids_modes().
set_wavenumber_4_ispack_fft()
subroutine set_sph_tranform_ordering::set_wavenumber_4_ispack_fft (integer(kind = kint), intent(in) nth, integer(kind = kint), intent(in) nph, integer(kind = kint), intent(in) m_folding, integer(kind = kint), dimension(-nth:nth), intent(inout) mspec_4_ispack, integer(kind = kint), dimension(nph), intent(inout) mdx_ispack)
Definition at line 43 of file set_sph_tranform_ordering.f90.
Referenced by const_each_global_sph_list::const_global_rlm_modes().
set_zonal_wavenum_4_legendre()
subroutine set_sph_tranform_ordering::set_zonal_wavenum_4_legendre (integer(kind = kint), intent(in) ndomain_m, integer(kind = kint), intent(in) ltr, integer(kind = kint), intent(in) m_folding, integer(kind = kint), intent(in) nth, integer(kind = kint), intent(in) nph, integer(kind = kint), dimension(-nth:nth), intent(inout) jdx_fsph, integer(kind = kint), dimension(0:nph), intent(inout) mdx_4_lgd)
Definition at line 69 of file set_sph_tranform_ordering.f90.