CALYPSO: adjust_reference_fields Module Reference
adjust_reference_fields Module Reference
Set boundary conditions for MHD dynamo simulation.
Functions/Subroutines
subroutine adjust_press_by_average_on_cmb (kr_in, kr_out, sph_rj, ipol, rj_fld)
subroutine sync_temp_by_per_temp_sph (SPH_model, sph_rj, ipol, rj_fld)
subroutine trans_per_temp_to_temp_sph (SPH_model, sph_rj, ipol, rj_fld)
subroutine, private sync_scalar_by_pert_sph (sph_rj, reference, ref_param, is_temp, is_grad_t, ids_grad_t, is_par_temp, is_grad_part_t, ids_grad_part_t, rj_fld)
subroutine trans_pert_to_scalar_sph (sph_rj, reference, ref_param, is_temp, is_grad_t, ids_grad_t, is_par_temp, is_grad_part_t, ids_grad_part_t, rj_fld)
subroutine delete_sphere_average (is_scalar, sph_rj, rj_fld)
Detailed Description
Set boundary conditions for MHD dynamo simulation.
      subroutine adjust_press_by_average_on_CMB                       &
     &         (kr_in, kr_out, sph_rj, ipol, rj_fld)
      subroutine sync_temp_by_per_temp_sph(ref_temp, ref_comp,        &
     &          MHD_prop, sph_rj, ipol, rj_fld)
        d_rj(inod,ipol%base%i_temp):        T => \Theta = T - T0
        d_rj(inod,ipol%base%i_per_temp):    \Theta = T - T0
        d_rj(inod,ipol%grad_fld%i_grad_temp):      T => d \Theta / dr
        d_rj(inod,ipol%grad_fld%i_grad_per_t): d \Theta / dr
      subroutine trans_per_temp_to_temp_sph                           &
     &         (SPH_model, sph_rj, ipol, rj_fld)
        d_rj(inod,ipol%base%i_temp):        \Theta = T - T0 => T
        d_rj(inod,ipol%base%i_per_temp):    \Theta = T - T0
        d_rj(inod,ipol%grad_fld%i_grad_temp): d \Theta / dr => dT / dr
        d_rj(inod,ipol%grad_fld%i_grad_per_t): d \Theta / dr
        type(SPH_MHD_model_data), intent(in) :: SPH_model
        type(sph_shell_parameters), intent(in) :: sph_params
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(phys_address), intent(in) :: ipol
      subroutine delete_sphere_average(is_scalar, sph_rj, rj_fld)
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(phys_data), intent(in) :: rj_fld
Function/Subroutine Documentation
adjust_press_by_average_on_cmb()
subroutine adjust_reference_fields::adjust_press_by_average_on_cmb (integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) kr_out, type(sph_rj_grid), intent(in) sph_rj, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld)
Definition at line 57 of file adjust_reference_fields.f90.
References set_reference_sph_mhd::adjust_by_ave_pressure_on_cmb().
delete_sphere_average()
subroutine adjust_reference_fields::delete_sphere_average (integer(kind = kint), intent(in) is_scalar, type(sph_rj_grid), intent(in) sph_rj, type(phys_data), intent(inout) rj_fld)
Definition at line 208 of file adjust_reference_fields.f90.
References set_reference_sph_mhd::delete_zero_degree_comp().
Referenced by cal_self_buoyancies_sph::sel_buoyancies_sph_mhd().
sync_scalar_by_pert_sph()
subroutine, private adjust_reference_fields::sync_scalar_by_pert_sph (type(sph_rj_grid), intent(in) sph_rj, type(reference_field), intent(in) reference, type(reference_scalar_param), intent(in) ref_param, integer(kind = kint), intent(in) is_temp, integer(kind = kint), intent(in) is_grad_t, integer(kind = kint), intent(in) ids_grad_t, integer(kind = kint), intent(in) is_par_temp, integer(kind = kint), intent(in) is_grad_part_t, integer(kind = kint), intent(in) ids_grad_part_t, type(phys_data), intent(inout) rj_fld) private
Definition at line 146 of file adjust_reference_fields.f90.
References set_reference_sph_mhd::chenge_temp_to_per_temp_sph(), t_reference_scalar_param::id_sphere_ref_temp, and t_reference_scalar_param::id_takepiro_temp.
Referenced by sync_temp_by_per_temp_sph().
sync_temp_by_per_temp_sph()
subroutine adjust_reference_fields::sync_temp_by_per_temp_sph (type(sph_mhd_model_data), intent(in) SPH_model, type(sph_rj_grid), intent(in) sph_rj, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld)
Definition at line 77 of file adjust_reference_fields.f90.
References sync_scalar_by_pert_sph().
Referenced by sph_analyzer_d_bench::sph_analyze_dbench(), sph_analyzer_mhd::sph_analyze_mhd(), sph_analyzer_snap_w_psf::sph_analyze_snap_psf(), and sph_analyzer_mhd::sph_initialize_mhd().
trans_per_temp_to_temp_sph()
subroutine adjust_reference_fields::trans_per_temp_to_temp_sph (type(sph_mhd_model_data), intent(in) SPH_model, type(sph_rj_grid), intent(in) sph_rj, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld)
Definition at line 110 of file adjust_reference_fields.f90.
References trans_pert_to_scalar_sph().
Referenced by sph_analyzer_d_bench::sph_analyze_dbench(), sph_analyzer_mhd::sph_analyze_mhd(), and sph_analyzer_snap_w_psf::sph_analyze_snap_psf().
trans_pert_to_scalar_sph()
subroutine adjust_reference_fields::trans_pert_to_scalar_sph (type(sph_rj_grid), intent(in) sph_rj, type(reference_field), intent(in) reference, type(reference_scalar_param), intent(in) ref_param, integer(kind = kint), intent(in) is_temp, integer(kind = kint), intent(in) is_grad_t, integer(kind = kint), intent(in) ids_grad_t, integer(kind = kint), intent(in) is_par_temp, integer(kind = kint), intent(in) is_grad_part_t, integer(kind = kint), intent(in) ids_grad_part_t, type(phys_data), intent(inout) rj_fld)
Definition at line 178 of file adjust_reference_fields.f90.
References t_reference_scalar_param::id_sphere_ref_temp, t_reference_scalar_param::id_takepiro_temp, and set_reference_sph_mhd::transfer_per_temp_to_temp_sph().
Referenced by trans_per_temp_to_temp_sph().