CALYPSO: node_geometry_io_b Module Reference
node_geometry_io_b Module Reference
Routines for Binary mesh data IO.
Functions/Subroutines
subroutine write_geometry_info_b (nod_IO, bbuf)
subroutine write_scalar_in_element_b (nod_IO, sfed_IO, bbuf)
subroutine write_vector_in_element_b (nod_IO, sfed_IO, bbuf)
subroutine read_number_of_node_b (bbuf, nod_IO)
subroutine read_geometry_info_b (bbuf, nod_IO)
subroutine read_scalar_in_element_b (bbuf, nod_IO, sfed_IO)
subroutine read_vector_in_element_b (bbuf, nod_IO, sfed_IO)
Detailed Description
Routines for Binary mesh data IO.
      subroutine write_geometry_info_b(nod_IO, bbuf)
      subroutine write_scalar_in_element_b(nod_IO, sfed_IO, bbuf)
      subroutine write_vector_in_element_b(nod_IO, sfed_IO, bbuf)
        type(node_data), intent(in) :: nod_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
        type(binary_IO_buffer), intent(inout) :: bbuf
      subroutine read_number_of_node_b(bbuf, nod_IO)
      subroutine read_geometry_info_b(bbuf, nod_IO)
        type(binary_IO_buffer), intent(inout) :: bbuf
        type(node_data), intent(inout) :: nod_IO
      subroutine read_scalar_in_element_b(bbuf, nod_IO, sfed_IO)
      subroutine read_vector_in_element_b(bbuf, nod_IO, sfed_IO)
        type(binary_IO_buffer), intent(inout) :: bbuf
        type(node_data), intent(inout) :: nod_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
Function/Subroutine Documentation
read_geometry_info_b()
subroutine node_geometry_io_b::read_geometry_info_b (type(binary_io_buffer), intent(inout) bbuf, type(node_data), intent(inout) nod_IO)
Definition at line 138 of file node_geometry_IO_b.f90.
References t_geometry_data::alloc_node_geometry_base(), m_phys_constants::n_vector, binary_io::read_2d_vector_b(), and binary_io::read_mul_int8_b().
Referenced by edge_data_io_b::read_edge_geometry_b(), element_data_io_b::read_element_geometry_b(), mesh_data_io_b::read_filter_geometry_b(), mesh_data_io_b::read_num_node_ele_b(), and surface_data_io_b::read_surface_geometry_b().
read_number_of_node_b()
subroutine node_geometry_io_b::read_number_of_node_b (type(binary_io_buffer), intent(inout) bbuf, type(node_data), intent(inout) nod_IO)
Definition at line 121 of file node_geometry_IO_b.f90.
References binary_io::read_one_integer_b().
Referenced by edge_data_io_b::read_edge_geometry_b(), element_data_io_b::read_element_geometry_b(), mesh_data_io_b::read_filter_geometry_b(), mesh_data_io_b::read_num_node_b(), and surface_data_io_b::read_surface_geometry_b().
read_scalar_in_element_b()
subroutine node_geometry_io_b::read_scalar_in_element_b (type(binary_io_buffer), intent(inout) bbuf, type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 160 of file node_geometry_IO_b.f90.
References t_surf_edge_io::alloc_ele_scalar_io(), transfer_to_long_integers::cast_long(), binary_io::read_1d_vector_b(), and binary_io::read_one_integer_b().
Referenced by edge_data_io_b::read_edge_geometry_b(), element_data_io_b::read_element_geometry_b(), and surface_data_io_b::read_surface_geometry_b().
read_vector_in_element_b()
subroutine node_geometry_io_b::read_vector_in_element_b (type(binary_io_buffer), intent(inout) bbuf, type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 186 of file node_geometry_IO_b.f90.
References t_surf_edge_io::alloc_ele_vector_io(), transfer_to_long_integers::cast_long(), m_phys_constants::n_vector, binary_io::read_2d_vector_b(), and binary_io::read_one_integer_b().
Referenced by edge_data_io_b::read_edge_geometry_b(), and surface_data_io_b::read_surface_geometry_b().
write_geometry_info_b()
subroutine node_geometry_io_b::write_geometry_info_b (type(node_data), intent(in) nod_IO, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 49 of file node_geometry_IO_b.f90.
References m_phys_constants::n_vector, binary_io::write_2d_vector_b(), binary_io::write_mul_int8_b(), and binary_io::write_one_integer_b().
Referenced by edge_data_io_b::write_edge_geometry_b(), element_data_io_b::write_element_geometry_b(), mesh_data_io_b::write_filter_geometry_b(), mesh_data_io_b::write_geometry_data_b(), and surface_data_io_b::write_surface_geometry_b().
write_scalar_in_element_b()
subroutine node_geometry_io_b::write_scalar_in_element_b (type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 74 of file node_geometry_IO_b.f90.
References transfer_to_long_integers::cast_long(), binary_io::write_1d_vector_b(), and binary_io::write_one_integer_b().
Referenced by edge_data_io_b::write_edge_geometry_b(), element_data_io_b::write_element_geometry_b(), and surface_data_io_b::write_surface_geometry_b().
write_vector_in_element_b()
subroutine node_geometry_io_b::write_vector_in_element_b (type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 97 of file node_geometry_IO_b.f90.
References transfer_to_long_integers::cast_long(), m_phys_constants::n_vector, binary_io::write_2d_vector_b(), and binary_io::write_one_integer_b().
Referenced by edge_data_io_b::write_edge_geometry_b(), and surface_data_io_b::write_surface_geometry_b().