CALYPSO: set_components_flags Module Reference
set_components_flags Module Reference
Set component labels.
Functions/Subroutines
subroutine s_set_components_flags (comp_name, phys_name, icomp, ncomp, ncomp_org, rst_name)
Variables
integer(kind=kint), parameter ncomp_scalar = 1
integer(kind=kint), parameter ncomp_vector = 3
integer(kind=kint), parameter ncomp_sym_tensor = 6
integer(kind=kint), parameter ncomp_asym_tensor = 3
integer(kind=kint), parameter icomp_scalar = 1
integer(kind=kint), parameter icomp_vector = 101
integer(kind=kint), parameter icomp_sym_tensor = 201
integer(kind=kint), parameter icomp_asym_tensor = 301
integer(kind=kint), parameter icomp_sph_vector = 102
integer(kind=kint), parameter icomp_cyl_vector = 103
integer(kind=kint), parameter icomp_sphl_sym_tensor = 202
integer(kind=kint), parameter icomp_cyl_sym_tensor = 203
integer(kind=kint), parameter icomp_norm = 0
integer(kind=kint), parameter icomp_norm_sym_tensor = 200
integer(kind=kint), parameter icomp_norm_asym_tensor = 300
integer(kind=kint), parameter icomp_x = 1
integer(kind=kint), parameter icomp_y = 2
integer(kind=kint), parameter icomp_z = 3
integer(kind=kint), parameter icomp_radial = 11
integer(kind=kint), parameter icomp_theta = 12
integer(kind=kint), parameter icomp_phi = 13
integer(kind=kint), parameter icomp_cylinder_r = 14
integer(kind=kint), parameter icomp_xx = 1
integer(kind=kint), parameter icomp_xy = 2
integer(kind=kint), parameter icomp_xz = 3
integer(kind=kint), parameter icomp_yy = 4
integer(kind=kint), parameter icomp_yz = 5
integer(kind=kint), parameter icomp_zz = 6
integer(kind=kint), parameter icomp_rr = 221
integer(kind=kint), parameter icomp_rt = 222
integer(kind=kint), parameter icomp_rp = 223
integer(kind=kint), parameter icomp_tt = 224
integer(kind=kint), parameter icomp_tp = 225
integer(kind=kint), parameter icomp_pp = 226
integer(kind=kint), parameter icomp_ss = 231
integer(kind=kint), parameter icomp_sp = 232
integer(kind=kint), parameter icomp_sz = 233
integer(kind=kint), parameter icomp_pp_cyl = 234
integer(kind=kint), parameter icomp_pz = 235
integer(kind=kint), parameter icomp_zz_cyl = 236
Detailed Description
Set component labels.
      subroutine s_set_components_flags(comp_name, phys_name,         &
     &          icomp, ncomp, ncomp_org, rst_name)
Function/Subroutine Documentation
s_set_components_flags()
subroutine set_components_flags::s_set_components_flags (character(len=kchara), intent(in) comp_name, character(len=kchara), intent(in) phys_name, integer(kind = kint), intent(inout) icomp, integer(kind = kint), intent(inout) ncomp, integer(kind = kint), intent(inout) ncomp_org, character(len=kchara), intent(inout) rst_name)
Definition at line 75 of file set_components_flags.f90.
References m_component_flags::asym_tensor, m_more_component_flags::asym_tensor_magnitude_flags, t_multi_flag_labels::check_mul_flags(), t_field_labels::cmp_field_no_case(), m_component_flags::cylindrical_sym_tensor, m_component_flags::cylindrical_vector, m_more_component_flags::cyrindrical_r_flags, m_more_component_flags::dealloc_more_componnet_flags(), icomp_asym_tensor, icomp_cyl_sym_tensor, icomp_cyl_vector, icomp_cylinder_r, icomp_norm, icomp_norm_asym_tensor, icomp_norm_sym_tensor, icomp_phi, icomp_pp, icomp_pp_cyl, icomp_pz, icomp_radial, icomp_rp, icomp_rr, icomp_rt, icomp_scalar, icomp_sp, icomp_sph_vector, icomp_sphl_sym_tensor, icomp_ss, icomp_sym_tensor, icomp_sz, icomp_theta, icomp_tp, icomp_tt, icomp_vector, icomp_x, icomp_xx, icomp_xy, icomp_xz, icomp_y, icomp_yy, icomp_yz, icomp_z, icomp_zz, icomp_zz_cyl, m_more_component_flags::init_more_componnet_flags(), m_more_component_flags::magnitude_flags, ncomp_asym_tensor, ncomp_scalar, ncomp_sym_tensor, ncomp_vector, m_more_component_flags::phi_flags, m_more_component_flags::radial_flags, m_component_flags::scalar, m_component_flags::spherical_sym_tensor, m_component_flags::spherical_vector, m_component_flags::sym_tensor, m_more_component_flags::sym_tensor_magnitude_flags, m_component_flags::t_pp, m_component_flags::t_pz, m_component_flags::t_rp, m_component_flags::t_rr, m_component_flags::t_rt, m_component_flags::t_sp, m_component_flags::t_ss, m_component_flags::t_sz, m_component_flags::t_tp, m_component_flags::t_tt, m_component_flags::t_xx, m_component_flags::t_xy, m_component_flags::t_xz, m_component_flags::t_yy, m_component_flags::t_yz, m_component_flags::t_zz, m_more_component_flags::theta_flags, m_component_flags::v_x, m_component_flags::v_y, m_component_flags::v_z, and m_component_flags::vector.
Referenced by set_field_comp_for_viz::set_components_4_viz(), and set_field_comp_for_viz::set_one_component_4_viz().
Variable Documentation
icomp_asym_tensor
integer(kind = kint), parameter set_components_flags::icomp_asym_tensor = 301
Definition at line 30 of file set_components_flags.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and s_set_components_flags().
icomp_cyl_sym_tensor
integer(kind = kint), parameter set_components_flags::icomp_cyl_sym_tensor = 203
Definition at line 35 of file set_components_flags.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and s_set_components_flags().
icomp_cyl_vector
integer(kind = kint), parameter set_components_flags::icomp_cyl_vector = 103
Definition at line 33 of file set_components_flags.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and s_set_components_flags().
icomp_cylinder_r
integer(kind = kint), parameter set_components_flags::icomp_cylinder_r = 14
Definition at line 47 of file set_components_flags.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and s_set_components_flags().
icomp_norm
integer(kind = kint), parameter set_components_flags::icomp_norm = 0
Definition at line 37 of file set_components_flags.f90.
Referenced by s_set_components_flags().
icomp_norm_asym_tensor
integer(kind = kint), parameter set_components_flags::icomp_norm_asym_tensor = 300
Definition at line 39 of file set_components_flags.f90.
Referenced by s_set_components_flags().
icomp_norm_sym_tensor
integer(kind = kint), parameter set_components_flags::icomp_norm_sym_tensor = 200
Definition at line 38 of file set_components_flags.f90.
Referenced by s_set_components_flags().
icomp_phi
integer(kind = kint), parameter set_components_flags::icomp_phi = 13
Definition at line 46 of file set_components_flags.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and s_set_components_flags().
icomp_pp
integer(kind = kint), parameter set_components_flags::icomp_pp = 226
Definition at line 60 of file set_components_flags.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and s_set_components_flags().
icomp_pp_cyl
integer(kind = kint), parameter set_components_flags::icomp_pp_cyl = 234
Definition at line 65 of file set_components_flags.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and s_set_components_flags().
icomp_pz
integer(kind = kint), parameter set_components_flags::icomp_pz = 235
Definition at line 66 of file set_components_flags.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and s_set_components_flags().
icomp_radial
integer(kind = kint), parameter set_components_flags::icomp_radial = 11
Definition at line 44 of file set_components_flags.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and s_set_components_flags().
icomp_rp
integer(kind = kint), parameter set_components_flags::icomp_rp = 223
Definition at line 57 of file set_components_flags.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and s_set_components_flags().
icomp_rr
integer(kind = kint), parameter set_components_flags::icomp_rr = 221
Definition at line 55 of file set_components_flags.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and s_set_components_flags().
icomp_rt
integer(kind = kint), parameter set_components_flags::icomp_rt = 222
Definition at line 56 of file set_components_flags.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and s_set_components_flags().
icomp_scalar
integer(kind = kint), parameter set_components_flags::icomp_scalar = 1
Definition at line 27 of file set_components_flags.f90.
Referenced by s_set_components_flags().
icomp_sp
integer(kind = kint), parameter set_components_flags::icomp_sp = 232
Definition at line 63 of file set_components_flags.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and s_set_components_flags().
icomp_sph_vector
integer(kind = kint), parameter set_components_flags::icomp_sph_vector = 102
Definition at line 32 of file set_components_flags.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and s_set_components_flags().
icomp_sphl_sym_tensor
integer(kind = kint), parameter set_components_flags::icomp_sphl_sym_tensor = 202
Definition at line 34 of file set_components_flags.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and s_set_components_flags().
icomp_ss
integer(kind = kint), parameter set_components_flags::icomp_ss = 231
Definition at line 62 of file set_components_flags.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and s_set_components_flags().
icomp_sym_tensor
integer(kind = kint), parameter set_components_flags::icomp_sym_tensor = 201
Definition at line 29 of file set_components_flags.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and s_set_components_flags().
icomp_sz
integer(kind = kint), parameter set_components_flags::icomp_sz = 233
Definition at line 64 of file set_components_flags.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and s_set_components_flags().
icomp_theta
integer(kind = kint), parameter set_components_flags::icomp_theta = 12
Definition at line 45 of file set_components_flags.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and s_set_components_flags().
icomp_tp
integer(kind = kint), parameter set_components_flags::icomp_tp = 225
Definition at line 59 of file set_components_flags.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and s_set_components_flags().
icomp_tt
integer(kind = kint), parameter set_components_flags::icomp_tt = 224
Definition at line 58 of file set_components_flags.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and s_set_components_flags().
icomp_vector
integer(kind = kint), parameter set_components_flags::icomp_vector = 101
Definition at line 28 of file set_components_flags.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and s_set_components_flags().
icomp_x
integer(kind = kint), parameter set_components_flags::icomp_x = 1
Definition at line 41 of file set_components_flags.f90.
Referenced by s_set_components_flags().
icomp_xx
integer(kind = kint), parameter set_components_flags::icomp_xx = 1
Definition at line 49 of file set_components_flags.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and s_set_components_flags().
icomp_xy
integer(kind = kint), parameter set_components_flags::icomp_xy = 2
Definition at line 50 of file set_components_flags.f90.
Referenced by s_set_components_flags().
icomp_xz
integer(kind = kint), parameter set_components_flags::icomp_xz = 3
Definition at line 51 of file set_components_flags.f90.
Referenced by s_set_components_flags().
icomp_y
integer(kind = kint), parameter set_components_flags::icomp_y = 2
Definition at line 42 of file set_components_flags.f90.
Referenced by s_set_components_flags().
icomp_yy
integer(kind = kint), parameter set_components_flags::icomp_yy = 4
Definition at line 52 of file set_components_flags.f90.
Referenced by s_set_components_flags().
icomp_yz
integer(kind = kint), parameter set_components_flags::icomp_yz = 5
Definition at line 53 of file set_components_flags.f90.
Referenced by s_set_components_flags().
icomp_z
integer(kind = kint), parameter set_components_flags::icomp_z = 3
Definition at line 43 of file set_components_flags.f90.
Referenced by s_set_components_flags().
icomp_zz
integer(kind = kint), parameter set_components_flags::icomp_zz = 6
Definition at line 54 of file set_components_flags.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and s_set_components_flags().
icomp_zz_cyl
integer(kind = kint), parameter set_components_flags::icomp_zz_cyl = 236
Definition at line 67 of file set_components_flags.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and s_set_components_flags().
ncomp_asym_tensor
integer(kind = kint), parameter set_components_flags::ncomp_asym_tensor = 3
Definition at line 24 of file set_components_flags.f90.
Referenced by s_set_components_flags().
ncomp_scalar
integer(kind = kint), parameter set_components_flags::ncomp_scalar = 1
Definition at line 21 of file set_components_flags.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and s_set_components_flags().
ncomp_sym_tensor
integer(kind = kint), parameter set_components_flags::ncomp_sym_tensor = 6
Definition at line 23 of file set_components_flags.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and s_set_components_flags().
ncomp_vector
integer(kind = kint), parameter set_components_flags::ncomp_vector = 3
Definition at line 22 of file set_components_flags.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and s_set_components_flags().