CALYPSO: t_ucd_data Module Reference
t_ucd_data Module Reference
Structure for Field data IO.
Data Types
type ucd_data
Structure for FEM field data IO.
Functions/Subroutines
subroutine allocate_ucd_nodal_data (ucd)
subroutine allocate_ucd_node (ucd)
subroutine allocate_ucd_ele (ucd)
subroutine allocate_ucd_phys_name (ucd)
subroutine allocate_ucd_phys_data (ucd)
subroutine alloc_merged_ucd_nod_stack (num_pe, ucd)
subroutine alloc_merged_ucd_ele_stack (num_pe, ucd)
subroutine deallocate_ucd_node (ucd)
subroutine deallocate_ucd_ele (ucd)
subroutine deallocate_ucd_phys_data (ucd)
subroutine deallocate_ucd_phys_name (ucd)
subroutine deallocate_ucd_data (ucd)
subroutine deallocate_ucd_mesh (ucd)
subroutine deallocate_parallel_ucd_mesh (ucd)
subroutine disconnect_ucd_node (ucd)
subroutine disconnect_ucd_data (ucd)
subroutine disconnect_ucd_mesh (ucd)
subroutine disconnect_merged_ucd_mesh (ucd)
subroutine unlink_merged_ucd_nod_stack (ucd)
subroutine unlink_merged_ucd_ele_stack (ucd)
subroutine dealloc_merged_ucd_nod_stack (ucd)
subroutine dealloc_merged_ucd_ele_stack (ucd)
subroutine cal_istack_ucd_component (ucd)
subroutine append_new_ucd_field_name (new_field_name, ncomp_new_field, tmp, ucd)
subroutine append_new_ucd_field_data (ncomp_new_field, d_tmp, tmp, ucd)
subroutine check_read_ucd_data (ucd_b)
subroutine compare_read_ucd_data (ucd_b, ucd_z)
Detailed Description
Structure for Field data IO.
      subroutine allocate_ucd_nodal_data(ucd)
      subroutine allocate_ucd_node(ucd)
      subroutine allocate_ucd_ele(ucd)
      subroutine allocate_ucd_phys_name(ucd)
      subroutine allocate_ucd_phys_data(ucd)
      subroutine alloc_merged_ucd_nod_stack(num_pe, ucd)
      subroutine alloc_merged_ucd_ele_stack(num_pe, ucd)
      subroutine deallocate_ucd_node(ucd)
      subroutine deallocate_ucd_ele(ucd)
      subroutine deallocate_ucd_phys_data(ucd)
      subroutine deallocate_ucd_phys_name(ucd)
      subroutine deallocate_ucd_data(ucd)
      subroutine deallocate_ucd_mesh(ucd)
      subroutine deallocate_parallel_ucd_mesh(ucd)
      subroutine disconnect_ucd_node(ucd)
      subroutine disconnect_ucd_data(ucd)
      subroutine disconnect_ucd_mesh(ucd)
      subroutine disconnect_merged_ucd_mesh(ucd)
      subroutine unlink_merged_ucd_nod_stack(ucd)
      subroutine unlink_merged_ucd_ele_stack(ucd)
      subroutine dealloc_merged_ucd_nod_stack(ucd)
      subroutine dealloc_merged_ucd_ele_stack(ucd)
      subroutine cal_istack_ucd_component(ucd)
      subroutine append_new_ucd_field_name(new_field_name,            &
     &          ncomp_new_field, tmp, ucd)
      subroutine append_new_ucd_field_data(ncomp_new_field, d_tmp,    &
     &          tmp, ucd)
        type(ucd_data), intent(inout) :: ucd
      subroutine check_read_ucd_data(ucd_b)
      subroutine compare_read_ucd_data(ucd_b, ucd_z)
        type(ucd_data), intent(in) :: ucd_b, ucd_z
Function/Subroutine Documentation
alloc_merged_ucd_ele_stack()
subroutine t_ucd_data::alloc_merged_ucd_ele_stack (integer, intent(in) num_pe, type(ucd_data), intent(inout) ucd)
Definition at line 194 of file t_ucd_data.f90.
Referenced by merged_udt_vtk_file_io::init_merged_ucd().
alloc_merged_ucd_nod_stack()
subroutine t_ucd_data::alloc_merged_ucd_nod_stack (integer, intent(in) num_pe, type(ucd_data), intent(inout) ucd)
Definition at line 179 of file t_ucd_data.f90.
allocate_ucd_ele()
subroutine t_ucd_data::allocate_ucd_ele (type(ucd_data), intent(inout) ucd)
Definition at line 134 of file t_ucd_data.f90.
Referenced by set_and_cal_udt_data::const_udt_global_connect(), set_and_cal_udt_data::const_udt_local_connect(), gz_read_udt_from_bin_data::gz_read_alloc_psf_bin_grid_data(), merged_udt_vtk_file_io::init_merged_ucd(), set_ucd_data::link_ele_data_2_output(), gz_udt_to_vtk_data_io::read_alloc_gz_ucd_grd_from_vtk(), gz_udt_type_data_io::read_alloc_gz_ucd_mesh_data(), read_udt_from_bindary_data::read_alloc_psf_bin_grid_data(), udt_type_data_io::read_alloc_ucd_mesh_data(), and udt_to_vtk_data_io::read_alloc_ucd_mesh_from_vtk().
allocate_ucd_nodal_data()
subroutine t_ucd_data::allocate_ucd_nodal_data (type(ucd_data), intent(inout) ucd)
Definition at line 104 of file t_ucd_data.f90.
References allocate_ucd_node(), allocate_ucd_phys_data(), and allocate_ucd_phys_name().
allocate_ucd_node()
subroutine t_ucd_data::allocate_ucd_node (type(ucd_data), intent(inout) ucd)
Definition at line 117 of file t_ucd_data.f90.
Referenced by allocate_ucd_nodal_data(), set_and_cal_udt_data::const_udt_local_nodes(), gz_read_udt_from_bin_data::gz_read_alloc_psf_bin_grid_data(), gz_udt_to_vtk_data_io::read_alloc_gz_ucd_grd_from_vtk(), gz_udt_type_data_io::read_alloc_gz_ucd_mesh_data(), read_udt_from_bindary_data::read_alloc_psf_bin_grid_data(), udt_type_data_io::read_alloc_ucd_mesh_data(), and udt_to_vtk_data_io::read_alloc_ucd_mesh_from_vtk().
allocate_ucd_phys_data()
subroutine t_ucd_data::allocate_ucd_phys_data (type(ucd_data), intent(inout) ucd)
Definition at line 166 of file t_ucd_data.f90.
Referenced by allocate_ucd_nodal_data(), append_new_ucd_field_name(), gz_ucd_field_mpi_io_b::gz_rd_alloc_ucd_fld_file_mpi_b(), gz_read_udt_from_bin_data::gz_read_alloc_psf_bin_fld_data(), gz_ucd_field_file_io_b::gz_read_alloc_ucd_2_fld_file_b(), gz_ucd_field_file_io::gz_read_alloc_ucd_2_ld_file(), gz_ucd_field_mpi_io::gz_read_alloc_ucd_fld_file_mpi(), gz_udt_type_data_io::read_alloc_gz_udt_field(), gz_udt_to_vtk_data_io::read_alloc_gz_udt_fld_from_vtk(), read_udt_from_bindary_data::read_alloc_psf_bin_field_data(), ucd_field_file_io::read_alloc_ucd_2_fld_file(), ucd_field_file_io_b::read_alloc_ucd_2_fld_file_b(), ucd_field_file_io_b::read_alloc_ucd_2_fld_header_b(), ucd_field_mpi_io::read_alloc_ucd_fld_file_mpi(), ucd_field_mpi_io_b::read_alloc_ucd_fld_file_mpi_b(), udt_type_data_io::read_alloc_udt_field(), and udt_to_vtk_data_io::read_alloc_udt_field_from_vtk().
allocate_ucd_phys_name()
subroutine t_ucd_data::allocate_ucd_phys_name (type(ucd_data), intent(inout) ucd)
Definition at line 152 of file t_ucd_data.f90.
Referenced by allocate_ucd_nodal_data(), append_new_ucd_field_name(), gz_ucd_field_mpi_io_b::gz_rd_alloc_ucd_fld_file_mpi_b(), gz_read_udt_from_bin_data::gz_read_alloc_psf_bin_fld_data(), gz_ucd_field_file_io_b::gz_read_alloc_ucd_2_fld_file_b(), gz_ucd_field_file_io::gz_read_alloc_ucd_2_ld_file(), gz_ucd_field_mpi_io::gz_read_alloc_ucd_fld_file_mpi(), gz_udt_type_data_io::read_alloc_gz_udt_field(), gz_udt_to_vtk_data_io::read_alloc_gz_udt_fld_from_vtk(), read_udt_from_bindary_data::read_alloc_psf_bin_field_data(), ucd_field_file_io::read_alloc_ucd_2_fld_file(), ucd_field_file_io_b::read_alloc_ucd_2_fld_file_b(), ucd_field_file_io_b::read_alloc_ucd_2_fld_header_b(), ucd_field_mpi_io::read_alloc_ucd_fld_file_mpi(), ucd_field_mpi_io_b::read_alloc_ucd_fld_file_mpi_b(), udt_type_data_io::read_alloc_udt_field(), and udt_to_vtk_data_io::read_alloc_udt_field_from_vtk().
append_new_ucd_field_data()
subroutine t_ucd_data::append_new_ucd_field_data (integer(kind = kint), intent(in) ncomp_new_field, real(kind = kreal), dimension(ucd%nnod,ncomp_new_field) d_tmp, type(ucd_data), intent(inout) tmp, type(ucd_data), intent(inout) ucd)
Definition at line 445 of file t_ucd_data.f90.
References copy_between_two_fields::copy_fields_2_fields(), and m_constants::ione.
Referenced by gz_udt_to_vtk_data_io::read_alloc_gz_udt_fld_from_vtk(), and udt_to_vtk_data_io::read_alloc_udt_field_from_vtk().
append_new_ucd_field_name()
subroutine t_ucd_data::append_new_ucd_field_name (character(len=kchara), intent(in) new_field_name, integer(kind = kint), intent(in) ncomp_new_field, type(ucd_data), intent(inout) tmp, type(ucd_data), intent(inout) ucd)
Definition at line 410 of file t_ucd_data.f90.
References allocate_ucd_phys_data(), allocate_ucd_phys_name(), copy_between_two_fields::copy_fields_2_fields(), deallocate_ucd_data(), and m_constants::ione.
Referenced by gz_udt_to_vtk_data_io::read_alloc_gz_udt_fld_from_vtk(), and udt_to_vtk_data_io::read_alloc_udt_field_from_vtk().
cal_istack_ucd_component()
subroutine t_ucd_data::cal_istack_ucd_component (type(ucd_data), intent(inout) ucd)
Definition at line 394 of file t_ucd_data.f90.
Referenced by gz_ucd_field_mpi_io_b::gz_rd_alloc_ucd_fld_file_mpi_b(), gz_ucd_field_file_io_b::gz_read_alloc_ucd_2_fld_file_b(), gz_ucd_field_file_io::gz_read_alloc_ucd_2_ld_file(), gz_ucd_field_mpi_io::gz_read_alloc_ucd_fld_file_mpi(), gz_udt_type_data_io::read_alloc_gz_udt_field(), ucd_field_file_io::read_alloc_ucd_2_fld_file(), ucd_field_file_io_b::read_alloc_ucd_2_fld_file_b(), ucd_field_file_io_b::read_alloc_ucd_2_fld_header_b(), ucd_field_mpi_io::read_alloc_ucd_fld_file_mpi(), ucd_field_mpi_io_b::read_alloc_ucd_fld_file_mpi_b(), udt_type_data_io::read_alloc_udt_field(), gz_udt_type_data_io::read_gz_udt_field(), and udt_type_data_io::read_udt_field().
check_read_ucd_data()
subroutine t_ucd_data::check_read_ucd_data (type(ucd_data), intent(in) ucd_b)
Definition at line 467 of file t_ucd_data.f90.
compare_read_ucd_data()
subroutine t_ucd_data::compare_read_ucd_data (type(ucd_data), intent(in) ucd_b, type(ucd_data), intent(in) ucd_z)
Definition at line 497 of file t_ucd_data.f90.
dealloc_merged_ucd_ele_stack()
subroutine t_ucd_data::dealloc_merged_ucd_ele_stack (type(ucd_data), intent(inout) ucd)
Definition at line 382 of file t_ucd_data.f90.
Referenced by deallocate_parallel_ucd_mesh(), and merged_udt_vtk_file_io::finalize_merged_ucd().
dealloc_merged_ucd_nod_stack()
subroutine t_ucd_data::dealloc_merged_ucd_nod_stack (type(ucd_data), intent(inout) ucd)
Definition at line 370 of file t_ucd_data.f90.
Referenced by deallocate_parallel_ucd_mesh().
deallocate_parallel_ucd_mesh()
subroutine t_ucd_data::deallocate_parallel_ucd_mesh (type(ucd_data), intent(inout) ucd)
Definition at line 277 of file t_ucd_data.f90.
References dealloc_merged_ucd_ele_stack(), dealloc_merged_ucd_nod_stack(), deallocate_ucd_data(), deallocate_ucd_ele(), and deallocate_ucd_node().
deallocate_ucd_data()
subroutine t_ucd_data::deallocate_ucd_data (type(ucd_data), intent(inout) ucd)
Definition at line 252 of file t_ucd_data.f90.
References deallocate_ucd_phys_data(), and deallocate_ucd_phys_name().
Referenced by output_parallel_ucd_file::add_ucd_to_data(), append_new_ucd_field_name(), deallocate_parallel_ucd_mesh(), deallocate_ucd_mesh(), gz_udt_to_vtk_data_io::read_alloc_gz_udt_fld_from_vtk(), udt_to_vtk_data_io::read_alloc_udt_field_from_vtk(), output_parallel_ucd_file::set_data_by_read_ucd_once(), and output_parallel_ucd_file::subtract_by_ucd_data().
deallocate_ucd_ele()
subroutine t_ucd_data::deallocate_ucd_ele (type(ucd_data), intent(inout) ucd)
Definition at line 219 of file t_ucd_data.f90.
Referenced by deallocate_parallel_ucd_mesh(), deallocate_ucd_mesh(), disconnect_merged_ucd_mesh(), disconnect_ucd_mesh(), output_parallel_ucd_file::link_output_grd_file(), and output_parallel_ucd_file::output_udt_one_snapshot().
deallocate_ucd_mesh()
subroutine t_ucd_data::deallocate_ucd_mesh (type(ucd_data), intent(inout) ucd)
Definition at line 264 of file t_ucd_data.f90.
References deallocate_ucd_data(), deallocate_ucd_ele(), and deallocate_ucd_node().
Referenced by psf_file_to_vtk().
deallocate_ucd_node()
subroutine t_ucd_data::deallocate_ucd_node (type(ucd_data), intent(inout) ucd)
Definition at line 208 of file t_ucd_data.f90.
Referenced by deallocate_parallel_ucd_mesh(), deallocate_ucd_mesh(), output_parallel_ucd_file::link_output_grd_file(), and output_parallel_ucd_file::output_udt_one_snapshot().
deallocate_ucd_phys_data()
subroutine t_ucd_data::deallocate_ucd_phys_data (type(ucd_data), intent(inout) ucd)
Definition at line 230 of file t_ucd_data.f90.
Referenced by deallocate_ucd_data(), gz_ucd_field_mpi_io_b::gz_rd_alloc_ucd_fld_file_mpi_b(), gz_ucd_field_mpi_io::gz_read_alloc_ucd_fld_file_mpi(), ucd_field_mpi_io::read_alloc_ucd_fld_file_mpi(), and ucd_field_mpi_io_b::read_alloc_ucd_fld_file_mpi_b().
deallocate_ucd_phys_name()
subroutine t_ucd_data::deallocate_ucd_phys_name (type(ucd_data), intent(inout) ucd)
Definition at line 241 of file t_ucd_data.f90.
Referenced by deallocate_ucd_data(), gz_ucd_field_mpi_io_b::gz_rd_alloc_ucd_fld_file_mpi_b(), gz_ucd_field_mpi_io::gz_read_alloc_ucd_fld_file_mpi(), ucd_field_mpi_io::read_alloc_ucd_fld_file_mpi(), and ucd_field_mpi_io_b::read_alloc_ucd_fld_file_mpi_b().
disconnect_merged_ucd_mesh()
subroutine t_ucd_data::disconnect_merged_ucd_mesh (type(ucd_data), intent(inout) ucd)
Definition at line 330 of file t_ucd_data.f90.
References deallocate_ucd_ele(), disconnect_ucd_data(), disconnect_ucd_node(), unlink_merged_ucd_ele_stack(), and unlink_merged_ucd_nod_stack().
Referenced by t_cross_section::dealloc_psf_field_type(), and output_4_psf::output_isosurface().
disconnect_ucd_data()
subroutine t_ucd_data::disconnect_ucd_data (type(ucd_data), intent(inout) ucd)
Definition at line 304 of file t_ucd_data.f90.
Referenced by disconnect_merged_ucd_mesh(), disconnect_ucd_mesh(), output_parallel_ucd_file::link_output_ucd_file_once(), and output_parallel_ucd_file::output_udt_one_snapshot().
disconnect_ucd_mesh()
subroutine t_ucd_data::disconnect_ucd_mesh (type(ucd_data), intent(inout) ucd)
Definition at line 317 of file t_ucd_data.f90.
References deallocate_ucd_ele(), disconnect_ucd_data(), and disconnect_ucd_node().
disconnect_ucd_node()
subroutine t_ucd_data::disconnect_ucd_node (type(ucd_data), intent(inout) ucd)
Definition at line 293 of file t_ucd_data.f90.
Referenced by disconnect_merged_ucd_mesh(), and disconnect_ucd_mesh().
unlink_merged_ucd_ele_stack()
subroutine t_ucd_data::unlink_merged_ucd_ele_stack (type(ucd_data), intent(inout) ucd)
Definition at line 358 of file t_ucd_data.f90.
Referenced by disconnect_merged_ucd_mesh().
unlink_merged_ucd_nod_stack()
subroutine t_ucd_data::unlink_merged_ucd_nod_stack (type(ucd_data), intent(inout) ucd)
Definition at line 346 of file t_ucd_data.f90.
Referenced by disconnect_merged_ucd_mesh(), and merged_udt_vtk_file_io::finalize_merged_ucd().