CALYPSO: t_legendre_trans_select Module Reference
t_legendre_trans_select Module Reference
Legendre transform selector.
Data Types
type legendre_trns_works
Work structures for various Legendre trasform.
Functions/Subroutines
subroutine sel_init_legendre_trans (ncomp, nvector, nscalar, sph_params, sph_rtm, sph_rlm, leg, idx_trns, WK_leg)
subroutine sel_finalize_legendre_trans (WK_leg)
subroutine sel_backward_legendre_trans (ncomp, nvector, nscalar, sph_rlm, sph_rtm, comm_rlm, comm_rtm, leg, idx_trns, n_WR, n_WS, WR, WS, WK_leg)
subroutine sel_forward_legendre_trans (ncomp, nvector, nscalar, sph_rtm, sph_rlm, comm_rtm, comm_rlm, leg, idx_trns, n_WR, n_WS, WR, WS, WK_leg)
Detailed Description
Legendre transform selector.
      subroutine sel_init_legendre_trans(ncomp, nvector, nscalar,     &
     &          sph_params, sph_rtm, sph_rlm, leg, idx_trns, WK_leg)
      subroutine sel_finalize_legendre_trans(WK_leg)
    Backward transforms
      subroutine sel_backward_legendre_trans(ncomp, nvector, nscalar, &
     &          sph_rlm, sph_rtm, comm_rlm, comm_rtm, leg, idx_trns,  &
     &          n_WR, n_WS, WR, WS, WK_leg)
        Input:  sp_rlm   (Order: poloidal,diff_poloidal,toroidal)
        Output: vr_rtm   (Order: radius,theta,phi)
    Forward transforms
      subroutine sel_forward_legendre_trans(ncomp, nvector, nscalar,  &
     &          sph_rtm, sph_rlm, comm_rtm, comm_rlm, leg, idx_trns,  &
     &          n_WR, n_WS, WR, WS, WK_leg)
        Input:  vr_rtm   (Order: radius,theta,phi)
        Output: sp_rlm   (Order: poloidal,diff_poloidal,toroidal)
        type(sph_shell_parameters), intent(in) :: sph_params
        type(sph_rtm_grid), intent(in) :: sph_rtm
        type(sph_rlm_grid), intent(in) :: sph_rlm
        type(sph_comm_tbl), intent(in) :: comm_rtm, comm_rlm
        type(legendre_4_sph_trans), intent(in) :: leg
        type(index_4_sph_trans), intent(in) :: idx_trns
        type(legendre_trns_works), intent(inout) :: WK_leg
Parameters
ncomp Total number of components for spherical transform
nvector Number of vector for spherical transform
nscalar Number of scalar (including tensor components) for spherical transform
Function/Subroutine Documentation
sel_backward_legendre_trans()
subroutine t_legendre_trans_select::sel_backward_legendre_trans (integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_comm_tbl), intent(in) comm_rlm, type(sph_comm_tbl), intent(in) comm_rtm, type(legendre_4_sph_trans), intent(in) leg, type(index_4_sph_trans), intent(in) idx_trns, integer(kind = kint), intent(in) n_WR, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_wr), intent(inout) WR, real (kind=kreal), dimension(n_ws), intent(inout) WS, type(legendre_trns_works), intent(inout) WK_leg)
Definition at line 185 of file t_legendre_trans_select.f90.
References matmul_for_legendre_trans::iflag_dgemm, matmul_for_legendre_trans::iflag_intrinsic, m_legendre_transform_list::iflag_leg_sym_dgemm, m_legendre_transform_list::iflag_leg_sym_dgemm_big, m_legendre_transform_list::iflag_leg_sym_dgemm_jt, m_legendre_transform_list::iflag_leg_sym_dgemm_tj, m_legendre_transform_list::iflag_leg_sym_mat_jt, m_legendre_transform_list::iflag_leg_sym_mat_tj, m_legendre_transform_list::iflag_leg_sym_matmul, m_legendre_transform_list::iflag_leg_sym_matmul_big, m_legendre_transform_list::iflag_leg_sym_spin_loop, m_legendre_transform_list::iflag_leg_test_loop, matmul_for_legendre_trans::iflag_matprod, m_legendre_transform_list::iflag_on_the_fly_dgemm, m_legendre_transform_list::iflag_on_the_fly_matmul, m_legendre_transform_list::iflag_on_the_fly_matprod, legendre_trans_matmul_big::leg_backward_trans_matmul_big(), legendre_transform_sym_tomp::leg_backward_trans_smat_jt(), legendre_transform_sym_tomp::leg_backward_trans_smat_tj(), legendre_trans_sym_matmul::leg_backward_trans_sym_matmul(), legendre_transform_org::leg_backward_trans_sym_org(), legendre_transform_spin::leg_backward_trans_sym_spin(), legendre_transform_testloop::leg_backward_trans_test(), and leg_bwd_trans_on_the_fly::legendre_b_trans_on_the_fly().
Referenced by sph_trans_w_coriols::sph_b_trans_w_coriolis(), t_sph_transforms::sph_b_trans_w_poles(), and t_sph_transforms::sph_backward_transforms().
sel_finalize_legendre_trans()
subroutine t_legendre_trans_select::sel_finalize_legendre_trans (type(legendre_trns_works), intent(inout) WK_leg)
Definition at line 150 of file t_legendre_trans_select.f90.
References t_legendre_work_testlooop::dealloc_leg_sym_mat_both(), t_legendre_work_sym_mat_jt::dealloc_leg_sym_mat_jt(), t_legendre_work_sym_mat_jt::dealloc_leg_sym_mat_tj(), t_leg_trans_sym_matmul_big::dealloc_leg_sym_matmul_big(), t_legendre_work_sym_matmul::finalize_legendre_sym_matmul(), m_legendre_transform_list::iflag_leg_sym_dgemm, m_legendre_transform_list::iflag_leg_sym_dgemm_big, m_legendre_transform_list::iflag_leg_sym_dgemm_jt, m_legendre_transform_list::iflag_leg_sym_dgemm_tj, m_legendre_transform_list::iflag_leg_sym_mat_jt, m_legendre_transform_list::iflag_leg_sym_mat_tj, m_legendre_transform_list::iflag_leg_sym_matmul, m_legendre_transform_list::iflag_leg_sym_matmul_big, m_legendre_transform_list::iflag_leg_sym_spin_loop, m_legendre_transform_list::iflag_leg_test_loop, m_legendre_transform_list::iflag_on_the_fly_dgemm, m_legendre_transform_list::iflag_on_the_fly_matmul, and m_legendre_transform_list::iflag_on_the_fly_matprod.
Referenced by test_legendre_transforms::s_test_legendre_transforms().
sel_forward_legendre_trans()
subroutine t_legendre_trans_select::sel_forward_legendre_trans (integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_comm_tbl), intent(in) comm_rtm, type(sph_comm_tbl), intent(in) comm_rlm, type(legendre_4_sph_trans), intent(in) leg, type(index_4_sph_trans), intent(in) idx_trns, integer(kind = kint), intent(in) n_WR, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_wr), intent(inout) WR, real (kind=kreal), dimension(n_ws), intent(inout) WS, type(legendre_trns_works), intent(inout) WK_leg)
Definition at line 280 of file t_legendre_trans_select.f90.
References matmul_for_legendre_trans::iflag_dgemm, matmul_for_legendre_trans::iflag_intrinsic, m_legendre_transform_list::iflag_leg_sym_dgemm, m_legendre_transform_list::iflag_leg_sym_dgemm_big, m_legendre_transform_list::iflag_leg_sym_dgemm_jt, m_legendre_transform_list::iflag_leg_sym_dgemm_tj, m_legendre_transform_list::iflag_leg_sym_mat_jt, m_legendre_transform_list::iflag_leg_sym_mat_tj, m_legendre_transform_list::iflag_leg_sym_matmul, m_legendre_transform_list::iflag_leg_sym_matmul_big, m_legendre_transform_list::iflag_leg_sym_spin_loop, m_legendre_transform_list::iflag_leg_test_loop, matmul_for_legendre_trans::iflag_matprod, m_legendre_transform_list::iflag_on_the_fly_dgemm, m_legendre_transform_list::iflag_on_the_fly_matmul, m_legendre_transform_list::iflag_on_the_fly_matprod, legendre_trans_matmul_big::leg_forward_trans_matmul_big(), legendre_transform_sym_tomp::leg_forward_trans_smat_jt(), legendre_transform_sym_tomp::leg_forward_trans_smat_tj(), legendre_trans_sym_matmul::leg_forward_trans_sym_matmul(), legendre_transform_org::leg_forward_trans_sym_org(), legendre_transform_spin::leg_forward_trans_sym_spin(), legendre_transform_testloop::leg_forward_trans_test(), and leg_fwd_trans_on_the_fly::legendre_f_trans_on_the_fly().
Referenced by sph_trans_w_coriols::sph_f_trans_w_coriolis(), and t_sph_transforms::sph_forward_transforms().
sel_init_legendre_trans()
subroutine t_legendre_trans_select::sel_init_legendre_trans (integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_shell_parameters), intent(in) sph_params, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(legendre_4_sph_trans), intent(in) leg, type(index_4_sph_trans), intent(in) idx_trns, type(legendre_trns_works), intent(inout) WK_leg)
Definition at line 99 of file t_legendre_trans_select.f90.
References m_legendre_transform_list::iflag_leg_sym_dgemm, m_legendre_transform_list::iflag_leg_sym_dgemm_big, m_legendre_transform_list::iflag_leg_sym_dgemm_jt, m_legendre_transform_list::iflag_leg_sym_dgemm_tj, m_legendre_transform_list::iflag_leg_sym_mat_jt, m_legendre_transform_list::iflag_leg_sym_mat_tj, m_legendre_transform_list::iflag_leg_sym_matmul, m_legendre_transform_list::iflag_leg_sym_matmul_big, m_legendre_transform_list::iflag_leg_sym_spin_loop, m_legendre_transform_list::iflag_leg_test_loop, m_legendre_transform_list::iflag_on_the_fly_dgemm, m_legendre_transform_list::iflag_on_the_fly_matmul, m_legendre_transform_list::iflag_on_the_fly_matprod, t_leg_trans_sym_matmul_big::init_leg_sym_matmul_big(), t_legendre_work_testlooop::init_legendre_sym_mat_both(), t_legendre_work_sym_mat_jt::init_legendre_sym_mat_jt(), t_legendre_work_sym_mat_jt::init_legendre_sym_mat_tj(), t_legendre_work_sym_matmul::init_legendre_sym_matmul(), and t_legendre_work_sym_matmul::init_legendre_symmetry().
Referenced by init_sph_trans::initialize_sph_trans(), test_legendre_transforms::s_test_legendre_transforms(), and init_sphrical_transform_mhd::sel_sph_transform_mhd().