CALYPSO: t_control_array_integer2 Module Reference
t_control_array_integer2 Module Reference
Data Types
type ctl_array_i2
Structure for 2 integers control array.
type read_int2_item
structure of control integer item
Functions/Subroutines
subroutine read_integer2_ctl_type (c_buf, label, int2_item)
subroutine write_integer2_ctl_type (id_file, level, label, int2_item)
subroutine copy_integer2_ctl (org_i2, new_i2)
subroutine alloc_control_array_i2 (array_i2)
subroutine dealloc_control_array_i2 (array_i2)
subroutine read_control_array_i2 (id_control, label, array_i2, c_buf)
subroutine write_control_array_i2 (id_control, level, label, array_i2)
subroutine append_control_array_i2 (read_i2, array_i2)
subroutine dup_control_array_i2 (org_i2, tgt_i2)
subroutine copy_control_array_i2 (num_copy, org_i2, tgt_i2)
subroutine append_control_item_i2 (read_i2, array_i2)
Function/Subroutine Documentation
alloc_control_array_i2()
subroutine t_control_array_integer2::alloc_control_array_i2 (type(ctl_array_i2), intent(inout) array_i2)
Definition at line 132 of file t_control_array_integer2.f90.
Referenced by append_control_array_i2(), bcast_control_arrays::bcast_ctl_array_i2(), dup_control_array_i2(), and read_control_array_i2().
append_control_array_i2()
subroutine t_control_array_integer2::append_control_array_i2 (type(read_int2_item), intent(inout) read_i2, type(ctl_array_i2), intent(inout) array_i2)
Definition at line 225 of file t_control_array_integer2.f90.
References alloc_control_array_i2(), append_control_item_i2(), copy_control_array_i2(), and dealloc_control_array_i2().
Referenced by read_control_array_i2().
append_control_item_i2()
subroutine t_control_array_integer2::append_control_item_i2 (type(read_int2_item), intent(in) read_i2, type(ctl_array_i2), intent(inout) array_i2)
Definition at line 280 of file t_control_array_integer2.f90.
Referenced by append_control_array_i2().
copy_control_array_i2()
subroutine t_control_array_integer2::copy_control_array_i2 (integer(kind = kint), intent(in) num_copy, type(ctl_array_i2), intent(in) org_i2, type(ctl_array_i2), intent(inout) tgt_i2)
Definition at line 264 of file t_control_array_integer2.f90.
Referenced by append_control_array_i2(), and dup_control_array_i2().
copy_integer2_ctl()
subroutine t_control_array_integer2::copy_integer2_ctl (type(read_int2_item), intent(in) org_i2, type(read_int2_item), intent(inout) new_i2)
Definition at line 119 of file t_control_array_integer2.f90.
dealloc_control_array_i2()
subroutine t_control_array_integer2::dealloc_control_array_i2 (type(ctl_array_i2), intent(inout) array_i2)
Definition at line 148 of file t_control_array_integer2.f90.
Referenced by append_control_array_i2(), t_ctl_data_4_sphere_model::dealloc_control_shell_define(), t_ctl_data_pick_sph_spectr::dealloc_gauss_spectr_control(), t_ctl_data_node_monitor::dealloc_monitor_data_ctl(), and t_ctl_data_pick_sph_spectr::dealloc_pick_spectr_control().
dup_control_array_i2()
subroutine t_control_array_integer2::dup_control_array_i2 (type(ctl_array_i2), intent(in) org_i2, type(ctl_array_i2), intent(inout) tgt_i2)
Definition at line 250 of file t_control_array_integer2.f90.
References alloc_control_array_i2(), and copy_control_array_i2().
read_control_array_i2()
subroutine t_control_array_integer2::read_control_array_i2 (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) label, type(ctl_array_i2), intent(inout) array_i2, type(buffer_for_control), intent(inout) c_buf)
Definition at line 162 of file t_control_array_integer2.f90.
References alloc_control_array_i2(), append_control_array_i2(), t_read_control_elements::check_array_flag(), t_read_control_elements::check_end_array_flag(), t_read_control_elements::load_one_line_from_control(), and read_integer2_ctl_type().
Referenced by t_ctl_data_4_sphere_model::read_control_shell_define(), t_ctl_data_pick_sph_spectr::read_gauss_spectr_ctl(), t_ctl_data_node_monitor::read_monitor_data_ctl(), and t_ctl_data_pick_sph_spectr::read_pickup_spectr_ctl().
read_integer2_ctl_type()
subroutine t_control_array_integer2::read_integer2_ctl_type (type(buffer_for_control), intent(in) c_buf, character(len=kchara), intent(in) label, type(read_int2_item), intent(inout) int2_item)
Definition at line 79 of file t_control_array_integer2.f90.
References m_machine_parameter::iflag_debug.
Referenced by read_control_array_i2().
write_control_array_i2()
subroutine t_control_array_integer2::write_control_array_i2 (integer(kind = kint), intent(in) id_control, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, type(ctl_array_i2), intent(in) array_i2)
Definition at line 196 of file t_control_array_integer2.f90.
References write_control_elements::write_array_flag_for_ctl(), write_control_elements::write_end_array_flag_for_ctl(), and write_control_elements::write_integer2_ctl_item().
write_integer2_ctl_type()
subroutine t_control_array_integer2::write_integer2_ctl_type (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, type(read_int2_item), intent(in) int2_item)
Definition at line 101 of file t_control_array_integer2.f90.
References write_control_elements::write_integer2_ctl_item().