CALYPSO: m_section_coef_flags Module Reference
m_section_coef_flags Module Reference
Set coefficients for cross section function.
Functions/Subroutines
subroutine set_coefs_4_psf (num_const, c_name_psf, const_psf_ctl, c_surf)
subroutine set_parameter_2_vectors (num_vect, ctl_name, vect_ctl, vector)
subroutine set_primary_section_coef_flag (dir_ctl)
integer(kind=kint) function num_label_psf_coefs ()
integer(kind=kint) function num_label_psf_dirs ()
subroutine set_label_psf_coefs (names)
subroutine set_label_psf_dirs (names)
subroutine, private init_section_coef_flags ()
subroutine, private dealloc_section_coef_flags ()
subroutine, private set_each_coef_4_psf (dir_ctl, coef_ctl, c_surf)
subroutine, private set_each_param_2_vector (ctl_name, vect_ctl, vector)
subroutine, private init_primary_section_coef_flag
Variables
character(len=kchara), dimension(3), parameter, private x_sq_name = (/'XX ', 'X2 ', 'X^2 '/)
character(len=kchara), dimension(3), parameter, private y_sq_name = (/'YY ', 'Y2 ', 'Y^2 '/)
character(len=kchara), dimension(3), parameter, private z_sq_name = (/'ZZ ', 'Z2 ', 'Z^2 '/)
character(len=kchara), dimension(2), parameter, private xy_name = (/'XY ', 'YX '/)
character(len=kchara), dimension(2), parameter, private yz_name = (/'YZ ', 'ZY '/)
character(len=kchara), dimension(2), parameter, private zx_name = (/'ZX ', 'XZ '/)
character(len=kchara), dimension(3), parameter, private x_name = (/'X ', 'X1 ', 'X^1 '/)
character(len=kchara), dimension(3), parameter, private y_name = (/'Y ', 'Y1 ', 'Y^1 '/)
character(len=kchara), dimension(3), parameter, private z_name = (/'Z ', 'Z1 ', 'Z^1 '/)
character(len=kchara), dimension(2), parameter, private c_name = (/'Const ', 'C '/)
type(multi_flag_labels), save x_sq_labels
flags for square of X: 'XX', 'X2', 'X^2 '
type(multi_flag_labels), save y_sq_labels
flags for square of Y: 'YY', 'Y2', 'Y^2 '
type(multi_flag_labels), save z_sq_labels
flags for square of Z: 'ZZ', 'Z2', 'Z^2 '
type(multi_flag_labels), save xy_labels
flags for xy: 'XY', 'YX'
type(multi_flag_labels), save yz_labels
flags for yz: 'YZ', 'ZY'
type(multi_flag_labels), save zx_labels
flags for zx: 'ZX', 'XZ'
type(multi_flag_labels), save x_labels
flags for x: 'X', 'X1', 'X^1'
type(multi_flag_labels), save y_labels
flags for y: 'Y', 'Y1', 'Y^1'
type(multi_flag_labels), save z_labels
flags for z: 'Z', 'Z1', 'z^1'
type(multi_flag_labels), save c_labels
flags for Constant: 'Const', 'C'
character(len=kchara), save cflag_x_sq
primary flag for square of X: 'X^2 '
character(len=kchara), save cflag_y_sq
primary flag for square of Y: 'Y^2 '
character(len=kchara), save cflag_z_sq
primary flag for square of Z: 'Z^2 '
character(len=kchara), save cflag_xy
primary flag for xy: 'XY'
character(len=kchara), save cflag_yz
primary flag for yz: 'YZ'
character(len=kchara), save cflag_zx
primary flag for zx: 'ZX'
character(len=kchara), save cflag_x
primary flag for x: 'X'
character(len=kchara), save cflag_y
primary flag for y: 'Y'
character(len=kchara), save cflag_z
primary flag for z: 'Z'
character(len=kchara), save cflag_const
primary flag for Constant: 'Const'
integer(kind=kint), parameter n_label_psf_coefs = 10
integer(kind=kint), parameter n_label_psf_dirs = 3
Detailed Description
Set coefficients for cross section function.
      subroutine set_coefs_4_psf                                      &
     &         (num_const, c_name_psf, const_psf_ctl, c_surf)
        integer(kind = kint), intent(in) :: num_const
        character(len=kchara), intent(in) :: c_name_psf(num_const)
        real(kind = kreal), intent(in) :: const_psf_ctl(num_const)
        real(kind = kreal), intent(inout) :: c_surf(10)
      subroutine set_parameter_2_vectors                              &
     &         (num_vect, ctl_name, vect_ctl, vector)
        integer(kind = kint), intent(in) :: num_vect
        character(len=kchara), intent(in) :: ctl_name(num_vect)
        real(kind = kreal), intent(in) :: vect_ctl(num_vect)
        real(kind = kreal), intent(inout) :: vector(3)
      subroutine set_primary_section_coef_flag(dir_ctl)
        character(len=kchara), intent(inout) :: dir_ctl
      integer(kind = kint) function num_label_psf_coefs()
      integer(kind = kint) function num_label_psf_dirs()
      subroutine set_label_psf_coefs(names)
      subroutine set_label_psf_dirs(names)
Function/Subroutine Documentation
dealloc_section_coef_flags()
subroutine, private m_section_coef_flags::dealloc_section_coef_flags private
Definition at line 287 of file m_section_coef_flags.f90.
References c_labels, t_multi_flag_labels::dealloc_multi_flags(), x_labels, x_sq_labels, xy_labels, y_labels, y_sq_labels, yz_labels, z_labels, z_sq_labels, and zx_labels.
Referenced by set_coefs_4_psf(), and set_primary_section_coef_flag().
init_primary_section_coef_flag()
subroutine, private m_section_coef_flags::init_primary_section_coef_flag private
Definition at line 363 of file m_section_coef_flags.f90.
References c_name, cflag_const, cflag_x, cflag_x_sq, cflag_xy, cflag_y, cflag_y_sq, cflag_yz, cflag_z, cflag_z_sq, cflag_zx, x_name, x_sq_name, xy_name, y_name, y_sq_name, yz_name, z_name, z_sq_name, and zx_name.
Referenced by set_label_psf_coefs(), set_label_psf_dirs(), set_parameter_2_vectors(), and set_primary_section_coef_flag().
init_section_coef_flags()
subroutine, private m_section_coef_flags::init_section_coef_flags private
Definition at line 269 of file m_section_coef_flags.f90.
References c_labels, c_name, t_multi_flag_labels::init_multi_flags_by_labels(), m_constants::ithree, m_constants::itwo, x_labels, x_name, x_sq_labels, x_sq_name, xy_labels, xy_name, y_labels, y_name, y_sq_labels, y_sq_name, yz_labels, yz_name, z_labels, z_name, z_sq_labels, z_sq_name, zx_labels, and zx_name.
Referenced by set_coefs_4_psf(), and set_primary_section_coef_flag().
num_label_psf_coefs()
integer(kind = kint) function m_section_coef_flags::num_label_psf_coefs
Definition at line 213 of file m_section_coef_flags.f90.
References n_label_psf_coefs.
num_label_psf_dirs()
integer(kind = kint) function m_section_coef_flags::num_label_psf_dirs
Definition at line 220 of file m_section_coef_flags.f90.
References n_label_psf_dirs.
set_coefs_4_psf()
subroutine m_section_coef_flags::set_coefs_4_psf (integer(kind = kint), intent(in) num_const, character(len=kchara), dimension(num_const), intent(in) c_name_psf, real(kind = kreal), dimension(num_const), intent(in) const_psf_ctl, real(kind = kreal), dimension(10), intent(inout) c_surf)
Definition at line 129 of file m_section_coef_flags.f90.
References dealloc_section_coef_flags(), init_section_coef_flags(), and set_each_coef_4_psf().
Referenced by set_coefs_of_sections::s_set_coefs_of_sections().
set_each_coef_4_psf()
subroutine, private m_section_coef_flags::set_each_coef_4_psf (character(len=kchara), intent(in) dir_ctl, real(kind = kreal), intent(in) coef_ctl, real(kind = kreal), dimension(10), intent(inout) c_surf) private
Definition at line 306 of file m_section_coef_flags.f90.
References c_labels, t_multi_flag_labels::check_mul_flags(), x_labels, x_sq_labels, xy_labels, y_labels, y_sq_labels, yz_labels, z_labels, z_sq_labels, and zx_labels.
Referenced by set_coefs_4_psf().
set_each_param_2_vector()
subroutine, private m_section_coef_flags::set_each_param_2_vector (character(len=kchara), intent(in) ctl_name, real(kind = kreal), intent(in) vect_ctl, real(kind = kreal), dimension(3), intent(inout) vector) private
Definition at line 340 of file m_section_coef_flags.f90.
References cflag_x, cflag_y, cflag_z, and skip_comment_f::cmp_no_case().
Referenced by set_parameter_2_vectors().
set_label_psf_coefs()
subroutine m_section_coef_flags::set_label_psf_coefs (character(len = kchara), dimension(n_label_psf_coefs), intent(inout) names)
Definition at line 227 of file m_section_coef_flags.f90.
References cflag_const, cflag_x, cflag_x_sq, cflag_xy, cflag_y, cflag_y_sq, cflag_yz, cflag_z, cflag_z_sq, cflag_zx, init_primary_section_coef_flag(), and t_read_control_elements::set_control_labels().
set_label_psf_dirs()
subroutine m_section_coef_flags::set_label_psf_dirs (character(len = kchara), dimension(n_label_psf_dirs), intent(inout) names)
Definition at line 251 of file m_section_coef_flags.f90.
References cflag_x, cflag_y, cflag_z, init_primary_section_coef_flag(), and t_read_control_elements::set_control_labels().
set_parameter_2_vectors()
subroutine m_section_coef_flags::set_parameter_2_vectors (integer(kind = kint), intent(in) num_vect, character(len=kchara), dimension(num_vect), intent(in) ctl_name, real(kind = kreal), dimension(num_vect), intent(in) vect_ctl, real(kind = kreal), dimension(3), intent(inout) vector)
Definition at line 152 of file m_section_coef_flags.f90.
References init_primary_section_coef_flag(), set_each_param_2_vector(), and m_constants::zero.
Referenced by set_cross_section_coefs::set_coefs_4_ellipsode(), set_cross_section_coefs::set_coefs_4_hyperboloide(), set_cross_section_coefs::set_coefs_4_parabolic(), set_cross_section_coefs::set_coefs_4_plane(), and set_cross_section_coefs::set_coefs_4_sphere().
set_primary_section_coef_flag()
subroutine m_section_coef_flags::set_primary_section_coef_flag (character(len=kchara), intent(inout) dir_ctl)
Definition at line 174 of file m_section_coef_flags.f90.
References c_labels, cflag_const, cflag_x, cflag_x_sq, cflag_xy, cflag_y, cflag_y_sq, cflag_yz, cflag_z, cflag_z_sq, cflag_zx, t_multi_flag_labels::check_mul_flags(), dealloc_section_coef_flags(), init_primary_section_coef_flag(), init_section_coef_flags(), x_labels, x_sq_labels, xy_labels, y_labels, y_sq_labels, yz_labels, z_labels, z_sq_labels, and zx_labels.
Variable Documentation
c_labels
type(multi_flag_labels), save m_section_coef_flags::c_labels
flags for Constant: 'Const', 'C'
Definition at line 85 of file m_section_coef_flags.f90.
Referenced by dealloc_section_coef_flags(), init_section_coef_flags(), set_each_coef_4_psf(), and set_primary_section_coef_flag().
c_name
character(len=kchara), dimension(2), parameter, private m_section_coef_flags::c_name = (/'Const ', 'C '/) private
Definition at line 60 of file m_section_coef_flags.f90.
Referenced by init_primary_section_coef_flag(), and init_section_coef_flags().
cflag_const
character(len=kchara), save m_section_coef_flags::cflag_const
primary flag for Constant: 'Const'
Definition at line 110 of file m_section_coef_flags.f90.
Referenced by init_primary_section_coef_flag(), set_label_psf_coefs(), and set_primary_section_coef_flag().
cflag_x
character(len=kchara), save m_section_coef_flags::cflag_x
primary flag for x: 'X'
Definition at line 103 of file m_section_coef_flags.f90.
Referenced by init_primary_section_coef_flag(), set_each_param_2_vector(), set_label_psf_coefs(), set_label_psf_dirs(), and set_primary_section_coef_flag().
cflag_x_sq
character(len=kchara), save m_section_coef_flags::cflag_x_sq
primary flag for square of X: 'X^2 '
Definition at line 89 of file m_section_coef_flags.f90.
Referenced by init_primary_section_coef_flag(), set_label_psf_coefs(), and set_primary_section_coef_flag().
cflag_xy
character(len=kchara), save m_section_coef_flags::cflag_xy
primary flag for xy: 'XY'
Definition at line 96 of file m_section_coef_flags.f90.
Referenced by init_primary_section_coef_flag(), set_label_psf_coefs(), and set_primary_section_coef_flag().
cflag_y
character(len=kchara), save m_section_coef_flags::cflag_y
primary flag for y: 'Y'
Definition at line 105 of file m_section_coef_flags.f90.
Referenced by init_primary_section_coef_flag(), set_each_param_2_vector(), set_label_psf_coefs(), set_label_psf_dirs(), and set_primary_section_coef_flag().
cflag_y_sq
character(len=kchara), save m_section_coef_flags::cflag_y_sq
primary flag for square of Y: 'Y^2 '
Definition at line 91 of file m_section_coef_flags.f90.
Referenced by init_primary_section_coef_flag(), set_label_psf_coefs(), and set_primary_section_coef_flag().
cflag_yz
character(len=kchara), save m_section_coef_flags::cflag_yz
primary flag for yz: 'YZ'
Definition at line 98 of file m_section_coef_flags.f90.
Referenced by init_primary_section_coef_flag(), set_label_psf_coefs(), and set_primary_section_coef_flag().
cflag_z
character(len=kchara), save m_section_coef_flags::cflag_z
primary flag for z: 'Z'
Definition at line 107 of file m_section_coef_flags.f90.
Referenced by init_primary_section_coef_flag(), set_each_param_2_vector(), set_label_psf_coefs(), set_label_psf_dirs(), and set_primary_section_coef_flag().
cflag_z_sq
character(len=kchara), save m_section_coef_flags::cflag_z_sq
primary flag for square of Z: 'Z^2 '
Definition at line 93 of file m_section_coef_flags.f90.
Referenced by init_primary_section_coef_flag(), set_label_psf_coefs(), and set_primary_section_coef_flag().
cflag_zx
character(len=kchara), save m_section_coef_flags::cflag_zx
primary flag for zx: 'ZX'
Definition at line 100 of file m_section_coef_flags.f90.
Referenced by init_primary_section_coef_flag(), set_label_psf_coefs(), and set_primary_section_coef_flag().
n_label_psf_coefs
integer(kind = kint), parameter m_section_coef_flags::n_label_psf_coefs = 10
Definition at line 112 of file m_section_coef_flags.f90.
Referenced by num_label_psf_coefs().
n_label_psf_dirs
integer(kind = kint), parameter m_section_coef_flags::n_label_psf_dirs = 3
Definition at line 113 of file m_section_coef_flags.f90.
Referenced by num_label_psf_dirs().
x_labels
type(multi_flag_labels), save m_section_coef_flags::x_labels
flags for x: 'X', 'X1', 'X^1'
Definition at line 78 of file m_section_coef_flags.f90.
Referenced by dealloc_section_coef_flags(), init_section_coef_flags(), set_each_coef_4_psf(), and set_primary_section_coef_flag().
x_name
character(len=kchara), dimension(3), parameter, private m_section_coef_flags::x_name = (/'X ', 'X1 ', 'X^1 '/) private
Definition at line 53 of file m_section_coef_flags.f90.
Referenced by init_primary_section_coef_flag(), and init_section_coef_flags().
x_sq_labels
type(multi_flag_labels), save m_section_coef_flags::x_sq_labels
flags for square of X: 'XX', 'X2', 'X^2 '
Definition at line 64 of file m_section_coef_flags.f90.
Referenced by dealloc_section_coef_flags(), init_section_coef_flags(), set_each_coef_4_psf(), and set_primary_section_coef_flag().
x_sq_name
character(len=kchara), dimension(3), parameter, private m_section_coef_flags::x_sq_name = (/'XX ', 'X2 ', 'X^2 '/) private
Definition at line 39 of file m_section_coef_flags.f90.
Referenced by init_primary_section_coef_flag(), and init_section_coef_flags().
xy_labels
type(multi_flag_labels), save m_section_coef_flags::xy_labels
flags for xy: 'XY', 'YX'
Definition at line 71 of file m_section_coef_flags.f90.
Referenced by dealloc_section_coef_flags(), init_section_coef_flags(), set_each_coef_4_psf(), and set_primary_section_coef_flag().
xy_name
character(len=kchara), dimension(2), parameter, private m_section_coef_flags::xy_name = (/'XY ', 'YX '/) private
Definition at line 46 of file m_section_coef_flags.f90.
Referenced by init_primary_section_coef_flag(), and init_section_coef_flags().
y_labels
type(multi_flag_labels), save m_section_coef_flags::y_labels
flags for y: 'Y', 'Y1', 'Y^1'
Definition at line 80 of file m_section_coef_flags.f90.
Referenced by dealloc_section_coef_flags(), init_section_coef_flags(), set_each_coef_4_psf(), and set_primary_section_coef_flag().
y_name
character(len=kchara), dimension(3), parameter, private m_section_coef_flags::y_name = (/'Y ', 'Y1 ', 'Y^1 '/) private
Definition at line 55 of file m_section_coef_flags.f90.
Referenced by init_primary_section_coef_flag(), and init_section_coef_flags().
y_sq_labels
type(multi_flag_labels), save m_section_coef_flags::y_sq_labels
flags for square of Y: 'YY', 'Y2', 'Y^2 '
Definition at line 66 of file m_section_coef_flags.f90.
Referenced by dealloc_section_coef_flags(), init_section_coef_flags(), set_each_coef_4_psf(), and set_primary_section_coef_flag().
y_sq_name
character(len=kchara), dimension(3), parameter, private m_section_coef_flags::y_sq_name = (/'YY ', 'Y2 ', 'Y^2 '/) private
Definition at line 41 of file m_section_coef_flags.f90.
Referenced by init_primary_section_coef_flag(), and init_section_coef_flags().
yz_labels
type(multi_flag_labels), save m_section_coef_flags::yz_labels
flags for yz: 'YZ', 'ZY'
Definition at line 73 of file m_section_coef_flags.f90.
Referenced by dealloc_section_coef_flags(), init_section_coef_flags(), set_each_coef_4_psf(), and set_primary_section_coef_flag().
yz_name
character(len=kchara), dimension(2), parameter, private m_section_coef_flags::yz_name = (/'YZ ', 'ZY '/) private
Definition at line 48 of file m_section_coef_flags.f90.
Referenced by init_primary_section_coef_flag(), and init_section_coef_flags().
z_labels
type(multi_flag_labels), save m_section_coef_flags::z_labels
flags for z: 'Z', 'Z1', 'z^1'
Definition at line 82 of file m_section_coef_flags.f90.
Referenced by dealloc_section_coef_flags(), init_section_coef_flags(), set_each_coef_4_psf(), and set_primary_section_coef_flag().
z_name
character(len=kchara), dimension(3), parameter, private m_section_coef_flags::z_name = (/'Z ', 'Z1 ', 'Z^1 '/) private
Definition at line 57 of file m_section_coef_flags.f90.
Referenced by init_primary_section_coef_flag(), and init_section_coef_flags().
z_sq_labels
type(multi_flag_labels), save m_section_coef_flags::z_sq_labels
flags for square of Z: 'ZZ', 'Z2', 'Z^2 '
Definition at line 68 of file m_section_coef_flags.f90.
Referenced by dealloc_section_coef_flags(), init_section_coef_flags(), set_each_coef_4_psf(), and set_primary_section_coef_flag().
z_sq_name
character(len=kchara), dimension(3), parameter, private m_section_coef_flags::z_sq_name = (/'ZZ ', 'Z2 ', 'Z^2 '/) private
Definition at line 43 of file m_section_coef_flags.f90.
Referenced by init_primary_section_coef_flag(), and init_section_coef_flags().
zx_labels
type(multi_flag_labels), save m_section_coef_flags::zx_labels
flags for zx: 'ZX', 'XZ'
Definition at line 75 of file m_section_coef_flags.f90.
Referenced by dealloc_section_coef_flags(), init_section_coef_flags(), set_each_coef_4_psf(), and set_primary_section_coef_flag().
zx_name
character(len=kchara), dimension(2), parameter, private m_section_coef_flags::zx_name = (/'ZX ', 'XZ '/) private
Definition at line 50 of file m_section_coef_flags.f90.
Referenced by init_primary_section_coef_flag(), and init_section_coef_flags().