CALYPSO: t_field_product_labels Module Reference
t_field_product_labels Module Reference
Data Types
type phys_products_address
Structure for start address for fields.
Functions/Subroutines
subroutine set_field_product_addresses (i_phys, field_name, prod_fld, flag)
Function/Subroutine Documentation
set_field_product_addresses()
subroutine t_field_product_labels::set_field_product_addresses (integer(kind = kint), intent(in) i_phys, character(len = kchara), intent(in) field_name, type(phys_products_address), intent(inout) prod_fld, logical, intent(inout) flag)
Definition at line 122 of file t_field_product_labels.f90.
References m_field_product_labels::check_field_product_scalars(), m_field_product_labels::check_field_product_vectors(), m_field_product_labels::composition_scale, m_field_product_labels::cross_helicity, m_field_product_labels::current_helicity, m_field_product_labels::electric_field, m_field_product_labels::kinetic_helicity, m_field_product_labels::magnetic_helicity, m_field_product_labels::magnetic_scale, m_field_product_labels::poynting_flux, m_field_product_labels::rest_of_geostrophic, m_field_product_labels::square_composition, m_field_product_labels::square_current, m_field_product_labels::square_magne, m_field_product_labels::square_temperature, m_field_product_labels::square_vector_potential, m_field_product_labels::square_velocity, m_field_product_labels::square_vorticity, m_field_product_labels::stream_pol_velocity, m_field_product_labels::temperature_scale, m_field_product_labels::truncated_magnetic_field, and m_field_product_labels::velocity_scale.
Referenced by set_mhd_field_address::set_mhd_field_addresses().