CALYPSO: const_1d_ele_connect_4_sph Module Reference
const_1d_ele_connect_4_sph Module Reference
Functions/Subroutines
subroutine s_const_1d_ele_connect_4_sph (iflag_shell_mode, m_folding, sph_rtp, s3d_ranks, stk_lc1d, sph_gl1d, stbl)
subroutine, private count_nod_ele_4_sph_radial (iflag_shell_mode, stk_lc1d, sph_gl1d, stbl)
subroutine, private count_nod_ele_4_sph_theta (iflag_shell_mode, stk_lc1d, stbl)
subroutine, private set_iele_4_sph_radial (stbl)
subroutine, private set_iele_4_sph_theta (stbl)
subroutine, private set_iele_4_sph_phi (stbl)
Function/Subroutine Documentation
count_nod_ele_4_sph_radial()
subroutine, private const_1d_ele_connect_4_sph::count_nod_ele_4_sph_radial (integer(kind = kint), intent(in) iflag_shell_mode, type(sph_1d_index_stack), intent(in) stk_lc1d, type(sph_1d_global_index), intent(in) sph_gl1d, type(comm_table_make_sph), intent(inout) stbl) private
Definition at line 79 of file const_1d_ele_connect_4_sph.f90.
References m_spheric_constants::iflag_mesh_w_center, and m_constants::ione.
Referenced by s_const_1d_ele_connect_4_sph().
count_nod_ele_4_sph_theta()
subroutine, private const_1d_ele_connect_4_sph::count_nod_ele_4_sph_theta (integer(kind = kint), intent(in) iflag_shell_mode, type(sph_1d_index_stack), intent(in) stk_lc1d, type(comm_table_make_sph), intent(inout) stbl) private
Definition at line 173 of file const_1d_ele_connect_4_sph.f90.
References m_spheric_constants::iflag_mesh_w_center, m_spheric_constants::iflag_mesh_w_pole, and m_constants::ione.
Referenced by s_const_1d_ele_connect_4_sph().
s_const_1d_ele_connect_4_sph()
subroutine const_1d_ele_connect_4_sph::s_const_1d_ele_connect_4_sph (integer(kind = kint), intent(in) iflag_shell_mode, integer(kind = kint), intent(in) m_folding, type(sph_rtp_grid), intent(in) sph_rtp, type(spheric_global_rank), intent(in) s3d_ranks, type(sph_1d_index_stack), intent(in) stk_lc1d, type(sph_1d_global_index), intent(in) sph_gl1d, type(comm_table_make_sph), intent(inout) stbl)
Definition at line 36 of file const_1d_ele_connect_4_sph.f90.
References t_sph_mesh_1d_connect::alloc_iele_sph_mesh(), t_sph_mesh_1d_connect::alloc_nnod_nele_sph_mesh(), t_sph_mesh_1d_connect::check_iele_4_sph_connects(), count_nod_ele_4_sph_radial(), count_nod_ele_4_sph_theta(), m_machine_parameter::iflag_debug, set_iele_4_sph_phi(), set_iele_4_sph_radial(), and set_iele_4_sph_theta().
Referenced by const_fem_mesh_sph_mhd::base_fem_mesh_sph_mhd().
set_iele_4_sph_phi()
subroutine, private const_1d_ele_connect_4_sph::set_iele_4_sph_phi (type(comm_table_make_sph), intent(inout) stbl) private
Definition at line 443 of file const_1d_ele_connect_4_sph.f90.
Referenced by s_const_1d_ele_connect_4_sph().
set_iele_4_sph_radial()
subroutine, private const_1d_ele_connect_4_sph::set_iele_4_sph_radial (type(comm_table_make_sph), intent(inout) stbl) private
Definition at line 304 of file const_1d_ele_connect_4_sph.f90.
Referenced by s_const_1d_ele_connect_4_sph().
set_iele_4_sph_theta()
subroutine, private const_1d_ele_connect_4_sph::set_iele_4_sph_theta (type(comm_table_make_sph), intent(inout) stbl) private
Definition at line 344 of file const_1d_ele_connect_4_sph.f90.
Referenced by s_const_1d_ele_connect_4_sph().