CALYPSO: set_field_comp_for_viz Module Reference
set_field_comp_for_viz Module Reference
Functions/Subroutines
subroutine check_field_4_viz (num_nod_phys, phys_nod_name, n_field_ctl, field_name, num_field, num_field_vis)
subroutine set_components_4_viz (num_nod_phys, phys_nod_name, n_field_ctl, field_name, comp_name, num_field, ifield, icomp, ncomp, ncomp_org, rst_name)
subroutine set_one_component_4_viz (num_nod_phys, phys_nod_name, field_name, comp_name, ifield, icomp, ncomp, ncomp_org, rst_name)
subroutine count_total_comps_4_viz (psf_fld)
Function/Subroutine Documentation
check_field_4_viz()
subroutine set_field_comp_for_viz::check_field_4_viz (integer(kind = kint), intent(in) num_nod_phys, character(len=kchara), dimension(num_nod_phys), intent(in) phys_nod_name, integer(kind = kint), intent(in) n_field_ctl, character(len=kchara), dimension(n_field_ctl), intent(in) field_name, integer(kind = kint), intent(inout) num_field, integer(kind = kint), intent(inout) num_field_vis)
Definition at line 29 of file set_field_comp_for_viz.f90.
Referenced by t_control_params_4_iso::count_control_4_field_on_iso(), and t_control_params_4_psf::count_control_4_field_on_psf().
count_total_comps_4_viz()
subroutine set_field_comp_for_viz::count_total_comps_4_viz (type(phys_data), intent(inout) psf_fld)
Definition at line 135 of file set_field_comp_for_viz.f90.
Referenced by set_psf_iso_control::set_iso_control(), and set_psf_iso_control::set_psf_control().
set_components_4_viz()
subroutine set_field_comp_for_viz::set_components_4_viz (integer(kind = kint), intent(in) num_nod_phys, character(len=kchara), dimension(num_nod_phys), intent(in) phys_nod_name, integer(kind = kint), intent(in) n_field_ctl, character(len=kchara), dimension(n_field_ctl), intent(in) field_name, character(len=kchara), dimension(n_field_ctl), intent(in) comp_name, integer(kind = kint), intent(in) num_field, integer(kind = kint), dimension(num_field), intent(inout) ifield, integer(kind = kint), dimension(num_field), intent(inout) icomp, integer(kind = kint), dimension(num_field), intent(inout) ncomp, integer(kind = kint), dimension(num_field), intent(inout) ncomp_org, character(len=kchara), dimension(num_field), intent(inout) rst_name)
Definition at line 57 of file set_field_comp_for_viz.f90.
References set_components_flags::s_set_components_flags().
Referenced by t_control_params_4_iso::set_control_4_field_on_iso(), and t_control_params_4_psf::set_control_4_field_on_psf().
set_one_component_4_viz()
subroutine set_field_comp_for_viz::set_one_component_4_viz (integer(kind = kint), intent(in) num_nod_phys, character(len=kchara), dimension(num_nod_phys), intent(in) phys_nod_name, character(len=kchara), intent(in) field_name, character(len=kchara), intent(in) comp_name, integer(kind = kint), intent(inout) ifield, integer(kind = kint), intent(inout) icomp, integer(kind = kint), intent(inout) ncomp, integer(kind = kint), intent(inout) ncomp_org, character(len=kchara), intent(inout) rst_name)
Definition at line 100 of file set_field_comp_for_viz.f90.
References set_components_flags::s_set_components_flags().
Referenced by t_control_params_4_iso::set_control_iso_def().