CALYPSO: set_fields_for_psf Module Reference
set_fields_for_psf Module Reference
Construct surface patch.
Functions/Subroutines
subroutine alloc_psf_field_data (num_psf, psf_mesh)
subroutine dealloc_psf_field_data (num_psf, psf_mesh)
subroutine set_field_4_psf (num_psf, edge, nod_fld, psf_def, psf_param, psf_list, psf_grp_list, psf_mesh)
subroutine set_field_4_iso (num_iso, edge, nod_fld, iso_param, iso_def, iso_list, iso_mesh)
subroutine, private set_field_on_psf (numnod, numedge, nnod_4_edge, ie_edge, nnod_patch, istack_n_smp, xyz_psf, rr_psf, ar_psf, ss_psf, as_psf, nfield_psf, max_ncomp_psf, ifield_psf, ncomp_psf, ncomp_org, icomp_psf, num_phys, ntot_phys, istack_ncomp, d_nod, dat_psf, dat_tmp, psf_list)
subroutine set_field_on_psf_grp (numnod, nnod_patch, istack_n_smp, xyz_psf, rr_psf, ar_psf, ss_psf, as_psf, nfield_psf, max_ncomp_psf, ifield_psf, ncomp_psf, ncomp_org, icomp_psf, num_phys, ntot_phys, istack_ncomp, d_nod, dat_psf, dat_tmp, psf_grp_list)
Detailed Description
Construct surface patch.
      subroutine alloc_psf_field_data(num_psf, psf_mesh)
      subroutine dealloc_psf_field_data(num_psf, psf_mesh)
      subroutine set_field_4_psf(num_psf, edge, nod_fld,              &
     &          psf_def, psf_param, psf_list, psf_grp_list, psf_mesh)
        type(edge_data), intent(in) :: edge
        type(phys_data), intent(in) :: nod_fld
        type(section_define), intent(in) :: psf_def(num_psf)
        type(psf_parameters), intent(in) :: psf_param(num_psf)
        type(sectioning_list), intent(in):: psf_list(num_psf)
        type(grp_section_list), intent(in) :: psf_grp_list(num_psf)
        type(psf_local_data), intent(inout) :: psf_mesh(num_psf)
      subroutine set_field_4_iso(num_iso, edge, nod_fld,              &
     &          iso_param, iso_def, iso_list, iso_mesh)
        type(edge_data), intent(in) :: edge
        type(phys_data), intent(in) :: nod_fld
        type(psf_parameters), intent(in) :: iso_param(num_iso)
        type(isosurface_define), intent(in) :: iso_def(num_iso)
        type(sectioning_list), intent(in):: iso_list(num_iso)
        type(psf_local_data), intent(inout) :: iso_mesh(num_iso)
Function/Subroutine Documentation
alloc_psf_field_data()
subroutine set_fields_for_psf::alloc_psf_field_data (integer(kind = kint), intent(in) num_psf, type(psf_local_data), dimension(num_psf), intent(inout) psf_mesh)
Definition at line 47 of file set_fields_for_psf.f90.
References t_psf_patch_data::alloc_dat_on_patch_psf().
Referenced by t_isosurface::isosurf_visualize(), and t_cross_section::sectioning_initialize().
dealloc_psf_field_data()
subroutine set_fields_for_psf::dealloc_psf_field_data (integer(kind = kint), intent(in) num_psf, type(psf_local_data), dimension(num_psf), intent(inout) psf_mesh)
Definition at line 67 of file set_fields_for_psf.f90.
References t_psf_patch_data::dealloc_dat_on_patch_psf().
Referenced by t_cross_section::dealloc_psf_field_type(), and t_isosurface::isosurf_visualize().
set_field_4_iso()
subroutine set_fields_for_psf::set_field_4_iso (integer(kind = kint), intent(in) num_iso, type(edge_data), intent(in) edge, type(phys_data), intent(in) nod_fld, type(psf_parameters), dimension(num_iso), intent(in) iso_param, type(isosurface_define), dimension(num_iso), intent(in) iso_def, type(sectioning_list), dimension(num_iso), intent(in) iso_list, type(psf_local_data), dimension(num_iso), intent(inout) iso_mesh)
Definition at line 141 of file set_fields_for_psf.f90.
References t_control_params_4_iso::iflag_constant_iso, set_nodal_field_for_psf::set_const_on_psf(), and set_field_on_psf().
Referenced by t_isosurface::isosurf_visualize().
set_field_4_psf()
subroutine set_fields_for_psf::set_field_4_psf (integer(kind = kint), intent(in) num_psf, type(edge_data), intent(in) edge, type(phys_data), intent(in) nod_fld, type(section_define), dimension(num_psf), intent(in) psf_def, type(psf_parameters), dimension(num_psf), intent(in) psf_param, type(sectioning_list), dimension(num_psf), intent(in) psf_list, type(grp_section_list), dimension(num_psf), intent(in) psf_grp_list, type(psf_local_data), dimension(num_psf), intent(inout) psf_mesh)
Definition at line 86 of file set_fields_for_psf.f90.
References set_field_on_psf(), and set_field_on_psf_grp().
Referenced by t_cross_section::sectioning_visualize().
set_field_on_psf()
subroutine, private set_fields_for_psf::set_field_on_psf (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) numedge, integer(kind = kint), intent(in) nnod_4_edge, integer(kind = kint), dimension(numedge,nnod_4_edge), intent(in) ie_edge, integer(kind = kint), intent(in) nnod_patch, integer(kind = kint), dimension(0:np_smp), intent(in) istack_n_smp, real(kind = kreal), dimension(nnod_patch,3), intent(in) xyz_psf, real(kind = kreal), dimension(nnod_patch), intent(in) rr_psf, real(kind = kreal), dimension(nnod_patch), intent(in) ar_psf, real(kind = kreal), dimension(nnod_patch), intent(in) ss_psf, real(kind = kreal), dimension(nnod_patch), intent(in) as_psf, integer(kind = kint), intent(in) nfield_psf, integer(kind = kint), intent(in) max_ncomp_psf, integer(kind = kint), dimension(nfield_psf), intent(in) ifield_psf, integer(kind = kint), dimension(nfield_psf), intent(in) ncomp_psf, integer(kind = kint), dimension(nfield_psf), intent(in) ncomp_org, integer(kind = kint), dimension(nfield_psf), intent(in) icomp_psf, integer(kind = kint), intent(in) num_phys, integer(kind = kint), intent(in) ntot_phys, integer(kind = kint), dimension(0:num_phys), intent(in) istack_ncomp, real(kind = kreal), dimension(numnod,ntot_phys), intent(in) d_nod, real(kind = kreal), dimension(nnod_patch,max_ncomp_psf), intent(inout) dat_psf, real(kind = kreal), dimension(nnod_patch,6), intent(inout) dat_tmp, type(sectioning_list), intent(in) psf_list) private
Definition at line 188 of file set_fields_for_psf.f90.
References convert_components_4_viz::convert_comps_4_viz(), and set_nodal_field_for_psf::set_field_on_psf_xyz().
Referenced by set_field_4_iso(), and set_field_4_psf().
set_field_on_psf_grp()
subroutine set_fields_for_psf::set_field_on_psf_grp (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) nnod_patch, integer(kind = kint), dimension(0:np_smp), intent(in) istack_n_smp, real(kind = kreal), dimension(nnod_patch,3), intent(in) xyz_psf, real(kind = kreal), dimension(nnod_patch), intent(in) rr_psf, real(kind = kreal), dimension(nnod_patch), intent(in) ar_psf, real(kind = kreal), dimension(nnod_patch), intent(in) ss_psf, real(kind = kreal), dimension(nnod_patch), intent(in) as_psf, integer(kind = kint), intent(in) nfield_psf, integer(kind = kint), intent(in) max_ncomp_psf, integer(kind = kint), dimension(nfield_psf), intent(in) ifield_psf, integer(kind = kint), dimension(nfield_psf), intent(in) ncomp_psf, integer(kind = kint), dimension(nfield_psf), intent(in) ncomp_org, integer(kind = kint), dimension(nfield_psf), intent(in) icomp_psf, integer(kind = kint), intent(in) num_phys, integer(kind = kint), intent(in) ntot_phys, integer(kind = kint), dimension(0:num_phys), intent(in) istack_ncomp, real(kind = kreal), dimension(numnod,ntot_phys), intent(in) d_nod, real(kind = kreal), dimension(nnod_patch,max_ncomp_psf), intent(inout) dat_psf, real(kind = kreal), dimension(nnod_patch,6), intent(inout) dat_tmp, type(grp_section_list), intent(in) psf_grp_list)
Definition at line 249 of file set_fields_for_psf.f90.
References convert_components_4_viz::convert_comps_4_viz(), and set_psf_nodes_4_by_surf_grp::set_field_on_psf_grp_xyz().
Referenced by set_field_4_psf().