CALYPSO: cal_diff_adv_src_explicit Module Reference
cal_diff_adv_src_explicit Module Reference
Evaluate time evolution explicitly.
Functions/Subroutines
subroutine scalar_diff_advect_adams (ist, ied, ipol_diffuse, ipol_advect, ipol_scalar, ipol_pre, dt, coef_exp, n_point, ntot_phys_rj, d_rj)
subroutine scalar_diff_advect_euler (ist, ied, ipol_diffuse, ipol_advect, ipol_scalar, dt, coef_exp, n_point, ntot_phys_rj, d_rj)
subroutine set_ini_adams_scalar (ist, ied, ipol_advect, ipol_pre, n_point, ntot_phys_rj, d_rj)
subroutine scalar_diff_adv_src_adams (ist, ied, ipol_diffuse, ipol_advect, ipol_source, ipol_scalar, ipol_pre, dt, coef_exp, coef_src, n_point, ntot_phys_rj, d_rj)
subroutine scalar_diff_adv_src_euler (ist, ied, ipol_diffuse, ipol_advect, ipol_source, ipol_scalar, dt, coef_exp, coef_src, n_point, ntot_phys_rj, d_rj)
subroutine set_ini_adams_scalar_w_src (ist, ied, ipol_advect, ipol_source, ipol_pre, coef_src, n_point, ntot_phys_rj, d_rj)
subroutine stable_scalar_diff_src (ist, ied, ipol_source, ipol_scalar, coef_src, n_point, ntot_phys_rj, d_rj)
subroutine stable_scalar_diffusion (ist, ied, ipol_scalar, n_point, ntot_phys_rj, d_rj)
subroutine center_scl_diff_adv_src_adams (inod_rj_center, ipol_diffuse, ipol_advect, ipol_source, ipol_scalar, ipol_pre, dt, coef_exp, coef_src, n_point, ntot_phys_rj, d_rj)
subroutine center_scl_diff_adv_src_euler (inod_rj_center, ipol_diffuse, ipol_advect, ipol_source, ipol_scalar, dt, coef_exp, coef_src, n_point, ntot_phys_rj, d_rj)
subroutine center_ini_adams_scalar_w_src (inod_rj_center, ipol_advect, ipol_source, ipol_pre, coef_src, n_point, ntot_phys_rj, d_rj)
Detailed Description
Evaluate time evolution explicitly.
      subroutine scalar_diff_advect_adams(ist, ied,                   &
     &          ipol_diffuse, ipol_advect, ipol_scalar, ipol_pre,     &
     &          dt, coef_exp, n_point, ntot_phys_rj, d_rj)
      subroutine scalar_diff_advect_euler                             &
     &         (ist, ied, ipol_diffuse, ipol_advect, ipol_scalar,     &
     &          dt, coef_exp, n_point, ntot_phys_rj, d_rj)
      subroutine set_ini_adams_scalar(ist, ied, ipol_advect, ipol_pre,&
     &          n_point, ntot_phys_rj, d_rj)
      subroutine scalar_diff_adv_src_adams(ist, ied, ipol_diffuse,    &
     &          ipol_advect, ipol_source, ipol_scalar, ipol_pre,      &
     &          dt, coef_exp, coef_src, n_point, ntot_phys_rj, d_rj)
      subroutine scalar_diff_adv_src_euler(ist, ied,                  &
     &          ipol_diffuse, ipol_advect, ipol_source, ipol_scalar,  &
     &          dt, coef_exp, coef_src, n_point, ntot_phys_rj, d_rj)
      subroutine set_ini_adams_scalar_w_src                           &
     &         (ist, ied, ipol_advect, ipol_source, ipol_pre,         &
     &          coef_src,  n_point, ntot_phys_rj, d_rj)
      subroutine stable_scalar_diff_src                               &
     &         (ist, ied, ipol_source, ipol_scalar, coef_src,         &
     &          n_point, ntot_phys_rj, d_rj)
      subroutine stable_scalar_diffusion                              &
     &         (ist, ied, ipol_scalar, n_point, ntot_phys_rj, d_rj)
      subroutine center_scl_diff_adv_src_adams(inod_rj_center,        &
     &          ipol_diffuse, ipol_advect, ipol_source,               &
     &          ipol_scalar, ipol_pre, dt, coef_exp, coef_src,        &
     &          n_point, ntot_phys_rj, d_rj)
      subroutine center_scl_diff_adv_src_euler(inod_rj_center,        &
     &          ipol_diffuse, ipol_advect, ipol_source, ipol_scalar,  &
     &          dt, coef_exp, coef_src, n_point, ntot_phys_rj, d_rj)
      subroutine center_ini_adams_scalar_w_src(inod_rj_center,        &
     &          ipol_advect, ipol_source, ipol_pre, coef_src,         &
     &          n_point, ntot_phys_rj, d_rj)
Parameters
kr_st Radial address for inner boundary
kr_ed Radial address for outer boundary
ipol_diffuse address for diffusion term
ipol_advect address for advection term
ipol_source address for source term
ipol_scalar address for scalar field to update
ipol_pre address for storeing previous evolution
coef_exp coeefient for expilict evolution for diffusion
coef_src coefficient for source term
Function/Subroutine Documentation
center_ini_adams_scalar_w_src()
subroutine cal_diff_adv_src_explicit::center_ini_adams_scalar_w_src (integer(kind = kint), intent(in) inod_rj_center, integer(kind = kint), intent(in) ipol_advect, integer(kind = kint), intent(in) ipol_source, integer(kind = kint), intent(in) ipol_pre, real(kind = kreal), intent(in) coef_src, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 346 of file cal_diff_adv_src_explicit.f90.
Referenced by select_diff_adv_source::sel_ini_adams_scalar_w_src().
center_scl_diff_adv_src_adams()
subroutine cal_diff_adv_src_explicit::center_scl_diff_adv_src_adams (integer(kind = kint), intent(in) inod_rj_center, integer(kind = kint), intent(in) ipol_diffuse, integer(kind = kint), intent(in) ipol_advect, integer(kind = kint), intent(in) ipol_source, integer(kind = kint), intent(in) ipol_scalar, integer(kind = kint), intent(in) ipol_pre, real(kind = kreal), intent(in) dt, real(kind = kreal), intent(in) coef_exp, real(kind = kreal), intent(in) coef_src, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 290 of file cal_diff_adv_src_explicit.f90.
References m_t_step_parameter::adam_0, and m_t_step_parameter::adam_1.
Referenced by select_diff_adv_source::sel_ctr_scl_diff_adv_src_adams().
center_scl_diff_adv_src_euler()
subroutine cal_diff_adv_src_explicit::center_scl_diff_adv_src_euler (integer(kind = kint), intent(in) inod_rj_center, integer(kind = kint), intent(in) ipol_diffuse, integer(kind = kint), intent(in) ipol_advect, integer(kind = kint), intent(in) ipol_source, integer(kind = kint), intent(in) ipol_scalar, real(kind = kreal), intent(in) dt, real(kind = kreal), intent(in) coef_exp, real(kind = kreal), intent(in) coef_src, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 321 of file cal_diff_adv_src_explicit.f90.
Referenced by select_diff_adv_source::sel_ctr_scl_diff_adv_src_euler().
scalar_diff_adv_src_adams()
subroutine cal_diff_adv_src_explicit::scalar_diff_adv_src_adams (integer(kind = kint), intent(in) ist, integer(kind = kint), intent(in) ied, integer(kind = kint), intent(in) ipol_diffuse, integer(kind = kint), intent(in) ipol_advect, integer(kind = kint), intent(in) ipol_source, integer(kind = kint), intent(in) ipol_scalar, integer(kind = kint), intent(in) ipol_pre, real(kind = kreal), intent(in) dt, real(kind = kreal), intent(in) coef_exp, real(kind = kreal), intent(in) coef_src, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 153 of file cal_diff_adv_src_explicit.f90.
References m_t_step_parameter::adam_0, and m_t_step_parameter::adam_1.
Referenced by select_diff_adv_source::sel_scalar_diff_adv_src_adams().
scalar_diff_adv_src_euler()
subroutine cal_diff_adv_src_explicit::scalar_diff_adv_src_euler (integer(kind = kint), intent(in) ist, integer(kind = kint), intent(in) ied, integer(kind = kint), intent(in) ipol_diffuse, integer(kind = kint), intent(in) ipol_advect, integer(kind = kint), intent(in) ipol_source, integer(kind = kint), intent(in) ipol_scalar, real(kind = kreal), intent(in) dt, real(kind = kreal), intent(in) coef_exp, real(kind = kreal), intent(in) coef_src, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 187 of file cal_diff_adv_src_explicit.f90.
Referenced by select_diff_adv_source::sel_scalar_diff_adv_src_euler().
scalar_diff_advect_adams()
subroutine cal_diff_adv_src_explicit::scalar_diff_advect_adams (integer(kind = kint), intent(in) ist, integer(kind = kint), intent(in) ied, integer(kind = kint), intent(in) ipol_diffuse, integer(kind = kint), intent(in) ipol_advect, integer(kind = kint), intent(in) ipol_scalar, integer(kind = kint), intent(in) ipol_pre, real(kind = kreal), intent(in) dt, real(kind = kreal), intent(in) coef_exp, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 71 of file cal_diff_adv_src_explicit.f90.
References m_t_step_parameter::adam_0, and m_t_step_parameter::adam_1.
Referenced by select_diff_adv_source::sel_scalar_diff_adv_src_adams().
scalar_diff_advect_euler()
subroutine cal_diff_adv_src_explicit::scalar_diff_advect_euler (integer(kind = kint), intent(in) ist, integer(kind = kint), intent(in) ied, integer(kind = kint), intent(in) ipol_diffuse, integer(kind = kint), intent(in) ipol_advect, integer(kind = kint), intent(in) ipol_scalar, real(kind = kreal), intent(in) dt, real(kind = kreal), intent(in) coef_exp, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 102 of file cal_diff_adv_src_explicit.f90.
Referenced by select_diff_adv_source::sel_scalar_diff_adv_src_euler().
set_ini_adams_scalar()
subroutine cal_diff_adv_src_explicit::set_ini_adams_scalar (integer(kind = kint), intent(in) ist, integer(kind = kint), intent(in) ied, integer(kind = kint), intent(in) ipol_advect, integer(kind = kint), intent(in) ipol_pre, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 130 of file cal_diff_adv_src_explicit.f90.
Referenced by select_diff_adv_source::sel_ini_adams_scalar_w_src().
set_ini_adams_scalar_w_src()
subroutine cal_diff_adv_src_explicit::set_ini_adams_scalar_w_src (integer(kind = kint), intent(in) ist, integer(kind = kint), intent(in) ied, integer(kind = kint), intent(in) ipol_advect, integer(kind = kint), intent(in) ipol_source, integer(kind = kint), intent(in) ipol_pre, real(kind = kreal), intent(in) coef_src, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 217 of file cal_diff_adv_src_explicit.f90.
Referenced by select_diff_adv_source::sel_ini_adams_scalar_w_src().
stable_scalar_diff_src()
subroutine cal_diff_adv_src_explicit::stable_scalar_diff_src (integer(kind = kint), intent(in) ist, integer(kind = kint), intent(in) ied, integer(kind = kint), intent(in) ipol_source, integer(kind = kint), intent(in) ipol_scalar, real(kind = kreal), intent(in) coef_src, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 243 of file cal_diff_adv_src_explicit.f90.
Referenced by select_diff_adv_source::sel_scalar_diff_adv_src_euler().
stable_scalar_diffusion()
subroutine cal_diff_adv_src_explicit::stable_scalar_diffusion (integer(kind = kint), intent(in) ist, integer(kind = kint), intent(in) ied, integer(kind = kint), intent(in) ipol_scalar, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 267 of file cal_diff_adv_src_explicit.f90.
References m_constants::zero.
Referenced by select_diff_adv_source::sel_scalar_diff_adv_src_euler().