CALYPSO: m_elapsed_labels_4_mhd Module Reference
m_elapsed_labels_4_mhd Module Reference
Labels for elapsed time monitor.
Functions/Subroutines
subroutine elapsed_label_4_mhd
subroutine elapsed_label_4_sph_mhd
subroutine elapsed_label_4_fem_mhd
subroutine elapsed_label_4_sgs_model
subroutine reset_elapse_after_init_sph_mhd
subroutine reset_elapse_after_init_sgs
Variables
logical, save iflag_mhd_time = .FALSE.
integer(kind=kint), save ist_elapsed_mhd = 0
integer(kind=kint), save ied_elapsed_mhd = 0
logical, save iflag_smhd_time = .FALSE.
integer(kind=kint), save ist_elapsed_smhd = 0
integer(kind=kint), save ied_elapsed_smhd = 0
logical, save iflag_fmhd_time = .FALSE.
integer(kind=kint), save ist_elapsed_fmhd = 0
integer(kind=kint), save ied_elapsed_fmhd = 0
logical, save iflag_sgs_time = .FALSE.
integer(kind=kint), save ist_elapsed_sgs = 0
integer(kind=kint), save ied_elapsed_sgs = 0
Detailed Description
Labels for elapsed time monitor.
      subroutine elapsed_label_4_MHD
      subroutine elapsed_label_4_SPH_MHD
      subroutine elapsed_label_4_FEM_MHD
      subroutine elapsed_label_4_SGS_model
      subroutine reset_elapse_after_init_SPH_MHD
      subroutine reset_elapse_after_init_SGS
Function/Subroutine Documentation
elapsed_label_4_fem_mhd()
subroutine m_elapsed_labels_4_mhd::elapsed_label_4_fem_mhd
Definition at line 97 of file m_elapsed_labels_4_MHD.f90.
References m_work_time::append_elapsed_times(), m_work_time::elps1, ied_elapsed_fmhd, iflag_fmhd_time, and ist_elapsed_fmhd.
elapsed_label_4_mhd()
subroutine m_elapsed_labels_4_mhd::elapsed_label_4_mhd
Definition at line 49 of file m_elapsed_labels_4_MHD.f90.
References m_work_time::append_elapsed_times(), m_work_time::elps1, ied_elapsed_mhd, iflag_mhd_time, and ist_elapsed_mhd.
Referenced by init_sph_mhd_elapsed_label::set_sph_mhd_elapsed_label().
elapsed_label_4_sgs_model()
subroutine m_elapsed_labels_4_mhd::elapsed_label_4_sgs_model
Definition at line 112 of file m_elapsed_labels_4_MHD.f90.
References m_work_time::append_elapsed_times(), m_work_time::elps1, ied_elapsed_sgs, iflag_sgs_time, and ist_elapsed_sgs.
Referenced by init_sph_mhd_elapsed_label::set_sph_mhd_elapsed_label().
elapsed_label_4_sph_mhd()
subroutine m_elapsed_labels_4_mhd::elapsed_label_4_sph_mhd
Definition at line 69 of file m_elapsed_labels_4_MHD.f90.
References m_work_time::append_elapsed_times(), m_work_time::elps1, ied_elapsed_smhd, iflag_smhd_time, and ist_elapsed_smhd.
Referenced by init_sph_mhd_elapsed_label::set_sph_mhd_elapsed_label().
reset_elapse_after_init_sgs()
subroutine m_elapsed_labels_4_mhd::reset_elapse_after_init_sgs
Definition at line 141 of file m_elapsed_labels_4_MHD.f90.
References ied_elapsed_sgs, iflag_sgs_time, ist_elapsed_sgs, and m_work_time::reset_elapsed_times().
Referenced by init_sph_mhd_elapsed_label::reset_elapse_4_init_sph_mhd().
reset_elapse_after_init_sph_mhd()
subroutine m_elapsed_labels_4_mhd::reset_elapse_after_init_sph_mhd
Definition at line 131 of file m_elapsed_labels_4_MHD.f90.
References ied_elapsed_smhd, iflag_smhd_time, ist_elapsed_smhd, and m_work_time::reset_elapsed_times().
Referenced by init_sph_mhd_elapsed_label::reset_elapse_4_init_sph_mhd().
Variable Documentation
ied_elapsed_fmhd
integer(kind = kint), save m_elapsed_labels_4_mhd::ied_elapsed_fmhd = 0
Definition at line 37 of file m_elapsed_labels_4_MHD.f90.
Referenced by elapsed_label_4_fem_mhd().
ied_elapsed_mhd
integer(kind = kint), save m_elapsed_labels_4_mhd::ied_elapsed_mhd = 0
Definition at line 29 of file m_elapsed_labels_4_MHD.f90.
Referenced by elapsed_label_4_mhd().
ied_elapsed_sgs
integer(kind = kint), save m_elapsed_labels_4_mhd::ied_elapsed_sgs = 0
Definition at line 41 of file m_elapsed_labels_4_MHD.f90.
Referenced by elapsed_label_4_sgs_model(), and reset_elapse_after_init_sgs().
ied_elapsed_smhd
integer(kind = kint), save m_elapsed_labels_4_mhd::ied_elapsed_smhd = 0
Definition at line 33 of file m_elapsed_labels_4_MHD.f90.
Referenced by elapsed_label_4_sph_mhd(), and reset_elapse_after_init_sph_mhd().
iflag_fmhd_time
logical, save m_elapsed_labels_4_mhd::iflag_fmhd_time = .FALSE.
Definition at line 35 of file m_elapsed_labels_4_MHD.f90.
Referenced by elapsed_label_4_fem_mhd().
iflag_mhd_time
logical, save m_elapsed_labels_4_mhd::iflag_mhd_time = .FALSE.
Definition at line 27 of file m_elapsed_labels_4_MHD.f90.
Referenced by elapsed_label_4_mhd(), analyzer_sph_dynamobench::evolution_sph_dynamobench(), analyzer_sph_mhd_w_psf::evolution_sph_mhd_w_psf(), analyzer_sph_snap_w_psf::evolution_sph_snap_w_psf(), fem_analyzer_sph_mhd::fem_analyze_sph_mhd(), fem_analyzer_sph_mhd::fem_initialize_sph_mhd(), sph_analyzer_add_initial::initialize_add_sph_initial(), sph_analyzer_const_initial::initialize_const_sph_initial(), analyzer_sph_dynamobench::initialize_sph_dynamobench(), analyzer_sph_mhd_w_psf::initialize_sph_mhd_w_psf(), analyzer_sph_snap_w_psf::initialize_sph_snap_w_psf(), sph_analyzer_d_bench::sph_analyze_dbench(), sph_analyzer_mhd::sph_analyze_mhd(), sph_analyzer_snap_w_psf::sph_analyze_snap_psf(), and sph_analyzer_mhd::sph_initialize_mhd().
iflag_sgs_time
logical, save m_elapsed_labels_4_mhd::iflag_sgs_time = .FALSE.
Definition at line 39 of file m_elapsed_labels_4_MHD.f90.
Referenced by elapsed_label_4_sgs_model(), and reset_elapse_after_init_sgs().
iflag_smhd_time
logical, save m_elapsed_labels_4_mhd::iflag_smhd_time = .FALSE.
Definition at line 31 of file m_elapsed_labels_4_MHD.f90.
Referenced by elapsed_label_4_sph_mhd(), cal_nonlinear::nonlinear(), cal_nonlinear::nonlinear_by_pseudo_sph(), reset_elapse_after_init_sph_mhd(), sph_analyzer_d_bench::sph_analyze_dbench(), sph_analyzer_mhd::sph_analyze_mhd(), sph_analyzer_snap_w_psf::sph_analyze_snap_psf(), sph_trans_w_coriols::sph_b_trans_licv(), sph_trans_w_coriols::sph_b_trans_w_coriolis(), sph_trans_w_coriols::sph_f_trans_licv(), and sph_trans_w_coriols::sph_f_trans_w_coriolis().
ist_elapsed_fmhd
integer(kind = kint), save m_elapsed_labels_4_mhd::ist_elapsed_fmhd = 0
Definition at line 36 of file m_elapsed_labels_4_MHD.f90.
Referenced by elapsed_label_4_fem_mhd().
ist_elapsed_mhd
integer(kind = kint), save m_elapsed_labels_4_mhd::ist_elapsed_mhd = 0
Definition at line 28 of file m_elapsed_labels_4_MHD.f90.
Referenced by elapsed_label_4_mhd(), analyzer_sph_dynamobench::evolution_sph_dynamobench(), analyzer_sph_mhd_w_psf::evolution_sph_mhd_w_psf(), analyzer_sph_snap_w_psf::evolution_sph_snap_w_psf(), fem_analyzer_sph_mhd::fem_analyze_sph_mhd(), fem_analyzer_sph_mhd::fem_initialize_sph_mhd(), sph_analyzer_add_initial::initialize_add_sph_initial(), sph_analyzer_const_initial::initialize_const_sph_initial(), analyzer_sph_dynamobench::initialize_sph_dynamobench(), analyzer_sph_mhd_w_psf::initialize_sph_mhd_w_psf(), analyzer_sph_snap_w_psf::initialize_sph_snap_w_psf(), sph_analyzer_d_bench::sph_analyze_dbench(), sph_analyzer_mhd::sph_analyze_mhd(), sph_analyzer_snap_w_psf::sph_analyze_snap_psf(), and sph_analyzer_mhd::sph_initialize_mhd().
ist_elapsed_sgs
integer(kind = kint), save m_elapsed_labels_4_mhd::ist_elapsed_sgs = 0
Definition at line 40 of file m_elapsed_labels_4_MHD.f90.
Referenced by elapsed_label_4_sgs_model(), and reset_elapse_after_init_sgs().
ist_elapsed_smhd
integer(kind = kint), save m_elapsed_labels_4_mhd::ist_elapsed_smhd = 0
Definition at line 32 of file m_elapsed_labels_4_MHD.f90.
Referenced by elapsed_label_4_sph_mhd(), cal_nonlinear::nonlinear(), cal_nonlinear::nonlinear_by_pseudo_sph(), reset_elapse_after_init_sph_mhd(), sph_analyzer_d_bench::sph_analyze_dbench(), sph_analyzer_mhd::sph_analyze_mhd(), sph_analyzer_snap_w_psf::sph_analyze_snap_psf(), sph_trans_w_coriols::sph_b_trans_licv(), sph_trans_w_coriols::sph_b_trans_w_coriolis(), sph_trans_w_coriols::sph_f_trans_licv(), and sph_trans_w_coriols::sph_f_trans_w_coriolis().