CALYPSO: t_sph_domain_fftpack5 Module Reference
t_sph_domain_fftpack5 Module Reference
Fourier transform using FFTPACK5.
Data Types
type work_for_domain_fftpack
Structure to use ISPACK.
Functions/Subroutines
subroutine init_sph_domain_fftpack5 (sph_rtp, comm_rtp, fftpack_d)
subroutine finalize_sph_domain_fftpack5 (fftpack_d)
subroutine verify_sph_domain_fftpack5 (sph_rtp, comm_rtp, fftpack_d)
subroutine, private alloc_work_domain_fftpack (Ncomp, Nfft, fftpack_d)
subroutine, private alloc_const_domain_fftpack (nfft, fftpack_d)
subroutine, private dealloc_work_domain_fftpack (fftpack_d)
subroutine, private dealloc_const_domain_fftpack (fftpack_d)
Detailed Description
Fourier transform using FFTPACK5.
  ---------------------------------------------------------------------
      subroutine init_sph_domain_FFTPACK5                             &
     &         (sph_rtp, comm_rtp, fftpack_d)
      subroutine finalize_sph_domain_FFTPACK5(fftpack_d)
      subroutine verify_sph_domain_FFTPACK5                           &
     &         (sph_rtp, comm_rtp, fftpack_d)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_comm_tbl), intent(in) :: comm_rtp
 ------------------------------------------------------------------
   wrapper subroutine for initierize FFT
 ------------------------------------------------------------------
      subroutine prt_domain_RFFTMF_to_send(sph_rtp, comm_rtp,         &
     &          ncomp_fwd, n_WS, X_rtp, WS, fftpack_d)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_comm_tbl), intent(in) :: comm_rtp
 ------------------------------------------------------------------
 wrapper subroutine for forward Fourier transform by FFTPACK5
   a_{k} = \frac{2}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
          *  \cos (\frac{2\pi j k}{Nfft})
   b_{k} = \frac{2}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
          *  \cos (\frac{2\pi j k}{Nfft})
   a_{0} = \frac{1}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
    K = Nfft/2....
   a_{k} = \frac{1}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
          * \cos (\frac{2\pi j k}{Nfft})
 ------------------------------------------------------------------
      subroutine prt_domain_RFFTMB_from_recv(sph_rtp, comm_rtp,       &
     &          ncomp_bwd, n_WR, WR, X_rtp, fftpack_d)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_comm_tbl), intent(in) :: comm_rtp
 ------------------------------------------------------------------
 wrapper subroutine for backward Fourier transform by FFTPACK5
   x_{k} = a_{0} + (-1)^{j} a_{Nfft/2} + sum_{k=1}^{Nfft/2-1}
          (a_{k} \cos(2\pijk/Nfft) + b_{k} \sin(2\pijk/Nfft))
 ------------------------------------------------------------------
       i = 1:     a_{0}
       i = 2:     a_{Nfft/2}
       i = 3:     a_{1}
       i = 4:     b_{1}
       ...
       i = 2*k+1: a_{k}
       i = 2*k+2: b_{k}
       ...
       i = Nfft-1:   a_{Nfft/2-1}
       i = Nfft:     b_{Nfft/2-1}
 ------------------------------------------------------------------
Parameters
Nsmp Number of SMP processors
Nstacksmp(0:Nsmp) End number for each SMP process
M Number of components for Fourier transforms
Nfft Data length for eadh FFT
X(M,Nfft) Data for Fourier transform
Function/Subroutine Documentation
alloc_const_domain_fftpack()
subroutine, private t_sph_domain_fftpack5::alloc_const_domain_fftpack (integer(kind = kint), intent(in) nfft, type(work_for_domain_fftpack), intent(inout) fftpack_d) private
Definition at line 209 of file t_sph_domain_FFTPACK5.f90.
References m_constants::ifour, and m_constants::two.
Referenced by init_sph_domain_fftpack5(), and verify_sph_domain_fftpack5().
alloc_work_domain_fftpack()
subroutine, private t_sph_domain_fftpack5::alloc_work_domain_fftpack (integer(kind = kint), intent(in) Ncomp, integer(kind = kint), intent(in) Nfft, type(work_for_domain_fftpack), intent(inout) fftpack_d) private
Definition at line 195 of file t_sph_domain_FFTPACK5.f90.
Referenced by init_sph_domain_fftpack5(), and verify_sph_domain_fftpack5().
dealloc_const_domain_fftpack()
subroutine, private t_sph_domain_fftpack5::dealloc_const_domain_fftpack (type(work_for_domain_fftpack), intent(inout) fftpack_d) private
Definition at line 238 of file t_sph_domain_FFTPACK5.f90.
Referenced by finalize_sph_domain_fftpack5(), and verify_sph_domain_fftpack5().
dealloc_work_domain_fftpack()
subroutine, private t_sph_domain_fftpack5::dealloc_work_domain_fftpack (type(work_for_domain_fftpack), intent(inout) fftpack_d) private
Definition at line 227 of file t_sph_domain_FFTPACK5.f90.
Referenced by finalize_sph_domain_fftpack5(), and verify_sph_domain_fftpack5().
finalize_sph_domain_fftpack5()
subroutine t_sph_domain_fftpack5::finalize_sph_domain_fftpack5 (type(work_for_domain_fftpack), intent(inout) fftpack_d)
Definition at line 141 of file t_sph_domain_FFTPACK5.f90.
References t_sph_comm_table_from_fft::dealloc_comm_table_sph_fft(), dealloc_const_domain_fftpack(), and dealloc_work_domain_fftpack().
Referenced by t_sph_fft_selector::finalize_sph_fft_select().
init_sph_domain_fftpack5()
subroutine t_sph_domain_fftpack5::init_sph_domain_fftpack5 (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, type(work_for_domain_fftpack), intent(inout) fftpack_d)
Definition at line 118 of file t_sph_domain_FFTPACK5.f90.
References alloc_const_domain_fftpack(), alloc_work_domain_fftpack(), m_machine_parameter::np_smp, and rfftmi().
Referenced by sph_prt_domain_fftpack5::init_prt_domain_fftpack5(), and sph_rtp_domain_fftpack5::init_rtp_domain_fftpack5().
verify_sph_domain_fftpack5()
subroutine t_sph_domain_fftpack5::verify_sph_domain_fftpack5 (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, type(work_for_domain_fftpack), intent(inout) fftpack_d)
Definition at line 154 of file t_sph_domain_FFTPACK5.f90.
References alloc_const_domain_fftpack(), alloc_work_domain_fftpack(), dealloc_const_domain_fftpack(), dealloc_work_domain_fftpack(), m_machine_parameter::np_smp, and rfftmi().
Referenced by sph_prt_domain_fftpack5::verify_prt_domain_fftpack5(), and sph_rtp_domain_fftpack5::verify_rtp_domain_fftpack5().