CALYPSO: t_control_array_integer Module Reference
t_control_array_integer Module Reference
Data Types
type ctl_array_int
Structure for integer control array.
type read_integer_item
structure of control integer item
Functions/Subroutines
subroutine read_integer_ctl_type (c_buf, label, int_item)
subroutine write_integer_ctl_type (id_file, level, maxlen, label, int_item)
subroutine copy_integer_ctl (org_i1, new_i1)
subroutine alloc_control_array_int (array_int)
subroutine dealloc_control_array_int (array_int)
subroutine read_control_array_i1 (id_control, label, array_int, c_buf)
subroutine write_control_array_i1 (id_control, level, label, array_int)
subroutine append_control_array_int (read_i1, array_i1)
subroutine copy_control_array_int (num_copy, org_i1, tgt_i1)
subroutine append_control_item_int (read_i1, array_i1)
Function/Subroutine Documentation
alloc_control_array_int()
subroutine t_control_array_integer::alloc_control_array_int (type(ctl_array_int), intent(inout) array_int)
Definition at line 128 of file t_control_array_integer.f90.
Referenced by append_control_array_int(), bcast_control_arrays::bcast_ctl_array_i1(), and read_control_array_i1().
append_control_array_int()
subroutine t_control_array_integer::append_control_array_int (type(read_integer_item), intent(inout) read_i1, type(ctl_array_int), intent(inout) array_i1)
Definition at line 220 of file t_control_array_integer.f90.
References alloc_control_array_int(), append_control_item_int(), copy_control_array_int(), and dealloc_control_array_int().
Referenced by read_control_array_i1().
append_control_item_int()
subroutine t_control_array_integer::append_control_item_int (type(read_integer_item), intent(in) read_i1, type(ctl_array_int), intent(inout) array_i1)
Definition at line 260 of file t_control_array_integer.f90.
Referenced by append_control_array_int().
copy_control_array_int()
subroutine t_control_array_integer::copy_control_array_int (integer(kind = kint), intent(in) num_copy, type(ctl_array_int), intent(in) org_i1, type(ctl_array_int), intent(inout) tgt_i1)
Definition at line 245 of file t_control_array_integer.f90.
Referenced by append_control_array_int().
copy_integer_ctl()
subroutine t_control_array_integer::copy_integer_ctl (type(read_integer_item), intent(in) org_i1, type(read_integer_item), intent(inout) new_i1)
Definition at line 115 of file t_control_array_integer.f90.
Referenced by t_control_data_surfacings::section_step_ctls_to_time_ctl().
dealloc_control_array_int()
subroutine t_control_array_integer::dealloc_control_array_int (type(ctl_array_int), intent(inout) array_int)
Definition at line 142 of file t_control_array_integer.f90.
Referenced by append_control_array_int(), t_ctl_data_pick_sph_spectr::dealloc_gauss_spectr_control(), t_ctl_data_sph_vol_spectr::dealloc_num_spec_layer_ctl(), and t_ctl_data_pick_sph_spectr::dealloc_pick_spectr_control().
read_control_array_i1()
subroutine t_control_array_integer::read_control_array_i1 (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) label, type(ctl_array_int), intent(inout) array_int, type(buffer_for_control), intent(inout) c_buf)
Definition at line 156 of file t_control_array_integer.f90.
References alloc_control_array_int(), append_control_array_int(), t_read_control_elements::check_array_flag(), t_read_control_elements::check_end_array_flag(), t_read_control_elements::load_one_line_from_control(), and read_integer_ctl_type().
Referenced by t_ctl_data_pick_sph_spectr::read_gauss_spectr_ctl(), t_ctl_data_sph_vol_spectr::read_layerd_spectr_ctl(), and t_ctl_data_pick_sph_spectr::read_pickup_spectr_ctl().
read_integer_ctl_type()
subroutine t_control_array_integer::read_integer_ctl_type (type(buffer_for_control), intent(in) c_buf, character(len=kchara), intent(in) label, type(read_integer_item), intent(inout) int_item)
Definition at line 73 of file t_control_array_integer.f90.
References m_machine_parameter::iflag_debug.
Referenced by read_control_array_i1(), t_ctl_data_4_platforms::read_control_platforms(), t_ctl_data_4_sphere_model::read_control_shell_define(), t_ctl_data_4_divide_sphere::read_control_shell_domain(), t_ctl_data_4_time_steps::read_control_time_step_data(), t_ctl_data_crust_filter::read_crustal_filtering_ctl(), t_ctl_data_4_fem_mesh::read_fem_mesh_control(), t_mid_equator_control::read_mid_eq_monitor_ctl(), t_control_data_surfacings::read_surfacing_controls(), and t_ctl_data_mhd_evo_scheme::read_time_loop_ctl().
write_control_array_i1()
subroutine t_control_array_integer::write_control_array_i1 (integer(kind = kint), intent(in) id_control, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, type(ctl_array_int), intent(in) array_int)
Definition at line 190 of file t_control_array_integer.f90.
References write_control_elements::write_array_flag_for_ctl(), write_control_elements::write_end_array_flag_for_ctl(), and write_control_elements::write_integer_ctl_item().
write_integer_ctl_type()
subroutine t_control_array_integer::write_integer_ctl_type (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, integer(kind = kint), intent(in) maxlen, character(len=kchara), intent(in) label, type(read_integer_item), intent(in) int_item)
Definition at line 95 of file t_control_array_integer.f90.
References write_control_elements::write_integer_ctl_item().
Referenced by t_ctl_data_4_platforms::write_control_platforms(), t_ctl_data_4_divide_sphere::write_control_shell_domain(), t_ctl_data_4_time_steps::write_control_time_step_data(), and t_ctl_data_4_fem_mesh::write_fem_mesh_control().