CALYPSO: t_buffer_4_gzip Module Reference
t_buffer_4_gzip Module Reference
Data Types
type buffer_4_gzip
Structure of buffer for zlib.
Functions/Subroutines
subroutine alloc_zip_buffer (zbuf)
subroutine alloc_textbuffer_for_zlib (len_buf, zbuf)
subroutine alloc_fixbuffer_for_zlib (zbuf)
subroutine dealloc_zip_buffer (zbuf)
subroutine dealloc_textbuffer_for_zlib (zbuf)
subroutine dealloc_fixbuffer_for_zlib (zbuf)
subroutine link_pointer_for_zlib_buffer (len_gzipbuf, gzipbuf, len_buf, textbuf, zbuf)
subroutine unlink_pointer_for_zlib_buffer (zbuf)
subroutine link_compressed_buffer (len_gzipbuf, gzipbuf, zbuf)
subroutine link_real_buffer_for_zlib (num, data, zbuf)
subroutine link_int8_buffer_for_zlib (num, int8_dat, zbuf)
subroutine link_int4_buffer_for_zlib (num, int4_dat, zbuf)
subroutine link_text_buffer_for_zlib (len_buf, textbuf, zbuf)
subroutine unlink_compressed_buffer (zbuf)
subroutine unlink_real_buffer_for_zlib (zbuf)
subroutine unlink_int8_buffer_for_zlib (zbuf)
subroutine unlink_int4_buffer_for_zlib (zbuf)
subroutine unlink_text_buffer_for_zlib (zbuf)
Variables
integer(kind=4), parameter, private nbuf = 65535
lengh of fixed text buffer
Function/Subroutine Documentation
alloc_fixbuffer_for_zlib()
subroutine t_buffer_4_gzip::alloc_fixbuffer_for_zlib (type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 117 of file t_buffer_4_gzip.f90.
Referenced by skip_gz_comment::open_ad_gzfile_a(), skip_gz_comment::open_rd_gzfile_a(), and skip_gz_comment::open_wt_gzfile_a().
alloc_textbuffer_for_zlib()
subroutine t_buffer_4_gzip::alloc_textbuffer_for_zlib (integer, intent(in) len_buf, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 106 of file t_buffer_4_gzip.f90.
Referenced by zlib_cvt_ascii_ele_connect::infleate_1d_global_address(), zlib_convert_text::infleate_1word(), zlib_cvt_ascii_comm_tbl::infleate_comm_table(), zlib_cvt_ascii_ele_connect::infleate_ele_connect(), zlib_cvt_ascii_ele_connect::infleate_ele_int_list(), zlib_cvt_ascii_comm_tbl::infleate_element_type(), zlib_convert_ascii_vector::infleate_node_position(), zlib_convert_text::infleate_skip_header(), and zlib_convert_ascii_vector::infleate_vector_txt().
alloc_zip_buffer()
subroutine t_buffer_4_gzip::alloc_zip_buffer (type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 96 of file t_buffer_4_gzip.f90.
Referenced by data_convert_by_zlib::defleate_1d_character_b(), zlib_cvt_ascii_ele_connect::defleate_1d_global_address(), data_convert_by_zlib::defleate_1d_vector_b(), zlib_convert_text::defleate_characters(), zlib_cvt_ascii_comm_tbl::defleate_comm_table(), zlib_cvt_ascii_ele_connect::defleate_ele_connect(), zlib_cvt_ascii_ele_connect::defleate_ele_int_list(), zlib_cvt_ascii_comm_tbl::defleate_element_type(), data_convert_by_zlib::defleate_int8_vector_b(), zlib_convert_ascii_vector::defleate_node_position(), zlib_cvt_ucd_data::defleate_ucd_connect(), zlib_cvt_ucd_data::defleate_ucd_vector(), zlib_convert_ascii_vector::defleate_vector_txt(), zlib_cvt_vtk_data::defleate_vtk_celltype(), zlib_cvt_vtk_data::defleate_vtk_connect(), zlib_cvt_vtk_data::defleate_vtk_scalar(), zlib_cvt_vtk_data::defleate_vtk_tensor(), zlib_cvt_vtk_data::defleate_vtk_vector(), gz_mpi_sph_gl_1d_idx_io::gz_mpi_read_1d_gl_address(), gz_mpi_binary_data_io::gz_mpi_read_1d_vector_b(), gz_mpi_binary_head_io::gz_mpi_read_byte_check(), gz_mpi_ascii_data_io::gz_mpi_read_characters(), gz_mpi_ascii_data_io::gz_mpi_read_charahead(), gz_mpi_domain_data_io::gz_mpi_read_comm_table(), gz_mpi_integer_list_io::gz_mpi_read_ele_connect(), gz_mpi_integer_list_io::gz_mpi_read_element_type(), gz_mpi_binary_data_io::gz_mpi_read_int8_vector_b(), gz_mpi_integer_list_io::gz_mpi_read_int_list(), gz_mpi_binary_head_io::gz_mpi_read_mul_charahead_b(), gz_mpi_binary_head_io::gz_mpi_read_mul_int8head_b(), gz_mpi_binary_head_io::gz_mpi_read_mul_realhead_b(), gz_mpi_position_io::gz_mpi_read_node_position(), gz_mpi_vectors_io::gz_mpi_read_vector(), gz_mpi_ascii_data_io::gz_mpi_skip_header(), gz_mpi_binary_head_io::gz_mpi_write_byte_flag(), gz_field_data_mpi_io::gz_read_each_field_mpi(), gz_field_data_mpi_io::gz_read_fld_1word_mpi(), and gz_field_data_mpi_io::gz_read_fld_charhead_mpi().
dealloc_fixbuffer_for_zlib()
subroutine t_buffer_4_gzip::dealloc_fixbuffer_for_zlib (type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 147 of file t_buffer_4_gzip.f90.
Referenced by skip_gz_comment::close_gzfile_a().
dealloc_textbuffer_for_zlib()
subroutine t_buffer_4_gzip::dealloc_textbuffer_for_zlib (type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 137 of file t_buffer_4_gzip.f90.
Referenced by zlib_cvt_ascii_ele_connect::infleate_1d_global_address(), zlib_convert_text::infleate_1word(), zlib_cvt_ascii_comm_tbl::infleate_comm_table(), zlib_cvt_ascii_ele_connect::infleate_ele_connect(), zlib_cvt_ascii_ele_connect::infleate_ele_int_list(), zlib_cvt_ascii_comm_tbl::infleate_element_type(), zlib_convert_ascii_vector::infleate_node_position(), zlib_convert_text::infleate_skip_header(), and zlib_convert_ascii_vector::infleate_vector_txt().
dealloc_zip_buffer()
subroutine t_buffer_4_gzip::dealloc_zip_buffer (type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 127 of file t_buffer_4_gzip.f90.
Referenced by gz_mpi_binary_data_io::gz_mpi_read_1d_vector_b(), gz_mpi_binary_head_io::gz_mpi_read_byte_check(), gz_mpi_binary_data_io::gz_mpi_read_int8_vector_b(), gz_mpi_binary_head_io::gz_mpi_read_mul_charahead_b(), gz_mpi_binary_head_io::gz_mpi_read_mul_int8head_b(), gz_mpi_binary_head_io::gz_mpi_read_mul_realhead_b(), gz_mpi_sph_gl_1d_idx_io::gz_mpi_write_1d_gl_address(), gz_mpi_binary_data_io::gz_mpi_write_1d_vector_b(), gz_mpi_binary_head_io::gz_mpi_write_byte_flag(), gz_mpi_ascii_data_io::gz_mpi_write_characters(), gz_mpi_ascii_data_io::gz_mpi_write_charahead(), gz_mpi_domain_data_io::gz_mpi_write_comm_table(), gz_mpi_integer_list_io::gz_mpi_write_ele_connect(), gz_mpi_integer_list_io::gz_mpi_write_element_type(), gz_mpi_binary_data_io::gz_mpi_write_int8_vector_b(), gz_mpi_integer_list_io::gz_mpi_write_int_list(), gz_mpi_binary_head_io::gz_mpi_write_mul_charahead_b(), gz_mpi_binary_head_io::gz_mpi_write_mul_int8head_b(), gz_mpi_binary_head_io::gz_mpi_write_mul_realhead_b(), gz_mpi_position_io::gz_mpi_write_node_position(), gz_mpi_vectors_io::gz_mpi_write_vector(), gz_mpi_viewer_mesh_io::gz_mpi_write_viewer_grp_item(), gz_mpi_viewer_mesh_io::gz_mpi_write_viewer_position(), gz_field_data_mpi_io::gz_write_fld_header_mpi(), gz_field_data_mpi_io::gz_write_fld_vecotr_mpi(), gz_ucd_file_mpi_io::gz_write_ucd_mesh_mpi(), gz_ucd_file_mpi_io::gz_write_ucd_vecotr_mpi(), gz_vtk_file_mpi_io::gz_write_vtk_header_mpi(), gz_vtk_file_mpi_io::gz_write_vtk_mesh_mpi(), gz_vtk_file_mpi_io::gz_write_vtk_scalar_mpi(), gz_vtk_file_mpi_io::gz_write_vtk_tensor_mpi(), gz_vtk_file_mpi_io::gz_write_vtk_vecotr_mpi(), zlib_cvt_ascii_ele_connect::infleate_1d_global_address(), zlib_convert_text::infleate_1word(), zlib_convert_text::infleate_characters(), zlib_cvt_ascii_comm_tbl::infleate_comm_table(), zlib_cvt_ascii_ele_connect::infleate_ele_connect(), zlib_cvt_ascii_ele_connect::infleate_ele_int_list(), zlib_cvt_ascii_comm_tbl::infleate_element_type(), zlib_convert_ascii_vector::infleate_node_position(), zlib_convert_text::infleate_skip_header(), and zlib_convert_ascii_vector::infleate_vector_txt().
link_compressed_buffer()
subroutine t_buffer_4_gzip::link_compressed_buffer (integer, intent(in) len_gzipbuf, character(len=1), dimension(len_gzipbuf), intent(in), target gzipbuf, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 187 of file t_buffer_4_gzip.f90.
Referenced by gzip_defleate::gzip_defleat_char_begin(), gzip_defleate::gzip_defleat_char_once(), gzip_defleate::gzip_defleat_int4_once(), gzip_defleate::gzip_defleat_int8_once(), gzip_defleate::gzip_defleat_real_once(), gzip_infleate::gzip_infleat_int4_once(), gzip_infleate::gzip_infleat_int8_once(), gzip_infleate::gzip_infleat_real_once(), and link_pointer_for_zlib_buffer().
link_int4_buffer_for_zlib()
subroutine t_buffer_4_gzip::link_int4_buffer_for_zlib (integer, intent(in) num, integer(kind = 4), dimension(num), intent(in), target int4_dat, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 232 of file t_buffer_4_gzip.f90.
Referenced by gzip_defleate::gzip_defleat_int4_once(), gzip_infleate::gzip_infleat_int4_once(), gzip_file_access::gzread_int4_f(), and gzip_file_access::gzwrite_int4_f().
link_int8_buffer_for_zlib()
subroutine t_buffer_4_gzip::link_int8_buffer_for_zlib (integer, intent(in) num, integer(kind = kint_gl), dimension(num), intent(in), target int8_dat, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 217 of file t_buffer_4_gzip.f90.
References m_precision::kint_gl.
Referenced by gzip_defleate::gzip_defleat_int8_once(), gzip_infleate::gzip_infleat_int8_once(), gzip_file_access::gzread_int8_f(), and gzip_file_access::gzwrite_int8_f().
link_pointer_for_zlib_buffer()
subroutine t_buffer_4_gzip::link_pointer_for_zlib_buffer (integer, intent(in) len_gzipbuf, character(len=1), dimension(len_gzipbuf), intent(in), target gzipbuf, integer, intent(in) len_buf, character(len=1), dimension(len_buf), intent(in), target textbuf, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 158 of file t_buffer_4_gzip.f90.
References link_compressed_buffer(), and link_text_buffer_for_zlib().
Referenced by gzip_infleate::gzip_infleat_char_once(), zlib_cvt_ascii_ele_connect::infleate_1d_global_address(), zlib_cvt_ascii_comm_tbl::infleate_comm_table(), zlib_cvt_ascii_ele_connect::infleate_ele_connect(), zlib_cvt_ascii_ele_connect::infleate_ele_int_list(), zlib_cvt_ascii_comm_tbl::infleate_element_type(), zlib_convert_ascii_vector::infleate_node_position(), and zlib_convert_ascii_vector::infleate_vector_txt().
link_real_buffer_for_zlib()
subroutine t_buffer_4_gzip::link_real_buffer_for_zlib (integer, intent(in) num, real(kind = kreal), dimension(num), intent(in), target data, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 202 of file t_buffer_4_gzip.f90.
References m_precision::kreal.
Referenced by gzip_defleate::gzip_defleat_real_once(), gzip_infleate::gzip_infleat_real_once(), gzip_file_access::gzread_real_f(), and gzip_file_access::gzwrite_real_f().
link_text_buffer_for_zlib()
subroutine t_buffer_4_gzip::link_text_buffer_for_zlib (integer, intent(in) len_buf, character(len=1), dimension(len_buf), intent(in), target textbuf, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 247 of file t_buffer_4_gzip.f90.
Referenced by gzip_file_access::get_one_line_text_from_gz(), gzip_file_access::gz_write_textbuf_no_lf(), gzip_defleate::gzip_defleat_char_begin(), gzip_defleate::gzip_defleat_char_cont(), gzip_defleate::gzip_defleat_char_last(), gzip_defleate::gzip_defleat_char_once(), gzip_file_access::gzread_chara_f(), gzip_file_access::gzwrite_chara_f(), link_pointer_for_zlib_buffer(), gzip_file_access::open_ad_gzfile_f(), gzip_file_access::open_rd_gzfile_f(), and gzip_file_access::open_wt_gzfile_f().
unlink_compressed_buffer()
subroutine t_buffer_4_gzip::unlink_compressed_buffer (type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 263 of file t_buffer_4_gzip.f90.
Referenced by unlink_pointer_for_zlib_buffer().
unlink_int4_buffer_for_zlib()
subroutine t_buffer_4_gzip::unlink_int4_buffer_for_zlib (type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 293 of file t_buffer_4_gzip.f90.
Referenced by gzip_file_access::gzread_int4_f(), and gzip_file_access::gzwrite_int4_f().
unlink_int8_buffer_for_zlib()
subroutine t_buffer_4_gzip::unlink_int8_buffer_for_zlib (type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 283 of file t_buffer_4_gzip.f90.
Referenced by gzip_file_access::gzread_int8_f(), and gzip_file_access::gzwrite_int8_f().
unlink_pointer_for_zlib_buffer()
subroutine t_buffer_4_gzip::unlink_pointer_for_zlib_buffer (type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 176 of file t_buffer_4_gzip.f90.
References unlink_compressed_buffer(), and unlink_text_buffer_for_zlib().
Referenced by gzip_defleate::gzip_defleat_char_last(), zlib_cvt_ascii_ele_connect::infleate_1d_global_address(), zlib_convert_text::infleate_1word(), zlib_convert_text::infleate_characters(), zlib_cvt_ascii_comm_tbl::infleate_comm_table(), zlib_cvt_ascii_ele_connect::infleate_ele_connect(), zlib_cvt_ascii_ele_connect::infleate_ele_int_list(), zlib_cvt_ascii_comm_tbl::infleate_element_type(), zlib_convert_ascii_vector::infleate_node_position(), zlib_convert_text::infleate_skip_header(), and zlib_convert_ascii_vector::infleate_vector_txt().
unlink_real_buffer_for_zlib()
subroutine t_buffer_4_gzip::unlink_real_buffer_for_zlib (type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 273 of file t_buffer_4_gzip.f90.
Referenced by gzip_file_access::gzread_real_f(), and gzip_file_access::gzwrite_real_f().
unlink_text_buffer_for_zlib()
subroutine t_buffer_4_gzip::unlink_text_buffer_for_zlib (type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 303 of file t_buffer_4_gzip.f90.
Referenced by gzip_file_access::get_one_line_text_from_gz(), gzip_file_access::gz_write_textbuf_no_lf(), gzip_file_access::gzread_chara_f(), gzip_file_access::gzwrite_chara_f(), gzip_file_access::open_ad_gzfile_f(), gzip_file_access::open_rd_gzfile_f(), gzip_file_access::open_wt_gzfile_f(), and unlink_pointer_for_zlib_buffer().
Variable Documentation
nbuf
integer(kind = 4), parameter, private t_buffer_4_gzip::nbuf = 65535 private
lengh of fixed text buffer
Definition at line 48 of file t_buffer_4_gzip.f90.