CALYPSO: pickup_surface_4_viewer Module Reference
pickup_surface_4_viewer Module Reference
Functions/Subroutines
subroutine allocate_imark_surf (surf)
subroutine allocate_sf_cvt_table_viewer (surf, view_mesh)
subroutine deallocate_imark_surf
subroutine deallocate_sf_cvt_table_viewer
subroutine mark_used_surface_4_viewer (group, surf, mgd_sf_grp)
subroutine count_used_surface_4_viewer (numsurf, nsurf_viewer)
subroutine set_surf_cvt_table_viewer (surf)
subroutine set_surf_connect_viewer (surf, view_mesh)
subroutine set_surf_domain_item_viewer (surf, domain_surf_grp)
subroutine set_element_group_item_viewer (mgd_sf_grp, ele_surf_grp)
subroutine set_surface_group_item_viewer (mgd_sf_grp, sf_surf_grp)
Variables
integer(kind=kint), dimension(:), allocatable, private imark_surf
integer(kind=kint), dimension(:), allocatable, private isf_merge2viewer
integer(kind=kint), dimension(:), allocatable, private isf_viewer2merge
Function/Subroutine Documentation
allocate_imark_surf()
subroutine pickup_surface_4_viewer::allocate_imark_surf (type(surface_data), intent(in) surf)
Definition at line 57 of file pickup_surface_4_viewer.f90.
References imark_surf.
Referenced by set_surf_connect_4_viewer::s_set_surf_connect_4_viewer().
allocate_sf_cvt_table_viewer()
subroutine pickup_surface_4_viewer::allocate_sf_cvt_table_viewer (type(surface_data), intent(in) surf, type(viewer_mesh_data), intent(in) view_mesh)
Definition at line 68 of file pickup_surface_4_viewer.f90.
References isf_merge2viewer, and isf_viewer2merge.
Referenced by set_surf_connect_4_viewer::s_set_surf_connect_4_viewer().
count_used_surface_4_viewer()
subroutine pickup_surface_4_viewer::count_used_surface_4_viewer (integer(kind = kint), intent(in) numsurf, integer(kind = kint), intent(inout) nsurf_viewer)
Definition at line 132 of file pickup_surface_4_viewer.f90.
References imark_surf.
Referenced by set_surf_connect_4_viewer::s_set_surf_connect_4_viewer().
deallocate_imark_surf()
subroutine pickup_surface_4_viewer::deallocate_imark_surf
Definition at line 82 of file pickup_surface_4_viewer.f90.
References imark_surf.
Referenced by set_surf_connect_4_viewer::s_set_surf_connect_4_viewer().
deallocate_sf_cvt_table_viewer()
subroutine pickup_surface_4_viewer::deallocate_sf_cvt_table_viewer
Definition at line 90 of file pickup_surface_4_viewer.f90.
References isf_merge2viewer, and isf_viewer2merge.
Referenced by set_surf_connect_4_viewer::s_set_surf_connect_4_viewer().
mark_used_surface_4_viewer()
subroutine pickup_surface_4_viewer::mark_used_surface_4_viewer (type(mesh_groups), intent(in) group, type(surface_data), intent(in) surf, type(viewer_ele_grp_surface), intent(in) mgd_sf_grp)
Definition at line 100 of file pickup_surface_4_viewer.f90.
References imark_surf.
Referenced by set_surf_connect_4_viewer::s_set_surf_connect_4_viewer().
set_element_group_item_viewer()
subroutine pickup_surface_4_viewer::set_element_group_item_viewer (type(viewer_ele_grp_surface), intent(in) mgd_sf_grp, type(viewer_group_data), intent(inout) ele_surf_grp)
Definition at line 214 of file pickup_surface_4_viewer.f90.
References isf_merge2viewer.
Referenced by set_surf_connect_4_viewer::s_set_groups_4_viewer_surface().
set_surf_connect_viewer()
subroutine pickup_surface_4_viewer::set_surf_connect_viewer (type(surface_data), intent(in) surf, type(viewer_mesh_data), intent(inout) view_mesh)
Definition at line 172 of file pickup_surface_4_viewer.f90.
References isf_viewer2merge.
Referenced by set_surf_connect_4_viewer::s_set_surf_connect_4_viewer().
set_surf_cvt_table_viewer()
subroutine pickup_surface_4_viewer::set_surf_cvt_table_viewer (type(surface_data), intent(in) surf)
Definition at line 150 of file pickup_surface_4_viewer.f90.
References imark_surf, isf_merge2viewer, and isf_viewer2merge.
Referenced by set_surf_connect_4_viewer::s_set_surf_connect_4_viewer().
set_surf_domain_item_viewer()
subroutine pickup_surface_4_viewer::set_surf_domain_item_viewer (type(surface_data), intent(in) surf, type(viewer_group_data), intent(inout) domain_surf_grp)
Definition at line 193 of file pickup_surface_4_viewer.f90.
References isf_merge2viewer.
Referenced by set_surf_connect_4_viewer::s_set_groups_4_viewer_surface().
set_surface_group_item_viewer()
subroutine pickup_surface_4_viewer::set_surface_group_item_viewer (type(viewer_ele_grp_surface), intent(in) mgd_sf_grp, type(viewer_group_data), intent(inout) sf_surf_grp)
Definition at line 236 of file pickup_surface_4_viewer.f90.
References isf_merge2viewer.
Referenced by set_surf_connect_4_viewer::s_set_groups_4_viewer_surface().
Variable Documentation
imark_surf
integer(kind = kint), dimension(:), allocatable, private pickup_surface_4_viewer::imark_surf private
Definition at line 45 of file pickup_surface_4_viewer.f90.
Referenced by allocate_imark_surf(), count_used_surface_4_viewer(), deallocate_imark_surf(), mark_used_surface_4_viewer(), and set_surf_cvt_table_viewer().
isf_merge2viewer
integer(kind = kint), dimension(:), allocatable, private pickup_surface_4_viewer::isf_merge2viewer private
Definition at line 46 of file pickup_surface_4_viewer.f90.
Referenced by allocate_sf_cvt_table_viewer(), deallocate_sf_cvt_table_viewer(), set_element_group_item_viewer(), set_surf_cvt_table_viewer(), set_surf_domain_item_viewer(), and set_surface_group_item_viewer().
isf_viewer2merge
integer(kind = kint), dimension(:), allocatable, private pickup_surface_4_viewer::isf_viewer2merge private
Definition at line 47 of file pickup_surface_4_viewer.f90.
Referenced by allocate_sf_cvt_table_viewer(), deallocate_sf_cvt_table_viewer(), set_surf_connect_viewer(), and set_surf_cvt_table_viewer().