CALYPSO: set_bc_flag_sph_velo Module Reference
set_bc_flag_sph_velo Module Reference
Set boundary conditions flags for velocity.
Functions/Subroutines
subroutine set_sph_bc_velo_sph (bc_IO, sph_rj, radial_rj_grp, r_ICB, r_CMB, velo_nod, torque_surf, sph_bc_U, bcs_U)
subroutine, private set_sph_velo_icb_flag (sph_rj, bc_IO, r_ICB, ibc_type, bc_mag, sph_bc_U, ICB_Uspec, ICB_Uevo)
subroutine, private set_sph_velo_cmb_flag (sph_rj, bc_IO, r_CMB, ibc_type, bc_mag, sph_bc_U, CMB_Uspec, CMB_Uevo)
Detailed Description
Set boundary conditions flags for velocity.
      subroutine set_sph_bc_velo_sph(bc_IO, sph_rj, radial_rj_grp,    &
     &          r_ICB, r_CMB, velo_nod, torque_surf, sph_bc_U, bcs_U)
        type(sph_rj_grid), intent(in) :: sph_rj
        type(group_data), intent(in) :: radial_rj_grp
        type(boundary_condition_list), intent(in) :: velo_nod
        type(boundary_condition_list), intent(in) :: torque_surf
        type(boundary_spectra), intent(in) :: bc_IO
        type(sph_boundary_type), intent(inout) :: sph_bc_U
        type(sph_vector_boundary_data), intent(inout) :: bcs_U
Function/Subroutine Documentation
set_sph_bc_velo_sph()
subroutine set_bc_flag_sph_velo::set_sph_bc_velo_sph (type(boundary_spectra), intent(in) bc_IO, type(sph_rj_grid), intent(in) sph_rj, type(group_data), intent(in) radial_rj_grp, real(kind = kreal), intent(in) r_ICB, real(kind = kreal), intent(in) r_CMB, type(boundary_condition_list), intent(in) velo_nod, type(boundary_condition_list), intent(in) torque_surf, type(sph_boundary_type), intent(inout) sph_bc_U, type(sph_vector_boundary_data), intent(inout) bcs_U)
Definition at line 43 of file set_bc_flag_sph_velo.f90.
References t_boundary_sph_spectr::alloc_sph_vector_bcs_data(), set_bc_sph_scalars::find_both_sides_of_boundaries(), set_sph_velo_cmb_flag(), and set_sph_velo_icb_flag().
Referenced by set_bc_sph_mhd::s_set_bc_sph_mhd().
set_sph_velo_cmb_flag()
subroutine, private set_bc_flag_sph_velo::set_sph_velo_cmb_flag (type(sph_rj_grid), intent(in) sph_rj, type(boundary_spectra), intent(in) bc_IO, real(kind = kreal), intent(in) r_CMB, integer(kind = kint), intent(in) ibc_type, real(kind = kreal), intent(in) bc_mag, type(sph_boundary_type), intent(inout) sph_bc_U, type(sph_vector_bc_coef), intent(inout) CMB_Uspec, type(sph_vector_bc_evo), intent(inout) CMB_Uevo) private
Definition at line 159 of file set_bc_flag_sph_velo.f90.
References m_boundary_condition_ids::iflag_bc_evo_field, m_boundary_condition_ids::iflag_bc_file_s, m_boundary_condition_ids::iflag_bc_rot, t_boundary_params_sph_mhd::iflag_fixed_field, t_boundary_params_sph_mhd::iflag_fixed_velo, t_boundary_params_sph_mhd::iflag_free_slip, m_boundary_condition_ids::iflag_free_sph, m_boundary_condition_ids::iflag_non_slip_sph, set_sph_bc_data_by_file::set_evolved_vector_bc_by_file(), set_sph_bc_data_by_file::set_fixed_vector_bc_by_file(), and m_base_field_labels::velocity.
Referenced by set_sph_bc_velo_sph().
set_sph_velo_icb_flag()
subroutine, private set_bc_flag_sph_velo::set_sph_velo_icb_flag (type(sph_rj_grid), intent(in) sph_rj, type(boundary_spectra), intent(in) bc_IO, real(kind = kreal), intent(in) r_ICB, integer(kind = kint), intent(in) ibc_type, real(kind = kreal), intent(in) bc_mag, type(sph_boundary_type), intent(inout) sph_bc_U, type(sph_vector_bc_coef), intent(inout) ICB_Uspec, type(sph_vector_bc_evo), intent(inout) ICB_Uevo) private
Definition at line 98 of file set_bc_flag_sph_velo.f90.
References m_boundary_condition_ids::iflag_bc_evo_field, m_boundary_condition_ids::iflag_bc_file_s, m_boundary_condition_ids::iflag_bc_rot, t_boundary_params_sph_mhd::iflag_fixed_field, t_boundary_params_sph_mhd::iflag_fixed_velo, t_boundary_params_sph_mhd::iflag_free_slip, m_boundary_condition_ids::iflag_free_sph, m_boundary_condition_ids::iflag_non_slip_sph, t_boundary_params_sph_mhd::iflag_rotatable_ic, m_boundary_condition_ids::iflag_rotatable_icore, m_boundary_condition_ids::iflag_sph_2_center, m_boundary_condition_ids::iflag_sph_clip_center, t_boundary_params_sph_mhd::iflag_sph_fill_center, t_boundary_params_sph_mhd::iflag_sph_fix_center, set_sph_bc_data_by_file::set_evolved_vector_bc_by_file(), set_sph_bc_data_by_file::set_fixed_vector_bc_by_file(), and m_base_field_labels::velocity.
Referenced by set_sph_bc_velo_sph().