CALYPSO: set_control_4_normalize Module Reference
set_control_4_normalize Module Reference
set normalizatios for MHD simulation from control data
Functions/Subroutines
subroutine s_set_control_4_normalize (fl_prop, cd_prop, ht_prop, cp_prop, dless_ctl, eqs_ctl, MHD_coef_list)
subroutine, private set_dimensionless_numbers (dless_ctl, MHD_coef_list)
subroutine, private set_coefs_4_thermal_eq (heat_ctl, MHD_coef_list)
subroutine, private set_coefs_4_momentum_eq (fl_prop, mom_ctl, MHD_coef_list)
subroutine, private set_coefs_4_induction_eq (cd_prop, induct_ctl, MHD_coef_list)
subroutine, private set_coefs_4_composition_eq (comp_ctl, MHD_coef_list)
subroutine, private copy_dimless_from_ctl (coef_ctl, dimless_list)
subroutine, private copy_power_and_names_from_ctl (coef_ctl, coef_list)
Detailed Description
set normalizatios for MHD simulation from control data
      subroutine s_set_control_4_normalize                            &
     &        (fl_prop, cd_prop, ht_prop, cp_prop,                    &
     &         dless_ctl, eqs_ctl, MHD_coef_list)
        type(fluid_property), intent(in) :: fl_prop
        type(conductive_property), intent(in)  :: cd_prop
        type(scalar_property), intent(in) :: ht_prop, cp_prop
        type(dimless_control), intent(in) :: dless_ctl
        type(equations_control), intent(in) :: eqs_ctl
        type(coef_parameters_list), intent(inout) :: MHD_coef_list
Function/Subroutine Documentation
copy_dimless_from_ctl()
subroutine, private set_control_4_normalize::copy_dimless_from_ctl (type(ctl_array_cr), intent(in) coef_ctl, type(list_of_dimless), intent(inout) dimless_list) private
Definition at line 392 of file set_control_4_normalize.f90.
References t_normalize_parameter::alloc_dimless_list().
Referenced by set_dimensionless_numbers().
copy_power_and_names_from_ctl()
subroutine, private set_control_4_normalize::copy_power_and_names_from_ctl (type(ctl_array_cr), intent(in) coef_ctl, type(powers_4_coefficients), intent(inout) coef_list) private
Definition at line 412 of file set_control_4_normalize.f90.
References t_normalize_parameter::alloc_coef_power_list().
Referenced by set_coefs_4_composition_eq(), set_coefs_4_induction_eq(), set_coefs_4_momentum_eq(), and set_coefs_4_thermal_eq().
s_set_control_4_normalize()
subroutine set_control_4_normalize::s_set_control_4_normalize (type(fluid_property), intent(in) fl_prop, type(conductive_property), intent(in) cd_prop, type(scalar_property), intent(in) ht_prop, type(scalar_property), intent(in) cp_prop, type(dimless_control), intent(in) dless_ctl, type(equations_control), intent(in) eqs_ctl, type(coef_parameters_list), intent(inout) MHD_coef_list)
Definition at line 47 of file set_control_4_normalize.f90.
References t_physical_property::id_no_evolution, m_machine_parameter::iflag_debug, m_machine_parameter::iflag_routine_msg, set_coefs_4_composition_eq(), set_coefs_4_induction_eq(), set_coefs_4_momentum_eq(), set_coefs_4_thermal_eq(), and set_dimensionless_numbers().
Referenced by set_control_sph_mhd::set_control_4_sph_mhd().
set_coefs_4_composition_eq()
subroutine, private set_control_4_normalize::set_coefs_4_composition_eq (type(heat_equation_control), intent(in) comp_ctl, type(coef_parameters_list), intent(inout) MHD_coef_list) private
Definition at line 351 of file set_control_4_normalize.f90.
References calypso_mpi::calypso_mpi_abort(), copy_power_and_names_from_ctl(), m_machine_parameter::e_message, and m_error_ids::ierr_dless.
Referenced by s_set_control_4_normalize().
set_coefs_4_induction_eq()
subroutine, private set_control_4_normalize::set_coefs_4_induction_eq (type(conductive_property), intent(in) cd_prop, type(induction_equation_control), intent(in) induct_ctl, type(coef_parameters_list), intent(inout) MHD_coef_list) private
Definition at line 293 of file set_control_4_normalize.f90.
References calypso_mpi::calypso_mpi_abort(), copy_power_and_names_from_ctl(), m_machine_parameter::e_message, t_physical_property::id_no_evolution, and m_error_ids::ierr_dless.
Referenced by s_set_control_4_normalize().
set_coefs_4_momentum_eq()
subroutine, private set_control_4_normalize::set_coefs_4_momentum_eq (type(fluid_property), intent(in) fl_prop, type(momentum_equation_control), intent(in) mom_ctl, type(coef_parameters_list), intent(inout) MHD_coef_list) private
Definition at line 189 of file set_control_4_normalize.f90.
References calypso_mpi::calypso_mpi_abort(), copy_power_and_names_from_ctl(), m_machine_parameter::e_message, and m_error_ids::ierr_dless.
Referenced by s_set_control_4_normalize().
set_coefs_4_thermal_eq()
subroutine, private set_control_4_normalize::set_coefs_4_thermal_eq (type(heat_equation_control), intent(in) heat_ctl, type(coef_parameters_list), intent(inout) MHD_coef_list) private
Definition at line 150 of file set_control_4_normalize.f90.
References calypso_mpi::calypso_mpi_abort(), copy_power_and_names_from_ctl(), m_machine_parameter::e_message, and m_error_ids::ierr_dless.
Referenced by s_set_control_4_normalize().
set_dimensionless_numbers()
subroutine, private set_control_4_normalize::set_dimensionless_numbers (type(dimless_control), intent(in) dless_ctl, type(coef_parameters_list), intent(inout) MHD_coef_list) private
Definition at line 129 of file set_control_4_normalize.f90.
References calypso_mpi::calypso_mpi_abort(), copy_dimless_from_ctl(), m_machine_parameter::e_message, and m_error_ids::ierr_dless.
Referenced by s_set_control_4_normalize().