CALYPSO: gz_mpi_sph_gl_1d_idx_io_b Module Reference
gz_mpi_sph_gl_1d_idx_io_b Module Reference
Mesh file IO for gxipped format.
Functions/Subroutines
subroutine gz_mpi_read_rtp_gl_1d_table_b (IO_param, sph_IO)
subroutine gz_mpi_read_rj_gl_1d_table_b (IO_param, sph_IO)
subroutine gz_mpi_write_rtp_gl_1d_table_b (IO_param, sph_IO)
subroutine gz_mpi_write_rj_gl_1d_table_b (IO_param, sph_IO)
Detailed Description
Mesh file IO for gxipped format.
      subroutine gz_mpi_read_rtp_gl_1d_table_b(IO_param, sph_IO)
      subroutine gz_mpi_read_rj_gl_1d_table_b(IO_param, sph_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(sph_IO_data), intent(inout) :: sph_IO
      subroutine gz_mpi_write_rtp_gl_1d_table_b(IO_param, sph_IO)
      subroutine gz_mpi_write_rj_gl_1d_table_b(IO_param, sph_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(sph_IO_data), intent(in) :: sph_IO
Function/Subroutine Documentation
gz_mpi_read_rj_gl_1d_table_b()
subroutine gz_mpi_sph_gl_1d_idx_io_b::gz_mpi_read_rj_gl_1d_table_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(inout) sph_IO)
Definition at line 75 of file gz_MPI_sph_gl_1d_idx_IO_b.f90.
References t_node_id_spherical_io::alloc_idx_sph_1d1_io(), t_node_id_spherical_io::alloc_idx_sph_1d2_io(), t_node_id_spherical_io::alloc_num_idx_sph_io(), gz_mpi_binary_data_io::gz_mpi_read_1d_vector_b(), and gz_mpi_binary_data_io::gz_mpi_read_int_vector_b().
Referenced by gz_mpi_sph_modes_data_io_b::gz_mpi_read_modes_rlm_data_b(), and gz_mpi_sph_modes_data_io_b::gz_mpi_read_spectr_rj_data_b().
gz_mpi_read_rtp_gl_1d_table_b()
subroutine gz_mpi_sph_gl_1d_idx_io_b::gz_mpi_read_rtp_gl_1d_table_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(inout) sph_IO)
Definition at line 37 of file gz_MPI_sph_gl_1d_idx_IO_b.f90.
References t_node_id_spherical_io::alloc_idx_sph_1d1_io(), t_node_id_spherical_io::alloc_idx_sph_1d2_io(), t_node_id_spherical_io::alloc_idx_sph_1d3_io(), t_node_id_spherical_io::alloc_num_idx_sph_io(), gz_mpi_binary_data_io::gz_mpi_read_1d_vector_b(), and gz_mpi_binary_data_io::gz_mpi_read_int_vector_b().
Referenced by gz_mpi_sph_modes_data_io_b::gz_mpi_read_geom_rtm_data_b(), and gz_mpi_sph_modes_data_io_b::gz_mpi_read_geom_rtp_data_b().
gz_mpi_write_rj_gl_1d_table_b()
subroutine gz_mpi_sph_gl_1d_idx_io_b::gz_mpi_write_rj_gl_1d_table_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(in) sph_IO)
Definition at line 139 of file gz_MPI_sph_gl_1d_idx_IO_b.f90.
References gz_mpi_binary_data_io::gz_mpi_write_1d_vector_b(), and gz_mpi_binary_data_io::gz_mpi_write_int_vector_b().
Referenced by gz_mpi_sph_modes_data_io_b::gz_mpi_write_modes_rlm_data_b(), and gz_mpi_sph_modes_data_io_b::gz_mpi_write_spectr_rj_data_b().
gz_mpi_write_rtp_gl_1d_table_b()
subroutine gz_mpi_sph_gl_1d_idx_io_b::gz_mpi_write_rtp_gl_1d_table_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(in) sph_IO)
Definition at line 110 of file gz_MPI_sph_gl_1d_idx_IO_b.f90.
References gz_mpi_binary_data_io::gz_mpi_write_1d_vector_b(), and gz_mpi_binary_data_io::gz_mpi_write_int_vector_b().
Referenced by gz_mpi_sph_modes_data_io_b::gz_mpi_write_geom_rtm_data_b(), and gz_mpi_sph_modes_data_io_b::gz_mpi_write_geom_rtp_data_b().