CALYPSO: init_spherical_srs Module Reference
init_spherical_srs Module Reference
Arbitrary components data communications
for spherical harmonics transform.
Functions/Subroutines
subroutine init_sph_send_recv_n (NB, sph, comms_sph, iflag_recv)
subroutine, private sel_sph_import_table (NB, comms_sph, nnod_rtp, nnod_rtm, nnod_rlm, nnod_rj, X_rtp, X_rtm, X_rlm, X_rj, iflag_recv)
subroutine, private all_sph_send_recv_n (iflag_recv, NB, comms_sph, nnod_rtp, nnod_rtm, nnod_rlm, nnod_rj, X_rtp, X_rtm, X_rlm, X_rj)
subroutine, private all_sph_sr_core_n (NB, comms_sph)
subroutine, private check_spherical_srs_n (NB, comm_rtp, comm_rtm, comm_rlm, comm_rj)
subroutine, private check_calypso_sph_buffer_n (NB, comms_sph)
Variables
type(leg_trns_spin_work), save, private wk0_spin
Detailed Description
Arbitrary components data communications
for spherical harmonics transform.
      subroutine init_sph_send_recv_N(NB, sph, comms_sph, iflag_recv)
        type(sph_grids), intent(in) :: sph
        type(sph_comm_tables), intent(in) :: comms_sph
Parameters
NB Number of components for communication
X_rtp(NB*nnod_rtp) \(f(r,\theta,\phi) \)
(Order, X_rtp(i_comp,inod))
Function/Subroutine Documentation
all_sph_send_recv_n()
subroutine, private init_spherical_srs::all_sph_send_recv_n (integer(kind = kint), intent(in) iflag_recv, integer(kind = kint), intent(in) NB, type(sph_comm_tables), intent(in) comms_sph, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) nnod_rtm, integer(kind = kint), intent(in) nnod_rlm, integer(kind = kint), intent(in) nnod_rj, real (kind=kreal), dimension(nb*nnod_rtp), intent(inout) X_rtp, real (kind=kreal), dimension(nb*nnod_rtm), intent(inout) X_rtm, real (kind=kreal), dimension(nb*nnod_rlm), intent(inout) X_rlm, real (kind=kreal), dimension(nb*nnod_rj), intent(inout) X_rj) private
Definition at line 159 of file init_spherical_SRs.f90.
Referenced by sel_sph_import_table().
all_sph_sr_core_n()
subroutine, private init_spherical_srs::all_sph_sr_core_n (integer (kind=kint), intent(in) NB, type(sph_comm_tables), intent(in) comms_sph) private
Definition at line 190 of file init_spherical_SRs.f90.
check_calypso_sph_buffer_n()
subroutine, private init_spherical_srs::check_calypso_sph_buffer_n (integer (kind=kint), intent(in) NB, type(sph_comm_tables), intent(in) comms_sph) private
Definition at line 255 of file init_spherical_SRs.f90.
Referenced by init_sph_send_recv_n().
check_spherical_srs_n()
subroutine, private init_spherical_srs::check_spherical_srs_n (integer (kind=kint), intent(in) NB, type(sph_comm_tbl), intent(in) comm_rtp, type(sph_comm_tbl), intent(in) comm_rtm, type(sph_comm_tbl), intent(in) comm_rlm, type(sph_comm_tbl), intent(in) comm_rj) private
Definition at line 217 of file init_spherical_SRs.f90.
Referenced by init_sph_send_recv_n(), and sel_sph_import_table().
init_sph_send_recv_n()
subroutine init_spherical_srs::init_sph_send_recv_n (integer(kind = kint), intent(in) NB, type(sph_grids), intent(in) sph, type(sph_comm_tables), intent(in) comms_sph, integer(kind = kint), intent(inout) iflag_recv)
Definition at line 47 of file init_spherical_SRs.f90.
References t_work_4_sph_trans_spin::alloc_work_sph_trans(), check_calypso_sph_buffer_n(), check_spherical_srs_n(), t_work_4_sph_trans_spin::dealloc_work_sph_trans(), sel_sph_import_table(), and wk0_spin.
Referenced by init_sph_trans::set_blocks_4_leg_trans().
sel_sph_import_table()
subroutine, private init_spherical_srs::sel_sph_import_table (integer(kind = kint), intent(in) NB, type(sph_comm_tables), intent(in) comms_sph, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) nnod_rtm, integer(kind = kint), intent(in) nnod_rlm, integer(kind = kint), intent(in) nnod_rj, real (kind=kreal), dimension(nb*nnod_rtp), intent(inout) X_rtp, real (kind=kreal), dimension(nb*nnod_rtm), intent(inout) X_rtm, real (kind=kreal), dimension(nb*nnod_rlm), intent(inout) X_rlm, real (kind=kreal), dimension(nb*nnod_rj), intent(inout) X_rj, integer(kind = kint), intent(inout) iflag_recv) private
Definition at line 87 of file init_spherical_SRs.f90.
References all_sph_send_recv_n(), calypso_mpi_real::calypso_mpi_allreduce_real(), transfer_to_long_integers::cast_long(), check_spherical_srs_n(), select_copy_from_recv::iflag_import_item, select_copy_from_recv::iflag_import_rev, select_copy_from_recv::iflag_import_undefined, calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by init_sph_send_recv_n().
Variable Documentation
wk0_spin
type(leg_trns_spin_work), save, private init_spherical_srs::wk0_spin private
Definition at line 35 of file init_spherical_SRs.f90.
Referenced by init_sph_send_recv_n().