CALYPSO: chebyshev_radial_grid Module Reference
chebyshev_radial_grid Module Reference
Set radial grid data.
Functions/Subroutines
subroutine set_chebyshev_distance_shell (num_layer, nlayer_ICB, nlayer_CMB, r_ICB, r_CMB, r_grid)
subroutine adjust_chebyshev_shell (num_layer, nlayer_ICB, nlayer_CMB, increment, r_grid)
subroutine count_chebyshev_ext_layers (nri, r_ICB, r_CMB, r_min, r_max, ntot_shell, nlayer_ICB, nlayer_CMB)
Detailed Description
Set radial grid data.
      subroutine set_chebyshev_distance_shell(num_layer, nlayer_ICB,  &
     &          nlayer_CMB, r_ICB, r_CMB, r_grid)
      subroutine adjust_chebyshev_shell                               &
     &         (num_layer, nlayer_ICB, nlayer_CMB, increment, r_grid)
      subroutine count_chebyshev_ext_layers(nri, r_ICB, r_CMB,        &
     &          r_min, r_max, ntot_shell, nlayer_ICB, nlayer_CMB)
Function/Subroutine Documentation
adjust_chebyshev_shell()
subroutine chebyshev_radial_grid::adjust_chebyshev_shell (integer(kind = kint), intent(in) num_layer, integer(kind = kint), intent(in) nlayer_ICB, integer(kind = kint), intent(in) nlayer_CMB, integer(kind = kint), intent(in) increment, real(kind = kreal), dimension(num_layer), intent(inout) r_grid)
Definition at line 87 of file chebyshev_radial_grid.f90.
References m_constants::ione, and m_constants::itwo.
Referenced by const_sph_radial_grid::count_set_radial_grid().
count_chebyshev_ext_layers()
subroutine chebyshev_radial_grid::count_chebyshev_ext_layers (integer(kind = kint), intent(in) nri, real(kind = kreal), intent(in) r_ICB, real(kind = kreal), intent(in) r_CMB, real(kind = kreal), intent(in) r_min, real(kind = kreal), intent(in) r_max, integer(kind = kint), intent(inout) ntot_shell, integer(kind = kint), intent(inout) nlayer_ICB, integer(kind = kint), intent(inout) nlayer_CMB)
Definition at line 133 of file chebyshev_radial_grid.f90.
References m_constants::four, m_constants::half, and m_constants::one.
Referenced by const_sph_radial_grid::count_set_radial_grid().
set_chebyshev_distance_shell()
subroutine chebyshev_radial_grid::set_chebyshev_distance_shell (integer(kind = kint), intent(in) num_layer, integer(kind = kint), intent(in) nlayer_ICB, integer(kind = kint), intent(in) nlayer_CMB, real(kind = kreal), intent(in) r_ICB, real(kind = kreal), intent(in) r_CMB, real(kind = kreal), dimension(num_layer), intent(inout) r_grid)
Definition at line 32 of file chebyshev_radial_grid.f90.
References m_constants::four, m_constants::half, m_constants::ione, m_constants::itwo, and m_constants::one.
Referenced by const_sph_radial_grid::count_set_radial_grid(), and set_radial_grid_sph_shell::set_radial_distance_flag().