CALYPSO: t_sph_comm_table_from_fft Module Reference
t_sph_comm_table_from_fft Module Reference
Fourier transform using FFTPACK5.
Data Types
type comm_tbl_from_fft
Structure of communication table from FFT to send buffer.
Functions/Subroutines
subroutine alloc_comm_table_sph_fft (ntot_sr_rtp, comm_sph_FFT)
subroutine dealloc_comm_table_sph_fft (comm_sph_FFT)
subroutine copy_all_rtp_fft_to_send_smp (nnod_rtp, nidx_rtp, irt_rtp_smp_stack, ncomp_fwd, X_FFT, comm_sph_FFT, n_WS, WS)
subroutine copy_1comp_rtp_fft_to_send_smp (nd, nnod_rtp, nidx_rtp, irt_rtp_smp_stack, ncomp_fwd, X_FFT, comm_sph_FFT, n_WS, WS)
subroutine copy_all_rtp_fft_to_send (nnod_rtp, irt_rtp_smp_stack, ncomp_fwd, X_FFT, comm_sph_FFT, n_WS, WS)
subroutine copy_1comp_rtp_fft_to_send (nd, nnod_rtp, irt_rtp_smp_stack, ncomp_fwd, X_FFT, comm_sph_FFT, n_WS, WS)
subroutine copy_all_prt_fft_to_send (nnod_rtp, nidx_rtp, ncomp_fwd, X_FFT, comm_sph_FFT, n_WS, WS)
subroutine copy_1comp_prt_fft_to_send (nd, nnod_rtp, nidx_rtp, ncomp_fwd, X_FFT, comm_sph_FFT, n_WS, WS)
Detailed Description
Fourier transform using FFTPACK5.
      subroutine alloc_comm_table_sph_FFT(ntot_sr_rtp, comm_sph_FFT)
      subroutine dealloc_comm_table_sph_FFT(comm_sph_FFT)
        type(comm_tbl_from_FFT), intent(inout) :: comm_sph_FFT
      subroutine copy_all_rtp_FFT_to_send_smp                         &
     &         (nnod_rtp, nidx_rtp, irt_rtp_smp_stack, ncomp_fwd,     &
     &          X_FFT, comm_sph_FFT, n_WS, WS)
      subroutine copy_1comp_rtp_FFT_to_send_smp                       &
     &         (nd, nnod_rtp, nidx_rtp, irt_rtp_smp_stack, ncomp_fwd, &
     &          X_FFT, comm_sph_FFT, n_WS, WS)
      subroutine copy_all_rtp_FFT_to_send(nnod_rtp, irt_rtp_smp_stack,&
     &          ncomp_fwd, X_FFT, comm_sph_FFT, n_WS, WS)
      subroutine copy_1comp_rtp_FFT_to_send                           &
     &         (nd, nnod_rtp, irt_rtp_smp_stack, ncomp_fwd,           &
     &          X_FFT, comm_sph_FFT, n_WS, WS)
        type(comm_tbl_from_FFT), intent(in) :: comm_sph_FFT
      subroutine copy_all_prt_FFT_to_send(nnod_rtp, nidx_rtp,         &
     &          ncomp_fwd, X_FFT, comm_sph_FFT, n_WS, WS)
      subroutine copy_1comp_prt_FFT_to_send(nd, nnod_rtp, nidx_rtp,   &
     &          ncomp_fwd, X_FFT, comm_sph_FFT, n_WS, WS)
Function/Subroutine Documentation
alloc_comm_table_sph_fft()
subroutine t_sph_comm_table_from_fft::alloc_comm_table_sph_fft (integer(kind = kint), intent(in) ntot_sr_rtp, type(comm_tbl_from_fft), intent(inout) comm_sph_FFT)
Definition at line 67 of file t_sph_comm_table_from_FFT.f90.
Referenced by sph_prt_domain_fftpack5::init_prt_domain_fftpack5(), sph_prt_fftpack5::init_prt_fftpack5(), sph_rtp_domain_fftpack5::init_rtp_domain_fftpack5(), sph_rtp_fftpack5::init_rtp_fftpack5(), sph_prt_domain_fftpack5::verify_prt_domain_fftpack5(), sph_prt_fftpack5::verify_prt_fftpack5(), sph_rtp_domain_fftpack5::verify_rtp_domain_fftpack5(), and sph_rtp_fftpack5::verify_rtp_fftpack5().
copy_1comp_prt_fft_to_send()
subroutine t_sph_comm_table_from_fft::copy_1comp_prt_fft_to_send (integer(kind = kint), intent(in) nd, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(3), intent(in) nidx_rtp, integer(kind = kint), intent(in) ncomp_fwd, real(kind = kreal), dimension(nnod_rtp), intent(in) X_FFT, type(comm_tbl_from_fft), intent(in) comm_sph_FFT, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 274 of file t_sph_comm_table_from_FFT.f90.
Referenced by sph_prt_domain_fftpack5::prt_domain_rfftmf_to_send().
copy_1comp_rtp_fft_to_send()
subroutine t_sph_comm_table_from_fft::copy_1comp_rtp_fft_to_send (integer(kind = kint), intent(in) nd, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(0:np_smp), intent(in) irt_rtp_smp_stack, integer(kind = kint), intent(in) ncomp_fwd, real(kind = kreal), dimension(ncomp_fwd*nnod_rtp), intent(in) X_FFT, type(comm_tbl_from_fft), intent(in) comm_sph_FFT, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 208 of file t_sph_comm_table_from_FFT.f90.
References m_machine_parameter::np_smp.
copy_1comp_rtp_fft_to_send_smp()
subroutine t_sph_comm_table_from_fft::copy_1comp_rtp_fft_to_send_smp (integer(kind = kint), intent(in) nd, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(3), intent(in) nidx_rtp, integer(kind = kint), dimension(0:np_smp), intent(in) irt_rtp_smp_stack, integer(kind = kint), intent(in) ncomp_fwd, real(kind = kreal), dimension(ncomp_fwd*nnod_rtp), intent(in) X_FFT, type(comm_tbl_from_fft), intent(in) comm_sph_FFT, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 135 of file t_sph_comm_table_from_FFT.f90.
Referenced by sph_rtp_domain_fftpack5::rtp_domain_rfftmf_to_send().
copy_all_prt_fft_to_send()
subroutine t_sph_comm_table_from_fft::copy_all_prt_fft_to_send (integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(3), intent(in) nidx_rtp, integer(kind = kint), intent(in) ncomp_fwd, real(kind = kreal), dimension(nnod_rtp,ncomp_fwd), intent(in) X_FFT, type(comm_tbl_from_fft), intent(in) comm_sph_FFT, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 242 of file t_sph_comm_table_from_FFT.f90.
Referenced by sph_prt_fftpack5::prt_rfftmf_to_send().
copy_all_rtp_fft_to_send()
subroutine t_sph_comm_table_from_fft::copy_all_rtp_fft_to_send (integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(0:np_smp), intent(in) irt_rtp_smp_stack, integer(kind = kint), intent(in) ncomp_fwd, real(kind = kreal), dimension(ncomp_fwd*nnod_rtp), intent(in) X_FFT, type(comm_tbl_from_fft), intent(in) comm_sph_FFT, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 174 of file t_sph_comm_table_from_FFT.f90.
References m_machine_parameter::np_smp.
copy_all_rtp_fft_to_send_smp()
subroutine t_sph_comm_table_from_fft::copy_all_rtp_fft_to_send_smp (integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(3), intent(in) nidx_rtp, integer(kind = kint), dimension(0:np_smp), intent(in) irt_rtp_smp_stack, integer(kind = kint), intent(in) ncomp_fwd, real(kind = kreal), dimension(ncomp_fwd*nnod_rtp), intent(in) X_FFT, type(comm_tbl_from_fft), intent(in) comm_sph_FFT, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 94 of file t_sph_comm_table_from_FFT.f90.
Referenced by sph_rtp_fftpack5::rtp_rfftmf_to_send().
dealloc_comm_table_sph_fft()
subroutine t_sph_comm_table_from_fft::dealloc_comm_table_sph_fft (type(comm_tbl_from_fft), intent(inout) comm_sph_FFT)
Definition at line 82 of file t_sph_comm_table_from_FFT.f90.
Referenced by t_sph_domain_fftpack5::finalize_sph_domain_fftpack5(), t_sph_fftpack5::finalize_sph_fftpack5(), sph_prt_domain_fftpack5::verify_prt_domain_fftpack5(), sph_prt_fftpack5::verify_prt_fftpack5(), sph_rtp_domain_fftpack5::verify_rtp_domain_fftpack5(), and sph_rtp_fftpack5::verify_rtp_fftpack5().