CALYPSO: mpi_mesh_file_io Module Reference
mpi_mesh_file_io Module Reference
Functions/Subroutines
subroutine mpi_read_mesh_file (num_pe, id_rank, file_name, mesh_IO, group_IO)
subroutine mpi_read_mesh_geometry (num_pe, id_rank, file_name, mesh_IO)
subroutine mpi_read_node_size (num_pe, id_rank, file_name, mesh_IO)
subroutine mpi_read_geometry_size (num_pe, id_rank, file_name, mesh_IO)
subroutine mpi_write_mesh_file (file_name, mesh_IO, group_IO)
Variables
type(calypso_mpi_io_params), save, private io_param
Function/Subroutine Documentation
mpi_read_geometry_size()
subroutine mpi_mesh_file_io::mpi_read_geometry_size (integer, intent(in) num_pe, integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 121 of file MPI_mesh_file_IO.f90.
References mpi_ascii_data_io::close_mpi_file(), m_machine_parameter::i_debug, io_param, mpi_mesh_data_io::mpi_read_num_node_ele(), and mpi_ascii_data_io::open_read_mpi_file().
Referenced by mesh_mpi_io_select::sel_mpi_read_geometry_size().
mpi_read_mesh_file()
subroutine mpi_mesh_file_io::mpi_read_mesh_file (integer, intent(in) num_pe, integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(inout) mesh_IO, type(mesh_groups), intent(inout) group_IO)
Definition at line 47 of file MPI_mesh_file_IO.f90.
References mpi_ascii_data_io::close_mpi_file(), m_machine_parameter::i_debug, io_param, mpi_mesh_data_io::mpi_read_geometry_data(), mpi_mesh_data_io::mpi_read_mesh_groups(), and mpi_ascii_data_io::open_read_mpi_file().
Referenced by mesh_mpi_io_select::sel_mpi_read_mesh().
mpi_read_mesh_geometry()
subroutine mpi_mesh_file_io::mpi_read_mesh_geometry (integer, intent(in) num_pe, integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 74 of file MPI_mesh_file_IO.f90.
References mpi_ascii_data_io::close_mpi_file(), m_machine_parameter::i_debug, io_param, mpi_mesh_data_io::mpi_read_geometry_data(), and mpi_ascii_data_io::open_read_mpi_file().
Referenced by mesh_mpi_io_select::sel_mpi_read_mesh_geometry().
mpi_read_node_size()
subroutine mpi_mesh_file_io::mpi_read_node_size (integer, intent(in) num_pe, integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 97 of file MPI_mesh_file_IO.f90.
References mpi_ascii_data_io::close_mpi_file(), m_machine_parameter::i_debug, io_param, mpi_mesh_data_io::mpi_read_num_node(), and mpi_ascii_data_io::open_read_mpi_file().
Referenced by mesh_mpi_io_select::sel_mpi_read_node_size().
mpi_write_mesh_file()
subroutine mpi_mesh_file_io::mpi_write_mesh_file (character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(in) mesh_IO, type(mesh_groups), intent(in) group_IO)
Definition at line 145 of file MPI_mesh_file_IO.f90.
References mpi_ascii_data_io::close_mpi_file(), m_machine_parameter::i_debug, io_param, mpi_mesh_data_io::mpi_write_geometry_data(), mpi_mesh_data_io::mpi_write_mesh_groups(), and mpi_ascii_data_io::open_write_mpi_file().
Referenced by mesh_mpi_io_select::sel_mpi_write_mesh_file().
Variable Documentation
io_param
type(calypso_mpi_io_params), save, private mpi_mesh_file_io::io_param private
Definition at line 39 of file MPI_mesh_file_IO.f90.
Referenced by mpi_read_geometry_size(), mpi_read_mesh_file(), mpi_read_mesh_geometry(), mpi_read_node_size(), and mpi_write_mesh_file().