CALYPSO: analyzer_rayleigh_cvt_sph Module Reference
analyzer_rayleigh_cvt_sph Module Reference
Main loop to assemble spectr data.
Functions/Subroutines
subroutine init_cvt_rayleigh_sph
subroutine analyze_cvt_rayleigh_sph
Variables
type(control_param_assemble), save asbl_param_s
type(spectr_data_4_assemble), save sph_asbl_s
type(time_data), save init_t
type(rayleigh_restart), save ra_rst_s
type(field_io), save fld_io_r
Detailed Description
Main loop to assemble spectr data.
      subroutine init_cvt_rayleigh_sph
      subroutine analyze_cvt_rayleigh_sph
Function/Subroutine Documentation
analyze_cvt_rayleigh_sph()
subroutine analyzer_rayleigh_cvt_sph::analyze_cvt_rayleigh_sph
Definition at line 144 of file analyzer_rayleigh_cvt_sph.f90.
References asbl_param_s, calypso_mpi::calypso_mpi_barrier(), new_sph_restart::const_assembled_sph_data(), convert_from_rayleigh_rst::convert_fields_from_rayleigh(), t_field_data_io::dealloc_phys_data_io(), t_field_data_io::dealloc_phys_name_io(), m_machine_parameter::iflag_debug, t_convert_from_rayleigh::init_rayleigh_restart_params(), init_t, calypso_mpi::my_rank, ra_rst_s, field_io_select::sel_write_step_sph_field_file(), share_field_data::share_time_step_data(), and sph_asbl_s.
Referenced by convert_rayleigh_cvt().
init_cvt_rayleigh_sph()
subroutine analyzer_rayleigh_cvt_sph::init_cvt_rayleigh_sph
Definition at line 57 of file analyzer_rayleigh_cvt_sph.f90.
References t_spectr_data_4_assemble::alloc_spectr_data_4_assemble(), asbl_param_s, bcast_4_assemble_sph_ctl::bcast_merge_control_data(), t_check_and_make_sph_mesh::check_and_make_sph_rj_mode(), r_interpolate_marged_sph::const_r_interpolate_table(), t_convert_from_rayleigh::copy_rayleigh_radial_data(), copy_rj_phys_data_4_io::copy_rj_phys_name_from_io(), fld_io_r, m_file_format_switch::id_rayleigh99, rayleigh_restart_io::init_rayleigh_restart_input(), t_convert_from_rayleigh::init_rayleigh_restart_params(), calypso_mpi::my_rank, ra_rst_s, t_control_data_4_merge::read_control_assemble_sph(), count_nnod_4_asseble_sph::s_count_nnod_4_asseble_sph(), set_control_newsph::set_control_4_newsph(), assemble_sph_fields::share_new_spectr_field_names(), and sph_asbl_s.
Referenced by convert_rayleigh_cvt().
Variable Documentation
asbl_param_s
type(control_param_assemble), save analyzer_rayleigh_cvt_sph::asbl_param_s
Definition at line 44 of file analyzer_rayleigh_cvt_sph.f90.
Referenced by analyze_cvt_rayleigh_sph(), and init_cvt_rayleigh_sph().
fld_io_r
type(field_io), save analyzer_rayleigh_cvt_sph::fld_io_r
Definition at line 49 of file analyzer_rayleigh_cvt_sph.f90.
Referenced by init_cvt_rayleigh_sph().
init_t
type(time_data), save analyzer_rayleigh_cvt_sph::init_t
Definition at line 46 of file analyzer_rayleigh_cvt_sph.f90.
Referenced by analyze_cvt_rayleigh_sph().
ra_rst_s
type(rayleigh_restart), save analyzer_rayleigh_cvt_sph::ra_rst_s
Definition at line 48 of file analyzer_rayleigh_cvt_sph.f90.
Referenced by analyze_cvt_rayleigh_sph(), and init_cvt_rayleigh_sph().
sph_asbl_s
type(spectr_data_4_assemble), save analyzer_rayleigh_cvt_sph::sph_asbl_s
Definition at line 45 of file analyzer_rayleigh_cvt_sph.f90.
Referenced by analyze_cvt_rayleigh_sph(), and init_cvt_rayleigh_sph().