CALYPSO: set_connects_4_ele_group Module Reference
set_connects_4_ele_group Module Reference
Functions/Subroutines
subroutine set_surf_4_ele_group (ele, surf, ele_grp, ele_grp_tbl)
subroutine set_edge_4_ele_group (ele, edge, ele_grp, ele_grp_tbl)
subroutine set_node_4_ele_group (ele, nod, ele_grp, ele_grp_tbl)
subroutine empty_sf_ed_nod_ele_grp_type (ele_grp, ele_grp_tbl)
subroutine, private allocate_imark_ele_grp (num)
subroutine, private deallocate_imark_ele_grp
Variables
integer(kind=kint), dimension(:), allocatable, private imark_ele_grp
Function/Subroutine Documentation
allocate_imark_ele_grp()
subroutine, private set_connects_4_ele_group::allocate_imark_ele_grp (integer(kind = kint), intent(in) num) private
Definition at line 182 of file set_connects_4_ele_group.f90.
References imark_ele_grp.
Referenced by set_edge_4_ele_group(), set_node_4_ele_group(), and set_surf_4_ele_group().
deallocate_imark_ele_grp()
subroutine, private set_connects_4_ele_group::deallocate_imark_ele_grp private
Definition at line 193 of file set_connects_4_ele_group.f90.
References imark_ele_grp.
Referenced by set_edge_4_ele_group(), set_node_4_ele_group(), and set_surf_4_ele_group().
empty_sf_ed_nod_ele_grp_type()
subroutine set_connects_4_ele_group::empty_sf_ed_nod_ele_grp_type (type(group_data), intent(in) ele_grp, type(element_group_table), intent(inout) ele_grp_tbl)
Definition at line 160 of file set_connects_4_ele_group.f90.
References t_group_connects::alloc_item_other_grp(), and t_group_connects::alloc_num_other_grp().
Referenced by const_mesh_information::empty_mesh_info().
set_edge_4_ele_group()
subroutine set_connects_4_ele_group::set_edge_4_ele_group (type(element_data), intent(in) ele, type(edge_data), intent(in) edge, type(group_data), intent(in) ele_grp, type(element_group_table), intent(inout) ele_grp_tbl)
Definition at line 88 of file set_connects_4_ele_group.f90.
References t_group_connects::alloc_item_other_grp(), t_group_connects::alloc_num_other_grp(), allocate_imark_ele_grp(), set_node_4_group::count_nod_4_ele_grp(), deallocate_imark_ele_grp(), imark_ele_grp, m_geometry_constants::nedge_4_ele, and set_node_4_group::set_nod_4_ele_grp().
Referenced by const_mesh_information::const_group_type_info().
set_node_4_ele_group()
subroutine set_connects_4_ele_group::set_node_4_ele_group (type(element_data), intent(in) ele, type(node_data), intent(in) nod, type(group_data), intent(in) ele_grp, type(element_group_table), intent(inout) ele_grp_tbl)
Definition at line 125 of file set_connects_4_ele_group.f90.
References t_group_connects::alloc_item_other_grp(), t_group_connects::alloc_num_other_grp(), allocate_imark_ele_grp(), set_node_4_group::count_nod_4_ele_grp(), deallocate_imark_ele_grp(), imark_ele_grp, and set_node_4_group::set_nod_4_ele_grp().
Referenced by const_mesh_information::const_group_type_info().
set_surf_4_ele_group()
subroutine set_connects_4_ele_group::set_surf_4_ele_group (type(element_data), intent(in) ele, type(surface_data), intent(in) surf, type(group_data), intent(in) ele_grp, type(element_group_table), intent(inout) ele_grp_tbl)
Definition at line 51 of file set_connects_4_ele_group.f90.
References t_group_connects::alloc_item_other_grp(), t_group_connects::alloc_num_other_grp(), allocate_imark_ele_grp(), set_node_4_group::count_nod_4_ele_grp(), deallocate_imark_ele_grp(), imark_ele_grp, m_geometry_constants::nsurf_4_ele, and set_node_4_group::set_nod_4_ele_grp().
Referenced by const_mesh_information::const_group_type_info().
Variable Documentation
imark_ele_grp
integer(kind=kint), dimension(:), allocatable, private set_connects_4_ele_group::imark_ele_grp private
Definition at line 40 of file set_connects_4_ele_group.f90.
Referenced by allocate_imark_ele_grp(), deallocate_imark_ele_grp(), set_edge_4_ele_group(), set_node_4_ele_group(), and set_surf_4_ele_group().