CALYPSO: set_nodal_field_for_psf Module Reference
set_nodal_field_for_psf Module Reference
Set nodal field for sectioning.
Functions/Subroutines
subroutine count_position_4_psf (psf_list, psf_node)
subroutine set_position_4_psf (nnod, nedge, nnod_edge, ie_edge, xx, istack_intnod, nnod_patch, inod_sum, xx_patch, psf_list)
subroutine set_position_on_edge_psf (nnod, nedge, nnod_edge, ie_edge, xx, ishift, nnod_on_edge, istack_n_on_e_smp, iedge_4_nod, coef_on_edge, istack_intnod, nnod_patch, inod_sum, xx_patch)
subroutine set_field_on_edge_psf (nnod, nedge, nnod_edge, ie_edge, ncomp, d_nod, ishift, nnod_on_edge, istack_n_on_e_smp, iedge_4_nod, coef_on_edge, nnod_patch, dat_tmp)
subroutine set_field_on_psf_xyz (nnod, nedge, nnod_edge, ie_edge, nnod_patch, num_fld, ntot_comp, istack_comp_nod, d_nod, ifield_psf, ncomp, dat_tmp, psf_list)
subroutine set_const_on_psf (nnod_patch, const, dat_psf)
Detailed Description
Set nodal field for sectioning.
      subroutine count_position_4_psf(psf_list, psf_node)
        type(sectioning_list), intent(in) :: psf_list
        type(node_data), intent(inout) :: psf_node
      subroutine set_position_4_psf(nnod, nedge, nnod_edge, ie_edge,  &
     &          xx, istack_intnod, nnod_patch, inod_sum, xx_patch,    &
     &          psf_list)
      subroutine set_field_on_psf_xyz                                 &
     &          (nnod, nedge, nnod_edge, ie_edge, nnod_patch,         &
     &          num_fld, ntot_comp, istack_comp_nod,                  &
     &          d_nod, ifield_psf, ncomp, dat_tmp, psf_list)
      subroutine set_const_on_psf(nnod_patch, const, dat_psf)
Function/Subroutine Documentation
count_position_4_psf()
subroutine set_nodal_field_for_psf::count_position_4_psf (type(sectioning_list), intent(in) psf_list, type(node_data), intent(inout) psf_node)
Definition at line 41 of file set_nodal_field_for_psf.f90.
References cal_minmax_and_stacks::count_number_4_smp(), m_constants::ione, and m_machine_parameter::np_smp.
Referenced by set_nodes_for_psf::count_nodes_4_iso(), and set_nodes_for_psf::count_nodes_4_psf().
set_const_on_psf()
subroutine set_nodal_field_for_psf::set_const_on_psf (integer(kind = kint), intent(in) nnod_patch, real(kind = kreal), intent(in) const, real(kind = kreal), dimension(nnod_patch), intent(inout) dat_psf)
Definition at line 234 of file set_nodal_field_for_psf.f90.
Referenced by set_fields_for_psf::set_field_4_iso().
set_field_on_edge_psf()
subroutine set_nodal_field_for_psf::set_field_on_edge_psf (integer(kind = kint), intent(in) nnod, integer(kind = kint), intent(in) nedge, integer(kind = kint), intent(in) nnod_edge, integer(kind = kint), dimension(nedge,nnod_edge), intent(in) ie_edge, integer(kind = kint), intent(in) ncomp, real(kind = kreal), dimension(nnod,ncomp), intent(in) d_nod, integer(kind = kint), intent(in) ishift, integer(kind = kint), intent(in) nnod_on_edge, integer(kind = kint), dimension(0:np_smp), intent(in) istack_n_on_e_smp, integer(kind = kint), dimension(nnod_on_edge), intent(in) iedge_4_nod, real(kind= kreal), dimension(nnod_on_edge,2), intent(in) coef_on_edge, integer(kind = kint), intent(in) nnod_patch, real(kind = kreal), dimension(nnod_patch,ncomp), intent(inout) dat_tmp)
Definition at line 146 of file set_nodal_field_for_psf.f90.
Referenced by set_field_on_psf_xyz(), and set_position_on_edge_psf().
set_field_on_psf_xyz()
subroutine set_nodal_field_for_psf::set_field_on_psf_xyz (integer(kind = kint), intent(in) nnod, integer(kind = kint), intent(in) nedge, integer(kind = kint), intent(in) nnod_edge, integer(kind = kint), dimension(nedge,nnod_edge), intent(in) ie_edge, integer(kind = kint), intent(in) nnod_patch, integer(kind = kint), intent(in) num_fld, integer(kind = kint), intent(in) ntot_comp, integer(kind = kint), dimension(0:num_fld), intent(in) istack_comp_nod, real(kind = kreal), dimension(nnod,ntot_comp), intent(in) d_nod, integer(kind = kint), intent(in) ifield_psf, integer(kind = kint), intent(in) ncomp, real(kind = kreal), dimension(nnod_patch,6), intent(inout) dat_tmp, type(sectioning_list), intent(in) psf_list)
Definition at line 191 of file set_nodal_field_for_psf.f90.
References set_field_on_edge_psf().
Referenced by set_fields_for_psf::set_field_on_psf().
set_position_4_psf()
subroutine set_nodal_field_for_psf::set_position_4_psf (integer(kind = kint), intent(in) nnod, integer(kind = kint), intent(in) nedge, integer(kind = kint), intent(in) nnod_edge, integer(kind = kint), dimension(nedge,nnod_edge), intent(in) ie_edge, real(kind = kreal), dimension(nnod,3), intent(in) xx, integer(kind = kint_gl), intent(in) istack_intnod, integer(kind = kint), intent(in) nnod_patch, integer(kind = kint_gl), dimension(nnod_patch), intent(inout) inod_sum, real(kind = kreal), dimension(nnod_patch,3), intent(inout) xx_patch, type(sectioning_list), intent(in) psf_list)
Definition at line 64 of file set_nodal_field_for_psf.f90.
References m_constants::izero, and set_position_on_edge_psf().
Referenced by set_nodes_for_psf::set_nodes_4_iso(), and set_nodes_for_psf::set_nodes_4_psf().
set_position_on_edge_psf()
subroutine set_nodal_field_for_psf::set_position_on_edge_psf (integer(kind = kint), intent(in) nnod, integer(kind = kint), intent(in) nedge, integer(kind = kint), intent(in) nnod_edge, integer(kind = kint), dimension(nedge,nnod_edge), intent(in) ie_edge, real(kind = kreal), dimension(nnod,3), intent(in) xx, integer(kind = kint), intent(in) ishift, integer(kind = kint), intent(in) nnod_on_edge, integer(kind = kint), dimension(0:np_smp), intent(in) istack_n_on_e_smp, integer(kind = kint), dimension(nnod_on_edge), intent(in) iedge_4_nod, real(kind= kreal), dimension(nnod_on_edge,2), intent(in) coef_on_edge, integer(kind = kint_gl), intent(in) istack_intnod, integer(kind = kint), intent(in) nnod_patch, integer(kind = kint_gl), dimension(nnod_patch), intent(inout) inod_sum, real(kind = kreal), dimension(nnod_patch,3), intent(inout) xx_patch)
Definition at line 103 of file set_nodal_field_for_psf.f90.
References m_constants::ithree, and set_field_on_edge_psf().
Referenced by set_position_4_psf().