CALYPSO: t_control_data_sections Module Reference
t_control_data_sections Module Reference
control data for cross sections
Data Types
type section_controls
Functions/Subroutines
subroutine alloc_psf_ctl_stract (psf_ctls)
subroutine dealloc_psf_ctl_stract (psf_ctls)
subroutine read_files_4_psf_ctl (id_control, hd_block, psf_ctls, c_buf)
subroutine bcast_files_4_psf_ctl (psf_ctls)
subroutine, private append_new_section_control (psf_ctls)
subroutine, private dup_control_4_psfs (num_psf, org_psf_ctls, new_psf_ctls)
subroutine, private dealloc_cont_dat_4_psfs (num_psf, psf_c)
subroutine read_control_4_psf_file (id_control, fname_psf_ctl, psf_ctl_struct)
Variables
character(len=kchara), parameter, private hd_section_ctl = 'cross_section_ctl'
character(len=kchara), parameter, private hd_psf_ctl = 'surface_rendering'
Detailed Description
control data for cross sections
      subroutine alloc_psf_ctl_stract(psf_ctls)
      subroutine dealloc_psf_ctl_stract(psf_ctls)
      subroutine read_files_4_psf_ctl                                 &
     &         (id_control, hd_block, psf_ctls, c_buf)
      subroutine bcast_files_4_psf_ctl(psf_ctls)
        type(section_controls), intent(inout) :: psf_ctls
      subroutine read_control_4_psf_file                              &
     &         (id_control, fname_psf_ctl, psf_ctl_struct)
    array cross_section_ctl  1
      file   cross_section_ctl   'ctl_psf_eq'
    end array cross_section_ctl
Function/Subroutine Documentation
alloc_psf_ctl_stract()
subroutine t_control_data_sections::alloc_psf_ctl_stract (type(section_controls), intent(inout) psf_ctls)
Definition at line 59 of file t_control_data_sections.f90.
References t_control_data_4_psf::init_psf_ctl_stract().
Referenced by append_new_section_control(), bcast_files_4_psf_ctl(), read_files_4_psf_ctl(), and t_control_data_dynamo_vizs::read_single_section_ctl().
append_new_section_control()
subroutine, private t_control_data_sections::append_new_section_control (type(section_controls), intent(inout) psf_ctls) private
Definition at line 166 of file t_control_data_sections.f90.
References alloc_psf_ctl_stract(), dealloc_cont_dat_4_psfs(), dealloc_psf_ctl_stract(), and dup_control_4_psfs().
Referenced by read_files_4_psf_ctl().
bcast_files_4_psf_ctl()
subroutine t_control_data_sections::bcast_files_4_psf_ctl (type(section_controls), intent(inout) psf_ctls)
Definition at line 138 of file t_control_data_sections.f90.
References alloc_psf_ctl_stract(), t_control_data_4_psf::bcast_psf_control_data(), calypso_mpi_char::calypso_mpi_bcast_character(), calypso_mpi_int::calypso_mpi_bcast_one_int(), transfer_to_long_integers::cast_long(), m_precision::kchara, and calypso_mpi::my_rank.
Referenced by t_control_data_dynamo_vizs::bcast_dynamo_viz_control(), and t_control_data_surfacings::bcast_surfacing_controls().
dealloc_cont_dat_4_psfs()
subroutine, private t_control_data_sections::dealloc_cont_dat_4_psfs (integer(kind = kint), intent(in) num_psf, type(psf_ctl), dimension(num_psf), intent(inout) psf_c) private
Definition at line 215 of file t_control_data_sections.f90.
References t_control_data_4_psf::dealloc_cont_dat_4_psf().
Referenced by append_new_section_control().
dealloc_psf_ctl_stract()
subroutine t_control_data_sections::dealloc_psf_ctl_stract (type(section_controls), intent(inout) psf_ctls)
Definition at line 77 of file t_control_data_sections.f90.
Referenced by append_new_section_control(), t_control_data_surfacings::dealloc_surfacing_controls(), and set_psf_iso_control::set_psf_control().
dup_control_4_psfs()
subroutine, private t_control_data_sections::dup_control_4_psfs (integer(kind = kint), intent(in) num_psf, type(section_controls), intent(in) org_psf_ctls, type(section_controls), intent(inout) new_psf_ctls) private
Definition at line 196 of file t_control_data_sections.f90.
References t_control_data_4_psf::dup_control_4_psf().
Referenced by append_new_section_control().
read_control_4_psf_file()
subroutine t_control_data_sections::read_control_4_psf_file (integer(kind = kint), intent(in) id_control, character(len = kchara), intent(in) fname_psf_ctl, type(psf_ctl), intent(inout) psf_ctl_struct)
Definition at line 230 of file t_control_data_sections.f90.
References hd_psf_ctl, hd_section_ctl, t_read_control_elements::load_one_line_from_control(), and t_control_data_4_psf::read_psf_control_data().
Referenced by read_files_4_psf_ctl(), and t_control_data_dynamo_vizs::read_single_section_ctl().
read_files_4_psf_ctl()
subroutine t_control_data_sections::read_files_4_psf_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(section_controls), intent(inout) psf_ctls, type(buffer_for_control), intent(inout) c_buf)
Definition at line 92 of file t_control_data_sections.f90.
References alloc_psf_ctl_stract(), append_new_section_control(), t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_array_flag(), t_read_control_elements::check_file_flag(), t_read_control_elements::load_one_line_from_control(), read_control_4_psf_file(), t_control_data_4_psf::read_psf_control_data(), and t_read_control_elements::third_word().
Referenced by t_control_data_surfacings::read_surfacing_controls().
Variable Documentation
hd_psf_ctl
character(len=kchara), parameter, private t_control_data_sections::hd_psf_ctl = 'surface_rendering' private
Definition at line 49 of file t_control_data_sections.f90.
Referenced by read_control_4_psf_file().
hd_section_ctl
character(len=kchara), parameter, private t_control_data_sections::hd_section_ctl = 'cross_section_ctl' private
Definition at line 46 of file t_control_data_sections.f90.
Referenced by read_control_4_psf_file(), t_control_data_surfacings::read_surfacing_controls(), and t_control_data_surfacings::set_label_surfacings().