CALYPSO: t_energy_label_parameters Module Reference
t_energy_label_parameters Module Reference
Mean sqare data.
Data Types
type energy_label_param
Structure of label for energies.
Functions/Subroutines
subroutine init_energy_labels_base (ene_labels)
subroutine alloc_energy_labels (ene_labels)
subroutine dealloc_energy_labels (ene_labels)
subroutine set_sph_rms_labels (ene_labels, num_rms_comp, rms_name, labels)
subroutine, private set_sph_energy_labels (rms_name, ene_labels, labels, flag)
Variables
integer(kind=kint), parameter, private n_fld_ene = 2
character(len=kchara), dimension(2), parameter, private ene_lebel_base = (/'K_ene ', 'M_ene '/)
Detailed Description
Mean sqare data.
      subroutine init_energy_labels_base(ene_labels)
      subroutine alloc_energy_labels(ene_labels)
      subroutine dealloc_energy_labels(ene_labels)
        type(energy_label_param), intent(inout) :: ene_labels
      subroutine set_sph_rms_labels                                   &
     &         (ene_labels, num_rms_comp, rms_name, labels)
        type(energy_label_param), intent(in) :: ene_labels
Function/Subroutine Documentation
alloc_energy_labels()
subroutine t_energy_label_parameters::alloc_energy_labels (type(energy_label_param), intent(inout) ene_labels)
Definition at line 77 of file t_energy_label_parameters.f90.
Referenced by init_energy_labels_base().
dealloc_energy_labels()
subroutine t_energy_label_parameters::dealloc_energy_labels (type(energy_label_param), intent(inout) ene_labels)
Definition at line 88 of file t_energy_label_parameters.f90.
init_energy_labels_base()
subroutine t_energy_label_parameters::init_energy_labels_base (type(energy_label_param), intent(inout) ene_labels)
Definition at line 52 of file t_energy_label_parameters.f90.
References add_direction_labels::add_vector_power_sph_label(), alloc_energy_labels(), ene_lebel_base, m_base_field_labels::magnetic_field, n_fld_ene, and m_base_field_labels::velocity.
Referenced by t_sph_mhd_monitor_data_io::init_rms_4_sph_spectr_4_mhd().
set_sph_energy_labels()
subroutine, private t_energy_label_parameters::set_sph_energy_labels (character(len = kchara), intent(in) rms_name, type(energy_label_param), intent(in) ene_labels, character(len = kchara), dimension(3), intent(inout) labels, logical, intent(inout) flag) private
Definition at line 133 of file t_energy_label_parameters.f90.
Referenced by set_sph_rms_labels().
set_sph_rms_labels()
subroutine t_energy_label_parameters::set_sph_rms_labels (type(energy_label_param), intent(in) ene_labels, integer(kind = kint), intent(in) num_rms_comp, character(len = kchara), intent(in) rms_name, character(len = kchara), dimension(num_rms_comp), intent(inout) labels)
Definition at line 99 of file t_energy_label_parameters.f90.
References add_direction_labels::add_tensor_direction_label_rtp(), add_direction_labels::add_vector_power_sph_label(), and set_sph_energy_labels().
Referenced by sph_mean_spectr_header_io::check_sph_vol_mean_sq_header(), sph_mean_spectr_header_io::set_sph_rms_labels_4_monitor(), sph_mean_spectr_header_io::write_sph_mean_sq_header(), and sph_mean_spectr_header_io::write_sph_vol_mean_sq_header().
Variable Documentation
ene_lebel_base
character(len=kchara), dimension(2), parameter, private t_energy_label_parameters::ene_lebel_base = (/'K_ene ', 'M_ene '/) private
Definition at line 33 of file t_energy_label_parameters.f90.
Referenced by init_energy_labels_base().
n_fld_ene
integer(kind = kint), parameter, private t_energy_label_parameters::n_fld_ene = 2 private
Definition at line 32 of file t_energy_label_parameters.f90.
Referenced by init_energy_labels_base().