CALYPSO: cvt_sph_tensor_2_xyz_smp Module Reference
cvt_sph_tensor_2_xyz_smp Module Reference
Functions/Subroutines
subroutine cal_xyz_tensor_by_sph_smp (np_smp, numnod, inod_smp_stack, tensor, txyz, xx, yy, zz, r, s, a_r, a_s)
subroutine overwrite_xyz_tensor_by_sph_smp (np_smp, numnod, inod_smp_stack, tensor, xx, yy, zz, r, s, a_r, a_s)
subroutine cal_xx_tensor_by_sph_smp (np_smp, numnod, inod_smp_stack, tensor, t_xx, xx, yy, zz, r, s, a_r, a_s)
subroutine cal_xy_tensor_by_sph_smp (np_smp, numnod, inod_smp_stack, tensor, t_xy, xx, yy, zz, r, s, a_r, a_s)
subroutine cal_xz_tensor_by_sph_smp (np_smp, numnod, inod_smp_stack, tensor, t_xz, xx, yy, zz, r, s, a_r, a_s)
subroutine cal_yy_tensor_by_sph_smp (np_smp, numnod, inod_smp_stack, tensor, t_yy, xx, yy, zz, r, s, a_r, a_s)
subroutine cal_yz_tensor_by_sph_smp (np_smp, numnod, inod_smp_stack, tensor, t_yz, xx, yy, zz, r, s, a_r, a_s)
subroutine cal_zz_tensor_by_sph_smp (np_smp, numnod, inod_smp_stack, tensor, t_zz, xx, zz, r, s, a_r)
Function/Subroutine Documentation
cal_xx_tensor_by_sph_smp()
subroutine cvt_sph_tensor_2_xyz_smp::cal_xx_tensor_by_sph_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,6), intent(in) tensor, real(kind=kreal), dimension(numnod), intent(inout) t_xx, real(kind=kreal), dimension(numnod), intent(in) xx, real(kind=kreal), dimension(numnod), intent(in) yy, real(kind=kreal), dimension(numnod), intent(in) zz, real(kind=kreal), dimension(numnod), intent(in) r, real(kind=kreal), dimension(numnod), intent(in) s, real(kind=kreal), dimension(numnod), intent(in) a_r, real(kind=kreal), dimension(numnod), intent(in) a_s)
Definition at line 331 of file cvt_sph_tensor_2_xyz_smp.f90.
References m_constants::two.
cal_xy_tensor_by_sph_smp()
subroutine cvt_sph_tensor_2_xyz_smp::cal_xy_tensor_by_sph_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,6), intent(in) tensor, real(kind=kreal), dimension(numnod), intent(inout) t_xy, real(kind=kreal), dimension(numnod), intent(in) xx, real(kind=kreal), dimension(numnod), intent(in) yy, real(kind=kreal), dimension(numnod), intent(in) zz, real(kind=kreal), dimension(numnod), intent(in) r, real(kind=kreal), dimension(numnod), intent(in) s, real(kind=kreal), dimension(numnod), intent(in) a_r, real(kind=kreal), dimension(numnod), intent(in) a_s)
Definition at line 388 of file cvt_sph_tensor_2_xyz_smp.f90.
cal_xyz_tensor_by_sph_smp()
subroutine cvt_sph_tensor_2_xyz_smp::cal_xyz_tensor_by_sph_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,6), intent(in) tensor, real(kind=kreal), dimension(numnod,6), intent(inout) txyz, real(kind=kreal), dimension(numnod), intent(in) xx, real(kind=kreal), dimension(numnod), intent(in) yy, real(kind=kreal), dimension(numnod), intent(in) zz, real(kind=kreal), dimension(numnod), intent(in) r, real(kind=kreal), dimension(numnod), intent(in) s, real(kind=kreal), dimension(numnod), intent(in) a_r, real(kind=kreal), dimension(numnod), intent(in) a_s)
Definition at line 99 of file cvt_sph_tensor_2_xyz_smp.f90.
References m_constants::two.
Referenced by cvt_nodal_and_sph_field::cvt_sph_tsr_to_nod_tsr().
cal_xz_tensor_by_sph_smp()
subroutine cvt_sph_tensor_2_xyz_smp::cal_xz_tensor_by_sph_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,6), intent(in) tensor, real(kind=kreal), dimension(numnod), intent(inout) t_xz, real(kind=kreal), dimension(numnod), intent(in) xx, real(kind=kreal), dimension(numnod), intent(in) yy, real(kind=kreal), dimension(numnod), intent(in) zz, real(kind=kreal), dimension(numnod), intent(in) r, real(kind=kreal), dimension(numnod), intent(in) s, real(kind=kreal), dimension(numnod), intent(in) a_r, real(kind=kreal), dimension(numnod), intent(in) a_s)
Definition at line 447 of file cvt_sph_tensor_2_xyz_smp.f90.
cal_yy_tensor_by_sph_smp()
subroutine cvt_sph_tensor_2_xyz_smp::cal_yy_tensor_by_sph_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,6), intent(in) tensor, real(kind=kreal), dimension(numnod), intent(inout) t_yy, real(kind=kreal), dimension(numnod), intent(in) xx, real(kind=kreal), dimension(numnod), intent(in) yy, real(kind=kreal), dimension(numnod), intent(in) zz, real(kind=kreal), dimension(numnod), intent(in) r, real(kind=kreal), dimension(numnod), intent(in) s, real(kind=kreal), dimension(numnod), intent(in) a_r, real(kind=kreal), dimension(numnod), intent(in) a_s)
Definition at line 503 of file cvt_sph_tensor_2_xyz_smp.f90.
References m_constants::two.
cal_yz_tensor_by_sph_smp()
subroutine cvt_sph_tensor_2_xyz_smp::cal_yz_tensor_by_sph_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,6), intent(in) tensor, real(kind=kreal), dimension(numnod), intent(inout) t_yz, real(kind=kreal), dimension(numnod), intent(in) xx, real(kind=kreal), dimension(numnod), intent(in) yy, real(kind=kreal), dimension(numnod), intent(in) zz, real(kind=kreal), dimension(numnod), intent(in) r, real(kind=kreal), dimension(numnod), intent(in) s, real(kind=kreal), dimension(numnod), intent(in) a_r, real(kind=kreal), dimension(numnod), intent(in) a_s)
Definition at line 560 of file cvt_sph_tensor_2_xyz_smp.f90.
cal_zz_tensor_by_sph_smp()
subroutine cvt_sph_tensor_2_xyz_smp::cal_zz_tensor_by_sph_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,6), intent(in) tensor, real(kind=kreal), dimension(numnod), intent(inout) t_zz, real(kind=kreal), dimension(numnod), intent(in) xx, real(kind=kreal), dimension(numnod), intent(in) zz, real(kind=kreal), dimension(numnod), intent(in) r, real(kind=kreal), dimension(numnod), intent(in) s, real(kind=kreal), dimension(numnod), intent(in) a_r)
Definition at line 615 of file cvt_sph_tensor_2_xyz_smp.f90.
References m_constants::two.
overwrite_xyz_tensor_by_sph_smp()
subroutine cvt_sph_tensor_2_xyz_smp::overwrite_xyz_tensor_by_sph_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,6), intent(inout) tensor, real(kind=kreal), dimension(numnod), intent(in) xx, real(kind=kreal), dimension(numnod), intent(in) yy, real(kind=kreal), dimension(numnod), intent(in) zz, real(kind=kreal), dimension(numnod), intent(in) r, real(kind=kreal), dimension(numnod), intent(in) s, real(kind=kreal), dimension(numnod), intent(in) a_r, real(kind=kreal), dimension(numnod), intent(in) a_s)
Definition at line 216 of file cvt_sph_tensor_2_xyz_smp.f90.
References m_constants::two.
Referenced by copy_nodal_fld_4_sph_trans::copy_nod_tsr_from_trans_wpole(), and coordinate_convert_4_sph::overwrite_nodal_sph_2_xyz_smp().