CALYPSO: set_sph_local_element Module Reference
set_sph_local_element Module Reference
Functions/Subroutines
subroutine count_local_elements_sph_mesh (ip_r, ip_t, sph_params, stbl, ele)
subroutine set_local_elements_sph_mesh (ip_r, ip_t, sph_params, stbl, ele)
Function/Subroutine Documentation
count_local_elements_sph_mesh()
subroutine set_sph_local_element::count_local_elements_sph_mesh (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, type(sph_shell_parameters), intent(in) sph_params, type(comm_table_make_sph), intent(in) stbl, type(element_data), intent(inout) ele)
Definition at line 31 of file set_sph_local_element.f90.
References cal_sph_ele_addresses::cal_sph_local_numele(), m_geometry_constants::num_t_linear, cal_sph_ele_addresses::reset_local_sph_ele_constants(), cal_sph_ele_addresses::set_nele_center_npole(), cal_sph_ele_addresses::set_nele_center_spole(), cal_sph_ele_addresses::set_nele_ext_ctr_sph(), cal_sph_ele_addresses::set_nele_gl_ctr_sph(), cal_sph_ele_addresses::set_nele_gl_npole(), cal_sph_ele_addresses::set_nele_gl_shell(), cal_sph_ele_addresses::set_nele_gl_spole(), cal_sph_ele_addresses::set_nele_lc_ctr_sph(), cal_sph_ele_addresses::set_nele_lc_npole(), cal_sph_ele_addresses::set_nele_lc_shell(), and cal_sph_ele_addresses::set_nele_lc_spole().
Referenced by set_fem_mesh_4_sph::const_fem_geometry_for_sph().
set_local_elements_sph_mesh()
subroutine set_sph_local_element::set_local_elements_sph_mesh (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, type(sph_shell_parameters), intent(in) sph_params, type(comm_table_make_sph), intent(in) stbl, type(element_data), intent(inout) ele)
Definition at line 95 of file set_sph_local_element.f90.
References cal_sph_ele_connects::set_exter_center_n_pole_ele(), cal_sph_ele_connects::set_exter_center_shell_ele(), cal_sph_ele_connects::set_inter_center_n_pole_ele(), cal_sph_ele_connects::set_inter_center_s_pole_ele(), cal_sph_ele_connects::set_inter_center_shell_ele(), cal_sph_ele_connects::set_north_pole_element(), cal_sph_ele_connects::set_south_pole_element(), and cal_sph_ele_connects::set_spherical_shell_element().
Referenced by set_fem_mesh_4_sph::const_fem_geometry_for_sph().