CALYPSO: cal_nonlinear_sph_mhd Module Reference
cal_nonlinear_sph_mhd Module Reference
Evaluate nonlinear terms in spherical coordinate grid.
Functions/Subroutines
subroutine nonlinear_terms_in_rtp (sph_rtp, MHD_prop, leg, b_trns_base, f_trns_frc, trns_b_MHD, trns_f_MHD)
subroutine cal_nonlinear_pole_mhd (sph_rtp, MHD_prop, b_trns_base, f_trns_frc, trns_b_snap, trns_f_MHD)
subroutine nonlinear_terms_on_node (MHD_prop, b_trns_base, f_trns_frc, nnod, ntot_comp_fld, fld_rtp, ntot_comp_frc, frc_rtp)
subroutine add_ref_advect_sph_mhd (sph_rj, sph_MHD_bc, MHD_prop, leg, ref_temp, ref_comp, ipol, rj_fld)
subroutine, private add_reference_advect_sph (sph_bc_S, property, ref_param_S, nidx_rj, ar_1d_rj, g_sph_rj, is_h_advect, is_velo, reftemp_rj, rj_fld)
Detailed Description
Evaluate nonlinear terms in spherical coordinate grid.
      subroutine nonlinear_terms_in_rtp(sph_rtp, MHD_prop, leg,       &
     &          b_trns_base, f_trns_frc, trns_b_MHD, trns_f_MHD)
       Input ::  trns_b_MHD%fld_rtp(1,ib_fld)
               ib_fld = i_velo, base%i_vort,
                        base%i_magne, base%i_current,
                        base%i_temp, base%i_light
       Output :: trns_f_MHD%fld_rtp(1,if_frc)
               if_frc = forces%i_m_advect, forces%i_lorentz,
                        forces%i_vp_induct, forces%i_h_flux,
                        forces%i_c_flux, forces%i_coriolis
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(MHD_evolution_param), intent(in) :: MHD_prop
        type(legendre_4_sph_trans), intent(in) :: leg
        type(base_field_address), intent(in) :: b_trns_base
        type(base_force_address), intent(in) :: f_trns_frc
        type(spherical_transform_data), intent(in) :: trns_b_MHD
        type(spherical_transform_data), intent(inout) :: trns_f_MHD
      subroutine cal_nonlinear_pole_MHD(sph_rtp, MHD_prop,            &
     &          b_trns_base, f_trns_frc, trns_b_snap, trns_f_MHD)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(MHD_evolution_param), intent(in) :: MHD_prop
        type(base_field_address), intent(in) :: b_trns_base
        type(base_force_address), intent(in) :: f_trns_frc
        type(spherical_transform_data), intent(in) :: trns_b_snap
        type(spherical_transform_data), intent(inout) :: trns_f_MHD
      subroutine nonlinear_terms_on_node                              &
     &         (MHD_prop, b_trns_base, f_trns_frc,                    &
     &          nnod, ntot_comp_fld, fld_rtp, ntot_comp_frc, frc_rtp)
        type(MHD_evolution_param), intent(in) :: MHD_prop
        type(base_field_address), intent(in) :: b_trns_base
        type(base_force_address), intent(in) :: f_trns_frc
      subroutine add_ref_advect_sph_MHD(sph_rj, sph_MHD_bc, MHD_prop, &
     &          leg, ref_temp, ref_comp, ipol, rj_fld)
       Input ::  rj_fld(1,is_fld)
               is_fld = i_velo, forces%i_h_advect, forces%i_c_advect
       Output :: rj_fld(1,is_fld)
               is_fld = forces%i_h_advect, forces%i_c_advect
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(MHD_evolution_param), intent(in) :: MHD_prop
        type(sph_MHD_boundary_data), intent(in) :: sph_MHD_bc
        type(legendre_4_sph_trans), intent(in) :: leg
        type(phys_address), intent(in) :: ipol
        type(reference_field), intent(in) :: ref_temp
        type(reference_field), intent(in) :: ref_comp
        type(phys_data), intent(inout) :: rj_fld
      subroutine add_reference_advect_sph                             &
     &         (kr_in, kr_out, nidx_rj, ar_1d_rj, g_sph_rj,           &
     &          coef_advect, is_h_advect, is_velo,                    &
     &          nnod_rj, ntot_phys_rj, reftemp_rj, d_rj)
Parameters
kr_in Radial ID for inner boundary
kr_out Radial ID for outer boundary
Function/Subroutine Documentation
add_ref_advect_sph_mhd()
subroutine cal_nonlinear_sph_mhd::add_ref_advect_sph_mhd (type(sph_rj_grid), intent(in) sph_rj, type(sph_mhd_boundary_data), intent(in) sph_MHD_bc, type(mhd_evolution_param), intent(in) MHD_prop, type(legendre_4_sph_trans), intent(in) leg, type(reference_field), intent(in) ref_temp, type(reference_field), intent(in) ref_comp, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld)
Definition at line 220 of file cal_nonlinear_sph_MHD.f90.
References add_reference_advect_sph().
Referenced by cal_nonlinear::licv_exp(), and cal_nonlinear::nonlinear().
add_reference_advect_sph()
subroutine, private cal_nonlinear_sph_mhd::add_reference_advect_sph (type(sph_boundary_type), intent(in) sph_bc_S, type(scalar_property), intent(in) property, type(reference_scalar_param), intent(in) ref_param_S, integer(kind = kint), dimension(2), intent(in) nidx_rj, real(kind = kreal), dimension(nidx_rj(1),3), intent(in) ar_1d_rj, real(kind = kreal), dimension(nidx_rj(2),13), intent(in) g_sph_rj, integer(kind = kint), intent(in) is_h_advect, integer(kind = kint), intent(in) is_velo, real(kind = kreal), dimension(nidx_rj(1),0:2), intent(in) reftemp_rj, type(phys_data), intent(inout) rj_fld) private
Definition at line 252 of file cal_nonlinear_sph_MHD.f90.
References t_reference_scalar_param::id_sphere_ref_temp.
Referenced by add_ref_advect_sph_mhd().
cal_nonlinear_pole_mhd()
subroutine cal_nonlinear_sph_mhd::cal_nonlinear_pole_mhd (type(sph_rtp_grid), intent(in) sph_rtp, type(mhd_evolution_param), intent(in) MHD_prop, type(base_field_address), intent(in) b_trns_base, type(base_force_address), intent(in) f_trns_frc, type(spherical_transform_data), intent(in) trns_b_snap, type(spherical_transform_data), intent(inout) trns_f_MHD)
Definition at line 125 of file cal_nonlinear_sph_MHD.f90.
References const_wz_coriolis_rtp::cal_wz_coriolis_pole(), and nonlinear_terms_on_node().
Referenced by lead_fields_4_sph_mhd::lead_fields_by_sph_trans().
nonlinear_terms_in_rtp()
subroutine cal_nonlinear_sph_mhd::nonlinear_terms_in_rtp (type(sph_rtp_grid), intent(in) sph_rtp, type(mhd_evolution_param), intent(in) MHD_prop, type(legendre_4_sph_trans), intent(in) leg, type(base_field_address), intent(in) b_trns_base, type(base_force_address), intent(in) f_trns_frc, type(spherical_transform_data), intent(in) trns_b_MHD, type(spherical_transform_data), intent(inout) trns_f_MHD)
Definition at line 94 of file cal_nonlinear_sph_MHD.f90.
References nonlinear_terms_on_node(), and const_wz_coriolis_rtp::sel_wz_coriolis_rtp().
Referenced by cal_nonlinear::nonlinear_by_pseudo_sph().
nonlinear_terms_on_node()
subroutine cal_nonlinear_sph_mhd::nonlinear_terms_on_node (type(mhd_evolution_param), intent(in) MHD_prop, type(base_field_address), intent(in) b_trns_base, type(base_force_address), intent(in) f_trns_frc, integer(kind = kint), intent(in) nnod, integer(kind = kint), intent(in) ntot_comp_fld, real(kind = kreal), dimension(nnod,ntot_comp_fld), intent(in) fld_rtp, integer(kind = kint), intent(in) ntot_comp_frc, real(kind = kreal), dimension(nnod,ntot_comp_frc), intent(inout) frc_rtp)
Definition at line 156 of file cal_nonlinear_sph_MHD.f90.
References cal_products_smp::cal_cross_prod_w_coef_smp(), and cal_products_smp::cal_vec_scalar_prod_w_coef_smp().
Referenced by cal_nonlinear_pole_mhd(), and nonlinear_terms_in_rtp().