CALYPSO: cal_tave_sph_ene_spectr Module Reference
cal_tave_sph_ene_spectr Module Reference
Evaluate time average spherical harmonics spectrum data.
Functions/Subroutines
subroutine sum_average_ene_spectr (time_sph, pre_time, nri_sph, ltr_sph, ncomp, spectr_l, ave_spec_l, spectr_pre_l)
subroutine sum_deviation_ene_spectr (time_sph, pre_time, nri_sph, ltr_sph, ncomp, spectr_l, ave_spec_l, sigma_spec_l, spectr_pre_l)
subroutine copy_ene_spectr_2_pre (time_sph, pre_time, nri_sph, ltr_sph, ncomp, spectr_l, ave_spec_l, spectr_pre_l)
subroutine copy_deviation_ene_2_pre (time_sph, pre_time, nri_sph, ltr_sph, ncomp, spectr_l, ave_spec_l, sigma_spec_l, spectr_pre_l)
subroutine divide_average_ene_spectr (time_sph, time_ini, nri_sph, ltr_sph, ncomp, ave_spec_l, spectr_IO)
subroutine divide_deviation_ene_spectr (time_sph, time_ini, nri_sph, ltr_sph, ncomp, sigma_spec_l, spectr_IO)
Detailed Description
Evaluate time average spherical harmonics spectrum data.
      subroutine sum_average_ene_spectr                               &
     &         (time_sph, pre_time, nri_sph, ltr_sph, ncomp, spectr_l,&
     &          ave_spec_l, spectr_pre_l)
      subroutine sum_deviation_ene_spectr(time_sph, pre_time,         &
     &          nri_sph, ltr_sph, ncomp, spectr_l, ave_spec_l,        &
     &          sigma_spec_l, spectr_pre_l)
      subroutine copy_ene_spectr_2_pre                                &
     &         (time_sph, pre_time, nri_sph, ltr_sph, ncomp, spectr_l,&
     &          ave_spec_l, spectr_pre_l)
      subroutine copy_deviation_ene_2_pre(time_sph, pre_time,         &
     &          nri_sph, ltr_sph, ncomp, spectr_l, ave_spec_l,        &
     &          sigma_spec_l, spectr_pre_l)
      subroutine divide_average_ene_spectr(time_sph, time_ini,        &
     &          nri_sph, ltr_sph, ncomp, ave_spec_l, spectr_IO)
      subroutine divide_deviation_ene_spectr(time_sph, time_ini,      &
     &          nri_sph, ltr_sph, ncomp, sigma_spec_l, spectr_IO)
Parameters
istep time step number
icou counter for snapshots
ierr error flag
Function/Subroutine Documentation
copy_deviation_ene_2_pre()
subroutine cal_tave_sph_ene_spectr::copy_deviation_ene_2_pre (real(kind = kreal), intent(in) time_sph, real(kind = kreal), intent(inout) pre_time, integer(kind = kint), intent(in) nri_sph, integer(kind = kint), intent(in) ltr_sph, integer(kind = kint), intent(in) ncomp, real(kind = kreal), dimension(ncomp, 0:ltr_sph, nri_sph), intent(in) spectr_l, real(kind = kreal), dimension(ncomp, 0:ltr_sph, nri_sph), intent(in) ave_spec_l, real(kind = kreal), dimension(ncomp, 0:ltr_sph, nri_sph), intent(inout) sigma_spec_l, real(kind = kreal), dimension(ncomp, 0:ltr_sph, nri_sph), intent(inout) spectr_pre_l)
Definition at line 176 of file cal_tave_sph_ene_spectr.f90.
Referenced by m_tave_sph_ene_spectr::sph_spectr_std_deviation().
copy_ene_spectr_2_pre()
subroutine cal_tave_sph_ene_spectr::copy_ene_spectr_2_pre (real(kind = kreal), intent(in) time_sph, real(kind = kreal), intent(inout) pre_time, integer(kind = kint), intent(in) nri_sph, integer(kind = kint), intent(in) ltr_sph, integer(kind = kint), intent(in) ncomp, real(kind = kreal), dimension(ncomp, 0:ltr_sph, nri_sph), intent(in) spectr_l, real(kind = kreal), dimension(ncomp, 0:ltr_sph, nri_sph), intent(inout) ave_spec_l, real(kind = kreal), dimension(ncomp, 0:ltr_sph, nri_sph), intent(inout) spectr_pre_l)
Definition at line 137 of file cal_tave_sph_ene_spectr.f90.
Referenced by m_tave_sph_ene_spectr::sph_spectr_average().
divide_average_ene_spectr()
subroutine cal_tave_sph_ene_spectr::divide_average_ene_spectr (real(kind = kreal), intent(in) time_sph, real(kind = kreal), intent(in) time_ini, integer(kind = kint), intent(in) nri_sph, integer(kind = kint), intent(in) ltr_sph, integer(kind = kint), intent(in) ncomp, real(kind = kreal), dimension(ncomp, 0:ltr_sph, nri_sph), intent(in) ave_spec_l, real(kind = kreal), dimension(ncomp, 0:ltr_sph, nri_sph), intent(inout) spectr_IO)
Definition at line 220 of file cal_tave_sph_ene_spectr.f90.
Referenced by m_tave_sph_ene_spectr::sph_spectr_average().
divide_deviation_ene_spectr()
subroutine cal_tave_sph_ene_spectr::divide_deviation_ene_spectr (real(kind = kreal), intent(in) time_sph, real(kind = kreal), intent(in) time_ini, integer(kind = kint), intent(in) nri_sph, integer(kind = kint), intent(in) ltr_sph, integer(kind = kint), intent(in) ncomp, real(kind = kreal), dimension(ncomp, 0:ltr_sph, nri_sph), intent(in) sigma_spec_l, real(kind = kreal), dimension(ncomp, 0:ltr_sph, nri_sph), intent(inout) spectr_IO)
Definition at line 243 of file cal_tave_sph_ene_spectr.f90.
Referenced by m_tave_sph_ene_spectr::sph_spectr_std_deviation().
sum_average_ene_spectr()
subroutine cal_tave_sph_ene_spectr::sum_average_ene_spectr (real(kind = kreal), intent(in) time_sph, real(kind = kreal), intent(inout) pre_time, integer(kind = kint), intent(in) nri_sph, integer(kind = kint), intent(in) ltr_sph, integer(kind = kint), intent(in) ncomp, real(kind = kreal), dimension(ncomp, 0:ltr_sph, nri_sph), intent(in) spectr_l, real(kind = kreal), dimension(ncomp, 0:ltr_sph, nri_sph), intent(inout) ave_spec_l, real(kind = kreal), dimension(ncomp, 0:ltr_sph, nri_sph), intent(inout) spectr_pre_l)
Definition at line 48 of file cal_tave_sph_ene_spectr.f90.
References m_constants::half.
Referenced by m_tave_sph_ene_spectr::sph_spectr_average().
sum_deviation_ene_spectr()
subroutine cal_tave_sph_ene_spectr::sum_deviation_ene_spectr (real(kind = kreal), intent(in) time_sph, real(kind = kreal), intent(inout) pre_time, integer(kind = kint), intent(in) nri_sph, integer(kind = kint), intent(in) ltr_sph, integer(kind = kint), intent(in) ncomp, real(kind = kreal), dimension(ncomp, 0:ltr_sph, nri_sph), intent(in) spectr_l, real(kind = kreal), dimension(ncomp, 0:ltr_sph, nri_sph), intent(in) ave_spec_l, real(kind = kreal), dimension(ncomp, 0:ltr_sph, nri_sph), intent(inout) sigma_spec_l, real(kind = kreal), dimension(ncomp, 0:ltr_sph, nri_sph), intent(inout) spectr_pre_l)
Definition at line 91 of file cal_tave_sph_ene_spectr.f90.
References m_constants::half.
Referenced by m_tave_sph_ene_spectr::sph_spectr_std_deviation().