CALYPSO: m_field_product_labels Module Reference
m_field_product_labels Module Reference
Functions/Subroutines
logical function check_field_product_vectors (field_name)
logical function check_field_product_scalars (field_name)
integer(kind=kint) function num_field_products ()
subroutine set_field_product_labels (n_comps, names, maths)
Variables
integer(kind=kint), parameter, private nfid_product = 21
type(field_def), parameter rest_of_geostrophic = field_def(n_comp = n_vector, name = 'rest_of_geostrophic', math = '$ -2 e_{ijk} \Omega_{j} u_{k}' // ' - \partial_{i} p $')
Field label for ageostrophic balance \(-2 e_{ijk} \Omega_{j} u_{k} - \partial_{i} p \).
type(field_def), parameter truncated_magnetic_field = field_def(n_comp = n_vector, name = 'truncated_magnetic_field', math = '$ B_{i} $')
Field label for truncated magnetic field \(B_{i} \).
type(field_def), parameter electric_field = field_def(n_comp = n_vector, name = 'electric_field', math = '$ E_{i} $')
Field label for electric field \(E_{i} \).
type(field_def), parameter poynting_flux = field_def(n_comp = n_vector, name = 'poynting_flux', math = '$ e_{ijk} E_{j} B_{k} $')
Field label for poynting flux \(e_{ijk} E_{j} B_{k} \).
type(field_def), parameter kinetic_helicity = field_def(n_comp = n_scalar, name = 'kinetic_helicity', math = '$ u_{i} \omega_{i} $')
Field label for kinetic helicity \(H_{u} = u_{i} \omega_{i} \).
type(field_def), parameter magnetic_helicity = field_def(n_comp = n_scalar, name = 'magnetic_helicity', math = '$ B_{i} A_{i} $')
Field label for magnetic helicity \(H_{B} = B_{i} A_{i} \).
type(field_def), parameter current_helicity = field_def(n_comp = n_scalar, name = 'current_helicity', math = '$ J_{i} B_{i} $')
Field label for current helicity \(H_{J} = J_{i} B_{i} \).
type(field_def), parameter cross_helicity = field_def(n_comp = n_scalar, name = 'cross_helicity', math = '$ u_{i} B_{i} $')
Field label for cross helicity \(H_{x} = u_{i} B{i} \).
type(field_def), parameter square_velocity = field_def(n_comp = n_vector, name = 'square_velocity', math = '$ u_{i}^{2} $')
Square of velocity \(u_{i}^{2} \).
type(field_def), parameter square_vorticity = field_def(n_comp = n_vector, name = 'square_vorticity', math = '$ \omega_{i}^{2} $')
Square of vorticity \(\omega_{i}^{2} \).
type(field_def), parameter square_magne = field_def(n_comp = n_vector, name = 'square_magne', math = '$ B_{i}^{2} $')
Square of magnetic field \(B_{i}^{2} \).
type(field_def), parameter square_vector_potential = field_def(n_comp = n_vector, name = 'square_vector_potential', math = '$ A_{i}^{2} $')
Square of magnetic vector potential \(A_{i}^{2} \).
type(field_def), parameter square_current = field_def(n_comp = n_vector, name = 'square_current', math = '$ J_{i}^{2} $')
Square of current density \(J_{i}^{2} \).
type(field_def), parameter square_temperature = field_def(n_comp = n_scalar, name = 'square_temperature', math = '$ T^{2} $')
Square of temperature \(T^{2} \).
type(field_def), parameter square_composition = field_def(n_comp = n_scalar, name = 'square_composition', math = '$ C^{2} $')
Square of composition \(C^{2} \).
type(field_def), parameter velocity_scale = field_def(n_comp = n_scalar, name = 'velocity_scale', math = '$ L_{u} $')
Field label for velocity length scale \(L_{u} \).
type(field_def), parameter magnetic_scale = field_def(n_comp = n_scalar, name = 'magnetic_scale', math = '$ L_{B} $')
Field label for magnetic field length scale \(L_{B} \).
type(field_def), parameter temperature_scale = field_def(n_comp = n_scalar, name = 'temperature_scale', math = '$ L_{T} $')
Field label for temperature length scale \(L_{T} \).
type(field_def), parameter composition_scale = field_def(n_comp = n_scalar, name = 'composition_scale', math = '$ L_{C} $')
Field label for composition length scale \(L_{C} \).
type(field_def), parameter stream_pol_velocity = field_def(n_comp = n_vector, name = 'stream_pol_velocity', math = '$ \Psi_{Us} $')
Stream functin for the poloidal velocity \(\Psi_{Us} \).
type(field_def), parameter stream_pol_magne = field_def(n_comp = n_vector, name = 'stream_pol_magne', math = '$ \Phi_{Bs} $')
Stream functin for the poloidal magnetic field \(\Phi_{Bs} \).
type(field_def), parameter geostrophic_balance = field_def(n_comp = n_vector, name = 'geostrophic_balance', math = '$ -2 e_{ijk} \Omega_{j} u_{k}' // ' - \partial_{i} p $')
Field label for ageostrophic balance \(-2 e_{ijk} \Omega_{j} u_{k} - \partial_{i} p \).
Function/Subroutine Documentation
check_field_product_scalars()
logical function m_field_product_labels::check_field_product_scalars (character(len = kchara), intent(in) field_name)
Definition at line 229 of file m_field_product_labels.f90.
References composition_scale, cross_helicity, current_helicity, kinetic_helicity, magnetic_helicity, magnetic_scale, square_composition, square_temperature, temperature_scale, and velocity_scale.
Referenced by set_mhd_field_address::check_scalar_fields(), and t_field_product_labels::set_field_product_addresses().
check_field_product_vectors()
logical function m_field_product_labels::check_field_product_vectors (character(len = kchara), intent(in) field_name)
Definition at line 203 of file m_field_product_labels.f90.
References electric_field, poynting_flux, rest_of_geostrophic, square_current, square_magne, square_vector_potential, square_velocity, square_vorticity, stream_pol_magne, stream_pol_velocity, and truncated_magnetic_field.
Referenced by set_mhd_field_address::check_vector_fields(), and t_field_product_labels::set_field_product_addresses().
num_field_products()
integer(kind = kint) function m_field_product_labels::num_field_products
Definition at line 254 of file m_field_product_labels.f90.
References nfid_product.
set_field_product_labels()
subroutine m_field_product_labels::set_field_product_labels (integer(kind = kint_4b), dimension(nfid_product), intent(inout) n_comps, character(len = kchara), dimension(nfid_product), intent(inout) names, character(len = kchara), dimension(nfid_product), intent(inout) maths)
Definition at line 261 of file m_field_product_labels.f90.
References composition_scale, cross_helicity, current_helicity, electric_field, kinetic_helicity, magnetic_helicity, magnetic_scale, poynting_flux, rest_of_geostrophic, t_field_labels::set_field_labels(), square_composition, square_current, square_magne, square_temperature, square_vector_potential, square_velocity, square_vorticity, stream_pol_velocity, temperature_scale, truncated_magnetic_field, and velocity_scale.
Variable Documentation
composition_scale
type(field_def), parameter m_field_product_labels::composition_scale = field_def(n_comp = n_scalar, name = 'composition_scale', math = '$ L_{C} $')
Field label for composition length scale \(L_{C} \).
Definition at line 169 of file m_field_product_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_field_products(), check_field_product_scalars(), t_field_product_labels::set_field_product_addresses(), and set_field_product_labels().
cross_helicity
type(field_def), parameter m_field_product_labels::cross_helicity = field_def(n_comp = n_scalar, name = 'cross_helicity', math = '$ u_{i} B_{i} $')
Field label for cross helicity \(H_{x} = u_{i} B{i} \).
Definition at line 108 of file m_field_product_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_field_products(), check_field_product_scalars(), t_field_product_labels::set_field_product_addresses(), and set_field_product_labels().
current_helicity
type(field_def), parameter m_field_product_labels::current_helicity = field_def(n_comp = n_scalar, name = 'current_helicity', math = '$ J_{i} B_{i} $')
Field label for current helicity \(H_{J} = J_{i} B_{i} \).
Definition at line 102 of file m_field_product_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_field_products(), check_field_product_scalars(), t_field_product_labels::set_field_product_addresses(), and set_field_product_labels().
electric_field
type(field_def), parameter m_field_product_labels::electric_field = field_def(n_comp = n_vector, name = 'electric_field', math = '$ E_{i} $')
Field label for electric field \(E_{i} \).
Definition at line 76 of file m_field_product_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_field_products(), check_field_product_vectors(), t_field_product_labels::set_field_product_addresses(), and set_field_product_labels().
geostrophic_balance
type(field_def), parameter m_field_product_labels::geostrophic_balance = field_def(n_comp = n_vector, name = 'geostrophic_balance', math = '$ -2 e_{ijk} \Omega_{j} u_{k}' // ' - \partial_{i} p $')
Field label for ageostrophic balance \(-2 e_{ijk} \Omega_{j} u_{k} - \partial_{i} p \).
Definition at line 191 of file m_field_product_labels.f90.
Referenced by set_mhd_field_address::set_old_mhd_field_addresses(), and set_nodal_field_name::set_vector_field_name().
kinetic_helicity
type(field_def), parameter m_field_product_labels::kinetic_helicity = field_def(n_comp = n_scalar, name = 'kinetic_helicity', math = '$ u_{i} \omega_{i} $')
Field label for kinetic helicity \(H_{u} = u_{i} \omega_{i} \).
Definition at line 90 of file m_field_product_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_field_products(), check_field_product_scalars(), t_field_product_labels::set_field_product_addresses(), and set_field_product_labels().
magnetic_helicity
type(field_def), parameter m_field_product_labels::magnetic_helicity = field_def(n_comp = n_scalar, name = 'magnetic_helicity', math = '$ B_{i} A_{i} $')
Field label for magnetic helicity \(H_{B} = B_{i} A_{i} \).
Definition at line 96 of file m_field_product_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_field_products(), check_field_product_scalars(), t_field_product_labels::set_field_product_addresses(), and set_field_product_labels().
magnetic_scale
type(field_def), parameter m_field_product_labels::magnetic_scale = field_def(n_comp = n_scalar, name = 'magnetic_scale', math = '$ L_{B} $')
Field label for magnetic field length scale \(L_{B} \).
Definition at line 159 of file m_field_product_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_field_products(), check_field_product_scalars(), t_field_product_labels::set_field_product_addresses(), and set_field_product_labels().
nfid_product
integer(kind = kint), parameter, private m_field_product_labels::nfid_product = 21 private
Definition at line 57 of file m_field_product_labels.f90.
Referenced by num_field_products().
poynting_flux
type(field_def), parameter m_field_product_labels::poynting_flux = field_def(n_comp = n_vector, name = 'poynting_flux', math = '$ e_{ijk} E_{j} B_{k} $')
Field label for poynting flux \(e_{ijk} E_{j} B_{k} \).
Definition at line 82 of file m_field_product_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_field_products(), check_field_product_vectors(), t_field_product_labels::set_field_product_addresses(), and set_field_product_labels().
rest_of_geostrophic
type(field_def), parameter m_field_product_labels::rest_of_geostrophic = field_def(n_comp = n_vector, name = 'rest_of_geostrophic', math = '$ -2 e_{ijk} \Omega_{j} u_{k}' // ' - \partial_{i} p $')
Field label for ageostrophic balance \(-2 e_{ijk} \Omega_{j} u_{k} - \partial_{i} p \).
Definition at line 62 of file m_field_product_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_field_products(), check_field_product_vectors(), t_field_product_labels::set_field_product_addresses(), set_field_product_labels(), and set_nodal_field_name::set_vector_field_name().
square_composition
type(field_def), parameter m_field_product_labels::square_composition = field_def(n_comp = n_scalar, name = 'square_composition', math = '$ C^{2} $')
Square of composition \(C^{2} \).
Definition at line 147 of file m_field_product_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_field_products(), check_field_product_scalars(), t_field_product_labels::set_field_product_addresses(), and set_field_product_labels().
square_current
type(field_def), parameter m_field_product_labels::square_current = field_def(n_comp = n_vector, name = 'square_current', math = '$ J_{i}^{2} $')
Square of current density \(J_{i}^{2} \).
Definition at line 136 of file m_field_product_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_field_products(), check_field_product_vectors(), t_field_product_labels::set_field_product_addresses(), and set_field_product_labels().
square_magne
type(field_def), parameter m_field_product_labels::square_magne = field_def(n_comp = n_vector, name = 'square_magne', math = '$ B_{i}^{2} $')
Square of magnetic field \(B_{i}^{2} \).
Definition at line 126 of file m_field_product_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_field_products(), check_field_product_vectors(), t_field_product_labels::set_field_product_addresses(), and set_field_product_labels().
square_temperature
type(field_def), parameter m_field_product_labels::square_temperature = field_def(n_comp = n_scalar, name = 'square_temperature', math = '$ T^{2} $')
Square of temperature \(T^{2} \).
Definition at line 142 of file m_field_product_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_field_products(), check_field_product_scalars(), t_field_product_labels::set_field_product_addresses(), and set_field_product_labels().
square_vector_potential
type(field_def), parameter m_field_product_labels::square_vector_potential = field_def(n_comp = n_vector, name = 'square_vector_potential', math = '$ A_{i}^{2} $')
Square of magnetic vector potential \(A_{i}^{2} \).
Definition at line 131 of file m_field_product_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_field_products(), check_field_product_vectors(), t_field_product_labels::set_field_product_addresses(), and set_field_product_labels().
square_velocity
type(field_def), parameter m_field_product_labels::square_velocity = field_def(n_comp = n_vector, name = 'square_velocity', math = '$ u_{i}^{2} $')
Square of velocity \(u_{i}^{2} \).
Definition at line 116 of file m_field_product_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_field_products(), check_field_product_vectors(), t_field_product_labels::set_field_product_addresses(), and set_field_product_labels().
square_vorticity
type(field_def), parameter m_field_product_labels::square_vorticity = field_def(n_comp = n_vector, name = 'square_vorticity', math = '$ \omega_{i}^{2} $')
Square of vorticity \(\omega_{i}^{2} \).
Definition at line 121 of file m_field_product_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_field_products(), check_field_product_vectors(), t_field_product_labels::set_field_product_addresses(), and set_field_product_labels().
stream_pol_magne
type(field_def), parameter m_field_product_labels::stream_pol_magne = field_def(n_comp = n_vector, name = 'stream_pol_magne', math = '$ \Phi_{Bs} $')
Stream functin for the poloidal magnetic field \(\Phi_{Bs} \).
Definition at line 183 of file m_field_product_labels.f90.
Referenced by check_field_product_vectors().
stream_pol_velocity
type(field_def), parameter m_field_product_labels::stream_pol_velocity = field_def(n_comp = n_vector, name = 'stream_pol_velocity', math = '$ \Psi_{Us} $')
Stream functin for the poloidal velocity \(\Psi_{Us} \).
Definition at line 176 of file m_field_product_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_field_products(), check_field_product_vectors(), t_field_product_labels::set_field_product_addresses(), and set_field_product_labels().
temperature_scale
type(field_def), parameter m_field_product_labels::temperature_scale = field_def(n_comp = n_scalar, name = 'temperature_scale', math = '$ L_{T} $')
Field label for temperature length scale \(L_{T} \).
Definition at line 164 of file m_field_product_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_field_products(), check_field_product_scalars(), t_field_product_labels::set_field_product_addresses(), and set_field_product_labels().
truncated_magnetic_field
type(field_def), parameter m_field_product_labels::truncated_magnetic_field = field_def(n_comp = n_vector, name = 'truncated_magnetic_field', math = '$ B_{i} $')
Field label for truncated magnetic field \(B_{i} \).
Definition at line 70 of file m_field_product_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_field_products(), check_field_product_vectors(), t_field_product_labels::set_field_product_addresses(), and set_field_product_labels().
velocity_scale
type(field_def), parameter m_field_product_labels::velocity_scale = field_def(n_comp = n_scalar, name = 'velocity_scale', math = '$ L_{u} $')
Field label for velocity length scale \(L_{u} \).
Definition at line 154 of file m_field_product_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_field_products(), check_field_product_scalars(), t_field_product_labels::set_field_product_addresses(), and set_field_product_labels().