CALYPSO: mpi_sph_gauss_coefs_io Module Reference
mpi_sph_gauss_coefs_io Module Reference
Data arrays to monitoring spectrum data.
Functions/Subroutines
subroutine append_sph_gauss_coefs_file (time_d, sph_params, sph_rj, ipol, rj_fld, gauss)
subroutine write_sph_gauss_header_mpi (IO_param, picked)
subroutine, private write_sph_gauss_coefes_mpi (IO_param, time_d, sph_params, sph_rj, ipol, rj_fld, picked)
character(len=16+25) function, private picked_gauss_head (i_step, time)
integer(kind=kint) function check_gauss_coefs_num (gauss)
integer(kind=kint) function check_gauss_coefs_4_monitor (gauss)
Variables
integer(kind=kint), parameter, private id_gauss_coef = 23
Detailed Description
Data arrays to monitoring spectrum data.
      subroutine append_sph_gauss_coefs_file                          &
     &         (time_d, sph_params, sph_rj, ipol, rj_fld, gauss)
        type(time_data), intent(in) :: time_d
        type(sph_shell_parameters), intent(in) :: sph_params
        type(sph_rj_grid), intent(in) :: sph_rj
        type(phys_address), intent(in) :: ipol
        type(phys_data), intent(in) :: rj_fld
        type(picked_spectrum_data), intent(in) :: gauss
        type(calypso_MPI_IO_params) :: IO_param
Function/Subroutine Documentation
append_sph_gauss_coefs_file()
subroutine mpi_sph_gauss_coefs_io::append_sph_gauss_coefs_file (type(time_data), intent(in) time_d, type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(phys_address), intent(in) ipol, type(phys_data), intent(in) rj_fld, type(picked_spectrum_data), intent(in) gauss)
Definition at line 49 of file MPI_sph_gauss_coefs_IO.f90.
References set_parallel_file_name::add_dat_extension(), calypso_mpi::calypso_mpi_barrier(), mpi_ascii_data_io::close_mpi_file(), mpi_ascii_data_io::open_append_mpi_file(), write_sph_gauss_coefes_mpi(), and write_sph_gauss_header_mpi().
Referenced by cal_write_sph_monitor_data::output_sph_monitor_data().
check_gauss_coefs_4_monitor()
integer(kind = kint) function mpi_sph_gauss_coefs_io::check_gauss_coefs_4_monitor (type(picked_spectrum_data), intent(in) gauss)
Definition at line 270 of file MPI_sph_gauss_coefs_IO.f90.
References id_gauss_coef, and skip_comment_f::skip_comment().
Referenced by check_gauss_coefs_num().
check_gauss_coefs_num()
integer(kind = kint) function mpi_sph_gauss_coefs_io::check_gauss_coefs_num (type(picked_spectrum_data), intent(in) gauss)
Definition at line 241 of file MPI_sph_gauss_coefs_IO.f90.
References set_parallel_file_name::add_dat_extension(), check_gauss_coefs_4_monitor(), id_gauss_coef, m_constants::izero, and calypso_mpi::my_rank.
Referenced by t_sph_mhd_monitor_data_io::open_sph_vol_rms_file_mhd().
picked_gauss_head()
character(len = 16+25) function, private mpi_sph_gauss_coefs_io::picked_gauss_head (integer(kind = kint), intent(in) i_step, real(kind = kreal), intent(in) time) private
Definition at line 228 of file MPI_sph_gauss_coefs_IO.f90.
Referenced by write_sph_gauss_coefes_mpi().
write_sph_gauss_coefes_mpi()
subroutine, private mpi_sph_gauss_coefs_io::write_sph_gauss_coefes_mpi (type(calypso_mpi_io_params), intent(inout) IO_param, type(time_data), intent(in) time_d, type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(phys_address), intent(in) ipol, type(phys_data), intent(in) rj_fld, type(picked_spectrum_data), intent(in) picked) private
Definition at line 151 of file MPI_sph_gauss_coefs_IO.f90.
References pickup_gauss_coefficients::gauss_coefficients_4_write(), m_constants::ione, m_calypso_mpi_io::mpi_write_mul_chara_b(), m_calypso_mpi_io::mpi_write_one_chara_b(), calypso_mpi::my_rank, calypso_mpi::nprocs, and picked_gauss_head().
Referenced by append_sph_gauss_coefs_file().
write_sph_gauss_header_mpi()
subroutine mpi_sph_gauss_coefs_io::write_sph_gauss_header_mpi (type(calypso_mpi_io_params), intent(inout) IO_param, type(picked_spectrum_data), intent(in) picked)
Definition at line 86 of file MPI_sph_gauss_coefs_IO.f90.
References transfer_to_long_integers::cast_long(), write_field_labels::count_label_list_length(), m_monitor_file_labels::hd_pick_gauss_head(), m_monitor_file_labels::hd_time_label(), m_constants::ione, t_calypso_mpi_io_param::istack64_4_parallel_data(), m_calypso_mpi_io::mpi_write_one_chara_b(), calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by append_sph_gauss_coefs_file().
Variable Documentation
id_gauss_coef
integer(kind = kint), parameter, private mpi_sph_gauss_coefs_io::id_gauss_coef = 23 private
Definition at line 38 of file MPI_sph_gauss_coefs_IO.f90.
Referenced by check_gauss_coefs_4_monitor(), and check_gauss_coefs_num().