CALYPSO: output_gen_sph_grid_modes Module Reference
output_gen_sph_grid_modes Module Reference
Main loop to generate spherical harmonics indices.
Functions/Subroutines
subroutine load_local_rj_mesh_4_merge (sph_file_param, num_pe, sph_mesh)
subroutine para_output_sph_mode_grids (sph_file_param, num_pe, sph_mesh)
subroutine para_output_sph_rj_modes (sph_file_param, num_pe, sph_mesh)
Variables
type(sph_file_data_type), save, private sph_file_m
Detailed Description
Main loop to generate spherical harmonics indices.
      subroutine load_local_rj_mesh_4_merge                           &
     &         (sph_file_param, num_pe, sph_mesh)
        integer, intent(in) ::  num_pe
        type(field_IO_params), intent(in) :: sph_file_param
        type(sph_mesh_data), intent(inout) :: sph_mesh(num_pe)
      subroutine para_output_sph_mode_grids                           &
     &         (sph_file_param, num_pe, sph_mesh)
      subroutine para_output_sph_rj_modes                             &
     &         (sph_file_param, num_pe, sph_mesh)
        integer(kind = kint), intent(in) :: num_pe
        type(field_IO_params), intent(in) :: sph_file_param
        type(sph_mesh_data), intent(inout) :: sph_mesh(num_pe)
Function/Subroutine Documentation
load_local_rj_mesh_4_merge()
subroutine output_gen_sph_grid_modes::load_local_rj_mesh_4_merge (type(field_io_params), intent(in) sph_file_param, integer, intent(in) num_pe, type(sph_mesh_data), dimension(num_pe), intent(inout) sph_mesh)
Definition at line 50 of file output_gen_sph_grid_modes.f90.
References load_data_for_sph_io::copy_sph_trans_rj_from_io(), count_num_sph_smp::count_num_rj_smp(), t_spheric_data_io::dealloc_rj_mode_io(), calypso_mpi::my_rank, calypso_mpi::nprocs, sph_file_mpi_io_select::sel_mpi_read_spectr_rj_file(), sph_file_io_select::set_sph_mesh_file_fmt_prefix(), and sph_file_m.
Referenced by parallel_gen_sph_grids::check_and_make_para_rj_mode().
para_output_sph_mode_grids()
subroutine output_gen_sph_grid_modes::para_output_sph_mode_grids (type(field_io_params), intent(in) sph_file_param, integer(kind = kint), intent(in) num_pe, type(sph_mesh_data), dimension(num_pe), intent(inout) sph_mesh)
Definition at line 90 of file output_gen_sph_grid_modes.f90.
References load_data_for_sph_io::copy_sph_trans_rj_to_io(), load_data_for_sph_io::copy_sph_trans_rlm_to_io(), load_data_for_sph_io::copy_sph_trans_rtm_to_io(), load_data_for_sph_io::copy_sph_trans_rtp_to_io(), t_spheric_data_io::dealloc_rj_mode_io(), t_spheric_data_io::dealloc_rlm_mode_io(), t_spheric_data_io::dealloc_rtm_grid_io(), t_spheric_data_io::dealloc_rtp_grid_io(), parallel_load_data_4_sph::dealloc_sph_modes(), m_machine_parameter::iflag_debug, calypso_mpi::my_rank, calypso_mpi::nprocs, sph_file_io_select::sel_write_geom_rtm_file(), sph_file_io_select::sel_write_geom_rtp_file(), sph_file_io_select::sel_write_modes_rlm_file(), sph_file_io_select::sel_write_spectr_modes_rj_file(), and sph_file_m.
Referenced by parallel_gen_sph_grids::check_and_make_para_sph_mesh().
para_output_sph_rj_modes()
subroutine output_gen_sph_grid_modes::para_output_sph_rj_modes (type(field_io_params), intent(in) sph_file_param, integer(kind = kint), intent(in) num_pe, type(sph_mesh_data), dimension(num_pe), intent(inout) sph_mesh)
Definition at line 165 of file output_gen_sph_grid_modes.f90.
References load_data_for_sph_io::copy_sph_trans_rj_to_io(), t_spheric_data_io::dealloc_rj_mode_io(), calypso_mpi::my_rank, calypso_mpi::nprocs, sph_file_io_select::sel_write_spectr_modes_rj_file(), and sph_file_m.
Referenced by parallel_gen_sph_grids::check_and_make_para_rj_mode().
Variable Documentation
sph_file_m
type(sph_file_data_type), save, private output_gen_sph_grid_modes::sph_file_m private
Definition at line 42 of file output_gen_sph_grid_modes.f90.
Referenced by load_local_rj_mesh_4_merge(), para_output_sph_mode_grids(), and para_output_sph_rj_modes().