CALYPSO: fem_analyzer_sph_mhd Module Reference
fem_analyzer_sph_mhd Module Reference
Top routines to transfer spherical harmonics grids data to FEM data for data visualization.
Functions/Subroutines
subroutine fem_initialize_sph_mhd (MHD_files, MHD_step, geofem, nod_fld, iphys, MHD_IO)
subroutine fem_analyze_sph_mhd (MHD_files, geofem, nod_fld, MHD_step, MHD_IO)
subroutine sph_to_fem_bridge_mhd (sph, WK, geofem, nod_fld)
subroutine fem_finalize (MHD_files, MHD_step, MHD_IO)
Detailed Description
Top routines to transfer spherical harmonics grids data to FEM data for data visualization.
      subroutine FEM_initialize_sph_MHD(MHD_files, MHD_step,          &
     &          geofem, nod_fld, iphys, MHD_IO)
        type(MHD_file_IO_params), intent(in) :: MHD_files
        type(MHD_step_param), intent(in) :: MHD_step
        type(mesh_data), intent(inout) :: geofem
        type(phys_address), intent(inout) :: iphys
        type(phys_data), intent(inout) :: nod_fld
        type(MHD_IO_data), intent(inout) :: MHD_IO
      subroutine FEM_analyze_sph_MHD                                  &
     &         (MHD_files, geofem, nod_fld, MHD_step, MHD_IO)
        type(MHD_file_IO_params), intent(in) :: MHD_files
        type(SGS_paremeters), intent(in) :: SGS_par
        type(time_data), intent(in) :: time_d
        type(mesh_data), intent(in) :: geofem
        type(phys_data), intent(inout) :: nod_fld
        type(MHD_step_param), intent(inout) :: MHD_step
        type(MHD_IO_data), intent(inout) :: MHD_IO
      subroutine FEM_finalize(MHD_files, MHD_step, MHD_IO)
        type(MHD_file_IO_params), intent(in) :: MHD_files
        type(MHD_step_param), intent(in) :: MHD_step
        type(MHD_IO_data), intent(inout) :: MHD_IO
      subroutine SPH_to_FEM_bridge_MHD(sph, WK, geofem, nod_fld)
        type(sph_grids), intent(in) :: sph
        type(works_4_sph_trans_MHD), intent(in) :: WK
        type(mesh_data), intent(in) :: geofem
        type(phys_address), intent(in) :: iphys
        type(phys_data), intent(inout) :: nod_fld
      subroutine FEM_to_SPH_bridge
Parameters
i_step Current time step
Function/Subroutine Documentation
fem_analyze_sph_mhd()
subroutine fem_analyzer_sph_mhd::fem_analyze_sph_mhd (type(mhd_file_io_params), intent(in) MHD_files, type(mesh_data), intent(in) geofem, type(phys_data), intent(inout) nod_fld, type(mhd_step_param), intent(inout) MHD_step, type(mhd_io_data), intent(inout) MHD_IO)
Definition at line 124 of file FEM_analyzer_sph_MHD.f90.
References m_work_time::end_elapsed_time(), m_machine_parameter::iflag_debug, m_elapsed_labels_4_mhd::iflag_mhd_time, m_elapsed_labels_4_mhd::ist_elapsed_mhd, output_viz_file_control::lead_field_data_flag(), nod_phys_send_recv::nod_fields_send_recv(), t_ucd_file::s_output_ucd_file_control(), and m_work_time::start_elapsed_time().
Referenced by analyzer_sph_mhd_w_psf::evolution_sph_mhd_w_psf(), and analyzer_sph_snap_w_psf::evolution_sph_snap_w_psf().
fem_finalize()
subroutine fem_analyzer_sph_mhd::fem_finalize (type(mhd_file_io_params), intent(in) MHD_files, type(mhd_step_param), intent(in) MHD_step, type(mhd_io_data), intent(inout) MHD_IO)
Definition at line 210 of file FEM_analyzer_sph_MHD.f90.
References t_cal_max_indices::dealloc_phys_range(), and t_ucd_file::finalize_output_ucd().
Referenced by analyzer_sph_mhd_w_psf::evolution_sph_mhd_w_psf(), and analyzer_sph_snap_w_psf::evolution_sph_snap_w_psf().
fem_initialize_sph_mhd()
subroutine fem_analyzer_sph_mhd::fem_initialize_sph_mhd (type(mhd_file_io_params), intent(in) MHD_files, type(mhd_step_param), intent(in) MHD_step, type(mesh_data), intent(inout) geofem, type(phys_data), intent(inout) nod_fld, type(phys_address), intent(inout) iphys, type(mhd_io_data), intent(inout) MHD_IO)
Definition at line 70 of file FEM_analyzer_sph_MHD.f90.
References t_cal_max_indices::alloc_phys_range(), m_work_time::end_elapsed_time(), parallel_fem_mesh_init::fem_mesh_initialization(), m_machine_parameter::iflag_debug, m_elapsed_labels_4_mhd::iflag_mhd_time, set_control_field_data::init_field_data(), m_elapsed_labels_4_mhd::ist_elapsed_mhd, t_ucd_file::output_grd_file_4_snapshot(), node_monitor_io::set_local_nod_4_monitor(), and m_work_time::start_elapsed_time().
Referenced by analyzer_sph_mhd_w_psf::initialize_sph_mhd_w_psf(), and analyzer_sph_snap_w_psf::initialize_sph_snap_w_psf().
sph_to_fem_bridge_mhd()
subroutine fem_analyzer_sph_mhd::sph_to_fem_bridge_mhd (type(sph_grids), intent(in) sph, type(works_4_sph_trans_mhd), intent(in) WK, type(mesh_data), intent(in) geofem, type(phys_data), intent(inout) nod_fld)
Definition at line 163 of file FEM_analyzer_sph_MHD.f90.
References set_address_sph_trans_snap::copy_field_from_transform(), set_address_sph_trans_snap::copy_force_from_transform(), and m_machine_parameter::iflag_debug.
Referenced by analyzer_sph_mhd_w_psf::evolution_sph_mhd_w_psf(), analyzer_sph_snap_w_psf::evolution_sph_snap_w_psf(), and t_sph_mhd_zonal_mean_viz::sph_mhd_zonal_rms_section().