CALYPSO: set_sph_exp_free_cmb Module Reference
set_sph_exp_free_cmb Module Reference
Evaluate velocity with free slip boundary at CMB.
Functions/Subroutines
subroutine cal_sph_nod_cmb_free_v_and_w (jmax, kr_out, fdm2_free_vp_CMB, fdm2_free_vt_CMB, is_fld, is_rot, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_nod_cmb_free_vpol2 (jmax, kr_out, fdm2_free_vp_CMB, is_fld, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_nod_cmb_free_rot2 (jmax, g_sph_rj, kr_out, r_CMB, fdm2_free_vp_CMB, fdm2_free_vt_CMB, is_fld, is_rot, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_nod_cmb_free_diffuse2 (jmax, g_sph_rj, kr_out, r_CMB, fdm2_free_vp_CMB, fdm2_free_vt_CMB, coef_d, is_fld, is_diffuse, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_nod_cmb_free_w_diffuse2 (jmax, g_sph_rj, kr_out, r_CMB, fdm2_fix_fld_CMB, fdm2_free_vt_CMB, coef_d, is_fld, is_diffuse, n_point, ntot_phys_rj, d_rj)
Detailed Description
Evaluate velocity with free slip boundary at CMB.
      subroutine cal_sph_nod_cmb_free_v_and_w(jmax, kr_out,           &
     &          fdm2_free_vp_CMB, fdm2_free_vt_CMB, is_fld, is_rot,   &
     &          n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_nod_cmb_free_vpol2(jmax, kr_out,             &
     &          fdm2_free_vp_CMB, is_fld, n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_nod_cmb_free_rot2(jmax, g_sph_rj, kr_out,    &
     &          r_CMB, fdm2_free_vp_CMB, fdm2_free_vt_CMB,            &
     &          is_fld, is_rot, n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_nod_cmb_free_diffuse2(jmax, g_sph_rj, kr_out,&
     &          r_CMB, fdm2_free_vp_CMB, fdm2_free_vt_CMB, coef_d,    &
     &          is_fld, is_diffuse, n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_nod_cmb_free_w_diffuse2(jmax, g_sph_rj,      &
     &          kr_out, r_CMB, fdm2_fix_fld_CMB, fdm2_free_vt_CMB,    &
     &          coef_d, is_fld, is_diffuse,                           &
     &          n_point, ntot_phys_rj, d_rj)
Parameters
n_point Number of points for spectrum data
jmax Number of modes for spherical harmonics \(L*(L+2)\)
kr_out Radial ID for outer boundary
r_CMB(0:2) Radius at CMB
Parameters
fdm2_fix_fld_CMB(0:2,3) Matrix to evaluate radial derivative at CMB with fixed field
fdm2_free_vp_CMB(-1:1,3) Matrix to evaluate poloidal velocity with free slip boundary at CMB
fdm2_free_vt_CMB(-1:1,3) Matrix to evaluate toroidal velocity with free slip boundary at CMB
Parameters
coef_d Coefficient for diffusion term
is_fld Address of poloidal velocity in d_rj
is_rot Address of poloidal vorticity in d_rj
is_diffuse Address of poloidal viscousity in d_rj
Parameters
ntot_phys_rj Total number of components
d_rj Spectrum data
Function/Subroutine Documentation
cal_sph_nod_cmb_free_diffuse2()
subroutine set_sph_exp_free_cmb::cal_sph_nod_cmb_free_diffuse2 (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_out, real(kind = kreal), dimension(0:2), intent(in) r_CMB, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_free_vp_CMB, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_free_vt_CMB, real(kind = kreal), intent(in) coef_d, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_diffuse, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 174 of file set_sph_exp_free_CMB.f90.
Referenced by select_exp_velocity_cmb::sel_cmb_sph_viscous_diffusion().
cal_sph_nod_cmb_free_rot2()
subroutine set_sph_exp_free_cmb::cal_sph_nod_cmb_free_rot2 (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_out, real(kind = kreal), dimension(0:2), intent(in) r_CMB, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_free_vp_CMB, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_free_vt_CMB, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_rot, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 133 of file set_sph_exp_free_CMB.f90.
Referenced by select_exp_velocity_cmb::sel_cmb_sph_vorticity().
cal_sph_nod_cmb_free_v_and_w()
subroutine set_sph_exp_free_cmb::cal_sph_nod_cmb_free_v_and_w (integer(kind = kint), intent(in) jmax, integer(kind = kint), intent(in) kr_out, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_free_vp_CMB, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_free_vt_CMB, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_rot, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 62 of file set_sph_exp_free_CMB.f90.
References m_constants::zero.
Referenced by select_exp_velocity_cmb::sel_cmb_grad_vp_and_vorticity().
cal_sph_nod_cmb_free_vpol2()
subroutine set_sph_exp_free_cmb::cal_sph_nod_cmb_free_vpol2 (integer(kind = kint), intent(in) jmax, integer(kind = kint), intent(in) kr_out, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_free_vp_CMB, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 102 of file set_sph_exp_free_CMB.f90.
References m_constants::zero.
Referenced by select_exp_velocity_cmb::sel_cmb_grad_poloidal_moment().
cal_sph_nod_cmb_free_w_diffuse2()
subroutine set_sph_exp_free_cmb::cal_sph_nod_cmb_free_w_diffuse2 (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_out, real(kind = kreal), dimension(0:2), intent(in) r_CMB, real(kind = kreal), dimension(0:2,3), intent(in) fdm2_fix_fld_CMB, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_free_vt_CMB, real(kind = kreal), intent(in) coef_d, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_diffuse, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 216 of file set_sph_exp_free_CMB.f90.
Referenced by select_exp_velocity_cmb::sel_cmb_sph_vort_diffusion().