CALYPSO: t_sph_spectr_data Module Reference
t_sph_spectr_data Module Reference
Flag and parameters for spherical transform dnyamo model.
Data Types
type sph_phys_data
!! Structure for spectr data Number of fields for spectrum data \(f(r,j) \) num_phys_rj = rj_fldnum_phys Total number of components for spectrum data \(f(r,j) \) ntot_phys_rj = rj_fldntot_phys Number of components for each field \(f(r,j) \) num_phys_comp_rj = rj_fldnum_component End address of d_rj for each field \(f(r,j) \) istack_phys_comp_rj = rj_fldistack_component Field name for \(f(r,j) \) phys_name_rj = rj_fldphys_name Spectr data \(f(r,j) \) d_rj = rj_fldd_fld Integer flag for monitoring output for spectr data \(f(r,j) \) flag_monitor_rj = rj_fldflag_monitor Number of fields for visualization output \(f(r,\theta,\phi) \) num_phys_rj_vis = rj_fldnum_phys_viz Total number of components for visualization output \(f(r,\theta,\phi) \) ntot_comp_rj_vis = rj_fldntot_phys_viz
Functions/Subroutines
subroutine alloc_phys_rj_name_t (sph_phys)
subroutine alloc_phys_rj_data_t (nnod_rj, sph_phys)
subroutine dealloc_phys_rj_name_t (sph_phys)
subroutine check_rj_spectr_name_t (sph_phys)
subroutine check_rj_spectr_data_t (id_rank, sph_phys)
Detailed Description
Flag and parameters for spherical transform dnyamo model.
      subroutine alloc_phys_rj_name_t(sph_phys)
      subroutine alloc_phys_rj_data_t(nnod_rj, sph_phys)
      subroutine dealloc_phys_rj_name_t(sph_phys)
      subroutine check_rj_spectr_name_t(sph_phys)
      subroutine check_rj_spectr_data_t(id_rank, sph_phys)
Parameters
id_rank process ID
Function/Subroutine Documentation
alloc_phys_rj_data_t()
subroutine t_sph_spectr_data::alloc_phys_rj_data_t (integer(kind = kint), intent(in) nnod_rj, type(sph_phys_data), intent(inout) sph_phys)
Definition at line 75 of file t_sph_spectr_data.f90.
References t_phys_data::alloc_phys_data_type().
alloc_phys_rj_name_t()
subroutine t_sph_spectr_data::alloc_phys_rj_name_t (type(sph_phys_data), intent(inout) sph_phys)
Definition at line 63 of file t_sph_spectr_data.f90.
References t_phys_data::alloc_phys_name_type().
check_rj_spectr_data_t()
subroutine t_sph_spectr_data::check_rj_spectr_data_t (integer, intent(in) id_rank, type(sph_phys_data), intent(in) sph_phys)
Definition at line 113 of file t_sph_spectr_data.f90.
References t_phys_data::check_nodal_data(), and t_phys_data::check_nodal_field_name().
check_rj_spectr_name_t()
subroutine t_sph_spectr_data::check_rj_spectr_name_t (type(sph_phys_data), intent(in) sph_phys)
Definition at line 100 of file t_sph_spectr_data.f90.
References t_phys_data::check_nodal_field_name().
dealloc_phys_rj_name_t()
subroutine t_sph_spectr_data::dealloc_phys_rj_name_t (type(sph_phys_data), intent(inout) sph_phys)
Definition at line 87 of file t_sph_spectr_data.f90.
References t_phys_data::dealloc_phys_data_type(), and t_phys_data::dealloc_phys_name_type().