CALYPSO: /home/takumi kera/calypso/src/programs/data_utilities/SNAPSHOT_MHD/main_sph_snapshot_w_psf.f90 File Reference
main_sph_snapshot_w_psf.f90 File Reference
program sph_snapshot_w_psf
Functions/Subroutines
program sph_snapshot_w_psf
Main program to evaluate snapshots from spectr data.
Detailed Description
program sph_snapshot_w_psf
Author
H. Matsui
Date
Programmed by H. Okuda in 2000
Modified by H. Matsui in May, 2003 (ver 2.0)
Connect to vizs by H. Matsui in July 2006 (ver 2.0)
Definition in file main_sph_snapshot_w_psf.f90.
Function/Subroutine Documentation
sph_snapshot_w_psf()
program sph_snapshot_w_psf
Main program to evaluate snapshots from spectr data.
Definition at line 11 of file main_sph_snapshot_w_psf.f90.
References calypso_mpi::calypso_mpi_finalize(), calypso_mpi::calypso_mpi_init(), analyzer_sph_snap_w_psf::evolution_sph_snap_w_psf(), and analyzer_sph_snap_w_psf::initialize_sph_snap_w_psf().