CALYPSO: set_nodes_4_viewer Module Reference
set_nodes_4_viewer Module Reference
Functions/Subroutines
subroutine s_set_nodes_4_viewer (nnod_4_surf, mesh, group, view_mesh, view_nod_grps)
subroutine, private s_set_nod_grp_4_viewer_surface (merged_grp, nnod_viewer, view_nod_grps)
Function/Subroutine Documentation
s_set_nod_grp_4_viewer_surface()
subroutine, private set_nodes_4_viewer::s_set_nod_grp_4_viewer_surface (type(mesh_groups), intent(in) merged_grp, integer(kind = kint), intent(in) nnod_viewer, type(viewer_node_groups), intent(inout) view_nod_grps) private
Definition at line 76 of file set_nodes_4_viewer.f90.
References pickup_node_4_viewer::set_node_group_item_viewer(), and renumber_surface_4_viewer::set_node_group_stack_viewer().
Referenced by s_set_nodes_4_viewer().
s_set_nodes_4_viewer()
subroutine set_nodes_4_viewer::s_set_nodes_4_viewer (integer(kind = kint), intent(in) nnod_4_surf, type(mesh_geometry), intent(in) mesh, type(mesh_groups), intent(in) group, type(viewer_mesh_data), intent(inout) view_mesh, type(viewer_node_groups), intent(inout) view_nod_grps)
Definition at line 32 of file set_nodes_4_viewer.f90.
References t_viewer_mesh::alloc_nod_position_viewer(), pickup_node_4_viewer::allocate_imark_nod_pick_node(), pickup_node_4_viewer::allocate_nod_cvt_table_viewer(), pickup_node_4_viewer::count_used_node_4_viewer(), pickup_node_4_viewer::deallocate_imark_nod_pick_node(), pickup_node_4_viewer::deallocate_nod_cvt_table_viewer(), m_machine_parameter::iflag_debug, pickup_node_4_viewer::mark_used_node_4_viewer(), pickup_node_4_viewer::renumber_surf_connect_4_viewer(), s_set_nod_grp_4_viewer_surface(), pickup_node_4_viewer::set_node_cvt_table_viewer(), and pickup_node_4_viewer::set_node_position_4_viewer().
Referenced by const_kemoview_mesh::const_surf_mesh_4_viewer().