CALYPSO: cvt_sph_vector_2_xyz_smp Module Reference
cvt_sph_vector_2_xyz_smp Module Reference
Functions/Subroutines
subroutine cvt_sph_vect_2_xyz_smp (np_smp, numnod, inod_smp_stack, vect, v_sph, theta, phi)
subroutine overwrite_sph_vect_2_xyz_smp (np_smp, numnod, inod_smp_stack, vect, theta, phi)
subroutine cal_sph_2_x_comp_smp (np_smp, numnod, inod_smp_stack, v_x, v_sph, theta, phi)
subroutine cal_sph_2_y_comp_smp (np_smp, numnod, inod_smp_stack, v_y, v_sph, theta, phi)
subroutine cal_sph_2_z_comp_smp (np_smp, numnod, inod_smp_stack, v_z, v_sph, theta)
Function/Subroutine Documentation
cal_sph_2_x_comp_smp()
subroutine cvt_sph_vector_2_xyz_smp::cal_sph_2_x_comp_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod), intent(inout) v_x, real(kind=kreal), dimension(numnod,3), intent(in) v_sph, real(kind=kreal), dimension(numnod), intent(in) theta, real(kind=kreal), dimension(numnod), intent(in) phi)
Definition at line 148 of file cvt_sph_vector_2_xyz_smp.f90.
cal_sph_2_y_comp_smp()
subroutine cvt_sph_vector_2_xyz_smp::cal_sph_2_y_comp_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod), intent(inout) v_y, real(kind=kreal), dimension(numnod,3), intent(in) v_sph, real(kind=kreal), dimension(numnod), intent(in) theta, real(kind=kreal), dimension(numnod), intent(in) phi)
Definition at line 182 of file cvt_sph_vector_2_xyz_smp.f90.
cal_sph_2_z_comp_smp()
subroutine cvt_sph_vector_2_xyz_smp::cal_sph_2_z_comp_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod), intent(inout) v_z, real(kind=kreal), dimension(numnod,3), intent(in) v_sph, real(kind=kreal), dimension(numnod), intent(in) theta)
Definition at line 215 of file cvt_sph_vector_2_xyz_smp.f90.
cvt_sph_vect_2_xyz_smp()
subroutine cvt_sph_vector_2_xyz_smp::cvt_sph_vect_2_xyz_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,3), intent(inout) vect, real(kind=kreal), dimension(numnod,3), intent(in) v_sph, real(kind=kreal), dimension(numnod), intent(in) theta, real(kind=kreal), dimension(numnod), intent(in) phi)
Definition at line 62 of file cvt_sph_vector_2_xyz_smp.f90.
Referenced by cvt_nodal_and_sph_field::cvt_sph_vec_to_nod_vec().
overwrite_sph_vect_2_xyz_smp()
subroutine cvt_sph_vector_2_xyz_smp::overwrite_sph_vect_2_xyz_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,3), intent(inout) vect, real(kind=kreal), dimension(numnod), intent(in) theta, real(kind=kreal), dimension(numnod), intent(in) phi)
Definition at line 105 of file cvt_sph_vector_2_xyz_smp.f90.
Referenced by copy_nodal_fld_4_sph_trans::copy_nod_vec_from_trans_wpole(), and coordinate_convert_4_sph::overwrite_nodal_sph_2_xyz_smp().