CALYPSO: t_binary_io_buffer Module Reference
t_binary_io_buffer Module Reference
Data Types
type binary_io_buffer
Structure of buffer for binary IO.
Functions/Subroutines
subroutine link_real_buffer_for_bin (num, data, bbuf)
subroutine link_int8_buffer_for_bin (num, int8_dat, bbuf)
subroutine link_int4_buffer_for_bin (num, int4_dat, bbuf)
subroutine link_text_buffer_for_bin (len_buf, textbuf, bbuf)
subroutine unlink_real_buffer_for_bin (bbuf)
subroutine unlink_int8_buffer_for_bin (bbuf)
subroutine unlink_int4_buffer_for_bin (bbuf)
subroutine unlink_text_buffer_for_bin (bbuf)
Variables
integer(kind=kint), parameter, private id_bin = 19
Function/Subroutine Documentation
link_int4_buffer_for_bin()
subroutine t_binary_io_buffer::link_int4_buffer_for_bin (integer, intent(in) num, integer(kind = 4), dimension(num), intent(in), target int4_dat, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 94 of file t_binary_IO_buffer.f90.
Referenced by binary_file_access::rawread_int4_f(), and binary_file_access::rawwrite_int4_f().
link_int8_buffer_for_bin()
subroutine t_binary_io_buffer::link_int8_buffer_for_bin (integer, intent(in) num, integer(kind = kint_gl), dimension(num), intent(in), target int8_dat, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 79 of file t_binary_IO_buffer.f90.
References m_precision::kint_gl.
Referenced by binary_file_access::rawread_int8_f(), and binary_file_access::rawwrite_int8_f().
link_real_buffer_for_bin()
subroutine t_binary_io_buffer::link_real_buffer_for_bin (integer, intent(in) num, real(kind = kreal), dimension(num), intent(in), target data, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 64 of file t_binary_IO_buffer.f90.
References m_precision::kreal.
Referenced by binary_file_access::rawread_real_f(), and binary_file_access::rawwrite_real_f().
link_text_buffer_for_bin()
subroutine t_binary_io_buffer::link_text_buffer_for_bin (integer, intent(in) len_buf, character(len=1), dimension(len_buf), intent(in), target textbuf, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 109 of file t_binary_IO_buffer.f90.
Referenced by binary_file_access::open_ad_rawfile_f(), binary_file_access::open_rd_rawfile_f(), binary_file_access::open_wt_rawfile_f(), binary_file_access::rawread_chara_f(), and binary_file_access::rawwrite_chara_f().
unlink_int4_buffer_for_bin()
subroutine t_binary_io_buffer::unlink_int4_buffer_for_bin (type(binary_io_buffer), intent(inout) bbuf)
Definition at line 145 of file t_binary_IO_buffer.f90.
Referenced by binary_file_access::rawread_int4_f(), and binary_file_access::rawwrite_int4_f().
unlink_int8_buffer_for_bin()
subroutine t_binary_io_buffer::unlink_int8_buffer_for_bin (type(binary_io_buffer), intent(inout) bbuf)
Definition at line 135 of file t_binary_IO_buffer.f90.
Referenced by binary_file_access::rawread_int8_f(), and binary_file_access::rawwrite_int8_f().
unlink_real_buffer_for_bin()
subroutine t_binary_io_buffer::unlink_real_buffer_for_bin (type(binary_io_buffer), intent(inout) bbuf)
Definition at line 125 of file t_binary_IO_buffer.f90.
Referenced by binary_file_access::rawread_real_f(), and binary_file_access::rawwrite_real_f().
unlink_text_buffer_for_bin()
subroutine t_binary_io_buffer::unlink_text_buffer_for_bin (type(binary_io_buffer), intent(inout) bbuf)
Definition at line 155 of file t_binary_IO_buffer.f90.
Referenced by binary_file_access::open_ad_rawfile_f(), binary_file_access::open_rd_rawfile_f(), binary_file_access::open_wt_rawfile_f(), binary_file_access::rawread_chara_f(), and binary_file_access::rawwrite_chara_f().
Variable Documentation
id_bin
integer(kind = kint), parameter, private t_binary_io_buffer::id_bin = 19 private
Definition at line 31 of file t_binary_IO_buffer.f90.