CALYPSO: init_sph_mhd_elapsed_label Module Reference
init_sph_mhd_elapsed_label Module Reference
Initialize elepsed time monitoring.
Functions/Subroutines
subroutine set_sph_mhd_elapsed_label
subroutine reset_elapse_4_init_sph_mhd
subroutine write_resolution_data (sph)
subroutine, private check_num_of_process_4_sph (sph_rtp, sph_rtm, sph_rlm, sph_rj, nproc_rj_IO, nproc_rlm_IO, nproc_rtm_IO, nproc_rtp_IO)
subroutine, private write_resolution_info (num_pe, sph_params, sph_rtp, sph_rtm, sph_rlm, sph_rj, nproc_rj_IO, nproc_rlm_IO, nproc_rtm_IO, nproc_rtp_IO)
Detailed Description
Initialize elepsed time monitoring.
      subroutine set_sph_MHD_elapsed_label
      subroutine reset_elapse_4_init_sph_mhd
      subroutine write_resolution_data(sph)
        type(sph_grids), intent(in) :: sph
Function/Subroutine Documentation
check_num_of_process_4_sph()
subroutine, private init_sph_mhd_elapsed_label::check_num_of_process_4_sph (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_rj_grid), intent(in) sph_rj, integer(kind = kint), dimension(2), intent(inout) nproc_rj_IO, integer(kind = kint), dimension(2), intent(inout) nproc_rlm_IO, integer(kind = kint), dimension(3), intent(inout) nproc_rtm_IO, integer(kind = kint), dimension(3), intent(inout) nproc_rtp_IO) private
Definition at line 111 of file init_sph_MHD_elapsed_label.F90.
References calypso_mpi_int::calypso_mpi_reduce_int(), and transfer_to_long_integers::cast_long().
Referenced by write_resolution_data().
reset_elapse_4_init_sph_mhd()
subroutine init_sph_mhd_elapsed_label::reset_elapse_4_init_sph_mhd
Definition at line 61 of file init_sph_MHD_elapsed_label.F90.
References m_elapsed_labels_sph_trns::reset_elapse_after_init_fft(), m_elapsed_labels_sph_trns::reset_elapse_after_init_leg(), m_elapsed_labels_sph_trns::reset_elapse_after_init_sdt(), m_elapsed_labels_4_mhd::reset_elapse_after_init_sgs(), m_elapsed_labels_sph_trns::reset_elapse_after_init_sph(), m_elapsed_labels_4_mhd::reset_elapse_after_init_sph_mhd(), m_elapsed_labels_send_recv::reset_elapse_after_init_sr(), and m_elapsed_labels_4_viz::reset_elapse_after_init_viz().
Referenced by sph_analyzer_add_initial::initialize_add_sph_initial(), sph_analyzer_const_initial::initialize_const_sph_initial(), analyzer_sph_dynamobench::initialize_sph_dynamobench(), analyzer_sph_mhd_w_psf::initialize_sph_mhd_w_psf(), and analyzer_sph_snap_w_psf::initialize_sph_snap_w_psf().
set_sph_mhd_elapsed_label()
subroutine init_sph_mhd_elapsed_label::set_sph_mhd_elapsed_label
Definition at line 30 of file init_sph_MHD_elapsed_label.F90.
References m_elapsed_labels_4_mhd::elapsed_label_4_mhd(), m_elapsed_labels_4_mhd::elapsed_label_4_sgs_model(), m_elapsed_labels_4_mhd::elapsed_label_4_sph_mhd(), m_elapsed_labels_sph_trns::elpsed_label_4_fft_detail(), m_elapsed_labels_sph_trns::elpsed_label_4_sph_detail(), m_elapsed_labels_sph_trns::elpsed_label_4_sph_trns(), m_elapsed_labels_4_viz::elpsed_label_4_viz(), m_elapsed_labels_send_recv::elpsed_label_calypso_send_recv(), and m_elapsed_labels_gen_sph::elpsed_label_gen_sph_grid().
Referenced by sph_analyzer_add_initial::initialize_add_sph_initial(), sph_analyzer_const_initial::initialize_const_sph_initial(), analyzer_sph_dynamobench::initialize_sph_dynamobench(), analyzer_sph_mhd_w_psf::initialize_sph_mhd_w_psf(), and analyzer_sph_snap_w_psf::initialize_sph_snap_w_psf().
write_resolution_data()
subroutine init_sph_mhd_elapsed_label::write_resolution_data (type(sph_grids), intent(in) sph)
Definition at line 84 of file init_sph_MHD_elapsed_label.F90.
References check_num_of_process_4_sph(), calypso_mpi::my_rank, calypso_mpi::nprocs, and write_resolution_info().
Referenced by analyzer_sph_mhd_w_psf::evolution_sph_mhd_w_psf().
write_resolution_info()
subroutine, private init_sph_mhd_elapsed_label::write_resolution_info (integer, intent(in) num_pe, type(sph_shell_parameters), intent(in) sph_params, type(sph_rtp_grid), intent(in) sph_rtp, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_rj_grid), intent(in) sph_rj, integer(kind = kint), dimension(2), intent(in) nproc_rj_IO, integer(kind = kint), dimension(2), intent(in) nproc_rlm_IO, integer(kind = kint), dimension(3), intent(in) nproc_rtm_IO, integer(kind = kint), dimension(3), intent(in) nproc_rtp_IO) private
Definition at line 154 of file init_sph_MHD_elapsed_label.F90.
References set_parallel_file_name::add_dat_extension(), m_work_time::id_timer_file, and m_work_time::time_file_prefix.
Referenced by write_resolution_data().