CALYPSO: t_sph_comm_table_from_fftw Module Reference
t_sph_comm_table_from_fftw Module Reference
Fourier transform using FFTPACK5.
Data Types
type comm_tbl_from_fftw
Structure of communication table from FFT to send buffer.
Functions/Subroutines
subroutine alloc_comm_table_sph_fftw (ntot_sr_rtp, comm_sph_FFTW)
subroutine dealloc_comm_table_sph_fftw (comm_sph_FFTW)
subroutine copy_all_rtp_fftw_to_send_smp (irt_rtp_smp_stack, Nfft_c, ncomp_fwd, C_fft, comm_sph_FFTW, n_WS, WS)
subroutine copy_1comp_rtp_fftw_to_send_smp (nd, irt_rtp_smp_stack, Nfft_c, ncomp_fwd, C_fft, comm_sph_FFTW, n_WS, WS)
subroutine copy_all_rtp_fftw_to_send (nnod_rt, Nfft_c, ncomp_fwd, C_fft, comm_sph_FFTW, n_WS, WS)
subroutine copy_1comp_rtp_fftw_to_send (nd, nnod_rt, Nfft_c, ncomp_fwd, C_fft, comm_sph_FFTW, n_WS, WS)
subroutine copy_all_prt_fftw_to_send (nnod_rtp, nnod_rt, ncomp_fwd, Nfft_c, C_fft, comm_sph_FFTW, n_WS, WS)
subroutine copy_1comp_prt_fftw_to_send (nd, nnod_rtp, nnod_rt, ncomp_fwd, Nfft_c, C_fft, comm_sph_FFTW, n_WS, WS)
Detailed Description
Fourier transform using FFTPACK5.
      subroutine alloc_comm_table_sph_FFTW(ntot_sr_rtp, comm_sph_FFTW)
      subroutine dealloc_comm_table_sph_FFTW(comm_sph_FFTW)
        type(comm_tbl_from_FFTW), intent(inout) :: comm_sph_FFTW
      subroutine copy_all_rtp_FFTW_to_send_smp                        &
     &         (irt_rtp_smp_stack, Nfft_c, ncomp_fwd, C_fft,          &
     &          comm_sph_FFTW, n_WS, WS)
      subroutine copy_1comp_rtp_FFTW_to_send_smp                      &
     &         (nd, irt_rtp_smp_stack, Nfft_c, ncomp_fwd, C_fft,      &
     &          comm_sph_FFTW, n_WS, WS)
      subroutine copy_all_rtp_FFTW_to_send                            &
     &         (nnod_rtp, irt_rtp_smp_stack, ncomp_fwd,               &
     &          X_FFT, comm_sph_FFTW, n_WS, WS)
      subroutine copy_1comp_rtp_FFTW_to_send(nd, nnod_rt, Nfft_c,     &
     &          ncomp_fwd, C_fft, comm_sph_FFTW, n_WS, WS)
        type(comm_tbl_from_FFTW), intent(in) :: comm_sph_FFTW
      subroutine copy_all_prt_FFTW_to_send(nnod_rtp, nnod_rt,         &
     &          ncomp_fwd, Nfft_c, C_fft, comm_sph_FFTW, n_WS, WS)
      subroutine copy_1comp_prt_FFTW_to_send(nd, nnod_rtp, nnod_rt,   &
     &          ncomp_fwd, Nfft_c, C_fft, comm_sph_FFTW, n_WS, WS)
Function/Subroutine Documentation
alloc_comm_table_sph_fftw()
subroutine t_sph_comm_table_from_fftw::alloc_comm_table_sph_fftw (integer(kind = kint), intent(in) ntot_sr_rtp, type(comm_tbl_from_fftw), intent(inout) comm_sph_FFTW)
Definition at line 67 of file t_sph_comm_table_from_FFTW.f90.
Referenced by sph_prt_fftw::init_prt_fftw(), sph_prt_domain_fftw::init_prt_field_fftw(), sph_rtp_fftw::init_rtp_fftw(), and sph_rtp_domain_fftw::init_rtp_field_fftw().
copy_1comp_prt_fftw_to_send()
subroutine t_sph_comm_table_from_fftw::copy_1comp_prt_fftw_to_send (integer(kind = kint), intent(in) nd, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) nnod_rt, integer(kind = kint), intent(in) ncomp_fwd, integer(kind = kint), intent(in) Nfft_c, complex(kind = fftw_complex), dimension(nfft_c,nnod_rt), intent(in) C_fft, type(comm_tbl_from_fftw), intent(in) comm_sph_FFTW, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 270 of file t_sph_comm_table_from_FFTW.f90.
Referenced by sph_prt_domain_fftw::prt_field_fwd_fftw_to_send().
copy_1comp_rtp_fftw_to_send()
subroutine t_sph_comm_table_from_fftw::copy_1comp_rtp_fftw_to_send (integer(kind = kint), intent(in) nd, integer(kind = kint), intent(in) nnod_rt, integer(kind = kint), intent(in) Nfft_c, integer(kind = kint), intent(in) ncomp_fwd, complex(kind = fftw_complex), dimension(nnod_rt,nfft_c), intent(in) C_fft, type(comm_tbl_from_fftw), intent(in) comm_sph_FFTW, integer(kind = kint), intent(in) n_WS, real(kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 203 of file t_sph_comm_table_from_FFTW.f90.
copy_1comp_rtp_fftw_to_send_smp()
subroutine t_sph_comm_table_from_fftw::copy_1comp_rtp_fftw_to_send_smp (integer(kind = kint), intent(in) nd, integer(kind = kint), dimension(0:np_smp), intent(in) irt_rtp_smp_stack, integer(kind = kint), intent(in) Nfft_c, integer(kind = kint), intent(in) ncomp_fwd, complex(kind = fftw_complex), dimension(irt_rtp_smp_stack(np_smp)*nfft_c), intent(in) C_fft, type(comm_tbl_from_fftw), intent(in) comm_sph_FFTW, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 132 of file t_sph_comm_table_from_FFTW.f90.
Referenced by sph_rtp_domain_fftw::rtp_field_fwd_fftw_to_send().
copy_all_prt_fftw_to_send()
subroutine t_sph_comm_table_from_fftw::copy_all_prt_fftw_to_send (integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) nnod_rt, integer(kind = kint), intent(in) ncomp_fwd, integer(kind = kint), intent(in) Nfft_c, complex(kind = fftw_complex), dimension(nfft_c,nnod_rt,ncomp_fwd), intent(in) C_fft, type(comm_tbl_from_fftw), intent(in) comm_sph_FFTW, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 236 of file t_sph_comm_table_from_FFTW.f90.
Referenced by sph_prt_fftw::prt_fwd_fftw_to_send().
copy_all_rtp_fftw_to_send()
subroutine t_sph_comm_table_from_fftw::copy_all_rtp_fftw_to_send (integer(kind = kint), intent(in) nnod_rt, integer(kind = kint), intent(in) Nfft_c, integer(kind = kint), intent(in) ncomp_fwd, complex(kind = fftw_complex), dimension(ncomp_fwd,nnod_rt,nfft_c), intent(in) C_fft, type(comm_tbl_from_fftw), intent(in) comm_sph_FFTW, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 171 of file t_sph_comm_table_from_FFTW.f90.
copy_all_rtp_fftw_to_send_smp()
subroutine t_sph_comm_table_from_fftw::copy_all_rtp_fftw_to_send_smp (integer(kind = kint), dimension(0:np_smp), intent(in) irt_rtp_smp_stack, integer(kind = kint), intent(in) Nfft_c, integer(kind = kint), intent(in) ncomp_fwd, complex(kind = fftw_complex), dimension(irt_rtp_smp_stack(np_smp)*nfft_c*ncomp_fwd), intent(in) C_fft, type(comm_tbl_from_fftw), intent(in) comm_sph_FFTW, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 94 of file t_sph_comm_table_from_FFTW.f90.
Referenced by sph_rtp_fftw::rtp_fwd_fftw_to_send().
dealloc_comm_table_sph_fftw()
subroutine t_sph_comm_table_from_fftw::dealloc_comm_table_sph_fftw (type(comm_tbl_from_fftw), intent(inout) comm_sph_FFTW)
Definition at line 82 of file t_sph_comm_table_from_FFTW.f90.
Referenced by t_sph_field_fftw::finalize_sph_field_fftw().