CALYPSO: load_data_for_sph_io Module Reference
load_data_for_sph_io Module Reference
load spherical harmonics indexing data
Functions/Subroutines
subroutine copy_sph_trans_rtp_from_io (sph_file, sph_rtp, comm_rtp, sph_grps, sph_params)
subroutine copy_sph_trans_rj_from_io (sph_file, sph_rj, comm_rj, sph_grps, sph_params)
subroutine copy_sph_trans_rtm_from_io (sph_file, sph_rtm, comm_rtm, sph_params)
subroutine copy_sph_trans_rlm_from_io (sph_file, sph_rlm, comm_rlm, sph_params)
subroutine copy_sph_trans_rtp_to_io (sph_params, sph_rtp, comm_rtp, sph_grps, sph_file)
subroutine copy_sph_trans_rj_to_io (sph_params, sph_rj, comm_rj, sph_grps, sph_file)
subroutine copy_sph_trans_rtm_to_io (sph_params, sph_rtm, comm_rtm, sph_file)
subroutine copy_sph_trans_rlm_to_io (sph_params, sph_rlm, comm_rlm, sph_file)
Detailed Description
load spherical harmonics indexing data
      subroutine copy_sph_trans_rtp_from_IO(sph_grps_IO,              &
     &          sph_rtp, comm_rtp, sph_grps, sph_params)
        type(sph_file_data_type), intent(in) :: sph_file
        type(sph_shell_parameters), intent(inout) :: sph_params
        type(sph_rtp_grid), intent(inout) :: sph_rtp
        type(sph_comm_tbl), intent(inout) :: comm_rtp
        type(sph_group_data), intent(inout) :: sph_grps
      subroutine copy_sph_trans_rj_from_IO(sph_grps_IO,               &
     &          sph_rj, comm_rj, sph_grps, sph_params)
        type(sph_file_data_type), intent(in) :: sph_file
        type(sph_shell_parameters), intent(inout) :: sph_params
        type(sph_rj_grid),  intent(inout) :: sph_rj
        type(sph_comm_tbl), intent(inout) :: comm_rj
        type(sph_group_data), intent(inout) :: sph_grps
      subroutine copy_sph_trans_rtm_from_IO                           &
     &         (sph_file, sph_rtm, comm_rtm, sph_params)
        type(sph_file_data_type), intent(in) :: sph_file
        type(sph_shell_parameters), intent(inout) :: sph_params
        type(sph_rtm_grid), intent(inout) :: sph_rtm
        type(sph_comm_tbl), intent(inout) :: comm_rtm
      subroutine copy_sph_trans_rlm_from_IO                           &
     &         (sph_file, sph_rlm, comm_rlm, sph_params)
        type(sph_file_data_type), intent(in) :: sph_file
        type(sph_shell_parameters), intent(inout) :: sph_params
        type(sph_rlm_grid), intent(inout) :: sph_rlm
        type(sph_comm_tbl), intent(inout) :: comm_rlm
      subroutine copy_sph_trans_rtp_to_IO                             &
     &         (sph_params, sph_rtp, comm_rtp, sph_grps, sph_file)
        type(sph_shell_parameters), intent(in) :: sph_params
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_comm_tbl), intent(in) :: comm_rtp
        type(sph_group_data), intent(in) :: sph_grps
        type(sph_file_data_type), intent(inout) :: sph_file
      subroutine copy_sph_trans_rj_to_IO(sph_params,                  &
     &          sph_rj, comm_rj, sph_grps, sph_file)
        type(sph_shell_parameters), intent(in) :: sph_params
        type(sph_rj_grid),  intent(in) :: sph_rj
        type(sph_comm_tbl), intent(in) :: comm_rj
        type(sph_group_data), intent(in) :: sph_grps
        type(sph_file_data_type), intent(inout) :: sph_file
      subroutine copy_sph_trans_rtm_to_IO                             &
     &         (sph_params, sph_rtm, comm_rtm, sph_file)
        type(sph_shell_parameters), intent(in) :: sph_params
        type(sph_rtm_grid), intent(in) :: sph_rtm
        type(sph_comm_tbl), intent(in) :: comm_rtm
        type(sph_file_data_type), intent(inout) :: sph_file
      subroutine copy_sph_trans_rlm_to_IO                             &
     &         (sph_params, sph_rlm, comm_rlm, sph_file)
        type(sph_shell_parameters), intent(in) :: sph_params
        type(sph_rlm_grid), intent(in) :: sph_rlm
        type(sph_comm_tbl), intent(in) :: comm_rlm
        type(sph_file_data_type), intent(inout) :: sph_file
Function/Subroutine Documentation
copy_sph_trans_rj_from_io()
subroutine load_data_for_sph_io::copy_sph_trans_rj_from_io (type(sph_file_data_type), intent(in) sph_file, type(sph_rj_grid), intent(inout) sph_rj, type(sph_comm_tbl), intent(inout) comm_rj, type(sph_group_data), intent(inout) sph_grps, type(sph_shell_parameters), intent(inout) sph_params)
Definition at line 117 of file load_data_for_sph_IO.f90.
References copy_sph_comm_table_4_io::copy_comm_sph_from_io(), copy_sph_rj_mode_4_io::copy_sph_node_4_rj_from_io(), and set_group_types_4_io::set_gruop_stracture().
Referenced by output_gen_sph_grid_modes::load_local_rj_mesh_4_merge(), parallel_load_data_4_sph::load_sph_mesh(), and parallel_load_data_4_sph::load_sph_rj_mesh().
copy_sph_trans_rj_to_io()
subroutine load_data_for_sph_io::copy_sph_trans_rj_to_io (type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(sph_comm_tbl), intent(in) comm_rj, type(sph_group_data), intent(in) sph_grps, type(sph_file_data_type), intent(inout) sph_file)
Definition at line 223 of file load_data_for_sph_IO.f90.
References copy_sph_comm_table_4_io::copy_comm_sph_to_comm_tbl(), copy_sph_rj_mode_4_io::copy_sph_node_4_rj_to_io(), and set_group_types_4_io::set_gruop_stracture().
Referenced by parallel_load_data_4_sph::output_sph_mesh(), parallel_load_data_4_sph::output_sph_rj_mesh(), output_gen_sph_grid_modes::para_output_sph_mode_grids(), and output_gen_sph_grid_modes::para_output_sph_rj_modes().
copy_sph_trans_rlm_from_io()
subroutine load_data_for_sph_io::copy_sph_trans_rlm_from_io (type(sph_file_data_type), intent(in) sph_file, type(sph_rlm_grid), intent(inout) sph_rlm, type(sph_comm_tbl), intent(inout) comm_rlm, type(sph_shell_parameters), intent(inout) sph_params)
Definition at line 168 of file load_data_for_sph_IO.f90.
References copy_sph_comm_table_4_io::copy_comm_sph_from_io(), and copy_sph_rlm_mode_4_io::copy_sph_node_4_rlm_from_io().
Referenced by parallel_load_data_4_sph::load_sph_mesh().
copy_sph_trans_rlm_to_io()
subroutine load_data_for_sph_io::copy_sph_trans_rlm_to_io (type(sph_shell_parameters), intent(in) sph_params, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_comm_tbl), intent(in) comm_rlm, type(sph_file_data_type), intent(inout) sph_file)
Definition at line 272 of file load_data_for_sph_IO.f90.
References copy_sph_comm_table_4_io::copy_comm_sph_to_comm_tbl(), and copy_sph_rlm_mode_4_io::copy_sph_node_4_rlm_to_io().
Referenced by parallel_load_data_4_sph::output_sph_mesh(), and output_gen_sph_grid_modes::para_output_sph_mode_grids().
copy_sph_trans_rtm_from_io()
subroutine load_data_for_sph_io::copy_sph_trans_rtm_from_io (type(sph_file_data_type), intent(in) sph_file, type(sph_rtm_grid), intent(inout) sph_rtm, type(sph_comm_tbl), intent(inout) comm_rtm, type(sph_shell_parameters), intent(inout) sph_params)
Definition at line 146 of file load_data_for_sph_IO.f90.
References copy_sph_comm_table_4_io::copy_comm_sph_from_io(), and copy_sph_rtm_node_4_io::copy_sph_node_4_rtm_from_io().
Referenced by parallel_load_data_4_sph::load_sph_mesh().
copy_sph_trans_rtm_to_io()
subroutine load_data_for_sph_io::copy_sph_trans_rtm_to_io (type(sph_shell_parameters), intent(in) sph_params, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_comm_tbl), intent(in) comm_rtm, type(sph_file_data_type), intent(inout) sph_file)
Definition at line 251 of file load_data_for_sph_IO.f90.
References copy_sph_comm_table_4_io::copy_comm_sph_to_comm_tbl(), and copy_sph_rtm_node_4_io::copy_sph_node_4_rtm_to_io().
Referenced by parallel_load_data_4_sph::output_sph_mesh(), and output_gen_sph_grid_modes::para_output_sph_mode_grids().
copy_sph_trans_rtp_from_io()
subroutine load_data_for_sph_io::copy_sph_trans_rtp_from_io (type(sph_file_data_type), intent(in) sph_file, type(sph_rtp_grid), intent(inout) sph_rtp, type(sph_comm_tbl), intent(inout) comm_rtp, type(sph_group_data), intent(inout) sph_grps, type(sph_shell_parameters), intent(inout) sph_params)
Definition at line 84 of file load_data_for_sph_IO.f90.
References copy_sph_comm_table_4_io::copy_comm_sph_from_io(), copy_sph_rtp_node_4_io::copy_sph_node_4_rtp_from_io(), and set_group_types_4_io::set_gruop_stracture().
Referenced by parallel_load_data_4_sph::load_sph_mesh().
copy_sph_trans_rtp_to_io()
subroutine load_data_for_sph_io::copy_sph_trans_rtp_to_io (type(sph_shell_parameters), intent(in) sph_params, type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, type(sph_group_data), intent(in) sph_grps, type(sph_file_data_type), intent(inout) sph_file)
Definition at line 191 of file load_data_for_sph_IO.f90.
References copy_sph_comm_table_4_io::copy_comm_sph_to_comm_tbl(), copy_sph_rtp_node_4_io::copy_sph_node_4_rtp_to_io(), and set_group_types_4_io::set_gruop_stracture().
Referenced by parallel_load_data_4_sph::output_sph_mesh(), and output_gen_sph_grid_modes::para_output_sph_mode_grids().