CALYPSO: set_initial_sph_scalars Module Reference
set_initial_sph_scalars Module Reference
Set initial data for spectrum dynamos.
Functions/Subroutines
subroutine set_ini_reference_temp_sph (is_temp, reftemp_rj, sph_rj, ref_param, nlayer_ICB, nlayer_CMB, n_point, ntot_phys_rj, d_rj)
subroutine set_initial_temp_sph (isig, is_temp, sph_rj, r_ICB, r_CMB, nlayer_ICB, nlayer_CMB, n_point, ntot_phys_rj, d_rj)
subroutine set_initial_light_sph (isig, is_fld, sph_rj, r_ICB, r_CMB, nlayer_ICB, nlayer_CMB, reftemp_rj, n_point, ntot_phys_rj, d_rj)
subroutine set_all_part_temp_sph (is_temp, sph_rj, r_ICB, r_CMB, nlayer_ICB, nlayer_CMB, n_point, ntot_phys_rj, d_rj)
subroutine set_noize_scalar_sph (is_fld, reftemp_rj, sph_rj, ref_param, r_ICB, r_CMB, nlayer_ICB, nlayer_CMB, n_point, ntot_phys_rj, d_rj)
Detailed Description
Set initial data for spectrum dynamos.
      subroutine set_ini_reference_temp_sph                           &
     &         (is_temp, reftemp_rj, sph_rj, ref_param,               &
     &          nlayer_ICB, nlayer_CMB, n_point, ntot_phys_rj, d_rj)
        type(sph_rj_grid), intent(in) :: sph_rj
        type(reference_scalar_param), intent(in) :: ref_param
      subroutine set_initial_temp_sph(isig, is_temp, sph_rj,          &
     &          r_ICB, r_CMB, nlayer_ICB, nlayer_CMB,                 &
     &          n_point, ntot_phys_rj, d_rj)
        type(sph_rj_grid), intent(in) :: sph_rj
      subroutine set_initial_light_sph(isig, is_fld, sph_rj,          &
     &          r_ICB, r_CMB, nlayer_ICB, nlayer_CMB,                 &
     &          reftemp_rj, n_point, ntot_phys_rj, d_rj)
        type(sph_rj_grid), intent(in) :: sph_rj
      subroutine set_all_part_temp_sph(is_temp, sph_rj,               &
     &          r_ICB, r_CMB, nlayer_ICB, nlayer_CMB,                 &
     &          n_point, ntot_phys_rj, d_rj)
        type(sph_rj_grid), intent(in) :: sph_rj
      subroutine set_noize_scalar_sph(is_fld, reftemp_rj, sph_rj,     &
     &          ref_param, r_ICB, r_CMB, nlayer_ICB, nlayer_CMB,      &
     &          n_point, ntot_phys_rj, d_rj)
        type(sph_rj_grid), intent(in) :: sph_rj
        type(reference_scalar_param), intent(in) :: ref_param
Function/Subroutine Documentation
set_all_part_temp_sph()
subroutine set_initial_sph_scalars::set_all_part_temp_sph (integer(kind = kint), intent(in) is_temp, type(sph_rj_grid), intent(in) sph_rj, real(kind = kreal), intent(in) r_ICB, real(kind = kreal), intent(in) r_CMB, integer(kind = kint), intent(in) nlayer_ICB, integer(kind = kint), intent(in) nlayer_CMB, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 215 of file set_initial_sph_scalars.f90.
References m_constants::four, m_constants::one, m_constants::six, m_constants::three, and m_constants::two.
Referenced by set_initial_sph_dynamo::sph_initial_field_4_licv().
set_ini_reference_temp_sph()
subroutine set_initial_sph_scalars::set_ini_reference_temp_sph (integer(kind = kint), intent(in) is_temp, real(kind=kreal), dimension(sph_rj%nidx_rj(1),0:1), intent(in) reftemp_rj, type(sph_rj_grid), intent(in) sph_rj, type(reference_scalar_param), intent(in) ref_param, integer(kind = kint), intent(in) nlayer_ICB, integer(kind = kint), intent(in) nlayer_CMB, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 53 of file set_initial_sph_scalars.f90.
References t_reference_scalar_param::id_sphere_ref_temp, and m_constants::zero.
Referenced by set_initial_sph_dynamo::sph_initial_data_4_benchmarks(), and set_initial_sph_dynamo::sph_initial_field_4_licv().
set_initial_light_sph()
subroutine set_initial_sph_scalars::set_initial_light_sph (integer (kind = kint), intent(in) isig, integer (kind = kint), intent(in) is_fld, type(sph_rj_grid), intent(in) sph_rj, real(kind = kreal), intent(in) r_ICB, real(kind = kreal), intent(in) r_CMB, integer(kind = kint), intent(in) nlayer_ICB, integer(kind = kint), intent(in) nlayer_CMB, real(kind=kreal), dimension(sph_rj%nidx_rj(1),0:1), intent(in) reftemp_rj, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 153 of file set_initial_sph_scalars.f90.
References m_constants::four, m_constants::icent, m_constants::ikilo, m_constants::one, m_constants::three, m_constants::two, and m_constants::zero.
Referenced by set_initial_sph_dynamo::sph_initial_data_4_benchmarks().
set_initial_temp_sph()
subroutine set_initial_sph_scalars::set_initial_temp_sph (integer (kind = kint), intent(in) isig, integer (kind = kint), intent(in) is_temp, type(sph_rj_grid), intent(in) sph_rj, real(kind = kreal), intent(in) r_ICB, real(kind = kreal), intent(in) r_CMB, integer(kind = kint), intent(in) nlayer_ICB, integer(kind = kint), intent(in) nlayer_CMB, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 109 of file set_initial_sph_scalars.f90.
References m_constants::four, m_constants::icent, m_constants::ikilo, m_constants::one, m_constants::three, and m_constants::two.
Referenced by set_initial_sph_dynamo::sph_initial_data_4_benchmarks().
set_noize_scalar_sph()
subroutine set_initial_sph_scalars::set_noize_scalar_sph (integer(kind = kint), intent(in) is_fld, real(kind=kreal), dimension(sph_rj%nidx_rj(1),0:1), intent(in) reftemp_rj, type(sph_rj_grid), intent(in) sph_rj, type(reference_scalar_param), intent(in) ref_param, real(kind = kreal), intent(in) r_ICB, real(kind = kreal), intent(in) r_CMB, integer(kind = kint), intent(in) nlayer_ICB, integer(kind = kint), intent(in) nlayer_CMB, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 256 of file set_initial_sph_scalars.f90.
References m_constants::four, t_reference_scalar_param::id_sphere_ref_temp, m_constants::one, m_constants::six, m_constants::three, m_constants::two, and m_constants::zero.
Referenced by set_initial_sph_dynamo::sph_initial_data_w_seed_b().