CALYPSO: m_elapsed_labels_send_recv Module Reference
m_elapsed_labels_send_recv Module Reference
Labels for elapsed time monitor.
Functions/Subroutines
subroutine elpsed_label_field_send_recv
subroutine elpsed_label_calypso_send_recv
subroutine reset_elapse_after_init_sr
Variables
logical, save iflag_fsr_time = .FALSE.
integer(kind=kint), save ist_elapsed_fsr = 0
integer(kind=kint), save, private ied_elapsed_fsr = 0
logical, save iflag_csr_time = .FALSE.
integer(kind=kint), save ist_elapsed_csr = 0
integer(kind=kint), save, private ied_elapsed_csr = 0
Detailed Description
Labels for elapsed time monitor.
      subroutine elpsed_label_field_send_recv
      subroutine elpsed_label_calypso_send_recv
      subroutine reset_elapse_after_init_SR
Function/Subroutine Documentation
elpsed_label_calypso_send_recv()
subroutine m_elapsed_labels_send_recv::elpsed_label_calypso_send_recv
Definition at line 54 of file m_elapsed_labels_SEND_RECV.f90.
References m_work_time::append_elapsed_times(), m_work_time::elps1, ied_elapsed_csr, iflag_csr_time, and ist_elapsed_csr.
Referenced by analyzer_test_sph::init_test_sph(), and init_sph_mhd_elapsed_label::set_sph_mhd_elapsed_label().
elpsed_label_field_send_recv()
subroutine m_elapsed_labels_send_recv::elpsed_label_field_send_recv
Definition at line 38 of file m_elapsed_labels_SEND_RECV.f90.
References m_work_time::append_elapsed_times(), m_work_time::elps1, ied_elapsed_fsr, iflag_fsr_time, and ist_elapsed_fsr.
Referenced by analyzer_psf::init_analyzer_psf(), analyzer_vtk_convert::init_analyzer_vtk_convert(), analyzer_test_sph::init_test_sph(), sph_analyzer_add_initial::initialize_add_sph_initial(), sph_analyzer_const_initial::initialize_const_sph_initial(), analyzer_sph_dynamobench::initialize_sph_dynamobench(), analyzer_sph_mhd_w_psf::initialize_sph_mhd_w_psf(), and analyzer_sph_snap_w_psf::initialize_sph_snap_w_psf().
reset_elapse_after_init_sr()
subroutine m_elapsed_labels_send_recv::reset_elapse_after_init_sr
Definition at line 73 of file m_elapsed_labels_SEND_RECV.f90.
References ied_elapsed_csr, ied_elapsed_fsr, iflag_csr_time, ist_elapsed_csr, ist_elapsed_fsr, and m_work_time::reset_elapsed_times().
Referenced by init_sph_mhd_elapsed_label::reset_elapse_4_init_sph_mhd().
Variable Documentation
ied_elapsed_csr
integer(kind = kint), save, private m_elapsed_labels_send_recv::ied_elapsed_csr = 0 private
Definition at line 30 of file m_elapsed_labels_SEND_RECV.f90.
Referenced by elpsed_label_calypso_send_recv(), and reset_elapse_after_init_sr().
ied_elapsed_fsr
integer(kind = kint), save, private m_elapsed_labels_send_recv::ied_elapsed_fsr = 0 private
Definition at line 26 of file m_elapsed_labels_SEND_RECV.f90.
Referenced by elpsed_label_field_send_recv(), and reset_elapse_after_init_sr().
iflag_csr_time
logical, save m_elapsed_labels_send_recv::iflag_csr_time = .FALSE.
Definition at line 28 of file m_elapsed_labels_SEND_RECV.f90.
Referenced by spherical_srs_n::calypso_sph_to_send_n(), elpsed_label_calypso_send_recv(), reset_elapse_after_init_sr(), sel_spherical_srs::sel_calypso_from_recv_n(), sel_spherical_srs::sel_calypso_sph_comm_n(), sel_spherical_srs::sel_calypso_to_send_n(), sel_spherical_srs::sel_calypso_to_send_scalar(), sel_spherical_srs::sel_calypso_to_send_tensor(), sel_spherical_srs::sel_calypso_to_send_vector(), sel_spherical_srs::sel_sph_scalar_from_recv(), sel_spherical_srs::sel_sph_tensor_from_recv(), and sel_spherical_srs::sel_sph_vector_from_recv().
iflag_fsr_time
logical, save m_elapsed_labels_send_recv::iflag_fsr_time = .FALSE.
Definition at line 24 of file m_elapsed_labels_SEND_RECV.f90.
Referenced by elpsed_label_field_send_recv(), solver_sr_type::solver_send_recv_1x3_type(), solver_sr_type::solver_send_recv_3_type(), solver_sr_type::solver_send_recv_3x3_type(), solver_sr_type::solver_send_recv_6_type(), solver_sr_type::solver_send_recv_int8_type(), solver_sr_type::solver_send_recv_int_type(), solver_sr_type::solver_send_recv_n_type(), solver_sr_type::solver_send_recv_num_type(), solver_sr_type::solver_send_recv_nx3_type(), and solver_sr_type::solver_send_recv_type().
ist_elapsed_csr
integer(kind = kint), save m_elapsed_labels_send_recv::ist_elapsed_csr = 0
Definition at line 29 of file m_elapsed_labels_SEND_RECV.f90.
Referenced by spherical_srs_n::calypso_sph_to_send_n(), elpsed_label_calypso_send_recv(), reset_elapse_after_init_sr(), sel_spherical_srs::sel_calypso_from_recv_n(), sel_spherical_srs::sel_calypso_sph_comm_n(), sel_spherical_srs::sel_calypso_to_send_n(), sel_spherical_srs::sel_calypso_to_send_scalar(), sel_spherical_srs::sel_calypso_to_send_tensor(), sel_spherical_srs::sel_calypso_to_send_vector(), sel_spherical_srs::sel_sph_scalar_from_recv(), sel_spherical_srs::sel_sph_tensor_from_recv(), and sel_spherical_srs::sel_sph_vector_from_recv().
ist_elapsed_fsr
integer(kind = kint), save m_elapsed_labels_send_recv::ist_elapsed_fsr = 0
Definition at line 25 of file m_elapsed_labels_SEND_RECV.f90.
Referenced by elpsed_label_field_send_recv(), reset_elapse_after_init_sr(), solver_sr_type::solver_send_recv_1x3_type(), solver_sr_type::solver_send_recv_3_type(), solver_sr_type::solver_send_recv_3x3_type(), solver_sr_type::solver_send_recv_6_type(), solver_sr_type::solver_send_recv_int8_type(), solver_sr_type::solver_send_recv_int_type(), solver_sr_type::solver_send_recv_n_type(), solver_sr_type::solver_send_recv_num_type(), solver_sr_type::solver_send_recv_nx3_type(), and solver_sr_type::solver_send_recv_type().