CALYPSO: set_radial_mat_sph Module Reference
set_radial_mat_sph Module Reference
Construct matrix for spherical shell dynamo model.
Functions/Subroutines
subroutine set_unit_mat5_4_time_evo (nri, jmax, mat5)
subroutine set_unit_mat_4_time_evo (nri, jmax, mat3)
subroutine set_unit_mat_4_poisson (nri, jmax, kr_in, kr_out, mat3)
subroutine add_scalar_poisson_mat_sph (nri, jmax, ar_1d_rj, g_sph_rj, kr_in, kr_out, coef_p, d1nod_mat_fdm_2, d2nod_mat_fdm_2, mat3)
subroutine add_vector_poisson_mat_sph (nri, jmax, ar_1d_rj, g_sph_rj, kr_in, kr_out, coef_p, d2nod_mat_fdm_2, mat3)
subroutine add_scalar_r_diffuse_mat_sph (nri, jmax, ar_1d_rj, g_sph_rj, kr_in, kr_out, coef_p, val_r, dval_r, d1nod_mat_fdm_2, d2nod_mat_fdm_2, mat3)
subroutine add_vector_r_diffuse_mat_sph (nri, jmax, ar_1d_rj, g_sph_rj, kr_in, kr_out, coef_p, d2nod_mat_fdm_2, mat3)
Detailed Description
Construct matrix for spherical shell dynamo model.
      subroutine set_unit_mat5_4_time_evo(nri, jmax, mat5)
      subroutine set_unit_mat_4_time_evo(nri, jmax, mat3)
      subroutine set_unit_mat_4_poisson(nri, jmax, kr_in, kr_out,     &
     &          mat3)
      subroutine add_scalar_poisson_mat_sph(nri, jmax, ar_1d_rj,      &
     &         g_sph_rj, kr_in, kr_out, coef_p,                       &
     &         d1nod_mat_fdm_2, d2nod_mat_fdm_2, mat3)
      subroutine add_vector_poisson_mat_sph(nri, jmax, ar_1d_rj,      &
     &         g_sph_rj, kr_in, kr_out, coef_p, d2nod_mat_fdm_2, mat3)
      subroutine add_scalar_r_diffuse_mat_sph(nri, jmax, ar_1d_rj,    &
     &         g_sph_rj, kr_in, kr_out, coef_p, val_r, dval_r,        &
     &         d1nod_mat_fdm_2, d2nod_mat_fdm_2, mat3)
      subroutine add_vector_r_diffuse_mat_sph(nri, jmax, ar_1d_rj,    &
     &         g_sph_rj, kr_in, kr_out, coef_p, d2nod_mat_fdm_2, mat3)
    Format of band matrix
               | a(2,1)  a(1,2)  ........     0         0     |
               | a(3,1)  a(2,2)  ........     .         .     |
               |   0     a(3,2)  ........     .         .     |
    a(i,j)  =  |   .       0     ........     0         .     |
               | ...... a(3,k-1)  a(2,k)  a(1,k+1) .......... |
               |   .       .     ........  a(1,N-2)     0     |
               |   .       .     ........  a(2,N-2)  a(1,N-1) |
               |   0       0     ........  a(3,N-2)  a(2,N-1) |
   Original band matrix
      band_a(i-j+iband+1,j) = a(i,j)
      band_a(k,j) = a(k+j-iband-1,j)
   3-band matrix
      band_a(i-j+2,j) = a(i,j)
      band_a(k,j) = a(k+j-2,j)
   5-band matrix
      band_lu(i-j+3,j) = a(i,j)
      band_lu(k,j) = a(k+j-3,j)
   7-band matrix
      band_lu(i-j+4,j) = a(i,j)
      band_lu(k,j) = a(k+j-4,j)
Parameters
nri Number of radial points
jmax Number of spherical harmonics modes
kr_st Start radial address to construct matrix
kr_ed End radial address to construct matrix
kr_in Radial address for inner boundary
kr_out Radial address for outer boundary
coef_d Coefficient of diffusiotn term
coef_p Coefficient of pressure gradient
Parameters
mat5(5,nri,jmax) Band matrix
mat3(3,nri,jmax) Band matrix
Function/Subroutine Documentation
add_scalar_poisson_mat_sph()
subroutine set_radial_mat_sph::add_scalar_poisson_mat_sph (integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(nri,3), intent(in) ar_1d_rj, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) kr_out, real(kind = kreal), intent(in) coef_p, real(kind = kreal), dimension(nri,-1:1), intent(in) d1nod_mat_fdm_2, real(kind = kreal), dimension(nri,-1:1), intent(in) d2nod_mat_fdm_2, real(kind = kreal), dimension(3,nri,jmax), intent(inout) mat3)
Definition at line 171 of file set_radial_mat_sph.f90.
References m_constants::two.
Referenced by const_r_mat_4_scalar_sph::const_radial_mat_4_press_sph(), and const_r_mat_4_scalar_sph::const_radial_mat_4_scalar_sph().
add_scalar_r_diffuse_mat_sph()
subroutine set_radial_mat_sph::add_scalar_r_diffuse_mat_sph (integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(nri,3), intent(in) ar_1d_rj, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) kr_out, real(kind = kreal), intent(in) coef_p, real(kind = kreal), dimension(nri), intent(in) val_r, real(kind = kreal), dimension(nri), intent(in) dval_r, real(kind = kreal), dimension(nri,-1:1), intent(in) d1nod_mat_fdm_2, real(kind = kreal), dimension(nri,-1:1), intent(in) d2nod_mat_fdm_2, real(kind = kreal), dimension(3,nri,jmax), intent(inout) mat3)
Definition at line 243 of file set_radial_mat_sph.f90.
References m_constants::two.
add_vector_poisson_mat_sph()
subroutine set_radial_mat_sph::add_vector_poisson_mat_sph (integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(nri,3), intent(in) ar_1d_rj, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) kr_out, real(kind = kreal), intent(in) coef_p, real(kind = kreal), dimension(nri,-1:1), intent(in) d2nod_mat_fdm_2, real(kind = kreal), dimension(3,nri,jmax), intent(inout) mat3)
Definition at line 209 of file set_radial_mat_sph.f90.
Referenced by const_r_mat_4_vector_sph::const_radial_mat_4_magne_sph(), and const_r_mat_4_vector_sph::const_radial_mat_vort_2step().
add_vector_r_diffuse_mat_sph()
subroutine set_radial_mat_sph::add_vector_r_diffuse_mat_sph (integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(nri,3), intent(in) ar_1d_rj, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) kr_out, real(kind = kreal), intent(in) coef_p, real(kind = kreal), dimension(nri,-1:1), intent(in) d2nod_mat_fdm_2, real(kind = kreal), dimension(3,nri,jmax), intent(inout) mat3)
Definition at line 285 of file set_radial_mat_sph.f90.
set_unit_mat5_4_time_evo()
subroutine set_radial_mat_sph::set_unit_mat5_4_time_evo (integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(5,nri,jmax), intent(inout) mat5)
Definition at line 77 of file set_radial_mat_sph.f90.
References m_constants::one, and m_constants::zero.
set_unit_mat_4_poisson()
subroutine set_radial_mat_sph::set_unit_mat_4_poisson (integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) kr_out, real(kind = kreal), dimension(3,nri,jmax), intent(inout) mat3)
Definition at line 137 of file set_radial_mat_sph.f90.
References m_constants::one, and m_constants::zero.
Referenced by const_r_mat_4_vector_sph::const_radial_mat_4_magne_sph(), const_r_mat_4_scalar_sph::const_radial_mat_4_press_sph(), const_r_mat_4_scalar_sph::const_radial_mat_4_scalar_sph(), and const_r_mat_4_vector_sph::const_radial_mat_vort_2step().
set_unit_mat_4_time_evo()
subroutine set_radial_mat_sph::set_unit_mat_4_time_evo (integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(3,nri,jmax), intent(inout) mat3)
Definition at line 110 of file set_radial_mat_sph.f90.
References m_constants::one, and m_constants::zero.
Referenced by const_r_mat_4_vector_sph::const_radial_mat_4_magne_sph(), const_r_mat_4_scalar_sph::const_radial_mat_4_scalar_sph(), and const_r_mat_4_vector_sph::const_radial_mat_vort_2step().