CALYPSO: bcast_comm_stacks_sph Module Reference
bcast_comm_stacks_sph Module Reference
Distribute number of data for communication.
Functions/Subroutines
subroutine mpi_bcast_comm_stacks_sph (ndomain_sph, comm_sph)
subroutine para_bcast_comm_stacks_sph (ndomain_sph, comm_sph)
subroutine dealloc_comm_stacks_sph (ndomain_sph, comm_rtm)
subroutine, private set_bcast_comm_stacks_sph (ndomain_sph, nneib_rtm_tmp, comm_sph)
subroutine allocate_nneib_rtm_lc
subroutine deallocate_nneib_rtm_lc
Variables
integer(kind=kint), dimension(:), allocatable, private nneib_rtm_lc
integer(kind=kint), dimension(:), allocatable, private nneib_rtm_gl
Detailed Description
Distribute number of data for communication.
      subroutine mpi_bcast_comm_stacks_sph(ndomain_sph, comm_sph)
      subroutine para_bcast_comm_stacks_sph(ndomain_sph, comm_sph)
        type(sph_comm_tbl), intent(inout) :: comm_sph(ndomain_sph)
      subroutine dealloc_comm_stacks_sph(ndomain_sph, comm_rtm)
        type(sph_comm_tbl), intent(inout) :: comm_rtm(ndomain_sph)
Function/Subroutine Documentation
allocate_nneib_rtm_lc()
subroutine bcast_comm_stacks_sph::allocate_nneib_rtm_lc
Definition at line 215 of file bcast_comm_stacks_sph.f90.
References nneib_rtm_gl, nneib_rtm_lc, and calypso_mpi::nprocs.
dealloc_comm_stacks_sph()
subroutine bcast_comm_stacks_sph::dealloc_comm_stacks_sph (integer(kind = kint), intent(in) ndomain_sph, type(sph_comm_tbl), dimension(ndomain_sph), intent(inout) comm_rtm)
Definition at line 125 of file bcast_comm_stacks_sph.f90.
References t_sph_trans_comm_tbl::dealloc_type_sph_comm_stack(), calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by mpi_gen_sph_grids_modes::mpi_gen_sph_grids(), mpi_gen_sph_grids_modes::mpi_gen_sph_rj_mode(), t_parai_gen_sph_grids_modes::para_gen_sph_rlm_rj_modes(), and t_parai_gen_sph_grids_modes::para_gen_sph_rtm_rtp_grids().
deallocate_nneib_rtm_lc()
subroutine bcast_comm_stacks_sph::deallocate_nneib_rtm_lc
Definition at line 222 of file bcast_comm_stacks_sph.f90.
References nneib_rtm_lc.
Referenced by para_bcast_comm_stacks_sph().
mpi_bcast_comm_stacks_sph()
subroutine bcast_comm_stacks_sph::mpi_bcast_comm_stacks_sph (integer(kind = kint), intent(in) ndomain_sph, type(sph_comm_tbl), dimension(ndomain_sph), intent(inout) comm_sph)
Definition at line 39 of file bcast_comm_stacks_sph.f90.
References calypso_mpi_int::calypso_mpi_allgather_one_int(), calypso_mpi::calypso_mpi_barrier(), calypso_mpi::my_rank, nneib_rtm_gl, and set_bcast_comm_stacks_sph().
Referenced by mpi_gen_sph_grids_modes::mpi_gen_sph_grids(), and mpi_gen_sph_grids_modes::mpi_gen_sph_rj_mode().
para_bcast_comm_stacks_sph()
subroutine bcast_comm_stacks_sph::para_bcast_comm_stacks_sph (integer(kind = kint), intent(in) ndomain_sph, type(sph_comm_tbl), dimension(ndomain_sph), intent(inout) comm_sph)
Definition at line 71 of file bcast_comm_stacks_sph.f90.
References calypso_mpi_int::calypso_mpi_allgather_one_int(), calypso_mpi::calypso_mpi_barrier(), deallocate_nneib_rtm_lc(), calypso_mpi::my_rank, nneib_rtm_gl, nneib_rtm_lc, calypso_mpi::nprocs, and set_bcast_comm_stacks_sph().
Referenced by t_parai_gen_sph_grids_modes::para_gen_sph_rlm_rj_modes(), and t_parai_gen_sph_grids_modes::para_gen_sph_rtm_rtp_grids().
set_bcast_comm_stacks_sph()
subroutine, private bcast_comm_stacks_sph::set_bcast_comm_stacks_sph (integer(kind = kint), intent(in) ndomain_sph, integer(kind = kint), dimension(ndomain_sph), intent(in) nneib_rtm_tmp, type(sph_comm_tbl), dimension(ndomain_sph), intent(inout) comm_sph) private
Definition at line 153 of file bcast_comm_stacks_sph.f90.
References t_sph_trans_comm_tbl::alloc_sph_comm_stack(), calypso_mpi::calypso_mpi_barrier(), calypso_mpi_int::calypso_mpi_bcast_int(), transfer_to_long_integers::cast_long(), t_sph_trans_comm_tbl::dealloc_type_sph_comm_stack(), calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by mpi_bcast_comm_stacks_sph(), and para_bcast_comm_stacks_sph().
Variable Documentation
nneib_rtm_gl
integer(kind = kint), dimension(:), allocatable, private bcast_comm_stacks_sph::nneib_rtm_gl private
Definition at line 29 of file bcast_comm_stacks_sph.f90.
Referenced by allocate_nneib_rtm_lc(), mpi_bcast_comm_stacks_sph(), and para_bcast_comm_stacks_sph().
nneib_rtm_lc
integer(kind = kint), dimension(:), allocatable, private bcast_comm_stacks_sph::nneib_rtm_lc private
Definition at line 28 of file bcast_comm_stacks_sph.f90.
Referenced by allocate_nneib_rtm_lc(), deallocate_nneib_rtm_lc(), and para_bcast_comm_stacks_sph().