CALYPSO: cal_sol_sph_mhd_crank Module Reference
cal_sol_sph_mhd_crank Module Reference
Update fields for MHD dynamo model.
Functions/Subroutines
subroutine s_cal_sol_sph_mhd_crank (dt, sph_rj, r_2nd, MHD_prop, sph_MHD_bc, leg, ipol, sph_MHD_mat, rj_fld)
subroutine set_sph_field_to_start (sph_rj, r_2nd, MHD_prop, sph_MHD_bc, leg, ipol, rj_fld)
subroutine, private update_after_vorticity_sph (sph_rj, r_2nd, fl_prop, sph_bc_U, fdm2_free_ICB, fdm2_free_CMB, leg, ipol, rj_fld)
subroutine update_after_magne_sph (sph_rj, r_2nd, cd_prop, sph_bc_B, leg, ipol, rj_fld)
subroutine, private update_after_heat_sph (sph_rj, r_2nd, ht_prop, sph_bc_T, bcs_T, fdm2_center, leg, ipol, rj_fld)
subroutine, private update_after_composit_sph (sph_rj, r_2nd, cp_prop, sph_bc_C, bcs_C, fdm2_center, leg, ipol, rj_fld)
subroutine check_vs_spectr (sph_rj, ipol, rj_fld)
subroutine check_ws_spectr (sph_rj, ipol, rj_fld)
Detailed Description
Update fields for MHD dynamo model.
      subroutine s_cal_sol_sph_MHD_crank                              &
     &         (dt, sph_rj, r_2nd, MHD_prop, sph_MHD_bc, leg,         &
     &          ipol, sph_MHD_mat, rj_fld)
      subroutine set_sph_field_to_start(sph_rj, r_2nd,                &
     &          MHD_prop, sph_MHD_bc, leg, ipol, rj_fld)
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(fdm_matrices), intent(in) :: r_2nd
        type(legendre_4_sph_trans), intent(in) :: leg
        type(MHD_evolution_param), intent(in) :: MHD_prop
        type(sph_MHD_boundary_data), intent(in) :: sph_MHD_bc
        type(phys_address), intent(in) :: ipol
        type(MHD_radial_matrices), intent(inout) :: sph_MHD_mat
        type(phys_data), intent(inout) :: rj_fld
      subroutine check_vs_spectr(sph_rj, ipol, rj_fld)
      subroutine check_ws_spectr(sph_rj, ipol, rj_fld)
      subroutine update_after_magne_sph(sph_rj, r_2nd,                &
     &          cd_prop, sph_bc_B, leg, ipol, rj_fld)
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(fdm_matrices), intent(in) :: r_2nd
        type(conductive_property), intent(in) :: cd_prop
        type(sph_boundary_type), intent(in) :: sph_bc_B
        type(legendre_4_sph_trans), intent(in) :: leg
        type(phys_address), intent(in) :: ipol
        type(phys_data), intent(inout) :: rj_fld
Function/Subroutine Documentation
check_vs_spectr()
subroutine cal_sol_sph_mhd_crank::check_vs_spectr (type(sph_rj_grid), intent(in) sph_rj, type(phys_address), intent(in) ipol, type(phys_data), intent(in) rj_fld)
Definition at line 386 of file cal_sol_sph_MHD_crank.f90.
References calypso_mpi::my_rank.
check_ws_spectr()
subroutine cal_sol_sph_mhd_crank::check_ws_spectr (type(sph_rj_grid), intent(in) sph_rj, type(phys_address), intent(in) ipol, type(phys_data), intent(in) rj_fld)
Definition at line 409 of file cal_sol_sph_MHD_crank.f90.
References calypso_mpi::my_rank.
s_cal_sol_sph_mhd_crank()
subroutine cal_sol_sph_mhd_crank::s_cal_sol_sph_mhd_crank (real(kind = kreal), intent(in) dt, type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(mhd_evolution_param), intent(in) MHD_prop, type(sph_mhd_boundary_data), intent(in) sph_MHD_bc, type(legendre_4_sph_trans), intent(in) leg, type(phys_address), intent(in) ipol, type(mhd_radial_matrices), intent(inout) sph_MHD_mat, type(phys_data), intent(inout) rj_fld)
Definition at line 70 of file cal_sol_sph_MHD_crank.f90.
References cal_sol_sph_fluid_crank::cal_sol_magne_sph_crank(), cal_sol_sph_fluid_crank::cal_sol_scalar_sph_crank(), cal_sol_sph_fluid_crank::cal_sol_velo_by_vort_sph_crank(), const_sph_radial_grad::const_grad_bp_and_current(), const_sph_radial_grad::const_grad_vp_and_vorticity(), t_physical_property::id_no_evolution, m_machine_parameter::iflag_debug, update_after_composit_sph(), update_after_heat_sph(), update_after_magne_sph(), and update_after_vorticity_sph().
Referenced by sph_analyzer_mhd::sph_analyze_mhd().
set_sph_field_to_start()
subroutine cal_sol_sph_mhd_crank::set_sph_field_to_start (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(mhd_evolution_param), intent(in) MHD_prop, type(sph_mhd_boundary_data), intent(in) sph_MHD_bc, type(legendre_4_sph_trans), intent(in) leg, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld)
Definition at line 172 of file cal_sol_sph_MHD_crank.f90.
References const_sph_radial_grad::const_grad_bp_and_current(), const_sph_radial_grad::const_grad_vp_and_vorticity(), t_physical_property::id_no_evolution, m_machine_parameter::iflag_debug, update_after_composit_sph(), update_after_heat_sph(), update_after_magne_sph(), and update_after_vorticity_sph().
Referenced by sph_analyzer_d_bench::sph_analyze_dbench(), sph_analyzer_snap_w_psf::sph_analyze_snap_psf(), and sph_analyzer_mhd::sph_initialize_mhd().
update_after_composit_sph()
subroutine, private cal_sol_sph_mhd_crank::update_after_composit_sph (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(scalar_property), intent(in) cp_prop, type(sph_boundary_type), intent(in) sph_bc_C, type(sph_scalar_boundary_data), intent(in) bcs_C, type(fdm2_center_mat), intent(in) fdm2_center, type(legendre_4_sph_trans), intent(in) leg, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld) private
Definition at line 345 of file cal_sol_sph_MHD_crank.f90.
References const_sph_radial_grad::const_radial_grad_scalar(), const_sph_diffusion::const_sph_scalar_diffusion(), and m_machine_parameter::iflag_debug.
Referenced by s_cal_sol_sph_mhd_crank(), and set_sph_field_to_start().
update_after_heat_sph()
subroutine, private cal_sol_sph_mhd_crank::update_after_heat_sph (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(scalar_property), intent(in) ht_prop, type(sph_boundary_type), intent(in) sph_bc_T, type(sph_scalar_boundary_data), intent(in) bcs_T, type(fdm2_center_mat), intent(in) fdm2_center, type(legendre_4_sph_trans), intent(in) leg, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld) private
Definition at line 306 of file cal_sol_sph_MHD_crank.f90.
References const_sph_radial_grad::const_radial_grad_scalar(), const_sph_diffusion::const_sph_scalar_diffusion(), and m_machine_parameter::iflag_debug.
Referenced by s_cal_sol_sph_mhd_crank(), and set_sph_field_to_start().
update_after_magne_sph()
subroutine cal_sol_sph_mhd_crank::update_after_magne_sph (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(conductive_property), intent(in) cd_prop, type(sph_boundary_type), intent(in) sph_bc_B, type(legendre_4_sph_trans), intent(in) leg, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld)
Definition at line 277 of file cal_sol_sph_MHD_crank.f90.
References const_sph_rotation::const_sph_mag_diffuse_by_j(), and m_machine_parameter::iflag_debug.
Referenced by s_cal_sol_sph_mhd_crank(), and set_sph_field_to_start().
update_after_vorticity_sph()
subroutine, private cal_sol_sph_mhd_crank::update_after_vorticity_sph (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(fluid_property), intent(in) fl_prop, type(sph_boundary_type), intent(in) sph_bc_U, type(fdm2_free_slip), intent(in) fdm2_free_ICB, type(fdm2_free_slip), intent(in) fdm2_free_CMB, type(legendre_4_sph_trans), intent(in) leg, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld) private
Definition at line 225 of file cal_sol_sph_MHD_crank.f90.
References const_sph_rotation::const_sph_viscous_by_vort2(), const_sph_diffusion::const_sph_vorticirty_diffusion(), m_machine_parameter::iflag_debug, t_boundary_params_sph_mhd::iflag_rotatable_ic, and cal_inner_core_rotation::set_inner_core_rotation().
Referenced by s_cal_sol_sph_mhd_crank(), and set_sph_field_to_start().