CALYPSO: gz_spherical_model_io Module Reference
gz_spherical_model_io Module Reference
Data IO routines for spectrum data.
Functions/Subroutines
subroutine read_rank_4_sph_gz (sph_IO, zbuf)
subroutine read_gl_resolution_sph_gz (sph_IO, zbuf)
subroutine read_gl_nodes_sph_gz (sph_IO, zbuf)
subroutine write_rank_4_sph_gz (sph_IO, zbuf)
subroutine write_gl_resolution_sph_gz (sph_IO, zbuf)
subroutine write_gl_nodes_sph_gz (sph_IO, zbuf)
Detailed Description
Data IO routines for spectrum data.
      subroutine read_rank_4_sph_gz(sph_IO, zbuf)
      subroutine read_gl_resolution_sph_gz(sph_IO, zbuf)
      subroutine read_gl_nodes_sph_gz(sph_IO, zbuf)
        type(sph_IO_data), intent(inout) :: sph_IO
        type(buffer_4_gzip), intent(inout) :: zbuf
      subroutine write_rank_4_sph_gz(sph_IO, zbuf)
      subroutine write_gl_resolution_sph_gz(sph_IO, zbuf)
      subroutine write_gl_nodes_sph_gz(sph_IO, zbuf)
        type(sph_IO_data), intent(in) :: sph_IO
        type(buffer_4_gzip), intent(inout) :: zbuf
Function/Subroutine Documentation
read_gl_nodes_sph_gz()
subroutine gz_spherical_model_io::read_gl_nodes_sph_gz (type(sph_io_data), intent(inout) sph_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 70 of file gz_spherical_model_IO.f90.
References t_node_id_spherical_io::alloc_nod_id_sph_io(), gzip_file_access::get_one_line_text_from_gz(), and skip_gz_comment::skip_gz_comment_int().
Referenced by gz_sph_modes_grids_data_io::read_geom_rtm_data_gz(), gz_sph_modes_grids_data_io::read_geom_rtp_data_gz(), gz_sph_modes_grids_data_io::read_spectr_modes_rj_data_gz(), and gz_sph_modes_grids_data_io::read_spectr_modes_rlm_data_gz().
read_gl_resolution_sph_gz()
subroutine gz_spherical_model_io::read_gl_resolution_sph_gz (type(sph_io_data), intent(inout) sph_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 53 of file gz_spherical_model_IO.f90.
References skip_gz_comment::skip_gz_comment_int().
Referenced by gz_sph_modes_grids_data_io::read_geom_rtm_data_gz(), gz_sph_modes_grids_data_io::read_geom_rtp_data_gz(), gz_sph_modes_grids_data_io::read_spectr_modes_rj_data_gz(), and gz_sph_modes_grids_data_io::read_spectr_modes_rlm_data_gz().
read_rank_4_sph_gz()
subroutine gz_spherical_model_io::read_rank_4_sph_gz (type(sph_io_data), intent(inout) sph_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 38 of file gz_spherical_model_IO.f90.
References skip_gz_comment::skip_gz_comment_int().
Referenced by gz_sph_modes_grids_data_io::read_geom_rtm_data_gz(), gz_sph_modes_grids_data_io::read_geom_rtp_data_gz(), gz_sph_modes_grids_data_io::read_spectr_modes_rj_data_gz(), and gz_sph_modes_grids_data_io::read_spectr_modes_rlm_data_gz().
write_gl_nodes_sph_gz()
subroutine gz_spherical_model_io::write_gl_nodes_sph_gz (type(sph_io_data), intent(in) sph_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 148 of file gz_spherical_model_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf().
Referenced by gz_sph_modes_grids_data_io::write_geom_rtm_data_gz(), gz_sph_modes_grids_data_io::write_geom_rtp_data_gz(), gz_sph_modes_grids_data_io::write_modes_rlm_data_gz(), and gz_sph_modes_grids_data_io::write_spectr_modes_rj_data_gz().
write_gl_resolution_sph_gz()
subroutine gz_spherical_model_io::write_gl_resolution_sph_gz (type(sph_io_data), intent(in) sph_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 120 of file gz_spherical_model_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf(), and m_sph_modes_grid_labels::hd_trunc().
Referenced by gz_sph_modes_grids_data_io::write_geom_rtm_data_gz(), gz_sph_modes_grids_data_io::write_geom_rtp_data_gz(), gz_sph_modes_grids_data_io::write_modes_rlm_data_gz(), and gz_sph_modes_grids_data_io::write_spectr_modes_rj_data_gz().
write_rank_4_sph_gz()
subroutine gz_spherical_model_io::write_rank_4_sph_gz (type(sph_io_data), intent(in) sph_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 96 of file gz_spherical_model_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf(), and m_sph_modes_grid_labels::hd_segment().
Referenced by gz_sph_modes_grids_data_io::write_geom_rtm_data_gz(), gz_sph_modes_grids_data_io::write_geom_rtp_data_gz(), gz_sph_modes_grids_data_io::write_modes_rlm_data_gz(), and gz_sph_modes_grids_data_io::write_spectr_modes_rj_data_gz().