CALYPSO: ucd_field_mpi_io_b Module Reference
ucd_field_mpi_io_b Module Reference
Output merged binary field file using MPI-IO.
Functions/Subroutines
subroutine write_ucd_field_file_mpi_b (file_name, t_IO, ucd)
subroutine read_ucd_field_file_mpi_b (file_name, num_pe, id_rank, t_IO, ucd)
subroutine read_alloc_ucd_fld_file_mpi_b (file_name, num_pe, id_rank, t_IO, ucd)
Variables
type(calypso_mpi_io_params), save, private io_param
Detailed Description
Output merged binary field file using MPI-IO.
      subroutine write_ucd_field_file_mpi_b(file_name, t_IO, ucd)
        type(time_data), intent(in) :: t_IO
        type(ucd_data), intent(in) :: ucd
      subroutine read_ucd_field_file_mpi_b                            &
     &         (file_name, num_pe, id_rank, t_IO, ucd)
      subroutine read_alloc_ucd_fld_file_mpi_b                        &
     &         (file_name, num_pe, id_rank, t_IO, ucd)
        type(time_data), intent(inout) :: t_IO
        type(ucd_data), intent(inout) :: ucd
   Data format for the merged binary field data
     1.   Number of process
     2.   Time step
     3.   Time, Delta t
     4.   Stacks of numbe of data points
     5.   Number of fields
     6.   List of number of components
     7.   Field names
     8.   List of data size (Byte)
     9.   All Field data
Function/Subroutine Documentation
read_alloc_ucd_fld_file_mpi_b()
subroutine ucd_field_mpi_io_b::read_alloc_ucd_fld_file_mpi_b (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, type(time_data), intent(inout) t_IO, type(ucd_data), intent(inout) ucd)
Definition at line 128 of file ucd_field_MPI_IO_b.f90.
References t_ucd_data::allocate_ucd_phys_data(), t_ucd_data::allocate_ucd_phys_name(), t_ucd_data::cal_istack_ucd_component(), mpi_ascii_data_io::close_mpi_file(), t_ucd_data::deallocate_ucd_phys_data(), t_ucd_data::deallocate_ucd_phys_name(), io_param, mpi_binary_data_io::mpi_read_2d_vector_b(), mpi_binary_head_io::mpi_read_mul_charahead_b(), mpi_binary_head_io::mpi_read_mul_inthead_b(), mpi_binary_head_io::mpi_read_one_inthead_b(), calypso_mpi::my_rank, mpi_binary_head_io::open_read_mpi_file_b(), and field_block_mpi_io_b::read_field_header_mpi_b().
Referenced by parallel_ucd_io_select::sel_read_alloc_para_udt_file().
read_ucd_field_file_mpi_b()
subroutine ucd_field_mpi_io_b::read_ucd_field_file_mpi_b (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, type(time_data), intent(inout) t_IO, type(ucd_data), intent(inout) ucd)
Definition at line 84 of file ucd_field_MPI_IO_b.f90.
References mpi_ascii_data_io::close_mpi_file(), io_param, mpi_binary_data_io::mpi_read_2d_vector_b(), mpi_binary_head_io::mpi_read_mul_charahead_b(), mpi_binary_head_io::mpi_read_mul_inthead_b(), mpi_binary_head_io::mpi_read_one_inthead_b(), calypso_mpi::my_rank, mpi_binary_head_io::open_read_mpi_file_b(), and field_block_mpi_io_b::read_field_header_mpi_b().
Referenced by parallel_ucd_io_select::sel_read_parallel_udt_file().
write_ucd_field_file_mpi_b()
subroutine ucd_field_mpi_io_b::write_ucd_field_file_mpi_b (character(len=kchara), intent(in) file_name, type(time_data), intent(in) t_IO, type(ucd_data), intent(in) ucd)
Definition at line 56 of file ucd_field_MPI_IO_b.f90.
References mpi_ascii_data_io::close_mpi_file(), io_param, calypso_mpi::my_rank, mpi_binary_head_io::open_write_mpi_file_b(), field_block_mpi_io_b::write_field_data_mpi_b(), and field_block_mpi_io_b::write_field_time_mpi_b().
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_file().
Variable Documentation
io_param
type(calypso_mpi_io_params), save, private ucd_field_mpi_io_b::io_param private
Definition at line 48 of file ucd_field_MPI_IO_b.f90.
Referenced by read_alloc_ucd_fld_file_mpi_b(), read_ucd_field_file_mpi_b(), and write_ucd_field_file_mpi_b().