CALYPSO: vtk_data_to_buffer Module Reference
vtk_data_to_buffer Module Reference
Output routine for VTK data segments.
Functions/Subroutines
character(n) function make_string (n)
character(len=nchara) function vtk_fields_head (nnod)
character(len=9+len_trim(field_name)+8+16+1+20+1) function vtk_scalar_head (field_name)
character(len=9+len_trim(field_name)+8+1) function vtk_vector_head (field_name)
character(len=9+len_trim(field_name)+8+1) function vtk_tensor_head (field_name)
character(len=25+1) function vtk_each_scalar (d_nod)
character(len=3 *25+1) function vtk_each_vector (d1, d2, d3)
character(len=nchara) function vtk_node_head (nnod)
character(len=nchara) function vtk_connect_head (nele, nnod_ele)
character(len=nchara) function vtk_cell_type_head (nele)
integer(kind=kint) function vtk_cell_type (nnod_ele)
character(len=5+1) function vtk_each_cell_type (icellid)
character(len=16+16 *nnod_ele+1) function vtk_each_connect (nnod_ele, ie0)
Variables
character(len=26), parameter, private vtk_hd1 = '# vtk DataFile Version 2.0'
character(len=47), parameter, private vtk_hd2 = 'converted data of tri-linear hexahedral element'
character(len=5), parameter, private vtk_hd3 = 'ASCII'
character(len=25), parameter, private vtk_hd4 = 'DATASET UNSTRUCTURED_GRID'
character(len=8), parameter, private vtk_hd5 = ' POINTS '
character(len=8), parameter, private vtk_hd6 = ' double '
integer(kind=kint) len_vtk_hd1 = 26 + 1
integer(kind=kint) len_vtk_hd2 = 47 + 1
integer(kind=kint) len_vtk_hd3 = 5 + 1
integer(kind=kint) len_vtk_hd4 = 25 + 1
integer(kind=kint) len_vtk_hd5 = 8+ 16 + 8 + 1
character(len= *), parameter, private vtk_pt1 = 'POINT_DATA '
character(len= *), parameter, private vtk_cl1 = ' CELLS '
character(len= *), parameter, private vtk_cl2 = ' CELL_TYPES '
character(len= *), parameter, private vtk_sc1 = ' SCALARS '
character(len= *), parameter, private vtk_vc1 = ' VECTORS '
character(len= *), parameter, private vtk_ts1 = ' TENSORS '
character(len= *), parameter, private vtk_lk1 = 'LOOKUP_TABLE default'
Detailed Description
Output routine for VTK data segments.
      function vtk_fields_head(nnod)
      function vtk_scalar_head(field_name)
      function vtk_vector_head(field_name)
      function vtk_tensor_head(field_name)
      function vtk_each_scalar(d_nod)
      function vtk_each_vector(d1, d2, d3)
      function vtk_node_head(nnod)
      function vtk_connect_head(nele, nnod_ele)
      function vtk_cell_type_head(nele)
      integer(kind = kint) function vtk_cell_type(nnod_ele)
      function vtk_each_cell_type(icellid)
      function vtk_each_connect(nnod_ele, ie0)
Parameters
nnod Number of nodes
nele Number of elements
nnod_ele number of nodes for each element
ie0(nnod_ele) element connectivity
ntot_comp total number of components
field_name field name
d_nod scalar data
d_nod x-component
d_nod y-component
d_nod z-component
Function/Subroutine Documentation
make_string()
character(n) function vtk_data_to_buffer::make_string (integer, intent(in) n)
Definition at line 83 of file vtk_data_to_buffer.f90.
vtk_cell_type()
integer(kind = kint) function vtk_data_to_buffer::vtk_cell_type (integer(kind = kint), intent(in) nnod_ele)
Definition at line 241 of file vtk_data_to_buffer.f90.
References m_geometry_constants::num_linear_edge, m_geometry_constants::num_t_linear, m_geometry_constants::num_t_quad, and m_geometry_constants::num_triangle.
Referenced by zlib_cvt_vtk_data::defleate_vtk_celltype(), gz_vtk_data_io::write_gz_vtk_cell_type(), vtk_file_mpi_io::write_vtk_celltype_mpi(), and vtk_data_io::write_vtk_connect_data().
vtk_cell_type_head()
character(len=nchara) function vtk_data_to_buffer::vtk_cell_type_head (integer(kind = kint_gl), intent(in) nele)
Definition at line 227 of file vtk_data_to_buffer.f90.
References vtk_cl2.
Referenced by gz_vtk_file_mpi_io::gz_write_vtk_mesh_mpi(), gz_vtk_data_io::write_gz_vtk_cell_type(), vtk_data_io::write_vtk_connect_data(), and vtk_file_mpi_io::write_vtk_mesh_mpi().
vtk_connect_head()
character(len=nchara) function vtk_data_to_buffer::vtk_connect_head (integer(kind = kint_gl), intent(in) nele, integer(kind = kint), intent(in) nnod_ele)
Definition at line 210 of file vtk_data_to_buffer.f90.
References vtk_cl1.
Referenced by gz_vtk_file_mpi_io::gz_write_vtk_mesh_mpi(), gz_vtk_data_io::write_gz_vtk_connect_head(), vtk_data_io::write_vtk_connect_data(), and vtk_file_mpi_io::write_vtk_mesh_mpi().
vtk_each_cell_type()
character(len=5+1) function vtk_data_to_buffer::vtk_each_cell_type (integer(kind = kint), intent(in) icellid)
Definition at line 264 of file vtk_data_to_buffer.f90.
Referenced by zlib_cvt_vtk_data::defleate_vtk_celltype(), gz_vtk_data_io::write_gz_vtk_cell_type(), vtk_file_mpi_io::write_vtk_celltype_mpi(), and vtk_data_io::write_vtk_connect_data().
vtk_each_connect()
character(len=16+16*nnod_ele+1) function vtk_data_to_buffer::vtk_each_connect (integer(kind = kint), intent(in) nnod_ele, integer(kind = kint_gl), dimension(nnod_ele), intent(in) ie0)
Definition at line 276 of file vtk_data_to_buffer.f90.
Referenced by zlib_cvt_vtk_data::defleate_vtk_connect(), gz_vtk_data_io::write_gz_vtk_connect_data(), vtk_data_io::write_vtk_connect_data(), and vtk_file_mpi_io::write_vtk_connect_mpi().
vtk_each_scalar()
character(len=25+1) function vtk_data_to_buffer::vtk_each_scalar (real(kind = kreal), intent(in) d_nod)
Definition at line 161 of file vtk_data_to_buffer.f90.
Referenced by zlib_cvt_vtk_data::defleate_vtk_scalar(), and gz_vtk_data_io::write_gz_vtk_each_field().
vtk_each_vector()
character(len=3*25+1) function vtk_data_to_buffer::vtk_each_vector (real(kind = kreal), intent(in) d1, real(kind = kreal), intent(in) d2, real(kind = kreal), intent(in) d3)
Definition at line 172 of file vtk_data_to_buffer.f90.
Referenced by zlib_cvt_vtk_data::defleate_vtk_tensor(), zlib_cvt_vtk_data::defleate_vtk_vector(), and gz_vtk_data_io::write_gz_vtk_each_field().
vtk_fields_head()
character(len=nchara) function vtk_data_to_buffer::vtk_fields_head (integer(kind=kint_gl), intent(in) nnod)
Definition at line 93 of file vtk_data_to_buffer.f90.
References vtk_pt1.
Referenced by gz_vtk_file_mpi_io::gz_write_vtk_data_mpi(), gz_vtk_data_io::write_gz_vtk_fields_head(), vtk_file_mpi_io::write_vtk_data_mpi(), and vtk_data_io::write_vtk_fields_head().
vtk_node_head()
character(len=nchara) function vtk_data_to_buffer::vtk_node_head (integer(kind = kint_gl), intent(in) nnod)
Definition at line 184 of file vtk_data_to_buffer.f90.
References vtk_hd1, vtk_hd2, vtk_hd3, vtk_hd4, vtk_hd5, and vtk_hd6.
Referenced by gz_vtk_file_mpi_io::gz_write_vtk_mesh_mpi(), gz_vtk_data_io::write_gz_vtk_node_head(), vtk_file_mpi_io::write_vtk_mesh_mpi(), and vtk_data_io::write_vtk_node_head().
vtk_scalar_head()
character(len=9+len_trim(field_name) +8+16+1+20+1) function vtk_data_to_buffer::vtk_scalar_head (character(len=kchara), intent(in) field_name)
Definition at line 112 of file vtk_data_to_buffer.f90.
References m_constants::ione, vtk_hd6, vtk_lk1, and vtk_sc1.
Referenced by gz_vtk_file_mpi_io::gz_write_vtk_data_mpi(), gz_vtk_data_io::write_gz_vtk_each_field_head(), vtk_file_mpi_io::write_vtk_data_mpi(), and vtk_data_io::write_vtk_each_field_head().
vtk_tensor_head()
character(len=9+len_trim(field_name) +8+1) function vtk_data_to_buffer::vtk_tensor_head (character(len=kchara), intent(in) field_name)
Definition at line 145 of file vtk_data_to_buffer.f90.
References vtk_hd6, and vtk_ts1.
Referenced by gz_vtk_file_mpi_io::gz_write_vtk_data_mpi(), gz_vtk_data_io::write_gz_vtk_each_field_head(), vtk_file_mpi_io::write_vtk_data_mpi(), and vtk_data_io::write_vtk_each_field_head().
vtk_vector_head()
character(len=9+len_trim(field_name) +8+1) function vtk_data_to_buffer::vtk_vector_head (character(len=kchara), intent(in) field_name)
Definition at line 130 of file vtk_data_to_buffer.f90.
References vtk_hd6, and vtk_vc1.
Referenced by gz_vtk_file_mpi_io::gz_write_vtk_data_mpi(), gz_vtk_data_io::write_gz_vtk_each_field_head(), vtk_file_mpi_io::write_vtk_data_mpi(), and vtk_data_io::write_vtk_each_field_head().
Variable Documentation
len_vtk_hd1
integer(kind = kint) vtk_data_to_buffer::len_vtk_hd1 = 26 + 1
Definition at line 57 of file vtk_data_to_buffer.f90.
len_vtk_hd2
integer(kind = kint) vtk_data_to_buffer::len_vtk_hd2 = 47 + 1
Definition at line 58 of file vtk_data_to_buffer.f90.
len_vtk_hd3
integer(kind = kint) vtk_data_to_buffer::len_vtk_hd3 = 5 + 1
Definition at line 59 of file vtk_data_to_buffer.f90.
len_vtk_hd4
integer(kind = kint) vtk_data_to_buffer::len_vtk_hd4 = 25 + 1
Definition at line 60 of file vtk_data_to_buffer.f90.
len_vtk_hd5
integer(kind = kint) vtk_data_to_buffer::len_vtk_hd5 = 8+ 16 + 8 + 1
Definition at line 61 of file vtk_data_to_buffer.f90.
vtk_cl1
character(len=*), parameter, private vtk_data_to_buffer::vtk_cl1 = ' CELLS ' private
Definition at line 65 of file vtk_data_to_buffer.f90.
Referenced by vtk_connect_head().
vtk_cl2
character(len=*), parameter, private vtk_data_to_buffer::vtk_cl2 = ' CELL_TYPES ' private
Definition at line 66 of file vtk_data_to_buffer.f90.
Referenced by vtk_cell_type_head().
vtk_hd1
character(len=26), parameter, private vtk_data_to_buffer::vtk_hd1 = '# vtk DataFile Version 2.0' private
Definition at line 47 of file vtk_data_to_buffer.f90.
Referenced by vtk_node_head().
vtk_hd2
character(len=47), parameter, private vtk_data_to_buffer::vtk_hd2 = 'converted data of tri-linear hexahedral element' private
Definition at line 49 of file vtk_data_to_buffer.f90.
Referenced by vtk_node_head().
vtk_hd3
character(len=5), parameter, private vtk_data_to_buffer::vtk_hd3 = 'ASCII' private
Definition at line 51 of file vtk_data_to_buffer.f90.
Referenced by vtk_node_head().
vtk_hd4
character(len=25), parameter, private vtk_data_to_buffer::vtk_hd4 = 'DATASET UNSTRUCTURED_GRID' private
Definition at line 52 of file vtk_data_to_buffer.f90.
Referenced by vtk_node_head().
vtk_hd5
character(len=8), parameter, private vtk_data_to_buffer::vtk_hd5 = ' POINTS ' private
Definition at line 54 of file vtk_data_to_buffer.f90.
Referenced by vtk_node_head().
vtk_hd6
character(len=8), parameter, private vtk_data_to_buffer::vtk_hd6 = ' double ' private
Definition at line 55 of file vtk_data_to_buffer.f90.
Referenced by vtk_node_head(), vtk_scalar_head(), vtk_tensor_head(), and vtk_vector_head().
vtk_lk1
character(len=*), parameter, private vtk_data_to_buffer::vtk_lk1 = 'LOOKUP_TABLE default' private
Definition at line 71 of file vtk_data_to_buffer.f90.
Referenced by vtk_scalar_head().
vtk_pt1
character(len=*), parameter, private vtk_data_to_buffer::vtk_pt1 = 'POINT_DATA ' private
Definition at line 63 of file vtk_data_to_buffer.f90.
Referenced by vtk_fields_head().
vtk_sc1
character(len=*), parameter, private vtk_data_to_buffer::vtk_sc1 = ' SCALARS ' private
Definition at line 68 of file vtk_data_to_buffer.f90.
Referenced by vtk_scalar_head().
vtk_ts1
character(len=*), parameter, private vtk_data_to_buffer::vtk_ts1 = ' TENSORS ' private
Definition at line 70 of file vtk_data_to_buffer.f90.
Referenced by vtk_tensor_head().
vtk_vc1
character(len=*), parameter, private vtk_data_to_buffer::vtk_vc1 = ' VECTORS ' private
Definition at line 69 of file vtk_data_to_buffer.f90.
Referenced by vtk_vector_head().