CALYPSO: t_surface_data Module Reference
t_surface_data Module Reference
structure of surface data (geometry and connectivity)
Data Types
type surface_data
structure of surface data (geometry and connectivity)
Functions/Subroutines
subroutine alloc_numsurf_stack (num_pe, surf)
subroutine allocate_inod_in_surf (surf)
subroutine allocate_surface_connect_type (surf, nele)
subroutine allocate_ext_surface_type (surf)
subroutine allocate_iso_surface_type (surf)
subroutine allocate_surface_geom_type (surf)
subroutine allocate_normal_vect_type (surf)
subroutine allocate_surf_param_smp_type (surf)
subroutine alloc_ele_4_surf_type (surf)
subroutine dealloc_numsurf_stack (surf)
subroutine deallocate_inod_in_surf_type (surf)
subroutine deallocate_surface_connect_type (surf)
subroutine deallocate_ext_surface_type (surf)
subroutine deallocate_iso_surface_type (surf)
subroutine deallocate_surface_geom_type (surf)
subroutine deallocate_normal_vect_type (surf)
subroutine deallocate_surf_param_smp_type (surf)
subroutine dealloc_ele_4_surf_type (surf)
Detailed Description
structure of surface data (geometry and connectivity)
      subroutine alloc_numsurf_stack(num_pe, surf)
      subroutine allocate_inod_in_surf(surf)
      subroutine allocate_surface_connect_type(surf, nele)
      subroutine allocate_ext_surface_type(surf)
      subroutine allocate_iso_surface_type(surf)
      subroutine allocate_surface_geom_type(surf)
      subroutine allocate_normal_vect_type(surf)
      subroutine allocate_surf_param_smp_type(surf)
      subroutine alloc_ele_4_surf_type(surf)
      subroutine dealloc_numsurf_stack(surf)
      subroutine deallocate_inod_in_surf_type(surf)
      subroutine deallocate_surface_connect_type(surf)
      subroutine deallocate_ext_surface_type(surf)
      subroutine deallocate_iso_surface_type(surf)
      subroutine deallocate_surface_geom_type(surf)
      subroutine deallocate_normal_vect_type(surf)
      subroutine deallocate_surf_param_smp_type(surf)
      subroutine dealloc_ele_4_surf_type(surf)
        integer(kind = kint), intent(in) :: nele
        type(surface_data), intent(inout) :: surf
Function/Subroutine Documentation
alloc_ele_4_surf_type()
subroutine t_surface_data::alloc_ele_4_surf_type (type(surface_data), intent(inout) surf)
Definition at line 246 of file t_surface_data.f90.
Referenced by const_surface_data::const_ele_list_4_surface().
alloc_numsurf_stack()
subroutine t_surface_data::alloc_numsurf_stack (integer, intent(in) num_pe, type(surface_data), intent(inout) surf)
Definition at line 114 of file t_surface_data.f90.
Referenced by const_element_comm_tables::const_global_surface_id().
allocate_ext_surface_type()
subroutine t_surface_data::allocate_ext_surface_type (type(surface_data), intent(inout) surf)
Definition at line 171 of file t_surface_data.f90.
Referenced by const_surface_data::const_external_surface_data().
allocate_inod_in_surf()
subroutine t_surface_data::allocate_inod_in_surf (type(surface_data), intent(inout) surf)
Definition at line 129 of file t_surface_data.f90.
References m_geometry_constants::nsurf_4_ele.
Referenced by const_mesh_information::set_local_element_info().
allocate_iso_surface_type()
subroutine t_surface_data::allocate_iso_surface_type (type(surface_data), intent(inout) surf)
Definition at line 182 of file t_surface_data.f90.
Referenced by const_surface_data::const_isolate_surface_data().
allocate_normal_vect_type()
subroutine t_surface_data::allocate_normal_vect_type (type(surface_data), intent(inout) surf)
Definition at line 211 of file t_surface_data.f90.
Referenced by set_surface_data_4_io::copy_surf_geometry_from_io().
allocate_surf_param_smp_type()
subroutine t_surface_data::allocate_surf_param_smp_type (type(surface_data), intent(inout) surf)
Definition at line 233 of file t_surface_data.f90.
References m_machine_parameter::np_smp.
Referenced by set_size_4_smp_types::count_surf_size_smp_type(), and const_surface_data::empty_surface_connect().
allocate_surface_connect_type()
subroutine t_surface_data::allocate_surface_connect_type (type(surface_data), intent(inout) surf, integer(kind = kint), intent(in) nele)
Definition at line 146 of file t_surface_data.f90.
References m_geometry_constants::nsurf_4_ele.
Referenced by const_surface_data::const_all_surface_data(), set_surface_data_4_io::copy_surf_connect_from_io(), and const_surface_data::empty_surface_connect().
allocate_surface_geom_type()
subroutine t_surface_data::allocate_surface_geom_type (type(surface_data), intent(inout) surf)
Definition at line 193 of file t_surface_data.f90.
Referenced by set_surface_data_4_io::copy_surf_geometry_from_io(), set_surf_edge_mesh::empty_surface_and_edge(), and set_surf_edge_mesh::set_surf_geometry().
dealloc_ele_4_surf_type()
subroutine t_surface_data::dealloc_ele_4_surf_type (type(surface_data), intent(inout) surf)
Definition at line 347 of file t_surface_data.f90.
Referenced by t_mesh_data::dealloc_mesh_infomations().
dealloc_numsurf_stack()
subroutine t_surface_data::dealloc_numsurf_stack (type(surface_data), intent(inout) surf)
Definition at line 259 of file t_surface_data.f90.
Referenced by const_element_comm_tables::const_global_surface_id().
deallocate_ext_surface_type()
subroutine t_surface_data::deallocate_ext_surface_type (type(surface_data), intent(inout) surf)
Definition at line 295 of file t_surface_data.f90.
Referenced by t_mesh_data::dealloc_mesh_infomations().
deallocate_inod_in_surf_type()
subroutine t_surface_data::deallocate_inod_in_surf_type (type(surface_data), intent(inout) surf)
Definition at line 270 of file t_surface_data.f90.
Referenced by t_mesh_data::dealloc_nod_ele_infos().
deallocate_iso_surface_type()
subroutine t_surface_data::deallocate_iso_surface_type (type(surface_data), intent(inout) surf)
Definition at line 305 of file t_surface_data.f90.
Referenced by t_mesh_data::dealloc_mesh_infomations().
deallocate_normal_vect_type()
subroutine t_surface_data::deallocate_normal_vect_type (type(surface_data), intent(inout) surf)
Definition at line 325 of file t_surface_data.f90.
deallocate_surf_param_smp_type()
subroutine t_surface_data::deallocate_surf_param_smp_type (type(surface_data), intent(inout) surf)
Definition at line 337 of file t_surface_data.f90.
Referenced by t_mesh_data::dealloc_mesh_infomations().
deallocate_surface_connect_type()
subroutine t_surface_data::deallocate_surface_connect_type (type(surface_data), intent(inout) surf)
Definition at line 281 of file t_surface_data.f90.
Referenced by t_mesh_data::dealloc_ele_surf_edge_type(), and t_mesh_data::dealloc_mesh_infomations().
deallocate_surface_geom_type()
subroutine t_surface_data::deallocate_surface_geom_type (type(surface_data), intent(inout) surf)
Definition at line 315 of file t_surface_data.f90.
Referenced by t_mesh_data::dealloc_mesh_infomations().