CALYPSO: zonal_wavenumber_4_legendre Module Reference
zonal_wavenumber_4_legendre Module Reference
Set order of spheherical harmonics modes.
Functions/Subroutines
subroutine set_domain_by_eq_leg_trns (ndomain_m, ltr, m_folding, ip_tmp)
subroutine set_domain_by_eq_leg_modes (ndomain_m, ltr, m_folding, ip_tmp)
subroutine set_local_sph_fwd_order (ndomain_m, ltr, m_folding, nth, nph, ip_tmp, jdx_fsph, mdx_4_lgd)
subroutine set_local_sph_back_order (ndomain_m, ltr, m_folding, nth, nph, ip_tmp, jdx_fsph, mdx_4_lgd)
subroutine set_local_sph_neib_order (ndomain_m, ltr, m_folding, nth, nph, ip_tmp, jdx_fsph, mdx_4_lgd)
Detailed Description
Set order of spheherical harmonics modes.
      subroutine set_domain_by_eq_leg_trns                            &
     &         (ndomain_m, ltr, m_folding, ip_tmp)
      subroutine set_domain_by_eq_leg_modes                           &
     &         (ndomain_m, ltr, m_folding, ip_tmp)
      subroutine set_local_sph_fwd_order(ndomain_m, ltr, m_folding,   &
     &          nth, nph, ip_tmp, jdx_fsph, mdx_4_lgd)
      subroutine set_local_sph_back_order(ndomain_m, ltr, m_folding,  &
     &          nth, nph, ip_tmp, jdx_fsph, mdx_4_lgd)
      subroutine set_local_sph_neib_order(ndomain_m, ltr, m_folding,  &
     &          nth, nph, ip_tmp, jdx_fsph, mdx_4_lgd)
Function/Subroutine Documentation
set_domain_by_eq_leg_modes()
subroutine zonal_wavenumber_4_legendre::set_domain_by_eq_leg_modes (integer(kind = kint), intent(in) ndomain_m, integer(kind = kint), intent(in) ltr, integer(kind = kint), intent(in) m_folding, integer(kind = kint), dimension(0:ltr), intent(inout) ip_tmp)
Definition at line 78 of file zonal_wavenumber_4_legendre.f90.
Referenced by select_zonal_4_legendre::sel_zonal_ordering_4_leg_trns(), and select_zonal_4_legendre::zonal_wavenum_list_test().
set_domain_by_eq_leg_trns()
subroutine zonal_wavenumber_4_legendre::set_domain_by_eq_leg_trns (integer(kind = kint), intent(in) ndomain_m, integer(kind = kint), intent(in) ltr, integer(kind = kint), intent(in) m_folding, integer(kind = kint), dimension(0:ltr), intent(inout) ip_tmp)
Definition at line 35 of file zonal_wavenumber_4_legendre.f90.
Referenced by select_zonal_4_legendre::sel_zonal_ordering_4_leg_trns().
set_local_sph_back_order()
subroutine zonal_wavenumber_4_legendre::set_local_sph_back_order (integer(kind = kint), intent(in) ndomain_m, integer(kind = kint), intent(in) ltr, integer(kind = kint), intent(in) m_folding, integer(kind = kint), intent(in) nth, integer(kind = kint), intent(in) nph, integer(kind = kint), dimension(0:ltr), intent(in) ip_tmp, integer(kind = kint), dimension(-nth:nth), intent(inout) jdx_fsph, integer(kind = kint), dimension(0:nph), intent(inout) mdx_4_lgd)
Definition at line 166 of file zonal_wavenumber_4_legendre.f90.
Referenced by select_zonal_4_legendre::sel_zonal_ordering_4_leg_trns().
set_local_sph_fwd_order()
subroutine zonal_wavenumber_4_legendre::set_local_sph_fwd_order (integer(kind = kint), intent(in) ndomain_m, integer(kind = kint), intent(in) ltr, integer(kind = kint), intent(in) m_folding, integer(kind = kint), intent(in) nth, integer(kind = kint), intent(in) nph, integer(kind = kint), dimension(0:ltr), intent(in) ip_tmp, integer(kind = kint), dimension(-nth:nth), intent(inout) jdx_fsph, integer(kind = kint), dimension(0:nph), intent(inout) mdx_4_lgd)
Definition at line 133 of file zonal_wavenumber_4_legendre.f90.
Referenced by select_zonal_4_legendre::sel_zonal_ordering_4_leg_trns(), and select_zonal_4_legendre::zonal_wavenum_list_test().
set_local_sph_neib_order()
subroutine zonal_wavenumber_4_legendre::set_local_sph_neib_order (integer(kind = kint), intent(in) ndomain_m, integer(kind = kint), intent(in) ltr, integer(kind = kint), intent(in) m_folding, integer(kind = kint), intent(in) nth, integer(kind = kint), intent(in) nph, integer(kind = kint), dimension(0:ltr), intent(in) ip_tmp, integer(kind = kint), dimension(-nth:nth), intent(inout) jdx_fsph, integer(kind = kint), dimension(0:nph), intent(inout) mdx_4_lgd)
Definition at line 199 of file zonal_wavenumber_4_legendre.f90.
Referenced by select_zonal_4_legendre::sel_zonal_ordering_4_leg_trns().