CALYPSO: input_control_sph_mhd Module Reference
input_control_sph_mhd Module Reference
Load mesh and filtering data for MHD simulation.
Functions/Subroutines
subroutine input_control_sph_mhd_psf (MHD_files, DMHD_ctl, MHD_step, SPH_model, SPH_WK, SPH_MHD, FEM_dat)
subroutine input_control_4_sph_mhd_nosnap (MHD_files, DMHD_ctl, MHD_step, SPH_model, SPH_WK, SPH_MHD)
subroutine input_control_4_sph_make_init (MHD_files, DMHD_ctl, MHD_step, SPH_model, SPH_WK, SPH_MHD, FEM_dat)
Variables
type(sph_grid_maker_in_sim), save, private sph_maker1
Structure to construct grid.
Detailed Description
Load mesh and filtering data for MHD simulation.
      subroutine input_control_SPH_MHD_psf(MHD_files, DMHD_ctl,       &
     &          MHD_step, SPH_model, SPH_WK, SPH_MHD, FEM_dat)
      subroutine input_control_4_SPH_MHD_nosnap(MHD_files, DMHD_ctl,  &
     &          MHD_step, SPH_model, SPH_WK, SPH_MHD)
      subroutine input_control_4_SPH_make_init(MHD_files, DMHD_ctl,   &
     &          MHD_step, SPH_model, SPH_WK, SPH_MHD, FEM_dat)
        type(MHD_file_IO_params), intent(inout) :: MHD_files
        type(DNS_mhd_simulation_control), intent(inout) :: DMHD_ctl
        type(MHD_step_param), intent(inout) :: MHD_step
        type(SPH_MHD_model_data), intent(inout) :: SPH_model
        type(work_SPH_MHD), intent(inout) :: SPH_WK
        type(SPH_mesh_field_data), intent(inout) :: SPH_MHD
        type(FEM_mesh_field_data), intent(inout) :: FEM_dat
Function/Subroutine Documentation
input_control_4_sph_make_init()
subroutine input_control_sph_mhd::input_control_4_sph_make_init (type(mhd_file_io_params), intent(inout) MHD_files, type(dns_mhd_simulation_control), intent(inout) DMHD_ctl, type(mhd_step_param), intent(inout) MHD_step, type(sph_mhd_model_data), intent(inout) SPH_model, type(work_sph_mhd), intent(inout) SPH_WK, type(sph_mesh_field_data), intent(inout) SPH_MHD, type(fem_mesh_field_data), intent(inout) FEM_dat)
Definition at line 152 of file input_control_sph_MHD.f90.
References t_ctl_data_mhd::dealloc_sph_mhd_ctl_data(), m_machine_parameter::iflag_debug, t_check_and_make_sph_mesh::load_para_sph_and_fem_mesh(), set_control_sph_mhd::set_control_4_sph_mhd(), set_control_sph_mhd::set_control_sph_mhd_w_viz(), set_control_4_sph_to_fem::sph_boundary_io_control(), and sph_maker1.
Referenced by sph_analyzer_add_initial::initialize_add_sph_initial(), and sph_analyzer_const_initial::initialize_const_sph_initial().
input_control_4_sph_mhd_nosnap()
subroutine input_control_sph_mhd::input_control_4_sph_mhd_nosnap (type(mhd_file_io_params), intent(inout) MHD_files, type(dns_mhd_simulation_control), intent(inout) DMHD_ctl, type(mhd_step_param), intent(inout) MHD_step, type(sph_mhd_model_data), intent(inout) SPH_model, type(work_sph_mhd), intent(inout) SPH_WK, type(sph_mesh_field_data), intent(inout) SPH_MHD)
Definition at line 109 of file input_control_sph_MHD.f90.
References t_check_and_make_sph_mesh::check_and_make_sph_mesh(), t_ctl_data_mhd::dealloc_sph_mhd_ctl_data(), m_machine_parameter::iflag_debug, set_control_sph_mhd::set_control_4_sph_mhd(), set_control_sph_mhd::set_control_sph_mhd_noviz(), set_control_4_sph_to_fem::sph_boundary_io_control(), and sph_maker1.
input_control_sph_mhd_psf()
subroutine input_control_sph_mhd::input_control_sph_mhd_psf (type(mhd_file_io_params), intent(inout) MHD_files, type(dns_mhd_simulation_control), intent(inout) DMHD_ctl, type(mhd_step_param), intent(inout) MHD_step, type(sph_mhd_model_data), intent(inout) SPH_model, type(work_sph_mhd), intent(inout) SPH_WK, type(sph_mesh_field_data), intent(inout) SPH_MHD, type(fem_mesh_field_data), intent(inout) FEM_dat)
Definition at line 59 of file input_control_sph_MHD.f90.
References t_ctl_data_mhd::dealloc_sph_mhd_ctl_data(), m_machine_parameter::iflag_debug, t_check_and_make_sph_mesh::load_para_sph_and_fem_mesh(), set_control_sph_mhd::set_control_4_sph_mhd(), set_control_sph_mhd::set_control_sph_mhd_w_viz(), set_control_4_sph_to_fem::sph_boundary_io_control(), and sph_maker1.
Referenced by analyzer_sph_mhd_w_psf::initialize_sph_mhd_w_psf(), and analyzer_sph_snap_w_psf::initialize_sph_snap_w_psf().
Variable Documentation
sph_maker1
type(sph_grid_maker_in_sim), save, private input_control_sph_mhd::sph_maker1 private
Structure to construct grid.
Definition at line 51 of file input_control_sph_MHD.f90.
Referenced by input_control_4_sph_make_init(), input_control_4_sph_mhd_nosnap(), and input_control_sph_mhd_psf().