CALYPSO: gz_field_file_mpi_io_b Module Reference
gz_field_file_mpi_io_b Module Reference
Output merged binary field file using MPI-IO.
Functions/Subroutines
subroutine gz_write_step_fld_file_mpi_b (file_name, t_IO, fld_IO)
subroutine gz_read_step_field_file_mpi_b (file_name, num_pe, id_rank, t_IO, fld_IO)
subroutine gz_rd_alloc_st_fld_file_mpi_b (file_name, num_pe, id_rank, t_IO, fld_IO)
subroutine gz_rd_alloc_st_fld_head_mpi_b (file_name, num_pe, id_rank, t_IO, fld_IO)
Variables
type(calypso_mpi_io_params), save, private io_param
Detailed Description
Output merged binary field file using MPI-IO.
      subroutine gz_write_step_fld_file_mpi_b(file_name, t_IO, fld_IO)
        type(time_data), intent(in) :: t_IO
        type(field_IO), intent(in) :: fld_IO
      subroutine gz_read_step_field_file_mpi_b                        &
     &         (file_name, num_pe, id_rank, t_IO, fld_IO)
      subroutine gz_rd_alloc_st_fld_file_mpi_b                        &
     &         (file_name, num_pe, id_rank, t_IO, fld_IO)
      subroutine gz_rd_alloc_st_fld_head_mpi_b                        &
     &         (file_name, num_pe, id_rank, t_IO, fld_IO)
        type(time_data), intent(inout) :: t_IO
        type(field_IO), intent(inout) :: fld_IO
Function/Subroutine Documentation
gz_rd_alloc_st_fld_file_mpi_b()
subroutine gz_field_file_mpi_io_b::gz_rd_alloc_st_fld_file_mpi_b (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO)
Definition at line 131 of file gz_field_file_MPI_IO_b.f90.
References t_field_data_io::alloc_merged_field_stack(), t_field_data_io::alloc_phys_data_io(), t_field_data_io::alloc_phys_name_io(), t_field_data_io::cal_istack_phys_comp_io(), mpi_ascii_data_io::close_mpi_file(), t_field_data_io::dealloc_merged_field_stack(), t_field_data_io::dealloc_phys_data_io(), t_field_data_io::dealloc_phys_name_io(), gz_mpi_binary_data_io::gz_mpi_read_2d_vector_b(), gz_mpi_binary_head_io::gz_mpi_read_mul_charahead_b(), gz_mpi_binary_head_io::gz_mpi_read_mul_inthead_b(), gz_field_block_mpi_io_b::gz_read_field_header_mpi_b(), gz_field_block_mpi_io_b::gz_read_step_data_mpi_b(), io_param, calypso_mpi::my_rank, and gz_mpi_binary_datum_io::open_read_gz_mpi_file_b().
Referenced by field_io_select::sel_read_alloc_step_field_file().
gz_rd_alloc_st_fld_head_mpi_b()
subroutine gz_field_file_mpi_io_b::gz_rd_alloc_st_fld_head_mpi_b (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO)
Definition at line 189 of file gz_field_file_MPI_IO_b.f90.
References t_field_data_io::alloc_merged_field_stack(), t_field_data_io::alloc_phys_name_io(), t_field_data_io::cal_istack_phys_comp_io(), mpi_ascii_data_io::close_mpi_file(), t_field_data_io::dealloc_merged_field_stack(), t_field_data_io::dealloc_phys_name_io(), gz_mpi_binary_head_io::gz_mpi_read_mul_charahead_b(), gz_mpi_binary_head_io::gz_mpi_read_mul_inthead_b(), gz_field_block_mpi_io_b::gz_read_field_header_mpi_b(), gz_field_block_mpi_io_b::gz_read_step_data_mpi_b(), io_param, calypso_mpi::my_rank, and gz_mpi_binary_datum_io::open_read_gz_mpi_file_b().
Referenced by field_io_select::sel_read_alloc_field_head().
gz_read_step_field_file_mpi_b()
subroutine gz_field_file_mpi_io_b::gz_read_step_field_file_mpi_b (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO)
Definition at line 79 of file gz_field_file_MPI_IO_b.f90.
References t_field_data_io::alloc_merged_field_stack(), t_field_data_io::cal_istack_phys_comp_io(), mpi_ascii_data_io::close_mpi_file(), t_field_data_io::dealloc_merged_field_stack(), gz_mpi_binary_data_io::gz_mpi_read_2d_vector_b(), gz_mpi_binary_head_io::gz_mpi_read_mul_charahead_b(), gz_mpi_binary_head_io::gz_mpi_read_mul_inthead_b(), gz_field_block_mpi_io_b::gz_read_field_header_mpi_b(), gz_field_block_mpi_io_b::gz_read_step_data_mpi_b(), io_param, calypso_mpi::my_rank, and gz_mpi_binary_datum_io::open_read_gz_mpi_file_b().
Referenced by field_io_select::sel_read_step_field_file().
gz_write_step_fld_file_mpi_b()
subroutine gz_field_file_mpi_io_b::gz_write_step_fld_file_mpi_b (character(len=kchara), intent(in) file_name, type(time_data), intent(in) t_IO, type(field_io), intent(in) fld_IO)
Definition at line 46 of file gz_field_file_MPI_IO_b.f90.
References transfer_to_long_integers::cast_long(), mpi_ascii_data_io::close_mpi_file(), gz_field_block_mpi_io_b::gz_write_field_data_mpi_b(), gz_field_block_mpi_io_b::gz_write_field_time_mpi_b(), io_param, calypso_mpi::my_rank, and gz_mpi_binary_datum_io::open_write_gz_mpi_file_b().
Referenced by field_io_select::sel_write_step_field_file().
Variable Documentation
io_param
type(calypso_mpi_io_params), save, private gz_field_file_mpi_io_b::io_param private
Definition at line 38 of file gz_field_file_MPI_IO_b.f90.
Referenced by gz_rd_alloc_st_fld_file_mpi_b(), gz_rd_alloc_st_fld_head_mpi_b(), gz_read_step_field_file_mpi_b(), gz_write_step_fld_file_mpi_b(), and gz_ucd_file_mpi_io::gz_write_ucd_data_mpi_b().