CALYPSO: gz_assembled_field_mpi_io Module Reference
gz_assembled_field_mpi_io Module Reference
gzipped data IO for
Functions/Subroutines
subroutine, private alloc_assemble_gz_buffer (nloop)
subroutine, private dealloc_assemble_gz_buffer
subroutine gz_write_step_asbl_fld_mpi (file_name, num_pe, nloop, fld_IO, t_IO)
subroutine gz_write_step_asbl_fld_mpi_b (file_name, num_pe, id_rank, nloop, fld_IO, t_IO)
subroutine, private gz_write_asmbl_fld_mpi (id_mpi_file, num_pe, ioff_gl, ist_fld, ndir, nloop, fld_IO, gz_bufs)
subroutine, private gz_write_asmbl_fld_mpi_b (IO_param, nloop, fld_IO, gz_bufs)
Variables
type(buffer_4_gzip), dimension(:), allocatable, save, private gz_bufs
Detailed Description
gzipped data IO for
      subroutine gz_write_step_asbl_fld_mpi                           &
     &         (file_name, num_pe, nloop, fld_IO, t_IO)
      subroutine gz_write_step_asbl_fld_mpi_b                         &
     &         (file_name, num_pe, id_rank, nloop, fld_IO, t_IO)
        type(field_IO), intent(in) :: fld_IO(nloop)
        type(time_data), intent(in) :: t_IO
   Data format for the merged ascii field data
     1.   Number of process
     2.   Time step
     3.   Time, Delta t
     4.   Stacks of numbe of data points
     5.   Number of fields
     6.   List of number of components
     7.   Each field data  (Itarate 7.1 - 7.3)
      7.1   Field name
      7.2   List of data size (Byte)
      7.3   Field data
   Data format for the merged binary field data
     1.   Number of process
     2.   Time step
     3.   Time, Delta t
     4.   Stacks of numbe of data points
     5.   Number of fields
     6.   List of number of components
     7.   Field names
     8.   List of data size (Byte)
     9.   All Field data
Function/Subroutine Documentation
alloc_assemble_gz_buffer()
subroutine, private gz_assembled_field_mpi_io::alloc_assemble_gz_buffer (integer(kind = kint), intent(in) nloop) private
Definition at line 67 of file gz_assembled_field_MPI_IO.f90.
References gz_bufs.
Referenced by gz_write_step_asbl_fld_mpi(), and gz_write_step_asbl_fld_mpi_b().
dealloc_assemble_gz_buffer()
subroutine, private gz_assembled_field_mpi_io::dealloc_assemble_gz_buffer private
Definition at line 78 of file gz_assembled_field_MPI_IO.f90.
References gz_bufs.
Referenced by gz_write_step_asbl_fld_mpi(), and gz_write_step_asbl_fld_mpi_b().
gz_write_asmbl_fld_mpi()
subroutine, private gz_assembled_field_mpi_io::gz_write_asmbl_fld_mpi (integer, intent(in) id_mpi_file, integer, intent(in) num_pe, integer(kind = kint_gl), intent(inout) ioff_gl, integer(kind = kint), intent(in) ist_fld, integer(kind = kint), intent(in) ndir, integer(kind = kint), intent(in) nloop, type(field_io), dimension(nloop), intent(in), target fld_IO, type(buffer_4_gzip), dimension(nloop), intent(inout) gz_bufs) private
Definition at line 180 of file gz_assembled_field_MPI_IO.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), field_data_io::buffer_istack_nod_buffer(), t_buffer_4_gzip::dealloc_zip_buffer(), zlib_convert_ascii_vector::defleate_vector_txt(), gz_bufs, gz_field_data_mpi_io::gz_write_fld_header_mpi(), m_constants::izero, m_calypso_mpi_io::mpi_write_one_chara_b(), calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by gz_write_step_asbl_fld_mpi().
gz_write_asmbl_fld_mpi_b()
subroutine, private gz_assembled_field_mpi_io::gz_write_asmbl_fld_mpi_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint), intent(in) nloop, type(field_io), dimension(nloop), intent(in) fld_IO, type(buffer_4_gzip), dimension(nloop), intent(inout) gz_bufs) private
Definition at line 263 of file gz_assembled_field_MPI_IO.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), t_buffer_4_gzip::dealloc_zip_buffer(), gz_bufs, gz_mpi_binary_head_io::gz_mpi_write_merged_stack_b(), gzip_defleat_once(), gz_field_file_mpi_io_b::io_param, m_precision::kreal, m_calypso_mpi_io::mpi_write_one_chara_b(), calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by gz_write_step_asbl_fld_mpi_b().
gz_write_step_asbl_fld_mpi()
subroutine gz_assembled_field_mpi_io::gz_write_step_asbl_fld_mpi (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer(kind = kint), intent(in) nloop, type(field_io), dimension(nloop), intent(in) fld_IO, type(time_data), intent(in) t_IO)
Definition at line 87 of file gz_assembled_field_MPI_IO.f90.
References alloc_assemble_gz_buffer(), m_calypso_mpi_io::calypso_close_mpi_file(), m_calypso_mpi_io::calypso_mpi_write_file_open(), dealloc_assemble_gz_buffer(), field_data_io::each_field_name_buffer(), gz_bufs, gz_write_asmbl_fld_mpi(), gz_field_data_mpi_io::gz_write_fld_header_mpi(), calypso_mpi::my_rank, and gz_field_block_mpi_io::write_field_head_gz_mpi().
Referenced by t_assembled_field_io::sel_write_sph_assemble_field().
gz_write_step_asbl_fld_mpi_b()
subroutine gz_assembled_field_mpi_io::gz_write_step_asbl_fld_mpi_b (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, integer(kind = kint), intent(in) nloop, type(field_io), dimension(nloop), intent(in) fld_IO, type(time_data), intent(in) t_IO)
Definition at line 135 of file gz_assembled_field_MPI_IO.f90.
References alloc_assemble_gz_buffer(), mpi_ascii_data_io::close_mpi_file(), dealloc_assemble_gz_buffer(), gz_bufs, gz_mpi_binary_head_io::gz_mpi_write_mul_charahead_b(), gz_write_asmbl_fld_mpi_b(), calypso_mpi::my_rank, and gz_mpi_binary_datum_io::open_write_gz_mpi_file_b().
Referenced by t_assembled_field_io::sel_write_sph_assemble_field().
Variable Documentation
gz_bufs
type(buffer_4_gzip), dimension(:), allocatable, save, private gz_assembled_field_mpi_io::gz_bufs private
Definition at line 55 of file gz_assembled_field_MPI_IO.f90.
Referenced by alloc_assemble_gz_buffer(), dealloc_assemble_gz_buffer(), gz_write_asmbl_fld_mpi(), gz_write_asmbl_fld_mpi_b(), gz_write_step_asbl_fld_mpi(), and gz_write_step_asbl_fld_mpi_b().