CALYPSO: mpi_node_geometry_io_b Module Reference
mpi_node_geometry_io_b Module Reference
routines for ASCII data IO for mesh geometry
Functions/Subroutines
subroutine, private mpi_write_num_node_b (IO_param, nod_IO)
subroutine mpi_write_geometry_info_b (IO_param, nod_IO)
subroutine mpi_write_scl_in_ele_b (IO_param, nod_IO, sfed_IO)
subroutine mpi_write_vect_in_ele_b (IO_param, nod_IO, sfed_IO)
subroutine mpi_read_number_of_node_b (IO_param, nod_IO)
subroutine mpi_read_geometry_info_b (IO_param, nod_IO)
subroutine mpi_read_scl_in_ele_b (IO_param, nod_IO, sfed_IO)
subroutine mpi_read_vect_in_ele_b (IO_param, nod_IO, sfed_IO)
Detailed Description
routines for ASCII data IO for mesh geometry
      subroutine mpi_write_geometry_info_b(IO_param, nod_IO)
      subroutine mpi_write_scl_in_ele_b(IO_param, nod_IO, sfed_IO)
      subroutine mpi_write_vect_in_ele_b(IO_param, nod_IO, sfed_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(node_data), intent(in) :: nod_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
      subroutine mpi_read_number_of_node_b(IO_param, nod_IO)
      subroutine mpi_read_geometry_info_b(IO_param, nod_IO)
      subroutine mpi_read_scl_in_ele_b(IO_param, nod_IO, sfed_IO)
      subroutine mpi_read_vect_in_ele_b(IO_param, nod_IO, sfed_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(node_data), intent(inout) :: nod_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
Function/Subroutine Documentation
mpi_read_geometry_info_b()
subroutine mpi_node_geometry_io_b::mpi_read_geometry_info_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(inout) nod_IO)
Definition at line 136 of file MPI_node_geometry_IO_b.f90.
References t_geometry_data::alloc_node_geometry_base(), mpi_binary_data_io::mpi_read_2d_vector_b(), and mpi_binary_data_io::mpi_read_int8_vector_b().
Referenced by mpi_edge_data_io_b::mpi_read_edge_geometry_b(), mpi_element_data_io_b::mpi_read_element_geometry_b(), mpi_mesh_data_io_b::mpi_read_num_node_ele_b(), and mpi_surface_data_io_b::mpi_read_surface_geometry_b().
mpi_read_number_of_node_b()
subroutine mpi_node_geometry_io_b::mpi_read_number_of_node_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(inout) nod_IO)
Definition at line 123 of file MPI_node_geometry_IO_b.f90.
References mpi_binary_data_io::mpi_read_one_integer_b().
Referenced by mpi_edge_data_io_b::mpi_read_edge_geometry_b(), mpi_element_data_io_b::mpi_read_element_geometry_b(), mpi_mesh_data_io_b::mpi_read_num_node_ele(), mpi_read_scl_in_ele_b(), mpi_surface_data_io_b::mpi_read_surface_geometry_b(), and mpi_read_vect_in_ele_b().
mpi_read_scl_in_ele_b()
subroutine mpi_node_geometry_io_b::mpi_read_scl_in_ele_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 156 of file MPI_node_geometry_IO_b.f90.
References t_surf_edge_io::alloc_ele_scalar_io(), mpi_read_number_of_node_b(), and mpi_binary_data_io::mpi_write_1d_vector_b().
Referenced by mpi_edge_data_io_b::mpi_read_edge_geometry_b(), mpi_element_data_io_b::mpi_read_element_geometry_b(), and mpi_surface_data_io_b::mpi_read_surface_geometry_b().
mpi_read_vect_in_ele_b()
subroutine mpi_node_geometry_io_b::mpi_read_vect_in_ele_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 176 of file MPI_node_geometry_IO_b.f90.
References t_surf_edge_io::alloc_ele_vector_io(), mpi_binary_data_io::mpi_read_2d_vector_b(), mpi_read_number_of_node_b(), and m_phys_constants::n_vector.
Referenced by mpi_edge_data_io_b::mpi_read_edge_geometry_b(), and mpi_surface_data_io_b::mpi_read_surface_geometry_b().
mpi_write_geometry_info_b()
subroutine mpi_node_geometry_io_b::mpi_write_geometry_info_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(in) nod_IO)
Definition at line 61 of file MPI_node_geometry_IO_b.f90.
References mpi_binary_data_io::mpi_write_2d_vector_b(), mpi_binary_data_io::mpi_write_int8_vector_b(), and mpi_write_num_node_b().
Referenced by mpi_edge_data_io_b::mpi_write_edge_geometry_b(), mpi_element_data_io_b::mpi_write_element_geometry_b(), mpi_mesh_data_io_b::mpi_write_geometry_data_b(), and mpi_surface_data_io_b::mpi_write_surface_geometry_b().
mpi_write_num_node_b()
subroutine, private mpi_node_geometry_io_b::mpi_write_num_node_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(in) nod_IO) private
Definition at line 48 of file MPI_node_geometry_IO_b.f90.
References mpi_binary_data_io::mpi_write_one_integer_b().
Referenced by mpi_write_geometry_info_b(), mpi_write_scl_in_ele_b(), and mpi_write_vect_in_ele_b().
mpi_write_scl_in_ele_b()
subroutine mpi_node_geometry_io_b::mpi_write_scl_in_ele_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 82 of file MPI_node_geometry_IO_b.f90.
References mpi_binary_data_io::mpi_write_1d_vector_b(), and mpi_write_num_node_b().
Referenced by mpi_edge_data_io_b::mpi_write_edge_geometry_b(), mpi_element_data_io_b::mpi_write_element_geometry_b(), and mpi_surface_data_io_b::mpi_write_surface_geometry_b().
mpi_write_vect_in_ele_b()
subroutine mpi_node_geometry_io_b::mpi_write_vect_in_ele_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 102 of file MPI_node_geometry_IO_b.f90.
References mpi_binary_data_io::mpi_write_2d_vector_b(), mpi_write_num_node_b(), and m_phys_constants::n_vector.
Referenced by mpi_edge_data_io_b::mpi_write_edge_geometry_b(), and mpi_surface_data_io_b::mpi_write_surface_geometry_b().