CALYPSO: mpi_element_file_io_b Module Reference
mpi_element_file_io_b Module Reference
File IO for element communication table.
Functions/Subroutines
subroutine mpi_input_element_file_b (num_pe, id_rank, file_name, ele_mesh_IO, ierr)
subroutine mpi_input_surface_file_b (num_pe, id_rank, file_name, surf_mesh_IO, ierr)
subroutine mpi_input_edge_file_b (num_pe, id_rank, file_name, edge_mesh_IO, ierr)
subroutine mpi_output_element_file_b (file_name, ele_mesh_IO)
subroutine mpi_output_surface_file_b (file_name, surf_mesh_IO)
subroutine mpi_output_edge_file_b (file_name, edge_mesh_IO)
Variables
type(calypso_mpi_io_params), save, private io_param
Detailed Description
File IO for element communication table.
      subroutine mpi_input_element_file_b                             &
     &         (num_pe, id_rank, file_name, ele_mesh_IO, ierr)
      subroutine mpi_input_surface_file_b                             &
     &         (num_pe, id_rank, file_name, surf_mesh_IO, ierr)
      subroutine mpi_input_edge_file_b                                &
     &         (num_pe, id_rank, file_name, edge_mesh_IO, ierr)
        type(surf_edge_IO_file), intent(inout) :: ele_mesh_IO
        type(surf_edge_IO_file), intent(inout) :: surf_mesh_IO
        type(surf_edge_IO_file), intent(inout) :: edge_mesh_IO
      subroutine mpi_output_element_file_b(file_name, ele_mesh_IO)
      subroutine mpi_output_surface_file_b(file_name, surf_mesh_IO)
      subroutine mpi_output_edge_file_b(file_name, edge_mesh_IO)
        type(surf_edge_IO_file), intent(in) :: ele_mesh_IO
        type(surf_edge_IO_file), intent(in) :: surf_mesh_IO
        type(surf_edge_IO_file), intent(in) :: edge_mesh_IO
Parameters
id_rank MPI rank
Function/Subroutine Documentation
mpi_input_edge_file_b()
subroutine mpi_element_file_io_b::mpi_input_edge_file_b (integer, intent(in) num_pe, integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(inout) edge_mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 100 of file MPI_element_file_IO_b.f90.
References m_machine_parameter::i_debug, io_param, and mpi_edge_data_io_b::mpi_read_edge_connection_b().
Referenced by element_mesh_mpi_io_select::sel_mpi_read_edge_mesh().
mpi_input_element_file_b()
subroutine mpi_element_file_io_b::mpi_input_element_file_b (integer, intent(in) num_pe, integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(inout) ele_mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 49 of file MPI_element_file_IO_b.f90.
References m_machine_parameter::i_debug, io_param, and mpi_element_data_io_b::mpi_read_element_comm_table_b().
Referenced by element_mesh_mpi_io_select::sel_mpi_read_ele_mesh().
mpi_input_surface_file_b()
subroutine mpi_element_file_io_b::mpi_input_surface_file_b (integer, intent(in) num_pe, integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(inout) surf_mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 74 of file MPI_element_file_IO_b.f90.
References m_machine_parameter::i_debug, io_param, and mpi_surface_data_io_b::mpi_read_surface_connection_b().
Referenced by element_mesh_mpi_io_select::sel_mpi_read_surf_mesh().
mpi_output_edge_file_b()
subroutine mpi_element_file_io_b::mpi_output_edge_file_b (character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(in) edge_mesh_IO)
Definition at line 170 of file MPI_element_file_IO_b.f90.
References m_machine_parameter::i_debug, io_param, and mpi_edge_data_io_b::mpi_write_edge_connection_b().
Referenced by element_mesh_mpi_io_select::sel_mpi_write_edge_mesh_file().
mpi_output_element_file_b()
subroutine mpi_element_file_io_b::mpi_output_element_file_b (character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(in) ele_mesh_IO)
Definition at line 127 of file MPI_element_file_IO_b.f90.
References m_machine_parameter::i_debug, io_param, and mpi_element_data_io_b::mpi_write_element_comm_table_b().
Referenced by element_mesh_mpi_io_select::sel_mpi_write_ele_mesh_file().
mpi_output_surface_file_b()
subroutine mpi_element_file_io_b::mpi_output_surface_file_b (character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(in) surf_mesh_IO)
Definition at line 148 of file MPI_element_file_IO_b.f90.
References m_machine_parameter::i_debug, io_param, and mpi_surface_data_io_b::mpi_write_surface_connection_b().
Referenced by element_mesh_mpi_io_select::sel_mpi_write_surf_mesh_file().
Variable Documentation
io_param
type(calypso_mpi_io_params), save, private mpi_element_file_io_b::io_param private
Definition at line 41 of file MPI_element_file_IO_b.f90.
Referenced by mpi_input_edge_file_b(), mpi_input_element_file_b(), mpi_input_surface_file_b(), mpi_output_edge_file_b(), mpi_output_element_file_b(), and mpi_output_surface_file_b().