CALYPSO: field_block_mpi_io_b Module Reference
field_block_mpi_io_b Module Reference
Output merged binary field file using MPI-IO.
Functions/Subroutines
subroutine write_field_time_mpi_b (IO_param_l, i_time_step_IO, time_IO, delta_t_IO)
subroutine write_field_data_mpi_b (IO_param_l, nnod, num_field, ntot_comp, ncomp_field, field_name, d_nod, istack_merged)
subroutine read_field_header_mpi_b (num_pe, IO_param_l, t_IO, nnod, istack_merged)
Detailed Description
Output merged binary field file using MPI-IO.
      subroutine write_field_time_mpi_b(IO_param_l,                   &
     &          i_time_step_IO, time_IO, delta_t_IO)
      subroutine write_field_data_mpi_b(IO_param_l,                   &
     &          i_time_step_IO, time_IO, delta_t_IO,                  &
     &          nnod, num_field, ntot_comp, ncomp_field,              &
     &          field_name, d_nod, istack_merged)
      subroutine read_field_header_mpi_b                              &
     &         (num_pe, IO_param_l, t_IO, nnod, istack_merged)
Function/Subroutine Documentation
read_field_header_mpi_b()
subroutine field_block_mpi_io_b::read_field_header_mpi_b (integer, intent(in) num_pe, type(calypso_mpi_io_params), intent(inout) IO_param_l, type(time_data), intent(inout) t_IO, integer(kind = kint_gl), intent(inout) nnod, integer(kind = kint_gl), dimension(0:num_pe), intent(inout) istack_merged)
Definition at line 95 of file field_block_MPI_IO_b.f90.
References transfer_to_long_integers::cast_long(), mpi_binary_head_io::mpi_read_i8stack_head_b(), mpi_binary_head_io::mpi_read_one_inthead_b(), mpi_binary_head_io::mpi_read_one_realhead_b(), mpi_binary_head_io::mpi_read_process_id_b(), and field_data_mpi_io::sync_field_header_mpi().
Referenced by field_file_mpi_io_b::read_alloc_stp_fld_file_mpi_b(), field_file_mpi_io_b::read_alloc_stp_fld_head_mpi_b(), ucd_field_mpi_io_b::read_alloc_ucd_fld_file_mpi_b(), field_file_mpi_io_b::read_step_field_file_mpi_b(), and ucd_field_mpi_io_b::read_ucd_field_file_mpi_b().
write_field_data_mpi_b()
subroutine field_block_mpi_io_b::write_field_data_mpi_b (type(calypso_mpi_io_params), intent(inout) IO_param_l, integer(kind=kint_gl), intent(in) nnod, integer(kind=kint), intent(in) num_field, integer(kind=kint), intent(in) ntot_comp, integer(kind=kint), dimension(num_field), intent(in) ncomp_field, character(len=kchara), dimension(num_field), intent(in) field_name, real(kind = kreal), dimension(nnod,ntot_comp), intent(in) d_nod, integer(kind = kint_gl), dimension(0:io_param_l%nprocs_in), intent(in) istack_merged)
Definition at line 60 of file field_block_MPI_IO_b.f90.
References transfer_to_long_integers::cast_long(), t_calypso_mpi_io_param::copy_istack_4_parallell_data(), mpi_binary_data_io::mpi_write_2d_vector_b(), mpi_binary_head_io::mpi_write_i8stack_head_b(), mpi_binary_head_io::mpi_write_mul_charahead_b(), mpi_binary_head_io::mpi_write_mul_inthead_b(), and mpi_binary_head_io::mpi_write_one_inthead_b().
Referenced by field_file_mpi_io_b::write_step_field_file_mpi_b(), and ucd_field_mpi_io_b::write_ucd_field_file_mpi_b().
write_field_time_mpi_b()
subroutine field_block_mpi_io_b::write_field_time_mpi_b (type(calypso_mpi_io_params), intent(inout) IO_param_l, integer(kind=kint), intent(in) i_time_step_IO, real(kind = kreal), intent(in) time_IO, real(kind = kreal), intent(in) delta_t_IO)
Definition at line 40 of file field_block_MPI_IO_b.f90.
References mpi_binary_head_io::mpi_write_one_inthead_b(), mpi_binary_head_io::mpi_write_one_realhead_b(), and mpi_binary_head_io::mpi_write_process_id_b().
Referenced by field_file_mpi_io_b::write_step_field_file_mpi_b(), ucd_field_mpi_io_b::write_ucd_field_file_mpi_b(), write_udt_file_io_b::write_ucd_file_mpi_b(), and write_udt_file_io_b::write_ucd_phys_mpi_b().