CALYPSO: correlation_by_sph_spectr Module Reference
correlation_by_sph_spectr Module Reference
Evaluate mean square data for each spherical harmonics mode.
Functions/Subroutines
subroutine correlate_sph_spec_one_field (sph_rj, ncomp_x, g_sph_rj, icomp1_rj, n1_point, ntot_phys1_rj, d1_rj, icomp2_rj, n2_point, ntot_phys2_rj, d2_rj, x_sph_rj)
subroutine, private correlate_each_scalar_sph_spec (nri, jmax, idx_rj_degree_zero, inod_rj_center, radius_1d_rj_r, g_sph_rj, n_point, d1_rj, d2_rj, x_sph_rj)
subroutine, private correlate_each_vector_sph_spec (nri, jmax, idx_rj_degree_zero, inod_rj_center, a_r_1d_rj_r, g_sph_rj, n_point, d1_rj, d2_rj, x_sph_rj)
Detailed Description
Evaluate mean square data for each spherical harmonics mode.
      subroutine correlate_sph_spec_one_field                         &
     &         (sph_rj, ncomp_x, g_sph_rj,                            &
     &          icomp1_rj, n1_point, ntot_phys1_rj, d1_rj,            &
     &          icomp2_rj, n2_point, ntot_phys2_rj, d2_rj, x_sph_rj)
        type(sph_rj_grid), intent(in) :: sph_rj
        (1/4\pi) \int (\bf{u}_{l}^{m})^2 sin \theta d\theta d\phi
          = r^{-2} [ l(l+1) / (2l+1)
           ( l(l+1)/r^2 (S_{l}^{m})^2 + (dS_{l}^{m}/dr)^2)
            + (T_{l}^{m})^2 ) ]
Parameters
d_rj spectrum data
x_sph_rj cross spectr data
Function/Subroutine Documentation
correlate_each_scalar_sph_spec()
subroutine, private correlation_by_sph_spectr::correlate_each_scalar_sph_spec (integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, integer(kind = kint), intent(in) idx_rj_degree_zero, integer(kind = kint), intent(in) inod_rj_center, real(kind = kreal), dimension(nri), intent(in) radius_1d_rj_r, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) n_point, real(kind = kreal), dimension(n_point), intent(in) d1_rj, real(kind = kreal), dimension(n_point), intent(in) d2_rj, real(kind = kreal), dimension(0:nri,jmax), intent(inout) x_sph_rj) private
Definition at line 81 of file correlation_by_sph_spectr.f90.
Referenced by correlate_sph_spec_one_field().
correlate_each_vector_sph_spec()
subroutine, private correlation_by_sph_spectr::correlate_each_vector_sph_spec (integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, integer(kind = kint), intent(in) idx_rj_degree_zero, integer(kind = kint), intent(in) inod_rj_center, real(kind = kreal), dimension(nri), intent(in) a_r_1d_rj_r, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) n_point, real(kind = kreal), dimension(n_point,3), intent(in) d1_rj, real(kind = kreal), dimension(n_point,3), intent(in) d2_rj, real(kind = kreal), dimension(0:nri,jmax,3), intent(inout) x_sph_rj) private
Definition at line 117 of file correlation_by_sph_spectr.f90.
References m_constants::half, m_constants::izero, and m_constants::zero.
Referenced by correlate_sph_spec_one_field().
correlate_sph_spec_one_field()
subroutine correlation_by_sph_spectr::correlate_sph_spec_one_field (type(sph_rj_grid), intent(in) sph_rj, integer(kind = kint), intent(in) ncomp_x, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, integer(kind = kint), intent(in) icomp1_rj, integer(kind = kint), intent(in) n1_point, integer(kind = kint), intent(in) ntot_phys1_rj, real(kind = kreal), dimension(n1_point,ntot_phys1_rj), intent(in) d1_rj, integer(kind = kint), intent(in) icomp2_rj, integer(kind = kint), intent(in) n2_point, integer(kind = kint), intent(in) ntot_phys2_rj, real(kind = kreal), dimension(n2_point,ntot_phys2_rj), intent(in) d2_rj, real(kind = kreal), dimension(0:sph_rj%nidx_rj(1),sph_rj%nidx_rj(2),ncomp_x), intent(inout) x_sph_rj)
Definition at line 41 of file correlation_by_sph_spectr.f90.
References correlate_each_scalar_sph_spec(), correlate_each_vector_sph_spec(), m_phys_constants::n_scalar, and m_phys_constants::n_vector.
Referenced by sum_sph_rms_data::sum_sph_layerd_correlate().