CALYPSO: t_solver_sr_int8 Module Reference
t_solver_sr_int8 Module Reference
Work area for 8-byte integer data communications.
Data Types
type send_recv_int8_buffer
Structure of communication buffer for 8-byte integer.
Functions/Subroutines
subroutine resize_i8work_sr (NPE_SEND, NPE_RECV, NTOT_SEND, NTOT_RECV, SR_sig, SR_il)
subroutine resize_i8work_itp_sr_t (NPE_SEND, NPE_RECV, NTOT_RECV, SR_sig, SR_il)
subroutine, private resize_i8send_sr (NTOT_SEND, SR_il)
subroutine, private resize_i8recv_sr (NTOT_RECV, SR_il)
Detailed Description
Work area for 8-byte integer data communications.
      subroutine resize_i8work_SR(NPE_SEND, NPE_RECV,                 &
     &          NTOT_SEND, NTOT_RECV, SR_sig, SR_il)
        type(send_recv_status), intent(inout) :: SR_sig
        type(send_recv_int8_buffer), intent(inout) :: SR_il
      subroutine resize_i8work_itp_SR_t                               &
     &         (NPE_SEND, NPE_RECV, NTOT_RECV, SR_sig, SR_il)
        type(send_recv_status), intent(inout) :: SR_sig
        type(send_recv_int8_buffer), intent(inout) :: SR_il
Parameters
NB Number of components
NTOT_SEND Total number of data points for export
NTOT_RECV Total number of data points for import
NPE_SEND Number of processses to receive
NPE_RECV Number of processses to send
Parameters
N_SHIFT number of shifting of the reversed import table
ITEM_IMPORT import table
REV_IMPORT reversed import table
Function/Subroutine Documentation
resize_i8recv_sr()
subroutine, private t_solver_sr_int8::resize_i8recv_sr (integer(kind=kint), intent(in) NTOT_RECV, type(send_recv_int8_buffer), intent(inout) SR_il) private
Definition at line 118 of file t_solver_SR_int8.f90.
Referenced by resize_i8work_itp_sr_t(), and resize_i8work_sr().
resize_i8send_sr()
subroutine, private t_solver_sr_int8::resize_i8send_sr (integer(kind=kint), intent(in) NTOT_SEND, type(send_recv_int8_buffer), intent(inout) SR_il) private
Definition at line 99 of file t_solver_SR_int8.f90.
Referenced by resize_i8work_sr().
resize_i8work_itp_sr_t()
subroutine t_solver_sr_int8::resize_i8work_itp_sr_t (integer(kind = kint), intent(in) NPE_SEND, integer(kind = kint), intent(in) NPE_RECV, integer(kind = kint), intent(in) NTOT_RECV, type(send_recv_status), intent(inout) SR_sig, type(send_recv_int8_buffer), intent(inout) SR_il)
Definition at line 82 of file t_solver_SR_int8.f90.
References resize_i8recv_sr(), and t_solver_sr::resize_sr_flag().
resize_i8work_sr()
subroutine t_solver_sr_int8::resize_i8work_sr (integer(kind = kint), intent(in) NPE_SEND, integer(kind = kint), intent(in) NPE_RECV, integer(kind = kint), intent(in) NTOT_SEND, integer(kind = kint), intent(in) NTOT_RECV, type(send_recv_status), intent(inout) SR_sig, type(send_recv_int8_buffer), intent(inout) SR_il)
Definition at line 65 of file t_solver_SR_int8.f90.
References resize_i8recv_sr(), resize_i8send_sr(), and t_solver_sr::resize_sr_flag().
Referenced by calypso_sr_int::calypso_send_recv_int8(), and solver_sr_int8::solver_send_recv_i8().