CALYPSO: cvt_xyz_vector_2_sph_smp Module Reference
cvt_xyz_vector_2_sph_smp Module Reference
Functions/Subroutines
subroutine cvt_vector_2_sph_smp (np_smp, numnod, inod_smp_stack, vect, v_sph, xx, yy, zz, r, s, a_r, a_s)
subroutine overwrite_vector_2_sph_smp (np_smp, numnod, inod_smp_stack, vect, xx, yy, zz, r, s, a_r, a_s)
subroutine cal_radial_comp_smp (np_smp, numnod, inod_smp_stack, vect, v_r, xx, yy, zz, r, a_r)
subroutine cal_theta_comp_smp (np_smp, numnod, inod_smp_stack, vect, v_theta, xx, yy, zz, r, s, a_r, a_s)
subroutine cal_phi_comp_smp (np_smp, numnod, inod_smp_stack, vect, v_phi, xx, yy, s, a_s)
Function/Subroutine Documentation
cal_phi_comp_smp()
subroutine cvt_xyz_vector_2_sph_smp::cal_phi_comp_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,3), intent(in) vect, real(kind=kreal), dimension(numnod), intent(inout) v_phi, real(kind=kreal), dimension(numnod), intent(in) xx, real(kind=kreal), dimension(numnod), intent(in) yy, real(kind=kreal), dimension(numnod), intent(in) s, real(kind=kreal), dimension(numnod), intent(in) a_s)
Definition at line 267 of file cvt_xyz_vector_2_sph_smp.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and set_const_4_sections::set_constant_4_iso().
cal_radial_comp_smp()
subroutine cvt_xyz_vector_2_sph_smp::cal_radial_comp_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,3), intent(in) vect, real(kind=kreal), dimension(numnod), intent(inout) v_r, real(kind=kreal), dimension(numnod), intent(in) xx, real(kind=kreal), dimension(numnod), intent(in) yy, real(kind=kreal), dimension(numnod), intent(in) zz, real(kind=kreal), dimension(numnod), intent(in) r, real(kind=kreal), dimension(numnod), intent(in) a_r)
Definition at line 181 of file cvt_xyz_vector_2_sph_smp.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and set_const_4_sections::set_constant_4_iso().
cal_theta_comp_smp()
subroutine cvt_xyz_vector_2_sph_smp::cal_theta_comp_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,3), intent(in) vect, real(kind=kreal), dimension(numnod), intent(inout) v_theta, real(kind=kreal), dimension(numnod), intent(in) xx, real(kind=kreal), dimension(numnod), intent(in) yy, real(kind=kreal), dimension(numnod), intent(in) zz, real(kind=kreal), dimension(numnod), intent(in) r, real(kind=kreal), dimension(numnod), intent(in) s, real(kind=kreal), dimension(numnod), intent(in) a_r, real(kind=kreal), dimension(numnod), intent(in) a_s)
Definition at line 222 of file cvt_xyz_vector_2_sph_smp.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and set_const_4_sections::set_constant_4_iso().
cvt_vector_2_sph_smp()
subroutine cvt_xyz_vector_2_sph_smp::cvt_vector_2_sph_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,3), intent(in) vect, real(kind=kreal), dimension(numnod,3), intent(inout) v_sph, real(kind=kreal), dimension(numnod), intent(in) xx, real(kind=kreal), dimension(numnod), intent(in) yy, real(kind=kreal), dimension(numnod), intent(in) zz, real(kind=kreal), dimension(numnod), intent(in) r, real(kind=kreal), dimension(numnod), intent(in) s, real(kind=kreal), dimension(numnod), intent(in) a_r, real(kind=kreal), dimension(numnod), intent(in) a_s)
Definition at line 73 of file cvt_xyz_vector_2_sph_smp.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and cvt_nodal_and_sph_field::cvt_nod_vec_to_sph_vec().
overwrite_vector_2_sph_smp()
subroutine cvt_xyz_vector_2_sph_smp::overwrite_vector_2_sph_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,3), intent(inout) vect, real(kind=kreal), dimension(numnod), intent(in) xx, real(kind=kreal), dimension(numnod), intent(in) yy, real(kind=kreal), dimension(numnod), intent(in) zz, real(kind=kreal), dimension(numnod), intent(in) r, real(kind=kreal), dimension(numnod), intent(in) s, real(kind=kreal), dimension(numnod), intent(in) a_r, real(kind=kreal), dimension(numnod), intent(in) a_s)
Definition at line 127 of file cvt_xyz_vector_2_sph_smp.f90.
Referenced by copy_nodal_fld_4_sph_trans::copy_nod_vec_to_sph_trans(), and coordinate_convert_4_sph::overwrite_nodal_xyz_2_sph_smp().