CALYPSO: gz_mpi_spherical_model_io Module Reference
gz_mpi_spherical_model_io Module Reference
Data IO routines for spectrum data.
Functions/Subroutines
subroutine gz_mpi_read_rank_4_sph (IO_param, sph_IO)
subroutine gz_mpi_read_gl_reso_sph (IO_param, sph_IO)
subroutine gz_mpi_read_gl_nodes_sph (IO_param, sph_IO)
subroutine gz_mpi_write_rank_4_sph (IO_param, sph_IO)
subroutine gz_mpi_write_gl_reso_sph (IO_param, sph_IO)
subroutine gz_mpi_write_gl_nodes_sph (IO_param, sph_IO)
Detailed Description
Data IO routines for spectrum data.
      subroutine gz_mpi_read_rank_4_sph(IO_param, sph_IO)
      subroutine gz_mpi_read_gl_reso_sph(IO_param, sph_IO)
      subroutine gz_mpi_read_gl_nodes_sph(IO_param, sph_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(sph_IO_data), intent(inout) :: sph_IO
      subroutine gz_mpi_write_rank_4_sph(IO_param, sph_IO)
      subroutine gz_mpi_write_gl_reso_sph(IO_param, sph_IO)
      subroutine gz_mpi_write_gl_nodes_sph(IO_param, sph_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(sph_IO_data), intent(in) :: sph_IO
Function/Subroutine Documentation
gz_mpi_read_gl_nodes_sph()
subroutine gz_mpi_spherical_model_io::gz_mpi_read_gl_nodes_sph (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(inout) sph_IO)
Definition at line 80 of file gz_MPI_spherical_model_IO.f90.
References t_node_id_spherical_io::alloc_nod_id_sph_io(), gz_mpi_integer_list_io::gz_mpi_read_ele_connect(), and gz_mpi_ascii_data_io::gz_mpi_read_num_of_data().
Referenced by gz_mpi_sph_modes_data_io::gz_mpi_read_geom_rtm_data(), gz_mpi_sph_modes_data_io::gz_mpi_read_geom_rtp_data(), gz_mpi_sph_modes_data_io::gz_mpi_read_modes_rlm_data(), and gz_mpi_sph_modes_data_io::gz_mpi_read_spectr_rj_data().
gz_mpi_read_gl_reso_sph()
subroutine gz_mpi_spherical_model_io::gz_mpi_read_gl_reso_sph (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(inout) sph_IO)
Definition at line 60 of file gz_MPI_spherical_model_IO.f90.
References gz_mpi_ascii_data_io::gz_mpi_read_charahead(), gz_mpi_domain_data_io::gz_mpi_read_comm_table(), gz_mpi_ascii_data_io::gz_mpi_read_num_of_data(), gz_mpi_ascii_data_io::gz_mpi_skip_header(), m_sph_modes_grid_labels::hd_trunc(), data_io_to_textline::len_int_txt, and data_io_to_textline::read_integer_textline().
Referenced by gz_mpi_sph_modes_data_io::gz_mpi_read_geom_rtm_data(), gz_mpi_sph_modes_data_io::gz_mpi_read_geom_rtp_data(), gz_mpi_sph_modes_data_io::gz_mpi_read_modes_rlm_data(), and gz_mpi_sph_modes_data_io::gz_mpi_read_spectr_rj_data().
gz_mpi_read_rank_4_sph()
subroutine gz_mpi_spherical_model_io::gz_mpi_read_rank_4_sph (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(inout) sph_IO)
Definition at line 43 of file gz_MPI_spherical_model_IO.f90.
References gz_mpi_domain_data_io::gz_mpi_read_comm_table(), gz_mpi_ascii_data_io::gz_mpi_read_num_of_data(), gz_mpi_ascii_data_io::gz_mpi_skip_header(), and m_sph_modes_grid_labels::hd_segment().
Referenced by gz_mpi_sph_modes_data_io::gz_mpi_read_geom_rtm_data(), gz_mpi_sph_modes_data_io::gz_mpi_read_geom_rtp_data(), gz_mpi_sph_modes_data_io::gz_mpi_read_modes_rlm_data(), and gz_mpi_sph_modes_data_io::gz_mpi_read_spectr_rj_data().
gz_mpi_write_gl_nodes_sph()
subroutine gz_mpi_spherical_model_io::gz_mpi_write_gl_nodes_sph (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(in) sph_IO)
Definition at line 130 of file gz_MPI_spherical_model_IO.f90.
References gz_mpi_integer_list_io::gz_mpi_write_ele_connect(), and gz_mpi_ascii_data_io::gz_mpi_write_num_of_data().
Referenced by gz_mpi_sph_modes_data_io::gz_mpi_write_geom_rtm_data(), gz_mpi_sph_modes_data_io::gz_mpi_write_geom_rtp_data(), gz_mpi_sph_modes_data_io::gz_mpi_write_modes_rlm_data(), and gz_mpi_sph_modes_data_io::gz_mpi_write_spectr_rj_data().
gz_mpi_write_gl_reso_sph()
subroutine gz_mpi_spherical_model_io::gz_mpi_write_gl_reso_sph (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(in) sph_IO)
Definition at line 113 of file gz_MPI_spherical_model_IO.f90.
References gz_mpi_ascii_data_io::gz_mpi_write_charahead(), gz_mpi_domain_data_io::gz_mpi_write_comm_table(), m_sph_modes_grid_labels::hd_trunc(), data_io_to_textline::integer_textline(), and data_io_to_textline::len_int_txt.
Referenced by gz_mpi_sph_modes_data_io::gz_mpi_write_geom_rtm_data(), gz_mpi_sph_modes_data_io::gz_mpi_write_geom_rtp_data(), gz_mpi_sph_modes_data_io::gz_mpi_write_modes_rlm_data(), and gz_mpi_sph_modes_data_io::gz_mpi_write_spectr_rj_data().
gz_mpi_write_rank_4_sph()
subroutine gz_mpi_spherical_model_io::gz_mpi_write_rank_4_sph (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(in) sph_IO)
Definition at line 98 of file gz_MPI_spherical_model_IO.f90.
References gz_mpi_ascii_data_io::gz_mpi_write_charahead(), gz_mpi_domain_data_io::gz_mpi_write_comm_table(), and m_sph_modes_grid_labels::hd_segment().
Referenced by gz_mpi_sph_modes_data_io::gz_mpi_write_geom_rtm_data(), gz_mpi_sph_modes_data_io::gz_mpi_write_geom_rtp_data(), gz_mpi_sph_modes_data_io::gz_mpi_write_modes_rlm_data(), and gz_mpi_sph_modes_data_io::gz_mpi_write_spectr_rj_data().