CALYPSO: gz_sph_modes_data_io_b Module Reference
gz_sph_modes_data_io_b Module Reference
gzipped binary spectr data IO routines
Functions/Subroutines
subroutine gz_read_geom_rtp_data_b (id_rank, zbuf, comm_IO, sph_IO, sph_grps_IO)
subroutine gz_read_spectr_modes_rj_data_b (id_rank, zbuf, comm_IO, sph_IO, sph_grps_IO)
subroutine gz_read_geom_rtm_data_b (id_rank, zbuf, comm_IO, sph_IO)
subroutine gz_read_modes_rlm_data_b (id_rank, zbuf, comm_IO, sph_IO)
subroutine gz_write_geom_rtp_data_b (id_rank, comm_IO, sph_IO, sph_grps_IO, zbuf)
subroutine gz_write_spectr_modes_rj_data_b (id_rank, comm_IO, sph_IO, sph_grps_IO, zbuf)
subroutine gz_write_geom_rtm_data_b (id_rank, comm_IO, sph_IO, zbuf)
subroutine gz_write_modes_rlm_data_b (id_rank, comm_IO, sph_IO, zbuf)
Detailed Description
gzipped binary spectr data IO routines
      subroutine gz_read_geom_rtp_data_b                              &
     &         (id_rank, zbuf, comm_IO, sph_IO, sph_grps_IO)
      subroutine gz_read_spectr_modes_rj_data_b                       &
     &         (id_rank, zbuf, comm_IO, sph_IO, sph_grps_IO)
      subroutine gz_read_geom_rtm_data_b                              &
     &         (id_rank, zbuf, comm_IO, sph_IO)
      subroutine gz_read_modes_rlm_data_b                             &
     &         (id_rank, zbuf, comm_IO, sph_IO)
        type(buffer_4_gzip), intent(inout) :: zbuf
        type(communication_table), intent(inout) :: comm_IO
        type(sph_IO_data), intent(inout) :: sph_IO
        type(sph_group_data), intent(inout) :: sph_grps_IO
      subroutine gz_write_geom_rtp_data_b                             &
     &         (id_rank, comm_IO, sph_IO, sph_grps_IO, zbuf)
      subroutine gz_write_spectr_modes_rj_data_b                      &
     &         (id_rank, comm_IO, sph_IO, sph_grps_IO, zbuf)
      subroutine gz_write_geom_rtm_data_b                             &
     &         (id_rank, comm_IO, sph_IO, zbuf)
      subroutine gz_write_modes_rlm_data_b                            &
     &         (id_rank, comm_IO, sph_IO, zbuf)
        type(communication_table), intent(in) :: comm_IO
        type(sph_IO_data), intent(in) :: sph_IO
        type(sph_group_data), intent(in) :: sph_grps_IO
        type(buffer_4_gzip), intent(inout) :: zbuf
Parameters
file_name file name for IO (.gz is appended in this module)
Function/Subroutine Documentation
gz_read_geom_rtm_data_b()
subroutine gz_sph_modes_data_io_b::gz_read_geom_rtm_data_b (integer, intent(in) id_rank, type(buffer_4_gzip), intent(inout) zbuf, type(communication_table), intent(inout) comm_IO, type(sph_io_data), intent(inout) sph_IO)
Definition at line 164 of file gz_sph_modes_data_IO_b.f90.
References gz_domain_data_io_b::gz_read_domain_info_b(), gz_spherical_model_io_b::gz_read_gl_nodes_sph_b(), gz_spherical_model_io_b::gz_read_gl_resolution_sph_b(), gz_domain_data_io_b::gz_read_import_data_b(), gz_spherical_model_io_b::gz_read_rank_4_sph_b(), and gz_sph_global_1d_idx_io_b::gz_read_rtp_gl_1d_table_b().
Referenced by gz_sph_modes_file_io_b::gz_read_geom_rtm_file_b().
gz_read_geom_rtp_data_b()
subroutine gz_sph_modes_data_io_b::gz_read_geom_rtp_data_b (integer, intent(in) id_rank, type(buffer_4_gzip), intent(inout) zbuf, type(communication_table), intent(inout) comm_IO, type(sph_io_data), intent(inout) sph_IO, type(sph_group_data), intent(inout) sph_grps_IO)
Definition at line 62 of file gz_sph_modes_data_IO_b.f90.
References gz_domain_data_io_b::gz_read_domain_info_b(), gz_spherical_model_io_b::gz_read_gl_nodes_sph_b(), gz_spherical_model_io_b::gz_read_gl_resolution_sph_b(), gz_groups_io_b::gz_read_group_data_b(), gz_domain_data_io_b::gz_read_import_data_b(), gz_spherical_model_io_b::gz_read_rank_4_sph_b(), and gz_sph_global_1d_idx_io_b::gz_read_rtp_gl_1d_table_b().
Referenced by gz_sph_modes_file_io_b::gz_read_geom_rtp_file_b().
gz_read_modes_rlm_data_b()
subroutine gz_sph_modes_data_io_b::gz_read_modes_rlm_data_b (integer, intent(in) id_rank, type(buffer_4_gzip), intent(inout) zbuf, type(communication_table), intent(inout) comm_IO, type(sph_io_data), intent(inout) sph_IO)
Definition at line 195 of file gz_sph_modes_data_IO_b.f90.
References gz_domain_data_io_b::gz_read_domain_info_b(), gz_spherical_model_io_b::gz_read_gl_nodes_sph_b(), gz_spherical_model_io_b::gz_read_gl_resolution_sph_b(), gz_domain_data_io_b::gz_read_import_data_b(), gz_spherical_model_io_b::gz_read_rank_4_sph_b(), and gz_sph_global_1d_idx_io_b::gz_read_rj_gl_1d_table_b().
Referenced by gz_sph_modes_file_io_b::gz_read_modes_rlm_file_b().
gz_read_spectr_modes_rj_data_b()
subroutine gz_sph_modes_data_io_b::gz_read_spectr_modes_rj_data_b (integer, intent(in) id_rank, type(buffer_4_gzip), intent(inout) zbuf, type(communication_table), intent(inout) comm_IO, type(sph_io_data), intent(inout) sph_IO, type(sph_group_data), intent(inout) sph_grps_IO)
Definition at line 117 of file gz_sph_modes_data_IO_b.f90.
References gz_domain_data_io_b::gz_read_domain_info_b(), gz_spherical_model_io_b::gz_read_gl_nodes_sph_b(), gz_spherical_model_io_b::gz_read_gl_resolution_sph_b(), gz_groups_io_b::gz_read_group_data_b(), gz_domain_data_io_b::gz_read_import_data_b(), gz_spherical_model_io_b::gz_read_rank_4_sph_b(), and gz_sph_global_1d_idx_io_b::gz_read_rj_gl_1d_table_b().
Referenced by gz_sph_modes_file_io_b::gz_read_spectr_modes_rj_file_b().
gz_write_geom_rtm_data_b()
subroutine gz_sph_modes_data_io_b::gz_write_geom_rtm_data_b (integer, intent(in) id_rank, type(communication_table), intent(in) comm_IO, type(sph_io_data), intent(in) sph_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 321 of file gz_sph_modes_data_IO_b.f90.
References gz_domain_data_io_b::gz_write_domain_info_b(), gz_spherical_model_io_b::gz_write_gl_nodes_sph_b(), gz_spherical_model_io_b::gz_write_gl_resolution_sph_b(), gz_domain_data_io_b::gz_write_import_data_b(), gz_spherical_model_io_b::gz_write_rank_4_sph_b(), and gz_sph_global_1d_idx_io_b::gz_write_rtp_gl_1d_table_b().
Referenced by gz_sph_modes_file_io_b::gz_write_geom_rtm_file_b().
gz_write_geom_rtp_data_b()
subroutine gz_sph_modes_data_io_b::gz_write_geom_rtp_data_b (integer, intent(in) id_rank, type(communication_table), intent(in) comm_IO, type(sph_io_data), intent(in) sph_IO, type(sph_group_data), intent(in) sph_grps_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 227 of file gz_sph_modes_data_IO_b.f90.
References gz_domain_data_io_b::gz_write_domain_info_b(), gz_spherical_model_io_b::gz_write_gl_nodes_sph_b(), gz_spherical_model_io_b::gz_write_gl_resolution_sph_b(), gz_groups_io_b::gz_write_grp_data_b(), gz_domain_data_io_b::gz_write_import_data_b(), gz_spherical_model_io_b::gz_write_rank_4_sph_b(), and gz_sph_global_1d_idx_io_b::gz_write_rtp_gl_1d_table_b().
Referenced by gz_sph_modes_file_io_b::gz_write_geom_rtp_file_b().
gz_write_modes_rlm_data_b()
subroutine gz_sph_modes_data_io_b::gz_write_modes_rlm_data_b (integer, intent(in) id_rank, type(communication_table), intent(in) comm_IO, type(sph_io_data), intent(in) sph_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 348 of file gz_sph_modes_data_IO_b.f90.
References gz_domain_data_io_b::gz_write_domain_info_b(), gz_spherical_model_io_b::gz_write_gl_nodes_sph_b(), gz_spherical_model_io_b::gz_write_gl_resolution_sph_b(), gz_domain_data_io_b::gz_write_import_data_b(), gz_spherical_model_io_b::gz_write_rank_4_sph_b(), and gz_sph_global_1d_idx_io_b::gz_write_rj_gl_1d_table_b().
Referenced by gz_sph_modes_file_io_b::gz_write_modes_rlm_file_b().
gz_write_spectr_modes_rj_data_b()
subroutine gz_sph_modes_data_io_b::gz_write_spectr_modes_rj_data_b (integer, intent(in) id_rank, type(communication_table), intent(in) comm_IO, type(sph_io_data), intent(in) sph_IO, type(sph_group_data), intent(in) sph_grps_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 276 of file gz_sph_modes_data_IO_b.f90.
References gz_domain_data_io_b::gz_write_domain_info_b(), gz_spherical_model_io_b::gz_write_gl_nodes_sph_b(), gz_spherical_model_io_b::gz_write_gl_resolution_sph_b(), gz_groups_io_b::gz_write_grp_data_b(), gz_domain_data_io_b::gz_write_import_data_b(), gz_spherical_model_io_b::gz_write_rank_4_sph_b(), and gz_sph_global_1d_idx_io_b::gz_write_rj_gl_1d_table_b().
Referenced by gz_sph_modes_file_io_b::gz_write_spectr_modes_rj_file_b().