CALYPSO: ucd_data_to_buffer Module Reference
ucd_data_to_buffer Module Reference
Output routine for UCD data segments.
Functions/Subroutines
character(len=8+2+num_output *4+1) function ucd_num_comps (num_output, ncomp_out)
character(len=len_trim(field_name)+1+1) function ucd_field_name (field_name)
character(len=16+ncomp_dat *23+1) function ucd_each_field (inod_gl, ncomp_dat, dat_out)
character(len=3 *16+2 *5+1) function ucd_connect_head (nnod, nele, ncomp)
character(len=16+3+6+16 *nnod_ele+1) function ucd_each_connect (iele_gl, nnod_ele, ie0)
character(len=6) function ucd_eletype (nnod_ele)
integer(kind=kint) function nnod_ele_by_ucd_eletype (eletype)
Variables
character(len=3), parameter, private ucd_hex = 'hex'
character(len=3), parameter, private ucd_tri = 'tri'
character(len=4), parameter, private ucd_lne = 'line'
Detailed Description
Output routine for UCD data segments.
      function ucd_num_comps(num_output, ncomp_out)
      function ucd_field_name(field_name)
      function ucd_each_field(inod_gl, ncomp_dat, dat_out)
      function ucd_connect_head(nnod, nele, ncomp)
      function ucd_each_connect(iele_gl, nnod_ele, ie0)
      character(len=6) function ucd_eletype(nnod_ele)
      integer(kind = kint) function nnod_ele_by_ucd_eletype(eletype)
Function/Subroutine Documentation
nnod_ele_by_ucd_eletype()
integer(kind = kint) function ucd_data_to_buffer::nnod_ele_by_ucd_eletype (character(len = kchara), intent(in) eletype)
Definition at line 152 of file ucd_data_to_buffer.f90.
References skip_comment_f::cmp_no_case(), m_geometry_constants::num_linear_edge, m_geometry_constants::num_t_linear, m_geometry_constants::num_triangle, ucd_hex, ucd_lne, and ucd_tri.
Referenced by gz_udt_type_data_io::read_alloc_gz_ucd_mesh_data(), udt_type_data_io::read_alloc_ucd_mesh_data(), gz_ucd_data_io::read_gz_ucd_ele_connect(), and udt_data_io::read_ucd_ele_connect().
ucd_connect_head()
character(len=3*16+2*5+1) function ucd_data_to_buffer::ucd_connect_head (integer(kind = kint_gl), intent(in) nnod, integer(kind = kint_gl), intent(in) nele, integer(kind = kint), intent(in) ncomp)
Definition at line 93 of file ucd_data_to_buffer.f90.
References m_constants::izero.
Referenced by gz_ucd_file_mpi_io::gz_write_ucd_mesh_mpi(), gz_ucd_data_io::write_gz_udt_mesh_header(), and ucd_file_mpi_io::write_ucd_node_mpi().
ucd_each_connect()
character(len=16+3+6+16*nnod_ele+1) function ucd_data_to_buffer::ucd_each_connect (integer(kind = kint_gl), intent(in) iele_gl, integer(kind = kint), intent(in) nnod_ele, integer(kind = kint_gl), dimension(nnod_ele), intent(in) ie0)
Definition at line 108 of file ucd_data_to_buffer.f90.
References m_constants::ione, and ucd_eletype().
Referenced by zlib_cvt_ucd_data::defleate_ucd_connect(), gz_ucd_data_io::write_gz_ucd_mesh_connect(), and ucd_file_mpi_io::write_ucd_connect_mpi().
ucd_each_field()
character(len=16+ncomp_dat*23+1) function ucd_data_to_buffer::ucd_each_field (integer(kind = kint_gl), intent(in) inod_gl, integer(kind = kint), intent(in) ncomp_dat, real(kind = kreal), dimension(ncomp_dat), intent(in) dat_out)
Definition at line 72 of file ucd_data_to_buffer.f90.
Referenced by zlib_cvt_ucd_data::defleate_ucd_vector(), gz_ucd_data_io::write_gz_ucd_field_data(), ucd_file_mpi_io::write_ucd_data_mpi(), and ucd_file_mpi_io::write_ucd_node_mpi().
ucd_eletype()
character(len=6) function ucd_data_to_buffer::ucd_eletype (integer(kind = kint), intent(in) nnod_ele)
Definition at line 130 of file ucd_data_to_buffer.f90.
References m_geometry_constants::num_linear_edge, m_geometry_constants::num_t_linear, m_geometry_constants::num_triangle, ucd_hex, ucd_lne, and ucd_tri.
Referenced by ucd_each_connect(), and udt_data_io::write_ucd_mesh_connect().
ucd_field_name()
character(len=len_trim(field_name) +1+1) function ucd_data_to_buffer::ucd_field_name (character(len = kchara), intent(in) field_name)
Definition at line 59 of file ucd_data_to_buffer.f90.
Referenced by gz_ucd_file_mpi_io::gz_write_ucd_data_mpi(), ucd_file_mpi_io::write_ucd_data_mpi(), and udt_data_io::write_udt_field_header().
ucd_num_comps()
character(len=8+2+num_output*4+1) function ucd_data_to_buffer::ucd_num_comps (integer(kind = kint), intent(in) num_output, integer(kind = kint), dimension(num_output), intent(in) ncomp_out)
Definition at line 40 of file ucd_data_to_buffer.f90.
Referenced by gz_ucd_file_mpi_io::gz_write_ucd_data_mpi(), ucd_file_mpi_io::write_ucd_data_mpi(), and udt_data_io::write_udt_field_header().
Variable Documentation
ucd_hex
character(len=3), parameter, private ucd_data_to_buffer::ucd_hex = 'hex' private
Definition at line 28 of file ucd_data_to_buffer.f90.
Referenced by nnod_ele_by_ucd_eletype(), and ucd_eletype().
ucd_lne
character(len=4), parameter, private ucd_data_to_buffer::ucd_lne = 'line' private
Definition at line 30 of file ucd_data_to_buffer.f90.
Referenced by nnod_ele_by_ucd_eletype(), and ucd_eletype().
ucd_tri
character(len=3), parameter, private ucd_data_to_buffer::ucd_tri = 'tri' private
Definition at line 29 of file ucd_data_to_buffer.f90.
Referenced by nnod_ele_by_ucd_eletype(), and ucd_eletype().