CALYPSO: m_sph_modes_grid_labels Module Reference
m_sph_modes_grid_labels Module Reference
Comments for spherical harmonics indexing data.
Functions/Subroutines
character(len=ilen_sph_para) function hd_sph_para ()
character(len=ilen_rtp_glbl) function hd_rtp_glbl ()
character(len=ilen_rtp_comm) function hd_rtp_comm ()
character(len=ilen_rj_glbl) function hd_rj_glbl ()
character(len=ilen_rj_comm) function hd_rj_comm ()
character(len=ilen_rlm_glbl) function hd_rlm_glbl ()
character(len=ilen_sgmt) function hd_segment ()
character(len=ilen_trnc) function hd_trunc ()
character(len=ilen_rgrd) function hd_rgrid ()
character(len=ilen_tgrd) function hd_tgrid ()
character(len=ilen_pgrd) function hd_pgrid ()
character(len=ilen_jmde) function hd_jmode ()
character(len=ilen_grphd) function hd_grphd ()
character(len=ilen_ngrphd) function hd_ngrphd ()
character(len=ilen_rgrphd) function hd_rgrphd ()
character(len=ilen_tgrphd) function hd_tgrphd ()
character(len=ilen_pgrphd) function hd_pgrphd ()
character(len=ilen_kgrphd) function hd_kgrphd ()
character(len=ilen_jgrphd) function hd_jgrphd ()
Variables
integer(kind=kint), parameter ilen_sph_para = 1+24+14+34+27+1+6
length of hd_sph_para
integer(kind=kint), parameter ilen_rtp_glbl = 1+40+21+30+1+5
length of hd_rtp_glbl
integer(kind=kint), parameter ilen_rtp_comm = 1+39+1+3
length of hd_rtp_comm
integer(kind=kint), parameter ilen_rj_glbl = 1+40+21+32+1+5
length of hd_rj_glbl
integer(kind=kint), parameter ilen_rj_comm = 1+41+1+3
length of hd_rj_comm
integer(kind=kint), parameter ilen_rlm_glbl = 1+40+21+36+1+5
length of hd_rlm_glbl
integer(kind=kint), parameter ilen_sgmt = 1+11+31+1+4
length of hd_segment
integer(kind=kint), parameter ilen_trnc = 1+22+42+1+4
length of hd_trunc
integer(kind=kint), parameter ilen_rgrd = 1+33+13+1+4
length of hd_rgrid
integer(kind=kint), parameter ilen_tgrd = 1+33+17+1+4
length of hd_tgrid
integer(kind=kint), parameter ilen_pgrd = 1+46+15+1+4
length of hd_pgrid
integer(kind=kint), parameter ilen_jmde = 1+33+41+1+4
length of hd_jmode
integer(kind=kint), parameter ilen_grphd = 1+12+1+3
length of hd_grphd
integer(kind=kint), parameter ilen_ngrphd = 1+13+1+3
length of hd_ngrphd
integer(kind=kint), parameter ilen_rgrphd = 1+15+1+3
length of hd_rgrphd
integer(kind=kint), parameter ilen_tgrphd = 1+19+1+3
length of hd_tgrphd
integer(kind=kint), parameter ilen_pgrphd = 1+14+1+3
length of hd_pgrphd
integer(kind=kint), parameter ilen_kgrphd = 1+25+1+3
length of hd_pgrphd
integer(kind=kint), parameter ilen_jgrphd = 1+28+1+3
length of hd_pgrphd
Detailed Description
Comments for spherical harmonics indexing data.
      character(len=ilen_sph_para) function hd_sph_para()
      character(len=ilen_rtp_glbl) function hd_rtp_glbl()
      character(len=ilen_rtp_comm) function hd_rtp_comm()
      character(len=ilen_rj_glbl) function hd_rj_glbl()
      character(len=ilen_rj_comm) function hd_rj_comm()
      character(len=ilen_rlm_glbl) function hd_rlm_glbl()
      character(len=ilen_sgmt) function hd_segment()
      character(len=ilen_trnc) function hd_trunc()
      character(len=ilen_rgrd) function hd_rgrid()
      character(len=ilen_tgrd) function hd_tgrid()
      character(len=ilen_pgrd) function hd_pgrid()
      character(len=ilen_jmde) function hd_jmode()
      character(len=ilen_grphd) function hd_grphd()
      character(len=ilen_ngrphd) function hd_ngrphd()
      character(len=ilen_rgrphd) function hd_rgrphd()
      character(len=ilen_tgrphd) function hd_tgrphd()
      character(len=ilen_pgrphd) function hd_pgrphd()
      character(len=ilen_kgrphd) function hd_kgrphd()
      character(len=ilen_jgrphd) function hd_jgrphd()
Function/Subroutine Documentation
hd_grphd()
character(len=ilen_grphd) function m_sph_modes_grid_labels::hd_grphd
Definition at line 243 of file m_sph_modes_grid_labels.f90.
Referenced by gz_mpi_sph_modes_data_io::gz_mpi_read_geom_rtp_data(), gz_mpi_sph_modes_data_io::gz_mpi_read_spectr_rj_data(), gz_mpi_sph_modes_data_io::gz_mpi_write_geom_rtp_data(), gz_mpi_sph_modes_data_io::gz_mpi_write_spectr_rj_data(), mpi_sph_modes_data_io::mpi_read_geom_rtp_data(), mpi_sph_modes_data_io::mpi_read_spectr_rj_data(), mpi_sph_modes_data_io::mpi_write_geom_rtp_data(), mpi_sph_modes_data_io::mpi_write_spectr_rj_data(), sph_modes_grids_data_io::write_geom_rtp_data(), gz_sph_modes_grids_data_io::write_geom_rtp_data_gz(), sph_modes_grids_data_io::write_spectr_modes_rj_data(), and gz_sph_modes_grids_data_io::write_spectr_modes_rj_data_gz().
hd_jgrphd()
character(len=ilen_jgrphd) function m_sph_modes_grid_labels::hd_jgrphd
Definition at line 304 of file m_sph_modes_grid_labels.f90.
Referenced by gz_mpi_sph_modes_data_io::gz_mpi_read_spectr_rj_data(), gz_mpi_sph_modes_data_io::gz_mpi_write_spectr_rj_data(), mpi_sph_modes_data_io::mpi_read_spectr_rj_data(), mpi_sph_modes_data_io::mpi_write_spectr_rj_data(), sph_modes_grids_data_io::write_spectr_modes_rj_data(), and gz_sph_modes_grids_data_io::write_spectr_modes_rj_data_gz().
hd_jmode()
character(len=ilen_jmde) function m_sph_modes_grid_labels::hd_jmode
Definition at line 230 of file m_sph_modes_grid_labels.f90.
Referenced by gz_mpi_sph_gl_1d_idx_io::gz_mpi_read_rj_gl_1d_table(), gz_mpi_sph_gl_1d_idx_io::gz_mpi_write_rj_gl_1d_table(), mpi_sph_gl_1d_idx_io::mpi_read_rj_gl_1d_table(), mpi_sph_gl_1d_idx_io::mpi_write_rj_gl_1d_table(), sph_global_1d_idx_io::write_rj_gl_1d_table(), and gz_sph_global_1d_idx_io::write_rj_gl_1d_table_gz().
hd_kgrphd()
character(len=ilen_kgrphd) function m_sph_modes_grid_labels::hd_kgrphd
Definition at line 294 of file m_sph_modes_grid_labels.f90.
Referenced by gz_mpi_sph_modes_data_io::gz_mpi_read_spectr_rj_data(), gz_mpi_sph_modes_data_io::gz_mpi_write_spectr_rj_data(), mpi_sph_modes_data_io::mpi_read_spectr_rj_data(), mpi_sph_modes_data_io::mpi_write_spectr_rj_data(), sph_modes_grids_data_io::write_spectr_modes_rj_data(), and gz_sph_modes_grids_data_io::write_spectr_modes_rj_data_gz().
hd_ngrphd()
character(len=ilen_ngrphd) function m_sph_modes_grid_labels::hd_ngrphd
Definition at line 253 of file m_sph_modes_grid_labels.f90.
Referenced by gz_mpi_sph_modes_data_io::gz_mpi_read_geom_rtp_data(), gz_mpi_sph_modes_data_io::gz_mpi_write_geom_rtp_data(), mpi_sph_modes_data_io::mpi_read_geom_rtp_data(), mpi_sph_modes_data_io::mpi_write_geom_rtp_data(), sph_modes_grids_data_io::write_geom_rtp_data(), and gz_sph_modes_grids_data_io::write_geom_rtp_data_gz().
hd_pgrid()
character(len=ilen_pgrd) function m_sph_modes_grid_labels::hd_pgrid
Definition at line 218 of file m_sph_modes_grid_labels.f90.
Referenced by gz_mpi_sph_gl_1d_idx_io::gz_mpi_read_rtp_gl_1d_table(), gz_mpi_sph_gl_1d_idx_io::gz_mpi_write_rtp_gl_1d_table(), mpi_sph_gl_1d_idx_io::mpi_read_rtp_gl_1d_table(), mpi_sph_gl_1d_idx_io::mpi_write_rtp_gl_1d_table(), sph_global_1d_idx_io::write_rtp_gl_1d_table(), and gz_sph_global_1d_idx_io::write_rtp_gl_1d_table_gz().
hd_pgrphd()
character(len=ilen_pgrphd) function m_sph_modes_grid_labels::hd_pgrphd
Definition at line 283 of file m_sph_modes_grid_labels.f90.
Referenced by gz_mpi_sph_modes_data_io::gz_mpi_read_geom_rtp_data(), gz_mpi_sph_modes_data_io::gz_mpi_write_geom_rtp_data(), mpi_sph_modes_data_io::mpi_read_geom_rtp_data(), mpi_sph_modes_data_io::mpi_write_geom_rtp_data(), sph_modes_grids_data_io::write_geom_rtp_data(), and gz_sph_modes_grids_data_io::write_geom_rtp_data_gz().
hd_rgrid()
character(len=ilen_rgrd) function m_sph_modes_grid_labels::hd_rgrid
Definition at line 196 of file m_sph_modes_grid_labels.f90.
Referenced by gz_mpi_sph_gl_1d_idx_io::gz_mpi_read_rj_gl_1d_table(), gz_mpi_sph_gl_1d_idx_io::gz_mpi_read_rtp_gl_1d_table(), gz_mpi_sph_gl_1d_idx_io::gz_mpi_write_rj_gl_1d_table(), gz_mpi_sph_gl_1d_idx_io::gz_mpi_write_rtp_gl_1d_table(), mpi_sph_gl_1d_idx_io::mpi_read_rj_gl_1d_table(), mpi_sph_gl_1d_idx_io::mpi_read_rtp_gl_1d_table(), mpi_sph_gl_1d_idx_io::mpi_write_rj_gl_1d_table(), mpi_sph_gl_1d_idx_io::mpi_write_rtp_gl_1d_table(), sph_global_1d_idx_io::write_rj_gl_1d_table(), gz_sph_global_1d_idx_io::write_rj_gl_1d_table_gz(), sph_global_1d_idx_io::write_rtp_gl_1d_table(), and gz_sph_global_1d_idx_io::write_rtp_gl_1d_table_gz().
hd_rgrphd()
character(len=ilen_rgrphd) function m_sph_modes_grid_labels::hd_rgrphd
Definition at line 263 of file m_sph_modes_grid_labels.f90.
Referenced by gz_mpi_sph_modes_data_io::gz_mpi_read_geom_rtp_data(), gz_mpi_sph_modes_data_io::gz_mpi_write_geom_rtp_data(), mpi_sph_modes_data_io::mpi_read_geom_rtp_data(), mpi_sph_modes_data_io::mpi_write_geom_rtp_data(), sph_modes_grids_data_io::write_geom_rtp_data(), and gz_sph_modes_grids_data_io::write_geom_rtp_data_gz().
hd_rj_comm()
character(len=ilen_rj_comm) function m_sph_modes_grid_labels::hd_rj_comm
Definition at line 146 of file m_sph_modes_grid_labels.f90.
Referenced by gz_mpi_sph_modes_data_io::gz_mpi_read_modes_rlm_data(), gz_mpi_sph_modes_data_io::gz_mpi_read_spectr_rj_data(), gz_mpi_sph_modes_data_io::gz_mpi_write_modes_rlm_data(), gz_mpi_sph_modes_data_io::gz_mpi_write_spectr_rj_data(), mpi_sph_modes_data_io::mpi_read_modes_rlm_data(), mpi_sph_modes_data_io::mpi_read_spectr_rj_data(), mpi_sph_modes_data_io::mpi_write_modes_rlm_data(), mpi_sph_modes_data_io::mpi_write_spectr_rj_data(), sph_modes_grids_data_io::write_modes_rlm_data(), gz_sph_modes_grids_data_io::write_modes_rlm_data_gz(), sph_modes_grids_data_io::write_spectr_modes_rj_data(), and gz_sph_modes_grids_data_io::write_spectr_modes_rj_data_gz().
hd_rj_glbl()
character(len=ilen_rj_glbl) function m_sph_modes_grid_labels::hd_rj_glbl
Definition at line 133 of file m_sph_modes_grid_labels.f90.
Referenced by gz_mpi_sph_modes_data_io::gz_mpi_read_spectr_rj_data(), gz_mpi_sph_modes_data_io::gz_mpi_write_spectr_rj_data(), mpi_sph_modes_data_io::mpi_read_spectr_rj_data(), mpi_sph_modes_data_io::mpi_write_spectr_rj_data(), sph_modes_grids_data_io::write_spectr_modes_rj_data(), and gz_sph_modes_grids_data_io::write_spectr_modes_rj_data_gz().
hd_rlm_glbl()
character(len=ilen_rlm_glbl) function m_sph_modes_grid_labels::hd_rlm_glbl
Definition at line 158 of file m_sph_modes_grid_labels.f90.
Referenced by gz_mpi_sph_modes_data_io::gz_mpi_read_modes_rlm_data(), gz_mpi_sph_modes_data_io::gz_mpi_write_modes_rlm_data(), mpi_sph_modes_data_io::mpi_read_modes_rlm_data(), mpi_sph_modes_data_io::mpi_write_modes_rlm_data(), sph_modes_grids_data_io::write_modes_rlm_data(), and gz_sph_modes_grids_data_io::write_modes_rlm_data_gz().
hd_rtp_comm()
character(len=ilen_rtp_comm) function m_sph_modes_grid_labels::hd_rtp_comm
Definition at line 121 of file m_sph_modes_grid_labels.f90.
Referenced by gz_mpi_sph_modes_data_io::gz_mpi_read_geom_rtm_data(), gz_mpi_sph_modes_data_io::gz_mpi_read_geom_rtp_data(), gz_mpi_sph_modes_data_io::gz_mpi_write_geom_rtm_data(), gz_mpi_sph_modes_data_io::gz_mpi_write_geom_rtp_data(), mpi_sph_modes_data_io::mpi_read_geom_rtm_data(), mpi_sph_modes_data_io::mpi_read_geom_rtp_data(), mpi_sph_modes_data_io::mpi_write_geom_rtm_data(), mpi_sph_modes_data_io::mpi_write_geom_rtp_data(), sph_modes_grids_data_io::write_geom_rtm_data(), gz_sph_modes_grids_data_io::write_geom_rtm_data_gz(), sph_modes_grids_data_io::write_geom_rtp_data(), and gz_sph_modes_grids_data_io::write_geom_rtp_data_gz().
hd_rtp_glbl()
character(len=ilen_rtp_glbl) function m_sph_modes_grid_labels::hd_rtp_glbl
Definition at line 108 of file m_sph_modes_grid_labels.f90.
Referenced by gz_mpi_sph_modes_data_io::gz_mpi_read_geom_rtm_data(), gz_mpi_sph_modes_data_io::gz_mpi_read_geom_rtp_data(), gz_mpi_sph_modes_data_io::gz_mpi_write_geom_rtm_data(), gz_mpi_sph_modes_data_io::gz_mpi_write_geom_rtp_data(), mpi_sph_modes_data_io::mpi_read_geom_rtm_data(), mpi_sph_modes_data_io::mpi_read_geom_rtp_data(), mpi_sph_modes_data_io::mpi_write_geom_rtm_data(), mpi_sph_modes_data_io::mpi_write_geom_rtp_data(), sph_modes_grids_data_io::write_geom_rtm_data(), gz_sph_modes_grids_data_io::write_geom_rtm_data_gz(), sph_modes_grids_data_io::write_geom_rtp_data(), and gz_sph_modes_grids_data_io::write_geom_rtp_data_gz().
hd_segment()
character(len=ilen_sgmt) function m_sph_modes_grid_labels::hd_segment
Definition at line 172 of file m_sph_modes_grid_labels.f90.
Referenced by gz_mpi_spherical_model_io::gz_mpi_read_rank_4_sph(), gz_mpi_spherical_model_io::gz_mpi_write_rank_4_sph(), mpi_spherical_model_io::mpi_read_rank_4_sph(), mpi_spherical_model_io::mpi_write_rank_4_sph(), spherical_model_io::write_rank_4_sph(), and gz_spherical_model_io::write_rank_4_sph_gz().
hd_sph_para()
character(len=ilen_sph_para) function m_sph_modes_grid_labels::hd_sph_para
Definition at line 94 of file m_sph_modes_grid_labels.f90.
Referenced by gz_mpi_sph_modes_data_io::gz_mpi_read_geom_rtm_data(), gz_mpi_sph_modes_data_io::gz_mpi_read_geom_rtp_data(), gz_mpi_sph_modes_data_io::gz_mpi_read_modes_rlm_data(), gz_mpi_sph_modes_data_io::gz_mpi_read_spectr_rj_data(), gz_mpi_sph_modes_data_io::gz_mpi_write_geom_rtm_data(), gz_mpi_sph_modes_data_io::gz_mpi_write_geom_rtp_data(), gz_mpi_sph_modes_data_io::gz_mpi_write_modes_rlm_data(), gz_mpi_sph_modes_data_io::gz_mpi_write_spectr_rj_data(), mpi_sph_modes_data_io::mpi_read_geom_rtm_data(), mpi_sph_modes_data_io::mpi_read_geom_rtp_data(), mpi_sph_modes_data_io::mpi_read_modes_rlm_data(), mpi_sph_modes_data_io::mpi_read_spectr_rj_data(), mpi_sph_modes_data_io::mpi_write_geom_rtm_data(), mpi_sph_modes_data_io::mpi_write_geom_rtp_data(), mpi_sph_modes_data_io::mpi_write_modes_rlm_data(), mpi_sph_modes_data_io::mpi_write_spectr_rj_data(), sph_modes_grids_data_io::write_geom_rtm_data(), gz_sph_modes_grids_data_io::write_geom_rtm_data_gz(), sph_modes_grids_data_io::write_geom_rtp_data(), gz_sph_modes_grids_data_io::write_geom_rtp_data_gz(), sph_modes_grids_data_io::write_modes_rlm_data(), gz_sph_modes_grids_data_io::write_modes_rlm_data_gz(), sph_modes_grids_data_io::write_spectr_modes_rj_data(), and gz_sph_modes_grids_data_io::write_spectr_modes_rj_data_gz().
hd_tgrid()
character(len=ilen_tgrd) function m_sph_modes_grid_labels::hd_tgrid
Definition at line 207 of file m_sph_modes_grid_labels.f90.
Referenced by gz_mpi_sph_gl_1d_idx_io::gz_mpi_read_rtp_gl_1d_table(), gz_mpi_sph_gl_1d_idx_io::gz_mpi_write_rtp_gl_1d_table(), mpi_sph_gl_1d_idx_io::mpi_read_rtp_gl_1d_table(), mpi_sph_gl_1d_idx_io::mpi_write_rtp_gl_1d_table(), sph_global_1d_idx_io::write_rtp_gl_1d_table(), and gz_sph_global_1d_idx_io::write_rtp_gl_1d_table_gz().
hd_tgrphd()
character(len=ilen_tgrphd) function m_sph_modes_grid_labels::hd_tgrphd
Definition at line 273 of file m_sph_modes_grid_labels.f90.
Referenced by gz_mpi_sph_modes_data_io::gz_mpi_read_geom_rtp_data(), gz_mpi_sph_modes_data_io::gz_mpi_write_geom_rtp_data(), mpi_sph_modes_data_io::mpi_read_geom_rtp_data(), mpi_sph_modes_data_io::mpi_write_geom_rtp_data(), sph_modes_grids_data_io::write_geom_rtp_data(), and gz_sph_modes_grids_data_io::write_geom_rtp_data_gz().
hd_trunc()
character(len=ilen_trnc) function m_sph_modes_grid_labels::hd_trunc
Definition at line 183 of file m_sph_modes_grid_labels.f90.
Referenced by gz_mpi_spherical_model_io::gz_mpi_read_gl_reso_sph(), gz_mpi_spherical_model_io::gz_mpi_write_gl_reso_sph(), mpi_spherical_model_io::mpi_read_gl_reso_sph(), mpi_spherical_model_io::mpi_write_gl_reso_sph(), spherical_model_io::write_gl_resolution_sph(), and gz_spherical_model_io::write_gl_resolution_sph_gz().
Variable Documentation
ilen_grphd
integer(kind = kint), parameter m_sph_modes_grid_labels::ilen_grphd = 1+12+1+3
length of hd_grphd
Definition at line 72 of file m_sph_modes_grid_labels.f90.
ilen_jgrphd
integer(kind = kint), parameter m_sph_modes_grid_labels::ilen_jgrphd = 1+28+1+3
length of hd_pgrphd
Definition at line 86 of file m_sph_modes_grid_labels.f90.
ilen_jmde
integer(kind = kint), parameter m_sph_modes_grid_labels::ilen_jmde = 1+33+41+1+4
length of hd_jmode
Definition at line 69 of file m_sph_modes_grid_labels.f90.
ilen_kgrphd
integer(kind = kint), parameter m_sph_modes_grid_labels::ilen_kgrphd = 1+25+1+3
length of hd_pgrphd
Definition at line 84 of file m_sph_modes_grid_labels.f90.
ilen_ngrphd
integer(kind = kint), parameter m_sph_modes_grid_labels::ilen_ngrphd = 1+13+1+3
length of hd_ngrphd
Definition at line 75 of file m_sph_modes_grid_labels.f90.
ilen_pgrd
integer(kind = kint), parameter m_sph_modes_grid_labels::ilen_pgrd = 1+46+15+1+4
length of hd_pgrid
Definition at line 67 of file m_sph_modes_grid_labels.f90.
ilen_pgrphd
integer(kind = kint), parameter m_sph_modes_grid_labels::ilen_pgrphd = 1+14+1+3
length of hd_pgrphd
Definition at line 81 of file m_sph_modes_grid_labels.f90.
ilen_rgrd
integer(kind = kint), parameter m_sph_modes_grid_labels::ilen_rgrd = 1+33+13+1+4
length of hd_rgrid
Definition at line 63 of file m_sph_modes_grid_labels.f90.
ilen_rgrphd
integer(kind = kint), parameter m_sph_modes_grid_labels::ilen_rgrphd = 1+15+1+3
length of hd_rgrphd
Definition at line 77 of file m_sph_modes_grid_labels.f90.
ilen_rj_comm
integer(kind = kint), parameter m_sph_modes_grid_labels::ilen_rj_comm = 1+41+1+3
length of hd_rj_comm
Definition at line 52 of file m_sph_modes_grid_labels.f90.
ilen_rj_glbl
integer(kind = kint), parameter m_sph_modes_grid_labels::ilen_rj_glbl = 1+40+21+32+1+5
length of hd_rj_glbl
Definition at line 50 of file m_sph_modes_grid_labels.f90.
ilen_rlm_glbl
integer(kind = kint), parameter m_sph_modes_grid_labels::ilen_rlm_glbl = 1+40+21+36+1+5
length of hd_rlm_glbl
Definition at line 55 of file m_sph_modes_grid_labels.f90.
ilen_rtp_comm
integer(kind = kint), parameter m_sph_modes_grid_labels::ilen_rtp_comm = 1+39+1+3
length of hd_rtp_comm
Definition at line 47 of file m_sph_modes_grid_labels.f90.
ilen_rtp_glbl
integer(kind = kint), parameter m_sph_modes_grid_labels::ilen_rtp_glbl = 1+40+21+30+1+5
length of hd_rtp_glbl
Definition at line 45 of file m_sph_modes_grid_labels.f90.
ilen_sgmt
integer(kind = kint), parameter m_sph_modes_grid_labels::ilen_sgmt = 1+11+31+1+4
length of hd_segment
Definition at line 58 of file m_sph_modes_grid_labels.f90.
ilen_sph_para
integer(kind = kint), parameter m_sph_modes_grid_labels::ilen_sph_para = 1+24+14+34+27+1+6
length of hd_sph_para
Definition at line 42 of file m_sph_modes_grid_labels.f90.
ilen_tgrd
integer(kind = kint), parameter m_sph_modes_grid_labels::ilen_tgrd = 1+33+17+1+4
length of hd_tgrid
Definition at line 65 of file m_sph_modes_grid_labels.f90.
ilen_tgrphd
integer(kind = kint), parameter m_sph_modes_grid_labels::ilen_tgrphd = 1+19+1+3
length of hd_tgrphd
Definition at line 79 of file m_sph_modes_grid_labels.f90.
ilen_trnc
integer(kind = kint), parameter m_sph_modes_grid_labels::ilen_trnc = 1+22+42+1+4
length of hd_trunc
Definition at line 60 of file m_sph_modes_grid_labels.f90.