CALYPSO: set_node_group_types Module Reference
set_node_group_types Module Reference
set surface boundary condition flags from conterol input
Functions/Subroutines
subroutine set_bc_group_types_scalar (bc_type_ctl, ibc_type)
subroutine set_bc_group_types_vector (bc_type_ctl, ibc_type)
subroutine set_bc_group_types_sgs_scalar (bc_type_ctl, ibc_type)
subroutine set_bc_group_types_sgs_vect (bc_type_ctl, ibc_type)
subroutine set_bc_group_types_rotation (bc_type_ctl, ibc_type)
subroutine set_bc_group_types_sph_center (bc_type_ctl, ibc_type)
subroutine set_bc_group_types_sph_velo (bc_type_ctl, ibc_type)
subroutine set_bc_group_types_sph_magne (bc_type_ctl, ibc_type)
subroutine set_bc_group_types_fluxes (bc_type_ctl, ibc_type)
Variables
character(len=kchara), parameter, private fixed_bc = 'fixed'
control name for fixed field by control
character(len=kchara), parameter, private fixed_ctl_bc = 'fixed_ctl'
control name for fixed field by control
character(len=kchara), parameter, private fixed_file = 'file'
control name for fixed field by external file
character(len=kchara), parameter, private fixed_file_bc = 'fixed_file'
control name for fixed field by external file
character(len=kchara), parameter evo_field_file_bc = 'evolved_field'
control name for evolved field by external file
character(len=kchara), parameter evo_flux_file_bc = 'evolved_flux'
control name for evolved flux by external file
character(len=kchara), parameter, private fixed_sgs = 'sgs'
control name for fixed field in SGS model
character(len=kchara), parameter, private fixed_x = 'fix_x'
control name for fixed x-componenet by control
character(len=kchara), parameter, private fixed_y = 'fix_y'
control name for fixed y-componenet by control
character(len=kchara), parameter, private fixed_z = 'fix_z'
control name for fixed z-componenet by control
character(len=kchara), parameter, private fix_ctl_x = 'fix_ctl_x'
control name for fixed x-componenet by control
character(len=kchara), parameter, private fix_ctl_y = 'fix_ctl_y'
control name for fixed y-componenet by control
character(len=kchara), parameter, private fix_ctl_z = 'fix_ctl_z'
control name for fixed z-componenet by control
character(len=kchara), parameter, private bc_file_x = 'file_x'
control name for fixed x-componenet by external file
character(len=kchara), parameter, private bc_file_y = 'file_y'
control name for fixed y-componenet by external file
character(len=kchara), parameter, private bc_file_z = 'file_z'
control name for fixed z-componenet by external file
character(len=kchara), parameter, private fix_file_x = 'fix_file_x'
control name for fixed x-componenet by external file
character(len=kchara), parameter, private fix_file_y = 'fix_file_y'
control name for fixed y-componenet by external file
character(len=kchara), parameter, private fix_file_z = 'fix_file_z'
control name for fixed z-componenet by external file
character(len=kchara), parameter, private fix_sgs_x = 'sgs_x'
control name for fixed x-componenet in SGS model
character(len=kchara), parameter, private fix_sgs_y = 'sgs_y'
control name for fixed y-componenet in SGS model
character(len=kchara), parameter, private fix_sgs_z = 'sgs_z'
control name for fixed z-componenet in SGS model
character(len=kchara), parameter, private fix_rot_x = 'rot_x'
control name for fixed rotation around x-axis boundary
character(len=kchara), parameter, private fix_rot_y = 'rot_y'
control name for fixed rotation around y-axis boundary
character(len=kchara), parameter, private fix_rot_z = 'rot_z'
control name for fixed rotation around z-axis boundary
character(len=kchara), parameter, private free_slip_sph = 'free_slip_sph'
control name for free slip boundary for spherical shell
character(len=kchara), parameter, private non_slip_sph = 'non_slip_sph'
control name for non-slip boundary for spherical shell
character(len=kchara), parameter, private rot_inner_core = 'rot_inner_core'
control name for rotetable inner core for spherical shell
character(len=kchara), parameter insulator_sph = 'insulator'
control name for insulated for spherical shell
character(len=kchara), parameter pseudo_vacuum_sph = 'pseudo_vacuum'
control name for psuedo vacuum for spherical shell
character(len=kchara), parameter, private fill_sph_center = 'sph_to_center'
control name to filling to center
character(len=kchara), parameter, private fix_sph_center = 'fix_at_center'
control name to filling to center
character(len=kchara), parameter, private flux_bc = 'fixed_flux'
control name for fixed flux by control
character(len=kchara), parameter, private flux_file_bc = 'fixed_flux_file'
control name for fixed flux by external file
Detailed Description
set surface boundary condition flags from conterol input
      subroutine set_bc_group_types_scalar(bc_type_ctl, ibc_type)
      subroutine set_bc_group_types_vector(bc_type_ctl, ibc_type)
      subroutine set_bc_group_types_sgs_scalar(bc_type_ctl, ibc_type)
      subroutine set_bc_group_types_sgs_vect(bc_type_ctl, ibc_type)
      subroutine set_bc_group_types_rotation(bc_type_ctl, ibc_type)
      subroutine set_bc_group_types_sph_center(bc_type_ctl, ibc_type)
      subroutine set_bc_group_types_sph_velo(bc_type_ctl, ibc_type)
      subroutine set_bc_group_types_sph_magne(bc_type_ctl, ibc_type)
      subroutine set_bc_group_types_fluxes(bc_type_ctl, ibc_type)
Function/Subroutine Documentation
set_bc_group_types_fluxes()
subroutine set_node_group_types::set_bc_group_types_fluxes (character (len=kchara), intent(in) bc_type_ctl, integer(kind = kint), intent(inout) ibc_type)
Definition at line 292 of file set_node_group_types.f90.
References skip_comment_f::cmp_no_case(), evo_flux_file_bc, flux_bc, flux_file_bc, m_boundary_condition_ids::iflag_bc_evo_flux, m_boundary_condition_ids::iflag_bc_file_flux, and m_boundary_condition_ids::iflag_bc_fix_flux.
Referenced by set_control_4_composition::s_set_control_4_composition(), and set_control_4_temp::s_set_control_4_temp().
set_bc_group_types_rotation()
subroutine set_node_group_types::set_bc_group_types_rotation (character (len=kchara), intent(in) bc_type_ctl, integer(kind = kint), intent(inout) ibc_type)
Definition at line 222 of file set_node_group_types.f90.
References skip_comment_f::cmp_no_case(), fix_rot_x, fix_rot_y, fix_rot_z, and m_boundary_condition_ids::iflag_bc_rot.
Referenced by set_control_4_velo::s_set_control_4_velo().
set_bc_group_types_scalar()
subroutine set_node_group_types::set_bc_group_types_scalar (character (len=kchara), intent(in) bc_type_ctl, integer(kind = kint), intent(inout) ibc_type)
Definition at line 134 of file set_node_group_types.f90.
References skip_comment_f::cmp_no_case(), evo_field_file_bc, fixed_bc, fixed_ctl_bc, fixed_file, fixed_file_bc, m_boundary_condition_ids::iflag_bc_evo_field, m_boundary_condition_ids::iflag_bc_file_s, and m_boundary_condition_ids::iflag_bc_fix_s.
Referenced by set_control_4_composition::s_set_control_4_composition(), set_control_4_press::s_set_control_4_press(), set_control_4_temp::s_set_control_4_temp(), and set_surface_group_types::set_surf_group_types_scalar().
set_bc_group_types_sgs_scalar()
subroutine set_node_group_types::set_bc_group_types_sgs_scalar (character (len=kchara), intent(in) bc_type_ctl, integer(kind = kint), intent(inout) ibc_type)
Definition at line 190 of file set_node_group_types.f90.
References skip_comment_f::cmp_no_case(), fixed_sgs, and m_boundary_condition_ids::iflag_bc_sgs_s.
Referenced by set_control_4_press::s_set_control_4_press(), set_control_4_temp::s_set_control_4_temp(), and set_surface_group_types::set_surf_group_types_scalar().
set_bc_group_types_sgs_vect()
subroutine set_node_group_types::set_bc_group_types_sgs_vect (character (len=kchara), intent(in) bc_type_ctl, integer(kind = kint), intent(inout) ibc_type)
Definition at line 204 of file set_node_group_types.f90.
References skip_comment_f::cmp_no_case(), fix_sgs_x, fix_sgs_y, fix_sgs_z, m_boundary_condition_ids::iflag_bc_sgs_x, m_boundary_condition_ids::iflag_bc_sgs_y, and m_boundary_condition_ids::iflag_bc_sgs_z.
Referenced by set_control_4_magne::s_set_control_4_magne(), set_control_4_velo::s_set_control_4_velo(), and set_surface_group_types::set_surf_group_types_vector().
set_bc_group_types_sph_center()
subroutine set_node_group_types::set_bc_group_types_sph_center (character (len=kchara), intent(in) bc_type_ctl, integer(kind = kint), intent(inout) ibc_type)
Definition at line 240 of file set_node_group_types.f90.
References skip_comment_f::cmp_no_case(), fill_sph_center, fix_sph_center, m_boundary_condition_ids::iflag_sph_2_center, and m_boundary_condition_ids::iflag_sph_clip_center.
Referenced by set_control_4_composition::s_set_control_4_composition(), set_control_4_magne::s_set_control_4_magne(), set_control_4_temp::s_set_control_4_temp(), and set_control_4_velo::s_set_control_4_velo().
set_bc_group_types_sph_magne()
subroutine set_node_group_types::set_bc_group_types_sph_magne (character (len=kchara), intent(in) bc_type_ctl, integer(kind = kint), intent(inout) ibc_type)
Definition at line 275 of file set_node_group_types.f90.
References skip_comment_f::cmp_no_case(), m_boundary_condition_ids::iflag_insulator, m_boundary_condition_ids::iflag_pseudo_vacuum, insulator_sph, and pseudo_vacuum_sph.
Referenced by set_control_4_magne::s_set_control_4_magne().
set_bc_group_types_sph_velo()
subroutine set_node_group_types::set_bc_group_types_sph_velo (character (len=kchara), intent(in) bc_type_ctl, integer(kind = kint), intent(inout) ibc_type)
Definition at line 257 of file set_node_group_types.f90.
References skip_comment_f::cmp_no_case(), free_slip_sph, m_boundary_condition_ids::iflag_free_sph, m_boundary_condition_ids::iflag_non_slip_sph, m_boundary_condition_ids::iflag_rotatable_icore, non_slip_sph, and rot_inner_core.
Referenced by set_control_4_velo::s_set_control_4_velo().
set_bc_group_types_vector()
subroutine set_node_group_types::set_bc_group_types_vector (character (len=kchara), intent(in) bc_type_ctl, integer(kind = kint), intent(inout) ibc_type)
Definition at line 154 of file set_node_group_types.f90.
References bc_file_x, bc_file_y, bc_file_z, skip_comment_f::cmp_no_case(), evo_field_file_bc, fix_ctl_x, fix_ctl_y, fix_ctl_z, fix_file_x, fix_file_y, fix_file_z, fixed_file, fixed_file_bc, fixed_x, fixed_y, fixed_z, m_boundary_condition_ids::iflag_bc_evo_field, m_boundary_condition_ids::iflag_bc_file_s, m_boundary_condition_ids::iflag_bc_file_x, m_boundary_condition_ids::iflag_bc_file_y, m_boundary_condition_ids::iflag_bc_file_z, m_boundary_condition_ids::iflag_bc_fix_x, m_boundary_condition_ids::iflag_bc_fix_y, and m_boundary_condition_ids::iflag_bc_fix_z.
Referenced by set_control_4_magne::s_set_control_4_magne(), set_control_4_velo::s_set_control_4_velo(), and set_surface_group_types::set_surf_group_types_vector().
Variable Documentation
bc_file_x
character(len = kchara), parameter, private set_node_group_types::bc_file_x = 'file_x' private
control name for fixed x-componenet by external file
Definition at line 61 of file set_node_group_types.f90.
Referenced by set_bc_group_types_vector().
bc_file_y
character(len = kchara), parameter, private set_node_group_types::bc_file_y = 'file_y' private
control name for fixed y-componenet by external file
Definition at line 63 of file set_node_group_types.f90.
Referenced by set_bc_group_types_vector().
bc_file_z
character(len = kchara), parameter, private set_node_group_types::bc_file_z = 'file_z' private
control name for fixed z-componenet by external file
Definition at line 65 of file set_node_group_types.f90.
Referenced by set_bc_group_types_vector().
evo_field_file_bc
character(len = kchara), parameter set_node_group_types::evo_field_file_bc = 'evolved_field'
control name for evolved field by external file
Definition at line 39 of file set_node_group_types.f90.
Referenced by set_bc_group_types_scalar(), and set_bc_group_types_vector().
evo_flux_file_bc
character(len = kchara), parameter set_node_group_types::evo_flux_file_bc = 'evolved_flux'
control name for evolved flux by external file
Definition at line 42 of file set_node_group_types.f90.
Referenced by set_bc_group_types_fluxes().
fill_sph_center
character(len = kchara), parameter, private set_node_group_types::fill_sph_center = 'sph_to_center' private
control name to filling to center
Definition at line 104 of file set_node_group_types.f90.
Referenced by set_bc_group_types_sph_center().
fix_ctl_x
character(len = kchara), parameter, private set_node_group_types::fix_ctl_x = 'fix_ctl_x' private
control name for fixed x-componenet by control
Definition at line 54 of file set_node_group_types.f90.
Referenced by set_bc_group_types_vector().
fix_ctl_y
character(len = kchara), parameter, private set_node_group_types::fix_ctl_y = 'fix_ctl_y' private
control name for fixed y-componenet by control
Definition at line 56 of file set_node_group_types.f90.
Referenced by set_bc_group_types_vector().
fix_ctl_z
character(len = kchara), parameter, private set_node_group_types::fix_ctl_z = 'fix_ctl_z' private
control name for fixed z-componenet by control
Definition at line 58 of file set_node_group_types.f90.
Referenced by set_bc_group_types_vector().
fix_file_x
character(len = kchara), parameter, private set_node_group_types::fix_file_x = 'fix_file_x' private
control name for fixed x-componenet by external file
Definition at line 67 of file set_node_group_types.f90.
Referenced by set_bc_group_types_vector().
fix_file_y
character(len = kchara), parameter, private set_node_group_types::fix_file_y = 'fix_file_y' private
control name for fixed y-componenet by external file
Definition at line 69 of file set_node_group_types.f90.
Referenced by set_bc_group_types_vector().
fix_file_z
character(len = kchara), parameter, private set_node_group_types::fix_file_z = 'fix_file_z' private
control name for fixed z-componenet by external file
Definition at line 71 of file set_node_group_types.f90.
Referenced by set_bc_group_types_vector().
fix_rot_x
character(len = kchara), parameter, private set_node_group_types::fix_rot_x = 'rot_x' private
control name for fixed rotation around x-axis boundary
Definition at line 80 of file set_node_group_types.f90.
Referenced by set_bc_group_types_rotation().
fix_rot_y
character(len = kchara), parameter, private set_node_group_types::fix_rot_y = 'rot_y' private
control name for fixed rotation around y-axis boundary
Definition at line 82 of file set_node_group_types.f90.
Referenced by set_bc_group_types_rotation().
fix_rot_z
character(len = kchara), parameter, private set_node_group_types::fix_rot_z = 'rot_z' private
control name for fixed rotation around z-axis boundary
Definition at line 84 of file set_node_group_types.f90.
Referenced by set_bc_group_types_rotation().
fix_sgs_x
character(len = kchara), parameter, private set_node_group_types::fix_sgs_x = 'sgs_x' private
control name for fixed x-componenet in SGS model
Definition at line 74 of file set_node_group_types.f90.
Referenced by set_bc_group_types_sgs_vect().
fix_sgs_y
character(len = kchara), parameter, private set_node_group_types::fix_sgs_y = 'sgs_y' private
control name for fixed y-componenet in SGS model
Definition at line 76 of file set_node_group_types.f90.
Referenced by set_bc_group_types_sgs_vect().
fix_sgs_z
character(len = kchara), parameter, private set_node_group_types::fix_sgs_z = 'sgs_z' private
control name for fixed z-componenet in SGS model
Definition at line 78 of file set_node_group_types.f90.
Referenced by set_bc_group_types_sgs_vect().
fix_sph_center
character(len = kchara), parameter, private set_node_group_types::fix_sph_center = 'fix_at_center' private
control name to filling to center
Definition at line 107 of file set_node_group_types.f90.
Referenced by set_bc_group_types_sph_center().
fixed_bc
character(len = kchara), parameter, private set_node_group_types::fixed_bc = 'fixed' private
control name for fixed field by control
Definition at line 30 of file set_node_group_types.f90.
Referenced by set_bc_group_types_scalar().
fixed_ctl_bc
character(len = kchara), parameter, private set_node_group_types::fixed_ctl_bc = 'fixed_ctl' private
control name for fixed field by control
Definition at line 32 of file set_node_group_types.f90.
Referenced by set_bc_group_types_scalar().
fixed_file
character(len = kchara), parameter, private set_node_group_types::fixed_file = 'file' private
control name for fixed field by external file
Definition at line 34 of file set_node_group_types.f90.
Referenced by set_bc_group_types_scalar(), and set_bc_group_types_vector().
fixed_file_bc
character(len = kchara), parameter, private set_node_group_types::fixed_file_bc = 'fixed_file' private
control name for fixed field by external file
Definition at line 36 of file set_node_group_types.f90.
Referenced by set_bc_group_types_scalar(), and set_bc_group_types_vector().
fixed_sgs
character(len = kchara), parameter, private set_node_group_types::fixed_sgs = 'sgs' private
control name for fixed field in SGS model
Definition at line 45 of file set_node_group_types.f90.
Referenced by set_bc_group_types_sgs_scalar().
fixed_x
character(len = kchara), parameter, private set_node_group_types::fixed_x = 'fix_x' private
control name for fixed x-componenet by control
Definition at line 48 of file set_node_group_types.f90.
Referenced by set_bc_group_types_vector().
fixed_y
character(len = kchara), parameter, private set_node_group_types::fixed_y = 'fix_y' private
control name for fixed y-componenet by control
Definition at line 50 of file set_node_group_types.f90.
Referenced by set_bc_group_types_vector().
fixed_z
character(len = kchara), parameter, private set_node_group_types::fixed_z = 'fix_z' private
control name for fixed z-componenet by control
Definition at line 52 of file set_node_group_types.f90.
Referenced by set_bc_group_types_vector().
flux_bc
character(len = kchara), parameter, private set_node_group_types::flux_bc = 'fixed_flux' private
control name for fixed flux by control
Definition at line 111 of file set_node_group_types.f90.
Referenced by set_bc_group_types_fluxes().
flux_file_bc
character(len = kchara), parameter, private set_node_group_types::flux_file_bc = 'fixed_flux_file' private
control name for fixed flux by external file
Definition at line 113 of file set_node_group_types.f90.
Referenced by set_bc_group_types_fluxes().
free_slip_sph
character(len = kchara), parameter, private set_node_group_types::free_slip_sph = 'free_slip_sph' private
control name for free slip boundary for spherical shell
Definition at line 87 of file set_node_group_types.f90.
Referenced by set_bc_group_types_sph_velo().
insulator_sph
character(len = kchara), parameter set_node_group_types::insulator_sph = 'insulator'
control name for insulated for spherical shell
Definition at line 97 of file set_node_group_types.f90.
Referenced by set_bc_group_types_sph_magne().
non_slip_sph
character(len = kchara), parameter, private set_node_group_types::non_slip_sph = 'non_slip_sph' private
control name for non-slip boundary for spherical shell
Definition at line 90 of file set_node_group_types.f90.
Referenced by set_bc_group_types_sph_velo().
pseudo_vacuum_sph
character(len = kchara), parameter set_node_group_types::pseudo_vacuum_sph = 'pseudo_vacuum'
control name for psuedo vacuum for spherical shell
Definition at line 100 of file set_node_group_types.f90.
Referenced by set_bc_group_types_sph_magne().
rot_inner_core
character(len = kchara), parameter, private set_node_group_types::rot_inner_core = 'rot_inner_core' private
control name for rotetable inner core for spherical shell
Definition at line 93 of file set_node_group_types.f90.
Referenced by set_bc_group_types_sph_velo().