CALYPSO: set_nnod_4_ele_by_type Module Reference
set_nnod_4_ele_by_type Module Reference
Set Number of element from element type ID.
Functions/Subroutines
subroutine set_3d_nnod_4_ele_by_type (itype, nnod_4_ele, nnod_4_surf, nnod_4_edge)
integer(kind=kint) function set_nnod_4_ele_by_eletype (itype)
subroutine set_3d_nnod_4_sfed_by_ele (nnod_4_ele, nnod_4_surf, nnod_4_edge)
subroutine s_set_nnod_4_ele_by_type (itype, nnod_4_ele)
integer(kind=kint) function set_cube_eletype_from_num (nnod_4_ele)
integer(kind=kint) function linear_eletype_from_num (nnod_4_ele)
Detailed Description
Set Number of element from element type ID.
      subroutine set_3D_nnod_4_ele_by_type(itype,                     &
     &          nnod_4_ele, nnod_4_surf, nnod_4_edge)
      integer(kind = kint) function set_nnod_4_ele_by_eletype(itype)
      subroutine set_3D_nnod_4_sfed_by_ele                            &
     &         (nnod_4_ele, nnod_4_surf, nnod_4_edge)
      subroutine set_3D_nnod_4_sfed_by_ele,                           &
     &         (nnod_4_ele, nnod_4_surf, nnod_4_edge)
      subroutine s_set_nnod_4_ele_by_type(itype, nnod_4_ele)
      integer(kind = kint) function                                   &
     &              set_cube_eletype_from_num(nnod_4_ele)
      integer(kind = kint) function                                   &
     &              linear_eletype_from_num(nnod_4_ele)
Function/Subroutine Documentation
linear_eletype_from_num()
integer(kind = kint) function set_nnod_4_ele_by_type::linear_eletype_from_num (integer(kind = kint), intent(in) nnod_4_ele)
Definition at line 195 of file set_nnod_4_ele_by_type.f90.
References m_geometry_constants::num_linear_edge, m_geometry_constants::num_linear_sf, m_geometry_constants::num_t_linear, and m_geometry_constants::num_triangle.
Referenced by gz_ucd_file_mpi_io::gz_mpi_write_ucd_mesh_data_b(), and ucd_file_mpi_io::write_ucd_mesh_data_mpi_b().
s_set_nnod_4_ele_by_type()
subroutine set_nnod_4_ele_by_type::s_set_nnod_4_ele_by_type (integer(kind = kint), intent(in) itype, integer(kind = kint), intent(inout) nnod_4_ele)
Definition at line 103 of file set_nnod_4_ele_by_type.f90.
References m_geometry_constants::num_lag_sf, m_geometry_constants::num_linear_edge, m_geometry_constants::num_linear_sf, m_geometry_constants::num_quad_edge, m_geometry_constants::num_quad_sf, m_geometry_constants::num_t_lag, m_geometry_constants::num_t_linear, and m_geometry_constants::num_t_quad.
Referenced by gz_mpi_element_connect_io_b::gz_mpi_read_ele_info_b(), gz_mpi_element_connect_io::gz_mpi_read_element_info(), gz_element_connect_io::gz_read_element_info(), gz_element_connect_io_b::gz_read_element_info_b(), mpi_element_connect_io::mpi_read_element_info(), mpi_element_connect_io_b::mpi_read_element_info_b(), element_connect_io::read_element_info(), and element_connect_io_b::read_element_info_b().
set_3d_nnod_4_ele_by_type()
subroutine set_nnod_4_ele_by_type::set_3d_nnod_4_ele_by_type (integer(kind = kint), intent(in) itype, integer(kind = kint), intent(inout) nnod_4_ele, integer(kind = kint), intent(inout) nnod_4_surf, integer(kind = kint), intent(inout) nnod_4_edge)
Definition at line 37 of file set_nnod_4_ele_by_type.f90.
References set_3d_nnod_4_sfed_by_ele(), and set_nnod_4_ele_by_eletype().
set_3d_nnod_4_sfed_by_ele()
subroutine set_nnod_4_ele_by_type::set_3d_nnod_4_sfed_by_ele (integer(kind = kint), intent(in) nnod_4_ele, integer(kind = kint), intent(inout) nnod_4_surf, integer(kind = kint), intent(inout) nnod_4_edge)
Definition at line 77 of file set_nnod_4_ele_by_type.f90.
References m_geometry_constants::num_lag_sf, m_geometry_constants::num_linear_edge, m_geometry_constants::num_linear_sf, m_geometry_constants::num_quad_edge, m_geometry_constants::num_quad_sf, m_geometry_constants::num_t_lag, m_geometry_constants::num_t_linear, and m_geometry_constants::num_t_quad.
Referenced by load_mesh_data::input_mesh(), set_fem_mesh_4_sph::s_const_fem_mesh_for_sph(), set_3d_nnod_4_ele_by_type(), load_mesh_data::set_mesh(), copy_mesh_structures::set_mesh_data_from_type(), and load_mesh_data::set_zero_mesh_data().
set_cube_eletype_from_num()
integer(kind = kint) function set_nnod_4_ele_by_type::set_cube_eletype_from_num (integer(kind = kint), intent(in) nnod_4_ele)
Definition at line 173 of file set_nnod_4_ele_by_type.f90.
References m_geometry_constants::num_t_lag, m_geometry_constants::num_t_linear, and m_geometry_constants::num_t_quad.
Referenced by t_check_and_make_sph_mesh::load_fem_mesh_4_sph().
set_nnod_4_ele_by_eletype()
integer(kind = kint) function set_nnod_4_ele_by_type::set_nnod_4_ele_by_eletype (integer(kind = kint), intent(in) itype)
Definition at line 56 of file set_nnod_4_ele_by_type.f90.
References m_geometry_constants::num_t_lag, m_geometry_constants::num_t_linear, and m_geometry_constants::num_t_quad.
Referenced by set_element_data_4_io::copy_ele_connect_from_io(), copy_mesh_structures::copy_element_connect_types(), and set_3d_nnod_4_ele_by_type().