CALYPSO: m_intersection_data_0 Module Reference
m_intersection_data_0 Module Reference
Variables
integer(kind=kint), parameter nkind_etype_0 = 2
integer(kind=kint), dimension(2), parameter iflag_psf_etype_0 = (/0, 255/)
integer(kind=kint), parameter num_triangle_0 = 0
integer(kind=kint), parameter num_patch_0 = 0
integer(kind=kint), dimension(1, 1), parameter iedge_4_patch_0 = reshape((/0/), shape=(/1,1/))
Variable Documentation
iedge_4_patch_0
integer(kind = kint), dimension(1,1), parameter m_intersection_data_0::iedge_4_patch_0 = reshape((/0/), shape=(/1,1/))
Definition at line 25 of file m_intersection_data_0.f90.
iflag_psf_etype_0
integer(kind = kint), dimension(2), parameter m_intersection_data_0::iflag_psf_etype_0 = (/0, 255/)
Definition at line 19 of file m_intersection_data_0.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
nkind_etype_0
integer(kind = kint), parameter m_intersection_data_0::nkind_etype_0 = 2
Definition at line 18 of file m_intersection_data_0.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
num_patch_0
integer(kind = kint), parameter m_intersection_data_0::num_patch_0 = 0
Definition at line 23 of file m_intersection_data_0.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
num_triangle_0
integer(kind = kint), parameter m_intersection_data_0::num_triangle_0 = 0
Definition at line 22 of file m_intersection_data_0.f90.