CALYPSO: t_ctl_data_termal_norm Module Reference
t_ctl_data_termal_norm Module Reference
Thermal equation parameters to read.
Data Types
type heat_equation_control
Structure for coefficients of heat and composition equation.
Functions/Subroutines
subroutine read_thermal_ctl (id_control, hd_block, heat_ctl, c_buf)
subroutine read_composition_eq_ctl (id_control, hd_block, comp_ctl, c_buf)
subroutine bcast_thermal_ctl (heat_ctl)
subroutine dealloc_thermal_ctl (heat_ctl)
Variables
character(len=kchara), private hd_n_thermal = 'coef_4_termal_ctl'
character(len=kchara), private hd_n_t_diff = 'coef_4_t_diffuse_ctl'
character(len=kchara), private hd_n_h_src = 'coef_4_heat_source_ctl'
character(len=kchara), parameter, private hd_n_dscalar = 'coef_4_composition_ctl'
character(len=kchara), parameter, private hd_n_dsc_diff = 'coef_4_c_diffuse_ctl'
character(len=kchara), parameter, private hd_n_dsc_src = 'coef_4_light_source_ctl'
Detailed Description
Thermal equation parameters to read.
      subroutine read_thermal_ctl                                     &
     &         (id_control, hd_block, heat_ctl, c_buf)
      subroutine read_composition_eq_ctl                              &
     &         (id_control, hd_block, comp_ctl, c_buf)
      subroutine bcast_thermal_ctl(heat_ctl)
      subroutine dealloc_thermal_ctl(heat_ctl)
        type(heat_equation_control), intent(inout) :: heat_ctl
        type(heat_equation_control), intent(inout) :: comp_ctl
   --------------------------------------------------------------------
 example of control block
      begin thermal
        array coef_4_termal_ctl     1
          coef_4_termal_ctl            One                   1.0
        end array coef_4_termal_ctl
        array coef_4_t_diffuse_ctl  1
          coef_4_t_diffuse_ctl         Prandtl_number       -1.0
        end array coef_4_t_diffuse_ctl
        array coef_4_heat_source_ctl  1
          coef_4_heat_source_ctl       One                   1.0
        end array coef_4_heat_source_ctl
      end  thermal
   --------------------------------------------------------------------
   --------------------------------------------------------------------
 example of control block
     begin composition
        array coef_4_composition_ctl     1
          coef_4_composition_ctl           One       1.0
        end array coef_4_composition_ctl
        array coef_4_c_diffuse_ctl  1
          coef_4_c_diffuse_ctl    Composite_Prandtl_number  -1.0
        end array coef_4_c_diffuse_ctl
        array coef_4_light_source_ctl  1
          coef_4_light_source_ctl     One                    1.0
        end array coef_4_light_source_ctl
      end  composition
   --------------------------------------------------------------------
Function/Subroutine Documentation
bcast_thermal_ctl()
subroutine t_ctl_data_termal_norm::bcast_thermal_ctl (type(heat_equation_control), intent(inout) heat_ctl)
Definition at line 177 of file t_ctl_data_termal_norm.f90.
References bcast_control_arrays::bcast_ctl_array_cr(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by t_ctl_data_mhd_normalize::bcast_coef_term_ctl().
dealloc_thermal_ctl()
subroutine t_ctl_data_termal_norm::dealloc_thermal_ctl (type(heat_equation_control), intent(inout) heat_ctl)
Definition at line 195 of file t_ctl_data_termal_norm.f90.
References t_control_array_charareal::dealloc_control_array_c_r().
Referenced by t_ctl_data_mhd_normalize::dealloc_coef_term_ctl().
read_composition_eq_ctl()
subroutine t_ctl_data_termal_norm::read_composition_eq_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(heat_equation_control), intent(inout) comp_ctl, type(buffer_for_control), intent(inout) c_buf)
Definition at line 144 of file t_ctl_data_termal_norm.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_n_dsc_diff, hd_n_dsc_src, hd_n_dscalar, t_read_control_elements::load_one_line_from_control(), and t_control_array_charareal::read_control_array_c_r().
Referenced by t_ctl_data_mhd_normalize::read_coef_term_ctl().
read_thermal_ctl()
subroutine t_ctl_data_termal_norm::read_thermal_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(heat_equation_control), intent(inout) heat_ctl, type(buffer_for_control), intent(inout) c_buf)
Definition at line 112 of file t_ctl_data_termal_norm.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_n_h_src, hd_n_t_diff, hd_n_thermal, t_read_control_elements::load_one_line_from_control(), and t_control_array_charareal::read_control_array_c_r().
Referenced by t_ctl_data_mhd_normalize::read_coef_term_ctl().
Variable Documentation
hd_n_dsc_diff
character(len=kchara), parameter, private t_ctl_data_termal_norm::hd_n_dsc_diff = 'coef_4_c_diffuse_ctl' private
Definition at line 98 of file t_ctl_data_termal_norm.f90.
Referenced by read_composition_eq_ctl().
hd_n_dsc_src
character(len=kchara), parameter, private t_ctl_data_termal_norm::hd_n_dsc_src = 'coef_4_light_source_ctl' private
Definition at line 100 of file t_ctl_data_termal_norm.f90.
Referenced by read_composition_eq_ctl().
hd_n_dscalar
character(len=kchara), parameter, private t_ctl_data_termal_norm::hd_n_dscalar = 'coef_4_composition_ctl' private
Definition at line 96 of file t_ctl_data_termal_norm.f90.
Referenced by read_composition_eq_ctl().
hd_n_h_src
character(len=kchara), private t_ctl_data_termal_norm::hd_n_h_src = 'coef_4_heat_source_ctl' private
Definition at line 92 of file t_ctl_data_termal_norm.f90.
Referenced by read_thermal_ctl().
hd_n_t_diff
character(len=kchara), private t_ctl_data_termal_norm::hd_n_t_diff = 'coef_4_t_diffuse_ctl' private
Definition at line 91 of file t_ctl_data_termal_norm.f90.
Referenced by read_thermal_ctl().
hd_n_thermal
character(len=kchara), private t_ctl_data_termal_norm::hd_n_thermal = 'coef_4_termal_ctl' private
Definition at line 90 of file t_ctl_data_termal_norm.f90.
Referenced by read_thermal_ctl().