CALYPSO: t_work_time Module Reference
t_work_time Module Reference
routines to count elapsed time
Data Types
type elapsed_time_data
Functions/Subroutines
subroutine alloc_elapsed_timer (elps)
subroutine append_elapsed_timer (num_append, iend_org, iend_new, elps)
subroutine dealloc_elapsed_timer (elps)
subroutine start_elapsed_timer (iflag_elps, elps)
subroutine end_elapsed_timer (iflag_elps, elps)
subroutine reset_elapsed_timer (istart, iend, elps)
subroutine output_elapsed_log (iflag_time_4_each_pe, time_file_prefix, elps)
Variables
integer(kind=kint), parameter, private id_timer_file = 13
Detailed Description
routines to count elapsed time
      subroutine alloc_elapsed_timer(elps)
      subroutine append_elapsed_timer                                 &
     &         (num_append, iend_org, iend_new, elps)
      subroutine dealloc_elapsed_timer(elps)
      subroutine start_elapsed_timer(iflag_elps, elps)
      subroutine end_elapsed_timer(iflag_elps, elps)
      subroutine reset_elapsed_timer(istart, iend, elps)
      subroutine output_elapsed_log                                   &
     &         (iflag_time_4_each_pe, time_file_prefix, elps)
        type(elapsed_time_data), intent(inout) :: elps
@params timer ID
Function/Subroutine Documentation
alloc_elapsed_timer()
subroutine t_work_time::alloc_elapsed_timer (type(elapsed_time_data), intent(inout) elps)
Definition at line 61 of file t_work_time.f90.
References m_constants::zero.
Referenced by m_work_time::allocate_elapsed_times(), and append_elapsed_timer().
append_elapsed_timer()
subroutine t_work_time::append_elapsed_timer (integer(kind = kint), intent(in) num_append, integer(kind = kint), intent(inout) iend_org, integer(kind = kint), intent(inout) iend_new, type(elapsed_time_data), intent(inout) elps)
Definition at line 84 of file t_work_time.f90.
References alloc_elapsed_timer(), and dealloc_elapsed_timer().
Referenced by m_work_time::append_elapsed_times().
dealloc_elapsed_timer()
subroutine t_work_time::dealloc_elapsed_timer (type(elapsed_time_data), intent(inout) elps)
Definition at line 112 of file t_work_time.f90.
Referenced by append_elapsed_timer(), and m_work_time::deallocate_elapsed_times().
end_elapsed_timer()
subroutine t_work_time::end_elapsed_timer (integer(kind = kint), intent(in) iflag_elps, type(elapsed_time_data), intent(inout) elps)
Definition at line 143 of file t_work_time.f90.
Referenced by m_work_time::end_elapsed_time().
output_elapsed_log()
subroutine t_work_time::output_elapsed_log (integer(kind = kint), intent(in) iflag_time_4_each_pe, character(len=kchara), intent(in) time_file_prefix, type(elapsed_time_data), intent(inout) elps)
Definition at line 173 of file t_work_time.f90.
References set_parallel_file_name::add_dat_extension(), set_parallel_file_name::add_process_id(), calypso_mpi_real::calypso_mpi_reduce_real(), id_timer_file, calypso_mpi::my_rank, calypso_mpi::nprocs, and m_constants::zero.
Referenced by m_work_time::output_elapsed_times().
reset_elapsed_timer()
subroutine t_work_time::reset_elapsed_timer (integer(kind = kint), intent(in) istart, integer(kind = kint), intent(in) iend, type(elapsed_time_data), intent(inout) elps)
Definition at line 160 of file t_work_time.f90.
References m_constants::zero.
Referenced by m_work_time::reset_elapsed_times().
start_elapsed_timer()
subroutine t_work_time::start_elapsed_timer (integer(kind = kint), intent(in) iflag_elps, type(elapsed_time_data), intent(inout) elps)
Definition at line 127 of file t_work_time.f90.
Referenced by m_work_time::start_elapsed_time().
Variable Documentation
id_timer_file
integer(kind = kint), parameter, private t_work_time::id_timer_file = 13 private
Definition at line 34 of file t_work_time.f90.
Referenced by output_elapsed_log().