CALYPSO: init_fft_4_mhd Module Reference
init_fft_4_mhd Module Reference
Select Fourier transform routine by elapsed time.
Functions/Subroutines
subroutine init_fourier_transform_4_mhd (sph_rtp, comm_rtp, trns_MHD, WK_FFTs, iflag_FFT_MHD)
integer(kind=kint) function set_fft_mode_4_snapshot (iflag_FFT_MHD)
subroutine, private compare_fft_4_mhd (sph_rtp, comm_rtp, n_WS, n_WR, WS, WR, trns_MHD, WK_FFTs)
subroutine, private test_fourier_trans_4_mhd (iflag_FFT, sph_rtp, comm_rtp, n_WS, n_WR, WS, WR, trns_MHD, WK_FFTs, etime_fft)
Variables
integer(kind=kint), parameter num_test = 4
integer(kind=kint), dimension(num_test), parameter list_test = (/iflag_FFTPACK, iflag_FFTPACK_COMPONENT, iflag_FFTPACK_DOMAIN, iflag_FFTPACK_SINGLE/)
real(kind=kreal), private etime_shortest = -1.0e10
integer(kind=kint), private iflag_selected
Detailed Description
Select Fourier transform routine by elapsed time.
      subroutine init_fourier_transform_4_MHD                         &
     &         (sph_rtp, comm_rtp, trns_MHD, WK_FFTs, iflag_FFT_MHD)
      integer(kind = kint) function                                   &
     &                    set_FFT_mode_4_snapshot(iflag_FFT_MHD)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_comm_tbl), intent(in) :: comm_rtp
        type(address_4_sph_trans), intent(inout) :: trns_MHD
        type(work_for_FFTs), intent(inout) :: WK_FFTs
       Current problem
      FFTW crashes when both single and multi transforms are
      comparaed
Function/Subroutine Documentation
compare_fft_4_mhd()
subroutine, private init_fft_4_mhd::compare_fft_4_mhd (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, integer(kind = kint), intent(in) n_WS, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_ws), intent(inout) WS, real (kind=kreal), dimension(n_wr), intent(inout) WR, type(address_4_sph_trans), intent(inout) trns_MHD, type(work_for_ffts), intent(inout) WK_FFTs) private
Definition at line 124 of file init_FFT_4_MHD.F90.
References etime_shortest, iflag_selected, list_test, num_test, and test_fourier_trans_4_mhd().
Referenced by init_fourier_transform_4_mhd().
init_fourier_transform_4_mhd()
subroutine init_fft_4_mhd::init_fourier_transform_4_mhd (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, type(address_4_sph_trans), intent(inout) trns_MHD, type(work_for_ffts), intent(inout) WK_FFTs, integer(kind = kint), intent(inout) iflag_FFT_MHD)
Definition at line 72 of file init_FFT_4_MHD.F90.
References m_fft_selector::chosen_fft_name(), compare_fft_4_mhd(), iflag_selected, m_fft_selector::iflag_undefined_fft, t_sph_fft_selector::init_sph_fft_select(), calypso_mpi::my_rank, and m_solver_sr::sr_r1.
Referenced by init_sphrical_transform_mhd::init_leg_fourier_trans_mhd().
set_fft_mode_4_snapshot()
integer(kind = kint) function init_fft_4_mhd::set_fft_mode_4_snapshot (integer(kind = kint), intent(in) iflag_FFT_MHD)
Definition at line 104 of file init_FFT_4_MHD.F90.
References m_fft_selector::iflag_fftw, m_fft_selector::iflag_fftw_component, m_fft_selector::iflag_fftw_domain, and m_fft_selector::iflag_fftw_single.
Referenced by init_sphrical_transform_mhd::init_leg_fourier_trans_mhd().
test_fourier_trans_4_mhd()
subroutine, private init_fft_4_mhd::test_fourier_trans_4_mhd (integer(kind = kint), intent(in) iflag_FFT, type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, integer(kind = kint), intent(in) n_WS, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_ws), intent(inout) WS, real (kind=kreal), dimension(n_wr), intent(inout) WR, type(address_4_sph_trans), intent(inout) trns_MHD, type(work_for_ffts), intent(inout) WK_FFTs, real(kind = kreal), intent(inout) etime_fft) private
Definition at line 158 of file init_FFT_4_MHD.F90.
References t_sph_fft_selector::back_fft_select_from_recv(), calypso_mpi::calypso_comm, calypso_mpi::calypso_real, t_sph_fft_selector::finalize_sph_fft_select(), t_sph_fft_selector::fwd_fft_select_to_send(), calypso_mpi::ierr_mpi, t_sph_fft_selector::init_sph_fft_select(), calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by compare_fft_4_mhd().
Variable Documentation
etime_shortest
real(kind = kreal), private init_fft_4_mhd::etime_shortest = -1.0e10 private
Definition at line 60 of file init_FFT_4_MHD.F90.
Referenced by compare_fft_4_mhd().
iflag_selected
integer(kind = kint), private init_fft_4_mhd::iflag_selected private
Definition at line 61 of file init_FFT_4_MHD.F90.
Referenced by compare_fft_4_mhd(), and init_fourier_transform_4_mhd().
list_test
integer(kind = kint), dimension(num_test), parameter init_fft_4_mhd::list_test = (/iflag_FFTPACK, iflag_FFTPACK_COMPONENT, iflag_FFTPACK_DOMAIN, iflag_FFTPACK_SINGLE/)
Definition at line 53 of file init_FFT_4_MHD.F90.
Referenced by compare_fft_4_mhd().
num_test
integer(kind = kint), parameter init_fft_4_mhd::num_test = 4
Definition at line 52 of file init_FFT_4_MHD.F90.
Referenced by compare_fft_4_mhd().