CALYPSO: bcast_4_sph_monitor_ctl Module Reference
bcast_4_sph_monitor_ctl Module Reference
Control data for spectr data monitoring.
Functions/Subroutines
subroutine bcast_sph_monitoring_ctl (smonitor_ctl)
subroutine, private bcast_pickup_spectr_ctl (pspec_ctl)
subroutine, private bcast_gauss_spectr_ctl (g_pwr)
subroutine, private bcast_each_vol_spectr_ctl (num_vspec_ctl, v_pwr)
subroutine, private bcast_layerd_spectr_ctl (lp_ctl)
subroutine, private bcast_mid_eq_monitor_ctl (meq_ctl)
Detailed Description
Control data for spectr data monitoring.
      subroutine bcast_sph_monitoring_ctl(smonitor_ctl)
        type(sph_monitor_control), intent(inout) :: smonitor_ctl
Function/Subroutine Documentation
bcast_each_vol_spectr_ctl()
subroutine, private bcast_4_sph_monitor_ctl::bcast_each_vol_spectr_ctl (integer(kind = kint), intent(in) num_vspec_ctl, type(volume_spectr_control), dimension(num_vspec_ctl), intent(inout) v_pwr) private
Definition at line 111 of file bcast_4_sph_monitor_ctl.f90.
References bcast_control_arrays::bcast_ctl_type_c1(), and bcast_control_arrays::bcast_ctl_type_r1().
Referenced by bcast_sph_monitoring_ctl().
bcast_gauss_spectr_ctl()
subroutine, private bcast_4_sph_monitor_ctl::bcast_gauss_spectr_ctl (type(gauss_spectr_control), intent(inout) g_pwr) private
Definition at line 94 of file bcast_4_sph_monitor_ctl.f90.
References bcast_control_arrays::bcast_ctl_array_i1(), bcast_control_arrays::bcast_ctl_array_i2(), bcast_control_arrays::bcast_ctl_type_c1(), and bcast_control_arrays::bcast_ctl_type_r1().
Referenced by bcast_sph_monitoring_ctl().
bcast_layerd_spectr_ctl()
subroutine, private bcast_4_sph_monitor_ctl::bcast_layerd_spectr_ctl (type(layerd_spectr_control), intent(inout) lp_ctl) private
Definition at line 130 of file bcast_4_sph_monitor_ctl.f90.
References bcast_control_arrays::bcast_ctl_array_i1(), and bcast_control_arrays::bcast_ctl_type_c1().
Referenced by bcast_sph_monitoring_ctl().
bcast_mid_eq_monitor_ctl()
subroutine, private bcast_4_sph_monitor_ctl::bcast_mid_eq_monitor_ctl (type(mid_equator_control), intent(inout) meq_ctl) private
Definition at line 149 of file bcast_4_sph_monitor_ctl.f90.
References bcast_control_arrays::bcast_ctl_type_c1(), bcast_control_arrays::bcast_ctl_type_i1(), and bcast_control_arrays::bcast_ctl_type_r1().
Referenced by bcast_sph_monitoring_ctl().
bcast_pickup_spectr_ctl()
subroutine, private bcast_4_sph_monitor_ctl::bcast_pickup_spectr_ctl (type(pick_spectr_control), intent(inout) pspec_ctl) private
Definition at line 77 of file bcast_4_sph_monitor_ctl.f90.
References bcast_control_arrays::bcast_ctl_array_i1(), bcast_control_arrays::bcast_ctl_array_i2(), and bcast_control_arrays::bcast_ctl_type_c1().
Referenced by bcast_sph_monitoring_ctl().
bcast_sph_monitoring_ctl()
subroutine bcast_4_sph_monitor_ctl::bcast_sph_monitoring_ctl (type(sph_monitor_control), intent(inout) smonitor_ctl)
Definition at line 37 of file bcast_4_sph_monitor_ctl.f90.
References bcast_control_arrays::bcast_ctl_type_c1(), bcast_each_vol_spectr_ctl(), bcast_gauss_spectr_ctl(), bcast_layerd_spectr_ctl(), bcast_mid_eq_monitor_ctl(), bcast_pickup_spectr_ctl(), calypso_mpi_int::calypso_mpi_bcast_one_int(), and calypso_mpi::my_rank.
Referenced by t_ctl_data_mhd::bcast_sph_mhd_ctl_data().