CALYPSO: t_control_array_real3 Module Reference
t_control_array_real3 Module Reference
Data Types
type ctl_array_r3
Structure for three reals control array.
type read_real3_item
structure of control item with three reals
Functions/Subroutines
subroutine read_real3_ctl_type (c_buf, label, real3_item)
subroutine write_real3_ctl_type (id_file, level, label, real3_item)
subroutine copy_real3_ctl (org_r3, new_r3)
subroutine alloc_control_array_r3 (array_r3)
subroutine dealloc_control_array_r3 (array_r3)
subroutine read_control_array_r3 (id_control, label, array_r3, c_buf)
subroutine write_control_array_r3 (id_control, level, label, array_r3)
subroutine append_control_array_r3 (read_r3, array_r3)
subroutine dup_control_array_r3 (org_r3, tgt_r3)
subroutine copy_control_array_r3 (num_copy, org_r3, tgt_r3)
subroutine append_control_item_r3 (read_r3, array_r3)
Function/Subroutine Documentation
alloc_control_array_r3()
subroutine t_control_array_real3::alloc_control_array_r3 (type(ctl_array_r3), intent(inout) array_r3)
Definition at line 135 of file t_control_array_real3.f90.
Referenced by append_control_array_r3(), bcast_control_arrays::bcast_ctl_array_r3(), dup_control_array_r3(), and read_control_array_r3().
append_control_array_r3()
subroutine t_control_array_real3::append_control_array_r3 (type(read_real3_item), intent(inout) read_r3, type(ctl_array_r3), intent(inout) array_r3)
Definition at line 230 of file t_control_array_real3.f90.
References alloc_control_array_r3(), append_control_item_r3(), copy_control_array_r3(), and dealloc_control_array_r3().
Referenced by read_control_array_r3().
append_control_item_r3()
subroutine t_control_array_real3::append_control_item_r3 (type(read_real3_item), intent(in) read_r3, type(ctl_array_r3), intent(inout) array_r3)
Definition at line 286 of file t_control_array_real3.f90.
Referenced by append_control_array_r3().
copy_control_array_r3()
subroutine t_control_array_real3::copy_control_array_r3 (integer(kind = kint), intent(in) num_copy, type(ctl_array_r3), intent(in) org_r3, type(ctl_array_r3), intent(inout) tgt_r3)
Definition at line 269 of file t_control_array_real3.f90.
Referenced by append_control_array_r3(), and dup_control_array_r3().
copy_real3_ctl()
subroutine t_control_array_real3::copy_real3_ctl (type(read_real3_item), intent(in) org_r3, type(read_real3_item), intent(inout) new_r3)
Definition at line 121 of file t_control_array_real3.f90.
dealloc_control_array_r3()
subroutine t_control_array_real3::dealloc_control_array_r3 (type(ctl_array_r3), intent(inout) array_r3)
Definition at line 153 of file t_control_array_real3.f90.
Referenced by append_control_array_r3(), and t_ctl_data_node_monitor::dealloc_monitor_data_ctl().
dup_control_array_r3()
subroutine t_control_array_real3::dup_control_array_r3 (type(ctl_array_r3), intent(in) org_r3, type(ctl_array_r3), intent(inout) tgt_r3)
Definition at line 255 of file t_control_array_real3.f90.
References alloc_control_array_r3(), and copy_control_array_r3().
read_control_array_r3()
subroutine t_control_array_real3::read_control_array_r3 (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) label, type(ctl_array_r3), intent(inout) array_r3, type(buffer_for_control), intent(inout) c_buf)
Definition at line 167 of file t_control_array_real3.f90.
References alloc_control_array_r3(), append_control_array_r3(), t_read_control_elements::check_array_flag(), t_read_control_elements::check_end_array_flag(), t_read_control_elements::load_one_line_from_control(), and read_real3_ctl_type().
Referenced by t_ctl_data_node_monitor::read_monitor_data_ctl().
read_real3_ctl_type()
subroutine t_control_array_real3::read_real3_ctl_type (type(buffer_for_control), intent(in) c_buf, character(len=kchara), intent(in) label, type(read_real3_item), intent(inout) real3_item)
Definition at line 80 of file t_control_array_real3.f90.
References m_machine_parameter::iflag_debug.
Referenced by read_control_array_r3().
write_control_array_r3()
subroutine t_control_array_real3::write_control_array_r3 (integer(kind = kint), intent(in) id_control, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, type(ctl_array_r3), intent(in) array_r3)
Definition at line 201 of file t_control_array_real3.f90.
References write_control_elements::write_array_flag_for_ctl(), write_control_elements::write_end_array_flag_for_ctl(), and write_control_elements::write_real3_ctl_item().
write_real3_ctl_type()
subroutine t_control_array_real3::write_real3_ctl_type (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, type(read_real3_item), intent(in) real3_item)
Definition at line 102 of file t_control_array_real3.f90.
References write_control_elements::write_real3_ctl_item().