CALYPSO: t_picked_sph_spectr_data_io Module Reference
t_picked_sph_spectr_data_io Module Reference
Data arrays to monitoring spectrum data.
Data Types
type picked_spectrum_data_io
Functions/Subroutines
subroutine dealloc_pick_sph_monitor_io (picked_IO)
subroutine write_tave_sph_spec_monitor (file_prefix, i_step, time, true_start, picked_IO)
subroutine open_sph_spec_read (id_pick, file_prefix, picked_IO)
subroutine read_sph_spec_monitor (id_pick, i_step, time, picked_IO, ierr)
subroutine, private alloc_pick_sph_monitor_io (picked_IO)
Variables
integer(kind=kint), parameter id_pick_mode = 22
File ID for spectrum monitor file.
Detailed Description
Data arrays to monitoring spectrum data.
      subroutine dealloc_pick_sph_monitor_IO(picked_IO)
      subroutine write_tave_sph_spec_monitor                          &
     &         (file_prefix, i_step, time, true_start, picked_IO)
      subroutine open_sph_spec_read(id_pick, file_prefix, picked_IO)
      subroutine read_sph_spec_monitor                                &
     &         (id_pick, i_step, time, picked_IO, ierr)
Parameters
id_rank Process ID
i_step time step
time time
id_pick file ID
ierr Error flag (0:success, 1:error)
Function/Subroutine Documentation
alloc_pick_sph_monitor_io()
subroutine, private t_picked_sph_spectr_data_io::alloc_pick_sph_monitor_io (type(picked_spectrum_data_io), intent(inout) picked_IO) private
Definition at line 220 of file t_picked_sph_spectr_data_IO.f90.
Referenced by open_sph_spec_read().
dealloc_pick_sph_monitor_io()
subroutine t_picked_sph_spectr_data_io::dealloc_pick_sph_monitor_io (type(picked_spectrum_data_io), intent(inout) picked_IO)
Definition at line 65 of file t_picked_sph_spectr_data_IO.f90.
Referenced by tave_picked_sph_spec_data().
open_sph_spec_read()
subroutine t_picked_sph_spectr_data_io::open_sph_spec_read (integer(kind = kint), intent(in) id_pick, character(len = kchara), intent(in) file_prefix, type(picked_spectrum_data_io), intent(inout) picked_IO)
Definition at line 145 of file t_picked_sph_spectr_data_IO.f90.
References set_parallel_file_name::add_dat_extension(), alloc_pick_sph_monitor_io(), and skip_comment_f::skip_comment().
Referenced by tave_picked_sph_spec_data().
read_sph_spec_monitor()
subroutine t_picked_sph_spectr_data_io::read_sph_spec_monitor (integer(kind = kint), intent(in) id_pick, integer(kind = kint), intent(inout) i_step, real(kind = kreal), intent(inout) time, type(picked_spectrum_data_io), intent(inout) picked_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 186 of file t_picked_sph_spectr_data_IO.f90.
Referenced by tave_picked_sph_spec_data().
write_tave_sph_spec_monitor()
subroutine t_picked_sph_spectr_data_io::write_tave_sph_spec_monitor (character(len = kchara), intent(in) file_prefix, integer(kind = kint), intent(in) i_step, real(kind = kreal), intent(in) time, real(kind = kreal), intent(in) true_start, type(picked_spectrum_data_io), intent(in) picked_IO)
Definition at line 81 of file t_picked_sph_spectr_data_IO.f90.
References set_parallel_file_name::add_dat_extension(), m_monitor_file_labels::hd_pick_sph_head(), m_monitor_file_labels::hd_pick_sph_num(), id_pick_mode, m_constants::izero, and write_field_labels::write_multi_labels().
Referenced by tave_picked_sph_spec_data().
Variable Documentation
id_pick_mode
integer(kind = kint), parameter t_picked_sph_spectr_data_io::id_pick_mode = 22
File ID for spectrum monitor file.
Definition at line 34 of file t_picked_sph_spectr_data_IO.f90.
Referenced by write_tave_sph_spec_monitor().