CALYPSO: set_sph_node_group Module Reference
set_sph_node_group Module Reference
Functions/Subroutines
subroutine count_sph_local_node_group (sph_params, radial_rj_grp, nod_grp)
subroutine count_sph_local_node_grp_item (ip_r, ip_t, sph_params, radial_rj_grp, stbl, nod_grp)
subroutine set_sph_local_node_grp_item (ip_r, ip_t, sph_params, radial_rj_grp, stbl, nod_grp)
subroutine, private count_node_grp_on_sphere (ip_r, ip_t, knum, stbl, nitem_grp)
subroutine, private set_node_grp_item_on_sphere (ip_r, ip_t, knum, icou, stbl, nod_grp)
Function/Subroutine Documentation
count_node_grp_on_sphere()
subroutine, private set_sph_node_group::count_node_grp_on_sphere (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, integer(kind = kint), intent(in) knum, type(comm_table_make_sph), intent(in) stbl, integer(kind = kint), intent(inout) nitem_grp) private
Definition at line 212 of file set_sph_node_group.f90.
Referenced by count_sph_local_node_grp_item().
count_sph_local_node_group()
subroutine set_sph_node_group::count_sph_local_node_group (type(sph_shell_parameters), intent(in) sph_params, type(group_data), intent(in) radial_rj_grp, type(group_data), intent(inout) nod_grp)
Definition at line 36 of file set_sph_node_group.f90.
Referenced by set_fem_mesh_4_sph::const_fem_groups_for_sph().
count_sph_local_node_grp_item()
subroutine set_sph_node_group::count_sph_local_node_grp_item (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, type(sph_shell_parameters), intent(in) sph_params, type(group_data), intent(in) radial_rj_grp, type(comm_table_make_sph), intent(in) stbl, type(group_data), intent(inout) nod_grp)
Definition at line 69 of file set_sph_node_group.f90.
References count_node_grp_on_sphere().
Referenced by set_fem_mesh_4_sph::const_fem_groups_for_sph().
set_node_grp_item_on_sphere()
subroutine, private set_sph_node_group::set_node_grp_item_on_sphere (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, integer(kind = kint), intent(in) knum, integer(kind = kint), intent(in) icou, type(comm_table_make_sph), intent(in) stbl, type(group_data), intent(inout) nod_grp) private
Definition at line 240 of file set_sph_node_group.f90.
References cal_sph_node_addresses::sph_center_np_node_id(), cal_sph_node_addresses::sph_ctr_shell_node_id(), cal_sph_node_addresses::sph_n_pole_node_id(), cal_sph_node_addresses::sph_s_pole_node_id(), and cal_sph_node_addresses::sph_shell_node_id().
Referenced by set_sph_local_node_grp_item().
set_sph_local_node_grp_item()
subroutine set_sph_node_group::set_sph_local_node_grp_item (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, type(sph_shell_parameters), intent(in) sph_params, type(group_data), intent(in) radial_rj_grp, type(comm_table_make_sph), intent(in) stbl, type(group_data), intent(inout) nod_grp)
Definition at line 139 of file set_sph_node_group.f90.
References set_node_grp_item_on_sphere(), cal_sph_node_addresses::sph_center_node_id(), cal_sph_node_addresses::sph_center_np_node_id(), cal_sph_node_addresses::sph_n_pole_node_id(), and cal_sph_node_addresses::sph_s_pole_node_id().
Referenced by set_fem_mesh_4_sph::const_fem_groups_for_sph().