CALYPSO: set_bc_sph_mhd Module Reference
set_bc_sph_mhd Module Reference
Set boundary conditions for MHD dynamo simulation.
Functions/Subroutines
subroutine s_set_bc_sph_mhd (bc_IO, sph_params, sph_rj, radial_rj_grp, MHD_prop, MHD_BC, sph_MHD_bc)
subroutine, private set_sph_bc_magne_sph (bc_IO, sph_rj, radial_rj_grp, CTR_nod_grp_name, CTR_sf_grp_name, magne_nod, magne_surf, sph_bc_B, bcs_B)
Detailed Description
Set boundary conditions for MHD dynamo simulation.
      subroutine s_set_bc_sph_mhd(bc_IO, sph_params, sph_rj,          &
     &          radial_rj_grp, MHD_prop, MHD_BC, sph_MHD_bc)
        type(boundary_spectra), intent(in) :: bc_IO
        type(MHD_evolution_param), intent(in) :: MHD_prop
        type(MHD_BC_lists), intent(in) :: MHD_BC
        type(sph_shell_parameters), intent(in) :: sph_params
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(group_data), intent(in) :: radial_rj_grp
        type(sph_MHD_boundary_data), intent(inout) :: sph_MHD_bc
Function/Subroutine Documentation
s_set_bc_sph_mhd()
subroutine set_bc_sph_mhd::s_set_bc_sph_mhd (type(boundary_spectra), intent(in) bc_IO, type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(group_data), intent(in) radial_rj_grp, type(mhd_evolution_param), intent(in) MHD_prop, type(mhd_bc_lists), intent(in) MHD_BC, type(sph_mhd_boundary_data), intent(inout) sph_MHD_bc)
Definition at line 48 of file set_bc_sph_mhd.f90.
References coef_fdm2_to_center::cal_2nd_center_fix_df_fdm(), coef_fdm2_to_center::cal_2nd_center_fixed_fdm(), coef_fdm2_to_center::cal_2nd_to_center_fixed_fdm(), coef_fdm2_free_cmb::cal_fdm2_cmb_free_vp(), coef_fdm2_free_cmb::cal_fdm2_cmb_free_vt(), coef_fdm2_free_icb::cal_fdm2_icb_free_vp(), coef_fdm2_free_icb::cal_fdm2_icb_free_vt(), t_boundary_params_sph_mhd::cal_fdm_coefs_4_bcs(), coef_fdm2_free_cmb::check_coef_fdm_free_cmb(), coef_fdm2_free_icb::check_coef_fdm_free_icb(), t_boundary_params_sph_mhd::check_fdm_coefs_4_bc2(), m_base_field_labels::composition, t_spheric_parameter::ctr_nod_grp_name, t_spheric_parameter::ctr_sf_grp_name, t_physical_property::id_no_evolution, m_machine_parameter::iflag_debug, m_machine_parameter::iflag_full_msg, m_base_field_labels::magnetic_field, set_bc_sph_scalars::set_sph_bc_composition_sph(), set_sph_bc_magne_sph(), set_bc_sph_scalars::set_sph_bc_temp_sph(), set_bc_flag_sph_velo::set_sph_bc_velo_sph(), m_base_field_labels::temperature, and m_base_field_labels::velocity.
Referenced by init_radial_infos_sph_mhd::init_r_infos_sph_mhd().
set_sph_bc_magne_sph()
subroutine, private set_bc_sph_mhd::set_sph_bc_magne_sph (type(boundary_spectra), intent(in) bc_IO, type(sph_rj_grid), intent(in) sph_rj, type(group_data), intent(in) radial_rj_grp, character(len=kchara), intent(in) CTR_nod_grp_name, character(len=kchara), intent(in) CTR_sf_grp_name, type(boundary_condition_list), intent(in) magne_nod, type(boundary_condition_list), intent(in) magne_surf, type(sph_boundary_type), intent(inout) sph_bc_B, type(sph_vector_boundary_data), intent(inout) bcs_B) private
Definition at line 193 of file set_bc_sph_mhd.f90.
References t_spheric_parameter::ctr_nod_grp_name, t_spheric_parameter::ctr_sf_grp_name, set_bc_sph_scalars::find_both_sides_of_boundaries(), m_boundary_condition_ids::iflag_bc_evo_field, m_boundary_condition_ids::iflag_bc_file_s, m_boundary_condition_ids::iflag_pseudo_vacuum, t_boundary_params_sph_mhd::iflag_radial_magne, m_boundary_condition_ids::iflag_sph_2_center, m_boundary_condition_ids::iflag_sph_clip_center, t_boundary_params_sph_mhd::iflag_sph_fill_center, t_boundary_params_sph_mhd::iflag_sph_fix_center, t_boundary_params_sph_mhd::iflag_sph_insulator, m_base_field_labels::magnetic_field, set_sph_bc_data_by_file::set_evolved_vector_bc_by_file(), and set_sph_bc_data_by_file::set_fixed_vector_bc_by_file().
Referenced by s_set_bc_sph_mhd().