CALYPSO: leg_bwd_trans_on_the_fly Module Reference
leg_bwd_trans_on_the_fly Module Reference
backward Legendre transform (Blocked loop version)
Functions/Subroutines
subroutine legendre_b_trans_on_the_fly (iflag_matmul, ncomp, nvector, nscalar, sph_rlm, sph_rtm, comm_rlm, comm_rtm, leg, idx_trns, n_WR, n_WS, WR, WS, WK_l_otf)
subroutine, private leg_bwd_trans_1latitude (lp_rtm, jst, mm, mp_rlm, mn_rlm, nkrs, nkrt, iflag_matmul, ncomp, nvector, nscalar, sph_rlm, sph_rtm, comm_rlm, comm_rtm, idx_trns, leg, n_WR, n_WS, WR, WS, n_jk_e, n_jk_o, Smat, Pjt_mat, Fmat, wk_plm)
subroutine, private leg_bwd_trans_at_equator (lp_rtm, jst, mm, mp_rlm, mn_rlm, nkrs, nkrt, iflag_matmul, ncomp, nvector, nscalar, sph_rlm, sph_rtm, comm_rtm, leg, n_WS, WS, n_jk_e, n_jk_o, Smat, Pjt_mat, Fmat, wk_plm)
Variables
integer, external omp_get_max_threads
Detailed Description
backward Legendre transform (Blocked loop version)
      subroutine legendre_b_trans_on_the_fly                          &
     &         (iflag_matmul, ncomp, nvector, nscalar,                &
     &          sph_rlm, sph_rtm, comm_rlm, comm_rtm, leg, idx_trns,  &
     &          n_WR, n_WS, WR, WS, WK_l_otf)
        Input:  vr_rtm   (Order: radius,theta,phi)
        Output: sp_rlm   (Order: poloidal,diff_poloidal,toroidal)
        type(sph_rlm_grid), intent(in) :: sph_rlm
        type(sph_rtm_grid), intent(in) :: sph_rtm
        type(sph_comm_tbl), intent(in) :: comm_rlm, comm_rtm
        type(index_4_sph_trans), intent(in) :: idx_trns
        type(leg_trns_on_the_fly_work), intent(inout) :: WK_l_otf
Parameters
ncomp Total number of components for spherical transform
nvector Number of vector for spherical transform
nscalar Number of scalar (including tensor components) for spherical transform
Function/Subroutine Documentation
leg_bwd_trans_1latitude()
subroutine, private leg_bwd_trans_on_the_fly::leg_bwd_trans_1latitude (integer(kind = kint), intent(in) lp_rtm, integer(kind = kint), intent(in) jst, integer(kind = kint), intent(in) mm, integer(kind = kint), intent(in) mp_rlm, integer(kind = kint), intent(in) mn_rlm, integer(kind = kint), intent(in) nkrs, integer(kind = kint), intent(in) nkrt, integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_comm_tbl), intent(in) comm_rlm, type(sph_comm_tbl), intent(in) comm_rtm, type(index_4_sph_trans), intent(in) idx_trns, type(legendre_4_sph_trans), intent(in) leg, integer(kind = kint), intent(in) n_WR, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_wr), intent(inout) WR, real (kind=kreal), dimension(n_ws), intent(inout) WS, integer(kind = kint), intent(in) n_jk_e, integer(kind = kint), intent(in) n_jk_o, type(spectr_matrix_omp), intent(inout) Smat, type(leg_jt_omp_matrix), intent(inout) Pjt_mat, type(field_matrix_omp), intent(inout) Fmat, type(work_make_legendre), intent(inout) wk_plm) private
Definition at line 175 of file leg_bwd_trans_on_the_fly.f90.
References cal_vr_rtm_sym_mat_tsmp::cal_vr_rtm_sym_mat_lt_rin(), and small_matmul_leg_trans_krin::matvec_bwd_leg_trans_pj().
Referenced by legendre_b_trans_on_the_fly().
leg_bwd_trans_at_equator()
subroutine, private leg_bwd_trans_on_the_fly::leg_bwd_trans_at_equator (integer(kind = kint), intent(in) lp_rtm, integer(kind = kint), intent(in) jst, integer(kind = kint), intent(in) mm, integer(kind = kint), intent(in) mp_rlm, integer(kind = kint), intent(in) mn_rlm, integer(kind = kint), intent(in) nkrs, integer(kind = kint), intent(in) nkrt, integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_comm_tbl), intent(in) comm_rtm, type(legendre_4_sph_trans), intent(in) leg, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS, integer(kind = kint), intent(in) n_jk_e, integer(kind = kint), intent(in) n_jk_o, type(spectr_matrix_omp), intent(inout) Smat, type(leg_jt_omp_matrix), intent(inout) Pjt_mat, type(field_matrix_omp), intent(inout) Fmat, type(work_make_legendre), intent(inout) wk_plm) private
Definition at line 247 of file leg_bwd_trans_on_the_fly.f90.
References cal_vr_rtm_sym_mat_tsmp::cal_vr_rtm_sym_mat_eq_rin(), and small_matmul_leg_trans_krin::matvec_bwd_leg_trans_pj().
Referenced by legendre_b_trans_on_the_fly().
legendre_b_trans_on_the_fly()
subroutine leg_bwd_trans_on_the_fly::legendre_b_trans_on_the_fly (integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_comm_tbl), intent(in) comm_rlm, type(sph_comm_tbl), intent(in) comm_rtm, type(legendre_4_sph_trans), intent(in) leg, type(index_4_sph_trans), intent(in) idx_trns, integer(kind = kint), intent(in) n_WR, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_wr), intent(inout) WR, real (kind=kreal), dimension(n_ws), intent(inout) WS, type(leg_trns_on_the_fly_work), intent(inout) WK_l_otf)
Definition at line 62 of file leg_bwd_trans_on_the_fly.f90.
References m_work_time::elps1, m_work_time::end_elapsed_time(), m_elapsed_labels_sph_trns::iflag_sdt_time, m_elapsed_labels_sph_trns::ist_elapsed_sdt, leg_bwd_trans_1latitude(), leg_bwd_trans_at_equator(), m_machine_parameter::np_smp, set_sp_rlm_sym_mat_tsmp::set_sp_rlm_sym_mat_rin(), and m_work_time::start_elapsed_time().
Referenced by t_legendre_trans_select::sel_backward_legendre_trans().
Variable Documentation
omp_get_max_threads
integer, external leg_bwd_trans_on_the_fly::omp_get_max_threads
Definition at line 52 of file leg_bwd_trans_on_the_fly.f90.