CALYPSO: m_file_format_switch Module Reference
m_file_format_switch Module Reference
integer flags for Data file's format
Functions/Subroutines
integer(kind=kint) function choose_file_format (file_fmt)
integer(kind=kint) function choose_para_file_format (file_fmt)
subroutine choose_file_format_array (num, files_fmt, id_files_fmt)
integer(kind=kint) function, private set_file_format (file_fmt_ctl, i_file_fmt)
integer(kind=kint) function, private set_parallel_file_format (file_fmt_ctl, i_file_fmt)
Variables
integer(kind=kint), parameter id_no_file = -1000
Integer flag for no file.
integer(kind=kint), parameter id_ascii_file_fmt = 0
Integer flag for ascii data format.
integer(kind=kint), parameter id_binary_file_fmt = 1
Integer flag for binary data format.
integer(kind=kint), parameter id_gzip_bin_file_fmt = 2
Integer flag for origianl gzipped binary data format.
integer(kind=kint), parameter id_gzip_txt_file_fmt = 3
Integer flag for origianl gzipped ascii data format.
integer(kind=kint), parameter iflag_para = 0
Integer flag for distributed data.
integer(kind=kint), parameter iflag_single = 100
Integer flag for merged data.
integer(kind=kint), parameter id_rayleigh = 105
Integer flag for Rayleigh data.
integer(kind=kint), parameter id_rayleigh99 = 195
Integer flag for Rayleigh Ver.0.9x data.
Detailed Description
integer flags for Data file's format
      integer(kind= kint) function choose_file_format(file_fmt)
      integer(kind= kint) function choose_para_file_format(file_fmt)
        type(read_character_item), intent(in) :: file_fmt
      subroutine choose_file_format_array(num, files_fmt, id_files_fmt)
        type(ctl_array_chara), intent(in) :: files_fmt
        File format name
          'ascii':   text (formatted) data
          'gzip':    gziopped text (formatted) data
          'binary':  binary data
          'merged_ascii': text (formatted) data in merged file
          'merged_gzip':  gziopped text (formatted) data in merged file
          'merged_binary': binary data in merged file
Parameters
file_fmt Structure for File format control
file_fmt_ctl File format name
i_file_fmt Check flag if file format is read
id_file_fmt File format flag (Output)
Function/Subroutine Documentation
choose_file_format()
integer(kind= kint) function m_file_format_switch::choose_file_format (type(read_character_item), intent(in) file_fmt)
Definition at line 71 of file m_file_format_switch.f90.
References set_file_format().
Referenced by set_control_platform_data::set_file_control_params().
choose_file_format_array()
subroutine m_file_format_switch::choose_file_format_array (integer(kind= kint), intent(in) num, type(ctl_array_chara), intent(in) files_fmt, integer(kind= kint), dimension(num), intent(inout) id_files_fmt)
Definition at line 100 of file m_file_format_switch.f90.
References m_file_format_labels::dealloc_file_format_flags(), m_file_format_labels::init_file_format_flags(), and set_file_format().
choose_para_file_format()
integer(kind= kint) function m_file_format_switch::choose_para_file_format (type(read_character_item), intent(in) file_fmt)
Definition at line 85 of file m_file_format_switch.f90.
References set_parallel_file_format().
Referenced by set_control_platform_data::set_control_sph_mesh(), and set_control_platform_data::set_parallel_file_ctl_params().
set_file_format()
integer(kind= kint) function, private m_file_format_switch::set_file_format (character(len=kchara), intent(in) file_fmt_ctl, integer(kind= kint), intent(in) i_file_fmt) private
Definition at line 125 of file m_file_format_switch.f90.
References m_file_format_labels::ascii_flags, m_file_format_labels::binary_flags, t_multi_flag_labels::check_mul_flags(), m_file_format_labels::gzip_ascii_flags, m_file_format_labels::gzip_bin_flags, id_ascii_file_fmt, id_binary_file_fmt, id_gzip_bin_file_fmt, id_gzip_txt_file_fmt, id_no_file, and m_file_format_labels::no_file_flags.
Referenced by choose_file_format(), choose_file_format_array(), and set_parallel_file_format().
set_parallel_file_format()
integer(kind= kint) function, private m_file_format_switch::set_parallel_file_format (character(len=kchara), intent(in) file_fmt_ctl, integer(kind= kint), intent(in) i_file_fmt) private
Definition at line 155 of file m_file_format_switch.f90.
References t_multi_flag_labels::check_mul_flags(), skip_comment_f::cmp_no_case(), m_file_format_labels::dealloc_file_format_flags(), m_file_format_labels::hd_rayleigh, m_file_format_labels::hd_rayleigh99, id_ascii_file_fmt, id_binary_file_fmt, id_gzip_bin_file_fmt, id_gzip_txt_file_fmt, id_rayleigh, id_rayleigh99, iflag_single, m_file_format_labels::init_file_format_flags(), m_file_format_labels::mgd_ascii_flags, m_file_format_labels::mgd_binary_flags, m_file_format_labels::mgd_gzip_bin_flags, m_file_format_labels::mgd_gzip_flags, and set_file_format().
Referenced by choose_para_file_format().
Variable Documentation
id_ascii_file_fmt
integer(kind = kint), parameter m_file_format_switch::id_ascii_file_fmt = 0
Integer flag for ascii data format.
Definition at line 45 of file m_file_format_switch.f90.
Referenced by set_file_format(), and set_parallel_file_format().
id_binary_file_fmt
integer(kind = kint), parameter m_file_format_switch::id_binary_file_fmt = 1
Integer flag for binary data format.
Definition at line 47 of file m_file_format_switch.f90.
Referenced by element_mesh_mpi_io_select::sel_mpi_read_edge_mesh(), element_mesh_mpi_io_select::sel_mpi_read_ele_mesh(), sph_file_mpi_io_select::sel_mpi_read_geom_rtm_file(), sph_file_mpi_io_select::sel_mpi_read_geom_rtp_file(), mesh_mpi_io_select::sel_mpi_read_geometry_size(), mesh_mpi_io_select::sel_mpi_read_mesh(), mesh_mpi_io_select::sel_mpi_read_mesh_geometry(), sph_file_mpi_io_select::sel_mpi_read_modes_rlm_file(), mesh_mpi_io_select::sel_mpi_read_node_size(), sph_file_mpi_io_select::sel_mpi_read_spectr_rj_file(), element_mesh_mpi_io_select::sel_mpi_read_surf_mesh(), element_mesh_mpi_io_select::sel_mpi_write_edge_mesh_file(), element_mesh_mpi_io_select::sel_mpi_write_ele_mesh_file(), sph_file_mpi_io_select::sel_mpi_write_geom_rtm_file(), sph_file_mpi_io_select::sel_mpi_write_geom_rtp_file(), mesh_mpi_io_select::sel_mpi_write_mesh_file(), sph_file_mpi_io_select::sel_mpi_write_modes_rlm_file(), sph_file_mpi_io_select::sel_mpi_write_spectr_rj_file(), element_mesh_mpi_io_select::sel_mpi_write_surf_mesh_file(), field_io_select::sel_read_alloc_field_head(), field_io_select::sel_read_alloc_step_field_file(), element_mesh_io_select::sel_read_edge_mesh(), element_mesh_io_select::sel_read_ele_mesh(), sph_file_io_select::sel_read_geom_rtm_file(), sph_file_io_select::sel_read_geom_rtp_file(), mesh_io_select::sel_read_geometry_size(), mesh_io_select::sel_read_mesh(), mesh_io_select::sel_read_mesh_geometry(), sph_file_io_select::sel_read_modes_rlm_file(), mesh_io_select::sel_read_node_size(), sph_file_io_select::sel_read_spectr_rj_file(), field_io_select::sel_read_step_field_file(), element_mesh_io_select::sel_read_surf_mesh(), element_mesh_io_select::sel_write_edge_mesh_file(), element_mesh_io_select::sel_write_ele_mesh_file(), sph_file_io_select::sel_write_geom_rtm_file(), sph_file_io_select::sel_write_geom_rtp_file(), mesh_io_select::sel_write_mesh_file(), sph_file_io_select::sel_write_modes_rlm_file(), sph_file_io_select::sel_write_spectr_modes_rj_file(), field_io_select::sel_write_step_field_file(), element_mesh_io_select::sel_write_surf_mesh_file(), set_field_file_names::set_fem_fld_file_name(), set_file_format(), set_mesh_file_names::set_mesh_file_name(), set_parallel_file_format(), and set_field_file_names::set_sph_fld_file_name().
id_gzip_bin_file_fmt
integer(kind = kint), parameter m_file_format_switch::id_gzip_bin_file_fmt = 2
Integer flag for origianl gzipped binary data format.
Definition at line 49 of file m_file_format_switch.f90.
Referenced by element_mesh_mpi_io_select::sel_mpi_read_edge_mesh(), element_mesh_mpi_io_select::sel_mpi_read_ele_mesh(), sph_file_mpi_io_select::sel_mpi_read_geom_rtm_file(), sph_file_mpi_io_select::sel_mpi_read_geom_rtp_file(), mesh_mpi_io_select::sel_mpi_read_geometry_size(), mesh_mpi_io_select::sel_mpi_read_mesh(), mesh_mpi_io_select::sel_mpi_read_mesh_geometry(), sph_file_mpi_io_select::sel_mpi_read_modes_rlm_file(), mesh_mpi_io_select::sel_mpi_read_node_size(), sph_file_mpi_io_select::sel_mpi_read_spectr_rj_file(), element_mesh_mpi_io_select::sel_mpi_read_surf_mesh(), element_mesh_mpi_io_select::sel_mpi_write_edge_mesh_file(), element_mesh_mpi_io_select::sel_mpi_write_ele_mesh_file(), sph_file_mpi_io_select::sel_mpi_write_geom_rtm_file(), sph_file_mpi_io_select::sel_mpi_write_geom_rtp_file(), mesh_mpi_io_select::sel_mpi_write_mesh_file(), sph_file_mpi_io_select::sel_mpi_write_modes_rlm_file(), sph_file_mpi_io_select::sel_mpi_write_spectr_rj_file(), element_mesh_mpi_io_select::sel_mpi_write_surf_mesh_file(), field_io_select::sel_read_alloc_field_head(), field_io_select::sel_read_alloc_step_field_file(), element_mesh_io_select::sel_read_edge_mesh(), element_mesh_io_select::sel_read_ele_mesh(), sph_file_io_select::sel_read_geom_rtm_file(), sph_file_io_select::sel_read_geom_rtp_file(), mesh_io_select::sel_read_geometry_size(), mesh_io_select::sel_read_mesh(), mesh_io_select::sel_read_mesh_geometry(), sph_file_io_select::sel_read_modes_rlm_file(), mesh_io_select::sel_read_node_size(), sph_file_io_select::sel_read_spectr_rj_file(), field_io_select::sel_read_step_field_file(), element_mesh_io_select::sel_read_surf_mesh(), element_mesh_io_select::sel_write_edge_mesh_file(), element_mesh_io_select::sel_write_ele_mesh_file(), sph_file_io_select::sel_write_geom_rtm_file(), sph_file_io_select::sel_write_geom_rtp_file(), mesh_io_select::sel_write_mesh_file(), sph_file_io_select::sel_write_modes_rlm_file(), sph_file_io_select::sel_write_spectr_modes_rj_file(), field_io_select::sel_write_step_field_file(), element_mesh_io_select::sel_write_surf_mesh_file(), set_field_file_names::set_fem_fld_file_name(), set_file_format(), set_mesh_file_names::set_mesh_file_name(), set_parallel_file_format(), and set_field_file_names::set_sph_fld_file_name().
id_gzip_txt_file_fmt
integer(kind = kint), parameter m_file_format_switch::id_gzip_txt_file_fmt = 3
Integer flag for origianl gzipped ascii data format.
Definition at line 51 of file m_file_format_switch.f90.
Referenced by delete_data_files::delete_parallel_files(), viewer_mesh_mpi_io_select::sel_mpi_output_surface_grid(), element_mesh_mpi_io_select::sel_mpi_read_edge_mesh(), element_mesh_mpi_io_select::sel_mpi_read_ele_mesh(), sph_file_mpi_io_select::sel_mpi_read_geom_rtm_file(), sph_file_mpi_io_select::sel_mpi_read_geom_rtp_file(), mesh_mpi_io_select::sel_mpi_read_geometry_size(), mesh_mpi_io_select::sel_mpi_read_mesh(), mesh_mpi_io_select::sel_mpi_read_mesh_geometry(), sph_file_mpi_io_select::sel_mpi_read_modes_rlm_file(), mesh_mpi_io_select::sel_mpi_read_node_size(), sph_file_mpi_io_select::sel_mpi_read_spectr_rj_file(), element_mesh_mpi_io_select::sel_mpi_read_surf_mesh(), element_mesh_mpi_io_select::sel_mpi_write_edge_mesh_file(), element_mesh_mpi_io_select::sel_mpi_write_ele_mesh_file(), sph_file_mpi_io_select::sel_mpi_write_geom_rtm_file(), sph_file_mpi_io_select::sel_mpi_write_geom_rtp_file(), mesh_mpi_io_select::sel_mpi_write_mesh_file(), sph_file_mpi_io_select::sel_mpi_write_modes_rlm_file(), sph_file_mpi_io_select::sel_mpi_write_spectr_rj_file(), element_mesh_mpi_io_select::sel_mpi_write_surf_mesh_file(), input_old_file_sel_4_zlib::sel_read_alloc_field_file(), field_io_select::sel_read_alloc_field_head(), field_io_select::sel_read_alloc_step_field_file(), element_mesh_io_select::sel_read_edge_mesh(), element_mesh_io_select::sel_read_ele_mesh(), sph_file_io_select::sel_read_geom_rtm_file(), sph_file_io_select::sel_read_geom_rtp_file(), mesh_io_select::sel_read_geometry_size(), mesh_io_select::sel_read_mesh(), mesh_io_select::sel_read_mesh_geometry(), sph_file_io_select::sel_read_modes_rlm_file(), mesh_io_select::sel_read_node_size(), input_old_file_sel_4_zlib::sel_read_rst_comps(), input_old_file_sel_4_zlib::sel_read_rst_file(), sph_file_io_select::sel_read_spectr_rj_file(), field_io_select::sel_read_step_field_file(), element_mesh_io_select::sel_read_surf_mesh(), element_mesh_io_select::sel_write_edge_mesh_file(), element_mesh_io_select::sel_write_ele_mesh_file(), sph_file_io_select::sel_write_geom_rtm_file(), sph_file_io_select::sel_write_geom_rtp_file(), mesh_io_select::sel_write_mesh_file(), sph_file_io_select::sel_write_modes_rlm_file(), sph_file_io_select::sel_write_spectr_modes_rj_file(), field_io_select::sel_write_step_field_file(), element_mesh_io_select::sel_write_surf_mesh_file(), set_field_file_names::set_fem_fld_file_name(), set_file_format(), set_mesh_file_names::set_mesh_file_name(), set_parallel_file_format(), and set_field_file_names::set_sph_fld_file_name().
id_no_file
integer(kind = kint), parameter m_file_format_switch::id_no_file = -1000
Integer flag for no file.
Definition at line 42 of file m_file_format_switch.f90.
Referenced by t_ctl_params_gen_sph_shell::set_control_4_gen_shell_grids(), set_control_newsph::set_control_4_newsph(), and set_file_format().
id_rayleigh
integer(kind = kint), parameter m_file_format_switch::id_rayleigh = 105
Integer flag for Rayleigh data.
Definition at line 59 of file m_file_format_switch.f90.
Referenced by set_parallel_file_format().
id_rayleigh99
integer(kind = kint), parameter m_file_format_switch::id_rayleigh99 = 195
Integer flag for Rayleigh Ver.0.9x data.
Definition at line 61 of file m_file_format_switch.f90.
Referenced by analyzer_rayleigh_cvt_sph::init_cvt_rayleigh_sph(), and set_parallel_file_format().
iflag_para
integer(kind = kint), parameter m_file_format_switch::iflag_para = 0
Integer flag for distributed data.
Definition at line 54 of file m_file_format_switch.f90.
iflag_single
integer(kind = kint), parameter m_file_format_switch::iflag_single = 100
Integer flag for merged data.
Definition at line 56 of file m_file_format_switch.f90.
Referenced by m_field_file_format::choose_para_fld_file_format(), t_control_params_4_iso::count_control_4_iso(), t_control_params_4_psf::count_control_4_psf(), element_mesh_mpi_io_select::sel_mpi_read_edge_mesh(), element_mesh_mpi_io_select::sel_mpi_read_ele_mesh(), sph_file_mpi_io_select::sel_mpi_read_geom_rtm_file(), sph_file_mpi_io_select::sel_mpi_read_geom_rtp_file(), mesh_mpi_io_select::sel_mpi_read_geometry_size(), mesh_mpi_io_select::sel_mpi_read_mesh(), mesh_mpi_io_select::sel_mpi_read_mesh_geometry(), sph_file_mpi_io_select::sel_mpi_read_modes_rlm_file(), mesh_mpi_io_select::sel_mpi_read_node_size(), sph_file_mpi_io_select::sel_mpi_read_spectr_rj_file(), element_mesh_mpi_io_select::sel_mpi_read_surf_mesh(), element_mesh_mpi_io_select::sel_mpi_write_edge_mesh_file(), element_mesh_mpi_io_select::sel_mpi_write_ele_mesh_file(), sph_file_mpi_io_select::sel_mpi_write_geom_rtm_file(), sph_file_mpi_io_select::sel_mpi_write_geom_rtp_file(), mesh_mpi_io_select::sel_mpi_write_mesh_file(), sph_file_mpi_io_select::sel_mpi_write_modes_rlm_file(), sph_file_mpi_io_select::sel_mpi_write_spectr_rj_file(), element_mesh_mpi_io_select::sel_mpi_write_surf_mesh_file(), field_io_select::sel_read_alloc_field_head(), parallel_ucd_io_select::sel_read_alloc_para_udt_file(), field_io_select::sel_read_alloc_step_field_file(), parallel_ucd_io_select::sel_read_parallel_udt_file(), field_io_select::sel_read_step_field_file(), parallel_ucd_io_select::sel_write_parallel_ucd_file(), parallel_ucd_io_select::sel_write_parallel_ucd_mesh(), field_io_select::sel_write_step_field_file(), set_field_file_names::set_fem_fld_file_name(), set_mesh_file_names::set_mesh_file_name(), set_parallel_file_format(), and set_field_file_names::set_sph_fld_file_name().