CALYPSO: address_sph_trans_mhd Module Reference
address_sph_trans_mhd Module Reference
Field addresses for spherical harmonics transform in MHD dynamo simulation.
Functions/Subroutines
subroutine bwd_trans_address_mhd (d_rj, ipol, iphys, b_trns, trns_back)
subroutine fwd_trans_address_mhd (d_rj, ipol, iphys, f_trns, trns_fwd)
Detailed Description
Field addresses for spherical harmonics transform in MHD dynamo simulation.
      subroutine bwd_trans_address_MHD                                &
     &         (d_rj, ipol, iphys, b_trns, trns_back)
        type(MHD_evolution_param), intent(in) :: MHD_prop
        type(phys_data), intent(in) :: d_rj
        type(phys_address), intent(in) :: ipol, iphys
        type(phys_address), intent(inout) :: b_trns
        type(spherical_transform_data), intent(inout) :: trns_back
      subroutine fwd_trans_address_MHD                                &
     &         (d_rj, ipol, iphys, f_trns, trns_fwd)
        type(MHD_evolution_param), intent(in) :: MHD_prop
        type(phys_data), intent(in) :: d_rj
        type(phys_address), intent(in) :: ipol, iphys
        type(phys_address), intent(inout) :: f_trns
        type(spherical_transform_data), intent(inout) :: trns_fwd
Function/Subroutine Documentation
bwd_trans_address_mhd()
subroutine address_sph_trans_mhd::bwd_trans_address_mhd (type(phys_data), intent(in) d_rj, type(phys_address), intent(in) ipol, type(phys_address), intent(in) iphys, type(phys_address), intent(inout) b_trns, type(spherical_transform_data), intent(inout) trns_back)
Definition at line 47 of file address_sph_trans_MHD.f90.
References add_base_field_4_sph_trns::add_base_scalar_4_mhd_sph_trns(), add_base_field_4_sph_trns::add_base_vector_4_mhd_sph_trns(), t_addresses_sph_transform::alloc_sph_trns_field_name(), and m_machine_parameter::iflag_debug.
Referenced by set_address_sph_trans_mhd::set_addresses_trans_sph_mhd().
fwd_trans_address_mhd()
subroutine address_sph_trans_mhd::fwd_trans_address_mhd (type(phys_data), intent(in) d_rj, type(phys_address), intent(in) ipol, type(phys_address), intent(in) iphys, type(phys_address), intent(inout) f_trns, type(spherical_transform_data), intent(inout) trns_fwd)
Definition at line 82 of file address_sph_trans_MHD.f90.
References add_base_force_4_sph_trns::add_base_force_4_mhd_sph_trns(), add_base_force_4_sph_trns::add_div_coriolis_mhd_sph_trns(), add_base_force_4_sph_trns::add_rot_coriolis_mhd_sph_trns(), t_addresses_sph_transform::alloc_sph_trns_field_name(), and m_machine_parameter::iflag_debug.
Referenced by set_address_sph_trans_mhd::set_addresses_trans_sph_mhd().