CALYPSO: /home/takumi kera/calypso/src/programs/mesh_utilities/main_generate_sph_grids.f90 File Reference
main_generate_sph_grids.f90 File Reference
program generate_sph_grids
Functions/Subroutines
program generate_sph_grids
Main program generate spherical harmonics indices.
Detailed Description
program generate_sph_grids
Author
H. Matsui
Date
Programmed by H. Matsui in Feb., 2015
Definition in file main_generate_sph_grids.f90.
Function/Subroutine Documentation
generate_sph_grids()
program generate_sph_grids
Main program generate spherical harmonics indices.
Definition at line 9 of file main_generate_sph_grids.f90.
References analyzer_gen_sph_grids::analyze_gen_sph_grids(), calypso_mpi::calypso_mpi_finalize(), calypso_mpi::calypso_mpi_init(), and analyzer_gen_sph_grids::init_gen_sph_grids().