CALYPSO: cal_rms_fields_by_sph Module Reference
cal_rms_fields_by_sph Module Reference
evaluate mean square data from spectr data
Functions/Subroutines
subroutine init_rms_4_sph_spectr (sph_params, sph_rj, rj_fld, pwr, WK_pwr)
subroutine cal_mean_squre_in_shell (sph_params, sph_rj, ipol, rj_fld, g_sph_rj, pwr, WK_pwr)
subroutine cal_correlate_in_shell (sph_params, sph_rj, rj_fld1, rj_fld2, g_sph_rj, cor, WK_pwr)
subroutine global_sum_sph_layerd_square (l_truncation, WK_pwr, pwr)
subroutine global_sum_sph_volume_square (l_truncation, ntot_rms_rj, WK_pwr, num_vol_spectr, v_pwr)
subroutine sum_mean_square_on_sphere (sph_params, sph_rj, pwr)
subroutine sum_mean_square_on_volume (sph_params, ntot_rms_rj, num_vol_spectr, v_pwr)
subroutine, private find_radial_grid_index (sph_rj, kr_default, r_target, kr_target)
subroutine, private set_domains_4_spectr_output (sph_rj, pwr)
Detailed Description
evaluate mean square data from spectr data
      subroutine init_rms_4_sph_spectr                                &
     &         (sph_params, sph_rj, rj_fld, pwr, WK_pwr)
      subroutine cal_mean_squre_in_shell(sph_params,                  &
     &          sph_rj, ipol, rj_fld, g_sph_rj, pwr, WK_pwr)
      subroutine cal_correlate_in_shell(sph_params,                   &
     &          sph_rj, rj_fld1, rj_fld2, g_sph_rj, cor, WK_pwr)
        type(sph_rj_grid), intent(in) :: sph_rj
        type(phys_data), intent(in) :: rj_fld
        type(sph_mean_squares), intent(inout) :: pwr
        type(sph_mean_square_work), intent(inout) :: WK_pwr
      subroutine global_sum_sph_layerd_square                         &
     &         (l_truncation, WK_pwr, pwr)
        type(sph_mean_square_work), intent(in) :: WK_pwr
        type(sph_mean_squares), intent(inout) :: pwr
      subroutine global_sum_sph_volume_square                         &
     &         (l_truncation, ntot_rms_rj, WK_pwr,                    &
     &          num_vol_spectr, v_pwr)
        type(sph_mean_square_work), intent(in) :: WK_pwr
        type(sph_vol_mean_squares), intent(inout)                     &
     &                         :: v_pwr(num_vol_spectr)
      subroutine sum_mean_square_on_sphere(sph_params, sph_rj, pwr)
        type(sph_shell_parameters), intent(in) :: sph_params
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(sph_mean_squares), intent(inout) :: pwr
      subroutine sum_mean_square_on_volume                            &
     &         (sph_params, ntot_rms_rj, num_vol_spectr, v_pwr)
      type(sph_shell_parameters), intent(in) :: sph_params
      type(sph_vol_mean_squares), intent(inout)                       &
     &                         :: v_pwr(num_vol_spectr)
Function/Subroutine Documentation
cal_correlate_in_shell()
subroutine cal_rms_fields_by_sph::cal_correlate_in_shell (type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(phys_data), intent(in) rj_fld1, type(phys_data), intent(in) rj_fld2, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, type(sph_mean_squares), intent(inout) cor, type(sph_mean_square_work), intent(inout) WK_pwr)
Definition at line 229 of file cal_rms_fields_by_sph.f90.
References global_sum_sph_layerd_square(), global_sum_sph_volume_square(), m_machine_parameter::iflag_debug, sum_mean_square_on_sphere(), sum_mean_square_on_volume(), and sum_sph_rms_data::sum_sph_layerd_correlate().
cal_mean_squre_in_shell()
subroutine cal_rms_fields_by_sph::cal_mean_squre_in_shell (type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(phys_address), intent(in) ipol, type(phys_data), intent(in) rj_fld, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, type(sph_mean_squares), intent(inout) pwr, type(sph_mean_square_work), intent(inout) WK_pwr)
Definition at line 183 of file cal_rms_fields_by_sph.f90.
References volume_average_4_sph::cal_volume_average_sph(), global_sum_sph_layerd_square(), global_sum_sph_volume_square(), m_machine_parameter::iflag_debug, sum_mean_square_on_sphere(), sum_mean_square_on_volume(), and sum_sph_rms_data::sum_sph_layerd_rms().
Referenced by cal_write_sph_monitor_data::cal_sph_monitor_data(), and const_data_4_dynamobench::s_const_data_4_dynamobench().
find_radial_grid_index()
subroutine, private cal_rms_fields_by_sph::find_radial_grid_index (type(sph_rj_grid), intent(in) sph_rj, integer(kind = kint), intent(in) kr_default, real(kind = kreal), intent(inout) r_target, integer(kind = kint), intent(inout) kr_target) private
Definition at line 461 of file cal_rms_fields_by_sph.f90.
References m_constants::zero.
Referenced by init_rms_4_sph_spectr().
global_sum_sph_layerd_square()
subroutine cal_rms_fields_by_sph::global_sum_sph_layerd_square (integer(kind = kint), intent(in) l_truncation, type(sph_mean_square_work), intent(in) WK_pwr, type(sph_mean_squares), intent(inout) pwr)
Definition at line 272 of file cal_rms_fields_by_sph.f90.
References calypso_mpi_real::calypso_mpi_reduce_real().
Referenced by cal_correlate_in_shell(), and cal_mean_squre_in_shell().
global_sum_sph_volume_square()
subroutine cal_rms_fields_by_sph::global_sum_sph_volume_square (integer(kind = kint), intent(in) l_truncation, integer(kind = kint), intent(in) ntot_rms_rj, type(sph_mean_square_work), intent(in) WK_pwr, integer(kind = kint), intent(in) num_vol_spectr, type(sph_vol_mean_squares), dimension(num_vol_spectr), intent(inout) v_pwr)
Definition at line 302 of file cal_rms_fields_by_sph.f90.
References calypso_mpi_real::calypso_mpi_reduce_real().
Referenced by cal_correlate_in_shell(), and cal_mean_squre_in_shell().
init_rms_4_sph_spectr()
subroutine cal_rms_fields_by_sph::init_rms_4_sph_spectr (type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(phys_data), intent(in) rj_fld, type(sph_mean_squares), intent(inout) pwr, type(sph_mean_square_work), intent(inout) WK_pwr)
Definition at line 66 of file cal_rms_fields_by_sph.f90.
References t_rms_4_sph_spectr::alloc_ave_4_sph_spectr(), t_rms_4_sph_spectr::alloc_num_spec_layer(), t_rms_4_sph_spectr::alloc_rms_4_sph_spectr(), t_rms_4_sph_spectr::alloc_rms_name_sph_spec(), t_sum_sph_rms_data::allocate_rms_sph_local_data(), cal_ave_4_rms_vector_sph::cal_one_over_volume(), find_radial_grid_index(), m_machine_parameter::iflag_debug, m_constants::ione, calypso_mpi::my_rank, quicksort::quicksort_int(), set_domains_4_spectr_output(), and sum_sph_rms_data::set_sum_table_4_sph_spectr().
Referenced by t_sph_mhd_monitor_data_io::init_rms_4_sph_spectr_4_mhd().
set_domains_4_spectr_output()
subroutine, private cal_rms_fields_by_sph::set_domains_4_spectr_output (type(sph_rj_grid), intent(in) sph_rj, type(sph_mean_squares), intent(inout) pwr) private
Definition at line 506 of file cal_rms_fields_by_sph.f90.
References calypso_mpi_int4::calypso_mpi_allreduce_one_int4(), m_machine_parameter::iflag_debug, m_constants::izero, calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by init_rms_4_sph_spectr().
sum_mean_square_on_sphere()
subroutine cal_rms_fields_by_sph::sum_mean_square_on_sphere (type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(sph_mean_squares), intent(inout) pwr)
Definition at line 339 of file cal_rms_fields_by_sph.f90.
References calypso_mpi::my_rank, cal_ave_4_rms_vector_sph::pick_axis_sph_power(), cal_ave_4_rms_vector_sph::sum_sph_rms_all_modes(), cal_ave_4_rms_vector_sph::surf_ave_4_sph_rms(), and cal_ave_4_rms_vector_sph::surf_ave_4_sph_rms_int().
Referenced by cal_correlate_in_shell(), and cal_mean_squre_in_shell().
sum_mean_square_on_volume()
subroutine cal_rms_fields_by_sph::sum_mean_square_on_volume (type(sph_shell_parameters), intent(in) sph_params, integer(kind = kint), intent(in) ntot_rms_rj, integer(kind = kint), intent(in) num_vol_spectr, type(sph_vol_mean_squares), dimension(num_vol_spectr), intent(inout) v_pwr)
Definition at line 397 of file cal_rms_fields_by_sph.f90.
References calypso_mpi::my_rank, cal_ave_4_rms_vector_sph::pick_axis_sph_vol_pwr(), cal_ave_4_rms_vector_sph::sum_sph_vol_rms_all_modes(), cal_ave_4_rms_vector_sph::vol_ave_4_rms_sph(), and cal_ave_4_rms_vector_sph::vol_ave_4_rms_sph_int().
Referenced by cal_correlate_in_shell(), and cal_mean_squre_in_shell().