CALYPSO: t_ucd_file Module Reference
t_ucd_file Module Reference
Strucures for field data output.
Functions/Subroutines
subroutine s_output_ucd_file_control (ucd_param, i_step, ucd_step, time_d, ucd)
subroutine output_grd_file_4_snapshot (ucd_param, ucd_step, mesh, nod_fld, ucd)
subroutine read_udt_4_snap (i_step, ucd_step, udt_file_param, nod_fld, t_IO)
subroutine finalize_output_ucd (ucd_param, ucd)
Detailed Description
Strucures for field data output.
      subroutine s_output_ucd_file_control                            &
     &         (ucd_param, i_step, ucd_step, time_d, ucd)
        type(IO_step_param), intent(in) :: ucd_step
        type(field_IO_params), intent(in) :: ucd_param
        type(time_data), intent(in) :: time_d
        type(ucd_data), intent(in) :: ucd
      subroutine output_grd_file_4_snapshot                           &
     &         (ucd_param, ucd_step, mesh, nod_fld, ucd)
        type(mesh_geometry), intent(in) :: mesh
        type(mesh_data_MHD), intent(in) :: MHD_mesh
        type(phys_data), intent(in) :: nod_fld
        type(field_IO_params), intent(in) :: ucd_param
        type(ucd_data), intent(inout) :: ucd
      subroutine read_udt_4_snap                                      &
     &         (i_step, ucd_step, udt_file_param, nod_fld, t_IO)
        type(IO_step_param), intent(in) :: ucd_step
        type(field_IO_params), intent(in) :: udt_file_param
        type(phys_data),intent(inout) :: nod_fld
        type(time_data), intent(inout) :: t_IO
      subroutine finalize_output_ucd(ucd_param, ucd)
        type(field_IO_params), intent(in) :: ucd_param
        type(ucd_data), intent(inout) :: ucd
Function/Subroutine Documentation
finalize_output_ucd()
subroutine t_ucd_file::finalize_output_ucd (type(field_io_params), intent(in) ucd_param, type(ucd_data), intent(inout) ucd)
Definition at line 132 of file t_ucd_file.f90.
References output_parallel_ucd_file::finalize_ucd_file_output().
Referenced by fem_analyzer_sph_mhd::fem_finalize().
output_grd_file_4_snapshot()
subroutine t_ucd_file::output_grd_file_4_snapshot (type(field_io_params), intent(in) ucd_param, type(io_step_param), intent(in) ucd_step, type(mesh_geometry), intent(in) mesh, type(phys_data), intent(in) nod_fld, type(ucd_data), intent(inout) ucd)
Definition at line 86 of file t_ucd_file.f90.
References output_parallel_ucd_file::link_output_grd_file().
Referenced by fem_analyzer_sph_mhd::fem_initialize_sph_mhd().
read_udt_4_snap()
subroutine t_ucd_file::read_udt_4_snap (integer(kind = kint), intent(in) i_step, type(io_step_param), intent(in) ucd_step, type(field_io_params), intent(in) udt_file_param, type(phys_data), intent(inout) nod_fld, type(time_data), intent(inout) t_IO)
Definition at line 107 of file t_ucd_file.f90.
References t_io_step_parameter::io_step_exc_zero_inc(), calypso_mpi::my_rank, t_io_step_parameter::output_io_flag(), and output_parallel_ucd_file::set_data_by_read_ucd_once().
s_output_ucd_file_control()
subroutine t_ucd_file::s_output_ucd_file_control (type(field_io_params), intent(in) ucd_param, integer(kind = kint), intent(in) i_step, type(io_step_param), intent(in) ucd_step, type(time_data), intent(in) time_d, type(ucd_data), intent(in) ucd)
Definition at line 59 of file t_ucd_file.f90.
References t_io_step_parameter::io_step_exc_zero_inc(), t_io_step_parameter::output_io_flag(), and parallel_ucd_io_select::sel_write_parallel_ucd_file().
Referenced by fem_analyzer_sph_mhd::fem_analyze_sph_mhd().