CALYPSO: spherical_srs_n Module Reference
spherical_srs_n Module Reference
Arbitrary components data communications
for spherical harmonics transform.
Functions/Subroutines
subroutine send_recv_sph_trans_n (iflag_recv, NB, nnod_send, nnod_recv, send_comm, recv_comm, X_send, X_recv)
subroutine send_recv_sph_trans_6 (iflag_recv, nnod_send, nnod_recv, send_comm, recv_comm, X_send, X_recv)
subroutine send_recv_sph_trans_3 (iflag_recv, nnod_send, nnod_recv, send_comm, recv_comm, X_send, X_recv)
subroutine send_recv_sph_trans_2 (iflag_recv, nnod_send, nnod_recv, send_comm, recv_comm, X_send, X_recv)
subroutine send_recv_sph_trans (iflag_recv, nnod_send, nnod_recv, send_comm, recv_comm, X_send, X_recv)
subroutine send_recv_sph_trans_int (iflag_recv, nnod_send, nnod_recv, send_comm, recv_comm, iX_send, iX_recv)
subroutine check_calypso_sph_comm_buf_n (NB, send_comm, recv_comm)
subroutine calypso_sph_comm_n (NB, send_comm, recv_comm)
subroutine calypso_sph_to_send_n (NB, nnod_org, comm_sph, n_WS, X_org, WS)
subroutine calypso_sph_from_recv_n (iflag_recv, NB, nnod_sph, comm_sph, n_WR, WR, X_sph)
subroutine finish_send_recv_sph (comm_sph)
Detailed Description
Arbitrary components data communications
for spherical harmonics transform.
      subroutine send_recv_sph_trans_N                                &
     &         (iflag_recv, NB, nnod_send, nnod_recv,                 &
     &          send_comm, recv_comm, X_send, X_recv)
      subroutine send_recv_sph_trans_6                                &
     &         (iflag_recv, nnod_send, nnod_recv,                     &
     &          send_comm, recv_comm, X_send, X_recv)
      subroutine send_recv_sph_trans_3                                &
     &         (iflag_recv, nnod_send, nnod_recv,                     &
     &          send_comm, recv_comm, X_send, X_recv)
      subroutine send_recv_sph_trans_2                                &
     &         (iflag_recv, nnod_send, nnod_recv,                     &
     &          send_comm, recv_comm, X_send, X_recv)
      subroutine send_recv_sph_trans                                  &
     &         (iflag_recv, nnod_send, nnod_recv,                     &
     &          send_comm, recv_comm, X_send, X_recv)
      subroutine send_recv_sph_trans_int                              &
     &         (iflag_recv, nnod_send, nnod_recv,                     &
     &          send_comm, recv_comm, iX_send, iX_recv)
      subroutine check_calypso_sph_comm_buf_N(NB, send_comm, recv_comm)
      subroutine calypso_sph_comm_N(NB, send_comm, recv_comm)
      subroutine calypso_sph_to_send_N(NB, nnod_org,                  &
     &          comm_sph, n_WS, X_org, WS)
      subroutine calypso_sph_from_recv_N(iflag_recv, NB, nnod_sph,    &
     &          comm_sph, n_WR, WR, X_sph)
      subroutine finish_send_recv_sph(comm_sph)
        type(sph_comm_tbl), intent(in) :: comm_sph
Parameters
NB Number of components for communication
WR(NB*ntot_recv) Communication buffer for recieving
X_rtp(NB*nnod_rtp) \(f(r,\theta,\phi) \)
(Order, X_rtp(i_comp,inod))
X_rtm(NB*nnod_rtm) \(f(r,\theta,m) \)
(Order, X_rtm(i_comp,inod))
X_rlm(NB*nnod_rlm) \(f(r,l,m) \)
(Order, X_rlm(i_comp,inod))
X_rj(NB*nnod_rj) \(f(r,j) \)
(Order, X_rj(i_comp,inod))
Function/Subroutine Documentation
calypso_sph_comm_n()
subroutine spherical_srs_n::calypso_sph_comm_n (integer (kind=kint), intent(in) NB, type(sph_comm_tbl), intent(in) send_comm, type(sph_comm_tbl), intent(in) recv_comm)
Definition at line 248 of file spherical_SRs_N.f90.
References sel_spherical_srs::sel_calypso_sph_comm_n().
Referenced by t_sph_transforms::pole_b_transform(), send_recv_sph_trans_n(), sph_trans_w_coriols::sph_b_trans_licv(), sph_trans_w_coriols::sph_b_trans_w_coriolis(), t_sph_transforms::sph_b_trans_w_poles(), t_sph_transforms::sph_backward_transforms(), sph_trans_w_coriols::sph_f_trans_licv(), sph_trans_w_coriols::sph_f_trans_w_coriolis(), and t_sph_transforms::sph_forward_transforms().
calypso_sph_from_recv_n()
subroutine spherical_srs_n::calypso_sph_from_recv_n (integer(kind = kint), intent(in) iflag_recv, integer (kind=kint), intent(in) NB, integer (kind=kint), intent(in) nnod_sph, type(sph_comm_tbl), intent(in) comm_sph, integer (kind=kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(inout) WR, real (kind=kreal), dimension(nb*nnod_sph), intent(inout) X_sph)
Definition at line 290 of file spherical_SRs_N.f90.
References sel_spherical_srs::sel_calypso_from_recv_n().
Referenced by send_recv_sph_trans_n().
calypso_sph_to_send_n()
subroutine spherical_srs_n::calypso_sph_to_send_n (integer (kind=kint), intent(in) NB, integer (kind=kint), intent(in) nnod_org, type(sph_comm_tbl), intent(in) comm_sph, integer (kind=kint), intent(in) n_WS, real (kind=kreal), dimension(nb*nnod_org), intent(in) X_org, real (kind=kreal), dimension(nb*comm_sph%ntot_item_sr), intent(inout) WS)
Definition at line 267 of file spherical_SRs_N.f90.
References m_work_time::end_elapsed_time(), m_elapsed_labels_send_recv::iflag_csr_time, m_elapsed_labels_send_recv::ist_elapsed_csr, set_to_send_buffer::set_to_send_buf_n(), and m_work_time::start_elapsed_time().
Referenced by send_recv_sph_trans_n().
check_calypso_sph_comm_buf_n()
subroutine spherical_srs_n::check_calypso_sph_comm_buf_n (integer (kind=kint), intent(in) NB, type(sph_comm_tbl), intent(in) send_comm, type(sph_comm_tbl), intent(in) recv_comm)
Definition at line 232 of file spherical_SRs_N.f90.
References sel_spherical_srs::check_calypso_sph_buf_n().
Referenced by send_recv_sph_trans_n(), sph_transforms_4_mhd::sph_back_trans_4_mhd(), sph_transforms_snapshot::sph_back_trans_snapshot_mhd(), sph_transforms_4_mhd::sph_forward_trans_4_mhd(), sph_transforms_snapshot::sph_forward_trans_snapshot_mhd(), sph_transforms_4_mhd::sph_pole_trans_4_mhd(), and sph_transforms_4_mhd::sph_transform_4_licv().
finish_send_recv_sph()
subroutine spherical_srs_n::finish_send_recv_sph (type(sph_comm_tbl), intent(in) comm_sph)
Definition at line 311 of file spherical_SRs_N.f90.
References t_solver_sr::calypso_send_recv_fin(), and m_solver_sr::sr_sig1.
Referenced by t_sph_transforms::pole_b_transform(), send_recv_sph_trans_n(), sph_trans_w_coriols::sph_b_trans_licv(), sph_trans_w_coriols::sph_b_trans_w_coriolis(), t_sph_transforms::sph_b_trans_w_poles(), t_sph_transforms::sph_backward_transforms(), sph_trans_w_coriols::sph_f_trans_licv(), sph_trans_w_coriols::sph_f_trans_w_coriolis(), and t_sph_transforms::sph_forward_transforms().
send_recv_sph_trans()
subroutine spherical_srs_n::send_recv_sph_trans (integer(kind = kint), intent(in) iflag_recv, integer (kind=kint), intent(in) nnod_send, integer (kind=kint), intent(in) nnod_recv, type(sph_comm_tbl), intent(in) send_comm, type(sph_comm_tbl), intent(in) recv_comm, real (kind=kreal), dimension(nnod_send), intent(in) X_send, real (kind=kreal), dimension(nnod_recv), intent(inout) X_recv)
Definition at line 179 of file spherical_SRs_N.f90.
References calypso_sr::calypso_send_recv(), m_solver_sr::sr_r1, and m_solver_sr::sr_sig1.
Referenced by cmp_trans_sph_tests::sph_transfer_test_1().
send_recv_sph_trans_2()
subroutine spherical_srs_n::send_recv_sph_trans_2 (integer(kind = kint), intent(in) iflag_recv, integer (kind=kint), intent(in) nnod_send, integer (kind=kint), intent(in) nnod_recv, type(sph_comm_tbl), intent(in) send_comm, type(sph_comm_tbl), intent(in) recv_comm, real (kind=kreal), dimension(ithree*nnod_send), intent(in) X_send, real (kind=kreal), dimension(ithree*nnod_recv), intent(inout) X_recv)
Definition at line 153 of file spherical_SRs_N.f90.
References calypso_sr_2::calypso_send_recv_2(), m_constants::ithree, m_solver_sr::sr_r1, and m_solver_sr::sr_sig1.
Referenced by cmp_trans_sph_tests::sph_transfer_test_2().
send_recv_sph_trans_3()
subroutine spherical_srs_n::send_recv_sph_trans_3 (integer(kind = kint), intent(in) iflag_recv, integer (kind=kint), intent(in) nnod_send, integer (kind=kint), intent(in) nnod_recv, type(sph_comm_tbl), intent(in) send_comm, type(sph_comm_tbl), intent(in) recv_comm, real (kind=kreal), dimension(ithree*nnod_send), intent(in) X_send, real (kind=kreal), dimension(ithree*nnod_recv), intent(inout) X_recv)
Definition at line 127 of file spherical_SRs_N.f90.
References calypso_sr_3::calypso_send_recv_3(), m_constants::ithree, m_solver_sr::sr_r1, and m_solver_sr::sr_sig1.
Referenced by cmp_trans_sph_tests::sph_transfer_test_3().
send_recv_sph_trans_6()
subroutine spherical_srs_n::send_recv_sph_trans_6 (integer(kind = kint), intent(in) iflag_recv, integer (kind=kint), intent(in) nnod_send, integer (kind=kint), intent(in) nnod_recv, type(sph_comm_tbl), intent(in) send_comm, type(sph_comm_tbl), intent(in) recv_comm, real (kind=kreal), dimension(isix*nnod_send), intent(in) X_send, real (kind=kreal), dimension(isix*nnod_recv), intent(inout) X_recv)
Definition at line 101 of file spherical_SRs_N.f90.
References calypso_sr_6::calypso_send_recv_6(), m_constants::isix, m_solver_sr::sr_r1, and m_solver_sr::sr_sig1.
Referenced by cmp_trans_sph_tests::sph_transfer_test_6().
send_recv_sph_trans_int()
subroutine spherical_srs_n::send_recv_sph_trans_int (integer(kind = kint), intent(in) iflag_recv, integer (kind=kint), intent(in) nnod_send, integer (kind=kint), intent(in) nnod_recv, type(sph_comm_tbl), intent(in) send_comm, type(sph_comm_tbl), intent(in) recv_comm, integer (kind=kint), dimension(nnod_send), intent(in) iX_send, integer (kind=kint), dimension(nnod_recv), intent(inout) iX_recv)
Definition at line 205 of file spherical_SRs_N.f90.
References calypso_sr_int::calypso_send_recv_int(), m_solver_sr::sr_i1, and m_solver_sr::sr_sig1.
Referenced by cmp_trans_sph_indices::sph_indices_transfer().
send_recv_sph_trans_n()
subroutine spherical_srs_n::send_recv_sph_trans_n (integer(kind = kint), intent(in) iflag_recv, integer (kind=kint), intent(in) NB, integer (kind=kint), intent(in) nnod_send, integer (kind=kint), intent(in) nnod_recv, type(sph_comm_tbl), intent(in) send_comm, type(sph_comm_tbl), intent(in) recv_comm, real (kind=kreal), dimension(nb*nnod_send), intent(in) X_send, real (kind=kreal), dimension(nb*nnod_recv), intent(inout) X_recv)
Definition at line 72 of file spherical_SRs_N.f90.
References calypso_sph_comm_n(), calypso_sph_from_recv_n(), calypso_sph_to_send_n(), check_calypso_sph_comm_buf_n(), finish_send_recv_sph(), and m_solver_sr::sr_r1.
Referenced by cmp_trans_sph_tests::sph_transfer_test_n().