CALYPSO: gz_mpi_sph_gl_1d_idx_io Module Reference
gz_mpi_sph_gl_1d_idx_io Module Reference
Mesh file IO for gxipped format.
Functions/Subroutines
subroutine gz_mpi_read_rtp_gl_1d_table (IO_param, sph_IO)
subroutine gz_mpi_read_rj_gl_1d_table (IO_param, sph_IO)
subroutine gz_mpi_write_rtp_gl_1d_table (IO_param, sph_IO)
subroutine gz_mpi_write_rj_gl_1d_table (IO_param, sph_IO)
subroutine, private gz_mpi_read_1d_gl_address (IO_param, nnod, numdir, idx)
subroutine, private gz_mpi_write_1d_gl_address (IO_param, nnod, numdir, idx)
Variables
type(buffer_4_gzip) zbuf
Detailed Description
Mesh file IO for gxipped format.
      subroutine gz_mpi_read_rtp_gl_1d_table(IO_param, sph_IO)
      subroutine gz_mpi_read_rj_gl_1d_table(IO_param, sph_IO)
      subroutine gz_mpi_write_rtp_gl_1d_table(IO_param, sph_IO)
      subroutine gz_mpi_write_rj_gl_1d_table(IO_param, sph_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(sph_IO_data), intent(in) :: sph_IO
Function/Subroutine Documentation
gz_mpi_read_1d_gl_address()
subroutine, private gz_mpi_sph_gl_1d_idx_io::gz_mpi_read_1d_gl_address (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint), intent(in) nnod, integer(kind = kint), intent(in) numdir, integer(kind = kint), dimension(nnod, numdir), intent(inout) idx) private
Definition at line 204 of file gz_MPI_sph_gl_1d_idx_IO.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), gz_mpi_ascii_data_io::gz_mpi_read_charahead(), zlib_cvt_ascii_ele_connect::infleate_1d_global_address(), and gz_mpi_domain_data_io::zbuf.
Referenced by gz_mpi_read_rj_gl_1d_table(), and gz_mpi_read_rtp_gl_1d_table().
gz_mpi_read_rj_gl_1d_table()
subroutine gz_mpi_sph_gl_1d_idx_io::gz_mpi_read_rj_gl_1d_table (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(inout) sph_IO)
Definition at line 93 of file gz_MPI_sph_gl_1d_idx_IO.f90.
References t_node_id_spherical_io::alloc_idx_sph_1d1_io(), t_node_id_spherical_io::alloc_idx_sph_1d2_io(), t_node_id_spherical_io::alloc_num_idx_sph_io(), gz_mpi_read_1d_gl_address(), gz_mpi_ascii_data_io::gz_mpi_read_num_of_data(), gz_mpi_position_io::gz_mpi_read_radial_position(), gz_mpi_ascii_data_io::gz_mpi_skip_header(), m_sph_modes_grid_labels::hd_jmode(), and m_sph_modes_grid_labels::hd_rgrid().
Referenced by gz_mpi_sph_modes_data_io::gz_mpi_read_modes_rlm_data(), and gz_mpi_sph_modes_data_io::gz_mpi_read_spectr_rj_data().
gz_mpi_read_rtp_gl_1d_table()
subroutine gz_mpi_sph_gl_1d_idx_io::gz_mpi_read_rtp_gl_1d_table (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(inout) sph_IO)
Definition at line 45 of file gz_MPI_sph_gl_1d_idx_IO.f90.
References t_node_id_spherical_io::alloc_idx_sph_1d1_io(), t_node_id_spherical_io::alloc_idx_sph_1d2_io(), t_node_id_spherical_io::alloc_idx_sph_1d3_io(), t_node_id_spherical_io::alloc_num_idx_sph_io(), gz_mpi_read_1d_gl_address(), gz_mpi_ascii_data_io::gz_mpi_read_num_of_data(), gz_mpi_position_io::gz_mpi_read_radial_position(), gz_mpi_ascii_data_io::gz_mpi_skip_header(), m_sph_modes_grid_labels::hd_pgrid(), m_sph_modes_grid_labels::hd_rgrid(), and m_sph_modes_grid_labels::hd_tgrid().
Referenced by gz_mpi_sph_modes_data_io::gz_mpi_read_geom_rtm_data(), and gz_mpi_sph_modes_data_io::gz_mpi_read_geom_rtp_data().
gz_mpi_write_1d_gl_address()
subroutine, private gz_mpi_sph_gl_1d_idx_io::gz_mpi_write_1d_gl_address (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) nnod, integer(kind=kint), intent(in) numdir, integer(kind=kint), dimension(nnod, numdir), intent(in) idx) private
Definition at line 243 of file gz_MPI_sph_gl_1d_idx_IO.f90.
References t_buffer_4_gzip::dealloc_zip_buffer(), zlib_cvt_ascii_ele_connect::defleate_1d_global_address(), gz_mpi_ascii_data_io::gz_mpi_write_num_of_data(), gz_mpi_ascii_data_io::gz_mpi_write_stack_over_domain(), and gz_mpi_domain_data_io::zbuf.
Referenced by gz_mpi_write_rj_gl_1d_table(), and gz_mpi_write_rtp_gl_1d_table().
gz_mpi_write_rj_gl_1d_table()
subroutine gz_mpi_sph_gl_1d_idx_io::gz_mpi_write_rj_gl_1d_table (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(in) sph_IO)
Definition at line 173 of file gz_MPI_sph_gl_1d_idx_IO.f90.
References gz_mpi_write_1d_gl_address(), gz_mpi_ascii_data_io::gz_mpi_write_charahead(), gz_mpi_ascii_data_io::gz_mpi_write_num_of_data(), gz_mpi_position_io::gz_mpi_write_radial_position(), m_sph_modes_grid_labels::hd_jmode(), and m_sph_modes_grid_labels::hd_rgrid().
Referenced by gz_mpi_sph_modes_data_io::gz_mpi_write_modes_rlm_data(), and gz_mpi_sph_modes_data_io::gz_mpi_write_spectr_rj_data().
gz_mpi_write_rtp_gl_1d_table()
subroutine gz_mpi_sph_gl_1d_idx_io::gz_mpi_write_rtp_gl_1d_table (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(in) sph_IO)
Definition at line 131 of file gz_MPI_sph_gl_1d_idx_IO.f90.
References gz_mpi_write_1d_gl_address(), gz_mpi_ascii_data_io::gz_mpi_write_charahead(), gz_mpi_ascii_data_io::gz_mpi_write_num_of_data(), gz_mpi_position_io::gz_mpi_write_radial_position(), m_sph_modes_grid_labels::hd_pgrid(), m_sph_modes_grid_labels::hd_rgrid(), and m_sph_modes_grid_labels::hd_tgrid().
Referenced by gz_mpi_sph_modes_data_io::gz_mpi_write_geom_rtm_data(), and gz_mpi_sph_modes_data_io::gz_mpi_write_geom_rtp_data().
Variable Documentation
zbuf
type(buffer_4_gzip) gz_mpi_sph_gl_1d_idx_io::zbuf
Definition at line 35 of file gz_MPI_sph_gl_1d_idx_IO.f90.