CALYPSO: pickup_sph_coefs Module Reference
pickup_sph_coefs Module Reference
Pick spectr data to output.
Functions/Subroutines
subroutine init_sph_radial_monitor_list (sph_rj, picked, iflag_center)
subroutine count_sph_labels_4_monitor (num_phys_rj, num_phys_comp_rj, flag_monitor_rj, picked)
subroutine set_sph_fld_id_4_monitor (num_phys_rj, num_phys_comp_rj, flag_monitor_rj, picked)
subroutine set_sph_labels_4_monitor (num_phys_rj, num_phys_comp_rj, phys_name_rj, picked)
Detailed Description
Pick spectr data to output.
      subroutine init_sph_radial_monitor_list                         &
     &         (sph_rj, picked, iflag_center)
      subroutine count_sph_labels_4_monitor                           &
     &       (num_phys_rj, num_phys_comp_rj, flag_monitor_rj, picked)
      subroutine set_sph_fld_id_4_monitor                             &
     &       (num_phys_rj, num_phys_comp_rj, flag_monitor_rj, picked)
      subroutine set_sph_labels_4_monitor                             &
     &        (num_phys_rj, num_phys_comp_rj, phys_name_rj, picked)
Function/Subroutine Documentation
count_sph_labels_4_monitor()
subroutine pickup_sph_coefs::count_sph_labels_4_monitor (integer(kind = kint), intent(in) num_phys_rj, integer(kind = kint), dimension(num_phys_rj), intent(in) num_phys_comp_rj, logical, dimension(num_phys_rj), intent(in) flag_monitor_rj, type(picked_spectrum_data), intent(inout) picked)
Definition at line 81 of file pickup_sph_coefs.f90.
Referenced by pickup_sph_spectr_data::init_sph_spec_4_monitor().
init_sph_radial_monitor_list()
subroutine pickup_sph_coefs::init_sph_radial_monitor_list (type(sph_rj_grid), intent(in) sph_rj, type(picked_spectrum_data), intent(inout) picked, integer(kind = kint), intent(inout) iflag_center)
Definition at line 38 of file pickup_sph_coefs.f90.
References t_pickup_sph_spectr_data::alloc_num_pick_layer(), m_constants::ione, and quicksort::quicksort_int().
Referenced by pickup_sph_spectr_data::init_sph_spec_4_monitor().
set_sph_fld_id_4_monitor()
subroutine pickup_sph_coefs::set_sph_fld_id_4_monitor (integer(kind = kint), intent(in) num_phys_rj, integer(kind = kint), dimension(num_phys_rj), intent(in) num_phys_comp_rj, logical, dimension(num_phys_rj), intent(in) flag_monitor_rj, type(picked_spectrum_data), intent(inout) picked)
Definition at line 107 of file pickup_sph_coefs.f90.
Referenced by pickup_sph_spectr_data::init_sph_spec_4_monitor().
set_sph_labels_4_monitor()
subroutine pickup_sph_coefs::set_sph_labels_4_monitor (integer(kind = kint), intent(in) num_phys_rj, integer(kind = kint), dimension(num_phys_rj), intent(in) num_phys_comp_rj, character(len=kchara), dimension(num_phys_rj), intent(in) phys_name_rj, type(picked_spectrum_data), intent(inout) picked)
Definition at line 134 of file pickup_sph_coefs.f90.
References add_direction_labels::add_tensor_direction_label_rtp(), and add_direction_labels::add_vector_sph_spectr_label().
Referenced by pickup_sph_spectr_data::init_sph_spec_4_monitor().