CALYPSO: element_mesh_io_select Module Reference
element_mesh_io_select Module Reference
Choose mesh file to read.
Functions/Subroutines
subroutine sel_read_ele_mesh (mesh_file, id_rank, ele_mesh_IO, ierr)
subroutine sel_read_surf_mesh (mesh_file, id_rank, surf_mesh_IO, ierr)
subroutine sel_read_edge_mesh (mesh_file, id_rank, edge_mesh_IO, ierr)
subroutine sel_write_ele_mesh_file (mesh_file, id_rank, ele_mesh_IO)
subroutine sel_write_surf_mesh_file (mesh_file, id_rank, surf_mesh_IO)
subroutine sel_write_edge_mesh_file (mesh_file, id_rank, edge_mesh_IO)
Variables
character(len=kchara), private file_name
Detailed Description
Choose mesh file to read.
      subroutine sel_read_ele_mesh                                    &
     &         (mesh_file, id_rank, ele_mesh_IO, ierr)
      subroutine sel_read_surf_mesh                                   &
     &         (mesh_file, id_rank, surf_mesh_IO, ierr)
      subroutine sel_read_edge_mesh                                   &
     &         (mesh_file, id_rank, edge_mesh_IO, ierr)
        type(surf_edge_IO_file), intent(inout) :: ele_mesh_IO
        type(surf_edge_IO_file), intent(inout) :: surf_mesh_IO
        type(surf_edge_IO_file), intent(inout) :: edge_mesh_IO
      subroutine sel_write_ele_mesh_file                              &
     &         (mesh_file, id_rank, ele_mesh_IO)
      subroutine sel_write_surf_mesh_file                             &
     &         (mesh_file, id_rank, surf_mesh_IO)
      subroutine sel_write_edge_mesh_file                             &
     &         (mesh_file, id_rank, edge_mesh_IO)
        type(surf_edge_IO_file), intent(in) :: ele_mesh_IO
        type(surf_edge_IO_file), intent(in) :: surf_mesh_IO
        type(surf_edge_IO_file), intent(in) :: edge_mesh_IO
Function/Subroutine Documentation
sel_read_edge_mesh()
subroutine element_mesh_io_select::sel_read_edge_mesh (type(field_io_params), intent(in) mesh_file, integer, intent(in) id_rank, type(surf_edge_io_file), intent(inout) edge_mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 131 of file element_mesh_IO_select.F90.
References file_name, gz_element_file_io::gz_input_edge_file(), gz_element_file_io_b::gz_input_edge_file_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, element_file_io::input_edge_file(), element_file_io_b::input_edge_file_b(), and set_mesh_file_names::set_edge_mesh_file_name().
Referenced by element_mesh_mpi_io_select::sel_mpi_read_edge_mesh().
sel_read_ele_mesh()
subroutine element_mesh_io_select::sel_read_ele_mesh (type(field_io_params), intent(in) mesh_file, integer, intent(in) id_rank, type(surf_edge_io_file), intent(inout) ele_mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 57 of file element_mesh_IO_select.F90.
References file_name, gz_element_file_io::gz_input_element_file(), gz_element_file_io_b::gz_input_element_file_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, element_file_io::input_element_file(), element_file_io_b::input_element_file_b(), and set_mesh_file_names::set_ele_comm_file_name().
Referenced by element_mesh_mpi_io_select::sel_mpi_read_ele_mesh().
sel_read_surf_mesh()
subroutine element_mesh_io_select::sel_read_surf_mesh (type(field_io_params), intent(in) mesh_file, integer, intent(in) id_rank, type(surf_edge_io_file), intent(inout) surf_mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 94 of file element_mesh_IO_select.F90.
References file_name, gz_element_file_io::gz_input_surface_file(), gz_element_file_io_b::gz_input_surface_file_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, element_file_io::input_surface_file(), element_file_io_b::input_surface_file_b(), and set_mesh_file_names::set_surf_mesh_file_name().
Referenced by element_mesh_mpi_io_select::sel_mpi_read_surf_mesh().
sel_write_edge_mesh_file()
subroutine element_mesh_io_select::sel_write_edge_mesh_file (type(field_io_params), intent(in) mesh_file, integer, intent(in) id_rank, type(surf_edge_io_file), intent(in) edge_mesh_IO)
Definition at line 243 of file element_mesh_IO_select.F90.
References file_name, gz_element_file_io::gz_output_edge_file(), gz_element_file_io_b::gz_output_edge_file_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, element_file_io::output_edge_file(), element_file_io_b::output_edge_file_b(), and set_mesh_file_names::set_edge_mesh_file_name().
Referenced by element_mesh_mpi_io_select::sel_mpi_write_edge_mesh_file().
sel_write_ele_mesh_file()
subroutine element_mesh_io_select::sel_write_ele_mesh_file (type(field_io_params), intent(in) mesh_file, integer, intent(in) id_rank, type(surf_edge_io_file), intent(in) ele_mesh_IO)
Definition at line 169 of file element_mesh_IO_select.F90.
References file_name, gz_element_file_io::gz_output_element_file(), gz_element_file_io_b::gz_output_element_file_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, element_file_io::output_element_file(), element_file_io_b::output_element_file_b(), and set_mesh_file_names::set_ele_comm_file_name().
Referenced by element_mesh_mpi_io_select::sel_mpi_write_ele_mesh_file().
sel_write_surf_mesh_file()
subroutine element_mesh_io_select::sel_write_surf_mesh_file (type(field_io_params), intent(in) mesh_file, integer, intent(in) id_rank, type(surf_edge_io_file), intent(in) surf_mesh_IO)
Definition at line 206 of file element_mesh_IO_select.F90.
References file_name, gz_element_file_io::gz_output_surface_file(), gz_element_file_io_b::gz_output_surface_file_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, element_file_io::output_surface_file(), element_file_io_b::output_surface_file_b(), and set_mesh_file_names::set_surf_mesh_file_name().
Referenced by element_mesh_mpi_io_select::sel_mpi_write_surf_mesh_file().
Variable Documentation
file_name
character(len=kchara), private element_mesh_io_select::file_name private
Definition at line 49 of file element_mesh_IO_select.F90.
Referenced by sel_read_edge_mesh(), sel_read_ele_mesh(), sel_read_surf_mesh(), sel_write_edge_mesh_file(), sel_write_ele_mesh_file(), and sel_write_surf_mesh_file().