CALYPSO: field_file_io Module Reference
field_file_io Module Reference
Rountines for field file IO.
Functions/Subroutines
subroutine write_step_field_file (file_name, id_rank, t_IO, fld_IO)
subroutine read_and_allocate_field_file (file_name, id_rank, fld_IO)
subroutine read_step_field_file (file_name, id_rank, t_IO, fld_IO)
subroutine read_and_alloc_step_field (file_name, id_rank, t_IO, fld_IO)
subroutine read_and_allocate_step_head (file_name, id_rank, t_IO, fld_IO)
Detailed Description
Rountines for field file IO.
      subroutine write_step_field_file                                &
     &         (file_name, id_rank, t_IO, fld_IO)
        type(time_data), intent(in) :: t_IO
        type(field_IO), intent(in) :: fld_IO
      subroutine read_and_allocate_field_file                         &
     &         (file_name, id_rank, fld_IO)
      subroutine read_step_field_file                                 &
     &         (file_name, id_rank, t_IO, fld_IO)
      subroutine read_and_alloc_step_field                            &
     &         (file_name, id_rank, t_IO, fld_IO)
        type(time_data), intent(inout) :: t_IO
        type(field_IO), intent(inout) :: fld_IO
      subroutine read_and_allocate_step_head                          &
     &         (file_name, id_rank, t_IO, fld_IO)
        type(time_data), intent(inout) :: t_IO
        type(field_IO), intent(inout) :: fld_IO
Function/Subroutine Documentation
read_and_alloc_step_field()
subroutine field_file_io::read_and_alloc_step_field (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO)
Definition at line 155 of file field_file_IO.f90.
References t_field_data_io::alloc_phys_data_io(), t_field_data_io::alloc_phys_name_io(), t_field_data_io::cal_istack_phys_comp_io(), transfer_to_long_integers::cast_long(), m_machine_parameter::i_debug, t_field_data_io::id_phys_file, field_data_io::read_field_data(), time_data_io::read_step_data(), and skip_comment_f::skip_comment().
Referenced by field_io_select::sel_read_alloc_step_field_file().
read_and_allocate_field_file()
subroutine field_file_io::read_and_allocate_field_file (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(field_io), intent(inout) fld_IO)
Definition at line 81 of file field_file_IO.f90.
References t_field_data_io::alloc_phys_data_io(), t_field_data_io::alloc_phys_name_io(), t_field_data_io::cal_istack_phys_comp_io(), transfer_to_long_integers::cast_long(), m_machine_parameter::i_debug, t_field_data_io::id_phys_file, field_data_io::read_field_data(), and skip_comment_f::skip_comment().
Referenced by input_old_file_sel_4_zlib::sel_read_alloc_field_file().
read_and_allocate_step_head()
subroutine field_file_io::read_and_allocate_step_head (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO)
Definition at line 196 of file field_file_IO.f90.
References t_field_data_io::alloc_phys_name_io(), t_field_data_io::cal_istack_phys_comp_io(), transfer_to_long_integers::cast_long(), m_machine_parameter::i_debug, t_field_data_io::id_phys_file, field_data_io::read_field_name(), time_data_io::read_step_data(), and skip_comment_f::skip_comment().
Referenced by field_io_select::sel_read_alloc_field_head().
read_step_field_file()
subroutine field_file_io::read_step_field_file (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO)
Definition at line 119 of file field_file_IO.f90.
References transfer_to_long_integers::cast_long(), m_machine_parameter::i_debug, t_field_data_io::id_phys_file, field_data_io::read_field_data(), time_data_io::read_step_data(), and skip_comment_f::skip_comment().
Referenced by field_io_select::sel_read_step_field_file().
write_step_field_file()
subroutine field_file_io::write_step_field_file (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(time_data), intent(in) t_IO, type(field_io), intent(in) fld_IO)
Definition at line 51 of file field_file_IO.f90.
References transfer_to_long_integers::cast_long(), m_machine_parameter::i_debug, t_field_data_io::id_phys_file, field_data_io::write_field_data(), and time_data_io::write_step_data().
Referenced by field_io_select::sel_write_step_field_file().