CALYPSO: sph_mean_spectr_io Module Reference
sph_mean_spectr_io Module Reference
Mean sqare data.
Functions/Subroutines
integer(kind=kint) function check_sph_vol_mean_sq_file (id_file, fname_rms, mode_label, ene_labels, sph_params, sph_rj, v_pwr)
subroutine open_sph_vol_mean_sq_file (id_file, fname_rms, mode_label, ene_labels, sph_params, sph_rj, v_pwr)
subroutine open_sph_mean_sq_file (id_file, fname_rms, mode_label, ltr, nlayer_ICB, nlayer_CMB, ene_labels, pwr)
subroutine write_sph_volume_data (id_file, time_d, ltr, ntot_rms_rj, rms_sph_x)
subroutine write_sph_layerd_power (id_file, time_d, pwr, rms_sph)
subroutine write_sph_layer_data (id_file, time_d, ltr, pwr, rms_sph_x)
Detailed Description
Mean sqare data.
      integer(kind = kint) function check_sph_vol_mean_sq_file        &
     &                   (id_file, fname_rms, mode_label,             &
     &                    ene_labels, sph_params, sph_rj, v_pwr)
      subroutine open_sph_vol_mean_sq_file(id_file, fname_rms,        &
     &          mode_label, ene_labels, sph_params, sph_rj, v_pwr)
      subroutine open_sph_mean_sq_file(id_file, fname_rms, mode_label,&
     &          ltr, nlayer_ICB, nlayer_CMB, ene_labels, pwr)
        type(energy_label_param), intent(in) :: ene_labels
        type(sph_shell_parameters), intent(in) :: sph_params
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(sph_vol_mean_squares), intent(in) :: v_pwr
        type(sph_mean_squares), intent(in) :: pwr
      subroutine write_sph_volume_data                                &
     &         (id_file, time_d, ltr, ntot_rms_rj, rms_sph_x)
      subroutine write_sph_layerd_power(id_file, time_d, pwr, rms_sph)
      subroutine write_sph_layer_data                                 &
     &         (id_file, time_d, ltr, pwr, rms_sph_x)
        type(time_data), intent(in) :: time_d
        type(sph_mean_squares), intent(in) :: pwr
Parameters
istep time step number
time time
Parameters
id_file file ID for output
fname_rms file name for output
mode_label data label for degree or order of harmonics
Function/Subroutine Documentation
check_sph_vol_mean_sq_file()
integer(kind = kint) function sph_mean_spectr_io::check_sph_vol_mean_sq_file (integer(kind = kint), intent(in) id_file, character(len = kchara), intent(in) fname_rms, character(len = kchara), intent(in) mode_label, type(energy_label_param), intent(in) ene_labels, type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(sph_vol_mean_squares), intent(in) v_pwr)
Definition at line 56 of file sph_mean_spectr_IO.f90.
References sph_mean_spectr_header_io::check_sph_vol_mean_sq_header().
Referenced by output_sph_m_square_file::check_sph_vol_ms_file().
open_sph_mean_sq_file()
subroutine sph_mean_spectr_io::open_sph_mean_sq_file (integer(kind = kint), intent(in) id_file, character(len = kchara), intent(in) fname_rms, character(len = kchara), intent(in) mode_label, integer(kind = kint), intent(in) ltr, integer(kind = kint), intent(in) nlayer_ICB, integer(kind = kint), intent(in) nlayer_CMB, type(energy_label_param), intent(in) ene_labels, type(sph_mean_squares), intent(in) pwr)
Definition at line 117 of file sph_mean_spectr_IO.f90.
References sph_mean_spectr_header_io::write_sph_mean_sq_header().
Referenced by output_sph_m_square_file::write_sph_layer_pwr_file(), and output_sph_m_square_file::write_sph_layer_spec_file().
open_sph_vol_mean_sq_file()
subroutine sph_mean_spectr_io::open_sph_vol_mean_sq_file (integer(kind = kint), intent(in) id_file, character(len = kchara), intent(in) fname_rms, character(len = kchara), intent(in) mode_label, type(energy_label_param), intent(in) ene_labels, type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(sph_vol_mean_squares), intent(in) v_pwr)
Definition at line 90 of file sph_mean_spectr_IO.f90.
References sph_mean_spectr_header_io::write_sph_vol_mean_sq_header().
Referenced by output_sph_m_square_file::write_sph_vol_ave_file(), output_sph_m_square_file::write_sph_volume_pwr_file(), and output_sph_m_square_file::write_sph_volume_spec_file().
write_sph_layer_data()
subroutine sph_mean_spectr_io::write_sph_layer_data (integer(kind = kint), intent(in) id_file, type(time_data), intent(in) time_d, integer(kind = kint), intent(in) ltr, type(sph_mean_squares), intent(in) pwr, real(kind = kreal), dimension(pwr%nri_rms,0:ltr,pwr%ntot_comp_sq), intent(in) rms_sph_x)
Definition at line 195 of file sph_mean_spectr_IO.f90.
Referenced by output_sph_m_square_file::write_sph_layer_spec_file().
write_sph_layerd_power()
subroutine sph_mean_spectr_io::write_sph_layerd_power (integer(kind = kint), intent(in) id_file, type(time_data), intent(in) time_d, type(sph_mean_squares), intent(in) pwr, real(kind = kreal), dimension(pwr%nri_rms,pwr%ntot_comp_sq), intent(in) rms_sph)
Definition at line 170 of file sph_mean_spectr_IO.f90.
Referenced by output_sph_m_square_file::write_sph_layer_pwr_file().
write_sph_volume_data()
subroutine sph_mean_spectr_io::write_sph_volume_data (integer(kind = kint), intent(in) id_file, type(time_data), intent(in) time_d, integer(kind = kint), intent(in) ltr, integer(kind = kint), intent(in) ntot_rms_rj, real(kind = kreal), dimension(0:ltr, ntot_rms_rj), intent(in) rms_sph_x)
Definition at line 145 of file sph_mean_spectr_IO.f90.
Referenced by output_sph_m_square_file::write_sph_volume_spec_file().