CALYPSO: mhd_fft_selector Module Reference
mhd_fft_selector Module Reference
Selector of Fourier transform.
Functions/Subroutines
subroutine init_mhd_fft_select (id_rank, sph_rtp, ncomp, ncomp_fwd, ncomp_bwd, MHD_mul_FFTW)
subroutine finalize_mhd_fft_select (MHD_mul_FFTW)
subroutine verify_mhd_fft_select (id_rank, sph_rtp, ncomp, ncomp_fwd, ncomp_bwd, MHD_mul_FFTW)
subroutine fwd_mhd_fft_sel_to_send (sph_rtp, comm_rtp, ncomp_fwd, n_WS, trns_fwd, WS, WK_FFTs, MHD_mul_FFTW)
subroutine back_mhd_fft_sel_from_recv (sph_rtp, comm_rtp, ncomp_bwd, n_WR, WR, fld_rtp, WK_FFTs, MHD_mul_FFTW)
Detailed Description
Selector of Fourier transform.
      subroutine init_MHD_FFT_select(id_rank, sph_rtp,                &
     &          ncomp, ncomp_fwd, ncomp_bwd, MHD_mul_FFTW)
      subroutine verify_MHD_FFT_select(id_rank, sph_rtp,              &
     &          ncomp, ncomp_fwd, ncomp_bwd, MHD_mul_FFTW)
      subroutine finalize_MHD_FFT_select(MHD_mul_FFTW)
      subroutine verify_MHD_FFT_select                                &
     &         (sph_rtp, ncomp, ncomp_fwd, ncomp_bwd, MHD_mul_FFTW)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(work_for_sgl_FFTW), intent(inout) :: MHD_mul_FFTW
 ------------------------------------------------------------------
   wrapper subroutine for initierize FFT for ISPACK
 ------------------------------------------------------------------
      subroutine fwd_MHD_FFT_sel_to_send(sph_rtp, comm_rtp,           &
     &          ncomp_fwd, n_WS, trns_fwd, WS, WK_FFTs, MHD_mul_FFTW)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_comm_tbl), intent(in)  :: comm_rtp
        type(work_for_FFTs), intent(inout) :: WK_FFTs
        type(work_for_sgl_FFTW), intent(inout) :: MHD_mul_FFTW
        type(spherical_transform_data), intent(inout) :: trns_fwd
 ------------------------------------------------------------------
   wrapper subroutine for FFT in ISPACK
   a_{k} = \frac{2}{Nfft} \sum_{j=0}^{Nfft-1} x_{j} \cos (\frac{2\pi j k}{Nfft})
   b_{k} = \frac{2}{Nfft} \sum_{j=0}^{Nfft-1} x_{j} \cos (\frac{2\pi j k}{Nfft})
   a_{0} = \frac{1}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
    K = Nfft/2....
   a_{k} = \frac{1}{Nfft} \sum_{j=0}^{Nfft-1} x_{j} \cos (\frac{2\pi j k}{Nfft})
 ------------------------------------------------------------------
      subroutine back_MHD_FFT_sel_from_recv(sph_rtp, comm_rtp,        &
     &         ncomp_bwd, n_WR, WR, fld_rtp, WK_FFTs, MHD_mul_FFTW)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_comm_tbl), intent(in)  :: comm_rtp
        type(work_for_FFTs), intent(inout) :: WK_FFTs
        type(work_for_sgl_FFTW), intent(inout) :: MHD_mul_FFTW
 ------------------------------------------------------------------
   wrapper subroutine for backward FFT
   x_{k} = a_{0} + (-1)^{j} a_{Nfft/2} + sum_{k=1}^{Nfft/2-1}
          (a_{k} \cos(2\pijk/Nfft) + b_{k} \sin(2\pijk/Nfft))
 ------------------------------------------------------------------
       i = 1:     a_{0}
       i = 2:     a_{Nfft/2}
       i = 3:     a_{1}
       i = 4:     b_{1}
       ...
       i = 2*k+1: a_{k}
       i = 2*k+2: b_{k}
       ...
       i = Nfft-1:   a_{Nfft/2-1}
       i = Nfft:     b_{Nfft/2-1}
 ------------------------------------------------------------------
Parameters
id_rank Procdess ID
Nsmp Number of SMP processors
Nstacksmp(0:Nsmp) End number for each SMP process
M Number of components for Fourier transforms
Nfft Data length for eadh FFT
X(M,Nfft) Data for Fourier transform
Function/Subroutine Documentation
back_mhd_fft_sel_from_recv()
subroutine mhd_fft_selector::back_mhd_fft_sel_from_recv (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), intent(in) n_WR, real(kind=kreal), dimension(n_wr), intent(inout) WR, real(kind=kreal), dimension(sph_rtp%nnod_rtp,ncomp_bwd), intent(inout) fld_rtp, type(work_for_ffts), intent(inout) WK_FFTs, type(work_for_sgl_fftw), intent(inout) MHD_mul_FFTW)
Definition at line 225 of file MHD_FFT_selector.F90.
References m_fft_selector::iflag_fft, m_fft_selector::iflag_fftw, m_fft_selector::iflag_fftw_field, m_fft_selector::iflag_fftw_single, t_sph_multi_fftw::mhd_multi_back_fftw_from_recv(), t_sph_field_fftw::sph_field_back_fftw_from_recv(), t_sph_fftpack5::sph_rfftmb_from_recv(), and t_sph_single_fftw::sph_single_back_fftw_from_recv().
Referenced by sph_trans_w_coriols::sph_b_trans_w_coriolis(), sph_trans_w_coriols::sph_b_transform_sgs(), and init_fft_4_mhd::test_fourier_trans_4_mhd().
finalize_mhd_fft_select()
subroutine mhd_fft_selector::finalize_mhd_fft_select (type(work_for_sgl_fftw), intent(inout) MHD_mul_FFTW)
Definition at line 131 of file MHD_FFT_selector.F90.
References t_sph_multi_fftw::finalize_mhd_multi_fftw(), m_machine_parameter::iflag_debug, m_fft_selector::iflag_fft, and m_fft_selector::iflag_fftw.
Referenced by init_fft_4_mhd::test_fourier_trans_4_mhd().
fwd_mhd_fft_sel_to_send()
subroutine mhd_fft_selector::fwd_mhd_fft_sel_to_send (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, integer(kind = kint), intent(in) ncomp_fwd, integer(kind = kint), intent(in) n_WS, type(spherical_transform_data), intent(inout) trns_fwd, real (kind=kreal), dimension(n_ws), intent(inout) WS, type(work_for_ffts), intent(inout) WK_FFTs, type(work_for_sgl_fftw), intent(inout) MHD_mul_FFTW)
Definition at line 175 of file MHD_FFT_selector.F90.
References m_fft_selector::iflag_fft, m_fft_selector::iflag_fftw, m_fft_selector::iflag_fftw_field, m_fft_selector::iflag_fftw_single, t_sph_multi_fftw::mhd_multi_fwd_fftw_to_send(), t_sph_field_fftw::sph_field_fwd_fftw_to_send(), t_sph_fftpack5::sph_rfftmf_to_send(), and t_sph_single_fftw::sph_single_fwd_fftw_to_send().
Referenced by sph_trans_w_coriols::sph_f_trans_w_coriolis(), sph_trans_w_coriols::sph_f_transform_sgs(), and init_fft_4_mhd::test_fourier_trans_4_mhd().
init_mhd_fft_select()
subroutine mhd_fft_selector::init_mhd_fft_select (integer, intent(in) id_rank, type(sph_rtp_grid), intent(in) sph_rtp, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) ncomp_fwd, integer(kind = kint), intent(in) ncomp_bwd, type(work_for_sgl_fftw), intent(inout) MHD_mul_FFTW)
Definition at line 105 of file MHD_FFT_selector.F90.
References m_fft_selector::iflag_fft, m_fft_selector::iflag_fftw, and t_sph_multi_fftw::init_mhd_multi_fftw().
Referenced by init_fft_4_mhd::init_fourier_transform_4_mhd(), and init_fft_4_mhd::test_fourier_trans_4_mhd().
verify_mhd_fft_select()
subroutine mhd_fft_selector::verify_mhd_fft_select (integer, intent(in) id_rank, type(sph_rtp_grid), intent(in) sph_rtp, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) ncomp_fwd, integer(kind = kint), intent(in) ncomp_bwd, type(work_for_sgl_fftw), intent(inout) MHD_mul_FFTW)
Definition at line 148 of file MHD_FFT_selector.F90.
References m_fft_selector::iflag_fft, m_fft_selector::iflag_fftw, and t_sph_multi_fftw::verify_mhd_multi_fftw().