CALYPSO: gz_mpi_sph_modes_file_io_b Module Reference
gz_mpi_sph_modes_file_io_b Module Reference
ASCII spectr data IO routines.
Functions/Subroutines
subroutine gz_mpi_read_geom_rtp_file_b (file_name, num_pe, id_rank, sph_file)
subroutine gz_mpi_read_spectr_rj_file_b (file_name, num_pe, id_rank, sph_file)
subroutine gz_mpi_read_geom_rtm_file_b (file_name, num_pe, id_rank, sph_file)
subroutine gz_mpi_read_modes_rlm_file_b (file_name, num_pe, id_rank, sph_file)
subroutine gz_mpi_write_geom_rtp_file_b (file_name, sph_file)
subroutine gz_mpi_write_spectr_rj_file_b (file_name, sph_file)
subroutine gz_mpi_write_geom_rtm_file_b (file_name, sph_file)
subroutine gz_mpi_write_modes_rlm_file_b (file_name, sph_file)
Variables
type(calypso_mpi_io_params), save, private io_param
Detailed Description
ASCII spectr data IO routines.
      subroutine gz_mpi_read_geom_rtp_file_b                          &
     &         (file_name, num_pe, id_rank, sph_file)
      subroutine gz_mpi_read_spectr_rj_file_b                         &
     &         (file_name, num_pe, id_rank, sph_file)
      subroutine gz_mpi_read_geom_rtm_file_b                          &
     &         (file_name, num_pe, id_rank, sph_file)
      subroutine gz_mpi_read_modes_rlm_file_b                         &
     &         (file_name, num_pe, id_rank, sph_file)
        type(sph_file_data_type), intent(inout) :: sph_file
      subroutine gz_mpi_write_geom_rtp_file_b(file_name, sph_file)
      subroutine gz_mpi_write_spectr_rj_file_b(file_name, sph_file)
      subroutine gz_mpi_write_geom_rtm_file_b(file_name, sph_file)
      subroutine gz_mpi_write_modes_rlm_file_b(file_name, sph_file)
        type(sph_file_data_type), intent(in) :: sph_file
Parameters
num_pe Number of subdomain
id_rank Domain ID
file_name file name for IO (.gz is appended in this module)
Function/Subroutine Documentation
gz_mpi_read_geom_rtm_file_b()
subroutine gz_mpi_sph_modes_file_io_b::gz_mpi_read_geom_rtm_file_b (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, type(sph_file_data_type), intent(inout) sph_file)
Definition at line 98 of file gz_MPI_sph_modes_file_IO_b.f90.
References mpi_ascii_data_io::close_mpi_file(), gz_mpi_sph_modes_data_io_b::gz_mpi_read_geom_rtm_data_b(), m_machine_parameter::i_debug, io_param, and gz_mpi_binary_datum_io::open_read_gz_mpi_file_b().
Referenced by sph_file_mpi_io_select::sel_mpi_read_geom_rtm_file().
gz_mpi_read_geom_rtp_file_b()
subroutine gz_mpi_sph_modes_file_io_b::gz_mpi_read_geom_rtp_file_b (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, type(sph_file_data_type), intent(inout) sph_file)
Definition at line 53 of file gz_MPI_sph_modes_file_IO_b.f90.
References mpi_ascii_data_io::close_mpi_file(), gz_mpi_sph_modes_data_io_b::gz_mpi_read_geom_rtp_data_b(), m_machine_parameter::i_debug, io_param, and gz_mpi_binary_datum_io::open_read_gz_mpi_file_b().
Referenced by sph_file_mpi_io_select::sel_mpi_read_geom_rtp_file().
gz_mpi_read_modes_rlm_file_b()
subroutine gz_mpi_sph_modes_file_io_b::gz_mpi_read_modes_rlm_file_b (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, type(sph_file_data_type), intent(inout) sph_file)
Definition at line 120 of file gz_MPI_sph_modes_file_IO_b.f90.
References mpi_ascii_data_io::close_mpi_file(), gz_mpi_sph_modes_data_io_b::gz_mpi_read_modes_rlm_data_b(), m_machine_parameter::i_debug, io_param, and gz_mpi_binary_datum_io::open_read_gz_mpi_file_b().
Referenced by sph_file_mpi_io_select::sel_mpi_read_modes_rlm_file().
gz_mpi_read_spectr_rj_file_b()
subroutine gz_mpi_sph_modes_file_io_b::gz_mpi_read_spectr_rj_file_b (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, type(sph_file_data_type), intent(inout) sph_file)
Definition at line 75 of file gz_MPI_sph_modes_file_IO_b.f90.
References mpi_ascii_data_io::close_mpi_file(), gz_mpi_sph_modes_data_io_b::gz_mpi_read_spectr_rj_data_b(), m_machine_parameter::i_debug, io_param, and gz_mpi_binary_datum_io::open_read_gz_mpi_file_b().
Referenced by sph_file_mpi_io_select::sel_mpi_read_spectr_rj_file().
gz_mpi_write_geom_rtm_file_b()
subroutine gz_mpi_sph_modes_file_io_b::gz_mpi_write_geom_rtm_file_b (character(len=kchara), intent(in) file_name, type(sph_file_data_type), intent(in) sph_file)
Definition at line 183 of file gz_MPI_sph_modes_file_IO_b.f90.
References mpi_ascii_data_io::close_mpi_file(), gz_mpi_sph_modes_data_io_b::gz_mpi_write_geom_rtm_data_b(), m_machine_parameter::i_debug, io_param, and gz_mpi_binary_datum_io::open_write_gz_mpi_file_b().
Referenced by sph_file_mpi_io_select::sel_mpi_write_geom_rtm_file().
gz_mpi_write_geom_rtp_file_b()
subroutine gz_mpi_sph_modes_file_io_b::gz_mpi_write_geom_rtp_file_b (character(len=kchara), intent(in) file_name, type(sph_file_data_type), intent(in) sph_file)
Definition at line 144 of file gz_MPI_sph_modes_file_IO_b.f90.
References mpi_ascii_data_io::close_mpi_file(), gz_mpi_sph_modes_data_io_b::gz_mpi_write_geom_rtp_data_b(), m_machine_parameter::i_debug, io_param, and gz_mpi_binary_datum_io::open_write_gz_mpi_file_b().
Referenced by sph_file_mpi_io_select::sel_mpi_write_geom_rtp_file().
gz_mpi_write_modes_rlm_file_b()
subroutine gz_mpi_sph_modes_file_io_b::gz_mpi_write_modes_rlm_file_b (character(len=kchara), intent(in) file_name, type(sph_file_data_type), intent(in) sph_file)
Definition at line 202 of file gz_MPI_sph_modes_file_IO_b.f90.
References mpi_ascii_data_io::close_mpi_file(), gz_mpi_sph_modes_data_io_b::gz_mpi_write_modes_rlm_data_b(), m_machine_parameter::i_debug, io_param, and gz_mpi_binary_datum_io::open_write_gz_mpi_file_b().
Referenced by sph_file_mpi_io_select::sel_mpi_write_modes_rlm_file().
gz_mpi_write_spectr_rj_file_b()
subroutine gz_mpi_sph_modes_file_io_b::gz_mpi_write_spectr_rj_file_b (character(len=kchara), intent(in) file_name, type(sph_file_data_type), intent(in) sph_file)
Definition at line 163 of file gz_MPI_sph_modes_file_IO_b.f90.
References mpi_ascii_data_io::close_mpi_file(), gz_mpi_sph_modes_data_io_b::gz_mpi_write_spectr_rj_data_b(), m_machine_parameter::i_debug, io_param, and gz_mpi_binary_datum_io::open_write_gz_mpi_file_b().
Referenced by sph_file_mpi_io_select::sel_mpi_write_spectr_rj_file().
Variable Documentation
io_param
type(calypso_mpi_io_params), save, private gz_mpi_sph_modes_file_io_b::io_param private
Definition at line 45 of file gz_MPI_sph_modes_file_IO_b.f90.
Referenced by gz_mpi_read_geom_rtm_file_b(), gz_mpi_read_geom_rtp_file_b(), gz_mpi_read_modes_rlm_file_b(), gz_mpi_read_spectr_rj_file_b(), gz_mpi_write_geom_rtm_file_b(), gz_mpi_write_geom_rtp_file_b(), gz_mpi_write_modes_rlm_file_b(), and gz_mpi_write_spectr_rj_file_b().