CALYPSO: convert_from_rayleigh_rst Module Reference
convert_from_rayleigh_rst Module Reference
Main loop to assemble spectr data.
Functions/Subroutines
subroutine convert_fields_from_rayleigh (istep, org_fld_file, new_sph_mesh, r_itp, ra_rst, new_sph_phys)
subroutine, private cvt_each_field_from_rayleigh (file_name, i_fld, i_comp, new_sph_mesh, r_itp, ra_rst, fcheby_WK, rayleigh_WK, new_sph_phys)
subroutine, private check_chebyshev_trans (sph_rj, r_itp, file_name, l, m, j, i_fld, i_comp, nri_org, rayleigh_in, nri_tgt, rayleigh_tg, new_sph_phys)
Detailed Description
Main loop to assemble spectr data.
      subroutine convert_fields_from_rayleigh(istep, org_fld_file,    &
     &          new_sph_mesh, r_itp, ra_rst, new_sph_phys)
        type(field_IO_params), intent(in) :: org_fld_file
        type(sph_mesh_data), intent(in) :: new_sph_mesh
        type(rayleigh_restart), intent(in) :: ra_rst
        type(sph_radial_itp_data), intent(in) :: r_itp
        type(phys_data), intent(inout) :: new_sph_phys
Function/Subroutine Documentation
check_chebyshev_trans()
subroutine, private convert_from_rayleigh_rst::check_chebyshev_trans (type(sph_rj_grid), intent(in) sph_rj, type(sph_radial_itp_data), intent(in) r_itp, character(len = kchara), intent(in) file_name, integer(kind = kint), intent(in) l, integer(kind = kint), intent(in) m, integer(kind = kint), intent(in) j, integer(kind = kint), intent(in) i_fld, integer(kind = kint), intent(in) i_comp, integer(kind = kint), intent(in) nri_org, real(kind = kreal), dimension(nri_org,2), intent(in) rayleigh_in, integer(kind = kint), intent(in) nri_tgt, real(kind = kreal), dimension(nri_tgt,1), intent(in) rayleigh_tg, type(phys_data), intent(in) new_sph_phys) private
Definition at line 175 of file convert_from_rayleigh_rst.f90.
References calypso_mpi::my_rank.
convert_fields_from_rayleigh()
subroutine convert_from_rayleigh_rst::convert_fields_from_rayleigh (integer(kind = kint), intent(in) istep, type(field_io_params), intent(in) org_fld_file, type(sph_mesh_data), intent(in) new_sph_mesh, type(sph_radial_itp_data), intent(in) r_itp, type(rayleigh_restart), intent(in) ra_rst, type(phys_data), intent(inout) new_sph_phys)
Definition at line 42 of file convert_from_rayleigh_rst.f90.
References t_convert_from_rayleigh::alloc_work_rayleigh_restart(), cvt_each_field_from_rayleigh(), t_convert_from_rayleigh::dealloc_fftpack_4_cheby(), t_convert_from_rayleigh::dealloc_work_rayleigh_restart(), t_convert_from_rayleigh::init_fftpack_4_cheby(), and rayleigh_restart_io::set_rayleigh_rst_file_name().
Referenced by analyzer_rayleigh_cvt_sph::analyze_cvt_rayleigh_sph().
cvt_each_field_from_rayleigh()
subroutine, private convert_from_rayleigh_rst::cvt_each_field_from_rayleigh (character(len = kchara), intent(in) file_name, integer(kind = kint), intent(in) i_fld, integer(kind = kint), intent(in) i_comp, type(sph_mesh_data), intent(in) new_sph_mesh, type(sph_radial_itp_data), intent(in) r_itp, type(rayleigh_restart), intent(in) ra_rst, type(work_fftpack_chebyshev), intent(in) fcheby_WK, type(work_rayleigh_checkpoint), intent(inout) rayleigh_WK, type(phys_data), intent(inout) new_sph_phys) private
Definition at line 93 of file convert_from_rayleigh_rst.f90.
References m_calypso_mpi_io::calypso_close_mpi_file(), m_calypso_mpi_io::calypso_mpi_read_file_open(), t_convert_from_rayleigh::copy_from_chebyshev_trans(), cost1b(), m_constants::ione, m_base_field_labels::magnetic_field, m_base_field_labels::pressure, m_explicit_term_labels::previous_heat, m_explicit_term_labels::previous_induction, m_explicit_term_labels::previous_momentum, t_convert_from_rayleigh::radial_interpolation_rayleigh(), t_convert_from_rayleigh::rescaling_for_chebyshev_fft(), t_convert_from_rayleigh::rescaling_from_rayleigh(), m_base_field_labels::temperature, and m_base_field_labels::velocity.
Referenced by convert_fields_from_rayleigh().