CALYPSO: set_surf_edge_mesh Module Reference
set_surf_edge_mesh Module Reference
Functions/Subroutines
subroutine set_surface_and_edge (node, ele, surf, edge)
subroutine empty_surface_and_edge (ele, surf, edge)
subroutine, private set_surf_connectivity (node, ele, surf)
subroutine, private set_edge_connectivity (node, ele, surf, edge)
subroutine, private set_surf_geometry (node, surf)
subroutine, private set_edge_geometry (node, edge)
Function/Subroutine Documentation
empty_surface_and_edge()
subroutine set_surf_edge_mesh::empty_surface_and_edge (type(element_data), intent(in) ele, type(surface_data), intent(inout) surf, type(edge_data), intent(inout) edge)
Definition at line 73 of file set_surf_edge_mesh.f90.
References t_edge_data::alloc_edge_geometory(), t_surface_data::allocate_surface_geom_type(), const_edge_data::empty_edge_connect_type(), and const_surface_data::empty_surface_connect().
Referenced by const_mesh_information::empty_mesh_info().
set_edge_connectivity()
subroutine, private set_surf_edge_mesh::set_edge_connectivity (type(node_data), intent(in) node, type(element_data), intent(in) ele, type(surface_data), intent(in) surf, type(edge_data), intent(inout) edge) private
Definition at line 129 of file set_surf_edge_mesh.f90.
References const_edge_data::construct_edge_data(), set_size_4_smp_types::count_edge_size_smp_type(), set_size_4_smp_types::count_overlap_edge(), and m_machine_parameter::iflag_debug.
Referenced by set_surface_and_edge().
set_edge_geometry()
subroutine, private set_surf_edge_mesh::set_edge_geometry (type(node_data), intent(in) node, type(edge_data), intent(inout) edge) private
Definition at line 178 of file set_surf_edge_mesh.f90.
References t_edge_data::alloc_edge_geometory(), and cal_mesh_position::set_center_of_edge().
Referenced by set_surface_and_edge().
set_surf_connectivity()
subroutine, private set_surf_edge_mesh::set_surf_connectivity (type(node_data), intent(in) node, type(element_data), intent(in) ele, type(surface_data), intent(inout) surf) private
Definition at line 95 of file set_surf_edge_mesh.f90.
References const_surface_data::construct_surface_data(), set_size_4_smp_types::count_overlap_surf(), set_size_4_smp_types::count_surf_size_smp_type(), and m_machine_parameter::iflag_debug.
Referenced by set_surface_and_edge().
set_surf_geometry()
subroutine, private set_surf_edge_mesh::set_surf_geometry (type(node_data), intent(in) node, type(surface_data), intent(inout) surf) private
Definition at line 163 of file set_surf_edge_mesh.f90.
References t_surface_data::allocate_surface_geom_type(), and cal_mesh_position::set_center_of_surface().
Referenced by set_surface_and_edge().
set_surface_and_edge()
subroutine set_surf_edge_mesh::set_surface_and_edge (type(node_data), intent(in) node, type(element_data), intent(in) ele, type(surface_data), intent(inout) surf, type(edge_data), intent(inout) edge)
Definition at line 50 of file set_surf_edge_mesh.f90.
References m_machine_parameter::iflag_debug, set_edge_connectivity(), set_edge_geometry(), set_surf_connectivity(), and set_surf_geometry().
Referenced by const_mesh_information::const_mesh_infos().