CALYPSO: zlib_convert_ascii_vector Module Reference
zlib_convert_ascii_vector Module Reference
Vector data compression routine.
Functions/Subroutines
subroutine defleate_node_position (nnod, numdir, id_global, xx, zbuf)
subroutine infleate_node_position (nnod, numdir, id_global, xx, zbuf)
subroutine defleate_vector_txt (iflag_blank, nnod, ndir, vector, zbuf)
subroutine infleate_vector_txt (iflag_blank, nnod, ndir, vector, zbuf)
Detailed Description
Vector data compression routine.
      subroutine defleate_node_position                               &
     &         (nnod, numdir, id_global, xx, zbuf)
      subroutine infleate_node_position                               &
     &         (nnod, numdir, id_global, xx, zbuf)
        type(buffer_4_gzip), intent(inout) :: zbuf
      subroutine defleate_vector_txt                                  &
     &         (iflag_blank, nnod, ndir, vector, zbuf)
      subroutine infleate_vector_txt                                  &
     &         (iflag_blank, nnod, ndir, vector, zbuf)
        type(buffer_4_gzip), intent(inout) :: zbuf
Function/Subroutine Documentation
defleate_node_position()
subroutine zlib_convert_ascii_vector::defleate_node_position (integer(kind = kint_gl), intent(in) nnod, integer(kind = kint), intent(in) numdir, integer(kind = kint_gl), dimension(nnod), intent(in) id_global, real(kind = kreal), dimension(nnod, numdir), intent(in) xx, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 38 of file zlib_convert_ascii_vector.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), gzip_defleate::gzip_defleat_char_begin(), gzip_defleate::gzip_defleat_char_cont(), gzip_defleate::gzip_defleat_char_last(), gzip_defleate::gzip_defleat_char_once(), m_constants::huge_30, data_io_to_textline::int8_and_vector_textline(), m_constants::ione, and data_io_to_textline::len_int8_and_vector_textline().
Referenced by gz_mpi_position_io::gz_mpi_write_node_position(), and gz_mpi_viewer_mesh_io::gz_mpi_write_viewer_position().
defleate_vector_txt()
subroutine zlib_convert_ascii_vector::defleate_vector_txt (integer(kind = kint), intent(in) iflag_blank, integer(kind = kint_gl), intent(in) nnod, integer(kind = kint), intent(in) ndir, real(kind = kreal), dimension(nnod,ndir), intent(in) vector, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 193 of file zlib_convert_ascii_vector.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), gzip_defleate::gzip_defleat_char_begin(), gzip_defleate::gzip_defleat_char_cont(), gzip_defleate::gzip_defleat_char_last(), gzip_defleate::gzip_defleat_char_once(), m_constants::huge_30, m_constants::ione, data_io_to_textline::len_vector_textline(), and data_io_to_textline::vector_textline().
Referenced by gz_mpi_vectors_io::gz_mpi_write_vector(), and gz_field_data_mpi_io::gz_write_fld_vecotr_mpi().
infleate_node_position()
subroutine zlib_convert_ascii_vector::infleate_node_position (integer(kind = kint_gl), intent(in) nnod, integer(kind = kint), intent(in) numdir, integer(kind = kint_gl), dimension(nnod), intent(inout) id_global, real(kind = kreal), dimension(nnod, numdir), intent(inout) xx, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 115 of file zlib_convert_ascii_vector.f90.
References t_buffer_4_gzip::alloc_textbuffer_for_zlib(), t_buffer_4_gzip::dealloc_textbuffer_for_zlib(), t_buffer_4_gzip::dealloc_zip_buffer(), gzip_infleate::gzip_infleat_char_begin(), gzip_infleate::gzip_infleat_char_cont(), gzip_infleate::gzip_infleat_char_last(), gzip_infleate::gzip_infleat_char_once(), m_constants::huge_30, m_constants::ione, data_io_to_textline::len_int8_and_vector_textline(), t_buffer_4_gzip::link_pointer_for_zlib_buffer(), data_io_to_textline::read_int8_and_vector_textline(), and t_buffer_4_gzip::unlink_pointer_for_zlib_buffer().
Referenced by gz_mpi_position_io::gz_mpi_read_node_position().
infleate_vector_txt()
subroutine zlib_convert_ascii_vector::infleate_vector_txt (integer(kind = kint), intent(in) iflag_blank, integer(kind = kint_gl), intent(in) nnod, integer(kind = kint), intent(in) ndir, real(kind = kreal), dimension(nnod,ndir), intent(inout) vector, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 262 of file zlib_convert_ascii_vector.f90.
References t_buffer_4_gzip::alloc_textbuffer_for_zlib(), t_buffer_4_gzip::dealloc_textbuffer_for_zlib(), t_buffer_4_gzip::dealloc_zip_buffer(), gzip_infleate::gzip_infleat_char_begin(), gzip_infleate::gzip_infleat_char_cont(), gzip_infleate::gzip_infleat_char_last(), gzip_infleate::gzip_infleat_char_once(), m_constants::huge_30, m_constants::ione, data_io_to_textline::len_vector_textline(), t_buffer_4_gzip::link_pointer_for_zlib_buffer(), data_io_to_textline::read_vector_textline(), and t_buffer_4_gzip::unlink_pointer_for_zlib_buffer().
Referenced by gz_mpi_vectors_io::gz_mpi_read_vector(), and gz_field_data_mpi_io::gz_read_each_field_mpi().