CALYPSO: t_sph_field_fftw Module Reference
t_sph_field_fftw Module Reference
Fourier transform using FFTW Ver.3.
Data Types
type work_for_field_fftw
Structure to use SNGLE FFTW.
Functions/Subroutines
subroutine finalize_sph_field_fftw (FFTW_f)
subroutine alloc_whole_fftw_plan (Nfft, irt_rtp_smp_stack, ncomp_bwd, ncomp_fwd, FFTW_f)
subroutine alloc_fld_fftw_plan (Nfft, irt_rtp_smp_stack, FFTW_f)
subroutine, private dealloc_fld_fftw_plan (FFTW_f)
Detailed Description
Fourier transform using FFTW Ver.3.
 ------------------------------------------------------------------
      subroutine finalize_sph_field_FFTW(FFTW_f)
      subroutine alloc_whole_FFTW_plan(Nfft, irt_rtp_smp_stack,       &
     &          ncomp_bwd, ncomp_fwd, FFTW_f)
      subroutine alloc_fld_FFTW_plan(Nfft, irt_rtp_smp_stack, FFTW_f)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_comm_tbl), intent(in)  :: comm_rtp
   wrapper subroutine for initierize FFT by FFTW
 ------------------------------------------------------------------
Parameters
Nstacksmp(0:np_smp) End number for each SMP process
Ncomp Number of components for Fourier transforms
Nfft Data length for eadh FFT
X(Ncomp,Nfft) Data for Fourier transform
Function/Subroutine Documentation
alloc_fld_fftw_plan()
subroutine t_sph_field_fftw::alloc_fld_fftw_plan (integer(kind = kint), intent(in) Nfft, integer(kind = kint), dimension(0:np_smp), intent(in) irt_rtp_smp_stack, type(work_for_field_fftw), intent(inout) FFTW_f)
Definition at line 133 of file t_sph_field_FFTW.F90.
Referenced by sph_prt_domain_fftw::init_prt_field_fftw(), and sph_rtp_domain_fftw::init_rtp_field_fftw().
alloc_whole_fftw_plan()
subroutine t_sph_field_fftw::alloc_whole_fftw_plan (integer(kind = kint), intent(in) Nfft, integer(kind = kint), dimension(0:np_smp), intent(in) irt_rtp_smp_stack, integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), intent(in) ncomp_fwd, type(work_for_field_fftw), intent(inout) FFTW_f)
Definition at line 105 of file t_sph_field_FFTW.F90.
References m_machine_parameter::np_smp.
Referenced by sph_prt_fftw::init_prt_fftw(), and sph_rtp_fftw::init_rtp_fftw().
dealloc_fld_fftw_plan()
subroutine, private t_sph_field_fftw::dealloc_fld_fftw_plan (type(work_for_field_fftw), intent(inout) FFTW_f) private
Definition at line 158 of file t_sph_field_FFTW.F90.
Referenced by finalize_sph_field_fftw().
finalize_sph_field_fftw()
subroutine t_sph_field_fftw::finalize_sph_field_fftw (type(work_for_field_fftw), intent(inout) FFTW_f)
Definition at line 83 of file t_sph_field_FFTW.F90.
References t_sph_comm_table_from_fftw::dealloc_comm_table_sph_fftw(), dealloc_fld_fftw_plan(), and m_machine_parameter::np_smp.
Referenced by t_sph_fft_selector::finalize_sph_fft_select(), sph_prt_fftw::verify_prt_fftw(), sph_prt_domain_fftw::verify_prt_field_fftw(), sph_rtp_fftw::verify_rtp_fftw(), and sph_rtp_domain_fftw::verify_rtp_field_fftw().