CALYPSO: m_tave_sph_ene_spectr Module Reference
m_tave_sph_ene_spectr Module Reference
Time average spherical harmonics spectrum data.
Functions/Subroutines
subroutine sph_spectr_average (fname_org, start_time, end_time, sph_IN)
subroutine sph_spectr_std_deviation (fname_org, start_time, end_time, sph_IN)
subroutine, private allocate_tave_sph_data (ltr, sph_IN)
subroutine, private deallocate_tave_sph_data
Variables
integer(kind=kint), parameter, private id_file_rms = 34
real(kind=kreal), dimension(:,:,:), allocatable, private ave_spec_l
real(kind=kreal), dimension(:,:,:), allocatable, private sigma_spec_l
real(kind=kreal), dimension(:,:,:), allocatable, private spectr_pre_l
Detailed Description
Time average spherical harmonics spectrum data.
      subroutine sph_spectr_average                                   &
     &         (fname_org, start_time, end_time, sph_IN)
      subroutine sph_spectr_std_deviation                             &
     &         (fname_org, start_time, end_time, sph_IN)
Function/Subroutine Documentation
allocate_tave_sph_data()
subroutine, private m_tave_sph_ene_spectr::allocate_tave_sph_data (integer(kind = kint), intent(in) ltr, type(read_sph_spectr_data), intent(inout) sph_IN) private
Definition at line 198 of file m_tave_sph_ene_spectr.f90.
References ave_spec_l, sigma_spec_l, and spectr_pre_l.
Referenced by sph_spectr_average().
deallocate_tave_sph_data()
subroutine, private m_tave_sph_ene_spectr::deallocate_tave_sph_data private
Definition at line 219 of file m_tave_sph_ene_spectr.f90.
References ave_spec_l, sigma_spec_l, and spectr_pre_l.
Referenced by sph_spectr_std_deviation().
sph_spectr_average()
subroutine m_tave_sph_ene_spectr::sph_spectr_average (character(len = kchara), intent(in) fname_org, real(kind = kreal), intent(in) start_time, real(kind = kreal), intent(in) end_time, type(read_sph_spectr_data), intent(inout) sph_IN)
Definition at line 42 of file m_tave_sph_ene_spectr.f90.
References allocate_tave_sph_data(), ave_spec_l, cal_tave_sph_ene_spectr::copy_ene_spectr_2_pre(), t_read_sph_spectra::dealloc_sph_espec_data(), cal_tave_sph_ene_spectr::divide_average_ene_spectr(), id_file_rms, sph_mean_square_io_select::select_input_sph_pwr_data(), sph_mean_square_io_select::select_input_sph_pwr_head(), sph_mean_square_io_select::select_output_sph_pwr_data(), sph_mean_square_io_select::select_output_sph_pwr_head(), spectr_pre_l, and cal_tave_sph_ene_spectr::sum_average_ene_spectr().
Referenced by t_average_sph_ene_spec().
sph_spectr_std_deviation()
subroutine m_tave_sph_ene_spectr::sph_spectr_std_deviation (character(len = kchara), intent(in) fname_org, real(kind = kreal), intent(in) start_time, real(kind = kreal), intent(in) end_time, type(read_sph_spectr_data), intent(inout) sph_IN)
Definition at line 119 of file m_tave_sph_ene_spectr.f90.
References ave_spec_l, cal_tave_sph_ene_spectr::copy_deviation_ene_2_pre(), t_read_sph_spectra::dealloc_sph_espec_data(), deallocate_tave_sph_data(), cal_tave_sph_ene_spectr::divide_deviation_ene_spectr(), id_file_rms, sph_mean_square_io_select::select_input_sph_pwr_data(), sph_mean_square_io_select::select_input_sph_pwr_head(), sph_mean_square_io_select::select_output_sph_pwr_data(), sph_mean_square_io_select::select_output_sph_pwr_head(), sigma_spec_l, spectr_pre_l, and cal_tave_sph_ene_spectr::sum_deviation_ene_spectr().
Referenced by t_average_sph_ene_spec().
Variable Documentation
ave_spec_l
real(kind = kreal), dimension(:,:,:), allocatable, private m_tave_sph_ene_spectr::ave_spec_l private
Definition at line 28 of file m_tave_sph_ene_spectr.f90.
Referenced by allocate_tave_sph_data(), deallocate_tave_sph_data(), sph_spectr_average(), and sph_spectr_std_deviation().
id_file_rms
integer(kind = kint), parameter, private m_tave_sph_ene_spectr::id_file_rms = 34 private
Definition at line 26 of file m_tave_sph_ene_spectr.f90.
Referenced by sph_spectr_average(), and sph_spectr_std_deviation().
sigma_spec_l
real(kind = kreal), dimension(:,:,:), allocatable, private m_tave_sph_ene_spectr::sigma_spec_l private
Definition at line 29 of file m_tave_sph_ene_spectr.f90.
Referenced by allocate_tave_sph_data(), deallocate_tave_sph_data(), and sph_spectr_std_deviation().
spectr_pre_l
real(kind = kreal), dimension(:,:,:), allocatable, private m_tave_sph_ene_spectr::spectr_pre_l private
Definition at line 30 of file m_tave_sph_ene_spectr.f90.
Referenced by allocate_tave_sph_data(), deallocate_tave_sph_data(), sph_spectr_average(), and sph_spectr_std_deviation().