CALYPSO: calypso_mpi_real Module Reference
calypso_mpi_real Module Reference
MPI communication routines for real in Calypso.
Functions/Subroutines
subroutine calypso_mpi_bcast_one_real (buffer, root)
subroutine calypso_mpi_bcast_real (buffer, count, root)
subroutine calypso_mpi_reduce_real (r_local, r_global, count, operation, destination)
subroutine calypso_mpi_allreduce_one_real (r_local, r_global, operation)
subroutine calypso_mpi_allreduce_real (r_local, r_global, count, operation)
subroutine calypso_mpi_gather_one_real (sendbuf, recvbuf, root)
subroutine calypso_mpi_allgather_one_real (sendbuf, recvbuf)
subroutine calypso_mpi_allgather_real (sendbuf, n_send, recvbuf, n_recv)
subroutine calypso_mpi_seek_write_real (id_mpi_file, ioffset, num, vector, sta_IO)
subroutine calypso_mpi_seek_read_real (id_mpi_file, ioffset, num, vector, sta_IO)
Detailed Description
MPI communication routines for real in Calypso.
      subroutine calypso_mpi_bcast_one_real(buffer, root)
        integer, intent(in) :: root
        real(kind = kreal), intent(inout) :: buffer
      subroutine calypso_mpi_bcast_real(buffer, count, root)
        integer, intent(in) :: root
        integer(kind = kint_gl), intent(in) :: count
        real(kind = kreal), intent(inout) :: buffer(count)
      subroutine calypso_mpi_reduce_real                              &
     &         (r_local, r_global, count, operation, destination)
        integer, intent(in) :: operation, destination
        integer(kind = kint_gl), intent(in) :: count
        real(kind = kreal), intent(in) ::    r_local(count)
        real(kind = kreal), intent(inout) :: r_global(count)
      subroutine calypso_mpi_allreduce_one_real                       &
     &         (r_local, r_global, operation)
        integer, intent(in) :: operation
        real(kind = kreal), intent(in) ::    r_local
        real(kind = kreal), intent(inout) :: r_global
      subroutine calypso_mpi_allreduce_real                           &
     &         (r_local, r_global, count, operation)
        integer, intent(in) :: operation
        integer(kind = kint_gl), intent(in) :: count
        real(kind = kreal), intent(in) ::    r_local(count)
        real(kind = kreal), intent(inout) :: r_global(count)
      subroutine calypso_mpi_gather_one_real(sendbuf, recvbuf, root)
        integer, intent(in) :: root
        real(kind = kreal), intent(in) ::    sendbuf
        real(kind = kreal), intent(inout) :: recvbuf(nprocs)
      subroutine calypso_mpi_allgather_one_real(sendbuf, recvbuf)
        real(kind = kreal), intent(in) ::    sendbuf
        real(kind = kreal), intent(inout) :: recvbuf(nprocs)
      subroutine calypso_mpi_allgather_real                           &
     &         (sendbuf, n_send, recvbuf, n_recv)
        integer(kind =kint), intent(in) :: n_send, n_recv
        real(kind = kreal), intent(in) ::    sendbuf(n_send)
        real(kind = kreal), intent(inout) :: recvbuf(nprocs*n_recv)
      subroutine calypso_mpi_seek_write_real                          &
     &         (id_mpi_file, ioffset, num, vector, sta_IO)
        integer, intent(in) ::  id_mpi_file
        integer(kind = MPI_OFFSET_KIND), intent(in) :: ioffset
        integer(kind = kint_gl), intent(in) :: num
        real(kind = kreal), intent(in) :: vector(num)
        integer, intent(inout) :: sta_IO(MPI_STATUS_SIZE)
      subroutine calypso_mpi_seek_read_real                           &
     &          (id_mpi_file, ioffset, num, vector, sta_IO)
        integer, intent(in) :: id_mpi_file
        integer(kind = kint_gl), intent(in) :: num
        integer(kind = MPI_OFFSET_KIND), intent(in) :: ioffset
        real(kind = kreal), intent(inout) :: vector(num)
        integer, intent(inout) :: sta_IO(MPI_STATUS_SIZE)
Parameters
icode error code
message message to output
Function/Subroutine Documentation
calypso_mpi_allgather_one_real()
subroutine calypso_mpi_real::calypso_mpi_allgather_one_real (real(kind = kreal), intent(in) sendbuf, real(kind = kreal), dimension(nprocs), intent(inout) recvbuf)
Definition at line 213 of file calypso_mpi_real.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_real, calypso_mpi::ierr_mpi, and calypso_mpi::nprocs.
calypso_mpi_allgather_real()
subroutine calypso_mpi_real::calypso_mpi_allgather_real (real(kind = kreal), dimension(n_send), intent(in) sendbuf, integer(kind =kint), intent(in) n_send, real(kind = kreal), dimension(nprocs*n_recv), intent(inout) recvbuf, integer(kind =kint), intent(in) n_recv)
Definition at line 229 of file calypso_mpi_real.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_real, calypso_mpi::ierr_mpi, and calypso_mpi::nprocs.
calypso_mpi_allreduce_one_real()
subroutine calypso_mpi_real::calypso_mpi_allreduce_one_real (real(kind = kreal), intent(in) r_local, real(kind = kreal), intent(inout) r_global, integer, intent(in) operation)
Definition at line 150 of file calypso_mpi_real.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_real, and calypso_mpi::ierr_mpi.
Referenced by sph_analyzer_mhd::sph_analyze_mhd(), and init_fft_4_sph::test_fourier_trans_vector().
calypso_mpi_allreduce_real()
subroutine calypso_mpi_real::calypso_mpi_allreduce_real (real(kind = kreal), dimension(count), intent(in) r_local, real(kind = kreal), dimension(count), intent(inout) r_global, integer(kind = kint_gl), intent(in) count, integer, intent(in) operation)
Definition at line 169 of file calypso_mpi_real.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_real, m_constants::huge_20, and calypso_mpi::ierr_mpi.
Referenced by t_cal_max_indices::cal_max_indices(), const_element_comm_tables::find_position_range(), global_field_4_dynamobench::pick_inner_core_rotation(), global_field_4_dynamobench::pick_mag_torque_inner_core(), t_sph_transforms::pole_b_transform(), test_legendre_transforms::s_test_legendre_transforms(), init_spherical_srs::sel_sph_import_table(), t_sph_transforms::sph_b_trans_w_poles(), and t_const_wz_coriolis_rtp::subtract_sphere_ave_coriolis().
calypso_mpi_bcast_one_real()
subroutine calypso_mpi_real::calypso_mpi_bcast_one_real (real(kind = kreal), intent(inout) buffer, integer, intent(in) root)
Definition at line 84 of file calypso_mpi_real.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_real, and calypso_mpi::ierr_mpi.
Referenced by set_control_newsph::bcast_ctl_param_newsph(), bcast_control_arrays::bcast_ctl_type_r1(), share_field_data::share_time_step_data(), and field_data_mpi_io::sync_field_time_mpi().
calypso_mpi_bcast_real()
subroutine calypso_mpi_real::calypso_mpi_bcast_real (real(kind = kreal), dimension(count), intent(inout) buffer, integer(kind = kint_gl), intent(in) count, integer, intent(in) root)
Definition at line 101 of file calypso_mpi_real.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_real, m_constants::huge_20, and calypso_mpi::ierr_mpi.
Referenced by bcast_control_arrays::bcast_ctl_array_c2r(), bcast_control_arrays::bcast_ctl_array_cr(), bcast_control_arrays::bcast_ctl_array_cr2(), bcast_control_arrays::bcast_ctl_array_i2r(), bcast_control_arrays::bcast_ctl_array_i2r2(), bcast_control_arrays::bcast_ctl_array_icr(), bcast_control_arrays::bcast_ctl_array_ir(), bcast_control_arrays::bcast_ctl_array_r1(), bcast_control_arrays::bcast_ctl_array_r2(), bcast_control_arrays::bcast_ctl_array_r3(), bcast_control_arrays::bcast_ctl_type_r2(), bcast_control_arrays::bcast_ctl_type_r3(), t_each_sph_boundary_io_data::bcast_each_bc_item_ctl(), t_convert_from_rayleigh::chebyshev_fwd_mat_4_rayleigh(), gz_mpi_binary_head_io::gz_mpi_read_mul_realhead_b(), mpi_binary_head_io::mpi_read_mul_realhead_b(), share_field_data::share_each_field_data(), share_field_data::share_each_field_io_data(), r_interpolate_marged_sph::share_r_interpolation_tbl(), and share_spectr_index_data::share_sph_rj_data().
calypso_mpi_gather_one_real()
subroutine calypso_mpi_real::calypso_mpi_gather_one_real (real(kind = kreal), intent(in) sendbuf, real(kind = kreal), dimension(nprocs), intent(inout) recvbuf, integer, intent(in) root)
Definition at line 195 of file calypso_mpi_real.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_real, calypso_mpi::ierr_mpi, and calypso_mpi::nprocs.
calypso_mpi_reduce_real()
subroutine calypso_mpi_real::calypso_mpi_reduce_real (real(kind = kreal), dimension(count), intent(in) r_local, real(kind = kreal), dimension(count), intent(inout) r_global, integer(kind = kint_gl), intent(in) count, integer, intent(in) operation, integer, intent(in) destination)
Definition at line 124 of file calypso_mpi_real.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_real, m_constants::huge_20, and calypso_mpi::ierr_mpi.
Referenced by t_field_on_circle::collect_spectr_for_circle(), cal_rms_fields_by_sph::global_sum_sph_layerd_square(), cal_rms_fields_by_sph::global_sum_sph_volume_square(), and t_work_time::output_elapsed_log().
calypso_mpi_seek_read_real()
subroutine calypso_mpi_real::calypso_mpi_seek_read_real (integer, intent(in) id_mpi_file, integer(kind = mpi_offset_kind), intent(in) ioffset, integer(kind = kint_gl), intent(in) num, real(kind = kreal), dimension(num), intent(inout) vector, integer, dimension(mpi_status_size), intent(inout) sta_IO)
Definition at line 276 of file calypso_mpi_real.f90.
References calypso_mpi::calypso_real, m_constants::huge_20, calypso_mpi::ierr_mpi, and m_precision::kreal.
Referenced by m_calypso_mpi_io::mpi_read_real_b().
calypso_mpi_seek_write_real()
subroutine calypso_mpi_real::calypso_mpi_seek_write_real (integer, intent(in) id_mpi_file, integer(kind = mpi_offset_kind), intent(in) ioffset, integer(kind = kint_gl), intent(in) num, real(kind = kreal), dimension(num), intent(in) vector, integer, dimension(mpi_status_size), intent(inout) sta_IO)
Definition at line 245 of file calypso_mpi_real.f90.
References calypso_mpi::calypso_real, m_constants::huge_20, calypso_mpi::ierr_mpi, and m_precision::kreal.
Referenced by m_calypso_mpi_io::mpi_write_real_b().