CALYPSO: gz_mpi_mesh_data_io Module Reference
gz_mpi_mesh_data_io Module Reference
Routines for gzipped binary mesh data IO.
Functions/Subroutines
subroutine gz_mpi_write_geometry_data (IO_param, mesh_IO)
subroutine gz_mpi_write_mesh_groups (IO_param, mesh_group_IO)
subroutine gz_mpi_read_num_node (IO_param, mesh_IO)
subroutine gz_mpi_read_num_node_ele (IO_param, mesh_IO)
subroutine gz_mpi_read_geometry_data (IO_param, mesh_IO)
subroutine gz_mpi_read_mesh_groups (IO_param, mesh_group_IO)
Detailed Description
Routines for gzipped binary mesh data IO.
      subroutine gz_mpi_write_geometry_data(IO_param, mesh_IO)
      subroutine gz_mpi_write_mesh_groups(IO_param, mesh_group_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(mesh_geometry), intent(in) :: mesh_IO
        type(mesh_groups), intent(in) ::   mesh_group_IO
      subroutine gz_mpi_read_num_node(IO_param, mesh_IO)
      subroutine gz_mpi_read_num_node_ele(IO_param, mesh_IO)
      subroutine gz_mpi_read_geometry_data(IO_param, mesh_IO)
      subroutine gz_mpi_read_mesh_groups(IO_param, mesh_group_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(mesh_geometry), intent(inout) :: mesh_IO
        type(mesh_groups), intent(inout) ::   mesh_group_IO
Function/Subroutine Documentation
gz_mpi_read_geometry_data()
subroutine gz_mpi_mesh_data_io::gz_mpi_read_geometry_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 142 of file gz_MPI_mesh_data_IO.f90.
References gz_mpi_element_connect_io::gz_mpi_read_element_info(), gz_mpi_domain_data_io::gz_mpi_read_export_data(), gz_mpi_domain_data_io::gz_mpi_read_import_data(), gz_mpi_read_num_node_ele(), gz_mpi_ascii_data_io::gz_mpi_skip_header(), m_fem_mesh_labels::hd_fem_export(), and m_fem_mesh_labels::hd_fem_import().
Referenced by gz_mpi_mesh_file_io::gz_mpi_read_mesh(), and gz_mpi_mesh_file_io::gz_mpi_read_mesh_geometry().
gz_mpi_read_mesh_groups()
subroutine gz_mpi_mesh_data_io::gz_mpi_read_mesh_groups (type(calypso_mpi_io_params), intent(inout) IO_param, type(mesh_groups), intent(inout) mesh_group_IO)
Definition at line 164 of file gz_MPI_mesh_data_IO.f90.
References gz_mpi_groups_io::gz_mpi_read_group_data(), gz_mpi_groups_io::gz_mpi_read_surf_grp_data(), gz_mpi_ascii_data_io::gz_mpi_skip_header(), m_fem_mesh_labels::hd_fem_elegrp(), m_fem_mesh_labels::hd_fem_nodgrp(), and m_fem_mesh_labels::hd_fem_sfgrp().
Referenced by gz_mpi_mesh_file_io::gz_mpi_read_mesh().
gz_mpi_read_num_node()
subroutine gz_mpi_mesh_data_io::gz_mpi_read_num_node (type(calypso_mpi_io_params), intent(inout) IO_param, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 108 of file gz_MPI_mesh_data_IO.f90.
References gz_mpi_domain_data_io::gz_mpi_read_domain_info(), gz_mpi_node_geometry_io::gz_mpi_read_number_of_node(), gz_mpi_ascii_data_io::gz_mpi_skip_header(), m_fem_mesh_labels::hd_fem_node(), and m_fem_mesh_labels::hd_fem_para().
Referenced by gz_mpi_mesh_file_io::gz_mpi_read_node_size(), and gz_mpi_read_num_node_ele().
gz_mpi_read_num_node_ele()
subroutine gz_mpi_mesh_data_io::gz_mpi_read_num_node_ele (type(calypso_mpi_io_params), intent(inout) IO_param, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 124 of file gz_MPI_mesh_data_IO.f90.
References gz_mpi_node_geometry_io::gz_mpi_read_geometry_info(), gz_mpi_element_connect_io::gz_mpi_read_num_element(), gz_mpi_read_num_node(), gz_mpi_ascii_data_io::gz_mpi_skip_header(), and m_fem_mesh_labels::hd_fem_elem().
Referenced by gz_mpi_read_geometry_data(), and gz_mpi_mesh_file_io::gz_mpi_read_geometry_size().
gz_mpi_write_geometry_data()
subroutine gz_mpi_mesh_data_io::gz_mpi_write_geometry_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(mesh_geometry), intent(in) mesh_IO)
Definition at line 50 of file gz_MPI_mesh_data_IO.f90.
References gz_mpi_ascii_data_io::gz_mpi_write_charahead(), gz_mpi_domain_data_io::gz_mpi_write_domain_info(), gz_mpi_element_connect_io::gz_mpi_write_element_info(), gz_mpi_domain_data_io::gz_mpi_write_export_data(), gz_mpi_node_geometry_io::gz_mpi_write_geometry_info(), gz_mpi_domain_data_io::gz_mpi_write_import_data(), m_fem_mesh_labels::hd_fem_elem(), m_fem_mesh_labels::hd_fem_export(), m_fem_mesh_labels::hd_fem_import(), m_fem_mesh_labels::hd_fem_node(), and m_fem_mesh_labels::hd_fem_para().
Referenced by gz_mpi_mesh_file_io::gz_mpi_write_mesh_file().
gz_mpi_write_mesh_groups()
subroutine gz_mpi_mesh_data_io::gz_mpi_write_mesh_groups (type(calypso_mpi_io_params), intent(inout) IO_param, type(mesh_groups), intent(in) mesh_group_IO)
Definition at line 80 of file gz_MPI_mesh_data_IO.f90.
References gz_mpi_ascii_data_io::gz_mpi_write_charahead(), gz_mpi_groups_io::gz_mpi_write_grp_data(), gz_mpi_groups_io::gz_mpi_write_surf_grp_data(), m_fem_mesh_labels::hd_fem_elegrp(), m_fem_mesh_labels::hd_fem_nodgrp(), and m_fem_mesh_labels::hd_fem_sfgrp().
Referenced by gz_mpi_mesh_file_io::gz_mpi_write_mesh_file().