CALYPSO: t_ctl_data_temp_model Module Reference
t_ctl_data_temp_model Module Reference
Data Types
type reference_point_control
type reference_temperature_ctl
type takepiro_model_control
Functions/Subroutines
subroutine read_reftemp_ctl (id_control, hd_block, reft_ctl, c_buf)
subroutine read_refcomp_ctl (id_control, hd_block, refc_ctl, c_buf)
subroutine bcast_ref_scalar_ctl (refs_ctl)
subroutine, private read_ref_temp_ctl (id_control, hd_block, ref_ctl, c_buf)
subroutine, private read_ref_comp_ctl (id_control, hd_block, ref_ctl, c_buf)
subroutine, private read_takepiro_ctl (id_control, hd_block, takepiro_ctl, c_buf)
subroutine, private bcast_ref_value_ctl (ref_ctl)
subroutine, private bcast_takepiro_ctl (takepiro_ctl)
Variables
character(len=kchara), parameter, private hd_ref_temp = 'ref_temp_ctl'
character(len=kchara), parameter, private hd_low_temp = 'low_temp_ctl'
character(len=kchara), parameter, private hd_high_temp = 'high_temp_ctl'
character(len=kchara), parameter, private hd_filterd_advection = 'filtered_advection_ctl'
character(len=kchara), parameter, private hd_ref_comp = 'ref_comp_ctl'
character(len=kchara), parameter, private hd_low_comp = 'low_comp_ctl'
character(len=kchara), parameter, private hd_high_comp = 'high_comp_ctl'
character(len=kchara), parameter, private hd_strat_ctl = 'stratified_ctl'
character(len=kchara), parameter, private hd_takepiro_ctl = 'takepiro_model_ctl'
character(len=kchara), parameter, private hd_strat_sigma = 'stratified_sigma_ctl'
character(len=kchara), parameter, private hd_strat_width = 'stratified_width_ctl'
character(len=kchara), parameter, private hd_strat_outer = 'stratified_outer_r_ctl'
character(len=kchara), parameter, private hd_position = 'depth'
character(len=kchara), parameter, private hd_temp_value = 'temperature'
character(len=kchara), parameter, private hd_comp_value = 'composition'
Function/Subroutine Documentation
bcast_ref_scalar_ctl()
subroutine t_ctl_data_temp_model::bcast_ref_scalar_ctl (type(reference_temperature_ctl), intent(inout) refs_ctl)
Definition at line 252 of file t_ctl_data_temp_model.f90.
References bcast_control_arrays::bcast_ctl_type_c1(), bcast_ref_value_ctl(), bcast_takepiro_ctl(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by t_ctl_data_mhd_model::bcast_sph_mhd_model().
bcast_ref_value_ctl()
subroutine, private t_ctl_data_temp_model::bcast_ref_value_ctl (type(reference_point_control), intent(inout) ref_ctl) private
Definition at line 354 of file t_ctl_data_temp_model.f90.
References bcast_control_arrays::bcast_ctl_type_r1(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by bcast_ref_scalar_ctl().
bcast_takepiro_ctl()
subroutine, private t_ctl_data_temp_model::bcast_takepiro_ctl (type(takepiro_model_control), intent(inout) takepiro_ctl) private
Definition at line 370 of file t_ctl_data_temp_model.f90.
References bcast_control_arrays::bcast_ctl_type_r1(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by bcast_ref_scalar_ctl().
read_ref_comp_ctl()
subroutine, private t_ctl_data_temp_model::read_ref_comp_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(reference_point_control), intent(inout) ref_ctl, type(buffer_for_control), intent(inout) c_buf) private
Definition at line 299 of file t_ctl_data_temp_model.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_comp_value, hd_position, t_read_control_elements::load_one_line_from_control(), and t_control_array_real::read_real_ctl_type().
Referenced by read_refcomp_ctl().
read_ref_temp_ctl()
subroutine, private t_ctl_data_temp_model::read_ref_temp_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(reference_point_control), intent(inout) ref_ctl, type(buffer_for_control), intent(inout) c_buf) private
Definition at line 274 of file t_ctl_data_temp_model.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_position, hd_temp_value, t_read_control_elements::load_one_line_from_control(), and t_control_array_real::read_real_ctl_type().
Referenced by read_reftemp_ctl().
read_refcomp_ctl()
subroutine t_ctl_data_temp_model::read_refcomp_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(reference_temperature_ctl), intent(inout) refc_ctl, type(buffer_for_control), intent(inout) c_buf)
Definition at line 214 of file t_ctl_data_temp_model.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_filterd_advection, hd_high_comp, hd_low_comp, hd_ref_comp, hd_strat_ctl, hd_takepiro_ctl, t_read_control_elements::load_one_line_from_control(), t_control_array_character::read_chara_ctl_type(), read_ref_comp_ctl(), and read_takepiro_ctl().
Referenced by t_ctl_data_mhd_model::read_sph_mhd_model().
read_reftemp_ctl()
subroutine t_ctl_data_temp_model::read_reftemp_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(reference_temperature_ctl), intent(inout) reft_ctl, type(buffer_for_control), intent(inout) c_buf)
Definition at line 177 of file t_ctl_data_temp_model.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_filterd_advection, hd_high_temp, hd_low_temp, hd_ref_temp, hd_strat_ctl, hd_takepiro_ctl, t_read_control_elements::load_one_line_from_control(), t_control_array_character::read_chara_ctl_type(), read_ref_temp_ctl(), and read_takepiro_ctl().
Referenced by t_ctl_data_mhd_model::read_sph_mhd_model().
read_takepiro_ctl()
subroutine, private t_ctl_data_temp_model::read_takepiro_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(takepiro_model_control), intent(inout) takepiro_ctl, type(buffer_for_control), intent(inout) c_buf) private
Definition at line 324 of file t_ctl_data_temp_model.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_strat_outer, hd_strat_sigma, hd_strat_width, t_read_control_elements::load_one_line_from_control(), and t_control_array_real::read_real_ctl_type().
Referenced by read_refcomp_ctl(), and read_reftemp_ctl().
Variable Documentation
hd_comp_value
character(len=kchara), parameter, private t_ctl_data_temp_model::hd_comp_value = 'composition' private
Definition at line 156 of file t_ctl_data_temp_model.f90.
Referenced by read_ref_comp_ctl().
hd_filterd_advection
character(len=kchara), parameter, private t_ctl_data_temp_model::hd_filterd_advection = 'filtered_advection_ctl' private
Definition at line 129 of file t_ctl_data_temp_model.f90.
Referenced by read_refcomp_ctl(), and read_reftemp_ctl().
hd_high_comp
character(len=kchara), parameter, private t_ctl_data_temp_model::hd_high_comp = 'high_comp_ctl' private
Definition at line 135 of file t_ctl_data_temp_model.f90.
Referenced by read_refcomp_ctl().
hd_high_temp
character(len=kchara), parameter, private t_ctl_data_temp_model::hd_high_temp = 'high_temp_ctl' private
Definition at line 126 of file t_ctl_data_temp_model.f90.
Referenced by read_reftemp_ctl().
hd_low_comp
character(len=kchara), parameter, private t_ctl_data_temp_model::hd_low_comp = 'low_comp_ctl' private
Definition at line 133 of file t_ctl_data_temp_model.f90.
Referenced by read_refcomp_ctl().
hd_low_temp
character(len=kchara), parameter, private t_ctl_data_temp_model::hd_low_temp = 'low_temp_ctl' private
Definition at line 124 of file t_ctl_data_temp_model.f90.
Referenced by read_reftemp_ctl().
hd_position
character(len=kchara), parameter, private t_ctl_data_temp_model::hd_position = 'depth' private
Definition at line 152 of file t_ctl_data_temp_model.f90.
Referenced by read_ref_comp_ctl(), and read_ref_temp_ctl().
hd_ref_comp
character(len=kchara), parameter, private t_ctl_data_temp_model::hd_ref_comp = 'ref_comp_ctl' private
Definition at line 131 of file t_ctl_data_temp_model.f90.
Referenced by read_refcomp_ctl().
hd_ref_temp
character(len=kchara), parameter, private t_ctl_data_temp_model::hd_ref_temp = 'ref_temp_ctl' private
Definition at line 122 of file t_ctl_data_temp_model.f90.
Referenced by read_reftemp_ctl().
hd_strat_ctl
character(len=kchara), parameter, private t_ctl_data_temp_model::hd_strat_ctl = 'stratified_ctl' private
Definition at line 138 of file t_ctl_data_temp_model.f90.
Referenced by read_refcomp_ctl(), and read_reftemp_ctl().
hd_strat_outer
character(len=kchara), parameter, private t_ctl_data_temp_model::hd_strat_outer = 'stratified_outer_r_ctl' private
Definition at line 147 of file t_ctl_data_temp_model.f90.
Referenced by read_takepiro_ctl().
hd_strat_sigma
character(len=kchara), parameter, private t_ctl_data_temp_model::hd_strat_sigma = 'stratified_sigma_ctl' private
Definition at line 143 of file t_ctl_data_temp_model.f90.
Referenced by read_takepiro_ctl().
hd_strat_width
character(len=kchara), parameter, private t_ctl_data_temp_model::hd_strat_width = 'stratified_width_ctl' private
Definition at line 145 of file t_ctl_data_temp_model.f90.
Referenced by read_takepiro_ctl().
hd_takepiro_ctl
character(len=kchara), parameter, private t_ctl_data_temp_model::hd_takepiro_ctl = 'takepiro_model_ctl' private
Definition at line 140 of file t_ctl_data_temp_model.f90.
Referenced by read_refcomp_ctl(), and read_reftemp_ctl().
hd_temp_value
character(len=kchara), parameter, private t_ctl_data_temp_model::hd_temp_value = 'temperature' private
Definition at line 154 of file t_ctl_data_temp_model.f90.
Referenced by read_ref_temp_ctl().