CALYPSO: set_to_send_buffer Module Reference
set_to_send_buffer Module Reference
Arbitrary components data communication.
Functions/Subroutines
subroutine set_to_send_buf_1 (nnod_org, nnod_send, inod_export, X_org, WS)
subroutine set_to_send_buf_2 (nnod_org, nnod_send, inod_export, X_org, WS)
subroutine set_to_send_buf_3 (nnod_org, nnod_send, inod_export, X_org, WS)
subroutine set_to_send_buf_6 (nnod_org, nnod_send, inod_export, X_org, WS)
subroutine set_to_send_buf_n (NB, nnod_org, nnod_send, inod_export, X_org, WS)
subroutine set_to_send_buf_n_mod (NB, nnod_org, npe_send, nnod_send, istack_send, inod_export, X_org, WS)
subroutine set_to_send_buf_int (nnod_org, nnod_send, inod_export, iX_org, iWS)
subroutine set_to_send_buf_i8 (nnod_org, nnod_send, inod_export, i8X_org, i8WS)
Detailed Description
Arbitrary components data communication.
      subroutine set_to_send_buf_1(nnod_org,                          &
     &          nnod_send, inod_export, X_org, WS)
      subroutine set_to_send_buf_2(nnod_org,                          &
     &          nnod_send, inod_export, X_org, WS)
      subroutine set_to_send_buf_3(nnod_org,                          &
     &          nnod_send, inod_export, X_org, WS)
      subroutine set_to_send_buf_6(nnod_org,                          &
     &          nnod_send, inod_export, X_org, WS)
      subroutine set_to_send_buf_N(NB, nnod_org,                      &
     &          nnod_send, inod_export, X_org, WS)
      subroutine set_to_send_buf_N_mod(NB, nnod_org,                  &
     &          npe_send, nnod_send, istack_send, inod_export,        &
     &          X_org, WS)
      subroutine set_to_send_buf_int(nnod_org,                        &
     &          nnod_send, inod_export, iX_org, iWS)
      subroutine set_to_send_buf_i8(nnod_org,                         &
     &          nnod_send, inod_export, i8X_org, i8WS)
Parameters
NB Number of components for communication
nnod_org Number of data points for origin
npe_send Number of processses to send
isend_self Integer flag to copy within own process
nnod_send Number of data points to send
istack_send(0:npe_send) End points of send buffer for each process
inod_export(nnod_send) local node ID to copy in send buffer
X_org(NB*nnod_org) Send data
Function/Subroutine Documentation
set_to_send_buf_1()
subroutine set_to_send_buffer::set_to_send_buf_1 (integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) nnod_send, integer(kind = kint), dimension(nnod_send), intent(in) inod_export, real (kind=kreal), dimension(nnod_org), intent(in) X_org, real (kind=kreal), dimension(nnod_send), intent(inout) WS)
Definition at line 55 of file set_to_send_buffer.f90.
Referenced by calypso_sr::calypso_send_recv().
set_to_send_buf_2()
subroutine set_to_send_buffer::set_to_send_buf_2 (integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) nnod_send, integer(kind = kint), dimension(nnod_send), intent(in) inod_export, real (kind=kreal), dimension(2*nnod_org), intent(in) X_org, real (kind=kreal), dimension(2*nnod_send), intent(inout) WS)
Definition at line 79 of file set_to_send_buffer.f90.
Referenced by calypso_sr_2::calypso_send_recv_2().
set_to_send_buf_3()
subroutine set_to_send_buffer::set_to_send_buf_3 (integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) nnod_send, integer(kind = kint), dimension(nnod_send), intent(in) inod_export, real (kind=kreal), dimension(3*nnod_org), intent(in) X_org, real (kind=kreal), dimension(3*nnod_send), intent(inout) WS)
Definition at line 104 of file set_to_send_buffer.f90.
Referenced by calypso_sr_3::calypso_send_recv_3().
set_to_send_buf_6()
subroutine set_to_send_buffer::set_to_send_buf_6 (integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) nnod_send, integer(kind = kint), dimension(nnod_send), intent(in) inod_export, real (kind=kreal), dimension(6*nnod_org), intent(in) X_org, real (kind=kreal), dimension(6*nnod_send), intent(inout) WS)
Definition at line 130 of file set_to_send_buffer.f90.
Referenced by calypso_sr_6::calypso_send_recv_6().
set_to_send_buf_i8()
subroutine set_to_send_buffer::set_to_send_buf_i8 (integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) nnod_send, integer(kind = kint), dimension(nnod_send), intent(in) inod_export, integer (kind = kint_gl), dimension(nnod_org), intent(in) i8X_org, integer (kind = kint_gl), dimension(nnod_send), intent(inout) i8WS)
Definition at line 253 of file set_to_send_buffer.f90.
Referenced by calypso_sr_int::calypso_send_recv_int8().
set_to_send_buf_int()
subroutine set_to_send_buffer::set_to_send_buf_int (integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) nnod_send, integer(kind = kint), dimension(nnod_send), intent(in) inod_export, integer (kind=kint), dimension(nnod_org), intent(in) iX_org, integer (kind=kint), dimension(nnod_send), intent(inout) iWS)
Definition at line 229 of file set_to_send_buffer.f90.
Referenced by calypso_sr_int::calypso_send_recv_int().
set_to_send_buf_n()
subroutine set_to_send_buffer::set_to_send_buf_n (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) nnod_send, integer(kind = kint), dimension(nnod_send), intent(in) inod_export, real (kind=kreal), dimension(nb*nnod_org), intent(in) X_org, real (kind=kreal), dimension(nb*nnod_send), intent(inout) WS)
Definition at line 159 of file set_to_send_buffer.f90.
Referenced by spherical_srs_n::calypso_sph_to_send_n(), sel_spherical_srs::sel_calypso_to_send_n(), and select_copy_from_recv::sel_cppy_to_send_buf_n().
set_to_send_buf_n_mod()
subroutine set_to_send_buffer::set_to_send_buf_n_mod (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) npe_send, integer(kind = kint), intent(in) nnod_send, integer(kind = kint), dimension(0:npe_send), intent(in) istack_send, integer(kind = kint), dimension(nnod_send), intent(in) inod_export, real (kind=kreal), dimension(nb*nnod_org), intent(in) X_org, real (kind=kreal), dimension(nb*nnod_send), intent(inout) WS)
Definition at line 188 of file set_to_send_buffer.f90.
Referenced by select_copy_from_recv::sel_cppy_to_send_buf_n().