CALYPSO: calypso_mpi_int Module Reference
calypso_mpi_int Module Reference
MPI communication routines for integer in Calypso.
Functions/Subroutines
subroutine calypso_mpi_bcast_one_int (buffer, root)
subroutine calypso_mpi_bcast_int (buffer, count, root)
subroutine calypso_mpi_reduce_int (i_local, i_global, count, operation, destination)
subroutine calypso_mpi_allreduce_one_int (i_local, i_global, operation)
subroutine calypso_mpi_allreduce_int (i_local, i_global, count, operation)
subroutine calypso_mpi_scatter_one_int (isendbuf, irecvbuf, root)
subroutine calypso_mpi_gather_one_int (isendbuf, irecvbuf, root)
subroutine calypso_mpi_allgather_one_int (isendbuf, irecvbuf)
subroutine calypso_mpi_allgather_int (isendbuf, n_send, irecvbuf, n_recv)
subroutine calypso_mpi_alltoall_one_int (isendbuf, irecvbuf)
subroutine calypso_mpi_seek_write_int (id_mpi_file, ioffset, num, i_vector, sta_IO)
subroutine calypso_mpi_seek_read_int (id_mpi_file, ioffset, num, i_vector, sta_IO)
Detailed Description
MPI communication routines for integer in Calypso.
      subroutine calypso_mpi_bcast_one_int(buffer, root)
        integer, intent(in) :: root
        integer(kind = kint), intent(inout) :: buffer
      subroutine calypso_mpi_bcast_int(buffer, count, root)
        integer, intent(in) :: root
        integer(kind = kint_gl), intent(in) :: count
        integer(kind = kint), intent(inout) :: buffer(count)
      subroutine calypso_mpi_reduce_int                               &
     &         (i_local, i_global, count, operation, destination)
        integer, intent(in) :: destination
        integer, intent(in) :: operation
        integer(kind = kint_gl), intent(in) :: count
        integer(kind = kint), intent(in) ::    i_local(count)
        integer(kind = kint), intent(inout) :: i_global(count)
      subroutine calypso_mpi_allreduce_one_int                        &
     &         (i_local, i_global, operation)
        integer, intent(in) :: operation
        integer(kind = kint), intent(in) ::    i_local
        integer(kind = kint), intent(inout) :: i_global
      subroutine calypso_mpi_allreduce_int                            &
     &         (i_local, i_global, count, operation)
        integer, intent(in) :: operation
        integer(kind = kint_gl), intent(in) :: count
        integer(kind = kint), intent(in) ::    i_local(count)
        integer(kind = kint), intent(inout) :: i_global(count)
      subroutine calypso_mpi_scatter_one_int(isendbuf, irecvbuf, root)
        integer, intent(in) :: root
        integer(kind = kint), intent(in) ::    isendbuf(nprocs)
        integer(kind = kint), intent(inout) :: irecvbuf
      subroutine calypso_mpi_gather_one_int(isendbuf, irecvbuf, root)
        integer(kind = kint), intent(in) ::    isendbuf
        integer(kind = kint), intent(inout) :: irecvbuf(nprocs)
      subroutine calypso_mpi_allgather_one_int(isendbuf, irecvbuf)
        integer(kind = kint), intent(in) ::    isendbuf
        integer(kind = kint), intent(inout) :: irecvbuf(nprocs)
      subroutine calypso_mpi_allgather_int                            &
     &         (isendbuf, n_send, irecvbuf, n_recv)
        integer(kind = kint), intent(in) :: n_send, n_recv
        integer(kind = kint), intent(in) ::    isendbuf(n_send)
        integer(kind = kint), intent(inout) :: irecvbuf(nprocs*n_recv)
      subroutine calypso_mpi_alltoall_one_int(isendbuf, irecvbuf)
        integer(kind = kint), intent(in) ::    isendbuf(nprocs)
        integer(kind = kint), intent(inout) :: irecvbuf(nprocs)
      subroutine calypso_mpi_seek_write_int                           &
     &         (id_mpi_file, ioffset, num, i_vector, sta_IO)
        integer, intent(in) ::  id_mpi_file
        integer(kind = MPI_OFFSET_KIND), intent(in) :: ioffset
        integer(kind = kint_gl), intent(in) :: num
        integer(kind = kint), intent(in) :: i_vector(num)
        integer, intent(inout) :: sta_IO(MPI_STATUS_SIZE)
      subroutine calypso_mpi_seek_read_int                            &
     &         (id_mpi_file, ioffset, num, i_vector, sta_IO)
        integer, intent(in) ::  id_mpi_file
        integer(kind = MPI_OFFSET_KIND), intent(in) :: ioffset
        integer(kind = kint_gl), intent(in) :: num
        integer(kind = kint), intent(inout) :: i_vector(num)
        integer, intent(inout) :: sta_IO(MPI_STATUS_SIZE)
Parameters
icode error code
message message to output
Function/Subroutine Documentation
calypso_mpi_allgather_int()
subroutine calypso_mpi_int::calypso_mpi_allgather_int (integer(kind = kint), dimension(n_send), intent(in) isendbuf, integer(kind = kint), intent(in) n_send, integer(kind = kint), dimension(nprocs*n_recv), intent(inout) irecvbuf, integer(kind = kint), intent(in) n_recv)
Definition at line 261 of file calypso_mpi_int.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_integer, and calypso_mpi::ierr_mpi.
calypso_mpi_allgather_one_int()
subroutine calypso_mpi_int::calypso_mpi_allgather_one_int (integer(kind = kint), intent(in) isendbuf, integer(kind = kint), dimension(nprocs), intent(inout) irecvbuf)
Definition at line 245 of file calypso_mpi_int.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_integer, and calypso_mpi::ierr_mpi.
Referenced by pickup_sph_spectr::const_picked_sph_address(), const_global_element_ids::count_number_of_node_stack(), const_global_element_ids::count_number_of_node_stack4(), bcast_comm_stacks_sph::mpi_bcast_comm_stacks_sph(), bcast_comm_stacks_sph::para_bcast_comm_stacks_sph(), count_nnod_4_asseble_sph::s_count_nnod_4_asseble_sph(), and t_calypso_mpi_io_param::set_numbers_2_head_node().
calypso_mpi_allreduce_int()
subroutine calypso_mpi_int::calypso_mpi_allreduce_int (integer(kind = kint), dimension(count), intent(in) i_local, integer(kind = kint), dimension(count), intent(inout) i_global, integer(kind = kint_gl), intent(in) count, integer, intent(in) operation)
Definition at line 181 of file calypso_mpi_int.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_integer, m_constants::huge_20, and calypso_mpi::ierr_mpi.
Referenced by const_fem_mesh_sph_mhd::const_global_rtp_mesh(), gz_mpi_viewer_mesh_io::gz_mpi_write_viewer_grp_data(), and mpi_viewer_mesh_io::mpi_write_viewer_grp_data().
calypso_mpi_allreduce_one_int()
subroutine calypso_mpi_int::calypso_mpi_allreduce_one_int (integer(kind = kint), intent(in) i_local, integer(kind = kint), intent(inout) i_global, integer, intent(in) operation)
Definition at line 162 of file calypso_mpi_int.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_integer, and calypso_mpi::ierr_mpi.
Referenced by analyzer_check_sph_grids::analyze_check_sph_grids(), analyzer_compare_sph_rst::analyze_compare_sph_restart(), analyzer_test_sph::analyze_test_sph(), const_global_element_ids::check_element_position(), parallel_fem_mesh_init::check_whole_num_of_elements(), set_loaded_data_4_sph::set_fem_center_mode_4_sph(), set_loaded_data_4_sph::set_index_flags_4_rj(), set_loaded_data_4_sph::set_index_flags_4_sph(), and find_node_and_patch_psf::set_node_and_patch_psf().
calypso_mpi_alltoall_one_int()
subroutine calypso_mpi_int::calypso_mpi_alltoall_one_int (integer(kind = kint), dimension(nprocs), intent(in) isendbuf, integer(kind = kint), dimension(nprocs), intent(inout) irecvbuf)
Definition at line 278 of file calypso_mpi_int.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_integer, and calypso_mpi::ierr_mpi.
calypso_mpi_bcast_int()
subroutine calypso_mpi_int::calypso_mpi_bcast_int (integer(kind = kint), dimension(count), intent(inout) buffer, integer(kind = kint_gl), intent(in) count, integer, intent(in) root)
Definition at line 110 of file calypso_mpi_int.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_integer, m_constants::huge_20, and calypso_mpi::ierr_mpi.
Referenced by bcast_control_arrays::bcast_ctl_array_ci(), bcast_control_arrays::bcast_ctl_array_ci3(), bcast_control_arrays::bcast_ctl_array_i1(), bcast_control_arrays::bcast_ctl_array_i2(), bcast_control_arrays::bcast_ctl_array_i2r(), bcast_control_arrays::bcast_ctl_array_i2r2(), bcast_control_arrays::bcast_ctl_array_i3(), bcast_control_arrays::bcast_ctl_array_icr(), bcast_control_arrays::bcast_ctl_array_ir(), bcast_control_arrays::bcast_ctl_type_c_i3(), bcast_control_arrays::bcast_ctl_type_i2(), bcast_control_arrays::bcast_ctl_type_i3(), t_each_sph_boundary_io_data::bcast_each_bc_item_ctl(), const_fem_mesh_sph_mhd::const_global_rtp_mesh(), rayleigh_restart_io::init_rayleigh_restart_input(), gz_field_block_mpi_io::read_field_num_gz_mpi(), field_data_mpi_io::read_field_num_mpi(), bcast_comm_stacks_sph::set_bcast_comm_stacks_sph(), share_field_data::share_field_io_names(), share_field_data::share_field_stack(), r_interpolate_marged_sph::share_r_interpolation_tbl(), share_spectr_index_data::share_sph_rj_data(), and mpi_load_mesh_data::sync_group_name_4_empty().
calypso_mpi_bcast_one_int()
subroutine calypso_mpi_int::calypso_mpi_bcast_one_int (integer(kind = kint), intent(inout) buffer, integer, intent(in) root)
Definition at line 93 of file calypso_mpi_int.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_integer, and calypso_mpi::ierr_mpi.
Referenced by t_ctl_data_node_boundary::bcast_bc_4_node_ctl(), t_ctl_data_surf_boundary::bcast_bc_4_surf_ctl(), t_sph_boundary_input_data::bcast_boundary_spectr_file(), t_ctl_data_mhd_normalize::bcast_coef_term_ctl(), t_ctl_data_mhd_forces::bcast_coriolis_ctl(), t_ctl_data_crust_filter::bcast_crustal_filtering_ctl(), bcast_control_arrays::bcast_ctl_array_c1(), bcast_control_arrays::bcast_ctl_array_c2(), bcast_control_arrays::bcast_ctl_array_c2r(), bcast_control_arrays::bcast_ctl_array_c3(), bcast_control_arrays::bcast_ctl_array_ci(), bcast_control_arrays::bcast_ctl_array_ci3(), bcast_control_arrays::bcast_ctl_array_cr(), bcast_control_arrays::bcast_ctl_array_cr2(), bcast_control_arrays::bcast_ctl_array_i1(), bcast_control_arrays::bcast_ctl_array_i2(), bcast_control_arrays::bcast_ctl_array_i2r(), bcast_control_arrays::bcast_ctl_array_i2r2(), bcast_control_arrays::bcast_ctl_array_i3(), bcast_control_arrays::bcast_ctl_array_icr(), bcast_control_arrays::bcast_ctl_array_ir(), bcast_control_arrays::bcast_ctl_array_r1(), bcast_control_arrays::bcast_ctl_array_r2(), bcast_control_arrays::bcast_ctl_array_r3(), bcast_4_platform_ctl::bcast_ctl_data_4_platform(), bcast_4_time_step_ctl::bcast_ctl_data_4_time_step(), set_control_newsph::bcast_ctl_param_newsph(), bcast_control_arrays::bcast_ctl_type_c1(), bcast_control_arrays::bcast_ctl_type_c3(), bcast_control_arrays::bcast_ctl_type_c_i3(), bcast_control_arrays::bcast_ctl_type_i1(), bcast_control_arrays::bcast_ctl_type_i2(), bcast_control_arrays::bcast_ctl_type_i3(), bcast_control_arrays::bcast_ctl_type_r1(), bcast_control_arrays::bcast_ctl_type_r2(), bcast_control_arrays::bcast_ctl_type_r3(), t_ctl_data_mhd_normalize::bcast_dimless_ctl(), t_each_sph_boundary_io_data::bcast_each_bc_item_num(), bcast_file_io_parameter::bcast_fem_file_io_flags(), bcast_4_platform_ctl::bcast_fem_mesh_control(), bcast_file_io_parameter::bcast_field_io_parameter(), t_control_data_isosurfaces::bcast_files_4_iso_ctl(), t_control_data_sections::bcast_files_4_psf_ctl(), t_control_data_4_fld_on_psf::bcast_fld_on_psf_control(), t_ctl_data_mhd_forces::bcast_forces_ctl(), t_ctl_data_mhd_forces::bcast_gravity_ctl(), t_ctl_data_induct_norm::bcast_induction_ctl(), t_control_data_4_iso::bcast_iso_control_data(), t_control_data_4_iso_def::bcast_iso_define_control(), t_ctl_data_mhd_forces::bcast_magneto_ctl(), bcast_4_assemble_sph_ctl::bcast_merge_control_data(), bcast_4_assemble_sph_ctl::bcast_merge_field_data(), bcast_4_assemble_sph_ctl::bcast_merge_step_data(), t_ctl_data_mhd_evolution::bcast_mhd_layer_ctl(), t_ctl_data_mhd_evolution::bcast_mhd_time_evo_ctl(), t_ctl_data_momentum_norm::bcast_momentum_ctl(), t_ctl_data_node_monitor::bcast_monitor_data_ctl(), bcast_4_assemble_sph_ctl::bcast_newrst_control(), t_ctl_data_gen_sph_shell::bcast_parallel_shell_ctl(), bcast_4_field_ctl::bcast_phys_data_ctl(), t_control_data_4_psf::bcast_psf_control_data(), t_ctl_data_temp_model::bcast_ref_scalar_ctl(), t_ctl_data_temp_model::bcast_ref_value_ctl(), t_ctl_data_mhd_evo_scheme::bcast_restart_ctl(), t_control_data_section_only::bcast_section_control_data(), t_control_data_4_psf_def::bcast_section_def_control(), t_ctl_data_sph_mhd_control::bcast_sph_mhd_control(), t_ctl_data_mhd::bcast_sph_mhd_ctl_data(), t_ctl_data_mhd_model::bcast_sph_mhd_model(), bcast_4_sph_monitor_ctl::bcast_sph_monitoring_ctl(), t_ctl_data_const_sph_mesh::bcast_sph_shell_define_ctl(), t_control_data_surfacings::bcast_surfacing_controls(), t_ctl_data_temp_model::bcast_takepiro_ctl(), t_ctl_data_termal_norm::bcast_thermal_ctl(), t_ctl_data_mhd_evo_scheme::bcast_time_loop_ctl(), rayleigh_restart_io::init_rayleigh_restart_input(), t_sph_mhd_monitor_data_io::open_sph_vol_rms_file_mhd(), gz_field_block_mpi_io::read_field_header_gz_mpi(), field_data_mpi_io::read_field_header_mpi(), share_field_data::share_each_field_data(), share_field_data::share_each_field_io_data(), share_field_data::share_field_io_names(), share_field_data::share_field_num(), r_interpolate_marged_sph::share_icb_and_cmb_radius(), r_interpolate_marged_sph::share_r_interpolation_tbl(), share_spectr_index_data::share_sph_rj_data(), share_field_data::share_time_step_data(), and field_data_mpi_io::sync_field_time_mpi().
calypso_mpi_gather_one_int()
subroutine calypso_mpi_int::calypso_mpi_gather_one_int (integer(kind = kint), intent(in) isendbuf, integer(kind = kint), dimension(nprocs), intent(inout) irecvbuf, integer, intent(in) root)
Definition at line 226 of file calypso_mpi_int.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_integer, and calypso_mpi::ierr_mpi.
calypso_mpi_reduce_int()
subroutine calypso_mpi_int::calypso_mpi_reduce_int (integer(kind = kint), dimension(count), intent(in) i_local, integer(kind = kint), dimension(count), intent(inout) i_global, integer(kind = kint_gl), intent(in) count, integer, intent(in) operation, integer, intent(in) destination)
Definition at line 134 of file calypso_mpi_int.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_integer, m_constants::huge_20, and calypso_mpi::ierr_mpi.
Referenced by init_sph_mhd_elapsed_label::check_num_of_process_4_sph().
calypso_mpi_scatter_one_int()
subroutine calypso_mpi_int::calypso_mpi_scatter_one_int (integer(kind = kint), dimension(nprocs), intent(in) isendbuf, integer(kind = kint), intent(inout) irecvbuf, integer, intent(in) root)
Definition at line 207 of file calypso_mpi_int.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_integer, and calypso_mpi::ierr_mpi.
calypso_mpi_seek_read_int()
subroutine calypso_mpi_int::calypso_mpi_seek_read_int (integer, intent(in) id_mpi_file, integer(kind = mpi_offset_kind), intent(in) ioffset, integer(kind = kint_gl), intent(in) num, integer(kind = kint), dimension(num), intent(inout) i_vector, integer, dimension(mpi_status_size), intent(inout) sta_IO)
Definition at line 323 of file calypso_mpi_int.f90.
References calypso_mpi::calypso_integer, m_constants::huge_20, calypso_mpi::ierr_mpi, and m_precision::kint.
Referenced by m_calypso_mpi_io::mpi_read_int_b().
calypso_mpi_seek_write_int()
subroutine calypso_mpi_int::calypso_mpi_seek_write_int (integer, intent(in) id_mpi_file, integer(kind = mpi_offset_kind), intent(in) ioffset, integer(kind = kint_gl), intent(in) num, integer(kind = kint), dimension(num), intent(in) i_vector, integer, dimension(mpi_status_size), intent(inout) sta_IO)
Definition at line 292 of file calypso_mpi_int.f90.
References calypso_mpi::calypso_integer, m_constants::huge_20, calypso_mpi::ierr_mpi, and m_precision::kint.
Referenced by m_calypso_mpi_io::mpi_write_int_b().