CALYPSO: gz_field_data_io_b Module Reference
gz_field_data_io_b Module Reference
Output merged binary field file using MPI-IO.
Functions/Subroutines
subroutine gz_write_step_data_b (id_rank, i_time_step_IO, time_IO, delta_t_IO, zbuf)
subroutine gz_write_field_data_b (nnod, num_field, ntot_comp, ncomp_field, field_name, d_nod, zbuf)
subroutine gz_read_step_data_b (zbuf, id_rank, i_time_step_IO, time_IO, delta_t_IO, istack_merged, num_field)
subroutine gz_read_field_data_b (zbuf, nnod, num_field, ncomp, field_name, vect)
Detailed Description
Output merged binary field file using MPI-IO.
      subroutine gz_write_step_data_b                                 &
     &         (id_rank, i_time_step_IO, time_IO, delta_t_IO, zbuf)
      subroutine gz_write_field_data_b(nnod, num_field,               &
     &          ntot_comp, ncomp_field, field_name, d_nod, zbuf)
        type(buffer_4_gzip), intent(inout) :: zbuf
      subroutine gz_read_step_data_b(zbuf, id_rank,                   &
     &          i_time_step_IO, time_IO, delta_t_IO,                  &
     &          istack_merged, num_field)
      subroutine gz_read_field_data_b                                 &
     &         (zbuf, nnod, num_field, ncomp, field_name, vect)
        type(buffer_4_gzip), intent(inout) :: zbuf
Function/Subroutine Documentation
gz_read_field_data_b()
subroutine gz_field_data_io_b::gz_read_field_data_b (type(buffer_4_gzip), intent(inout) zbuf, integer(kind = kint_gl), intent(in) nnod, integer(kind = kint), intent(in) num_field, integer(kind = kint), intent(in) ncomp, character(len=kchara), dimension(num_field), intent(inout) field_name, real(kind = kreal), dimension(nnod,ncomp), intent(inout) vect)
Definition at line 153 of file gz_field_data_IO_b.f90.
References transfer_to_long_integers::cast_long(), gz_binary_io::gz_read_2d_vector_b(), and gz_binary_io::gz_read_mul_character_b().
Referenced by gz_field_file_io_b::gz_rd_alloc_st_fld_file_b(), gz_ucd_field_file_io_b::gz_read_alloc_ucd_2_fld_file_b(), gz_field_file_io_b::gz_read_step_field_file_b(), and gz_ucd_field_file_io_b::gz_read_ucd_2_fld_file_b().
gz_read_step_data_b()
subroutine gz_field_data_io_b::gz_read_step_data_b (type(buffer_4_gzip), intent(inout) zbuf, integer, intent(in) id_rank, integer(kind=kint), intent(inout) i_time_step_IO, real(kind = kreal), intent(inout) time_IO, real(kind = kreal), intent(inout) delta_t_IO, integer(kind = kint_gl), dimension(1), intent(inout) istack_merged, integer(kind = kint), intent(inout) num_field)
Definition at line 107 of file gz_field_data_IO_b.f90.
References gz_binary_io::gz_read_mul_int8_b(), gz_binary_io::gz_read_one_integer_b(), gz_binary_io::gz_read_one_real_b(), and m_error_ids::ierr_file.
Referenced by gz_field_file_io_b::gz_rd_alloc_st_fld_file_b(), gz_field_file_io_b::gz_rd_alloc_st_fld_head_b(), gz_ucd_field_file_io_b::gz_read_alloc_ucd_2_fld_file_b(), gz_field_file_io_b::gz_read_step_field_file_b(), and gz_ucd_field_file_io_b::gz_read_ucd_2_fld_file_b().
gz_write_field_data_b()
subroutine gz_field_data_io_b::gz_write_field_data_b (integer(kind=kint_gl), intent(in) nnod, integer(kind=kint), intent(in) num_field, integer(kind=kint), intent(in) ntot_comp, integer(kind=kint), dimension(num_field), intent(in) ncomp_field, character(len=kchara), dimension(num_field), intent(in) field_name, real(kind = kreal), dimension(nnod,ntot_comp), intent(in) d_nod, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 69 of file gz_field_data_IO_b.f90.
References transfer_to_long_integers::cast_long(), gz_binary_io::gz_write_2d_vector_b(), gz_binary_io::gz_write_mul_character_b(), gz_binary_io::gz_write_mul_int8_b(), gz_binary_io::gz_write_mul_integer_b(), and gz_binary_io::gz_write_one_integer_b().
Referenced by gz_field_file_io_b::gz_write_step_fld_file_b(), and gz_ucd_field_file_io_b::gz_write_ucd_2_fld_file_b().
gz_write_step_data_b()
subroutine gz_field_data_io_b::gz_write_step_data_b (integer, intent(in) id_rank, integer(kind = kint), intent(in) i_time_step_IO, real(kind = kreal), intent(in) time_IO, real(kind = kreal), intent(in) delta_t_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 42 of file gz_field_data_IO_b.f90.
References gz_binary_io::gz_write_one_integer_b(), and gz_binary_io::gz_write_one_real_b().
Referenced by gz_field_file_io_b::gz_write_step_fld_file_b(), and gz_ucd_field_file_io_b::gz_write_ucd_2_fld_file_b().