CALYPSO: mpi_mesh_data_io_b Module Reference
mpi_mesh_data_io_b Module Reference
Routines for gzipped binary mesh data IO.
Functions/Subroutines
subroutine mpi_write_geometry_data_b (IO_param, mesh_IO)
subroutine mpi_write_mesh_groups_b (IO_param, mesh_group_IO)
subroutine mpi_read_num_node_ele (IO_param, mesh_IO)
subroutine mpi_read_num_node_ele_b (IO_param, mesh_IO)
subroutine mpi_read_geometry_data_b (IO_param, mesh_IO)
subroutine mpi_read_mesh_groups_b (IO_param, mesh_group_IO)
Detailed Description
Routines for gzipped binary mesh data IO.
      subroutine mpi_write_geometry_data_b(IO_param, mesh_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(mesh_geometry), intent(in) :: mesh_IO
      subroutine mpi_write_mesh_groups_b(IO_param, mesh_group_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(mesh_groups), intent(in) :: mesh_group_IO
      subroutine mpi_read_geometry_data_b(IO_param, mesh_IO)
      subroutine mpi_read_mesh_groups_b(IO_param, mesh_group_IO)
      subroutine mpi_read_num_node_ele_b(IO_param, mesh_IO)
      subroutine mpi_read_num_node_ele(IO_param, mesh_IO)
        type(mesh_geometry), intent(inout) :: mesh_IO
        type(mesh_groups), intent(inout) ::   mesh_group_IO
Function/Subroutine Documentation
mpi_read_geometry_data_b()
subroutine mpi_mesh_data_io_b::mpi_read_geometry_data_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 127 of file MPI_mesh_data_IO_b.f90.
References mpi_read_num_node_ele_b().
Referenced by mpi_mesh_file_io_b::mpi_read_mesh_file_b(), and mpi_mesh_file_io_b::mpi_read_mesh_geometry_b().
mpi_read_mesh_groups_b()
subroutine mpi_mesh_data_io_b::mpi_read_mesh_groups_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(mesh_groups), intent(inout) mesh_group_IO)
Definition at line 151 of file MPI_mesh_data_IO_b.f90.
References mpi_groups_io_b::mpi_read_group_data_b(), and mpi_groups_io_b::mpi_read_surf_grp_data_b().
Referenced by mpi_mesh_file_io_b::mpi_read_mesh_file_b().
mpi_read_num_node_ele()
subroutine mpi_mesh_data_io_b::mpi_read_num_node_ele (type(calypso_mpi_io_params), intent(inout) IO_param, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 89 of file MPI_mesh_data_IO_b.f90.
References mpi_domain_data_io_b::mpi_read_domain_info_b(), and mpi_node_geometry_io_b::mpi_read_number_of_node_b().
Referenced by mpi_mesh_file_io_b::mpi_read_node_size_b(), and mpi_read_num_node_ele_b().
mpi_read_num_node_ele_b()
subroutine mpi_mesh_data_io_b::mpi_read_num_node_ele_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 106 of file MPI_mesh_data_IO_b.f90.
References mpi_node_geometry_io_b::mpi_read_geometry_info_b(), and mpi_read_num_node_ele().
Referenced by mpi_read_geometry_data_b(), and mpi_mesh_file_io_b::mpi_read_geometry_size_b().
mpi_write_geometry_data_b()
subroutine mpi_mesh_data_io_b::mpi_write_geometry_data_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(mesh_geometry), intent(in) mesh_IO)
Definition at line 47 of file MPI_mesh_data_IO_b.f90.
References mpi_domain_data_io_b::mpi_write_domain_info_b(), mpi_domain_data_io_b::mpi_write_export_data_b(), mpi_node_geometry_io_b::mpi_write_geometry_info_b(), and mpi_domain_data_io_b::mpi_write_import_data_b().
Referenced by mpi_mesh_file_io_b::mpi_write_mesh_file_b().
mpi_write_mesh_groups_b()
subroutine mpi_mesh_data_io_b::mpi_write_mesh_groups_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(mesh_groups), intent(in) mesh_group_IO)
Definition at line 69 of file MPI_mesh_data_IO_b.f90.
References mpi_groups_io_b::mpi_write_grp_data_b(), and mpi_groups_io_b::mpi_write_surf_grp_data_b().
Referenced by mpi_mesh_file_io_b::mpi_write_mesh_file_b().