CALYPSO: t_sph_ispack_fft Module Reference
t_sph_ispack_fft Module Reference
Fourier transform for spherical harmonics transform
using ISPACK.
Data Types
type work_each_ispack
Structure for each thread.
type work_for_ispack
Structure to use ISPACK.
Functions/Subroutines
subroutine init_sph_ispack (nidx_rtp, maxirt_rtp_smp, ncomp, ispack_t)
subroutine finalize_sph_ispack (ispack_t)
subroutine verify_sph_ispack (nidx_rtp, maxirt_rtp_smp, ncomp, ispack_t)
subroutine sph_fttruf_to_send (nnod_rtp, nidx_rtp, irt_rtp_smp_stack, ncomp, n_WS, irev_sr_rtp, X_rtp, WS, ispack_t)
subroutine sph_fttrub_from_recv (nnod_rtp, nidx_rtp, irt_rtp_smp_stack, ncomp, n_WR, irev_sr_rtp, WR, X_rtp, ispack_t)
subroutine, private alloc_work_4_ispack (Nfft, ispack_t)
subroutine, private alloc_const_4_ispack (nfft, ispack_t)
subroutine, private dealloc_work_4_ispack (ispack_t)
subroutine, private dealloc_const_4_ispack (ispack_t)
Detailed Description
Fourier transform for spherical harmonics transform
using ISPACK.
  ---------------------------------------------------------------------
      subroutine init_sph_ISPACK(nidx_rtp, maxirt_rtp_smp, ncomp,     &
     &          ispack_t)
      subroutine finalize_sph_ISPACK(ispack_t)
      subroutine verify_sph_ISPACK(nidx_rtp, maxirt_rtp_smp, ncomp,   &
     &          ispack_t)
 ------------------------------------------------------------------
 wrapper subroutine for initierize FFT for ISPACK
 ------------------------------------------------------------------
      subroutine sph_FTTRUF_to_send(nnod_rtp, nidx_rtp,               &
     &          irt_rtp_smp_stack, ncomp, n_WS, irev_sr_rtp,          &
     &          X_rtp, WS, ispack_t)
 ------------------------------------------------------------------
 wrapper subroutine for forward Fourier transform by ISPACK
 a_{k} = \frac{2}{Nfft} \sum_{j=0}^{Nfft-1} x_{j} \cos (\frac{2\pi j k}{Nfft})
 b_{k} = \frac{2}{Nfft} \sum_{j=0}^{Nfft-1} x_{j} \cos (\frac{2\pi j k}{Nfft})
 a_{0} = \frac{1}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
 K = Nfft/2....
 a_{k} = \frac{1}{Nfft} \sum_{j=0}^{Nfft-1} x_{j} \cos (\frac{2\pi j k}{Nfft})
 ------------------------------------------------------------------
      subroutine sph_FTTRUB_from_recv(nnod_rtp, nidx_rtp,             &
     &          irt_rtp_smp_stack, ncomp, n_WR, irev_sr_rtp,          &
     &          WR, X_rtp, ispack_t)
 ------------------------------------------------------------------
 wrapper subroutine for backward Fourier transform by ISPACK
 x_{k} = a_{0} + (-1)^{j} a_{Nfft/2} + sum_{k=1}^{Nfft/2-1}
 (a_{k} \cos(2\pijk/Nfft) + b_{k} \sin(2\pijk/Nfft))
 ------------------------------------------------------------------
 i = 1:     a_{0}
 i = 2:     a_{Nfft/2}
 i = 3:     a_{1}
 i = 4:     b_{1}
 ...
 i = 2*k+1: a_{k}
 i = 2*k+2: b_{k}
 ...
 i = Nfft-1:   a_{Nfft/2-1}
 i = Nfft:     b_{Nfft/2-1}
 ------------------------------------------------------------------
Parameters
Nsmp Number of SMP processors
Nstacksmp(0:Nsmp) End number for each SMP process
M Number of components for Fourier transforms
Nfft Data length for eadh FFT
X(M,Nfft) Data for Fourier transform
Function/Subroutine Documentation
alloc_const_4_ispack()
subroutine, private t_sph_ispack_fft::alloc_const_4_ispack (integer(kind = kint), intent(in) nfft, type(work_for_ispack), intent(inout) ispack_t) private
Definition at line 355 of file t_sph_ISPACK_FFT.f90.
Referenced by init_sph_ispack(), and verify_sph_ispack().
alloc_work_4_ispack()
subroutine, private t_sph_ispack_fft::alloc_work_4_ispack (integer(kind = kint), intent(in) Nfft, type(work_for_ispack), intent(inout) ispack_t) private
Definition at line 334 of file t_sph_ISPACK_FFT.f90.
References m_machine_parameter::np_smp.
Referenced by init_sph_ispack(), and verify_sph_ispack().
dealloc_const_4_ispack()
subroutine, private t_sph_ispack_fft::dealloc_const_4_ispack (type(work_for_ispack), intent(inout) ispack_t) private
Definition at line 386 of file t_sph_ISPACK_FFT.f90.
Referenced by finalize_sph_ispack(), and verify_sph_ispack().
dealloc_work_4_ispack()
subroutine, private t_sph_ispack_fft::dealloc_work_4_ispack (type(work_for_ispack), intent(inout) ispack_t) private
Definition at line 369 of file t_sph_ISPACK_FFT.f90.
References m_machine_parameter::np_smp.
Referenced by finalize_sph_ispack(), and verify_sph_ispack().
finalize_sph_ispack()
subroutine t_sph_ispack_fft::finalize_sph_ispack (type(work_for_ispack), intent(inout) ispack_t)
Definition at line 131 of file t_sph_ISPACK_FFT.f90.
References dealloc_const_4_ispack(), and dealloc_work_4_ispack().
init_sph_ispack()
subroutine t_sph_ispack_fft::init_sph_ispack (integer(kind = kint), dimension(3), intent(in) nidx_rtp, integer(kind = kint), intent(in) maxirt_rtp_smp, integer(kind = kint), intent(in) ncomp, type(work_for_ispack), intent(inout) ispack_t)
Definition at line 110 of file t_sph_ISPACK_FFT.f90.
References alloc_const_4_ispack(), and alloc_work_4_ispack().
sph_fttrub_from_recv()
subroutine t_sph_ispack_fft::sph_fttrub_from_recv (integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(3), intent(in) nidx_rtp, integer(kind = kint), dimension(0:np_smp), intent(in) irt_rtp_smp_stack, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) n_WR, integer(kind = kint), dimension(nnod_rtp), intent(in) irev_sr_rtp, real (kind=kreal), dimension(n_wr), intent(inout) WR, real(kind = kreal), dimension(irt_rtp_smp_stack(np_smp),nidx_rtp(3),ncomp), intent(inout) X_rtp, type(work_for_ispack), intent(inout) ispack_t)
Definition at line 257 of file t_sph_ISPACK_FFT.f90.
References m_constants::half.
sph_fttruf_to_send()
subroutine t_sph_ispack_fft::sph_fttruf_to_send (integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(3), intent(in) nidx_rtp, integer(kind = kint), dimension(0:np_smp), intent(in) irt_rtp_smp_stack, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) n_WS, integer(kind = kint), dimension(nnod_rtp), intent(in) irev_sr_rtp, real(kind = kreal), dimension(irt_rtp_smp_stack(np_smp),nidx_rtp(3),ncomp), intent(in) X_rtp, real (kind=kreal), dimension(n_ws), intent(inout) WS, type(work_for_ispack), intent(inout) ispack_t)
Definition at line 180 of file t_sph_ISPACK_FFT.f90.
References m_constants::two.
verify_sph_ispack()
subroutine t_sph_ispack_fft::verify_sph_ispack (integer(kind = kint), dimension(3), intent(in) nidx_rtp, integer(kind = kint), intent(in) maxirt_rtp_smp, integer(kind = kint), intent(in) ncomp, type(work_for_ispack), intent(inout) ispack_t)
Definition at line 143 of file t_sph_ISPACK_FFT.f90.
References alloc_const_4_ispack(), alloc_work_4_ispack(), dealloc_const_4_ispack(), and dealloc_work_4_ispack().