CALYPSO: set_edge_data_by_ele Module Reference
set_edge_data_by_ele Module Reference
Functions/Subroutines
subroutine count_num_edges_by_ele (ntot_id, ntot_list, istack_edge_hash, iend_edge_hash, iedge_flag, numedge)
subroutine set_edges_connect_by_ele (numele, numedge, nnod_4_ele, nnod_4_edge, ie, ntot_id, ntot_list, istack_edge_hash, iend_edge_hash, iedge_hash, iedge_flag, ie_edge, iedge_4_ele, node_on_edge)
subroutine set_edges_connect_4_sf (numele, numsurf, numedge, nnod_4_surf, nnod_4_edge, ie_surf, iedge_4_ele, ntot_id, ntot_list, istack_edge_hash, iedge_hash, iedge_flag, ie_edge, iedge_4_sf)
subroutine set_part_edges_4_ele (numele, nunmedge_part, iedge_4_ele, ntot_id, ntot_list, istack_edge_hash, iend_edge_hash, iedge_hash, iedge_flag, iedge_part)
Function/Subroutine Documentation
count_num_edges_by_ele()
subroutine set_edge_data_by_ele::count_num_edges_by_ele (integer(kind = kint_gl), intent(in) ntot_id, integer(kind = kint_gl), intent(in) ntot_list, integer(kind = kint_gl), dimension(0:ntot_id), intent(in) istack_edge_hash, integer(kind = kint_gl), intent(in) iend_edge_hash, integer(kind = kint_gl), dimension(ntot_list), intent(in) iedge_flag, integer(kind = kint), intent(inout) numedge)
Definition at line 36 of file set_edge_data_by_ele.f90.
Referenced by const_edge_data::construct_edge_data().
set_edges_connect_4_sf()
subroutine set_edge_data_by_ele::set_edges_connect_4_sf (integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) numsurf, integer(kind = kint), intent(in) numedge, integer(kind = kint), intent(in) nnod_4_surf, integer(kind = kint), intent(in) nnod_4_edge, integer(kind = kint), dimension(numsurf, nnod_4_surf), intent(in) ie_surf, integer(kind = kint), dimension(numele,nedge_4_ele), intent(in) iedge_4_ele, integer(kind = kint_gl), intent(in) ntot_id, integer(kind = kint_gl), intent(in) ntot_list, integer(kind = kint_gl), dimension(0:ntot_id), intent(in) istack_edge_hash, integer(kind = kint), dimension(ntot_list,2), intent(in) iedge_hash, integer(kind = kint_gl), dimension(ntot_list), intent(in) iedge_flag, integer(kind = kint), dimension(numedge,nnod_4_edge), intent(in) ie_edge, integer(kind = kint), dimension(numsurf,nedge_4_surf), intent(inout) iedge_4_sf)
Definition at line 138 of file set_edge_data_by_ele.f90.
References m_geometry_constants::nedge_4_surf, and m_geometry_constants::node_on_edge_sf_l.
Referenced by const_edge_data::construct_edge_data().
set_edges_connect_by_ele()
subroutine set_edge_data_by_ele::set_edges_connect_by_ele (integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) numedge, integer(kind = kint), intent(in) nnod_4_ele, integer(kind = kint), intent(in) nnod_4_edge, integer(kind = kint), dimension(numele, nnod_4_ele), intent(in) ie, integer(kind = kint_gl), intent(in) ntot_id, integer(kind = kint_gl), intent(in) ntot_list, integer(kind = kint_gl), dimension(0:ntot_id), intent(in) istack_edge_hash, integer(kind = kint_gl), intent(in) iend_edge_hash, integer(kind = kint), dimension(ntot_list,2), intent(in) iedge_hash, integer(kind = kint_gl), dimension(ntot_list), intent(in) iedge_flag, integer(kind = kint), dimension(numedge,nnod_4_edge), intent(inout) ie_edge, integer(kind = kint), dimension(numele,nedge_4_ele), intent(inout) iedge_4_ele, integer(kind = kint), dimension(nnod_4_edge,nedge_4_ele), intent(in) node_on_edge)
Definition at line 65 of file set_edge_data_by_ele.f90.
Referenced by const_edge_data::construct_edge_data().
set_part_edges_4_ele()
subroutine set_edge_data_by_ele::set_part_edges_4_ele (integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) nunmedge_part, integer(kind = kint), dimension(numele,nedge_4_ele), intent(in) iedge_4_ele, integer(kind = kint_gl), intent(in) ntot_id, integer(kind = kint_gl), intent(in) ntot_list, integer(kind = kint_gl), dimension(0:ntot_id), intent(in) istack_edge_hash, integer(kind = kint_gl), intent(in) iend_edge_hash, integer(kind = kint), dimension(ntot_list,2), intent(in) iedge_hash, integer(kind = kint_gl), dimension(ntot_list), intent(in) iedge_flag, integer(kind = kint), dimension(nunmedge_part), intent(inout) iedge_part)
Definition at line 200 of file set_edge_data_by_ele.f90.