CALYPSO: write_field_labels Module Reference
write_field_labels Module Reference
Write field labels in one line.
Functions/Subroutines
integer(kind=kint) function count_label_list_length (num, field_list)
character(len=length_tot) function make_field_list (length_tot, num, field_list)
character(len=len_org+len_add+4) function append_to_field_list (len_org, list_org, len_add, added)
subroutine write_one_label (id_file, label1)
subroutine write_vector_label (id_file, label_v)
subroutine write_sym_tensor_label (id_file, label_st)
subroutine write_two_labels (id_file, label1, label2)
subroutine write_three_labels (id_file, label1, label2, label3)
subroutine write_four_labels (id_file, label1, label2, label3, label4)
subroutine write_six_labels (id_file, label1, label2, label3, label4, label5, label6)
subroutine write_multi_labels (id_file, nlabel, labels)
subroutine write_seven_labels (id_file, label1, label2, label3, label4, label5, label6, label7)
subroutine write_one_label_cont (id_file, label1)
Detailed Description
Write field labels in one line.
      integer(kind = kint) function                                   &
     &                    count_label_list_length(num, field_list)
      function make_field_list(length_tot, num, field_list)
        character(len = length_tot) :: make_field_list
      function append_to_field_list(len_org, list_org, len_add, added)
        character(len = len_org+len_add+4) :: make_field_list
      subroutine write_one_label(id_file, label1)
      subroutine write_vector_label(id_file, label_v)
      subroutine write_sym_tensor_label(id_file, label_st)
      subroutine write_two_labels(id_file, label1, label2)
      subroutine write_three_labels(id_file, label1, label2, label3)
      subroutine write_four_labels(id_file, label1, label2,           &
     &          label3, label4)
      subroutine write_six_labels(id_file, label1, label2,            &
     &          label3, label4, label5, label6)
      subroutine write_seven_labels(id_file, label1, label2,          &
     &          label3, label4, label5, label6, label7)
      subroutine write_multi_labels(id_file, nlabel, labels)
      subroutine write_one_label_cont(id_file, label1)
Function/Subroutine Documentation
append_to_field_list()
character(len = len_org+len_add+4) function write_field_labels::append_to_field_list (integer(kind = kint), intent(in) len_org, character(len = len_org), intent(in) list_org, integer(kind = kint), intent(in) len_add, character(len = len_add), intent(in) added)
Definition at line 90 of file write_field_labels.f90.
count_label_list_length()
integer(kind = kint) function write_field_labels::count_label_list_length (integer(kind = kint), intent(in) num, character(len = kchara), dimension(num), intent(in) field_list)
Definition at line 48 of file write_field_labels.f90.
Referenced by mpi_sph_gauss_coefs_io::write_sph_gauss_header_mpi().
make_field_list()
character(len = length_tot) function write_field_labels::make_field_list (integer(kind = kint), intent(in) length_tot, integer(kind = kint), intent(in) num, character(len = kchara), dimension(num), intent(in) field_list)
Definition at line 67 of file write_field_labels.f90.
write_four_labels()
subroutine write_field_labels::write_four_labels (integer(kind = kint), intent(in) id_file, character(len=kchara), intent(in) label1, character(len=kchara), intent(in) label2, character(len=kchara), intent(in) label3, character(len=kchara), intent(in) label4)
Definition at line 167 of file write_field_labels.f90.
References write_one_label_cont().
write_multi_labels()
subroutine write_field_labels::write_multi_labels (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) nlabel, character(len=kchara), dimension(nlabel), intent(in) labels)
Definition at line 201 of file write_field_labels.f90.
References write_one_label_cont().
Referenced by t_cal_max_indices::open_maximum_file(), t_pickup_sph_spectr_data::write_pick_sph_file_header(), sph_mean_spectr_header_io::write_sph_mean_sq_header(), sph_mean_spectr_header_io::write_sph_vol_mean_sq_header(), write_sym_tensor_label(), t_picked_sph_spectr_data_io::write_tave_sph_spec_monitor(), and write_vector_label().
write_one_label()
subroutine write_field_labels::write_one_label (integer(kind = kint), intent(in) id_file, character(len=kchara), intent(in) label1)
Definition at line 106 of file write_field_labels.f90.
References write_one_label_cont().
write_one_label_cont()
subroutine write_field_labels::write_one_label_cont (integer(kind = kint), intent(in) id_file, character(len=kchara), intent(in) label1)
Definition at line 238 of file write_field_labels.f90.
Referenced by write_four_labels(), write_multi_labels(), write_one_label(), write_seven_labels(), write_six_labels(), write_three_labels(), and write_two_labels().
write_seven_labels()
subroutine write_field_labels::write_seven_labels (integer(kind = kint), intent(in) id_file, character(len=kchara), intent(in) label1, character(len=kchara), intent(in) label2, character(len=kchara), intent(in) label3, character(len=kchara), intent(in) label4, character(len=kchara), intent(in) label5, character(len=kchara), intent(in) label6, character(len=kchara), intent(in) label7)
Definition at line 217 of file write_field_labels.f90.
References write_one_label_cont().
write_six_labels()
subroutine write_field_labels::write_six_labels (integer(kind = kint), intent(in) id_file, character(len=kchara), intent(in) label1, character(len=kchara), intent(in) label2, character(len=kchara), intent(in) label3, character(len=kchara), intent(in) label4, character(len=kchara), intent(in) label5, character(len=kchara), intent(in) label6)
Definition at line 183 of file write_field_labels.f90.
References write_one_label_cont().
write_sym_tensor_label()
subroutine write_field_labels::write_sym_tensor_label (integer(kind = kint), intent(in) id_file, character(len=kchara), dimension(6), intent(in) label_st)
Definition at line 129 of file write_field_labels.f90.
References write_multi_labels().
write_three_labels()
subroutine write_field_labels::write_three_labels (integer(kind = kint), intent(in) id_file, character(len=kchara), intent(in) label1, character(len=kchara), intent(in) label2, character(len=kchara), intent(in) label3)
Definition at line 154 of file write_field_labels.f90.
References write_one_label_cont().
write_two_labels()
subroutine write_field_labels::write_two_labels (integer(kind = kint), intent(in) id_file, character(len=kchara), intent(in) label1, character(len=kchara), intent(in) label2)
Definition at line 142 of file write_field_labels.f90.
References write_one_label_cont().
write_vector_label()
subroutine write_field_labels::write_vector_label (integer(kind = kint), intent(in) id_file, character(len=kchara), dimension(3), intent(in) label_v)
Definition at line 117 of file write_field_labels.f90.
References write_multi_labels().