CALYPSO: set_import_sph_center_mesh Module Reference
set_import_sph_center_mesh Module Reference
Functions/Subroutines
subroutine count_import_4_center_mesh (ip_r, ip_t, jp_r, jp_t, stbl, num_import)
subroutine count_import_4_ctr_shell_mesh (ip_r, ip_t, jp_r, jp_t, stbl, num_import)
subroutine count_import_4_ctr_npole_mesh (ip_r, ip_t, jp_r, jp_t, stbl, num_import)
subroutine set_import_rtp_center_mesh (ip_r, ip_t, jp_r, jp_t, icou, stbl, nod_comm)
subroutine set_import_rtp_ctr_shell_mesh (ip_r, ip_t, jp_r, jp_t, icou, stbl, nod_comm)
subroutine set_import_rtp_ctr_npole_mesh (ip_r, ip_t, jp_r, jp_t, icou, stbl, nod_comm)
Function/Subroutine Documentation
count_import_4_center_mesh()
subroutine set_import_sph_center_mesh::count_import_4_center_mesh (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, integer(kind = kint), intent(in) jp_r, integer(kind = kint), intent(in) jp_t, type(comm_table_make_sph), intent(in) stbl, integer(kind = kint), intent(inout) num_import)
Definition at line 38 of file set_import_sph_center_mesh.f90.
Referenced by const_comm_tbl_4_sph_mesh::count_import_4_sph_mesh().
count_import_4_ctr_npole_mesh()
subroutine set_import_sph_center_mesh::count_import_4_ctr_npole_mesh (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, integer(kind = kint), intent(in) jp_r, integer(kind = kint), intent(in) jp_t, type(comm_table_make_sph), intent(in) stbl, integer(kind = kint), intent(inout) num_import)
Definition at line 83 of file set_import_sph_center_mesh.f90.
Referenced by const_comm_tbl_4_sph_mesh::count_import_4_sph_mesh().
count_import_4_ctr_shell_mesh()
subroutine set_import_sph_center_mesh::count_import_4_ctr_shell_mesh (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, integer(kind = kint), intent(in) jp_r, integer(kind = kint), intent(in) jp_t, type(comm_table_make_sph), intent(in) stbl, integer(kind = kint), intent(inout) num_import)
Definition at line 57 of file set_import_sph_center_mesh.f90.
Referenced by const_comm_tbl_4_sph_mesh::count_import_4_sph_mesh().
set_import_rtp_center_mesh()
subroutine set_import_sph_center_mesh::set_import_rtp_center_mesh (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, integer(kind = kint), intent(in) jp_r, integer(kind = kint), intent(in) jp_t, integer(kind = kint), intent(inout) icou, type(comm_table_make_sph), intent(inout) stbl, type(communication_table), intent(inout) nod_comm)
Definition at line 103 of file set_import_sph_center_mesh.f90.
References cal_sph_node_addresses::sph_center_node_id().
Referenced by const_comm_tbl_4_sph_mesh::set_import_rtp_sph_mesh().
set_import_rtp_ctr_npole_mesh()
subroutine set_import_sph_center_mesh::set_import_rtp_ctr_npole_mesh (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, integer(kind = kint), intent(in) jp_r, integer(kind = kint), intent(in) jp_t, integer(kind = kint), intent(inout) icou, type(comm_table_make_sph), intent(inout) stbl, type(communication_table), intent(inout) nod_comm)
Definition at line 190 of file set_import_sph_center_mesh.f90.
References m_constants::ione, and cal_sph_node_addresses::sph_center_np_node_id().
Referenced by const_comm_tbl_4_sph_mesh::set_import_rtp_sph_mesh().
set_import_rtp_ctr_shell_mesh()
subroutine set_import_sph_center_mesh::set_import_rtp_ctr_shell_mesh (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, integer(kind = kint), intent(in) jp_r, integer(kind = kint), intent(in) jp_t, integer(kind = kint), intent(inout) icou, type(comm_table_make_sph), intent(inout) stbl, type(communication_table), intent(inout) nod_comm)
Definition at line 131 of file set_import_sph_center_mesh.f90.
References m_constants::ione, and cal_sph_node_addresses::sph_ctr_shell_node_id().
Referenced by const_comm_tbl_4_sph_mesh::set_import_rtp_sph_mesh().