CALYPSO: gz_read_psf_binary_data Module Reference
gz_read_psf_binary_data Module Reference
Output merged VTK file usgin MPI-IO.
Functions/Subroutines
subroutine read_psf_phys_num_bin_gz (nprocs, nnod, num_field, itmp1_mp_gz, zbuf)
subroutine read_psf_phys_name_bin_gz (num_field, ntot_comp, ncomp_field, field_name, zbuf)
subroutine read_psf_phys_data_bin_gz (nprocs, nnod, ntot_comp, d_nod, itmp1_mp_gz, zbuf)
subroutine read_psf_node_num_bin_gz (nprocs, nnod, itmp1_mp_gz, zbuf)
subroutine read_psf_node_data_bin_gz (nprocs, nnod, inod_global, xx, itmp1_mp_gz, zbuf)
subroutine read_psf_ele_num_bin_gz (nprocs, nele, nnod_ele, itmp1_mp_gz, zbuf)
subroutine read_psf_ele_connect_bin_gz (nprocs, nele, nnod_ele, iele_global, ie_psf, itmp1_mp_gz, zbuf)
Detailed Description
Output merged VTK file usgin MPI-IO.
      subroutine read_psf_phys_num_bin_gz                             &
     &         (nprocs, nnod, num_field, itmp1_mp_gz, zbuf)
      subroutine read_psf_phys_name_bin_gz                            &
     &         (num_field, ntot_comp, ncomp_field, field_name, zbuf)
      subroutine read_psf_phys_data_bin_gz                            &
     &         (nprocs, nnod, ntot_comp, d_nod, itmp1_mp_gz, zbuf)
      subroutine read_psf_node_num_bin_gz                             &
     &         (nprocs, nnod, itmp1_mp_gz, zbuf)
      subroutine read_psf_node_data_bin_gz                            &
     &         (nprocs, nnod, inod_global, xx, itmp1_mp_gz, zbuf)
      subroutine read_psf_ele_num_bin_gz                              &
     &         (nprocs, nele, nnod_ele, itmp1_mp_gz, zbuf)
      subroutine read_psf_ele_connect_bin_gz                          &
     &         (nprocs, nele, nnod_ele, iele_global, ie_psf,          &
     &          itmp1_mp_gz, zbuf)
        type(buffer_4_gzip), intent(inout)  :: zbuf
Function/Subroutine Documentation
read_psf_ele_connect_bin_gz()
subroutine gz_read_psf_binary_data::read_psf_ele_connect_bin_gz (integer, intent(in) nprocs, integer(kind = kint_gl), intent(in) nele, integer(kind = kint), intent(in) nnod_ele, integer(kind = kint_gl), dimension(nele), intent(inout) iele_global, integer(kind = kint_gl), dimension(nele,nnod_ele), intent(inout) ie_psf, integer(kind = kint_gl), dimension(nprocs), intent(inout) itmp1_mp_gz, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 216 of file gz_read_psf_binary_data.f90.
References transfer_to_long_integers::cast_long(), and gz_binary_io::gz_read_mul_int8_b().
Referenced by gz_read_udt_from_bin_data::gz_read_alloc_psf_bin_grid_data(), and gz_read_udt_from_bin_data::gz_read_psf_bin_grid_data().
read_psf_ele_num_bin_gz()
subroutine gz_read_psf_binary_data::read_psf_ele_num_bin_gz (integer, intent(in) nprocs, integer(kind = kint_gl), intent(inout) nele, integer(kind = kint), intent(inout) nnod_ele, integer(kind = kint_gl), dimension(nprocs), intent(inout) itmp1_mp_gz, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 179 of file gz_read_psf_binary_data.f90.
References transfer_to_long_integers::cast_long(), gz_binary_io::gz_read_mul_int8_b(), and m_constants::ione.
Referenced by gz_read_udt_from_bin_data::gz_read_alloc_psf_bin_grid_data(), and gz_read_udt_from_bin_data::gz_read_psf_bin_grid_data().
read_psf_node_data_bin_gz()
subroutine gz_read_psf_binary_data::read_psf_node_data_bin_gz (integer, intent(in) nprocs, integer(kind=kint_gl), intent(in) nnod, integer(kind=kint_gl), dimension(nnod), intent(inout) inod_global, real(kind = kreal), dimension(nnod,3), intent(inout) xx, integer(kind = kint_gl), dimension(nprocs), intent(inout) itmp1_mp_gz, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 148 of file gz_read_psf_binary_data.f90.
References m_constants::ithree, and read_psf_phys_data_bin_gz().
Referenced by gz_read_udt_from_bin_data::gz_read_alloc_psf_bin_grid_data(), and gz_read_udt_from_bin_data::gz_read_psf_bin_grid_data().
read_psf_node_num_bin_gz()
subroutine gz_read_psf_binary_data::read_psf_node_num_bin_gz (integer, intent(in) nprocs, integer(kind=kint_gl), intent(inout) nnod, integer(kind = kint_gl), dimension(nprocs), intent(inout) itmp1_mp_gz, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 121 of file gz_read_psf_binary_data.f90.
References transfer_to_long_integers::cast_long(), and gz_binary_io::gz_read_mul_int8_b().
Referenced by gz_read_udt_from_bin_data::gz_read_alloc_psf_bin_grid_data(), gz_read_udt_from_bin_data::gz_read_psf_bin_grid_data(), and read_psf_phys_num_bin_gz().
read_psf_phys_data_bin_gz()
subroutine gz_read_psf_binary_data::read_psf_phys_data_bin_gz (integer, intent(in) nprocs, integer(kind=kint_gl), intent(in) nnod, integer(kind=kint), intent(in) ntot_comp, real(kind = kreal), dimension(nnod,ntot_comp), intent(inout) d_nod, integer(kind = kint_gl), dimension(nprocs), intent(inout) itmp1_mp_gz, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 94 of file gz_read_psf_binary_data.f90.
References transfer_to_long_integers::cast_long(), gz_binary_io::gz_read_1d_vector_b(), and gz_binary_io::gz_read_mul_int8_b().
Referenced by gz_read_udt_from_bin_data::gz_read_alloc_psf_bin_fld_data(), gz_read_udt_from_bin_data::gz_read_psf_bin_field_data(), and read_psf_node_data_bin_gz().
read_psf_phys_name_bin_gz()
subroutine gz_read_psf_binary_data::read_psf_phys_name_bin_gz (integer(kind=kint), intent(in) num_field, integer(kind=kint), intent(inout) ntot_comp, integer(kind=kint), dimension(num_field), intent(inout) ncomp_field, character(len=kchara), dimension(num_field), intent(inout) field_name, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 70 of file gz_read_psf_binary_data.f90.
References transfer_to_long_integers::cast_long(), gz_binary_io::gz_read_mul_character_b(), and gz_binary_io::gz_read_mul_integer_b().
Referenced by gz_read_udt_from_bin_data::gz_read_alloc_psf_bin_fld_data(), and gz_read_udt_from_bin_data::gz_read_psf_bin_field_data().
read_psf_phys_num_bin_gz()
subroutine gz_read_psf_binary_data::read_psf_phys_num_bin_gz (integer, intent(in) nprocs, integer(kind=kint_gl), intent(in) nnod, integer(kind=kint), intent(inout) num_field, integer(kind = kint_gl), dimension(nprocs), intent(inout) itmp1_mp_gz, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 46 of file gz_read_psf_binary_data.f90.
References gz_binary_io::gz_read_one_integer_b(), and read_psf_node_num_bin_gz().
Referenced by gz_read_udt_from_bin_data::gz_read_alloc_psf_bin_fld_data(), and gz_read_udt_from_bin_data::gz_read_psf_bin_field_data().