CALYPSO: t_poloidal_rotation Module Reference
t_poloidal_rotation Module Reference
Set Rotation data for Coriolis term.
Data Types
type sph_rotation
Functions/Subroutines
subroutine set_rot_earth_4_sph (sph_rlm, sph_rj, fl_prop, omega_sph)
subroutine set_3dir_rot_earth_sph_rj (sph_rj, fl_prop, omega_sph)
subroutine dealloc_rot_rlm_data (omega_sph)
subroutine dealloc_rot_rj_data (omega_sph)
subroutine, private alloc_rot_rlm_data (nri_rlm, omega_sph)
subroutine, private alloc_rot_rj_data (nri_rj, omega_sph)
subroutine, private set_zdir_rot_earth_4_sph (nri, r, rotate, omega)
subroutine, private set_3dir_rot_earth_4_sph (nri, r, rotate, omega)
subroutine, private set_rotation_spectr (nri, r, rotate, rot_e, drot_e, d2rot_e)
Detailed Description
Set Rotation data for Coriolis term.
Function/Subroutine Documentation
alloc_rot_rj_data()
subroutine, private t_poloidal_rotation::alloc_rot_rj_data (integer(kind = kint), intent(in) nri_rj, type(sph_rotation), intent(inout) omega_sph) private
Definition at line 182 of file t_poloidal_rotation.f90.
Referenced by set_3dir_rot_earth_sph_rj(), and set_rot_earth_4_sph().
alloc_rot_rlm_data()
subroutine, private t_poloidal_rotation::alloc_rot_rlm_data (integer(kind = kint), intent(in) nri_rlm, type(sph_rotation), intent(inout) omega_sph) private
Definition at line 168 of file t_poloidal_rotation.f90.
Referenced by set_rot_earth_4_sph().
dealloc_rot_rj_data()
subroutine t_poloidal_rotation::dealloc_rot_rj_data (type(sph_rotation), intent(inout) omega_sph)
Definition at line 157 of file t_poloidal_rotation.f90.
dealloc_rot_rlm_data()
subroutine t_poloidal_rotation::dealloc_rot_rlm_data (type(sph_rotation), intent(inout) omega_sph)
Definition at line 147 of file t_poloidal_rotation.f90.
set_3dir_rot_earth_4_sph()
subroutine, private t_poloidal_rotation::set_3dir_rot_earth_4_sph (integer(kind = kint), intent(in) nri, real(kind = kreal), dimension(nri), intent(in) r, real(kind = kreal), dimension(3), intent(in) rotate, real(kind = kreal), dimension(nri,0:2,3), intent(inout) omega) private
Definition at line 213 of file t_poloidal_rotation.f90.
References set_rotation_spectr().
Referenced by set_3dir_rot_earth_sph_rj(), and set_rot_earth_4_sph().
set_3dir_rot_earth_sph_rj()
subroutine t_poloidal_rotation::set_3dir_rot_earth_sph_rj (type(sph_rj_grid), intent(in) sph_rj, type(fluid_property), intent(in) fl_prop, type(sph_rotation), intent(inout) omega_sph)
Definition at line 126 of file t_poloidal_rotation.f90.
References alloc_rot_rj_data(), and set_3dir_rot_earth_4_sph().
set_rot_earth_4_sph()
subroutine t_poloidal_rotation::set_rot_earth_4_sph (type(sph_rlm_grid), intent(in) sph_rlm, type(sph_rj_grid), intent(in) sph_rj, type(fluid_property), intent(in) fl_prop, type(sph_rotation), intent(inout) omega_sph)
Definition at line 97 of file t_poloidal_rotation.f90.
References alloc_rot_rj_data(), alloc_rot_rlm_data(), m_constants::one, set_3dir_rot_earth_4_sph(), and set_zdir_rot_earth_4_sph().
Referenced by init_radial_infos_sph_mhd::init_r_infos_sph_mhd().
set_rotation_spectr()
subroutine, private t_poloidal_rotation::set_rotation_spectr (integer(kind = kint), intent(in) nri, real(kind = kreal), dimension(nri), intent(in) r, real(kind = kreal), intent(in) rotate, real(kind = kreal), dimension(nri), intent(inout) rot_e, real(kind = kreal), dimension(nri), intent(inout) drot_e, real(kind = kreal), dimension(nri), intent(inout) d2rot_e) private
Definition at line 234 of file t_poloidal_rotation.f90.
References m_constants::half.
Referenced by set_3dir_rot_earth_4_sph(), and set_zdir_rot_earth_4_sph().
set_zdir_rot_earth_4_sph()
subroutine, private t_poloidal_rotation::set_zdir_rot_earth_4_sph (integer(kind = kint), intent(in) nri, real(kind = kreal), dimension(nri), intent(in) r, real(kind = kreal), intent(in) rotate, real(kind = kreal), dimension(nri,0:2), intent(inout) omega) private
Definition at line 197 of file t_poloidal_rotation.f90.
References set_rotation_spectr().
Referenced by set_rot_earth_4_sph().