CALYPSO: check_workarea_4_explicit Module Reference
check_workarea_4_explicit Module Reference
Functions/Subroutines
subroutine add_field_ctl_4_check_evo (field_ctl)
Function/Subroutine Documentation
add_field_ctl_4_check_evo()
subroutine check_workarea_4_explicit::add_field_ctl_4_check_evo (type(ctl_array_c3), intent(inout) field_ctl)
Definition at line 28 of file check_workarea_4_explicit.f90.
References add_nodal_fields_ctl::add_phys_name_ctl(), m_explicit_term_labels::check_composition, m_explicit_term_labels::check_composition_2, add_nodal_fields_ctl::check_field_list_ctl(), m_explicit_term_labels::check_heat, m_explicit_term_labels::check_heat_2, m_explicit_term_labels::check_induction, m_explicit_term_labels::check_induction_2, m_explicit_term_labels::check_momentum, m_explicit_term_labels::check_momentum_2, m_explicit_term_labels::check_potential, m_explicit_term_labels::check_potential_2, m_explicit_term_labels::check_pressure, m_explicit_term_labels::check_pressure_2, m_base_field_labels::composition, m_base_field_labels::magnetic_potential, m_base_field_labels::pressure, m_base_field_labels::temperature, and m_base_field_labels::velocity.
Referenced by add_nodal_fields_4_mhd::add_dependent_field().