CALYPSO: ucd_file_mpi_io Module Reference
ucd_file_mpi_io Module Reference
Output merged VTK file usgin MPI-IO.
Functions/Subroutines
subroutine write_ucd_data_mpi_b (IO_param_l, nnod, num_field, ntot_comp, ncomp_field, field_name, d_nod, istack_merged_intnod)
subroutine write_ucd_mesh_data_mpi_b (IO_param_l, nnod, nele, nnod_ele, xx, ie, istack_merged_intnod)
subroutine write_ucd_data_mpi (id_vtk, ioff_gl, nnod, num_field, ntot_comp, ncomp_field, field_name, d_nod, istack_merged_intnod)
subroutine write_ucd_node_mpi (id_vtk, ioff_gl, nnod, ntot_comp, xx, istack_merged_intnod, istack_merged_ele)
subroutine write_ucd_connect_mpi (id_vtk, ioff_gl, nele, nnod_ele, ie, istack_merged_ele)
Detailed Description
Output merged VTK file usgin MPI-IO.
      subroutine write_ucd_data_mpi_b(IO_param_l,                     &
     &          nnod, num_field, ntot_comp, ncomp_field,              &
     &          field_name, d_nod, istack_merged_intnod)
      subroutine write_ucd_mesh_data_mpi_b                            &
     &         (IO_param_l, nnod, nele, nnod_ele, xx, ie,             &
     &          istack_merged_intnod, istack_merged_ele)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param_l
      subroutine write_ucd_data_mpi(id_vtk, ioff_gl,                  &
     &          nnod, num_field, ntot_comp, ncomp_field,              &
     &          field_name, d_nod, istack_merged_intnod)
      subroutine write_ucd_node_mpi(id_vtk, ioff_gl, nnod,            &
     &          ntot_comp, xx, istack_merged_intnod, istack_merged_ele)
      subroutine write_ucd_connect_mpi(id_vtk, ioff_gl,               &
     &          nele, nnod_ele, ie, istack_merged_ele)
Function/Subroutine Documentation
write_ucd_connect_mpi()
subroutine ucd_file_mpi_io::write_ucd_connect_mpi (integer, intent(in) id_vtk, integer(kind = kint_gl), intent(inout) ioff_gl, integer(kind = kint_gl), intent(in) nele, integer(kind = kint), intent(in) nnod_ele, integer(kind = kint_gl), dimension(nele,nnod_ele), intent(in) ie, integer(kind = kint_gl), dimension(0:nprocs), intent(in) istack_merged_ele)
Definition at line 250 of file ucd_file_MPI_IO.f90.
References m_calypso_mpi_io::mpi_write_mul_chara_b(), calypso_mpi::my_rank, calypso_mpi::nprocs, and ucd_data_to_buffer::ucd_each_connect().
Referenced by merged_udt_vtk_file_io::write_ucd_file_mpi(), and merged_udt_vtk_file_io::write_ucd_grid_mpi().
write_ucd_data_mpi()
subroutine ucd_file_mpi_io::write_ucd_data_mpi (integer, intent(in) id_vtk, integer(kind = kint_gl), intent(inout) ioff_gl, integer(kind=kint_gl), intent(in) nnod, integer(kind=kint), intent(in) num_field, integer(kind=kint), intent(in) ntot_comp, integer(kind=kint), dimension(num_field), intent(in) ncomp_field, character(len=kchara), dimension(num_field), intent(in) field_name, real(kind = kreal), dimension(nnod,ntot_comp), intent(in) d_nod, integer(kind = kint_gl), dimension(0:nprocs), intent(in) istack_merged_intnod)
Definition at line 144 of file ucd_file_MPI_IO.f90.
References m_calypso_mpi_io::calypso_mpi_seek_write_head_c(), m_calypso_mpi_io::mpi_write_mul_chara_b(), calypso_mpi::my_rank, calypso_mpi::nprocs, ucd_data_to_buffer::ucd_each_field(), ucd_data_to_buffer::ucd_field_name(), and ucd_data_to_buffer::ucd_num_comps().
Referenced by merged_udt_vtk_file_io::write_ucd_file_mpi(), and merged_udt_vtk_file_io::write_ucd_phys_mpi().
write_ucd_data_mpi_b()
subroutine ucd_file_mpi_io::write_ucd_data_mpi_b (type(calypso_mpi_io_params), intent(inout) IO_param_l, integer(kind=kint_gl), intent(in) nnod, integer(kind=kint), intent(in) num_field, integer(kind=kint), intent(in) ntot_comp, integer(kind=kint), dimension(num_field), intent(in) ncomp_field, character(len=kchara), dimension(num_field), intent(in) field_name, real(kind = kreal), dimension(nnod,ntot_comp), intent(in) d_nod, integer(kind = kint_gl), dimension(0:nprocs), intent(in) istack_merged_intnod)
Definition at line 47 of file ucd_file_MPI_IO.f90.
References t_calypso_mpi_io_param::istack64_4_parallel_data(), mpi_binary_data_io::mpi_write_1d_vector_b(), mpi_binary_data_io::mpi_write_int8_vector_b(), mpi_binary_head_io::mpi_write_mul_charahead_b(), mpi_binary_head_io::mpi_write_mul_inthead_b(), mpi_binary_head_io::mpi_write_one_inthead_b(), and calypso_mpi::my_rank.
Referenced by write_udt_file_io_b::write_ucd_file_mpi_b(), and write_udt_file_io_b::write_ucd_phys_mpi_b().
write_ucd_mesh_data_mpi_b()
subroutine ucd_file_mpi_io::write_ucd_mesh_data_mpi_b (type(calypso_mpi_io_params), intent(inout) IO_param_l, integer(kind = kint_gl), intent(in) nnod, integer(kind = kint_gl), intent(in) nele, integer(kind = kint), intent(in) nnod_ele, real(kind = kreal), dimension(nnod,3), intent(in) xx, integer(kind = kint_gl), dimension(nele,nnod_ele), intent(in) ie, integer(kind = kint_gl), dimension(0:nprocs), intent(in) istack_merged_intnod)
Definition at line 89 of file ucd_file_MPI_IO.f90.
References t_calypso_mpi_io_param::istack64_4_parallel_data(), set_nnod_4_ele_by_type::linear_eletype_from_num(), mpi_binary_data_io::mpi_write_1d_vector_b(), mpi_binary_data_io::mpi_write_int8_vector_b(), mpi_binary_head_io::mpi_write_one_inthead_b(), mpi_binary_head_io::mpi_write_process_id_b(), and calypso_mpi::my_rank.
Referenced by write_udt_file_io_b::write_ucd_file_mpi_b(), and write_udt_file_io_b::write_ucd_grid_mpi_b().
write_ucd_node_mpi()
subroutine ucd_file_mpi_io::write_ucd_node_mpi (integer, intent(in) id_vtk, integer(kind = kint_gl), intent(inout) ioff_gl, integer(kind = kint_gl), intent(in) nnod, integer(kind = kint), intent(in) ntot_comp, real(kind = kreal), dimension(nnod,3), intent(in) xx, integer(kind = kint_gl), dimension(0:nprocs), intent(in) istack_merged_intnod, integer(kind = kint_gl), dimension(0:nprocs), intent(in) istack_merged_ele)
Definition at line 199 of file ucd_file_MPI_IO.f90.
References m_calypso_mpi_io::calypso_mpi_seek_write_head_c(), m_calypso_mpi_io::mpi_write_mul_chara_b(), calypso_mpi::my_rank, m_phys_constants::n_vector, calypso_mpi::nprocs, ucd_data_to_buffer::ucd_connect_head(), and ucd_data_to_buffer::ucd_each_field().
Referenced by merged_udt_vtk_file_io::write_ucd_file_mpi(), and merged_udt_vtk_file_io::write_ucd_grid_mpi().