CALYPSO: set_vr_rtm_for_leg_vecprod Module Reference
set_vr_rtm_for_leg_vecprod Module Reference
forward Legendre transform using dot products
Functions/Subroutines
subroutine set_vr_rtm_vector_blocked (nnod_rtm, nidx_rtm, istep_rtm, weight_rtm, asin_rtm, nd, k_rlm, mp_rlm, mn_rlm, lst, nle_rtm, ncomp, irev_sr_rtm, n_WR, WR, symp_r, asmp_t, asmp_p, symn_t, symn_p)
subroutine set_vr_rtm_scalar_blocked (nnod_rtm, nidx_rtm, istep_rtm, weight_rtm, nd, k_rlm, mp_rlm, lst, nle_rtm, ncomp, nvector, irev_sr_rtm, n_WR, WR, symp)
subroutine set_vr_rtm_vector_symmetry (nnod_rtm, nidx_rtm, istep_rtm, weight_rtm, asin_rtm, nd, k_rlm, mp_rlm, mn_rlm, nle_rtm, nlo_rtm, ncomp, irev_sr_rtm, n_WR, WR, symp_r, asmp_t, asmp_p, symn_t, symn_p, asmp_r, symp_t, symp_p, asmn_t, asmn_p)
subroutine set_vr_rtm_scalar_symmetry (nnod_rtm, nidx_rtm, istep_rtm, weight_rtm, nd, k_rlm, mp_rlm, lst, nle_rtm, nlo_rtm, ncomp, nvector, irev_sr_rtm, n_WR, WR, symp, asmp)
Detailed Description
forward Legendre transform using dot products
      subroutine set_vr_rtm_vector_blocked                            &
     &         (nnod_rtm, nidx_rtm, istep_rtm, weight_rtm, asin_rtm,  &
     &          nd, k_rlm, mp_rlm, mn_rlm, lst, nle_rtm,              &
     &          ncomp, irev_sr_rtm, n_WR, WR,                         &
     &          symp_r, asmp_t, asmp_p, symn_t, symn_p)
      subroutine set_vr_rtm_scalar_blocked(nnod_rtm, nidx_rtm,        &
     &         istep_rtm, weight_rtm, nd, k_rlm, mp_rlm, lst, nle_rtm,&
     &         ncomp, nvector, irev_sr_rtm, n_WR, WR, symp)
      subroutine set_vr_rtm_vector_symmetry                           &
     &         (nnod_rtm, nidx_rtm, istep_rtm, weight_rtm, asin_rtm,  &
     &          nd, k_rlm, mp_rlm, mn_rlm, nle_rtm, nlo_rtm,          &
     &          ncomp, irev_sr_rtm, n_WR, WR,                         &
     &          symp_r, asmp_t, asmp_p, symn_t, symn_p, asmp_r,       &
     &          symp_t, symp_p, asmn_t, asmn_p)
      subroutine set_vr_rtm_scalar_symmetry                           &
     &         (nnod_rtm, nidx_rtm, istep_rtm, weight_rtm, nd,        &
     &          k_rlm, mp_rlm, lst, nle_rtm, nlo_rtm,                 &
     &          ncomp, nvector, irev_sr_rtm, n_WR, WR, symp, asmp)
Function/Subroutine Documentation
set_vr_rtm_scalar_blocked()
subroutine set_vr_rtm_for_leg_vecprod::set_vr_rtm_scalar_blocked (integer(kind = kint), intent(in) nnod_rtm, integer(kind = kint), dimension(3), intent(in) nidx_rtm, integer(kind = kint), dimension(3), intent(in) istep_rtm, real(kind = kreal), dimension(nidx_rtm(2)), intent(in) weight_rtm, integer(kind = kint), intent(in) nd, integer(kind = kint), intent(in) k_rlm, integer(kind = kint), intent(in) mp_rlm, integer(kind = kint), intent(in) lst, integer(kind = kint), intent(in) nle_rtm, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), dimension(nnod_rtm), intent(in) irev_sr_rtm, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(in) WR, real(kind = kreal), dimension(nle_rtm), intent(inout) symp)
Definition at line 103 of file set_vr_rtm_for_leg_vecprod.f90.
set_vr_rtm_scalar_symmetry()
subroutine set_vr_rtm_for_leg_vecprod::set_vr_rtm_scalar_symmetry (integer(kind = kint), intent(in) nnod_rtm, integer(kind = kint), dimension(3), intent(in) nidx_rtm, integer(kind = kint), dimension(3), intent(in) istep_rtm, real(kind = kreal), dimension(nidx_rtm(2)), intent(in) weight_rtm, integer(kind = kint), intent(in) nd, integer(kind = kint), intent(in) k_rlm, integer(kind = kint), intent(in) mp_rlm, integer(kind = kint), intent(in) lst, integer(kind = kint), intent(in) nle_rtm, integer(kind = kint), intent(in) nlo_rtm, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), dimension(nnod_rtm), intent(in) irev_sr_rtm, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(in) WR, real(kind = kreal), dimension(nle_rtm), intent(inout) symp, real(kind = kreal), dimension(nle_rtm), intent(inout) asmp)
Definition at line 255 of file set_vr_rtm_for_leg_vecprod.f90.
Referenced by legendre_fwd_trans_symmetry::leg_fwd_trans_scalar_sym_org(), and legendre_fwd_trans_sym_spin::leg_fwd_trans_scalar_sym_spin().
set_vr_rtm_vector_blocked()
subroutine set_vr_rtm_for_leg_vecprod::set_vr_rtm_vector_blocked (integer(kind = kint), intent(in) nnod_rtm, integer(kind = kint), dimension(3), intent(in) nidx_rtm, integer(kind = kint), dimension(3), intent(in) istep_rtm, real(kind = kreal), dimension(nidx_rtm(2)), intent(in) weight_rtm, real(kind = kreal), dimension(nidx_rtm(2)), intent(in) asin_rtm, integer(kind = kint), intent(in) nd, integer(kind = kint), intent(in) k_rlm, integer(kind = kint), intent(in) mp_rlm, integer(kind = kint), intent(in) mn_rlm, integer(kind = kint), intent(in) lst, integer(kind = kint), intent(in) nle_rtm, integer(kind = kint), intent(in) ncomp, integer(kind = kint), dimension(nnod_rtm), intent(in) irev_sr_rtm, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(in) WR, real(kind = kreal), dimension(nle_rtm), intent(inout) symp_r, real(kind = kreal), dimension(nle_rtm), intent(inout) asmp_t, real(kind = kreal), dimension(nle_rtm), intent(inout) asmp_p, real(kind = kreal), dimension(nle_rtm), intent(inout) symn_t, real(kind = kreal), dimension(nle_rtm), intent(inout) symn_p)
Definition at line 44 of file set_vr_rtm_for_leg_vecprod.f90.
set_vr_rtm_vector_symmetry()
subroutine set_vr_rtm_for_leg_vecprod::set_vr_rtm_vector_symmetry (integer(kind = kint), intent(in) nnod_rtm, integer(kind = kint), dimension(3), intent(in) nidx_rtm, integer(kind = kint), dimension(3), intent(in) istep_rtm, real(kind = kreal), dimension(nidx_rtm(2)), intent(in) weight_rtm, real(kind = kreal), dimension(nidx_rtm(2)), intent(in) asin_rtm, integer(kind = kint), intent(in) nd, integer(kind = kint), intent(in) k_rlm, integer(kind = kint), intent(in) mp_rlm, integer(kind = kint), intent(in) mn_rlm, integer(kind = kint), intent(in) nle_rtm, integer(kind = kint), intent(in) nlo_rtm, integer(kind = kint), intent(in) ncomp, integer(kind = kint), dimension(nnod_rtm), intent(in) irev_sr_rtm, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(in) WR, real(kind = kreal), dimension(nle_rtm), intent(inout) symp_r, real(kind = kreal), dimension(nle_rtm), intent(inout) asmp_t, real(kind = kreal), dimension(nle_rtm), intent(inout) asmp_p, real(kind = kreal), dimension(nle_rtm), intent(inout) symn_t, real(kind = kreal), dimension(nle_rtm), intent(inout) symn_p, real(kind = kreal), dimension(nle_rtm), intent(inout) asmp_r, real(kind = kreal), dimension(nle_rtm), intent(inout) symp_t, real(kind = kreal), dimension(nle_rtm), intent(inout) symp_p, real(kind = kreal), dimension(nle_rtm), intent(inout) asmn_t, real(kind = kreal), dimension(nle_rtm), intent(inout) asmn_p)
Definition at line 144 of file set_vr_rtm_for_leg_vecprod.f90.
Referenced by legendre_fwd_trans_symmetry::leg_fwd_trans_vector_sym_org(), and legendre_fwd_trans_sym_spin::leg_fwd_trans_vector_sym_spin().