CALYPSO: material_property Module Reference
material_property Module Reference
Subroutines to set coeffiecient of each term.
Functions/Subroutines
subroutine set_material_property (depth_top, depth_bottom, iphys, MHD_prop)
subroutine, private set_fluid_property (depth_top, depth_bottom, MHD_coef_list, fl_prop)
subroutine, private set_conductive_property (depth_top, depth_bottom, MHD_coef_list, cd_prop)
subroutine, private set_thermal_property (iphys, depth_top, depth_bottom, MHD_coef_list, ht_prop)
subroutine, private set_composition_property (iphys, depth_top, depth_bottom, MHD_coef_list, cp_prop)
Detailed Description
Subroutines to set coeffiecient of each term.
      subroutine set_material_property                                &
     &         (depth_top, depth_bottom, iphys, MHD_prop)
        type(phys_address), intent(in) :: iphys
        type(MHD_evolution_param), intent(inout) :: MHD_prop
Function/Subroutine Documentation
set_composition_property()
subroutine, private material_property::set_composition_property (type(phys_address), intent(in) iphys, real(kind = kreal), intent(in) depth_top, real(kind = kreal), intent(in) depth_bottom, type(coef_parameters_list), intent(inout) MHD_coef_list, type(scalar_property), intent(inout) cp_prop) private
Definition at line 287 of file material_property.f90.
References construct_mhd_coefficient::construct_coefficient(), t_physical_property::id_no_evolution, calypso_mpi::my_rank, m_constants::one, and construct_mhd_coefficient::set_implicit_4_inf_viscous().
Referenced by set_material_property().
set_conductive_property()
subroutine, private material_property::set_conductive_property (real(kind = kreal), intent(in) depth_top, real(kind = kreal), intent(in) depth_bottom, type(coef_parameters_list), intent(inout) MHD_coef_list, type(conductive_property), intent(inout) cd_prop) private
Definition at line 168 of file material_property.f90.
References construct_mhd_coefficient::construct_coefficient(), t_physical_property::id_no_evolution, calypso_mpi::my_rank, m_constants::one, and construct_mhd_coefficient::set_implicit_4_inf_viscous().
Referenced by set_material_property().
set_fluid_property()
subroutine, private material_property::set_fluid_property (real(kind = kreal), intent(in) depth_top, real(kind = kreal), intent(in) depth_bottom, type(coef_parameters_list), intent(inout) MHD_coef_list, type(fluid_property), intent(inout) fl_prop) private
Definition at line 71 of file material_property.f90.
References construct_mhd_coefficient::construct_coefficient(), t_physical_property::id_no_evolution, calypso_mpi::my_rank, m_constants::one, and construct_mhd_coefficient::set_implicit_4_inf_viscous().
Referenced by set_material_property().
set_material_property()
subroutine material_property::set_material_property (real(kind = kreal), intent(in) depth_top, real(kind = kreal), intent(in) depth_bottom, type(phys_address), intent(in) iphys, type(mhd_evolution_param), intent(inout) MHD_prop)
Definition at line 39 of file material_property.f90.
References calypso_mpi::my_rank, set_composition_property(), set_conductive_property(), set_fluid_property(), and set_thermal_property().
Referenced by init_radial_infos_sph_mhd::init_r_infos_sph_mhd_evo().
set_thermal_property()
subroutine, private material_property::set_thermal_property (type(phys_address), intent(in) iphys, real(kind = kreal), intent(in) depth_top, real(kind = kreal), intent(in) depth_bottom, type(coef_parameters_list), intent(inout) MHD_coef_list, type(scalar_property), intent(inout) ht_prop) private
Definition at line 235 of file material_property.f90.
References construct_mhd_coefficient::construct_coefficient(), t_physical_property::id_no_evolution, calypso_mpi::my_rank, m_constants::one, and construct_mhd_coefficient::set_implicit_4_inf_viscous().
Referenced by set_material_property().