CALYPSO: t_gauss_points Module Reference
t_gauss_points Module Reference
Data Types
type gauss_integrations
type gauss_points
Functions/Subroutines
subroutine const_gauss_colatitude (num_gauss, gauss)
subroutine construct_gauss_coefs (num_gauss, gauss)
subroutine, private set_gauss_colatitude (gauss)
subroutine alloc_work_4_integration (num_inte, n_point, g_int)
subroutine dealloc_gauss_colatitude (gauss)
subroutine dealloc_gauss_points (gauss)
subroutine, private dealloc_gauss_colats (gauss)
subroutine dealloc_work_4_integration (g_int)
subroutine alloc_gauss_points (num_gauss, gauss)
subroutine alloc_gauss_colatitude (gauss)
subroutine set_points_4_integration (xst, xed, gauss, g_int)
subroutine set_points_4_elevation (gauss, g_int)
subroutine cal_gauss_integrals (gauss, g_int, x)
Calicurate gauss integrations.
Function/Subroutine Documentation
alloc_gauss_colatitude()
subroutine t_gauss_points::alloc_gauss_colatitude (type(gauss_points), intent(inout) gauss)
Definition at line 207 of file t_gauss_points.f90.
Referenced by gauss_points_io::read_alloc_gauss_points(), and set_gauss_colatitude().
alloc_gauss_points()
subroutine t_gauss_points::alloc_gauss_points (integer(kind = kint), intent(in) num_gauss, type(gauss_points), intent(inout) gauss)
Definition at line 190 of file t_gauss_points.f90.
Referenced by construct_gauss_coefs(), and gauss_points_io::read_alloc_gauss_points().
alloc_work_4_integration()
subroutine t_gauss_points::alloc_work_4_integration (integer(kind = kint), intent(in) num_inte, integer(kind = kint), intent(in) n_point, type(gauss_integrations), intent(inout) g_int)
Definition at line 124 of file t_gauss_points.f90.
cal_gauss_integrals()
subroutine t_gauss_points::cal_gauss_integrals (type(gauss_points), intent(in) gauss, type(gauss_integrations), intent(in) g_int, real(kind = kreal), dimension(g_int%num_inte), intent(inout) x)
Calicurate gauss integrations.
Definition at line 260 of file t_gauss_points.f90.
References gauss_integration::cal_gauss_integration().
const_gauss_colatitude()
subroutine t_gauss_points::const_gauss_colatitude (integer(kind = kint), intent(in) num_gauss, type(gauss_points), intent(inout) gauss)
Definition at line 80 of file t_gauss_points.f90.
References construct_gauss_coefs(), and set_gauss_colatitude().
Referenced by const_fem_mesh_sph_mhd::base_fem_mesh_sph_mhd(), schmidt_poly_on_meridian::cal_full_legendre_on_med(), schmidt_poly_on_rtm_grid::set_gauss_points_rtm(), and test_gauss_points().
construct_gauss_coefs()
subroutine t_gauss_points::construct_gauss_coefs (integer(kind = kint), intent(in) num_gauss, type(gauss_points), intent(inout) gauss)
Definition at line 93 of file t_gauss_points.f90.
References alloc_gauss_points(), and gauss_integration::const_gauss_points_coefs().
Referenced by const_gauss_colatitude().
dealloc_gauss_colatitude()
subroutine t_gauss_points::dealloc_gauss_colatitude (type(gauss_points), intent(inout) gauss)
Definition at line 142 of file t_gauss_points.f90.
References dealloc_gauss_colats(), and dealloc_gauss_points().
Referenced by const_fem_mesh_sph_mhd::base_fem_mesh_sph_mhd(), schmidt_poly_on_meridian::cal_full_legendre_on_med(), compare_gauss_points(), schmidt_poly_on_rtm_grid::set_gauss_points_rtm(), and test_gauss_points().
dealloc_gauss_colats()
subroutine, private t_gauss_points::dealloc_gauss_colats (type(gauss_points), intent(inout) gauss) private
Definition at line 165 of file t_gauss_points.f90.
Referenced by dealloc_gauss_colatitude().
dealloc_gauss_points()
subroutine t_gauss_points::dealloc_gauss_points (type(gauss_points), intent(inout) gauss)
Definition at line 154 of file t_gauss_points.f90.
Referenced by dealloc_gauss_colatitude().
dealloc_work_4_integration()
subroutine t_gauss_points::dealloc_work_4_integration (type(gauss_integrations), intent(inout) g_int)
Definition at line 179 of file t_gauss_points.f90.
set_gauss_colatitude()
subroutine, private t_gauss_points::set_gauss_colatitude (type(gauss_points), intent(inout) gauss) private
Definition at line 109 of file t_gauss_points.f90.
References alloc_gauss_colatitude(), and gauss_integration::set_gauss_points_sph().
Referenced by const_gauss_colatitude().
set_points_4_elevation()
subroutine t_gauss_points::set_points_4_elevation (type(gauss_points), intent(in) gauss, type(gauss_integrations), intent(inout) g_int)
Definition at line 244 of file t_gauss_points.f90.
References gauss_integration::set_gauss_colat_integration().
set_points_4_integration()
subroutine t_gauss_points::set_points_4_integration (real(kind = kreal), intent(in) xst, real(kind = kreal), intent(in) xed, type(gauss_points), intent(in) gauss, type(gauss_integrations), intent(inout) g_int)
Definition at line 227 of file t_gauss_points.f90.
References gauss_integration::set_gauss_points_integration().