CALYPSO: gz_mpi_domain_data_io_b Module Reference
gz_mpi_domain_data_io_b Module Reference
Routine for gzipped binary doimain data IO.
Functions/Subroutines
subroutine gz_mpi_read_domain_info_b (IO_param, comm_IO)
subroutine gz_mpi_read_import_data_b (IO_param, comm_IO)
subroutine gz_mpi_read_export_data_b (IO_param, comm_IO)
subroutine gz_mpi_write_domain_info_b (IO_param, comm_IO)
subroutine gz_mpi_write_import_data_b (IO_param, comm_IO)
subroutine gz_mpi_write_export_data_b (IO_param, comm_IO)
Detailed Description
Routine for gzipped binary doimain data IO.
      subroutine gz_mpi_read_domain_info_b(IO_param, comm_IO)
      subroutine gz_mpi_read_import_data_b(IO_param, comm_IO)
      subroutine gz_mpi_read_export_data_b(IO_param, comm_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(communication_table), intent(inout) :: comm_IO
      subroutine gz_mpi_write_domain_info_b(IO_param, comm_IO)
      subroutine gz_mpi_write_import_data_b(IO_param, comm_IO)
      subroutine gz_mpi_write_export_data_b(IO_param, comm_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(communication_table), intent(in) :: comm_IO
Function/Subroutine Documentation
gz_mpi_read_domain_info_b()
subroutine gz_mpi_domain_data_io_b::gz_mpi_read_domain_info_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(inout) comm_IO)
Definition at line 41 of file gz_MPI_domain_data_IO_b.f90.
References t_comm_table::alloc_neighbouring_id(), gz_mpi_binary_data_io::gz_mpi_read_int_vector_b(), gz_mpi_binary_datum_io::gz_mpi_read_one_integer_b(), and gz_mpi_binary_datum_io::gz_mpi_read_process_id_b().
Referenced by gz_mpi_edge_data_io_b::gz_mpi_read_edge_connect_b(), gz_mpi_element_data_io_b::gz_mpi_read_ele_comm_table_b(), gz_mpi_sph_modes_data_io_b::gz_mpi_read_geom_rtm_data_b(), gz_mpi_sph_modes_data_io_b::gz_mpi_read_geom_rtp_data_b(), gz_mpi_sph_modes_data_io_b::gz_mpi_read_modes_rlm_data_b(), gz_mpi_mesh_data_io_b::gz_mpi_read_num_node_b(), gz_mpi_sph_modes_data_io_b::gz_mpi_read_spectr_rj_data_b(), and gz_mpi_surface_data_io_b::gz_mpi_read_surf_connect_b().
gz_mpi_read_export_data_b()
subroutine gz_mpi_domain_data_io_b::gz_mpi_read_export_data_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(inout) comm_IO)
Definition at line 86 of file gz_MPI_domain_data_IO_b.f90.
References t_comm_table::alloc_export_item(), t_comm_table::alloc_export_num(), gz_mpi_binary_data_io::gz_mpi_read_int_vector_b(), and gz_mpi_binary_data_io::gz_mpi_read_integer_stack_b().
Referenced by gz_mpi_edge_data_io_b::gz_mpi_read_edge_connect_b(), gz_mpi_element_data_io_b::gz_mpi_read_ele_comm_table_b(), gz_mpi_mesh_data_io_b::gz_mpi_read_geometry_data_b(), and gz_mpi_surface_data_io_b::gz_mpi_read_surf_connect_b().
gz_mpi_read_import_data_b()
subroutine gz_mpi_domain_data_io_b::gz_mpi_read_import_data_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(inout) comm_IO)
Definition at line 64 of file gz_MPI_domain_data_IO_b.f90.
References t_comm_table::alloc_import_item(), t_comm_table::alloc_import_num(), gz_mpi_binary_data_io::gz_mpi_read_int_vector_b(), and gz_mpi_binary_data_io::gz_mpi_read_integer_stack_b().
Referenced by gz_mpi_edge_data_io_b::gz_mpi_read_edge_connect_b(), gz_mpi_element_data_io_b::gz_mpi_read_ele_comm_table_b(), gz_mpi_sph_modes_data_io_b::gz_mpi_read_geom_rtm_data_b(), gz_mpi_sph_modes_data_io_b::gz_mpi_read_geom_rtp_data_b(), gz_mpi_mesh_data_io_b::gz_mpi_read_geometry_data_b(), gz_mpi_sph_modes_data_io_b::gz_mpi_read_modes_rlm_data_b(), gz_mpi_sph_modes_data_io_b::gz_mpi_read_spectr_rj_data_b(), and gz_mpi_surface_data_io_b::gz_mpi_read_surf_connect_b().
gz_mpi_write_domain_info_b()
subroutine gz_mpi_domain_data_io_b::gz_mpi_write_domain_info_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(in) comm_IO)
Definition at line 109 of file gz_MPI_domain_data_IO_b.f90.
References gz_mpi_binary_data_io::gz_mpi_write_int_vector_b(), gz_mpi_binary_datum_io::gz_mpi_write_one_integer_b(), and gz_mpi_binary_datum_io::gz_mpi_write_process_id_b().
Referenced by gz_mpi_edge_data_io_b::gz_mpi_write_edge_connect_b(), gz_mpi_element_data_io_b::gz_mpi_write_ele_comm_table_b(), gz_mpi_sph_modes_data_io_b::gz_mpi_write_geom_rtm_data_b(), gz_mpi_sph_modes_data_io_b::gz_mpi_write_geom_rtp_data_b(), gz_mpi_mesh_data_io_b::gz_mpi_write_geometry_data_b(), gz_mpi_sph_modes_data_io_b::gz_mpi_write_modes_rlm_data_b(), gz_mpi_sph_modes_data_io_b::gz_mpi_write_spectr_rj_data_b(), and gz_mpi_surface_data_io_b::gz_mpi_write_surf_connect_b().
gz_mpi_write_export_data_b()
subroutine gz_mpi_domain_data_io_b::gz_mpi_write_export_data_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(in) comm_IO)
Definition at line 149 of file gz_MPI_domain_data_IO_b.f90.
References gz_mpi_binary_data_io::gz_mpi_write_int_vector_b(), and gz_mpi_binary_data_io::gz_mpi_write_integer_stack_b().
Referenced by gz_mpi_edge_data_io_b::gz_mpi_write_edge_connect_b(), gz_mpi_element_data_io_b::gz_mpi_write_ele_comm_table_b(), gz_mpi_mesh_data_io_b::gz_mpi_write_geometry_data_b(), and gz_mpi_surface_data_io_b::gz_mpi_write_surf_connect_b().
gz_mpi_write_import_data_b()
subroutine gz_mpi_domain_data_io_b::gz_mpi_write_import_data_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(in) comm_IO)
Definition at line 129 of file gz_MPI_domain_data_IO_b.f90.
References gz_mpi_binary_data_io::gz_mpi_write_int_vector_b(), and gz_mpi_binary_data_io::gz_mpi_write_integer_stack_b().
Referenced by gz_mpi_edge_data_io_b::gz_mpi_write_edge_connect_b(), gz_mpi_element_data_io_b::gz_mpi_write_ele_comm_table_b(), gz_mpi_sph_modes_data_io_b::gz_mpi_write_geom_rtm_data_b(), gz_mpi_sph_modes_data_io_b::gz_mpi_write_geom_rtp_data_b(), gz_mpi_mesh_data_io_b::gz_mpi_write_geometry_data_b(), gz_mpi_sph_modes_data_io_b::gz_mpi_write_modes_rlm_data_b(), gz_mpi_sph_modes_data_io_b::gz_mpi_write_spectr_rj_data_b(), and gz_mpi_surface_data_io_b::gz_mpi_write_surf_connect_b().