CALYPSO: set_params_sph_trans Module Reference
set_params_sph_trans Module Reference
Initialize spherical harmonics transform.
Functions/Subroutines
subroutine const_conatitude_rtp (sph_rtm, sph_rtp, leg)
subroutine const_sin_theta_rtp (leg, sph_rtm, sph_rtp)
subroutine set_mdx_rlm_rtm (l_truncation, nidx_rtm, nidx_rlm, idx_gl_1d_rtm_m, idx_gl_1d_rlm_j, mdx_p_rlm_rtm, mdx_n_rlm_rtm, maxdegree_rlm, lstack_rlm)
subroutine find_conjugate_sph_order (nidx_rtm, idx_gl_1d_mphi, mn_rlm)
subroutine set_sin_theta_rtm (nth_rtm, g_colat_rtm, asin_theta_1d_rtm)
subroutine, private set_colatitude_rtp (nth_rtp, nth_rtm, g_colat_rtm, idx_gl_1d_rtp_t, g_colat_rtp)
subroutine, private set_sin_theta_rtp (nth_rtp, nth_rtm, g_colat_rtm, idx_gl_1d_rtp_t, cos_theta_1d_rtp, sin_theta_1d_rtp, cot_theta_1d_rtp)
subroutine radial_4_sph_trans (sph_rtp, sph_rtm, sph_rlm, sph_rj)
Detailed Description
Initialize spherical harmonics transform.
      subroutine const_conatitude_rtp(sph_rtm, sph_rtp, leg)
        type(sph_rtm_grid), intent(in) :: sph_rtm
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(legendre_4_sph_trans), intent(inout) :: leg
      subroutine const_sin_theta_rtp(leg, sph_rtm, sph_rtp)
        type(legendre_4_sph_trans), intent(in) :: leg
        type(sph_rtm_grid), intent(in) ::    sph_rtm
        type(sph_rtp_grid), intent(inout) :: sph_rtp
      subroutine set_mdx_rlm_rtm(l_truncation, nidx_rtm, nidx_rlm,    &
     &          idx_gl_1d_rtm_m, idx_gl_1d_rlm_j,                     &
     &          mdx_p_rlm_rtm, mdx_n_rlm_rtm, maxdegree_rlm,          &
     &          lstack_rlm)
      subroutine find_conjugate_sph_order                             &
     &         (nidx_rtm, idx_gl_1d_mphi, mn_rlm)
      subroutine set_sin_theta_rtm                                    &
     &         (nth_rtm, g_colat_rtm, asin_theta_1d_rtm)
      subroutine radial_4_sph_trans(sph_rtp, sph_rtm, sph_rlm, sph_rj)
        type(sph_rtp_grid), intent(inout) :: sph_rtp
        type(sph_rtm_grid), intent(inout) :: sph_rtm
        type(sph_rlm_grid), intent(inout) :: sph_rlm
        type(sph_rj_grid), intent(inout) :: sph_rj
Function/Subroutine Documentation
const_conatitude_rtp()
subroutine set_params_sph_trans::const_conatitude_rtp (type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rtp_grid), intent(in) sph_rtp, type(legendre_4_sph_trans), intent(inout) leg)
Definition at line 48 of file set_params_sph_trans.f90.
References t_schmidt_poly_on_rtm::alloc_gauss_colatitude_rtp(), and set_colatitude_rtp().
Referenced by init_sph_trans::initialize_legendre_trans().
const_sin_theta_rtp()
subroutine set_params_sph_trans::const_sin_theta_rtp (type(legendre_4_sph_trans), intent(in) leg, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rtp_grid), intent(inout) sph_rtp)
Definition at line 68 of file set_params_sph_trans.f90.
References t_spheric_rtp_data::alloc_theta_4_rtp(), and set_sin_theta_rtp().
Referenced by init_sph_trans::initialize_legendre_trans().
find_conjugate_sph_order()
subroutine set_params_sph_trans::find_conjugate_sph_order (integer(kind = kint), dimension(3), intent(in) nidx_rtm, integer(kind = kint), dimension(nidx_rtm(3)), intent(in) idx_gl_1d_mphi, integer(kind = kint), dimension(nidx_rtm(3)), intent(inout) mn_rlm)
Definition at line 139 of file set_params_sph_trans.f90.
Referenced by init_sph_trans::initialize_legendre_trans().
radial_4_sph_trans()
subroutine set_params_sph_trans::radial_4_sph_trans (type(sph_rtp_grid), intent(inout) sph_rtp, type(sph_rtm_grid), intent(inout) sph_rtm, type(sph_rlm_grid), intent(inout) sph_rlm, type(sph_rj_grid), intent(inout) sph_rj)
Definition at line 248 of file set_params_sph_trans.f90.
References m_constants::one.
Referenced by init_sph_trans::initialize_legendre_trans().
set_colatitude_rtp()
subroutine, private set_params_sph_trans::set_colatitude_rtp (integer(kind = kint), intent(in) nth_rtp, integer(kind = kint), intent(in) nth_rtm, real(kind= kreal), dimension(nth_rtm), intent(in) g_colat_rtm, integer(kind = kint), dimension(nth_rtp), intent(in) idx_gl_1d_rtp_t, real(kind= kreal), dimension(nth_rtp), intent(inout) g_colat_rtp) private
Definition at line 194 of file set_params_sph_trans.f90.
Referenced by const_conatitude_rtp().
set_mdx_rlm_rtm()
subroutine set_params_sph_trans::set_mdx_rlm_rtm (integer(kind = kint), intent(in) l_truncation, integer(kind = kint), dimension(3), intent(in) nidx_rtm, integer(kind = kint), dimension(2), intent(in) nidx_rlm, integer(kind = kint), dimension(nidx_rtm(3),2), intent(in) idx_gl_1d_rtm_m, integer(kind = kint), dimension(nidx_rlm(2),3), intent(in) idx_gl_1d_rlm_j, integer(kind = kint), dimension(nidx_rlm(2)), intent(inout) mdx_p_rlm_rtm, integer(kind = kint), dimension(nidx_rlm(2)), intent(inout) mdx_n_rlm_rtm, integer(kind = kint), intent(inout) maxdegree_rlm, integer(kind = kint), dimension(0:nidx_rtm(3)), intent(inout) lstack_rlm)
Definition at line 90 of file set_params_sph_trans.f90.
Referenced by init_sph_trans::initialize_legendre_trans().
set_sin_theta_rtm()
subroutine set_params_sph_trans::set_sin_theta_rtm (integer(kind = kint), intent(in) nth_rtm, real(kind= kreal), dimension(nth_rtm), intent(in) g_colat_rtm, real(kind= kreal), dimension(nth_rtm), intent(inout) asin_theta_1d_rtm)
Definition at line 174 of file set_params_sph_trans.f90.
References m_constants::one.
Referenced by init_sph_trans::init_legendre_rtm().
set_sin_theta_rtp()
subroutine, private set_params_sph_trans::set_sin_theta_rtp (integer(kind = kint), intent(in) nth_rtp, integer(kind = kint), intent(in) nth_rtm, real(kind= kreal), dimension(nth_rtm), intent(in) g_colat_rtm, integer(kind = kint), dimension(nth_rtp), intent(in) idx_gl_1d_rtp_t, real(kind= kreal), dimension(nth_rtp), intent(inout) cos_theta_1d_rtp, real(kind= kreal), dimension(nth_rtp), intent(inout) sin_theta_1d_rtp, real(kind= kreal), dimension(nth_rtp), intent(inout) cot_theta_1d_rtp) private
Definition at line 218 of file set_params_sph_trans.f90.
Referenced by const_sin_theta_rtp().