CALYPSO: const_edge_data Module Reference
const_edge_data Module Reference
Construct edge connectivity by element connectivity.
Functions/Subroutines
subroutine construct_edge_data (nod, ele, surf, edge)
subroutine empty_edge_connect_type (ele, surf, edge)
subroutine const_edge_hash_4_ele (ele, edge_ele_tbl)
subroutine const_part_edge_hash_4_ele (ele, numele_part, iele_part, edge_ele_tbl)
Variables
type(sum_hash_tbl), save, private edge_ele_tbl
Detailed Description
Construct edge connectivity by element connectivity.
      subroutine construct_edge_data(nod, ele, surf, edge)
      subroutine empty_edge_connect_type(ele, surf, edge)
        type(node_data),    intent(in) :: nod
        type(element_data), intent(in) :: ele
        type(surface_data), intent(in) :: surf
        type(edge_data),    intent(inout) :: edge
Function/Subroutine Documentation
const_edge_hash_4_ele()
subroutine const_edge_data::const_edge_hash_4_ele (type(element_data), intent(in) ele, type(sum_hash_tbl), intent(inout) edge_ele_tbl)
Definition at line 114 of file const_edge_data.f90.
References set_edge_hash_by_ele::count_edge_hash_4_ele(), set_edge_hash_by_ele::mark_all_edges_by_ele(), and set_edge_hash_by_ele::set_edge_hash_4_ele().
Referenced by construct_edge_data().
const_part_edge_hash_4_ele()
subroutine const_edge_data::const_part_edge_hash_4_ele (type(element_data), intent(in) ele, integer(kind = kint), intent(in) numele_part, integer(kind = kint), dimension(numele_part), intent(in) iele_part, type(sum_hash_tbl), intent(inout) edge_ele_tbl)
Definition at line 142 of file const_edge_data.f90.
References set_edge_hash_by_ele::count_part_edge_hash_4_ele(), edge_ele_tbl, set_edge_hash_by_ele::mark_all_edges_by_ele(), and set_edge_hash_by_ele::set_part_edge_hash_4_ele().
construct_edge_data()
subroutine const_edge_data::construct_edge_data (type(node_data), intent(in) nod, type(element_data), intent(in) ele, type(surface_data), intent(in) surf, type(edge_data), intent(inout) edge)
Definition at line 39 of file const_edge_data.f90.
References t_edge_data::alloc_edge_4_ele(), t_edge_data::alloc_edge_connect(), t_sum_hash::alloc_sum_hash(), const_edge_hash_4_ele(), set_edge_data_by_ele::count_num_edges_by_ele(), t_sum_hash::dealloc_sum_hash(), edge_ele_tbl, m_machine_parameter::iflag_debug, m_geometry_constants::nedge_4_ele, set_edge_data_by_ele::set_edges_connect_4_sf(), and set_edge_data_by_ele::set_edges_connect_by_ele().
Referenced by set_surf_edge_mesh::set_edge_connectivity().
empty_edge_connect_type()
subroutine const_edge_data::empty_edge_connect_type (type(element_data), intent(in) ele, type(surface_data), intent(in) surf, type(edge_data), intent(inout) edge)
Definition at line 92 of file const_edge_data.f90.
References t_edge_data::alloc_edge_4_ele(), t_edge_data::alloc_edge_connect(), t_edge_data::alloc_edge_param_smp(), and m_machine_parameter::iflag_debug.
Referenced by set_surf_edge_mesh::empty_surface_and_edge().
Variable Documentation
edge_ele_tbl
type(sum_hash_tbl), save, private const_edge_data::edge_ele_tbl private
Definition at line 31 of file const_edge_data.f90.
Referenced by const_part_edge_hash_4_ele(), and construct_edge_data().