CALYPSO: m_intersection_data_13 Module Reference
m_intersection_data_13 Module Reference
Variables
integer(kind=kint), parameter, private nnod_tri = 3
integer(kind=kint), parameter nkind_etype_13 = 2
integer(kind=kint), parameter num_tri_13 = 4
integer(kind=kint), parameter num_patch_13 = 4
integer(kind=kint), dimension(3), parameter itri_2_patch_13 = (/1, 2, 3/)
integer(kind=kint), dimension(nkind_etype_13), parameter iflag_psf_etype_13 = (/165, 90/)
integer(kind=kint), dimension(nnod_tri, num_tri_13, nkind_etype_13), parameter iedge_tri_13 = reshape((/ 3, 12, 4, 1, 10, 2, 9, 8, 5, 6, 7, 11, 1, 4, 9, 5, 6, 10, 3, 2, 11, 12, 7, 8/), shape=(/nnod_tri,num_tri_13,nkind_etype_13/))
integer(kind=kint), dimension(nnod_tri, num_patch_13, nkind_etype_13), parameter iedge_4_patch_13 = reshape((/ 3, 12, 4, 1, 10, 2, 9, 8, 5, 6, 7, 11, 1, 4, 9, 5, 6, 10, 3, 2, 11, 12, 7, 8/), shape=(/nnod_tri,num_patch_13,nkind_etype_13/))
Variable Documentation
iedge_4_patch_13
integer(kind = kint), dimension(nnod_tri,num_patch_13,nkind_etype_13), parameter m_intersection_data_13::iedge_4_patch_13 = reshape((/ 3, 12, 4, 1, 10, 2, 9, 8, 5, 6, 7, 11, 1, 4, 9, 5, 6, 10, 3, 2, 11, 12, 7, 8/), shape=(/nnod_tri,num_patch_13,nkind_etype_13/))
Definition at line 43 of file m_intersection_data_13.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
iedge_tri_13
integer(kind = kint), dimension(nnod_tri,num_tri_13,nkind_etype_13), parameter m_intersection_data_13::iedge_tri_13 = reshape((/ 3, 12, 4, 1, 10, 2, 9, 8, 5, 6, 7, 11, 1, 4, 9, 5, 6, 10, 3, 2, 11, 12, 7, 8/), shape=(/nnod_tri,num_tri_13,nkind_etype_13/))
Definition at line 36 of file m_intersection_data_13.f90.
iflag_psf_etype_13
integer(kind = kint), dimension(nkind_etype_13), parameter m_intersection_data_13::iflag_psf_etype_13 = (/165, 90/)
Definition at line 33 of file m_intersection_data_13.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
itri_2_patch_13
integer(kind = kint), dimension(3), parameter m_intersection_data_13::itri_2_patch_13 = (/1, 2, 3/)
Definition at line 30 of file m_intersection_data_13.f90.
nkind_etype_13
integer(kind = kint), parameter m_intersection_data_13::nkind_etype_13 = 2
Definition at line 27 of file m_intersection_data_13.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
nnod_tri
integer(kind = kint), parameter, private m_intersection_data_13::nnod_tri = 3 private
Definition at line 25 of file m_intersection_data_13.f90.
num_patch_13
integer(kind = kint), parameter m_intersection_data_13::num_patch_13 = 4
Definition at line 29 of file m_intersection_data_13.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
num_tri_13
integer(kind = kint), parameter m_intersection_data_13::num_tri_13 = 4
Definition at line 28 of file m_intersection_data_13.f90.