CALYPSO: mpi_spherical_model_io Module Reference
mpi_spherical_model_io Module Reference
Data IO routines for spectrum data.
Functions/Subroutines
subroutine mpi_read_rank_4_sph (IO_param, sph_IO)
subroutine mpi_read_gl_reso_sph (IO_param, sph_IO)
subroutine mpi_read_gl_nodes_sph (IO_param, sph_IO)
subroutine mpi_write_rank_4_sph (IO_param, sph_IO)
subroutine mpi_write_gl_reso_sph (IO_param, sph_IO)
subroutine mpi_write_gl_nodes_sph (IO_param, sph_IO)
Detailed Description
Data IO routines for spectrum data.
      subroutine mpi_read_rank_4_sph(IO_param, sph_IO)
      subroutine mpi_read_gl_reso_sph(IO_param, sph_IO)
      subroutine mpi_read_gl_nodes_sph(IO_param, sph_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(sph_IO_data), intent(inout) :: sph_IO
      subroutine mpi_write_rank_4_sph(IO_param, sph_IO)
      subroutine mpi_write_gl_reso_sph(IO_param, sph_IO)
      subroutine mpi_write_gl_nodes_sph(IO_param, sph_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(sph_IO_data), intent(in) :: sph_IO
Function/Subroutine Documentation
mpi_read_gl_nodes_sph()
subroutine mpi_spherical_model_io::mpi_read_gl_nodes_sph (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(inout) sph_IO)
Definition at line 80 of file MPI_spherical_model_IO.f90.
References t_node_id_spherical_io::alloc_nod_id_sph_io(), mpi_integer_list_io::mpi_read_ele_connect(), and mpi_ascii_data_io::mpi_read_num_of_data().
Referenced by mpi_sph_modes_data_io::mpi_read_geom_rtm_data(), mpi_sph_modes_data_io::mpi_read_geom_rtp_data(), mpi_sph_modes_data_io::mpi_read_modes_rlm_data(), and mpi_sph_modes_data_io::mpi_read_spectr_rj_data().
mpi_read_gl_reso_sph()
subroutine mpi_spherical_model_io::mpi_read_gl_reso_sph (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(inout) sph_IO)
Definition at line 60 of file MPI_spherical_model_IO.f90.
References m_sph_modes_grid_labels::hd_trunc(), data_io_to_textline::len_int_txt, mpi_ascii_data_io::mpi_read_charahead(), mpi_domain_data_io::mpi_read_comm_table(), mpi_ascii_data_io::mpi_read_num_of_data(), mpi_ascii_data_io::mpi_skip_read(), and data_io_to_textline::read_integer_textline().
Referenced by mpi_sph_modes_data_io::mpi_read_geom_rtm_data(), mpi_sph_modes_data_io::mpi_read_geom_rtp_data(), mpi_sph_modes_data_io::mpi_read_modes_rlm_data(), and mpi_sph_modes_data_io::mpi_read_spectr_rj_data().
mpi_read_rank_4_sph()
subroutine mpi_spherical_model_io::mpi_read_rank_4_sph (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(inout) sph_IO)
Definition at line 43 of file MPI_spherical_model_IO.f90.
References m_sph_modes_grid_labels::hd_segment(), mpi_domain_data_io::mpi_read_comm_table(), mpi_ascii_data_io::mpi_read_num_of_data(), and mpi_ascii_data_io::mpi_skip_read().
Referenced by mpi_sph_modes_data_io::mpi_read_geom_rtm_data(), mpi_sph_modes_data_io::mpi_read_geom_rtp_data(), mpi_sph_modes_data_io::mpi_read_modes_rlm_data(), and mpi_sph_modes_data_io::mpi_read_spectr_rj_data().
mpi_write_gl_nodes_sph()
subroutine mpi_spherical_model_io::mpi_write_gl_nodes_sph (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(in) sph_IO)
Definition at line 130 of file MPI_spherical_model_IO.f90.
References mpi_integer_list_io::mpi_write_ele_connect(), and mpi_ascii_data_io::mpi_write_num_of_data().
Referenced by mpi_sph_modes_data_io::mpi_write_geom_rtm_data(), mpi_sph_modes_data_io::mpi_write_geom_rtp_data(), mpi_sph_modes_data_io::mpi_write_modes_rlm_data(), and mpi_sph_modes_data_io::mpi_write_spectr_rj_data().
mpi_write_gl_reso_sph()
subroutine mpi_spherical_model_io::mpi_write_gl_reso_sph (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(in) sph_IO)
Definition at line 113 of file MPI_spherical_model_IO.f90.
References m_sph_modes_grid_labels::hd_trunc(), data_io_to_textline::integer_textline(), data_io_to_textline::len_int_txt, mpi_ascii_data_io::mpi_write_charahead(), and mpi_domain_data_io::mpi_write_comm_table().
Referenced by mpi_sph_modes_data_io::mpi_write_geom_rtm_data(), mpi_sph_modes_data_io::mpi_write_geom_rtp_data(), mpi_sph_modes_data_io::mpi_write_modes_rlm_data(), and mpi_sph_modes_data_io::mpi_write_spectr_rj_data().
mpi_write_rank_4_sph()
subroutine mpi_spherical_model_io::mpi_write_rank_4_sph (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(in) sph_IO)
Definition at line 98 of file MPI_spherical_model_IO.f90.
References m_sph_modes_grid_labels::hd_segment(), mpi_ascii_data_io::mpi_write_charahead(), and mpi_domain_data_io::mpi_write_comm_table().
Referenced by mpi_sph_modes_data_io::mpi_write_geom_rtm_data(), mpi_sph_modes_data_io::mpi_write_geom_rtp_data(), mpi_sph_modes_data_io::mpi_write_modes_rlm_data(), and mpi_sph_modes_data_io::mpi_write_spectr_rj_data().