CALYPSO: t_control_array_int2real Module Reference
t_control_array_int2real Module Reference
Data Types
type ctl_array_i2r
Structure for 1 real and 2 integers control array.
type read_int2_real_item
structure of control item with three characters
Functions/Subroutines
subroutine read_int2real_ctl_type (c_buf, label, i2r_item)
subroutine write_int2real_ctl_type (id_file, level, label, i2r_item)
subroutine copy_int2real_ctl (org_i2r, new_i2r)
subroutine alloc_control_array_i2_r (array_i2r)
subroutine dealloc_control_array_i2_r (array_i2r)
subroutine read_control_array_i2_r (id_control, label, array_i2r, c_buf)
subroutine write_control_array_i2_r (id_control, level, label, array_i2r)
subroutine append_control_array_i2_r (read_i2r, array_i2r)
subroutine copy_control_array_i2_r (num_copy, org_i2r, tgt_i2r)
subroutine append_control_item_i2_r (read_i2r, array_i2r)
Function/Subroutine Documentation
alloc_control_array_i2_r()
subroutine t_control_array_int2real::alloc_control_array_i2_r (type(ctl_array_i2r), intent(inout) array_i2r)
Definition at line 139 of file t_control_array_int2real.f90.
Referenced by append_control_array_i2_r(), bcast_control_arrays::bcast_ctl_array_i2r(), and read_control_array_i2_r().
append_control_array_i2_r()
subroutine t_control_array_int2real::append_control_array_i2_r (type(read_int2_real_item), intent(inout) read_i2r, type(ctl_array_i2r), intent(inout) array_i2r)
Definition at line 234 of file t_control_array_int2real.f90.
References alloc_control_array_i2_r(), append_control_item_i2_r(), copy_control_array_i2_r(), and dealloc_control_array_i2_r().
Referenced by read_control_array_i2_r().
append_control_item_i2_r()
subroutine t_control_array_int2real::append_control_item_i2_r (type(read_int2_real_item), intent(in) read_i2r, type(ctl_array_i2r), intent(inout) array_i2r)
Definition at line 276 of file t_control_array_int2real.f90.
Referenced by append_control_array_i2_r().
copy_control_array_i2_r()
subroutine t_control_array_int2real::copy_control_array_i2_r (integer(kind = kint), intent(in) num_copy, type(ctl_array_i2r), intent(in) org_i2r, type(ctl_array_i2r), intent(inout) tgt_i2r)
Definition at line 259 of file t_control_array_int2real.f90.
Referenced by append_control_array_i2_r().
copy_int2real_ctl()
subroutine t_control_array_int2real::copy_int2real_ctl (type(read_int2_real_item), intent(in) org_i2r, type(read_int2_real_item), intent(inout) new_i2r)
Definition at line 124 of file t_control_array_int2real.f90.
dealloc_control_array_i2_r()
subroutine t_control_array_int2real::dealloc_control_array_i2_r (type(ctl_array_i2r), intent(inout) array_i2r)
Definition at line 157 of file t_control_array_int2real.f90.
Referenced by append_control_array_i2_r().
read_control_array_i2_r()
subroutine t_control_array_int2real::read_control_array_i2_r (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) label, type(ctl_array_i2r), intent(inout) array_i2r, type(buffer_for_control), intent(inout) c_buf)
Definition at line 171 of file t_control_array_int2real.f90.
References alloc_control_array_i2_r(), append_control_array_i2_r(), t_read_control_elements::check_array_flag(), t_read_control_elements::check_end_array_flag(), t_read_control_elements::load_one_line_from_control(), and read_int2real_ctl_type().
read_int2real_ctl_type()
subroutine t_control_array_int2real::read_int2real_ctl_type (type(buffer_for_control), intent(in) c_buf, character(len=kchara), intent(in) label, type(read_int2_real_item), intent(inout) i2r_item)
Definition at line 79 of file t_control_array_int2real.f90.
References m_machine_parameter::iflag_debug.
Referenced by read_control_array_i2_r().
write_control_array_i2_r()
subroutine t_control_array_int2real::write_control_array_i2_r (integer(kind = kint), intent(in) id_control, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, type(ctl_array_i2r), intent(in) array_i2r)
Definition at line 205 of file t_control_array_int2real.f90.
References write_control_elements::write_array_flag_for_ctl(), write_control_elements::write_end_array_flag_for_ctl(), and write_control_elements::write_i2_r_ctl_item().
write_int2real_ctl_type()
subroutine t_control_array_int2real::write_int2real_ctl_type (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, type(read_int2_real_item), intent(in) i2r_item)
Definition at line 104 of file t_control_array_int2real.f90.
References write_control_elements::write_i2_r_ctl_item().