CALYPSO: data_io_to_textline Module Reference
data_io_to_textline Module Reference
Data IO to one line text buffer.
Functions/Subroutines
integer function len_one_word_textline (word)
integer function len_byte_stack_textline (num_pe)
integer function len_multi_int_textline (num)
integer function len_multi_6digit_line (num)
integer function len_vector_textline (num)
integer function len_int8_and_mul_int_textline (num)
integer function len_int8_and_mul_int8_textline (num)
integer function len_int8_and_vector_textline (num)
character(len=len_trim(word)+1) function one_word_textline (word)
character(len=16) function integer_nolfline (int_dat)
character(len=16+1) function integer_textline (int_dat)
character(len=num *16+1) function int_stack_textline (num, istack)
character(len=num *16+1) function multi_int_textline (num, int_dat)
character(len=num_pe *16+1) function byte_stack_textline (num_pe, istack)
character(len=num *16+1) function int_stack8_textline (num, istack)
character(len=num *16+1) function multi_int8_textline (num, int8_dat)
character(len=num *6+1) function mul_6digit_int_line (num, int_dat)
character(len=num *25+1) function vector_textline (num, real_dat)
character(len=num *16+17) function int8_and_mul_int_textline (int8_gl, num, int_dat)
character(len=num *16+17) function int8_and_mul_int8_textline (int8_gl, num, int8_dat)
character(len=num *25+17) function int8_and_vector_textline (int8_gl, num, real_dat)
subroutine read_one_word_textline (textbuf, field_name, len_txt)
subroutine read_integer_nolfline (textbuf, int_dat)
subroutine read_integer_textline (textbuf, int_dat)
subroutine read_int_stack_textline (textbuf, num, istack, ntot)
subroutine read_multi_int_textline (textbuf, num, int_dat)
subroutine read_byte_stack_textline (textbuf, num_pe, istack)
subroutine read_int8_stack_textline (textbuf, num, istack)
subroutine read_multi_int8_textline (textbuf, num, int8_dat)
subroutine read_mul_6digit_int_line (textbuf, num, int_dat)
subroutine read_vector_textline (textbuf, num, real_dat)
subroutine read_int8_and_mul_int_textline (textbuf, int8_gl, num, int_dat)
subroutine read_int8_and_mul_int8_textline (textbuf, int8_gl, num, int8_dat)
subroutine read_int8_and_vector_textline (textbuf, int8_gl, num, real_dat)
Variables
integer, parameter len_real_nolf = 25
integer, parameter len_real_text = len_real_nolf + 1
integer, parameter len_integer_nolf = 16
integer, parameter len_int_txt = len_integer_nolf + 1
integer, parameter len_6digit_nolf = 6
integer, parameter len_6digit_txt = len_6digit_nolf + 1
Detailed Description
Data IO to one line text buffer.
      integer function len_one_word_textline(word)
      integer function len_byte_stack_textline(num_pe)
      integer function len_multi_int_textline(num)
      integer function len_multi_6digit_line(num)
      integer function len_vector_textline(num)
      integer function len_int8_and_mul_int_textline(num)
      integer function len_int8_and_mul_int8_textline(num)
      integer function len_int8_and_vector_textline(num)
      character(len=len_trim(word)+1) function one_word_textline(word)
      function integer_nolfline(int_dat)
        character(len=16) :: integer_nolfline
      function integer_textline(int_dat)
        character(len=16+1) :: integer_textline
      function int_stack_textline(num, istack)
        character(len=num*16+1) :: int_stack_textline
      function multi_int_textline(num, int_dat)
        character(len=num*16+1) :: multi_int_textline
      function byte_stack_textline(num_pe, istack)
        character(len=num*16+1) :: byte_stack_textline
      function int_stack8_textline(num, istack)
        character(len=num*16+1) :: int_stack8_textline
      function multi_int8_textline(num, int8_dat)
        character(len=num*16+1) :: multi_int8_textline
      function mul_6digit_int_line(num, int_dat)
        character(len=num*6+1) :: mul_6digit_int_line
      function vector_textline(num, real_dat)
        character(len=num*25+1) :: vector_textline
      function int8_and_mul_int_textline(int8_gl, num, int_dat)
        character(len=num*16+17) :: int8_and_mul_int_textline
      function int8_and_mul_int8_textline(int8_gl, num, int8_dat)
        character(len=num*16+17) :: int8_and_mul_int8_textline
      function int8_and_vector_textline(int8_gl, num, real_dat)
        character(len=num*25+17) :: int8_and_vector_textline
      subroutine read_one_word_textline(textbuf, field_name, len_txt)
      subroutine read_integer_nolfline(textbuf, int_dat)
      subroutine read_integer_textline(textbuf, int_dat)
      subroutine read_int_stack_textline(textbuf, num, istack, ntot)
      subroutine read_multi_int_textline(textbuf, num, int_dat)
      subroutine read_byte_stack_textline(textbuf, num_pe, istack)
      subroutine read_int8_stack_textline(textbuf, num, istack)
      subroutine read_multi_int8_textline(textbuf, num, int8_dat)
      subroutine read_mul_6digit_int_line(textbuf, num, int_dat)
      subroutine read_vector_textline(textbuf, num, real_dat)
      subroutine read_int8_and_mul_int_textline                       &
     &         (textbuf, int8_gl, num, int_dat)
      subroutine read_int8_and_mul_int8_textline                      &
     &         (textbuf, int8_gl, num, int8_dat)
      subroutine read_int8_and_vector_textline                        &
     &         (textbuf, int8_gl, num, real_dat)
Function/Subroutine Documentation
byte_stack_textline()
character(len=num_pe*16+1) function data_io_to_textline::byte_stack_textline (integer, intent(in) num_pe, integer(kind = kint_gl), dimension(0:num_pe), intent(in) istack)
Definition at line 246 of file data_IO_to_textline.f90.
References multi_int8_textline().
Referenced by gz_mpi_ascii_data_io::gz_mpi_write_num_of_data(), gz_mpi_ascii_data_io::gz_mpi_write_stack_over_domain(), mpi_domain_data_io::mpi_write_int_vector(), mpi_ascii_data_io::mpi_write_num_of_data(), and mpi_ascii_data_io::mpi_write_stack_over_domain().
int8_and_mul_int8_textline()
character(len=num*16+17) function data_io_to_textline::int8_and_mul_int8_textline (integer(kind = kint_gl), intent(in) int8_gl, integer(kind = kint), intent(in) num, integer(kind = kint_gl), dimension(num), intent(in) int8_dat)
Definition at line 358 of file data_IO_to_textline.f90.
Referenced by zlib_cvt_ascii_ele_connect::defleate_ele_connect().
int8_and_mul_int_textline()
character(len=num*16+17) function data_io_to_textline::int8_and_mul_int_textline (integer(kind = kint_gl), intent(in) int8_gl, integer(kind = kint), intent(in) num, integer(kind = kint), dimension(num), intent(in) int_dat)
Definition at line 335 of file data_IO_to_textline.f90.
Referenced by mpi_integer_list_io::mpi_write_ele_connect().
int8_and_vector_textline()
character(len=num*25+17) function data_io_to_textline::int8_and_vector_textline (integer(kind = kint_gl), intent(in) int8_gl, integer(kind = kint), intent(in) num, real(kind = kreal), dimension(num), intent(in) real_dat)
Definition at line 381 of file data_IO_to_textline.f90.
Referenced by zlib_convert_ascii_vector::defleate_node_position().
int_stack8_textline()
character(len=num*16+1) function data_io_to_textline::int_stack8_textline (integer(kind = kint), intent(in) num, integer(kind = kint_gl), dimension(0:num), intent(in) istack)
Definition at line 262 of file data_IO_to_textline.f90.
References multi_int8_textline().
int_stack_textline()
character(len=num*16+1) function data_io_to_textline::int_stack_textline (integer(kind = kint), intent(in) num, integer(kind = kint), dimension(0:num), intent(in) istack)
Definition at line 211 of file data_IO_to_textline.f90.
References multi_int_textline().
integer_nolfline()
character(len=16) function data_io_to_textline::integer_nolfline (integer(kind = kint), intent(in) int_dat)
Definition at line 181 of file data_IO_to_textline.f90.
References m_constants::ione, and multi_int_textline().
integer_textline()
character(len=16+1) function data_io_to_textline::integer_textline (integer(kind = kint), intent(in) int_dat)
Definition at line 196 of file data_IO_to_textline.f90.
References m_constants::ione, and multi_int_textline().
Referenced by gz_mpi_domain_data_io::gz_mpi_write_domain_info(), gz_mpi_spherical_model_io::gz_mpi_write_gl_reso_sph(), mpi_domain_data_io::mpi_write_domain_info(), and mpi_spherical_model_io::mpi_write_gl_reso_sph().
len_byte_stack_textline()
integer function data_io_to_textline::len_byte_stack_textline (integer, intent(in) num_pe)
Definition at line 95 of file data_IO_to_textline.f90.
Referenced by gz_mpi_domain_data_io::gz_mpi_read_comm_table(), gz_mpi_integer_list_io::gz_mpi_read_ele_connect(), gz_mpi_integer_list_io::gz_mpi_read_element_type(), gz_mpi_integer_list_io::gz_mpi_read_int_list(), gz_mpi_domain_data_io::gz_mpi_read_int_vector(), gz_mpi_ascii_data_io::gz_mpi_read_num_of_data(), gz_mpi_ascii_data_io::gz_mpi_write_num_of_data(), gz_mpi_ascii_data_io::gz_mpi_write_stack_over_domain(), mpi_domain_data_io::mpi_read_comm_table(), mpi_domain_data_io::mpi_read_int_vector(), mpi_ascii_data_io::mpi_read_num_of_data(), mpi_domain_data_io::mpi_write_int_vector(), mpi_ascii_data_io::mpi_write_num_of_data(), and mpi_ascii_data_io::mpi_write_stack_over_domain().
len_int8_and_mul_int8_textline()
integer function data_io_to_textline::len_int8_and_mul_int8_textline (integer(kind = kint), intent(in) num)
Definition at line 148 of file data_IO_to_textline.f90.
Referenced by zlib_cvt_ascii_ele_connect::defleate_ele_connect(), and zlib_cvt_ascii_ele_connect::infleate_ele_connect().
len_int8_and_mul_int_textline()
integer function data_io_to_textline::len_int8_and_mul_int_textline (integer(kind = kint), intent(in) num)
Definition at line 138 of file data_IO_to_textline.f90.
Referenced by mpi_integer_list_io::mpi_read_ele_connect(), and mpi_integer_list_io::mpi_write_ele_connect().
len_int8_and_vector_textline()
integer function data_io_to_textline::len_int8_and_vector_textline (integer(kind = kint), intent(in) num)
Definition at line 158 of file data_IO_to_textline.f90.
Referenced by zlib_convert_ascii_vector::defleate_node_position(), and zlib_convert_ascii_vector::infleate_node_position().
len_multi_6digit_line()
integer function data_io_to_textline::len_multi_6digit_line (integer(kind = kint), intent(in) num)
Definition at line 117 of file data_IO_to_textline.f90.
Referenced by zlib_cvt_ascii_comm_tbl::defleate_element_type(), zlib_cvt_ascii_comm_tbl::infleate_element_type(), mpi_integer_list_io::mpi_read_element_type(), and mpi_integer_list_io::mpi_write_element_type().
len_multi_int_textline()
integer function data_io_to_textline::len_multi_int_textline (integer(kind = kint), intent(in) num)
Definition at line 106 of file data_IO_to_textline.f90.
Referenced by zlib_cvt_ascii_ele_connect::defleate_1d_global_address(), zlib_cvt_ascii_comm_tbl::defleate_comm_table(), zlib_cvt_ascii_ele_connect::defleate_ele_int_list(), gz_mpi_domain_data_io::gz_mpi_read_int_vector(), gz_mpi_domain_data_io::gz_mpi_write_int_vector(), zlib_cvt_ascii_ele_connect::infleate_1d_global_address(), zlib_cvt_ascii_comm_tbl::infleate_comm_table(), zlib_cvt_ascii_ele_connect::infleate_ele_int_list(), mpi_domain_data_io::mpi_read_comm_table(), mpi_integer_list_io::mpi_read_ele_connect(), mpi_integer_list_io::mpi_read_element_type(), mpi_integer_list_io::mpi_read_int_list(), mpi_domain_data_io::mpi_read_int_vector(), mpi_domain_data_io::mpi_write_comm_table(), mpi_integer_list_io::mpi_write_int_list(), and mpi_domain_data_io::mpi_write_int_vector().
len_one_word_textline()
integer function data_io_to_textline::len_one_word_textline (character(len=kchara), intent(in) word)
Definition at line 84 of file data_IO_to_textline.f90.
len_vector_textline()
integer function data_io_to_textline::len_vector_textline (integer(kind = kint), intent(in) num)
Definition at line 128 of file data_IO_to_textline.f90.
Referenced by zlib_convert_ascii_vector::defleate_vector_txt(), zlib_convert_ascii_vector::infleate_vector_txt(), and field_block_mpi_io::write_fld_vecotr_mpi().
mul_6digit_int_line()
character(len=num*6+1) function data_io_to_textline::mul_6digit_int_line (integer(kind = kint), intent(in) num, integer(kind = kint), dimension(num), intent(in) int_dat)
Definition at line 297 of file data_IO_to_textline.f90.
Referenced by zlib_cvt_ascii_comm_tbl::defleate_element_type(), and mpi_integer_list_io::mpi_write_element_type().
multi_int8_textline()
character(len=num*16+1) function data_io_to_textline::multi_int8_textline (integer(kind = kint), intent(in) num, integer(kind = kint_gl), dimension(num), intent(in) int8_dat)
Definition at line 276 of file data_IO_to_textline.f90.
Referenced by byte_stack_textline(), and int_stack8_textline().
multi_int_textline()
character(len=num*16+1) function data_io_to_textline::multi_int_textline (integer(kind = kint), intent(in) num, integer(kind = kint), dimension(num), intent(in) int_dat)
Definition at line 225 of file data_IO_to_textline.f90.
Referenced by zlib_cvt_ascii_ele_connect::defleate_1d_global_address(), zlib_cvt_ascii_comm_tbl::defleate_comm_table(), zlib_cvt_ascii_ele_connect::defleate_ele_int_list(), gz_mpi_domain_data_io::gz_mpi_write_int_vector(), int_stack_textline(), integer_nolfline(), integer_textline(), mpi_domain_data_io::mpi_write_comm_table(), mpi_integer_list_io::mpi_write_int_list(), and mpi_domain_data_io::mpi_write_int_vector().
one_word_textline()
character(len=len_trim(word)+1) function data_io_to_textline::one_word_textline (character(len=kchara), intent(in) word)
Definition at line 169 of file data_IO_to_textline.f90.
read_byte_stack_textline()
subroutine data_io_to_textline::read_byte_stack_textline (character(len=num_pe*16+1), intent(in) textbuf, integer, intent(in) num_pe, integer(kind = kint_gl), dimension(0:num_pe), intent(inout) istack)
Definition at line 483 of file data_IO_to_textline.f90.
References read_multi_int8_textline().
Referenced by gz_mpi_domain_data_io::gz_mpi_read_comm_table(), gz_mpi_integer_list_io::gz_mpi_read_ele_connect(), gz_mpi_integer_list_io::gz_mpi_read_element_type(), gz_mpi_integer_list_io::gz_mpi_read_int_list(), gz_mpi_domain_data_io::gz_mpi_read_int_vector(), gz_mpi_ascii_data_io::gz_mpi_read_num_of_data(), and mpi_ascii_data_io::mpi_read_num_of_data().
read_int8_and_mul_int8_textline()
subroutine data_io_to_textline::read_int8_and_mul_int8_textline (character(len=num*16+17), intent(in) textbuf, integer(kind = kint_gl), intent(inout) int8_gl, integer(kind = kint), intent(in) num, integer(kind = kint_gl), dimension(num), intent(inout) int8_dat)
Definition at line 582 of file data_IO_to_textline.f90.
Referenced by zlib_cvt_ascii_ele_connect::infleate_ele_connect().
read_int8_and_mul_int_textline()
subroutine data_io_to_textline::read_int8_and_mul_int_textline (character(len=num*16+17), intent(in) textbuf, integer(kind = kint_gl), intent(inout) int8_gl, integer(kind = kint), intent(in) num, integer(kind = kint), dimension(num), intent(inout) int_dat)
Definition at line 561 of file data_IO_to_textline.f90.
Referenced by mpi_integer_list_io::mpi_read_ele_connect().
read_int8_and_vector_textline()
subroutine data_io_to_textline::read_int8_and_vector_textline (character(len=num*25+17), intent(in) textbuf, integer(kind = kint_gl), intent(inout) int8_gl, integer(kind = kint), intent(in) num, real(kind = kreal), dimension(num), intent(inout) real_dat)
Definition at line 603 of file data_IO_to_textline.f90.
Referenced by zlib_convert_ascii_vector::infleate_node_position().
read_int8_stack_textline()
subroutine data_io_to_textline::read_int8_stack_textline (character(len=num*16+1), intent(in) textbuf, integer(kind = kint), intent(in) num, integer(kind = kint_gl), dimension(0:num), intent(inout) istack)
Definition at line 500 of file data_IO_to_textline.f90.
References read_multi_int8_textline().
read_int_stack_textline()
subroutine data_io_to_textline::read_int_stack_textline (character(len=num*16+1), intent(in) textbuf, integer(kind = kint), intent(in) num, integer(kind = kint), dimension(0:num), intent(inout) istack, integer(kind = kint), intent(inout) ntot)
Definition at line 451 of file data_IO_to_textline.f90.
References read_multi_int_textline().
read_integer_nolfline()
subroutine data_io_to_textline::read_integer_nolfline (character(len=16), intent(in) textbuf, integer(kind = kint), intent(inout) int_dat)
Definition at line 425 of file data_IO_to_textline.f90.
read_integer_textline()
subroutine data_io_to_textline::read_integer_textline (character(len=16+1), intent(in) textbuf, integer(kind = kint), intent(inout) int_dat)
Definition at line 437 of file data_IO_to_textline.f90.
References m_constants::ione, and read_multi_int_textline().
Referenced by gz_mpi_domain_data_io::gz_mpi_check_num_of_domains(), gz_mpi_spherical_model_io::gz_mpi_read_gl_reso_sph(), mpi_domain_data_io::mpi_check_num_of_domains(), and mpi_spherical_model_io::mpi_read_gl_reso_sph().
read_mul_6digit_int_line()
subroutine data_io_to_textline::read_mul_6digit_int_line (character(len=num*6+1), intent(in) textbuf, integer(kind = kint), intent(in) num, integer(kind = kint), dimension(num), intent(inout) int_dat)
Definition at line 529 of file data_IO_to_textline.f90.
Referenced by zlib_cvt_ascii_comm_tbl::infleate_element_type(), and mpi_integer_list_io::mpi_read_element_type().
read_multi_int8_textline()
subroutine data_io_to_textline::read_multi_int8_textline (character(len=num*16+1), intent(in) textbuf, integer(kind = kint), intent(in) num, integer(kind = kint_gl), dimension(num), intent(inout) int8_dat)
Definition at line 513 of file data_IO_to_textline.f90.
Referenced by read_byte_stack_textline(), and read_int8_stack_textline().
read_multi_int_textline()
subroutine data_io_to_textline::read_multi_int_textline (character(len=num*16+1), intent(in) textbuf, integer(kind = kint), intent(in) num, integer(kind = kint), dimension(num), intent(inout) int_dat)
Definition at line 467 of file data_IO_to_textline.f90.
Referenced by gz_mpi_domain_data_io::gz_mpi_read_int_vector(), zlib_cvt_ascii_ele_connect::infleate_1d_global_address(), zlib_cvt_ascii_comm_tbl::infleate_comm_table(), zlib_cvt_ascii_ele_connect::infleate_ele_int_list(), mpi_domain_data_io::mpi_read_comm_table(), mpi_integer_list_io::mpi_read_int_list(), mpi_domain_data_io::mpi_read_int_vector(), read_int_stack_textline(), and read_integer_textline().
read_one_word_textline()
subroutine data_io_to_textline::read_one_word_textline (character(len=kchara), intent(in) textbuf, character(len=kchara), intent(inout) field_name, integer(kind = kint), intent(inout) len_txt)
Definition at line 405 of file data_IO_to_textline.f90.
References m_precision::kchara.
read_vector_textline()
subroutine data_io_to_textline::read_vector_textline (character(len=num*25+1), intent(in) textbuf, integer(kind = kint), intent(in) num, real(kind = kreal), dimension(num), intent(inout) real_dat)
Definition at line 545 of file data_IO_to_textline.f90.
Referenced by zlib_convert_ascii_vector::infleate_vector_txt(), and field_block_mpi_io::read_fld_vecotr_mpi().
vector_textline()
character(len=num*25+1) function data_io_to_textline::vector_textline (integer(kind = kint), intent(in) num, real(kind = kreal), dimension(num), intent(in) real_dat)
Definition at line 318 of file data_IO_to_textline.f90.
Referenced by zlib_convert_ascii_vector::defleate_vector_txt(), and field_block_mpi_io::write_fld_vecotr_mpi().
Variable Documentation
len_6digit_nolf
integer, parameter data_io_to_textline::len_6digit_nolf = 6
Definition at line 75 of file data_IO_to_textline.f90.
len_6digit_txt
integer, parameter data_io_to_textline::len_6digit_txt = len_6digit_nolf + 1
Definition at line 76 of file data_IO_to_textline.f90.
Referenced by zlib_cvt_ascii_comm_tbl::defleate_element_type().
len_int_txt
integer, parameter data_io_to_textline::len_int_txt = len_integer_nolf + 1
Definition at line 74 of file data_IO_to_textline.f90.
Referenced by zlib_cvt_ascii_comm_tbl::defleate_comm_table(), gz_mpi_domain_data_io::gz_mpi_check_num_of_domains(), gz_mpi_spherical_model_io::gz_mpi_read_gl_reso_sph(), gz_mpi_domain_data_io::gz_mpi_write_domain_info(), gz_mpi_spherical_model_io::gz_mpi_write_gl_reso_sph(), mpi_domain_data_io::mpi_check_num_of_domains(), mpi_spherical_model_io::mpi_read_gl_reso_sph(), mpi_domain_data_io::mpi_write_domain_info(), and mpi_spherical_model_io::mpi_write_gl_reso_sph().
len_integer_nolf
integer, parameter data_io_to_textline::len_integer_nolf = 16
Definition at line 73 of file data_IO_to_textline.f90.
len_real_nolf
integer, parameter data_io_to_textline::len_real_nolf = 25
Definition at line 71 of file data_IO_to_textline.f90.
len_real_text
integer, parameter data_io_to_textline::len_real_text = len_real_nolf + 1
Definition at line 72 of file data_IO_to_textline.f90.