CALYPSO: udt_file_io Module Reference
udt_file_io Module Reference
UCD format data IO.
Functions/Subroutines
subroutine write_ucd_file (id_rank, file_name, ucd)
subroutine write_udt_file (id_rank, file_name, ucd)
subroutine write_grd_file (id_rank, file_name, ucd)
subroutine read_udt_file (id_rank, file_name, ucd)
subroutine read_ucd_file (id_rank, file_name, ucd)
subroutine read_grd_file (id_rank, file_name, ucd)
subroutine read_alloc_udt_params (id_rank, file_name, ucd)
subroutine read_alloc_udt_file (id_rank, file_name, ucd)
subroutine read_alloc_ucd_file (id_rank, file_name, ucd)
subroutine read_alloc_grd_file (id_rank, file_name, ucd)
Variables
integer(kind=kint), parameter, private id_ucd_file = 16
file ID for UCD file
Detailed Description
UCD format data IO.
      subroutine write_ucd_file(id_rank, file_name, ucd)
      subroutine write_udt_file(id_rank, file_name, ucd)
      subroutine write_grd_file(id_rank, file_name, ucd)
        type(ucd_data), intent(in) :: ucd
      subroutine read_udt_file(id_rank, file_name, ucd)
      subroutine read_ucd_file(id_rank, file_name, ucd)
      subroutine read_grd_file(id_rank, file_name, nnod_ele, ucd)
        type(ucd_data), intent(inout) :: ucd
      subroutine read_alloc_udt_params(id_rank, file_name, ucd)
      subroutine read_alloc_udt_file(id_rank, file_name, ucd)
      subroutine read_alloc_ucd_file(id_rank, file_name, ucd)
      subroutine read_alloc_grd_file(id_rank, file_name, ucd)
        type(ucd_data), intent(inout) :: ucd
Parameters
id_rank process ID
file_name file name
ucd Structure for FEM field data IO
Function/Subroutine Documentation
read_alloc_grd_file()
subroutine udt_file_io::read_alloc_grd_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(ucd_data), intent(inout) ucd)
Definition at line 242 of file udt_file_IO.f90.
References m_machine_parameter::i_debug, id_ucd_file, and udt_type_data_io::read_alloc_ucd_mesh_data().
Referenced by ucd_io_select::sel_read_alloc_ucd_file().
read_alloc_ucd_file()
subroutine udt_file_io::read_alloc_ucd_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(ucd_data), intent(inout) ucd)
Definition at line 217 of file udt_file_IO.f90.
References m_machine_parameter::i_debug, id_ucd_file, udt_type_data_io::read_alloc_ucd_mesh_data(), udt_type_data_io::read_alloc_udt_field(), and udt_data_io::read_ucd_field_data().
Referenced by ucd_io_select::sel_read_alloc_ucd_file().
read_alloc_udt_file()
subroutine udt_file_io::read_alloc_udt_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(ucd_data), intent(inout) ucd)
Definition at line 193 of file udt_file_IO.f90.
References m_machine_parameter::i_debug, id_ucd_file, udt_type_data_io::read_alloc_udt_field(), and udt_data_io::read_ucd_field_data().
Referenced by ucd_io_select::sel_read_alloc_ucd_file(), and ucd_io_select::sel_read_alloc_udt_file().
read_alloc_udt_params()
subroutine udt_file_io::read_alloc_udt_params (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(ucd_data), intent(inout) ucd)
Definition at line 173 of file udt_file_IO.f90.
References m_machine_parameter::i_debug, id_ucd_file, and udt_type_data_io::read_alloc_udt_field().
Referenced by ucd_io_select::sel_read_udt_param().
read_grd_file()
subroutine udt_file_io::read_grd_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(ucd_data), intent(inout) ucd)
Definition at line 151 of file udt_file_IO.f90.
References m_machine_parameter::i_debug, id_ucd_file, and udt_type_data_io::read_ucd_mesh_data().
Referenced by ucd_io_select::sel_read_ucd_file().
read_ucd_file()
subroutine udt_file_io::read_ucd_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(ucd_data), intent(inout) ucd)
Definition at line 131 of file udt_file_IO.f90.
References m_machine_parameter::i_debug, id_ucd_file, udt_type_data_io::read_ucd_mesh_data(), and udt_type_data_io::read_udt_field().
Referenced by ucd_io_select::sel_read_ucd_file().
read_udt_file()
subroutine udt_file_io::read_udt_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(ucd_data), intent(inout) ucd)
Definition at line 112 of file udt_file_IO.f90.
References m_machine_parameter::i_debug, id_ucd_file, and udt_type_data_io::read_udt_field().
Referenced by ucd_io_select::sel_read_ucd_file(), and ucd_io_select::sel_read_udt_file().
write_grd_file()
subroutine udt_file_io::write_grd_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(ucd_data), intent(in) ucd)
Definition at line 91 of file udt_file_IO.f90.
References m_machine_parameter::i_debug, id_ucd_file, and udt_type_data_io::write_ucd_type_mesh().
Referenced by ucd_io_select::sel_write_grd_file().
write_ucd_file()
subroutine udt_file_io::write_ucd_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(ucd_data), intent(in) ucd)
Definition at line 50 of file udt_file_IO.f90.
References m_machine_parameter::i_debug, id_ucd_file, udt_type_data_io::write_ucd_type_mesh(), and udt_type_data_io::write_udt_type_fields().
Referenced by ucd_io_select::sel_write_ucd_file(), and ucd_io_select::sel_write_udt_file().
write_udt_file()
subroutine udt_file_io::write_udt_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(ucd_data), intent(in) ucd)
Definition at line 71 of file udt_file_IO.f90.
References m_machine_parameter::i_debug, id_ucd_file, and udt_type_data_io::write_udt_type_fields().
Referenced by ucd_io_select::sel_write_ucd_file(), and ucd_io_select::sel_write_udt_file().
Variable Documentation
id_ucd_file
integer(kind = kint), parameter, private udt_file_io::id_ucd_file = 16 private
file ID for UCD file
Definition at line 42 of file udt_file_IO.f90.
Referenced by read_alloc_grd_file(), read_alloc_ucd_file(), read_alloc_udt_file(), read_alloc_udt_params(), read_grd_file(), read_ucd_file(), read_udt_file(), write_grd_file(), write_ucd_file(), and write_udt_file().