CALYPSO: m_fem_mesh_labels Module Reference
m_fem_mesh_labels Module Reference
Comments for mesh data.
Functions/Subroutines
character(len=ilen_fem_para) function hd_fem_para ()
character(len=ilen_fem_node) function hd_fem_node ()
character(len=ilen_fem_elem) function hd_fem_elem ()
character(len=ilen_fem_import) function hd_fem_import ()
character(len=ilen_fem_export) function hd_fem_export ()
character(len=ilen_fem_nodgrp) function hd_fem_nodgrp ()
character(len=ilen_fem_elegrp) function hd_fem_elegrp ()
character(len=ilen_fem_sfgrp) function hd_fem_sfgrp ()
character(len=ilen_fem_para_sph) function hd_fem_para_sph ()
character(len=ilen_fem_node_sph) function hd_fem_node_sph ()
character(len=ilen_fem_para_cyl) function hd_fem_para_cyl ()
character(len=ilen_fem_node_cyl) function hd_fem_node_cyl ()
Variables
integer(kind=kint), parameter ilen_fem_para = 1+24+1+3
length of hd_fem_para
integer(kind=kint), parameter ilen_fem_node = 1+54+1+22+1+5
length of hd_fem_node
integer(kind=kint), parameter ilen_fem_elem = 1+27+1+3
length of hd_fem_elem
integer(kind=kint), parameter ilen_fem_import = 1+32+13+1+4
length of hd_fem_import
integer(kind=kint), parameter ilen_fem_export = 1+13+1+3
length of hd_fem_export
integer(kind=kint), parameter ilen_fem_nodgrp = 1+24+17+1+4
length of hd_fem_nodgrp
integer(kind=kint), parameter ilen_fem_elegrp = 1+20+1+3
length of hd_fem_elegrp
integer(kind=kint), parameter ilen_fem_sfgrp = 1+20+1+3
length of hd_fem_sfgrp
integer(kind=kint), parameter ilen_fem_para_sph = 1+17+26+1+4
length of hd_fem_nod_sph
integer(kind=kint), parameter ilen_fem_node_sph = 1+54+1+27+1+5
length of hd_fem_node
integer(kind=kint), parameter ilen_fem_para_cyl = 1+17+28+1+4
length of hd_fem_nod_sph
integer(kind=kint), parameter ilen_fem_node_cyl = 1+54+1+23+1+5
length of hd_fem_node
Detailed Description
Comments for mesh data.
      character(len=ilen_fem_para) function hd_fem_para()
      character(len=ilen_fem_node) function hd_fem_node()
      character(len=ilen_fem_elem) function hd_fem_elem()
      character(len=ilen_fem_import) function hd_fem_import()
      character(len=ilen_fem_export) function hd_fem_export()
      character(len=ilen_fem_nodgrp) function hd_fem_nodgrp()
      character(len=ilen_fem_elegrp) function hd_fem_elegrp()
      character(len=ilen_fem_sfgrp) function hd_fem_sfgrp()
      character(len=ilen_fem_para_sph) function hd_fem_para_sph()
      character(len=ilen_fem_node_sph) function hd_fem_node_sph()
      character(len=ilen_fem_para_cyl) function hd_fem_para_cyl()
      character(len=ilen_fem_node_cyl) function hd_fem_node_cyl()
Function/Subroutine Documentation
hd_fem_elegrp()
character(len=ilen_fem_elegrp) function m_fem_mesh_labels::hd_fem_elegrp
Definition at line 145 of file m_fem_mesh_labels.f90.
Referenced by gz_mpi_mesh_data_io::gz_mpi_read_mesh_groups(), gz_mpi_mesh_data_io::gz_mpi_write_mesh_groups(), gz_mesh_data_io::gz_write_mesh_groups(), gz_mpi_viewer_mesh_file_io::gz_write_viewer_mesh_infos(), mpi_mesh_data_io::mpi_read_mesh_groups(), mpi_mesh_data_io::mpi_write_mesh_groups(), viewer_group_data_io::write_ele_group_viewer(), mesh_data_io::write_mesh_groups(), and mpi_viewer_mesh_file_io::write_viewer_mesh_infos().
hd_fem_elem()
character(len=ilen_fem_elem) function m_fem_mesh_labels::hd_fem_elem
Definition at line 96 of file m_fem_mesh_labels.f90.
Referenced by gz_mpi_mesh_data_io::gz_mpi_read_num_node_ele(), gz_mpi_mesh_data_io::gz_mpi_write_geometry_data(), gz_mesh_data_io::gz_write_geometry_data(), mpi_mesh_data_io::mpi_read_num_node_ele(), mpi_mesh_data_io::mpi_write_geometry_data(), and mesh_data_io::write_geometry_data().
hd_fem_export()
character(len=ilen_fem_export) function m_fem_mesh_labels::hd_fem_export
Definition at line 120 of file m_fem_mesh_labels.f90.
Referenced by gz_mpi_mesh_data_io::gz_mpi_read_geometry_data(), gz_mpi_mesh_data_io::gz_mpi_write_geometry_data(), gz_mesh_data_io::gz_write_filter_geometry(), gz_mesh_data_io::gz_write_geometry_data(), mpi_mesh_data_io::mpi_read_geometry_data(), mpi_mesh_data_io::mpi_write_geometry_data(), mesh_data_io::write_filter_geometry(), and mesh_data_io::write_geometry_data().
hd_fem_import()
character(len=ilen_fem_import) function m_fem_mesh_labels::hd_fem_import
Definition at line 108 of file m_fem_mesh_labels.f90.
Referenced by gz_mpi_mesh_data_io::gz_mpi_read_geometry_data(), gz_mpi_mesh_data_io::gz_mpi_write_geometry_data(), gz_mesh_data_io::gz_write_filter_geometry(), gz_mesh_data_io::gz_write_geometry_data(), mpi_mesh_data_io::mpi_read_geometry_data(), mpi_mesh_data_io::mpi_write_geometry_data(), mesh_data_io::write_filter_geometry(), and mesh_data_io::write_geometry_data().
hd_fem_node()
character(len=ilen_fem_node) function m_fem_mesh_labels::hd_fem_node
Definition at line 82 of file m_fem_mesh_labels.f90.
Referenced by gz_mpi_mesh_data_io::gz_mpi_read_num_node(), gz_mpi_mesh_data_io::gz_mpi_write_geometry_data(), gz_mesh_data_io::gz_write_filter_geometry(), gz_mesh_data_io::gz_write_geometry_data(), mpi_mesh_data_io::mpi_read_num_node(), mpi_mesh_data_io::mpi_write_geometry_data(), mesh_data_io::write_filter_geometry(), and mesh_data_io::write_geometry_data().
hd_fem_node_cyl()
character(len=ilen_fem_node_cyl) function m_fem_mesh_labels::hd_fem_node_cyl
Definition at line 209 of file m_fem_mesh_labels.f90.
Referenced by mesh_data_io::output_node_cyl_geometry().
hd_fem_node_sph()
character(len=ilen_fem_node_sph) function m_fem_mesh_labels::hd_fem_node_sph
Definition at line 182 of file m_fem_mesh_labels.f90.
Referenced by mesh_data_io::output_node_sph_geometry().
hd_fem_nodgrp()
character(len=ilen_fem_nodgrp) function m_fem_mesh_labels::hd_fem_nodgrp
Definition at line 132 of file m_fem_mesh_labels.f90.
Referenced by gz_mpi_mesh_data_io::gz_mpi_read_mesh_groups(), gz_mpi_mesh_data_io::gz_mpi_write_mesh_groups(), gz_mesh_data_io::gz_write_mesh_groups(), gz_mpi_viewer_mesh_file_io::gz_write_viewer_mesh_infos(), mpi_mesh_data_io::mpi_read_mesh_groups(), mpi_mesh_data_io::mpi_write_mesh_groups(), mesh_data_io::write_mesh_groups(), viewer_group_data_io::write_nod_group_viewer(), and mpi_viewer_mesh_file_io::write_viewer_mesh_infos().
hd_fem_para()
character(len=ilen_fem_para) function m_fem_mesh_labels::hd_fem_para
Definition at line 71 of file m_fem_mesh_labels.f90.
Referenced by gz_mpi_edge_data_io::gz_mpi_read_edge_connect(), gz_mpi_element_data_io::gz_mpi_read_ele_comm_table(), gz_mpi_mesh_data_io::gz_mpi_read_num_node(), gz_mpi_surface_data_io::gz_mpi_read_surf_connect(), gz_mpi_edge_data_io::gz_mpi_write_edge_connect(), gz_mpi_element_data_io::gz_mpi_write_ele_comm_table(), gz_mpi_mesh_data_io::gz_mpi_write_geometry_data(), gz_mpi_surface_data_io::gz_mpi_write_surf_connect(), gz_edge_data_io::gz_write_edge_connection(), gz_element_data_io::gz_write_element_comm_table(), gz_mesh_data_io::gz_write_filter_geometry(), gz_mesh_data_io::gz_write_geometry_data(), gz_surface_data_io::gz_write_surface_connection(), mpi_edge_data_io::mpi_read_edge_connection(), mpi_element_data_io::mpi_read_element_comm_table(), mpi_mesh_data_io::mpi_read_num_node(), mpi_surface_data_io::mpi_read_surface_connection(), mpi_edge_data_io::mpi_write_edge_connection(), mpi_element_data_io::mpi_write_element_comm_table(), mpi_mesh_data_io::mpi_write_geometry_data(), mpi_surface_data_io::mpi_write_surface_connection(), mesh_data_io::output_node_cyl_geometry(), mesh_data_io::output_node_sph_geometry(), edge_data_io::write_edge_connection(), element_data_io::write_element_comm_table(), mesh_data_io::write_filter_geometry(), mesh_data_io::write_geometry_data(), and surface_data_io::write_surface_connection().
hd_fem_para_cyl()
character(len=ilen_fem_para_cyl) function m_fem_mesh_labels::hd_fem_para_cyl
Definition at line 197 of file m_fem_mesh_labels.f90.
Referenced by mesh_data_io::output_node_cyl_geometry().
hd_fem_para_sph()
character(len=ilen_fem_para_sph) function m_fem_mesh_labels::hd_fem_para_sph
Definition at line 170 of file m_fem_mesh_labels.f90.
Referenced by mesh_data_io::output_node_sph_geometry().
hd_fem_sfgrp()
character(len=ilen_fem_sfgrp) function m_fem_mesh_labels::hd_fem_sfgrp
Definition at line 157 of file m_fem_mesh_labels.f90.
Referenced by gz_mpi_mesh_data_io::gz_mpi_read_mesh_groups(), gz_mpi_mesh_data_io::gz_mpi_write_mesh_groups(), gz_mesh_data_io::gz_write_mesh_groups(), gz_mpi_viewer_mesh_file_io::gz_write_viewer_mesh_infos(), mpi_mesh_data_io::mpi_read_mesh_groups(), mpi_mesh_data_io::mpi_write_mesh_groups(), mesh_data_io::write_mesh_groups(), viewer_group_data_io::write_surf_group_viewer(), and mpi_viewer_mesh_file_io::write_viewer_mesh_infos().
Variable Documentation
ilen_fem_elegrp
integer(kind = kint), parameter m_fem_mesh_labels::ilen_fem_elegrp = 1+20+1+3
length of hd_fem_elegrp
Definition at line 47 of file m_fem_mesh_labels.f90.
ilen_fem_elem
integer(kind = kint), parameter m_fem_mesh_labels::ilen_fem_elem = 1+27+1+3
length of hd_fem_elem
Definition at line 37 of file m_fem_mesh_labels.f90.
ilen_fem_export
integer(kind = kint), parameter m_fem_mesh_labels::ilen_fem_export = 1+13+1+3
length of hd_fem_export
Definition at line 42 of file m_fem_mesh_labels.f90.
ilen_fem_import
integer(kind = kint), parameter m_fem_mesh_labels::ilen_fem_import = 1+32+13+1+4
length of hd_fem_import
Definition at line 40 of file m_fem_mesh_labels.f90.
ilen_fem_node
integer(kind = kint), parameter m_fem_mesh_labels::ilen_fem_node = 1+54+1+22+1+5
length of hd_fem_node
Definition at line 35 of file m_fem_mesh_labels.f90.
ilen_fem_node_cyl
integer(kind = kint), parameter m_fem_mesh_labels::ilen_fem_node_cyl = 1+54+1+23+1+5
length of hd_fem_node
Definition at line 62 of file m_fem_mesh_labels.f90.
ilen_fem_node_sph
integer(kind = kint), parameter m_fem_mesh_labels::ilen_fem_node_sph = 1+54+1+27+1+5
length of hd_fem_node
Definition at line 55 of file m_fem_mesh_labels.f90.
ilen_fem_nodgrp
integer(kind = kint), parameter m_fem_mesh_labels::ilen_fem_nodgrp = 1+24+17+1+4
length of hd_fem_nodgrp
Definition at line 45 of file m_fem_mesh_labels.f90.
ilen_fem_para
integer(kind = kint), parameter m_fem_mesh_labels::ilen_fem_para = 1+24+1+3
length of hd_fem_para
Definition at line 33 of file m_fem_mesh_labels.f90.
ilen_fem_para_cyl
integer(kind = kint), parameter m_fem_mesh_labels::ilen_fem_para_cyl = 1+17+28+1+4
length of hd_fem_nod_sph
Definition at line 59 of file m_fem_mesh_labels.f90.
ilen_fem_para_sph
integer(kind = kint), parameter m_fem_mesh_labels::ilen_fem_para_sph = 1+17+26+1+4
length of hd_fem_nod_sph
Definition at line 52 of file m_fem_mesh_labels.f90.
ilen_fem_sfgrp
integer(kind = kint), parameter m_fem_mesh_labels::ilen_fem_sfgrp = 1+20+1+3
length of hd_fem_sfgrp
Definition at line 49 of file m_fem_mesh_labels.f90.