CALYPSO: set_sp_rlm_leg_matmul_big Module Reference
set_sp_rlm_leg_matmul_big Module Reference
forward Legendre transform using matmulti
Functions/Subroutines
subroutine set_sp_rlm_vec_sym_matmul_big (nnod_rlm, nidx_rlm, istep_rlm, idx_gl_1d_rlm_j, a_r_1d_rlm_r, g_sph_rlm, kst, nkr, jst, n_jk_e, n_jk_o, ncomp, nvector, irev_sr_rlm, n_WR, WR, pol_e, tor_e, pol_o, tor_o)
subroutine set_sp_rlm_scl_sym_matmul_big (nnod_rlm, nidx_rlm, istep_rlm, kst, nkr, jst, n_jk_e, n_jk_o, ncomp, nvector, nscalar, irev_sr_rlm, n_WR, WR, scl_e, scl_o)
subroutine cal_sp_rlm_vec_sym_matmul_big (nnod_rlm, nidx_rlm, istep_rlm, idx_gl_1d_rlm_j, radius_1d_rlm_r, g_sph_rlm, kst, nkr, jst, n_jk_o, n_jk_e, pol_e, pol_o, tor_e, tor_o, ncomp, nvector, irev_sr_rlm, n_WS, WS)
subroutine cal_sp_rlm_scl_sym_matmul_big (nnod_rlm, nidx_rlm, istep_rlm, g_sph_rlm, kst, nkr, jst, n_jk_o, n_jk_e, scl_e, scl_o, ncomp, nvector, nscalar, irev_sr_rlm, n_WS, WS)
Detailed Description
forward Legendre transform using matmulti
      subroutine set_sp_rlm_vec_sym_matmul_big(nnod_rlm, nidx_rlm,    &
     &          istep_rlm, idx_gl_1d_rlm_j, a_r_1d_rlm_r, g_sph_rlm,  &
     &          kst, nkr, jst, n_jk_e, n_jk_o, ncomp, nvector,        &
     &          irev_sr_rlm, n_WR, WR,  pol_e, tor_e, pol_o, tor_o)
      subroutine set_sp_rlm_scl_sym_matmul_big                        &
     &         (nnod_rlm, nidx_rlm, istep_rlm, kst, nkr, jst,         &
     &          n_jk_e, n_jk_o, ncomp, nvector, nscalar, irev_sr_rlm, &
     &          n_WR, WR, scl_e, scl_o)
      subroutine cal_sp_rlm_vec_sym_matmul_big(nnod_rlm, nidx_rlm,    &
     &         istep_rlm, idx_gl_1d_rlm_j, radius_1d_rlm_r, g_sph_rlm,&
     &         kst, nkr, jst, n_jk_o, n_jk_e, pol_e, pol_o,           &
     &         tor_e, tor_o, ncomp, nvector, irev_sr_rlm, n_WS, WS)
      subroutine cal_sp_rlm_scl_sym_matmul_big                        &
     &         (nnod_rlm, nidx_rlm, istep_rlm, g_sph_rlm,             &
     &          kst, nkr, jst, n_jk_o, n_jk_e, scl_e, scl_o,          &
     &          ncomp, nvector, nscalar, irev_sr_rlm, n_WS, WS)
Function/Subroutine Documentation
cal_sp_rlm_scl_sym_matmul_big()
subroutine set_sp_rlm_leg_matmul_big::cal_sp_rlm_scl_sym_matmul_big (integer(kind = kint), intent(in) nnod_rlm, integer(kind = kint), dimension(2), intent(in) nidx_rlm, integer(kind = kint), dimension(2), intent(in) istep_rlm, real(kind = kreal), dimension(nidx_rlm(2),17), intent(in) g_sph_rlm, integer(kind = kint), intent(in) kst, integer(kind = kint), intent(in) nkr, integer(kind = kint), intent(in) jst, integer(kind = kint), intent(in) n_jk_o, integer(kind = kint), intent(in) n_jk_e, real(kind = kreal), dimension(ncomp*nkr,n_jk_e), intent(inout) scl_e, real(kind = kreal), dimension(ncomp*nkr,n_jk_o), intent(inout) scl_o, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, integer(kind = kint), dimension(nnod_rlm), intent(in) irev_sr_rlm, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 280 of file set_sp_rlm_leg_matmul_big.f90.
Referenced by leg_f_trans_sym_matmul_big::leg_fwd_trans_sym_matmul_big().
cal_sp_rlm_vec_sym_matmul_big()
subroutine set_sp_rlm_leg_matmul_big::cal_sp_rlm_vec_sym_matmul_big (integer(kind = kint), intent(in) nnod_rlm, integer(kind = kint), dimension(2), intent(in) nidx_rlm, integer(kind = kint), dimension(2), intent(in) istep_rlm, integer(kind = kint), dimension(nidx_rlm(2),3), intent(in) idx_gl_1d_rlm_j, real(kind = kreal), dimension(nidx_rlm(1)), intent(in) radius_1d_rlm_r, real(kind = kreal), dimension(nidx_rlm(2),17), intent(in) g_sph_rlm, integer(kind = kint), intent(in) kst, integer(kind = kint), intent(in) nkr, integer(kind = kint), intent(in) jst, integer(kind = kint), intent(in) n_jk_o, integer(kind = kint), intent(in) n_jk_e, real(kind = kreal), dimension(ncomp*nkr,n_jk_e), intent(inout) pol_e, real(kind = kreal), dimension(ncomp*nkr,n_jk_o), intent(inout) pol_o, real(kind = kreal), dimension(2*nvector*nkr,n_jk_e), intent(inout) tor_e, real(kind = kreal), dimension(2*nvector*nkr,n_jk_o), intent(inout) tor_o, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), dimension(nnod_rlm), intent(in) irev_sr_rlm, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 165 of file set_sp_rlm_leg_matmul_big.f90.
Referenced by leg_f_trans_sym_matmul_big::leg_fwd_trans_sym_matmul_big().
set_sp_rlm_scl_sym_matmul_big()
subroutine set_sp_rlm_leg_matmul_big::set_sp_rlm_scl_sym_matmul_big (integer(kind = kint), intent(in) nnod_rlm, integer(kind = kint), dimension(2), intent(in) nidx_rlm, integer(kind = kint), dimension(2), intent(in) istep_rlm, integer(kind = kint), intent(in) kst, integer(kind = kint), intent(in) nkr, integer(kind = kint), intent(in) jst, integer(kind = kint), intent(in) n_jk_e, integer(kind = kint), intent(in) n_jk_o, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, integer(kind = kint), dimension(nnod_rlm), intent(in) irev_sr_rlm, integer(kind = kint), intent(in) n_WR, real(kind = kreal), dimension(n_wr), intent(in) WR, real(kind = kreal), dimension(n_jk_e,ncomp*nkr), intent(inout) scl_e, real(kind = kreal), dimension(n_jk_o,ncomp*nkr), intent(inout) scl_o)
Definition at line 116 of file set_sp_rlm_leg_matmul_big.f90.
Referenced by leg_b_trans_sym_matmul_big::leg_bwd_trans_sym_matmul_big().
set_sp_rlm_vec_sym_matmul_big()
subroutine set_sp_rlm_leg_matmul_big::set_sp_rlm_vec_sym_matmul_big (integer(kind = kint), intent(in) nnod_rlm, integer(kind = kint), dimension(2), intent(in) nidx_rlm, integer(kind = kint), dimension(2), intent(in) istep_rlm, integer(kind = kint), dimension(nidx_rlm(2),3), intent(in) idx_gl_1d_rlm_j, real(kind = kreal), dimension(nidx_rlm(1)), intent(in) a_r_1d_rlm_r, real(kind = kreal), dimension(nidx_rlm(2),17), intent(in) g_sph_rlm, integer(kind = kint), intent(in) kst, integer(kind = kint), intent(in) nkr, integer(kind = kint), intent(in) jst, integer(kind = kint), intent(in) n_jk_e, integer(kind = kint), intent(in) n_jk_o, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), dimension(nnod_rlm), intent(in) irev_sr_rlm, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(in) WR, real(kind = kreal), dimension(n_jk_e,ncomp*nkr), intent(inout) pol_e, real(kind = kreal), dimension(n_jk_e,2*nvector*nkr), intent(inout) tor_e, real(kind = kreal), dimension(n_jk_o,ncomp*nkr), intent(inout) pol_o, real(kind = kreal), dimension(n_jk_o,2*nvector*nkr), intent(inout) tor_o)
Definition at line 43 of file set_sp_rlm_leg_matmul_big.f90.
Referenced by leg_b_trans_sym_matmul_big::leg_bwd_trans_sym_matmul_big().