CALYPSO: solver_sr_3 Module Reference
solver_sr_3 Module Reference
MPI SEND and RECEIVE routine for vector fields in overlapped partitioning.
Functions/Subroutines
subroutine solver_send_recv_3 (N, NEIBPETOT, NEIBPE, STACK_IMPORT, NOD_IMPORT, STACK_EXPORT, NOD_EXPORT, SR_sig, SR_r, X)
subroutine solver_send_recv_3x3 (N, NEIBPETOT, NEIBPE, STACK_IMPORT, NOD_IMPORT, STACK_EXPORT, NOD_EXPORT, SR_sig, SR_r, X1, X2, X3)
Detailed Description
MPI SEND and RECEIVE routine for vector fields in overlapped partitioning.
      subroutine  SOLVER_SEND_RECV_3(N, NEIBPETOT, NEIBPE,            &
     &                               STACK_IMPORT, NOD_IMPORT,        &
     &                               STACK_EXPORT, NOD_EXPORT,        &
     &                               SR_sig, SR_r, X)
      subroutine  solver_send_recv_3x3(N, NEIBPETOT, NEIBPE,          &
     &                                 STACK_IMPORT, NOD_IMPORT,      &
     &                                 STACK_EXPORT, NOD_EXPORT,      &
     &                                 SR_sig, SR_r, X1, X2, X3)
        type(send_recv_status), intent(inout) :: SR_sig
        type(send_recv_real_buffer), intent(inout) :: SR_r
Parameters
N Number of data points
Parameters
NEIBPETOT Number of processses to communicate
NEIBPE(NEIBPETOT) Process ID to communicate
STACK_IMPORT(0:NEIBPETOT) End points of import buffer for each process
NOD_IMPORT(STACK_IMPORT(NEIBPETOT)) local node ID to copy in import buffer
STACK_EXPORT(0:NEIBPETOT) End points of export buffer for each process
NOD_EXPORT(STACK_IMPORT(NEIBPETOT)) local node ID to copy in export buffer
Parameters
X(3*N) vector field data
X1(3*N) 1st vector field data
X2(3*N) 2nd vector field data
X3(3*N) 3rd vector field data
Function/Subroutine Documentation
solver_send_recv_3()
subroutine solver_sr_3::solver_send_recv_3 (integer(kind=kint), intent(in) N, integer(kind=kint), intent(in) NEIBPETOT, integer(kind=kint), dimension(neibpetot) NEIBPE, integer(kind=kint), dimension(0:neibpetot) STACK_IMPORT, integer(kind=kint), dimension(stack_import(neibpetot)) NOD_IMPORT, integer(kind=kint), dimension(0:neibpetot) STACK_EXPORT, integer(kind=kint), dimension(stack_export(neibpetot)) NOD_EXPORT, type(send_recv_status), intent(inout) SR_sig, type(send_recv_real_buffer), intent(inout) SR_r, real (kind=kreal), dimension(3*n), intent(inout) X)
Parameters
[in] n number of nodes
[in] neibpetot total neighboring pe count
neibpe neighboring pe id (i-th pe)
stack_import imported node count for each neighbor pe (i-th pe)
nod_import imported node (i-th dof)
stack_export exported node count for each neighbor pe (i-th pe)
nod_export exported node (i-th dof)
[in,out] x communicated result vector
[in,out] sr_sig Structure of communication flags
[in,out] sr_r Structure of communication buffer for 8-byte real
Definition at line 60 of file solver_SR_3.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_real, calypso_mpi::ierr_mpi, m_constants::ithree, and t_solver_sr::resize_work_sr().
Referenced by solver_sr_type::solver_send_recv_3_type().
solver_send_recv_3x3()
subroutine solver_sr_3::solver_send_recv_3x3 (integer(kind=kint), intent(in) N, integer(kind=kint), intent(in) NEIBPETOT, integer(kind=kint), dimension(neibpetot) NEIBPE, integer(kind=kint), dimension(0:neibpetot) STACK_IMPORT, integer(kind=kint), dimension(stack_import(neibpetot)) NOD_IMPORT, integer(kind=kint), dimension(0:neibpetot) STACK_EXPORT, integer(kind=kint), dimension(stack_export(neibpetot)) NOD_EXPORT, type(send_recv_status), intent(inout) SR_sig, type(send_recv_real_buffer), intent(inout) SR_r, real (kind=kreal), dimension(3*n), intent(inout) X1, real (kind=kreal), dimension(3*n), intent(inout) X2, real (kind=kreal), dimension(3*n), intent(inout) X3)
Parameters
[in,out] sr_sig Structure of communication flags
[in,out] sr_r Structure of communication buffer for 8-byte real
Definition at line 148 of file solver_SR_3.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_real, calypso_mpi::ierr_mpi, m_constants::inine, and t_solver_sr::resize_work_sr().
Referenced by solver_sr_type::solver_send_recv_3x3_type().