CALYPSO: t_ctl_data_crust_filter Module Reference
t_ctl_data_crust_filter Module Reference
Control data structure for zonal mean visualization controls.
Data Types
type clust_filtering_ctl
Structure of crustal filtering of mangeitc field.
Functions/Subroutines
subroutine read_crustal_filtering_ctl (id_control, hd_block, crust_filter_c, c_buf)
subroutine bcast_crustal_filtering_ctl (crust_filter_c)
subroutine reset_crustal_filtering_ctl (crust_filter_c)
Variables
character(len=kchara), parameter, private hd_crustal_truncation = 'truncation_degree_ctl'
Detailed Description
Control data structure for zonal mean visualization controls.
      subroutine read_crustal_filtering_ctl                       &
     &         (id_control, hd_block, crust_filter_c, c_buf)
      subroutine bcast_crustal_filtering_ctl(crust_filter_c)
      subroutine reset_crustal_filtering_ctl(crust_filter_c)
  begin dynamo_vizs_control
    begin crustal_filtering_ctl
      truncation_degree_ctl        13
    end crustal_filtering_ctl
  end dynamo_vizs_control
Function/Subroutine Documentation
bcast_crustal_filtering_ctl()
subroutine t_ctl_data_crust_filter::bcast_crustal_filtering_ctl (type(clust_filtering_ctl), intent(inout) crust_filter_c)
Definition at line 86 of file t_ctl_data_crust_filter.f90.
References bcast_control_arrays::bcast_ctl_type_i1(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by t_control_data_dynamo_vizs::bcast_dynamo_viz_control().
read_crustal_filtering_ctl()
subroutine t_ctl_data_crust_filter::read_crustal_filtering_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(clust_filtering_ctl), intent(inout) crust_filter_c, type(buffer_for_control), intent(inout) c_buf)
Definition at line 58 of file t_ctl_data_crust_filter.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_crustal_truncation, t_read_control_elements::load_one_line_from_control(), and t_control_array_integer::read_integer_ctl_type().
Referenced by t_control_data_dynamo_vizs::read_dynamo_viz_control().
reset_crustal_filtering_ctl()
subroutine t_ctl_data_crust_filter::reset_crustal_filtering_ctl (type(clust_filtering_ctl), intent(inout) crust_filter_c)
Definition at line 102 of file t_ctl_data_crust_filter.f90.
Variable Documentation
hd_crustal_truncation
character(len=kchara), parameter, private t_ctl_data_crust_filter::hd_crustal_truncation = 'truncation_degree_ctl' private
Definition at line 47 of file t_ctl_data_crust_filter.f90.
Referenced by read_crustal_filtering_ctl().