CALYPSO: t_boundary_data_sph_mhd Module Reference
t_boundary_data_sph_mhd Module Reference
Structure for basic boundary conditions for spherical dynamo.
Data Types
type sph_mhd_boundary_data
Structure for boundary conditions.
Functions/Subroutines
subroutine set_mhd_evolved_boundaries (time_d, sph, MHD_prop, sph_MHD_bc)
subroutine set_cv_evolved_boundaries (time_d, sph, MHD_prop, sph_MHD_bc)
Detailed Description
Structure for basic boundary conditions for spherical dynamo.
      subroutine set_MHD_evolved_boundaries                           &
     &         (time_d, sph, MHD_prop, sph_MHD_bc)
      subroutine set_cv_evolved_boundaries                            &
     &         (time_d, sph, MHD_prop, sph_MHD_bc)
        type(time_data), intent(in) :: time_d
        type(sph_grids), intent(in) :: sph
        type(MHD_evolution_param), intent(in) :: MHD_prop
        type(sph_MHD_boundary_data), intent(inout) :: sph_MHD_bc
Parameters
jmax number of modes for spherical harmonics \(L*(L+2)\)
nri number of radial grid points
radius radius
Function/Subroutine Documentation
set_cv_evolved_boundaries()
subroutine t_boundary_data_sph_mhd::set_cv_evolved_boundaries (type(time_data), intent(in) time_d, type(sph_grids), intent(in) sph, type(mhd_evolution_param), intent(in) MHD_prop, type(sph_mhd_boundary_data), intent(inout) sph_MHD_bc)
Definition at line 106 of file t_boundary_data_sph_MHD.f90.
References set_evoluved_boundaries::set_evo_scalar_boundaries(), and set_evoluved_boundaries::set_evo_vector_boundaries().
Referenced by set_mhd_evolved_boundaries().
set_mhd_evolved_boundaries()
subroutine t_boundary_data_sph_mhd::set_mhd_evolved_boundaries (type(time_data), intent(in) time_d, type(sph_grids), intent(in) sph, type(mhd_evolution_param), intent(in) MHD_prop, type(sph_mhd_boundary_data), intent(inout) sph_MHD_bc)
Definition at line 83 of file t_boundary_data_sph_MHD.f90.
References set_cv_evolved_boundaries(), and set_evoluved_boundaries::set_evo_vector_boundaries().
Referenced by sph_analyzer_mhd::sph_analyze_mhd(), sph_analyzer_snap_w_psf::sph_analyze_snap_psf(), and sph_analyzer_mhd::sph_initialize_mhd().