CALYPSO: mpi_mesh_file_io_b Module Reference
mpi_mesh_file_io_b Module Reference
Mesh file IO for gxipped format.
Functions/Subroutines
subroutine mpi_read_mesh_file_b (num_pe, id_rank, file_name, mesh_IO, group_IO)
subroutine mpi_read_mesh_geometry_b (num_pe, id_rank, file_name, mesh_IO)
subroutine mpi_read_node_size_b (num_pe, id_rank, file_name, mesh_IO)
subroutine mpi_read_geometry_size_b (num_pe, id_rank, file_name, mesh_IO)
subroutine mpi_write_mesh_file_b (file_name, mesh_IO, group_IO)
Variables
type(calypso_mpi_io_params), save, private io_param
Detailed Description
Mesh file IO for gxipped format.
      subroutine mpi_read_mesh_file_b                                 &
     &         (num_pe, id_rank, file_name, mesh_IO, group_IO)
        type(mesh_geometry), intent(inout) :: mesh_IO
        type(mesh_groups), intent(inout) ::   group_IO
      subroutine mpi_read_mesh_geometry_b(num_pe, id_rank, mesh_IO)
      subroutine mpi_read_node_size_b                                 &
     &         (num_pe, id_rank, file_name, mesh_IO)
      subroutine mpi_read_geometry_size_b                             &
     &         (num_pe, id_rank, file_name, mesh_IO)
        type(mesh_geometry), intent(inout) :: mesh_IO
      subroutine mpi_write_mesh_file_b(file_name, mesh_IO, group_IO)
        type(mesh_geometry), intent(in) :: mesh_IO
        type(mesh_groups), intent(in) ::   group_IO
Function/Subroutine Documentation
mpi_read_geometry_size_b()
subroutine mpi_mesh_file_io_b::mpi_read_geometry_size_b (integer, intent(in) num_pe, integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 121 of file MPI_mesh_file_IO_b.f90.
References mpi_ascii_data_io::close_mpi_file(), m_machine_parameter::i_debug, io_param, and mpi_mesh_data_io_b::mpi_read_num_node_ele_b().
Referenced by mesh_mpi_io_select::sel_mpi_read_geometry_size().
mpi_read_mesh_file_b()
subroutine mpi_mesh_file_io_b::mpi_read_mesh_file_b (integer, intent(in) num_pe, integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(inout) mesh_IO, type(mesh_groups), intent(inout) group_IO)
Definition at line 46 of file MPI_mesh_file_IO_b.f90.
References mpi_ascii_data_io::close_mpi_file(), m_machine_parameter::i_debug, io_param, mpi_mesh_data_io_b::mpi_read_geometry_data_b(), and mpi_mesh_data_io_b::mpi_read_mesh_groups_b().
Referenced by mesh_mpi_io_select::sel_mpi_read_mesh().
mpi_read_mesh_geometry_b()
subroutine mpi_mesh_file_io_b::mpi_read_mesh_geometry_b (integer, intent(in) num_pe, integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 74 of file MPI_mesh_file_IO_b.f90.
References mpi_ascii_data_io::close_mpi_file(), m_machine_parameter::i_debug, io_param, and mpi_mesh_data_io_b::mpi_read_geometry_data_b().
Referenced by mesh_mpi_io_select::sel_mpi_read_mesh_geometry().
mpi_read_node_size_b()
subroutine mpi_mesh_file_io_b::mpi_read_node_size_b (integer, intent(in) num_pe, integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 97 of file MPI_mesh_file_IO_b.f90.
References mpi_ascii_data_io::close_mpi_file(), m_machine_parameter::i_debug, io_param, and mpi_mesh_data_io_b::mpi_read_num_node_ele().
Referenced by mesh_mpi_io_select::sel_mpi_read_node_size().
mpi_write_mesh_file_b()
subroutine mpi_mesh_file_io_b::mpi_write_mesh_file_b (character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(in) mesh_IO, type(mesh_groups), intent(in) group_IO)
Definition at line 146 of file MPI_mesh_file_IO_b.f90.
References mpi_ascii_data_io::close_mpi_file(), m_machine_parameter::i_debug, io_param, mpi_mesh_data_io_b::mpi_write_geometry_data_b(), and mpi_mesh_data_io_b::mpi_write_mesh_groups_b().
Referenced by mesh_mpi_io_select::sel_mpi_write_mesh_file().
Variable Documentation
io_param
type(calypso_mpi_io_params), save, private mpi_mesh_file_io_b::io_param private
Definition at line 38 of file MPI_mesh_file_IO_b.f90.
Referenced by mpi_read_geometry_size_b(), mpi_read_mesh_file_b(), mpi_read_mesh_geometry_b(), mpi_read_node_size_b(), and mpi_write_mesh_file_b().