CALYPSO: t_sph_transforms Module Reference
t_sph_transforms Module Reference
Spherical harmonics transform for vector and gradient of scalar.
Data Types
type spherical_trns_works
Work structures for various spherical harmonics trasform.
Functions/Subroutines
subroutine sph_backward_transforms (ncomp_trans, nvector, nscalar, sph, comms_sph, trans_p, n_WS, n_WR, WS, WR, v_rtp, WK_leg, WK_FFTs)
subroutine sph_b_trans_w_poles (ncomp_trans, nvector, nscalar, sph, comms_sph, trans_p, n_WS, n_WR, WS, WR, v_rtp, v_pl_local, v_pole, WK_leg, WK_FFTs)
subroutine pole_b_transform (ncomp_trans, nvector, nscalar, sph, comms_sph, trans_p, n_WS, n_WR, WS, WR, v_pl_local, v_pole)
subroutine sph_forward_transforms (ncomp_trans, nvector, nscalar, sph, comms_sph, trans_p, v_rtp, n_WS, n_WR, WS, WR, WK_leg, WK_FFTs)
Detailed Description
Spherical harmonics transform for vector and gradient of scalar.
      subroutine sph_backward_transforms                              &
     &        (ncomp_trans, nvector, nscalar, sph, comms_sph, trans_p,&
     &         n_WS, n_WR, WS, WR, v_rtp, WK_leg, WK_FFTs)
      subroutine sph_b_trans_w_poles                                  &
     &        (ncomp_trans, nvector, nscalar, sph, comms_sph, trans_p,&
     &         n_WS, n_WR, WS, WR, v_rtp, v_pl_local, v_pole,         &
     &          WK_leg, WK_FFTs)
      subroutine pole_b_transform                                     &
     &        (ncomp_trans, nvector, nscalar, sph, comms_sph, trans_p,&
     &         n_WS, n_WR, WS, WR, v_pl_local, v_pole)
      subroutine sph_forward_transforms                               &
     &        (ncomp_trans, nvector, nscalar, sph, comms_sph, trans_p,&
     &         v_rtp, n_WS, n_WR, WS, WR, WK_leg, WK_FFTs)
        type(sph_grids), intent(in) :: sph
        type(sph_comm_tables), intent(in) :: comms_sph
        type(parameters_4_sph_trans), intent(in) :: trans_p
        type(legendre_trns_works), intent(inout) :: WK_leg
        type(work_for_FFTs), intent(inout) :: WK_FFTs
   input /outpt arrays for single field
      radial component:      v_rtp(i_rtp,1)
      elevetional component: v_rtp(i_rtp,2)
      azimuthal component:   v_rtp(i_rtp,3)
      Poloidal component:          WR(3*i_rj-2)
      diff. of Poloidal component: WR(3*i_rj-1)
      Toroidal component:          WR(3*i_rj  )
Parameters
ncomp_trans Number of components for transform
Function/Subroutine Documentation
pole_b_transform()
subroutine t_sph_transforms::pole_b_transform (integer(kind = kint), intent(in) ncomp_trans, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_grids), intent(in) sph, type(sph_comm_tables), intent(in) comms_sph, type(parameters_4_sph_trans), intent(in) trans_p, integer(kind = kint), intent(in) n_WS, integer(kind = kint), intent(in) n_WR, real(kind = kreal), dimension(n_ws), intent(inout) WS, real(kind = kreal), dimension(n_wr), intent(inout) WR, real(kind = kreal), dimension(sph%sph_rtp%nnod_pole,ncomp_trans), intent(inout) v_pl_local, real(kind = kreal), dimension(sph%sph_rtp%nnod_pole,ncomp_trans), intent(inout) v_pole)
Definition at line 199 of file t_sph_transforms.f90.
References calypso_mpi_real::calypso_mpi_allreduce_real(), spherical_srs_n::calypso_sph_comm_n(), m_work_time::end_elapsed_time(), spherical_srs_n::finish_send_recv_sph(), m_elapsed_labels_sph_trns::iflag_sph_time, m_elapsed_labels_sph_trns::ist_elapsed_sph, pole_sph_transform::pole_backward_transforms(), m_work_time::start_elapsed_time(), and m_constants::zero.
Referenced by sph_transforms_4_mhd::sph_pole_trans_4_mhd().
sph_b_trans_w_poles()
subroutine t_sph_transforms::sph_b_trans_w_poles (integer(kind = kint), intent(in) ncomp_trans, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_grids), intent(in) sph, type(sph_comm_tables), intent(in) comms_sph, type(parameters_4_sph_trans), intent(in) trans_p, integer(kind = kint), intent(in) n_WS, integer(kind = kint), intent(in) n_WR, real(kind = kreal), dimension(n_ws), intent(inout) WS, real(kind = kreal), dimension(n_wr), intent(inout) WR, real(kind = kreal), dimension(sph%sph_rtp%nnod_rtp,ncomp_trans), intent(inout) v_rtp, real(kind = kreal), dimension(sph%sph_rtp%nnod_pole,ncomp_trans), intent(inout) v_pl_local, real(kind = kreal), dimension(sph%sph_rtp%nnod_pole,ncomp_trans), intent(inout) v_pole, type(legendre_trns_works), intent(inout) WK_leg, type(work_for_ffts), intent(inout) WK_FFTs)
Definition at line 127 of file t_sph_transforms.f90.
References t_sph_fft_selector::back_fft_select_from_recv(), calypso_mpi_real::calypso_mpi_allreduce_real(), spherical_srs_n::calypso_sph_comm_n(), m_work_time::end_elapsed_time(), spherical_srs_n::finish_send_recv_sph(), m_machine_parameter::iflag_debug, m_elapsed_labels_sph_trns::iflag_sph_time, m_elapsed_labels_sph_trns::ist_elapsed_sph, pole_sph_transform::pole_backward_transforms(), t_legendre_trans_select::sel_backward_legendre_trans(), m_work_time::start_elapsed_time(), and m_constants::zero.
Referenced by sph_transforms_snapshot::sph_back_trans_snapshot_mhd().
sph_backward_transforms()
subroutine t_sph_transforms::sph_backward_transforms (integer(kind = kint), intent(in) ncomp_trans, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_grids), intent(in) sph, type(sph_comm_tables), intent(in) comms_sph, type(parameters_4_sph_trans), intent(in) trans_p, integer(kind = kint), intent(in) n_WS, integer(kind = kint), intent(in) n_WR, real(kind = kreal), dimension(n_ws), intent(inout) WS, real(kind = kreal), dimension(n_wr), intent(inout) WR, real(kind = kreal), dimension(sph%sph_rtp%nnod_rtp,ncomp_trans), intent(inout) v_rtp, type(legendre_trns_works), intent(inout) WK_leg, type(work_for_ffts), intent(inout) WK_FFTs)
Definition at line 77 of file t_sph_transforms.f90.
References t_sph_fft_selector::back_fft_select_from_recv(), spherical_srs_n::calypso_sph_comm_n(), m_work_time::end_elapsed_time(), spherical_srs_n::finish_send_recv_sph(), m_elapsed_labels_sph_trns::iflag_sph_time, m_elapsed_labels_sph_trns::ist_elapsed_sph, t_legendre_trans_select::sel_backward_legendre_trans(), and m_work_time::start_elapsed_time().
sph_forward_transforms()
subroutine t_sph_transforms::sph_forward_transforms (integer(kind = kint), intent(in) ncomp_trans, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_grids), intent(in) sph, type(sph_comm_tables), intent(in) comms_sph, type(parameters_4_sph_trans), intent(in) trans_p, real(kind = kreal), dimension(sph%sph_rtp%nnod_rtp,ncomp_trans), intent(in) v_rtp, integer(kind = kint), intent(in) n_WS, integer(kind = kint), intent(in) n_WR, real(kind = kreal), dimension(n_ws), intent(inout) WS, real(kind = kreal), dimension(n_wr), intent(inout) WR, type(legendre_trns_works), intent(inout) WK_leg, type(work_for_ffts), intent(inout) WK_FFTs)
Definition at line 245 of file t_sph_transforms.f90.
References spherical_srs_n::calypso_sph_comm_n(), m_work_time::end_elapsed_time(), spherical_srs_n::finish_send_recv_sph(), t_sph_fft_selector::fwd_fft_select_to_send(), m_machine_parameter::iflag_debug, m_elapsed_labels_sph_trns::iflag_sph_time, m_elapsed_labels_sph_trns::ist_elapsed_sph, t_legendre_trans_select::sel_forward_legendre_trans(), and m_work_time::start_elapsed_time().
Referenced by sph_transforms_snapshot::sph_forward_trans_snapshot_mhd().