CALYPSO: global_field_4_dynamobench Module Reference
global_field_4_dynamobench Module Reference
Evaluate global data for dynamo benchmark test.
Functions/Subroutines
subroutine copy_energy_4_dynamobench (pwr, KE_bench, ME_bench)
subroutine copy_icore_energy_4_dbench (pwr, mene_icore)
subroutine pick_inner_core_rotation (idx_rj_degree_one, nidx_rj, nlayer_ICB, ar_1d_rj, is_velo, nnod_rj, ntot_phys_rj, d_rj, rotate_icore)
subroutine pick_mag_torque_inner_core (idx_rj_degree_one, nidx_rj, nlayer_ICB, radius_1d_rj_r, is_lorentz, nnod_rj, ntot_phys_rj, d_rj, m_torque_icore)
Detailed Description
Evaluate global data for dynamo benchmark test.
      subroutine copy_energy_4_dynamobench(pwr, KE_bench, ME_bench)
      subroutine copy_icore_energy_4_dbench(pwr, mene_icore)
        type(sph_mean_squares), intent(in) :: pwr
      subroutine pick_inner_core_rotation(idx_rj_degree_one, nidx_rj, &
     &          nlayer_ICB, ar_1d_rj, is_velo,                        &
     &          nnod_rj, ntot_phys_rj, d_rj, rotate_icore)
      subroutine pick_mag_torque_inner_core(idx_rj_degree_one,        &
     &          nidx_rj, nlayer_ICB, radius_1d_rj_r, is_lorentz,      &
     &          nnod_rj, ntot_phys_rj, d_rj, m_torque_icore)
Function/Subroutine Documentation
copy_energy_4_dynamobench()
subroutine global_field_4_dynamobench::copy_energy_4_dynamobench (type(sph_mean_squares), intent(in) pwr, real(kind = kreal), dimension(3), intent(inout) KE_bench, real(kind = kreal), dimension(3), intent(inout) ME_bench)
Definition at line 35 of file global_field_4_dynamobench.f90.
References m_base_field_labels::magnetic_field, and m_base_field_labels::velocity.
Referenced by const_data_4_dynamobench::s_const_data_4_dynamobench().
copy_icore_energy_4_dbench()
subroutine global_field_4_dynamobench::copy_icore_energy_4_dbench (type(sph_mean_squares), intent(in) pwr, real(kind = kreal), dimension(3), intent(inout) mene_icore)
Definition at line 71 of file global_field_4_dynamobench.f90.
References m_base_field_labels::magnetic_field.
Referenced by const_data_4_dynamobench::s_const_data_4_dynamobench().
pick_inner_core_rotation()
subroutine global_field_4_dynamobench::pick_inner_core_rotation (integer(kind = kint), dimension(-1:1), intent(in) idx_rj_degree_one, integer(kind = kint), dimension(2), intent(in) nidx_rj, integer(kind = kint), intent(in) nlayer_ICB, real(kind = kreal), dimension(nidx_rj(1),3), intent(in) ar_1d_rj, integer(kind = kint), intent(in) is_velo, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(nnod_rj,ntot_phys_rj), intent(in) d_rj, real(kind = kreal), dimension(-1:1), intent(inout) rotate_icore)
Definition at line 98 of file global_field_4_dynamobench.f90.
References calypso_mpi_real::calypso_mpi_allreduce_real(), transfer_to_long_integers::cast_long(), and m_constants::zero.
Referenced by const_data_4_dynamobench::s_const_data_4_dynamobench().
pick_mag_torque_inner_core()
subroutine global_field_4_dynamobench::pick_mag_torque_inner_core (integer(kind = kint), dimension(-1:1), intent(in) idx_rj_degree_one, integer(kind = kint), dimension(2), intent(in) nidx_rj, integer(kind = kint), intent(in) nlayer_ICB, real(kind = kreal), dimension(nidx_rj(1)), intent(in) radius_1d_rj_r, integer(kind = kint), intent(in) is_lorentz, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(nnod_rj,ntot_phys_rj), intent(in) d_rj, real(kind = kreal), dimension(-1:1), intent(inout) m_torque_icore)
Definition at line 137 of file global_field_4_dynamobench.f90.
References calypso_mpi_real::calypso_mpi_allreduce_real(), transfer_to_long_integers::cast_long(), m_constants::eight, m_constants::five, m_constants::four, m_constants::one, m_constants::three, and m_constants::zero.
Referenced by const_data_4_dynamobench::s_const_data_4_dynamobench().