CALYPSO: /home/takumi kera/calypso/src/programs/SPH_MHD/main_sph_MHD_w_psf.f90 File Reference
main_sph_MHD_w_psf.f90 File Reference
program kemorin_sph_MHD
Functions/Subroutines
program kemorin_sph_mhd
Main program for MHD dynamo simulation.
Detailed Description
program kemorin_sph_MHD
Author
H. Matsui
Date
Programmed by H. Okuda in 2000
Modified by H. Matsui in May, 2003 (ver 2.0)
Connect to vizs by H. Matsui in July 2006 (ver 2.0)
Definition in file main_sph_MHD_w_psf.f90.
Function/Subroutine Documentation
kemorin_sph_mhd()
program kemorin_sph_mhd
Main program for MHD dynamo simulation.
Definition at line 11 of file main_sph_MHD_w_psf.f90.
References calypso_mpi::calypso_mpi_finalize(), calypso_mpi::calypso_mpi_init(), analyzer_sph_mhd_w_psf::evolution_sph_mhd_w_psf(), and analyzer_sph_mhd_w_psf::initialize_sph_mhd_w_psf().