CALYPSO: t_surface_group_connect Module Reference
t_surface_group_connect Module Reference
Structure of connectivity data for surface group items.
Data Types
type surface_node_grp_data
Structure of connectivity data for surface group items.
Functions/Subroutines
subroutine alloc_num_surf_grp_nod (num_surf, sf_nod)
subroutine alloc_num_surf_grp_nod_smp (num_surf_smp, sf_nod)
subroutine alloc_item_surf_grp_nod (sf_nod)
subroutine alloc_vect_surf_grp_nod (sf_nod)
subroutine dealloc_num_surf_grp_nod_smp (sf_nod)
subroutine dealloc_surf_grp_nod (sf_nod)
subroutine dealloc_vect_surf_grp_nod (sf_nod)
subroutine check_surface_node_id (id_check, sf_nod)
subroutine check_surf_nod_4_sheard_para (id_check, num_surf, sf_nod)
Detailed Description
Structure of connectivity data for surface group items.
      subroutine alloc_num_surf_grp_nod(num_surf, sf_nod)
      subroutine alloc_num_surf_grp_nod_smp(num_surf_smp, sf_nod)
      subroutine alloc_item_surf_grp_nod(sf_nod)
      subroutine alloc_vect_surf_grp_nod(sf_nod)
        type(surface_group_data), intent(in) :: sf_grp
        type(surface_node_grp_data), intent(in) :: sf_nod
      subroutine dealloc_num_surf_grp_nod_smp(sf_nod)
      subroutine dealloc_surf_grp_nod(sf_nod)
      subroutine dealloc_vect_surf_grp_nod(sf_nod)
        type(surface_node_grp_data), intent(in) :: sf_nod
       subroutine check_surface_node_id(id_check, sf_nod)
      subroutine check_surf_nod_4_sheard_para                         &
     &         (id_check, num_surf, sf_nod)
Function/Subroutine Documentation
alloc_item_surf_grp_nod()
subroutine t_surface_group_connect::alloc_item_surf_grp_nod (type(surface_node_grp_data), intent(inout) sf_nod)
Definition at line 95 of file t_surface_group_connect.f90.
Referenced by set_connects_4_surf_group::empty_surface_node_grp_type(), and set_connects_4_surf_group::set_node_4_surf_group().
alloc_num_surf_grp_nod()
subroutine t_surface_group_connect::alloc_num_surf_grp_nod (integer(kind = kint), intent(in) num_surf, type(surface_node_grp_data), intent(inout) sf_nod)
Definition at line 67 of file t_surface_group_connect.f90.
Referenced by set_connects_4_surf_group::empty_surface_node_grp_type(), and set_connects_4_surf_group::set_node_4_surf_group().
alloc_num_surf_grp_nod_smp()
subroutine t_surface_group_connect::alloc_num_surf_grp_nod_smp (integer(kind = kint), intent(in) num_surf_smp, type(surface_node_grp_data), intent(inout) sf_nod)
Definition at line 82 of file t_surface_group_connect.f90.
Referenced by set_connects_4_surf_group::set_node_4_surf_group().
alloc_vect_surf_grp_nod()
subroutine t_surface_group_connect::alloc_vect_surf_grp_nod (type(surface_node_grp_data), intent(inout) sf_nod)
Definition at line 114 of file t_surface_group_connect.f90.
Referenced by set_connects_4_surf_group::cal_surf_normal_at_nod().
check_surf_nod_4_sheard_para()
subroutine t_surface_group_connect::check_surf_nod_4_sheard_para (integer(kind = kint), intent(in) id_check, integer(kind = kint), intent(in) num_surf, type(surface_node_grp_data), intent(in) sf_nod)
Definition at line 186 of file t_surface_group_connect.f90.
References m_machine_parameter::np_smp.
check_surface_node_id()
subroutine t_surface_group_connect::check_surface_node_id (integer(kind = kint), intent(in) id_check, type(surface_node_grp_data), intent(in) sf_nod)
Definition at line 168 of file t_surface_group_connect.f90.
dealloc_num_surf_grp_nod_smp()
subroutine t_surface_group_connect::dealloc_num_surf_grp_nod_smp (type(surface_node_grp_data), intent(inout) sf_nod)
Definition at line 132 of file t_surface_group_connect.f90.
Referenced by t_mesh_data::dealloc_mesh_infomations().
dealloc_surf_grp_nod()
subroutine t_surface_group_connect::dealloc_surf_grp_nod (type(surface_node_grp_data), intent(inout) sf_nod)
Definition at line 143 of file t_surface_group_connect.f90.
Referenced by t_mesh_data::dealloc_mesh_infomations().
dealloc_vect_surf_grp_nod()
subroutine t_surface_group_connect::dealloc_vect_surf_grp_nod (type(surface_node_grp_data), intent(inout) sf_nod)
Definition at line 156 of file t_surface_group_connect.f90.
Referenced by t_mesh_data::dealloc_mesh_infos_w_normal().