CALYPSO: set_group_types_4_io Module Reference
set_group_types_4_io Module Reference
Copy group data.
Functions/Subroutines
subroutine set_gruop_stracture (org_group, new_group)
subroutine set_surf_grp_stracture (org_sf_grp, new_sf_grp)
integer(kind=kint) function compare_gruop_stracture (org_group, new_group)
integer(kind=kint) function compare_surf_grp_stracture (org_sf_grp, new_sf_grp)
Detailed Description
Copy group data.
      subroutine set_gruop_stracture(org_group, new_group)
        type(group_data), intent(in) :: org_group
        type(group_data), intent(inout) :: new_group
      subroutine set_surf_grp_stracture(org_sf_grp, new_sf_grp)
        type(surface_group_data), intent(in) :: org_sf_grp
        type(surface_group_data), intent(inout) :: new_sf_grp
      integer(kind = kint) function compare_gruop_stracture           &
     &                            (org_group, new_group)
        type(group_data), intent(in) :: org_group, new_group
      integer(kind = kint) function compare_surf_grp_stracture        &
     &                            (org_sf_grp, new_sf_grp)
        type(surface_group_data), intent(in) :: org_sf_grp, new_sf_grp
Function/Subroutine Documentation
compare_gruop_stracture()
integer(kind = kint) function set_group_types_4_io::compare_gruop_stracture (type(group_data), intent(in) org_group, type(group_data), intent(in) new_group)
Definition at line 104 of file set_group_types_4_IO.f90.
Referenced by compare_sph_with_io::compare_sph_rj_with_io(), and compare_sph_with_io::compare_sph_rtp_with_io().
compare_surf_grp_stracture()
integer(kind = kint) function set_group_types_4_io::compare_surf_grp_stracture (type(surface_group_data), intent(in) org_sf_grp, type(surface_group_data), intent(in) new_sf_grp)
Definition at line 131 of file set_group_types_4_IO.f90.
set_gruop_stracture()
subroutine set_group_types_4_io::set_gruop_stracture (type(group_data), intent(in) org_group, type(group_data), intent(inout) new_group)
Definition at line 39 of file set_group_types_4_IO.f90.
References t_group_data::alloc_group_item(), and t_group_data::alloc_group_num().
Referenced by load_data_for_sph_io::copy_sph_trans_rj_from_io(), load_data_for_sph_io::copy_sph_trans_rj_to_io(), load_data_for_sph_io::copy_sph_trans_rtp_from_io(), load_data_for_sph_io::copy_sph_trans_rtp_to_io(), load_mesh_data::set_grp_data_from_io(), and load_mesh_data::set_grp_data_to_io().
set_surf_grp_stracture()
subroutine set_group_types_4_io::set_surf_grp_stracture (type(surface_group_data), intent(in) org_sf_grp, type(surface_group_data), intent(inout) new_sf_grp)
Definition at line 71 of file set_group_types_4_IO.f90.
References t_group_data::alloc_sf_group_item(), and t_group_data::alloc_sf_group_num().
Referenced by load_mesh_data::set_grp_data_from_io(), and load_mesh_data::set_grp_data_to_io().