CALYPSO: gz_mpi_mesh_file_io_b Module Reference
gz_mpi_mesh_file_io_b Module Reference
Mesh file IO for gxipped format.
Functions/Subroutines
subroutine gz_mpi_read_mesh_file_b (num_pe, id_rank, file_name, mesh_IO, group_IO)
subroutine gz_mpi_read_mesh_geometry_b (num_pe, id_rank, file_name, mesh_IO)
subroutine gz_mpi_read_node_size_b (num_pe, id_rank, file_name, mesh_IO)
subroutine gz_mpi_read_geometry_size_b (num_pe, id_rank, file_name, mesh_IO)
subroutine gz_mpi_write_mesh_file_b (file_name, mesh_IO, group_IO)
Variables
type(calypso_mpi_io_params), save, private io_param
Detailed Description
Mesh file IO for gxipped format.
      subroutine gz_mpi_read_mesh_file_b                              &
     &         (num_pe, id_rank, file_name, mesh_IO, group_IO)
        type(mesh_geometry), intent(inout) :: mesh_IO
        type(mesh_groups), intent(inout) ::   group_IO
      subroutine gz_mpi_read_mesh_geometry_b                          &
     &         (num_pe, id_rank, file_name, mesh_IO)
      subroutine gz_mpi_read_node_size_b                              &
     &         (num_pe, id_rank, file_name, mesh_IO)
      subroutine gz_mpi_read_geometry_size_b                          &
     &         (num_pe, id_rank, file_name, mesh_IO)
        type(mesh_geometry), intent(inout) :: mesh_IO
      subroutine gz_mpi_write_mesh_file_b                             &
     &         (file_name, mesh_IO, group_IO)
        type(mesh_geometry), intent(in) :: mesh_IO
        type(mesh_groups), intent(in) ::   group_IO
Function/Subroutine Documentation
gz_mpi_read_geometry_size_b()
subroutine gz_mpi_mesh_file_io_b::gz_mpi_read_geometry_size_b (integer, intent(in) num_pe, integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 128 of file gz_MPI_mesh_file_IO_b.f90.
References mpi_ascii_data_io::close_mpi_file(), gz_mpi_mesh_data_io_b::gz_mpi_read_num_node_ele_b(), m_machine_parameter::i_debug, io_param, and gz_mpi_binary_datum_io::open_read_gz_mpi_file_b().
Referenced by mesh_mpi_io_select::sel_mpi_read_geometry_size().
gz_mpi_read_mesh_file_b()
subroutine gz_mpi_mesh_file_io_b::gz_mpi_read_mesh_file_b (integer, intent(in) num_pe, integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(inout) mesh_IO, type(mesh_groups), intent(inout) group_IO)
Definition at line 50 of file gz_MPI_mesh_file_IO_b.f90.
References mpi_ascii_data_io::close_mpi_file(), gz_mpi_mesh_data_io_b::gz_mpi_read_geometry_data_b(), gz_mpi_mesh_data_io_b::gz_mpi_read_mesh_groups_b(), m_machine_parameter::i_debug, io_param, and gz_mpi_binary_datum_io::open_read_gz_mpi_file_b().
Referenced by mesh_mpi_io_select::sel_mpi_read_mesh().
gz_mpi_read_mesh_geometry_b()
subroutine gz_mpi_mesh_file_io_b::gz_mpi_read_mesh_geometry_b (integer, intent(in) num_pe, integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 79 of file gz_MPI_mesh_file_IO_b.f90.
References mpi_ascii_data_io::close_mpi_file(), gz_mpi_mesh_data_io_b::gz_mpi_read_geometry_data_b(), m_machine_parameter::i_debug, io_param, and gz_mpi_binary_datum_io::open_read_gz_mpi_file_b().
Referenced by mesh_mpi_io_select::sel_mpi_read_mesh_geometry().
gz_mpi_read_node_size_b()
subroutine gz_mpi_mesh_file_io_b::gz_mpi_read_node_size_b (integer, intent(in) num_pe, integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 103 of file gz_MPI_mesh_file_IO_b.f90.
References mpi_ascii_data_io::close_mpi_file(), gz_mpi_mesh_data_io_b::gz_mpi_read_num_node_b(), m_machine_parameter::i_debug, io_param, and gz_mpi_binary_datum_io::open_read_gz_mpi_file_b().
Referenced by mesh_mpi_io_select::sel_mpi_read_node_size().
gz_mpi_write_mesh_file_b()
subroutine gz_mpi_mesh_file_io_b::gz_mpi_write_mesh_file_b (character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(in) mesh_IO, type(mesh_groups), intent(in) group_IO)
Definition at line 154 of file gz_MPI_mesh_file_IO_b.f90.
References mpi_ascii_data_io::close_mpi_file(), gz_mpi_mesh_data_io_b::gz_mpi_write_geometry_data_b(), gz_mpi_mesh_data_io_b::gz_mpi_write_mesh_groups_b(), m_machine_parameter::i_debug, io_param, and gz_mpi_binary_datum_io::open_write_gz_mpi_file_b().
Referenced by mesh_mpi_io_select::sel_mpi_write_mesh_file().
Variable Documentation
io_param
type(calypso_mpi_io_params), save, private gz_mpi_mesh_file_io_b::io_param private
Definition at line 42 of file gz_MPI_mesh_file_IO_b.f90.
Referenced by gz_mpi_read_geometry_size_b(), gz_mpi_read_mesh_file_b(), gz_mpi_read_mesh_geometry_b(), gz_mpi_read_node_size_b(), and gz_mpi_write_mesh_file_b().