CALYPSO: gzip_infleate Module Reference
gzip_infleate Module Reference
Data Types
interface gzip_infleat_begin
interface gzip_infleat_cont
interface gzip_infleat_last
interface gzip_infleat_once
Functions/Subroutines
subroutine gzip_infleat_real_once (len_gzipbuf, gzipbuf, num, data, zbuf)
subroutine gzip_infleat_int8_once (len_gzipbuf, gzipbuf, num, int8_dat, zbuf)
subroutine gzip_infleat_int4_once (len_gzipbuf, gzipbuf, num, int4_dat, zbuf)
subroutine gzip_infleat_char_once (len_gzipbuf, gzipbuf, len_buf, textbuf, zbuf)
subroutine gzip_infleat_char_begin (zbuf)
subroutine gzip_infleat_char_cont (zbuf)
subroutine gzip_infleat_char_last (zbuf)
Function/Subroutine Documentation
gzip_infleat_char_begin()
subroutine gzip_infleate::gzip_infleat_char_begin (type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 198 of file gzip_infleate.f90.
Referenced by zlib_cvt_ascii_ele_connect::infleate_1d_global_address(), zlib_cvt_ascii_comm_tbl::infleate_comm_table(), zlib_cvt_ascii_ele_connect::infleate_ele_connect(), zlib_cvt_ascii_ele_connect::infleate_ele_int_list(), zlib_cvt_ascii_comm_tbl::infleate_element_type(), zlib_convert_ascii_vector::infleate_node_position(), and zlib_convert_ascii_vector::infleate_vector_txt().
gzip_infleat_char_cont()
subroutine gzip_infleate::gzip_infleat_char_cont (type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 209 of file gzip_infleate.f90.
Referenced by zlib_cvt_ascii_ele_connect::infleate_1d_global_address(), zlib_cvt_ascii_comm_tbl::infleate_comm_table(), zlib_cvt_ascii_ele_connect::infleate_ele_connect(), zlib_cvt_ascii_ele_connect::infleate_ele_int_list(), zlib_cvt_ascii_comm_tbl::infleate_element_type(), zlib_convert_ascii_vector::infleate_node_position(), and zlib_convert_ascii_vector::infleate_vector_txt().
gzip_infleat_char_last()
subroutine gzip_infleate::gzip_infleat_char_last (type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 220 of file gzip_infleate.f90.
Referenced by zlib_cvt_ascii_ele_connect::infleate_1d_global_address(), zlib_cvt_ascii_comm_tbl::infleate_comm_table(), zlib_cvt_ascii_ele_connect::infleate_ele_connect(), zlib_cvt_ascii_ele_connect::infleate_ele_int_list(), zlib_cvt_ascii_comm_tbl::infleate_element_type(), zlib_convert_ascii_vector::infleate_node_position(), and zlib_convert_ascii_vector::infleate_vector_txt().
gzip_infleat_char_once()
subroutine gzip_infleate::gzip_infleat_char_once (integer, intent(in) len_gzipbuf, character(len=1), dimension(len_gzipbuf), intent(in), target gzipbuf, integer, intent(in) len_buf, character(len=1), dimension(len_buf), intent(in), target textbuf, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 175 of file gzip_infleate.f90.
References t_buffer_4_gzip::link_pointer_for_zlib_buffer().
Referenced by data_convert_by_zlib::infleate_1d_character_b(), zlib_cvt_ascii_ele_connect::infleate_1d_global_address(), zlib_convert_text::infleate_1word(), zlib_convert_text::infleate_characters(), zlib_cvt_ascii_comm_tbl::infleate_comm_table(), zlib_cvt_ascii_ele_connect::infleate_ele_connect(), zlib_cvt_ascii_ele_connect::infleate_ele_int_list(), zlib_cvt_ascii_comm_tbl::infleate_element_type(), zlib_convert_ascii_vector::infleate_node_position(), zlib_convert_text::infleate_skip_header(), and zlib_convert_ascii_vector::infleate_vector_txt().
gzip_infleat_int4_once()
subroutine gzip_infleate::gzip_infleat_int4_once (integer, intent(in) len_gzipbuf, character(len=1), dimension(len_gzipbuf), intent(in), target gzipbuf, integer, intent(in) num, integer(kind = 4), dimension(num), intent(inout), target int4_dat, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 152 of file gzip_infleate.f90.
References t_buffer_4_gzip::link_compressed_buffer(), and t_buffer_4_gzip::link_int4_buffer_for_zlib().
Referenced by data_convert_by_zlib::infleate_endian_flag().
gzip_infleat_int8_once()
subroutine gzip_infleate::gzip_infleat_int8_once (integer, intent(in) len_gzipbuf, character(len=1), dimension(len_gzipbuf), intent(in), target gzipbuf, integer, intent(in) num, integer(kind = kint_gl), dimension(num), intent(inout), target int8_dat, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 130 of file gzip_infleate.f90.
References t_buffer_4_gzip::link_compressed_buffer(), and t_buffer_4_gzip::link_int8_buffer_for_zlib().
Referenced by data_convert_by_zlib::infleate_int8_vector_b().
gzip_infleat_real_once()
subroutine gzip_infleate::gzip_infleat_real_once (integer, intent(in) len_gzipbuf, character(len=1), dimension(len_gzipbuf), intent(in), target gzipbuf, integer, intent(in) num, real(kind = kreal), dimension(num), intent(inout), target data, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 108 of file gzip_infleate.f90.
References t_buffer_4_gzip::link_compressed_buffer(), and t_buffer_4_gzip::link_real_buffer_for_zlib().
Referenced by data_convert_by_zlib::infleate_1d_vector_b().