CALYPSO: rayleigh_restart_io Module Reference
rayleigh_restart_io Module Reference
Set file extension.
Functions/Subroutines
character(len=kchara) function sel_rayleigh_file_name (i_version, dir, int_id, postfix)
subroutine sel_read_rayleigh_rst_params (dir, i_step, ra_rst)
subroutine init_rayleigh_restart_input (i_version, dir, i_step, fld_IO)
logical function, private check_raylegh_rst_field (i_version, dir, i_step, sclchar)
subroutine, private set_rayleigh_restart_field (i_version, dir, i_step, fld_IO)
subroutine set_rayleigh_rst_file_name (i_version, dir, i_step, field_name, iflag_ncomp, file_name)
Detailed Description
Set file extension.
      character(len = kchara) function sel_rayleigh_file_name         &
     &                               (i_version, dir, int_id, postfix)
      subroutine sel_read_rayleigh_rst_params(dir, i_step, ra_rst)
        type(rayleigh_restart), intent(inout) :: ra_rst
          Version 0.99: "[dir]/[int_id]_[field_flag]"
          Version 1.x:  "[dir]/[int_id]/[field_flag]"
      subroutine init_rayleigh_restart_input                          &
     &         (i_version, dir, i_step, fld_IO)
        type(field_IO), intent(inout) :: fld_IO
      subroutine set_rayleigh_rst_file_name(i_version, dir, i_step,   &
     &          field_name, iflag_ncomp, file_name)
Function/Subroutine Documentation
check_raylegh_rst_field()
logical function, private rayleigh_restart_io::check_raylegh_rst_field (integer(kind = kint), intent(in) i_version, character(len = kchara), intent(in) dir, integer(kind = kint), intent(in) i_step, character(len = kchara), intent(in) sclchar) private
Definition at line 127 of file rayleigh_restart_IO.f90.
References delete_data_files::check_file_exist(), and sel_rayleigh_file_name().
Referenced by set_rayleigh_restart_field().
init_rayleigh_restart_input()
subroutine rayleigh_restart_io::init_rayleigh_restart_input (integer(kind = kint), intent(in) i_version, character(len = kchara), intent(in) dir, integer(kind = kint), intent(in) i_step, type(field_io), intent(inout) fld_IO)
Definition at line 89 of file rayleigh_restart_IO.f90.
References t_field_data_io::alloc_phys_data_io(), t_field_data_io::alloc_phys_name_io(), t_field_data_io::cal_istack_phys_comp_io(), calypso_mpi_char::calypso_mpi_bcast_character(), calypso_mpi_int::calypso_mpi_bcast_int(), calypso_mpi_int::calypso_mpi_bcast_one_int(), transfer_to_long_integers::cast_long(), m_precision::kchara, calypso_mpi::my_rank, and set_rayleigh_restart_field().
Referenced by analyzer_rayleigh_cvt_sph::init_cvt_rayleigh_sph().
sel_rayleigh_file_name()
character(len = kchara) function rayleigh_restart_io::sel_rayleigh_file_name (integer(kind = kint), intent(in) i_version, character(len=kchara), intent(in) dir, integer(kind = kint), intent(in) int_id, character(len=kchara), intent(in) postfix)
Definition at line 47 of file rayleigh_restart_IO.f90.
References t_rayleigh_restart_io::set_rayleigh_file_name().
Referenced by check_raylegh_rst_field(), and set_rayleigh_rst_file_name().
sel_read_rayleigh_rst_params()
subroutine rayleigh_restart_io::sel_read_rayleigh_rst_params (character(len = kchara), intent(in) dir, integer(kind = kint), intent(in) i_step, type(rayleigh_restart), intent(inout) ra_rst)
Definition at line 68 of file rayleigh_restart_IO.f90.
References t_rayleigh_restart_io::read_rayleigh_restart_params().
Referenced by t_convert_from_rayleigh::init_rayleigh_restart_params().
set_rayleigh_restart_field()
subroutine, private rayleigh_restart_io::set_rayleigh_restart_field (integer(kind = kint), intent(in) i_version, character(len = kchara), intent(in) dir, integer(kind = kint), intent(in) i_step, type(field_io), intent(inout) fld_IO) private
Definition at line 147 of file rayleigh_restart_IO.f90.
References t_rayleigh_restart_io::aabchar, t_rayleigh_restart_io::achar, t_field_data_io::alloc_phys_name_io(), t_field_data_io::append_phys_name_io(), t_rayleigh_restart_io::cabchar, t_rayleigh_restart_io::cchar, check_raylegh_rst_field(), m_base_field_labels::magnetic_field, t_rayleigh_restart_io::pchar, m_base_field_labels::pressure, m_explicit_term_labels::previous_heat, m_explicit_term_labels::previous_induction, m_explicit_term_labels::previous_momentum, t_rayleigh_restart_io::tabchar, t_rayleigh_restart_io::tchar, m_base_field_labels::temperature, m_base_field_labels::velocity, t_rayleigh_restart_io::wabchar, t_rayleigh_restart_io::wchar, t_rayleigh_restart_io::zabchar, and t_rayleigh_restart_io::zchar.
Referenced by init_rayleigh_restart_input().
set_rayleigh_rst_file_name()
subroutine rayleigh_restart_io::set_rayleigh_rst_file_name (integer(kind = kint), intent(in) i_version, character(len = kchara), intent(in) dir, integer(kind = kint), intent(in) i_step, character(len = kchara), intent(in) field_name, integer(kind = kint), intent(inout) iflag_ncomp, character(len = kchara), dimension(2), intent(inout) file_name)
Definition at line 193 of file rayleigh_restart_IO.f90.
References t_rayleigh_restart_io::aabchar, t_rayleigh_restart_io::achar, t_rayleigh_restart_io::cabchar, t_rayleigh_restart_io::cchar, m_base_field_labels::magnetic_field, t_rayleigh_restart_io::pchar, m_base_field_labels::pressure, m_explicit_term_labels::previous_heat, m_explicit_term_labels::previous_induction, m_explicit_term_labels::previous_momentum, sel_rayleigh_file_name(), t_rayleigh_restart_io::tabchar, t_rayleigh_restart_io::tchar, m_base_field_labels::temperature, m_base_field_labels::velocity, t_rayleigh_restart_io::wabchar, t_rayleigh_restart_io::wchar, t_rayleigh_restart_io::zabchar, and t_rayleigh_restart_io::zchar.
Referenced by convert_from_rayleigh_rst::convert_fields_from_rayleigh().