CALYPSO: load_mesh_and_field_4_viz Module Reference
load_mesh_and_field_4_viz Module Reference
Load FEM data loading for visualize program.
Functions/Subroutines
subroutine set_control_params_4_viz (tctl, plt, mesh_file, ucd_param, t_viz_param, ierr)
subroutine mesh_setup_4_viz (init_d, ucd_step, ucd_param, mesh_file, fem, t_IO, ucd, field)
subroutine set_field_data_4_viz (istep, ucd_step, ucd_param, fem, t_IO, ucd, time_d, field)
Detailed Description
Load FEM data loading for visualize program.
      subroutine set_control_params_4_viz                             &
     &         (tctl, plt, mesh_file, ucd_param, ierr)
        type(time_data_control), intent(in) :: tctl
        type(platform_data_control), intent(in) :: plt
        type(field_IO_params), intent(inout) :: mesh_file
        type(IO_step_param), intent(in) :: ucd_step
        type(field_IO_params), intent(inout) :: ucd_param
        type(time_step_param_w_viz), intent(inout) :: t_viz_param
      subroutine mesh_setup_4_VIZ(init_d, ucd_step, mesh_file,        &
     &          ucd_param, fem, t_IO, ucd, field)
        type(field_IO_params), intent(in) :: mesh_file
        type(field_IO_params), intent(in) :: ucd_param
        type(IO_step_param), intent(in) :: ucd_step
        type(time_data), intent(in) :: init_d
        type(mesh_data), intent(inout) :: fem
        type(time_data), intent(inout) :: t_IO
        type(ucd_data), intent(inout) :: ucd
        type(phys_data), intent(inout) :: field
      subroutine set_field_data_4_VIZ(istep, ucd_step, ucd_param,     &
     &          fem, t_IO, ucd, time_d, field)
        type(field_IO_params), intent(in) :: ucd_param
        type(time_data), intent(inout) :: time_d
Function/Subroutine Documentation
mesh_setup_4_viz()
subroutine load_mesh_and_field_4_viz::mesh_setup_4_viz (type(time_data), intent(in) init_d, type(io_step_param), intent(in) ucd_step, type(field_io_params), intent(in) ucd_param, type(field_io_params), intent(in) mesh_file, type(mesh_data), intent(inout) fem, type(time_data), intent(inout) t_IO, type(ucd_data), intent(inout) ucd, type(phys_data), intent(inout) field)
Definition at line 94 of file load_mesh_and_field_4_viz.f90.
References set_ucd_data_to_type::alloc_phys_data_type_by_output(), parallel_fem_mesh_init::fem_mesh_initialization(), m_machine_parameter::iflag_debug, t_io_step_parameter::io_step_exc_zero_inc(), mpi_load_mesh_data::mpi_input_mesh(), calypso_mpi::my_rank, calypso_mpi::nprocs, and ucd_io_select::sel_read_udt_param().
Referenced by fem_analyzer_viz_surf::fem_initialize_surface(), and fem_analyzer_vtk_convert::fem_initialize_vtk_convert().
set_control_params_4_viz()
subroutine load_mesh_and_field_4_viz::set_control_params_4_viz (type(time_data_control), intent(in) tctl, type(platform_data_control), intent(in) plt, type(field_io_params), intent(inout) mesh_file, type(field_io_params), intent(inout) ucd_param, type(time_step_param_w_viz), intent(inout) t_viz_param, integer(kind = kint), intent(inout) ierr)
Definition at line 58 of file load_mesh_and_field_4_viz.f90.
References t_time_data::copy_delta_t(), m_machine_parameter::e_message, calypso_mpi::my_rank, set_control_platform_data::set_control_mesh_def(), set_control_platform_data::set_control_smp_def(), t_viz_only_step_parameter::set_fixed_t_step_params_w_viz(), ucd_io_select::set_ucd_file_define(), and set_control_platform_data::turn_off_debug_flag_by_ctl().
Referenced by analyzer_psf::init_analyzer_psf(), and analyzer_vtk_convert::init_analyzer_vtk_convert().
set_field_data_4_viz()
subroutine load_mesh_and_field_4_viz::set_field_data_4_viz (integer(kind = kint), intent(in) istep, type(io_step_param), intent(in) ucd_step, type(field_io_params), intent(in) ucd_param, type(mesh_data), intent(in) fem, type(time_data), intent(inout) t_IO, type(ucd_data), intent(inout) ucd, type(time_data), intent(inout) time_d, type(phys_data), intent(inout) field)
Definition at line 139 of file load_mesh_and_field_4_viz.f90.
References t_time_data::copy_time_step_size_data(), m_machine_parameter::iflag_debug, t_io_step_parameter::io_step_exc_zero_inc(), nod_phys_send_recv::nod_fields_send_recv(), and output_parallel_ucd_file::set_data_by_read_ucd().
Referenced by fem_analyzer_viz_surf::fem_analyze_surface(), and fem_analyzer_vtk_convert::fem_analyze_vtk_convert().