CALYPSO: m_initial_field_control Module Reference
m_initial_field_control Module Reference
Control flags for initial data.
Functions/Subroutines
subroutine set_initial_field_id (restart_flag_ctl, tctl, time_init)
Variables
character(len=kchara), parameter, private no_restart = 'no_data'
Label for starting from zero fields.
character(len=kchara), parameter, private from_restart = 'start_from_rst_file'
Label for starting from saved restart data.
character(len=kchara), parameter, private dynamobench_0 = 'dynamo_benchmark_0'
Label for dynamo benchmark Case 0.
character(len=kchara), parameter, private dynamobench_1 = 'dynamo_benchmark_1'
Label for dynamo benchmark Case 1.
character(len=kchara), parameter, private dynamobench_2 = 'dynamo_benchmark_2'
Label for dynamo benchmark Case 2.
character(len=kchara), parameter, private pseudo_bench = 'pseudo_vacuum_benchmark'
Label for pseudo vacuume dynamo benchmar.
character(len=kchara), parameter, private rotate_x = 'rotate_x'
Label for solid body rotation around x-axis.
character(len=kchara), parameter, private rotate_y = 'rotate_y'
Label for solid body rotation around y-axis.
character(len=kchara), parameter, private rotate_z = 'rotate_z'
Label for solid body rotation around z-axis.
character(len=kchara), parameter, private kinematic = 'kinematic'
Label for kinematic dynamo.
character(len=kchara), parameter, private liear_cv = 'linear_conveciton'
Label for linear convection model.
integer(kind=kint), parameter i_rst_no_file = 0
Start ID from zero fields.
integer(kind=kint), parameter i_rst_by_file = 1
Start ID from saved restart data.
integer(kind=kint), parameter i_rst_dbench0 = -1
Use initial field for dynamo benchmark Case 0.
integer(kind=kint), parameter i_rst_dbench1 = -2
Use initial field for dynamo benchmark Case 1.
integer(kind=kint), parameter i_rst_dbench2 = -3
Use initial field for dynamo benchmark Case 2.
integer(kind=kint), parameter i_rst_dbench_qcv = -31
Use initial field for pseudo vacuume dynamo benchmark.
integer(kind=kint), parameter i_rst_rotate_x = -11
Start ID from solid body rotation around x-axis.
integer(kind=kint), parameter i_rst_rotate_y = -12
Start ID from solid body rotation around y-axis.
integer(kind=kint), parameter i_rst_rotate_z = -13
Start ID from solid body rotation around z-axis.
integer(kind=kint), parameter i_rst_kinematic = 20
Initial field for kinematic dynamo.
integer(kind=kint), parameter i_rst_licv = -20
Initial field for linear convection model.
integer(kind=kint) iflag_restart = i_rst_no_file
flag for the initial field
Detailed Description
Control flags for initial data.
Function/Subroutine Documentation
set_initial_field_id()
subroutine m_initial_field_control::set_initial_field_id (type(read_character_item), intent(in) restart_flag_ctl, type(time_data_control), intent(in) tctl, real(kind = kreal), intent(inout) time_init)
Definition at line 97 of file m_initial_field_control.f90.
References calypso_mpi::calypso_mpi_abort(), skip_comment_f::cmp_no_case(), dynamobench_0, dynamobench_1, dynamobench_2, m_machine_parameter::e_message, from_restart, i_rst_by_file, i_rst_dbench0, i_rst_dbench1, i_rst_dbench2, i_rst_dbench_qcv, i_rst_kinematic, i_rst_licv, i_rst_no_file, i_rst_rotate_x, i_rst_rotate_y, i_rst_rotate_z, m_error_ids::ierr_evo, m_machine_parameter::iflag_debug, iflag_restart, m_machine_parameter::iflag_routine_msg, kinematic, liear_cv, no_restart, pseudo_bench, rotate_x, rotate_y, and rotate_z.
Referenced by t_mhd_step_parameter::s_set_control_4_time_steps().
Variable Documentation
dynamobench_0
character(len=kchara), parameter, private m_initial_field_control::dynamobench_0 = 'dynamo_benchmark_0' private
Label for dynamo benchmark Case 0.
Definition at line 29 of file m_initial_field_control.f90.
Referenced by set_initial_field_id().
dynamobench_1
character(len=kchara), parameter, private m_initial_field_control::dynamobench_1 = 'dynamo_benchmark_1' private
Label for dynamo benchmark Case 1.
Definition at line 32 of file m_initial_field_control.f90.
Referenced by set_initial_field_id().
dynamobench_2
character(len=kchara), parameter, private m_initial_field_control::dynamobench_2 = 'dynamo_benchmark_2' private
Label for dynamo benchmark Case 2.
Definition at line 35 of file m_initial_field_control.f90.
Referenced by set_initial_field_id().
from_restart
character(len=kchara), parameter, private m_initial_field_control::from_restart = 'start_from_rst_file' private
Label for starting from saved restart data.
Definition at line 25 of file m_initial_field_control.f90.
Referenced by set_initial_field_id().
i_rst_by_file
integer(kind=kint), parameter m_initial_field_control::i_rst_by_file = 1
Start ID from saved restart data.
Definition at line 58 of file m_initial_field_control.f90.
Referenced by set_initial_field_id(), and set_initial_sph_dynamo::sph_initial_data_control().
i_rst_dbench0
integer(kind=kint), parameter m_initial_field_control::i_rst_dbench0 = -1
Use initial field for dynamo benchmark Case 0.
Definition at line 61 of file m_initial_field_control.f90.
Referenced by set_initial_field_id(), and set_initial_sph_dynamo::sph_initial_data_control().
i_rst_dbench1
integer(kind=kint), parameter m_initial_field_control::i_rst_dbench1 = -2
Use initial field for dynamo benchmark Case 1.
Definition at line 63 of file m_initial_field_control.f90.
Referenced by set_initial_field_id(), set_initial_sph_dynamo::sph_initial_data_4_benchmarks(), and set_initial_sph_dynamo::sph_initial_data_control().
i_rst_dbench2
integer(kind=kint), parameter m_initial_field_control::i_rst_dbench2 = -3
Use initial field for dynamo benchmark Case 2.
Definition at line 65 of file m_initial_field_control.f90.
Referenced by set_initial_field_id(), set_initial_sph_dynamo::sph_initial_data_4_benchmarks(), and set_initial_sph_dynamo::sph_initial_data_control().
i_rst_dbench_qcv
integer(kind=kint), parameter m_initial_field_control::i_rst_dbench_qcv = -31
Use initial field for pseudo vacuume dynamo benchmark.
Definition at line 68 of file m_initial_field_control.f90.
Referenced by set_initial_field_id(), set_initial_sph_dynamo::sph_initial_data_4_benchmarks(), and set_initial_sph_dynamo::sph_initial_data_control().
i_rst_kinematic
integer(kind=kint), parameter m_initial_field_control::i_rst_kinematic = 20
Initial field for kinematic dynamo.
Definition at line 78 of file m_initial_field_control.f90.
Referenced by set_initial_field_id().
i_rst_licv
integer(kind=kint), parameter m_initial_field_control::i_rst_licv = -20
Initial field for linear convection model.
Definition at line 80 of file m_initial_field_control.f90.
Referenced by set_initial_field_id(), and set_initial_sph_dynamo::sph_initial_data_control().
i_rst_no_file
integer(kind=kint), parameter m_initial_field_control::i_rst_no_file = 0
Start ID from zero fields.
Definition at line 56 of file m_initial_field_control.f90.
Referenced by set_initial_field_id(), and set_initial_sph_dynamo::sph_initial_data_control().
i_rst_rotate_x
integer(kind=kint), parameter m_initial_field_control::i_rst_rotate_x = -11
Start ID from solid body rotation around x-axis.
Definition at line 71 of file m_initial_field_control.f90.
Referenced by set_initial_field_id().
i_rst_rotate_y
integer(kind=kint), parameter m_initial_field_control::i_rst_rotate_y = -12
Start ID from solid body rotation around y-axis.
Definition at line 73 of file m_initial_field_control.f90.
Referenced by set_initial_field_id().
i_rst_rotate_z
integer(kind=kint), parameter m_initial_field_control::i_rst_rotate_z = -13
Start ID from solid body rotation around z-axis.
Definition at line 75 of file m_initial_field_control.f90.
Referenced by set_initial_field_id().
iflag_restart
integer(kind=kint) m_initial_field_control::iflag_restart = i_rst_no_file
flag for the initial field
Definition at line 84 of file m_initial_field_control.f90.
Referenced by set_initial_field_id(), set_initial_sph_dynamo::sph_initial_data_4_benchmarks(), and set_initial_sph_dynamo::sph_initial_data_control().
kinematic
character(len=kchara), parameter, private m_initial_field_control::kinematic = 'kinematic' private
Label for kinematic dynamo.
Definition at line 49 of file m_initial_field_control.f90.
Referenced by set_initial_field_id().
liear_cv
character(len=kchara), parameter, private m_initial_field_control::liear_cv = 'linear_conveciton' private
Label for linear convection model.
Definition at line 51 of file m_initial_field_control.f90.
Referenced by set_initial_field_id().
no_restart
character(len=kchara), parameter, private m_initial_field_control::no_restart = 'no_data' private
Label for starting from zero fields.
Definition at line 23 of file m_initial_field_control.f90.
Referenced by set_initial_field_id().
pseudo_bench
character(len=kchara), parameter, private m_initial_field_control::pseudo_bench = 'pseudo_vacuum_benchmark' private
Label for pseudo vacuume dynamo benchmar.
Definition at line 38 of file m_initial_field_control.f90.
Referenced by set_initial_field_id().
rotate_x
character(len=kchara), parameter, private m_initial_field_control::rotate_x = 'rotate_x' private
Label for solid body rotation around x-axis.
Definition at line 42 of file m_initial_field_control.f90.
Referenced by set_initial_field_id().
rotate_y
character(len=kchara), parameter, private m_initial_field_control::rotate_y = 'rotate_y' private
Label for solid body rotation around y-axis.
Definition at line 44 of file m_initial_field_control.f90.
Referenced by set_initial_field_id().
rotate_z
character(len=kchara), parameter, private m_initial_field_control::rotate_z = 'rotate_z' private
Label for solid body rotation around z-axis.
Definition at line 46 of file m_initial_field_control.f90.
Referenced by set_initial_field_id().