CALYPSO: const_radial_mat_4_sph Module Reference
const_radial_mat_4_sph Module Reference
Construct 1D matrices for MHD dynamo simulaiton.
Functions/Subroutines
subroutine const_radial_mat_sph_mhd (dt, MHD_prop, sph_MHD_bc, sph_rj, r_2nd, leg, sph_MHD_mat)
subroutine const_radial_mat_sph_snap (MHD_prop, sph_MHD_bc, sph_rj, r_2nd, leg, sph_MHD_mat)
subroutine, private const_radial_matrices_sph (dt, sph_rj, r_2nd, MHD_prop, sph_MHD_bc, g_sph_rj, sph_MHD_mat)
subroutine, private const_radial_mat_sph_w_center (dt, sph_rj, MHD_prop, sph_MHD_bc, sph_MHD_mat)
Detailed Description
Construct 1D matrices for MHD dynamo simulaiton.
      subroutine const_radial_mat_sph_mhd(dt, MHD_prop, sph_MHD_bc,   &
     &          sph_rj, r_2nd, leg, sph_MHD_mat)
      subroutine const_radial_mat_sph_snap(MHD_prop, sph_MHD_bc,      &
     &          sph_rj, r_2nd, leg, sph_MHD_mat)
        type(MHD_evolution_param), intent(in) :: MHD_prop
        type(sph_MHD_boundary_data), intent(in) :: sph_MHD_bc
        type(sph_rj_grid), intent(in) :: sph_rj
        type(fdm_matrices), intent(in) :: r_2nd
        type(legendre_4_sph_trans), intent(in) :: leg
        type(MHD_radial_matrices), intent(inout) :: sph_MHD_mat
Function/Subroutine Documentation
const_radial_mat_sph_mhd()
subroutine const_radial_mat_4_sph::const_radial_mat_sph_mhd (real(kind = kreal), intent(in) dt, type(mhd_evolution_param), intent(in) MHD_prop, type(sph_mhd_boundary_data), intent(in) sph_MHD_bc, type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(legendre_4_sph_trans), intent(in) leg, type(mhd_radial_matrices), intent(inout) sph_MHD_mat)
Definition at line 54 of file const_radial_mat_4_sph.f90.
References const_radial_mat_sph_w_center(), and const_radial_matrices_sph().
Referenced by sph_analyzer_mhd::sph_initialize_mhd().
const_radial_mat_sph_snap()
subroutine const_radial_mat_4_sph::const_radial_mat_sph_snap (type(mhd_evolution_param), intent(in) MHD_prop, type(sph_mhd_boundary_data), intent(in) sph_MHD_bc, type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(legendre_4_sph_trans), intent(in) leg, type(mhd_radial_matrices), intent(inout) sph_MHD_mat)
Definition at line 80 of file const_radial_mat_4_sph.f90.
References const_r_mat_4_scalar_sph::const_radial_mat_4_press_sph(), const_r_mat_w_center_sph::const_radial_mat_press00_sph(), t_physical_property::id_crank_nicolson, and m_machine_parameter::iflag_debug.
Referenced by sph_analyzer_d_bench::sph_init_sph_dbench(), and sph_analyzer_snap_w_psf::sph_init_sph_snap_psf().
const_radial_mat_sph_w_center()
subroutine, private const_radial_mat_4_sph::const_radial_mat_sph_w_center (real(kind = kreal), intent(in) dt, type(sph_rj_grid), intent(in) sph_rj, type(mhd_evolution_param), intent(in) MHD_prop, type(sph_mhd_boundary_data), intent(in) sph_MHD_bc, type(mhd_radial_matrices), intent(inout) sph_MHD_mat) private
Definition at line 174 of file const_radial_mat_4_sph.f90.
References t_radial_matrices_sph_mhd::alloc_average_w_center(), const_r_mat_w_center_sph::const_radial_mat_press00_sph(), and const_r_mat_w_center_sph::const_radial_mat_scalar00_sph().
Referenced by const_radial_mat_sph_mhd().
const_radial_matrices_sph()
subroutine, private const_radial_mat_4_sph::const_radial_matrices_sph (real(kind = kreal), intent(in) dt, type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(mhd_evolution_param), intent(in) MHD_prop, type(sph_mhd_boundary_data), intent(in) sph_MHD_bc, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, type(mhd_radial_matrices), intent(inout) sph_MHD_mat) private
Definition at line 119 of file const_radial_mat_4_sph.f90.
References const_r_mat_4_vector_sph::const_radial_mat_4_magne_sph(), const_r_mat_4_scalar_sph::const_radial_mat_4_press_sph(), const_r_mat_4_scalar_sph::const_radial_mat_4_scalar_sph(), const_r_mat_4_vector_sph::const_radial_mat_vort_2step(), t_physical_property::id_crank_nicolson, and m_machine_parameter::iflag_debug.
Referenced by const_radial_mat_sph_mhd().