CALYPSO: gz_data_io Module Reference
gz_data_io Module Reference
Functions/Subroutines
subroutine read_gz_multi_real (num, real_input, zbuf)
subroutine read_gz_integer_stack (num, istack, ntot, zbuf)
subroutine read_gz_multi_int (num, int_input, zbuf)
subroutine read_gz_surf_group (is1, ntot, istack, item_sf, zbuf)
subroutine read_gz_multi_int8 (num, int8_input, zbuf)
subroutine write_gz_surf_group (is1, ntot, istack, item_sf, zbuf)
subroutine write_gz_multi_int_8i16 (num, int_data, zbuf)
subroutine write_gz_multi_int_10i8 (num, int_data, zbuf)
subroutine write_gz_multi_int_10i12 (num, int_data, zbuf)
subroutine write_gz_comment_string (comment, zbuf)
subroutine gz_write_chara_nolf (chara_output, zbuf)
Function/Subroutine Documentation
gz_write_chara_nolf()
subroutine gz_data_io::gz_write_chara_nolf (character(len=kchara), intent(in) chara_output, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 319 of file gz_data_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf().
read_gz_integer_stack()
subroutine gz_data_io::read_gz_integer_stack (integer(kind = kint), intent(in) num, integer(kind = kint), dimension(0:num), intent(inout) istack, integer(kind = kint), intent(inout) ntot, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 76 of file gz_data_IO.f90.
References read_gz_multi_int().
Referenced by gz_domain_data_io::gz_read_export_data(), gz_domain_data_io::gz_read_import_data(), gz_group_data_io::read_group_data_gz(), and gz_group_data_io::read_surface_group_data_gz().
read_gz_multi_int()
subroutine gz_data_io::read_gz_multi_int (integer(kind = kint), intent(in) num, integer(kind = kint), dimension(num), intent(inout) int_input, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 92 of file gz_data_IO.f90.
References gzip_file_access::get_one_line_text_from_gz(), and skip_gz_comment::skip_gz_comment_get_nword().
Referenced by gz_ucd_field_file_io::gz_read_alloc_ucd_2_ld_file(), gz_domain_data_io::gz_read_domain_info(), gz_element_connect_io::gz_read_element_info(), gz_ucd_field_file_io::gz_read_ucd_2_fld_file(), gz_field_file_io::read_alloc_gz_field_file(), gz_field_file_io::read_alloc_gz_step_field_file(), gz_field_file_io::read_alloc_gz_step_field_head(), gz_group_data_io::read_group_data_gz(), read_gz_integer_stack(), and gz_field_file_io::read_gz_step_field_file().
read_gz_multi_int8()
subroutine gz_data_io::read_gz_multi_int8 (integer(kind = kint), intent(in) num, integer(kind = kint_gl), dimension(num), intent(inout) int8_input, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 161 of file gz_data_IO.f90.
References gzip_file_access::get_one_line_text_from_gz(), and skip_gz_comment::skip_gz_comment_get_nword().
read_gz_multi_real()
subroutine gz_data_io::read_gz_multi_real (integer(kind = kint), intent(in) num, real(kind = kreal), dimension(num), intent(inout) real_input, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 43 of file gz_data_IO.f90.
References gzip_file_access::get_one_line_text_from_gz(), and skip_gz_comment::skip_gz_comment_get_nword().
read_gz_surf_group()
subroutine gz_data_io::read_gz_surf_group (integer(kind = kint), intent(in) is1, integer(kind = kint), intent(in) ntot, integer(kind = kint), dimension(0:1), intent(in) istack, integer(kind = kint), dimension(2,ntot), intent(inout) item_sf, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 125 of file gz_data_IO.f90.
References gzip_file_access::get_one_line_text_from_gz(), and skip_gz_comment::skip_gz_comment_get_nword().
Referenced by gz_group_data_io::read_surface_group_data_gz().
write_gz_comment_string()
subroutine gz_data_io::write_gz_comment_string (character(len=*), intent(in) comment, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 304 of file gz_data_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf().
write_gz_multi_int_10i12()
subroutine gz_data_io::write_gz_multi_int_10i12 (integer(kind = kint), intent(in) num, integer(kind = kint), dimension(num), intent(in) int_data, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 277 of file gz_data_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf(), m_constants::inine, and m_constants::ione.
write_gz_multi_int_10i8()
subroutine gz_data_io::write_gz_multi_int_10i8 (integer(kind = kint), intent(in) num, integer(kind = kint), dimension(num), intent(in) int_data, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 250 of file gz_data_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf(), m_constants::inine, and m_constants::ione.
Referenced by gz_element_connect_io::gz_write_element_info().
write_gz_multi_int_8i16()
subroutine gz_data_io::write_gz_multi_int_8i16 (integer(kind = kint), intent(in) num, integer(kind = kint), dimension(num), intent(in) int_data, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 223 of file gz_data_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf(), m_constants::ione, and m_constants::iseven.
Referenced by gz_domain_data_io::gz_write_domain_info(), gz_group_data_io::write_group_data_gz(), gz_domain_data_io::write_send_recv_data_gz(), and gz_group_data_io::write_surf_group_data_gz().
write_gz_surf_group()
subroutine gz_data_io::write_gz_surf_group (integer(kind = kint), intent(in) is1, integer(kind = kint), intent(in) ntot, integer(kind = kint), dimension(0:1), intent(in) istack, integer(kind = kint), dimension(2,ntot), intent(in) item_sf, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 195 of file gz_data_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf(), m_constants::ione, and m_constants::iseven.
Referenced by gz_group_data_io::write_surf_group_data_gz().