CALYPSO: cal_energy_flux_rj Module Reference
cal_energy_flux_rj Module Reference
Evaluate energy fluxes for MHD dynamo in physical space.
Functions/Subroutines
subroutine s_cal_energy_flux_rj (ltr_crust, sph_rj, r_2nd, sph_MHD_bc, ipol, rj_fld)
subroutine, private truncate_magnetic_field_4_view (ltr_crust, sph_rj, rj_fld, i_magne, i_truncated_B)
subroutine, private copy_poloidal_to_streamfunc_rj (sph_rj, rj_fld, is_fld, is_stream)
Detailed Description
Evaluate energy fluxes for MHD dynamo in physical space.
      subroutine s_cal_energy_flux_rj                                 &
     &         (ltr_crust, sph_rj, r_2nd, sph_MHD_bc, ipol, rj_fld)
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(fdm_matrices), intent(in) :: r_2nd
        type(sph_MHD_boundary_data), intent(in) :: sph_MHD_bc
        type(phys_address), intent(in) :: ipol
        type(phys_data), intent(inout) :: rj_fld
Function/Subroutine Documentation
copy_poloidal_to_streamfunc_rj()
subroutine, private cal_energy_flux_rj::copy_poloidal_to_streamfunc_rj (type(sph_rj_grid), intent(in) sph_rj, type(phys_data), intent(inout) rj_fld, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_stream) private
Definition at line 117 of file cal_energy_flux_rj.f90.
References m_constants::zero.
Referenced by s_cal_energy_flux_rj().
s_cal_energy_flux_rj()
subroutine cal_energy_flux_rj::s_cal_energy_flux_rj (integer(kind = kint), intent(in) ltr_crust, type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_mhd_boundary_data), intent(in) sph_MHD_bc, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld)
Definition at line 42 of file cal_energy_flux_rj.f90.
References copy_nodal_fields::add_2_nod_vectors(), const_sph_radial_grad::const_grad_poloidal_moment(), copy_poloidal_to_streamfunc_rj(), and truncate_magnetic_field_4_view().
Referenced by lead_fields_4_sph_mhd::cal_sph_enegy_fluxes().
truncate_magnetic_field_4_view()
subroutine, private cal_energy_flux_rj::truncate_magnetic_field_4_view (integer(kind = kint), intent(in) ltr_crust, type(sph_rj_grid), intent(in) sph_rj, type(phys_data), intent(inout) rj_fld, integer(kind = kint), intent(in) i_magne, integer(kind = kint), intent(in) i_truncated_B) private
Definition at line 85 of file cal_energy_flux_rj.f90.
References m_constants::zero.
Referenced by s_cal_energy_flux_rj().