CALYPSO: pickup_sph_spectr_data Module Reference
pickup_sph_spectr_data Module Reference
Data arrays to monitoring spectrum data.
Functions/Subroutines
subroutine init_sph_spec_4_monitor (sph_params, sph_rj, rj_fld, pick_list, picked)
subroutine pick_degre0_sped_4_monitor (rj_fld, picked, ntot_comp_rj, d_rj_out)
subroutine pick_single_sph_spec_4_monitor (inum, knum, sph_rj, rj_fld, picked, ntot_comp_rj, d_rj_out)
subroutine, private copy_rj_spectrum_4_monitor (inod, n_point, num_phys_rj, ntot_phys_rj, istack_phys_comp_rj, d_rj, nfld_monitor, istack_comp_monitor, ifld_monitor, ntot_comp_monitor, prod_degree_zero, d_rj_out)
Detailed Description
Data arrays to monitoring spectrum data.
      subroutine init_sph_spec_4_monitor(sph_params, sph_rj, rj_fld,  &
     &          pick_list, picked)
        type(sph_shell_parameters), intent(in) :: sph_params
        type(sph_rj_grid), intent(in) :: sph_rj
        type(pickup_mode_list), intent(inout) :: pick_list
        type(picked_spectrum_data), intent(inout) :: picked
      subroutine pick_degre0_sped_4_monitor                           &
     &         (rj_fld, picked, ntot_comp_rj, d_rj_out)
      subroutine pick_single_sph_spec_4_monitor(inum, knum,           &
     &          sph_rj, rj_fld, picked, ntot_comp_rj, d_rj_out)
        type(sph_rj_grid), intent(in) :: sph_rj
        type(phys_data), intent(in) :: rj_fld
        type(picked_spectrum_data), intent(in) :: picked
Parameters
my_rank Process ID
i_step time step
time time
id_pick file ID
ierr Error flag (0:success, 1:error)
Function/Subroutine Documentation
copy_rj_spectrum_4_monitor()
subroutine, private pickup_sph_spectr_data::copy_rj_spectrum_4_monitor (integer(kind = kint), intent(in) inod, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) num_phys_rj, integer(kind = kint), intent(in) ntot_phys_rj, integer(kind = kint), dimension(0:num_phys_rj), intent(in) istack_phys_comp_rj, real(kind=kreal), dimension(n_point,ntot_phys_rj), intent(in) d_rj, integer(kind = kint), intent(in) nfld_monitor, integer(kind = kint), dimension(0:nfld_monitor), intent(in) istack_comp_monitor, integer(kind = kint), dimension(nfld_monitor), intent(in) ifld_monitor, integer(kind = kint), intent(in) ntot_comp_monitor, real(kind=kreal), intent(in) prod_degree_zero, real(kind=kreal), dimension(ntot_comp_monitor), intent(inout) d_rj_out) private
Definition at line 157 of file pickup_sph_spectr_data.f90.
Referenced by pick_degre0_sped_4_monitor(), and pick_single_sph_spec_4_monitor().
init_sph_spec_4_monitor()
subroutine pickup_sph_spectr_data::init_sph_spec_4_monitor (type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(phys_data), intent(in) rj_fld, type(pickup_mode_list), intent(inout) pick_list, type(picked_spectrum_data), intent(inout) picked)
Definition at line 49 of file pickup_sph_spectr_data.f90.
References t_pickup_sph_spectr_data::alloc_pick_sph_l(), pickup_sph_coefs::count_sph_labels_4_monitor(), pickup_sph_coefs::init_sph_radial_monitor_list(), calypso_mpi::my_rank, pickup_sph_coefs::set_sph_fld_id_4_monitor(), and pickup_sph_coefs::set_sph_labels_4_monitor().
Referenced by t_sph_mhd_monitor_data_io::open_sph_vol_rms_file_mhd().
pick_degre0_sped_4_monitor()
subroutine pickup_sph_spectr_data::pick_degre0_sped_4_monitor (type(phys_data), intent(in) rj_fld, type(picked_spectrum_data), intent(in) picked, integer(kind = kint), intent(in) ntot_comp_rj, real(kind=kreal), dimension(ntot_comp_rj), intent(inout) d_rj_out)
Definition at line 102 of file pickup_sph_spectr_data.f90.
References copy_rj_spectrum_4_monitor(), and m_constants::half.
Referenced by mpi_picked_sph_spectr_io::write_picked_specr_data_mpi().
pick_single_sph_spec_4_monitor()
subroutine pickup_sph_spectr_data::pick_single_sph_spec_4_monitor (integer(kind = kint), intent(in) inum, integer(kind = kint), intent(in) knum, type(sph_rj_grid), intent(in) sph_rj, type(phys_data), intent(in) rj_fld, type(picked_spectrum_data), intent(in) picked, integer(kind = kint), intent(in) ntot_comp_rj, real(kind=kreal), dimension(ntot_comp_rj), intent(inout) d_rj_out)
Definition at line 122 of file pickup_sph_spectr_data.f90.
References copy_rj_spectrum_4_monitor().
Referenced by mpi_picked_sph_spectr_io::write_picked_specr_data_mpi().