CALYPSO: t_control_data_4_psf_def Module Reference
t_control_data_4_psf_def Module Reference
control ID data for surfacing module
Data Types
type psf_define_ctl
Structure of cross section definition.
Functions/Subroutines
subroutine init_psf_def_ctl_stract (psf_def_c)
subroutine dealloc_cont_dat_4_psf_def (psf_def_c)
subroutine dup_control_4_psf_def (org_psf_def_c, new_psf_def_c)
subroutine read_section_def_control (id_control, hd_block, psf_def_c, c_buf)
subroutine bcast_section_def_control (psf_def_c)
integer(kind=kint) function num_label_psf_define_control ()
subroutine set_label_psf_define_control (names)
Variables
character(len=kchara), parameter, private hd_section_method = 'section_method'
character(len=kchara), parameter, private hd_coefs_ctl = 'coefs_ctl'
character(len=kchara), parameter, private hd_normal_ctl = 'normal_vector'
character(len=kchara), parameter, private hd_axis_ctl = 'axial_length'
character(len=kchara), parameter, private hd_center_ctl = 'center_position'
character(len=kchara), parameter, private hd_radius = 'radius'
character(len=kchara), parameter, private hd_group_name = 'group_name'
character(len=kchara), parameter, private hd_psf_area = 'section_area_ctl'
integer(kind=kint), parameter, private n_label_psf_define_ctl = 8
Detailed Description
control ID data for surfacing module
      subroutine init_psf_def_ctl_stract(psf_def_c)
      subroutine dealloc_cont_dat_4_psf_def(psf_def_c)
        type(psf_define_ctl), intent(inout) :: psf_def_c
      subroutine dup_control_4_psf_def(org_psf_def_c, new_psf_def_c)
        type(psf_define_ctl), intent(in) :: org_psf_def_c
        type(psf_define_ctl), intent(inout) :: new_psf_def_c
      subroutine read_section_def_control                             &
     &         (id_control, hd_block, psf_def_c, psf_def_c)
      subroutine bcast_section_def_control(psf_def_c)
        type(psf_define_ctl), intent(inout) :: psf_def_c
      integer(kind = kint) function num_label_psf_define_control()
      subroutine set_label_psf_define_control(names)
 example of control for Kemo's surface rendering
    begin surface_define
      section_method    equation
      array coefs_ctl  10
        coefs_ctl  x2     1.0
        coefs_ctl  y2     1.0
        coefs_ctl  z2     0.0
        coefs_ctl  xy     0.0
        coefs_ctl  yz     0.0
        coefs_ctl  zx     0.0
        coefs_ctl  x      0.0
        coefs_ctl  y      0.0
        coefs_ctl  z      0.0
        coefs_ctl  const  1.0
      end array coefs_ctl
      array section_area_ctl 1
        section_area_ctl   outer_core   end
      end array section_area_ctl
    end surface_define
      psf_output_type:
           ucd, OpenDX
    num_result_comp: number of fields
    output_field: (Original name: color_comp and color_subcomp)
         field and componenet name for output
           x, y, z, radial, elevation, azimuth, cylinder_r, norm
           vector, sym_tensor, asym_tensor
           spherical_vector, cylindrical_vector
    output_value: (Original name: specified_color)
    section_method: (original: method)
           plane, sphere, ellipsoid, hyperboloid, paraboloid
           equation, group
    normal_vector: normal vector (for plane)
        array normal_vector    3
          normal_vector  x   0.0
          normal_vector  y   0.0
          normal_vector  z   1.0
        end array normal_vector
    center_position: position of center (for sphere and plane)
        array center_position    3
          center_position  x   0.0
          center_position  y   0.0
          center_position  z   0.0
        end array center_position
    radius:  radius of sphere
    axial_length: length of axis
          (for ellipsoid, hyperboloid, paraboloid)
        array axial_length   3
          axial_length  x   1.0
          axial_length  y   0.5
          axial_length  z   0.0
        end array axial_length
    coefficients:  coefficients for equation
        array coefs_ctl  10
          coefs_ctl  x2     1.0
          coefs_ctl  y2     0.5
          coefs_ctl  z2     0.0
          coefs_ctl  xy     1.0
          coefs_ctl  yz     0.5
          coefs_ctl  zx     0.0
          coefs_ctl  x      1.0
          coefs_ctl  y      0.5
          coefs_ctl  z      0.0
          coefs_ctl  const  1.0
        end array coefs_ctl
    group_type:  (Original: defined_style)
           node_group or surface_group
    group_name:  name of group to plot
   field type:
     scalar, vector,     sym_tensor, asym_tensor
     spherical_vector,   spherical_sym_tensor
     cylindrical_vector, cylindrical_sym_tensor
     norm
Function/Subroutine Documentation
bcast_section_def_control()
subroutine t_control_data_4_psf_def::bcast_section_def_control (type(psf_define_ctl), intent(inout) psf_def_c)
Definition at line 310 of file t_control_data_4_psf_def.f90.
References bcast_control_arrays::bcast_ctl_array_c1(), bcast_control_arrays::bcast_ctl_array_cr(), bcast_control_arrays::bcast_ctl_type_c1(), bcast_control_arrays::bcast_ctl_type_r1(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by t_control_data_4_psf::bcast_psf_control_data().
dealloc_cont_dat_4_psf_def()
subroutine t_control_data_4_psf_def::dealloc_cont_dat_4_psf_def (type(psf_define_ctl), intent(inout) psf_def_c)
Definition at line 200 of file t_control_data_4_psf_def.f90.
References t_control_array_charareal::dealloc_control_array_c_r(), and t_control_array_character::dealloc_control_array_chara().
Referenced by t_control_data_4_psf::dealloc_cont_dat_4_psf().
dup_control_4_psf_def()
subroutine t_control_data_4_psf_def::dup_control_4_psf_def (type(psf_define_ctl), intent(in) org_psf_def_c, type(psf_define_ctl), intent(inout) new_psf_def_c)
Definition at line 234 of file t_control_data_4_psf_def.f90.
References t_control_array_character::copy_chara_ctl(), t_control_array_real::copy_real_ctl(), t_control_array_character::dup_control_array_c1(), and t_control_array_charareal::dup_control_array_c_r().
Referenced by t_control_data_4_psf::dup_control_4_psf().
init_psf_def_ctl_stract()
subroutine t_control_data_4_psf_def::init_psf_def_ctl_stract (type(psf_define_ctl), intent(inout) psf_def_c)
Definition at line 189 of file t_control_data_4_psf_def.f90.
Referenced by t_control_data_4_psf::init_psf_ctl_stract().
num_label_psf_define_control()
integer(kind = kint) function t_control_data_4_psf_def::num_label_psf_define_control
Definition at line 338 of file t_control_data_4_psf_def.f90.
References n_label_psf_define_ctl.
read_section_def_control()
subroutine t_control_data_4_psf_def::read_section_def_control (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(psf_define_ctl), intent(inout) psf_def_c, type(buffer_for_control), intent(inout) c_buf)
Definition at line 268 of file t_control_data_4_psf_def.f90.
References t_read_control_elements::check_end_flag(), hd_axis_ctl, hd_center_ctl, hd_coefs_ctl, hd_group_name, hd_normal_ctl, hd_psf_area, hd_radius, hd_section_method, t_read_control_elements::load_one_line_from_control(), t_control_array_character::read_chara_ctl_type(), t_control_array_character::read_control_array_c1(), t_control_array_charareal::read_control_array_c_r(), and t_control_array_real::read_real_ctl_type().
Referenced by t_control_data_4_psf::read_psf_control_data().
set_label_psf_define_control()
subroutine t_control_data_4_psf_def::set_label_psf_define_control (character(len = kchara), dimension(n_label_psf_define_ctl), intent(inout) names)
Definition at line 345 of file t_control_data_4_psf_def.f90.
References hd_axis_ctl, hd_center_ctl, hd_coefs_ctl, hd_group_name, hd_normal_ctl, hd_psf_area, hd_radius, hd_section_method, and t_read_control_elements::set_control_labels().
Variable Documentation
hd_axis_ctl
character(len=kchara), parameter, private t_control_data_4_psf_def::hd_axis_ctl = 'axial_length' private
Definition at line 165 of file t_control_data_4_psf_def.f90.
Referenced by read_section_def_control(), and set_label_psf_define_control().
hd_center_ctl
character(len=kchara), parameter, private t_control_data_4_psf_def::hd_center_ctl = 'center_position' private
Definition at line 167 of file t_control_data_4_psf_def.f90.
Referenced by read_section_def_control(), and set_label_psf_define_control().
hd_coefs_ctl
character(len=kchara), parameter, private t_control_data_4_psf_def::hd_coefs_ctl = 'coefs_ctl' private
Definition at line 161 of file t_control_data_4_psf_def.f90.
Referenced by read_section_def_control(), and set_label_psf_define_control().
hd_group_name
character(len=kchara), parameter, private t_control_data_4_psf_def::hd_group_name = 'group_name' private
Definition at line 171 of file t_control_data_4_psf_def.f90.
Referenced by read_section_def_control(), and set_label_psf_define_control().
hd_normal_ctl
character(len=kchara), parameter, private t_control_data_4_psf_def::hd_normal_ctl = 'normal_vector' private
Definition at line 163 of file t_control_data_4_psf_def.f90.
Referenced by read_section_def_control(), and set_label_psf_define_control().
hd_psf_area
character(len=kchara), parameter, private t_control_data_4_psf_def::hd_psf_area = 'section_area_ctl' private
Definition at line 173 of file t_control_data_4_psf_def.f90.
Referenced by read_section_def_control(), and set_label_psf_define_control().
hd_radius
character(len=kchara), parameter, private t_control_data_4_psf_def::hd_radius = 'radius' private
Definition at line 169 of file t_control_data_4_psf_def.f90.
Referenced by read_section_def_control(), and set_label_psf_define_control().
hd_section_method
character(len=kchara), parameter, private t_control_data_4_psf_def::hd_section_method = 'section_method' private
Definition at line 159 of file t_control_data_4_psf_def.f90.
Referenced by read_section_def_control(), and set_label_psf_define_control().
n_label_psf_define_ctl
integer(kind = kint), parameter, private t_control_data_4_psf_def::n_label_psf_define_ctl = 8 private
Definition at line 176 of file t_control_data_4_psf_def.f90.
Referenced by num_label_psf_define_control().