CALYPSO: sph_modes_grids_data_io Module Reference
sph_modes_grids_data_io Module Reference
Routines for speherical grid data IO.
Functions/Subroutines
subroutine read_geom_rtp_data (id_file, id_rank, comm_IO, sph_IO, sph_grps_IO, ierr)
subroutine read_spectr_modes_rj_data (id_file, id_rank, comm_IO, sph_IO, sph_grps_IO, ierr)
subroutine read_geom_rtm_data (id_file, id_rank, comm_IO, sph_IO, ierr)
subroutine read_spectr_modes_rlm_data (id_file, id_rank, comm_IO, sph_IO, ierr)
subroutine write_geom_rtp_data (id_file, id_rank, comm_IO, sph_IO, sph_grps_IO)
subroutine write_spectr_modes_rj_data (id_file, id_rank, comm_IO, sph_IO, sph_grps_IO)
subroutine write_geom_rtm_data (id_file, id_rank, comm_IO, sph_IO)
subroutine write_modes_rlm_data (id_file, id_rank, comm_IO, sph_IO)
Detailed Description
Routines for speherical grid data IO.
      subroutine read_geom_rtp_data(id_file, id_rank,                 &
     &          comm_IO, sph_IO, sph_grps_IO, ierr)
      subroutine read_spectr_modes_rj_data(id_file, id_rank,          &
     &          comm_IO, sph_IO, sph_grps_IO, ierr)
      subroutine read_geom_rtm_data                                   &
     &         (id_file, id_rank, comm_IO, sph_IO, ierr)
      subroutine read_spectr_modes_rlm_data                           &
     &         (id_file, id_rank, comm_IO, sph_IO, ierr)
        type(communication_table), intent(inout) :: comm_IO
        type(sph_IO_data), intent(inout) :: sph_IO
        type(sph_group_data), intent(inout) :: sph_grps_IO
      subroutine write_geom_rtp_data                                  &
     &         (id_file, id_rank, comm_IO, sph_IO, sph_grps_IO)
      subroutine write_spectr_modes_rj_data                           &
     &         (id_file, id_rank, comm_IO, sph_IO, sph_grps_IO)
      subroutine write_geom_rtm_data                                  &
     &         (id_file, id_rank, comm_IO, sph_IO)
      subroutine write_modes_rlm_data                                 &
     &         (id_file, id_rank, comm_IO, sph_IO)
        type(communication_table), intent(in) :: comm_IO
        type(sph_IO_data), intent(in) :: sph_IO
        type(sph_group_data), intent(in) :: sph_grps_IO
Function/Subroutine Documentation
read_geom_rtm_data()
subroutine sph_modes_grids_data_io::read_geom_rtm_data (integer(kind = kint), intent(in) id_file, integer, intent(in) id_rank, type(communication_table), intent(inout) comm_IO, type(sph_io_data), intent(inout) sph_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 142 of file sph_modes_grids_data_IO.f90.
References domain_data_io::read_domain_info(), spherical_model_io::read_gl_nodes_sph(), spherical_model_io::read_gl_resolution_sph(), domain_data_io::read_import_data(), spherical_model_io::read_rank_4_sph(), and sph_global_1d_idx_io::read_rtp_gl_1d_table().
Referenced by sph_modes_grids_file_io::read_geom_rtm_file().
read_geom_rtp_data()
subroutine sph_modes_grids_data_io::read_geom_rtp_data (integer(kind = kint), intent(in) id_file, integer, intent(in) id_rank, type(communication_table), intent(inout) comm_IO, type(sph_io_data), intent(inout) sph_IO, type(sph_group_data), intent(inout) sph_grps_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 56 of file sph_modes_grids_data_IO.f90.
References domain_data_io::read_domain_info(), spherical_model_io::read_gl_nodes_sph(), spherical_model_io::read_gl_resolution_sph(), groups_io::read_group_data(), domain_data_io::read_import_data(), spherical_model_io::read_rank_4_sph(), and sph_global_1d_idx_io::read_rtp_gl_1d_table().
Referenced by sph_modes_grids_file_io::read_geom_rtp_file().
read_spectr_modes_rj_data()
subroutine sph_modes_grids_data_io::read_spectr_modes_rj_data (integer(kind = kint), intent(in) id_file, integer, intent(in) id_rank, type(communication_table), intent(inout) comm_IO, type(sph_io_data), intent(inout) sph_IO, type(sph_group_data), intent(inout) sph_grps_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 100 of file sph_modes_grids_data_IO.f90.
References domain_data_io::read_domain_info(), spherical_model_io::read_gl_nodes_sph(), spherical_model_io::read_gl_resolution_sph(), groups_io::read_group_data(), domain_data_io::read_import_data(), spherical_model_io::read_rank_4_sph(), and sph_global_1d_idx_io::read_rj_gl_1d_table().
Referenced by sph_modes_grids_file_io::read_spectr_modes_rj_file().
read_spectr_modes_rlm_data()
subroutine sph_modes_grids_data_io::read_spectr_modes_rlm_data (integer(kind = kint), intent(in) id_file, integer, intent(in) id_rank, type(communication_table), intent(inout) comm_IO, type(sph_io_data), intent(inout) sph_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 169 of file sph_modes_grids_data_IO.f90.
References domain_data_io::read_domain_info(), spherical_model_io::read_gl_nodes_sph(), spherical_model_io::read_gl_resolution_sph(), domain_data_io::read_import_data(), spherical_model_io::read_rank_4_sph(), and sph_global_1d_idx_io::read_rj_gl_1d_table().
Referenced by sph_modes_grids_file_io::read_modes_rlm_file().
write_geom_rtm_data()
subroutine sph_modes_grids_data_io::write_geom_rtm_data (integer(kind = kint), intent(in) id_file, integer, intent(in) id_rank, type(communication_table), intent(in) comm_IO, type(sph_io_data), intent(in) sph_IO)
Definition at line 289 of file sph_modes_grids_data_IO.f90.
References m_sph_modes_grid_labels::hd_rtp_comm(), m_sph_modes_grid_labels::hd_rtp_glbl(), m_sph_modes_grid_labels::hd_sph_para(), domain_data_io::write_domain_info(), spherical_model_io::write_gl_nodes_sph(), spherical_model_io::write_gl_resolution_sph(), domain_data_io::write_import_data(), spherical_model_io::write_rank_4_sph(), and sph_global_1d_idx_io::write_rtp_gl_1d_table().
Referenced by sph_modes_grids_file_io::write_geom_rtm_file().
write_geom_rtp_data()
subroutine sph_modes_grids_data_io::write_geom_rtp_data (integer(kind = kint), intent(in) id_file, integer, intent(in) id_rank, type(communication_table), intent(in) comm_IO, type(sph_io_data), intent(in) sph_IO, type(sph_group_data), intent(in) sph_grps_IO)
Definition at line 197 of file sph_modes_grids_data_IO.f90.
References m_sph_modes_grid_labels::hd_grphd(), m_sph_modes_grid_labels::hd_ngrphd(), m_sph_modes_grid_labels::hd_pgrphd(), m_sph_modes_grid_labels::hd_rgrphd(), m_sph_modes_grid_labels::hd_rtp_comm(), m_sph_modes_grid_labels::hd_rtp_glbl(), m_sph_modes_grid_labels::hd_sph_para(), m_sph_modes_grid_labels::hd_tgrphd(), domain_data_io::write_domain_info(), spherical_model_io::write_gl_nodes_sph(), spherical_model_io::write_gl_resolution_sph(), groups_io::write_grp_data(), domain_data_io::write_import_data(), spherical_model_io::write_rank_4_sph(), and sph_global_1d_idx_io::write_rtp_gl_1d_table().
Referenced by sph_modes_grids_file_io::write_geom_rtp_file().
write_modes_rlm_data()
subroutine sph_modes_grids_data_io::write_modes_rlm_data (integer(kind = kint), intent(in) id_file, integer, intent(in) id_rank, type(communication_table), intent(in) comm_IO, type(sph_io_data), intent(in) sph_IO)
Definition at line 319 of file sph_modes_grids_data_IO.f90.
References m_sph_modes_grid_labels::hd_rj_comm(), m_sph_modes_grid_labels::hd_rlm_glbl(), m_sph_modes_grid_labels::hd_sph_para(), domain_data_io::write_domain_info(), spherical_model_io::write_gl_nodes_sph(), spherical_model_io::write_gl_resolution_sph(), domain_data_io::write_import_data(), spherical_model_io::write_rank_4_sph(), and sph_global_1d_idx_io::write_rj_gl_1d_table().
Referenced by sph_modes_grids_file_io::write_modes_rlm_file().
write_spectr_modes_rj_data()
subroutine sph_modes_grids_data_io::write_spectr_modes_rj_data (integer(kind = kint), intent(in) id_file, integer, intent(in) id_rank, type(communication_table), intent(in) comm_IO, type(sph_io_data), intent(in) sph_IO, type(sph_group_data), intent(in) sph_grps_IO)
Definition at line 248 of file sph_modes_grids_data_IO.f90.
References m_sph_modes_grid_labels::hd_grphd(), m_sph_modes_grid_labels::hd_jgrphd(), m_sph_modes_grid_labels::hd_kgrphd(), m_sph_modes_grid_labels::hd_rj_comm(), m_sph_modes_grid_labels::hd_rj_glbl(), m_sph_modes_grid_labels::hd_sph_para(), domain_data_io::write_domain_info(), spherical_model_io::write_gl_nodes_sph(), spherical_model_io::write_gl_resolution_sph(), groups_io::write_grp_data(), domain_data_io::write_import_data(), spherical_model_io::write_rank_4_sph(), and sph_global_1d_idx_io::write_rj_gl_1d_table().
Referenced by sph_modes_grids_file_io::write_spectr_modes_rj_file().