CALYPSO: set_bc_sph_scalars Module Reference
set_bc_sph_scalars Module Reference
Set boundary conditions for scalar fields.
Functions/Subroutines
subroutine check_sph_bc_scalar_sph (sph_rj, sph_bc, ICB_Sspec, CMB_Sspec)
subroutine set_sph_bc_temp_sph (bc_IO, sph_rj, radial_rj_grp, temp_nod, h_flux_surf, sph_bc_T, bcs_T)
subroutine set_sph_bc_composition_sph (bc_IO, sph_rj, radial_rj_grp, light_nod, light_surf, sph_bc_C, bcs_C)
subroutine, private set_sph_bc_scalar_sph (field, flux, bc_IO, sph_rj, radial_rj_grp, nod_bc_list, surf_bc_list, sph_bc, bcs_S)
subroutine, private inner_sph_bc_scalar_sph (field, flux, nod_bc_list, surf_bc_list, bc_IO, igrp_icb, sph_rj, sph_bc, ICB_Sspec, ICB_Sevo)
subroutine, private outer_sph_bc_scalar_sph (field, flux, nod_bc_list, surf_bc_list, bc_IO, igrp_cmb, sph_rj, sph_bc, CMB_Sspec, CMB_Sevo)
subroutine, private set_homogenious_scalar_bc (bc_name, bc_magnitude, jmax, idx_rj_degree_zero, ref_grp, bc_data, iflag_bc_scalar)
subroutine, private set_homogenious_grad_bc (bc_name, bc_magnitude, jmax, idx_rj_degree_zero, ref_grp, iflag_bc_scalar, bc_data)
subroutine find_both_sides_of_boundaries (sph_rj, radial_rj_grp, bc_nod, bc_surf, sph_bc, igrp_icb, igrp_cmb)
Detailed Description
Set boundary conditions for scalar fields.
      subroutine set_sph_bc_temp_sph                                  &
     &         (bc_IO, sph_rj, radial_rj_grp, temp_nod, h_flux_surf,  &
     &          sph_bc_T, bcs_T)
      subroutine set_sph_bc_composition_sph                           &
     &         (bc_IO, sph_rj, radial_rj_grp, light_nod, light_surf,  &
     &          sph_bc_C, bcs_C)
        type(boundary_spectra), intent(in) :: bc_IO
        type(sph_rj_grid), intent(in) :: sph_rj
        type(group_data), intent(in) :: radial_rj_grp
        type(sph_boundary_type), intent(inout) :: sph_bc_T
        type(sph_scalar_boundary_data), intent(inout) :: bcs_T
        type(sph_boundary_type), intent(inout) :: sph_bc_C
        type(sph_scalar_boundary_data), intent(inout) :: bcs_C
      subroutine find_both_sides_of_boundaries(sph_rj, radial_rj_grp, &
     &         bc_nod, bc_surf, sph_bc, igrp_icb, igrp_cmb)
        type(sph_rj_grid), intent(in) :: sph_rj
        type(group_data), intent(in) :: radial_rj_grp
        type(boundary_condition_list), intent(in) :: bc_nod
        type(boundary_condition_list), intent(in) :: bc_surf
        type(sph_boundary_type), intent(inout) :: sph_bc
Function/Subroutine Documentation
check_sph_bc_scalar_sph()
subroutine set_bc_sph_scalars::check_sph_bc_scalar_sph (type(sph_rj_grid), intent(in) sph_rj, type(sph_boundary_type), intent(in) sph_bc, type(sph_scalar_bc_coef), intent(in) ICB_Sspec, type(sph_scalar_bc_coef), intent(in) CMB_Sspec)
Definition at line 63 of file set_bc_sph_scalars.f90.
References m_machine_parameter::i_debug.
Referenced by set_sph_bc_composition_sph(), and set_sph_bc_temp_sph().
find_both_sides_of_boundaries()
subroutine set_bc_sph_scalars::find_both_sides_of_boundaries (type(sph_rj_grid), intent(in) sph_rj, type(group_data), intent(in) radial_rj_grp, type(boundary_condition_list), intent(in) bc_nod, type(boundary_condition_list), intent(in) bc_surf, type(sph_boundary_type), intent(inout) sph_bc, integer(kind = kint), intent(inout) igrp_icb, integer(kind = kint), intent(inout) igrp_cmb)
Definition at line 434 of file set_bc_sph_scalars.f90.
References calypso_mpi::calypso_mpi_abort(), and m_error_ids::ierr_bc.
Referenced by set_bc_sph_mhd::set_sph_bc_magne_sph(), set_sph_bc_scalar_sph(), and set_bc_flag_sph_velo::set_sph_bc_velo_sph().
inner_sph_bc_scalar_sph()
subroutine, private set_bc_sph_scalars::inner_sph_bc_scalar_sph (type(field_def), intent(in) field, type(field_def), intent(in) flux, type(boundary_condition_list), intent(in) nod_bc_list, type(boundary_condition_list), intent(in) surf_bc_list, type(boundary_spectra), intent(in) bc_IO, integer(kind = kint), intent(in) igrp_icb, type(sph_rj_grid), intent(in) sph_rj, type(sph_boundary_type), intent(inout) sph_bc, type(sph_scalar_bc_coef), intent(inout) ICB_Sspec, type(sph_scalar_bc_evo), intent(inout) ICB_Sevo) private
Definition at line 228 of file set_bc_sph_scalars.f90.
References m_boundary_condition_ids::iflag_bc_evo_field, m_boundary_condition_ids::iflag_bc_evo_flux, m_boundary_condition_ids::iflag_bc_file_flux, m_boundary_condition_ids::iflag_bc_file_s, m_boundary_condition_ids::iflag_bc_fix_flux, m_boundary_condition_ids::iflag_bc_fix_s, t_boundary_params_sph_mhd::iflag_fixed_flux, m_boundary_condition_ids::iflag_sph_2_center, m_boundary_condition_ids::iflag_sph_clip_center, t_boundary_params_sph_mhd::iflag_sph_fill_center, t_boundary_params_sph_mhd::iflag_sph_fix_center, set_sph_bc_data_by_file::set_evolved_grad_bc_by_file(), set_sph_bc_data_by_file::set_evolved_scalar_bc_by_file(), set_sph_bc_data_by_file::set_fixed_grad_bc_by_file(), set_sph_bc_data_by_file::set_fixed_scalar_bc_by_file(), set_homogenious_grad_bc(), and set_homogenious_scalar_bc().
Referenced by set_sph_bc_scalar_sph().
outer_sph_bc_scalar_sph()
subroutine, private set_bc_sph_scalars::outer_sph_bc_scalar_sph (type(field_def), intent(in) field, type(field_def), intent(in) flux, type(boundary_condition_list), intent(in) nod_bc_list, type(boundary_condition_list), intent(in) surf_bc_list, type(boundary_spectra), intent(in) bc_IO, integer(kind = kint), intent(in) igrp_cmb, type(sph_rj_grid), intent(in) sph_rj, type(sph_boundary_type), intent(inout) sph_bc, type(sph_scalar_bc_coef), intent(inout) CMB_Sspec, type(sph_scalar_bc_evo), intent(inout) CMB_Sevo) private
Definition at line 317 of file set_bc_sph_scalars.f90.
References m_boundary_condition_ids::iflag_bc_evo_field, m_boundary_condition_ids::iflag_bc_evo_flux, m_boundary_condition_ids::iflag_bc_file_flux, m_boundary_condition_ids::iflag_bc_file_s, m_boundary_condition_ids::iflag_bc_fix_flux, m_boundary_condition_ids::iflag_bc_fix_s, set_sph_bc_data_by_file::set_evolved_grad_bc_by_file(), set_sph_bc_data_by_file::set_evolved_scalar_bc_by_file(), set_sph_bc_data_by_file::set_fixed_grad_bc_by_file(), set_sph_bc_data_by_file::set_fixed_scalar_bc_by_file(), set_homogenious_grad_bc(), and set_homogenious_scalar_bc().
Referenced by set_sph_bc_scalar_sph().
set_homogenious_grad_bc()
subroutine, private set_bc_sph_scalars::set_homogenious_grad_bc (character(len=kchara), intent(in) bc_name, real(kind = kreal), intent(in) bc_magnitude, integer(kind = kint), intent(in) jmax, integer(kind = kint), intent(in) idx_rj_degree_zero, character(len=kchara), intent(in) ref_grp, integer(kind = kint), intent(inout) iflag_bc_scalar, real(kind = kreal), dimension(jmax), intent(inout) bc_data) private
Definition at line 409 of file set_bc_sph_scalars.f90.
References t_boundary_params_sph_mhd::iflag_fixed_flux.
Referenced by inner_sph_bc_scalar_sph(), and outer_sph_bc_scalar_sph().
set_homogenious_scalar_bc()
subroutine, private set_bc_sph_scalars::set_homogenious_scalar_bc (character(len=kchara), intent(in) bc_name, real(kind = kreal), intent(in) bc_magnitude, integer(kind = kint), intent(in) jmax, integer(kind = kint), intent(in) idx_rj_degree_zero, character(len=kchara), intent(in) ref_grp, real(kind = kreal), dimension(jmax), intent(inout) bc_data, integer(kind = kint), intent(inout) iflag_bc_scalar) private
Definition at line 385 of file set_bc_sph_scalars.f90.
References t_boundary_params_sph_mhd::iflag_fixed_field.
Referenced by inner_sph_bc_scalar_sph(), and outer_sph_bc_scalar_sph().
set_sph_bc_composition_sph()
subroutine set_bc_sph_scalars::set_sph_bc_composition_sph (type(boundary_spectra), intent(in) bc_IO, type(sph_rj_grid), intent(in) sph_rj, type(group_data), intent(in) radial_rj_grp, type(boundary_condition_list), intent(in) light_nod, type(boundary_condition_list), intent(in) light_surf, type(sph_boundary_type), intent(inout) sph_bc_C, type(sph_scalar_boundary_data), intent(inout) bcs_C)
Definition at line 141 of file set_bc_sph_scalars.f90.
References calypso_mpi::calypso_mpi_abort(), check_sph_bc_scalar_sph(), m_base_force_labels::composite_flux, m_base_field_labels::composition, m_machine_parameter::i_debug, m_error_ids::ierr_bc, t_boundary_params_sph_mhd::iflag_undefined_bc, calypso_mpi::my_rank, and set_sph_bc_scalar_sph().
Referenced by set_bc_sph_mhd::s_set_bc_sph_mhd().
set_sph_bc_scalar_sph()
subroutine, private set_bc_sph_scalars::set_sph_bc_scalar_sph (type(field_def), intent(in) field, type(field_def), intent(in) flux, type(boundary_spectra), intent(in) bc_IO, type(sph_rj_grid), intent(in) sph_rj, type(group_data), intent(in) radial_rj_grp, type(boundary_condition_list), intent(in) nod_bc_list, type(boundary_condition_list), intent(in) surf_bc_list, type(sph_boundary_type), intent(inout) sph_bc, type(sph_scalar_boundary_data), intent(inout) bcs_S) private
Definition at line 192 of file set_bc_sph_scalars.f90.
References t_boundary_sph_spectr::alloc_sph_scalar_bcs_data(), find_both_sides_of_boundaries(), inner_sph_bc_scalar_sph(), and outer_sph_bc_scalar_sph().
Referenced by set_sph_bc_composition_sph(), and set_sph_bc_temp_sph().
set_sph_bc_temp_sph()
subroutine set_bc_sph_scalars::set_sph_bc_temp_sph (type(boundary_spectra), intent(in) bc_IO, type(sph_rj_grid), intent(in) sph_rj, type(group_data), intent(in) radial_rj_grp, type(boundary_condition_list), intent(in) temp_nod, type(boundary_condition_list), intent(in) h_flux_surf, type(sph_boundary_type), intent(inout) sph_bc_T, type(sph_scalar_boundary_data), intent(inout) bcs_T)
Definition at line 92 of file set_bc_sph_scalars.f90.
References calypso_mpi::calypso_mpi_abort(), check_sph_bc_scalar_sph(), m_base_force_labels::heat_flux, m_machine_parameter::i_debug, m_error_ids::ierr_bc, t_boundary_params_sph_mhd::iflag_undefined_bc, calypso_mpi::my_rank, set_sph_bc_scalar_sph(), and m_base_field_labels::temperature.
Referenced by set_bc_sph_mhd::s_set_bc_sph_mhd().