CALYPSO: t_sph_local_parameter Module Reference
t_sph_local_parameter Module Reference
Data Types
type sph_local_1d_param
type sph_local_default_bc
type sph_local_parameters
Functions/Subroutines
subroutine alloc_sph_gl_parameter (s3d_ranks, sph_lcp)
subroutine alloc_nidx_local (s3d_ranks, sph_lc1)
subroutine alloc_sph_gl_bc_param (s3d_ranks, sph_dbc)
subroutine dealloc_sph_gl_parameter (sph_lcp)
subroutine dealloc_nidx_local (sph_lc1)
subroutine dealloc_sph_gl_bc_param (sph_dbc)
subroutine check_spheric_global_param (id_rank, s3d_ranks, sph_lcp)
subroutine check_nidx_local (ip_rank, sph_lc1)
subroutine check_sph_gl_bc_param (id_rank, sph_dbc)
Function/Subroutine Documentation
alloc_nidx_local()
subroutine t_sph_local_parameter::alloc_nidx_local (type(spheric_global_rank), intent(in) s3d_ranks, type(sph_local_1d_param), intent(inout) sph_lc1)
Definition at line 113 of file t_sph_local_parameter.f90.
Referenced by const_fem_mesh_sph_mhd::const_global_rtp_mesh(), const_global_sph_grids_modes::const_global_sph_fem_grid(), and const_global_sph_grids_modes::s_const_global_sph_grids_modes().
alloc_sph_gl_bc_param()
subroutine t_sph_local_parameter::alloc_sph_gl_bc_param (type(spheric_global_rank), intent(in) s3d_ranks, type(sph_local_default_bc), intent(inout) sph_dbc)
Definition at line 160 of file t_sph_local_parameter.f90.
Referenced by const_fem_mesh_sph_mhd::const_global_rtp_mesh(), const_global_sph_grids_modes::const_global_sph_fem_grid(), and const_global_sph_grids_modes::s_const_global_sph_grids_modes().
alloc_sph_gl_parameter()
subroutine t_sph_local_parameter::alloc_sph_gl_parameter (type(spheric_global_rank), intent(in) s3d_ranks, type(sph_local_parameters), intent(inout) sph_lcp)
Definition at line 83 of file t_sph_local_parameter.f90.
Referenced by const_fem_mesh_sph_mhd::const_global_rtp_mesh(), const_global_sph_grids_modes::const_global_sph_fem_grid(), and const_global_sph_grids_modes::s_const_global_sph_grids_modes().
check_nidx_local()
subroutine t_sph_local_parameter::check_nidx_local (integer(kind = kint), intent(in) ip_rank, type(sph_local_1d_param), intent(inout) sph_lc1)
Definition at line 306 of file t_sph_local_parameter.f90.
check_sph_gl_bc_param()
subroutine t_sph_local_parameter::check_sph_gl_bc_param (integer, intent(in) id_rank, type(sph_local_default_bc), intent(in) sph_dbc)
Definition at line 330 of file t_sph_local_parameter.f90.
check_spheric_global_param()
subroutine t_sph_local_parameter::check_spheric_global_param (integer, intent(in) id_rank, type(spheric_global_rank), intent(in) s3d_ranks, type(sph_local_parameters), intent(in) sph_lcp)
Definition at line 258 of file t_sph_local_parameter.f90.
dealloc_nidx_local()
subroutine t_sph_local_parameter::dealloc_nidx_local (type(sph_local_1d_param), intent(inout) sph_lc1)
Definition at line 218 of file t_sph_local_parameter.f90.
Referenced by const_fem_mesh_sph_mhd::const_global_rtp_mesh(), const_global_sph_grids_modes::const_global_sph_fem_grid(), and const_global_sph_grids_modes::s_const_global_sph_grids_modes().
dealloc_sph_gl_bc_param()
subroutine t_sph_local_parameter::dealloc_sph_gl_bc_param (type(sph_local_default_bc), intent(inout) sph_dbc)
Definition at line 234 of file t_sph_local_parameter.f90.
Referenced by const_fem_mesh_sph_mhd::const_global_rtp_mesh(), const_global_sph_grids_modes::const_global_sph_fem_grid(), and const_global_sph_grids_modes::s_const_global_sph_grids_modes().
dealloc_sph_gl_parameter()
subroutine t_sph_local_parameter::dealloc_sph_gl_parameter (type(sph_local_parameters), intent(inout) sph_lcp)
Definition at line 203 of file t_sph_local_parameter.f90.
Referenced by t_const_spherical_grid::dealloc_gen_mesh_params().