CALYPSO: gz_ucd_file_mpi_io Module Reference
gz_ucd_file_mpi_io Module Reference
Output merged VTK file usgin MPI-IO.
Functions/Subroutines
subroutine gz_write_ucd_data_mpi_b (IO_param, nnod, num_field, ntot_comp, ncomp_field, field_name, d_nod, istack_merged_intnod)
subroutine gz_mpi_write_ucd_mesh_data_b (IO_param, nnod, nele, nnod_ele, xx, ie, istack_merged_intnod)
subroutine gz_write_ucd_data_mpi (id_vtk, ioff_gl, nnod, num_field, ntot_comp, ncomp_field, field_name, d_nod, istack_merged_intnod)
subroutine gz_write_ucd_mesh_mpi (id_vtk, ioff_gl, nnod, nele, nnod_ele, ntot_comp, xx, ie, istack_merged_intnod, istack_merged_ele)
subroutine, private gz_write_ucd_vecotr_mpi (id_vtk, ioff_gl, nnod, ntot_comp, vect, istack_merged_intnod)
Variables
character(len=1), dimension(:), allocatable gzip_buf
Detailed Description
Output merged VTK file usgin MPI-IO.
      subroutine gz_write_ucd_data_mpi_b(IO_param,                    &
     &          nnod, num_field, ntot_comp, ncomp_field,              &
     &          field_name, d_nod, istack_merged_intnod)
      subroutine gz_mpi_write_ucd_mesh_data_b                         &
     &         (IO_param, nnod, nele, nnod_ele, xx, ie,               &
     &          istack_merged_intnod)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
      subroutine gz_write_ucd_data_mpi(id_vtk, ioff_gl,               &
     &          nnod, num_field, ntot_comp, ncomp_field,              &
     &          field_name, d_nod, istack_merged_intnod)
      subroutine gz_write_ucd_mesh_mpi(id_vtk, ioff_gl,               &
     &          nnod, nele, nnod_ele, ntot_comp, xx, ie,              &
     &          istack_merged_intnod, istack_merged_ele)
Function/Subroutine Documentation
gz_mpi_write_ucd_mesh_data_b()
subroutine gz_ucd_file_mpi_io::gz_mpi_write_ucd_mesh_data_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint_gl), intent(in) nnod, integer(kind = kint_gl), intent(in) nele, integer(kind = kint), intent(in) nnod_ele, real(kind = kreal), dimension(nnod,3), intent(in) xx, integer(kind = kint_gl), dimension(nele,nnod_ele), intent(in) ie, integer(kind = kint_gl), dimension(0:nprocs), intent(in) istack_merged_intnod)
Definition at line 92 of file gz_ucd_file_MPI_IO.f90.
References gz_mpi_binary_datum_io::gz_mpi_write_one_inthead_b(), gz_mpi_binary_datum_io::gz_mpi_write_process_id_b(), set_nnod_4_ele_by_type::linear_eletype_from_num(), and calypso_mpi::my_rank.
Referenced by gz_write_udt_file_io_b::gz_write_ucd_file_mpi_b(), and gz_write_udt_file_io_b::gz_write_ucd_grid_mpi_b().
gz_write_ucd_data_mpi()
subroutine gz_ucd_file_mpi_io::gz_write_ucd_data_mpi (integer, intent(in) id_vtk, integer(kind = kint_gl), intent(inout) ioff_gl, integer(kind=kint_gl), intent(in) nnod, integer(kind=kint), intent(in) num_field, integer(kind=kint), intent(in) ntot_comp, integer(kind=kint), dimension(num_field), intent(in) ncomp_field, character(len=kchara), dimension(num_field), intent(in) field_name, real(kind = kreal), dimension(nnod,ntot_comp), intent(in) d_nod, integer(kind = kint_gl), dimension(0:nprocs), intent(in) istack_merged_intnod)
Definition at line 143 of file gz_ucd_file_MPI_IO.f90.
References gz_write_ucd_vecotr_mpi(), gz_vtk_file_mpi_io::gz_write_vtk_header_mpi(), ucd_data_to_buffer::ucd_field_name(), and ucd_data_to_buffer::ucd_num_comps().
Referenced by gz_merged_udt_vtk_file_io::gz_write_ucd_file_mpi(), and gz_merged_udt_vtk_file_io::gz_write_ucd_phys_mpi().
gz_write_ucd_data_mpi_b()
subroutine gz_ucd_file_mpi_io::gz_write_ucd_data_mpi_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint_gl), intent(in) nnod, integer(kind=kint), intent(in) num_field, integer(kind=kint), intent(in) ntot_comp, integer(kind=kint), dimension(num_field), intent(in) ncomp_field, character(len=kchara), dimension(num_field), intent(in) field_name, real(kind = kreal), dimension(nnod,ntot_comp), intent(in) d_nod, integer(kind = kint_gl), dimension(0:nprocs), intent(in) istack_merged_intnod)
Definition at line 49 of file gz_ucd_file_MPI_IO.f90.
References gz_mpi_binary_head_io::gz_mpi_write_mul_charahead_b(), gz_mpi_binary_head_io::gz_mpi_write_mul_inthead_b(), gz_mpi_binary_datum_io::gz_mpi_write_one_inthead_b(), gz_field_file_mpi_io_b::io_param, and calypso_mpi::my_rank.
Referenced by gz_write_udt_file_io_b::gz_write_ucd_file_mpi_b(), and gz_write_udt_file_io_b::gz_write_ucd_phys_mpi_b().
gz_write_ucd_mesh_mpi()
subroutine gz_ucd_file_mpi_io::gz_write_ucd_mesh_mpi (integer, intent(in) id_vtk, integer(kind = kint_gl), intent(inout) ioff_gl, integer(kind = kint_gl), intent(in) nnod, integer(kind = kint_gl), intent(in) nele, integer(kind = kint), intent(in) nnod_ele, integer(kind = kint), intent(in) ntot_comp, real(kind = kreal), dimension(nnod,3), intent(in) xx, integer(kind = kint_gl), dimension(nele,nnod_ele), intent(in) ie, integer(kind = kint_gl), dimension(0:nprocs), intent(in) istack_merged_intnod, integer(kind = kint_gl), dimension(0:nprocs), intent(in) istack_merged_ele)
Definition at line 178 of file gz_ucd_file_MPI_IO.f90.
References m_calypso_mpi_io::calypso_gz_mpi_seek_write(), t_buffer_4_gzip::dealloc_zip_buffer(), zlib_cvt_ucd_data::defleate_ucd_connect(), gz_write_ucd_vecotr_mpi(), gz_vtk_file_mpi_io::gz_write_vtk_header_mpi(), calypso_mpi::my_rank, m_phys_constants::n_vector, calypso_mpi::nprocs, and ucd_data_to_buffer::ucd_connect_head().
Referenced by gz_merged_udt_vtk_file_io::gz_write_ucd_file_mpi(), and gz_merged_udt_vtk_file_io::gz_write_ucd_grid_mpi().
gz_write_ucd_vecotr_mpi()
subroutine, private gz_ucd_file_mpi_io::gz_write_ucd_vecotr_mpi (integer, intent(in) id_vtk, integer(kind = kint_gl), intent(inout) ioff_gl, integer(kind = kint_gl), intent(in) nnod, integer(kind=kint), intent(in) ntot_comp, real(kind = kreal), dimension(nnod,ntot_comp), intent(in) vect, integer(kind = kint_gl), dimension(0:nprocs), intent(in) istack_merged_intnod) private
Definition at line 221 of file gz_ucd_file_MPI_IO.f90.
References m_calypso_mpi_io::calypso_gz_mpi_seek_write(), t_buffer_4_gzip::dealloc_zip_buffer(), zlib_cvt_ucd_data::defleate_ucd_vector(), and calypso_mpi::my_rank.
Referenced by gz_write_ucd_data_mpi(), and gz_write_ucd_mesh_mpi().
Variable Documentation
gzip_buf
character(len=1), dimension(:), allocatable gz_ucd_file_mpi_io::gzip_buf
Definition at line 39 of file gz_ucd_file_MPI_IO.f90.