CALYPSO: set_reference_temp_sph Module Reference
set_reference_temp_sph Module Reference
Set diffusive temperature profile
with fixed temperature boundary.
Functions/Subroutines
subroutine no_ref_temp_sph_mhd (depth_top, depth_bottom, nri, r_ICB, r_CMB, reftemp_rj)
subroutine set_ref_temp_sph_mhd (low_temp, depth_top, high_temp, depth_bottom, nidx_rj, r_1d_rj, ar_1d_rj, reftemp_rj)
subroutine set_stratified_sph_mhd (stratified_sigma, stratified_width, stratified_outer_r, nidx_rj, r_ICB, r_CMB, kr_ICB, kr_CMB, r_1d_rj, reftemp_rj)
subroutine set_reftemp_4_sph (idx_rj_degree_zero, nidx_rj, reftemp_rj, i_ref, i_gref, nnod_rj, ntot_phys_rj, d_rj)
Detailed Description
Set diffusive temperature profile
with fixed temperature boundary.
      subroutine no_ref_temp_sph_mhd(depth_top, depth_bottom,         &
     &          nri, r_ICB, r_CMB, reftemp_rj)
      subroutine set_ref_temp_sph_mhd                                 &
     &         (low_temp, depth_top, high_temp, depth_bottom,         &
     &          nidx_rj, r_1d_rj, ar_1d_rj, reftemp_rj)
      subroutine set_stratified_sph_mhd                               &
     &        (stratified_sigma, stratified_width, stratified_outer_r,&
     &         nidx_rj, r_ICB, r_CMB, kr_ICB, kr_CMB, r_1d_rj,        &
     &         reftemp_rj)
      subroutine set_reftemp_4_sph(idx_rj_degree_zero, nidx_rj,       &
     &         reftemp_rj, i_ref, i_gref, nnod_rj, ntot_phys_rj, d_rj)
        type(phys_address), intent(in) :: ipol
***********************************************************************
*
*     ref_temp(k,0) : reference of temperature  (output)
*     ref_temp(k,1) : dT_0 / dr
*     ref_temp(k,2) : d^2 T_0 / dr^2
*
*                          c2
*      ref_temp(k) = c1 + ------
*                          r(k)
*
*                      dto(k)
*     dref_temp(k) = ---------
*                        dr
*                         c2
*                  = - --------
*                        rs(k)
*
***********************************************************************
Function/Subroutine Documentation
no_ref_temp_sph_mhd()
subroutine set_reference_temp_sph::no_ref_temp_sph_mhd (real (kind = kreal), intent(inout) depth_top, real (kind = kreal), intent(inout) depth_bottom, integer(kind = kint), intent(in) nri, real(kind = kreal), intent(in) r_ICB, real(kind = kreal), intent(in) r_CMB, real(kind=kreal), dimension(nri,0:2), intent(inout) reftemp_rj)
Definition at line 61 of file set_reference_temp_sph.f90.
References m_constants::zero.
Referenced by init_radial_infos_sph_mhd::init_reference_temps().
set_ref_temp_sph_mhd()
subroutine set_reference_temp_sph::set_ref_temp_sph_mhd (real (kind = kreal), intent(in) low_temp, real (kind = kreal), intent(inout) depth_top, real (kind = kreal), intent(in) high_temp, real (kind = kreal), intent(inout) depth_bottom, integer(kind = kint), dimension(2), intent(in) nidx_rj, real(kind=kreal), dimension(nidx_rj(1)), intent(in) r_1d_rj, real(kind=kreal), dimension(nidx_rj(1),3), intent(in) ar_1d_rj, real(kind=kreal), dimension(nidx_rj(1),0:2), intent(inout) reftemp_rj)
Definition at line 82 of file set_reference_temp_sph.f90.
References m_constants::two, and m_constants::zero.
Referenced by init_radial_infos_sph_mhd::init_reference_temps().
set_reftemp_4_sph()
subroutine set_reference_temp_sph::set_reftemp_4_sph (integer(kind = kint), intent(in) idx_rj_degree_zero, integer(kind = kint), dimension(2), intent(in) nidx_rj, real(kind=kreal), dimension(nidx_rj(1),0:1), intent(in) reftemp_rj, integer(kind = kint), intent(in) i_ref, integer(kind = kint), intent(in) i_gref, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 182 of file set_reference_temp_sph.f90.
References m_constants::izero.
set_stratified_sph_mhd()
subroutine set_reference_temp_sph::set_stratified_sph_mhd (real (kind=kreal), intent(in) stratified_sigma, real (kind=kreal), intent(in) stratified_width, real (kind=kreal), intent(in) stratified_outer_r, integer(kind = kint), dimension(2), intent(in) nidx_rj, real(kind = kreal), intent(in) r_ICB, real(kind = kreal), intent(in) r_CMB, integer(kind = kint), intent(in) kr_ICB, integer(kind = kint), intent(in) kr_CMB, real(kind=kreal), dimension(nidx_rj(1)), intent(in) r_1d_rj, real(kind=kreal), dimension(nidx_rj(1),0:2), intent(inout) reftemp_rj)
Definition at line 128 of file set_reference_temp_sph.f90.
References m_constants::half, m_constants::one, and m_constants::zero.
Referenced by init_radial_infos_sph_mhd::init_reference_temps().