CALYPSO: t_ctl_data_sph_mhd_control Module Reference
t_ctl_data_sph_mhd_control Module Reference
Data Types
type sph_mhd_control_control
Functions/Subroutines
subroutine read_sph_mhd_control (id_control, hd_block, smctl_ctl, c_buf)
subroutine bcast_sph_mhd_control (smctl_ctl)
Variables
character(len=kchara), parameter, private hd_time_step = 'time_step_ctl'
character(len=kchara), parameter, private hd_restart_file = 'restart_file_ctl'
character(len=kchara), parameter, private hd_time_loop = 'time_loop_ctl'
Function/Subroutine Documentation
bcast_sph_mhd_control()
subroutine t_ctl_data_sph_mhd_control::bcast_sph_mhd_control (type(sph_mhd_control_control), intent(inout) smctl_ctl)
Definition at line 94 of file t_ctl_data_SPH_MHD_control.f90.
References bcast_4_time_step_ctl::bcast_ctl_data_4_time_step(), t_ctl_data_mhd_evo_scheme::bcast_restart_ctl(), t_ctl_data_mhd_evo_scheme::bcast_time_loop_ctl(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by t_ctl_data_mhd::bcast_sph_mhd_ctl_data().
read_sph_mhd_control()
subroutine t_ctl_data_sph_mhd_control::read_sph_mhd_control (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(sph_mhd_control_control), intent(inout) smctl_ctl, type(buffer_for_control), intent(inout) c_buf)
Definition at line 61 of file t_ctl_data_SPH_MHD_control.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_restart_file, hd_time_loop, hd_time_step, t_read_control_elements::load_one_line_from_control(), t_ctl_data_4_time_steps::read_control_time_step_data(), t_ctl_data_mhd_evo_scheme::read_restart_ctl(), and t_ctl_data_mhd_evo_scheme::read_time_loop_ctl().
Referenced by t_ctl_data_mhd::read_sph_mhd_ctl_noviz(), and t_ctl_data_mhd::read_sph_mhd_ctl_w_psf().
Variable Documentation
hd_restart_file
character(len=kchara), parameter, private t_ctl_data_sph_mhd_control::hd_restart_file = 'restart_file_ctl' private
Definition at line 48 of file t_ctl_data_SPH_MHD_control.f90.
Referenced by read_sph_mhd_control().
hd_time_loop
character(len=kchara), parameter, private t_ctl_data_sph_mhd_control::hd_time_loop = 'time_loop_ctl' private
Definition at line 50 of file t_ctl_data_SPH_MHD_control.f90.
Referenced by read_sph_mhd_control().
hd_time_step
character(len=kchara), parameter, private t_ctl_data_sph_mhd_control::hd_time_step = 'time_step_ctl' private
Definition at line 46 of file t_ctl_data_SPH_MHD_control.f90.
Referenced by read_sph_mhd_control().