CALYPSO: calypso_sr_core Module Reference
calypso_sr_core Module Reference
Arbitrary components data communication
using reverse import table.
Functions/Subroutines
subroutine check_calypso_sr_stack (NB, npe_send, isend_self, istack_send, npe_recv, irecv_self, istack_recv, SR_sig, SR_r)
subroutine calypso_send_recv_core (NB, npe_send, isend_self, id_pe_send, istack_send, npe_recv, irecv_self, id_pe_recv, istack_recv, SR_sig, SR_r)
subroutine, private check_calypso_send_recv_stack (NB, npe_send, isend_self, istack_send, npe_recv, irecv_self, istack_recv, SR_r)
Detailed Description
Arbitrary components data communication
using reverse import table.
      subroutine check_calypso_SR_stack                               &
     &         (NB, npe_send, isend_self, istack_send,                &
     &              npe_recv, irecv_self, istack_recv, SR_sig, SR_r)
      subroutine calypso_send_recv_core                               &
     &         (NB, npe_send, isend_self, id_pe_send, istack_send,    &
     &              npe_recv, irecv_self, id_pe_recv, istack_recv,    &
     &              SR_sig, SR_r)
        type(send_recv_status), intent(inout) :: SR_sig
        type(send_recv_real_buffer), intent(inout) :: SR_r
Parameters
NB Number of components for communication
nnod_org Number of data points for origin
nnod_new Number of components for destination
npe_send Number of processses to send
isend_self Integer flag to copy within own process
id_pe_send(npe_send) Process ID to send
istack_send(0:npe_send) End points of send buffer for each process
inod_export(istack_send(npe_send)) local node ID to copy in send buffer
npe_recv Number of processses to receive
irecv_self Integer flag to copy within own process
id_pe_recv(npe_send) Process ID to receive
istack_recv(0:npe_send) End points of receive buffer for each process
irev_import(nnod_new) import buffer ID for each data point
Function/Subroutine Documentation
calypso_send_recv_core()
subroutine calypso_sr_core::calypso_send_recv_core (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) npe_send, integer(kind = kint), intent(in) isend_self, integer(kind = kint), dimension(npe_send), intent(in) id_pe_send, integer(kind = kint), dimension(0:npe_send), intent(in) istack_send, integer(kind = kint), intent(in) npe_recv, integer(kind = kint), intent(in) irecv_self, integer(kind = kint), dimension(npe_recv), intent(in) id_pe_recv, integer(kind = kint), dimension(0:npe_recv), intent(in) istack_recv, type(send_recv_status), intent(inout) SR_sig, type(send_recv_real_buffer), intent(inout) SR_r)
Parameters
[in,out] sr_sig Structure of communication flags
[in,out] sr_r Structure of communication buffer for 8-byte real
Definition at line 87 of file calypso_SR_core.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_real, and calypso_mpi::ierr_mpi.
Referenced by calypso_sr::calypso_send_recv(), calypso_sr_2::calypso_send_recv_2(), calypso_sr_3::calypso_send_recv_3(), calypso_sr::calypso_send_recv_3x1(), calypso_sr_2::calypso_send_recv_3x2(), calypso_sr_3::calypso_send_recv_3x3(), calypso_sr_6::calypso_send_recv_3x6(), calypso_sr_n::calypso_send_recv_3xn(), calypso_sr_6::calypso_send_recv_6(), calypso_sr_n::calypso_send_recv_n(), and sel_spherical_srs::sel_calypso_sph_comm_n().
check_calypso_send_recv_stack()
subroutine, private calypso_sr_core::check_calypso_send_recv_stack (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) npe_send, integer(kind = kint), intent(in) isend_self, integer(kind = kint), dimension(0:npe_send), intent(in) istack_send, integer(kind = kint), intent(in) npe_recv, integer(kind = kint), intent(in) irecv_self, integer(kind = kint), dimension(0:npe_recv), intent(in) istack_recv, type(send_recv_real_buffer), intent(inout) SR_r) private
Parameters
[in,out] sr_r Structure of communication buffer for 8-byte real
Definition at line 154 of file calypso_SR_core.f90.
References calypso_mpi::my_rank.
Referenced by check_calypso_sr_stack().
check_calypso_sr_stack()
subroutine calypso_sr_core::check_calypso_sr_stack (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) npe_send, integer(kind = kint), intent(in) isend_self, integer(kind = kint), dimension(0:npe_send), intent(in) istack_send, integer(kind = kint), intent(in) npe_recv, integer(kind = kint), intent(in) irecv_self, integer(kind = kint), dimension(0:npe_recv), intent(in) istack_recv, type(send_recv_status), intent(inout) SR_sig, type(send_recv_real_buffer), intent(inout) SR_r)
Parameters
[in,out] sr_sig Structure of communication flags
[in,out] sr_r Structure of communication buffer for 8-byte real
Definition at line 58 of file calypso_SR_core.f90.
References check_calypso_send_recv_stack(), and t_solver_sr::resize_work_sr().