CALYPSO: t_spheric_rtp_data Module Reference
t_spheric_rtp_data Module Reference
Structure for indexing table of speherical harmonics transform.
Data Types
type sph_rtp_grid
structure of index table for \(f(r,\theta,\phi) \)
Functions/Subroutines
subroutine alloc_spheric_param_rtp (sph_rtp)
subroutine alloc_sph_1d_index_rtp (sph_rtp)
subroutine alloc_rtp_param_smp (sph_rtp)
subroutine alloc_num_pole_sph_trans (sph_rtp)
subroutine alloc_theta_4_rtp (sph_rtp)
subroutine dealloc_spheric_param_rtp (sph_rtp)
subroutine dealloc_sph_1d_index_rtp (sph_rtp)
subroutine dealloc_rtp_param_smp (sph_rtp)
subroutine dealloc_num_pole_sph_trans (sph_rtp)
subroutine dealloc_theta_4_rtp (sph_rtp)
subroutine copy_spheric_rtp_data (ltr_org, rtp_org, ltr_new, rtp_new)
subroutine check_spheric_param_rtp (id_rank, sph_rtp)
Detailed Description
Structure for indexing table of speherical harmonics transform.
      subroutine alloc_spheric_param_rtp(sph_rtp)
      subroutine alloc_sph_1d_index_rtp(sph_rtp)
      subroutine alloc_rtp_param_smp(sph_rtp)
      subroutine alloc_num_pole_sph_trans(sph_rtp)
      subroutine alloc_theta_4_rtp(sph_rtp)
        type(sph_rtp_grid), intent(inout) :: sph_rtp
      subroutine dealloc_spheric_param_rtp(sph_rtp)
      subroutine dealloc_sph_1d_index_rtp(sph_rtp)
      subroutine dealloc_rtp_param_smp(sph_rtp)
      subroutine dealloc_num_pole_sph_trans(sph_rtp)
      subroutine dealloc_theta_4_rtp(sph_rtp)
        type(sph_rtp_grid), intent(inout) :: sph_rtp
      subroutine copy_spheric_rtp_data                                &
     &         (ltr_org, rtp_org, ltr_new, rtp_new)
        type(sph_rtp_grid), intent(inout) :: rtp_org
        type(sph_rtp_grid), intent(inout) :: rtp_new
      subroutine check_spheric_param_rtp(id_rank, sph_rtp)
        integer, intent(in) :: id_rank
        type(sph_rtp_grid), intent(in) :: sph_rtp
Parameters
id_rank Running rank ID
Function/Subroutine Documentation
alloc_num_pole_sph_trans()
subroutine t_spheric_rtp_data::alloc_num_pole_sph_trans (type(sph_rtp_grid), intent(inout) sph_rtp)
Definition at line 180 of file t_spheric_rtp_data.f90.
References m_machine_parameter::np_smp.
alloc_rtp_param_smp()
subroutine t_spheric_rtp_data::alloc_rtp_param_smp (type(sph_rtp_grid), intent(inout) sph_rtp)
Definition at line 153 of file t_spheric_rtp_data.f90.
References m_machine_parameter::np_smp.
Referenced by count_num_sph_smp::count_num_rtp_smp().
alloc_sph_1d_index_rtp()
subroutine t_spheric_rtp_data::alloc_sph_1d_index_rtp (type(sph_rtp_grid), intent(inout) sph_rtp)
Definition at line 126 of file t_spheric_rtp_data.f90.
Referenced by copy_sph_rtp_node_4_io::copy_sph_node_4_rtp_from_io(), and copy_spheric_rtp_data().
alloc_spheric_param_rtp()
subroutine t_spheric_rtp_data::alloc_spheric_param_rtp (type(sph_rtp_grid), intent(inout) sph_rtp)
Definition at line 115 of file t_spheric_rtp_data.f90.
Referenced by t_spheric_parameter::alloc_spheric_parameter(), copy_sph_rtp_node_4_io::copy_sph_node_4_rtp_from_io(), and copy_spheric_rtp_data().
alloc_theta_4_rtp()
subroutine t_spheric_rtp_data::alloc_theta_4_rtp (type(sph_rtp_grid), intent(inout) sph_rtp)
Definition at line 195 of file t_spheric_rtp_data.f90.
Referenced by set_params_sph_trans::const_sin_theta_rtp().
check_spheric_param_rtp()
subroutine t_spheric_rtp_data::check_spheric_param_rtp (integer, intent(in) id_rank, type(sph_rtp_grid), intent(in) sph_rtp)
Definition at line 325 of file t_spheric_rtp_data.f90.
Referenced by t_spheric_parameter::check_spheric_parameter().
copy_spheric_rtp_data()
subroutine t_spheric_rtp_data::copy_spheric_rtp_data (integer(kind = kint), intent(in) ltr_org, type(sph_rtp_grid), intent(inout) rtp_org, integer(kind = kint), intent(inout) ltr_new, type(sph_rtp_grid), intent(inout) rtp_new)
Definition at line 276 of file t_spheric_rtp_data.f90.
References alloc_sph_1d_index_rtp(), alloc_spheric_param_rtp(), and m_constants::ithree.
dealloc_num_pole_sph_trans()
subroutine t_spheric_rtp_data::dealloc_num_pole_sph_trans (type(sph_rtp_grid), intent(inout) sph_rtp)
Definition at line 251 of file t_spheric_rtp_data.f90.
dealloc_rtp_param_smp()
subroutine t_spheric_rtp_data::dealloc_rtp_param_smp (type(sph_rtp_grid), intent(inout) sph_rtp)
Definition at line 237 of file t_spheric_rtp_data.f90.
dealloc_sph_1d_index_rtp()
subroutine t_spheric_rtp_data::dealloc_sph_1d_index_rtp (type(sph_rtp_grid), intent(inout) sph_rtp)
Definition at line 223 of file t_spheric_rtp_data.f90.
Referenced by t_spheric_parameter::dealloc_sph_1d_indices().
dealloc_spheric_param_rtp()
subroutine t_spheric_rtp_data::dealloc_spheric_param_rtp (type(sph_rtp_grid), intent(inout) sph_rtp)
Definition at line 213 of file t_spheric_rtp_data.f90.
Referenced by t_spheric_parameter::dealloc_spheric_parameter().
dealloc_theta_4_rtp()
subroutine t_spheric_rtp_data::dealloc_theta_4_rtp (type(sph_rtp_grid), intent(inout) sph_rtp)
Definition at line 262 of file t_spheric_rtp_data.f90.