CALYPSO: t_control_array_intcharreal Module Reference
t_control_array_intcharreal Module Reference
Data Types
type ctl_array_icr
Structure for integere, charactor, and real control array.
type read_int_chara_real_item
structure of control item with three characters
Functions/Subroutines
subroutine read_intcharreal_ctl_type (c_buf, label, icr_item)
subroutine write_intcharreal_ctl_type (id_file, level, label, icr_item)
subroutine copy_intchrreal_ctl (org_icr, new_icr)
subroutine alloc_control_array_i_c_r (array_icr)
subroutine dealloc_control_array_i_c_r (array_icr)
subroutine read_control_array_i_c_r (id_control, label, array_icr, c_buf)
subroutine write_control_array_i_c_r (id_control, level, label, array_icr)
subroutine append_control_array_i_c_r (read_icr, array_icr)
subroutine copy_control_array_i_c_r (num_copy, org_icr, tgt_icr)
subroutine append_control_item_i_c_r (read_icr, array_icr)
Function/Subroutine Documentation
alloc_control_array_i_c_r()
subroutine t_control_array_intcharreal::alloc_control_array_i_c_r (type(ctl_array_icr), intent(inout) array_icr)
Definition at line 143 of file t_control_array_intcharreal.f90.
Referenced by append_control_array_i_c_r(), bcast_control_arrays::bcast_ctl_array_icr(), and read_control_array_i_c_r().
append_control_array_i_c_r()
subroutine t_control_array_intcharreal::append_control_array_i_c_r (type(read_int_chara_real_item), intent(inout) read_icr, type(ctl_array_icr), intent(inout) array_icr)
Definition at line 237 of file t_control_array_intcharreal.f90.
References alloc_control_array_i_c_r(), append_control_item_i_c_r(), copy_control_array_i_c_r(), and dealloc_control_array_i_c_r().
Referenced by read_control_array_i_c_r().
append_control_item_i_c_r()
subroutine t_control_array_intcharreal::append_control_item_i_c_r (type(read_int_chara_real_item), intent(in) read_icr, type(ctl_array_icr), intent(inout) array_icr)
Definition at line 279 of file t_control_array_intcharreal.f90.
Referenced by append_control_array_i_c_r().
copy_control_array_i_c_r()
subroutine t_control_array_intcharreal::copy_control_array_i_c_r (integer(kind = kint), intent(in) num_copy, type(ctl_array_icr), intent(in) org_icr, type(ctl_array_icr), intent(inout) tgt_icr)
Definition at line 262 of file t_control_array_intcharreal.f90.
Referenced by append_control_array_i_c_r().
copy_intchrreal_ctl()
subroutine t_control_array_intcharreal::copy_intchrreal_ctl (type(read_int_chara_real_item), intent(in) org_icr, type(read_int_chara_real_item), intent(inout) new_icr)
Definition at line 127 of file t_control_array_intcharreal.f90.
dealloc_control_array_i_c_r()
subroutine t_control_array_intcharreal::dealloc_control_array_i_c_r (type(ctl_array_icr), intent(inout) array_icr)
Definition at line 160 of file t_control_array_intcharreal.f90.
Referenced by append_control_array_i_c_r().
read_control_array_i_c_r()
subroutine t_control_array_intcharreal::read_control_array_i_c_r (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) label, type(ctl_array_icr), intent(inout) array_icr, type(buffer_for_control), intent(inout) c_buf)
Definition at line 174 of file t_control_array_intcharreal.f90.
References alloc_control_array_i_c_r(), append_control_array_i_c_r(), t_read_control_elements::check_array_flag(), t_read_control_elements::check_end_array_flag(), t_read_control_elements::load_one_line_from_control(), and read_intcharreal_ctl_type().
read_intcharreal_ctl_type()
subroutine t_control_array_intcharreal::read_intcharreal_ctl_type (type(buffer_for_control), intent(in) c_buf, character(len=kchara), intent(in) label, type(read_int_chara_real_item), intent(inout) icr_item)
Definition at line 81 of file t_control_array_intcharreal.f90.
References m_machine_parameter::iflag_debug.
Referenced by read_control_array_i_c_r().
write_control_array_i_c_r()
subroutine t_control_array_intcharreal::write_control_array_i_c_r (integer(kind = kint), intent(in) id_control, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, type(ctl_array_icr), intent(in) array_icr)
Definition at line 208 of file t_control_array_intcharreal.f90.
References write_control_elements::write_array_flag_for_ctl(), write_control_elements::write_end_array_flag_for_ctl(), and write_control_elements::write_i_c_r_ctl_item().
write_intcharreal_ctl_type()
subroutine t_control_array_intcharreal::write_intcharreal_ctl_type (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, type(read_int_chara_real_item), intent(in) icr_item)
Definition at line 108 of file t_control_array_intcharreal.f90.
References write_control_elements::write_i_c_r_ctl_item().