CALYPSO: bcast_4_assemble_sph_ctl Module Reference
bcast_4_assemble_sph_ctl Module Reference
Control data for merge program.
Functions/Subroutines
subroutine bcast_merge_control_data (mgd_ctl)
subroutine, private bcast_merge_field_data (mgd_ctl)
subroutine, private bcast_merge_step_data (mgd_ctl)
subroutine, private bcast_newrst_control (mgd_ctl)
Detailed Description
Control data for merge program.
       subroutine bcast_merge_control_data(mgd_ctl)
         type(control_data_4_merge), intent(inout) :: mgd_ctl
Function/Subroutine Documentation
bcast_merge_control_data()
subroutine bcast_4_assemble_sph_ctl::bcast_merge_control_data (type(control_data_4_merge), intent(inout) mgd_ctl)
Definition at line 31 of file bcast_4_assemble_sph_ctl.f90.
References bcast_4_platform_ctl::bcast_ctl_data_4_platform(), bcast_merge_field_data(), bcast_merge_step_data(), bcast_newrst_control(), t_ctl_data_gen_sph_shell::bcast_parallel_shell_ctl(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by analyzer_assemble_sph::init_assemble_sph(), analyzer_compare_sph_rst::init_compare_sph_restart(), and analyzer_rayleigh_cvt_sph::init_cvt_rayleigh_sph().
bcast_merge_field_data()
subroutine, private bcast_4_assemble_sph_ctl::bcast_merge_field_data (type(control_data_4_merge), intent(inout) mgd_ctl) private
Definition at line 59 of file bcast_4_assemble_sph_ctl.f90.
References bcast_4_field_ctl::bcast_phys_data_ctl(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by bcast_merge_control_data().
bcast_merge_step_data()
subroutine, private bcast_4_assemble_sph_ctl::bcast_merge_step_data (type(control_data_4_merge), intent(inout) mgd_ctl) private
Definition at line 75 of file bcast_4_assemble_sph_ctl.f90.
References bcast_4_time_step_ctl::bcast_ctl_data_4_time_step(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by bcast_merge_control_data().
bcast_newrst_control()
subroutine, private bcast_4_assemble_sph_ctl::bcast_newrst_control (type(control_data_4_merge), intent(inout) mgd_ctl) private
Definition at line 92 of file bcast_4_assemble_sph_ctl.f90.
References bcast_control_arrays::bcast_ctl_type_r1(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by bcast_merge_control_data().