CALYPSO: t_control_data_4_psf Module Reference
t_control_data_4_psf Module Reference
control ID data for surfacing module
Data Types
type psf_ctl
Functions/Subroutines
subroutine init_psf_ctl_stract (psf_c)
subroutine dealloc_cont_dat_4_psf (psf_c)
subroutine dup_control_4_psf (org_psf_c, new_psf_c)
subroutine read_psf_control_data (id_control, hd_block, psf_c, c_buf)
subroutine bcast_psf_control_data (psf_c)
integer(kind=kint) function num_label_psf_ctl ()
integer(kind=kint) function num_label_psf_ctl_w_dpl ()
subroutine set_label_psf_ctl (names)
subroutine set_label_psf_ctl_w_dpl (names)
Variables
character(len=kchara), parameter, private hd_psf_file_prefix = 'section_file_prefix'
character(len=kchara), parameter, private hd_psf_out_type = 'psf_output_type'
character(len=kchara), parameter, private hd_surface_define = 'surface_define'
character(len=kchara), parameter, private hd_output_field = 'output_field_define'
character(len=kchara), parameter, private hd_psf_file_head = 'psf_file_head'
integer(kind=kint), parameter, private n_label_psf_ctl = 4
integer(kind=kint), parameter, private n_label_psf_ctl_w_dpl = 5
Detailed Description
control ID data for surfacing module
      subroutine init_psf_ctl_stract(psf_c)
      subroutine dealloc_cont_dat_4_psf(psf_c)
        type(psf_ctl), intent(inout) :: psf_c
      subroutine dup_control_4_psf(org_psf_c, new_psf_c)
        type(psf_ctl), intent(in) :: org_psf_c
        type(psf_ctl), intent(inout) :: new_psf_c
      subroutine read_psf_control_data                                &
     &         (id_control, hd_block, psf_c, c_buf)
      subroutine bcast_psf_control_data(psf_c)
        type(psf_ctl), intent(inout) :: psf_c
      integer(kind = kint) function num_label_psf_ctl()
      integer(kind = kint) function num_label_psf_ctl_w_dpl()
      subroutine set_label_psf_ctl(names)
      subroutine set_label_psf_ctl_w_dpl(names)
 example of control for Kemo's surface rendering
  begin cross_section_ctl
    section_file_prefix    'psf'
    psf_output_type         ucd
    begin surface_define
      section_method    equation
      array coefs_ctl  10
        coefs_ctl  x2     1.0
        coefs_ctl  y2     1.0
        coefs_ctl  z2     0.0
        coefs_ctl  xy     0.0
        coefs_ctl  yz     0.0
        coefs_ctl  zx     0.0
        coefs_ctl  x      0.0
        coefs_ctl  y      0.0
        coefs_ctl  z      0.0
        coefs_ctl  const  1.0
      end array coefs_ctl
      array section_area_ctl 1
        section_area_ctl   outer_core   end
      end array section_area_ctl
    end surface_define
    begin output_field_define
      array  output_field   2
        output_field    velocity         vector   end
        output_field    magnetic_field   radial   end
      end  array output_field
    end output_field_define
  end  cross_section_ctl
      psf_output_type:
           ucd, OpenDX
    num_result_comp: number of fields
    output_field: (Original name: color_comp and color_subcomp)
         field and componenet name for output
           x, y, z, radial, elevation, azimuth, cylinder_r, norm
           vector, sym_tensor, asym_tensor
           spherical_vector, cylindrical_vector
    output_value: (Original name: specified_color)
    section_method: (original: method)
           plane, sphere, ellipsoid, hyperboloid, paraboloid
           equation, group
    normal_vector: normal vector (for plane)
        array normal_vector    3
          normal_vector  x   0.0
          normal_vector  y   0.0
          normal_vector  z   1.0
        end array normal_vector
    center_position: position of center (for sphere and plane)
        array center_position    3
          center_position  x   0.0
          center_position  y   0.0
          center_position  z   0.0
        end array center_position
    radius:  radius of sphere
    axial_length: length of axis
          (for ellipsoid, hyperboloid, paraboloid)
        array axial_length   3
          axial_length  x   1.0
          axial_length  y   0.5
          axial_length  z   0.0
        end array axial_length
    coefficients:  coefficients for equation
        array coefs_ctl  10
          coefs_ctl  x2     1.0
          coefs_ctl  y2     0.5
          coefs_ctl  z2     0.0
          coefs_ctl  xy     1.0
          coefs_ctl  yz     0.5
          coefs_ctl  zx     0.0
          coefs_ctl  x      1.0
          coefs_ctl  y      0.5
          coefs_ctl  z      0.0
          coefs_ctl  const  1.0
        end array coefs_ctl
    group_type:  (Original: defined_style)
           node_group or surface_group
    group_name:  name of group to plot
   field type:
     scalar, vector,     sym_tensor, asym_tensor
     spherical_vector,   spherical_sym_tensor
     cylindrical_vector, cylindrical_sym_tensor
     norm
Function/Subroutine Documentation
bcast_psf_control_data()
subroutine t_control_data_4_psf::bcast_psf_control_data (type(psf_ctl), intent(inout) psf_c)
Definition at line 280 of file t_control_data_4_psf.f90.
References bcast_control_arrays::bcast_ctl_type_c1(), t_control_data_4_fld_on_psf::bcast_fld_on_psf_control(), t_control_data_4_psf_def::bcast_section_def_control(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by t_control_data_sections::bcast_files_4_psf_ctl().
dealloc_cont_dat_4_psf()
subroutine t_control_data_4_psf::dealloc_cont_dat_4_psf (type(psf_ctl), intent(inout) psf_c)
Definition at line 198 of file t_control_data_4_psf.f90.
References t_control_data_4_psf_def::dealloc_cont_dat_4_psf_def(), and t_control_data_4_fld_on_psf::dealloc_fld_on_psf_control().
Referenced by t_control_data_sections::dealloc_cont_dat_4_psfs(), and set_psf_iso_control::set_psf_control().
dup_control_4_psf()
subroutine t_control_data_4_psf::dup_control_4_psf (type(psf_ctl), intent(in) org_psf_c, type(psf_ctl), intent(inout) new_psf_c)
Definition at line 216 of file t_control_data_4_psf.f90.
References t_control_array_character::copy_chara_ctl(), t_control_data_4_psf_def::dup_control_4_psf_def(), and t_control_data_4_fld_on_psf::dup_fld_on_psf_control().
Referenced by t_control_data_sections::dup_control_4_psfs().
init_psf_ctl_stract()
subroutine t_control_data_4_psf::init_psf_ctl_stract (type(psf_ctl), intent(inout) psf_c)
Definition at line 187 of file t_control_data_4_psf.f90.
References t_control_data_4_fld_on_psf::init_fld_on_psf_control(), and t_control_data_4_psf_def::init_psf_def_ctl_stract().
Referenced by t_control_data_sections::alloc_psf_ctl_stract().
num_label_psf_ctl()
integer(kind = kint) function t_control_data_4_psf::num_label_psf_ctl
Definition at line 303 of file t_control_data_4_psf.f90.
References n_label_psf_ctl.
num_label_psf_ctl_w_dpl()
integer(kind = kint) function t_control_data_4_psf::num_label_psf_ctl_w_dpl
Definition at line 310 of file t_control_data_4_psf.f90.
References n_label_psf_ctl_w_dpl.
read_psf_control_data()
subroutine t_control_data_4_psf::read_psf_control_data (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(psf_ctl), intent(inout) psf_c, type(buffer_for_control), intent(inout) c_buf)
Definition at line 240 of file t_control_data_4_psf.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_output_field, hd_psf_file_head, hd_psf_file_prefix, hd_psf_out_type, hd_surface_define, t_read_control_elements::load_one_line_from_control(), t_control_array_character::read_chara_ctl_type(), t_control_data_4_fld_on_psf::read_fld_on_psf_control(), and t_control_data_4_psf_def::read_section_def_control().
Referenced by t_control_data_sections::read_control_4_psf_file(), and t_control_data_sections::read_files_4_psf_ctl().
set_label_psf_ctl()
subroutine t_control_data_4_psf::set_label_psf_ctl (character(len = kchara), dimension(n_label_psf_ctl), intent(inout) names)
Definition at line 317 of file t_control_data_4_psf.f90.
References hd_output_field, hd_psf_file_prefix, hd_psf_out_type, hd_surface_define, and t_read_control_elements::set_control_labels().
Referenced by set_label_psf_ctl_w_dpl().
set_label_psf_ctl_w_dpl()
subroutine t_control_data_4_psf::set_label_psf_ctl_w_dpl (character(len = kchara), dimension(n_label_psf_ctl_w_dpl), intent(inout) names)
Definition at line 332 of file t_control_data_4_psf.f90.
References hd_psf_file_head, t_read_control_elements::set_control_labels(), and set_label_psf_ctl().
Variable Documentation
hd_output_field
character(len=kchara), parameter, private t_control_data_4_psf::hd_output_field = 'output_field_define' private
Definition at line 166 of file t_control_data_4_psf.f90.
Referenced by read_psf_control_data(), and set_label_psf_ctl().
hd_psf_file_head
character(len=kchara), parameter, private t_control_data_4_psf::hd_psf_file_head = 'psf_file_head' private
Definition at line 170 of file t_control_data_4_psf.f90.
Referenced by read_psf_control_data(), and set_label_psf_ctl_w_dpl().
hd_psf_file_prefix
character(len=kchara), parameter, private t_control_data_4_psf::hd_psf_file_prefix = 'section_file_prefix' private
Definition at line 160 of file t_control_data_4_psf.f90.
Referenced by read_psf_control_data(), and set_label_psf_ctl().
hd_psf_out_type
character(len=kchara), parameter, private t_control_data_4_psf::hd_psf_out_type = 'psf_output_type' private
Definition at line 162 of file t_control_data_4_psf.f90.
Referenced by read_psf_control_data(), and set_label_psf_ctl().
hd_surface_define
character(len=kchara), parameter, private t_control_data_4_psf::hd_surface_define = 'surface_define' private
Definition at line 164 of file t_control_data_4_psf.f90.
Referenced by read_psf_control_data(), and set_label_psf_ctl().
n_label_psf_ctl
integer(kind = kint), parameter, private t_control_data_4_psf::n_label_psf_ctl = 4 private
Definition at line 173 of file t_control_data_4_psf.f90.
Referenced by num_label_psf_ctl().
n_label_psf_ctl_w_dpl
integer(kind = kint), parameter, private t_control_data_4_psf::n_label_psf_ctl_w_dpl = 5 private
Definition at line 174 of file t_control_data_4_psf.f90.
Referenced by num_label_psf_ctl_w_dpl().