CALYPSO: t_boundary_sph_spectr Module Reference
t_boundary_sph_spectr Module Reference
Structure for basic boundary conditions for spherical dynamo.
Data Types
type sph_scalar_bc_coef
Structure for boundary scalar spectr.
type sph_scalar_bc_evo
Structure for boundary scalar spectr.
type sph_scalar_boundary_data
Structure for scalar spectr boundaries.
type sph_vector_bc_coef
Structure for boundary velocity spectr.
type sph_vector_bc_evo
Structure for boundary velocity spectr.
type sph_vector_boundary_data
Structure for vector spectr boundaries.
Functions/Subroutines
subroutine alloc_sph_scalar_bcs_data (jmax, bcs_S)
subroutine alloc_sph_vector_bcs_data (jmax, bcs_V)
subroutine dealloc_sph_scalar_bcs_data (bcs_S)
subroutine dealloc_sph_vector_bcs_data (bcs_V)
subroutine, private alloc_sph_scalar_bc_array (jmax, bc_Sspec)
subroutine, private alloc_sph_vector_bc_array (jmax, bc_Vspec)
subroutine, private alloc_sph_evo_scalar_bc_array (jmax, bc_Sevo)
subroutine, private alloc_sph_evo_vector_bc_array (jmax, bc_Vevo)
subroutine, private dealloc_sph_scalar_bc_array (bc_Sspec)
subroutine, private dealloc_sph_vector_bc_array (bc_Vspec)
subroutine, private dealloc_sph_evo_scalar_bc_array (bc_Sevo)
subroutine, private dealloc_sph_evo_vector_bc_array (bc_Vevo)
Detailed Description
Structure for basic boundary conditions for spherical dynamo.
      subroutine alloc_sph_scalar_bcs_data(jmax, bcs_S)
      subroutine dealloc_sph_scalar_bcs_data(bcs_S)
        type(sph_scalar_boundary_data), intent(inout) :: bcs_S
      subroutine alloc_sph_vector_bcs_data(jmax, bcs_V)
      subroutine dealloc_sph_vector_bcs_data(bcs_V)
        type(sph_vector_boundary_data), intent(inout) :: bcs_V
Parameters
jmax number of modes for spherical harmonics \(L*(L+2)\)
nri number of radial grid points
radius radius
Function/Subroutine Documentation
alloc_sph_evo_scalar_bc_array()
subroutine, private t_boundary_sph_spectr::alloc_sph_evo_scalar_bc_array (integer(kind = kint), intent(in) jmax, type(sph_scalar_bc_evo), intent(inout) bc_Sevo) private
Definition at line 234 of file t_boundary_sph_spectr.f90.
Referenced by alloc_sph_scalar_bcs_data().
alloc_sph_evo_vector_bc_array()
subroutine, private t_boundary_sph_spectr::alloc_sph_evo_vector_bc_array (integer(kind = kint), intent(in) jmax, type(sph_vector_bc_evo), intent(inout) bc_Vevo) private
Definition at line 255 of file t_boundary_sph_spectr.f90.
Referenced by alloc_sph_vector_bcs_data().
alloc_sph_scalar_bc_array()
subroutine, private t_boundary_sph_spectr::alloc_sph_scalar_bc_array (integer(kind = kint), intent(in) jmax, type(sph_scalar_bc_coef), intent(inout) bc_Sspec) private
Definition at line 197 of file t_boundary_sph_spectr.f90.
Referenced by alloc_sph_scalar_bcs_data().
alloc_sph_scalar_bcs_data()
subroutine t_boundary_sph_spectr::alloc_sph_scalar_bcs_data (integer(kind = kint), intent(in) jmax, type(sph_scalar_boundary_data), intent(inout) bcs_S)
Definition at line 135 of file t_boundary_sph_spectr.f90.
References alloc_sph_evo_scalar_bc_array(), and alloc_sph_scalar_bc_array().
Referenced by set_bc_sph_scalars::set_sph_bc_scalar_sph().
alloc_sph_vector_bc_array()
subroutine, private t_boundary_sph_spectr::alloc_sph_vector_bc_array (integer(kind = kint), intent(in) jmax, type(sph_vector_bc_coef), intent(inout) bc_Vspec) private
Definition at line 213 of file t_boundary_sph_spectr.f90.
Referenced by alloc_sph_vector_bcs_data().
alloc_sph_vector_bcs_data()
subroutine t_boundary_sph_spectr::alloc_sph_vector_bcs_data (integer(kind = kint), intent(in) jmax, type(sph_vector_boundary_data), intent(inout) bcs_V)
Definition at line 151 of file t_boundary_sph_spectr.f90.
References alloc_sph_evo_vector_bc_array(), and alloc_sph_vector_bc_array().
Referenced by set_bc_flag_sph_velo::set_sph_bc_velo_sph().
dealloc_sph_evo_scalar_bc_array()
subroutine, private t_boundary_sph_spectr::dealloc_sph_evo_scalar_bc_array (type(sph_scalar_bc_evo), intent(inout) bc_Sevo) private
Definition at line 311 of file t_boundary_sph_spectr.f90.
Referenced by dealloc_sph_scalar_bcs_data().
dealloc_sph_evo_vector_bc_array()
subroutine, private t_boundary_sph_spectr::dealloc_sph_evo_vector_bc_array (type(sph_vector_bc_evo), intent(inout) bc_Vevo) private
Definition at line 323 of file t_boundary_sph_spectr.f90.
Referenced by dealloc_sph_vector_bcs_data().
dealloc_sph_scalar_bc_array()
subroutine, private t_boundary_sph_spectr::dealloc_sph_scalar_bc_array (type(sph_scalar_bc_coef), intent(inout) bc_Sspec) private
Definition at line 291 of file t_boundary_sph_spectr.f90.
Referenced by dealloc_sph_scalar_bcs_data().
dealloc_sph_scalar_bcs_data()
subroutine t_boundary_sph_spectr::dealloc_sph_scalar_bcs_data (type(sph_scalar_boundary_data), intent(inout) bcs_S)
Definition at line 167 of file t_boundary_sph_spectr.f90.
References dealloc_sph_evo_scalar_bc_array(), and dealloc_sph_scalar_bc_array().
dealloc_sph_vector_bc_array()
subroutine, private t_boundary_sph_spectr::dealloc_sph_vector_bc_array (type(sph_vector_bc_coef), intent(inout) bc_Vspec) private
Definition at line 301 of file t_boundary_sph_spectr.f90.
Referenced by dealloc_sph_vector_bcs_data().
dealloc_sph_vector_bcs_data()
subroutine t_boundary_sph_spectr::dealloc_sph_vector_bcs_data (type(sph_vector_boundary_data), intent(inout) bcs_V)
Definition at line 182 of file t_boundary_sph_spectr.f90.
References dealloc_sph_evo_vector_bc_array(), and dealloc_sph_vector_bc_array().