CALYPSO: t_mhd_multi_fftw Module Reference
t_mhd_multi_fftw Module Reference
Fourier transform for MHD simulation using FFTW Ver.3.
Functions/Subroutines
subroutine init_mhd_multi_fftw_t (ncomp, ncomp_bwd, ncomp_fwd, nidx_rtp, irt_rtp_smp_stack, X_rtp, FFTW_t)
subroutine finalize_mhd_multi_fftw_t (FFTW_t)
subroutine verify_mhd_multi_fftw_t (ncomp, ncomp_bwd, ncomp_fwd, nnod_rtp, nidx_rtp, irt_rtp_smp_stack, X_rtp, FFTW_t)
subroutine mhd_mul_fwd_fftw_to_send_t (ncomp_fwd, nnod_rtp, nidx_rtp, irt_rtp_smp_stack, n_WS, irev_sr_rtp, X_rtp, WS, FFTW_t)
subroutine mhd_mul_back_fftw_from_recv_t (ncomp_bwd, nnod_rtp, nidx_rtp, irt_rtp_smp_stack, n_WR, irev_sr_rtp, WR, X_rtp, FFTW_t)
subroutine, private alloc_mhd_mul_fftw_plan (ncomp, nnod_rt, Nfft, FFTW_t)
Variables
real(kind=kreal), dimension(3) elapsed_fftw = (/0.0,0.0,0.0/)
Detailed Description
Fourier transform for MHD simulation using FFTW Ver.3.
 ------------------------------------------------------------------
      subroutine init_MHD_multi_FFTW_t(ncomp, ncomp_bwd, ncomp_fwd,   &
     &         nidx_rtp, irt_rtp_smp_stack, X_rtp, FFTW_t)
      subroutine finalize_MHD_multi_FFTW_t(FFTW_t)
      subroutine verify_MHD_multi_FFTW_t(ncomp, ncomp_bwd, ncomp_fwd, &
     &          nnod_rtp, nidx_rtp, irt_rtp_smp_stack, X_rtp, FFTW_t)
   wrapper subroutine for initierize FFT by FFTW
 ------------------------------------------------------------------
      subroutine MHD_mul_fwd_FFTW_to_send_t                           &
     &         (ncomp_fwd, nnod_rtp, nidx_rtp, irt_rtp_smp_stack,     &
     &          n_WS, irev_sr_rtp, X_rtp, WS, FFTW_t)
 ------------------------------------------------------------------
 wrapper subroutine for forward Fourier transform by FFTW3
   a_{k} = \frac{2}{Nfft} \sum_{j=0}^{Nfft-1} x_{j} \cos (\frac{2\pi j k}{Nfft})
   b_{k} = \frac{2}{Nfft} \sum_{j=0}^{Nfft-1} x_{j} \cos (\frac{2\pi j k}{Nfft})
   a_{0} = \frac{1}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
    K = Nfft/2....
   a_{k} = \frac{1}{Nfft} \sum_{j=0}^{Nfft-1} x_{j} \cos (\frac{2\pi j k}{Nfft})
 ------------------------------------------------------------------
      subroutine MHD_mul_back_FFTW_from_recv_t                        &
     &         (ncomp_bwd, nnod_rtp, nidx_rtp, irt_rtp_smp_stack,     &
     &          n_WR, irev_sr_rtp, WR, X_rtp, FFTW_t)
 ------------------------------------------------------------------
 wrapper subroutine for backward Fourier transform by FFTW3
   x_{k} = a_{0} + (-1)^{j} a_{Nfft/2} + sum_{k=1}^{Nfft/2-1}
          (a_{k} \cos(2\pijk/Nfft) + b_{k} \sin(2\pijk/Nfft))
 ------------------------------------------------------------------
       i = 1:     a_{0}
       i = 2:     a_{Nfft/2}
       i = 3:     a_{1}
       i = 4:     b_{1}
       ...
       i = 2*k+1: a_{k}
       i = 2*k+2: b_{k}
       ...
       i = Nfft-1:   a_{Nfft/2-1}
       i = Nfft:     b_{Nfft/2-1}
 ------------------------------------------------------------------
Parameters
Nstacksmp(0:np_smp) End number for each SMP process
Ncomp Number of components for Fourier transforms
Nfft Data length for eadh FFT
X(Ncomp,Nfft) Data for Fourier transform
Function/Subroutine Documentation
alloc_mhd_mul_fftw_plan()
subroutine, private t_mhd_multi_fftw::alloc_mhd_mul_fftw_plan (integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nnod_rt, integer(kind = kint), intent(in) Nfft, type(work_for_sgl_fftw), intent(inout) FFTW_t) private
Definition at line 326 of file t_MHD_multi_FFTW.F90.
References m_machine_parameter::np_smp.
Referenced by init_mhd_multi_fftw_t().
finalize_mhd_multi_fftw_t()
subroutine t_mhd_multi_fftw::finalize_mhd_multi_fftw_t (type(work_for_sgl_fftw), intent(inout) FFTW_t)
Definition at line 147 of file t_MHD_multi_FFTW.F90.
References t_sph_single_fftw::dealloc_fftw_plan(), and m_machine_parameter::np_smp.
Referenced by verify_mhd_multi_fftw_t().
init_mhd_multi_fftw_t()
subroutine t_mhd_multi_fftw::init_mhd_multi_fftw_t (integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), intent(in) ncomp_fwd, integer(kind = kint), dimension(3), intent(in) nidx_rtp, integer(kind = kint), dimension(0:np_smp), intent(in) irt_rtp_smp_stack, real(kind = kreal), dimension(nidx_rtp(3),irt_rtp_smp_stack(np_smp),ncomp), intent(inout) X_rtp, type(work_for_sgl_fftw), intent(inout) FFTW_t)
Definition at line 87 of file t_MHD_multi_FFTW.F90.
References alloc_mhd_mul_fftw_plan(), and m_constants::one.
Referenced by verify_mhd_multi_fftw_t().
mhd_mul_back_fftw_from_recv_t()
subroutine t_mhd_multi_fftw::mhd_mul_back_fftw_from_recv_t (integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(3), intent(in) nidx_rtp, integer(kind = kint), dimension(0:np_smp), intent(in) irt_rtp_smp_stack, integer(kind = kint), intent(in) n_WR, integer(kind = kint), dimension(nnod_rtp), intent(in) irev_sr_rtp, real (kind=kreal), dimension(n_wr), intent(inout) WR, real(kind = kreal), dimension(nidx_rtp(3),irt_rtp_smp_stack(np_smp),ncomp_bwd), intent(inout) X_rtp, type(work_for_sgl_fftw), intent(inout) FFTW_t)
Definition at line 260 of file t_MHD_multi_FFTW.F90.
References m_constants::half, and m_constants::zero.
mhd_mul_fwd_fftw_to_send_t()
subroutine t_mhd_multi_fftw::mhd_mul_fwd_fftw_to_send_t (integer(kind = kint), intent(in) ncomp_fwd, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(3), intent(in) nidx_rtp, integer(kind = kint), dimension(0:np_smp), intent(in) irt_rtp_smp_stack, integer(kind = kint), intent(in) n_WS, integer(kind = kint), dimension(nnod_rtp), intent(in) irev_sr_rtp, real(kind = kreal), dimension(nidx_rtp(3),irt_rtp_smp_stack(np_smp),ncomp_fwd), intent(inout) X_rtp, real (kind=kreal), dimension(n_ws), intent(inout) WS, type(work_for_sgl_fftw), intent(inout) FFTW_t)
Definition at line 196 of file t_MHD_multi_FFTW.F90.
References m_constants::two.
verify_mhd_multi_fftw_t()
subroutine t_mhd_multi_fftw::verify_mhd_multi_fftw_t (integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), intent(in) ncomp_fwd, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(3), intent(in) nidx_rtp, integer(kind = kint), dimension(0:np_smp), intent(in) irt_rtp_smp_stack, real(kind = kreal), dimension(nidx_rtp(3),irt_rtp_smp_stack(np_smp),ncomp), intent(inout) X_rtp, type(work_for_sgl_fftw), intent(inout) FFTW_t)
Definition at line 166 of file t_MHD_multi_FFTW.F90.
References finalize_mhd_multi_fftw_t(), and init_mhd_multi_fftw_t().
Variable Documentation
elapsed_fftw
real(kind = kreal), dimension(3) t_mhd_multi_fftw::elapsed_fftw = (/0.0,0.0,0.0/)
Definition at line 77 of file t_MHD_multi_FFTW.F90.