CALYPSO: parallel_ucd_io_select Module Reference
parallel_ucd_io_select Module Reference
Functions/Subroutines
subroutine set_merged_ucd_file_define (plt, ucd_param)
subroutine set_merged_ucd_file_ctl (default_prefix, file_prefix_ctl, file_format_ctl, ucd_param)
subroutine sel_write_parallel_ucd_file (istep_ucd, ucd_param, t_IO, ucd)
subroutine sel_write_parallel_ucd_mesh (ucd_param, ucd)
subroutine sel_read_parallel_udt_file (istep_ucd, ucd_param, t_IO, ucd)
subroutine sel_read_alloc_para_udt_file (istep_ucd, ucd_param, t_IO, ucd)
Function/Subroutine Documentation
sel_read_alloc_para_udt_file()
subroutine parallel_ucd_io_select::sel_read_alloc_para_udt_file (integer(kind=kint), intent(in) istep_ucd, type(field_io_params), intent(in) ucd_param, type(time_data), intent(inout) t_IO, type(ucd_data), intent(inout) ucd)
Definition at line 345 of file parallel_ucd_IO_select.F90.
References gz_ucd_field_mpi_io_b::gz_rd_alloc_ucd_fld_file_mpi_b(), gz_ucd_field_mpi_io::gz_read_alloc_ucd_fld_file_mpi(), m_field_file_format::iflag_sgl_bin, m_field_file_format::iflag_sgl_bin_gz, m_field_file_format::iflag_sgl_gz, m_field_file_format::iflag_sgl_hdf5, m_field_file_format::iflag_sgl_ucd, m_field_file_format::iflag_sgl_ucd_bin, m_field_file_format::iflag_sgl_ucd_bin_gz, m_field_file_format::iflag_sgl_ucd_gz, m_field_file_format::iflag_sgl_udt_bin, m_field_file_format::iflag_sgl_udt_bin_gz, m_field_file_format::iflag_sgl_udt_gz, m_field_file_format::iflag_sgl_vtd, m_field_file_format::iflag_sgl_vtd_gz, m_field_file_format::iflag_sgl_vtk, m_field_file_format::iflag_sgl_vtk_gz, m_file_format_switch::iflag_single, calypso_mpi::my_rank, calypso_mpi::nprocs, ucd_field_mpi_io::read_alloc_ucd_fld_file_mpi(), ucd_field_mpi_io_b::read_alloc_ucd_fld_file_mpi_b(), and ucd_io_select::sel_read_alloc_udt_file().
Referenced by output_parallel_ucd_file::add_ucd_to_data(), output_parallel_ucd_file::set_data_by_read_ucd_once(), and output_parallel_ucd_file::subtract_by_ucd_data().
sel_read_parallel_udt_file()
subroutine parallel_ucd_io_select::sel_read_parallel_udt_file (integer(kind=kint), intent(in) istep_ucd, type(field_io_params), intent(in) ucd_param, type(time_data), intent(inout) t_IO, type(ucd_data), intent(inout) ucd)
Definition at line 282 of file parallel_ucd_IO_select.F90.
References gz_ucd_field_mpi_io::gz_read_ucd_field_file_mpi(), gz_ucd_field_mpi_io_b::gz_read_ucd_field_file_mpi_b(), m_field_file_format::iflag_sgl_bin, m_field_file_format::iflag_sgl_bin_gz, m_field_file_format::iflag_sgl_gz, m_field_file_format::iflag_sgl_hdf5, m_field_file_format::iflag_sgl_ucd, m_field_file_format::iflag_sgl_ucd_bin, m_field_file_format::iflag_sgl_ucd_bin_gz, m_field_file_format::iflag_sgl_ucd_gz, m_field_file_format::iflag_sgl_udt_bin, m_field_file_format::iflag_sgl_udt_bin_gz, m_field_file_format::iflag_sgl_udt_gz, m_field_file_format::iflag_sgl_vtd, m_field_file_format::iflag_sgl_vtd_gz, m_field_file_format::iflag_sgl_vtk, m_field_file_format::iflag_sgl_vtk_gz, m_file_format_switch::iflag_single, calypso_mpi::my_rank, calypso_mpi::nprocs, ucd_field_mpi_io::read_ucd_field_file_mpi(), ucd_field_mpi_io_b::read_ucd_field_file_mpi_b(), and ucd_io_select::sel_read_udt_file().
Referenced by output_parallel_ucd_file::set_data_by_read_ucd().
sel_write_parallel_ucd_file()
subroutine parallel_ucd_io_select::sel_write_parallel_ucd_file (integer(kind=kint), intent(in) istep_ucd, type(field_io_params), intent(in) ucd_param, type(time_data), intent(in) t_IO, type(ucd_data), intent(in) ucd)
Definition at line 102 of file parallel_ucd_IO_select.F90.
References gz_ucd_field_mpi_io::gz_write_ucd_field_file_mpi(), gz_ucd_field_mpi_io_b::gz_write_ucd_field_file_mpi_b(), gz_merged_udt_vtk_file_io::gz_write_ucd_file_mpi(), gz_write_udt_file_io_b::gz_write_ucd_file_mpi_b(), gz_merged_udt_vtk_file_io::gz_write_ucd_phys_mpi(), gz_write_udt_file_io_b::gz_write_ucd_phys_mpi_b(), gz_merged_udt_vtk_file_io::gz_write_vtk_file_mpi(), gz_merged_udt_vtk_file_io::gz_write_vtk_phys_mpi(), m_field_file_format::iflag_sgl_bin, m_field_file_format::iflag_sgl_bin_gz, m_field_file_format::iflag_sgl_gz, m_field_file_format::iflag_sgl_hdf5, m_field_file_format::iflag_sgl_ucd, m_field_file_format::iflag_sgl_ucd_bin, m_field_file_format::iflag_sgl_ucd_bin_gz, m_field_file_format::iflag_sgl_ucd_gz, m_field_file_format::iflag_sgl_udt, m_field_file_format::iflag_sgl_udt_bin, m_field_file_format::iflag_sgl_udt_bin_gz, m_field_file_format::iflag_sgl_udt_gz, m_field_file_format::iflag_sgl_vtd, m_field_file_format::iflag_sgl_vtd_gz, m_field_file_format::iflag_sgl_vtk, m_field_file_format::iflag_sgl_vtk_gz, m_file_format_switch::iflag_single, m_field_file_format::iflag_ucd_bin, m_field_file_format::iflag_ucd_bin_gz, m_field_file_format::iflag_udt_bin, m_field_file_format::iflag_udt_bin_gz, m_field_file_format::iflag_vtd, m_field_file_format::iflag_vtd_gz, m_field_file_format::iflag_vtk, m_field_file_format::iflag_vtk_gz, calypso_mpi::my_rank, calypso_mpi::nprocs, hdf5_file_io::parallel_write_hdf5_field_file(), hdf5_file_io::parallel_write_xdmf_evo_file(), hdf5_file_io::parallel_write_xdmf_snap_file(), ucd_io_select::sel_write_ucd_file(), gz_vtk_file_io::write_gz_parallel_vtk_file(), gz_vtk_file_io::write_gz_vtk_file(), gz_vtk_file_io::write_gz_vtk_phys(), vtk_file_io::write_parallel_vtk_file(), ucd_field_mpi_io::write_ucd_field_file_mpi(), ucd_field_mpi_io_b::write_ucd_field_file_mpi_b(), merged_udt_vtk_file_io::write_ucd_file_mpi(), write_udt_file_io_b::write_ucd_file_mpi_b(), merged_udt_vtk_file_io::write_ucd_phys_mpi(), write_udt_file_io_b::write_ucd_phys_mpi_b(), vtk_file_io::write_vtk_file(), merged_udt_vtk_file_io::write_vtk_file_mpi(), vtk_file_io::write_vtk_phys(), and merged_udt_vtk_file_io::write_vtk_phys_mpi().
Referenced by output_parallel_ucd_file::link_output_ucd_file_once(), output_4_psf::output_isosurface(), output_4_psf::output_section_data(), output_parallel_ucd_file::output_udt_one_snapshot(), t_ucd_file::s_output_ucd_file_control(), and t_viz_vtk_convert::visualize_convert_vtk().
sel_write_parallel_ucd_mesh()
subroutine parallel_ucd_io_select::sel_write_parallel_ucd_mesh (type(field_io_params), intent(in) ucd_param, type(ucd_data), intent(in) ucd)
Definition at line 217 of file parallel_ucd_IO_select.F90.
References gz_merged_udt_vtk_file_io::gz_write_ucd_grid_mpi(), gz_write_udt_file_io_b::gz_write_ucd_grid_mpi_b(), gz_merged_udt_vtk_file_io::gz_write_vtk_grid_mpi(), m_field_file_format::iflag_sgl_bin, m_field_file_format::iflag_sgl_bin_gz, m_field_file_format::iflag_sgl_gz, m_field_file_format::iflag_sgl_hdf5, m_field_file_format::iflag_sgl_udt, m_field_file_format::iflag_sgl_udt_bin, m_field_file_format::iflag_sgl_udt_bin_gz, m_field_file_format::iflag_sgl_udt_gz, m_field_file_format::iflag_sgl_vtd, m_field_file_format::iflag_sgl_vtd_gz, m_file_format_switch::iflag_single, m_field_file_format::iflag_udt_bin, m_field_file_format::iflag_udt_bin_gz, calypso_mpi::my_rank, hdf5_file_io::parallel_write_hdf5_mesh_file(), ucd_io_select::sel_write_grd_file(), merged_udt_vtk_file_io::write_ucd_grid_mpi(), write_udt_file_io_b::write_ucd_grid_mpi_b(), and merged_udt_vtk_file_io::write_vtk_grid_mpi().
Referenced by output_parallel_ucd_file::link_output_grd_file(), and output_4_psf::output_section_mesh().
set_merged_ucd_file_ctl()
subroutine parallel_ucd_io_select::set_merged_ucd_file_ctl (character(len = kchara), intent(in) default_prefix, type(read_character_item), intent(in) file_prefix_ctl, type(read_character_item), intent(in) file_format_ctl, type(field_io_params), intent(inout) ucd_param)
Definition at line 74 of file parallel_ucd_IO_select.F90.
References m_field_file_format::choose_para_fld_file_format().
Referenced by t_control_param_assemble::set_assemble_ucd_file_param(), and set_merged_ucd_file_define().
set_merged_ucd_file_define()
subroutine parallel_ucd_io_select::set_merged_ucd_file_define (type(platform_data_control), intent(in) plt, type(field_io_params), intent(inout) ucd_param)
Definition at line 57 of file parallel_ucd_IO_select.F90.
References set_merged_ucd_file_ctl().
Referenced by set_control_sph_mhd::set_control_4_sph_mhd().