CALYPSO: rst_data_io_by_fld Module Reference
rst_data_io_by_fld Module Reference
read restart file
Functions/Subroutines
subroutine read_rst_file (id_rank, file_name, t_IO, fld_IO)
subroutine read_rst_data_comps (id_rank, file_name, t_IO, fld_IO)
subroutine, private read_rst_field_comps (fld_IO)
Detailed Description
read restart file
      subroutine read_rst_file(id_rank, file_name, t_IO, fld_IO)
      subroutine read_rst_data_comps(id_rank, file_name, t_IO, fld_IO)
        type(time_data), intent(inout) :: t_IO
        type(field_IO), intent(inout) :: fld_IO
Function/Subroutine Documentation
read_rst_data_comps()
subroutine rst_data_io_by_fld::read_rst_data_comps (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO)
Definition at line 69 of file rst_data_IO_by_fld.f90.
References t_field_data_io::alloc_phys_name_io(), t_field_data_io::cal_istack_phys_comp_io(), m_machine_parameter::i_debug, t_field_data_io::id_phys_file, read_rst_field_comps(), time_data_io::read_step_data(), and skip_comment_f::skip_comment().
Referenced by input_old_file_sel_4_zlib::sel_read_rst_comps().
read_rst_field_comps()
subroutine, private rst_data_io_by_fld::read_rst_field_comps (type(field_io), intent(inout) fld_IO) private
Definition at line 105 of file rst_data_IO_by_fld.f90.
References t_field_data_io::id_phys_file, set_restart_data::set_num_comps_4_rst(), and skip_comment_f::skip_comment().
Referenced by read_rst_data_comps().
read_rst_file()
subroutine rst_data_io_by_fld::read_rst_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO)
Definition at line 35 of file rst_data_IO_by_fld.f90.
References transfer_to_long_integers::cast_long(), m_machine_parameter::i_debug, t_field_data_io::id_phys_file, field_data_io::read_field_data(), time_data_io::read_step_data(), and skip_comment_f::skip_comment().
Referenced by input_old_file_sel_4_zlib::sel_read_rst_file().