CALYPSO: gz_mpi_sph_modes_data_io Module Reference
gz_mpi_sph_modes_data_io Module Reference
ASCII spectr data IO routines.
Functions/Subroutines
subroutine gz_mpi_read_geom_rtp_data (IO_param, comm_IO, sph_IO, sph_grps_IO)
subroutine gz_mpi_read_spectr_rj_data (IO_param, comm_IO, sph_IO, sph_grps_IO)
subroutine gz_mpi_read_geom_rtm_data (IO_param, comm_IO, sph_IO)
subroutine gz_mpi_read_modes_rlm_data (IO_param, comm_IO, sph_IO)
subroutine gz_mpi_write_geom_rtp_data (IO_param, comm_IO, sph_IO, sph_grps_IO)
subroutine gz_mpi_write_spectr_rj_data (IO_param, comm_IO, sph_IO, sph_grps_IO)
subroutine gz_mpi_write_geom_rtm_data (IO_param, comm_IO, sph_IO)
subroutine gz_mpi_write_modes_rlm_data (IO_param, comm_IO, sph_IO)
Detailed Description
ASCII spectr data IO routines.
      subroutine gz_mpi_read_geom_rtp_data                            &
     &         (IO_param, comm_IO, sph_IO, sph_grps_IO)
      subroutine gz_mpi_read_spectr_rj_data                           &
     &         (IO_param, comm_IO, sph_IO, sph_grps_IO)
      subroutine gz_mpi_read_geom_rtm_data                            &
     &         (IO_param, comm_IO, sph_IO)
      subroutine gz_mpi_read_modes_rlm_data                           &
     &         (IO_param, comm_IO, sph_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(communication_table), intent(inout) :: comm_IO
        type(sph_IO_data), intent(inout) :: sph_IO
        type(sph_group_data), intent(inout) :: sph_grps_IO
      subroutine gz_mpi_write_geom_rtp_data                           &
     &         (IO_param, comm_IO, sph_IO, sph_grps_IO)
      subroutine gz_mpi_write_spectr_rj_data                          &
     &         (IO_param, comm_IO, sph_IO, sph_grps_IO)
      subroutine gz_mpi_write_geom_rtm_data                           &
     &         (IO_param, comm_IO, sph_IO)
      subroutine gz_mpi_write_modes_rlm_data                          &
     &         (IO_param, comm_IO, sph_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(communication_table), intent(in) :: comm_IO
        type(sph_IO_data), intent(in) :: sph_IO
        type(sph_group_data), intent(in) :: sph_grps_IO
Function/Subroutine Documentation
gz_mpi_read_geom_rtm_data()
subroutine gz_mpi_sph_modes_data_io::gz_mpi_read_geom_rtm_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(inout) comm_IO, type(sph_io_data), intent(inout) sph_IO)
Definition at line 137 of file gz_MPI_sph_modes_data_IO.f90.
References gz_mpi_domain_data_io::gz_mpi_read_domain_info(), gz_mpi_spherical_model_io::gz_mpi_read_gl_nodes_sph(), gz_mpi_spherical_model_io::gz_mpi_read_gl_reso_sph(), gz_mpi_domain_data_io::gz_mpi_read_import_data(), gz_mpi_spherical_model_io::gz_mpi_read_rank_4_sph(), gz_mpi_sph_gl_1d_idx_io::gz_mpi_read_rtp_gl_1d_table(), gz_mpi_ascii_data_io::gz_mpi_skip_header(), m_sph_modes_grid_labels::hd_rtp_comm(), m_sph_modes_grid_labels::hd_rtp_glbl(), and m_sph_modes_grid_labels::hd_sph_para().
Referenced by gz_mpi_sph_modes_file_io::gz_mpi_read_geom_rtm_file().
gz_mpi_read_geom_rtp_data()
subroutine gz_mpi_sph_modes_data_io::gz_mpi_read_geom_rtp_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(inout) comm_IO, type(sph_io_data), intent(inout) sph_IO, type(sph_group_data), intent(inout) sph_grps_IO)
Definition at line 61 of file gz_MPI_sph_modes_data_IO.f90.
References gz_mpi_domain_data_io::gz_mpi_read_domain_info(), gz_mpi_spherical_model_io::gz_mpi_read_gl_nodes_sph(), gz_mpi_spherical_model_io::gz_mpi_read_gl_reso_sph(), gz_mpi_groups_io::gz_mpi_read_group_data(), gz_mpi_domain_data_io::gz_mpi_read_import_data(), gz_mpi_spherical_model_io::gz_mpi_read_rank_4_sph(), gz_mpi_sph_gl_1d_idx_io::gz_mpi_read_rtp_gl_1d_table(), gz_mpi_ascii_data_io::gz_mpi_skip_header(), m_sph_modes_grid_labels::hd_grphd(), m_sph_modes_grid_labels::hd_ngrphd(), m_sph_modes_grid_labels::hd_pgrphd(), m_sph_modes_grid_labels::hd_rgrphd(), m_sph_modes_grid_labels::hd_rtp_comm(), m_sph_modes_grid_labels::hd_rtp_glbl(), m_sph_modes_grid_labels::hd_sph_para(), and m_sph_modes_grid_labels::hd_tgrphd().
Referenced by gz_mpi_sph_modes_file_io::gz_mpi_read_geom_rtp_file().
gz_mpi_read_modes_rlm_data()
subroutine gz_mpi_sph_modes_data_io::gz_mpi_read_modes_rlm_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(inout) comm_IO, type(sph_io_data), intent(inout) sph_IO)
Definition at line 164 of file gz_MPI_sph_modes_data_IO.f90.
References gz_mpi_domain_data_io::gz_mpi_read_domain_info(), gz_mpi_spherical_model_io::gz_mpi_read_gl_nodes_sph(), gz_mpi_spherical_model_io::gz_mpi_read_gl_reso_sph(), gz_mpi_domain_data_io::gz_mpi_read_import_data(), gz_mpi_spherical_model_io::gz_mpi_read_rank_4_sph(), gz_mpi_sph_gl_1d_idx_io::gz_mpi_read_rj_gl_1d_table(), gz_mpi_ascii_data_io::gz_mpi_skip_header(), m_sph_modes_grid_labels::hd_rj_comm(), m_sph_modes_grid_labels::hd_rlm_glbl(), and m_sph_modes_grid_labels::hd_sph_para().
Referenced by gz_mpi_sph_modes_file_io::gz_mpi_read_modes_rlm_file().
gz_mpi_read_spectr_rj_data()
subroutine gz_mpi_sph_modes_data_io::gz_mpi_read_spectr_rj_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(inout) comm_IO, type(sph_io_data), intent(inout) sph_IO, type(sph_group_data), intent(inout) sph_grps_IO)
Definition at line 102 of file gz_MPI_sph_modes_data_IO.f90.
References gz_mpi_domain_data_io::gz_mpi_read_domain_info(), gz_mpi_spherical_model_io::gz_mpi_read_gl_nodes_sph(), gz_mpi_spherical_model_io::gz_mpi_read_gl_reso_sph(), gz_mpi_groups_io::gz_mpi_read_group_data(), gz_mpi_domain_data_io::gz_mpi_read_import_data(), gz_mpi_spherical_model_io::gz_mpi_read_rank_4_sph(), gz_mpi_sph_gl_1d_idx_io::gz_mpi_read_rj_gl_1d_table(), gz_mpi_ascii_data_io::gz_mpi_skip_header(), m_sph_modes_grid_labels::hd_grphd(), m_sph_modes_grid_labels::hd_jgrphd(), m_sph_modes_grid_labels::hd_kgrphd(), m_sph_modes_grid_labels::hd_rj_comm(), m_sph_modes_grid_labels::hd_rj_glbl(), and m_sph_modes_grid_labels::hd_sph_para().
Referenced by gz_mpi_sph_modes_file_io::gz_mpi_read_spectr_rj_file().
gz_mpi_write_geom_rtm_data()
subroutine gz_mpi_sph_modes_data_io::gz_mpi_write_geom_rtm_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(in) comm_IO, type(sph_io_data), intent(in) sph_IO)
Definition at line 282 of file gz_MPI_sph_modes_data_IO.f90.
References gz_mpi_ascii_data_io::gz_mpi_write_charahead(), gz_mpi_domain_data_io::gz_mpi_write_domain_info(), gz_mpi_spherical_model_io::gz_mpi_write_gl_nodes_sph(), gz_mpi_spherical_model_io::gz_mpi_write_gl_reso_sph(), gz_mpi_domain_data_io::gz_mpi_write_import_data(), gz_mpi_spherical_model_io::gz_mpi_write_rank_4_sph(), gz_mpi_sph_gl_1d_idx_io::gz_mpi_write_rtp_gl_1d_table(), m_sph_modes_grid_labels::hd_rtp_comm(), m_sph_modes_grid_labels::hd_rtp_glbl(), and m_sph_modes_grid_labels::hd_sph_para().
Referenced by gz_mpi_sph_modes_file_io::gz_mpi_write_geom_rtm_file().
gz_mpi_write_geom_rtp_data()
subroutine gz_mpi_sph_modes_data_io::gz_mpi_write_geom_rtp_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(in) comm_IO, type(sph_io_data), intent(in) sph_IO, type(sph_group_data), intent(in) sph_grps_IO)
Definition at line 192 of file gz_MPI_sph_modes_data_IO.f90.
References gz_mpi_ascii_data_io::gz_mpi_write_charahead(), gz_mpi_domain_data_io::gz_mpi_write_domain_info(), gz_mpi_spherical_model_io::gz_mpi_write_gl_nodes_sph(), gz_mpi_spherical_model_io::gz_mpi_write_gl_reso_sph(), gz_mpi_groups_io::gz_mpi_write_grp_data(), gz_mpi_domain_data_io::gz_mpi_write_import_data(), gz_mpi_spherical_model_io::gz_mpi_write_rank_4_sph(), gz_mpi_sph_gl_1d_idx_io::gz_mpi_write_rtp_gl_1d_table(), m_sph_modes_grid_labels::hd_grphd(), m_sph_modes_grid_labels::hd_ngrphd(), m_sph_modes_grid_labels::hd_pgrphd(), m_sph_modes_grid_labels::hd_rgrphd(), m_sph_modes_grid_labels::hd_rtp_comm(), m_sph_modes_grid_labels::hd_rtp_glbl(), m_sph_modes_grid_labels::hd_sph_para(), and m_sph_modes_grid_labels::hd_tgrphd().
Referenced by gz_mpi_sph_modes_file_io::gz_mpi_write_geom_rtp_file().
gz_mpi_write_modes_rlm_data()
subroutine gz_mpi_sph_modes_data_io::gz_mpi_write_modes_rlm_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(in) comm_IO, type(sph_io_data), intent(in) sph_IO)
Definition at line 312 of file gz_MPI_sph_modes_data_IO.f90.
References gz_mpi_ascii_data_io::gz_mpi_write_charahead(), gz_mpi_domain_data_io::gz_mpi_write_domain_info(), gz_mpi_spherical_model_io::gz_mpi_write_gl_nodes_sph(), gz_mpi_spherical_model_io::gz_mpi_write_gl_reso_sph(), gz_mpi_domain_data_io::gz_mpi_write_import_data(), gz_mpi_spherical_model_io::gz_mpi_write_rank_4_sph(), gz_mpi_sph_gl_1d_idx_io::gz_mpi_write_rj_gl_1d_table(), m_sph_modes_grid_labels::hd_rj_comm(), m_sph_modes_grid_labels::hd_rlm_glbl(), and m_sph_modes_grid_labels::hd_sph_para().
Referenced by gz_mpi_sph_modes_file_io::gz_mpi_write_modes_rlm_file().
gz_mpi_write_spectr_rj_data()
subroutine gz_mpi_sph_modes_data_io::gz_mpi_write_spectr_rj_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(in) comm_IO, type(sph_io_data), intent(in) sph_IO, type(sph_group_data), intent(in) sph_grps_IO)
Definition at line 241 of file gz_MPI_sph_modes_data_IO.f90.
References gz_mpi_ascii_data_io::gz_mpi_write_charahead(), gz_mpi_domain_data_io::gz_mpi_write_domain_info(), gz_mpi_spherical_model_io::gz_mpi_write_gl_nodes_sph(), gz_mpi_spherical_model_io::gz_mpi_write_gl_reso_sph(), gz_mpi_groups_io::gz_mpi_write_grp_data(), gz_mpi_domain_data_io::gz_mpi_write_import_data(), gz_mpi_spherical_model_io::gz_mpi_write_rank_4_sph(), gz_mpi_sph_gl_1d_idx_io::gz_mpi_write_rj_gl_1d_table(), m_sph_modes_grid_labels::hd_grphd(), m_sph_modes_grid_labels::hd_jgrphd(), m_sph_modes_grid_labels::hd_kgrphd(), m_sph_modes_grid_labels::hd_rj_comm(), m_sph_modes_grid_labels::hd_rj_glbl(), and m_sph_modes_grid_labels::hd_sph_para().
Referenced by gz_mpi_sph_modes_file_io::gz_mpi_write_spectr_rj_file().