CALYPSO: gz_mpi_vectors_io Module Reference
gz_mpi_vectors_io Module Reference
Mesh file IO for gxipped format.
Functions/Subroutines
subroutine gz_mpi_read_scalar (IO_param, nnod, scalar)
subroutine gz_mpi_read_vector (IO_param, nnod, numdir, vect)
subroutine gz_mpi_write_scalar (IO_param, nnod, scalar)
subroutine gz_mpi_write_vector (IO_param, nnod, numdir, vect)
Variables
type(buffer_4_gzip) zbuf
Detailed Description
Mesh file IO for gxipped format.
      subroutine gz_mpi_read_scalar(IO_param, nnod, scalar)
      subroutine gz_mpi_read_vector(IO_param, nnod, numdir, vect)
      subroutine gz_mpi_write_scalar(IO_param, nnod, scalar)
      subroutine gz_mpi_write_vector(IO_param, nnod, numdir, vect)
Function/Subroutine Documentation
gz_mpi_read_scalar()
subroutine gz_mpi_vectors_io::gz_mpi_read_scalar (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint_gl), intent(in) nnod, real(kind=kreal), dimension(nnod), intent(inout) scalar)
Definition at line 38 of file gz_MPI_vectors_IO.f90.
References gz_mpi_read_vector(), and m_constants::ione.
Referenced by gz_mpi_node_geometry_io::gz_mpi_read_scl_in_ele().
gz_mpi_read_vector()
subroutine gz_mpi_vectors_io::gz_mpi_read_vector (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint_gl), intent(in) nnod, integer(kind=kint), intent(in) numdir, real(kind=kreal), dimension(nnod, numdir), intent(inout) vect)
Definition at line 51 of file gz_MPI_vectors_IO.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), gz_mpi_ascii_data_io::gz_mpi_read_charahead(), zlib_convert_ascii_vector::infleate_vector_txt(), m_constants::ione, and gz_mpi_domain_data_io::zbuf.
Referenced by gz_mpi_read_scalar(), and gz_mpi_node_geometry_io::gz_mpi_read_vect_in_ele().
gz_mpi_write_scalar()
subroutine gz_mpi_vectors_io::gz_mpi_write_scalar (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint_gl), intent(in) nnod, real(kind=kreal), dimension(nnod), intent(in) scalar)
Definition at line 88 of file gz_MPI_vectors_IO.f90.
References gz_mpi_write_vector(), and m_constants::ione.
Referenced by gz_mpi_node_geometry_io::gz_mpi_write_scl_in_ele().
gz_mpi_write_vector()
subroutine gz_mpi_vectors_io::gz_mpi_write_vector (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint_gl), intent(in) nnod, integer(kind=kint), intent(in) numdir, real(kind=kreal), dimension(nnod, numdir), intent(in) vect)
Definition at line 101 of file gz_MPI_vectors_IO.f90.
References t_buffer_4_gzip::dealloc_zip_buffer(), zlib_convert_ascii_vector::defleate_vector_txt(), gz_mpi_ascii_data_io::gz_mpi_write_stack_over_domain(), m_constants::ione, and gz_mpi_domain_data_io::zbuf.
Referenced by gz_mpi_write_scalar(), and gz_mpi_node_geometry_io::gz_mpi_write_vect_in_ele().
Variable Documentation
zbuf
type(buffer_4_gzip) gz_mpi_vectors_io::zbuf
Definition at line 30 of file gz_MPI_vectors_IO.f90.