CALYPSO: const_global_sph_grids_modes Module Reference
const_global_sph_grids_modes Module Reference
Set global spherical harmonics ID.
Functions/Subroutines
subroutine s_const_global_sph_grids_modes (sph_params, sph_rtp, sph_rtm, sph_rj, s3d_ranks, sph_lcp, stk_lc1d, sph_gl1d)
subroutine const_global_sph_fem_grid (sph_params, sph_rtp, sph_rj, s3d_ranks, sph_lcp, stk_lc1d, sph_gl1d)
Variables
type(sph_local_1d_param), save, private sph_lc1_sp
type(sph_trans_2d_table), save, private s2d_tbl_sp
type(sph_local_default_bc), save sph_dbc_sp
Detailed Description
Set global spherical harmonics ID.
      subroutine s_const_global_sph_grids_modes                       &
     &         (sph_params, sph_rtp, sph_rtm, sph_rj, s3d_ranks,      &
     &          sph_lcp, stk_lc1d, sph_gl1d)
      subroutine const_global_sph_FEM_grid                            &
     &         (sph_params, sph_rtp, sph_rj, s3d_ranks,               &
     &          sph_lcp, stk_lc1d, sph_gl1d)
        type(sph_shell_parameters), intent(in) :: sph_params
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_rtm_grid), intent(in) :: sph_rtm
        type(sph_rj_grid), intent(in) :: sph_rj
        type(spheric_global_rank), intent(inout) :: s3d_ranks
        type(sph_local_parameters), intent(inout) :: sph_lcp
        type(sph_1d_index_stack), intent(inout) :: stk_lc1d
        type(sph_1d_global_index), intent(inout) :: sph_gl1d
Parameters
ip_rank process ID
Function/Subroutine Documentation
const_global_sph_fem_grid()
subroutine const_global_sph_grids_modes::const_global_sph_fem_grid (type(sph_shell_parameters), intent(in) sph_params, type(sph_rtp_grid), intent(in) sph_rtp, type(sph_rj_grid), intent(in) sph_rj, type(spheric_global_rank), intent(inout) s3d_ranks, type(sph_local_parameters), intent(inout) sph_lcp, type(sph_1d_index_stack), intent(inout) stk_lc1d, type(sph_1d_global_index), intent(inout) sph_gl1d)
Definition at line 145 of file const_global_sph_grids_modes.f90.
References t_2d_sph_trans_table::alloc_2d_sph_trans_table(), t_sph_local_parameter::alloc_nidx_local(), t_spheric_global_ranks::alloc_sph_1d_domain_id(), t_sph_1d_global_index::alloc_sph_1d_global_idx(), t_sph_1d_global_index::alloc_sph_1d_global_stack(), t_sph_local_parameter::alloc_sph_gl_bc_param(), t_sph_local_parameter::alloc_sph_gl_parameter(), t_spheric_global_ranks::alloc_sph_ranks(), const_each_global_sph_list::const_global_rtp_grids(), t_2d_sph_trans_table::dealloc_2d_sph_trans_table(), t_sph_local_parameter::dealloc_nidx_local(), t_sph_local_parameter::dealloc_sph_gl_bc_param(), m_machine_parameter::iflag_debug, s2d_tbl_sp, set_sph_1d_domain_id::set_sph_1d_domain_id_rtp(), set_sph_1d_global_index::set_sph_1d_global_idx_rtp(), set_sph_tranform_ordering::set_trans_table_fft_2_lgd(), sph_dbc_sp, and sph_lc1_sp.
s_const_global_sph_grids_modes()
subroutine const_global_sph_grids_modes::s_const_global_sph_grids_modes (type(sph_shell_parameters), intent(in) sph_params, type(sph_rtp_grid), intent(in) sph_rtp, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rj_grid), intent(in) sph_rj, type(spheric_global_rank), intent(inout) s3d_ranks, type(sph_local_parameters), intent(inout) sph_lcp, type(sph_1d_index_stack), intent(inout) stk_lc1d, type(sph_1d_global_index), intent(inout) sph_gl1d)
Definition at line 60 of file const_global_sph_grids_modes.f90.
References t_2d_sph_trans_table::alloc_2d_sph_trans_table(), t_sph_local_parameter::alloc_nidx_local(), t_spheric_global_ranks::alloc_sph_1d_domain_id(), t_sph_1d_global_index::alloc_sph_1d_global_idx(), t_sph_1d_global_index::alloc_sph_1d_global_stack(), t_sph_local_parameter::alloc_sph_gl_bc_param(), t_sph_local_parameter::alloc_sph_gl_parameter(), t_spheric_global_ranks::alloc_sph_ranks(), const_each_global_sph_list::const_global_rj_modes_by_rlm(), const_each_global_sph_list::const_global_rlm_modes(), const_each_global_sph_list::const_global_rtm_grids(), const_each_global_sph_list::const_global_rtp_grids(), t_2d_sph_trans_table::dealloc_2d_sph_trans_table(), t_sph_local_parameter::dealloc_nidx_local(), t_sph_local_parameter::dealloc_sph_gl_bc_param(), m_machine_parameter::iflag_debug, s2d_tbl_sp, set_sph_1d_domain_id::set_sph_1d_domain_id_rj(), set_sph_1d_domain_id::set_sph_1d_domain_id_rtp(), set_sph_1d_global_index::set_sph_1d_global_idx_rj(), set_sph_1d_global_index::set_sph_1d_global_idx_rlm(), set_sph_1d_global_index::set_sph_1d_global_idx_rtm(), set_sph_1d_global_index::set_sph_1d_global_idx_rtp(), set_sph_tranform_ordering::set_trans_table_fft_2_lgd(), sph_dbc_sp, and sph_lc1_sp.
Referenced by mpi_gen_sph_grids_modes::const_sph_global_parameters().
Variable Documentation
s2d_tbl_sp
type(sph_trans_2d_table), save, private const_global_sph_grids_modes::s2d_tbl_sp private
Definition at line 49 of file const_global_sph_grids_modes.f90.
Referenced by const_global_sph_fem_grid(), and s_const_global_sph_grids_modes().
sph_dbc_sp
type(sph_local_default_bc), save const_global_sph_grids_modes::sph_dbc_sp
Definition at line 50 of file const_global_sph_grids_modes.f90.
Referenced by const_global_sph_fem_grid(), and s_const_global_sph_grids_modes().
sph_lc1_sp
type(sph_local_1d_param), save, private const_global_sph_grids_modes::sph_lc1_sp private
Definition at line 48 of file const_global_sph_grids_modes.f90.
Referenced by const_global_sph_fem_grid(), and s_const_global_sph_grids_modes().