CALYPSO: t_boundary_params_sph_mhd Module Reference
t_boundary_params_sph_mhd Module Reference
Structure for basic boundary conditions for spherical dynamo.
Data Types
type sph_boundary_type
Structure for basic boundary condition parameters.
Functions/Subroutines
subroutine cal_fdm_coefs_4_bcs (nri, radius, sph_bc)
subroutine check_fdm_coefs_4_bc2 (label, sph_bc)
Variables
integer(kind=kint), parameter iflag_undefined_bc = -1
integer flag for undefined boundary
integer(kind=kint), parameter iflag_fixed_field = 0
integer flag for fixed boundary
integer(kind=kint), parameter iflag_fixed_flux = 1
integer flag for fixed flux boundary
integer(kind=kint), parameter iflag_sph_fill_center = 41
integer flag for whole sphere model
integer(kind=kint), parameter iflag_sph_fix_center = 42
integer flag for whole sphere model
integer(kind=kint), parameter iflag_evolve_field = 50
integer flag for fixed drifting boundary
integer(kind=kint), parameter iflag_evolve_flux = 51
integer flag for fixed drifting flux
integer(kind=kint), parameter iflag_fixed_velo = 100
integer flag for fixed velocity boundary at inner core
integer(kind=kint), parameter iflag_free_slip = 101
integer flag for free-slip boundary at inner core
integer(kind=kint), parameter iflag_rotatable_ic = 110
integer flag for rotatable inner core
integer(kind=kint), parameter iflag_sph_insulator = 200
integer flag for insulated magnetic boundary
integer(kind=kint), parameter iflag_radial_magne = 201
integer flag for pseudo vacuum magnetic boundary
Detailed Description
Structure for basic boundary conditions for spherical dynamo.
      subroutine cal_fdm_coefs_4_BCs(nri, radius, sph_bc)
      subroutine check_fdm_coefs_4_BC2(label, sph_bc)
        type(sph_boundary_type), intent(inout) :: sph_bc
Parameters
jmax number of modes for spherical harmonics \(L*(L+2)\)
nri number of radial grid points
radius radius
j_rj local spherical harmionics modes for f(r,j)
Function/Subroutine Documentation
cal_fdm_coefs_4_bcs()
subroutine t_boundary_params_sph_mhd::cal_fdm_coefs_4_bcs (integer(kind = kint), intent(in) nri, real(kind = kreal), dimension(nri), intent(in) radius, type(sph_boundary_type), intent(inout) sph_bc)
Definition at line 107 of file t_boundary_params_sph_MHD.f90.
References cal_fdm_coefs_4_boundaries::cal_fdm1_coef_fix_fld_cmb(), cal_fdm_coefs_4_boundaries::cal_fdm1_coef_fix_fld_icb(), cal_fdm_coefs_4_boundaries::cal_fdm2_coef_fix_df_cmb(), cal_fdm_coefs_4_boundaries::cal_fdm2_coef_fix_df_icb(), cal_fdm_coefs_4_boundaries::cal_fdm2_coef_fix_fld_cmb(), and cal_fdm_coefs_4_boundaries::cal_fdm2_coef_fix_fld_icb().
Referenced by set_bc_sph_mhd::s_set_bc_sph_mhd().
check_fdm_coefs_4_bc2()
subroutine t_boundary_params_sph_mhd::check_fdm_coefs_4_bc2 (character(len=kchara), intent(in) label, type(sph_boundary_type), intent(in) sph_bc)
Definition at line 137 of file t_boundary_params_sph_MHD.f90.
Referenced by set_bc_sph_mhd::s_set_bc_sph_mhd().
Variable Documentation
iflag_evolve_field
integer(kind = kint), parameter t_boundary_params_sph_mhd::iflag_evolve_field = 50
integer flag for fixed drifting boundary
Definition at line 39 of file t_boundary_params_sph_MHD.f90.
Referenced by set_reference_sph_mhd::adjust_sph_temp_bc_by_reftemp(), const_r_mat_4_vector_sph::const_radial_mat_4_magne_sph(), select_exp_magne_cmb::sel_cmb_grad_bp_and_current(), select_exp_magne_cmb::sel_cmb_grad_poloidal_magne(), select_exp_velocity_cmb::sel_cmb_grad_poloidal_moment(), select_exp_velocity_cmb::sel_cmb_grad_vp_and_vorticity(), select_exp_magne_cmb::sel_cmb_sph_current(), select_exp_magne_cmb::sel_cmb_sph_magnetic_diffusion(), select_exp_velocity_cmb::sel_cmb_sph_viscous_diffusion(), select_exp_velocity_cmb::sel_cmb_sph_vorticity(), select_exp_magne_icb::sel_icb_grad_bp_and_current(), select_exp_magne_icb::sel_icb_grad_poloidal_magne(), select_exp_velocity_icb::sel_icb_grad_poloidal_moment(), select_exp_velocity_icb::sel_icb_grad_vp_and_vorticity(), select_exp_magne_icb::sel_icb_sph_current(), select_exp_magne_icb::sel_icb_sph_magnetic_diffusion(), select_exp_velocity_icb::sel_icb_sph_viscous_diffusion(), select_exp_velocity_icb::sel_icb_sph_vorticity(), select_exp_scalar_cmb::set_cmb_scalar_sph_crank(), set_evoluved_boundaries::set_evo_scalar_boundaries(), set_evoluved_boundaries::set_evo_vector_boundaries(), and select_exp_scalar_icb::set_icb_scalar_sph_crank().
iflag_evolve_flux
integer(kind = kint), parameter t_boundary_params_sph_mhd::iflag_evolve_flux = 51
integer flag for fixed drifting flux
Definition at line 41 of file t_boundary_params_sph_MHD.f90.
Referenced by set_reference_sph_mhd::adjust_sph_temp_bc_by_reftemp(), const_r_mat_4_scalar_sph::const_radial_mat_4_scalar_sph(), select_exp_scalar_cmb::sel_cmb_radial_grad_scalar(), select_exp_scalar_cmb::sel_cmb_sph_scalar_advect(), select_exp_scalar_cmb::sel_cmb_sph_scalar_diffusion(), select_exp_scalar_icb::sel_icb_radial_grad_scalar(), select_exp_scalar_icb::sel_icb_sph_scalar_advect(), select_exp_scalar_icb::sel_icb_sph_scalar_diffusion(), set_evoluved_boundaries::set_evo_scalar_boundaries(), and set_evoluved_boundaries::set_evo_vector_boundaries().
iflag_fixed_field
integer(kind = kint), parameter t_boundary_params_sph_mhd::iflag_fixed_field = 0
integer flag for fixed boundary
Definition at line 31 of file t_boundary_params_sph_MHD.f90.
Referenced by set_reference_sph_mhd::adjust_sph_temp_bc_by_reftemp(), select_exp_velocity_cmb::sel_cmb_grad_poloidal_moment(), select_exp_velocity_cmb::sel_cmb_grad_vp_and_vorticity(), select_exp_velocity_cmb::sel_cmb_sph_viscous_diffusion(), select_exp_velocity_cmb::sel_cmb_sph_vorticity(), select_exp_velocity_icb::sel_icb_grad_poloidal_moment(), select_exp_velocity_icb::sel_icb_grad_vp_and_vorticity(), select_exp_velocity_icb::sel_icb_sph_viscous_diffusion(), select_exp_velocity_icb::sel_icb_sph_vorticity(), select_exp_scalar_cmb::set_cmb_scalar_sph_crank(), set_bc_sph_scalars::set_homogenious_scalar_bc(), select_exp_scalar_icb::set_icb_scalar_sph_crank(), set_bc_flag_sph_velo::set_sph_velo_cmb_flag(), and set_bc_flag_sph_velo::set_sph_velo_icb_flag().
iflag_fixed_flux
integer(kind = kint), parameter t_boundary_params_sph_mhd::iflag_fixed_flux = 1
integer flag for fixed flux boundary
Definition at line 33 of file t_boundary_params_sph_MHD.f90.
Referenced by set_reference_sph_mhd::adjust_sph_temp_bc_by_reftemp(), const_r_mat_4_scalar_sph::const_radial_mat_4_scalar_sph(), set_bc_sph_scalars::inner_sph_bc_scalar_sph(), select_exp_scalar_cmb::sel_cmb_radial_grad_scalar(), select_exp_scalar_cmb::sel_cmb_sph_scalar_advect(), select_exp_scalar_cmb::sel_cmb_sph_scalar_diffusion(), select_exp_scalar_icb::sel_icb_radial_grad_scalar(), select_exp_scalar_icb::sel_icb_sph_scalar_advect(), select_exp_scalar_icb::sel_icb_sph_scalar_diffusion(), set_bc_sph_scalars::set_homogenious_grad_bc(), and select_exp_scalar_icb::set_icb_scalar_sph_crank().
iflag_fixed_velo
integer(kind = kint), parameter t_boundary_params_sph_mhd::iflag_fixed_velo = 100
integer flag for fixed velocity boundary at inner core
Definition at line 45 of file t_boundary_params_sph_MHD.f90.
Referenced by set_bc_flag_sph_velo::set_sph_velo_cmb_flag(), and set_bc_flag_sph_velo::set_sph_velo_icb_flag().
iflag_free_slip
integer(kind = kint), parameter t_boundary_params_sph_mhd::iflag_free_slip = 101
integer flag for free-slip boundary at inner core
Definition at line 47 of file t_boundary_params_sph_MHD.f90.
Referenced by const_r_mat_4_vector_sph::const_radial_mat_vort_2step(), select_exp_velocity_cmb::sel_cmb_grad_poloidal_moment(), select_exp_velocity_cmb::sel_cmb_grad_vp_and_vorticity(), select_exp_velocity_cmb::sel_cmb_sph_viscous_diffusion(), select_exp_velocity_cmb::sel_cmb_sph_vort_diffusion(), select_exp_velocity_cmb::sel_cmb_sph_vorticity(), select_exp_velocity_icb::sel_icb_grad_poloidal_moment(), select_exp_velocity_icb::sel_icb_grad_vp_and_vorticity(), select_exp_velocity_icb::sel_icb_sph_viscous_diffusion(), select_exp_velocity_icb::sel_icb_sph_vort_diffusion(), select_exp_velocity_icb::sel_icb_sph_vorticity(), set_bc_flag_sph_velo::set_sph_velo_cmb_flag(), and set_bc_flag_sph_velo::set_sph_velo_icb_flag().
iflag_radial_magne
integer(kind = kint), parameter t_boundary_params_sph_mhd::iflag_radial_magne = 201
integer flag for pseudo vacuum magnetic boundary
Definition at line 54 of file t_boundary_params_sph_MHD.f90.
Referenced by const_r_mat_4_vector_sph::const_radial_mat_4_magne_sph(), select_exp_magne_cmb::sel_cmb_grad_bp_and_current(), select_exp_magne_cmb::sel_cmb_grad_poloidal_magne(), select_exp_magne_cmb::sel_cmb_sph_current(), select_exp_magne_cmb::sel_cmb_sph_magnetic_diffusion(), select_exp_magne_cmb::sel_cmb_sph_rotation_uxb(), select_exp_magne_icb::sel_icb_grad_bp_and_current(), select_exp_magne_icb::sel_icb_grad_poloidal_magne(), select_exp_magne_icb::sel_icb_sph_current(), select_exp_magne_icb::sel_icb_sph_magnetic_diffusion(), select_exp_magne_icb::sel_icb_sph_rotation_uxb(), and set_bc_sph_mhd::set_sph_bc_magne_sph().
iflag_rotatable_ic
integer(kind = kint), parameter t_boundary_params_sph_mhd::iflag_rotatable_ic = 110
integer flag for rotatable inner core
Definition at line 49 of file t_boundary_params_sph_MHD.f90.
Referenced by cal_sph_field_by_rotation::cal_rot_of_forces_sph_2(), const_r_mat_4_vector_sph::const_radial_mat_vort_2step(), cal_inner_core_rotation::copy_icore_rot_to_tor_coriolis(), select_exp_velocity_icb::sel_icb_grad_poloidal_moment(), select_exp_velocity_icb::sel_icb_grad_vp_and_vorticity(), select_exp_velocity_icb::sel_icb_sph_viscous_diffusion(), select_exp_velocity_icb::sel_icb_sph_vort_diffusion(), set_bc_flag_sph_velo::set_sph_velo_icb_flag(), t_coriolis_terms_rlm::sum_coriolis_rlm(), and cal_sol_sph_mhd_crank::update_after_vorticity_sph().
iflag_sph_fill_center
integer(kind = kint), parameter t_boundary_params_sph_mhd::iflag_sph_fill_center = 41
integer flag for whole sphere model
Definition at line 35 of file t_boundary_params_sph_MHD.f90.
Referenced by const_r_mat_4_vector_sph::const_radial_mat_4_magne_sph(), const_r_mat_4_scalar_sph::const_radial_mat_4_press_sph(), const_r_mat_4_scalar_sph::const_radial_mat_4_scalar_sph(), const_r_mat_4_vector_sph::const_radial_mat_vort_2step(), const_r_mat_w_center_sph::const_rmat_press00_sph(), const_r_mat_w_center_sph::const_rmat_scalar00_sph(), set_bc_sph_scalars::inner_sph_bc_scalar_sph(), select_exp_magne_icb::sel_icb_grad_bp_and_current(), select_exp_magne_icb::sel_icb_grad_poloidal_magne(), select_exp_velocity_icb::sel_icb_grad_poloidal_moment(), select_exp_velocity_icb::sel_icb_grad_vp_and_vorticity(), select_exp_scalar_icb::sel_icb_radial_grad_scalar(), select_exp_magne_icb::sel_icb_sph_current(), select_exp_magne_icb::sel_icb_sph_magnetic_diffusion(), select_exp_magne_icb::sel_icb_sph_rotation_uxb(), select_exp_scalar_icb::sel_icb_sph_scalar_advect(), select_exp_scalar_icb::sel_icb_sph_scalar_diffusion(), select_exp_velocity_icb::sel_icb_sph_viscous_diffusion(), select_exp_velocity_icb::sel_icb_sph_vort_diffusion(), select_exp_velocity_icb::sel_icb_sph_vorticity(), set_initial_sph_dynamo::set_initial_magne_sph(), set_bc_sph_mhd::set_sph_bc_magne_sph(), and set_bc_flag_sph_velo::set_sph_velo_icb_flag().
iflag_sph_fix_center
integer(kind = kint), parameter t_boundary_params_sph_mhd::iflag_sph_fix_center = 42
integer flag for whole sphere model
Definition at line 37 of file t_boundary_params_sph_MHD.f90.
Referenced by set_reference_sph_mhd::adjust_sph_temp_bc_by_reftemp(), const_r_mat_4_scalar_sph::const_radial_mat_4_scalar_sph(), const_r_mat_w_center_sph::const_rmat_scalar00_sph(), set_bc_sph_scalars::inner_sph_bc_scalar_sph(), select_exp_scalar_icb::sel_icb_radial_grad_scalar(), select_exp_scalar_icb::sel_icb_sph_scalar_advect(), select_exp_scalar_icb::sel_icb_sph_scalar_diffusion(), select_exp_scalar_icb::set_icb_scalar_sph_crank(), set_bc_sph_mhd::set_sph_bc_magne_sph(), and set_bc_flag_sph_velo::set_sph_velo_icb_flag().
iflag_sph_insulator
integer(kind = kint), parameter t_boundary_params_sph_mhd::iflag_sph_insulator = 200
integer flag for insulated magnetic boundary
Definition at line 52 of file t_boundary_params_sph_MHD.f90.
Referenced by const_sph_radial_grad::const_grad_bp_and_current(), const_sph_radial_grad::const_grad_poloidal_magne(), and set_bc_sph_mhd::set_sph_bc_magne_sph().
iflag_undefined_bc
integer(kind = kint), parameter t_boundary_params_sph_mhd::iflag_undefined_bc = -1
integer flag for undefined boundary
Definition at line 29 of file t_boundary_params_sph_MHD.f90.
Referenced by set_bc_sph_scalars::set_sph_bc_composition_sph(), and set_bc_sph_scalars::set_sph_bc_temp_sph().