CALYPSO: circle_transform_single Module Reference
circle_transform_single Module Reference
spherical transform at a specific circle at \((r, theta)\)
Functions/Subroutines
subroutine initialize_circle_transform (iflag_FFT, circle, circ_spec, WK_circle_fft)
subroutine circle_transfer_vector (iflag_FFT, ifld, circle, circ_spec, WK_circle_fft)
subroutine circle_transfer_scalar (iflag_FFT, ifld, circle, circ_spec, WK_circle_fft)
subroutine circle_transfer_sym_tensor (iflag_FFT, ifld, circle, circ_spec, WK_circle_fft)
Variables
type(legendre_polynomials), save, private leg_c
Detailed Description
spherical transform at a specific circle at \((r, theta)\)
      subroutine initialize_circle_transform                          &
     &          (iflag_FFT, circle, circ_spec, WK_circle_fft)
      subroutine circle_transfer_vector                               &
     &         (iflag_FFT, ifld, circle, circ_spec, WK_circle_fft)
      subroutine circle_transfer_scalar                               &
     &         (iflag_FFT, ifld, circle, circ_spec, WK_circle_fft)
      subroutine circle_transfer_sym_tensor                           &
     &         (iflag_FFT, ifld, circle, circ_spec, WK_circle_fft)
        type(fields_on_circle), intent(inout) :: circle
        type(circle_transform_spetr), intent(inout) :: circ_spec
        type(working_FFTs), intent(inout) :: WK_circle_fft
Function/Subroutine Documentation
circle_transfer_scalar()
subroutine circle_transform_single::circle_transfer_scalar (integer(kind = kint), intent(in) iflag_FFT, integer(kind = kint), intent(in) ifld, type(fields_on_circle), intent(inout) circle, type(circle_transform_spetr), intent(inout) circ_spec, type(working_ffts), intent(inout) WK_circle_fft)
Definition at line 148 of file circle_transform_single.f90.
References t_fft_selector::backward_fft_select(), cal_circle_transform::cal_circle_spectrum_vector(), cal_circle_transform::circle_lag_transfer_scalar(), cal_circle_transform::copy_circle_spectrum_4_fft(), m_constants::ione, and m_machine_parameter::np_smp.
Referenced by circle_transfer_sym_tensor(), and t_field_on_circle::sph_transfer_on_circle().
circle_transfer_sym_tensor()
subroutine circle_transform_single::circle_transfer_sym_tensor (integer(kind = kint), intent(in) iflag_FFT, integer(kind = kint), intent(in) ifld, type(fields_on_circle), intent(inout) circle, type(circle_transform_spetr), intent(inout) circ_spec, type(working_ffts), intent(inout) WK_circle_fft)
Definition at line 183 of file circle_transform_single.f90.
References circle_transfer_scalar(), and m_phys_constants::n_sym_tensor.
Referenced by t_field_on_circle::sph_transfer_on_circle().
circle_transfer_vector()
subroutine circle_transform_single::circle_transfer_vector (integer(kind = kint), intent(in) iflag_FFT, integer(kind = kint), intent(in) ifld, type(fields_on_circle), intent(inout) circle, type(circle_transform_spetr), intent(inout) circ_spec, type(working_ffts), intent(inout) WK_circle_fft)
Definition at line 98 of file circle_transform_single.f90.
References t_fft_selector::backward_fft_select(), cal_circle_transform::cal_circle_spectrum_vector(), cal_circle_transform::circle_lag_transfer_vector(), cal_circle_transform::copy_circle_spectrum_4_fft(), t_circle_transform::iflag_circle_cyl, m_constants::ione, m_constants::ithree, m_machine_parameter::np_smp, and cal_circle_transform::overwrt_circle_sph_vect_2_cyl().
Referenced by t_field_on_circle::sph_transfer_on_circle().
initialize_circle_transform()
subroutine circle_transform_single::initialize_circle_transform (integer(kind = kint), intent(in) iflag_FFT, type(fields_on_circle), intent(in) circle, type(circle_transform_spetr), intent(inout) circ_spec, type(working_ffts), intent(inout) WK_circle_fft)
Definition at line 48 of file circle_transform_single.f90.
References t_schmidt_polynomial::alloc_schmidt_polynomial(), t_schmidt_polynomial::dealloc_schmidt_polynomial(), t_schmidt_polynomial::dschmidt(), t_fft_selector::initialize_fft_select(), leg_c, calypso_mpi::my_rank, m_machine_parameter::np_smp, and m_constants::one.
Referenced by t_field_on_circle::const_circle_point_global().
Variable Documentation
leg_c
type(legendre_polynomials), save, private circle_transform_single::leg_c private
Definition at line 37 of file circle_transform_single.f90.
Referenced by initialize_circle_transform().