CALYPSO: m_array_for_send_recv Module Reference
m_array_for_send_recv Module Reference
Work array for data communication of FEM data.
Functions/Subroutines
subroutine verify_vector_for_solver (NB, NP)
subroutine allocate_vector_for_solver (NB, NP)
subroutine deallocate_vector_for_solver
subroutine allocate_iccg_int_matrix (NP)
subroutine deallocate_iccg_int_matrix
subroutine allocate_iccg_int8_matrix (NP)
subroutine deallocate_iccg_int8_matrix
Variables
real(kind=kreal), dimension(:), allocatable x_vec
Vector for solution vector.
real(kind=kreal), dimension(:), allocatable b_vec
Vector for right hand side vector.
integer(kind=kint), private isize_solver_vect = -1
Size of allocated vectors.
integer(kind=kint), dimension(:), allocatable ix_vec
Work area for integer data.
integer(kind=kint_gl), dimension(:), allocatable i8x_vec
Work area for 8-byte integer data.
Detailed Description
Work array for data communication of FEM data.
      subroutine verify_vector_for_solver(NB, NP)
      subroutine allocate_vector_for_solver(NB, NP)
      subroutine deallocate_vector_for_solver
      subroutine allocate_iccg_int_matrix(NP)
      subroutine deallocate_iccg_int_matrix
      subroutine allocate_iccg_int8_matrix(NP)
      subroutine deallocate_iccg_int8_matrix
Parameters
N length of vector
NB number of vectors to solve
Function/Subroutine Documentation
allocate_iccg_int8_matrix()
subroutine m_array_for_send_recv::allocate_iccg_int8_matrix (integer(kind = kint), intent(in) NP)
Definition at line 127 of file m_array_for_send_recv.f90.
References i8x_vec.
allocate_iccg_int_matrix()
subroutine m_array_for_send_recv::allocate_iccg_int_matrix (integer(kind = kint), intent(in) NP)
Definition at line 105 of file m_array_for_send_recv.f90.
References ix_vec.
allocate_vector_for_solver()
subroutine m_array_for_send_recv::allocate_vector_for_solver (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) NP)
Definition at line 74 of file m_array_for_send_recv.f90.
References b_vec, isize_solver_vect, and x_vec.
Referenced by parallel_fem_mesh_init::fem_mesh_initialization(), sph_analyzer_d_bench::sph_init_sph_dbench(), and verify_vector_for_solver().
deallocate_iccg_int8_matrix()
subroutine m_array_for_send_recv::deallocate_iccg_int8_matrix
Definition at line 140 of file m_array_for_send_recv.f90.
References i8x_vec.
deallocate_iccg_int_matrix()
subroutine m_array_for_send_recv::deallocate_iccg_int_matrix
Definition at line 118 of file m_array_for_send_recv.f90.
References ix_vec.
deallocate_vector_for_solver()
subroutine m_array_for_send_recv::deallocate_vector_for_solver
Definition at line 94 of file m_array_for_send_recv.f90.
References b_vec, isize_solver_vect, and x_vec.
Referenced by verify_vector_for_solver().
verify_vector_for_solver()
subroutine m_array_for_send_recv::verify_vector_for_solver (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) NP)
Definition at line 54 of file m_array_for_send_recv.f90.
References allocate_vector_for_solver(), deallocate_vector_for_solver(), and isize_solver_vect.
Variable Documentation
b_vec
real(kind=kreal), dimension(:), allocatable m_array_for_send_recv::b_vec
Vector for right hand side vector.
Definition at line 37 of file m_array_for_send_recv.f90.
Referenced by allocate_vector_for_solver(), and deallocate_vector_for_solver().
i8x_vec
integer(kind=kint_gl), dimension(:), allocatable m_array_for_send_recv::i8x_vec
Work area for 8-byte integer data.
Definition at line 44 of file m_array_for_send_recv.f90.
Referenced by allocate_iccg_int8_matrix(), and deallocate_iccg_int8_matrix().
isize_solver_vect
integer(kind = kint), private m_array_for_send_recv::isize_solver_vect = -1 private
Size of allocated vectors.
Definition at line 39 of file m_array_for_send_recv.f90.
Referenced by allocate_vector_for_solver(), deallocate_vector_for_solver(), and verify_vector_for_solver().
ix_vec
integer(kind=kint), dimension(:), allocatable m_array_for_send_recv::ix_vec
Work area for integer data.
Definition at line 42 of file m_array_for_send_recv.f90.
Referenced by allocate_iccg_int_matrix(), and deallocate_iccg_int_matrix().
x_vec
real(kind=kreal), dimension(:), allocatable m_array_for_send_recv::x_vec
Vector for solution vector.
Definition at line 35 of file m_array_for_send_recv.f90.
Referenced by allocate_vector_for_solver(), deallocate_vector_for_solver(), nod_phys_send_recv::nod_scalar_send_recv(), nod_phys_send_recv::nod_tensor_send_recv(), and nod_phys_send_recv::nod_vector_send_recv().