CALYPSO: t_control_array_charaint3 Module Reference
t_control_array_charaint3 Module Reference
Data Types
type ctl_array_ci3
Structure for charactor and integer control array.
type read_chara_int3_item
structure of control item with character and three integers
Functions/Subroutines
subroutine read_charaint3_ctl_type (c_buf, label, ci3_item)
subroutine write_charaint3_ctl_type (id_file, level, label, ci3_item)
subroutine copy_charaint3_ctl (org_ci3, new_ci3)
subroutine alloc_control_array_c_i3 (array_ci3)
subroutine dealloc_control_array_c_i3 (array_ci3)
subroutine read_control_array_c_i3 (id_control, label, array_ci3, c_buf)
subroutine write_control_array_c_i3 (id_control, level, label, array_ci3)
subroutine append_control_array_c_i3 (read_ci3, array_ci3)
subroutine copy_control_array_c_i3 (num_copy, org_ci, tgt_ci)
subroutine append_control_item_c_i3 (read_ci3, array_ci3)
Function/Subroutine Documentation
alloc_control_array_c_i3()
subroutine t_control_array_charaint3::alloc_control_array_c_i3 (type(ctl_array_ci3), intent(inout) array_ci3)
Definition at line 142 of file t_control_array_charaint3.f90.
Referenced by append_control_array_c_i3(), bcast_control_arrays::bcast_ctl_array_ci3(), and read_control_array_c_i3().
append_control_array_c_i3()
subroutine t_control_array_charaint3::append_control_array_c_i3 (type(read_chara_int3_item), intent(inout) read_ci3, type(ctl_array_ci3), intent(inout) array_ci3)
Definition at line 240 of file t_control_array_charaint3.f90.
References alloc_control_array_c_i3(), append_control_item_c_i3(), copy_control_array_c_i3(), and dealloc_control_array_c_i3().
Referenced by read_control_array_c_i3().
append_control_item_c_i3()
subroutine t_control_array_charaint3::append_control_item_c_i3 (type(read_chara_int3_item), intent(in) read_ci3, type(ctl_array_ci3), intent(inout) array_ci3)
Definition at line 283 of file t_control_array_charaint3.f90.
Referenced by append_control_array_c_i3().
copy_charaint3_ctl()
subroutine t_control_array_charaint3::copy_charaint3_ctl (type(read_chara_int3_item), intent(in) org_ci3, type(read_chara_int3_item), intent(inout) new_ci3)
Definition at line 127 of file t_control_array_charaint3.f90.
copy_control_array_c_i3()
subroutine t_control_array_charaint3::copy_control_array_c_i3 (integer(kind = kint), intent(in) num_copy, type(ctl_array_ci3), intent(in) org_ci, type(ctl_array_ci3), intent(inout) tgt_ci)
Definition at line 265 of file t_control_array_charaint3.f90.
Referenced by append_control_array_c_i3().
dealloc_control_array_c_i3()
subroutine t_control_array_charaint3::dealloc_control_array_c_i3 (type(ctl_array_ci3), intent(inout) array_ci3)
Definition at line 161 of file t_control_array_charaint3.f90.
Referenced by append_control_array_c_i3(), and t_ctl_data_4_fields::dealloc_phys_control().
read_charaint3_ctl_type()
subroutine t_control_array_charaint3::read_charaint3_ctl_type (type(buffer_for_control), intent(in) c_buf, character(len=kchara), intent(in) label, type(read_chara_int3_item), intent(inout) ci3_item)
Definition at line 81 of file t_control_array_charaint3.f90.
References m_machine_parameter::iflag_debug.
Referenced by read_control_array_c_i3().
read_control_array_c_i3()
subroutine t_control_array_charaint3::read_control_array_c_i3 (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) label, type(ctl_array_ci3), intent(inout) array_ci3, type(buffer_for_control), intent(inout) c_buf)
Definition at line 176 of file t_control_array_charaint3.f90.
References alloc_control_array_c_i3(), append_control_array_c_i3(), t_read_control_elements::check_array_flag(), t_read_control_elements::check_end_array_flag(), t_read_control_elements::load_one_line_from_control(), and read_charaint3_ctl_type().
Referenced by t_ctl_data_4_fields::read_phys_data_control().
write_charaint3_ctl_type()
subroutine t_control_array_charaint3::write_charaint3_ctl_type (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, type(read_chara_int3_item), intent(in) ci3_item)
Definition at line 107 of file t_control_array_charaint3.f90.
References write_control_elements::write_chara_int3_ctl_item().
write_control_array_c_i3()
subroutine t_control_array_charaint3::write_control_array_c_i3 (integer(kind = kint), intent(in) id_control, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, type(ctl_array_ci3), intent(in) array_ci3)
Definition at line 210 of file t_control_array_charaint3.f90.
References write_control_elements::write_array_flag_for_ctl(), write_control_elements::write_chara_int3_ctl_item(), and write_control_elements::write_end_array_flag_for_ctl().
Referenced by t_ctl_data_4_fields::write_phys_data_control().