CALYPSO: gz_field_file_io Module Reference
gz_field_file_io Module Reference
Field file IO using zlib.
Functions/Subroutines
subroutine write_gz_step_field_file (gzip_name, id_rank, t_IO, fld_IO)
subroutine read_alloc_gz_field_file (gzip_name, id_rank, fld_IO)
subroutine read_gz_step_field_file (gzip_name, id_rank, t_IO, fld_IO, ierr_IO)
subroutine read_alloc_gz_step_field_file (gzip_name, id_rank, t_IO, fld_IO, ierr_IO)
subroutine read_alloc_gz_step_field_head (gzip_name, id_rank, t_IO, fld_IO, ierr_IO)
Variables
type(buffer_4_gzip), private zbuf_f
Detailed Description
Field file IO using zlib.
      subroutine write_gz_step_field_file                             &
     &         (gzip_name, id_rank, t_IO, fld_IO)
        type(time_data), intent(in) :: t_IO
        type(field_IO), intent(in) :: fld_IO
      subroutine read_alloc_gz_field_file(gzip_name, id_rank, fld_IO)
      subroutine read_gz_step_field_file                              &
     &         (gzip_name, id_rank, t_IO, fld_IO, ierr_IO)
      subroutine read_alloc_gz_step_field_file                        &
     &          (gzip_name, id_rank, t_IO, fld_IO, ierr_IO)
        type(time_data), intent(inout) :: t_IO
        type(field_IO), intent(inout) :: fld_IO
      subroutine read_alloc_gz_step_field_head                        &
     &         (gzip_name, id_rank, t_IO, fld_IO, ierr_IO)
        type(time_data), intent(inout) :: t_IO
        type(field_IO), intent(inout) :: fld_IO
Function/Subroutine Documentation
read_alloc_gz_field_file()
subroutine gz_field_file_io::read_alloc_gz_field_file (character(len=kchara), intent(in) gzip_name, integer, intent(in) id_rank, type(field_io), intent(inout) fld_IO)
Definition at line 80 of file gz_field_file_IO.f90.
References t_field_data_io::alloc_phys_data_io(), t_field_data_io::alloc_phys_name_io(), t_field_data_io::cal_istack_phys_comp_io(), transfer_to_long_integers::cast_long(), skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_rd_gzfile_a(), gz_field_data_io::read_gz_field_data(), gz_data_io::read_gz_multi_int(), skip_gz_comment::skip_gz_comment_int2(), and zbuf_f.
Referenced by input_old_file_sel_4_zlib::sel_read_alloc_field_file().
read_alloc_gz_step_field_file()
subroutine gz_field_file_io::read_alloc_gz_step_field_file (character(len=kchara), intent(in) gzip_name, integer, intent(in) id_rank, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO, integer(kind=kint), intent(inout) ierr_IO)
Definition at line 155 of file gz_field_file_IO.f90.
References t_field_data_io::alloc_phys_data_io(), t_field_data_io::alloc_phys_name_io(), t_field_data_io::cal_istack_phys_comp_io(), transfer_to_long_integers::cast_long(), skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_rd_gzfile_a(), gz_field_data_io::read_gz_field_data(), gz_data_io::read_gz_multi_int(), gz_field_data_io::read_gz_step_data(), skip_gz_comment::skip_gz_comment_int2(), and zbuf_f.
Referenced by field_io_select::sel_read_alloc_step_field_file().
read_alloc_gz_step_field_head()
subroutine gz_field_file_io::read_alloc_gz_step_field_head (character(len=kchara), intent(in) gzip_name, integer, intent(in) id_rank, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO, integer(kind=kint), intent(inout) ierr_IO)
Definition at line 200 of file gz_field_file_IO.f90.
References t_field_data_io::alloc_phys_name_io(), t_field_data_io::cal_istack_phys_comp_io(), transfer_to_long_integers::cast_long(), skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_rd_gzfile_a(), gz_field_data_io::read_gz_field_name(), gz_data_io::read_gz_multi_int(), gz_field_data_io::read_gz_step_data(), skip_gz_comment::skip_gz_comment_int2(), and zbuf_f.
Referenced by field_io_select::sel_read_alloc_field_head().
read_gz_step_field_file()
subroutine gz_field_file_io::read_gz_step_field_file (character(len=kchara), intent(in) gzip_name, integer, intent(in) id_rank, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO, integer(kind=kint), intent(inout) ierr_IO)
Definition at line 116 of file gz_field_file_IO.f90.
References transfer_to_long_integers::cast_long(), skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_rd_gzfile_a(), gz_field_data_io::read_gz_field_data(), gz_data_io::read_gz_multi_int(), gz_field_data_io::read_gz_step_data(), skip_gz_comment::skip_gz_comment_int2(), and zbuf_f.
Referenced by field_io_select::sel_read_step_field_file().
write_gz_step_field_file()
subroutine gz_field_file_io::write_gz_step_field_file (character(len=kchara), intent(in) gzip_name, integer, intent(in) id_rank, type(time_data), intent(in) t_IO, type(field_io), intent(in) fld_IO)
Definition at line 50 of file gz_field_file_IO.f90.
References transfer_to_long_integers::cast_long(), skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_wt_gzfile_a(), gz_field_data_io::write_gz_field_data(), gz_field_data_io::write_gz_step_data(), and zbuf_f.
Referenced by field_io_select::sel_write_step_field_file().
Variable Documentation
zbuf_f
type(buffer_4_gzip), private gz_field_file_io::zbuf_f private
Definition at line 42 of file gz_field_file_IO.f90.
Referenced by read_alloc_gz_field_file(), read_alloc_gz_step_field_file(), read_alloc_gz_step_field_head(), read_gz_step_field_file(), and write_gz_step_field_file().