CALYPSO: gz_field_block_mpi_io Module Reference
gz_field_block_mpi_io Module Reference
Output merged VTK file usgin MPI-IO.
Functions/Subroutines
subroutine write_field_head_gz_mpi (id_fld, ioff_gl, t_IO, num_field, ncomp_field, istack_merged)
subroutine write_field_data_gz_mpi (id_fld, ioff_gl, nnod, num_field, ntot_comp, ncomp_field, field_name, d_nod)
subroutine read_field_step_gz_mpi (id_fld, num_pe, ioff_gl, t_IO)
subroutine read_field_header_gz_mpi (id_fld, num_pe, id_rank, ioff_gl, nnod, num_field, istack_merged)
subroutine read_field_num_gz_mpi (id_fld, ioff_gl, num_field, ncomp_field)
subroutine read_field_data_gz_mpi (id_fld, num_pe, id_rank, ioff_gl, nnod, num_field, ntot_comp, ncomp_field, field_name, d_nod)
subroutine read_field_names_gz_mpi (id_fld, num_pe, id_rank, ioff_gl, num_field, field_name)
Detailed Description
Output merged VTK file usgin MPI-IO.
      subroutine write_field_head_gz_mpi(id_fld, ioff_gl,             &
     &          t_IO, num_field, ncomp_field, istack_merged)
      subroutine write_field_data_gz_mpi(id_fld, ioff_gl,             &
     &           nnod, num_field, ntot_comp, ncomp_field,             &
     &           field_name, d_nod)
      subroutine read_field_step_gz_mpi                               &
     &         (id_fld, num_pe, ioff_gl, t_IO)
      subroutine read_field_header_gz_mpi(id_fld, num_pe, id_rank,    &
     &          ioff_gl, nnod, num_field, istack_merged)
      subroutine read_field_num_gz_mpi                                &
     &         (id_fld, ioff_gl, num_field, ncomp_field)
      subroutine read_field_data_gz_mpi(id_fld, num_pe, id_rank,      &
     &          ioff_gl, nnod, num_field, ntot_comp, ncomp_field,     &
     &          field_name, d_nod)
Function/Subroutine Documentation
read_field_data_gz_mpi()
subroutine gz_field_block_mpi_io::read_field_data_gz_mpi (integer, intent(in) id_fld, integer, intent(in) num_pe, integer, intent(in) id_rank, integer(kind = kint_gl), intent(inout) ioff_gl, integer(kind=kint_gl), intent(in) nnod, integer(kind=kint), intent(in) num_field, integer(kind=kint), intent(in) ntot_comp, integer(kind=kint), dimension(num_field), intent(in) ncomp_field, character(len=kchara), dimension(num_field), intent(inout) field_name, real(kind = kreal), dimension(nnod,ntot_comp), intent(inout) d_nod)
Definition at line 223 of file gz_field_block_MPI_IO.f90.
References gz_field_data_mpi_io::gz_read_each_field_mpi(), gz_field_data_mpi_io::gz_read_fld_1word_mpi(), and calypso_mpi::my_rank.
Referenced by gz_ucd_field_mpi_io::gz_read_alloc_ucd_fld_file_mpi(), gz_ucd_field_mpi_io::gz_read_ucd_field_file_mpi(), gz_field_file_mpi_io::read_alloc_stp_fld_file_gz_mpi(), and gz_field_file_mpi_io::read_step_field_file_gz_mpi().
read_field_header_gz_mpi()
subroutine gz_field_block_mpi_io::read_field_header_gz_mpi (integer, intent(in) id_fld, integer, intent(in) num_pe, integer, intent(in) id_rank, integer(kind = kint_gl), intent(inout) ioff_gl, integer(kind = kint_gl), intent(inout) nnod, integer(kind = kint), intent(inout) num_field, integer(kind = kint_gl), dimension(0:num_pe), intent(inout) istack_merged)
Definition at line 146 of file gz_field_block_MPI_IO.f90.
References calypso_mpi_int8::calypso_mpi_bcast_int8(), calypso_mpi_int::calypso_mpi_bcast_one_int(), transfer_to_long_integers::cast_long(), field_data_io::field_num_buffer(), gz_field_data_mpi_io::gz_read_fld_charhead_mpi(), m_constants::izero, calypso_mpi::my_rank, field_data_io::read_field_istack_nod_buffer(), field_data_io::read_field_num_buffer(), and field_data_mpi_io::sync_field_header_mpi().
Referenced by gz_ucd_field_mpi_io::gz_read_alloc_ucd_fld_file_mpi(), gz_ucd_field_mpi_io::gz_read_ucd_field_file_mpi(), gz_field_file_mpi_io::read_alloc_stp_fld_file_gz_mpi(), gz_field_file_mpi_io::read_alloc_stp_fld_head_gz_mpi(), and gz_field_file_mpi_io::read_step_field_file_gz_mpi().
read_field_names_gz_mpi()
subroutine gz_field_block_mpi_io::read_field_names_gz_mpi (integer, intent(in) id_fld, integer, intent(in) num_pe, integer, intent(in) id_rank, integer(kind = kint_gl), intent(inout) ioff_gl, integer(kind=kint), intent(in) num_field, character(len=kchara), dimension(num_field), intent(inout) field_name)
Definition at line 259 of file gz_field_block_MPI_IO.f90.
References gz_field_data_mpi_io::gz_read_fld_1word_mpi(), and gz_field_data_mpi_io::gz_skip_each_field_mpi().
Referenced by gz_field_file_mpi_io::read_alloc_stp_fld_head_gz_mpi().
read_field_num_gz_mpi()
subroutine gz_field_block_mpi_io::read_field_num_gz_mpi (integer, intent(in) id_fld, integer(kind = kint_gl), intent(inout) ioff_gl, integer(kind=kint), intent(inout) num_field, integer(kind=kint), dimension(num_field), intent(inout) ncomp_field)
Definition at line 192 of file gz_field_block_MPI_IO.f90.
References calypso_mpi_int::calypso_mpi_bcast_int(), transfer_to_long_integers::cast_long(), gz_field_data_mpi_io::gz_read_fld_charhead_mpi(), calypso_mpi::my_rank, and field_data_io::read_field_comp_buffer().
Referenced by gz_ucd_field_mpi_io::gz_read_alloc_ucd_fld_file_mpi(), gz_ucd_field_mpi_io::gz_read_ucd_field_file_mpi(), gz_field_file_mpi_io::read_alloc_stp_fld_file_gz_mpi(), gz_field_file_mpi_io::read_alloc_stp_fld_head_gz_mpi(), and gz_field_file_mpi_io::read_step_field_file_gz_mpi().
read_field_step_gz_mpi()
subroutine gz_field_block_mpi_io::read_field_step_gz_mpi (integer, intent(in) id_fld, integer, intent(in) num_pe, integer(kind = kint_gl), intent(inout) ioff_gl, type(time_data), intent(inout) t_IO)
Definition at line 111 of file gz_field_block_MPI_IO.f90.
References calypso_mpi::calypso_mpi_abort(), gz_field_data_mpi_io::gz_read_fld_charhead_mpi(), m_error_ids::ierr_fld, time_data_io::len_step_data_buf, calypso_mpi::my_rank, time_data_io::read_step_data_buffer(), and field_data_mpi_io::sync_field_time_mpi().
Referenced by gz_ucd_field_mpi_io::gz_read_alloc_ucd_fld_file_mpi(), gz_ucd_field_mpi_io::gz_read_ucd_field_file_mpi(), gz_field_file_mpi_io::read_alloc_stp_fld_file_gz_mpi(), gz_field_file_mpi_io::read_alloc_stp_fld_head_gz_mpi(), and gz_field_file_mpi_io::read_step_field_file_gz_mpi().
write_field_data_gz_mpi()
subroutine gz_field_block_mpi_io::write_field_data_gz_mpi (integer, intent(in) id_fld, integer(kind = kint_gl), intent(inout) ioff_gl, integer(kind = kint_gl), intent(in) nnod, integer(kind=kint), intent(in) num_field, integer(kind=kint), intent(in) ntot_comp, integer(kind=kint), dimension(num_field), intent(in) ncomp_field, character(len=kchara), dimension(num_field), intent(in) field_name, real(kind = kreal), dimension(nnod,ntot_comp), intent(in) d_nod)
Definition at line 76 of file gz_field_block_MPI_IO.f90.
References field_data_io::each_field_name_buffer(), gz_field_data_mpi_io::gz_write_fld_header_mpi(), and gz_field_data_mpi_io::gz_write_fld_vecotr_mpi().
Referenced by gz_ucd_field_mpi_io::gz_write_ucd_field_file_mpi(), and gz_field_file_mpi_io::write_gz_step_field_file_mpi().
write_field_head_gz_mpi()
subroutine gz_field_block_mpi_io::write_field_head_gz_mpi (integer, intent(in) id_fld, integer(kind = kint_gl), intent(inout) ioff_gl, type(time_data), intent(in) t_IO, integer(kind=kint), intent(in) num_field, integer(kind=kint), dimension(num_field), intent(in) ncomp_field, integer(kind = kint_gl), dimension(0:nprocs), intent(in) istack_merged)
Definition at line 44 of file gz_field_block_MPI_IO.f90.
References field_data_io::field_comp_buffer(), field_data_io::field_istack_nod_buffer(), field_data_io::field_num_buffer(), gz_field_data_mpi_io::gz_write_fld_header_mpi(), and time_data_io::step_data_buffer().
Referenced by gz_ucd_field_mpi_io::gz_write_ucd_field_file_mpi(), and gz_field_file_mpi_io::write_gz_step_field_file_mpi().