CALYPSO: extend_potential_field_t Module Reference
extend_potential_field_t Module Reference
Extend magnetic field by potential field structure.
Functions/Subroutines
subroutine ext_outside_scalar_t (rj, kr_out, d_rj)
subroutine ext_inside_scalar_t (rj, kr_in, d_rj)
subroutine ext_outside_potential_t (rj, kr_out, d_rj)
subroutine ext_inside_potential_t (rj, kr_in, d_rj)
subroutine ext_outside_potential_t_with_j (rj, kr_out, d_rj_b, d_rj_j)
subroutine ext_inside_potential_t_with_j (rj, kr_in, d_rj_b, d_rj_j)
subroutine gauss_to_poloidal_out_t (rj, kr_out, ltr_w, r_gauss, w_gauss, index_w, d_rj)
subroutine gauss_to_poloidal_in_t (rj, kr_in, ltr_w, r_gauss, w_gauss, index_w, d_rj)
Detailed Description
Extend magnetic field by potential field structure.
      subroutine ext_outside_scalar_t(rj, kr_out, d_rj)
      subroutine ext_inside_scalar_t(rj, kr_in, d_rj)
      subroutine ext_outside_potential_t(rj, kr_out, d_rj)
        Output: d_rj(kr_out+1:,1:3)
      subroutine ext_inside_potential_t(rj, kr_in, d_rj)
        Output: d_rj(1:kr_in,1:3)
      subroutine ext_outside_potential_t_with_j(rj, kr_out,           &
     &          d_rj_b, d_rj_j)
        Output: d_rj_b(kr_out+1:,1:3)
        Output: d_rj_j(kr_out+1:,1:3)
      subroutine ext_inside_potential_t_with_j(rj, kr_in,             &
     &          d_rj_b, d_rj_j)
        Output: d_rj_b(1:kr_in,1:3)
        Output: d_rj_j(1:kr_in,1:3)
      subroutine gauss_to_poloidal_out_t(rj, kr_out, ltr_w, r_gauss,  &
     &          w_gauss, index_w, d_rj)
      subroutine gauss_to_poloidal_in_t(rj, kr_in, ltr_w, r_gauss,    &
     &          w_gauss, index_w, d_rj)
        type(sph_rj_grid), intent(in) :: rj
Function/Subroutine Documentation
ext_inside_potential_t()
subroutine extend_potential_field_t::ext_inside_potential_t (type(sph_rj_grid), intent(in) rj, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(rj%nnod_rj,3), intent(inout) d_rj)
Definition at line 142 of file extend_potential_field_t.f90.
References m_constants::zero.
Referenced by assemble_sph_fields::extend_potential_magne_type().
ext_inside_potential_t_with_j()
subroutine extend_potential_field_t::ext_inside_potential_t_with_j (type(sph_rj_grid), intent(in) rj, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(rj%nnod_rj,3), intent(inout) d_rj_b, real(kind = kreal), dimension(rj%nnod_rj,3), intent(inout) d_rj_j)
Definition at line 214 of file extend_potential_field_t.f90.
References m_constants::zero.
ext_inside_scalar_t()
subroutine extend_potential_field_t::ext_inside_scalar_t (type(sph_rj_grid), intent(in) rj, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(rj%nnod_rj), intent(inout) d_rj)
Definition at line 79 of file extend_potential_field_t.f90.
Referenced by assemble_sph_fields::extend_inner_core_scl_type().
ext_outside_potential_t()
subroutine extend_potential_field_t::ext_outside_potential_t (type(sph_rj_grid), intent(in) rj, integer(kind = kint), intent(in) kr_out, real(kind = kreal), dimension(rj%nnod_rj,3), intent(inout) d_rj)
Definition at line 109 of file extend_potential_field_t.f90.
References m_constants::zero.
Referenced by assemble_sph_fields::extend_potential_magne_type().
ext_outside_potential_t_with_j()
subroutine extend_potential_field_t::ext_outside_potential_t_with_j (type(sph_rj_grid), intent(in) rj, integer(kind = kint), intent(in) kr_out, real(kind = kreal), dimension(rj%nnod_rj,3), intent(inout) d_rj_b, real(kind = kreal), dimension(rj%nnod_rj,3), intent(inout) d_rj_j)
Definition at line 176 of file extend_potential_field_t.f90.
References m_constants::zero.
ext_outside_scalar_t()
subroutine extend_potential_field_t::ext_outside_scalar_t (type(sph_rj_grid), intent(in) rj, integer(kind = kint), intent(in) kr_out, real(kind = kreal), dimension(rj%nnod_rj), intent(inout) d_rj)
Definition at line 49 of file extend_potential_field_t.f90.
gauss_to_poloidal_in_t()
subroutine extend_potential_field_t::gauss_to_poloidal_in_t (type(sph_rj_grid), intent(in) rj, integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) ltr_w, real(kind = kreal), intent(in) r_gauss, real(kind = kreal), dimension(ltr_w*(ltr_w+2)), intent(in) w_gauss, integer(kind = kint), dimension(ltr_w*(ltr_w+2),2), intent(in) index_w, real(kind = kreal), dimension(rj%nnod_rj,3), intent(inout) d_rj)
Definition at line 294 of file extend_potential_field_t.f90.
References t_spheric_rj_data::find_local_sph_address(), m_constants::one, and m_constants::zero.
gauss_to_poloidal_out_t()
subroutine extend_potential_field_t::gauss_to_poloidal_out_t (type(sph_rj_grid), intent(in) rj, integer(kind = kint), intent(in) kr_out, integer(kind = kint), intent(in) ltr_w, real(kind = kreal), intent(in) r_gauss, real(kind = kreal), dimension(ltr_w*(ltr_w+2)), intent(in) w_gauss, integer(kind = kint), dimension(ltr_w*(ltr_w+2),2), intent(in) index_w, real(kind = kreal), dimension(rj%nnod_rj,3), intent(inout) d_rj)
Definition at line 253 of file extend_potential_field_t.f90.
References t_spheric_rj_data::find_local_sph_address(), m_constants::one, and m_constants::zero.