CALYPSO: gz_binary_io Module Reference
gz_binary_io Module Reference
Output merged binary field file using MPI-IO.
Functions/Subroutines
subroutine open_wt_gzfile_b (gzip_name, zbuf)
subroutine open_rd_gzfile_b (gzip_name, id_rank, zbuf)
subroutine, private gz_write_endian_flag (zbuf)
subroutine gz_write_one_integer_b (int_dat, zbuf)
subroutine gz_write_one_real_b (real_dat, zbuf)
subroutine gz_write_mul_int8_b (num, int8_dat, zbuf)
subroutine gz_write_mul_integer_b (num, int_dat, zbuf)
subroutine gz_write_integer_stack_b (num, istack, zbuf)
subroutine gz_write_mul_character_b (num, chara_dat, zbuf)
subroutine gz_write_mul_one_character_b (num, chara_dat, zbuf)
subroutine gz_write_1d_vector_b (num, real_dat, zbuf)
subroutine gz_write_2d_vector_b (n1, n2, real_dat, zbuf)
subroutine, private gz_read_endian_flag (id_rank, zbuf)
subroutine gz_read_one_integer_b (zbuf, int_dat)
subroutine gz_read_one_real_b (zbuf, real_dat)
subroutine gz_read_mul_int8_b (zbuf, num, int8_dat)
subroutine gz_read_mul_integer_b (zbuf, num, int_dat)
subroutine gz_read_integer_stack_b (zbuf, num, istack, ntot)
subroutine gz_read_mul_character_b (zbuf, num, chara_dat)
subroutine gz_read_mul_one_character_b (zbuf, num, chara_dat)
subroutine gz_read_1d_vector_b (zbuf, num, real_dat)
subroutine gz_read_2d_vector_b (zbuf, n1, n2, real_dat)
Detailed Description
Output merged binary field file using MPI-IO.
      subroutine open_wt_gzfile_b(gzip_name, zbuf)
      subroutine open_rd_gzfile_b(gzip_name, id_rank, zbuf)
        type(buffer_4_gzip), intent(inout) :: zbuf
      subroutine gz_write_one_integer_b(int_dat, zbuf)
      subroutine gz_write_one_real_b(real_dat, zbuf)
      subroutine gz_write_mul_int8_b(num, int8_dat, zbuf)
      subroutine gz_write_mul_integer_b(num, int_dat, zbuf)
      subroutine gz_write_integer_stack_b(num, istack, zbuf)
      subroutine gz_write_mul_character_b(num, chara_dat, zbuf)
      subroutine gz_write_mul_one_character_b(num, chara_dat, zbuf)
      subroutine gz_write_1d_vector_b(num, real_dat, zbuf)
      subroutine gz_write_2d_vector_b(n1, n2, real_dat, zbuf)
        type(buffer_4_gzip), intent(inout) :: zbuf
      subroutine gz_read_endian_flag(id_rank, zbuf)
      subroutine gz_read_one_integer_b(zbuf, int_dat)
      subroutine gz_read_one_real_b(zbuf, real_dat)
      subroutine gz_read_mul_int8_b(zbuf, num, int8_dat)
      subroutine gz_read_mul_integer_b(zbuf, num, int_dat)
      subroutine gz_read_integer_stack_b(zbuf, num, istack, ntot)
      subroutine gz_read_mul_character_b(zbuf, num, chara_dat)
      subroutine gz_read_mul_one_character_b(zbuf, num, chara_dat)
      subroutine gz_read_1d_vector_b(zbuf, num, real_dat)
      subroutine gz_read_2d_vector_b(zbuf, n1, n2, real_dat)
        type(buffer_4_gzip), intent(inout) :: zbuf
Function/Subroutine Documentation
gz_read_1d_vector_b()
subroutine gz_binary_io::gz_read_1d_vector_b (type(buffer_4_gzip), intent(inout) zbuf, integer(kind = kint_gl), intent(in) num, real(kind = kreal), dimension(num), intent(inout) real_dat)
Definition at line 481 of file gz_binary_IO.f90.
References gzip_file_access::gzread_real_f(), and m_constants::huge_20.
Referenced by gz_read_2d_vector_b(), gz_read_one_real_b(), gz_sph_global_1d_idx_io_b::gz_read_rj_gl_1d_table_b(), gz_sph_global_1d_idx_io_b::gz_read_rtp_gl_1d_table_b(), gz_node_geometry_io_b::gz_read_scalar_in_element_b(), and gz_read_psf_binary_data::read_psf_phys_data_bin_gz().
gz_read_2d_vector_b()
subroutine gz_binary_io::gz_read_2d_vector_b (type(buffer_4_gzip), intent(inout) zbuf, integer(kind = kint_gl), intent(in) n1, integer(kind = kint), intent(in) n2, real(kind = kreal), dimension(n1,n2), intent(inout) real_dat)
Definition at line 507 of file gz_binary_IO.f90.
References gz_read_1d_vector_b().
Referenced by gz_field_data_io_b::gz_read_field_data_b(), gz_node_geometry_io_b::gz_read_geometry_info_b(), and gz_node_geometry_io_b::gz_read_vector_in_element_b().
gz_read_endian_flag()
subroutine, private gz_binary_io::gz_read_endian_flag (integer, intent(in) id_rank, type(buffer_4_gzip), intent(inout) zbuf) private
Definition at line 308 of file gz_binary_IO.f90.
References binary_io::endian_check(), gzip_file_access::gzread_int4_f(), and m_machine_parameter::iendian_keep.
Referenced by open_rd_gzfile_b().
gz_read_integer_stack_b()
subroutine gz_binary_io::gz_read_integer_stack_b (type(buffer_4_gzip), intent(inout) zbuf, integer(kind = kint_gl), intent(in) num, integer(kind = kint), dimension(0:num), intent(inout) istack, integer(kind = kint), intent(inout) ntot)
Definition at line 411 of file gz_binary_IO.f90.
References gz_read_mul_integer_b().
Referenced by gz_domain_data_io_b::gz_read_export_data_b(), gz_groups_io_b::gz_read_group_data_b(), gz_domain_data_io_b::gz_read_import_data_b(), and gz_groups_io_b::gz_read_surf_grp_data_b().
gz_read_mul_character_b()
subroutine gz_binary_io::gz_read_mul_character_b (type(buffer_4_gzip), intent(inout) zbuf, integer(kind = kint_gl), intent(in) num, character(len=kchara), dimension(num), intent(inout) chara_dat)
Definition at line 428 of file gz_binary_IO.f90.
References gzip_file_access::gzread_chara_f(), m_constants::huge_20, and m_precision::kchara.
Referenced by gz_field_data_io_b::gz_read_field_data_b(), gz_groups_io_b::gz_read_group_data_b(), gz_groups_io_b::gz_read_surf_grp_data_b(), and gz_read_psf_binary_data::read_psf_phys_name_bin_gz().
gz_read_mul_int8_b()
subroutine gz_binary_io::gz_read_mul_int8_b (type(buffer_4_gzip), intent(inout) zbuf, integer(kind = kint_gl), intent(in) num, integer(kind = kint_gl), dimension(num), intent(inout) int8_dat)
Definition at line 364 of file gz_binary_IO.f90.
References gzip_file_access::gzread_int8_f(), m_constants::huge_20, and m_precision::kint_gl.
Referenced by gz_element_connect_io_b::gz_read_element_info_b(), gz_node_geometry_io_b::gz_read_geometry_info_b(), gz_spherical_model_io_b::gz_read_gl_nodes_sph_b(), gz_read_mul_integer_b(), gz_read_one_integer_b(), gz_field_data_io_b::gz_read_step_data_b(), gz_read_psf_binary_data::read_psf_ele_connect_bin_gz(), gz_read_psf_binary_data::read_psf_ele_num_bin_gz(), gz_read_psf_binary_data::read_psf_node_num_bin_gz(), and gz_read_psf_binary_data::read_psf_phys_data_bin_gz().
gz_read_mul_integer_b()
subroutine gz_binary_io::gz_read_mul_integer_b (type(buffer_4_gzip), intent(inout) zbuf, integer(kind = kint_gl), intent(in) num, integer(kind = kint), dimension(num), intent(inout) int_dat)
Definition at line 391 of file gz_binary_IO.f90.
References transfer_to_long_integers::alloc_1d_i8array(), transfer_to_long_integers::dup_to_short_array(), and gz_read_mul_int8_b().
Referenced by gz_field_file_io_b::gz_rd_alloc_st_fld_file_b(), gz_field_file_io_b::gz_rd_alloc_st_fld_head_b(), gz_domain_data_io_b::gz_read_domain_info_b(), gz_element_connect_io_b::gz_read_edge_4_element_b(), gz_element_connect_io_b::gz_read_element_info_b(), gz_domain_data_io_b::gz_read_export_data_b(), gz_spherical_model_io_b::gz_read_gl_nodes_sph_b(), gz_spherical_model_io_b::gz_read_gl_resolution_sph_b(), gz_groups_io_b::gz_read_group_data_b(), gz_domain_data_io_b::gz_read_import_data_b(), gz_read_integer_stack_b(), gz_spherical_model_io_b::gz_read_rank_4_sph_b(), gz_sph_global_1d_idx_io_b::gz_read_rj_gl_1d_table_b(), gz_sph_global_1d_idx_io_b::gz_read_rtp_gl_1d_table_b(), gz_field_file_io_b::gz_read_step_field_file_b(), gz_groups_io_b::gz_read_surf_grp_data_b(), gz_element_connect_io_b::gz_read_surface_4_element_b(), and gz_read_psf_binary_data::read_psf_phys_name_bin_gz().
gz_read_mul_one_character_b()
subroutine gz_binary_io::gz_read_mul_one_character_b (type(buffer_4_gzip), intent(inout) zbuf, integer(kind = kint_gl), intent(in) num, character(len=1), dimension(num), intent(inout) chara_dat)
Definition at line 455 of file gz_binary_IO.f90.
References gzip_file_access::gzread_chara_f(), and m_constants::huge_20.
gz_read_one_integer_b()
subroutine gz_binary_io::gz_read_one_integer_b (type(buffer_4_gzip), intent(inout) zbuf, integer(kind = kint), intent(inout) int_dat)
Definition at line 327 of file gz_binary_IO.f90.
References gz_read_mul_int8_b().
Referenced by gz_read_psf_binary_file::gz_read_alloc_iso_bin_file(), gz_read_psf_binary_file::gz_read_alloc_psf_bin_grid(), gz_domain_data_io_b::gz_read_domain_info_b(), gz_element_connect_io_b::gz_read_edge_4_element_b(), gz_spherical_model_io_b::gz_read_gl_nodes_sph_b(), gz_spherical_model_io_b::gz_read_gl_resolution_sph_b(), gz_groups_io_b::gz_read_group_data_b(), gz_read_psf_binary_file::gz_read_iso_bin_file(), gz_element_connect_io_b::gz_read_number_of_element_b(), gz_node_geometry_io_b::gz_read_number_of_node_b(), gz_read_psf_binary_file::gz_read_psf_bin_grid(), gz_read_udt_from_bin_data::gz_read_psf_bin_time_data(), gz_field_data_io_b::gz_read_step_data_b(), gz_groups_io_b::gz_read_surf_grp_data_b(), gz_element_connect_io_b::gz_read_surface_4_element_b(), and gz_read_psf_binary_data::read_psf_phys_num_bin_gz().
gz_read_one_real_b()
subroutine gz_binary_io::gz_read_one_real_b (type(buffer_4_gzip), intent(inout) zbuf, real(kind = kreal), intent(inout) real_dat)
Definition at line 345 of file gz_binary_IO.f90.
References gz_read_1d_vector_b().
Referenced by gz_read_udt_from_bin_data::gz_read_psf_bin_time_data(), and gz_field_data_io_b::gz_read_step_data_b().
gz_write_1d_vector_b()
subroutine gz_binary_io::gz_write_1d_vector_b (integer(kind = kint_gl), intent(in) num, real(kind = kreal), dimension(num), intent(in) real_dat, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 261 of file gz_binary_IO.f90.
References gzip_file_access::gzwrite_real_f(), and m_constants::huge_20.
Referenced by gz_write_2d_vector_b(), gz_write_one_real_b(), gz_sph_global_1d_idx_io_b::gz_write_rj_gl_1d_table_b(), gz_sph_global_1d_idx_io_b::gz_write_rtp_gl_1d_table_b(), and gz_node_geometry_io_b::gz_write_scalar_in_element_b().
gz_write_2d_vector_b()
subroutine gz_binary_io::gz_write_2d_vector_b (integer(kind = kint_gl), intent(in) n1, integer(kind = kint), intent(in) n2, real(kind = kreal), dimension(n1,n2), intent(in) real_dat, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 288 of file gz_binary_IO.f90.
References gz_write_1d_vector_b().
Referenced by gz_field_data_io_b::gz_write_field_data_b(), gz_node_geometry_io_b::gz_write_geometry_info_b(), and gz_node_geometry_io_b::gz_write_vector_in_element_b().
gz_write_endian_flag()
subroutine, private gz_binary_io::gz_write_endian_flag (type(buffer_4_gzip), intent(inout) zbuf) private
Definition at line 95 of file gz_binary_IO.f90.
References gzip_file_access::gzwrite_int4_f().
Referenced by open_wt_gzfile_b().
gz_write_integer_stack_b()
subroutine gz_binary_io::gz_write_integer_stack_b (integer(kind = kint_gl), intent(in) num, integer(kind = kint), dimension(0:num), intent(in) istack, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 194 of file gz_binary_IO.f90.
References gz_write_mul_integer_b().
Referenced by gz_domain_data_io_b::gz_write_export_data_b(), gz_groups_io_b::gz_write_grp_data_b(), gz_domain_data_io_b::gz_write_import_data_b(), and gz_groups_io_b::gz_write_surf_grp_data_b().
gz_write_mul_character_b()
subroutine gz_binary_io::gz_write_mul_character_b (integer(kind = kint_gl), intent(in) num, character(len=kchara), dimension(num), intent(in) chara_dat, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 206 of file gz_binary_IO.f90.
References gzip_file_access::gzwrite_chara_f(), m_constants::huge_20, and m_precision::kchara.
Referenced by gz_field_data_io_b::gz_write_field_data_b(), gz_groups_io_b::gz_write_grp_data_b(), and gz_groups_io_b::gz_write_surf_grp_data_b().
gz_write_mul_int8_b()
subroutine gz_binary_io::gz_write_mul_int8_b (integer(kind = kint_gl), intent(in) num, integer(kind = kint_gl), dimension(num), intent(in) int8_dat, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 147 of file gz_binary_IO.f90.
References gzip_file_access::gzwrite_int8_f(), and m_constants::huge_20.
Referenced by gz_element_connect_io_b::gz_write_element_info_b(), gz_field_data_io_b::gz_write_field_data_b(), gz_node_geometry_io_b::gz_write_geometry_info_b(), gz_spherical_model_io_b::gz_write_gl_nodes_sph_b(), gz_write_mul_integer_b(), and gz_write_one_integer_b().
gz_write_mul_integer_b()
subroutine gz_binary_io::gz_write_mul_integer_b (integer(kind = kint_gl), intent(in) num, integer(kind = kint), dimension(num), intent(in) int_dat, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 174 of file gz_binary_IO.f90.
References transfer_to_long_integers::dealloc_1d_i8array(), transfer_to_long_integers::dup_from_short_array(), and gz_write_mul_int8_b().
Referenced by gz_domain_data_io_b::gz_write_domain_info_b(), gz_element_connect_io_b::gz_write_edge_4_element_b(), gz_element_connect_io_b::gz_write_element_info_b(), gz_domain_data_io_b::gz_write_export_data_b(), gz_field_data_io_b::gz_write_field_data_b(), gz_spherical_model_io_b::gz_write_gl_nodes_sph_b(), gz_spherical_model_io_b::gz_write_gl_resolution_sph_b(), gz_groups_io_b::gz_write_grp_data_b(), gz_domain_data_io_b::gz_write_import_data_b(), gz_write_integer_stack_b(), gz_spherical_model_io_b::gz_write_rank_4_sph_b(), gz_sph_global_1d_idx_io_b::gz_write_rj_gl_1d_table_b(), gz_sph_global_1d_idx_io_b::gz_write_rtp_gl_1d_table_b(), gz_groups_io_b::gz_write_surf_grp_data_b(), and gz_element_connect_io_b::gz_write_surface_4_element_b().
gz_write_mul_one_character_b()
subroutine gz_binary_io::gz_write_mul_one_character_b (integer(kind = kint_gl), intent(in) num, character(len=1), dimension(num), intent(in) chara_dat, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 234 of file gz_binary_IO.f90.
References gzip_file_access::gzwrite_chara_f(), and m_constants::huge_20.
gz_write_one_integer_b()
subroutine gz_binary_io::gz_write_one_integer_b (integer(kind = kint), intent(in) int_dat, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 109 of file gz_binary_IO.f90.
References transfer_to_long_integers::cast_long(), and gz_write_mul_int8_b().
Referenced by gz_domain_data_io_b::gz_write_domain_info_b(), gz_element_connect_io_b::gz_write_edge_4_element_b(), gz_element_connect_io_b::gz_write_element_info_b(), gz_field_data_io_b::gz_write_field_data_b(), gz_node_geometry_io_b::gz_write_geometry_info_b(), gz_spherical_model_io_b::gz_write_gl_nodes_sph_b(), gz_spherical_model_io_b::gz_write_gl_resolution_sph_b(), gz_groups_io_b::gz_write_grp_data_b(), gz_node_geometry_io_b::gz_write_scalar_in_element_b(), gz_field_data_io_b::gz_write_step_data_b(), gz_groups_io_b::gz_write_surf_grp_data_b(), gz_element_connect_io_b::gz_write_surface_4_element_b(), and gz_node_geometry_io_b::gz_write_vector_in_element_b().
gz_write_one_real_b()
subroutine gz_binary_io::gz_write_one_real_b (real(kind = kreal), intent(in) real_dat, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 128 of file gz_binary_IO.f90.
References gz_write_1d_vector_b().
Referenced by gz_field_data_io_b::gz_write_step_data_b().
open_rd_gzfile_b()
subroutine gz_binary_io::open_rd_gzfile_b (character(len=kchara), intent(in) gzip_name, integer, intent(in) id_rank, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 74 of file gz_binary_IO.f90.
References gz_read_endian_flag(), m_error_ids::ierr_file, and gzip_file_access::open_rd_gzfile_f().
Referenced by gz_field_file_io_b::gz_rd_alloc_st_fld_file_b(), gz_field_file_io_b::gz_rd_alloc_st_fld_head_b(), gz_read_psf_binary_file::gz_read_alloc_iso_bin_file(), gz_read_psf_binary_file::gz_read_alloc_psf_bin_file(), gz_read_psf_binary_file::gz_read_alloc_psf_bin_grid(), gz_mesh_file_io_b::gz_read_geometry_size_b(), gz_read_psf_binary_file::gz_read_iso_bin_file(), gz_mesh_file_io_b::gz_read_mesh_file_b(), gz_mesh_file_io_b::gz_read_mesh_geometry_b(), gz_mesh_file_io_b::gz_read_node_size_b(), gz_read_psf_binary_file::gz_read_psf_bin_file(), gz_read_psf_binary_file::gz_read_psf_bin_grid(), and gz_field_file_io_b::gz_read_step_field_file_b().
open_wt_gzfile_b()
subroutine gz_binary_io::open_wt_gzfile_b (character(len=kchara), intent(in) gzip_name, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 57 of file gz_binary_IO.f90.
References gz_write_endian_flag(), and gzip_file_access::open_wt_gzfile_f().
Referenced by gz_mesh_file_io_b::gz_write_mesh_file_b(), and gz_field_file_io_b::gz_write_step_fld_file_b().