CALYPSO: cmp_trans_sph_tests Module Reference
cmp_trans_sph_tests Module Reference
Functions/Subroutines
subroutine allocate_real_sph_test (NB, nnod_rtp, nnod_rtm, nnod_rlm, nnod_rj)
subroutine deallocate_real_sph_test
subroutine sph_transfer_test_1 (iflag_recv, sph, comms_sph)
subroutine sph_transfer_test_2 (iflag_recv, sph, comms_sph)
subroutine sph_transfer_test_3 (iflag_recv, sph, comms_sph)
subroutine sph_transfer_test_6 (iflag_recv, sph, comms_sph)
subroutine sph_transfer_test_n (iflag_recv, NB, sph, comms_sph)
subroutine, private set_transfer_sph_reals (NB, sph_rtp, sph_rtm, sph_rlm, sph_rj)
subroutine, private set_real_4_sph_transfer_test (NB, nnod_rtp, nnod_rtm, nnod_rlm, nnod_rj, idx_global_rtp, idx_global_rtm, idx_global_rlm, idx_global_rj)
integer(kind=kint) function compare_transfer_sph_reals (NB, id_check, sph)
Variables
real(kind=kreal), dimension(:), allocatable x_global_rtp
real(kind=kreal), dimension(:), allocatable x_global_rtm
real(kind=kreal), dimension(:), allocatable x_global_rlm
real(kind=kreal), dimension(:), allocatable x_global_rj
real(kind=kreal), dimension(:), allocatable x_rtp_recieve
real(kind=kreal), dimension(:), allocatable x_rtm_recieve
real(kind=kreal), dimension(:), allocatable x_rlm_recieve
real(kind=kreal), dimension(:), allocatable x_rj_recieve
Function/Subroutine Documentation
allocate_real_sph_test()
subroutine cmp_trans_sph_tests::allocate_real_sph_test (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) nnod_rtm, integer(kind = kint), intent(in) nnod_rlm, integer(kind = kint), intent(in) nnod_rj)
Definition at line 47 of file cmp_trans_sph_tests.f90.
References x_global_rj, x_global_rlm, x_global_rtm, x_global_rtp, x_rj_recieve, x_rlm_recieve, x_rtm_recieve, and x_rtp_recieve.
Referenced by analyzer_test_sph::analyze_test_sph().
compare_transfer_sph_reals()
integer(kind = kint) function cmp_trans_sph_tests::compare_transfer_sph_reals (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) id_check, type(sph_grids), intent(in) sph)
Definition at line 357 of file cmp_trans_sph_tests.f90.
References cmp_trans_sph_indices::idx_rj_recieve, cmp_trans_sph_indices::idx_rlm_recieve, cmp_trans_sph_indices::idx_rtm_recieve, cmp_trans_sph_indices::idx_rtp_recieve, x_global_rj, x_global_rlm, x_global_rtm, x_global_rtp, x_rj_recieve, x_rlm_recieve, x_rtm_recieve, and x_rtp_recieve.
Referenced by analyzer_test_sph::analyze_test_sph().
deallocate_real_sph_test()
subroutine cmp_trans_sph_tests::deallocate_real_sph_test
Definition at line 77 of file cmp_trans_sph_tests.f90.
References x_global_rj, x_global_rlm, x_global_rtm, x_global_rtp, x_rj_recieve, x_rlm_recieve, x_rtm_recieve, and x_rtp_recieve.
Referenced by analyzer_test_sph::analyze_test_sph().
set_real_4_sph_transfer_test()
subroutine, private cmp_trans_sph_tests::set_real_4_sph_transfer_test (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) nnod_rtm, integer(kind = kint), intent(in) nnod_rlm, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), dimension(nnod_rtp,3), intent(in) idx_global_rtp, integer(kind = kint), dimension(nnod_rtm,3), intent(in) idx_global_rtm, integer(kind = kint), dimension(nnod_rlm,2), intent(in) idx_global_rlm, integer(kind = kint), dimension(nnod_rj,2), intent(in) idx_global_rj) private
Definition at line 309 of file cmp_trans_sph_tests.f90.
References x_global_rj, x_global_rlm, x_global_rtm, and x_global_rtp.
Referenced by set_transfer_sph_reals().
set_transfer_sph_reals()
subroutine, private cmp_trans_sph_tests::set_transfer_sph_reals (integer(kind = kint), intent(in) NB, type(sph_rtp_grid), intent(in) sph_rtp, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_rj_grid), intent(in) sph_rj) private
Definition at line 288 of file cmp_trans_sph_tests.f90.
References set_real_4_sph_transfer_test().
Referenced by sph_transfer_test_1(), sph_transfer_test_2(), sph_transfer_test_3(), sph_transfer_test_6(), and sph_transfer_test_n().
sph_transfer_test_1()
subroutine cmp_trans_sph_tests::sph_transfer_test_1 (integer(kind = kint), intent(in) iflag_recv, type(sph_grids), intent(in) sph, type(sph_comm_tables), intent(in) comms_sph)
Definition at line 89 of file cmp_trans_sph_tests.f90.
References calypso_mpi::my_rank, spherical_srs_n::send_recv_sph_trans(), set_transfer_sph_reals(), x_global_rj, x_global_rlm, x_global_rtm, x_global_rtp, x_rj_recieve, x_rlm_recieve, x_rtm_recieve, and x_rtp_recieve.
Referenced by analyzer_test_sph::analyze_test_sph().
sph_transfer_test_2()
subroutine cmp_trans_sph_tests::sph_transfer_test_2 (integer(kind = kint), intent(in) iflag_recv, type(sph_grids), intent(in) sph, type(sph_comm_tables), intent(in) comms_sph)
Definition at line 128 of file cmp_trans_sph_tests.f90.
References calypso_mpi::my_rank, spherical_srs_n::send_recv_sph_trans_2(), set_transfer_sph_reals(), x_global_rj, x_global_rlm, x_global_rtm, x_global_rtp, x_rj_recieve, x_rlm_recieve, x_rtm_recieve, and x_rtp_recieve.
Referenced by analyzer_test_sph::analyze_test_sph().
sph_transfer_test_3()
subroutine cmp_trans_sph_tests::sph_transfer_test_3 (integer(kind = kint), intent(in) iflag_recv, type(sph_grids), intent(in) sph, type(sph_comm_tables), intent(in) comms_sph)
Definition at line 167 of file cmp_trans_sph_tests.f90.
References calypso_mpi::my_rank, spherical_srs_n::send_recv_sph_trans_3(), set_transfer_sph_reals(), x_global_rj, x_global_rlm, x_global_rtm, x_global_rtp, x_rj_recieve, x_rlm_recieve, x_rtm_recieve, and x_rtp_recieve.
Referenced by analyzer_test_sph::analyze_test_sph().
sph_transfer_test_6()
subroutine cmp_trans_sph_tests::sph_transfer_test_6 (integer(kind = kint), intent(in) iflag_recv, type(sph_grids), intent(in) sph, type(sph_comm_tables), intent(in) comms_sph)
Definition at line 206 of file cmp_trans_sph_tests.f90.
References calypso_mpi::my_rank, spherical_srs_n::send_recv_sph_trans_6(), set_transfer_sph_reals(), x_global_rj, x_global_rlm, x_global_rtm, x_global_rtp, x_rj_recieve, x_rlm_recieve, x_rtm_recieve, and x_rtp_recieve.
Referenced by analyzer_test_sph::analyze_test_sph().
sph_transfer_test_n()
subroutine cmp_trans_sph_tests::sph_transfer_test_n (integer(kind = kint), intent(in) iflag_recv, integer(kind = kint), intent(in) NB, type(sph_grids), intent(in) sph, type(sph_comm_tables), intent(in) comms_sph)
Definition at line 245 of file cmp_trans_sph_tests.f90.
References calypso_mpi::my_rank, spherical_srs_n::send_recv_sph_trans_n(), set_transfer_sph_reals(), x_global_rj, x_global_rlm, x_global_rtm, x_global_rtp, x_rj_recieve, x_rlm_recieve, x_rtm_recieve, and x_rtp_recieve.
Referenced by analyzer_test_sph::analyze_test_sph().
Variable Documentation
x_global_rj
real(kind = kreal), dimension(:), allocatable cmp_trans_sph_tests::x_global_rj
Definition at line 32 of file cmp_trans_sph_tests.f90.
Referenced by allocate_real_sph_test(), compare_transfer_sph_reals(), deallocate_real_sph_test(), set_real_4_sph_transfer_test(), sph_transfer_test_1(), sph_transfer_test_2(), sph_transfer_test_3(), sph_transfer_test_6(), and sph_transfer_test_n().
x_global_rlm
real(kind = kreal), dimension(:), allocatable cmp_trans_sph_tests::x_global_rlm
Definition at line 31 of file cmp_trans_sph_tests.f90.
Referenced by allocate_real_sph_test(), compare_transfer_sph_reals(), deallocate_real_sph_test(), set_real_4_sph_transfer_test(), sph_transfer_test_1(), sph_transfer_test_2(), sph_transfer_test_3(), sph_transfer_test_6(), and sph_transfer_test_n().
x_global_rtm
real(kind = kreal), dimension(:), allocatable cmp_trans_sph_tests::x_global_rtm
Definition at line 30 of file cmp_trans_sph_tests.f90.
Referenced by allocate_real_sph_test(), compare_transfer_sph_reals(), deallocate_real_sph_test(), set_real_4_sph_transfer_test(), sph_transfer_test_1(), sph_transfer_test_2(), sph_transfer_test_3(), sph_transfer_test_6(), and sph_transfer_test_n().
x_global_rtp
real(kind = kreal), dimension(:), allocatable cmp_trans_sph_tests::x_global_rtp
Definition at line 29 of file cmp_trans_sph_tests.f90.
Referenced by allocate_real_sph_test(), compare_transfer_sph_reals(), deallocate_real_sph_test(), set_real_4_sph_transfer_test(), sph_transfer_test_1(), sph_transfer_test_2(), sph_transfer_test_3(), sph_transfer_test_6(), and sph_transfer_test_n().
x_rj_recieve
real(kind = kreal), dimension(:), allocatable cmp_trans_sph_tests::x_rj_recieve
Definition at line 37 of file cmp_trans_sph_tests.f90.
Referenced by allocate_real_sph_test(), compare_transfer_sph_reals(), deallocate_real_sph_test(), sph_transfer_test_1(), sph_transfer_test_2(), sph_transfer_test_3(), sph_transfer_test_6(), and sph_transfer_test_n().
x_rlm_recieve
real(kind = kreal), dimension(:), allocatable cmp_trans_sph_tests::x_rlm_recieve
Definition at line 36 of file cmp_trans_sph_tests.f90.
Referenced by allocate_real_sph_test(), compare_transfer_sph_reals(), deallocate_real_sph_test(), sph_transfer_test_1(), sph_transfer_test_2(), sph_transfer_test_3(), sph_transfer_test_6(), and sph_transfer_test_n().
x_rtm_recieve
real(kind = kreal), dimension(:), allocatable cmp_trans_sph_tests::x_rtm_recieve
Definition at line 35 of file cmp_trans_sph_tests.f90.
Referenced by allocate_real_sph_test(), compare_transfer_sph_reals(), deallocate_real_sph_test(), sph_transfer_test_1(), sph_transfer_test_2(), sph_transfer_test_3(), sph_transfer_test_6(), and sph_transfer_test_n().
x_rtp_recieve
real(kind = kreal), dimension(:), allocatable cmp_trans_sph_tests::x_rtp_recieve
Definition at line 34 of file cmp_trans_sph_tests.f90.
Referenced by allocate_real_sph_test(), compare_transfer_sph_reals(), deallocate_real_sph_test(), sph_transfer_test_1(), sph_transfer_test_2(), sph_transfer_test_3(), sph_transfer_test_6(), and sph_transfer_test_n().