CALYPSO: const_edge_4_viewer Module Reference
const_edge_4_viewer Module Reference
Functions/Subroutines
subroutine construct_edge_4_viewer (nnod_4_surf, edge, view_mesh, domain_grps, view_ele_grps, view_sf_grps)
subroutine, private const_all_edge_4_viewer (nnod_4_surf, edge, view_mesh, ed_sf_tbl)
subroutine, private construct_edge_4_domain (nnod_4_surf, view_mesh, domain_surf_grp, domain_edge_grp, ed_sf_tbl)
subroutine, private count_nedge_domain_4_domain (view_mesh, domain_edge_grp)
subroutine, private count_nedge_ele_grp_4_domain (view_mesh, ngrp_ele_sf, ele_edge_grp)
Variables
type(sum_hash_tbl), save, private edge_sf_tbl
Function/Subroutine Documentation
const_all_edge_4_viewer()
subroutine, private const_edge_4_viewer::const_all_edge_4_viewer (integer(kind = kint), intent(in) nnod_4_surf, type(edge_data), intent(in) edge, type(viewer_mesh_data), intent(inout) view_mesh, type(sum_hash_tbl), intent(inout) ed_sf_tbl) private
Definition at line 84 of file const_edge_4_viewer.f90.
References t_viewer_mesh::alloc_edge_data_4_sf(), t_sum_hash::clear_sum_hash(), set_edge_hash_by_sf::const_edge_hash_4_sf(), set_edge_data_by_sf::count_num_edges_by_sf(), and set_edge_data_by_sf::set_edges_connect_by_sf().
Referenced by construct_edge_4_viewer().
construct_edge_4_domain()
subroutine, private const_edge_4_viewer::construct_edge_4_domain (integer(kind = kint), intent(in) nnod_4_surf, type(viewer_mesh_data), intent(in) view_mesh, type(viewer_group_data), intent(in) domain_surf_grp, type(viewer_group_data), intent(inout) domain_edge_grp, type(sum_hash_tbl), intent(inout) ed_sf_tbl) private
Definition at line 128 of file const_edge_4_viewer.f90.
References t_viewer_group::alloc_merged_group_item(), t_sum_hash::clear_sum_hash(), set_edge_hash_by_sf::const_part_edge_hash_4_sf(), set_edge_data_by_sf::count_num_edges_by_sf(), and set_edge_data_by_sf::set_part_edges_4_sf().
Referenced by construct_edge_4_viewer().
construct_edge_4_viewer()
subroutine const_edge_4_viewer::construct_edge_4_viewer (integer(kind = kint), intent(in) nnod_4_surf, type(edge_data), intent(in) edge, type(viewer_mesh_data), intent(inout) view_mesh, type(viewer_surface_groups), intent(inout) domain_grps, type(viewer_surface_groups), intent(inout) view_ele_grps, type(viewer_surface_groups), intent(inout) view_sf_grps)
Definition at line 39 of file const_edge_4_viewer.f90.
References t_sum_hash::alloc_sum_hash(), const_all_edge_4_viewer(), construct_edge_4_domain(), const_grp_edge_4_viewer::construct_edge_4_ele_grp(), const_grp_edge_4_viewer::construct_edge_4_surf_grp(), count_nedge_domain_4_domain(), count_nedge_ele_grp_4_domain(), t_sum_hash::dealloc_sum_hash(), edge_sf_tbl, and m_geometry_constants::nedge_4_surf.
Referenced by const_kemoview_mesh::const_surf_mesh_4_viewer().
count_nedge_domain_4_domain()
subroutine, private const_edge_4_viewer::count_nedge_domain_4_domain (type(viewer_mesh_data), intent(in) view_mesh, type(viewer_group_data), intent(inout) domain_edge_grp) private
Definition at line 172 of file const_edge_4_viewer.f90.
Referenced by construct_edge_4_viewer().
count_nedge_ele_grp_4_domain()
subroutine, private const_edge_4_viewer::count_nedge_ele_grp_4_domain (type(viewer_mesh_data), intent(in) view_mesh, integer(kind = kint), intent(in) ngrp_ele_sf, type(viewer_group_data), intent(inout) ele_edge_grp) private
Definition at line 192 of file const_edge_4_viewer.f90.
Referenced by construct_edge_4_viewer().
Variable Documentation
edge_sf_tbl
type(sum_hash_tbl), save, private const_edge_4_viewer::edge_sf_tbl private
Definition at line 26 of file const_edge_4_viewer.f90.
Referenced by construct_edge_4_viewer().