CALYPSO: cal_fdm_coefs_4_boundaries Module Reference
cal_fdm_coefs_4_boundaries Module Reference
Obtain FDM matrix for basic boundary conditions at boundaries.
Functions/Subroutines
subroutine cal_fdm1_coef_fix_fld_icb (r_from_ICB, fdm1_fix_fld_ICB)
subroutine cal_fdm2_coef_fix_fld_icb (r_from_ICB, fdm2_fix_fld_ICB)
subroutine cal_fdm2_coef_fix_df_icb (r_from_ICB, fdm2_fix_dr_ICB)
subroutine cal_fdm1_coef_fix_fld_cmb (r_from_CMB1, fdm1_fix_fld_CMB)
subroutine cal_fdm2_coef_fix_fld_cmb (r_from_CMB2, fdm2_fix_fld_CMB)
subroutine cal_fdm2_coef_fix_df_cmb (r_from_CMB1, fdm2_fix_dr_CMB)
Variables
real(kind=kreal), dimension(3, 3), private mat_fdm_icb_fix_2
Work matrix to evaluate fdm2_fix_fld_ICB(0:2,3)
real(kind=kreal), dimension(3, 3), private mat_fdm_icb_fix_dr_2
Work matrix to evaluate fdm2_fix_dr_ICB(-1:1,3)
real(kind=kreal), dimension(3, 3), private mat_fdm_cmb_fix_2
Work matrix to evaluate fdm2_fix_fld_CMB(0:2,3)
real(kind=kreal), dimension(3, 3), private mat_fdm_cmb_fix_dr_2
Work matrix to evaluate fdm2_fix_dr_CMB(-1:1,3)
Detailed Description
Obtain FDM matrix for basic boundary conditions at boundaries.
      subroutine cal_fdm1_coef_fix_fld_ICB(r_from_ICB,                &
     &          fdm1_fix_fld_ICB)
      subroutine cal_fdm2_coef_fix_fld_ICB(r_from_ICB,                &
     &          fdm2_fix_fld_ICB)
      subroutine cal_fdm2_coef_fix_df_ICB(r_from_ICB,                 &
     &          fdm2_fix_dr_ICB)
      subroutine cal_fdm1_coef_fix_fld_CMB(r_from_CMB1,               &
     &          fdm1_fix_fld_CMB)
      subroutine cal_fdm2_coef_fix_fld_CMB(r_from_CMB2,               &
     &          fdm2_fix_fld_CMB)
      subroutine cal_fdm2_coef_fix_df_CMB(r_from_CMB1,                &
     &          fdm2_fix_dr_CMB)
   Matrix for derivatives with fixed field
    at inner boundary of the shell
      dfdr =      fdm1_fix_fld_ICB( 0,2) * d_rj(ICB  )
                + fdm1_fix_fld_ICB( 1,2) * d_rj(ICB+1)
      dfdr =      fdm2_fix_fld_ICB( 0,2) * d_rj(ICB  )
                + fdm2_fix_fld_ICB( 1,2) * d_rj(ICB+1)
                + fdm2_fix_fld_ICB( 2,2) * d_rj(ICB+2)
      d2fdr2 =    fdm2_fix_fld_ICB( 0,3) * d_rj(ICB  )
                + fdm2_fix_fld_ICB( 1,3) * d_rj(ICB+1)
                + fdm2_fix_fld_ICB( 2,3) * d_rj(ICB+2)
   Matrix for field and 2nd derivatives with fixed gradient
    at inner boundary of the shell
      d_rj(k) =   fdm2_fix_dr_ICB(-1,2) * dfdr(ICB)
                + fdm2_fix_dr_ICB( 0,2) * d_rj(ICB  )
                + fdm2_fix_dr_ICB( 1,2) * d_rj(ICB+1)
      d2fdr2 =    fdm2_fix_dr_ICB(-1,3) * dfdr(ICB)
                + fdm2_fix_dr_ICB( 0,3) * d_rj(ICB  )
                + fdm2_fix_dr_ICB( 1,3) * d_rj(ICB+1)
   Matrix for derivatives with fixed field
    at outer boundary of the shell
      dfdr =      fdm1_fix_fld_CMB( 1,2) * d_rj(CMB-1)
                + fdm1_fix_fld_CMB( 0,2) * d_rj(CMB  )
      dfdr =      fdm2_fix_fld_CMB( 2,2) * d_rj(CMB-2)
                + fdm2_fix_fld_CMB( 1,2) * d_rj(CMB-1)
                + fdm2_fix_fld_CMB( 0,2) * d_rj(CMB  )
      d2fdr2 =    fdm2_fix_fld_CMB( 2,3) * d_rj(CMB-2)
                + fdm2_fix_fld_CMB( 1,3) * d_rj(CMB-1)
                + fdm2_fix_fld_CMB( 0,3) * d_rj(CMB  )
   Matrix for field and 2nd derivatives with fixed gradient
    at outer boundary of the shell
      d_rj(k) =  fdm2_fix_dr_CMB(-1,1) * d_rj(CMB-1)
               + fdm2_fix_dr_CMB( 0,1) * d_rj(CMB  )
               + fdm2_fix_dr_CMB( 1,1) * dfdr(CMB)
      d2fdr2 =   fdm2_fix_dr_CMB(-1,3) * d_rj(CMB-1)
               + fdm2_fix_dr_CMB( 0,3) * d_rj(CMB  )
               + fdm2_fix_dr_CMB( 1,3) * dfdr(CMB)
Parameters
r_from_ICB(0:2) radius to teo next points of ICB
r_from_CMB2(-2:0) radius from two next points to CMB
r_from_CMB1(-1:0) radius from next points to CMB
Function/Subroutine Documentation
cal_fdm1_coef_fix_fld_cmb()
subroutine cal_fdm_coefs_4_boundaries::cal_fdm1_coef_fix_fld_cmb (real(kind = kreal), dimension(-1:0), intent(in) r_from_CMB1, real(kind = kreal), dimension(0:1,2), intent(inout) fdm1_fix_fld_CMB)
Definition at line 236 of file cal_fdm_coefs_4_boundaries.f90.
References m_constants::one, and m_constants::zero.
Referenced by t_boundary_params_sph_mhd::cal_fdm_coefs_4_bcs().
cal_fdm1_coef_fix_fld_icb()
subroutine cal_fdm_coefs_4_boundaries::cal_fdm1_coef_fix_fld_icb (real(kind = kreal), dimension(0:1), intent(in) r_from_ICB, real(kind = kreal), dimension(0:1,2), intent(inout) fdm1_fix_fld_ICB)
Definition at line 135 of file cal_fdm_coefs_4_boundaries.f90.
References m_constants::one, and m_constants::zero.
Referenced by t_boundary_params_sph_mhd::cal_fdm_coefs_4_bcs().
cal_fdm2_coef_fix_df_cmb()
subroutine cal_fdm_coefs_4_boundaries::cal_fdm2_coef_fix_df_cmb (real(kind = kreal), dimension(-1:0), intent(in) r_from_CMB1, real(kind = kreal), dimension(-1:1,3), intent(inout) fdm2_fix_dr_CMB)
Definition at line 297 of file cal_fdm_coefs_4_boundaries.f90.
References cal_inverse_small_matrix::cal_inverse_33_matrix(), mat_fdm_cmb_fix_dr_2, m_constants::one, m_constants::two, and m_constants::zero.
Referenced by t_boundary_params_sph_mhd::cal_fdm_coefs_4_bcs().
cal_fdm2_coef_fix_df_icb()
subroutine cal_fdm_coefs_4_boundaries::cal_fdm2_coef_fix_df_icb (real(kind = kreal), dimension(0:1), intent(in) r_from_ICB, real(kind = kreal), dimension(-1:1,3), intent(inout) fdm2_fix_dr_ICB)
Definition at line 195 of file cal_fdm_coefs_4_boundaries.f90.
References cal_inverse_small_matrix::cal_inverse_33_matrix(), mat_fdm_icb_fix_dr_2, m_constants::one, m_constants::two, and m_constants::zero.
Referenced by t_boundary_params_sph_mhd::cal_fdm_coefs_4_bcs().
cal_fdm2_coef_fix_fld_cmb()
subroutine cal_fdm_coefs_4_boundaries::cal_fdm2_coef_fix_fld_cmb (real(kind = kreal), dimension(-2:0), intent(in) r_from_CMB2, real(kind = kreal), dimension(0:2,3), intent(inout) fdm2_fix_fld_CMB)
Definition at line 256 of file cal_fdm_coefs_4_boundaries.f90.
References cal_inverse_small_matrix::cal_inverse_33_matrix(), mat_fdm_cmb_fix_2, m_constants::one, m_constants::two, and m_constants::zero.
Referenced by t_boundary_params_sph_mhd::cal_fdm_coefs_4_bcs().
cal_fdm2_coef_fix_fld_icb()
subroutine cal_fdm_coefs_4_boundaries::cal_fdm2_coef_fix_fld_icb (real(kind = kreal), dimension(0:2), intent(in) r_from_ICB, real(kind = kreal), dimension(0:2,3), intent(inout) fdm2_fix_fld_ICB)
Definition at line 155 of file cal_fdm_coefs_4_boundaries.f90.
References cal_inverse_small_matrix::cal_inverse_33_matrix(), mat_fdm_icb_fix_2, m_constants::one, m_constants::two, and m_constants::zero.
Referenced by t_boundary_params_sph_mhd::cal_fdm_coefs_4_bcs().
Variable Documentation
mat_fdm_cmb_fix_2
real(kind = kreal), dimension(3,3), private cal_fdm_coefs_4_boundaries::mat_fdm_cmb_fix_2 private
Work matrix to evaluate fdm2_fix_fld_CMB(0:2,3)
      dfdr =      mat_fdm_CMB_fix_2(2,1) * d_rj(CMB  )
                + mat_fdm_CMB_fix_2(2,2) * d_rj(CMB-1)
                + mat_fdm_CMB_fix_2(2,3) * d_rj(CMB-2)
      d2fdr2 =    mat_fdm_CMB_fix_2(3,1) * d_rj(CMB  )
                + mat_fdm_CMB_fix_2(3,2) * d_rj(CMB-1)
                + mat_fdm_CMB_fix_2(3,3) * d_rj(CMB-2)
Definition at line 113 of file cal_fdm_coefs_4_boundaries.f90.
Referenced by cal_fdm2_coef_fix_fld_cmb().
mat_fdm_cmb_fix_dr_2
real(kind = kreal), dimension(3,3), private cal_fdm_coefs_4_boundaries::mat_fdm_cmb_fix_dr_2 private
Work matrix to evaluate fdm2_fix_dr_CMB(-1:1,3)
      d_rj(k) =  mat_fdm_CMB_fix_dr_2(1,1) * d_rj(CMB  )
               + mat_fdm_CMB_fix_dr_2(1,2) * dfdr(CMB)
               + mat_fdm_CMB_fix_dr_2(1,3) * d_rj(CMB-1)
      d2fdr2 =   mat_fdm_CMB_fix_dr_2(3,1) * d_rj(CMB  )
               + mat_fdm_CMB_fix_dr_2(3,2) * dfdr(CMB)
               + mat_fdm_CMB_fix_dr_2(3,3) * d_rj(CMB-1)
Definition at line 124 of file cal_fdm_coefs_4_boundaries.f90.
Referenced by cal_fdm2_coef_fix_df_cmb().
mat_fdm_icb_fix_2
real(kind = kreal), dimension(3,3), private cal_fdm_coefs_4_boundaries::mat_fdm_icb_fix_2 private
Work matrix to evaluate fdm2_fix_fld_ICB(0:2,3)
      dfdr =      mat_fdm_ICB_fix_2(2,1) * d_rj(ICB  )
                + mat_fdm_ICB_fix_2(2,2) * d_rj(ICB+1)
                + mat_fdm_ICB_fix_2(2,3) * d_rj(ICB+2)
      d2fdr2 =    mat_fdm_ICB_fix_2(3,1) * d_rj(ICB  )
                + mat_fdm_ICB_fix_2(3,2) * d_rj(ICB+1)
                + mat_fdm_ICB_fix_2(3,3) * d_rj(ICB+2)
Definition at line 91 of file cal_fdm_coefs_4_boundaries.f90.
Referenced by cal_fdm2_coef_fix_fld_icb().
mat_fdm_icb_fix_dr_2
real(kind = kreal), dimension(3,3), private cal_fdm_coefs_4_boundaries::mat_fdm_icb_fix_dr_2 private
Work matrix to evaluate fdm2_fix_dr_ICB(-1:1,3)
      d_rj(k) =  mat_fdm_ICB_fix_dr_2(2,1) * d_rj(ICB  )
               + mat_fdm_ICB_fix_dr_2(2,2) * dfdr(ICB)
               + mat_fdm_ICB_fix_dr_2(2,3) * d_rj(ICB+1)
      d2fdr2 =   mat_fdm_ICB_fix_dr_2(3,1) * d_rj(ICB  )
               + mat_fdm_ICB_fix_dr_2(3,2) * dfdr(ICB)
               + mat_fdm_ICB_fix_dr_2(3,3) * d_rj(ICB+1)
Definition at line 102 of file cal_fdm_coefs_4_boundaries.f90.
Referenced by cal_fdm2_coef_fix_df_icb().