CALYPSO: set_comm_table_rtp_fftw Module Reference
set_comm_table_rtp_fftw Module Reference
communication table from FFTW
Functions/Subroutines
subroutine set_comm_item_rtp_4_fftw (nnod_rtp, ntot_sr_rtp, irev_sr_rtp, irt_rtp_smp_stack, Nfft_c, aNfft, comm_sph_FFTW)
subroutine copy_rtp_comp_fftw_to_send (nd, nnod_rtp, irev_sr_rtp, irt_rtp_smp_stack, ncomp_fwd, Nfft_c, aNfft, C_fft, n_WS, WS)
subroutine copy_rtp_field_fftw_to_send (nnod_rtp, irev_sr_rtp, irt_rtp_smp_stack, ncomp_fwd, Nfft_c, aNfft, C_fft, n_WS, WS)
subroutine copy_rtp_fftw_comp_from_recv (nd, nnod_rtp, irev_sr_rtp, irt_rtp_smp_stack, ncomp_bwd, n_WR, WR, Nfft_c, C_fft)
subroutine copy_rtp_fftw_field_from_recv (nnod_rtp, irev_sr_rtp, irt_rtp_smp_stack, ncomp_bwd, n_WR, WR, Nfft_c, C_fft)
Detailed Description
communication table from FFTW
      subroutine set_comm_item_rtp_4_FFTW                             &
     &         (nnod_rtp, ntot_sr_rtp, irev_sr_rtp,                   &
     &          irt_rtp_smp_stack, Nfft_c, aNfft, comm_sph_FFTW)
        type(comm_tbl_from_FFTW), intent(inout) :: comm_sph_FFTW
      subroutine copy_rtp_comp_FFTW_to_send                           &
     &         (nd, nnod_rtp, irev_sr_rtp, irt_rtp_smp_stack,         &
     &          ncomp_fwd, Nfft_c, aNfft, C_fft, n_WS, WS)
      subroutine copy_rtp_field_FFTW_to_send                          &
     &         (nnod_rtp, irev_sr_rtp, irt_rtp_smp_stack,             &
     &          ncomp_fwd, Nfft_c, aNfft, C_fft, n_WS, WS)
      subroutine copy_rtp_FFTW_comp_from_recv                         &
     &         (nd, nnod_rtp, irev_sr_rtp, irt_rtp_smp_stack,         &
     &          ncomp_bwd, n_WR, WR, Nfft_c, C_fft)
      subroutine copy_rtp_FFTW_field_from_recv                        &
     &         (nnod_rtp, irev_sr_rtp, irt_rtp_smp_stack,             &
     &          ncomp_bwd, n_WR, WR, Nfft_c, C_fft)
Function/Subroutine Documentation
copy_rtp_comp_fftw_to_send()
subroutine set_comm_table_rtp_fftw::copy_rtp_comp_fftw_to_send (integer(kind = kint), intent(in) nd, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(nnod_rtp), intent(in) irev_sr_rtp, integer(kind = kint), dimension(0:np_smp), intent(in) irt_rtp_smp_stack, integer(kind = kint), intent(in) ncomp_fwd, integer(kind = kint), intent(in) Nfft_c, real(kind = kreal), intent(in) aNfft, complex(kind = fftw_complex), dimension(irt_rtp_smp_stack(np_smp)*nfft_c), intent(in) C_fft, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 128 of file set_comm_table_rtp_FFTW.f90.
References m_machine_parameter::np_smp, and m_constants::two.
copy_rtp_fftw_comp_from_recv()
subroutine set_comm_table_rtp_fftw::copy_rtp_fftw_comp_from_recv (integer(kind = kint), intent(in) nd, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(nnod_rtp), intent(in) irev_sr_rtp, integer(kind = kint), dimension(0:np_smp), intent(in) irt_rtp_smp_stack, integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), intent(in) n_WR, real(kind=kreal), dimension(n_wr), intent(in) WR, integer(kind = kint), intent(in) Nfft_c, complex(kind = fftw_complex), dimension(irt_rtp_smp_stack(np_smp)*nfft_c), intent(inout) C_fft)
Definition at line 247 of file set_comm_table_rtp_FFTW.f90.
References m_constants::half, and m_constants::zero.
Referenced by sph_rtp_domain_fftw::rtp_field_back_fftw_from_recv().
copy_rtp_fftw_field_from_recv()
subroutine set_comm_table_rtp_fftw::copy_rtp_fftw_field_from_recv (integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(nnod_rtp), intent(in) irev_sr_rtp, integer(kind = kint), dimension(0:np_smp), intent(in) irt_rtp_smp_stack, integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(in) WR, integer(kind = kint), intent(in) Nfft_c, complex(kind = fftw_complex), dimension(ncomp_bwd*nfft_c), intent(inout) C_fft)
Definition at line 306 of file set_comm_table_rtp_FFTW.f90.
References m_constants::half, and m_constants::zero.
Referenced by sph_rtp_fftw::rtp_back_fftw_from_recv().
copy_rtp_field_fftw_to_send()
subroutine set_comm_table_rtp_fftw::copy_rtp_field_fftw_to_send (integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(nnod_rtp), intent(in) irev_sr_rtp, integer(kind = kint), dimension(0:np_smp), intent(in) irt_rtp_smp_stack, integer(kind = kint), intent(in) ncomp_fwd, integer(kind = kint), intent(in) Nfft_c, real(kind = kreal), intent(in) aNfft, complex(kind = fftw_complex), dimension(irt_rtp_smp_stack(np_smp)*nfft_c*ncomp_fwd), intent(in) C_fft, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 189 of file set_comm_table_rtp_FFTW.f90.
References m_constants::two.
set_comm_item_rtp_4_fftw()
subroutine set_comm_table_rtp_fftw::set_comm_item_rtp_4_fftw (integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) ntot_sr_rtp, integer(kind = kint), dimension(nnod_rtp), intent(in) irev_sr_rtp, integer(kind = kint), dimension(0:np_smp), intent(in) irt_rtp_smp_stack, integer(kind = kint), intent(in) Nfft_c, real(kind = kreal), intent(in) aNfft, type(comm_tbl_from_fftw), intent(inout) comm_sph_FFTW)
Definition at line 45 of file set_comm_table_rtp_FFTW.f90.
References m_constants::two.
Referenced by sph_rtp_fftw::init_rtp_fftw(), and sph_rtp_domain_fftw::init_rtp_field_fftw().