CALYPSO: compare_sph_with_io Module Reference
compare_sph_with_io Module Reference
Compare spherical harmonics index data and file.
Functions/Subroutines
integer(kind=kint) function s_compare_sph_with_io (sph_file_param, sph, comms_sph, sph_grps)
integer(kind=kint) function, private compare_sph_rtp_with_io (sph_params, sph_rtp, comm_rtp, sph_grps, sph_file)
integer(kind=kint) function, private compare_sph_rj_with_io (sph_params, sph_rj, comm_rj, sph_grps, sph_file)
integer(kind=kint) function, private compare_sph_rtm_with_io (sph_params, sph_rtm, comm_rtm, sph_file)
integer(kind=kint) function, private compare_sph_rlm_with_io (sph_params, sph_rlm, comm_rlm, sph_file)
Variables
type(sph_file_data_type), save, private sph_file_l
Detailed Description
Compare spherical harmonics index data and file.
      integer(kind = kint) function s_compare_sph_with_IO             &
     &                   (sph_file_param, sph, comms_sph, sph_grps)
        type(field_IO_params), intent(in) ::  sph_file_param
        type(sph_grids), intent(in) :: sph
        type(sph_comm_tables), intent(in) :: comms_sph
        type(sph_group_data), intent(in) ::  sph_grps
Function/Subroutine Documentation
compare_sph_rj_with_io()
integer(kind = kint) function, private compare_sph_with_io::compare_sph_rj_with_io (type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(sph_comm_tbl), intent(in) comm_rj, type(sph_group_data), intent(in) sph_grps, type(sph_file_data_type), intent(in) sph_file) private
Definition at line 164 of file compare_sph_with_IO.f90.
References copy_sph_comm_table_4_io::compare_comm_sph_with_comm_tbl(), set_group_types_4_io::compare_gruop_stracture(), copy_sph_rj_mode_4_io::compare_sph_node_rj_with_io(), and m_machine_parameter::e_message.
Referenced by s_compare_sph_with_io().
compare_sph_rlm_with_io()
integer(kind = kint) function, private compare_sph_with_io::compare_sph_rlm_with_io (type(sph_shell_parameters), intent(in) sph_params, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_comm_tbl), intent(in) comm_rlm, type(sph_file_data_type), intent(in) sph_file) private
Definition at line 246 of file compare_sph_with_IO.f90.
References copy_sph_comm_table_4_io::compare_comm_sph_with_comm_tbl(), copy_sph_rlm_mode_4_io::compare_sph_mode_rlm_with_io(), and m_machine_parameter::e_message.
Referenced by s_compare_sph_with_io().
compare_sph_rtm_with_io()
integer(kind = kint) function, private compare_sph_with_io::compare_sph_rtm_with_io (type(sph_shell_parameters), intent(in) sph_params, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_comm_tbl), intent(in) comm_rtm, type(sph_file_data_type), intent(in) sph_file) private
Definition at line 213 of file compare_sph_with_IO.f90.
References copy_sph_comm_table_4_io::compare_comm_sph_with_comm_tbl(), copy_sph_rtm_node_4_io::compare_sph_rtm_node_with_io(), and m_machine_parameter::e_message.
Referenced by s_compare_sph_with_io().
compare_sph_rtp_with_io()
integer(kind = kint) function, private compare_sph_with_io::compare_sph_rtp_with_io (type(sph_shell_parameters), intent(in) sph_params, type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, type(sph_group_data), intent(in) sph_grps, type(sph_file_data_type), intent(in) sph_file) private
Definition at line 100 of file compare_sph_with_IO.f90.
References copy_sph_comm_table_4_io::compare_comm_sph_with_comm_tbl(), set_group_types_4_io::compare_gruop_stracture(), copy_sph_rtp_node_4_io::compare_sph_rtp_node_with_io(), and m_machine_parameter::e_message.
Referenced by s_compare_sph_with_io().
s_compare_sph_with_io()
integer(kind = kint) function compare_sph_with_io::s_compare_sph_with_io (type(field_io_params), intent(in) sph_file_param, type(sph_grids), intent(in) sph, type(sph_comm_tables), intent(in) comms_sph, type(sph_group_data), intent(in) sph_grps)
Definition at line 48 of file compare_sph_with_IO.f90.
References compare_sph_rj_with_io(), compare_sph_rlm_with_io(), compare_sph_rtm_with_io(), compare_sph_rtp_with_io(), t_spheric_data_io::dealloc_rj_mode_io(), t_spheric_data_io::dealloc_rlm_mode_io(), t_spheric_data_io::dealloc_rtm_grid_io(), t_spheric_data_io::dealloc_rtp_grid_io(), m_machine_parameter::iflag_debug, calypso_mpi::my_rank, calypso_mpi::nprocs, sph_file_mpi_io_select::sel_mpi_read_geom_rtm_file(), sph_file_mpi_io_select::sel_mpi_read_geom_rtp_file(), sph_file_mpi_io_select::sel_mpi_read_modes_rlm_file(), sph_file_mpi_io_select::sel_mpi_read_spectr_rj_file(), and sph_file_l.
Referenced by analyzer_check_sph_grids::analyze_check_sph_grids().
Variable Documentation
sph_file_l
type(sph_file_data_type), save, private compare_sph_with_io::sph_file_l private
Definition at line 37 of file compare_sph_with_IO.f90.
Referenced by s_compare_sph_with_io().