CALYPSO: data_convert_by_zlib Module Reference
data_convert_by_zlib Module Reference
BAse routines to compress and decompress data.
Functions/Subroutines
subroutine defleate_endian_flag (zbuf)
subroutine defleate_int8_vector_b (num, int8_dat, zbuf)
subroutine defleate_1d_vector_b (num, real_dat, zbuf)
subroutine defleate_1d_character_b (num, chara_dat, zbuf)
subroutine infleate_endian_flag (id_rank, iflag_swap, zbuf)
subroutine infleate_int8_vector_b (num, int8_dat, zbuf)
subroutine infleate_1d_vector_b (num, real_dat, zbuf)
subroutine infleate_1d_character_b (num, chara_dat, zbuf)
Detailed Description
BAse routines to compress and decompress data.
      subroutine defleate_endian_flag(zbuf)
      subroutine defleate_int8_vector_b(num, int8_dat, zbuf)
      subroutine defleate_1d_vector_b(num, real_dat, zbuf)
      subroutine defleate_1d_character_b(num, chara_dat, zbuf)
        type(buffer_4_gzip), intent(inout) :: zbuf
      subroutine infleate_endian_flag(id_rank, iflag_swap, zbuf)
      subroutine infleate_int8_vector_b(num, int8_dat, zbuf)
      subroutine infleate_1d_vector_b(num, real_dat, zbuf)
      subroutine infleate_1d_character_b(num, chara_dat, zbuf)
          type(buffer_4_gzip), intent(inout) :: zbuf
Function/Subroutine Documentation
defleate_1d_character_b()
subroutine data_convert_by_zlib::defleate_1d_character_b (integer(kind = kint_gl), intent(in) num, character(len=kchara), dimension(num), intent(in) chara_dat, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 127 of file data_convert_by_zlib.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), transfer_to_long_integers::cast_long(), gzip_defleate::gzip_defleat_char_once(), m_constants::huge_30, and m_precision::kchara.
Referenced by gz_mpi_binary_head_io::gz_mpi_write_mul_charahead_b().
defleate_1d_vector_b()
subroutine data_convert_by_zlib::defleate_1d_vector_b (integer(kind = kint_gl), intent(in) num, real(kind = kreal), dimension(num), intent(in) real_dat, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 92 of file data_convert_by_zlib.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), transfer_to_long_integers::cast_long(), gzip_defleate::gzip_defleat_real_once(), m_constants::huge_30, and m_precision::kreal.
Referenced by gz_mpi_binary_data_io::gz_mpi_write_1d_vector_b(), and gz_mpi_binary_head_io::gz_mpi_write_mul_realhead_b().
defleate_endian_flag()
subroutine data_convert_by_zlib::defleate_endian_flag (type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 39 of file data_convert_by_zlib.f90.
References gzip_defleate::gzip_defleat_int4_once().
Referenced by gz_mpi_binary_head_io::gz_mpi_write_byte_flag().
defleate_int8_vector_b()
subroutine data_convert_by_zlib::defleate_int8_vector_b (integer(kind = kint_gl), intent(in) num, integer(kind = kint_gl), dimension(num), intent(in) int8_dat, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 57 of file data_convert_by_zlib.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), transfer_to_long_integers::cast_long(), gzip_defleate::gzip_defleat_int8_once(), m_constants::huge_30, and m_precision::kint_gl.
Referenced by gz_mpi_binary_data_io::gz_mpi_write_int8_vector_b(), and gz_mpi_binary_head_io::gz_mpi_write_mul_int8head_b().
infleate_1d_character_b()
subroutine data_convert_by_zlib::infleate_1d_character_b (integer(kind = kint_gl), intent(in) num, character(len=kchara), dimension(num), intent(inout) chara_dat, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 251 of file data_convert_by_zlib.f90.
References transfer_to_long_integers::cast_long(), gzip_infleate::gzip_infleat_char_once(), m_constants::huge_30, and m_precision::kchara.
Referenced by gz_mpi_binary_head_io::gz_mpi_read_mul_charahead_b().
infleate_1d_vector_b()
subroutine data_convert_by_zlib::infleate_1d_vector_b (integer(kind = kint_gl), intent(in) num, real(kind = kreal), dimension(num), intent(inout) real_dat, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 219 of file data_convert_by_zlib.f90.
References transfer_to_long_integers::cast_long(), gzip_infleate::gzip_infleat_real_once(), m_constants::huge_30, and m_precision::kreal.
Referenced by gz_mpi_binary_data_io::gz_mpi_read_1d_vector_b(), and gz_mpi_binary_head_io::gz_mpi_read_mul_realhead_b().
infleate_endian_flag()
subroutine data_convert_by_zlib::infleate_endian_flag (integer, intent(in) id_rank, integer, intent(inout) iflag_swap, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 163 of file data_convert_by_zlib.f90.
References binary_io::endian_check(), gzip_infleate::gzip_infleat_int4_once(), and m_constants::ione.
Referenced by gz_mpi_binary_head_io::gz_mpi_read_byte_check().
infleate_int8_vector_b()
subroutine data_convert_by_zlib::infleate_int8_vector_b (integer(kind = kint_gl), intent(in) num, integer(kind = kint_gl), dimension(num), intent(inout) int8_dat, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 187 of file data_convert_by_zlib.f90.
References transfer_to_long_integers::cast_long(), gzip_infleate::gzip_infleat_int8_once(), m_constants::huge_30, and m_precision::kint_gl.
Referenced by gz_mpi_binary_data_io::gz_mpi_read_int8_vector_b(), and gz_mpi_binary_head_io::gz_mpi_read_mul_int8head_b().