CALYPSO: init_sphrical_transform_mhd Module Reference
init_sphrical_transform_mhd Module Reference
Perform spherical harmonics transform for MHD dynamo model.
Functions/Subroutines
subroutine init_sph_transform_mhd (SPH_model, iphys, trans_p, WK, SPH_MHD)
subroutine init_leg_fourier_trans_mhd (sph, comms_sph, ncomp_max_trans, trans_p, WK)
subroutine sel_sph_transform_mhd (MHD_prop, sph_MHD_bc, sph, comms_sph, omega_sph, ncomp_max_trans, nvector_max_trans, nscalar_max_trans, trns_MHD, WK_leg, WK_FFTs_MHD, trans_p, gt_cor, cor_rlm, rj_fld)
subroutine init_work_4_coriolis (sph_MHD_bc, sph, trans_p, WK)
Detailed Description
Perform spherical harmonics transform for MHD dynamo model.
      subroutine init_sph_transform_MHD                               &
     &         (SPH_model, iphys, trans_p, WK, SPH_MHD)
      subroutine init_leg_fourier_trans_MHD                           &
     &         (sph, comms_sph, ncomp_max_trans, trans_p, WK)
      subroutine sel_sph_transform_MHD                                &
     &         (MHD_prop, sph_MHD_bc, sph, comms_sph, omega_sph,      &
     &          ncomp_max_trans, nvector_max_trans, nscalar_max_trans,&
     &          trns_MHD, WK_leg, WK_FFTs_MHD, trans_p, gt_cor,       &
     &          cor_rlm, rj_fld)
        type(MHD_evolution_param), intent(in) :: MHD_prop
        type(parameters_4_sph_trans), intent(inout) :: trans_p
        type(works_4_sph_trans_MHD), intent(inout) :: WK
        type(gaunt_coriolis_rlm), intent(inout) :: gt_cor
        type(coriolis_rlm_data), intent(inout) :: cor_rlm
        type(SPH_mesh_field_data), intent(inout) :: SPH_MHD
      subroutine init_work_4_coriolis(sph_MHD_bc, sph, trans_p, WK)
        type(sph_MHD_boundary_data), intent(in) :: sph_MHD_bc
        type(sph_grids), intent(inout) :: sph
        type(parameters_4_sph_trans), intent(in) :: trans_p
        type(works_4_sph_trans_MHD), intent(inout) :: WK
Function/Subroutine Documentation
init_leg_fourier_trans_mhd()
subroutine init_sphrical_transform_mhd::init_leg_fourier_trans_mhd (type(sph_grids), intent(inout) sph, type(sph_comm_tables), intent(inout) comms_sph, integer(kind = kint), intent(in) ncomp_max_trans, type(parameters_4_sph_trans), intent(inout) trans_p, type(works_4_sph_trans_mhd), intent(inout) WK)
Definition at line 119 of file init_sphrical_transform_MHD.f90.
References m_machine_parameter::iflag_debug, init_fft_4_mhd::init_fourier_transform_4_mhd(), t_sph_fft_selector::init_sph_fft_select(), init_sph_trans::initialize_legendre_trans(), calypso_mpi::my_rank, init_fft_4_mhd::set_fft_mode_4_snapshot(), and t_work_4_sph_trans::write_import_table_mode().
Referenced by init_sph_transform_mhd().
init_sph_transform_mhd()
subroutine init_sphrical_transform_mhd::init_sph_transform_mhd (type(sph_mhd_model_data), intent(in) SPH_model, type(phys_address), intent(in) iphys, type(parameters_4_sph_trans), intent(inout) trans_p, type(works_4_sph_trans_mhd), intent(inout) WK, type(sph_mesh_field_data), intent(inout) SPH_MHD)
total number of components for spherical harmonics transform
total number of vectors for spherical harmonics transform
total number of svalars for spherical harmonics transform
Definition at line 63 of file init_sphrical_transform_MHD.f90.
References t_sph_trans_arrays_mhd::alloc_sph_trans_address(), m_machine_parameter::iflag_debug, m_machine_parameter::iflag_routine_msg, init_leg_fourier_trans_mhd(), init_work_4_coriolis(), sel_sph_transform_mhd(), set_address_sph_trans_snap::set_addresses_diff_vect_trans(), set_address_sph_trans_snap::set_addresses_ene_flux_trans(), set_address_sph_trans_snap::set_addresses_snapshot_trans(), and set_address_sph_trans_mhd::set_addresses_trans_sph_mhd().
Referenced by sph_analyzer_d_bench::sph_init_sph_dbench(), sph_analyzer_snap_w_psf::sph_init_sph_snap_psf(), and sph_analyzer_mhd::sph_initialize_mhd().
init_work_4_coriolis()
subroutine init_sphrical_transform_mhd::init_work_4_coriolis (type(sph_mhd_boundary_data), intent(in) sph_MHD_bc, type(sph_grids), intent(inout) sph, type(parameters_4_sph_trans), intent(in) trans_p, type(works_4_sph_trans_mhd), intent(inout) WK)
Definition at line 212 of file init_sphrical_transform_MHD.f90.
References t_const_wz_coriolis_rtp::alloc_sphere_ave_coriolis(), m_machine_parameter::iflag_debug, and t_coriolis_terms_rlm::init_sum_coriolis_rlm().
Referenced by init_sph_transform_mhd().
sel_sph_transform_mhd()
subroutine init_sphrical_transform_mhd::sel_sph_transform_mhd (type(mhd_evolution_param), intent(in) MHD_prop, type(sph_mhd_boundary_data), intent(in) sph_MHD_bc, type(sph_grids), intent(in) sph, type(sph_comm_tables), intent(in) comms_sph, type(sph_rotation), intent(in) omega_sph, integer(kind = kint), intent(in) ncomp_max_trans, integer(kind = kint), intent(in) nvector_max_trans, integer(kind = kint), intent(in) nscalar_max_trans, type(address_4_sph_trans), intent(inout) trns_MHD, type(legendre_trns_works), intent(inout) WK_leg, type(work_for_ffts), intent(inout) WK_FFTs_MHD, type(parameters_4_sph_trans), intent(inout) trans_p, type(gaunt_coriolis_rlm), intent(inout) gt_cor, type(coriolis_rlm_data), intent(inout) cor_rlm, type(phys_data), intent(inout) rj_fld)
Definition at line 158 of file init_sphrical_transform_MHD.f90.
References skip_comment_f::change_2_upper_case(), m_legendre_transform_list::chosen_legendre_name(), m_machine_parameter::iflag_debug, calypso_mpi::my_rank, test_legendre_transforms::s_test_legendre_transforms(), and t_legendre_trans_select::sel_init_legendre_trans().
Referenced by init_sph_transform_mhd().