CALYPSO: cal_sph_exp_fixed_scalar Module Reference
cal_sph_exp_fixed_scalar Module Reference
Set fixed scalar boundarry for explicit method.
Functions/Subroutines
subroutine dsdr_sph_fix_scalar_in_2 (jmax, g_sph_rj, kr_in, r_ICB, fdm2_fix_fld_ICB, fix_ICB, is_fld, is_grd, n_point, ntot_phys_rj, d_rj)
subroutine dsdr_sph_lm0_fix_scalar_in_2 (idx_rj_degree_zero, jmax, kr_in, r_ICB, fdm2_fix_fld_ICB, fix_ICB, is_fld, is_grd, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_fix_scalar_in_diffuse2 (jmax, g_sph_rj, kr_in, r_ICB, fdm2_fix_fld_ICB, fix_ICB, coef_d, is_fld, is_diffuse, n_point, ntot_phys_rj, d_rj)
subroutine cal_dsdr_sph_no_bc_in_2 (jmax, kr_in, fdm2_fix_fld_ICB, is_fld, is_grd, n_point, ntot_phys_rj, d_rj)
subroutine dsdr_sph_fix_scalar_out_2 (jmax, g_sph_rj, kr_out, r_CMB, fdm2_fix_fld_CMB, fix_CMB, is_fld, is_grd, n_point, ntot_phys_rj, d_rj)
subroutine dsdr_sph_lm0_fix_scalar_out_2 (idx_rj_degree_zero, jmax, kr_out, r_CMB, fdm2_fix_fld_CMB, fix_CMB, is_fld, is_grd, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_out_fix_scalar_diffuse2 (jmax, g_sph_rj, kr_out, r_CMB, fdm2_fix_fld_CMB, fix_CMB, coef_d, is_fld, is_diffuse, n_point, ntot_phys_rj, d_rj)
subroutine cal_dsdr_sph_no_bc_out_2 (jmax, kr_out, fdm2_fix_fld_CMB, is_fld, is_grd, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_div_flux_4_fix_in (jmax, g_sph_rj, kr_in, r_ICB, fdm2_fix_fld_ICB, fix_ICB, is_fld, is_div, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_div_flux_4_fix_out (jmax, g_sph_rj, kr_out, r_CMB, fdm2_fix_fld_CMB, fix_CMB, is_fld, is_div, n_point, ntot_phys_rj, d_rj)
Detailed Description
Set fixed scalar boundarry for explicit method.
      subroutine dsdr_sph_fix_scalar_in_2(jmax, g_sph_rj,             &
     &          kr_in, r_ICB, fdm2_fix_fld_ICB, fix_ICB,              &
     &          is_fld, is_grd, n_point, ntot_phys_rj, d_rj)
      subroutine dsdr_sph_lm0_fix_scalar_in_2(idx_rj_degree_zero,     &
     &          jmax, kr_in, r_ICB, fdm2_fix_fld_ICB, fix_ICB,        &
     &          is_fld, is_grd, n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_fix_scalar_in_diffuse2(jmax, g_sph_rj,       &
     &          kr_in, r_ICB, fdm2_fix_fld_ICB, fix_ICB, coef_d,      &
     &          is_fld, is_diffuse, n_point, ntot_phys_rj, d_rj)
      subroutine cal_dsdr_sph_no_bc_in_2                              &
     &         (jmax, kr_in, fdm2_fix_fld_ICB, is_fld, is_grd,        &
     &          n_point, ntot_phys_rj, d_rj)
      subroutine dsdr_sph_fix_scalar_out_2(jmax, g_sph_rj,            &
     &          kr_out, r_CMB, fdm2_fix_fld_CMB, fix_CMB,             &
     &          is_fld, is_grd, n_point, ntot_phys_rj, d_rj)
      subroutine dsdr_sph_lm0_fix_scalar_out_2(idx_rj_degree_zero,    &
     &          jmax, kr_out, r_CMB, fdm2_fix_fld_CMB, fix_CMB,       &
     &          is_fld, is_grd, n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_out_fix_scalar_diffuse2(jmax, g_sph_rj,      &
     &          kr_out, r_CMB, fdm2_fix_fld_CMB, fix_CMB, coef_d,     &
     &          is_fld, is_diffuse, n_point, ntot_phys_rj, d_rj)
      subroutine cal_dsdr_sph_no_bc_out_2                             &
     &         (jmax, kr_out, fdm2_fix_fld_CMB, is_fld, is_grd,       &
     &          n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_div_flux_4_fix_in(jmax, g_sph_rj,            &
     &          kr_in, r_ICB, fdm2_fix_fld_ICB, fix_ICB,              &
     &          is_fld, is_div, n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_div_flux_4_fix_out(jmax, g_sph_rj,           &
     &          kr_out, r_CMB, fdm2_fix_fld_CMB, fix_CMB,             &
     &          is_fld, is_div, n_point, ntot_phys_rj, d_rj)
Parameters
idx_rj_degree_zero Local address for degree 0
n_point Number of points for spectrum data
jmax Number of local spherical harmonics mode
kr_in Radial ID for inner boundary
kr_out Radial ID for outer boundary
r_ICB(0:2) Radius at ICB
r_CMB(0:2) Radius at CMB
r_CTR1(0:2) Radius at innermost point
fdm2_fix_fld_ICB(0:2,3) Matrix to evaluate radial derivative at ICB with fixed field
fdm2_fix_fld_CMB(0:2,3) Matrix to evaluate radial derivative at CMB with fixed field
Parameters
fix_ICB(jmax) Spectr data for fixed scalar at ICB
fix_CMB(jmax) Spectr data for fixed scalar at CMB
fix_CTR(jmax) Spectr data for fixed scalar at center
coef_d Coefficient for diffusion term
Parameters
is_fld Field address of input field
is_grd Field address of radial gradient of field
is_diffuse Field address for diffusion of field
Parameters
ntot_phys_rj Total number of components
d_rj Spectrum data
Function/Subroutine Documentation
cal_dsdr_sph_no_bc_in_2()
subroutine cal_sph_exp_fixed_scalar::cal_dsdr_sph_no_bc_in_2 (integer(kind = kint), intent(in) jmax, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(0:2,3), intent(in) fdm2_fix_fld_ICB, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_grd, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 200 of file cal_sph_exp_fixed_scalar.f90.
Referenced by select_exp_velocity_cmb::sel_cmb_sph_vort_diffusion(), select_exp_magne_icb::sel_icb_sph_magnetic_diffusion(), and select_exp_velocity_icb::sel_icb_sph_viscous_diffusion().
cal_dsdr_sph_no_bc_out_2()
subroutine cal_sph_exp_fixed_scalar::cal_dsdr_sph_no_bc_out_2 (integer(kind = kint), intent(in) jmax, integer(kind = kint), intent(in) kr_out, real(kind = kreal), dimension(0:2,3), intent(in) fdm2_fix_fld_CMB, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_grd, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 350 of file cal_sph_exp_fixed_scalar.f90.
Referenced by select_exp_magne_cmb::sel_cmb_sph_magnetic_diffusion(), select_exp_velocity_cmb::sel_cmb_sph_viscous_diffusion(), and select_exp_velocity_cmb::sel_cmb_sph_vort_diffusion().
cal_sph_div_flux_4_fix_in()
subroutine cal_sph_exp_fixed_scalar::cal_sph_div_flux_4_fix_in (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(0:2), intent(in) r_ICB, real(kind = kreal), dimension(0:2,3), intent(in) fdm2_fix_fld_ICB, real(kind = kreal), dimension(jmax), intent(in) fix_ICB, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_div, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 381 of file cal_sph_exp_fixed_scalar.f90.
References m_constants::half.
Referenced by select_exp_scalar_icb::sel_icb_sph_scalar_advect().
cal_sph_div_flux_4_fix_out()
subroutine cal_sph_exp_fixed_scalar::cal_sph_div_flux_4_fix_out (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_out, real(kind = kreal), dimension(0:2), intent(in) r_CMB, real(kind = kreal), dimension(0:2,3), intent(in) fdm2_fix_fld_CMB, real(kind = kreal), dimension(jmax), intent(in) fix_CMB, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_div, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 419 of file cal_sph_exp_fixed_scalar.f90.
References m_constants::half.
Referenced by select_exp_scalar_cmb::sel_cmb_sph_scalar_advect().
cal_sph_fix_scalar_in_diffuse2()
subroutine cal_sph_exp_fixed_scalar::cal_sph_fix_scalar_in_diffuse2 (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(0:2), intent(in) r_ICB, real(kind = kreal), dimension(0:2,3), intent(in) fdm2_fix_fld_ICB, real(kind = kreal), dimension(jmax), intent(in) fix_ICB, real(kind = kreal), intent(in) coef_d, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_diffuse, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 156 of file cal_sph_exp_fixed_scalar.f90.
References m_constants::two.
Referenced by select_exp_scalar_icb::sel_icb_sph_scalar_diffusion().
cal_sph_out_fix_scalar_diffuse2()
subroutine cal_sph_exp_fixed_scalar::cal_sph_out_fix_scalar_diffuse2 (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_out, real(kind = kreal), dimension(0:2), intent(in) r_CMB, real(kind = kreal), dimension(0:2,3), intent(in) fdm2_fix_fld_CMB, real(kind = kreal), dimension(jmax), intent(in) fix_CMB, real(kind = kreal), intent(in) coef_d, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_diffuse, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 306 of file cal_sph_exp_fixed_scalar.f90.
References m_constants::two.
Referenced by select_exp_scalar_cmb::sel_cmb_sph_scalar_diffusion().
dsdr_sph_fix_scalar_in_2()
subroutine cal_sph_exp_fixed_scalar::dsdr_sph_fix_scalar_in_2 (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(0:2), intent(in) r_ICB, real(kind = kreal), dimension(0:2,3), intent(in) fdm2_fix_fld_ICB, real(kind = kreal), dimension(jmax), intent(in) fix_ICB, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_grd, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 82 of file cal_sph_exp_fixed_scalar.f90.
References m_constants::zero.
Referenced by select_exp_scalar_icb::sel_icb_radial_grad_scalar().
dsdr_sph_fix_scalar_out_2()
subroutine cal_sph_exp_fixed_scalar::dsdr_sph_fix_scalar_out_2 (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_out, real(kind = kreal), dimension(0:2), intent(in) r_CMB, real(kind = kreal), dimension(0:2,3), intent(in) fdm2_fix_fld_CMB, real(kind = kreal), dimension(jmax), intent(in) fix_CMB, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_grd, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 231 of file cal_sph_exp_fixed_scalar.f90.
References m_constants::zero.
Referenced by select_exp_scalar_cmb::sel_cmb_radial_grad_scalar().
dsdr_sph_lm0_fix_scalar_in_2()
subroutine cal_sph_exp_fixed_scalar::dsdr_sph_lm0_fix_scalar_in_2 (integer(kind = kint), intent(in) idx_rj_degree_zero, integer(kind = kint), intent(in) jmax, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(0:2), intent(in) r_ICB, real(kind = kreal), dimension(0:2,3), intent(in) fdm2_fix_fld_ICB, real(kind = kreal), dimension(jmax), intent(in) fix_ICB, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_grd, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 121 of file cal_sph_exp_fixed_scalar.f90.
References m_constants::zero.
Referenced by select_exp_scalar_icb::sel_icb_radial_grad_scalar().
dsdr_sph_lm0_fix_scalar_out_2()
subroutine cal_sph_exp_fixed_scalar::dsdr_sph_lm0_fix_scalar_out_2 (integer(kind = kint), intent(in) idx_rj_degree_zero, integer(kind = kint), intent(in) jmax, integer(kind = kint), intent(in) kr_out, real(kind = kreal), dimension(0:2), intent(in) r_CMB, real(kind = kreal), dimension(0:2,3), intent(in) fdm2_fix_fld_CMB, real(kind = kreal), dimension(jmax), intent(in) fix_CMB, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_grd, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 270 of file cal_sph_exp_fixed_scalar.f90.
References m_constants::zero.
Referenced by select_exp_scalar_cmb::sel_cmb_radial_grad_scalar().