CALYPSO: parallel_fem_mesh_init Module Reference
parallel_fem_mesh_init Module Reference
Top routines to transfer spherical harmonics grids data to FEM data for data visualization.
Functions/Subroutines
subroutine fem_mesh_initialization (mesh, group)
subroutine check_whole_num_of_elements (ele)
Detailed Description
Top routines to transfer spherical harmonics grids data to FEM data for data visualization.
      subroutine FEM_mesh_initialization(mesh, group)
        type(field_io_params), intent(in) :: mesh_file
        type(mesh_geometry), intent(inout) :: mesh
        type(mesh_groups), intent(inout) ::   group
Function/Subroutine Documentation
check_whole_num_of_elements()
subroutine parallel_fem_mesh_init::check_whole_num_of_elements (type(element_data), intent(inout) ele)
Definition at line 78 of file parallel_FEM_mesh_init.f90.
References calypso_mpi_int::calypso_mpi_allreduce_one_int(), and calypso_mpi::my_rank.
Referenced by fem_mesh_initialization().
fem_mesh_initialization()
subroutine parallel_fem_mesh_init::fem_mesh_initialization (type(mesh_geometry), intent(inout) mesh, type(mesh_groups), intent(inout) group)
Definition at line 38 of file parallel_FEM_mesh_init.f90.
References m_array_for_send_recv::allocate_vector_for_solver(), check_whole_num_of_elements(), const_element_comm_tables::const_global_mesh_infos(), const_mesh_information::const_mesh_infos(), m_machine_parameter::i_debug, m_machine_parameter::iflag_debug, m_machine_parameter::iflag_full_msg, nod_phys_send_recv::init_nod_send_recv(), calypso_mpi::my_rank, and m_phys_constants::n_sym_tensor.
Referenced by fem_analyzer_sph_mhd::fem_initialize_sph_mhd(), and load_mesh_and_field_4_viz::mesh_setup_4_viz().