CALYPSO: t_ctl_data_4_fem_mesh Module Reference
t_ctl_data_4_fem_mesh Module Reference
Data Types
type fem_mesh_control
Structure of mesh IO controls and sleeve informations.
Functions/Subroutines
subroutine read_fem_mesh_control (id_control, hd_block, Fmesh_ctl, c_buf)
subroutine write_fem_mesh_control (id_file, hd_block, Fmesh_ctl, level)
subroutine reset_fem_mesh_control (Fmesh_ctl)
Variables
character(len=kchara), parameter, private hd_mem_conserve = 'memory_conservation_ctl'
character(len=kchara), parameter, private hd_fem_mesh_output = 'FEM_mesh_output_switch'
character(len=kchara), parameter, private hd_fem_surf_output = 'FEM_surface_output_switch'
character(len=kchara), parameter, private hd_fem_viewer_output = 'FEM_viewer_mesh_output_switch'
character(len=kchara), parameter, private hd_sleeve_level = 'sleeve_level_ctl'
character(len=kchara), parameter, private hd_ele_overlap = 'element_overlap_ctl'
Function/Subroutine Documentation
read_fem_mesh_control()
subroutine t_ctl_data_4_fem_mesh::read_fem_mesh_control (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(fem_mesh_control), intent(inout) Fmesh_ctl, type(buffer_for_control), intent(inout) c_buf)
Definition at line 82 of file t_ctl_data_4_FEM_mesh.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_ele_overlap, hd_fem_mesh_output, hd_fem_surf_output, hd_fem_viewer_output, hd_mem_conserve, hd_sleeve_level, t_read_control_elements::load_one_line_from_control(), t_control_array_character::read_chara_ctl_type(), and t_control_array_integer::read_integer_ctl_type().
Referenced by t_ctl_data_gen_sph_shell::read_parallel_shell_ctl().
reset_fem_mesh_control()
subroutine t_ctl_data_4_fem_mesh::reset_fem_mesh_control (type(fem_mesh_control), intent(inout) Fmesh_ctl)
Definition at line 167 of file t_ctl_data_4_FEM_mesh.f90.
Referenced by t_ctl_data_gen_sph_shell::dealloc_parallel_shell_ctl().
write_fem_mesh_control()
subroutine t_ctl_data_4_fem_mesh::write_fem_mesh_control (integer(kind = kint), intent(in) id_file, character(len=kchara), intent(in) hd_block, type(fem_mesh_control), intent(in) Fmesh_ctl, integer(kind = kint), intent(inout) level)
Definition at line 124 of file t_ctl_data_4_FEM_mesh.f90.
References hd_ele_overlap, hd_fem_mesh_output, hd_fem_surf_output, hd_fem_viewer_output, hd_mem_conserve, hd_sleeve_level, t_control_array_character::write_chara_ctl_type(), write_control_elements::write_end_flag_for_ctl(), and t_control_array_integer::write_integer_ctl_type().
Variable Documentation
hd_ele_overlap
character(len=kchara), parameter, private t_ctl_data_4_fem_mesh::hd_ele_overlap = 'element_overlap_ctl' private
Definition at line 73 of file t_ctl_data_4_FEM_mesh.f90.
Referenced by read_fem_mesh_control(), and write_fem_mesh_control().
hd_fem_mesh_output
character(len=kchara), parameter, private t_ctl_data_4_fem_mesh::hd_fem_mesh_output = 'FEM_mesh_output_switch' private
Definition at line 64 of file t_ctl_data_4_FEM_mesh.f90.
Referenced by read_fem_mesh_control(), and write_fem_mesh_control().
hd_fem_surf_output
character(len=kchara), parameter, private t_ctl_data_4_fem_mesh::hd_fem_surf_output = 'FEM_surface_output_switch' private
Definition at line 66 of file t_ctl_data_4_FEM_mesh.f90.
Referenced by read_fem_mesh_control(), and write_fem_mesh_control().
hd_fem_viewer_output
character(len=kchara), parameter, private t_ctl_data_4_fem_mesh::hd_fem_viewer_output = 'FEM_viewer_mesh_output_switch' private
Definition at line 68 of file t_ctl_data_4_FEM_mesh.f90.
Referenced by read_fem_mesh_control(), and write_fem_mesh_control().
hd_mem_conserve
character(len=kchara), parameter, private t_ctl_data_4_fem_mesh::hd_mem_conserve = 'memory_conservation_ctl' private
Definition at line 62 of file t_ctl_data_4_FEM_mesh.f90.
Referenced by read_fem_mesh_control(), and write_fem_mesh_control().
hd_sleeve_level
character(len=kchara), parameter, private t_ctl_data_4_fem_mesh::hd_sleeve_level = 'sleeve_level_ctl' private
Definition at line 71 of file t_ctl_data_4_FEM_mesh.f90.
Referenced by read_fem_mesh_control(), and write_fem_mesh_control().