CALYPSO: t_group_connects Module Reference
t_group_connects Module Reference
Structure of connectivity data for group items.
Data Types
type element_group_table
Structure of connectivities for element group.
type group_connect_data
Structure of connectivities for groups.
type surface_group_table
Structure of connectivities for surface group.
Functions/Subroutines
subroutine alloc_surf_item_sf_grp_type (nitem_grp, sf_grp_data)
subroutine alloc_num_other_grp (num_grp, e_grp)
subroutine alloc_item_other_grp (e_grp)
subroutine dealloc_surf_item_sf_grp_type (sf_grp_data)
subroutine dealloc_grp_connect (e_grp)
Detailed Description
Structure of connectivity data for group items.
      subroutine alloc_surf_item_sf_grp_type(nitem_grp, sf_grp_data)
      subroutine alloc_num_other_grp(num_grp, e_grp)
      subroutine alloc_item_other_grp(e_grp)
      subroutine dealloc_surf_item_sf_grp_type(sf_grp_data)
      subroutine dealloc_grp_connect(e_grp)
Function/Subroutine Documentation
alloc_item_other_grp()
subroutine t_group_connects::alloc_item_other_grp (type(group_connect_data), intent(inout) e_grp)
Definition at line 100 of file t_group_connects.f90.
Referenced by set_connects_4_ele_group::empty_sf_ed_nod_ele_grp_type(), set_connects_4_surf_group::empty_sf_ed_nod_surf_grp_type(), set_connects_4_ele_group::set_edge_4_ele_group(), set_connects_4_surf_group::set_edge_4_surf_group(), set_connects_4_ele_group::set_node_4_ele_group(), and set_connects_4_ele_group::set_surf_4_ele_group().
alloc_num_other_grp()
subroutine t_group_connects::alloc_num_other_grp (integer(kind = kint), intent(in) num_grp, type(group_connect_data), intent(inout) e_grp)
Definition at line 84 of file t_group_connects.f90.
Referenced by set_connects_4_ele_group::empty_sf_ed_nod_ele_grp_type(), set_connects_4_surf_group::empty_sf_ed_nod_surf_grp_type(), set_connects_4_ele_group::set_edge_4_ele_group(), set_connects_4_surf_group::set_edge_4_surf_group(), set_connects_4_ele_group::set_node_4_ele_group(), and set_connects_4_ele_group::set_surf_4_ele_group().
alloc_surf_item_sf_grp_type()
subroutine t_group_connects::alloc_surf_item_sf_grp_type (integer(kind = kint), intent(in) nitem_grp, type(surface_group_table), intent(inout) sf_grp_data)
Definition at line 67 of file t_group_connects.f90.
Referenced by set_connects_4_surf_group::empty_sf_ed_nod_surf_grp_type(), and set_connects_4_surf_group::set_surf_id_4_surf_group().
dealloc_grp_connect()
subroutine t_group_connects::dealloc_grp_connect (type(group_connect_data), intent(inout) e_grp)
Definition at line 123 of file t_group_connects.f90.
Referenced by t_mesh_data::dealloc_mesh_infomations().
dealloc_surf_item_sf_grp_type()
subroutine t_group_connects::dealloc_surf_item_sf_grp_type (type(surface_group_table), intent(inout) sf_grp_data)
Definition at line 112 of file t_group_connects.f90.
Referenced by t_mesh_data::dealloc_mesh_infomations().