CALYPSO: m_intersection_data_12 Module Reference
m_intersection_data_12 Module Reference
Variables
integer(kind=kint), parameter, private nnod_tri = 3
integer(kind=kint), parameter, private nnod_pen = 5
integer(kind=kint), parameter nkind_etype_12 = 24
integer(kind=kint), parameter num_patch_12 = 4
integer(kind=kint), dimension(9), parameter itri_2_patch_12 = (/4, 5, 3, 5, 2, 3, 5, 1, 2/)
integer(kind=kint), dimension(nkind_etype_12), parameter iflag_psf_etype_12 = (/154, 169, 89, 149, 101, 106, 166, 86, 58, 53, 83, 163, 197, 92, 172, 202, 30, 135, 75, 45, 225, 210, 180, 120/)
integer(kind=kint), dimension(nnod_tri, nkind_etype_12), parameter iedge_tri_12 = reshape((/ 1, 4, 9, 8, 5, 9, 7, 8, 12, 4, 3, 12, 2, 1, 10, 3, 2, 11, 6, 7, 11, 5, 6, 10, 1, 4, 9, 2, 1, 10, 5, 6, 10, 8, 5, 9, 4, 3, 12, 7, 8, 12, 6, 7, 11, 3, 2, 11, 1, 4, 9, 4, 3, 12, 3, 2, 11, 2, 1, 10, 8, 5, 9, 5, 6, 10, 6, 7, 11, 7, 8, 12/), shape=(/nnod_tri, nkind_etype_12/))
integer(kind=kint), dimension(nnod_pen, nkind_etype_12), parameter iedge_pen_12 = reshape((/ 7, 3, 2, 10, 5, 3, 1, 10, 6, 7, 1, 5, 6, 11, 3, 5, 7, 11, 2, 1, 7, 5, 9, 4, 3, 5, 1, 4, 12, 7, 1, 3, 12, 8, 5, 3, 7, 8, 9, 1, 6, 8, 12, 3, 2, 8, 4, 3, 11, 6, 4, 2, 11, 7, 8, 2, 6, 7, 12, 4, 6, 2, 1, 9, 8, 2, 4, 9, 5, 6, 4, 8, 5, 10, 2, 8, 6, 10, 1, 4, 11, 10, 5, 8, 12, 10, 9, 8, 7, 11, 9, 12, 7, 6, 10, 12, 11, 6, 5, 9, 11, 12, 4, 1, 10, 12, 9, 1, 2, 11, 9, 10, 2, 3, 12, 10, 11, 3, 4, 9/), shape=(/nnod_pen, nkind_etype_12/))
integer(kind=kint), dimension(nnod_tri, num_patch_12, nkind_etype_12), parameter iedge_4_patch_12 = reshape((/ 1, 4, 9, 10, 5, 2, 5, 3, 2, 5, 7, 3, 8, 5, 9, 6, 7, 10, 7, 1, 10, 7, 3, 1, 7, 8, 12, 11, 3, 6, 3, 5, 6, 3, 1, 5, 4, 3, 12, 2, 1, 11, 1, 7, 11, 1, 5, 7, 2, 1, 10, 4, 3, 9, 3, 5, 9, 3, 7, 5, 3, 2, 11, 12, 7, 4, 7, 1, 4, 7, 5, 1, 6, 7, 11, 8, 5, 12, 5, 3, 12, 5, 1, 3, 5, 6, 10, 9, 1, 8, 1, 7, 8, 1, 3, 7, 1, 4, 9, 3, 2, 12, 2, 8, 12, 2, 6, 8, 2, 1, 10, 11, 6, 3, 6, 4, 3, 6, 8, 4, 5, 6, 10, 7, 8, 11, 8, 2, 11, 8, 4, 2, 8, 5, 9, 12, 4, 7, 4, 6, 7, 4, 2, 6, 4, 3, 12, 9, 8, 1, 8, 2, 1, 8, 6, 2, 7, 8, 12, 5, 6, 9, 6, 4, 9, 6, 2, 4, 6, 7, 11, 10, 2, 5, 2, 8, 5, 2, 4, 8, 3, 2, 11, 1, 4, 10, 4, 6, 10, 4, 8, 6, 1, 4, 9, 8, 12, 5, 12, 10, 5, 12, 11, 10, 4, 3, 12, 7, 11, 8, 11, 9, 8, 11, 10, 9, 3, 2, 11, 6, 10, 7, 10, 12, 7, 10, 9, 12, 2, 1, 10, 5, 9, 6, 9, 11, 6, 9, 12, 11, 8, 5, 9, 1, 10, 4, 10, 12, 4, 10, 11, 12, 5, 6, 10, 2, 11, 1, 11, 9, 1, 11, 12, 9, 6, 7, 11, 3, 12, 2, 12, 10, 2, 12, 9, 10, 7, 8, 12, 4, 9, 3, 9, 11, 3, 9, 10, 11/), shape=(/nnod_tri,num_patch_12,nkind_etype_12/))
Variable Documentation
iedge_4_patch_12
integer(kind = kint), dimension(nnod_tri,num_patch_12,nkind_etype_12), parameter m_intersection_data_12::iedge_4_patch_12 = reshape((/ 1, 4, 9, 10, 5, 2, 5, 3, 2, 5, 7, 3, 8, 5, 9, 6, 7, 10, 7, 1, 10, 7, 3, 1, 7, 8, 12, 11, 3, 6, 3, 5, 6, 3, 1, 5, 4, 3, 12, 2, 1, 11, 1, 7, 11, 1, 5, 7, 2, 1, 10, 4, 3, 9, 3, 5, 9, 3, 7, 5, 3, 2, 11, 12, 7, 4, 7, 1, 4, 7, 5, 1, 6, 7, 11, 8, 5, 12, 5, 3, 12, 5, 1, 3, 5, 6, 10, 9, 1, 8, 1, 7, 8, 1, 3, 7, 1, 4, 9, 3, 2, 12, 2, 8, 12, 2, 6, 8, 2, 1, 10, 11, 6, 3, 6, 4, 3, 6, 8, 4, 5, 6, 10, 7, 8, 11, 8, 2, 11, 8, 4, 2, 8, 5, 9, 12, 4, 7, 4, 6, 7, 4, 2, 6, 4, 3, 12, 9, 8, 1, 8, 2, 1, 8, 6, 2, 7, 8, 12, 5, 6, 9, 6, 4, 9, 6, 2, 4, 6, 7, 11, 10, 2, 5, 2, 8, 5, 2, 4, 8, 3, 2, 11, 1, 4, 10, 4, 6, 10, 4, 8, 6, 1, 4, 9, 8, 12, 5, 12, 10, 5, 12, 11, 10, 4, 3, 12, 7, 11, 8, 11, 9, 8, 11, 10, 9, 3, 2, 11, 6, 10, 7, 10, 12, 7, 10, 9, 12, 2, 1, 10, 5, 9, 6, 9, 11, 6, 9, 12, 11, 8, 5, 9, 1, 10, 4, 10, 12, 4, 10, 11, 12, 5, 6, 10, 2, 11, 1, 11, 9, 1, 11, 12, 9, 6, 7, 11, 3, 12, 2, 12, 10, 2, 12, 9, 10, 7, 8, 12, 4, 9, 3, 9, 11, 3, 9, 10, 11/), shape=(/nnod_tri,num_patch_12,nkind_etype_12/))
Definition at line 143 of file m_intersection_data_12.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
iedge_pen_12
integer(kind = kint), dimension(nnod_pen, nkind_etype_12), parameter m_intersection_data_12::iedge_pen_12 = reshape((/ 7, 3, 2, 10, 5, 3, 1, 10, 6, 7, 1, 5, 6, 11, 3, 5, 7, 11, 2, 1, 7, 5, 9, 4, 3, 5, 1, 4, 12, 7, 1, 3, 12, 8, 5, 3, 7, 8, 9, 1, 6, 8, 12, 3, 2, 8, 4, 3, 11, 6, 4, 2, 11, 7, 8, 2, 6, 7, 12, 4, 6, 2, 1, 9, 8, 2, 4, 9, 5, 6, 4, 8, 5, 10, 2, 8, 6, 10, 1, 4, 11, 10, 5, 8, 12, 10, 9, 8, 7, 11, 9, 12, 7, 6, 10, 12, 11, 6, 5, 9, 11, 12, 4, 1, 10, 12, 9, 1, 2, 11, 9, 10, 2, 3, 12, 10, 11, 3, 4, 9/), shape=(/nnod_pen, nkind_etype_12/))
Definition at line 126 of file m_intersection_data_12.f90.
iedge_tri_12
integer(kind = kint), dimension(nnod_tri, nkind_etype_12), parameter m_intersection_data_12::iedge_tri_12 = reshape((/ 1, 4, 9, 8, 5, 9, 7, 8, 12, 4, 3, 12, 2, 1, 10, 3, 2, 11, 6, 7, 11, 5, 6, 10, 1, 4, 9, 2, 1, 10, 5, 6, 10, 8, 5, 9, 4, 3, 12, 7, 8, 12, 6, 7, 11, 3, 2, 11, 1, 4, 9, 4, 3, 12, 3, 2, 11, 2, 1, 10, 8, 5, 9, 5, 6, 10, 6, 7, 11, 7, 8, 12/), shape=(/nnod_tri, nkind_etype_12/))
Definition at line 115 of file m_intersection_data_12.f90.
iflag_psf_etype_12
integer(kind = kint), dimension(nkind_etype_12), parameter m_intersection_data_12::iflag_psf_etype_12 = (/154, 169, 89, 149, 101, 106, 166, 86, 58, 53, 83, 163, 197, 92, 172, 202, 30, 135, 75, 45, 225, 210, 180, 120/)
Definition at line 108 of file m_intersection_data_12.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
itri_2_patch_12
integer(kind = kint), dimension(9), parameter m_intersection_data_12::itri_2_patch_12 = (/4, 5, 3, 5, 2, 3, 5, 1, 2/)
Definition at line 105 of file m_intersection_data_12.f90.
nkind_etype_12
integer(kind = kint), parameter m_intersection_data_12::nkind_etype_12 = 24
Definition at line 103 of file m_intersection_data_12.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
nnod_pen
integer(kind = kint), parameter, private m_intersection_data_12::nnod_pen = 5 private
Definition at line 101 of file m_intersection_data_12.f90.
nnod_tri
integer(kind = kint), parameter, private m_intersection_data_12::nnod_tri = 3 private
Definition at line 100 of file m_intersection_data_12.f90.
num_patch_12
integer(kind = kint), parameter m_intersection_data_12::num_patch_12 = 4
Definition at line 104 of file m_intersection_data_12.f90.
Referenced by t_psf_case_table::init_psf_case_tables().