CALYPSO: set_node_4_group Module Reference
set_node_4_group Module Reference
Functions/Subroutines
subroutine count_nod_4_ele_grp (numnod, numele, nnod_4_ele, ie, num_grp, num_item, istack_grp, item_grp, ntot_nod_grp, nnod_grp, inod_stack_grp, inod_2_nod_grp)
subroutine set_nod_4_ele_grp (numnod, numele, nnod_4_ele, ie, num_grp, num_item, istack_grp, item_grp, ntot_nod_grp, nnod_grp, inod_stack_grp, inod_ele_grp, inod_2_nod_grp)
subroutine count_nod_each_grp (numnod, numele, nnod_4_ele, ie, nele_grp, iele_grp, nnod_grp, inod_2_nod_grp)
subroutine set_nod_each_grp (numnod, numele, nnod_4_ele, ie, nele_grp, iele_grp, nnod_grp, inod_2_nod_grp, inod_grp)
subroutine set_new_connect_4_grp (numnod, numele, nnod_4_ele, ie, nele_grp, ist_grp, ied_grp, iele_grp, nnod_grp, inod_2_nod_grp, inod_grp, ie_grp)
Function/Subroutine Documentation
count_nod_4_ele_grp()
subroutine set_node_4_group::count_nod_4_ele_grp (integer(kind=kint), intent(in) numnod, integer(kind=kint), intent(in) numele, integer(kind=kint), intent(in) nnod_4_ele, integer(kind=kint), dimension(numele,nnod_4_ele), intent(in) ie, integer(kind=kint), intent(in) num_grp, integer(kind=kint), intent(in) num_item, integer(kind=kint), dimension(0:num_grp), intent(in) istack_grp, integer(kind=kint), dimension(num_item), intent(in) item_grp, integer(kind=kint), intent(inout) ntot_nod_grp, integer(kind=kint), dimension(num_grp), intent(inout) nnod_grp, integer(kind=kint), dimension(0:num_grp), intent(inout) inod_stack_grp, integer(kind=kint), dimension(numnod), intent(inout) inod_2_nod_grp)
Definition at line 33 of file set_node_4_group.f90.
References count_nod_each_grp().
Referenced by set_connects_4_ele_group::set_edge_4_ele_group(), set_connects_4_surf_group::set_edge_4_surf_group(), set_connects_4_ele_group::set_node_4_ele_group(), and set_connects_4_ele_group::set_surf_4_ele_group().
count_nod_each_grp()
subroutine set_node_4_group::count_nod_each_grp (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) nnod_4_ele, integer(kind = kint), dimension(numele,nnod_4_ele), intent(in) ie, integer(kind = kint), intent(in) nele_grp, integer(kind = kint), dimension(nele_grp), intent(in) iele_grp, integer(kind = kint), intent(inout) nnod_grp, integer(kind = kint), dimension(numnod), intent(inout) inod_2_nod_grp)
Definition at line 105 of file set_node_4_group.f90.
Referenced by count_nod_4_ele_grp().
set_new_connect_4_grp()
subroutine set_node_4_group::set_new_connect_4_grp (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) nnod_4_ele, integer(kind = kint), dimension(numele,nnod_4_ele), intent(in) ie, integer(kind = kint), intent(in) nele_grp, integer(kind = kint), intent(in) ist_grp, integer(kind = kint), intent(in) ied_grp, integer(kind = kint), dimension(nele_grp), intent(in) iele_grp, integer(kind = kint), intent(in) nnod_grp, integer(kind = kint), dimension(numnod), intent(inout) inod_2_nod_grp, integer(kind = kint), dimension(nnod_grp), intent(in) inod_grp, integer(kind = kint), dimension(nele_grp,nnod_4_ele), intent(inout) ie_grp)
Definition at line 183 of file set_node_4_group.f90.
set_nod_4_ele_grp()
subroutine set_node_4_group::set_nod_4_ele_grp (integer(kind=kint), intent(in) numnod, integer(kind=kint), intent(in) numele, integer(kind=kint), intent(in) nnod_4_ele, integer(kind=kint), dimension(numele,nnod_4_ele), intent(in) ie, integer(kind=kint), intent(in) num_grp, integer(kind=kint), intent(in) num_item, integer(kind=kint), dimension(0:num_grp), intent(in) istack_grp, integer(kind=kint), dimension(num_item), intent(in) item_grp, integer(kind=kint), intent(in) ntot_nod_grp, integer(kind=kint), dimension(num_grp), intent(in) nnod_grp, integer(kind=kint), dimension(0:num_grp), intent(in) inod_stack_grp, integer(kind=kint), dimension(ntot_nod_grp), intent(inout) inod_ele_grp, integer(kind=kint), dimension(numnod), intent(inout) inod_2_nod_grp)
Definition at line 69 of file set_node_4_group.f90.
References set_nod_each_grp().
Referenced by set_connects_4_ele_group::set_edge_4_ele_group(), set_connects_4_surf_group::set_edge_4_surf_group(), set_connects_4_ele_group::set_node_4_ele_group(), and set_connects_4_ele_group::set_surf_4_ele_group().
set_nod_each_grp()
subroutine set_node_4_group::set_nod_each_grp (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) nnod_4_ele, integer(kind = kint), dimension(numele,nnod_4_ele), intent(in) ie, integer(kind = kint), intent(in) nele_grp, integer(kind = kint), dimension(nele_grp), intent(in) iele_grp, integer(kind = kint), intent(in) nnod_grp, integer(kind = kint), dimension(numnod), intent(inout) inod_2_nod_grp, integer(kind = kint), dimension(nnod_grp), intent(inout) inod_grp)
Definition at line 145 of file set_node_4_group.f90.
Referenced by set_nod_4_ele_grp().