CALYPSO: t_viewer_group Module Reference
t_viewer_group Module Reference
Structure of surface information for pickup surface.
Data Types
type viewer_group_data
type viewer_node_groups
type viewer_surface_groups
Functions/Subroutines
subroutine alloc_domain_stack_4_surf (num_pe, domain_grps)
subroutine alloc_viewer_node_grps_stack (num_group, view_nod_grps)
subroutine alloc_viewer_surf_grps_stack (num_group, view_grps)
subroutine alloc_merged_node_grps_stack (num_pe, view_nod_grps)
subroutine alloc_merged_surf_grps_stack (num_pe, view_grps)
subroutine dealloc_viewer_node_grps_item (view_nod_grps)
subroutine dealloc_viewer_surf_grps_item (view_grps)
subroutine alloc_viewer_group_stack (ngrp, v_grp)
subroutine alloc_merged_group_stack (num_pe, ngrp, v_grp)
subroutine alloc_merged_group_item (v_grp)
subroutine dealloc_merged_group_stack (group)
subroutine dealloc_merged_group_item (v_grp)
Detailed Description
Structure of surface information for pickup surface.
      subroutine alloc_domain_stack_4_surf(num_pe, domain_grps)
      subroutine dealloc_viewer_node_grps_item(view_nod_grps)
        type(viewer_node_groups), intent(inout) :: view_nod_grps
      subroutine alloc_viewer_node_grps_stack                         &
     &         (num_group, view_nod_grps)
      subroutine alloc_viewer_surf_grps_stack(num_group, view_grps)
      subroutine alloc_merged_node_grps_stack(num_pe, view_nod_grps)
      subroutine alloc_merged_surf_grps_stack(num_pe, view_grps)
      subroutine dealloc_viewer_surf_grps_item(view_grps)
        type(viewer_surface_groups), intent(inout) :: view_grps
      subroutine alloc_merged_group_stack(num_pe, ngrp, v_grp)
      subroutine alloc_merged_group_item(v_grp)
      subroutine dealloc_merged_group_stack(v_grp)
      subroutine dealloc_merged_group_item(v_grp)
        type(viewer_group_data), intent(inout) :: v_grp
Function/Subroutine Documentation
alloc_domain_stack_4_surf()
subroutine t_viewer_group::alloc_domain_stack_4_surf (integer, intent(in) num_pe, type(viewer_surface_groups), intent(inout) domain_grps)
Definition at line 62 of file t_viewer_group.f90.
References alloc_merged_surf_grps_stack().
alloc_merged_group_item()
subroutine t_viewer_group::alloc_merged_group_item (type(viewer_group_data), intent(inout) v_grp)
Definition at line 208 of file t_viewer_group.f90.
Referenced by const_edge_4_viewer::construct_edge_4_domain(), const_grp_edge_4_viewer::construct_edge_4_ele_grp(), const_grp_edge_4_viewer::construct_edge_4_surf_grp(), set_nodes_4_groups_viewer::s_set_nodes_4_groups_viewer(), set_nodes_4_groups_viewer::set_nod_4_domain_viewer(), set_nodes_4_groups_viewer::set_nod_4_ele_group_viewer(), and set_nodes_4_groups_viewer::set_nod_4_surf_group_viewer().
alloc_merged_group_stack()
subroutine t_viewer_group::alloc_merged_group_stack (integer, intent(in) num_pe, integer(kind = kint), intent(in) ngrp, type(viewer_group_data), intent(inout) v_grp)
Definition at line 194 of file t_viewer_group.f90.
Referenced by alloc_merged_node_grps_stack(), and alloc_merged_surf_grps_stack().
alloc_merged_node_grps_stack()
subroutine t_viewer_group::alloc_merged_node_grps_stack (integer, intent(in) num_pe, type(viewer_node_groups), intent(inout) view_nod_grps)
Definition at line 115 of file t_viewer_group.f90.
References alloc_merged_group_stack().
alloc_merged_surf_grps_stack()
subroutine t_viewer_group::alloc_merged_surf_grps_stack (integer, intent(in) num_pe, type(viewer_surface_groups), intent(inout) view_grps)
Definition at line 130 of file t_viewer_group.f90.
References alloc_merged_group_stack().
Referenced by alloc_domain_stack_4_surf().
alloc_viewer_group_stack()
subroutine t_viewer_group::alloc_viewer_group_stack (integer(kind = kint), intent(in) ngrp, type(viewer_group_data), intent(inout) v_grp)
Definition at line 181 of file t_viewer_group.f90.
Referenced by alloc_viewer_node_grps_stack(), and alloc_viewer_surf_grps_stack().
alloc_viewer_node_grps_stack()
subroutine t_viewer_group::alloc_viewer_node_grps_stack (integer(kind = kint), intent(in) num_group, type(viewer_node_groups), intent(inout) view_nod_grps)
Definition at line 78 of file t_viewer_group.f90.
References alloc_viewer_group_stack().
alloc_viewer_surf_grps_stack()
subroutine t_viewer_group::alloc_viewer_surf_grps_stack (integer(kind = kint), intent(in) num_group, type(viewer_surface_groups), intent(inout) view_grps)
Definition at line 95 of file t_viewer_group.f90.
References alloc_viewer_group_stack().
dealloc_merged_group_item()
subroutine t_viewer_group::dealloc_merged_group_item (type(viewer_group_data), intent(inout) v_grp)
Definition at line 232 of file t_viewer_group.f90.
Referenced by const_grp_edge_4_viewer::construct_edge_4_ele_grp(), const_grp_edge_4_viewer::construct_edge_4_surf_grp(), dealloc_viewer_node_grps_item(), dealloc_viewer_surf_grps_item(), set_nodes_4_groups_viewer::set_nod_4_ele_group_viewer(), and set_nodes_4_groups_viewer::set_nod_4_surf_group_viewer().
dealloc_merged_group_stack()
subroutine t_viewer_group::dealloc_merged_group_stack (type(viewer_group_data), intent(inout) group)
Definition at line 221 of file t_viewer_group.f90.
Referenced by dealloc_viewer_node_grps_item(), and dealloc_viewer_surf_grps_item().
dealloc_viewer_node_grps_item()
subroutine t_viewer_group::dealloc_viewer_node_grps_item (type(viewer_node_groups), intent(inout) view_nod_grps)
Definition at line 150 of file t_viewer_group.f90.
References dealloc_merged_group_item(), and dealloc_merged_group_stack().
dealloc_viewer_surf_grps_item()
subroutine t_viewer_group::dealloc_viewer_surf_grps_item (type(viewer_surface_groups), intent(inout) view_grps)
Definition at line 163 of file t_viewer_group.f90.
References dealloc_merged_group_item(), and dealloc_merged_group_stack().