CALYPSO: pickup_node_4_viewer Module Reference
pickup_node_4_viewer Module Reference
Functions/Subroutines
subroutine allocate_imark_nod_pick_node (mesh)
subroutine allocate_nod_cvt_table_viewer (mesh, view_mesh)
subroutine deallocate_imark_nod_pick_node
subroutine deallocate_nod_cvt_table_viewer
subroutine mark_used_node_4_viewer (nnod_4_surf, merged_grp, view_mesh)
subroutine count_used_node_4_viewer (numnod, nnod_viewer)
subroutine set_node_cvt_table_viewer (mesh)
subroutine renumber_surf_connect_4_viewer (nnod_4_surf, view_mesh)
subroutine set_node_position_4_viewer (mesh, view_mesh)
subroutine set_node_group_item_viewer (merged_grp, nod_nod_grp)
Variables
integer(kind=kint), dimension(:), allocatable, private imark_node
integer(kind=kint), dimension(:), allocatable, private inod_merge2viewer
integer(kind=kint), dimension(:), allocatable, private inod_viewer2merge
Function/Subroutine Documentation
allocate_imark_nod_pick_node()
subroutine pickup_node_4_viewer::allocate_imark_nod_pick_node (type(mesh_geometry), intent(in) mesh)
Definition at line 51 of file pickup_node_4_viewer.f90.
References imark_node.
Referenced by set_nodes_4_viewer::s_set_nodes_4_viewer().
allocate_nod_cvt_table_viewer()
subroutine pickup_node_4_viewer::allocate_nod_cvt_table_viewer (type(mesh_geometry), intent(in) mesh, type(viewer_mesh_data), intent(in) view_mesh)
Definition at line 64 of file pickup_node_4_viewer.f90.
References inod_merge2viewer, and inod_viewer2merge.
Referenced by set_nodes_4_viewer::s_set_nodes_4_viewer().
count_used_node_4_viewer()
subroutine pickup_node_4_viewer::count_used_node_4_viewer (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(inout) nnod_viewer)
Definition at line 125 of file pickup_node_4_viewer.f90.
References imark_node.
Referenced by set_nodes_4_viewer::s_set_nodes_4_viewer().
deallocate_imark_nod_pick_node()
subroutine pickup_node_4_viewer::deallocate_imark_nod_pick_node
Definition at line 80 of file pickup_node_4_viewer.f90.
References imark_node.
Referenced by set_nodes_4_viewer::s_set_nodes_4_viewer().
deallocate_nod_cvt_table_viewer()
subroutine pickup_node_4_viewer::deallocate_nod_cvt_table_viewer
Definition at line 88 of file pickup_node_4_viewer.f90.
References inod_merge2viewer, and inod_viewer2merge.
Referenced by set_nodes_4_viewer::s_set_nodes_4_viewer().
mark_used_node_4_viewer()
subroutine pickup_node_4_viewer::mark_used_node_4_viewer (integer(kind = kint), intent(in) nnod_4_surf, type(mesh_groups), intent(in) merged_grp, type(viewer_mesh_data), intent(in) view_mesh)
Definition at line 97 of file pickup_node_4_viewer.f90.
References imark_node.
Referenced by set_nodes_4_viewer::s_set_nodes_4_viewer().
renumber_surf_connect_4_viewer()
subroutine pickup_node_4_viewer::renumber_surf_connect_4_viewer (integer(kind = kint), intent(in) nnod_4_surf, type(viewer_mesh_data), intent(inout) view_mesh)
Definition at line 165 of file pickup_node_4_viewer.f90.
References inod_merge2viewer.
Referenced by set_nodes_4_viewer::s_set_nodes_4_viewer().
set_node_cvt_table_viewer()
subroutine pickup_node_4_viewer::set_node_cvt_table_viewer (type(mesh_geometry), intent(in) mesh)
Definition at line 143 of file pickup_node_4_viewer.f90.
References imark_node, inod_merge2viewer, and inod_viewer2merge.
Referenced by set_nodes_4_viewer::s_set_nodes_4_viewer().
set_node_group_item_viewer()
subroutine pickup_node_4_viewer::set_node_group_item_viewer (type(mesh_groups), intent(in) merged_grp, type(viewer_group_data), intent(inout) nod_nod_grp)
Definition at line 205 of file pickup_node_4_viewer.f90.
References inod_merge2viewer.
Referenced by set_nodes_4_viewer::s_set_nod_grp_4_viewer_surface().
set_node_position_4_viewer()
subroutine pickup_node_4_viewer::set_node_position_4_viewer (type(mesh_geometry), intent(in) mesh, type(viewer_mesh_data), intent(inout) view_mesh)
Definition at line 185 of file pickup_node_4_viewer.f90.
References inod_viewer2merge.
Referenced by set_nodes_4_viewer::s_set_nodes_4_viewer().
Variable Documentation
imark_node
integer(kind = kint), dimension(:), allocatable, private pickup_node_4_viewer::imark_node private
Definition at line 39 of file pickup_node_4_viewer.f90.
Referenced by allocate_imark_nod_pick_node(), count_used_node_4_viewer(), deallocate_imark_nod_pick_node(), mark_used_node_4_viewer(), and set_node_cvt_table_viewer().
inod_merge2viewer
integer(kind = kint), dimension(:), allocatable, private pickup_node_4_viewer::inod_merge2viewer private
Definition at line 40 of file pickup_node_4_viewer.f90.
Referenced by allocate_nod_cvt_table_viewer(), deallocate_nod_cvt_table_viewer(), renumber_surf_connect_4_viewer(), set_node_cvt_table_viewer(), and set_node_group_item_viewer().
inod_viewer2merge
integer(kind = kint), dimension(:), allocatable, private pickup_node_4_viewer::inod_viewer2merge private
Definition at line 41 of file pickup_node_4_viewer.f90.
Referenced by allocate_nod_cvt_table_viewer(), deallocate_nod_cvt_table_viewer(), set_node_cvt_table_viewer(), and set_node_position_4_viewer().