CALYPSO: t_control_array_charaint Module Reference
t_control_array_charaint Module Reference
Data Types
type ctl_array_ci
Structure for charactor and integer control array.
type read_chara_int_item
structure of control item with three characters
Functions/Subroutines
subroutine read_charaint_ctl_type (c_buf, label, ci_item)
subroutine write_charaint_ctl_type (id_file, level, label, ci_item)
subroutine copy_charaint_ctl (org_ci, new_ci)
subroutine alloc_control_array_c_i (array_ci)
subroutine dealloc_control_array_c_i (array_ci)
subroutine read_control_array_c_i (id_control, label, array_ci, c_buf)
subroutine write_control_array_c_i (id_control, level, label, array_ci)
subroutine append_control_array_c_i (read_ci, array_ci)
subroutine copy_control_array_c_i (num_copy, org_ci, tgt_ci)
subroutine append_control_item_c_i (read_ci, array_ci)
Function/Subroutine Documentation
alloc_control_array_c_i()
subroutine t_control_array_charaint::alloc_control_array_c_i (type(ctl_array_ci), intent(inout) array_ci)
Definition at line 136 of file t_control_array_charaint.f90.
Referenced by append_control_array_c_i(), bcast_control_arrays::bcast_ctl_array_ci(), and read_control_array_c_i().
append_control_array_c_i()
subroutine t_control_array_charaint::append_control_array_c_i (type(read_chara_int_item), intent(inout) read_ci, type(ctl_array_ci), intent(inout) array_ci)
Definition at line 228 of file t_control_array_charaint.f90.
References alloc_control_array_c_i(), append_control_item_c_i(), copy_control_array_c_i(), and dealloc_control_array_c_i().
Referenced by read_control_array_c_i().
append_control_item_c_i()
subroutine t_control_array_charaint::append_control_item_c_i (type(read_chara_int_item), intent(in) read_ci, type(ctl_array_ci), intent(inout) array_ci)
Definition at line 269 of file t_control_array_charaint.f90.
Referenced by append_control_array_c_i().
copy_charaint_ctl()
subroutine t_control_array_charaint::copy_charaint_ctl (type(read_chara_int_item), intent(in) org_ci, type(read_chara_int_item), intent(inout) new_ci)
Definition at line 121 of file t_control_array_charaint.f90.
copy_control_array_c_i()
subroutine t_control_array_charaint::copy_control_array_c_i (integer(kind = kint), intent(in) num_copy, type(ctl_array_ci), intent(in) org_ci, type(ctl_array_ci), intent(inout) tgt_ci)
Definition at line 253 of file t_control_array_charaint.f90.
Referenced by append_control_array_c_i().
dealloc_control_array_c_i()
subroutine t_control_array_charaint::dealloc_control_array_c_i (type(ctl_array_ci), intent(inout) array_ci)
Definition at line 151 of file t_control_array_charaint.f90.
Referenced by append_control_array_c_i(), t_ctl_data_4_sphere_model::dealloc_control_shell_define(), t_ctl_data_4_divide_sphere::dealloc_ndomain_rtp_ctl(), and t_ctl_data_4_fields::dealloc_phys_control().
read_charaint_ctl_type()
subroutine t_control_array_charaint::read_charaint_ctl_type (type(buffer_for_control), intent(in) c_buf, character(len=kchara), intent(in) label, type(read_chara_int_item), intent(inout) ci_item)
Definition at line 77 of file t_control_array_charaint.f90.
References m_machine_parameter::iflag_debug.
Referenced by read_control_array_c_i().
read_control_array_c_i()
subroutine t_control_array_charaint::read_control_array_c_i (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) label, type(ctl_array_ci), intent(inout) array_ci, type(buffer_for_control), intent(inout) c_buf)
Definition at line 165 of file t_control_array_charaint.f90.
References alloc_control_array_c_i(), append_control_array_c_i(), t_read_control_elements::check_array_flag(), t_read_control_elements::check_end_array_flag(), t_read_control_elements::load_one_line_from_control(), and read_charaint_ctl_type().
Referenced by t_ctl_data_4_sphere_model::read_control_shell_define(), t_ctl_data_4_divide_sphere::read_control_shell_domain(), and t_ctl_data_4_fields::read_phys_data_control().
write_charaint_ctl_type()
subroutine t_control_array_charaint::write_charaint_ctl_type (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, type(read_chara_int_item), intent(in) ci_item)
Definition at line 102 of file t_control_array_charaint.f90.
References write_control_elements::write_chara_int_ctl_item().
write_control_array_c_i()
subroutine t_control_array_charaint::write_control_array_c_i (integer(kind = kint), intent(in) id_control, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, type(ctl_array_ci), intent(in) array_ci)
Definition at line 199 of file t_control_array_charaint.f90.
References write_control_elements::write_array_flag_for_ctl(), write_control_elements::write_chara_int_ctl_item(), and write_control_elements::write_end_array_flag_for_ctl().
Referenced by t_ctl_data_4_divide_sphere::write_control_shell_domain(), and t_ctl_data_4_fields::write_phys_data_control().