CALYPSO: set_comm_table_prt_fftpack Module Reference
set_comm_table_prt_fftpack Module Reference
communication table from FFTPACK5
Functions/Subroutines
subroutine set_comm_item_prt_4_fftpack (nnod_rtp, ntot_sr_rtp, irev_sr_rtp, mphi_rtp, nnod_rt, comm_sph_FFT)
subroutine copy_prt_fftpack_to_send (nnod_rtp, irev_sr_rtp, mphi_rtp, nnod_rt, ncomp_fwd, X_FFT, n_WS, WS)
subroutine copy_prt_comp_fftpack_to_send (nd, nnod_rtp, irev_sr_rtp, mphi_rtp, nnod_rt, ncomp_fwd, X_FFT, n_WS, WS)
subroutine copy_prt_fftpack_from_recv (nnod_rtp, irev_sr_rtp, mphi_rtp, nnod_rt, ncomp_bwd, n_WR, WR, X_FFT)
subroutine copy_prt_comp_fftpack_from_recv (nd, nnod_rtp, irev_sr_rtp, mphi_rtp, nnod_rt, ncomp_bwd, n_WR, WR, X_FFT)
Detailed Description
communication table from FFTPACK5
      subroutine set_comm_item_prt_4_FFTPACK                          &
     &         (nnod_rtp, ntot_sr_rtp, irev_sr_rtp,                   &
     &          mphi_rtp, nnod_rt, comm_sph_FFT)
        type(comm_tbl_from_FFT), intent(inout) :: comm_sph_FFT
      subroutine copy_prt_FFTPACK_to_send(nnod_rtp, irev_sr_rtp,      &
     &          mphi_rtp, nnod_rt, ncomp_fwd, X_FFT, n_WS, WS)
      subroutine copy_prt_comp_FFTPACK_to_send                        &
     &         (nd, nnod_rtp, irev_sr_rtp, mphi_rtp, nnod_rt,         &
     &          ncomp_fwd, X_FFT, n_WS, WS)
        type(comm_tbl_from_FFT), intent(inout) :: comm_sph_FFT
      subroutine copy_prt_FFTPACK_from_recv                           &
     &         (nnod_rtp, irev_sr_rtp, mphi_rtp, nnod_rt,             &
     &          ncomp_bwd, n_WR, WR, X_FFT)
      subroutine copy_prt_comp_FFTPACK_from_recv                      &
     &         (nd, nnod_rtp, irev_sr_rtp, mphi_rtp, nnod_rt,         &
     &          ncomp_bwd, n_WR, WR, X_FFT)
Function/Subroutine Documentation
copy_prt_comp_fftpack_from_recv()
subroutine set_comm_table_prt_fftpack::copy_prt_comp_fftpack_from_recv (integer(kind = kint), intent(in) nd, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(nnod_rtp), intent(in) irev_sr_rtp, integer(kind = kint), intent(in) mphi_rtp, integer(kind = kint), intent(in) nnod_rt, integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(in) WR, real(kind = kreal), dimension(nnod_rtp), intent(inout) X_FFT)
Definition at line 237 of file set_comm_table_prt_FFTPACK.f90.
Referenced by sph_prt_domain_fftpack5::prt_domain_rfftmb_from_recv().
copy_prt_comp_fftpack_to_send()
subroutine set_comm_table_prt_fftpack::copy_prt_comp_fftpack_to_send (integer(kind = kint), intent(in) nd, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(nnod_rtp), intent(in) irev_sr_rtp, integer(kind = kint), intent(in) mphi_rtp, integer(kind = kint), intent(in) nnod_rt, integer(kind = kint), intent(in) ncomp_fwd, real(kind = kreal), dimension(ncomp_fwd*nnod_rtp), intent(in) X_FFT, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 147 of file set_comm_table_prt_FFTPACK.f90.
copy_prt_fftpack_from_recv()
subroutine set_comm_table_prt_fftpack::copy_prt_fftpack_from_recv (integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(nnod_rtp), intent(in) irev_sr_rtp, integer(kind = kint), intent(in) mphi_rtp, integer(kind = kint), intent(in) nnod_rt, integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(in) WR, real(kind = kreal), dimension(nnod_rtp,ncomp_bwd), intent(inout) X_FFT)
Definition at line 191 of file set_comm_table_prt_FFTPACK.f90.
Referenced by sph_prt_fftpack5::prt_rfftmb_from_recv().
copy_prt_fftpack_to_send()
subroutine set_comm_table_prt_fftpack::copy_prt_fftpack_to_send (integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(nnod_rtp), intent(in) irev_sr_rtp, integer(kind = kint), intent(in) mphi_rtp, integer(kind = kint), intent(in) nnod_rt, integer(kind = kint), intent(in) ncomp_fwd, real(kind = kreal), dimension(nnod_rtp,ncomp_fwd), intent(in) X_FFT, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 102 of file set_comm_table_prt_FFTPACK.f90.
set_comm_item_prt_4_fftpack()
subroutine set_comm_table_prt_fftpack::set_comm_item_prt_4_fftpack (integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) ntot_sr_rtp, integer(kind = kint), dimension(nnod_rtp), intent(in) irev_sr_rtp, integer(kind = kint), intent(in) mphi_rtp, integer(kind = kint), intent(in) nnod_rt, type(comm_tbl_from_fft), intent(inout) comm_sph_FFT)
Definition at line 44 of file set_comm_table_prt_FFTPACK.f90.
References m_constants::one.
Referenced by sph_prt_domain_fftpack5::init_prt_domain_fftpack5(), sph_prt_fftpack5::init_prt_fftpack5(), sph_prt_domain_fftpack5::verify_prt_domain_fftpack5(), and sph_prt_fftpack5::verify_prt_fftpack5().