CALYPSO: copy_field_4_sph_trans Module Reference
copy_field_4_sph_trans Module Reference
Copy spherical harmonics data.
Functions/Subroutines
subroutine copy_scalar_from_trans_smp (nnod_rtp, m_folding, nnod, v_rtp, d_sph)
subroutine copy_vector_from_trans_smp (nnod_rtp, m_folding, nnod, v_rtp, d_sph)
subroutine copy_tensor_from_trans_smp (nnod_rtp, m_folding, nnod, v_rtp, d_sph)
subroutine copy_scalar_to_trans_smp (nnod_rtp, nnod, d_sph, v_rtp)
subroutine copy_vector_to_trans_smp (nnod_rtp, nnod, d_sph, v_rtp)
subroutine copy_tensor_to_trans_smp (nnod_rtp, nnod, d_sph, v_rtp)
Detailed Description
Copy spherical harmonics data.
      subroutine copy_scalar_from_trans_smp                           &
     &         (nnod_rtp, m_folding, nnod, v_rtp, d_sph)
      subroutine copy_vector_from_trans_smp                           &
     &         (nnod_rtp, m_folding, nnod, v_rtp, d_sph)
      subroutine copy_tensor_from_trans_smp                           &
     &         (nnod_rtp, m_folding, nnod, v_rtp, d_sph)
      subroutine copy_scalar_to_trans_smp                             &
     &         (nnod_rtp, nnod, d_sph, v_rtp)
      subroutine copy_vector_to_trans_smp                             &
     &         (nnod_rtp, nnod, d_sph, v_rtp)
      subroutine copy_tensor_to_trans_smp                             &
     &         (nnod_rtp, nnod, d_sph, v_rtp)
Function/Subroutine Documentation
copy_scalar_from_trans_smp()
subroutine copy_field_4_sph_trans::copy_scalar_from_trans_smp (integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) m_folding, integer(kind = kint), intent(in) nnod, real(kind = kreal), dimension(nnod_rtp), intent(in) v_rtp, real(kind = kreal), dimension(nnod), intent(inout) d_sph)
Definition at line 38 of file copy_field_4_sph_trans.f90.
Referenced by copy_nodal_fld_4_sph_trans::copy_nod_scl_from_trans_wpole(), and copy_rtp_vectors_4_grad::sel_scalar_from_trans().
copy_scalar_to_trans_smp()
subroutine copy_field_4_sph_trans::copy_scalar_to_trans_smp (integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) nnod, real(kind = kreal), dimension(nnod), intent(in) d_sph, real(kind = kreal), dimension(nnod_rtp), intent(inout) v_rtp)
Definition at line 109 of file copy_field_4_sph_trans.f90.
Referenced by copy_nodal_fld_4_sph_trans::copy_nod_scl_to_sph_trans().
copy_tensor_from_trans_smp()
subroutine copy_field_4_sph_trans::copy_tensor_from_trans_smp (integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) m_folding, integer(kind = kint), intent(in) nnod, real(kind = kreal), dimension(nnod_rtp,6), intent(in) v_rtp, real(kind = kreal), dimension(nnod,6), intent(inout) d_sph)
Definition at line 82 of file copy_field_4_sph_trans.f90.
Referenced by copy_nodal_fld_4_sph_trans::copy_nod_tsr_from_trans_wpole().
copy_tensor_to_trans_smp()
subroutine copy_field_4_sph_trans::copy_tensor_to_trans_smp (integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) nnod, real(kind = kreal), dimension(nnod,6), intent(in) d_sph, real(kind = kreal), dimension(nnod_rtp,6), intent(inout) v_rtp)
Definition at line 143 of file copy_field_4_sph_trans.f90.
Referenced by copy_nodal_fld_4_sph_trans::copy_nod_tsr_to_sph_trans().
copy_vector_from_trans_smp()
subroutine copy_field_4_sph_trans::copy_vector_from_trans_smp (integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) m_folding, integer(kind = kint), intent(in) nnod, real(kind = kreal), dimension(nnod_rtp,3), intent(in) v_rtp, real(kind = kreal), dimension(nnod,3), intent(inout) d_sph)
Definition at line 59 of file copy_field_4_sph_trans.f90.
Referenced by copy_nodal_fld_4_sph_trans::copy_nod_vec_from_trans_wpole().
copy_vector_to_trans_smp()
subroutine copy_field_4_sph_trans::copy_vector_to_trans_smp (integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) nnod, real(kind = kreal), dimension(nnod,3), intent(in) d_sph, real(kind = kreal), dimension(nnod_rtp,3), intent(inout) v_rtp)
Definition at line 125 of file copy_field_4_sph_trans.f90.
Referenced by copy_nodal_fld_4_sph_trans::copy_nod_vec_to_sph_trans().