CALYPSO: /home/takumi kera/calypso/src/programs/data_utilities/VIZ_only/psf_file_to_VTK.f90 File Reference
psf_file_to_VTK.f90 File Reference
Functions/Subroutines
program psf_file_to_vtk
Function/Subroutine Documentation
psf_file_to_vtk()
program psf_file_to_vtk
Definition at line 1 of file psf_file_to_VTK.f90.
References t_ucd_data::deallocate_ucd_mesh(), m_field_file_format::iflag_vtk, m_section_file_extensions::psf_to_vtk_format_id_from_input(), ucd_io_select::sel_read_alloc_ucd_file(), and ucd_io_select::sel_write_ucd_file().