CALYPSO: t_node_id_spherical_io Module Reference
t_node_id_spherical_io Module Reference
Array for speherical harmonics indexing IO.
Data Types
type sph_io_data
Structure for spherical harmonics table IO.
Functions/Subroutines
subroutine dealloc_sph_grid_idx_io (sph_IO)
subroutine dealloc_sph_mode_idx_io (sph_IO)
subroutine alloc_num_idx_sph_io (sph_IO)
subroutine alloc_nod_id_sph_io (sph_IO)
subroutine alloc_idx_sph_1d1_io (sph_IO)
subroutine alloc_idx_sph_1d2_io (sph_IO)
subroutine alloc_idx_sph_1d3_io (sph_IO)
subroutine, private dealloc_num_idx_sph_io (sph_IO)
subroutine, private dealloc_nod_id_sph_io (sph_IO)
subroutine, private dealloc_idx_sph_1d1_io (sph_IO)
subroutine, private dealloc_idx_sph_1d2_io (sph_IO)
subroutine, private dealloc_idx_sph_1d3_io (sph_IO)
Detailed Description
Array for speherical harmonics indexing IO.
      subroutine dealloc_sph_grid_idx_IO(sph_IO)
      subroutine dealloc_sph_mode_idx_IO(sph_IO)
      subroutine alloc_num_idx_sph_IO(sph_IO)
      subroutine alloc_nod_id_sph_IO(sph_IO)
      subroutine alloc_idx_sph_1d1_IO(sph_IO)
      subroutine alloc_idx_sph_1d2_IO(sph_IO)
      subroutine alloc_idx_sph_1d3_IO(sph_IO)
        type(sph_IO_data), intent(inout) :: sph_IO
Function/Subroutine Documentation
alloc_idx_sph_1d1_io()
subroutine t_node_id_spherical_io::alloc_idx_sph_1d1_io (type(sph_io_data), intent(inout) sph_IO)
Definition at line 141 of file t_node_id_spherical_IO.f90.
Referenced by copy_sph_rj_mode_4_io::copy_sph_node_4_rj_to_io(), copy_sph_rlm_mode_4_io::copy_sph_node_4_rlm_to_io(), copy_sph_rtm_node_4_io::copy_sph_node_4_rtm_to_io(), copy_sph_rtp_node_4_io::copy_sph_node_4_rtp_to_io(), gz_mpi_sph_gl_1d_idx_io::gz_mpi_read_rj_gl_1d_table(), gz_mpi_sph_gl_1d_idx_io_b::gz_mpi_read_rj_gl_1d_table_b(), gz_mpi_sph_gl_1d_idx_io::gz_mpi_read_rtp_gl_1d_table(), gz_mpi_sph_gl_1d_idx_io_b::gz_mpi_read_rtp_gl_1d_table_b(), gz_sph_global_1d_idx_io_b::gz_read_rj_gl_1d_table_b(), gz_sph_global_1d_idx_io_b::gz_read_rtp_gl_1d_table_b(), mpi_sph_gl_1d_idx_io::mpi_read_rj_gl_1d_table(), mpi_sph_gl_1d_idx_io_b::mpi_read_rj_gl_1d_table_b(), mpi_sph_gl_1d_idx_io::mpi_read_rtp_gl_1d_table(), mpi_sph_gl_1d_idx_io_b::mpi_read_rtp_gl_1d_table_b(), sph_global_1d_idx_io::read_rj_gl_1d_table(), sph_global_1d_idx_io_b::read_rj_gl_1d_table_b(), gz_sph_global_1d_idx_io::read_rj_gl_1d_table_gz(), sph_global_1d_idx_io::read_rtp_gl_1d_table(), sph_global_1d_idx_io_b::read_rtp_gl_1d_table_b(), and gz_sph_global_1d_idx_io::read_rtp_gl_1d_table_gz().
alloc_idx_sph_1d2_io()
subroutine t_node_id_spherical_io::alloc_idx_sph_1d2_io (type(sph_io_data), intent(inout) sph_IO)
Definition at line 157 of file t_node_id_spherical_IO.f90.
Referenced by copy_sph_rj_mode_4_io::copy_sph_node_4_rj_to_io(), copy_sph_rlm_mode_4_io::copy_sph_node_4_rlm_to_io(), copy_sph_rtm_node_4_io::copy_sph_node_4_rtm_to_io(), copy_sph_rtp_node_4_io::copy_sph_node_4_rtp_to_io(), gz_mpi_sph_gl_1d_idx_io::gz_mpi_read_rj_gl_1d_table(), gz_mpi_sph_gl_1d_idx_io_b::gz_mpi_read_rj_gl_1d_table_b(), gz_mpi_sph_gl_1d_idx_io::gz_mpi_read_rtp_gl_1d_table(), gz_mpi_sph_gl_1d_idx_io_b::gz_mpi_read_rtp_gl_1d_table_b(), gz_sph_global_1d_idx_io_b::gz_read_rj_gl_1d_table_b(), gz_sph_global_1d_idx_io_b::gz_read_rtp_gl_1d_table_b(), mpi_sph_gl_1d_idx_io::mpi_read_rj_gl_1d_table(), mpi_sph_gl_1d_idx_io_b::mpi_read_rj_gl_1d_table_b(), mpi_sph_gl_1d_idx_io::mpi_read_rtp_gl_1d_table(), mpi_sph_gl_1d_idx_io_b::mpi_read_rtp_gl_1d_table_b(), sph_global_1d_idx_io::read_rj_gl_1d_table(), sph_global_1d_idx_io_b::read_rj_gl_1d_table_b(), gz_sph_global_1d_idx_io::read_rj_gl_1d_table_gz(), sph_global_1d_idx_io::read_rtp_gl_1d_table(), sph_global_1d_idx_io_b::read_rtp_gl_1d_table_b(), and gz_sph_global_1d_idx_io::read_rtp_gl_1d_table_gz().
alloc_idx_sph_1d3_io()
subroutine t_node_id_spherical_io::alloc_idx_sph_1d3_io (type(sph_io_data), intent(inout) sph_IO)
Definition at line 173 of file t_node_id_spherical_IO.f90.
Referenced by copy_sph_rtm_node_4_io::copy_sph_node_4_rtm_to_io(), copy_sph_rtp_node_4_io::copy_sph_node_4_rtp_to_io(), gz_mpi_sph_gl_1d_idx_io::gz_mpi_read_rtp_gl_1d_table(), gz_mpi_sph_gl_1d_idx_io_b::gz_mpi_read_rtp_gl_1d_table_b(), gz_sph_global_1d_idx_io_b::gz_read_rtp_gl_1d_table_b(), mpi_sph_gl_1d_idx_io::mpi_read_rtp_gl_1d_table(), mpi_sph_gl_1d_idx_io_b::mpi_read_rtp_gl_1d_table_b(), sph_global_1d_idx_io::read_rtp_gl_1d_table(), sph_global_1d_idx_io_b::read_rtp_gl_1d_table_b(), and gz_sph_global_1d_idx_io::read_rtp_gl_1d_table_gz().
alloc_nod_id_sph_io()
subroutine t_node_id_spherical_io::alloc_nod_id_sph_io (type(sph_io_data), intent(inout) sph_IO)
Definition at line 125 of file t_node_id_spherical_IO.f90.
Referenced by copy_sph_rj_mode_4_io::copy_sph_node_4_rj_to_io(), copy_sph_rlm_mode_4_io::copy_sph_node_4_rlm_to_io(), copy_sph_rtm_node_4_io::copy_sph_node_4_rtm_to_io(), copy_sph_rtp_node_4_io::copy_sph_node_4_rtp_to_io(), gz_mpi_spherical_model_io::gz_mpi_read_gl_nodes_sph(), gz_mpi_spherical_model_io_b::gz_mpi_read_gl_nodes_sph_b(), gz_spherical_model_io_b::gz_read_gl_nodes_sph_b(), mpi_spherical_model_io::mpi_read_gl_nodes_sph(), mpi_spherical_model_io_b::mpi_read_gl_nodes_sph_b(), spherical_model_io::read_gl_nodes_sph(), spherical_model_io_b::read_gl_nodes_sph_b(), and gz_spherical_model_io::read_gl_nodes_sph_gz().
alloc_num_idx_sph_io()
subroutine t_node_id_spherical_io::alloc_num_idx_sph_io (type(sph_io_data), intent(inout) sph_IO)
Definition at line 108 of file t_node_id_spherical_IO.f90.
Referenced by copy_sph_rj_mode_4_io::copy_sph_node_4_rj_to_io(), copy_sph_rlm_mode_4_io::copy_sph_node_4_rlm_to_io(), copy_sph_rtm_node_4_io::copy_sph_node_4_rtm_to_io(), copy_sph_rtp_node_4_io::copy_sph_node_4_rtp_to_io(), gz_mpi_sph_gl_1d_idx_io::gz_mpi_read_rj_gl_1d_table(), gz_mpi_sph_gl_1d_idx_io_b::gz_mpi_read_rj_gl_1d_table_b(), gz_mpi_sph_gl_1d_idx_io::gz_mpi_read_rtp_gl_1d_table(), gz_mpi_sph_gl_1d_idx_io_b::gz_mpi_read_rtp_gl_1d_table_b(), gz_sph_global_1d_idx_io_b::gz_read_rj_gl_1d_table_b(), gz_sph_global_1d_idx_io_b::gz_read_rtp_gl_1d_table_b(), mpi_sph_gl_1d_idx_io::mpi_read_rj_gl_1d_table(), mpi_sph_gl_1d_idx_io_b::mpi_read_rj_gl_1d_table_b(), mpi_sph_gl_1d_idx_io::mpi_read_rtp_gl_1d_table(), mpi_sph_gl_1d_idx_io_b::mpi_read_rtp_gl_1d_table_b(), sph_global_1d_idx_io::read_rj_gl_1d_table(), sph_global_1d_idx_io_b::read_rj_gl_1d_table_b(), gz_sph_global_1d_idx_io::read_rj_gl_1d_table_gz(), sph_global_1d_idx_io::read_rtp_gl_1d_table(), sph_global_1d_idx_io_b::read_rtp_gl_1d_table_b(), and gz_sph_global_1d_idx_io::read_rtp_gl_1d_table_gz().
dealloc_idx_sph_1d1_io()
subroutine, private t_node_id_spherical_io::dealloc_idx_sph_1d1_io (type(sph_io_data), intent(inout) sph_IO) private
Definition at line 214 of file t_node_id_spherical_IO.f90.
Referenced by dealloc_sph_grid_idx_io(), and dealloc_sph_mode_idx_io().
dealloc_idx_sph_1d2_io()
subroutine, private t_node_id_spherical_io::dealloc_idx_sph_1d2_io (type(sph_io_data), intent(inout) sph_IO) private
Definition at line 225 of file t_node_id_spherical_IO.f90.
Referenced by dealloc_sph_grid_idx_io(), and dealloc_sph_mode_idx_io().
dealloc_idx_sph_1d3_io()
subroutine, private t_node_id_spherical_io::dealloc_idx_sph_1d3_io (type(sph_io_data), intent(inout) sph_IO) private
Definition at line 235 of file t_node_id_spherical_IO.f90.
Referenced by dealloc_sph_grid_idx_io().
dealloc_nod_id_sph_io()
subroutine, private t_node_id_spherical_io::dealloc_nod_id_sph_io (type(sph_io_data), intent(inout) sph_IO) private
Definition at line 203 of file t_node_id_spherical_IO.f90.
Referenced by dealloc_sph_grid_idx_io(), and dealloc_sph_mode_idx_io().
dealloc_num_idx_sph_io()
subroutine, private t_node_id_spherical_io::dealloc_num_idx_sph_io (type(sph_io_data), intent(inout) sph_IO) private
Definition at line 190 of file t_node_id_spherical_IO.f90.
Referenced by dealloc_sph_grid_idx_io(), and dealloc_sph_mode_idx_io().
dealloc_sph_grid_idx_io()
subroutine t_node_id_spherical_io::dealloc_sph_grid_idx_io (type(sph_io_data), intent(inout) sph_IO)
Definition at line 78 of file t_node_id_spherical_IO.f90.
References dealloc_idx_sph_1d1_io(), dealloc_idx_sph_1d2_io(), dealloc_idx_sph_1d3_io(), dealloc_nod_id_sph_io(), and dealloc_num_idx_sph_io().
Referenced by t_spheric_data_io::dealloc_rtm_grid_io(), and t_spheric_data_io::dealloc_rtp_grid_io().
dealloc_sph_mode_idx_io()
subroutine t_node_id_spherical_io::dealloc_sph_mode_idx_io (type(sph_io_data), intent(inout) sph_IO)
Definition at line 93 of file t_node_id_spherical_IO.f90.
References dealloc_idx_sph_1d1_io(), dealloc_idx_sph_1d2_io(), dealloc_nod_id_sph_io(), and dealloc_num_idx_sph_io().
Referenced by t_spheric_data_io::dealloc_rj_mode_io(), and t_spheric_data_io::dealloc_rlm_mode_io().