CALYPSO: load_mesh_data Module Reference
load_mesh_data Module Reference
Copy FEM mesh data from IO structure.
Functions/Subroutines
subroutine input_mesh (mesh_file, id_rank, mesh, group, ierr)
subroutine input_mesh_geometry (mesh_file, id_rank, mesh, ierr)
subroutine output_mesh (mesh_file, id_rank, mesh, group)
subroutine set_mesh (fem_IO, mesh, group)
subroutine set_mesh_geometry_data (mesh_IO, nod_comm, node, ele)
subroutine set_node_geometry_data (mesh_IO, node)
subroutine set_zero_mesh_data (nod_comm, node, ele, surf, edge)
subroutine set_zero_node_data (node)
subroutine set_grp_data_from_io (mesh_group_IO, nod_grp, ele_grp, surf_grp)
subroutine set_grp_data_to_io (nod_grp, ele_grp, surf_grp, mesh_group_IO)
Detailed Description
Copy FEM mesh data from IO structure.
      subroutine input_mesh(mesh_file, id_rank, mesh, group, ierr)
        type(mesh_geometry), intent(inout) :: mesh
        type(mesh_groups), intent(inout) ::   group
      subroutine input_mesh_geometry(mesh_file, id_rank, mesh, ierr)
      subroutine output_mesh(mesh_file, id_rank, mesh, group)
        type(field_IO_params), intent(in) ::  mesh_file
        type(mesh_geometry), intent(inout) :: mesh
        type(mesh_groups), intent(inout) ::   group
      subroutine set_mesh(mesh, group)
      subroutine set_mesh_geometry_data(mesh_IO, nod_comm, node, ele)
      subroutine set_node_geometry_data(mesh_IO, node)
      subroutine set_zero_mesh_data                                   &
     &          (nod_comm, node, ele, surf, edge)
        type(communication_table), intent(inout) :: nod_comm
        type(node_data), intent(inout) :: node
        type(element_data), intent(inout) :: ele
        type(surface_data), intent(inout) :: surf
        type(edge_data), intent(inout) ::    edge
      subroutine set_zero_node_data(node)
        type(node_data), intent(inout) :: node
      subroutine set_grp_data_from_IO(nod_grp, ele_grp, surf_grp)
      subroutine set_grp_data_to_IO(nod_grp, ele_grp, surf_grp)
        type(mesh_groups), intent(inout) :: mesh_group_IO
        type(group_data), intent(inout) :: nod_grp, ele_grp
        type(surface_group_data), intent(inout) :: surf_grp
Function/Subroutine Documentation
input_mesh()
subroutine load_mesh_data::input_mesh (type(field_io_params), intent(in) mesh_file, integer, intent(in) id_rank, type(mesh_geometry), intent(inout) mesh, type(mesh_groups), intent(inout) group, integer(kind = kint), intent(inout) ierr)
Definition at line 61 of file load_mesh_data.f90.
References t_geometry_data::alloc_sph_node_geometry(), cal_minmax_and_stacks::s_cal_numbers_from_stack(), mesh_io_select::sel_read_mesh(), and set_nnod_4_ele_by_type::set_3d_nnod_4_sfed_by_ele().
input_mesh_geometry()
subroutine load_mesh_data::input_mesh_geometry (type(field_io_params), intent(in) mesh_file, integer, intent(in) id_rank, type(mesh_geometry), intent(inout) mesh, integer(kind = kint), intent(inout) ierr)
Definition at line 92 of file load_mesh_data.f90.
References mesh_io_select::sel_read_mesh_geometry(), and set_mesh_geometry_data().
output_mesh()
subroutine load_mesh_data::output_mesh (type(field_io_params), intent(in) mesh_file, integer, intent(in) id_rank, type(mesh_geometry), intent(inout) mesh, type(mesh_groups), intent(inout) group)
Definition at line 113 of file load_mesh_data.f90.
References t_comm_table::copy_comm_tbl_type(), set_element_data_4_io::copy_ele_connect_to_io(), copy_mesh_structures::copy_node_geometry_types(), t_mesh_data::dealloc_groups_data(), t_mesh_data::dealloc_mesh_geometry_base(), mesh_io_select::sel_write_mesh_file(), and set_grp_data_to_io().
set_grp_data_from_io()
subroutine load_mesh_data::set_grp_data_from_io (type(mesh_groups), intent(inout) mesh_group_IO, type(group_data), intent(inout) nod_grp, type(group_data), intent(inout) ele_grp, type(surface_group_data), intent(inout) surf_grp)
Definition at line 263 of file load_mesh_data.f90.
References set_group_types_4_io::set_gruop_stracture(), and set_group_types_4_io::set_surf_grp_stracture().
Referenced by set_mesh().
set_grp_data_to_io()
subroutine load_mesh_data::set_grp_data_to_io (type(group_data), intent(inout) nod_grp, type(group_data), intent(inout) ele_grp, type(surface_group_data), intent(inout) surf_grp, type(mesh_groups), intent(inout) mesh_group_IO)
Definition at line 281 of file load_mesh_data.f90.
References set_group_types_4_io::set_gruop_stracture(), and set_group_types_4_io::set_surf_grp_stracture().
Referenced by mpi_load_mesh_data::mpi_output_mesh(), and output_mesh().
set_mesh()
subroutine load_mesh_data::set_mesh (type(mesh_data), intent(inout) fem_IO, type(mesh_geometry), intent(inout) mesh, type(mesh_groups), intent(inout) group)
Definition at line 147 of file load_mesh_data.f90.
References t_mesh_data::dealloc_groups_data(), set_nnod_4_ele_by_type::set_3d_nnod_4_sfed_by_ele(), set_grp_data_from_io(), and set_mesh_geometry_data().
Referenced by mpi_load_mesh_data::mpi_input_mesh().
set_mesh_geometry_data()
subroutine load_mesh_data::set_mesh_geometry_data (type(mesh_geometry), intent(inout) mesh_IO, type(communication_table), intent(inout) nod_comm, type(node_data), intent(inout) node, type(element_data), intent(inout) ele)
Definition at line 170 of file load_mesh_data.f90.
References t_geometry_data::alloc_sph_node_geometry(), t_comm_table::copy_comm_tbl_type(), set_element_data_4_io::copy_ele_connect_from_io(), copy_mesh_structures::copy_node_geometry_types(), and t_mesh_data::dealloc_mesh_geometry_base().
Referenced by input_mesh_geometry(), mpi_load_mesh_data::mpi_input_mesh_geometry(), and set_mesh().
set_node_geometry_data()
subroutine load_mesh_data::set_node_geometry_data (type(mesh_geometry), intent(inout) mesh_IO, type(node_data), intent(inout) node)
Definition at line 193 of file load_mesh_data.f90.
References copy_mesh_structures::copy_node_geometry_types(), and t_mesh_data::dealloc_node_geometry_io().
Referenced by mpi_load_mesh_data::mpi_input_node_geometry().
set_zero_mesh_data()
subroutine load_mesh_data::set_zero_mesh_data (type(communication_table), intent(inout) nod_comm, type(node_data), intent(inout) node, type(element_data), intent(inout) ele, type(surface_data), intent(inout) surf, type(edge_data), intent(inout) edge)
Definition at line 211 of file load_mesh_data.f90.
References t_comm_table::alloc_comm_table_item(), t_comm_table::alloc_comm_table_num(), t_geometry_data::alloc_node_geometry_w_sph(), t_geometry_data::allocate_ele_connect_type(), m_constants::izero, and set_nnod_4_ele_by_type::set_3d_nnod_4_sfed_by_ele().
Referenced by mpi_load_mesh_data::mpi_input_mesh(), and mpi_load_mesh_data::mpi_input_mesh_geometry().
set_zero_node_data()
subroutine load_mesh_data::set_zero_node_data (type(node_data), intent(inout) node)
Definition at line 247 of file load_mesh_data.f90.
References t_geometry_data::alloc_node_geometry_w_sph(), and m_constants::izero.
Referenced by mpi_load_mesh_data::mpi_input_node_geometry().