CALYPSO: gz_merged_udt_vtk_file_io Module Reference
gz_merged_udt_vtk_file_io Module Reference
Output merged VTK or UCD file usging MPI-IO.
Functions/Subroutines
subroutine gz_write_ucd_file_mpi (gzip_name, ucd)
subroutine gz_write_ucd_phys_mpi (gzip_name, ucd)
subroutine gz_write_ucd_grid_mpi (gzip_name, ucd)
subroutine gz_write_vtk_file_mpi (gzip_name, ucd)
subroutine gz_write_vtk_phys_mpi (gzip_name, ucd)
subroutine gz_write_vtk_grid_mpi (gzip_name, ucd)
Variables
type(calypso_mpi_io_params), private io_param
Detailed Description
Output merged VTK or UCD file usging MPI-IO.
      subroutine gz_write_ucd_file_mpi(gzip_name, ucd)
      subroutine gz_write_ucd_phys_mpi(gzip_name, ucd)
      subroutine gz_write_ucd_grid_mpi(gzip_name, ucd)
      subroutine gz_write_vtk_file_mpi(gzip_name, ucd)
      subroutine gz_write_vtk_phys_mpi(gzip_name, ucd)
      subroutine gz_write_vtk_grid_mpi(gzip_name, ucd)
        type(ucd_data), intent(in) :: ucd
Function/Subroutine Documentation
gz_write_ucd_file_mpi()
subroutine gz_merged_udt_vtk_file_io::gz_write_ucd_file_mpi (character(len=kchara), intent(in) gzip_name, type(ucd_data), intent(in) ucd)
Definition at line 49 of file gz_merged_udt_vtk_file_IO.f90.
References gz_ucd_file_mpi_io::gz_write_ucd_data_mpi(), gz_ucd_file_mpi_io::gz_write_ucd_mesh_mpi(), calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_file().
gz_write_ucd_grid_mpi()
subroutine gz_merged_udt_vtk_file_io::gz_write_ucd_grid_mpi (character(len=kchara), intent(in) gzip_name, type(ucd_data), intent(in) ucd)
Definition at line 111 of file gz_merged_udt_vtk_file_IO.f90.
References gz_ucd_file_mpi_io::gz_write_ucd_mesh_mpi(), calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_mesh().
gz_write_ucd_phys_mpi()
subroutine gz_merged_udt_vtk_file_io::gz_write_ucd_phys_mpi (character(len=kchara), intent(in) gzip_name, type(ucd_data), intent(in) ucd)
Definition at line 82 of file gz_merged_udt_vtk_file_IO.f90.
References gz_ucd_file_mpi_io::gz_write_ucd_data_mpi(), calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_file().
gz_write_vtk_file_mpi()
subroutine gz_merged_udt_vtk_file_io::gz_write_vtk_file_mpi (character(len=kchara), intent(in) gzip_name, type(ucd_data), intent(in) ucd)
Definition at line 141 of file gz_merged_udt_vtk_file_IO.f90.
References gz_vtk_file_mpi_io::gz_write_vtk_data_mpi(), gz_vtk_file_mpi_io::gz_write_vtk_mesh_mpi(), calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_file().
gz_write_vtk_grid_mpi()
subroutine gz_merged_udt_vtk_file_io::gz_write_vtk_grid_mpi (character(len=kchara), intent(in) gzip_name, type(ucd_data), intent(in) ucd)
Definition at line 202 of file gz_merged_udt_vtk_file_IO.f90.
References gz_vtk_file_mpi_io::gz_write_vtk_mesh_mpi(), calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_mesh().
gz_write_vtk_phys_mpi()
subroutine gz_merged_udt_vtk_file_io::gz_write_vtk_phys_mpi (character(len=kchara), intent(in) gzip_name, type(ucd_data), intent(in) ucd)
Definition at line 174 of file gz_merged_udt_vtk_file_IO.f90.
References gz_vtk_file_mpi_io::gz_write_vtk_data_mpi(), calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_file().
Variable Documentation
io_param
type(calypso_mpi_io_params), private gz_merged_udt_vtk_file_io::io_param private
Definition at line 41 of file gz_merged_udt_vtk_file_IO.f90.