CALYPSO: const_r_mat_4_scalar_sph Module Reference
const_r_mat_4_scalar_sph Module Reference
Construct matrix for time evolution of scalar fields.
Functions/Subroutines
subroutine const_radial_mat_4_press_sph (sph_rj, r_2nd, fl_prop, sph_bc_U, fdm2_center, g_sph_rj, band_p_poisson)
subroutine const_radial_mat_4_scalar_sph (mat_name, dt, sph_rj, r_2nd, property, sph_bc, fdm2_center, g_sph_rj, band_s_evo)
Detailed Description
Construct matrix for time evolution of scalar fields.
      subroutine const_radial_mat_4_press_sph                         &
     &         (sph_rj, r_2nd, fl_prop, sph_bc_U, fdm2_center,        &
     &          g_sph_rj, band_p_poisson)
      subroutine const_radial_mat_4_scalar_sph                        &
     &         (mat_name, dt, sph_rj, r_2nd, property,                &
     &          sph_bc, fdm2_center, g_sph_rj, band_s_evo)
        type(scalar_property), intent(in) :: property
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(fdm_matrices), intent(in) :: r_2nd
        type(sph_boundary_type), intent(in) :: sph_bc_U
        type(fdm2_center_mat), intent(in) :: fdm2_center
Function/Subroutine Documentation
const_radial_mat_4_press_sph()
subroutine const_r_mat_4_scalar_sph::const_radial_mat_4_press_sph (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(fluid_property), intent(in) fl_prop, type(sph_boundary_type), intent(in) sph_bc_U, type(fdm2_center_mat), intent(in) fdm2_center, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, type(band_matrices_type), intent(inout) band_p_poisson)
Definition at line 45 of file const_r_mat_4_scalar_sph.f90.
References set_sph_scalar_mat_bc::add_cmb_scalar_poisson_mat(), set_sph_scalar_mat_bc::add_icb_scalar_poisson_mat(), center_sph_matrices::add_scalar_poisson_mat_ctr1(), set_radial_mat_sph::add_scalar_poisson_mat_sph(), t_sph_matrices::alloc_band_mat_sph(), t_sph_matrices::check_radial_band_mat(), m_machine_parameter::i_debug, m_machine_parameter::iflag_full_msg, t_boundary_params_sph_mhd::iflag_sph_fill_center, m_constants::ithree, t_sph_matrices::ludcmp_3band_mul_t(), calypso_mpi::my_rank, m_machine_parameter::np_smp, and set_radial_mat_sph::set_unit_mat_4_poisson().
Referenced by const_radial_mat_4_sph::const_radial_mat_sph_snap(), and const_radial_mat_4_sph::const_radial_matrices_sph().
const_radial_mat_4_scalar_sph()
subroutine const_r_mat_4_scalar_sph::const_radial_mat_4_scalar_sph (character(len=kchara), intent(in) mat_name, real(kind = kreal), intent(in) dt, type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(scalar_property), intent(in) property, type(sph_boundary_type), intent(in) sph_bc, type(fdm2_center_mat), intent(in) fdm2_center, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, type(band_matrices_type), intent(inout) band_s_evo)
Definition at line 119 of file const_r_mat_4_scalar_sph.f90.
References set_sph_scalar_mat_bc::add_fix_flux_cmb_poisson_mat(), set_sph_scalar_mat_bc::add_fix_flux_icb_poisson_mat(), center_sph_matrices::add_scalar_poisson_mat_ctr1(), set_radial_mat_sph::add_scalar_poisson_mat_sph(), t_sph_matrices::alloc_band_mat_sph(), t_sph_matrices::check_radial_band_mat(), m_machine_parameter::i_debug, t_physical_property::id_crank_nicolson, t_boundary_params_sph_mhd::iflag_evolve_flux, t_boundary_params_sph_mhd::iflag_fixed_flux, m_machine_parameter::iflag_full_msg, t_boundary_params_sph_mhd::iflag_sph_fill_center, t_boundary_params_sph_mhd::iflag_sph_fix_center, m_constants::ithree, t_sph_matrices::ludcmp_3band_mul_t(), calypso_mpi::my_rank, m_machine_parameter::np_smp, m_constants::one, set_sph_scalar_mat_bc::set_fix_fld_cmb_poisson_mat(), set_sph_scalar_mat_bc::set_fix_fld_icb_poisson_mat(), set_radial_mat_sph::set_unit_mat_4_poisson(), set_radial_mat_sph::set_unit_mat_4_time_evo(), t_sph_matrices::set_unit_on_diag(), and m_constants::zero.
Referenced by const_radial_mat_4_sph::const_radial_matrices_sph().