CALYPSO: m_fem_surface_labels Module Reference
m_fem_surface_labels Module Reference
Comments for surface mesh data.
Functions/Subroutines
character(len=ilen_ecomm_para) function hd_ecomm_para ()
character(len=ilen_ecomm_import) function hd_ecomm_import ()
character(len=ilen_ecomm_export) function hd_ecomm_export ()
character(len=ilen_ecomm_point) function hd_ecomm_point ()
character(len=ilen_ecomm_vol) function hd_ecomm_vol ()
character(len=ilen_surf_para) function hd_surf_para ()
character(len=ilen_surf_connect) function hd_surf_connect ()
character(len=ilen_surf_on_ele) function hd_surf_on_ele ()
character(len=ilen_surf_import) function hd_surf_import ()
character(len=ilen_surf_export) function hd_surf_export ()
character(len=ilen_surf_point) function hd_surf_point ()
character(len=ilen_surf_norm) function hd_surf_norm ()
character(len=ilen_surf_area) function hd_surf_area ()
character(len=ilen_edge_para) function hd_edge_para ()
character(len=ilen_edge_connect) function hd_edge_connect ()
character(len=ilen_edge_on_surf) function hd_edge_on_surf ()
character(len=ilen_edge_on_ele) function hd_edge_on_ele ()
character(len=ilen_edge_import) function hd_edge_import ()
character(len=ilen_edge_export) function hd_edge_export ()
character(len=ilen_edge_point) function hd_edge_point ()
character(len=ilen_edge_dir) function hd_edge_dir ()
character(len=ilen_edge_length) function hd_edge_length ()
Variables
integer(kind=kint), parameter ilen_ecomm_para = 1+19+26+1+4
length of ilen_ecomm_para
integer(kind=kint), parameter ilen_ecomm_import = 1+31+27+1+4
length of hd_ecomm_import
integer(kind=kint), parameter ilen_ecomm_export = 1+27+1+3
length of hd_ecomm_export
integer(kind=kint), parameter ilen_ecomm_point = 1+23+1+34+1+5
length of hd_ecomm_point
integer(kind=kint), parameter ilen_ecomm_vol = 1+23+1+3
length of hd_ecomm_vol
integer(kind=kint), parameter ilen_surf_para = 1+23+26+1+4
length of hd_surf_para
integer(kind=kint), parameter ilen_surf_connect = 1+26+28+28+1+5
length of hd_surf_connect
integer(kind=kint), parameter ilen_surf_on_ele = 1+34+33+30+1+5
length of hd_surf_on_ele
integer(kind=kint), parameter ilen_surf_import = 1+31+27+1+4
length of hd_surf_import
integer(kind=kint), parameter ilen_surf_export = 1+27+1+3
length of hd_surf_export
integer(kind=kint), parameter ilen_surf_point = 1+23+25+1+4
length of hd_surf_point
integer(kind=kint), parameter ilen_surf_norm = 1+31+1+3
length of hd_surf_norm
integer(kind=kint), parameter ilen_surf_area = 1+21+1+3
length of hd_surf_area
integer(kind=kint), parameter ilen_edge_para = 1+20+26+1+4
length of hd_edge_para
integer(kind=kint), parameter ilen_edge_connect = 1+23+25+28+1+5
length of hd_edge_connect
integer(kind=kint), parameter ilen_edge_on_surf = 1+32+1+3
length of hd_edge_on_surf
integer(kind=kint), parameter ilen_edge_on_ele = 1+33+1+3
length of hd_edge_on_ele
integer(kind=kint), parameter ilen_edge_import = 1+31+25+1+4
length of hd_edge_import
integer(kind=kint), parameter ilen_edge_export = 1+24+1+3
length of hd_edge_export
integer(kind=kint), parameter ilen_edge_point = 1+22+23+1+4
length of hd_edge_point
integer(kind=kint), parameter ilen_edge_dir = 1+25+1+3
length of hd_edge_dir
integer(kind=kint), parameter ilen_edge_length = 1+22+1+3
length of hd_edge_length
Detailed Description
Comments for surface mesh data.
      character(len=ilen_ecomm_para) function hd_ecomm_para()
      character(len=ilen_ecomm_import) function hd_ecomm_import()
      character(len=ilen_ecomm_export) function hd_ecomm_export()
      character(len=ilen_ecomm_point) function hd_ecomm_point()
      character(len=ilen_ecomm_vol) function hd_ecomm_vol()
      character(len=ilen_surf_para) function hd_surf_para()
      character(len=ilen_surf_connect) function hd_surf_connect()
      character(len=ilen_surf_on_ele) function hd_surf_on_ele()
      character(len=ilen_surf_import) function hd_surf_import()
      character(len=ilen_surf_export) function hd_surf_export()
      character(len=ilen_surf_point) function hd_surf_point()
      character(len=ilen_surf_norm) function hd_surf_norm()
      character(len=ilen_surf_area) function hd_surf_area()
      character(len=ilen_edge_para) function hd_edge_para()
      character(len=ilen_edge_connect) function hd_edge_connect()
      character(len=ilen_edge_on_surf) function hd_edge_on_surf()
      character(len=ilen_edge_on_ele) function hd_edge_on_ele()
      character(len=ilen_edge_import) function hd_edge_import()
      character(len=ilen_edge_export) function hd_edge_export()
      character(len=ilen_edge_point) function hd_edge_point()
      character(len=ilen_edge_dir) function hd_edge_dir()
      character(len=ilen_edge_length) function hd_edge_length()
Function/Subroutine Documentation
hd_ecomm_export()
character(len=ilen_ecomm_export) function m_fem_surface_labels::hd_ecomm_export
Definition at line 129 of file m_fem_surface_labels.f90.
Referenced by gz_mpi_element_data_io::gz_mpi_read_ele_comm_table(), gz_mpi_element_data_io::gz_mpi_write_ele_comm_table(), gz_element_data_io::gz_write_element_comm_table(), mpi_element_data_io::mpi_read_element_comm_table(), mpi_element_data_io::mpi_write_element_comm_table(), and element_data_io::write_element_comm_table().
hd_ecomm_import()
character(len=ilen_ecomm_import) function m_fem_surface_labels::hd_ecomm_import
Definition at line 117 of file m_fem_surface_labels.f90.
Referenced by gz_mpi_element_data_io::gz_mpi_read_ele_comm_table(), gz_mpi_element_data_io::gz_mpi_write_ele_comm_table(), gz_element_data_io::gz_write_element_comm_table(), mpi_element_data_io::mpi_read_element_comm_table(), mpi_element_data_io::mpi_write_element_comm_table(), and element_data_io::write_element_comm_table().
hd_ecomm_para()
character(len=ilen_ecomm_para) function m_fem_surface_labels::hd_ecomm_para
Definition at line 105 of file m_fem_surface_labels.f90.
Referenced by gz_mpi_element_data_io::gz_mpi_read_ele_comm_table(), gz_mpi_element_data_io::gz_mpi_write_ele_comm_table(), gz_element_data_io::gz_write_element_comm_table(), mpi_element_data_io::mpi_read_element_comm_table(), mpi_element_data_io::mpi_write_element_comm_table(), and element_data_io::write_element_comm_table().
hd_ecomm_point()
character(len=ilen_ecomm_point) function m_fem_surface_labels::hd_ecomm_point
Definition at line 141 of file m_fem_surface_labels.f90.
Referenced by gz_mpi_element_data_io::gz_mpi_read_ele_geometry(), gz_mpi_element_data_io::gz_mpi_write_ele_geometry(), gz_element_data_io::gz_write_element_geometry(), mpi_element_data_io::mpi_read_element_geometry(), mpi_element_data_io::mpi_write_element_geometry(), and element_data_io::write_element_geometry().
hd_ecomm_vol()
character(len=ilen_ecomm_vol) function m_fem_surface_labels::hd_ecomm_vol
Definition at line 154 of file m_fem_surface_labels.f90.
Referenced by gz_mpi_element_data_io::gz_mpi_read_ele_geometry(), gz_mpi_element_data_io::gz_mpi_write_ele_geometry(), gz_element_data_io::gz_write_element_geometry(), mpi_element_data_io::mpi_read_element_geometry(), mpi_element_data_io::mpi_write_element_geometry(), element_data_io::write_element_geometry(), element_data_io::write_element_geometry_cyl(), and element_data_io::write_element_geometry_sph().
hd_edge_connect()
character(len=ilen_edge_connect) function m_fem_surface_labels::hd_edge_connect
Definition at line 275 of file m_fem_surface_labels.f90.
Referenced by gz_mpi_edge_data_io::gz_mpi_read_edge_connect(), gz_mpi_edge_data_io::gz_mpi_write_edge_connect(), gz_edge_data_io::gz_write_edge_connection(), mpi_edge_data_io::mpi_read_edge_connection(), mpi_edge_data_io::mpi_write_edge_connection(), and edge_data_io::write_edge_connection().
hd_edge_dir()
character(len=ilen_edge_dir) function m_fem_surface_labels::hd_edge_dir
Definition at line 346 of file m_fem_surface_labels.f90.
Referenced by gz_mpi_edge_data_io::gz_mpi_read_edge_geometry(), gz_mpi_edge_data_io::gz_mpi_write_edge_geometry(), gz_edge_data_io::gz_write_edge_geometry(), mpi_edge_data_io::mpi_read_edge_geometry(), mpi_edge_data_io::mpi_write_edge_geometry(), edge_data_io::write_edge_geometry(), edge_data_io::write_edge_geometry_cyl(), and edge_data_io::write_edge_geometry_sph().
hd_edge_export()
character(len=ilen_edge_export) function m_fem_surface_labels::hd_edge_export
Definition at line 322 of file m_fem_surface_labels.f90.
Referenced by gz_mpi_edge_data_io::gz_mpi_read_edge_connect(), gz_mpi_edge_data_io::gz_mpi_write_edge_connect(), gz_edge_data_io::gz_write_edge_connection(), mpi_edge_data_io::mpi_read_edge_connection(), mpi_edge_data_io::mpi_write_edge_connection(), and edge_data_io::write_edge_connection().
hd_edge_import()
character(len=ilen_edge_import) function m_fem_surface_labels::hd_edge_import
Definition at line 310 of file m_fem_surface_labels.f90.
Referenced by gz_mpi_edge_data_io::gz_mpi_read_edge_connect(), gz_mpi_edge_data_io::gz_mpi_write_edge_connect(), gz_edge_data_io::gz_write_edge_connection(), mpi_edge_data_io::mpi_read_edge_connection(), mpi_edge_data_io::mpi_write_edge_connection(), and edge_data_io::write_edge_connection().
hd_edge_length()
character(len=ilen_edge_length) function m_fem_surface_labels::hd_edge_length
Definition at line 357 of file m_fem_surface_labels.f90.
Referenced by gz_mpi_edge_data_io::gz_mpi_read_edge_geometry(), gz_mpi_edge_data_io::gz_mpi_write_edge_geometry(), gz_edge_data_io::gz_write_edge_geometry(), mpi_edge_data_io::mpi_read_edge_geometry(), mpi_edge_data_io::mpi_write_edge_geometry(), edge_data_io::write_edge_geometry(), edge_data_io::write_edge_geometry_cyl(), and edge_data_io::write_edge_geometry_sph().
hd_edge_on_ele()
character(len=ilen_edge_on_ele) function m_fem_surface_labels::hd_edge_on_ele
Definition at line 299 of file m_fem_surface_labels.f90.
Referenced by gz_mpi_edge_data_io::gz_mpi_read_edge_connect(), gz_mpi_edge_data_io::gz_mpi_write_edge_connect(), gz_edge_data_io::gz_write_edge_connection(), mpi_edge_data_io::mpi_read_edge_connection(), mpi_edge_data_io::mpi_write_edge_connection(), and edge_data_io::write_edge_connection().
hd_edge_on_surf()
character(len=ilen_edge_on_surf) function m_fem_surface_labels::hd_edge_on_surf
Definition at line 288 of file m_fem_surface_labels.f90.
Referenced by gz_mpi_edge_data_io::gz_mpi_read_edge_connect(), gz_mpi_edge_data_io::gz_mpi_write_edge_connect(), gz_edge_data_io::gz_write_edge_connection(), mpi_edge_data_io::mpi_read_edge_connection(), mpi_edge_data_io::mpi_write_edge_connection(), and edge_data_io::write_edge_connection().
hd_edge_para()
character(len=ilen_edge_para) function m_fem_surface_labels::hd_edge_para
Definition at line 263 of file m_fem_surface_labels.f90.
Referenced by gz_mpi_edge_data_io::gz_mpi_read_edge_connect(), gz_mpi_edge_data_io::gz_mpi_write_edge_connect(), gz_edge_data_io::gz_write_edge_connection(), mpi_edge_data_io::mpi_read_edge_connection(), mpi_edge_data_io::mpi_write_edge_connection(), and edge_data_io::write_edge_connection().
hd_edge_point()
character(len=ilen_edge_point) function m_fem_surface_labels::hd_edge_point
Definition at line 334 of file m_fem_surface_labels.f90.
Referenced by gz_mpi_edge_data_io::gz_mpi_read_edge_geometry(), gz_mpi_edge_data_io::gz_mpi_write_edge_geometry(), gz_edge_data_io::gz_write_edge_geometry(), mpi_edge_data_io::mpi_read_edge_geometry(), mpi_edge_data_io::mpi_write_edge_geometry(), and edge_data_io::write_edge_geometry().
hd_surf_area()
character(len=ilen_surf_area) function m_fem_surface_labels::hd_surf_area
Definition at line 251 of file m_fem_surface_labels.f90.
Referenced by gz_mpi_surface_data_io::gz_mpi_read_surf_geometry(), gz_mpi_surface_data_io::gz_mpi_write_surf_geometry(), gz_surface_data_io::gz_write_surface_geometry(), mpi_surface_data_io::mpi_read_surface_geometry(), mpi_surface_data_io::mpi_write_surface_geometry(), surface_data_io::write_surface_geometry(), surface_data_io::write_surface_geometry_cyl(), and surface_data_io::write_surface_geometry_sph().
hd_surf_connect()
character(len=ilen_surf_connect) function m_fem_surface_labels::hd_surf_connect
Definition at line 178 of file m_fem_surface_labels.f90.
Referenced by gz_mpi_surface_data_io::gz_mpi_read_surf_connect(), gz_mpi_surface_data_io::gz_mpi_write_surf_connect(), gz_surface_data_io::gz_write_surface_connection(), mpi_surface_data_io::mpi_read_surface_connection(), mpi_surface_data_io::mpi_write_surface_connection(), and surface_data_io::write_surface_connection().
hd_surf_export()
character(len=ilen_surf_export) function m_fem_surface_labels::hd_surf_export
Definition at line 216 of file m_fem_surface_labels.f90.
Referenced by gz_mpi_surface_data_io::gz_mpi_read_surf_connect(), gz_mpi_surface_data_io::gz_mpi_write_surf_connect(), gz_surface_data_io::gz_write_surface_connection(), mpi_surface_data_io::mpi_read_surface_connection(), mpi_surface_data_io::mpi_write_surface_connection(), and surface_data_io::write_surface_connection().
hd_surf_import()
character(len=ilen_surf_import) function m_fem_surface_labels::hd_surf_import
Definition at line 204 of file m_fem_surface_labels.f90.
Referenced by gz_mpi_surface_data_io::gz_mpi_read_surf_connect(), gz_mpi_surface_data_io::gz_mpi_write_surf_connect(), gz_surface_data_io::gz_write_surface_connection(), mpi_surface_data_io::mpi_read_surface_connection(), mpi_surface_data_io::mpi_write_surface_connection(), and surface_data_io::write_surface_connection().
hd_surf_norm()
character(len=ilen_surf_norm) function m_fem_surface_labels::hd_surf_norm
Definition at line 240 of file m_fem_surface_labels.f90.
Referenced by gz_mpi_surface_data_io::gz_mpi_read_surf_geometry(), gz_mpi_surface_data_io::gz_mpi_write_surf_geometry(), gz_surface_data_io::gz_write_surface_geometry(), mpi_surface_data_io::mpi_read_surface_geometry(), mpi_surface_data_io::mpi_write_surface_geometry(), and surface_data_io::write_surface_geometry().
hd_surf_on_ele()
character(len=ilen_surf_on_ele) function m_fem_surface_labels::hd_surf_on_ele
Definition at line 191 of file m_fem_surface_labels.f90.
Referenced by gz_mpi_surface_data_io::gz_mpi_read_surf_connect(), gz_mpi_surface_data_io::gz_mpi_write_surf_connect(), gz_surface_data_io::gz_write_surface_connection(), mpi_surface_data_io::mpi_read_surface_connection(), mpi_surface_data_io::mpi_write_surface_connection(), and surface_data_io::write_surface_connection().
hd_surf_para()
character(len=ilen_surf_para) function m_fem_surface_labels::hd_surf_para
Definition at line 166 of file m_fem_surface_labels.f90.
Referenced by gz_mpi_surface_data_io::gz_mpi_read_surf_connect(), gz_mpi_surface_data_io::gz_mpi_write_surf_connect(), gz_surface_data_io::gz_write_surface_connection(), mpi_surface_data_io::mpi_read_surface_connection(), mpi_surface_data_io::mpi_write_surface_connection(), and surface_data_io::write_surface_connection().
hd_surf_point()
character(len=ilen_surf_point) function m_fem_surface_labels::hd_surf_point
Definition at line 228 of file m_fem_surface_labels.f90.
Referenced by gz_mpi_surface_data_io::gz_mpi_read_surf_geometry(), gz_mpi_surface_data_io::gz_mpi_write_surf_geometry(), gz_surface_data_io::gz_write_surface_geometry(), mpi_surface_data_io::mpi_read_surface_geometry(), mpi_surface_data_io::mpi_write_surface_geometry(), and surface_data_io::write_surface_geometry().
Variable Documentation
ilen_ecomm_export
integer(kind = kint), parameter m_fem_surface_labels::ilen_ecomm_export = 1+27+1+3
length of hd_ecomm_export
Definition at line 49 of file m_fem_surface_labels.f90.
ilen_ecomm_import
integer(kind = kint), parameter m_fem_surface_labels::ilen_ecomm_import = 1+31+27+1+4
length of hd_ecomm_import
Definition at line 46 of file m_fem_surface_labels.f90.
ilen_ecomm_para
integer(kind = kint), parameter m_fem_surface_labels::ilen_ecomm_para = 1+19+26+1+4
length of ilen_ecomm_para
Definition at line 43 of file m_fem_surface_labels.f90.
ilen_ecomm_point
integer(kind = kint), parameter m_fem_surface_labels::ilen_ecomm_point = 1+23+1+34+1+5
length of hd_ecomm_point
Definition at line 53 of file m_fem_surface_labels.f90.
ilen_ecomm_vol
integer(kind = kint), parameter m_fem_surface_labels::ilen_ecomm_vol = 1+23+1+3
length of hd_ecomm_vol
Definition at line 56 of file m_fem_surface_labels.f90.
ilen_edge_connect
integer(kind = kint), parameter m_fem_surface_labels::ilen_edge_connect = 1+23+25+28+1+5
length of hd_edge_connect
Definition at line 81 of file m_fem_surface_labels.f90.
ilen_edge_dir
integer(kind = kint), parameter m_fem_surface_labels::ilen_edge_dir = 1+25+1+3
length of hd_edge_dir
Definition at line 95 of file m_fem_surface_labels.f90.
ilen_edge_export
integer(kind = kint), parameter m_fem_surface_labels::ilen_edge_export = 1+24+1+3
length of hd_edge_export
Definition at line 90 of file m_fem_surface_labels.f90.
ilen_edge_import
integer(kind = kint), parameter m_fem_surface_labels::ilen_edge_import = 1+31+25+1+4
length of hd_edge_import
Definition at line 88 of file m_fem_surface_labels.f90.
ilen_edge_length
integer(kind = kint), parameter m_fem_surface_labels::ilen_edge_length = 1+22+1+3
length of hd_edge_length
Definition at line 97 of file m_fem_surface_labels.f90.
ilen_edge_on_ele
integer(kind = kint), parameter m_fem_surface_labels::ilen_edge_on_ele = 1+33+1+3
length of hd_edge_on_ele
Definition at line 86 of file m_fem_surface_labels.f90.
ilen_edge_on_surf
integer(kind = kint), parameter m_fem_surface_labels::ilen_edge_on_surf = 1+32+1+3
length of hd_edge_on_surf
Definition at line 84 of file m_fem_surface_labels.f90.
ilen_edge_para
integer(kind = kint), parameter m_fem_surface_labels::ilen_edge_para = 1+20+26+1+4
length of hd_edge_para
Definition at line 79 of file m_fem_surface_labels.f90.
ilen_edge_point
integer(kind = kint), parameter m_fem_surface_labels::ilen_edge_point = 1+22+23+1+4
length of hd_edge_point
Definition at line 93 of file m_fem_surface_labels.f90.
ilen_surf_area
integer(kind = kint), parameter m_fem_surface_labels::ilen_surf_area = 1+21+1+3
length of hd_surf_area
Definition at line 76 of file m_fem_surface_labels.f90.
ilen_surf_connect
integer(kind = kint), parameter m_fem_surface_labels::ilen_surf_connect = 1+26+28+28+1+5
length of hd_surf_connect
Definition at line 61 of file m_fem_surface_labels.f90.
ilen_surf_export
integer(kind = kint), parameter m_fem_surface_labels::ilen_surf_export = 1+27+1+3
length of hd_surf_export
Definition at line 69 of file m_fem_surface_labels.f90.
ilen_surf_import
integer(kind = kint), parameter m_fem_surface_labels::ilen_surf_import = 1+31+27+1+4
length of hd_surf_import
Definition at line 67 of file m_fem_surface_labels.f90.
ilen_surf_norm
integer(kind = kint), parameter m_fem_surface_labels::ilen_surf_norm = 1+31+1+3
length of hd_surf_norm
Definition at line 74 of file m_fem_surface_labels.f90.
ilen_surf_on_ele
integer(kind = kint), parameter m_fem_surface_labels::ilen_surf_on_ele = 1+34+33+30+1+5
length of hd_surf_on_ele
Definition at line 64 of file m_fem_surface_labels.f90.
ilen_surf_para
integer(kind = kint), parameter m_fem_surface_labels::ilen_surf_para = 1+23+26+1+4
length of hd_surf_para
Definition at line 59 of file m_fem_surface_labels.f90.
ilen_surf_point
integer(kind = kint), parameter m_fem_surface_labels::ilen_surf_point = 1+23+25+1+4
length of hd_surf_point
Definition at line 72 of file m_fem_surface_labels.f90.