CALYPSO: t_surf_edge_io Module Reference
t_surf_edge_io Module Reference
Data arry for mesh_data_IO.
Data Types
type surf_edge_io_data
Functions/Subroutines
subroutine alloc_surface_connect_io (numele, num_of_surf, sfed_IO)
subroutine alloc_edge_connect_io (numele, num_of_edge, sfed_IO)
subroutine dealloc_surface_connect_io (sfed_IO)
subroutine dealloc_edge_connect_io (sfed_IO)
subroutine alloc_ele_vector_io (nod_IO, sfed_IO)
subroutine dealloc_ele_vector_io (sfed_IO)
subroutine alloc_ele_scalar_io (nod_IO, sfed_IO)
subroutine dealloc_ele_scalar_io (sfed_IO)
Detailed Description
Data arry for mesh_data_IO.
      subroutine alloc_surface_connect_IO                             &
     &         (numele, num_of_surf, sfed_IO)
      subroutine alloc_edge_connect_IO(numele, num_of_edge, sfed_IO)
      subroutine dealloc_surface_connect_IO(sfed_IO)
      subroutine dealloc_edge_connect_IO(sfed_IO)
      subroutine alloc_ele_vector_IO(nod_IO, sfed_IO)
      subroutine dealloc_ele_vector_IO(sfed_IO)
      subroutine alloc_ele_scalar_IO(nod_IO, sfed_IO)
      subroutine dealloc_ele_scalar_IO(sfed_IO)
        type(node_data), intent(in) :: nod_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
Function/Subroutine Documentation
alloc_edge_connect_io()
subroutine t_surf_edge_io::alloc_edge_connect_io (integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) num_of_edge, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 69 of file t_surf_edge_IO.f90.
Referenced by set_edge_data_4_io::copy_edge_connect_to_io(), gz_mpi_element_connect_io::gz_mpi_read_edge_4_element(), gz_mpi_element_connect_io_b::gz_mpi_read_edge_4_element_b(), gz_element_connect_io::gz_read_edge_4_element(), gz_element_connect_io_b::gz_read_edge_4_element_b(), mpi_element_connect_io::mpi_read_edge_4_element(), mpi_element_connect_io_b::mpi_read_edge_4_element_b(), element_connect_io::read_edge_4_element(), and element_connect_io_b::read_edge_4_element_b().
alloc_ele_scalar_io()
subroutine t_surf_edge_io::alloc_ele_scalar_io (type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 133 of file t_surf_edge_IO.f90.
Referenced by set_edge_data_4_io::copy_edge_geometry_to_io(), set_element_data_4_io::copy_ele_cyl_geom_to_io(), set_element_data_4_io::copy_ele_geometry_to_io(), set_element_data_4_io::copy_ele_sph_geom_to_io(), set_surface_data_4_io::copy_surf_geometry_to_io(), gz_mpi_node_geometry_io::gz_mpi_read_scl_in_ele(), gz_mpi_node_geometry_io_b::gz_mpi_read_scl_in_ele_b(), gz_node_geometry_io::gz_read_scalar_in_element(), gz_node_geometry_io_b::gz_read_scalar_in_element_b(), mpi_node_geometry_io::mpi_read_scl_in_ele(), mpi_node_geometry_io_b::mpi_read_scl_in_ele_b(), node_geometry_io::read_scalar_in_element(), and node_geometry_io_b::read_scalar_in_element_b().
alloc_ele_vector_io()
subroutine t_surf_edge_io::alloc_ele_vector_io (type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 108 of file t_surf_edge_IO.f90.
Referenced by set_edge_data_4_io::copy_edge_geometry_to_io(), set_surface_data_4_io::copy_surf_geometry_to_io(), gz_mpi_node_geometry_io::gz_mpi_read_vect_in_ele(), gz_mpi_node_geometry_io_b::gz_mpi_read_vect_in_ele_b(), gz_node_geometry_io::gz_read_vector_in_element(), gz_node_geometry_io_b::gz_read_vector_in_element_b(), mpi_node_geometry_io::mpi_read_vect_in_ele(), mpi_node_geometry_io_b::mpi_read_vect_in_ele_b(), node_geometry_io::read_vector_in_element(), and node_geometry_io_b::read_vector_in_element_b().
alloc_surface_connect_io()
subroutine t_surf_edge_io::alloc_surface_connect_io (integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) num_of_surf, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 53 of file t_surf_edge_IO.f90.
Referenced by set_edge_data_4_io::copy_edge_connect_to_io(), set_surface_data_4_io::copy_surf_connect_to_io(), gz_mpi_element_connect_io_b::gz_mpi_read_surf_4_elem_b(), gz_mpi_element_connect_io::gz_mpi_read_surface_4_element(), gz_element_connect_io::gz_read_surface_4_element(), gz_element_connect_io_b::gz_read_surface_4_element_b(), mpi_element_connect_io::mpi_read_surface_4_element(), mpi_element_connect_io_b::mpi_read_surface_4_element_b(), element_connect_io::read_surface_4_element(), and element_connect_io_b::read_surface_4_element_b().
dealloc_edge_connect_io()
subroutine t_surf_edge_io::dealloc_edge_connect_io (type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 96 of file t_surf_edge_IO.f90.
Referenced by t_read_mesh_data::dealloc_edge_mesh_io().
dealloc_ele_scalar_io()
subroutine t_surf_edge_io::dealloc_ele_scalar_io (type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 146 of file t_surf_edge_IO.f90.
Referenced by t_read_mesh_data::dealloc_ele_geometry_data(), and t_read_mesh_data::dealloc_surf_geometry_data().
dealloc_ele_vector_io()
subroutine t_surf_edge_io::dealloc_ele_vector_io (type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 121 of file t_surf_edge_IO.f90.
Referenced by t_read_mesh_data::dealloc_surf_geometry_data().
dealloc_surface_connect_io()
subroutine t_surf_edge_io::dealloc_surface_connect_io (type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 85 of file t_surf_edge_IO.f90.
Referenced by t_read_mesh_data::dealloc_edge_mesh_io(), and t_read_mesh_data::dealloc_surface_mesh_io().