CALYPSO: copy_single_fft_and_rtp Module Reference
copy_single_fft_and_rtp Module Reference
Data copy between rtp field and single FFT.
Functions/Subroutines
subroutine sum_omp_elapsed_4_fft (np_smp, time_omp, ave_time)
subroutine sel_copy_single_rtp_to_fft (j, nnod_rtp, istep_phi, nnod_rt, Nfft_r, X_rtp, X_fft)
subroutine sel_copy_single_fft_to_rtp (j, nnod_rtp, istep_phi, nnod_rt, Nfft_r, X_fft, X_rtp)
subroutine sel_copy_comp_rtp_to_fft (j, nnod_rtp, istep_phi, nnod_rt, Nfft_r, ncomp_fwd, X_rtp, X_fft)
subroutine sel_copy_comp_fft_to_rtp (j, nnod_rtp, istep_phi, nnod_rt, Nfft_r, ncomp_bwd, X_fft, X_rtp)
Detailed Description
Data copy between rtp field and single FFT.
      subroutine sum_omp_elapsed_4_FFT(np_smp, time_omp, ave_time)
      subroutine sel_copy_single_rtp_to_FFT                           &
     &         (j, nnod_rtp, istep_phi, nnod_rt, Nfft_r, X_rtp, X_fft)
      subroutine sel_copy_single_FFT_to_rtp                           &
     &         (j, nnod_rtp, istep_phi, nnod_rt, Nfft_r, X_fft, X_rtp)
      subroutine sel_copy_comp_rtp_to_FFT                             &
     &         (j, nnod_rtp, istep_phi, nnod_rt, Nfft_r,              &
     &          ncomp_fwd, X_rtp, X_fft)
      subroutine sel_copy_comp_FFT_to_rtp                             &
     &         (j, nnod_rtp, istep_phi, nnod_rt, Nfft_r,              &
     &          ncomp_bwd, X_fft, X_rtp)
Function/Subroutine Documentation
sel_copy_comp_fft_to_rtp()
subroutine copy_single_fft_and_rtp::sel_copy_comp_fft_to_rtp (integer(kind = kint), intent(in) j, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) istep_phi, integer(kind = kint), intent(in) nnod_rt, integer(kind = kint), intent(in) Nfft_r, integer(kind = kint), intent(in) ncomp_bwd, real(kind = kreal), dimension(ncomp_bwd,nfft_r), intent(in) X_fft, real(kind = kreal), dimension(nnod_rtp,ncomp_bwd), intent(inout) X_rtp)
Definition at line 145 of file copy_single_FFT_and_rtp.f90.
Referenced by t_sph_component_fftw::sph_comp_back_fftw_from_recv(), and t_sph_component_fftpack5::sph_comp_rfftmb_from_recv().
sel_copy_comp_rtp_to_fft()
subroutine copy_single_fft_and_rtp::sel_copy_comp_rtp_to_fft (integer(kind = kint), intent(in) j, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) istep_phi, integer(kind = kint), intent(in) nnod_rt, integer(kind = kint), intent(in) Nfft_r, integer(kind = kint), intent(in) ncomp_fwd, real(kind = kreal), dimension(nnod_rtp,ncomp_fwd), intent(in) X_rtp, real(kind = kreal), dimension(ncomp_fwd,nfft_r), intent(inout) X_fft)
Definition at line 114 of file copy_single_FFT_and_rtp.f90.
Referenced by t_sph_component_fftw::sph_comp_fwd_fftw_to_send(), and t_sph_component_fftpack5::sph_comp_rfftmf_to_send().
sel_copy_single_fft_to_rtp()
subroutine copy_single_fft_and_rtp::sel_copy_single_fft_to_rtp (integer(kind = kint), intent(in) j, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) istep_phi, integer(kind = kint), intent(in) nnod_rt, integer(kind = kint), intent(in) Nfft_r, real(kind = kreal), dimension(nfft_r), intent(in) X_fft, real(kind = kreal), dimension(nnod_rtp), intent(inout) X_rtp)
Definition at line 87 of file copy_single_FFT_and_rtp.f90.
Referenced by t_sph_single_fftw::sph_single_back_fftw_from_recv(), and t_sph_single_fftpack5::sph_single_rfftmb_from_recv().
sel_copy_single_rtp_to_fft()
subroutine copy_single_fft_and_rtp::sel_copy_single_rtp_to_fft (integer(kind = kint), intent(in) j, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) istep_phi, integer(kind = kint), intent(in) nnod_rt, integer(kind = kint), intent(in) Nfft_r, real(kind = kreal), dimension(nnod_rtp), intent(in) X_rtp, real(kind = kreal), dimension(nfft_r), intent(inout) X_fft)
Definition at line 60 of file copy_single_FFT_and_rtp.f90.
Referenced by t_sph_single_fftw::sph_single_fwd_fftw_to_send(), and t_sph_single_fftpack5::sph_single_rfftmf_to_send().
sum_omp_elapsed_4_fft()
subroutine copy_single_fft_and_rtp::sum_omp_elapsed_4_fft (integer(kind = kint), intent(in) np_smp, real(kind = kreal), dimension(np_smp,3), intent(inout) time_omp, real(kind = kreal), dimension(3), intent(inout) ave_time)
Definition at line 37 of file copy_single_FFT_and_rtp.f90.
Referenced by t_sph_component_fftw::sph_comp_back_fftw_from_recv(), t_sph_component_fftw::sph_comp_fwd_fftw_to_send(), t_sph_component_fftpack5::sph_comp_rfftmb_from_recv(), t_sph_component_fftpack5::sph_comp_rfftmf_to_send(), t_sph_single_fftw::sph_single_back_fftw_from_recv(), t_sph_single_fftw::sph_single_fwd_fftw_to_send(), t_sph_single_fftpack5::sph_single_rfftmb_from_recv(), and t_sph_single_fftpack5::sph_single_rfftmf_to_send().