CALYPSO: t_spheric_data_io Module Reference
t_spheric_data_io Module Reference
Structure for grid and comm table for spherical transform.
Data Types
type mul_sph_group_data
Structure of group data for spherical transform.
type multi_sph_file_data
Structure of spherical transform mesh IO for multiple domains.
type sph_file_data_type
Structure of spherical transform mesh IO.
Functions/Subroutines
subroutine dealloc_rtp_grid_io (sph_IO)
subroutine dealloc_rtm_grid_io (sph_IO)
subroutine dealloc_rlm_mode_io (sph_IO)
subroutine dealloc_rj_mode_io (sph_IO)
subroutine alloc_multi_mesh_data_io (nloop, sph_file)
subroutine dealloc_multi_mesh_data_io (sph_file)
subroutine, private alloc_multi_sph_group_io (nloop, sph_grp_IO)
subroutine dealloc_multi_sph_group_io (sph_grp_IO)
Detailed Description
Structure for grid and comm table for spherical transform.
      subroutine alloc_multi_mesh_data_IO(nloop, sph_file)
      subroutine dealloc_multi_mesh_data_IO(sph_file)
Function/Subroutine Documentation
alloc_multi_mesh_data_io()
subroutine t_spheric_data_io::alloc_multi_mesh_data_io (integer(kind = kint), intent(in) nloop, type(multi_sph_file_data), intent(inout) sph_file)
Definition at line 125 of file t_spheric_data_IO.f90.
References alloc_multi_sph_group_io().
alloc_multi_sph_group_io()
subroutine, private t_spheric_data_io::alloc_multi_sph_group_io (integer(kind = kint), intent(in) nloop, type(mul_sph_group_data), intent(inout) sph_grp_IO) private
Definition at line 155 of file t_spheric_data_IO.f90.
Referenced by alloc_multi_mesh_data_io().
dealloc_multi_mesh_data_io()
subroutine t_spheric_data_io::dealloc_multi_mesh_data_io (type(multi_sph_file_data), intent(inout) sph_file)
Definition at line 141 of file t_spheric_data_IO.f90.
References dealloc_multi_sph_group_io().
dealloc_multi_sph_group_io()
subroutine t_spheric_data_io::dealloc_multi_sph_group_io (type(mul_sph_group_data), intent(inout) sph_grp_IO)
Definition at line 173 of file t_spheric_data_IO.f90.
Referenced by dealloc_multi_mesh_data_io().
dealloc_rj_mode_io()
subroutine t_spheric_data_io::dealloc_rj_mode_io (type(sph_file_data_type), intent(inout) sph_IO)
Definition at line 112 of file t_spheric_data_IO.f90.
References t_comm_table::dealloc_import_table(), t_spheric_group::dealloc_sph_mode_group(), and t_node_id_spherical_io::dealloc_sph_mode_idx_io().
Referenced by r_interpolate_sph_data::input_old_rj_sph_trans(), output_gen_sph_grid_modes::load_local_rj_mesh_4_merge(), parallel_load_data_4_sph::load_sph_mesh(), parallel_load_data_4_sph::load_sph_rj_mesh(), parallel_load_data_4_sph::output_sph_mesh(), parallel_load_data_4_sph::output_sph_rj_mesh(), output_gen_sph_grid_modes::para_output_sph_mode_grids(), output_gen_sph_grid_modes::para_output_sph_rj_modes(), and compare_sph_with_io::s_compare_sph_with_io().
dealloc_rlm_mode_io()
subroutine t_spheric_data_io::dealloc_rlm_mode_io (type(sph_file_data_type), intent(inout) sph_IO)
Definition at line 101 of file t_spheric_data_IO.f90.
References t_comm_table::dealloc_import_table(), and t_node_id_spherical_io::dealloc_sph_mode_idx_io().
Referenced by parallel_load_data_4_sph::load_sph_mesh(), parallel_load_data_4_sph::output_sph_mesh(), output_gen_sph_grid_modes::para_output_sph_mode_grids(), and compare_sph_with_io::s_compare_sph_with_io().
dealloc_rtm_grid_io()
subroutine t_spheric_data_io::dealloc_rtm_grid_io (type(sph_file_data_type), intent(inout) sph_IO)
Definition at line 90 of file t_spheric_data_IO.f90.
References t_comm_table::dealloc_import_table(), and t_node_id_spherical_io::dealloc_sph_grid_idx_io().
Referenced by parallel_load_data_4_sph::load_sph_mesh(), parallel_load_data_4_sph::output_sph_mesh(), output_gen_sph_grid_modes::para_output_sph_mode_grids(), and compare_sph_with_io::s_compare_sph_with_io().
dealloc_rtp_grid_io()
subroutine t_spheric_data_io::dealloc_rtp_grid_io (type(sph_file_data_type), intent(inout) sph_IO)
Definition at line 78 of file t_spheric_data_IO.f90.
References t_comm_table::dealloc_import_table(), t_spheric_group::dealloc_sph_grid_group(), and t_node_id_spherical_io::dealloc_sph_grid_idx_io().
Referenced by parallel_load_data_4_sph::load_sph_mesh(), parallel_load_data_4_sph::output_sph_mesh(), output_gen_sph_grid_modes::para_output_sph_mode_grids(), and compare_sph_with_io::s_compare_sph_with_io().