CALYPSO: sph_mean_spectr_header_io Module Reference
sph_mean_spectr_header_io Module Reference
Mean sqare data.
Functions/Subroutines
subroutine write_sph_vol_mean_sq_header (id_file, mode_label, ene_labels, sph_params, sph_rj, v_pwr)
subroutine write_sph_mean_sq_header (id_file, mode_label, ltr, nlayer_ICB, nlayer_CMB, ene_labels, pwr)
integer(kind=kint) function check_sph_vol_mean_sq_header (id_file, mode_label, ene_labels, sph_params, sph_rj, v_pwr)
subroutine set_sph_rms_labels_4_monitor (ene_labels, pwr, pick_rms)
Detailed Description
Mean sqare data.
      subroutine write_sph_vol_mean_sq_header(id_file, mode_label,    &
     &          ene_labels, sph_params, sph_rj, v_pwr)
      subroutine write_sph_mean_sq_header(id_file, mode_label,        &
     &          ltr, nlayer_ICB, nlayer_CMB, ene_labels, pwr)
      integer(kind = kint)  function check_sph_vol_mean_sq_header     &
     &                   (id_file, mode_label, ene_labels,            &
     &                    sph_params, sph_rj, v_pwr)
        type(energy_label_param), intent(in) :: ene_labels
        type(sph_shell_parameters), intent(in) :: sph_params
        type(sph_rj_grid), intent(in) :: sph_rj
        type(sph_vol_mean_squares), intent(in) :: v_pwr
      subroutine set_sph_rms_labels_4_monitor                         &
     &         (ene_labels, pwr, pick_rms)
        type(energy_label_param), intent(in) :: ene_labels
        type(sph_mean_squares), intent(in) :: pwr
        type(picked_spectrum_data), intent(inout) :: pick_rms
Parameters
istep time step number
time time
Parameters
id_file file ID for output
fname_rms file name for output
mode_label data label for degree or order of harmonics
Function/Subroutine Documentation
check_sph_vol_mean_sq_header()
integer(kind = kint) function sph_mean_spectr_header_io::check_sph_vol_mean_sq_header (integer(kind = kint), intent(in) id_file, character(len = kchara), intent(in) mode_label, type(energy_label_param), intent(in) ene_labels, type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(sph_vol_mean_squares), intent(in) v_pwr)
Definition at line 146 of file sph_mean_spectr_header_IO.f90.
References t_energy_label_parameters::set_sph_rms_labels(), and skip_comment_f::skip_comment().
Referenced by sph_mean_spectr_io::check_sph_vol_mean_sq_file().
set_sph_rms_labels_4_monitor()
subroutine sph_mean_spectr_header_io::set_sph_rms_labels_4_monitor (type(energy_label_param), intent(in) ene_labels, type(sph_mean_squares), intent(in) pwr, type(picked_spectrum_data), intent(inout) pick_rms)
Definition at line 287 of file sph_mean_spectr_header_IO.f90.
References t_energy_label_parameters::set_sph_rms_labels().
write_sph_mean_sq_header()
subroutine sph_mean_spectr_header_io::write_sph_mean_sq_header (integer(kind = kint), intent(in) id_file, character(len = kchara), intent(in) mode_label, integer(kind = kint), intent(in) ltr, integer(kind = kint), intent(in) nlayer_ICB, integer(kind = kint), intent(in) nlayer_CMB, type(energy_label_param), intent(in) ene_labels, type(sph_mean_squares), intent(in) pwr)
Definition at line 104 of file sph_mean_spectr_header_IO.f90.
References t_energy_label_parameters::set_sph_rms_labels(), and write_field_labels::write_multi_labels().
Referenced by sph_mean_spectr_io::open_sph_mean_sq_file().
write_sph_vol_mean_sq_header()
subroutine sph_mean_spectr_header_io::write_sph_vol_mean_sq_header (integer(kind = kint), intent(in) id_file, character(len = kchara), intent(in) mode_label, type(energy_label_param), intent(in) ene_labels, type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(sph_vol_mean_squares), intent(in) v_pwr)
Definition at line 53 of file sph_mean_spectr_header_IO.f90.
References t_energy_label_parameters::set_sph_rms_labels(), and write_field_labels::write_multi_labels().
Referenced by sph_mean_spectr_io::open_sph_vol_mean_sq_file().