CALYPSO: gz_mpi_spherical_model_io_b Module Reference
gz_mpi_spherical_model_io_b Module Reference
Data IO routines for spectrum data.
Functions/Subroutines
subroutine gz_mpi_read_rank_4_sph_b (IO_param, sph_IO)
subroutine gz_mpi_read_gl_reso_sph_b (IO_param, sph_IO)
subroutine gz_mpi_read_gl_nodes_sph_b (IO_param, sph_IO)
subroutine gz_mpi_write_rank_4_sph_b (IO_param, sph_IO)
subroutine gz_mpi_write_gl_reso_sph_b (IO_param, sph_IO)
subroutine gz_mpi_write_gl_nodes_sph_b (IO_param, sph_IO)
Detailed Description
Data IO routines for spectrum data.
      subroutine gz_mpi_read_rank_4_sph_b(IO_param, sph_IO)
      subroutine gz_mpi_read_gl_reso_sph_b(IO_param, sph_IO)
      subroutine gz_mpi_read_gl_nodes_sph_b(IO_param, sph_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(sph_IO_data), intent(inout) :: sph_IO
      subroutine gz_mpi_write_rank_4_sph_b(IO_param, sph_IO)
      subroutine gz_mpi_write_gl_reso_sph_b(IO_param, sph_IO)
      subroutine gz_mpi_write_gl_nodes_sph_b(IO_param, sph_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(sph_IO_data), intent(in) :: sph_IO
Function/Subroutine Documentation
gz_mpi_read_gl_nodes_sph_b()
subroutine gz_mpi_spherical_model_io_b::gz_mpi_read_gl_nodes_sph_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(inout) sph_IO)
Definition at line 70 of file gz_MPI_spherical_model_IO_b.f90.
References t_node_id_spherical_io::alloc_nod_id_sph_io(), gz_mpi_binary_data_io::gz_mpi_read_int8_vector_b(), gz_mpi_binary_data_io::gz_mpi_read_int_vector_b(), and gz_mpi_binary_datum_io::gz_mpi_read_one_integer_b().
Referenced by gz_mpi_sph_modes_data_io_b::gz_mpi_read_geom_rtm_data_b(), gz_mpi_sph_modes_data_io_b::gz_mpi_read_geom_rtp_data_b(), gz_mpi_sph_modes_data_io_b::gz_mpi_read_modes_rlm_data_b(), and gz_mpi_sph_modes_data_io_b::gz_mpi_read_spectr_rj_data_b().
gz_mpi_read_gl_reso_sph_b()
subroutine gz_mpi_spherical_model_io_b::gz_mpi_read_gl_reso_sph_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(inout) sph_IO)
Definition at line 56 of file gz_MPI_spherical_model_IO_b.f90.
References gz_mpi_binary_head_io::gz_mpi_read_mul_inthead_b(), and gz_mpi_binary_datum_io::gz_mpi_read_one_inthead_b().
Referenced by gz_mpi_sph_modes_data_io_b::gz_mpi_read_geom_rtm_data_b(), gz_mpi_sph_modes_data_io_b::gz_mpi_read_geom_rtp_data_b(), gz_mpi_sph_modes_data_io_b::gz_mpi_read_modes_rlm_data_b(), and gz_mpi_sph_modes_data_io_b::gz_mpi_read_spectr_rj_data_b().
gz_mpi_read_rank_4_sph_b()
subroutine gz_mpi_spherical_model_io_b::gz_mpi_read_rank_4_sph_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(inout) sph_IO)
Definition at line 41 of file gz_MPI_spherical_model_IO_b.f90.
References gz_mpi_binary_data_io::gz_mpi_read_int_vector_b().
Referenced by gz_mpi_sph_modes_data_io_b::gz_mpi_read_geom_rtm_data_b(), gz_mpi_sph_modes_data_io_b::gz_mpi_read_geom_rtp_data_b(), gz_mpi_sph_modes_data_io_b::gz_mpi_read_modes_rlm_data_b(), and gz_mpi_sph_modes_data_io_b::gz_mpi_read_spectr_rj_data_b().
gz_mpi_write_gl_nodes_sph_b()
subroutine gz_mpi_spherical_model_io_b::gz_mpi_write_gl_nodes_sph_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(in) sph_IO)
Definition at line 123 of file gz_MPI_spherical_model_IO_b.f90.
References gz_mpi_binary_data_io::gz_mpi_write_int8_vector_b(), gz_mpi_binary_data_io::gz_mpi_write_int_vector_b(), and gz_mpi_binary_datum_io::gz_mpi_write_one_integer_b().
Referenced by gz_mpi_sph_modes_data_io_b::gz_mpi_write_geom_rtm_data_b(), gz_mpi_sph_modes_data_io_b::gz_mpi_write_geom_rtp_data_b(), gz_mpi_sph_modes_data_io_b::gz_mpi_write_modes_rlm_data_b(), and gz_mpi_sph_modes_data_io_b::gz_mpi_write_spectr_rj_data_b().
gz_mpi_write_gl_reso_sph_b()
subroutine gz_mpi_spherical_model_io_b::gz_mpi_write_gl_reso_sph_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(in) sph_IO)
Definition at line 109 of file gz_MPI_spherical_model_IO_b.f90.
References gz_mpi_binary_head_io::gz_mpi_write_mul_inthead_b(), and gz_mpi_binary_datum_io::gz_mpi_write_one_inthead_b().
Referenced by gz_mpi_sph_modes_data_io_b::gz_mpi_write_geom_rtm_data_b(), gz_mpi_sph_modes_data_io_b::gz_mpi_write_geom_rtp_data_b(), gz_mpi_sph_modes_data_io_b::gz_mpi_write_modes_rlm_data_b(), and gz_mpi_sph_modes_data_io_b::gz_mpi_write_spectr_rj_data_b().
gz_mpi_write_rank_4_sph_b()
subroutine gz_mpi_spherical_model_io_b::gz_mpi_write_rank_4_sph_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(in) sph_IO)
Definition at line 94 of file gz_MPI_spherical_model_IO_b.f90.
References gz_mpi_binary_data_io::gz_mpi_write_int_vector_b().
Referenced by gz_mpi_sph_modes_data_io_b::gz_mpi_write_geom_rtm_data_b(), gz_mpi_sph_modes_data_io_b::gz_mpi_write_geom_rtp_data_b(), gz_mpi_sph_modes_data_io_b::gz_mpi_write_modes_rlm_data_b(), and gz_mpi_sph_modes_data_io_b::gz_mpi_write_spectr_rj_data_b().