CALYPSO: gz_edge_data_io Module Reference
gz_edge_data_io Module Reference
data IO orutines for edge
Functions/Subroutines
subroutine gz_read_edge_connection (id_rank, comm_IO, ele_IO, sfed_IO, zbuf, ierr)
subroutine gz_write_edge_connection (id_rank, comm_IO, ele_IO, sfed_IO, zbuf)
subroutine gz_read_edge_geometry (nod_IO, sfed_IO, zbuf)
subroutine gz_write_edge_geometry (nod_IO, sfed_IO, zbuf)
Detailed Description
data IO orutines for edge
      subroutine gz_read_edge_connection                              &
     &         (id_rank, comm_IO, ele_IO, sfed_IO, zbuf, ierr)
        type(communication_table), intent(inout) :: comm_IO
        type(element_data), intent(inout) :: ele_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
      subroutine gz_write_edge_connection                             &
     &         (id_rank, comm_IO, ele_IO, sfed_IO, zbuf)
        type(communication_table), intent(in) :: comm_IO
        type(element_data), intent(in) :: ele_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
      subroutine gz_read_edge_geometry(nod_IO, sfed_IO, zbuf)
        type(node_data), intent(inout) :: nod_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
        type(buffer_4_gzip), intent(inout) :: zbuf
      subroutine gz_write_edge_geometry(nod_IO, sfed_IO, zbuf)
        type(node_data), intent(in) :: nod_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
        type(buffer_4_gzip), intent(inout) :: zbuf
Function/Subroutine Documentation
gz_read_edge_connection()
subroutine gz_edge_data_io::gz_read_edge_connection (integer, intent(in) id_rank, type(communication_table), intent(inout) comm_IO, type(element_data), intent(inout) ele_IO, type(surf_edge_io_data), intent(inout) sfed_IO, type(buffer_4_gzip), intent(inout) zbuf, integer(kind = kint), intent(inout) ierr)
Definition at line 51 of file gz_edge_data_IO.f90.
References gz_domain_data_io::gz_read_domain_info(), gz_element_connect_io::gz_read_edge_4_element(), gz_element_connect_io::gz_read_element_info(), gz_domain_data_io::gz_read_export_data(), gz_domain_data_io::gz_read_import_data(), gz_element_connect_io::gz_read_number_of_element(), and gz_element_connect_io::gz_read_surface_4_element().
Referenced by gz_element_file_io::gz_input_edge_file().
gz_read_edge_geometry()
subroutine gz_edge_data_io::gz_read_edge_geometry (type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 167 of file gz_edge_data_IO.f90.
References gz_node_geometry_io::gz_read_geometry_info(), gz_node_geometry_io::gz_read_number_of_node(), gz_node_geometry_io::gz_read_scalar_in_element(), and gz_node_geometry_io::gz_read_vector_in_element().
gz_write_edge_connection()
subroutine gz_edge_data_io::gz_write_edge_connection (integer, intent(in) id_rank, type(communication_table), intent(in) comm_IO, type(element_data), intent(in) ele_IO, type(surf_edge_io_data), intent(in) sfed_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 114 of file gz_edge_data_IO.f90.
References gz_domain_data_io::gz_write_domain_info(), gz_element_connect_io::gz_write_edge_4_element(), gz_element_connect_io::gz_write_element_info(), gz_domain_data_io::gz_write_export_data(), gz_domain_data_io::gz_write_import_data(), gz_element_connect_io::gz_write_surface_4_element(), gzip_file_access::gz_write_textbuf_no_lf(), m_fem_surface_labels::hd_edge_connect(), m_fem_surface_labels::hd_edge_export(), m_fem_surface_labels::hd_edge_import(), m_fem_surface_labels::hd_edge_on_ele(), m_fem_surface_labels::hd_edge_on_surf(), m_fem_surface_labels::hd_edge_para(), and m_fem_mesh_labels::hd_fem_para().
Referenced by gz_element_file_io::gz_output_edge_file().
gz_write_edge_geometry()
subroutine gz_edge_data_io::gz_write_edge_geometry (type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 201 of file gz_edge_data_IO.f90.
References gz_node_geometry_io::gz_write_geometry_info(), gz_node_geometry_io::gz_write_scalar_in_element(), gzip_file_access::gz_write_textbuf_no_lf(), gz_node_geometry_io::gz_write_vector_in_element(), m_fem_surface_labels::hd_edge_dir(), m_fem_surface_labels::hd_edge_length(), and m_fem_surface_labels::hd_edge_point().