CALYPSO: set_psf_nodes_4_by_surf_grp Module Reference
set_psf_nodes_4_by_surf_grp Module Reference
Construct node data for secitoning using surface group.
Functions/Subroutines
subroutine count_node_at_node_on_grp (igrp, internal_node, num_surf, ntot_node_sf_grp, inod_stack_sf_grp, inod_surf_grp, psf_g_list)
subroutine count_position_4_psf_grp (psf_g_list, psf_node)
subroutine set_node_at_node_on_grp (igrp, internal_node, num_surf, ntot_node_sf_grp, inod_stack_sf_grp, inod_surf_grp, psf_g_list)
subroutine set_position_psf_grp (nnod, xx, istack_intnod, nnod_patch, inod_sum, xx_patch, psf_g_list)
subroutine set_field_on_psf_grp_xyz (nnod, nnod_patch, num_fld, ntot_comp, istack_comp_nod, d_nod, ifield_psf, ncomp, dat_tmp, psf_g_list)
subroutine set_position_at_nod_psf (nnod, xx, ishift, nnod_on_nod, istack_n_on_n_smp, inod_4_nod, istack_intnod, nnod_patch, inod_sum, xx_patch)
subroutine set_field_at_nod_psf (nnod, ncomp, d_nod, ishift, nnod_on_nod, istack_n_on_n_smp, inod_4_nod, nnod_patch, dat_tmp)
Detailed Description
Construct node data for secitoning using surface group.
      subroutine count_node_at_node_on_grp(igrp, internal_node,       &
     &          num_surf, ntot_node_sf_grp, inod_stack_sf_grp,        &
     &          inod_surf_grp,  psf_g_list)
      subroutine count_position_4_psf_grp(psf_g_list, psf_node)
      subroutine set_node_at_node_on_grp(igrp, internal_node,         &
     &          num_surf, ntot_node_sf_grp, inod_stack_sf_grp,        &
     &          inod_surf_grp, psf_g_list)
      subroutine set_position_psf_grp(nnod, xx, istack_intnod,        &
     &          nnod_patch, inod_sum, xx_patch, psf_list, psf_g_list)
      subroutine set_field_on_psf_grp_xyz(nnod, nnod_patch,           &
     &          num_fld, ntot_comp, istack_comp_nod,                  &
     &          d_nod, ifield_psf, ncomp, psf_g_list)
Function/Subroutine Documentation
count_node_at_node_on_grp()
subroutine set_psf_nodes_4_by_surf_grp::count_node_at_node_on_grp (integer(kind = kint), intent(in) igrp, integer(kind = kint), intent(in) internal_node, integer(kind = kint), intent(in) num_surf, integer(kind = kint), intent(in) ntot_node_sf_grp, integer(kind = kint), dimension(0:num_surf), intent(in) inod_stack_sf_grp, integer(kind = kint), dimension(ntot_node_sf_grp), intent(in) inod_surf_grp, type(grp_section_list), intent(inout) psf_g_list)
Definition at line 40 of file set_psf_nodes_4_by_surf_grp.f90.
References cal_minmax_and_stacks::count_number_4_smp(), m_constants::ione, and m_machine_parameter::np_smp.
Referenced by set_nodes_for_psf::count_nodes_4_psf().
count_position_4_psf_grp()
subroutine set_psf_nodes_4_by_surf_grp::count_position_4_psf_grp (type(grp_section_list), intent(in) psf_g_list, type(node_data), intent(inout) psf_node)
Definition at line 83 of file set_psf_nodes_4_by_surf_grp.f90.
References cal_minmax_and_stacks::count_number_4_smp(), m_constants::ione, and m_machine_parameter::np_smp.
Referenced by set_nodes_for_psf::count_nodes_4_psf().
set_field_at_nod_psf()
subroutine set_psf_nodes_4_by_surf_grp::set_field_at_nod_psf (integer(kind = kint), intent(in) nnod, integer(kind = kint), intent(in) ncomp, real(kind = kreal), dimension(nnod,ncomp), intent(in) d_nod, integer(kind = kint), intent(in) ishift, integer(kind = kint), intent(in) nnod_on_nod, integer(kind = kint), dimension(0:np_smp), intent(in) istack_n_on_n_smp, integer(kind = kint), dimension(nnod_on_nod), intent(in) inod_4_nod, integer(kind = kint), intent(in) nnod_patch, real(kind = kreal), dimension(nnod_patch,ncomp), intent(inout) dat_tmp)
Definition at line 261 of file set_psf_nodes_4_by_surf_grp.f90.
Referenced by set_field_on_psf_grp_xyz(), and set_position_at_nod_psf().
set_field_on_psf_grp_xyz()
subroutine set_psf_nodes_4_by_surf_grp::set_field_on_psf_grp_xyz (integer(kind = kint), intent(in) nnod, integer(kind = kint), intent(in) nnod_patch, integer(kind = kint), intent(in) num_fld, integer(kind = kint), intent(in) ntot_comp, integer(kind = kint), dimension(0:num_fld), intent(in) istack_comp_nod, real(kind = kreal), dimension(nnod,ntot_comp), intent(in) d_nod, integer(kind = kint), intent(in) ifield_psf, integer(kind = kint), intent(in) ncomp, real(kind = kreal), dimension(nnod_patch,6), intent(inout) dat_tmp, type(grp_section_list), intent(in) psf_g_list)
Definition at line 184 of file set_psf_nodes_4_by_surf_grp.f90.
References m_constants::izero, and set_field_at_nod_psf().
Referenced by set_fields_for_psf::set_field_on_psf_grp().
set_node_at_node_on_grp()
subroutine set_psf_nodes_4_by_surf_grp::set_node_at_node_on_grp (integer(kind = kint), intent(in) igrp, integer(kind = kint), intent(in) internal_node, integer(kind = kint), intent(in) num_surf, integer(kind = kint), intent(in) ntot_node_sf_grp, integer(kind = kint), dimension(0:num_surf), intent(in) inod_stack_sf_grp, integer(kind = kint), dimension(ntot_node_sf_grp), intent(in) inod_surf_grp, type(grp_section_list), intent(inout) psf_g_list)
Definition at line 106 of file set_psf_nodes_4_by_surf_grp.f90.
Referenced by set_nodes_for_psf::set_nodes_4_psf().
set_position_at_nod_psf()
subroutine set_psf_nodes_4_by_surf_grp::set_position_at_nod_psf (integer(kind = kint), intent(in) nnod, real(kind = kreal), dimension(nnod,3), intent(in) xx, integer(kind = kint), intent(in) ishift, integer(kind = kint), intent(in) nnod_on_nod, integer(kind = kint), dimension(0:np_smp), intent(in) istack_n_on_n_smp, integer(kind = kint), dimension(nnod_on_nod), intent(in) inod_4_nod, integer(kind = kint_gl), intent(in) istack_intnod, integer(kind = kint), intent(in) nnod_patch, integer(kind = kint_gl), dimension(nnod_patch), intent(inout) inod_sum, real(kind = kreal), dimension(nnod_patch,3), intent(inout) xx_patch)
Definition at line 224 of file set_psf_nodes_4_by_surf_grp.f90.
References m_constants::ithree, and set_field_at_nod_psf().
Referenced by set_position_psf_grp().
set_position_psf_grp()
subroutine set_psf_nodes_4_by_surf_grp::set_position_psf_grp (integer(kind = kint), intent(in) nnod, real(kind = kreal), dimension(nnod,3), intent(in) xx, integer(kind = kint_gl), intent(in) istack_intnod, integer(kind = kint), intent(in) nnod_patch, integer(kind = kint_gl), dimension(nnod_patch), intent(inout) inod_sum, real(kind = kreal), dimension(nnod_patch,3), intent(inout) xx_patch, type(grp_section_list), intent(in) psf_g_list)
Definition at line 147 of file set_psf_nodes_4_by_surf_grp.f90.
References m_constants::izero, and set_position_at_nod_psf().
Referenced by set_nodes_for_psf::set_nodes_4_psf().