CALYPSO: sph_poynting_flux_smp Module Reference
sph_poynting_flux_smp Module Reference
Evaluate poynting flux for nodal field
$omp parallel is required to use these routines.
Functions/Subroutines
subroutine copy_vectors_rtp_4_grad (sph, b_trns, fn_trns, trns_b_MHD, trns_f_ngSGS)
subroutine copy_vect_to_grad_vect_rtp (sph_rtp, ib_vect, if_grad_vx, if_grad_vy, if_grad_vz, ncomp_rj_2_rtp, ncomp_rtp_2_rj, fld_rtp, frc_rtp)
subroutine cal_grad_of_velocities_sph (sph_rj, r_2nd, sph_bc_U, g_sph_rj, ipol, rj_fld)
subroutine sel_scalar_from_trans (sph_rtp, v_rtp, d_sph)
subroutine, private copy_grad_vect_to_m_stretch (ipol, nnod, ntot_phys_rj, d_rj)
Detailed Description
Evaluate poynting flux for nodal field
$omp parallel is required to use these routines.
      subroutine copy_vectors_rtp_4_grad                              &
     &         (sph, b_trns, fn_trns, trns_b_MHD, trns_f_ngSGS)
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(fdm_matrices), intent(in) :: r_2nd
        type(sph_boundary_type), intent(in)  :: sph_bc_U
        type(phys_address), intent(in) :: ipol
        type(phys_data), intent(inout) :: rj_fld
      subroutine copy_vect_to_grad_vect_rtp                           &
     &         (sph_rtp, ib_vect, if_grad_vx, if_grad_vy, if_grad_vz, &
     &          ncomp_rj_2_rtp, ncomp_rtp_2_rj, fld_rtp, frc_rtp)
      subroutine sel_scalar_from_trans(sph_rtp, v_rtp, d_sph)
Function/Subroutine Documentation
cal_grad_of_velocities_sph()
subroutine sph_poynting_flux_smp::cal_grad_of_velocities_sph (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc_U, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld)
Definition at line 131 of file sph_poynting_flux_smp.f90.
References const_sph_radial_grad::const_sph_gradient_no_bc(), and copy_grad_vect_to_m_stretch().
Referenced by lead_fields_4_sph_mhd::gradients_of_vectors_sph().
copy_grad_vect_to_m_stretch()
subroutine, private sph_poynting_flux_smp::copy_grad_vect_to_m_stretch (type(phys_address), intent(in) ipol, integer(kind = kint), intent(in) nnod, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(nnod,ntot_phys_rj), intent(inout) d_rj) private
Definition at line 189 of file sph_poynting_flux_smp.f90.
Referenced by cal_grad_of_velocities_sph().
copy_vect_to_grad_vect_rtp()
subroutine sph_poynting_flux_smp::copy_vect_to_grad_vect_rtp (type(sph_rtp_grid), intent(in) sph_rtp, integer(kind = kint), intent(in) ib_vect, integer(kind = kint), intent(in) if_grad_vx, integer(kind = kint), intent(in) if_grad_vy, integer(kind = kint), intent(in) if_grad_vz, integer(kind = kint), intent(in) ncomp_rj_2_rtp, integer(kind = kint), intent(in) ncomp_rtp_2_rj, real(kind = kreal), dimension(sph_rtp%nnod_rtp,ncomp_rj_2_rtp), intent(in) fld_rtp, real(kind = kreal), dimension(sph_rtp%nnod_rtp,ncomp_rtp_2_rj), intent(inout) frc_rtp)
Definition at line 103 of file sph_poynting_flux_smp.f90.
References sel_scalar_from_trans().
Referenced by copy_vectors_rtp_4_grad().
copy_vectors_rtp_4_grad()
subroutine sph_poynting_flux_smp::copy_vectors_rtp_4_grad (type(sph_grids), intent(in) sph, type(phys_address), intent(in) b_trns, type(phys_address), intent(in) fn_trns, type(spherical_transform_data), intent(in) trns_b_MHD, type(spherical_transform_data), intent(inout) trns_f_ngSGS)
Definition at line 42 of file sph_poynting_flux_smp.f90.
References copy_vect_to_grad_vect_rtp().
Referenced by lead_fields_4_sph_mhd::gradients_of_vectors_sph().
sel_scalar_from_trans()
subroutine sph_poynting_flux_smp::sel_scalar_from_trans (type(sph_rtp_grid), intent(in) sph_rtp, real(kind = kreal), dimension(sph_rtp%nnod_rtp), intent(in) v_rtp, real(kind = kreal), dimension(sph_rtp%nnod_rtp), intent(inout) d_sph)
Definition at line 169 of file sph_poynting_flux_smp.f90.
References copy_field_4_sph_trans::copy_scalar_from_trans_smp().
Referenced by copy_vect_to_grad_vect_rtp().