CALYPSO: set_const_4_sections Module Reference
set_const_4_sections Module Reference
Functions/Subroutines
subroutine set_const_4_crossections (num_psf, psf_def, node, psf_list)
subroutine set_const_4_isosurfaces (num_iso, node, nod_fld, iso_def, iso_list)
subroutine, private set_constant_4_psf (nnod, istack_nod_smp, xx, const_psf, c_ref_psf)
subroutine, private set_constant_4_iso (iso_def, nnod, istack_nod_smp, xx, radius, a_r, s_radius, a_s, num_fld, ntot_comp, istack_comp_nod, d_nod, c_ref_iso)
Function/Subroutine Documentation
set_const_4_crossections()
subroutine set_const_4_sections::set_const_4_crossections (integer(kind = kint), intent(in) num_psf, type(section_define), dimension(num_psf), intent(in) psf_def, type(node_data), intent(in) node, type(sectioning_list), dimension(num_psf), intent(inout) psf_list)
Definition at line 35 of file set_const_4_sections.f90.
References set_constant_4_psf().
Referenced by t_cross_section::sectioning_initialize().
set_const_4_isosurfaces()
subroutine set_const_4_sections::set_const_4_isosurfaces (integer(kind = kint), intent(in) num_iso, type(node_data), intent(in) node, type(phys_data), intent(in) nod_fld, type(isosurface_define), dimension(num_iso), intent(in) iso_def, type(sectioning_list), dimension(num_iso), intent(inout) iso_list)
Definition at line 63 of file set_const_4_sections.f90.
References set_constant_4_iso().
Referenced by t_isosurface::isosurf_visualize().
set_constant_4_iso()
subroutine, private set_const_4_sections::set_constant_4_iso (type(isosurface_define), intent(in) iso_def, integer(kind = kint), intent(in) nnod, integer(kind = kint), dimension(0:np_smp), intent(in) istack_nod_smp, real(kind = kreal), dimension(nnod,3), intent(in) xx, real(kind = kreal), dimension(nnod), intent(in) radius, real(kind = kreal), dimension(nnod), intent(in) a_r, real(kind = kreal), dimension(nnod), intent(in) s_radius, real(kind = kreal), dimension(nnod), intent(in) a_s, integer(kind = kint), intent(in) num_fld, integer(kind = kint), intent(in) ntot_comp, integer(kind = kint), dimension(0:num_fld), intent(in) istack_comp_nod, real(kind = kreal), dimension(nnod,ntot_comp), intent(in) d_nod, real(kind = kreal), dimension(nnod), intent(inout) c_ref_iso) private
Definition at line 131 of file set_const_4_sections.f90.
References cvt_xyz_vector_2_cyl_smp::cal_cylinder_r_comp_smp(), cvt_xyz_vector_2_sph_smp::cal_phi_comp_smp(), cvt_xyz_vector_2_sph_smp::cal_radial_comp_smp(), mag_of_field_smp::cal_sym_tensor_magnitude(), cvt_xyz_vector_2_sph_smp::cal_theta_comp_smp(), mag_of_field_smp::cal_vector_magnitude(), copy_field_smp::copy_nod_scalar_smp(), m_machine_parameter::np_smp, and cal_subtract_smp::subtruct_const_4_scalar_smp_ow().
Referenced by set_const_4_isosurfaces().
set_constant_4_psf()
subroutine, private set_const_4_sections::set_constant_4_psf (integer(kind = kint), intent(in) nnod, integer(kind = kint), dimension(0:np_smp), intent(in) istack_nod_smp, real(kind = kreal), dimension(nnod,3), intent(in) xx, real(kind = kreal), dimension(10), intent(in) const_psf, real(kind = kreal), dimension(nnod), intent(inout) c_ref_psf) private
Definition at line 94 of file set_const_4_sections.f90.
References m_machine_parameter::np_smp.
Referenced by set_const_4_crossections().