CALYPSO: calypso_sr_int Module Reference
calypso_sr_int Module Reference
Integer data communication.
Functions/Subroutines
subroutine calypso_send_recv_int (iflag_recv, nnod_org, nnod_new, npe_send, isend_self, id_pe_send, istack_send, inod_export, npe_recv, irecv_self, id_pe_recv, istack_recv, inod_import, irev_import, SR_sig, SR_i, iX_org, iX_new)
subroutine calypso_send_recv_int8 (iflag_recv, nnod_org, nnod_new, npe_send, isend_self, id_pe_send, istack_send, inod_export, npe_recv, irecv_self, id_pe_recv, istack_recv, inod_import, irev_import, SR_sig, SR_il, i8X_org, i8X_new)
Detailed Description
Integer data communication.
      subroutine calypso_send_recv_int                                &
     &                      (iflag_recv, nnod_org, nnod_new,          &
     &                       npe_send, isend_self,                    &
     &                       id_pe_send, istack_send, inod_export,    &
     &                       npe_recv, irecv_self,                    &
     &                       id_pe_recv, istack_recv, inod_import,    &
     &                       irev_import, SR_sig, SR_i,               &
     &                       iX_org, iX_new)
      subroutine calypso_send_recv_int8                               &
     &                      (iflag_recv, nnod_org, nnod_new,          &
     &                       npe_send, isend_self,                    &
     &                       id_pe_send, istack_send, inod_export,    &
     &                       npe_recv, irecv_self,                    &
     &                       id_pe_recv, istack_recv, inod_import,    &
     &                       irev_import, SR_sig, SR_il,              &
     &                       i8X_org, i8X_new)
        type(send_recv_status), intent(inout) :: SR_sig
        type(send_recv_int_buffer), intent(inout) :: SR_i
        type(send_recv_int8_buffer), intent(inout) :: SR_il
Parameters
nnod_org Number of data points for origin
nnod_new Number of components for destination
Parameters
npe_send Number of processses to send
isend_self Integer flag to copy within own process
id_pe_send(npe_send) Process ID to send
istack_send(0:npe_send) End points of send buffer for each process
inod_export(istack_send(npe_send)) local node ID to copy in send buffer
irev_import(nnod_new) import buffer ID for each data point
Parameters
npe_recv Number of processses to receive
irecv_self Integer flag to copy within own process
id_pe_recv(npe_send) Process ID to receive
istack_recv(0:npe_send) End points of receive buffer for each process
inod_import(istack_recv(npe_recv)) local node ID to copy from receive buffer
Parameters
iX_org(nnod_org) Send data
iX_new(nnod_new) Received data
Function/Subroutine Documentation
calypso_send_recv_int()
subroutine calypso_sr_int::calypso_send_recv_int (integer(kind = kint), intent(in) iflag_recv, integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) npe_send, integer(kind = kint), intent(in) isend_self, integer(kind = kint), dimension(npe_send), intent(in) id_pe_send, integer(kind = kint), dimension(0:npe_send), intent(in) istack_send, integer(kind = kint), dimension(istack_send(npe_send)), intent(in) inod_export, integer(kind = kint), intent(in) npe_recv, integer(kind = kint), intent(in) irecv_self, integer(kind = kint), dimension(npe_recv), intent(in) id_pe_recv, integer(kind = kint), dimension(0:npe_recv), intent(in) istack_recv, integer(kind = kint), dimension(istack_recv(npe_recv)), intent(in) inod_import, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, type(send_recv_status), intent(inout) SR_sig, type(send_recv_int_buffer), intent(inout) SR_i, integer (kind=kint), dimension(nnod_org), intent(in) iX_org, integer (kind=kint), dimension(nnod_new), intent(inout) iX_new)
Parameters
[in,out] sr_sig Structure of communication flags
[in,out] sr_i Structure of communication buffer for 4-byte integer
Definition at line 69 of file calypso_SR_int.f90.
References t_solver_sr::calypso_send_recv_fin(), solver_sr_int::calypso_send_recv_intcore(), t_solver_sr_int::resize_iwork_sr_t(), select_copy_from_recv::sel_cppy_from_recv_buf_int(), and set_to_send_buffer::set_to_send_buf_int().
Referenced by spherical_srs_n::send_recv_sph_trans_int().
calypso_send_recv_int8()
subroutine calypso_sr_int::calypso_send_recv_int8 (integer(kind = kint), intent(in) iflag_recv, integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) npe_send, integer(kind = kint), intent(in) isend_self, integer(kind = kint), dimension(npe_send), intent(in) id_pe_send, integer(kind = kint), dimension(0:npe_send), intent(in) istack_send, integer(kind = kint), dimension(istack_send(npe_send)), intent(in) inod_export, integer(kind = kint), intent(in) npe_recv, integer(kind = kint), intent(in) irecv_self, integer(kind = kint), dimension(npe_recv), intent(in) id_pe_recv, integer(kind = kint), dimension(0:npe_recv), intent(in) istack_recv, integer(kind = kint), dimension(istack_recv(npe_recv)), intent(in) inod_import, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, type(send_recv_status), intent(inout) SR_sig, type(send_recv_int8_buffer), intent(inout) SR_il, integer(kind = kint_gl), dimension(nnod_org), intent(in) i8X_org, integer(kind = kint_gl), dimension(nnod_new), intent(inout) i8X_new)
Parameters
[in,out] sr_sig Structure of communication flags
[in,out] sr_il Structure of communication buffer for 8-byte integer
Definition at line 135 of file calypso_SR_int.f90.
References t_solver_sr::calypso_send_recv_fin(), solver_sr_int8::calypso_send_recv_i8core(), t_solver_sr_int8::resize_i8work_sr(), select_copy_from_recv::sel_cppy_from_recv_buf_i8(), and set_to_send_buffer::set_to_send_buf_i8().