CALYPSO: t_field_data_io Module Reference
t_field_data_io Module Reference
Structure for field data IO.
Data Types
type field_io
Structure for field data IO.
type multi_field_io
Structure for field data IO for multiple domains.
Functions/Subroutines
subroutine alloc_multi_field_data_io (nloop, mul_f)
subroutine dealloc_multi_field_data_io (mul_f)
subroutine alloc_phys_name_io (fld_IO)
subroutine append_phys_name_io (field_name, num_component, fld_IO)
subroutine alloc_phys_data_io (fld_IO)
subroutine alloc_merged_field_stack (num_pe, fld_IO)
subroutine dealloc_phys_io (fld_IO)
subroutine dealloc_phys_name_io (fld_IO)
subroutine dealloc_phys_data_io (fld_IO)
subroutine dealloc_merged_field_stack (fld_IO)
subroutine cal_istack_phys_comp_io (fld_IO)
subroutine copy_phys_name_io (num, org_fld_IO, new_fld_IO)
subroutine check_field_name_4_io (id_field, fld_IO)
Variables
integer(kind=kint), parameter id_phys_file = 15
file ID for field data IO
Detailed Description
Structure for field data IO.
      subroutine alloc_multi_field_data_IO(nloop, mul_f)
      subroutine dealloc_multi_field_data_IO(mul_f)
        type(multi_field_IO), intent(inout) :: mul_f
      subroutine alloc_phys_name_IO(fld_IO)
      subroutine append_phys_name_IO                                  &
     &         (field_name, num_component, fld_IO)
      subroutine alloc_phys_data_IO(fld_IO)
      subroutine alloc_merged_field_stack(num_pe, fld_IO)
        type(field_IO), intent(inout) :: fld_IO
      subroutine dealloc_phys_IO(fld_IO)
      subroutine dealloc_phys_name_IO(fld_IO)
      subroutine dealloc_phys_data_IO(fld_IO)
      subroutine dealloc_merged_field_stack(fld_IO)
      subroutine cal_istack_phys_comp_IO(fld_IO)
      subroutine copy_phys_name_IO(num, org_fld_IO, new_fld_IO)
        type(field_IO), intent(in) :: org_fld_IO
        type(field_IO), intent(inout) :: new_fld_IO
      subroutine check_field_name_4_IO(id_field, fld_IO)
        type(field_IO), intent(in) :: fld_IO
Function/Subroutine Documentation
alloc_merged_field_stack()
subroutine t_field_data_io::alloc_merged_field_stack (integer, intent(in) num_pe, type(field_io), intent(inout) fld_IO)
Definition at line 172 of file t_field_data_IO.f90.
Referenced by gz_field_file_mpi_io_b::gz_rd_alloc_st_fld_file_mpi_b(), gz_field_file_mpi_io_b::gz_rd_alloc_st_fld_head_mpi_b(), gz_field_file_mpi_io_b::gz_read_step_field_file_mpi_b(), sph_mhd_rst_io_control::output_spectr_4_snap(), field_file_mpi_io::read_alloc_step_fld_file_mpi(), field_file_mpi_io::read_alloc_step_fld_head_mpi(), gz_field_file_mpi_io::read_alloc_stp_fld_file_gz_mpi(), field_file_mpi_io_b::read_alloc_stp_fld_file_mpi_b(), gz_field_file_mpi_io::read_alloc_stp_fld_head_gz_mpi(), field_file_mpi_io_b::read_alloc_stp_fld_head_mpi_b(), field_file_mpi_io::read_step_field_file_mpi(), field_file_mpi_io_b::read_step_field_file_mpi_b(), count_nnod_4_asseble_sph::s_count_nnod_4_asseble_sph(), and set_sph_restart_io::set_sph_restart_num_to_io().
alloc_multi_field_data_io()
subroutine t_field_data_io::alloc_multi_field_data_io (integer(kind = kint), intent(in) nloop, type(multi_field_io), intent(inout) mul_f)
Definition at line 89 of file t_field_data_IO.f90.
alloc_phys_data_io()
subroutine t_field_data_io::alloc_phys_data_io (type(field_io), intent(inout) fld_IO)
Definition at line 160 of file t_field_data_IO.f90.
Referenced by new_sph_restart::const_assembled_sph_data(), gz_field_file_io_b::gz_rd_alloc_st_fld_file_b(), gz_field_file_mpi_io_b::gz_rd_alloc_st_fld_file_mpi_b(), rayleigh_restart_io::init_rayleigh_restart_input(), sph_mhd_rst_io_control::output_spectr_4_snap(), gz_field_file_io::read_alloc_gz_field_file(), gz_field_file_io::read_alloc_gz_step_field_file(), field_file_mpi_io::read_alloc_step_fld_file_mpi(), gz_field_file_mpi_io::read_alloc_stp_fld_file_gz_mpi(), field_file_mpi_io_b::read_alloc_stp_fld_file_mpi_b(), gz_field_file_mpi_io::read_alloc_stp_fld_head_gz_mpi(), field_file_io::read_and_alloc_step_field(), field_file_io::read_and_allocate_field_file(), field_file_io_b::read_and_allocate_step_field_b(), set_sph_restart_io::set_sph_restart_num_to_io(), and share_field_data::share_each_field_io_data().
alloc_phys_name_io()
subroutine t_field_data_io::alloc_phys_name_io (type(field_io), intent(inout) fld_IO)
Definition at line 112 of file t_field_data_IO.f90.
Referenced by append_phys_name_io(), copy_rj_phys_data_4_io::copy_rj_phys_name_to_io(), gz_field_file_io_b::gz_rd_alloc_st_fld_file_b(), gz_field_file_mpi_io_b::gz_rd_alloc_st_fld_file_mpi_b(), gz_field_file_io_b::gz_rd_alloc_st_fld_head_b(), gz_field_file_mpi_io_b::gz_rd_alloc_st_fld_head_mpi_b(), rayleigh_restart_io::init_rayleigh_restart_input(), gz_field_file_io::read_alloc_gz_field_file(), gz_field_file_io::read_alloc_gz_step_field_file(), gz_field_file_io::read_alloc_gz_step_field_head(), field_file_mpi_io::read_alloc_step_fld_file_mpi(), field_file_mpi_io::read_alloc_step_fld_head_mpi(), gz_field_file_mpi_io::read_alloc_stp_fld_file_gz_mpi(), field_file_mpi_io_b::read_alloc_stp_fld_file_mpi_b(), gz_field_file_mpi_io::read_alloc_stp_fld_head_gz_mpi(), field_file_mpi_io_b::read_alloc_stp_fld_head_mpi_b(), field_file_io::read_and_alloc_step_field(), field_file_io::read_and_allocate_field_file(), field_file_io_b::read_and_allocate_step_b(), field_file_io::read_and_allocate_step_head(), gz_rst_data_io_by_fld::read_gz_rst_comps(), rst_data_io_by_fld::read_rst_data_comps(), rayleigh_restart_io::set_rayleigh_restart_field(), set_sph_restart_io::set_sph_restart_num_to_io(), and share_field_data::share_field_io_names().
append_phys_name_io()
subroutine t_field_data_io::append_phys_name_io (character(len = kchara), intent(in) field_name, integer(kind = kint), intent(in) num_component, type(field_io), intent(inout) fld_IO)
Definition at line 127 of file t_field_data_IO.f90.
References alloc_phys_name_io(), copy_phys_name_io(), and dealloc_phys_name_io().
Referenced by rayleigh_restart_io::set_rayleigh_restart_field().
cal_istack_phys_comp_io()
subroutine t_field_data_io::cal_istack_phys_comp_io (type(field_io), intent(inout) fld_IO)
Definition at line 238 of file t_field_data_IO.f90.
Referenced by gz_field_file_io_b::gz_rd_alloc_st_fld_file_b(), gz_field_file_mpi_io_b::gz_rd_alloc_st_fld_file_mpi_b(), gz_field_file_io_b::gz_rd_alloc_st_fld_head_b(), gz_field_file_mpi_io_b::gz_rd_alloc_st_fld_head_mpi_b(), gz_field_file_mpi_io_b::gz_read_step_field_file_mpi_b(), rayleigh_restart_io::init_rayleigh_restart_input(), gz_field_file_io::read_alloc_gz_field_file(), gz_field_file_io::read_alloc_gz_step_field_file(), gz_field_file_io::read_alloc_gz_step_field_head(), field_file_mpi_io::read_alloc_step_fld_file_mpi(), field_file_mpi_io::read_alloc_step_fld_head_mpi(), gz_field_file_mpi_io::read_alloc_stp_fld_file_gz_mpi(), field_file_mpi_io_b::read_alloc_stp_fld_file_mpi_b(), gz_field_file_mpi_io::read_alloc_stp_fld_head_gz_mpi(), field_file_mpi_io_b::read_alloc_stp_fld_head_mpi_b(), field_file_io::read_and_alloc_step_field(), field_file_io::read_and_allocate_field_file(), field_file_io_b::read_and_allocate_step_b(), field_file_io::read_and_allocate_step_head(), gz_rst_data_io_by_fld::read_gz_rst_comps(), and rst_data_io_by_fld::read_rst_data_comps().
check_field_name_4_io()
subroutine t_field_data_io::check_field_name_4_io (integer(kind = kint), intent(in) id_field, type(field_io), intent(in) fld_IO)
Definition at line 278 of file t_field_data_IO.f90.
copy_phys_name_io()
subroutine t_field_data_io::copy_phys_name_io (integer(kind = kint), intent(in) num, type(field_io), intent(in) org_fld_IO, type(field_io), intent(inout) new_fld_IO)
Definition at line 256 of file t_field_data_IO.f90.
Referenced by append_phys_name_io().
dealloc_merged_field_stack()
subroutine t_field_data_io::dealloc_merged_field_stack (type(field_io), intent(inout) fld_IO)
Definition at line 225 of file t_field_data_IO.f90.
Referenced by dealloc_phys_io(), gz_field_file_mpi_io_b::gz_rd_alloc_st_fld_file_mpi_b(), gz_field_file_mpi_io_b::gz_rd_alloc_st_fld_head_mpi_b(), gz_field_file_mpi_io_b::gz_read_step_field_file_mpi_b(), analyzer_compare_sph_rst::init_compare_sph_restart(), sph_mhd_rst_io_control::output_spectr_4_snap(), field_file_mpi_io::read_alloc_step_fld_file_mpi(), field_file_mpi_io::read_alloc_step_fld_head_mpi(), gz_field_file_mpi_io::read_alloc_stp_fld_file_gz_mpi(), field_file_mpi_io_b::read_alloc_stp_fld_file_mpi_b(), gz_field_file_mpi_io::read_alloc_stp_fld_head_gz_mpi(), field_file_mpi_io_b::read_alloc_stp_fld_head_mpi_b(), gz_field_file_mpi_io::read_step_field_file_gz_mpi(), field_file_mpi_io::read_step_field_file_mpi(), and field_file_mpi_io_b::read_step_field_file_mpi_b().
dealloc_multi_field_data_io()
subroutine t_field_data_io::dealloc_multi_field_data_io (type(multi_field_io), intent(inout) mul_f)
Definition at line 101 of file t_field_data_IO.f90.
dealloc_phys_data_io()
subroutine t_field_data_io::dealloc_phys_data_io (type(field_io), intent(inout) fld_IO)
Definition at line 214 of file t_field_data_IO.f90.
Referenced by analyzer_assemble_sph::analyze_assemble_sph(), analyzer_compare_sph_rst::analyze_compare_sph_restart(), analyzer_rayleigh_cvt_sph::analyze_cvt_rayleigh_sph(), dealloc_phys_io(), gz_field_file_mpi_io_b::gz_rd_alloc_st_fld_file_mpi_b(), new_sph_restart::load_old_fmt_sph_data(), new_sph_restart::load_org_sph_data(), sph_mhd_rst_io_control::output_spectr_4_snap(), sph_mhd_rst_io_control::read_alloc_sph_restart_data(), sph_mhd_rst_io_control::read_alloc_sph_rst_4_snap(), sph_mhd_rst_io_control::read_alloc_sph_spectr(), field_file_mpi_io::read_alloc_step_fld_file_mpi(), gz_field_file_mpi_io::read_alloc_stp_fld_file_gz_mpi(), and field_file_mpi_io_b::read_alloc_stp_fld_file_mpi_b().
dealloc_phys_io()
subroutine t_field_data_io::dealloc_phys_io (type(field_io), intent(inout) fld_IO)
Definition at line 186 of file t_field_data_IO.f90.
References dealloc_merged_field_stack(), dealloc_phys_data_io(), and dealloc_phys_name_io().
dealloc_phys_name_io()
subroutine t_field_data_io::dealloc_phys_name_io (type(field_io), intent(inout) fld_IO)
Definition at line 199 of file t_field_data_IO.f90.
Referenced by analyzer_assemble_sph::analyze_assemble_sph(), analyzer_compare_sph_rst::analyze_compare_sph_restart(), analyzer_rayleigh_cvt_sph::analyze_cvt_rayleigh_sph(), append_phys_name_io(), dealloc_phys_io(), gz_field_file_mpi_io_b::gz_rd_alloc_st_fld_file_mpi_b(), gz_field_file_mpi_io_b::gz_rd_alloc_st_fld_head_mpi_b(), new_sph_restart::load_field_name_assemble_sph(), new_sph_restart::load_old_fmt_sph_data(), new_sph_restart::load_org_sph_data(), sph_mhd_rst_io_control::output_spectr_4_snap(), sph_mhd_rst_io_control::read_alloc_sph_restart_data(), sph_mhd_rst_io_control::read_alloc_sph_rst_4_snap(), sph_mhd_rst_io_control::read_alloc_sph_spectr(), field_file_mpi_io::read_alloc_step_fld_file_mpi(), field_file_mpi_io::read_alloc_step_fld_head_mpi(), gz_field_file_mpi_io::read_alloc_stp_fld_file_gz_mpi(), field_file_mpi_io_b::read_alloc_stp_fld_file_mpi_b(), gz_field_file_mpi_io::read_alloc_stp_fld_head_gz_mpi(), and field_file_mpi_io_b::read_alloc_stp_fld_head_mpi_b().
Variable Documentation
id_phys_file
integer(kind = kint), parameter t_field_data_io::id_phys_file = 15
file ID for field data IO
Definition at line 44 of file t_field_data_IO.f90.
Referenced by field_file_io::read_and_alloc_step_field(), field_file_io::read_and_allocate_field_file(), field_file_io::read_and_allocate_step_head(), rst_data_io_by_fld::read_rst_data_comps(), rst_data_io_by_fld::read_rst_field_comps(), rst_data_io_by_fld::read_rst_file(), field_file_io::read_step_field_file(), and field_file_io::write_step_field_file().