CALYPSO: t_geometry_data Module Reference
t_geometry_data Module Reference
structure of geometry data for FEM mesh including node and element position, connectivities
Data Types
type element_data
structure for element data (position and connectivity)
type node_data
structure for node data (position)
Functions/Subroutines
subroutine alloc_numnod_stack (num_pe, node)
subroutine alloc_numele_stack (num_pe, ele)
subroutine alloc_node_geometry_w_sph (node)
subroutine alloc_node_geometry_base (node)
subroutine alloc_sph_node_geometry (node)
subroutine allocate_ele_connect_type (ele)
subroutine alloc_element_types (ele)
subroutine alloc_ele_connectivity (ele)
subroutine alloc_overlaped_ele (ele)
subroutine alloc_ele_geometry (ele)
subroutine allocate_node_param_smp_type (node)
subroutine allocate_ele_param_smp_type (ele)
subroutine dealloc_numnod_stack (node)
subroutine dealloc_numele_stack (ele)
subroutine dealloc_node_geometry_w_sph (node)
subroutine dealloc_node_geometry_base (node)
subroutine deallocate_sph_node_geometry (node)
subroutine deallocate_ele_connect_type (ele)
subroutine dealloc_overlaped_ele (ele)
subroutine deallocate_ele_geometry_type (ele)
subroutine deallocate_node_param_smp_type (node)
subroutine deallocate_ele_param_smp_type (ele)
subroutine check_nod_size_smp_type (node, id_rank)
subroutine check_ele_size_smp_type (ele, id_rank)
Detailed Description
structure of geometry data for FEM mesh including node and element position, connectivities
      subroutine alloc_numnod_stack(num_pe, node)
      subroutine alloc_numele_stack(num_pe, ele)
      subroutine alloc_node_geometry_w_sph(node)
      subroutine alloc_node_geometry_base(node)
      subroutine alloc_sph_node_geometry(node)
      subroutine allocate_ele_connect_type(ele)
      subroutine alloc_element_types(ele)
      subroutine alloc_ele_connectivity(ele)
      subroutine alloc_overlaped_ele(ele)
      subroutine alloc_ele_geometry(ele)
      subroutine allocate_node_param_smp_type(node)
      subroutine allocate_ele_param_smp_type(ele)
        type(element_data), intent(inout) :: ele
      subroutine dealloc_numnod_stack(node)
      subroutine dealloc_numele_stack(ele)
      subroutine dealloc_node_geometry_w_sph(node)
      subroutine dealloc_node_geometry_base(node)
      subroutine deallocate_sph_node_geometry(node)
      subroutine deallocate_ele_connect_type(ele)
      subroutine dealloc_overlaped_ele(ele)
      subroutine deallocate_ele_geometry_type(ele)
      subroutine deallocate_node_param_smp_type(node)
      subroutine deallocate_ele_param_smp_type(ele)
        type(element_data), intent(inout) :: ele
      subroutine check_nod_size_smp_type(node, id_rank)
      subroutine check_ele_size_smp_type(ele, id_rank)
Function/Subroutine Documentation
alloc_ele_connectivity()
subroutine t_geometry_data::alloc_ele_connectivity (type(element_data), intent(inout) ele)
Definition at line 281 of file t_geometry_data.f90.
Referenced by allocate_ele_connect_type(), gz_mpi_element_connect_io_b::gz_mpi_read_ele_info_b(), gz_mpi_element_connect_io::gz_mpi_read_element_info(), gz_element_connect_io::gz_read_element_info(), gz_element_connect_io_b::gz_read_element_info_b(), mpi_element_connect_io::mpi_read_element_info(), mpi_element_connect_io_b::mpi_read_element_info_b(), element_connect_io::read_element_info(), and element_connect_io_b::read_element_info_b().
alloc_ele_geometry()
subroutine t_geometry_data::alloc_ele_geometry (type(element_data), intent(inout) ele)
Definition at line 305 of file t_geometry_data.f90.
References alloc_overlaped_ele().
Referenced by set_element_data_4_io::copy_ele_geometry_from_io(), const_mesh_information::empty_nod_and_ele_type_infos(), and const_mesh_information::set_nod_and_ele_infos().
alloc_element_types()
subroutine t_geometry_data::alloc_element_types (type(element_data), intent(inout) ele)
Definition at line 263 of file t_geometry_data.f90.
Referenced by allocate_ele_connect_type(), gz_mpi_element_connect_io_b::gz_mpi_read_ele_info_b(), gz_mpi_element_connect_io::gz_mpi_read_element_info(), gz_element_connect_io::gz_read_element_info(), gz_element_connect_io_b::gz_read_element_info_b(), mpi_element_connect_io::mpi_read_element_info(), mpi_element_connect_io_b::mpi_read_element_info_b(), element_connect_io::read_element_info(), and element_connect_io_b::read_element_info_b().
alloc_node_geometry_base()
subroutine t_geometry_data::alloc_node_geometry_base (type(node_data), intent(inout) node)
Definition at line 212 of file t_geometry_data.f90.
Referenced by alloc_node_geometry_w_sph(), set_edge_data_4_io::copy_edge_geometry_to_io(), set_element_data_4_io::copy_ele_cyl_geom_to_io(), set_element_data_4_io::copy_ele_geometry_to_io(), set_element_data_4_io::copy_ele_sph_geom_to_io(), copy_mesh_structures::copy_node_cyl_to_xx(), copy_mesh_structures::copy_node_geometry_types(), copy_mesh_structures::copy_node_sph_to_xx(), set_surface_data_4_io::copy_surf_geometry_to_io(), gz_mpi_node_geometry_io::gz_mpi_read_geometry_info(), gz_mpi_node_geometry_io_b::gz_mpi_read_geometry_info_b(), gz_node_geometry_io::gz_read_geometry_info(), gz_node_geometry_io_b::gz_read_geometry_info_b(), mpi_node_geometry_io::mpi_read_geometry_info(), mpi_node_geometry_io_b::mpi_read_geometry_info_b(), node_geometry_io::read_geometry_info(), and node_geometry_io_b::read_geometry_info_b().
alloc_node_geometry_w_sph()
subroutine t_geometry_data::alloc_node_geometry_w_sph (type(node_data), intent(inout) node)
Definition at line 201 of file t_geometry_data.f90.
References alloc_node_geometry_base(), and alloc_sph_node_geometry().
Referenced by set_fem_mesh_4_sph::const_fem_geometry_for_sph(), set_nodes_for_psf::set_nodes_4_iso(), load_mesh_data::set_zero_mesh_data(), and load_mesh_data::set_zero_node_data().
alloc_numele_stack()
subroutine t_geometry_data::alloc_numele_stack (integer, intent(in) num_pe, type(element_data), intent(inout) ele)
Definition at line 186 of file t_geometry_data.f90.
Referenced by const_element_comm_tables::const_global_numele_list().
alloc_numnod_stack()
subroutine t_geometry_data::alloc_numnod_stack (integer, intent(in) num_pe, type(node_data), intent(inout) node)
Definition at line 171 of file t_geometry_data.f90.
Referenced by const_element_comm_tables::const_global_numnod_list().
alloc_overlaped_ele()
subroutine t_geometry_data::alloc_overlaped_ele (type(element_data), intent(inout) ele)
Definition at line 293 of file t_geometry_data.f90.
Referenced by alloc_ele_geometry().
alloc_sph_node_geometry()
subroutine t_geometry_data::alloc_sph_node_geometry (type(node_data), intent(inout) node)
Definition at line 228 of file t_geometry_data.f90.
Referenced by alloc_node_geometry_w_sph(), load_mesh_data::input_mesh(), copy_mesh_structures::set_mesh_data_from_type(), and load_mesh_data::set_mesh_geometry_data().
allocate_ele_connect_type()
subroutine t_geometry_data::allocate_ele_connect_type (type(element_data), intent(inout) ele)
Definition at line 252 of file t_geometry_data.f90.
References alloc_ele_connectivity(), and alloc_element_types().
Referenced by set_fem_mesh_4_sph::const_fem_geometry_for_sph(), set_edge_data_4_io::copy_edge_connect_to_io(), set_element_data_4_io::copy_ele_connect_from_io(), set_element_data_4_io::copy_ele_connect_to_io(), copy_mesh_structures::copy_element_connect_types(), set_surface_data_4_io::copy_surf_connect_to_io(), set_patches_for_psf::set_iso_patches(), set_patches_for_psf::set_psf_patches(), and load_mesh_data::set_zero_mesh_data().
allocate_ele_param_smp_type()
subroutine t_geometry_data::allocate_ele_param_smp_type (type(element_data), intent(inout) ele)
Definition at line 357 of file t_geometry_data.f90.
References m_machine_parameter::np_smp.
Referenced by set_size_4_smp_types::count_ele_4_smp_mesh_type(), and const_mesh_information::empty_nod_and_ele_type_infos().
allocate_node_param_smp_type()
subroutine t_geometry_data::allocate_node_param_smp_type (type(node_data), intent(inout) node)
Definition at line 341 of file t_geometry_data.f90.
References m_machine_parameter::np_smp.
Referenced by set_size_4_smp_types::count_node_4_smp_mesh_type(), and const_mesh_information::empty_nod_and_ele_type_infos().
check_ele_size_smp_type()
subroutine t_geometry_data::check_ele_size_smp_type (type(element_data), intent(in) ele, integer, intent(in) id_rank)
Definition at line 509 of file t_geometry_data.f90.
References m_machine_parameter::np_smp.
check_nod_size_smp_type()
subroutine t_geometry_data::check_nod_size_smp_type (type(node_data), intent(in) node, integer, intent(in) id_rank)
Definition at line 492 of file t_geometry_data.f90.
References m_machine_parameter::np_smp.
dealloc_node_geometry_base()
subroutine t_geometry_data::dealloc_node_geometry_base (type(node_data), intent(inout) node)
Definition at line 404 of file t_geometry_data.f90.
Referenced by t_read_mesh_data::dealloc_ele_geometry_data(), t_mesh_data::dealloc_mesh_geometry_base(), t_mesh_data::dealloc_node_geometry_io(), dealloc_node_geometry_w_sph(), and t_read_mesh_data::dealloc_surf_geometry_data().
dealloc_node_geometry_w_sph()
subroutine t_geometry_data::dealloc_node_geometry_w_sph (type(node_data), intent(inout) node)
Definition at line 393 of file t_geometry_data.f90.
References dealloc_node_geometry_base(), and deallocate_sph_node_geometry().
Referenced by t_mesh_data::dealloc_mesh_type().
dealloc_numele_stack()
subroutine t_geometry_data::dealloc_numele_stack (type(element_data), intent(inout) ele)
Definition at line 382 of file t_geometry_data.f90.
Referenced by const_element_comm_tables::dealloc_ele_comm_tbls_gl_nele().
dealloc_numnod_stack()
subroutine t_geometry_data::dealloc_numnod_stack (type(node_data), intent(inout) node)
Definition at line 371 of file t_geometry_data.f90.
Referenced by const_element_comm_tables::dealloc_ele_comm_tbls_gl_nele().
dealloc_overlaped_ele()
subroutine t_geometry_data::dealloc_overlaped_ele (type(element_data), intent(inout) ele)
Definition at line 437 of file t_geometry_data.f90.
Referenced by deallocate_ele_geometry_type().
deallocate_ele_connect_type()
subroutine t_geometry_data::deallocate_ele_connect_type (type(element_data), intent(inout) ele)
Definition at line 425 of file t_geometry_data.f90.
Referenced by set_element_data_4_io::copy_ele_connect_from_io(), t_read_mesh_data::dealloc_edge_mesh_io(), t_mesh_data::dealloc_mesh_geometry_base(), t_mesh_data::dealloc_mesh_type(), and t_read_mesh_data::dealloc_surface_mesh_io().
deallocate_ele_geometry_type()
subroutine t_geometry_data::deallocate_ele_geometry_type (type(element_data), intent(inout) ele)
Definition at line 448 of file t_geometry_data.f90.
References dealloc_overlaped_ele().
Referenced by t_mesh_data::dealloc_nod_ele_infos().
deallocate_ele_param_smp_type()
subroutine t_geometry_data::deallocate_ele_param_smp_type (type(element_data), intent(inout) ele)
Definition at line 481 of file t_geometry_data.f90.
Referenced by t_mesh_data::dealloc_nod_ele_infos().
deallocate_node_param_smp_type()
subroutine t_geometry_data::deallocate_node_param_smp_type (type(node_data), intent(inout) node)
Definition at line 470 of file t_geometry_data.f90.
Referenced by t_mesh_data::dealloc_nod_ele_infos().
deallocate_sph_node_geometry()
subroutine t_geometry_data::deallocate_sph_node_geometry (type(node_data), intent(inout) node)
Definition at line 414 of file t_geometry_data.f90.
Referenced by dealloc_node_geometry_w_sph().