CALYPSO: mpi_domain_data_io Module Reference
mpi_domain_data_io Module Reference
Routine for gzipped binary doimain data IO.
Functions/Subroutines
subroutine mpi_check_num_of_domains (IO_param)
subroutine mpi_read_domain_info (IO_param, comm_IO)
subroutine mpi_read_import_data (IO_param, comm_IO)
subroutine mpi_read_export_data (IO_param, comm_IO)
subroutine mpi_write_domain_info (IO_param, comm_IO)
subroutine mpi_write_import_data (IO_param, comm_IO)
subroutine mpi_write_export_data (IO_param, comm_IO)
subroutine mpi_write_int_stack (IO_param, num, istack)
subroutine, private mpi_write_int_vector (IO_param, num, int_dat)
subroutine mpi_read_int_stack (IO_param, num, istack, ntot)
subroutine, private mpi_read_int_vector (IO_param, num, int_dat)
subroutine mpi_read_comm_table (IO_param, ncolumn, num, int_dat)
subroutine mpi_write_comm_table (IO_param, ncolumn, num, int_dat)
Detailed Description
Routine for gzipped binary doimain data IO.
      subroutine mpi_check_num_of_domains(IO_param)
      subroutine mpi_read_domain_info(IO_param, comm_IO)
      subroutine mpi_read_import_data(IO_param, comm_IO)
      subroutine mpi_read_export_data(IO_param, comm_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(communication_table), intent(inout) :: comm_IO
      subroutine mpi_write_domain_info(IO_param, comm_IO)
      subroutine mpi_write_import_data(IO_param, comm_IO)
      subroutine mpi_write_export_data(IO_param, comm_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(communication_table), intent(in) :: comm_IO
      subroutine mpi_read_int_stack(IO_param, num, istack, ntot)
      subroutine mpi_read_comm_table(IO_param, ncolumn, num, int_dat)
      subroutine mpi_write_int_stack(IO_param, num, istack)
      subroutine mpi_write_comm_table(IO_param, ncolumn, num, int_dat)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
      subroutine mpi_write_int_vector(IO_param, num, int_dat)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
      subroutine mpi_read_int_vector(IO_param, num, int_dat)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
Function/Subroutine Documentation
mpi_check_num_of_domains()
subroutine mpi_domain_data_io::mpi_check_num_of_domains (type(calypso_mpi_io_params), intent(inout) IO_param)
Definition at line 57 of file MPI_domain_data_IO.f90.
References m_error_ids::ierr_file, data_io_to_textline::len_int_txt, mpi_ascii_data_io::mpi_read_charahead(), and data_io_to_textline::read_integer_textline().
Referenced by mpi_read_domain_info().
mpi_read_comm_table()
subroutine mpi_domain_data_io::mpi_read_comm_table (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) ncolumn, integer(kind=kint), intent(in) num, integer(kind=kint), dimension(num), intent(inout) int_dat)
Definition at line 302 of file MPI_domain_data_IO.f90.
References m_constants::ione, data_io_to_textline::len_byte_stack_textline(), data_io_to_textline::len_multi_int_textline(), mpi_ascii_data_io::mpi_skip_read(), and data_io_to_textline::read_multi_int_textline().
Referenced by mpi_read_export_data(), mpi_spherical_model_io::mpi_read_gl_reso_sph(), mpi_groups_io::mpi_read_group_data(), mpi_read_import_data(), mpi_spherical_model_io::mpi_read_rank_4_sph(), and mpi_groups_io::mpi_read_surf_grp_item().
mpi_read_domain_info()
subroutine mpi_domain_data_io::mpi_read_domain_info (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(inout) comm_IO)
Definition at line 76 of file MPI_domain_data_IO.f90.
References t_comm_table::alloc_neighbouring_id(), mpi_check_num_of_domains(), mpi_read_int_vector(), and mpi_ascii_data_io::mpi_read_num_of_data().
Referenced by mpi_edge_data_io::mpi_read_edge_connection(), mpi_element_data_io::mpi_read_element_comm_table(), mpi_sph_modes_data_io::mpi_read_geom_rtm_data(), mpi_sph_modes_data_io::mpi_read_geom_rtp_data(), mpi_sph_modes_data_io::mpi_read_modes_rlm_data(), mpi_mesh_data_io::mpi_read_num_node(), mpi_sph_modes_data_io::mpi_read_spectr_rj_data(), and mpi_surface_data_io::mpi_read_surface_connection().
mpi_read_export_data()
subroutine mpi_domain_data_io::mpi_read_export_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(inout) comm_IO)
Definition at line 121 of file MPI_domain_data_IO.f90.
References t_comm_table::alloc_export_item(), t_comm_table::alloc_export_num(), m_constants::ione, mpi_read_comm_table(), mpi_read_int_stack(), and mpi_ascii_data_io::mpi_read_num_of_data().
Referenced by mpi_edge_data_io::mpi_read_edge_connection(), mpi_element_data_io::mpi_read_element_comm_table(), mpi_mesh_data_io::mpi_read_geometry_data(), and mpi_surface_data_io::mpi_read_surface_connection().
mpi_read_import_data()
subroutine mpi_domain_data_io::mpi_read_import_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(inout) comm_IO)
Definition at line 97 of file MPI_domain_data_IO.f90.
References t_comm_table::alloc_import_item(), t_comm_table::alloc_import_num(), m_constants::ione, mpi_read_comm_table(), mpi_read_int_stack(), and mpi_ascii_data_io::mpi_read_num_of_data().
Referenced by mpi_edge_data_io::mpi_read_edge_connection(), mpi_element_data_io::mpi_read_element_comm_table(), mpi_sph_modes_data_io::mpi_read_geom_rtm_data(), mpi_sph_modes_data_io::mpi_read_geom_rtp_data(), mpi_mesh_data_io::mpi_read_geometry_data(), mpi_sph_modes_data_io::mpi_read_modes_rlm_data(), mpi_sph_modes_data_io::mpi_read_spectr_rj_data(), and mpi_surface_data_io::mpi_read_surface_connection().
mpi_read_int_stack()
subroutine mpi_domain_data_io::mpi_read_int_stack (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) num, integer(kind=kint), dimension(0:num), intent(inout) istack, integer(kind=kint), intent(inout) ntot)
Definition at line 250 of file MPI_domain_data_IO.f90.
References mpi_read_int_vector().
Referenced by mpi_read_export_data(), mpi_groups_io::mpi_read_group_data(), mpi_read_import_data(), and mpi_groups_io::mpi_read_surf_grp_data().
mpi_read_int_vector()
subroutine, private mpi_domain_data_io::mpi_read_int_vector (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) num, integer(kind=kint), dimension(num), intent(inout) int_dat) private
Definition at line 269 of file MPI_domain_data_IO.f90.
References data_io_to_textline::len_byte_stack_textline(), data_io_to_textline::len_multi_int_textline(), mpi_ascii_data_io::mpi_read_characters(), mpi_ascii_data_io::mpi_skip_read(), and data_io_to_textline::read_multi_int_textline().
Referenced by mpi_read_domain_info(), and mpi_read_int_stack().
mpi_write_comm_table()
subroutine mpi_domain_data_io::mpi_write_comm_table (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) ncolumn, integer(kind=kint), intent(in) num, integer(kind=kint), dimension(num), intent(in) int_dat)
Definition at line 361 of file MPI_domain_data_IO.f90.
References m_constants::ione, data_io_to_textline::len_multi_int_textline(), mpi_ascii_data_io::mpi_write_num_of_data(), mpi_ascii_data_io::mpi_write_stack_over_domain(), and data_io_to_textline::multi_int_textline().
Referenced by mpi_write_export_data(), mpi_spherical_model_io::mpi_write_gl_reso_sph(), mpi_groups_io::mpi_write_grp_data(), mpi_write_import_data(), mpi_spherical_model_io::mpi_write_rank_4_sph(), and mpi_groups_io::mpi_write_surf_grp_item().
mpi_write_domain_info()
subroutine mpi_domain_data_io::mpi_write_domain_info (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(in) comm_IO)
Definition at line 146 of file MPI_domain_data_IO.f90.
References data_io_to_textline::integer_textline(), data_io_to_textline::len_int_txt, mpi_ascii_data_io::mpi_write_charahead(), and mpi_write_int_vector().
Referenced by mpi_edge_data_io::mpi_write_edge_connection(), mpi_element_data_io::mpi_write_element_comm_table(), mpi_sph_modes_data_io::mpi_write_geom_rtm_data(), mpi_sph_modes_data_io::mpi_write_geom_rtp_data(), mpi_mesh_data_io::mpi_write_geometry_data(), mpi_sph_modes_data_io::mpi_write_modes_rlm_data(), mpi_sph_modes_data_io::mpi_write_spectr_rj_data(), and mpi_surface_data_io::mpi_write_surface_connection().
mpi_write_export_data()
subroutine mpi_domain_data_io::mpi_write_export_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(in) comm_IO)
Definition at line 181 of file MPI_domain_data_IO.f90.
References m_constants::ione, mpi_write_comm_table(), and mpi_write_int_stack().
Referenced by mpi_edge_data_io::mpi_write_edge_connection(), mpi_element_data_io::mpi_write_element_comm_table(), mpi_mesh_data_io::mpi_write_geometry_data(), and mpi_surface_data_io::mpi_write_surface_connection().
mpi_write_import_data()
subroutine mpi_domain_data_io::mpi_write_import_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(in) comm_IO)
Definition at line 166 of file MPI_domain_data_IO.f90.
References m_constants::ione, mpi_write_comm_table(), and mpi_write_int_stack().
Referenced by mpi_edge_data_io::mpi_write_edge_connection(), mpi_element_data_io::mpi_write_element_comm_table(), mpi_sph_modes_data_io::mpi_write_geom_rtm_data(), mpi_sph_modes_data_io::mpi_write_geom_rtp_data(), mpi_mesh_data_io::mpi_write_geometry_data(), mpi_sph_modes_data_io::mpi_write_modes_rlm_data(), mpi_sph_modes_data_io::mpi_write_spectr_rj_data(), and mpi_surface_data_io::mpi_write_surface_connection().
mpi_write_int_stack()
subroutine mpi_domain_data_io::mpi_write_int_stack (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) num, integer(kind=kint), dimension(0:num), intent(in) istack)
Definition at line 197 of file MPI_domain_data_IO.f90.
References mpi_write_int_vector().
Referenced by mpi_write_export_data(), mpi_groups_io::mpi_write_grp_data(), mpi_write_import_data(), and mpi_groups_io::mpi_write_surf_grp_data().
mpi_write_int_vector()
subroutine, private mpi_domain_data_io::mpi_write_int_vector (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) num, integer(kind=kint), dimension(num), intent(in) int_dat) private
Definition at line 211 of file MPI_domain_data_IO.f90.
References data_io_to_textline::byte_stack_textline(), data_io_to_textline::len_byte_stack_textline(), data_io_to_textline::len_multi_int_textline(), mpi_ascii_data_io::mpi_write_charahead(), mpi_ascii_data_io::mpi_write_num_of_data(), and data_io_to_textline::multi_int_textline().
Referenced by mpi_write_domain_info(), and mpi_write_int_stack().