CALYPSO: mag_of_field_smp Module Reference
mag_of_field_smp Module Reference
Functions/Subroutines
subroutine nodal_lscale_by_rot_smp (np_smp, nnod, inod_smp_stack, ncomp_nod, i_fld, i_rot, d_nod, d_len)
subroutine nodal_lscale_by_diffuse_smp (np_smp, nnod, inod_smp_stack, ncomp_nod, i_fld, i_diffuse, d_nod, d_len)
subroutine cal_vector_magnitude (np_smp, nnod, inod_smp_stack, d_fld, d_mag)
subroutine cal_sym_tensor_magnitude (np_smp, nnod, inod_smp_stack, d_fld, d_mag)
subroutine cal_asym_tensor_magnitude (np_smp, nnod, inod_smp_stack, d_fld, d_mag)
subroutine cal_len_scale_by_rot_smp (np_smp, nnod, inod_smp_stack, d_fld, d_rot, d_len)
subroutine cal_len_scale_by_diffuse_smp (np_smp, nnod, inod_smp_stack, d_fld, d_diffuse, d_len)
Function/Subroutine Documentation
cal_asym_tensor_magnitude()
subroutine mag_of_field_smp::cal_asym_tensor_magnitude (integer (kind = kint) np_smp, integer (kind = kint) nnod, integer (kind = kint), dimension(0:np_smp) inod_smp_stack, real(kind=kreal), dimension(nnod,3), intent(in) d_fld, real(kind=kreal), dimension(nnod), intent(inout) d_mag)
Definition at line 154 of file mag_of_field_smp.f90.
References m_constants::two.
cal_len_scale_by_diffuse_smp()
subroutine mag_of_field_smp::cal_len_scale_by_diffuse_smp (integer (kind = kint) np_smp, integer (kind = kint) nnod, integer (kind = kint), dimension(0:np_smp) inod_smp_stack, real(kind=kreal), dimension(nnod), intent(in) d_fld, real(kind=kreal), dimension(nnod), intent(in) d_diffuse, real(kind=kreal), dimension(nnod), intent(inout) d_len)
Definition at line 219 of file mag_of_field_smp.f90.
References m_constants::zero.
Referenced by cal_energy_flux_rtp::cal_lengh_scale_rtp(), and nodal_lscale_by_diffuse_smp().
cal_len_scale_by_rot_smp()
subroutine mag_of_field_smp::cal_len_scale_by_rot_smp (integer (kind = kint) np_smp, integer (kind = kint) nnod, integer (kind = kint), dimension(0:np_smp) inod_smp_stack, real(kind=kreal), dimension(nnod,3), intent(in) d_fld, real(kind=kreal), dimension(nnod,3), intent(in) d_rot, real(kind=kreal), dimension(nnod), intent(inout) d_len)
Definition at line 183 of file mag_of_field_smp.f90.
References m_constants::zero.
Referenced by cal_energy_flux_rtp::cal_lengh_scale_rtp(), and nodal_lscale_by_rot_smp().
cal_sym_tensor_magnitude()
subroutine mag_of_field_smp::cal_sym_tensor_magnitude (integer (kind = kint) np_smp, integer (kind = kint) nnod, integer (kind = kint), dimension(0:np_smp) inod_smp_stack, real(kind=kreal), dimension(nnod,6), intent(in) d_fld, real(kind=kreal), dimension(nnod), intent(inout) d_mag)
Definition at line 123 of file mag_of_field_smp.f90.
References m_constants::two.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and set_const_4_sections::set_constant_4_iso().
cal_vector_magnitude()
subroutine mag_of_field_smp::cal_vector_magnitude (integer (kind = kint) np_smp, integer (kind = kint) nnod, integer (kind = kint), dimension(0:np_smp) inod_smp_stack, real(kind=kreal), dimension(nnod,3), intent(in) d_fld, real(kind=kreal), dimension(nnod), intent(inout) d_mag)
Definition at line 95 of file mag_of_field_smp.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and set_const_4_sections::set_constant_4_iso().
nodal_lscale_by_diffuse_smp()
subroutine mag_of_field_smp::nodal_lscale_by_diffuse_smp (integer (kind = kint) np_smp, integer (kind = kint) nnod, integer (kind = kint), dimension(0:np_smp) inod_smp_stack, integer(kind = kint), intent(in) ncomp_nod, integer(kind = kint), intent(in) i_fld, integer(kind = kint), intent(in) i_diffuse, real(kind=kreal), dimension(nnod,ncomp_nod), intent(in) d_nod, real(kind=kreal), dimension(nnod), intent(inout) d_len)
Definition at line 75 of file mag_of_field_smp.f90.
References cal_len_scale_by_diffuse_smp().
nodal_lscale_by_rot_smp()
subroutine mag_of_field_smp::nodal_lscale_by_rot_smp (integer (kind = kint) np_smp, integer (kind = kint) nnod, integer (kind = kint), dimension(0:np_smp) inod_smp_stack, integer(kind = kint), intent(in) ncomp_nod, integer(kind = kint), intent(in) i_fld, integer(kind = kint), intent(in) i_rot, real(kind=kreal), dimension(nnod,ncomp_nod), intent(in) d_nod, real(kind=kreal), dimension(nnod), intent(inout) d_len)
Definition at line 57 of file mag_of_field_smp.f90.
References cal_len_scale_by_rot_smp().