CALYPSO: set_control_4_model Module Reference
set_control_4_model Module Reference
set models for MHD simulation from control data
Functions/Subroutines
subroutine s_set_control_4_model (reft_ctl, refc_ctl, mevo_ctl, evo_ctl, nmtr_ctl, MHD_prop)
subroutine s_set_control_4_crank (mevo_ctl, fl_prop, cd_prop, ht_prop, cp_prop)
subroutine, private set_implicit_coefs (coef_imp_ctl, iflag_scheme, coef_imp, coef_exp)
Detailed Description
set models for MHD simulation from control data
      subroutine s_set_control_4_model(reft_ctl, refc_ctl,            &
     &          mevo_ctl, evo_ctl, nmtr_ctl, MHD_prop)
      subroutine s_set_control_4_crank                                &
     &         (mevo_ctl, fl_prop, cd_prop, ht_prop, cp_prop)
        type(reference_temperature_ctl), intent(in) :: reft_ctl
        type(reference_temperature_ctl), intent(in) :: refc_ctl
        type(mhd_evo_scheme_control), intent(in) :: mevo_ctl
        type(mhd_evolution_control), intent(in) :: evo_ctl
        type(node_monitor_control), intent(in) :: nmtr_ctl
        type(MHD_evolution_param), intent(inout) :: MHD_prop
Function/Subroutine Documentation
s_set_control_4_crank()
subroutine set_control_4_model::s_set_control_4_crank (type(mhd_evo_scheme_control), intent(in) mevo_ctl, type(fluid_property), intent(inout) fl_prop, type(conductive_property), intent(inout) cd_prop, type(scalar_property), intent(inout) ht_prop, type(scalar_property), intent(inout) cp_prop)
Definition at line 177 of file set_control_4_model.f90.
References m_machine_parameter::iflag_debug, m_machine_parameter::iflag_routine_msg, and set_implicit_coefs().
Referenced by set_control_sph_mhd::set_control_4_sph_mhd().
s_set_control_4_model()
subroutine set_control_4_model::s_set_control_4_model (type(reference_temperature_ctl), intent(in) reft_ctl, type(reference_temperature_ctl), intent(in) refc_ctl, type(mhd_evo_scheme_control), intent(in) mevo_ctl, type(mhd_evolution_control), intent(in) evo_ctl, type(node_monitor_control), intent(in) nmtr_ctl, type(mhd_evolution_param), intent(inout) MHD_prop)
Definition at line 44 of file set_control_4_model.f90.
References node_monitor_io::allocate_monitor_group(), calypso_mpi::calypso_mpi_abort(), m_base_field_labels::composition, m_machine_parameter::e_message, m_error_ids::ierr_evo, m_machine_parameter::iflag_debug, m_machine_parameter::iflag_routine_msg, m_base_field_labels::magnetic_field, node_monitor_io::monitor_grp, node_monitor_io::num_monitor, t_reference_scalar_param::set_reference_scalar_ctl(), m_base_field_labels::temperature, m_base_field_labels::vector_potential, and m_base_field_labels::velocity.
Referenced by set_control_sph_mhd::set_control_4_sph_mhd().
set_implicit_coefs()
subroutine, private set_control_4_model::set_implicit_coefs (type(read_real_item), intent(in) coef_imp_ctl, integer(kind=kint), intent(in) iflag_scheme, real(kind = kreal), intent(inout) coef_imp, real(kind = kreal), intent(inout) coef_exp) private
Definition at line 215 of file set_control_4_model.f90.
References m_constants::half, m_constants::one, and m_constants::zero.
Referenced by s_set_control_4_crank().