CALYPSO: gz_udt_file_io Module Reference
gz_udt_file_io Module Reference
gzipped UCD format data IO
Functions/Subroutines
subroutine write_gz_ucd_file (id_rank, gzip_name, ucd)
subroutine write_gz_udt_file (id_rank, gzip_name, ucd)
subroutine write_gz_grd_file (id_rank, gzip_name, ucd)
subroutine read_gz_udt_file (id_rank, gzip_name, ucd)
subroutine read_gz_ucd_file (id_rank, gzip_name, ucd)
subroutine read_gz_ucd_grd (id_rank, gzip_name, ucd)
subroutine read_alloc_gz_udt_params (id_rank, gzip_name, ucd)
subroutine read_alloc_gz_udt_file (id_rank, gzip_name, ucd)
subroutine read_alloc_gz_ucd_file (id_rank, gzip_name, ucd)
subroutine read_alloc_gz_ucd_grd (id_rank, gzip_name, ucd)
Variables
type(buffer_4_gzip), private zbuf_ucd
Detailed Description
gzipped UCD format data IO
      subroutine write_gz_ucd_file(id_rank, gzip_name, ucd)
      subroutine write_gz_udt_file(id_rank, gzip_name, ucd)
      subroutine write_gz_grd_file(id_rank, gzip_name, ucd)
        type(ucd_data), intent(in) :: ucd
      subroutine read_gz_udt_file(id_rank, gzip_name, ucd)
      subroutine read_gz_ucd_file(id_rank, gzip_name, ucd)
      subroutine read_gz_ucd_grd(id_rank, gzip_name, ucd)
        type(ucd_data), intent(inout) :: ucd
      subroutine read_alloc_gz_udt_params(id_rank, gzip_name, ucd)
      subroutine read_alloc_gz_udt_file(id_rank, gzip_name, ucd)
      subroutine read_alloc_gz_ucd_file(id_rank, gzip_name, ucd)
      subroutine read_alloc_gz_ucd_grd(id_rank, gzip_name, ucd)
        type(ucd_data), intent(inout) :: ucd
Parameters
id_rank process ID
gzip_name file name
ucd Structure for FEM field data IO
Function/Subroutine Documentation
read_alloc_gz_ucd_file()
subroutine gz_udt_file_io::read_alloc_gz_ucd_file (integer, intent(in) id_rank, character(len=kchara), intent(in) gzip_name, type(ucd_data), intent(inout) ucd)
Definition at line 222 of file gz_udt_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_rd_gzfile_a(), gz_udt_type_data_io::read_alloc_gz_ucd_mesh_data(), gz_udt_type_data_io::read_alloc_gz_udt_field(), gz_ucd_data_io::read_gz_udt_field_data(), and zbuf_ucd.
Referenced by ucd_io_select::sel_read_alloc_ucd_file().
read_alloc_gz_ucd_grd()
subroutine gz_udt_file_io::read_alloc_gz_ucd_grd (integer, intent(in) id_rank, character(len=kchara), intent(in) gzip_name, type(ucd_data), intent(inout) ucd)
Definition at line 246 of file gz_udt_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_rd_gzfile_a(), gz_udt_type_data_io::read_alloc_gz_ucd_mesh_data(), and zbuf_ucd.
Referenced by ucd_io_select::sel_read_alloc_ucd_file().
read_alloc_gz_udt_file()
subroutine gz_udt_file_io::read_alloc_gz_udt_file (integer, intent(in) id_rank, character(len=kchara), intent(in) gzip_name, type(ucd_data), intent(inout) ucd)
Definition at line 199 of file gz_udt_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_rd_gzfile_a(), gz_udt_type_data_io::read_alloc_gz_udt_field(), gz_ucd_data_io::read_gz_udt_field_data(), and zbuf_ucd.
Referenced by ucd_io_select::sel_read_alloc_ucd_file(), and ucd_io_select::sel_read_alloc_udt_file().
read_alloc_gz_udt_params()
subroutine gz_udt_file_io::read_alloc_gz_udt_params (integer, intent(in) id_rank, character(len=kchara), intent(in) gzip_name, type(ucd_data), intent(inout) ucd)
Definition at line 178 of file gz_udt_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_rd_gzfile_a(), gz_udt_type_data_io::read_alloc_gz_udt_field(), and zbuf_ucd.
Referenced by ucd_io_select::sel_read_udt_param().
read_gz_ucd_file()
subroutine gz_udt_file_io::read_gz_ucd_file (integer, intent(in) id_rank, character(len=kchara), intent(in) gzip_name, type(ucd_data), intent(inout) ucd)
Definition at line 136 of file gz_udt_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_rd_gzfile_a(), gz_udt_type_data_io::read_gz_ucd_mesh_data(), gz_udt_type_data_io::read_gz_udt_field(), and zbuf_ucd.
Referenced by ucd_io_select::sel_read_ucd_file().
read_gz_ucd_grd()
subroutine gz_udt_file_io::read_gz_ucd_grd (integer, intent(in) id_rank, character(len=kchara), intent(in) gzip_name, type(ucd_data), intent(inout) ucd)
Definition at line 157 of file gz_udt_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_rd_gzfile_a(), gz_udt_type_data_io::read_gz_ucd_mesh_data(), and zbuf_ucd.
Referenced by ucd_io_select::sel_read_ucd_file().
read_gz_udt_file()
subroutine gz_udt_file_io::read_gz_udt_file (integer, intent(in) id_rank, character(len=kchara), intent(in) gzip_name, type(ucd_data), intent(inout) ucd)
Definition at line 115 of file gz_udt_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_rd_gzfile_a(), gz_udt_type_data_io::read_gz_udt_field(), and zbuf_ucd.
Referenced by ucd_io_select::sel_read_ucd_file(), and ucd_io_select::sel_read_udt_file().
write_gz_grd_file()
subroutine gz_udt_file_io::write_gz_grd_file (integer, intent(in) id_rank, character(len=kchara), intent(in) gzip_name, type(ucd_data), intent(in) ucd)
Definition at line 93 of file gz_udt_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_wt_gzfile_a(), gz_udt_type_data_io::write_gz_ucd_type_mesh(), and zbuf_ucd.
Referenced by ucd_io_select::sel_write_grd_file().
write_gz_ucd_file()
subroutine gz_udt_file_io::write_gz_ucd_file (integer, intent(in) id_rank, character(len=kchara), intent(in) gzip_name, type(ucd_data), intent(in) ucd)
Definition at line 50 of file gz_udt_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_wt_gzfile_a(), gz_udt_type_data_io::write_gz_ucd_type_mesh(), gz_udt_type_data_io::write_gz_udt_type_fields(), and zbuf_ucd.
Referenced by ucd_io_select::sel_write_ucd_file(), and ucd_io_select::sel_write_udt_file().
write_gz_udt_file()
subroutine gz_udt_file_io::write_gz_udt_file (integer, intent(in) id_rank, character(len=kchara), intent(in) gzip_name, type(ucd_data), intent(in) ucd)
Definition at line 72 of file gz_udt_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_wt_gzfile_a(), gz_udt_type_data_io::write_gz_udt_type_fields(), and zbuf_ucd.
Referenced by ucd_io_select::sel_write_ucd_file(), and ucd_io_select::sel_write_udt_file().
Variable Documentation
zbuf_ucd
type(buffer_4_gzip), private gz_udt_file_io::zbuf_ucd private
Definition at line 42 of file gz_udt_file_IO.f90.
Referenced by read_alloc_gz_ucd_file(), read_alloc_gz_ucd_grd(), read_alloc_gz_udt_file(), read_alloc_gz_udt_params(), read_gz_ucd_file(), read_gz_ucd_grd(), read_gz_udt_file(), write_gz_grd_file(), write_gz_ucd_file(), and write_gz_udt_file().