CALYPSO: sph_transforms_4_mhd Module Reference
sph_transforms_4_mhd Module Reference
Perform spherical harmonics transform for MHD dynamo model.
Functions/Subroutines
subroutine sph_back_trans_4_mhd (sph, comms_sph, fl_prop, sph_bc_U, omega_sph, trans_p, gt_cor, rj_fld, b_trns, trns_bwd, WK_leg, WK_FFTs_MHD, cor_rlm)
subroutine sph_forward_trans_4_mhd (sph, comms_sph, fl_prop, trans_p, cor_rlm, f_trns, trns_fwd, WK_leg, WK_FFTs_MHD, rj_fld)
subroutine sph_pole_trans_4_mhd (sph, comms_sph, trans_p, rj_fld, trns_bwd)
subroutine sph_transform_4_licv (sph_rlm, comm_rlm, comm_rj, fl_prop, sph_bc_U, omega_sph, trans_p, gt_cor, trns_MHD, rj_fld, cor_rlm)
Detailed Description
Perform spherical harmonics transform for MHD dynamo model.
      subroutine sph_back_trans_4_MHD(sph, comms_sph, fl_prop,        &
     &          sph_bc_U, omega_sph, trans_p, gt_cor, rj_fld,         &
     &          b_trns, trns_bwd, WK_leg, WK_FFTs_MHD, cor_rlm)
        Input ::  rj_fld
        Output :: trns_MHD, cor_rlm
      subroutine sph_pole_trans_4_MHD                                 &
     &         (sph, comms_sph, trans_p, rj_fld, trns_bwd)
        Input ::  rj_fld
        Output :: trns_MHD
        type(sph_grids), intent(inout) :: sph
        type(sph_comm_tables), intent(inout) :: comms_sph
        type(fluid_property), intent(in) :: fl_prop
        type(sph_boundary_type), intent(in) :: sph_bc_U
        type(sph_rotation), intent(in) :: omega_sph
        type(parameters_4_sph_trans), intent(in) :: trans_p
        type(gaunt_coriolis_rlm), intent(in) :: gt_cor
        type(phys_data), intent(in) :: rj_fld
        type(phys_address), intent(in) :: b_trns
        type(phys_address), intent(in) :: f_trns
        type(spherical_transform_data), intent(inout) :: trns_bwd
        type(spherical_transform_data), intent(inout) :: trns_fwd
        type(legendre_trns_works), intent(inout) :: WK_leg
        type(work_for_FFTs), intent(inout) :: WK_FFTs_MHD
        type(coriolis_rlm_data), intent(inout) :: cor_rlm
      subroutine sph_forward_trans_4_MHD                              &
     &         (sph, comms_sph, fl_prop, trans_p, cor_rlm, f_trns,    &
     &          trns_fwd, WK_leg, WK_FFTs_MHD, rj_fld)
        Input :: trns_fwd, cor_rlm
        Output ::  rj_fld
        type(sph_grids), intent(inout) :: sph
        type(sph_comm_tables), intent(inout) :: comms_sph
        type(fluid_property), intent(in) :: fl_prop
        type(parameters_4_sph_trans), intent(in) :: trans_p
        type(coriolis_rlm_data), intent(in) :: cor_rlm
        type(phys_address), intent(in) :: ipol
        type(phys_address), intent(in) :: f_trns
        type(spherical_transform_data), intent(inout) :: trns_fwd
        type(legendre_trns_works), intent(inout) :: WK_leg
        type(work_for_FFTs), intent(inout) :: WK_FFTs_MHD
        type(phys_data), intent(inout) :: rj_fld
      subroutine sph_transform_4_licv                                 &
     &         (sph_rlm, comm_rlm, comm_rj, fl_prop, sph_bc_U,        &
     &          omega_sph, trans_p, gt_cor, trns_MHD,                 &
     &          rj_fld, cor_rlm)
        type(fluid_property), intent(in) :: fl_prop
        type(phys_data), intent(inout) :: rj_fld
        type(coriolis_rlm_data), intent(inout) :: cor_rlm
Function/Subroutine Documentation
sph_back_trans_4_mhd()
subroutine sph_transforms_4_mhd::sph_back_trans_4_mhd (type(sph_grids), intent(in) sph, type(sph_comm_tables), intent(in) comms_sph, type(fluid_property), intent(in) fl_prop, type(sph_boundary_type), intent(in) sph_bc_U, type(sph_rotation), intent(in) omega_sph, type(parameters_4_sph_trans), intent(in) trans_p, type(gaunt_coriolis_rlm), intent(in) gt_cor, type(phys_data), intent(in) rj_fld, type(phys_address), intent(in) b_trns, type(spherical_transform_data), intent(inout) trns_bwd, type(legendre_trns_works), intent(inout) WK_leg, type(work_for_ffts), intent(inout) WK_FFTs_MHD, type(coriolis_rlm_data), intent(inout) cor_rlm)
Definition at line 96 of file sph_transforms_4_MHD.f90.
References spherical_srs_n::check_calypso_sph_comm_buf_n(), m_work_time::end_elapsed_time(), m_machine_parameter::iflag_debug, m_elapsed_labels_sph_trns::iflag_sph_time, m_elapsed_labels_sph_trns::ist_elapsed_sph, set_address_sph_trans_mhd::mhd_spectr_to_sendbuf(), sph_trans_w_coriols::sph_b_trans_w_coriolis(), m_solver_sr::sr_r1, and m_work_time::start_elapsed_time().
Referenced by cal_nonlinear::nonlinear_by_pseudo_sph(), and test_legendre_transforms::s_test_legendre_transforms().
sph_forward_trans_4_mhd()
subroutine sph_transforms_4_mhd::sph_forward_trans_4_mhd (type(sph_grids), intent(in) sph, type(sph_comm_tables), intent(in) comms_sph, type(fluid_property), intent(in) fl_prop, type(parameters_4_sph_trans), intent(in) trans_p, type(coriolis_rlm_data), intent(in) cor_rlm, type(phys_address), intent(in) f_trns, type(spherical_transform_data), intent(inout) trns_fwd, type(legendre_trns_works), intent(inout) WK_leg, type(work_for_ffts), intent(inout) WK_FFTs_MHD, type(phys_data), intent(inout) rj_fld)
Definition at line 142 of file sph_transforms_4_MHD.f90.
References spherical_srs_n::check_calypso_sph_comm_buf_n(), m_work_time::end_elapsed_time(), m_elapsed_labels_sph_trns::iflag_sph_time, m_elapsed_labels_sph_trns::ist_elapsed_sph, set_address_sph_trans_mhd::mhd_spectr_from_recvbuf(), sph_trans_w_coriols::sph_f_trans_w_coriolis(), m_solver_sr::sr_r1, and m_work_time::start_elapsed_time().
Referenced by cal_nonlinear::nonlinear_by_pseudo_sph(), and test_legendre_transforms::s_test_legendre_transforms().
sph_pole_trans_4_mhd()
subroutine sph_transforms_4_mhd::sph_pole_trans_4_mhd (type(sph_grids), intent(in) sph, type(sph_comm_tables), intent(in) comms_sph, type(parameters_4_sph_trans), intent(in) trans_p, type(phys_data), intent(in) rj_fld, type(spherical_transform_data), intent(inout) trns_bwd)
Definition at line 184 of file sph_transforms_4_MHD.f90.
References spherical_srs_n::check_calypso_sph_comm_buf_n(), m_machine_parameter::iflag_debug, set_address_sph_trans_mhd::mhd_spectr_to_sendbuf(), t_sph_transforms::pole_b_transform(), and m_solver_sr::sr_r1.
sph_transform_4_licv()
subroutine sph_transforms_4_mhd::sph_transform_4_licv (type(sph_rlm_grid), intent(in) sph_rlm, type(sph_comm_tbl), intent(in) comm_rlm, type(sph_comm_tbl), intent(in) comm_rj, type(fluid_property), intent(in) fl_prop, type(sph_boundary_type), intent(in) sph_bc_U, type(sph_rotation), intent(in) omega_sph, type(parameters_4_sph_trans), intent(in) trans_p, type(gaunt_coriolis_rlm), intent(in) gt_cor, type(address_4_sph_trans), intent(in) trns_MHD, type(phys_data), intent(inout) rj_fld, type(coriolis_rlm_data), intent(inout) cor_rlm)
Definition at line 220 of file sph_transforms_4_MHD.f90.
References spherical_srs_n::check_calypso_sph_comm_buf_n(), set_address_sph_trans_mhd::mhd_spectr_from_recvbuf(), set_address_sph_trans_mhd::mhd_spectr_to_sendbuf(), sph_trans_w_coriols::sph_b_trans_licv(), sph_trans_w_coriols::sph_f_trans_licv(), and m_solver_sr::sr_r1.
Referenced by cal_nonlinear::licv_exp().