CALYPSO: mpi_element_data_io_b Module Reference
mpi_element_data_io_b Module Reference
Data IO routines for element data.
Functions/Subroutines
subroutine mpi_read_element_comm_table_b (IO_param, comm_IO)
subroutine mpi_write_element_comm_table_b (IO_param, comm_IO)
subroutine mpi_read_element_geometry_b (IO_param, nod_IO, sfed_IO)
subroutine mpi_write_element_geometry_b (IO_param, nod_IO, sfed_IO)
Detailed Description
Data IO routines for element data.
      subroutine mpi_read_element_comm_table_b(IO_param, comm_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(communication_table), intent(inout) :: comm_IO
      subroutine mpi_write_element_comm_table_b(IO_param, comm_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(communication_table), intent(in) :: comm_IO
      subroutine mpi_read_element_geometry_b                          &
     &         (IO_param, nod_IO, sfed_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(node_data), intent(inout) :: nod_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
      subroutine mpi_write_element_geometry_b                         &
     &         (IO_param, nod_IO, sfed_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(node_data), intent(in) :: nod_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
Function/Subroutine Documentation
mpi_read_element_comm_table_b()
subroutine mpi_element_data_io_b::mpi_read_element_comm_table_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(inout) comm_IO)
Definition at line 51 of file MPI_element_data_IO_b.f90.
References mpi_domain_data_io_b::mpi_read_domain_info_b(), mpi_domain_data_io_b::mpi_read_export_data_b(), and mpi_domain_data_io_b::mpi_read_import_data_b().
Referenced by mpi_element_file_io_b::mpi_input_element_file_b().
mpi_read_element_geometry_b()
subroutine mpi_element_data_io_b::mpi_read_element_geometry_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 86 of file MPI_element_data_IO_b.f90.
References mpi_node_geometry_io_b::mpi_read_geometry_info_b(), mpi_node_geometry_io_b::mpi_read_number_of_node_b(), and mpi_node_geometry_io_b::mpi_read_scl_in_ele_b().
mpi_write_element_comm_table_b()
subroutine mpi_element_data_io_b::mpi_write_element_comm_table_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(in) comm_IO)
Definition at line 68 of file MPI_element_data_IO_b.f90.
References mpi_domain_data_io_b::mpi_write_domain_info_b(), mpi_domain_data_io_b::mpi_write_export_data_b(), and mpi_domain_data_io_b::mpi_write_import_data_b().
Referenced by mpi_element_file_io_b::mpi_output_element_file_b().
mpi_write_element_geometry_b()
subroutine mpi_element_data_io_b::mpi_write_element_geometry_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 103 of file MPI_element_data_IO_b.f90.
References mpi_node_geometry_io_b::mpi_write_geometry_info_b(), and mpi_node_geometry_io_b::mpi_write_scl_in_ele_b().