CALYPSO: set_radial_grid_sph_shell Module Reference
set_radial_grid_sph_shell Module Reference
Set radial grid data.
Functions/Subroutines
subroutine set_equi_distance_shell (num_layer, nlayer_ICB, nlayer_CMB, r_ICB, r_CMB, r_grid)
subroutine count_equi_ext_layers (nri, r_ICB, r_CMB, r_min, r_max, ntot_shell, nlayer_ICB, nlayer_CMB)
subroutine set_radial_distance_flag (num_layer, nlayer_ICB, nlayer_CMB, r_ICB, r_CMB, r_grid, iflag_rgrid)
Detailed Description
Set radial grid data.
      subroutine set_equi_distance_shell(num_layer, nlayer_ICB,       &
     &          nlayer_CMB, r_ICB, r_CMB, r_grid)
      subroutine count_equi_ext_layers(nri, r_ICB, r_CMB,             &
     &          r_min, r_max, ntot_shell, nlayer_ICB, nlayer_CMB)
      subroutine set_radial_distance_flag(num_layer, nlayer_ICB,      &
     &          nlayer_CMB, r_ICB, r_CMB, r_grid, iflag_rgrid)
Function/Subroutine Documentation
count_equi_ext_layers()
subroutine set_radial_grid_sph_shell::count_equi_ext_layers (integer(kind = kint), intent(in) nri, real(kind = kreal), intent(in) r_ICB, real(kind = kreal), intent(in) r_CMB, real(kind = kreal), intent(in) r_min, real(kind = kreal), intent(in) r_max, integer(kind = kint), intent(inout) ntot_shell, integer(kind = kint), intent(inout) nlayer_ICB, integer(kind = kint), intent(inout) nlayer_CMB)
Definition at line 56 of file set_radial_grid_sph_shell.f90.
Referenced by const_sph_radial_grid::count_set_radial_grid().
set_equi_distance_shell()
subroutine set_radial_grid_sph_shell::set_equi_distance_shell (integer(kind = kint), intent(in) num_layer, integer(kind = kint), intent(in) nlayer_ICB, integer(kind = kint), intent(in) nlayer_CMB, real(kind = kreal), intent(in) r_ICB, real(kind = kreal), intent(in) r_CMB, real(kind = kreal), dimension(num_layer), intent(inout) r_grid)
Definition at line 32 of file set_radial_grid_sph_shell.f90.
Referenced by const_sph_radial_grid::count_set_radial_grid(), and set_radial_distance_flag().
set_radial_distance_flag()
subroutine set_radial_grid_sph_shell::set_radial_distance_flag (integer(kind = kint), intent(in) num_layer, integer(kind = kint), intent(in) nlayer_ICB, integer(kind = kint), intent(in) nlayer_CMB, real(kind = kreal), intent(in) r_ICB, real(kind = kreal), intent(in) r_CMB, real(kind = kreal), dimension(num_layer), intent(in) r_grid, integer(kind = kint), intent(inout) iflag_rgrid)
Definition at line 97 of file set_radial_grid_sph_shell.f90.
References half_chebyshev_radial_grid::half_chebyshev_distance_shell(), m_spheric_constants::igrid_chebyshev, m_spheric_constants::igrid_equidistance, m_spheric_constants::igrid_half_chebyshev, m_spheric_constants::igrid_non_equidist, chebyshev_radial_grid::set_chebyshev_distance_shell(), and set_equi_distance_shell().
Referenced by set_radius_4_sph_dynamo::set_radius_dat_4_sph_dynamo().