CALYPSO: set_edge_list_for_psf Module Reference
set_edge_list_for_psf Module Reference
Functions/Subroutines
subroutine allocate_work_4_mark_edge_psf (numedge)
subroutine deallocate_work_4_mark_edge_psf
subroutine mark_edge_list_4_psf (numsurf, numedge, iedge_4_sf, surf_search)
subroutine count_edge_list_4_psf (iedge_smp_stack, edge_search)
subroutine set_edge_list_4_psf (iedge_smp_stack, edge_search)
Variables
integer(kind=kint), dimension(:), allocatable, private imark_edge
integer(kind=kint), dimension(:,:), allocatable, private imark_edge_smp
integer(kind=kint), dimension(:), allocatable, private nedge_search_smp
Function/Subroutine Documentation
allocate_work_4_mark_edge_psf()
subroutine set_edge_list_for_psf::allocate_work_4_mark_edge_psf (integer(kind = kint), intent(in) numedge)
Definition at line 36 of file set_edge_list_for_psf.f90.
References imark_edge, imark_edge_smp, nedge_search_smp, and m_machine_parameter::np_smp.
Referenced by search_ele_list_for_psf::set_searched_edge_list_4_psf().
count_edge_list_4_psf()
subroutine set_edge_list_for_psf::count_edge_list_4_psf (integer(kind=kint), dimension(0:np_smp), intent(in) iedge_smp_stack, type(sect_search_list), intent(inout) edge_search)
Definition at line 127 of file set_edge_list_for_psf.f90.
References imark_edge, and nedge_search_smp.
Referenced by search_ele_list_for_psf::set_searched_edge_list_4_psf().
deallocate_work_4_mark_edge_psf()
subroutine set_edge_list_for_psf::deallocate_work_4_mark_edge_psf
Definition at line 54 of file set_edge_list_for_psf.f90.
References imark_edge, imark_edge_smp, and nedge_search_smp.
Referenced by search_ele_list_for_psf::set_searched_edge_list_4_psf().
mark_edge_list_4_psf()
subroutine set_edge_list_for_psf::mark_edge_list_4_psf (integer(kind = kint), intent(in) numsurf, integer(kind = kint), intent(in) numedge, integer(kind = kint), dimension(numsurf,nedge_4_surf), intent(in) iedge_4_sf, type(sect_search_list), intent(in) surf_search)
Definition at line 63 of file set_edge_list_for_psf.f90.
References imark_edge, imark_edge_smp, m_geometry_constants::nedge_4_surf, and m_machine_parameter::np_smp.
Referenced by search_ele_list_for_psf::set_searched_edge_list_4_psf().
set_edge_list_4_psf()
subroutine set_edge_list_for_psf::set_edge_list_4_psf (integer(kind = kint), dimension(0:np_smp), intent(in) iedge_smp_stack, type(sect_search_list), intent(inout) edge_search)
Definition at line 160 of file set_edge_list_for_psf.f90.
References imark_edge.
Referenced by search_ele_list_for_psf::set_searched_edge_list_4_psf().
Variable Documentation
imark_edge
integer(kind = kint), dimension(:), allocatable, private set_edge_list_for_psf::imark_edge private
Definition at line 22 of file set_edge_list_for_psf.f90.
Referenced by allocate_work_4_mark_edge_psf(), count_edge_list_4_psf(), deallocate_work_4_mark_edge_psf(), mark_edge_list_4_psf(), and set_edge_list_4_psf().
imark_edge_smp
integer(kind = kint), dimension(:,:), allocatable, private set_edge_list_for_psf::imark_edge_smp private
Definition at line 23 of file set_edge_list_for_psf.f90.
Referenced by allocate_work_4_mark_edge_psf(), deallocate_work_4_mark_edge_psf(), and mark_edge_list_4_psf().
nedge_search_smp
integer(kind = kint), dimension(:), allocatable, private set_edge_list_for_psf::nedge_search_smp private
Definition at line 25 of file set_edge_list_for_psf.f90.
Referenced by allocate_work_4_mark_edge_psf(), count_edge_list_4_psf(), and deallocate_work_4_mark_edge_psf().