CALYPSO: t_ctl_data_mhd Module Reference
t_ctl_data_mhd Module Reference
Data Types
type dns_mhd_simulation_control
Functions/Subroutines
subroutine read_sph_mhd_ctl_w_psf (id_control, hd_block, DMHD_ctl, c_buf)
subroutine read_sph_mhd_ctl_noviz (id_control, hd_block, DMHD_ctl, c_buf)
subroutine bcast_sph_mhd_ctl_w_psf (DMHD_ctl)
subroutine bcast_sph_mhd_ctl_data (DMHD_ctl)
subroutine dealloc_sph_mhd_ctl_data (DMHD_ctl)
Variables
character(len=kchara), parameter, private hd_platform = 'data_files_def'
character(len=kchara), parameter, private hd_org_data = 'org_data_files_def'
character(len=kchara), parameter, private hd_new_data = 'new_data_files_def'
character(len=kchara), parameter, private hd_sph_shell = 'spherical_shell_ctl'
character(len=kchara), parameter, private hd_model = 'model'
character(len=kchara), parameter, private hd_control = 'control'
character(len=kchara), parameter, private hd_pick_sph = 'sph_monitor_ctl'
character(len=kchara), parameter, private hd_monitor_data = 'monitor_data_ctl'
character(len=kchara), parameter, private hd_viz_ctl = 'visual_control'
character(len=kchara), parameter, private hd_dynamo_viz_ctl = 'dynamo_vizs_control'
character(len=kchara), parameter, private hd_zm_viz_ctl = 'zonal_mean_control'
Here is the old label.
Function/Subroutine Documentation
bcast_sph_mhd_ctl_data()
subroutine t_ctl_data_mhd::bcast_sph_mhd_ctl_data (type(dns_mhd_simulation_control), intent(inout) DMHD_ctl)
Definition at line 213 of file t_ctl_data_MHD.f90.
References bcast_4_platform_ctl::bcast_ctl_data_4_platform(), t_ctl_data_node_monitor::bcast_monitor_data_ctl(), t_ctl_data_gen_sph_shell::bcast_parallel_shell_ctl(), t_ctl_data_sph_mhd_control::bcast_sph_mhd_control(), t_ctl_data_mhd_model::bcast_sph_mhd_model(), bcast_4_sph_monitor_ctl::bcast_sph_monitoring_ctl(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by bcast_sph_mhd_ctl_w_psf(), and t_ctl_data_sph_mhd_psf::read_control_4_sph_mhd_noviz().
bcast_sph_mhd_ctl_w_psf()
subroutine t_ctl_data_mhd::bcast_sph_mhd_ctl_w_psf (type(dns_mhd_simulation_control), intent(inout) DMHD_ctl)
Definition at line 200 of file t_ctl_data_MHD.f90.
References t_control_data_dynamo_vizs::bcast_dynamo_viz_control(), bcast_sph_mhd_ctl_data(), and t_control_data_surfacings::bcast_surfacing_controls().
Referenced by t_ctl_data_sph_mhd_psf::read_control_4_sph_mhd_w_psf().
dealloc_sph_mhd_ctl_data()
subroutine t_ctl_data_mhd::dealloc_sph_mhd_ctl_data (type(dns_mhd_simulation_control), intent(inout) DMHD_ctl)
Definition at line 241 of file t_ctl_data_MHD.f90.
References t_ctl_data_node_monitor::dealloc_monitor_data_ctl(), t_ctl_data_gen_sph_shell::dealloc_parallel_shell_ctl(), t_ctl_data_mhd_model::dealloc_sph_mhd_model(), and t_ctl_data_4_sph_monitor::dealloc_sph_monitoring_ctl().
Referenced by input_control_sph_mhd::input_control_4_sph_make_init(), input_control_sph_mhd::input_control_4_sph_mhd_nosnap(), input_control_dynamobench::input_control_sph_dynamobench(), and input_control_sph_mhd::input_control_sph_mhd_psf().
read_sph_mhd_ctl_noviz()
subroutine t_ctl_data_mhd::read_sph_mhd_ctl_noviz (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(dns_mhd_simulation_control), intent(inout) DMHD_ctl, type(buffer_for_control), intent(inout) c_buf)
Definition at line 158 of file t_ctl_data_MHD.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_control, hd_model, hd_monitor_data, hd_org_data, hd_pick_sph, hd_platform, hd_sph_shell, t_read_control_elements::load_one_line_from_control(), t_ctl_data_4_platforms::read_control_platforms(), t_ctl_data_node_monitor::read_monitor_data_ctl(), t_ctl_data_gen_sph_shell::read_parallel_shell_in_mhd_ctl(), t_ctl_data_sph_mhd_control::read_sph_mhd_control(), t_ctl_data_mhd_model::read_sph_mhd_model(), and t_ctl_data_4_sph_monitor::read_sph_monitoring_ctl().
Referenced by t_ctl_data_sph_mhd_psf::read_control_4_sph_mhd_noviz().
read_sph_mhd_ctl_w_psf()
subroutine t_ctl_data_mhd::read_sph_mhd_ctl_w_psf (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(dns_mhd_simulation_control), intent(inout) DMHD_ctl, type(buffer_for_control), intent(inout) c_buf)
Definition at line 109 of file t_ctl_data_MHD.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_control, hd_dynamo_viz_ctl, hd_model, hd_monitor_data, hd_org_data, hd_pick_sph, hd_platform, hd_sph_shell, hd_viz_ctl, hd_zm_viz_ctl, t_read_control_elements::load_one_line_from_control(), t_ctl_data_4_platforms::read_control_platforms(), t_control_data_dynamo_vizs::read_dynamo_viz_control(), t_ctl_data_node_monitor::read_monitor_data_ctl(), t_ctl_data_gen_sph_shell::read_parallel_shell_in_mhd_ctl(), t_ctl_data_sph_mhd_control::read_sph_mhd_control(), t_ctl_data_mhd_model::read_sph_mhd_model(), t_ctl_data_4_sph_monitor::read_sph_monitoring_ctl(), and t_control_data_surfacings::read_surfacing_controls().
Referenced by t_ctl_data_sph_mhd_psf::read_control_4_sph_mhd_w_psf().
Variable Documentation
hd_control
character(len=kchara), parameter, private t_ctl_data_mhd::hd_control = 'control' private
Definition at line 84 of file t_ctl_data_MHD.f90.
Referenced by read_sph_mhd_ctl_noviz(), and read_sph_mhd_ctl_w_psf().
hd_dynamo_viz_ctl
character(len=kchara), parameter, private t_ctl_data_mhd::hd_dynamo_viz_ctl = 'dynamo_vizs_control' private
Definition at line 91 of file t_ctl_data_MHD.f90.
Referenced by read_sph_mhd_ctl_w_psf().
hd_model
character(len=kchara), parameter, private t_ctl_data_mhd::hd_model = 'model' private
Definition at line 83 of file t_ctl_data_MHD.f90.
Referenced by read_sph_mhd_ctl_noviz(), and read_sph_mhd_ctl_w_psf().
hd_monitor_data
character(len=kchara), parameter, private t_ctl_data_mhd::hd_monitor_data = 'monitor_data_ctl' private
Definition at line 87 of file t_ctl_data_MHD.f90.
Referenced by read_sph_mhd_ctl_noviz(), and read_sph_mhd_ctl_w_psf().
hd_new_data
character(len=kchara), parameter, private t_ctl_data_mhd::hd_new_data = 'new_data_files_def' private
Definition at line 79 of file t_ctl_data_MHD.f90.
hd_org_data
character(len=kchara), parameter, private t_ctl_data_mhd::hd_org_data = 'org_data_files_def' private
Definition at line 77 of file t_ctl_data_MHD.f90.
Referenced by read_sph_mhd_ctl_noviz(), and read_sph_mhd_ctl_w_psf().
hd_pick_sph
character(len=kchara), parameter, private t_ctl_data_mhd::hd_pick_sph = 'sph_monitor_ctl' private
Definition at line 85 of file t_ctl_data_MHD.f90.
Referenced by read_sph_mhd_ctl_noviz(), and read_sph_mhd_ctl_w_psf().
hd_platform
character(len=kchara), parameter, private t_ctl_data_mhd::hd_platform = 'data_files_def' private
Definition at line 75 of file t_ctl_data_MHD.f90.
Referenced by read_sph_mhd_ctl_noviz(), and read_sph_mhd_ctl_w_psf().
hd_sph_shell
character(len=kchara), parameter, private t_ctl_data_mhd::hd_sph_shell = 'spherical_shell_ctl' private
Definition at line 81 of file t_ctl_data_MHD.f90.
Referenced by read_sph_mhd_ctl_noviz(), and read_sph_mhd_ctl_w_psf().
hd_viz_ctl
character(len=kchara), parameter, private t_ctl_data_mhd::hd_viz_ctl = 'visual_control' private
Definition at line 90 of file t_ctl_data_MHD.f90.
Referenced by read_sph_mhd_ctl_w_psf().
hd_zm_viz_ctl
character(len=kchara), parameter, private t_ctl_data_mhd::hd_zm_viz_ctl = 'zonal_mean_control' private
Here is the old label.
Definition at line 95 of file t_ctl_data_MHD.f90.
Referenced by read_sph_mhd_ctl_w_psf().