CALYPSO: mpi_edge_data_io Module Reference
mpi_edge_data_io Module Reference
data IO orutines for edge
Functions/Subroutines
subroutine mpi_read_edge_connection (IO_param, comm_IO, ele_IO, sfed_IO)
subroutine mpi_write_edge_connection (IO_param, comm_IO, ele_IO, sfed_IO)
subroutine mpi_read_edge_geometry (IO_param, nod_IO, sfed_IO)
subroutine mpi_write_edge_geometry (IO_param, nod_IO, sfed_IO)
Detailed Description
data IO orutines for edge
      subroutine mpi_read_edge_connection                             &
     &         (IO_param, comm_IO, ele_IO, sfed_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(communication_table), intent(inout) :: comm_IO
        type(element_data), intent(inout) :: ele_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
      subroutine mpi_write_edge_connection                            &
     &         (IO_param, comm_IO, ele_IO, sfed_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(communication_table), intent(in) :: comm_IO
        type(element_data), intent(in) :: ele_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
      subroutine mpi_read_edge_geometry(IO_param, nod_IO, sfed_IO)
        type(node_data), intent(inout) :: nod_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
      subroutine mpi_write_edge_geometry(IO_param, nod_IO, sfed_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(communication_table), intent(inout) :: comm_IO
        type(node_data), intent(in) :: nod_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
Function/Subroutine Documentation
mpi_read_edge_connection()
subroutine mpi_edge_data_io::mpi_read_edge_connection (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(inout) comm_IO, type(element_data), intent(inout) ele_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 57 of file MPI_edge_data_IO.f90.
References m_fem_surface_labels::hd_edge_connect(), m_fem_surface_labels::hd_edge_export(), m_fem_surface_labels::hd_edge_import(), m_fem_surface_labels::hd_edge_on_ele(), m_fem_surface_labels::hd_edge_on_surf(), m_fem_surface_labels::hd_edge_para(), m_fem_mesh_labels::hd_fem_para(), mpi_domain_data_io::mpi_read_domain_info(), mpi_element_connect_io::mpi_read_edge_4_element(), mpi_element_connect_io::mpi_read_element_info(), mpi_domain_data_io::mpi_read_export_data(), mpi_domain_data_io::mpi_read_import_data(), mpi_element_connect_io::mpi_read_num_element(), mpi_element_connect_io::mpi_read_surface_4_element(), and mpi_ascii_data_io::mpi_skip_read().
Referenced by mpi_element_file_io::mpi_input_edge_file().
mpi_read_edge_geometry()
subroutine mpi_edge_data_io::mpi_read_edge_geometry (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 137 of file MPI_edge_data_IO.f90.
References m_fem_surface_labels::hd_edge_dir(), m_fem_surface_labels::hd_edge_length(), m_fem_surface_labels::hd_edge_point(), mpi_node_geometry_io::mpi_read_geometry_info(), mpi_node_geometry_io::mpi_read_number_of_node(), mpi_node_geometry_io::mpi_read_scl_in_ele(), mpi_node_geometry_io::mpi_read_vect_in_ele(), and mpi_ascii_data_io::mpi_skip_read().
mpi_write_edge_connection()
subroutine mpi_edge_data_io::mpi_write_edge_connection (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(in) comm_IO, type(element_data), intent(in) ele_IO, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 94 of file MPI_edge_data_IO.f90.
References m_fem_surface_labels::hd_edge_connect(), m_fem_surface_labels::hd_edge_export(), m_fem_surface_labels::hd_edge_import(), m_fem_surface_labels::hd_edge_on_ele(), m_fem_surface_labels::hd_edge_on_surf(), m_fem_surface_labels::hd_edge_para(), m_fem_mesh_labels::hd_fem_para(), mpi_ascii_data_io::mpi_write_charahead(), mpi_domain_data_io::mpi_write_domain_info(), mpi_element_connect_io::mpi_write_edge_4_element(), mpi_element_connect_io::mpi_write_element_info(), mpi_domain_data_io::mpi_write_export_data(), mpi_domain_data_io::mpi_write_import_data(), and mpi_element_connect_io::mpi_write_surface_4_element().
Referenced by mpi_element_file_io::mpi_output_edge_file().
mpi_write_edge_geometry()
subroutine mpi_edge_data_io::mpi_write_edge_geometry (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 159 of file MPI_edge_data_IO.f90.
References m_fem_surface_labels::hd_edge_dir(), m_fem_surface_labels::hd_edge_length(), m_fem_surface_labels::hd_edge_point(), mpi_ascii_data_io::mpi_write_charahead(), mpi_node_geometry_io::mpi_write_geometry_info(), mpi_node_geometry_io::mpi_write_scl_in_ele(), and mpi_node_geometry_io::mpi_write_vect_in_ele().