CALYPSO: const_fem_mesh_sph_mhd Module Reference
const_fem_mesh_sph_mhd Module Reference
Construct FEM mesh from spherical harmonics transform data.
Functions/Subroutines
subroutine const_fem_mesh_4_sph_mhd (FEM_mesh_flags, mesh_file, sph_params, sph_rtp, sph_rj, mesh, group, gen_sph)
subroutine base_fem_mesh_sph_mhd (sph_params, sph_rtp, sph_rj, mesh, group, gen_sph)
subroutine, private const_global_sph_fem (sph_rtp, sph_rj, gen_sph)
subroutine, private const_global_rtp_mesh (sph_rtp, radial_rtp_grp, s3d_ranks, sph_dbc, sph_lcp, stk_lc1d, sph_gl1d)
Variables
type(gauss_points), save, private gauss_sf
type(sph_local_1d_param), save, private sph_lc1_sf
type(comm_table_make_sph), save, private stbl_sf
type(sph_local_default_bc), save, private sph_dbc_sf
Detailed Description
Construct FEM mesh from spherical harmonics transform data.
      subroutine const_FEM_mesh_4_sph_mhd                             &
     &        (FEM_mesh_flags, mesh_file, sph_params, sph_rtp, sph_rj,&
     &         mesh, group, mesh_file, gen_sph)
      subroutine base_FEM_mesh_sph_mhd                                &
     &         (FEM_mesh_flags, sph_params, sph_rtp, sph_rj,          &
     &          mesh, group, gen_sph)
        type(FEM_file_IO_flags), intent(in) :: FEM_mesh_flags
        type(sph_shell_parameters), intent(in) :: sph_params
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_rj_grid), intent(in) :: sph_rj
        type(mesh_geometry), intent(inout) :: mesh
        type(mesh_groups), intent(inout) ::  group
        type(field_IO_params), intent(inout) ::  mesh_file
        type(construct_spherical_grid), intent(inout) :: gen_sph
Function/Subroutine Documentation
base_fem_mesh_sph_mhd()
subroutine const_fem_mesh_sph_mhd::base_fem_mesh_sph_mhd (type(sph_shell_parameters), intent(in) sph_params, type(sph_rtp_grid), intent(in) sph_rtp, type(sph_rj_grid), intent(in) sph_rj, type(mesh_geometry), intent(inout) mesh, type(mesh_groups), intent(inout) group, type(construct_spherical_grid), intent(inout) gen_sph)
Definition at line 108 of file const_FEM_mesh_sph_mhd.f90.
References t_gauss_points::const_gauss_colatitude(), const_global_sph_fem(), t_gauss_points::dealloc_gauss_colatitude(), t_sph_mesh_1d_connect::dealloc_nnod_nele_sph_mesh(), gauss_sf, calypso_mpi::my_rank, const_1d_ele_connect_4_sph::s_const_1d_ele_connect_4_sph(), set_fem_mesh_4_sph::s_const_fem_mesh_for_sph(), and stbl_sf.
Referenced by const_fem_mesh_4_sph_mhd().
const_fem_mesh_4_sph_mhd()
subroutine const_fem_mesh_sph_mhd::const_fem_mesh_4_sph_mhd (type(fem_file_io_flags), intent(in) FEM_mesh_flags, type(field_io_params), intent(in) mesh_file, type(sph_shell_parameters), intent(in) sph_params, type(sph_rtp_grid), intent(in) sph_rtp, type(sph_rj_grid), intent(in) sph_rj, type(mesh_geometry), intent(inout) mesh, type(mesh_groups), intent(inout) group, type(construct_spherical_grid), intent(inout) gen_sph)
Definition at line 58 of file const_FEM_mesh_sph_mhd.f90.
References base_fem_mesh_sph_mhd(), mpi_load_mesh_data::mpi_output_mesh(), and calypso_mpi::my_rank.
Referenced by t_check_and_make_sph_mesh::load_fem_mesh_4_sph().
const_global_rtp_mesh()
subroutine, private const_fem_mesh_sph_mhd::const_global_rtp_mesh (type(sph_rtp_grid), intent(in) sph_rtp, type(group_data), intent(in) radial_rtp_grp, type(spheric_global_rank), intent(inout) s3d_ranks, type(sph_local_default_bc), intent(inout) sph_dbc, type(sph_local_parameters), intent(inout) sph_lcp, type(sph_1d_index_stack), intent(inout) stk_lc1d, type(sph_1d_global_index), intent(inout) sph_gl1d) private
Definition at line 179 of file const_FEM_mesh_sph_mhd.f90.
References t_sph_local_parameter::alloc_nidx_local(), t_sph_local_parameter::alloc_sph_gl_bc_param(), t_sph_local_parameter::alloc_sph_gl_parameter(), calypso_mpi_int::calypso_mpi_allreduce_int(), calypso_mpi_int::calypso_mpi_bcast_int(), transfer_to_long_integers::cast_long(), t_sph_local_parameter::dealloc_nidx_local(), t_sph_local_parameter::dealloc_sph_gl_bc_param(), t_spheric_parameter::ic_ele_grp_name, calypso_mpi::my_rank, calypso_mpi::nprocs, t_spheric_parameter::oc_ele_grp_name, set_global_spherical_param::set_gl_nnod_spherical(), and sph_lc1_sf.
Referenced by const_global_sph_fem().
const_global_sph_fem()
subroutine, private const_fem_mesh_sph_mhd::const_global_sph_fem (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_rj_grid), intent(in) sph_rj, type(construct_spherical_grid), intent(inout) gen_sph) private
Definition at line 148 of file const_FEM_mesh_sph_mhd.f90.
References const_global_rtp_mesh(), m_machine_parameter::iflag_debug, set_sph_1d_domain_id::set_sph_1d_domain_id_rtp(), and sph_dbc_sf.
Referenced by base_fem_mesh_sph_mhd().
Variable Documentation
gauss_sf
type(gauss_points), save, private const_fem_mesh_sph_mhd::gauss_sf private
Definition at line 43 of file const_FEM_mesh_sph_mhd.f90.
Referenced by base_fem_mesh_sph_mhd().
sph_dbc_sf
type(sph_local_default_bc), save, private const_fem_mesh_sph_mhd::sph_dbc_sf private
Definition at line 46 of file const_FEM_mesh_sph_mhd.f90.
Referenced by const_global_sph_fem().
sph_lc1_sf
type(sph_local_1d_param), save, private const_fem_mesh_sph_mhd::sph_lc1_sf private
Definition at line 44 of file const_FEM_mesh_sph_mhd.f90.
Referenced by const_global_rtp_mesh().
stbl_sf
type(comm_table_make_sph), save, private const_fem_mesh_sph_mhd::stbl_sf private
Definition at line 45 of file const_FEM_mesh_sph_mhd.f90.
Referenced by base_fem_mesh_sph_mhd().