CALYPSO: /home/takumi kera/calypso/src/C_libraries/BASE/numbers_to_bin_c.h File Reference
numbers_to_bin_c.h File Reference
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
void byte_swap_4 (int lengh_byte, char *array)
void byte_swap_8 (int lengh_byte, char *array)
void swap_4byte (char *buf8)
void swap_fortran_64bit (int *ilength, char *buf)
void uchar_2binarray (unsigned char hex, int bin[8])
void uchar_2bin (unsigned char hex, char bin[8])
void dec2bin (int dec, char *bin)
int charhex2bin (char *hex, char *bin)
double round_2_3digit (double value)
void find_order_digit (double d_in, double *d_out, int *i_digit)
double const_from_digit_order (double d_in, int i_digit)
Function Documentation
byte_swap_4()
void byte_swap_4 (int lengh_byte, char * array)
Definition at line 6 of file numbers_to_bin_c.c.
Referenced by gzread_32bit_f(), and rawread_32bit().
byte_swap_8()
void byte_swap_8 (int lengh_byte, char * array)
Definition at line 22 of file numbers_to_bin_c.c.
Referenced by gzread_64bit_f(), and rawread_64bit().
charhex2bin()
int charhex2bin (char * hex, char * bin)
Definition at line 141 of file numbers_to_bin_c.c.
const_from_digit_order()
double const_from_digit_order (double d_in, int i_digit)
Definition at line 195 of file numbers_to_bin_c.c.
dec2bin()
void dec2bin (int dec, char * bin)
Definition at line 119 of file numbers_to_bin_c.c.
find_order_digit()
void find_order_digit (double d_in, double * d_out, int * i_digit)
Definition at line 174 of file numbers_to_bin_c.c.
round_2_3digit()
double round_2_3digit (double value)
Definition at line 164 of file numbers_to_bin_c.c.
swap_4byte()
void swap_4byte (char * buf8)
Definition at line 46 of file numbers_to_bin_c.c.
Referenced by swap_fortran_64bit().
swap_fortran_64bit()
void swap_fortran_64bit (int * ilength, char * buf)
Definition at line 65 of file numbers_to_bin_c.c.
References swap_4byte().
uchar_2bin()
void uchar_2bin (unsigned char hex, char bin[8])
uchar_2binarray()
void uchar_2binarray (unsigned char hex, int bin[8])
Definition at line 97 of file numbers_to_bin_c.c.