CALYPSO: vtk_file_mpi_io Module Reference
vtk_file_mpi_io Module Reference
Output merged VTK file usgin MPI-IO.
Functions/Subroutines
subroutine write_vtk_data_mpi (id_vtk, ioff_gl, nnod, num_field, ntot_comp, ncomp_field, field_name, d_nod, istack_merged_intnod)
subroutine write_vtk_mesh_mpi (id_vtk, ioff_gl, nnod, nele, nnod_ele, xx, ie, istack_merged_intnod, istack_merged_ele)
subroutine, private write_vtk_field_mpi (id_vtk, ioff_gl, nnod, ncomp, vect, istack_merged_intnod)
subroutine, private write_vtk_tensor_mpi (id_vtk, ioff_gl, nnod, vect, istack_merged_intnod)
subroutine, private write_vtk_connect_mpi (id_vtk, ioff_gl, nt_ele, nele, nnod_ele, ie, istack)
subroutine, private write_vtk_celltype_mpi (id_vtk, ioff_gl, nt_ele, nele, nnod_ele, istack)
Detailed Description
Output merged VTK file usgin MPI-IO.
      subroutine write_vtk_data_mpi(id_vtk, ioff_gl,                  &
     &          nnod, num_field, ntot_comp, ncomp_field,              &
     &          field_name, d_nod, istack_merged_intnod)
      subroutine write_vtk_mesh_mpi(id_vtk, ioff_gl,                  &
     &          nnod, nele, nnod_ele, xx, ie,                         &
     &          istack_merged_intnod, istack_merged_ele)
Function/Subroutine Documentation
write_vtk_celltype_mpi()
subroutine, private vtk_file_mpi_io::write_vtk_celltype_mpi (integer, intent(in) id_vtk, integer(kind = kint_gl), intent(inout) ioff_gl, integer(kind = kint_gl), intent(in) nt_ele, integer(kind = kint_gl), intent(in) nele, integer(kind = kint), intent(in) nnod_ele, integer(kind = kint_gl), intent(in) istack) private
Definition at line 271 of file vtk_file_MPI_IO.f90.
References m_calypso_mpi_io::mpi_write_mul_chara_b(), vtk_data_to_buffer::vtk_cell_type(), and vtk_data_to_buffer::vtk_each_cell_type().
Referenced by write_vtk_mesh_mpi().
write_vtk_connect_mpi()
subroutine, private vtk_file_mpi_io::write_vtk_connect_mpi (integer, intent(in) id_vtk, integer(kind = kint_gl), intent(inout) ioff_gl, integer(kind = kint_gl), intent(in) nt_ele, integer(kind = kint_gl), intent(in) nele, integer(kind = kint), intent(in) nnod_ele, integer(kind = kint_gl), dimension(nele,nnod_ele), intent(in) ie, integer(kind = kint_gl), intent(in) istack) private
Definition at line 232 of file vtk_file_MPI_IO.f90.
References m_calypso_mpi_io::mpi_write_mul_chara_b(), and vtk_data_to_buffer::vtk_each_connect().
Referenced by write_vtk_mesh_mpi().
write_vtk_data_mpi()
subroutine vtk_file_mpi_io::write_vtk_data_mpi (integer, intent(in) id_vtk, integer(kind = kint_gl), intent(inout) ioff_gl, integer(kind=kint_gl), intent(in) nnod, integer(kind=kint), intent(in) num_field, integer(kind=kint), intent(in) ntot_comp, integer(kind=kint), dimension(num_field), intent(in) ncomp_field, character(len=kchara), dimension(num_field), intent(in) field_name, real(kind = kreal), dimension(nnod,ntot_comp), intent(in) d_nod, integer(kind = kint_gl), dimension(0:nprocs), intent(in) istack_merged_intnod)
Definition at line 38 of file vtk_file_MPI_IO.f90.
References m_calypso_mpi_io::calypso_mpi_seek_write_head_c(), m_phys_constants::n_scalar, m_phys_constants::n_sym_tensor, m_phys_constants::n_vector, calypso_mpi::nprocs, vtk_data_to_buffer::vtk_fields_head(), vtk_data_to_buffer::vtk_scalar_head(), vtk_data_to_buffer::vtk_tensor_head(), vtk_data_to_buffer::vtk_vector_head(), write_vtk_field_mpi(), and write_vtk_tensor_mpi().
Referenced by merged_udt_vtk_file_io::write_vtk_file_mpi(), and merged_udt_vtk_file_io::write_vtk_phys_mpi().
write_vtk_field_mpi()
subroutine, private vtk_file_mpi_io::write_vtk_field_mpi (integer, intent(in) id_vtk, integer(kind = kint_gl), intent(inout) ioff_gl, integer(kind = kint_gl), intent(in) nnod, integer(kind = kint), intent(in) ncomp, real(kind = kreal), dimension(nnod,ncomp), intent(in) vect, integer(kind = kint_gl), dimension(0:nprocs), intent(in) istack_merged_intnod) private
Definition at line 140 of file vtk_file_MPI_IO.f90.
References m_calypso_mpi_io::mpi_write_mul_chara_b(), calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by write_vtk_data_mpi(), and write_vtk_mesh_mpi().
write_vtk_mesh_mpi()
subroutine vtk_file_mpi_io::write_vtk_mesh_mpi (integer, intent(in) id_vtk, integer(kind = kint_gl), intent(inout) ioff_gl, integer(kind = kint_gl), intent(in) nnod, integer(kind = kint_gl), intent(in) nele, integer(kind = kint), intent(in) nnod_ele, real(kind = kreal), dimension(nnod,3), intent(in) xx, integer(kind = kint_gl), dimension(nele,nnod_ele), intent(in) ie, integer(kind = kint_gl), dimension(0:nprocs), intent(in) istack_merged_intnod, integer(kind = kint_gl), dimension(0:nprocs), intent(in) istack_merged_ele)
Definition at line 93 of file vtk_file_MPI_IO.f90.
References m_calypso_mpi_io::calypso_mpi_seek_write_head_c(), calypso_mpi::my_rank, m_phys_constants::n_vector, calypso_mpi::nprocs, vtk_data_to_buffer::vtk_cell_type_head(), vtk_data_to_buffer::vtk_connect_head(), vtk_data_to_buffer::vtk_node_head(), write_vtk_celltype_mpi(), write_vtk_connect_mpi(), and write_vtk_field_mpi().
Referenced by merged_udt_vtk_file_io::write_vtk_file_mpi(), and merged_udt_vtk_file_io::write_vtk_grid_mpi().
write_vtk_tensor_mpi()
subroutine, private vtk_file_mpi_io::write_vtk_tensor_mpi (integer, intent(in) id_vtk, integer(kind = kint_gl), intent(inout) ioff_gl, integer(kind = kint_gl), intent(in) nnod, real(kind = kreal), dimension(nnod,6), intent(in) vect, integer(kind = kint_gl), dimension(0:nprocs), intent(in) istack_merged_intnod) private
Definition at line 183 of file vtk_file_MPI_IO.f90.
References m_calypso_mpi_io::mpi_write_mul_chara_b(), calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by write_vtk_data_mpi().