CALYPSO: nod_phys_send_recv Module Reference
nod_phys_send_recv Module Reference
DAta communication for nodal field.
Functions/Subroutines
subroutine init_nod_send_recv (mesh)
subroutine nod_fields_send_recv (mesh, nod_fld)
subroutine init_send_recv (nod_comm)
subroutine fields_send_recv (nod_comm, nod_fld)
subroutine scalar_send_recv (id_phys, nod_comm, nod_fld)
subroutine vector_send_recv (id_phys, nod_comm, nod_fld)
subroutine sym_tensor_send_recv (id_phys, nod_comm, nod_fld)
subroutine nod_scalar_send_recv (numnod, nod_comm, scl_nod)
subroutine nod_vector_send_recv (numnod, nod_comm, vec_nod)
subroutine nod_tensor_send_recv (numnod, nod_comm, tsr_nod)
Detailed Description
DAta communication for nodal field.
      subroutine init_nod_send_recv(mesh)
      subroutine nod_fields_send_recv(mesh, nod_fld)
        type(mesh_geometry), intent(in) :: mesh
        type(phys_data),intent(inout) :: nod_fld
      subroutine init_send_recv(nod_comm)
      subroutine fields_send_recv(nod_comm, nod_fld)
        type(communication_table), intent(in) :: nod_comm
      subroutine scalar_send_recv(id_phys, nod_comm, nod_fld)
      subroutine vector_send_recv(id_phys, nod_comm, nod_fld)
      subroutine sym_tensor_send_recv(id_phys, nod_comm, nod_fld)
        type(node_data), intent(in) :: node
        type(communication_table), intent(in) :: nod_comm
        type(phys_data),intent(inout) :: nod_fld
         id_phys:  field ID of nodal fields
      subroutine nod_scalar_send_recv(numnod, nod_comm, scl_nod)
      subroutine nod_vector_send_recv(numnod, nod_comm, vec_nod)
      subroutine nod_tensor_send_recv(numnod, nod_comm, tsr_nod)
Function/Subroutine Documentation
fields_send_recv()
subroutine nod_phys_send_recv::fields_send_recv (type(communication_table), intent(in) nod_comm, type(phys_data), intent(inout) nod_fld)
Definition at line 98 of file nod_phys_send_recv.f90.
References m_machine_parameter::iflag_debug, m_machine_parameter::iflag_routine_msg, m_phys_constants::n_scalar, m_phys_constants::n_sym_tensor, m_phys_constants::n_vector, scalar_send_recv(), sym_tensor_send_recv(), and vector_send_recv().
Referenced by nod_fields_send_recv().
init_nod_send_recv()
subroutine nod_phys_send_recv::init_nod_send_recv (type(mesh_geometry), intent(in) mesh)
Definition at line 49 of file nod_phys_send_recv.f90.
References init_send_recv().
Referenced by parallel_fem_mesh_init::fem_mesh_initialization().
init_send_recv()
subroutine nod_phys_send_recv::init_send_recv (type(communication_table), intent(in) nod_comm)
Definition at line 77 of file nod_phys_send_recv.f90.
References m_phys_constants::n_sym_tensor, t_solver_sr::resize_work_sr(), m_solver_sr::sr_i1, m_solver_sr::sr_il1, m_solver_sr::sr_r1, and m_solver_sr::sr_sig1.
Referenced by init_nod_send_recv().
nod_fields_send_recv()
subroutine nod_phys_send_recv::nod_fields_send_recv (type(mesh_geometry), intent(in) mesh, type(phys_data), intent(inout) nod_fld)
Definition at line 60 of file nod_phys_send_recv.f90.
References fields_send_recv().
Referenced by fem_analyzer_sph_mhd::fem_analyze_sph_mhd(), load_mesh_and_field_4_viz::set_field_data_4_viz(), t_sph_mhd_zonal_mean_viz::sph_mhd_zonal_mean_section(), and t_sph_mhd_zonal_mean_viz::sph_mhd_zonal_rms_section().
nod_scalar_send_recv()
subroutine nod_phys_send_recv::nod_scalar_send_recv (integer(kind = kint), intent(in) numnod, type(communication_table), intent(in) nod_comm, real(kind = kreal), dimension(numnod), intent(inout) scl_nod)
Definition at line 183 of file nod_phys_send_recv.f90.
References solver_sr_type::solver_send_recv_type(), and m_array_for_send_recv::x_vec.
Referenced by scalar_send_recv().
nod_tensor_send_recv()
subroutine nod_phys_send_recv::nod_tensor_send_recv (integer(kind = kint), intent(in) numnod, type(communication_table), intent(in) nod_comm, real(kind = kreal), dimension(numnod,6), intent(inout) tsr_nod)
Definition at line 248 of file nod_phys_send_recv.f90.
References solver_sr_type::solver_send_recv_6_type(), and m_array_for_send_recv::x_vec.
Referenced by sym_tensor_send_recv().
nod_vector_send_recv()
subroutine nod_phys_send_recv::nod_vector_send_recv (integer(kind = kint), intent(in) numnod, type(communication_table), intent(in) nod_comm, real(kind = kreal), dimension(numnod,3), intent(inout) vec_nod)
Definition at line 214 of file nod_phys_send_recv.f90.
References solver_sr_type::solver_send_recv_3_type(), and m_array_for_send_recv::x_vec.
Referenced by vector_send_recv().
scalar_send_recv()
subroutine nod_phys_send_recv::scalar_send_recv (integer(kind = kint), intent(in) id_phys, type(communication_table), intent(in) nod_comm, type(phys_data), intent(inout) nod_fld)
Definition at line 134 of file nod_phys_send_recv.f90.
References nod_scalar_send_recv().
Referenced by fields_send_recv().
sym_tensor_send_recv()
subroutine nod_phys_send_recv::sym_tensor_send_recv (integer(kind = kint), intent(in) id_phys, type(communication_table), intent(in) nod_comm, type(phys_data), intent(inout) nod_fld)
Definition at line 166 of file nod_phys_send_recv.f90.
References nod_tensor_send_recv().
Referenced by fields_send_recv().
vector_send_recv()
subroutine nod_phys_send_recv::vector_send_recv (integer(kind = kint), intent(in) id_phys, type(communication_table), intent(in) nod_comm, type(phys_data), intent(inout) nod_fld)
Definition at line 150 of file nod_phys_send_recv.f90.
References nod_vector_send_recv().
Referenced by fields_send_recv().