CALYPSO: radial_interpolation Module Reference
radial_interpolation Module Reference
Functions/Subroutines
subroutine const_radial_itp_table (nri_org, r_org, nri_new, radius_1d_rj_r, kr_inside, kr_outside, k_inter, rcoef_inter)
subroutine r_interpolate_sph_vector (i_fld, nidx_rj, nnod_rj, num_phys_rj, ntot_phys_rj, istack_phys_comp_rj, kr_inside, kr_outside, nri_org, k_inter, rcoef_inter, n_rj_org, d_rj_org, d_rj)
subroutine set_org_rj_phys_data_from_io (j_fld, fld_IO, n_rj_org, d_rj_org)
Function/Subroutine Documentation
const_radial_itp_table()
subroutine radial_interpolation::const_radial_itp_table (integer(kind = kint), intent(in) nri_org, real(kind = kreal), dimension(nri_org), intent(in) r_org, integer(kind = kint), intent(in) nri_new, real(kind = kreal), dimension(nri_new), intent(in) radius_1d_rj_r, integer(kind = kint), intent(inout) kr_inside, integer(kind = kint), intent(inout) kr_outside, integer(kind = kint), dimension(nri_org,2), intent(inout) k_inter, real (kind=kreal), dimension(nri_org,2), intent(inout) rcoef_inter)
Definition at line 34 of file radial_interpolation.f90.
References m_constants::one, and m_constants::zero.
Referenced by r_interpolate_sph_data::input_old_rj_sph_trans().
r_interpolate_sph_vector()
subroutine radial_interpolation::r_interpolate_sph_vector (integer(kind = kint), intent(in) i_fld, integer(kind = kint), dimension(2), intent(in) nidx_rj, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) num_phys_rj, integer(kind = kint), intent(in) ntot_phys_rj, integer(kind = kint), dimension(0:num_phys_rj), intent(in) istack_phys_comp_rj, integer(kind = kint), intent(in) kr_inside, integer(kind = kint), intent(in) kr_outside, integer(kind = kint), intent(in) nri_org, integer(kind = kint), dimension(nri_org,2), intent(in) k_inter, real (kind=kreal), dimension(nri_org,2), intent(in) rcoef_inter, integer(kind = kint), intent(in) n_rj_org, real (kind=kreal), dimension(n_rj_org,6), intent(in) d_rj_org, real (kind=kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 88 of file radial_interpolation.f90.
References m_constants::zero.
Referenced by r_interpolate_sph_data::r_interpolate_sph_fld_from_io(), and r_interpolate_sph_data::r_interpolate_sph_rst_from_io().
set_org_rj_phys_data_from_io()
subroutine radial_interpolation::set_org_rj_phys_data_from_io (integer(kind = kint), intent(in) j_fld, type(field_io), intent(in) fld_IO, integer(kind = kint), intent(in) n_rj_org, real (kind=kreal), dimension(n_rj_org,6), intent(inout) d_rj_org)
Definition at line 151 of file radial_interpolation.f90.
Referenced by r_interpolate_sph_data::r_interpolate_sph_fld_from_io(), and r_interpolate_sph_data::r_interpolate_sph_rst_from_io().