CALYPSO: gz_mpi_sph_modes_data_io_b Module Reference
gz_mpi_sph_modes_data_io_b Module Reference
ASCII spectr data IO routines.
Functions/Subroutines
subroutine gz_mpi_read_geom_rtp_data_b (IO_param, comm_IO, sph_IO, sph_grps_IO)
subroutine gz_mpi_read_spectr_rj_data_b (IO_param, comm_IO, sph_IO, sph_grps_IO)
subroutine gz_mpi_read_geom_rtm_data_b (IO_param, comm_IO, sph_IO)
subroutine gz_mpi_read_modes_rlm_data_b (IO_param, comm_IO, sph_IO)
subroutine gz_mpi_write_geom_rtp_data_b (IO_param, comm_IO, sph_IO, sph_grps_IO)
subroutine gz_mpi_write_spectr_rj_data_b (IO_param, comm_IO, sph_IO, sph_grps_IO)
subroutine gz_mpi_write_geom_rtm_data_b (IO_param, comm_IO, sph_IO)
subroutine gz_mpi_write_modes_rlm_data_b (IO_param, comm_IO, sph_IO)
Detailed Description
ASCII spectr data IO routines.
      subroutine gz_mpi_read_geom_rtp_data_b                          &
     &         (IO_param, comm_IO, sph_IO, sph_grps_IO)
      subroutine gz_mpi_read_spectr_rj_data_b                         &
     &         (IO_param, comm_IO, sph_IO, sph_grps_IO)
      subroutine gz_mpi_read_geom_rtm_data_b                          &
     &         (IO_param, comm_IO, sph_IO)
      subroutine gz_mpi_read_modes_rlm_data_b                         &
     &         (IO_param, comm_IO, sph_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(communication_table), intent(inout) :: comm_IO
        type(sph_IO_data), intent(inout) :: sph_IO
        type(sph_group_data), intent(inout) :: sph_grps_IO
      subroutine gz_mpi_write_geom_rtp_data_b                         &
     &         (IO_param, comm_IO, sph_IO, sph_grps_IO)
      subroutine gz_mpi_write_spectr_rj_data_b                        &
     &         (IO_param, comm_IO, sph_IO, sph_grps_IO)
      subroutine gz_mpi_write_geom_rtm_data_b                         &
     &         (IO_param, comm_IO, sph_IO)
      subroutine gz_mpi_write_modes_rlm_data_b                        &
     &         (IO_param, comm_IO, sph_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(communication_table), intent(in) :: comm_IO
        type(sph_IO_data), intent(in) :: sph_IO
        type(sph_group_data), intent(in) :: sph_grps_IO
Function/Subroutine Documentation
gz_mpi_read_geom_rtm_data_b()
subroutine gz_mpi_sph_modes_data_io_b::gz_mpi_read_geom_rtm_data_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(inout) comm_IO, type(sph_io_data), intent(inout) sph_IO)
Definition at line 122 of file gz_MPI_sph_modes_data_IO_b.f90.
References gz_mpi_domain_data_io_b::gz_mpi_read_domain_info_b(), gz_mpi_spherical_model_io_b::gz_mpi_read_gl_nodes_sph_b(), gz_mpi_spherical_model_io_b::gz_mpi_read_gl_reso_sph_b(), gz_mpi_domain_data_io_b::gz_mpi_read_import_data_b(), gz_mpi_spherical_model_io_b::gz_mpi_read_rank_4_sph_b(), and gz_mpi_sph_gl_1d_idx_io_b::gz_mpi_read_rtp_gl_1d_table_b().
Referenced by gz_mpi_sph_modes_file_io_b::gz_mpi_read_geom_rtm_file_b().
gz_mpi_read_geom_rtp_data_b()
subroutine gz_mpi_sph_modes_data_io_b::gz_mpi_read_geom_rtp_data_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(inout) comm_IO, type(sph_io_data), intent(inout) sph_IO, type(sph_group_data), intent(inout) sph_grps_IO)
Definition at line 60 of file gz_MPI_sph_modes_data_IO_b.f90.
References gz_mpi_domain_data_io_b::gz_mpi_read_domain_info_b(), gz_mpi_spherical_model_io_b::gz_mpi_read_gl_nodes_sph_b(), gz_mpi_spherical_model_io_b::gz_mpi_read_gl_reso_sph_b(), gz_mpi_groups_io_b::gz_mpi_read_group_data_b(), gz_mpi_domain_data_io_b::gz_mpi_read_import_data_b(), gz_mpi_spherical_model_io_b::gz_mpi_read_rank_4_sph_b(), and gz_mpi_sph_gl_1d_idx_io_b::gz_mpi_read_rtp_gl_1d_table_b().
Referenced by gz_mpi_sph_modes_file_io_b::gz_mpi_read_geom_rtp_file_b().
gz_mpi_read_modes_rlm_data_b()
subroutine gz_mpi_sph_modes_data_io_b::gz_mpi_read_modes_rlm_data_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(inout) comm_IO, type(sph_io_data), intent(inout) sph_IO)
Definition at line 145 of file gz_MPI_sph_modes_data_IO_b.f90.
References gz_mpi_domain_data_io_b::gz_mpi_read_domain_info_b(), gz_mpi_spherical_model_io_b::gz_mpi_read_gl_nodes_sph_b(), gz_mpi_spherical_model_io_b::gz_mpi_read_gl_reso_sph_b(), gz_mpi_domain_data_io_b::gz_mpi_read_import_data_b(), gz_mpi_spherical_model_io_b::gz_mpi_read_rank_4_sph_b(), and gz_mpi_sph_gl_1d_idx_io_b::gz_mpi_read_rj_gl_1d_table_b().
Referenced by gz_mpi_sph_modes_file_io_b::gz_mpi_read_modes_rlm_file_b().
gz_mpi_read_spectr_rj_data_b()
subroutine gz_mpi_sph_modes_data_io_b::gz_mpi_read_spectr_rj_data_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(inout) comm_IO, type(sph_io_data), intent(inout) sph_IO, type(sph_group_data), intent(inout) sph_grps_IO)
Definition at line 93 of file gz_MPI_sph_modes_data_IO_b.f90.
References gz_mpi_domain_data_io_b::gz_mpi_read_domain_info_b(), gz_mpi_spherical_model_io_b::gz_mpi_read_gl_nodes_sph_b(), gz_mpi_spherical_model_io_b::gz_mpi_read_gl_reso_sph_b(), gz_mpi_groups_io_b::gz_mpi_read_group_data_b(), gz_mpi_domain_data_io_b::gz_mpi_read_import_data_b(), gz_mpi_spherical_model_io_b::gz_mpi_read_rank_4_sph_b(), and gz_mpi_sph_gl_1d_idx_io_b::gz_mpi_read_rj_gl_1d_table_b().
Referenced by gz_mpi_sph_modes_file_io_b::gz_mpi_read_spectr_rj_file_b().
gz_mpi_write_geom_rtm_data_b()
subroutine gz_mpi_sph_modes_data_io_b::gz_mpi_write_geom_rtm_data_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(in) comm_IO, type(sph_io_data), intent(in) sph_IO)
Definition at line 229 of file gz_MPI_sph_modes_data_IO_b.f90.
References gz_mpi_domain_data_io_b::gz_mpi_write_domain_info_b(), gz_mpi_spherical_model_io_b::gz_mpi_write_gl_nodes_sph_b(), gz_mpi_spherical_model_io_b::gz_mpi_write_gl_reso_sph_b(), gz_mpi_domain_data_io_b::gz_mpi_write_import_data_b(), gz_mpi_spherical_model_io_b::gz_mpi_write_rank_4_sph_b(), and gz_mpi_sph_gl_1d_idx_io_b::gz_mpi_write_rtp_gl_1d_table_b().
Referenced by gz_mpi_sph_modes_file_io_b::gz_mpi_write_geom_rtm_file_b().
gz_mpi_write_geom_rtp_data_b()
subroutine gz_mpi_sph_modes_data_io_b::gz_mpi_write_geom_rtp_data_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(in) comm_IO, type(sph_io_data), intent(in) sph_IO, type(sph_group_data), intent(in) sph_grps_IO)
Definition at line 169 of file gz_MPI_sph_modes_data_IO_b.f90.
References gz_mpi_domain_data_io_b::gz_mpi_write_domain_info_b(), gz_mpi_spherical_model_io_b::gz_mpi_write_gl_nodes_sph_b(), gz_mpi_spherical_model_io_b::gz_mpi_write_gl_reso_sph_b(), gz_mpi_groups_io_b::gz_mpi_write_grp_data_b(), gz_mpi_domain_data_io_b::gz_mpi_write_import_data_b(), gz_mpi_spherical_model_io_b::gz_mpi_write_rank_4_sph_b(), and gz_mpi_sph_gl_1d_idx_io_b::gz_mpi_write_rtp_gl_1d_table_b().
Referenced by gz_mpi_sph_modes_file_io_b::gz_mpi_write_geom_rtp_file_b().
gz_mpi_write_modes_rlm_data_b()
subroutine gz_mpi_sph_modes_data_io_b::gz_mpi_write_modes_rlm_data_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(in) comm_IO, type(sph_io_data), intent(in) sph_IO)
Definition at line 251 of file gz_MPI_sph_modes_data_IO_b.f90.
References gz_mpi_domain_data_io_b::gz_mpi_write_domain_info_b(), gz_mpi_spherical_model_io_b::gz_mpi_write_gl_nodes_sph_b(), gz_mpi_spherical_model_io_b::gz_mpi_write_gl_reso_sph_b(), gz_mpi_domain_data_io_b::gz_mpi_write_import_data_b(), gz_mpi_spherical_model_io_b::gz_mpi_write_rank_4_sph_b(), and gz_mpi_sph_gl_1d_idx_io_b::gz_mpi_write_rj_gl_1d_table_b().
Referenced by gz_mpi_sph_modes_file_io_b::gz_mpi_write_modes_rlm_file_b().
gz_mpi_write_spectr_rj_data_b()
subroutine gz_mpi_sph_modes_data_io_b::gz_mpi_write_spectr_rj_data_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(in) comm_IO, type(sph_io_data), intent(in) sph_IO, type(sph_group_data), intent(in) sph_grps_IO)
Definition at line 201 of file gz_MPI_sph_modes_data_IO_b.f90.
References gz_mpi_domain_data_io_b::gz_mpi_write_domain_info_b(), gz_mpi_spherical_model_io_b::gz_mpi_write_gl_nodes_sph_b(), gz_mpi_spherical_model_io_b::gz_mpi_write_gl_reso_sph_b(), gz_mpi_groups_io_b::gz_mpi_write_grp_data_b(), gz_mpi_domain_data_io_b::gz_mpi_write_import_data_b(), gz_mpi_spherical_model_io_b::gz_mpi_write_rank_4_sph_b(), and gz_mpi_sph_gl_1d_idx_io_b::gz_mpi_write_rj_gl_1d_table_b().
Referenced by gz_mpi_sph_modes_file_io_b::gz_mpi_write_spectr_rj_file_b().