CALYPSO: gz_domain_data_io Module Reference
gz_domain_data_io Module Reference
Routine for doimain data IO using zlib.
Functions/Subroutines
subroutine gz_read_domain_info (id_rank, comm_IO, zbuf, ierr)
subroutine gz_read_import_data (comm_IO, zbuf)
subroutine gz_read_export_data (comm_IO, zbuf)
subroutine gz_write_domain_info (id_rank, comm_IO, zbuf)
subroutine gz_write_import_data (comm_IO, zbuf)
subroutine gz_write_export_data (comm_IO, zbuf)
subroutine, private read_send_recv_item_gz (ntot_sr, inod_sr, zbuf)
subroutine, private write_send_recv_data_gz (num_sr, ntot_sr, istack_sr, inod_sr, zbuf)
Detailed Description
Routine for doimain data IO using zlib.
      subroutine gz_read_domain_info(id_rank, comm_IO, zbuf, ierr)
      subroutine gz_read_import_data(comm_IO, zbuf)
      subroutine gz_read_export_data(comm_IO, zbuf)
        type(communication_table), intent(inout) :: comm_IO
        type(buffer_4_gzip) , intent(inout):: zbuf
      subroutine gz_write_domain_info(id_rank, comm_IO, zbuf)
      subroutine gz_write_import_data(comm_IO, zbuf)
      subroutine gz_write_export_data(comm_IO, zbuf)
        type(communication_table), intent(in) :: comm_IO
        type(buffer_4_gzip) , intent(inout):: zbuf
Function/Subroutine Documentation
gz_read_domain_info()
subroutine gz_domain_data_io::gz_read_domain_info (integer, intent(in) id_rank, type(communication_table), intent(inout) comm_IO, type(buffer_4_gzip), intent(inout) zbuf, integer(kind = kint), intent(inout) ierr)
Definition at line 40 of file gz_domain_data_IO.f90.
References t_comm_table::alloc_neighbouring_id(), gzip_file_access::get_one_line_text_from_gz(), m_error_ids::ierr_mesh, gz_data_io::read_gz_multi_int(), and skip_gz_comment::skip_gz_comment_int().
Referenced by gz_edge_data_io::gz_read_edge_connection(), gz_element_data_io::gz_read_element_comm_table(), gz_mesh_data_io::gz_read_filter_geometry(), gz_mesh_data_io::gz_read_num_node(), gz_surface_data_io::gz_read_surface_connection(), gz_sph_modes_grids_data_io::read_geom_rtm_data_gz(), gz_sph_modes_grids_data_io::read_geom_rtp_data_gz(), gz_sph_modes_grids_data_io::read_spectr_modes_rj_data_gz(), and gz_sph_modes_grids_data_io::read_spectr_modes_rlm_data_gz().
gz_read_export_data()
subroutine gz_domain_data_io::gz_read_export_data (type(communication_table), intent(inout) comm_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 105 of file gz_domain_data_IO.f90.
References t_comm_table::alloc_export_item(), t_comm_table::alloc_export_num(), gz_data_io::read_gz_integer_stack(), and read_send_recv_item_gz().
Referenced by gz_edge_data_io::gz_read_edge_connection(), gz_element_data_io::gz_read_element_comm_table(), gz_mesh_data_io::gz_read_filter_geometry(), gz_mesh_data_io::gz_read_geometry_data(), and gz_surface_data_io::gz_read_surface_connection().
gz_read_import_data()
subroutine gz_domain_data_io::gz_read_import_data (type(communication_table), intent(inout) comm_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 78 of file gz_domain_data_IO.f90.
References t_comm_table::alloc_import_item(), t_comm_table::alloc_import_num(), gz_data_io::read_gz_integer_stack(), and read_send_recv_item_gz().
Referenced by gz_edge_data_io::gz_read_edge_connection(), gz_element_data_io::gz_read_element_comm_table(), gz_mesh_data_io::gz_read_filter_geometry(), gz_mesh_data_io::gz_read_geometry_data(), gz_surface_data_io::gz_read_surface_connection(), gz_sph_modes_grids_data_io::read_geom_rtm_data_gz(), gz_sph_modes_grids_data_io::read_geom_rtp_data_gz(), gz_sph_modes_grids_data_io::read_spectr_modes_rj_data_gz(), and gz_sph_modes_grids_data_io::read_spectr_modes_rlm_data_gz().
gz_write_domain_info()
subroutine gz_domain_data_io::gz_write_domain_info (integer, intent(in) id_rank, type(communication_table), intent(in) comm_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 133 of file gz_domain_data_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf(), and gz_data_io::write_gz_multi_int_8i16().
Referenced by gz_edge_data_io::gz_write_edge_connection(), gz_element_data_io::gz_write_element_comm_table(), gz_mesh_data_io::gz_write_filter_geometry(), gz_mesh_data_io::gz_write_geometry_data(), gz_surface_data_io::gz_write_surface_connection(), gz_sph_modes_grids_data_io::write_geom_rtm_data_gz(), gz_sph_modes_grids_data_io::write_geom_rtp_data_gz(), gz_sph_modes_grids_data_io::write_modes_rlm_data_gz(), and gz_sph_modes_grids_data_io::write_spectr_modes_rj_data_gz().
gz_write_export_data()
subroutine gz_domain_data_io::gz_write_export_data (type(communication_table), intent(in) comm_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 176 of file gz_domain_data_IO.f90.
References write_send_recv_data_gz().
Referenced by gz_edge_data_io::gz_write_edge_connection(), gz_element_data_io::gz_write_element_comm_table(), gz_mesh_data_io::gz_write_filter_geometry(), gz_mesh_data_io::gz_write_geometry_data(), and gz_surface_data_io::gz_write_surface_connection().
gz_write_import_data()
subroutine gz_domain_data_io::gz_write_import_data (type(communication_table), intent(in) comm_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 162 of file gz_domain_data_IO.f90.
References write_send_recv_data_gz().
Referenced by gz_edge_data_io::gz_write_edge_connection(), gz_element_data_io::gz_write_element_comm_table(), gz_mesh_data_io::gz_write_filter_geometry(), gz_mesh_data_io::gz_write_geometry_data(), gz_surface_data_io::gz_write_surface_connection(), gz_sph_modes_grids_data_io::write_geom_rtm_data_gz(), gz_sph_modes_grids_data_io::write_geom_rtp_data_gz(), gz_sph_modes_grids_data_io::write_modes_rlm_data_gz(), and gz_sph_modes_grids_data_io::write_spectr_modes_rj_data_gz().
read_send_recv_item_gz()
subroutine, private gz_domain_data_io::read_send_recv_item_gz (integer(kind = kint), intent(in) ntot_sr, integer(kind = kint), dimension(ntot_sr), intent(inout) inod_sr, type(buffer_4_gzip), intent(inout) zbuf) private
Definition at line 191 of file gz_domain_data_IO.f90.
References gzip_file_access::get_one_line_text_from_gz(), and skip_gz_comment::skip_gz_comment_int().
Referenced by gz_read_export_data(), and gz_read_import_data().
write_send_recv_data_gz()
subroutine, private gz_domain_data_io::write_send_recv_data_gz (integer(kind = kint), intent(in) num_sr, integer(kind = kint), intent(in) ntot_sr, integer(kind = kint), dimension(0:num_sr), intent(in) istack_sr, integer(kind = kint), dimension(ntot_sr), intent(in) inod_sr, type(buffer_4_gzip), intent(inout) zbuf) private
Definition at line 212 of file gz_domain_data_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf(), and gz_data_io::write_gz_multi_int_8i16().
Referenced by gz_write_export_data(), and gz_write_import_data().