CALYPSO: cal_add_smp Module Reference
cal_add_smp Module Reference
Functions/Subroutines
subroutine add_scalars_smp (nnod, scalar1, scalar2, added)
subroutine add_vectors_smp (nnod, vector1, vector2, added)
subroutine add_tensors_smp (nnod, tensor1, tensor2, added)
subroutine add_const_to_scalar_smp (nnod, scalar, const, added)
subroutine add_const_to_vector_smp (nnod, vector, const, added)
subroutine add_const_to_tensor_smp (nnod, tensor, const, added)
subroutine add_const_to_scalar_smp_ow (nnod, scalar, const)
subroutine add_const_to_vector_smp_ow (nnod, vector, const)
subroutine add_const_to_tensor_smp_ow (nnod, tensor, const)
Function/Subroutine Documentation
add_const_to_scalar_smp()
subroutine cal_add_smp::add_const_to_scalar_smp (integer (kind=kint), intent(in) nnod, real (kind=kreal), dimension(nnod), intent(in) scalar, real (kind=kreal), intent(in) const, real (kind=kreal), dimension(nnod), intent(inout) added)
Definition at line 109 of file cal_add_smp.f90.
add_const_to_scalar_smp_ow()
subroutine cal_add_smp::add_const_to_scalar_smp_ow (integer (kind=kint), intent(in) nnod, real (kind=kreal), dimension(nnod), intent(inout) scalar, real (kind=kreal), intent(in) const)
Definition at line 164 of file cal_add_smp.f90.
add_const_to_tensor_smp()
subroutine cal_add_smp::add_const_to_tensor_smp (integer (kind=kint), intent(in) nnod, real (kind=kreal), dimension(nnod,6), intent(in) tensor, real (kind=kreal), dimension(6), intent(in) const, real (kind=kreal), dimension(nnod,6), intent(inout) added)
Definition at line 143 of file cal_add_smp.f90.
add_const_to_tensor_smp_ow()
subroutine cal_add_smp::add_const_to_tensor_smp_ow (integer (kind=kint), intent(in) nnod, real (kind=kreal), dimension(nnod,6), intent(inout) tensor, real (kind=kreal), dimension(6), intent(in) const)
Definition at line 198 of file cal_add_smp.f90.
add_const_to_vector_smp()
subroutine cal_add_smp::add_const_to_vector_smp (integer (kind=kint), intent(in) nnod, real (kind=kreal), dimension(nnod,3), intent(in) vector, real (kind=kreal), dimension(3), intent(in) const, real (kind=kreal), dimension(nnod,3), intent(inout) added)
Definition at line 125 of file cal_add_smp.f90.
add_const_to_vector_smp_ow()
subroutine cal_add_smp::add_const_to_vector_smp_ow (integer (kind=kint), intent(in) nnod, real (kind=kreal), dimension(nnod,3), intent(inout) vector, real (kind=kreal), dimension(3), intent(in) const)
Definition at line 180 of file cal_add_smp.f90.
add_scalars_smp()
subroutine cal_add_smp::add_scalars_smp (integer (kind=kint), intent(in) nnod, real (kind=kreal), dimension(nnod), intent(in) scalar1, real (kind=kreal), dimension(nnod), intent(in) scalar2, real (kind=kreal), dimension(nnod), intent(inout) added)
Definition at line 53 of file cal_add_smp.f90.
Referenced by copy_nodal_fields::add_2_nod_scalars().
add_tensors_smp()
subroutine cal_add_smp::add_tensors_smp (integer (kind=kint), intent(in) nnod, real (kind=kreal), dimension(nnod,6), intent(in) tensor1, real (kind=kreal), dimension(nnod,6), intent(in) tensor2, real (kind=kreal), dimension(nnod,6), intent(inout) added)
Definition at line 87 of file cal_add_smp.f90.
Referenced by copy_nodal_fields::add_2_nod_tensors().
add_vectors_smp()
subroutine cal_add_smp::add_vectors_smp (integer (kind=kint), intent(in) nnod, real (kind=kreal), dimension(nnod,3), intent(in) vector1, real (kind=kreal), dimension(nnod,3), intent(in) vector2, real (kind=kreal), dimension(nnod,3), intent(inout) added)
Definition at line 69 of file cal_add_smp.f90.
Referenced by copy_nodal_fields::add_2_nod_vectors().