CALYPSO: t_psf_geometry_list Module Reference
t_psf_geometry_list Module Reference
Structure for cross sectioning data.
Data Types
type grp_section_list
Structure for cross sectioning by surface group list.
type psf_search_lists
Structure for search list for sectioning.
type sect_search_list
Structure for search list for surfacing.
type sectioning_list
Structure for cross sectioning list.
Functions/Subroutines
subroutine alloc_num_psf_search_list (np_smp, list)
subroutine alloc_psf_search_list (list)
subroutine alloc_mark_ele_psf (search)
subroutine dealloc_num_psf_search_list (list)
subroutine dealloc_psf_search_list (list)
subroutine dealloc_mark_ele_psf (search)
subroutine alloc_ref_field_4_psf (node, psf_list)
subroutine alloc_nnod_psf (np_smp, edge, psf_list)
subroutine alloc_iedge_global_psf (psf_list)
subroutine alloc_inod_psf (psf_list)
subroutine alloc_nnod_grp_psf (np_smp, node, psf_g_list)
subroutine alloc_inod_grp_psf (psf_g_list)
subroutine dealloc_ref_field_4_psf (psf_list)
subroutine dealloc_nnod_psf (psf_list)
subroutine dealloc_iedge_global_psf (psf_list)
subroutine dealloc_inod_psf (psf_list)
subroutine dealloc_inod_grp_psf (psf_g_list)
Detailed Description
Structure for cross sectioning data.
      subroutine alloc_num_psf_search_list(np_smp, list)
      subroutine alloc_psf_search_list(list)
      subroutine alloc_mark_ele_psf(search)
      subroutine dealloc_num_psf_search_list(list)
      subroutine dealloc_psf_search_list(list)
      subroutine dealloc_mark_ele_psf(search)
      subroutine alloc_ref_field_4_psf(node, psf_list)
       type(node_data), intent(in) :: node
      subroutine alloc_nnod_psf(np_smp, edge, psf_list)
      subroutine alloc_iedge_global_psf(psf_list)
        type(edge_data), intent(in) :: edge
      subroutine alloc_inod_psf(psf_list)
      subroutine alloc_nnod_grp_psf(np_smp, node, psf_g_list)
       type(node_data), intent(in) :: node
      subroutine alloc_inod_grp_psf(psf_g_list)
      subroutine dealloc_ref_field_4_psf(psf_list)
      subroutine dealloc_nnod_psf(psf_list)
      subroutine dealloc_iedge_global_psf(psf_list)
      subroutine dealloc_inod_psf(psf_list)
      subroutine dealloc_inod_grp_psf(psf_g_list)
Function/Subroutine Documentation
alloc_iedge_global_psf()
subroutine t_psf_geometry_list::alloc_iedge_global_psf (type(sectioning_list), intent(inout) psf_list)
Definition at line 240 of file t_psf_geometry_list.f90.
Referenced by set_nodes_for_psf::set_nodes_4_iso(), and set_nodes_for_psf::set_nodes_4_psf().
alloc_inod_grp_psf()
subroutine t_psf_geometry_list::alloc_inod_grp_psf (type(grp_section_list), intent(inout) psf_g_list)
Definition at line 293 of file t_psf_geometry_list.f90.
Referenced by find_node_and_patch_psf::set_node_and_patch_psf().
alloc_inod_psf()
subroutine t_psf_geometry_list::alloc_inod_psf (type(sectioning_list), intent(inout) psf_list)
Definition at line 252 of file t_psf_geometry_list.f90.
References m_constants::zero.
Referenced by find_node_and_patch_psf::set_node_and_patch_psf(), and set_nodes_for_psf::set_nodes_4_iso().
alloc_mark_ele_psf()
subroutine t_psf_geometry_list::alloc_mark_ele_psf (type(psf_search_lists), intent(inout) search)
Definition at line 156 of file t_psf_geometry_list.f90.
Referenced by set_patches_for_psf::count_iso_patches(), and set_patches_for_psf::count_psf_patches().
alloc_nnod_grp_psf()
subroutine t_psf_geometry_list::alloc_nnod_grp_psf (integer(kind= kint), intent(in) np_smp, type(node_data), intent(in) node, type(grp_section_list), intent(inout) psf_g_list)
Definition at line 272 of file t_psf_geometry_list.f90.
Referenced by find_node_and_patch_psf::set_node_and_patch_psf().
alloc_nnod_psf()
subroutine t_psf_geometry_list::alloc_nnod_psf (integer(kind= kint), intent(in) np_smp, type(edge_data), intent(in) edge, type(sectioning_list), intent(inout) psf_list)
Definition at line 219 of file t_psf_geometry_list.f90.
Referenced by set_nodes_for_psf::count_nodes_4_iso(), and find_node_and_patch_psf::set_node_and_patch_psf().
alloc_num_psf_search_list()
subroutine t_psf_geometry_list::alloc_num_psf_search_list (integer(kind = kint), intent(in) np_smp, type(sect_search_list), intent(inout) list)
Definition at line 131 of file t_psf_geometry_list.f90.
Referenced by search_ele_list_for_psf::set_searched_edge_list_4_psf(), search_ele_list_for_psf::set_searched_element_list_4_psf(), search_ele_list_for_psf::set_searched_node_list_4_psf(), and search_ele_list_for_psf::set_searched_surface_list_4_psf().
alloc_psf_search_list()
subroutine t_psf_geometry_list::alloc_psf_search_list (type(sect_search_list), intent(inout) list)
Definition at line 144 of file t_psf_geometry_list.f90.
Referenced by search_ele_list_for_psf::set_searched_edge_list_4_psf(), search_ele_list_for_psf::set_searched_element_list_4_psf(), search_ele_list_for_psf::set_searched_node_list_4_psf(), and search_ele_list_for_psf::set_searched_surface_list_4_psf().
alloc_ref_field_4_psf()
subroutine t_psf_geometry_list::alloc_ref_field_4_psf (type(node_data), intent(in) node, type(sectioning_list), intent(inout) psf_list)
Definition at line 203 of file t_psf_geometry_list.f90.
Referenced by t_cross_section::sectioning_initialize().
dealloc_iedge_global_psf()
subroutine t_psf_geometry_list::dealloc_iedge_global_psf (type(sectioning_list), intent(inout) psf_list)
Definition at line 333 of file t_psf_geometry_list.f90.
References t_comm_table::dealloc_comm_table().
Referenced by set_nodes_for_psf::set_nodes_4_iso(), and set_nodes_for_psf::set_nodes_4_psf().
dealloc_inod_grp_psf()
subroutine t_psf_geometry_list::dealloc_inod_grp_psf (type(grp_section_list), intent(inout) psf_g_list)
Definition at line 357 of file t_psf_geometry_list.f90.
Referenced by t_cross_section::dealloc_psf_field_type().
dealloc_inod_psf()
subroutine t_psf_geometry_list::dealloc_inod_psf (type(sectioning_list), intent(inout) psf_list)
Definition at line 345 of file t_psf_geometry_list.f90.
Referenced by find_node_and_patch_psf::dealloc_psf_node_and_patch().
dealloc_mark_ele_psf()
subroutine t_psf_geometry_list::dealloc_mark_ele_psf (type(psf_search_lists), intent(inout) search)
Definition at line 191 of file t_psf_geometry_list.f90.
Referenced by find_node_and_patch_psf::set_node_and_patch_iso(), and find_node_and_patch_psf::set_node_and_patch_psf().
dealloc_nnod_psf()
subroutine t_psf_geometry_list::dealloc_nnod_psf (type(sectioning_list), intent(inout) psf_list)
Definition at line 320 of file t_psf_geometry_list.f90.
Referenced by find_node_and_patch_psf::dealloc_psf_node_and_patch().
dealloc_num_psf_search_list()
subroutine t_psf_geometry_list::dealloc_num_psf_search_list (type(sect_search_list), intent(inout) list)
Definition at line 169 of file t_psf_geometry_list.f90.
dealloc_psf_search_list()
subroutine t_psf_geometry_list::dealloc_psf_search_list (type(sect_search_list), intent(inout) list)
Definition at line 180 of file t_psf_geometry_list.f90.
dealloc_ref_field_4_psf()
subroutine t_psf_geometry_list::dealloc_ref_field_4_psf (type(sectioning_list), intent(inout) psf_list)
Definition at line 309 of file t_psf_geometry_list.f90.