CALYPSO: mpi_surface_data_io_b Module Reference
mpi_surface_data_io_b Module Reference
routines for surface mesh data IO
Functions/Subroutines
subroutine mpi_read_surface_connection_b (IO_param, comm_IO, ele_IO, sfed_IO)
subroutine mpi_write_surface_connection_b (IO_param, comm_IO, ele_IO, sfed_IO)
subroutine mpi_read_surface_geometry_b (IO_param, nod_IO, sfed_IO)
subroutine mpi_write_surface_geometry_b (IO_param, nod_IO, sfed_IO)
Detailed Description
routines for surface mesh data IO
      subroutine mpi_read_surface_connection_b                        &
     &         (IO_param, comm_IO, ele_IO, sfed_IO)
        type(communication_table), intent(inout) :: comm_IO
        type(node_data), intent(inout) :: nod_IO
        type(element_data), intent(inout) :: ele_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
      subroutine mpi_write_surface_connection_b                       &
     &         (IO_param, comm_IO, ele_IO, sfed_IO)
        type(communication_table), intent(inout) :: comm_IO
        type(node_data), intent(in) :: nod_IO
        type(element_data), intent(in) :: ele_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
      subroutine mpi_read_surface_geometry_b                          &
     &         (IO_param, nod_IO, sfed_IO)
        type(communication_table), intent(inout) :: comm_IO
        type(node_data), intent(inout) :: nod_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
      subroutine mpi_write_surface_geometry_b                         &
     &         (IO_param, nod_IO, sfed_IO)
        type(communication_table), intent(inout) :: comm_IO
        type(node_data), intent(in) :: nod_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
Function/Subroutine Documentation
mpi_read_surface_connection_b()
subroutine mpi_surface_data_io_b::mpi_read_surface_connection_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(inout) comm_IO, type(element_data), intent(inout) ele_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 57 of file MPI_surface_data_IO_b.f90.
References mpi_domain_data_io_b::mpi_read_domain_info_b(), mpi_element_connect_io_b::mpi_read_element_info_b(), mpi_domain_data_io_b::mpi_read_export_data_b(), mpi_domain_data_io_b::mpi_read_import_data_b(), mpi_element_connect_io_b::mpi_read_number_of_element_b(), and mpi_element_connect_io_b::mpi_read_surface_4_element_b().
Referenced by mpi_element_file_io_b::mpi_input_surface_file_b().
mpi_read_surface_geometry_b()
subroutine mpi_surface_data_io_b::mpi_read_surface_geometry_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 107 of file MPI_surface_data_IO_b.f90.
References mpi_node_geometry_io_b::mpi_read_geometry_info_b(), mpi_node_geometry_io_b::mpi_read_number_of_node_b(), mpi_node_geometry_io_b::mpi_read_scl_in_ele_b(), and mpi_node_geometry_io_b::mpi_read_vect_in_ele_b().
mpi_write_surface_connection_b()
subroutine mpi_surface_data_io_b::mpi_write_surface_connection_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(in) comm_IO, type(element_data), intent(in) ele_IO, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 83 of file MPI_surface_data_IO_b.f90.
References mpi_domain_data_io_b::mpi_write_domain_info_b(), mpi_element_connect_io_b::mpi_write_element_info_b(), mpi_domain_data_io_b::mpi_write_export_data_b(), mpi_domain_data_io_b::mpi_write_import_data_b(), and mpi_element_connect_io_b::mpi_write_surface_4_element_b().
Referenced by mpi_element_file_io_b::mpi_output_surface_file_b().
mpi_write_surface_geometry_b()
subroutine mpi_surface_data_io_b::mpi_write_surface_geometry_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 126 of file MPI_surface_data_IO_b.f90.
References mpi_node_geometry_io_b::mpi_write_geometry_info_b(), mpi_node_geometry_io_b::mpi_write_scl_in_ele_b(), and mpi_node_geometry_io_b::mpi_write_vect_in_ele_b().