CALYPSO: set_address_sph_trans_mhd Module Reference
set_address_sph_trans_mhd Module Reference
Field addresses for spherical harmonics transform in MHD dynamo simulation.
Functions/Subroutines
subroutine set_addresses_trans_sph_mhd (d_rj, ipol, iphys, trns_MHD, ncomp_sph_trans, nvector_sph_trans, nscalar_sph_trans)
subroutine mhd_spectr_to_sendbuf (backward, comm_rj, rj_fld, n_WS, WS)
subroutine mhd_spectr_to_sendbuf_wpole (nnod_pole, sph_rj, comm_rj, rj_fld, n_WS, WS, backward)
subroutine mhd_spectr_from_recvbuf (iflag_recv, forward, comm_rj, n_WR, WR, rj_fld)
Detailed Description
Field addresses for spherical harmonics transform in MHD dynamo simulation.
      subroutine set_addresses_trans_sph_MHD                          &
 !     &         (MHD_prop, d_rj, ipol, iphys, trns_MHD,              &
     &         (d_rj, ipol, iphys, trns_MHD,                          &
     &          ncomp_sph_trans, nvector_sph_trans, nscalar_sph_trans)
        type(MHD_evolution_param), intent(in) :: MHD_prop
        type(phys_data), intent(in) :: d_rj
        type(phys_address), intent(in) :: ipol, iphys
        type(address_4_sph_trans), intent(inout) :: trns_MHD
      subroutine mhd_spectr_to_sendbuf                                &
     &         (backward, comm_rj, rj_fld, n_WS, WS)
        type(spherical_transform_data), intent(in) :: backward
        type(sph_comm_tbl), intent(in) :: comm_rj
        type(phys_data), intent(in) :: rj_fld
      subroutine mhd_spectr_to_sendbuf_wpole(nnod_pole,               &
     &          sph_rj, comm_rj, rj_fld, n_WS, WS, backward)
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(sph_comm_tbl), intent(in) :: comm_rj
        type(phys_data), intent(in) :: rj_fld
        type(spherical_transform_data), intent(inout) :: backward
      subroutine mhd_spectr_from_recvbuf                              &
     &         (iflag_recv, forward, comm_rj, n_WR, WR, rj_fld)
        type(spherical_transform_data), intent(in) :: forward
        type(sph_comm_tbl), intent(in) :: comm_rj
        type(phys_data), intent(inout) :: rj_fld
Function/Subroutine Documentation
mhd_spectr_from_recvbuf()
subroutine set_address_sph_trans_mhd::mhd_spectr_from_recvbuf (integer(kind = kint), intent(in) iflag_recv, type(spherical_transform_data), intent(in) forward, type(sph_comm_tbl), intent(in) comm_rj, integer(kind = kint), intent(in) n_WR, real(kind = kreal), dimension(n_wr), intent(inout) WR, type(phys_data), intent(inout) rj_fld)
Definition at line 167 of file set_address_sph_trans_MHD.f90.
References copy_spectr_4_sph_trans::sel_sph_rj_scalar_from_recv(), and copy_spectr_4_sph_trans::sel_sph_rj_vector_from_recv().
Referenced by sph_transforms_4_mhd::sph_forward_trans_4_mhd(), sph_transforms_snapshot::sph_forward_trans_snapshot_mhd(), and sph_transforms_4_mhd::sph_transform_4_licv().
mhd_spectr_to_sendbuf()
subroutine set_address_sph_trans_mhd::mhd_spectr_to_sendbuf (type(spherical_transform_data), intent(in) backward, type(sph_comm_tbl), intent(in) comm_rj, type(phys_data), intent(in) rj_fld, integer(kind = kint), intent(in) n_WS, real(kind = kreal), dimension(n_ws), intent(inout) WS)
Definition at line 105 of file set_address_sph_trans_MHD.f90.
References copy_spectr_4_sph_trans::sel_sph_rj_scalar_to_send(), and copy_spectr_4_sph_trans::sel_sph_rj_vector_to_send().
Referenced by sph_transforms_4_mhd::sph_back_trans_4_mhd(), sph_transforms_4_mhd::sph_pole_trans_4_mhd(), and sph_transforms_4_mhd::sph_transform_4_licv().
mhd_spectr_to_sendbuf_wpole()
subroutine set_address_sph_trans_mhd::mhd_spectr_to_sendbuf_wpole (integer(kind = kint), intent(in) nnod_pole, type(sph_rj_grid), intent(in) sph_rj, type(sph_comm_tbl), intent(in) comm_rj, type(phys_data), intent(in) rj_fld, integer(kind = kint), intent(in) n_WS, real(kind = kreal), dimension(n_ws), intent(inout) WS, type(spherical_transform_data), intent(inout) backward)
Definition at line 135 of file set_address_sph_trans_MHD.f90.
References copy_spectr_4_sph_trans::sel_sph_rj_scalar_2_send_wpole(), and copy_spectr_4_sph_trans::sel_sph_rj_vector_to_send().
Referenced by sph_transforms_snapshot::sph_back_trans_snapshot_mhd().
set_addresses_trans_sph_mhd()
subroutine set_address_sph_trans_mhd::set_addresses_trans_sph_mhd (type(phys_data), intent(in) d_rj, type(phys_address), intent(in) ipol, type(phys_address), intent(in) iphys, type(address_4_sph_trans), intent(inout) trns_MHD, integer(kind = kint), intent(inout) ncomp_sph_trans, integer(kind = kint), intent(inout) nvector_sph_trans, integer(kind = kint), intent(inout) nscalar_sph_trans)
Definition at line 58 of file set_address_sph_trans_MHD.f90.
References address_sph_trans_mhd::bwd_trans_address_mhd(), and address_sph_trans_mhd::fwd_trans_address_mhd().
Referenced by init_sphrical_transform_mhd::init_sph_transform_mhd().