CALYPSO: mpi_groups_io_b Module Reference
mpi_groups_io_b Module Reference
Binary output routines for group data.
Functions/Subroutines
subroutine mpi_read_group_data_b (IO_param, group_IO)
subroutine mpi_read_surf_grp_data_b (IO_param, surf_grp_IO)
subroutine mpi_write_grp_data_b (IO_param, group_IO)
subroutine mpi_write_surf_grp_data_b (IO_param, surf_grp_IO)
Detailed Description
Binary output routines for group data.
      subroutine mpi_read_group_data_b(IO_param, group_IO)
      subroutine mpi_read_surf_grp_data_b(IO_param, surf_grp_IO)
        type(group_data), intent(inout) :: group_IO
        type(surface_group_data), intent(inout) :: surf_grp_IO
      subroutine mpi_write_grp_data_b(IO_param, group_IO)
      subroutine mpi_write_surf_grp_data_b(IO_param, surf_grp_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(group_data), intent(in) :: group_IO
        type(surface_group_data), intent(in) :: surf_grp_IO
Function/Subroutine Documentation
mpi_read_group_data_b()
subroutine mpi_groups_io_b::mpi_read_group_data_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(group_data), intent(inout) group_IO)
Definition at line 41 of file MPI_groups_IO_b.f90.
References t_group_data::alloc_group_item(), t_group_data::alloc_group_num(), mpi_binary_data_io::mpi_read_int_vector_b(), mpi_binary_data_io::mpi_read_integer_stack_b(), mpi_binary_head_io::mpi_read_mul_charahead_b(), and mpi_binary_head_io::mpi_read_one_inthead_b().
Referenced by mpi_sph_modes_data_io_b::mpi_read_geom_rtp_data_b(), mpi_mesh_data_io_b::mpi_read_mesh_groups_b(), and mpi_sph_modes_data_io_b::mpi_read_spectr_rj_data_b().
mpi_read_surf_grp_data_b()
subroutine mpi_groups_io_b::mpi_read_surf_grp_data_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(surface_group_data), intent(inout) surf_grp_IO)
Definition at line 68 of file MPI_groups_IO_b.f90.
References t_group_data::alloc_sf_group_item(), t_group_data::alloc_sf_group_num(), mpi_binary_data_io::mpi_read_int_vector_b(), mpi_binary_data_io::mpi_read_integer_stack_b(), mpi_binary_head_io::mpi_read_mul_charahead_b(), and mpi_binary_head_io::mpi_read_one_inthead_b().
Referenced by mpi_mesh_data_io_b::mpi_read_mesh_groups_b().
mpi_write_grp_data_b()
subroutine mpi_groups_io_b::mpi_write_grp_data_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(group_data), intent(in) group_IO)
Definition at line 97 of file MPI_groups_IO_b.f90.
References transfer_to_long_integers::cast_long(), t_calypso_mpi_io_param::istack64_4_parallel_data(), mpi_binary_data_io::mpi_write_int_vector_b(), mpi_binary_data_io::mpi_write_integer_stack_b(), mpi_binary_head_io::mpi_write_mul_charahead_b(), and mpi_binary_head_io::mpi_write_one_inthead_b().
Referenced by mpi_sph_modes_data_io_b::mpi_write_geom_rtp_data_b(), mpi_mesh_data_io_b::mpi_write_mesh_groups_b(), and mpi_sph_modes_data_io_b::mpi_write_spectr_rj_data_b().
mpi_write_surf_grp_data_b()
subroutine mpi_groups_io_b::mpi_write_surf_grp_data_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(surface_group_data), intent(in) surf_grp_IO)
Definition at line 123 of file MPI_groups_IO_b.f90.
References transfer_to_long_integers::cast_long(), t_calypso_mpi_io_param::istack64_4_parallel_data(), mpi_binary_data_io::mpi_write_int_vector_b(), mpi_binary_data_io::mpi_write_integer_stack_b(), mpi_binary_head_io::mpi_write_mul_charahead_b(), and mpi_binary_head_io::mpi_write_one_inthead_b().
Referenced by mpi_mesh_data_io_b::mpi_write_mesh_groups_b().