CALYPSO: products_at_poles Module Reference
products_at_poles Module Reference
Evaluate products at poles.
Functions/Subroutines
subroutine pole_fld_cst_dot_prod (numnod, internal_node, xx, nnod_rtp, nidx_rtp_r, coef, ncomp_nod, i_vec1, i_vec2, i_prod, d_nod)
subroutine pole_fld_cst_cross_prod (numnod, internal_node, xx, nnod_rtp, nidx_rtp_r, coef, ncomp_nod, i_vec1, i_vec2, i_prod, d_nod)
subroutine pole_fld_cst_vec_scalar_prod (numnod, internal_node, xx, nnod_rtp, nidx_rtp_r, coef, ncomp_nod, i_vec1, i_scl, i_prod, d_nod)
subroutine pole_sph_dot_prod_w_const (numnod, internal_node, xx, nnod_rtp, nidx_rtp_r, coef, d_vec1, d_vec2, d_prod)
subroutine pole_sph_cross_prod_w_const (numnod, internal_node, xx, nnod_rtp, nidx_rtp_r, coef, d_vec1, d_vec2, d_prod)
subroutine pole_vec_scalar_prod_w_const (numnod, internal_node, xx, nnod_rtp, nidx_rtp_r, coef, d_vec1, d_scl, d_prod)
Detailed Description
Evaluate products at poles.
      subroutine pole_fld_cst_dot_prod(numnod, internal_node,         &
     &          xx, nnod_rtp, nidx_rtp_r, coef,                       &
     &          ncomp_nod, i_vec1, i_vec2, i_prod, d_nod)
      subroutine pole_fld_cst_cross_prod(numnod, internal_node,       &
     &          xx, nnod_rtp, nidx_rtp_r, coef,                       &
     &          ncomp_nod, i_vec1, i_vec2, i_prod, d_nod)
      subroutine pole_fld_cst_vec_scalar_prod(numnod, internal_node,  &
     &          xx, nnod_rtp, nidx_rtp_r, coef,                       &
     &          ncomp_nod, i_vec1, i_scl, i_prod, d_nod)
      subroutine pole_sph_dot_prod_w_const(numnod, internal_node,     &
     &          xx, nnod_rtp, nidx_rtp_r, coef, d_vec1, d_vec2,       &
     &          d_prod)
      subroutine pole_sph_cross_prod_w_const(numnod, internal_node,   &
     &          xx, nnod_rtp, nidx_rtp_r, coef, d_vec1, d_vec2,       &
     &          d_prod)
      subroutine pole_vec_scalar_prod_w_const(numnod, internal_node,  &
     &          xx, nnod_rtp, nidx_rtp_r, coef, d_vec1, d_scl,        &
     &          d_prod)
Parameters
numnod number of nodes
internal_node number of internal nodes
xx position
nnod_rtp number of grid points for \(f(r,\theta,\phi) \)
nidx_rtp_r number of radial points for \(f(r,\theta,\phi) \)
coef coefficient
d_vec1(numnod,3) vector field
d_vec2(numnod,3) vector field
d_scl(numnod) scalar field
d_prod(numnod,nd) produced field
Function/Subroutine Documentation
pole_fld_cst_cross_prod()
subroutine products_at_poles::pole_fld_cst_cross_prod (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) internal_node, real(kind = kreal), dimension(numnod,3), intent(in) xx, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) nidx_rtp_r, real(kind = kreal), intent(in) coef, integer(kind = kint), intent(in) ncomp_nod, integer(kind = kint), intent(in) i_vec1, integer(kind = kint), intent(in) i_vec2, integer(kind = kint), intent(in) i_prod, real(kind = kreal), dimension(numnod,ncomp_nod), intent(inout) d_nod)
Definition at line 81 of file products_at_poles.f90.
References pole_sph_cross_prod_w_const().
pole_fld_cst_dot_prod()
subroutine products_at_poles::pole_fld_cst_dot_prod (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) internal_node, real(kind = kreal), dimension(numnod,3), intent(in) xx, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) nidx_rtp_r, real(kind = kreal), intent(in) coef, integer(kind = kint), intent(in) ncomp_nod, integer(kind = kint), intent(in) i_vec1, integer(kind = kint), intent(in) i_vec2, integer(kind = kint), intent(in) i_prod, real(kind = kreal), dimension(numnod,ncomp_nod), intent(inout) d_nod)
Definition at line 57 of file products_at_poles.f90.
References pole_sph_dot_prod_w_const().
pole_fld_cst_vec_scalar_prod()
subroutine products_at_poles::pole_fld_cst_vec_scalar_prod (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) internal_node, real(kind = kreal), dimension(numnod,3), intent(in) xx, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) nidx_rtp_r, real(kind = kreal), intent(in) coef, integer(kind = kint), intent(in) ncomp_nod, integer(kind = kint), intent(in) i_vec1, integer(kind = kint), intent(in) i_scl, integer(kind = kint), intent(in) i_prod, real(kind = kreal), dimension(numnod,ncomp_nod), intent(inout) d_nod)
Definition at line 105 of file products_at_poles.f90.
References pole_vec_scalar_prod_w_const().
pole_sph_cross_prod_w_const()
subroutine products_at_poles::pole_sph_cross_prod_w_const (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) internal_node, real(kind = kreal), dimension(numnod,3), intent(in) xx, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) nidx_rtp_r, real(kind = kreal), intent(in) coef, real(kind = kreal), dimension(numnod,3), intent(in) d_vec1, real(kind = kreal), dimension(numnod,3), intent(in) d_vec2, real(kind = kreal), dimension(numnod,3), intent(inout) d_prod)
Definition at line 185 of file products_at_poles.f90.
References m_constants::zero.
Referenced by pole_fld_cst_cross_prod().
pole_sph_dot_prod_w_const()
subroutine products_at_poles::pole_sph_dot_prod_w_const (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) internal_node, real(kind = kreal), dimension(numnod,3), intent(in) xx, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) nidx_rtp_r, real(kind = kreal), intent(in) coef, real(kind = kreal), dimension(numnod,3), intent(in) d_vec1, real(kind = kreal), dimension(numnod,3), intent(in) d_vec2, real(kind = kreal), dimension(numnod), intent(inout) d_prod)
Definition at line 130 of file products_at_poles.f90.
References m_constants::zero.
Referenced by pole_fld_cst_dot_prod().
pole_vec_scalar_prod_w_const()
subroutine products_at_poles::pole_vec_scalar_prod_w_const (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) internal_node, real(kind = kreal), dimension(numnod,3), intent(in) xx, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) nidx_rtp_r, real(kind = kreal), intent(in) coef, real(kind = kreal), dimension(numnod,3), intent(in) d_vec1, real(kind = kreal), dimension(numnod), intent(in) d_scl, real(kind = kreal), dimension(numnod,3), intent(inout) d_prod)
Definition at line 249 of file products_at_poles.f90.
References m_constants::zero.
Referenced by pole_fld_cst_vec_scalar_prod().