CALYPSO: mpi_sph_gl_1d_idx_io_b Module Reference
mpi_sph_gl_1d_idx_io_b Module Reference
Mesh file IO for gxipped format.
Functions/Subroutines
subroutine mpi_read_rtp_gl_1d_table_b (IO_param, sph_IO)
subroutine mpi_read_rj_gl_1d_table_b (IO_param, sph_IO)
subroutine mpi_write_rtp_gl_1d_table_b (IO_param, sph_IO)
subroutine mpi_write_rj_gl_1d_table_b (IO_param, sph_IO)
Detailed Description
Mesh file IO for gxipped format.
      subroutine mpi_read_rtp_gl_1d_table_b(IO_param, sph_IO)
      subroutine mpi_read_rj_gl_1d_table_b(IO_param, sph_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(sph_IO_data), intent(inout) :: sph_IO
      subroutine mpi_write_rtp_gl_1d_table_b(IO_param, sph_IO)
      subroutine mpi_write_rj_gl_1d_table_b (IO_param, sph_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(sph_IO_data), intent(in) :: sph_IO
Function/Subroutine Documentation
mpi_read_rj_gl_1d_table_b()
subroutine mpi_sph_gl_1d_idx_io_b::mpi_read_rj_gl_1d_table_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(inout) sph_IO)
Definition at line 75 of file MPI_sph_gl_1d_idx_IO_b.f90.
References t_node_id_spherical_io::alloc_idx_sph_1d1_io(), t_node_id_spherical_io::alloc_idx_sph_1d2_io(), t_node_id_spherical_io::alloc_num_idx_sph_io(), mpi_binary_data_io::mpi_read_1d_vector_b(), and mpi_binary_data_io::mpi_read_int_vector_b().
Referenced by mpi_sph_modes_data_io_b::mpi_read_modes_rlm_data_b(), and mpi_sph_modes_data_io_b::mpi_read_spectr_rj_data_b().
mpi_read_rtp_gl_1d_table_b()
subroutine mpi_sph_gl_1d_idx_io_b::mpi_read_rtp_gl_1d_table_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(inout) sph_IO)
Definition at line 37 of file MPI_sph_gl_1d_idx_IO_b.f90.
References t_node_id_spherical_io::alloc_idx_sph_1d1_io(), t_node_id_spherical_io::alloc_idx_sph_1d2_io(), t_node_id_spherical_io::alloc_idx_sph_1d3_io(), t_node_id_spherical_io::alloc_num_idx_sph_io(), mpi_binary_data_io::mpi_read_1d_vector_b(), and mpi_binary_data_io::mpi_read_int_vector_b().
Referenced by mpi_sph_modes_data_io_b::mpi_read_geom_rtm_data_b(), and mpi_sph_modes_data_io_b::mpi_read_geom_rtp_data_b().
mpi_write_rj_gl_1d_table_b()
subroutine mpi_sph_gl_1d_idx_io_b::mpi_write_rj_gl_1d_table_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(in) sph_IO)
Definition at line 143 of file MPI_sph_gl_1d_idx_IO_b.f90.
References t_calypso_mpi_io_param::istack64_4_parallel_data(), mpi_binary_data_io::mpi_write_1d_vector_b(), and mpi_binary_data_io::mpi_write_int_vector_b().
Referenced by mpi_sph_modes_data_io_b::mpi_write_modes_rlm_data_b(), and mpi_sph_modes_data_io_b::mpi_write_spectr_rj_data_b().
mpi_write_rtp_gl_1d_table_b()
subroutine mpi_sph_gl_1d_idx_io_b::mpi_write_rtp_gl_1d_table_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(in) sph_IO)
Definition at line 110 of file MPI_sph_gl_1d_idx_IO_b.f90.
References t_calypso_mpi_io_param::istack64_4_parallel_data(), mpi_binary_data_io::mpi_write_1d_vector_b(), and mpi_binary_data_io::mpi_write_int_vector_b().
Referenced by mpi_sph_modes_data_io_b::mpi_write_geom_rtm_data_b(), and mpi_sph_modes_data_io_b::mpi_write_geom_rtp_data_b().