CALYPSO: t_control_params_4_iso Module Reference
t_control_params_4_iso Module Reference
control parameter for isuosurfaces
Data Types
type isosurface_define
Functions/Subroutines
subroutine count_control_4_iso (iso_c, ele_grp, num_nod_phys, phys_nod_name, iso_fld, iso_param, iso_def, iso_file_IO)
subroutine set_control_4_iso (iso_c, ele_grp, num_nod_phys, phys_nod_name, iso_fld, iso_param, iso_def)
subroutine, private count_control_iso_def (iso_def_c, ele_grp, iso_param)
subroutine, private set_control_iso_def (iso_def_c, ele_grp, num_nod_phys, phys_nod_name, iso_param, iso_def)
subroutine, private count_control_4_field_on_iso (fld_on_iso_c, num_nod_phys, phys_nod_name, iso_fld, iso_def)
subroutine, private set_control_4_field_on_iso (fld_on_iso_c, num_nod_phys, phys_nod_name, iso_fld, iso_param, iso_def)
subroutine, private set_merged_iso_file_ctl (default_prefix, file_prefix_ctl, file_format_ctl, ucd_param)
integer(kind=kint) function sel_iso_file_format (file_fmt_ctl)
integer(kind=kint) function num_label_iso_type ()
subroutine set_label_iso_type (names)
Variables
character(len=kchara), parameter, private default_iso_prefix = 'iso'
character(len=kchara), parameter cflag_const_iso = 'constant'
character(len=kchara), parameter cflag_field_iso = 'field'
integer(kind=kint), parameter iflag_constant_iso = -1
integer(kind=kint), parameter iflag_field_iso = 1
integer(kind=kint), parameter n_label_iso_type = 2
Detailed Description
control parameter for isuosurfaces
      subroutine count_control_4_iso                                  &
     &         (iso_c, ele_grp, num_nod_phys, phys_nod_name,          &
     &          iso_fld, iso_param, iso_def, iso_file_IO)
      subroutine set_control_4_iso                                    &
     &         (iso_c, ele_grp, num_nod_phys, phys_nod_name,          &
     &          iso_fld, iso_param, iso_def)
        type(group_data), intent(in) :: ele_grp
        type(iso_ctl), intent(in) :: iso_c
        type(phys_data), intent(inout) :: iso_fld
        type(psf_parameters), intent(inout) :: iso_param
        type(isosurface_define), intent(inout) :: iso_def
        type(field_IO_params), intent(inout) :: iso_file_IO
        integer(kind = kint) function sel_iso_file_format(file_fmt_ctl)
      integer(kind = kint) function num_label_iso_type()
      subroutine set_label_iso_type(names)
Function/Subroutine Documentation
count_control_4_field_on_iso()
subroutine, private t_control_params_4_iso::count_control_4_field_on_iso (type(field_on_psf_ctl), intent(in) fld_on_iso_c, integer(kind = kint), intent(in) num_nod_phys, character(len=kchara), dimension(num_nod_phys), intent(in) phys_nod_name, type(phys_data), intent(inout) iso_fld, type(isosurface_define), intent(inout) iso_def) private
Definition at line 205 of file t_control_params_4_iso.f90.
References cflag_const_iso, cflag_field_iso, set_field_comp_for_viz::check_field_4_viz(), skip_comment_f::cmp_no_case(), iflag_constant_iso, and iflag_field_iso.
Referenced by count_control_4_iso().
count_control_4_iso()
subroutine t_control_params_4_iso::count_control_4_iso (type(iso_ctl), intent(in) iso_c, type(group_data), intent(in) ele_grp, integer(kind = kint), intent(in) num_nod_phys, character(len=kchara), dimension(num_nod_phys), intent(in) phys_nod_name, type(phys_data), intent(inout) iso_fld, type(psf_parameters), intent(inout) iso_param, type(isosurface_define), intent(inout) iso_def, type(field_io_params), intent(inout) iso_file_IO)
Definition at line 65 of file t_control_params_4_iso.f90.
References count_control_4_field_on_iso(), count_control_iso_def(), default_iso_prefix, m_file_format_switch::iflag_single, and set_merged_iso_file_ctl().
Referenced by set_psf_iso_control::set_iso_control().
count_control_iso_def()
subroutine, private t_control_params_4_iso::count_control_iso_def (type(iso_define_ctl), intent(in) iso_def_c, type(group_data), intent(in) ele_grp, type(psf_parameters), intent(inout) iso_param) private
Definition at line 143 of file t_control_params_4_iso.f90.
References set_area_4_viz::count_area_4_viz().
Referenced by count_control_4_iso().
num_label_iso_type()
integer(kind = kint) function t_control_params_4_iso::num_label_iso_type
Definition at line 404 of file t_control_params_4_iso.f90.
References n_label_iso_type.
sel_iso_file_format()
integer(kind = kint) function t_control_params_4_iso::sel_iso_file_format (character(len=kchara), intent(in) file_fmt_ctl)
Definition at line 339 of file t_control_params_4_iso.f90.
References t_multi_flag_labels::check_mul_flags(), m_merged_field_fmt_labels::dealloc_mgd_field_type_flags(), m_field_file_format::iflag_sgl_ucd, m_field_file_format::iflag_sgl_ucd_bin, m_field_file_format::iflag_sgl_ucd_bin_gz, m_field_file_format::iflag_sgl_ucd_gz, m_field_file_format::iflag_sgl_vtk, m_field_file_format::iflag_sgl_vtk_gz, m_merged_field_fmt_labels::init_mgd_field_type_flags(), m_merged_field_fmt_labels::mgd_fbin_gz_labels, m_merged_field_fmt_labels::mgd_fld_ascii_labels, m_merged_field_fmt_labels::mgd_fld_bin_labels, m_merged_field_fmt_labels::mgd_fld_gz_labels, m_merged_field_fmt_labels::mgd_iso_gz_labels, m_merged_field_fmt_labels::mgd_iso_labels, m_merged_field_fmt_labels::mgd_psf_gz_labels, m_merged_field_fmt_labels::mgd_psf_labels, m_merged_field_fmt_labels::mgd_ucd_gz_labels, m_merged_field_fmt_labels::mgd_ucd_labels, m_merged_field_fmt_labels::mgd_udt_gz_labels, m_merged_field_fmt_labels::mgd_udt_labels, m_merged_field_fmt_labels::mgd_vtd_gz_labels, m_merged_field_fmt_labels::mgd_vtd_labels, m_merged_field_fmt_labels::mgd_vtk_gz_labels, and m_merged_field_fmt_labels::mgd_vtk_labels.
Referenced by set_merged_iso_file_ctl().
set_control_4_field_on_iso()
subroutine, private t_control_params_4_iso::set_control_4_field_on_iso (type(field_on_psf_ctl), intent(in) fld_on_iso_c, integer(kind = kint), intent(in) num_nod_phys, character(len=kchara), dimension(num_nod_phys), intent(in) phys_nod_name, type(phys_data), intent(inout) iso_fld, type(psf_parameters), intent(inout) iso_param, type(isosurface_define), intent(inout) iso_def) private
Definition at line 262 of file t_control_params_4_iso.f90.
References t_psf_patch_data::alloc_output_comps_psf(), iflag_constant_iso, iflag_field_iso, and set_field_comp_for_viz::set_components_4_viz().
Referenced by set_control_4_iso().
set_control_4_iso()
subroutine t_control_params_4_iso::set_control_4_iso (type(iso_ctl), intent(in) iso_c, type(group_data), intent(in) ele_grp, integer(kind = kint), intent(in) num_nod_phys, character(len=kchara), dimension(num_nod_phys), intent(in) phys_nod_name, type(phys_data), intent(inout) iso_fld, type(psf_parameters), intent(inout) iso_param, type(isosurface_define), intent(inout) iso_def)
Definition at line 110 of file t_control_params_4_iso.f90.
References t_psf_patch_data::alloc_area_group_psf(), set_control_4_field_on_iso(), and set_control_iso_def().
Referenced by set_psf_iso_control::set_iso_control().
set_control_iso_def()
subroutine, private t_control_params_4_iso::set_control_iso_def (type(iso_define_ctl), intent(in) iso_def_c, type(group_data), intent(in) ele_grp, integer(kind = kint), intent(in) num_nod_phys, character(len=kchara), dimension(num_nod_phys), intent(in) phys_nod_name, type(psf_parameters), intent(inout) iso_param, type(isosurface_define), intent(inout) iso_def) private
Definition at line 165 of file t_control_params_4_iso.f90.
References set_area_4_viz::s_set_area_4_viz(), and set_field_comp_for_viz::set_one_component_4_viz().
Referenced by set_control_4_iso().
set_label_iso_type()
subroutine t_control_params_4_iso::set_label_iso_type (character(len = kchara), dimension(n_label_iso_type), intent(inout) names)
Definition at line 411 of file t_control_params_4_iso.f90.
References cflag_const_iso, cflag_field_iso, and t_read_control_elements::set_control_labels().
set_merged_iso_file_ctl()
subroutine, private t_control_params_4_iso::set_merged_iso_file_ctl (character(len = kchara), intent(in) default_prefix, type(read_character_item), intent(in) file_prefix_ctl, type(read_character_item), intent(in) file_format_ctl, type(field_io_params), intent(inout) ucd_param) private
Definition at line 306 of file t_control_params_4_iso.f90.
References m_field_file_format::iflag_sgl_vtk, and sel_iso_file_format().
Referenced by count_control_4_iso().
Variable Documentation
cflag_const_iso
character(len=kchara), parameter t_control_params_4_iso::cflag_const_iso = 'constant'
Definition at line 36 of file t_control_params_4_iso.f90.
Referenced by count_control_4_field_on_iso(), and set_label_iso_type().
cflag_field_iso
character(len=kchara), parameter t_control_params_4_iso::cflag_field_iso = 'field'
Definition at line 37 of file t_control_params_4_iso.f90.
Referenced by count_control_4_field_on_iso(), and set_label_iso_type().
default_iso_prefix
character(len=kchara), parameter, private t_control_params_4_iso::default_iso_prefix = 'iso' private
Definition at line 34 of file t_control_params_4_iso.f90.
Referenced by count_control_4_iso().
iflag_constant_iso
integer(kind = kint), parameter t_control_params_4_iso::iflag_constant_iso = -1
Definition at line 39 of file t_control_params_4_iso.f90.
Referenced by count_control_4_field_on_iso(), set_control_4_field_on_iso(), and set_fields_for_psf::set_field_4_iso().
iflag_field_iso
integer(kind = kint), parameter t_control_params_4_iso::iflag_field_iso = 1
Definition at line 40 of file t_control_params_4_iso.f90.
Referenced by count_control_4_field_on_iso(), and set_control_4_field_on_iso().
n_label_iso_type
integer(kind = kint), parameter t_control_params_4_iso::n_label_iso_type = 2
Definition at line 42 of file t_control_params_4_iso.f90.
Referenced by num_label_iso_type().