CALYPSO: t_physical_property Module Reference
t_physical_property Module Reference
Coeffiecients of each term.
Data Types
type conductive_property
Structure for manetic property.
type fluid_property
Structure for fluid property.
type scalar_property
Structure for thermal property.
Functions/Subroutines
subroutine alloc_force_list (fl_prop)
subroutine dealloc_force_list (fl_prop)
subroutine set_filtered_advection_ctl (filterd_advect_ctl, scl_prop)
subroutine set_filtered_induction_ctl (filterd_induction_ctl, cd_prop)
Variables
integer(kind=kint), parameter id_no_evolution = 0
Scheme ID for no evolution.
integer(kind=kint), parameter id_explicit_euler = 1
Scheme ID for explicit Euler scheme.
integer(kind=kint), parameter id_explicit_adams2 = 2
Scheme ID for 2nd order Adams-Bashforth Scheme.
integer(kind=kint), parameter id_crank_nicolson = 3
Scheme ID for Crank-Nicolson Scheme.
integer(kind=kint), parameter id_crank_nicolson_cmass = 4
Scheme ID for Crank-Nicolson Scheme with consistent mass matrix.
integer(kind=kint), parameter iflag_no_gravity = -1
flag for no gravity
integer(kind=kint), parameter iflag_const_g = 0
flag for constant gravity
integer(kind=kint), parameter iflag_radial_g = 1
flag for radial gravity (amplitude is fixed)
integer(kind=kint), parameter iflag_self_r_g = 2
flag for self radial gravity
integer(kind=kint), parameter id_force_ele_int = 1
Turn ON and evaluate over elements flag.
integer(kind=kint), parameter id_force_at_node = 2
Turn ON and evaluate at node flag.
Detailed Description
Coeffiecients of each term.
      subroutine alloc_force_list(num, fl_prop)
      subroutine dealloc_force_list(fl_prop)
        type(fluid_property), intent(inout) :: fl_prop
      subroutine set_reference_scalar_ctl(ref_ctl, scl_prop)
        type(reference_temperature_ctl), intent(in) :: ref_ctl
        type(scalar_property), intent(inout) :: scl_prop
Function/Subroutine Documentation
alloc_force_list()
subroutine t_physical_property::alloc_force_list (type(fluid_property), intent(inout) fl_prop)
Definition at line 191 of file t_physical_property.f90.
Referenced by set_control_4_force::set_control_force_flags().
dealloc_force_list()
subroutine t_physical_property::dealloc_force_list (type(fluid_property), intent(inout) fl_prop)
Definition at line 202 of file t_physical_property.f90.
set_filtered_advection_ctl()
subroutine t_physical_property::set_filtered_advection_ctl (type(read_character_item), intent(in) filterd_advect_ctl, type(scalar_property), intent(inout) scl_prop)
Definition at line 213 of file t_physical_property.f90.
References id_no_evolution, and skip_comment_f::yes_flag().
set_filtered_induction_ctl()
subroutine t_physical_property::set_filtered_induction_ctl (type(read_character_item), intent(in) filterd_induction_ctl, type(conductive_property), intent(inout) cd_prop)
Definition at line 236 of file t_physical_property.f90.
References id_no_evolution, and skip_comment_f::yes_flag().
Referenced by set_control_4_force::set_control_4_induction().
Variable Documentation
id_crank_nicolson
integer (kind=kint), parameter t_physical_property::id_crank_nicolson = 3
Scheme ID for Crank-Nicolson Scheme.
Definition at line 34 of file t_physical_property.f90.
Referenced by const_r_mat_4_vector_sph::const_radial_mat_4_magne_sph(), const_r_mat_4_scalar_sph::const_radial_mat_4_scalar_sph(), const_r_mat_w_center_sph::const_radial_mat_press00_sph(), const_r_mat_w_center_sph::const_radial_mat_scalar00_sph(), const_radial_mat_4_sph::const_radial_mat_sph_snap(), const_radial_mat_4_sph::const_radial_matrices_sph(), and set_control_4_force::set_control_4_coriolis_force().
id_crank_nicolson_cmass
integer (kind=kint), parameter t_physical_property::id_crank_nicolson_cmass = 4
Scheme ID for Crank-Nicolson Scheme with consistent mass matrix.
Definition at line 36 of file t_physical_property.f90.
Referenced by set_control_4_force::set_control_4_coriolis_force(), and set_control_4_force::set_control_4_gravity().
id_explicit_adams2
integer (kind=kint), parameter t_physical_property::id_explicit_adams2 = 2
Scheme ID for 2nd order Adams-Bashforth Scheme.
Definition at line 32 of file t_physical_property.f90.
id_explicit_euler
integer (kind=kint), parameter t_physical_property::id_explicit_euler = 1
Scheme ID for explicit Euler scheme.
Definition at line 30 of file t_physical_property.f90.
Referenced by cal_momentum_eq_explicit::sel_explicit_sph().
id_force_at_node
integer (kind=kint), parameter t_physical_property::id_force_at_node = 2
Turn ON and evaluate at node flag.
Definition at line 52 of file t_physical_property.f90.
Referenced by add_nodal_fields_4_mhd::add_ctl_4_forces(), set_control_4_force::set_control_4_coriolis_force(), and set_control_4_force::set_control_4_gravity().
id_force_ele_int
integer (kind=kint), parameter t_physical_property::id_force_ele_int = 1
Turn ON and evaluate over elements flag.
Definition at line 50 of file t_physical_property.f90.
Referenced by set_control_4_force::set_control_4_gravity().
id_no_evolution
integer (kind=kint), parameter t_physical_property::id_no_evolution = 0
Scheme ID for no evolution.
Definition at line 28 of file t_physical_property.f90.
Referenced by add_nodal_fields_4_mhd::add_data_4_check_step(), add_nodal_fields_4_mhd::add_data_4_previous_step(), add_nodal_fields_4_mhd::add_field_ctl_4_evo_magne(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), add_nodal_fields_4_mhd::add_work_area_4_potentials(), cal_momentum_eq_explicit::cal_explicit_sph_adams(), cal_momentum_eq_explicit::cal_explicit_sph_euler(), cal_momentum_eq_explicit::cal_first_prev_step_adams(), cal_vorticity_terms_adams::cal_vorticity_eq_adams(), cal_vorticity_terms_adams::cal_vorticity_eq_euler(), check_dependency_for_mhd::check_dependence_sph_evo(), check_dependency_for_mhd::check_field_dependencies(), check_read_bc_file::chk_read_boundary_files(), explicit_scalars_sph::explicit_scalars_sph_adams(), explicit_scalars_sph::explicit_scalars_sph_euler(), explicit_scalars_sph::first_scalars_prev_step_adams(), cal_nonlinear::licv_exp(), cal_nonlinear::nonlinear(), cal_sol_sph_mhd_crank::s_cal_sol_sph_mhd_crank(), copy_field_data_4_dt_check::s_copy_field_data_for_dt_check(), set_bc_sph_mhd::s_set_bc_sph_mhd(), set_control_4_composition::s_set_control_4_composition(), set_control_4_magne::s_set_control_4_magne(), set_control_4_normalize::s_set_control_4_normalize(), set_control_4_press::s_set_control_4_press(), set_control_4_temp::s_set_control_4_temp(), set_control_4_velo::s_set_control_4_velo(), set_control_4_normalize::set_coefs_4_induction_eq(), material_property::set_composition_property(), material_property::set_conductive_property(), set_control_4_force::set_control_force_flags(), set_filtered_advection_ctl(), set_filtered_induction_ctl(), material_property::set_fluid_property(), cal_vorticity_terms_adams::set_ini_adams_inertia(), cal_sol_sph_mhd_crank::set_sph_field_to_start(), and material_property::set_thermal_property().
iflag_const_g
integer (kind = kint), parameter t_physical_property::iflag_const_g = 0
flag for constant gravity
Definition at line 42 of file t_physical_property.f90.
Referenced by set_control_4_force::set_control_4_gravity().
iflag_no_gravity
integer (kind = kint), parameter t_physical_property::iflag_no_gravity = -1
flag for no gravity
Definition at line 40 of file t_physical_property.f90.
Referenced by set_control_4_force::set_control_4_gravity().
iflag_radial_g
integer (kind = kint), parameter t_physical_property::iflag_radial_g = 1
flag for radial gravity (amplitude is fixed)
Definition at line 44 of file t_physical_property.f90.
Referenced by set_control_4_force::set_control_4_gravity().
iflag_self_r_g
integer (kind = kint), parameter t_physical_property::iflag_self_r_g = 2
flag for self radial gravity
Definition at line 46 of file t_physical_property.f90.
Referenced by set_control_4_force::set_control_4_gravity().