CALYPSO: copy_sph_comm_table_4_io Module Reference
copy_sph_comm_table_4_io Module Reference
Copy communication table for spherical hermonica transform between IO data.
Functions/Subroutines
subroutine copy_comm_sph_from_io (numnod, comm, comm_sph)
subroutine copy_comm_sph_to_comm_tbl (comm_sph, comm)
integer(kind=kint) function compare_comm_sph_with_comm_tbl (comm_sph, comm)
Detailed Description
Copy communication table for spherical hermonica transform between IO data.
      subroutine copy_comm_sph_from_IO(numnod, comm, comm_sph)
        type(communication_table), intent(in) :: comm
        type(sph_comm_tbl), intent(inout) :: comm_sph
      subroutine copy_comm_sph_to_comm_tbl(comm_sph, comm)
        type(sph_comm_tbl), intent(in) :: comm_sph
        type(communication_table), intent(inout) :: comm
      integer(kind = kint) function compare_comm_sph_with_comm_tbl    &
     &                            (comm_sph, comm)
        type(sph_comm_tbl), intent(in) :: comm_sph
        type(communication_table), intent(in) :: comm
Parameters
nnod_rtp number of data points for \(f(r,\theta,\phi) \)
nnod_rtm number of data points for \(f(r,\theta,m) \)
nnod_rlm number of data points for \(f(r,l,m) \)
nnod_rj
number of data points for \(f(r,j) \)
Function/Subroutine Documentation
compare_comm_sph_with_comm_tbl()
integer(kind = kint) function copy_sph_comm_table_4_io::compare_comm_sph_with_comm_tbl (type(sph_comm_tbl), intent(in) comm_sph, type(communication_table), intent(in) comm)
Definition at line 101 of file copy_sph_comm_table_4_IO.f90.
Referenced by compare_sph_with_io::compare_sph_rj_with_io(), compare_sph_with_io::compare_sph_rlm_with_io(), compare_sph_with_io::compare_sph_rtm_with_io(), and compare_sph_with_io::compare_sph_rtp_with_io().
copy_comm_sph_from_io()
subroutine copy_sph_comm_table_4_io::copy_comm_sph_from_io (integer(kind = kint), intent(in) numnod, type(communication_table), intent(in) comm, type(sph_comm_tbl), intent(inout) comm_sph)
Definition at line 51 of file copy_sph_comm_table_4_IO.f90.
References t_sph_trans_comm_tbl::alloc_sph_comm_item(), and t_sph_trans_comm_tbl::alloc_sph_comm_stack().
Referenced by load_data_for_sph_io::copy_sph_trans_rj_from_io(), load_data_for_sph_io::copy_sph_trans_rlm_from_io(), load_data_for_sph_io::copy_sph_trans_rtm_from_io(), and load_data_for_sph_io::copy_sph_trans_rtp_from_io().
copy_comm_sph_to_comm_tbl()
subroutine copy_sph_comm_table_4_io::copy_comm_sph_to_comm_tbl (type(sph_comm_tbl), intent(in) comm_sph, type(communication_table), intent(inout) comm)
Definition at line 76 of file copy_sph_comm_table_4_IO.f90.
References t_comm_table::alloc_import_item(), t_comm_table::alloc_import_num(), and t_comm_table::alloc_neighbouring_id().
Referenced by load_data_for_sph_io::copy_sph_trans_rj_to_io(), load_data_for_sph_io::copy_sph_trans_rlm_to_io(), load_data_for_sph_io::copy_sph_trans_rtm_to_io(), and load_data_for_sph_io::copy_sph_trans_rtp_to_io().