CALYPSO: sph_global_1d_idx_io Module Reference
sph_global_1d_idx_io Module Reference
Base routines for spectr indexing data IO.
Functions/Subroutines
subroutine read_rtp_gl_1d_table (id_file, sph_IO)
subroutine read_rj_gl_1d_table (id_file, sph_IO)
subroutine write_rtp_gl_1d_table (id_file, sph_IO)
subroutine write_rj_gl_1d_table (id_file, sph_IO)
Variables
character(len=255), private character_4_read = ''
Detailed Description
Base routines for spectr indexing data IO.
      subroutine read_rtp_gl_1d_table(id_file, sph_IO)
      subroutine read_rj_gl_1d_table(id_file, sph_IO)
        type(sph_IO_data), intent(inout) :: sph_IO
      subroutine write_rtp_gl_1d_table(id_file, sph_IO)
      subroutine write_rj_gl_1d_table(id_file, sph_IO)
        type(sph_IO_data), intent(in) :: sph_IO
Function/Subroutine Documentation
read_rj_gl_1d_table()
subroutine sph_global_1d_idx_io::read_rj_gl_1d_table (integer(kind = kint), intent(in) id_file, type(sph_io_data), intent(inout) sph_IO)
Definition at line 82 of file sph_global_1d_idx_IO.f90.
References t_node_id_spherical_io::alloc_idx_sph_1d1_io(), t_node_id_spherical_io::alloc_idx_sph_1d2_io(), t_node_id_spherical_io::alloc_num_idx_sph_io(), character_4_read, and skip_comment_f::skip_comment().
Referenced by sph_modes_grids_data_io::read_spectr_modes_rj_data(), and sph_modes_grids_data_io::read_spectr_modes_rlm_data().
read_rtp_gl_1d_table()
subroutine sph_global_1d_idx_io::read_rtp_gl_1d_table (integer(kind = kint), intent(in) id_file, type(sph_io_data), intent(inout) sph_IO)
Definition at line 35 of file sph_global_1d_idx_IO.f90.
References t_node_id_spherical_io::alloc_idx_sph_1d1_io(), t_node_id_spherical_io::alloc_idx_sph_1d2_io(), t_node_id_spherical_io::alloc_idx_sph_1d3_io(), t_node_id_spherical_io::alloc_num_idx_sph_io(), character_4_read, and skip_comment_f::skip_comment().
Referenced by sph_modes_grids_data_io::read_geom_rtm_data(), and sph_modes_grids_data_io::read_geom_rtp_data().
write_rj_gl_1d_table()
subroutine sph_global_1d_idx_io::write_rj_gl_1d_table (integer(kind = kint), intent(in) id_file, type(sph_io_data), intent(in) sph_IO)
Definition at line 159 of file sph_global_1d_idx_IO.f90.
References m_sph_modes_grid_labels::hd_jmode(), and m_sph_modes_grid_labels::hd_rgrid().
Referenced by sph_modes_grids_data_io::write_modes_rlm_data(), and sph_modes_grids_data_io::write_spectr_modes_rj_data().
write_rtp_gl_1d_table()
subroutine sph_global_1d_idx_io::write_rtp_gl_1d_table (integer(kind = kint), intent(in) id_file, type(sph_io_data), intent(in) sph_IO)
Definition at line 121 of file sph_global_1d_idx_IO.f90.
References m_sph_modes_grid_labels::hd_pgrid(), m_sph_modes_grid_labels::hd_rgrid(), and m_sph_modes_grid_labels::hd_tgrid().
Referenced by sph_modes_grids_data_io::write_geom_rtm_data(), and sph_modes_grids_data_io::write_geom_rtp_data().
Variable Documentation
character_4_read
character(len=255), private sph_global_1d_idx_io::character_4_read = '' private
Definition at line 27 of file sph_global_1d_idx_IO.f90.
Referenced by read_rj_gl_1d_table(), and read_rtp_gl_1d_table().