CALYPSO: gz_ucd_field_mpi_io Module Reference
gz_ucd_field_mpi_io Module Reference
Output ucd data into gzipped field file using MPI-IO.
Functions/Subroutines
subroutine gz_write_ucd_field_file_mpi (file_name, t_IO, ucd)
subroutine gz_read_ucd_field_file_mpi (file_name, num_pe, id_rank, t_IO, ucd)
subroutine gz_read_alloc_ucd_fld_file_mpi (file_name, num_pe, id_rank, t_IO, ucd)
Detailed Description
Output ucd data into gzipped field file using MPI-IO.
      subroutine gz_write_ucd_field_file_mpi(file_name, t_IO, ucd)
        type(time_data), intent(in) :: t_IO
        type(field_IO), intent(in) :: ucd
      subroutine gz_read_ucd_field_file_mpi                           &
     &         (file_name, num_pe, id_rank, t_IO, ucd)
      subroutine gz_read_alloc_ucd_fld_file_mpi                       &
     &         (file_name, num_pe, id_rank, t_IO, ucd)
        type(time_data), intent(inout) :: t_IO
        type(ucd_data), intent(inout) :: ucd
   Data format for the merged ascii field data
     1.   Number of process
     2.   Time step
     3.   Time, Delta t
     4.   Stacks of numbe of data points
     5.   Number of fields
     6.   List of number of components
     7.   Each field data  (Itarate 7.1 - 7.3)
      7.1   Field name
      7.2   List of data size (Byte, after compressed)
      7.3   Field data
Function/Subroutine Documentation
gz_read_alloc_ucd_fld_file_mpi()
subroutine gz_ucd_field_mpi_io::gz_read_alloc_ucd_fld_file_mpi (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, type(time_data), intent(inout) t_IO, type(ucd_data), intent(inout) ucd)
Definition at line 124 of file gz_ucd_field_MPI_IO.f90.
References t_ucd_data::allocate_ucd_phys_data(), t_ucd_data::allocate_ucd_phys_name(), t_ucd_data::cal_istack_ucd_component(), m_calypso_mpi_io::calypso_close_mpi_file(), m_calypso_mpi_io::calypso_mpi_read_file_open(), t_ucd_data::deallocate_ucd_phys_data(), t_ucd_data::deallocate_ucd_phys_name(), calypso_mpi::my_rank, gz_field_block_mpi_io::read_field_data_gz_mpi(), gz_field_block_mpi_io::read_field_header_gz_mpi(), gz_field_block_mpi_io::read_field_num_gz_mpi(), and gz_field_block_mpi_io::read_field_step_gz_mpi().
Referenced by parallel_ucd_io_select::sel_read_alloc_para_udt_file().
gz_read_ucd_field_file_mpi()
subroutine gz_ucd_field_mpi_io::gz_read_ucd_field_file_mpi (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, type(time_data), intent(inout) t_IO, type(ucd_data), intent(inout) ucd)
Definition at line 83 of file gz_ucd_field_MPI_IO.f90.
References m_calypso_mpi_io::calypso_close_mpi_file(), m_calypso_mpi_io::calypso_mpi_read_file_open(), calypso_mpi::my_rank, gz_field_block_mpi_io::read_field_data_gz_mpi(), gz_field_block_mpi_io::read_field_header_gz_mpi(), gz_field_block_mpi_io::read_field_num_gz_mpi(), and gz_field_block_mpi_io::read_field_step_gz_mpi().
Referenced by parallel_ucd_io_select::sel_read_parallel_udt_file().
gz_write_ucd_field_file_mpi()
subroutine gz_ucd_field_mpi_io::gz_write_ucd_field_file_mpi (character(len=kchara), intent(in) file_name, type(time_data), intent(in) t_IO, type(ucd_data), intent(in) ucd)
Definition at line 52 of file gz_ucd_field_MPI_IO.f90.
References m_calypso_mpi_io::calypso_close_mpi_file(), m_calypso_mpi_io::calypso_mpi_write_file_open(), calypso_mpi::my_rank, calypso_mpi::nprocs, gz_field_block_mpi_io::write_field_data_gz_mpi(), and gz_field_block_mpi_io::write_field_head_gz_mpi().
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_file().