CALYPSO: explicit_scalars_sph Module Reference
explicit_scalars_sph Module Reference
Time integration for momentum equation by explicit scheme.
Functions/Subroutines
subroutine explicit_scalars_sph_adams (dt, sph_rj, ht_prop, cp_prop, sph_bc_T, sph_bc_C, ipol_base, ipol_exp, ipol_frc, ipol_dif, rj_fld)
subroutine explicit_scalars_sph_euler (dt, sph_rj, ht_prop, cp_prop, sph_bc_T, sph_bc_C, ipol_base, ipol_frc, ipol_dif, rj_fld)
subroutine first_scalars_prev_step_adams (sph_rj, ht_prop, cp_prop, sph_bc_T, sph_bc_C, ipol_base, ipol_exp, ipol_frc, rj_fld)
Detailed Description
Time integration for momentum equation by explicit scheme.
      subroutine explicit_scalars_sph_adams                           &
     &         (dt, sph_rj, ht_prop, cp_prop, sph_bc_T, sph_bc_C,     &
     &          ipol_base, ipol_exp, ipol_frc, ipol_dif, rj_fld)
      subroutine explicit_scalars_sph_euler                           &
     &         (dt, sph_rj, ht_prop, cp_prop, sph_bc_T, sph_bc_C,     &
     &          ipol_base, ipol_frc, ipol_dif, rj_fld)
      subroutine first_scalars_prev_step_adams                        &
     &         (sph_rj, ht_prop, cp_prop, sph_bc_T, sph_bc_C,         &
     &          ipol_base, ipol_exp, ipol_frc, rj_fld)
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(scalar_property), intent(in) :: ht_prop, cp_prop
        type(sph_boundary_type), intent(in) :: sph_bc_T, sph_bc_C
        type(base_field_address), intent(in) :: ipol_base
        type(explicit_term_address), intent(in) :: ipol_exp
        type(base_force_address), intent(in) :: ipol_frc
        type(diffusion_address), intent(in) :: ipol_dif
        type(phys_data), intent(inout) :: rj_fld
Parameters
i_step time step
Function/Subroutine Documentation
explicit_scalars_sph_adams()
subroutine explicit_scalars_sph::explicit_scalars_sph_adams (real(kind = kreal), intent(in) dt, type(sph_rj_grid), intent(in) sph_rj, type(scalar_property), intent(in) ht_prop, type(scalar_property), intent(in) cp_prop, type(sph_boundary_type), intent(in) sph_bc_T, type(sph_boundary_type), intent(in) sph_bc_C, type(base_field_address), intent(in) ipol_base, type(explicit_term_address), intent(in) ipol_exp, type(base_force_address), intent(in) ipol_frc, type(diffusion_address), intent(in) ipol_dif, type(phys_data), intent(inout) rj_fld)
Definition at line 52 of file explicit_scalars_sph.f90.
References t_physical_property::id_no_evolution, select_diff_adv_source::sel_ctr_scl_diff_adv_src_adams(), and select_diff_adv_source::sel_scalar_diff_adv_src_adams().
Referenced by cal_momentum_eq_explicit::cal_explicit_sph_adams().
explicit_scalars_sph_euler()
subroutine explicit_scalars_sph::explicit_scalars_sph_euler (real(kind = kreal), intent(in) dt, type(sph_rj_grid), intent(in) sph_rj, type(scalar_property), intent(in) ht_prop, type(scalar_property), intent(in) cp_prop, type(sph_boundary_type), intent(in) sph_bc_T, type(sph_boundary_type), intent(in) sph_bc_C, type(base_field_address), intent(in) ipol_base, type(base_force_address), intent(in) ipol_frc, type(diffusion_address), intent(in) ipol_dif, type(phys_data), intent(inout) rj_fld)
Definition at line 118 of file explicit_scalars_sph.f90.
References t_physical_property::id_no_evolution, select_diff_adv_source::sel_ctr_scl_diff_adv_src_euler(), and select_diff_adv_source::sel_scalar_diff_adv_src_euler().
Referenced by cal_momentum_eq_explicit::cal_explicit_sph_euler().
first_scalars_prev_step_adams()
subroutine explicit_scalars_sph::first_scalars_prev_step_adams (type(sph_rj_grid), intent(in) sph_rj, type(scalar_property), intent(in) ht_prop, type(scalar_property), intent(in) cp_prop, type(sph_boundary_type), intent(in) sph_bc_T, type(sph_boundary_type), intent(in) sph_bc_C, type(base_field_address), intent(in) ipol_base, type(explicit_term_address), intent(in) ipol_exp, type(base_force_address), intent(in) ipol_frc, type(phys_data), intent(inout) rj_fld)
Definition at line 183 of file explicit_scalars_sph.f90.
References t_physical_property::id_no_evolution, and select_diff_adv_source::sel_ini_adams_scalar_w_src().
Referenced by cal_momentum_eq_explicit::cal_first_prev_step_adams().