CALYPSO: m_elapsed_labels_4_viz Module Reference
m_elapsed_labels_4_viz Module Reference
Initialize elepsed time monitoring.
Functions/Subroutines
subroutine elpsed_label_4_viz
subroutine reset_elapse_after_init_viz
subroutine, private elpsed_label_4_viz_outline
subroutine, private elpsed_label_4_pvr
subroutine, private elpsed_label_4_lic
subroutine elpsed_label_4_psf
subroutine elpsed_label_4_iso
subroutine, private reset_elapse_after_init_viz_top
subroutine, private reset_elapse_after_init_pvr
subroutine, private reset_elapse_after_init_lic
subroutine, private reset_elapse_after_init_psf
subroutine, private reset_elapse_after_init_iso
Variables
logical, save iflag_viz_time = .FALSE.
integer(kind=kint), save ist_elapsed_viz = 0
integer(kind=kint), save ied_elapsed_viz = 0
logical, save iflag_pvr_time = .FALSE.
integer(kind=kint), save ist_elapsed_pvr = 0
integer(kind=kint), save ied_elapsed_pvr = 0
logical, save iflag_lic_time = .FALSE.
integer(kind=kint), save ist_elapsed_lic = 0
integer(kind=kint), save ied_elapsed_lic = 0
logical, save iflag_psf_time = .FALSE.
integer(kind=kint), save ist_elapsed_psf = 0
integer(kind=kint), save ied_elapsed_psf = 0
logical, save iflag_iso_time = .FALSE.
integer(kind=kint), save ist_elapsed_iso = 0
integer(kind=kint), save ied_elapsed_iso = 0
Detailed Description
Initialize elepsed time monitoring.
      subroutine elpsed_label_4_VIZ
      subroutine reset_elapse_after_init_VIZ
Function/Subroutine Documentation
elpsed_label_4_iso()
subroutine m_elapsed_labels_4_viz::elpsed_label_4_iso
Definition at line 202 of file m_elapsed_labels_4_VIZ.f90.
References m_work_time::append_elapsed_times(), m_work_time::elps1, ied_elapsed_iso, iflag_iso_time, and ist_elapsed_iso.
Referenced by elpsed_label_4_viz().
elpsed_label_4_lic()
subroutine, private m_elapsed_labels_4_viz::elpsed_label_4_lic private
Definition at line 158 of file m_elapsed_labels_4_VIZ.f90.
References m_work_time::append_elapsed_times(), m_work_time::elps1, ied_elapsed_lic, iflag_lic_time, and ist_elapsed_lic.
Referenced by elpsed_label_4_viz().
elpsed_label_4_psf()
subroutine m_elapsed_labels_4_viz::elpsed_label_4_psf
Definition at line 181 of file m_elapsed_labels_4_VIZ.f90.
References m_work_time::append_elapsed_times(), m_work_time::elps1, ied_elapsed_psf, iflag_psf_time, and ist_elapsed_psf.
Referenced by elpsed_label_4_viz().
elpsed_label_4_pvr()
subroutine, private m_elapsed_labels_4_viz::elpsed_label_4_pvr private
Definition at line 118 of file m_elapsed_labels_4_VIZ.f90.
References m_work_time::append_elapsed_times(), m_work_time::elps1, ied_elapsed_pvr, iflag_pvr_time, and ist_elapsed_pvr.
Referenced by elpsed_label_4_viz().
elpsed_label_4_viz()
subroutine m_elapsed_labels_4_viz::elpsed_label_4_viz
Definition at line 56 of file m_elapsed_labels_4_VIZ.f90.
References elpsed_label_4_iso(), elpsed_label_4_lic(), elpsed_label_4_psf(), elpsed_label_4_pvr(), and elpsed_label_4_viz_outline().
Referenced by analyzer_psf::init_analyzer_psf(), analyzer_vtk_convert::init_analyzer_vtk_convert(), and init_sph_mhd_elapsed_label::set_sph_mhd_elapsed_label().
elpsed_label_4_viz_outline()
subroutine, private m_elapsed_labels_4_viz::elpsed_label_4_viz_outline private
Definition at line 85 of file m_elapsed_labels_4_VIZ.f90.
References m_work_time::append_elapsed_times(), m_work_time::elps1, ied_elapsed_viz, iflag_viz_time, and ist_elapsed_viz.
Referenced by elpsed_label_4_viz().
reset_elapse_after_init_iso()
subroutine, private m_elapsed_labels_4_viz::reset_elapse_after_init_iso private
Definition at line 264 of file m_elapsed_labels_4_VIZ.f90.
References iflag_iso_time, ist_elapsed_iso, and m_work_time::reset_elapsed_times().
Referenced by reset_elapse_after_init_viz().
reset_elapse_after_init_lic()
subroutine, private m_elapsed_labels_4_viz::reset_elapse_after_init_lic private
Definition at line 244 of file m_elapsed_labels_4_VIZ.f90.
References ied_elapsed_lic, iflag_lic_time, ist_elapsed_lic, and m_work_time::reset_elapsed_times().
Referenced by reset_elapse_after_init_viz().
reset_elapse_after_init_psf()
subroutine, private m_elapsed_labels_4_viz::reset_elapse_after_init_psf private
Definition at line 254 of file m_elapsed_labels_4_VIZ.f90.
References iflag_psf_time, ist_elapsed_psf, and m_work_time::reset_elapsed_times().
Referenced by reset_elapse_after_init_viz().
reset_elapse_after_init_pvr()
subroutine, private m_elapsed_labels_4_viz::reset_elapse_after_init_pvr private
Definition at line 234 of file m_elapsed_labels_4_VIZ.f90.
References ied_elapsed_pvr, iflag_pvr_time, ist_elapsed_pvr, and m_work_time::reset_elapsed_times().
reset_elapse_after_init_viz()
subroutine m_elapsed_labels_4_viz::reset_elapse_after_init_viz
Definition at line 70 of file m_elapsed_labels_4_VIZ.f90.
References reset_elapse_after_init_iso(), reset_elapse_after_init_lic(), reset_elapse_after_init_psf(), and reset_elapse_after_init_viz_top().
Referenced by init_sph_mhd_elapsed_label::reset_elapse_4_init_sph_mhd().
reset_elapse_after_init_viz_top()
subroutine, private m_elapsed_labels_4_viz::reset_elapse_after_init_viz_top private
Definition at line 224 of file m_elapsed_labels_4_VIZ.f90.
References ied_elapsed_viz, iflag_viz_time, ist_elapsed_viz, and m_work_time::reset_elapsed_times().
Referenced by reset_elapse_after_init_viz().
Variable Documentation
ied_elapsed_iso
integer(kind = kint), save m_elapsed_labels_4_viz::ied_elapsed_iso = 0
Definition at line 39 of file m_elapsed_labels_4_VIZ.f90.
Referenced by elpsed_label_4_iso().
ied_elapsed_lic
integer(kind = kint), save m_elapsed_labels_4_viz::ied_elapsed_lic = 0
Definition at line 31 of file m_elapsed_labels_4_VIZ.f90.
Referenced by elpsed_label_4_lic(), and reset_elapse_after_init_lic().
ied_elapsed_psf
integer(kind = kint), save m_elapsed_labels_4_viz::ied_elapsed_psf = 0
Definition at line 35 of file m_elapsed_labels_4_VIZ.f90.
Referenced by elpsed_label_4_psf().
ied_elapsed_pvr
integer(kind = kint), save m_elapsed_labels_4_viz::ied_elapsed_pvr = 0
Definition at line 27 of file m_elapsed_labels_4_VIZ.f90.
Referenced by elpsed_label_4_pvr(), and reset_elapse_after_init_pvr().
ied_elapsed_viz
integer(kind = kint), save m_elapsed_labels_4_viz::ied_elapsed_viz = 0
Definition at line 23 of file m_elapsed_labels_4_VIZ.f90.
Referenced by elpsed_label_4_viz_outline(), and reset_elapse_after_init_viz_top().
iflag_iso_time
logical, save m_elapsed_labels_4_viz::iflag_iso_time = .FALSE.
Definition at line 37 of file m_elapsed_labels_4_VIZ.f90.
Referenced by elpsed_label_4_iso(), t_isosurface::isosurf_visualize(), and reset_elapse_after_init_iso().
iflag_lic_time
logical, save m_elapsed_labels_4_viz::iflag_lic_time = .FALSE.
Definition at line 29 of file m_elapsed_labels_4_VIZ.f90.
Referenced by elpsed_label_4_lic(), and reset_elapse_after_init_lic().
iflag_psf_time
logical, save m_elapsed_labels_4_viz::iflag_psf_time = .FALSE.
Definition at line 33 of file m_elapsed_labels_4_VIZ.f90.
Referenced by elpsed_label_4_psf(), reset_elapse_after_init_psf(), t_cross_section::sectioning_initialize(), and t_cross_section::sectioning_visualize().
iflag_pvr_time
logical, save m_elapsed_labels_4_viz::iflag_pvr_time = .FALSE.
Definition at line 25 of file m_elapsed_labels_4_VIZ.f90.
Referenced by elpsed_label_4_pvr(), and reset_elapse_after_init_pvr().
iflag_viz_time
logical, save m_elapsed_labels_4_viz::iflag_viz_time = .FALSE.
Definition at line 21 of file m_elapsed_labels_4_VIZ.f90.
Referenced by elpsed_label_4_viz_outline(), t_viz_sections::init_visualize_surface(), t_sph_mhd_zonal_mean_viz::init_zonal_mean_sections(), reset_elapse_after_init_viz_top(), t_sph_mhd_zonal_mean_viz::sph_mhd_zonal_mean_section(), t_sph_mhd_zonal_mean_viz::sph_mhd_zonal_rms_section(), t_viz_vtk_convert::visualize_convert_vtk(), and t_viz_sections::visualize_surface().
ist_elapsed_iso
integer(kind = kint), save m_elapsed_labels_4_viz::ist_elapsed_iso = 0
Definition at line 38 of file m_elapsed_labels_4_VIZ.f90.
Referenced by elpsed_label_4_iso(), t_isosurface::isosurf_visualize(), and reset_elapse_after_init_iso().
ist_elapsed_lic
integer(kind = kint), save m_elapsed_labels_4_viz::ist_elapsed_lic = 0
Definition at line 30 of file m_elapsed_labels_4_VIZ.f90.
Referenced by elpsed_label_4_lic(), and reset_elapse_after_init_lic().
ist_elapsed_psf
integer(kind = kint), save m_elapsed_labels_4_viz::ist_elapsed_psf = 0
Definition at line 34 of file m_elapsed_labels_4_VIZ.f90.
Referenced by elpsed_label_4_psf(), reset_elapse_after_init_psf(), t_cross_section::sectioning_initialize(), and t_cross_section::sectioning_visualize().
ist_elapsed_pvr
integer(kind = kint), save m_elapsed_labels_4_viz::ist_elapsed_pvr = 0
Definition at line 26 of file m_elapsed_labels_4_VIZ.f90.
Referenced by elpsed_label_4_pvr(), and reset_elapse_after_init_pvr().
ist_elapsed_viz
integer(kind = kint), save m_elapsed_labels_4_viz::ist_elapsed_viz = 0
Definition at line 22 of file m_elapsed_labels_4_VIZ.f90.
Referenced by elpsed_label_4_viz_outline(), t_viz_sections::init_visualize_surface(), t_sph_mhd_zonal_mean_viz::init_zonal_mean_sections(), reset_elapse_after_init_viz_top(), t_sph_mhd_zonal_mean_viz::sph_mhd_zonal_mean_section(), t_sph_mhd_zonal_mean_viz::sph_mhd_zonal_rms_section(), t_viz_vtk_convert::visualize_convert_vtk(), and t_viz_sections::visualize_surface().