CALYPSO: t_sph_multi_fftw Module Reference
t_sph_multi_fftw Module Reference
Fourier transform using FFTW Ver.3.
Functions/Subroutines
subroutine init_mhd_multi_fftw (ncomp, ncomp_fwd, ncomp_bwd, nnod_rtp, nidx_rtp, irt_rtp_smp_stack, FFTW_t)
subroutine finalize_mhd_multi_fftw (FFTW_t)
subroutine verify_mhd_multi_fftw (ncomp, ncomp_fwd, ncomp_bwd, nnod_rtp, nidx_rtp, irt_rtp_smp_stack, FFTW_t)
subroutine mhd_multi_fwd_fftw_to_send (ncomp_fwd, nnod_rtp, nidx_rtp, irt_rtp_smp_stack, n_WS, irev_sr_rtp, X_rtp, WS, FFTW_t)
subroutine mhd_multi_back_fftw_from_recv (ncomp_bwd, nnod_rtp, nidx_rtp, irt_rtp_smp_stack, n_WR, irev_sr_rtp, WR, X_rtp, FFTW_t)
subroutine, private alloc_mul_fftw_plan (ncomp, nnod_rt, Nfft, FFTW_t)
Variables
real(kind=kreal), dimension(3) elapsed_fftw = (/0.0,0.0,0.0/)
Detailed Description
Fourier transform using FFTW Ver.3.
 ------------------------------------------------------------------
      subroutine init_MHD_multi_FFTW(ncomp, ncomp_fwd, ncomp_bwd,     &
     &          nnod_rtp, nidx_rtp, irt_rtp_smp_stack, FFTW_t)
      subroutine finalize_MHD_multi_FFTW(FFTW_t)
      subroutine verify_MHD_multi_FFTW(ncomp, ncomp_fwd, ncomp_bwd,   &
     &          nnod_rtp, nidx_rtp, irt_rtp_smp_stack, FFTW_t)
   wrapper subroutine for initierize FFT by FFTW
 ------------------------------------------------------------------
      subroutine MHD_multi_fwd_FFTW_to_send                           &
     &         (ncomp_fwd, nnod_rtp, nidx_rtp, irt_rtp_smp_stack,     &
     &          n_WS, irev_sr_rtp, X_rtp, WS, FFTW_t)
 ------------------------------------------------------------------
 wrapper subroutine for forward Fourier transform by FFTW3
   a_{k} = \frac{2}{Nfft} \sum_{j=0}^{Nfft-1} x_{j} \cos (\frac{2\pi j k}{Nfft})
   b_{k} = \frac{2}{Nfft} \sum_{j=0}^{Nfft-1} x_{j} \cos (\frac{2\pi j k}{Nfft})
   a_{0} = \frac{1}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
    K = Nfft/2....
   a_{k} = \frac{1}{Nfft} \sum_{j=0}^{Nfft-1} x_{j} \cos (\frac{2\pi j k}{Nfft})
 ------------------------------------------------------------------
      subroutine MHD_multi_back_FFTW_from_recv                        &
     &         (ncomp_bwd, nnod_rtp, nidx_rtp, irt_rtp_smp_stack,     &
     &          n_WR, irev_sr_rtp, WR, X_rtp, FFTW_t)
 ------------------------------------------------------------------
 wrapper subroutine for backward Fourier transform by FFTW3
   x_{k} = a_{0} + (-1)^{j} a_{Nfft/2} + sum_{k=1}^{Nfft/2-1}
          (a_{k} \cos(2\pijk/Nfft) + b_{k} \sin(2\pijk/Nfft))
 ------------------------------------------------------------------
       i = 1:     a_{0}
       i = 2:     a_{Nfft/2}
       i = 3:     a_{1}
       i = 4:     b_{1}
       ...
       i = 2*k+1: a_{k}
       i = 2*k+2: b_{k}
       ...
       i = Nfft-1:   a_{Nfft/2-1}
       i = Nfft:     b_{Nfft/2-1}
 ------------------------------------------------------------------
Parameters
Nstacksmp(0:np_smp) End number for each SMP process
Ncomp Number of components for Fourier transforms
Nfft Data length for eadh FFT
X(Ncomp,Nfft) Data for Fourier transform
Function/Subroutine Documentation
alloc_mul_fftw_plan()
subroutine, private t_sph_multi_fftw::alloc_mul_fftw_plan (integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nnod_rt, integer(kind = kint), intent(in) Nfft, type(work_for_sgl_fftw), intent(inout) FFTW_t) private
Definition at line 313 of file t_sph_multi_FFTW.F90.
References m_machine_parameter::np_smp.
Referenced by init_mhd_multi_fftw().
finalize_mhd_multi_fftw()
subroutine t_sph_multi_fftw::finalize_mhd_multi_fftw (type(work_for_sgl_fftw), intent(inout) FFTW_t)
Definition at line 138 of file t_sph_multi_FFTW.F90.
References t_sph_single_fftw::dealloc_fftw_plan(), t_sph_single_fftw::dealloc_tmp_ordering_fftw(), and m_machine_parameter::np_smp.
Referenced by verify_mhd_multi_fftw().
init_mhd_multi_fftw()
subroutine t_sph_multi_fftw::init_mhd_multi_fftw (integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) ncomp_fwd, integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(3), intent(in) nidx_rtp, integer(kind = kint), dimension(0:np_smp), intent(in) irt_rtp_smp_stack, type(work_for_sgl_fftw), intent(inout) FFTW_t)
Definition at line 87 of file t_sph_multi_FFTW.F90.
References alloc_mul_fftw_plan(), t_sph_single_fftw::alloc_tmp_ordering_fftw(), and m_constants::one.
Referenced by verify_mhd_multi_fftw().
mhd_multi_back_fftw_from_recv()
subroutine t_sph_multi_fftw::mhd_multi_back_fftw_from_recv (integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(3), intent(in) nidx_rtp, integer(kind = kint), dimension(0:np_smp), intent(in) irt_rtp_smp_stack, integer(kind = kint), intent(in) n_WR, integer(kind = kint), dimension(nnod_rtp), intent(in) irev_sr_rtp, real (kind=kreal), dimension(n_wr), intent(inout) WR, real(kind = kreal), dimension(nidx_rtp(3),irt_rtp_smp_stack(np_smp)*ncomp_bwd), intent(inout) X_rtp, type(work_for_sgl_fftw), intent(inout) FFTW_t)
Definition at line 248 of file t_sph_multi_FFTW.F90.
References m_constants::half, and m_constants::zero.
mhd_multi_fwd_fftw_to_send()
subroutine t_sph_multi_fftw::mhd_multi_fwd_fftw_to_send (integer(kind = kint), intent(in) ncomp_fwd, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(3), intent(in) nidx_rtp, integer(kind = kint), dimension(0:np_smp), intent(in) irt_rtp_smp_stack, integer(kind = kint), intent(in) n_WS, integer(kind = kint), dimension(nnod_rtp), intent(in) irev_sr_rtp, real(kind = kreal), dimension(nidx_rtp(3),irt_rtp_smp_stack(np_smp)*ncomp_fwd), intent(in) X_rtp, real (kind=kreal), dimension(n_ws), intent(inout) WS, type(work_for_sgl_fftw), intent(inout) FFTW_t)
Definition at line 185 of file t_sph_multi_FFTW.F90.
References m_constants::two.
verify_mhd_multi_fftw()
subroutine t_sph_multi_fftw::verify_mhd_multi_fftw (integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) ncomp_fwd, integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(3), intent(in) nidx_rtp, integer(kind = kint), dimension(0:np_smp), intent(in) irt_rtp_smp_stack, type(work_for_sgl_fftw), intent(inout) FFTW_t)
Definition at line 158 of file t_sph_multi_FFTW.F90.
References finalize_mhd_multi_fftw(), and init_mhd_multi_fftw().
Variable Documentation
elapsed_fftw
real(kind = kreal), dimension(3) t_sph_multi_fftw::elapsed_fftw = (/0.0,0.0,0.0/)
Definition at line 77 of file t_sph_multi_FFTW.F90.