CALYPSO: sph_prt_fftpack5 Module Reference
sph_prt_fftpack5 Module Reference
Fourier transform using FFTPACK5.
Functions/Subroutines
subroutine init_prt_fftpack5 (sph_rtp, comm_rtp, ncomp_bwd, ncomp_fwd, fftpack_t)
subroutine verify_prt_fftpack5 (sph_rtp, comm_rtp, ncomp_bwd, ncomp_fwd, fftpack_t)
subroutine prt_rfftmf_to_send (sph_rtp, comm_rtp, ncomp_fwd, n_WS, X_rtp, WS, fftpack_t)
subroutine prt_rfftmb_from_recv (sph_rtp, comm_rtp, ncomp_bwd, n_WR, WR, X_rtp, fftpack_t)
Detailed Description
Fourier transform using FFTPACK5.
  ---------------------------------------------------------------------
      subroutine init_prt_FFTPACK5(sph_rtp, comm_rtp,                 &
     &                             ncomp_bwd, ncomp_fwd, fftpack_t)
      subroutine verify_prt_FFTPACK5(sph_rtp, comm_rtp,               &
     &                               ncomp_bwd, ncomp_fwd, fftpack_t)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_comm_tbl), intent(in) :: comm_rtp
        type(work_for_fftpack), intent(inout) :: fftpack_t
 ------------------------------------------------------------------
   wrapper subroutine for initierize FFT
 ------------------------------------------------------------------
      subroutine prt_RFFTMF_to_send(sph_rtp, comm_rtp, ncomp_fwd,     &
     &          n_WS, X_rtp, WS, fftpack_t)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_comm_tbl), intent(in) :: comm_rtp
        type(work_for_fftpack), intent(inout) :: fftpack_t
 ------------------------------------------------------------------
 wrapper subroutine for forward Fourier transform by FFTPACK5
   a_{k} = \frac{2}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
          *  \cos (\frac{2\pi j k}{Nfft})
   b_{k} = \frac{2}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
          *  \cos (\frac{2\pi j k}{Nfft})
   a_{0} = \frac{1}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
    K = Nfft/2....
   a_{k} = \frac{1}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
          * \cos (\frac{2\pi j k}{Nfft})
 ------------------------------------------------------------------
      subroutine prt_RFFTMB_from_recv(sph_rtp, comm_rtp, ncomp_bwd,   &
     &                                n_WR, WR, X_rtp, fftpack_t)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_comm_tbl), intent(in) :: comm_rtp
        type(work_for_fftpack), intent(inout) :: fftpack_t
 ------------------------------------------------------------------
 wrapper subroutine for backward Fourier transform by FFTPACK5
   x_{k} = a_{0} + (-1)^{j} a_{Nfft/2} + sum_{k=1}^{Nfft/2-1}
          (a_{k} \cos(2\pijk/Nfft) + b_{k} \sin(2\pijk/Nfft))
 ------------------------------------------------------------------
       i = 1:     a_{0}
       i = 2:     a_{Nfft/2}
       i = 3:     a_{1}
       i = 4:     b_{1}
       ...
       i = 2*k+1: a_{k}
       i = 2*k+2: b_{k}
       ...
       i = Nfft-1:   a_{Nfft/2-1}
       i = Nfft:     b_{Nfft/2-1}
 ------------------------------------------------------------------
Parameters
Nsmp Number of SMP processors
Nstacksmp(0:Nsmp) End number for each SMP process
M Number of components for Fourier transforms
Nfft Data length for eadh FFT
X(M,Nfft) Data for Fourier transform
Function/Subroutine Documentation
init_prt_fftpack5()
subroutine sph_prt_fftpack5::init_prt_fftpack5 (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), intent(in) ncomp_fwd, type(work_for_fftpack), intent(inout) fftpack_t)
Definition at line 100 of file sph_prt_FFTPACK5.f90.
References t_sph_comm_table_from_fft::alloc_comm_table_sph_fft(), t_sph_fftpack5::init_sph_fftpack5(), m_machine_parameter::np_smp, and set_comm_table_prt_fftpack::set_comm_item_prt_4_fftpack().
Referenced by t_sph_fft_selector::init_sph_fft_select().
prt_rfftmb_from_recv()
subroutine sph_prt_fftpack5::prt_rfftmb_from_recv (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(inout) WR, real(kind = kreal), dimension(sph_rtp%nnod_rtp,ncomp_bwd), intent(inout) X_rtp, type(work_for_fftpack), intent(inout) fftpack_t)
Definition at line 212 of file sph_prt_FFTPACK5.f90.
References copy_rtp_data_to_fftpack::copy_fftpack_to_prt_comp(), set_comm_table_prt_fftpack::copy_prt_fftpack_from_recv(), m_elapsed_labels_sph_trns::iflag_fft_time, m_constants::ione, m_elapsed_labels_sph_trns::ist_elapsed_fft, m_machine_parameter::np_smp, and rfftmb().
Referenced by t_sph_fft_selector::back_fft_select_from_recv().
prt_rfftmf_to_send()
subroutine sph_prt_fftpack5::prt_rfftmf_to_send (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, integer(kind = kint), intent(in) ncomp_fwd, integer(kind = kint), intent(in) n_WS, real(kind = kreal), dimension(sph_rtp%nnod_rtp,ncomp_fwd), intent(in) X_rtp, real (kind=kreal), dimension(n_ws), intent(inout) WS, type(work_for_fftpack), intent(inout) fftpack_t)
Definition at line 156 of file sph_prt_FFTPACK5.f90.
References t_sph_comm_table_from_fft::copy_all_prt_fft_to_send(), copy_rtp_data_to_fftpack::copy_fftpack_to_prt_comp(), m_elapsed_labels_sph_trns::iflag_fft_time, m_constants::ione, m_elapsed_labels_sph_trns::ist_elapsed_fft, m_machine_parameter::np_smp, and rfftmf().
Referenced by t_sph_fft_selector::fwd_fft_select_to_send().
verify_prt_fftpack5()
subroutine sph_prt_fftpack5::verify_prt_fftpack5 (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), intent(in) ncomp_fwd, type(work_for_fftpack), intent(inout) fftpack_t)
Definition at line 126 of file sph_prt_FFTPACK5.f90.
References t_sph_comm_table_from_fft::alloc_comm_table_sph_fft(), t_sph_comm_table_from_fft::dealloc_comm_table_sph_fft(), m_machine_parameter::np_smp, set_comm_table_prt_fftpack::set_comm_item_prt_4_fftpack(), and t_sph_fftpack5::verify_sph_fftpack5().
Referenced by t_sph_fft_selector::verify_sph_fft_select().