CALYPSO: t_control_array_charareal Module Reference
t_control_array_charareal Module Reference
Data Types
type ctl_array_cr
Structure for charactor and real control array.
type read_chara_real_item
structure of control item with three characters
Functions/Subroutines
subroutine read_charareal_ctl_type (c_buf, label, cr_item)
subroutine write_charareal_ctl_type (id_file, level, label, cr_item)
subroutine copy_charareal_ctl (org_cr, new_cr)
subroutine alloc_control_array_c_r (array_cr)
subroutine dealloc_control_array_c_r (array_cr)
subroutine read_control_array_c_r (id_control, label, array_cr, c_buf)
subroutine write_control_array_c_r (id_control, level, label, array_cr)
subroutine append_control_array_c_r (read_cr, array_cr)
subroutine dup_control_array_c_r (org_cr, tgt_cr)
subroutine copy_control_array_c_r (num_copy, org_cr, tgt_cr)
subroutine append_control_item_c_r (read_cr, array_cr)
Function/Subroutine Documentation
alloc_control_array_c_r()
subroutine t_control_array_charareal::alloc_control_array_c_r (type(ctl_array_cr), intent(inout) array_cr)
Definition at line 137 of file t_control_array_charareal.f90.
Referenced by append_control_array_c_r(), bcast_control_arrays::bcast_ctl_array_cr(), dup_control_array_c_r(), and read_control_array_c_r().
append_control_array_c_r()
subroutine t_control_array_charareal::append_control_array_c_r (type(read_chara_real_item), intent(inout) read_cr, type(ctl_array_cr), intent(inout) array_cr)
Definition at line 229 of file t_control_array_charareal.f90.
References alloc_control_array_c_r(), append_control_item_c_r(), copy_control_array_c_r(), and dealloc_control_array_c_r().
Referenced by read_control_array_c_r().
append_control_item_c_r()
subroutine t_control_array_charareal::append_control_item_c_r (type(read_chara_real_item), intent(in) read_cr, type(ctl_array_cr), intent(inout) array_cr)
Definition at line 284 of file t_control_array_charareal.f90.
Referenced by append_control_array_c_r().
copy_charareal_ctl()
subroutine t_control_array_charareal::copy_charareal_ctl (type(read_chara_real_item), intent(in) org_cr, type(read_chara_real_item), intent(inout) new_cr)
Definition at line 122 of file t_control_array_charareal.f90.
copy_control_array_c_r()
subroutine t_control_array_charareal::copy_control_array_c_r (integer(kind = kint), intent(in) num_copy, type(ctl_array_cr), intent(in) org_cr, type(ctl_array_cr), intent(inout) tgt_cr)
Definition at line 268 of file t_control_array_charareal.f90.
Referenced by append_control_array_c_r(), and dup_control_array_c_r().
dealloc_control_array_c_r()
subroutine t_control_array_charareal::dealloc_control_array_c_r (type(ctl_array_cr), intent(inout) array_cr)
Definition at line 152 of file t_control_array_charareal.f90.
Referenced by append_control_array_c_r(), t_control_data_4_psf_def::dealloc_cont_dat_4_psf_def(), t_ctl_data_mhd_forces::dealloc_coriolis_ctl(), t_ctl_data_mhd_normalize::dealloc_dimless_ctl(), t_ctl_data_mhd_forces::dealloc_gravity_ctl(), t_ctl_data_induct_norm::dealloc_induction_ctl(), t_ctl_data_mhd_forces::dealloc_magneto_ctl(), t_ctl_data_momentum_norm::dealloc_momentum_ctl(), and t_ctl_data_termal_norm::dealloc_thermal_ctl().
dup_control_array_c_r()
subroutine t_control_array_charareal::dup_control_array_c_r (type(ctl_array_cr), intent(in) org_cr, type(ctl_array_cr), intent(inout) tgt_cr)
Definition at line 254 of file t_control_array_charareal.f90.
References alloc_control_array_c_r(), and copy_control_array_c_r().
Referenced by t_control_data_4_psf_def::dup_control_4_psf_def().
read_charareal_ctl_type()
subroutine t_control_array_charareal::read_charareal_ctl_type (type(buffer_for_control), intent(in) c_buf, character(len=kchara), intent(in) label, type(read_chara_real_item), intent(inout) cr_item)
Definition at line 78 of file t_control_array_charareal.f90.
References m_machine_parameter::iflag_debug.
Referenced by read_control_array_c_r().
read_control_array_c_r()
subroutine t_control_array_charareal::read_control_array_c_r (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) label, type(ctl_array_cr), intent(inout) array_cr, type(buffer_for_control), intent(inout) c_buf)
Definition at line 166 of file t_control_array_charareal.f90.
References alloc_control_array_c_r(), append_control_array_c_r(), t_read_control_elements::check_array_flag(), t_read_control_elements::check_end_array_flag(), t_read_control_elements::load_one_line_from_control(), and read_charareal_ctl_type().
Referenced by t_ctl_data_termal_norm::read_composition_eq_ctl(), t_ctl_data_mhd_forces::read_coriolis_ctl(), t_ctl_data_mhd_normalize::read_dimless_ctl(), t_ctl_data_mhd_forces::read_gravity_ctl(), t_ctl_data_induct_norm::read_induction_ctl(), t_ctl_data_mhd_forces::read_magneto_ctl(), t_ctl_data_momentum_norm::read_momentum_ctl(), t_control_data_4_psf_def::read_section_def_control(), and t_ctl_data_termal_norm::read_thermal_ctl().
write_charareal_ctl_type()
subroutine t_control_array_charareal::write_charareal_ctl_type (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, type(read_chara_real_item), intent(in) cr_item)
Definition at line 103 of file t_control_array_charareal.f90.
References write_control_elements::write_chara_real_ctl_item().
write_control_array_c_r()
subroutine t_control_array_charareal::write_control_array_c_r (integer(kind = kint), intent(in) id_control, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, type(ctl_array_cr), intent(in) array_cr)
Definition at line 200 of file t_control_array_charareal.f90.
References write_control_elements::write_array_flag_for_ctl(), write_control_elements::write_chara_real_ctl_item(), and write_control_elements::write_end_array_flag_for_ctl().