CALYPSO: select_exp_scalar_icb Module Reference
select_exp_scalar_icb Module Reference
Evaluate radial delivatives.
Functions/Subroutines
subroutine set_icb_scalar_sph_crank (sph_rj, sph_bc, ICB_Sspec, coef_f, coef_d, dt, coef_imp, is_field, rj_fld)
subroutine sel_icb_radial_grad_scalar (sph_rj, sph_bc, ICB_Sspec, fdm2_center, g_sph_rj, is_fld, is_grad, rj_fld)
subroutine sel_icb_sph_scalar_diffusion (sph_rj, sph_bc, ICB_Sspec, fdm2_center, g_sph_rj, coef_diffuse, is_fld, is_diffuse, rj_fld)
subroutine sel_icb_sph_scalar_advect (sph_rj, sph_bc, ICB_Sspec, fdm2_center, g_sph_rj, is_flux, is_advect, rj_fld)
Detailed Description
Evaluate radial delivatives.
      subroutine set_ICB_scalar_sph_crank(sph_rj, sph_bc, ICB_Sspec,  &
     &          coef_f, coef_d, dt, coef_imp, is_field, rj_fld)
        type(sph_rj_grid), intent(in) :: sph_rj
        type(sph_boundary_type), intent(in) :: sph_bc
        type(sph_scalar_BC_coef), intent(in) :: ICB_Sspec
        type(phys_data), intent(inout) :: rj_fld
      subroutine sel_ICB_radial_grad_scalar                           &
     &         (sph_rj, sph_bc, ICB_Sspec, fdm2_center, g_sph_rj,     &
     &          is_fld, is_grad, rj_fld)
          Input:    is_fld
          Solution: is_grad
        type(sph_boundary_type), intent(in) :: sph_bc
        type(sph_rj_grid), intent(in) :: sph_rj
        type(fdm2_center_mat), intent(in) :: fdm2_center
      subroutine sel_ICB_sph_scalar_diffusion                         &
     &         (sph_rj, sph_bc, ICB_Sspec, fdm2_center,               &
     &          g_sph_rj, coef_diffuse, is_fld, is_diffuse, rj_fld)
          Input:    is_fld
          Solution: is_diffusee
      subroutine sel_ICB_sph_scalar_advect                            &
     &         (sph_rj, sph_bc, ICB_Sspec, fdm2_center, g_sph_rj,     &
     &          is_flux, is_advect, rj_fld)
          Input:    is_flux
          Solution: is_advect
        type(sph_boundary_type), intent(in) :: sph_bc
        type(sph_rj_grid), intent(in) :: sph_rj
        type(phys_data), intent(inout) :: rj_fld
        type(fdm2_center_mat), intent(in) :: fdm2_center
Parameters
sph_bc Structure for basic boundary condition parameters
coef_diffuse Diffusion coefficient
is_fld Spherical hermonics data address for input vector
is_grad Spherical hermonics data address for gradient
is_diffuse Input spectr diffusiton term address
is_flux Spherical hermonics data address for input flux
is_advect Spherical hermonics data address for advection
Function/Subroutine Documentation
sel_icb_radial_grad_scalar()
subroutine select_exp_scalar_icb::sel_icb_radial_grad_scalar (type(sph_rj_grid), intent(in) sph_rj, type(sph_boundary_type), intent(in) sph_bc, type(sph_scalar_bc_coef), intent(in) ICB_Sspec, type(fdm2_center_mat), intent(in) fdm2_center, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_grad, type(phys_data), intent(inout) rj_fld)
Definition at line 122 of file select_exp_scalar_ICB.f90.
References cal_sph_exp_center::cal_sph_center1_grad22(), cal_sph_exp_fixed_scalar::dsdr_sph_fix_scalar_in_2(), cal_sph_exp_fixed_flux::dsdr_sph_in_fix_flux_2(), cal_sph_exp_fixed_scalar::dsdr_sph_lm0_fix_scalar_in_2(), cal_sph_exp_center::dsdr_sph_lm0_fixed_ctr_2(), cal_sph_exp_fixed_flux::dsdr_sph_lm0_in_fix_flux_2(), t_boundary_params_sph_mhd::iflag_evolve_flux, t_boundary_params_sph_mhd::iflag_fixed_flux, t_boundary_params_sph_mhd::iflag_sph_fill_center, t_boundary_params_sph_mhd::iflag_sph_fix_center, and cal_sph_exp_center::sph0_scalar_fill_ctr_grad2().
Referenced by const_sph_radial_grad::const_radial_grad_scalar().
sel_icb_sph_scalar_advect()
subroutine select_exp_scalar_icb::sel_icb_sph_scalar_advect (type(sph_rj_grid), intent(in) sph_rj, type(sph_boundary_type), intent(in) sph_bc, type(sph_scalar_bc_coef), intent(in) ICB_Sspec, type(fdm2_center_mat), intent(in) fdm2_center, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, integer(kind = kint), intent(in) is_flux, integer(kind = kint), intent(in) is_advect, type(phys_data), intent(inout) rj_fld)
Definition at line 250 of file select_exp_scalar_ICB.f90.
References cal_sph_exp_fixed_flux::cal_div_sph_in_fix_flux_2(), cal_sph_exp_center::cal_sph_div_flux_4_fix_ctr(), cal_sph_exp_fixed_scalar::cal_sph_div_flux_4_fix_in(), cal_sph_exp_center::cal_sph_filled_center_diffuse2(), cal_sph_exp_center::cal_sph_fixed_center_diffuse2(), m_constants::dminus, t_boundary_params_sph_mhd::iflag_evolve_flux, t_boundary_params_sph_mhd::iflag_fixed_flux, t_boundary_params_sph_mhd::iflag_sph_fill_center, and t_boundary_params_sph_mhd::iflag_sph_fix_center.
Referenced by const_sph_divergence::const_sph_scalar_advect().
sel_icb_sph_scalar_diffusion()
subroutine select_exp_scalar_icb::sel_icb_sph_scalar_diffusion (type(sph_rj_grid), intent(in) sph_rj, type(sph_boundary_type), intent(in) sph_bc, type(sph_scalar_bc_coef), intent(in) ICB_Sspec, type(fdm2_center_mat), intent(in) fdm2_center, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, real(kind = kreal), intent(in) coef_diffuse, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_diffuse, type(phys_data), intent(inout) rj_fld)
Definition at line 193 of file select_exp_scalar_ICB.f90.
References cal_sph_exp_center::cal_sph_filled_center_diffuse2(), cal_sph_exp_fixed_scalar::cal_sph_fix_scalar_in_diffuse2(), cal_sph_exp_center::cal_sph_fixed_center1_diffuse2(), cal_sph_exp_center::cal_sph_fixed_center_diffuse2(), cal_sph_exp_fixed_flux::cal_sph_in_fix_flux_diffuse2(), t_boundary_params_sph_mhd::iflag_evolve_flux, t_boundary_params_sph_mhd::iflag_fixed_flux, t_boundary_params_sph_mhd::iflag_sph_fill_center, and t_boundary_params_sph_mhd::iflag_sph_fix_center.
Referenced by const_sph_diffusion::const_sph_scalar_diffusion().
set_icb_scalar_sph_crank()
subroutine select_exp_scalar_icb::set_icb_scalar_sph_crank (type(sph_rj_grid), intent(in) sph_rj, type(sph_boundary_type), intent(in) sph_bc, type(sph_scalar_bc_coef), intent(in) ICB_Sspec, real(kind = kreal), intent(in) coef_f, real(kind = kreal), intent(in) coef_d, real(kind = kreal), intent(in) dt, real(kind = kreal), intent(in) coef_imp, integer(kind = kint), intent(in) is_field, type(phys_data), intent(inout) rj_fld)
Definition at line 72 of file select_exp_scalar_ICB.f90.
References set_scalar_boundary_sph::adjust_in_fixed_flux_sph(), cal_sph_exp_center::cal_sph_fixed_center(), t_boundary_params_sph_mhd::iflag_evolve_field, t_boundary_params_sph_mhd::iflag_fixed_field, t_boundary_params_sph_mhd::iflag_fixed_flux, t_boundary_params_sph_mhd::iflag_sph_fix_center, m_constants::ione, set_scalar_boundary_sph::poisson_in_fixed_flux_sph(), and set_scalar_boundary_sph::set_fixed_scalar_sph().
Referenced by cal_sol_sph_fluid_crank::cal_sol_scalar_sph_crank().