CALYPSO: set_reference_sph_mhd Module Reference
set_reference_sph_mhd Module Reference
Convert temperature data using reference temperature.
Functions/Subroutines
subroutine adjust_by_ave_pressure_on_cmb (kr_in, kr_out, idx_rj_degree_zero, nidx_rj, i_press, n_point, ntot_phys_rj, d_rj)
subroutine adjust_sph_temp_bc_by_reftemp (idx_rj_degree_zero, nri, reftemp_rj, sph_bc, ICB_Sspec, CMB_Sspec, ICB_Sevo, CMB_Sevo)
subroutine chenge_temp_to_per_temp_sph (idx_rj_degree_zero, nidx_rj, radius_1d_rj_r, reftemp_rj, is_temp, is_grad_t, ids_grad_t, is_par_temp, is_grad_part_t, ids_grad_part_t, n_point, ntot_phys_rj, d_rj)
subroutine transfer_per_temp_to_temp_sph (idx_rj_degree_zero, nidx_rj, radius_1d_rj_r, reftemp_rj, is_temp, is_grad_t, ids_grad_t, is_par_temp, is_grad_part_t, ids_grad_part_t, n_point, ntot_phys_rj, d_rj)
subroutine delete_zero_degree_vect (is_fld, idx_rj_degree_zero, n_point, nidx_rj, ntot_phys_rj, d_rj)
subroutine delete_zero_degree_comp (is_fld, idx_rj_degree_zero, n_point, nidx_rj, ntot_phys_rj, d_rj)
Detailed Description
Convert temperature data using reference temperature.
      subroutine adjust_by_ave_pressure_on_CMB(kr_in, kr_out,         &
     &          idx_rj_degree_zero, nidx_rj, i_press,                 &
     &          n_point, ntot_phys_rj, d_rj)
      subroutine adjust_sph_temp_bc_by_reftemp                        &
     &         (idx_rj_degree_zero, nri, reftemp_rj, sph_bc,          &
     &          ICB_Sspec, CMB_Sspec, ICB_Sevo, CMB_Sevo)
        type(sph_boundary_type), intent(in) :: sph_bc
        type(sph_scalar_BC_coef), intent(inout) :: ICB_Sspec, CMB_Sspec
        type(sph_scalar_BC_evo), intent(inout) :: ICB_Sevo, CMB_Sevo
      subroutine chenge_temp_to_per_temp_sph(idx_rj_degree_zero,      &
     &          nidx_rj, radius_1d_rj_r, reftemp_rj,                  &
     &          is_temp, is_grad_t, ids_grad_t,                       &
     &          is_par_temp, is_grad_part_t, ids_grad_part_t,         &
     &          n_point, ntot_phys_rj, d_rj)
        d_rj(inod,is_tempp):        T => \Theta = T - T0
        d_rj(inod,is_par_temp):    \Theta = T - T0
        d_rj(inod,is_grad_t):      T => d \Theta / dr
        d_rj(inod,is_grad_part_t): d \Theta / dr
      subroutine transfer_per_temp_to_temp_sph(idx_rj_degree_zero,    &
     &          nidx_rj, radius_1d_rj_r, reftemp_rj,                  &
     &          is_temp, is_grad_t, ids_grad_t,                       &
     &          is_par_temp, is_grad_part_t, ids_grad_part_t,         &
     &          n_point, ntot_phys_rj, d_rj)
        d_rj(inod,is_temp):        \Theta = T - T0 => T
        d_rj(inod,is_par_temp):    \Theta = T - T0
        d_rj(inod,is_grad_t):      d \Theta / dr   => dT / dr
        d_rj(inod,is_grad_part_t): d \Theta / dr
      subroutine delete_zero_degree_vect(is_fld, idx_rj_degree_zero,  &
     &          n_point, nidx_rj, ntot_phys_rj, d_rj)
      subroutine delete_zero_degree_comp(is_fld, idx_rj_degree_zero,  &
     &          n_point, nidx_rj, ntot_phys_rj, d_rj)
Parameters
sph_bc_S Structure for basic boundary condition parameters for scalar
is_fld Address of poloidal component
Parameters
ntot_phys_rj Total number of components
d_rj Spectrum data
Function/Subroutine Documentation
adjust_by_ave_pressure_on_cmb()
subroutine set_reference_sph_mhd::adjust_by_ave_pressure_on_cmb (integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) kr_out, integer(kind = kint), intent(in) idx_rj_degree_zero, integer(kind = kint), dimension(2), intent(in) nidx_rj, integer(kind = kint), intent(in) i_press, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 70 of file set_reference_sph_mhd.f90.
Referenced by adjust_reference_fields::adjust_press_by_average_on_cmb(), and cal_sol_sph_fluid_crank::cal_sol_pressure_by_div_v().
adjust_sph_temp_bc_by_reftemp()
subroutine set_reference_sph_mhd::adjust_sph_temp_bc_by_reftemp (integer(kind = kint), intent(in) idx_rj_degree_zero, integer(kind = kint), intent(in) nri, real(kind=kreal), dimension(nri,0:2), intent(in) reftemp_rj, type(sph_boundary_type), intent(in) sph_bc, type(sph_scalar_bc_coef), intent(inout) ICB_Sspec, type(sph_scalar_bc_coef), intent(inout) CMB_Sspec, type(sph_scalar_bc_evo), intent(inout) ICB_Sevo, type(sph_scalar_bc_evo), intent(inout) CMB_Sevo)
Definition at line 101 of file set_reference_sph_mhd.f90.
References t_boundary_params_sph_mhd::iflag_evolve_field, t_boundary_params_sph_mhd::iflag_evolve_flux, t_boundary_params_sph_mhd::iflag_fixed_field, t_boundary_params_sph_mhd::iflag_fixed_flux, and t_boundary_params_sph_mhd::iflag_sph_fix_center.
Referenced by init_radial_infos_sph_mhd::init_reference_temps().
chenge_temp_to_per_temp_sph()
subroutine set_reference_sph_mhd::chenge_temp_to_per_temp_sph (integer(kind = kint), intent(in) idx_rj_degree_zero, integer(kind = kint), dimension(2), intent(in) nidx_rj, real(kind=kreal), dimension(nidx_rj(1)), intent(in) radius_1d_rj_r, real(kind=kreal), dimension(nidx_rj(1),0:2), intent(in) reftemp_rj, integer(kind = kint), intent(in) is_temp, integer(kind = kint), intent(in) is_grad_t, integer(kind = kint), intent(in) ids_grad_t, integer(kind = kint), intent(in) is_par_temp, integer(kind = kint), intent(in) is_grad_part_t, integer(kind = kint), intent(in) ids_grad_part_t, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 159 of file set_reference_sph_mhd.f90.
References m_constants::two.
Referenced by adjust_reference_fields::sync_scalar_by_pert_sph().
delete_zero_degree_comp()
subroutine set_reference_sph_mhd::delete_zero_degree_comp (integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) idx_rj_degree_zero, integer(kind = kint), intent(in) n_point, integer(kind = kint), dimension(2), intent(in) nidx_rj, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 277 of file set_reference_sph_mhd.f90.
References m_constants::zero.
Referenced by adjust_reference_fields::delete_sphere_average().
delete_zero_degree_vect()
subroutine set_reference_sph_mhd::delete_zero_degree_vect (integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) idx_rj_degree_zero, integer(kind = kint), intent(in) n_point, integer(kind = kint), dimension(2), intent(in) nidx_rj, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 252 of file set_reference_sph_mhd.f90.
References m_constants::zero.
Referenced by cal_sol_sph_fluid_crank::cal_sol_magne_sph_crank(), and cal_sol_sph_fluid_crank::cal_sol_velo_by_vort_sph_crank().
transfer_per_temp_to_temp_sph()
subroutine set_reference_sph_mhd::transfer_per_temp_to_temp_sph (integer(kind = kint), intent(in) idx_rj_degree_zero, integer(kind = kint), dimension(2), intent(in) nidx_rj, real(kind=kreal), dimension(nidx_rj(1)), intent(in) radius_1d_rj_r, real(kind=kreal), dimension(nidx_rj(1),0:2), intent(in) reftemp_rj, integer(kind = kint), intent(in) is_temp, integer(kind = kint), intent(in) is_grad_t, integer(kind = kint), intent(in) ids_grad_t, integer(kind = kint), intent(in) is_par_temp, integer(kind = kint), intent(in) is_grad_part_t, integer(kind = kint), intent(in) ids_grad_part_t, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 205 of file set_reference_sph_mhd.f90.
References m_constants::two.
Referenced by adjust_reference_fields::trans_pert_to_scalar_sph().