CALYPSO: cal_sph_zonal_ave_rms_data Module Reference
cal_sph_zonal_ave_rms_data Module Reference
Get zonal mean and RMS fields in spherical grid.
Functions/Subroutines
subroutine cal_sph_zonal_ave_data_rin (nidx_rtp, nnod, numdir, irtp_fld, d_rtp)
subroutine cal_sph_zonal_ave_data_pin (nidx_rtp, nnod, numdir, irtp_fld, d_rtp)
subroutine cal_sph_zonal_rms_data_rin (nidx_rtp, nnod, numdir, irtp_fld, d_rtp)
subroutine cal_sph_zonal_rms_data_pin (nidx_rtp, nnod, numdir, irtp_fld, d_rtp)
Detailed Description
Get zonal mean and RMS fields in spherical grid.
      subroutine cal_sph_zonal_ave_data_rin                           &
     &         (nidx_rtp, nnod, numdir, irtp_fld, d_rtp)
      subroutine cal_sph_zonal_ave_data_pin                           &
     &         (nidx_rtp, nnod, numdir, irtp_fld, d_rtp)
      subroutine cal_sph_zonal_rms_data_rin                           &
     &         (nidx_rtp, nnod, numdir, irtp_fld, d_rtp)
      subroutine cal_sph_zonal_rms_data_pin                           &
     &         (nidx_rtp, nnod, numdir, irtp_fld, d_rtp)
Parameters
numdir Number of component of field
irtp_fld Start address for field \(f(\r,\theta\phi) \)
Function/Subroutine Documentation
cal_sph_zonal_ave_data_pin()
subroutine cal_sph_zonal_ave_rms_data::cal_sph_zonal_ave_data_pin (integer(kind = kint), dimension(3), intent(in) nidx_rtp, integer(kind = kint), intent(in) nnod, integer(kind = kint), intent(in) numdir, integer(kind = kint), intent(in) irtp_fld, real(kind = kreal), dimension(nnod,numdir), intent(inout) d_rtp)
Definition at line 87 of file cal_sph_zonal_ave_rms_data.f90.
References m_constants::one.
Referenced by sph_rtp_zonal_rms_data::zonal_mean_all_rtp_field().
cal_sph_zonal_ave_data_rin()
subroutine cal_sph_zonal_ave_rms_data::cal_sph_zonal_ave_data_rin (integer(kind = kint), dimension(3), intent(in) nidx_rtp, integer(kind = kint), intent(in) nnod, integer(kind = kint), intent(in) numdir, integer(kind = kint), intent(in) irtp_fld, real(kind = kreal), dimension(nnod,numdir), intent(inout) d_rtp)
Definition at line 38 of file cal_sph_zonal_ave_rms_data.f90.
References m_constants::one.
Referenced by sph_rtp_zonal_rms_data::zonal_mean_all_rtp_field().
cal_sph_zonal_rms_data_pin()
subroutine cal_sph_zonal_ave_rms_data::cal_sph_zonal_rms_data_pin (integer(kind = kint), dimension(3), intent(in) nidx_rtp, integer(kind = kint), intent(in) nnod, integer(kind = kint), intent(in) numdir, integer(kind = kint), intent(in) irtp_fld, real(kind = kreal), dimension(nnod,numdir), intent(inout) d_rtp)
Definition at line 190 of file cal_sph_zonal_ave_rms_data.f90.
References m_constants::one.
Referenced by sph_rtp_zonal_rms_data::zonal_cyl_rms_all_rtp_field(), and sph_rtp_zonal_rms_data::zonal_rms_all_rtp_field().
cal_sph_zonal_rms_data_rin()
subroutine cal_sph_zonal_ave_rms_data::cal_sph_zonal_rms_data_rin (integer(kind = kint), dimension(3), intent(in) nidx_rtp, integer(kind = kint), intent(in) nnod, integer(kind = kint), intent(in) numdir, integer(kind = kint), intent(in) irtp_fld, real(kind = kreal), dimension(nnod,numdir), intent(inout) d_rtp)
Definition at line 135 of file cal_sph_zonal_ave_rms_data.f90.
References m_constants::one.
Referenced by sph_rtp_zonal_rms_data::zonal_cyl_rms_all_rtp_field(), and sph_rtp_zonal_rms_data::zonal_rms_all_rtp_field().