CALYPSO: viewer_mesh_mpi_io_select Module Reference
viewer_mesh_mpi_io_select Module Reference
Viewer mesh file IO selector.
Functions/Subroutines
subroutine sel_mpi_output_surface_grid (mesh_file, mgd_v_mesh, mgd_view_prm)
Detailed Description
Viewer mesh file IO selector.
      subroutine sel_mpi_output_surface_grid                          &
     &         (ifmt_file, mgd_v_mesh, mgd_view_prm)
        type(field_IO_params), intent(in) :: mesh_file
        type(merged_viewer_mesh), intent(in) :: mgd_v_mesh
        type(mpi_viewer_mesh_param), intent(in) :: mgd_view_prm
Function/Subroutine Documentation
sel_mpi_output_surface_grid()
subroutine viewer_mesh_mpi_io_select::sel_mpi_output_surface_grid (type(field_io_params), intent(in) mesh_file, type(merged_viewer_mesh), intent(in) mgd_v_mesh, type(mpi_viewer_mesh_param), intent(in) mgd_view_prm)
Definition at line 40 of file viewer_mesh_MPI_IO_select.F90.
References set_mesh_extensions::add_ksm_extension(), gz_mpi_viewer_mesh_file_io::gz_mpi_write_viewer_mesh_file(), m_file_format_switch::id_gzip_txt_file_fmt, and mpi_viewer_mesh_file_io::mpi_write_viewer_mesh_file().
Referenced by para_const_kemoview_mesh::collect_surf_mesh_4_viewer().