CALYPSO: t_comm_table Module Reference
t_comm_table Module Reference
Structure for communication table.
Data Types
type communication_table
data structure for communication table
Functions/Subroutines
subroutine alloc_comm_table_num (comm_tbl)
subroutine alloc_comm_table_item (comm_tbl)
subroutine dealloc_comm_table (comm_tbl)
subroutine dealloc_import_table (comm_tbl)
subroutine dealloc_comm_tbl_num (comm_tbl)
subroutine, private dealloc_comm_tbl_item (comm_tbl)
subroutine empty_comm_table (comm_tbl)
subroutine copy_comm_tbl_type (comm_org, comm_new)
subroutine copy_neib_pe_type (comm_org, comm_new)
subroutine copy_import_table_type (comm_org, comm_new)
subroutine copy_export_table_type (comm_org, comm_new)
subroutine alloc_neighbouring_id (comm_tbl)
subroutine alloc_import_num (comm_tbl)
subroutine alloc_export_num (comm_tbl)
subroutine alloc_import_item (comm_tbl)
subroutine alloc_export_item (comm_tbl)
subroutine dealloc_neib_id (comm_tbl)
subroutine, private dealloc_import_num (comm_tbl)
subroutine, private dealloc_export_num (comm_tbl)
subroutine, private dealloc_import_item (comm_tbl)
subroutine, private dealloc_export_item (comm_tbl)
subroutine link_comm_tbl_types (comm_org, comm_tbl)
subroutine unlink_dest_comm_tbl_type (comm_tbl)
subroutine compare_comm_table_stacks (id_rank, org_comm, new_comm)
Detailed Description
Structure for communication table.
      subroutine alloc_comm_table_num(comm_tbl)
      subroutine alloc_comm_table_item(comm_tbl)
      subroutine dealloc_comm_table(comm_tbl)
      subroutine dealloc_import_table(comm_tbl)
      subroutine dealloc_comm_tbl_num(comm_tbl)
      subroutine empty_comm_table(comm_tbl)
      subroutine copy_comm_tbl_type(comm_org, comm_new)
      subroutine copy_neib_pe_type(comm_org, comm_new)
      subroutine copy_import_table_type(comm_org, comm_new)
      subroutine copy_export_table_type(comm_org, comm_new)
        type(communication_table), intent(in) :: comm_org
        type(communication_table), intent(inout) :: comm_new
      subroutine alloc_neighbouring_id(comm_tbl)
      subroutine alloc_import_num(comm_tbl)
      subroutine alloc_export_num(comm_tbl)
      subroutine alloc_import_item(comm_tbl)
      subroutine alloc_export_item(comm_tbl)
      subroutine dealloc_neib_id(comm_tbl)
      subroutine link_comm_tbl_types(comm_org, comm_tbl)
        type(communication_table), intent(in) :: comm_org
        type(communication_table), intent(inout) :: comm_tbl
      subroutine unlink_dest_comm_tbl_type(comm_tbl)
        type(interpolate_table), intent(inout) :: comm_tbl
      subroutine compare_comm_table_stacks                            &
     &         (id_rank, org_comm, new_comm)
      type(communication_table), intent(in) :: org_comm
      type(communication_table), intent(in) :: new_comm
Function/Subroutine Documentation
alloc_comm_table_item()
subroutine t_comm_table::alloc_comm_table_item (type(communication_table), intent(inout) comm_tbl)
Definition at line 99 of file t_comm_table.f90.
References alloc_export_item(), and alloc_import_item().
Referenced by copy_mesh_structures::copy_comm_tbl_types(), empty_comm_table(), and load_mesh_data::set_zero_mesh_data().
alloc_comm_table_num()
subroutine t_comm_table::alloc_comm_table_num (type(communication_table), intent(inout) comm_tbl)
Definition at line 86 of file t_comm_table.f90.
References alloc_export_num(), alloc_import_num(), and alloc_neighbouring_id().
Referenced by set_fem_mesh_4_sph::const_nod_comm_table_for_sph(), copy_mesh_structures::copy_comm_tbl_types(), empty_comm_table(), and load_mesh_data::set_zero_mesh_data().
alloc_export_item()
subroutine t_comm_table::alloc_export_item (type(communication_table), intent(inout) comm_tbl)
Definition at line 315 of file t_comm_table.f90.
Referenced by alloc_comm_table_item(), const_element_comm_table::const_comm_table_by_connenct(), set_fem_mesh_4_sph::const_nod_comm_table_for_sph(), copy_export_table_type(), gz_mpi_domain_data_io::gz_mpi_read_export_data(), gz_mpi_domain_data_io_b::gz_mpi_read_export_data_b(), gz_domain_data_io::gz_read_export_data(), gz_domain_data_io_b::gz_read_export_data_b(), mpi_domain_data_io::mpi_read_export_data(), mpi_domain_data_io_b::mpi_read_export_data_b(), domain_data_io::read_export_data(), and domain_data_io_b::read_export_data_b().
alloc_export_num()
subroutine t_comm_table::alloc_export_num (type(communication_table), intent(inout) comm_tbl)
Definition at line 289 of file t_comm_table.f90.
Referenced by alloc_comm_table_num(), const_element_comm_table::const_comm_table_by_connenct(), copy_export_table_type(), gz_mpi_domain_data_io::gz_mpi_read_export_data(), gz_mpi_domain_data_io_b::gz_mpi_read_export_data_b(), gz_domain_data_io::gz_read_export_data(), gz_domain_data_io_b::gz_read_export_data_b(), mpi_domain_data_io::mpi_read_export_data(), mpi_domain_data_io_b::mpi_read_export_data_b(), domain_data_io::read_export_data(), and domain_data_io_b::read_export_data_b().
alloc_import_item()
subroutine t_comm_table::alloc_import_item (type(communication_table), intent(inout) comm_tbl)
Definition at line 303 of file t_comm_table.f90.
Referenced by alloc_comm_table_item(), const_element_comm_table::const_comm_table_by_connenct(), set_fem_mesh_4_sph::const_nod_comm_table_for_sph(), copy_sph_comm_table_4_io::copy_comm_sph_to_comm_tbl(), copy_import_table_type(), gz_mpi_domain_data_io::gz_mpi_read_import_data(), gz_mpi_domain_data_io_b::gz_mpi_read_import_data_b(), gz_domain_data_io::gz_read_import_data(), gz_domain_data_io_b::gz_read_import_data_b(), mpi_domain_data_io::mpi_read_import_data(), mpi_domain_data_io_b::mpi_read_import_data_b(), domain_data_io::read_import_data(), and domain_data_io_b::read_import_data_b().
alloc_import_num()
subroutine t_comm_table::alloc_import_num (type(communication_table), intent(inout) comm_tbl)
Definition at line 275 of file t_comm_table.f90.
Referenced by alloc_comm_table_num(), const_element_comm_table::const_comm_table_by_connenct(), copy_sph_comm_table_4_io::copy_comm_sph_to_comm_tbl(), copy_import_table_type(), gz_mpi_domain_data_io::gz_mpi_read_import_data(), gz_mpi_domain_data_io_b::gz_mpi_read_import_data_b(), gz_domain_data_io::gz_read_import_data(), gz_domain_data_io_b::gz_read_import_data_b(), mpi_domain_data_io::mpi_read_import_data(), mpi_domain_data_io_b::mpi_read_import_data_b(), domain_data_io::read_import_data(), and domain_data_io_b::read_import_data_b().
alloc_neighbouring_id()
subroutine t_comm_table::alloc_neighbouring_id (type(communication_table), intent(inout) comm_tbl)
Definition at line 263 of file t_comm_table.f90.
Referenced by alloc_comm_table_num(), const_element_comm_table::const_comm_table_by_connenct(), copy_sph_comm_table_4_io::copy_comm_sph_to_comm_tbl(), copy_neib_pe_type(), gz_mpi_domain_data_io::gz_mpi_read_domain_info(), gz_mpi_domain_data_io_b::gz_mpi_read_domain_info_b(), gz_domain_data_io::gz_read_domain_info(), gz_domain_data_io_b::gz_read_domain_info_b(), mpi_domain_data_io::mpi_read_domain_info(), mpi_domain_data_io_b::mpi_read_domain_info_b(), domain_data_io::read_domain_info(), and domain_data_io_b::read_domain_info_b().
compare_comm_table_stacks()
subroutine t_comm_table::compare_comm_table_stacks (integer, intent(in) id_rank, type(communication_table), intent(in) org_comm, type(communication_table), intent(in) new_comm)
Definition at line 430 of file t_comm_table.f90.
copy_comm_tbl_type()
subroutine t_comm_table::copy_comm_tbl_type (type(communication_table), intent(in) comm_org, type(communication_table), intent(inout) comm_new)
Definition at line 179 of file t_comm_table.f90.
References copy_export_table_type(), copy_import_table_type(), and copy_neib_pe_type().
Referenced by mpi_load_mesh_data::mpi_output_mesh(), load_mesh_data::output_mesh(), and load_mesh_data::set_mesh_geometry_data().
copy_export_table_type()
subroutine t_comm_table::copy_export_table_type (type(communication_table), intent(in) comm_org, type(communication_table), intent(inout) comm_new)
Definition at line 237 of file t_comm_table.f90.
References alloc_export_item(), alloc_export_num(), copy_communication_table::copy_export_item(), copy_communication_table::copy_num_export(), and cal_minmax_and_stacks::s_cal_numbers_from_stack().
Referenced by copy_comm_tbl_type().
copy_import_table_type()
subroutine t_comm_table::copy_import_table_type (type(communication_table), intent(in) comm_org, type(communication_table), intent(inout) comm_new)
Definition at line 212 of file t_comm_table.f90.
References alloc_import_item(), alloc_import_num(), copy_communication_table::copy_import_item(), copy_communication_table::copy_num_import(), and cal_minmax_and_stacks::s_cal_numbers_from_stack().
Referenced by copy_comm_tbl_type().
copy_neib_pe_type()
subroutine t_comm_table::copy_neib_pe_type (type(communication_table), intent(in) comm_org, type(communication_table), intent(inout) comm_new)
Definition at line 193 of file t_comm_table.f90.
References alloc_neighbouring_id(), and copy_communication_table::copy_neighboring_pe().
Referenced by copy_comm_tbl_type().
dealloc_comm_table()
subroutine t_comm_table::dealloc_comm_table (type(communication_table), intent(inout) comm_tbl)
Definition at line 111 of file t_comm_table.f90.
References dealloc_comm_tbl_item(), and dealloc_comm_tbl_num().
Referenced by t_read_mesh_data::dealloc_edge_mesh_io(), t_psf_geometry_list::dealloc_iedge_global_psf(), t_mesh_data::dealloc_mesh_geometry_base(), t_mesh_data::dealloc_mesh_type(), and t_read_mesh_data::dealloc_surface_mesh_io().
dealloc_comm_tbl_item()
subroutine, private t_comm_table::dealloc_comm_tbl_item (type(communication_table), intent(inout) comm_tbl) private
Definition at line 149 of file t_comm_table.f90.
References dealloc_export_item(), and dealloc_import_item().
Referenced by dealloc_comm_table().
dealloc_comm_tbl_num()
subroutine t_comm_table::dealloc_comm_tbl_num (type(communication_table), intent(inout) comm_tbl)
Definition at line 136 of file t_comm_table.f90.
References dealloc_export_num(), dealloc_import_num(), and dealloc_neib_id().
Referenced by dealloc_comm_table().
dealloc_export_item()
subroutine, private t_comm_table::dealloc_export_item (type(communication_table), intent(inout) comm_tbl) private
Definition at line 373 of file t_comm_table.f90.
Referenced by dealloc_comm_tbl_item().
dealloc_export_num()
subroutine, private t_comm_table::dealloc_export_num (type(communication_table), intent(inout) comm_tbl) private
Definition at line 350 of file t_comm_table.f90.
Referenced by dealloc_comm_tbl_num().
dealloc_import_item()
subroutine, private t_comm_table::dealloc_import_item (type(communication_table), intent(inout) comm_tbl) private
Definition at line 361 of file t_comm_table.f90.
Referenced by dealloc_comm_tbl_item(), and dealloc_import_table().
dealloc_import_num()
subroutine, private t_comm_table::dealloc_import_num (type(communication_table), intent(inout) comm_tbl) private
Definition at line 339 of file t_comm_table.f90.
Referenced by dealloc_comm_tbl_num(), and dealloc_import_table().
dealloc_import_table()
subroutine t_comm_table::dealloc_import_table (type(communication_table), intent(inout) comm_tbl)
Definition at line 123 of file t_comm_table.f90.
References dealloc_import_item(), dealloc_import_num(), and dealloc_neib_id().
Referenced by t_spheric_data_io::dealloc_rj_mode_io(), t_spheric_data_io::dealloc_rlm_mode_io(), t_spheric_data_io::dealloc_rtm_grid_io(), and t_spheric_data_io::dealloc_rtp_grid_io().
dealloc_neib_id()
subroutine t_comm_table::dealloc_neib_id (type(communication_table), intent(inout) comm_tbl)
Definition at line 328 of file t_comm_table.f90.
Referenced by dealloc_comm_tbl_num(), dealloc_import_table(), and t_mesh_data::dealloc_node_geometry_io().
empty_comm_table()
subroutine t_comm_table::empty_comm_table (type(communication_table), intent(inout) comm_tbl)
Definition at line 162 of file t_comm_table.f90.
References alloc_comm_table_item(), and alloc_comm_table_num().
link_comm_tbl_types()
subroutine t_comm_table::link_comm_tbl_types (type(communication_table), intent(in) comm_org, type(communication_table), intent(inout) comm_tbl)
Definition at line 386 of file t_comm_table.f90.
unlink_dest_comm_tbl_type()
subroutine t_comm_table::unlink_dest_comm_tbl_type (type(communication_table), intent(inout) comm_tbl)
Definition at line 408 of file t_comm_table.f90.