CALYPSO: read_sections_control_data Module Reference
read_sections_control_data Module Reference
read control data for cross sections and isosurfaces
Functions/Subroutines
subroutine s_read_sections_control_data (id_control, psf_ctls, iso_ctls, c_buf)
Variables
character(len=kchara), parameter, private hd_viz_ctl = 'visual_control'
integer(kind=kint), private i_viz_ctl = 0
character(len=kchara), parameter, private hd_section_ctl = 'cross_section_ctl'
character(len=kchara), parameter, private hd_isosurf_ctl = 'isosurface_ctl'
character(len=kchara), parameter, private hd_psf_ctl = 'surface_rendering'
character(len=kchara), parameter, private hd_iso_ctl = 'isosurf_rendering'
Detailed Description
read control data for cross sections and isosurfaces
      subroutine s_read_sections_control_data                         &
     &         (id_control, psf_ctls, iso_ctls, c_buf)
        type(section_controls), intent(inout) :: psf_ctls
        type(isosurf_controls), intent(inout) :: iso_ctls
        type(buffer_for_control), intent(inout)  :: c_buf
  begin visual_control
    array cross_section_ctl  1
      file   cross_section_ctl   'ctl_psf_eq'
    end array cross_section_ctl
    array isosurface_ctl     2
      file   isosurface_ctl   'ctl_iso_p_n1e4'
      file   isosurface_ctl   'ctl_iso_p_p1e4'
    end array isosurface_ctl
  end visual_control
Function/Subroutine Documentation
s_read_sections_control_data()
subroutine read_sections_control_data::s_read_sections_control_data (integer(kind = kint), intent(in) id_control, type(section_controls), intent(inout) psf_ctls, type(isosurf_controls), intent(inout) iso_ctls, type(buffer_for_control), intent(inout) c_buf)
Definition at line 67 of file read_sections_control_data.f90.
References t_read_control_elements::check_array_flag(), t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_iso_ctl, hd_isosurf_ctl, hd_psf_ctl, hd_section_ctl, hd_viz_ctl, i_viz_ctl, t_read_control_elements::load_one_line_from_control(), t_control_data_isosurfaces::read_files_4_iso_ctl(), and t_control_data_sections::read_files_4_psf_ctl().
Referenced by t_ctl_data_mhd::read_sph_mhd_ctl_w_psf().
Variable Documentation
hd_iso_ctl
character(len=kchara), parameter, private read_sections_control_data::hd_iso_ctl = 'isosurf_rendering' private
Definition at line 54 of file read_sections_control_data.f90.
Referenced by s_read_sections_control_data().
hd_isosurf_ctl
character(len=kchara), parameter, private read_sections_control_data::hd_isosurf_ctl = 'isosurface_ctl' private
Definition at line 48 of file read_sections_control_data.f90.
Referenced by s_read_sections_control_data().
hd_psf_ctl
character(len=kchara), parameter, private read_sections_control_data::hd_psf_ctl = 'surface_rendering' private
Definition at line 52 of file read_sections_control_data.f90.
Referenced by s_read_sections_control_data().
hd_section_ctl
character(len=kchara), parameter, private read_sections_control_data::hd_section_ctl = 'cross_section_ctl' private
Definition at line 46 of file read_sections_control_data.f90.
Referenced by s_read_sections_control_data().
hd_viz_ctl
character(len=kchara), parameter, private read_sections_control_data::hd_viz_ctl = 'visual_control' private
Definition at line 42 of file read_sections_control_data.f90.
Referenced by s_read_sections_control_data().
i_viz_ctl
integer (kind=kint), private read_sections_control_data::i_viz_ctl = 0 private
Definition at line 43 of file read_sections_control_data.f90.
Referenced by s_read_sections_control_data().