CALYPSO: udt_to_vtk_data_io Module Reference
udt_to_vtk_data_io Module Reference
ucd data into VTK format IO
Functions/Subroutines
subroutine write_ucd_field_to_vtk (id_vtk, ucd)
subroutine write_ucd_mesh_to_vtk (id_vtk, ucd)
subroutine read_udt_field_from_vtk (id_vtk, ucd)
subroutine read_alloc_udt_field_from_vtk (id_vtk, ucd)
subroutine read_ucd_mesh_from_vtk (id_vtk, ucd)
subroutine read_alloc_ucd_mesh_from_vtk (id_vtk, ucd)
Detailed Description
ucd data into VTK format IO
      subroutine write_ucd_field_to_VTK(id_vtk, ucd)
      subroutine write_ucd_mesh_to_VTK(id_vtk, ucd)
        type(ucd_data), intent(in) :: ucd
      subroutine read_udt_field_from_VTK(id_vtk, ucd)
      subroutine read_alloc_udt_field_from_VTK(id_vtk, ucd)
      subroutine read_ucd_mesh_from_VTK(id_vtk, ucd)
      subroutine read_alloc_ucd_mesh_from_VTK(id_vtk, ucd)
        type(ucd_data), intent(inout) :: ucd
Function/Subroutine Documentation
read_alloc_ucd_mesh_from_vtk()
subroutine udt_to_vtk_data_io::read_alloc_ucd_mesh_from_vtk (integer(kind = kint), intent(in) id_vtk, type(ucd_data), intent(inout) ucd)
Definition at line 212 of file udt_to_VTK_data_IO.f90.
References t_ucd_data::allocate_ucd_ele(), t_ucd_data::allocate_ucd_node(), m_constants::ithree, vtk_data_io::read_vtk_cell_type(), vtk_data_io::read_vtk_connect_data(), vtk_data_io::read_vtk_connect_head(), vtk_data_io::read_vtk_each_field(), and vtk_data_io::read_vtk_node_head().
Referenced by vtk_file_io::read_alloc_vtk_file(), and vtk_file_io::read_alloc_vtk_grid().
read_alloc_udt_field_from_vtk()
subroutine udt_to_vtk_data_io::read_alloc_udt_field_from_vtk (integer(kind = kint), intent(in) id_vtk, type(ucd_data), intent(inout) ucd)
Definition at line 121 of file udt_to_VTK_data_IO.f90.
References t_ucd_data::allocate_ucd_phys_data(), t_ucd_data::allocate_ucd_phys_name(), t_ucd_data::append_new_ucd_field_data(), t_ucd_data::append_new_ucd_field_name(), t_ucd_data::deallocate_ucd_data(), m_constants::izero, vtk_data_io::read_vtk_each_field(), vtk_data_io::read_vtk_each_field_head(), and vtk_data_io::read_vtk_fields_head().
Referenced by vtk_file_io::read_alloc_vtk_file(), and vtk_file_io::read_alloc_vtk_phys().
read_ucd_mesh_from_vtk()
subroutine udt_to_vtk_data_io::read_ucd_mesh_from_vtk (integer(kind = kint), intent(in) id_vtk, type(ucd_data), intent(inout) ucd)
Definition at line 171 of file udt_to_VTK_data_IO.f90.
References m_constants::ithree, vtk_data_io::read_vtk_cell_type(), vtk_data_io::read_vtk_connect_data(), vtk_data_io::read_vtk_connect_head(), vtk_data_io::read_vtk_each_field(), and vtk_data_io::read_vtk_node_head().
Referenced by vtk_file_io::read_vtk_file(), and vtk_file_io::read_vtk_grid().
read_udt_field_from_vtk()
subroutine udt_to_vtk_data_io::read_udt_field_from_vtk (integer(kind = kint), intent(in) id_vtk, type(ucd_data), intent(inout) ucd)
Definition at line 72 of file udt_to_VTK_data_IO.f90.
References skip_comment_f::cmp_no_case(), copy_between_two_fields::copy_fields_2_fields(), m_constants::ione, m_constants::izero, vtk_data_io::read_vtk_each_field(), vtk_data_io::read_vtk_each_field_head(), and vtk_data_io::read_vtk_fields_head().
Referenced by vtk_file_io::read_vtk_file(), and vtk_file_io::read_vtk_phys().
write_ucd_field_to_vtk()
subroutine udt_to_vtk_data_io::write_ucd_field_to_vtk (integer(kind = kint), intent(in) id_vtk, type(ucd_data), intent(in) ucd)
Definition at line 40 of file udt_to_VTK_data_IO.f90.
References vtk_data_io::write_vtk_data(), and vtk_data_io::write_vtk_fields_head().
Referenced by vtk_file_io::write_vtk_file(), and vtk_file_io::write_vtk_phys().
write_ucd_mesh_to_vtk()
subroutine udt_to_vtk_data_io::write_ucd_mesh_to_vtk (integer(kind = kint), intent(in) id_vtk, type(ucd_data), intent(in) ucd)
Definition at line 54 of file udt_to_VTK_data_IO.f90.
References m_constants::ithree, vtk_data_io::write_vtk_connect_data(), vtk_data_io::write_vtk_each_field(), and vtk_data_io::write_vtk_node_head().
Referenced by vtk_file_io::write_vtk_file(), and vtk_file_io::write_vtk_grid().