CALYPSO: element_mesh_mpi_io_select Module Reference
element_mesh_mpi_io_select Module Reference
Choose mesh file to read.
Functions/Subroutines
subroutine sel_mpi_read_ele_mesh (mesh_file, ele_mesh_IO)
subroutine sel_mpi_read_surf_mesh (mesh_file, surf_mesh_IO)
subroutine sel_mpi_read_edge_mesh (mesh_file, edge_mesh_IO)
subroutine sel_mpi_write_ele_mesh_file (mesh_file, ele_mesh_IO)
subroutine sel_mpi_write_surf_mesh_file (mesh_file, surf_mesh_IO)
subroutine sel_mpi_write_edge_mesh_file (mesh_file, edge_mesh_IO)
Variables
character(len=kchara), private file_name
Detailed Description
Choose mesh file to read.
      subroutine sel_mpi_read_ele_mesh(mesh_file, ele_mesh_IO)
      subroutine sel_mpi_read_surf_mesh(mesh_file, surf_mesh_IO)
      subroutine sel_mpi_read_edge_mesh(mesh_file, edge_mesh_IO)
        type(field_IO_params), intent(in) ::  mesh_file
        type(surf_edge_IO_file), intent(inout) :: ele_mesh_IO
        type(surf_edge_IO_file), intent(inout) :: surf_mesh_IO
        type(surf_edge_IO_file), intent(inout) :: edge_mesh_IO
      subroutine sel_mpi_write_ele_mesh_file(mesh_file, ele_mesh_IO)
      subroutine sel_mpi_write_surf_mesh_file(mesh_file, surf_mesh_IO)
      subroutine sel_mpi_write_edge_mesh_file(mesh_file, edge_mesh_IO)
        type(field_IO_params), intent(in) ::  mesh_file
        type(surf_edge_IO_file), intent(inout) :: ele_mesh_IO
        type(surf_edge_IO_file), intent(inout) :: surf_mesh_IO
        type(surf_edge_IO_file), intent(inout) :: edge_mesh_IO
Function/Subroutine Documentation
sel_mpi_read_edge_mesh()
subroutine element_mesh_mpi_io_select::sel_mpi_read_edge_mesh (type(field_io_params), intent(in) mesh_file, type(surf_edge_io_file), intent(inout) edge_mesh_IO)
Definition at line 145 of file element_mesh_MPI_IO_select.F90.
References calypso_mpi::calypso_mpi_abort(), file_name, gz_mpi_element_file_io::gz_mpi_input_edge_file(), gz_mpi_element_file_io_b::gz_mpi_input_edge_file_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, m_file_format_switch::iflag_single, mpi_element_file_io::mpi_input_edge_file(), mpi_element_file_io_b::mpi_input_edge_file_b(), calypso_mpi::my_rank, calypso_mpi::nprocs, element_mesh_io_select::sel_read_edge_mesh(), and set_mesh_file_names::set_edge_mesh_file_name().
sel_mpi_read_ele_mesh()
subroutine element_mesh_mpi_io_select::sel_mpi_read_ele_mesh (type(field_io_params), intent(in) mesh_file, type(surf_edge_io_file), intent(inout) ele_mesh_IO)
Definition at line 59 of file element_mesh_MPI_IO_select.F90.
References calypso_mpi::calypso_mpi_abort(), file_name, gz_mpi_element_file_io::gz_mpi_input_element_file(), gz_mpi_element_file_io_b::gz_mpi_input_element_file_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, m_file_format_switch::iflag_single, mpi_element_file_io::mpi_input_element_file(), mpi_element_file_io_b::mpi_input_element_file_b(), calypso_mpi::my_rank, calypso_mpi::nprocs, element_mesh_io_select::sel_read_ele_mesh(), and set_mesh_file_names::set_ele_comm_file_name().
sel_mpi_read_surf_mesh()
subroutine element_mesh_mpi_io_select::sel_mpi_read_surf_mesh (type(field_io_params), intent(in) mesh_file, type(surf_edge_io_file), intent(inout) surf_mesh_IO)
Definition at line 101 of file element_mesh_MPI_IO_select.F90.
References calypso_mpi::calypso_mpi_abort(), file_name, gz_mpi_element_file_io::gz_mpi_input_surface_file(), gz_mpi_element_file_io_b::gz_mpi_input_surface_file_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, m_file_format_switch::iflag_single, mpi_element_file_io::mpi_input_surface_file(), mpi_element_file_io_b::mpi_input_surface_file_b(), calypso_mpi::my_rank, calypso_mpi::nprocs, element_mesh_io_select::sel_read_surf_mesh(), and set_mesh_file_names::set_surf_mesh_file_name().
sel_mpi_write_edge_mesh_file()
subroutine element_mesh_mpi_io_select::sel_mpi_write_edge_mesh_file (type(field_io_params), intent(in) mesh_file, type(surf_edge_io_file), intent(inout) edge_mesh_IO)
Definition at line 262 of file element_mesh_MPI_IO_select.F90.
References file_name, gz_mpi_element_file_io::gz_mpi_output_edge_file(), gz_mpi_element_file_io_b::gz_mpi_output_edge_file_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, m_file_format_switch::iflag_single, mpi_element_file_io::mpi_output_edge_file(), mpi_element_file_io_b::mpi_output_edge_file_b(), calypso_mpi::my_rank, element_mesh_io_select::sel_write_edge_mesh_file(), and set_mesh_file_names::set_edge_mesh_file_name().
sel_mpi_write_ele_mesh_file()
subroutine element_mesh_mpi_io_select::sel_mpi_write_ele_mesh_file (type(field_io_params), intent(in) mesh_file, type(surf_edge_io_file), intent(inout) ele_mesh_IO)
Definition at line 190 of file element_mesh_MPI_IO_select.F90.
References file_name, gz_mpi_element_file_io::gz_mpi_output_element_file(), gz_mpi_element_file_io_b::gz_mpi_output_element_file_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, m_file_format_switch::iflag_single, mpi_element_file_io::mpi_output_element_file(), mpi_element_file_io_b::mpi_output_element_file_b(), calypso_mpi::my_rank, element_mesh_io_select::sel_write_ele_mesh_file(), and set_mesh_file_names::set_ele_comm_file_name().
sel_mpi_write_surf_mesh_file()
subroutine element_mesh_mpi_io_select::sel_mpi_write_surf_mesh_file (type(field_io_params), intent(in) mesh_file, type(surf_edge_io_file), intent(inout) surf_mesh_IO)
Definition at line 225 of file element_mesh_MPI_IO_select.F90.
References file_name, gz_mpi_element_file_io::gz_mpi_output_surface_file(), gz_mpi_element_file_io_b::gz_mpi_output_surface_file_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, m_file_format_switch::iflag_single, mpi_element_file_io::mpi_output_surface_file(), mpi_element_file_io_b::mpi_output_surface_file_b(), calypso_mpi::my_rank, element_mesh_io_select::sel_write_surf_mesh_file(), and set_mesh_file_names::set_surf_mesh_file_name().
Variable Documentation
file_name
character(len=kchara), private element_mesh_mpi_io_select::file_name private
Definition at line 51 of file element_mesh_MPI_IO_select.F90.
Referenced by open_ad_rawfile(), open_rd_rawfile(), open_wt_rawfile(), sel_mpi_read_edge_mesh(), sel_mpi_read_ele_mesh(), sel_mpi_read_surf_mesh(), sel_mpi_write_edge_mesh_file(), sel_mpi_write_ele_mesh_file(), and sel_mpi_write_surf_mesh_file().