CALYPSO: gz_mpi_edge_data_io Module Reference
gz_mpi_edge_data_io Module Reference
data IO orutines for edge
Functions/Subroutines
subroutine gz_mpi_read_edge_connect (IO_param, comm_IO, ele_IO, sfed_IO)
subroutine gz_mpi_write_edge_connect (IO_param, comm_IO, ele_IO, sfed_IO)
subroutine gz_mpi_read_edge_geometry (IO_param, nod_IO, sfed_IO)
subroutine gz_mpi_write_edge_geometry (IO_param, nod_IO, sfed_IO)
Detailed Description
data IO orutines for edge
      subroutine gz_mpi_read_edge_connect                             &
     &         (IO_param, comm_IO, ele_IO, sfed_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(communication_table), intent(inout) :: comm_IO
        type(element_data), intent(inout) :: ele_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
      subroutine gz_mpi_write_edge_connect                            &
     &         (IO_param, comm_IO, ele_IO, sfed_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(communication_table), intent(in) :: comm_IO
        type(element_data), intent(in) :: ele_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
      subroutine gz_mpi_read_edge_geometry(IO_param, nod_IO, sfed_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(node_data), intent(in) :: nod_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
      subroutine gz_mpi_write_edge_geometry(IO_param, nod_IO, sfed_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(node_data), intent(inout) :: nod_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
Function/Subroutine Documentation
gz_mpi_read_edge_connect()
subroutine gz_mpi_edge_data_io::gz_mpi_read_edge_connect (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(inout) comm_IO, type(element_data), intent(inout) ele_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 57 of file gz_MPI_edge_data_IO.f90.
References gz_mpi_domain_data_io::gz_mpi_read_domain_info(), gz_mpi_element_connect_io::gz_mpi_read_edge_4_element(), gz_mpi_element_connect_io::gz_mpi_read_element_info(), gz_mpi_domain_data_io::gz_mpi_read_export_data(), gz_mpi_domain_data_io::gz_mpi_read_import_data(), gz_mpi_element_connect_io::gz_mpi_read_num_element(), gz_mpi_element_connect_io::gz_mpi_read_surface_4_element(), gz_mpi_ascii_data_io::gz_mpi_skip_header(), m_fem_surface_labels::hd_edge_connect(), m_fem_surface_labels::hd_edge_export(), m_fem_surface_labels::hd_edge_import(), m_fem_surface_labels::hd_edge_on_ele(), m_fem_surface_labels::hd_edge_on_surf(), m_fem_surface_labels::hd_edge_para(), and m_fem_mesh_labels::hd_fem_para().
Referenced by gz_mpi_element_file_io::gz_mpi_input_edge_file().
gz_mpi_read_edge_geometry()
subroutine gz_mpi_edge_data_io::gz_mpi_read_edge_geometry (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 137 of file gz_MPI_edge_data_IO.f90.
References gz_mpi_node_geometry_io::gz_mpi_read_geometry_info(), gz_mpi_node_geometry_io::gz_mpi_read_number_of_node(), gz_mpi_node_geometry_io::gz_mpi_read_scl_in_ele(), gz_mpi_node_geometry_io::gz_mpi_read_vect_in_ele(), gz_mpi_ascii_data_io::gz_mpi_skip_header(), m_fem_surface_labels::hd_edge_dir(), m_fem_surface_labels::hd_edge_length(), and m_fem_surface_labels::hd_edge_point().
gz_mpi_write_edge_connect()
subroutine gz_mpi_edge_data_io::gz_mpi_write_edge_connect (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(in) comm_IO, type(element_data), intent(in) ele_IO, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 94 of file gz_MPI_edge_data_IO.f90.
References gz_mpi_ascii_data_io::gz_mpi_write_charahead(), gz_mpi_domain_data_io::gz_mpi_write_domain_info(), gz_mpi_element_connect_io::gz_mpi_write_edge_4_element(), gz_mpi_element_connect_io::gz_mpi_write_element_info(), gz_mpi_domain_data_io::gz_mpi_write_export_data(), gz_mpi_domain_data_io::gz_mpi_write_import_data(), gz_mpi_element_connect_io::gz_mpi_write_surface_4_element(), m_fem_surface_labels::hd_edge_connect(), m_fem_surface_labels::hd_edge_export(), m_fem_surface_labels::hd_edge_import(), m_fem_surface_labels::hd_edge_on_ele(), m_fem_surface_labels::hd_edge_on_surf(), m_fem_surface_labels::hd_edge_para(), and m_fem_mesh_labels::hd_fem_para().
Referenced by gz_mpi_element_file_io::gz_mpi_output_edge_file().
gz_mpi_write_edge_geometry()
subroutine gz_mpi_edge_data_io::gz_mpi_write_edge_geometry (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 159 of file gz_MPI_edge_data_IO.f90.
References gz_mpi_ascii_data_io::gz_mpi_write_charahead(), gz_mpi_node_geometry_io::gz_mpi_write_geometry_info(), gz_mpi_node_geometry_io::gz_mpi_write_scl_in_ele(), gz_mpi_node_geometry_io::gz_mpi_write_vect_in_ele(), m_fem_surface_labels::hd_edge_dir(), m_fem_surface_labels::hd_edge_length(), and m_fem_surface_labels::hd_edge_point().