CALYPSO: cal_sph_mean_square Module Reference
cal_sph_mean_square Module Reference
Data arrays to monitoring spectrum data.
Functions/Subroutines
subroutine one_mode_scalar_mean_square (j, nri, jmax, inod_rj_center, radius_1d_rj_r, g_rj_11, n_point, d_rj, sq_r)
subroutine each_scalar_sph_spec (nri, jmax, idx_rj_degree_zero, inod_rj_center, radius_1d_rj_r, g_sph_rj, n_point, d_rj, sq_rj)
subroutine one_mode_vector_mean_square (j, nri, jmax, a_r_1d_rj_r, g_rj_3, g_rj_12, n_point, d_rj, sq_r)
subroutine degree_zero_vector_mean_square (nri, jmax, idx_rj_degree_zero, inod_rj_center, a_r_1d_rj_r, n_point, d_rj, sq_r)
subroutine each_vector_sph_spec (nri, jmax, idx_rj_degree_zero, inod_rj_center, a_r_1d_rj_r, g_sph_rj, n_point, d_rj, sq_rj)
subroutine one_mode_mean_sq_to_energy (nri, ene_r)
subroutine one_field_mean_sq_to_energy (nri, jmax, ene_rj)
Detailed Description
Data arrays to monitoring spectrum data.
      subroutine one_mode_scalar_mean_square(j, nri, jmax,            &
     &          inod_rj_center, radius_1d_rj_r,                       &
     &          g_rj_11, n_point, d_rj, sq_r)
      subroutine each_scalar_sph_spec(nri, jmax,                      &
     &          idx_rj_degree_zero, inod_rj_center, radius_1d_rj_r,   &
     &          g_sph_rj, n_point, d_rj, sq_rj)
        real(kind = kreal), intent(inout) :: sq_rj(0:nri,jmax)
      subroutine one_mode_vector_mean_square(j, nri, jmax,            &
     &          a_r_1d_rj_r, g_rj_3, g_rj_12, n_point, d_rj, sq_r)
      subroutine degree_zero_vector_mean_square(nri, jmax,            &
     &          idx_rj_degree_zero, inod_rj_center, a_r_1d_rj_r,      &
     &          n_point, d_rj, sq_r)
      subroutine each_vector_sph_spec(nri, jmax,                      &
     &          idx_rj_degree_zero, inod_rj_center, a_r_1d_rj_r,      &
     &          g_sph_rj, n_point, d_rj, sq_rj)
        real(kind = kreal), intent(inout) :: sq_rj(0:nri,jmax,3)
      subroutine one_mode_mean_sq_to_energy(nri, ene_r)
      subroutine one_field_mean_sq_to_energy(nri, jmax, ene_rj)
Function/Subroutine Documentation
degree_zero_vector_mean_square()
subroutine cal_sph_mean_square::degree_zero_vector_mean_square (integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, integer(kind = kint), intent(in) idx_rj_degree_zero, integer(kind = kint), intent(in) inod_rj_center, real(kind = kreal), dimension(nri), intent(in) a_r_1d_rj_r, integer(kind = kint), intent(in) n_point, real(kind = kreal), dimension(n_point,3), intent(in) d_rj, real(kind = kreal), dimension(0:nri,3), intent(inout) sq_r)
Definition at line 145 of file cal_sph_mean_square.f90.
References m_constants::half, and m_constants::zero.
Referenced by cal_rms_by_sph_spectr::cal_rms_sph_spec_one_mode().
each_scalar_sph_spec()
subroutine cal_sph_mean_square::each_scalar_sph_spec (integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, integer(kind = kint), intent(in) idx_rj_degree_zero, integer(kind = kint), intent(in) inod_rj_center, real(kind = kreal), dimension(nri), intent(in) radius_1d_rj_r, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) n_point, real(kind = kreal), dimension(n_point), intent(in) d_rj, real(kind = kreal), dimension(0:nri,jmax), intent(inout) sq_rj)
Definition at line 78 of file cal_sph_mean_square.f90.
Referenced by cal_rms_by_sph_spectr::cal_rms_sph_spec_one_field().
each_vector_sph_spec()
subroutine cal_sph_mean_square::each_vector_sph_spec (integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, integer(kind = kint), intent(in) idx_rj_degree_zero, integer(kind = kint), intent(in) inod_rj_center, real(kind = kreal), dimension(nri), intent(in) a_r_1d_rj_r, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) n_point, real(kind = kreal), dimension(n_point,3), intent(in) d_rj, real(kind = kreal), dimension(0:nri,jmax,3), intent(inout) sq_rj)
Definition at line 184 of file cal_sph_mean_square.f90.
References m_constants::half, m_constants::izero, and m_constants::zero.
Referenced by cal_rms_by_sph_spectr::cal_rms_sph_spec_one_field().
one_field_mean_sq_to_energy()
subroutine cal_sph_mean_square::one_field_mean_sq_to_energy (integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(0:nri,jmax,3), intent(inout) ene_rj)
Definition at line 254 of file cal_sph_mean_square.f90.
References m_constants::half.
Referenced by cal_rms_by_sph_spectr::cvt_mag_or_kin_ene_spectr().
one_mode_mean_sq_to_energy()
subroutine cal_sph_mean_square::one_mode_mean_sq_to_energy (integer(kind = kint), intent(in) nri, real(kind = kreal), dimension(0:nri,3), intent(inout) ene_r)
Definition at line 238 of file cal_sph_mean_square.f90.
References m_constants::half.
Referenced by cal_rms_by_sph_spectr::cvt_mag_or_kin_ene_one_mode().
one_mode_scalar_mean_square()
subroutine cal_sph_mean_square::one_mode_scalar_mean_square (integer(kind = kint), intent(in) j, integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, integer(kind = kint), intent(in) inod_rj_center, real(kind = kreal), dimension(nri), intent(in) radius_1d_rj_r, real(kind = kreal), intent(in) g_rj_11, integer(kind = kint), intent(in) n_point, real(kind = kreal), dimension(n_point), intent(in) d_rj, real(kind = kreal), dimension(0:nri), intent(inout) sq_r)
Definition at line 45 of file cal_sph_mean_square.f90.
Referenced by cal_rms_by_sph_spectr::cal_rms_sph_spec_one_mode().
one_mode_vector_mean_square()
subroutine cal_sph_mean_square::one_mode_vector_mean_square (integer(kind = kint), intent(in) j, integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(nri), intent(in) a_r_1d_rj_r, real(kind = kreal), intent(in) g_rj_3, real(kind = kreal), intent(in) g_rj_12, integer(kind = kint), intent(in) n_point, real(kind = kreal), dimension(n_point,3), intent(in) d_rj, real(kind = kreal), dimension(0:nri,3), intent(inout) sq_r)
Definition at line 114 of file cal_sph_mean_square.f90.
Referenced by cal_rms_by_sph_spectr::cal_rms_sph_spec_one_mode().