CALYPSO: check_energy_fluxes Module Reference
check_energy_fluxes Module Reference
Functions/Subroutines
subroutine add_field_ctl_4_ene_flux (field_ctl)
Function/Subroutine Documentation
add_field_ctl_4_ene_flux()
subroutine check_energy_fluxes::add_field_ctl_4_ene_flux (type(ctl_array_c3), intent(inout) field_ctl)
Definition at line 28 of file check_energy_fluxes.f90.
References add_nodal_fields_ctl::add_phys_name_ctl(), m_base_force_labels::buoyancy, m_energy_flux_labels::buoyancy_flux, add_nodal_fields_ctl::check_field_list_ctl(), m_energy_flux_labels::comp_generation, m_base_force_labels::composite_buoyancy, m_energy_flux_labels::composite_buoyancy_flux, m_base_field_labels::composition, m_base_force_labels::composition_advect, m_base_field_labels::current_density, m_base_force_labels::heat_advect, m_base_force_labels::inertia, m_energy_flux_labels::inertia_work, m_base_force_labels::lorentz_force, m_energy_flux_labels::lorentz_work, m_energy_flux_labels::mag_tension_work, m_diffusion_term_labels::magnetic_diffusion, m_energy_flux_labels::magnetic_ene_diffusion, m_energy_flux_labels::magnetic_ene_generation, m_base_field_labels::magnetic_field, m_base_force_labels::magnetic_induction, m_base_force_labels::magnetic_stretch, m_energy_flux_labels::magnetic_stretch_flux, m_base_force_labels::magnetic_tension, m_base_force_labels::pert_comp_advect, m_energy_flux_labels::pert_comp_generation, m_base_force_labels::pert_heat_advect, m_energy_flux_labels::pert_temp_generation, m_base_field_labels::perturbation_composition, m_base_field_labels::perturbation_temp, m_energy_flux_labels::temp_generation, m_base_field_labels::temperature, m_base_field_labels::velocity, m_diffusion_term_labels::viscous_diffusion, m_energy_flux_labels::viscous_ene_diffusion, and m_energy_flux_labels::work_against_lorentz.
Referenced by add_nodal_fields_4_mhd::add_dependent_field().