CALYPSO: const_sph_radial_grad Module Reference
const_sph_radial_grad Module Reference
Evaluate radial delivatives.
Functions/Subroutines
subroutine const_radial_grad_scalar (sph_rj, r_2nd, sph_bc, bcs_S, fdm2_center, g_sph_rj, is_fld, is_grad, rj_fld)
subroutine const_grad_vp_and_vorticity (sph_rj, r_2nd, sph_bc_U, bcs_U, fdm2_free_ICB, fdm2_free_CMB, g_sph_rj, is_velo, is_vort, rj_fld)
subroutine const_grad_bp_and_current (sph_rj, r_2nd, sph_bc_B, bcs_B, g_sph_rj, is_magne, is_current, rj_fld)
subroutine const_grad_poloidal_moment (sph_rj, r_2nd, sph_bc_U, bcs_U, fdm2_free_ICB, fdm2_free_CMB, is_fld, rj_fld)
subroutine const_grad_poloidal_magne (sph_rj, r_2nd, sph_bc_B, bcs_B, g_sph_rj, is_magne, rj_fld)
subroutine const_pressure_gradient (sph_rj, r_2nd, sph_bc_U, g_sph_rj, coef_press, is_press, is_grad, rj_fld)
subroutine const_sph_gradient_no_bc (sph_rj, r_2nd, sph_bc, g_sph_rj, is_fld, is_grad, rj_fld)
Detailed Description
Evaluate radial delivatives.
      subroutine const_radial_grad_scalar                             &
     &         (sph_rj, r_2nd, sph_bc, bcs_S, fdm2_center, g_sph_rj,  &
     &          is_fld, is_grad, rj_fld)
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(fdm_matrices), intent(in) :: r_2nd
        type(sph_boundary_type), intent(in) :: sph_bc
        type(sph_scalar_boundary_data), intent(in) :: bcs_S
        type(fdm2_center_mat), intent(in) :: fdm2_center
        type(phys_data), intent(inout) :: rj_fld
        Address for input:    is_fld
        Address for solution: is_grad
      subroutine const_grad_vp_and_vorticity(sph_rj, r_2nd,           &
     &          sph_bc_U, bcs_U, fdm2_free_ICB, fdm2_free_CMB,        &
     &          g_sph_rj, is_velo, is_vort, rj_fld)
        Address for input:    is_velo, is_velo+2
        Address for solution: is_velo+1,
                              is_vort, is_vort+2, is_vort+1
      subroutine const_grad_bp_and_current                            &
     &         (sph_rj, r_2nd, sph_bc_B, bcs_B, g_sph_rj,             &
     &          is_magne, is_current, rj_fld)
        Address for input:    is_magne, is_magne+2
        Address for solution: is_magne+1,
                              is_current, is_current+2, is_current+1
      subroutine const_grad_poloidal_moment                           &
     &         (sph_rj, r_2nd, sph_bc_U, bcs_U,                       &
     &          fdm2_free_ICB, fdm2_free_CMB, is_fld, rj_fld)
        Address for input:    is_fld, is_fld+2
        Address for solution: is_fld+1
      subroutine const_grad_poloidal_magne(sph_rj, r_2nd,             &
     &          sph_bc_B, bcs_B, g_sph_rj, is_magne, rj_fld)
        Address for input:    is_magne, is_magne+2
        Address for solution: is_magne+1
      subroutine const_pressure_gradient(sph_rj, r_2nd, sph_bc_U,     &
     &          g_sph_rj, coef_press, is_press, is_grad, rj_fld)
        Address for input:    is_press
        Address for solution: is_grad
      subroutine const_sph_gradient_no_bc(sph_rj, r_2nd, sph_bc,      &
     &          g_sph_rj, is_fld, is_grad, rj_fld)
        Address for input:    is_fld
        Address for solution: is_grad, it_grad, ids_grad
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(fdm_matrices), intent(in) :: r_2nd
        type(sph_boundary_type), intent(in) :: sph_bc_U
        type(sph_vector_boundary_data), intent(inout) :: bcs_U
        type(sph_vector_boundary_data), intent(inout) :: bcs_B
        type(phys_data), intent(inout) :: rj_fld
Parameters
sph_bc Structure for basic boundary condition parameters
sph_bc_B Structure for basic boundary condition parameters for magnetic field
sph_bc_U Structure for basic boundary condition parameters for velocity
is_fld Spherical hermonics data address for input vector
is_grad Spherical hermonics data address for gradient
is_velo Spherical hermonics data address for poloidal velocity
is_vort Spherical hermonics data address for poloidal vorticity
is_magne Spherical hermonics data address for poloidal magnetic field
is_current Spherical hermonics data address for poloidal current density
is_press Spherical hermonics data address for pressure
rj_fld Spectr data structure
Function/Subroutine Documentation
const_grad_bp_and_current()
subroutine const_sph_radial_grad::const_grad_bp_and_current (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc_B, type(sph_vector_boundary_data), intent(in) bcs_B, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, integer(kind = kint), intent(in) is_magne, integer(kind = kint), intent(in) is_current, type(phys_data), intent(inout) rj_fld)
Definition at line 186 of file const_sph_radial_grad.f90.
References cal_sph_exp_rotation::cal_sph_diff_pol_and_rot2(), extend_potential_field::ext_inside_potential_with_j(), extend_potential_field::ext_outside_potential_with_j(), t_boundary_params_sph_mhd::iflag_sph_insulator, select_exp_magne_cmb::sel_cmb_grad_bp_and_current(), and select_exp_magne_icb::sel_icb_grad_bp_and_current().
Referenced by cal_sol_sph_mhd_crank::s_cal_sol_sph_mhd_crank(), and cal_sol_sph_mhd_crank::set_sph_field_to_start().
const_grad_poloidal_magne()
subroutine const_sph_radial_grad::const_grad_poloidal_magne (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc_B, type(sph_vector_boundary_data), intent(in) bcs_B, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, integer(kind = kint), intent(in) is_magne, type(phys_data), intent(inout) rj_fld)
Definition at line 269 of file const_sph_radial_grad.f90.
References cal_sph_exp_rotation::cal_sph_diff_poloidal2(), extend_potential_field::ext_inside_potential(), extend_potential_field::ext_outside_potential(), t_boundary_params_sph_mhd::iflag_sph_insulator, select_exp_magne_cmb::sel_cmb_grad_poloidal_magne(), and select_exp_magne_icb::sel_icb_grad_poloidal_magne().
const_grad_poloidal_moment()
subroutine const_sph_radial_grad::const_grad_poloidal_moment (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc_U, type(sph_vector_boundary_data), intent(in) bcs_U, type(fdm2_free_slip), intent(in) fdm2_free_ICB, type(fdm2_free_slip), intent(in) fdm2_free_CMB, integer(kind = kint), intent(in) is_fld, type(phys_data), intent(inout) rj_fld)
Definition at line 236 of file const_sph_radial_grad.f90.
References cal_sph_exp_rotation::cal_sph_diff_poloidal2(), select_exp_velocity_cmb::sel_cmb_grad_poloidal_moment(), and select_exp_velocity_icb::sel_icb_grad_poloidal_moment().
Referenced by cal_energy_flux_rj::s_cal_energy_flux_rj().
const_grad_vp_and_vorticity()
subroutine const_sph_radial_grad::const_grad_vp_and_vorticity (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc_U, type(sph_vector_boundary_data), intent(in) bcs_U, type(fdm2_free_slip), intent(in) fdm2_free_ICB, type(fdm2_free_slip), intent(in) fdm2_free_CMB, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, integer(kind = kint), intent(in) is_velo, integer(kind = kint), intent(in) is_vort, type(phys_data), intent(inout) rj_fld)
Definition at line 151 of file const_sph_radial_grad.f90.
References cal_sph_exp_rotation::cal_sph_diff_pol_and_rot2(), select_exp_velocity_cmb::sel_cmb_grad_vp_and_vorticity(), and select_exp_velocity_icb::sel_icb_grad_vp_and_vorticity().
Referenced by cal_sol_sph_mhd_crank::s_cal_sol_sph_mhd_crank(), and cal_sol_sph_mhd_crank::set_sph_field_to_start().
const_pressure_gradient()
subroutine const_sph_radial_grad::const_pressure_gradient (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc_U, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, real(kind = kreal), intent(in) coef_press, integer(kind = kint), intent(in) is_press, integer(kind = kint), intent(in) is_grad, type(phys_data), intent(inout) rj_fld)
Definition at line 316 of file const_sph_radial_grad.f90.
References cal_sph_exp_1st_diff::cal_sph_nod_gradient_2(), cal_sph_exp_nod_none_bc::delete_bc_rj_vector(), cal_sph_exp_1st_diff::normalize_sph_average_grad(), and t_const_wz_coriolis_rtp::ovwrt_rj_coef_prod_vect_smp().
Referenced by lead_fields_4_sph_mhd::pressure_4_sph_mhd().
const_radial_grad_scalar()
subroutine const_sph_radial_grad::const_radial_grad_scalar (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc, type(sph_scalar_boundary_data), intent(in) bcs_S, type(fdm2_center_mat), intent(in) fdm2_center, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_grad, type(phys_data), intent(inout) rj_fld)
Definition at line 109 of file const_sph_radial_grad.f90.
References cal_sph_exp_1st_diff::cal_sph_nod_gradient_2(), cal_sph_exp_1st_diff::normalize_sph_average_grad(), select_exp_scalar_cmb::sel_cmb_radial_grad_scalar(), and select_exp_scalar_icb::sel_icb_radial_grad_scalar().
Referenced by cal_grad_of_sph_vectors::cal_grad_of_scalars_sph(), cal_sol_sph_mhd_crank::update_after_composit_sph(), and cal_sol_sph_mhd_crank::update_after_heat_sph().
const_sph_gradient_no_bc()
subroutine const_sph_radial_grad::const_sph_gradient_no_bc (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_grad, type(phys_data), intent(inout) rj_fld)
Definition at line 354 of file const_sph_radial_grad.f90.
References cal_sph_exp_1st_diff::cal_sph_nod_gradient_2(), cal_sph_exp_nod_none_bc::cal_sph_nod_nobc_in_grad2(), cal_sph_exp_nod_none_bc::cal_sph_nod_nobc_out_grad2(), and cal_sph_exp_1st_diff::normalize_sph_average_grad().
Referenced by cal_grad_of_sph_vectors::overwrt_grad_of_vector_sph().