CALYPSO: cvt_xyz_tensor_2_sph_smp Module Reference
cvt_xyz_tensor_2_sph_smp Module Reference
Functions/Subroutines
subroutine cal_sph_tensor_smp (np_smp, numnod, inod_smp_stack, tensor, tsph, xx, yy, zz, r, s, a_r, a_s)
subroutine overwrite_sph_tensor_smp (np_smp, numnod, inod_smp_stack, tensor, xx, yy, zz, r, s, a_r, a_s)
subroutine cal_rr_tensor_smp (np_smp, numnod, inod_smp_stack, tensor, t_rr, xx, yy, zz, r, s, a_r)
subroutine cal_rt_tensor_smp (np_smp, numnod, inod_smp_stack, tensor, t_rt, xx, yy, zz, r, s, a_r, a_s)
subroutine cal_rp_tensor_smp (np_smp, numnod, inod_smp_stack, tensor, t_rp, xx, yy, zz, r, s, a_r, a_s)
subroutine cal_tt_tensor_smp (np_smp, numnod, inod_smp_stack, tensor, t_tt, xx, yy, zz, r, s, a_r, a_s)
subroutine cal_tp_tensor_smp (np_smp, numnod, inod_smp_stack, tensor, t_tp, xx, yy, zz, r, s, a_r, a_s)
subroutine cal_pp_tensor_smp (np_smp, numnod, inod_smp_stack, tensor, t_pp, xx, yy, s, a_s)
Function/Subroutine Documentation
cal_pp_tensor_smp()
subroutine cvt_xyz_tensor_2_sph_smp::cal_pp_tensor_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,6), intent(in) tensor, real(kind=kreal), dimension(numnod), intent(inout) t_pp, real(kind=kreal), dimension(numnod), intent(in) xx, real(kind=kreal), dimension(numnod), intent(in) yy, real(kind=kreal), dimension(numnod), intent(in) s, real(kind=kreal), dimension(numnod), intent(in) a_s)
Definition at line 583 of file cvt_xyz_tensor_2_sph_smp.f90.
References m_constants::two.
Referenced by convert_components_4_viz::convert_comps_4_viz().
cal_rp_tensor_smp()
subroutine cvt_xyz_tensor_2_sph_smp::cal_rp_tensor_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,6), intent(in) tensor, real(kind=kreal), dimension(numnod), intent(inout) t_rp, real(kind=kreal), dimension(numnod), intent(in) xx, real(kind=kreal), dimension(numnod), intent(in) yy, real(kind=kreal), dimension(numnod), intent(in) zz, real(kind=kreal), dimension(numnod), intent(in) r, real(kind=kreal), dimension(numnod), intent(in) s, real(kind=kreal), dimension(numnod), intent(in) a_r, real(kind=kreal), dimension(numnod), intent(in) a_s)
Definition at line 417 of file cvt_xyz_tensor_2_sph_smp.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz().
cal_rr_tensor_smp()
subroutine cvt_xyz_tensor_2_sph_smp::cal_rr_tensor_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,6), intent(in) tensor, real(kind=kreal), dimension(numnod), intent(inout) t_rr, real(kind=kreal), dimension(numnod), intent(in) xx, real(kind=kreal), dimension(numnod), intent(in) yy, real(kind=kreal), dimension(numnod), intent(in) zz, real(kind=kreal), dimension(numnod), intent(in) r, real(kind=kreal), dimension(numnod), intent(in) s, real(kind=kreal), dimension(numnod), intent(in) a_r)
Definition at line 304 of file cvt_xyz_tensor_2_sph_smp.f90.
References m_constants::two.
Referenced by convert_components_4_viz::convert_comps_4_viz().
cal_rt_tensor_smp()
subroutine cvt_xyz_tensor_2_sph_smp::cal_rt_tensor_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,6), intent(in) tensor, real(kind=kreal), dimension(numnod), intent(inout) t_rt, real(kind=kreal), dimension(numnod), intent(in) xx, real(kind=kreal), dimension(numnod), intent(in) yy, real(kind=kreal), dimension(numnod), intent(in) zz, real(kind=kreal), dimension(numnod), intent(in) r, real(kind=kreal), dimension(numnod), intent(in) s, real(kind=kreal), dimension(numnod), intent(in) a_r, real(kind=kreal), dimension(numnod), intent(in) a_s)
Definition at line 359 of file cvt_xyz_tensor_2_sph_smp.f90.
References m_constants::two.
Referenced by convert_components_4_viz::convert_comps_4_viz().
cal_sph_tensor_smp()
subroutine cvt_xyz_tensor_2_sph_smp::cal_sph_tensor_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,6), intent(in) tensor, real(kind=kreal), dimension(numnod,6), intent(inout) tsph, real(kind=kreal), dimension(numnod), intent(in) xx, real(kind=kreal), dimension(numnod), intent(in) yy, real(kind=kreal), dimension(numnod), intent(in) zz, real(kind=kreal), dimension(numnod), intent(in) r, real(kind=kreal), dimension(numnod), intent(in) s, real(kind=kreal), dimension(numnod), intent(in) a_r, real(kind=kreal), dimension(numnod), intent(in) a_s)
Definition at line 73 of file cvt_xyz_tensor_2_sph_smp.f90.
References m_constants::two.
Referenced by convert_components_4_viz::convert_comps_4_viz(), and cvt_nodal_and_sph_field::cvt_nod_tsr_to_sph_tsr().
cal_tp_tensor_smp()
subroutine cvt_xyz_tensor_2_sph_smp::cal_tp_tensor_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,6), intent(in) tensor, real(kind=kreal), dimension(numnod), intent(inout) t_tp, real(kind=kreal), dimension(numnod), intent(in) xx, real(kind=kreal), dimension(numnod), intent(in) yy, real(kind=kreal), dimension(numnod), intent(in) zz, real(kind=kreal), dimension(numnod), intent(in) r, real(kind=kreal), dimension(numnod), intent(in) s, real(kind=kreal), dimension(numnod), intent(in) a_r, real(kind=kreal), dimension(numnod), intent(in) a_s)
Definition at line 528 of file cvt_xyz_tensor_2_sph_smp.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz().
cal_tt_tensor_smp()
subroutine cvt_xyz_tensor_2_sph_smp::cal_tt_tensor_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,6), intent(in) tensor, real(kind=kreal), dimension(numnod), intent(inout) t_tt, real(kind=kreal), dimension(numnod), intent(in) xx, real(kind=kreal), dimension(numnod), intent(in) yy, real(kind=kreal), dimension(numnod), intent(in) zz, real(kind=kreal), dimension(numnod), intent(in) r, real(kind=kreal), dimension(numnod), intent(in) s, real(kind=kreal), dimension(numnod), intent(in) a_r, real(kind=kreal), dimension(numnod), intent(in) a_s)
Definition at line 472 of file cvt_xyz_tensor_2_sph_smp.f90.
References m_constants::two.
Referenced by convert_components_4_viz::convert_comps_4_viz().
overwrite_sph_tensor_smp()
subroutine cvt_xyz_tensor_2_sph_smp::overwrite_sph_tensor_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,6), intent(inout) tensor, real(kind=kreal), dimension(numnod), intent(in) xx, real(kind=kreal), dimension(numnod), intent(in) yy, real(kind=kreal), dimension(numnod), intent(in) zz, real(kind=kreal), dimension(numnod), intent(in) r, real(kind=kreal), dimension(numnod), intent(in) s, real(kind=kreal), dimension(numnod), intent(in) a_r, real(kind=kreal), dimension(numnod), intent(in) a_s)
Definition at line 189 of file cvt_xyz_tensor_2_sph_smp.f90.
References m_constants::two.
Referenced by copy_nodal_fld_4_sph_trans::copy_nod_tsr_to_sph_trans(), and coordinate_convert_4_sph::overwrite_nodal_xyz_2_sph_smp().