CALYPSO: sph_file_mpi_io_select Module Reference
sph_file_mpi_io_select Module Reference
Spectr data IO selector.
Functions/Subroutines
subroutine sel_mpi_read_geom_rtp_file (num_pe, id_rank, file_param, sph_file)
subroutine sel_mpi_read_spectr_rj_file (num_pe, id_rank, file_param, sph_file)
subroutine sel_mpi_read_geom_rtm_file (num_pe, id_rank, file_param, sph_file)
subroutine sel_mpi_read_modes_rlm_file (num_pe, id_rank, file_param, sph_file)
subroutine sel_mpi_write_geom_rtp_file (file_param, sph_file)
subroutine sel_mpi_write_spectr_rj_file (file_param, sph_file)
subroutine sel_mpi_write_geom_rtm_file (file_param, sph_file)
subroutine sel_mpi_write_modes_rlm_file (file_param, sph_file)
Variables
character(len=kchara), private sph_file_name
Detailed Description
Spectr data IO selector.
      subroutine sel_mpi_read_geom_rtp_file                           &
     &         (num_pe, id_rank, file_param, sph_file)
      subroutine sel_mpi_read_spectr_rj_file                          &
     &         (num_pe, id_rank, file_param, sph_file)
      subroutine sel_mpi_read_geom_rtm_file                           &
     &         (num_pe, id_rank, file_param, sph_file)
      subroutine sel_mpi_read_modes_rlm_file                          &
     &         (num_pe, id_rank, file_param, sph_file)
        type(field_IO_params), intent(in) :: file_param
        type(sph_file_data_type), intent(inout) :: sph_file
      subroutine sel_mpi_write_geom_rtp_file(file_param, sph_file)
      subroutine sel_mpi_write_spectr_rj_file(file_param, sph_file)
      subroutine sel_mpi_write_geom_rtm_file(file_param, sph_file)
      subroutine sel_mpi_write_modes_rlm_file(file_param, sph_file)
        type(field_IO_params), intent(in) :: file_param
        type(sph_file_data_type), intent(in) :: sph_file
Parameters
sph_file_name file name for IO (.gz is appended in this module)
Function/Subroutine Documentation
sel_mpi_read_geom_rtm_file()
subroutine sph_file_mpi_io_select::sel_mpi_read_geom_rtm_file (integer, intent(in) num_pe, integer, intent(in) id_rank, type(field_io_params), intent(in) file_param, type(sph_file_data_type), intent(inout) sph_file)
Definition at line 156 of file sph_file_MPI_IO_select.F90.
References calypso_mpi::calypso_mpi_abort(), gz_mpi_sph_modes_file_io::gz_mpi_read_geom_rtm_file(), gz_mpi_sph_modes_file_io_b::gz_mpi_read_geom_rtm_file_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, m_file_format_switch::iflag_single, mpi_sph_modes_file_io::mpi_read_geom_rtm_file(), mpi_sph_modes_file_io_b::mpi_read_geom_rtm_file_b(), sph_file_io_select::sel_read_geom_rtm_file(), set_mesh_file_names::set_sph_rtm_file_name(), and sph_file_name.
Referenced by parallel_load_data_4_sph::load_sph_mesh(), and compare_sph_with_io::s_compare_sph_with_io().
sel_mpi_read_geom_rtp_file()
subroutine sph_file_mpi_io_select::sel_mpi_read_geom_rtp_file (integer, intent(in) num_pe, integer, intent(in) id_rank, type(field_io_params), intent(in) file_param, type(sph_file_data_type), intent(inout) sph_file)
Definition at line 62 of file sph_file_MPI_IO_select.F90.
References calypso_mpi::calypso_mpi_abort(), gz_mpi_sph_modes_file_io::gz_mpi_read_geom_rtp_file(), gz_mpi_sph_modes_file_io_b::gz_mpi_read_geom_rtp_file_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, m_file_format_switch::iflag_single, mpi_sph_modes_file_io::mpi_read_geom_rtp_file(), mpi_sph_modes_file_io_b::mpi_read_geom_rtp_file_b(), sph_file_io_select::sel_read_geom_rtp_file(), set_mesh_file_names::set_sph_rtp_file_name(), and sph_file_name.
Referenced by parallel_load_data_4_sph::load_sph_mesh(), and compare_sph_with_io::s_compare_sph_with_io().
sel_mpi_read_modes_rlm_file()
subroutine sph_file_mpi_io_select::sel_mpi_read_modes_rlm_file (integer, intent(in) num_pe, integer, intent(in) id_rank, type(field_io_params), intent(in) file_param, type(sph_file_data_type), intent(inout) sph_file)
Definition at line 203 of file sph_file_MPI_IO_select.F90.
References calypso_mpi::calypso_mpi_abort(), gz_mpi_sph_modes_file_io::gz_mpi_read_modes_rlm_file(), gz_mpi_sph_modes_file_io_b::gz_mpi_read_modes_rlm_file_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, m_file_format_switch::iflag_single, mpi_sph_modes_file_io::mpi_read_modes_rlm_file(), mpi_sph_modes_file_io_b::mpi_read_modes_rlm_file_b(), sph_file_io_select::sel_read_modes_rlm_file(), set_mesh_file_names::set_sph_rlm_file_name(), and sph_file_name.
Referenced by parallel_load_data_4_sph::load_sph_mesh(), and compare_sph_with_io::s_compare_sph_with_io().
sel_mpi_read_spectr_rj_file()
subroutine sph_file_mpi_io_select::sel_mpi_read_spectr_rj_file (integer, intent(in) num_pe, integer, intent(in) id_rank, type(field_io_params), intent(in) file_param, type(sph_file_data_type), intent(inout) sph_file)
Definition at line 109 of file sph_file_MPI_IO_select.F90.
References calypso_mpi::calypso_mpi_abort(), gz_mpi_sph_modes_file_io::gz_mpi_read_spectr_rj_file(), gz_mpi_sph_modes_file_io_b::gz_mpi_read_spectr_rj_file_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, m_file_format_switch::iflag_single, mpi_sph_modes_file_io::mpi_read_spectr_rj_file(), mpi_sph_modes_file_io_b::mpi_read_spectr_rj_file_b(), sph_file_io_select::sel_read_spectr_rj_file(), set_mesh_file_names::set_sph_rj_file_name(), and sph_file_name.
Referenced by r_interpolate_sph_data::input_old_rj_sph_trans(), output_gen_sph_grid_modes::load_local_rj_mesh_4_merge(), parallel_load_data_4_sph::load_sph_mesh(), parallel_load_data_4_sph::load_sph_rj_mesh(), and compare_sph_with_io::s_compare_sph_with_io().
sel_mpi_write_geom_rtm_file()
subroutine sph_file_mpi_io_select::sel_mpi_write_geom_rtm_file (type(field_io_params), intent(in) file_param, type(sph_file_data_type), intent(in) sph_file)
Definition at line 321 of file sph_file_MPI_IO_select.F90.
References gz_mpi_sph_modes_file_io::gz_mpi_write_geom_rtm_file(), gz_mpi_sph_modes_file_io_b::gz_mpi_write_geom_rtm_file_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, m_file_format_switch::iflag_single, mpi_sph_modes_file_io::mpi_write_geom_rtm_file(), mpi_sph_modes_file_io_b::mpi_write_geom_rtm_file_b(), calypso_mpi::my_rank, sph_file_io_select::sel_write_geom_rtm_file(), set_mesh_file_names::set_sph_rtm_file_name(), and sph_file_name.
Referenced by parallel_load_data_4_sph::output_sph_mesh().
sel_mpi_write_geom_rtp_file()
subroutine sph_file_mpi_io_select::sel_mpi_write_geom_rtp_file (type(field_io_params), intent(in) file_param, type(sph_file_data_type), intent(in) sph_file)
Definition at line 251 of file sph_file_MPI_IO_select.F90.
References gz_mpi_sph_modes_file_io::gz_mpi_write_geom_rtp_file(), gz_mpi_sph_modes_file_io_b::gz_mpi_write_geom_rtp_file_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, m_file_format_switch::iflag_single, mpi_sph_modes_file_io::mpi_write_geom_rtp_file(), mpi_sph_modes_file_io_b::mpi_write_geom_rtp_file_b(), calypso_mpi::my_rank, sph_file_io_select::sel_write_geom_rtp_file(), set_mesh_file_names::set_sph_rtp_file_name(), and sph_file_name.
Referenced by parallel_load_data_4_sph::output_sph_mesh().
sel_mpi_write_modes_rlm_file()
subroutine sph_file_mpi_io_select::sel_mpi_write_modes_rlm_file (type(field_io_params), intent(in) file_param, type(sph_file_data_type), intent(in) sph_file)
Definition at line 356 of file sph_file_MPI_IO_select.F90.
References gz_mpi_sph_modes_file_io::gz_mpi_write_modes_rlm_file(), gz_mpi_sph_modes_file_io_b::gz_mpi_write_modes_rlm_file_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, m_file_format_switch::iflag_single, mpi_sph_modes_file_io::mpi_write_modes_rlm_file(), mpi_sph_modes_file_io_b::mpi_write_modes_rlm_file_b(), calypso_mpi::my_rank, sph_file_io_select::sel_write_modes_rlm_file(), set_mesh_file_names::set_sph_rlm_file_name(), and sph_file_name.
Referenced by parallel_load_data_4_sph::output_sph_mesh().
sel_mpi_write_spectr_rj_file()
subroutine sph_file_mpi_io_select::sel_mpi_write_spectr_rj_file (type(field_io_params), intent(in) file_param, type(sph_file_data_type), intent(in) sph_file)
Definition at line 286 of file sph_file_MPI_IO_select.F90.
References gz_mpi_sph_modes_file_io::gz_mpi_write_spectr_rj_file(), gz_mpi_sph_modes_file_io_b::gz_mpi_write_spectr_rj_file_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, m_file_format_switch::iflag_single, mpi_sph_modes_file_io::mpi_write_spectr_rj_file(), mpi_sph_modes_file_io_b::mpi_write_spectr_rj_file_b(), calypso_mpi::my_rank, sph_file_io_select::sel_write_spectr_modes_rj_file(), set_mesh_file_names::set_sph_rj_file_name(), and sph_file_name.
Referenced by parallel_load_data_4_sph::output_sph_mesh(), and parallel_load_data_4_sph::output_sph_rj_mesh().
Variable Documentation
sph_file_name
character(len=kchara), private sph_file_mpi_io_select::sph_file_name private
Definition at line 54 of file sph_file_MPI_IO_select.F90.
Referenced by sel_mpi_read_geom_rtm_file(), sel_mpi_read_geom_rtp_file(), sel_mpi_read_modes_rlm_file(), sel_mpi_read_spectr_rj_file(), sel_mpi_write_geom_rtm_file(), sel_mpi_write_geom_rtp_file(), sel_mpi_write_modes_rlm_file(), and sel_mpi_write_spectr_rj_file().