CALYPSO: node_geometry_io Module Reference
node_geometry_io Module Reference
routines for ASCII data IO for mesh geometry
Functions/Subroutines
character(len=len_each_node_buffer) function, private write_each_node_buffer (inod, nod_IO)
subroutine read_each_node_buffer (textbuf, inod, nod_IO)
subroutine write_geometry_info (id_file, nod_IO)
subroutine write_scalar_in_element (id_file, nod_IO, sfed_IO)
subroutine write_vector_in_element (id_file, nod_IO, sfed_IO)
subroutine read_number_of_node (id_file, nod_IO)
subroutine read_geometry_info (id_file, nod_IO)
subroutine read_scalar_in_element (id_file, nod_IO, sfed_IO)
subroutine read_vector_in_element (id_file, nod_IO, sfed_IO)
Variables
integer(kind=kint), parameter len_each_node_buffer = 16 + 3*25 + 1
character(len=255), private character_4_read
Detailed Description
routines for ASCII data IO for mesh geometry
      function write_each_node_buffer(inod, nod_IO)
      subroutine read_each_node_buffer(textbuf, inod, nod_IO)
      subroutine write_geometry_info(id_file, nod_IO)
      subroutine write_scalar_in_element(id_file, nod_IO, sfed_IO)
      subroutine write_vector_in_element(id_file, nod_IO, sfed_IO)
        type(node_data), intent(in) :: nod_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
      subroutine read_number_of_node(id_file, nod_IO)
      subroutine read_geometry_info(id_file, nod_IO)
      subroutine read_scalar_in_element(id_file, nod_IO, sfed_IO)
      subroutine read_vector_in_element(id_file, nod_IO, sfed_IO)
        type(node_data), intent(inout) :: nod_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
Function/Subroutine Documentation
read_each_node_buffer()
subroutine node_geometry_io::read_each_node_buffer (character(len=len_each_node_buffer), intent(in) textbuf, integer (kind = kint), intent(in) inod, type(node_data), intent(inout) nod_IO)
Definition at line 67 of file node_geometry_IO.f90.
read_geometry_info()
subroutine node_geometry_io::read_geometry_info (integer (kind = kint), intent(in) id_file, type(node_data), intent(inout) nod_IO)
Definition at line 151 of file node_geometry_IO.f90.
References t_geometry_data::alloc_node_geometry_base().
Referenced by edge_data_io::read_edge_geometry(), element_data_io::read_element_geometry(), mesh_data_io::read_filter_geometry(), mesh_data_io::read_num_node_ele(), and surface_data_io::read_surface_geometry().
read_number_of_node()
subroutine node_geometry_io::read_number_of_node (integer (kind = kint), intent(in) id_file, type(node_data), intent(inout) nod_IO)
Definition at line 135 of file node_geometry_IO.f90.
References character_4_read, and skip_comment_f::skip_comment().
Referenced by edge_data_io::read_edge_geometry(), element_data_io::read_element_geometry(), mesh_data_io::read_filter_geometry(), mesh_data_io::read_num_node(), read_scalar_in_element(), surface_data_io::read_surface_geometry(), and read_vector_in_element().
read_scalar_in_element()
subroutine node_geometry_io::read_scalar_in_element (integer (kind = kint), intent(in) id_file, type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 169 of file node_geometry_IO.f90.
References t_surf_edge_io::alloc_ele_scalar_io(), and read_number_of_node().
Referenced by edge_data_io::read_edge_geometry(), element_data_io::read_element_geometry(), and surface_data_io::read_surface_geometry().
read_vector_in_element()
subroutine node_geometry_io::read_vector_in_element (integer (kind = kint), intent(in) id_file, type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 190 of file node_geometry_IO.f90.
References t_surf_edge_io::alloc_ele_vector_io(), and read_number_of_node().
Referenced by edge_data_io::read_edge_geometry(), and surface_data_io::read_surface_geometry().
write_each_node_buffer()
character(len=len_each_node_buffer) function, private node_geometry_io::write_each_node_buffer (integer (kind = kint), intent(in) inod, type(node_data), intent(in) nod_IO) private
Definition at line 52 of file node_geometry_IO.f90.
write_geometry_info()
subroutine node_geometry_io::write_geometry_info (integer (kind = kint), intent(in) id_file, type(node_data), intent(in) nod_IO)
Definition at line 81 of file node_geometry_IO.f90.
Referenced by mesh_data_io::output_node_cyl_geometry(), mesh_data_io::output_node_sph_geometry(), edge_data_io::write_edge_geometry(), edge_data_io::write_edge_geometry_cyl(), edge_data_io::write_edge_geometry_sph(), element_data_io::write_element_geometry(), element_data_io::write_element_geometry_cyl(), element_data_io::write_element_geometry_sph(), mesh_data_io::write_filter_geometry(), mesh_data_io::write_geometry_data(), surface_data_io::write_surface_geometry(), surface_data_io::write_surface_geometry_cyl(), and surface_data_io::write_surface_geometry_sph().
write_scalar_in_element()
subroutine node_geometry_io::write_scalar_in_element (integer (kind = kint), intent(in) id_file, type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 100 of file node_geometry_IO.f90.
Referenced by edge_data_io::write_edge_geometry(), edge_data_io::write_edge_geometry_cyl(), edge_data_io::write_edge_geometry_sph(), element_data_io::write_element_geometry(), element_data_io::write_element_geometry_cyl(), element_data_io::write_element_geometry_sph(), surface_data_io::write_surface_geometry(), surface_data_io::write_surface_geometry_cyl(), and surface_data_io::write_surface_geometry_sph().
write_vector_in_element()
subroutine node_geometry_io::write_vector_in_element (integer (kind = kint), intent(in) id_file, type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 117 of file node_geometry_IO.f90.
Referenced by edge_data_io::write_edge_geometry(), edge_data_io::write_edge_geometry_cyl(), edge_data_io::write_edge_geometry_sph(), surface_data_io::write_surface_geometry(), surface_data_io::write_surface_geometry_cyl(), and surface_data_io::write_surface_geometry_sph().
Variable Documentation
character_4_read
character(len=255), private node_geometry_io::character_4_read private
Definition at line 41 of file node_geometry_IO.f90.
Referenced by read_number_of_node().
len_each_node_buffer
integer(kind = kint), parameter node_geometry_io::len_each_node_buffer = 16 + 3*25 + 1
Definition at line 38 of file node_geometry_IO.f90.