CALYPSO: sum_sph_rms_data Module Reference
sum_sph_rms_data Module Reference
Evaluate mean square by spherical hermonics coefficients.
Functions/Subroutines
subroutine set_sum_table_4_sph_spectr (l_truncation, nidx_rj, idx_gl_1d_rj_j, num_mode_sum_l, num_mode_sum_m, num_mode_sum_lm, istack_mode_sum_l, istack_mode_sum_m, istack_mode_sum_lm, item_mode_sum_l, item_mode_sum_m, item_mode_sum_lm)
subroutine sum_sph_layerd_rms (l_truncation, sph_rj, ipol, g_sph_rj, rj_fld, nri_rms, num_rms_rj, istack_rms_comp_rj, ifield_rms_rj, kr_for_rms, num_vol_spectr, v_pwr, WK_pwr)
subroutine sum_sph_layerd_correlate (l_truncation, sph_rj, g_sph_rj, rj_fld1, rj_fld2, nri_rms, num_rms_rj, istack_cor_comp_rj, ifield_cor_rj, kr_for_rms, num_vol_spectr, v_pwr, WK_pwr)
subroutine sum_sph_v_rms_by_degree (ltr, nidx_j, istack_sum, item_mode_4_sum, ncomp, rms_sph_vol_j, rms_sph_vlc)
subroutine sum_sph_rms_by_degree (ltr, nidx_rj, nri_rms, kr_for_rms, istack_sum, item_mode_4_sum, ncomp, rms_sph_rj, rms_sph_lc)
Detailed Description
Evaluate mean square by spherical hermonics coefficients.
      subroutine set_sum_table_4_sph_spectr                           &
     &      (l_truncation, nidx_rj, idx_gl_1d_rj_j,                   &
     &       num_mode_sum_l, num_mode_sum_m, num_mode_sum_lm,         &
     &       istack_mode_sum_l, istack_mode_sum_m, istack_mode_sum_lm,&
     &       item_mode_sum_l, item_mode_sum_m, item_mode_sum_lm)
      subroutine sum_sph_layerd_rms(l_truncation, sph_rj, ipol,       &
     &       g_sph_rj, rj_fld, nri_rms, num_rms_rj,                   &
     &       istack_rms_comp_rj, ifield_rms_rj, kr_for_rms,           &
     &       num_vol_spectr, v_pwr, WK_pwr)
      subroutine sum_sph_layerd_correlate(l_truncation, sph_rj,       &
     &          g_sph_rj, rj_fld1, rj_fld2, nri_rms, num_rms_rj,      &
     &          istack_cor_comp_rj, ifield_cor_rj, kr_for_rms,        &
     &          num_vol_spectr, v_pwr, WK_pwr)
        type(sph_rj_grid), intent(in) :: sph_rj
        type(phys_data), intent(in) :: rj_fld
        type(sph_vol_mean_squares), intent(in) :: v_pwr(num_vol_spectr)
        type(sph_mean_square_work), intent(inout) :: WK_pwr
      subroutine sum_sph_v_rms_by_degree(ltr, nidx_j, istack_sum,     &
     &          item_mode_4_sum, ncomp, rms_sph_vol_j, rms_sph_vlc)
      subroutine sum_sph_rms_by_degree(ltr, nidx_rj, nri_rms,         &
     &          kr_for_rms, istack_sum, item_mode_4_sum, ncomp,       &
     &          rms_sph_rj, rms_sph_lc)
Function/Subroutine Documentation
set_sum_table_4_sph_spectr()
subroutine sum_sph_rms_data::set_sum_table_4_sph_spectr (integer(kind = kint), intent(in) l_truncation, integer(kind = kint), dimension(2), intent(in) nidx_rj, integer(kind = kint), dimension(nidx_rj(2),3), intent(in) idx_gl_1d_rj_j, integer(kind = kint), dimension(0:l_truncation), intent(inout) num_mode_sum_l, integer(kind = kint), dimension(0:l_truncation), intent(inout) num_mode_sum_m, integer(kind = kint), dimension(0:l_truncation), intent(inout) num_mode_sum_lm, integer(kind = kint), dimension(-1:l_truncation), intent(inout) istack_mode_sum_l, integer(kind = kint), dimension(-1:l_truncation), intent(inout) istack_mode_sum_m, integer(kind = kint), dimension(-1:l_truncation), intent(inout) istack_mode_sum_lm, integer(kind = kint), dimension(nidx_rj(2)), intent(inout) item_mode_sum_l, integer(kind = kint), dimension(nidx_rj(2)), intent(inout) item_mode_sum_m, integer(kind = kint), dimension(nidx_rj(2)), intent(inout) item_mode_sum_lm)
Definition at line 48 of file sum_sph_rms_data.f90.
Referenced by cal_rms_fields_by_sph::init_rms_4_sph_spectr().
sum_sph_layerd_correlate()
subroutine sum_sph_rms_data::sum_sph_layerd_correlate (integer(kind = kint), intent(in) l_truncation, type(sph_rj_grid), intent(in) sph_rj, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, type(phys_data), intent(in) rj_fld1, type(phys_data), intent(in) rj_fld2, integer(kind = kint), intent(in) nri_rms, integer(kind = kint), intent(in) num_rms_rj, integer(kind = kint), dimension(0:num_rms_rj), intent(in) istack_cor_comp_rj, integer(kind = kint), dimension(num_rms_rj), intent(in) ifield_cor_rj, integer(kind = kint), dimension(nri_rms), intent(in) kr_for_rms, integer(kind = kint), intent(in) num_vol_spectr, type(sph_vol_mean_squares), dimension(num_vol_spectr), intent(in) v_pwr, type(sph_mean_square_work), intent(inout) WK_pwr)
Definition at line 232 of file sum_sph_rms_data.f90.
References correlation_by_sph_spectr::correlate_sph_spec_one_field(), radial_int_for_sph_spec::radial_integration(), sum_sph_rms_by_degree(), sum_sph_v_rms_by_degree(), and m_constants::zero.
Referenced by cal_rms_fields_by_sph::cal_correlate_in_shell().
sum_sph_layerd_rms()
subroutine sum_sph_rms_data::sum_sph_layerd_rms (integer(kind = kint), intent(in) l_truncation, type(sph_rj_grid), intent(in) sph_rj, type(phys_address), intent(in) ipol, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, type(phys_data), intent(in) rj_fld, integer(kind = kint), intent(in) nri_rms, integer(kind = kint), intent(in) num_rms_rj, integer(kind = kint), dimension(0:num_rms_rj), intent(in) istack_rms_comp_rj, integer(kind = kint), dimension(num_rms_rj), intent(in) ifield_rms_rj, integer(kind = kint), dimension(nri_rms), intent(in) kr_for_rms, integer(kind = kint), intent(in) num_vol_spectr, type(sph_vol_mean_squares), dimension(num_vol_spectr), intent(in) v_pwr, type(sph_mean_square_work), intent(inout) WK_pwr)
Definition at line 136 of file sum_sph_rms_data.f90.
References cal_rms_by_sph_spectr::cal_rms_sph_spec_one_field(), radial_int_for_sph_spec::radial_integration(), sum_sph_rms_by_degree(), sum_sph_v_rms_by_degree(), and m_constants::zero.
Referenced by cal_rms_fields_by_sph::cal_mean_squre_in_shell().
sum_sph_rms_by_degree()
subroutine sum_sph_rms_data::sum_sph_rms_by_degree (integer(kind = kint), intent(in) ltr, integer(kind = kint), dimension(2), intent(in) nidx_rj, integer(kind = kint), intent(in) nri_rms, integer(kind = kint), dimension(nri_rms), intent(in) kr_for_rms, integer(kind = kint), dimension(-1:ltr), intent(in) istack_sum, integer(kind = kint), dimension(nidx_rj(2)), intent(in) item_mode_4_sum, integer(kind = kint), intent(in) ncomp, real(kind = kreal), dimension(0:nidx_rj(1),nidx_rj(2),3), intent(in) rms_sph_rj, real(kind = kreal), dimension(nri_rms,0:ltr,ncomp), intent(inout) rms_sph_lc)
Definition at line 348 of file sum_sph_rms_data.f90.
Referenced by sum_sph_layerd_correlate(), and sum_sph_layerd_rms().
sum_sph_v_rms_by_degree()
subroutine sum_sph_rms_data::sum_sph_v_rms_by_degree (integer(kind = kint), intent(in) ltr, integer(kind = kint), intent(in) nidx_j, integer(kind = kint), dimension(-1:ltr), intent(in) istack_sum, integer(kind = kint), dimension(nidx_j), intent(in) item_mode_4_sum, integer(kind = kint), intent(in) ncomp, real(kind = kreal), dimension(nidx_j,3), intent(in) rms_sph_vol_j, real(kind = kreal), dimension(0:ltr,ncomp), intent(inout) rms_sph_vlc)
Definition at line 312 of file sum_sph_rms_data.f90.
Referenced by sum_sph_layerd_correlate(), and sum_sph_layerd_rms().