CALYPSO: legendre_transform_sym_tomp Module Reference
legendre_transform_sym_tomp Module Reference
Legendre transforms (longest loop version)
Functions/Subroutines
subroutine leg_backward_trans_smat_jt (iflag_matmul, ncomp, nvector, nscalar, sph_rlm, sph_rtm, comm_rlm, comm_rtm, leg, idx_trns, n_WR, n_WS, WR, WS, WK_l_tsp)
subroutine leg_forward_trans_smat_jt (iflag_matmul, ncomp, nvector, nscalar, sph_rtm, sph_rlm, comm_rtm, comm_rlm, leg, idx_trns, n_WR, n_WS, WR, WS, WK_l_tsp)
subroutine leg_backward_trans_smat_tj (iflag_matmul, ncomp, nvector, nscalar, sph_rlm, sph_rtm, comm_rlm, comm_rtm, leg, idx_trns, n_WR, n_WS, WR, WS, WK_l_tsp)
subroutine leg_forward_trans_smat_tj (iflag_matmul, ncomp, nvector, nscalar, sph_rtm, sph_rlm, comm_rtm, comm_rlm, leg, idx_trns, n_WR, n_WS, WR, WS, WK_l_tsp)
Detailed Description
Legendre transforms (longest loop version)
      subroutine leg_backward_trans_smat_jt                           &
     &         (iflag_matmul, ncomp, nvector, nscalar,                &
     &          sph_rlm, sph_rtm, comm_rlm, comm_rtm, leg, idx_trns,  &
     &          n_WR, n_WS, WR, WS, WK_l_tsp)
      subroutine leg_backward_trans_smat_tj                           &
     &         (iflag_matmul, ncomp, nvector, nscalar,                &
     &          sph_rlm, sph_rtm, comm_rlm, comm_rtm, leg, idx_trns,  &
        Input:  sp_rlm   (Order: poloidal,diff_poloidal,toroidal)
        Output: vr_rtm   (Order: radius,theta,phi)
        type(sph_rlm_grid), intent(in) :: sph_rlm
        type(sph_rtm_grid), intent(in) :: sph_rtm
        type(sph_comm_tbl), intent(in) :: comm_rlm, comm_rtm
        type(legendre_4_sph_trans), intent(in) :: leg
        type(index_4_sph_trans), intent(in) :: idx_trns
        type(leg_trns_theta_omp_work), intent(inout) :: WK_l_tsp
    Forward transforms
      subroutine leg_forward_trans_smat_jt                            &
     &         (iflag_matmul, ncomp, nvector, nscalar,                &
     &          sph_rtm, sph_rlm, comm_rtm, comm_rlm, leg, idx_trns,  &
     &          n_WR, n_WS, WR, WS, WK_l_tsp)
      subroutine leg_forward_trans_smat_tj                            &
     &         (iflag_matmul, ncomp, nvector, nscalar,                &
     &          sph_rtm, sph_rlm, comm_rtm, comm_rlm, leg, idx_trns,  &
     &          n_WR, n_WS, WR, WS, WK_l_tsp)
        Input:  vr_rtm   (Order: radius,theta,phi)
        Output: sp_rlm   (Order: poloidal,diff_poloidal,toroidal)
        type(sph_rtm_grid), intent(in) :: sph_rtm
        type(sph_rlm_grid), intent(in) :: sph_rlm
        type(sph_comm_tbl), intent(in) :: comm_rtm, comm_rlm
        type(legendre_4_sph_trans), intent(in) :: leg
        type(index_4_sph_trans), intent(in) :: idx_trns
        type(leg_trns_theta_omp_work), intent(inout) :: WK_l_tsp
Parameters
ncomp Total number of components for spherical transform
nvector Number of vector for spherical transform
nscalar Number of scalar (including tensor components) for spherical transform
Function/Subroutine Documentation
leg_backward_trans_smat_jt()
subroutine legendre_transform_sym_tomp::leg_backward_trans_smat_jt (integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_comm_tbl), intent(in) comm_rlm, type(sph_comm_tbl), intent(in) comm_rtm, type(legendre_4_sph_trans), intent(in) leg, type(index_4_sph_trans), intent(in) idx_trns, integer(kind = kint), intent(in) n_WR, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_wr), intent(inout) WR, real (kind=kreal), dimension(n_ws), intent(inout) WS, type(leg_trns_theta_omp_work), intent(inout) WK_l_tsp)
Definition at line 74 of file legendre_transform_sym_tomp.f90.
References leg_bwd_trans_sym_mat_jt::legendre_b_trans_sym_mat_jt().
Referenced by t_legendre_trans_select::sel_backward_legendre_trans().
leg_backward_trans_smat_tj()
subroutine legendre_transform_sym_tomp::leg_backward_trans_smat_tj (integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_comm_tbl), intent(in) comm_rlm, type(sph_comm_tbl), intent(in) comm_rtm, type(legendre_4_sph_trans), intent(in) leg, type(index_4_sph_trans), intent(in) idx_trns, integer(kind = kint), intent(in) n_WR, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_wr), intent(inout) WR, real (kind=kreal), dimension(n_ws), intent(inout) WS, type(leg_trns_theta_omp_work), intent(inout) WK_l_tsp)
Definition at line 139 of file legendre_transform_sym_tomp.f90.
References leg_bwd_trans_sym_mat_tj::legendre_b_trans_sym_mat_tj().
Referenced by t_legendre_trans_select::sel_backward_legendre_trans().
leg_forward_trans_smat_jt()
subroutine legendre_transform_sym_tomp::leg_forward_trans_smat_jt (integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_comm_tbl), intent(in) comm_rtm, type(sph_comm_tbl), intent(in) comm_rlm, type(legendre_4_sph_trans), intent(in) leg, type(index_4_sph_trans), intent(in) idx_trns, integer(kind = kint), intent(in) n_WR, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_wr), intent(inout) WR, real (kind=kreal), dimension(n_ws), intent(inout) WS, type(leg_trns_theta_omp_work), intent(inout) WK_l_tsp)
Definition at line 106 of file legendre_transform_sym_tomp.f90.
References leg_fwd_trans_sym_mat_jt::legendre_f_trans_sym_mat_jt().
Referenced by t_legendre_trans_select::sel_forward_legendre_trans().
leg_forward_trans_smat_tj()
subroutine legendre_transform_sym_tomp::leg_forward_trans_smat_tj (integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_comm_tbl), intent(in) comm_rtm, type(sph_comm_tbl), intent(in) comm_rlm, type(legendre_4_sph_trans), intent(in) leg, type(index_4_sph_trans), intent(in) idx_trns, integer(kind = kint), intent(in) n_WR, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_wr), intent(inout) WR, real (kind=kreal), dimension(n_ws), intent(inout) WS, type(leg_trns_theta_omp_work), intent(inout) WK_l_tsp)
Definition at line 171 of file legendre_transform_sym_tomp.f90.
References leg_fwd_trans_sym_mat_tj::legendre_f_trans_sym_mat_tj().
Referenced by t_legendre_trans_select::sel_forward_legendre_trans().