CALYPSO: set_restart_data Module Reference
set_restart_data Module Reference
Copy between field data and IO data.
Functions/Subroutines
subroutine count_field_num_to_rst_io (num_fld, phys_name, num_fld_IO)
subroutine copy_field_name_to_rst_io (nnod, num_fld, istack_comp, phys_name, num_fld_IO, ntot_comp_IO, ncomp_IO, istack_comp_IO, field_IO_name, nnod_IO)
subroutine copy_field_data_to_rst_io (nnod, num_fld, ntot_comp, istack_comp, phys_name, d_nod, num_fld_IO, ntot_comp_IO, istack_comp_IO, field_IO_name, nnod_IO, dat_IO)
subroutine simple_copy_fld_name_to_rst_io (num_fld, istack_comp, phys_name, num_fld_IO, ntot_comp_IO, ncomp_IO, istack_comp_IO, field_IO_name)
subroutine simple_copy_fld_dat_to_rst_io (nnod, ntot_comp, d_nod, ntot_comp_IO, nnod_IO, dat_IO)
subroutine copy_field_data_from_rst_io (nnod, num_fld, ntot_comp, istack_comp, phys_name, d_nod, num_fld_IO, ntot_comp_IO, istack_comp_IO, field_IO_name, nnod_IO, dat_IO)
logical function, private set_output_field_flag_4_rst (d_name)
subroutine set_num_comps_4_rst (rst_name, numdir)
subroutine set_field_id_4_read_rst (d_name, num_fld, istack_comp, phys_name, numdir, i_field)
logical function, private check_vector_4_fem_rst (field_name)
logical function, private check_scalar_4_fem_rst (field_name)
Detailed Description
Copy between field data and IO data.
      subroutine count_field_num_to_rst_IO(num_fld, phys_name,        &
     &          num_fld_IO)
      subroutine copy_field_name_to_rst_IO (nnod, num_fld,            &
     &          istack_comp, phys_name, num_fld_IO, ntot_comp_IO,     &
     &          ncomp_IO, istack_comp_IO, field_IO_name, nnod_IO)
      subroutine copy_field_data_to_rst_IO(nnod, num_fld, ntot_comp,  &
     &          istack_comp, phys_name, d_nod,                        &
     &          num_fld_IO, ntot_comp_IO, istack_comp_IO,             &
     &          field_IO_name, nnod_IO, dat_IO)
      subroutine simple_copy_fld_name_to_rst_IO                       &
     &         (num_fld, istack_comp, phys_name, num_fld_IO,          &
     &          ntot_comp_IO, ncomp_IO, istack_comp_IO, field_IO_name)
      subroutine simple_copy_fld_dat_to_rst_IO(nnod, ntot_comp, d_nod,&
     &          ntot_comp_IO, nnod_IO, dat_IO)
      subroutine copy_field_data_from_rst_IO(nnod, num_fld, ntot_comp,&
     &          istack_comp, phys_name, d_nod,                        &
     &          num_fld_IO, ntot_comp_IO, istack_comp_IO,             &
     &          field_IO_name, nnod_IO, dat_IO)
      subroutine set_num_comps_4_rst(rst_name, numdir)
      subroutine set_field_id_4_read_rst(d_name, num_fld, istack_comp,&
     &          phys_name, numdir, i_field)
Function/Subroutine Documentation
check_scalar_4_fem_rst()
logical function, private set_restart_data::check_scalar_4_fem_rst (character(len = kchara), intent(in) field_name) private
Definition at line 326 of file set_restart_data.f90.
References m_explicit_term_labels::check_composition, m_explicit_term_labels::check_potential, m_explicit_term_labels::check_pressure, m_base_field_labels::composition, m_base_field_labels::composition_source, m_base_field_labels::heat_source, m_base_field_labels::magnetic_potential, m_base_field_labels::pressure, m_explicit_term_labels::previous_composition, m_explicit_term_labels::previous_heat, and m_base_field_labels::temperature.
Referenced by set_num_comps_4_rst().
check_vector_4_fem_rst()
logical function, private set_restart_data::check_vector_4_fem_rst (character(len = kchara), intent(in) field_name) private
Definition at line 303 of file set_restart_data.f90.
References m_explicit_term_labels::check_induction, m_explicit_term_labels::check_momentum, m_base_field_labels::magnetic_field, m_explicit_term_labels::previous_induction, m_explicit_term_labels::previous_momentum, m_base_field_labels::vector_potential, and m_base_field_labels::velocity.
Referenced by set_num_comps_4_rst(), and set_output_field_flag_4_rst().
copy_field_data_from_rst_io()
subroutine set_restart_data::copy_field_data_from_rst_io (integer(kind=kint), intent(in) nnod, integer(kind=kint), intent(in) num_fld, integer(kind=kint), intent(in) ntot_comp, integer(kind=kint), dimension(0:num_fld), intent(in) istack_comp, character(len=kchara), dimension(num_fld), intent(in) phys_name, real(kind = kreal), dimension(nnod,ntot_comp), intent(inout) d_nod, integer(kind=kint), intent(in) num_fld_IO, integer(kind=kint), intent(in) ntot_comp_IO, integer(kind=kint), dimension(0:num_fld_io), intent(in) istack_comp_IO, character(len=kchara), dimension(num_fld_io), intent(in) field_IO_name, integer(kind=kint), intent(in) nnod_IO, real(kind = kreal), dimension(nnod_io,ntot_comp_io), intent(in) dat_IO)
Definition at line 201 of file set_restart_data.f90.
copy_field_data_to_rst_io()
subroutine set_restart_data::copy_field_data_to_rst_io (integer(kind=kint), intent(in) nnod, integer(kind=kint), intent(in) num_fld, integer(kind=kint), intent(in) ntot_comp, integer(kind=kint), dimension(0:num_fld), intent(in) istack_comp, character(len=kchara), dimension(num_fld), intent(in) phys_name, real(kind = kreal), dimension(nnod,ntot_comp), intent(in) d_nod, integer(kind=kint), intent(in) num_fld_IO, integer(kind=kint), intent(in) ntot_comp_IO, integer(kind=kint), dimension(0:num_fld_io), intent(in) istack_comp_IO, character(len=kchara), dimension(num_fld_io), intent(in) field_IO_name, integer(kind=kint), intent(in) nnod_IO, real(kind = kreal), dimension(nnod_io,ntot_comp_io), intent(inout) dat_IO)
Definition at line 108 of file set_restart_data.f90.
copy_field_name_to_rst_io()
subroutine set_restart_data::copy_field_name_to_rst_io (integer(kind=kint), intent(in) nnod, integer(kind=kint), intent(in) num_fld, integer(kind=kint), dimension(0:num_fld), intent(in) istack_comp, character(len=kchara), dimension(num_fld), intent(in) phys_name, integer(kind=kint), intent(in) num_fld_IO, integer(kind=kint), intent(inout) ntot_comp_IO, integer(kind=kint), dimension(num_fld_io), intent(inout) ncomp_IO, integer(kind=kint), dimension(0:num_fld_io), intent(inout) istack_comp_IO, character(len=kchara), dimension(num_fld_io), intent(inout) field_IO_name, integer(kind=kint), intent(inout) nnod_IO)
Definition at line 72 of file set_restart_data.f90.
References set_output_field_flag_4_rst().
count_field_num_to_rst_io()
subroutine set_restart_data::count_field_num_to_rst_io (integer(kind=kint), intent(in) num_fld, character (len=kchara), dimension(num_fld), intent(in) phys_name, integer(kind=kint), intent(inout) num_fld_IO)
Definition at line 52 of file set_restart_data.f90.
References set_output_field_flag_4_rst().
set_field_id_4_read_rst()
subroutine set_restart_data::set_field_id_4_read_rst (character (len=kchara), intent(in) d_name, integer(kind=kint), intent(in) num_fld, integer(kind=kint), dimension(0:num_fld), intent(in) istack_comp, character (len=kchara), dimension(num_fld), intent(in) phys_name, integer(kind = kint), intent(inout) numdir, integer(kind = kint), intent(inout) i_field)
Definition at line 275 of file set_restart_data.f90.
set_num_comps_4_rst()
subroutine set_restart_data::set_num_comps_4_rst (character(len=kchara), intent(in) rst_name, integer(kind = kint), intent(inout) numdir)
Definition at line 259 of file set_restart_data.f90.
References check_scalar_4_fem_rst(), and check_vector_4_fem_rst().
Referenced by gz_rst_data_io_by_fld::read_gz_rst_field_comps(), and rst_data_io_by_fld::read_rst_field_comps().
set_output_field_flag_4_rst()
logical function, private set_restart_data::set_output_field_flag_4_rst (character (len=kchara), intent(in) d_name) private
Definition at line 247 of file set_restart_data.f90.
References check_vector_4_fem_rst().
Referenced by copy_field_name_to_rst_io(), and count_field_num_to_rst_io().
simple_copy_fld_dat_to_rst_io()
subroutine set_restart_data::simple_copy_fld_dat_to_rst_io (integer(kind=kint), intent(in) nnod, integer(kind=kint), intent(in) ntot_comp, real(kind = kreal), dimension(nnod,ntot_comp), intent(in) d_nod, integer(kind=kint), intent(in) ntot_comp_IO, integer(kind=kint), intent(in) nnod_IO, real(kind = kreal), dimension(nnod_io,ntot_comp_io), intent(inout) dat_IO)
Definition at line 182 of file set_restart_data.f90.
simple_copy_fld_name_to_rst_io()
subroutine set_restart_data::simple_copy_fld_name_to_rst_io (integer(kind=kint), intent(in) num_fld, integer(kind=kint), dimension(0:num_fld), intent(in) istack_comp, character(len=kchara), dimension(num_fld), intent(in) phys_name, integer(kind=kint), intent(in) num_fld_IO, integer(kind=kint), intent(inout) ntot_comp_IO, integer(kind=kint), dimension(num_fld_io), intent(inout) ncomp_IO, integer(kind=kint), dimension(0:num_fld_io), intent(inout) istack_comp_IO, character(len=kchara), dimension(num_fld_io), intent(inout) field_IO_name)
Definition at line 153 of file set_restart_data.f90.