CALYPSO: module_dependency Module Reference
module_dependency Module Reference
Constract module dependency for Makefile Usage: kemo_module_dep MAKEFILE SOURCE_DIRECTORY SOURCE_FILES for single file: kemo_module_dep MAKEFILE SOURCE_FILES Output command list for source with .f90 extension -c $< Output command list for source with .F90 extension -c $<.
Functions/Subroutines
subroutine alloc_mod_list
subroutine dealloc_mod_list
subroutine, private extend_mod_list
subroutine getarg_k (i, argc)
integer function iargc_kemo ()
subroutine, private const_module_list (filename)
subroutine, private write_module_list (objfile, filename, dirname, iflag_cpp)
subroutine make_module_dependency (dirname, filename)
subroutine make_module_dependency_f (dirname, filename)
Variables
integer ntot
integer num
integer, parameter id_makefile = 21
character(len=64), dimension(:), allocatable mod_name
character(len=28), parameter, private command = ' $(F90) -c $(F90OPTFLAGS) $<'
character(len=43), parameter, private command_cpp = ' $(F90) -c $(F90OPTFLAGS) $(F90CPPFLAGS) $<'
integer, parameter, private num_exclude = 3
character(len=31), dimension(num_exclude) exclude_list = (/'ISO_C_BINDING', 'hdf5 ', 'mpi '/)
Detailed Description
Constract module dependency for Makefile Usage: kemo_module_dep MAKEFILE SOURCE_DIRECTORY SOURCE_FILES for single file: kemo_module_dep MAKEFILE SOURCE_FILES Output command list for source with .f90 extension -c $< Output command list for source with .F90 extension -c $<.
 Warning: To use this program, module name
          must be same as the file name!!
Function/Subroutine Documentation
alloc_mod_list()
subroutine module_dependency::alloc_mod_list
Definition at line 50 of file make_module_dependency.f90.
References mod_name, and ntot.
Referenced by make_multi_mod_dependency().
const_module_list()
subroutine, private module_dependency::const_module_list (character(len=255), intent(in) filename) private
Definition at line 113 of file make_module_dependency.f90.
References exclude_list, extend_mod_list(), mod_name, ntot, num, and num_exclude.
Referenced by make_module_dependency(), and make_module_dependency_f().
dealloc_mod_list()
subroutine module_dependency::dealloc_mod_list
Definition at line 58 of file make_module_dependency.f90.
References mod_name.
extend_mod_list()
subroutine, private module_dependency::extend_mod_list private
Definition at line 66 of file make_module_dependency.f90.
References mod_name, ntot, and num.
Referenced by const_module_list().
getarg_k()
subroutine module_dependency::getarg_k (integer, intent(in) i, character(len=*), intent(out) argc)
Definition at line 84 of file make_module_dependency.f90.
Referenced by make_multi_mod_dependency().
iargc_kemo()
integer function module_dependency::iargc_kemo
Definition at line 99 of file make_module_dependency.f90.
Referenced by make_multi_mod_dependency().
make_module_dependency()
subroutine module_dependency::make_module_dependency (character(len=255), intent(in) dirname, character(len=255), intent(in) filename)
Definition at line 198 of file make_module_dependency.f90.
References const_module_list(), and write_module_list().
Referenced by make_multi_mod_dependency().
make_module_dependency_f()
subroutine module_dependency::make_module_dependency_f (character(len=255), intent(in) dirname, character(len=255), intent(in) filename)
Definition at line 232 of file make_module_dependency.f90.
References const_module_list(), and write_module_list().
write_module_list()
subroutine, private module_dependency::write_module_list (character(len=255), intent(in) objfile, character(len=255), intent(in) filename, character(len=255), intent(in) dirname, integer, intent(in) iflag_cpp) private
Definition at line 159 of file make_module_dependency.f90.
References command, command_cpp, id_makefile, mod_name, and num.
Referenced by make_module_dependency(), and make_module_dependency_f().
Variable Documentation
command
character(len=28), parameter, private module_dependency::command = ' $(F90) -c $(F90OPTFLAGS) $<' private
Definition at line 26 of file make_module_dependency.f90.
Referenced by write_module_list().
command_cpp
character(len=43), parameter, private module_dependency::command_cpp = ' $(F90) -c $(F90OPTFLAGS) $(F90CPPFLAGS) $<' private
Definition at line 28 of file make_module_dependency.f90.
Referenced by write_module_list().
exclude_list
character(len=31), dimension(num_exclude) module_dependency::exclude_list = (/'ISO_C_BINDING', 'hdf5 ', 'mpi '/)
Definition at line 32 of file make_module_dependency.f90.
Referenced by const_module_list().
id_makefile
integer, parameter module_dependency::id_makefile = 21
Definition at line 24 of file make_module_dependency.f90.
Referenced by make_multi_mod_dependency(), and write_module_list().
mod_name
character(len=64), dimension(:), allocatable module_dependency::mod_name
Definition at line 25 of file make_module_dependency.f90.
Referenced by alloc_mod_list(), const_module_list(), dealloc_mod_list(), extend_mod_list(), and write_module_list().
ntot
integer module_dependency::ntot
Definition at line 23 of file make_module_dependency.f90.
Referenced by alloc_mod_list(), const_module_list(), extend_mod_list(), and make_multi_mod_dependency().
num
integer module_dependency::num
Definition at line 23 of file make_module_dependency.f90.
Referenced by const_module_list(), extend_mod_list(), and write_module_list().
num_exclude
integer, parameter, private module_dependency::num_exclude = 3 private
Definition at line 31 of file make_module_dependency.f90.
Referenced by const_module_list().