CALYPSO: gz_group_data_io Module Reference
gz_group_data_io Module Reference
Functions/Subroutines
subroutine read_group_data_gz (grp_IO, zbuf)
subroutine read_surface_group_data_gz (surf_grp_IO, zbuf)
subroutine write_group_data_gz (grp_IO, zbuf)
subroutine write_surf_group_data_gz (surf_grp_IO, zbuf)
Function/Subroutine Documentation
read_group_data_gz()
subroutine gz_group_data_io::read_group_data_gz (type(group_data), intent(inout) grp_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 34 of file gz_group_data_IO.f90.
References t_group_data::alloc_group_item(), t_group_data::alloc_group_num(), gz_data_io::read_gz_integer_stack(), gz_data_io::read_gz_multi_int(), skip_gz_comment::skip_gz_comment_chara(), and skip_gz_comment::skip_gz_comment_int().
Referenced by gz_mesh_data_io::gz_read_mesh_groups(), gz_sph_modes_grids_data_io::read_geom_rtp_data_gz(), and gz_sph_modes_grids_data_io::read_spectr_modes_rj_data_gz().
read_surface_group_data_gz()
subroutine gz_group_data_io::read_surface_group_data_gz (type(surface_group_data), intent(inout) surf_grp_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 70 of file gz_group_data_IO.f90.
References t_group_data::alloc_sf_group_item(), t_group_data::alloc_sf_group_num(), m_constants::ione, m_constants::itwo, gz_data_io::read_gz_integer_stack(), gz_data_io::read_gz_surf_group(), skip_gz_comment::skip_gz_comment_chara(), and skip_gz_comment::skip_gz_comment_int().
Referenced by gz_mesh_data_io::gz_read_mesh_groups().
write_group_data_gz()
subroutine gz_group_data_io::write_group_data_gz (type(group_data), intent(in) grp_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 113 of file gz_group_data_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf(), and gz_data_io::write_gz_multi_int_8i16().
Referenced by gz_mesh_data_io::gz_write_mesh_groups(), gz_sph_modes_grids_data_io::write_geom_rtp_data_gz(), and gz_sph_modes_grids_data_io::write_spectr_modes_rj_data_gz().
write_surf_group_data_gz()
subroutine gz_group_data_io::write_surf_group_data_gz (type(surface_group_data), intent(in) surf_grp_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 158 of file gz_group_data_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf(), m_constants::ione, m_constants::itwo, gz_data_io::write_gz_multi_int_8i16(), and gz_data_io::write_gz_surf_group().
Referenced by gz_mesh_data_io::gz_write_mesh_groups().