CALYPSO: set_patches_for_psf Module Reference
set_patches_for_psf Module Reference
count and set surface patch
Functions/Subroutines
subroutine count_psf_patches (node, ele, edge, sf_grp, psf_case_tbls, psf_def, psf_search, psf_list, psf_patch, ntot_failed)
subroutine count_iso_patches (node, ele, edge, psf_case_tbls, iso_search, iso_list, iso_patch)
subroutine set_psf_patches (ele, edge, sf_grp, psf_case_tbls, psf_def, psf_search, psf_list, psf_grp_list, psf_patch)
subroutine set_iso_patches (edge, psf_case_tbls, iso_search, iso_list, iso_patch)
Detailed Description
count and set surface patch
      subroutine count_psf_patches                                    &
     &         (node, ele, edge, sf_grp, psf_case_tbls,               &
     &          psf_def, psf_search, psf_list, psf_mesh, ntot_failed)
        type(node_data), intent(in) :: node
        type(element_data), intent(in) :: ele
        type(edge_data), intent(in) :: edge
        type(surface_group_data), intent(in) :: sf_grp
        type(psf_cases), intent(in) :: psf_case_tbls
        type(section_define), intent(in) :: psf_def
        type(psf_search_lists), intent(inout) :: psf_search
        type(sectioning_list), intent(inout) :: psf_list
        type(psf_local_data), intent(inout) :: psf_mesh
      subroutine count_iso_patches(node, ele, edge,  psf_case_tbls,   &
     &         iso_search, iso_list, iso_patch)
        type(node_data), intent(in) :: node
        type(element_data), intent(in) :: ele
        type(edge_data), intent(in) :: edge
        type(psf_cases), intent(in) :: psf_case_tbls
        type(psf_search_lists), intent(inout) :: iso_search
        type(sectioning_list), intent(inout) :: iso_list
        type(psf_local_data), intent(inout) :: iso_mesh
      subroutine set_psf_patches                                      &
     &         (ele, edge, sf_grp, psf_case_tbls, psf_def,            &
     &          psf_search, psf_list, psf_grp_list, psf_patch)
        type(element_data), intent(in) :: ele
        type(edge_data), intent(in) :: edge
        type(surface_group_data), intent(in) :: sf_grp
        type(psf_cases), intent(in) :: psf_case_tbls
        type(section_define), intent(in) :: psf_def
        type(psf_search_lists), intent(in) :: psf_search
        type(sectioning_list), intent(in) :: psf_list
        type(grp_section_list), intent(inout) :: psf_grp_list
        type(psf_local_data), intent(inout) :: psf_mesh
      subroutine set_iso_patches                                      &
     &         (edge, psf_case_tbls, iso_search, iso_list, iso_patch)
        type(element_data), intent(in) :: ele
        type(edge_data), intent(in) :: edge
        type(psf_cases), intent(in) :: psf_case_tbls
        type(psf_search_lists), intent(in) :: iso_search
        type(sectioning_list), intent(in) :: iso_list
        type(psf_local_data), intent(inout) :: iso_mesh
Function/Subroutine Documentation
count_iso_patches()
subroutine set_patches_for_psf::count_iso_patches (type(node_data), intent(in) node, type(element_data), intent(in) ele, type(edge_data), intent(in) edge, type(psf_cases), intent(in) psf_case_tbls, type(psf_search_lists), intent(inout) iso_search, type(sectioning_list), intent(inout) iso_list, type(element_data), intent(inout) iso_patch)
Definition at line 124 of file set_patches_for_psf.f90.
References t_psf_geometry_list::alloc_mark_ele_psf(), patch_4_psf::count_num_patch_4_psf(), m_machine_parameter::np_smp, m_geometry_constants::num_triangle, and patch_4_psf::set_psf_type_id().
Referenced by find_node_and_patch_psf::set_node_and_patch_iso().
count_psf_patches()
subroutine set_patches_for_psf::count_psf_patches (type(node_data), intent(in) node, type(element_data), intent(in) ele, type(edge_data), intent(in) edge, type(surface_group_data), intent(in) sf_grp, type(psf_cases), intent(in) psf_case_tbls, type(section_define), intent(in) psf_def, type(psf_search_lists), intent(inout) psf_search, type(sectioning_list), intent(inout) psf_list, type(element_data), intent(inout) psf_patch, integer(kind = kint), intent(inout) ntot_failed)
Definition at line 75 of file set_patches_for_psf.f90.
References t_psf_geometry_list::alloc_mark_ele_psf(), set_psf_patch_4_by_surf_grp::count_num_patch_4_grp(), patch_4_psf::count_num_patch_4_psf(), m_machine_parameter::np_smp, m_geometry_constants::num_triangle, and patch_4_psf::set_psf_type_id().
Referenced by find_node_and_patch_psf::set_node_and_patch_psf().
set_iso_patches()
subroutine set_patches_for_psf::set_iso_patches (type(edge_data), intent(in) edge, type(psf_cases), intent(in) psf_case_tbls, type(psf_search_lists), intent(in) iso_search, type(sectioning_list), intent(in) iso_list, type(element_data), intent(inout) iso_patch)
Definition at line 214 of file set_patches_for_psf.f90.
References transfer_to_long_integers::alloc_2d_i8array(), t_geometry_data::allocate_ele_connect_type(), transfer_to_long_integers::cast_long(), const_element_comm_tables::const_global_numele_list(), transfer_to_long_integers::dup_to_short_darray(), calypso_mpi::my_rank, m_geometry_constants::num_triangle, and patch_4_psf::set_patch_4_psf().
Referenced by find_node_and_patch_psf::set_node_and_patch_iso().
set_psf_patches()
subroutine set_patches_for_psf::set_psf_patches (type(element_data), intent(in) ele, type(edge_data), intent(in) edge, type(surface_group_data), intent(in) sf_grp, type(psf_cases), intent(in) psf_case_tbls, type(section_define), intent(in) psf_def, type(psf_search_lists), intent(in) psf_search, type(sectioning_list), intent(in) psf_list, type(grp_section_list), intent(in) psf_grp_list, type(element_data), intent(inout) psf_patch)
Definition at line 160 of file set_patches_for_psf.f90.
References transfer_to_long_integers::alloc_2d_i8array(), t_geometry_data::allocate_ele_connect_type(), transfer_to_long_integers::cast_long(), const_element_comm_tables::const_global_numele_list(), transfer_to_long_integers::dup_to_short_darray(), calypso_mpi::my_rank, m_geometry_constants::num_triangle, set_psf_patch_4_by_surf_grp::set_patch_4_grp(), and patch_4_psf::set_patch_4_psf().
Referenced by find_node_and_patch_psf::set_node_and_patch_psf().