CALYPSO: t_base_force_labels Module Reference
t_base_force_labels Module Reference
Data Types
type base_force_address
Structure for start address for base forces.
Functions/Subroutines
subroutine set_base_force_addresses (i_phys, field_name, forces, flag)
subroutine set_rot_force_addresses (i_phys, field_name, rot_forces, flag)
subroutine set_div_force_addresses (i_phys, field_name, div_forces, flag)
Function/Subroutine Documentation
set_base_force_addresses()
subroutine t_base_force_labels::set_base_force_addresses (integer(kind = kint), intent(in) i_phys, character(len = kchara), intent(in) field_name, type(base_force_address), intent(inout) forces, logical, intent(inout) flag)
Definition at line 148 of file t_base_force_labels.f90.
References m_base_force_labels::buoyancy, m_base_force_labels::check_asym_flux_tensors(), m_base_force_labels::check_flux_tensors(), m_base_force_labels::check_force_vectors(), m_base_force_labels::check_scalar_advection(), m_base_force_labels::composite_buoyancy, m_base_force_labels::composite_flux, m_base_force_labels::composition_advect, m_base_force_labels::coriolis_force, m_base_force_labels::heat_advect, m_base_force_labels::heat_flux, m_base_force_labels::induction_tensor, m_base_force_labels::inertia, m_base_force_labels::lorentz_force, m_base_force_labels::magnetic_induction, m_base_force_labels::magnetic_stretch, m_base_force_labels::magnetic_tension, m_base_force_labels::maxwell_tensor, m_base_force_labels::momentum_flux, m_base_force_labels::pert_comp_advect, m_base_force_labels::pert_comp_flux, m_base_force_labels::pert_heat_advect, m_base_force_labels::pert_heat_flux, m_base_force_labels::pressure_gradient, and m_base_force_labels::vecp_induction.
Referenced by set_mhd_field_address::set_mhd_field_addresses().
set_div_force_addresses()
subroutine t_base_force_labels::set_div_force_addresses (integer(kind = kint), intent(in) i_phys, character(len = kchara), intent(in) field_name, type(base_force_address), intent(inout) div_forces, logical, intent(inout) flag)
Definition at line 254 of file t_base_force_labels.f90.
References m_div_force_labels::check_div_flux_tensor(), m_div_force_labels::check_div_force(), m_div_force_labels::check_div_scalar_flux(), m_div_force_labels::div_buoyancy, m_div_force_labels::div_composite_buoyancy, m_div_force_labels::div_composition_flux, m_div_force_labels::div_coriolis_force, m_div_force_labels::div_heat_flux, m_div_force_labels::div_induction_tensor, m_div_force_labels::div_inertia, m_div_force_labels::div_lorentz_force, m_div_force_labels::div_maxwell_tensor, m_div_force_labels::div_momentum_flux, m_div_force_labels::div_pert_composition_flux, and m_div_force_labels::div_pert_heat_flux.
Referenced by set_mhd_field_address::set_mhd_field_addresses().
set_rot_force_addresses()
subroutine t_base_force_labels::set_rot_force_addresses (integer(kind = kint), intent(in) i_phys, character(len = kchara), intent(in) field_name, type(base_force_address), intent(inout) rot_forces, logical, intent(inout) flag)
Definition at line 221 of file t_base_force_labels.f90.
References m_rot_force_labels::check_rot_force(), m_rot_force_labels::rot_buoyancy, m_rot_force_labels::rot_composite_buoyancy, m_rot_force_labels::rot_coriolis_force, m_rot_force_labels::rot_inertia, and m_rot_force_labels::rot_lorentz_force.
Referenced by set_mhd_field_address::set_mhd_field_addresses().