CALYPSO: mpi_element_data_io Module Reference
mpi_element_data_io Module Reference
Data IO routines for element data.
Functions/Subroutines
subroutine mpi_read_element_comm_table (IO_param, comm_IO)
subroutine mpi_write_element_comm_table (IO_param, comm_IO)
subroutine mpi_read_element_geometry (IO_param, nod_IO, sfed_IO)
subroutine mpi_write_element_geometry (IO_param, nod_IO, sfed_IO)
Detailed Description
Data IO routines for element data.
      subroutine mpi_read_element_comm_table(IO_param, comm_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(communication_table), intent(inout) :: comm_IO
      subroutine mpi_write_element_comm_table(IO_param, comm_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(communication_table), intent(in) :: comm_IO
      subroutine mpi_read_element_geometry(IO_param, nod_IO, sfed_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(node_data), intent(inout) :: nod_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
      subroutine mpi_write_element_geometry(IO_param, nod_IO, sfed_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(node_data), intent(in) :: nod_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
Function/Subroutine Documentation
mpi_read_element_comm_table()
subroutine mpi_element_data_io::mpi_read_element_comm_table (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(inout) comm_IO)
Definition at line 50 of file MPI_element_data_IO.f90.
References m_fem_surface_labels::hd_ecomm_export(), m_fem_surface_labels::hd_ecomm_import(), m_fem_surface_labels::hd_ecomm_para(), m_fem_mesh_labels::hd_fem_para(), mpi_domain_data_io::mpi_read_domain_info(), mpi_domain_data_io::mpi_read_export_data(), mpi_domain_data_io::mpi_read_import_data(), and mpi_ascii_data_io::mpi_skip_read().
Referenced by mpi_element_file_io::mpi_input_element_file().
mpi_read_element_geometry()
subroutine mpi_element_data_io::mpi_read_element_geometry (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 99 of file MPI_element_data_IO.f90.
References m_fem_surface_labels::hd_ecomm_point(), m_fem_surface_labels::hd_ecomm_vol(), mpi_node_geometry_io::mpi_read_geometry_info(), mpi_node_geometry_io::mpi_read_number_of_node(), mpi_node_geometry_io::mpi_read_scl_in_ele(), and mpi_ascii_data_io::mpi_skip_read().
mpi_write_element_comm_table()
subroutine mpi_element_data_io::mpi_write_element_comm_table (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(in) comm_IO)
Definition at line 72 of file MPI_element_data_IO.f90.
References m_fem_surface_labels::hd_ecomm_export(), m_fem_surface_labels::hd_ecomm_import(), m_fem_surface_labels::hd_ecomm_para(), m_fem_mesh_labels::hd_fem_para(), mpi_ascii_data_io::mpi_write_charahead(), mpi_domain_data_io::mpi_write_domain_info(), mpi_domain_data_io::mpi_write_export_data(), and mpi_domain_data_io::mpi_write_import_data().
Referenced by mpi_element_file_io::mpi_output_element_file().
mpi_write_element_geometry()
subroutine mpi_element_data_io::mpi_write_element_geometry (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 117 of file MPI_element_data_IO.f90.
References m_fem_surface_labels::hd_ecomm_point(), m_fem_surface_labels::hd_ecomm_vol(), mpi_ascii_data_io::mpi_write_charahead(), mpi_node_geometry_io::mpi_write_geometry_info(), and mpi_node_geometry_io::mpi_write_scl_in_ele().