CALYPSO: const_each_global_sph_list Module Reference
const_each_global_sph_list Module Reference
Set global spherical harmonics ID.
Functions/Subroutines
subroutine const_global_rtp_grids (sph_params, sph_rtp, s3d_ranks, sph_lc1, sph_lcp, sph_dbc, stk_lc1d)
subroutine const_global_rtm_grids (sph_params, sph_rtm, s3d_ranks, sph_lc1, sph_lcp, sph_dbc, stk_lc1d)
subroutine const_global_rj_modes_by_rlm (sph_rj, s3d_ranks, sph_lc1, sph_lcp, stk_lc1d, s2d_tbl)
subroutine const_global_rlm_modes (sph_params, sph_rtp, sph_rj, s3d_ranks, sph_lc1, sph_lcp, stk_lc1d, s2d_tbl)
Detailed Description
Set global spherical harmonics ID.
      subroutine const_global_rtp_grids(sph_params, sph_rtp,          &
     &          s3d_ranks, sph_lc1, sph_lcp, sph_dbc, stk_lc1d)
      subroutine const_global_rtm_grids(sph_params, sph_rtm,          &
     &          s3d_ranks, sph_lc1, sph_lcp, sph_dbc, stk_lc1d)
      subroutine const_global_rj_modes_by_rlm                         &
     &         (sph_rj, s3d_ranks, sph_lc1, sph_lcp, stk_lc1d, s2d_tbl)
      subroutine const_global_rlm_modes(sph_params, sph_rtp, sph_rj,  &
     &          s3d_ranks, sph_lc1, sph_lcp, stk_lc1d, s2d_tbl)
        type(sph_shell_parameters), intent(in) :: sph_params
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_rtm_grid), intent(in) :: sph_rtm
        type(sph_rj_grid), intent(in) :: sph_rj
        type(spheric_global_rank), intent(inout) :: s3d_ranks
        type(sph_local_1d_param), intent(inout) :: sph_lc1
        type(sph_local_parameters), intent(inout) :: sph_lcp
        type(sph_local_default_BC), intent(inout) :: sph_dbc
        type(sph_1d_index_stack), intent(inout) :: stk_lc1d
Parameters
ip_rank process ID
Function/Subroutine Documentation
const_global_rj_modes_by_rlm()
subroutine const_each_global_sph_list::const_global_rj_modes_by_rlm (type(sph_rj_grid), intent(in) sph_rj, type(spheric_global_rank), intent(inout) s3d_ranks, type(sph_local_1d_param), intent(inout) sph_lc1, type(sph_local_parameters), intent(inout) sph_lcp, type(sph_1d_index_stack), intent(inout) stk_lc1d, type(sph_trans_2d_table), intent(inout) s2d_tbl)
Definition at line 193 of file const_each_global_sph_list.f90.
References set_indices_4_sph_tranform::cal_local_nums(), m_constants::ione, set_global_spherical_param::set_gl_nnod_spheric_rj(), set_global_spherical_param::set_gl_rank_2d(), and set_sph_tranform_ordering::set_merged_index_4_sph_rj().
Referenced by const_global_sph_grids_modes::s_const_global_sph_grids_modes().
const_global_rlm_modes()
subroutine const_each_global_sph_list::const_global_rlm_modes (type(sph_shell_parameters), intent(in) sph_params, type(sph_rtp_grid), intent(in) sph_rtp, type(sph_rj_grid), intent(in) sph_rj, type(spheric_global_rank), intent(inout) s3d_ranks, type(sph_local_1d_param), intent(inout) sph_lc1, type(sph_local_parameters), intent(inout) sph_lcp, type(sph_1d_index_stack), intent(inout) stk_lc1d, type(sph_trans_2d_table), intent(inout) s2d_tbl)
Definition at line 232 of file const_each_global_sph_list.f90.
References select_zonal_4_legendre::sel_zonal_ordering_4_leg_trns(), set_global_spherical_param::set_gl_nnod_spheric_rj(), set_global_spherical_param::set_gl_rank_2d(), set_sph_tranform_ordering::set_merged_index_4_sph_trans(), and set_sph_tranform_ordering::set_wavenumber_4_ispack_fft().
Referenced by const_global_sph_grids_modes::s_const_global_sph_grids_modes().
const_global_rtm_grids()
subroutine const_each_global_sph_list::const_global_rtm_grids (type(sph_shell_parameters), intent(in) sph_params, type(sph_rtm_grid), intent(in) sph_rtm, type(spheric_global_rank), intent(inout) s3d_ranks, type(sph_local_1d_param), intent(inout) sph_lc1, type(sph_local_parameters), intent(inout) sph_lcp, type(sph_local_default_bc), intent(inout) sph_dbc, type(sph_1d_index_stack), intent(inout) stk_lc1d)
Definition at line 128 of file const_each_global_sph_list.f90.
References set_indices_4_sph_tranform::cal_local_num_rtm_m(), set_indices_4_sph_tranform::cal_local_nums(), set_indices_4_sph_tranform::cal_local_nums_rev(), set_indices_4_sph_tranform::cal_local_nums_st(), m_constants::ione, set_indices_4_sph_tranform::merge_num_3_local_layers(), set_global_spherical_param::set_gl_nnod_spherical(), and set_global_spherical_param::set_gl_rank_3d().
Referenced by const_global_sph_grids_modes::s_const_global_sph_grids_modes().
const_global_rtp_grids()
subroutine const_each_global_sph_list::const_global_rtp_grids (type(sph_shell_parameters), intent(in) sph_params, type(sph_rtp_grid), intent(in) sph_rtp, type(spheric_global_rank), intent(inout) s3d_ranks, type(sph_local_1d_param), intent(inout) sph_lc1, type(sph_local_parameters), intent(inout) sph_lcp, type(sph_local_default_bc), intent(inout) sph_dbc, type(sph_1d_index_stack), intent(inout) stk_lc1d)
Definition at line 56 of file const_each_global_sph_list.f90.
References set_indices_4_sph_tranform::cal_local_nums(), set_indices_4_sph_tranform::cal_local_nums_rev(), set_indices_4_sph_tranform::cal_local_nums_st(), m_constants::ione, set_indices_4_sph_tranform::merge_num_3_local_layers(), set_global_spherical_param::set_gl_nnod_spherical(), and set_global_spherical_param::set_gl_rank_3d().
Referenced by const_global_sph_grids_modes::const_global_sph_fem_grid(), and const_global_sph_grids_modes::s_const_global_sph_grids_modes().