CALYPSO: cvt_xyz_tensor_2_cyl_smp Module Reference
cvt_xyz_tensor_2_cyl_smp Module Reference
Functions/Subroutines
subroutine cal_cyl_tensor_smp (np_smp, numnod, inod_smp_stack, tensor, tcyl, xx, yy, s, a_s)
subroutine overwrite_cyl_tensor_smp (np_smp, numnod, inod_smp_stack, tensor, xx, yy, s, a_s)
subroutine cal_ss_tensor_smp (np_smp, numnod, inod_smp_stack, tensor, t_ss, xx, yy, s, a_s)
subroutine cal_sp_tensor_smp (np_smp, numnod, inod_smp_stack, tensor, t_sp, xx, yy, s, a_s)
subroutine cal_sz_tensor_smp (np_smp, numnod, inod_smp_stack, tensor, t_sz, xx, yy, s, a_s)
subroutine cal_pp_cyl_tensor_smp (np_smp, numnod, inod_smp_stack, tensor, t_pp, xx, yy, s, a_s)
subroutine cal_pz_tensor_smp (np_smp, numnod, inod_smp_stack, tensor, t_pz, xx, yy, s, a_s)
subroutine cal_zz_tensor_smp (np_smp, numnod, inod_smp_stack, tensor, t_zz)
Function/Subroutine Documentation
cal_cyl_tensor_smp()
subroutine cvt_xyz_tensor_2_cyl_smp::cal_cyl_tensor_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,6), intent(in) tensor, real(kind=kreal), dimension(numnod,6), intent(inout) tcyl, real(kind=kreal), dimension(numnod), intent(in) xx, real(kind=kreal), dimension(numnod), intent(in) yy, real(kind=kreal), dimension(numnod), intent(in) s, real(kind=kreal), dimension(numnod), intent(in) a_s)
Definition at line 71 of file cvt_xyz_tensor_2_cyl_smp.f90.
References m_constants::two.
Referenced by convert_components_4_viz::convert_comps_4_viz().
cal_pp_cyl_tensor_smp()
subroutine cvt_xyz_tensor_2_cyl_smp::cal_pp_cyl_tensor_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,6), intent(in) tensor, real(kind=kreal), dimension(numnod), intent(inout) t_pp, real(kind=kreal), dimension(numnod), intent(in) xx, real(kind=kreal), dimension(numnod), intent(in) yy, real(kind=kreal), dimension(numnod), intent(in) s, real(kind=kreal), dimension(numnod), intent(in) a_s)
Definition at line 334 of file cvt_xyz_tensor_2_cyl_smp.f90.
References m_constants::two.
Referenced by convert_components_4_viz::convert_comps_4_viz().
cal_pz_tensor_smp()
subroutine cvt_xyz_tensor_2_cyl_smp::cal_pz_tensor_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,6), intent(in) tensor, real(kind=kreal), dimension(numnod), intent(inout) t_pz, real(kind=kreal), dimension(numnod), intent(in) xx, real(kind=kreal), dimension(numnod), intent(in) yy, real(kind=kreal), dimension(numnod), intent(in) s, real(kind=kreal), dimension(numnod), intent(in) a_s)
Definition at line 376 of file cvt_xyz_tensor_2_cyl_smp.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz().
cal_sp_tensor_smp()
subroutine cvt_xyz_tensor_2_cyl_smp::cal_sp_tensor_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,6), intent(in) tensor, real(kind=kreal), dimension(numnod), intent(inout) t_sp, real(kind=kreal), dimension(numnod), intent(in) xx, real(kind=kreal), dimension(numnod), intent(in) yy, real(kind=kreal), dimension(numnod), intent(in) s, real(kind=kreal), dimension(numnod), intent(in) a_s)
Definition at line 252 of file cvt_xyz_tensor_2_cyl_smp.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz().
cal_ss_tensor_smp()
subroutine cvt_xyz_tensor_2_cyl_smp::cal_ss_tensor_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,6), intent(in) tensor, real(kind=kreal), dimension(numnod), intent(inout) t_ss, real(kind=kreal), dimension(numnod), intent(in) xx, real(kind=kreal), dimension(numnod), intent(in) yy, real(kind=kreal), dimension(numnod), intent(in) s, real(kind=kreal), dimension(numnod), intent(in) a_s)
Definition at line 210 of file cvt_xyz_tensor_2_cyl_smp.f90.
References m_constants::two.
Referenced by convert_components_4_viz::convert_comps_4_viz().
cal_sz_tensor_smp()
subroutine cvt_xyz_tensor_2_cyl_smp::cal_sz_tensor_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,6), intent(in) tensor, real(kind=kreal), dimension(numnod), intent(inout) t_sz, real(kind=kreal), dimension(numnod), intent(in) xx, real(kind=kreal), dimension(numnod), intent(in) yy, real(kind=kreal), dimension(numnod), intent(in) s, real(kind=kreal), dimension(numnod), intent(in) a_s)
Definition at line 295 of file cvt_xyz_tensor_2_cyl_smp.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz().
cal_zz_tensor_smp()
subroutine cvt_xyz_tensor_2_cyl_smp::cal_zz_tensor_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,6), intent(in) tensor, real(kind=kreal), dimension(numnod), intent(inout) t_zz)
Definition at line 415 of file cvt_xyz_tensor_2_cyl_smp.f90.
Referenced by convert_components_4_viz::convert_comps_4_viz().
overwrite_cyl_tensor_smp()
subroutine cvt_xyz_tensor_2_cyl_smp::overwrite_cyl_tensor_smp (integer (kind = kint), intent(in) np_smp, integer (kind = kint), intent(in) numnod, integer (kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind=kreal), dimension(numnod,6), intent(inout) tensor, real(kind=kreal), dimension(numnod), intent(in) xx, real(kind=kreal), dimension(numnod), intent(in) yy, real(kind=kreal), dimension(numnod), intent(in) s, real(kind=kreal), dimension(numnod), intent(in) a_s)
Definition at line 141 of file cvt_xyz_tensor_2_cyl_smp.f90.
References m_constants::two.
Referenced by coordinate_convert_4_sph::overwrite_nodal_xyz_2_cyl_smp().