CALYPSO: set_surface_data Module Reference
set_surface_data Module Reference
Functions/Subroutines
subroutine count_all_surfaces (ntot_list, isurf_flag, numsurf)
subroutine set_all_surfaces (numele, numsurf, nnod_4_ele, nnod_4_surf, ie, node_on_sf, ntot_list, isurf_hash, isurf_flag, ie_surf, isf_4_ele)
subroutine set_surf_rotation_flag (numele, numsurf, nnod_4_ele, nnod_4_surf, ie, ie_surf, isf_4_ele, isf_rot_ele)
subroutine count_part_surface (nele_grp, ntot_list, isurf_flag, numsurf_part)
subroutine set_part_surface (numele, nele_grp, numsurf_part, isf_4_ele, ntot_list, isurf_hash, isurf_flag, isf_part)
Function/Subroutine Documentation
count_all_surfaces()
subroutine set_surface_data::count_all_surfaces (integer(kind = kint_gl), intent(in) ntot_list, integer(kind = kint_gl), dimension(ntot_list), intent(in) isurf_flag, integer(kind = kint), intent(inout) numsurf)
Definition at line 33 of file set_surface_data.f90.
Referenced by const_surface_data::const_all_surface_data().
count_part_surface()
subroutine set_surface_data::count_part_surface (integer(kind = kint), intent(in) nele_grp, integer(kind = kint_gl), intent(in) ntot_list, integer(kind = kint_gl), dimension(ntot_list), intent(in) isurf_flag, integer(kind = kint), intent(inout) numsurf_part)
Definition at line 158 of file set_surface_data.f90.
References m_geometry_constants::nsurf_4_ele.
Referenced by const_surface_data::const_external_surface_data(), const_surface_data::const_isolate_surface_data(), and const_merged_surf_4_group::const_merged_surface_4_ele_grp().
set_all_surfaces()
subroutine set_surface_data::set_all_surfaces (integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) numsurf, integer(kind = kint), intent(in) nnod_4_ele, integer(kind = kint), intent(in) nnod_4_surf, integer(kind = kint), dimension(numele,nnod_4_ele), intent(in) ie, integer(kind = kint), dimension(nnod_4_surf,nsurf_4_ele), intent(in) node_on_sf, integer(kind = kint_gl), intent(in) ntot_list, integer(kind = kint), dimension(ntot_list,2), intent(in) isurf_hash, integer(kind = kint_gl), dimension(ntot_list), intent(in) isurf_flag, integer(kind = kint), dimension(numsurf,nnod_4_surf), intent(inout) ie_surf, integer(kind = kint), dimension(numele,nsurf_4_ele), intent(inout) isf_4_ele)
Definition at line 52 of file set_surface_data.f90.
Referenced by const_surface_data::const_all_surface_data().
set_part_surface()
subroutine set_surface_data::set_part_surface (integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) nele_grp, integer(kind = kint), intent(in) numsurf_part, integer(kind = kint), dimension(numele,nsurf_4_ele), intent(in) isf_4_ele, integer(kind = kint_gl), intent(in) ntot_list, integer(kind = kint), dimension(ntot_list,2), intent(in) isurf_hash, integer(kind = kint_gl), dimension(ntot_list), intent(in) isurf_flag, integer(kind = kint), dimension(numsurf_part), intent(inout) isf_part)
Definition at line 180 of file set_surface_data.f90.
Referenced by const_surface_data::const_external_surface_data(), const_surface_data::const_isolate_surface_data(), and const_merged_surf_4_group::const_merged_surface_4_ele_grp().
set_surf_rotation_flag()
subroutine set_surface_data::set_surf_rotation_flag (integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) numsurf, integer(kind = kint), intent(in) nnod_4_ele, integer(kind = kint), intent(in) nnod_4_surf, integer(kind = kint), dimension(numele,nnod_4_ele), intent(in) ie, integer(kind = kint), dimension(numsurf,nnod_4_surf), intent(in) ie_surf, integer(kind = kint), dimension(numele,nsurf_4_ele), intent(in) isf_4_ele, integer(kind = kint), dimension(numele,nsurf_4_ele), intent(inout) isf_rot_ele)
Definition at line 114 of file set_surface_data.f90.
References m_geometry_constants::node_on_sf_4.
Referenced by const_surface_data::const_all_surface_data(), and load_element_mesh_data::set_surface_mesh_from_io().