CALYPSO: m_legendre_transform_list Module Reference
m_legendre_transform_list Module Reference
Legendre transform selector.
Functions/Subroutines
integer(kind=kint) function set_legendre_trans_mode_ctl (tranx_loop_ctl)
character(len=kchara) function chosen_legendre_name (i_mode)
subroutine write_elapsed_4_legendre (i_mode, etime_max, etime_trans)
Variables
integer(kind=kint), parameter maxindex_leg_trans_loop = 17
Number of LEgendre transform types.
character(len=kchara), parameter leg_orginal_loop = 'Original_loop'
Character flag to perform Legendre transform.
character(len=kchara), parameter leg_blocked_loop = 'Blocked_loop'
Character flag to perform Legendre transform.
character(len=kchara), parameter leg_krloop_inner = 'Inner_radial_loop'
Character flag to perform Legendre transform
using longer loop for original array order.
character(len=kchara), parameter leg_krloop_outer = 'Outer_radial_loop'
Character flag to perform Legendre transform.
character(len=kchara), parameter leg_sym_org_loop = 'Symmetric_original_loop'
Character flag to perform Legendre transform.
character(len=kchara), parameter leg_sym_spin_loop = 'Symmetric_outer_radial_loop'
Character flag to perform Legendre transform.
character(len=kchara), parameter leg_matmul = 'matmul'
Character flag to perform Legendre transform.
character(len=kchara), parameter leg_dgemm = 'BLAS'
Character flag to perform Legendre transform.
character(len=kchara), parameter leg_matprod = 'Matproduct'
Character flag to perform Legendre transform.
character(len=kchara), parameter leg_sym_matmul = 'Symmetric_matmul'
Chalacter flag to perform Legendre transform.
character(len=kchara), parameter leg_sym_dgemm = 'Symmetric_BLAS'
Character flag to perform Legendre transform.
character(len=kchara), parameter leg_sym_matprod = 'Symmetric_matproduct'
Character flag to perform Legendre transform.
character(len=kchara), parameter leg_sym_matmul_big = 'Symmetric_matmul_big'
Chalacter flag to perform Legendre transform.
character(len=kchara), parameter leg_sym_dgemm_big = 'Symmetric_BLAS_big'
Character flag to perform Legendre transform.
character(len=kchara), parameter leg_sym_matprod_big = 'Symmetric_matproduct_big'
Character flag to perform Legendre transform.
character(len=kchara), parameter leg_sym_mat_jt = 'Pjt_matmul_theta_OMP'
Chalacter flag to perform Legendre transform.
character(len=kchara), parameter leg_sym_dgemm_jt = 'Pjt_BLAS_w_theta_OMP'
Character flag to perform Legendre transform.
character(len=kchara), parameter leg_sym_mat_tj = 'Ptj_matmul_theta_OMP'
Chalacter flag to perform Legendre transform.
character(len=kchara), parameter leg_dgemm_tj = 'Ptj_BLAS_w_theta_OMP'
Character flag to perform Legendre transform.
character(len=kchara), parameter on_the_fly_matmul = 'On_the_fly_Plm_matmul'
Character flag to perform Legendre transform.
character(len=kchara), parameter on_the_fly_dgemm = 'On_the_fly_Plm_BLAS'
Character flag to perform Legendre transform.
character(len=kchara), parameter on_the_fly_matprod = 'On_the_fly_Plm'
Character flag to perform Legendre transform.
character(len=kchara), parameter leg_test_loop = 'Test_Loop'
Character flag to perform Legendre transform.
integer(kind=kint), parameter iflag_leg_undefined = -1
integer flag to run elpse time check for legendre transform
integer(kind=kint), parameter iflag_leg_symmetry = 1
integer flag to perform Legendre transform with symmetry
integer(kind=kint), parameter iflag_leg_sym_spin_loop = 2
integer flag to perform Legendre transform
integer(kind=kint), parameter iflag_leg_sym_matmul = 3
integer flag to perform Legendre transform
integer(kind=kint), parameter iflag_leg_sym_dgemm = 13
integer flag to perform Legendre transform
integer(kind=kint), parameter iflag_leg_sym_matmul_big = 4
integer flag to perform Legendre transform
integer(kind=kint), parameter iflag_leg_sym_dgemm_big = 14
integer flag to perform Legendre transform
integer(kind=kint), parameter iflag_leg_sym_mat_jt = 5
integer flag to perform Legendre transform
integer(kind=kint), parameter iflag_leg_sym_dgemm_jt = 15
integer flag to perform Legendre transform
integer(kind=kint), parameter iflag_leg_sym_mat_tj = 6
integer flag to perform Legendre transform
integer(kind=kint), parameter iflag_leg_sym_dgemm_tj = 16
integer flag to perform Legendre transform
integer(kind=kint), parameter iflag_on_the_fly_matmul = 7
integer flag to perform Legendre transform
integer(kind=kint), parameter iflag_on_the_fly_dgemm = 17
integer flag to perform Legendre transform
integer(kind=kint), parameter iflag_on_the_fly_matprod = 8
integer flag to perform Legendre transform
integer(kind=kint), parameter iflag_leg_test_loop = 99
integer flag to perform Legendre transform
Detailed Description
Legendre transform selector.
      integer(kind = kint) function                                   &
     &                    set_legendre_trans_mode_ctl(tranx_loop_ctl)
      character(len = kchara) function chosen_legendre_name(i_mode)
      subroutine write_elapsed_4_legendre                             &
     &         (i_mode, etime_max, etime_trans)
Parameters
ncomp Total number of components for spherical transform
nvector Number of vector for spherical transform
nscalar Number of scalar (including tensor components) for spherical transform
Function/Subroutine Documentation
chosen_legendre_name()
character(len = kchara) function m_legendre_transform_list::chosen_legendre_name (integer(kind = kint), intent(in) i_mode)
Definition at line 238 of file m_legendre_transform_list.f90.
References iflag_leg_sym_dgemm, iflag_leg_sym_dgemm_big, iflag_leg_sym_dgemm_jt, iflag_leg_sym_dgemm_tj, iflag_leg_sym_mat_jt, iflag_leg_sym_mat_tj, iflag_leg_sym_matmul, iflag_leg_sym_matmul_big, iflag_leg_sym_spin_loop, iflag_leg_symmetry, iflag_leg_test_loop, iflag_on_the_fly_dgemm, iflag_on_the_fly_matmul, iflag_on_the_fly_matprod, leg_dgemm_tj, leg_sym_dgemm, leg_sym_dgemm_big, leg_sym_dgemm_jt, leg_sym_mat_jt, leg_sym_mat_tj, leg_sym_matmul, leg_sym_matmul_big, leg_sym_org_loop, leg_sym_spin_loop, leg_test_loop, on_the_fly_dgemm, on_the_fly_matmul, and on_the_fly_matprod.
Referenced by init_sphrical_transform_mhd::sel_sph_transform_mhd(), and write_elapsed_4_legendre().
set_legendre_trans_mode_ctl()
integer(kind = kint) function m_legendre_transform_list::set_legendre_trans_mode_ctl (character(len = kchara), intent(in) tranx_loop_ctl)
Definition at line 187 of file m_legendre_transform_list.f90.
References skip_comment_f::cmp_no_case(), iflag_leg_sym_dgemm, iflag_leg_sym_dgemm_big, iflag_leg_sym_dgemm_jt, iflag_leg_sym_dgemm_tj, iflag_leg_sym_mat_jt, iflag_leg_sym_mat_tj, iflag_leg_sym_matmul, iflag_leg_sym_matmul_big, iflag_leg_sym_spin_loop, iflag_leg_symmetry, iflag_leg_test_loop, iflag_on_the_fly_dgemm, iflag_on_the_fly_matmul, iflag_on_the_fly_matprod, leg_dgemm_tj, leg_sym_dgemm, leg_sym_dgemm_big, leg_sym_dgemm_jt, leg_sym_mat_jt, leg_sym_mat_tj, leg_sym_matmul, leg_sym_matmul_big, leg_sym_org_loop, leg_sym_spin_loop, leg_test_loop, on_the_fly_dgemm, on_the_fly_matmul, and on_the_fly_matprod.
Referenced by set_control_sph_data_mhd::s_set_control_sph_data_mhd().
write_elapsed_4_legendre()
subroutine m_legendre_transform_list::write_elapsed_4_legendre (integer(kind = kint), intent(in) i_mode, real(kind = kreal), intent(in) etime_max, real(kind = kreal), intent(in) etime_trans)
Definition at line 283 of file m_legendre_transform_list.f90.
References chosen_legendre_name(), iflag_leg_sym_dgemm, iflag_leg_sym_dgemm_big, iflag_leg_sym_dgemm_jt, iflag_leg_sym_dgemm_tj, iflag_leg_sym_mat_jt, iflag_leg_sym_mat_tj, iflag_leg_sym_matmul, iflag_leg_sym_matmul_big, iflag_leg_sym_spin_loop, iflag_leg_symmetry, iflag_on_the_fly_dgemm, iflag_on_the_fly_matmul, and iflag_on_the_fly_matprod.
Variable Documentation
iflag_leg_sym_dgemm
integer(kind = kint), parameter m_legendre_transform_list::iflag_leg_sym_dgemm = 13
integer flag to perform Legendre transform
Definition at line 147 of file m_legendre_transform_list.f90.
Referenced by chosen_legendre_name(), t_legendre_trans_select::sel_backward_legendre_trans(), t_legendre_trans_select::sel_finalize_legendre_trans(), t_legendre_trans_select::sel_forward_legendre_trans(), t_legendre_trans_select::sel_init_legendre_trans(), set_legendre_trans_mode_ctl(), and write_elapsed_4_legendre().
iflag_leg_sym_dgemm_big
integer(kind = kint), parameter m_legendre_transform_list::iflag_leg_sym_dgemm_big = 14
integer flag to perform Legendre transform
Definition at line 153 of file m_legendre_transform_list.f90.
Referenced by chosen_legendre_name(), t_legendre_trans_select::sel_backward_legendre_trans(), t_legendre_trans_select::sel_finalize_legendre_trans(), t_legendre_trans_select::sel_forward_legendre_trans(), t_legendre_trans_select::sel_init_legendre_trans(), set_legendre_trans_mode_ctl(), and write_elapsed_4_legendre().
iflag_leg_sym_dgemm_jt
integer(kind = kint), parameter m_legendre_transform_list::iflag_leg_sym_dgemm_jt = 15
integer flag to perform Legendre transform
Definition at line 159 of file m_legendre_transform_list.f90.
Referenced by chosen_legendre_name(), t_legendre_trans_select::sel_backward_legendre_trans(), t_legendre_trans_select::sel_finalize_legendre_trans(), t_legendre_trans_select::sel_forward_legendre_trans(), t_legendre_trans_select::sel_init_legendre_trans(), set_legendre_trans_mode_ctl(), and write_elapsed_4_legendre().
iflag_leg_sym_dgemm_tj
integer(kind = kint), parameter m_legendre_transform_list::iflag_leg_sym_dgemm_tj = 16
integer flag to perform Legendre transform
Definition at line 165 of file m_legendre_transform_list.f90.
Referenced by chosen_legendre_name(), t_legendre_trans_select::sel_backward_legendre_trans(), t_legendre_trans_select::sel_finalize_legendre_trans(), t_legendre_trans_select::sel_forward_legendre_trans(), t_legendre_trans_select::sel_init_legendre_trans(), set_legendre_trans_mode_ctl(), and write_elapsed_4_legendre().
iflag_leg_sym_mat_jt
integer(kind = kint), parameter m_legendre_transform_list::iflag_leg_sym_mat_jt = 5
integer flag to perform Legendre transform
Definition at line 156 of file m_legendre_transform_list.f90.
Referenced by chosen_legendre_name(), t_legendre_trans_select::sel_backward_legendre_trans(), t_legendre_trans_select::sel_finalize_legendre_trans(), t_legendre_trans_select::sel_forward_legendre_trans(), t_legendre_trans_select::sel_init_legendre_trans(), set_legendre_trans_mode_ctl(), and write_elapsed_4_legendre().
iflag_leg_sym_mat_tj
integer(kind = kint), parameter m_legendre_transform_list::iflag_leg_sym_mat_tj = 6
integer flag to perform Legendre transform
Definition at line 162 of file m_legendre_transform_list.f90.
Referenced by chosen_legendre_name(), t_legendre_trans_select::sel_backward_legendre_trans(), t_legendre_trans_select::sel_finalize_legendre_trans(), t_legendre_trans_select::sel_forward_legendre_trans(), t_legendre_trans_select::sel_init_legendre_trans(), set_legendre_trans_mode_ctl(), and write_elapsed_4_legendre().
iflag_leg_sym_matmul
integer(kind = kint), parameter m_legendre_transform_list::iflag_leg_sym_matmul = 3
integer flag to perform Legendre transform
Definition at line 144 of file m_legendre_transform_list.f90.
Referenced by chosen_legendre_name(), t_legendre_trans_select::sel_backward_legendre_trans(), t_legendre_trans_select::sel_finalize_legendre_trans(), t_legendre_trans_select::sel_forward_legendre_trans(), t_legendre_trans_select::sel_init_legendre_trans(), set_legendre_trans_mode_ctl(), and write_elapsed_4_legendre().
iflag_leg_sym_matmul_big
integer(kind = kint), parameter m_legendre_transform_list::iflag_leg_sym_matmul_big = 4
integer flag to perform Legendre transform
Definition at line 150 of file m_legendre_transform_list.f90.
Referenced by chosen_legendre_name(), t_legendre_trans_select::sel_backward_legendre_trans(), t_legendre_trans_select::sel_finalize_legendre_trans(), t_legendre_trans_select::sel_forward_legendre_trans(), t_legendre_trans_select::sel_init_legendre_trans(), set_legendre_trans_mode_ctl(), and write_elapsed_4_legendre().
iflag_leg_sym_spin_loop
integer(kind = kint), parameter m_legendre_transform_list::iflag_leg_sym_spin_loop = 2
integer flag to perform Legendre transform
Definition at line 141 of file m_legendre_transform_list.f90.
Referenced by chosen_legendre_name(), t_legendre_trans_select::sel_backward_legendre_trans(), t_legendre_trans_select::sel_finalize_legendre_trans(), t_legendre_trans_select::sel_forward_legendre_trans(), t_legendre_trans_select::sel_init_legendre_trans(), set_legendre_trans_mode_ctl(), and write_elapsed_4_legendre().
iflag_leg_symmetry
integer(kind = kint), parameter m_legendre_transform_list::iflag_leg_symmetry = 1
integer flag to perform Legendre transform with symmetry
Definition at line 138 of file m_legendre_transform_list.f90.
Referenced by chosen_legendre_name(), set_legendre_trans_mode_ctl(), and write_elapsed_4_legendre().
iflag_leg_test_loop
integer(kind = kint), parameter m_legendre_transform_list::iflag_leg_test_loop = 99
integer flag to perform Legendre transform
Definition at line 179 of file m_legendre_transform_list.f90.
Referenced by chosen_legendre_name(), t_legendre_trans_select::sel_backward_legendre_trans(), t_legendre_trans_select::sel_finalize_legendre_trans(), t_legendre_trans_select::sel_forward_legendre_trans(), t_legendre_trans_select::sel_init_legendre_trans(), and set_legendre_trans_mode_ctl().
iflag_leg_undefined
integer(kind = kint), parameter m_legendre_transform_list::iflag_leg_undefined = -1
integer flag to run elpse time check for legendre transform
Definition at line 135 of file m_legendre_transform_list.f90.
iflag_on_the_fly_dgemm
integer(kind = kint), parameter m_legendre_transform_list::iflag_on_the_fly_dgemm = 17
integer flag to perform Legendre transform
Definition at line 172 of file m_legendre_transform_list.f90.
Referenced by chosen_legendre_name(), t_legendre_trans_select::sel_backward_legendre_trans(), t_legendre_trans_select::sel_finalize_legendre_trans(), t_legendre_trans_select::sel_forward_legendre_trans(), t_legendre_trans_select::sel_init_legendre_trans(), set_legendre_trans_mode_ctl(), and write_elapsed_4_legendre().
iflag_on_the_fly_matmul
integer(kind = kint), parameter m_legendre_transform_list::iflag_on_the_fly_matmul = 7
integer flag to perform Legendre transform
Definition at line 169 of file m_legendre_transform_list.f90.
Referenced by chosen_legendre_name(), t_legendre_trans_select::sel_backward_legendre_trans(), t_legendre_trans_select::sel_finalize_legendre_trans(), t_legendre_trans_select::sel_forward_legendre_trans(), t_legendre_trans_select::sel_init_legendre_trans(), set_legendre_trans_mode_ctl(), and write_elapsed_4_legendre().
iflag_on_the_fly_matprod
integer(kind = kint), parameter m_legendre_transform_list::iflag_on_the_fly_matprod = 8
integer flag to perform Legendre transform
Definition at line 175 of file m_legendre_transform_list.f90.
Referenced by chosen_legendre_name(), t_legendre_trans_select::sel_backward_legendre_trans(), t_legendre_trans_select::sel_finalize_legendre_trans(), t_legendre_trans_select::sel_forward_legendre_trans(), t_legendre_trans_select::sel_init_legendre_trans(), set_legendre_trans_mode_ctl(), and write_elapsed_4_legendre().
leg_blocked_loop
character(len = kchara), parameter m_legendre_transform_list::leg_blocked_loop = 'Blocked_loop'
Character flag to perform Legendre transform.
Definition at line 38 of file m_legendre_transform_list.f90.
leg_dgemm
character(len = kchara), parameter m_legendre_transform_list::leg_dgemm = 'BLAS'
Character flag to perform Legendre transform.
Definition at line 63 of file m_legendre_transform_list.f90.
leg_dgemm_tj
character(len = kchara), parameter m_legendre_transform_list::leg_dgemm_tj = 'Ptj_BLAS_w_theta_OMP'
Character flag to perform Legendre transform.
Definition at line 111 of file m_legendre_transform_list.f90.
Referenced by chosen_legendre_name(), and set_legendre_trans_mode_ctl().
leg_krloop_inner
character(len = kchara), parameter m_legendre_transform_list::leg_krloop_inner = 'Inner_radial_loop'
Character flag to perform Legendre transform
using longer loop for original array order.
Definition at line 42 of file m_legendre_transform_list.f90.
leg_krloop_outer
character(len = kchara), parameter m_legendre_transform_list::leg_krloop_outer = 'Outer_radial_loop'
Character flag to perform Legendre transform.
Definition at line 46 of file m_legendre_transform_list.f90.
leg_matmul
character(len = kchara), parameter m_legendre_transform_list::leg_matmul = 'matmul'
Character flag to perform Legendre transform.
Definition at line 59 of file m_legendre_transform_list.f90.
leg_matprod
character(len = kchara), parameter m_legendre_transform_list::leg_matprod = 'Matproduct'
Character flag to perform Legendre transform.
Definition at line 67 of file m_legendre_transform_list.f90.
leg_orginal_loop
character(len = kchara), parameter m_legendre_transform_list::leg_orginal_loop = 'Original_loop'
Character flag to perform Legendre transform.
Definition at line 34 of file m_legendre_transform_list.f90.
leg_sym_dgemm
character(len = kchara), parameter m_legendre_transform_list::leg_sym_dgemm = 'Symmetric_BLAS'
Character flag to perform Legendre transform.
Definition at line 76 of file m_legendre_transform_list.f90.
Referenced by chosen_legendre_name(), and set_legendre_trans_mode_ctl().
leg_sym_dgemm_big
character(len = kchara), parameter m_legendre_transform_list::leg_sym_dgemm_big = 'Symmetric_BLAS_big'
Character flag to perform Legendre transform.
Definition at line 89 of file m_legendre_transform_list.f90.
Referenced by chosen_legendre_name(), and set_legendre_trans_mode_ctl().
leg_sym_dgemm_jt
character(len = kchara), parameter m_legendre_transform_list::leg_sym_dgemm_jt = 'Pjt_BLAS_w_theta_OMP'
Character flag to perform Legendre transform.
Definition at line 102 of file m_legendre_transform_list.f90.
Referenced by chosen_legendre_name(), and set_legendre_trans_mode_ctl().
leg_sym_mat_jt
character(len = kchara), parameter m_legendre_transform_list::leg_sym_mat_jt = 'Pjt_matmul_theta_OMP'
Chalacter flag to perform Legendre transform.
Definition at line 98 of file m_legendre_transform_list.f90.
Referenced by chosen_legendre_name(), and set_legendre_trans_mode_ctl().
leg_sym_mat_tj
character(len = kchara), parameter m_legendre_transform_list::leg_sym_mat_tj = 'Ptj_matmul_theta_OMP'
Chalacter flag to perform Legendre transform.
Definition at line 107 of file m_legendre_transform_list.f90.
Referenced by chosen_legendre_name(), and set_legendre_trans_mode_ctl().
leg_sym_matmul
character(len = kchara), parameter m_legendre_transform_list::leg_sym_matmul = 'Symmetric_matmul'
Chalacter flag to perform Legendre transform.
Definition at line 72 of file m_legendre_transform_list.f90.
Referenced by chosen_legendre_name(), and set_legendre_trans_mode_ctl().
leg_sym_matmul_big
character(len = kchara), parameter m_legendre_transform_list::leg_sym_matmul_big = 'Symmetric_matmul_big'
Chalacter flag to perform Legendre transform.
Definition at line 85 of file m_legendre_transform_list.f90.
Referenced by chosen_legendre_name(), and set_legendre_trans_mode_ctl().
leg_sym_matprod
character(len = kchara), parameter m_legendre_transform_list::leg_sym_matprod = 'Symmetric_matproduct'
Character flag to perform Legendre transform.
Definition at line 80 of file m_legendre_transform_list.f90.
leg_sym_matprod_big
character(len = kchara), parameter m_legendre_transform_list::leg_sym_matprod_big = 'Symmetric_matproduct_big'
Character flag to perform Legendre transform.
Definition at line 93 of file m_legendre_transform_list.f90.
leg_sym_org_loop
character(len = kchara), parameter m_legendre_transform_list::leg_sym_org_loop = 'Symmetric_original_loop'
Character flag to perform Legendre transform.
Definition at line 50 of file m_legendre_transform_list.f90.
Referenced by chosen_legendre_name(), and set_legendre_trans_mode_ctl().
leg_sym_spin_loop
character(len = kchara), parameter m_legendre_transform_list::leg_sym_spin_loop = 'Symmetric_outer_radial_loop'
Character flag to perform Legendre transform.
Definition at line 54 of file m_legendre_transform_list.f90.
Referenced by chosen_legendre_name(), and set_legendre_trans_mode_ctl().
leg_test_loop
character(len = kchara), parameter m_legendre_transform_list::leg_test_loop = 'Test_Loop'
Character flag to perform Legendre transform.
Definition at line 129 of file m_legendre_transform_list.f90.
Referenced by chosen_legendre_name(), and set_legendre_trans_mode_ctl().
maxindex_leg_trans_loop
integer(kind = kint), parameter m_legendre_transform_list::maxindex_leg_trans_loop = 17
Number of LEgendre transform types.
Definition at line 30 of file m_legendre_transform_list.f90.
on_the_fly_dgemm
character(len = kchara), parameter m_legendre_transform_list::on_the_fly_dgemm = 'On_the_fly_Plm_BLAS'
Character flag to perform Legendre transform.
Definition at line 120 of file m_legendre_transform_list.f90.
Referenced by chosen_legendre_name(), and set_legendre_trans_mode_ctl().
on_the_fly_matmul
character(len = kchara), parameter m_legendre_transform_list::on_the_fly_matmul = 'On_the_fly_Plm_matmul'
Character flag to perform Legendre transform.
Definition at line 116 of file m_legendre_transform_list.f90.
Referenced by chosen_legendre_name(), and set_legendre_trans_mode_ctl().
on_the_fly_matprod
character(len = kchara), parameter m_legendre_transform_list::on_the_fly_matprod = 'On_the_fly_Plm'
Character flag to perform Legendre transform.
Definition at line 124 of file m_legendre_transform_list.f90.
Referenced by chosen_legendre_name(), and set_legendre_trans_mode_ctl().