CALYPSO: mpi_spherical_model_io_b Module Reference
mpi_spherical_model_io_b Module Reference
Data IO routines for spectrum data.
Functions/Subroutines
subroutine mpi_read_rank_4_sph_b (IO_param, sph_IO)
subroutine mpi_read_gl_reso_sph_b (IO_param, sph_IO)
subroutine mpi_read_gl_nodes_sph_b (IO_param, sph_IO)
subroutine mpi_write_rank_4_sph_b (IO_param, sph_IO)
subroutine mpi_write_gl_reso_sph_b (IO_param, sph_IO)
subroutine mpi_write_gl_nodes_sph_b (IO_param, sph_IO)
Detailed Description
Data IO routines for spectrum data.
      subroutine mpi_read_rank_4_sph_b(IO_param, sph_IO)
      subroutine mpi_read_gl_reso_sph_b(IO_param, sph_IO)
      subroutine mpi_read_gl_nodes_sph_b(IO_param, sph_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(sph_IO_data), intent(inout) :: sph_IO
      subroutine mpi_write_rank_4_sph_b(IO_param, sph_IO)
      subroutine mpi_write_gl_reso_sph_b(IO_param, sph_IO)
      subroutine mpi_write_gl_nodes_sph_b(IO_param, sph_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(sph_IO_data), intent(in) :: sph_IO
Function/Subroutine Documentation
mpi_read_gl_nodes_sph_b()
subroutine mpi_spherical_model_io_b::mpi_read_gl_nodes_sph_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(inout) sph_IO)
Definition at line 72 of file MPI_spherical_model_IO_b.f90.
References t_node_id_spherical_io::alloc_nod_id_sph_io(), mpi_binary_data_io::mpi_read_int8_vector_b(), mpi_binary_data_io::mpi_read_int_vector_b(), and mpi_binary_data_io::mpi_read_one_integer_b().
Referenced by mpi_sph_modes_data_io_b::mpi_read_geom_rtm_data_b(), mpi_sph_modes_data_io_b::mpi_read_geom_rtp_data_b(), mpi_sph_modes_data_io_b::mpi_read_modes_rlm_data_b(), and mpi_sph_modes_data_io_b::mpi_read_spectr_rj_data_b().
mpi_read_gl_reso_sph_b()
subroutine mpi_spherical_model_io_b::mpi_read_gl_reso_sph_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(inout) sph_IO)
Definition at line 55 of file MPI_spherical_model_IO_b.f90.
References mpi_binary_head_io::mpi_read_mul_inthead_b(), and mpi_binary_head_io::mpi_read_one_inthead_b().
Referenced by mpi_sph_modes_data_io_b::mpi_read_geom_rtm_data_b(), mpi_sph_modes_data_io_b::mpi_read_geom_rtp_data_b(), mpi_sph_modes_data_io_b::mpi_read_modes_rlm_data_b(), and mpi_sph_modes_data_io_b::mpi_read_spectr_rj_data_b().
mpi_read_rank_4_sph_b()
subroutine mpi_spherical_model_io_b::mpi_read_rank_4_sph_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(inout) sph_IO)
Definition at line 40 of file MPI_spherical_model_IO_b.f90.
References mpi_binary_data_io::mpi_read_int_vector_b().
Referenced by mpi_sph_modes_data_io_b::mpi_read_geom_rtm_data_b(), mpi_sph_modes_data_io_b::mpi_read_geom_rtp_data_b(), mpi_sph_modes_data_io_b::mpi_read_modes_rlm_data_b(), and mpi_sph_modes_data_io_b::mpi_read_spectr_rj_data_b().
mpi_write_gl_nodes_sph_b()
subroutine mpi_spherical_model_io_b::mpi_write_gl_nodes_sph_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(in) sph_IO)
Definition at line 128 of file MPI_spherical_model_IO_b.f90.
References t_calypso_mpi_io_param::istack64_4_parallel_data(), mpi_binary_data_io::mpi_write_int8_vector_b(), mpi_binary_data_io::mpi_write_int_vector_b(), mpi_binary_data_io::mpi_write_one_integer_b(), and t_calypso_mpi_io_param::mul_istack_4_parallell_vect().
Referenced by mpi_sph_modes_data_io_b::mpi_write_geom_rtm_data_b(), mpi_sph_modes_data_io_b::mpi_write_geom_rtp_data_b(), mpi_sph_modes_data_io_b::mpi_write_modes_rlm_data_b(), and mpi_sph_modes_data_io_b::mpi_write_spectr_rj_data_b().
mpi_write_gl_reso_sph_b()
subroutine mpi_spherical_model_io_b::mpi_write_gl_reso_sph_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(in) sph_IO)
Definition at line 112 of file MPI_spherical_model_IO_b.f90.
References mpi_binary_head_io::mpi_write_mul_inthead_b(), and mpi_binary_head_io::mpi_write_one_inthead_b().
Referenced by mpi_sph_modes_data_io_b::mpi_write_geom_rtm_data_b(), mpi_sph_modes_data_io_b::mpi_write_geom_rtp_data_b(), mpi_sph_modes_data_io_b::mpi_write_modes_rlm_data_b(), and mpi_sph_modes_data_io_b::mpi_write_spectr_rj_data_b().
mpi_write_rank_4_sph_b()
subroutine mpi_spherical_model_io_b::mpi_write_rank_4_sph_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(in) sph_IO)
Definition at line 96 of file MPI_spherical_model_IO_b.f90.
References t_calypso_mpi_io_param::istack64_4_parallel_data(), and mpi_binary_data_io::mpi_write_int_vector_b().
Referenced by mpi_sph_modes_data_io_b::mpi_write_geom_rtm_data_b(), mpi_sph_modes_data_io_b::mpi_write_geom_rtp_data_b(), mpi_sph_modes_data_io_b::mpi_write_modes_rlm_data_b(), and mpi_sph_modes_data_io_b::mpi_write_spectr_rj_data_b().