CALYPSO: gz_mpi_edge_data_io_b Module Reference
gz_mpi_edge_data_io_b Module Reference
data IO orutines for edge
Functions/Subroutines
subroutine gz_mpi_read_edge_connect_b (IO_param, comm_IO, ele_IO, sfed_IO)
subroutine gz_mpi_write_edge_connect_b (IO_param, comm_IO, ele_IO, sfed_IO)
subroutine gz_mpi_read_edge_geometry_b (IO_param, nod_IO, sfed_IO)
subroutine gz_mpi_write_edge_geometry_b (IO_param, nod_IO, sfed_IO)
Detailed Description
data IO orutines for edge
      subroutine gz_mpi_read_edge_connect_b                           &
     &         (IO_param, comm_IO, ele_IO, sfed_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(communication_table), intent(inout) :: comm_IO
        type(element_data), intent(inout) :: ele_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
      subroutine gz_mpi_write_edge_connect_b                          &
     &         (IO_param, comm_IO, ele_IO, sfed_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(communication_table), intent(in) :: comm_IO
        type(element_data), intent(in) :: ele_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
      subroutine gz_mpi_read_edge_geometry_b                          &
     &         (IO_param, nod_IO, sfed_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(node_data), intent(inout) :: nod_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
      subroutine gz_mpi_write_edge_geometry_b                         &
     &         (IO_param, nod_IO, sfed_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(node_data), intent(in) :: nod_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
Function/Subroutine Documentation
gz_mpi_read_edge_connect_b()
subroutine gz_mpi_edge_data_io_b::gz_mpi_read_edge_connect_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(inout) comm_IO, type(element_data), intent(inout) ele_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 58 of file gz_MPI_edge_data_IO_b.f90.
References gz_mpi_domain_data_io_b::gz_mpi_read_domain_info_b(), gz_mpi_element_connect_io_b::gz_mpi_read_edge_4_element_b(), gz_mpi_element_connect_io_b::gz_mpi_read_ele_info_b(), gz_mpi_domain_data_io_b::gz_mpi_read_export_data_b(), gz_mpi_domain_data_io_b::gz_mpi_read_import_data_b(), gz_mpi_element_connect_io_b::gz_mpi_read_num_element_b(), and gz_mpi_element_connect_io_b::gz_mpi_read_surf_4_elem_b().
Referenced by gz_mpi_element_file_io_b::gz_mpi_input_edge_file_b().
gz_mpi_read_edge_geometry_b()
subroutine gz_mpi_edge_data_io_b::gz_mpi_read_edge_geometry_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 109 of file gz_MPI_edge_data_IO_b.f90.
References gz_mpi_node_geometry_io_b::gz_mpi_read_geometry_info_b(), gz_mpi_node_geometry_io_b::gz_mpi_read_number_of_node_b(), gz_mpi_node_geometry_io_b::gz_mpi_read_scl_in_ele_b(), and gz_mpi_node_geometry_io_b::gz_mpi_read_vect_in_ele_b().
gz_mpi_write_edge_connect_b()
subroutine gz_mpi_edge_data_io_b::gz_mpi_write_edge_connect_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(in) comm_IO, type(element_data), intent(in) ele_IO, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 84 of file gz_MPI_edge_data_IO_b.f90.
References gz_mpi_domain_data_io_b::gz_mpi_write_domain_info_b(), gz_mpi_element_connect_io_b::gz_mpi_write_edge_4_ele_b(), gz_mpi_element_connect_io_b::gz_mpi_write_element_info_b(), gz_mpi_domain_data_io_b::gz_mpi_write_export_data_b(), gz_mpi_domain_data_io_b::gz_mpi_write_import_data_b(), and gz_mpi_element_connect_io_b::gz_mpi_write_surf_4_ele_b().
Referenced by gz_mpi_element_file_io_b::gz_mpi_output_edge_file_b().
gz_mpi_write_edge_geometry_b()
subroutine gz_mpi_edge_data_io_b::gz_mpi_write_edge_geometry_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 128 of file gz_MPI_edge_data_IO_b.f90.
References gz_mpi_node_geometry_io_b::gz_mpi_write_geometry_info_b(), gz_mpi_node_geometry_io_b::gz_mpi_write_scl_in_ele_b(), and gz_mpi_node_geometry_io_b::gz_mpi_write_vect_in_ele_b().