CALYPSO: count_nnod_4_asseble_sph Module Reference
count_nnod_4_asseble_sph Module Reference
Count number of nodes for data assemble.
Functions/Subroutines
subroutine s_count_nnod_4_asseble_sph (np_sph_new, new_sph_mesh, new_fst_IO)
Detailed Description
Count number of nodes for data assemble.
      subroutine s_count_nnod_4_asseble_sph                           &
     &         (np_sph_new, new_sph_mesh, new_fst_IO)
        type(sph_mesh_data), intent(in) :: new_sph_mesh(np_sph_new)
        type(field_IO), intent(inout) :: new_fst_IO
Function/Subroutine Documentation
s_count_nnod_4_asseble_sph()
subroutine count_nnod_4_asseble_sph::s_count_nnod_4_asseble_sph (integer, intent(in) np_sph_new, type(sph_mesh_data), intent(in) new_sph_mesh, type(field_io), intent(inout) new_fst_IO)
Definition at line 33 of file count_nnod_4_asseble_sph.f90.
References t_field_data_io::alloc_merged_field_stack(), calypso_mpi_int::calypso_mpi_allgather_one_int(), and calypso_mpi::nprocs.
Referenced by analyzer_assemble_sph::init_assemble_sph(), analyzer_compare_sph_rst::init_compare_sph_restart(), and analyzer_rayleigh_cvt_sph::init_cvt_rayleigh_sph().