CALYPSO: schmidt_poly_on_rtm_grid Module Reference
schmidt_poly_on_rtm_grid Module Reference
Copy Legendre polynomials for spherical transform.
Functions/Subroutines
subroutine set_gauss_points_rtm (nth, leg)
subroutine, private set_gauss_colatitude_rtm (gauss, leg)
subroutine copy_sph_normalization_2_rlm (sph_rlm, g_sph_rlm)
subroutine copy_sph_normalization_2_rj (sph_rj, g_sph_rj)
subroutine set_lagender_4_rlm (l_truncation, sph_rtm, sph_rlm, idx_trns, g_colat_rtm, P_rtm, dPdt_rtm)
subroutine set_lagender_pole_rlm (l_truncation, sph_rtm, sph_rlm, idx_trns, P_pole_rtm, dPdt_pole_rtm)
Variables
type(gauss_points), private gauss_rtm
Detailed Description
Copy Legendre polynomials for spherical transform.
      subroutine set_gauss_points_rtm(nth, leg)
        type(legendre_4_sph_trans), intent(inout) :: leg
      subroutine copy_sph_normalization_2_rlm(sph_rlm, g_sph_rlm)
        type(sph_rlm_grid), intent(in) :: sph_rlm
      subroutine copy_sph_normalization_2_rj(sph_rj, g_sph_rj)
        type(sph_rj_grid), intent(in) :: sph_rj
      subroutine set_lagender_4_rlm(l_truncation, sph_rtm, sph_rlm,   &
     &          idx_trns, g_colat_rtm, P_rtm, dPdt_rtm)
      subroutine set_lagender_pole_rlm(l_truncation, sph_rtm, sph_rlm,&
     &          idx_trns, P_pole_rtm, dPdt_pole_rtm)
        integer(kind = kint), intent(in) :: l_truncation
        type(sph_rtm_grid), intent(in) :: sph_rtm
        type(sph_rlm_grid), intent(in) :: sph_rlm
        type(index_4_sph_trans), intent(in) :: idx_trns
Function/Subroutine Documentation
copy_sph_normalization_2_rj()
subroutine schmidt_poly_on_rtm_grid::copy_sph_normalization_2_rj (type(sph_rj_grid), intent(in) sph_rj, real(kind = kreal), dimension(sph_rj%nidx_rj(2),17), intent(inout) g_sph_rj)
Definition at line 117 of file schmidt_poly_on_rtm_grid.f90.
References spherical_harmonics::sph_normalizations().
Referenced by init_sph_trans::init_legendre_rtm().
copy_sph_normalization_2_rlm()
subroutine schmidt_poly_on_rtm_grid::copy_sph_normalization_2_rlm (type(sph_rlm_grid), intent(in) sph_rlm, real(kind = kreal), dimension(sph_rlm%nidx_rlm(2),17), intent(inout) g_sph_rlm)
Definition at line 89 of file schmidt_poly_on_rtm_grid.f90.
References m_constants::half, and spherical_harmonics::sph_normalizations().
Referenced by init_sph_trans::init_legendre_rtm().
set_gauss_colatitude_rtm()
subroutine, private schmidt_poly_on_rtm_grid::set_gauss_colatitude_rtm (type(gauss_points), intent(in) gauss, type(legendre_4_sph_trans), intent(inout) leg) private
Definition at line 71 of file schmidt_poly_on_rtm_grid.f90.
Referenced by set_gauss_points_rtm().
set_gauss_points_rtm()
subroutine schmidt_poly_on_rtm_grid::set_gauss_points_rtm (integer(kind = kint), intent(in) nth, type(legendre_4_sph_trans), intent(inout) leg)
Definition at line 51 of file schmidt_poly_on_rtm_grid.f90.
References t_schmidt_poly_on_rtm::alloc_gauss_colat_rtm(), t_gauss_points::const_gauss_colatitude(), t_gauss_points::dealloc_gauss_colatitude(), gauss_rtm, and set_gauss_colatitude_rtm().
Referenced by init_sph_trans::init_legendre_rtm().
set_lagender_4_rlm()
subroutine schmidt_poly_on_rtm_grid::set_lagender_4_rlm (integer(kind = kint), intent(in) l_truncation, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(index_4_sph_trans), intent(in) idx_trns, real(kind= kreal), dimension(sph_rtm%nidx_rtm(2)), intent(in) g_colat_rtm, real(kind= kreal), dimension(sph_rtm%nidx_rtm(2),sph_rlm%nidx_rlm(2)), intent(inout) P_rtm, real(kind= kreal), dimension(sph_rtm%nidx_rtm(2),sph_rlm%nidx_rlm(2)), intent(inout) dPdt_rtm)
Definition at line 145 of file schmidt_poly_on_rtm_grid.f90.
References m_machine_parameter::np_smp, and schmidt_fix_m::schmidt_legendres_m().
Referenced by init_sph_trans::init_legendre_rtm().
set_lagender_pole_rlm()
subroutine schmidt_poly_on_rtm_grid::set_lagender_pole_rlm (integer(kind = kint), intent(in) l_truncation, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(index_4_sph_trans), intent(in) idx_trns, real(kind = kreal), dimension(2,sph_rlm%nidx_rlm(2)), intent(inout) P_pole_rtm, real(kind = kreal), dimension(2,sph_rlm%nidx_rlm(2)), intent(inout) dPdt_pole_rtm)
Definition at line 201 of file schmidt_poly_on_rtm_grid.f90.
References m_constants::four, m_constants::one, schmidt_fix_m::schmidt_legendres_m(), and m_constants::zero.
Referenced by init_sph_trans::init_legendre_rtm().
Variable Documentation
gauss_rtm
type(gauss_points), private schmidt_poly_on_rtm_grid::gauss_rtm private
Definition at line 41 of file schmidt_poly_on_rtm_grid.f90.
Referenced by set_gauss_points_rtm().