CALYPSO: t_base_field_labels Module Reference
t_base_field_labels Module Reference
Data Types
type base_field_address
Structure for start address for base fields.
Functions/Subroutines
integer(kind=kint) function missing_field (iphys_tgt, target_name, iphys_ref, ref_name)
subroutine set_base_vector_addresses (i_phys, field_name, base_fld, flag)
subroutine set_base_scalar_addresses (i_phys, field_name, base_fld, flag)
Function/Subroutine Documentation
missing_field()
integer(kind = kint) function t_base_field_labels::missing_field (integer(kind = kint), intent(in) iphys_tgt, character(len = kchara), intent(in) target_name, integer(kind = kint), intent(in) iphys_ref, character(len = kchara), intent(in) ref_name)
Definition at line 165 of file t_base_field_labels.f90.
set_base_scalar_addresses()
subroutine t_base_field_labels::set_base_scalar_addresses (integer(kind = kint), intent(in) i_phys, character(len = kchara), intent(in) field_name, type(base_field_address), intent(inout) base_fld, logical, intent(inout) flag)
Definition at line 220 of file t_base_field_labels.f90.
References m_base_field_labels::check_base_scalar(), m_base_field_labels::composition, m_base_field_labels::composition_source, m_base_field_labels::density, m_base_field_labels::entropy, m_base_field_labels::entropy_source, m_base_field_labels::heat_source, m_base_field_labels::magnetic_potential, m_base_field_labels::perturbation_composition, m_base_field_labels::perturbation_density, m_base_field_labels::perturbation_entropy, m_base_field_labels::perturbation_temp, m_base_field_labels::pressure, m_base_field_labels::reference_composition, m_base_field_labels::reference_density, m_base_field_labels::reference_entropy, m_base_field_labels::reference_temperature, m_base_field_labels::scalar_potential, and m_base_field_labels::temperature.
Referenced by set_mhd_field_address::set_mhd_field_addresses().
set_base_vector_addresses()
subroutine t_base_field_labels::set_base_vector_addresses (integer(kind = kint), intent(in) i_phys, character(len = kchara), intent(in) field_name, type(base_field_address), intent(inout) base_fld, logical, intent(inout) flag)
Definition at line 183 of file t_base_field_labels.f90.
References m_base_field_labels::background_b, m_base_field_labels::check_base_vector(), m_base_field_labels::current_density, m_base_field_labels::magnetic_field, m_base_field_labels::system_rotation, m_base_field_labels::vector_potential, m_base_field_labels::velocity, and m_base_field_labels::vorticity.
Referenced by set_mhd_field_address::set_mhd_field_addresses().