CALYPSO: para_const_kemoview_mesh Module Reference
para_const_kemoview_mesh Module Reference
Surface mesh data generator for kemoviewer.
Data Types
type parallel_make_vierwer_mesh
Functions/Subroutines
subroutine pickup_surface_mesh (mesh_file, par_v)
subroutine collect_surf_mesh_4_viewer (mesh_file, mgd_v_mesh)
Variables
integer(kind=kint), private iflag_add_comm_tbl = 1
integer(kind=kint), parameter, private iflag_write_subdomain = 0
Detailed Description
Surface mesh data generator for kemoviewer.
      subroutine pickup_surface_mesh(mesh_file, par_v)
        type(field_IO_params), intent(inout) :: mesh_file
        type(parallel_make_vierwer_mesh), intent(inout) :: par_v
Function/Subroutine Documentation
collect_surf_mesh_4_viewer()
subroutine para_const_kemoview_mesh::collect_surf_mesh_4_viewer (type(field_io_params), intent(in) mesh_file, type(merged_viewer_mesh), intent(inout) mgd_v_mesh)
Definition at line 103 of file para_const_kemoview_mesh.f90.
References t_merged_viewer_mesh::alloc_mpi_viewer_mesh_param(), const_global_element_ids::count_number_of_node_stack4(), t_merged_viewer_mesh::dealloc_mpi_viewer_mesh_param(), calypso_mpi::my_rank, calypso_mpi::nprocs, renumber_para_viewer_mesh::s_renumber_para_viewer_mesh(), and viewer_mesh_mpi_io_select::sel_mpi_output_surface_grid().
Referenced by pickup_surface_mesh().
pickup_surface_mesh()
subroutine para_const_kemoview_mesh::pickup_surface_mesh (type(field_io_params), intent(in) mesh_file, type(parallel_make_vierwer_mesh), intent(inout) par_v)
Definition at line 47 of file para_const_kemoview_mesh.f90.
References add_comm_table_in_node_grp::add_comm_tbl_in_node_grp_mesh(), m_node_quad_2_linear_sf::allocate_quad4_2_linear(), collect_surf_mesh_4_viewer(), const_kemoview_mesh::const_surf_mesh_4_viewer(), t_mesh_data::dealloc_mesh_infos(), m_node_quad_2_linear_sf::deallocate_quad4_2_linear(), iflag_add_comm_tbl, m_machine_parameter::iflag_debug, iflag_write_subdomain, mpi_load_mesh_data::mpi_input_mesh(), calypso_mpi::my_rank, calypso_mpi::nprocs, and viewer_file_io::sel_output_single_surface_grid().
Referenced by analyzer_gen_sph_grids::analyze_gen_sph_grids().
Variable Documentation
iflag_add_comm_tbl
integer(kind = kint), private para_const_kemoview_mesh::iflag_add_comm_tbl = 1 private
Definition at line 30 of file para_const_kemoview_mesh.f90.
Referenced by pickup_surface_mesh().
iflag_write_subdomain
integer(kind = kint), parameter, private para_const_kemoview_mesh::iflag_write_subdomain = 0 private
Definition at line 31 of file para_const_kemoview_mesh.f90.
Referenced by pickup_surface_mesh().