CALYPSO: mesh_file_name_by_param Module Reference
mesh_file_name_by_param Module Reference
Choose mesh file to read.
Functions/Subroutines
logical function check_exist_mesh (mesh_file, id_rank)
logical function check_exist_ele_mesh (mesh_file, id_rank)
logical function check_exist_surf_mesh (mesh_file, id_rank)
logical function check_exist_edge_mesh (mesh_file, id_rank)
Detailed Description
Choose mesh file to read.
      logical function check_exist_mesh(mesh_file, id_rank)
      logical function check_exist_ele_mesh(mesh_file, id_rank)
      logical function check_exist_surf_mesh(mesh_file, id_rank)
      logical function check_exist_edge_mesh(mesh_file, id_rank)
Function/Subroutine Documentation
check_exist_edge_mesh()
logical function mesh_file_name_by_param::check_exist_edge_mesh (type(field_io_params), intent(in) mesh_file, integer, intent(in) id_rank)
Definition at line 94 of file mesh_file_name_by_param.f90.
References delete_data_files::check_file_exist(), and set_mesh_file_names::set_edge_mesh_file_name().
check_exist_ele_mesh()
logical function mesh_file_name_by_param::check_exist_ele_mesh (type(field_io_params), intent(in) mesh_file, integer, intent(in) id_rank)
Definition at line 52 of file mesh_file_name_by_param.f90.
References delete_data_files::check_file_exist(), and set_mesh_file_names::set_ele_comm_file_name().
check_exist_mesh()
logical function mesh_file_name_by_param::check_exist_mesh (type(field_io_params), intent(in) mesh_file, integer, intent(in) id_rank)
Definition at line 31 of file mesh_file_name_by_param.f90.
References delete_data_files::check_file_exist(), and set_mesh_file_names::set_mesh_file_name().
Referenced by t_check_and_make_sph_mesh::load_para_sph_and_fem_mesh().
check_exist_surf_mesh()
logical function mesh_file_name_by_param::check_exist_surf_mesh (type(field_io_params), intent(in) mesh_file, integer, intent(in) id_rank)
Definition at line 73 of file mesh_file_name_by_param.f90.
References delete_data_files::check_file_exist(), and set_mesh_file_names::set_surf_mesh_file_name().