CALYPSO: shader_into_c_source Module Reference
shader_into_c_source Module Reference
Functions/Subroutines
subroutine getarg_k (i, argc)
integer function iargc_kemo ()
subroutine set_shader_name (shader_file, shader_name)
subroutine set_load_shader_name (shader_name, func_name)
subroutine append_each_shader (dirname, shader_file, c_prefix)
Function/Subroutine Documentation
append_each_shader()
subroutine shader_into_c_source::append_each_shader (character(len=1024), intent(in) dirname, character(len=255), intent(in) shader_file, character(len=255), intent(in) c_prefix)
Definition at line 85 of file shader_into_c.f90.
References set_load_shader_name(), and set_shader_name().
Referenced by shader_into_c().
getarg_k()
subroutine shader_into_c_source::getarg_k (integer, intent(in) i, character(len=*), intent(out) argc)
Definition at line 12 of file shader_into_c.f90.
Referenced by shader_into_c().
iargc_kemo()
integer function shader_into_c_source::iargc_kemo
Definition at line 27 of file shader_into_c.f90.
Referenced by shader_into_c().
set_load_shader_name()
subroutine shader_into_c_source::set_load_shader_name (character(len=512), intent(in) shader_name, character(len=512), intent(inout) func_name)
Definition at line 64 of file shader_into_c.f90.
Referenced by append_each_shader().
set_shader_name()
subroutine shader_into_c_source::set_shader_name (character(len=255), intent(in) shader_file, character(len=512), intent(inout) shader_name)
Definition at line 41 of file shader_into_c.f90.
Referenced by append_each_shader().