CALYPSO: t_viz_sections Module Reference
t_viz_sections Module Reference
Top routine for sectiong.
Data Types
type surfacing_modules
Structure of sectioning and isosurfaceing modules.
Functions/Subroutines
subroutine init_visualize_surface (fem, nod_fld, surfacing_ctls, viz_psfs)
subroutine visualize_surface (viz_step, time_d, fem, nod_fld, viz_psfs)
Detailed Description
Top routine for sectiong.
      subroutine init_visualize_surface                               &
     &         (fem, nod_fld, surfacing_ctls, viz_psfs)
      subroutine visualize_surface                                    &
     &        (viz_step, time_d, fem, nod_fld, viz_psfs)
        type(VIZ_step_params), intent(in) :: viz_step
        type(time_data), intent(in) :: time_d
        type(mesh_data), intent(in) :: fem
        type(phys_data), intent(in) :: nod_fld
        type(surfacing_controls), intent(inout) :: surfacing_ctls
        type(surfacing_modules), intent(inout) :: viz_psfs
Function/Subroutine Documentation
init_visualize_surface()
subroutine t_viz_sections::init_visualize_surface (type(mesh_data), intent(in) fem, type(phys_data), intent(in) nod_fld, type(surfacing_controls), intent(inout) surfacing_ctls, type(surfacing_modules), intent(inout) viz_psfs)
Definition at line 55 of file t_viz_sections.f90.
References t_control_data_surfacings::dealloc_surfacing_controls(), m_work_time::end_elapsed_time(), m_elapsed_labels_4_viz::iflag_viz_time, t_isosurface::isosurf_initialize(), m_elapsed_labels_4_viz::ist_elapsed_viz, t_cross_section::sectioning_initialize(), and m_work_time::start_elapsed_time().
Referenced by analyzer_psf::init_analyzer_psf(), analyzer_sph_mhd_w_psf::initialize_sph_mhd_w_psf(), and analyzer_sph_snap_w_psf::initialize_sph_snap_w_psf().
visualize_surface()
subroutine t_viz_sections::visualize_surface (type(viz_step_params), intent(in) viz_step, type(time_data), intent(in) time_d, type(mesh_data), intent(in) fem, type(phys_data), intent(in) nod_fld, type(surfacing_modules), intent(inout) viz_psfs)
Definition at line 83 of file t_viz_sections.f90.
References m_work_time::end_elapsed_time(), m_elapsed_labels_4_viz::iflag_viz_time, t_isosurface::isosurf_visualize(), m_elapsed_labels_4_viz::ist_elapsed_viz, t_cross_section::sectioning_visualize(), and m_work_time::start_elapsed_time().
Referenced by analyzer_psf::analyze_psf(), analyzer_sph_mhd_w_psf::evolution_sph_mhd_w_psf(), and analyzer_sph_snap_w_psf::evolution_sph_snap_w_psf().