CALYPSO: leg_fwd_trans_on_the_fly Module Reference
leg_fwd_trans_on_the_fly Module Reference
forward Legendre transform (Blocked loop version)
Functions/Subroutines
subroutine legendre_f_trans_on_the_fly (iflag_matmul, ncomp, nvector, nscalar, sph_rtm, sph_rlm, comm_rtm, comm_rlm, leg, idx_trns, n_WR, n_WS, WR, WS, WK_l_otf)
subroutine, private leg_fwd_trans_8latitude (lt2, jst, mm, mp_rlm, mn_rlm, nkrs, nkrt, iflag_matmul, ncomp, nvector, nscalar, sph_rtm, sph_rlm, comm_rtm, leg, n_WR, WR, n_jk_e, n_jk_o, lst_rtm, Fmat, Ptj_mat, Smat, wk_plm)
subroutine, private leg_fwd_trans_4latitude (lt2, jst, mm, mp_rlm, mn_rlm, nkrs, nkrt, iflag_matmul, ncomp, nvector, nscalar, sph_rtm, sph_rlm, comm_rtm, leg, n_WR, WR, n_jk_e, n_jk_o, lst_rtm, Fmat, Ptj_mat, Smat, wk_plm)
subroutine, private leg_fwd_trans_2latitude (lt2, jst, mm, mp_rlm, mn_rlm, nkrs, nkrt, iflag_matmul, ncomp, nvector, nscalar, sph_rtm, sph_rlm, comm_rtm, leg, n_WR, WR, n_jk_e, n_jk_o, lst_rtm, Fmat, Ptj_mat, Smat, wk_plm)
subroutine, private leg_fwd_trans_1latitude (lp_rtm, ln_rtm, jst, mm, mp_rlm, mn_rlm, nkrs, nkrt, iflag_matmul, ncomp, nvector, nscalar, sph_rtm, sph_rlm, comm_rtm, leg, n_WR, WR, n_jk_e, n_jk_o, Fmat, Pjt_mat, Smat, wk_plm)
subroutine, private leg_fwd_trans_at_equator (lp_rtm, jst, mm, mp_rlm, mn_rlm, nkrs, nkrt, iflag_matmul, ncomp, nvector, nscalar, sph_rtm, sph_rlm, comm_rtm, leg, n_WR, WR, n_jk_e, n_jk_o, Fmat, Pjt_mat, Smat, wk_plm)
subroutine sum_spectr_over_smp_in (nkrs, nkrt, n_jk_e, n_jk_o, Smat)
subroutine sum_spectr_over_smp_krin (nkrs, nkrt, n_jk_e, n_jk_o, Smat)
subroutine sum_spectr_over_smp_out (nkrs, nkrt, n_jk_e, n_jk_o, Smat)
Variables
integer, external omp_get_max_threads
Detailed Description
forward Legendre transform (Blocked loop version)
      subroutine legendre_f_trans_on_the_fly                          &
     &         (iflag_matmul, ncomp, nvector, nscalar,                &
     &          sph_rtm, sph_rlm, comm_rtm, comm_rlm, leg, idx_trns,  &
     &          n_WR, n_WS, WR, WS, WK_l_otf)
        Input:  vr_rtm   (Order: radius,theta,phi)
        Output: sp_rlm   (Order: poloidal,diff_poloidal,toroidal)
        type(sph_rlm_grid), intent(in) :: sph_rlm
        type(sph_rtm_grid), intent(in) :: sph_rtm
        type(sph_comm_tbl), intent(in) :: comm_rlm, comm_rtm
        type(index_4_sph_trans), intent(in) :: idx_trns
        type(leg_trns_on_the_fly_work), intent(inout) :: WK_l_otf
Parameters
ncomp Total number of components for spherical transform
nvector Number of vector for spherical transform
nscalar Number of scalar (including tensor components) for spherical transform
Function/Subroutine Documentation
leg_fwd_trans_1latitude()
subroutine, private leg_fwd_trans_on_the_fly::leg_fwd_trans_1latitude (integer(kind = kint), intent(in) lp_rtm, integer(kind = kint), intent(in) ln_rtm, integer(kind = kint), intent(in) jst, integer(kind = kint), intent(in) mm, integer(kind = kint), intent(in) mp_rlm, integer(kind = kint), intent(in) mn_rlm, integer(kind = kint), intent(in) nkrs, integer(kind = kint), intent(in) nkrt, integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_comm_tbl), intent(in) comm_rtm, type(legendre_4_sph_trans), intent(in) leg, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(inout) WR, integer(kind = kint), intent(in) n_jk_e, integer(kind = kint), intent(in) n_jk_o, type(field_matrix_omp), intent(inout) Fmat, type(leg_jt_omp_matrix), intent(inout) Pjt_mat, type(spectr_matrix_omp), intent(inout) Smat, type(work_make_legendre), intent(inout) wk_plm) private
Definition at line 473 of file leg_fwd_trans_on_the_fly.f90.
References small_matmul_leg_trans_krin::matvec_fwd_leg_trans_pj(), t_set_legendre_4_sph_trans::set_each_sym_leg_omp_mat_j1(), and set_vr_rtm_sym_mat_tsmp::set_vr_rtm_lt_sym_mat_rin().
Referenced by legendre_f_trans_on_the_fly().
leg_fwd_trans_2latitude()
subroutine, private leg_fwd_trans_on_the_fly::leg_fwd_trans_2latitude (integer(kind = kint), intent(in) lt2, integer(kind = kint), intent(in) jst, integer(kind = kint), intent(in) mm, integer(kind = kint), intent(in) mp_rlm, integer(kind = kint), intent(in) mn_rlm, integer(kind = kint), intent(in) nkrs, integer(kind = kint), intent(in) nkrt, integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_comm_tbl), intent(in) comm_rtm, type(legendre_4_sph_trans), intent(in) leg, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(inout) WR, integer(kind = kint), intent(in) n_jk_e, integer(kind = kint), intent(in) n_jk_o, integer(kind = kint), intent(in) lst_rtm, type(field_matrix_omp), intent(inout) Fmat, type(leg_tj_omp_matrix), intent(inout) Ptj_mat, type(spectr_matrix_omp), intent(inout) Smat, type(work_make_legendre), intent(inout) wk_plm) private
Definition at line 389 of file leg_fwd_trans_on_the_fly.f90.
References small_matmul_leg_trans_krin::matmul2_fwd_leg_trans_ptj(), t_legendre_work_on_the_fly::n_sse2, t_set_legendre_4_sph_trans::set_each_sym_leg_omp_mat_tj(), and set_vr_rtm_sym_mat_tsmp::set_vr_rtm_lt_sym_mat_rin().
Referenced by legendre_f_trans_on_the_fly().
leg_fwd_trans_4latitude()
subroutine, private leg_fwd_trans_on_the_fly::leg_fwd_trans_4latitude (integer(kind = kint), intent(in) lt2, integer(kind = kint), intent(in) jst, integer(kind = kint), intent(in) mm, integer(kind = kint), intent(in) mp_rlm, integer(kind = kint), intent(in) mn_rlm, integer(kind = kint), intent(in) nkrs, integer(kind = kint), intent(in) nkrt, integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_comm_tbl), intent(in) comm_rtm, type(legendre_4_sph_trans), intent(in) leg, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(inout) WR, integer(kind = kint), intent(in) n_jk_e, integer(kind = kint), intent(in) n_jk_o, integer(kind = kint), intent(in) lst_rtm, type(field_matrix_omp), intent(inout) Fmat, type(leg_tj_omp_matrix), intent(inout) Ptj_mat, type(spectr_matrix_omp), intent(inout) Smat, type(work_make_legendre), intent(inout) wk_plm) private
Definition at line 305 of file leg_fwd_trans_on_the_fly.f90.
References small_matmul_leg_trans_krin::matmul4_fwd_leg_trans_ptj(), t_legendre_work_on_the_fly::n_avx, t_set_legendre_4_sph_trans::set_each_sym_leg_omp_mat_tj(), and set_vr_rtm_sym_mat_tsmp::set_vr_rtm_lt_sym_mat_rin().
Referenced by legendre_f_trans_on_the_fly().
leg_fwd_trans_8latitude()
subroutine, private leg_fwd_trans_on_the_fly::leg_fwd_trans_8latitude (integer(kind = kint), intent(in) lt2, integer(kind = kint), intent(in) jst, integer(kind = kint), intent(in) mm, integer(kind = kint), intent(in) mp_rlm, integer(kind = kint), intent(in) mn_rlm, integer(kind = kint), intent(in) nkrs, integer(kind = kint), intent(in) nkrt, integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_comm_tbl), intent(in) comm_rtm, type(legendre_4_sph_trans), intent(in) leg, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(inout) WR, integer(kind = kint), intent(in) n_jk_e, integer(kind = kint), intent(in) n_jk_o, integer(kind = kint), intent(in) lst_rtm, type(field_matrix_omp), intent(inout) Fmat, type(leg_tj_omp_matrix), intent(inout) Ptj_mat, type(spectr_matrix_omp), intent(inout) Smat, type(work_make_legendre), intent(inout) wk_plm) private
Definition at line 220 of file leg_fwd_trans_on_the_fly.f90.
References small_matmul_leg_trans_krin::matmul8_fwd_leg_trans_ptj(), t_legendre_work_on_the_fly::n_avx512, t_set_legendre_4_sph_trans::set_each_sym_leg_omp_mat_tj(), and set_vr_rtm_sym_mat_tsmp::set_vr_rtm_lt_sym_mat_rin().
Referenced by legendre_f_trans_on_the_fly().
leg_fwd_trans_at_equator()
subroutine, private leg_fwd_trans_on_the_fly::leg_fwd_trans_at_equator (integer(kind = kint), intent(in) lp_rtm, integer(kind = kint), intent(in) jst, integer(kind = kint), intent(in) mm, integer(kind = kint), intent(in) mp_rlm, integer(kind = kint), intent(in) mn_rlm, integer(kind = kint), intent(in) nkrs, integer(kind = kint), intent(in) nkrt, integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_comm_tbl), intent(in) comm_rtm, type(legendre_4_sph_trans), intent(in) leg, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(inout) WR, integer(kind = kint), intent(in) n_jk_e, integer(kind = kint), intent(in) n_jk_o, type(field_matrix_omp), intent(inout) Fmat, type(leg_jt_omp_matrix), intent(inout) Pjt_mat, type(spectr_matrix_omp), intent(inout) Smat, type(work_make_legendre), intent(inout) wk_plm) private
Definition at line 547 of file leg_fwd_trans_on_the_fly.f90.
References small_matmul_leg_trans_krin::matvec_fwd_leg_trans_pj(), t_set_legendre_4_sph_trans::set_each_sym_leg_omp_mat_j1(), and set_vr_rtm_sym_mat_tsmp::set_vr_rtm_eq_sym_mat_rin().
Referenced by legendre_f_trans_on_the_fly().
legendre_f_trans_on_the_fly()
subroutine leg_fwd_trans_on_the_fly::legendre_f_trans_on_the_fly (integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_comm_tbl), intent(in) comm_rtm, type(sph_comm_tbl), intent(in) comm_rlm, type(legendre_4_sph_trans), intent(in) leg, type(index_4_sph_trans), intent(in) idx_trns, integer(kind = kint), intent(in) n_WR, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_wr), intent(inout) WR, real (kind=kreal), dimension(n_ws), intent(inout) WS, type(leg_trns_on_the_fly_work), intent(inout) WK_l_otf)
Definition at line 63 of file leg_fwd_trans_on_the_fly.f90.
References cal_sp_rlm_sym_mat_tsmp::cal_sp_rlm_sym_mat_rin(), m_work_time::elps1, m_work_time::end_elapsed_time(), m_elapsed_labels_sph_trns::iflag_sdt_time, m_elapsed_labels_sph_trns::ist_elapsed_sdt, leg_fwd_trans_1latitude(), leg_fwd_trans_2latitude(), leg_fwd_trans_4latitude(), leg_fwd_trans_8latitude(), leg_fwd_trans_at_equator(), m_machine_parameter::np_smp, m_work_time::start_elapsed_time(), and sum_spectr_over_smp_segment::sum_spectr_over_kr_in().
Referenced by t_legendre_trans_select::sel_forward_legendre_trans().
sum_spectr_over_smp_in()
subroutine leg_fwd_trans_on_the_fly::sum_spectr_over_smp_in (integer(kind = kint), intent(in) nkrs, integer(kind = kint), intent(in) nkrt, integer(kind = kint), intent(in) n_jk_e, integer(kind = kint), intent(in) n_jk_o, type(spectr_matrix_omp), dimension(np_smp), intent(inout) Smat)
Definition at line 623 of file leg_fwd_trans_on_the_fly.f90.
sum_spectr_over_smp_krin()
subroutine leg_fwd_trans_on_the_fly::sum_spectr_over_smp_krin (integer(kind = kint), intent(in) nkrs, integer(kind = kint), intent(in) nkrt, integer(kind = kint), intent(in) n_jk_e, integer(kind = kint), intent(in) n_jk_o, type(spectr_matrix_omp), dimension(np_smp), intent(inout) Smat)
Definition at line 668 of file leg_fwd_trans_on_the_fly.f90.
sum_spectr_over_smp_out()
subroutine leg_fwd_trans_on_the_fly::sum_spectr_over_smp_out (integer(kind = kint), intent(in) nkrs, integer(kind = kint), intent(in) nkrt, integer(kind = kint), intent(in) n_jk_e, integer(kind = kint), intent(in) n_jk_o, type(spectr_matrix_omp), dimension(np_smp), intent(inout) Smat)
Definition at line 725 of file leg_fwd_trans_on_the_fly.f90.
Variable Documentation
omp_get_max_threads
integer, external leg_fwd_trans_on_the_fly::omp_get_max_threads
Definition at line 51 of file leg_fwd_trans_on_the_fly.f90.