CALYPSO: m_sel_spherical_srs Module Reference
m_sel_spherical_srs Module Reference
Data communication selector for spherical transform.
Functions/Subroutines
subroutine set_import_table_ctl (import_ctl)
subroutine check_calypso_sph_buf_n (NB, npe_send, istack_send, npe_recv, istack_recv)
subroutine sel_calypso_sph_comm_n (NB, npe_send, isend_self, id_pe_send, istack_send, npe_recv, irecv_self, id_pe_recv, istack_recv)
subroutine sel_calypso_to_send_n (NB, nnod_org, n_WS, npe_send, istack_send, inod_export, X_org, WS)
subroutine sel_calypso_to_send_vector (NB, nnod_org, n_WS, npe_send, istack_send, inod_export, ncomp_X, i_fld_X, i_fld_WS, d_org, WS)
subroutine sel_calypso_to_send_scalar (NB, nnod_org, n_WS, npe_send, istack_send, inod_export, ncomp_X, i_fld_X, i_fld_WS, d_org, WS)
subroutine sel_calypso_to_send_tensor (NB, nnod_org, n_WS, npe_send, istack_send, inod_export, ncomp_X, i_fld_X, i_fld_WS, d_org, WS)
subroutine sel_sph_vector_from_recv (NB, nnod_new, n_WR, npe_recv, istack_recv, inod_import, irev_import, ncomp_X, i_fld_X, i_fld_WR, WR, d_new)
subroutine sel_sph_scalar_from_recv (NB, nnod_new, n_WR, npe_recv, istack_recv, inod_import, irev_import, ncomp_X, i_fld_X, i_fld_WR, WR, d_new)
subroutine sel_sph_tensor_from_recv (NB, nnod_new, n_WR, npe_recv, istack_recv, inod_import, irev_import, ncomp_X, i_fld_X, i_fld_WR, WR, d_new)
subroutine sel_calypso_from_recv_n (NB, nnod_new, n_WR, npe_recv, istack_recv, inod_import, irev_import, WR, X_new)
Variables
character(len=kchara), parameter hd_import_item = 'regular_table'
Character flag to use import table.
character(len=kchara), parameter hd_import_rev = 'reversed_table'
Character flag to use reverse import table.
integer(kind=kint) iflag_sph_srn = iflag_import_UNDEFINED
Data communication mode for arbitrary size data.
integer(kind=kint) iflag_sph_sr6 = iflag_import_item
Data communication mode for six components data.
integer(kind=kint) iflag_sph_sr3 = iflag_import_item
Data communication mode for vector.
integer(kind=kint) iflag_sph_sr2 = iflag_import_item
Data communication mode for soleinoidal vection.
integer(kind=kint) iflag_sph_sr = iflag_import_item
Data communication mode for scalar.
integer(kind=kint) iflag_sph_sr_int = iflag_import_item
Data communication mode for integer.
Detailed Description
Data communication selector for spherical transform.
      subroutine set_import_table_ctl(import_ctl)
      subroutine check_calypso_sph_buf_N                              &
     &         (NB, npe_send, istack_send, npe_recv, istack_recv)
      subroutine sel_calypso_sph_comm_N            ,                  &
     &             (NB, npe_send, isend_self, id_pe_send, istack_send,&
     &                  npe_recv, irecv_self, id_pe_recv, istack_recv)
      subroutine sel_calypso_to_send_N(NB, nnod_org, n_WS, nmax_sr,   &
     &                    npe_send, istack_send, inod_export,         &
     &                    X_org, WS)
      subroutine sel_calypso_to_send_vector(NB, nnod_org, n_WS,       &
     &                    nmax_sr, npe_send, istack_send, inod_export,&
     &                    ncomp_X, i_fld_X, i_fld_WS, d_org, WS)
      subroutine sel_calypso_to_send_scalar(NB, nnod_org, n_WS,       &
     &                    npe_send, istack_send, inod_export,         &
     &                    ncomp_X, i_fld_X, i_fld_WS, d_org, WS)
      subroutine sel_calypso_to_send_tensor(NB, nnod_org, n_WS,       &
     &                    npe_send, istack_send, inod_export,         &
     &                    ncomp_X, i_fld_X, i_fld_WS, d_org, WS)
      subroutine sel_sph_vector_from_recv(NB, nnod_new, n_WR,         &
     &                    npe_recv, istack_recv, inod_import,         &
     &                    irev_import, ncomp_X, i_fld_X, i_fld_WR,    &
     &                    WR, d_new)
      subroutine sel_sph_scalar_from_recv(NB, nnod_new, n_WR,         &
     &                    npe_recv, istack_recv, inod_import,         &
     &                    irev_import, ncomp_X, i_fld_X, i_fld_WR,    &
     &                    WR, d_new)
      subroutine sel_sph_tensor_from_recv(NB, nnod_new, n_WR,         &
     &                    npe_recv, istack_recv, inod_import,         &
     &                    irev_import, ncomp_X, i_fld_X, i_fld_WR,    &
     &                    WR, d_new)
      subroutine sel_calypso_from_recv_N(NB, nnod_new, n_WR,          &
     &                    npe_recv, istack_recv, inod_import,         &
     &                    irev_import, WR, X_new)
Function/Subroutine Documentation
check_calypso_sph_buf_n()
subroutine m_sel_spherical_srs::check_calypso_sph_buf_n (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) npe_send, integer(kind = kint), dimension(0:npe_send), intent(in) istack_send, integer(kind = kint), intent(in) npe_recv, integer(kind = kint), dimension(0:npe_recv), intent(in) istack_recv)
Definition at line 109 of file m_sel_spherical_SRs.f90.
References m_solver_sr::resize_work_4_sr().
Referenced by spherical_srs_n::check_calypso_sph_comm_buf_n().
sel_calypso_from_recv_n()
subroutine m_sel_spherical_srs::sel_calypso_from_recv_n (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) n_WR, integer(kind = kint), intent(in) npe_recv, integer(kind = kint), dimension(0:npe_recv), intent(in) istack_recv, integer(kind = kint), dimension(istack_recv(npe_recv)), intent(in) inod_import, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, real (kind=kreal), dimension(n_wr), intent(inout) WR, real (kind=kreal), dimension(nb*nnod_new), intent(inout) X_new)
Definition at line 381 of file m_sel_spherical_SRs.f90.
References m_work_time::end_elapsed_time(), m_elapsed_labels_send_recv::iflag_csr_time, select_copy_from_recv::iflag_import_item, iflag_sph_srn, m_elapsed_labels_send_recv::ist_elapsed_csr, set_from_recv_buffer::set_from_recv_buf_n(), set_from_recv_buf_rev::set_from_recv_buf_rev_n(), and m_work_time::start_elapsed_time().
Referenced by spherical_srs_n::calypso_sph_from_recv_n().
sel_calypso_sph_comm_n()
subroutine m_sel_spherical_srs::sel_calypso_sph_comm_n (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) npe_send, integer(kind = kint), intent(in) isend_self, integer(kind = kint), dimension(npe_send), intent(in) id_pe_send, integer(kind = kint), dimension(0:npe_send), intent(in) istack_send, integer(kind = kint), intent(in) npe_recv, integer(kind = kint), intent(in) irecv_self, integer(kind = kint), dimension(npe_recv), intent(in) id_pe_recv, integer(kind = kint), dimension(0:npe_recv), intent(in) istack_recv)
Definition at line 131 of file m_sel_spherical_SRs.f90.
References calypso_sr_core::calypso_send_recv_core(), set_from_recv_buf_rev::clear_addtional_sr_recv(), m_work_time::end_elapsed_time(), m_elapsed_labels_send_recv::iflag_csr_time, m_elapsed_labels_send_recv::ist_elapsed_csr, m_work_time::start_elapsed_time(), and m_solver_sr::wr.
Referenced by spherical_srs_n::calypso_sph_comm_n().
sel_calypso_to_send_n()
subroutine m_sel_spherical_srs::sel_calypso_to_send_n (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) n_WS, integer(kind = kint), intent(in) npe_send, integer(kind = kint), dimension(0:npe_send), intent(in) istack_send, integer(kind = kint), dimension(istack_send(npe_send)), intent(in) inod_export, real (kind=kreal), dimension(nb*nnod_org), intent(in) X_org, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 161 of file m_sel_spherical_SRs.f90.
References m_work_time::end_elapsed_time(), m_elapsed_labels_send_recv::iflag_csr_time, m_elapsed_labels_send_recv::ist_elapsed_csr, set_to_send_buffer::set_to_send_buf_n(), and m_work_time::start_elapsed_time().
sel_calypso_to_send_scalar()
subroutine m_sel_spherical_srs::sel_calypso_to_send_scalar (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) n_WS, integer(kind = kint), intent(in) npe_send, integer(kind = kint), dimension(0:npe_send), intent(in) istack_send, integer(kind = kint), dimension(istack_send(npe_send)), intent(in) inod_export, integer(kind = kint), intent(in) ncomp_X, integer(kind = kint), intent(in) i_fld_X, integer(kind = kint), intent(in) i_fld_WS, real (kind=kreal), dimension(nnod_org,nb), intent(in) d_org, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 215 of file m_sel_spherical_SRs.f90.
References m_work_time::end_elapsed_time(), m_elapsed_labels_send_recv::iflag_csr_time, m_elapsed_labels_send_recv::ist_elapsed_csr, field_to_send_buffer::set_to_send_buf_scalar(), and m_work_time::start_elapsed_time().
Referenced by t_coriolis_terms_rlm::copy_coriolis_terms_rlm(), copy_spectr_4_sph_trans::sel_sph_rj_scalar_2_send_wpole(), and copy_spectr_4_sph_trans::sel_sph_rj_scalar_to_send().
sel_calypso_to_send_tensor()
subroutine m_sel_spherical_srs::sel_calypso_to_send_tensor (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) n_WS, integer(kind = kint), intent(in) npe_send, integer(kind = kint), dimension(0:npe_send), intent(in) istack_send, integer(kind = kint), dimension(istack_send(npe_send)), intent(in) inod_export, integer(kind = kint), intent(in) ncomp_X, integer(kind = kint), intent(in) i_fld_X, integer(kind = kint), intent(in) i_fld_WS, real (kind=kreal), dimension(nnod_org,nb), intent(in) d_org, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 243 of file m_sel_spherical_SRs.f90.
References m_work_time::end_elapsed_time(), m_elapsed_labels_send_recv::iflag_csr_time, m_elapsed_labels_send_recv::ist_elapsed_csr, field_to_send_buffer::set_to_send_buf_tensor(), and m_work_time::start_elapsed_time().
Referenced by copy_spectr_4_sph_trans::sel_sph_rj_tensor_to_send().
sel_calypso_to_send_vector()
subroutine m_sel_spherical_srs::sel_calypso_to_send_vector (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) n_WS, integer(kind = kint), intent(in) npe_send, integer(kind = kint), dimension(0:npe_send), intent(in) istack_send, integer(kind = kint), dimension(istack_send(npe_send)), intent(in) inod_export, integer(kind = kint), intent(in) ncomp_X, integer(kind = kint), intent(in) i_fld_X, integer(kind = kint), intent(in) i_fld_WS, real (kind=kreal), dimension(nnod_org,nb), intent(in) d_org, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 187 of file m_sel_spherical_SRs.f90.
References m_work_time::end_elapsed_time(), m_elapsed_labels_send_recv::iflag_csr_time, m_elapsed_labels_send_recv::ist_elapsed_csr, field_to_send_buffer::set_to_send_buf_vector(), and m_work_time::start_elapsed_time().
Referenced by copy_spectr_4_sph_trans::sel_sph_rj_vector_to_send().
sel_sph_scalar_from_recv()
subroutine m_sel_spherical_srs::sel_sph_scalar_from_recv (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) n_WR, integer(kind = kint), intent(in) npe_recv, integer(kind = kint), dimension(0:npe_recv), intent(in) istack_recv, integer(kind = kint), dimension(istack_recv(npe_recv)), intent(in) inod_import, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, integer(kind = kint), intent(in) ncomp_X, integer(kind = kint), intent(in) i_fld_X, integer(kind = kint), intent(in) i_fld_WR, real (kind=kreal), dimension(n_wr), intent(inout) WR, real (kind=kreal), dimension(nnod_new,ncomp_x), intent(inout) d_new)
Definition at line 308 of file m_sel_spherical_SRs.f90.
References m_work_time::end_elapsed_time(), m_elapsed_labels_send_recv::iflag_csr_time, select_copy_from_recv::iflag_import_item, iflag_sph_srn, m_elapsed_labels_send_recv::ist_elapsed_csr, field_to_send_buffer::set_from_recv_buf_rev_scalar(), field_to_send_buffer::set_from_recv_buf_scalar(), and m_work_time::start_elapsed_time().
Referenced by copy_spectr_4_sph_trans::sel_sph_rj_scalar_from_recv().
sel_sph_tensor_from_recv()
subroutine m_sel_spherical_srs::sel_sph_tensor_from_recv (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) n_WR, integer(kind = kint), intent(in) npe_recv, integer(kind = kint), dimension(0:npe_recv), intent(in) istack_recv, integer(kind = kint), dimension(istack_recv(npe_recv)), intent(in) inod_import, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, integer(kind = kint), intent(in) ncomp_X, integer(kind = kint), intent(in) i_fld_X, integer(kind = kint), intent(in) i_fld_WR, real (kind=kreal), dimension(n_wr), intent(inout) WR, real (kind=kreal), dimension(nnod_new,ncomp_x), intent(inout) d_new)
Definition at line 344 of file m_sel_spherical_SRs.f90.
References m_work_time::end_elapsed_time(), m_elapsed_labels_send_recv::iflag_csr_time, select_copy_from_recv::iflag_import_item, iflag_sph_srn, m_elapsed_labels_send_recv::ist_elapsed_csr, field_to_send_buffer::set_from_recv_buf_rev_tensor(), field_to_send_buffer::set_from_recv_buf_tensor(), and m_work_time::start_elapsed_time().
Referenced by copy_spectr_4_sph_trans::sel_sph_rj_tensor_from_recv().
sel_sph_vector_from_recv()
subroutine m_sel_spherical_srs::sel_sph_vector_from_recv (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) n_WR, integer(kind = kint), intent(in) npe_recv, integer(kind = kint), dimension(0:npe_recv), intent(in) istack_recv, integer(kind = kint), dimension(istack_recv(npe_recv)), intent(in) inod_import, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, integer(kind = kint), intent(in) ncomp_X, integer(kind = kint), intent(in) i_fld_X, integer(kind = kint), intent(in) i_fld_WR, real (kind=kreal), dimension(n_wr), intent(inout) WR, real (kind=kreal), dimension(nnod_new,ncomp_x), intent(inout) d_new)
Definition at line 272 of file m_sel_spherical_SRs.f90.
References m_work_time::end_elapsed_time(), m_elapsed_labels_send_recv::iflag_csr_time, select_copy_from_recv::iflag_import_item, iflag_sph_srn, m_elapsed_labels_send_recv::ist_elapsed_csr, field_to_send_buffer::set_from_recv_buf_rev_vector(), field_to_send_buffer::set_from_recv_buf_vector(), and m_work_time::start_elapsed_time().
Referenced by copy_spectr_4_sph_trans::sel_sph_rj_vector_from_recv().
set_import_table_ctl()
subroutine m_sel_spherical_srs::set_import_table_ctl (character(len = kchara), intent(in) import_ctl)
Definition at line 87 of file m_sel_spherical_SRs.f90.
References skip_comment_f::cmp_no_case(), hd_import_item, hd_import_rev, select_copy_from_recv::iflag_import_item, select_copy_from_recv::iflag_import_rev, select_copy_from_recv::iflag_import_undefined, and iflag_sph_srn.
Referenced by set_control_sph_data_mhd::s_set_control_sph_data_mhd().
Variable Documentation
hd_import_item
character(len = kchara), parameter m_sel_spherical_srs::hd_import_item = 'regular_table'
Character flag to use import table.
Definition at line 60 of file m_sel_spherical_SRs.f90.
Referenced by init_spherical_srs::init_sph_send_recv_n(), and set_import_table_ctl().
hd_import_rev
character(len = kchara), parameter m_sel_spherical_srs::hd_import_rev = 'reversed_table'
Character flag to use reverse import table.
Definition at line 63 of file m_sel_spherical_SRs.f90.
Referenced by init_spherical_srs::init_sph_send_recv_n(), and set_import_table_ctl().
iflag_sph_sr
integer(kind = kint) m_sel_spherical_srs::iflag_sph_sr = iflag_import_item
Data communication mode for scalar.
Definition at line 77 of file m_sel_spherical_SRs.f90.
Referenced by spherical_srs_n::send_recv_sph_trans(), and cmp_trans_sph_tests::sph_transfer_test_1().
iflag_sph_sr2
integer(kind = kint) m_sel_spherical_srs::iflag_sph_sr2 = iflag_import_item
Data communication mode for soleinoidal vection.
Definition at line 75 of file m_sel_spherical_SRs.f90.
Referenced by spherical_srs_n::send_recv_sph_trans_2(), and cmp_trans_sph_tests::sph_transfer_test_2().
iflag_sph_sr3
integer(kind = kint) m_sel_spherical_srs::iflag_sph_sr3 = iflag_import_item
Data communication mode for vector.
Definition at line 73 of file m_sel_spherical_SRs.f90.
Referenced by spherical_srs_n::send_recv_sph_trans_3(), and cmp_trans_sph_tests::sph_transfer_test_3().
iflag_sph_sr6
integer(kind = kint) m_sel_spherical_srs::iflag_sph_sr6 = iflag_import_item
Data communication mode for six components data.
Definition at line 71 of file m_sel_spherical_SRs.f90.
Referenced by spherical_srs_n::send_recv_sph_trans_6(), and cmp_trans_sph_tests::sph_transfer_test_6().
iflag_sph_sr_int
integer(kind = kint) m_sel_spherical_srs::iflag_sph_sr_int = iflag_import_item
Data communication mode for integer.
Definition at line 79 of file m_sel_spherical_SRs.f90.
Referenced by spherical_srs_n::send_recv_sph_trans_int(), and cmp_trans_sph_indices::sph_indices_transfer().
iflag_sph_srn
integer(kind = kint) m_sel_spherical_srs::iflag_sph_srn = iflag_import_UNDEFINED
Data communication mode for arbitrary size data.
Definition at line 68 of file m_sel_spherical_SRs.f90.
Referenced by init_spherical_srs::init_sph_send_recv_n(), sel_calypso_from_recv_n(), init_spherical_srs::sel_sph_import_table(), sel_sph_scalar_from_recv(), sel_sph_tensor_from_recv(), sel_sph_vector_from_recv(), set_import_table_ctl(), and cmp_trans_sph_tests::sph_transfer_test_n().