CALYPSO: m_sph_communicators Module Reference
m_sph_communicators Module Reference
MPI communicator for spherical transforms.
Functions/Subroutines
subroutine split_rtp_comms (nneib_domain_rtp, id_domain_rtp, nneib_domain_rj)
subroutine calypso_rtp_mpi_abort (code, message)
subroutine calypso_rj_mpi_abort (code, message)
subroutine calypso_mpi_rtp_barrier
subroutine calypso_mpi_rj_barrier
Variables
integer calypso_rtp_comm
MPI communicator for f(r,t,p) data communication.
integer(kind=kint) my_rank_rtp
process ID for f(r,t,p) data communication (start from 0)
integer(kind=kint) nprocs_rtp
number of processes for f(r,t,m) data communication
integer calypso_rj_comm
MPI communicator for f(r,j) data communication.
integer(kind=kint) my_rank_rj
process ID for f(r,j) data communication (start from 0)
integer(kind=kint) nprocs_rj
number of processes for f(r,j) data communication
Detailed Description
MPI communicator for spherical transforms.
      subroutine split_rtp_comms(nneib_domain_rtp, id_domain_rtp,     &
     &          nneib_domain_rj)
      subroutine calypso_RTP_MPI_abort(code, message)
      subroutine calypso_RJ_MPI_abort(code, message)
      subroutine calypso_MPI_RTP_barrier
      subroutine calypso_MPI_RJ_barrier
Parameters
nneib_domain_rtp Number of commucation for f(r,t,p)
id_domain_rtp process list of commucation for f(r,t,p)
nneib_domain_rj Number of commucation for f(r,j)
Function/Subroutine Documentation
calypso_mpi_rj_barrier()
subroutine m_sph_communicators::calypso_mpi_rj_barrier
Definition at line 160 of file m_sph_communicators.f90.
References calypso_rj_comm, and calypso_mpi::ierr_mpi.
calypso_mpi_rtp_barrier()
subroutine m_sph_communicators::calypso_mpi_rtp_barrier
Definition at line 151 of file m_sph_communicators.f90.
References calypso_rtp_comm, and calypso_mpi::ierr_mpi.
calypso_rj_mpi_abort()
subroutine m_sph_communicators::calypso_rj_mpi_abort (integer, intent(in) code, character(len=*), intent(in) message)
Definition at line 135 of file m_sph_communicators.f90.
References calypso_rj_comm, and calypso_mpi::ierr_mpi.
calypso_rtp_mpi_abort()
subroutine m_sph_communicators::calypso_rtp_mpi_abort (integer, intent(in) code, character(len=*), intent(in) message)
Definition at line 120 of file m_sph_communicators.f90.
References calypso_rtp_comm, and calypso_mpi::ierr_mpi.
split_rtp_comms()
subroutine m_sph_communicators::split_rtp_comms (integer(kind = kint), intent(in) nneib_domain_rtp, integer(kind = kint), dimension(nneib_domain_rtp), intent(in) id_domain_rtp, integer(kind = kint), intent(in) nneib_domain_rj)
Definition at line 53 of file m_sph_communicators.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_four_int, calypso_rj_comm, calypso_rtp_comm, m_machine_parameter::i_debug, calypso_mpi::ierr_mpi, calypso_mpi::my_rank, my_rank_rj, my_rank_rtp, nprocs_rj, and nprocs_rtp.
Referenced by init_sph_trans::set_blocks_4_leg_trans().
Variable Documentation
calypso_rj_comm
integer m_sph_communicators::calypso_rj_comm
MPI communicator for f(r,j) data communication.
Definition at line 41 of file m_sph_communicators.f90.
Referenced by calypso_mpi_rj_barrier(), calypso_rj_mpi_abort(), and split_rtp_comms().
calypso_rtp_comm
integer m_sph_communicators::calypso_rtp_comm
MPI communicator for f(r,t,p) data communication.
Definition at line 34 of file m_sph_communicators.f90.
Referenced by calypso_mpi_rtp_barrier(), calypso_rtp_mpi_abort(), and split_rtp_comms().
my_rank_rj
integer(kind=kint) m_sph_communicators::my_rank_rj
process ID for f(r,j) data communication (start from 0)
Definition at line 43 of file m_sph_communicators.f90.
Referenced by split_rtp_comms().
my_rank_rtp
integer(kind=kint) m_sph_communicators::my_rank_rtp
process ID for f(r,t,p) data communication (start from 0)
Definition at line 36 of file m_sph_communicators.f90.
Referenced by split_rtp_comms().
nprocs_rj
integer(kind=kint) m_sph_communicators::nprocs_rj
number of processes for f(r,j) data communication
Definition at line 45 of file m_sph_communicators.f90.
Referenced by split_rtp_comms().
nprocs_rtp
integer(kind=kint) m_sph_communicators::nprocs_rtp
number of processes for f(r,t,m) data communication
Definition at line 38 of file m_sph_communicators.f90.
Referenced by split_rtp_comms().