CALYPSO: t_sph_trans_comm_tbl Module Reference
t_sph_trans_comm_tbl Module Reference
Structure for communication table for spherical transform.
Data Types
type sph_comm_tables
Structure for communication table for spherical transform.
type sph_comm_tbl
Structure for communication table for each spherical grid.
Functions/Subroutines
subroutine alloc_sph_comms_stack (comms_sph)
subroutine alloc_sph_comms_item (sph, comms_sph)
subroutine dealloc_sph_comms_item (comms_sph)
subroutine alloc_sph_comm_stack (comm)
subroutine alloc_sph_comm_item (numnod, comm)
subroutine dealloc_type_sph_comm_stack (comm)
subroutine dealloc_sph_comm_item (comm)
subroutine copy_sph_comm_table (nnod_sph, comm_org, comm_new)
subroutine copy_sph_comm_neib (comm_org, comm_new)
subroutine copy_sph_comm_item (nnod_sph, comm_org, comm_new)
subroutine set_reverse_sph_comm_tbl_t (numnod, comm)
Detailed Description
Structure for communication table for spherical transform.
      subroutine alloc_sph_comms_stack(comms_sph)
      subroutine alloc_sph_comms_item(sph, comms_sph)
      subroutine dealloc_sph_comms_item(comms_sph)
        type(sph_grids), intent(in) :: sph
        type(sph_comm_tables), intent(inout) :: comms_sph
      subroutine alloc_sph_comm_stack(comm)
      subroutine alloc_sph_comm_item(numnod, comm)
      subroutine dealloc_sph_comm_item(comm)
        type(sph_comm_tbl), intent(inout) :: comm
      subroutine copy_sph_comm_table(nnod_sph, comm_org, comm_new)
      subroutine copy_sph_comm_neib(comm_org, comm_new)
      subroutine copy_sph_comm_item(nnod_sph, comm_org, comm_new)
        type(sph_comm_tbl), intent(in) :: comm_org
        type(sph_comm_tbl), intent(inout) :: comm_new
      subroutine set_reverse_sph_comm_tbl_t(numnod, comm)
        integer(kind = kint), intent(in) :: numnod
        type(sph_comm_tbl), intent(inout) :: comm
Function/Subroutine Documentation
alloc_sph_comm_item()
subroutine t_sph_trans_comm_tbl::alloc_sph_comm_item (integer(kind = kint), intent(in) numnod, type(sph_comm_tbl), intent(inout) comm)
Definition at line 137 of file t_sph_trans_comm_tbl.f90.
Referenced by alloc_sph_comms_item(), set_comm_table_rtp_rj::const_comm_table_4_rj(), gen_sph_grids_modes::const_comm_table_4_rlm(), gen_sph_grids_modes::const_comm_table_4_rtm(), set_comm_table_rtp_rj::const_comm_table_4_rtp(), copy_sph_comm_table_4_io::copy_comm_sph_from_io(), and copy_sph_comm_item().
alloc_sph_comm_stack()
subroutine t_sph_trans_comm_tbl::alloc_sph_comm_stack (type(sph_comm_tbl), intent(inout) comm)
Definition at line 123 of file t_sph_trans_comm_tbl.f90.
Referenced by alloc_sph_comms_stack(), set_comm_table_rtp_rj::const_comm_table_4_rj(), gen_sph_grids_modes::const_comm_table_4_rlm(), gen_sph_grids_modes::const_comm_table_4_rtm(), set_comm_table_rtp_rj::const_comm_table_4_rtp(), copy_sph_comm_table_4_io::copy_comm_sph_from_io(), copy_sph_comm_neib(), and bcast_comm_stacks_sph::set_bcast_comm_stacks_sph().
alloc_sph_comms_item()
subroutine t_sph_trans_comm_tbl::alloc_sph_comms_item (type(sph_grids), intent(in) sph, type(sph_comm_tables), intent(inout) comms_sph)
Definition at line 88 of file t_sph_trans_comm_tbl.f90.
References alloc_sph_comm_item().
alloc_sph_comms_stack()
subroutine t_sph_trans_comm_tbl::alloc_sph_comms_stack (type(sph_comm_tables), intent(inout) comms_sph)
Definition at line 75 of file t_sph_trans_comm_tbl.f90.
References alloc_sph_comm_stack().
copy_sph_comm_item()
subroutine t_sph_trans_comm_tbl::copy_sph_comm_item (integer(kind = kint), intent(in) nnod_sph, type(sph_comm_tbl), intent(in) comm_org, type(sph_comm_tbl), intent(inout) comm_new)
Definition at line 207 of file t_sph_trans_comm_tbl.f90.
References alloc_sph_comm_item(), and set_reverse_sph_comm_tbl_t().
Referenced by copy_sph_comm_table().
copy_sph_comm_neib()
subroutine t_sph_trans_comm_tbl::copy_sph_comm_neib (type(sph_comm_tbl), intent(in) comm_org, type(sph_comm_tbl), intent(inout) comm_new)
Definition at line 189 of file t_sph_trans_comm_tbl.f90.
References alloc_sph_comm_stack().
Referenced by copy_sph_comm_table(), mpi_gen_sph_grids_modes::mpi_gen_sph_grids(), and mpi_gen_sph_grids_modes::mpi_gen_sph_rj_mode().
copy_sph_comm_table()
subroutine t_sph_trans_comm_tbl::copy_sph_comm_table (integer(kind = kint), intent(in) nnod_sph, type(sph_comm_tbl), intent(in) comm_org, type(sph_comm_tbl), intent(inout) comm_new)
Definition at line 175 of file t_sph_trans_comm_tbl.f90.
References copy_sph_comm_item(), and copy_sph_comm_neib().
dealloc_sph_comm_item()
subroutine t_sph_trans_comm_tbl::dealloc_sph_comm_item (type(sph_comm_tbl), intent(inout) comm)
Definition at line 163 of file t_sph_trans_comm_tbl.f90.
References dealloc_type_sph_comm_stack().
Referenced by dealloc_sph_comms_item(), set_comm_table_rtp_rj::set_comm_table_4_rj(), and set_comm_table_rtp_rj::set_comm_table_4_rtp().
dealloc_sph_comms_item()
subroutine t_sph_trans_comm_tbl::dealloc_sph_comms_item (type(sph_comm_tables), intent(inout) comms_sph)
Definition at line 109 of file t_sph_trans_comm_tbl.f90.
References dealloc_sph_comm_item().
Referenced by parallel_load_data_4_sph::dealloc_sph_modes().
dealloc_type_sph_comm_stack()
subroutine t_sph_trans_comm_tbl::dealloc_type_sph_comm_stack (type(sph_comm_tbl), intent(inout) comm)
Definition at line 153 of file t_sph_trans_comm_tbl.f90.
Referenced by bcast_comm_stacks_sph::dealloc_comm_stacks_sph(), dealloc_sph_comm_item(), and bcast_comm_stacks_sph::set_bcast_comm_stacks_sph().
set_reverse_sph_comm_tbl_t()
subroutine t_sph_trans_comm_tbl::set_reverse_sph_comm_tbl_t (integer(kind = kint), intent(in) numnod, type(sph_comm_tbl), intent(inout) comm)
Definition at line 229 of file t_sph_trans_comm_tbl.f90.
Referenced by copy_sph_comm_item().