CALYPSO: t_viz_step_parameter Module Reference
t_viz_step_parameter Module Reference
Parameteres for time steppings.
Data Types
type viz_step_params
Functions/Subroutines
logical function iflag_vizs_w_fix_step (i_step, viz_step)
logical function iflag_vizs_w_flex_step (time_d, viz_step)
subroutine istep_viz_w_fix_dt (i_step, viz_step)
subroutine istep_viz_w_flex_dt (time_d, viz_step)
subroutine viz_fixed_time_step_params (dt, tctl, viz_step)
subroutine viz_flex_time_step_controls (tctl, dt, viz_step)
Detailed Description
Parameteres for time steppings.
      logical function iflag_vizs_w_fix_step(i_step, viz_step)
      logical function iflag_vizs_w_flex_step(time_d, viz_step)
      subroutine istep_viz_w_fix_dt(i_step, viz_step)
      subroutine istep_viz_w_flex_dt(time_d, viz_step)
        type(VIZ_step_params), intent(inout) :: viz_step
      subroutine viz_fixed_time_step_params(dt, tctl, viz_step)
      subroutine viz_flex_time_step_controls(tctl, dt, viz_step)
        integer(kind=kint ), intent(inout) :: visval
Function/Subroutine Documentation
iflag_vizs_w_fix_step()
logical function t_viz_step_parameter::iflag_vizs_w_fix_step (integer(kind = kint), intent(in) i_step, type(viz_step_params), intent(in) viz_step)
Definition at line 62 of file t_VIZ_step_parameter.f90.
References t_io_step_parameter::output_io_flag().
iflag_vizs_w_flex_step()
logical function t_viz_step_parameter::iflag_vizs_w_flex_step (type(time_data), intent(in) time_d, type(viz_step_params), intent(in) viz_step)
Definition at line 78 of file t_VIZ_step_parameter.f90.
References t_io_step_parameter::iflag_viz_flex_step().
istep_viz_w_fix_dt()
subroutine t_viz_step_parameter::istep_viz_w_fix_dt (integer(kind = kint), intent(in) i_step, type(viz_step_params), intent(inout) viz_step)
Definition at line 95 of file t_VIZ_step_parameter.f90.
References t_io_step_parameter::istep_file_w_fix_dt().
istep_viz_w_flex_dt()
subroutine t_viz_step_parameter::istep_viz_w_flex_dt (type(time_data), intent(in) time_d, type(viz_step_params), intent(inout) viz_step)
Definition at line 112 of file t_VIZ_step_parameter.f90.
References t_io_step_parameter::istep_file_w_flex_dt().
viz_fixed_time_step_params()
subroutine t_viz_step_parameter::viz_fixed_time_step_params (real(kind=kreal), intent(in) dt, type(time_data_control), intent(in) tctl, type(viz_step_params), intent(inout) viz_step)
Definition at line 130 of file t_VIZ_step_parameter.f90.
References m_constants::izero, and t_io_step_parameter::output_step_4_fixed_step_ctl().
Referenced by t_viz_only_step_parameter::set_fixed_t_step_params_w_viz(), and t_mhd_step_parameter::set_fixed_time_step_controls().
viz_flex_time_step_controls()
subroutine t_viz_step_parameter::viz_flex_time_step_controls (type(time_data_control), intent(in) tctl, real(kind=kreal), intent(in) dt, type(viz_step_params), intent(inout) viz_step)
Definition at line 163 of file t_VIZ_step_parameter.f90.
References m_constants::izero, and t_io_step_parameter::output_step_4_flex_step_ctl().
Referenced by t_mhd_step_parameter::set_flex_time_step_controls().