CALYPSO: set_comm_table_prt_fftw Module Reference
set_comm_table_prt_fftw Module Reference
communication table from FFTW
Functions/Subroutines
subroutine set_comm_item_prt_4_fftw (nnod_rtp, ntot_sr_rtp, irev_sr_rtp, nnod_rt, Nfft_c, aNfft, comm_sph_FFTW)
subroutine copy_prt_field_fftw_to_send (nnod_rtp, irev_sr_rtp, nnod_rt, ncomp_fwd, Nfft_c, aNfft, C_fft, n_WS, WS)
subroutine copy_prt_comp_fftw_to_send (nd, nnod_rtp, irev_sr_rtp, nnod_rt, ncomp_fwd, Nfft_c, aNfft, C_fft, n_WS, WS)
subroutine copy_prt_fftw_field_from_recv (nnod_rtp, irev_sr_rtp, nnod_rt, ncomp_bwd, n_WR, WR, Nfft_c, C_fft)
subroutine copy_prt_fftw_comp_from_recv (nd, nnod_rtp, irev_sr_rtp, nnod_rt, ncomp_bwd, n_WR, WR, Nfft_c, C_fft)
Detailed Description
communication table from FFTW
      subroutine set_comm_item_prt_4_FFTW                             &
     &         (nnod_rtp, ntot_sr_rtp, irev_sr_rtp, nnod_rt,          &
     &          Nfft_c, aNfft, comm_sph_FFTW)
        type(comm_tbl_from_FFTW), intent(inout) :: comm_sph_FFTW
      subroutine copy_prt_field_FFTW_to_send                          &
     &         (nnod_rtp, irev_sr_rtp, nnod_rt,                       &
     &          ncomp_fwd, Nfft_c, aNfft, C_fft, n_WS, WS)
      subroutine copy_prt_comp_FFTW_to_send                           &
     &         (nd, nnod_rtp, irev_sr_rtp, nnod_rt,                   &
     &          ncomp_fwd, Nfft_c, aNfft, C_fft, n_WS, WS)
      subroutine copy_prt_FFTW_field_from_recv                        &
     &         (nnod_rtp, irev_sr_rtp, nnod_rt,                       &
     &          ncomp_bwd, n_WR, WR, Nfft_c, C_fft)
      subroutine copy_prt_FFTW_comp_from_recv                         &
     &         (nd, nnod_rtp, irev_sr_rtp, nnod_rt,                   &
     &          ncomp_bwd, n_WR, WR, Nfft_c, C_fft)
Function/Subroutine Documentation
copy_prt_comp_fftw_to_send()
subroutine set_comm_table_prt_fftw::copy_prt_comp_fftw_to_send (integer(kind = kint), intent(in) nd, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(nnod_rtp), intent(in) irev_sr_rtp, integer(kind = kint), intent(in) nnod_rt, integer(kind = kint), intent(in) ncomp_fwd, integer(kind = kint), intent(in) Nfft_c, real(kind = kreal), intent(in) aNfft, complex(kind = fftw_complex), dimension(nnod_rt*nfft_c), intent(in) C_fft, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 164 of file set_comm_table_prt_FFTW.f90.
References m_constants::two.
copy_prt_fftw_comp_from_recv()
subroutine set_comm_table_prt_fftw::copy_prt_fftw_comp_from_recv (integer(kind = kint), intent(in) nd, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(nnod_rtp), intent(in) irev_sr_rtp, integer(kind = kint), intent(in) nnod_rt, integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), intent(in) n_WR, real(kind=kreal), dimension(n_wr), intent(in) WR, integer(kind = kint), intent(in) Nfft_c, complex(kind = fftw_complex), dimension(nnod_rt*nfft_c), intent(inout) C_fft)
Definition at line 261 of file set_comm_table_prt_FFTW.f90.
References m_constants::half, and m_constants::zero.
Referenced by sph_prt_domain_fftw::prt_field_back_fftw_from_recv().
copy_prt_fftw_field_from_recv()
subroutine set_comm_table_prt_fftw::copy_prt_fftw_field_from_recv (integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(nnod_rtp), intent(in) irev_sr_rtp, integer(kind = kint), intent(in) nnod_rt, integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), intent(in) n_WR, real(kind=kreal), dimension(n_wr), intent(in) WR, integer(kind = kint), intent(in) Nfft_c, complex(kind = fftw_complex), dimension(nnod_rt*nfft_c,ncomp_bwd), intent(inout) C_fft)
Definition at line 214 of file set_comm_table_prt_FFTW.f90.
References m_constants::half, and m_constants::zero.
Referenced by sph_prt_fftw::prt_back_fftw_from_recv().
copy_prt_field_fftw_to_send()
subroutine set_comm_table_prt_fftw::copy_prt_field_fftw_to_send (integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(nnod_rtp), intent(in) irev_sr_rtp, integer(kind = kint), intent(in) nnod_rt, integer(kind = kint), intent(in) ncomp_fwd, integer(kind = kint), intent(in) Nfft_c, real(kind = kreal), intent(in) aNfft, complex(kind = fftw_complex), dimension(nnod_rt*nfft_c,ncomp_fwd), intent(in) C_fft, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 112 of file set_comm_table_prt_FFTW.f90.
References m_constants::two.
set_comm_item_prt_4_fftw()
subroutine set_comm_table_prt_fftw::set_comm_item_prt_4_fftw (integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) ntot_sr_rtp, integer(kind = kint), dimension(nnod_rtp), intent(in) irev_sr_rtp, integer(kind = kint), intent(in) nnod_rt, integer(kind = kint), intent(in) Nfft_c, real(kind = kreal), intent(in) aNfft, type(comm_tbl_from_fftw), intent(inout) comm_sph_FFTW)
Definition at line 45 of file set_comm_table_prt_FFTW.f90.
References m_constants::two.
Referenced by sph_prt_fftw::init_prt_fftw(), and sph_prt_domain_fftw::init_prt_field_fftw().