CALYPSO: mpi_vectors_io Module Reference
mpi_vectors_io Module Reference
Mesh file IO for gxipped format.
Functions/Subroutines
subroutine mpi_read_scalar (IO_param, nnod, scalar)
subroutine mpi_read_vector (IO_param, nnod, numdir, vect)
subroutine mpi_write_scalar (IO_param, nnod, scalar)
subroutine mpi_write_vector (IO_param, nnod, numdir, vect)
Detailed Description
Mesh file IO for gxipped format.
      subroutine mpi_read_scalar(IO_param, nnod, scalar)
      subroutine mpi_read_vector(IO_param, nnod, numdir, vect)
      subroutine mpi_write_scalar(IO_param, nnod, scalar)
      subroutine mpi_write_vector(IO_param, nnod, numdir, vect)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
Function/Subroutine Documentation
mpi_read_scalar()
subroutine mpi_vectors_io::mpi_read_scalar (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) nnod, real(kind=kreal), dimension(nnod), intent(inout) scalar)
Definition at line 34 of file MPI_vectors_IO.f90.
References m_constants::ione, and mpi_ascii_data_io::mpi_skip_read().
Referenced by mpi_node_geometry_io::mpi_read_scl_in_ele().
mpi_read_vector()
subroutine mpi_vectors_io::mpi_read_vector (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) nnod, integer(kind=kint), intent(in) numdir, real(kind=kreal), dimension(nnod, numdir), intent(inout) vect)
Definition at line 86 of file MPI_vectors_IO.f90.
References m_constants::ione, and mpi_ascii_data_io::mpi_skip_read().
Referenced by mpi_node_geometry_io::mpi_read_vect_in_ele().
mpi_write_scalar()
subroutine mpi_vectors_io::mpi_write_scalar (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) nnod, real(kind=kreal), dimension(nnod), intent(in) scalar)
Definition at line 139 of file MPI_vectors_IO.f90.
References m_constants::ione, mpi_ascii_data_io::mpi_write_num_of_data(), and mpi_ascii_data_io::mpi_write_stack_over_domain().
Referenced by mpi_node_geometry_io::mpi_write_scl_in_ele().
mpi_write_vector()
subroutine mpi_vectors_io::mpi_write_vector (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) nnod, integer(kind=kint), intent(in) numdir, real(kind=kreal), dimension(nnod, numdir), intent(in) vect)
Definition at line 180 of file MPI_vectors_IO.f90.
References mpi_ascii_data_io::mpi_write_num_of_data(), and mpi_ascii_data_io::mpi_write_stack_over_domain().
Referenced by mpi_node_geometry_io::mpi_write_vect_in_ele().