CALYPSO: m_machine_parameter Module Reference
m_machine_parameter Module Reference
Variables
integer(kind=kint) np_smp = 1
number of SMP threads
integer(kind=kint), parameter iflag_minimum_msg = 0
integer flag for minimum message
integer(kind=kint), parameter iflag_routine_msg = 1
integer flag for routine name output
integer(kind=kint), parameter iflag_full_msg = 2
integer flag for full debug output
integer, parameter iendian_keep = 0
integer flag for keep endian
integer, parameter iendian_flip = 1
integer flag for flip endian
integer, parameter i_unix = ichar('U') * 256**3 +ichar('N') * 256**2 +ichar('I') * 256 +ichar('X')
Endian check integer.
integer, parameter i_xinu = ichar('X') * 256**3 +ichar('I') * 256**2 +ichar('N') * 256 +ichar('U')
Endian check integer (reversed)
integer(kind=kint) i_debug = iflag_minimum_msg
debug flag for all processes
integer(kind=kint) iflag_debug = iflag_minimum_msg
debug flag for master process
character(len=256) e_message
character array for error message
Variable Documentation
e_message
character(len=256) m_machine_parameter::e_message
character array for error message
Definition at line 49 of file m_machine_parameter.f90.
Referenced by analyzer_check_sph_grids::analyze_check_sph_grids(), analyzer_compare_sph_rst::analyze_compare_sph_restart(), set_ctl_parallel_platform::check_control_num_domains(), compare_sph_with_io::compare_sph_rj_with_io(), compare_sph_with_io::compare_sph_rlm_with_io(), compare_sph_with_io::compare_sph_rtm_with_io(), compare_sph_with_io::compare_sph_rtp_with_io(), construct_mhd_coefficient::construct_coefficient(), analyzer_check_sph_grids::init_check_sph_grids(), analyzer_gen_sph_grids::init_gen_sph_grids(), check_sph_mhd_openmp_size::s_check_sph_mhd_openmp_size(), set_control_4_model::s_set_control_4_model(), set_control_field_data::s_set_control_field_data(), set_control_4_normalize::set_coefs_4_composition_eq(), set_control_4_normalize::set_coefs_4_induction_eq(), set_control_4_normalize::set_coefs_4_momentum_eq(), set_control_4_normalize::set_coefs_4_thermal_eq(), set_control_4_force::set_control_4_gravity(), set_control_4_force::set_control_4_induction(), t_ctl_params_gen_sph_shell::set_control_4_shell_grids(), set_control_field_data::set_control_field_by_comp_viz(), load_mesh_and_field_4_viz::set_control_params_4_viz(), set_control_4_normalize::set_dimensionless_numbers(), m_initial_field_control::set_initial_field_id(), t_reference_scalar_param::set_linear_ref_scalar_ctl(), set_psf_iso_control::set_psf_control(), and t_reference_scalar_param::set_takepiro_scalar_ctl().
i_debug
integer(kind = kint) m_machine_parameter::i_debug = iflag_minimum_msg
debug flag for all processes
Definition at line 44 of file m_machine_parameter.f90.
Referenced by set_ctl_parallel_platform::check_control_num_domains(), const_global_element_ids::check_element_position(), set_bc_sph_scalars::check_sph_bc_scalar_sph(), const_r_mat_4_vector_sph::const_radial_mat_4_magne_sph(), const_r_mat_4_scalar_sph::const_radial_mat_4_press_sph(), const_r_mat_4_scalar_sph::const_radial_mat_4_scalar_sph(), const_r_mat_w_center_sph::const_radial_mat_press00_sph(), const_r_mat_w_center_sph::const_radial_mat_scalar00_sph(), const_r_mat_4_vector_sph::const_radial_mat_vort_2step(), const_r_mat_w_center_sph::const_rmat_press00_sph(), const_r_mat_w_center_sph::const_rmat_scalar00_sph(), patch_4_psf::count_num_patch_4_psf(), parallel_fem_mesh_init::fem_mesh_initialization(), gz_element_file_io::gz_input_edge_file(), gz_element_file_io_b::gz_input_edge_file_b(), gz_element_file_io::gz_input_element_file(), gz_element_file_io_b::gz_input_element_file_b(), gz_element_file_io::gz_input_surface_file(), gz_element_file_io_b::gz_input_surface_file_b(), gz_mpi_element_file_io::gz_mpi_input_edge_file(), gz_mpi_element_file_io_b::gz_mpi_input_edge_file_b(), gz_mpi_element_file_io::gz_mpi_input_element_file(), gz_mpi_element_file_io_b::gz_mpi_input_element_file_b(), gz_mpi_element_file_io::gz_mpi_input_surface_file(), gz_mpi_element_file_io_b::gz_mpi_input_surface_file_b(), gz_mpi_element_file_io::gz_mpi_output_edge_file(), gz_mpi_element_file_io_b::gz_mpi_output_edge_file_b(), gz_mpi_element_file_io::gz_mpi_output_element_file(), gz_mpi_element_file_io_b::gz_mpi_output_element_file_b(), gz_mpi_element_file_io::gz_mpi_output_surface_file(), gz_mpi_element_file_io_b::gz_mpi_output_surface_file_b(), gz_mpi_sph_modes_file_io::gz_mpi_read_geom_rtm_file(), gz_mpi_sph_modes_file_io_b::gz_mpi_read_geom_rtm_file_b(), gz_mpi_sph_modes_file_io::gz_mpi_read_geom_rtp_file(), gz_mpi_sph_modes_file_io_b::gz_mpi_read_geom_rtp_file_b(), gz_mpi_mesh_file_io::gz_mpi_read_geometry_size(), gz_mpi_mesh_file_io_b::gz_mpi_read_geometry_size_b(), gz_mpi_mesh_file_io::gz_mpi_read_mesh(), gz_mpi_mesh_file_io_b::gz_mpi_read_mesh_file_b(), gz_mpi_mesh_file_io::gz_mpi_read_mesh_geometry(), gz_mpi_mesh_file_io_b::gz_mpi_read_mesh_geometry_b(), gz_mpi_sph_modes_file_io::gz_mpi_read_modes_rlm_file(), gz_mpi_sph_modes_file_io_b::gz_mpi_read_modes_rlm_file_b(), gz_mpi_mesh_file_io::gz_mpi_read_node_size(), gz_mpi_mesh_file_io_b::gz_mpi_read_node_size_b(), gz_mpi_sph_modes_file_io::gz_mpi_read_spectr_rj_file(), gz_mpi_sph_modes_file_io_b::gz_mpi_read_spectr_rj_file_b(), gz_mpi_sph_modes_file_io::gz_mpi_write_geom_rtm_file(), gz_mpi_sph_modes_file_io_b::gz_mpi_write_geom_rtm_file_b(), gz_mpi_sph_modes_file_io::gz_mpi_write_geom_rtp_file(), gz_mpi_sph_modes_file_io_b::gz_mpi_write_geom_rtp_file_b(), gz_mpi_mesh_file_io::gz_mpi_write_mesh_file(), gz_mpi_mesh_file_io_b::gz_mpi_write_mesh_file_b(), gz_mpi_sph_modes_file_io::gz_mpi_write_modes_rlm_file(), gz_mpi_sph_modes_file_io_b::gz_mpi_write_modes_rlm_file_b(), gz_mpi_sph_modes_file_io::gz_mpi_write_spectr_rj_file(), gz_mpi_sph_modes_file_io_b::gz_mpi_write_spectr_rj_file_b(), gz_element_file_io::gz_output_edge_file(), gz_element_file_io_b::gz_output_edge_file_b(), gz_element_file_io::gz_output_element_file(), gz_element_file_io_b::gz_output_element_file_b(), gz_element_file_io::gz_output_surface_file(), gz_element_file_io_b::gz_output_surface_file_b(), gz_field_file_io_b::gz_rd_alloc_st_fld_file_b(), gz_field_file_io_b::gz_rd_alloc_st_fld_head_b(), gz_ucd_field_file_io_b::gz_read_alloc_ucd_2_fld_file_b(), gz_ucd_field_file_io::gz_read_alloc_ucd_2_ld_file(), gz_sph_modes_grids_file_io::gz_read_geom_rtm_file(), gz_sph_modes_file_io_b::gz_read_geom_rtm_file_b(), gz_sph_modes_grids_file_io::gz_read_geom_rtp_file(), gz_sph_modes_file_io_b::gz_read_geom_rtp_file_b(), gz_mesh_file_io::gz_read_geometry_size(), gz_mesh_file_io_b::gz_read_geometry_size_b(), gz_mesh_file_io::gz_read_mesh(), gz_mesh_file_io_b::gz_read_mesh_file_b(), gz_mesh_file_io::gz_read_mesh_geometry(), gz_mesh_file_io_b::gz_read_mesh_geometry_b(), gz_sph_modes_grids_file_io::gz_read_modes_rlm_file(), gz_sph_modes_file_io_b::gz_read_modes_rlm_file_b(), gz_mesh_file_io::gz_read_node_size(), gz_mesh_file_io_b::gz_read_node_size_b(), gz_sph_modes_grids_file_io::gz_read_spectr_modes_rj_file(), gz_sph_modes_file_io_b::gz_read_spectr_modes_rj_file_b(), gz_field_file_io_b::gz_read_step_field_file_b(), gz_ucd_field_file_io::gz_read_ucd_2_fld_file(), gz_ucd_field_file_io_b::gz_read_ucd_2_fld_file_b(), gz_sph_modes_grids_file_io::gz_write_geom_rtm_file(), gz_sph_modes_file_io_b::gz_write_geom_rtm_file_b(), gz_sph_modes_grids_file_io::gz_write_geom_rtp_file(), gz_sph_modes_file_io_b::gz_write_geom_rtp_file_b(), gz_mesh_file_io::gz_write_mesh_file(), gz_mesh_file_io_b::gz_write_mesh_file_b(), gz_sph_modes_grids_file_io::gz_write_modes_rlm_file(), gz_sph_modes_file_io_b::gz_write_modes_rlm_file_b(), gz_sph_modes_grids_file_io::gz_write_spectr_modes_rj_file(), gz_sph_modes_file_io_b::gz_write_spectr_modes_rj_file_b(), gz_field_file_io_b::gz_write_step_fld_file_b(), gz_ucd_field_file_io::gz_write_ucd_2_fld_file(), gz_ucd_field_file_io_b::gz_write_ucd_2_fld_file_b(), gz_write_udt_file_io_b::gz_write_ucd_grid_mpi_b(), element_file_io::input_edge_file(), element_file_io_b::input_edge_file_b(), element_file_io::input_element_file(), element_file_io_b::input_element_file_b(), element_file_io::input_surface_file(), element_file_io_b::input_surface_file_b(), mpi_element_file_io::mpi_input_edge_file(), mpi_element_file_io_b::mpi_input_edge_file_b(), mpi_element_file_io::mpi_input_element_file(), mpi_element_file_io_b::mpi_input_element_file_b(), mpi_element_file_io::mpi_input_surface_file(), mpi_element_file_io_b::mpi_input_surface_file_b(), mpi_element_file_io::mpi_output_edge_file(), mpi_element_file_io_b::mpi_output_edge_file_b(), mpi_element_file_io::mpi_output_element_file(), mpi_element_file_io_b::mpi_output_element_file_b(), mpi_element_file_io::mpi_output_surface_file(), mpi_element_file_io_b::mpi_output_surface_file_b(), mpi_sph_modes_file_io::mpi_read_geom_rtm_file(), mpi_sph_modes_file_io_b::mpi_read_geom_rtm_file_b(), mpi_sph_modes_file_io::mpi_read_geom_rtp_file(), mpi_sph_modes_file_io_b::mpi_read_geom_rtp_file_b(), mpi_mesh_file_io::mpi_read_geometry_size(), mpi_mesh_file_io_b::mpi_read_geometry_size_b(), mpi_mesh_file_io::mpi_read_mesh_file(), mpi_mesh_file_io_b::mpi_read_mesh_file_b(), mpi_mesh_file_io::mpi_read_mesh_geometry(), mpi_mesh_file_io_b::mpi_read_mesh_geometry_b(), mpi_sph_modes_file_io::mpi_read_modes_rlm_file(), mpi_sph_modes_file_io_b::mpi_read_modes_rlm_file_b(), mpi_mesh_file_io::mpi_read_node_size(), mpi_mesh_file_io_b::mpi_read_node_size_b(), mpi_sph_modes_file_io::mpi_read_spectr_rj_file(), mpi_sph_modes_file_io_b::mpi_read_spectr_rj_file_b(), mpi_sph_modes_file_io::mpi_write_geom_rtm_file(), mpi_sph_modes_file_io_b::mpi_write_geom_rtm_file_b(), mpi_sph_modes_file_io::mpi_write_geom_rtp_file(), mpi_sph_modes_file_io_b::mpi_write_geom_rtp_file_b(), mpi_mesh_file_io::mpi_write_mesh_file(), mpi_mesh_file_io_b::mpi_write_mesh_file_b(), mpi_sph_modes_file_io::mpi_write_modes_rlm_file(), mpi_sph_modes_file_io_b::mpi_write_modes_rlm_file_b(), mpi_sph_modes_file_io::mpi_write_spectr_rj_file(), mpi_sph_modes_file_io_b::mpi_write_spectr_rj_file_b(), element_file_io::output_edge_file(), element_file_io_b::output_edge_file_b(), element_file_io::output_element_file(), element_file_io_b::output_element_file_b(), element_file_io::output_surface_file(), element_file_io_b::output_surface_file_b(), udt_file_io::read_alloc_grd_file(), gz_field_file_io::read_alloc_gz_field_file(), gz_field_file_io::read_alloc_gz_step_field_file(), gz_field_file_io::read_alloc_gz_step_field_head(), gz_udt_file_io::read_alloc_gz_ucd_file(), gz_udt_file_io::read_alloc_gz_ucd_grd(), gz_udt_file_io::read_alloc_gz_udt_file(), gz_udt_file_io::read_alloc_gz_udt_params(), gz_vtk_file_io::read_alloc_gz_vtk_file(), gz_vtk_file_io::read_alloc_gz_vtk_grid(), gz_vtk_file_io::read_alloc_gz_vtk_phys(), ucd_field_file_io::read_alloc_ucd_2_fld_file(), ucd_field_file_io_b::read_alloc_ucd_2_fld_file_b(), ucd_field_file_io_b::read_alloc_ucd_2_fld_header_b(), udt_file_io::read_alloc_ucd_file(), udt_file_io::read_alloc_udt_file(), udt_file_io::read_alloc_udt_params(), vtk_file_io::read_alloc_vtk_file(), vtk_file_io::read_alloc_vtk_grid(), vtk_file_io::read_alloc_vtk_phys(), field_file_io::read_and_alloc_step_field(), field_file_io::read_and_allocate_field_file(), field_file_io_b::read_and_allocate_step_field_b(), field_file_io::read_and_allocate_step_head(), field_file_io_b::read_and_allocate_step_head_b(), sph_modes_grids_file_io::read_geom_rtm_file(), sph_modes_grids_file_io_b::read_geom_rtm_file_b(), sph_modes_grids_file_io::read_geom_rtp_file(), sph_modes_grids_file_io_b::read_geom_rtp_file_b(), mesh_file_io::read_geometry_size(), mesh_file_io_b::read_geometry_size_b(), udt_file_io::read_grd_file(), gz_rst_data_io_by_fld::read_gz_rst_comps(), gz_rst_data_io_by_fld::read_gz_rst_file(), gz_field_file_io::read_gz_step_field_file(), gz_udt_file_io::read_gz_ucd_file(), gz_udt_file_io::read_gz_ucd_grd(), gz_udt_file_io::read_gz_udt_file(), gz_vtk_file_io::read_gz_vtk_file(), gz_vtk_file_io::read_gz_vtk_grid(), gz_vtk_file_io::read_gz_vtk_phys(), mesh_file_io::read_mesh_file(), mesh_file_io_b::read_mesh_file_b(), mesh_file_io::read_mesh_geometry(), mesh_file_io_b::read_mesh_geometry_b(), sph_modes_grids_file_io::read_modes_rlm_file(), sph_modes_grids_file_io_b::read_modes_rlm_file_b(), mesh_file_io::read_node_size(), mesh_file_io_b::read_node_size_b(), rst_data_io_by_fld::read_rst_data_comps(), rst_data_io_by_fld::read_rst_file(), sph_modes_grids_file_io::read_spectr_modes_rj_file(), sph_modes_grids_file_io_b::read_spectr_modes_rj_file_b(), field_file_io::read_step_field_file(), field_file_io_b::read_step_field_file_b(), ucd_field_file_io::read_ucd_2_fld_file(), ucd_field_file_io_b::read_ucd_2_fld_file_b(), udt_file_io::read_ucd_file(), udt_file_io::read_udt_file(), vtk_file_io::read_vtk_file(), vtk_file_io::read_vtk_grid(), vtk_file_io::read_vtk_phys(), set_loaded_data_4_sph::set_fem_center_mode_4_sph(), find_node_and_patch_psf::set_node_and_patch_psf(), set_bc_sph_scalars::set_sph_bc_composition_sph(), set_bc_sph_scalars::set_sph_bc_temp_sph(), solve_sph_fluid_crank::solve_pressure_by_div_v(), m_sph_communicators::split_rtp_comms(), set_control_platform_data::turn_off_debug_flag_by_ctl(), sph_modes_grids_file_io::write_geom_rtm_file(), sph_modes_grids_file_io_b::write_geom_rtm_file_b(), sph_modes_grids_file_io::write_geom_rtp_file(), sph_modes_grids_file_io_b::write_geom_rtp_file_b(), udt_file_io::write_grd_file(), gz_udt_file_io::write_gz_grd_file(), gz_field_file_io::write_gz_step_field_file(), gz_udt_file_io::write_gz_ucd_file(), gz_udt_file_io::write_gz_udt_file(), mesh_file_io::write_mesh_file(), mesh_file_io_b::write_mesh_file_b(), sph_modes_grids_file_io::write_modes_rlm_file(), sph_modes_grids_file_io_b::write_modes_rlm_file_b(), mesh_file_io::write_node_position_cyl(), mesh_file_io::write_node_position_sph(), sph_modes_grids_file_io::write_spectr_modes_rj_file(), sph_modes_grids_file_io_b::write_spectr_modes_rj_file_b(), field_file_io::write_step_field_file(), field_file_io_b::write_step_field_file_b(), ucd_field_file_io::write_ucd_2_fld_file(), ucd_field_file_io_b::write_ucd_2_fld_file_b(), udt_file_io::write_ucd_file(), udt_file_io::write_udt_file(), vtk_file_io::write_vtk_file(), vtk_file_io::write_vtk_grid(), and vtk_file_io::write_vtk_phys().
i_unix
integer, parameter m_machine_parameter::i_unix = ichar('U') * 256**3 +ichar('N') * 256**2 +ichar('I') * 256 +ichar('X')
Endian check integer.
Definition at line 33 of file m_machine_parameter.f90.
Referenced by binary_io::endian_check(), m_calypso_mpi_io::mpi_write_endian_flag(), and binary_io::write_endian_flag().
i_xinu
integer, parameter m_machine_parameter::i_xinu = ichar('X') * 256**3 +ichar('I') * 256**2 +ichar('N') * 256 +ichar('U')
Endian check integer (reversed)
Definition at line 38 of file m_machine_parameter.f90.
Referenced by binary_io::endian_check().
iendian_flip
integer, parameter m_machine_parameter::iendian_flip = 1
integer flag for flip endian
Definition at line 30 of file m_machine_parameter.f90.
Referenced by binary_io::endian_check(), gz_mpi_binary_data_io::gz_mpi_read_1d_vector_b(), gz_mpi_binary_data_io::gz_mpi_read_int8_vector_b(), gz_mpi_binary_head_io::gz_mpi_read_mul_int8head_b(), gz_mpi_binary_head_io::gz_mpi_read_mul_realhead_b(), m_calypso_mpi_io::mpi_read_int4_b(), m_calypso_mpi_io::mpi_read_int8_b(), m_calypso_mpi_io::mpi_read_int_b(), m_calypso_mpi_io::mpi_read_real_b(), and t_rayleigh_restart_io::read_rayleigh_restart_params().
iendian_keep
integer, parameter m_machine_parameter::iendian_keep = 0
integer flag for keep endian
Definition at line 28 of file m_machine_parameter.f90.
Referenced by binary_io::endian_check(), gz_binary_io::gz_read_endian_flag(), binary_io::read_endian_flag(), and t_rayleigh_restart_io::read_rayleigh_restart_params().
iflag_debug
integer(kind = kint) m_machine_parameter::iflag_debug = iflag_minimum_msg
debug flag for master process
Definition at line 46 of file m_machine_parameter.f90.
Referenced by add_nodal_fields_4_mhd::add_dependent_field(), add_nodal_fields_4_mhd::add_field_name_4_mhd(), add_field_to_sph_trans_list::add_field_name_4_sph_trns(), add_nodal_fields_ctl::add_phys_name_ctl(), analyzer_assemble_sph::analyze_assemble_sph(), analyzer_check_sph_grids::analyze_check_sph_grids(), analyzer_compare_sph_rst::analyze_compare_sph_restart(), analyzer_rayleigh_cvt_sph::analyze_cvt_rayleigh_sph(), analyzer_gen_sph_grids::analyze_gen_sph_grids(), analyzer_test_sph::analyze_test_sph(), address_sph_trans_snap::bwd_trans_address_diff_vect(), address_sph_trans_snap::bwd_trans_address_ene_flux(), address_sph_trans_mhd::bwd_trans_address_mhd(), address_sph_trans_snap::bwd_trans_address_snap(), cal_rms_fields_by_sph::cal_correlate_in_shell(), cal_sph_field_by_rotation::cal_div_of_fluxes_sph(), cal_grad_of_sph_vectors::cal_grad_of_scalars_sph(), cal_rms_fields_by_sph::cal_mean_squre_in_shell(), cal_sph_field_by_rotation::cal_rot_of_forces_sph_2(), cal_sph_field_by_rotation::cal_rot_of_induction_sph(), lead_fields_4_sph_mhd::cal_sph_enegy_fluxes(), cal_write_sph_monitor_data::cal_sph_monitor_data(), parallel_gen_sph_grids::check_and_make_para_rj_mode(), parallel_gen_sph_grids::check_and_make_para_sph_mesh(), t_check_and_make_sph_mesh::check_and_make_sph_mesh(), set_ctl_parallel_platform::check_control_num_domains(), t_field_on_circle::collect_spectr_for_circle(), const_surface_data::const_all_surface_data(), gen_sph_grids_modes::const_comm_table_4_rlm(), const_element_comm_tables::const_edge_comm_table(), const_element_comm_tables::const_element_comm_tbl_only(), const_surface_data::const_external_surface_data(), const_element_comm_tables::const_global_edge_id(), const_element_comm_tables::const_global_mesh_infos(), const_fem_mesh_sph_mhd::const_global_sph_fem(), const_global_sph_grids_modes::const_global_sph_fem_grid(), const_mesh_information::const_group_type_info(), const_surface_data::const_isolate_surface_data(), const_mesh_information::const_mesh_infos(), const_mesh_information::const_nod_ele_infos(), const_radial_mat_4_sph::const_radial_mat_sph_snap(), const_radial_mat_4_sph::const_radial_matrices_sph(), set_comm_table_rtp_rj::const_sph_rj_modes(), gen_sph_grids_modes::const_sph_rlm_modes(), gen_sph_grids_modes::const_sph_rtm_grids(), set_comm_table_rtp_rj::const_sph_rtp_grids(), const_edge_data::construct_edge_data(), const_surface_data::construct_surface_data(), set_sph_local_node::count_numnod_local_sph_mesh(), const_edge_data::empty_edge_connect_type(), const_mesh_information::empty_mesh_info(), const_mesh_information::empty_nod_and_ele_type_infos(), const_surface_data::empty_surface_connect(), lead_fields_4_sph_mhd::enegy_fluxes_4_sph_mhd(), analyzer_sph_dynamobench::evolution_sph_dynamobench(), analyzer_sph_mhd_w_psf::evolution_sph_mhd_w_psf(), analyzer_sph_snap_w_psf::evolution_sph_snap_w_psf(), fem_analyzer_sph_mhd::fem_analyze_sph_mhd(), fem_analyzer_sph_mhd::fem_initialize_sph_mhd(), parallel_fem_mesh_init::fem_mesh_initialization(), nod_phys_send_recv::fields_send_recv(), t_fft_selector::finalize_fft_sel_t(), t_sph_fft_selector::finalize_sph_fft_select(), const_element_comm_tables::find_position_range(), address_sph_trans_snap::fwd_trans_address_diff_vect(), address_sph_trans_snap::fwd_trans_address_ene_flux(), address_sph_trans_mhd::fwd_trans_address_mhd(), address_sph_trans_snap::fwd_trans_address_snap(), lead_fields_4_sph_mhd::gradients_of_vectors_sph(), init_sphrical_transform_mhd::init_leg_fourier_trans_mhd(), init_radial_infos_sph_mhd::init_r_infos_sph_mhd(), init_radial_infos_sph_mhd::init_r_infos_sph_mhd_evo(), sph_mhd_rst_io_control::init_radial_sph_interpolation(), init_radial_infos_sph_mhd::init_reference_temps(), cal_rms_fields_by_sph::init_rms_4_sph_spectr(), t_sph_mhd_monitor_data_io::init_rms_4_sph_spectr_4_mhd(), init_sphrical_transform_mhd::init_sph_transform_mhd(), t_coriolis_terms_rlm::init_sum_coriolis_rlm(), analyzer_test_sph::init_test_sph(), init_sphrical_transform_mhd::init_work_4_coriolis(), sph_analyzer_add_initial::initialize_add_sph_initial(), sph_analyzer_const_initial::initialize_const_sph_initial(), analyzer_sph_dynamobench::initialize_sph_dynamobench(), analyzer_sph_mhd_w_psf::initialize_sph_mhd_w_psf(), analyzer_sph_snap_w_psf::initialize_sph_snap_w_psf(), input_control_sph_mhd::input_control_4_sph_make_init(), input_control_sph_mhd::input_control_4_sph_mhd_nosnap(), input_control_dynamobench::input_control_sph_dynamobench(), input_control_sph_mhd::input_control_sph_mhd_psf(), output_viz_file_control::lead_field_data_flag(), lead_fields_4_sph_mhd::lead_fields_by_sph_trans(), cal_nonlinear::licv_exp(), t_check_and_make_sph_mesh::load_fem_mesh_4_sph(), t_check_and_make_sph_mesh::load_para_sph_and_fem_mesh(), parallel_load_data_4_sph::load_sph_mesh(), parallel_load_data_4_sph::load_sph_rj_mesh(), load_mesh_and_field_4_viz::mesh_setup_4_viz(), const_data_4_dynamobench::mid_eq_transfer_dynamobench(), mpi_gen_sph_grids_modes::mpi_gen_sph_grids(), mpi_gen_sph_grids_modes::mpi_gen_sph_rj_mode(), cal_nonlinear::nonlinear(), cal_nonlinear::nonlinear_by_pseudo_sph(), t_sph_mhd_monitor_data_io::open_sph_vol_rms_file_mhd(), node_monitor_io::output_monitor_control(), parallel_load_data_4_sph::output_sph_mesh(), cal_write_sph_monitor_data::output_sph_monitor_data(), parallel_load_data_4_sph::output_sph_rj_mesh(), parallel_gen_sph_grids::para_gen_sph_grids(), parallel_gen_sph_grids::para_gen_sph_rj_mode(), t_parai_gen_sph_grids_modes::para_gen_sph_rlm_rj_modes(), t_parai_gen_sph_grids_modes::para_gen_sph_rtm_rtp_grids(), output_gen_sph_grid_modes::para_output_sph_mode_grids(), para_const_kemoview_mesh::pickup_surface_mesh(), pole_sph_transform::pole_backward_transforms(), lead_fields_4_sph_mhd::pressure_4_sph_mhd(), self_buoyancy_on_sphere::r_buoyancy_on_sphere(), sph_mhd_rst_io_control::read_alloc_sph_rst_4_snap(), sph_mhd_rst_io_control::read_alloc_sph_spectr(), t_sph_boundary_input_data::read_boundary_spectr_file(), t_control_array_chara2real::read_char2real_ctl_type(), t_control_array_character::read_chara_ctl_type(), t_control_array_character2::read_character2_ctl_type(), t_control_array_character3::read_character3_ctl_type(), t_control_array_charaint3::read_charaint3_ctl_type(), t_control_array_charaint::read_charaint_ctl_type(), t_control_array_charareal::read_charareal_ctl_type(), t_control_array_charareal2::read_charreal2_ctl_type(), t_control_array_int2real2::read_int2real2_ctl_type(), t_control_array_int2real::read_int2real_ctl_type(), t_control_array_intcharreal::read_intcharreal_ctl_type(), t_control_array_integer2::read_integer2_ctl_type(), t_control_array_integer3::read_integer3_ctl_type(), t_control_array_integer::read_integer_ctl_type(), t_control_array_intreal::read_intreal_ctl_type(), t_control_array_real2::read_real2_ctl_type(), t_control_array_real3::read_real3_ctl_type(), t_control_array_real::read_real_ctl_type(), cal_sph_field_by_rotation::rot_momentum_eq_exp_sph(), cal_sol_sph_mhd_crank::s_cal_sol_sph_mhd_crank(), compare_sph_with_io::s_compare_sph_with_io(), const_1d_ele_connect_4_sph::s_const_1d_ele_connect_4_sph(), const_data_4_dynamobench::s_const_data_4_dynamobench(), const_global_sph_grids_modes::s_const_global_sph_grids_modes(), set_bc_sph_mhd::s_set_bc_sph_mhd(), set_control_4_composition::s_set_control_4_composition(), set_control_4_model::s_set_control_4_crank(), set_control_4_magne::s_set_control_4_magne(), set_control_4_model::s_set_control_4_model(), set_control_4_normalize::s_set_control_4_normalize(), set_control_4_press::s_set_control_4_press(), set_control_4_temp::s_set_control_4_temp(), set_control_4_velo::s_set_control_4_velo(), set_control_field_data::s_set_control_field_data(), set_nodes_4_groups_viewer::s_set_nodes_4_groups_viewer(), set_nodes_4_viewer::s_set_nodes_4_viewer(), t_cross_section::sectioning_initialize(), t_cross_section::sectioning_visualize(), cal_self_buoyancies_sph::sel_buoyancies_sph_mhd(), div_self_buoyancies_sph::sel_div_buoyancies_sph_mhd(), rot_self_buoyancies_sph::sel_rot_self_buoyancy_sph(), init_sphrical_transform_mhd::sel_sph_transform_mhd(), set_address_sph_trans_snap::set_addresses_diff_vect_trans(), set_address_sph_trans_snap::set_addresses_ene_flux_trans(), set_address_sph_trans_snap::set_addresses_snapshot_trans(), set_control_4_force::set_control_4_coriolis_force(), set_control_4_force::set_control_4_gravity(), set_control_4_force::set_control_4_induction(), set_control_sph_mhd::set_control_4_sph_mhd(), set_control_field_data::set_control_field_by_comp_viz(), set_control_4_force::set_control_force_flags(), set_control_sph_mhd::set_control_sph_mhd_bcs(), set_control_sph_data_mhd::set_control_sph_mhd_fields(), set_control_sph_mhd::set_control_sph_mhd_noviz(), set_control_sph_mhd::set_control_sph_mhd_w_viz(), init_radial_infos_sph_mhd::set_delta_r_4_sph_mhd(), cal_rms_fields_by_sph::set_domains_4_spectr_output(), set_radius_func_noequi::set_dr_for_nonequi(), set_surf_edge_mesh::set_edge_connectivity(), set_controls_4_sph_shell::set_fem_mesh_mode_4_sph(), load_mesh_and_field_4_viz::set_field_data_4_viz(), m_initial_field_control::set_initial_field_id(), set_psf_iso_control::set_iso_control(), t_reference_scalar_param::set_linear_ref_scalar_ctl(), const_mesh_information::set_local_element_info(), const_mesh_information::set_nod_and_ele_infos(), find_node_and_patch_psf::set_node_and_patch_psf(), set_radius_4_sph_dynamo::set_radius_dat_4_sph_dynamo(), parallel_load_data_4_sph::set_radius_dat_sph_mhd(), t_reference_scalar_param::set_reference_scalar_ctl(), cal_sol_sph_mhd_crank::set_sph_field_to_start(), set_surf_edge_mesh::set_surf_connectivity(), set_surf_edge_mesh::set_surface_and_edge(), load_element_mesh_data::set_surface_mesh_from_io(), t_reference_scalar_param::set_takepiro_scalar_ctl(), sph_analyzer_add_initial::sph_add_initial_field(), sph_trans_w_coriols::sph_b_trans_licv(), sph_trans_w_coriols::sph_b_trans_w_coriolis(), t_sph_transforms::sph_b_trans_w_poles(), sph_transforms_4_mhd::sph_back_trans_4_mhd(), set_control_4_sph_to_fem::sph_boundary_io_control(), sph_analyzer_const_initial::sph_const_initial_field(), sph_trans_w_coriols::sph_f_trans_licv(), sph_trans_w_coriols::sph_f_trans_w_coriolis(), t_sph_transforms::sph_forward_transforms(), parallel_load_data_4_sph::sph_index_flags_and_params(), sph_analyzer_d_bench::sph_init_sph_dbench(), sph_analyzer_snap_w_psf::sph_init_sph_snap_psf(), set_initial_sph_dynamo::sph_initial_data_control(), sph_analyzer_mhd::sph_initialize_mhd(), t_sph_mhd_zonal_mean_viz::sph_mhd_zonal_mean_section(), t_sph_mhd_zonal_mean_viz::sph_mhd_zonal_rms_section(), sph_transforms_4_mhd::sph_pole_trans_4_mhd(), fem_analyzer_sph_mhd::sph_to_fem_bridge_mhd(), test_fftw3(), init_fft_4_sph::test_fourier_trans_vector(), test_single_fftw3(), set_control_platform_data::turn_off_debug_flag_by_ctl(), cal_sol_sph_mhd_crank::update_after_composit_sph(), cal_sol_sph_mhd_crank::update_after_heat_sph(), cal_sol_sph_mhd_crank::update_after_magne_sph(), cal_sol_sph_mhd_crank::update_after_vorticity_sph(), t_fft_selector::verify_fft_select(), and t_sph_fft_selector::verify_sph_fft_select().
iflag_full_msg
integer(kind = kint), parameter m_machine_parameter::iflag_full_msg = 2
integer flag for full debug output
Definition at line 25 of file m_machine_parameter.f90.
Referenced by const_r_mat_4_vector_sph::const_radial_mat_4_magne_sph(), const_r_mat_4_scalar_sph::const_radial_mat_4_press_sph(), const_r_mat_4_scalar_sph::const_radial_mat_4_scalar_sph(), const_r_mat_4_vector_sph::const_radial_mat_vort_2step(), const_r_mat_w_center_sph::const_rmat_press00_sph(), const_r_mat_w_center_sph::const_rmat_scalar00_sph(), parallel_fem_mesh_init::fem_mesh_initialization(), set_bc_sph_mhd::s_set_bc_sph_mhd(), set_control_4_composition::s_set_control_4_composition(), set_control_4_press::s_set_control_4_press(), set_control_4_temp::s_set_control_4_temp(), set_control_4_velo::s_set_control_4_velo(), set_radius_func_noequi::set_dr_for_nonequi(), set_loaded_data_4_sph::set_fem_center_mode_4_sph(), and set_control_platform_data::turn_off_debug_flag_by_ctl().
iflag_minimum_msg
integer(kind = kint), parameter m_machine_parameter::iflag_minimum_msg = 0
integer flag for minimum message
Definition at line 21 of file m_machine_parameter.f90.
Referenced by set_control_platform_data::turn_off_debug_flag_by_ctl().
iflag_routine_msg
integer(kind = kint), parameter m_machine_parameter::iflag_routine_msg = 1
integer flag for routine name output
Definition at line 23 of file m_machine_parameter.f90.
Referenced by add_nodal_fields_4_mhd::add_dependent_field(), nod_phys_send_recv::fields_send_recv(), init_radial_infos_sph_mhd::init_r_infos_sph_mhd(), init_sphrical_transform_mhd::init_sph_transform_mhd(), cal_sph_field_by_rotation::rot_momentum_eq_exp_sph(), set_control_4_model::s_set_control_4_crank(), set_control_4_magne::s_set_control_4_magne(), set_control_4_model::s_set_control_4_model(), set_control_4_normalize::s_set_control_4_normalize(), set_control_field_data::s_set_control_field_data(), set_control_4_force::set_control_4_coriolis_force(), set_control_4_force::set_control_4_gravity(), set_control_4_force::set_control_4_induction(), set_control_field_data::set_control_field_by_comp_viz(), set_control_4_force::set_control_force_flags(), init_radial_infos_sph_mhd::set_delta_r_4_sph_mhd(), m_initial_field_control::set_initial_field_id(), t_reference_scalar_param::set_linear_ref_scalar_ctl(), parallel_load_data_4_sph::set_radius_dat_sph_mhd(), t_reference_scalar_param::set_reference_scalar_ctl(), t_reference_scalar_param::set_takepiro_scalar_ctl(), and set_control_platform_data::turn_off_debug_flag_by_ctl().
np_smp
integer(kind=kint) m_machine_parameter::np_smp = 1
number of SMP threads
Definition at line 18 of file m_machine_parameter.f90.
Referenced by t_flex_delta_t_data::alloc_check_delta_t_data(), t_circle_transform::alloc_circle_transform(), t_sph_component_fftw::alloc_comp_fftw_plan(), t_edge_data::alloc_edge_param_smp(), t_fft_test_data::alloc_fft_test_data(), t_legendre_work_sym_matmul::alloc_leg_scl_sym_matmul(), t_legendre_work_sym_matmul::alloc_leg_scl_symmetry(), t_leg_trans_sym_matmul_big::alloc_leg_sym_matmul_big(), t_leg_trans_sym_matmul_big::alloc_leg_sym_matmul_big2(), t_legendre_work_sym_matmul::alloc_leg_vec_sym_matmul(), t_legendre_work_sym_matmul::alloc_leg_vec_symmetry(), t_spheric_rtp_data::alloc_num_pole_sph_trans(), t_spheric_rj_data::alloc_rj_param_smp(), t_spheric_rlm_data::alloc_rlm_param_smp(), t_spheric_rtm_data::alloc_rtm_param_smp(), t_spheric_rtp_data::alloc_rtp_param_smp(), t_field_matrices_4_legendre::alloc_spectr_mat_omp(), t_sph_field_fftw::alloc_whole_fftw_plan(), t_sph_component_fftpack5::alloc_work_comp_fftpack(), t_sph_single_fftpack5::alloc_work_sgl_fftpack(), t_geometry_data::allocate_ele_param_smp_type(), set_surface_node::allocate_make_4_surf_nod_grp(), t_geometry_data::allocate_node_param_smp_type(), t_surface_data::allocate_surf_param_smp_type(), set_edge_list_for_psf::allocate_work_4_mark_edge_psf(), set_node_list_for_psf::allocate_work_4_mark_node_psf(), set_element_list_for_psf::allocate_work_4_mark_psf(), set_surface_list_for_psf::allocate_work_4_mark_surf_psf(), cal_energy_flux_rtp::cal_lengh_scale_rtp(), t_geometry_data::check_ele_size_smp_type(), t_geometry_data::check_nod_size_smp_type(), t_surface_group_connect::check_surf_nod_4_sheard_para(), circle_transform_single::circle_transfer_scalar(), circle_transform_single::circle_transfer_vector(), set_ele_id_4_node_type::const_next_nod_id_4_node(), const_r_mat_4_vector_sph::const_radial_mat_4_magne_sph(), const_r_mat_4_scalar_sph::const_radial_mat_4_press_sph(), const_r_mat_4_scalar_sph::const_radial_mat_4_scalar_sph(), const_r_mat_4_vector_sph::const_radial_mat_vort_2step(), t_sph_comm_table_from_fft::copy_1comp_rtp_fft_to_send(), t_sph_comm_table_from_fft::copy_all_rtp_fft_to_send(), copy_nodal_fld_4_sph_trans::copy_nod_tsr_from_trans_wpole(), copy_nodal_fld_4_sph_trans::copy_nod_tsr_to_sph_trans(), copy_nodal_fld_4_sph_trans::copy_nod_vec_from_trans_wpole(), copy_nodal_fld_4_sph_trans::copy_nod_vec_to_sph_trans(), set_comm_table_rtp_fftw::copy_rtp_comp_fftw_to_send(), set_size_4_smp_types::count_edge_size_smp_type(), set_size_4_smp_types::count_ele_4_smp_mesh_type(), set_smp_4_group_types::count_grp_type_smp(), set_patches_for_psf::count_iso_patches(), set_size_4_smp_types::count_node_4_smp_mesh_type(), set_psf_nodes_4_by_surf_grp::count_node_at_node_on_grp(), set_nodes_for_psf::count_nodes_4_iso(), count_num_sph_smp::count_num_rj_smp(), count_num_sph_smp::count_num_rlm_smp(), count_num_sph_smp::count_num_rtm_smp(), count_num_sph_smp::count_num_rtp_smp(), set_size_4_smp_types::count_overlap_edge(), set_size_4_smp_types::count_overlap_ele(), set_size_4_smp_types::count_overlap_surf(), set_nodal_field_for_psf::count_position_4_psf(), set_psf_nodes_4_by_surf_grp::count_position_4_psf_grp(), set_patches_for_psf::count_psf_patches(), t_field_matrices_4_legendre::count_size_of_field_mat_omp(), t_legendre_work_on_the_fly::count_size_of_field_mat_otfly(), t_legendre_work_testlooop::count_size_of_field_mat_test(), set_smp_4_group_types::count_surf_grp_type_smp(), set_size_4_smp_types::count_surf_size_smp_type(), t_legendre_work_testlooop::dealloc_leg_sym_mat_both(), t_legendre_work_sym_mat_jt::dealloc_leg_sym_mat_jt(), t_legendre_work_on_the_fly::dealloc_leg_sym_mat_otfly(), t_legendre_work_sym_mat_jt::dealloc_leg_sym_mat_tj(), t_legendre_work_sym_mat_jt::dealloc_sym_leg_omp_mat_jt(), t_legendre_work_sym_mat_jt::dealloc_sym_leg_omp_mat_tj(), t_sph_component_fftw::finalize_sph_component_fftw(), t_sph_field_fftw::finalize_sph_field_fftw(), t_sph_single_fftw::finalize_sph_single_fftw(), t_legendre_work_sym_mat_jt::init_each_sym_leg_omp_mat_jt(), t_legendre_work_sym_mat_jt::init_each_sym_leg_omp_mat_tj(), t_leg_trans_sym_matmul_big::init_leg_sym_matmul_big(), t_leg_trans_sym_matmul_big::init_leg_sym_matmul_big2(), t_legendre_work_testlooop::init_legendre_sym_mat_both(), t_legendre_work_sym_mat_jt::init_legendre_sym_mat_jt(), t_legendre_work_on_the_fly::init_legendre_sym_mat_otfly(), t_legendre_work_sym_mat_jt::init_legendre_sym_mat_tj(), pole_sph_transform::init_pole_grids(), sph_prt_domain_fftpack5::init_prt_domain_fftpack5(), sph_prt_fftpack5::init_prt_fftpack5(), sph_prt_fftw::init_prt_fftw(), sph_prt_domain_fftw::init_prt_field_fftw(), sph_rtp_fftw::init_rtp_fftw(), sph_rtp_domain_fftw::init_rtp_field_fftw(), t_sph_component_fftpack5::init_sph_comp_fftpack5(), t_sph_component_fftw::init_sph_component_fftw(), t_sph_domain_fftpack5::init_sph_domain_fftpack5(), t_sph_fftpack5::init_sph_fftpack5(), t_sph_single_fftpack5::init_sph_single_fftpack5(), t_sph_single_fftw::init_sph_single_fftw(), circle_transform_single::initialize_circle_transform(), legendre_bwd_trans_symmetry::leg_bwd_trans_scalar_sym_org(), legendre_bwd_trans_sym_spin::leg_bwd_trans_scalar_sym_spin(), legendre_bwd_trans_symmetry::leg_bwd_trans_vector_sym_org(), legendre_bwd_trans_sym_spin::leg_bwd_trans_vector_sym_spin(), legendre_fwd_trans_symmetry::leg_fwd_trans_scalar_sym_org(), legendre_fwd_trans_sym_spin::leg_fwd_trans_scalar_sym_spin(), legendre_fwd_trans_symmetry::leg_fwd_trans_vector_sym_org(), legendre_fwd_trans_sym_spin::leg_fwd_trans_vector_sym_spin(), leg_bwd_trans_on_the_fly::legendre_b_trans_on_the_fly(), leg_bwd_trans_sym_mat_jt::legendre_b_trans_sym_mat_jt(), leg_bwd_trans_sym_mat_tj::legendre_b_trans_sym_mat_tj(), legendre_bwd_trans_testloop::legendre_b_trans_vector_test(), leg_fwd_trans_on_the_fly::legendre_f_trans_on_the_fly(), leg_fwd_trans_sym_mat_jt::legendre_f_trans_sym_mat_jt(), leg_fwd_trans_sym_mat_tj::legendre_f_trans_sym_mat_tj(), legendre_fwd_trans_testloop::legendre_f_trans_vector_test(), set_edge_list_for_psf::mark_edge_list_4_psf(), set_node_list_for_psf::mark_node_list_4_psf(), set_surface_list_for_psf::mark_surface_list_4_psf(), coordinate_convert_4_sph::overwrite_nodal_cyl_2_xyz_smp(), coordinate_convert_4_sph::overwrite_nodal_sph_2_cyl_smp(), coordinate_convert_4_sph::overwrite_nodal_sph_2_xyz_smp(), coordinate_convert_4_sph::overwrite_nodal_xyz_2_cyl_smp(), coordinate_convert_4_sph::overwrite_nodal_xyz_2_sph_smp(), t_const_wz_coriolis_rtp::ovwrt_rj_coef_prod_vect_smp(), sph_prt_fftw::prt_back_fftw_from_recv(), sph_prt_domain_fftpack5::prt_domain_rfftmb_from_recv(), sph_prt_domain_fftpack5::prt_domain_rfftmf_to_send(), sph_prt_domain_fftw::prt_field_back_fftw_from_recv(), sph_prt_domain_fftw::prt_field_fwd_fftw_to_send(), sph_prt_fftw::prt_fwd_fftw_to_send(), sph_prt_fftpack5::prt_rfftmb_from_recv(), sph_prt_fftpack5::prt_rfftmf_to_send(), t_fft_test_data::read_alloc_fft_test_data(), sph_rtp_fftw::rtp_back_fftw_from_recv(), sph_rtp_domain_fftpack5::rtp_domain_rfftmb_from_recv(), sph_rtp_domain_fftpack5::rtp_domain_rfftmf_to_send(), sph_rtp_domain_fftw::rtp_field_back_fftw_from_recv(), sph_rtp_domain_fftw::rtp_field_fwd_fftw_to_send(), sph_rtp_fftw::rtp_fwd_fftw_to_send(), sph_rtp_fftpack5::rtp_rfftmb_from_recv(), sph_rtp_fftpack5::rtp_rfftmf_to_send(), check_sph_mhd_openmp_size::s_check_sph_mhd_openmp_size(), set_const_4_sections::set_constant_4_iso(), set_const_4_sections::set_constant_4_psf(), set_control_platform_data::set_control_smp_def(), schmidt_poly_on_rtm_grid::set_lagender_4_rlm(), set_connects_4_surf_group::set_node_4_surf_group(), find_node_and_patch_psf::set_node_and_patch_psf(), set_node_on_edge_quad_psf::set_node_on_edge_4_linear_psf(), set_node_for_sections::set_node_on_edge_4_psf(), patch_4_psf::set_patch_4_psf(), patch_4_psf::set_psf_type_id(), search_ele_list_for_psf::set_searched_edge_list_4_psf(), search_ele_list_for_psf::set_searched_element_list_4_psf(), search_ele_list_for_psf::set_searched_node_list_4_psf(), search_ele_list_for_psf::set_searched_surface_list_4_psf(), solve_sph_fluid_crank::solve_magne_sph_crank(), solve_sph_fluid_crank::solve_pressure_by_div_v(), solve_sph_fluid_crank::solve_scalar_sph_crank(), solve_sph_fluid_crank::solve_velo_by_vort_sph_crank(), t_sph_component_fftw::sph_comp_back_fftw_from_recv(), t_sph_component_fftw::sph_comp_fwd_fftw_to_send(), t_sph_component_fftpack5::sph_comp_rfftmb_from_recv(), t_sph_component_fftpack5::sph_comp_rfftmf_to_send(), t_sph_single_fftw::sph_single_back_fftw_from_recv(), t_sph_single_fftw::sph_single_fwd_fftw_to_send(), t_sph_single_fftpack5::sph_single_rfftmb_from_recv(), t_sph_single_fftpack5::sph_single_rfftmf_to_send(), test_fftpack5(), test_fftw3(), test_single_fftw3(), sph_prt_domain_fftpack5::verify_prt_domain_fftpack5(), sph_prt_fftpack5::verify_prt_fftpack5(), t_sph_domain_fftpack5::verify_sph_domain_fftpack5(), t_sph_fftpack5::verify_sph_fftpack5(), and t_sph_single_fftw::verify_sph_single_fftw().