CALYPSO: t_gaunt_coriolis_rlm Module Reference
t_gaunt_coriolis_rlm Module Reference
Adams-Gaunt integrals for Coriolis term and coefficients for Coriolis term on f(r,l,m)
Data Types
type gaunt_coriolis_rlm
Gunat integrals of Coriolis term.
Functions/Subroutines
subroutine alloc_gaunt_coriolis_rlm (jmax_rlm, gt_cor)
subroutine alloc_coriolis_coef_tri_rlm (jmax_rlm, gt_cor)
subroutine dealloacte_gaunt_coriolis_rlm (gt_cor)
subroutine dealloc_coriolis_coef_tri_rlm (gt_cor)
integer function find_local_sph_rlm_address (jmax_rlm, idx_gl_1d_rlm_j, l_gl, m_gl)
integer function find_local_radius_rlm_address (nri_rlm, idx_gl_1d_rlm_r, kr_gl)
Detailed Description
Adams-Gaunt integrals for Coriolis term and coefficients for Coriolis term on f(r,l,m)
      subroutine alloc_gaunt_coriolis_rlm(jmax_rlm, gt_cor)
      subroutine alloc_coriolis_coef_tri_rlm(jmax_rlm, gt_cor)
      subroutine dealloacte_gaunt_coriolis_rlm
      subroutine dealloc_coriolis_coef_tri_rlm
      integer function find_local_sph_rlm_address(jmax_rlm,           &
     &       idx_gl_1d_rlm_j, l_gl, m_gl)
      integer function find_local_radius_rlm_address(nri_rlm,         &
     &       idx_gl_1d_rlm_r, kr_gl)
*************************************************
*
*  Rotation of the Coriolos term
*     (wss) = wss(jc,1,j3)*w*dyb/r**2
*            + wss(jc,2,j3)*dw*yb/r**2
*
*     (wts) = wts(j3)*w*yb/r**2
*
*     (wst) = wst(1,j3)*(dw*dyb/r**2 + w*d2yb/r**2 - 2*w*dyb/r**3)
*            + wst(2,j3)*(d2w/r**2 - 2*dw/r**3)*yb
*
*     (wtt) = wtt(jc,1,j3)*dw*yb/r**2
*            + wtt(jc,2,j3)*w*(dyb/r**2 - 2*yb/r**3)
*
*   Divergence of the Coriolis term
*     (wsd) = wsd(jc,1,j3)*w*wsb/r**4
*            + wsd(jc,2,j3)*dw*dwsb/r**2
*     (wtd) = wtd(j3)*dw*dwtb/r**2
*
*  Radial componenet of the Coriolis term
*     (wsr) = wsr(jc,1,j3)*dw*dusb/r**2
*     (wtr) = wtr(j3)*dw*wtb/r**2
*************************************************
*
*************************************************
*
*     wss(jc,1,j3) = sw_rlm(jc,1,j3)
*     wss(jc,2,j3) = sw_rlm(jc,2,j3)
*     wts(jc,j3)   = sw_rlm(jc,3,j3)
*     wst(jc,1,j3) = tw_rlm(jc,1,j3)
*     wst(jc,2,j3) = tw_rlm(jc,2,j3)
*     wtt(jc,1,j3) = tw_rlm(jc,3,j3)
*     wtt(jc,2,j3) = tw_rlm(jc,4,j3)
*
*     wsd(jc,1,j3) = sd_rlm(jc,1,j3)
*     wsd(jc,2,j3) = sd_rlm(jc,2,j3)
*     wtd(jc,j3)   = td_rlm(jc,j3)
*
*     wsr(jc,j3) =   sr_rlm(jc,j3)
*     wtr(jc,j3) =   tr_rlm(jc,j3)
*
*************************************************
*
*************************************************************
*
*      gk_cor(j3,jk,2) : gaunt integral for Coriolis term
*              jgi_rlm(j3,1) : index for gi_rlm(j3,1)
*              jgi_rlm(j3,2) : index for gi_rlm(j3,2)
*      ei_rlm(j3,1) : elsasser integral for Coriolis term
*              jei_rlm(j3,1) : index for ei_rlm(j3,1)
*
*************************************************************
*
*******************************************************************
*                                                                 *
*  Adams - Gaunt integrals                                        *
*                                                                 *
*  (m1,m2,m3)  //  (m1)   (m2)   (m3)                             *
* Ki         = || Y    * Y    * Y     sin(theta) d(theta)d(phi)   *
*  (l1,l2,l3)  //  (l1)   (l2)   (l3)                             *
*                                                                 *
*                            (m2)        (m3)                     *
*  (m1,m2,m3)  //  (m1)    dy(l2)      dy(l3)                     *
* Li         = || Y    *[ -------- * ----------                   *
*  (l1,l2,l3)  //  (l1)   d(theta)    d(phi)                      *
*                                                                 *
*                    (m2)        (m3)                             *
*                  dy(l2)      dy(l3)                             *
*              - ---------- * -------- ] d(theta)d(phi)           *
*                  d(phi)     d(theta)                            *
*                                                                 *
*  where                                                          *
*                   (m)   (m)  | sin(m*phi) |                     *
*                  Y   = P   * |   1        |                     *
*                   (l)   (l)  | cos(m*phi) |                     *
*                                                                 *
*                         (m)     2(l-m)!     1                   *
*                        P   = [----------]**--- * P(l,m)         *
*                         (l)      (l+m)!     2                   *
*                         (0)                                     *
*                        P   =           P(l,0)                   *
*                         (l)                                     *
*                                                                 *
*******************************************************************
Function/Subroutine Documentation
alloc_coriolis_coef_tri_rlm()
subroutine t_gaunt_coriolis_rlm::alloc_coriolis_coef_tri_rlm (integer(kind = kint), intent(in) jmax_rlm, type(gaunt_coriolis_rlm), intent(inout) gt_cor)
Definition at line 174 of file t_gaunt_coriolis_rlm.f90.
References m_constants::zero.
Referenced by t_coriolis_terms_rlm::init_sum_coriolis_rlm().
alloc_gaunt_coriolis_rlm()
subroutine t_gaunt_coriolis_rlm::alloc_gaunt_coriolis_rlm (integer(kind = kint), intent(in) jmax_rlm, type(gaunt_coriolis_rlm), intent(inout) gt_cor)
Definition at line 153 of file t_gaunt_coriolis_rlm.f90.
Referenced by t_coriolis_terms_rlm::init_sum_coriolis_rlm().
dealloacte_gaunt_coriolis_rlm()
subroutine t_gaunt_coriolis_rlm::dealloacte_gaunt_coriolis_rlm (type(gaunt_coriolis_rlm), intent(inout) gt_cor)
Definition at line 203 of file t_gaunt_coriolis_rlm.f90.
dealloc_coriolis_coef_tri_rlm()
subroutine t_gaunt_coriolis_rlm::dealloc_coriolis_coef_tri_rlm (type(gaunt_coriolis_rlm), intent(inout) gt_cor)
Definition at line 215 of file t_gaunt_coriolis_rlm.f90.
find_local_radius_rlm_address()
integer function t_gaunt_coriolis_rlm::find_local_radius_rlm_address (integer(kind = kint), intent(in) nri_rlm, integer(kind = kint), dimension(nri_rlm), intent(in) idx_gl_1d_rlm_r, integer(kind = kint), intent(in) kr_gl)
Definition at line 251 of file t_gaunt_coriolis_rlm.f90.
Referenced by t_coriolis_terms_rlm::init_sum_coriolis_rlm().
find_local_sph_rlm_address()
integer function t_gaunt_coriolis_rlm::find_local_sph_rlm_address (integer(kind = kint), intent(in) jmax_rlm, integer(kind = kint), dimension(jmax_rlm,3), intent(in) idx_gl_1d_rlm_j, integer(kind = kint), intent(in) l_gl, integer(kind = kint), intent(in) m_gl)
Definition at line 228 of file t_gaunt_coriolis_rlm.f90.
Referenced by interact_coriolis_rlm::cal_gaunt_coriolis_rlm(), t_coriolis_terms_rlm::init_sum_coriolis_rlm(), and sum_coriolis_terms_rlm::sum_r_coriolis_bc_rlm_10().