CALYPSO: count_num_sph_smp Module Reference
count_num_sph_smp Module Reference
SEt SMP parameters for spectr data.
Functions/Subroutines
subroutine s_count_num_sph_smp (sph_rtp, sph_rtm, sph_rlm, sph_rj, ierr)
subroutine count_num_rtp_smp (sph_rtp, ierr)
subroutine count_num_rtm_smp (sph_rtm, ierr)
subroutine count_num_rlm_smp (sph_rlm, ierr)
subroutine count_num_rj_smp (sph_rj, ierr)
Variables
character(len=kchara), parameter e_message_rsmp = '# of r-grid for SPH trans. should be more than SMP threads'
Error message.
Detailed Description
SEt SMP parameters for spectr data.
      subroutine s_count_num_sph_smp                                  &
     &         (sph_rtp, sph_rtm, sph_rlm, sph_rj, ierr)
        type(sph_rtp_grid), intent(inout) :: sph_rtp
        type(sph_rtm_grid), intent(inout) :: sph_rtm
        type(sph_rlm_grid), intent(inout) :: sph_rlm
        type(sph_rj_grid),  intent(inout) :: sph_rj
Parameters
ierr Error flag
Function/Subroutine Documentation
count_num_rj_smp()
subroutine count_num_sph_smp::count_num_rj_smp (type(sph_rj_grid), intent(inout) sph_rj, integer(kind = kint), intent(inout) ierr)
Definition at line 168 of file count_num_sph_smp.f90.
References t_spheric_rj_data::alloc_rj_param_smp(), cal_minmax_and_stacks::count_number_4_smp(), m_constants::ione, and m_machine_parameter::np_smp.
Referenced by output_gen_sph_grid_modes::load_local_rj_mesh_4_merge(), s_count_num_sph_smp(), parallel_load_data_4_sph::sph_index_flags_and_params(), and parallel_load_data_4_sph::sph_rj_index_flags_and_params().
count_num_rlm_smp()
subroutine count_num_sph_smp::count_num_rlm_smp (type(sph_rlm_grid), intent(inout) sph_rlm, integer(kind = kint), intent(inout) ierr)
Definition at line 138 of file count_num_sph_smp.f90.
References t_spheric_rlm_data::alloc_rlm_param_smp(), cal_minmax_and_stacks::count_number_4_smp(), m_constants::ione, and m_machine_parameter::np_smp.
Referenced by s_count_num_sph_smp(), and parallel_load_data_4_sph::sph_index_flags_and_params().
count_num_rtm_smp()
subroutine count_num_sph_smp::count_num_rtm_smp (type(sph_rtm_grid), intent(inout) sph_rtm, integer(kind = kint), intent(inout) ierr)
Definition at line 101 of file count_num_sph_smp.f90.
References t_spheric_rtm_data::alloc_rtm_param_smp(), cal_minmax_and_stacks::count_number_4_smp(), m_constants::ione, and m_machine_parameter::np_smp.
Referenced by s_count_num_sph_smp(), and parallel_load_data_4_sph::sph_index_flags_and_params().
count_num_rtp_smp()
subroutine count_num_sph_smp::count_num_rtp_smp (type(sph_rtp_grid), intent(inout) sph_rtp, integer(kind = kint), intent(inout) ierr)
Definition at line 63 of file count_num_sph_smp.f90.
References t_spheric_rtp_data::alloc_rtp_param_smp(), cal_minmax_and_stacks::count_number_4_smp(), m_constants::ione, and m_machine_parameter::np_smp.
Referenced by s_count_num_sph_smp(), and parallel_load_data_4_sph::sph_index_flags_and_params().
s_count_num_sph_smp()
subroutine count_num_sph_smp::s_count_num_sph_smp (type(sph_rtp_grid), intent(inout) sph_rtp, type(sph_rtm_grid), intent(inout) sph_rtm, type(sph_rlm_grid), intent(inout) sph_rlm, type(sph_rj_grid), intent(inout) sph_rj, integer(kind = kint), intent(inout) ierr)
Definition at line 43 of file count_num_sph_smp.f90.
References count_num_rj_smp(), count_num_rlm_smp(), count_num_rtm_smp(), and count_num_rtp_smp().
Variable Documentation
e_message_rsmp
character(len=kchara), parameter count_num_sph_smp::e_message_rsmp = '# of r-grid for SPH trans. should be more than SMP threads'
Error message.
Definition at line 34 of file count_num_sph_smp.f90.