CALYPSO: gz_mpi_mesh_data_io_b Module Reference
gz_mpi_mesh_data_io_b Module Reference
Routines for gzipped binary mesh data IO.
Functions/Subroutines
subroutine gz_mpi_write_geometry_data_b (IO_param, mesh_IO)
subroutine gz_mpi_write_mesh_groups_b (IO_param, mesh_group_IO)
subroutine gz_mpi_read_num_node_b (IO_param, mesh_IO)
subroutine gz_mpi_read_num_node_ele_b (IO_param, mesh_IO)
subroutine gz_mpi_read_geometry_data_b (IO_param, mesh_IO)
subroutine gz_mpi_read_mesh_groups_b (IO_param, mesh_group_IO)
Detailed Description
Routines for gzipped binary mesh data IO.
      subroutine gz_mpi_write_geometry_data_b(IO_param, mesh_IO)
      subroutine gz_mpi_write_mesh_groups_b(IO_param, mesh_group_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(mesh_geometry), intent(in) :: mesh_IO
        type(mesh_groups), intent(in) ::   mesh_group_IO
      subroutine gz_mpi_read_num_node_b(IO_param, mesh_IO)
      subroutine gz_mpi_read_num_node_ele_b(IO_param, mesh_IO)
      subroutine gz_mpi_read_geometry_data_b(IO_param, mesh_IO)
      subroutine gz_mpi_read_mesh_groups_b(IO_param, mesh_group_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(mesh_geometry), intent(inout) :: mesh_IO
        type(mesh_groups), intent(inout) ::   mesh_group_IO
Function/Subroutine Documentation
gz_mpi_read_geometry_data_b()
subroutine gz_mpi_mesh_data_io_b::gz_mpi_read_geometry_data_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 123 of file gz_MPI_mesh_data_IO_b.f90.
References gz_mpi_element_connect_io_b::gz_mpi_read_ele_info_b(), gz_mpi_domain_data_io_b::gz_mpi_read_export_data_b(), gz_mpi_domain_data_io_b::gz_mpi_read_import_data_b(), and gz_mpi_read_num_node_ele_b().
Referenced by gz_mpi_mesh_file_io_b::gz_mpi_read_mesh_file_b(), and gz_mpi_mesh_file_io_b::gz_mpi_read_mesh_geometry_b().
gz_mpi_read_mesh_groups_b()
subroutine gz_mpi_mesh_data_io_b::gz_mpi_read_mesh_groups_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(mesh_groups), intent(inout) mesh_group_IO)
Definition at line 143 of file gz_MPI_mesh_data_IO_b.f90.
References gz_mpi_groups_io_b::gz_mpi_read_group_data_b(), and gz_mpi_groups_io_b::gz_mpi_read_surf_grp_data_b().
Referenced by gz_mpi_mesh_file_io_b::gz_mpi_read_mesh_file_b().
gz_mpi_read_num_node_b()
subroutine gz_mpi_mesh_data_io_b::gz_mpi_read_num_node_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 88 of file gz_MPI_mesh_data_IO_b.f90.
References gz_mpi_domain_data_io_b::gz_mpi_read_domain_info_b(), and gz_mpi_node_geometry_io_b::gz_mpi_read_number_of_node_b().
Referenced by gz_mpi_mesh_file_io_b::gz_mpi_read_node_size_b(), and gz_mpi_read_num_node_ele_b().
gz_mpi_read_num_node_ele_b()
subroutine gz_mpi_mesh_data_io_b::gz_mpi_read_num_node_ele_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 104 of file gz_MPI_mesh_data_IO_b.f90.
References gz_mpi_node_geometry_io_b::gz_mpi_read_geometry_info_b(), gz_mpi_element_connect_io_b::gz_mpi_read_num_element_b(), and gz_mpi_read_num_node_b().
Referenced by gz_mpi_read_geometry_data_b(), and gz_mpi_mesh_file_io_b::gz_mpi_read_geometry_size_b().
gz_mpi_write_geometry_data_b()
subroutine gz_mpi_mesh_data_io_b::gz_mpi_write_geometry_data_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(mesh_geometry), intent(in) mesh_IO)
Definition at line 48 of file gz_MPI_mesh_data_IO_b.f90.
References gz_mpi_domain_data_io_b::gz_mpi_write_domain_info_b(), gz_mpi_element_connect_io_b::gz_mpi_write_element_info_b(), gz_mpi_domain_data_io_b::gz_mpi_write_export_data_b(), gz_mpi_node_geometry_io_b::gz_mpi_write_geometry_info_b(), and gz_mpi_domain_data_io_b::gz_mpi_write_import_data_b().
Referenced by gz_mpi_mesh_file_io_b::gz_mpi_write_mesh_file_b().
gz_mpi_write_mesh_groups_b()
subroutine gz_mpi_mesh_data_io_b::gz_mpi_write_mesh_groups_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(mesh_groups), intent(in) mesh_group_IO)
Definition at line 66 of file gz_MPI_mesh_data_IO_b.f90.
References gz_mpi_groups_io_b::gz_mpi_write_grp_data_b(), and gz_mpi_groups_io_b::gz_mpi_write_surf_grp_data_b().
Referenced by gz_mpi_mesh_file_io_b::gz_mpi_write_mesh_file_b().