CALYPSO: m_intersection_data_1 Module Reference
m_intersection_data_1 Module Reference
Variables
integer(kind=kint), parameter, private nnod_tri = 3
integer(kind=kint), parameter nkind_etype_1 = 8
integer(kind=kint), parameter num_triangle_1 = 1
integer(kind=kint), parameter num_patch_1 = 1
integer(kind=kint), dimension(3), parameter itri_2_patch_1 = (/1, 2, 3/)
integer(kind=kint), dimension(nkind_etype_1), parameter iflag_psf_etype_1p = (/1, 2, 4, 8, 16, 32, 64, 128/)
integer(kind=kint), dimension(nkind_etype_1), parameter iflag_psf_etype_1n = (/254, 253, 251, 247, 239, 223, 191, 127/)
integer(kind=kint), dimension(nnod_tri, nkind_etype_1), parameter iedge_triangle_1p = reshape((/ 4, 1, 9, 1, 2, 10, 2, 3, 11, 3, 4, 12, 5, 8, 9, 6, 5, 10, 7, 6, 11, 8, 7, 12/), shape=(/nnod_tri,nkind_etype_1/))
integer(kind=kint), dimension(nnod_tri, nkind_etype_1), parameter iedge_triangle_1n = reshape((/ 1, 4, 9, 2, 1, 10, 3, 2, 11, 4, 3, 12, 8, 5, 9, 5, 6, 10, 6, 7, 11, 7, 8, 12/), shape=(/nnod_tri,nkind_etype_1/))
integer(kind=kint), dimension(nnod_tri, nkind_etype_1), parameter iedge_4_patch_1p = reshape((/ 4, 1, 9, 1, 2, 10, 2, 3, 11, 3, 4, 12, 5, 8, 9, 6, 5, 10, 7, 6, 11, 8, 7, 12/), shape=(/nnod_tri,nkind_etype_1/))
integer(kind=kint), dimension(nnod_tri, nkind_etype_1), parameter iedge_4_patch_1n = reshape((/ 1, 4, 9, 2, 1, 10, 3, 2, 11, 4, 3, 12, 8, 5, 9, 5, 6, 10, 6, 7, 11, 7, 8, 12/), shape=(/nnod_tri,nkind_etype_1/))
Variable Documentation
iedge_4_patch_1n
integer(kind = kint), dimension(nnod_tri,nkind_etype_1), parameter m_intersection_data_1::iedge_4_patch_1n = reshape((/ 1, 4, 9, 2, 1, 10, 3, 2, 11, 4, 3, 12, 8, 5, 9, 5, 6, 10, 6, 7, 11, 7, 8, 12/), shape=(/nnod_tri,nkind_etype_1/))
Definition at line 77 of file m_intersection_data_1.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
iedge_4_patch_1p
integer(kind = kint), dimension(nnod_tri,nkind_etype_1), parameter m_intersection_data_1::iedge_4_patch_1p = reshape((/ 4, 1, 9, 1, 2, 10, 2, 3, 11, 3, 4, 12, 5, 8, 9, 6, 5, 10, 7, 6, 11, 8, 7, 12/), shape=(/nnod_tri,nkind_etype_1/))
Definition at line 70 of file m_intersection_data_1.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
iedge_triangle_1n
integer(kind = kint), dimension(nnod_tri,nkind_etype_1), parameter m_intersection_data_1::iedge_triangle_1n = reshape((/ 1, 4, 9, 2, 1, 10, 3, 2, 11, 4, 3, 12, 8, 5, 9, 5, 6, 10, 6, 7, 11, 7, 8, 12/), shape=(/nnod_tri,nkind_etype_1/))
Definition at line 62 of file m_intersection_data_1.f90.
iedge_triangle_1p
integer(kind = kint), dimension(nnod_tri,nkind_etype_1), parameter m_intersection_data_1::iedge_triangle_1p = reshape((/ 4, 1, 9, 1, 2, 10, 2, 3, 11, 3, 4, 12, 5, 8, 9, 6, 5, 10, 7, 6, 11, 8, 7, 12/), shape=(/nnod_tri,nkind_etype_1/))
Definition at line 55 of file m_intersection_data_1.f90.
iflag_psf_etype_1n
integer(kind = kint), dimension(nkind_etype_1), parameter m_intersection_data_1::iflag_psf_etype_1n = (/254, 253, 251, 247, 239, 223, 191, 127/)
Definition at line 50 of file m_intersection_data_1.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
iflag_psf_etype_1p
integer(kind = kint), dimension(nkind_etype_1), parameter m_intersection_data_1::iflag_psf_etype_1p = (/1, 2, 4, 8, 16, 32, 64, 128/)
Definition at line 47 of file m_intersection_data_1.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
itri_2_patch_1
integer(kind = kint), dimension(3), parameter m_intersection_data_1::itri_2_patch_1 = (/1, 2, 3/)
Definition at line 44 of file m_intersection_data_1.f90.
nkind_etype_1
integer(kind = kint), parameter m_intersection_data_1::nkind_etype_1 = 8
Definition at line 41 of file m_intersection_data_1.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
nnod_tri
integer(kind = kint), parameter, private m_intersection_data_1::nnod_tri = 3 private
Definition at line 39 of file m_intersection_data_1.f90.
num_patch_1
integer(kind = kint), parameter m_intersection_data_1::num_patch_1 = 1
Definition at line 43 of file m_intersection_data_1.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
num_triangle_1
integer(kind = kint), parameter m_intersection_data_1::num_triangle_1 = 1
Definition at line 42 of file m_intersection_data_1.f90.