CALYPSO: /home/takumi kera/calypso/src/programs/TESTS/FFT_test/test_FFTW3.f90 File Reference
test_FFTW3.f90 File Reference
Functions/Subroutines
program test_fftw3
Function/Subroutine Documentation
test_fftw3()
program test_fftw3
Definition at line 2 of file test_FFTW3.f90.
References t_fft_test_data::dealloc_fft_test_data(), t_multi_fftw_wrapper::fftw_mul_backward_type(), t_multi_fftw_wrapper::fftw_mul_forward_type(), m_machine_parameter::iflag_debug, t_fft_test_data::init_fft_test_data(), t_multi_fftw_wrapper::init_fftw_mul_type(), m_machine_parameter::np_smp, and t_fft_test_data::write_fft_test_data().