CALYPSO: vtk_file_io Module Reference
vtk_file_io Module Reference
Output VTK file.
Functions/Subroutines
subroutine write_parallel_vtk_file (id_rank, nprocs, istep, file_prefix)
subroutine write_vtk_file (id_rank, file_name, ucd)
subroutine write_vtk_phys (id_rank, file_name, ucd)
subroutine write_vtk_grid (id_rank, file_name, ucd)
subroutine read_vtk_file (id_rank, file_name, ucd)
subroutine read_vtk_phys (id_rank, file_name, ucd)
subroutine read_vtk_grid (id_rank, file_name, ucd)
subroutine read_alloc_vtk_file (id_rank, file_name, ucd)
subroutine read_alloc_vtk_phys (id_rank, file_name, ucd)
subroutine read_alloc_vtk_grid (id_rank, file_name, ucd)
Variables
integer(kind=kint), parameter, private id_vtk_file = 16
file ID for VTK file
Detailed Description
Output VTK file.
      subroutine write_parallel_vtk_file                              &
     &         (id_rank, nprocs, istep, file_prefix)
      subroutine write_vtk_file(id_rank, file_name, ucd)
      subroutine write_vtk_phys(id_rank, file_name, ucd)
      subroutine write_vtk_grid(id_rank, file_name, ucd)
        integer, intent(in) :: id_rank
        character(len=kchara), intent(in) :: file_name
        type(ucd_data), intent(in) :: ucd
      subroutine read_vtk_file(id_rank, file_name, ucd)
      subroutine read_vtk_phys(id_rank, file_name, ucd)
      subroutine read_vtk_grid(id_rank, file_name, ucd)
        integer, intent(in) :: id_rank
        character(len=kchara), intent(in) :: file_name
        type(ucd_data), intent(inout) :: ucd
      subroutine read_alloc_vtk_file(id_rank, file_name, ucd)
      subroutine read_alloc_vtk_phys(id_rank, file_name, ucd)
      subroutine read_alloc_vtk_grid(id_rank, file_name, ucd)
        integer, intent(in) :: id_rank
        character(len=kchara), intent(in) :: file_name
        type(ucd_data), intent(inout) :: ucd
Function/Subroutine Documentation
read_alloc_vtk_file()
subroutine vtk_file_io::read_alloc_vtk_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(ucd_data), intent(inout) ucd)
Definition at line 217 of file vtk_file_IO.f90.
References m_machine_parameter::i_debug, id_vtk_file, udt_to_vtk_data_io::read_alloc_ucd_mesh_from_vtk(), and udt_to_vtk_data_io::read_alloc_udt_field_from_vtk().
Referenced by ucd_io_select::sel_read_alloc_ucd_file().
read_alloc_vtk_grid()
subroutine vtk_file_io::read_alloc_vtk_grid (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(ucd_data), intent(inout) ucd)
Definition at line 256 of file vtk_file_IO.f90.
References m_machine_parameter::i_debug, id_vtk_file, and udt_to_vtk_data_io::read_alloc_ucd_mesh_from_vtk().
Referenced by ucd_io_select::sel_read_alloc_ucd_file().
read_alloc_vtk_phys()
subroutine vtk_file_io::read_alloc_vtk_phys (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(ucd_data), intent(inout) ucd)
Definition at line 237 of file vtk_file_IO.f90.
References m_machine_parameter::i_debug, id_vtk_file, and udt_to_vtk_data_io::read_alloc_udt_field_from_vtk().
Referenced by ucd_io_select::sel_read_alloc_ucd_file(), ucd_io_select::sel_read_alloc_udt_file(), and ucd_io_select::sel_read_udt_param().
read_vtk_file()
subroutine vtk_file_io::read_vtk_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(ucd_data), intent(inout) ucd)
Definition at line 158 of file vtk_file_IO.f90.
References m_machine_parameter::i_debug, id_vtk_file, udt_to_vtk_data_io::read_ucd_mesh_from_vtk(), and udt_to_vtk_data_io::read_udt_field_from_vtk().
Referenced by ucd_io_select::sel_read_ucd_file().
read_vtk_grid()
subroutine vtk_file_io::read_vtk_grid (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(ucd_data), intent(inout) ucd)
Definition at line 197 of file vtk_file_IO.f90.
References m_machine_parameter::i_debug, id_vtk_file, and udt_to_vtk_data_io::read_ucd_mesh_from_vtk().
Referenced by ucd_io_select::sel_read_ucd_file().
read_vtk_phys()
subroutine vtk_file_io::read_vtk_phys (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(ucd_data), intent(inout) ucd)
Definition at line 178 of file vtk_file_IO.f90.
References m_machine_parameter::i_debug, id_vtk_file, and udt_to_vtk_data_io::read_udt_field_from_vtk().
Referenced by ucd_io_select::sel_read_ucd_file(), and ucd_io_select::sel_read_udt_file().
write_parallel_vtk_file()
subroutine vtk_file_io::write_parallel_vtk_file (integer, intent(in) id_rank, integer, intent(in) nprocs, integer(kind = kint), intent(in) istep, character(len=kchara), intent(in) file_prefix)
Definition at line 56 of file vtk_file_IO.f90.
References set_parallel_file_name::add_int_suffix(), set_ucd_extensions::add_pvtk_extension(), set_parallel_file_name::delete_directory_name(), id_vtk_file, and set_ucd_file_names::set_parallel_vtk_file_name().
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_file().
write_vtk_file()
subroutine vtk_file_io::write_vtk_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(ucd_data), intent(in) ucd)
Definition at line 99 of file vtk_file_IO.f90.
References m_machine_parameter::i_debug, id_vtk_file, udt_to_vtk_data_io::write_ucd_field_to_vtk(), and udt_to_vtk_data_io::write_ucd_mesh_to_vtk().
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_file(), ucd_io_select::sel_write_ucd_file(), and ucd_io_select::sel_write_udt_file().
write_vtk_grid()
subroutine vtk_file_io::write_vtk_grid (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(ucd_data), intent(in) ucd)
Definition at line 138 of file vtk_file_IO.f90.
References m_machine_parameter::i_debug, id_vtk_file, and udt_to_vtk_data_io::write_ucd_mesh_to_vtk().
Referenced by ucd_io_select::sel_write_grd_file().
write_vtk_phys()
subroutine vtk_file_io::write_vtk_phys (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(ucd_data), intent(in) ucd)
Definition at line 119 of file vtk_file_IO.f90.
References m_machine_parameter::i_debug, id_vtk_file, and udt_to_vtk_data_io::write_ucd_field_to_vtk().
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_file(), ucd_io_select::sel_write_ucd_file(), and ucd_io_select::sel_write_udt_file().
Variable Documentation
id_vtk_file
integer(kind = kint), parameter, private vtk_file_io::id_vtk_file = 16 private
file ID for VTK file
Definition at line 48 of file vtk_file_IO.f90.
Referenced by read_alloc_vtk_file(), read_alloc_vtk_grid(), read_alloc_vtk_phys(), read_vtk_file(), read_vtk_grid(), read_vtk_phys(), write_parallel_vtk_file(), write_vtk_file(), write_vtk_grid(), and write_vtk_phys().