CALYPSO: simple_sph_spectr_data_io Module Reference
simple_sph_spectr_data_io Module Reference
Time spectrum data IO for utilities.
Functions/Subroutines
integer(kind=kint) function read_volume_pwr_sph (id_file, sph_IN)
integer(kind=kint) function read_volume_spectr_sph (id_file, sph_IN)
integer(kind=kint) function read_layer_pwr_sph (id_file, sph_IN)
integer(kind=kint) function read_layer_spectr_sph (id_file, sph_IN)
subroutine write_vol_sph_data (id_file, sph_IN)
subroutine write_vol_spectr_data (id_file, sph_IN)
subroutine write_layer_sph_data (id_file, sph_IN)
subroutine write_layer_spectr_data (id_file, sph_IN)
integer(kind=kint) function read_layer_pwr_sph_old (id_file, sph_IN)
integer(kind=kint) function read_layer_spectr_sph_old (id_file, sph_IN)
Detailed Description
Time spectrum data IO for utilities.
      integer(kind = kint) function  read_volume_pwr_sph              &
     &                            (id_file, sph_IN)
      integer(kind = kint) function  read_volume_spectr_sph           &
     &                            (id_file, sph_IN)
      integer(kind = kint) function  read_layer_pwr_sph               &
     &                            (id_file, sph_IN)
      integer(kind = kint) function  read_layer_spectr_sph            &
     &                            (id_file, sph_IN)
        type(read_sph_spectr_data), intent(inout) :: sph_IN
      subroutine write_vol_sph_data(id_file, sph_IN)
      subroutine write_vol_spectr_data(id_file, sph_IN)
      subroutine write_layer_sph_data(id_file, sph_IN)
      subroutine write_layer_spectr_data(id_file, sph_IN)
        type(read_sph_spectr_data), intent(in) :: sph_IN
      integer(kind = kint) function  read_layer_pwr_sph_old           &
     &                            (id_file, sph_IN)
      integer(kind = kint) function  read_layer_spectr_sph_old        &
     &                            (id_file, sph_IN)
        type(read_sph_spectr_data), intent(inout) :: sph_IN
Function/Subroutine Documentation
read_layer_pwr_sph()
integer(kind = kint) function simple_sph_spectr_data_io::read_layer_pwr_sph (integer(kind = kint), intent(in) id_file, type(read_sph_spectr_data), intent(inout) sph_IN)
Definition at line 92 of file simple_sph_spectr_data_IO.f90.
Referenced by sph_mean_square_io_select::select_input_sph_pwr_data().
read_layer_pwr_sph_old()
integer(kind = kint) function simple_sph_spectr_data_io::read_layer_pwr_sph_old (integer(kind = kint), intent(in) id_file, type(read_sph_spectr_data), intent(inout) sph_IN)
Definition at line 225 of file simple_sph_spectr_data_IO.f90.
Referenced by sph_mean_square_io_select::select_input_sph_pwr_data().
read_layer_spectr_sph()
integer(kind = kint) function simple_sph_spectr_data_io::read_layer_spectr_sph (integer(kind = kint), intent(in) id_file, type(read_sph_spectr_data), intent(inout) sph_IN)
Definition at line 117 of file simple_sph_spectr_data_IO.f90.
Referenced by sph_mean_square_io_select::select_input_sph_pwr_data().
read_layer_spectr_sph_old()
integer(kind = kint) function simple_sph_spectr_data_io::read_layer_spectr_sph_old (integer(kind = kint), intent(in) id_file, type(read_sph_spectr_data), intent(inout) sph_IN)
Definition at line 250 of file simple_sph_spectr_data_IO.f90.
Referenced by sph_mean_square_io_select::select_input_sph_pwr_data().
read_volume_pwr_sph()
integer(kind = kint) function simple_sph_spectr_data_io::read_volume_pwr_sph (integer(kind = kint), intent(in) id_file, type(read_sph_spectr_data), intent(inout) sph_IN)
Definition at line 48 of file simple_sph_spectr_data_IO.f90.
Referenced by sph_mean_square_io_select::select_input_sph_pwr_data().
read_volume_spectr_sph()
integer(kind = kint) function simple_sph_spectr_data_io::read_volume_spectr_sph (integer(kind = kint), intent(in) id_file, type(read_sph_spectr_data), intent(inout) sph_IN)
Definition at line 68 of file simple_sph_spectr_data_IO.f90.
Referenced by sph_mean_square_io_select::select_input_sph_pwr_data().
write_layer_spectr_data()
subroutine simple_sph_spectr_data_io::write_layer_spectr_data (integer(kind = kint), intent(in) id_file, type(read_sph_spectr_data), intent(in) sph_IN)
Definition at line 202 of file simple_sph_spectr_data_IO.f90.
Referenced by sph_mean_square_io_select::select_output_sph_pwr_data().
write_layer_sph_data()
subroutine simple_sph_spectr_data_io::write_layer_sph_data (integer(kind = kint), intent(in) id_file, type(read_sph_spectr_data), intent(in) sph_IN)
Definition at line 182 of file simple_sph_spectr_data_IO.f90.
Referenced by sph_mean_square_io_select::select_output_sph_pwr_data().
write_vol_spectr_data()
subroutine simple_sph_spectr_data_io::write_vol_spectr_data (integer(kind = kint), intent(in) id_file, type(read_sph_spectr_data), intent(in) sph_IN)
Definition at line 162 of file simple_sph_spectr_data_IO.f90.
Referenced by sph_mean_square_io_select::select_output_sph_pwr_data().
write_vol_sph_data()
subroutine simple_sph_spectr_data_io::write_vol_sph_data (integer(kind = kint), intent(in) id_file, type(read_sph_spectr_data), intent(in) sph_IN)
Definition at line 145 of file simple_sph_spectr_data_IO.f90.
Referenced by sph_mean_square_io_select::select_output_sph_pwr_data().