CALYPSO: sph_file_io_select Module Reference
sph_file_io_select Module Reference
Spectr data IO selector.
Functions/Subroutines
subroutine set_sph_mesh_file_fmt_prefix (iflag_fmt, file_head, file_param)
subroutine sel_read_geom_rtp_file (id_rank, file_param, sph_file, ierr)
subroutine sel_read_spectr_rj_file (id_rank, file_param, sph_file, ierr)
subroutine sel_read_geom_rtm_file (id_rank, file_param, sph_file, ierr)
subroutine sel_read_modes_rlm_file (id_rank, file_param, sph_file, ierr)
subroutine sel_write_geom_rtp_file (id_rank, file_param, sph_file, ierr)
subroutine sel_write_spectr_modes_rj_file (id_rank, file_param, sph_file, ierr)
subroutine sel_write_geom_rtm_file (id_rank, file_param, sph_file, ierr)
subroutine sel_write_modes_rlm_file (id_rank, file_param, sph_file, ierr)
logical function check_exsist_rtp_file (id_rank, file_param)
logical function check_exsist_rj_file (id_rank, file_param)
logical function check_exsist_rtm_file (id_rank, file_param)
logical function check_exsist_rlm_file (id_rank, file_param)
Variables
integer(kind=kint), parameter, private mesh_file_id = 14
character(len=kchara), private sph_file_name
Detailed Description
Spectr data IO selector.
      subroutine set_sph_mesh_file_fmt_prefix                         &
     &         (iflag_fmt, file_head, file_param)
      subroutine sel_read_geom_rtp_file                               &
     &         (id_rank, file_param, sph_file, ierr)
      subroutine sel_read_spectr_rj_file                              &
     &         (id_rank, file_param, sph_file, ierr)
      subroutine sel_read_geom_rtm_file                               &
     &         (id_rank, file_param, sph_file, ierr)
      subroutine sel_read_modes_rlm_file                              &
     &         (id_rank, file_param, sph_file, ierr)
        type(sph_file_data_type), intent(inout) :: sph_file
      subroutine sel_write_geom_rtp_file                              &
     &         (id_rank, file_param, sph_file, ierr)
      subroutine sel_write_spectr_modes_rj_file                       &
     &         (id_rank, sph_file, ierr)
      subroutine sel_write_geom_rtm_file                              &
     &         (id_rank, file_param, sph_file, ierr)
      subroutine sel_write_modes_rlm_file                             &
     &         (id_rank, file_param, sph_file, ierr)
        type(sph_file_data_type), intent(in) :: sph_file
      logical function check_exsist_rtp_file(id_rank, file_param)
      logical function check_exsist_rj_file(id_rank, file_param)
      logical function check_exsist_rtm_file(id_rank, file_param)
      logical function check_exsist_rlm_file(id_rank, file_param)
Parameters
id_rank Process ID
file_name file name for IO (.gz is appended in this module)
Function/Subroutine Documentation
check_exsist_rj_file()
logical function sph_file_io_select::check_exsist_rj_file (integer, intent(in) id_rank, type(field_io_params), intent(in) file_param)
Definition at line 376 of file sph_file_IO_select.F90.
References delete_data_files::check_file_exist(), set_mesh_file_names::set_sph_rj_file_name(), and sph_file_name.
Referenced by parallel_gen_sph_grids::check_and_make_para_rj_mode(), t_check_and_make_sph_mesh::check_and_make_sph_mesh(), and t_check_and_make_sph_mesh::check_and_make_sph_rj_mode().
check_exsist_rlm_file()
logical function sph_file_io_select::check_exsist_rlm_file (integer, intent(in) id_rank, type(field_io_params), intent(in) file_param)
Definition at line 408 of file sph_file_IO_select.F90.
References delete_data_files::check_file_exist(), set_mesh_file_names::set_sph_rlm_file_name(), and sph_file_name.
Referenced by t_check_and_make_sph_mesh::check_and_make_sph_mesh(), and t_check_and_make_sph_mesh::check_and_make_sph_rj_mode().
check_exsist_rtm_file()
logical function sph_file_io_select::check_exsist_rtm_file (integer, intent(in) id_rank, type(field_io_params), intent(in) file_param)
Definition at line 392 of file sph_file_IO_select.F90.
References delete_data_files::check_file_exist(), set_mesh_file_names::set_sph_rtm_file_name(), and sph_file_name.
Referenced by t_check_and_make_sph_mesh::check_and_make_sph_mesh(), and t_check_and_make_sph_mesh::check_and_make_sph_rj_mode().
check_exsist_rtp_file()
logical function sph_file_io_select::check_exsist_rtp_file (integer, intent(in) id_rank, type(field_io_params), intent(in) file_param)
Definition at line 360 of file sph_file_IO_select.F90.
References delete_data_files::check_file_exist(), set_mesh_file_names::set_sph_rtp_file_name(), and sph_file_name.
Referenced by t_check_and_make_sph_mesh::check_and_make_sph_mesh(), and t_check_and_make_sph_mesh::check_and_make_sph_rj_mode().
sel_read_geom_rtm_file()
subroutine sph_file_io_select::sel_read_geom_rtm_file (integer, intent(in) id_rank, type(field_io_params), intent(in) file_param, type(sph_file_data_type), intent(inout) sph_file, integer(kind = kint), intent(inout) ierr)
Definition at line 157 of file sph_file_IO_select.F90.
References gz_sph_modes_grids_file_io::gz_read_geom_rtm_file(), gz_sph_modes_file_io_b::gz_read_geom_rtm_file_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, mesh_file_id, sph_modes_grids_file_io::read_geom_rtm_file(), sph_modes_grids_file_io_b::read_geom_rtm_file_b(), set_mesh_file_names::set_sph_rtm_file_name(), and sph_file_name.
Referenced by sph_file_mpi_io_select::sel_mpi_read_geom_rtm_file().
sel_read_geom_rtp_file()
subroutine sph_file_io_select::sel_read_geom_rtp_file (integer, intent(in) id_rank, type(field_io_params), intent(in) file_param, type(sph_file_data_type), intent(inout) sph_file, integer(kind = kint), intent(inout) ierr)
Definition at line 87 of file sph_file_IO_select.F90.
References gz_sph_modes_grids_file_io::gz_read_geom_rtp_file(), gz_sph_modes_file_io_b::gz_read_geom_rtp_file_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, mesh_file_id, sph_modes_grids_file_io::read_geom_rtp_file(), sph_modes_grids_file_io_b::read_geom_rtp_file_b(), set_mesh_file_names::set_sph_rtp_file_name(), and sph_file_name.
Referenced by sph_file_mpi_io_select::sel_mpi_read_geom_rtp_file().
sel_read_modes_rlm_file()
subroutine sph_file_io_select::sel_read_modes_rlm_file (integer, intent(in) id_rank, type(field_io_params), intent(in) file_param, type(sph_file_data_type), intent(inout) sph_file, integer(kind = kint), intent(inout) ierr)
Definition at line 192 of file sph_file_IO_select.F90.
References gz_sph_modes_grids_file_io::gz_read_modes_rlm_file(), gz_sph_modes_file_io_b::gz_read_modes_rlm_file_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, mesh_file_id, sph_modes_grids_file_io::read_modes_rlm_file(), sph_modes_grids_file_io_b::read_modes_rlm_file_b(), set_mesh_file_names::set_sph_rlm_file_name(), and sph_file_name.
Referenced by sph_file_mpi_io_select::sel_mpi_read_modes_rlm_file().
sel_read_spectr_rj_file()
subroutine sph_file_io_select::sel_read_spectr_rj_file (integer, intent(in) id_rank, type(field_io_params), intent(in) file_param, type(sph_file_data_type), intent(inout) sph_file, integer(kind = kint), intent(inout) ierr)
Definition at line 122 of file sph_file_IO_select.F90.
References gz_sph_modes_grids_file_io::gz_read_spectr_modes_rj_file(), gz_sph_modes_file_io_b::gz_read_spectr_modes_rj_file_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, mesh_file_id, sph_modes_grids_file_io::read_spectr_modes_rj_file(), sph_modes_grids_file_io_b::read_spectr_modes_rj_file_b(), set_mesh_file_names::set_sph_rj_file_name(), and sph_file_name.
Referenced by sph_file_mpi_io_select::sel_mpi_read_spectr_rj_file().
sel_write_geom_rtm_file()
subroutine sph_file_io_select::sel_write_geom_rtm_file (integer, intent(in) id_rank, type(field_io_params), intent(in) file_param, type(sph_file_data_type), intent(in) sph_file, integer(kind = kint), intent(inout) ierr)
Definition at line 294 of file sph_file_IO_select.F90.
References gz_sph_modes_grids_file_io::gz_write_geom_rtm_file(), gz_sph_modes_file_io_b::gz_write_geom_rtm_file_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, mesh_file_id, set_mesh_file_names::set_sph_rtm_file_name(), sph_file_name, sph_modes_grids_file_io::write_geom_rtm_file(), and sph_modes_grids_file_io_b::write_geom_rtm_file_b().
Referenced by output_gen_sph_grid_modes::para_output_sph_mode_grids(), and sph_file_mpi_io_select::sel_mpi_write_geom_rtm_file().
sel_write_geom_rtp_file()
subroutine sph_file_io_select::sel_write_geom_rtp_file (integer, intent(in) id_rank, type(field_io_params), intent(in) file_param, type(sph_file_data_type), intent(in) sph_file, integer(kind = kint), intent(inout) ierr)
Definition at line 228 of file sph_file_IO_select.F90.
References gz_sph_modes_grids_file_io::gz_write_geom_rtp_file(), gz_sph_modes_file_io_b::gz_write_geom_rtp_file_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, mesh_file_id, set_mesh_file_names::set_sph_rtp_file_name(), sph_file_name, sph_modes_grids_file_io::write_geom_rtp_file(), and sph_modes_grids_file_io_b::write_geom_rtp_file_b().
Referenced by output_gen_sph_grid_modes::para_output_sph_mode_grids(), and sph_file_mpi_io_select::sel_mpi_write_geom_rtp_file().
sel_write_modes_rlm_file()
subroutine sph_file_io_select::sel_write_modes_rlm_file (integer, intent(in) id_rank, type(field_io_params), intent(in) file_param, type(sph_file_data_type), intent(in) sph_file, integer(kind = kint), intent(inout) ierr)
Definition at line 326 of file sph_file_IO_select.F90.
References gz_sph_modes_grids_file_io::gz_write_modes_rlm_file(), gz_sph_modes_file_io_b::gz_write_modes_rlm_file_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, mesh_file_id, set_mesh_file_names::set_sph_rlm_file_name(), sph_file_name, sph_modes_grids_file_io::write_modes_rlm_file(), and sph_modes_grids_file_io_b::write_modes_rlm_file_b().
Referenced by output_gen_sph_grid_modes::para_output_sph_mode_grids(), and sph_file_mpi_io_select::sel_mpi_write_modes_rlm_file().
sel_write_spectr_modes_rj_file()
subroutine sph_file_io_select::sel_write_spectr_modes_rj_file (integer, intent(in) id_rank, type(field_io_params), intent(in) file_param, type(sph_file_data_type), intent(in) sph_file, integer(kind = kint), intent(inout) ierr)
Definition at line 260 of file sph_file_IO_select.F90.
References gz_sph_modes_grids_file_io::gz_write_spectr_modes_rj_file(), gz_sph_modes_file_io_b::gz_write_spectr_modes_rj_file_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, mesh_file_id, set_mesh_file_names::set_sph_rj_file_name(), sph_file_name, sph_modes_grids_file_io::write_spectr_modes_rj_file(), and sph_modes_grids_file_io_b::write_spectr_modes_rj_file_b().
Referenced by output_gen_sph_grid_modes::para_output_sph_mode_grids(), output_gen_sph_grid_modes::para_output_sph_rj_modes(), and sph_file_mpi_io_select::sel_mpi_write_spectr_rj_file().
set_sph_mesh_file_fmt_prefix()
subroutine sph_file_io_select::set_sph_mesh_file_fmt_prefix (integer(kind = kint), intent(in) iflag_fmt, character(len=kchara), intent(in) file_head, type(field_io_params), intent(inout) file_param)
Definition at line 72 of file sph_file_IO_select.F90.
Referenced by output_gen_sph_grid_modes::load_local_rj_mesh_4_merge().
Variable Documentation
mesh_file_id
integer(kind = kint), parameter, private sph_file_io_select::mesh_file_id = 14 private
Definition at line 62 of file sph_file_IO_select.F90.
Referenced by sel_read_geom_rtm_file(), sel_read_geom_rtp_file(), sel_read_modes_rlm_file(), sel_read_spectr_rj_file(), sel_write_geom_rtm_file(), sel_write_geom_rtp_file(), sel_write_modes_rlm_file(), and sel_write_spectr_modes_rj_file().
sph_file_name
character(len=kchara), private sph_file_io_select::sph_file_name private
Definition at line 64 of file sph_file_IO_select.F90.
Referenced by check_exsist_rj_file(), check_exsist_rlm_file(), check_exsist_rtm_file(), check_exsist_rtp_file(), sel_read_geom_rtm_file(), sel_read_geom_rtp_file(), sel_read_modes_rlm_file(), sel_read_spectr_rj_file(), sel_write_geom_rtm_file(), sel_write_geom_rtp_file(), sel_write_modes_rlm_file(), and sel_write_spectr_modes_rj_file().