CALYPSO: t_field_labels Module Reference
t_field_labels Module Reference
Data Types
type field_def
Structure of field label.
Functions/Subroutines
subroutine set_field_labels (field, n_comps, field_names, maths)
logical function cmp_field_no_case (cmp_chara, field)
Function/Subroutine Documentation
cmp_field_no_case()
logical function t_field_labels::cmp_field_no_case (character(len=kchara), intent(in) cmp_chara, type(field_def), intent(in) field)
Definition at line 73 of file t_field_labels.f90.
References skip_comment_f::cmp_no_case().
Referenced by set_components_flags::s_set_components_flags().
set_field_labels()
subroutine t_field_labels::set_field_labels (type(field_def), intent(in) field, integer(kind = kint_4b), intent(inout) n_comps, character(len = kchara), intent(inout) field_names, character(len = kchara), intent(inout) maths)
Definition at line 49 of file t_field_labels.f90.
References m_precision::kchara.
Referenced by m_diffusion_term_labels::set_base_diffusion_labels(), m_diffusion_term_labels::set_base_diffusivity_labels(), m_base_field_labels::set_base_field_names(), m_base_force_labels::set_base_force_labels(), m_explicit_term_labels::set_check_fields_labels(), m_diff_vector_labels::set_differnce_vector_labels(), m_div_force_labels::set_div_force_labels(), m_grad_field_labels::set_divergence_field_labels(), m_energy_flux_labels::set_energy_flux_names(), m_field_product_labels::set_field_product_labels(), m_component_flags::set_flag_asym_tensor_comp(), m_component_flags::set_flag_scalar_comp(), m_component_flags::set_flag_sym_tensor_comp(), m_component_flags::set_flag_vector_comp(), m_grad_field_labels::set_gradient_field_labels(), m_rot_force_labels::set_rot_force_labels(), and m_explicit_term_labels::set_work_4_explicit_labels().