CALYPSO: m_energy_flux_labels Module Reference
m_energy_flux_labels Module Reference
Functions/Subroutines
logical function check_enegy_fluxes (field_name)
integer(kind=kint) function num_energy_fluxes ()
subroutine set_energy_flux_names (n_comps, names, maths)
Variables
integer(kind=kint), parameter, private nene_flux = 14
type(field_def), parameter inertia_work = field_def(n_comp = n_scalar, name = 'inertia_work', math = '$ -u_{i} (e_{ijk} \omega_{j} u_{k}) $')
Field label of work of inertia \(-u_{i} (e_{ijk} \omega_{j} u_{k}) \).
type(field_def), parameter work_against_lorentz = field_def(n_comp = n_scalar, name = 'work_against_Lorentz', math = '$ -u_{i} (e_{ijk} J_{j} B_{k}) $')
Field label of work against Lorentz force \(- u_{i} (e_{ijk} J_{j} B_{k}) \).
type(field_def), parameter lorentz_work = field_def(n_comp = n_scalar, name = 'Lorentz_work', math = '$ u_{i} (e_{ijk} J_{j} B_{k}) $')
Field label of work of Lorentz force \(u_{i} \left(e_{ijk} J_{j} B_{k} \right) \).
type(field_def), parameter mag_tension_work = field_def(n_comp = n_scalar, name = 'mag_tension_work', math = '$ u_{i} (B_{j} \partial_{j}) B_{i} $')
Field address of work of magnetic tension \(u_{i} (B_{j} \partial_{j}) B_{i} \).
type(field_def), parameter buoyancy_flux = field_def(n_comp = n_scalar, name = 'buoyancy_flux', math = '$ -u_{i} \alpha_{T} g_{i} T $')
Field label of buoyancy flux \(-u_{i} \alpha_{T} g_{i} T \).
type(field_def), parameter composite_buoyancy_flux = field_def(n_comp = n_scalar, name = 'composite_buoyancy_flux', math = '$ -u_{i} \alpha_{C} g_{i} C $')
Field label of compositional buoyancy flux \(-u_{i} \alpha_{c} g_{i} C \).
type(field_def), parameter magnetic_ene_generation = field_def(n_comp = n_scalar, name = 'magnetic_ene_generation', math = '$ B_{i}e_{ijk} \partial_{j}' // ' (e_{klm}u_{l}B_{m}) $')
Field label of magnetic energy flux \(B_{i}e_{ijk} \partial_{j} (e_{klm}u_{l}B_{m}) \).
type(field_def), parameter magnetic_stretch_flux = field_def(n_comp = n_scalar, name = 'magnetic_stretch_flux', math = '$ B_{i} (B_{j} \partial_{j} u_{i} $')
Field label of energy flux of magnetic stretch term \(B_{i} (B_{j} \partial_{j} u_{i}) \).
type(field_def), parameter temp_generation = field_def(n_comp = n_scalar, name = 'temp_generation', math = '$ T (u_{i} \partial_{i}) T $')
Field label of temperature flux \(T (u_{i} \partial_{i}) T \).
type(field_def), parameter pert_temp_generation = field_def(n_comp = n_scalar, name = 'pert_temp_generation', math = '$ \Theta (u_{i} \partial_{i}) \Theta $')
Field label of perturbation temperature flux \(\Theta (u_{i} \partial_{i}) \Theta \).
type(field_def), parameter comp_generation = field_def(n_comp = n_scalar, name = 'comp_generation', math = '$ C (u_{i} \partial_{i}) C $')
Field label of composition flux \(C (u_{i} \partial_{i}) \).
type(field_def), parameter pert_comp_generation = field_def(n_comp = n_scalar, name = 'pert_comp_generation', math = '$ \Theta_C} (u_{i} \partial_{i}) \Theta_{C} $')
Field label of perturbation composition flux \((C - C_0) (u_{i} \partial_{i}) (C - C_0) \).
type(field_def), parameter viscous_ene_diffusion = field_def(n_comp = n_scalar, name = 'viscous_ene_diffusion', math = '$ u_{i} (\partial_{j}\partial_{j} u_{i}) $')
Field label of energy flux by viscous diffusion \(u_{i} (\partial_{j}\partial_{j} u_{i}) \).
type(field_def), parameter magnetic_ene_diffusion = field_def(n_comp = n_scalar, name = 'magnetic_ene_diffusion', math = '$ B_{i} (\partial_{j}\partial_{j} B_{i}) $')
Field label of energy flux by magnetic diffusion \(B_{i} \left(\partial_{j}\partial_{j} B_{i} \right) \).
type(field_def), parameter buoyancy_work = field_def(n_comp = n_scalar, name = 'buoyancy_work', math = '$ -u_{i} \alpha_{T} g_{i} T $')
Old Field label for buoyancy flux \(-u_{i} \alpha_{T} g_{i} T \).
Function/Subroutine Documentation
check_enegy_fluxes()
logical function m_energy_flux_labels::check_enegy_fluxes (character(len = kchara), intent(in) field_name)
Definition at line 173 of file m_energy_flux_labels.f90.
References buoyancy_flux, comp_generation, composite_buoyancy_flux, inertia_work, lorentz_work, mag_tension_work, magnetic_ene_diffusion, magnetic_ene_generation, magnetic_stretch_flux, pert_comp_generation, pert_temp_generation, temp_generation, viscous_ene_diffusion, and work_against_lorentz.
Referenced by set_mhd_field_address::check_scalar_fields(), and t_energy_flux_labels::set_enegy_fluxes_addresses().
num_energy_fluxes()
integer(kind = kint) function m_energy_flux_labels::num_energy_fluxes
Definition at line 203 of file m_energy_flux_labels.f90.
References nene_flux.
set_energy_flux_names()
subroutine m_energy_flux_labels::set_energy_flux_names (integer(kind = kint_4b), dimension(nene_flux), intent(inout) n_comps, character(len = kchara), dimension(nene_flux), intent(inout) names, character(len = kchara), dimension(nene_flux), intent(inout) maths)
Definition at line 210 of file m_energy_flux_labels.f90.
References buoyancy_flux, comp_generation, composite_buoyancy_flux, inertia_work, lorentz_work, mag_tension_work, magnetic_ene_diffusion, magnetic_ene_generation, magnetic_stretch_flux, pert_comp_generation, pert_temp_generation, t_field_labels::set_field_labels(), temp_generation, viscous_ene_diffusion, and work_against_lorentz.
Variable Documentation
buoyancy_flux
type(field_def), parameter m_energy_flux_labels::buoyancy_flux = field_def(n_comp = n_scalar, name = 'buoyancy_flux', math = '$ -u_{i} \alpha_{T} g_{i} T $')
Field label of buoyancy flux \(-u_{i} \alpha_{T} g_{i} T \).
Definition at line 95 of file m_energy_flux_labels.f90.
Referenced by check_energy_fluxes::add_field_ctl_4_ene_flux(), check_enegy_fluxes(), t_energy_flux_labels::set_enegy_fluxes_addresses(), set_energy_flux_names(), and set_nodal_field_name::set_scalar_field_name().
buoyancy_work
type(field_def), parameter m_energy_flux_labels::buoyancy_work = field_def(n_comp = n_scalar, name = 'buoyancy_work', math = '$ -u_{i} \alpha_{T} g_{i} T $')
Old Field label for buoyancy flux \(-u_{i} \alpha_{T} g_{i} T \).
Definition at line 162 of file m_energy_flux_labels.f90.
Referenced by set_mhd_field_address::set_old_mhd_field_addresses(), and set_nodal_field_name::set_scalar_field_name().
comp_generation
type(field_def), parameter m_energy_flux_labels::comp_generation = field_def(n_comp = n_scalar, name = 'comp_generation', math = '$ C (u_{i} \partial_{i}) C $')
Field label of composition flux \(C (u_{i} \partial_{i}) \).
Definition at line 134 of file m_energy_flux_labels.f90.
Referenced by check_energy_fluxes::add_field_ctl_4_ene_flux(), check_enegy_fluxes(), t_energy_flux_labels::set_enegy_fluxes_addresses(), and set_energy_flux_names().
composite_buoyancy_flux
type(field_def), parameter m_energy_flux_labels::composite_buoyancy_flux = field_def(n_comp = n_scalar, name = 'composite_buoyancy_flux', math = '$ -u_{i} \alpha_{C} g_{i} C $')
Field label of compositional buoyancy flux \(-u_{i} \alpha_{c} g_{i} C \).
Definition at line 101 of file m_energy_flux_labels.f90.
Referenced by check_energy_fluxes::add_field_ctl_4_ene_flux(), check_enegy_fluxes(), t_energy_flux_labels::set_enegy_fluxes_addresses(), and set_energy_flux_names().
inertia_work
type(field_def), parameter m_energy_flux_labels::inertia_work = field_def(n_comp = n_scalar, name = 'inertia_work', math = '$ -u_{i} (e_{ijk} \omega_{j} u_{k}) $')
Field label of work of inertia \(-u_{i} (e_{ijk} \omega_{j} u_{k}) \).
Definition at line 70 of file m_energy_flux_labels.f90.
Referenced by check_energy_fluxes::add_field_ctl_4_ene_flux(), check_enegy_fluxes(), t_energy_flux_labels::set_enegy_fluxes_addresses(), and set_energy_flux_names().
lorentz_work
type(field_def), parameter m_energy_flux_labels::lorentz_work = field_def(n_comp = n_scalar, name = 'Lorentz_work', math = '$ u_{i} (e_{ijk} J_{j} B_{k}) $')
Field label of work of Lorentz force \(u_{i} \left(e_{ijk} J_{j} B_{k} \right) \).
Definition at line 82 of file m_energy_flux_labels.f90.
Referenced by check_energy_fluxes::add_field_ctl_4_ene_flux(), check_enegy_fluxes(), t_energy_flux_labels::set_enegy_fluxes_addresses(), and set_energy_flux_names().
mag_tension_work
type(field_def), parameter m_energy_flux_labels::mag_tension_work = field_def(n_comp = n_scalar, name = 'mag_tension_work', math = '$ u_{i} (B_{j} \partial_{j}) B_{i} $')
Field address of work of magnetic tension \(u_{i} (B_{j} \partial_{j}) B_{i} \).
Definition at line 88 of file m_energy_flux_labels.f90.
Referenced by check_energy_fluxes::add_field_ctl_4_ene_flux(), check_enegy_fluxes(), t_energy_flux_labels::set_enegy_fluxes_addresses(), and set_energy_flux_names().
magnetic_ene_diffusion
type(field_def), parameter m_energy_flux_labels::magnetic_ene_diffusion = field_def(n_comp = n_scalar, name = 'magnetic_ene_diffusion', math = '$ B_{i} (\partial_{j}\partial_{j} B_{i}) $')
Field label of energy flux by magnetic diffusion \(B_{i} \left(\partial_{j}\partial_{j} B_{i} \right) \).
Definition at line 153 of file m_energy_flux_labels.f90.
Referenced by check_energy_fluxes::add_field_ctl_4_ene_flux(), check_enegy_fluxes(), t_energy_flux_labels::set_enegy_fluxes_addresses(), and set_energy_flux_names().
magnetic_ene_generation
type(field_def), parameter m_energy_flux_labels::magnetic_ene_generation = field_def(n_comp = n_scalar, name = 'magnetic_ene_generation', math = '$ B_{i}e_{ijk} \partial_{j}' // ' (e_{klm}u_{l}B_{m}) $')
Field label of magnetic energy flux \(B_{i}e_{ijk} \partial_{j} (e_{klm}u_{l}B_{m}) \).
Definition at line 108 of file m_energy_flux_labels.f90.
Referenced by check_energy_fluxes::add_field_ctl_4_ene_flux(), check_enegy_fluxes(), t_energy_flux_labels::set_enegy_fluxes_addresses(), and set_energy_flux_names().
magnetic_stretch_flux
type(field_def), parameter m_energy_flux_labels::magnetic_stretch_flux = field_def(n_comp = n_scalar, name = 'magnetic_stretch_flux', math = '$ B_{i} (B_{j} \partial_{j} u_{i} $')
Field label of energy flux of magnetic stretch term \(B_{i} (B_{j} \partial_{j} u_{i}) \).
Definition at line 115 of file m_energy_flux_labels.f90.
Referenced by check_energy_fluxes::add_field_ctl_4_ene_flux(), check_enegy_fluxes(), t_energy_flux_labels::set_enegy_fluxes_addresses(), and set_energy_flux_names().
nene_flux
integer(kind = kint), parameter, private m_energy_flux_labels::nene_flux = 14 private
Definition at line 66 of file m_energy_flux_labels.f90.
Referenced by num_energy_fluxes().
pert_comp_generation
type(field_def), parameter m_energy_flux_labels::pert_comp_generation = field_def(n_comp = n_scalar, name = 'pert_comp_generation', math = '$ \Theta_C} (u_{i} \partial_{i}) \Theta_{C} $')
Field label of perturbation composition flux \((C - C_0) (u_{i} \partial_{i}) (C - C_0) \).
Definition at line 140 of file m_energy_flux_labels.f90.
Referenced by check_energy_fluxes::add_field_ctl_4_ene_flux(), check_enegy_fluxes(), t_energy_flux_labels::set_enegy_fluxes_addresses(), and set_energy_flux_names().
pert_temp_generation
type(field_def), parameter m_energy_flux_labels::pert_temp_generation = field_def(n_comp = n_scalar, name = 'pert_temp_generation', math = '$ \Theta (u_{i} \partial_{i}) \Theta $')
Field label of perturbation temperature flux \(\Theta (u_{i} \partial_{i}) \Theta \).
Definition at line 128 of file m_energy_flux_labels.f90.
Referenced by check_energy_fluxes::add_field_ctl_4_ene_flux(), check_enegy_fluxes(), t_energy_flux_labels::set_enegy_fluxes_addresses(), and set_energy_flux_names().
temp_generation
type(field_def), parameter m_energy_flux_labels::temp_generation = field_def(n_comp = n_scalar, name = 'temp_generation', math = '$ T (u_{i} \partial_{i}) T $')
Field label of temperature flux \(T (u_{i} \partial_{i}) T \).
Definition at line 122 of file m_energy_flux_labels.f90.
Referenced by check_energy_fluxes::add_field_ctl_4_ene_flux(), check_enegy_fluxes(), t_energy_flux_labels::set_enegy_fluxes_addresses(), and set_energy_flux_names().
viscous_ene_diffusion
type(field_def), parameter m_energy_flux_labels::viscous_ene_diffusion = field_def(n_comp = n_scalar, name = 'viscous_ene_diffusion', math = '$ u_{i} (\partial_{j}\partial_{j} u_{i}) $')
Field label of energy flux by viscous diffusion \(u_{i} (\partial_{j}\partial_{j} u_{i}) \).
Definition at line 147 of file m_energy_flux_labels.f90.
Referenced by check_energy_fluxes::add_field_ctl_4_ene_flux(), check_enegy_fluxes(), t_energy_flux_labels::set_enegy_fluxes_addresses(), and set_energy_flux_names().
work_against_lorentz
type(field_def), parameter m_energy_flux_labels::work_against_lorentz = field_def(n_comp = n_scalar, name = 'work_against_Lorentz', math = '$ -u_{i} (e_{ijk} J_{j} B_{k}) $')
Field label of work against Lorentz force \(- u_{i} (e_{ijk} J_{j} B_{k}) \).
Definition at line 76 of file m_energy_flux_labels.f90.
Referenced by check_energy_fluxes::add_field_ctl_4_ene_flux(), check_enegy_fluxes(), t_energy_flux_labels::set_enegy_fluxes_addresses(), and set_energy_flux_names().