CALYPSO: t_control_data_4_iso_def Module Reference
t_control_data_4_iso_def Module Reference
control data for each isosurface
Data Types
type iso_define_ctl
Structure of isosurface define control.
Functions/Subroutines
subroutine init_iso_define_control (iso_def_c)
subroutine dealloc_iso_define_control (iso_def_c)
subroutine dup_iso_define_control (org_iso_def_c, new_iso_def_c)
subroutine read_iso_define_data (id_control, hd_block, iso_def_c, c_buf)
subroutine bcast_iso_define_control (iso_def_c)
integer(kind=kint) function num_label_iso_define_control ()
subroutine set_label_iso_define_control (names)
Variables
character(len=kchara), parameter, private hd_iso_field = 'isosurf_field'
character(len=kchara), parameter, private hd_iso_comp = 'isosurf_component'
character(len=kchara), parameter, private hd_iso_value = 'isosurf_value'
character(len=kchara), parameter, private hd_iso_area = 'isosurf_area_ctl'
integer(kind=kint), parameter, private n_label_iso_define_ctl = 4
Detailed Description
control data for each isosurface
      subroutine init_iso_define_control(iso_def_c)
      subroutine dealloc_iso_define_control(iso_def_c)
        type(iso_define_ctl), intent(inout) :: iso_def_c
      subroutine dup_iso_define_control(org_iso_def_c, new_iso_def_c)
        type(iso_define_ctl), intent(in) :: org_iso_def_c
        type(iso_define_ctl), intent(inout) :: new_iso_def_c
      subroutine read_iso_define_data                                 &
     &         (id_control, hd_block, iso_def_c, c_buf)
      subroutine bcast_iso_define_control(iso_def_c)
        type(iso_define_ctl), intent(inout) :: iso_def_c
      integer(kind = kint) function num_label_iso_define_control()
      subroutine set_label_iso_define_control(names)
     example of control for Kemo's surface rendering
    begin isosurf_define
      isosurf_field        pressure
      isosurf_component      scalar
      isosurf_value            4000.0
      array isosurf_area_ctl   2
        isosurf_area_ctl   inner_core   end
        isosurf_area_ctl   outer_core   end
      end array isosurf_area_ctl
    end isosurf_define
    iso_output_type:
           ucd, OpenDX
    result_type:  (Original name: display_method)
                   specified_fields
                   constant
    num_result_comp: number of fields
    output_field: (Original name: color_comp and color_subcomp)
         field and componenet name for output
           x, y, z, radial, elevation, azimuth, cylinder_r
           norm, vector, tensor, spherical_vector, cylindrical_vector
    result_value: (Original name: specified_color)
    isosurf_data: field for isosurface
    isosurf_comp: component for isosurface
           x, y, z, radial, elevation, azimuth, cylinder_r, norm
    isosurf_value:  value for isosurface
Function/Subroutine Documentation
bcast_iso_define_control()
subroutine t_control_data_4_iso_def::bcast_iso_define_control (type(iso_define_ctl), intent(inout) iso_def_c)
Definition at line 200 of file t_control_data_4_iso_def.f90.
References bcast_control_arrays::bcast_ctl_array_c1(), bcast_control_arrays::bcast_ctl_type_c1(), bcast_control_arrays::bcast_ctl_type_r1(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
dealloc_iso_define_control()
subroutine t_control_data_4_iso_def::dealloc_iso_define_control (type(iso_define_ctl), intent(inout) iso_def_c)
Definition at line 126 of file t_control_data_4_iso_def.f90.
dup_iso_define_control()
subroutine t_control_data_4_iso_def::dup_iso_define_control (type(iso_define_ctl), intent(in) org_iso_def_c, type(iso_define_ctl), intent(inout) new_iso_def_c)
Definition at line 145 of file t_control_data_4_iso_def.f90.
init_iso_define_control()
subroutine t_control_data_4_iso_def::init_iso_define_control (type(iso_define_ctl), intent(inout) iso_def_c)
Definition at line 114 of file t_control_data_4_iso_def.f90.
num_label_iso_define_control()
integer(kind = kint) function t_control_data_4_iso_def::num_label_iso_define_control
Definition at line 221 of file t_control_data_4_iso_def.f90.
References n_label_iso_define_ctl.
read_iso_define_data()
subroutine t_control_data_4_iso_def::read_iso_define_data (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(iso_define_ctl), intent(inout) iso_def_c, type(buffer_for_control), intent(inout) c_buf)
Definition at line 167 of file t_control_data_4_iso_def.f90.
References hd_iso_area, hd_iso_comp, hd_iso_field, and hd_iso_value.
set_label_iso_define_control()
subroutine t_control_data_4_iso_def::set_label_iso_define_control (character(len = kchara), dimension(n_label_iso_define_ctl), intent(inout) names)
Definition at line 228 of file t_control_data_4_iso_def.f90.
References hd_iso_area, hd_iso_comp, hd_iso_field, and hd_iso_value.
Variable Documentation
hd_iso_area
character(len=kchara), parameter, private t_control_data_4_iso_def::hd_iso_area = 'isosurf_area_ctl' private
Definition at line 100 of file t_control_data_4_iso_def.f90.
Referenced by read_iso_define_data(), and set_label_iso_define_control().
hd_iso_comp
character(len=kchara), parameter, private t_control_data_4_iso_def::hd_iso_comp = 'isosurf_component' private
Definition at line 96 of file t_control_data_4_iso_def.f90.
Referenced by read_iso_define_data(), and set_label_iso_define_control().
hd_iso_field
character(len=kchara), parameter, private t_control_data_4_iso_def::hd_iso_field = 'isosurf_field' private
Definition at line 94 of file t_control_data_4_iso_def.f90.
Referenced by read_iso_define_data(), and set_label_iso_define_control().
hd_iso_value
character(len=kchara), parameter, private t_control_data_4_iso_def::hd_iso_value = 'isosurf_value' private
Definition at line 98 of file t_control_data_4_iso_def.f90.
Referenced by read_iso_define_data(), and set_label_iso_define_control().
n_label_iso_define_ctl
integer(kind = kint), parameter, private t_control_data_4_iso_def::n_label_iso_define_ctl = 4 private
Definition at line 103 of file t_control_data_4_iso_def.f90.
Referenced by num_label_iso_define_control().