CALYPSO: /home/takumi kera/calypso/src/programs/data_utilities/SNAPSHOT_MHD/main_sph_dynamobench.f90 File Reference
main_sph_dynamobench.f90 File Reference
program sph_dynamobench
Functions/Subroutines
program sph_dynamobench
Main program for dynamo benchmark check.
Detailed Description
program sph_dynamobench
Author
H. Matsui
Date
Programmed by H. Okuda in 2000
Modified by H. Matsui in May, 2003 (ver 2.0)
Connect to vizs by H. Matsui in July 2006 (ver 2.0)
Definition in file main_sph_dynamobench.f90.
Function/Subroutine Documentation
sph_dynamobench()
program sph_dynamobench
Main program for dynamo benchmark check.
Definition at line 11 of file main_sph_dynamobench.f90.
References calypso_mpi::calypso_mpi_finalize(), calypso_mpi::calypso_mpi_init(), analyzer_sph_dynamobench::evolution_sph_dynamobench(), and analyzer_sph_dynamobench::initialize_sph_dynamobench().