CALYPSO: mesh_data_io Module Reference
mesh_data_io Module Reference
Routines for ASCII mesh data IO.
Functions/Subroutines
subroutine write_geometry_data (id_file, id_rank, mesh_IO)
subroutine write_mesh_groups (id_file, mesh_group_IO)
subroutine read_num_node (id_file, id_rank, mesh_IO, ierr)
subroutine read_num_node_ele (id_file, id_rank, mesh_IO, ierr)
subroutine read_geometry_data (id_file, id_rank, mesh_IO, ierr)
subroutine read_mesh_groups (id_file, mesh_group_IO)
subroutine write_filter_geometry (id_file, id_rank, comm_IO, nod_IO)
subroutine read_filter_geometry (id_file, id_rank, comm_IO, nod_IO, ierr)
subroutine output_node_sph_geometry (id_file, id_rank, mesh_IO)
subroutine output_node_cyl_geometry (id_file, id_rank, mesh_IO)
Detailed Description
Routines for ASCII mesh data IO.
      subroutine write_geometry_data(id_file, id_rank, mesh_IO)
      subroutine write_mesh_groups(id_file, mesh_group_IO)
        type(mesh_geometry), intent(in) :: mesh_IO
        type(mesh_groups), intent(in) ::   mesh_group_IO
      subroutine read_num_node(id_file, id_rank, mesh_IO, ierr)
      subroutine read_num_node_ele(id_file, id_rank, mesh_IO, ierr)
      subroutine read_geometry_data(id_file, id_rank, mesh_IO, ierr)
      subroutine read_mesh_groups(id_file, mesh_group_IO)
        type(mesh_geometry), intent(inout) :: mesh_IO
        type(mesh_groups), intent(inout) ::   mesh_group_IO
      subroutine write_filter_geometry                                &
     &         (id_file, id_rank, comm_IO, nod_IO)
        type(node_data), intent(in) :: nod_IO
        type(communication_table), intent(in) :: comm_IO
      subroutine read_filter_geometry                                 &
     &         (id_file, id_rank, comm_IO, nod_IO, ierr)
        type(node_data), intent(inout) :: nod_IO
        type(communication_table), intent(inout) :: comm_IO
      subroutine output_node_sph_geometry                             &
     &         (id_file, id_rank, mesh_IO)
      subroutine output_node_cyl_geometry                             &
     &         (id_file, id_rank, mesh_IO)
        type(mesh_geometry), intent(in) :: mesh_IO
Function/Subroutine Documentation
output_node_cyl_geometry()
subroutine mesh_data_io::output_node_cyl_geometry (integer(kind = kint), intent(in) id_file, integer, intent(in) id_rank, type(mesh_geometry), intent(in) mesh_IO)
Definition at line 293 of file mesh_data_IO.f90.
References m_fem_mesh_labels::hd_fem_node_cyl(), m_fem_mesh_labels::hd_fem_para(), m_fem_mesh_labels::hd_fem_para_cyl(), domain_data_io::write_domain_info(), and node_geometry_io::write_geometry_info().
Referenced by mesh_file_io::write_node_position_cyl().
output_node_sph_geometry()
subroutine mesh_data_io::output_node_sph_geometry (integer(kind = kint), intent(in) id_file, integer, intent(in) id_rank, type(mesh_geometry), intent(in) mesh_IO)
Definition at line 272 of file mesh_data_IO.f90.
References m_fem_mesh_labels::hd_fem_node_sph(), m_fem_mesh_labels::hd_fem_para(), m_fem_mesh_labels::hd_fem_para_sph(), domain_data_io::write_domain_info(), and node_geometry_io::write_geometry_info().
Referenced by mesh_file_io::write_node_position_sph().
read_filter_geometry()
subroutine mesh_data_io::read_filter_geometry (integer(kind = kint), intent(in) id_file, integer, intent(in) id_rank, type(communication_table), intent(inout) comm_IO, type(node_data), intent(inout) nod_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 239 of file mesh_data_IO.f90.
References domain_data_io::read_domain_info(), domain_data_io::read_export_data(), node_geometry_io::read_geometry_info(), domain_data_io::read_import_data(), and node_geometry_io::read_number_of_node().
read_geometry_data()
subroutine mesh_data_io::read_geometry_data (integer(kind = kint), intent(in) id_file, integer, intent(in) id_rank, type(mesh_geometry), intent(inout) mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 157 of file mesh_data_IO.f90.
References element_connect_io::read_element_info(), domain_data_io::read_export_data(), domain_data_io::read_import_data(), and read_num_node_ele().
Referenced by mesh_file_io::read_mesh_file(), and mesh_file_io::read_mesh_geometry().
read_mesh_groups()
subroutine mesh_data_io::read_mesh_groups (integer(kind = kint), intent(in) id_file, type(mesh_groups), intent(inout) mesh_group_IO)
Definition at line 186 of file mesh_data_IO.f90.
References groups_io::read_group_data(), and groups_io::read_surf_grp_data().
Referenced by mesh_file_io::read_mesh_file().
read_num_node()
subroutine mesh_data_io::read_num_node (integer(kind = kint), intent(in) id_file, integer, intent(in) id_rank, type(mesh_geometry), intent(inout) mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 115 of file mesh_data_IO.f90.
References domain_data_io::read_domain_info(), and node_geometry_io::read_number_of_node().
Referenced by mesh_file_io::read_node_size(), and read_num_node_ele().
read_num_node_ele()
subroutine mesh_data_io::read_num_node_ele (integer(kind = kint), intent(in) id_file, integer, intent(in) id_rank, type(mesh_geometry), intent(inout) mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 134 of file mesh_data_IO.f90.
References node_geometry_io::read_geometry_info(), read_num_node(), and element_connect_io::read_number_of_element().
Referenced by read_geometry_data(), and mesh_file_io::read_geometry_size().
write_filter_geometry()
subroutine mesh_data_io::write_filter_geometry (integer(kind = kint), intent(in) id_file, integer, intent(in) id_rank, type(communication_table), intent(in) comm_IO, type(node_data), intent(in) nod_IO)
Definition at line 209 of file mesh_data_IO.f90.
References m_fem_mesh_labels::hd_fem_export(), m_fem_mesh_labels::hd_fem_import(), m_fem_mesh_labels::hd_fem_node(), m_fem_mesh_labels::hd_fem_para(), domain_data_io::write_domain_info(), domain_data_io::write_export_data(), node_geometry_io::write_geometry_info(), and domain_data_io::write_import_data().
write_geometry_data()
subroutine mesh_data_io::write_geometry_data (integer(kind = kint), intent(in) id_file, integer, intent(in) id_rank, type(mesh_geometry), intent(in) mesh_IO)
Definition at line 58 of file mesh_data_IO.f90.
References m_fem_mesh_labels::hd_fem_elem(), m_fem_mesh_labels::hd_fem_export(), m_fem_mesh_labels::hd_fem_import(), m_fem_mesh_labels::hd_fem_node(), m_fem_mesh_labels::hd_fem_para(), domain_data_io::write_domain_info(), element_connect_io::write_element_info(), domain_data_io::write_export_data(), node_geometry_io::write_geometry_info(), and domain_data_io::write_import_data().
Referenced by mesh_file_io::write_mesh_file().
write_mesh_groups()
subroutine mesh_data_io::write_mesh_groups (integer(kind = kint), intent(in) id_file, type(mesh_groups), intent(in) mesh_group_IO)
Definition at line 89 of file mesh_data_IO.f90.
References m_fem_mesh_labels::hd_fem_elegrp(), m_fem_mesh_labels::hd_fem_nodgrp(), m_fem_mesh_labels::hd_fem_sfgrp(), groups_io::write_grp_data(), and groups_io::write_surf_grp_data().
Referenced by mesh_file_io::write_mesh_file().