CALYPSO: t_ctl_params_gen_sph_shell Module Reference
t_ctl_params_gen_sph_shell Module Reference
Set control data for domain decomposition for spherical transform.
Data Types
type gen_sph_file_io_params
Structure of file name and format for MHD.
Functions/Subroutines
subroutine set_control_4_gen_shell_grids (id_rank, plt, psph_ctl, sph_files, sph_maker, ierr)
subroutine, private set_control_4_shell_files (id_rank, plt, Fmesh_ctl, nprocs_check, sph_files)
subroutine set_control_4_shell_grids (nprocs_check, Fmesh_ctl, spctl, sdctl, sph, gen_sph, ierr)
subroutine, private set_ctl_radius_4_shell (spctl, sph_params, sph_rtp, sph_rj, added_radial_grp, s3d_radius, ierr)
subroutine, private set_control_4_sgs_shell (sph, spctl, r_layer_grp, med_layer_grp)
Variables
character(len=kchara), parameter, private cflag_sgs_r = 'SGS_r'
character(len=kchara), parameter, private cflag_sgs_t = 'SGS_theta'
Detailed Description
Set control data for domain decomposition for spherical transform.
      subroutine set_control_4_gen_shell_grids                        &
     &         (id_rank, plt, psph_ctl, sph, sph_files, gen_sph, ierr)
        type(platform_data_control), intent(in) :: plt
        type(parallel_sph_shell_control), intent(inout) :: psph_ctl
        type(sph_grids), intent(inout) :: sph
        type(field_IO_params), intent(inout) ::  mesh_file
        type(construct_spherical_grid), intent(inout) :: gen_sph
      subroutine set_control_4_shell_grids(nprocs_check,              &
     &          Fmesh_ctl, spctl, sdctl, sph, gen_sph, ierr)
        type(FEM_mesh_control), intent(in) :: Fmesh_ctl
        type(sphere_data_control), intent(inout) :: spctl
        type(sphere_domain_control), intent(in) :: sdctl
        type(sph_grids), intent(inout) :: sph
        type(construct_spherical_grid), intent(inout) :: gen_sph
Function/Subroutine Documentation
set_control_4_gen_shell_grids()
subroutine t_ctl_params_gen_sph_shell::set_control_4_gen_shell_grids (integer, intent(in) id_rank, type(platform_data_control), intent(in) plt, type(parallel_sph_shell_control), intent(inout) psph_ctl, type(gen_sph_file_io_params), intent(inout) sph_files, type(sph_grid_maker_in_sim), intent(inout) sph_maker, integer(kind = kint), intent(inout) ierr)
Definition at line 69 of file t_ctl_params_gen_sph_shell.f90.
References t_ctl_data_gen_sph_shell::dealloc_parallel_shell_ctl(), m_file_format_switch::id_no_file, t_ctl_data_4_sphere_model::reset_control_shell_define(), set_control_4_shell_files(), and set_control_4_shell_grids().
Referenced by analyzer_check_sph_grids::init_check_sph_grids(), analyzer_gen_sph_grids::init_gen_sph_grids(), and analyzer_test_sph::init_test_sph().
set_control_4_sgs_shell()
subroutine, private t_ctl_params_gen_sph_shell::set_control_4_sgs_shell (type(sph_grids), intent(in) sph, type(sphere_data_control), intent(in) spctl, type(layering_group_list), intent(inout) r_layer_grp, type(layering_group_list), intent(inout) med_layer_grp) private
Definition at line 426 of file t_ctl_params_gen_sph_shell.f90.
References t_control_1d_layering::alloc_layering_group(), cflag_sgs_r, cflag_sgs_t, t_control_1d_layering::set_group_by_equidivide(), and t_control_1d_layering::set_group_by_layering_list().
Referenced by set_control_4_shell_grids().
set_control_4_shell_files()
subroutine, private t_ctl_params_gen_sph_shell::set_control_4_shell_files (integer, intent(in) id_rank, type(platform_data_control), intent(in) plt, type(fem_mesh_control), intent(in) Fmesh_ctl, integer, intent(inout) nprocs_check, type(gen_sph_file_io_params), intent(inout) sph_files) private
Definition at line 106 of file t_ctl_params_gen_sph_shell.f90.
References set_control_platform_data::set_control_sph_mesh(), and set_control_platform_data::turn_off_debug_flag_by_ctl().
Referenced by set_control_4_gen_shell_grids().
set_control_4_shell_grids()
subroutine t_ctl_params_gen_sph_shell::set_control_4_shell_grids (integer, intent(in) nprocs_check, type(fem_mesh_control), intent(in) Fmesh_ctl, type(sphere_data_control), intent(in) spctl, type(sphere_domain_control), intent(in) sdctl, type(sph_grids), intent(inout) sph, type(construct_spherical_grid), intent(inout) gen_sph, integer(kind = kint), intent(inout) ierr)
Definition at line 133 of file t_ctl_params_gen_sph_shell.f90.
References m_machine_parameter::e_message, m_error_ids::ierr_mesh, m_spheric_constants::iflag_mesh_w_center, m_spheric_constants::iflag_mesh_w_pole, set_control_4_sgs_shell(), set_ctl_radius_4_shell(), set_controls_4_sph_shell::set_fem_mesh_mode_4_sph(), set_control_sph_subdomains::set_inner_loop_4_sph_shell(), and set_control_sph_subdomains::set_subdomains_4_sph_shell().
Referenced by set_control_4_gen_shell_grids(), set_control_newsph::set_control_4_newsph(), and set_control_sph_mhd::set_control_4_sph_mhd().
set_ctl_radius_4_shell()
subroutine, private t_ctl_params_gen_sph_shell::set_ctl_radius_4_shell (type(sphere_data_control), intent(in) spctl, type(sph_shell_parameters), intent(inout) sph_params, type(sph_rtp_grid), intent(inout) sph_rtp, type(sph_rj_grid), intent(inout) sph_rj, type(layering_group_list), intent(inout) added_radial_grp, type(spheric_global_radius), intent(inout) s3d_radius, integer(kind = kint), intent(inout) ierr) private
Definition at line 228 of file t_ctl_params_gen_sph_shell.f90.
References t_spheric_global_ranks::alloc_radius_1d_gl(), t_spheric_parameter::cmb_nod_grp_name, skip_comment_f::cmp_no_case(), const_sph_radial_grid::count_set_radial_grid(), t_spheric_parameter::ctr_nod_grp_name, t_spheric_parameter::icb_nod_grp_name, and m_error_ids::ierr_mesh.
Referenced by set_control_4_shell_grids().
Variable Documentation
cflag_sgs_r
character(len=kchara), parameter, private t_ctl_params_gen_sph_shell::cflag_sgs_r = 'SGS_r' private
Definition at line 56 of file t_ctl_params_gen_sph_shell.f90.
Referenced by set_control_4_sgs_shell().
cflag_sgs_t
character(len=kchara), parameter, private t_ctl_params_gen_sph_shell::cflag_sgs_t = 'SGS_theta' private
Definition at line 57 of file t_ctl_params_gen_sph_shell.f90.
Referenced by set_control_4_sgs_shell().