CALYPSO: set_area_4_viz Module Reference
set_area_4_viz Module Reference
Functions/Subroutines
subroutine count_area_4_viz (num_mat, mat_name, num_area_grp, area_ele_grp, ngrp_area)
subroutine s_set_area_4_viz (num_mat, mat_name, num_area_grp, area_ele_grp, ngrp_area, id_ele_grp_psf)
subroutine set_surf_grp_id_4_viz (num_surf, surf_name, chosen_surf_grp, id_surf_grp)
Function/Subroutine Documentation
count_area_4_viz()
subroutine set_area_4_viz::count_area_4_viz (integer(kind = kint), intent(in) num_mat, character(len=kchara), dimension(num_mat), intent(in) mat_name, integer(kind = kint), intent(in) num_area_grp, character(len=kchara), dimension(num_area_grp), intent(in) area_ele_grp, integer(kind = kint), intent(inout) ngrp_area)
Definition at line 26 of file set_area_4_viz.f90.
Referenced by t_control_params_4_psf::count_control_4_psf_define(), and t_control_params_4_iso::count_control_iso_def().
s_set_area_4_viz()
subroutine set_area_4_viz::s_set_area_4_viz (integer(kind = kint), intent(in) num_mat, character(len=kchara), dimension(num_mat), intent(in) mat_name, integer(kind = kint), intent(in) num_area_grp, character(len=kchara), dimension(num_area_grp), intent(in) area_ele_grp, integer(kind = kint), intent(in) ngrp_area, integer(kind = kint), dimension(ngrp_area), intent(inout) id_ele_grp_psf)
Definition at line 60 of file set_area_4_viz.f90.
Referenced by t_control_params_4_iso::set_control_iso_def(), and t_control_params_4_psf::set_control_psf_define().
set_surf_grp_id_4_viz()
subroutine set_area_4_viz::set_surf_grp_id_4_viz (integer(kind = kint), intent(in) num_surf, character(len=kchara), dimension(num_surf), intent(in) surf_name, character(len=kchara), intent(in) chosen_surf_grp, integer(kind = kint), intent(inout) id_surf_grp)
Definition at line 97 of file set_area_4_viz.f90.
Referenced by t_control_params_4_psf::set_control_psf_define().