CALYPSO: set_sph_ele_group Module Reference
set_sph_ele_group Module Reference
Functions/Subroutines
subroutine allocate_sph_ele_grp_flag (stbl)
subroutine deallocate_sph_ele_grp_flag
subroutine count_sph_local_ele_group (ele_grp, radial_rj_grp)
subroutine count_sph_local_ele_grp_item (ip_r, ip_t, sph_params, stbl, radial_rj_grp, ele_grp)
subroutine set_sph_local_ele_grp_item (ip_r, ip_t, sph_params, stbl, radial_rj_grp, ele_grp)
subroutine, private count_ele_grp_item_on_sphere (ip_t, sph_params, stbl, nitem_grp)
subroutine, private count_ele_grp_item_4_center (ip_t, stbl, nitem_grp)
subroutine, private set_ele_grp_item_on_sphere (ip_r, ip_t, kr, sph_params, stbl, inum, ele_grp)
subroutine, private set_ele_grp_item_4_center (ip_t, stbl, inum, ele_grp)
Variables
integer(kind=kint), dimension(:), allocatable, private iflag_r
Function/Subroutine Documentation
allocate_sph_ele_grp_flag()
subroutine set_sph_ele_group::allocate_sph_ele_grp_flag (type(comm_table_make_sph), intent(in) stbl)
Definition at line 40 of file set_sph_ele_group.f90.
References iflag_r.
Referenced by set_fem_mesh_4_sph::const_fem_groups_for_sph().
count_ele_grp_item_4_center()
subroutine, private set_sph_ele_group::count_ele_grp_item_4_center (integer(kind = kint), intent(in) ip_t, type(comm_table_make_sph), intent(in) stbl, integer(kind = kint), intent(inout) nitem_grp) private
Definition at line 237 of file set_sph_ele_group.f90.
Referenced by count_sph_local_ele_grp_item().
count_ele_grp_item_on_sphere()
subroutine, private set_sph_ele_group::count_ele_grp_item_on_sphere (integer(kind = kint), intent(in) ip_t, type(sph_shell_parameters), intent(in) sph_params, type(comm_table_make_sph), intent(in) stbl, integer(kind = kint), intent(inout) nitem_grp) private
Definition at line 205 of file set_sph_ele_group.f90.
Referenced by count_sph_local_ele_grp_item().
count_sph_local_ele_group()
subroutine set_sph_ele_group::count_sph_local_ele_group (type(group_data), intent(inout) ele_grp, type(group_data), intent(in) radial_rj_grp)
Definition at line 64 of file set_sph_ele_group.f90.
References iflag_r.
Referenced by set_fem_mesh_4_sph::const_fem_groups_for_sph().
count_sph_local_ele_grp_item()
subroutine set_sph_ele_group::count_sph_local_ele_grp_item (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, type(sph_shell_parameters), intent(in) sph_params, type(comm_table_make_sph), intent(in) stbl, type(group_data), intent(in) radial_rj_grp, type(group_data), intent(inout) ele_grp)
Definition at line 86 of file set_sph_ele_group.f90.
References count_ele_grp_item_4_center(), count_ele_grp_item_on_sphere(), t_spheric_parameter::ic_ele_grp_name, iflag_r, and m_constants::ione.
Referenced by set_fem_mesh_4_sph::const_fem_groups_for_sph().
deallocate_sph_ele_grp_flag()
subroutine set_sph_ele_group::deallocate_sph_ele_grp_flag
Definition at line 54 of file set_sph_ele_group.f90.
References iflag_r.
Referenced by set_fem_mesh_4_sph::const_fem_groups_for_sph().
set_ele_grp_item_4_center()
subroutine, private set_sph_ele_group::set_ele_grp_item_4_center (integer(kind = kint), intent(in) ip_t, type(comm_table_make_sph), intent(in) stbl, integer(kind = kint), intent(inout) inum, type(group_data), intent(inout) ele_grp) private
Definition at line 315 of file set_sph_ele_group.f90.
References cal_sph_ele_addresses::sph_exter_ctr_npole_ele_id(), cal_sph_ele_addresses::sph_exter_ctr_shell_ele_id(), cal_sph_ele_addresses::sph_inter_ctr_npole_ele_id(), cal_sph_ele_addresses::sph_inter_ctr_shell_ele_id(), and cal_sph_ele_addresses::sph_inter_ctr_spole_ele_id().
Referenced by set_sph_local_ele_grp_item().
set_ele_grp_item_on_sphere()
subroutine, private set_sph_ele_group::set_ele_grp_item_on_sphere (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, integer(kind = kint), intent(in) kr, type(sph_shell_parameters), intent(in) sph_params, type(comm_table_make_sph), intent(in) stbl, integer(kind = kint), intent(inout) inum, type(group_data), intent(inout) ele_grp) private
Definition at line 264 of file set_sph_ele_group.f90.
References cal_sph_ele_addresses::sph_n_pole_ele_id(), cal_sph_ele_addresses::sph_s_pole_ele_id(), and cal_sph_ele_addresses::sph_shell_ele_id().
Referenced by set_sph_local_ele_grp_item().
set_sph_local_ele_grp_item()
subroutine set_sph_ele_group::set_sph_local_ele_grp_item (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, type(sph_shell_parameters), intent(in) sph_params, type(comm_table_make_sph), intent(in) stbl, type(group_data), intent(in) radial_rj_grp, type(group_data), intent(inout) ele_grp)
Definition at line 146 of file set_sph_ele_group.f90.
References t_spheric_parameter::ic_ele_grp_name, iflag_r, m_constants::ione, set_ele_grp_item_4_center(), and set_ele_grp_item_on_sphere().
Referenced by set_fem_mesh_4_sph::const_fem_groups_for_sph().
Variable Documentation
iflag_r
integer(kind = kint), dimension(:), allocatable, private set_sph_ele_group::iflag_r private
Definition at line 31 of file set_sph_ele_group.f90.
Referenced by allocate_sph_ele_grp_flag(), count_sph_local_ele_group(), count_sph_local_ele_grp_item(), deallocate_sph_ele_grp_flag(), and set_sph_local_ele_grp_item().