CALYPSO: time_data_io Module Reference
time_data_io Module Reference
time and time step data for data IO
Functions/Subroutines
character(len=len_step_data_buf) function step_data_buffer (id_rank, t_IO)
subroutine read_step_data_buffer (textbuf, id_rank, t_IO)
subroutine write_step_data (id_file, id_rank, t_IO)
subroutine read_step_data (id_file, t_IO)
Variables
character(len=12), parameter, private time_hd1 = '! domain ID'
character(len=19), parameter, private time_hd2 = '! time step number'
character(len=16), parameter, private time_hd3 = '! time, Delta t'
integer, parameter, private l_hd = 12 + 19 + 16 + 3
integer, parameter, private l_dt = 2*16 + 2*25 + 3
integer, parameter len_step_data_buf = l_hd+l_dt
Detailed Description
time and time step data for data IO
      function step_data_buffer(id_rank, t_IO)
      subroutine read_step_data_buffer(textbuf, id_rank, t_IO)
      subroutine write_step_data(id_file, id_rank, t_IO)
      subroutine read_step_data(id_file, t_IO)
        type(time_data), intent(inout) :: t_IO
Parameters
id_rank Process ID
id_file file ID for data IO
Function/Subroutine Documentation
read_step_data()
subroutine time_data_io::read_step_data (integer(kind = kint), intent(in) id_file, type(time_data), intent(inout) t_IO)
Definition at line 115 of file time_data_IO.f90.
References skip_comment_f::skip_comment().
Referenced by ucd_field_file_io::read_alloc_ucd_2_fld_file(), field_file_io::read_and_alloc_step_field(), field_file_io::read_and_allocate_step_head(), rst_data_io_by_fld::read_rst_data_comps(), rst_data_io_by_fld::read_rst_file(), field_file_io::read_step_field_file(), and ucd_field_file_io::read_ucd_2_fld_file().
read_step_data_buffer()
subroutine time_data_io::read_step_data_buffer (character(len=len_step_data_buf), intent(in) textbuf, integer(kind = kint), intent(inout) id_rank, type(time_data), intent(inout) t_IO)
Definition at line 75 of file time_data_IO.f90.
Referenced by gz_field_block_mpi_io::read_field_step_gz_mpi(), and field_data_mpi_io::read_field_time_mpi().
step_data_buffer()
character(len=len_step_data_buf) function time_data_io::step_data_buffer (integer, intent(in) id_rank, type(time_data), intent(in) t_IO)
Definition at line 49 of file time_data_IO.f90.
References time_hd1, time_hd2, and time_hd3.
Referenced by field_block_mpi_io::write_field_data_mpi(), and gz_field_block_mpi_io::write_field_head_gz_mpi().
write_step_data()
subroutine time_data_io::write_step_data (integer(kind = kint), intent(in) id_file, integer, intent(in) id_rank, type(time_data), intent(in) t_IO)
Definition at line 97 of file time_data_IO.f90.
References time_hd1, time_hd2, and time_hd3.
Referenced by field_file_io::write_step_field_file(), and ucd_field_file_io::write_ucd_2_fld_file().
Variable Documentation
l_dt
integer, parameter, private time_data_io::l_dt = 2*16 + 2*25 + 3 private
Definition at line 36 of file time_data_IO.f90.
l_hd
integer, parameter, private time_data_io::l_hd = 12 + 19 + 16 + 3 private
Definition at line 35 of file time_data_IO.f90.
len_step_data_buf
integer, parameter time_data_io::len_step_data_buf = l_hd+l_dt
Definition at line 38 of file time_data_IO.f90.
Referenced by gz_field_block_mpi_io::read_field_step_gz_mpi(), and field_data_mpi_io::read_field_time_mpi().
time_hd1
character(len=12), parameter, private time_data_io::time_hd1 = '! domain ID' private
Definition at line 31 of file time_data_IO.f90.
Referenced by step_data_buffer(), and write_step_data().
time_hd2
character(len=19), parameter, private time_data_io::time_hd2 = '! time step number' private
Definition at line 32 of file time_data_IO.f90.
Referenced by step_data_buffer(), and write_step_data().
time_hd3
character(len=16), parameter, private time_data_io::time_hd3 = '! time, Delta t' private
Definition at line 33 of file time_data_IO.f90.
Referenced by step_data_buffer(), and write_step_data().