CALYPSO: bcast_4_platform_ctl Module Reference
bcast_4_platform_ctl Module Reference
Broardcast input routine for data file headers.
Functions/Subroutines
subroutine bcast_ctl_data_4_platform (plt)
subroutine bcast_fem_mesh_control (Fmesh_ctl)
Detailed Description
Broardcast input routine for data file headers.
      subroutine bcast_ctl_data_4_platform(plt)
        type(platform_data_control), intent(inout) :: plt
      subroutine bcast_FEM_mesh_control(Fmesh_ctl)
        type(FEM_mesh_control), intent(inout) :: Fmesh_ctl
Function/Subroutine Documentation
bcast_ctl_data_4_platform()
subroutine bcast_4_platform_ctl::bcast_ctl_data_4_platform (type(platform_data_control), intent(inout) plt)
Definition at line 26 of file bcast_4_platform_ctl.f90.
References bcast_control_arrays::bcast_ctl_type_c1(), bcast_control_arrays::bcast_ctl_type_i1(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by bcast_4_assemble_sph_ctl::bcast_merge_control_data(), t_control_data_section_only::bcast_section_control_data(), t_ctl_data_mhd::bcast_sph_mhd_ctl_data(), and t_ctl_data_const_sph_mesh::bcast_sph_shell_define_ctl().
bcast_fem_mesh_control()
subroutine bcast_4_platform_ctl::bcast_fem_mesh_control (type(fem_mesh_control), intent(inout) Fmesh_ctl)
Definition at line 73 of file bcast_4_platform_ctl.f90.
References bcast_control_arrays::bcast_ctl_type_c1(), bcast_control_arrays::bcast_ctl_type_i1(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by t_ctl_data_gen_sph_shell::bcast_parallel_shell_ctl().