CALYPSO: gz_mpi_binary_datum_io Module Reference
gz_mpi_binary_datum_io Module Reference
Output merged binary field file using MPI-IO.
Functions/Subroutines
subroutine open_write_gz_mpi_file_b (file_name, IO_param)
subroutine open_read_gz_mpi_file_b (file_name, num_pe, id_rank, IO_param)
subroutine gz_mpi_write_process_id_b (IO_param)
subroutine gz_mpi_write_one_inthead_b (IO_param, int_dat)
subroutine gz_mpi_write_one_realhead_b (IO_param, real_dat)
subroutine gz_mpi_write_one_integer_b (IO_param, int_dat)
subroutine gz_mpi_read_process_id_b (IO_param)
subroutine gz_mpi_read_one_inthead_b (IO_param, int_dat)
subroutine gz_mpi_read_one_realhead_b (IO_param, real_dat)
subroutine gz_mpi_read_one_integer_b (IO_param, int_dat)
Detailed Description
Output merged binary field file using MPI-IO.
      subroutine open_write_gz_mpi_file_b(file_name, IO_param)
      subroutine open_read_gz_mpi_file_b                              &
     &         (file_name, num_pe, id_rank, IO_param)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
      subroutine gz_mpi_write_process_id_b(IO_param)
      subroutine gz_mpi_write_one_inthead_b(IO_param, int_dat)
      subroutine gz_mpi_write_one_realhead_b(IO_param, real_dat)
      subroutine gz_mpi_write_one_integer_b(IO_param, int_dat)
      subroutine gz_mpi_read_process_id_b(IO_param)
      subroutine gz_mpi_read_one_inthead_b(IO_param, int_dat)
      subroutine gz_mpi_read_one_realhead_b(IO_param, real_dat)
      subroutine gz_mpi_read_one_integer_b(IO_param, int_dat)
Function/Subroutine Documentation
gz_mpi_read_one_integer_b()
subroutine gz_mpi_binary_datum_io::gz_mpi_read_one_integer_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint), intent(inout) int_dat)
Definition at line 187 of file gz_MPI_binary_datum_IO.f90.
References gz_mpi_binary_data_io::gz_mpi_read_int_vector_b().
Referenced by gz_mpi_domain_data_io_b::gz_mpi_read_domain_info_b(), gz_mpi_element_connect_io_b::gz_mpi_read_edge_4_element_b(), gz_mpi_spherical_model_io_b::gz_mpi_read_gl_nodes_sph_b(), gz_mpi_element_connect_io_b::gz_mpi_read_num_element_b(), gz_mpi_node_geometry_io_b::gz_mpi_read_number_of_node_b(), and gz_mpi_element_connect_io_b::gz_mpi_read_surf_4_elem_b().
gz_mpi_read_one_inthead_b()
subroutine gz_mpi_binary_datum_io::gz_mpi_read_one_inthead_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint), intent(inout) int_dat)
Definition at line 157 of file gz_MPI_binary_datum_IO.f90.
References gz_mpi_binary_head_io::gz_mpi_read_mul_inthead_b(), and m_constants::ione.
Referenced by gz_mpi_spherical_model_io_b::gz_mpi_read_gl_reso_sph_b(), gz_mpi_groups_io_b::gz_mpi_read_group_data_b(), gz_mpi_groups_io_b::gz_mpi_read_surf_grp_data_b(), gz_field_block_mpi_io_b::gz_read_field_header_mpi_b(), and gz_field_block_mpi_io_b::gz_read_step_data_mpi_b().
gz_mpi_read_one_realhead_b()
subroutine gz_mpi_binary_datum_io::gz_mpi_read_one_realhead_b (type(calypso_mpi_io_params), intent(inout) IO_param, real(kind = kreal), intent(inout) real_dat)
Definition at line 172 of file gz_MPI_binary_datum_IO.f90.
References gz_mpi_binary_head_io::gz_mpi_read_mul_realhead_b(), and m_constants::ione.
Referenced by gz_field_block_mpi_io_b::gz_read_step_data_mpi_b().
gz_mpi_read_process_id_b()
subroutine gz_mpi_binary_datum_io::gz_mpi_read_process_id_b (type(calypso_mpi_io_params), intent(inout) IO_param)
Definition at line 139 of file gz_MPI_binary_datum_IO.f90.
References calypso_mpi::calypso_mpi_abort(), gz_mpi_binary_head_io::gz_mpi_read_mul_inthead_b(), m_error_ids::ierr_file, and m_constants::ione.
Referenced by gz_mpi_domain_data_io_b::gz_mpi_read_domain_info_b(), and gz_field_block_mpi_io_b::gz_read_step_data_mpi_b().
gz_mpi_write_one_integer_b()
subroutine gz_mpi_binary_datum_io::gz_mpi_write_one_integer_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint), intent(in) int_dat)
Definition at line 122 of file gz_MPI_binary_datum_IO.f90.
References gz_mpi_binary_data_io::gz_mpi_write_int_vector_b().
Referenced by gz_mpi_domain_data_io_b::gz_mpi_write_domain_info_b(), gz_mpi_element_connect_io_b::gz_mpi_write_edge_4_ele_b(), gz_mpi_element_connect_io_b::gz_mpi_write_element_info_b(), gz_mpi_node_geometry_io_b::gz_mpi_write_geometry_info_b(), gz_mpi_spherical_model_io_b::gz_mpi_write_gl_nodes_sph_b(), gz_mpi_node_geometry_io_b::gz_mpi_write_scl_in_ele_b(), gz_mpi_element_connect_io_b::gz_mpi_write_surf_4_ele_b(), and gz_mpi_node_geometry_io_b::gz_mpi_write_vect_in_ele_b().
gz_mpi_write_one_inthead_b()
subroutine gz_mpi_binary_datum_io::gz_mpi_write_one_inthead_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint), intent(in) int_dat)
Definition at line 92 of file gz_MPI_binary_datum_IO.f90.
References gz_mpi_binary_head_io::gz_mpi_write_mul_inthead_b(), and m_constants::ione.
Referenced by gz_mpi_spherical_model_io_b::gz_mpi_write_gl_reso_sph_b(), gz_mpi_groups_io_b::gz_mpi_write_grp_data_b(), gz_mpi_groups_io_b::gz_mpi_write_surf_grp_data_b(), gz_ucd_file_mpi_io::gz_mpi_write_ucd_mesh_data_b(), gz_field_block_mpi_io_b::gz_write_field_data_mpi_b(), gz_field_block_mpi_io_b::gz_write_field_time_mpi_b(), and gz_ucd_file_mpi_io::gz_write_ucd_data_mpi_b().
gz_mpi_write_one_realhead_b()
subroutine gz_mpi_binary_datum_io::gz_mpi_write_one_realhead_b (type(calypso_mpi_io_params), intent(inout) IO_param, real(kind = kreal), intent(in) real_dat)
Definition at line 107 of file gz_MPI_binary_datum_IO.f90.
References gz_mpi_binary_head_io::gz_mpi_write_mul_realhead_b(), and m_constants::ione.
Referenced by gz_field_block_mpi_io_b::gz_write_field_time_mpi_b().
gz_mpi_write_process_id_b()
subroutine gz_mpi_binary_datum_io::gz_mpi_write_process_id_b (type(calypso_mpi_io_params), intent(inout) IO_param)
Definition at line 78 of file gz_MPI_binary_datum_IO.f90.
References gz_mpi_binary_head_io::gz_mpi_write_mul_inthead_b(), and m_constants::ione.
Referenced by gz_mpi_domain_data_io_b::gz_mpi_write_domain_info_b(), gz_ucd_file_mpi_io::gz_mpi_write_ucd_mesh_data_b(), and gz_field_block_mpi_io_b::gz_write_field_time_mpi_b().
open_read_gz_mpi_file_b()
subroutine gz_mpi_binary_datum_io::open_read_gz_mpi_file_b (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, type(calypso_mpi_io_params), intent(inout) IO_param)
Definition at line 61 of file gz_MPI_binary_datum_IO.f90.
References gz_mpi_binary_head_io::gz_mpi_read_byte_check(), and mpi_ascii_data_io::open_read_mpi_file().
Referenced by gz_mpi_sph_modes_file_io_b::gz_mpi_read_geom_rtm_file_b(), gz_mpi_sph_modes_file_io_b::gz_mpi_read_geom_rtp_file_b(), gz_mpi_mesh_file_io_b::gz_mpi_read_geometry_size_b(), gz_mpi_mesh_file_io_b::gz_mpi_read_mesh_file_b(), gz_mpi_mesh_file_io_b::gz_mpi_read_mesh_geometry_b(), gz_mpi_sph_modes_file_io_b::gz_mpi_read_modes_rlm_file_b(), gz_mpi_mesh_file_io_b::gz_mpi_read_node_size_b(), gz_mpi_sph_modes_file_io_b::gz_mpi_read_spectr_rj_file_b(), gz_field_file_mpi_io_b::gz_rd_alloc_st_fld_file_mpi_b(), gz_field_file_mpi_io_b::gz_rd_alloc_st_fld_head_mpi_b(), gz_ucd_field_mpi_io_b::gz_rd_alloc_ucd_fld_file_mpi_b(), gz_field_file_mpi_io_b::gz_read_step_field_file_mpi_b(), and gz_ucd_field_mpi_io_b::gz_read_ucd_field_file_mpi_b().
open_write_gz_mpi_file_b()
subroutine gz_mpi_binary_datum_io::open_write_gz_mpi_file_b (character(len=kchara), intent(in) file_name, type(calypso_mpi_io_params), intent(inout) IO_param)
Definition at line 47 of file gz_MPI_binary_datum_IO.f90.
References gz_mpi_binary_head_io::gz_mpi_write_byte_flag(), and mpi_ascii_data_io::open_write_mpi_file().
Referenced by gz_mpi_sph_modes_file_io_b::gz_mpi_write_geom_rtm_file_b(), gz_mpi_sph_modes_file_io_b::gz_mpi_write_geom_rtp_file_b(), gz_mpi_mesh_file_io_b::gz_mpi_write_mesh_file_b(), gz_mpi_sph_modes_file_io_b::gz_mpi_write_modes_rlm_file_b(), gz_mpi_sph_modes_file_io_b::gz_mpi_write_spectr_rj_file_b(), gz_field_file_mpi_io_b::gz_write_step_fld_file_mpi_b(), gz_ucd_field_mpi_io_b::gz_write_ucd_field_file_mpi_b(), gz_write_udt_file_io_b::gz_write_ucd_file_mpi_b(), gz_write_udt_file_io_b::gz_write_ucd_grid_mpi_b(), and gz_write_udt_file_io_b::gz_write_ucd_phys_mpi_b().