CALYPSO: m_elapsed_labels_gen_sph Module Reference
m_elapsed_labels_gen_sph Module Reference
Labels for elapsed time monitor.
Functions/Subroutines
subroutine elpsed_label_gen_sph_grid
Variables
logical, save iflag_gsp_time = .FALSE.
integer(kind=kint), save ist_elapsed_gsp = 0
integer(kind=kint), save ied_elapsed_gsp = 0
Detailed Description
Labels for elapsed time monitor.
      subroutine elpsed_label_gen_sph_grid
Function/Subroutine Documentation
elpsed_label_gen_sph_grid()
subroutine m_elapsed_labels_gen_sph::elpsed_label_gen_sph_grid
Definition at line 30 of file m_elapsed_labels_gen_SPH.f90.
References m_work_time::append_elapsed_times(), m_work_time::elps1, ied_elapsed_gsp, iflag_gsp_time, and ist_elapsed_gsp.
Referenced by analyzer_check_sph_grids::init_check_sph_grids(), analyzer_gen_sph_grids::init_gen_sph_grids(), and init_sph_mhd_elapsed_label::set_sph_mhd_elapsed_label().
Variable Documentation
ied_elapsed_gsp
integer(kind = kint), save m_elapsed_labels_gen_sph::ied_elapsed_gsp = 0
Definition at line 22 of file m_elapsed_labels_gen_SPH.f90.
Referenced by elpsed_label_gen_sph_grid().
iflag_gsp_time
logical, save m_elapsed_labels_gen_sph::iflag_gsp_time = .FALSE.
Definition at line 20 of file m_elapsed_labels_gen_SPH.f90.
Referenced by analyzer_check_sph_grids::analyze_check_sph_grids(), analyzer_gen_sph_grids::analyze_gen_sph_grids(), t_check_and_make_sph_mesh::check_and_make_sph_mesh(), t_check_and_make_sph_mesh::check_and_make_sph_rj_mode(), elpsed_label_gen_sph_grid(), mpi_gen_sph_grids_modes::mpi_gen_sph_grids(), mpi_gen_sph_grids_modes::mpi_gen_sph_rj_mode(), t_parai_gen_sph_grids_modes::para_gen_sph_rlm_rj_modes(), and t_parai_gen_sph_grids_modes::para_gen_sph_rtm_rtp_grids().
ist_elapsed_gsp
integer(kind = kint), save m_elapsed_labels_gen_sph::ist_elapsed_gsp = 0
Definition at line 21 of file m_elapsed_labels_gen_SPH.f90.
Referenced by analyzer_check_sph_grids::analyze_check_sph_grids(), analyzer_gen_sph_grids::analyze_gen_sph_grids(), t_check_and_make_sph_mesh::check_and_make_sph_mesh(), t_check_and_make_sph_mesh::check_and_make_sph_rj_mode(), elpsed_label_gen_sph_grid(), mpi_gen_sph_grids_modes::mpi_gen_sph_grids(), mpi_gen_sph_grids_modes::mpi_gen_sph_rj_mode(), t_parai_gen_sph_grids_modes::para_gen_sph_rlm_rj_modes(), and t_parai_gen_sph_grids_modes::para_gen_sph_rtm_rtp_grids().