CALYPSO: t_sph_volume_mean_square Module Reference
t_sph_volume_mean_square Module Reference
Mean sqare data.
Data Types
type sph_vol_mean_squares
Structure of mean square data over volume.
Functions/Subroutines
subroutine alloc_sph_vol_mean_square (id_rank, ltr, num_fld_sq, ntot_comp_sq, v_pwr)
subroutine alloc_sph_vol_ave (idx_rj_degree_zero, v_pwr)
subroutine dealloc_sph_vol_mean_square (v_pwr)
subroutine dealloc_sph_vol_ave (idx_rj_degree_zero, v_pwr)
Detailed Description
Mean sqare data.
      subroutine alloc_sph_vol_mean_square                            &
     &         (id_rank, ltr, num_fld_sq, ntot_comp_sq, v_pwr)
      subroutine alloc_sph_vol_ave(idx_rj_degree_zero, v_pwr)
        type(sph_vol_mean_squares), intent(inout) :: v_pwr
      subroutine dealloc_sph_vol_mean_square(v_pwr)
      subroutine dealloc_sph_vol_ave(idx_rj_degree_zero, v_pwr)
        type(sph_vol_mean_squares), intent(inout) :: v_pwr
Parameters
id_rank Process ID
Function/Subroutine Documentation
alloc_sph_vol_ave()
subroutine t_sph_volume_mean_square::alloc_sph_vol_ave (integer(kind = kint), intent(in) idx_rj_degree_zero, type(sph_vol_mean_squares), intent(inout) v_pwr)
Definition at line 148 of file t_sph_volume_mean_square.f90.
Referenced by t_rms_4_sph_spectr::alloc_ave_4_sph_spectr().
alloc_sph_vol_mean_square()
subroutine t_sph_volume_mean_square::alloc_sph_vol_mean_square (integer, intent(in) id_rank, integer(kind = kint), intent(in) ltr, integer(kind = kint), intent(in) num_fld_sq, integer(kind = kint), intent(in) ntot_comp_sq, type(sph_vol_mean_squares), intent(inout) v_pwr)
Definition at line 95 of file t_sph_volume_mean_square.f90.
Referenced by t_rms_4_sph_spectr::alloc_rms_4_sph_spectr().
dealloc_sph_vol_ave()
subroutine t_sph_volume_mean_square::dealloc_sph_vol_ave (integer(kind = kint), intent(in) idx_rj_degree_zero, type(sph_vol_mean_squares), intent(inout) v_pwr)
Definition at line 179 of file t_sph_volume_mean_square.f90.
Referenced by t_rms_4_sph_spectr::dealloc_ave_4_sph_spectr().
dealloc_sph_vol_mean_square()
subroutine t_sph_volume_mean_square::dealloc_sph_vol_mean_square (type(sph_vol_mean_squares), intent(inout) v_pwr)
Definition at line 165 of file t_sph_volume_mean_square.f90.
Referenced by t_rms_4_sph_spectr::dealloc_rms_4_sph_spectr().