CALYPSO: element_data_io Module Reference
element_data_io Module Reference
Data IO routines for element data.
Functions/Subroutines
subroutine read_element_comm_table (id_file, id_rank, comm_IO, ierr)
subroutine write_element_comm_table (id_file, id_rank, comm_IO)
subroutine read_element_geometry (id_file, nod_IO, sfed_IO)
subroutine write_element_geometry (id_file, nod_IO, sfed_IO)
subroutine write_element_geometry_sph (id_file, nod_IO, sfed_IO)
subroutine write_element_geometry_cyl (id_file, nod_IO, sfed_IO)
Detailed Description
Data IO routines for element data.
      subroutine read_element_comm_table                              &
     &         (id_file, id_rank, comm_IO, ierr)
        type(communication_table), intent(inout) :: comm_IO
      subroutine write_element_comm_table                             &
     &         (id_file, id_rank, comm_IO)
        type(communication_table), intent(in) :: comm_IO
      subroutine read_element_geometry(id_file, nod_IO, sfed_IO)
        type(node_data), intent(inout) :: nod_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
      subroutine write_element_geometry(id_file, nod_IO, sfed_IO)
      subroutine write_element_geometry_sph(id_file, nod_IO, sfed_IO)
      subroutine write_element_geometry_cyl(id_file, nod_IO, sfed_IO)
        type(node_data), intent(in) :: nod_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
Function/Subroutine Documentation
read_element_comm_table()
subroutine element_data_io::read_element_comm_table (integer (kind = kint), intent(in) id_file, integer, intent(in) id_rank, type(communication_table), intent(inout) comm_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 45 of file element_data_IO.f90.
References domain_data_io::read_domain_info(), domain_data_io::read_export_data(), and domain_data_io::read_import_data().
Referenced by element_file_io::input_element_file().
read_element_geometry()
subroutine element_data_io::read_element_geometry (integer (kind = kint), intent(in) id_file, type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 109 of file element_data_IO.f90.
References node_geometry_io::read_geometry_info(), node_geometry_io::read_number_of_node(), and node_geometry_io::read_scalar_in_element().
write_element_comm_table()
subroutine element_data_io::write_element_comm_table (integer (kind = kint), intent(in) id_file, integer, intent(in) id_rank, type(communication_table), intent(in) comm_IO)
Definition at line 83 of file element_data_IO.f90.
References m_fem_surface_labels::hd_ecomm_export(), m_fem_surface_labels::hd_ecomm_import(), m_fem_surface_labels::hd_ecomm_para(), m_fem_mesh_labels::hd_fem_para(), domain_data_io::write_domain_info(), domain_data_io::write_export_data(), and domain_data_io::write_import_data().
Referenced by element_file_io::output_element_file().
write_element_geometry()
subroutine element_data_io::write_element_geometry (integer (kind = kint), intent(in) id_file, type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 137 of file element_data_IO.f90.
References m_fem_surface_labels::hd_ecomm_point(), m_fem_surface_labels::hd_ecomm_vol(), node_geometry_io::write_geometry_info(), and node_geometry_io::write_scalar_in_element().
write_element_geometry_cyl()
subroutine element_data_io::write_element_geometry_cyl (integer (kind = kint), intent(in) id_file, type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 180 of file element_data_IO.f90.
References m_fem_surface_labels::hd_ecomm_vol(), node_geometry_io::write_geometry_info(), and node_geometry_io::write_scalar_in_element().
write_element_geometry_sph()
subroutine element_data_io::write_element_geometry_sph (integer (kind = kint), intent(in) id_file, type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 156 of file element_data_IO.f90.
References m_fem_surface_labels::hd_ecomm_vol(), node_geometry_io::write_geometry_info(), and node_geometry_io::write_scalar_in_element().