var dir_3bf697d4c6c15d1860ed7a03fa5aa9bb =
[
    [ "add_nodal_fields_4_MHD.f90", "d6/d52/add__nodal__fields__4___m_h_d_8f90.html", "d6/d52/add__nodal__fields__4___m_h_d_8f90" ],
    [ "add_sph_MHD_fields_2_ctl.f90", "dc/d81/add__sph___m_h_d__fields__2__ctl_8f90.html", "dc/d81/add__sph___m_h_d__fields__2__ctl_8f90" ],
    [ "check_read_bc_file.f90", "dc/d85/check__read__bc__file_8f90.html", "dc/d85/check__read__bc__file_8f90" ],
    [ "init_sph_MHD_elapsed_label.F90", "df/d90/init__sph___m_h_d__elapsed__label_8_f90.html", "df/d90/init__sph___m_h_d__elapsed__label_8_f90" ],
    [ "m_boundary_condition_IDs.f90", "df/d2b/m__boundary__condition___i_ds_8f90.html", "df/d2b/m__boundary__condition___i_ds_8f90" ],
    [ "m_ctl_data_sph_MHD.f90", "dd/daa/m__ctl__data__sph___m_h_d_8f90.html", "dd/daa/m__ctl__data__sph___m_h_d_8f90" ],
    [ "m_force_control_labels.f90", "dd/df1/m__force__control__labels_8f90.html", "dd/df1/m__force__control__labels_8f90" ],
    [ "output_viz_file_control.f90", "db/d1f/output__viz__file__control_8f90.html", "db/d1f/output__viz__file__control_8f90" ],
    [ "set_control_4_composition.f90", "dd/d62/set__control__4__composition_8f90.html", "dd/d62/set__control__4__composition_8f90" ],
    [ "set_control_4_force.f90", "db/d6d/set__control__4__force_8f90.html", "db/d6d/set__control__4__force_8f90" ],
    [ "set_control_4_magne.f90", "d3/d63/set__control__4__magne_8f90.html", "d3/d63/set__control__4__magne_8f90" ],
    [ "set_control_4_model.f90", "d7/d8b/set__control__4__model_8f90.html", "d7/d8b/set__control__4__model_8f90" ],
    [ "set_control_4_normalize.f90", "df/d62/set__control__4__normalize_8f90.html", "df/d62/set__control__4__normalize_8f90" ],
    [ "set_control_4_press.f90", "d3/d0e/set__control__4__press_8f90.html", "d3/d0e/set__control__4__press_8f90" ],
    [ "set_control_4_temp.f90", "df/d93/set__control__4__temp_8f90.html", "df/d93/set__control__4__temp_8f90" ],
    [ "set_control_4_velo.f90", "d3/ddd/set__control__4__velo_8f90.html", "d3/ddd/set__control__4__velo_8f90" ],
    [ "set_node_group_types.f90", "dd/d3c/set__node__group__types_8f90.html", "dd/d3c/set__node__group__types_8f90" ],
    [ "set_surface_group_types.f90", "de/d4f/set__surface__group__types_8f90.html", "de/d4f/set__surface__group__types_8f90" ],
    [ "sph_mhd_rst_IO_control.f90", "db/de8/sph__mhd__rst___i_o__control_8f90.html", "db/de8/sph__mhd__rst___i_o__control_8f90" ],
    [ "t_bc_data_list.f90", "dd/dd9/t__bc__data__list_8f90.html", "dd/dd9/t__bc__data__list_8f90" ],
    [ "t_control_data_dynamo_vizs.f90", "d6/d11/t__control__data__dynamo__vizs_8f90.html", "d6/d11/t__control__data__dynamo__vizs_8f90" ],
    [ "t_ctl_data_crust_filter.f90", "df/d7e/t__ctl__data__crust__filter_8f90.html", "df/d7e/t__ctl__data__crust__filter_8f90" ],
    [ "t_ctl_data_induct_norm.f90", "d2/d3e/t__ctl__data__induct__norm_8f90.html", "d2/d3e/t__ctl__data__induct__norm_8f90" ],
    [ "t_ctl_data_MHD.f90", "d8/d69/t__ctl__data___m_h_d_8f90.html", "d8/d69/t__ctl__data___m_h_d_8f90" ],
    [ "t_ctl_data_mhd_evo_scheme.f90", "d3/da3/t__ctl__data__mhd__evo__scheme_8f90.html", "d3/da3/t__ctl__data__mhd__evo__scheme_8f90" ],
    [ "t_ctl_data_mhd_evolution.f90", "d1/d6d/t__ctl__data__mhd__evolution_8f90.html", "d1/d6d/t__ctl__data__mhd__evolution_8f90" ],
    [ "t_ctl_data_mhd_forces.f90", "dc/d16/t__ctl__data__mhd__forces_8f90.html", "dc/d16/t__ctl__data__mhd__forces_8f90" ],
    [ "t_ctl_data_MHD_model.f90", "d1/ddb/t__ctl__data___m_h_d__model_8f90.html", "d1/ddb/t__ctl__data___m_h_d__model_8f90" ],
    [ "t_ctl_data_mhd_normalize.f90", "d7/d25/t__ctl__data__mhd__normalize_8f90.html", "d7/d25/t__ctl__data__mhd__normalize_8f90" ],
    [ "t_ctl_data_momentum_norm.f90", "d2/d08/t__ctl__data__momentum__norm_8f90.html", "d2/d08/t__ctl__data__momentum__norm_8f90" ],
    [ "t_ctl_data_node_boundary.f90", "d1/df1/t__ctl__data__node__boundary_8f90.html", "d1/df1/t__ctl__data__node__boundary_8f90" ],
    [ "t_ctl_data_node_monitor.f90", "df/da7/t__ctl__data__node__monitor_8f90.html", "df/da7/t__ctl__data__node__monitor_8f90" ],
    [ "t_ctl_data_sph_MHD.f90", "dd/d22/t__ctl__data__sph___m_h_d_8f90.html", null ],
    [ "t_ctl_data_SPH_MHD_control.f90", "d9/de3/t__ctl__data___s_p_h___m_h_d__control_8f90.html", "d9/de3/t__ctl__data___s_p_h___m_h_d__control_8f90" ],
    [ "t_ctl_data_sph_MHD_psf.f90", "d1/d8f/t__ctl__data__sph___m_h_d__psf_8f90.html", "d1/d8f/t__ctl__data__sph___m_h_d__psf_8f90" ],
    [ "t_ctl_data_surf_boundary.f90", "df/db1/t__ctl__data__surf__boundary_8f90.html", "df/db1/t__ctl__data__surf__boundary_8f90" ],
    [ "t_ctl_data_temp_model.f90", "d8/d95/t__ctl__data__temp__model_8f90.html", "d8/d95/t__ctl__data__temp__model_8f90" ],
    [ "t_ctl_data_termal_norm.f90", "d0/dd2/t__ctl__data__termal__norm_8f90.html", "d0/dd2/t__ctl__data__termal__norm_8f90" ],
    [ "t_MHD_IO_data.f90", "d2/dd3/t___m_h_d___i_o__data_8f90.html", [
      [ "mhd_io_data", "db/ddc/structt__mhd__io__data_1_1mhd__io__data.html", "db/ddc/structt__mhd__io__data_1_1mhd__io__data" ]
    ] ],
    [ "t_sph_boundary_input_data.f90", "d7/dae/t__sph__boundary__input__data_8f90.html", "d7/dae/t__sph__boundary__input__data_8f90" ],
    [ "t_ucd_file.f90", "d3/dec/t__ucd__file_8f90.html", "d3/dec/t__ucd__file_8f90" ]
];