CALYPSO: m_sph_mhd_model_data Module Reference
m_sph_mhd_model_data Module Reference
Instace of Structures for spherical shell dynamo.
Variables
type(sph_mhd_model_data), save sph_model1
Parameters for spectr dynamo model.
type(work_sph_mhd), save sph_wk1
Structures of work area for spherical shell dynamo.
type(fem_mesh_field_data), save fem_d1
Structure of FEM mesh and field structures.
type(sph_zonal_mean_sectioning), save zmeans1
Structures of zonal mean controls.
Detailed Description
Instace of Structures for spherical shell dynamo.
Variable Documentation
fem_d1
type(fem_mesh_field_data), save m_sph_mhd_model_data::fem_d1
Structure of FEM mesh and field structures.
Definition at line 33 of file m_SPH_MHD_model_data.f90.
Referenced by analyzer_sph_mhd_w_psf::evolution_sph_mhd_w_psf(), analyzer_sph_snap_w_psf::evolution_sph_snap_w_psf(), sph_analyzer_add_initial::initialize_add_sph_initial(), sph_analyzer_const_initial::initialize_const_sph_initial(), analyzer_sph_dynamobench::initialize_sph_dynamobench(), analyzer_sph_mhd_w_psf::initialize_sph_mhd_w_psf(), and analyzer_sph_snap_w_psf::initialize_sph_snap_w_psf().
sph_model1
type(sph_mhd_model_data), save m_sph_mhd_model_data::sph_model1
Parameters for spectr dynamo model.
Definition at line 26 of file m_SPH_MHD_model_data.f90.
Referenced by analyzer_sph_dynamobench::evolution_sph_dynamobench(), analyzer_sph_mhd_w_psf::evolution_sph_mhd_w_psf(), analyzer_sph_snap_w_psf::evolution_sph_snap_w_psf(), sph_analyzer_add_initial::initialize_add_sph_initial(), sph_analyzer_const_initial::initialize_const_sph_initial(), analyzer_sph_dynamobench::initialize_sph_dynamobench(), analyzer_sph_mhd_w_psf::initialize_sph_mhd_w_psf(), and analyzer_sph_snap_w_psf::initialize_sph_snap_w_psf().
sph_wk1
type(work_sph_mhd), save m_sph_mhd_model_data::sph_wk1
Structures of work area for spherical shell dynamo.
Definition at line 30 of file m_SPH_MHD_model_data.f90.
Referenced by analyzer_sph_dynamobench::evolution_sph_dynamobench(), analyzer_sph_mhd_w_psf::evolution_sph_mhd_w_psf(), analyzer_sph_snap_w_psf::evolution_sph_snap_w_psf(), sph_analyzer_add_initial::initialize_add_sph_initial(), sph_analyzer_const_initial::initialize_const_sph_initial(), analyzer_sph_dynamobench::initialize_sph_dynamobench(), analyzer_sph_mhd_w_psf::initialize_sph_mhd_w_psf(), and analyzer_sph_snap_w_psf::initialize_sph_snap_w_psf().
zmeans1
type(sph_zonal_mean_sectioning), save m_sph_mhd_model_data::zmeans1
Structures of zonal mean controls.
Definition at line 36 of file m_SPH_MHD_model_data.f90.
Referenced by analyzer_sph_mhd_w_psf::evolution_sph_mhd_w_psf(), analyzer_sph_snap_w_psf::evolution_sph_snap_w_psf(), analyzer_sph_mhd_w_psf::initialize_sph_mhd_w_psf(), and analyzer_sph_snap_w_psf::initialize_sph_snap_w_psf().