CALYPSO: field_data_io Module Reference
field_data_io Module Reference
Data IO rountines for field data IO.
Functions/Subroutines
character(len=25+1+num_pe *16+1) function field_istack_nod_buffer (num_pe, istack_nod)
character(len=num_pe *16+1) function buffer_istack_nod_buffer (num_pe, istack_nod)
character(len=31+1+16+1) function field_num_buffer (num_field)
character(len=num_field *5+1) function field_comp_buffer (num_field, ncomp_field)
character(len=len_trim(field_name)+1) function each_field_name_buffer (field_name)
subroutine read_arrays_for_stacks (file_id, num, istack_begin, ntot, istack)
subroutine read_field_istack_nod_buffer (textbuf, num_pe, istack_nod)
subroutine read_buffer_istack_nod_buffer (textbuf, num_pe, istack_nod)
subroutine read_field_num_buffer (textbuf, num_field)
subroutine read_field_comp_buffer (textbuf, num_field, ncomp_field)
subroutine read_each_field_name_buffer (textbuf, field_name, len_text)
subroutine write_arrays_for_stacks (file_id, num, istack)
subroutine write_field_data (id_file, nnod64, num_field, ntot_comp, ncomp_field, field_name, field_data)
subroutine read_field_data (id_file, nnod64, num_field, ntot_comp, ncomp_field, field_name, field_data)
subroutine read_field_name (id_file, nnod64, num_field, ncomp_field, field_name)
Variables
character(len=25), parameter fld_hd0 = '! List of Number of nodes'
character(len=31), parameter, private fld_hd1 = '! Number of field and component'
Detailed Description
Data IO rountines for field data IO.
      function field_istack_nod_buffer(num_pe, istack_nod)
      function buffer_istack_nod_buffer(num_pe, istack_nod)
      function field_num_buffer(num_field)
      function field_comp_buffer(num_field, ncomp_field)
      function each_field_name_buffer(field_name)
      subroutine read_arrays_for_stacks(file_id, num, istack_begin,   &
      &         ntot, istack)
      subroutine read_field_num_buffer(textbuf, nnod, num_field)
      subroutine read_buffer_istack_nod_buffer                        &
     &         (textbuf, num_pe, istack_nod)
      subroutine read_field_comp_buffer                               &
     &         (textbuf, num_field, ncomp_field)
      subroutine read_each_field_name_buffer                          &
     &         (textbuf, field_name, len_text)
      subroutine write_arrays_for_stacks(file_id, num, istack)
      subroutine write_field_data                                     &
     &         (id_file, nnod64, num_field, ntot_comp,                &
     &          ncomp_field, field_name, field_data)
      subroutine read_field_data                                      &
     &         (id_file, nnod64, num_field, ntot_comp,                &
     &          ncomp_field, field_name, field_data)
      subroutine read_field_name                                      &
     &         (id_file, nnod64, num_field, ntot_comp,                &
     &          ncomp_field, field_name)
Function/Subroutine Documentation
buffer_istack_nod_buffer()
character(len=num_pe*16+1) function field_data_io::buffer_istack_nod_buffer (integer, intent(in) num_pe, integer(kind = kint_gl), dimension(0:num_pe), intent(in) istack_nod)
Definition at line 72 of file field_data_IO.f90.
Referenced by field_istack_nod_buffer(), gz_field_data_mpi_io::gz_write_fld_vecotr_mpi(), field_block_mpi_io::read_fld_vecotr_mpi(), field_block_mpi_io::skip_fld_vecotr_mpi(), and field_block_mpi_io::write_fld_vecotr_mpi().
each_field_name_buffer()
character(len=len_trim(field_name)+1) function field_data_io::each_field_name_buffer (character(len=kchara), intent(in) field_name)
Definition at line 124 of file field_data_IO.f90.
Referenced by gz_field_block_mpi_io::write_field_data_gz_mpi(), and field_data_mpi_io::write_field_name_mpi().
field_comp_buffer()
character(len=num_field*5+1) function field_data_io::field_comp_buffer (integer(kind = kint), intent(in) num_field, integer(kind = kint), dimension(num_field), intent(in) ncomp_field)
Definition at line 107 of file field_data_IO.f90.
Referenced by field_block_mpi_io::write_field_data_mpi(), and gz_field_block_mpi_io::write_field_head_gz_mpi().
field_istack_nod_buffer()
character(len=25+1+num_pe*16+1) function field_data_io::field_istack_nod_buffer (integer, intent(in) num_pe, integer(kind = kint_gl), dimension(0:num_pe), intent(in) istack_nod)
Definition at line 58 of file field_data_IO.f90.
References buffer_istack_nod_buffer(), and fld_hd0.
Referenced by field_block_mpi_io::write_field_data_mpi(), and gz_field_block_mpi_io::write_field_head_gz_mpi().
field_num_buffer()
character(len=31+1+16+1) function field_data_io::field_num_buffer (integer(kind = kint), intent(in) num_field)
Definition at line 91 of file field_data_IO.f90.
References fld_hd1.
Referenced by gz_field_block_mpi_io::read_field_header_gz_mpi(), field_block_mpi_io::write_field_data_mpi(), and gz_field_block_mpi_io::write_field_head_gz_mpi().
read_arrays_for_stacks()
subroutine field_data_io::read_arrays_for_stacks (integer (kind = kint), intent(in) file_id, integer (kind = kint), intent(in) num, integer (kind = kint), intent(in) istack_begin, integer (kind = kint), intent(inout) ntot, integer (kind = kint), dimension(0:num), intent(inout) istack)
Definition at line 138 of file field_data_IO.f90.
References skip_comment_f::skip_comment().
Referenced by domain_data_io::read_export_data(), group_data_io::read_group_stack(), and domain_data_io::read_import_data().
read_buffer_istack_nod_buffer()
subroutine field_data_io::read_buffer_istack_nod_buffer (character(num_pe*16+1), intent(in) textbuf, integer, intent(in) num_pe, integer(kind = kint_gl), dimension(0:num_pe), intent(inout) istack_nod)
Definition at line 198 of file field_data_IO.f90.
Referenced by gz_field_data_mpi_io::gz_read_each_field_mpi(), and gz_field_data_mpi_io::gz_skip_each_field_mpi().
read_each_field_name_buffer()
subroutine field_data_io::read_each_field_name_buffer (character(len=kchara), intent(in) textbuf, character(len=kchara), intent(inout) field_name, integer, intent(inout) len_text)
Definition at line 246 of file field_data_IO.f90.
Referenced by zlib_convert_text::infleate_1word(), and field_data_mpi_io::read_field_name_mpi().
read_field_comp_buffer()
subroutine field_data_io::read_field_comp_buffer (character(len=num_field*5+1), intent(in) textbuf, integer(kind = kint), intent(in) num_field, integer(kind = kint), dimension(num_field), intent(inout) ncomp_field)
Definition at line 229 of file field_data_IO.f90.
Referenced by gz_field_block_mpi_io::read_field_num_gz_mpi(), and field_data_mpi_io::read_field_num_mpi().
read_field_data()
subroutine field_data_io::read_field_data (integer(kind = kint), intent(in) id_file, integer(kind = kint_gl), intent(in) nnod64, integer(kind = kint), intent(in) num_field, integer(kind = kint), intent(in) ntot_comp, integer(kind = kint), dimension(num_field), intent(in) ncomp_field, character(len=kchara), dimension(num_field), intent(inout) field_name, real(kind = kreal), dimension(nnod64, ntot_comp), intent(inout) field_data)
Definition at line 320 of file field_data_IO.f90.
References skip_comment_f::skip_comment().
Referenced by ucd_field_file_io::read_alloc_ucd_2_fld_file(), field_file_io::read_and_alloc_step_field(), field_file_io::read_and_allocate_field_file(), rst_data_io_by_fld::read_rst_file(), field_file_io::read_step_field_file(), and ucd_field_file_io::read_ucd_2_fld_file().
read_field_istack_nod_buffer()
subroutine field_data_io::read_field_istack_nod_buffer (character(len=25+1+num_pe*16+1), intent(in) textbuf, integer, intent(in) num_pe, integer(kind = kint_gl), dimension(0:num_pe), intent(inout) istack_nod)
Definition at line 181 of file field_data_IO.f90.
Referenced by gz_field_block_mpi_io::read_field_header_gz_mpi(), and field_data_mpi_io::read_field_header_mpi().
read_field_name()
subroutine field_data_io::read_field_name (integer(kind = kint), intent(in) id_file, integer(kind = kint_gl), intent(in) nnod64, integer(kind = kint), intent(in) num_field, integer(kind = kint), dimension(num_field), intent(in) ncomp_field, character(len=kchara), dimension(num_field), intent(inout) field_name)
Definition at line 358 of file field_data_IO.f90.
References skip_comment_f::skip_comment().
Referenced by field_file_io::read_and_allocate_step_head().
read_field_num_buffer()
subroutine field_data_io::read_field_num_buffer (character(len=49), intent(in) textbuf, integer(kind = kint), intent(inout) num_field)
Definition at line 215 of file field_data_IO.f90.
Referenced by gz_field_block_mpi_io::read_field_header_gz_mpi(), and field_data_mpi_io::read_field_header_mpi().
write_arrays_for_stacks()
subroutine field_data_io::write_arrays_for_stacks (integer (kind = kint), intent(in) file_id, integer (kind = kint), intent(in) num, integer (kind = kint), dimension(0:num), intent(in) istack)
Definition at line 268 of file field_data_IO.f90.
write_field_data()
subroutine field_data_io::write_field_data (integer(kind = kint), intent(in) id_file, integer(kind = kint_gl), intent(in) nnod64, integer(kind = kint), intent(in) num_field, integer(kind = kint), intent(in) ntot_comp, integer(kind = kint), dimension(num_field), intent(in) ncomp_field, character(len=kchara), dimension(num_field), intent(in) field_name, real(kind = kreal), dimension(nnod64, ntot_comp), intent(in) field_data)
Definition at line 281 of file field_data_IO.f90.
References fld_hd1.
Referenced by field_file_io::write_step_field_file(), and ucd_field_file_io::write_ucd_2_fld_file().
Variable Documentation
fld_hd0
character(len=25), parameter field_data_io::fld_hd0 = '! List of Number of nodes'
Definition at line 45 of file field_data_IO.f90.
Referenced by field_istack_nod_buffer().
fld_hd1
character(len=31), parameter, private field_data_io::fld_hd1 = '! Number of field and component' private
Definition at line 47 of file field_data_IO.f90.
Referenced by field_num_buffer(), and write_field_data().