CALYPSO: t_control_data_4_fld_on_psf Module Reference
t_control_data_4_fld_on_psf Module Reference
control data for field on isosurface
Data Types
type field_on_psf_ctl
Structure of fields on isosurface control.
Functions/Subroutines
subroutine init_fld_on_psf_control (fld_on_psf_c)
subroutine dealloc_fld_on_psf_control (fld_on_psf_c)
subroutine dup_fld_on_psf_control (org_fld_on_iso_c, new_fld_on_iso_c)
subroutine read_fld_on_psf_control (id_control, hd_block, fld_on_psf_c, c_buf)
subroutine bcast_fld_on_psf_control (fld_on_psf_c)
integer(kind=kint) function num_label_fld_on_psf_control ()
subroutine set_label_fld_on_psf_control (names)
Variables
character(len=kchara), parameter, private hd_result_type = 'result_type'
character(len=kchara), parameter, private hd_iso_result_field = 'output_field'
character(len=kchara), parameter, private hd_result_value = 'result_value'
integer(kind=kint), parameter n_label_fld_on_psf_ctl = 3
Detailed Description
control data for field on isosurface
      subroutine init_fld_on_psf_control(fld_on_psf_c)
      subroutine dealloc_fld_on_psf_control(fld_on_psf_c)
        type(field_on_psf_ctl), intent(inout) :: fld_on_psf_c
      subroutine dup_fld_on_psf_control                               &
     &         (org_fld_on_iso_c, new_fld_on_iso_c)
        type(field_on_psf_ctl), intent(in) :: org_fld_on_iso_c
        type(field_on_psf_ctl), intent(inout) :: new_fld_on_iso_c
      subroutine read_fld_on_psf_control                              &
     &         (id_control, hd_block, fld_on_psf_c, c_buf)
      subroutine bcast_fld_on_psf_control(fld_on_psf_c)
        type(field_on_psf_ctl), intent(inout) :: fld_on_psf_c
      integer(kind = kint) function num_label_fld_on_psf_control()
      subroutine set_label_fld_on_psf_control(names)
     example of control for Kemo's surface rendering
    begin field_on_isosurf
      result_type      constant
      result_value     0.7
      array output_field   2
        output_field    velocity         vector   end
        output_field    magnetic_field   radial   end
      end array output_field
    end field_on_isosurf
    result_type:  (Original name: display_method)
                   specified_fields
                   constant
    output_field: (Original name: color_comp and color_subcomp)
         field and componenet name for output
           x, y, z, radial, elevation, azimuth, cylinder_r
           norm, vector, tensor, spherical_vector, cylindrical_vector
    result_value: (Original name: specified_color)
Function/Subroutine Documentation
bcast_fld_on_psf_control()
subroutine t_control_data_4_fld_on_psf::bcast_fld_on_psf_control (type(field_on_psf_ctl), intent(inout) fld_on_psf_c)
Definition at line 175 of file t_control_data_4_fld_on_psf.f90.
References bcast_control_arrays::bcast_ctl_array_c2(), bcast_control_arrays::bcast_ctl_type_c1(), bcast_control_arrays::bcast_ctl_type_r1(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by t_control_data_4_psf::bcast_psf_control_data().
dealloc_fld_on_psf_control()
subroutine t_control_data_4_fld_on_psf::dealloc_fld_on_psf_control (type(field_on_psf_ctl), intent(inout) fld_on_psf_c)
Definition at line 105 of file t_control_data_4_fld_on_psf.f90.
References t_control_array_character2::dealloc_control_array_c2().
Referenced by t_control_data_4_psf::dealloc_cont_dat_4_psf().
dup_fld_on_psf_control()
subroutine t_control_data_4_fld_on_psf::dup_fld_on_psf_control (type(field_on_psf_ctl), intent(in) org_fld_on_iso_c, type(field_on_psf_ctl), intent(inout) new_fld_on_iso_c)
Definition at line 123 of file t_control_data_4_fld_on_psf.f90.
References t_control_array_character::copy_chara_ctl(), t_control_array_real::copy_real_ctl(), and t_control_array_character2::dup_control_array_c2().
Referenced by t_control_data_4_psf::dup_control_4_psf().
init_fld_on_psf_control()
subroutine t_control_data_4_fld_on_psf::init_fld_on_psf_control (type(field_on_psf_ctl), intent(inout) fld_on_psf_c)
Definition at line 93 of file t_control_data_4_fld_on_psf.f90.
Referenced by t_control_data_4_psf::init_psf_ctl_stract().
num_label_fld_on_psf_control()
integer(kind = kint) function t_control_data_4_fld_on_psf::num_label_fld_on_psf_control
Definition at line 195 of file t_control_data_4_fld_on_psf.f90.
References n_label_fld_on_psf_ctl.
read_fld_on_psf_control()
subroutine t_control_data_4_fld_on_psf::read_fld_on_psf_control (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(field_on_psf_ctl), intent(inout) fld_on_psf_c, type(buffer_for_control), intent(inout) c_buf)
Definition at line 144 of file t_control_data_4_fld_on_psf.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_iso_result_field, hd_result_type, hd_result_value, t_read_control_elements::load_one_line_from_control(), t_control_array_character::read_chara_ctl_type(), t_control_array_character2::read_control_array_c2(), and t_control_array_real::read_real_ctl_type().
Referenced by t_control_data_4_psf::read_psf_control_data().
set_label_fld_on_psf_control()
subroutine t_control_data_4_fld_on_psf::set_label_fld_on_psf_control (character(len = kchara), dimension(n_label_fld_on_psf_ctl), intent(inout) names)
Definition at line 202 of file t_control_data_4_fld_on_psf.f90.
References hd_iso_result_field, hd_result_type, hd_result_value, and t_read_control_elements::set_control_labels().
Variable Documentation
hd_iso_result_field
character(len=kchara), parameter, private t_control_data_4_fld_on_psf::hd_iso_result_field = 'output_field' private
Definition at line 78 of file t_control_data_4_fld_on_psf.f90.
Referenced by read_fld_on_psf_control(), and set_label_fld_on_psf_control().
hd_result_type
character(len=kchara), parameter, private t_control_data_4_fld_on_psf::hd_result_type = 'result_type' private
Definition at line 76 of file t_control_data_4_fld_on_psf.f90.
Referenced by read_fld_on_psf_control(), and set_label_fld_on_psf_control().
hd_result_value
character(len=kchara), parameter, private t_control_data_4_fld_on_psf::hd_result_value = 'result_value' private
Definition at line 80 of file t_control_data_4_fld_on_psf.f90.
Referenced by read_fld_on_psf_control(), and set_label_fld_on_psf_control().
n_label_fld_on_psf_ctl
integer(kind = kint), parameter t_control_data_4_fld_on_psf::n_label_fld_on_psf_ctl = 3
Definition at line 83 of file t_control_data_4_fld_on_psf.f90.
Referenced by num_label_fld_on_psf_control().