CALYPSO: set_element_export_item Module Reference
set_element_export_item Module Reference
Routines to construca element communication table.
Functions/Subroutines
subroutine s_set_element_export_item (txt, numnod, numele, internal_flag, x_ele, iele_stack_4_node, iele_4_node, x_ref_ele, num_neib, istack_import, item_import, num_neib_e, istack_export_e, inod_export_l, xe_export, item_export_e)
subroutine element_export_item_in_ext (txt, numnod, numele, inod_global, internal_flag, x_ele, iele_stack_4_node, iele_4_node, x_ref_ele, num_neib, istack_export, item_export, num_neib_e, istack_export_e, inod_export_e, xe_export, item_export_e)
subroutine, private search_target_element (numele, internal_flag, x_ele, nele_4_node, iele_4_node, x_ref_ele, xe_export, item_export_e, dist_min, iflag, inum)
subroutine, private search_target_element3 (numele, internal_flag, x_ele, nele_4_node, iele_4_node, x_ref_ele, xe_export, item_export_e, dist_min, iflag, inum)
subroutine, private search_target_element2 (numele, internal_flag, x_ele, nele_4_node, iele_4_node, xe_export, item_export_e, dist_min, iflag, inum)
Variables
integer(kind=kint), parameter, private many = 64
many number
Detailed Description
Routines to construca element communication table.
      subroutine s_set_element_export_item                            &
     &         (txt, numnod, numele, internal_flag, x_ele,            &
     &          iele_stack_4_node, iele_4_node, x_ref_ele,            &
     &          num_neib, istack_import, item_import,                 &
     &          num_neib_e, istack_export_e, inod_export_l,           &
     &          xe_export, item_export_e)
      subroutine element_export_item_in_ext                           &
     &         (txt, numnod, numele, inod_global, internal_flag,      &
     &          x_ele, iele_stack_4_node, iele_4_node, x_ref_ele,     &
     &          num_neib, istack_export, item_export,                 &
     &          num_neib_e, istack_export_e, inod_export_e,           &
     &          xe_export, item_export_e)
Function/Subroutine Documentation
element_export_item_in_ext()
subroutine set_element_export_item::element_export_item_in_ext (character(len=kchara), intent(in) txt, integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) numele, integer(kind = kint_gl), dimension(numnod), intent(in) inod_global, integer(kind = kint), dimension(numele), intent(in) internal_flag, real(kind = kreal), dimension(numele,3), intent(in) x_ele, integer(kind = kint), dimension(0:numnod), intent(in) iele_stack_4_node, integer(kind = kint), dimension(iele_stack_4_node(numnod)), intent(in) iele_4_node, real(kind = kreal), dimension(iele_stack_4_node(numnod)), intent(in) x_ref_ele, integer(kind = kint), intent(in) num_neib, integer(kind = kint), dimension(0:num_neib), intent(in) istack_export, integer(kind = kint), dimension(istack_export(num_neib)), intent(in) item_export, integer(kind = kint), intent(in) num_neib_e, integer(kind = kint), dimension(0:num_neib_e), intent(in) istack_export_e, integer(kind = kint_gl), dimension(istack_export_e(num_neib_e)), intent(in) inod_export_e, real(kind = kreal), dimension(3*istack_export_e(num_neib_e)), intent(in) xe_export, integer(kind = kint), dimension(istack_export_e(num_neib_e)), intent(inout) item_export_e)
Definition at line 122 of file set_element_export_item.f90.
References calypso_mpi::my_rank, and search_target_element().
Referenced by const_element_comm_table::const_comm_table_by_connenct().
s_set_element_export_item()
subroutine set_element_export_item::s_set_element_export_item (character(len=kchara), intent(in) txt, integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) numele, integer(kind = kint), dimension(numele), intent(in) internal_flag, real(kind = kreal), dimension(numele,3), intent(in) x_ele, integer(kind = kint), dimension(0:numnod), intent(in) iele_stack_4_node, integer(kind = kint), dimension(iele_stack_4_node(numnod)), intent(in) iele_4_node, real(kind = kreal), dimension(iele_stack_4_node(numnod)), intent(in) x_ref_ele, integer(kind = kint), intent(in) num_neib, integer(kind = kint), dimension(0:num_neib), intent(in) istack_import, integer(kind = kint), dimension(istack_import(num_neib)), intent(in) item_import, integer(kind = kint), intent(in) num_neib_e, integer(kind = kint), dimension(0:num_neib_e), intent(in) istack_export_e, integer(kind = kint), dimension(istack_export_e(num_neib_e)), intent(in) inod_export_l, real(kind = kreal), dimension(3*istack_export_e(num_neib_e)), intent(in) xe_export, integer(kind = kint), dimension(istack_export_e(num_neib_e)), intent(inout) item_export_e)
Definition at line 44 of file set_element_export_item.f90.
References search_target_element().
Referenced by const_element_comm_table::const_comm_table_by_connenct().
search_target_element()
subroutine, private set_element_export_item::search_target_element (integer(kind = kint), intent(in) numele, integer(kind = kint), dimension(numele), intent(in) internal_flag, real(kind = kreal), dimension(numele,3), intent(in) x_ele, integer(kind = kint), intent(in) nele_4_node, integer(kind = kint), dimension(nele_4_node), intent(in) iele_4_node, real(kind = kreal), dimension(nele_4_node), intent(in) x_ref_ele, real(kind = kreal), dimension(3), intent(in) xe_export, integer(kind = kint), intent(inout) item_export_e, real(kind = kreal), intent(inout) dist_min, integer(kind = kint), intent(inout) iflag, integer(kind = kint), intent(in) inum) private
Definition at line 203 of file set_element_export_item.f90.
References many, search_target_element2(), and search_target_element3().
Referenced by element_export_item_in_ext(), and s_set_element_export_item().
search_target_element2()
subroutine, private set_element_export_item::search_target_element2 (integer(kind = kint), intent(in) numele, integer(kind = kint), dimension(numele), intent(in) internal_flag, real(kind = kreal), dimension(numele,3), intent(in) x_ele, integer(kind = kint), intent(in) nele_4_node, integer(kind = kint), dimension(nele_4_node), intent(in) iele_4_node, real(kind = kreal), dimension(3), intent(in) xe_export, integer(kind = kint), intent(inout) item_export_e, real(kind = kreal), intent(inout) dist_min, integer(kind = kint), intent(inout) iflag, integer(kind = kint), intent(in) inum) private
Definition at line 317 of file set_element_export_item.f90.
References m_constants::tiny.
Referenced by search_target_element(), and search_target_element3().
search_target_element3()
subroutine, private set_element_export_item::search_target_element3 (integer(kind = kint), intent(in) numele, integer(kind = kint), dimension(numele), intent(in) internal_flag, real(kind = kreal), dimension(numele,3), intent(in) x_ele, integer(kind = kint), intent(in) nele_4_node, integer(kind = kint), dimension(nele_4_node), intent(in) iele_4_node, real(kind = kreal), dimension(nele_4_node), intent(in) x_ref_ele, real(kind = kreal), dimension(3), intent(in) xe_export, integer(kind = kint), intent(inout) item_export_e, real(kind = kreal), intent(inout) dist_min, integer(kind = kint), intent(inout) iflag, integer(kind = kint), intent(in) inum) private
Definition at line 239 of file set_element_export_item.f90.
References many, search_target_element2(), and m_constants::tiny.
Referenced by search_target_element().
Variable Documentation
many
integer(kind = kint), parameter, private set_element_export_item::many = 64 private
many number
Definition at line 33 of file set_element_export_item.f90.
Referenced by search_target_element(), and search_target_element3().