CALYPSO: set_cross_section_coefs Module Reference
set_cross_section_coefs Module Reference
Set coefficients for cross section function.
Functions/Subroutines
subroutine set_coefs_4_plane (psf_def_c, c_surf)
subroutine set_coefs_4_sphere (psf_def_c, c_surf)
subroutine set_coefs_4_ellipsode (psf_def_c, c_surf)
subroutine set_coefs_4_hyperboloide (psf_def_c, c_surf)
subroutine set_coefs_4_parabolic (psf_def_c, c_surf)
Detailed Description
Set coefficients for cross section function.
      subroutine set_coefs_4_plane(psf_def_c, c_surf)
      subroutine set_coefs_4_sphere(psf_def_c, c_surf)
      subroutine set_coefs_4_ellipsode(psf_def_c, c_surf)
      subroutine set_coefs_4_hyperboloide(psf_def_c, c_surf)
      subroutine set_coefs_4_parabolic(psf_def_c, c_surf)
        type(psf_define_ctl), intent(in) :: psf_def_c
Function/Subroutine Documentation
set_coefs_4_ellipsode()
subroutine set_cross_section_coefs::set_coefs_4_ellipsode (type(psf_define_ctl), intent(in) psf_def_c, real(kind = kreal), dimension(10), intent(inout) c_surf)
Definition at line 96 of file set_cross_section_coefs.f90.
References m_constants::one, m_section_coef_flags::set_parameter_2_vectors(), m_constants::two, and m_constants::zero.
Referenced by set_coefs_of_sections::s_set_coefs_of_sections().
set_coefs_4_hyperboloide()
subroutine set_cross_section_coefs::set_coefs_4_hyperboloide (type(psf_define_ctl), intent(in) psf_def_c, real(kind = kreal), dimension(10), intent(inout) c_surf)
Definition at line 138 of file set_cross_section_coefs.f90.
References m_constants::one, m_section_coef_flags::set_parameter_2_vectors(), m_constants::two, and m_constants::zero.
Referenced by set_coefs_of_sections::s_set_coefs_of_sections().
set_coefs_4_parabolic()
subroutine set_cross_section_coefs::set_coefs_4_parabolic (type(psf_define_ctl), intent(in) psf_def_c, real(kind = kreal), dimension(10), intent(inout) c_surf)
Definition at line 173 of file set_cross_section_coefs.f90.
References m_constants::one, m_section_coef_flags::set_parameter_2_vectors(), m_constants::two, and m_constants::zero.
Referenced by set_coefs_of_sections::s_set_coefs_of_sections().
set_coefs_4_plane()
subroutine set_cross_section_coefs::set_coefs_4_plane (type(psf_define_ctl), intent(in) psf_def_c, real(kind = kreal), dimension(10), intent(inout) c_surf)
Definition at line 33 of file set_cross_section_coefs.f90.
References m_section_coef_flags::set_parameter_2_vectors(), and m_constants::zero.
Referenced by set_coefs_of_sections::s_set_coefs_of_sections().
set_coefs_4_sphere()
subroutine set_cross_section_coefs::set_coefs_4_sphere (type(psf_define_ctl), intent(in) psf_def_c, real(kind = kreal), dimension(10), intent(inout) c_surf)
Definition at line 65 of file set_cross_section_coefs.f90.
References m_constants::one, m_section_coef_flags::set_parameter_2_vectors(), m_constants::two, and m_constants::zero.
Referenced by set_coefs_of_sections::s_set_coefs_of_sections().