CALYPSO: legendre_bwd_sym_matmul Module Reference
legendre_bwd_sym_matmul Module Reference
backward Legendre transform (Developping version)
Functions/Subroutines
subroutine leg_b_trans_vec_sym_matmul (iflag_matmul, ncomp, nvector, sph_rlm, sph_rtm, comm_rlm, comm_rtm, idx_trns, asin_theta_1d_rtm, g_sph_rlm, n_WR, n_WS, WR, WS, WK_l_sml)
subroutine leg_b_trans_scl_sym_matmul (iflag_matmul, ncomp, nvector, nscalar, sph_rlm, sph_rtm, comm_rlm, comm_rtm, idx_trns, n_WR, n_WS, WR, WS, WK_l_sml)
Variables
real(kind=kreal), private st_elapsed
real(kind=kreal), dimension(4), private elaps
integer, external omp_get_max_threads
Detailed Description
backward Legendre transform (Developping version)
      subroutine leg_b_trans_vec_sym_matmul                           &
     &         (iflag_matmul, ncomp, nvector,                         &
     &          sph_rlm, sph_rtm, comm_rlm, comm_rtm, idx_trns,       &
     &          asin_theta_1d_rtm, g_sph_rlm,                         &
     &          n_WR, n_WS, WR, WS, WK_l_sml)
      subroutine leg_b_trans_scl_sym_matmul                           &
     &         (iflag_matmul, ncomp, nvector, nscalar,                &
     &          sph_rlm, sph_rtm, comm_rlm, comm_rtm, idx_trns,       &
     &          n_WR, n_WS, WR, WS, WK_l_sml)
        type(sph_rtm_grid), intent(in) :: sph_rtm
        type(sph_rlm_grid), intent(in) :: sph_rlm
        type(sph_comm_tbl), intent(in) :: comm_rlm, comm_rtm
        type(index_4_sph_trans), intent(in) :: idx_trns
        type(leg_trns_sym_mul_work), intent(inout) :: WK_l_sml
        Input:  sp_rlm
        Output: vr_rtm
     field data for Legendre transform
       original layout: vr_rtm(l_rtm,m_rtm,k_rlm,icomp)
       size: vr_rtm(nidx_rtm(2),nidx_rtm(1)*ncomp,nidx_rtm(3))
      real(kind = kreal), allocatable :: vr_rtm(:,:,:)
     spectr data for Legendre transform
       original layout: sp_rlm(j_rlm,k_rlm,icomp)
        size: sp_rlm(nidx_rlm(2),nidx_rtm(1)*ncomp)
      real(kind = kreal), allocatable :: sp_rlm(:,:)
Parameters
ncomp Total number of components for spherical transform
nvector Number of vector for spherical transform
nscalar Number of scalar (including tensor components) for spherical transform
Function/Subroutine Documentation
leg_b_trans_scl_sym_matmul()
subroutine legendre_bwd_sym_matmul::leg_b_trans_scl_sym_matmul (integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_comm_tbl), intent(in) comm_rlm, type(sph_comm_tbl), intent(in) comm_rtm, type(index_4_sph_trans), intent(in) idx_trns, integer(kind = kint), intent(in) n_WR, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_wr), intent(inout) WR, real (kind=kreal), dimension(n_ws), intent(inout) WS, type(leg_trns_sym_mul_work), intent(inout) WK_l_sml)
Definition at line 212 of file legendre_bwd_sym_matmul.f90.
References set_vr_rtm_leg_sym_matmul::cal_vr_rtm_scalar_sym_matmul(), elaps, matmul_for_legendre_trans::matmul_bwd_leg_trans(), and set_sp_rlm_leg_sym_matmul::set_sp_rlm_scalar_sym_matmul().
Referenced by legendre_trans_sym_matmul::leg_backward_trans_sym_matmul().
leg_b_trans_vec_sym_matmul()
subroutine legendre_bwd_sym_matmul::leg_b_trans_vec_sym_matmul (integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_comm_tbl), intent(in) comm_rlm, type(sph_comm_tbl), intent(in) comm_rtm, type(index_4_sph_trans), intent(in) idx_trns, real(kind = kreal), dimension(sph_rtm%nidx_rtm(2)), intent(in) asin_theta_1d_rtm, real(kind = kreal), dimension(sph_rlm%nidx_rlm(2),17), intent(in) g_sph_rlm, integer(kind = kint), intent(in) n_WR, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_wr), intent(inout) WR, real (kind=kreal), dimension(n_ws), intent(inout) WS, type(leg_trns_sym_mul_work), intent(inout) WK_l_sml)
Definition at line 75 of file legendre_bwd_sym_matmul.f90.
References set_vr_rtm_leg_sym_matmul::cal_vr_rtm_vector_sym_matmul(), elaps, matmul_for_legendre_trans::matmul_bwd_leg_trans(), and set_sp_rlm_leg_sym_matmul::set_sp_rlm_vector_sym_matmul().
Referenced by legendre_trans_sym_matmul::leg_backward_trans_sym_matmul().
Variable Documentation
elaps
real(kind = kreal), dimension(4), private legendre_bwd_sym_matmul::elaps private
Definition at line 66 of file legendre_bwd_sym_matmul.f90.
Referenced by leg_b_trans_scl_sym_matmul(), and leg_b_trans_vec_sym_matmul().
omp_get_max_threads
integer, external legendre_bwd_sym_matmul::omp_get_max_threads
Definition at line 67 of file legendre_bwd_sym_matmul.f90.
st_elapsed
real(kind = kreal), private legendre_bwd_sym_matmul::st_elapsed private
Definition at line 65 of file legendre_bwd_sym_matmul.f90.