CALYPSO: gauss_integration Module Reference
gauss_integration Module Reference
Functions/Subroutines
subroutine const_gauss_points_coefs (n_point, w_point, w_coefs)
subroutine set_gauss_points_sph (n_point, w_point, w_colat, w_col_deg, w_azim, w_azim_deg)
subroutine set_gauss_points_integration (xst, xed, n_point, w_point, x_point, coef_gauss)
subroutine set_gauss_colat_integration (n_point, w_colat, x_point, coef_gauss)
subroutine cal_gauss_integration (num_inte, n_point, w_coefs, f_point, coef_gauss, x)
Function/Subroutine Documentation
cal_gauss_integration()
subroutine gauss_integration::cal_gauss_integration (integer(kind = kint), intent(in) num_inte, integer(kind = kint), intent(in) n_point, real(kind = kreal), dimension(n_point), intent(in) w_coefs, real(kind = kreal), dimension(num_inte, n_point), intent(in) f_point, real(kind = kreal), intent(in) coef_gauss, real(kind = kreal), dimension(num_inte), intent(inout) x)
Definition at line 216 of file gauss_integration.f90.
Referenced by t_gauss_points::cal_gauss_integrals().
const_gauss_points_coefs()
subroutine gauss_integration::const_gauss_points_coefs (integer(kind = kint), intent(in) n_point, real(kind = kreal), dimension(n_point), intent(inout) w_point, real(kind = kreal), dimension(n_point), intent(inout) w_coefs)
Definition at line 60 of file gauss_integration.f90.
References m_constants::four, m_constants::half, m_constants::ione, m_constants::itwo, m_constants::one, m_constants::quad, m_constants::two, and m_constants::zero.
Referenced by t_gauss_points::construct_gauss_coefs().
set_gauss_colat_integration()
subroutine gauss_integration::set_gauss_colat_integration (integer(kind = kint), intent(in) n_point, real(kind = kreal), dimension(n_point), intent(in) w_colat, real(kind = kreal), dimension(n_point), intent(inout) x_point, real(kind = kreal), intent(inout) coef_gauss)
Definition at line 192 of file gauss_integration.f90.
References m_constants::four, m_constants::half, and m_constants::one.
Referenced by t_gauss_points::set_points_4_elevation().
set_gauss_points_integration()
subroutine gauss_integration::set_gauss_points_integration (real(kind = kreal), intent(in) xst, real(kind = kreal), intent(in) xed, integer(kind = kint), intent(in) n_point, real(kind = kreal), dimension(n_point), intent(in) w_point, real(kind = kreal), dimension(n_point), intent(inout) x_point, real(kind = kreal), intent(inout) coef_gauss)
Definition at line 169 of file gauss_integration.f90.
References m_constants::half.
Referenced by t_gauss_points::set_points_4_integration().
set_gauss_points_sph()
subroutine gauss_integration::set_gauss_points_sph (integer(kind = kint), intent(in) n_point, real(kind = kreal), dimension(n_point), intent(in) w_point, real(kind = kreal), dimension(n_point), intent(inout) w_colat, real(kind = kreal), dimension(n_point), intent(inout) w_col_deg, real(kind = kreal), dimension(2*n_point), intent(inout) w_azim, real(kind = kreal), dimension(2*n_point), intent(inout) w_azim_deg)
Definition at line 137 of file gauss_integration.f90.
References m_constants::four, and m_constants::one.
Referenced by t_gauss_points::set_gauss_colatitude().