CALYPSO: field_io_select Module Reference
field_io_select Module Reference
read and write restart file
Functions/Subroutines
logical function check_step_fem_field_file (id_rank, istep_fld, file_IO)
subroutine sel_write_step_fem_field_file (istep_fld, file_IO, t_IO, fld_IO)
subroutine sel_write_step_sph_field_file (istep_fld, file_IO, t_IO, fld_IO)
subroutine sel_read_step_fem_field_file (num_pe, id_rank, istep_fld, file_IO, t_IO, fld_IO)
subroutine sel_read_step_sph_field_file (num_pe, id_rank, istep_fld, file_IO, t_IO, fld_IO)
subroutine sel_read_alloc_step_fem_file (num_pe, id_rank, istep_fld, file_IO, t_IO, fld_IO)
subroutine sel_read_alloc_step_sph_file (num_pe, id_rank, istep_fld, file_IO, t_IO, fld_IO)
subroutine sel_read_alloc_fem_fld_head (num_pe, id_rank, istep_fld, file_IO, t_IO, fld_IO)
subroutine sel_read_alloc_sph_fld_head (num_pe, id_rank, istep_fld, file_IO, t_IO, fld_IO)
subroutine, private sel_write_step_field_file (file_name, file_IO, t_IO, fld_IO)
subroutine, private sel_read_step_field_file (file_name, num_pe, id_rank, file_IO, t_IO, fld_IO)
subroutine, private sel_read_alloc_step_field_file (file_name, num_pe, id_rank, file_IO, t_IO, fld_IO)
subroutine, private sel_read_alloc_field_head (file_name, num_pe, id_rank, file_IO, t_IO, fld_IO)
Detailed Description
read and write restart file
      logical function check_step_FEM_field_file                      &
     &                (id_rank, istep_fld, file_IO)
      subroutine sel_write_step_FEM_field_file                        &
     &         (istep_fld, file_IO, t_IO, fld_IO)
      subroutine sel_write_step_SPH_field_file                        &
     &         (istep_fld, file_IO, t_IO, fld_IO)
      subroutine sel_read_step_FEM_field_file                         &
     &         (num_pe, id_rank, istep_fld, file_IO, t_IO, fld_IO)
      subroutine sel_read_step_SPH_field_file                         &
     &         (num_pe, id_rank, istep_fld, file_IO, t_IO, fld_IO)
      subroutine sel_read_alloc_step_FEM_file                         &
     &         (num_pe, id_rank, istep_fld, file_IO, t_IO, fld_IO)
      subroutine sel_read_alloc_step_SPH_file                         &
     &         (num_pe, id_rank, istep_fld, file_IO, t_IO, fld_IO)
      subroutine sel_read_alloc_FEM_fld_head                          &
     &         (num_pe, id_rank, istep_fld, file_IO, t_IO, fld_IO)
      subroutine sel_read_alloc_SPH_fld_head                          &
     &         (num_pe, id_rank, istep_fld, file_IO, t_IO, fld_IO)
        type(field_IO_params), intent(in) :: file_IO
        type(time_data), intent(inout) :: t_IO
        type(field_IO), intent(inout) :: fld_IO
Function/Subroutine Documentation
check_step_fem_field_file()
logical function field_io_select::check_step_fem_field_file (integer, intent(in) id_rank, integer(kind = kint), intent(in) istep_fld, type(field_io_params), intent(in) file_IO)
Definition at line 73 of file field_IO_select.F90.
References delete_data_files::check_file_exist(), and set_field_file_names::set_fem_fld_file_name().
sel_read_alloc_fem_fld_head()
subroutine field_io_select::sel_read_alloc_fem_fld_head (integer, intent(in) num_pe, integer, intent(in) id_rank, integer(kind=kint), intent(in) istep_fld, type(field_io_params), intent(in) file_IO, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO)
Definition at line 236 of file field_IO_select.F90.
References sel_read_alloc_field_head(), and set_field_file_names::set_fem_fld_file_name().
sel_read_alloc_field_head()
subroutine, private field_io_select::sel_read_alloc_field_head (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, type(field_io_params), intent(in) file_IO, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO) private
Definition at line 448 of file field_IO_select.F90.
References calypso_mpi::calypso_mpi_abort(), gz_field_file_io_b::gz_rd_alloc_st_fld_head_b(), gz_field_file_mpi_io_b::gz_rd_alloc_st_fld_head_mpi_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, m_file_format_switch::iflag_single, gz_field_file_io::read_alloc_gz_step_field_head(), field_file_mpi_io::read_alloc_step_fld_head_mpi(), gz_field_file_mpi_io::read_alloc_stp_fld_head_gz_mpi(), field_file_mpi_io_b::read_alloc_stp_fld_head_mpi_b(), field_file_io::read_and_allocate_step_head(), and field_file_io_b::read_and_allocate_step_head_b().
Referenced by sel_read_alloc_fem_fld_head(), and sel_read_alloc_sph_fld_head().
sel_read_alloc_sph_fld_head()
subroutine field_io_select::sel_read_alloc_sph_fld_head (integer, intent(in) num_pe, integer, intent(in) id_rank, integer(kind = kint), intent(in) istep_fld, type(field_io_params), intent(in) file_IO, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO)
Definition at line 260 of file field_IO_select.F90.
References sel_read_alloc_field_head(), and set_field_file_names::set_sph_fld_file_name().
Referenced by new_sph_restart::load_field_name_assemble_sph().
sel_read_alloc_step_fem_file()
subroutine field_io_select::sel_read_alloc_step_fem_file (integer, intent(in) num_pe, integer, intent(in) id_rank, integer(kind = kint), intent(in) istep_fld, type(field_io_params), intent(in) file_IO, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO)
Definition at line 188 of file field_IO_select.F90.
References sel_read_alloc_step_field_file(), and set_field_file_names::set_fem_fld_file_name().
sel_read_alloc_step_field_file()
subroutine, private field_io_select::sel_read_alloc_step_field_file (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, type(field_io_params), intent(in) file_IO, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO) private
Definition at line 391 of file field_IO_select.F90.
References calypso_mpi::calypso_mpi_abort(), gz_field_file_io_b::gz_rd_alloc_st_fld_file_b(), gz_field_file_mpi_io_b::gz_rd_alloc_st_fld_file_mpi_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, m_file_format_switch::iflag_single, gz_field_file_io::read_alloc_gz_step_field_file(), field_file_mpi_io::read_alloc_step_fld_file_mpi(), gz_field_file_mpi_io::read_alloc_stp_fld_file_gz_mpi(), field_file_mpi_io_b::read_alloc_stp_fld_file_mpi_b(), field_file_io::read_and_alloc_step_field(), and field_file_io_b::read_and_allocate_step_field_b().
Referenced by sel_read_alloc_step_fem_file(), and sel_read_alloc_step_sph_file().
sel_read_alloc_step_sph_file()
subroutine field_io_select::sel_read_alloc_step_sph_file (integer, intent(in) num_pe, integer, intent(in) id_rank, integer(kind = kint), intent(in) istep_fld, type(field_io_params), intent(in) file_IO, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO)
Definition at line 212 of file field_IO_select.F90.
References sel_read_alloc_step_field_file(), and set_field_file_names::set_sph_fld_file_name().
Referenced by analyzer_compare_sph_rst::analyze_compare_sph_restart(), new_sph_restart::load_org_sph_data(), sph_mhd_rst_io_control::read_alloc_sph_restart_data(), sph_mhd_rst_io_control::read_alloc_sph_rst_4_snap(), and sph_mhd_rst_io_control::read_alloc_sph_spectr().
sel_read_step_fem_field_file()
subroutine field_io_select::sel_read_step_fem_field_file (integer, intent(in) num_pe, integer, intent(in) id_rank, integer(kind = kint), intent(in) istep_fld, type(field_io_params), intent(in) file_IO, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO)
Definition at line 139 of file field_IO_select.F90.
References sel_read_step_field_file(), and set_field_file_names::set_fem_fld_file_name().
sel_read_step_field_file()
subroutine, private field_io_select::sel_read_step_field_file (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, type(field_io_params), intent(in) file_IO, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO) private
Definition at line 335 of file field_IO_select.F90.
References calypso_mpi::calypso_mpi_abort(), gz_field_file_io_b::gz_read_step_field_file_b(), gz_field_file_mpi_io_b::gz_read_step_field_file_mpi_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, m_file_format_switch::iflag_single, gz_field_file_io::read_gz_step_field_file(), field_file_io::read_step_field_file(), field_file_io_b::read_step_field_file_b(), gz_field_file_mpi_io::read_step_field_file_gz_mpi(), field_file_mpi_io::read_step_field_file_mpi(), and field_file_mpi_io_b::read_step_field_file_mpi_b().
Referenced by sel_read_step_fem_field_file(), and sel_read_step_sph_field_file().
sel_read_step_sph_field_file()
subroutine field_io_select::sel_read_step_sph_field_file (integer, intent(in) num_pe, integer, intent(in) id_rank, integer(kind = kint), intent(in) istep_fld, type(field_io_params), intent(in) file_IO, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO)
Definition at line 163 of file field_IO_select.F90.
References sel_read_step_field_file(), and set_field_file_names::set_sph_fld_file_name().
sel_write_step_fem_field_file()
subroutine field_io_select::sel_write_step_fem_field_file (integer(kind = kint), intent(in) istep_fld, type(field_io_params), intent(in) file_IO, type(time_data), intent(in) t_IO, type(field_io), intent(in) fld_IO)
Definition at line 96 of file field_IO_select.F90.
References calypso_mpi::my_rank, sel_write_step_field_file(), and set_field_file_names::set_fem_fld_file_name().
sel_write_step_field_file()
subroutine, private field_io_select::sel_write_step_field_file (character(len=kchara), intent(in) file_name, type(field_io_params), intent(in) file_IO, type(time_data), intent(in) t_IO, type(field_io), intent(in) fld_IO) private
Definition at line 285 of file field_IO_select.F90.
References calypso_mpi::calypso_mpi_abort(), gz_field_file_io_b::gz_write_step_fld_file_b(), gz_field_file_mpi_io_b::gz_write_step_fld_file_mpi_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, m_error_ids::ierr_fld, m_file_format_switch::iflag_single, calypso_mpi::my_rank, calypso_mpi::nprocs, gz_field_file_io::write_gz_step_field_file(), gz_field_file_mpi_io::write_gz_step_field_file_mpi(), field_file_io::write_step_field_file(), field_file_io_b::write_step_field_file_b(), field_file_mpi_io::write_step_field_file_mpi(), and field_file_mpi_io_b::write_step_field_file_mpi_b().
Referenced by sel_write_step_fem_field_file(), and sel_write_step_sph_field_file().
sel_write_step_sph_field_file()
subroutine field_io_select::sel_write_step_sph_field_file (integer(kind = kint), intent(in) istep_fld, type(field_io_params), intent(in) file_IO, type(time_data), intent(in) t_IO, type(field_io), intent(in) fld_IO)
Definition at line 117 of file field_IO_select.F90.
References calypso_mpi::my_rank, sel_write_step_field_file(), and set_field_file_names::set_sph_fld_file_name().
Referenced by analyzer_assemble_sph::analyze_assemble_sph(), analyzer_rayleigh_cvt_sph::analyze_cvt_rayleigh_sph(), sph_mhd_rst_io_control::output_spectr_4_snap(), and sph_mhd_rst_io_control::output_sph_restart_control().