CALYPSO: set_local_sphere_param Module Reference
set_local_sphere_param Module Reference
Copy number of global spherical harmonics indices to local data.
Functions/Subroutines
subroutine set_global_sph_rtp_id (s3d_ranks, stk_lc1d, sph_rtp)
subroutine set_global_sph_prt_id (s3d_ranks, stk_lc1d, sph_rtp)
subroutine set_global_sph_rj_id (s3d_ranks, stk_lc1d, sph_rj)
subroutine set_global_sph_4_rtm (s3d_ranks, stk_lc1d, sph_rtm)
subroutine set_global_sph_4_trm (s3d_ranks, stk_lc1d, sph_rtm)
subroutine set_global_sph_4_rlm (s3d_ranks, stk_lc1d, sph_rlm)
subroutine set_global_sph_4_lmr (s3d_ranks, stk_lc1d, sph_rlm)
Detailed Description
Copy number of global spherical harmonics indices to local data.
      subroutine set_global_sph_rtp_id(s3d_ranks, stk_lc1d, sph_rtp)
      subroutine set_global_sph_prt_id(s3d_ranks, stk_lc1d, sph_rtp)
        type(spheric_global_rank), intent(in) :: s3d_ranks
        type(sph_1d_index_stack), intent(in) :: stk_lc1d
        type(sph_rtp_grid), intent(inout) :: sph_rtp
      subroutine set_global_sph_rj_id(s3d_ranks, stk_lc1d, sph_rj)
        type(spheric_global_rank), intent(in) :: s3d_ranks
        type(sph_1d_index_stack), intent(in) :: stk_lc1d
        type(sph_rj_grid), intent(inout) ::  sph_rj
      subroutine set_global_sph_4_rtm(s3d_ranks, stk_lc1d, sph_rtm)
      subroutine set_global_sph_4_trm(s3d_ranks, stk_lc1d, sph_rtm)
        type(spheric_global_rank), intent(in) :: s3d_ranks
        type(sph_1d_index_stack), intent(in) :: stk_lc1d
        type(sph_rtm_grid), intent(inout) :: sph_rtm
      subroutine set_global_sph_4_rlm(s3d_ranks, stk_lc1d, sph_rlm)
      subroutine set_global_sph_4_lmr(s3d_ranks, stk_lc1d, sph_rlm)
        type(spheric_global_rank), intent(in) :: s3d_ranks
        type(sph_1d_index_stack), intent(in) :: stk_lc1d
        type(sph_rlm_grid), intent(inout) :: sph_rlm
Function/Subroutine Documentation
set_global_sph_4_lmr()
subroutine set_local_sphere_param::set_global_sph_4_lmr (type(spheric_global_rank), intent(in) s3d_ranks, type(sph_1d_index_stack), intent(in) stk_lc1d, type(sph_rlm_grid), intent(inout) sph_rlm)
Definition at line 262 of file set_local_sphere_param.f90.
Referenced by gen_sph_grids_modes::const_sph_rlm_modes().
set_global_sph_4_rlm()
subroutine set_local_sphere_param::set_global_sph_4_rlm (type(spheric_global_rank), intent(in) s3d_ranks, type(sph_1d_index_stack), intent(in) stk_lc1d, type(sph_rlm_grid), intent(inout) sph_rlm)
Definition at line 234 of file set_local_sphere_param.f90.
Referenced by gen_sph_grids_modes::const_sph_rlm_modes().
set_global_sph_4_rtm()
subroutine set_local_sphere_param::set_global_sph_4_rtm (type(spheric_global_rank), intent(in) s3d_ranks, type(sph_1d_index_stack), intent(in) stk_lc1d, type(sph_rtm_grid), intent(inout) sph_rtm)
Definition at line 157 of file set_local_sphere_param.f90.
Referenced by gen_sph_grids_modes::const_sph_rtm_grids().
set_global_sph_4_trm()
subroutine set_local_sphere_param::set_global_sph_4_trm (type(spheric_global_rank), intent(in) s3d_ranks, type(sph_1d_index_stack), intent(in) stk_lc1d, type(sph_rtm_grid), intent(inout) sph_rtm)
Definition at line 195 of file set_local_sphere_param.f90.
Referenced by gen_sph_grids_modes::const_sph_rtm_grids().
set_global_sph_prt_id()
subroutine set_local_sphere_param::set_global_sph_prt_id (type(spheric_global_rank), intent(in) s3d_ranks, type(sph_1d_index_stack), intent(in) stk_lc1d, type(sph_rtp_grid), intent(inout) sph_rtp)
Definition at line 86 of file set_local_sphere_param.f90.
Referenced by set_comm_table_rtp_rj::const_sph_rtp_grids().
set_global_sph_rj_id()
subroutine set_local_sphere_param::set_global_sph_rj_id (type(spheric_global_rank), intent(in) s3d_ranks, type(sph_1d_index_stack), intent(in) stk_lc1d, type(sph_rj_grid), intent(inout) sph_rj)
Definition at line 125 of file set_local_sphere_param.f90.
Referenced by set_comm_table_rtp_rj::const_sph_rj_modes().
set_global_sph_rtp_id()
subroutine set_local_sphere_param::set_global_sph_rtp_id (type(spheric_global_rank), intent(in) s3d_ranks, type(sph_1d_index_stack), intent(in) stk_lc1d, type(sph_rtp_grid), intent(inout) sph_rtp)
Definition at line 48 of file set_local_sphere_param.f90.
Referenced by set_comm_table_rtp_rj::const_sph_rtp_grids().