CALYPSO: set_psf_iso_control Module Reference
set_psf_iso_control Module Reference
Structure for parallel sectioned data.
Functions/Subroutines
subroutine dealloc_psf_field_name (num_psf, psf_mesh)
subroutine set_psf_control (num_psf, group, nod_fld, psf_ctls, psf_param, psf_def, psf_mesh, psf_file_IO)
subroutine set_iso_control (num_iso, group, nod_fld, iso_ctls, iso_param, iso_def, iso_mesh, iso_file_IO)
Detailed Description
Structure for parallel sectioned data.
      subroutine dealloc_psf_field_name(num_psf, psf_mesh)
        type(psf_local_data), intent(inout) :: psf_mesh(num_psf)
      subroutine set_psf_control(num_psf, group, nod_fld,             &
     &          psf_ctls, psf_param, psf_def, psf_mesh, psf_file_IO)
        type(mesh_groups), intent(in) :: group
        type(phys_data), intent(in) :: nod_fld
        type(section_controls), intent(inout) :: psf_ctls
        type(psf_parameters), intent(inout) :: psf_param(num_psf)
        type(section_define), intent(inout) :: psf_def(num_psf)
        type(psf_local_data), intent(inout) :: psf_mesh(num_psf)
      subroutine set_iso_control(num_iso, group, nod_fld,             &
     &          iso_ctls, iso_param, iso_def, iso_mesh, iso_file_IO)
        type(mesh_groups), intent(in) :: group
        type(phys_data), intent(in) :: nod_fld
        type(isosurf_controls), intent(inout) :: iso_ctls
        type(psf_parameters), intent(inout) :: iso_param(num_iso)
        type(isosurface_define), intent(inout) :: iso_def(num_iso)
        type(psf_local_data), intent(inout) :: iso_mesh(num_iso)
        type(field_IO_params), intent(inout) :: iso_file_IO(num_iso)
Function/Subroutine Documentation
dealloc_psf_field_name()
subroutine set_psf_iso_control::dealloc_psf_field_name (integer(kind = kint), intent(in) num_psf, type(psf_local_data), dimension(num_psf), intent(inout) psf_mesh)
Definition at line 45 of file set_psf_iso_control.f90.
Referenced by t_isosurface::dealloc_iso_field_type(), and t_cross_section::dealloc_psf_field_type().
set_iso_control()
subroutine set_psf_iso_control::set_iso_control (integer(kind= kint), intent(in) num_iso, type(mesh_groups), intent(in) group, type(phys_data), intent(in) nod_fld, type(isosurf_controls), intent(inout) iso_ctls, type(psf_parameters), dimension(num_iso), intent(inout) iso_param, type(isosurface_define), dimension(num_iso), intent(inout) iso_def, type(psf_local_data), dimension(num_iso), intent(inout) iso_mesh, type(field_io_params), dimension(num_iso), intent(inout) iso_file_IO)
Definition at line 116 of file set_psf_iso_control.f90.
References t_phys_data::alloc_phys_name_type(), t_control_params_4_iso::count_control_4_iso(), set_field_comp_for_viz::count_total_comps_4_viz(), t_control_data_4_iso::dealloc_cont_dat_4_iso(), t_control_data_isosurfaces::dealloc_iso_ctl_stract(), m_machine_parameter::iflag_debug, and t_control_params_4_iso::set_control_4_iso().
Referenced by t_isosurface::isosurf_initialize().
set_psf_control()
subroutine set_psf_iso_control::set_psf_control (integer(kind= kint), intent(in) num_psf, type(mesh_groups), intent(in) group, type(phys_data), intent(in) nod_fld, type(section_controls), intent(inout) psf_ctls, type(psf_parameters), dimension(num_psf), intent(inout) psf_param, type(section_define), dimension(num_psf), intent(inout) psf_def, type(psf_local_data), dimension(num_psf), intent(inout) psf_mesh, type(field_io_params), dimension(num_psf), intent(inout) psf_file_IO)
Definition at line 62 of file set_psf_iso_control.f90.
References t_phys_data::alloc_phys_name_type(), calypso_mpi::calypso_mpi_abort(), t_control_params_4_psf::count_control_4_psf(), set_field_comp_for_viz::count_total_comps_4_viz(), t_control_data_4_psf::dealloc_cont_dat_4_psf(), t_control_data_sections::dealloc_psf_ctl_stract(), m_machine_parameter::e_message, and t_control_params_4_psf::set_control_4_psf().
Referenced by t_cross_section::sectioning_initialize().