CALYPSO: t_parai_gen_sph_grids_modes Module Reference
t_parai_gen_sph_grids_modes Module Reference
Main loop to generate spherical harmonics indices.
Functions/Subroutines
subroutine para_gen_sph_rlm_rj_modes (num_pe, gen_sph, sph_mesh)
subroutine para_gen_sph_rtm_rtp_grids (num_pe, gen_sph, sph_mesh)
Detailed Description
Main loop to generate spherical harmonics indices.
      subroutine para_gen_sph_rlm_rj_modes(gen_sph, para_sph)
        type(construct_spherical_grid), intent(inout) :: gen_sph
        type(parallel_sph_params), intent(inout) :: para_sph
      subroutine para_gen_sph_rtm_rtp_grids(gen_sph, para_sph)
        type(construct_spherical_grid), intent(inout) :: gen_sph
        type(parallel_sph_params), intent(inout) :: para_sph
Function/Subroutine Documentation
para_gen_sph_rlm_rj_modes()
subroutine t_parai_gen_sph_grids_modes::para_gen_sph_rlm_rj_modes (integer(kind = kint), intent(in) num_pe, type(construct_spherical_grid), intent(inout) gen_sph, type(sph_mesh_data), dimension(num_pe), intent(inout) sph_mesh)
Structure for parallel spherical mesh table
Definition at line 39 of file t_parai_gen_sph_grids_modes.f90.
References set_comm_table_rtp_rj::const_sph_rj_modes(), gen_sph_grids_modes::const_sph_rlm_modes(), bcast_comm_stacks_sph::dealloc_comm_stacks_sph(), m_work_time::end_elapsed_time(), m_machine_parameter::iflag_debug, m_elapsed_labels_gen_sph::iflag_gsp_time, m_elapsed_labels_gen_sph::ist_elapsed_gsp, calypso_mpi::my_rank, calypso_mpi::nprocs, bcast_comm_stacks_sph::para_bcast_comm_stacks_sph(), and m_work_time::start_elapsed_time().
Referenced by parallel_gen_sph_grids::para_gen_sph_grids(), and parallel_gen_sph_grids::para_gen_sph_rj_mode().
para_gen_sph_rtm_rtp_grids()
subroutine t_parai_gen_sph_grids_modes::para_gen_sph_rtm_rtp_grids (integer(kind = kint), intent(in) num_pe, type(construct_spherical_grid), intent(inout) gen_sph, type(sph_mesh_data), dimension(num_pe), intent(inout) sph_mesh)
Structure for parallel spherical mesh table
Definition at line 98 of file t_parai_gen_sph_grids_modes.f90.
References gen_sph_grids_modes::const_sph_rtm_grids(), set_comm_table_rtp_rj::const_sph_rtp_grids(), bcast_comm_stacks_sph::dealloc_comm_stacks_sph(), m_work_time::end_elapsed_time(), m_machine_parameter::iflag_debug, m_elapsed_labels_gen_sph::iflag_gsp_time, m_elapsed_labels_gen_sph::ist_elapsed_gsp, calypso_mpi::my_rank, calypso_mpi::nprocs, bcast_comm_stacks_sph::para_bcast_comm_stacks_sph(), and m_work_time::start_elapsed_time().
Referenced by parallel_gen_sph_grids::para_gen_sph_grids().