CALYPSO: const_sph_radial_grid Module Reference
const_sph_radial_grid Module Reference
Functions/Subroutines
subroutine count_set_radial_grid (nele, rmin, rmax, increment_cheby, sph_param, sph_rtp, s3d_radius)
subroutine output_set_radial_grid (sph_param, sph_rtp, s3d_radius)
Function/Subroutine Documentation
count_set_radial_grid()
subroutine const_sph_radial_grid::count_set_radial_grid (integer(kind = kint), intent(in) nele, real(kind = kreal), intent(in) rmin, real(kind = kreal), intent(in) rmax, integer(kind = kint), intent(in) increment_cheby, type(sph_shell_parameters), intent(inout) sph_param, type(sph_rtp_grid), intent(inout) sph_rtp, type(spheric_global_radius), intent(inout) s3d_radius)
Definition at line 35 of file const_sph_radial_grid.f90.
References chebyshev_radial_grid::adjust_chebyshev_shell(), t_spheric_global_ranks::alloc_radius_1d_gl(), chebyshev_radial_grid::count_chebyshev_ext_layers(), set_radial_grid_sph_shell::count_equi_ext_layers(), half_chebyshev_radial_grid::count_half_chebyshev_external(), half_chebyshev_radial_grid::half_chebyshev_distance_shell(), m_spheric_constants::igrid_chebyshev, m_spheric_constants::igrid_equidistance, m_spheric_constants::igrid_half_chebyshev, chebyshev_radial_grid::set_chebyshev_distance_shell(), and set_radial_grid_sph_shell::set_equi_distance_shell().
Referenced by t_ctl_params_gen_sph_shell::set_ctl_radius_4_shell().
output_set_radial_grid()
subroutine const_sph_radial_grid::output_set_radial_grid (type(sph_shell_parameters), intent(in) sph_param, type(sph_rtp_grid), intent(in) sph_rtp, type(spheric_global_radius), intent(in) s3d_radius)
Definition at line 100 of file const_sph_radial_grid.f90.
References m_constants::ione.
Referenced by mpi_gen_sph_grids_modes::const_sph_global_parameters().