CALYPSO: fftpack5_wrapper Module Reference
fftpack5_wrapper Module Reference
FFTPACK5 wrapper.
Functions/Subroutines
subroutine init_calypso_fftpack (Nfft, lSAVE, WSAVE)
subroutine calypso_rfftmf_smp (Nsmp, Nstacksmp, M, Nfft, X, X_FFTPACK5, Mmax_smp, lSAVE, WSAVE, WORK)
subroutine calypso_rfftmb_smp (Nsmp, Nstacksmp, M, Nfft, X, X_FFTPACK5, Mmax_smp, lSAVE, WSAVE, WORK)
Detailed Description
FFTPACK5 wrapper.
  ---------------------------------------------------------------------
      subroutine init_CALYPSO_FFTPACK(Nfft, lSAVE, WSAVE)
 ------------------------------------------------------------------
   wrapper subroutine for initierize FFT
 ------------------------------------------------------------------
      subroutine CALYPSO_RFFTMF_SMP(Nsmp, Nstacksmp, M, Nfft,         &
     &          X, X_FFTPACK5, Mmax_smp, lSAVE, WSAVE, WORK)
 ------------------------------------------------------------------
 wrapper subroutine for forward Fourier transform by FFTPACK5
   a_{k} = \frac{2}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
          *  \cos (\frac{2\pi j k}{Nfft})
   b_{k} = \frac{2}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
          *  \cos (\frac{2\pi j k}{Nfft})
   a_{0} = \frac{1}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
    K = Nfft/2....
   a_{k} = \frac{1}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
          * \cos (\frac{2\pi j k}{Nfft})
 ------------------------------------------------------------------
      subroutine CALYPSO_RFFTMB_SMP(Nsmp, Nstacksmp, M, Nfft,         &
     &          X, X_FFTPACK5, Mmax_smp, lSAVE, WSAVE, WORK)
 ------------------------------------------------------------------
 wrapper subroutine for backward Fourier transform by FFTPACK5
   x_{k} = a_{0} + (-1)^{j} a_{Nfft/2} + sum_{k=1}^{Nfft/2-1}
          (a_{k} \cos(2\pijk/Nfft) + b_{k} \sin(2\pijk/Nfft))
 ------------------------------------------------------------------
       i = 1:     a_{0}
       i = 2:     a_{Nfft/2}
       i = 3:     a_{1}
       i = 4:     b_{1}
       ...
       i = 2*k+1: a_{k}
       i = 2*k+2: b_{k}
       ...
       i = Nfft-1:   a_{Nfft/2-1}
       i = Nfft:     b_{Nfft/2-1}
 ------------------------------------------------------------------
Parameters
Nsmp Number of SMP processors
Nstacksmp(0:Nsmp) End number for each SMP process
M Number of components for Fourier transforms
Nfft Data length for eadh FFT
X(M,Nfft) Data for Fourier transform
Parameters
Mmax_smp Maximum number of component for each SMP process
X_FFTPACK5(Mmax_smp*Nfft,Nsmp) Data for multiple Fourier transform
lSAVE Size of work constant for FFTPACK
WSAVE(lSAVE) Work constatnts for FFTPACK
WORK(Mmax_smp*Nfft,Nsmp) Work area for FFTPACK
Function/Subroutine Documentation
calypso_rfftmb_smp()
subroutine fftpack5_wrapper::calypso_rfftmb_smp (integer(kind = kint), intent(in) Nsmp, integer(kind = kint), dimension(0:nsmp), intent(in) Nstacksmp, integer(kind = kint), intent(in) M, integer(kind = kint), intent(in) Nfft, real(kind = kreal), dimension(m,nfft), intent(inout) X, real(kind = 8), dimension(mmax_smp*nfft,nsmp), intent(inout) X_FFTPACK5, integer(kind = kint), intent(in) Mmax_smp, integer(kind = kint), intent(in) lSAVE, real(kind = 8), dimension(lsave), intent(in) WSAVE, real(kind = 8), dimension(mmax_smp*nfft,nsmp), intent(inout) WORK)
Definition at line 158 of file FFTPACK5_wrapper.f90.
References m_constants::ione, and rfftmb().
Referenced by t_fftpack5_wrapper::calypso_rfftmb_t().
calypso_rfftmf_smp()
subroutine fftpack5_wrapper::calypso_rfftmf_smp (integer(kind = kint), intent(in) Nsmp, integer(kind = kint), dimension(0:nsmp), intent(in) Nstacksmp, integer(kind = kint), intent(in) M, integer(kind = kint), intent(in) Nfft, real(kind = kreal), dimension(m, nfft), intent(inout) X, real(kind = 8), dimension(mmax_smp*nfft,nsmp), intent(inout) X_FFTPACK5, integer(kind = kint), intent(in) Mmax_smp, integer(kind = kint), intent(in) lSAVE, real(kind = 8), dimension(lsave), intent(in) WSAVE, real(kind = 8), dimension(mmax_smp*nfft,nsmp), intent(inout) WORK)
Definition at line 101 of file FFTPACK5_wrapper.f90.
References m_constants::ione, and rfftmf().
Referenced by t_fftpack5_wrapper::calypso_rfftmf_t().
init_calypso_fftpack()
subroutine fftpack5_wrapper::init_calypso_fftpack (integer(kind = kint), intent(in) Nfft, integer(kind = kint), intent(in) lSAVE, real(kind = 8), dimension(lsave), intent(in) WSAVE)
Definition at line 86 of file FFTPACK5_wrapper.f90.
References rfftmi().
Referenced by t_fftpack5_wrapper::init_wk_fftpack_t(), and t_fftpack5_wrapper::verify_wk_fftpack_t().