CALYPSO: t_const_spherical_grid Module Reference
t_const_spherical_grid Module Reference
Structure to constract spherical shell mesh.
Data Types
type construct_spherical_grid
Structure of spherical shell parameters.
Functions/Subroutines
subroutine dealloc_gen_mesh_params (gen_sph)
subroutine dealloc_gen_sph_radial_groups (gen_sph)
subroutine copy_sph_radial_groups (sph_grps, gen_sph)
subroutine empty_theta_rtp_grp (theta_rtp_grp_lc)
Detailed Description
Structure to constract spherical shell mesh.
      subroutine dealloc_gen_mesh_params(gen_sph)
      subroutine dealloc_gen_sph_radial_groups(gen_sph)
        type(construct_spherical_grid), intent(inout) :: gen_sph
      subroutine copy_sph_radial_groups(gen_sph)
        type(sph_group_data), intent(in) ::  sph_grps
        type(construct_spherical_grid), intent(inout) :: gen_sph
      subroutine empty_theta_rtp_grp(theta_rtp_grp_lc)
        type(group_data), intent(inout) :: theta_rtp_grp_lc
Function/Subroutine Documentation
copy_sph_radial_groups()
subroutine t_const_spherical_grid::copy_sph_radial_groups (type(sph_group_data), intent(in) sph_grps, type(construct_spherical_grid), intent(inout) gen_sph)
Definition at line 109 of file t_const_spherical_grid.f90.
References copy_mesh_structures::copy_group_data().
Referenced by t_check_and_make_sph_mesh::const_fem_mesh_4_sph(), and t_check_and_make_sph_mesh::load_para_sph_and_fem_mesh().
dealloc_gen_mesh_params()
subroutine t_const_spherical_grid::dealloc_gen_mesh_params (type(construct_spherical_grid), intent(inout) gen_sph)
Definition at line 72 of file t_const_spherical_grid.f90.
References t_control_1d_layering::dealloc_layering_group(), t_spheric_global_ranks::dealloc_radius_1d_gl(), t_spheric_global_ranks::dealloc_sph_1d_domain_id(), t_sph_1d_global_index::dealloc_sph_1d_global_idx(), t_sph_1d_global_index::dealloc_sph_1d_global_stack(), t_sph_local_parameter::dealloc_sph_gl_parameter(), and t_spheric_global_ranks::dealloc_sph_ranks().
Referenced by mpi_gen_sph_grids_modes::mpi_gen_sph_grids(), mpi_gen_sph_grids_modes::mpi_gen_sph_rj_mode(), parallel_gen_sph_grids::para_gen_sph_grids(), and parallel_gen_sph_grids::para_gen_sph_rj_mode().
dealloc_gen_sph_radial_groups()
subroutine t_const_spherical_grid::dealloc_gen_sph_radial_groups (type(construct_spherical_grid), intent(inout) gen_sph)
Definition at line 95 of file t_const_spherical_grid.f90.
References t_group_data::dealloc_group().
Referenced by t_check_and_make_sph_mesh::const_fem_mesh_4_sph(), and t_check_and_make_sph_mesh::load_para_sph_and_fem_mesh().
empty_theta_rtp_grp()
subroutine t_const_spherical_grid::empty_theta_rtp_grp (type(group_data), intent(inout) theta_rtp_grp_lc)
Definition at line 129 of file t_const_spherical_grid.f90.
References t_group_data::alloc_group_item(), and t_group_data::alloc_group_num().