CALYPSO: m_grad_field_labels Module Reference
m_grad_field_labels Module Reference
Functions/Subroutines
logical function check_divergence_field (field_name)
logical function check_gradient_field (field_name)
integer(kind=kint) function num_divergence_fields ()
integer(kind=kint) function num_gradient_fields ()
subroutine set_divergence_field_labels (n_comps, names, maths)
subroutine set_gradient_field_labels (n_comps, names, maths)
Variables
integer(kind=kint), parameter, private ndiv_vector = 3
integer(kind=kint), parameter, private ngrad_scalar = 12
type(field_def), parameter div_velocity = field_def(n_comp = n_scalar, name = 'div_velocity', math = '$ \partial_{i} u_{i} $')
Divergence of velocity \(\partial_{i} u_{i} \).
type(field_def), parameter div_magnetic = field_def(n_comp = n_scalar, name = 'div_magnetic', math = '$ \partial_{i} B_{i} $')
Divergence of magnetic field \(\partial_{igrad} B_{i} \).
type(field_def), parameter div_vector_potential = field_def(n_comp = n_scalar, name = 'div_vector_potential', math = '$ \partial_{i} A_{i} $')
Divergence of magnetic vector potential \(\partial_{i} A_{i} \).
type(field_def), parameter grad_temp = field_def(n_comp = n_vector, name = 'grad_temp', math = '$ \partial_{i} T $')
Field label for gradient of \(T \) \(\partial_{i} T / dz\).
type(field_def), parameter grad_pert_temp = field_def(n_comp = n_vector, name = 'grad_pert_temp', math = '$ \partial_{i} \Theta $')
Field label for gradient of \(\Theta \) \(\partial_{i} \Theta / dz\).
type(field_def), parameter grad_reference_temp = field_def(n_comp = n_vector, name = 'grad_reference_temp', math = '$ \partial_{i} T_{0} $')
Field label for gradient of reference temperature \(\partial_{i} T_{0} / dz\).
type(field_def), parameter grad_composition = field_def(n_comp = n_vector, name = 'grad_composition', math = '$ \partial_{i} C $')
Field label for gradient of \(C \) \(\partial_{i} C / dz\).
type(field_def), parameter grad_pert_composition = field_def(n_comp = n_vector, name = 'grad_pert_composition', math = '$ \partial_{i} \Theta_{C} $')
Field label for gradient of perturbation of composition \(\partial_{i} \Theta_{C} / dz\).
type(field_def), parameter grad_reference_composition = field_def(n_comp = n_vector, name = 'grad_reference_composition', math = '$ \partial_{i} C_{0} $')
Field label for gradient of reference composition \(\partial_{i} C_{0} / dz\).
type(field_def), parameter grad_density = field_def(n_comp = n_vector, name = 'grad_density', math = '$ \partial_{i} \rho $')
Field label for gradient of density \(\partial_{i} \rho / dz\).
type(field_def), parameter grad_pert_density = field_def(n_comp = n_vector, name = 'grad_pert_density', math = '$ \partial_{i} \Theta_{\rho} $')
Field label for gradient of perturbation of density \(\partial_{i} \Theta_{\rho} / dz\).
type(field_def), parameter grad_reference_density = field_def(n_comp = n_vector, name = 'grad_reference_density', math = '$ \partial_{i} \rho_{0} $')
Field label for gradient of reference density \(\partial_{i} \rho_{0} / dz\).
type(field_def), parameter grad_entropy = field_def(n_comp = n_vector, name = 'grad_entropy', math = '$ \partial_{i} S $')
Field label for gradient of entropy \(\partial_{i} S / dz\).
type(field_def), parameter grad_pert_entropy = field_def(n_comp = n_vector, name = 'grad_pert_entropy', math = '$ \partial_{i} \Theta_{S} $')
Field label for gradient of perturbation of entropy \(\partial_{i} \Theta_{S} / dz\).
type(field_def), parameter grad_reference_entropy = field_def(n_comp = n_vector, name = 'grad_reference_entropy', math = '$ \partial_{i} S_{0} $')
Field label for gradient of reference density \(\partial_{i} S_{0} / dz\).
Function/Subroutine Documentation
check_divergence_field()
logical function m_grad_field_labels::check_divergence_field (character(len = kchara), intent(in) field_name)
Definition at line 165 of file m_grad_field_labels.f90.
References div_magnetic, div_vector_potential, and div_velocity.
Referenced by set_mhd_field_address::check_scalar_fields(), and t_grad_field_labels::set_gradient_field_addresses().
check_gradient_field()
logical function m_grad_field_labels::check_gradient_field (character(len = kchara), intent(in) field_name)
Definition at line 179 of file m_grad_field_labels.f90.
References grad_composition, grad_density, grad_entropy, grad_pert_composition, grad_pert_density, grad_pert_entropy, grad_pert_temp, grad_reference_composition, grad_reference_density, grad_reference_entropy, grad_reference_temp, and grad_temp.
Referenced by set_mhd_field_address::check_vector_fields(), and t_grad_field_labels::set_gradient_field_addresses().
num_divergence_fields()
integer(kind = kint) function m_grad_field_labels::num_divergence_fields
Definition at line 206 of file m_grad_field_labels.f90.
References ndiv_vector.
num_gradient_fields()
integer(kind = kint) function m_grad_field_labels::num_gradient_fields
Definition at line 213 of file m_grad_field_labels.f90.
References ngrad_scalar.
set_divergence_field_labels()
subroutine m_grad_field_labels::set_divergence_field_labels (integer(kind = kint_4b), dimension(ndiv_vector), intent(inout) n_comps, character(len = kchara), dimension(ndiv_vector), intent(inout) names, character(len = kchara), dimension(ndiv_vector), intent(inout) maths)
Definition at line 220 of file m_grad_field_labels.f90.
References div_magnetic, div_vector_potential, div_velocity, and t_field_labels::set_field_labels().
set_gradient_field_labels()
subroutine m_grad_field_labels::set_gradient_field_labels (integer(kind = kint_4b), dimension(ngrad_scalar), intent(inout) n_comps, character(len = kchara), dimension(ngrad_scalar), intent(inout) names, character(len = kchara), dimension(ngrad_scalar), intent(inout) maths)
Definition at line 238 of file m_grad_field_labels.f90.
References grad_composition, grad_density, grad_entropy, grad_pert_composition, grad_pert_density, grad_pert_entropy, grad_pert_temp, grad_reference_composition, grad_reference_density, grad_reference_entropy, grad_reference_temp, grad_temp, and t_field_labels::set_field_labels().
Variable Documentation
div_magnetic
type(field_def), parameter m_grad_field_labels::div_magnetic = field_def(n_comp = n_scalar, name = 'div_magnetic', math = '$ \partial_{i} B_{i} $')
Divergence of magnetic field \(\partial_{igrad} B_{i} \).
Definition at line 72 of file m_grad_field_labels.f90.
Referenced by check_base_field::add_field_ctl_4_grad_field(), check_divergence_field(), set_divergence_field_labels(), and t_grad_field_labels::set_gradient_field_addresses().
div_vector_potential
type(field_def), parameter m_grad_field_labels::div_vector_potential = field_def(n_comp = n_scalar, name = 'div_vector_potential', math = '$ \partial_{i} A_{i} $')
Divergence of magnetic vector potential \(\partial_{i} A_{i} \).
Definition at line 78 of file m_grad_field_labels.f90.
Referenced by check_base_field::add_field_ctl_4_grad_field(), check_divergence_field(), set_divergence_field_labels(), and t_grad_field_labels::set_gradient_field_addresses().
div_velocity
type(field_def), parameter m_grad_field_labels::div_velocity = field_def(n_comp = n_scalar, name = 'div_velocity', math = '$ \partial_{i} u_{i} $')
Divergence of velocity \(\partial_{i} u_{i} \).
Definition at line 66 of file m_grad_field_labels.f90.
Referenced by check_base_field::add_field_ctl_4_grad_field(), check_divergence_field(), set_divergence_field_labels(), and t_grad_field_labels::set_gradient_field_addresses().
grad_composition
type(field_def), parameter m_grad_field_labels::grad_composition = field_def(n_comp = n_vector, name = 'grad_composition', math = '$ \partial_{i} C $')
Field label for gradient of \(C \) \(\partial_{i} C / dz\).
Definition at line 104 of file m_grad_field_labels.f90.
Referenced by check_base_field::add_field_ctl_4_grad_field(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_gradient_field(), t_grad_field_labels::set_gradient_field_addresses(), and set_gradient_field_labels().
grad_density
type(field_def), parameter m_grad_field_labels::grad_density = field_def(n_comp = n_vector, name = 'grad_density', math = '$ \partial_{i} \rho $')
Field label for gradient of density \(\partial_{i} \rho / dz\).
Definition at line 123 of file m_grad_field_labels.f90.
Referenced by check_base_field::add_field_ctl_4_grad_field(), check_gradient_field(), t_grad_field_labels::set_gradient_field_addresses(), and set_gradient_field_labels().
grad_entropy
type(field_def), parameter m_grad_field_labels::grad_entropy = field_def(n_comp = n_vector, name = 'grad_entropy', math = '$ \partial_{i} S $')
Field label for gradient of entropy \(\partial_{i} S / dz\).
Definition at line 142 of file m_grad_field_labels.f90.
Referenced by check_base_field::add_field_ctl_4_grad_field(), check_gradient_field(), t_grad_field_labels::set_gradient_field_addresses(), and set_gradient_field_labels().
grad_pert_composition
type(field_def), parameter m_grad_field_labels::grad_pert_composition = field_def(n_comp = n_vector, name = 'grad_pert_composition', math = '$ \partial_{i} \Theta_{C} $')
Field label for gradient of perturbation of composition \(\partial_{i} \Theta_{C} / dz\).
Definition at line 110 of file m_grad_field_labels.f90.
Referenced by check_base_field::add_field_ctl_4_grad_field(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_gradient_field(), t_grad_field_labels::set_gradient_field_addresses(), and set_gradient_field_labels().
grad_pert_density
type(field_def), parameter m_grad_field_labels::grad_pert_density = field_def(n_comp = n_vector, name = 'grad_pert_density', math = '$ \partial_{i} \Theta_{\rho} $')
Field label for gradient of perturbation of density \(\partial_{i} \Theta_{\rho} / dz\).
Definition at line 129 of file m_grad_field_labels.f90.
Referenced by check_base_field::add_field_ctl_4_grad_field(), check_gradient_field(), t_grad_field_labels::set_gradient_field_addresses(), and set_gradient_field_labels().
grad_pert_entropy
type(field_def), parameter m_grad_field_labels::grad_pert_entropy = field_def(n_comp = n_vector, name = 'grad_pert_entropy', math = '$ \partial_{i} \Theta_{S} $')
Field label for gradient of perturbation of entropy \(\partial_{i} \Theta_{S} / dz\).
Definition at line 148 of file m_grad_field_labels.f90.
Referenced by check_base_field::add_field_ctl_4_grad_field(), check_gradient_field(), t_grad_field_labels::set_gradient_field_addresses(), and set_gradient_field_labels().
grad_pert_temp
type(field_def), parameter m_grad_field_labels::grad_pert_temp = field_def(n_comp = n_vector, name = 'grad_pert_temp', math = '$ \partial_{i} \Theta $')
Field label for gradient of \(\Theta \) \(\partial_{i} \Theta / dz\).
Definition at line 91 of file m_grad_field_labels.f90.
Referenced by check_base_field::add_field_ctl_4_grad_field(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_gradient_field(), t_grad_field_labels::set_gradient_field_addresses(), and set_gradient_field_labels().
grad_reference_composition
type(field_def), parameter m_grad_field_labels::grad_reference_composition = field_def(n_comp = n_vector, name = 'grad_reference_composition', math = '$ \partial_{i} C_{0} $')
Field label for gradient of reference composition \(\partial_{i} C_{0} / dz\).
Definition at line 116 of file m_grad_field_labels.f90.
Referenced by add_nodal_fields_4_mhd::add_ctl_4_ref_temp(), check_base_field::add_field_ctl_4_grad_field(), check_gradient_field(), t_grad_field_labels::set_gradient_field_addresses(), and set_gradient_field_labels().
grad_reference_density
type(field_def), parameter m_grad_field_labels::grad_reference_density = field_def(n_comp = n_vector, name = 'grad_reference_density', math = '$ \partial_{i} \rho_{0} $')
Field label for gradient of reference density \(\partial_{i} \rho_{0} / dz\).
Definition at line 135 of file m_grad_field_labels.f90.
Referenced by check_base_field::add_field_ctl_4_grad_field(), check_gradient_field(), t_grad_field_labels::set_gradient_field_addresses(), and set_gradient_field_labels().
grad_reference_entropy
type(field_def), parameter m_grad_field_labels::grad_reference_entropy = field_def(n_comp = n_vector, name = 'grad_reference_entropy', math = '$ \partial_{i} S_{0} $')
Field label for gradient of reference density \(\partial_{i} S_{0} / dz\).
Definition at line 154 of file m_grad_field_labels.f90.
Referenced by check_base_field::add_field_ctl_4_grad_field(), check_gradient_field(), t_grad_field_labels::set_gradient_field_addresses(), and set_gradient_field_labels().
grad_reference_temp
type(field_def), parameter m_grad_field_labels::grad_reference_temp = field_def(n_comp = n_vector, name = 'grad_reference_temp', math = '$ \partial_{i} T_{0} $')
Field label for gradient of reference temperature \(\partial_{i} T_{0} / dz\).
Definition at line 97 of file m_grad_field_labels.f90.
Referenced by add_nodal_fields_4_mhd::add_ctl_4_ref_temp(), check_base_field::add_field_ctl_4_grad_field(), check_gradient_field(), t_grad_field_labels::set_gradient_field_addresses(), and set_gradient_field_labels().
grad_temp
type(field_def), parameter m_grad_field_labels::grad_temp = field_def(n_comp = n_vector, name = 'grad_temp', math = '$ \partial_{i} T $')
Field label for gradient of \(T \) \(\partial_{i} T / dz\).
Definition at line 85 of file m_grad_field_labels.f90.
Referenced by check_base_field::add_field_ctl_4_grad_field(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_gradient_field(), set_control_4_pickup_sph::set_ctl_params_no_heat_nu(), t_grad_field_labels::set_gradient_field_addresses(), and set_gradient_field_labels().
ndiv_vector
integer(kind = kint), parameter, private m_grad_field_labels::ndiv_vector = 3 private
Definition at line 61 of file m_grad_field_labels.f90.
Referenced by num_divergence_fields().
ngrad_scalar
integer(kind = kint), parameter, private m_grad_field_labels::ngrad_scalar = 12 private
Definition at line 62 of file m_grad_field_labels.f90.
Referenced by num_gradient_fields().