CALYPSO: t_control_data_4_merge Module Reference
t_control_data_4_merge Module Reference
Control data for merge program.
Data Types
type control_data_4_merge
Structure for merged program control.
Functions/Subroutines
subroutine read_control_4_merge (mgd_ctl)
subroutine read_control_assemble_sph (mgd_ctl)
subroutine, private read_merge_control_data (id_control, hd_block, mgd_ctl, c_buf)
subroutine reset_merge_control_data (mgd_ctl)
subroutine, private read_merge_field_data (id_control, hd_block, mgd_ctl, c_buf)
subroutine reset_merge_field_data (mgd_ctl)
subroutine, private read_merge_step_data (id_control, hd_block, mgd_ctl, c_buf)
subroutine reset_merge_step_data (mgd_ctl)
subroutine, private read_newrst_control (id_control, hd_block, mgd_ctl, c_buf)
subroutine reset_newrst_control (mgd_ctl)
Variables
integer(kind=kint), parameter, private control_file_code = 13
character(len=kchara), parameter, private control_file_name = 'control_merge'
character(len=kchara), parameter, private ctl_assemble_sph_name = 'control_assemble_sph'
character(len=kchara), parameter, private hd_assemble = 'assemble_control'
character(len=kchara), parameter, private hd_platform = 'data_files_def'
character(len=kchara), parameter, private hd_new_data = 'new_data_files_def'
character(len=kchara), parameter, private hd_model = 'model'
character(len=kchara), parameter, private hd_control = 'control'
character(len=kchara), parameter, private hd_newrst_magne = 'newrst_magne_ctl'
character(len=kchara), parameter, private hd_orgsph_shell = 'spherical_shell_ctl'
character(len=kchara), parameter, private hd_newsph_shell = 'new_spherical_shell_ctl'
character(len=kchara), parameter, private hd_phys_values = 'phys_values_ctl'
label for block
character(len=kchara), parameter, private hd_time_step = 'time_step_ctl'
character(len=kchara), parameter, private hd_new_time_step = 'new_time_step_ctl'
character(len=kchara), parameter, private hd_magnetic_field_ratio = 'magnetic_field_ratio_ctl'
Detailed Description
Control data for merge program.
       subroutine read_control_4_merge(mgd_ctl)
       subroutine read_control_assemble_sph(mgd_ctl)
       subroutine reset_merge_control_data(mgd_ctl)
        type(control_data_4_merge), intent(inout) :: mgd_ctl
Function/Subroutine Documentation
read_control_4_merge()
subroutine t_control_data_4_merge::read_control_4_merge (type(control_data_4_merge), intent(inout) mgd_ctl)
Definition at line 118 of file t_control_data_4_merge.f90.
References control_file_code, control_file_name, hd_assemble, t_read_control_elements::load_one_line_from_control(), and read_merge_control_data().
read_control_assemble_sph()
subroutine t_control_data_4_merge::read_control_assemble_sph (type(control_data_4_merge), intent(inout) mgd_ctl)
Definition at line 139 of file t_control_data_4_merge.f90.
References control_file_code, ctl_assemble_sph_name, hd_assemble, t_read_control_elements::load_one_line_from_control(), and read_merge_control_data().
Referenced by analyzer_assemble_sph::init_assemble_sph(), analyzer_compare_sph_rst::init_compare_sph_restart(), and analyzer_rayleigh_cvt_sph::init_cvt_rayleigh_sph().
read_merge_control_data()
subroutine, private t_control_data_4_merge::read_merge_control_data (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(control_data_4_merge), intent(inout) mgd_ctl, type(buffer_for_control), intent(inout) c_buf) private
Definition at line 161 of file t_control_data_4_merge.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_control, hd_model, hd_new_data, hd_newrst_magne, hd_newsph_shell, hd_orgsph_shell, hd_platform, t_read_control_elements::load_one_line_from_control(), t_ctl_data_4_platforms::read_control_platforms(), read_merge_field_data(), read_merge_step_data(), read_newrst_control(), and t_ctl_data_gen_sph_shell::read_parallel_shell_in_mhd_ctl().
Referenced by read_control_4_merge(), and read_control_assemble_sph().
read_merge_field_data()
subroutine, private t_control_data_4_merge::read_merge_field_data (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(control_data_4_merge), intent(inout) mgd_ctl, type(buffer_for_control), intent(inout) c_buf) private
Definition at line 221 of file t_control_data_4_merge.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_phys_values, t_read_control_elements::load_one_line_from_control(), and t_ctl_data_4_fields::read_phys_data_control().
Referenced by read_merge_control_data().
read_merge_step_data()
subroutine, private t_control_data_4_merge::read_merge_step_data (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(control_data_4_merge), intent(inout) mgd_ctl, type(buffer_for_control), intent(inout) c_buf) private
Definition at line 259 of file t_control_data_4_merge.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_new_time_step, hd_time_step, t_read_control_elements::load_one_line_from_control(), and t_ctl_data_4_time_steps::read_control_time_step_data().
Referenced by read_merge_control_data().
read_newrst_control()
subroutine, private t_control_data_4_merge::read_newrst_control (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(control_data_4_merge), intent(inout) mgd_ctl, type(buffer_for_control), intent(inout) c_buf) private
Definition at line 298 of file t_control_data_4_merge.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_magnetic_field_ratio, t_read_control_elements::load_one_line_from_control(), and t_control_array_real::read_real_ctl_type().
Referenced by read_merge_control_data().
reset_merge_control_data()
subroutine t_control_data_4_merge::reset_merge_control_data (type(control_data_4_merge), intent(inout) mgd_ctl)
Definition at line 200 of file t_control_data_4_merge.f90.
References t_ctl_data_gen_sph_shell::dealloc_parallel_shell_ctl(), t_ctl_data_4_platforms::reset_control_platforms(), reset_merge_field_data(), reset_merge_step_data(), and reset_newrst_control().
reset_merge_field_data()
subroutine t_control_data_4_merge::reset_merge_field_data (type(control_data_4_merge), intent(inout) mgd_ctl)
Definition at line 246 of file t_control_data_4_merge.f90.
References t_ctl_data_4_fields::dealloc_phys_control().
Referenced by reset_merge_control_data().
reset_merge_step_data()
subroutine t_control_data_4_merge::reset_merge_step_data (type(control_data_4_merge), intent(inout) mgd_ctl)
Definition at line 286 of file t_control_data_4_merge.f90.
Referenced by reset_merge_control_data().
reset_newrst_control()
subroutine t_control_data_4_merge::reset_newrst_control (type(control_data_4_merge), intent(inout) mgd_ctl)
Definition at line 323 of file t_control_data_4_merge.f90.
Referenced by reset_merge_control_data().
Variable Documentation
control_file_code
integer (kind = kint), parameter, private t_control_data_4_merge::control_file_code = 13 private
Definition at line 31 of file t_control_data_4_merge.f90.
Referenced by read_control_4_merge(), and read_control_assemble_sph().
control_file_name
character (len = kchara), parameter, private t_control_data_4_merge::control_file_name = 'control_merge' private
Definition at line 32 of file t_control_data_4_merge.f90.
Referenced by read_control_4_merge().
ctl_assemble_sph_name
character (len = kchara), parameter, private t_control_data_4_merge::ctl_assemble_sph_name = 'control_assemble_sph' private
Definition at line 34 of file t_control_data_4_merge.f90.
Referenced by read_control_assemble_sph().
hd_assemble
character(len=kchara), parameter, private t_control_data_4_merge::hd_assemble = 'assemble_control' private
Definition at line 68 of file t_control_data_4_merge.f90.
Referenced by read_control_4_merge(), and read_control_assemble_sph().
hd_control
character(len=kchara), parameter, private t_control_data_4_merge::hd_control = 'control' private
Definition at line 78 of file t_control_data_4_merge.f90.
Referenced by read_merge_control_data().
hd_magnetic_field_ratio
character(len=kchara), parameter, private t_control_data_4_merge::hd_magnetic_field_ratio = 'magnetic_field_ratio_ctl' private
Definition at line 97 of file t_control_data_4_merge.f90.
Referenced by read_newrst_control().
hd_model
character(len=kchara), parameter, private t_control_data_4_merge::hd_model = 'model' private
Definition at line 77 of file t_control_data_4_merge.f90.
Referenced by read_merge_control_data().
hd_new_data
character(len=kchara), parameter, private t_control_data_4_merge::hd_new_data = 'new_data_files_def' private
Definition at line 75 of file t_control_data_4_merge.f90.
Referenced by read_merge_control_data().
hd_new_time_step
character(len=kchara), parameter, private t_control_data_4_merge::hd_new_time_step = 'new_time_step_ctl' private
Definition at line 92 of file t_control_data_4_merge.f90.
Referenced by read_merge_step_data().
hd_newrst_magne
character(len=kchara), parameter, private t_control_data_4_merge::hd_newrst_magne = 'newrst_magne_ctl' private
Definition at line 79 of file t_control_data_4_merge.f90.
Referenced by read_merge_control_data().
hd_newsph_shell
character(len=kchara), parameter, private t_control_data_4_merge::hd_newsph_shell = 'new_spherical_shell_ctl' private
Definition at line 84 of file t_control_data_4_merge.f90.
Referenced by read_merge_control_data().
hd_orgsph_shell
character(len=kchara), parameter, private t_control_data_4_merge::hd_orgsph_shell = 'spherical_shell_ctl' private
Definition at line 82 of file t_control_data_4_merge.f90.
Referenced by read_merge_control_data().
hd_phys_values
character(len=kchara), parameter, private t_control_data_4_merge::hd_phys_values = 'phys_values_ctl' private
label for block
Definition at line 88 of file t_control_data_4_merge.f90.
Referenced by read_merge_field_data().
hd_platform
character(len=kchara), parameter, private t_control_data_4_merge::hd_platform = 'data_files_def' private
Definition at line 73 of file t_control_data_4_merge.f90.
Referenced by read_merge_control_data().
hd_time_step
character(len=kchara), parameter, private t_control_data_4_merge::hd_time_step = 'time_step_ctl' private
Definition at line 90 of file t_control_data_4_merge.f90.
Referenced by read_merge_step_data().