CALYPSO: init_sph_trans Module Reference
init_sph_trans Module Reference
Initialize spherical harmonics transform.
Functions/Subroutines
subroutine initialize_sph_trans (ncomp_trans, nvector_trns, nscalar_trns, sph, comms_sph, trans_p, WK_leg, WK_FFTs)
subroutine initialize_legendre_trans (nvector_legendre, ncomp_trans, sph, comms_sph, leg, idx_trns, iflag_recv)
subroutine, private init_legendre_rtm (l_truncation, sph_rj, sph_rtm, sph_rlm, idx_trns, leg)
subroutine, private set_blocks_4_leg_trans (nvector_legendre, ncomp_trans, sph, comms_sph, idx_trns, iflag_recv)
Detailed Description
Initialize spherical harmonics transform.
      subroutine initialize_sph_trans                                 &
     &         (ncomp_trans, nvector_trns, nscalar_trns,              &
     &          sph, comms_sph, trans_p, WK_leg, WK_FFTs)
        type(sph_grids), intent(inout) :: sph
        type(sph_comm_tables), intent(inout) :: comms_sph
        type(parameters_4_sph_trans), intent(inout) :: trans_p
        type(legendre_trns_works), intent(inout) :: WK_leg
        type(work_for_FFTs), intent(inout) :: WK_FFTs
      subroutine initialize_legendre_trans                            &
     &         (nvector_legendre, ncomp_trans, sph, comms_sph,        &
     &          leg, idx_trns, iflag_recv)
        type(sph_grids), intent(in) :: sph
        type(sph_comm_tables), intent(in) :: comms_sph
        type(legendre_4_sph_trans), intent(inout) :: leg
        type(index_4_sph_trans), intent(inout) :: idx_trns
Function/Subroutine Documentation
init_legendre_rtm()
subroutine, private init_sph_trans::init_legendre_rtm (integer(kind = kint), intent(in) l_truncation, type(sph_rj_grid), intent(in) sph_rj, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(index_4_sph_trans), intent(in) idx_trns, type(legendre_4_sph_trans), intent(inout) leg) private
Definition at line 144 of file init_sph_trans.f90.
References t_schmidt_poly_on_rtm::alloc_schmidt_normalize(), t_schmidt_poly_on_rtm::alloc_schmidt_p_rtm_pole(), t_schmidt_poly_on_rtm::alloc_schmidt_poly_rtm(), t_schmidt_poly_on_rtm::alloc_trans_schmidt_rtm(), schmidt_poly_on_rtm_grid::copy_sph_normalization_2_rj(), schmidt_poly_on_rtm_grid::copy_sph_normalization_2_rlm(), schmidt_poly_on_rtm_grid::set_gauss_points_rtm(), schmidt_poly_on_rtm_grid::set_lagender_4_rlm(), schmidt_poly_on_rtm_grid::set_lagender_pole_rlm(), set_params_sph_trans::set_sin_theta_rtm(), and set_legendre_matrices::set_trans_legendre_rtm().
Referenced by initialize_legendre_trans().
initialize_legendre_trans()
subroutine init_sph_trans::initialize_legendre_trans (integer(kind = kint), intent(in) nvector_legendre, integer(kind = kint), intent(in) ncomp_trans, type(sph_grids), intent(inout) sph, type(sph_comm_tables), intent(inout) comms_sph, type(legendre_4_sph_trans), intent(inout) leg, type(index_4_sph_trans), intent(inout) idx_trns, integer(kind = kint), intent(inout) iflag_recv)
Definition at line 87 of file init_sph_trans.f90.
References t_work_4_sph_trans::alloc_work_4_sph_trans(), set_params_sph_trans::const_conatitude_rtp(), set_params_sph_trans::const_sin_theta_rtp(), set_params_sph_trans::find_conjugate_sph_order(), init_legendre_rtm(), set_params_sph_trans::radial_4_sph_trans(), set_blocks_4_leg_trans(), set_params_sph_trans::set_mdx_rlm_rtm(), and set_legendre_matrices::set_sym_legendre_stack().
Referenced by init_sphrical_transform_mhd::init_leg_fourier_trans_mhd(), and initialize_sph_trans().
initialize_sph_trans()
subroutine init_sph_trans::initialize_sph_trans (integer(kind = kint), intent(in) ncomp_trans, integer(kind = kint), intent(in) nvector_trns, integer(kind = kint), intent(in) nscalar_trns, type(sph_grids), intent(inout) sph, type(sph_comm_tables), intent(inout) comms_sph, type(parameters_4_sph_trans), intent(inout) trans_p, type(legendre_trns_works), intent(inout) WK_leg, type(work_for_ffts), intent(inout) WK_FFTs)
Definition at line 49 of file init_sph_trans.f90.
References init_fft_4_sph::init_fourier_transform_4_sph(), initialize_legendre_trans(), t_legendre_trans_select::sel_init_legendre_trans(), and t_work_4_sph_trans::write_import_table_mode().
set_blocks_4_leg_trans()
subroutine, private init_sph_trans::set_blocks_4_leg_trans (integer(kind = kint), intent(in) nvector_legendre, integer(kind = kint), intent(in) ncomp_trans, type(sph_grids), intent(in) sph, type(sph_comm_tables), intent(in) comms_sph, type(index_4_sph_trans), intent(inout) idx_trns, integer(kind = kint), intent(inout) iflag_recv) private
Definition at line 197 of file init_sph_trans.f90.
References t_work_4_sph_trans::alloc_l_rtm_block(), cal_minmax_and_stacks::count_number_4_smp(), init_spherical_srs::init_sph_send_recv_n(), m_constants::ione, and m_sph_communicators::split_rtp_comms().
Referenced by initialize_legendre_trans().