CALYPSO: t_spheric_group Module Reference
t_spheric_group Module Reference
Structure of group data for spherical shell model.
Data Types
type sph_group_data
Structure of group data for spherical transform.
Functions/Subroutines
subroutine dealloc_sph_grid_group (sph_grps)
subroutine dealloc_sph_mode_group (sph_grps)
Detailed Description
Structure of group data for spherical shell model.
      subroutine dealloc_sph_grid_group(sph_grps)
      subroutine dealloc_sph_mode_group(sph_grps)
        type(sph_group_data), intent(inout) :: sph_grps
Function/Subroutine Documentation
dealloc_sph_grid_group()
subroutine t_spheric_group::dealloc_sph_grid_group (type(sph_group_data), intent(inout) sph_grps)
Definition at line 47 of file t_spheric_group.f90.
References t_group_data::dealloc_group().
Referenced by t_spheric_data_io::dealloc_rtp_grid_io(), and parallel_load_data_4_sph::dealloc_sph_modes().
dealloc_sph_mode_group()
subroutine t_spheric_group::dealloc_sph_mode_group (type(sph_group_data), intent(inout) sph_grps)
Definition at line 61 of file t_spheric_group.f90.
References t_group_data::dealloc_group().
Referenced by t_spheric_data_io::dealloc_rj_mode_io(), and parallel_load_data_4_sph::dealloc_sph_modes().