CALYPSO: t_psf_patch_data Module Reference
t_psf_patch_data Module Reference
Structure for parallel sectioned data.
Data Types
type psf_local_data
type psf_parameters
Functions/Subroutines
subroutine alloc_output_comps_psf (num_phys, params)
subroutine alloc_area_group_psf (params)
subroutine dealloc_output_comps_psf (params)
subroutine dealloc_area_group_psf (params)
subroutine alloc_dat_on_patch_psf (psf_mesh)
subroutine dealloc_dat_on_patch_psf (psf_mesh)
Detailed Description
Structure for parallel sectioned data.
      subroutine alloc_output_comps_psf(num_phys, params)
      subroutine alloc_area_group_psf(params)
      subroutine dealloc_output_comps_psf(params)
      subroutine dealloc_area_group_psf(params)
      subroutine alloc_dat_on_patch_psf(ncomp, psf_mesh)
      subroutine dealloc_dat_on_patch_psf(psf_mesh)
Function/Subroutine Documentation
alloc_area_group_psf()
subroutine t_psf_patch_data::alloc_area_group_psf (type(psf_parameters), intent(inout) params)
Definition at line 76 of file t_psf_patch_data.f90.
Referenced by t_control_params_4_iso::set_control_4_iso(), and t_control_params_4_psf::set_control_4_psf().
alloc_dat_on_patch_psf()
subroutine t_psf_patch_data::alloc_dat_on_patch_psf (type(psf_local_data), intent(inout) psf_mesh)
Definition at line 111 of file t_psf_patch_data.f90.
Referenced by set_fields_for_psf::alloc_psf_field_data().
alloc_output_comps_psf()
subroutine t_psf_patch_data::alloc_output_comps_psf (integer(kind= kint), intent(in) num_phys, type(psf_parameters), intent(inout) params)
Definition at line 57 of file t_psf_patch_data.f90.
Referenced by t_control_params_4_iso::set_control_4_field_on_iso(), and t_control_params_4_psf::set_control_4_psf().
dealloc_area_group_psf()
subroutine t_psf_patch_data::dealloc_area_group_psf (type(psf_parameters), intent(inout) params)
Definition at line 99 of file t_psf_patch_data.f90.
dealloc_dat_on_patch_psf()
subroutine t_psf_patch_data::dealloc_dat_on_patch_psf (type(psf_local_data), intent(inout) psf_mesh)
Definition at line 122 of file t_psf_patch_data.f90.
Referenced by set_fields_for_psf::dealloc_psf_field_data().
dealloc_output_comps_psf()
subroutine t_psf_patch_data::dealloc_output_comps_psf (type(psf_parameters), intent(inout) params)
Definition at line 88 of file t_psf_patch_data.f90.