CALYPSO: legendre_transform_spin Module Reference
legendre_transform_spin Module Reference
Legendre transforms (innermost loop is spherical harmonics)
Functions/Subroutines
subroutine leg_backward_trans_sym_spin (ncomp, nvector, nscalar, sph_rlm, sph_rtm, comm_rlm, comm_rtm, leg, idx_trns, n_WR, n_WS, WR, WS, WK_l_sml)
subroutine leg_forward_trans_sym_spin (ncomp, nvector, nscalar, sph_rtm, sph_rlm, comm_rtm, comm_rlm, leg, idx_trns, n_WR, n_WS, WR, WS, WK_l_sml)
Detailed Description
Legendre transforms (innermost loop is spherical harmonics)
    Backward transforms
      subroutine leg_backward_trans_sym_spin(ncomp, nvector, nscalar, &
     &          sph_rlm, sph_rtm, comm_rlm, comm_rtm, leg, idx_trns,  &
     &          n_WR, n_WS, WR, WS, WK_l_sml)
        Input:  sp_rlm   (Order: poloidal,diff_poloidal,toroidal)
        Output: vr_rtm   (Order: radius,theta,phi)
    Forward transforms
        Input:  vr_rtm   (Order: radius,theta,phi)
        Output: sp_rlm   (Order: poloidal,diff_poloidal,toroidal)
      subroutine leg_forward_trans_sym_spin(ncomp, nvector, nscalar,  &
     &          sph_rtm, sph_rlm, comm_rtm, comm_rlm, leg, idx_trns,  &
     &          n_WR, n_WS, WR, WS, WK_l_sml)
        type(sph_rtm_grid), intent(in) :: sph_rtm
        type(sph_rlm_grid), intent(in) :: sph_rlm
        type(sph_comm_tbl), intent(in) :: comm_rtm, comm_rlm
        type(legendre_4_sph_trans), intent(in) :: leg
        type(index_4_sph_trans), intent(in) :: idx_trns
        type(leg_trns_matmul_work), intent(inout) :: WK_l_mtl
Parameters
ncomp Total number of components for spherical transform
nvector Number of vector for spherical transform
nscalar Number of scalar (including tensor components) for spherical transform
Function/Subroutine Documentation
leg_backward_trans_sym_spin()
subroutine legendre_transform_spin::leg_backward_trans_sym_spin (integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_comm_tbl), intent(in) comm_rlm, type(sph_comm_tbl), intent(in) comm_rtm, type(legendre_4_sph_trans), intent(in) leg, type(index_4_sph_trans), intent(in) idx_trns, integer(kind = kint), intent(in) n_WR, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_wr), intent(inout) WR, real (kind=kreal), dimension(n_ws), intent(inout) WS, type(leg_trns_sym_mul_work), intent(inout) WK_l_sml)
Definition at line 61 of file legendre_transform_spin.f90.
References legendre_bwd_trans_sym_spin::leg_bwd_trans_scalar_sym_spin(), and legendre_bwd_trans_sym_spin::leg_bwd_trans_vector_sym_spin().
Referenced by t_legendre_trans_select::sel_backward_legendre_trans().
leg_forward_trans_sym_spin()
subroutine legendre_transform_spin::leg_forward_trans_sym_spin (integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_comm_tbl), intent(in) comm_rtm, type(sph_comm_tbl), intent(in) comm_rlm, type(legendre_4_sph_trans), intent(in) leg, type(index_4_sph_trans), intent(in) idx_trns, integer(kind = kint), intent(in) n_WR, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_wr), intent(inout) WR, real (kind=kreal), dimension(n_ws), intent(inout) WS, type(leg_trns_sym_mul_work), intent(inout) WK_l_sml)
Definition at line 91 of file legendre_transform_spin.f90.
References legendre_fwd_trans_sym_spin::leg_fwd_trans_scalar_sym_spin(), and legendre_fwd_trans_sym_spin::leg_fwd_trans_vector_sym_spin().
Referenced by t_legendre_trans_select::sel_forward_legendre_trans().