CALYPSO: cal_sph_exp_1st_diff Module Reference
cal_sph_exp_1st_diff Module Reference
Evaluate first radial derivative for spectr data.
Functions/Subroutines
subroutine cal_sph_nod_gradient_2 (kr_in, kr_out, is_fld, is_grad, nidx_rj, radius_1d_rj_r, g_sph_rj, d1nod_mat_fdm_2, n_point, ntot_phys_rj, d_rj)
subroutine normalize_sph_average_grad (is_fld, idx_rj_degree_zero, nidx_rj, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_nod_vect_dr_2 (kr_in, kr_out, is_fld, nidx_rj, d1nod_mat_fdm_2, n_point, ntot_phys_rj, d_rj)
Detailed Description
Evaluate first radial derivative for spectr data.
      subroutine cal_sph_nod_gradient_2(kr_in, kr_out,                &
     &          is_fld, is_grad, nidx_rj, radius_1d_rj_r, g_sph_rj,   &
     &          d1nod_mat_fdm_2, n_point, ntot_phys_rj, d_rj)
      subroutine normalize_sph_average_grad                           &
     &         (is_fld, idx_rj_degree_zero, nidx_rj,                  &
     &          n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_nod_vect_dr_2(kr_in, kr_out, is_fld,         &
     &          nidx_rj, d1nod_mat_fdm_2, n_point, ntot_phys_rj, d_rj)
Parameters
kr_in radial ID for inner boundary
kr_out radial ID for outer boundary
dnod_rj(n_point) Input spectr data
dnod_dr(n_point,nd) Gradient of field
dnod_dr(n_point,1) = r^2 l(l+1) d phi / dr
dnod_dr(n_point,2) = phi
dnod_dr(n_point,3) = 0
Function/Subroutine Documentation
cal_sph_nod_gradient_2()
subroutine cal_sph_exp_1st_diff::cal_sph_nod_gradient_2 (integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) kr_out, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_grad, integer(kind = kint), dimension(2), intent(in) nidx_rj, real(kind = kreal), dimension(nidx_rj(1)), intent(in) radius_1d_rj_r, real(kind = kreal), dimension(nidx_rj(2),13), intent(in) g_sph_rj, real(kind = kreal), dimension(nidx_rj(1),-1:1), intent(in) d1nod_mat_fdm_2, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 41 of file cal_sph_exp_1st_diff.f90.
References m_constants::zero.
Referenced by const_sph_radial_grad::const_pressure_gradient(), const_sph_radial_grad::const_radial_grad_scalar(), and const_sph_radial_grad::const_sph_gradient_no_bc().
cal_sph_nod_vect_dr_2()
subroutine cal_sph_exp_1st_diff::cal_sph_nod_vect_dr_2 (integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) kr_out, integer(kind = kint), intent(in) is_fld, integer(kind = kint), dimension(2), intent(in) nidx_rj, real(kind = kreal), dimension(nidx_rj(1),-1:1), intent(in) d1nod_mat_fdm_2, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 122 of file cal_sph_exp_1st_diff.f90.
Referenced by const_sph_diffusion::const_sph_magnetic_diffusion(), const_sph_diffusion::const_sph_viscous_diffusion(), and const_sph_diffusion::const_sph_vorticirty_diffusion().
normalize_sph_average_grad()
subroutine cal_sph_exp_1st_diff::normalize_sph_average_grad (integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) idx_rj_degree_zero, integer(kind = kint), dimension(2), intent(in) nidx_rj, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 92 of file cal_sph_exp_1st_diff.f90.
References m_constants::two, and m_constants::zero.
Referenced by const_sph_radial_grad::const_pressure_gradient(), const_sph_radial_grad::const_radial_grad_scalar(), and const_sph_radial_grad::const_sph_gradient_no_bc().