CALYPSO: ordering_sph_mesh_to_rtp Module Reference
ordering_sph_mesh_to_rtp Module Reference
Functions/Subroutines
subroutine ordering_for_sph_mesh (ip_r, ip_t, stk_lc1d, sph_gl1d, stbl, sph_rtp, node, ele, nod_grp, nod_comm)
subroutine, private ordering_sph_mesh_for_rtp (nidx_rtp, ip_r, ip_t, stk_lc1d, sph_gl1d, stbl, node, nod_comm, inod_old2new)
subroutine, private ordering_sph_mesh_for_prt (nidx_rtp, ip_r, ip_t, stk_lc1d, sph_gl1d, stbl, node, nod_comm, inod_old2new)
subroutine, private ordering_sph_mesh_and_group (inod_old2new, node, ele, nod_grp, nod_comm)
Function/Subroutine Documentation
ordering_for_sph_mesh()
subroutine ordering_sph_mesh_to_rtp::ordering_for_sph_mesh (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, type(sph_1d_index_stack), intent(in) stk_lc1d, type(sph_1d_global_index), intent(in) sph_gl1d, type(comm_table_make_sph), intent(in) stbl, type(sph_rtp_grid), intent(in) sph_rtp, type(node_data), intent(inout) node, type(element_data), intent(inout) ele, type(group_data), intent(inout) nod_grp, type(communication_table), intent(inout) nod_comm)
Definition at line 34 of file ordering_sph_mesh_to_rtp.f90.
References ordering_sph_mesh_and_group(), ordering_sph_mesh_for_prt(), and ordering_sph_mesh_for_rtp().
Referenced by set_fem_mesh_4_sph::s_const_fem_mesh_for_sph().
ordering_sph_mesh_and_group()
subroutine, private ordering_sph_mesh_to_rtp::ordering_sph_mesh_and_group (integer(kind = kint), dimension(node%numnod), intent(in) inod_old2new, type(node_data), intent(inout) node, type(element_data), intent(inout) ele, type(group_data), intent(inout) nod_grp, type(communication_table), intent(inout) nod_comm) private
Definition at line 230 of file ordering_sph_mesh_to_rtp.f90.
Referenced by ordering_for_sph_mesh().
ordering_sph_mesh_for_prt()
subroutine, private ordering_sph_mesh_to_rtp::ordering_sph_mesh_for_prt (integer(kind = kint), dimension(3), intent(in) nidx_rtp, integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, type(sph_1d_index_stack), intent(in) stk_lc1d, type(sph_1d_global_index), intent(in) sph_gl1d, type(comm_table_make_sph), intent(in) stbl, type(node_data), intent(in) node, type(communication_table), intent(in) nod_comm, integer(kind = kint), dimension(node%numnod), intent(inout) inod_old2new) private
Definition at line 156 of file ordering_sph_mesh_to_rtp.f90.
References cal_sph_node_addresses::sph_shell_node_id().
Referenced by ordering_for_sph_mesh().
ordering_sph_mesh_for_rtp()
subroutine, private ordering_sph_mesh_to_rtp::ordering_sph_mesh_for_rtp (integer(kind = kint), dimension(3), intent(in) nidx_rtp, integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, type(sph_1d_index_stack), intent(in) stk_lc1d, type(sph_1d_global_index), intent(in) sph_gl1d, type(comm_table_make_sph), intent(in) stbl, type(node_data), intent(inout) node, type(communication_table), intent(in) nod_comm, integer(kind = kint), dimension(node%numnod), intent(inout) inod_old2new) private
Definition at line 80 of file ordering_sph_mesh_to_rtp.f90.
References cal_sph_node_addresses::sph_shell_node_id().
Referenced by ordering_for_sph_mesh().