CALYPSO: groups_io Module Reference
groups_io Module Reference
Base routines for spectrum group data IO.
Functions/Subroutines
subroutine read_group_data (id_file, grp_IO)
subroutine read_surf_grp_data (id_file, surf_grp_IO)
subroutine write_grp_data (id_file, grp_IO)
subroutine write_surf_grp_data (id_file, surf_grp_IO)
Variables
character(len=255), private character_4_read = ''
Detailed Description
Base routines for spectrum group data IO.
      subroutine read_group_datamesh_file_id, grp_IO)
      subroutine read_surf_grp_data(id_file, surf_grp_IO)
        type(group_data), intent(inout) :: grp_IO
        type(surface_group_data), intent(inout) :: surf_grp_IO
      subroutine write_grp_data(id_file, grp_IO)
      subroutine write_surf_grp_data(id_file, surf_grp_IO)
        type(group_data), intent(in) :: grp_IO
        type(surface_group_data), intent(in) :: surf_grp_IO
Function/Subroutine Documentation
read_group_data()
subroutine groups_io::read_group_data (integer(kind = kint), intent(in) id_file, type(group_data), intent(inout) grp_IO)
Definition at line 42 of file groups_IO.f90.
References t_group_data::alloc_group_item(), t_group_data::alloc_group_num(), group_data_io::character_4_read, group_data_io::read_group_item(), group_data_io::read_group_stack(), and skip_comment_f::skip_comment().
Referenced by sph_modes_grids_data_io::read_geom_rtp_data(), mesh_data_io::read_mesh_groups(), and sph_modes_grids_data_io::read_spectr_modes_rj_data().
read_surf_grp_data()
subroutine groups_io::read_surf_grp_data (integer(kind = kint), intent(in) id_file, type(surface_group_data), intent(inout) surf_grp_IO)
Definition at line 73 of file groups_IO.f90.
References t_group_data::alloc_sf_group_item(), t_group_data::alloc_sf_group_num(), group_data_io::character_4_read, group_data_io::read_group_stack(), group_data_io::read_surface_group_item(), and skip_comment_f::skip_comment().
Referenced by mesh_data_io::read_mesh_groups().
write_grp_data()
subroutine groups_io::write_grp_data (integer(kind = kint), intent(in) id_file, type(group_data), intent(in) grp_IO)
Definition at line 104 of file groups_IO.f90.
References group_data_io::write_group_data().
Referenced by sph_modes_grids_data_io::write_geom_rtp_data(), mesh_data_io::write_mesh_groups(), and sph_modes_grids_data_io::write_spectr_modes_rj_data().
write_surf_grp_data()
subroutine groups_io::write_surf_grp_data (integer(kind = kint), intent(in) id_file, type(surface_group_data), intent(in) surf_grp_IO)
Definition at line 121 of file groups_IO.f90.
References group_data_io::write_surf_group_data().
Referenced by mesh_data_io::write_mesh_groups().
Variable Documentation
character_4_read
character(len=255), private groups_io::character_4_read = '' private
Definition at line 33 of file groups_IO.f90.