CALYPSO: analyzer_test_sph Module Reference
analyzer_test_sph Module Reference
Functions/Subroutines
subroutine init_test_sph
subroutine analyze_test_sph
Variables
integer(kind=kint), parameter id_check = 44
character(len=kchara), parameter, private check_header = 'comm_errors'
character(len=kchara), private control_file_name = 'control_sph_shell'
type(sph_mesh_generation_ctl), save, private sph_test_ctl
Structure for file settings.
type(sph_grid_maker_in_sim), save sph_maker_t
Structure to check and construct spherical shell mesh.
type(sph_mesh_field_data), save, private sph_test
type(gen_sph_file_io_params), save test_sph_files
Function/Subroutine Documentation
analyze_test_sph()
subroutine analyzer_test_sph::analyze_test_sph
Definition at line 91 of file analyzer_test_sph.f90.
References set_parallel_file_name::add_dat_extension(), set_parallel_file_name::add_process_id(), cmp_trans_sph_indices::allocate_idx_sph_recieve(), cmp_trans_sph_tests::allocate_real_sph_test(), calypso_mpi_int::calypso_mpi_allreduce_one_int(), check_header, cmp_trans_sph_indices::check_missing_sph_indices(), cmp_trans_sph_indices::compare_transfer_sph_indices(), cmp_trans_sph_tests::compare_transfer_sph_reals(), cmp_trans_sph_indices::deallocate_idx_sph_recieve(), cmp_trans_sph_tests::deallocate_real_sph_test(), delete_data_files::delete_file_by_f(), id_check, m_machine_parameter::iflag_debug, select_copy_from_recv::iflag_import_item, select_copy_from_recv::iflag_import_rev, m_constants::ione, m_constants::isix, m_constants::ithree, m_constants::itwo, calypso_mpi::my_rank, sph_test, cmp_trans_sph_tests::sph_transfer_test_1(), cmp_trans_sph_tests::sph_transfer_test_2(), cmp_trans_sph_tests::sph_transfer_test_3(), cmp_trans_sph_tests::sph_transfer_test_6(), cmp_trans_sph_tests::sph_transfer_test_n(), and cmp_trans_sph_indices::sph_type_indices_transfer().
Referenced by test_sph_model().
init_test_sph()
subroutine analyzer_test_sph::init_test_sph
Definition at line 54 of file analyzer_test_sph.f90.
References t_check_and_make_sph_mesh::check_and_make_sph_mesh(), control_file_name, m_elapsed_labels_send_recv::elpsed_label_calypso_send_recv(), m_elapsed_labels_send_recv::elpsed_label_field_send_recv(), m_machine_parameter::iflag_debug, m_work_time::init_elapse_time_by_total(), calypso_mpi::my_rank, t_ctl_data_const_sph_mesh::read_control_4_const_shell(), t_ctl_params_gen_sph_shell::set_control_4_gen_shell_grids(), sph_maker_t, sph_test, sph_test_ctl, test_sph_files, and set_control_platform_data::turn_off_debug_flag_by_ctl().
Referenced by test_sph_model().
Variable Documentation
check_header
character(len=kchara), parameter, private analyzer_test_sph::check_header = 'comm_errors' private
Definition at line 31 of file analyzer_test_sph.f90.
Referenced by analyze_test_sph().
control_file_name
character (len = kchara), private analyzer_test_sph::control_file_name = 'control_sph_shell' private
Definition at line 33 of file analyzer_test_sph.f90.
Referenced by init_test_sph().
id_check
integer(kind = kint), parameter analyzer_test_sph::id_check = 44
Definition at line 30 of file analyzer_test_sph.f90.
Referenced by analyze_test_sph().
sph_maker_t
type(sph_grid_maker_in_sim), save analyzer_test_sph::sph_maker_t
Structure to check and construct spherical shell mesh.
Definition at line 39 of file analyzer_test_sph.f90.
Referenced by init_test_sph().
sph_test
type(sph_mesh_field_data), save, private analyzer_test_sph::sph_test private
Definition at line 41 of file analyzer_test_sph.f90.
Referenced by analyze_test_sph(), and init_test_sph().
sph_test_ctl
type(sph_mesh_generation_ctl), save, private analyzer_test_sph::sph_test_ctl private
Structure for file settings.
Definition at line 37 of file analyzer_test_sph.f90.
Referenced by init_test_sph().
test_sph_files
type(gen_sph_file_io_params), save analyzer_test_sph::test_sph_files
Definition at line 43 of file analyzer_test_sph.f90.
Referenced by init_test_sph().