CALYPSO: calypso_mpi_int4 Module Reference
calypso_mpi_int4 Module Reference
MPI communication routines for 4 byte integer in Calypso.
Functions/Subroutines
subroutine calypso_mpi_bcast_one_int4 (buffer, root)
subroutine calypso_mpi_allreduce_one_int4 (i4_local, i4_global, operation)
subroutine calypso_mpi_seek_write_int4 (id_mpi_file, ioffset, num, i4_vector, sta_IO)
subroutine calypso_mpi_seek_read_int4 (id_mpi_file, ioffset, num, i4_vector, sta_IO)
subroutine calypso_mpi_seek_write_one_int4 (id_mpi_file, ioffset, i4_dat, sta_IO)
subroutine calypso_mpi_seek_read_one_int4 (id_mpi_file, ioffset, i4_dat, sta_IO)
Detailed Description
MPI communication routines for 4 byte integer in Calypso.
      subroutine calypso_mpi_bcast_one_int4(buffer, root)
        integer, intent(in) :: root
        integer(kind = kint_4b), intent(inout) :: buffer
      subroutine calypso_mpi_allreduce_one_int4                       &
     &         (i4_local, i4_global, operation)
        integer, intent(in) :: operation
        integer(kind = kint_4b), intent(in) ::    i4_local
        integer(kind = kint_4b), intent(inout) :: i4_global
      subroutine calypso_mpi_seek_write_int4                          &
     &         (id_mpi_file, ioffset, num, i4_vector)
        integer, intent(in) ::  id_mpi_file
        integer(kind = MPI_OFFSET_KIND), intent(in) :: ioffset
        integer(kind = kint_gl), intent(in) :: num
        integer(kind = kint_4b), intent(in) :: i4_vector(num)
       integer, intent(inout) :: sta_IO(MPI_STATUS_SIZE)
      subroutine calypso_mpi_seek_write_one_int4                      &
     &         (id_mpi_file, ioffset, i4_dat, sta_IO)
        integer, intent(in) ::  id_mpi_file
        integer(kind = kint_gl), intent(in) :: ioffset
        integer(kind = kint_4b), intent(in) :: i4_dat
        integer, intent(inout) :: sta_IO(MPI_STATUS_SIZE)
      subroutine calypso_mpi_seek_read_one_int4                       &
     &         (id_mpi_file, ioffset, i4_dat, sta_IO)
        integer, intent(in) ::  id_mpi_file
        integer(kind = kint_gl), intent(in) :: ioffset
        integer(kind = kint_4b), intent(inout) :: i4_dat
        integer, intent(inout) :: sta_IO(MPI_STATUS_SIZE)
Parameters
icode error code
message message to output
Function/Subroutine Documentation
calypso_mpi_allreduce_one_int4()
subroutine calypso_mpi_int4::calypso_mpi_allreduce_one_int4 (integer(kind = kint_4b), intent(in) i4_local, integer(kind = kint_4b), intent(inout) i4_global, integer, intent(in) operation)
Definition at line 76 of file calypso_mpi_int4.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_four_int, and calypso_mpi::ierr_mpi.
Referenced by cal_rms_fields_by_sph::set_domains_4_spectr_output().
calypso_mpi_bcast_one_int4()
subroutine calypso_mpi_int4::calypso_mpi_bcast_one_int4 (integer(kind = kint_4b), intent(inout) buffer, integer, intent(in) root)
Definition at line 58 of file calypso_mpi_int4.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_four_int, and calypso_mpi::ierr_mpi.
Referenced by gz_mpi_binary_head_io::gz_mpi_read_byte_check(), m_calypso_mpi_io::mpi_read_set_endian_flag(), field_data_mpi_io::sync_field_name_mpi(), and mpi_picked_sph_spectr_io::write_picked_specr_head_mpi().
calypso_mpi_seek_read_int4()
subroutine calypso_mpi_int4::calypso_mpi_seek_read_int4 (integer, intent(in) id_mpi_file, integer(kind = mpi_offset_kind), intent(in) ioffset, integer(kind = kint_gl), intent(in) num, integer(kind = kint_4b), dimension(num), intent(inout) i4_vector, integer, dimension(mpi_status_size), intent(inout) sta_IO)
Definition at line 127 of file calypso_mpi_int4.f90.
References calypso_mpi::calypso_four_int, m_constants::huge_20, calypso_mpi::ierr_mpi, and m_precision::kint_4b.
Referenced by m_calypso_mpi_io::mpi_read_int4_b().
calypso_mpi_seek_read_one_int4()
subroutine calypso_mpi_int4::calypso_mpi_seek_read_one_int4 (integer, intent(in) id_mpi_file, integer(kind = kint_gl), intent(in) ioffset, integer(kind = kint_4b), intent(inout) i4_dat, integer, dimension(mpi_status_size), intent(inout) sta_IO)
Definition at line 180 of file calypso_mpi_int4.f90.
References calypso_mpi::calypso_four_int, and calypso_mpi::ierr_mpi.
Referenced by m_calypso_mpi_io::mpi_read_set_endian_flag().
calypso_mpi_seek_write_int4()
subroutine calypso_mpi_int4::calypso_mpi_seek_write_int4 (integer, intent(in) id_mpi_file, integer(kind = mpi_offset_kind), intent(in) ioffset, integer(kind = kint_gl), intent(in) num, integer(kind = kint_4b), dimension(num), intent(in) i4_vector, integer, dimension(mpi_status_size), intent(inout) sta_IO)
Definition at line 96 of file calypso_mpi_int4.f90.
References calypso_mpi::calypso_four_int, m_constants::huge_20, calypso_mpi::ierr_mpi, and m_precision::kint_4b.
Referenced by m_calypso_mpi_io::mpi_write_int4_b().
calypso_mpi_seek_write_one_int4()
subroutine calypso_mpi_int4::calypso_mpi_seek_write_one_int4 (integer, intent(in) id_mpi_file, integer(kind = kint_gl), intent(in) ioffset, integer(kind = kint_4b), intent(in) i4_dat, integer, dimension(mpi_status_size), intent(inout) sta_IO)
Definition at line 159 of file calypso_mpi_int4.f90.
References calypso_mpi::calypso_four_int, and calypso_mpi::ierr_mpi.
Referenced by m_calypso_mpi_io::mpi_write_endian_flag().