CALYPSO: set_fem_mesh_4_sph Module Reference
set_fem_mesh_4_sph Module Reference
Functions/Subroutines
subroutine s_const_fem_mesh_for_sph (id_rank, gauss, sph_params, sph_rtp, sph_rj, gen_sph, mesh, group, stbl)
subroutine, private const_fem_geometry_for_sph (ip_r, ip_t, sph_params, sph_rj, gauss, stbl, node, ele)
subroutine, private const_fem_groups_for_sph (ip_r, ip_t, sph_params, gen_sph, stbl, group)
subroutine, private const_nod_comm_table_for_sph (id_rank, ip_r, ip_t, s3d_ranks, stbl, nod_comm)
Function/Subroutine Documentation
const_fem_geometry_for_sph()
subroutine, private set_fem_mesh_4_sph::const_fem_geometry_for_sph (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(gauss_points), intent(in) gauss, type(comm_table_make_sph), intent(in) stbl, type(node_data), intent(inout) node, type(element_data), intent(inout) ele) private
Definition at line 112 of file set_FEM_mesh_4_sph.f90.
References t_geometry_data::alloc_node_geometry_w_sph(), t_geometry_data::allocate_ele_connect_type(), set_sph_local_element::count_local_elements_sph_mesh(), set_sph_local_node::count_numnod_local_sph_mesh(), set_sph_local_element::set_local_elements_sph_mesh(), and set_sph_local_node::set_local_nodes_sph_mesh().
Referenced by s_const_fem_mesh_for_sph().
const_fem_groups_for_sph()
subroutine, private set_fem_mesh_4_sph::const_fem_groups_for_sph (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, type(sph_shell_parameters), intent(in) sph_params, type(construct_spherical_grid), intent(in) gen_sph, type(comm_table_make_sph), intent(in) stbl, type(mesh_groups), intent(inout) group) private
Definition at line 155 of file set_FEM_mesh_4_sph.f90.
References set_sph_ele_group::allocate_sph_ele_grp_flag(), set_sph_ele_group::count_sph_local_ele_group(), set_sph_ele_group::count_sph_local_ele_grp_item(), set_sph_node_group::count_sph_local_node_group(), set_sph_node_group::count_sph_local_node_grp_item(), set_sph_surf_group::count_sph_local_surf_group(), set_sph_surf_group::count_sph_local_surf_grp_item(), set_sph_ele_group::deallocate_sph_ele_grp_flag(), cal_minmax_and_stacks::s_cal_total_and_stacks(), set_sph_ele_group::set_sph_local_ele_grp_item(), set_sph_node_group::set_sph_local_node_grp_item(), and set_sph_surf_group::set_sph_local_surf_grp_item().
Referenced by s_const_fem_mesh_for_sph().
const_nod_comm_table_for_sph()
subroutine, private set_fem_mesh_4_sph::const_nod_comm_table_for_sph (integer, intent(in) id_rank, integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, type(spheric_global_rank), intent(in) s3d_ranks, type(comm_table_make_sph), intent(inout) stbl, type(communication_table), intent(inout) nod_comm) private
Definition at line 233 of file set_FEM_mesh_4_sph.f90.
References t_sph_mesh_1d_connect::alloc_1d_comm_tbl_4_sph(), t_comm_table::alloc_comm_table_num(), t_comm_table::alloc_export_item(), t_comm_table::alloc_import_item(), const_comm_tbl_4_sph_mesh::count_export_4_sph_mesh(), const_comm_tbl_4_sph_mesh::count_import_4_sph_mesh(), const_comm_tbl_4_sph_mesh::count_neib_4_sph_center_mesh(), const_comm_tbl_4_sph_mesh::count_neib_4_sph_mesh(), t_sph_mesh_1d_connect::dealloc_1d_comm_tbl_4_sph(), const_comm_tbl_4_sph_mesh::set_export_rtp_sph_mesh(), const_comm_tbl_4_sph_mesh::set_import_rtp_sph_mesh(), const_comm_tbl_4_sph_mesh::set_neib_4_sph_center_mesh(), and const_comm_tbl_4_sph_mesh::set_neib_4_sph_mesh().
Referenced by s_const_fem_mesh_for_sph().
s_const_fem_mesh_for_sph()
subroutine set_fem_mesh_4_sph::s_const_fem_mesh_for_sph (integer, intent(in) id_rank, type(gauss_points), intent(in) gauss, type(sph_shell_parameters), intent(in) sph_params, type(sph_rtp_grid), intent(in) sph_rtp, type(sph_rj_grid), intent(in) sph_rj, type(construct_spherical_grid), intent(in) gen_sph, type(mesh_geometry), intent(inout) mesh, type(mesh_groups), intent(inout) group, type(comm_table_make_sph), intent(inout) stbl)
Definition at line 37 of file set_FEM_mesh_4_sph.f90.
References const_fem_geometry_for_sph(), const_fem_groups_for_sph(), const_nod_comm_table_for_sph(), ordering_sph_mesh_to_rtp::ordering_for_sph_mesh(), coordinate_converter::position_2_xyz(), and set_nnod_4_ele_by_type::set_3d_nnod_4_sfed_by_ele().
Referenced by const_fem_mesh_sph_mhd::base_fem_mesh_sph_mhd().