CALYPSO: t_each_sph_boundary_io_data Module Reference
t_each_sph_boundary_io_data Module Reference
Boundary condition data from external file.
Data Types
type each_boundary_spectr
Structure for each boundary condition.
Functions/Subroutines
subroutine alloc_each_bc_item_ctl (bc_ctls)
subroutine dealloc_each_bc_item_ctl (bc_ctls)
subroutine bcast_each_bc_item_num (bc_ctls)
subroutine bcast_each_bc_item_ctl (bc_ctls)
subroutine read_each_boundary_spectr (id_file, bc_ctls)
subroutine write_each_boundary_spectr (id_file, bc_ctls)
subroutine set_bc_4_sph_scalar_by_file (sph_rj, bc_ctls, bc_data)
subroutine set_bc_4_sph_vector_by_file (sph_rj, bc_ctls, vp_data, dp_data, vt_data)
subroutine bc_4_evo_scalar_sph_by_file (sph_rj, bc_ctls, bc_data)
subroutine bc_4_evo_vect2_sph_by_file (sph_rj, bc_ctls, vp_data, vt_data)
subroutine bc_4_evo_vector_sph_by_file (sph_rj, bc_ctls, vp_data, dp_data, vt_data)
Detailed Description
Boundary condition data from external file.
      subroutine alloc_each_bc_item_ctl(bc_ctls)
      subroutine bcast_each_bc_item_ctl(bc_ctls)
      subroutine dealloc_each_bc_item_ctl(bc_ctls)
        type(each_boundary_spectr), intent(inout) :: bc_ctls
      subroutine read_each_boundary_spectr(id_file, bc_ctls)
        type(each_boundary_spectr), intent(inout) :: bc_ctls
      subroutine write_each_boundary_spectr(id_file, bc_ctls)
        type(each_boundary_spectr), intent(in) :: bc_ctls
      subroutine set_bc_4_sph_scalar_by_file(sph_rj, bc_ctls, bc_data)
      subroutine set_bc_4_sph_vector_by_file                          &
     &         (sph_rj, bc_ctls, vp_data, dp_data, vt_data)
      subroutine bc_4_evo_scalar_sph_by_file(sph_rj, bc_ctls, bc_data)
      subroutine bc_4_evo_vect2_sph_by_file                           &
     &         (sph_rj, bc_ctls, vp_data, vt_data)
      subroutine bc_4_evo_vector_sph_by_file(sph_rj, bc_ctls,         &
     &          vp_data, dp_data, vt_data)
        type(sph_rj_grid), intent(in) :: sph_rj
        type(each_boundary_spectr), intent(in) :: bc_ctls
  ---------------------------------------------------------------------
       line 2:     Field name to define the first boundary condition
       line 3:     Place to define the first boundary condition
       line 4:     Number of spherical harmonics modes
                    for each boundary condition
       line 5...:  Spectrum data for the boundary conditions
                  (degree $l$, order $m$, and harmonics coefficients)
        Return to 2...
  ---------------------------------------------------------------------
Function/Subroutine Documentation
alloc_each_bc_item_ctl()
subroutine t_each_sph_boundary_io_data::alloc_each_bc_item_ctl (type(each_boundary_spectr), intent(inout) bc_ctls)
Definition at line 74 of file t_each_sph_boundary_IO_data.f90.
Referenced by t_sph_boundary_input_data::bcast_boundary_spectr_file(), and read_each_boundary_spectr().
bc_4_evo_scalar_sph_by_file()
subroutine t_each_sph_boundary_io_data::bc_4_evo_scalar_sph_by_file (type(sph_rj_grid), intent(in) sph_rj, type(each_boundary_spectr), intent(in) bc_ctls, real(kind = kreal), dimension(sph_rj%nidx_rj(2)), intent(inout) bc_data)
Definition at line 255 of file t_each_sph_boundary_IO_data.f90.
References t_spheric_rj_data::find_local_sph_address().
Referenced by set_sph_bc_data_by_file::set_evolved_grad_bc_by_file(), and set_sph_bc_data_by_file::set_evolved_scalar_bc_by_file().
bc_4_evo_vect2_sph_by_file()
subroutine t_each_sph_boundary_io_data::bc_4_evo_vect2_sph_by_file (type(sph_rj_grid), intent(in) sph_rj, type(each_boundary_spectr), intent(in) bc_ctls, real(kind = kreal), dimension(sph_rj%nidx_rj(2)), intent(inout) vp_data, real(kind = kreal), dimension(sph_rj%nidx_rj(2)), intent(inout) vt_data)
Definition at line 281 of file t_each_sph_boundary_IO_data.f90.
References t_spheric_rj_data::find_local_sph_address().
Referenced by set_sph_bc_data_by_file::set_evolved_vector_bc_by_file().
bc_4_evo_vector_sph_by_file()
subroutine t_each_sph_boundary_io_data::bc_4_evo_vector_sph_by_file (type(sph_rj_grid), intent(in) sph_rj, type(each_boundary_spectr), intent(in) bc_ctls, real(kind = kreal), dimension(sph_rj%nidx_rj(2)), intent(inout) vp_data, real(kind = kreal), dimension(sph_rj%nidx_rj(2)), intent(inout) dp_data, real(kind = kreal), dimension(sph_rj%nidx_rj(2)), intent(inout) vt_data)
Definition at line 315 of file t_each_sph_boundary_IO_data.f90.
References t_spheric_rj_data::find_local_sph_address().
Referenced by set_sph_bc_data_by_file::set_evolved_vector_bc_by_file().
bcast_each_bc_item_ctl()
subroutine t_each_sph_boundary_io_data::bcast_each_bc_item_ctl (type(each_boundary_spectr), intent(inout) bc_ctls)
Definition at line 123 of file t_each_sph_boundary_IO_data.f90.
References calypso_mpi_int::calypso_mpi_bcast_int(), calypso_mpi_real::calypso_mpi_bcast_real(), and transfer_to_long_integers::cast_long().
Referenced by t_sph_boundary_input_data::bcast_boundary_spectr_file().
bcast_each_bc_item_num()
subroutine t_each_sph_boundary_io_data::bcast_each_bc_item_num (type(each_boundary_spectr), intent(inout) bc_ctls)
Definition at line 102 of file t_each_sph_boundary_IO_data.f90.
References calypso_mpi_char::calypso_mpi_bcast_character(), calypso_mpi_int::calypso_mpi_bcast_one_int(), transfer_to_long_integers::cast_long(), and m_precision::kchara.
Referenced by t_sph_boundary_input_data::bcast_boundary_spectr_file().
dealloc_each_bc_item_ctl()
subroutine t_each_sph_boundary_io_data::dealloc_each_bc_item_ctl (type(each_boundary_spectr), intent(inout) bc_ctls)
Definition at line 91 of file t_each_sph_boundary_IO_data.f90.
Referenced by t_sph_boundary_input_data::dealloc_sph_bc_item_ctl().
read_each_boundary_spectr()
subroutine t_each_sph_boundary_io_data::read_each_boundary_spectr (integer(kind = kint), intent(in) id_file, type(each_boundary_spectr), intent(inout) bc_ctls)
Definition at line 142 of file t_each_sph_boundary_IO_data.f90.
References alloc_each_bc_item_ctl(), set_sph_boundary_from_file::num_comp_bc_data(), and skip_comment_f::skip_comment().
Referenced by t_sph_boundary_input_data::read_boundary_spectr_file().
set_bc_4_sph_scalar_by_file()
subroutine t_each_sph_boundary_io_data::set_bc_4_sph_scalar_by_file (type(sph_rj_grid), intent(in) sph_rj, type(each_boundary_spectr), intent(in) bc_ctls, real(kind = kreal), dimension(sph_rj%nidx_rj(2)), intent(inout) bc_data)
Definition at line 202 of file t_each_sph_boundary_IO_data.f90.
References t_spheric_rj_data::find_local_sph_address().
Referenced by set_sph_bc_data_by_file::set_fixed_grad_bc_by_file(), and set_sph_bc_data_by_file::set_fixed_scalar_bc_by_file().
set_bc_4_sph_vector_by_file()
subroutine t_each_sph_boundary_io_data::set_bc_4_sph_vector_by_file (type(sph_rj_grid), intent(in) sph_rj, type(each_boundary_spectr), intent(in) bc_ctls, real(kind = kreal), dimension(sph_rj%nidx_rj(2)), intent(inout) vp_data, real(kind = kreal), dimension(sph_rj%nidx_rj(2)), intent(inout) dp_data, real(kind = kreal), dimension(sph_rj%nidx_rj(2)), intent(inout) vt_data)
Definition at line 224 of file t_each_sph_boundary_IO_data.f90.
References t_spheric_rj_data::find_local_sph_address().
Referenced by set_sph_bc_data_by_file::set_fixed_vector_bc_by_file().
write_each_boundary_spectr()
subroutine t_each_sph_boundary_io_data::write_each_boundary_spectr (integer(kind = kint), intent(in) id_file, type(each_boundary_spectr), intent(in) bc_ctls)
Definition at line 175 of file t_each_sph_boundary_IO_data.f90.
Referenced by t_sph_boundary_input_data::write_boundary_spectr_file().