CALYPSO: schmidt Module Reference
schmidt Module Reference
module for Legendre polynomials with Schmidt normalization
Functions/Subroutines
subroutine schmidt_legendre (ltr, theta, p, df)
subroutine diff_schmidt_legendre (ltr, p, dp)
subroutine full_normalize_from_smdt (ltr, p, dp)
Detailed Description
module for Legendre polynomials with Schmidt normalization
      subroutine schmidt_legendre(ltr, theta,  p, df)
*************************************************************
*     lead legendre and adjoint Legendle Polynomial
*
*      p(m,l)  : Schmidt Polynomial
*         Normalization...
*           P_{l}^{0} = P_{l,0}
*           P_{l}^{m} = sqrt(2(l-m)! / (l+m)!) * P_{l,m}
*        theta :  input colatitude (0 =< theta <= pi)
*
*        df(m,l)  :   work area
*
*************************************************************
      subroutine diff_schmidt_legendre(ltr, p, dp)
*************************************************************
*     lead difference of Schmidt Polynomial
*
*      p(m,l)  : Schmidt Polynomial (input)
*         Normalization...
*           P_{l}^{0} = P_{l,0}
*           P_{l}^{m} = sqrt(2(l-m)! / (l+m)!) * P_{l,m}
*      dp(m,l) : diffrential of Schmidt Polynomial  dp/dtheta
*
*************************************************************
      subroutine full_normalize_from_smdt(ltr, p, dp)
Parameters
ltr Truncation level for the polynomial
theta Input degree (\(0 \le \theta \le \pi \))
p(m,l) Schmidt Polynomial \(P_{l}^{m} \)
dp(m,l) diffrence of Schmidt Polynomial \(d P_{l}^{m} / d\theta \)
df(m) work area
Function/Subroutine Documentation
diff_schmidt_legendre()
subroutine schmidt::diff_schmidt_legendre (integer(kind = kint), intent(in) ltr, real(kind = kreal), dimension(0:ltr,0:ltr), intent(in) p, real(kind = kreal), dimension(0:ltr,0:ltr), intent(inout) dp)
Definition at line 115 of file schmidt.f90.
References m_constants::half, and m_constants::zero.
Referenced by t_schmidt_polynomial::dschmidt().
full_normalize_from_smdt()
subroutine schmidt::full_normalize_from_smdt (integer(kind = kint), intent(in) ltr, real(kind = kreal), dimension(0:ltr,0:ltr), intent(inout) p, real(kind = kreal), dimension(0:ltr,0:ltr), intent(inout) dp)
Definition at line 154 of file schmidt.f90.
Referenced by t_schmidt_polynomial::full_norm_legendre().
schmidt_legendre()
subroutine schmidt::schmidt_legendre (integer(kind = kint), intent(in) ltr, real(kind = kreal), intent(in) theta, real(kind = kreal), dimension(0:ltr,0:ltr), intent(inout) p, real(kind = kreal), dimension(0:ltr+2), intent(inout) df)
Definition at line 60 of file schmidt.f90.
References m_constants::one, and m_constants::two.
Referenced by t_schmidt_polynomial::dschmidt().