CALYPSO: const_element_comm_table Module Reference
const_element_comm_table Module Reference
Routines to construca element communication table.
Data Types
type work_4_ele_comm_table
Functions/Subroutines
subroutine elapsed_label_4_ele_comm_tbl
subroutine const_comm_table_by_connenct (txt, numele, nnod_4_ele, ie, internal_flag, x_ele, node, nod_comm, neib_e, x_ref_ele, host, e_comm)
subroutine alloc_element_rev_imports (numnod, ntot_export, ntot_import_e, wk_comm)
subroutine alloc_element_rev_exports (ntot_export_e, wk_comm)
subroutine dealloc_element_rev_imports (wk_comm)
subroutine dealloc_element_rev_exports (wk_comm)
Variables
logical, save, private iflag_ecomm_time = .FALSE.
integer(kind=kint), save, private ist_elapsed
integer(kind=kint), save, private ied_elapsed
Detailed Description
Routines to construca element communication table.
      subroutine elapsed_label_4_ele_comm_tbl
      subroutine const_comm_table_by_connenct                         &
     &         (txt, numele, nnod_4_ele, ie, internal_flag, x_ele,    &
     &          node, nod_comm, neib_e, x_ref_ele, host, e_comm)
        type(node_data), intent(in) :: node
        type(element_around_node), intent(in) :: host
        type(element_around_node), intent(in) :: neib_e
        type(communication_table), intent(in) :: nod_comm
        type(communication_table), intent(inout) :: e_comm
Function/Subroutine Documentation
alloc_element_rev_exports()
subroutine const_element_comm_table::alloc_element_rev_exports (integer(kind = kint), intent(in) ntot_export_e, type(work_4_ele_comm_table), intent(inout) wk_comm)
Definition at line 247 of file const_element_comm_table.f90.
Referenced by const_comm_table_by_connenct().
alloc_element_rev_imports()
subroutine const_element_comm_table::alloc_element_rev_imports (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) ntot_export, integer(kind = kint), intent(in) ntot_import_e, type(work_4_ele_comm_table), intent(inout) wk_comm)
Definition at line 222 of file const_element_comm_table.f90.
Referenced by const_comm_table_by_connenct().
const_comm_table_by_connenct()
subroutine const_element_comm_table::const_comm_table_by_connenct (character(len=kchara), intent(in) txt, integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) nnod_4_ele, integer(kind = kint), dimension(numele, nnod_4_ele), intent(in) ie, integer(kind = kint), dimension(numele), intent(in) internal_flag, real(kind = kreal), dimension(numele,3), intent(in) x_ele, type(node_data), intent(in) node, type(communication_table), intent(in) nod_comm, type(element_around_node), intent(in) neib_e, real(kind = kreal), dimension(neib_e%istack_4_node(node%numnod)), intent(in) x_ref_ele, type(element_around_node), intent(in) host, type(communication_table), intent(inout) e_comm)
Definition at line 100 of file const_element_comm_table.f90.
References alloc_element_rev_exports(), alloc_element_rev_imports(), t_comm_table::alloc_export_item(), t_comm_table::alloc_export_num(), t_comm_table::alloc_import_item(), t_comm_table::alloc_import_num(), t_comm_table::alloc_neighbouring_id(), const_global_element_ids::check_element_position(), find_element_comm_table::count_element_import_num(), dealloc_element_rev_exports(), dealloc_element_rev_imports(), make_element_comm_table_sr::element_data_reverse_sr(), set_element_export_item::element_export_item_in_ext(), reverse_sr_int::element_num_reverse_sr(), m_work_time::end_elapsed_time(), iflag_ecomm_time, ist_elapsed, reverse_sr_int::local_node_id_reverse_sr(), set_element_export_item::s_set_element_export_item(), find_element_comm_table::set_element_import_item(), m_solver_sr::sr_sig1, and m_work_time::start_elapsed_time().
Referenced by const_element_comm_tables::const_edge_comm_table(), const_element_comm_tables::const_ele_comm_tbl(), and const_element_comm_tables::const_surf_comm_table().
dealloc_element_rev_exports()
subroutine const_element_comm_table::dealloc_element_rev_exports (type(work_4_ele_comm_table), intent(inout) wk_comm)
Definition at line 277 of file const_element_comm_table.f90.
Referenced by const_comm_table_by_connenct().
dealloc_element_rev_imports()
subroutine const_element_comm_table::dealloc_element_rev_imports (type(work_4_ele_comm_table), intent(inout) wk_comm)
Definition at line 265 of file const_element_comm_table.f90.
Referenced by const_comm_table_by_connenct().
elapsed_label_4_ele_comm_tbl()
subroutine const_element_comm_table::elapsed_label_4_ele_comm_tbl
Definition at line 78 of file const_element_comm_table.f90.
References m_work_time::append_elapsed_times(), m_work_time::elps1, ied_elapsed, iflag_ecomm_time, and ist_elapsed.
Variable Documentation
ied_elapsed
integer(kind = kint), save, private const_element_comm_table::ied_elapsed private
Definition at line 63 of file const_element_comm_table.f90.
Referenced by elapsed_label_4_ele_comm_tbl().
iflag_ecomm_time
logical, save, private const_element_comm_table::iflag_ecomm_time = .FALSE. private
Definition at line 61 of file const_element_comm_table.f90.
Referenced by const_comm_table_by_connenct(), and elapsed_label_4_ele_comm_tbl().
ist_elapsed
integer(kind = kint), save, private const_element_comm_table::ist_elapsed private
Definition at line 62 of file const_element_comm_table.f90.
Referenced by const_comm_table_by_connenct(), and elapsed_label_4_ele_comm_tbl().