CALYPSO: analyzer_compare_sph_rst Module Reference
analyzer_compare_sph_rst Module Reference
Main loop to assemble spectr data.
Functions/Subroutines
subroutine init_compare_sph_restart
subroutine analyze_compare_sph_restart
Variables
type(control_param_assemble), save asbl_param_s
type(spectr_data_4_assemble), save sph_asbl_s
type(time_data), save init_t
Detailed Description
Main loop to assemble spectr data.
      subroutine init_compare_sph_restart
      subroutine analyze_compare_sph_restart
Function/Subroutine Documentation
analyze_compare_sph_restart()
subroutine analyzer_compare_sph_rst::analyze_compare_sph_restart
Definition at line 123 of file analyzer_compare_sph_rst.f90.
References asbl_param_s, calypso_mpi::calypso_mpi_abort(), calypso_mpi_int::calypso_mpi_allreduce_one_int(), calypso_mpi::calypso_mpi_barrier(), compare_by_assemble_sph::compare_assembled_sph_data(), t_field_data_io::dealloc_phys_data_io(), t_field_data_io::dealloc_phys_name_io(), t_spectr_data_4_assemble::dealloc_spectr_data_4_assemble(), m_machine_parameter::e_message, m_machine_parameter::iflag_debug, init_t, new_sph_restart::load_org_sph_data(), calypso_mpi::my_rank, calypso_mpi::nprocs, field_io_select::sel_read_alloc_step_sph_file(), new_sph_restart::set_assembled_sph_data(), share_field_data::share_each_field_data(), share_field_data::share_time_step_data(), and sph_asbl_s.
Referenced by compare_sph_restart().
init_compare_sph_restart()
subroutine analyzer_compare_sph_rst::init_compare_sph_restart
Definition at line 49 of file analyzer_compare_sph_rst.f90.
References t_spectr_data_4_assemble::alloc_spectr_data_4_assemble(), asbl_param_s, bcast_4_assemble_sph_ctl::bcast_merge_control_data(), parallel_gen_sph_grids::check_and_make_para_rj_mode(), t_check_and_make_sph_mesh::check_and_make_sph_rj_mode(), r_interpolate_marged_sph::const_r_interpolate_table(), t_field_data_io::dealloc_merged_field_stack(), new_sph_restart::load_field_name_assemble_sph(), assemble_sph_fields::load_new_spectr_rj_data(), calypso_mpi::my_rank, t_control_data_4_merge::read_control_assemble_sph(), count_nnod_4_asseble_sph::s_count_nnod_4_asseble_sph(), set_control_newsph::set_control_4_newsph(), assemble_sph_fields::share_new_spectr_field_names(), assemble_sph_fields::share_org_spectr_field_names(), assemble_sph_fields::share_org_sph_rj_data(), and sph_asbl_s.
Referenced by compare_sph_restart().
Variable Documentation
asbl_param_s
type(control_param_assemble), save analyzer_compare_sph_rst::asbl_param_s
Definition at line 39 of file analyzer_compare_sph_rst.f90.
Referenced by analyze_compare_sph_restart(), and init_compare_sph_restart().
init_t
type(time_data), save analyzer_compare_sph_rst::init_t
Definition at line 41 of file analyzer_compare_sph_rst.f90.
Referenced by analyze_compare_sph_restart().
sph_asbl_s
type(spectr_data_4_assemble), save analyzer_compare_sph_rst::sph_asbl_s
Definition at line 40 of file analyzer_compare_sph_rst.f90.
Referenced by analyze_compare_sph_restart(), and init_compare_sph_restart().