CALYPSO: copy_rtp_vectors_4_grad Module Reference
copy_rtp_vectors_4_grad Module Reference
Evaluate pressure and energy fluxes for snapshots.
Functions/Subroutines
subroutine copy_vectors_rtp_4_grad (sph, b_trns_base, fn_trns_dvec, trns_b_MHD, trns_f_ngSGS)
subroutine, private copy_vect_to_grad_vect_rtp (sph_rtp, ib_vect, if_grad_vx, if_grad_vy, if_grad_vz, ncomp_rj_2_rtp, ncomp_rtp_2_rj, fld_rtp, frc_rtp)
subroutine, private sel_scalar_from_trans (sph_rtp, v_rtp, d_sph)
Detailed Description
Evaluate pressure and energy fluxes for snapshots.
      subroutine copy_vectors_rtp_4_grad(sph,                         &
     &          b_trns_base, fn_trns_dvec, trns_b_MHD, trns_f_ngSGS)
        type(sph_grids), intent(in) :: sph
        type(base_field_address), intent(in) :: b_trns_base
        type(diff_vector_address), intent(in) :: fn_trns_dvec
        type(spherical_transform_data), intent(in) :: trns_b_MHD
        type(spherical_transform_data), intent(inout) :: trns_f_ngSGS
      subroutine copy_vect_to_grad_vect_rtp                           &
     &         (sph_rtp, ib_vect, if_grad_vx, if_grad_vy, if_grad_vz, &
     &          ncomp_rj_2_rtp, ncomp_rtp_2_rj, fld_rtp, frc_rtp)
      subroutine sel_scalar_from_trans(sph_rtp, v_rtp, d_sph)
Function/Subroutine Documentation
copy_vect_to_grad_vect_rtp()
subroutine, private copy_rtp_vectors_4_grad::copy_vect_to_grad_vect_rtp (type(sph_rtp_grid), intent(in) sph_rtp, integer(kind = kint), intent(in) ib_vect, integer(kind = kint), intent(in) if_grad_vx, integer(kind = kint), intent(in) if_grad_vy, integer(kind = kint), intent(in) if_grad_vz, integer(kind = kint), intent(in) ncomp_rj_2_rtp, integer(kind = kint), intent(in) ncomp_rtp_2_rj, real(kind = kreal), dimension(sph_rtp%nnod_rtp,ncomp_rj_2_rtp), intent(in) fld_rtp, real(kind = kreal), dimension(sph_rtp%nnod_rtp,ncomp_rtp_2_rj), intent(inout) frc_rtp) private
Definition at line 95 of file copy_rtp_vectors_4_grad.f90.
References sel_scalar_from_trans().
Referenced by copy_vectors_rtp_4_grad().
copy_vectors_rtp_4_grad()
subroutine copy_rtp_vectors_4_grad::copy_vectors_rtp_4_grad (type(sph_grids), intent(in) sph, type(base_field_address), intent(in) b_trns_base, type(diff_vector_address), intent(in) fn_trns_dvec, type(spherical_transform_data), intent(in) trns_b_MHD, type(spherical_transform_data), intent(inout) trns_f_ngSGS)
Definition at line 43 of file copy_rtp_vectors_4_grad.f90.
References copy_vect_to_grad_vect_rtp().
Referenced by lead_fields_4_sph_mhd::gradients_of_vectors_sph().
sel_scalar_from_trans()
subroutine, private copy_rtp_vectors_4_grad::sel_scalar_from_trans (type(sph_rtp_grid), intent(in) sph_rtp, real(kind = kreal), dimension(sph_rtp%nnod_rtp), intent(in) v_rtp, real(kind = kreal), dimension(sph_rtp%nnod_rtp), intent(inout) d_sph) private
Definition at line 124 of file copy_rtp_vectors_4_grad.f90.
References copy_field_4_sph_trans::copy_scalar_from_trans_smp().
Referenced by copy_vect_to_grad_vect_rtp().