CALYPSO: field_data_mpi_io Module Reference
field_data_mpi_io Module Reference
Output merged field file using MPI-IO.
Functions/Subroutines
subroutine sync_field_time_mpi (t_IO)
subroutine sync_field_header_mpi (num_pe, id_rank, istack_merged, nnod)
subroutine sync_field_name_mpi (ilength, field_name)
subroutine sync_field_names_mpi (num_field, field_name)
subroutine write_field_name_mpi (id_fld, ioff_gl, field_name)
subroutine read_field_time_mpi (id_fld, num_pe, ioff_gl, t_IO)
subroutine read_field_header_mpi (id_fld, num_pe, id_rank, ioff_gl, nnod, num_field, istack_merged)
subroutine read_field_num_mpi (id_fld, ioff_gl, num_field, ncomp_field)
subroutine read_field_name_mpi (id_fld, ioff_gl, field_name)
Detailed Description
Output merged field file using MPI-IO.
      subroutine sync_field_time_mpi(t_IO)
        type(time_data), intent(inout) :: t_IO
      subroutine sync_field_header_mpi                                &
     &         (num_pe, id_rank, istack_merged, nnod)
      subroutine sync_field_comp_mpi(num_field, ncomp_field)
      subroutine sync_field_name_mpi(ilength, field_name)
      subroutine sync_field_names_mpi(num_field, field_name)
      subroutine read_field_time_mpi(id_fld, num_pe, ioff_gl, t_IO)
        type(time_data), intent(inout) :: t_IO
      subroutine read_field_header_mpi(id_fld, num_pe, id_rank,       &
     &           ioff_gl, nnod, num_field, istack_merged)
      subroutine read_field_num_mpi                                   &
     &         (id_fld, ioff_gl, num_field, ncomp_field)
      subroutine read_field_name_mpi(id_fld, ioff_gl, field_name)
   Data format for the merged ascii field data
     1.   Number of process
     2.   Time step
     3.   Time, Delta t
     4.   Stacks of numbe of data points
     5.   Number of fields
     6.   List of number of components
     7.   Each field data  (Itarate 7.1 - 7.3)
      7.1   Field name
      7.2   List of data size (Byte)
      7.3   Field data
Function/Subroutine Documentation
read_field_header_mpi()
subroutine field_data_mpi_io::read_field_header_mpi (integer, intent(in) id_fld, integer, intent(in) num_pe, integer, intent(in) id_rank, integer(kind = kint_gl), intent(inout) ioff_gl, integer(kind = kint_gl), intent(inout) nnod, integer(kind = kint), intent(inout) num_field, integer(kind = kint_gl), dimension(0:num_pe), intent(inout) istack_merged)
Definition at line 182 of file field_data_MPI_IO.f90.
References calypso_mpi_int8::calypso_mpi_bcast_int8(), calypso_mpi_int::calypso_mpi_bcast_one_int(), m_calypso_mpi_io::mpi_read_one_chara_b(), calypso_mpi::my_rank, field_data_io::read_field_istack_nod_buffer(), field_data_io::read_field_num_buffer(), and sync_field_header_mpi().
Referenced by field_file_mpi_io::read_alloc_step_fld_file_mpi(), field_file_mpi_io::read_alloc_step_fld_head_mpi(), ucd_field_mpi_io::read_alloc_ucd_fld_file_mpi(), field_file_mpi_io::read_step_field_file_mpi(), and ucd_field_mpi_io::read_ucd_field_file_mpi().
read_field_name_mpi()
subroutine field_data_mpi_io::read_field_name_mpi (integer, intent(in) id_fld, integer(kind = kint_gl), intent(inout) ioff_gl, character(len=kchara), intent(inout) field_name)
Definition at line 272 of file field_data_MPI_IO.f90.
References m_calypso_mpi_io::mpi_read_one_chara_b(), calypso_mpi::my_rank, field_data_io::read_each_field_name_buffer(), and sync_field_name_mpi().
Referenced by mpi_groups_io::mpi_read_group_data(), mpi_groups_io::mpi_read_surf_grp_data(), field_block_mpi_io::read_field_data_mpi(), and field_block_mpi_io::read_field_names_mpi().
read_field_num_mpi()
subroutine field_data_mpi_io::read_field_num_mpi (integer, intent(in) id_fld, integer(kind = kint_gl), intent(inout) ioff_gl, integer(kind=kint), intent(in) num_field, integer(kind=kint), dimension(num_field), intent(inout) ncomp_field)
Definition at line 236 of file field_data_MPI_IO.f90.
References calypso_mpi_int::calypso_mpi_bcast_int(), transfer_to_long_integers::cast_long(), m_calypso_mpi_io::mpi_read_one_chara_b(), calypso_mpi::my_rank, and field_data_io::read_field_comp_buffer().
Referenced by field_file_mpi_io::read_alloc_step_fld_file_mpi(), field_file_mpi_io::read_alloc_step_fld_head_mpi(), ucd_field_mpi_io::read_alloc_ucd_fld_file_mpi(), field_file_mpi_io::read_step_field_file_mpi(), and ucd_field_mpi_io::read_ucd_field_file_mpi().
read_field_time_mpi()
subroutine field_data_mpi_io::read_field_time_mpi (integer, intent(in) id_fld, integer, intent(in) num_pe, integer(kind = kint_gl), intent(inout) ioff_gl, type(time_data), intent(inout) t_IO)
Definition at line 144 of file field_data_MPI_IO.f90.
References calypso_mpi::calypso_mpi_abort(), m_error_ids::ierr_fld, time_data_io::len_step_data_buf, m_calypso_mpi_io::mpi_read_one_chara_b(), calypso_mpi::my_rank, time_data_io::read_step_data_buffer(), and sync_field_time_mpi().
Referenced by field_file_mpi_io::read_alloc_step_fld_file_mpi(), field_file_mpi_io::read_alloc_step_fld_head_mpi(), ucd_field_mpi_io::read_alloc_ucd_fld_file_mpi(), field_file_mpi_io::read_step_field_file_mpi(), and ucd_field_mpi_io::read_ucd_field_file_mpi().
sync_field_header_mpi()
subroutine field_data_mpi_io::sync_field_header_mpi (integer, intent(in) num_pe, integer, intent(in) id_rank, integer(kind = kint_gl), dimension(0:num_pe), intent(in) istack_merged, integer(kind = kint_gl), intent(inout) nnod)
Definition at line 73 of file field_data_MPI_IO.f90.
Referenced by gz_field_block_mpi_io::read_field_header_gz_mpi(), read_field_header_mpi(), and field_block_mpi_io_b::read_field_header_mpi_b().
sync_field_name_mpi()
subroutine field_data_mpi_io::sync_field_name_mpi (integer, intent(inout) ilength, character(len=kchara), intent(inout) field_name)
Definition at line 91 of file field_data_MPI_IO.f90.
References calypso_mpi_char::calypso_mpi_bcast_character(), calypso_mpi_int4::calypso_mpi_bcast_one_int4(), transfer_to_long_integers::cast_long(), and m_precision::kchara.
Referenced by gz_field_data_mpi_io::gz_read_fld_1word_mpi(), and read_field_name_mpi().
sync_field_names_mpi()
subroutine field_data_mpi_io::sync_field_names_mpi (integer(kind=kint), intent(in) num_field, character(len=kchara), dimension(num_field), intent(inout) field_name)
Definition at line 109 of file field_data_MPI_IO.f90.
References calypso_mpi_char::calypso_mpi_bcast_character(), transfer_to_long_integers::cast_long(), and m_precision::kchara.
sync_field_time_mpi()
subroutine field_data_mpi_io::sync_field_time_mpi (type(time_data), intent(inout) t_IO)
Definition at line 56 of file field_data_MPI_IO.f90.
References calypso_mpi_int::calypso_mpi_bcast_one_int(), and calypso_mpi_real::calypso_mpi_bcast_one_real().
Referenced by gz_field_block_mpi_io::read_field_step_gz_mpi(), and read_field_time_mpi().
write_field_name_mpi()
subroutine field_data_mpi_io::write_field_name_mpi (integer, intent(in) id_fld, integer(kind = kint_gl), intent(inout) ioff_gl, character(len=kchara), intent(in) field_name)
Definition at line 126 of file field_data_MPI_IO.f90.
References m_calypso_mpi_io::calypso_mpi_seek_write_head_c(), and field_data_io::each_field_name_buffer().
Referenced by field_block_mpi_io::write_field_data_mpi().