CALYPSO: m_phys_constants Module Reference
m_phys_constants Module Reference
Variables
integer(kind=kint), parameter n_scalar = 1
Number of components for scalar.
integer(kind=kint), parameter n_vector = 3
Number of components for vector.
integer(kind=kint), parameter n_sym_tensor = 6
Number of components for symmetric tensor.
integer(kind=kint), parameter n_asym_tensor = 3
Number of components for asymmetric tensor.
integer(kind=kint), parameter n_solenoid = 2
Number of components for solenoidal field.
integer(kind=kint), dimension(3, 3), parameter l_sim_t = reshape((/0, 1, 2, 1, 3, 4, 2, 4, 5/), shape=(/3,3/))
Component table for symmetric tensor.
integer(kind=kint), dimension(3, 3, 2), parameter l_asim_t = reshape((/0, 0, 2, 0, 0, 1, 2, 1, 0, 0, 1,-1, -1, 0, 1, 1,-1, 0 /), shape=(/3,3,2/))
Component table for asymmetric tensor.
integer(kind=kint), dimension(3), parameter lst_sim_t = (/0, 3, 5/)
Address for diagonal component for symmetric tensor.
Variable Documentation
l_asim_t
integer (kind = kint), dimension(3,3,2), parameter m_phys_constants::l_asim_t = reshape((/0, 0, 2, 0, 0, 1, 2, 1, 0, 0, 1,-1, -1, 0, 1, 1,-1, 0 /), shape=(/3,3,2/))
Component table for asymmetric tensor.
Definition at line 34 of file m_phys_constants.f90.
l_sim_t
integer (kind = kint), dimension(3,3), parameter m_phys_constants::l_sim_t = reshape((/0, 1, 2, 1, 3, 4, 2, 4, 5/), shape=(/3,3/))
Component table for symmetric tensor.
Definition at line 28 of file m_phys_constants.f90.
lst_sim_t
integer (kind = kint), dimension(3), parameter m_phys_constants::lst_sim_t = (/0, 3, 5/)
Address for diagonal component for symmetric tensor.
Definition at line 40 of file m_phys_constants.f90.
n_asym_tensor
integer (kind = kint), parameter m_phys_constants::n_asym_tensor = 3
Number of components for asymmetric tensor.
Definition at line 23 of file m_phys_constants.f90.
n_scalar
integer (kind = kint), parameter m_phys_constants::n_scalar = 1
Number of components for scalar.
Definition at line 17 of file m_phys_constants.f90.
Referenced by cal_rms_by_sph_spectr::cal_rms_sph_spec_one_field(), cal_rms_by_sph_spectr::cal_rms_sph_spec_one_mode(), volume_average_4_sph::cal_sphere_average_sph(), correlation_by_sph_spectr::correlate_sph_spec_one_field(), nod_phys_send_recv::fields_send_recv(), gz_vtk_file_mpi_io::gz_write_vtk_data_mpi(), cal_nonlinear::licv_exp(), hdf5_file_io::parallel_write_hdf5_field_file(), gz_vtk_data_io::read_gz_vtk_each_field_head(), vtk_data_io::read_vtk_each_field_head(), input_control_dynamobench::set_ctl_params_dynamobench(), set_sph_restart_io::set_sph_restart_comp_to_io(), gz_vtk_data_io::write_gz_vtk_each_field_head(), vtk_file_mpi_io::write_vtk_data_mpi(), and vtk_data_io::write_vtk_each_field_head().
n_solenoid
integer (kind = kint), parameter m_phys_constants::n_solenoid = 2
Number of components for solenoidal field.
Definition at line 25 of file m_phys_constants.f90.
n_sym_tensor
integer (kind = kint), parameter m_phys_constants::n_sym_tensor = 6
Number of components for symmetric tensor.
Definition at line 21 of file m_phys_constants.f90.
Referenced by circle_transform_single::circle_transfer_sym_tensor(), parallel_fem_mesh_init::fem_mesh_initialization(), nod_phys_send_recv::fields_send_recv(), gz_vtk_file_mpi_io::gz_write_vtk_data_mpi(), nod_phys_send_recv::init_send_recv(), gz_vtk_data_io::read_gz_vtk_each_field(), gz_vtk_data_io::read_gz_vtk_each_field_head(), vtk_data_io::read_vtk_each_field(), vtk_data_io::read_vtk_each_field_head(), t_field_on_circle::sph_transfer_on_circle(), gz_vtk_data_io::write_gz_vtk_each_field(), gz_vtk_data_io::write_gz_vtk_each_field_head(), vtk_file_mpi_io::write_vtk_data_mpi(), vtk_data_io::write_vtk_each_field(), and vtk_data_io::write_vtk_each_field_head().
n_vector
integer (kind = kint), parameter m_phys_constants::n_vector = 3
Number of components for vector.
Definition at line 19 of file m_phys_constants.f90.
Referenced by cal_rms_by_sph_spectr::cal_rms_sph_spec_one_field(), cal_rms_by_sph_spectr::cal_rms_sph_spec_one_mode(), volume_average_4_sph::cal_sphere_average_sph(), copy_rj_phys_data_4_io::copy_rj_phys_data_to_io(), correlation_by_sph_spectr::correlate_sph_spec_one_field(), nod_phys_send_recv::fields_send_recv(), gz_mpi_node_geometry_io::gz_mpi_read_geometry_info(), gz_mpi_node_geometry_io_b::gz_mpi_read_geometry_info_b(), gz_mpi_node_geometry_io::gz_mpi_read_vect_in_ele(), gz_mpi_node_geometry_io_b::gz_mpi_read_vect_in_ele_b(), gz_mpi_node_geometry_io_b::gz_mpi_write_geometry_info_b(), gz_mpi_node_geometry_io::gz_mpi_write_vect_in_ele(), gz_mpi_node_geometry_io_b::gz_mpi_write_vect_in_ele_b(), gz_node_geometry_io_b::gz_read_vector_in_element_b(), gz_ucd_file_mpi_io::gz_write_ucd_mesh_mpi(), gz_node_geometry_io_b::gz_write_vector_in_element_b(), gz_mpi_viewer_mesh_file_io::gz_write_viewer_mesh_infos(), gz_vtk_file_mpi_io::gz_write_vtk_data_mpi(), cal_nonlinear::licv_exp(), mpi_node_geometry_io::mpi_read_geometry_info(), mpi_node_geometry_io::mpi_read_vect_in_ele(), mpi_node_geometry_io_b::mpi_read_vect_in_ele_b(), mpi_node_geometry_io::mpi_write_vect_in_ele(), mpi_node_geometry_io_b::mpi_write_vect_in_ele_b(), hdf5_file_io::parallel_write_hdf5_field_file(), hdf5_file_io::parallel_write_hdf5_mesh_file(), node_geometry_io_b::read_geometry_info_b(), gz_vtk_data_io::read_gz_vtk_each_field_head(), node_geometry_io_b::read_vector_in_element_b(), vtk_data_io::read_vtk_each_field_head(), input_control_dynamobench::set_ctl_params_dynamobench(), set_sph_restart_io::set_sph_restart_comp_to_io(), t_field_on_circle::sph_transfer_on_circle(), node_geometry_io_b::write_geometry_info_b(), gz_vtk_data_io::write_gz_vtk_each_field(), gz_vtk_data_io::write_gz_vtk_each_field_head(), ucd_file_mpi_io::write_ucd_node_mpi(), node_geometry_io_b::write_vector_in_element_b(), vtk_file_mpi_io::write_vtk_data_mpi(), vtk_data_io::write_vtk_each_field(), vtk_data_io::write_vtk_each_field_head(), and vtk_file_mpi_io::write_vtk_mesh_mpi().