CALYPSO: mpi_sph_gl_1d_idx_io Module Reference
mpi_sph_gl_1d_idx_io Module Reference
Mesh file IO for gxipped format.
Functions/Subroutines
subroutine mpi_read_rtp_gl_1d_table (IO_param, sph_IO)
subroutine mpi_read_rj_gl_1d_table (IO_param, sph_IO)
subroutine mpi_write_rtp_gl_1d_table (IO_param, sph_IO)
subroutine mpi_write_rj_gl_1d_table (IO_param, sph_IO)
subroutine, private mpi_read_1d_gl_address (IO_param, nnod, numdir, idx)
subroutine, private mpi_write_1d_gl_address (IO_param, nnod, numdir, idx)
Detailed Description
Mesh file IO for gxipped format.
      subroutine mpi_read_rtp_gl_1d_table(IO_param, sph_IO)
      subroutine mpi_read_rj_gl_1d_table(IO_param, sph_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(sph_IO_data), intent(inout) :: sph_IO
      subroutine mpi_write_rtp_gl_1d_table(IO_param, sph_IO)
      subroutine mpi_write_rj_gl_1d_table(IO_param, sph_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(sph_IO_data), intent(in) :: sph_IO
Function/Subroutine Documentation
mpi_read_1d_gl_address()
subroutine, private mpi_sph_gl_1d_idx_io::mpi_read_1d_gl_address (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) nnod, integer(kind=kint), intent(in) numdir, integer(kind=kint), dimension(nnod, numdir), intent(inout) idx) private
Definition at line 203 of file MPI_sph_gl_1d_idx_IO.f90.
References m_constants::ione, and mpi_ascii_data_io::mpi_skip_read().
Referenced by mpi_read_rj_gl_1d_table(), and mpi_read_rtp_gl_1d_table().
mpi_read_rj_gl_1d_table()
subroutine mpi_sph_gl_1d_idx_io::mpi_read_rj_gl_1d_table (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(inout) sph_IO)
Definition at line 91 of file MPI_sph_gl_1d_idx_IO.f90.
References t_node_id_spherical_io::alloc_idx_sph_1d1_io(), t_node_id_spherical_io::alloc_idx_sph_1d2_io(), t_node_id_spherical_io::alloc_num_idx_sph_io(), m_sph_modes_grid_labels::hd_jmode(), m_sph_modes_grid_labels::hd_rgrid(), mpi_read_1d_gl_address(), mpi_ascii_data_io::mpi_read_num_of_data(), mpi_position_io::mpi_read_radial_position(), and mpi_ascii_data_io::mpi_skip_read().
Referenced by mpi_sph_modes_data_io::mpi_read_modes_rlm_data(), and mpi_sph_modes_data_io::mpi_read_spectr_rj_data().
mpi_read_rtp_gl_1d_table()
subroutine mpi_sph_gl_1d_idx_io::mpi_read_rtp_gl_1d_table (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(inout) sph_IO)
Definition at line 42 of file MPI_sph_gl_1d_idx_IO.f90.
References t_node_id_spherical_io::alloc_idx_sph_1d1_io(), t_node_id_spherical_io::alloc_idx_sph_1d2_io(), t_node_id_spherical_io::alloc_idx_sph_1d3_io(), t_node_id_spherical_io::alloc_num_idx_sph_io(), m_sph_modes_grid_labels::hd_pgrid(), m_sph_modes_grid_labels::hd_rgrid(), m_sph_modes_grid_labels::hd_tgrid(), mpi_read_1d_gl_address(), mpi_ascii_data_io::mpi_read_num_of_data(), mpi_position_io::mpi_read_radial_position(), and mpi_ascii_data_io::mpi_skip_read().
Referenced by mpi_sph_modes_data_io::mpi_read_geom_rtm_data(), and mpi_sph_modes_data_io::mpi_read_geom_rtp_data().
mpi_write_1d_gl_address()
subroutine, private mpi_sph_gl_1d_idx_io::mpi_write_1d_gl_address (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) nnod, integer(kind=kint), intent(in) numdir, integer(kind=kint), dimension(nnod, numdir), intent(in) idx) private
Definition at line 257 of file MPI_sph_gl_1d_idx_IO.f90.
References m_constants::ione, mpi_ascii_data_io::mpi_write_num_of_data(), and mpi_ascii_data_io::mpi_write_stack_over_domain().
Referenced by mpi_write_rj_gl_1d_table(), and mpi_write_rtp_gl_1d_table().
mpi_write_rj_gl_1d_table()
subroutine mpi_sph_gl_1d_idx_io::mpi_write_rj_gl_1d_table (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(in) sph_IO)
Definition at line 171 of file MPI_sph_gl_1d_idx_IO.f90.
References m_sph_modes_grid_labels::hd_jmode(), m_sph_modes_grid_labels::hd_rgrid(), mpi_write_1d_gl_address(), mpi_ascii_data_io::mpi_write_charahead(), mpi_ascii_data_io::mpi_write_num_of_data(), and mpi_position_io::mpi_write_radial_position().
Referenced by mpi_sph_modes_data_io::mpi_write_modes_rlm_data(), and mpi_sph_modes_data_io::mpi_write_spectr_rj_data().
mpi_write_rtp_gl_1d_table()
subroutine mpi_sph_gl_1d_idx_io::mpi_write_rtp_gl_1d_table (type(calypso_mpi_io_params), intent(inout) IO_param, type(sph_io_data), intent(in) sph_IO)
Definition at line 129 of file MPI_sph_gl_1d_idx_IO.f90.
References m_sph_modes_grid_labels::hd_pgrid(), m_sph_modes_grid_labels::hd_rgrid(), m_sph_modes_grid_labels::hd_tgrid(), mpi_write_1d_gl_address(), mpi_ascii_data_io::mpi_write_charahead(), mpi_ascii_data_io::mpi_write_num_of_data(), and mpi_position_io::mpi_write_radial_position().
Referenced by mpi_sph_modes_data_io::mpi_write_geom_rtm_data(), and mpi_sph_modes_data_io::mpi_write_geom_rtp_data().