CALYPSO: t_no_heat_nusselt Module Reference
t_no_heat_nusselt Module Reference
Data arrays for Nusselt number.
Data Types
type nusselt_number_data
Structure for Nusselt number data.
Functions/Subroutines
subroutine, private open_no_heat_source_nu (Nu_type)
subroutine write_no_heat_source_nu (idx_rj_degree_zero, i_step, time, Nu_type)
subroutine open_read_no_heat_source_nu (id_pick, Nu_type)
subroutine read_no_heat_source_nu (id_pick, i_step, time, Nu_type, ierr)
Variables
integer(kind=kint), parameter, private id_nusselt = 23
File ID for Nusselt number IO.
Detailed Description
Data arrays for Nusselt number.
      subroutine write_no_heat_source_Nu(idx_rj_degree_zero,          &
     &          i_step, time, Nu_type)
      subroutine open_read_no_heat_source_Nu(id_pick, Nu_type)
      subroutine read_no_heat_source_Nu                               &
     &         (id_pick, i_step, time, Nu_type, ierr)
Function/Subroutine Documentation
open_no_heat_source_nu()
subroutine, private t_no_heat_nusselt::open_no_heat_source_nu (type(nusselt_number_data), intent(in) Nu_type) private
Definition at line 55 of file t_no_heat_Nusselt.f90.
References set_parallel_file_name::add_dat_extension(), and id_nusselt.
Referenced by write_no_heat_source_nu().
open_read_no_heat_source_nu()
subroutine t_no_heat_nusselt::open_read_no_heat_source_nu (integer(kind = kint), intent(in) id_pick, type(nusselt_number_data), intent(inout) Nu_type)
Definition at line 109 of file t_no_heat_Nusselt.f90.
References set_parallel_file_name::add_dat_extension(), and skip_comment_f::skip_comment().
Referenced by t_average_nusselt().
read_no_heat_source_nu()
subroutine t_no_heat_nusselt::read_no_heat_source_nu (integer(kind = kint), intent(in) id_pick, integer(kind = kint), intent(inout) i_step, real(kind = kreal), intent(inout) time, type(nusselt_number_data), intent(inout) Nu_type, integer(kind = kint), intent(inout) ierr)
Definition at line 135 of file t_no_heat_Nusselt.f90.
Referenced by t_average_nusselt().
write_no_heat_source_nu()
subroutine t_no_heat_nusselt::write_no_heat_source_nu (integer(kind = kint), intent(in) idx_rj_degree_zero, integer(kind = kint), intent(in) i_step, real(kind = kreal), intent(in) time, type(nusselt_number_data), intent(in) Nu_type)
Definition at line 86 of file t_no_heat_Nusselt.f90.
References id_nusselt, m_constants::izero, and open_no_heat_source_nu().
Referenced by cal_write_sph_monitor_data::cal_write_no_heat_sourse_nu(), and cal_write_sph_monitor_data::output_sph_monitor_data().
Variable Documentation
id_nusselt
integer(kind = kint), parameter, private t_no_heat_nusselt::id_nusselt = 23 private
File ID for Nusselt number IO.
Definition at line 27 of file t_no_heat_Nusselt.f90.
Referenced by open_no_heat_source_nu(), and write_no_heat_source_nu().