CALYPSO: copy_spectr_4_sph_trans Module Reference
copy_spectr_4_sph_trans Module Reference
Copy data from/to sphrical transform buffer and local array for center.
Functions/Subroutines
subroutine sel_sph_rj_scalar_2_send_wpole (ncomp_send, i_field, i_send, nnod_pole, sph_rj, comm_rj, rj_fld, n_WS, WS, v_pl_local)
subroutine sel_sph_rj_scalar_to_send (ncomp_send, i_field, i_send, comm_rj, rj_fld, n_WS, WS)
subroutine sel_sph_rj_vector_to_send (ncomp_send, i_field, i_send, comm_rj, rj_fld, n_WS, WS)
subroutine sel_sph_rj_tensor_to_send (ncomp_send, i_field, i_send, comm_rj, rj_fld, n_WS, WS)
subroutine sel_sph_rj_scalar_from_recv (iflag_recv, ncomp_recv, i_field, i_recv, comm_rj, n_WR, WR, rj_fld)
subroutine sel_sph_rj_vector_from_recv (iflag_recv, ncomp_recv, i_field, i_recv, comm_rj, n_WR, WR, rj_fld)
subroutine sel_sph_rj_tensor_from_recv (iflag_recv, ncomp_recv, i_field, i_recv, comm_rj, n_WR, WR, rj_fld)
Detailed Description
Copy data from/to sphrical transform buffer and local array for center.
      subroutine sel_sph_rj_scalar_2_send_wpole                       &
     &         (ncomp_send, i_field, i_send, nnod_pole,               &
     &          sph_rj, comm_rj, rj_fld, n_WS, WS, v_pl_local)
        type(sph_rj_grid), intent(in) ::  sph_rj
      subroutine sel_sph_rj_scalar_to_send                            &
     &         (ncomp_send, i_field, i_send, comm_rj, rj_fld,         &
     &          n_WS, WS)
      subroutine sel_sph_rj_vector_to_send                            &
     &         (ncomp_send, i_field, i_send, comm_rj, rj_fld,         &
     &          n_WS, WS)
      subroutine sel_sph_rj_tensor_to_send                            &
     &         (ncomp_send, i_field, i_send, comm_rj, rj_fld,         &
     &          n_WS, WS)
        type(phys_data), intent(in) :: rj_fld
      subroutine sel_sph_rj_scalar_from_recv                          &
     &         (iflag_recv, ncomp_recv, i_field, i_recv, comm_rj,     &
     &          n_WR, WR, rj_fld)
      subroutine sel_sph_rj_vector_from_recv                          &
     &         (iflag_recv, ncomp_recv, i_field, i_recv, comm_rj,     &
     &          n_WR, WR, rj_fld)
      subroutine sel_sph_rj_tensor_from_recv                          &
     &         (iflag_recv, ncomp_recv, i_field, i_recv, comm_rj,     &
     &          n_WR, WR, rj_fld)
        type(sph_comm_tbl), intent(in) :: comm_rj
        type(phys_data), intent(inout) :: rj_fld
Function/Subroutine Documentation
sel_sph_rj_scalar_2_send_wpole()
subroutine copy_spectr_4_sph_trans::sel_sph_rj_scalar_2_send_wpole (integer(kind = kint), intent(in) ncomp_send, integer(kind = kint), intent(in) i_field, integer(kind = kint), intent(in) i_send, integer(kind = kint), intent(in) nnod_pole, type(sph_rj_grid), intent(in) sph_rj, type(sph_comm_tbl), intent(in) comm_rj, type(phys_data), intent(in) rj_fld, integer(kind = kint), intent(in) n_WS, real(kind = kreal), dimension(n_ws), intent(inout) WS, real(kind = kreal), dimension(nnod_pole,ncomp_send), intent(inout) v_pl_local)
Definition at line 56 of file copy_spectr_4_sph_trans.f90.
References sel_spherical_srs::sel_calypso_to_send_scalar().
Referenced by set_address_sph_trans_mhd::mhd_spectr_to_sendbuf_wpole().
sel_sph_rj_scalar_from_recv()
subroutine copy_spectr_4_sph_trans::sel_sph_rj_scalar_from_recv (integer(kind = kint), intent(in) iflag_recv, integer(kind = kint), intent(in) ncomp_recv, integer(kind = kint), intent(in) i_field, integer(kind = kint), intent(in) i_recv, type(sph_comm_tbl), intent(in) comm_rj, integer(kind = kint), intent(in) n_WR, real(kind = kreal), dimension(n_wr), intent(inout) WR, type(phys_data), intent(inout) rj_fld)
Definition at line 165 of file copy_spectr_4_sph_trans.f90.
References sel_spherical_srs::sel_sph_scalar_from_recv().
Referenced by set_address_sph_trans_mhd::mhd_spectr_from_recvbuf().
sel_sph_rj_scalar_to_send()
subroutine copy_spectr_4_sph_trans::sel_sph_rj_scalar_to_send (integer(kind = kint), intent(in) ncomp_send, integer(kind = kint), intent(in) i_field, integer(kind = kint), intent(in) i_send, type(sph_comm_tbl), intent(in) comm_rj, type(phys_data), intent(in) rj_fld, integer(kind = kint), intent(in) n_WS, real(kind = kreal), dimension(n_ws), intent(inout) WS)
Definition at line 95 of file copy_spectr_4_sph_trans.f90.
References sel_spherical_srs::sel_calypso_to_send_scalar().
Referenced by set_address_sph_trans_mhd::mhd_spectr_to_sendbuf().
sel_sph_rj_tensor_from_recv()
subroutine copy_spectr_4_sph_trans::sel_sph_rj_tensor_from_recv (integer(kind = kint), intent(in) iflag_recv, integer(kind = kint), intent(in) ncomp_recv, integer(kind = kint), intent(in) i_field, integer(kind = kint), intent(in) i_recv, type(sph_comm_tbl), intent(in) comm_rj, integer(kind = kint), intent(in) n_WR, real(kind = kreal), dimension(n_wr), intent(inout) WR, type(phys_data), intent(inout) rj_fld)
Definition at line 217 of file copy_spectr_4_sph_trans.f90.
References sel_spherical_srs::sel_sph_tensor_from_recv().
sel_sph_rj_tensor_to_send()
subroutine copy_spectr_4_sph_trans::sel_sph_rj_tensor_to_send (integer(kind = kint), intent(in) ncomp_send, integer(kind = kint), intent(in) i_field, integer(kind = kint), intent(in) i_send, type(sph_comm_tbl), intent(in) comm_rj, type(phys_data), intent(in) rj_fld, integer(kind = kint), intent(in) n_WS, real(kind = kreal), dimension(n_ws), intent(inout) WS)
Definition at line 141 of file copy_spectr_4_sph_trans.f90.
References sel_spherical_srs::sel_calypso_to_send_tensor().
sel_sph_rj_vector_from_recv()
subroutine copy_spectr_4_sph_trans::sel_sph_rj_vector_from_recv (integer(kind = kint), intent(in) iflag_recv, integer(kind = kint), intent(in) ncomp_recv, integer(kind = kint), intent(in) i_field, integer(kind = kint), intent(in) i_recv, type(sph_comm_tbl), intent(in) comm_rj, integer(kind = kint), intent(in) n_WR, real(kind = kreal), dimension(n_wr), intent(inout) WR, type(phys_data), intent(inout) rj_fld)
Definition at line 191 of file copy_spectr_4_sph_trans.f90.
References sel_spherical_srs::sel_sph_vector_from_recv().
Referenced by set_address_sph_trans_mhd::mhd_spectr_from_recvbuf().
sel_sph_rj_vector_to_send()
subroutine copy_spectr_4_sph_trans::sel_sph_rj_vector_to_send (integer(kind = kint), intent(in) ncomp_send, integer(kind = kint), intent(in) i_field, integer(kind = kint), intent(in) i_send, type(sph_comm_tbl), intent(in) comm_rj, type(phys_data), intent(in) rj_fld, integer(kind = kint), intent(in) n_WS, real(kind = kreal), dimension(n_ws), intent(inout) WS)
Definition at line 118 of file copy_spectr_4_sph_trans.f90.
References sel_spherical_srs::sel_calypso_to_send_vector().
Referenced by set_address_sph_trans_mhd::mhd_spectr_to_sendbuf(), and set_address_sph_trans_mhd::mhd_spectr_to_sendbuf_wpole().