CALYPSO: gz_read_udt_from_bin_data Module Reference
gz_read_udt_from_bin_data Module Reference
read binary section file
Functions/Subroutines
subroutine gz_read_psf_bin_time_data (nprocs, i_time_step_IO, time_IO, delta_t_IO, zbuf)
subroutine gz_read_psf_bin_field_data (nprocs, ucd_z, zbuf, itmp1_mp)
subroutine gz_read_alloc_psf_bin_fld_data (nprocs, ucd_z, zbuf, itmp1_mp)
subroutine gz_read_psf_bin_grid_data (nprocs, ucd_z, zbuf, itmp1_mp)
subroutine gz_read_alloc_psf_bin_grid_data (nprocs, ucd_z, zbuf, itmp1_mp)
Detailed Description
read binary section file
      subroutine gz_read_psf_bin_time_data                           &
     &         (nprocs, i_time_step_IO, time_IO, delta_t_IO, zbuf)
      subroutine gz_read_psf_bin_field_data                           &
     &         (nprocs, ucd_z, zbuf, itmp1_mp)
      subroutine gz_read_alloc_psf_bin_fld_data                       &
     &         (nprocs, ucd_z, zbuf, itmp1_mp)
      subroutine gz_read_psf_bin_grid_data                            &
     &         (nprocs, ucd_z, zbuf, itmp1_mp)
      subroutine gz_read_alloc_psf_bin_grid_data                      &
        type(ucd_data), intent(inout) :: ucd_z
        type(binary_IO_buffer), intent(inout) :: zbuf
Function/Subroutine Documentation
gz_read_alloc_psf_bin_fld_data()
subroutine gz_read_udt_from_bin_data::gz_read_alloc_psf_bin_fld_data (integer, intent(in) nprocs, type(ucd_data), intent(inout) ucd_z, type(buffer_4_gzip), intent(inout) zbuf, integer(kind = kint_gl), dimension(nprocs), intent(inout) itmp1_mp)
Definition at line 100 of file gz_read_udt_from_bin_data.f90.
References t_ucd_data::allocate_ucd_phys_data(), t_ucd_data::allocate_ucd_phys_name(), gz_read_psf_binary_data::read_psf_phys_data_bin_gz(), gz_read_psf_binary_data::read_psf_phys_name_bin_gz(), and gz_read_psf_binary_data::read_psf_phys_num_bin_gz().
Referenced by gz_read_psf_binary_file::gz_read_alloc_iso_bin_file(), and gz_read_psf_binary_file::gz_read_alloc_psf_bin_file().
gz_read_alloc_psf_bin_grid_data()
subroutine gz_read_udt_from_bin_data::gz_read_alloc_psf_bin_grid_data (integer, intent(inout) nprocs, type(ucd_data), intent(inout) ucd_z, type(buffer_4_gzip), intent(inout) zbuf, integer(kind = kint_gl), dimension(nprocs), intent(inout) itmp1_mp)
Definition at line 168 of file gz_read_udt_from_bin_data.f90.
References t_ucd_data::allocate_ucd_ele(), t_ucd_data::allocate_ucd_node(), gz_read_psf_binary_data::read_psf_ele_connect_bin_gz(), gz_read_psf_binary_data::read_psf_ele_num_bin_gz(), gz_read_psf_binary_data::read_psf_node_data_bin_gz(), and gz_read_psf_binary_data::read_psf_node_num_bin_gz().
Referenced by gz_read_psf_binary_file::gz_read_alloc_iso_bin_file(), and gz_read_psf_binary_file::gz_read_alloc_psf_bin_grid().
gz_read_psf_bin_field_data()
subroutine gz_read_udt_from_bin_data::gz_read_psf_bin_field_data (integer, intent(in) nprocs, type(ucd_data), intent(inout) ucd_z, type(buffer_4_gzip), intent(inout) zbuf, integer(kind = kint_gl), dimension(nprocs), intent(inout) itmp1_mp)
Definition at line 66 of file gz_read_udt_from_bin_data.f90.
References gz_read_psf_binary_data::read_psf_phys_data_bin_gz(), gz_read_psf_binary_data::read_psf_phys_name_bin_gz(), and gz_read_psf_binary_data::read_psf_phys_num_bin_gz().
Referenced by gz_read_psf_binary_file::gz_read_iso_bin_file(), and gz_read_psf_binary_file::gz_read_psf_bin_file().
gz_read_psf_bin_grid_data()
subroutine gz_read_udt_from_bin_data::gz_read_psf_bin_grid_data (integer, intent(inout) nprocs, type(ucd_data), intent(inout) ucd_z, type(buffer_4_gzip), intent(inout) zbuf, integer(kind = kint_gl), dimension(nprocs), intent(inout) itmp1_mp)
Definition at line 131 of file gz_read_udt_from_bin_data.f90.
References gz_read_psf_binary_data::read_psf_ele_connect_bin_gz(), gz_read_psf_binary_data::read_psf_ele_num_bin_gz(), gz_read_psf_binary_data::read_psf_node_data_bin_gz(), and gz_read_psf_binary_data::read_psf_node_num_bin_gz().
Referenced by gz_read_psf_binary_file::gz_read_iso_bin_file(), and gz_read_psf_binary_file::gz_read_psf_bin_grid().
gz_read_psf_bin_time_data()
subroutine gz_read_udt_from_bin_data::gz_read_psf_bin_time_data (integer, intent(in) nprocs, integer(kind=kint), intent(inout) i_time_step_IO, real(kind = kreal), intent(inout) time_IO, real(kind = kreal), intent(inout) delta_t_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 40 of file gz_read_udt_from_bin_data.f90.
References gz_binary_io::gz_read_one_integer_b(), and gz_binary_io::gz_read_one_real_b().
Referenced by gz_read_psf_binary_file::gz_read_alloc_iso_bin_file(), gz_read_psf_binary_file::gz_read_alloc_psf_bin_file(), gz_read_psf_binary_file::gz_read_iso_bin_file(), and gz_read_psf_binary_file::gz_read_psf_bin_file().