CALYPSO: gz_read_psf_binary_file Module Reference
gz_read_psf_binary_file Module Reference
read gzipped binary section file
Functions/Subroutines
subroutine gz_read_alloc_psf_bin_grid (gzip_name, nprocs, ucd_z)
subroutine gz_read_alloc_psf_bin_file (gzip_name, nprocs, t_IO, ucd_z)
subroutine gz_read_alloc_iso_bin_file (gzip_name, t_IO, ucd_z)
subroutine gz_read_psf_bin_grid (gzip_name, nprocs, ucd_z)
subroutine gz_read_psf_bin_file (gzip_name, nprocs, t_IO, ucd_z)
subroutine gz_read_iso_bin_file (gzip_name, t_IO, ucd_z)
Variables
type(buffer_4_gzip), save, private zbuf_ucd
integer(kind=kint_gl), dimension(:), allocatable, private itmp1_mp
Detailed Description
read gzipped binary section file
      subroutine gz_read_alloc_psf_bin_grid(gzip_name, nprocs, ucd_z)
      subroutine gz_read_alloc_psf_bin_file                           &
     &         (gzip_name, nprocs, t_IO, ucd_z)
      subroutine gz_read_alloc_iso_bin_file(gzip_name, t_IO, ucd_z)
        character(len = kchara), intent(in) :: gzip_name
        type(ucd_data), intent(inout) :: ucd_z
      subroutine gz_read_psf_bin_grid(gzip_name, nprocs, ucd_z)
      subroutine gz_read_psf_bin_file(gzip_name, nprocs, t_IO, ucd_z)
      subroutine gz_read_iso_bin_file(gzip_name, t_IO, ucd_z)
        character(len = kchara), intent(in) :: gzip_name
        type(ucd_data), intent(inout) :: ucd_z
Function/Subroutine Documentation
gz_read_alloc_iso_bin_file()
subroutine gz_read_psf_binary_file::gz_read_alloc_iso_bin_file (character(len = kchara), intent(in) gzip_name, type(time_data), intent(inout) t_IO, type(ucd_data), intent(inout) ucd_z)
Definition at line 96 of file gz_read_psf_binary_file.f90.
References gzip_file_access::close_gzfile_b(), gz_read_udt_from_bin_data::gz_read_alloc_psf_bin_fld_data(), gz_read_udt_from_bin_data::gz_read_alloc_psf_bin_grid_data(), gz_binary_io::gz_read_one_integer_b(), gz_read_udt_from_bin_data::gz_read_psf_bin_time_data(), itmp1_mp, m_constants::izero, gz_binary_io::open_rd_gzfile_b(), and zbuf_ucd.
Referenced by ucd_io_select::sel_read_alloc_ucd_file().
gz_read_alloc_psf_bin_file()
subroutine gz_read_psf_binary_file::gz_read_alloc_psf_bin_file (character(len = kchara), intent(in) gzip_name, integer, intent(in) nprocs, type(time_data), intent(inout) t_IO, type(ucd_data), intent(inout) ucd_z)
Definition at line 69 of file gz_read_psf_binary_file.f90.
References gzip_file_access::close_gzfile_b(), gz_read_udt_from_bin_data::gz_read_alloc_psf_bin_fld_data(), gz_read_udt_from_bin_data::gz_read_psf_bin_time_data(), itmp1_mp, m_constants::izero, gz_binary_io::open_rd_gzfile_b(), and zbuf_ucd.
Referenced by ucd_io_select::sel_read_alloc_ucd_file(), ucd_io_select::sel_read_alloc_udt_file(), and ucd_io_select::sel_read_udt_param().
gz_read_alloc_psf_bin_grid()
subroutine gz_read_psf_binary_file::gz_read_alloc_psf_bin_grid (character(len = kchara), intent(in) gzip_name, integer, intent(inout) nprocs, type(ucd_data), intent(inout) ucd_z)
Definition at line 45 of file gz_read_psf_binary_file.f90.
References gzip_file_access::close_gzfile_b(), gz_read_udt_from_bin_data::gz_read_alloc_psf_bin_grid_data(), gz_binary_io::gz_read_one_integer_b(), itmp1_mp, m_constants::izero, gz_binary_io::open_rd_gzfile_b(), and zbuf_ucd.
Referenced by ucd_io_select::sel_read_alloc_ucd_file().
gz_read_iso_bin_file()
subroutine gz_read_psf_binary_file::gz_read_iso_bin_file (character(len = kchara), intent(in) gzip_name, type(time_data), intent(inout) t_IO, type(ucd_data), intent(inout) ucd_z)
Definition at line 177 of file gz_read_psf_binary_file.f90.
References gzip_file_access::close_gzfile_b(), gz_binary_io::gz_read_one_integer_b(), gz_read_udt_from_bin_data::gz_read_psf_bin_field_data(), gz_read_udt_from_bin_data::gz_read_psf_bin_grid_data(), gz_read_udt_from_bin_data::gz_read_psf_bin_time_data(), itmp1_mp, m_constants::izero, gz_binary_io::open_rd_gzfile_b(), and zbuf_ucd.
Referenced by ucd_io_select::sel_read_ucd_file().
gz_read_psf_bin_file()
subroutine gz_read_psf_binary_file::gz_read_psf_bin_file (character(len = kchara), intent(in) gzip_name, integer, intent(in) nprocs, type(time_data), intent(inout) t_IO, type(ucd_data), intent(inout) ucd_z)
Definition at line 151 of file gz_read_psf_binary_file.f90.
References gzip_file_access::close_gzfile_b(), gz_read_udt_from_bin_data::gz_read_psf_bin_field_data(), gz_read_udt_from_bin_data::gz_read_psf_bin_time_data(), itmp1_mp, m_constants::izero, gz_binary_io::open_rd_gzfile_b(), and zbuf_ucd.
Referenced by ucd_io_select::sel_read_ucd_file(), and ucd_io_select::sel_read_udt_file().
gz_read_psf_bin_grid()
subroutine gz_read_psf_binary_file::gz_read_psf_bin_grid (character(len = kchara), intent(in) gzip_name, integer, intent(inout) nprocs, type(ucd_data), intent(inout) ucd_z)
Definition at line 128 of file gz_read_psf_binary_file.f90.
References gzip_file_access::close_gzfile_b(), gz_binary_io::gz_read_one_integer_b(), gz_read_udt_from_bin_data::gz_read_psf_bin_grid_data(), itmp1_mp, m_constants::izero, gz_binary_io::open_rd_gzfile_b(), and zbuf_ucd.
Referenced by ucd_io_select::sel_read_ucd_file().
Variable Documentation
itmp1_mp
integer(kind = kint_gl), dimension(:), allocatable, private gz_read_psf_binary_file::itmp1_mp private
Definition at line 37 of file gz_read_psf_binary_file.f90.
Referenced by gz_read_alloc_iso_bin_file(), gz_read_alloc_psf_bin_file(), gz_read_alloc_psf_bin_grid(), gz_read_iso_bin_file(), gz_read_psf_bin_file(), and gz_read_psf_bin_grid().
zbuf_ucd
type(buffer_4_gzip), save, private gz_read_psf_binary_file::zbuf_ucd private
Definition at line 36 of file gz_read_psf_binary_file.f90.
Referenced by gz_read_alloc_iso_bin_file(), gz_read_alloc_psf_bin_file(), gz_read_alloc_psf_bin_grid(), gz_read_iso_bin_file(), gz_read_psf_bin_file(), and gz_read_psf_bin_grid().