CALYPSO: set_comm_table_rtp_fftpack Module Reference
set_comm_table_rtp_fftpack Module Reference
communication table from FFTPACK5
Functions/Subroutines
subroutine set_comm_item_rtp_4_fftpack (nnod_rtp, nidx_rtp, irt_rtp_smp_stack, ntot_sr_rtp, irev_sr_rtp, comm_sph_FFT)
subroutine copy_fftpack_field_to_send (nnod_rtp, nidx_rtp, irt_rtp_smp_stack, ncomp_fwd, irev_sr_rtp, X_FFT, n_WS, WS)
subroutine copy_rtp_comp_fftpack_to_send (nd, nnod_rtp, nidx_rtp, irt_rtp_smp_stack, ncomp_fwd, irev_sr_rtp, X_FFT, n_WS, WS)
subroutine copy_fftpack_field_from_recv (nnod_rtp, nidx_rtp, irt_rtp_smp_stack, ncomp_bwd, irev_sr_rtp, n_WR, WR, X_FFT)
subroutine copy_fftpack_comp_from_recv (nd, nnod_rtp, nidx_rtp, irt_rtp_smp_stack, ncomp_bwd, irev_sr_rtp, n_WR, WR, X_FFT)
Detailed Description
communication table from FFTPACK5
      subroutine set_comm_item_rtp_4_FFTPACK                          &
     &         (nnod_rtp, nidx_rtp, irt_rtp_smp_stack,                &
     &          ntot_sr_rtp, irev_sr_rtp, comm_sph_FFT)
      subroutine copy_FFTPACK_field_to_send(nnod_rtp, nidx_rtp,       &
     &          irt_rtp_smp_stack, ncomp_fwd, irev_sr_rtp, X_FFT,     &
     &          n_WS, WS)
      subroutine copy_rtp_comp_FFTPACK_to_send(nd, nnod_rtp, nidx_rtp,&
     &          irt_rtp_smp_stack, ncomp_fwd, irev_sr_rtp, X_FFT,     &
     &          n_WS, WS)
      subroutine copy_FFTPACK_field_from_recv(nnod_rtp, nidx_rtp,     &
     &          irt_rtp_smp_stack, ncomp_bwd, irev_sr_rtp,            &
     &          n_WR, WR, X_FFT)
      subroutine copy_FFTPACK_comp_from_recv(nd, nnod_rtp, nidx_rtp,  &
     &          irt_rtp_smp_stack, ncomp_bwd, irev_sr_rtp,            &
     &          n_WR, WR, X_FFT)
        type(comm_tbl_from_FFT), intent(inout) :: comm_sph_FFT
Function/Subroutine Documentation
copy_fftpack_comp_from_recv()
subroutine set_comm_table_rtp_fftpack::copy_fftpack_comp_from_recv (integer(kind = kint), intent(in) nd, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(3), intent(in) nidx_rtp, integer(kind = kint), dimension(0:np_smp), intent(in) irt_rtp_smp_stack, integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), dimension(nnod_rtp), intent(in) irev_sr_rtp, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(inout) WR, real(kind = kreal), dimension(nnod_rtp), intent(inout) X_FFT)
Definition at line 294 of file set_comm_table_rtp_FFTPACK.f90.
Referenced by sph_rtp_domain_fftpack5::rtp_domain_rfftmb_from_recv().
copy_fftpack_field_from_recv()
subroutine set_comm_table_rtp_fftpack::copy_fftpack_field_from_recv (integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(3), intent(in) nidx_rtp, integer(kind = kint), dimension(0:np_smp), intent(in) irt_rtp_smp_stack, integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), dimension(nnod_rtp), intent(in) irev_sr_rtp, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(inout) WR, real(kind = kreal), dimension(ncomp_bwd*nnod_rtp), intent(inout) X_FFT)
Definition at line 232 of file set_comm_table_rtp_FFTPACK.f90.
Referenced by sph_rtp_fftpack5::rtp_rfftmb_from_recv().
copy_fftpack_field_to_send()
subroutine set_comm_table_rtp_fftpack::copy_fftpack_field_to_send (integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(3), intent(in) nidx_rtp, integer(kind = kint), dimension(0:np_smp), intent(in) irt_rtp_smp_stack, integer(kind = kint), intent(in) ncomp_fwd, integer(kind = kint), dimension(nnod_rtp), intent(in) irev_sr_rtp, real(kind = kreal), dimension(ncomp_fwd*nnod_rtp), intent(in) X_FFT, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 114 of file set_comm_table_rtp_FFTPACK.f90.
copy_rtp_comp_fftpack_to_send()
subroutine set_comm_table_rtp_fftpack::copy_rtp_comp_fftpack_to_send (integer(kind = kint), intent(in) nd, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(3), intent(in) nidx_rtp, integer(kind = kint), dimension(0:np_smp), intent(in) irt_rtp_smp_stack, integer(kind = kint), intent(in) ncomp_fwd, integer(kind = kint), dimension(nnod_rtp), intent(in) irev_sr_rtp, real(kind = kreal), dimension(ncomp_fwd*nnod_rtp), intent(in) X_FFT, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 175 of file set_comm_table_rtp_FFTPACK.f90.
set_comm_item_rtp_4_fftpack()
subroutine set_comm_table_rtp_fftpack::set_comm_item_rtp_4_fftpack (integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(3), intent(in) nidx_rtp, integer(kind = kint), dimension(0:np_smp), intent(in) irt_rtp_smp_stack, integer(kind = kint), intent(in) ntot_sr_rtp, integer(kind = kint), dimension(nnod_rtp), intent(in) irev_sr_rtp, type(comm_tbl_from_fft), intent(inout) comm_sph_FFT)
Definition at line 44 of file set_comm_table_rtp_FFTPACK.f90.
References m_constants::one.
Referenced by sph_rtp_domain_fftpack5::init_rtp_domain_fftpack5(), sph_rtp_fftpack5::init_rtp_fftpack5(), sph_rtp_domain_fftpack5::verify_rtp_domain_fftpack5(), and sph_rtp_fftpack5::verify_rtp_fftpack5().