CALYPSO: mesh_io_select Module Reference
mesh_io_select Module Reference
Choose mesh file to read.
Functions/Subroutines
subroutine sel_read_mesh (mesh_file, id_rank, mesh_IO, group_IO, ierr)
subroutine sel_read_mesh_geometry (mesh_file, id_rank, mesh_IO, ierr)
subroutine sel_read_node_size (mesh_file, id_rank, mesh_IO, ierr)
subroutine sel_read_geometry_size (mesh_file, id_rank, mesh_IO, ierr)
subroutine sel_write_mesh_file (mesh_file, id_rank, mesh_IO, group_IO)
Variables
character(len=kchara), private file_name
Detailed Description
Choose mesh file to read.
      subroutine sel_read_mesh                                        &
     &         (mesh_file, id_rank, mesh_IO, group_IO, ierr)
        type(mesh_geometry), intent(inout) :: mesh_IO
        type(mesh_groups), intent(inout) ::   group_IO
      subroutine sel_read_mesh_geometry                               &
     &         (mesh_file, id_rank, mesh_IO, ierr)
      subroutine sel_read_node_size                                   &
     &         (mesh_file, id_rank, mesh_IO, ierr)
      subroutine sel_read_geometry_size                               &
     &         (mesh_file, id_rank, mesh_IO, ierr)
        type(mesh_geometry), intent(inout) :: mesh_IO
      subroutine sel_write_mesh_file                                  &
     &         (mesh_file, id_rank, mesh_IO, group_IO)
        type(mesh_geometry), intent(in) :: mesh_IO
        type(mesh_groups), intent(in) ::   group_IO
Function/Subroutine Documentation
sel_read_geometry_size()
subroutine mesh_io_select::sel_read_geometry_size (type(field_io_params), intent(in) mesh_file, integer, intent(in) id_rank, type(mesh_geometry), intent(inout) mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 159 of file mesh_IO_select.F90.
References file_name, gz_mesh_file_io::gz_read_geometry_size(), gz_mesh_file_io_b::gz_read_geometry_size_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, mesh_file_io::read_geometry_size(), mesh_file_io_b::read_geometry_size_b(), and set_mesh_file_names::set_mesh_file_name().
Referenced by mesh_mpi_io_select::sel_mpi_read_geometry_size().
sel_read_mesh()
subroutine mesh_io_select::sel_read_mesh (type(field_io_params), intent(in) mesh_file, integer, intent(in) id_rank, type(mesh_geometry), intent(inout) mesh_IO, type(mesh_groups), intent(inout) group_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 53 of file mesh_IO_select.F90.
References file_name, gz_mesh_file_io::gz_read_mesh(), gz_mesh_file_io_b::gz_read_mesh_file_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, mesh_file_io::read_mesh_file(), mesh_file_io_b::read_mesh_file_b(), and set_mesh_file_names::set_mesh_file_name().
Referenced by load_mesh_data::input_mesh(), and mesh_mpi_io_select::sel_mpi_read_mesh().
sel_read_mesh_geometry()
subroutine mesh_io_select::sel_read_mesh_geometry (type(field_io_params), intent(in) mesh_file, integer, intent(in) id_rank, type(mesh_geometry), intent(inout) mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 90 of file mesh_IO_select.F90.
References file_name, gz_mesh_file_io::gz_read_mesh_geometry(), gz_mesh_file_io_b::gz_read_mesh_geometry_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, mesh_file_io::read_mesh_geometry(), mesh_file_io_b::read_mesh_geometry_b(), and set_mesh_file_names::set_mesh_file_name().
Referenced by load_mesh_data::input_mesh_geometry(), and mesh_mpi_io_select::sel_mpi_read_mesh_geometry().
sel_read_node_size()
subroutine mesh_io_select::sel_read_node_size (type(field_io_params), intent(in) mesh_file, integer, intent(in) id_rank, type(mesh_geometry), intent(inout) mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 125 of file mesh_IO_select.F90.
References file_name, gz_mesh_file_io::gz_read_node_size(), gz_mesh_file_io_b::gz_read_node_size_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, mesh_file_io::read_node_size(), mesh_file_io_b::read_node_size_b(), and set_mesh_file_names::set_mesh_file_name().
Referenced by mesh_mpi_io_select::sel_mpi_read_node_size().
sel_write_mesh_file()
subroutine mesh_io_select::sel_write_mesh_file (type(field_io_params), intent(in) mesh_file, integer, intent(in) id_rank, type(mesh_geometry), intent(in) mesh_IO, type(mesh_groups), intent(in) group_IO)
Definition at line 195 of file mesh_IO_select.F90.
References file_name, gz_mesh_file_io::gz_write_mesh_file(), gz_mesh_file_io_b::gz_write_mesh_file_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, set_mesh_file_names::set_mesh_file_name(), mesh_file_io::write_mesh_file(), and mesh_file_io_b::write_mesh_file_b().
Referenced by load_mesh_data::output_mesh(), and mesh_mpi_io_select::sel_mpi_write_mesh_file().
Variable Documentation
file_name
character(len=kchara), private mesh_io_select::file_name private
Definition at line 45 of file mesh_IO_select.F90.
Referenced by sel_read_geometry_size(), sel_read_mesh(), sel_read_mesh_geometry(), sel_read_node_size(), and sel_write_mesh_file().