CALYPSO: t_schmidt_polynomial Module Reference
t_schmidt_polynomial Module Reference
Data array for Legendre polyonomials with Schmidt normalization.
Data Types
type legendre_polynomials
Structure for LEgendre polynomial for single point.
Functions/Subroutines
subroutine alloc_schmidt_polynomial (ltr, leg)
subroutine dealloc_schmidt_polynomial (leg)
subroutine dlad (theta, leg)
subroutine dschmidt (theta, leg)
subroutine full_norm_legendre (theta, leg)
Detailed Description
Data array for Legendre polyonomials with Schmidt normalization.
      subroutine alloc_schmidt_polynomial(ltr, leg)
       subroutine dealloc_schmidt_polynomial(leg)
      subroutine dlad(theta, leg)
      subroutine dschmidt(theta, leg)
      subroutine full_norm_legendre(theta, leg)
Function/Subroutine Documentation
alloc_schmidt_polynomial()
subroutine t_schmidt_polynomial::alloc_schmidt_polynomial (integer(kind = kint), intent(in) ltr, type(legendre_polynomials), intent(inout) leg)
Definition at line 51 of file t_schmidt_polynomial.f90.
Referenced by t_spherical_harmonics::init_sph_indices(), and circle_transform_single::initialize_circle_transform().
dealloc_schmidt_polynomial()
subroutine t_schmidt_polynomial::dealloc_schmidt_polynomial (type(legendre_polynomials), intent(inout) leg)
Definition at line 73 of file t_schmidt_polynomial.f90.
Referenced by t_spherical_harmonics::finalize_sph_indices(), and circle_transform_single::initialize_circle_transform().
dlad()
subroutine t_schmidt_polynomial::dlad (real(kind = kreal), intent(in) theta, type(legendre_polynomials), intent(inout) leg)
Definition at line 84 of file t_schmidt_polynomial.f90.
References legendre::dledendre().
Referenced by schmidt_poly_on_meridian::cal_full_legendre_on_med().
dschmidt()
subroutine t_schmidt_polynomial::dschmidt (real(kind = kreal), intent(in) theta, type(legendre_polynomials), intent(inout) leg)
Definition at line 105 of file t_schmidt_polynomial.f90.
References schmidt::diff_schmidt_legendre(), and schmidt::schmidt_legendre().
Referenced by full_norm_legendre(), circle_transform_single::initialize_circle_transform(), and t_spherical_harmonics::spheric_1point().
full_norm_legendre()
subroutine t_schmidt_polynomial::full_norm_legendre (real(kind = kreal), intent(in) theta, type(legendre_polynomials), intent(inout) leg)
Definition at line 126 of file t_schmidt_polynomial.f90.
References dschmidt(), and schmidt::full_normalize_from_smdt().
Referenced by schmidt_poly_on_meridian::cal_full_legendre_on_med().