CALYPSO: set_surface_node Module Reference
set_surface_node Module Reference
Functions/Subroutines
subroutine allocate_make_4_surf_nod_grp (nnod)
subroutine deallocate_make_4_surf_nod_grp
subroutine count_surf_nod_grp_stack (np_smp, inod_smp_stack, numele, nnod_4_ele, ie, nnod_4_surf, node_on_sf, num_surf, num_surf_bc, surf_istack, surf_item, ntot_node_sf_grp, nnod_sf_grp, inod_stack_sf_grp)
subroutine set_surf_nod_grp_item (numnod, numele, nnod_4_ele, ie, nnod_4_surf, node_on_sf, node_on_sf_n, num_surf, num_surf_bc, surf_istack, surf_item, ntot_node_sf_grp, inod_stack_sf_grp, inod_surf_grp, surf_node_n, num_sf_4_nod)
Variables
integer(kind=kint), dimension(:), allocatable, private imark_nod
integer(kind=kint), dimension(:), allocatable, private icount_smp
Function/Subroutine Documentation
allocate_make_4_surf_nod_grp()
subroutine set_surface_node::allocate_make_4_surf_nod_grp (integer(kind = kint), intent(in) nnod)
Definition at line 39 of file set_surface_node.f90.
References icount_smp, imark_nod, and m_machine_parameter::np_smp.
Referenced by set_connects_4_surf_group::set_node_4_surf_group().
count_surf_nod_grp_stack()
subroutine set_surface_node::count_surf_nod_grp_stack (integer(kind = kint), intent(in) np_smp, integer(kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) nnod_4_ele, integer(kind = kint), dimension(numele,nnod_4_ele), intent(in) ie, integer(kind = kint), intent(in) nnod_4_surf, integer(kind = kint), dimension(nnod_4_surf,nsurf_4_ele), intent(in) node_on_sf, integer(kind = kint), intent(in) num_surf, integer(kind = kint), intent(in) num_surf_bc, integer(kind = kint), dimension(0:num_surf), intent(in) surf_istack, integer(kind = kint), dimension(2,num_surf_bc), intent(in) surf_item, integer(kind = kint), intent(inout) ntot_node_sf_grp, integer(kind = kint), dimension(num_surf), intent(inout) nnod_sf_grp, integer(kind = kint), dimension(0:num_surf), intent(inout) inod_stack_sf_grp)
Definition at line 65 of file set_surface_node.f90.
References icount_smp, and imark_nod.
Referenced by set_connects_4_surf_group::set_node_4_surf_group().
deallocate_make_4_surf_nod_grp()
subroutine set_surface_node::deallocate_make_4_surf_nod_grp
Definition at line 55 of file set_surface_node.f90.
References icount_smp, and imark_nod.
Referenced by set_connects_4_surf_group::set_node_4_surf_group().
set_surf_nod_grp_item()
subroutine set_surface_node::set_surf_nod_grp_item (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) nnod_4_ele, integer(kind = kint), dimension(numele,nnod_4_ele), intent(in) ie, integer(kind = kint), intent(in) nnod_4_surf, integer(kind = kint), dimension(nnod_4_surf,nsurf_4_ele), intent(in) node_on_sf, integer(kind = kint), dimension(nnod_4_surf,nsurf_4_ele), intent(in) node_on_sf_n, integer(kind = kint), intent(in) num_surf, integer(kind = kint), intent(in) num_surf_bc, integer(kind = kint), dimension(0:num_surf), intent(in) surf_istack, integer(kind = kint), dimension(2,num_surf_bc), intent(in) surf_item, integer(kind = kint), intent(in) ntot_node_sf_grp, integer(kind = kint), dimension(0:num_surf), intent(in) inod_stack_sf_grp, integer(kind = kint), dimension(ntot_node_sf_grp), intent(inout) inod_surf_grp, integer(kind = kint), dimension(ntot_node_sf_grp), intent(inout) surf_node_n, integer(kind = kint), dimension(ntot_node_sf_grp), intent(inout) num_sf_4_nod)
Definition at line 141 of file set_surface_node.f90.
References imark_nod.
Referenced by set_connects_4_surf_group::set_node_4_surf_group().
Variable Documentation
icount_smp
integer(kind = kint), dimension(:), allocatable, private set_surface_node::icount_smp private
Definition at line 30 of file set_surface_node.f90.
Referenced by allocate_make_4_surf_nod_grp(), count_surf_nod_grp_stack(), and deallocate_make_4_surf_nod_grp().
imark_nod
integer(kind = kint), dimension(:), allocatable, private set_surface_node::imark_nod private
Definition at line 29 of file set_surface_node.f90.
Referenced by allocate_make_4_surf_nod_grp(), count_surf_nod_grp_stack(), deallocate_make_4_surf_nod_grp(), and set_surf_nod_grp_item().