CALYPSO: mpi_groups_io Module Reference
mpi_groups_io Module Reference
Binary output routines for group data.
Functions/Subroutines
subroutine mpi_read_group_data (IO_param, group_IO)
subroutine mpi_read_surf_grp_data (IO_param, surf_grp_IO)
subroutine mpi_write_grp_data (IO_param, group_IO)
subroutine mpi_write_surf_grp_data (IO_param, surf_grp_IO)
subroutine, private mpi_read_surf_grp_item (IO_param, ncolumn, ntot, ist, num, int_dat)
subroutine, private mpi_write_surf_grp_item (IO_param, ncolumn, ntot, ist, num, int_dat)
Detailed Description
Binary output routines for group data.
      subroutine mpi_read_group_data(IO_param, group_IO)
      subroutine mpi_read_surf_grp_data(IO_param, surf_grp_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(group_data), intent(inout) :: group_IO
        type(surface_group_data), intent(inout) :: surf_grp_IO
      subroutine mpi_write_grp_data(IO_param, group_IO)
      subroutine mpi_write_surf_grp_data(IO_param, surf_grp_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(group_data), intent(in) :: group_IO
        type(surface_group_data), intent(in) :: surf_grp_IO
Function/Subroutine Documentation
mpi_read_group_data()
subroutine mpi_groups_io::mpi_read_group_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(group_data), intent(inout) group_IO)
Definition at line 45 of file MPI_groups_IO.f90.
References t_group_data::alloc_group_item(), t_group_data::alloc_group_num(), mpi_ascii_data_io::mpi_read_charahead(), mpi_domain_data_io::mpi_read_comm_table(), mpi_domain_data_io::mpi_read_int_stack(), mpi_ascii_data_io::mpi_read_num_of_data(), and field_data_mpi_io::read_field_name_mpi().
Referenced by mpi_sph_modes_data_io::mpi_read_geom_rtp_data(), mpi_mesh_data_io::mpi_read_mesh_groups(), and mpi_sph_modes_data_io::mpi_read_spectr_rj_data().
mpi_read_surf_grp_data()
subroutine mpi_groups_io::mpi_read_surf_grp_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(surface_group_data), intent(inout) surf_grp_IO)
Definition at line 83 of file MPI_groups_IO.f90.
References t_group_data::alloc_sf_group_item(), t_group_data::alloc_sf_group_num(), mpi_ascii_data_io::mpi_read_charahead(), mpi_domain_data_io::mpi_read_int_stack(), mpi_ascii_data_io::mpi_read_num_of_data(), mpi_read_surf_grp_item(), and field_data_mpi_io::read_field_name_mpi().
Referenced by mpi_mesh_data_io::mpi_read_mesh_groups().
mpi_read_surf_grp_item()
subroutine, private mpi_groups_io::mpi_read_surf_grp_item (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) ncolumn, integer(kind=kint), intent(in) ntot, integer(kind=kint), intent(in) ist, integer(kind=kint), intent(in) num, integer(kind=kint), dimension(2,ntot), intent(inout) int_dat) private
Definition at line 181 of file MPI_groups_IO.f90.
References mpi_domain_data_io::mpi_read_comm_table(), and mpi_ascii_data_io::mpi_read_num_of_data().
Referenced by mpi_read_surf_grp_data().
mpi_write_grp_data()
subroutine mpi_groups_io::mpi_write_grp_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(group_data), intent(in) group_IO)
Definition at line 123 of file MPI_groups_IO.f90.
References mpi_ascii_data_io::mpi_write_charahead(), mpi_domain_data_io::mpi_write_comm_table(), and mpi_domain_data_io::mpi_write_int_stack().
Referenced by mpi_sph_modes_data_io::mpi_write_geom_rtp_data(), mpi_mesh_data_io::mpi_write_mesh_groups(), and mpi_sph_modes_data_io::mpi_write_spectr_rj_data().
mpi_write_surf_grp_data()
subroutine mpi_groups_io::mpi_write_surf_grp_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(surface_group_data), intent(in) surf_grp_IO)
Definition at line 152 of file MPI_groups_IO.f90.
References mpi_ascii_data_io::mpi_write_charahead(), mpi_domain_data_io::mpi_write_int_stack(), and mpi_write_surf_grp_item().
Referenced by mpi_mesh_data_io::mpi_write_mesh_groups().
mpi_write_surf_grp_item()
subroutine, private mpi_groups_io::mpi_write_surf_grp_item (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) ncolumn, integer(kind=kint), intent(in) ntot, integer(kind=kint), intent(in) ist, integer(kind=kint), intent(in) num, integer(kind=kint), dimension(2,ntot), intent(in) int_dat) private
Definition at line 208 of file MPI_groups_IO.f90.
References mpi_domain_data_io::mpi_write_comm_table().
Referenced by mpi_write_surf_grp_data().