CALYPSO: convert_components_4_viz Module Reference
convert_components_4_viz Module Reference
Functions/Subroutines
subroutine convert_comps_4_viz (nnod, istack_n_smp, xx, sph_r, a_r, cyl_s, a_s, ncomp_viz, ncomp_org, icomp_viz, dat_xyz, dat_viz)
Function/Subroutine Documentation
convert_comps_4_viz()
subroutine convert_components_4_viz::convert_comps_4_viz (integer(kind = kint), intent(in) nnod, integer(kind = kint), dimension(0:np_smp), intent(in) istack_n_smp, real(kind = kreal), dimension(nnod,3), intent(in) xx, real(kind = kreal), dimension(nnod), intent(in) sph_r, real(kind = kreal), dimension(nnod), intent(in) a_r, real(kind = kreal), dimension(nnod), intent(in) cyl_s, real(kind = kreal), dimension(nnod), intent(in) a_s, integer(kind = kint), intent(in) ncomp_viz, integer(kind = kint), intent(in) ncomp_org, integer(kind = kint), intent(in) icomp_viz, real(kind = kreal), dimension(nnod,ncomp_org), intent(in) dat_xyz, real(kind = kreal), dimension(nnod,ncomp_viz), intent(inout) dat_viz)
Definition at line 24 of file convert_components_4_viz.f90.
References cvt_xyz_tensor_2_cyl_smp::cal_cyl_tensor_smp(), cvt_xyz_vector_2_cyl_smp::cal_cylinder_r_comp_smp(), cvt_xyz_vector_2_sph_smp::cal_phi_comp_smp(), cvt_xyz_tensor_2_cyl_smp::cal_pp_cyl_tensor_smp(), cvt_xyz_tensor_2_sph_smp::cal_pp_tensor_smp(), cvt_xyz_tensor_2_cyl_smp::cal_pz_tensor_smp(), cvt_xyz_vector_2_sph_smp::cal_radial_comp_smp(), cvt_xyz_tensor_2_sph_smp::cal_rp_tensor_smp(), cvt_xyz_tensor_2_sph_smp::cal_rr_tensor_smp(), cvt_xyz_tensor_2_sph_smp::cal_rt_tensor_smp(), cvt_xyz_tensor_2_cyl_smp::cal_sp_tensor_smp(), cvt_xyz_tensor_2_sph_smp::cal_sph_tensor_smp(), cvt_xyz_tensor_2_cyl_smp::cal_ss_tensor_smp(), mag_of_field_smp::cal_sym_tensor_magnitude(), cvt_xyz_tensor_2_cyl_smp::cal_sz_tensor_smp(), cvt_xyz_vector_2_sph_smp::cal_theta_comp_smp(), cvt_xyz_tensor_2_sph_smp::cal_tp_tensor_smp(), cvt_xyz_tensor_2_sph_smp::cal_tt_tensor_smp(), mag_of_field_smp::cal_vector_magnitude(), cvt_xyz_tensor_2_cyl_smp::cal_zz_tensor_smp(), copy_field_smp::copy_nod_scalar_smp(), copy_field_smp::copy_nod_sym_tensor_smp(), copy_field_smp::copy_nod_vector_smp(), cvt_xyz_vector_2_cyl_smp::cvt_vector_2_cyl_smp(), cvt_xyz_vector_2_sph_smp::cvt_vector_2_sph_smp(), set_components_flags::icomp_asym_tensor, set_components_flags::icomp_cyl_sym_tensor, set_components_flags::icomp_cyl_vector, set_components_flags::icomp_cylinder_r, set_components_flags::icomp_phi, set_components_flags::icomp_pp, set_components_flags::icomp_pp_cyl, set_components_flags::icomp_pz, set_components_flags::icomp_radial, set_components_flags::icomp_rp, set_components_flags::icomp_rr, set_components_flags::icomp_rt, set_components_flags::icomp_sp, set_components_flags::icomp_sph_vector, set_components_flags::icomp_sphl_sym_tensor, set_components_flags::icomp_ss, set_components_flags::icomp_sym_tensor, set_components_flags::icomp_sz, set_components_flags::icomp_theta, set_components_flags::icomp_tp, set_components_flags::icomp_tt, set_components_flags::icomp_vector, set_components_flags::icomp_xx, set_components_flags::icomp_zz, set_components_flags::icomp_zz_cyl, set_components_flags::ncomp_scalar, set_components_flags::ncomp_sym_tensor, and set_components_flags::ncomp_vector.
Referenced by set_fields_for_psf::set_field_on_psf(), and set_fields_for_psf::set_field_on_psf_grp().