CALYPSO: init_fft_4_sph Module Reference
init_fft_4_sph Module Reference
Select Fourier transform routine by elapsed time.
Functions/Subroutines
subroutine init_fourier_transform_4_sph (ncomp, sph_rtp, comm_rtp, WK_FFTs, iflag_FFT)
subroutine, private s_select_fourier_transform (ncomp, sph_rtp, comm_rtp, n_WS, n_WR, WS, WR, WK_FFTs)
subroutine, private test_fourier_trans_vector (iflag_FFT, ncomp, sph_rtp, comm_rtp, n_WS, n_WR, WS, WR, X_rtp, WK_FFTs, etime_fft)
Variables
integer(kind=kint), parameter, private num_test = 3
integer(kind=kint), dimension(num_test), parameter, private list_test = (/iflag_FFTPACK, iflag_ISPACK1, iflag_ISPACK3/)
real(kind=kreal), private etime_shortest = -1.0e10
integer(kind=kint), private iflag_selected
Detailed Description
Select Fourier transform routine by elapsed time.
      subroutine init_fourier_transform_4_sph                         &
     &         (ncomp, sph_rtp, comm_rtp, WK_FFTs, iflag_FFT)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_comm_tbl), intent(in) :: comm_rtp
        type(work_for_FFTs), intent(inout) :: WK_FFTs
       Current problem
      FFTW crashes when both single and multi transforms are
      comparaed
Function/Subroutine Documentation
init_fourier_transform_4_sph()
subroutine init_fft_4_sph::init_fourier_transform_4_sph (integer(kind = kint), intent(in) ncomp, type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, type(work_for_ffts), intent(inout) WK_FFTs, integer(kind = kint), intent(inout) iflag_FFT)
Definition at line 67 of file init_FFT_4_sph.F90.
References m_fft_selector::chosen_fft_name(), iflag_selected, m_fft_selector::iflag_undefined_fft, t_sph_fft_selector::init_sph_fft_select(), calypso_mpi::my_rank, s_select_fourier_transform(), and m_solver_sr::sr_r1.
Referenced by init_sph_trans::initialize_sph_trans().
s_select_fourier_transform()
subroutine, private init_fft_4_sph::s_select_fourier_transform (integer(kind = kint), intent(in) ncomp, type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, integer(kind = kint), intent(in) n_WS, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_ws), intent(inout) WS, real (kind=kreal), dimension(n_wr), intent(inout) WR, type(work_for_ffts), intent(inout) WK_FFTs) private
Definition at line 97 of file init_FFT_4_sph.F90.
References etime_shortest, iflag_selected, list_test, calypso_mpi::my_rank, test_fourier_trans_vector(), and m_fft_selector::write_elapsed_4_fft().
Referenced by init_fourier_transform_4_sph().
test_fourier_trans_vector()
subroutine, private init_fft_4_sph::test_fourier_trans_vector (integer(kind = kint), intent(in) iflag_FFT, integer(kind = kint), intent(in) ncomp, type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, integer(kind = kint), intent(in) n_WS, integer(kind = kint), intent(in) n_WR, real(kind = kreal), dimension(n_ws), intent(inout) WS, real(kind = kreal), dimension(n_wr), intent(inout) WR, real(kind = kreal), dimension(sph_rtp%nnod_rtp,ncomp), intent(inout) X_rtp, type(work_for_ffts), intent(inout) WK_FFTs, real(kind = kreal), intent(inout) etime_fft) private
Definition at line 136 of file init_FFT_4_sph.F90.
References t_sph_fft_selector::back_fft_select_from_recv(), calypso_mpi_real::calypso_mpi_allreduce_one_real(), t_sph_fft_selector::finalize_sph_fft_select(), t_sph_fft_selector::fwd_fft_select_to_send(), m_machine_parameter::iflag_debug, t_sph_fft_selector::init_sph_fft_select(), calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by s_select_fourier_transform().
Variable Documentation
etime_shortest
real(kind = kreal), private init_fft_4_sph::etime_shortest = -1.0e10 private
Definition at line 53 of file init_FFT_4_sph.F90.
Referenced by s_select_fourier_transform().
iflag_selected
integer(kind = kint), private init_fft_4_sph::iflag_selected private
Definition at line 54 of file init_FFT_4_sph.F90.
Referenced by init_fourier_transform_4_sph(), and s_select_fourier_transform().
list_test
integer(kind = kint), dimension(num_test), parameter, private init_fft_4_sph::list_test = (/iflag_FFTPACK, iflag_ISPACK1, iflag_ISPACK3/) private
Definition at line 43 of file init_FFT_4_sph.F90.
Referenced by s_select_fourier_transform().
num_test
integer(kind = kint), parameter, private init_fft_4_sph::num_test = 3 private
Definition at line 40 of file init_FFT_4_sph.F90.