CALYPSO: viewer_group_data_io Module Reference
viewer_group_data_io Module Reference
Functions/Subroutines
subroutine write_domain_group_viewer (num_pe, domain_grps)
subroutine write_nod_group_viewer (num_pe, view_nod_grps)
subroutine write_ele_group_viewer (num_pe, view_ele_grps)
subroutine write_surf_group_viewer (num_pe, view_sf_grps)
subroutine, private write_viewer_group_data (id_file, num_pe, ngrp, name, v_grp)
Function/Subroutine Documentation
write_domain_group_viewer()
subroutine viewer_group_data_io::write_domain_group_viewer (integer, intent(in) num_pe, type(viewer_surface_groups), intent(in) domain_grps)
Definition at line 35 of file viewer_group_data_IO.f90.
References m_viewer_mesh_labels::hd_domain_edge_grp(), m_viewer_mesh_labels::hd_domain_nod_grp(), m_viewer_mesh_labels::hd_domain_surf_grp(), and t_viewer_mesh::surface_id.
Referenced by viewer_file_io::output_single_surface_grid().
write_ele_group_viewer()
subroutine viewer_group_data_io::write_ele_group_viewer (integer, intent(in) num_pe, type(viewer_surface_groups), intent(in) view_ele_grps)
Definition at line 107 of file viewer_group_data_IO.f90.
References m_viewer_mesh_labels::hd_ele_edge_grp(), m_viewer_mesh_labels::hd_ele_nod_grp(), m_viewer_mesh_labels::hd_ele_surf_grp(), m_fem_mesh_labels::hd_fem_elegrp(), t_viewer_mesh::surface_id, and write_viewer_group_data().
Referenced by viewer_file_io::output_single_surface_grid().
write_nod_group_viewer()
subroutine viewer_group_data_io::write_nod_group_viewer (integer, intent(in) num_pe, type(viewer_node_groups), intent(in) view_nod_grps)
Definition at line 87 of file viewer_group_data_IO.f90.
References m_fem_mesh_labels::hd_fem_nodgrp(), t_viewer_mesh::surface_id, and write_viewer_group_data().
Referenced by viewer_file_io::output_single_surface_grid().
write_surf_group_viewer()
subroutine viewer_group_data_io::write_surf_group_viewer (integer, intent(in) num_pe, type(viewer_surface_groups), intent(in) view_sf_grps)
Definition at line 144 of file viewer_group_data_IO.f90.
References m_fem_mesh_labels::hd_fem_sfgrp(), m_viewer_mesh_labels::hd_surf_edge_grp(), m_viewer_mesh_labels::hd_surf_nod_grp(), m_viewer_mesh_labels::hd_surf_surf_grp(), t_viewer_mesh::surface_id, and write_viewer_group_data().
Referenced by viewer_file_io::output_single_surface_grid().
write_viewer_group_data()
subroutine, private viewer_group_data_io::write_viewer_group_data (integer(kind = kint), intent(in) id_file, integer, intent(in) num_pe, integer(kind = kint), intent(in) ngrp, character(len = kchara), dimension(ngrp), intent(in) name, type(viewer_group_data), intent(in) v_grp) private
Definition at line 180 of file viewer_group_data_IO.f90.
Referenced by write_ele_group_viewer(), write_nod_group_viewer(), and write_surf_group_viewer().