CALYPSO: check_dependency_for_mhd Module Reference
check_dependency_for_mhd Module Reference
Check dependecy of field list fro MHD dynamo.
Functions/Subroutines
subroutine set_sph_mhd_sprctr_data (sph, MHD_prop, rj_fld, ipol)
subroutine check_field_dependencies (fl_prop, cd_prop, ht_prop, cp_prop, iphys_base, fld)
subroutine check_dependence_sph_evo (fl_prop, iphys, fld)
subroutine check_missing_field_w_msg (fld, target_msg, iphys_ref)
Detailed Description
Check dependecy of field list fro MHD dynamo.
      subroutine set_sph_MHD_sprctr_data(sph, MHD_prop, rj_fld, ipol)
        type(sph_grids), intent(in) :: sph
        type(MHD_evolution_param), intent(in) :: MHD_prop
        type(phys_data), intent(inout) :: rj_fld
        type(phys_address), intent(inout) :: ipol
        type(SGS_model_addresses), intent(inout) :: ipol_LES
      subroutine check_field_dependencies                             &
     &         (fl_prop, cd_prop, ht_prop, cp_prop,                   &
     &          iphys_base, iphys_fil, fld)
      subroutine check_dependence_SPH_evo(fl_prop, iphys, fld)
        type(fluid_property), intent(in) :: fl_prop
        type(conductive_property), intent(in) :: cd_prop
        type(scalar_property), intent(in) :: ht_prop, cp_prop
        type(base_field_address), intent(in) :: iphys_base
        type(base_field_address), intent(in) :: iphys_fil
        type(phys_data), intent(in) :: fld
Function/Subroutine Documentation
check_dependence_sph_evo()
subroutine check_dependency_for_mhd::check_dependence_sph_evo (type(fluid_property), intent(in) fl_prop, type(phys_address), intent(in) iphys, type(phys_data), intent(in) fld)
Definition at line 154 of file check_dependency_for_MHD.f90.
References check_missing_field_w_msg(), and t_physical_property::id_no_evolution.
Referenced by set_sph_mhd_sprctr_data().
check_field_dependencies()
subroutine check_dependency_for_mhd::check_field_dependencies (type(fluid_property), intent(in) fl_prop, type(conductive_property), intent(in) cd_prop, type(scalar_property), intent(in) ht_prop, type(scalar_property), intent(in) cp_prop, type(base_field_address), intent(in) iphys_base, type(phys_data), intent(in) fld)
Definition at line 75 of file check_dependency_for_MHD.f90.
References calypso_mpi::calypso_mpi_abort(), check_missing_field_w_msg(), t_physical_property::id_no_evolution, and m_error_ids::ierr_fld.
Referenced by set_sph_mhd_sprctr_data().
check_missing_field_w_msg()
subroutine check_dependency_for_mhd::check_missing_field_w_msg (type(phys_data), intent(in) fld, character(len=kchara), intent(in) target_msg, integer(kind = kint), intent(in) iphys_ref)
Definition at line 173 of file check_dependency_for_MHD.f90.
References calypso_mpi::calypso_mpi_abort(), t_phys_data::field_name_by_address(), and m_error_ids::ierr_fld.
Referenced by check_dependence_sph_evo(), and check_field_dependencies().
set_sph_mhd_sprctr_data()
subroutine check_dependency_for_mhd::set_sph_mhd_sprctr_data (type(sph_grids), intent(in) sph, type(mhd_evolution_param), intent(in) MHD_prop, type(phys_data), intent(inout) rj_fld, type(phys_address), intent(inout) ipol)
Definition at line 51 of file check_dependency_for_MHD.f90.
References check_dependence_sph_evo(), check_field_dependencies(), and set_control_field_data::init_field_data().
Referenced by sph_analyzer_const_initial::sph_const_initial_field(), sph_analyzer_d_bench::sph_init_sph_dbench(), sph_analyzer_snap_w_psf::sph_init_sph_snap_psf(), and sph_analyzer_mhd::sph_initialize_mhd().