CALYPSO: t_schmidt_poly_on_gauss Module Reference
t_schmidt_poly_on_gauss Module Reference
Array for Legendre polyonoials and its derivatives.
Data Types
type gauss_legendre_data
Functions/Subroutines
subroutine alloc_stack_smdt_med_smp (np_smp, leg_d)
subroutine dealloc_stack_smdt_med_smp (leg_d)
subroutine alloc_gauss_colat_med (nth, leg_d)
subroutine alloc_schmidt_poly_med (leg_d)
subroutine alloc_fully_legendre_med (leg_d)
subroutine alloc_legendre_med (leg_d)
subroutine dealloc_gauss_colat_med (leg_d)
subroutine dealloc_schmidt_poly_med (leg_d)
subroutine dealloc_fully_legendre_med (leg_d)
subroutine dealloc_legendre_med (leg_d)
subroutine check_gauss_colat_med (leg_d)
subroutine check_schmidt_poly_med (idx, leg_d)
subroutine check_fully_legendre_med (idx, leg_d)
subroutine check_legendre_poly_med (idx, leg_d)
Detailed Description
Array for Legendre polyonoials and its derivatives.
      subroutine alloc_stack_smdt_med_smp(np_smp, leg_d)
      subroutine dealloc_stack_smdt_med_smp(leg_d)
      subroutine alloc_gauss_colat_med(nth, leg_d)
      subroutine alloc_schmidt_poly_med(leg_d)
      subroutine alloc_fully_legendre_med(leg_d)
      subroutine alloc_legendre_med(leg_d)
      subroutine dealloc_gauss_colat_med(leg_d)
      subroutine dealloc_schmidt_poly_med(leg_d)
      subroutine dealloc_fully_legendre_med(leg_d)
      subroutine dealloc_legendre_med(leg_d)
        type(gauss_legendre_data), intent(inout) :: leg_d
      subroutine check_gauss_colat_med(leg_d)
      subroutine check_schmidt_poly_med(idx, leg_d)
      subroutine check_fully_legendre_med(idx, leg_d)
      subroutine check_legendre_poly_med(idx, leg_d)
Function/Subroutine Documentation
alloc_fully_legendre_med()
subroutine t_schmidt_poly_on_gauss::alloc_fully_legendre_med (type(gauss_legendre_data), intent(inout) leg_d)
Definition at line 138 of file t_schmidt_poly_on_gauss.f90.
alloc_gauss_colat_med()
subroutine t_schmidt_poly_on_gauss::alloc_gauss_colat_med (integer(kind = kint), intent(in) nth, type(gauss_legendre_data), intent(inout) leg_d)
Definition at line 102 of file t_schmidt_poly_on_gauss.f90.
Referenced by schmidt_poly_on_meridian::cal_full_legendre_on_med().
alloc_legendre_med()
subroutine t_schmidt_poly_on_gauss::alloc_legendre_med (type(gauss_legendre_data), intent(inout) leg_d)
Definition at line 153 of file t_schmidt_poly_on_gauss.f90.
Referenced by schmidt_poly_on_meridian::cal_full_legendre_on_med().
alloc_schmidt_poly_med()
subroutine t_schmidt_poly_on_gauss::alloc_schmidt_poly_med (type(gauss_legendre_data), intent(inout) leg_d)
Definition at line 123 of file t_schmidt_poly_on_gauss.f90.
Referenced by schmidt_poly_on_meridian::cal_full_legendre_on_med().
alloc_stack_smdt_med_smp()
subroutine t_schmidt_poly_on_gauss::alloc_stack_smdt_med_smp (integer(kind = kint), intent(in) np_smp, type(gauss_legendre_data), intent(inout) leg_d)
Definition at line 72 of file t_schmidt_poly_on_gauss.f90.
check_fully_legendre_med()
subroutine t_schmidt_poly_on_gauss::check_fully_legendre_med (integer(kind = kint), dimension(0:leg_d%jmax_g,2), intent(in) idx, type(gauss_legendre_data), intent(in) leg_d)
Definition at line 249 of file t_schmidt_poly_on_gauss.f90.
check_gauss_colat_med()
subroutine t_schmidt_poly_on_gauss::check_gauss_colat_med (type(gauss_legendre_data), intent(in) leg_d)
Definition at line 208 of file t_schmidt_poly_on_gauss.f90.
check_legendre_poly_med()
subroutine t_schmidt_poly_on_gauss::check_legendre_poly_med (integer(kind = kint), dimension(0:leg_d%jmax_g,2), intent(in) idx, type(gauss_legendre_data), intent(in) leg_d)
Definition at line 273 of file t_schmidt_poly_on_gauss.f90.
check_schmidt_poly_med()
subroutine t_schmidt_poly_on_gauss::check_schmidt_poly_med (integer(kind = kint), dimension(0:leg_d%jmax_g,2), intent(in) idx, type(gauss_legendre_data), intent(in) leg_d)
Definition at line 226 of file t_schmidt_poly_on_gauss.f90.
dealloc_fully_legendre_med()
subroutine t_schmidt_poly_on_gauss::dealloc_fully_legendre_med (type(gauss_legendre_data), intent(inout) leg_d)
Definition at line 187 of file t_schmidt_poly_on_gauss.f90.
dealloc_gauss_colat_med()
subroutine t_schmidt_poly_on_gauss::dealloc_gauss_colat_med (type(gauss_legendre_data), intent(inout) leg_d)
Definition at line 165 of file t_schmidt_poly_on_gauss.f90.
dealloc_legendre_med()
subroutine t_schmidt_poly_on_gauss::dealloc_legendre_med (type(gauss_legendre_data), intent(inout) leg_d)
Definition at line 197 of file t_schmidt_poly_on_gauss.f90.
dealloc_schmidt_poly_med()
subroutine t_schmidt_poly_on_gauss::dealloc_schmidt_poly_med (type(gauss_legendre_data), intent(inout) leg_d)
Definition at line 177 of file t_schmidt_poly_on_gauss.f90.
dealloc_stack_smdt_med_smp()
subroutine t_schmidt_poly_on_gauss::dealloc_stack_smdt_med_smp (type(gauss_legendre_data), intent(inout) leg_d)
Definition at line 89 of file t_schmidt_poly_on_gauss.f90.