CALYPSO: cal_sph_ele_connects Module Reference
cal_sph_ele_connects Module Reference
Functions/Subroutines
subroutine set_spherical_shell_element (ip_r, ip_t, stbl, ele)
subroutine set_south_pole_element (ip_r, ip_t, stbl, ele)
subroutine set_north_pole_element (ip_r, ip_t, stbl, ele)
subroutine set_inter_center_shell_ele (ip_r, ip_t, stbl, ele)
subroutine set_exter_center_shell_ele (ip_r, ip_t, stbl, ele)
subroutine set_inter_center_s_pole_ele (ip_r, ip_t, stbl, ele)
subroutine set_inter_center_n_pole_ele (ip_r, ip_t, stbl, ele)
subroutine set_exter_center_n_pole_ele (ip_r, ip_t, stbl, ele)
Function/Subroutine Documentation
set_exter_center_n_pole_ele()
subroutine cal_sph_ele_connects::set_exter_center_n_pole_ele (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, type(comm_table_make_sph), intent(in) stbl, type(element_data), intent(inout) ele)
Definition at line 364 of file cal_sph_ele_connects.f90.
References cal_sph_ele_addresses::global_ctr_npole_ele_id(), cal_sph_node_addresses::sph_center_node_id(), cal_sph_ele_addresses::sph_exter_ctr_npole_ele_id(), cal_sph_node_addresses::sph_n_pole_node_id(), and cal_sph_node_addresses::sph_shell_node_id().
Referenced by set_sph_local_element::set_local_elements_sph_mesh().
set_exter_center_shell_ele()
subroutine cal_sph_ele_connects::set_exter_center_shell_ele (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, type(comm_table_make_sph), intent(in) stbl, type(element_data), intent(inout) ele)
Definition at line 237 of file cal_sph_ele_connects.f90.
References cal_sph_ele_addresses::global_ctr_shell_ele_id(), cal_sph_node_addresses::sph_center_node_id(), cal_sph_ele_addresses::sph_exter_ctr_shell_ele_id(), and cal_sph_node_addresses::sph_shell_node_id().
Referenced by set_sph_local_element::set_local_elements_sph_mesh().
set_inter_center_n_pole_ele()
subroutine cal_sph_ele_connects::set_inter_center_n_pole_ele (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, type(comm_table_make_sph), intent(in) stbl, type(element_data), intent(inout) ele)
Definition at line 318 of file cal_sph_ele_connects.f90.
References cal_sph_ele_addresses::global_ctr_npole_ele_id(), cal_sph_node_addresses::sph_center_node_id(), cal_sph_node_addresses::sph_center_np_node_id(), cal_sph_node_addresses::sph_ctr_shell_node_id(), cal_sph_ele_addresses::sph_inter_ctr_npole_ele_id(), cal_sph_node_addresses::sph_n_pole_node_id(), and cal_sph_node_addresses::sph_shell_node_id().
Referenced by set_sph_local_element::set_local_elements_sph_mesh().
set_inter_center_s_pole_ele()
subroutine cal_sph_ele_connects::set_inter_center_s_pole_ele (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, type(comm_table_make_sph), intent(in) stbl, type(element_data), intent(inout) ele)
Definition at line 281 of file cal_sph_ele_connects.f90.
References cal_sph_ele_addresses::global_ctr_spole_ele_id(), cal_sph_node_addresses::sph_center_node_id(), cal_sph_ele_addresses::sph_inter_ctr_spole_ele_id(), cal_sph_node_addresses::sph_s_pole_node_id(), and cal_sph_node_addresses::sph_shell_node_id().
Referenced by set_sph_local_element::set_local_elements_sph_mesh().
set_inter_center_shell_ele()
subroutine cal_sph_ele_connects::set_inter_center_shell_ele (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, type(comm_table_make_sph), intent(in) stbl, type(element_data), intent(inout) ele)
Definition at line 182 of file cal_sph_ele_connects.f90.
References cal_sph_ele_addresses::global_ctr_shell_ele_id(), cal_sph_node_addresses::sph_center_node_id(), cal_sph_node_addresses::sph_ctr_shell_node_id(), cal_sph_ele_addresses::sph_inter_ctr_shell_ele_id(), and cal_sph_node_addresses::sph_shell_node_id().
Referenced by set_sph_local_element::set_local_elements_sph_mesh().
set_north_pole_element()
subroutine cal_sph_ele_connects::set_north_pole_element (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, type(comm_table_make_sph), intent(in) stbl, type(element_data), intent(inout) ele)
Definition at line 135 of file cal_sph_ele_connects.f90.
References cal_sph_ele_addresses::global_sph_n_pole_ele_id(), cal_sph_ele_addresses::sph_n_pole_ele_id(), cal_sph_node_addresses::sph_n_pole_node_id(), and cal_sph_node_addresses::sph_shell_node_id().
Referenced by set_sph_local_element::set_local_elements_sph_mesh().
set_south_pole_element()
subroutine cal_sph_ele_connects::set_south_pole_element (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, type(comm_table_make_sph), intent(in) stbl, type(element_data), intent(inout) ele)
Definition at line 89 of file cal_sph_ele_connects.f90.
References cal_sph_ele_addresses::global_sph_s_pole_ele_id(), cal_sph_ele_addresses::sph_s_pole_ele_id(), cal_sph_node_addresses::sph_s_pole_node_id(), and cal_sph_node_addresses::sph_shell_node_id().
Referenced by set_sph_local_element::set_local_elements_sph_mesh().
set_spherical_shell_element()
subroutine cal_sph_ele_connects::set_spherical_shell_element (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, type(comm_table_make_sph), intent(in) stbl, type(element_data), intent(inout) ele)
Definition at line 36 of file cal_sph_ele_connects.f90.
References cal_sph_ele_addresses::global_sph_shell_ele_id(), cal_sph_ele_addresses::sph_shell_ele_id(), and cal_sph_node_addresses::sph_shell_node_id().
Referenced by set_sph_local_element::set_local_elements_sph_mesh().