CALYPSO: cal_ave_4_rms_vector_sph Module Reference
cal_ave_4_rms_vector_sph Module Reference
Take surface or volume average for mean square data.
Functions/Subroutines
subroutine cal_one_over_volume (kg_st, kg_ed, nri, radius_1d_rj_r, avol)
subroutine surf_ave_4_sph_rms_int (l_truncation, nri, a_r_1d_rj_r, nri_rms, ntot_rms_rj, kr_for_rms, rms_sph_l)
subroutine surf_ave_4_sph_rms (nri, a_r_1d_rj_r, nri_rms, ntot_rms_rj, kr_for_rms, rms_sph)
subroutine vol_ave_4_rms_sph_int (l_truncation, ntot_rms_rj, avol, rms_sph_vol_l)
subroutine vol_ave_4_rms_sph (ntot_rms_rj, avol, rms_sph_vol)
subroutine sum_sph_vol_rms_all_modes (ltr, ntot_rms, rms_sph_vl, rms_v_sph)
subroutine sum_sph_rms_all_modes (ltr, nri_rms, ntot_rms, rms_sph_l, rms_sph)
subroutine pick_axis_sph_vol_pwr (ltr, ntot_rms, rms_sph_vm, sq_v_sph, rms_v_sph_m0, ratio_v_sph_m0)
subroutine pick_axis_sph_power (ltr, nri_rms, ntot_rms, rms_sph_m, rms_sph, rms_sph_m0, ratio_sph_m0)
Detailed Description
Take surface or volume average for mean square data.
      subroutine cal_one_over_volume                                  &
     &         (kg_st, kg_ed, nri, radius_1d_rj_r, avol)
      subroutine surf_ave_4_sph_rms_int(l_truncation, nri,            &
     &          a_r_1d_rj_r, nri_rms, ntot_rms_rj, kr_for_rms,        &
     &          rms_sph_l)
      subroutine surf_ave_4_sph_rms(nri, a_r_1d_rj_r,                 &
     &          nri_rms, ntot_rms_rj, kr_for_rms, rms_sph)
      subroutine vol_ave_4_rms_sph_int(l_truncation, ntot_rms_rj,     &
     &          avol, sq_sph_vol_l)
      subroutine vol_ave_4_rms_sph(ntot_rms_rj, avol, rms_sph_vol)
      subroutine sum_sph_vol_rms_all_modes(ltr, ntot_rms,             &
     &          sq_sph_vl, sq_v_sph)
      subroutine sum_sph_rms_all_modes(ltr, nri_rms, ntot_rms,        &
     &          rms_sph_l, rms_sph)
      subroutine pick_axis_sph_vol_pwr(ltr, ntot_rms,                 &
     &          rms_sph_vm, sq_v_sph, rms_v_sph_m0, ratio_v_sph_m0)
      subroutine pick_axis_sph_power(ltr, nri_rms, ntot_rms,          &
     &          rms_sph_m, rms_sph, rms_sph_m0, ratio_sph_m0)
\(1/V \int (\phi_l^m)^2 r^{2} sin \theta dr d\theta d\phi = [3/(ro^3-ri^3)] \int 1/(2l+1) (\phi_l^m)^2 r^{2} dr \)
Parameters
avol 1 / Volume
Function/Subroutine Documentation
cal_one_over_volume()
subroutine cal_ave_4_rms_vector_sph::cal_one_over_volume (integer(kind = kint), intent(in) kg_st, integer(kind = kint), intent(in) kg_ed, integer(kind = kint), intent(in) nri, real(kind = kreal), dimension(nri), intent(in) radius_1d_rj_r, real(kind = kreal), intent(inout) avol)
Definition at line 53 of file cal_ave_4_rms_vector_sph.f90.
References m_constants::three.
Referenced by cal_rms_fields_by_sph::init_rms_4_sph_spectr().
pick_axis_sph_power()
subroutine cal_ave_4_rms_vector_sph::pick_axis_sph_power (integer(kind = kint), intent(in) ltr, integer(kind = kint), intent(in) nri_rms, integer(kind = kint), intent(in) ntot_rms, real(kind = kreal), dimension(nri_rms,0:ltr,ntot_rms), intent(in) rms_sph_m, real(kind = kreal), dimension(nri_rms,ntot_rms), intent(in) rms_sph, real(kind = kreal), dimension(nri_rms,ntot_rms), intent(inout) rms_sph_m0, real(kind = kreal), dimension(nri_rms,ntot_rms), intent(inout) ratio_sph_m0)
Definition at line 264 of file cal_ave_4_rms_vector_sph.f90.
References m_constants::zero.
Referenced by cal_rms_fields_by_sph::sum_mean_square_on_sphere().
pick_axis_sph_vol_pwr()
subroutine cal_ave_4_rms_vector_sph::pick_axis_sph_vol_pwr (integer(kind = kint), intent(in) ltr, integer(kind = kint), intent(in) ntot_rms, real(kind = kreal), dimension(0:ltr,ntot_rms), intent(in) rms_sph_vm, real(kind = kreal), dimension(ntot_rms), intent(in) sq_v_sph, real(kind = kreal), dimension(ntot_rms), intent(inout) rms_v_sph_m0, real(kind = kreal), dimension(ntot_rms), intent(inout) ratio_v_sph_m0)
Definition at line 236 of file cal_ave_4_rms_vector_sph.f90.
References m_constants::zero.
Referenced by cal_rms_fields_by_sph::sum_mean_square_on_volume().
sum_sph_rms_all_modes()
subroutine cal_ave_4_rms_vector_sph::sum_sph_rms_all_modes (integer(kind = kint), intent(in) ltr, integer(kind = kint), intent(in) nri_rms, integer(kind = kint), intent(in) ntot_rms, real(kind = kreal), dimension(nri_rms,0:ltr,ntot_rms), intent(in) rms_sph_l, real(kind = kreal), dimension(nri_rms,ntot_rms), intent(inout) rms_sph)
Definition at line 207 of file cal_ave_4_rms_vector_sph.f90.
Referenced by cal_rms_fields_by_sph::sum_mean_square_on_sphere().
sum_sph_vol_rms_all_modes()
subroutine cal_ave_4_rms_vector_sph::sum_sph_vol_rms_all_modes (integer(kind = kint), intent(in) ltr, integer(kind = kint), intent(in) ntot_rms, real(kind = kreal), dimension(0:ltr,ntot_rms), intent(in) rms_sph_vl, real(kind = kreal), dimension(ntot_rms), intent(inout) rms_v_sph)
Definition at line 182 of file cal_ave_4_rms_vector_sph.f90.
Referenced by cal_rms_fields_by_sph::sum_mean_square_on_volume().
surf_ave_4_sph_rms()
subroutine cal_ave_4_rms_vector_sph::surf_ave_4_sph_rms (integer(kind = kint), intent(in) nri, real(kind = kreal), dimension(nri), intent(in) a_r_1d_rj_r, integer(kind = kint), intent(in) nri_rms, integer(kind = kint), intent(in) ntot_rms_rj, integer(kind=kint), dimension(nri_rms), intent(in) kr_for_rms, real(kind = kreal), dimension(nri_rms,ntot_rms_rj), intent(inout) rms_sph)
Definition at line 107 of file cal_ave_4_rms_vector_sph.f90.
Referenced by cal_rms_fields_by_sph::sum_mean_square_on_sphere().
surf_ave_4_sph_rms_int()
subroutine cal_ave_4_rms_vector_sph::surf_ave_4_sph_rms_int (integer(kind = kint), intent(in) l_truncation, integer(kind = kint), intent(in) nri, real(kind = kreal), dimension(nri), intent(in) a_r_1d_rj_r, integer(kind = kint), intent(in) nri_rms, integer(kind = kint), intent(in) ntot_rms_rj, integer(kind=kint), dimension(nri_rms), intent(in) kr_for_rms, real(kind = kreal), dimension(nri_rms,0:l_truncation,ntot_rms_rj), intent(inout) rms_sph_l)
Definition at line 74 of file cal_ave_4_rms_vector_sph.f90.
Referenced by cal_rms_fields_by_sph::sum_mean_square_on_sphere().
vol_ave_4_rms_sph()
subroutine cal_ave_4_rms_vector_sph::vol_ave_4_rms_sph (integer(kind = kint), intent(in) ntot_rms_rj, real(kind = kreal), intent(in) avol, real(kind = kreal), dimension(ntot_rms_rj), intent(inout) rms_sph_vol)
Definition at line 161 of file cal_ave_4_rms_vector_sph.f90.
Referenced by cal_rms_fields_by_sph::sum_mean_square_on_volume().
vol_ave_4_rms_sph_int()
subroutine cal_ave_4_rms_vector_sph::vol_ave_4_rms_sph_int (integer(kind = kint), intent(in) l_truncation, integer(kind = kint), intent(in) ntot_rms_rj, real(kind = kreal), intent(in) avol, real(kind = kreal), dimension(0:l_truncation,ntot_rms_rj), intent(inout) rms_sph_vol_l)
Definition at line 137 of file cal_ave_4_rms_vector_sph.f90.
Referenced by cal_rms_fields_by_sph::sum_mean_square_on_volume().