CALYPSO: mpi_domain_data_io_b Module Reference
mpi_domain_data_io_b Module Reference
Routine for gzipped binary doimain data IO.
Functions/Subroutines
subroutine mpi_read_domain_info_b (IO_param, comm_IO)
subroutine mpi_read_import_data_b (IO_param, comm_IO)
subroutine mpi_read_export_data_b (IO_param, comm_IO)
subroutine mpi_write_domain_info_b (IO_param, comm_IO)
subroutine mpi_write_import_data_b (IO_param, comm_IO)
subroutine mpi_write_export_data_b (IO_param, comm_IO)
Detailed Description
Routine for gzipped binary doimain data IO.
      subroutine mpi_read_domain_info_b(IO_param, comm_IO)
      subroutine mpi_read_import_data_b(IO_param, comm_IO)
      subroutine mpi_read_export_data_b(IO_param, comm_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(communication_table), intent(inout) :: comm_IO
      subroutine mpi_write_domain_info_b(IO_param, comm_IO)
      subroutine mpi_write_import_data_b(IO_param, comm_IO)
      subroutine mpi_write_export_data_b(IO_param, comm_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(communication_table), intent(in) :: comm_IO
Function/Subroutine Documentation
mpi_read_domain_info_b()
subroutine mpi_domain_data_io_b::mpi_read_domain_info_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(inout) comm_IO)
Definition at line 41 of file MPI_domain_data_IO_b.f90.
References t_comm_table::alloc_neighbouring_id(), mpi_binary_data_io::mpi_read_int_vector_b(), mpi_binary_data_io::mpi_read_one_integer_b(), and mpi_binary_head_io::mpi_read_process_id_b().
Referenced by mpi_edge_data_io_b::mpi_read_edge_connection_b(), mpi_element_data_io_b::mpi_read_element_comm_table_b(), mpi_sph_modes_data_io_b::mpi_read_geom_rtm_data_b(), mpi_sph_modes_data_io_b::mpi_read_geom_rtp_data_b(), mpi_sph_modes_data_io_b::mpi_read_modes_rlm_data_b(), mpi_mesh_data_io_b::mpi_read_num_node_ele(), mpi_sph_modes_data_io_b::mpi_read_spectr_rj_data_b(), and mpi_surface_data_io_b::mpi_read_surface_connection_b().
mpi_read_export_data_b()
subroutine mpi_domain_data_io_b::mpi_read_export_data_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(inout) comm_IO)
Definition at line 89 of file MPI_domain_data_IO_b.f90.
References t_comm_table::alloc_export_item(), t_comm_table::alloc_export_num(), mpi_binary_data_io::mpi_read_int_vector_b(), and mpi_binary_data_io::mpi_read_integer_stack_b().
Referenced by mpi_edge_data_io_b::mpi_read_edge_connection_b(), mpi_element_data_io_b::mpi_read_element_comm_table_b(), and mpi_surface_data_io_b::mpi_read_surface_connection_b().
mpi_read_import_data_b()
subroutine mpi_domain_data_io_b::mpi_read_import_data_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(inout) comm_IO)
Definition at line 66 of file MPI_domain_data_IO_b.f90.
References t_comm_table::alloc_import_item(), t_comm_table::alloc_import_num(), mpi_binary_data_io::mpi_read_int_vector_b(), and mpi_binary_data_io::mpi_read_integer_stack_b().
Referenced by mpi_edge_data_io_b::mpi_read_edge_connection_b(), mpi_element_data_io_b::mpi_read_element_comm_table_b(), mpi_sph_modes_data_io_b::mpi_read_geom_rtm_data_b(), mpi_sph_modes_data_io_b::mpi_read_geom_rtp_data_b(), mpi_sph_modes_data_io_b::mpi_read_modes_rlm_data_b(), mpi_sph_modes_data_io_b::mpi_read_spectr_rj_data_b(), and mpi_surface_data_io_b::mpi_read_surface_connection_b().
mpi_write_domain_info_b()
subroutine mpi_domain_data_io_b::mpi_write_domain_info_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(in) comm_IO)
Definition at line 113 of file MPI_domain_data_IO_b.f90.
References t_calypso_mpi_io_param::istack64_4_parallel_data(), mpi_binary_data_io::mpi_write_int_vector_b(), mpi_binary_data_io::mpi_write_one_integer_b(), and mpi_binary_head_io::mpi_write_process_id_b().
Referenced by mpi_edge_data_io_b::mpi_write_edge_connection_b(), mpi_element_data_io_b::mpi_write_element_comm_table_b(), mpi_sph_modes_data_io_b::mpi_write_geom_rtm_data_b(), mpi_sph_modes_data_io_b::mpi_write_geom_rtp_data_b(), mpi_mesh_data_io_b::mpi_write_geometry_data_b(), mpi_sph_modes_data_io_b::mpi_write_modes_rlm_data_b(), mpi_sph_modes_data_io_b::mpi_write_spectr_rj_data_b(), and mpi_surface_data_io_b::mpi_write_surface_connection_b().
mpi_write_export_data_b()
subroutine mpi_domain_data_io_b::mpi_write_export_data_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(in) comm_IO)
Definition at line 156 of file MPI_domain_data_IO_b.f90.
References transfer_to_long_integers::cast_long(), t_calypso_mpi_io_param::istack64_4_parallel_data(), mpi_binary_data_io::mpi_write_int_vector_b(), and mpi_binary_data_io::mpi_write_integer_stack_b().
Referenced by mpi_edge_data_io_b::mpi_write_edge_connection_b(), mpi_element_data_io_b::mpi_write_element_comm_table_b(), mpi_mesh_data_io_b::mpi_write_geometry_data_b(), and mpi_surface_data_io_b::mpi_write_surface_connection_b().
mpi_write_import_data_b()
subroutine mpi_domain_data_io_b::mpi_write_import_data_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(in) comm_IO)
Definition at line 134 of file MPI_domain_data_IO_b.f90.
References transfer_to_long_integers::cast_long(), t_calypso_mpi_io_param::istack64_4_parallel_data(), mpi_binary_data_io::mpi_write_int_vector_b(), and mpi_binary_data_io::mpi_write_integer_stack_b().
Referenced by mpi_edge_data_io_b::mpi_write_edge_connection_b(), mpi_element_data_io_b::mpi_write_element_comm_table_b(), mpi_sph_modes_data_io_b::mpi_write_geom_rtm_data_b(), mpi_sph_modes_data_io_b::mpi_write_geom_rtp_data_b(), mpi_mesh_data_io_b::mpi_write_geometry_data_b(), mpi_sph_modes_data_io_b::mpi_write_modes_rlm_data_b(), mpi_sph_modes_data_io_b::mpi_write_spectr_rj_data_b(), and mpi_surface_data_io_b::mpi_write_surface_connection_b().