CALYPSO: const_node_list_4_viewer Module Reference
const_node_list_4_viewer Module Reference
Functions/Subroutines
subroutine allocate_imark_node_4_list (numnod)
subroutine deallocate_imark_node_4_list
subroutine mark_node_4_domain_viewer (nnod_4_surf, nnod_4_edge, view_mesh, domain_edge_grp, domain_surf_grp)
subroutine mark_node_4_ele_grp_viewer (igrp, nnod_4_surf, nnod_4_edge, view_mesh, domain_edge_grp, ele_surf_grp, ele_edge_grp)
subroutine mark_node_4_surf_grp_viewer (igrp, nnod_4_surf, nnod_4_edge, view_mesh, domain_edge_grp, sf_surf_grp, sf_edge_grp)
subroutine count_nod_stack_4_ele_gp_viewer (igrp, nnod_viewer, ele_nod_grp)
subroutine const_nod_4_ele_gp_viewer (igrp, nnod_viewer, ele_nod_grp)
Variables
integer(kind=kint), dimension(:), allocatable, private imark_node
Function/Subroutine Documentation
allocate_imark_node_4_list()
subroutine const_node_list_4_viewer::allocate_imark_node_4_list (integer(kind = kint) numnod)
Definition at line 55 of file const_node_list_4_viewer.f90.
References imark_node.
Referenced by set_nodes_4_groups_viewer::s_set_nodes_4_groups_viewer().
const_nod_4_ele_gp_viewer()
subroutine const_node_list_4_viewer::const_nod_4_ele_gp_viewer (integer(kind = kint), intent(in) igrp, integer(kind = kint), intent(in) nnod_viewer, type(viewer_group_data), intent(inout) ele_nod_grp)
Definition at line 209 of file const_node_list_4_viewer.f90.
References imark_node.
Referenced by set_nodes_4_groups_viewer::set_nod_4_domain_viewer(), set_nodes_4_groups_viewer::set_nod_4_ele_group_viewer(), and set_nodes_4_groups_viewer::set_nod_4_surf_group_viewer().
count_nod_stack_4_ele_gp_viewer()
subroutine const_node_list_4_viewer::count_nod_stack_4_ele_gp_viewer (integer(kind = kint), intent(in) igrp, integer(kind = kint), intent(in) nnod_viewer, type(viewer_group_data), intent(inout) ele_nod_grp)
Definition at line 188 of file const_node_list_4_viewer.f90.
References imark_node.
Referenced by set_nodes_4_groups_viewer::set_nod_4_domain_viewer(), set_nodes_4_groups_viewer::set_nod_4_ele_group_viewer(), and set_nodes_4_groups_viewer::set_nod_4_surf_group_viewer().
deallocate_imark_node_4_list()
subroutine const_node_list_4_viewer::deallocate_imark_node_4_list
Definition at line 66 of file const_node_list_4_viewer.f90.
References imark_node.
Referenced by set_nodes_4_groups_viewer::s_set_nodes_4_groups_viewer().
mark_node_4_domain_viewer()
subroutine const_node_list_4_viewer::mark_node_4_domain_viewer (integer(kind = kint), intent(in) nnod_4_surf, integer(kind = kint), intent(in) nnod_4_edge, type(viewer_mesh_data), intent(in) view_mesh, type(viewer_group_data), intent(in) domain_edge_grp, type(viewer_group_data), intent(in) domain_surf_grp)
Definition at line 75 of file const_node_list_4_viewer.f90.
References imark_node, and m_geometry_constants::num_lag_sf.
Referenced by set_nodes_4_groups_viewer::set_nod_4_domain_viewer().
mark_node_4_ele_grp_viewer()
subroutine const_node_list_4_viewer::mark_node_4_ele_grp_viewer (integer(kind = kint), intent(in) igrp, integer(kind = kint), intent(in) nnod_4_surf, integer(kind = kint), intent(in) nnod_4_edge, type(viewer_mesh_data), intent(in) view_mesh, type(viewer_group_data), intent(in) domain_edge_grp, type(viewer_group_data), intent(in) ele_surf_grp, type(viewer_group_data), intent(in) ele_edge_grp)
Definition at line 107 of file const_node_list_4_viewer.f90.
References imark_node, and m_geometry_constants::num_lag_sf.
Referenced by set_nodes_4_groups_viewer::set_nod_4_ele_group_viewer().
mark_node_4_surf_grp_viewer()
subroutine const_node_list_4_viewer::mark_node_4_surf_grp_viewer (integer(kind = kint), intent(in) igrp, integer(kind = kint), intent(in) nnod_4_surf, integer(kind = kint), intent(in) nnod_4_edge, type(viewer_mesh_data), intent(in) view_mesh, type(viewer_group_data), intent(in) domain_edge_grp, type(viewer_group_data), intent(in) sf_surf_grp, type(viewer_group_data), intent(in) sf_edge_grp)
Definition at line 147 of file const_node_list_4_viewer.f90.
References imark_node, and m_geometry_constants::num_lag_sf.
Referenced by set_nodes_4_groups_viewer::set_nod_4_surf_group_viewer().
Variable Documentation
imark_node
integer(kind = kint), dimension(:), allocatable, private const_node_list_4_viewer::imark_node private
Definition at line 47 of file const_node_list_4_viewer.f90.
Referenced by allocate_imark_node_4_list(), const_nod_4_ele_gp_viewer(), count_nod_stack_4_ele_gp_viewer(), deallocate_imark_node_4_list(), mark_node_4_domain_viewer(), mark_node_4_ele_grp_viewer(), and mark_node_4_surf_grp_viewer().