CALYPSO: read_psf_binary_file Module Reference
read_psf_binary_file Module Reference
read binary section file
Functions/Subroutines
subroutine read_alloc_psf_bin_grid (file_name, nprocs, ucd_b)
subroutine read_alloc_psf_bin_file (file_name, nprocs, t_IO, ucd_b)
subroutine read_alloc_iso_bin_file (file_name, t_IO, ucd_b)
subroutine read_alloc_nostep_psf_bin_file (file_name, nprocs, ucd_b)
subroutine read_alloc_nostep_iso_bin_file (file_name, ucd_b)
subroutine read_psf_bin_grid (file_name, nprocs, ucd_b)
subroutine read_psf_bin_file (file_name, nprocs, t_IO, ucd_b)
subroutine read_iso_bin_file (file_name, t_IO, ucd_b)
Variables
type(binary_io_buffer), save, private bbuf_ucd
integer(kind=kint_gl), dimension(:), allocatable, private itmp1_mp
Detailed Description
read binary section file
      subroutine read_alloc_psf_bin_grid(file_name, nprocs, ucd_b)
      subroutine read_alloc_psf_bin_file                              &
     &         (file_name, nprocs, t_IO, ucd_b)
      subroutine read_alloc_iso_bin_file(file_name, t_IO, ucd_b)
      subroutine read_alloc_nostep_psf_bin_file                       &
     &         (file_name, nprocs, ucd_b)
      subroutine read_alloc_nostep_iso_bin_file(file_name, ucd_b)
        character(len = kchara), intent(in) :: file_name
        type(ucd_data), intent(inout) :: ucd_b
      subroutine read_psf_bin_grid(file_name, nprocs, ucd_b)
      subroutine read_psf_bin_file(file_name, nprocs, t_IO, ucd_b)
      subroutine read_iso_bin_file(file_name, t_IO, ucd_b)
        character(len = kchara), intent(in) :: file_name
        type(ucd_data), intent(inout) :: ucd_b
Function/Subroutine Documentation
read_alloc_iso_bin_file()
subroutine read_psf_binary_file::read_alloc_iso_bin_file (character(len = kchara), intent(in) file_name, type(time_data), intent(inout) t_IO, type(ucd_data), intent(inout) ucd_b)
Definition at line 99 of file read_psf_binary_file.f90.
References bbuf_ucd, binary_io::close_binary_file(), itmp1_mp, m_constants::izero, binary_io::open_read_binary_file(), read_udt_from_bindary_data::read_alloc_psf_bin_field_data(), read_udt_from_bindary_data::read_alloc_psf_bin_grid_data(), binary_io::read_one_integer_b(), and read_udt_from_bindary_data::read_psf_bin_time_data().
Referenced by ucd_io_select::sel_read_alloc_ucd_file().
read_alloc_nostep_iso_bin_file()
subroutine read_psf_binary_file::read_alloc_nostep_iso_bin_file (character(len = kchara), intent(in) file_name, type(ucd_data), intent(inout) ucd_b)
Definition at line 160 of file read_psf_binary_file.f90.
References bbuf_ucd, binary_io::close_binary_file(), itmp1_mp, m_constants::izero, binary_io::open_read_binary_file(), read_udt_from_bindary_data::read_alloc_psf_bin_field_data(), read_udt_from_bindary_data::read_alloc_psf_bin_grid_data(), and binary_io::read_one_integer_b().
read_alloc_nostep_psf_bin_file()
subroutine read_psf_binary_file::read_alloc_nostep_psf_bin_file (character(len = kchara), intent(in) file_name, integer, intent(in) nprocs, type(ucd_data), intent(inout) ucd_b)
Definition at line 131 of file read_psf_binary_file.f90.
References bbuf_ucd, binary_io::close_binary_file(), itmp1_mp, m_constants::izero, binary_io::open_read_binary_file(), read_udt_from_bindary_data::read_alloc_psf_bin_field_data(), and binary_io::read_one_integer_b().
read_alloc_psf_bin_file()
subroutine read_psf_binary_file::read_alloc_psf_bin_file (character(len = kchara), intent(in) file_name, integer, intent(in) nprocs, type(time_data), intent(inout) t_IO, type(ucd_data), intent(inout) ucd_b)
Definition at line 72 of file read_psf_binary_file.f90.
References bbuf_ucd, binary_io::close_binary_file(), itmp1_mp, m_constants::izero, binary_io::open_read_binary_file(), read_udt_from_bindary_data::read_alloc_psf_bin_field_data(), and read_udt_from_bindary_data::read_psf_bin_time_data().
Referenced by ucd_io_select::sel_read_alloc_ucd_file(), ucd_io_select::sel_read_alloc_udt_file(), and ucd_io_select::sel_read_udt_param().
read_alloc_psf_bin_grid()
subroutine read_psf_binary_file::read_alloc_psf_bin_grid (character(len = kchara), intent(in) file_name, integer, intent(inout) nprocs, type(ucd_data), intent(inout) ucd_b)
Definition at line 48 of file read_psf_binary_file.f90.
References bbuf_ucd, binary_io::close_binary_file(), itmp1_mp, m_constants::izero, binary_io::open_read_binary_file(), read_udt_from_bindary_data::read_alloc_psf_bin_grid_data(), and binary_io::read_one_integer_b().
Referenced by ucd_io_select::sel_read_alloc_ucd_file().
read_iso_bin_file()
subroutine read_psf_binary_file::read_iso_bin_file (character(len = kchara), intent(in) file_name, type(time_data), intent(inout) t_IO, type(ucd_data), intent(inout) ucd_b)
Definition at line 242 of file read_psf_binary_file.f90.
References bbuf_ucd, binary_io::close_binary_file(), itmp1_mp, m_constants::izero, binary_io::open_read_binary_file(), binary_io::read_one_integer_b(), read_udt_from_bindary_data::read_psf_bin_field_data(), read_udt_from_bindary_data::read_psf_bin_grid_data(), and read_udt_from_bindary_data::read_psf_bin_time_data().
Referenced by ucd_io_select::sel_read_ucd_file().
read_psf_bin_file()
subroutine read_psf_binary_file::read_psf_bin_file (character(len = kchara), intent(in) file_name, integer, intent(in) nprocs, type(time_data), intent(inout) t_IO, type(ucd_data), intent(inout) ucd_b)
Definition at line 215 of file read_psf_binary_file.f90.
References binary_io::close_binary_file(), itmp1_mp, m_constants::izero, binary_io::open_read_binary_file(), read_udt_from_bindary_data::read_psf_bin_field_data(), and read_udt_from_bindary_data::read_psf_bin_time_data().
Referenced by ucd_io_select::sel_read_ucd_file(), and ucd_io_select::sel_read_udt_file().
read_psf_bin_grid()
subroutine read_psf_binary_file::read_psf_bin_grid (character(len = kchara), intent(in) file_name, integer, intent(inout) nprocs, type(ucd_data), intent(inout) ucd_b)
Definition at line 192 of file read_psf_binary_file.f90.
References bbuf_ucd, binary_io::close_binary_file(), itmp1_mp, m_constants::izero, binary_io::open_read_binary_file(), binary_io::read_one_integer_b(), and read_udt_from_bindary_data::read_psf_bin_grid_data().
Referenced by ucd_io_select::sel_read_ucd_file().
Variable Documentation
bbuf_ucd
type(binary_io_buffer), save, private read_psf_binary_file::bbuf_ucd private
Definition at line 39 of file read_psf_binary_file.f90.
Referenced by read_alloc_iso_bin_file(), read_alloc_nostep_iso_bin_file(), read_alloc_nostep_psf_bin_file(), read_alloc_psf_bin_file(), read_alloc_psf_bin_grid(), read_iso_bin_file(), and read_psf_bin_grid().
itmp1_mp
integer(kind = kint_gl), dimension(:), allocatable, private read_psf_binary_file::itmp1_mp private
Definition at line 40 of file read_psf_binary_file.f90.
Referenced by read_alloc_iso_bin_file(), read_alloc_nostep_iso_bin_file(), read_alloc_nostep_psf_bin_file(), read_alloc_psf_bin_file(), read_alloc_psf_bin_grid(), read_iso_bin_file(), read_psf_bin_file(), and read_psf_bin_grid().