CALYPSO: gz_rst_data_io_by_fld Module Reference
gz_rst_data_io_by_fld Module Reference
read gzipped restart file
Functions/Subroutines
subroutine read_gz_rst_file (id_rank, file_name, t_IO, fld_IO, ierr_IO)
subroutine read_gz_rst_comps (id_rank, file_name, t_IO, fld_IO, ierr_IO)
subroutine, private read_gz_rst_field_comps (fld_IO, zbuf)
Variables
type(buffer_4_gzip), private zbuf_r
Detailed Description
read gzipped restart file
      subroutine read_gz_rst_file                                     &
     &         (id_rank, file_name, t_IO, fld_IO, ierr_IO)
      subroutine read_gz_rst_comps                                    &
     &          (id_rank, file_name, t_IO, fld_IO, ierr_IO)
        type(time_data), intent(inout) :: t_IO
        type(field_IO), intent(inout) :: fld_IO
Function/Subroutine Documentation
read_gz_rst_comps()
subroutine gz_rst_data_io_by_fld::read_gz_rst_comps (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO, integer(kind=kint), intent(inout) ierr_IO)
Definition at line 79 of file gz_rst_data_IO_by_fld.f90.
References set_parallel_file_name::add_gzip_extension(), t_field_data_io::alloc_phys_name_io(), t_field_data_io::cal_istack_phys_comp_io(), skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_rd_gzfile_a(), read_gz_rst_field_comps(), gz_field_data_io::read_gz_step_data(), skip_gz_comment::skip_gz_comment_int(), and zbuf_r.
Referenced by input_old_file_sel_4_zlib::sel_read_rst_comps().
read_gz_rst_field_comps()
subroutine, private gz_rst_data_io_by_fld::read_gz_rst_field_comps (type(field_io), intent(inout) fld_IO, type(buffer_4_gzip), intent(inout) zbuf) private
Definition at line 120 of file gz_rst_data_IO_by_fld.f90.
References gzip_file_access::get_one_line_text_from_gz(), set_restart_data::set_num_comps_4_rst(), and skip_gz_comment::skip_gz_comment_chara().
Referenced by read_gz_rst_comps().
read_gz_rst_file()
subroutine gz_rst_data_io_by_fld::read_gz_rst_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO, integer(kind=kint), intent(inout) ierr_IO)
Definition at line 41 of file gz_rst_data_IO_by_fld.f90.
References set_parallel_file_name::add_gzip_extension(), transfer_to_long_integers::cast_long(), skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_rd_gzfile_a(), gz_field_data_io::read_gz_field_data(), gz_field_data_io::read_gz_step_data(), skip_gz_comment::skip_gz_comment_int(), and zbuf_r.
Referenced by input_old_file_sel_4_zlib::sel_read_rst_file().
Variable Documentation
zbuf_r
type(buffer_4_gzip), private gz_rst_data_io_by_fld::zbuf_r private
Definition at line 31 of file gz_rst_data_IO_by_fld.f90.
Referenced by read_gz_rst_comps(), and read_gz_rst_file().