CALYPSO: solver_sr_type Module Reference
solver_sr_type Module Reference
Data communication using communication table structure.
Functions/Subroutines
subroutine solver_send_recv_type (NP, comm_tbl, X)
subroutine solver_send_recv_3_type (NP, comm_tbl, X)
subroutine solver_send_recv_6_type (NP, comm_tbl, X)
subroutine solver_send_recv_n_type (NP, NB, comm_tbl, X)
subroutine solver_send_recv_1x3_type (NP, comm_tbl, X1, X2, X3)
subroutine solver_send_recv_3x3_type (NP, comm_tbl, X1, X2, X3)
subroutine solver_send_recv_nx3_type (NP, NB, comm_tbl, X1, X2, X3)
subroutine solver_send_recv_int_type (NP, comm_tbl, iX)
subroutine solver_send_recv_int8_type (NP, comm_tbl, i8X)
subroutine solver_send_recv_num_type (comm_tbl, nSEND, nRECV)
Variables
logical, save, private iflag_f3d_time = .FALSE.
integer(kind=kint), save, private ist_elapsed_f3d = 0
integer(kind=kint), save, private ied_elapsed_f3d = 0
Detailed Description
Data communication using communication table structure.
      subroutine SOLVER_SEND_RECV_type(NP, comm_tbl, X)
      subroutine SOLVER_SEND_RECV_3_type(NP, comm_tbl, X)
      subroutine SOLVER_SEND_RECV_6_type(NP, comm_tbl, X)
      subroutine SOLVER_SEND_RECV_N_type(NP, NB, comm_tbl, X)
      subroutine SOLVER_SEND_RECV_1x3_type(NP, comm_tbl, X1, X2, X3)
      subroutine SOLVER_SEND_RECV_3x3_type(NP, comm_tbl, X1, X2, X3)
      subroutine SOLVER_SEND_RECV_Nx3_type                            &
     &         (NP, NB, comm_tbl, X1, X2, X3)
      subroutine SOLVER_SEND_RECV_int_type(NP, comm_tbl, iX)
      subroutine SOLVER_SEND_RECV_int8_type(NP, comm_tbl, i8X)
      subroutine SOLVER_SEND_RECV_num_type(comm_tbl, nSEND, nRECV)
        type(communication_table), intent(in) :: comm_tbl
        integer(kind = kint), intent(in) :: NP
        real(kind = kreal), intent(inout) :: X(NP)
        integer(kind = kint), intent(inout) :: iX(NP)
        integer(kind = kint_gl), intent(inout) :: i8X(NP)
        integer(kind = kint), intent(in) :: nSEND(comm_tbl%num_neib)
        integer(kind = kint), intent(inout) :: nRECV(comm_tbl%num_neib)
Function/Subroutine Documentation
solver_send_recv_1x3_type()
subroutine solver_sr_type::solver_send_recv_1x3_type (integer(kind = kint), intent(in) NP, type(communication_table), intent(in) comm_tbl, real(kind = kreal), dimension(np), intent(inout) X1, real(kind = kreal), dimension(np), intent(inout) X2, real(kind = kreal), dimension(np), intent(inout) X3)
Definition at line 152 of file solver_SR_type.f90.
References m_work_time::end_elapsed_time(), m_elapsed_labels_send_recv::iflag_fsr_time, m_elapsed_labels_send_recv::ist_elapsed_fsr, solver_sr::solver_send_recvx3(), m_solver_sr::sr_r1, m_solver_sr::sr_sig1, and m_work_time::start_elapsed_time().
solver_send_recv_3_type()
subroutine solver_sr_type::solver_send_recv_3_type (integer(kind = kint), intent(in) NP, type(communication_table), intent(in) comm_tbl, real(kind = kreal), dimension(3*np), intent(inout) X)
Definition at line 74 of file solver_SR_type.f90.
References m_work_time::end_elapsed_time(), m_elapsed_labels_send_recv::iflag_fsr_time, m_elapsed_labels_send_recv::ist_elapsed_fsr, solver_sr_3::solver_send_recv_3(), m_solver_sr::sr_r1, m_solver_sr::sr_sig1, and m_work_time::start_elapsed_time().
Referenced by const_global_element_ids::check_element_position(), and nod_phys_send_recv::nod_vector_send_recv().
solver_send_recv_3x3_type()
subroutine solver_sr_type::solver_send_recv_3x3_type (integer(kind = kint), intent(in) NP, type(communication_table), intent(in) comm_tbl, real(kind = kreal), dimension(3*np), intent(inout) X1, real(kind = kreal), dimension(3*np), intent(inout) X2, real(kind = kreal), dimension(3*np), intent(inout) X3)
Definition at line 178 of file solver_SR_type.f90.
References m_work_time::end_elapsed_time(), m_elapsed_labels_send_recv::iflag_fsr_time, m_elapsed_labels_send_recv::ist_elapsed_fsr, solver_sr_3::solver_send_recv_3x3(), m_solver_sr::sr_r1, m_solver_sr::sr_sig1, and m_work_time::start_elapsed_time().
solver_send_recv_6_type()
subroutine solver_sr_type::solver_send_recv_6_type (integer(kind = kint), intent(in) NP, type(communication_table), intent(in) comm_tbl, real(kind = kreal), dimension(6*np), intent(inout) X)
Definition at line 98 of file solver_SR_type.f90.
References m_work_time::end_elapsed_time(), m_elapsed_labels_send_recv::iflag_fsr_time, m_elapsed_labels_send_recv::ist_elapsed_fsr, solver_sr_6::solver_send_recv_6(), m_solver_sr::sr_r1, m_solver_sr::sr_sig1, and m_work_time::start_elapsed_time().
Referenced by nod_phys_send_recv::nod_tensor_send_recv().
solver_send_recv_int8_type()
subroutine solver_sr_type::solver_send_recv_int8_type (integer(kind = kint), intent(in) NP, type(communication_table), intent(in) comm_tbl, integer(kind = kint_gl), dimension(np), intent(inout) i8X)
Definition at line 262 of file solver_SR_type.f90.
References m_work_time::end_elapsed_time(), m_elapsed_labels_send_recv::iflag_fsr_time, m_elapsed_labels_send_recv::ist_elapsed_fsr, solver_sr_int8::solver_send_recv_i8(), m_solver_sr::sr_il1, m_solver_sr::sr_sig1, and m_work_time::start_elapsed_time().
Referenced by psf_global_nod_id::psf_global_nod_id_on_edge(), psf_global_nod_id::psf_global_nod_id_on_node(), and const_global_element_ids::set_global_ele_id().
solver_send_recv_int_type()
subroutine solver_sr_type::solver_send_recv_int_type (integer(kind = kint), intent(in) NP, type(communication_table), intent(in) comm_tbl, integer(kind = kint), dimension(np), intent(inout) iX)
Definition at line 237 of file solver_SR_type.f90.
References m_work_time::end_elapsed_time(), m_elapsed_labels_send_recv::iflag_fsr_time, m_elapsed_labels_send_recv::ist_elapsed_fsr, solver_sr_int::solver_send_recv_i(), m_solver_sr::sr_i1, m_solver_sr::sr_sig1, and m_work_time::start_elapsed_time().
Referenced by t_para_double_numbering::set_para_double_numbering(), and t_para_double_numbering::set_para_ele_double_numbering().
solver_send_recv_n_type()
subroutine solver_sr_type::solver_send_recv_n_type (integer(kind = kint), intent(in) NP, integer(kind = kint), intent(in) NB, type(communication_table), intent(in) comm_tbl, real(kind = kreal), dimension(nb*np), intent(inout) X)
Structure of communication flags
Structure of communication buffer for 8-byte real
Definition at line 122 of file solver_SR_type.f90.
References m_work_time::end_elapsed_time(), m_elapsed_labels_send_recv::iflag_fsr_time, m_elapsed_labels_send_recv::ist_elapsed_fsr, solver_sr_n::solver_send_recv_n(), m_solver_sr::sr_r1, m_solver_sr::sr_sig1, and m_work_time::start_elapsed_time().
solver_send_recv_num_type()
subroutine solver_sr_type::solver_send_recv_num_type (type(communication_table), intent(in) comm_tbl, integer(kind = kint), dimension(comm_tbl%num_neib), intent(in) nSEND, integer(kind = kint), dimension(comm_tbl%num_neib), intent(inout) nRECV)
Definition at line 287 of file solver_SR_type.f90.
References m_work_time::end_elapsed_time(), m_elapsed_labels_send_recv::iflag_fsr_time, m_elapsed_labels_send_recv::ist_elapsed_fsr, solver_sr_int::solver_send_recv_num(), m_solver_sr::sr_sig1, and m_work_time::start_elapsed_time().
solver_send_recv_nx3_type()
subroutine solver_sr_type::solver_send_recv_nx3_type (integer(kind = kint), intent(in) NP, integer(kind = kint), intent(in) NB, type(communication_table), intent(in) comm_tbl, real(kind = kreal), dimension(nb*np), intent(inout) X1, real(kind = kreal), dimension(nb*np), intent(inout) X2, real(kind = kreal), dimension(nb*np), intent(inout) X3)
Structure of communication flags
Structure of communication buffer for 8-byte real
Definition at line 204 of file solver_SR_type.f90.
References m_work_time::end_elapsed_time(), m_elapsed_labels_send_recv::iflag_fsr_time, m_elapsed_labels_send_recv::ist_elapsed_fsr, solver_sr_n::solver_send_recv_nx3(), m_solver_sr::sr_r1, m_solver_sr::sr_sig1, and m_work_time::start_elapsed_time().
solver_send_recv_type()
subroutine solver_sr_type::solver_send_recv_type (integer(kind = kint), intent(in) NP, type(communication_table), intent(in) comm_tbl, real(kind = kreal), dimension(np), intent(inout) X)
Definition at line 50 of file solver_SR_type.f90.
References m_work_time::end_elapsed_time(), m_elapsed_labels_send_recv::iflag_fsr_time, m_elapsed_labels_send_recv::ist_elapsed_fsr, solver_sr::solver_send_recv(), m_solver_sr::sr_r1, m_solver_sr::sr_sig1, and m_work_time::start_elapsed_time().
Referenced by nod_phys_send_recv::nod_scalar_send_recv().
Variable Documentation
ied_elapsed_f3d
integer(kind = kint), save, private solver_sr_type::ied_elapsed_f3d = 0 private
Definition at line 42 of file solver_SR_type.f90.
iflag_f3d_time
logical, save, private solver_sr_type::iflag_f3d_time = .FALSE. private
Definition at line 40 of file solver_SR_type.f90.
ist_elapsed_f3d
integer(kind = kint), save, private solver_sr_type::ist_elapsed_f3d = 0 private
Definition at line 41 of file solver_SR_type.f90.