CALYPSO: cal_self_buoyancies_sph Module Reference
cal_self_buoyancies_sph Module Reference
Evaluate divergence of buoyancy for pressure evaluation.
Functions/Subroutines
subroutine sel_buoyancies_sph_mhd (sph_rj, leg, ipol_base, ipol_frc, fl_prop, ref_param_T, ref_param_C, sph_bc_U, rj_fld)
subroutine cal_buoyancy_sph_mhd (kr_in, kr_out, g_sph_rj, coef, is_fld, is_buo, nidx_rj, radius_1d_rj_r, nnod_rj, ntot_phys_rj, d_rj)
Detailed Description
Evaluate divergence of buoyancy for pressure evaluation.
      subroutine sel_buoyancies_sph_MHD                               &
     &         (sph_rj, leg, ipol_base, ipol_frc,                     &
     &          fl_prop, ref_param_T, ref_param_C, sph_bc_U, rj_fld)
        type(legendre_4_sph_trans), intent(in) :: leg
        type(fluid_property), intent(in) :: fl_prop
        type(reference_scalar_param), intent(in) :: ref_param_T
        type(reference_scalar_param), intent(in) :: ref_param_C
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(base_field_address), intent(in) :: ipol_base
        type(base_force_address), intent(in) :: ipol_frc
        type(sph_boundary_type), intent(in) :: sph_bc_U
        type(phys_data), intent(inout) :: rj_fld
      subroutine cal_buoyancy_sph_MHD(kr_in, kr_out, g_sph_rj, coef,  &
     &          is_fld, is_buo, nidx_rj, radius_1d_rj_r,              &
     &          nnod_rj, ntot_phys_rj, d_rj)
Parameters
sph_bc_U Structure for basic velocity boundary condition parameters
Function/Subroutine Documentation
cal_buoyancy_sph_mhd()
subroutine cal_self_buoyancies_sph::cal_buoyancy_sph_mhd (integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) kr_out, real(kind = kreal), dimension(nidx_rj(2),17), intent(in) g_sph_rj, real(kind = kreal), intent(in) coef, integer(kind= kint), intent(in) is_fld, integer(kind= kint), intent(in) is_buo, integer(kind = kint), dimension(2), intent(in) nidx_rj, real(kind = kreal), dimension(nidx_rj(1)), intent(in) radius_1d_rj_r, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 117 of file cal_self_buoyancies_sph.f90.
Referenced by sel_buoyancies_sph_mhd().
sel_buoyancies_sph_mhd()
subroutine cal_self_buoyancies_sph::sel_buoyancies_sph_mhd (type(sph_rj_grid), intent(in) sph_rj, type(legendre_4_sph_trans), intent(in) leg, type(base_field_address), intent(in) ipol_base, type(base_force_address), intent(in) ipol_frc, type(fluid_property), intent(in) fl_prop, type(reference_scalar_param), intent(in) ref_param_T, type(reference_scalar_param), intent(in) ref_param_C, type(sph_boundary_type), intent(in) sph_bc_U, type(phys_data), intent(inout) rj_fld)
Definition at line 46 of file cal_self_buoyancies_sph.f90.
References cal_buoyancy_sph_mhd(), adjust_reference_fields::delete_sphere_average(), t_reference_scalar_param::id_sphere_ref_temp, t_reference_scalar_param::id_takepiro_temp, and m_machine_parameter::iflag_debug.
Referenced by lead_fields_4_sph_mhd::s_lead_fields_4_sph_mhd().