CALYPSO: coef_fdm2_to_center Module Reference
coef_fdm2_to_center Module Reference
Matrix to evaluate radial derivative toward center.
Functions/Subroutines
subroutine cal_2nd_to_center_fixed_fdm (radius, fdm2_center)
subroutine cal_2nd_center_fix_df_fdm (radius, fdm2_center)
subroutine cal_2nd_center_fixed_fdm (radius, fdm2_center)
Variables
real(kind=kreal), dimension(3, 3), private mat_fdm_ctr_fix_2
Work matrix to evaluate fdm2_centerdmat_fix_fld(-1:1,3)
real(kind=kreal), dimension(3, 3), private mat_fdm_ctr_fix_dr_2
Work matrix to evaluate fdm2_centerdmat_fix_dr(-1:1,3)
real(kind=kreal), dimension(3, 3), private mat_fdm_ctr_fixed_2
Work matrix to evaluate fdm2_centerdmat_fixed(-1:1,3)
Detailed Description
Matrix to evaluate radial derivative toward center.
      subroutine cal_2nd_to_center_fixed_fdm(radius, fdm2_center)
      subroutine cal_2nd_center_fix_df_fdm(radius, fdm2_center)
      subroutine cal_2nd_center_fixed_fdm(radius, fdm2_center)
        type(fdm2_center_mat), intent(inout) :: fdm2_center
   Matrix for derivatives with fixed field
      dfdr =      fdm2_center%dmat_fix_fld(-1,2) * d_center(0)
                + fdm2_center%dmat_fix_fld( 0,2) * d_rj(1)
                + fdm2_center%dmat_fix_fld( 1,2) * d_rj(2)
      d2fdr2 =    fdm2_center%dmat_fix_fld(-1,3) * d_center(0)
                + fdm2_center%dmat_fix_fld( 0,3) * d_rj(1)
                + fdm2_center%dmat_fix_fld( 1,3) * d_rj(2)
      Matrix to evaluate field at center fixed radial derivative
      (Only used for l = m = 0 component of scalar)
      d_center(0) =fdm2_center%dmat_fix_dr(-1,1) * dfdr(0)
                 + fdm2_center%dmat_fix_dr( 0,1) * d_center(0)
                 + fdm2_center%dmat_fix_dr( 1,1) * d_rj(1)
      d2fdr2(0) =  fdm2_center%dmat_fix_dr(-1,3) * dfdr(0)
                 + fdm2_center%dmat_fix_dr( 0,3) * d_center(0)
                 + fdm2_center%dmat_fix_dr( 1,3) * d_rj(1)
      Matrix to evaluate field at center fixed field
      (Only used for l = m = 0 component of scalar)
      dfdr(0) =    fdm2_center%dmat_fixed( 0,2) * d_center(0)
                 + fdm2_center%dmat_fixed( 1,2) * d_rj(1)
                 + fdm2_center%dmat_fixed( 2,2) * d_rj(2)
      d2fdr2(0) =  fdm2_center%dmat_fixed( 0,3) * d_center(0)
                 + fdm2_center%dmat_fixed( 1,3) * d_rj(1)
                 + fdm2_center%dmat_fixed( 2,3) * d_rj(2)
Parameters
radius(1:2) radius at two innermost grids
Function/Subroutine Documentation
cal_2nd_center_fix_df_fdm()
subroutine coef_fdm2_to_center::cal_2nd_center_fix_df_fdm (real(kind = kreal), intent(in) radius, type(fdm2_center_mat), intent(inout) fdm2_center)
Definition at line 137 of file coef_fdm2_to_center.f90.
References cal_inverse_small_matrix::cal_inverse_33_matrix(), mat_fdm_ctr_fix_dr_2, m_constants::one, m_constants::two, and m_constants::zero.
Referenced by set_bc_sph_mhd::s_set_bc_sph_mhd().
cal_2nd_center_fixed_fdm()
subroutine coef_fdm2_to_center::cal_2nd_center_fixed_fdm (real(kind = kreal), dimension(2), intent(in) radius, type(fdm2_center_mat), intent(inout) fdm2_center)
Definition at line 173 of file coef_fdm2_to_center.f90.
References cal_inverse_small_matrix::cal_inverse_33_matrix(), mat_fdm_ctr_fixed_2, m_constants::one, m_constants::two, and m_constants::zero.
Referenced by set_bc_sph_mhd::s_set_bc_sph_mhd().
cal_2nd_to_center_fixed_fdm()
subroutine coef_fdm2_to_center::cal_2nd_to_center_fixed_fdm (real(kind = kreal), dimension(2), intent(in) radius, type(fdm2_center_mat), intent(inout) fdm2_center)
Definition at line 98 of file coef_fdm2_to_center.f90.
References cal_inverse_small_matrix::cal_inverse_33_matrix(), mat_fdm_ctr_fix_2, m_constants::one, m_constants::two, and m_constants::zero.
Referenced by set_bc_sph_mhd::s_set_bc_sph_mhd().
Variable Documentation
mat_fdm_ctr_fix_2
real(kind = kreal), dimension(3,3), private coef_fdm2_to_center::mat_fdm_ctr_fix_2 private
Work matrix to evaluate fdm2_centerdmat_fix_fld(-1:1,3)
      dfdr =      mat_fdm_ctr_fix_2(2,1) * d_center(0)
                + mat_fdm_ctr_fix_2(2,2) * d_rj(1)
                + mat_fdm_ctr_fix_2(2,3) * d_rj(2)
      d2fdr2 =    mat_fdm_ctr_fix_2(3,1) * d_center(0)
                + mat_fdm_ctr_fix_2(3,2) * d_rj(1)
                + mat_fdm_ctr_fix_2(3,3) * d_rj(2)
Definition at line 65 of file coef_fdm2_to_center.f90.
Referenced by cal_2nd_to_center_fixed_fdm().
mat_fdm_ctr_fix_dr_2
real(kind = kreal), dimension(3,3), private coef_fdm2_to_center::mat_fdm_ctr_fix_dr_2 private
Work matrix to evaluate fdm2_centerdmat_fix_dr(-1:1,3)
      dfdr =     mat_fdm_ctr_fix_dr_2(2,1) * d_center(0)
               + mat_fdm_ctr_fix_dr_2(2,2) * dfdr(0)
               + mat_fdm_ctr_fix_dr_2(2,3) * d_rj(1)
      d2fdr2 =   mat_fdm_ctr_fix_dr_2(3,1) * d_center(0)
               + mat_fdm_ctr_fix_dr_2(3,2) * dfdr(0)
               + mat_fdm_ctr_fix_dr_2(3,3) * d_rj(1)
Definition at line 76 of file coef_fdm2_to_center.f90.
Referenced by cal_2nd_center_fix_df_fdm().
mat_fdm_ctr_fixed_2
real(kind = kreal), dimension(3,3), private coef_fdm2_to_center::mat_fdm_ctr_fixed_2 private
Work matrix to evaluate fdm2_centerdmat_fixed(-1:1,3)
      dfdr =     mat_fdm_ctr_fixed_2(2,1) * d_center(0)
               + mat_fdm_ctr_fixed_2(2,2) * d_rj(0)
               + mat_fdm_ctr_fixed_2(2,3) * d_rj(2)
      d2fdr2 =   mat_fdm_ctr_fixed_2(3,1) * d_center(0)
               + mat_fdm_ctr_fixed_2(3,2) * d_rj(0)
               + mat_fdm_ctr_fixed_2(3,3) * d_rj(2)
Definition at line 87 of file coef_fdm2_to_center.f90.
Referenced by cal_2nd_center_fixed_fdm().