CALYPSO: t_sph_boundary_input_data Module Reference
t_sph_boundary_input_data Module Reference
Boundary condition data from external file.
Data Types
type boundary_spectra
Functions/Subroutines
subroutine, private alloc_sph_bc_item_ctl (bc_IO)
subroutine dealloc_sph_bc_item_ctl (bc_IO)
subroutine bcast_boundary_spectr_file (bc_IO)
subroutine read_boundary_spectr_file (bc_IO)
subroutine write_boundary_spectr_file (bc_IO)
Variables
integer(kind=kint), parameter, private id_boundary_file = 41
File ID for boundary condition file.
Detailed Description
Boundary condition data from external file.
      subroutine dealloc_sph_bc_item_ctl(bc_IO)
      subroutine bcast_boundary_spectr_file(bc_IO)
        type(boundary_spectra), intent(inout) :: bc_IO
      subroutine read_boundary_spectr_file(bc_IO)
        type(boundary_spectra), intent(inout) :: bc_IO
      subroutine write_boundary_spectr_file(bc_IO)
        type(boundary_spectra), intent(in) :: bc_IO
  ---------------------------------------------------------------------
      Data format
       line 1:  Number of total boundary conditions to be defined
       line 2:     Field name to define the first boundary condition
       line 3:     Place to define the first boundary condition
       line 4:     Number of spherical harmonics modes
                    for each boundary condition
       line 5...:  Spectrum data for the boundary conditions
                  (degree $l$, order $m$, and harmonics coefficients)
        Return to 2...
  ---------------------------------------------------------------------
Parameters
field_name Field name to be define the boundary condition by file
ref_grp Boundary group name to be defined the boundary condition by file
bc_data(sph_rj%nidx_rj(2)) Local boundary condition spectrum
iflag_bc_scalar Boundary condition type flag
Function/Subroutine Documentation
alloc_sph_bc_item_ctl()
subroutine, private t_sph_boundary_input_data::alloc_sph_bc_item_ctl (type(boundary_spectra), intent(inout) bc_IO) private
Definition at line 70 of file t_sph_boundary_input_data.f90.
Referenced by bcast_boundary_spectr_file(), and read_boundary_spectr_file().
bcast_boundary_spectr_file()
subroutine t_sph_boundary_input_data::bcast_boundary_spectr_file (type(boundary_spectra), intent(inout) bc_IO)
Definition at line 99 of file t_sph_boundary_input_data.f90.
References t_each_sph_boundary_io_data::alloc_each_bc_item_ctl(), alloc_sph_bc_item_ctl(), t_each_sph_boundary_io_data::bcast_each_bc_item_ctl(), t_each_sph_boundary_io_data::bcast_each_bc_item_num(), calypso_mpi::calypso_mpi_barrier(), calypso_mpi_int::calypso_mpi_bcast_one_int(), and calypso_mpi::my_rank.
Referenced by set_control_4_sph_to_fem::sph_boundary_io_control().
dealloc_sph_bc_item_ctl()
subroutine t_sph_boundary_input_data::dealloc_sph_bc_item_ctl (type(boundary_spectra), intent(inout) bc_IO)
Definition at line 83 of file t_sph_boundary_input_data.f90.
References t_each_sph_boundary_io_data::dealloc_each_bc_item_ctl().
read_boundary_spectr_file()
subroutine t_sph_boundary_input_data::read_boundary_spectr_file (type(boundary_spectra), intent(inout) bc_IO)
Definition at line 126 of file t_sph_boundary_input_data.f90.
References alloc_sph_bc_item_ctl(), id_boundary_file, m_machine_parameter::iflag_debug, t_each_sph_boundary_io_data::read_each_boundary_spectr(), and skip_comment_f::skip_comment().
Referenced by set_control_4_sph_to_fem::sph_boundary_io_control().
write_boundary_spectr_file()
subroutine t_sph_boundary_input_data::write_boundary_spectr_file (type(boundary_spectra), intent(in) bc_IO)
Definition at line 156 of file t_sph_boundary_input_data.f90.
References id_boundary_file, and t_each_sph_boundary_io_data::write_each_boundary_spectr().
Variable Documentation
id_boundary_file
integer(kind = kint), parameter, private t_sph_boundary_input_data::id_boundary_file = 41 private
File ID for boundary condition file.
Definition at line 49 of file t_sph_boundary_input_data.f90.
Referenced by read_boundary_spectr_file(), and write_boundary_spectr_file().