CALYPSO: set_mesh_extensions Module Reference
set_mesh_extensions Module Reference
Set file extension.
Functions/Subroutines
character(len=kchara) function add_fld_extension (file_head)
character(len=kchara) function add_flb_extension (file_head)
character(len=kchara) function add_gfm_extension (file_head)
character(len=kchara) function add_gfb_extension (file_head)
character(len=kchara) function add_ksm_extension (file_head)
character(len=kchara) function add_itp_extension (file_head)
character(len=kchara) function add_itb_extension (file_head)
character(len=kchara) function add_gel_extension (file_head)
character(len=kchara) function add_gsf_extension (file_head)
character(len=kchara) function add_ged_extension (file_head)
character(len=kchara) function add_elb_extension (file_head)
character(len=kchara) function add_sfb_extension (file_head)
character(len=kchara) function add_edb_extension (file_head)
Variables
character(len=3), parameter, private fld_ext = "fld"
character(len=3), parameter, private flb_ext = "flb"
character(len=3), parameter, private gfm_ext = "gfm"
character(len=3), parameter, private gfb_ext = "gfb"
character(len=3), parameter, private ksm_ext = "ksm"
character(len=3), parameter, private itp_ext = "itp"
character(len=3), parameter, private itb_ext = "itb"
character(len=3), parameter, private gel_ext = "gel"
character(len=3), parameter, private gsf_ext = "gsf"
character(len=3), parameter, private ged_ext = "ged"
character(len=3), parameter, private elb_ext = "elb"
character(len=3), parameter, private sfb_ext = "sfb"
character(len=3), parameter, private edb_ext = "edb"
Detailed Description
Set file extension.
      character(len=kchara) function add_fld_extension(file_header)
                put ".fld" at the end
      character(len=kchara) function add_flb_extension(file_head)
                put ".flb" at the end
      character(len=kchara) function add_gfm_extension(file_head)
                put ".gfm" at the end
      character(len=kchara) function add_gfb_extension(file_head)
                put ".gfb" at the end
      character(len=kchara) function add_ksm_extension(file_head)
                put ".ksm" at the end
      character(len=kchara) function add_itp_extension(file_head)
                put ".itp" at the end
      character(len=kchara) function add_itb_extension(file_head)
                put ".itb" at the end
      character(len=kchara) function add_gel_extension(file_head)
                put ".gel" at the end
      character(len=kchara) function add_gsf_extension(file_head)
                put ".gsf" at the end
      character(len=kchara) function add_ged_extension(file_head)
                put ".ged" at the end
      character(len=kchara) function add_elb_extension(file_head)
                put ".elb" at the end
      character(len=kchara) function add_sfb_extension(file_head)
                put ".sfb" at the end
      character(len=kchara) function add_edb_extension(file_head)
                put ".edb" at the end
Parameters
dir_file_name file name (header) including directory name
int_id integer to be added at the end of prefix
int_val integer to be tranfered to character
int_string output character
Function/Subroutine Documentation
add_edb_extension()
character(len=kchara) function set_mesh_extensions::add_edb_extension (character(len=kchara), intent(in) file_head)
Definition at line 202 of file set_mesh_extensions.f90.
References set_parallel_file_name::add_3chara_extension(), and edb_ext.
Referenced by set_mesh_file_names::set_edge_mesh_file_name().
add_elb_extension()
character(len=kchara) function set_mesh_extensions::add_elb_extension (character(len=kchara), intent(in) file_head)
Definition at line 182 of file set_mesh_extensions.f90.
References set_parallel_file_name::add_3chara_extension(), and elb_ext.
Referenced by set_mesh_file_names::set_ele_comm_file_name().
add_flb_extension()
character(len=kchara) function set_mesh_extensions::add_flb_extension (character(len=kchara), intent(in) file_head)
Definition at line 88 of file set_mesh_extensions.f90.
References set_parallel_file_name::add_3chara_extension(), and flb_ext.
Referenced by set_field_file_names::set_fem_fld_file_name(), and set_ucd_file_names::set_parallel_ucd_file_name().
add_fld_extension()
character(len=kchara) function set_mesh_extensions::add_fld_extension (character(len=kchara), intent(in) file_head)
Definition at line 78 of file set_mesh_extensions.f90.
References set_parallel_file_name::add_3chara_extension(), and fld_ext.
Referenced by set_field_file_names::set_fem_fld_file_name(), set_ucd_file_names::set_parallel_ucd_file_name(), and set_ucd_file_names::set_single_ucd_file_name().
add_ged_extension()
character(len=kchara) function set_mesh_extensions::add_ged_extension (character(len=kchara), intent(in) file_head)
Definition at line 172 of file set_mesh_extensions.f90.
References set_parallel_file_name::add_3chara_extension(), and ged_ext.
Referenced by set_mesh_file_names::set_edge_mesh_file_name().
add_gel_extension()
character(len=kchara) function set_mesh_extensions::add_gel_extension (character(len=kchara), intent(in) file_head)
Definition at line 152 of file set_mesh_extensions.f90.
References set_parallel_file_name::add_3chara_extension(), and gel_ext.
Referenced by set_mesh_file_names::set_ele_comm_file_name().
add_gfb_extension()
character(len=kchara) function set_mesh_extensions::add_gfb_extension (character(len=kchara), intent(in) file_head)
Definition at line 109 of file set_mesh_extensions.f90.
References set_parallel_file_name::add_3chara_extension(), and gfb_ext.
Referenced by set_mesh_file_names::set_mesh_file_name().
add_gfm_extension()
character(len=kchara) function set_mesh_extensions::add_gfm_extension (character(len=kchara), intent(in) file_head)
Definition at line 99 of file set_mesh_extensions.f90.
References set_parallel_file_name::add_3chara_extension(), and gfm_ext.
Referenced by set_mesh_file_names::set_mesh_file_name().
add_gsf_extension()
character(len=kchara) function set_mesh_extensions::add_gsf_extension (character(len=kchara), intent(in) file_head)
Definition at line 162 of file set_mesh_extensions.f90.
References set_parallel_file_name::add_3chara_extension(), and gsf_ext.
Referenced by set_mesh_file_names::set_surf_mesh_file_name().
add_itb_extension()
character(len=kchara) function set_mesh_extensions::add_itb_extension (character(len=kchara), intent(in) file_head)
Definition at line 141 of file set_mesh_extensions.f90.
References set_parallel_file_name::add_3chara_extension(), and itb_ext.
add_itp_extension()
character(len=kchara) function set_mesh_extensions::add_itp_extension (character(len=kchara), intent(in) file_head)
Definition at line 131 of file set_mesh_extensions.f90.
References set_parallel_file_name::add_3chara_extension(), and itp_ext.
add_ksm_extension()
character(len=kchara) function set_mesh_extensions::add_ksm_extension (character(len=kchara), intent(in) file_head)
Definition at line 120 of file set_mesh_extensions.f90.
References set_parallel_file_name::add_3chara_extension(), and ksm_ext.
Referenced by viewer_mesh_mpi_io_select::sel_mpi_output_surface_grid(), and viewer_file_io::sel_output_single_surface_grid().
add_sfb_extension()
character(len=kchara) function set_mesh_extensions::add_sfb_extension (character(len=kchara), intent(in) file_head)
Definition at line 192 of file set_mesh_extensions.f90.
References set_parallel_file_name::add_3chara_extension(), and sfb_ext.
Referenced by set_mesh_file_names::set_surf_mesh_file_name().
Variable Documentation
edb_ext
character(len=3), parameter, private set_mesh_extensions::edb_ext = "edb" private
Definition at line 70 of file set_mesh_extensions.f90.
Referenced by add_edb_extension().
elb_ext
character(len=3), parameter, private set_mesh_extensions::elb_ext = "elb" private
Definition at line 68 of file set_mesh_extensions.f90.
Referenced by add_elb_extension().
flb_ext
character(len=3), parameter, private set_mesh_extensions::flb_ext = "flb" private
Definition at line 55 of file set_mesh_extensions.f90.
Referenced by add_flb_extension().
fld_ext
character(len=3), parameter, private set_mesh_extensions::fld_ext = "fld" private
Definition at line 54 of file set_mesh_extensions.f90.
Referenced by add_fld_extension().
ged_ext
character(len=3), parameter, private set_mesh_extensions::ged_ext = "ged" private
Definition at line 67 of file set_mesh_extensions.f90.
Referenced by add_ged_extension().
gel_ext
character(len=3), parameter, private set_mesh_extensions::gel_ext = "gel" private
Definition at line 65 of file set_mesh_extensions.f90.
Referenced by add_gel_extension().
gfb_ext
character(len=3), parameter, private set_mesh_extensions::gfb_ext = "gfb" private
Definition at line 58 of file set_mesh_extensions.f90.
Referenced by add_gfb_extension().
gfm_ext
character(len=3), parameter, private set_mesh_extensions::gfm_ext = "gfm" private
Definition at line 57 of file set_mesh_extensions.f90.
Referenced by add_gfm_extension().
gsf_ext
character(len=3), parameter, private set_mesh_extensions::gsf_ext = "gsf" private
Definition at line 66 of file set_mesh_extensions.f90.
Referenced by add_gsf_extension().
itb_ext
character(len=3), parameter, private set_mesh_extensions::itb_ext = "itb" private
Definition at line 63 of file set_mesh_extensions.f90.
Referenced by add_itb_extension().
itp_ext
character(len=3), parameter, private set_mesh_extensions::itp_ext = "itp" private
Definition at line 62 of file set_mesh_extensions.f90.
Referenced by add_itp_extension().
ksm_ext
character(len=3), parameter, private set_mesh_extensions::ksm_ext = "ksm" private
Definition at line 60 of file set_mesh_extensions.f90.
Referenced by add_ksm_extension().
sfb_ext
character(len=3), parameter, private set_mesh_extensions::sfb_ext = "sfb" private
Definition at line 69 of file set_mesh_extensions.f90.
Referenced by add_sfb_extension().