CALYPSO: copy_nodal_fld_4_sph_trans Module Reference
copy_nodal_fld_4_sph_trans Module Reference
Copy spherical transform data to 1st FEM data.
Functions/Subroutines
subroutine copy_nod_scl_from_trans_wpole (sph_rtp, m_folding, ncomp_trans, i_trns, d_rtp, v_pole, i_field, node, nod_fld)
subroutine copy_nod_vec_from_trans_wpole (sph_rtp, m_folding, ncomp_trans, i_trns, d_rtp, v_pole, i_field, node, nod_fld)
subroutine copy_nod_tsr_from_trans_wpole (sph_rtp, m_folding, ncomp_trans, i_trns, d_rtp, v_pole, i_field, node, nod_fld)
subroutine copy_nod_scl_to_sph_trans (node, sph_rtp, nod_fld, i_field, d_rtp)
subroutine copy_nod_vec_to_sph_trans (node, sph_rtp, nod_fld, i_field, d_rtp)
subroutine copy_nod_tsr_to_sph_trans (node, sph_rtp, nod_fld, i_field, d_rtp)
Detailed Description
Copy spherical transform data to 1st FEM data.
      subroutine copy_nod_scl_from_trans_wpole(sph_rtp, m_folding,    &
     &          ncomp_trans, i_trns, d_rtp, v_pole, i_field,          &
     &          node, nod_fld)
      subroutine copy_nod_vec_from_trans_wpole(sph_rtp, m_folding,    &
     &          ncomp_trans, i_trns, d_rtp, v_pole, i_field,          &
     &          node, nod_fld)
      subroutine copy_nod_tsr_from_trans_wpole(sph_rtp, m_folding,    &
     &          ncomp_trans, i_trns, d_rtp, v_pole, i_field,          &
     &          node, nod_fld)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(node_data), intent(in) :: node
        type(phys_data),intent(inout) :: nod_fld
      subroutine copy_nod_scl_to_sph_trans                            &
     &         (node, sph_rtp, nod_fld, i_field, d_rtp)
      subroutine copy_nod_vec_to_sph_trans                            &
     &         (node, sph_rtp, nod_fld, i_field, d_rtp)
      subroutine copy_nod_tsr_to_sph_trans                            &
     &         (node, sph_rtp, nod_fld, i_field, d_rtp)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(node_data), intent(in) :: node
        type(phys_data),intent(in) :: nod_fld
Function/Subroutine Documentation
copy_nod_scl_from_trans_wpole()
subroutine copy_nodal_fld_4_sph_trans::copy_nod_scl_from_trans_wpole (type(sph_rtp_grid), intent(in) sph_rtp, integer(kind = kint), intent(in) m_folding, integer(kind = kint), intent(in) ncomp_trans, integer(kind = kint), intent(in) i_trns, real(kind = kreal), dimension(sph_rtp%nnod_rtp,ncomp_trans), intent(in) d_rtp, real(kind = kreal), dimension(sph_rtp%nnod_pole,ncomp_trans), intent(in) v_pole, integer(kind = kint), intent(in) i_field, type(node_data), intent(in) node, type(phys_data), intent(inout) nod_fld)
Definition at line 54 of file copy_nodal_fld_4_sph_trans.f90.
References copy_pole_field_sph_trans::copy_pole_scl_fld_from_trans(), and copy_field_4_sph_trans::copy_scalar_from_trans_smp().
Referenced by copy_fields_from_sph_trans::copy_scalar_from_snap_force(), and copy_fields_from_sph_trans::copy_scalar_from_snap_trans().
copy_nod_scl_to_sph_trans()
subroutine copy_nodal_fld_4_sph_trans::copy_nod_scl_to_sph_trans (type(node_data), intent(in) node, type(sph_rtp_grid), intent(in) sph_rtp, type(phys_data), intent(in) nod_fld, integer(kind = kint), intent(in) i_field, real(kind = kreal), dimension(sph_rtp%nnod_rtp), intent(inout) d_rtp)
Definition at line 166 of file copy_nodal_fld_4_sph_trans.f90.
References copy_field_4_sph_trans::copy_scalar_to_trans_smp().
copy_nod_tsr_from_trans_wpole()
subroutine copy_nodal_fld_4_sph_trans::copy_nod_tsr_from_trans_wpole (type(sph_rtp_grid), intent(in) sph_rtp, integer(kind = kint), intent(in) m_folding, integer(kind = kint), intent(in) ncomp_trans, integer(kind = kint), intent(in) i_trns, real(kind = kreal), dimension(sph_rtp%nnod_rtp,ncomp_trans), intent(in) d_rtp, real(kind = kreal), dimension(sph_rtp%nnod_pole,ncomp_trans), intent(in) v_pole, integer(kind = kint), intent(in) i_field, type(node_data), intent(in) node, type(phys_data), intent(inout) nod_fld)
Definition at line 125 of file copy_nodal_fld_4_sph_trans.f90.
References copy_pole_field_sph_trans::copy_pole_tsr_fld_from_trans(), copy_field_4_sph_trans::copy_tensor_from_trans_smp(), m_machine_parameter::np_smp, and cvt_sph_tensor_2_xyz_smp::overwrite_xyz_tensor_by_sph_smp().
Referenced by copy_fields_from_sph_trans::copy_tensor_from_snap_force(), and copy_fields_from_sph_trans::copy_tensor_from_snap_trans().
copy_nod_tsr_to_sph_trans()
subroutine copy_nodal_fld_4_sph_trans::copy_nod_tsr_to_sph_trans (type(node_data), intent(in) node, type(sph_rtp_grid), intent(in) sph_rtp, type(phys_data), intent(in) nod_fld, integer(kind = kint), intent(in) i_field, real(kind = kreal), dimension(sph_rtp%nnod_rtp,6), intent(inout) d_rtp)
Definition at line 218 of file copy_nodal_fld_4_sph_trans.f90.
References copy_field_4_sph_trans::copy_tensor_to_trans_smp(), m_machine_parameter::np_smp, and cvt_xyz_tensor_2_sph_smp::overwrite_sph_tensor_smp().
copy_nod_vec_from_trans_wpole()
subroutine copy_nodal_fld_4_sph_trans::copy_nod_vec_from_trans_wpole (type(sph_rtp_grid), intent(in) sph_rtp, integer(kind = kint), intent(in) m_folding, integer(kind = kint), intent(in) ncomp_trans, integer(kind = kint), intent(in) i_trns, real(kind = kreal), dimension(sph_rtp%nnod_rtp,ncomp_trans), intent(in) d_rtp, real(kind = kreal), dimension(sph_rtp%nnod_pole,ncomp_trans), intent(in) v_pole, integer(kind = kint), intent(in) i_field, type(node_data), intent(in) node, type(phys_data), intent(inout) nod_fld)
Definition at line 86 of file copy_nodal_fld_4_sph_trans.f90.
References copy_pole_field_sph_trans::copy_pole_vec_fld_from_trans(), copy_field_4_sph_trans::copy_vector_from_trans_smp(), m_machine_parameter::np_smp, and cvt_sph_vector_2_xyz_smp::overwrite_sph_vect_2_xyz_smp().
Referenced by copy_fields_from_sph_trans::copy_vector_from_snap_force(), and copy_fields_from_sph_trans::copy_vector_from_snap_trans().
copy_nod_vec_to_sph_trans()
subroutine copy_nodal_fld_4_sph_trans::copy_nod_vec_to_sph_trans (type(node_data), intent(in) node, type(sph_rtp_grid), intent(in) sph_rtp, type(phys_data), intent(in) nod_fld, integer(kind = kint), intent(in) i_field, real(kind = kreal), dimension(sph_rtp%nnod_rtp,3), intent(inout) d_rtp)
Definition at line 188 of file copy_nodal_fld_4_sph_trans.f90.
References copy_field_4_sph_trans::copy_vector_to_trans_smp(), m_machine_parameter::np_smp, and cvt_xyz_vector_2_sph_smp::overwrite_vector_2_sph_smp().