CALYPSO: comm_table_io Module Reference
comm_table_io Module Reference
Routines for communcation table IO.
Functions/Subroutines
subroutine read_send_recv_item (id_file, ntot_sr, inod_sr)
subroutine read_send_recv_work (id_file, ntot_sr, nwork, inod_sr, idx_work)
subroutine write_send_recv_data (id_file, num_sr, ntot_sr, istack_sr, inod_sr)
subroutine write_send_recv_work (id_file, num_sr, ntot_sr, nwork, istack_sr, inod_sr, idx_work)
Variables
character(len=255), private character_4_read = ''
Detailed Description
Routines for communcation table IO.
      subroutine read_send_recv_item(id_file, ntot_sr, inod_sr)
      subroutine read_send_recv_work(id_file, ntot_sr, nwork,         &
     &          inod_sr, idx_work)
      subroutine write_send_recv_data(id_file, num_sr, ntot_sr,       &
     &          istack_sr, inod_sr)
      subroutine write_send_recv_work(id_file, num_sr, ntot_sr, nwork,&
     &          istack_sr, inod_sr, idx_work)
Function/Subroutine Documentation
read_send_recv_item()
subroutine comm_table_io::read_send_recv_item (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) ntot_sr, integer(kind = kint), dimension(ntot_sr), intent(inout) inod_sr)
Definition at line 34 of file comm_table_IO.f90.
References character_4_read, and skip_comment_f::skip_comment().
Referenced by domain_data_io::read_export_data(), and domain_data_io::read_import_data().
read_send_recv_work()
subroutine comm_table_io::read_send_recv_work (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) ntot_sr, integer(kind = kint), intent(in) nwork, integer(kind = kint), dimension(ntot_sr), intent(inout) inod_sr, integer(kind = kint), dimension(ntot_sr,nwork), intent(inout) idx_work)
Definition at line 54 of file comm_table_IO.f90.
References character_4_read, and skip_comment_f::skip_comment().
write_send_recv_data()
subroutine comm_table_io::write_send_recv_data (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) num_sr, integer(kind = kint), intent(in) ntot_sr, integer(kind = kint), dimension(0:num_sr), intent(in) istack_sr, integer(kind = kint), dimension(ntot_sr), intent(in) inod_sr)
Definition at line 78 of file comm_table_IO.f90.
Referenced by domain_data_io::write_export_data(), and domain_data_io::write_import_data().
write_send_recv_work()
subroutine comm_table_io::write_send_recv_work (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) num_sr, integer(kind = kint), intent(in) ntot_sr, integer(kind = kint), intent(in) nwork, integer(kind = kint), dimension(0:num_sr), intent(in) istack_sr, integer(kind = kint), dimension(ntot_sr), intent(in) inod_sr, integer(kind = kint), dimension(ntot_sr,nwork), intent(in) idx_work)
Definition at line 105 of file comm_table_IO.f90.
Variable Documentation
character_4_read
character(len=255), private comm_table_io::character_4_read = '' private
Definition at line 25 of file comm_table_IO.f90.
Referenced by read_send_recv_item(), and read_send_recv_work().