CALYPSO: set_special_sph_lm_flags Module Reference
set_special_sph_lm_flags Module Reference
Communication tables for spherical transform.
Functions/Subroutines
subroutine set_sph_rj_center_flag (nnod_rj, nidx_rj, inod_rj_center)
subroutine set_special_degree_order_flags (nidx_rj2, nidx_rlm2, idx_gl_1d_rj_j, idx_gl_1d_rlm_j, idx_rj_degree_zero, idx_rj_degree_one, ist_rtm_order_zero, ist_rtm_order_1s, ist_rtm_order_1c)
integer function find_local_rj_mode_address (jmax, idx_gl_1d_rj_j, l, m)
Detailed Description
Communication tables for spherical transform.
      subroutine set_sph_rj_center_flag                               &
     &         (nnod_rj, nidx_rj, inod_rj_center)
      subroutine set_special_degree_order_flags(nidx_rj2, nidx_rlm2,  &
     &          idx_gl_1d_rj_j, idx_gl_1d_rlm_j, idx_rj_degree_zero,  &
     &          idx_rj_degree_one, ist_rtm_order_zero,                &
     &          ist_rtm_order_1s, ist_rtm_order_1c)
      integer function find_local_rj_mode_address                     &
     &      (jmax, idx_gl_1d_rj_j, l, m)
Function/Subroutine Documentation
find_local_rj_mode_address()
integer function set_special_sph_lm_flags::find_local_rj_mode_address (integer(kind = kint), intent(in) jmax, integer(kind = kint), dimension(jmax,3), intent(in) idx_gl_1d_rj_j, integer(kind = kint), intent(in) l, integer(kind = kint), intent(in) m)
Definition at line 108 of file set_special_sph_lm_flags.f90.
Referenced by set_special_degree_order_flags().
set_special_degree_order_flags()
subroutine set_special_sph_lm_flags::set_special_degree_order_flags (integer (kind=kint), intent(in) nidx_rj2, integer (kind=kint), intent(in) nidx_rlm2, integer (kind=kint), dimension(nidx_rj2,3), intent(in) idx_gl_1d_rj_j, integer (kind=kint), dimension(nidx_rlm2,3), intent(in) idx_gl_1d_rlm_j, integer (kind=kint), intent(inout) idx_rj_degree_zero, integer (kind=kint), dimension(-1:1), intent(inout) idx_rj_degree_one, integer (kind=kint), intent(inout) ist_rtm_order_zero, integer (kind=kint), intent(inout) ist_rtm_order_1s, integer (kind=kint), intent(inout) ist_rtm_order_1c)
Definition at line 47 of file set_special_sph_lm_flags.f90.
References find_local_rj_mode_address(), m_constants::ione, and m_constants::izero.
Referenced by set_loaded_data_4_sph::set_index_flags_4_sph().
set_sph_rj_center_flag()
subroutine set_special_sph_lm_flags::set_sph_rj_center_flag (integer (kind=kint), intent(in) nnod_rj, integer (kind=kint), dimension(2), intent(in) nidx_rj, integer (kind=kint), intent(inout) inod_rj_center)
Definition at line 33 of file set_special_sph_lm_flags.f90.
Referenced by set_loaded_data_4_sph::set_index_flags_4_rj(), and set_loaded_data_4_sph::set_index_flags_4_sph().