CALYPSO: t_spheric_global_ranks Module Reference
t_spheric_global_ranks Module Reference
Global subdomain informatikn for spherical shell.
Data Types
type spheric_global_radius
type spheric_global_rank
Functions/Subroutines
subroutine alloc_radius_1d_gl (nri_gl, s3d_radius)
subroutine dealloc_radius_1d_gl (s3d_radius)
subroutine alloc_sph_ranks (s3d_ranks)
subroutine alloc_sph_1d_domain_id (sph_rtp, sph_rj, s3d_ranks)
subroutine dealloc_sph_ranks (s3d_ranks)
subroutine dealloc_sph_1d_domain_id (s3d_ranks)
subroutine check_sph_domains (nprocs_check, s3d_ranks, ierr, e_message)
subroutine check_sph_ranks (id_rank, s3d_ranks)
subroutine check_sph_1d_domain_id (sph_rtp, sph_rj, s3d_ranks)
Detailed Description
Global subdomain informatikn for spherical shell.
      subroutine alloc_radius_1d_gl(nri_gl, s3d_radius)
      subroutine dealloc_radius_1d_gl(s3d_radius)
        type(spheric_global_radius), intent(inout) :: s3d_radius
      subroutine alloc_sph_ranks(s3d_ranks)
      subroutine alloc_sph_1d_domain_id(sph_rtp, sph_rj, s3d_ranks)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_rj_grid), intent(in) :: sph_rj
      subroutine dealloc_sph_ranks(s3d_ranks)
      subroutine dealloc_sph_1d_domain_id(s3d_ranks)
      subroutine check_sph_domains                                    &
     &         (nprocs_check, s3d_ranks, ierr, e_message)
      subroutine check_sph_ranks(id_rank, nprocs_check)
      subroutine check_sph_1d_domain_id(nprocs_check)
Function/Subroutine Documentation
alloc_radius_1d_gl()
subroutine t_spheric_global_ranks::alloc_radius_1d_gl (integer(kind = kint), intent(in) nri_gl, type(spheric_global_radius), intent(inout) s3d_radius)
Definition at line 89 of file t_spheric_global_ranks.f90.
Referenced by const_sph_radial_grid::count_set_radial_grid(), and t_ctl_params_gen_sph_shell::set_ctl_radius_4_shell().
alloc_sph_1d_domain_id()
subroutine t_spheric_global_ranks::alloc_sph_1d_domain_id (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_rj_grid), intent(in) sph_rj, type(spheric_global_rank), intent(inout) s3d_ranks)
Definition at line 133 of file t_spheric_global_ranks.f90.
Referenced by const_global_sph_grids_modes::const_global_sph_fem_grid(), and const_global_sph_grids_modes::s_const_global_sph_grids_modes().
alloc_sph_ranks()
subroutine t_spheric_global_ranks::alloc_sph_ranks (type(spheric_global_rank), intent(inout) s3d_ranks)
Definition at line 114 of file t_spheric_global_ranks.f90.
Referenced by const_global_sph_grids_modes::const_global_sph_fem_grid(), and const_global_sph_grids_modes::s_const_global_sph_grids_modes().
check_sph_1d_domain_id()
subroutine t_spheric_global_ranks::check_sph_1d_domain_id (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_rj_grid), intent(in) sph_rj, type(spheric_global_rank), intent(in) s3d_ranks)
Definition at line 289 of file t_spheric_global_ranks.f90.
check_sph_domains()
subroutine t_spheric_global_ranks::check_sph_domains (integer, intent(in) nprocs_check, type(spheric_global_rank), intent(inout) s3d_ranks, integer(kind = kint), intent(inout) ierr, character(len = kchara), intent(inout) e_message)
Definition at line 199 of file t_spheric_global_ranks.f90.
References m_error_ids::ierr_mesh.
Referenced by set_control_sph_subdomains::set_subdomains_4_sph_shell().
check_sph_ranks()
subroutine t_spheric_global_ranks::check_sph_ranks (integer, intent(in) id_rank, type(spheric_global_rank), intent(in) s3d_ranks)
Definition at line 257 of file t_spheric_global_ranks.f90.
dealloc_radius_1d_gl()
subroutine t_spheric_global_ranks::dealloc_radius_1d_gl (type(spheric_global_radius), intent(inout) s3d_radius)
Definition at line 103 of file t_spheric_global_ranks.f90.
Referenced by t_const_spherical_grid::dealloc_gen_mesh_params().
dealloc_sph_1d_domain_id()
subroutine t_spheric_global_ranks::dealloc_sph_1d_domain_id (type(spheric_global_rank), intent(inout) s3d_ranks)
Definition at line 185 of file t_spheric_global_ranks.f90.
Referenced by t_const_spherical_grid::dealloc_gen_mesh_params().
dealloc_sph_ranks()
subroutine t_spheric_global_ranks::dealloc_sph_ranks (type(spheric_global_rank), intent(inout) s3d_ranks)
Definition at line 171 of file t_spheric_global_ranks.f90.
Referenced by t_const_spherical_grid::dealloc_gen_mesh_params().