CALYPSO: gz_mesh_file_io Module Reference
gz_mesh_file_io Module Reference
Mesh file IO for gxipped format.
Functions/Subroutines
subroutine gz_read_mesh (id_rank, file_name, mesh_IO, group_IO, ierr)
subroutine gz_read_mesh_geometry (id_rank, file_name, mesh_IO, ierr)
subroutine gz_read_node_size (id_rank, file_name, mesh_IO, ierr)
subroutine gz_read_geometry_size (id_rank, file_name, mesh_IO, ierr)
subroutine gz_write_mesh_file (id_rank, file_name, mesh_IO, group_IO)
Variables
type(buffer_4_gzip), private zbuf_m
Detailed Description
Mesh file IO for gxipped format.
      subroutine gz_read_mesh                                         &
     &         (id_rank, file_name, mesh_IO, group_IO, ierr)
        type(mesh_geometry), intent(inout) :: mesh_IO
        type(mesh_groups), intent(inout) ::   group_IO
      subroutine gz_read_mesh_geometry                                &
     &         (id_rank, file_name, mesh_IO, ierr)
      subroutine gz_read_node_size                                    &
     &         (id_rank, file_name, mesh_IO, ierr)
      subroutine gz_read_geometry_size                                &
     &         (id_rank, file_name, mesh_IO, ierr)
        type(mesh_geometry), intent(inout) :: mesh_IO
      subroutine gz_write_mesh_file                                   &
     &         (id_rank, file_name, mesh_IO, group_IO)
        type(mesh_geometry), intent(in) :: mesh_IO
        type(mesh_groups), intent(in) ::   group_IO
Function/Subroutine Documentation
gz_read_geometry_size()
subroutine gz_mesh_file_io::gz_read_geometry_size (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(inout) mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 121 of file gz_mesh_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), gz_mesh_data_io::gz_read_num_node_ele(), m_machine_parameter::i_debug, skip_gz_comment::open_rd_gzfile_a(), and zbuf_m.
Referenced by mesh_io_select::sel_read_geometry_size().
gz_read_mesh()
subroutine gz_mesh_file_io::gz_read_mesh (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(inout) mesh_IO, type(mesh_groups), intent(inout) group_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 47 of file gz_mesh_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), gz_mesh_data_io::gz_read_geometry_data(), gz_mesh_data_io::gz_read_mesh_groups(), m_machine_parameter::i_debug, skip_gz_comment::open_rd_gzfile_a(), and zbuf_m.
Referenced by mesh_io_select::sel_read_mesh().
gz_read_mesh_geometry()
subroutine gz_mesh_file_io::gz_read_mesh_geometry (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(inout) mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 74 of file gz_mesh_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), gz_mesh_data_io::gz_read_geometry_data(), m_machine_parameter::i_debug, skip_gz_comment::open_rd_gzfile_a(), and zbuf_m.
Referenced by mesh_io_select::sel_read_mesh_geometry().
gz_read_node_size()
subroutine gz_mesh_file_io::gz_read_node_size (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(inout) mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 97 of file gz_mesh_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), gz_mesh_data_io::gz_read_num_node(), m_machine_parameter::i_debug, skip_gz_comment::open_rd_gzfile_a(), and zbuf_m.
Referenced by mesh_io_select::sel_read_node_size().
gz_write_mesh_file()
subroutine gz_mesh_file_io::gz_write_mesh_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(in) mesh_IO, type(mesh_groups), intent(in) group_IO)
Definition at line 146 of file gz_mesh_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), gz_mesh_data_io::gz_write_geometry_data(), gz_mesh_data_io::gz_write_mesh_groups(), m_machine_parameter::i_debug, skip_gz_comment::open_wt_gzfile_a(), and zbuf_m.
Referenced by mesh_io_select::sel_write_mesh_file().
Variable Documentation
zbuf_m
type(buffer_4_gzip), private gz_mesh_file_io::zbuf_m private
Definition at line 39 of file gz_mesh_file_IO.f90.
Referenced by gz_read_geometry_size(), gz_read_mesh(), gz_read_mesh_geometry(), gz_read_node_size(), and gz_write_mesh_file().