CALYPSO: sph_mean_square_io_select Module Reference
sph_mean_square_io_select Module Reference
Mean sqare data.
Functions/Subroutines
subroutine select_input_sph_pwr_head (id_file, sph_IN)
integer(kind=kint) function select_input_sph_pwr_data (id_file, sph_IN)
subroutine select_output_sph_pwr_head (id_file, sph_IN)
subroutine select_output_sph_pwr_data (id_file, sph_IN)
Detailed Description
Mean sqare data.
      subroutine select_input_sph_pwr_head(id_file, sph_IN)
      integer(kind = kint) function select_input_sph_pwr_data         &
     &                            (id_file, sph_IN)
        type(read_sph_spectr_data), intent(inout) :: sph_IN
      subroutine select_output_sph_pwr_head(id_file, sph_IN)
      subroutine select_output_sph_pwr_data(id_file, sph_IN)
        type(read_sph_spectr_data), intent(in) :: sph_IN
Function/Subroutine Documentation
select_input_sph_pwr_data()
integer(kind = kint) function sph_mean_square_io_select::select_input_sph_pwr_data (integer(kind = kint), intent(in) id_file, type(read_sph_spectr_data), intent(inout) sph_IN)
Definition at line 75 of file sph_mean_square_IO_select.f90.
References simple_sph_spectr_data_io::read_layer_pwr_sph(), simple_sph_spectr_data_io::read_layer_pwr_sph_old(), simple_sph_spectr_data_io::read_layer_spectr_sph(), simple_sph_spectr_data_io::read_layer_spectr_sph_old(), simple_sph_spectr_data_io::read_volume_pwr_sph(), and simple_sph_spectr_data_io::read_volume_spectr_sph().
Referenced by m_tave_sph_ene_spectr::sph_spectr_average(), and m_tave_sph_ene_spectr::sph_spectr_std_deviation().
select_input_sph_pwr_head()
subroutine sph_mean_square_io_select::select_input_sph_pwr_head (integer(kind = kint), intent(in) id_file, type(read_sph_spectr_data), intent(inout) sph_IN)
Definition at line 34 of file sph_mean_square_IO_select.f90.
References simple_sph_spectr_head_io::input_sph_pwr_layer_head(), simple_sph_spectr_head_io::input_sph_pwr_layer_head_old(), simple_sph_spectr_head_io::input_sph_pwr_vol_head(), simple_sph_spectr_head_io::input_sph_pwr_vol_head_old(), simple_sph_spectr_head_io::input_sph_spectr_layer_head(), simple_sph_spectr_head_io::input_sph_spectr_layer_head_old(), simple_sph_spectr_head_io::input_sph_spectr_vol_head(), and simple_sph_spectr_head_io::input_sph_spectr_vol_head_old().
Referenced by m_tave_sph_ene_spectr::sph_spectr_average(), and m_tave_sph_ene_spectr::sph_spectr_std_deviation().
select_output_sph_pwr_data()
subroutine sph_mean_square_io_select::select_output_sph_pwr_data (integer(kind = kint), intent(in) id_file, type(read_sph_spectr_data), intent(in) sph_IN)
Definition at line 139 of file sph_mean_square_IO_select.f90.
References simple_sph_spectr_data_io::write_layer_spectr_data(), simple_sph_spectr_data_io::write_layer_sph_data(), simple_sph_spectr_data_io::write_vol_spectr_data(), and simple_sph_spectr_data_io::write_vol_sph_data().
Referenced by m_tave_sph_ene_spectr::sph_spectr_average(), and m_tave_sph_ene_spectr::sph_spectr_std_deviation().
select_output_sph_pwr_head()
subroutine sph_mean_square_io_select::select_output_sph_pwr_head (integer(kind = kint), intent(in) id_file, type(read_sph_spectr_data), intent(inout) sph_IN)
Definition at line 121 of file sph_mean_square_IO_select.f90.
References simple_sph_spectr_head_io::write_sph_pwr_layer_head(), and simple_sph_spectr_head_io::write_sph_pwr_vol_head().
Referenced by m_tave_sph_ene_spectr::sph_spectr_average(), and m_tave_sph_ene_spectr::sph_spectr_std_deviation().