CALYPSO: gz_edge_data_io_b Module Reference
gz_edge_data_io_b Module Reference
data IO orutines for edge
Functions/Subroutines
subroutine gz_read_edge_connection_b (id_rank, zbuf, comm_IO, ele_IO, sfed_IO)
subroutine gz_write_edge_connection_b (id_rank, comm_IO, ele_IO, sfed_IO, zbuf)
subroutine gz_read_edge_geometry_b (zbuf, nod_IO, sfed_IO)
subroutine gz_write_edge_geometry_b (nod_IO, sfed_IO, zbuf)
Detailed Description
data IO orutines for edge
      subroutine gz_read_edge_connection_b                            &
     &         (id_rank, zbuf, comm_IO, ele_IO, sfed_IO)
        type(buffer_4_gzip), intent(inout) :: zbuf
        type(communication_table), intent(inout) :: comm_IO
        type(element_data), intent(inout) :: ele_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
      subroutine gz_write_edge_connection_b                           &
     &         (id_rank, comm_IO, ele_IO, sfed_IO, zbuf)
        type(communication_table), intent(in) :: comm_IO
        type(element_data), intent(in) :: ele_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
        type(buffer_4_gzip), intent(inout) :: zbuf
      subroutine gz_read_edge_geometry_b(zbuf, nod_IO, sfed_IO)
        type(buffer_4_gzip), intent(inout) :: zbuf
        type(node_data), intent(inout) :: nod_IO
        type(element_data), intent(inout) :: ele_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
      subroutine gz_write_edge_geometry_b(nod_IO, sfed_IO, zbuf)
        type(node_data), intent(in) :: nod_IO
        type(element_data), intent(in) :: ele_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
        type(buffer_4_gzip), intent(inout) :: zbuf
Function/Subroutine Documentation
gz_read_edge_connection_b()
subroutine gz_edge_data_io_b::gz_read_edge_connection_b (integer, intent(in) id_rank, type(buffer_4_gzip), intent(inout) zbuf, type(communication_table), intent(inout) comm_IO, type(element_data), intent(inout) ele_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 56 of file gz_edge_data_IO_b.f90.
References gz_domain_data_io_b::gz_read_domain_info_b(), gz_element_connect_io_b::gz_read_edge_4_element_b(), gz_element_connect_io_b::gz_read_element_info_b(), gz_domain_data_io_b::gz_read_export_data_b(), gz_domain_data_io_b::gz_read_import_data_b(), gz_element_connect_io_b::gz_read_number_of_element_b(), and gz_element_connect_io_b::gz_read_surface_4_element_b().
Referenced by gz_element_file_io_b::gz_input_edge_file_b().
gz_read_edge_geometry_b()
subroutine gz_edge_data_io_b::gz_read_edge_geometry_b (type(buffer_4_gzip), intent(inout) zbuf, type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 147 of file gz_edge_data_IO_b.f90.
References gz_node_geometry_io_b::gz_read_geometry_info_b(), gz_node_geometry_io_b::gz_read_number_of_node_b(), gz_node_geometry_io_b::gz_read_scalar_in_element_b(), and gz_node_geometry_io_b::gz_read_vector_in_element_b().
gz_write_edge_connection_b()
subroutine gz_edge_data_io_b::gz_write_edge_connection_b (integer, intent(in) id_rank, type(communication_table), intent(in) comm_IO, type(element_data), intent(in) ele_IO, type(surf_edge_io_data), intent(in) sfed_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 101 of file gz_edge_data_IO_b.f90.
References gz_domain_data_io_b::gz_write_domain_info_b(), gz_element_connect_io_b::gz_write_edge_4_element_b(), gz_element_connect_io_b::gz_write_element_info_b(), gz_domain_data_io_b::gz_write_export_data_b(), gz_domain_data_io_b::gz_write_import_data_b(), and gz_element_connect_io_b::gz_write_surface_4_element_b().
Referenced by gz_element_file_io_b::gz_output_edge_file_b().
gz_write_edge_geometry_b()
subroutine gz_edge_data_io_b::gz_write_edge_geometry_b (type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 176 of file gz_edge_data_IO_b.f90.
References gz_node_geometry_io_b::gz_write_geometry_info_b(), gz_node_geometry_io_b::gz_write_scalar_in_element_b(), and gz_node_geometry_io_b::gz_write_vector_in_element_b().