CALYPSO: gz_mpi_mesh_file_io Module Reference
gz_mpi_mesh_file_io Module Reference
Mesh file IO for gxipped format.
Functions/Subroutines
subroutine gz_mpi_read_mesh (num_pe, id_rank, file_name, mesh_IO, group_IO)
subroutine gz_mpi_read_mesh_geometry (num_pe, id_rank, file_name, mesh_IO)
subroutine gz_mpi_read_node_size (num_pe, id_rank, file_name, mesh_IO)
subroutine gz_mpi_read_geometry_size (num_pe, id_rank, file_name, mesh_IO)
subroutine gz_mpi_write_mesh_file (file_name, mesh_IO, group_IO)
Variables
type(calypso_mpi_io_params), save, private io_param
Detailed Description
Mesh file IO for gxipped format.
      subroutine gz_mpi_read_mesh                                     &
     &         (num_pe, id_rank, file_name, mesh_IO, group_IO)
        type(mesh_geometry), intent(inout) :: mesh_IO
        type(mesh_groups), intent(inout) ::   group_IO
      subroutine gz_mpi_read_mesh_geometry                            &
     &         (num_pe, id_rank, file_name, mesh_IO)
      subroutine gz_mpi_read_node_size                                &
     &         (num_pe, id_rank, file_name, mesh_IO)
      subroutine gz_mpi_read_geometry_size                            &
     &         (num_pe, id_rank, file_name, mesh_IO)
        type(mesh_geometry), intent(inout) :: mesh_IO
      subroutine gz_mpi_write_mesh_file(file_name, mesh_IO, group_IO)
        type(mesh_geometry), intent(in) :: mesh_IO
        type(mesh_groups), intent(in) ::   group_IO
Function/Subroutine Documentation
gz_mpi_read_geometry_size()
subroutine gz_mpi_mesh_file_io::gz_mpi_read_geometry_size (integer, intent(in) num_pe, integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 113 of file gz_MPI_mesh_file_IO.f90.
References mpi_ascii_data_io::close_mpi_file(), gz_mpi_mesh_data_io::gz_mpi_read_num_node_ele(), m_machine_parameter::i_debug, io_param, and mpi_ascii_data_io::open_read_mpi_file().
Referenced by mesh_mpi_io_select::sel_mpi_read_geometry_size().
gz_mpi_read_mesh()
subroutine gz_mpi_mesh_file_io::gz_mpi_read_mesh (integer, intent(in) num_pe, integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(inout) mesh_IO, type(mesh_groups), intent(inout) group_IO)
Definition at line 49 of file gz_MPI_mesh_file_IO.f90.
References mpi_ascii_data_io::close_mpi_file(), gz_mpi_mesh_data_io::gz_mpi_read_geometry_data(), gz_mpi_mesh_data_io::gz_mpi_read_mesh_groups(), m_machine_parameter::i_debug, io_param, and mpi_ascii_data_io::open_read_mpi_file().
Referenced by mesh_mpi_io_select::sel_mpi_read_mesh().
gz_mpi_read_mesh_geometry()
subroutine gz_mpi_mesh_file_io::gz_mpi_read_mesh_geometry (integer, intent(in) num_pe, integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 73 of file gz_MPI_mesh_file_IO.f90.
References mpi_ascii_data_io::close_mpi_file(), gz_mpi_mesh_data_io::gz_mpi_read_geometry_data(), m_machine_parameter::i_debug, io_param, and mpi_ascii_data_io::open_read_mpi_file().
Referenced by mesh_mpi_io_select::sel_mpi_read_mesh_geometry().
gz_mpi_read_node_size()
subroutine gz_mpi_mesh_file_io::gz_mpi_read_node_size (integer, intent(in) num_pe, integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 93 of file gz_MPI_mesh_file_IO.f90.
References mpi_ascii_data_io::close_mpi_file(), gz_mpi_mesh_data_io::gz_mpi_read_num_node(), m_machine_parameter::i_debug, io_param, and mpi_ascii_data_io::open_read_mpi_file().
Referenced by mesh_mpi_io_select::sel_mpi_read_node_size().
gz_mpi_write_mesh_file()
subroutine gz_mpi_mesh_file_io::gz_mpi_write_mesh_file (character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(in) mesh_IO, type(mesh_groups), intent(in) group_IO)
Definition at line 134 of file gz_MPI_mesh_file_IO.f90.
References mpi_ascii_data_io::close_mpi_file(), gz_mpi_mesh_data_io::gz_mpi_write_geometry_data(), gz_mpi_mesh_data_io::gz_mpi_write_mesh_groups(), m_machine_parameter::i_debug, io_param, and mpi_ascii_data_io::open_write_mpi_file().
Referenced by mesh_mpi_io_select::sel_mpi_write_mesh_file().
Variable Documentation
io_param
type(calypso_mpi_io_params), save, private gz_mpi_mesh_file_io::io_param private
Definition at line 41 of file gz_MPI_mesh_file_IO.f90.
Referenced by gz_mpi_read_geometry_size(), gz_mpi_read_mesh(), gz_mpi_read_mesh_geometry(), gz_mpi_read_node_size(), and gz_mpi_write_mesh_file().