CALYPSO: t_spheric_rlm_data Module Reference
t_spheric_rlm_data Module Reference
Structure for indexing table of speherical harmonics transform.
Data Types
type sph_rlm_grid
structure of index table for \(f(r,l,m) \)
Functions/Subroutines
subroutine alloc_spheric_param_rlm (sph_rlm)
subroutine alloc_sph_1d_index_rlm (sph_rlm)
subroutine alloc_rlm_param_smp (sph_rlm)
subroutine dealloc_spheric_param_rlm (sph_rlm)
subroutine dealloc_sph_1d_index_rlm (sph_rlm)
subroutine dealloc_rlm_param_smp (sph_rlm)
subroutine copy_spheric_rlm_data (ltr_org, rlm_org, ltr_new, rlm_new)
subroutine check_spheric_param_rlm (id_rank, sph_rlm)
Detailed Description
Structure for indexing table of speherical harmonics transform.
      subroutine alloc_spheric_param_rlm(sph_rlm)
      subroutine alloc_sph_1d_index_rlm(sph_rlm)
      subroutine alloc_rlm_param_smp(sph_rlm)
        type(sph_rlm_grid), intent(inout) :: sph_rlm
      subroutine dealloc_spheric_param_rlm(sph_rlm)
      subroutine dealloc_sph_1d_index_rlm(sph_rlm)
      subroutine dealloc_rlm_param_smp(sph_rlm)
        type(sph_rlm_grid), intent(inout) :: sph_rlm
      subroutine copy_spheric_rlm_data                                &
     &         (ltr_org, rlm_org, ltr_new, rlm_new)
        type(sph_rlm_grid), intent(in) :: rlm_org
        type(sph_rlm_grid), intent(inout) :: rlm_new
      subroutine check_spheric_param_rlm(id_rank, sph_rlm)
        integer, intent(in) :: id_rank
        type(sph_rlm_grid), intent(in) :: sph_rlm
Parameters
id_rank Running rank ID
Function/Subroutine Documentation
alloc_rlm_param_smp()
subroutine t_spheric_rlm_data::alloc_rlm_param_smp (type(sph_rlm_grid), intent(inout) sph_rlm)
Definition at line 128 of file t_spheric_rlm_data.f90.
References m_machine_parameter::np_smp.
Referenced by count_num_sph_smp::count_num_rlm_smp().
alloc_sph_1d_index_rlm()
subroutine t_spheric_rlm_data::alloc_sph_1d_index_rlm (type(sph_rlm_grid), intent(inout) sph_rlm)
Definition at line 105 of file t_spheric_rlm_data.f90.
Referenced by gen_sph_grids_modes::const_sph_rlm_modes(), copy_sph_rlm_mode_4_io::copy_sph_node_4_rlm_from_io(), copy_spheric_rlm_data(), and set_comm_table_rtp_rj::set_comm_table_4_rj().
alloc_spheric_param_rlm()
subroutine t_spheric_rlm_data::alloc_spheric_param_rlm (type(sph_rlm_grid), intent(inout) sph_rlm)
Definition at line 90 of file t_spheric_rlm_data.f90.
Referenced by t_spheric_parameter::alloc_spheric_parameter(), gen_sph_grids_modes::const_sph_rlm_modes(), copy_sph_rlm_mode_4_io::copy_sph_node_4_rlm_from_io(), and copy_spheric_rlm_data().
check_spheric_param_rlm()
subroutine t_spheric_rlm_data::check_spheric_param_rlm (integer, intent(in) id_rank, type(sph_rlm_grid), intent(in) sph_rlm)
Definition at line 235 of file t_spheric_rlm_data.f90.
Referenced by t_spheric_parameter::check_spheric_parameter(), and gen_sph_grids_modes::const_sph_rlm_modes().
copy_spheric_rlm_data()
subroutine t_spheric_rlm_data::copy_spheric_rlm_data (integer(kind = kint), intent(in) ltr_org, type(sph_rlm_grid), intent(in) rlm_org, integer(kind = kint), intent(inout) ltr_new, type(sph_rlm_grid), intent(inout) rlm_new)
Definition at line 187 of file t_spheric_rlm_data.f90.
References alloc_sph_1d_index_rlm(), alloc_spheric_param_rlm(), and m_constants::itwo.
dealloc_rlm_param_smp()
subroutine t_spheric_rlm_data::dealloc_rlm_param_smp (type(sph_rlm_grid), intent(inout) sph_rlm)
Definition at line 174 of file t_spheric_rlm_data.f90.
dealloc_sph_1d_index_rlm()
subroutine t_spheric_rlm_data::dealloc_sph_1d_index_rlm (type(sph_rlm_grid), intent(inout) sph_rlm)
Definition at line 160 of file t_spheric_rlm_data.f90.
Referenced by t_spheric_parameter::dealloc_sph_1d_indices(), and set_comm_table_rtp_rj::set_comm_table_4_rj().
dealloc_spheric_param_rlm()
subroutine t_spheric_rlm_data::dealloc_spheric_param_rlm (type(sph_rlm_grid), intent(inout) sph_rlm)
Definition at line 150 of file t_spheric_rlm_data.f90.
Referenced by t_spheric_parameter::dealloc_spheric_parameter(), and set_comm_table_rtp_rj::set_comm_table_4_rj().