CALYPSO: t_belonged_element_4_node Module Reference
t_belonged_element_4_node Module Reference
Belonged element list for each node.
Data Types
type belonged_table
Functions/Subroutines
subroutine set_belonged_id_4_node (mesh, surf, edge, belongs)
subroutine dealloc_belonged_id_4_node (belongs)
subroutine alloc_x_ref_ele (node, belongs)
subroutine alloc_x_ref_surf (node, belongs)
subroutine alloc_x_ref_edge (node, belongs)
subroutine dealloc_x_ref_ele (belongs)
subroutine dealloc_x_ref_surf (belongs)
subroutine dealloc_x_ref_edge (belongs)
subroutine belonged_ele_id_4_node (node, ele, host_ele)
subroutine belonged_surf_id_4_node (node, surf, host_surf)
subroutine belonged_edge_id_4_node (node, edge, host_edge)
subroutine sort_inod_4_ele_by_position (nd, numele, x_ele, node, neib_e, x_ref_ele)
Detailed Description
Belonged element list for each node.
      subroutine set_belonged_id_4_node(mesh, surf, edge, belongs)
      subroutine dealloc_belonged_id_4_node(belongs)
      subroutine alloc_x_ref_ele(node, belongs)
      subroutine alloc_x_ref_surf(node, belongs)
      subroutine alloc_x_ref_edge(node, belongs)
      subroutine dealloc_x_ref_ele(belongs)
      subroutine dealloc_x_ref_surf(belongs)
      subroutine adelloc_x_ref_edge(belongs)
        type(belonged_table), intent(inout) :: belongs
      subroutine sort_inod_4_ele_by_position                          &
     &         (nd, numele, x_ele, node, neib_e, x_ref_ele)
        integer(kind = kint), intent(in) :: nd
        type(node_data), intent(in) :: node
      type(element_data), intent(in) :: ele
        type(element_around_node), intent(inout) :: neib_e
Function/Subroutine Documentation
alloc_x_ref_edge()
subroutine t_belonged_element_4_node::alloc_x_ref_edge (type(node_data), intent(in) node, type(belonged_table), intent(inout) belongs)
Definition at line 138 of file t_belonged_element_4_node.f90.
Referenced by const_element_comm_tables::const_edge_comm_table().
alloc_x_ref_ele()
subroutine t_belonged_element_4_node::alloc_x_ref_ele (type(node_data), intent(in) node, type(belonged_table), intent(inout) belongs)
Definition at line 102 of file t_belonged_element_4_node.f90.
Referenced by const_element_comm_tables::const_ele_comm_tbl().
alloc_x_ref_surf()
subroutine t_belonged_element_4_node::alloc_x_ref_surf (type(node_data), intent(in) node, type(belonged_table), intent(inout) belongs)
Definition at line 120 of file t_belonged_element_4_node.f90.
Referenced by const_element_comm_tables::const_surf_comm_table().
belonged_edge_id_4_node()
subroutine t_belonged_element_4_node::belonged_edge_id_4_node (type(node_data), intent(in) node, type(edge_data), intent(in) edge, type(element_around_node), intent(inout) host_edge)
Definition at line 254 of file t_belonged_element_4_node.f90.
References t_next_node_ele_4_node::alloc_iele_belonged(), t_next_node_ele_4_node::alloc_numele_belonged(), find_element_id_4_node::count_belonged_ele_4_node(), m_constants::ione, m_constants::izero, cal_minmax_and_stacks::s_cal_minmax_and_stacks(), and find_element_id_4_node::set_belonged_ele_4_node().
Referenced by const_element_comm_tables::const_edge_comm_table(), and set_belonged_id_4_node().
belonged_ele_id_4_node()
subroutine t_belonged_element_4_node::belonged_ele_id_4_node (type(node_data), intent(in) node, type(element_data), intent(in) ele, type(element_around_node), intent(inout) host_ele)
Definition at line 188 of file t_belonged_element_4_node.f90.
References t_next_node_ele_4_node::alloc_iele_belonged(), t_next_node_ele_4_node::alloc_numele_belonged(), find_element_id_4_node::count_belonged_ele_4_node(), m_constants::ione, m_constants::izero, cal_minmax_and_stacks::s_cal_minmax_and_stacks(), and find_element_id_4_node::set_belonged_ele_4_node().
Referenced by const_element_comm_tables::const_ele_comm_tbl(), and set_belonged_id_4_node().
belonged_surf_id_4_node()
subroutine t_belonged_element_4_node::belonged_surf_id_4_node (type(node_data), intent(in) node, type(surface_data), intent(in) surf, type(element_around_node), intent(inout) host_surf)
Definition at line 220 of file t_belonged_element_4_node.f90.
References t_next_node_ele_4_node::alloc_iele_belonged(), t_next_node_ele_4_node::alloc_numele_belonged(), find_element_id_4_node::count_belonged_ele_4_node(), m_constants::ione, m_constants::izero, cal_minmax_and_stacks::s_cal_minmax_and_stacks(), and find_element_id_4_node::set_belonged_ele_4_node().
Referenced by const_element_comm_tables::const_surf_comm_table(), and set_belonged_id_4_node().
dealloc_belonged_id_4_node()
subroutine t_belonged_element_4_node::dealloc_belonged_id_4_node (type(belonged_table), intent(inout) belongs)
Definition at line 88 of file t_belonged_element_4_node.f90.
References t_next_node_ele_4_node::dealloc_iele_belonged().
dealloc_x_ref_edge()
subroutine t_belonged_element_4_node::dealloc_x_ref_edge (type(belonged_table), intent(inout) belongs)
Definition at line 177 of file t_belonged_element_4_node.f90.
Referenced by const_element_comm_tables::const_edge_comm_table().
dealloc_x_ref_ele()
subroutine t_belonged_element_4_node::dealloc_x_ref_ele (type(belonged_table), intent(inout) belongs)
Definition at line 157 of file t_belonged_element_4_node.f90.
Referenced by const_element_comm_tables::const_ele_comm_tbl().
dealloc_x_ref_surf()
subroutine t_belonged_element_4_node::dealloc_x_ref_surf (type(belonged_table), intent(inout) belongs)
Definition at line 167 of file t_belonged_element_4_node.f90.
Referenced by const_element_comm_tables::const_surf_comm_table().
set_belonged_id_4_node()
subroutine t_belonged_element_4_node::set_belonged_id_4_node (type(mesh_geometry), intent(in) mesh, type(surface_data), intent(in) surf, type(edge_data), intent(in) edge, type(belonged_table), intent(inout) belongs)
Definition at line 67 of file t_belonged_element_4_node.f90.
References belonged_edge_id_4_node(), belonged_ele_id_4_node(), and belonged_surf_id_4_node().
sort_inod_4_ele_by_position()
subroutine t_belonged_element_4_node::sort_inod_4_ele_by_position (integer(kind = kint), intent(in) nd, integer(kind = kint), intent(in) numele, real(kind = kreal), dimension(numele,3), intent(in) x_ele, type(node_data), intent(in) node, type(element_around_node), intent(inout) neib_e, real(kind = kreal), dimension(neib_e%istack_4_node(node%numnod)), intent(inout) x_ref_ele)
Definition at line 289 of file t_belonged_element_4_node.f90.
References m_constants::ione, and quicksort::quicksort_real_w_index().
Referenced by const_element_comm_tables::const_edge_comm_table(), const_element_comm_tables::const_ele_comm_tbl(), and const_element_comm_tables::const_surf_comm_table().