CALYPSO: set_ele_id_4_node_type Module Reference
set_ele_id_4_node_type Module Reference
Set belonged element list for each node.
Functions/Subroutines
subroutine set_ele_id_4_node (node, ele, neib_ele)
subroutine set_surf_id_4_node (node, surf, neib_ele)
subroutine set_edge_id_4_node (node, edge, neib_ele)
subroutine set_layerd_ele_id_4_node (nnod, iele_start, iele_end, node, ele, neib_ele)
subroutine set_grouped_ele_id_4_node (nele_grp, iele_grp, node, ele, neib_ele)
subroutine const_next_nod_id_4_node (node, ele, neib_ele, neib_nod)
Detailed Description
Set belonged element list for each node.
      subroutine set_ele_id_4_node(node, ele, neib_ele)
      subroutine set_surf_id_4_node(node, surf, neib_ele)
      subroutine set_edge_id_4_node(node, edge, neib_ele)
        type(node_data),        intent(in) :: node
        type(surface_data), intent(in) :: surf
        type(edge_data), intent(in) :: edge
        type(element_around_node), intent(inout) :: neib_ele
      subroutine set_layerd_ele_id_4_node(nnod, iele_start, iele_end, &
     &          node, ele, neib_ele)
        integer(kind = kint), intent(in) :: nnod
        integer(kind = kint), intent(in) :: iele_start, iele_end
        type(node_data),        intent(in) :: node
        type(element_data),       intent(in) :: ele
        type(element_around_node), intent(inout) :: neib_ele
      subroutine set_grouped_ele_id_4_node(nele_grp, iele_grp,        &
     &          node, ele, neib_ele)
        integer (kind=kint), intent(in) :: nele_grp
        integer (kind=kint), intent(in) :: iele_grp(nele_grp)
        type(node_data),        intent(in) :: node
        type(element_data),       intent(in) :: ele
        type(element_around_node), intent(inout) :: neib_ele
      subroutine const_next_nod_id_4_node(node, ele, neib_ele,        &
     &          neib_nod)
        type(node_data),        intent(in) :: node
        type(element_data),       intent(in) :: ele
        type(element_around_node), intent(in) :: neib_ele
        type(next_nod_id_4_nod), intent(inout) :: neib_nod
Function/Subroutine Documentation
const_next_nod_id_4_node()
subroutine set_ele_id_4_node_type::const_next_nod_id_4_node (type(node_data), intent(in) node, type(element_data), intent(in) ele, type(element_around_node), intent(in) neib_ele, type(next_nod_id_4_nod), intent(inout) neib_nod)
Definition at line 228 of file set_ele_id_4_node_type.f90.
References t_next_node_ele_4_node::alloc_inod_next_node(), t_next_node_ele_4_node::alloc_num_next_node(), find_node_4_group::allocate_work_next_node(), find_node_4_group::count_nod_4_grp_smp(), find_node_4_group::deallocate_work_next_node(), m_constants::izero, find_node_4_group::move_myself_2_first_smp(), m_machine_parameter::np_smp, cal_minmax_and_stacks::s_cal_minmax_and_stacks(), find_node_4_group::set_nod_4_grp_smp(), and find_node_4_group::sort_next_node_list_by_weight().
set_edge_id_4_node()
subroutine set_ele_id_4_node_type::set_edge_id_4_node (type(node_data), intent(in) node, type(edge_data), intent(in) edge, type(element_around_node), intent(inout) neib_ele)
Definition at line 119 of file set_ele_id_4_node_type.f90.
References t_next_node_ele_4_node::alloc_iele_belonged(), t_next_node_ele_4_node::alloc_numele_belonged(), find_element_id_4_node::count_iele_4_node(), m_constants::ione, m_constants::izero, cal_minmax_and_stacks::s_cal_minmax_and_stacks(), and find_element_id_4_node::set_iele_4_node().
Referenced by const_element_comm_tables::const_edge_comm_table().
set_ele_id_4_node()
subroutine set_ele_id_4_node_type::set_ele_id_4_node (type(node_data), intent(in) node, type(element_data), intent(in) ele, type(element_around_node), intent(inout) neib_ele)
Definition at line 53 of file set_ele_id_4_node_type.f90.
References t_next_node_ele_4_node::alloc_iele_belonged(), t_next_node_ele_4_node::alloc_numele_belonged(), find_element_id_4_node::count_iele_4_node(), m_constants::ione, m_constants::izero, cal_minmax_and_stacks::s_cal_minmax_and_stacks(), and find_element_id_4_node::set_iele_4_node().
Referenced by const_element_comm_tables::const_ele_comm_tbl().
set_grouped_ele_id_4_node()
subroutine set_ele_id_4_node_type::set_grouped_ele_id_4_node (integer (kind=kint), intent(in) nele_grp, integer (kind=kint), dimension(nele_grp), intent(in) iele_grp, type(node_data), intent(in) node, type(element_data), intent(in) ele, type(element_around_node), intent(inout) neib_ele)
Definition at line 190 of file set_ele_id_4_node_type.f90.
References t_next_node_ele_4_node::alloc_iele_belonged(), t_next_node_ele_4_node::alloc_numele_belonged(), find_grp_ele_id_4_node::count_grp_iele_4_node(), m_constants::izero, cal_minmax_and_stacks::s_cal_minmax_and_stacks(), and find_grp_ele_id_4_node::set_grp_iele_4_node().
set_layerd_ele_id_4_node()
subroutine set_ele_id_4_node_type::set_layerd_ele_id_4_node (integer(kind = kint), intent(in) nnod, integer(kind = kint), intent(in) iele_start, integer(kind = kint), intent(in) iele_end, type(node_data), intent(in) node, type(element_data), intent(in) ele, type(element_around_node), intent(inout) neib_ele)
Definition at line 154 of file set_ele_id_4_node_type.f90.
References t_next_node_ele_4_node::alloc_iele_belonged(), t_next_node_ele_4_node::alloc_numele_belonged(), find_element_id_4_node::count_iele_4_node(), m_constants::izero, cal_minmax_and_stacks::s_cal_minmax_and_stacks(), and find_element_id_4_node::set_iele_4_node().
set_surf_id_4_node()
subroutine set_ele_id_4_node_type::set_surf_id_4_node (type(node_data), intent(in) node, type(surface_data), intent(in) surf, type(element_around_node), intent(inout) neib_ele)
Definition at line 85 of file set_ele_id_4_node_type.f90.
References t_next_node_ele_4_node::alloc_iele_belonged(), t_next_node_ele_4_node::alloc_numele_belonged(), find_element_id_4_node::count_iele_4_node(), m_constants::ione, m_constants::izero, cal_minmax_and_stacks::s_cal_minmax_and_stacks(), and find_element_id_4_node::set_iele_4_node().
Referenced by const_element_comm_tables::const_surf_comm_table().