CALYPSO: t_sph_matrix Module Reference
t_sph_matrix Module Reference
structures of radial matrix
Data Types
type band_matrix_type
Structure for band matrices.
Functions/Subroutines
subroutine alloc_single_band_mat (nband, sph_rj, smat)
subroutine set_unit_single_mat (smat)
subroutine dealloc_band_matrix (smat)
subroutine ludcmp_3band_type (smat)
subroutine ludcmp_5band_type (smat)
subroutine ludcmp_7band_type (smat)
subroutine lubksb_3band_type (smat, x)
subroutine lubksb_5band_type (smat, x)
subroutine lubksb_7band_type (smat, x)
subroutine check_radial_band_matrix (id_rank, sph_rj, smat)
Detailed Description
structures of radial matrix
      subroutine alloc_single_band_mat(nband, sph_rj, smat)
      subroutine set_unit_single_mat(smat)
      subroutine dealloc_band_matrix(smat)
      subroutine ludcmp_3band_type(smat)
      subroutine ludcmp_5band_type(smat)
      subroutine ludcmp_7band_type(smat)
      subroutine lubksb_3band_type(smat, x)
      subroutine lubksb_5band_type(smat, x)
      subroutine lubksb_7band_type(smat, x)
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(band_matrix_type), intent(inout) :: smat
      subroutine check_radial_band_matrix(id_rank, sph_rj, smat)
Function/Subroutine Documentation
alloc_single_band_mat()
subroutine t_sph_matrix::alloc_single_band_mat (integer(kind = kint), intent(in) nband, type(sph_rj_grid), intent(in) sph_rj, type(band_matrix_type), intent(inout) smat)
Definition at line 67 of file t_sph_matrix.f90.
check_radial_band_matrix()
subroutine t_sph_matrix::check_radial_band_matrix (integer, intent(in) id_rank, type(sph_rj_grid), intent(in) sph_rj, type(band_matrix_type), intent(in) smat)
Definition at line 211 of file t_sph_matrix.f90.
References check_sph_radial_mat::check_single_radial_3band_mat(), check_sph_radial_mat::check_single_radial_5band_mat(), and check_sph_radial_mat::check_single_radial_7band_mat().
dealloc_band_matrix()
subroutine t_sph_matrix::dealloc_band_matrix (type(band_matrix_type), intent(inout) smat)
Definition at line 109 of file t_sph_matrix.f90.
lubksb_3band_type()
subroutine t_sph_matrix::lubksb_3band_type (type(band_matrix_type), intent(in) smat, real(kind = kreal), dimension(smat%n_vect), intent(inout) x)
Definition at line 165 of file t_sph_matrix.f90.
References lubksb_357band::lubksb_3band().
lubksb_5band_type()
subroutine t_sph_matrix::lubksb_5band_type (type(band_matrix_type), intent(in) smat, real(kind = kreal), dimension(smat%n_vect), intent(inout) x)
Definition at line 180 of file t_sph_matrix.f90.
References lubksb_357band::lubksb_5band().
lubksb_7band_type()
subroutine t_sph_matrix::lubksb_7band_type (type(band_matrix_type), intent(in) smat, real(kind = kreal), dimension(smat%n_vect), intent(inout) x)
Definition at line 195 of file t_sph_matrix.f90.
References lubksb_357band::lubksb_7band().
ludcmp_3band_type()
subroutine t_sph_matrix::ludcmp_3band_type (type(band_matrix_type), intent(inout) smat)
Definition at line 121 of file t_sph_matrix.f90.
References m_ludcmp_3band::ludcmp_3band().
ludcmp_5band_type()
subroutine t_sph_matrix::ludcmp_5band_type (type(band_matrix_type), intent(inout) smat)
Definition at line 136 of file t_sph_matrix.f90.
References m_ludcmp_band::ludcmp_band().
ludcmp_7band_type()
subroutine t_sph_matrix::ludcmp_7band_type (type(band_matrix_type), intent(inout) smat)
Definition at line 150 of file t_sph_matrix.f90.
References m_ludcmp_band::ludcmp_band().
set_unit_single_mat()
subroutine t_sph_matrix::set_unit_single_mat (type(band_matrix_type), intent(inout) smat)
Definition at line 94 of file t_sph_matrix.f90.