CALYPSO: sph_trans_w_coriols Module Reference
sph_trans_w_coriols Module Reference
Spherical harmonics transform including Coriolis terms.
Functions/Subroutines
subroutine sph_b_trans_w_coriolis (sph, comms_sph, fl_prop, sph_bc_U, omega_sph, b_trns, trans_p, gt_cor, n_WS, n_WR, WS, WR, trns_bwd, WK_leg, WK_FFTs_MHD, cor_rlm)
subroutine sph_f_trans_w_coriolis (sph, comms_sph, fl_prop, trans_p, cor_rlm, f_trns, trns_fwd, n_WS, n_WR, WS, WR, WK_leg, WK_FFTs_MHD)
subroutine sph_b_trans_licv (sph_rlm, comm_rlm, comm_rj, fl_prop, sph_bc_U, omega_sph, leg, gt_cor, b_trns, trns_bwd, n_WR, WR, cor_rlm)
subroutine sph_f_trans_licv (sph_rlm, comm_rlm, comm_rj, fl_prop, cor_rlm, f_trns, trns_fwd, n_WS, WS)
Detailed Description
Spherical harmonics transform including Coriolis terms.
      subroutine sph_b_trans_w_coriolis                               &
     &         (sph, comms_sph, fl_prop, sph_bc_U, omega_sph, b_trns, &
     &          trans_p, gt_cor, n_WS, n_WR, WS, WR, trns_bwd,        &
     &          WK_leg, WK_FFTs_MHD, cor_rlm)
      subroutine sph_f_trans_w_coriolis                               &
     &         (sph, comms_sph, fl_prop, trans_p, cor_rlm, f_trns,    &
     &          trns_fwd, n_WS, n_WR, WS, WR, WK_leg, WK_FFTs_MHD)
        type(sph_grids), intent(in) :: sph
        type(sph_comm_tables), intent(in) :: comms_sph
        type(fluid_property), intent(in) :: fl_prop
        type(sph_boundary_type), intent(in) :: sph_bc_U
        type(sph_rotation), intent(in) :: omega_sph
        type(parameters_4_sph_trans), intent(in) :: trans_p
        type(phys_address), intent(in) :: b_trns
        type(phys_address), intent(in) :: f_trns
        type(spherical_transform_data), intent(inout) :: trns_bwd
        type(spherical_transform_data), intent(inout) :: trns_fwd
        type(legendre_trns_works), intent(inout) :: WK_leg
        type(work_for_FFTs), intent(inout) :: WK_FFTs_MHD
      subroutine sph_b_trans_licv(sph_rlm, comm_rlm, comm_rj,         &
     &          fl_prop, sph_bc_U, omega_sph, leg, gt_cor,            &
     &          b_trns, trns_bwd, n_WR, WR, cor_rlm)
      subroutine sph_f_trans_licv(sph_rlm, comm_rlm, comm_rj,         &
     &          fl_prop, cor_rlm, f_trns, trns_fwd,  n_WS, WS)
        type(sph_rlm_grid), intent(in) :: sph_rlm
        type(sph_comm_tbl), intent(in) :: comm_rlm
        type(sph_comm_tbl), intent(in) :: comm_rj
        type(fluid_property), intent(in) :: fl_prop
        type(sph_boundary_type), intent(in) :: sph_bc_U
        type(sph_rotation), intent(in) :: omega_sph
        type(legendre_4_sph_trans), intent(in) :: leg
        type(gaunt_coriolis_rlm), intent(in) :: gt_cor
        type(phys_address), intent(in) :: b_trns
        type(phys_address), intent(in) :: f_trns
        type(spherical_transform_data), intent(in) :: trns_bwd
        type(coriolis_rlm_data), intent(inout) :: cor_rlm
   input /outpt arrays for single vector
      radial component:      v_rtp(i_rtp,1)
      elevetional component: v_rtp(i_rtp,2)
      azimuthal component:   v_rtp(i_rtp,3)
      Poloidal component:          WR(3*i_rj-2)
      diff. of Poloidal component: WR(3*i_rj-1)
      Toroidal component:          WR(3*i_rj  )
Parameters
ncomp_trans Number of components for transform
nvector Number of vectors for transform
nscalar Number of scalars for transform
n_WS Number of components for send buffrt
n_WR Number of components for recieve buffer
WS Send buffer
WR Recieve buffer
fld_rtp Field data to make nonlinear terms
frc_rtp Nonlinear terms
Function/Subroutine Documentation
sph_b_trans_licv()
subroutine sph_trans_w_coriols::sph_b_trans_licv (type(sph_rlm_grid), intent(in) sph_rlm, type(sph_comm_tbl), intent(in) comm_rlm, type(sph_comm_tbl), intent(in) comm_rj, type(fluid_property), intent(in) fl_prop, type(sph_boundary_type), intent(in) sph_bc_U, type(sph_rotation), intent(in) omega_sph, type(legendre_4_sph_trans), intent(in) leg, type(gaunt_coriolis_rlm), intent(in) gt_cor, type(phys_address), intent(in) b_trns, type(spherical_transform_data), intent(in) trns_bwd, integer(kind = kint), intent(in) n_WR, real(kind = kreal), dimension(n_wr), intent(inout) WR, type(coriolis_rlm_data), intent(inout) cor_rlm)
Definition at line 233 of file sph_trans_w_coriols.f90.
References spherical_srs_n::calypso_sph_comm_n(), m_work_time::end_elapsed_time(), spherical_srs_n::finish_send_recv_sph(), m_machine_parameter::iflag_debug, m_elapsed_labels_4_mhd::iflag_smhd_time, m_elapsed_labels_sph_trns::iflag_sph_time, m_elapsed_labels_4_mhd::ist_elapsed_smhd, m_elapsed_labels_sph_trns::ist_elapsed_sph, m_work_time::start_elapsed_time(), and t_coriolis_terms_rlm::sum_coriolis_rlm().
Referenced by sph_transforms_4_mhd::sph_transform_4_licv().
sph_b_trans_w_coriolis()
subroutine sph_trans_w_coriols::sph_b_trans_w_coriolis (type(sph_grids), intent(in) sph, type(sph_comm_tables), intent(in) comms_sph, type(fluid_property), intent(in) fl_prop, type(sph_boundary_type), intent(in) sph_bc_U, type(sph_rotation), intent(in) omega_sph, type(phys_address), intent(in) b_trns, type(parameters_4_sph_trans), intent(in) trans_p, type(gaunt_coriolis_rlm), intent(in) gt_cor, integer(kind = kint), intent(in) n_WS, integer(kind = kint), intent(in) n_WR, real(kind = kreal), dimension(n_ws), intent(inout) WS, real(kind = kreal), dimension(n_wr), intent(inout) WR, type(spherical_transform_data), intent(inout) trns_bwd, type(legendre_trns_works), intent(inout) WK_leg, type(work_for_ffts), intent(inout) WK_FFTs_MHD, type(coriolis_rlm_data), intent(inout) cor_rlm)
Definition at line 104 of file sph_trans_w_coriols.f90.
References t_sph_fft_selector::back_fft_select_from_recv(), calypso_mpi::calypso_mpi_barrier(), spherical_srs_n::calypso_sph_comm_n(), m_work_time::end_elapsed_time(), spherical_srs_n::finish_send_recv_sph(), m_machine_parameter::iflag_debug, m_elapsed_labels_4_mhd::iflag_smhd_time, m_elapsed_labels_sph_trns::iflag_sph_time, m_elapsed_labels_4_mhd::ist_elapsed_smhd, m_elapsed_labels_sph_trns::ist_elapsed_sph, t_legendre_trans_select::sel_backward_legendre_trans(), m_work_time::start_elapsed_time(), and t_coriolis_terms_rlm::sum_coriolis_rlm().
Referenced by sph_transforms_4_mhd::sph_back_trans_4_mhd().
sph_f_trans_licv()
subroutine sph_trans_w_coriols::sph_f_trans_licv (type(sph_rlm_grid), intent(in) sph_rlm, type(sph_comm_tbl), intent(in) comm_rlm, type(sph_comm_tbl), intent(in) comm_rj, type(fluid_property), intent(in) fl_prop, type(coriolis_rlm_data), intent(in) cor_rlm, type(phys_address), intent(in) f_trns, type(spherical_transform_data), intent(in) trns_fwd, integer(kind = kint), intent(in) n_WS, real(kind = kreal), dimension(n_ws), intent(inout) WS)
Definition at line 270 of file sph_trans_w_coriols.f90.
References spherical_srs_n::calypso_sph_comm_n(), t_coriolis_terms_rlm::copy_coriolis_terms_rlm(), m_work_time::end_elapsed_time(), spherical_srs_n::finish_send_recv_sph(), m_machine_parameter::iflag_debug, m_elapsed_labels_4_mhd::iflag_smhd_time, m_elapsed_labels_sph_trns::iflag_sph_time, m_elapsed_labels_4_mhd::ist_elapsed_smhd, m_elapsed_labels_sph_trns::ist_elapsed_sph, and m_work_time::start_elapsed_time().
Referenced by sph_transforms_4_mhd::sph_transform_4_licv().
sph_f_trans_w_coriolis()
subroutine sph_trans_w_coriols::sph_f_trans_w_coriolis (type(sph_grids), intent(in) sph, type(sph_comm_tables), intent(in) comms_sph, type(fluid_property), intent(in) fl_prop, type(parameters_4_sph_trans), intent(in) trans_p, type(coriolis_rlm_data), intent(in) cor_rlm, type(phys_address), intent(in) f_trns, type(spherical_transform_data), intent(inout) trns_fwd, integer(kind = kint), intent(in) n_WS, integer(kind = kint), intent(in) n_WR, real(kind = kreal), dimension(n_ws), intent(inout) WS, real(kind = kreal), dimension(n_wr), intent(inout) WR, type(legendre_trns_works), intent(inout) WK_leg, type(work_for_ffts), intent(inout) WK_FFTs_MHD)
Definition at line 176 of file sph_trans_w_coriols.f90.
References spherical_srs_n::calypso_sph_comm_n(), t_coriolis_terms_rlm::copy_coriolis_terms_rlm(), m_work_time::end_elapsed_time(), spherical_srs_n::finish_send_recv_sph(), t_sph_fft_selector::fwd_fft_select_to_send(), m_machine_parameter::iflag_debug, m_elapsed_labels_4_mhd::iflag_smhd_time, m_elapsed_labels_sph_trns::iflag_sph_time, m_elapsed_labels_4_mhd::ist_elapsed_smhd, m_elapsed_labels_sph_trns::ist_elapsed_sph, t_legendre_trans_select::sel_forward_legendre_trans(), and m_work_time::start_elapsed_time().
Referenced by sph_transforms_4_mhd::sph_forward_trans_4_mhd().