CALYPSO: gz_mpi_binary_head_io Module Reference
gz_mpi_binary_head_io Module Reference
Output merged binary field file using MPI-IO.
Functions/Subroutines
subroutine gz_mpi_write_byte_flag (IO_param)
subroutine gz_mpi_write_mul_inthead_b (IO_param, num, int_dat)
subroutine gz_mpi_write_merged_stack_b (IO_param, num_pe, i8stack)
subroutine gz_mpi_write_i8stack_head_b (IO_param, num, i8stack)
subroutine gz_mpi_write_mul_int8head_b (IO_param, num, int8_dat)
subroutine gz_mpi_write_mul_charahead_b (IO_param, num, chara_dat)
subroutine gz_mpi_write_mul_realhead_b (IO_param, num, real_dat)
subroutine gz_mpi_read_byte_check (IO_param)
subroutine gz_mpi_read_mul_inthead_b (IO_param, num, int_dat)
subroutine gz_mpi_read_merged_stack_b (IO_param, num_pe, i8stack)
subroutine gz_mpi_read_i8stack_head_b (IO_param, num, i8stack)
subroutine gz_mpi_read_mul_int8head_b (IO_param, num, int8_dat)
subroutine gz_mpi_read_mul_charahead_b (IO_param, num, chara_dat)
subroutine gz_mpi_read_mul_realhead_b (IO_param, num, real_dat)
Variables
type(buffer_4_gzip), private zbuf
Detailed Description
Output merged binary field file using MPI-IO.
      subroutine gz_mpi_write_byte_flag(IO_param)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
      subroutine gz_mpi_write_mul_inthead_b(IO_param, num, int_dat)
      subroutine gz_mpi_write_merged_stack_b                          &
     &         (IO_param, num_pe, i8stack)
      subroutine gz_mpi_write_i8stack_head_b(IO_param, num, i8stack)
      subroutine gz_mpi_write_mul_int8head_b(IO_param, num, int8_dat)
      subroutine gz_mpi_write_mul_charahead_b(IO_param, num, chara_dat)
      subroutine gz_mpi_write_mul_realhead_b(IO_param, num, real_dat)
      subroutine gz_mpi_read_mul_inthead_b(IO_param, num, int_dat)
      subroutine gz_mpi_read_merged_stack_b(IO_param, num_pe, i8stack)
      subroutine gz_mpi_read_i8stack_head_b(IO_param, num, i8stack)
      subroutine gz_mpi_read_mul_int8head_b(IO_param, num, int_dat)
      subroutine gz_mpi_read_mul_charahead_b(IO_param, num, chara_dat)
      subroutine gz_mpi_read_mul_realhead_b(IO_param, num, real_dat)
Function/Subroutine Documentation
gz_mpi_read_byte_check()
subroutine gz_mpi_binary_head_io::gz_mpi_read_byte_check (type(calypso_mpi_io_params), intent(inout) IO_param)
Definition at line 212 of file gz_MPI_binary_head_IO.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), calypso_mpi_int4::calypso_mpi_bcast_one_int4(), calypso_mpi_int8::calypso_mpi_bcast_one_int8(), m_calypso_mpi_io::calypso_mpi_seek_read_gz(), t_buffer_4_gzip::dealloc_zip_buffer(), data_convert_by_zlib::infleate_endian_flag(), m_precision::kint, calypso_mpi::my_rank, and zbuf.
Referenced by gz_mpi_binary_datum_io::open_read_gz_mpi_file_b().
gz_mpi_read_i8stack_head_b()
subroutine gz_mpi_binary_head_io::gz_mpi_read_i8stack_head_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint_gl), intent(in) num, integer(kind = kint_gl), dimension(0:num), intent(inout) i8stack)
Definition at line 281 of file gz_MPI_binary_head_IO.f90.
References gz_mpi_read_mul_int8head_b().
gz_mpi_read_merged_stack_b()
subroutine gz_mpi_binary_head_io::gz_mpi_read_merged_stack_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer, intent(in) num_pe, integer(kind = kint_gl), dimension(0:num_pe), intent(inout) i8stack)
Definition at line 264 of file gz_MPI_binary_head_IO.f90.
References gz_mpi_read_mul_int8head_b().
Referenced by gz_mpi_binary_data_io::gz_mpi_read_1d_vector_b(), gz_mpi_binary_data_io::gz_mpi_read_int8_vector_b(), and gz_field_block_mpi_io_b::gz_read_field_header_mpi_b().
gz_mpi_read_mul_charahead_b()
subroutine gz_mpi_binary_head_io::gz_mpi_read_mul_charahead_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) num, character(len=kchara), dimension(num), intent(inout) chara_dat)
Definition at line 334 of file gz_MPI_binary_head_IO.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), calypso_mpi_char::calypso_mpi_bcast_character(), calypso_mpi_int8::calypso_mpi_bcast_one_int8(), m_calypso_mpi_io::calypso_mpi_seek_read_gz(), transfer_to_long_integers::cast_long(), t_buffer_4_gzip::dealloc_zip_buffer(), data_convert_by_zlib::infleate_1d_character_b(), m_precision::kchara, calypso_mpi::my_rank, and zbuf.
Referenced by gz_mpi_groups_io_b::gz_mpi_read_group_data_b(), gz_mpi_groups_io_b::gz_mpi_read_surf_grp_data_b(), gz_field_file_mpi_io_b::gz_rd_alloc_st_fld_file_mpi_b(), gz_field_file_mpi_io_b::gz_rd_alloc_st_fld_head_mpi_b(), gz_ucd_field_mpi_io_b::gz_rd_alloc_ucd_fld_file_mpi_b(), gz_field_file_mpi_io_b::gz_read_step_field_file_mpi_b(), and gz_ucd_field_mpi_io_b::gz_read_ucd_field_file_mpi_b().
gz_mpi_read_mul_int8head_b()
subroutine gz_mpi_binary_head_io::gz_mpi_read_mul_int8head_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint_gl), intent(in) num, integer(kind = kint_gl), dimension(num), intent(inout) int8_dat)
Definition at line 296 of file gz_MPI_binary_head_IO.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), byte_swap_f::byte_swap_int8_f(), calypso_mpi_int8::calypso_mpi_bcast_int8(), calypso_mpi_int8::calypso_mpi_bcast_one_int8(), m_calypso_mpi_io::calypso_mpi_seek_read_gz(), t_buffer_4_gzip::dealloc_zip_buffer(), m_machine_parameter::iendian_flip, data_convert_by_zlib::infleate_int8_vector_b(), m_precision::kint_gl, calypso_mpi::my_rank, and zbuf.
Referenced by gz_mpi_read_i8stack_head_b(), gz_mpi_read_merged_stack_b(), and gz_mpi_read_mul_inthead_b().
gz_mpi_read_mul_inthead_b()
subroutine gz_mpi_binary_head_io::gz_mpi_read_mul_inthead_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint), intent(in) num, integer(kind = kint), dimension(num), intent(inout) int_dat)
Definition at line 244 of file gz_MPI_binary_head_IO.f90.
References transfer_to_long_integers::alloc_1d_i8array(), transfer_to_long_integers::cast_long(), transfer_to_long_integers::dup_to_short_array(), and gz_mpi_read_mul_int8head_b().
Referenced by gz_mpi_spherical_model_io_b::gz_mpi_read_gl_reso_sph_b(), gz_mpi_binary_datum_io::gz_mpi_read_one_inthead_b(), gz_mpi_binary_datum_io::gz_mpi_read_process_id_b(), gz_field_file_mpi_io_b::gz_rd_alloc_st_fld_file_mpi_b(), gz_field_file_mpi_io_b::gz_rd_alloc_st_fld_head_mpi_b(), gz_ucd_field_mpi_io_b::gz_rd_alloc_ucd_fld_file_mpi_b(), gz_field_file_mpi_io_b::gz_read_step_field_file_mpi_b(), and gz_ucd_field_mpi_io_b::gz_read_ucd_field_file_mpi_b().
gz_mpi_read_mul_realhead_b()
subroutine gz_mpi_binary_head_io::gz_mpi_read_mul_realhead_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) num, real(kind = kreal), dimension(num), intent(inout) real_dat)
Definition at line 368 of file gz_MPI_binary_head_IO.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), byte_swap_f::byte_swap_real_f(), calypso_mpi_int8::calypso_mpi_bcast_one_int8(), calypso_mpi_real::calypso_mpi_bcast_real(), m_calypso_mpi_io::calypso_mpi_seek_read_gz(), transfer_to_long_integers::cast_long(), t_buffer_4_gzip::dealloc_zip_buffer(), m_machine_parameter::iendian_flip, data_convert_by_zlib::infleate_1d_vector_b(), m_precision::kreal, calypso_mpi::my_rank, and zbuf.
Referenced by gz_mpi_binary_datum_io::gz_mpi_read_one_realhead_b().
gz_mpi_write_byte_flag()
subroutine gz_mpi_binary_head_io::gz_mpi_write_byte_flag (type(calypso_mpi_io_params), intent(inout) IO_param)
Definition at line 49 of file gz_MPI_binary_head_IO.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), calypso_mpi_int8::calypso_mpi_bcast_one_int8(), m_calypso_mpi_io::calypso_mpi_seek_write_gz(), t_buffer_4_gzip::dealloc_zip_buffer(), data_convert_by_zlib::defleate_endian_flag(), m_precision::kint, calypso_mpi::my_rank, and zbuf.
Referenced by gz_mpi_binary_datum_io::open_write_gz_mpi_file_b().
gz_mpi_write_i8stack_head_b()
subroutine gz_mpi_binary_head_io::gz_mpi_write_i8stack_head_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint_gl), intent(in) num, integer(kind = kint_gl), dimension(0:num), intent(in) i8stack)
Definition at line 112 of file gz_MPI_binary_head_IO.f90.
References gz_mpi_write_mul_int8head_b().
gz_mpi_write_merged_stack_b()
subroutine gz_mpi_binary_head_io::gz_mpi_write_merged_stack_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer, intent(in) num_pe, integer(kind = kint_gl), dimension(0:num_pe), intent(in) i8stack)
Definition at line 95 of file gz_MPI_binary_head_IO.f90.
References gz_mpi_write_mul_int8head_b().
Referenced by gz_mpi_binary_data_io::gz_mpi_write_1d_vector_b(), gz_mpi_binary_data_io::gz_mpi_write_int8_vector_b(), and gz_field_block_mpi_io_b::gz_write_field_data_mpi_b().
gz_mpi_write_mul_charahead_b()
subroutine gz_mpi_binary_head_io::gz_mpi_write_mul_charahead_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint), intent(in) num, character(len=kchara), dimension(num), intent(in) chara_dat)
Definition at line 153 of file gz_MPI_binary_head_IO.f90.
References calypso_mpi_int8::calypso_mpi_bcast_one_int8(), m_calypso_mpi_io::calypso_mpi_seek_write_gz(), t_buffer_4_gzip::dealloc_zip_buffer(), data_convert_by_zlib::defleate_1d_character_b(), calypso_mpi::my_rank, and zbuf.
Referenced by gz_mpi_groups_io_b::gz_mpi_write_grp_data_b(), gz_mpi_groups_io_b::gz_mpi_write_surf_grp_data_b(), gz_field_block_mpi_io_b::gz_write_field_data_mpi_b(), and gz_ucd_file_mpi_io::gz_write_ucd_data_mpi_b().
gz_mpi_write_mul_int8head_b()
subroutine gz_mpi_binary_head_io::gz_mpi_write_mul_int8head_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint_gl), intent(in) num, integer(kind = kint_gl), dimension(num), intent(in) int8_dat)
Definition at line 126 of file gz_MPI_binary_head_IO.f90.
References calypso_mpi_int8::calypso_mpi_bcast_one_int8(), m_calypso_mpi_io::calypso_mpi_seek_write_gz(), t_buffer_4_gzip::dealloc_zip_buffer(), data_convert_by_zlib::defleate_int8_vector_b(), calypso_mpi::my_rank, and zbuf.
Referenced by gz_mpi_write_i8stack_head_b(), gz_mpi_write_merged_stack_b(), and gz_mpi_write_mul_inthead_b().
gz_mpi_write_mul_inthead_b()
subroutine gz_mpi_binary_head_io::gz_mpi_write_mul_inthead_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint), intent(in) num, integer(kind = kint), dimension(num), intent(in) int_dat)
Definition at line 75 of file gz_MPI_binary_head_IO.f90.
References transfer_to_long_integers::cast_long(), transfer_to_long_integers::dealloc_1d_i8array(), transfer_to_long_integers::dup_from_short_array(), and gz_mpi_write_mul_int8head_b().
Referenced by gz_mpi_spherical_model_io_b::gz_mpi_write_gl_reso_sph_b(), gz_mpi_binary_datum_io::gz_mpi_write_one_inthead_b(), gz_mpi_binary_datum_io::gz_mpi_write_process_id_b(), gz_field_block_mpi_io_b::gz_write_field_data_mpi_b(), and gz_ucd_file_mpi_io::gz_write_ucd_data_mpi_b().
gz_mpi_write_mul_realhead_b()
subroutine gz_mpi_binary_head_io::gz_mpi_write_mul_realhead_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint), intent(in) num, real(kind = kreal), dimension(num), intent(inout) real_dat)
Definition at line 182 of file gz_MPI_binary_head_IO.f90.
References calypso_mpi_int8::calypso_mpi_bcast_one_int8(), m_calypso_mpi_io::calypso_mpi_seek_write_gz(), t_buffer_4_gzip::dealloc_zip_buffer(), data_convert_by_zlib::defleate_1d_vector_b(), calypso_mpi::my_rank, and zbuf.
Referenced by gz_mpi_binary_datum_io::gz_mpi_write_one_realhead_b().
Variable Documentation
zbuf
type(buffer_4_gzip), private gz_mpi_binary_head_io::zbuf private
Definition at line 41 of file gz_MPI_binary_head_IO.f90.
Referenced by gz_mpi_read_byte_check(), gz_mpi_read_mul_charahead_b(), gz_mpi_read_mul_int8head_b(), gz_mpi_read_mul_realhead_b(), gz_mpi_write_byte_flag(), gz_mpi_write_mul_charahead_b(), gz_mpi_write_mul_int8head_b(), and gz_mpi_write_mul_realhead_b().