CALYPSO: t_legendre_work_sym_mat_jt Module Reference
t_legendre_work_sym_mat_jt Module Reference
Work array for forward Legendre transform useing mat multi
data are strored communication buffer.
Data Types
type leg_trns_theta_omp_work
Work structure for Legendre trasform by large matmul.
Functions/Subroutines
subroutine init_legendre_sym_mat_jt (sph_rtm, sph_rlm, leg, idx_trns, nvector, nscalar, WK_l_tsp)
subroutine init_legendre_sym_mat_tj (sph_rtm, sph_rlm, leg, idx_trns, nvector, nscalar, WK_l_tsp)
subroutine dealloc_leg_sym_mat_jt (WK_l_tsp)
subroutine dealloc_leg_sym_mat_tj (WK_l_tsp)
subroutine, private count_leg_sym_matmul_mtr (nidx_rtm, nvector, nscalar, idx_trns, WK_l_tsp)
subroutine, private count_symmetric_leg_lj_omp (mphi_rtm, idx_trns, WK_l_tsp)
subroutine, private init_each_sym_leg_omp_mat_jt (nth_rtm, mphi_rtm, jmax_rlm, lstack_rlm, P_rtm, dPdt_rtm, WK_l_tsp)
subroutine init_each_sym_leg_omp_mat_tj (nth_rtm, mphi_rtm, jmax_rlm, lstack_rlm, P_rtm, dPdt_rtm, WK_l_tsp)
subroutine, private dealloc_sym_leg_omp_mat_jt (WK_l_tsp)
subroutine dealloc_sym_leg_omp_mat_tj (WK_l_tsp)
Detailed Description
Work array for forward Legendre transform useing mat multi
data are strored communication buffer.
      subroutine init_legendre_sym_mat_jt(sph_rtm, sph_rlm, leg,      &
     &          idx_trns, nvector, nscalar, WK_l_tsp)
      subroutine init_legendre_sym_mat_tj(sph_rtm, sph_rlm, leg,      &
     &          idx_trns, nvector, nscalar, WK_l_tsp)
        type(sph_rtm_grid), intent(in) :: sph_rtm
        type(sph_rlm_grid), intent(in) :: sph_rlm
        type(legendre_4_sph_trans), intent(in) :: leg
        type(index_4_sph_trans), intent(in) :: idx_trns
        type(leg_trns_theta_omp_work), intent(inout) :: WK_l_tsp
      subroutine dealloc_leg_sym_mat_jt(mphi_rtm, WK_l_tsp)
      subroutine dealloc_leg_sym_mat_tj(WK_l_tsp)
        type(leg_trns_theta_omp_work), intent(inout) :: WK_l_tsp
     field data for Legendre transform
       original layout: vr_rtm(l_rtm,m_rtm,k_rtm,icomp)
       size: vr_rtm(nth_rtm,nidx_rtm(1)*ncomp,nidx_rtm(3))
      real(kind = kreal), allocatable :: vr_rtm(:,:,:)
     spectr data for Legendre transform
       original layout: sp_rlm(j_rlm,k_rtm,icomp)
        size: sp_rlm(nidx_rlm(2),nidx_rtm(1)*ncomp)
      real(kind = kreal), allocatable :: sp_rlm(:,:)
Parameters
ncomp Total number of components for spherical transform
nvector Number of vector for spherical transform
nscalar Number of scalar (including tensor components) for spherical transform
Function/Subroutine Documentation
count_leg_sym_matmul_mtr()
subroutine, private t_legendre_work_sym_mat_jt::count_leg_sym_matmul_mtr (integer(kind = kint), dimension(3), intent(in) nidx_rtm, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(index_4_sph_trans), intent(in) idx_trns, type(leg_trns_theta_omp_work), intent(inout) WK_l_tsp) private
Definition at line 249 of file t_legendre_work_sym_mat_jt.f90.
Referenced by init_legendre_sym_mat_jt(), and init_legendre_sym_mat_tj().
count_symmetric_leg_lj_omp()
subroutine, private t_legendre_work_sym_mat_jt::count_symmetric_leg_lj_omp (integer(kind = kint), intent(in) mphi_rtm, type(index_4_sph_trans), intent(in) idx_trns, type(leg_trns_theta_omp_work), intent(inout) WK_l_tsp) private
Definition at line 268 of file t_legendre_work_sym_mat_jt.f90.
Referenced by init_legendre_sym_mat_jt(), and init_legendre_sym_mat_tj().
dealloc_leg_sym_mat_jt()
subroutine t_legendre_work_sym_mat_jt::dealloc_leg_sym_mat_jt (type(leg_trns_theta_omp_work), intent(inout) WK_l_tsp)
Definition at line 204 of file t_legendre_work_sym_mat_jt.f90.
References t_field_matrices_4_legendre::dealloc_field_mat_omp(), t_field_matrices_4_legendre::dealloc_spectr_mat_omp(), dealloc_sym_leg_omp_mat_jt(), and m_machine_parameter::np_smp.
Referenced by t_legendre_trans_select::sel_finalize_legendre_trans().
dealloc_leg_sym_mat_tj()
subroutine t_legendre_work_sym_mat_jt::dealloc_leg_sym_mat_tj (type(leg_trns_theta_omp_work), intent(inout) WK_l_tsp)
Definition at line 226 of file t_legendre_work_sym_mat_jt.f90.
References t_field_matrices_4_legendre::dealloc_field_mat_omp(), t_field_matrices_4_legendre::dealloc_spectr_mat_omp(), dealloc_sym_leg_omp_mat_tj(), and m_machine_parameter::np_smp.
Referenced by t_legendre_trans_select::sel_finalize_legendre_trans().
dealloc_sym_leg_omp_mat_jt()
subroutine, private t_legendre_work_sym_mat_jt::dealloc_sym_leg_omp_mat_jt (type(leg_trns_theta_omp_work), intent(inout) WK_l_tsp) private
Definition at line 369 of file t_legendre_work_sym_mat_jt.f90.
References t_legendre_matrix_4_trns::dealloc_each_sym_leg_mat_jt(), and m_machine_parameter::np_smp.
Referenced by dealloc_leg_sym_mat_jt().
dealloc_sym_leg_omp_mat_tj()
subroutine t_legendre_work_sym_mat_jt::dealloc_sym_leg_omp_mat_tj (type(leg_trns_theta_omp_work), intent(inout) WK_l_tsp)
Definition at line 386 of file t_legendre_work_sym_mat_jt.f90.
References t_legendre_matrix_4_trns::dealloc_each_sym_leg_mat_tj(), and m_machine_parameter::np_smp.
Referenced by dealloc_leg_sym_mat_tj().
init_each_sym_leg_omp_mat_jt()
subroutine, private t_legendre_work_sym_mat_jt::init_each_sym_leg_omp_mat_jt (integer(kind = kint), intent(in) nth_rtm, integer(kind = kint), intent(in) mphi_rtm, integer(kind = kint), intent(in) jmax_rlm, integer(kind = kint), dimension(0:mphi_rtm), intent(in) lstack_rlm, real(kind= kreal), dimension(nth_rtm,jmax_rlm), intent(in) P_rtm, real(kind= kreal), dimension(nth_rtm,jmax_rlm), intent(in) dPdt_rtm, type(leg_trns_theta_omp_work), intent(inout) WK_l_tsp) private
Definition at line 293 of file t_legendre_work_sym_mat_jt.f90.
References t_legendre_matrix_4_trns::alloc_each_sym_leg_omp_mat_jt(), t_set_legendre_4_sph_trans::copy_each_sym_leg_omp_mat_jt(), and m_machine_parameter::np_smp.
Referenced by init_legendre_sym_mat_jt().
init_each_sym_leg_omp_mat_tj()
subroutine t_legendre_work_sym_mat_jt::init_each_sym_leg_omp_mat_tj (integer(kind = kint), intent(in) nth_rtm, integer(kind = kint), intent(in) mphi_rtm, integer(kind = kint), intent(in) jmax_rlm, integer(kind = kint), dimension(0:mphi_rtm), intent(in) lstack_rlm, real(kind= kreal), dimension(nth_rtm,jmax_rlm), intent(in) P_rtm, real(kind= kreal), dimension(nth_rtm,jmax_rlm), intent(in) dPdt_rtm, type(leg_trns_theta_omp_work), intent(inout) WK_l_tsp)
Definition at line 331 of file t_legendre_work_sym_mat_jt.f90.
References t_legendre_matrix_4_trns::alloc_each_sym_leg_omp_mat_tj(), t_set_legendre_4_sph_trans::copy_each_sym_leg_omp_mat_tj(), and m_machine_parameter::np_smp.
Referenced by init_legendre_sym_mat_tj().
init_legendre_sym_mat_jt()
subroutine t_legendre_work_sym_mat_jt::init_legendre_sym_mat_jt (type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(legendre_4_sph_trans), intent(in) leg, type(index_4_sph_trans), intent(in) idx_trns, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(leg_trns_theta_omp_work), intent(inout) WK_l_tsp)
Definition at line 103 of file t_legendre_work_sym_mat_jt.f90.
References t_field_matrices_4_legendre::alloc_field_mat_omp(), t_field_matrices_4_legendre::alloc_spectr_mat_omp(), count_leg_sym_matmul_mtr(), t_field_matrices_4_legendre::count_size_of_field_mat_omp(), count_symmetric_leg_lj_omp(), init_each_sym_leg_omp_mat_jt(), and m_machine_parameter::np_smp.
Referenced by t_legendre_trans_select::sel_init_legendre_trans().
init_legendre_sym_mat_tj()
subroutine t_legendre_work_sym_mat_jt::init_legendre_sym_mat_tj (type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(legendre_4_sph_trans), intent(in) leg, type(index_4_sph_trans), intent(in) idx_trns, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(leg_trns_theta_omp_work), intent(inout) WK_l_tsp)
Definition at line 153 of file t_legendre_work_sym_mat_jt.f90.
References t_field_matrices_4_legendre::alloc_field_mat_omp(), t_field_matrices_4_legendre::alloc_spectr_mat_omp(), count_leg_sym_matmul_mtr(), t_field_matrices_4_legendre::count_size_of_field_mat_omp(), count_symmetric_leg_lj_omp(), init_each_sym_leg_omp_mat_tj(), and m_machine_parameter::np_smp.
Referenced by t_legendre_trans_select::sel_init_legendre_trans().