CALYPSO: sel_comp_labels_by_coord Module Reference
sel_comp_labels_by_coord Module Reference
Constants for geometry data.
Functions/Subroutines
subroutine sel_coord_vector_comp_labels (iflag_coord, field_name, label_comp)
subroutine sel_coord_tensor_comp_labels (iflag_coord, field_name, label_comp)
Detailed Description
Constants for geometry data.
      subroutine sel_coord_vector_comp_labels(iflag_coord,            &
     &          field_name, label_comp)
Function/Subroutine Documentation
sel_coord_tensor_comp_labels()
subroutine sel_comp_labels_by_coord::sel_coord_tensor_comp_labels (integer(kind = kint), intent(in) iflag_coord, character(len=kchara), intent(in) field_name, character(len=kchara), dimension(6), intent(inout) label_comp)
Definition at line 59 of file sel_comp_labels_by_coord.f90.
References add_direction_labels::add_tensor_direction_label_cyl(), add_direction_labels::add_tensor_direction_label_rtp(), add_direction_labels::add_tensor_direction_label_xyz(), m_geometry_constants::iflag_cylindrical, and m_geometry_constants::iflag_spherical.
sel_coord_vector_comp_labels()
subroutine sel_comp_labels_by_coord::sel_coord_vector_comp_labels (integer(kind = kint), intent(in) iflag_coord, character(len=kchara), intent(in) field_name, character(len=kchara), dimension(3), intent(inout) label_comp)
Definition at line 33 of file sel_comp_labels_by_coord.f90.
References add_direction_labels::add_vector_direction_label_cyl(), add_direction_labels::add_vector_direction_label_rtp(), add_direction_labels::add_vector_direction_label_xyz(), m_geometry_constants::iflag_cylindrical, and m_geometry_constants::iflag_spherical.