CALYPSO: t_ctl_data_const_sph_mesh Module Reference
t_ctl_data_const_sph_mesh Module Reference
Data Types
type sph_mesh_generation_ctl
Functions/Subroutines
subroutine read_control_4_const_shell (file_name, gen_SPH_ctl)
subroutine, private read_sph_shell_define_ctl (id_control, hd_block, gen_SPH_ctl, c_buf)
subroutine, private bcast_sph_shell_define_ctl (gen_SPH_ctl)
Variables
integer(kind=kint), parameter, private control_file_code = 11
character(len=kchara), parameter, private hd_mhd_ctl = 'MHD_control'
character(len=kchara), parameter, private hd_platform = 'data_files_def'
character(len=kchara), parameter, private hd_sph_shell = 'spherical_shell_ctl'
Function/Subroutine Documentation
bcast_sph_shell_define_ctl()
subroutine, private t_ctl_data_const_sph_mesh::bcast_sph_shell_define_ctl (type(sph_mesh_generation_ctl), intent(inout) gen_SPH_ctl) private
Definition at line 120 of file t_ctl_data_const_sph_mesh.f90.
References bcast_4_platform_ctl::bcast_ctl_data_4_platform(), t_ctl_data_gen_sph_shell::bcast_parallel_shell_ctl(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by read_control_4_const_shell().
read_control_4_const_shell()
subroutine t_ctl_data_const_sph_mesh::read_control_4_const_shell (character(len=kchara), intent(in) file_name, type(sph_mesh_generation_ctl), intent(inout) gen_SPH_ctl)
Definition at line 65 of file t_ctl_data_const_sph_mesh.f90.
References bcast_sph_shell_define_ctl(), control_file_code, hd_mhd_ctl, t_read_control_elements::load_one_line_from_control(), calypso_mpi::my_rank, and read_sph_shell_define_ctl().
Referenced by analyzer_check_sph_grids::init_check_sph_grids(), analyzer_gen_sph_grids::init_gen_sph_grids(), and analyzer_test_sph::init_test_sph().
read_sph_shell_define_ctl()
subroutine, private t_ctl_data_const_sph_mesh::read_sph_shell_define_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(sph_mesh_generation_ctl), intent(inout) gen_SPH_ctl, type(buffer_for_control), intent(inout) c_buf) private
Definition at line 93 of file t_ctl_data_const_sph_mesh.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_platform, hd_sph_shell, t_read_control_elements::load_one_line_from_control(), t_ctl_data_4_platforms::read_control_platforms(), and t_ctl_data_gen_sph_shell::read_parallel_shell_in_mhd_ctl().
Referenced by read_control_4_const_shell().
Variable Documentation
control_file_code
integer(kind=kint), parameter, private t_ctl_data_const_sph_mesh::control_file_code = 11 private
Definition at line 33 of file t_ctl_data_const_sph_mesh.f90.
Referenced by read_control_4_const_shell().
hd_mhd_ctl
character(len=kchara), parameter, private t_ctl_data_const_sph_mesh::hd_mhd_ctl = 'MHD_control' private
Definition at line 47 of file t_ctl_data_const_sph_mesh.f90.
Referenced by read_control_4_const_shell().
hd_platform
character(len=kchara), parameter, private t_ctl_data_const_sph_mesh::hd_platform = 'data_files_def' private
Definition at line 52 of file t_ctl_data_const_sph_mesh.f90.
Referenced by read_sph_shell_define_ctl().
hd_sph_shell
character(len=kchara), parameter, private t_ctl_data_const_sph_mesh::hd_sph_shell = 'spherical_shell_ctl' private
Definition at line 54 of file t_ctl_data_const_sph_mesh.f90.
Referenced by read_sph_shell_define_ctl().