CALYPSO: set_node_for_sections Module Reference
set_node_for_sections Module Reference
Find nodes to make sectioning data.
Functions/Subroutines
subroutine count_node_on_edge_4_psf (numedge, nnod_4_edge, ie_edge, interior_edge, edge_search, psf_list)
subroutine set_node_on_edge_4_psf (numedge, nnod_4_edge, ie_edge, interior_edge, edge_search, psf_list)
Detailed Description
Find nodes to make sectioning data.
      subroutine count_node_on_edge_4_psf                             &
     &         (numedge, nnod_4_edge, ie_edge, interior_edge,         &
     &          ie_edge, edge_search, psf_list)
      subroutine set_node_on_edge_4_psf(numedge, nnod_4_edge,         &
     &          ie_edge, interior_edge, edge_search, psf_list)
Function/Subroutine Documentation
count_node_on_edge_4_psf()
subroutine set_node_for_sections::count_node_on_edge_4_psf (integer(kind = kint), intent(in) numedge, integer(kind = kint), intent(in) nnod_4_edge, integer(kind = kint), dimension(numedge,nnod_4_edge), intent(in) ie_edge, integer(kind = kint), dimension(numedge), intent(in) interior_edge, type(sect_search_list), intent(in) edge_search, type(sectioning_list), intent(inout) psf_list)
Definition at line 30 of file set_node_for_sections.f90.
References m_constants::zero.
Referenced by set_nodes_for_psf::count_nodes_4_iso(), and set_nodes_for_psf::count_nodes_4_psf().
set_node_on_edge_4_psf()
subroutine set_node_for_sections::set_node_on_edge_4_psf (integer(kind = kint), intent(in) numedge, integer(kind = kint), intent(in) nnod_4_edge, integer(kind = kint), dimension(numedge,nnod_4_edge), intent(in) ie_edge, integer(kind = kint), dimension(numedge), intent(in) interior_edge, type(sect_search_list), intent(in) edge_search, type(sectioning_list), intent(inout) psf_list)
Definition at line 96 of file set_node_for_sections.f90.
References m_machine_parameter::np_smp, and m_constants::zero.
Referenced by set_nodes_for_psf::set_nodes_4_iso(), and set_nodes_for_psf::set_nodes_4_psf().