CALYPSO: assemble_sph_fields Module Reference
assemble_sph_fields Module Reference
routines for parallel spectr data assemble
Functions/Subroutines
subroutine share_org_sph_rj_data (np_sph_org, org_sph_mesh)
subroutine share_org_spectr_field_names (np_sph_org, org_sph_phys)
subroutine share_new_spectr_field_names (new_sph_mesh, new_sph_phys)
subroutine load_new_spectr_rj_data (np_sph_org, org_sph_mesh, new_sph_mesh, j_table)
subroutine extend_potential_magne (sph, r_itp, sph_phys)
subroutine extend_inner_core_scalar (field_name, sph, r_itp, sph_phys)
subroutine, private extend_potential_magne_type (is_magne, ntot_phys_rj, sph, kr_inner_domain, kr_outer_domain, d_rj)
subroutine, private extend_inner_core_scl_type (is_field, ntot_phys_rj, sph, kr_inner_domain, d_rj)
Detailed Description
routines for parallel spectr data assemble
      subroutine share_org_sph_rj_data(np_sph_org, org_sph_mesh)
        type(sph_mesh_data), intent(inout) :: org_sph_mesh(np_sph_org)
      subroutine share_org_spectr_field_names                         &
     &         (np_sph_org, org_sph_phys)
        type(phys_data), intent(inout) :: org_sph_phys(np_sph_org)
      subroutine share_new_spectr_field_names                         &
     &         (np_sph_new, new_sph_mesh, new_sph_phys)
        type(sph_mesh_data), intent(in) :: new_sph_mesh
        type(phys_data), intent(inout) :: new_sph_phys
      subroutine load_new_spectr_rj_data(np_sph_org, org_sph_mesh,    &
     &                                   new_sph_mesh, j_table)
        type(sph_mesh_data), intent(in) :: org_sph_mesh(np_sph_org)
        type(sph_mesh_data), intent(in) :: new_sph_mesh
        type(rj_assemble_tbl), intent(inout)                          &
       &                             :: j_table(np_sph_org,np_sph_new)
      subroutine extend_potential_magne(sph, r_itp, sph_phys)
      subroutine extend_inner_core_scalar                             &
     &         (field_name, sph, r_itp, sph_phys)
        type(sph_grids), intent(in) :: sph
        type(sph_radial_itp_data), intent(in) :: r_itp
        type(phys_data), intent(inout) :: sph_phys
Function/Subroutine Documentation
extend_inner_core_scalar()
subroutine assemble_sph_fields::extend_inner_core_scalar (character(len = kchara), intent(in) field_name, type(sph_grids), intent(in) sph, type(sph_radial_itp_data), intent(in) r_itp, type(phys_data), intent(inout) sph_phys)
Definition at line 169 of file assemble_sph_fields.f90.
References extend_inner_core_scl_type().
Referenced by new_sph_restart::const_assembled_sph_data().
extend_inner_core_scl_type()
subroutine, private assemble_sph_fields::extend_inner_core_scl_type (integer(kind = kint), intent(in) is_field, integer(kind = kint), intent(in) ntot_phys_rj, type(sph_grids), intent(in) sph, integer(kind = kint), intent(in) kr_inner_domain, real(kind= kreal), dimension(sph%sph_rj%nnod_rj,ntot_phys_rj), intent(inout) d_rj) private
Definition at line 231 of file assemble_sph_fields.f90.
References extend_potential_field_t::ext_inside_scalar_t().
Referenced by extend_inner_core_scalar().
extend_potential_magne()
subroutine assemble_sph_fields::extend_potential_magne (type(sph_grids), intent(in) sph, type(sph_radial_itp_data), intent(in) r_itp, type(phys_data), intent(inout) sph_phys)
Definition at line 135 of file assemble_sph_fields.f90.
References extend_potential_magne_type(), and m_base_field_labels::magnetic_field.
Referenced by new_sph_restart::const_assembled_sph_data().
extend_potential_magne_type()
subroutine, private assemble_sph_fields::extend_potential_magne_type (integer(kind = kint), intent(in) is_magne, integer(kind = kint), intent(in) ntot_phys_rj, type(sph_grids), intent(in) sph, integer(kind = kint), intent(in) kr_inner_domain, integer(kind = kint), intent(in) kr_outer_domain, real(kind= kreal), dimension(sph%sph_rj%nnod_rj,ntot_phys_rj), intent(inout) d_rj) private
Definition at line 203 of file assemble_sph_fields.f90.
References extend_potential_field_t::ext_inside_potential_t(), and extend_potential_field_t::ext_outside_potential_t().
Referenced by extend_potential_magne().
load_new_spectr_rj_data()
subroutine assemble_sph_fields::load_new_spectr_rj_data (integer, intent(in) np_sph_org, type(sph_mesh_data), dimension(np_sph_org), intent(in) org_sph_mesh, type(sph_mesh_data), intent(in) new_sph_mesh, type(rj_assemble_tbl), dimension(np_sph_org), intent(inout) j_table)
Definition at line 110 of file assemble_sph_fields.f90.
References parallel_assemble_sph::alloc_each_mode_tbl_4_assemble(), and parallel_assemble_sph::set_mode_table_4_assemble().
Referenced by analyzer_assemble_sph::init_assemble_sph(), and analyzer_compare_sph_rst::init_compare_sph_restart().
share_new_spectr_field_names()
subroutine assemble_sph_fields::share_new_spectr_field_names (type(sph_mesh_data), intent(in) new_sph_mesh, type(phys_data), intent(inout) new_sph_phys)
Definition at line 93 of file assemble_sph_fields.f90.
References share_field_data::share_phys_field_names().
Referenced by analyzer_assemble_sph::init_assemble_sph(), analyzer_compare_sph_rst::init_compare_sph_restart(), and analyzer_rayleigh_cvt_sph::init_cvt_rayleigh_sph().
share_org_spectr_field_names()
subroutine assemble_sph_fields::share_org_spectr_field_names (integer, intent(in) np_sph_org, type(phys_data), dimension(np_sph_org), intent(inout) org_sph_phys)
Definition at line 74 of file assemble_sph_fields.f90.
References share_field_data::share_phys_field_names().
Referenced by analyzer_assemble_sph::init_assemble_sph(), and analyzer_compare_sph_rst::init_compare_sph_restart().
share_org_sph_rj_data()
subroutine assemble_sph_fields::share_org_sph_rj_data (integer, intent(in) np_sph_org, type(sph_mesh_data), dimension(np_sph_org), intent(inout) org_sph_mesh)
Definition at line 56 of file assemble_sph_fields.f90.
References share_spectr_index_data::share_sph_rj_data().
Referenced by analyzer_assemble_sph::init_assemble_sph(), and analyzer_compare_sph_rst::init_compare_sph_restart().