CALYPSO: set_from_recv_buffer Module Reference
set_from_recv_buffer Module Reference
Arbitrary components data communication.
Functions/Subroutines
subroutine set_from_recv_buf_1 (nnod_new, nnod_recv, inod_import, WR, X_new)
subroutine set_from_recv_buf_2 (nnod_new, nnod_recv, inod_import, WR, X_new)
subroutine set_from_recv_buf_3 (nnod_new, nnod_recv, inod_import, WR, X_new)
subroutine set_from_recv_buf_6 (nnod_new, nnod_recv, inod_import, WR, X_new)
subroutine set_from_recv_buf_n (NB, nnod_new, nnod_recv, inod_import, WR, X_new)
subroutine set_from_recv_buf_n_mod (NB, nnod_new, npe_recv, nnod_recv, istack_recv, inod_import, WR, X_new)
subroutine set_from_recv_buf_int (nnod_new, nnod_recv, inod_import, iWR, iX_new)
subroutine set_from_recv_buf_i8 (nnod_new, nnod_recv, inod_import, i8WR, i8X_new)
Detailed Description
Arbitrary components data communication.
      subroutine set_from_recv_buf_1(nnod_new,                        &
     &          nnod_recv, inod_import, WR, X_new)
      subroutine set_from_recv_buf_2(nnod_new,                        &
     &          nnod_recv, inod_import, WR, X_new)
      subroutine set_from_recv_buf_3(nnod_new,                        &
     &          nnod_recv, inod_import, WR, X_new)
      subroutine set_from_recv_buf_6(nnod_new,                        &
     &          nnod_recv, inod_import, WR, X_new)
      subroutine set_from_recv_buf_N(NB, nnod_new,                    &
     &          nnod_recv, inod_import, WR, X_new)
      subroutine set_from_recv_buf_N_mod(NB, nnod_new,                &
     &          npe_recv, nnod_recv, istack_recv, inod_import,        &
     &          WR, X_new)
      subroutine set_from_recv_buf_int(nnod_new,                      &
     &          nnod_recv, inod_import, iWR, iX_new)
      subroutine set_from_recv_buf_i8(nnod_new,                       &
     &          nnod_recv, inod_import, i8WR, i8X_new)
Parameters
NB Number of components for communication
nnod_new Number of components for destination
npe_recv Number of processses to receive
nnod_recv Number of data points to receive
istack_recv(0:npe_send) End points of receive buffer for each process
inod_import(nnod_recv) local node ID to copy from receive buffer
X_new(NB*nnod_new) Received data
Function/Subroutine Documentation
set_from_recv_buf_1()
subroutine set_from_recv_buffer::set_from_recv_buf_1 (integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) nnod_recv, integer(kind = kint), dimension(nnod_recv), intent(in) inod_import, real (kind=kreal), dimension(nnod_recv), intent(in) WR, real (kind=kreal), dimension(nnod_new), intent(inout) X_new)
Definition at line 54 of file set_from_recv_buffer.f90.
Referenced by select_copy_from_recv::sel_cppy_from_recv_buf_1().
set_from_recv_buf_2()
subroutine set_from_recv_buffer::set_from_recv_buf_2 (integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) nnod_recv, integer(kind = kint), dimension(nnod_recv), intent(in) inod_import, real (kind=kreal), dimension(2*nnod_recv), intent(in) WR, real (kind=kreal), dimension(2*nnod_new), intent(inout) X_new)
Definition at line 84 of file set_from_recv_buffer.f90.
Referenced by select_copy_from_recv::sel_cppy_from_recv_buf_2().
set_from_recv_buf_3()
subroutine set_from_recv_buffer::set_from_recv_buf_3 (integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) nnod_recv, integer(kind = kint), dimension(nnod_recv), intent(in) inod_import, real (kind=kreal), dimension(3*nnod_recv), intent(in) WR, real (kind=kreal), dimension(3*nnod_new), intent(inout) X_new)
Definition at line 115 of file set_from_recv_buffer.f90.
Referenced by select_copy_from_recv::sel_cppy_from_recv_buf_3().
set_from_recv_buf_6()
subroutine set_from_recv_buffer::set_from_recv_buf_6 (integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) nnod_recv, integer(kind = kint), dimension(nnod_recv), intent(in) inod_import, real (kind=kreal), dimension(6*nnod_recv), intent(in) WR, real (kind=kreal), dimension(6*nnod_new), intent(inout) X_new)
Definition at line 147 of file set_from_recv_buffer.f90.
Referenced by select_copy_from_recv::sel_cppy_from_recv_buf_6().
set_from_recv_buf_i8()
subroutine set_from_recv_buffer::set_from_recv_buf_i8 (integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) nnod_recv, integer(kind = kint), dimension(nnod_recv), intent(in) inod_import, integer(kind = kint_gl), dimension(nnod_recv), intent(in) i8WR, integer(kind = kint_gl), dimension(nnod_new), intent(inout) i8X_new)
Definition at line 284 of file set_from_recv_buffer.f90.
Referenced by select_copy_from_recv::sel_cppy_from_recv_buf_i8().
set_from_recv_buf_int()
subroutine set_from_recv_buffer::set_from_recv_buf_int (integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) nnod_recv, integer(kind = kint), dimension(nnod_recv), intent(in) inod_import, integer(kind = kint), dimension(nnod_recv), intent(in) iWR, integer(kind = kint), dimension(nnod_new), intent(inout) iX_new)
Definition at line 260 of file set_from_recv_buffer.f90.
Referenced by select_copy_from_recv::sel_cppy_from_recv_buf_int().
set_from_recv_buf_n()
subroutine set_from_recv_buffer::set_from_recv_buf_n (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) nnod_recv, integer(kind = kint), dimension(nnod_recv), intent(in) inod_import, real (kind=kreal), dimension(nb*nnod_recv), intent(in) WR, real (kind=kreal), dimension(nb*nnod_new), intent(inout) X_new)
Definition at line 182 of file set_from_recv_buffer.f90.
Referenced by sel_spherical_srs::sel_calypso_from_recv_n(), and select_copy_from_recv::sel_cppy_from_recv_buf_n().
set_from_recv_buf_n_mod()
subroutine set_from_recv_buffer::set_from_recv_buf_n_mod (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) npe_recv, integer(kind = kint), intent(in) nnod_recv, integer(kind = kint), dimension(0:npe_recv), intent(in) istack_recv, integer(kind = kint), dimension(nnod_recv), intent(in) inod_import, real (kind=kreal), dimension(nb*nnod_recv), intent(in) WR, real (kind=kreal), dimension(nb*nnod_new), intent(inout) X_new)
Definition at line 215 of file set_from_recv_buffer.f90.
Referenced by select_copy_from_recv::sel_cppy_from_recv_buf_n().