CALYPSO: t_schmidt_poly_on_rtm Module Reference
t_schmidt_poly_on_rtm Module Reference
Parameters for LEgendre transforms.
Data Types
type legendre_4_sph_trans
Structures for Legendre polynomials for spherical transform.
Functions/Subroutines
subroutine alloc_gauss_colat_rtm (nth_rtm, Plm_WK)
subroutine alloc_schmidt_normalize (jmax_rlm, jmax_rj, Plm_WK)
subroutine alloc_schmidt_poly_rtm (nth_rtm, jmax_rlm, Plm_WK)
subroutine alloc_trans_schmidt_rtm (nth_rtm, jmax_rlm, Plm_WK)
subroutine alloc_schmidt_p_rtm_pole (jmax_rlm, Plm_WK)
subroutine alloc_gauss_colatitude_rtp (nth_rtp, Plm_WK)
subroutine dealloc_gauss_colat_rtm (Plm_WK)
subroutine dealloc_schmidt_poly_rtm (Plm_WK)
subroutine dealloc_trans_schmidt_rtm (Plm_WK)
subroutine dealloc_schmidt_p_rtm_pole (Plm_WK)
subroutine dealloc_gauss_colatitude_rtp (Plm_WK)
subroutine check_gauss_colat_rtm (id_rank, nth_rtm, Plm_WK)
subroutine check_schmidt_poly_rtm (id_rank, sph_rtm, sph_rlm, Plm_WK)
subroutine check_schmidt_p_rtm_pole (id_rank, sph_rlm, Plm_WK)
Detailed Description
Parameters for LEgendre transforms.
      subroutine alloc_gauss_colat_rtm(nth_rtm, Plm_WK)
      subroutine alloc_schmidt_normalize(jmax_rlm, jmax_rj, Plm_WK)
      subroutine alloc_schmidt_poly_rtm(nth_rtm, jmax_rlm, Plm_WK)
      subroutine alloc_trans_schmidt_rtm(nth_rtm, jmax_rlm, Plm_WK)
      subroutine alloc_schmidt_p_rtm_pole(jmax_rlm, Plm_WK)
      subroutine alloc_gauss_colatitude_rtp(nth_rtp, Plm_WK)
        type(legendre_4_sph_trans), intent(inout) :: Plm_WK
      subroutine dealloc_gauss_colat_rtm(Plm_WK)
      subroutine dealloc_schmidt_poly_rtm(Plm_WK)
      subroutine dealloc_trans_schmidt_rtm(Plm_WK)
      subroutine dealloc_schmidt_p_rtm_pole(Plm_WK)
      subroutine dealloc_gauss_colatitude_rtp(Plm_WK)
        type(legendre_4_sph_trans), intent(inout) :: Plm_WK
      subroutine check_gauss_colat_rtm(id_rank, nth_rtm, Plm_WK)
      subroutine check_schmidt_poly_rtm                               &
     &         (id_rank, sph_rtm, sph_rlm, Plm_WK)
      subroutine check_schmidt_p_rtm_pole(id_rank, sph_rlm, Plm_WK)
        type(sph_rtm_grid), intent(in) :: sph_rtm
        type(sph_rlm_grid), intent(in) :: sph_rlm
        type(legendre_4_sph_trans), intent(in) :: Plm_WK
Function/Subroutine Documentation
alloc_gauss_colat_rtm()
subroutine t_schmidt_poly_on_rtm::alloc_gauss_colat_rtm (integer(kind = kint), intent(in) nth_rtm, type(legendre_4_sph_trans), intent(inout) Plm_WK)
Definition at line 79 of file t_schmidt_poly_on_rtm.f90.
Referenced by schmidt_poly_on_rtm_grid::set_gauss_points_rtm().
alloc_gauss_colatitude_rtp()
subroutine t_schmidt_poly_on_rtm::alloc_gauss_colatitude_rtp (integer(kind = kint), intent(in) nth_rtp, type(legendre_4_sph_trans), intent(inout) Plm_WK)
Definition at line 164 of file t_schmidt_poly_on_rtm.f90.
Referenced by set_params_sph_trans::const_conatitude_rtp().
alloc_schmidt_normalize()
subroutine t_schmidt_poly_on_rtm::alloc_schmidt_normalize (integer(kind = kint), intent(in) jmax_rlm, integer(kind = kint), intent(in) jmax_rj, type(legendre_4_sph_trans), intent(inout) Plm_WK)
Definition at line 100 of file t_schmidt_poly_on_rtm.f90.
Referenced by init_sph_trans::init_legendre_rtm().
alloc_schmidt_p_rtm_pole()
subroutine t_schmidt_poly_on_rtm::alloc_schmidt_p_rtm_pole (integer(kind = kint), intent(in) jmax_rlm, type(legendre_4_sph_trans), intent(inout) Plm_WK)
Definition at line 148 of file t_schmidt_poly_on_rtm.f90.
Referenced by init_sph_trans::init_legendre_rtm().
alloc_schmidt_poly_rtm()
subroutine t_schmidt_poly_on_rtm::alloc_schmidt_poly_rtm (integer(kind = kint), intent(in) nth_rtm, integer(kind = kint), intent(in) jmax_rlm, type(legendre_4_sph_trans), intent(inout) Plm_WK)
Definition at line 116 of file t_schmidt_poly_on_rtm.f90.
Referenced by init_sph_trans::init_legendre_rtm().
alloc_trans_schmidt_rtm()
subroutine t_schmidt_poly_on_rtm::alloc_trans_schmidt_rtm (integer(kind = kint), intent(in) nth_rtm, integer(kind = kint), intent(in) jmax_rlm, type(legendre_4_sph_trans), intent(inout) Plm_WK)
Definition at line 132 of file t_schmidt_poly_on_rtm.f90.
Referenced by init_sph_trans::init_legendre_rtm().
check_gauss_colat_rtm()
subroutine t_schmidt_poly_on_rtm::check_gauss_colat_rtm (integer, intent(in) id_rank, integer(kind = kint), intent(in) nth_rtm, type(legendre_4_sph_trans), intent(in) Plm_WK)
Definition at line 234 of file t_schmidt_poly_on_rtm.f90.
check_schmidt_p_rtm_pole()
subroutine t_schmidt_poly_on_rtm::check_schmidt_p_rtm_pole (integer, intent(in) id_rank, type(sph_rlm_grid), intent(in) sph_rlm, type(legendre_4_sph_trans), intent(in) Plm_WK)
Definition at line 284 of file t_schmidt_poly_on_rtm.f90.
check_schmidt_poly_rtm()
subroutine t_schmidt_poly_on_rtm::check_schmidt_poly_rtm (integer, intent(in) id_rank, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(legendre_4_sph_trans), intent(in) Plm_WK)
Definition at line 254 of file t_schmidt_poly_on_rtm.f90.
dealloc_gauss_colat_rtm()
subroutine t_schmidt_poly_on_rtm::dealloc_gauss_colat_rtm (type(legendre_4_sph_trans), intent(inout) Plm_WK)
Definition at line 178 of file t_schmidt_poly_on_rtm.f90.
dealloc_gauss_colatitude_rtp()
subroutine t_schmidt_poly_on_rtm::dealloc_gauss_colatitude_rtp (type(legendre_4_sph_trans), intent(inout) Plm_WK)
Definition at line 222 of file t_schmidt_poly_on_rtm.f90.
dealloc_schmidt_p_rtm_pole()
subroutine t_schmidt_poly_on_rtm::dealloc_schmidt_p_rtm_pole (type(legendre_4_sph_trans), intent(inout) Plm_WK)
Definition at line 212 of file t_schmidt_poly_on_rtm.f90.
dealloc_schmidt_poly_rtm()
subroutine t_schmidt_poly_on_rtm::dealloc_schmidt_poly_rtm (type(legendre_4_sph_trans), intent(inout) Plm_WK)
Definition at line 191 of file t_schmidt_poly_on_rtm.f90.
dealloc_trans_schmidt_rtm()
subroutine t_schmidt_poly_on_rtm::dealloc_trans_schmidt_rtm (type(legendre_4_sph_trans), intent(inout) Plm_WK)
Definition at line 202 of file t_schmidt_poly_on_rtm.f90.