CALYPSO: gz_vtk_file_io Module Reference
gz_vtk_file_io Module Reference
Output FEM field data to distributed VTK file (gzipped)
Functions/Subroutines
subroutine write_gz_parallel_vtk_file (id_rank, nprocs, istep, file_prefix)
subroutine write_gz_vtk_file (id_rank, gzip_name, ucd)
subroutine write_gz_vtk_phys (id_rank, gzip_name, ucd)
subroutine write_gz_vtk_grid (id_rank, gzip_name, ucd)
subroutine read_gz_vtk_file (id_rank, gzip_name, ucd)
subroutine read_gz_vtk_phys (id_rank, gzip_name, ucd)
subroutine read_gz_vtk_grid (id_rank, gzip_name, ucd)
subroutine read_alloc_gz_vtk_file (id_rank, gzip_name, ucd)
subroutine read_alloc_gz_vtk_phys (id_rank, gzip_name, ucd)
subroutine read_alloc_gz_vtk_grid (id_rank, gzip_name, ucd)
Variables
type(buffer_4_gzip), private zbuf_vtk
Detailed Description
Output FEM field data to distributed VTK file (gzipped)
      subroutine write_gz_parallel_vtk_file(id_rank, nprocs,          &
     &          istep, file_prefix)
      subroutine write_gz_vtk_file(gzip_name,                         &
     &          nnod, nele, nnod_ele, xx, ie, num_field,  ntot_comp,  &
     &          ncomp_field, field_name, d_nod)
      subroutine write_gz_vtk_phys(id_rank, gzip_name, ucd)
      subroutine write_gz_vtk_grid(id_rank, gzip_name, ucd)
        type(ucd_data), intent(in) :: ucd
      subroutine read_gz_vtk_file(id_rank, gzip_name, ucd)
      subroutine read_gz_vtk_phys(id_rank, gzip_name, ucd)
      subroutine read_gz_vtk_grid(id_rank, gzip_name, ucd)
        type(ucd_data), intent(inout) :: ucd
      subroutine read_alloc_gz_vtk_file(id_rank, gzip_name, ucd)
      subroutine read_alloc_gz_vtk_phys(id_rank, gzip_name, ucd)
      subroutine read_alloc_gz_vtk_grid(id_rank, gzip_name, ucd)
        type(ucd_data), intent(inout) :: ucd
Function/Subroutine Documentation
read_alloc_gz_vtk_file()
subroutine gz_vtk_file_io::read_alloc_gz_vtk_file (integer, intent(in) id_rank, character(len=kchara), intent(in) gzip_name, type(ucd_data), intent(inout) ucd)
Definition at line 234 of file gz_vtk_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_rd_gzfile_a(), gz_udt_to_vtk_data_io::read_alloc_gz_ucd_grd_from_vtk(), gz_udt_to_vtk_data_io::read_alloc_gz_udt_fld_from_vtk(), and zbuf_vtk.
Referenced by ucd_io_select::sel_read_alloc_ucd_file().
read_alloc_gz_vtk_grid()
subroutine gz_vtk_file_io::read_alloc_gz_vtk_grid (integer, intent(in) id_rank, character(len=kchara), intent(in) gzip_name, type(ucd_data), intent(inout) ucd)
Definition at line 275 of file gz_vtk_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_rd_gzfile_a(), gz_udt_to_vtk_data_io::read_alloc_gz_ucd_grd_from_vtk(), and zbuf_vtk.
Referenced by ucd_io_select::sel_read_alloc_ucd_file().
read_alloc_gz_vtk_phys()
subroutine gz_vtk_file_io::read_alloc_gz_vtk_phys (integer, intent(in) id_rank, character(len=kchara), intent(in) gzip_name, type(ucd_data), intent(inout) ucd)
Definition at line 255 of file gz_vtk_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_rd_gzfile_a(), gz_udt_to_vtk_data_io::read_alloc_gz_udt_fld_from_vtk(), and zbuf_vtk.
Referenced by ucd_io_select::sel_read_alloc_ucd_file(), ucd_io_select::sel_read_alloc_udt_file(), and ucd_io_select::sel_read_udt_param().
read_gz_vtk_file()
subroutine gz_vtk_file_io::read_gz_vtk_file (integer, intent(in) id_rank, character(len=kchara), intent(in) gzip_name, type(ucd_data), intent(inout) ucd)
Definition at line 172 of file gz_vtk_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_rd_gzfile_a(), gz_udt_to_vtk_data_io::read_gz_ucd_grd_from_vtk(), gz_udt_to_vtk_data_io::read_gz_udt_field_from_vtk(), and zbuf_vtk.
Referenced by ucd_io_select::sel_read_ucd_file().
read_gz_vtk_grid()
subroutine gz_vtk_file_io::read_gz_vtk_grid (integer, intent(in) id_rank, character(len=kchara), intent(in) gzip_name, type(ucd_data), intent(inout) ucd)
Definition at line 213 of file gz_vtk_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_rd_gzfile_a(), gz_udt_to_vtk_data_io::read_gz_ucd_grd_from_vtk(), and zbuf_vtk.
Referenced by ucd_io_select::sel_read_ucd_file().
read_gz_vtk_phys()
subroutine gz_vtk_file_io::read_gz_vtk_phys (integer, intent(in) id_rank, character(len=kchara), intent(in) gzip_name, type(ucd_data), intent(inout) ucd)
Definition at line 193 of file gz_vtk_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_rd_gzfile_a(), gz_udt_to_vtk_data_io::read_gz_udt_field_from_vtk(), and zbuf_vtk.
Referenced by ucd_io_select::sel_read_ucd_file(), and ucd_io_select::sel_read_udt_file().
write_gz_parallel_vtk_file()
subroutine gz_vtk_file_io::write_gz_parallel_vtk_file (integer, intent(in) id_rank, integer, intent(in) nprocs, integer(kind = kint), intent(in) istep, character(len=kchara), intent(in) file_prefix)
Definition at line 53 of file gz_vtk_file_IO.f90.
References set_parallel_file_name::add_gzip_extension(), set_parallel_file_name::add_int_suffix(), set_ucd_extensions::add_pvtk_extension(), skip_gz_comment::close_gzfile_a(), set_parallel_file_name::delete_directory_name(), gzip_file_access::gz_write_textbuf_no_lf(), m_field_file_format::iflag_vtk, skip_gz_comment::open_wt_gzfile_a(), set_ucd_file_names::set_parallel_ucd_file_name(), and zbuf_vtk.
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_file().
write_gz_vtk_file()
subroutine gz_vtk_file_io::write_gz_vtk_file (integer, intent(in) id_rank, character(len=kchara), intent(in) gzip_name, type(ucd_data), intent(in) ucd)
Definition at line 107 of file gz_vtk_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), skip_gz_comment::open_wt_gzfile_a(), gz_udt_to_vtk_data_io::write_gz_ucd_field_to_vtk(), gz_udt_to_vtk_data_io::write_gz_ucd_mesh_to_vtk(), and zbuf_vtk.
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_file(), ucd_io_select::sel_write_ucd_file(), and ucd_io_select::sel_write_udt_file().
write_gz_vtk_grid()
subroutine gz_vtk_file_io::write_gz_vtk_grid (integer, intent(in) id_rank, character(len=kchara), intent(in) gzip_name, type(ucd_data), intent(in) ucd)
Definition at line 150 of file gz_vtk_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), skip_gz_comment::open_wt_gzfile_a(), gz_udt_to_vtk_data_io::write_gz_ucd_mesh_to_vtk(), and zbuf_vtk.
Referenced by ucd_io_select::sel_write_grd_file().
write_gz_vtk_phys()
subroutine gz_vtk_file_io::write_gz_vtk_phys (integer, intent(in) id_rank, character(len=kchara), intent(in) gzip_name, type(ucd_data), intent(in) ucd)
Definition at line 129 of file gz_vtk_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), skip_gz_comment::open_wt_gzfile_a(), gz_udt_to_vtk_data_io::write_gz_ucd_field_to_vtk(), and zbuf_vtk.
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_file(), ucd_io_select::sel_write_ucd_file(), and ucd_io_select::sel_write_udt_file().
Variable Documentation
zbuf_vtk
type(buffer_4_gzip), private gz_vtk_file_io::zbuf_vtk private
Definition at line 45 of file gz_vtk_file_IO.f90.
Referenced by read_alloc_gz_vtk_file(), read_alloc_gz_vtk_grid(), read_alloc_gz_vtk_phys(), read_gz_vtk_file(), read_gz_vtk_grid(), read_gz_vtk_phys(), write_gz_parallel_vtk_file(), write_gz_vtk_file(), write_gz_vtk_grid(), and write_gz_vtk_phys().