CALYPSO: element_file_io_b Module Reference
element_file_io_b Module Reference
File IO for element communication table.
Functions/Subroutines
subroutine input_element_file_b (id_rank, file_name, ele_mesh_IO, ierr)
subroutine input_surface_file_b (id_rank, file_name, surf_mesh_IO, ierr)
subroutine input_edge_file_b (id_rank, file_name, edge_mesh_IO, ierr)
subroutine output_element_file_b (id_rank, file_name, ele_mesh_IO, ierr)
subroutine output_surface_file_b (id_rank, file_name, surf_mesh_IO, ierr)
subroutine output_edge_file_b (id_rank, file_name, edge_mesh_IO, ierr)
Variables
integer(kind=kint), parameter, private id_read_ele = 21
integer(kind=kint), parameter, private id_write_ele = 22
type(binary_io_buffer), private bbuf_emesh
Detailed Description
File IO for element communication table.
      subroutine input_element_file_b                                 &
     &         (id_rank, file_name, ele_mesh_IO, ierr)
        type(surf_edge_IO_file), intent(inout) :: ele_mesh_IO
      subroutine input_surface_file_b                                 &
     &         (id_rank, file_name, surf_mesh_IO, ierr)
        type(surf_edge_IO_file), intent(inout) :: surf_mesh_IO
      subroutine input_edge_file_b                                    &
     &         (id_rank, file_name, edge_mesh_IO, ierr)
        type(surf_edge_IO_file), intent(inout) :: edge_mesh_IO
      subroutine output_element_file_b                                &
     &         (id_rank, file_name, ele_mesh_IO, ierr)
      subroutine output_surface_file_b                                &
     &         (id_rank, file_name, surf_mesh_IO, ierr)
      subroutine output_edge_file_b                                   &
     &         (id_rank, file_name, edge_mesh_IO, ierr)
        type(surf_edge_IO_file), intent(in) :: edge_mesh_IO
Parameters
id_rank MPI rank
Function/Subroutine Documentation
input_edge_file_b()
subroutine element_file_io_b::input_edge_file_b (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(inout) edge_mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 117 of file element_file_IO_b.f90.
References bbuf_emesh, binary_io::close_binary_file(), m_machine_parameter::i_debug, id_read_ele, binary_io::open_read_binary_file(), and edge_data_io_b::read_edge_connection_b().
Referenced by element_mesh_io_select::sel_read_edge_mesh().
input_element_file_b()
subroutine element_file_io_b::input_element_file_b (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(inout) ele_mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 55 of file element_file_IO_b.f90.
References bbuf_emesh, binary_io::close_binary_file(), m_machine_parameter::i_debug, id_read_ele, binary_io::open_read_binary_file(), and element_data_io_b::read_element_comm_table_b().
Referenced by element_mesh_io_select::sel_read_ele_mesh().
input_surface_file_b()
subroutine element_file_io_b::input_surface_file_b (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(inout) surf_mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 86 of file element_file_IO_b.f90.
References bbuf_emesh, binary_io::close_binary_file(), m_machine_parameter::i_debug, id_read_ele, binary_io::open_read_binary_file(), and surface_data_io_b::read_surface_connection_b().
Referenced by element_mesh_io_select::sel_read_surf_mesh().
output_edge_file_b()
subroutine element_file_io_b::output_edge_file_b (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(in) edge_mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 210 of file element_file_IO_b.f90.
References bbuf_emesh, binary_io::close_binary_file(), m_machine_parameter::i_debug, id_write_ele, binary_io::open_write_binary_file(), and edge_data_io_b::write_edge_connection_b().
Referenced by element_mesh_io_select::sel_write_edge_mesh_file().
output_element_file_b()
subroutine element_file_io_b::output_element_file_b (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(in) ele_mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 149 of file element_file_IO_b.f90.
References bbuf_emesh, binary_io::close_binary_file(), m_machine_parameter::i_debug, id_write_ele, binary_io::open_write_binary_file(), and element_data_io_b::write_element_comm_table_b().
Referenced by element_mesh_io_select::sel_write_ele_mesh_file().
output_surface_file_b()
subroutine element_file_io_b::output_surface_file_b (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(in) surf_mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 180 of file element_file_IO_b.f90.
References bbuf_emesh, binary_io::close_binary_file(), m_machine_parameter::i_debug, id_write_ele, binary_io::open_write_binary_file(), and surface_data_io_b::write_surface_connection_b().
Referenced by element_mesh_io_select::sel_write_surf_mesh_file().
Variable Documentation
bbuf_emesh
type(binary_io_buffer), private element_file_io_b::bbuf_emesh private
Definition at line 46 of file element_file_IO_b.f90.
Referenced by input_edge_file_b(), input_element_file_b(), input_surface_file_b(), output_edge_file_b(), output_element_file_b(), and output_surface_file_b().
id_read_ele
integer(kind = kint), parameter, private element_file_io_b::id_read_ele = 21 private
Definition at line 44 of file element_file_IO_b.f90.
Referenced by input_edge_file_b(), input_element_file_b(), and input_surface_file_b().
id_write_ele
integer(kind = kint), parameter, private element_file_io_b::id_write_ele = 22 private
Definition at line 45 of file element_file_IO_b.f90.
Referenced by output_edge_file_b(), output_element_file_b(), and output_surface_file_b().