CALYPSO: t_cal_max_indices Module Reference
t_cal_max_indices Module Reference
Find node positions of maximum values.
Data Types
type maximum_informations
Functions/Subroutines
subroutine alloc_phys_range (ncomp_viz, range)
subroutine dealloc_phys_range (range)
subroutine output_range_data (istep_ucd, time, node, nod_fld, range)
subroutine, private cal_max_indices (node, nod_fld, range)
subroutine, private open_maximum_file (nod_fld)
Variables
integer(kind=kint), parameter, private maximum_data_code = 44
integer(kind=kint), parameter, private maximum_position_code = 45
character(len=kchara), parameter, private minmax_data_file_name = 'maximum_data.dat'
character(len=kchara), parameter, private minmax_posi_file_name = 'maximum_posi.dat'
Detailed Description
Find node positions of maximum values.
      subroutine alloc_phys_range(ncomp_viz, range)
      subroutine dealloc_phys_range(range)
      subroutine cal_max_indices(node, nod_fld)
        type(node_data), intent(in) :: node
        type(phys_data), intent(in) :: nod_fld
Function/Subroutine Documentation
alloc_phys_range()
subroutine t_cal_max_indices::alloc_phys_range (integer(kind = kint), intent(in) ncomp_viz, type(maximum_informations), intent(inout) range)
Definition at line 67 of file t_cal_max_indices.f90.
Referenced by fem_analyzer_sph_mhd::fem_initialize_sph_mhd().
cal_max_indices()
subroutine, private t_cal_max_indices::cal_max_indices (type(node_data), intent(in) node, type(phys_data), intent(in) nod_fld, type(maximum_informations), intent(inout) range) private
Definition at line 151 of file t_cal_max_indices.f90.
References calypso_mpi_int8::calypso_mpi_allreduce_int8(), and calypso_mpi_real::calypso_mpi_allreduce_real().
Referenced by output_range_data().
dealloc_phys_range()
subroutine t_cal_max_indices::dealloc_phys_range (type(maximum_informations), intent(inout) range)
Definition at line 96 of file t_cal_max_indices.f90.
Referenced by fem_analyzer_sph_mhd::fem_finalize().
open_maximum_file()
subroutine, private t_cal_max_indices::open_maximum_file (type(phys_data), intent(in) nod_fld) private
Definition at line 196 of file t_cal_max_indices.f90.
References maximum_data_code, maximum_position_code, minmax_data_file_name, minmax_posi_file_name, and write_field_labels::write_multi_labels().
Referenced by output_range_data().
output_range_data()
subroutine t_cal_max_indices::output_range_data (integer(kind = kint), intent(in) istep_ucd, real(kind = kreal), intent(in) time, type(node_data), intent(in) node, type(phys_data), intent(in) nod_fld, type(maximum_informations), intent(inout) range)
Definition at line 112 of file t_cal_max_indices.f90.
References cal_max_indices(), maximum_data_code, maximum_position_code, calypso_mpi::my_rank, and open_maximum_file().
Variable Documentation
maximum_data_code
integer(kind=kint), parameter, private t_cal_max_indices::maximum_data_code = 44 private
Definition at line 49 of file t_cal_max_indices.f90.
Referenced by open_maximum_file(), and output_range_data().
maximum_position_code
integer(kind=kint), parameter, private t_cal_max_indices::maximum_position_code = 45 private
Definition at line 50 of file t_cal_max_indices.f90.
Referenced by open_maximum_file(), and output_range_data().
minmax_data_file_name
character(len=kchara), parameter, private t_cal_max_indices::minmax_data_file_name = 'maximum_data.dat' private
Definition at line 52 of file t_cal_max_indices.f90.
Referenced by open_maximum_file().
minmax_posi_file_name
character(len=kchara), parameter, private t_cal_max_indices::minmax_posi_file_name = 'maximum_posi.dat' private
Definition at line 54 of file t_cal_max_indices.f90.
Referenced by open_maximum_file().