CALYPSO: ucd_field_file_io Module Reference
ucd_field_file_io Module Reference
ascii format data IO
Functions/Subroutines
subroutine write_ucd_2_fld_file (id_rank, file_name, t_IO, ucd)
subroutine read_ucd_2_fld_file (id_rank, file_name, t_IO, ucd)
subroutine read_alloc_ucd_2_fld_file (id_rank, file_name, t_IO, ucd)
Variables
integer(kind=kint), parameter, private id_fld_file = 16
file ID for field file IO
Detailed Description
ascii format data IO
      subroutine write_ucd_2_fld_file(id_rank, file_name, t_IO, ucd)
        type(time_data), intent(in) :: t_IO
        type(ucd_data), intent(in) :: ucd
      subroutine read_ucd_2_fld_file(id_rank, file_name, t_IO, ucd)
      subroutine read_alloc_ucd_2_fld_file                            &
     &         (id_rank, file_name, t_IO, ucd)
        type(time_data), intent(inout) :: t_IO
        type(ucd_data), intent(inout) :: ucd
Parameters
id_rank process ID
file_name File name
t_IO Structure for time information
ucd Structure for FEM field data IO
Function/Subroutine Documentation
read_alloc_ucd_2_fld_file()
subroutine ucd_field_file_io::read_alloc_ucd_2_fld_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(time_data), intent(inout) t_IO, type(ucd_data), intent(inout) ucd)
Definition at line 107 of file ucd_field_file_IO.f90.
References t_ucd_data::allocate_ucd_phys_data(), t_ucd_data::allocate_ucd_phys_name(), t_ucd_data::cal_istack_ucd_component(), m_machine_parameter::i_debug, id_fld_file, field_data_io::read_field_data(), time_data_io::read_step_data(), and skip_comment_f::skip_comment().
Referenced by ucd_io_select::sel_read_alloc_udt_file(), and ucd_io_select::sel_read_udt_param().
read_ucd_2_fld_file()
subroutine ucd_field_file_io::read_ucd_2_fld_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(time_data), intent(inout) t_IO, type(ucd_data), intent(inout) ucd)
Definition at line 75 of file ucd_field_file_IO.f90.
References m_machine_parameter::i_debug, id_fld_file, field_data_io::read_field_data(), time_data_io::read_step_data(), and skip_comment_f::skip_comment().
Referenced by ucd_io_select::sel_read_udt_file().
write_ucd_2_fld_file()
subroutine ucd_field_file_io::write_ucd_2_fld_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(time_data), intent(in) t_IO, type(ucd_data), intent(in) ucd)
Definition at line 51 of file ucd_field_file_IO.f90.
References m_machine_parameter::i_debug, id_fld_file, field_data_io::write_field_data(), and time_data_io::write_step_data().
Referenced by ucd_io_select::sel_write_ucd_file(), and ucd_io_select::sel_write_udt_file().
Variable Documentation
id_fld_file
integer(kind = kint), parameter, private ucd_field_file_io::id_fld_file = 16 private
file ID for field file IO
Definition at line 43 of file ucd_field_file_IO.f90.
Referenced by read_alloc_ucd_2_fld_file(), read_ucd_2_fld_file(), and write_ucd_2_fld_file().