CALYPSO: set_vr_rtm_leg_matmul_big Module Reference
set_vr_rtm_leg_matmul_big Module Reference
forward Legendre transform using matrix multi
Functions/Subroutines
subroutine set_vr_rtm_vec_sym_matmul_big (nnod_rtm, nidx_rtm, istep_rtm, nidx_rlm, asin_theta_1d_rtm, weight_rtm, kst, nkr, mp_rlm, mn_rlm, nle_rtm, nlo_rtm, ncomp, nvector, irev_sr_rtm, n_WR, WR, symp_r, asmp_p, asmp_r, symp_p)
subroutine set_vr_rtm_scl_sym_matmul_big (nnod_rtm, nidx_rtm, istep_rtm, nidx_rlm, weight_rtm, kst, nkr, mp_rlm, nle_rtm, nlo_rtm, ncomp, nvector, nscalar, irev_sr_rtm, n_WR, WR, symp, asmp)
subroutine cal_vr_rtm_vec_sym_matmul_big (nnod_rtm, nidx_rtm, istep_rtm, nidx_rlm, asin_theta_1d_rtm, kst, nkr, mp_rlm, mn_rlm, nl_rtm, symp_r, asmp_p, asmp_r, symp_p, ncomp, nvector, irev_sr_rtm, n_WS, WS)
subroutine cal_vr_rtm_scl_sym_matmul_big (nnod_rtm, nidx_rtm, istep_rtm, nidx_rlm, kst, nkr, mp_rlm, nl_rtm, symp, asmp, ncomp, nvector, nscalar, irev_sr_rtm, n_WS, WS)
Detailed Description
forward Legendre transform using matrix multi
      subroutine set_vr_rtm_vec_sym_matmul_big(nnod_rtm, nidx_rtm,    &
     &         istep_rtm, nidx_rlm, asin_theta_1d_rtm, weight_rtm,    &
     &         kst, nkr, mp_rlm, mn_rlm, nle_rtm, nlo_rtm,            &
     &         ncomp, nvector, irev_sr_rtm, n_WR, WR,                 &
     &         symp_r, asmp_p, asmp_r, symp_p)
      subroutine set_vr_rtm_scl_sym_matmul_big                        &
     &         (nnod_rtm, nidx_rtm, istep_rtm, nidx_rlm, weight_rtm,  &
     &          kst, nkr, mp_rlm,  nle_rtm, nlo_rtm,                  &
     &          ncomp, nvector, nscalar, irev_sr_rtm,                 &
     &          n_WR, WR, symp, asmp)
      subroutine cal_vr_rtm_vec_sym_matmul_big(nnod_rtm, nidx_rtm,    &
     &          istep_rtm, nidx_rlm, asin_theta_1d_rtm,               &
     &          kst, nkr, mp_rlm, mn_rlm, nl_rtm, symp_r, asmp_p,     &
     &          asmp_r, symp_p, ncomp, nvector, irev_sr_rtm, n_WS, WS)
      subroutine cal_vr_rtm_scl_sym_matmul_big                        &
     &         (nnod_rtm, nidx_rtm, istep_rtm, nidx_rlm, kst, nkr,    &
     &          mp_rlm, nl_rtm, symp, asmp, ncomp, nvector, nscalar,  &
     &          irev_sr_rtm, n_WS, WS)
Function/Subroutine Documentation
cal_vr_rtm_scl_sym_matmul_big()
subroutine set_vr_rtm_leg_matmul_big::cal_vr_rtm_scl_sym_matmul_big (integer(kind = kint), intent(in) nnod_rtm, integer(kind = kint), dimension(3), intent(in) nidx_rtm, integer(kind = kint), dimension(3), intent(in) istep_rtm, integer(kind = kint), dimension(2), intent(in) nidx_rlm, integer(kind = kint), intent(in) kst, integer(kind = kint), intent(in) nkr, integer(kind = kint), intent(in) mp_rlm, integer(kind = kint), intent(in) nl_rtm, real(kind = kreal), dimension(nl_rtm,ncomp*nkr), intent(in) symp, real(kind = kreal), dimension(nl_rtm,ncomp*nkr), intent(in) asmp, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, integer(kind = kint), dimension(nnod_rtm), intent(in) irev_sr_rtm, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 365 of file set_vr_rtm_leg_matmul_big.f90.
Referenced by leg_b_trans_sym_matmul_big::leg_bwd_trans_sym_matmul_big().
cal_vr_rtm_vec_sym_matmul_big()
subroutine set_vr_rtm_leg_matmul_big::cal_vr_rtm_vec_sym_matmul_big (integer(kind = kint), intent(in) nnod_rtm, integer(kind = kint), dimension(3), intent(in) nidx_rtm, integer(kind = kint), dimension(3), intent(in) istep_rtm, integer(kind = kint), dimension(2), intent(in) nidx_rlm, real(kind = kreal), dimension(nidx_rtm(2)), intent(in) asin_theta_1d_rtm, integer(kind = kint), intent(in) kst, integer(kind = kint), intent(in) nkr, integer(kind = kint), intent(in) mp_rlm, integer(kind = kint), intent(in) mn_rlm, integer(kind = kint), intent(in) nl_rtm, real(kind = kreal), dimension(nl_rtm,ncomp*nkr), intent(inout) symp_r, real(kind = kreal), dimension(nl_rtm,2*nvector*nkr), intent(in) asmp_p, real(kind = kreal), dimension(nl_rtm,ncomp*nkr), intent(inout) asmp_r, real(kind = kreal), dimension(nl_rtm,2*nvector*nkr), intent(in) symp_p, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), dimension(nnod_rtm), intent(in) irev_sr_rtm, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS)
Definition at line 245 of file set_vr_rtm_leg_matmul_big.f90.
Referenced by leg_b_trans_sym_matmul_big::leg_bwd_trans_sym_matmul_big().
set_vr_rtm_scl_sym_matmul_big()
subroutine set_vr_rtm_leg_matmul_big::set_vr_rtm_scl_sym_matmul_big (integer(kind = kint), intent(in) nnod_rtm, integer(kind = kint), dimension(3), intent(in) nidx_rtm, integer(kind = kint), dimension(3), intent(in) istep_rtm, integer(kind = kint), dimension(2), intent(in) nidx_rlm, real(kind = kreal), dimension(nidx_rtm(2)), intent(in) weight_rtm, integer(kind = kint), intent(in) kst, integer(kind = kint), intent(in) nkr, integer(kind = kint), intent(in) mp_rlm, integer(kind = kint), intent(in) nle_rtm, integer(kind = kint), intent(in) nlo_rtm, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, integer(kind = kint), dimension(nnod_rtm), intent(in) irev_sr_rtm, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(in) WR, real(kind = kreal), dimension(ncomp*nkr,nle_rtm), intent(inout) symp, real(kind = kreal), dimension(ncomp*nkr,nle_rtm), intent(inout) asmp)
Definition at line 167 of file set_vr_rtm_leg_matmul_big.f90.
Referenced by leg_f_trans_sym_matmul_big::leg_fwd_trans_sym_matmul_big().
set_vr_rtm_vec_sym_matmul_big()
subroutine set_vr_rtm_leg_matmul_big::set_vr_rtm_vec_sym_matmul_big (integer(kind = kint), intent(in) nnod_rtm, integer(kind = kint), dimension(3), intent(in) nidx_rtm, integer(kind = kint), dimension(3), intent(in) istep_rtm, integer(kind = kint), dimension(2), intent(in) nidx_rlm, real(kind = kreal), dimension(nidx_rtm(2)), intent(in) asin_theta_1d_rtm, real(kind = kreal), dimension(nidx_rtm(2)), intent(in) weight_rtm, integer(kind = kint), intent(in) kst, integer(kind = kint), intent(in) nkr, integer(kind = kint), intent(in) mp_rlm, integer(kind = kint), intent(in) mn_rlm, integer(kind = kint), intent(in) nle_rtm, integer(kind = kint), intent(in) nlo_rtm, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), dimension(nnod_rtm), intent(in) irev_sr_rtm, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(in) WR, real(kind=kreal), dimension(ncomp*nkr,nle_rtm), intent(inout) symp_r, real(kind=kreal), dimension(2*nkr*nvector,nle_rtm), intent(inout) asmp_p, real(kind=kreal), dimension(ncomp*nkr,nle_rtm), intent(inout) asmp_r, real(kind=kreal), dimension(2*nkr*nvector,nle_rtm), intent(inout) symp_p)
Definition at line 44 of file set_vr_rtm_leg_matmul_big.f90.
Referenced by leg_f_trans_sym_matmul_big::leg_fwd_trans_sym_matmul_big().