CALYPSO: set_control_4_sph_to_fem Module Reference
set_control_4_sph_to_fem Module Reference
Load mesh and filtering data for MHD simulation.
Functions/Subroutines
subroutine sph_boundary_io_control (MHD_prop, MHD_BC, bc_IO)
Detailed Description
Load mesh and filtering data for MHD simulation.
      subroutine sph_boundary_IO_control(MHD_prop, MHD_BC, bc_IO)
        type(MHD_evolution_param), intent(in) :: MHD_prop
        type(MHD_BC_lists), intent(in) :: MHD_BC
        type(boundary_spectra), intent(inout) :: bc_IO
Function/Subroutine Documentation
sph_boundary_io_control()
subroutine set_control_4_sph_to_fem::sph_boundary_io_control (type(mhd_evolution_param), intent(in) MHD_prop, type(mhd_bc_lists), intent(in) MHD_BC, type(boundary_spectra), intent(inout) bc_IO)
Definition at line 38 of file set_control_4_SPH_to_FEM.f90.
References t_sph_boundary_input_data::bcast_boundary_spectr_file(), calypso_mpi::calypso_mpi_barrier(), check_read_bc_file::check_read_boundary_files(), check_read_bc_file::id_no_boundary_file, m_machine_parameter::iflag_debug, calypso_mpi::my_rank, and t_sph_boundary_input_data::read_boundary_spectr_file().
Referenced by input_control_sph_mhd::input_control_4_sph_make_init(), input_control_sph_mhd::input_control_4_sph_mhd_nosnap(), and input_control_sph_mhd::input_control_sph_mhd_psf().