CALYPSO: gz_node_geometry_io_b Module Reference
gz_node_geometry_io_b Module Reference
Node data IO using zlib.
Functions/Subroutines
subroutine gz_write_geometry_info_b (nod_IO, zbuf)
subroutine gz_write_scalar_in_element_b (nod_IO, sfed_IO, zbuf)
subroutine gz_write_vector_in_element_b (nod_IO, sfed_IO, zbuf)
subroutine gz_read_number_of_node_b (zbuf, nod_IO)
subroutine gz_read_geometry_info_b (zbuf, nod_IO)
subroutine gz_read_scalar_in_element_b (zbuf, nod_IO, sfed_IO)
subroutine gz_read_vector_in_element_b (zbuf, nod_IO, sfed_IO)
Detailed Description
Node data IO using zlib.
      subroutine gz_write_geometry_info_b(nod_IO, zbuf)
      subroutine gz_write_scalar_in_element_b(nod_IO, sfed_IO, zbuf)
      subroutine gz_write_vector_in_element_b(nod_IO, sfed_IO, zbuf)
        type(node_data), intent(in) :: nod_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
        type(buffer_4_gzip), intent(inout) :: zbuf
      subroutine gz_read_number_of_node_b(zbuf, nod_IO)
      subroutine gz_read_geometry_info_b(zbuf, nod_IO)
      subroutine gz_read_scalar_in_element_b(zbuf, nod_IO, sfed_IO)
      subroutine gz_read_vector_in_element_b                          &
     &         (zbuf, nod_IO, sfed_IO)
        type(buffer_4_gzip), intent(inout) :: zbuf
        type(node_data), intent(inout) :: nod_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
Function/Subroutine Documentation
gz_read_geometry_info_b()
subroutine gz_node_geometry_io_b::gz_read_geometry_info_b (type(buffer_4_gzip), intent(inout) zbuf, type(node_data), intent(inout) nod_IO)
Definition at line 133 of file gz_node_geometry_IO_b.f90.
References t_geometry_data::alloc_node_geometry_base(), transfer_to_long_integers::cast_long(), gz_binary_io::gz_read_2d_vector_b(), and gz_binary_io::gz_read_mul_int8_b().
Referenced by gz_edge_data_io_b::gz_read_edge_geometry_b(), gz_element_data_io_b::gz_read_element_geometry_b(), gz_mesh_data_io_b::gz_read_num_node_ele_b(), and gz_surface_data_io_b::gz_read_surface_geometry_b().
gz_read_number_of_node_b()
subroutine gz_node_geometry_io_b::gz_read_number_of_node_b (type(buffer_4_gzip), intent(inout) zbuf, type(node_data), intent(inout) nod_IO)
Definition at line 115 of file gz_node_geometry_IO_b.f90.
References gz_binary_io::gz_read_one_integer_b().
Referenced by gz_edge_data_io_b::gz_read_edge_geometry_b(), gz_element_data_io_b::gz_read_element_geometry_b(), gz_mesh_data_io_b::gz_read_num_node_b(), gz_read_scalar_in_element_b(), gz_surface_data_io_b::gz_read_surface_geometry_b(), and gz_read_vector_in_element_b().
gz_read_scalar_in_element_b()
subroutine gz_node_geometry_io_b::gz_read_scalar_in_element_b (type(buffer_4_gzip), intent(inout) zbuf, type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 155 of file gz_node_geometry_IO_b.f90.
References t_surf_edge_io::alloc_ele_scalar_io(), transfer_to_long_integers::cast_long(), gz_binary_io::gz_read_1d_vector_b(), and gz_read_number_of_node_b().
Referenced by gz_edge_data_io_b::gz_read_edge_geometry_b(), gz_element_data_io_b::gz_read_element_geometry_b(), and gz_surface_data_io_b::gz_read_surface_geometry_b().
gz_read_vector_in_element_b()
subroutine gz_node_geometry_io_b::gz_read_vector_in_element_b (type(buffer_4_gzip), intent(inout) zbuf, type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 177 of file gz_node_geometry_IO_b.f90.
References t_surf_edge_io::alloc_ele_vector_io(), transfer_to_long_integers::cast_long(), gz_binary_io::gz_read_2d_vector_b(), gz_read_number_of_node_b(), and m_phys_constants::n_vector.
Referenced by gz_edge_data_io_b::gz_read_edge_geometry_b(), and gz_surface_data_io_b::gz_read_surface_geometry_b().
gz_write_geometry_info_b()
subroutine gz_node_geometry_io_b::gz_write_geometry_info_b (type(node_data), intent(in) nod_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 46 of file gz_node_geometry_IO_b.f90.
References transfer_to_long_integers::cast_long(), gz_binary_io::gz_write_2d_vector_b(), gz_binary_io::gz_write_mul_int8_b(), and gz_binary_io::gz_write_one_integer_b().
Referenced by gz_edge_data_io_b::gz_write_edge_geometry_b(), gz_element_data_io_b::gz_write_element_geometry_b(), gz_mesh_data_io_b::gz_write_geometry_data_b(), and gz_surface_data_io_b::gz_write_surface_geometry_b().
gz_write_scalar_in_element_b()
subroutine gz_node_geometry_io_b::gz_write_scalar_in_element_b (type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 70 of file gz_node_geometry_IO_b.f90.
References transfer_to_long_integers::cast_long(), gz_binary_io::gz_write_1d_vector_b(), and gz_binary_io::gz_write_one_integer_b().
Referenced by gz_edge_data_io_b::gz_write_edge_geometry_b(), gz_element_data_io_b::gz_write_element_geometry_b(), and gz_surface_data_io_b::gz_write_surface_geometry_b().
gz_write_vector_in_element_b()
subroutine gz_node_geometry_io_b::gz_write_vector_in_element_b (type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 92 of file gz_node_geometry_IO_b.f90.
References transfer_to_long_integers::cast_long(), gz_binary_io::gz_write_2d_vector_b(), gz_binary_io::gz_write_one_integer_b(), and m_phys_constants::n_vector.
Referenced by gz_edge_data_io_b::gz_write_edge_geometry_b(), and gz_surface_data_io_b::gz_write_surface_geometry_b().