CALYPSO: compare_mesh_structures Module Reference
compare_mesh_structures Module Reference
Compare FEM mesh structures.
Functions/Subroutines
subroutine compare_mesh_type (id_rank, nod_comm, node, ele, mesh)
subroutine compare_node_types (id_rank, org_node, new_node)
subroutine compare_element_types (id_rank, org_ele, new_ele)
subroutine compare_node_comm_types (id_rank, org_comm, new_comm)
Detailed Description
Compare FEM mesh structures.
      subroutine compare_mesh_type(id_rank, nod_comm, node, ele, mesh)
        type(mesh_geometry),    intent(inout) :: mesh
        type(communication_table), intent(inout) :: nod_comm
        type(node_data), intent(inout) ::           node
        type(element_data), intent(inout) ::        ele
      subroutine compare_node_types(id_rank, org_node, new_node)
        type(node_data), intent(in) :: org_node
        type(node_data), intent(in) :: new_node
      subroutine compare_element_types(id_rank, org_ele, new_ele)
        type(element_data), intent(in) :: org_ele
        type(element_data), intent(in) :: new_ele
      subroutine compare_node_comm_types(id_rank, org_comm, new_comm)
        type(communication_table), intent(in) :: org_comm
        type(communication_table), intent(in) :: new_comm
Function/Subroutine Documentation
compare_element_types()
subroutine compare_mesh_structures::compare_element_types (integer, intent(in) id_rank, type(element_data), intent(in) org_ele, type(element_data), intent(in) new_ele)
Definition at line 93 of file compare_mesh_structures.f90.
Referenced by compare_mesh_type().
compare_mesh_type()
subroutine compare_mesh_structures::compare_mesh_type (integer, intent(in) id_rank, type(communication_table), intent(inout) nod_comm, type(node_data), intent(inout) node, type(element_data), intent(inout) ele, type(mesh_geometry), intent(inout) mesh)
Definition at line 39 of file compare_mesh_structures.f90.
References compare_element_types(), compare_node_comm_types(), and compare_node_types().
compare_node_comm_types()
subroutine compare_mesh_structures::compare_node_comm_types (integer, intent(in) id_rank, type(communication_table), intent(in) org_comm, type(communication_table), intent(in) new_comm)
Definition at line 140 of file compare_mesh_structures.f90.
Referenced by compare_mesh_type().
compare_node_types()
subroutine compare_mesh_structures::compare_node_types (integer, intent(in) id_rank, type(node_data), intent(in) org_node, type(node_data), intent(in) new_node)
Definition at line 61 of file compare_mesh_structures.f90.
Referenced by compare_mesh_type().