CALYPSO: cal_subtract_smp Module Reference
cal_subtract_smp Module Reference
Functions/Subroutines
subroutine subtract_scalars_smp (nnod, source, subt, sol)
subroutine subtract_vectors_smp (nnod, source, subt, sol)
subroutine subtract_tensors_smp (nnod, source, subt, sol)
subroutine subtruct_const_4_scalar_smp (nnod, dest, scalar, const)
subroutine subtruct_const_4_vect_smp (nnod, dest, vector, const)
subroutine subtruct_const_4_tensor_smp (nnod, dest, tensor, const)
subroutine subtruct_const_4_scalar_smp_ow (nnod, scalar, const)
subroutine subtruct_const_4_vect_smp_ow (nnod, vector, const)
subroutine subtruct_const_4_tensor_smp_ow (nnod, tensor, const)
subroutine subt_const_to_vector_smp_ow (nnod, vector, const)
subroutine subt_const_to_tensor_smp_ow (nnod, tensor, const)
Function/Subroutine Documentation
subt_const_to_tensor_smp_ow()
subroutine cal_subtract_smp::subt_const_to_tensor_smp_ow (integer (kind=kint), intent(in) nnod, real (kind=kreal), dimension(nnod,6), intent(inout) tensor, real (kind=kreal), dimension(6), intent(in) const)
Definition at line 235 of file cal_subtract_smp.f90.
subt_const_to_vector_smp_ow()
subroutine cal_subtract_smp::subt_const_to_vector_smp_ow (integer (kind=kint), intent(in) nnod, real (kind=kreal), dimension(nnod,3), intent(inout) vector, real (kind=kreal), dimension(3), intent(in) const)
Definition at line 218 of file cal_subtract_smp.f90.
subtract_scalars_smp()
subroutine cal_subtract_smp::subtract_scalars_smp (integer (kind=kint), intent(in) nnod, real (kind=kreal), dimension(nnod), intent(in) source, real (kind=kreal), dimension(nnod), intent(in) subt, real (kind=kreal), dimension(nnod), intent(inout) sol)
Definition at line 48 of file cal_subtract_smp.f90.
Referenced by copy_nodal_fields::subtract_2_nod_scalars().
subtract_tensors_smp()
subroutine cal_subtract_smp::subtract_tensors_smp (integer (kind=kint), intent(in) nnod, real (kind=kreal), dimension(nnod,6), intent(in) source, real (kind=kreal), dimension(nnod,6), intent(in) subt, real (kind=kreal), dimension(nnod,6), intent(inout) sol)
Definition at line 80 of file cal_subtract_smp.f90.
Referenced by copy_nodal_fields::subtract_2_nod_tensors().
subtract_vectors_smp()
subroutine cal_subtract_smp::subtract_vectors_smp (integer (kind=kint), intent(in) nnod, real (kind=kreal), dimension(nnod,3), intent(in) source, real (kind=kreal), dimension(nnod,3), intent(in) subt, real (kind=kreal), dimension(nnod,3), intent(inout) sol)
Definition at line 63 of file cal_subtract_smp.f90.
Referenced by copy_nodal_fields::subtract_2_nod_vectors().
subtruct_const_4_scalar_smp()
subroutine cal_subtract_smp::subtruct_const_4_scalar_smp (integer (kind = kint), intent(in) nnod, real(kind=kreal), dimension(nnod), intent(inout) dest, real(kind=kreal), dimension(nnod), intent(in) scalar, real(kind=kreal), intent(in) const)
Definition at line 101 of file cal_subtract_smp.f90.
subtruct_const_4_scalar_smp_ow()
subroutine cal_subtract_smp::subtruct_const_4_scalar_smp_ow (integer (kind=kint), intent(in) nnod, real(kind=kreal), dimension(nnod), intent(inout) scalar, real(kind=kreal), intent(in) const)
Definition at line 162 of file cal_subtract_smp.f90.
Referenced by set_const_4_sections::set_constant_4_iso().
subtruct_const_4_tensor_smp()
subroutine cal_subtract_smp::subtruct_const_4_tensor_smp (integer (kind = kint), intent(in) nnod, real(kind=kreal), dimension(nnod,6), intent(inout) dest, real(kind=kreal), dimension(nnod,6), intent(in) tensor, real(kind=kreal), intent(in) const)
Definition at line 138 of file cal_subtract_smp.f90.
subtruct_const_4_tensor_smp_ow()
subroutine cal_subtract_smp::subtruct_const_4_tensor_smp_ow (integer (kind=kint), intent(in) nnod, real(kind=kreal), dimension(nnod,6), intent(inout) tensor, real(kind=kreal), intent(in) const)
Definition at line 196 of file cal_subtract_smp.f90.
subtruct_const_4_vect_smp()
subroutine cal_subtract_smp::subtruct_const_4_vect_smp (integer (kind = kint), intent(in) nnod, real(kind=kreal), dimension(nnod,3), intent(inout) dest, real(kind=kreal), dimension(nnod,3), intent(in) vector, real(kind=kreal), intent(in) const)
Definition at line 119 of file cal_subtract_smp.f90.
subtruct_const_4_vect_smp_ow()
subroutine cal_subtract_smp::subtruct_const_4_vect_smp_ow (integer (kind=kint), intent(in) nnod, real(kind=kreal), dimension(nnod,3), intent(inout) vector, real(kind=kreal), intent(in) const)
Definition at line 178 of file cal_subtract_smp.f90.