CALYPSO: t_global_gauss_coefs Module Reference
t_global_gauss_coefs Module Reference
Gauss coefficients data for output.
Data Types
type global_gauss_points
Functions/Subroutines
subroutine alloc_gauss_global_coefs (d_gauss)
subroutine dealloc_gauss_global_coefs (d_gauss)
subroutine read_gauss_global_coefs (d_gauss)
subroutine write_gauss_global_coefs (d_gauss)
Variables
integer(kind=kint), parameter, private id_gauss = 12
Detailed Description
Gauss coefficients data for output.
      subroutine alloc_gauss_global_coefs(d_gauss)
      subroutine dealloc_gauss_global_coefs(d_gauss)
      subroutine read_gauss_global_coefs(d_gauss)
      subroutine write_gauss_global_coefs(d_gauss)
Function/Subroutine Documentation
alloc_gauss_global_coefs()
subroutine t_global_gauss_coefs::alloc_gauss_global_coefs (type(global_gauss_points), intent(inout) d_gauss)
Definition at line 45 of file t_global_gauss_coefs.f90.
Referenced by read_gauss_global_coefs().
dealloc_gauss_global_coefs()
subroutine t_global_gauss_coefs::dealloc_gauss_global_coefs (type(global_gauss_points), intent(inout) d_gauss)
Definition at line 71 of file t_global_gauss_coefs.f90.
read_gauss_global_coefs()
subroutine t_global_gauss_coefs::read_gauss_global_coefs (type(global_gauss_points), intent(inout) d_gauss)
Definition at line 83 of file t_global_gauss_coefs.f90.
References alloc_gauss_global_coefs(), id_gauss, and skip_comment_f::skip_comment().
write_gauss_global_coefs()
subroutine t_global_gauss_coefs::write_gauss_global_coefs (type(global_gauss_points), intent(in) d_gauss)
Definition at line 124 of file t_global_gauss_coefs.f90.
References id_gauss.
Variable Documentation
id_gauss
integer(kind = kint), parameter, private t_global_gauss_coefs::id_gauss = 12 private
Definition at line 24 of file t_global_gauss_coefs.f90.
Referenced by read_gauss_global_coefs(), and write_gauss_global_coefs().