CALYPSO: t_control_array_intreal Module Reference
t_control_array_intreal Module Reference
Data Types
type ctl_array_ir
Structure for real and integer control array.
type read_int_real_item
structure of control item with three characters
Functions/Subroutines
subroutine read_intreal_ctl_type (c_buf, label, ir_item)
subroutine write_intreal_ctl_type (id_file, level, label, ir_item)
subroutine copy_intreal_ctl (org_ir, new_ir)
subroutine alloc_control_array_i_r (array_ir)
subroutine dealloc_control_array_i_r (array_ir)
subroutine read_control_array_i_r (id_control, label, array_ir, c_buf)
subroutine write_control_array_i_r (id_control, level, label, array_ir)
subroutine append_control_array_i_r (read_ir, array_ir)
subroutine copy_control_array_i_r (num_copy, org_ir, tgt_ir)
subroutine append_control_item_i_r (read_ir, array_ir)
Function/Subroutine Documentation
alloc_control_array_i_r()
subroutine t_control_array_intreal::alloc_control_array_i_r (type(ctl_array_ir), intent(inout) array_ir)
Definition at line 136 of file t_control_array_intreal.f90.
Referenced by append_control_array_i_r(), bcast_control_arrays::bcast_ctl_array_ir(), and read_control_array_i_r().
append_control_array_i_r()
subroutine t_control_array_intreal::append_control_array_i_r (type(read_int_real_item), intent(inout) read_ir, type(ctl_array_ir), intent(inout) array_ir)
Definition at line 229 of file t_control_array_intreal.f90.
References alloc_control_array_i_r(), append_control_item_i_r(), copy_control_array_i_r(), and dealloc_control_array_i_r().
Referenced by read_control_array_i_r().
append_control_item_i_r()
subroutine t_control_array_intreal::append_control_item_i_r (type(read_int_real_item), intent(in) read_ir, type(ctl_array_ir), intent(inout) array_ir)
Definition at line 270 of file t_control_array_intreal.f90.
Referenced by append_control_array_i_r().
copy_control_array_i_r()
subroutine t_control_array_intreal::copy_control_array_i_r (integer(kind = kint), intent(in) num_copy, type(ctl_array_ir), intent(in) org_ir, type(ctl_array_ir), intent(inout) tgt_ir)
Definition at line 254 of file t_control_array_intreal.f90.
Referenced by append_control_array_i_r().
copy_intreal_ctl()
subroutine t_control_array_intreal::copy_intreal_ctl (type(read_int_real_item), intent(in) org_ir, type(read_int_real_item), intent(inout) new_ir)
Definition at line 121 of file t_control_array_intreal.f90.
dealloc_control_array_i_r()
subroutine t_control_array_intreal::dealloc_control_array_i_r (type(ctl_array_ir), intent(inout) array_ir)
Definition at line 152 of file t_control_array_intreal.f90.
Referenced by append_control_array_i_r(), and t_ctl_data_4_sphere_model::dealloc_control_shell_define().
read_control_array_i_r()
subroutine t_control_array_intreal::read_control_array_i_r (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) label, type(ctl_array_ir), intent(inout) array_ir, type(buffer_for_control), intent(inout) c_buf)
Definition at line 166 of file t_control_array_intreal.f90.
References alloc_control_array_i_r(), append_control_array_i_r(), t_read_control_elements::check_array_flag(), t_read_control_elements::check_end_array_flag(), t_read_control_elements::load_one_line_from_control(), and read_intreal_ctl_type().
Referenced by t_ctl_data_4_sphere_model::read_control_shell_define().
read_intreal_ctl_type()
subroutine t_control_array_intreal::read_intreal_ctl_type (type(buffer_for_control), intent(in) c_buf, character(len=kchara), intent(in) label, type(read_int_real_item), intent(inout) ir_item)
Definition at line 77 of file t_control_array_intreal.f90.
References m_machine_parameter::iflag_debug.
Referenced by read_control_array_i_r().
write_control_array_i_r()
subroutine t_control_array_intreal::write_control_array_i_r (integer(kind = kint), intent(in) id_control, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, type(ctl_array_ir), intent(in) array_ir)
Definition at line 200 of file t_control_array_intreal.f90.
References write_control_elements::write_array_flag_for_ctl(), write_control_elements::write_end_array_flag_for_ctl(), and write_control_elements::write_int_real_ctl_item().
write_intreal_ctl_type()
subroutine t_control_array_intreal::write_intreal_ctl_type (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, type(read_int_real_item), intent(in) ir_item)
Definition at line 102 of file t_control_array_intreal.f90.
References write_control_elements::write_int_real_ctl_item().