CALYPSO: m_constants Module Reference
m_constants Module Reference
Variables
real(kind=kreal), parameter zero = 0.0d0
real(kind=kreal), parameter one = 1.0d0
real(kind=kreal), parameter two = 2.0d0
real(kind=kreal), parameter three = 3.0d0
real(kind=kreal), parameter four = 4.0d0
real(kind=kreal), parameter five = 5.0d0
real(kind=kreal), parameter six = 6.0d0
real(kind=kreal), parameter seven = 7.0d0
real(kind=kreal), parameter eight = 8.0d0
real(kind=kreal), parameter dnine = 9.0d0
real(kind=kreal), parameter ten = 10.0d0
real(kind=kreal), parameter eleven = 11.0d0
real(kind=kreal), parameter twenty = 20.0d0
real(kind=kreal), parameter thirty = 30.0d0
real(kind=kreal), parameter half = one / two
real(kind=kreal), parameter third = one / three
real(kind=kreal), parameter quad = one / four
real(kind=kreal), parameter r125 = one / eight
real(kind=kreal), parameter deci = one / ten
real(kind=kreal), parameter dminus = -one
integer(kind=kint), parameter izero = 0
integer(kind=kint), parameter ione = 1
integer(kind=kint), parameter itwo = 2
integer(kind=kint), parameter ithree = 3
integer(kind=kint), parameter ifour = 4
integer(kind=kint), parameter ifive = 5
integer(kind=kint), parameter isix = 6
integer(kind=kint), parameter iseven = 7
integer(kind=kint), parameter ieight = 8
integer(kind=kint), parameter inine = 9
integer(kind=kint), parameter iten = 10
integer(kind=kint), parameter icent = 100
integer(kind=kint), parameter ikilo = 1000
integer(kind=kint), parameter iminus = -1
real, parameter rzero = 0.0e0
real, parameter rone = 1.0e0
real, parameter rtwo = 2.0e0
real, parameter rhalf = 0.5e0
real(kind=kreal), parameter tiny = 1.0D-11
Tiny value.
real(kind=kreal), parameter tiny9 = 1.0D-9
integer(kind=kint_gl), parameter huge_30 = 1073741824
Huge value.
integer(kind=kint_gl), parameter huge_20 = 1048576
integer(kind=kint), parameter id_turn_off = 0
Turn OFF flag.
integer(kind=kint), parameter id_turn_on = 1
Turn ON flag.
Variable Documentation
deci
real(kind = kreal), parameter m_constants::deci = one / ten
Definition at line 35 of file m_constants.f90.
dminus
real(kind = kreal), parameter m_constants::dminus = -one
Definition at line 37 of file m_constants.f90.
Referenced by cal_energy_flux_rtp::cal_energy_fluxes_on_node(), cal_gaunt_itgs::leadli(), and select_exp_scalar_icb::sel_icb_sph_scalar_advect().
dnine
real(kind = kreal), parameter m_constants::dnine = 9.0d0
Definition at line 25 of file m_constants.f90.
Referenced by initial_magne_dynamobench::initial_b_dynamobench_1(), initial_magne_dynamobench::initial_b_dynamobench_2(), initial_magne_dbench_qvc::initial_b_dynamobench_qcv(), and set_initial_sph_dynamo::set_initial_magne_sph().
eight
real(kind = kreal), parameter m_constants::eight = 8.0d0
Definition at line 24 of file m_constants.f90.
Referenced by initial_magne_dynamobench::initial_b_dynamobench_1(), initial_magne_dynamobench::initial_b_dynamobench_2(), initial_magne_dbench_qvc::initial_b_dynamobench_qcv(), global_field_4_dynamobench::pick_mag_torque_inner_core(), and set_initial_sph_dynamo::set_initial_magne_sph().
eleven
real(kind = kreal), parameter m_constants::eleven = 11.0d0
Definition at line 27 of file m_constants.f90.
five
real(kind = kreal), parameter m_constants::five = 5.0d0
Definition at line 21 of file m_constants.f90.
Referenced by cal_inner_core_rotation::cal_icore_viscous_drag_l1(), initial_magne_dynamobench::initial_b_dynamobench_1(), initial_magne_dynamobench::initial_b_dynamobench_2(), initial_magne_dbench_qvc::initial_b_dynamobench_qcv(), cal_inner_core_rotation::int_icore_tor_lorentz_l1(), global_field_4_dynamobench::pick_mag_torque_inner_core(), set_initial_sph_dynamo::set_initial_magne_sph(), and cal_inner_core_rotation::set_rotate_icb_vt_sph_mat().
four
real(kind = kreal), parameter m_constants::four = 4.0d0
Definition at line 20 of file m_constants.f90.
Referenced by field_at_mid_equator::cal_field_4_dynamobench(), gauss_integration::const_gauss_points_coefs(), chebyshev_radial_grid::count_chebyshev_ext_layers(), half_chebyshev_radial_grid::count_half_chebyshev_external(), half_chebyshev_radial_grid::half_chebyshev_distance_shell(), t_fft_test_data::init_fft_test_data(), initial_magne_dynamobench::initial_b_dynamobench_1(), initial_magne_dynamobench::initial_b_dynamobench_2(), initial_magne_dbench_qvc::initial_b_dynamobench_qcv(), global_field_4_dynamobench::pick_mag_torque_inner_core(), coordinate_converter::position_2_sph(), coordinate_converter::position_cyl_2_sph(), t_convert_from_rayleigh::rescaling_from_rayleigh(), set_initial_sph_scalars::set_all_part_temp_sph(), chebyshev_radial_grid::set_chebyshev_distance_shell(), gauss_integration::set_gauss_colat_integration(), gauss_integration::set_gauss_points_sph(), const_sph_initial_spectr::set_initial_composition(), set_initial_sph_scalars::set_initial_light_sph(), const_sph_initial_spectr::set_initial_magne_sph(), set_initial_sph_dynamo::set_initial_magne_sph(), set_initial_sph_scalars::set_initial_temp_sph(), const_sph_initial_spectr::set_initial_temperature(), const_sph_initial_spectr::set_initial_velocity(), schmidt_poly_on_rtm_grid::set_lagender_pole_rlm(), set_sph_local_node::set_local_nodes_sph_mesh(), set_node_on_edge_quad_psf::set_node_on_edge_4_quad_psf(), set_initial_sph_scalars::set_noize_scalar_sph(), and spherical_harmonics::sph_normalizations().
half
real(kind = kreal), parameter m_constants::half = one / two
Definition at line 31 of file m_constants.f90.
Referenced by const_sph_initial_spectr::add_inner_core_heat_source(), const_sph_initial_spectr::add_whole_core_heat_source(), cal_sph_exp_1st_diff_ele::cal_2nd_ele_r_fdm_coefs(), cal_sph_exp_fixed_flux::cal_div_sph_in_fix_flux_2(), cal_sph_exp_fixed_flux::cal_div_sph_out_fix_flux_2(), coef_fdm2_free_cmb::cal_fdm2_cmb_free_vp(), coef_fdm2_free_cmb::cal_fdm2_cmb_free_vt(), coef_fdm2_free_icb::cal_fdm2_icb_free_vp(), coef_fdm2_free_icb::cal_fdm2_icb_free_vt(), pickup_gauss_coefficients::cal_no_heat_source_nu(), const_radial_forces_on_bc::cal_radial_force_on_sph(), cal_sph_exp_center::cal_sph_div_flux_4_fix_ctr(), cal_sph_exp_fixed_scalar::cal_sph_div_flux_4_fix_in(), cal_sph_exp_fixed_scalar::cal_sph_div_flux_4_fix_out(), cal_sph_exp_nod_none_bc::cal_sph_nod_nobc_in_div2(), cal_sph_exp_nod_none_bc::cal_sph_nod_nobc_out_div2(), cal_sph_exp_rotation::cal_sph_nod_vect_div2(), single_pt_sph_mean_square::center_vector_mean_square(), gauss_integration::const_gauss_points_coefs(), t_sph_component_fftw::copy_comp_fftw_from_recv(), set_comm_table_prt_fftw::copy_prt_fftw_comp_from_recv(), set_comm_table_prt_fftw::copy_prt_fftw_field_from_recv(), set_comm_table_rtp_fftw::copy_rtp_fftw_comp_from_recv(), set_comm_table_rtp_fftw::copy_rtp_fftw_field_from_recv(), t_sph_single_fftw::copy_single_fftw_from_recv(), schmidt_poly_on_rtm_grid::copy_sph_normalization_2_rlm(), correlation_by_sph_spectr::correlate_each_vector_sph_spec(), chebyshev_radial_grid::count_chebyshev_ext_layers(), half_chebyshev_radial_grid::count_half_chebyshev_external(), single_pt_sph_mean_square::degree0_vector_mean_square(), cal_sph_mean_square::degree_zero_vector_mean_square(), schmidt::diff_schmidt_legendre(), schmidt_fix_m::diff_schmidt_legendre_m(), cal_sph_mean_square::each_vector_sph_spec(), fftw3_wrapper::fftw_backward_smp(), fftw3_multi_wrapper::fftw_mul_backward_smp(), half_chebyshev_radial_grid::half_chebyshev_distance_shell(), initial_magne_dbench_qvc::initial_b_dynamobench_qcv(), cal_inner_core_rotation::int_icore_tor_lorentz_l1(), interact_coriolis_rlm::interact_rot_coriolis_rlm(), normei::leades(), set_radius_func_noequi::nod_r_2nd_fdm_coef_noequi(), const_radial_4th_fdm_noequi::nod_r_4th_fdm_coef_noequi(), cal_gaunt_itgs::normki(), cal_gaunt_itgs::normli(), cal_sph_mean_square::one_field_mean_sq_to_energy(), cal_sph_mean_square::one_mode_mean_sq_to_energy(), single_pt_sph_mean_square::one_point_mean_sq_to_energy(), pickup_sph_spectr_data::pick_degre0_sped_4_monitor(), radial_int_for_sph_spec::radial_int_by_simpson(), radial_int_for_sph_spec::radial_int_by_trapezoid(), radial_int_for_sph_spec::radial_int_matrix_by_simpson(), radial_int_for_sph_spec::radial_int_matrix_by_trapezoid(), t_convert_from_rayleigh::rescaling_for_chebyshev_fft(), chebyshev_radial_grid::set_chebyshev_distance_shell(), gauss_integration::set_gauss_colat_integration(), gauss_integration::set_gauss_points_integration(), set_control_4_model::set_implicit_coefs(), field_at_mid_equator::set_mid_equator_point_global(), set_node_on_edge_quad_psf::set_node_on_edge_4_quad_psf(), set_surface_position::set_quad_surf_position(), set_radius_4_sph_dynamo::set_radius_dat_4_sph_dynamo(), t_poloidal_rotation::set_rotation_spectr(), pickup_sph_spectr::set_scale_4_vect_l0(), set_reference_temp_sph::set_stratified_sph_mhd(), cal_tave_sph_ene_spectr::sum_average_ene_spectr(), cal_tave_sph_ene_spectr::sum_deviation_ene_spectr(), t_average_nusselt(), and tave_picked_sph_spec_data().
huge_20
integer(kind = kint_gl), parameter m_constants::huge_20 = 1048576
Definition at line 66 of file m_constants.f90.
Referenced by calypso_mpi_int::calypso_mpi_allreduce_int(), calypso_mpi_int8::calypso_mpi_allreduce_int8(), calypso_mpi_real::calypso_mpi_allreduce_real(), calypso_mpi_char::calypso_mpi_bcast_character(), calypso_mpi_int::calypso_mpi_bcast_int(), calypso_mpi_int8::calypso_mpi_bcast_int8(), calypso_mpi_logical::calypso_mpi_bcast_logical(), calypso_mpi_real::calypso_mpi_bcast_real(), calypso_mpi_int::calypso_mpi_reduce_int(), calypso_mpi_int8::calypso_mpi_reduce_int8(), calypso_mpi_real::calypso_mpi_reduce_real(), calypso_mpi_int::calypso_mpi_seek_read_int(), calypso_mpi_int4::calypso_mpi_seek_read_int4(), calypso_mpi_int8::calypso_mpi_seek_read_int8(), calypso_mpi_char::calypso_mpi_seek_read_mul_chara(), calypso_mpi_real::calypso_mpi_seek_read_real(), calypso_mpi_int::calypso_mpi_seek_write_int(), calypso_mpi_int4::calypso_mpi_seek_write_int4(), calypso_mpi_int8::calypso_mpi_seek_write_int8(), calypso_mpi_real::calypso_mpi_seek_write_real(), calypso_mpi_char::calypso_mpi_seek_wrt_mul_chara(), gz_binary_io::gz_read_1d_vector_b(), gz_binary_io::gz_read_mul_character_b(), gz_binary_io::gz_read_mul_int8_b(), gz_binary_io::gz_read_mul_one_character_b(), gz_binary_io::gz_write_1d_vector_b(), gz_binary_io::gz_write_mul_character_b(), gz_binary_io::gz_write_mul_int8_b(), and gz_binary_io::gz_write_mul_one_character_b().
huge_30
integer(kind = kint_gl), parameter m_constants::huge_30 = 1073741824
Huge value.
Definition at line 65 of file m_constants.f90.
Referenced by data_convert_by_zlib::defleate_1d_character_b(), data_convert_by_zlib::defleate_1d_vector_b(), zlib_cvt_ascii_comm_tbl::defleate_comm_table(), zlib_cvt_ascii_comm_tbl::defleate_element_type(), data_convert_by_zlib::defleate_int8_vector_b(), zlib_convert_ascii_vector::defleate_node_position(), zlib_cvt_ucd_data::defleate_ucd_connect(), zlib_cvt_ucd_data::defleate_ucd_vector(), zlib_convert_ascii_vector::defleate_vector_txt(), zlib_cvt_vtk_data::defleate_vtk_celltype(), zlib_cvt_vtk_data::defleate_vtk_connect(), zlib_cvt_vtk_data::defleate_vtk_scalar(), zlib_cvt_vtk_data::defleate_vtk_tensor(), zlib_cvt_vtk_data::defleate_vtk_vector(), data_convert_by_zlib::infleate_1d_character_b(), data_convert_by_zlib::infleate_1d_vector_b(), zlib_cvt_ascii_comm_tbl::infleate_comm_table(), zlib_cvt_ascii_comm_tbl::infleate_element_type(), data_convert_by_zlib::infleate_int8_vector_b(), zlib_convert_ascii_vector::infleate_node_position(), and zlib_convert_ascii_vector::infleate_vector_txt().
icent
integer(kind = kint), parameter m_constants::icent = 100
Definition at line 50 of file m_constants.f90.
Referenced by set_initial_sph_scalars::set_initial_light_sph(), set_initial_sph_scalars::set_initial_temp_sph(), set_ucd_file_names::set_parallel_grd_file_name(), set_ucd_file_names::set_parallel_ucd_file_name(), set_ucd_file_names::set_single_grd_file_name(), and set_ucd_file_names::set_single_ucd_file_name().
id_turn_off
integer (kind=kint), parameter m_constants::id_turn_off = 0
Turn OFF flag.
Definition at line 69 of file m_constants.f90.
Referenced by set_control_4_force::set_control_4_induction().
id_turn_on
integer (kind=kint), parameter m_constants::id_turn_on = 1
Turn ON flag.
Definition at line 71 of file m_constants.f90.
Referenced by set_control_4_force::set_control_4_induction().
ieight
integer(kind = kint), parameter m_constants::ieight = 8
Definition at line 47 of file m_constants.f90.
Referenced by gz_mpi_viewer_mesh_io::gz_mpi_write_domain_grp_data(), gz_mpi_viewer_mesh_io::gz_mpi_write_viewer_grp_data(), mpi_viewer_mesh_io::mpi_write_domain_grp_data(), and mpi_viewer_mesh_io::mpi_write_viewer_grp_data().
ifive
integer(kind = kint), parameter m_constants::ifive = 5
Definition at line 44 of file m_constants.f90.
Referenced by field_at_mid_equator::cal_drift_by_v44(), const_r_mat_4_vector_sph::const_radial_mat_vort_2step(), normgi_by_primes::conut_prims_normgi(), normgi_by_primes::gs_prime(), ludcmp_357band_mul::ludcmp_5band_mul(), const_radial_4th_fdm_noequi::nod_r_4th_fdm_coef_noequi(), and set_sph_surf_group::set_sph_local_surf_grp_item().
ifour
integer(kind = kint), parameter m_constants::ifour = 4
Definition at line 43 of file m_constants.f90.
Referenced by t_sph_fftpack5::alloc_const_4_fftpack(), t_fftpack5_wrapper::alloc_const_4_fftpack_t(), t_sph_component_fftpack5::alloc_const_comp_fftpack(), t_sph_domain_fftpack5::alloc_const_domain_fftpack(), t_sph_single_fftpack5::alloc_const_sgl_fftpack(), field_at_mid_equator::cal_drift_by_v44(), const_fdm_coefs::const_4th_fdm_coefs(), m_ludcmp_3band::ludcmp_3band(), m_calypso_mpi_io::mpi_read_set_endian_flag(), and m_calypso_mpi_io::mpi_write_endian_flag().
ikilo
integer(kind = kint), parameter m_constants::ikilo = 1000
Definition at line 51 of file m_constants.f90.
Referenced by set_initial_sph_scalars::set_initial_light_sph(), and set_initial_sph_scalars::set_initial_temp_sph().
iminus
integer(kind = kint), parameter m_constants::iminus = -1
Definition at line 53 of file m_constants.f90.
Referenced by set_field_file_names::set_fem_fld_file_name(), and set_field_file_names::set_sph_fld_file_name().
inine
integer(kind = kint), parameter m_constants::inine = 9
Definition at line 48 of file m_constants.f90.
Referenced by calypso_sr_3::calypso_send_recv_3x3(), solver_sr_3::solver_send_recv_3x3(), gz_data_io::write_gz_multi_int_10i12(), and gz_data_io::write_gz_multi_int_10i8().
ione
integer(kind = kint), parameter m_constants::ione = 1
Definition at line 40 of file m_constants.f90.
Referenced by chebyshev_radial_grid::adjust_chebyshev_shell(), analyzer_test_sph::analyze_test_sph(), t_ucd_data::append_new_ucd_field_data(), t_ucd_data::append_new_ucd_field_name(), t_belonged_element_4_node::belonged_edge_id_4_node(), t_belonged_element_4_node::belonged_ele_id_4_node(), t_belonged_element_4_node::belonged_surf_id_4_node(), set_sph_exp_nod_center::cal_dsdr_sph_center_2(), interact_coriolis_rlm::cal_gaunt_coriolis_rlm(), poynting_flux_smp::cal_rtp_magnetic_streach(), poynting_flux_smp::cal_rtp_magnetic_streach_tmp(), set_sph_exp_nod_center::cal_sph_nod_center_diffuse2(), set_sph_exp_nod_center::cal_sph_nod_center_rot2(), fftpack5_wrapper::calypso_rfftmb_smp(), fftpack5_wrapper::calypso_rfftmf_smp(), calypso_sr::calypso_send_recv(), check_sph_radial_mat::check_single_radial_3band_mat(), check_sph_radial_mat::check_single_radial_5band_mat(), check_sph_radial_mat::check_single_radial_7band_mat(), circle_transform_single::circle_transfer_scalar(), circle_transform_single::circle_transfer_vector(), const_fdm_coefs::const_2e_fdm_coefs(), gauss_integration::const_gauss_points_coefs(), const_each_global_sph_list::const_global_rj_modes_by_rlm(), const_each_global_sph_list::const_global_rtm_grids(), const_each_global_sph_list::const_global_rtp_grids(), normgi_by_primes::conut_prims_normgi(), copy_sph_rj_mode_4_io::copy_sph_node_4_rj_to_io(), copy_sph_rlm_mode_4_io::copy_sph_node_4_rlm_to_io(), copy_sph_rtm_node_4_io::copy_sph_node_4_rtm_to_io(), copy_sph_rtp_node_4_io::copy_sph_node_4_rtp_to_io(), find_element_id_4_node::count_belonged_ele_4_node(), set_size_4_smp_types::count_edge_size_smp_type(), set_size_4_smp_types::count_ele_4_smp_mesh_type(), const_1d_ele_connect_4_sph::count_nod_ele_4_sph_radial(), const_1d_ele_connect_4_sph::count_nod_ele_4_sph_theta(), set_size_4_smp_types::count_node_4_smp_mesh_type(), set_psf_nodes_4_by_surf_grp::count_node_at_node_on_grp(), count_num_sph_smp::count_num_rj_smp(), count_num_sph_smp::count_num_rlm_smp(), count_num_sph_smp::count_num_rtm_smp(), count_num_sph_smp::count_num_rtp_smp(), set_sph_local_node::count_numnod_local_sph_mesh(), set_nodal_field_for_psf::count_position_4_psf(), set_psf_nodes_4_by_surf_grp::count_position_4_psf_grp(), set_sph_ele_group::count_sph_local_ele_grp_item(), set_size_4_smp_types::count_surf_size_smp_type(), convert_from_rayleigh_rst::cvt_each_field_from_rayleigh(), cvt_nodal_and_sph_field::cvt_nod_tsr_to_sph_tsr(), cvt_nodal_and_sph_field::cvt_nod_vec_to_sph_vec(), cvt_nodal_and_sph_field::cvt_sph_tsr_to_nod_tsr(), cvt_nodal_and_sph_field::cvt_sph_vec_to_nod_vec(), zlib_cvt_ascii_comm_tbl::defleate_comm_table(), zlib_cvt_ascii_comm_tbl::defleate_element_type(), zlib_convert_ascii_vector::defleate_node_position(), zlib_convert_ascii_vector::defleate_vector_txt(), delete_field_smp::delete_phys_data_smp(), cal_zonal_mean_sph_spectr::delete_zonal_mean_rj_field(), normgi_by_primes::gs_prime(), gz_mpi_domain_data_io::gz_mpi_read_export_data(), gz_mpi_domain_data_io::gz_mpi_read_import_data(), gz_mpi_binary_datum_io::gz_mpi_read_one_inthead_b(), gz_mpi_binary_datum_io::gz_mpi_read_one_realhead_b(), gz_mpi_binary_datum_io::gz_mpi_read_process_id_b(), gz_mpi_position_io::gz_mpi_read_radial_position(), gz_mpi_vectors_io::gz_mpi_read_scalar(), gz_mpi_vectors_io::gz_mpi_read_vector(), gz_mpi_domain_data_io::gz_mpi_write_export_data(), gz_mpi_domain_data_io::gz_mpi_write_import_data(), gz_mpi_binary_datum_io::gz_mpi_write_one_inthead_b(), gz_mpi_binary_datum_io::gz_mpi_write_one_realhead_b(), gz_mpi_binary_datum_io::gz_mpi_write_process_id_b(), gz_mpi_position_io::gz_mpi_write_radial_position(), gz_mpi_vectors_io::gz_mpi_write_scalar(), gz_mpi_vectors_io::gz_mpi_write_vector(), zlib_cvt_ascii_comm_tbl::infleate_comm_table(), zlib_cvt_ascii_comm_tbl::infleate_element_type(), data_convert_by_zlib::infleate_endian_flag(), zlib_convert_ascii_vector::infleate_node_position(), zlib_convert_ascii_vector::infleate_vector_txt(), m_field_file_format_labels::init_field_type_flags(), pole_sph_transform::init_pole_grids(), cal_rms_fields_by_sph::init_rms_4_sph_spectr(), pickup_sph_coefs::init_sph_radial_monitor_list(), t_coriolis_terms_rlm::init_sum_coriolis_rlm(), data_io_to_textline::integer_nolfline(), data_io_to_textline::integer_textline(), t_io_step_parameter::istep_file_w_fix_dt(), t_io_step_parameter::istep_file_w_flex_dt(), normei::leades(), cal_gaunt_itgs::leadli(), m_ludcmp_band::lubksb_band(), m_ludcmp_band::lubksb_band_mul(), m_ludcmp_3band::ludcmp_3band(), m_ludcmp_band::ludcmp_band(), mpi_sph_gl_1d_idx_io::mpi_read_1d_gl_address(), mpi_domain_data_io::mpi_read_comm_table(), mpi_domain_data_io::mpi_read_export_data(), mpi_domain_data_io::mpi_read_import_data(), mpi_position_io::mpi_read_node_position(), mpi_position_io::mpi_read_radial_position(), mpi_vectors_io::mpi_read_scalar(), mpi_vectors_io::mpi_read_vector(), mpi_sph_gl_1d_idx_io::mpi_write_1d_gl_address(), mpi_domain_data_io::mpi_write_comm_table(), mpi_domain_data_io::mpi_write_export_data(), mpi_domain_data_io::mpi_write_import_data(), mpi_binary_head_io::mpi_write_one_inthead_b(), mpi_binary_head_io::mpi_write_process_id_b(), mpi_position_io::mpi_write_radial_position(), mpi_vectors_io::mpi_write_scalar(), mpi_viewer_mesh_io::mpi_write_viewer_connect(), mpi_viewer_mesh_io::mpi_write_viewer_element_type(), mpi_viewer_mesh_io::mpi_write_viewer_grp_item(), set_radius_func_noequi::nod_r_2nd_fdm_coefs_equi(), set_radius_func_noequi::nod_r_2nd_fdm_coefs_nonequi(), const_radial_4th_fdm_noequi::nod_r_4th_fdm_coefs_nonequi(), const_sph_radial_grid::output_set_radial_grid(), cal_zonal_mean_sph_spectr::pick_del_degree_sph_spectr(), cal_zonal_mean_sph_spectr::pick_del_order_sph_spectr(), sph_prt_domain_fftpack5::prt_domain_rfftmb_from_recv(), sph_prt_domain_fftpack5::prt_domain_rfftmf_to_send(), sph_prt_fftpack5::prt_rfftmb_from_recv(), sph_prt_fftpack5::prt_rfftmf_to_send(), gz_udt_to_vtk_data_io::read_gz_udt_field_from_vtk(), gz_vtk_data_io::read_gz_vtk_each_field_head(), data_io_to_textline::read_integer_textline(), read_psf_binary_data::read_psf_ele_num_bin(), gz_read_psf_binary_data::read_psf_ele_num_bin_gz(), gz_group_data_io::read_surface_group_data_gz(), udt_to_vtk_data_io::read_udt_field_from_vtk(), sph_rtp_domain_fftpack5::rtp_domain_rfftmb_from_recv(), sph_rtp_domain_fftpack5::rtp_domain_rfftmf_to_send(), sph_rtp_fftpack5::rtp_rfftmb_from_recv(), sph_rtp_fftpack5::rtp_rfftmf_to_send(), m_ludcmp_band::set_band_mt_2_mat(), find_element_id_4_node::set_belonged_ele_4_node(), init_sph_trans::set_blocks_4_leg_trans(), chebyshev_radial_grid::set_chebyshev_distance_shell(), t_flex_delta_t_parameter::set_control_flex_time_steps(), set_ele_id_4_node_type::set_edge_id_4_node(), set_ele_id_4_node_type::set_ele_id_4_node(), set_element_list_4_surface::set_ele_list_4_edge(), set_element_list_4_surface::set_ele_list_4_surf(), set_export_sph_center_mesh::set_export_rtp_ctr_npole_mesh(), set_export_sph_center_mesh::set_export_rtp_ctr_shell_mesh(), set_scalar_boundary_sph::set_fixed_scalar_sph(), t_viz_only_step_parameter::set_fixed_t_step_params_w_viz(), t_step_parameter::set_fixed_time_step_params(), t_flex_delta_t_parameter::set_flex_time_step_params(), select_exp_scalar_icb::set_icb_scalar_sph_crank(), find_element_id_4_node::set_iele_4_node(), set_import_sph_center_mesh::set_import_rtp_ctr_npole_mesh(), set_import_sph_center_mesh::set_import_rtp_ctr_shell_mesh(), const_sph_initial_spectr::set_initial_magne_sph(), cal_sph_node_addresses::set_intnod_center(), set_item_4_sph_groups::set_item_rj_spectr_grp(), set_sph_local_node::set_local_nodes_sph_mesh(), m_ludcmp_band::set_mt_2_band_mat(), cal_sph_node_addresses::set_nnod_gl_center(), set_nodes_4_groups_viewer::set_nod_4_domain_viewer(), pickup_sph_spectr::set_picked_sph_address(), patch_4_psf::set_psf_type_id(), set_special_sph_lm_flags::set_special_degree_order_flags(), set_sph_ele_group::set_sph_local_ele_grp_item(), set_stack_4_sph_groups::set_stack_rj_spectr_grp(), set_ele_id_4_node_type::set_surf_id_4_node(), set_surface_id_4_surf_grp::set_surface_id_4_surf_group(), normei::setei(), solver_sr::solver_send_recv(), t_belonged_element_4_node::sort_inod_4_ele_by_position(), find_node_4_group::sort_next_node_list_by_weight(), set_sph_exp_nod_center::sph_center_fld_and_curl(), t_sph_component_fftpack5::sph_comp_rfftmb_from_recv(), t_sph_component_fftpack5::sph_comp_rfftmf_to_send(), t_sph_single_fftpack5::sph_single_rfftmb_from_recv(), t_sph_single_fftpack5::sph_single_rfftmf_to_send(), sum_coriolis_terms_rlm::sum_r_coriolis_bc_rlm_10(), cal_zonal_mean_sph_spectr::take_zonal_mean_rj_field(), ucd_data_to_buffer::ucd_each_connect(), vtk_data_to_buffer::vtk_scalar_head(), t_control_array_character2::write_character2_ctl_type(), t_flex_delta_t_data::write_delta_t_check_head(), t_fft_test_data::write_fft_test_data(), gz_data_io::write_gz_multi_int_10i12(), gz_data_io::write_gz_multi_int_10i8(), gz_data_io::write_gz_multi_int_8i16(), gz_data_io::write_gz_surf_group(), mpi_picked_sph_spectr_io::write_picked_specr_head_mpi(), viewer_mesh_data_io::write_sgl_domain_data_viewer(), mpi_sph_gauss_coefs_io::write_sph_gauss_coefes_mpi(), mpi_sph_gauss_coefs_io::write_sph_gauss_header_mpi(), gz_group_data_io::write_surf_group_data_gz(), udt_data_io::write_ucd_mesh_connect(), sph_rtp_zonal_rms_data::zonal_cyl_rms_all_rtp_field(), sph_rtp_zonal_rms_data::zonal_mean_all_rtp_field(), cal_zonal_mean_sph_spectr::zonal_mean_all_sph_spectr(), and sph_rtp_zonal_rms_data::zonal_rms_all_rtp_field().
iseven
integer(kind = kint), parameter m_constants::iseven = 7
Definition at line 46 of file m_constants.f90.
Referenced by ludcmp_357band_mul::ludcmp_7band_mul(), gz_data_io::write_gz_multi_int_8i16(), and gz_data_io::write_gz_surf_group().
isix
integer(kind = kint), parameter m_constants::isix = 6
Definition at line 45 of file m_constants.f90.
Referenced by analyzer_test_sph::analyze_test_sph(), calypso_sr_2::calypso_send_recv_3x2(), calypso_sr_6::calypso_send_recv_3x6(), calypso_sr_6::calypso_send_recv_6(), cvt_nodal_and_sph_field::cvt_nod_tsr_to_sph_tsr(), cvt_nodal_and_sph_field::cvt_nod_vec_to_sph_vec(), cvt_nodal_and_sph_field::cvt_sph_tsr_to_nod_tsr(), cvt_nodal_and_sph_field::cvt_sph_vec_to_nod_vec(), delete_field_smp::delete_phys_data_smp(), select_copy_from_recv::sel_cppy_from_recv_buf_3x6(), spherical_srs_n::send_recv_sph_trans_6(), set_sph_surf_group::set_sph_local_surf_grp_item(), solver_sr_6::solver_send_recv_6(), and sph_analyzer_d_bench::sph_init_sph_dbench().
iten
integer(kind = kint), parameter m_constants::iten = 10
Definition at line 49 of file m_constants.f90.
Referenced by cal_num_digits::cal_num_digit_int(), gz_mpi_element_connect_io::gz_mpi_read_element_info(), gz_mpi_element_connect_io::gz_mpi_write_element_info(), gz_mpi_viewer_mesh_file_io::gz_write_viewer_mesh_infos(), mpi_element_connect_io::mpi_read_element_info(), mpi_element_connect_io::mpi_write_element_info(), set_field_file_names::set_fem_fld_file_name(), set_mesh_file_names::set_mesh_file_name(), set_ucd_file_names::set_parallel_grd_file_name(), set_ucd_file_names::set_parallel_ucd_file_name(), set_ucd_file_names::set_single_grd_file_name(), set_ucd_file_names::set_single_ucd_file_name(), set_field_file_names::set_sph_fld_file_name(), and mpi_viewer_mesh_file_io::write_viewer_mesh_infos().
ithree
integer(kind = kint), parameter m_constants::ithree = 3
Definition at line 42 of file m_constants.f90.
Referenced by analyzer_test_sph::analyze_test_sph(), calypso_sr_2::calypso_send_recv_2(), calypso_sr_3::calypso_send_recv_3(), calypso_sr::calypso_send_recv_3x1(), calypso_sr_2::calypso_send_recv_3x2(), calypso_sr_3::calypso_send_recv_3x3(), calypso_sr_6::calypso_send_recv_3x6(), check_sph_radial_mat::check_single_radial_7band_mat(), circle_transform_single::circle_transfer_vector(), copy_sph_rtm_node_4_io::compare_sph_rtm_node_with_io(), copy_sph_rtp_node_4_io::compare_sph_rtp_node_with_io(), const_r_mat_4_vector_sph::const_radial_mat_4_magne_sph(), const_r_mat_4_scalar_sph::const_radial_mat_4_press_sph(), const_r_mat_4_scalar_sph::const_radial_mat_4_scalar_sph(), const_r_mat_4_vector_sph::const_radial_mat_vort_2step(), const_r_mat_w_center_sph::const_rmat_press00_sph(), const_r_mat_w_center_sph::const_rmat_scalar00_sph(), normgi_by_primes::conut_prims_normgi(), copy_sph_rj_mode_4_io::copy_sph_node_4_rj_to_io(), copy_sph_rlm_mode_4_io::copy_sph_node_4_rlm_to_io(), copy_sph_rtm_node_4_io::copy_sph_node_4_rtm_from_io(), copy_sph_rtm_node_4_io::copy_sph_node_4_rtm_to_io(), copy_sph_rtp_node_4_io::copy_sph_node_4_rtp_from_io(), copy_sph_rtp_node_4_io::copy_sph_node_4_rtp_to_io(), t_spheric_rtm_data::copy_spheric_rtm_data(), t_spheric_rtp_data::copy_spheric_rtp_data(), delete_field_smp::delete_phys_data_smp(), normgi_by_primes::gs_prime(), m_section_coef_flags::init_section_coef_flags(), hdf5_file_io::parallel_write_xdmf_file(), gz_udt_to_vtk_data_io::read_alloc_gz_ucd_grd_from_vtk(), udt_to_vtk_data_io::read_alloc_ucd_mesh_from_vtk(), gz_udt_to_vtk_data_io::read_gz_ucd_grd_from_vtk(), read_psf_binary_data::read_psf_node_data_bin(), gz_read_psf_binary_data::read_psf_node_data_bin_gz(), udt_to_vtk_data_io::read_ucd_mesh_from_vtk(), spherical_srs_n::send_recv_sph_trans_2(), spherical_srs_n::send_recv_sph_trans_3(), set_loaded_data_4_sph::set_index_flags_4_sph(), set_item_4_sph_groups::set_item_rj_spectr_grp(), set_psf_nodes_4_by_surf_grp::set_position_at_nod_psf(), set_nodal_field_for_psf::set_position_on_edge_psf(), set_stack_4_sph_groups::set_stack_rj_spectr_grp(), solver_sr_3::solver_send_recv_3(), solver_sr::solver_send_recvx3(), t_flex_delta_t_data::write_delta_t_check_head(), gz_udt_type_data_io::write_gz_ucd_type_mesh(), udt_to_vtk_data_io::write_ucd_mesh_to_vtk(), udt_type_data_io::write_ucd_type_mesh(), and mpi_viewer_mesh_file_io::write_viewer_mesh_infos().
itwo
integer(kind = kint), parameter m_constants::itwo = 2
Definition at line 41 of file m_constants.f90.
Referenced by chebyshev_radial_grid::adjust_chebyshev_shell(), analyzer_test_sph::analyze_test_sph(), calypso_sr_2::calypso_send_recv_2(), calypso_sr_2::calypso_send_recv_3x2(), check_sph_radial_mat::check_single_radial_5band_mat(), check_sph_radial_mat::check_single_radial_7band_mat(), copy_sph_rlm_mode_4_io::compare_sph_mode_rlm_with_io(), copy_sph_rj_mode_4_io::compare_sph_node_rj_with_io(), const_fdm_coefs::const_2nd_fdm_matrices(), gauss_integration::const_gauss_points_coefs(), copy_sph_rj_mode_4_io::copy_sph_node_4_rj_from_io(), copy_sph_rj_mode_4_io::copy_sph_node_4_rj_to_io(), copy_sph_rlm_mode_4_io::copy_sph_node_4_rlm_from_io(), copy_sph_rlm_mode_4_io::copy_sph_node_4_rlm_to_io(), copy_sph_rtm_node_4_io::copy_sph_node_4_rtm_to_io(), copy_sph_rtp_node_4_io::copy_sph_node_4_rtp_to_io(), t_spheric_rj_data::copy_spheric_rj_data(), t_spheric_rlm_data::copy_spheric_rlm_data(), m_field_file_format_labels::init_field_type_flags(), m_file_format_labels::init_file_format_flags(), m_section_coef_flags::init_section_coef_flags(), cal_gaunt_itgs::leadki(), cal_gaunt_itgs::leadli(), m_ludcmp_3band::ludcmp_3band(), const_radial_4th_fdm_noequi::nod_r_4th_fdm_coefs_nonequi(), gz_group_data_io::read_surface_group_data_gz(), chebyshev_radial_grid::set_chebyshev_distance_shell(), set_loaded_data_4_sph::set_index_flags_4_rj(), set_loaded_data_4_sph::set_index_flags_4_sph(), set_item_4_sph_groups::set_item_rj_spectr_grp(), patch_4_psf::set_psf_type_id(), set_stack_4_sph_groups::set_stack_rj_spectr_grp(), set_surface_id_4_surf_grp::set_surface_id_4_surf_group(), t_fft_test_data::write_fft_test_data(), and gz_group_data_io::write_surf_group_data_gz().
izero
integer(kind = kint), parameter m_constants::izero = 0
Definition at line 39 of file m_constants.f90.
Referenced by copy_sph_1d_global_index::add_center_mode_rj(), const_sph_initial_spectr::add_inner_core_heat_source(), const_sph_initial_spectr::add_outer_core_heat_source(), const_sph_initial_spectr::add_whole_core_heat_source(), const_sph_initial_spectr::adjust_by_cmb_temp(), t_flex_delta_t_data::alloc_check_delta_t_data(), t_flex_delta_t_data::alloc_check_delta_t_name(), t_circle_transform::alloc_circle_field(), set_ucd_data_to_type::alloc_phys_name_type_by_output(), t_read_sph_spectra::alloc_sph_spectr_data(), r_interpolate_sph_data::allocate_original_sph_data(), t_belonged_element_4_node::belonged_edge_id_4_node(), t_belonged_element_4_node::belonged_ele_id_4_node(), t_belonged_element_4_node::belonged_surf_id_4_node(), interact_coriolis_rlm::cal_gaunt_coriolis_rlm(), pickup_gauss_coefficients::cal_no_heat_source_nu(), volume_average_4_sph::cal_volume_average_sph(), parallel_gen_sph_grids::check_and_make_para_rj_mode(), t_check_and_make_sph_mesh::check_and_make_sph_mesh(), t_check_and_make_sph_mesh::check_and_make_sph_rj_mode(), mpi_sph_gauss_coefs_io::check_gauss_coefs_num(), check_sph_radial_mat::check_radial_3band_mat_w_ctr(), set_ele_id_4_node_type::const_next_nod_id_4_node(), normgi_by_primes::conut_prims_normgi(), copy_communication_table::copy_num_export(), copy_communication_table::copy_num_import(), t_read_sph_spectra::copy_read_ene_params_4_sum(), copy_sph_rj_mode_4_io::copy_sph_node_4_rj_to_io(), correlation_by_sph_spectr::correlate_each_vector_sph_spec(), set_comm_tbl_4_pole_mesh::count_export_4_npole_mesh(), set_comm_tbl_4_sph_mesh::count_export_4_shell_mesh(), const_comm_tbl_4_sph_mesh::count_export_4_sph_mesh(), set_comm_tbl_4_pole_mesh::count_export_4_spole_mesh(), set_comm_tbl_4_pole_mesh::count_import_4_npole_mesh(), set_comm_tbl_4_sph_mesh::count_import_4_shell_mesh(), const_comm_tbl_4_sph_mesh::count_import_4_sph_mesh(), set_comm_tbl_4_pole_mesh::count_import_4_spole_mesh(), const_comm_tbl_4_sph_mesh::count_neib_4_sph_center_mesh(), const_comm_tbl_4_sph_mesh::count_neib_4_sph_mesh(), pickup_sph_spectr::count_picked_sph_adrress(), cal_sph_mean_square::each_vector_sph_spec(), normgi_by_primes::gs_prime(), gz_read_psf_binary_file::gz_read_alloc_iso_bin_file(), gz_read_psf_binary_file::gz_read_alloc_psf_bin_file(), gz_read_psf_binary_file::gz_read_alloc_psf_bin_grid(), gz_field_data_mpi_io::gz_read_each_field_mpi(), gz_read_psf_binary_file::gz_read_iso_bin_file(), gz_read_psf_binary_file::gz_read_psf_bin_file(), gz_read_psf_binary_file::gz_read_psf_bin_grid(), gz_field_data_mpi_io::gz_write_fld_vecotr_mpi(), pickup_gauss_coefficients::init_gauss_coefs_4_monitor(), t_coriolis_terms_rlm::init_sum_coriolis_rlm(), simple_sph_spectr_head_io::input_sph_pwr_layer_head(), simple_sph_spectr_head_io::input_sph_pwr_layer_head_old(), simple_sph_spectr_head_io::input_sph_pwr_vol_head(), simple_sph_spectr_head_io::input_sph_pwr_vol_head_old(), t_io_step_parameter::istep_file_w_fix_dt(), cal_gaunt_itgs::leadki(), legendre_fwd_trans_symmetry::leg_fwd_trans_scalar_sym_org(), legendre_fwd_trans_sym_spin::leg_fwd_trans_scalar_sym_spin(), mpi_ascii_data_io::open_read_mpi_file(), mpi_ascii_data_io::open_write_mpi_file(), cal_zonal_mean_sph_spectr::pick_del_degree_sph_spectr(), cal_zonal_mean_sph_spectr::pick_del_order_sph_spectr(), gz_udt_to_vtk_data_io::read_alloc_gz_udt_fld_from_vtk(), read_psf_binary_file::read_alloc_iso_bin_file(), read_psf_binary_file::read_alloc_nostep_iso_bin_file(), read_psf_binary_file::read_alloc_nostep_psf_bin_file(), read_psf_binary_file::read_alloc_psf_bin_file(), read_psf_binary_file::read_alloc_psf_bin_grid(), udt_to_vtk_data_io::read_alloc_udt_field_from_vtk(), domain_data_io::read_export_data(), gz_field_block_mpi_io::read_field_header_gz_mpi(), group_data_io::read_group_stack(), gz_udt_to_vtk_data_io::read_gz_udt_field_from_vtk(), gz_vtk_data_io::read_gz_vtk_each_field_head(), domain_data_io::read_import_data(), read_psf_binary_file::read_iso_bin_file(), read_psf_binary_file::read_psf_bin_file(), read_psf_binary_file::read_psf_bin_grid(), udt_to_vtk_data_io::read_udt_field_from_vtk(), t_time_data::reset_time_data(), const_data_4_dynamobench::s_const_data_4_dynamobench(), copy_field_data_4_dt_check::s_copy_field_data_for_dt_check(), select_diff_adv_source::sel_ctr_scl_diff_adv_src_adams(), select_diff_adv_source::sel_ctr_scl_diff_adv_src_euler(), select_diff_adv_source::sel_ini_adams_scalar_w_src(), select_diff_adv_source::sel_scalar_diff_adv_src_adams(), select_diff_adv_source::sel_scalar_diff_adv_src_euler(), t_field_on_circle::set_circle_point_global(), t_flex_delta_t_parameter::set_control_flex_time_steps(), cal_rms_fields_by_sph::set_domains_4_spectr_output(), set_ele_id_4_node_type::set_edge_id_4_node(), set_ele_id_4_node_type::set_ele_id_4_node(), set_comm_tbl_4_pole_mesh::set_export_rtp_npole_mesh(), set_comm_tbl_4_sph_mesh::set_export_rtp_shell_mesh(), set_comm_tbl_4_pole_mesh::set_export_rtp_spole_mesh(), set_psf_nodes_4_by_surf_grp::set_field_on_psf_grp_xyz(), pickup_gauss_coefficients::set_gauss_coefs_labels(), set_ele_id_4_node_type::set_grouped_ele_id_4_node(), set_comm_tbl_4_pole_mesh::set_import_rtp_npole_mesh(), set_comm_tbl_4_sph_mesh::set_import_rtp_shell_mesh(), set_comm_tbl_4_pole_mesh::set_import_rtp_spole_mesh(), const_sph_initial_spectr::set_initial_composition(), const_sph_initial_spectr::set_initial_heat_source_sph(), const_sph_initial_spectr::set_initial_light_source_sph(), const_sph_initial_spectr::set_initial_magne_sph(), const_sph_initial_spectr::set_initial_temperature(), const_sph_initial_spectr::set_initial_velocity(), set_item_4_sph_groups::set_item_rj_spectr_grp(), set_ele_id_4_node_type::set_layerd_ele_id_4_node(), const_comm_tbl_4_sph_mesh::set_neib_4_sph_center_mesh(), const_comm_tbl_4_sph_mesh::set_neib_4_sph_mesh(), set_ucd_file_names::set_parallel_grd_file_name(), pickup_sph_spectr::set_picked_sph_address(), set_nodal_field_for_psf::set_position_4_psf(), set_psf_nodes_4_by_surf_grp::set_position_psf_grp(), set_reference_temp_sph::set_reftemp_4_sph(), set_ucd_file_names::set_single_grd_file_name(), set_special_sph_lm_flags::set_special_degree_order_flags(), set_stack_4_sph_groups::set_stack_rj_spectr_grp(), set_ele_id_4_node_type::set_surf_id_4_node(), load_mesh_data::set_zero_mesh_data(), load_mesh_data::set_zero_node_data(), sum_coriolis_terms_rlm::sum_r_coriolis_bc_rlm_10(), ucd_data_to_buffer::ucd_connect_head(), t_viz_step_parameter::viz_fixed_time_step_params(), t_viz_step_parameter::viz_flex_time_step_controls(), t_no_heat_nusselt::write_no_heat_source_nu(), mpi_picked_sph_spectr_io::write_picked_specr_data_mpi(), output_sph_m_square_file::write_sph_layer_ms_file(), output_sph_m_square_file::write_sph_layer_spectr_file(), t_picked_sph_spectr_data_io::write_tave_sph_spec_monitor(), and udt_data_io::write_udt_mesh_header().
one
real(kind = kreal), parameter m_constants::one = 1.0d0
Definition at line 17 of file m_constants.f90.
Referenced by matmul_for_legendre_trans::add_matmul_bwd_leg_trans(), matmul_for_legendre_trans::add_matmul_fwd_leg_trans(), center_sph_matrices::add_scalar_poisson_mat_fix_ctr(), center_sph_matrices::add_scalar_poisson_mat_no_fld(), coef_fdm2_to_center::cal_2nd_center_fix_df_fdm(), coef_fdm2_to_center::cal_2nd_center_fixed_fdm(), cal_sph_exp_1st_diff_ele::cal_2nd_ele_r_fdm_coefs(), coef_fdm2_to_center::cal_2nd_to_center_fixed_fdm(), cal_fdm_coefs_4_boundaries::cal_fdm1_coef_fix_fld_cmb(), cal_fdm_coefs_4_boundaries::cal_fdm1_coef_fix_fld_icb(), coef_fdm2_free_cmb::cal_fdm2_cmb_free_vp(), coef_fdm2_free_cmb::cal_fdm2_cmb_free_vt(), cal_fdm_coefs_4_boundaries::cal_fdm2_coef_fix_df_cmb(), cal_fdm_coefs_4_boundaries::cal_fdm2_coef_fix_df_icb(), cal_fdm_coefs_4_boundaries::cal_fdm2_coef_fix_fld_cmb(), cal_fdm_coefs_4_boundaries::cal_fdm2_coef_fix_fld_icb(), coef_fdm2_free_icb::cal_fdm2_icb_free_vp(), coef_fdm2_free_icb::cal_fdm2_icb_free_vt(), field_at_mid_equator::cal_field_4_dynamobench(), mat_product_3band_mul::cal_mat_product_3band_mul(), cal_num_digits::cal_num_digit_int(), cal_num_digits::cal_num_digit_real(), set_evoluved_boundaries::cal_sph_nod_evo_scalar_bc(), set_evoluved_boundaries::cal_sph_nod_evo_vector_bc(), cal_sph_exp_nod_icb_ins::cal_sph_nod_icb_ins_b_and_j(), cal_sph_exp_nod_icb_ins::cal_sph_nod_icb_ins_diffuse2(), cal_sph_exp_nod_icb_ins::cal_sph_nod_icb_ins_mag2(), cal_sph_exp_nod_icb_ins::cal_sph_nod_icb_ins_rot2(), cal_sph_exp_nod_icb_ins::cal_sph_nod_icb_ins_vp_rot2(), cal_sph_zonal_ave_rms_data::cal_sph_zonal_ave_data_pin(), cal_sph_zonal_ave_rms_data::cal_sph_zonal_ave_data_rin(), cal_sph_zonal_ave_rms_data::cal_sph_zonal_rms_data_pin(), cal_sph_zonal_ave_rms_data::cal_sph_zonal_rms_data_rin(), const_wz_coriolis_rtp::cal_wz_coriolis_pole(), t_convert_from_rayleigh::chebyshev_fwd_mat_4_rayleigh(), gauss_integration::const_gauss_points_coefs(), radial_interpolation::const_radial_itp_table(), const_r_mat_4_vector_sph::const_radial_mat_4_magne_sph(), const_r_mat_4_scalar_sph::const_radial_mat_4_scalar_sph(), const_r_mat_4_vector_sph::const_radial_mat_vort_2step(), const_r_mat_w_center_sph::const_rmat_scalar00_sph(), construct_mhd_coefficient::construct_coefficient(), copy_sph_rj_mode_4_io::copy_sph_node_4_rj_from_io(), center_sph_matrices::copy_to_band3_mat_w_center(), chebyshev_radial_grid::count_chebyshev_ext_layers(), half_chebyshev_radial_grid::count_half_chebyshev_external(), factorials::factorial(), pickup_gauss_coefficients::gauss_coefficients_4_write(), extend_potential_field::gauss_to_poloidal_in(), extend_potential_field_t::gauss_to_poloidal_in_t(), extend_potential_field::gauss_to_poloidal_out(), extend_potential_field_t::gauss_to_poloidal_out_t(), normgi_by_primes::gs_prime(), half_chebyshev_radial_grid::half_chebyshev_distance_shell(), fftw3_multi_wrapper::init_4_fftw_mul_smp(), fftw3_wrapper::init_4_fftw_smp(), t_fft_test_data::init_fft_test_data(), sph_prt_fftw::init_prt_fftw(), sph_prt_domain_fftw::init_prt_field_fftw(), sph_rtp_fftw::init_rtp_fftw(), sph_rtp_domain_fftw::init_rtp_field_fftw(), t_sph_component_fftw::init_sph_component_fftw(), t_sph_single_fftw::init_sph_single_fftw(), initial_magne_dynamobench::initial_b_dynamobench_1(), initial_magne_dynamobench::initial_b_dynamobench_2(), initial_magne_dbench_qvc::initial_b_dynamobench_qcv(), circle_transform_single::initialize_circle_transform(), small_matmul_leg_trans_krin::matmul2_bwd_leg_trans_pjt(), small_matmul_leg_trans_krin::matmul2_fwd_leg_trans_ptj(), small_matmul_leg_trans_krin::matmul4_bwd_leg_trans_pjt(), small_matmul_leg_trans_krin::matmul4_fwd_leg_trans_ptj(), small_matmul_leg_trans_krin::matmul8_bwd_leg_trans_pjt(), small_matmul_leg_trans_krin::matmul8_fwd_leg_trans_ptj(), matmul_for_legendre_trans::matmul_bwd_leg_trans(), matmul_for_legendre_trans::matmul_bwd_leg_trans_pjl(), matmul_for_legendre_trans::matmul_fwd_leg_trans(), matmul_for_legendre_trans::matmul_fwd_leg_trans_pjl(), set_radius_func_noequi::nod_r_2nd_fdm_coef_noequi(), const_radial_4th_fdm_noequi::nod_r_4th_fdm_coef_noequi(), global_field_4_dynamobench::pick_mag_torque_inner_core(), coordinate_converter::position_2_sph(), coordinate_converter::position_cyl_2_sph(), coordinate_converter::position_sph_2_cyl_radius(), set_params_sph_trans::radial_4_sph_trans(), t_convert_from_rayleigh::rescaling_for_chebyshev_fft(), t_convert_from_rayleigh::rescaling_from_rayleigh(), schmidt::schmidt_legendre(), schmidt_fix_m::schmidt_legendre_m(), set_initial_sph_scalars::set_all_part_temp_sph(), chebyshev_radial_grid::set_chebyshev_distance_shell(), t_field_on_circle::set_circle_point_global(), set_cross_section_coefs::set_coefs_4_ellipsode(), set_cross_section_coefs::set_coefs_4_hyperboloide(), set_cross_section_coefs::set_coefs_4_parabolic(), set_cross_section_coefs::set_coefs_4_sphere(), set_comm_table_prt_fftpack::set_comm_item_prt_4_fftpack(), set_comm_table_rtp_fftpack::set_comm_item_rtp_4_fftpack(), material_property::set_composition_property(), material_property::set_conductive_property(), set_control_4_force::set_control_4_coriolis_force(), set_sph_scalar_mat_bc::set_fix_fld_cmb_poisson_mat(), set_sph_scalar_mat_bc::set_fix_fld_icb_poisson_mat(), material_property::set_fluid_property(), gauss_integration::set_gauss_colat_integration(), gauss_integration::set_gauss_points_sph(), construct_mhd_coefficient::set_implicit_4_inf_viscous(), set_control_4_model::set_implicit_coefs(), const_sph_initial_spectr::set_initial_composition(), set_initial_sph_scalars::set_initial_light_sph(), const_sph_initial_spectr::set_initial_magne_sph(), set_initial_sph_dynamo::set_initial_magne_sph(), set_initial_sph_scalars::set_initial_temp_sph(), const_sph_initial_spectr::set_initial_temperature(), const_sph_initial_spectr::set_initial_velocity(), set_sph_magne_mat_bc::set_ins_magne_icb_rmat_sph(), schmidt_poly_on_rtm_grid::set_lagender_pole_rlm(), set_sph_local_node::set_local_nodes_sph_mesh(), set_node_on_edge_quad_psf::set_node_on_edge_4_quad_psf(), set_initial_sph_scalars::set_noize_scalar_sph(), patch_4_psf::set_psf_type_id(), set_radius_4_sph_dynamo::set_radius_dat_4_sph_dynamo(), t_poloidal_rotation::set_rot_earth_4_sph(), cal_inner_core_rotation::set_rotate_icb_vt_sph_mat(), pickup_sph_spectr::set_scale_4_vect_l0(), set_params_sph_trans::set_sin_theta_rtm(), set_reference_temp_sph::set_stratified_sph_mhd(), material_property::set_thermal_property(), set_radial_mat_sph::set_unit_mat5_4_time_evo(), set_radial_mat_sph::set_unit_mat_4_poisson(), set_radial_mat_sph::set_unit_mat_4_time_evo(), spherical_harmonics::sph_normalizations(), spherical_harmonics::spheric(), t_average_nusselt(), and tave_picked_sph_spec_data().
quad
real(kind = kreal), parameter m_constants::quad = one / four
Definition at line 33 of file m_constants.f90.
Referenced by field_at_mid_equator::cal_drift_by_v44(), field_at_mid_equator::cal_field_4_dynamobench(), gauss_integration::const_gauss_points_coefs(), set_surface_position::set_linear_surf_position(), and set_surface_position::set_quad_surf_position().
r125
real(kind = kreal), parameter m_constants::r125 = one / eight
Definition at line 34 of file m_constants.f90.
rhalf
real, parameter m_constants::rhalf = 0.5e0
Definition at line 58 of file m_constants.f90.
rone
real, parameter m_constants::rone = 1.0e0
Definition at line 56 of file m_constants.f90.
rtwo
real, parameter m_constants::rtwo = 2.0e0
Definition at line 57 of file m_constants.f90.
rzero
real, parameter m_constants::rzero = 0.0e0
Definition at line 55 of file m_constants.f90.
seven
real(kind = kreal), parameter m_constants::seven = 7.0d0
Definition at line 23 of file m_constants.f90.
six
real(kind = kreal), parameter m_constants::six = 6.0d0
Definition at line 22 of file m_constants.f90.
Referenced by initial_magne_dynamobench::initial_b_dynamobench_2(), initial_magne_dbench_qvc::initial_b_dynamobench_qcv(), set_initial_sph_scalars::set_all_part_temp_sph(), set_initial_sph_dynamo::set_initial_magne_sph(), and set_initial_sph_scalars::set_noize_scalar_sph().
ten
real(kind = kreal), parameter m_constants::ten = 10.0d0
Definition at line 26 of file m_constants.f90.
Referenced by cal_num_digits::cal_num_digit_int(), cal_num_digits::cal_num_digit_real(), initial_magne_dynamobench::initial_b_dynamobench_1(), initial_magne_dynamobench::initial_b_dynamobench_2(), initial_magne_dbench_qvc::initial_b_dynamobench_qcv(), and set_initial_sph_dynamo::set_initial_magne_sph().
third
real(kind = kreal), parameter m_constants::third = one / three
Definition at line 32 of file m_constants.f90.
Referenced by set_surface_position::set_triangle_surf_position().
thirty
real(kind = kreal), parameter m_constants::thirty = 30.0d0
Definition at line 29 of file m_constants.f90.
three
real(kind = kreal), parameter m_constants::three = 3.0d0
Definition at line 19 of file m_constants.f90.
Referenced by const_sph_initial_spectr::add_inner_core_heat_source(), const_sph_initial_spectr::add_outer_core_heat_source(), const_sph_initial_spectr::add_whole_core_heat_source(), div_self_buoyancies_sph::cal_div_buoyancy_sph_mhd(), div_self_buoyancies_sph::cal_div_double_buoyancy_sph_mhd(), cal_ave_4_rms_vector_sph::cal_one_over_volume(), initial_magne_dynamobench::initial_b_dynamobench_1(), initial_magne_dynamobench::initial_b_dynamobench_2(), initial_magne_dbench_qvc::initial_b_dynamobench_qcv(), global_field_4_dynamobench::pick_mag_torque_inner_core(), set_initial_sph_scalars::set_all_part_temp_sph(), const_sph_initial_spectr::set_initial_composition(), const_sph_initial_spectr::set_initial_heat_source_sph(), set_initial_sph_scalars::set_initial_light_sph(), set_initial_sph_dynamo::set_initial_magne_sph(), set_initial_sph_scalars::set_initial_temp_sph(), const_sph_initial_spectr::set_initial_temperature(), set_initial_sph_scalars::set_noize_scalar_sph(), and sum_coriolis_terms_rlm::sum_r_coriolis_bc_rlm_10().
tiny
real(kind = kreal), parameter m_constants::tiny = 1.0D-11
Tiny value.
Definition at line 61 of file m_constants.f90.
Referenced by const_global_element_ids::check_element_position(), t_fft_test_data::compare_fft_tests(), gauss_points_io::compare_gauss_point_data(), m_ludcmp_3band::ludcmp_3band(), m_ludcmp_band::ludcmp_band(), set_element_export_item::search_target_element2(), and set_element_export_item::search_target_element3().
tiny9
real(kind = kreal), parameter m_constants::tiny9 = 1.0D-9
Definition at line 62 of file m_constants.f90.
twenty
real(kind = kreal), parameter m_constants::twenty = 20.0d0
Definition at line 28 of file m_constants.f90.
two
real(kind = kreal), parameter m_constants::two = 2.0d0
Definition at line 18 of file m_constants.f90.
Referenced by set_sph_scalar_mat_bc::add_cmb_scalar_poisson_mat(), set_sph_scalar_mat_bc::add_icb_scalar_poisson_mat(), center_sph_matrices::add_scalar_poisson_mat_ctr1(), center_sph_matrices::add_scalar_poisson_mat_fill_ctr(), center_sph_matrices::add_scalar_poisson_mat_fix_ctr(), set_radial_mat_sph::add_scalar_poisson_mat_sph(), set_radial_mat_sph::add_scalar_r_diffuse_mat_sph(), set_scalar_boundary_sph::adjust_in_fixed_flux_sph(), set_scalar_boundary_sph::adjust_out_fixed_flux_sph(), t_sph_fftpack5::alloc_const_4_fftpack(), t_fftpack5_wrapper::alloc_const_4_fftpack_t(), t_sph_component_fftpack5::alloc_const_comp_fftpack(), t_sph_domain_fftpack5::alloc_const_domain_fftpack(), t_sph_single_fftpack5::alloc_const_sgl_fftpack(), coef_fdm2_to_center::cal_2nd_center_fix_df_fdm(), coef_fdm2_to_center::cal_2nd_center_fixed_fdm(), coef_fdm2_to_center::cal_2nd_to_center_fixed_fdm(), mag_of_field_smp::cal_asym_tensor_magnitude(), cvt_sph_tensor_2_cyl_smp::cal_cyl_tensor_by_sph_smp(), cvt_xyz_tensor_2_cyl_smp::cal_cyl_tensor_smp(), cvt_sph_tensor_2_cyl_smp::cal_cyl_zz_tensor_by_sph_smp(), coef_fdm2_free_cmb::cal_fdm2_cmb_free_vt(), cal_fdm_coefs_4_boundaries::cal_fdm2_coef_fix_df_cmb(), cal_fdm_coefs_4_boundaries::cal_fdm2_coef_fix_df_icb(), cal_fdm_coefs_4_boundaries::cal_fdm2_coef_fix_fld_cmb(), cal_fdm_coefs_4_boundaries::cal_fdm2_coef_fix_fld_icb(), coef_fdm2_free_icb::cal_fdm2_icb_free_vt(), field_at_mid_equator::cal_field_4_dynamobench(), cal_inner_core_rotation::cal_icore_viscous_drag_l1(), set_coefs_of_sections::cal_normal_of_plane(), cvt_xyz_tensor_2_cyl_smp::cal_pp_cyl_tensor_smp(), cvt_xyz_tensor_2_sph_smp::cal_pp_tensor_smp(), cvt_xyz_tensor_2_sph_smp::cal_rr_tensor_smp(), cvt_xyz_tensor_2_sph_smp::cal_rt_tensor_smp(), cal_sph_exp_center::cal_sph_filled_center_diffuse2(), cal_sph_exp_fixed_scalar::cal_sph_fix_scalar_in_diffuse2(), cal_sph_exp_center::cal_sph_fixed_center1_diffuse2(), cal_sph_exp_fixed_flux::cal_sph_in_fix_flux_diffuse2(), cal_sph_exp_diffusion::cal_sph_nod_scalar_diffuse2(), cal_sph_exp_fixed_flux::cal_sph_out_fix_flux_diffuse2(), cal_sph_exp_fixed_scalar::cal_sph_out_fix_scalar_diffuse2(), cvt_xyz_tensor_2_sph_smp::cal_sph_tensor_smp(), cvt_sph_tensor_2_cyl_smp::cal_ss_tensor_by_sph_smp(), cvt_xyz_tensor_2_cyl_smp::cal_ss_tensor_smp(), mag_of_field_smp::cal_sym_tensor_magnitude(), cvt_xyz_tensor_2_sph_smp::cal_tt_tensor_smp(), cvt_cyl_tensor_2_xyz_smp::cal_xx_tensor_by_cyl_smp(), cvt_sph_tensor_2_xyz_smp::cal_xx_tensor_by_sph_smp(), cvt_cyl_tensor_2_xyz_smp::cal_xyz_tensor_by_cyl_smp(), cvt_sph_tensor_2_xyz_smp::cal_xyz_tensor_by_sph_smp(), cvt_cyl_tensor_2_xyz_smp::cal_yy_tensor_by_cyl_smp(), cvt_sph_tensor_2_xyz_smp::cal_yy_tensor_by_sph_smp(), cvt_sph_tensor_2_xyz_smp::cal_zz_tensor_by_sph_smp(), t_convert_from_rayleigh::chebyshev_fwd_mat_4_rayleigh(), set_reference_sph_mhd::chenge_temp_to_per_temp_sph(), gauss_integration::const_gauss_points_coefs(), construct_mhd_coefficient::construct_coefficient(), t_sph_component_fftw::copy_comp_fftw_to_send(), set_comm_table_prt_fftw::copy_prt_comp_fftw_to_send(), set_comm_table_prt_fftw::copy_prt_field_fftw_to_send(), set_comm_table_rtp_fftw::copy_rtp_comp_fftw_to_send(), set_comm_table_rtp_fftw::copy_rtp_field_fftw_to_send(), t_sph_single_fftw::copy_single_fftw_to_send(), fftw3_wrapper::fftw_forward_smp(), fftw3_multi_wrapper::fftw_mul_forward_smp(), normgi_by_primes::gs_prime(), t_fft_test_data::init_fft_test_data(), initial_magne_dynamobench::initial_b_dynamobench_1(), initial_magne_dynamobench::initial_b_dynamobench_2(), initial_magne_dbench_qvc::initial_b_dynamobench_qcv(), cal_inner_core_rotation::inner_core_coriolis_rj(), sum_coriolis_terms_rlm::inner_core_rot_z_coriolis_rlm(), interact_coriolis_rlm::interact_rot_coriolis_rlm(), normei::leades(), cal_sph_exp_1st_diff::normalize_sph_average_grad(), cal_gaunt_itgs::normki(), cvt_sph_tensor_2_cyl_smp::overwrite_cyl_tensor_by_sph_smp(), cvt_xyz_tensor_2_cyl_smp::overwrite_cyl_tensor_smp(), cvt_xyz_tensor_2_sph_smp::overwrite_sph_tensor_smp(), cvt_cyl_tensor_2_xyz_smp::overwrite_xyz_tensor_by_cyl_smp(), cvt_sph_tensor_2_xyz_smp::overwrite_xyz_tensor_by_sph_smp(), set_scalar_boundary_sph::poisson_in_fixed_flux_sph(), set_scalar_boundary_sph::poisson_out_fixed_flux_sph(), t_convert_from_rayleigh::rescaling_from_rayleigh(), schmidt_b_trans_at_center::schmidt_b_trans_center_vect(), schmidt::schmidt_legendre(), schmidt_fix_m::schmidt_legendre_m(), set_initial_sph_scalars::set_all_part_temp_sph(), set_cross_section_coefs::set_coefs_4_ellipsode(), set_cross_section_coefs::set_coefs_4_hyperboloide(), set_cross_section_coefs::set_coefs_4_parabolic(), set_cross_section_coefs::set_coefs_4_sphere(), set_comm_table_prt_fftw::set_comm_item_prt_4_fftw(), set_comm_table_rtp_fftw::set_comm_item_rtp_4_fftw(), const_sph_initial_spectr::set_initial_composition(), set_initial_sph_scalars::set_initial_light_sph(), set_initial_sph_dynamo::set_initial_magne_sph(), set_initial_sph_scalars::set_initial_temp_sph(), const_sph_initial_spectr::set_initial_temperature(), cal_inner_core_rotation::set_inner_core_rot_l1(), set_sph_local_node::set_local_nodes_sph_mesh(), set_node_on_edge_quad_psf::set_node_on_edge_4_quad_psf(), set_initial_sph_scalars::set_noize_scalar_sph(), set_reference_temp_sph::set_ref_temp_sph_mhd(), cal_inner_core_rotation::set_rotate_icb_vt_sph_mat(), spherical_harmonics::sph_normalizations(), sum_coriolis_terms_rlm::sum_r_coriolis_bc_rlm_10(), sum_rot_coriolis_terms_rlm::sum_rot_coriolis_lrm_10(), sum_rot_coriolis_terms_rlm::sum_rot_coriolis_rlm_10(), and set_reference_sph_mhd::transfer_per_temp_to_temp_sph().
zero
real(kind = kreal), parameter m_constants::zero = 0.0d0
Definition at line 16 of file m_constants.f90.
Referenced by const_sph_initial_spectr::add_inner_core_heat_source(), const_sph_initial_spectr::add_outer_core_heat_source(), center_sph_matrices::add_scalar_poisson_mat_fix_ctr(), center_sph_matrices::add_scalar_poisson_mat_no_fld(), const_sph_initial_spectr::add_whole_core_heat_source(), t_flex_delta_t_data::alloc_check_delta_t_data(), t_flex_delta_t_data::alloc_check_delta_t_rms(), t_circle_transform::alloc_circle_transform(), t_gaunt_coriolis_rlm::alloc_coriolis_coef_tri_rlm(), t_work_time::alloc_elapsed_timer(), t_psf_geometry_list::alloc_inod_psf(), t_read_sph_spectra::alloc_sph_spectr_data(), r_interpolate_sph_data::allocate_original_sph_data(), coef_fdm2_to_center::cal_2nd_center_fix_df_fdm(), coef_fdm2_to_center::cal_2nd_center_fixed_fdm(), coef_fdm2_to_center::cal_2nd_to_center_fixed_fdm(), volume_average_4_sph::cal_ave_vector_sph_spectr(), cal_circle_transform::cal_circle_spectrum_vector(), cal_fdm_coefs_4_boundaries::cal_fdm1_coef_fix_fld_cmb(), cal_fdm_coefs_4_boundaries::cal_fdm1_coef_fix_fld_icb(), coef_fdm2_free_cmb::cal_fdm2_cmb_free_vp(), coef_fdm2_free_cmb::cal_fdm2_cmb_free_vt(), cal_fdm_coefs_4_boundaries::cal_fdm2_coef_fix_df_cmb(), cal_fdm_coefs_4_boundaries::cal_fdm2_coef_fix_df_icb(), cal_fdm_coefs_4_boundaries::cal_fdm2_coef_fix_fld_cmb(), cal_fdm_coefs_4_boundaries::cal_fdm2_coef_fix_fld_icb(), coef_fdm2_free_icb::cal_fdm2_icb_free_vp(), coef_fdm2_free_icb::cal_fdm2_icb_free_vt(), field_at_mid_equator::cal_field_4_dynamobench(), interact_coriolis_rlm::cal_gaunt_coriolis_rlm(), mag_of_field_smp::cal_len_scale_by_diffuse_smp(), mag_of_field_smp::cal_len_scale_by_rot_smp(), mat_product_3band_mul::cal_mat_product_3band_mul(), poynting_flux_smp::cal_rtp_magnetic_streach_tmp(), cal_sph_exp_center::cal_sph_center1_grad22(), set_sph_exp_free_cmb::cal_sph_nod_cmb_free_v_and_w(), set_sph_exp_free_cmb::cal_sph_nod_cmb_free_vpol2(), cal_sph_exp_nod_cmb_ins::cal_sph_nod_cmb_ins_b_and_j(), cal_sph_exp_nod_cmb_ins::cal_sph_nod_cmb_ins_mag2(), cal_sph_exp_nod_cmb_ins::cal_sph_nod_cmb_ins_vp_rot2(), cal_sph_exp_nod_cmb_qvac::cal_sph_nod_cmb_qvc_b_and_j(), cal_sph_exp_nod_cmb_qvac::cal_sph_nod_cmb_qvc_mag2(), cal_sph_exp_nod_cmb_qvac::cal_sph_nod_cmb_qvc_vp_rot2(), set_sph_exp_rigid_cmb::cal_sph_nod_cmb_rigid_v_and_w(), set_sph_exp_rigid_cmb::cal_sph_nod_cmb_rigid_velo(), cal_sph_exp_1st_diff::cal_sph_nod_gradient_2(), set_sph_exp_free_icb::cal_sph_nod_icb_free_v_and_w(), set_sph_exp_free_icb::cal_sph_nod_icb_free_vpol2(), cal_sph_exp_nod_icb_ins::cal_sph_nod_icb_ins_b_and_j(), cal_sph_exp_nod_icb_ins::cal_sph_nod_icb_ins_mag2(), cal_sph_exp_nod_icb_ins::cal_sph_nod_icb_ins_vp_rot2(), cal_sph_exp_nod_icb_qvac::cal_sph_nod_icb_qvc_b_and_j(), cal_sph_exp_nod_icb_qvac::cal_sph_nod_icb_qvc_mag2(), cal_sph_exp_nod_icb_qvac::cal_sph_nod_icb_qvc_vp_rot2(), set_sph_exp_rigid_icb::cal_sph_nod_icb_rigid_velo2(), set_sph_exp_rigid_icb::cal_sph_nod_icb_rotate_velo2(), cal_sph_exp_nod_none_bc::cal_sph_nod_nobc_in_grad2(), cal_sph_exp_nod_none_bc::cal_sph_nod_nobc_out_grad2(), const_wz_coriolis_rtp::cal_wz_coriolis_pole(), const_wz_coriolis_rtp::cal_wz_coriolis_prt(), const_wz_coriolis_rtp::cal_wz_coriolis_rtp(), const_wz_coriolis_rtp::cal_wz_div_coriolis_prt(), const_wz_coriolis_rtp::cal_wz_div_coriolis_rtp(), single_pt_sph_mean_square::center_vector_mean_square(), check_sph_radial_mat::check_radial_3band_mat_w_ctr(), t_const_wz_coriolis_rtp::clear_rj_degree0_scalar_smp(), t_const_wz_coriolis_rtp::clear_rj_degree0_vector_smp(), t_field_on_circle::collect_spectr_for_circle(), gauss_integration::const_gauss_points_coefs(), radial_interpolation::const_radial_itp_table(), const_r_mat_4_vector_sph::const_radial_mat_4_magne_sph(), const_r_mat_4_scalar_sph::const_radial_mat_4_scalar_sph(), const_r_mat_4_vector_sph::const_radial_mat_vort_2step(), const_r_mat_w_center_sph::const_rmat_press00_sph(), const_r_mat_w_center_sph::const_rmat_scalar00_sph(), construct_mhd_coefficient::construct_coefficient(), t_sph_component_fftw::copy_comp_fftw_from_recv(), copy_pole_field_sph_trans::copy_pole_scalar_from_trans(), copy_pole_field_sph_trans::copy_pole_tensor_from_trans(), copy_pole_field_sph_trans::copy_pole_vector_from_trans(), cal_energy_flux_rj::copy_poloidal_to_streamfunc_rj(), set_comm_table_prt_fftw::copy_prt_fftw_comp_from_recv(), set_comm_table_prt_fftw::copy_prt_fftw_field_from_recv(), set_comm_table_rtp_fftw::copy_rtp_fftw_comp_from_recv(), set_comm_table_rtp_fftw::copy_rtp_fftw_field_from_recv(), t_sph_single_fftw::copy_single_fftw_from_recv(), t_time_data::copy_time_steps_from_restart(), center_sph_matrices::copy_to_band3_mat_w_center(), correlation_by_sph_spectr::correlate_each_vector_sph_spec(), set_node_for_sections::count_node_on_edge_4_psf(), zlib_cvt_ucd_data::defleate_ucd_vector(), zlib_cvt_vtk_data::defleate_vtk_scalar(), zlib_cvt_vtk_data::defleate_vtk_tensor(), zlib_cvt_vtk_data::defleate_vtk_vector(), single_pt_sph_mean_square::degree0_vector_mean_square(), cal_sph_mean_square::degree_zero_vector_mean_square(), delete_field_smp::delete_arb_vect_smp(), delete_field_smp::delete_scalar_smp(), delete_field_smp::delete_sym_tensor_smp(), delete_field_smp::delete_vector_smp(), set_reference_sph_mhd::delete_zero_degree_comp(), set_reference_sph_mhd::delete_zero_degree_vect(), schmidt::diff_schmidt_legendre(), schmidt_fix_m::diff_schmidt_legendre_m(), cal_sph_exp_fixed_scalar::dsdr_sph_fix_scalar_in_2(), cal_sph_exp_fixed_scalar::dsdr_sph_fix_scalar_out_2(), cal_sph_exp_fixed_flux::dsdr_sph_in_fix_flux_2(), cal_sph_exp_fixed_scalar::dsdr_sph_lm0_fix_scalar_in_2(), cal_sph_exp_fixed_scalar::dsdr_sph_lm0_fix_scalar_out_2(), cal_sph_exp_center::dsdr_sph_lm0_fixed_ctr_2(), cal_sph_exp_fixed_flux::dsdr_sph_lm0_in_fix_flux_2(), cal_sph_exp_fixed_flux::dsdr_sph_lm0_out_fix_flux_2(), cal_sph_exp_fixed_flux::dsdr_sph_out_fix_flux_2(), cal_sph_mean_square::each_vector_sph_spec(), extend_potential_field::ext_inside_potential(), extend_potential_field_t::ext_inside_potential_t(), extend_potential_field_t::ext_inside_potential_t_with_j(), extend_potential_field::ext_inside_potential_with_j(), extend_potential_field::ext_outside_potential(), extend_potential_field_t::ext_outside_potential_t(), extend_potential_field_t::ext_outside_potential_t_with_j(), extend_potential_field::ext_outside_potential_with_j(), fftw3_wrapper::fftw_backward_smp(), fftw3_multi_wrapper::fftw_mul_backward_smp(), cal_rms_fields_by_sph::find_radial_grid_index(), extend_potential_field::gauss_to_poloidal_in(), extend_potential_field_t::gauss_to_poloidal_in_t(), extend_potential_field::gauss_to_poloidal_out(), extend_potential_field_t::gauss_to_poloidal_out_t(), t_io_step_parameter::iflag_viz_flex_step(), initial_magne_dynamobench::initial_b_dynamobench_1(), initial_magne_dynamobench::initial_b_dynamobench_2(), initial_magne_dbench_qvc::initial_b_dynamobench_qcv(), sum_coriolis_terms_rlm::inner_core_rot_z_coriolis_rlm(), interact_coriolis_rlm::interact_rot_coriolis_rlm(), t_io_step_parameter::istep_file_w_flex_dt(), cal_gaunt_itgs::leadki(), cal_gaunt_itgs::leadli(), small_matmul_leg_trans_krin::matmul2_bwd_leg_trans_pjt(), small_matmul_leg_trans_krin::matmul4_bwd_leg_trans_pjt(), small_matmul_leg_trans_krin::matmul8_bwd_leg_trans_pjt(), matmul_for_legendre_trans::matmul_bwd_leg_trans(), matmul_for_legendre_trans::matmul_bwd_leg_trans_pjl(), matmul_for_legendre_trans::matmul_fwd_leg_trans(), matmul_for_legendre_trans::matmul_fwd_leg_trans_pjl(), set_reference_temp_sph::no_ref_temp_sph_mhd(), set_radius_func_noequi::nod_r_2nd_fdm_coef_noequi(), const_radial_4th_fdm_noequi::nod_r_4th_fdm_coef_noequi(), cal_sph_exp_1st_diff::normalize_sph_average_grad(), cal_gaunt_itgs::normki(), cal_gaunt_itgs::normli(), t_work_time::output_elapsed_log(), cal_ave_4_rms_vector_sph::pick_axis_sph_power(), cal_ave_4_rms_vector_sph::pick_axis_sph_vol_pwr(), cal_zonal_mean_sph_spectr::pick_del_degree_sph_spectr(), cal_zonal_mean_sph_spectr::pick_del_order_sph_spectr(), global_field_4_dynamobench::pick_inner_core_rotation(), global_field_4_dynamobench::pick_mag_torque_inner_core(), t_sph_transforms::pole_b_transform(), cal_buoyancy_flux_sph::pole_sph_buoyancy_flux(), products_at_poles::pole_sph_cross_prod_w_const(), products_at_poles::pole_sph_dot_prod_w_const(), products_at_poles::pole_vec_scalar_prod_w_const(), coordinate_converter::position_cyl_2_sph(), radial_interpolation::r_interpolate_sph_vector(), radial_int_for_sph_spec::radial_int_by_simpson(), radial_int_for_sph_spec::radial_int_by_trapezoid(), radial_int_for_sph_spec::radial_int_matrix_by_simpson(), radial_int_for_sph_spec::radial_int_matrix_by_trapezoid(), t_work_time::reset_elapsed_timer(), t_time_data::reset_time_data(), test_legendre_transforms::s_test_legendre_transforms(), schmidt_b_trans_at_center::schmidt_b_trans_center_vect(), schmidt_b_trans_at_pole::schmidt_b_trans_pole_scalar(), schmidt_b_trans_at_pole::schmidt_b_trans_pole_vect(), schmidt_fix_m::schmidt_legendre_m(), select_diff_adv_source::sel_ctr_scl_diff_adv_src_euler(), select_diff_adv_source::sel_scalar_diff_adv_src_euler(), t_field_on_circle::set_circle_point_global(), set_cross_section_coefs::set_coefs_4_ellipsode(), set_cross_section_coefs::set_coefs_4_hyperboloide(), set_cross_section_coefs::set_coefs_4_parabolic(), set_cross_section_coefs::set_coefs_4_plane(), set_cross_section_coefs::set_coefs_4_sphere(), set_control_4_force::set_control_4_coriolis_force(), t_flex_delta_t_parameter::set_control_flex_time_steps(), set_sph_scalar_mat_bc::set_fix_fld_cmb_poisson_mat(), set_sph_scalar_mat_bc::set_fix_fld_icb_poisson_mat(), construct_mhd_coefficient::set_implicit_4_inf_viscous(), set_control_4_model::set_implicit_coefs(), set_initial_sph_scalars::set_ini_reference_temp_sph(), const_sph_initial_spectr::set_initial_composition(), const_sph_initial_spectr::set_initial_heat_source_sph(), const_sph_initial_spectr::set_initial_light_source_sph(), set_initial_sph_scalars::set_initial_light_sph(), const_sph_initial_spectr::set_initial_magne_sph(), set_initial_sph_dynamo::set_initial_magne_sph(), const_sph_initial_spectr::set_initial_temperature(), set_initial_sph_dynamo::set_initial_velo_sph(), const_sph_initial_spectr::set_initial_velocity(), schmidt_poly_on_rtm_grid::set_lagender_pole_rlm(), set_sph_local_node::set_local_nodes_sph_mesh(), field_at_mid_equator::set_mid_equator_point_global(), set_node_for_sections::set_node_on_edge_4_psf(), set_node_on_edge_quad_psf::set_node_on_edge_4_quad_psf(), set_initial_sph_scalars::set_noize_scalar_sph(), m_section_coef_flags::set_parameter_2_vectors(), set_reference_temp_sph::set_ref_temp_sph_mhd(), set_reference_temp_sph::set_stratified_sph_mhd(), set_radial_mat_sph::set_unit_mat5_4_time_evo(), set_radial_mat_sph::set_unit_mat_4_poisson(), set_radial_mat_sph::set_unit_mat_4_time_evo(), normei::setei(), cal_sph_exp_center::sph0_scalar_fill_ctr_grad2(), t_sph_transforms::sph_b_trans_w_poles(), spherical_harmonics::sph_normalizations(), spherical_harmonics::spheric(), cal_diff_adv_src_explicit::stable_scalar_diffusion(), t_const_wz_coriolis_rtp::subtract_sphere_ave_coriolis(), sum_sph_rms_data::sum_sph_layerd_correlate(), sum_sph_rms_data::sum_sph_layerd_rms(), cal_energy_flux_rj::truncate_magnetic_field_4_view(), and mpi_picked_sph_spectr_io::write_picked_specr_data_mpi().