CALYPSO: cal_sph_field_by_rotation Module Reference
cal_sph_field_by_rotation Module Reference
Evaluate curl or divergence of forces.
Functions/Subroutines
subroutine rot_momentum_eq_exp_sph (sph_rj, r_2nd, sph_MHD_bc, leg, ipol_frc, ipol_rot_frc, rj_fld)
subroutine cal_rot_of_forces_sph_2 (sph_rj, r_2nd, g_sph_rj, sph_bc_U, fdm2_free_ICB, fdm2_free_CMB, ipol_frc, ipol_rot_frc, rj_fld)
subroutine cal_rot_of_induction_sph (sph_rj, r_2nd, g_sph_rj, sph_bc_B, ipol_frc, rj_fld)
subroutine cal_div_of_fluxes_sph (sph_rj, r_2nd, g_sph_rj, sph_bc_T, bcs_T, sph_bc_C, bcs_C, fdm2_center, ipol_frc, rj_fld)
Detailed Description
Evaluate curl or divergence of forces.
      subroutine rot_momentum_eq_exp_sph                              &
     &         (sph_rj, r_2nd, sph_MHD_bc, leg,                       &
     &          ipol_frc, ipol_rot_frc, rj_fld)
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(fdm_matrices), intent(in) :: r_2nd
        type(MHD_evolution_param), intent(in) :: MHD_prop
        type(sph_MHD_boundary_data), intent(in) :: sph_MHD_bc
        type(phys_address), intent(in) :: ipol
        type(base_force_address), intent(in) :: ipol_frc
        type(base_force_address), intent(in) :: ipol_rot_frc
        type(base_force_address), intent(in) :: ipol_div_frc
        type(phys_data), intent(inout) :: rj_fld
      subroutine cal_rot_of_forces_sph_2(sph_rj, r_2nd,               &
     &          g_sph_rj, sph_bc_U, fdm2_free_ICB, fdm2_free_CMB,     &
     &          ipol_frc, ipol_rot_frc, rj_fld)
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(fdm_matrices), intent(in) :: r_2nd
        type(base_force_address), intent(in) :: ipol_frc
        type(base_force_address), intent(in) :: ipol_rot_frc
        type(sph_boundary_type), intent(in)  :: sph_bc_U
        type(fdm2_free_slip), intent(in) :: fdm2_free_ICB
        type(fdm2_free_slip), intent(in) :: fdm2_free_CMB
        type(phys_data), intent(inout) :: rj_fld
      subroutine cal_rot_of_induction_sph                             &
     &         (sph_rj, r_2nd, g_sph_rj, sph_bc_B, ipol_frc, rj_fld)
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(fdm_matrices), intent(in) :: r_2nd
        type(base_force_address), intent(in) :: ipol_frc
        type(sph_boundary_type), intent(in) :: sph_bc_B
        type(phys_data), intent(inout) :: rj_fld
      subroutine cal_div_of_fluxes_sph(sph_rj, r_2nd, g_sph_rj,       &
     &          sph_bc_T, bcs_T, sph_bc_C, bcs_C, fdm2_center,        &
     &          ipol_frc, rj_fld)
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(fdm_matrices), intent(in) :: r_2nd
        type(base_force_address), intent(in) :: ipol_frc
        type(sph_boundary_type), intent(in) :: sph_bc_T, sph_bc_C
        type(sph_scalar_boundary_data), intent(in) :: bcs_T, bcs_C
        type(fdm2_center_mat), intent(in) :: fdm2_center
        type(phys_data), intent(inout) :: rj_fld
Function/Subroutine Documentation
cal_div_of_fluxes_sph()
subroutine cal_sph_field_by_rotation::cal_div_of_fluxes_sph (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, type(sph_boundary_type), intent(in) sph_bc_T, type(sph_scalar_boundary_data), intent(in) bcs_T, type(sph_boundary_type), intent(in) sph_bc_C, type(sph_scalar_boundary_data), intent(in) bcs_C, type(fdm2_center_mat), intent(in) fdm2_center, type(base_force_address), intent(in) ipol_frc, type(phys_data), intent(inout) rj_fld)
Definition at line 185 of file cal_sph_field_by_rotation.f90.
References const_sph_divergence::const_sph_scalar_advect(), and m_machine_parameter::iflag_debug.
Referenced by rot_momentum_eq_exp_sph().
cal_rot_of_forces_sph_2()
subroutine cal_sph_field_by_rotation::cal_rot_of_forces_sph_2 (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, type(sph_boundary_type), intent(in) sph_bc_U, type(fdm2_free_slip), intent(in) fdm2_free_ICB, type(fdm2_free_slip), intent(in) fdm2_free_CMB, type(base_force_address), intent(in) ipol_frc, type(base_force_address), intent(in) ipol_rot_frc, type(phys_data), intent(inout) rj_fld)
Definition at line 116 of file cal_sph_field_by_rotation.f90.
References const_sph_rotation::const_sph_force_rot2(), m_machine_parameter::iflag_debug, t_boundary_params_sph_mhd::iflag_rotatable_ic, and cal_inner_core_rotation::int_icore_toroidal_lorentz().
Referenced by rot_momentum_eq_exp_sph().
cal_rot_of_induction_sph()
subroutine cal_sph_field_by_rotation::cal_rot_of_induction_sph (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, type(sph_boundary_type), intent(in) sph_bc_B, type(base_force_address), intent(in) ipol_frc, type(phys_data), intent(inout) rj_fld)
Definition at line 160 of file cal_sph_field_by_rotation.f90.
References const_sph_rotation::const_sph_rotation_uxb(), and m_machine_parameter::iflag_debug.
Referenced by rot_momentum_eq_exp_sph().
rot_momentum_eq_exp_sph()
subroutine cal_sph_field_by_rotation::rot_momentum_eq_exp_sph (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_mhd_boundary_data), intent(in) sph_MHD_bc, type(legendre_4_sph_trans), intent(in) leg, type(base_force_address), intent(in) ipol_frc, type(base_force_address), intent(in) ipol_rot_frc, type(phys_data), intent(inout) rj_fld)
Definition at line 79 of file cal_sph_field_by_rotation.f90.
References cal_div_of_fluxes_sph(), cal_rot_of_forces_sph_2(), cal_rot_of_induction_sph(), m_machine_parameter::iflag_debug, and m_machine_parameter::iflag_routine_msg.
Referenced by cal_nonlinear::nonlinear_by_pseudo_sph().