CALYPSO: spherical_model_io Module Reference
spherical_model_io Module Reference
Data IO routines for spectrum data.
Functions/Subroutines
subroutine read_rank_4_sph (id_file, sph_IO)
subroutine read_gl_resolution_sph (id_file, sph_IO)
subroutine read_gl_nodes_sph (id_file, sph_IO)
subroutine write_rank_4_sph (id_file, sph_IO)
subroutine write_gl_resolution_sph (id_file, sph_IO)
subroutine write_gl_nodes_sph (id_file, sph_IO)
Variables
character(len=255), private character_4_read = ''
Detailed Description
Data IO routines for spectrum data.
      subroutine read_rank_4_sph(id_file, sph_IO)
      subroutine read_gl_resolution_sph(id_file, sph_IO)
      subroutine read_gl_nodes_sph(id_file, sph_IO)
        type(sph_IO_data), intent(inout) :: sph_IO
      subroutine write_rank_4_sph(id_file, sph_IO)
      subroutine write_gl_resolution_sph(id_file, sph_IO)
      subroutine write_gl_nodes_sph(id_file, sph_IO)
        type(sph_IO_data), intent(in) :: sph_IO
Function/Subroutine Documentation
read_gl_nodes_sph()
subroutine spherical_model_io::read_gl_nodes_sph (integer(kind = kint), intent(in) id_file, type(sph_io_data), intent(inout) sph_IO)
Definition at line 70 of file spherical_model_IO.f90.
References t_node_id_spherical_io::alloc_nod_id_sph_io(), character_4_read, and skip_comment_f::skip_comment().
Referenced by sph_modes_grids_data_io::read_geom_rtm_data(), sph_modes_grids_data_io::read_geom_rtp_data(), sph_modes_grids_data_io::read_spectr_modes_rj_data(), and sph_modes_grids_data_io::read_spectr_modes_rlm_data().
read_gl_resolution_sph()
subroutine spherical_model_io::read_gl_resolution_sph (integer(kind = kint), intent(in) id_file, type(sph_io_data), intent(inout) sph_IO)
Definition at line 53 of file spherical_model_IO.f90.
References character_4_read, and skip_comment_f::skip_comment().
Referenced by sph_modes_grids_data_io::read_geom_rtm_data(), sph_modes_grids_data_io::read_geom_rtp_data(), sph_modes_grids_data_io::read_spectr_modes_rj_data(), and sph_modes_grids_data_io::read_spectr_modes_rlm_data().
read_rank_4_sph()
subroutine spherical_model_io::read_rank_4_sph (integer(kind = kint), intent(in) id_file, type(sph_io_data), intent(inout) sph_IO)
Definition at line 38 of file spherical_model_IO.f90.
References character_4_read, and skip_comment_f::skip_comment().
Referenced by sph_modes_grids_data_io::read_geom_rtm_data(), sph_modes_grids_data_io::read_geom_rtp_data(), sph_modes_grids_data_io::read_spectr_modes_rj_data(), and sph_modes_grids_data_io::read_spectr_modes_rlm_data().
write_gl_nodes_sph()
subroutine spherical_model_io::write_gl_nodes_sph (integer(kind = kint), intent(in) id_file, type(sph_io_data), intent(in) sph_IO)
Definition at line 129 of file spherical_model_IO.f90.
Referenced by sph_modes_grids_data_io::write_geom_rtm_data(), sph_modes_grids_data_io::write_geom_rtp_data(), sph_modes_grids_data_io::write_modes_rlm_data(), and sph_modes_grids_data_io::write_spectr_modes_rj_data().
write_gl_resolution_sph()
subroutine spherical_model_io::write_gl_resolution_sph (integer(kind = kint), intent(in) id_file, type(sph_io_data), intent(in) sph_IO)
Definition at line 113 of file spherical_model_IO.f90.
References m_sph_modes_grid_labels::hd_trunc().
Referenced by sph_modes_grids_data_io::write_geom_rtm_data(), sph_modes_grids_data_io::write_geom_rtp_data(), sph_modes_grids_data_io::write_modes_rlm_data(), and sph_modes_grids_data_io::write_spectr_modes_rj_data().
write_rank_4_sph()
subroutine spherical_model_io::write_rank_4_sph (integer(kind = kint), intent(in) id_file, type(sph_io_data), intent(in) sph_IO)
Definition at line 98 of file spherical_model_IO.f90.
References m_sph_modes_grid_labels::hd_segment().
Referenced by sph_modes_grids_data_io::write_geom_rtm_data(), sph_modes_grids_data_io::write_geom_rtp_data(), sph_modes_grids_data_io::write_modes_rlm_data(), and sph_modes_grids_data_io::write_spectr_modes_rj_data().
Variable Documentation
character_4_read
character(len=255), private spherical_model_io::character_4_read = '' private
Definition at line 29 of file spherical_model_IO.f90.
Referenced by read_gl_nodes_sph(), read_gl_resolution_sph(), and read_rank_4_sph().