CALYPSO: sph_rtp_domain_fftpack5 Module Reference
sph_rtp_domain_fftpack5 Module Reference
Fourier transform using FFTPACK5.
Functions/Subroutines
subroutine init_rtp_domain_fftpack5 (sph_rtp, comm_rtp, fftpack_d)
subroutine verify_rtp_domain_fftpack5 (sph_rtp, comm_rtp, fftpack_d)
subroutine rtp_domain_rfftmf_to_send (sph_rtp, comm_rtp, ncomp_fwd, n_WS, X_rtp, WS, fftpack_d)
subroutine rtp_domain_rfftmb_from_recv (sph_rtp, comm_rtp, ncomp_bwd, n_WR, WR, X_rtp, fftpack_d)
Detailed Description
Fourier transform using FFTPACK5.
  ---------------------------------------------------------------------
      subroutine init_rtp_domain_FFTPACK5                             &
     &         (sph_rtp, comm_rtp, fftpack_d)
      subroutine verify_rtp_domain_FFTPACK5                           &
     &         (sph_rtp, comm_rtp, fftpack_d)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_comm_tbl), intent(in) :: comm_rtp
 ------------------------------------------------------------------
   wrapper subroutine for initierize FFT
 ------------------------------------------------------------------
      subroutine rtp_domain_RFFTMF_to_send(sph_rtp, comm_rtp,         &
     &          ncomp_fwd, n_WS, X_rtp, WS, fftpack_d)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_comm_tbl), intent(in) :: comm_rtp
 ------------------------------------------------------------------
 wrapper subroutine for forward Fourier transform by FFTPACK5
   a_{k} = \frac{2}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
          *  \cos (\frac{2\pi j k}{Nfft})
   b_{k} = \frac{2}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
          *  \cos (\frac{2\pi j k}{Nfft})
   a_{0} = \frac{1}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
    K = Nfft/2....
   a_{k} = \frac{1}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
          * \cos (\frac{2\pi j k}{Nfft})
 ------------------------------------------------------------------
      subroutine rtp_domain_RFFTMB_from_recv(sph_rtp, comm_rtp,       &
     &          ncomp_bwd, n_WR, WR, X_rtp, fftpack_d)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_comm_tbl), intent(in) :: comm_rtp
 ------------------------------------------------------------------
 wrapper subroutine for backward Fourier transform by FFTPACK5
   x_{k} = a_{0} + (-1)^{j} a_{Nfft/2} + sum_{k=1}^{Nfft/2-1}
          (a_{k} \cos(2\pijk/Nfft) + b_{k} \sin(2\pijk/Nfft))
 ------------------------------------------------------------------
       i = 1:     a_{0}
       i = 2:     a_{Nfft/2}
       i = 3:     a_{1}
       i = 4:     b_{1}
       ...
       i = 2*k+1: a_{k}
       i = 2*k+2: b_{k}
       ...
       i = Nfft-1:   a_{Nfft/2-1}
       i = Nfft:     b_{Nfft/2-1}
 ------------------------------------------------------------------
Parameters
Nsmp Number of SMP processors
Nstacksmp(0:Nsmp) End number for each SMP process
M Number of components for Fourier transforms
Nfft Data length for eadh FFT
X(M,Nfft) Data for Fourier transform
Function/Subroutine Documentation
init_rtp_domain_fftpack5()
subroutine sph_rtp_domain_fftpack5::init_rtp_domain_fftpack5 (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, type(work_for_domain_fftpack), intent(inout) fftpack_d)
Definition at line 96 of file sph_rtp_domain_FFTPACK5.f90.
References t_sph_comm_table_from_fft::alloc_comm_table_sph_fft(), t_sph_domain_fftpack5::init_sph_domain_fftpack5(), and set_comm_table_rtp_fftpack::set_comm_item_rtp_4_fftpack().
Referenced by t_sph_fft_selector::init_sph_fft_select().
rtp_domain_rfftmb_from_recv()
subroutine sph_rtp_domain_fftpack5::rtp_domain_rfftmb_from_recv (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(inout) WR, real(kind = kreal), dimension(sph_rtp%nnod_rtp,ncomp_bwd), intent(inout) X_rtp, type(work_for_domain_fftpack), intent(inout) fftpack_d)
Definition at line 208 of file sph_rtp_domain_FFTPACK5.f90.
References set_comm_table_rtp_fftpack::copy_fftpack_comp_from_recv(), copy_rtp_data_to_fftpack::copy_fftpack_to_rtp_comp(), m_elapsed_labels_sph_trns::iflag_fft_time, m_constants::ione, m_elapsed_labels_sph_trns::ist_elapsed_fft, m_machine_parameter::np_smp, and rfftmb().
Referenced by t_sph_fft_selector::back_fft_select_from_recv().
rtp_domain_rfftmf_to_send()
subroutine sph_rtp_domain_fftpack5::rtp_domain_rfftmf_to_send (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, integer(kind = kint), intent(in) ncomp_fwd, integer(kind = kint), intent(in) n_WS, real(kind = kreal), dimension(sph_rtp%nnod_rtp,ncomp_fwd), intent(in) X_rtp, real (kind=kreal), dimension(n_ws), intent(inout) WS, type(work_for_domain_fftpack), intent(inout) fftpack_d)
Definition at line 148 of file sph_rtp_domain_FFTPACK5.f90.
References t_sph_comm_table_from_fft::copy_1comp_rtp_fft_to_send_smp(), copy_rtp_data_to_fftpack::copy_fftpack_from_rtp_comp(), m_elapsed_labels_sph_trns::iflag_fft_time, m_constants::ione, m_elapsed_labels_sph_trns::ist_elapsed_fft, m_machine_parameter::np_smp, and rfftmf().
Referenced by t_sph_fft_selector::fwd_fft_select_to_send().
verify_rtp_domain_fftpack5()
subroutine sph_rtp_domain_fftpack5::verify_rtp_domain_fftpack5 (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, type(work_for_domain_fftpack), intent(inout) fftpack_d)
Definition at line 120 of file sph_rtp_domain_FFTPACK5.f90.
References t_sph_comm_table_from_fft::alloc_comm_table_sph_fft(), t_sph_comm_table_from_fft::dealloc_comm_table_sph_fft(), set_comm_table_rtp_fftpack::set_comm_item_rtp_4_fftpack(), and t_sph_domain_fftpack5::verify_sph_domain_fftpack5().
Referenced by t_sph_fft_selector::verify_sph_fft_select().