CALYPSO: input_control_dynamobench Module Reference
input_control_dynamobench Module Reference
Load mesh and filtering data for MHD simulation.
Functions/Subroutines
subroutine input_control_sph_dynamobench (MHD_files, bc_IO, DMHD_ctl, sph, comms_sph, sph_grps, rj_fld, nod_fld, MHD_step, MHD_prop, MHD_BC, SPH_WK, cdat, bench)
subroutine, private set_ctl_params_dynamobench (fld_ctl, meq_ctl, circle, d_circle, bench)
Variables
type(sph_grid_maker_in_sim), save, private sph_maker2
Structure to construct grid.
Detailed Description
Load mesh and filtering data for MHD simulation.
      subroutine input_control_SPH_dynamobench                        &
     &          (MHD_files, bc_IO, DMHD_ctl, sph, comms_sph, sph_grps,&
     &           rj_fld, nod_fld, MHD_step, MHD_prop, MHD_BC,         &
     &           SPH_WK, cdat, bench)
        type(MHD_file_IO_params), intent(inout) :: MHD_files
        type(sph_sgs_mhd_control), intent(inout) :: MHD_ctl
        type(DNS_mhd_simulation_control), intent(inout) :: DMHD_ctl
        type(sph_grids), intent(inout) :: sph
        type(sph_comm_tables), intent(inout) :: comms_sph
        type(sph_group_data), intent(inout) ::  sph_grps
        type(construct_spherical_grid), intent(inout) :: gen_sph1
        type(phys_data), intent(inout) :: rj_fld
        type(phys_data), intent(inout) :: nod_fld
        type(MHD_step_param), intent(inout) :: MHD_step
        type(MHD_evolution_param), intent(inout) :: MHD_prop
        type(MHD_BC_lists), intent(inout) :: MHD_BC
        type(work_SPH_MHD), intent(inout) :: SPH_WK
        type(circle_fld_maker), intent(inout) :: cdat
        type(dynamobench_monitor), intent(inout) :: bench
Function/Subroutine Documentation
input_control_sph_dynamobench()
subroutine input_control_dynamobench::input_control_sph_dynamobench (type(mhd_file_io_params), intent(inout) MHD_files, type(boundary_spectra), intent(inout) bc_IO, type(dns_mhd_simulation_control), intent(inout) DMHD_ctl, type(sph_grids), intent(inout) sph, type(sph_comm_tables), intent(inout) comms_sph, type(sph_group_data), intent(inout) sph_grps, type(phys_data), intent(inout) rj_fld, type(phys_data), intent(inout) nod_fld, type(mhd_step_param), intent(inout) MHD_step, type(mhd_evolution_param), intent(inout) MHD_prop, type(mhd_bc_lists), intent(inout) MHD_BC, type(work_sph_mhd), intent(inout) SPH_WK, type(circle_fld_maker), intent(inout) cdat, type(dynamobench_monitor), intent(inout) bench)
Definition at line 70 of file input_control_dynamobench.f90.
References t_ctl_data_mhd::dealloc_sph_mhd_ctl_data(), m_machine_parameter::iflag_debug, parallel_load_data_4_sph::load_sph_mesh(), set_control_sph_mhd::set_control_4_sph_mhd(), set_control_sph_mhd::set_control_sph_mhd_w_viz(), set_ctl_params_dynamobench(), parallel_load_data_4_sph::sph_index_flags_and_params(), and sph_maker2.
Referenced by analyzer_sph_dynamobench::initialize_sph_dynamobench().
set_ctl_params_dynamobench()
subroutine, private input_control_dynamobench::set_ctl_params_dynamobench (type(ctl_array_c3), intent(in) fld_ctl, type(mid_equator_control), intent(in) meq_ctl, type(fields_on_circle), intent(inout) circle, type(phys_data), intent(inout) d_circle, type(dynamobench_monitor), intent(inout) bench) private
Definition at line 126 of file input_control_dynamobench.f90.
References t_phys_data::alloc_phys_name_type(), t_circle_transform::iflag_circle_sph, m_base_field_labels::magnetic_field, m_phys_constants::n_scalar, m_phys_constants::n_vector, m_base_field_labels::temperature, and m_base_field_labels::velocity.
Referenced by input_control_sph_dynamobench().
Variable Documentation
sph_maker2
type(sph_grid_maker_in_sim), save, private input_control_dynamobench::sph_maker2 private
Structure to construct grid.
Definition at line 59 of file input_control_dynamobench.f90.
Referenced by input_control_sph_dynamobench().