CALYPSO: sph_analyzer_add_initial Module Reference
sph_analyzer_add_initial Module Reference
Main spectrum method loop to generate initial field
Initial field definision is in const_sph_initial_spectr.f90.
Functions/Subroutines
subroutine initialize_add_sph_initial
subroutine, private sph_add_initial_field (SPH_model, SPH_MHD)
Variables
character(len=kchara), parameter, private mhd_ctl_name = 'control_MHD'
File name for control file.
type(dns_mhd_simulation_control), save, private dns_mhd_ctl1
Control struture for MHD simulation.
type(sph_mesh_field_data), save, private sph_mhd1
Structure of spectr grid and data.
type(field_io), save, private rst_io1
Structure of restart IO data.
Detailed Description
Main spectrum method loop to generate initial field
Initial field definision is in const_sph_initial_spectr.f90.
      subroutine initialize_add_sph_initial
      subroutine SPH_add_initial_field
Function/Subroutine Documentation
initialize_add_sph_initial()
subroutine sph_analyzer_add_initial::initialize_add_sph_initial
Definition at line 53 of file SPH_analyzer_add_initial.f90.
References dns_mhd_ctl1, m_elapsed_labels_send_recv::elpsed_label_field_send_recv(), m_work_time::end_elapsed_time(), m_sph_mhd_model_data::fem_d1, m_work_time::ied_total_elapsed, m_machine_parameter::iflag_debug, m_elapsed_labels_4_mhd::iflag_mhd_time, m_work_time::iflag_tot_time, m_work_time::init_elapse_time_by_total(), input_control_sph_mhd::input_control_4_sph_make_init(), m_elapsed_labels_4_mhd::ist_elapsed_mhd, mhd_ctl_name, m_mhd_step_parameter::mhd_files1, m_mhd_step_parameter::mhd_step1, calypso_mpi::my_rank, t_ctl_data_sph_mhd_psf::read_control_4_sph_mhd_noviz(), init_sph_mhd_elapsed_label::reset_elapse_4_init_sph_mhd(), init_sph_mhd_elapsed_label::set_sph_mhd_elapsed_label(), sph_add_initial_field(), sph_mhd1, m_sph_mhd_model_data::sph_model1, m_sph_mhd_model_data::sph_wk1, and m_work_time::start_elapsed_time().
Referenced by sph_add_initial().
sph_add_initial_field()
subroutine, private sph_analyzer_add_initial::sph_add_initial_field (type(sph_mhd_model_data), intent(inout) SPH_model, type(sph_mesh_field_data), intent(inout) SPH_MHD) private
Definition at line 97 of file SPH_analyzer_add_initial.f90.
References m_work_time::end_elapsed_time(), m_work_time::ied_total_elapsed, m_machine_parameter::iflag_debug, m_work_time::iflag_tot_time, set_control_field_data::init_field_data(), init_radial_infos_sph_mhd::init_r_infos_sph_mhd(), m_mhd_step_parameter::mhd_files1, m_mhd_step_parameter::mhd_step1, sph_mhd_rst_io_control::read_alloc_sph_restart_data(), rst_io1, and const_sph_initial_spectr::sph_initial_spectrum().
Referenced by initialize_add_sph_initial().
Variable Documentation
dns_mhd_ctl1
type(dns_mhd_simulation_control), save, private sph_analyzer_add_initial::dns_mhd_ctl1 private
Control struture for MHD simulation.
Definition at line 37 of file SPH_analyzer_add_initial.f90.
Referenced by initialize_add_sph_initial().
mhd_ctl_name
character(len=kchara), parameter, private sph_analyzer_add_initial::mhd_ctl_name = 'control_MHD' private
File name for control file.
Definition at line 35 of file SPH_analyzer_add_initial.f90.
Referenced by initialize_add_sph_initial().
rst_io1
type(field_io), save, private sph_analyzer_add_initial::rst_io1 private
Structure of restart IO data.
Definition at line 43 of file SPH_analyzer_add_initial.f90.
Referenced by sph_add_initial_field().
sph_mhd1
type(sph_mesh_field_data), save, private sph_analyzer_add_initial::sph_mhd1 private
Structure of spectr grid and data.
Definition at line 41 of file SPH_analyzer_add_initial.f90.
Referenced by initialize_add_sph_initial().