CALYPSO: read_psf_binary_data Module Reference
read_psf_binary_data Module Reference
Output merged VTK file usgin MPI-IO.
Functions/Subroutines
subroutine read_psf_phys_num_bin (nprocs, nnod, num_field, itmp1_mp, bbuf)
subroutine read_psf_phys_name_bin (num_field, ntot_comp, ncomp_field, field_name, bbuf)
subroutine read_psf_phys_data_bin (nprocs, nnod, ntot_comp, d_nod, itmp1_mp, bbuf)
subroutine read_psf_node_num_bin (nprocs, nnod, itmp1_mp, bbuf)
subroutine read_psf_node_data_bin (nprocs, nnod, inod_global, xx, itmp1_mp, bbuf)
subroutine read_psf_ele_num_bin (nprocs, nele, nnod_ele, itmp1_mp, bbuf)
subroutine read_psf_ele_connect_bin (nprocs, nele, nnod_ele, iele_global, ie_psf, itmp1_mp, bbuf)
Detailed Description
Output merged VTK file usgin MPI-IO.
      subroutine read_psf_phys_num_bin                                &
     &         (nprocs, nnod, num_field, itmp1_mp, bbuf)
      subroutine read_psf_phys_name_bin                               &
     &         (num_field, ntot_comp, ncomp_field, field_name, bbuf)
      subroutine read_psf_phys_data_bin                               &
     &         (nprocs, nnod, ntot_comp, d_nod, itmp1_mp, bbuf)
      subroutine read_psf_node_num_bin(nprocs, nnod, itmp1_mp, bbuf)
      subroutine read_psf_node_data_bin                               &
     &         (nprocs, nnod, inod_global, xx, itmp1_mp, bbuf)
      subroutine read_psf_ele_num_bin                                 &
     &         (nprocs, nele, nnod_ele, itmp1_mp, bbuf)
      subroutine read_psf_ele_connect_bin                             &
     &         (nprocs, nele, nnod_ele, iele_global, ie_psf,          &
     &          itmp1_mp, bbuf)
        type(binary_IO_buffer), intent(inout) :: bbuf
Function/Subroutine Documentation
read_psf_ele_connect_bin()
subroutine read_psf_binary_data::read_psf_ele_connect_bin (integer, intent(in) nprocs, integer(kind = kint_gl), intent(in) nele, integer(kind = kint), intent(in) nnod_ele, integer(kind = kint_gl), dimension(nele), intent(inout) iele_global, integer(kind = kint_gl), dimension(nele,nnod_ele), intent(inout) ie_psf, integer(kind = kint_gl), dimension(nprocs), intent(inout) itmp1_mp, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 207 of file read_psf_binary_data.f90.
References transfer_to_long_integers::cast_long(), and binary_io::read_mul_int8_b().
Referenced by read_udt_from_bindary_data::read_alloc_psf_bin_grid_data(), and read_udt_from_bindary_data::read_psf_bin_grid_data().
read_psf_ele_num_bin()
subroutine read_psf_binary_data::read_psf_ele_num_bin (integer, intent(in) nprocs, integer(kind = kint_gl), intent(inout) nele, integer(kind = kint), intent(inout) nnod_ele, integer(kind = kint_gl), dimension(nprocs), intent(inout) itmp1_mp, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 170 of file read_psf_binary_data.f90.
References transfer_to_long_integers::cast_long(), m_constants::ione, and binary_io::read_mul_int8_b().
Referenced by read_udt_from_bindary_data::read_alloc_psf_bin_grid_data(), and read_udt_from_bindary_data::read_psf_bin_grid_data().
read_psf_node_data_bin()
subroutine read_psf_binary_data::read_psf_node_data_bin (integer, intent(in) nprocs, integer(kind=kint_gl), intent(in) nnod, integer(kind=kint_gl), dimension(nnod), intent(inout) inod_global, real(kind = kreal), dimension(nnod,3), intent(inout) xx, integer(kind = kint_gl), dimension(nprocs), intent(inout) itmp1_mp, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 143 of file read_psf_binary_data.f90.
References m_constants::ithree, and read_psf_phys_data_bin().
Referenced by read_udt_from_bindary_data::read_alloc_psf_bin_grid_data(), and read_udt_from_bindary_data::read_psf_bin_grid_data().
read_psf_node_num_bin()
subroutine read_psf_binary_data::read_psf_node_num_bin (integer, intent(in) nprocs, integer(kind=kint_gl), intent(inout) nnod, integer(kind = kint_gl), dimension(nprocs), intent(inout) itmp1_mp, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 117 of file read_psf_binary_data.f90.
References transfer_to_long_integers::cast_long(), and binary_io::read_mul_int8_b().
Referenced by read_udt_from_bindary_data::read_alloc_psf_bin_grid_data(), read_udt_from_bindary_data::read_psf_bin_grid_data(), and read_psf_phys_num_bin().
read_psf_phys_data_bin()
subroutine read_psf_binary_data::read_psf_phys_data_bin (integer, intent(in) nprocs, integer(kind=kint_gl), intent(in) nnod, integer(kind=kint), intent(in) ntot_comp, real(kind = kreal), dimension(nnod,ntot_comp), intent(inout) d_nod, integer(kind = kint_gl), dimension(nprocs), intent(inout) itmp1_mp, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 90 of file read_psf_binary_data.f90.
References transfer_to_long_integers::cast_long(), binary_io::read_1d_vector_b(), and binary_io::read_mul_int8_b().
Referenced by read_udt_from_bindary_data::read_alloc_psf_bin_field_data(), read_udt_from_bindary_data::read_psf_bin_field_data(), and read_psf_node_data_bin().
read_psf_phys_name_bin()
subroutine read_psf_binary_data::read_psf_phys_name_bin (integer(kind=kint), intent(in) num_field, integer(kind=kint), intent(inout) ntot_comp, integer(kind=kint), dimension(num_field), intent(inout) ncomp_field, character(len=kchara), dimension(num_field), intent(inout) field_name, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 68 of file read_psf_binary_data.f90.
References transfer_to_long_integers::cast_long(), binary_io::read_mul_character_b(), and binary_io::read_mul_integer_b().
Referenced by read_udt_from_bindary_data::read_alloc_psf_bin_field_data(), and read_udt_from_bindary_data::read_psf_bin_field_data().
read_psf_phys_num_bin()
subroutine read_psf_binary_data::read_psf_phys_num_bin (integer, intent(in) nprocs, integer(kind=kint_gl), intent(in) nnod, integer(kind=kint), intent(inout) num_field, integer(kind = kint_gl), dimension(nprocs), intent(inout) itmp1_mp, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 44 of file read_psf_binary_data.f90.
References binary_io::read_one_integer_b(), and read_psf_node_num_bin().
Referenced by read_udt_from_bindary_data::read_alloc_psf_bin_field_data(), and read_udt_from_bindary_data::read_psf_bin_field_data().