CALYPSO: /home/takumi kera/calypso/src/External_libs/FFTPACK5.1D/fftpack5.1_prb.f90 File Reference
fftpack5.1_prb.f90 File Reference
Functions/Subroutines
program main
subroutine test01 ()
subroutine test02 ()
subroutine test03 ()
subroutine test04 ()
subroutine test05 ()
subroutine test06 ()
subroutine test07 ()
subroutine test09 ()
subroutine test10 ()
subroutine test11 ()
subroutine test12 ()
subroutine test13 ()
subroutine test14 ()
subroutine test15 ()
subroutine c4mat_print_some (m, n, a, ilo, jlo, ihi, jhi, title)
subroutine c4mat_uniform_01 (m, n, seed, c)
subroutine c4vec_print_part (n, a, max_print, title)
subroutine c4vec_uniform_01 (n, seed, c)
subroutine r4mat_print (m, n, a, title)
subroutine r4mat_print_some (m, n, a, ilo, jlo, ihi, jhi, title)
subroutine r4mat_uniform_01 (m, n, seed, r)
subroutine r4vec_print_part (n, a, max_print, title)
subroutine r4vec_uniform_01 (n, seed, r)
subroutine timestamp ()
Function/Subroutine Documentation
c4mat_print_some()
subroutine c4mat_print_some (integer (kind = 4) m, integer (kind = 4) n, complex (kind = 4), dimension(m,n) a, integer (kind = 4) ilo, integer (kind = 4) jlo, integer (kind = 4) ihi, integer (kind = 4) jhi, character (len = *) title)
Definition at line 1291 of file fftpack5.1_prb.f90.
Referenced by test02(), and test03().
c4mat_uniform_01()
subroutine c4mat_uniform_01 (integer (kind = 4) m, integer (kind = 4) n, integer (kind = 4) seed, complex (kind = 4), dimension(m,n) c)
Definition at line 1411 of file fftpack5.1_prb.f90.
Referenced by test02(), and test03().
c4vec_print_part()
subroutine c4vec_print_part (integer (kind = 4) n, complex (kind = 4), dimension(n) a, integer (kind = 4) max_print, character (len = *) title)
Definition at line 1494 of file fftpack5.1_prb.f90.
Referenced by test01().
c4vec_uniform_01()
subroutine c4vec_uniform_01 (integer (kind = 4) n, integer (kind = 4) seed, complex (kind = 4), dimension(n) c)
Definition at line 1583 of file fftpack5.1_prb.f90.
Referenced by test01().
main()
program main
Definition at line 1 of file fftpack5.1_prb.f90.
References test01(), test02(), test03(), test04(), test05(), test06(), test07(), test09(), test10(), test11(), test12(), test13(), test14(), test15(), and timestamp().
r4mat_print()
subroutine r4mat_print (integer (kind = 4) m, integer (kind = 4) n, real (kind = 4), dimension(m,n) a, character (len = *) title)
Definition at line 1660 of file fftpack5.1_prb.f90.
References r4mat_print_some().
r4mat_print_some()
subroutine r4mat_print_some (integer (kind = 4) m, integer (kind = 4) n, real (kind = 4), dimension(m,n) a, integer (kind = 4) ilo, integer (kind = 4) jlo, integer (kind = 4) ihi, integer (kind = 4) jhi, character (len = *) title)
Definition at line 1704 of file fftpack5.1_prb.f90.
Referenced by r4mat_print(), test05(), test07(), test10(), test11(), test13(), and test15().
r4mat_uniform_01()
subroutine r4mat_uniform_01 (integer (kind = 4) m, integer (kind = 4) n, integer (kind = 4) seed, real (kind = 4), dimension(m,n) r)
Definition at line 1807 of file fftpack5.1_prb.f90.
Referenced by test05(), test07(), test10(), test11(), test13(), and test15().
r4vec_print_part()
subroutine r4vec_print_part (integer (kind = 4) n, real (kind = 4), dimension(n) a, integer (kind = 4) max_print, character (len = *) title)
Definition at line 1888 of file fftpack5.1_prb.f90.
Referenced by test04(), test06(), test09(), test12(), and test14().
r4vec_uniform_01()
subroutine r4vec_uniform_01 (integer (kind = 4) n, integer (kind = 4) seed, real (kind = 4), dimension(n) r)
Definition at line 1976 of file fftpack5.1_prb.f90.
Referenced by test04(), test06(), test09(), test12(), and test14().
test01()
subroutine test01
Definition at line 55 of file fftpack5.1_prb.f90.
References c4vec_print_part(), c4vec_uniform_01(), cfft1b(), cfft1f(), and cfft1i().
Referenced by main().
test02()
subroutine test02
Definition at line 138 of file fftpack5.1_prb.f90.
References c4mat_print_some(), c4mat_uniform_01(), cfft2b(), cfft2f(), and cfft2i().
Referenced by main().
test03()
subroutine test03
Definition at line 227 of file fftpack5.1_prb.f90.
References c4mat_print_some(), c4mat_uniform_01(), cfftmb(), cfftmf(), and cfftmi().
Referenced by main().
test04()
subroutine test04
Definition at line 320 of file fftpack5.1_prb.f90.
References cosq1b(), cosq1f(), cosq1i(), r4vec_print_part(), and r4vec_uniform_01().
Referenced by main().
test05()
subroutine test05
Definition at line 403 of file fftpack5.1_prb.f90.
References cosqmb(), cosqmf(), cosqmi(), r4mat_print_some(), and r4mat_uniform_01().
Referenced by main().
test06()
subroutine test06
Definition at line 496 of file fftpack5.1_prb.f90.
References cost1b(), cost1f(), cost1i(), r4vec_print_part(), and r4vec_uniform_01().
Referenced by main().
test07()
subroutine test07
Definition at line 578 of file fftpack5.1_prb.f90.
References costmb(), costmf(), costmi(), r4mat_print_some(), and r4mat_uniform_01().
Referenced by main().
test09()
subroutine test09
Definition at line 671 of file fftpack5.1_prb.f90.
References r4vec_print_part(), r4vec_uniform_01(), rfft1b(), rfft1f(), and rfft1i().
Referenced by main().
test10()
subroutine test10
Definition at line 754 of file fftpack5.1_prb.f90.
References r4mat_print_some(), r4mat_uniform_01(), rfft2b(), rfft2f(), and rfft2i().
Referenced by main().
test11()
subroutine test11
Definition at line 845 of file fftpack5.1_prb.f90.
References r4mat_print_some(), r4mat_uniform_01(), rfftmb(), rfftmf(), and rfftmi().
Referenced by main().
test12()
subroutine test12
Definition at line 937 of file fftpack5.1_prb.f90.
References r4vec_print_part(), r4vec_uniform_01(), sinq1b(), sinq1f(), and sinq1i().
Referenced by main().
test13()
subroutine test13
Definition at line 1020 of file fftpack5.1_prb.f90.
References r4mat_print_some(), r4mat_uniform_01(), sinqmb(), sinqmf(), and sinqmi().
Referenced by main().
test14()
subroutine test14
Definition at line 1113 of file fftpack5.1_prb.f90.
References r4vec_print_part(), r4vec_uniform_01(), sint1b(), sint1f(), and sint1i().
Referenced by main().
test15()
subroutine test15
Definition at line 1196 of file fftpack5.1_prb.f90.
References r4mat_print_some(), r4mat_uniform_01(), sintmb(), sintmf(), and sintmi().
Referenced by main().
timestamp()
subroutine timestamp
Definition at line 2070 of file fftpack5.1_prb.f90.
Referenced by main().