CALYPSO: m_default_file_prefix Module Reference
m_default_file_prefix Module Reference
List of default file prefixes.
Variables
character(len=kchara), parameter def_mesh_file_head = 'mesh/in'
Mesh file.
character(len=kchara), parameter def_ele_mesh_head = 'mesh/element'
Element mesh file.
character(len=kchara), parameter def_surf_mesh_head = 'mesh/surface'
Surface mesh file.
character(len=kchara), parameter def_edge_mesh_head = 'mesh/edge'
Edge mesh file.
character(len=kchara), parameter def_sph_mesh_head = 'mesh/node_sph'
Node file in spherical coordinate.
character(len=kchara), parameter def_cyl_mesh_head = 'mesh/node_cyl'
Node file in Cylindrical coordinate.
character(len=kchara), parameter def_org_mesh_head = 'mesh_org/in'
Mesh file.
character(len=kchara) def_org_sph_rj_head = "sph_org/in_rj"
file header for original spectrum indexing data
character(len=kchara) def_org_ucd_header = "field_org/out"
file header for original field data
character(len=kchara) def_org_rst_header = "rst_org/rst"
file header for original restart data
character(len=kchara), parameter def_new_mesh_head = 'mesh_target/in'
file header for new mesh data
Detailed Description
List of default file prefixes.
Variable Documentation
def_cyl_mesh_head
character(len=kchara), parameter m_default_file_prefix::def_cyl_mesh_head = 'mesh/node_cyl'
Node file in Cylindrical coordinate.
Definition at line 32 of file m_default_file_prefix.f90.
def_edge_mesh_head
character(len=kchara), parameter m_default_file_prefix::def_edge_mesh_head = 'mesh/edge'
Edge mesh file.
Definition at line 25 of file m_default_file_prefix.f90.
def_ele_mesh_head
character(len=kchara), parameter m_default_file_prefix::def_ele_mesh_head = 'mesh/element'
Element mesh file.
Definition at line 19 of file m_default_file_prefix.f90.
def_mesh_file_head
character(len=kchara), parameter m_default_file_prefix::def_mesh_file_head = 'mesh/in'
Mesh file.
Definition at line 16 of file m_default_file_prefix.f90.
Referenced by set_control_platform_data::set_control_mesh_def().
def_new_mesh_head
character(len=kchara), parameter m_default_file_prefix::def_new_mesh_head = 'mesh_target/in'
file header for new mesh data
Definition at line 46 of file m_default_file_prefix.f90.
def_org_mesh_head
character(len=kchara), parameter m_default_file_prefix::def_org_mesh_head = 'mesh_org/in'
Mesh file.
Definition at line 36 of file m_default_file_prefix.f90.
def_org_rst_header
character(len=kchara) m_default_file_prefix::def_org_rst_header = "rst_org/rst"
file header for original restart data
Definition at line 43 of file m_default_file_prefix.f90.
Referenced by t_mhd_file_parameter::set_control_org_sph_files().
def_org_sph_rj_head
character(len=kchara) m_default_file_prefix::def_org_sph_rj_head = "sph_org/in_rj"
file header for original spectrum indexing data
Definition at line 39 of file m_default_file_prefix.f90.
Referenced by t_mhd_file_parameter::set_control_org_sph_files().
def_org_ucd_header
character(len=kchara) m_default_file_prefix::def_org_ucd_header = "field_org/out"
file header for original field data
Definition at line 41 of file m_default_file_prefix.f90.
def_sph_mesh_head
character(len=kchara), parameter m_default_file_prefix::def_sph_mesh_head = 'mesh/node_sph'
Node file in spherical coordinate.
Definition at line 29 of file m_default_file_prefix.f90.
def_surf_mesh_head
character(len=kchara), parameter m_default_file_prefix::def_surf_mesh_head = 'mesh/surface'
Surface mesh file.
Definition at line 22 of file m_default_file_prefix.f90.