CALYPSO: fftw3_multi_wrapper Module Reference
fftw3_multi_wrapper Module Reference
Fourier transform using FFTW Ver.3.
Functions/Subroutines
subroutine init_4_fftw_mul_smp (Nsmp, Nstacksmp, Ncomp, Nfft, plan_forward_smp, plan_backward_smp, aNfft, X_FFTW, C_FFTW)
subroutine destroy_fftw_mul_smp (Nsmp, plan_forward, plan_backward)
subroutine fftw_mul_forward_smp (plan_forward_smp, Nsmp, Nstacksmp, Ncomp, Nfft, aNfft, X, X_FFTW, C_FFTW)
subroutine fftw_mul_backward_smp (plan_backward_smp, Nsmp, Nstacksmp, Ncomp, Nfft, X, X_FFTW, C_FFTW)
Variables
real(kind=kreal), dimension(3) elapsed_fftw = (/0.0,0.0,0.0/)
integer, parameter, private ione_4 = 1
integer, parameter, private inembed = 0
integer, parameter, private istride = 1
Detailed Description
Fourier transform using FFTW Ver.3.
 ------------------------------------------------------------------
      subroutine init_4_FFTW_mul_smp(Nsmp, Nstacksmp, Ncomp, Nfft,    &
     &          plan_forward_smp, plan_backward_smp,                  &
     &          aNfft, X_FFTW, C_FFTW)
   wrapper subroutine for initierize FFTW plans
 ------------------------------------------------------------------
      subroutine destroy_FFTW_mul_smp                                 &
     &         (Nsmp, plan_backward_smp, plan_backward)
        CAUTION!!  dfftw_destroy_plan oftern makes SEGMENTAION FAULT!!
   wrapper subroutine for clear FFTW plans
 ------------------------------------------------------------------
      subroutine FFTW_mul_forward_SMP(plan_forward_smp,               &
     &          Nsmp, Nstacksmp, Ncomp, Nfft, aNfft, X, X_FFTW, C_FFTW)
 ------------------------------------------------------------------
 wrapper subroutine for forward Fourier transform by FFTW3
   a_{k} = \frac{2}{Nfft} \sum_{j=0}^{Nfft-1} x_{j} \cos (\frac{2\pi j k}{Nfft})
   b_{k} = \frac{2}{Nfft} \sum_{j=0}^{Nfft-1} x_{j} \cos (\frac{2\pi j k}{Nfft})
   a_{0} = \frac{1}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
    K = Nfft/2....
   a_{k} = \frac{1}{Nfft} \sum_{j=0}^{Nfft-1} x_{j} \cos (\frac{2\pi j k}{Nfft})
 ------------------------------------------------------------------
      subroutine FFTW_mul_backward_SMP(plan_backward_smp,             &
     &          Nsmp, Nstacksmp, Ncomp, Nfft, X, X_FFTW, C_FFTW)
 ------------------------------------------------------------------
 wrapper subroutine for backward Fourier transform by FFTW3
   x_{k} = a_{0} + (-1)^{j} a_{Nfft/2} + sum_{k=1}^{Nfft/2-1}
          (a_{k} \cos(2\pijk/Nfft) + b_{k} \sin(2\pijk/Nfft))
 ------------------------------------------------------------------
       i = 1:     a_{0}
       i = 2:     a_{Nfft/2}
       i = 3:     a_{1}
       i = 4:     b_{1}
       ...
       i = 2*k+1: a_{k}
       i = 2*k+2: b_{k}
       ...
       i = Nfft-1:   a_{Nfft/2-1}
       i = Nfft:     b_{Nfft/2-1}
 ------------------------------------------------------------------
Parameters
Nsmp Number of SMP processors
Nstacksmp(0:Nsmp) End number for each SMP process
Ncomp Number of components for Fourier transforms
Nfft Data length for eadh FFT
X(Ncomp,Nfft) Data for Fourier transform
Parameters
plan_forward FFTW plan for forward transform
plan_backward FFTW plan for backward transform
aNfft normalization parameter for FFTW (= 1 / Nfft)
X_FFTW real data for multiple Fourier transform
C_FFTW spectrum data for multiple Fourier transform
Function/Subroutine Documentation
destroy_fftw_mul_smp()
subroutine fftw3_multi_wrapper::destroy_fftw_mul_smp (integer(kind = kint), intent(in) Nsmp, integer(kind = fftw_plan), dimension(nsmp), intent(in) plan_forward, integer(kind = fftw_plan), dimension(nsmp), intent(in) plan_backward)
Definition at line 141 of file FFTW3_multi_wrapper.F90.
Referenced by t_multi_fftw_wrapper::finalize_fftw_mul_type().
fftw_mul_backward_smp()
subroutine fftw3_multi_wrapper::fftw_mul_backward_smp (integer(kind = fftw_plan), dimension(nsmp), intent(in) plan_backward_smp, integer(kind = kint), intent(in) Nsmp, integer(kind = kint), dimension(0:nsmp), intent(in) Nstacksmp, integer(kind = kint), intent(in) Ncomp, integer(kind = kint), intent(in) Nfft, real(kind = kreal), dimension(ncomp,nfft), intent(inout) X, real(kind = kreal), dimension(nfft,ncomp), intent(inout) X_FFTW, complex(kind = fftw_complex), dimension(nfft/2+1,ncomp), intent(inout) C_FFTW)
Definition at line 226 of file FFTW3_multi_wrapper.F90.
References m_constants::half, and m_constants::zero.
Referenced by t_multi_fftw_wrapper::fftw_mul_backward_type().
fftw_mul_forward_smp()
subroutine fftw3_multi_wrapper::fftw_mul_forward_smp (integer(kind = fftw_plan), dimension(nsmp), intent(in) plan_forward_smp, integer(kind = kint), intent(in) Nsmp, integer(kind = kint), dimension(0:nsmp), intent(in) Nstacksmp, integer(kind = kint), intent(in) Ncomp, integer(kind = kint), intent(in) Nfft, real(kind = kreal), intent(in) aNfft, real(kind = kreal), dimension(ncomp, nfft), intent(inout) X, real(kind = kreal), dimension(nfft,ncomp), intent(inout) X_FFTW, complex(kind = fftw_complex), dimension(nfft/2+1,ncomp), intent(inout) C_FFTW)
Definition at line 162 of file FFTW3_multi_wrapper.F90.
References m_fftw_parameters::iu, and m_constants::two.
Referenced by t_multi_fftw_wrapper::fftw_mul_forward_type().
init_4_fftw_mul_smp()
subroutine fftw3_multi_wrapper::init_4_fftw_mul_smp (integer(kind = kint), intent(in) Nsmp, integer(kind = kint), dimension(0:nsmp), intent(in) Nstacksmp, integer(kind = kint), intent(in) Ncomp, integer(kind = kint), intent(in) Nfft, integer(kind = fftw_plan), dimension(nsmp), intent(inout) plan_forward_smp, integer(kind = fftw_plan), dimension(nsmp), intent(inout) plan_backward_smp, real(kind = kreal), intent(inout) aNfft, real(kind = kreal), dimension(nfft,ncomp), intent(inout) X_FFTW, complex(kind = fftw_complex), dimension(nfft/2+1,ncomp), intent(inout) C_FFTW)
Definition at line 99 of file FFTW3_multi_wrapper.F90.
References m_fftw_parameters::fftw_estimate, inembed, ione_4, istride, and m_constants::one.
Referenced by t_multi_fftw_wrapper::init_fftw_mul_type().
Variable Documentation
elapsed_fftw
real(kind = kreal), dimension(3) fftw3_multi_wrapper::elapsed_fftw = (/0.0,0.0,0.0/)
Definition at line 85 of file FFTW3_multi_wrapper.F90.
inembed
integer, parameter, private fftw3_multi_wrapper::inembed = 0 private
Definition at line 88 of file FFTW3_multi_wrapper.F90.
Referenced by init_4_fftw_mul_smp().
ione_4
integer, parameter, private fftw3_multi_wrapper::ione_4 = 1 private
Definition at line 87 of file FFTW3_multi_wrapper.F90.
Referenced by init_4_fftw_mul_smp().
istride
integer, parameter, private fftw3_multi_wrapper::istride = 1 private
Definition at line 89 of file FFTW3_multi_wrapper.F90.
Referenced by init_4_fftw_mul_smp().