CALYPSO: parallel_assemble_sph Module Reference
parallel_assemble_sph Module Reference
Construct spectrum data for new spectrum domain.
Data Types
type rj_assemble_tbl
Functions/Subroutines
subroutine alloc_each_mode_tbl_4_assemble (org_sph, j_table)
subroutine dealloc_mode_table_4_assemble (j_table)
subroutine set_mode_table_4_assemble (org_sph, new_sph, j_table)
subroutine copy_field_data_sph_assemble (org_sph, new_sph, j_table, ntot_phys_rj, d_rj_org, d_rj)
subroutine copy_field_data_sph_center (org_sph, new_sph, j_table, ntot_phys_rj, d_rj_org, d_rj)
subroutine r_itp_field_data_sph_assemble (org_sph, new_sph, r_itp, j_table, ntot_phys_rj, d_rj_org, d_rj_new)
Detailed Description
Construct spectrum data for new spectrum domain.
      subroutine alloc_each_mode_tbl_4_assemble(org_sph, j_table)
      subroutine dealloc_mode_table_4_assemble(j_table)
      subroutine set_mode_table_4_assemble(org_sph, new_sph, j_table)
      subroutine copy_field_data_sph_assemble(org_sph, new_sph,       &
     &          j_table, ntot_phys_rj, d_rj_org, d_rj_tmp)
      subroutine r_itp_field_data_sph_assemble(org_sph, new_sph,      &
     &          r_itp, j_table, ntot_phys_rj, d_rj_org, d_rj_new)
      subroutine copy_field_data_sph_center(org_sph, new_sph, j_table,&
     &          ntot_phys_rj, d_rj_org, d_rj)
Parameters
istep TIme step number
Function/Subroutine Documentation
alloc_each_mode_tbl_4_assemble()
subroutine parallel_assemble_sph::alloc_each_mode_tbl_4_assemble (type(sph_grids), intent(in) org_sph, type(rj_assemble_tbl), intent(inout) j_table)
Definition at line 43 of file parallel_assemble_sph.f90.
Referenced by assemble_sph_fields::load_new_spectr_rj_data().
copy_field_data_sph_assemble()
subroutine parallel_assemble_sph::copy_field_data_sph_assemble (type(sph_grids), intent(in) org_sph, type(sph_grids), intent(in) new_sph, type(rj_assemble_tbl), intent(in) j_table, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(org_sph%sph_rj%nnod_rj,ntot_phys_rj), intent(in) d_rj_org, real(kind = kreal), dimension(new_sph%sph_rj%nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 110 of file parallel_assemble_sph.f90.
Referenced by new_sph_restart::set_assembled_sph_data().
copy_field_data_sph_center()
subroutine parallel_assemble_sph::copy_field_data_sph_center (type(sph_grids), intent(in) org_sph, type(sph_grids), intent(in) new_sph, type(rj_assemble_tbl), intent(in) j_table, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(org_sph%sph_rj%nnod_rj,ntot_phys_rj), intent(in) d_rj_org, real(kind = kreal), dimension(new_sph%sph_rj%nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 150 of file parallel_assemble_sph.f90.
Referenced by new_sph_restart::set_assembled_sph_data().
dealloc_mode_table_4_assemble()
subroutine parallel_assemble_sph::dealloc_mode_table_4_assemble (type(rj_assemble_tbl), intent(inout) j_table)
Definition at line 62 of file parallel_assemble_sph.f90.
Referenced by t_spectr_data_4_assemble::dealloc_spectr_data_4_assemble().
r_itp_field_data_sph_assemble()
subroutine parallel_assemble_sph::r_itp_field_data_sph_assemble (type(sph_grids), intent(in) org_sph, type(sph_grids), intent(in) new_sph, type(sph_radial_itp_data), intent(in) r_itp, type(rj_assemble_tbl), intent(in) j_table, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(org_sph%sph_rj%nnod_rj,ntot_phys_rj), intent(in) d_rj_org, real(kind = kreal), dimension(new_sph%sph_rj%nnod_rj,ntot_phys_rj), intent(inout) d_rj_new)
Definition at line 182 of file parallel_assemble_sph.f90.
Referenced by new_sph_restart::set_assembled_sph_data().
set_mode_table_4_assemble()
subroutine parallel_assemble_sph::set_mode_table_4_assemble (type(sph_grids), intent(in) org_sph, type(sph_grids), intent(in) new_sph, type(rj_assemble_tbl), intent(inout) j_table)
Definition at line 74 of file parallel_assemble_sph.f90.
References t_spheric_rj_data::find_local_sph_address().
Referenced by assemble_sph_fields::load_new_spectr_rj_data().