CALYPSO: set_sph_1d_domain_id Module Reference
set_sph_1d_domain_id Module Reference
Functions/Subroutines
subroutine set_sph_1d_domain_id_rtp (stk_lc1d, sph_gl1d, s3d_ranks)
subroutine set_sph_1d_domain_id_rj (stk_lc1d, sph_gl1d, s3d_ranks)
Function/Subroutine Documentation
set_sph_1d_domain_id_rj()
subroutine set_sph_1d_domain_id::set_sph_1d_domain_id_rj (type(sph_1d_index_stack), intent(in) stk_lc1d, type(sph_1d_global_index), intent(in) sph_gl1d, type(spheric_global_rank), intent(inout) s3d_ranks)
Definition at line 74 of file set_sph_1d_domain_id.f90.
Referenced by const_global_sph_grids_modes::s_const_global_sph_grids_modes().
set_sph_1d_domain_id_rtp()
subroutine set_sph_1d_domain_id::set_sph_1d_domain_id_rtp (type(sph_1d_index_stack), intent(in) stk_lc1d, type(sph_1d_global_index), intent(in) sph_gl1d, type(spheric_global_rank), intent(inout) s3d_ranks)
Definition at line 29 of file set_sph_1d_domain_id.f90.
Referenced by const_fem_mesh_sph_mhd::const_global_sph_fem(), const_global_sph_grids_modes::const_global_sph_fem_grid(), and const_global_sph_grids_modes::s_const_global_sph_grids_modes().