CALYPSO: field_file_mpi_io_b Module Reference
field_file_mpi_io_b Module Reference
Output merged binary field file using MPI-IO.
Functions/Subroutines
subroutine write_step_field_file_mpi_b (file_name, t_IO, fld_IO)
subroutine read_step_field_file_mpi_b (file_name, num_pe, id_rank, t_IO, fld_IO)
subroutine read_alloc_stp_fld_file_mpi_b (file_name, num_pe, id_rank, t_IO, fld_IO)
subroutine read_alloc_stp_fld_head_mpi_b (file_name, num_pe, id_rank, t_IO, fld_IO)
Variables
type(calypso_mpi_io_params), save, private io_param
Detailed Description
Output merged binary field file using MPI-IO.
      subroutine write_step_field_file_mpi_b(file_name, t_IO, fld_IO)
        type(time_data), intent(in) :: t_IO
        type(field_IO), intent(in) :: fld_IO
      subroutine read_step_field_file_mpi_b                           &
     &         (file_name, num_pe, id_rank, t_IO, fld_IO)
      subroutine read_alloc_stp_fld_file_mpi_b                        &
     &         (file_name, num_pe, id_rank, t_IO, fld_IO)
      subroutine read_alloc_stp_fld_head_mpi_b                        &
     &         (file_name, num_pe, id_rank, t_IO, fld_IO)
        type(time_data), intent(inout) :: t_IO
        type(field_IO), intent(inout) :: fld_IO
   Data format for the merged binary field data
     1.   Number of process
     2.   Time step
     3.   Time, Delta t
     4.   Stacks of numbe of data points
     5.   Number of fields
     6.   List of number of components
     7.   Field names
     8.   List of data size (Byte)
     9.   All Field data
Function/Subroutine Documentation
read_alloc_stp_fld_file_mpi_b()
subroutine field_file_mpi_io_b::read_alloc_stp_fld_file_mpi_b (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO)
Definition at line 137 of file field_file_MPI_IO_b.f90.
References t_field_data_io::alloc_merged_field_stack(), t_field_data_io::alloc_phys_data_io(), t_field_data_io::alloc_phys_name_io(), t_field_data_io::cal_istack_phys_comp_io(), mpi_ascii_data_io::close_mpi_file(), t_field_data_io::dealloc_merged_field_stack(), t_field_data_io::dealloc_phys_data_io(), t_field_data_io::dealloc_phys_name_io(), io_param, mpi_binary_data_io::mpi_read_2d_vector_b(), mpi_binary_head_io::mpi_read_mul_charahead_b(), mpi_binary_head_io::mpi_read_mul_inthead_b(), mpi_binary_head_io::mpi_read_one_inthead_b(), calypso_mpi::my_rank, mpi_binary_head_io::open_read_mpi_file_b(), and field_block_mpi_io_b::read_field_header_mpi_b().
Referenced by field_io_select::sel_read_alloc_step_field_file().
read_alloc_stp_fld_head_mpi_b()
subroutine field_file_mpi_io_b::read_alloc_stp_fld_head_mpi_b (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO)
Definition at line 195 of file field_file_MPI_IO_b.f90.
References t_field_data_io::alloc_merged_field_stack(), t_field_data_io::alloc_phys_name_io(), t_field_data_io::cal_istack_phys_comp_io(), mpi_ascii_data_io::close_mpi_file(), t_field_data_io::dealloc_merged_field_stack(), t_field_data_io::dealloc_phys_name_io(), io_param, mpi_binary_head_io::mpi_read_mul_charahead_b(), mpi_binary_head_io::mpi_read_mul_inthead_b(), mpi_binary_head_io::mpi_read_one_inthead_b(), calypso_mpi::my_rank, mpi_binary_head_io::open_read_mpi_file_b(), and field_block_mpi_io_b::read_field_header_mpi_b().
Referenced by field_io_select::sel_read_alloc_field_head().
read_step_field_file_mpi_b()
subroutine field_file_mpi_io_b::read_step_field_file_mpi_b (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, type(time_data), intent(inout) t_IO, type(field_io), intent(inout) fld_IO)
Definition at line 87 of file field_file_MPI_IO_b.f90.
References t_field_data_io::alloc_merged_field_stack(), mpi_ascii_data_io::close_mpi_file(), t_field_data_io::dealloc_merged_field_stack(), io_param, mpi_binary_data_io::mpi_read_2d_vector_b(), mpi_binary_head_io::mpi_read_mul_charahead_b(), mpi_binary_head_io::mpi_read_mul_inthead_b(), mpi_binary_head_io::mpi_read_one_inthead_b(), calypso_mpi::my_rank, mpi_binary_head_io::open_read_mpi_file_b(), and field_block_mpi_io_b::read_field_header_mpi_b().
Referenced by field_io_select::sel_read_step_field_file().
write_step_field_file_mpi_b()
subroutine field_file_mpi_io_b::write_step_field_file_mpi_b (character(len=kchara), intent(in) file_name, type(time_data), intent(in) t_IO, type(field_io), intent(in) fld_IO)
Definition at line 58 of file field_file_MPI_IO_b.f90.
References transfer_to_long_integers::cast_long(), mpi_ascii_data_io::close_mpi_file(), io_param, calypso_mpi::my_rank, mpi_binary_head_io::open_write_mpi_file_b(), field_block_mpi_io_b::write_field_data_mpi_b(), and field_block_mpi_io_b::write_field_time_mpi_b().
Referenced by field_io_select::sel_write_step_field_file().
Variable Documentation
io_param
type(calypso_mpi_io_params), save, private field_file_mpi_io_b::io_param private
Definition at line 50 of file field_file_MPI_IO_b.f90.
Referenced by read_alloc_stp_fld_file_mpi_b(), read_alloc_stp_fld_head_mpi_b(), read_step_field_file_mpi_b(), and write_step_field_file_mpi_b().