CALYPSO: t_calypso_mpi_io_param Module Reference
t_calypso_mpi_io_param Module Reference
Base parameter structure for MPI-IO.
Data Types
type calypso_mpi_io_params
Structure for parameters of MPI-IO.
Functions/Subroutines
subroutine alloc_istack_merge (id_rank, nprocs_in, IO_param)
subroutine dealloc_istack_merge (IO_param)
integer(kind=kint) function rank_in_multi_domain (iloop)
integer(kind=kint) function num_loop_4_multi_domain (nprocs_in)
subroutine copy_istack_4_parallell_data (istack8, IO_param)
subroutine mul_istack_4_parallell_vect (nvect, IO_param)
subroutine set_numbers_2_head_node (num_local, IO_param)
subroutine istack64_4_parallel_data (num_local, IO_param)
subroutine set_istack_over_subdomains (nprocs_in, nloop, num_local, istack_merged)
Detailed Description
Base parameter structure for MPI-IO.
      subroutine alloc_istack_merge(id_rank, nprocs_in, IO_param)
      subroutine dealloc_istack_merge(IO_param)
      integer(kind = kint) function rank_in_multi_domain(iloop)
      integer(kind = kint) function num_loop_4_multi_domain(nprocs_in)
      subroutine copy_istack_4_parallell_data(istack8, IO_param)
      subroutine mul_istack_4_parallell_vect(nvect, IO_param)
      subroutine set_numbers_2_head_node(num_local, IO_param)
      subroutine istack64_4_parallel_data(num_local, IO_param)
      subroutine set_istack_over_subdomains                           &
     &         (nprocs_in, nloop, num_local, istack_merged)
Function/Subroutine Documentation
alloc_istack_merge()
subroutine t_calypso_mpi_io_param::alloc_istack_merge (integer, intent(in) id_rank, integer, intent(in) nprocs_in, type(calypso_mpi_io_params), intent(inout) IO_param)
Definition at line 64 of file t_calypso_mpi_IO_param.f90.
References calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by mpi_ascii_data_io::open_append_mpi_file(), mpi_ascii_data_io::open_read_mpi_file(), and mpi_ascii_data_io::open_write_mpi_file().
copy_istack_4_parallell_data()
subroutine t_calypso_mpi_io_param::copy_istack_4_parallell_data (integer(kind = kint_gl), dimension(0:io_param%nprocs_in), intent(in) istack8, type(calypso_mpi_io_params), intent(inout) IO_param)
Definition at line 135 of file t_calypso_mpi_IO_param.f90.
Referenced by field_block_mpi_io_b::write_field_data_mpi_b().
dealloc_istack_merge()
subroutine t_calypso_mpi_io_param::dealloc_istack_merge (type(calypso_mpi_io_params), intent(inout) IO_param)
Definition at line 97 of file t_calypso_mpi_IO_param.f90.
Referenced by mpi_ascii_data_io::close_mpi_file().
istack64_4_parallel_data()
subroutine t_calypso_mpi_io_param::istack64_4_parallel_data (integer(kind = kint_gl), intent(in) num_local, type(calypso_mpi_io_params), intent(inout) IO_param)
Definition at line 183 of file t_calypso_mpi_IO_param.f90.
References calypso_mpi_int8::calypso_mpi_allgather_one_int8().
Referenced by gz_mpi_binary_data_io::gz_mpi_write_1d_vector_b(), gz_mpi_binary_data_io::gz_mpi_write_int8_vector_b(), gz_mpi_ascii_data_io::gz_mpi_write_stack_over_domain(), mpi_domain_data_io_b::mpi_write_domain_info_b(), mpi_element_connect_io_b::mpi_write_edge_4_element_b(), mpi_element_connect_io_b::mpi_write_element_info_b(), mpi_domain_data_io_b::mpi_write_export_data_b(), mpi_spherical_model_io_b::mpi_write_gl_nodes_sph_b(), mpi_groups_io_b::mpi_write_grp_data_b(), mpi_domain_data_io_b::mpi_write_import_data_b(), mpi_binary_data_io::mpi_write_integer_stack_b(), mpi_spherical_model_io_b::mpi_write_rank_4_sph_b(), mpi_sph_gl_1d_idx_io_b::mpi_write_rj_gl_1d_table_b(), mpi_sph_gl_1d_idx_io_b::mpi_write_rtp_gl_1d_table_b(), mpi_ascii_data_io::mpi_write_stack_over_domain(), mpi_groups_io_b::mpi_write_surf_grp_data_b(), mpi_element_connect_io_b::mpi_write_surface_4_element_b(), mpi_viewer_mesh_io::mpi_write_viewer_connect(), mpi_viewer_mesh_io::mpi_write_viewer_element_type(), mpi_viewer_mesh_io::mpi_write_viewer_grp_item(), mpi_viewer_mesh_io::mpi_write_viewer_position(), mpi_sph_gauss_coefs_io::write_sph_gauss_header_mpi(), ucd_file_mpi_io::write_ucd_data_mpi_b(), and ucd_file_mpi_io::write_ucd_mesh_data_mpi_b().
mul_istack_4_parallell_vect()
subroutine t_calypso_mpi_io_param::mul_istack_4_parallell_vect (integer(kind = kint), intent(in) nvect, type(calypso_mpi_io_params), intent(inout) IO_param)
Definition at line 151 of file t_calypso_mpi_IO_param.f90.
Referenced by mpi_binary_data_io::mpi_read_2d_vector_b(), mpi_binary_data_io::mpi_write_2d_vector_b(), mpi_element_connect_io_b::mpi_write_element_info_b(), and mpi_spherical_model_io_b::mpi_write_gl_nodes_sph_b().
num_loop_4_multi_domain()
integer(kind = kint) function t_calypso_mpi_io_param::num_loop_4_multi_domain (integer, intent(in) nprocs_in)
Definition at line 120 of file t_calypso_mpi_IO_param.f90.
References calypso_mpi::nprocs, and rank_in_multi_domain().
rank_in_multi_domain()
integer(kind = kint) function t_calypso_mpi_io_param::rank_in_multi_domain (integer(kind = kint), intent(in) iloop)
Definition at line 110 of file t_calypso_mpi_IO_param.f90.
References calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by num_loop_4_multi_domain().
set_istack_over_subdomains()
subroutine t_calypso_mpi_io_param::set_istack_over_subdomains (integer, intent(in) nprocs_in, integer(kind = kint), intent(in) nloop, integer(kind = kint_gl), dimension(nloop), intent(in) num_local, integer(kind = kint_gl), dimension(0:nprocs_in), intent(inout) istack_merged)
Definition at line 206 of file t_calypso_mpi_IO_param.f90.
References calypso_mpi_int8::calypso_mpi_allreduce_int8(), calypso_mpi::my_rank, and calypso_mpi::nprocs.
set_numbers_2_head_node()
subroutine t_calypso_mpi_io_param::set_numbers_2_head_node (integer(kind = kint), intent(in) num_local, type(calypso_mpi_io_params), intent(inout) IO_param)
Definition at line 166 of file t_calypso_mpi_IO_param.f90.
References calypso_mpi_int::calypso_mpi_allgather_one_int().
Referenced by gz_mpi_ascii_data_io::gz_mpi_write_num_of_data(), and mpi_ascii_data_io::mpi_write_num_of_data().