CALYPSO: add_prod_field_4_sph_trns Module Reference
add_prod_field_4_sph_trns Module Reference
Products of field addresses for spherical harmonics transform in MHD dynamo simulation.
Functions/Subroutines
subroutine add_subtracted_sph_trns_snap (d_rj, ipol_prd, iphys_prd, b_trns_prd, trns)
subroutine add_prod_vector_sph_trns_snap (d_rj, ipol_prd, iphys_prd, f_trns_prd, trns)
subroutine add_prod_scalar_sph_trns_snap (d_rj, ipol_prd, iphys_prd, f_trns_prd, trns)
Detailed Description
Products of field addresses for spherical harmonics transform in MHD dynamo simulation.
      subroutine add_subtracted_sph_trns_snap                         &
     &         (d_rj, ipol_prd, iphys_prd, b_trns_prd, trns)
        type(phys_data), intent(in) :: d_rj
        type(phys_products_address), intent(in) :: ipol_prd, iphys_prd
        type(phys_products_address), intent(inout) :: b_trns_prd
        type(spherical_transform_data), intent(inout) :: trns
      subroutine add_prod_vector_sph_trns_snap                        &
     &         (d_rj, ipol_prd, iphys_prd, f_trns_prd, trns)
      subroutine add_prod_scalar_sph_trns_snap                        &
     &         (d_rj, ipol_prd, iphys_prd, f_trns_prd, trns)
        type(phys_data), intent(in) :: d_rj
        type(phys_products_address), intent(in) :: ipol_prd, iphys_prd
        type(phys_products_address), intent(inout) :: f_trns_prd
        type(spherical_transform_data), intent(inout) :: trns
Function/Subroutine Documentation
add_prod_scalar_sph_trns_snap()
subroutine add_prod_field_4_sph_trns::add_prod_scalar_sph_trns_snap (type(phys_data), intent(in) d_rj, type(phys_products_address), intent(in) ipol_prd, type(phys_products_address), intent(in) iphys_prd, type(phys_products_address), intent(inout) f_trns_prd, type(spherical_transform_data), intent(inout) trns)
Definition at line 109 of file add_prod_field_4_sph_trns.f90.
References add_field_to_sph_trans_list::add_field_name_4_sph_trns_snap().
Referenced by address_sph_trans_snap::fwd_trans_address_ene_flux().
add_prod_vector_sph_trns_snap()
subroutine add_prod_field_4_sph_trns::add_prod_vector_sph_trns_snap (type(phys_data), intent(in) d_rj, type(phys_products_address), intent(in) ipol_prd, type(phys_products_address), intent(in) iphys_prd, type(phys_products_address), intent(inout) f_trns_prd, type(spherical_transform_data), intent(inout) trns)
Definition at line 71 of file add_prod_field_4_sph_trns.f90.
References add_field_to_sph_trans_list::add_field_name_4_sph_trns_snap().
Referenced by address_sph_trans_snap::fwd_trans_address_ene_flux().
add_subtracted_sph_trns_snap()
subroutine add_prod_field_4_sph_trns::add_subtracted_sph_trns_snap (type(phys_data), intent(in) d_rj, type(phys_products_address), intent(in) ipol_prd, type(phys_products_address), intent(in) iphys_prd, type(phys_products_address), intent(inout) b_trns_prd, type(spherical_transform_data), intent(inout) trns)
Definition at line 43 of file add_prod_field_4_sph_trns.f90.
References add_field_to_sph_trans_list::add_field_name_4_sph_trns_snap().
Referenced by address_sph_trans_snap::bwd_trans_address_ene_flux().