CALYPSO: t_io_step_parameter Module Reference
t_io_step_parameter Module Reference
Parameteres for time steppings.
Data Types
type io_step_param
Functions/Subroutines
logical function output_io_flag (i_step, IO_step)
integer(kind=kint) function set_io_step (i_step, IO_step)
integer(kind=kint) function io_step_exc_zero_inc (i_step, IO_step)
subroutine output_step_4_fixed_step_ctl (istep_def, dt, istep_ctl, delta_t_ctl, IO_step)
subroutine output_step_4_flex_step_ctl (istep_def, dt_max, istep_ctl, delta_t_ctl, IO_step)
logical function output_flag (i_step, increment)
logical function iflag_viz_flex_step (time_d, IO_step)
integer(kind=kint) function istep_file_w_fix_dt (i_step, IO_step)
integer(kind=kint) function istep_file_w_flex_dt (time_d, IO_step)
Detailed Description
Parameteres for time steppings.
      subroutine output_step_4_fixed_step_ctl(istep_def, dt,          &
     &          istep_ctl, delta_t_ctl, IO_step)
      subroutine output_step_4_flex_step_ctl                          &
     &         (istep_def, dt_max, step_ctl, delta_t_ctl, IO_step)
        type(read_integer_item), intent(inout) :: step_ctl
        type(read_real_item), intent(inout) :: delta_t_ctl
        type(IO_step_param), intent(inout) :: IO_step
      logical function output_IO_flag(i_step, IO_step)
        type(IO_step_param), intent(in) :: IO_step
      integer(kind = kint) function set_IO_step(i_step, IO_step)
        type(IO_step_param), intent(inout) :: IO_step
      subroutine set_monitor_param_4_fixed_step(istep_def, istep_ctl, &
     &          delta_t_ctl, istep_out, dt_out)
      subroutine set_monitor_param_4_flex_step(istep_def, dt_max,     &
     &          istep_ctl, delta_t_ctl, istep_out, dt_out)
      logical function output_flag(i_step, increment)
      logical function iflag_viz_flex_step(time_d, IO_step)
        type(time_data), intent(in) :: time_d
        type(IO_step_param), intent(in) :: IO_step
      integer(kind = kint) function istep_file_w_fix_dt               &
     &                            (i_step, IO_step)
      integer(kind = kint) function                                   &
     &                    istep_file_w_flex_dt(time_d, IO_step)
        type(time_data), intent(in) :: time_d
        type(IO_step_param), intent(in) :: IO_step
Function/Subroutine Documentation
iflag_viz_flex_step()
logical function t_io_step_parameter::iflag_viz_flex_step (type(time_data), intent(in) time_d, type(io_step_param), intent(in) IO_step)
Definition at line 184 of file t_IO_step_parameter.f90.
References m_constants::zero.
Referenced by output_viz_file_control::iflag_viz_output(), and t_viz_step_parameter::iflag_vizs_w_flex_step().
io_step_exc_zero_inc()
integer(kind = kint) function t_io_step_parameter::io_step_exc_zero_inc (integer (kind =kint), intent(in) i_step, type(io_step_param), intent(in) IO_step)
Definition at line 92 of file t_IO_step_parameter.f90.
Referenced by load_mesh_and_field_4_viz::mesh_setup_4_viz(), t_ucd_file::read_udt_4_snap(), t_ucd_file::s_output_ucd_file_control(), and load_mesh_and_field_4_viz::set_field_data_4_viz().
istep_file_w_fix_dt()
integer(kind = kint) function t_io_step_parameter::istep_file_w_fix_dt (integer(kind = kint), intent(in) i_step, type(io_step_param), intent(in) IO_step)
Definition at line 208 of file t_IO_step_parameter.f90.
References m_constants::ione, and m_constants::izero.
Referenced by t_viz_step_parameter::istep_viz_w_fix_dt(), and output_viz_file_control::viz_time_step().
istep_file_w_flex_dt()
integer(kind = kint) function t_io_step_parameter::istep_file_w_flex_dt (type(time_data), intent(in) time_d, type(io_step_param), intent(in) IO_step)
Definition at line 225 of file t_IO_step_parameter.f90.
References m_constants::ione, and m_constants::zero.
Referenced by t_viz_step_parameter::istep_viz_w_flex_dt(), and output_viz_file_control::viz_time_step().
output_flag()
logical function t_io_step_parameter::output_flag (integer (kind = kint), intent(in) i_step, integer (kind = kint), intent(in) increment)
Definition at line 169 of file t_IO_step_parameter.f90.
Referenced by output_io_flag().
output_io_flag()
logical function t_io_step_parameter::output_io_flag (integer (kind =kint), intent(in) i_step, type(io_step_param), intent(in) IO_step)
Definition at line 61 of file t_IO_step_parameter.f90.
References output_flag().
Referenced by output_viz_file_control::iflag_viz_output(), t_viz_step_parameter::iflag_vizs_w_fix_step(), output_viz_file_control::lead_field_data_flag(), node_monitor_io::output_monitor_control(), sph_mhd_rst_io_control::output_spectr_4_snap(), t_ucd_file::read_udt_4_snap(), and t_ucd_file::s_output_ucd_file_control().
output_step_4_fixed_step_ctl()
subroutine t_io_step_parameter::output_step_4_fixed_step_ctl (integer(kind = kint), intent(in) istep_def, real(kind = kreal), intent(in) dt, type(read_integer_item), intent(in) istep_ctl, type(read_real_item), intent(in) delta_t_ctl, type(io_step_param), intent(inout) IO_step)
Definition at line 110 of file t_IO_step_parameter.f90.
Referenced by t_viz_only_step_parameter::set_fixed_t_step_params_w_viz(), t_mhd_step_parameter::set_fixed_time_step_controls(), t_step_parameter::set_fixed_time_step_params(), and t_viz_step_parameter::viz_fixed_time_step_params().
output_step_4_flex_step_ctl()
subroutine t_io_step_parameter::output_step_4_flex_step_ctl (integer(kind = kint), intent(in) istep_def, real(kind = kreal), intent(in) dt_max, type(read_integer_item), intent(in) istep_ctl, type(read_real_item), intent(in) delta_t_ctl, type(io_step_param), intent(inout) IO_step)
Definition at line 139 of file t_IO_step_parameter.f90.
Referenced by t_mhd_step_parameter::set_flex_time_step_controls(), t_flex_delta_t_parameter::set_flex_time_step_params(), and t_viz_step_parameter::viz_flex_time_step_controls().
set_io_step()
integer(kind = kint) function t_io_step_parameter::set_io_step (integer (kind =kint), intent(in) i_step, type(io_step_param), intent(in) IO_step)
Definition at line 73 of file t_IO_step_parameter.f90.
Referenced by sph_mhd_rst_io_control::output_spectr_4_snap(), sph_mhd_rst_io_control::output_sph_restart_control(), sph_mhd_rst_io_control::read_alloc_sph_restart_data(), sph_mhd_rst_io_control::read_alloc_sph_rst_4_snap(), and sph_mhd_rst_io_control::read_alloc_sph_spectr().