CALYPSO: t_spectr_data_4_assemble Module Reference
t_spectr_data_4_assemble Module Reference
Main loop to assemble spectr data.
Data Types
type spectr_data_4_assemble
Functions/Subroutines
subroutine alloc_spectr_data_4_assemble (sph_asbl)
subroutine dealloc_spectr_data_4_assemble (sph_asbl)
Detailed Description
Main loop to assemble spectr data.
      subroutine alloc_spectr_data_4_assemble(sph_asbl)
      subroutine dealloc_spectr_data_4_assemble(sph_asbl)
        type(spectr_data_4_assemble), intent(inout) :: sph_asbl
Function/Subroutine Documentation
alloc_spectr_data_4_assemble()
subroutine t_spectr_data_4_assemble::alloc_spectr_data_4_assemble (type(spectr_data_4_assemble), intent(inout) sph_asbl)
Definition at line 51 of file t_spectr_data_4_assemble.f90.
Referenced by analyzer_assemble_sph::init_assemble_sph(), analyzer_compare_sph_rst::init_compare_sph_restart(), and analyzer_rayleigh_cvt_sph::init_cvt_rayleigh_sph().
dealloc_spectr_data_4_assemble()
subroutine t_spectr_data_4_assemble::dealloc_spectr_data_4_assemble (type(spectr_data_4_assemble), intent(inout) sph_asbl)
Definition at line 64 of file t_spectr_data_4_assemble.f90.
References parallel_assemble_sph::dealloc_mode_table_4_assemble().
Referenced by analyzer_assemble_sph::analyze_assemble_sph(), and analyzer_compare_sph_rst::analyze_compare_sph_restart().