CALYPSO: set_comm_table_rtm_rlm Module Reference
set_comm_table_rtm_rlm Module Reference
Construct communication table for rlm and rtm grid.
Functions/Subroutines
subroutine allocate_ncomm (ndomain_sph)
subroutine deallocate_ncomm
subroutine count_comm_table_4_rlm (s3d_ranks, nnod_rlm, idx_global_rlm)
subroutine set_comm_table_4_rlm (s3d_ranks, nnod_rlm, idx_global_rlm, nneib_domain_rlm, ntot_item_sr_rlm, istack_sr_rlm, item_sr_rlm)
subroutine count_comm_table_4_rtm (s3d_ranks, nnod_rtm, nidx_global_rtm, idx_global_rtm)
subroutine set_comm_table_4_rtm (s3d_ranks, nnod_rtm, nidx_global_rtm, idx_global_rtm, nneib_domain_rtm, ntot_item_sr_rtm, istack_sr_rtm, item_sr_rtm)
subroutine count_num_domain_rtm_rlm (ndomain_sph, nneib_domain)
subroutine set_comm_stack_rtm_rlm (id_rank, ndomain_sph, nneib_domain, id_domain, istack_sr, ntot_item_sr)
Variables
integer(kind=kint), dimension(:), allocatable, private ncomm
integer(kind=kint), dimension(:), allocatable, private ineib_tgt
Detailed Description
Construct communication table for rlm and rtm grid.
      subroutine allocate_ncomm(ndomain_sph)
      subroutine deallocate_ncomm
      subroutine count_comm_table_4_rlm                               &
     &         (s3d_ranks, nnod_rlm, idx_global_rlm)
      subroutine set_comm_table_4_rlm                                 &
     &         (s3d_ranks, nnod_rlm, idx_global_rlm,                  &
     &          nneib_domain_rlm, ntot_item_sr_rlm, istack_sr_rlm,    &
     &          item_sr_rlm)
        type(spheric_global_rank), intent(in) :: s3d_ranks
      subroutine count_comm_table_4_rtm                               &
     &         (s3d_ranks, nnod_rtm, nidx_global_rtm, idx_global_rtm)
      subroutine set_comm_table_4_rtm                                 &
     &         (s3d_ranks, nnod_rtm, nidx_global_rtm, idx_global_rtm, &
     &          nneib_domain_rtm, ntot_item_sr_rtm, istack_sr_rtm,    &
     &          item_sr_rtm)
        type(spheric_global_rank), intent(in) :: s3d_ranks
      subroutine count_num_domain_rtm_rlm(ndomain_sph, nneib_domain)
      subroutine set_comm_stack_rtm_rlm(id_rank, ndomain_sph,         &
     &          nneib_domain, id_domain, istack_sr, ntot_item_sr)
Function/Subroutine Documentation
allocate_ncomm()
subroutine set_comm_table_rtm_rlm::allocate_ncomm (integer(kind = kint), intent(in) ndomain_sph)
Definition at line 51 of file set_comm_table_rtm_rlm.f90.
References ineib_tgt, and ncomm.
Referenced by gen_sph_grids_modes::const_comm_table_4_rlm(), and gen_sph_grids_modes::const_comm_table_4_rtm().
count_comm_table_4_rlm()
subroutine set_comm_table_rtm_rlm::count_comm_table_4_rlm (type(spheric_global_rank), intent(in) s3d_ranks, integer(kind = kint), intent(in) nnod_rlm, integer(kind = kint), dimension(nnod_rlm,2), intent(in) idx_global_rlm)
Definition at line 73 of file set_comm_table_rtm_rlm.f90.
References ncomm, and set_global_spherical_param::set_rank_by_1b_rj_rank().
Referenced by gen_sph_grids_modes::const_comm_table_4_rlm().
count_comm_table_4_rtm()
subroutine set_comm_table_rtm_rlm::count_comm_table_4_rtm (type(spheric_global_rank), intent(in) s3d_ranks, integer(kind = kint), intent(in) nnod_rtm, integer(kind = kint), dimension(3), intent(in) nidx_global_rtm, integer(kind = kint), dimension(nnod_rtm,3), intent(in) idx_global_rtm)
Definition at line 152 of file set_comm_table_rtm_rlm.f90.
References ncomm, and set_global_spherical_param::set_rank_by_1b_sph_rank().
Referenced by gen_sph_grids_modes::const_comm_table_4_rtm().
count_num_domain_rtm_rlm()
subroutine set_comm_table_rtm_rlm::count_num_domain_rtm_rlm (integer(kind = kint), intent(in) ndomain_sph, integer(kind = kint), intent(inout) nneib_domain)
Definition at line 269 of file set_comm_table_rtm_rlm.f90.
References ncomm.
Referenced by gen_sph_grids_modes::const_comm_table_4_rlm(), and gen_sph_grids_modes::const_comm_table_4_rtm().
deallocate_ncomm()
subroutine set_comm_table_rtm_rlm::deallocate_ncomm
Definition at line 64 of file set_comm_table_rtm_rlm.f90.
References ineib_tgt, and ncomm.
Referenced by gen_sph_grids_modes::const_comm_table_4_rlm(), and gen_sph_grids_modes::const_comm_table_4_rtm().
set_comm_stack_rtm_rlm()
subroutine set_comm_table_rtm_rlm::set_comm_stack_rtm_rlm (integer, intent(in) id_rank, integer(kind = kint), intent(in) ndomain_sph, integer(kind = kint), intent(in) nneib_domain, integer(kind = kint), dimension(nneib_domain), intent(inout) id_domain, integer(kind = kint), dimension(0:nneib_domain), intent(inout) istack_sr, integer(kind = kint), intent(inout) ntot_item_sr)
Definition at line 285 of file set_comm_table_rtm_rlm.f90.
References ineib_tgt, and ncomm.
Referenced by gen_sph_grids_modes::const_comm_table_4_rlm(), and gen_sph_grids_modes::const_comm_table_4_rtm().
set_comm_table_4_rlm()
subroutine set_comm_table_rtm_rlm::set_comm_table_4_rlm (type(spheric_global_rank), intent(in) s3d_ranks, integer(kind = kint), intent(in) nnod_rlm, integer(kind = kint), dimension(nnod_rlm,2), intent(in) idx_global_rlm, integer(kind = kint), intent(in) nneib_domain_rlm, integer(kind = kint), intent(in) ntot_item_sr_rlm, integer(kind = kint), dimension(0:nneib_domain_rlm), intent(in) istack_sr_rlm, integer(kind = kint), dimension(ntot_item_sr_rlm), intent(inout) item_sr_rlm)
Definition at line 105 of file set_comm_table_rtm_rlm.f90.
References ineib_tgt, ncomm, and set_global_spherical_param::set_rank_by_1b_rj_rank().
Referenced by gen_sph_grids_modes::const_comm_table_4_rlm().
set_comm_table_4_rtm()
subroutine set_comm_table_rtm_rlm::set_comm_table_4_rtm (type(spheric_global_rank), intent(in) s3d_ranks, integer(kind = kint), intent(in) nnod_rtm, integer(kind = kint), dimension(3), intent(in) nidx_global_rtm, integer(kind = kint), dimension(nnod_rtm,3), intent(in) idx_global_rtm, integer(kind = kint), intent(in) nneib_domain_rtm, integer(kind = kint), intent(in) ntot_item_sr_rtm, integer(kind = kint), dimension(0:nneib_domain_rtm), intent(in) istack_sr_rtm, integer(kind = kint), dimension(ntot_item_sr_rtm), intent(inout) item_sr_rtm)
Definition at line 202 of file set_comm_table_rtm_rlm.f90.
References ineib_tgt, ncomm, and set_global_spherical_param::set_rank_by_1b_sph_rank().
Referenced by gen_sph_grids_modes::const_comm_table_4_rtm().
Variable Documentation
ineib_tgt
integer(kind = kint), dimension(:), allocatable, private set_comm_table_rtm_rlm::ineib_tgt private
Definition at line 42 of file set_comm_table_rtm_rlm.f90.
Referenced by allocate_ncomm(), deallocate_ncomm(), set_comm_stack_rtm_rlm(), set_comm_table_4_rlm(), and set_comm_table_4_rtm().
ncomm
integer(kind = kint), dimension(:), allocatable, private set_comm_table_rtm_rlm::ncomm private
Definition at line 41 of file set_comm_table_rtm_rlm.f90.
Referenced by allocate_ncomm(), count_comm_table_4_rlm(), count_comm_table_4_rtm(), count_num_domain_rtm_rlm(), deallocate_ncomm(), set_comm_stack_rtm_rlm(), set_comm_table_4_rlm(), and set_comm_table_4_rtm().