CALYPSO: element_data_io_b Module Reference
element_data_io_b Module Reference
Data IO routines for element data.
Functions/Subroutines
subroutine read_element_comm_table_b (id_rank, bbuf, comm_IO)
subroutine write_element_comm_table_b (id_rank, comm_IO, bbuf)
subroutine read_element_geometry_b (bbuf, nod_IO, sfed_IO)
subroutine write_element_geometry_b (nod_IO, sfed_IO, bbuf)
Detailed Description
Data IO routines for element data.
      subroutine read_element_comm_table_b(id_rank, bbuf, comm_IO)
        type(binary_IO_buffer), intent(inout) :: bbuf
        type(communication_table), intent(inout) :: comm_IO
      subroutine write_element_comm_table_b(id_rank, comm_IO, bbuf)
        type(communication_table), intent(in) :: comm_IO
        type(binary_IO_buffer), intent(inout) :: bbuf
      subroutine read_element_geometry_b(bbuf, nod_IO, sfed_IO)
        type(binary_IO_buffer), intent(inout) :: bbuf
        type(node_data), intent(inout) :: nod_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
      subroutine write_element_geometry_b(nod_IO, sfed_IO, bbuf)
        type(node_data), intent(in) :: nod_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
        type(binary_IO_buffer), intent(inout) :: bbuf
Function/Subroutine Documentation
read_element_comm_table_b()
subroutine element_data_io_b::read_element_comm_table_b (integer, intent(in) id_rank, type(binary_io_buffer), intent(inout) bbuf, type(communication_table), intent(inout) comm_IO)
Definition at line 46 of file element_data_IO_b.f90.
References domain_data_io_b::read_domain_info_b(), domain_data_io_b::read_export_data_b(), and domain_data_io_b::read_import_data_b().
Referenced by element_file_io_b::input_element_file_b().
read_element_geometry_b()
subroutine element_data_io_b::read_element_geometry_b (type(binary_io_buffer), intent(inout) bbuf, type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 94 of file element_data_IO_b.f90.
References node_geometry_io_b::read_geometry_info_b(), node_geometry_io_b::read_number_of_node_b(), and node_geometry_io_b::read_scalar_in_element_b().
write_element_comm_table_b()
subroutine element_data_io_b::write_element_comm_table_b (integer, intent(in) id_rank, type(communication_table), intent(in) comm_IO, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 70 of file element_data_IO_b.f90.
References domain_data_io_b::write_domain_info_b(), domain_data_io_b::write_export_data_b(), and domain_data_io_b::write_import_data_b().
Referenced by element_file_io_b::output_element_file_b().
write_element_geometry_b()
subroutine element_data_io_b::write_element_geometry_b (type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 115 of file element_data_IO_b.f90.
References node_geometry_io_b::write_geometry_info_b(), and node_geometry_io_b::write_scalar_in_element_b().