CALYPSO: div_self_buoyancies_sph Module Reference
div_self_buoyancies_sph Module Reference
Evaluate divergence of buoyancy for pressure evaluation.
Functions/Subroutines
subroutine sel_div_buoyancies_sph_mhd (iflag_4_gravity, iflag_4_composit_buo, sph_rj, ipol_base, ipol_grd, ipol_div_frc, coef_buo, coef_comp_buo, sph_bc_U, ref_param_T, ref_param_C, rj_fld)
subroutine, private cal_div_double_buoyancy_sph_mhd (kr_in, kr_out, coef_t_buo, is_t, ids_t, coef_c_buo, is_c, ids_c, is_div, nidx_rj, radius_1d_rj_r, nnod_rj, ntot_phys_rj, d_rj)
subroutine cal_div_buoyancy_sph_mhd (kr_in, kr_out, coef, is_fld, ids_fld, is_div, nidx_rj, radius_1d_rj_r, nnod_rj, ntot_phys_rj, d_rj)
Detailed Description
Evaluate divergence of buoyancy for pressure evaluation.
      subroutine sel_div_buoyancies_sph_MHD                           &
     &         (iflag_4_gravity, iflag_4_composit_buo,                &
     &          sph_rj, ipol_base, ipol_grd, ipol_div_frc,            &
     &          coef_buo, coef_comp_buo, sph_bc_U,                    &
     &          ref_param_T, ref_param_C, rj_fld)
        type(reference_scalar_param), intent(in) :: ref_param_T
        type(reference_scalar_param), intent(in) :: ref_param_C
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(base_field_address), intent(in) :: ipol_base
        type(gradient_field_address), intent(in) :: ipol_grd
        type(base_force_address), intent(in) :: ipol_div_frc
        type(sph_boundary_type), intent(in) :: sph_bc_U
        type(phys_data), intent(inout) :: rj_fld
      subroutine cal_div_buoyancy_sph_MHD(kr_in, kr_out, coef,        &
     &          is_fld, ids_fld, is_div, nidx_rj, radius_1d_rj_r,     &
     &          nnod_rj, ntot_phys_rj, d_rj)
Parameters
sph_bc_U Structure for basic velocity boundary condition parameters
Function/Subroutine Documentation
cal_div_buoyancy_sph_mhd()
subroutine div_self_buoyancies_sph::cal_div_buoyancy_sph_mhd (integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) kr_out, real(kind = kreal), intent(in) coef, integer(kind= kint), intent(in) is_fld, integer(kind= kint), intent(in) ids_fld, integer(kind= kint), intent(in) is_div, integer(kind = kint), dimension(2), intent(in) nidx_rj, real(kind = kreal), dimension(nidx_rj(1)), intent(in) radius_1d_rj_r, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 172 of file div_self_buoyancies_sph.f90.
References m_constants::three.
Referenced by sel_div_buoyancies_sph_mhd().
cal_div_double_buoyancy_sph_mhd()
subroutine, private div_self_buoyancies_sph::cal_div_double_buoyancy_sph_mhd (integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) kr_out, real(kind = kreal), intent(in) coef_t_buo, integer(kind= kint), intent(in) is_t, integer(kind= kint), intent(in) ids_t, real(kind = kreal), intent(in) coef_c_buo, integer(kind= kint), intent(in) is_c, integer(kind= kint), intent(in) ids_c, integer(kind= kint), intent(in) is_div, integer(kind = kint), dimension(2), intent(in) nidx_rj, real(kind = kreal), dimension(nidx_rj(1)), intent(in) radius_1d_rj_r, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj) private
Definition at line 133 of file div_self_buoyancies_sph.f90.
References m_constants::three.
Referenced by sel_div_buoyancies_sph_mhd().
sel_div_buoyancies_sph_mhd()
subroutine div_self_buoyancies_sph::sel_div_buoyancies_sph_mhd (logical, intent(in) iflag_4_gravity, logical, intent(in) iflag_4_composit_buo, type(sph_rj_grid), intent(in) sph_rj, type(base_field_address), intent(in) ipol_base, type(gradient_field_address), intent(in) ipol_grd, type(base_force_address), intent(in) ipol_div_frc, real(kind = kreal), intent(in) coef_buo, real(kind = kreal), intent(in) coef_comp_buo, type(sph_boundary_type), intent(in) sph_bc_U, type(reference_scalar_param), intent(in) ref_param_T, type(reference_scalar_param), intent(in) ref_param_C, type(phys_data), intent(inout) rj_fld)
Definition at line 48 of file div_self_buoyancies_sph.f90.
References cal_div_buoyancy_sph_mhd(), cal_div_double_buoyancy_sph_mhd(), t_reference_scalar_param::id_sphere_ref_temp, t_reference_scalar_param::id_takepiro_temp, and m_machine_parameter::iflag_debug.