CALYPSO: t_control_data_dynamo_vizs Module Reference
t_control_data_dynamo_vizs Module Reference
Control data structure for zonal mean visualization controls.
Data Types
type sph_dynamo_viz_controls
Structures of zonal mean controls.
Functions/Subroutines
subroutine read_dynamo_viz_control (id_control, hd_block, zm_ctls, c_buf)
subroutine bcast_dynamo_viz_control (zm_ctls)
subroutine read_single_section_ctl (id_control, hd_section, psf_ctls, c_buf)
Variables
character(len=kchara), parameter, private hd_zm_section = 'zonal_mean_section_ctl'
character(len=kchara), parameter, private hd_zrms_section = 'zonal_RMS_section_ctl'
character(len=kchara), parameter, private hd_crustal_filtering = 'crustal_filtering_ctl'
Detailed Description
Control data structure for zonal mean visualization controls.
      subroutine read_dynamo_viz_control                              &
     &         (id_control, hd_block, zm_ctls, c_buf)
      subroutine bcast_dynamo_viz_control(viz_ctls)
  begin dynamo_vizs_control
    file  zonal_mean_section_ctl
    begin  zonal_RMS_section_ctl
      ....
    end zonal_RMS_section_ctl
    begin crustal_filtering_ctl
      truncation_degree_ctl        13
    end crustal_filtering_ctl
  end dynamo_vizs_control
Function/Subroutine Documentation
bcast_dynamo_viz_control()
subroutine t_control_data_dynamo_vizs::bcast_dynamo_viz_control (type(sph_dynamo_viz_controls), intent(inout) zm_ctls)
Definition at line 105 of file t_control_data_dynamo_vizs.f90.
References t_ctl_data_crust_filter::bcast_crustal_filtering_ctl(), and t_control_data_sections::bcast_files_4_psf_ctl().
Referenced by t_ctl_data_mhd::bcast_sph_mhd_ctl_w_psf().
read_dynamo_viz_control()
subroutine t_control_data_dynamo_vizs::read_dynamo_viz_control (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(sph_dynamo_viz_controls), intent(inout) zm_ctls, type(buffer_for_control), intent(inout) c_buf)
Definition at line 73 of file t_control_data_dynamo_vizs.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_crustal_filtering, hd_zm_section, hd_zrms_section, t_read_control_elements::load_one_line_from_control(), t_ctl_data_crust_filter::read_crustal_filtering_ctl(), and read_single_section_ctl().
Referenced by t_ctl_data_mhd::read_sph_mhd_ctl_w_psf().
read_single_section_ctl()
subroutine t_control_data_dynamo_vizs::read_single_section_ctl (integer(kind = kint), intent(in) id_control, character(len = kchara), intent(in) hd_section, type(section_controls), intent(inout) psf_ctls, type(buffer_for_control), intent(inout) c_buf)
Definition at line 119 of file t_control_data_dynamo_vizs.f90.
References t_control_data_sections::alloc_psf_ctl_stract(), t_read_control_elements::check_begin_flag(), t_read_control_elements::check_file_flag(), t_control_data_sections::read_control_4_psf_file(), and t_read_control_elements::third_word().
Referenced by read_dynamo_viz_control().
Variable Documentation
hd_crustal_filtering
character(len=kchara), parameter, private t_control_data_dynamo_vizs::hd_crustal_filtering = 'crustal_filtering_ctl' private
Definition at line 61 of file t_control_data_dynamo_vizs.f90.
Referenced by read_dynamo_viz_control().
hd_zm_section
character(len=kchara), parameter, private t_control_data_dynamo_vizs::hd_zm_section = 'zonal_mean_section_ctl' private
Definition at line 57 of file t_control_data_dynamo_vizs.f90.
Referenced by read_dynamo_viz_control().
hd_zrms_section
character(len=kchara), parameter, private t_control_data_dynamo_vizs::hd_zrms_section = 'zonal_RMS_section_ctl' private
Definition at line 59 of file t_control_data_dynamo_vizs.f90.
Referenced by read_dynamo_viz_control().