CALYPSO: set_edge_data_by_sf Module Reference
set_edge_data_by_sf Module Reference
Functions/Subroutines
subroutine count_num_edges_by_sf (ntot_id, ntot_list, istack_edge_hash, iend_edge_hash, iedge_flag, numedge)
subroutine set_edges_connect_by_sf (numsurf, numedge, nnod_4_surf, nnod_4_edge, ie_surf, ntot_id, ntot_list, istack_edge_hash, iend_edge_hash, iedge_hash, iedge_flag, ie_edge, iedge_4_sf, node_on_edge_sf)
subroutine set_edges_connect_4_ele (numele, numsurf, numedge, nnod_4_ele, nnod_4_edge, ie, iedge_4_sf, ntot_id, ntot_list, istack_edge_hash, iedge_hash, iedge_flag, ie_edge, iedge_4_ele)
subroutine set_part_edges_4_sf (numsurf, nunmedge_part, iedge_4_sf, ntot_id, ntot_list, istack_edge_hash, iend_edge_hash, iedge_hash, iedge_flag, iedge_part)
Function/Subroutine Documentation
count_num_edges_by_sf()
subroutine set_edge_data_by_sf::count_num_edges_by_sf (integer(kind = kint_gl), intent(in) ntot_id, integer(kind = kint_gl), intent(in) ntot_list, integer(kind = kint_gl), dimension(0:ntot_id), intent(in) istack_edge_hash, integer(kind = kint_gl), intent(in) iend_edge_hash, integer(kind = kint_gl), dimension(ntot_list), intent(in) iedge_flag, integer(kind = kint), intent(inout) numedge)
Definition at line 36 of file set_edge_data_by_sf.f90.
Referenced by const_edge_4_viewer::const_all_edge_4_viewer(), const_edge_4_viewer::construct_edge_4_domain(), const_grp_edge_4_viewer::construct_edge_4_ele_grp(), and const_grp_edge_4_viewer::construct_edge_4_surf_grp().
set_edges_connect_4_ele()
subroutine set_edge_data_by_sf::set_edges_connect_4_ele (integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) numsurf, integer(kind = kint), intent(in) numedge, integer(kind = kint), intent(in) nnod_4_ele, integer(kind = kint), intent(in) nnod_4_edge, integer(kind = kint), dimension(numele,nnod_4_ele), intent(in) ie, integer(kind = kint), dimension(numsurf,nedge_4_surf), intent(in) iedge_4_sf, integer(kind = kint_gl), intent(in) ntot_id, integer(kind = kint_gl), intent(in) ntot_list, integer(kind = kint_gl), dimension(0:ntot_id), intent(in) istack_edge_hash, integer(kind = kint), dimension(ntot_list,2), intent(in) iedge_hash, integer(kind = kint_gl), dimension(ntot_list), intent(in) iedge_flag, integer(kind = kint), dimension(numedge,nnod_4_edge), intent(in) ie_edge, integer(kind = kint), dimension(numele,nedge_4_ele), intent(inout) iedge_4_ele)
Definition at line 138 of file set_edge_data_by_sf.f90.
References m_geometry_constants::nedge_4_ele, and m_geometry_constants::node_on_edge_l.
set_edges_connect_by_sf()
subroutine set_edge_data_by_sf::set_edges_connect_by_sf (integer(kind = kint), intent(in) numsurf, integer(kind = kint), intent(in) numedge, integer(kind = kint), intent(in) nnod_4_surf, integer(kind = kint), intent(in) nnod_4_edge, integer(kind = kint), dimension(numsurf, nnod_4_surf), intent(in) ie_surf, integer(kind = kint_gl), intent(in) ntot_id, integer(kind = kint_gl), intent(in) ntot_list, integer(kind = kint_gl), dimension(0:ntot_id), intent(in) istack_edge_hash, integer(kind = kint_gl), intent(in) iend_edge_hash, integer(kind = kint), dimension(ntot_list,2), intent(in) iedge_hash, integer(kind = kint_gl), dimension(ntot_list), intent(in) iedge_flag, integer(kind = kint), dimension(numedge,nnod_4_edge), intent(inout) ie_edge, integer(kind = kint), dimension(numsurf,nedge_4_surf), intent(inout) iedge_4_sf, integer(kind = kint), dimension(nnod_4_edge,nedge_4_surf), intent(in) node_on_edge_sf)
Definition at line 64 of file set_edge_data_by_sf.f90.
Referenced by const_edge_4_viewer::const_all_edge_4_viewer().
set_part_edges_4_sf()
subroutine set_edge_data_by_sf::set_part_edges_4_sf (integer(kind = kint), intent(in) numsurf, integer(kind = kint), intent(in) nunmedge_part, integer(kind = kint), dimension(numsurf,nedge_4_surf), intent(in) iedge_4_sf, integer(kind = kint_gl), intent(in) ntot_id, integer(kind = kint_gl), intent(in) ntot_list, integer(kind = kint_gl), dimension(0:ntot_id), intent(in) istack_edge_hash, integer(kind = kint_gl), intent(in) iend_edge_hash, integer(kind = kint), dimension(ntot_list,2), intent(in) iedge_hash, integer(kind = kint_gl), dimension(ntot_list), intent(in) iedge_flag, integer(kind = kint), dimension(nunmedge_part), intent(inout) iedge_part)
Definition at line 198 of file set_edge_data_by_sf.f90.
Referenced by const_edge_4_viewer::construct_edge_4_domain(), const_grp_edge_4_viewer::construct_edge_4_ele_grp(), and const_grp_edge_4_viewer::construct_edge_4_surf_grp().