CALYPSO: t_ctl_data_mhd_normalize Module Reference
t_ctl_data_mhd_normalize Module Reference
Data Types
type dimless_control
Structure for list of dimensionless numbers.
type equations_control
Structure for coefficients of governing equations.
Functions/Subroutines
subroutine read_dimless_ctl (id_control, hd_block, dless_ctl, c_buf)
subroutine read_coef_term_ctl (id_control, hd_block, eqs_ctl, c_buf)
subroutine bcast_dimless_ctl (dless_ctl)
subroutine bcast_coef_term_ctl (eqs_ctl)
subroutine dealloc_dimless_ctl (dless_ctl)
subroutine dealloc_coef_term_ctl (eqs_ctl)
Variables
character(len=kchara), parameter, private hd_dimless = 'dimless_ctl'
character(len=kchara), parameter, private hd_momentum = 'momentum'
character(len=kchara), parameter, private hd_thermal = 'thermal'
character(len=kchara), parameter, private hd_dsc_diff_adv = 'composition'
character(len=kchara), parameter, private hd_induction = 'induction'
Function/Subroutine Documentation
bcast_coef_term_ctl()
subroutine t_ctl_data_mhd_normalize::bcast_coef_term_ctl (type(equations_control), intent(inout) eqs_ctl)
Definition at line 233 of file t_ctl_data_mhd_normalize.f90.
References t_ctl_data_induct_norm::bcast_induction_ctl(), t_ctl_data_momentum_norm::bcast_momentum_ctl(), t_ctl_data_termal_norm::bcast_thermal_ctl(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by t_ctl_data_mhd_model::bcast_sph_mhd_model().
bcast_dimless_ctl()
subroutine t_ctl_data_mhd_normalize::bcast_dimless_ctl (type(dimless_control), intent(inout) dless_ctl)
Definition at line 217 of file t_ctl_data_mhd_normalize.f90.
References bcast_control_arrays::bcast_ctl_array_cr(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by t_ctl_data_mhd_model::bcast_sph_mhd_model().
dealloc_coef_term_ctl()
subroutine t_ctl_data_mhd_normalize::dealloc_coef_term_ctl (type(equations_control), intent(inout) eqs_ctl)
Definition at line 264 of file t_ctl_data_mhd_normalize.f90.
References t_ctl_data_induct_norm::dealloc_induction_ctl(), t_ctl_data_momentum_norm::dealloc_momentum_ctl(), and t_ctl_data_termal_norm::dealloc_thermal_ctl().
Referenced by t_ctl_data_mhd_model::dealloc_sph_mhd_model().
dealloc_dimless_ctl()
subroutine t_ctl_data_mhd_normalize::dealloc_dimless_ctl (type(dimless_control), intent(inout) dless_ctl)
Definition at line 252 of file t_ctl_data_mhd_normalize.f90.
References t_control_array_charareal::dealloc_control_array_c_r().
Referenced by t_ctl_data_mhd_model::dealloc_sph_mhd_model().
read_coef_term_ctl()
subroutine t_ctl_data_mhd_normalize::read_coef_term_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(equations_control), intent(inout) eqs_ctl, type(buffer_for_control), intent(inout) c_buf)
Definition at line 185 of file t_ctl_data_mhd_normalize.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_dsc_diff_adv, hd_induction, hd_momentum, hd_thermal, t_read_control_elements::load_one_line_from_control(), t_ctl_data_termal_norm::read_composition_eq_ctl(), t_ctl_data_induct_norm::read_induction_ctl(), t_ctl_data_momentum_norm::read_momentum_ctl(), and t_ctl_data_termal_norm::read_thermal_ctl().
Referenced by t_ctl_data_mhd_model::read_sph_mhd_model().
read_dimless_ctl()
subroutine t_ctl_data_mhd_normalize::read_dimless_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(dimless_control), intent(inout) dless_ctl, type(buffer_for_control), intent(inout) c_buf)
Definition at line 160 of file t_ctl_data_mhd_normalize.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_dimless, t_read_control_elements::load_one_line_from_control(), and t_control_array_charareal::read_control_array_c_r().
Referenced by t_ctl_data_mhd_model::read_sph_mhd_model().
Variable Documentation
hd_dimless
character(len=kchara), parameter, private t_ctl_data_mhd_normalize::hd_dimless = 'dimless_ctl' private
Definition at line 140 of file t_ctl_data_mhd_normalize.f90.
Referenced by read_dimless_ctl().
hd_dsc_diff_adv
character(len=kchara), parameter, private t_ctl_data_mhd_normalize::hd_dsc_diff_adv = 'composition' private
Definition at line 146 of file t_ctl_data_mhd_normalize.f90.
Referenced by read_coef_term_ctl().
hd_induction
character(len=kchara), parameter, private t_ctl_data_mhd_normalize::hd_induction = 'induction' private
Definition at line 148 of file t_ctl_data_mhd_normalize.f90.
Referenced by read_coef_term_ctl().
hd_momentum
character(len=kchara), parameter, private t_ctl_data_mhd_normalize::hd_momentum = 'momentum' private
Definition at line 144 of file t_ctl_data_mhd_normalize.f90.
Referenced by read_coef_term_ctl().
hd_thermal
character(len=kchara), parameter, private t_ctl_data_mhd_normalize::hd_thermal = 'thermal' private
Definition at line 145 of file t_ctl_data_mhd_normalize.f90.
Referenced by read_coef_term_ctl().