CALYPSO: set_control_platform_data Module Reference
set_control_platform_data Module Reference
Functions/Subroutines
subroutine turn_off_debug_flag_by_ctl (id_rank, plt)
subroutine set_control_smp_def (id_rank, plt)
subroutine set_control_mesh_def (plt, mesh_file)
subroutine set_control_sph_mesh (plt, Fmesh_ctl, sph_file_param, mesh_file, sph_file_IO, FEM_mesh_flags)
subroutine set_fem_mesh_switch_4_sph (Fmesh_ctl, iflag_access_FEM)
subroutine set_fem_surface_output_flag (Fmesh_ctl, iflag_output_SURF)
subroutine set_fem_viewer_output_flag (Fmesh_ctl, iflag_output_VMESH)
subroutine set_control_restart_file_def (plt, file_IO)
subroutine set_control_mesh_file_def (default_prefix, plt_ctl, mesh_file)
subroutine set_file_control_params (default_prefix, file_prefix_ctl, file_format_ctl, file_params)
subroutine set_parallel_file_ctl_params (default_prefix, file_prefix_ctl, file_format_ctl, file_params)
Variables
character(len=kchara), parameter default_sph_prefix = 'in'
character(len=kchara), parameter default_rst_prefix = 'rst'
Function/Subroutine Documentation
set_control_mesh_def()
subroutine set_control_platform_data::set_control_mesh_def (type(platform_data_control), intent(in) plt, type(field_io_params), intent(inout) mesh_file)
Definition at line 119 of file set_control_platform_data.F90.
References m_default_file_prefix::def_mesh_file_head, and set_parallel_file_ctl_params().
Referenced by load_mesh_and_field_4_viz::set_control_params_4_viz(), and set_control_sph_mesh().
set_control_mesh_file_def()
subroutine set_control_platform_data::set_control_mesh_file_def (character(len=kchara), intent(in) default_prefix, type(platform_data_control), intent(in) plt_ctl, type(field_io_params), intent(inout) mesh_file)
Definition at line 264 of file set_control_platform_data.F90.
References set_file_control_params().
Referenced by t_mhd_file_parameter::set_control_org_sph_files().
set_control_restart_file_def()
subroutine set_control_platform_data::set_control_restart_file_def (type(platform_data_control), intent(in) plt, type(field_io_params), intent(inout) file_IO)
Definition at line 246 of file set_control_platform_data.F90.
References default_rst_prefix, and set_parallel_file_ctl_params().
Referenced by set_control_sph_mhd::set_control_4_sph_mhd().
set_control_smp_def()
subroutine set_control_platform_data::set_control_smp_def (integer, intent(in) id_rank, type(platform_data_control), intent(in) plt)
Definition at line 88 of file set_control_platform_data.F90.
References m_machine_parameter::np_smp.
Referenced by set_control_sph_mhd::set_control_4_sph_mhd(), and load_mesh_and_field_4_viz::set_control_params_4_viz().
set_control_sph_mesh()
subroutine set_control_platform_data::set_control_sph_mesh (type(platform_data_control), intent(in) plt, type(fem_mesh_control), intent(in) Fmesh_ctl, type(field_io_params), intent(inout) sph_file_param, type(field_io_params), intent(inout) mesh_file, type(field_io_params), intent(inout) sph_file_IO, type(fem_file_io_flags), intent(inout) FEM_mesh_flags)
Definition at line 135 of file set_control_platform_data.F90.
References m_file_format_switch::choose_para_file_format(), t_file_io_parameter::copy_mesh_format_and_prefix(), default_sph_prefix, set_control_mesh_def(), set_fem_mesh_switch_4_sph(), set_fem_surface_output_flag(), and set_fem_viewer_output_flag().
Referenced by t_ctl_params_gen_sph_shell::set_control_4_shell_files(), and set_control_sph_mhd::set_control_4_sph_mhd().
set_fem_mesh_switch_4_sph()
subroutine set_control_platform_data::set_fem_mesh_switch_4_sph (type(fem_mesh_control), intent(in) Fmesh_ctl, integer(kind = kint), intent(inout) iflag_access_FEM)
Definition at line 187 of file set_control_platform_data.F90.
References skip_comment_f::yes_flag().
Referenced by set_control_sph_mesh().
set_fem_surface_output_flag()
subroutine set_control_platform_data::set_fem_surface_output_flag (type(fem_mesh_control), intent(in) Fmesh_ctl, integer(kind = kint), intent(inout) iflag_output_SURF)
Definition at line 206 of file set_control_platform_data.F90.
References skip_comment_f::yes_flag().
Referenced by set_control_sph_mesh().
set_fem_viewer_output_flag()
subroutine set_control_platform_data::set_fem_viewer_output_flag (type(fem_mesh_control), intent(in) Fmesh_ctl, integer(kind = kint), intent(inout) iflag_output_VMESH)
Definition at line 226 of file set_control_platform_data.F90.
References skip_comment_f::yes_flag().
Referenced by set_control_sph_mesh().
set_file_control_params()
subroutine set_control_platform_data::set_file_control_params (character(len = kchara), intent(in) default_prefix, type(read_character_item), intent(in) file_prefix_ctl, type(read_character_item), intent(in) file_format_ctl, type(field_io_params), intent(inout) file_params)
Definition at line 280 of file set_control_platform_data.F90.
References m_file_format_switch::choose_file_format().
Referenced by set_control_mesh_file_def().
set_parallel_file_ctl_params()
subroutine set_control_platform_data::set_parallel_file_ctl_params (character(len = kchara), intent(in) default_prefix, type(read_character_item), intent(in) file_prefix_ctl, type(read_character_item), intent(in) file_format_ctl, type(field_io_params), intent(inout) file_params)
Definition at line 306 of file set_control_platform_data.F90.
References m_file_format_switch::choose_para_file_format().
Referenced by t_control_param_assemble::set_assemble_rst_file_param(), set_control_newsph::set_control_4_newsph(), set_control_mesh_def(), and set_control_restart_file_def().
turn_off_debug_flag_by_ctl()
subroutine set_control_platform_data::turn_off_debug_flag_by_ctl (integer, intent(in) id_rank, type(platform_data_control), intent(in) plt)
Definition at line 61 of file set_control_platform_data.F90.
References skip_comment_f::cmp_no_case(), m_machine_parameter::i_debug, m_machine_parameter::iflag_debug, m_machine_parameter::iflag_full_msg, m_machine_parameter::iflag_minimum_msg, m_machine_parameter::iflag_routine_msg, skip_comment_f::no_flag(), and skip_comment_f::yes_flag().
Referenced by analyzer_test_sph::init_test_sph(), t_ctl_params_gen_sph_shell::set_control_4_shell_files(), set_control_sph_mhd::set_control_4_sph_mhd(), and load_mesh_and_field_4_viz::set_control_params_4_viz().
Variable Documentation
default_rst_prefix
character(len=kchara), parameter set_control_platform_data::default_rst_prefix = 'rst'
Definition at line 53 of file set_control_platform_data.F90.
Referenced by set_control_restart_file_def().
default_sph_prefix
character(len=kchara), parameter set_control_platform_data::default_sph_prefix = 'in'
Definition at line 52 of file set_control_platform_data.F90.
Referenced by set_control_sph_mesh().