CALYPSO: add_nodal_fields_ctl Module Reference
add_nodal_fields_ctl Module Reference
Add require field name.
Functions/Subroutines
logical function check_field_list_ctl (field, field_ctl)
subroutine add_phys_name_ctl (field, field_ctl)
Detailed Description
Add require field name.
      logical function check_field_list_ctl(field, field_ctl)
      subroutine add_phys_name_ctl(field, field_ctl)
        type(field_def), intent(in) :: field
        type(ctl_array_c3), intent(inout) :: field_ctl
Function/Subroutine Documentation
add_phys_name_ctl()
subroutine add_nodal_fields_ctl::add_phys_name_ctl (type(field_def), intent(in) field, type(ctl_array_c3), intent(inout) field_ctl)
Definition at line 53 of file add_nodal_fields_ctl.f90.
References t_control_array_character3::append_control_array_c3(), check_field_list_ctl(), and m_machine_parameter::iflag_debug.
Referenced by add_nodal_fields_4_mhd::add_ctl_4_forces(), add_nodal_fields_4_mhd::add_ctl_4_ref_temp(), add_nodal_fields_4_mhd::add_data_4_check_step(), add_nodal_fields_4_mhd::add_data_4_previous_step(), check_base_field::add_field_ctl_4_base_field(), check_workarea_4_explicit::add_field_ctl_4_check_evo(), check_base_field::add_field_ctl_4_diff_vector(), check_base_forces::add_field_ctl_4_diffusions(), check_base_forces::add_field_ctl_4_div_forces(), check_energy_fluxes::add_field_ctl_4_ene_flux(), add_nodal_fields_4_mhd::add_field_ctl_4_evo_magne(), check_base_forces::add_field_ctl_4_field_products(), check_base_forces::add_field_ctl_4_forces(), check_base_field::add_field_ctl_4_grad_field(), check_base_forces::add_field_ctl_4_rot_forces(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), and add_nodal_fields_4_mhd::add_work_area_4_potentials().
check_field_list_ctl()
logical function add_nodal_fields_ctl::check_field_list_ctl (type(field_def), intent(in) field, type(ctl_array_c3), intent(in) field_ctl)
Definition at line 31 of file add_nodal_fields_ctl.f90.
Referenced by check_base_field::add_field_ctl_4_base_field(), check_workarea_4_explicit::add_field_ctl_4_check_evo(), check_base_field::add_field_ctl_4_diff_vector(), check_base_forces::add_field_ctl_4_diffusions(), check_base_forces::add_field_ctl_4_div_forces(), check_energy_fluxes::add_field_ctl_4_ene_flux(), add_nodal_fields_4_mhd::add_field_ctl_4_evo_magne(), check_base_forces::add_field_ctl_4_field_products(), check_base_forces::add_field_ctl_4_forces(), check_base_field::add_field_ctl_4_grad_field(), check_base_forces::add_field_ctl_4_rot_forces(), and add_phys_name_ctl().