CALYPSO: t_phys_data Module Reference
t_phys_data Module Reference
Data Types
type phys_data
Structure for field data.
Functions/Subroutines
subroutine alloc_phys_name_type (fld)
subroutine alloc_phys_data_type (num, fld)
subroutine dealloc_phys_name_type (fld)
subroutine dealloc_phys_data_type (fld)
subroutine append_field_name_list (field_name, numdir, flag_viz, flag_monitor, iorder_eletype, fld)
subroutine copy_field_name_type (org_fld, new_fld)
subroutine copy_field_data_type (org_fld, new_fld)
subroutine, private add_field_name_list_4_viz (field_name, numdir, flag_monitor, iorder_eletype, org_fld, new_fld)
subroutine, private add_field_name_list_noviz (field_name, numdir, flag_monitor, iorder_eletype, org_fld, new_fld)
integer(kind=kint) function field_id_by_address (fld, i_ref)
character(len=kchara) function field_name_by_address (fld, i_ref)
integer(kind=kint) function field_comp_by_address (fld, i_ref)
subroutine check_all_field_data (id_rank, fld)
subroutine check_nodal_field_name (id_output, fld)
subroutine check_nodal_data (id_output, fld, numdir, i_field)
Function/Subroutine Documentation
add_field_name_list_4_viz()
subroutine, private t_phys_data::add_field_name_list_4_viz (character(len = kchara), intent(in) field_name, integer(kind = kint), intent(in) numdir, logical, intent(in) flag_monitor, integer(kind = kint), intent(in) iorder_eletype, type(phys_data), intent(in) org_fld, type(phys_data), intent(inout) new_fld) private
Definition at line 242 of file t_phys_data.f90.
Referenced by append_field_name_list().
add_field_name_list_noviz()
subroutine, private t_phys_data::add_field_name_list_noviz (character(len = kchara), intent(in) field_name, integer(kind = kint), intent(in) numdir, logical, intent(in) flag_monitor, integer(kind = kint), intent(in) iorder_eletype, type(phys_data), intent(in) org_fld, type(phys_data), intent(inout) new_fld) private
Definition at line 286 of file t_phys_data.f90.
Referenced by append_field_name_list().
alloc_phys_data_type()
subroutine t_phys_data::alloc_phys_data_type (integer(kind = kint), intent(in) num, type(phys_data), intent(inout) fld)
Definition at line 111 of file t_phys_data.f90.
Referenced by t_circle_transform::alloc_circle_field(), set_ucd_data_to_type::alloc_phys_data_type_by_output(), t_sph_spectr_data::alloc_phys_rj_data_t(), copy_field_data_type(), set_control_field_data::init_field_data(), and share_field_data::share_each_field_data().
alloc_phys_name_type()
subroutine t_phys_data::alloc_phys_name_type (type(phys_data), intent(inout) fld)
Definition at line 88 of file t_phys_data.f90.
Referenced by set_ucd_data_to_type::alloc_phys_name_type_by_output(), t_sph_spectr_data::alloc_phys_rj_name_t(), append_field_name_list(), copy_field_name_type(), set_nodal_field_name::ordering_field_by_comp_viz(), set_nodal_field_name::ordering_field_by_viz(), input_control_dynamobench::set_ctl_params_dynamobench(), set_psf_iso_control::set_iso_control(), set_psf_iso_control::set_psf_control(), and share_field_data::share_phys_field_names().
append_field_name_list()
subroutine t_phys_data::append_field_name_list (character(len = kchara), intent(in) field_name, integer(kind = kint), intent(in) numdir, logical, intent(in) flag_viz, logical, intent(in) flag_monitor, integer(kind = kint), intent(in) iorder_eletype, type(phys_data), intent(inout) fld)
Definition at line 154 of file t_phys_data.f90.
References add_field_name_list_4_viz(), add_field_name_list_noviz(), alloc_phys_name_type(), copy_field_name_type(), and dealloc_phys_name_type().
Referenced by set_nodal_field_name::set_scalar_field_name(), set_nodal_field_name::set_tensor_field_name(), and set_nodal_field_name::set_vector_field_name().
check_all_field_data()
subroutine t_phys_data::check_all_field_data (integer, intent(in) id_rank, type(phys_data), intent(in) fld)
Definition at line 381 of file t_phys_data.f90.
References check_nodal_data(), and check_nodal_field_name().
check_nodal_data()
subroutine t_phys_data::check_nodal_data (integer(kind = kint), intent(in) id_output, type(phys_data), intent(in) fld, integer(kind = kint), intent(in) numdir, integer(kind = kint), intent(in) i_field)
Definition at line 419 of file t_phys_data.f90.
Referenced by check_all_field_data(), and t_sph_spectr_data::check_rj_spectr_data_t().
check_nodal_field_name()
subroutine t_phys_data::check_nodal_field_name (integer(kind = kint), intent(in) id_output, type(phys_data), intent(in) fld)
Definition at line 398 of file t_phys_data.f90.
Referenced by check_all_field_data(), t_sph_spectr_data::check_rj_spectr_data_t(), t_sph_spectr_data::check_rj_spectr_name_t(), set_control_field_data::s_set_control_field_data(), and set_control_field_data::set_control_field_by_comp_viz().
copy_field_data_type()
subroutine t_phys_data::copy_field_data_type (type(phys_data), intent(in) org_fld, type(phys_data), intent(inout) new_fld)
Definition at line 224 of file t_phys_data.f90.
References alloc_phys_data_type().
copy_field_name_type()
subroutine t_phys_data::copy_field_name_type (type(phys_data), intent(in) org_fld, type(phys_data), intent(inout) new_fld)
Definition at line 195 of file t_phys_data.f90.
References alloc_phys_name_type().
Referenced by append_field_name_list().
dealloc_phys_data_type()
subroutine t_phys_data::dealloc_phys_data_type (type(phys_data), intent(inout) fld)
Definition at line 142 of file t_phys_data.f90.
Referenced by t_circle_transform::dealloc_circle_field(), and t_sph_spectr_data::dealloc_phys_rj_name_t().
dealloc_phys_name_type()
subroutine t_phys_data::dealloc_phys_name_type (type(phys_data), intent(inout) fld)
Definition at line 130 of file t_phys_data.f90.
Referenced by append_field_name_list(), t_circle_transform::dealloc_circle_field(), and t_sph_spectr_data::dealloc_phys_rj_name_t().
field_comp_by_address()
integer(kind=kint) function t_phys_data::field_comp_by_address (type(phys_data), intent(in) fld, integer(kind = kint), intent(in) i_ref)
Definition at line 361 of file t_phys_data.f90.
References field_id_by_address().
field_id_by_address()
integer(kind = kint) function t_phys_data::field_id_by_address (type(phys_data), intent(in) fld, integer(kind = kint), intent(in) i_ref)
Definition at line 324 of file t_phys_data.f90.
Referenced by add_field_to_sph_trans_list::add_field_4_sph_trns_by_pol(), add_field_to_sph_trans_list::add_field_name_4_sph_trns_snap(), add_field_to_sph_trans_list::add_scalar_4_sph_trns_by_pol(), add_field_to_sph_trans_list::add_scalar_4_sph_trns_snap(), field_comp_by_address(), and field_name_by_address().
field_name_by_address()
character(len=kchara) function t_phys_data::field_name_by_address (type(phys_data), intent(in) fld, integer(kind = kint), intent(in) i_ref)
Definition at line 343 of file t_phys_data.f90.
References field_id_by_address().
Referenced by check_dependency_for_mhd::check_missing_field_w_msg().