CALYPSO: cal_vorticity_terms_adams Module Reference
cal_vorticity_terms_adams Module Reference
Evoluve the vorticity equation by explicit scheme.
Functions/Subroutines
subroutine cal_vorticity_eq_adams (sph_rj, fl_prop, sph_bc_U, ipol_base, ipol_exp, ipol_dif, dt, nnod_rj, ntot_phys_rj, d_rj)
subroutine cal_vorticity_eq_euler (sph_rj, fl_prop, sph_bc_U, ipol_base, ipol_exp, ipol_dif, dt, nnod_rj, ntot_phys_rj, d_rj)
subroutine set_mhd_terms_to_force (ipol_exp, ipol_rot_frc, is_rot_buo, nnod_rj, ntot_phys_rj, d_rj)
subroutine set_rot_cv_terms_to_force (ipol_exp, ipol_rot_frc, is_rot_buo, nnod_rj, ntot_phys_rj, d_rj)
subroutine add_rot_advection_to_force (is_exp, is_rot_inertia, nnod_rj, ntot_phys_rj, d_rj)
subroutine add_buoyancy_to_vort_force (is_exp, is_rot_buo, nnod_rj, ntot_phys_rj, d_rj)
subroutine add_each_force_to_rot_forces (is_exp, is_rot_force, nnod_rj, ntot_phys_rj, d_rj)
subroutine set_ini_adams_inertia (fl_prop, ipol_exp, nnod_rj, ntot_phys_rj, d_rj)
Detailed Description
Evoluve the vorticity equation by explicit scheme.
      subroutine cal_vorticity_eq_adams(sph_rj, fl_prop, sph_bc_U,    &
     &          ipol_base, ipol_exp, ipol_dif,                        &
     &          dt, nnod_rj, ntot_phys_rj, d_rj)
      subroutine cal_vorticity_eq_euler(sph_rj, fl_prop, sph_bc_U,    &
     &          ipol_base, ipol_exp, ipol_dif,                        &
     &          dt, nnod_rj, ntot_phys_rj, d_rj)
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(fluid_property), intent(in) :: fl_prop
        type(sph_boundary_type), intent(in) :: sph_bc_U
        type(base_field_address), intent(in) :: ipol_base
        type(explicit_term_address), intent(in) :: ipol_exp
        type(diffusion_address), intent(in) :: ipol_dif
      subroutine set_MHD_terms_to_force                               &
     &         (ipol_exp, ipol_rot_frc, is_rot_buo,                   &
     &          nnod_rj, ntot_phys_rj, d_rj)
      subroutine set_rot_cv_terms_to_force                            &
     &         (ipol_exp, ipol_rot_frc, is_rot_buo,                   &
     &          nnod_rj, ntot_phys_rj, d_rj)
        type(explicit_term_address), intent(in) :: ipol_exp
        type(base_force_address), intent(in) :: ipol_rot_frc
      subroutine add_rot_advection_to_force                           &
     &         (is_exp, is_rot_inertia, nnod_rj, ntot_phys_rj, d_rj)
      subroutine add_buoyancy_to_vort_force                           &
     &         (is_exp, is_rot_buo, nnod_rj, ntot_phys_rj, d_rj)
      subroutine add_each_force_to_rot_forces                         &
     &         (is_exp, is_rot_force, nnod_rj, ntot_phys_rj, d_rj)
      subroutine set_ini_adams_inertia                                &
     &         (fl_prop, ipol_exp, nnod_rj, ntot_phys_rj, d_rj)
        type(fluid_property), intent(in) :: fl_prop
        type(explicit_term_address), intent(in) :: ipol_exp
Parameters
kr_in Radial ID for inner boundary
kr_out Radial ID for outer boundary
Parameters
is_rot_buo Spectr field address for toroidal curl of buodyancy
Parameters
ntot_phys_rj Total number of components
d_rj Spectrum data
Function/Subroutine Documentation
add_buoyancy_to_vort_force()
subroutine cal_vorticity_terms_adams::add_buoyancy_to_vort_force (integer(kind = kint), intent(in) is_exp, integer(kind = kint), intent(in) is_rot_buo, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 234 of file cal_vorticity_terms_adams.f90.
Referenced by sum_rotation_of_forces::licv_forces_to_explicit(), and sum_rotation_of_forces::sum_forces_to_explicit().
add_each_force_to_rot_forces()
subroutine cal_vorticity_terms_adams::add_each_force_to_rot_forces (integer(kind = kint), intent(in) is_exp, integer(kind = kint), intent(in) is_rot_force, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 250 of file cal_vorticity_terms_adams.f90.
Referenced by sum_rotation_of_forces::licv_forces_to_explicit(), and sum_rotation_of_forces::sum_forces_to_explicit().
add_rot_advection_to_force()
subroutine cal_vorticity_terms_adams::add_rot_advection_to_force (integer(kind = kint), intent(in) is_exp, integer(kind = kint), intent(in) is_rot_inertia, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 215 of file cal_vorticity_terms_adams.f90.
Referenced by sum_rotation_of_forces::sum_forces_to_explicit().
cal_vorticity_eq_adams()
subroutine cal_vorticity_terms_adams::cal_vorticity_eq_adams (type(sph_rj_grid), intent(in) sph_rj, type(fluid_property), intent(in) fl_prop, type(sph_boundary_type), intent(in) sph_bc_U, type(base_field_address), intent(in) ipol_base, type(explicit_term_address), intent(in) ipol_exp, type(diffusion_address), intent(in) ipol_dif, real(kind = kreal), intent(in) dt, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 75 of file cal_vorticity_terms_adams.f90.
References m_t_step_parameter::adam_0, m_t_step_parameter::adam_1, and t_physical_property::id_no_evolution.
Referenced by cal_momentum_eq_explicit::cal_explicit_sph_adams().
cal_vorticity_eq_euler()
subroutine cal_vorticity_terms_adams::cal_vorticity_eq_euler (type(sph_rj_grid), intent(in) sph_rj, type(fluid_property), intent(in) fl_prop, type(sph_boundary_type), intent(in) sph_bc_U, type(base_field_address), intent(in) ipol_base, type(explicit_term_address), intent(in) ipol_exp, type(diffusion_address), intent(in) ipol_dif, real(kind = kreal), intent(in) dt, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 117 of file cal_vorticity_terms_adams.f90.
References t_physical_property::id_no_evolution.
Referenced by cal_momentum_eq_explicit::cal_explicit_sph_euler().
set_ini_adams_inertia()
subroutine cal_vorticity_terms_adams::set_ini_adams_inertia (type(fluid_property), intent(in) fl_prop, type(explicit_term_address), intent(in) ipol_exp, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 270 of file cal_vorticity_terms_adams.f90.
References t_physical_property::id_no_evolution.
Referenced by cal_momentum_eq_explicit::cal_first_prev_step_adams().
set_mhd_terms_to_force()
subroutine cal_vorticity_terms_adams::set_mhd_terms_to_force (type(explicit_term_address), intent(in) ipol_exp, type(base_force_address), intent(in) ipol_rot_frc, integer(kind = kint), intent(in) is_rot_buo, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 154 of file cal_vorticity_terms_adams.f90.
Referenced by sum_rotation_of_forces::sum_forces_to_explicit().
set_rot_cv_terms_to_force()
subroutine cal_vorticity_terms_adams::set_rot_cv_terms_to_force (type(explicit_term_address), intent(in) ipol_exp, type(base_force_address), intent(in) ipol_rot_frc, integer(kind = kint), intent(in) is_rot_buo, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 185 of file cal_vorticity_terms_adams.f90.
Referenced by sum_rotation_of_forces::sum_forces_to_explicit().