CALYPSO: mpi_binary_data_io Module Reference
mpi_binary_data_io Module Reference
Output gzipped merged binary field file using MPI-IO.
Functions/Subroutines
subroutine mpi_write_one_integer_b (IO_param, int_dat)
subroutine mpi_write_integer_stack_b (IO_param, num, istack)
subroutine mpi_write_int_vector_b (IO_param, num, int_dat)
subroutine mpi_write_int8_vector_b (IO_param, num, int8_dat)
subroutine mpi_write_1d_vector_b (IO_param, num, real_dat)
subroutine mpi_write_2d_vector_b (IO_param, n1, n2, real_dat)
subroutine mpi_read_one_integer_b (IO_param, int_dat)
subroutine mpi_read_integer_stack_b (IO_param, num, istack, ntot)
subroutine mpi_read_int_vector_b (IO_param, num, int_dat)
subroutine mpi_read_int8_vector_b (IO_param, num, int8_dat)
subroutine mpi_read_1d_vector_b (IO_param, num, real_dat)
subroutine mpi_read_2d_vector_b (IO_param, n1, n2, real_dat)
Detailed Description
Output gzipped merged binary field file using MPI-IO.
      subroutine mpi_write_one_integer_b(IO_param, int_dat)
      subroutine mpi_write_integer_stack_b(IO_param, num, istack)
        Substitution of gz_write_integer_stack_b
      subroutine mpi_write_int_vector_b(IO_param, num, int_dat)
        Substitution of gz_write_mul_integer_b
      subroutine mpi_write_int8_vector_b(IO_param, num, int8_dat)
        Substitution of gz_write_mul_int8_b
      subroutine mpi_write_1d_vector_b(IO_param, num, real_dat)
        Substitution of gz_write_1d_vector_b
      subroutine mpi_write_2d_vector_b(IO_param, n1, n2, real_dat)
        Substitution of gz_write_2d_vector_b
      subroutine mpi_read_one_integer_b(IO_param, int_dat)
      subroutine mpi_read_integer_stack_b(IO_param, num, istack, ntot)
        Substittion of  gz_read_integer_stack_b
      subroutine mpi_read_int_vector_b(IO_param, num, int_dat)
        Substitution of gz_read_mul_integer_b
      subroutine mpi_read_int8_vector_b(IO_param, num, int8_dat)
        Substitution of gz_read_mul_int8_b
      subroutine mpi_read_1d_vector_b(IO_param, num, real_dat)
        Substitution of gz_read_1d_vector_b
      subroutine mpi_read_2d_vector_b(IO_param, n1, n2, real_dat)
        Substitution of gz_read_2d_vector_b
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
Function/Subroutine Documentation
mpi_read_1d_vector_b()
subroutine mpi_binary_data_io::mpi_read_1d_vector_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint_gl), intent(in) num, real(kind = kreal), dimension(num), intent(inout) real_dat)
Definition at line 299 of file MPI_binary_data_IO.f90.
References mpi_binary_head_io::mpi_read_i8stack_head_b(), and m_calypso_mpi_io::mpi_read_real_b().
Referenced by mpi_read_2d_vector_b(), mpi_sph_gl_1d_idx_io_b::mpi_read_rj_gl_1d_table_b(), and mpi_sph_gl_1d_idx_io_b::mpi_read_rtp_gl_1d_table_b().
mpi_read_2d_vector_b()
subroutine mpi_binary_data_io::mpi_read_2d_vector_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint_gl), intent(in) n1, integer(kind = kint), intent(in) n2, real(kind = kreal), dimension(n1,n2), intent(inout) real_dat)
Definition at line 334 of file MPI_binary_data_IO.f90.
References mpi_read_1d_vector_b(), and t_calypso_mpi_io_param::mul_istack_4_parallell_vect().
Referenced by mpi_node_geometry_io_b::mpi_read_geometry_info_b(), mpi_node_geometry_io_b::mpi_read_vect_in_ele_b(), field_file_mpi_io_b::read_alloc_stp_fld_file_mpi_b(), ucd_field_mpi_io_b::read_alloc_ucd_fld_file_mpi_b(), field_file_mpi_io_b::read_step_field_file_mpi_b(), and ucd_field_mpi_io_b::read_ucd_field_file_mpi_b().
mpi_read_int8_vector_b()
subroutine mpi_binary_data_io::mpi_read_int8_vector_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint_gl), intent(in) num, integer(kind = kint_gl), dimension(num), intent(inout) int8_dat)
Definition at line 264 of file MPI_binary_data_IO.f90.
References mpi_binary_head_io::mpi_read_i8stack_head_b(), and m_calypso_mpi_io::mpi_read_int8_b().
Referenced by mpi_element_connect_io_b::mpi_read_element_info_b(), mpi_node_geometry_io_b::mpi_read_geometry_info_b(), mpi_spherical_model_io_b::mpi_read_gl_nodes_sph_b(), mpi_read_int_vector_b(), and mpi_read_one_integer_b().
mpi_read_int_vector_b()
subroutine mpi_binary_data_io::mpi_read_int_vector_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint_gl), intent(in) num, integer(kind = kint), dimension(num), intent(inout) int_dat)
Definition at line 244 of file MPI_binary_data_IO.f90.
References transfer_to_long_integers::alloc_1d_i8array(), transfer_to_long_integers::dup_to_short_array(), and mpi_read_int8_vector_b().
Referenced by mpi_domain_data_io_b::mpi_read_domain_info_b(), mpi_element_connect_io_b::mpi_read_edge_4_element_b(), mpi_element_connect_io_b::mpi_read_element_info_b(), mpi_domain_data_io_b::mpi_read_export_data_b(), mpi_spherical_model_io_b::mpi_read_gl_nodes_sph_b(), mpi_groups_io_b::mpi_read_group_data_b(), mpi_domain_data_io_b::mpi_read_import_data_b(), mpi_read_integer_stack_b(), mpi_spherical_model_io_b::mpi_read_rank_4_sph_b(), mpi_sph_gl_1d_idx_io_b::mpi_read_rj_gl_1d_table_b(), mpi_sph_gl_1d_idx_io_b::mpi_read_rtp_gl_1d_table_b(), mpi_groups_io_b::mpi_read_surf_grp_data_b(), and mpi_element_connect_io_b::mpi_read_surface_4_element_b().
mpi_read_integer_stack_b()
subroutine mpi_binary_data_io::mpi_read_integer_stack_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint_gl), intent(in) num, integer(kind = kint), dimension(0:num), intent(inout) istack, integer(kind = kint), intent(inout) ntot)
Definition at line 225 of file MPI_binary_data_IO.f90.
References mpi_read_int_vector_b().
Referenced by mpi_domain_data_io_b::mpi_read_export_data_b(), mpi_groups_io_b::mpi_read_group_data_b(), mpi_domain_data_io_b::mpi_read_import_data_b(), and mpi_groups_io_b::mpi_read_surf_grp_data_b().
mpi_read_one_integer_b()
subroutine mpi_binary_data_io::mpi_read_one_integer_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint), intent(inout) int_dat)
Definition at line 204 of file MPI_binary_data_IO.f90.
References transfer_to_long_integers::alloc_1d_i8array(), transfer_to_long_integers::cast_long(), transfer_to_long_integers::dup_to_short_array(), and mpi_read_int8_vector_b().
Referenced by mpi_domain_data_io_b::mpi_read_domain_info_b(), mpi_element_connect_io_b::mpi_read_edge_4_element_b(), mpi_spherical_model_io_b::mpi_read_gl_nodes_sph_b(), mpi_element_connect_io_b::mpi_read_number_of_element_b(), mpi_node_geometry_io_b::mpi_read_number_of_node_b(), and mpi_element_connect_io_b::mpi_read_surface_4_element_b().
mpi_write_1d_vector_b()
subroutine mpi_binary_data_io::mpi_write_1d_vector_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint_gl), intent(in) num, real(kind = kreal), dimension(num), intent(in) real_dat)
Definition at line 153 of file MPI_binary_data_IO.f90.
References m_precision::kreal, mpi_binary_head_io::mpi_write_i8stack_head_b(), and m_calypso_mpi_io::mpi_write_real_b().
Referenced by mpi_node_geometry_io_b::mpi_read_scl_in_ele_b(), mpi_write_2d_vector_b(), mpi_sph_gl_1d_idx_io_b::mpi_write_rj_gl_1d_table_b(), mpi_sph_gl_1d_idx_io_b::mpi_write_rtp_gl_1d_table_b(), mpi_node_geometry_io_b::mpi_write_scl_in_ele_b(), ucd_file_mpi_io::write_ucd_data_mpi_b(), and ucd_file_mpi_io::write_ucd_mesh_data_mpi_b().
mpi_write_2d_vector_b()
subroutine mpi_binary_data_io::mpi_write_2d_vector_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint_gl), intent(in) n1, integer(kind=kint), intent(in) n2, real(kind = kreal), dimension(n1,n2), intent(in) real_dat)
Definition at line 185 of file MPI_binary_data_IO.f90.
References mpi_write_1d_vector_b(), and t_calypso_mpi_io_param::mul_istack_4_parallell_vect().
Referenced by mpi_node_geometry_io_b::mpi_write_geometry_info_b(), mpi_node_geometry_io_b::mpi_write_vect_in_ele_b(), and field_block_mpi_io_b::write_field_data_mpi_b().
mpi_write_int8_vector_b()
subroutine mpi_binary_data_io::mpi_write_int8_vector_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint_gl), intent(in) num, integer(kind = kint_gl), dimension(num), intent(in) int8_dat)
Definition at line 122 of file MPI_binary_data_IO.f90.
References m_precision::kint_gl, mpi_binary_head_io::mpi_write_i8stack_head_b(), and m_calypso_mpi_io::mpi_write_int8_b().
Referenced by mpi_element_connect_io_b::mpi_write_element_info_b(), mpi_node_geometry_io_b::mpi_write_geometry_info_b(), mpi_spherical_model_io_b::mpi_write_gl_nodes_sph_b(), mpi_write_int_vector_b(), mpi_write_one_integer_b(), ucd_file_mpi_io::write_ucd_data_mpi_b(), and ucd_file_mpi_io::write_ucd_mesh_data_mpi_b().
mpi_write_int_vector_b()
subroutine mpi_binary_data_io::mpi_write_int_vector_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint_gl), intent(in) num, integer(kind = kint), dimension(num), intent(in) int_dat)
Definition at line 102 of file MPI_binary_data_IO.f90.
References transfer_to_long_integers::dealloc_1d_i8array(), transfer_to_long_integers::dup_from_short_array(), and mpi_write_int8_vector_b().
Referenced by mpi_domain_data_io_b::mpi_write_domain_info_b(), mpi_element_connect_io_b::mpi_write_edge_4_element_b(), mpi_element_connect_io_b::mpi_write_element_info_b(), mpi_domain_data_io_b::mpi_write_export_data_b(), mpi_spherical_model_io_b::mpi_write_gl_nodes_sph_b(), mpi_groups_io_b::mpi_write_grp_data_b(), mpi_domain_data_io_b::mpi_write_import_data_b(), mpi_write_integer_stack_b(), mpi_spherical_model_io_b::mpi_write_rank_4_sph_b(), mpi_sph_gl_1d_idx_io_b::mpi_write_rj_gl_1d_table_b(), mpi_sph_gl_1d_idx_io_b::mpi_write_rtp_gl_1d_table_b(), mpi_groups_io_b::mpi_write_surf_grp_data_b(), and mpi_element_connect_io_b::mpi_write_surface_4_element_b().
mpi_write_integer_stack_b()
subroutine mpi_binary_data_io::mpi_write_integer_stack_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint_gl), intent(in) num, integer(kind = kint), dimension(0:num), intent(in) istack)
Definition at line 85 of file MPI_binary_data_IO.f90.
References t_calypso_mpi_io_param::istack64_4_parallel_data(), and mpi_write_int_vector_b().
Referenced by mpi_domain_data_io_b::mpi_write_export_data_b(), mpi_groups_io_b::mpi_write_grp_data_b(), mpi_domain_data_io_b::mpi_write_import_data_b(), and mpi_groups_io_b::mpi_write_surf_grp_data_b().
mpi_write_one_integer_b()
subroutine mpi_binary_data_io::mpi_write_one_integer_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint), intent(in) int_dat)
Definition at line 59 of file MPI_binary_data_IO.f90.
References transfer_to_long_integers::cast_long(), transfer_to_long_integers::dealloc_1d_i8array(), transfer_to_long_integers::dup_from_short_array(), and mpi_write_int8_vector_b().
Referenced by mpi_domain_data_io_b::mpi_write_domain_info_b(), mpi_element_connect_io_b::mpi_write_edge_4_element_b(), mpi_element_connect_io_b::mpi_write_element_info_b(), mpi_spherical_model_io_b::mpi_write_gl_nodes_sph_b(), mpi_node_geometry_io_b::mpi_write_num_node_b(), and mpi_element_connect_io_b::mpi_write_surface_4_element_b().