CALYPSO: lubksb_357band Module Reference
lubksb_357band Module Reference
Solve 3, 5, or 7 band matriox after LU decomposition.
Functions/Subroutines
subroutine lubksb_3band (n, band_lu, i_pivot, x)
subroutine lubksb_5band (n, band_lu, i_pivot, x)
subroutine lubksb_7band (n, band_lu, i_pivot, x)
Detailed Description
Solve 3, 5, or 7 band matriox after LU decomposition.
  ---------------------------------------------------------------------
      SUBROUTINE lubksb_3band(n, band_lu, i_pivot, x)
      SUBROUTINE lubksb_5band(n, band_lu, i_pivot, x)
      SUBROUTINE lubksb_7band(n, band_lu, i_pivot, x)
c solve the set of n linear equations Ax=b. Here is a input,
c not at the matrix A but rather as its LU decompsition,
c determined by the routine ludcmp. i_pivot is input as the
c permutation vector returned by ludcmp. b(1:n) is input
c as the right-hand side vectror b, and returns with the
c solution vector x.
c a, n, np and i_pivot are not modified by this routine
c and be left in place for successive calls with different
c right hand sides b. This routine takes into account
c the possibility that b will begin with many zero elements,
c so it is efficient for use in matrix inversion.
      Data formt of band matrix
               | a(2,1)  a(1,2)  ........     0         0     |
               | a(3,1)  a(2,2)  ........     .         .     |
               |   0     a(3,2)  ........     .         .     |
    a(i,j)  =  |   .       0     ........     0         .     |
               | ...... a(3,k-1)  a(2,k)  a(1,k+1) .......... |
               |   .       .     ........  a(1,N-2)     0     |
               |   .       .     ........  a(2,N-2)  a(1,N-1) |
               |   0       0     ........  a(3,N-2)  a(2,N-1) |
   Original band matrix
      band_a(i-j+iband+1,j) = a(i,j)
      band_a(k,j) = a(k+j-iband-1,j)
   3-band matrix
      band_a(i-j+2,j) = a(i,j)
      band_a(k,j) = a(k+j-2,j)
   5-band matrix
      band_lu(i-j+3,j) = a(i,j)
      band_lu(k,j) = a(k+j-3,j)
   7-band matrix
      band_lu(i-j+4,j) = a(i,j)
      band_lu(k,j) = a(k+j-4,j)
   9-band matrix
      band_lu(i-j+5,j) = a(i,j)
      band_lu(k,j) = a(k+j-5,j)
  ---------------------------------------------------------------------
Function/Subroutine Documentation
lubksb_3band()
subroutine lubksb_357band::lubksb_3band (integer (kind = kint), intent(in) n, real(kind = kreal), dimension(5,n), intent(in) band_lu, integer (kind = kint), dimension(n), intent(in) i_pivot, real(kind = kreal), dimension(n), intent(inout) x)
Definition at line 69 of file lubksb_357band.f90.
Referenced by t_sph_center_matrix::lubksb_3band_ctr(), and t_sph_matrix::lubksb_3band_type().
lubksb_5band()
subroutine lubksb_357band::lubksb_5band (integer (kind = kint), intent(in) n, real(kind = kreal), dimension(9,n), intent(in) band_lu, integer (kind = kint), dimension(n), intent(in) i_pivot, real(kind = kreal), dimension(n), intent(inout) x)
Definition at line 103 of file lubksb_357band.f90.
Referenced by t_sph_center_matrix::lubksb_5band_ctr(), and t_sph_matrix::lubksb_5band_type().
lubksb_7band()
subroutine lubksb_357band::lubksb_7band (integer (kind = kint), intent(in) n, real(kind = kreal), dimension(13,n), intent(in) band_lu, integer (kind = kint), dimension(n), intent(in) i_pivot, real(kind = kreal), dimension(n), intent(inout) x)
Definition at line 152 of file lubksb_357band.f90.
Referenced by t_sph_center_matrix::lubksb_7band_ctr(), and t_sph_matrix::lubksb_7band_type().