CALYPSO: /home/takumi kera/calypso/src/programs/data_utilities/INITIAL_FIELD/main_sph_initial_fld.f90 File Reference
main_sph_initial_fld.f90 File Reference
program sph_meke_initial
Functions/Subroutines
program sph_meke_initial
Main program to generate initial field
Define initial field at const_sph_initial_spectr.f90.
Detailed Description
program sph_meke_initial
Author
H. Matsui
Date
Programmed by H. Okuda in 2000
Modified by H. Matsui in May, 2003 (ver 2.0)
Connect to vizs by H. Matsui in July 2006 (ver 2.0)
Definition in file main_sph_initial_fld.f90.
Function/Subroutine Documentation
sph_meke_initial()
program sph_meke_initial
Main program to generate initial field
Define initial field at const_sph_initial_spectr.f90.
Definition at line 12 of file main_sph_initial_fld.f90.
References calypso_mpi::calypso_mpi_finalize(), calypso_mpi::calypso_mpi_init(), and sph_analyzer_const_initial::initialize_const_sph_initial().