CALYPSO: set_control_newsph Module Reference
set_control_newsph Module Reference
Main loop to assemble spectr data.
Functions/Subroutines
subroutine bcast_ctl_param_newsph (asbl_param, sph_asbl)
subroutine set_control_4_newsph (mgd_ctl, asbl_param, sph_asbl, org_sph_maker, asbl_sph_maker)
Variables
character(len=kchara), parameter, private def_org_sph_head = 'mesh_org/in_rj'
character(len=kchara), parameter, private def_new_sph_head = 'mesh_new/in_rj'
Detailed Description
Main loop to assemble spectr data.
      subroutine bcast_ctl_param_newsph(asbl_param, sph_asbl)
      subroutine set_control_4_newsph(mgd_ctl, asbl_param,            &
     &          sph_asbl, org_sph_maker, asbl_sph_maker)
        type(control_data_4_merge), intent(in) :: mgd_ctl
        type(control_param_assemble), intent(inout) :: asbl_param
        type(spectr_data_4_assemble), intent(inout) :: sph_asbl
        type(sph_grid_maker_in_sim), intent(inout) :: org_sph_maker
        type(sph_grid_maker_in_sim), intent(inout) :: asbl_sph_maker
Function/Subroutine Documentation
bcast_ctl_param_newsph()
subroutine set_control_newsph::bcast_ctl_param_newsph (type(control_param_assemble), intent(inout) asbl_param, type(spectr_data_4_assemble), intent(inout) sph_asbl)
Definition at line 42 of file set_control_newsph.f90.
References bcast_file_io_parameter::bcast_field_io_parameter(), calypso_mpi_int::calypso_mpi_bcast_one_int(), and calypso_mpi_real::calypso_mpi_bcast_one_real().
set_control_4_newsph()
subroutine set_control_newsph::set_control_4_newsph (type(control_data_4_merge), intent(in) mgd_ctl, type(control_param_assemble), intent(inout) asbl_param, type(spectr_data_4_assemble), intent(inout) sph_asbl, type(sph_grid_maker_in_sim), intent(inout) org_sph_maker, type(sph_grid_maker_in_sim), intent(inout) asbl_sph_maker)
Definition at line 78 of file set_control_newsph.f90.
References calypso_mpi::calypso_mpi_abort(), def_new_sph_head, def_org_sph_head, m_file_format_switch::id_no_file, m_error_ids::ierr_file, m_error_ids::ierr_p_mpi, calypso_mpi::my_rank, calypso_mpi::nprocs, t_control_param_assemble::set_assemble_rst_file_param(), t_control_param_assemble::set_assemble_step_4_rst(), t_ctl_params_gen_sph_shell::set_control_4_shell_grids(), t_control_param_assemble::set_control_new_step(), t_control_param_assemble::set_delete_flag_4_assemble(), t_control_param_assemble::set_magnetic_ratio_4_assemble(), and set_control_platform_data::set_parallel_file_ctl_params().
Referenced by analyzer_assemble_sph::init_assemble_sph(), analyzer_compare_sph_rst::init_compare_sph_restart(), and analyzer_rayleigh_cvt_sph::init_cvt_rayleigh_sph().
Variable Documentation
def_new_sph_head
character(len=kchara), parameter, private set_control_newsph::def_new_sph_head = 'mesh_new/in_rj' private
Definition at line 33 of file set_control_newsph.f90.
Referenced by set_control_4_newsph().
def_org_sph_head
character(len=kchara), parameter, private set_control_newsph::def_org_sph_head = 'mesh_org/in_rj' private
Definition at line 31 of file set_control_newsph.f90.
Referenced by set_control_4_newsph().