CALYPSO: set_initial_sph_dynamo Module Reference
set_initial_sph_dynamo Module Reference
Set initial data for spectrum dynamos.
Functions/Subroutines
subroutine sph_initial_data_control (MHD_files, SPH_model, sph, ipol, MHD_step, rj_fld, sph_fst_IO)
subroutine, private sph_initial_data_4_benchmarks (ref_temp, sph_params, sph_rj, MHD_prop, ipol, rj_fld)
subroutine, private sph_initial_data_w_seed_b (ref_temp, ref_comp, sph_params, sph_rj, MHD_prop, sph_MHD_bc, ipol, rj_fld)
subroutine sph_initial_field_4_licv (ref_temp, sph_params, sph_rj, MHD_prop, ipol, rj_fld)
subroutine, private set_initial_velo_sph (is_velo, n_point, ntot_phys_rj, d_rj)
subroutine, private set_initial_magne_sph (sph_rj, sph_bc_B, ipol, r_ICB, r_CMB, nlayer_ICB, nlayer_CMB, n_point, ntot_phys_rj, d_rj)
subroutine, private reduce_initial_magne_sph (ipol, nnod_rj, ntot_phys_rj, d_rj)
Detailed Description
Set initial data for spectrum dynamos.
      subroutine sph_initial_data_control                             &
     &         (MHD_files, SPH_model, SPH_MHD, MHD_step, sph_fst_IO)
        type(MHD_file_IO_params), intent(in) :: MHD_files
        type(sph_grids), intent(in) :: sph
        type(phys_address), intent(in) :: ipol
        type(SPH_MHD_model_data), intent(in) :: SPH_model
        type(MHD_step_param), intent(inout) :: MHD_step
        type(phys_data), intent(inout) :: rj_fld
        type(field_IO), intent(inout) :: sph_fst_IO
Function/Subroutine Documentation
reduce_initial_magne_sph()
subroutine, private set_initial_sph_dynamo::reduce_initial_magne_sph (type(phys_address), intent(in) ipol, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj) private
Definition at line 401 of file set_initial_sph_dynamo.f90.
Referenced by sph_initial_data_w_seed_b().
set_initial_magne_sph()
subroutine, private set_initial_sph_dynamo::set_initial_magne_sph (type(sph_rj_grid), intent(in) sph_rj, type(sph_boundary_type), intent(in) sph_bc_B, type(phys_address), intent(in) ipol, real(kind = kreal), intent(in) r_ICB, real(kind = kreal), intent(in) r_CMB, integer(kind = kint), intent(in) nlayer_ICB, integer(kind = kint), intent(in) nlayer_CMB, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj) private
Definition at line 299 of file set_initial_sph_dynamo.f90.
References m_constants::dnine, m_constants::eight, m_constants::five, m_constants::four, t_boundary_params_sph_mhd::iflag_sph_fill_center, m_constants::one, m_constants::six, m_constants::ten, m_constants::three, m_constants::two, and m_constants::zero.
Referenced by sph_initial_data_w_seed_b().
set_initial_velo_sph()
subroutine, private set_initial_sph_dynamo::set_initial_velo_sph (integer(kind = kint), intent(in) is_velo, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj) private
Definition at line 277 of file set_initial_sph_dynamo.f90.
References m_constants::zero.
Referenced by sph_initial_data_4_benchmarks().
sph_initial_data_4_benchmarks()
subroutine, private set_initial_sph_dynamo::sph_initial_data_4_benchmarks (type(reference_field), intent(in) ref_temp, type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(mhd_evolution_param), intent(in) MHD_prop, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld) private
Definition at line 123 of file set_initial_sph_dynamo.f90.
References m_initial_field_control::i_rst_dbench1, m_initial_field_control::i_rst_dbench2, m_initial_field_control::i_rst_dbench_qcv, m_initial_field_control::iflag_restart, initial_magne_dynamobench::initial_b_dynamobench_1(), initial_magne_dynamobench::initial_b_dynamobench_2(), initial_magne_dbench_qvc::initial_b_dynamobench_qcv(), set_initial_sph_scalars::set_ini_reference_temp_sph(), set_initial_sph_scalars::set_initial_light_sph(), set_initial_sph_scalars::set_initial_temp_sph(), and set_initial_velo_sph().
Referenced by sph_initial_data_control().
sph_initial_data_control()
subroutine set_initial_sph_dynamo::sph_initial_data_control (type(mhd_file_io_params), intent(in) MHD_files, type(sph_mhd_model_data), intent(in) SPH_model, type(sph_grids), intent(in) sph, type(phys_address), intent(in) ipol, type(mhd_step_param), intent(inout) MHD_step, type(phys_data), intent(inout) rj_fld, type(field_io), intent(inout) sph_fst_IO)
Definition at line 52 of file set_initial_sph_dynamo.f90.
References t_time_data::copy_time_step_data(), m_initial_field_control::i_rst_by_file, m_initial_field_control::i_rst_dbench0, m_initial_field_control::i_rst_dbench1, m_initial_field_control::i_rst_dbench2, m_initial_field_control::i_rst_dbench_qcv, m_initial_field_control::i_rst_licv, m_initial_field_control::i_rst_no_file, m_machine_parameter::iflag_debug, m_initial_field_control::iflag_restart, sph_mhd_rst_io_control::output_sph_restart_control(), sph_mhd_rst_io_control::read_alloc_sph_restart_data(), set_sph_restart_io::set_sph_restart_num_to_io(), sph_initial_data_4_benchmarks(), sph_initial_data_w_seed_b(), and sph_initial_field_4_licv().
Referenced by sph_analyzer_mhd::sph_initialize_mhd().
sph_initial_data_w_seed_b()
subroutine, private set_initial_sph_dynamo::sph_initial_data_w_seed_b (type(reference_field), intent(in) ref_temp, type(reference_field), intent(in) ref_comp, type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(mhd_evolution_param), intent(in) MHD_prop, type(sph_mhd_boundary_data), intent(in) sph_MHD_bc, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld) private
Definition at line 195 of file set_initial_sph_dynamo.f90.
References reduce_initial_magne_sph(), set_initial_magne_sph(), and set_initial_sph_scalars::set_noize_scalar_sph().
Referenced by sph_initial_data_control().
sph_initial_field_4_licv()
subroutine set_initial_sph_dynamo::sph_initial_field_4_licv (type(reference_field), intent(in) ref_temp, type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(mhd_evolution_param), intent(in) MHD_prop, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld)
Definition at line 244 of file set_initial_sph_dynamo.f90.
References set_initial_sph_scalars::set_all_part_temp_sph(), and set_initial_sph_scalars::set_ini_reference_temp_sph().
Referenced by sph_initial_data_control().