CALYPSO: set_from_recv_buff_tri Module Reference
set_from_recv_buff_tri Module Reference
Arbitrary components data communication.
Functions/Subroutines
subroutine set_from_recv_buf_3x1 (nnod_new, nnod_recv, inod_import, WR, X1_new, X2_new, X3_new)
subroutine set_from_recv_buf_3x2 (nnod_new, nnod_recv, inod_import, WR, X1_new, X2_new, X3_new)
subroutine set_from_recv_buf_3x3 (nnod_new, nnod_recv, inod_import, WR, X1_new, X2_new, X3_new)
subroutine set_from_recv_buf_3x6 (nnod_new, nnod_recv, inod_import, WR, X1_new, X2_new, X3_new)
subroutine set_from_recv_buf_3xn (NB, nnod_new, npe_recv, nnod_recv, istack_recv, inod_import, WR, X1_new, X2_new, X3_new)
Detailed Description
Arbitrary components data communication.
      subroutine set_from_recv_buf_3x1(nnod_new,                      &
     &          nnod_recv, inod_import, WR, X1_new, X2_new, X3_new)
      subroutine set_from_recv_buf_3x2(nnod_new,                      &
     &          nnod_recv, inod_import, WR, X1_new, X2_new, X3_new)
      subroutine set_from_recv_buf_3x3(nnod_new,                      &
     &          nnod_recv, inod_import, WR, X1_new, X2_new, X3_new)
      subroutine set_from_recv_buf_3x6(nnod_new,                      &
     &          nnod_recv, inod_import, WR, X1_new, X2_new, X3_new)
      subroutine set_from_recv_buf_3xN(NB, nnod_new,                  &
     &          npe_recv, nnod_recv, istack_recv, inod_import,        &
     &          WR, X1_new, X2_new, X3_new)
Parameters
NB Number of components for communication
nnod_new Number of components for destination
npe_recv Number of processses to receive
nnod_recv Number of data points to receive
istack_recv(0:npe_send) End points of receive buffer for each process
inod_import(nnod_recv) local node ID to copy from receive buffer
X_new(NB*nnod_new) Received data
Function/Subroutine Documentation
set_from_recv_buf_3x1()
subroutine set_from_recv_buff_tri::set_from_recv_buf_3x1 (integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) nnod_recv, integer(kind = kint), dimension(nnod_recv), intent(in) inod_import, real (kind=kreal), dimension(3*nnod_recv), intent(in) WR, real (kind=kreal), dimension(nnod_new), intent(inout) X1_new, real (kind=kreal), dimension(nnod_new), intent(inout) X2_new, real (kind=kreal), dimension(nnod_new), intent(inout) X3_new)
Definition at line 47 of file set_from_recv_buff_tri.f90.
Referenced by select_copy_from_recv::sel_cppy_from_recv_buf_3x1().
set_from_recv_buf_3x2()
subroutine set_from_recv_buff_tri::set_from_recv_buf_3x2 (integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) nnod_recv, integer(kind = kint), dimension(nnod_recv), intent(in) inod_import, real (kind=kreal), dimension(6*nnod_recv), intent(in) WR, real (kind=kreal), dimension(2*nnod_new), intent(inout) X1_new, real (kind=kreal), dimension(2*nnod_new), intent(inout) X2_new, real (kind=kreal), dimension(2*nnod_new), intent(inout) X3_new)
Definition at line 75 of file set_from_recv_buff_tri.f90.
Referenced by select_copy_from_recv::sel_cppy_from_recv_buf_3x2().
set_from_recv_buf_3x3()
subroutine set_from_recv_buff_tri::set_from_recv_buf_3x3 (integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) nnod_recv, integer(kind = kint), dimension(nnod_recv), intent(in) inod_import, real (kind=kreal), dimension(9*nnod_recv), intent(in) WR, real (kind=kreal), dimension(3*nnod_new), intent(inout) X1_new, real (kind=kreal), dimension(3*nnod_new), intent(inout) X2_new, real (kind=kreal), dimension(3*nnod_new), intent(inout) X3_new)
Definition at line 106 of file set_from_recv_buff_tri.f90.
Referenced by select_copy_from_recv::sel_cppy_from_recv_buf_3x3().
set_from_recv_buf_3x6()
subroutine set_from_recv_buff_tri::set_from_recv_buf_3x6 (integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) nnod_recv, integer(kind = kint), dimension(nnod_recv), intent(in) inod_import, real (kind=kreal), dimension(18*nnod_recv), intent(in) WR, real (kind=kreal), dimension(6*nnod_new), intent(inout) X1_new, real (kind=kreal), dimension(6*nnod_new), intent(inout) X2_new, real (kind=kreal), dimension(6*nnod_new), intent(inout) X3_new)
Definition at line 140 of file set_from_recv_buff_tri.f90.
Referenced by select_copy_from_recv::sel_cppy_from_recv_buf_3x6().
set_from_recv_buf_3xn()
subroutine set_from_recv_buff_tri::set_from_recv_buf_3xn (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) npe_recv, integer(kind = kint), intent(in) nnod_recv, integer(kind = kint), dimension(0:npe_recv), intent(in) istack_recv, integer(kind = kint), dimension(nnod_recv), intent(in) inod_import, real (kind=kreal), dimension(3*nb*nnod_recv), intent(in) WR, real (kind=kreal), dimension(nb*nnod_new), intent(inout) X1_new, real (kind=kreal), dimension(nb*nnod_new), intent(inout) X2_new, real (kind=kreal), dimension(nb*nnod_new), intent(inout) X3_new)
Definition at line 183 of file set_from_recv_buff_tri.f90.
Referenced by select_copy_from_recv::sel_cppy_from_recv_buf_3xn().