CALYPSO: gz_ucd_field_file_io Module Reference
gz_ucd_field_file_io Module Reference
gzipped UCD ascii data IO
Functions/Subroutines
subroutine gz_write_ucd_2_fld_file (id_rank, gzip_name, t_IO, ucd)
subroutine gz_read_ucd_2_fld_file (id_rank, gzip_name, t_IO, ucd, ierr_IO)
subroutine gz_read_alloc_ucd_2_ld_file (id_rank, gzip_name, t_IO, ucd, ierr_IO)
Variables
type(buffer_4_gzip), private zbuf_fu
Detailed Description
gzipped UCD ascii data IO
      subroutine gz_write_ucd_2_fld_file                              &
     &         (id_rank, gzip_name, t_IO, ucd)
      subroutine gz_read_ucd_2_fld_file                               &
     &         (id_rank, gzip_name, t_IO, ucd, ierr_IO)
      subroutine gz_read_alloc_ucd_2_ld_file                          &
     &         (id_rank, gzip_name, t_IO, ucd, ierr)
        type(time_data), intent(inout) :: t_IO
        type(ucd_data), intent(inout) :: ucd
Parameters
id_rank process ID
gzip_name File name
ucd Structure for FEM field data IO
Function/Subroutine Documentation
gz_read_alloc_ucd_2_ld_file()
subroutine gz_ucd_field_file_io::gz_read_alloc_ucd_2_ld_file (integer, intent(in) id_rank, character(len=kchara), intent(in) gzip_name, type(time_data), intent(inout) t_IO, type(ucd_data), intent(inout) ucd, integer(kind = kint), intent(inout) ierr_IO)
Definition at line 113 of file gz_ucd_field_file_IO.f90.
References t_ucd_data::allocate_ucd_phys_data(), t_ucd_data::allocate_ucd_phys_name(), t_ucd_data::cal_istack_ucd_component(), skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_rd_gzfile_a(), gz_field_data_io::read_gz_field_data(), gz_data_io::read_gz_multi_int(), gz_field_data_io::read_gz_step_data(), skip_gz_comment::skip_gz_comment_int8_int(), and zbuf_fu.
Referenced by ucd_io_select::sel_read_alloc_udt_file(), and ucd_io_select::sel_read_udt_param().
gz_read_ucd_2_fld_file()
subroutine gz_ucd_field_file_io::gz_read_ucd_2_fld_file (integer, intent(in) id_rank, character(len=kchara), intent(in) gzip_name, type(time_data), intent(inout) t_IO, type(ucd_data), intent(inout) ucd, integer(kind = kint), intent(inout) ierr_IO)
Definition at line 78 of file gz_ucd_field_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_rd_gzfile_a(), gz_field_data_io::read_gz_field_data(), gz_data_io::read_gz_multi_int(), gz_field_data_io::read_gz_step_data(), skip_gz_comment::skip_gz_comment_int8_int(), and zbuf_fu.
Referenced by ucd_io_select::sel_read_udt_file().
gz_write_ucd_2_fld_file()
subroutine gz_ucd_field_file_io::gz_write_ucd_2_fld_file (integer, intent(in) id_rank, character(len=kchara), intent(in) gzip_name, type(time_data), intent(in) t_IO, type(ucd_data), intent(in) ucd)
Definition at line 48 of file gz_ucd_field_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), m_machine_parameter::i_debug, skip_gz_comment::open_wt_gzfile_a(), gz_field_data_io::write_gz_field_data(), gz_field_data_io::write_gz_step_data(), and zbuf_fu.
Referenced by ucd_io_select::sel_write_ucd_file(), and ucd_io_select::sel_write_udt_file().
Variable Documentation
zbuf_fu
type(buffer_4_gzip), private gz_ucd_field_file_io::zbuf_fu private
Definition at line 40 of file gz_ucd_field_file_IO.f90.
Referenced by gz_read_alloc_ucd_2_ld_file(), gz_read_ucd_2_fld_file(), and gz_write_ucd_2_fld_file().