CALYPSO: byte_swap_f Module Reference
byte_swap_f Module Reference
swap byte endian
Functions/Subroutines
subroutine byte_swap_real_f (num, real_dat)
subroutine byte_swap_int_f (num, int_dat)
subroutine byte_swap_int8_f (num, int8_dat)
subroutine byte_swap_int4_f (num, int4_dat)
subroutine, private byte_swap_64bit_f (l8_byte, array)
subroutine, private byte_swap_32bit_f (l8_byte, array)
subroutine integer_from_charabuffer (num, buffer, int_dat)
subroutine int8_from_charabuffer (num, buffer, int8_dat)
subroutine real_from_charabuffer (num, buffer, real_dat)
subroutine integer_to_charabuffer (num, int_dat, buffer)
subroutine int8_to_charabuffer (num, int8_dat, buffer)
subroutine real_to_charabuffer (num, real_dat, buffer)
Detailed Description
swap byte endian
      subroutine byte_swap_real_f(num, real_dat)
        integer(kind = kint_gl), intent(in) :: num
        real(kind = kreal), target, intent(inout) :: real_dat(num)
      subroutine byte_swap_int_f(num, int_dat)
        integer(kind = kint_gl), intent(in) :: num
        integer(kind = kint), target, intent(inout) :: int_dat(num)
      subroutine byte_swap_int8_f(num, int8_dat)
        integer(kind = kint_gl), intent(in) :: num
        integer(kind = kint_gl), target, intent(inout) :: int8_dat(num)
      subroutine byte_swap_int4_f(num, int4_dat)
        integer(kind = kint_gl), intent(in) :: num
        integer(kind = kint_4b), target, intent(inout) :: int4_dat(num)
      subroutine byte_swap_64bit_f(l8_byte, array)
      subroutine byte_swap_32bit_f(l8_byte, array)
         l8_byte :: byte length of array (defined by 8-byte integer)
         array ::   array to be transfered (call by using pointer!)
      subroutine integer_from_charabuffer(num, buffer, int_dat)
      subroutine int8_from_charabuffer(num, buffer, int8_dat)
      subroutine real_from_charabuffer(num, buffer, real_dat)
      subroutine integer_to_charabuffer(num, int_dat, buffer)
      subroutine int8_to_charabuffer(num, int8_dat, buffer)
      subroutine real_to_charabuffer(num, real_dat, buffer)
Function/Subroutine Documentation
byte_swap_32bit_f()
subroutine, private byte_swap_f::byte_swap_32bit_f (integer(kind = kint_gl), intent(in) l8_byte, character(len=1), dimension(l8_byte), intent(inout) array) private
Definition at line 164 of file byte_swap_f.f90.
Referenced by byte_swap_int4_f(), and byte_swap_int_f().
byte_swap_64bit_f()
subroutine, private byte_swap_f::byte_swap_64bit_f (integer(kind = kint_gl), intent(in) l8_byte, character(len=1), dimension(l8_byte), intent(inout) array) private
Definition at line 132 of file byte_swap_f.f90.
Referenced by byte_swap_int8_f(), byte_swap_int_f(), and byte_swap_real_f().
byte_swap_int4_f()
subroutine byte_swap_f::byte_swap_int4_f (integer(kind = kint_gl), intent(in) num, integer(kind = kint_4b), dimension(num), intent(inout), target int4_dat)
Definition at line 112 of file byte_swap_f.f90.
References byte_swap_32bit_f(), and m_precision::kint_4b.
Referenced by m_calypso_mpi_io::mpi_read_int4_b(), and t_rayleigh_restart_io::read_rayleigh_restart_params().
byte_swap_int8_f()
subroutine byte_swap_f::byte_swap_int8_f (integer(kind = kint_gl), intent(in) num, integer(kind = kint_gl), dimension(num), intent(inout), target int8_dat)
Definition at line 93 of file byte_swap_f.f90.
References byte_swap_64bit_f(), and m_precision::kint_gl.
Referenced by gz_mpi_binary_data_io::gz_mpi_read_int8_vector_b(), gz_mpi_binary_head_io::gz_mpi_read_mul_int8head_b(), and m_calypso_mpi_io::mpi_read_int8_b().
byte_swap_int_f()
subroutine byte_swap_f::byte_swap_int_f (integer(kind = kint_gl), intent(in) num, integer(kind = kint), dimension(num), intent(inout), target int_dat)
Definition at line 69 of file byte_swap_f.f90.
References byte_swap_32bit_f(), byte_swap_64bit_f(), m_precision::kint, and m_precision::kint_gl.
Referenced by m_calypso_mpi_io::mpi_read_int_b().
byte_swap_real_f()
subroutine byte_swap_f::byte_swap_real_f (integer(kind = kint_gl), intent(in) num, real(kind = kreal), dimension(num), intent(inout), target real_dat)
Definition at line 50 of file byte_swap_f.f90.
References byte_swap_64bit_f(), and m_precision::kreal.
Referenced by gz_mpi_binary_data_io::gz_mpi_read_1d_vector_b(), gz_mpi_binary_head_io::gz_mpi_read_mul_realhead_b(), m_calypso_mpi_io::mpi_read_real_b(), and t_rayleigh_restart_io::read_rayleigh_restart_params().
int8_from_charabuffer()
subroutine byte_swap_f::int8_from_charabuffer (integer(kind = kint_gl), intent(in) num, character(len = 1), dimension(kint_gl*num), intent(in) buffer, integer(kind = kint_gl), dimension(num), intent(inout) int8_dat)
Definition at line 220 of file byte_swap_f.f90.
int8_to_charabuffer()
subroutine byte_swap_f::int8_to_charabuffer (integer(kind = kint_gl), intent(in) num, integer(kind = kint_gl), dimension(num), intent(in) int8_dat, character(len = 1), dimension(kint_gl*num), intent(inout) buffer)
Definition at line 299 of file byte_swap_f.f90.
integer_from_charabuffer()
subroutine byte_swap_f::integer_from_charabuffer (integer(kind = kint_gl), intent(in) num, character(len = 1), dimension(kint*num), intent(in) buffer, integer(kind = kint), dimension(num), intent(inout) int_dat)
Definition at line 194 of file byte_swap_f.f90.
integer_to_charabuffer()
subroutine byte_swap_f::integer_to_charabuffer (integer(kind = kint_gl), intent(in) num, integer(kind = kint), dimension(num), intent(in) int_dat, character(len = 1), dimension(kint*num), intent(inout) buffer)
Definition at line 273 of file byte_swap_f.f90.
real_from_charabuffer()
subroutine byte_swap_f::real_from_charabuffer (integer(kind = kint_gl), intent(in) num, character(len = 1), dimension(kreal*num), intent(in) buffer, real(kind = kreal), dimension(num), intent(inout) real_dat)
Definition at line 246 of file byte_swap_f.f90.
real_to_charabuffer()
subroutine byte_swap_f::real_to_charabuffer (integer(kind = kint_gl), intent(in) num, real(kind = kreal), dimension(num), intent(in) real_dat, character(len = 1), dimension(kreal*num), intent(inout) buffer)
Definition at line 325 of file byte_swap_f.f90.