CALYPSO: mpi_sph_modes_data_io Module Reference
mpi_sph_modes_data_io Module Reference
ASCII spectr data IO routines.
Functions/Subroutines
subroutine mpi_read_geom_rtp_data (IO_param, comm_IO, sph_IO, sph_grps_IO)
subroutine mpi_read_spectr_rj_data (IO_param, comm_IO, sph_IO, sph_grps_IO)
subroutine mpi_read_geom_rtm_data (IO_param, comm_IO, sph_IO)
subroutine mpi_read_modes_rlm_data (IO_param, comm_IO, sph_IO)
subroutine mpi_write_geom_rtp_data (IO_param, comm_IO, sph_IO, sph_grps_IO)
subroutine mpi_write_spectr_rj_data (IO_param, comm_IO, sph_IO, sph_grps_IO)
subroutine mpi_write_geom_rtm_data (IO_param, comm_IO, sph_IO)
subroutine mpi_write_modes_rlm_data (IO_param, comm_IO, sph_IO)
Detailed Description
ASCII spectr data IO routines.
      subroutine mpi_read_geom_rtp_data                               &
     &         (IO_param, comm_IO, sph_IO, sph_grps_IO)
      subroutine mpi_read_spectr_rj_data                              &
     &         (IO_param, comm_IO, sph_IO, sph_grps_IO)
      subroutine mpi_read_geom_rtm_data                               &
     &         (IO_param, comm_IO, sph_IO)
      subroutine mpi_read_modes_rlm_data                              &
     &         (IO_param, comm_IO, sph_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(communication_table), intent(inout) :: comm_IO
        type(sph_IO_data), intent(inout) :: sph_IO
        type(sph_group_data), intent(inout) :: sph_grps_IO
      subroutine mpi_write_geom_rtp_data                              &
     &         (IO_param, comm_IO, sph_IO, sph_grps_IO)
      subroutine mpi_write_spectr_rj_data                             &
     &         (IO_param, comm_IO, sph_IO, sph_grps_IO)
      subroutine mpi_write_geom_rtm_data                              &
     &         (IO_param, comm_IO, sph_IO)
      subroutine mpi_write_modes_rlm_data                             &
     &         (IO_param, comm_IO, sph_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(communication_table), intent(in) :: comm_IO
        type(sph_IO_data), intent(in) :: sph_IO
        type(sph_group_data), intent(in) :: sph_grps_IO
Function/Subroutine Documentation
mpi_read_geom_rtm_data()
subroutine mpi_sph_modes_data_io::mpi_read_geom_rtm_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(inout) comm_IO, type(sph_io_data), intent(inout) sph_IO)
Definition at line 139 of file MPI_sph_modes_data_IO.f90.
References m_sph_modes_grid_labels::hd_rtp_comm(), m_sph_modes_grid_labels::hd_rtp_glbl(), m_sph_modes_grid_labels::hd_sph_para(), mpi_domain_data_io::mpi_read_domain_info(), mpi_spherical_model_io::mpi_read_gl_nodes_sph(), mpi_spherical_model_io::mpi_read_gl_reso_sph(), mpi_domain_data_io::mpi_read_import_data(), mpi_spherical_model_io::mpi_read_rank_4_sph(), mpi_sph_gl_1d_idx_io::mpi_read_rtp_gl_1d_table(), and mpi_ascii_data_io::mpi_skip_read().
Referenced by mpi_sph_modes_file_io::mpi_read_geom_rtm_file().
mpi_read_geom_rtp_data()
subroutine mpi_sph_modes_data_io::mpi_read_geom_rtp_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(inout) comm_IO, type(sph_io_data), intent(inout) sph_IO, type(sph_group_data), intent(inout) sph_grps_IO)
Definition at line 62 of file MPI_sph_modes_data_IO.f90.
References m_sph_modes_grid_labels::hd_grphd(), m_sph_modes_grid_labels::hd_ngrphd(), m_sph_modes_grid_labels::hd_pgrphd(), m_sph_modes_grid_labels::hd_rgrphd(), m_sph_modes_grid_labels::hd_rtp_comm(), m_sph_modes_grid_labels::hd_rtp_glbl(), m_sph_modes_grid_labels::hd_sph_para(), m_sph_modes_grid_labels::hd_tgrphd(), mpi_domain_data_io::mpi_read_domain_info(), mpi_spherical_model_io::mpi_read_gl_nodes_sph(), mpi_spherical_model_io::mpi_read_gl_reso_sph(), mpi_groups_io::mpi_read_group_data(), mpi_domain_data_io::mpi_read_import_data(), mpi_spherical_model_io::mpi_read_rank_4_sph(), mpi_sph_gl_1d_idx_io::mpi_read_rtp_gl_1d_table(), and mpi_ascii_data_io::mpi_skip_read().
Referenced by mpi_sph_modes_file_io::mpi_read_geom_rtp_file().
mpi_read_modes_rlm_data()
subroutine mpi_sph_modes_data_io::mpi_read_modes_rlm_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(inout) comm_IO, type(sph_io_data), intent(inout) sph_IO)
Definition at line 166 of file MPI_sph_modes_data_IO.f90.
References m_sph_modes_grid_labels::hd_rj_comm(), m_sph_modes_grid_labels::hd_rlm_glbl(), m_sph_modes_grid_labels::hd_sph_para(), mpi_domain_data_io::mpi_read_domain_info(), mpi_spherical_model_io::mpi_read_gl_nodes_sph(), mpi_spherical_model_io::mpi_read_gl_reso_sph(), mpi_domain_data_io::mpi_read_import_data(), mpi_spherical_model_io::mpi_read_rank_4_sph(), mpi_sph_gl_1d_idx_io::mpi_read_rj_gl_1d_table(), and mpi_ascii_data_io::mpi_skip_read().
Referenced by mpi_sph_modes_file_io::mpi_read_modes_rlm_file().
mpi_read_spectr_rj_data()
subroutine mpi_sph_modes_data_io::mpi_read_spectr_rj_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(inout) comm_IO, type(sph_io_data), intent(inout) sph_IO, type(sph_group_data), intent(inout) sph_grps_IO)
Definition at line 104 of file MPI_sph_modes_data_IO.f90.
References m_sph_modes_grid_labels::hd_grphd(), m_sph_modes_grid_labels::hd_jgrphd(), m_sph_modes_grid_labels::hd_kgrphd(), m_sph_modes_grid_labels::hd_rj_comm(), m_sph_modes_grid_labels::hd_rj_glbl(), m_sph_modes_grid_labels::hd_sph_para(), mpi_domain_data_io::mpi_read_domain_info(), mpi_spherical_model_io::mpi_read_gl_nodes_sph(), mpi_spherical_model_io::mpi_read_gl_reso_sph(), mpi_groups_io::mpi_read_group_data(), mpi_domain_data_io::mpi_read_import_data(), mpi_spherical_model_io::mpi_read_rank_4_sph(), mpi_sph_gl_1d_idx_io::mpi_read_rj_gl_1d_table(), and mpi_ascii_data_io::mpi_skip_read().
Referenced by mpi_sph_modes_file_io::mpi_read_spectr_rj_file().
mpi_write_geom_rtm_data()
subroutine mpi_sph_modes_data_io::mpi_write_geom_rtm_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(in) comm_IO, type(sph_io_data), intent(in) sph_IO)
Definition at line 286 of file MPI_sph_modes_data_IO.f90.
References m_sph_modes_grid_labels::hd_rtp_comm(), m_sph_modes_grid_labels::hd_rtp_glbl(), m_sph_modes_grid_labels::hd_sph_para(), mpi_ascii_data_io::mpi_write_charahead(), mpi_domain_data_io::mpi_write_domain_info(), mpi_spherical_model_io::mpi_write_gl_nodes_sph(), mpi_spherical_model_io::mpi_write_gl_reso_sph(), mpi_domain_data_io::mpi_write_import_data(), mpi_spherical_model_io::mpi_write_rank_4_sph(), and mpi_sph_gl_1d_idx_io::mpi_write_rtp_gl_1d_table().
Referenced by mpi_sph_modes_file_io::mpi_write_geom_rtm_file().
mpi_write_geom_rtp_data()
subroutine mpi_sph_modes_data_io::mpi_write_geom_rtp_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(in) comm_IO, type(sph_io_data), intent(in) sph_IO, type(sph_group_data), intent(in) sph_grps_IO)
Definition at line 194 of file MPI_sph_modes_data_IO.f90.
References m_sph_modes_grid_labels::hd_grphd(), m_sph_modes_grid_labels::hd_ngrphd(), m_sph_modes_grid_labels::hd_pgrphd(), m_sph_modes_grid_labels::hd_rgrphd(), m_sph_modes_grid_labels::hd_rtp_comm(), m_sph_modes_grid_labels::hd_rtp_glbl(), m_sph_modes_grid_labels::hd_sph_para(), m_sph_modes_grid_labels::hd_tgrphd(), mpi_ascii_data_io::mpi_write_charahead(), mpi_domain_data_io::mpi_write_domain_info(), mpi_spherical_model_io::mpi_write_gl_nodes_sph(), mpi_spherical_model_io::mpi_write_gl_reso_sph(), mpi_groups_io::mpi_write_grp_data(), mpi_domain_data_io::mpi_write_import_data(), mpi_spherical_model_io::mpi_write_rank_4_sph(), and mpi_sph_gl_1d_idx_io::mpi_write_rtp_gl_1d_table().
Referenced by mpi_sph_modes_file_io::mpi_write_geom_rtp_file().
mpi_write_modes_rlm_data()
subroutine mpi_sph_modes_data_io::mpi_write_modes_rlm_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(in) comm_IO, type(sph_io_data), intent(in) sph_IO)
Definition at line 317 of file MPI_sph_modes_data_IO.f90.
References m_sph_modes_grid_labels::hd_rj_comm(), m_sph_modes_grid_labels::hd_rlm_glbl(), m_sph_modes_grid_labels::hd_sph_para(), mpi_ascii_data_io::mpi_write_charahead(), mpi_domain_data_io::mpi_write_domain_info(), mpi_spherical_model_io::mpi_write_gl_nodes_sph(), mpi_spherical_model_io::mpi_write_gl_reso_sph(), mpi_domain_data_io::mpi_write_import_data(), mpi_spherical_model_io::mpi_write_rank_4_sph(), and mpi_sph_gl_1d_idx_io::mpi_write_rj_gl_1d_table().
Referenced by mpi_sph_modes_file_io::mpi_write_modes_rlm_file().
mpi_write_spectr_rj_data()
subroutine mpi_sph_modes_data_io::mpi_write_spectr_rj_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(in) comm_IO, type(sph_io_data), intent(in) sph_IO, type(sph_group_data), intent(in) sph_grps_IO)
Definition at line 244 of file MPI_sph_modes_data_IO.f90.
References m_sph_modes_grid_labels::hd_grphd(), m_sph_modes_grid_labels::hd_jgrphd(), m_sph_modes_grid_labels::hd_kgrphd(), m_sph_modes_grid_labels::hd_rj_comm(), m_sph_modes_grid_labels::hd_rj_glbl(), m_sph_modes_grid_labels::hd_sph_para(), mpi_ascii_data_io::mpi_write_charahead(), mpi_domain_data_io::mpi_write_domain_info(), mpi_spherical_model_io::mpi_write_gl_nodes_sph(), mpi_spherical_model_io::mpi_write_gl_reso_sph(), mpi_groups_io::mpi_write_grp_data(), mpi_domain_data_io::mpi_write_import_data(), mpi_spherical_model_io::mpi_write_rank_4_sph(), and mpi_sph_gl_1d_idx_io::mpi_write_rj_gl_1d_table().
Referenced by mpi_sph_modes_file_io::mpi_write_spectr_rj_file().