CALYPSO: set_comm_table_rtp_rj Module Reference
set_comm_table_rtp_rj Module Reference
Construct communication table for rj and rtp grid.
Functions/Subroutines
subroutine, private allocate_domain_sr_tmp (num_pe)
subroutine, private deallocate_domain_sr_tmp
subroutine const_sph_rj_modes (id_rank, num_pe, comm_rlm_mul, added_radial_grp, s3d_ranks, s3d_radius, sph_lcp, stk_lc1d, sph_gl1d, sph_params, sph_rtp, sph_rj, comm_rj_lc, sph_grp_lc)
subroutine const_sph_rtp_grids (id_rank, num_pe, comm_rtm_mul, added_radial_grp, r_layer_grp, med_layer_grp, s3d_ranks, s3d_radius, sph_lcp, stk_lc1d, sph_gl1d, sph_params, sph_rtp, comm_rtp_lc, sph_grp_lc)
subroutine, private const_comm_table_4_rj (id_rank, num_pe, comm_rlm_mul, s3d_ranks, s3d_radius, sph_lcp, stk_lc1d, sph_gl1d, nidx_global_rtp_r, sph_params, sph_rj, comm_rj)
subroutine, private const_comm_table_4_rtp (id_rank, num_pe, comm_rtm_mul, s3d_ranks, s3d_radius, sph_lcp, stk_lc1d, sph_gl1d, sph_params, sph_rtp, comm_rtp)
subroutine, private count_comm_table_4_rj (id_rank, num_pe, comm_rlm, comm_rj)
subroutine, private set_comm_table_4_rj (id_rank, num_pe, comm_rlm_mul, s3d_ranks, s3d_radius, sph_lcp, stk_lc1d, sph_gl1d, nidx_global_rtp_r, sph_params, sph_rj, comm_rj, icou)
subroutine, private count_comm_table_4_rtp (id_rank, num_pe, comm_rtm, nneib_domain_rtp)
subroutine, private set_comm_table_4_rtp (id_rank, num_pe, comm_rtm_mul, s3d_ranks, s3d_radius, sph_lcp, stk_lc1d, sph_gl1d, sph_params, sph_rtp, comm_rtp, icou)
subroutine, private set_comm_stack_rtp_rj (nneib_domain, id_domain, istack_sr, ntot_item_sr)
Variables
integer(kind=kint), dimension(:), allocatable, private id_domain_tmp
integer(kind=kint), dimension(:), allocatable, private nnod_sr_tmp
type(sph_local_1d_index_rtp), private sph_lcx_rtp
type(sph_local_1d_index_rj), private sph_lcx_rj
Detailed Description
Construct communication table for rj and rtp grid.
      subroutine const_sph_rj_modes                                   &
     &         (id_rank, num_pe, comm_rlm_mul, added_radial_grp,      &
     &          s3d_ranks, s3d_radius, sph_lcp, stk_lc1d, sph_gl1d,   &
     &          sph_params, sph_rtp, sph_rj, comm_rj_lc, sph_grp_lc)
        type(spheric_global_rank), intent(in) :: s3d_ranks
        type(spheric_global_radius), intent(in) :: s3d_radius
        type(sph_local_parameters), intent(in) :: sph_lcp
        type(sph_1d_index_stack), intent(in) :: stk_lc1d
        type(sph_1d_global_index), intent(in) :: sph_gl1d
        type(sph_shell_parameters), intent(in) :: sph_params
        type(sph_comm_tbl), intent(in) :: comm_rlm_mul(ndomain_sph)
        type(sph_shell_parameters), intent(in) :: sph_params
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_rj_grid), intent(inout) :: sph_rj
        type(sph_comm_tbl), intent(inout) :: comm_rj_lc
        type(sph_group_data), intent(inout) :: sph_grp_lc
      subroutine const_sph_rtp_grids(id_rank, num_pe, comm_rtm_mul,   &
     &          added_radial_grp, r_layer_grp, med_layer_grp,         &
     &          s3d_ranks, s3d_radius, sph_lcp, stk_lc1d, sph_gl1d,   &
     &          sph_params, sph_rtp, comm_rtp_lc, sph_grp_lc)
        type(spheric_global_rank), intent(in) :: s3d_ranks
        type(spheric_global_radius), intent(in) :: s3d_radius
        type(sph_local_parameters), intent(in) :: sph_lcp
        type(sph_1d_index_stack), intent(in) :: stk_lc1d
        type(sph_1d_global_index), intent(in) :: sph_gl1d
        type(sph_shell_parameters), intent(in) :: sph_params
        type(sph_comm_tbl), intent(in) :: comm_rtm_mul(ndomain_sph)
        type(sph_rtp_grid), intent(inout) :: sph_rtp
        type(sph_comm_tbl), intent(inout) :: comm_rtp_lc
        type(sph_group_data), intent(inout) :: sph_grp_lc
Function/Subroutine Documentation
allocate_domain_sr_tmp()
subroutine, private set_comm_table_rtp_rj::allocate_domain_sr_tmp (integer, intent(in) num_pe) private
Definition at line 81 of file set_comm_table_rtp_rj.f90.
References id_domain_tmp, and nnod_sr_tmp.
Referenced by const_comm_table_4_rj(), and const_comm_table_4_rtp().
const_comm_table_4_rj()
subroutine, private set_comm_table_rtp_rj::const_comm_table_4_rj (integer, intent(in) id_rank, integer, intent(in) num_pe, type(sph_comm_tbl), dimension(num_pe), intent(in) comm_rlm_mul, type(spheric_global_rank), intent(in) s3d_ranks, type(spheric_global_radius), intent(in) s3d_radius, type(sph_local_parameters), intent(in) sph_lcp, type(sph_1d_index_stack), intent(in) stk_lc1d, type(sph_1d_global_index), intent(in) sph_gl1d, integer(kind = kint), intent(in) nidx_global_rtp_r, type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(sph_comm_tbl), intent(inout) comm_rj) private
Definition at line 239 of file set_comm_table_rtp_rj.f90.
References t_sph_trans_comm_tbl::alloc_sph_comm_item(), t_sph_trans_comm_tbl::alloc_sph_comm_stack(), allocate_domain_sr_tmp(), count_comm_table_4_rj(), deallocate_domain_sr_tmp(), set_comm_stack_rtp_rj(), and set_comm_table_4_rj().
Referenced by const_sph_rj_modes().
const_comm_table_4_rtp()
subroutine, private set_comm_table_rtp_rj::const_comm_table_4_rtp (integer, intent(in) id_rank, integer, intent(in) num_pe, type(sph_comm_tbl), dimension(num_pe), intent(in) comm_rtm_mul, type(spheric_global_rank), intent(in) s3d_ranks, type(spheric_global_radius), intent(in) s3d_radius, type(sph_local_parameters), intent(in) sph_lcp, type(sph_1d_index_stack), intent(in) stk_lc1d, type(sph_1d_global_index), intent(in) sph_gl1d, type(sph_shell_parameters), intent(in) sph_params, type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(inout) comm_rtp) private
Definition at line 283 of file set_comm_table_rtp_rj.f90.
References t_sph_trans_comm_tbl::alloc_sph_comm_item(), t_sph_trans_comm_tbl::alloc_sph_comm_stack(), allocate_domain_sr_tmp(), count_comm_table_4_rtp(), deallocate_domain_sr_tmp(), set_comm_stack_rtp_rj(), and set_comm_table_4_rtp().
Referenced by const_sph_rtp_grids().
const_sph_rj_modes()
subroutine set_comm_table_rtp_rj::const_sph_rj_modes (integer, intent(in) id_rank, integer, intent(in) num_pe, type(sph_comm_tbl), dimension(num_pe), intent(in) comm_rlm_mul, type(layering_group_list), intent(in) added_radial_grp, type(spheric_global_rank), intent(in) s3d_ranks, type(spheric_global_radius), intent(in) s3d_radius, type(sph_local_parameters), intent(in) sph_lcp, type(sph_1d_index_stack), intent(in) stk_lc1d, type(sph_1d_global_index), intent(in) sph_gl1d, type(sph_shell_parameters), intent(in) sph_params, type(sph_rtp_grid), intent(in) sph_rtp, type(sph_rj_grid), intent(inout) sph_rj, type(sph_comm_tbl), intent(inout) comm_rj_lc, type(sph_group_data), intent(inout) sph_grp_lc)
Definition at line 104 of file set_comm_table_rtp_rj.f90.
References copy_sph_1d_global_index::add_center_mode_rj(), const_comm_table_4_rj(), set_local_sphere_by_global::copy_gl_2_local_rj_param(), copy_sph_1d_global_index::copy_sph_1d_gl_idx_rj(), m_machine_parameter::iflag_debug, set_local_sphere_param::set_global_sph_rj_id(), and set_sph_groups::set_sph_rj_groups().
Referenced by mpi_gen_sph_grids_modes::mpi_gen_sph_grids(), mpi_gen_sph_grids_modes::mpi_gen_sph_rj_mode(), and t_parai_gen_sph_grids_modes::para_gen_sph_rlm_rj_modes().
const_sph_rtp_grids()
subroutine set_comm_table_rtp_rj::const_sph_rtp_grids (integer, intent(in) id_rank, integer, intent(in) num_pe, type(sph_comm_tbl), dimension(num_pe), intent(in) comm_rtm_mul, type(layering_group_list), intent(in) added_radial_grp, type(layering_group_list), intent(in) r_layer_grp, type(layering_group_list), intent(in) med_layer_grp, type(spheric_global_rank), intent(in) s3d_ranks, type(spheric_global_radius), intent(in) s3d_radius, type(sph_local_parameters), intent(in) sph_lcp, type(sph_1d_index_stack), intent(in) stk_lc1d, type(sph_1d_global_index), intent(in) sph_gl1d, type(sph_shell_parameters), intent(in) sph_params, type(sph_rtp_grid), intent(inout) sph_rtp, type(sph_comm_tbl), intent(inout) comm_rtp_lc, type(sph_group_data), intent(inout) sph_grp_lc)
Definition at line 168 of file set_comm_table_rtp_rj.f90.
References const_comm_table_4_rtp(), set_local_sphere_by_global::copy_gl_2_local_rtp_param(), copy_sph_1d_global_index::copy_sph_1d_gl_idx_rtp(), m_machine_parameter::iflag_debug, set_local_sphere_param::set_global_sph_prt_id(), set_local_sphere_param::set_global_sph_rtp_id(), and set_sph_groups::set_sph_rtp_groups().
Referenced by mpi_gen_sph_grids_modes::mpi_gen_sph_grids(), and t_parai_gen_sph_grids_modes::para_gen_sph_rtm_rtp_grids().
count_comm_table_4_rj()
subroutine, private set_comm_table_rtp_rj::count_comm_table_4_rj (integer, intent(in) id_rank, integer, intent(in) num_pe, type(sph_comm_tbl), dimension(num_pe), intent(in) comm_rlm, type(sph_comm_tbl), intent(inout) comm_rj) private
Definition at line 331 of file set_comm_table_rtp_rj.f90.
References id_domain_tmp, and nnod_sr_tmp.
Referenced by const_comm_table_4_rj().
count_comm_table_4_rtp()
subroutine, private set_comm_table_rtp_rj::count_comm_table_4_rtp (integer, intent(in) id_rank, integer, intent(in) num_pe, type(sph_comm_tbl), dimension(num_pe), intent(in) comm_rtm, integer(kind = kint), intent(inout) nneib_domain_rtp) private
Definition at line 455 of file set_comm_table_rtp_rj.f90.
References id_domain_tmp, and nnod_sr_tmp.
Referenced by const_comm_table_4_rtp().
deallocate_domain_sr_tmp()
subroutine, private set_comm_table_rtp_rj::deallocate_domain_sr_tmp private
Definition at line 94 of file set_comm_table_rtp_rj.f90.
References id_domain_tmp, and nnod_sr_tmp.
Referenced by const_comm_table_4_rj(), and const_comm_table_4_rtp().
set_comm_stack_rtp_rj()
subroutine, private set_comm_table_rtp_rj::set_comm_stack_rtp_rj (integer(kind = kint), intent(in) nneib_domain, integer(kind = kint), dimension(nneib_domain), intent(inout) id_domain, integer(kind = kint), dimension(0:nneib_domain), intent(inout) istack_sr, integer(kind = kint), intent(inout) ntot_item_sr) private
Definition at line 575 of file set_comm_table_rtp_rj.f90.
References id_domain_tmp, and nnod_sr_tmp.
Referenced by const_comm_table_4_rj(), and const_comm_table_4_rtp().
set_comm_table_4_rj()
subroutine, private set_comm_table_rtp_rj::set_comm_table_4_rj (integer, intent(in) id_rank, integer, intent(in) num_pe, type(sph_comm_tbl), dimension(num_pe), intent(in) comm_rlm_mul, type(spheric_global_rank), intent(in) s3d_ranks, type(spheric_global_radius), intent(in) s3d_radius, type(sph_local_parameters), intent(in) sph_lcp, type(sph_1d_index_stack), intent(in) stk_lc1d, type(sph_1d_global_index), intent(in) sph_gl1d, integer(kind = kint), intent(in) nidx_global_rtp_r, type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(sph_comm_tbl), intent(inout) comm_rj, integer(kind = kint), intent(inout) icou) private
Definition at line 369 of file set_comm_table_rtp_rj.f90.
References t_spheric_rlm_data::alloc_sph_1d_index_rlm(), gen_sph_grids_modes::const_sph_rlm_modes(), t_sph_local_index::dealloc_rj_1d_local_idx(), t_spheric_rlm_data::dealloc_sph_1d_index_rlm(), t_sph_trans_comm_tbl::dealloc_sph_comm_item(), t_spheric_rlm_data::dealloc_spheric_param_rlm(), t_sph_local_index::init_local_idx_table_rj(), set_global_spherical_param::set_global_rlm_resolution(), and sph_lcx_rj.
Referenced by const_comm_table_4_rj().
set_comm_table_4_rtp()
subroutine, private set_comm_table_rtp_rj::set_comm_table_4_rtp (integer, intent(in) id_rank, integer, intent(in) num_pe, type(sph_comm_tbl), dimension(num_pe), intent(in) comm_rtm_mul, type(spheric_global_rank), intent(in) s3d_ranks, type(spheric_global_radius), intent(in) s3d_radius, type(sph_local_parameters), intent(in) sph_lcp, type(sph_1d_index_stack), intent(in) stk_lc1d, type(sph_1d_global_index), intent(in) sph_gl1d, type(sph_shell_parameters), intent(in) sph_params, type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(inout) comm_rtp, integer(kind = kint), intent(inout) icou) private
Definition at line 495 of file set_comm_table_rtp_rj.f90.
References gen_sph_grids_modes::const_sph_rtm_grids(), t_sph_local_index::dealloc_rtp_1d_local_idx(), t_sph_trans_comm_tbl::dealloc_sph_comm_item(), t_sph_local_index::init_local_idx_table_rtp(), set_global_spherical_param::set_global_rtm_resolution(), and sph_lcx_rtp.
Referenced by const_comm_table_4_rtp().
Variable Documentation
id_domain_tmp
integer(kind = kint), dimension(:), allocatable, private set_comm_table_rtp_rj::id_domain_tmp private
Definition at line 61 of file set_comm_table_rtp_rj.f90.
Referenced by allocate_domain_sr_tmp(), count_comm_table_4_rj(), count_comm_table_4_rtp(), deallocate_domain_sr_tmp(), and set_comm_stack_rtp_rj().
nnod_sr_tmp
integer(kind = kint), dimension(:), allocatable, private set_comm_table_rtp_rj::nnod_sr_tmp private
Definition at line 62 of file set_comm_table_rtp_rj.f90.
Referenced by allocate_domain_sr_tmp(), count_comm_table_4_rj(), count_comm_table_4_rtp(), deallocate_domain_sr_tmp(), and set_comm_stack_rtp_rj().
sph_lcx_rj
type(sph_local_1d_index_rj), private set_comm_table_rtp_rj::sph_lcx_rj private
Definition at line 65 of file set_comm_table_rtp_rj.f90.
Referenced by set_comm_table_4_rj().
sph_lcx_rtp
type(sph_local_1d_index_rtp), private set_comm_table_rtp_rj::sph_lcx_rtp private
Definition at line 64 of file set_comm_table_rtp_rj.f90.
Referenced by set_comm_table_4_rtp().