CALYPSO: set_sph_exp_free_icb Module Reference
set_sph_exp_free_icb Module Reference
Evaluate velocity with free slip boundary at ICB.
Functions/Subroutines
subroutine cal_sph_nod_icb_free_v_and_w (jmax, kr_in, fdm2_free_vp_ICB, fdm2_free_vt_ICB, is_fld, is_rot, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_nod_icb_free_vpol2 (jmax, kr_in, fdm2_free_vp_ICB, is_fld, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_nod_icb_free_rot2 (jmax, g_sph_rj, kr_in, r_ICB, fdm2_free_vp_ICB, fdm2_free_vt_ICB, is_fld, is_rot, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_nod_icb_free_diffuse2 (jmax, g_sph_rj, kr_in, r_ICB, fdm2_free_vp_ICB, fdm2_free_vt_ICB, coef_d, is_fld, is_diffuse, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_nod_icb_free_w_diffuse2 (jmax, g_sph_rj, kr_in, r_ICB, fdm2_fix_fld_ICB, fdm2_free_vt_ICB, coef_d, is_fld, is_diffuse, n_point, ntot_phys_rj, d_rj)
Detailed Description
Evaluate velocity with free slip boundary at ICB.
      subroutine cal_sph_nod_icb_free_v_and_w(jmax, kr_in,            &
     &          fdm2_free_vp_ICB, fdm2_free_vt_ICB, is_fld, is_rot,   &
     &          n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_nod_icb_free_vpol2(jmax, kr_in,              &
     &          fdm2_free_vp_ICB, is_fld, n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_nod_icb_free_rot2(jmax, g_sph_rj, kr_in,     &
     &          r_ICB, fdm2_free_vp_ICB, fdm2_free_vt_ICB,            &
     &          is_fld, is_rot, n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_nod_icb_free_diffuse2(jmax, g_sph_rj, kr_in, &
     &          r_ICB, fdm2_free_vp_ICB, fdm2_free_vt_ICB, coef_d,    &
     &          is_fld, is_diffuse, n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_nod_icb_free_w_diffuse2(jmax, g_sph_rj,      &
     &          kr_in, r_ICB, fdm2_fix_fld_ICB, fdm2_free_vt_ICB,     &
     &          coef_d, is_fld, is_diffuse,                           &
     &          n_point, ntot_phys_rj, d_rj)
Parameters
n_point Number of points for spectrum data
jmax Number of modes for spherical harmonics \(L*(L+2)\)
kr_in Radial ID for inner boundary
r_ICB(0:2) Radius at ICB
Parameters
fdm2_fix_fld_ICB(0:2,3) Matrix to evaluate radial derivative at ICB with fixed field
fdm2_free_vp_ICB(-1:1,3) Matrix to evaluate poloidal velocity with free slip boundary at ICB
fdm2_free_vt_ICB(-1:1,3) Matrix to evaluate toroidal velocity with free slip boundary at ICB
Parameters
coef_d Coefficient for diffusion term
is_fld Address of poloidal velocity in d_rj
is_rot Address of poloidal vorticity in d_rj
is_diffuse Address of poloidal viscousity in d_rj
Parameters
ntot_phys_rj Total number of components
d_rj Spectrum data
Function/Subroutine Documentation
cal_sph_nod_icb_free_diffuse2()
subroutine set_sph_exp_free_icb::cal_sph_nod_icb_free_diffuse2 (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(0:2), intent(in) r_ICB, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_free_vp_ICB, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_free_vt_ICB, real(kind = kreal), intent(in) coef_d, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_diffuse, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 170 of file set_sph_exp_free_ICB.f90.
Referenced by select_exp_velocity_icb::sel_icb_sph_viscous_diffusion().
cal_sph_nod_icb_free_rot2()
subroutine set_sph_exp_free_icb::cal_sph_nod_icb_free_rot2 (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(0:2), intent(in) r_ICB, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_free_vp_ICB, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_free_vt_ICB, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_rot, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 131 of file set_sph_exp_free_ICB.f90.
Referenced by select_exp_velocity_icb::sel_icb_sph_vorticity().
cal_sph_nod_icb_free_v_and_w()
subroutine set_sph_exp_free_icb::cal_sph_nod_icb_free_v_and_w (integer(kind = kint), intent(in) jmax, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_free_vp_ICB, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_free_vt_ICB, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_rot, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 62 of file set_sph_exp_free_ICB.f90.
References m_constants::zero.
Referenced by select_exp_velocity_icb::sel_icb_grad_vp_and_vorticity().
cal_sph_nod_icb_free_vpol2()
subroutine set_sph_exp_free_icb::cal_sph_nod_icb_free_vpol2 (integer(kind = kint), intent(in) jmax, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_free_vp_ICB, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 100 of file set_sph_exp_free_ICB.f90.
References m_constants::zero.
Referenced by select_exp_velocity_icb::sel_icb_grad_poloidal_moment().
cal_sph_nod_icb_free_w_diffuse2()
subroutine set_sph_exp_free_icb::cal_sph_nod_icb_free_w_diffuse2 (integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(0:2), intent(in) r_ICB, real(kind = kreal), dimension(0:2,3), intent(in) fdm2_fix_fld_ICB, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_free_vt_ICB, real(kind = kreal), intent(in) coef_d, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_diffuse, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 210 of file set_sph_exp_free_ICB.f90.
Referenced by select_exp_velocity_icb::sel_icb_sph_vort_diffusion().