CALYPSO: normgi_by_primes Module Reference
normgi_by_primes Module Reference
Functions/Subroutines
subroutine alloc_int_prime_ks
subroutine dealloc_int_prime_ks
subroutine resize_int_prime_ks (imax_fact, nmax_prm_ks)
double precision function gs_prime (m1, l1, m2, l2, m3, l3)
subroutine conut_prims_normgi (m1, l1, m2, l2, m3, l3)
subroutine const_prime_table_4_factor (num_fact, nmax_prms, itbl_prime, num_prime, iprime, iexp, kst, ked, order, iexp_fact)
Variables
integer(kind=kint), private nmax_prms
integer(kind=kint), private num_fact
integer(kind=kint), dimension(:), allocatable, private int_prime_ks
integer(kind=kint), dimension(:), allocatable, private num_prm_ks
integer(kind=kint), dimension(:), allocatable itbl_prime_ks
integer(kind=kint), dimension(:,:), allocatable, private iprm_ks
integer(kind=kint), dimension(:,:), allocatable, private iexp_ks
integer(kind=kint), dimension(:), allocatable, private iexp_gi
integer(kind=kint), dimension(:), allocatable, private iexp_gsi
integer(kind=kint), dimension(:), allocatable, private iexp_ti
Function/Subroutine Documentation
alloc_int_prime_ks()
subroutine normgi_by_primes::alloc_int_prime_ks
Definition at line 30 of file normgi_by_primes.f90.
References iexp_gi, iexp_gsi, iexp_ks, iexp_ti, int_prime_ks, iprm_ks, itbl_prime_ks, nmax_prms, num_fact, and num_prm_ks.
Referenced by conut_prims_normgi(), and resize_int_prime_ks().
const_prime_table_4_factor()
subroutine normgi_by_primes::const_prime_table_4_factor (integer(kind = kint), intent(in) num_fact, integer(kind = kint), intent(in) nmax_prms, integer(kind = kint), dimension(num_fact), intent(in) itbl_prime, integer(kind = kint), dimension(nmax_prms), intent(in) num_prime, integer(kind = kint), dimension(nmax_prms,num_fact), intent(in) iprime, integer(kind = kint), dimension(nmax_prms,num_fact), intent(in) iexp, integer(kind = kint), intent(in) kst, integer(kind = kint), intent(in) ked, integer(kind = kint), intent(in) order, integer(kind = kint), dimension(nmax_prms), intent(inout) iexp_fact)
Definition at line 298 of file normgi_by_primes.f90.
Referenced by gs_prime().
conut_prims_normgi()
subroutine normgi_by_primes::conut_prims_normgi (integer(kind = kint), intent(in) m1, integer(kind = kint), intent(in) l1, integer(kind = kint), intent(in) m2, integer(kind = kint), intent(in) l2, integer(kind = kint), intent(in) m3, integer(kind = kint), intent(in) l3)
Definition at line 215 of file normgi_by_primes.f90.
References alloc_int_prime_ks(), primefac::countprimes(), iexp_ks, m_constants::ifive, int_prime_ks, m_constants::ione, iprm_ks, itbl_prime_ks, m_constants::ithree, m_constants::izero, nmax_prms, num_fact, num_prm_ks, primefac::prmfac(), quicksort::quicksort_int(), and primefac::setprimes().
Referenced by gs_prime().
dealloc_int_prime_ks()
subroutine normgi_by_primes::dealloc_int_prime_ks
Definition at line 59 of file normgi_by_primes.f90.
References iexp_gi, iexp_gsi, iexp_ks, iexp_ti, int_prime_ks, iprm_ks, itbl_prime_ks, and num_prm_ks.
Referenced by gs_prime(), and resize_int_prime_ks().
gs_prime()
double precision function normgi_by_primes::gs_prime (integer(kind = kint), intent(in) m1, integer(kind = kint), intent(in) l1, integer(kind = kint), intent(in) m2, integer(kind = kint), intent(in) l2, integer(kind = kint), intent(in) m3, integer(kind = kint), intent(in) l3)
Definition at line 84 of file normgi_by_primes.f90.
References const_prime_table_4_factor(), conut_prims_normgi(), dealloc_int_prime_ks(), iexp_gi, iexp_gsi, iexp_ks, iexp_ti, m_constants::ifive, int_prime_ks, m_constants::ione, iprm_ks, itbl_prime_ks, m_constants::ithree, m_constants::izero, nmax_prms, num_fact, num_prm_ks, m_constants::one, quicksort::quicksort_int(), and m_constants::two.
Referenced by normgi::gs().
resize_int_prime_ks()
subroutine normgi_by_primes::resize_int_prime_ks (integer(kind = kint), intent(in) imax_fact, integer(kind = kint), intent(in) nmax_prm_ks)
Definition at line 70 of file normgi_by_primes.f90.
References alloc_int_prime_ks(), dealloc_int_prime_ks(), int_prime_ks, nmax_prms, and num_fact.
Variable Documentation
iexp_gi
integer(kind = kint), dimension(:), allocatable, private normgi_by_primes::iexp_gi private
Definition at line 15 of file normgi_by_primes.f90.
Referenced by alloc_int_prime_ks(), dealloc_int_prime_ks(), and gs_prime().
iexp_gsi
integer(kind = kint), dimension(:), allocatable, private normgi_by_primes::iexp_gsi private
Definition at line 16 of file normgi_by_primes.f90.
Referenced by alloc_int_prime_ks(), dealloc_int_prime_ks(), and gs_prime().
iexp_ks
integer(kind = kint), dimension(:,:), allocatable, private normgi_by_primes::iexp_ks private
Definition at line 14 of file normgi_by_primes.f90.
Referenced by alloc_int_prime_ks(), conut_prims_normgi(), dealloc_int_prime_ks(), and gs_prime().
iexp_ti
integer(kind = kint), dimension(:), allocatable, private normgi_by_primes::iexp_ti private
Definition at line 17 of file normgi_by_primes.f90.
Referenced by alloc_int_prime_ks(), dealloc_int_prime_ks(), and gs_prime().
int_prime_ks
integer(kind = kint), dimension(:), allocatable, private normgi_by_primes::int_prime_ks private
Definition at line 10 of file normgi_by_primes.f90.
Referenced by alloc_int_prime_ks(), conut_prims_normgi(), dealloc_int_prime_ks(), gs_prime(), and resize_int_prime_ks().
iprm_ks
integer(kind = kint), dimension(:,:), allocatable, private normgi_by_primes::iprm_ks private
Definition at line 13 of file normgi_by_primes.f90.
Referenced by alloc_int_prime_ks(), conut_prims_normgi(), dealloc_int_prime_ks(), and gs_prime().
itbl_prime_ks
integer(kind = kint), dimension(:), allocatable normgi_by_primes::itbl_prime_ks
Definition at line 12 of file normgi_by_primes.f90.
Referenced by alloc_int_prime_ks(), conut_prims_normgi(), dealloc_int_prime_ks(), and gs_prime().
nmax_prms
integer(kind = kint), private normgi_by_primes::nmax_prms private
Definition at line 9 of file normgi_by_primes.f90.
Referenced by alloc_int_prime_ks(), conut_prims_normgi(), gs_prime(), and resize_int_prime_ks().
num_fact
integer(kind = kint), private normgi_by_primes::num_fact private
Definition at line 9 of file normgi_by_primes.f90.
Referenced by alloc_int_prime_ks(), conut_prims_normgi(), gs_prime(), and resize_int_prime_ks().
num_prm_ks
integer(kind = kint), dimension(:), allocatable, private normgi_by_primes::num_prm_ks private
Definition at line 11 of file normgi_by_primes.f90.
Referenced by alloc_int_prime_ks(), conut_prims_normgi(), dealloc_int_prime_ks(), and gs_prime().