CALYPSO: set_and_cal_udt_data Module Reference
set_and_cal_udt_data Module Reference
set mesh and field data from UCD data input
Functions/Subroutines
subroutine const_udt_local_nodes (numnod, xx, ucd)
subroutine const_udt_local_connect (internal_node, nele, nnod_ele, ie, ucd)
subroutine const_udt_global_connect (internal_node, nele, nnod_ele, iele_global, ie, ucd)
subroutine, private set_udt_local_nodes (numnod, xx, ucd)
subroutine, private set_udt_local_connect (internal_node, nele, nnod_ele, ie, ucd)
subroutine, private set_udt_global_connect (internal_node, nele, nnod_ele, iele_global, ie, ucd)
subroutine set_one_field_to_udt_data (nnod, numdir, i_field, d_nod, ucd)
subroutine set_one_field_by_udt_data (nnod, numdir, i_field, d_nod, ucd)
subroutine set_field_by_udt_data (nnod, num_fld, ntot_cmp, istack_comp, phys_name, d_nod, ucd)
subroutine add_field_by_udt_data (nnod, num_fld, ntot_cmp, istack_comp, phys_name, d_nod, ucd)
subroutine subtract_field_by_udt_data (nnod, num_fld, ntot_cmp, istack_comp, phys_name, d_nod, ucd)
subroutine find_field_id_in_ucd (ucd, field_name, i_field, ncomp)
Detailed Description
set mesh and field data from UCD data input
      subroutine const_udt_local_nodes(numnod, xx, ucd)
      subroutine const_udt_local_connect(internal_node,               &
     &          nele, nnod_ele, ie, ucd)
      subroutine const_udt_global_connect(internal_node,              &
     &          nele, nnod_ele, iele_global, ie, ucd)
      subroutine set_one_field_to_udt_data(nnod, numdir, i_field,     &
     &          d_nod, ucd)
      subroutine set_one_field_by_udt_data(nnod, numdir, i_field,     &
     &          d_nod, ucd)
      subroutine set_field_by_udt_data(nnod, num_fld, ntot_cmp,       &
     &          istack_comp, phys_name, d_nod, ucd)
      subroutine add_field_by_udt_data(nnod, num_fld, ntot_cmp,       &
     &          istack_comp, phys_name, d_nod, ucd)
      subroutine subtract_field_by_udt_data(nnod, num_fld, ntot_cmp,  &
     &          istack_comp, phys_name, d_nod, ucd)
      subroutine find_field_id_in_ucd(ucd, field_name)
Function/Subroutine Documentation
add_field_by_udt_data()
subroutine set_and_cal_udt_data::add_field_by_udt_data (integer(kind=kint), intent(in) nnod, integer(kind=kint), intent(in) num_fld, integer(kind=kint), intent(in) ntot_cmp, integer(kind=kint), dimension(0:num_fld), intent(in) istack_comp, character (len=kchara), dimension(num_fld), intent(in) phys_name, real(kind = kreal), dimension(nnod,ntot_cmp), intent(inout) d_nod, type(ucd_data), intent(in) ucd)
Definition at line 273 of file set_and_cal_udt_data.f90.
References find_field_id_in_ucd().
Referenced by output_parallel_ucd_file::add_ucd_to_data().
const_udt_global_connect()
subroutine set_and_cal_udt_data::const_udt_global_connect (integer(kind=kint), intent(in) internal_node, integer(kind=kint), intent(in) nele, integer(kind=kint), intent(in) nnod_ele, integer(kind=kint_gl), dimension(nele), intent(in) iele_global, integer(kind=kint), dimension(nele, nnod_ele), intent(in) ie, type(ucd_data), intent(inout) ucd)
Definition at line 88 of file set_and_cal_udt_data.f90.
References t_ucd_data::allocate_ucd_ele(), count_overlap::count_interier_element(), and set_udt_global_connect().
Referenced by set_ucd_data_to_type::link_global_mesh_2_ucd().
const_udt_local_connect()
subroutine set_and_cal_udt_data::const_udt_local_connect (integer(kind=kint), intent(in) internal_node, integer(kind=kint), intent(in) nele, integer(kind=kint), intent(in) nnod_ele, integer(kind=kint), dimension(nele, nnod_ele), intent(in) ie, type(ucd_data), intent(inout) ucd)
Definition at line 65 of file set_and_cal_udt_data.f90.
References t_ucd_data::allocate_ucd_ele(), count_overlap::count_interier_element(), and set_udt_local_connect().
Referenced by set_ucd_data_to_type::link_local_mesh_2_ucd().
const_udt_local_nodes()
subroutine set_and_cal_udt_data::const_udt_local_nodes (integer(kind=kint), intent(in) numnod, real(kind=kreal), dimension(numnod,3), intent(in) xx, type(ucd_data), intent(inout) ucd)
Definition at line 49 of file set_and_cal_udt_data.f90.
References t_ucd_data::allocate_ucd_node(), and set_udt_local_nodes().
Referenced by set_ucd_data_to_type::link_local_mesh_2_ucd().
find_field_id_in_ucd()
subroutine set_and_cal_udt_data::find_field_id_in_ucd (type(ucd_data), intent(in) ucd, character(len = kchara), intent(in) field_name, integer(kind = kint), intent(inout) i_field, integer(kind = kint), intent(inout) ncomp)
Definition at line 340 of file set_and_cal_udt_data.f90.
Referenced by add_field_by_udt_data(), set_field_by_udt_data(), and subtract_field_by_udt_data().
set_field_by_udt_data()
subroutine set_and_cal_udt_data::set_field_by_udt_data (integer(kind=kint), intent(in) nnod, integer(kind=kint), intent(in) num_fld, integer(kind=kint), intent(in) ntot_cmp, integer(kind=kint), dimension(0:num_fld), intent(in) istack_comp, character (len=kchara), dimension(num_fld), intent(in) phys_name, real(kind = kreal), dimension(nnod,ntot_cmp), intent(inout) d_nod, type(ucd_data), intent(in) ucd)
Definition at line 241 of file set_and_cal_udt_data.f90.
References find_field_id_in_ucd().
Referenced by output_parallel_ucd_file::set_data_by_read_ucd(), and output_parallel_ucd_file::set_data_by_read_ucd_once().
set_one_field_by_udt_data()
subroutine set_and_cal_udt_data::set_one_field_by_udt_data (integer(kind=kint), intent(in) nnod, integer(kind=kint), intent(in) numdir, integer(kind=kint), intent(in) i_field, real(kind = kreal), dimension(nnod,numdir), intent(inout) d_nod, type(ucd_data), intent(in) ucd)
Definition at line 217 of file set_and_cal_udt_data.f90.
set_one_field_to_udt_data()
subroutine set_and_cal_udt_data::set_one_field_to_udt_data (integer(kind=kint), intent(in) nnod, integer(kind=kint), intent(in) numdir, integer(kind=kint), intent(in) i_field, real(kind = kreal), dimension(nnod,numdir), intent(in) d_nod, type(ucd_data), intent(inout) ucd)
Definition at line 194 of file set_and_cal_udt_data.f90.
set_udt_global_connect()
subroutine, private set_and_cal_udt_data::set_udt_global_connect (integer(kind=kint), intent(in) internal_node, integer(kind=kint), intent(in) nele, integer(kind=kint), intent(in) nnod_ele, integer(kind=kint_gl), dimension(nele), intent(in) iele_global, integer(kind=kint), dimension(nele, nnod_ele), intent(in) ie, type(ucd_data), intent(inout) ucd) private
Definition at line 164 of file set_and_cal_udt_data.f90.
Referenced by const_udt_global_connect().
set_udt_local_connect()
subroutine, private set_and_cal_udt_data::set_udt_local_connect (integer(kind=kint), intent(in) internal_node, integer(kind=kint), intent(in) nele, integer(kind=kint), intent(in) nnod_ele, integer(kind=kint), dimension(nele, nnod_ele), intent(in) ie, type(ucd_data), intent(inout) ucd) private
Definition at line 137 of file set_and_cal_udt_data.f90.
Referenced by const_udt_local_connect().
set_udt_local_nodes()
subroutine, private set_and_cal_udt_data::set_udt_local_nodes (integer(kind=kint), intent(in) numnod, real(kind=kreal), dimension(numnod,3), intent(in) xx, type(ucd_data), intent(inout) ucd) private
Definition at line 113 of file set_and_cal_udt_data.f90.
Referenced by const_udt_local_nodes().
subtract_field_by_udt_data()
subroutine set_and_cal_udt_data::subtract_field_by_udt_data (integer(kind=kint), intent(in) nnod, integer(kind=kint), intent(in) num_fld, integer(kind=kint), intent(in) ntot_cmp, integer(kind=kint), dimension(0:num_fld), intent(in) istack_comp, character (len=kchara), dimension(num_fld), intent(in) phys_name, real(kind = kreal), dimension(nnod,ntot_cmp), intent(inout) d_nod, type(ucd_data), intent(in) ucd)
Definition at line 306 of file set_and_cal_udt_data.f90.
References find_field_id_in_ucd().
Referenced by output_parallel_ucd_file::subtract_by_ucd_data().