CALYPSO: t_solver_sr Module Reference
t_solver_sr Module Reference
Work area for data communications.
Data Types
type send_recv_real_buffer
Structure of communication buffer for real.
type send_recv_status
Structure of communication flags.
Functions/Subroutines
subroutine resize_work_sr (NB, NPE_SEND, NPE_RECV, NTOT_SEND, NTOT_RECV, SR_sig, SR_r)
subroutine resize_work_itp_sr (NB, NPE_SEND, NPE_RECV, NTOT_RECV, SR_sig, SR_r)
subroutine calypso_send_recv_fin (npe_send, isend_self, SR_sig)
subroutine resize_sr_flag (NPE_SEND, NPE_RECV, SR_sig)
subroutine dealloc_sr_flag (SR_sig)
subroutine, private resize_wsend_sr (NB, NTOT_SEND, SR_r)
subroutine, private resize_wrecv_sr (NB, NTOT_RECV, SR_r)
Detailed Description
Work area for data communications.
      subroutine resize_work_SR(NB, NPE_SEND, NPE_RECV,               &
     &          NTOT_SEND, NTOT_RECV, SR_sig, SR_r)
        type(send_recv_status), intent(inout) :: SR_sig
        type(send_recv_real_buffer), intent(inout) :: SR_r
      subroutine resize_work_itp_SR                                   &
     &         (NB, NPE_SEND, NPE_RECV, NTOT_RECV, SR_sig, SR_r)
        type(send_recv_status), intent(inout) :: SR_sig
        type(send_recv_real_buffer), intent(inout) :: SR_r
      subroutine resize_SR_flag(NPE_SEND, NPE_RECV, SR_sig)
      subroutine dealloc_SR_flag(SR_sig)
        integer(kind = kint), intent(in)   ::  NPE_SEND, NPE_RECV
        type(send_recv_status), intent(inout) :: SR_sig
      subroutine calypso_send_recv_fin(npe_send, isend_self, SR_sig)
        integer(kind = kint), intent(in) :: npe_send, isend_self
        type(send_recv_status), intent(inout) :: SR_sig
Parameters
NB Number of components
NTOT_SEND Total number of data points for export
NTOT_RECV Total number of data points for import
NPE_SEND Number of processses to receive
NPE_RECV Number of processses to send
Parameters
N_SHIFT number of shifting of the reversed import table
ITEM_IMPORT import table
REV_IMPORT reversed import table
Function/Subroutine Documentation
calypso_send_recv_fin()
subroutine t_solver_sr::calypso_send_recv_fin (integer(kind = kint), intent(in) npe_send, integer(kind = kint), intent(in) isend_self, type(send_recv_status), intent(inout) SR_sig)
Definition at line 119 of file t_solver_SR.f90.
References calypso_mpi::ierr_mpi.
Referenced by calypso_sr::calypso_send_recv(), calypso_sr_2::calypso_send_recv_2(), calypso_sr_3::calypso_send_recv_3(), calypso_sr::calypso_send_recv_3x1(), calypso_sr_2::calypso_send_recv_3x2(), calypso_sr_3::calypso_send_recv_3x3(), calypso_sr_6::calypso_send_recv_3x6(), calypso_sr_n::calypso_send_recv_3xn(), calypso_sr_6::calypso_send_recv_6(), calypso_sr_int::calypso_send_recv_int(), calypso_sr_int::calypso_send_recv_int8(), calypso_sr_n::calypso_send_recv_n(), and spherical_srs_n::finish_send_recv_sph().
dealloc_sr_flag()
subroutine t_solver_sr::dealloc_sr_flag (type(send_recv_status), intent(inout) SR_sig)
Definition at line 166 of file t_solver_SR.f90.
resize_sr_flag()
subroutine t_solver_sr::resize_sr_flag (integer(kind = kint), intent(in) NPE_SEND, integer(kind = kint), intent(in) NPE_RECV, type(send_recv_status), intent(inout) SR_sig)
Definition at line 138 of file t_solver_SR.f90.
Referenced by reverse_sr_int::element_num_reverse_sr(), reverse_sr_int::local_node_id_reverse_sr(), t_solver_sr_int8::resize_i8work_itp_sr_t(), t_solver_sr_int8::resize_i8work_sr(), t_solver_sr_int::resize_iwork_itp_sr(), t_solver_sr_int::resize_iwork_sr_t(), resize_work_itp_sr(), resize_work_sr(), reverse_sr_real::reverse_send_recv_3(), reverse_sr_int::reverse_send_recv_int(), reverse_sr_int8::reverse_send_recv_int8(), and solver_sr_int::solver_send_recv_num().
resize_work_itp_sr()
subroutine t_solver_sr::resize_work_itp_sr (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) NPE_SEND, integer(kind = kint), intent(in) NPE_RECV, integer(kind = kint), intent(in) NTOT_RECV, type(send_recv_status), intent(inout) SR_sig, type(send_recv_real_buffer), intent(inout) SR_r)
Definition at line 102 of file t_solver_SR.f90.
References resize_sr_flag(), and resize_wrecv_sr().
resize_work_sr()
subroutine t_solver_sr::resize_work_sr (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) NPE_SEND, integer(kind = kint), intent(in) NPE_RECV, integer(kind = kint), intent(in) NTOT_SEND, integer(kind = kint), intent(in) NTOT_RECV, type(send_recv_status), intent(inout) SR_sig, type(send_recv_real_buffer), intent(inout) SR_r)
Definition at line 84 of file t_solver_SR.f90.
References resize_sr_flag(), resize_wrecv_sr(), and resize_wsend_sr().
Referenced by calypso_sr::calypso_send_recv(), calypso_sr_2::calypso_send_recv_2(), calypso_sr_3::calypso_send_recv_3(), calypso_sr::calypso_send_recv_3x1(), calypso_sr_2::calypso_send_recv_3x2(), calypso_sr_3::calypso_send_recv_3x3(), calypso_sr_6::calypso_send_recv_3x6(), calypso_sr_n::calypso_send_recv_3xn(), calypso_sr_6::calypso_send_recv_6(), calypso_sr_n::calypso_send_recv_n(), sel_spherical_srs::check_calypso_sph_buf_n(), calypso_sr_core::check_calypso_sr_stack(), nod_phys_send_recv::init_send_recv(), solver_sr::solver_send_recv(), solver_sr_3::solver_send_recv_3(), solver_sr_3::solver_send_recv_3x3(), solver_sr_6::solver_send_recv_6(), solver_sr_n::solver_send_recv_n(), solver_sr_n::solver_send_recv_nx3(), and solver_sr::solver_send_recvx3().
resize_wrecv_sr()
subroutine, private t_solver_sr::resize_wrecv_sr (integer(kind=kint), intent(in) NB, integer(kind=kint), intent(in) NTOT_RECV, type(send_recv_real_buffer), intent(inout) SR_r) private
Definition at line 199 of file t_solver_SR.f90.
Referenced by resize_work_itp_sr(), and resize_work_sr().
resize_wsend_sr()
subroutine, private t_solver_sr::resize_wsend_sr (integer(kind=kint), intent(in) NB, integer(kind=kint), intent(in) NTOT_SEND, type(send_recv_real_buffer), intent(inout) SR_r) private
Definition at line 179 of file t_solver_SR.f90.
Referenced by resize_work_sr().