CALYPSO: leg_fwd_trans_sym_mat_jt Module Reference
leg_fwd_trans_sym_mat_jt Module Reference
forward Legendre transform (Blocked loop version)
Functions/Subroutines
subroutine legendre_f_trans_sym_mat_jt (iflag_matmul, ncomp, nvector, nscalar, sph_rtm, sph_rlm, comm_rtm, comm_rlm, idx_trns, asin_theta_1d_rtm, g_sph_rlm, weight_rtm, n_WR, n_WS, WR, WS, WK_l_tsp)
Variables
integer, external omp_get_max_threads
Detailed Description
forward Legendre transform (Blocked loop version)
      subroutine legendre_f_trans_sym_mat_jt                          &
     &         (iflag_matmul, ncomp, nvector, nscalar,                &
     &          sph_rtm, sph_rlm, comm_rtm, comm_rlm, idx_trns,       &
     &          asin_theta_1d_rtm, g_sph_rlm, weight_rtm,             &
     &          n_WR, n_WS, WR, WS, WK_l_tsp)
        Input:  vr_rtm   (Order: radius,theta,phi)
        Output: sp_rlm   (Order: poloidal,diff_poloidal,toroidal)
        type(sph_rlm_grid), intent(in) :: sph_rlm
        type(sph_rtm_grid), intent(in) :: sph_rtm
        type(sph_comm_tbl), intent(in) :: comm_rlm, comm_rtm
        type(index_4_sph_trans), intent(in) :: idx_trns
        type(leg_trns_theta_omp_work), intent(inout) :: WK_l_tsp
Parameters
ncomp Total number of components for spherical transform
nvector Number of vector for spherical transform
nscalar Number of scalar (including tensor components) for spherical transform
Function/Subroutine Documentation
legendre_f_trans_sym_mat_jt()
subroutine leg_fwd_trans_sym_mat_jt::legendre_f_trans_sym_mat_jt (integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_comm_tbl), intent(in) comm_rtm, type(sph_comm_tbl), intent(in) comm_rlm, type(index_4_sph_trans), intent(in) idx_trns, real(kind = kreal), dimension(sph_rtm%nidx_rtm(2)), intent(in) asin_theta_1d_rtm, real(kind = kreal), dimension(sph_rlm%nidx_rlm(2),17), intent(in) g_sph_rlm, real(kind = kreal), dimension(sph_rtm%nidx_rtm(2)), intent(in) weight_rtm, integer(kind = kint), intent(in) n_WR, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_wr), intent(inout) WR, real (kind=kreal), dimension(n_ws), intent(inout) WS, type(leg_trns_theta_omp_work), intent(inout) WK_l_tsp)
Definition at line 60 of file leg_fwd_trans_sym_mat_jt.f90.
References cal_sp_rlm_sym_mat_tsmp::cal_sp_rlm_sym_mat_rout(), m_work_time::end_elapsed_time(), m_elapsed_labels_sph_trns::iflag_sdt_time, m_elapsed_labels_sph_trns::ist_elapsed_sdt, matmul_for_legendre_trans::matmul_fwd_leg_trans_pjl(), m_machine_parameter::np_smp, set_vr_rtm_sym_mat_tsmp::set_vr_rtm_sym_mat_rout(), m_work_time::start_elapsed_time(), and sum_spectr_over_smp_segment::sum_spectr_over_kr_in().
Referenced by legendre_transform_sym_tomp::leg_forward_trans_smat_jt().
Variable Documentation
omp_get_max_threads
integer, external leg_fwd_trans_sym_mat_jt::omp_get_max_threads
Definition at line 52 of file leg_fwd_trans_sym_mat_jt.f90.