CALYPSO: gz_mpi_domain_data_io Module Reference
gz_mpi_domain_data_io Module Reference
Routine for gzipped binary doimain data IO.
Functions/Subroutines
subroutine gz_mpi_check_num_of_domains (IO_param)
subroutine gz_mpi_read_domain_info (IO_param, comm_IO)
subroutine gz_mpi_read_import_data (IO_param, comm_IO)
subroutine gz_mpi_read_export_data (IO_param, comm_IO)
subroutine gz_mpi_write_domain_info (IO_param, comm_IO)
subroutine gz_mpi_write_import_data (IO_param, comm_IO)
subroutine gz_mpi_write_export_data (IO_param, comm_IO)
subroutine gz_mpi_write_int_stack (IO_param, num, istack)
subroutine, private gz_mpi_write_int_vector (IO_param, num, int_dat)
subroutine gz_mpi_read_int_stack (IO_param, num, istack, ntot)
subroutine, private gz_mpi_read_int_vector (IO_param, num, int_dat)
subroutine gz_mpi_read_comm_table (IO_param, ncolumn, num, int_dat)
subroutine gz_mpi_write_comm_table (IO_param, ncolumn, num, int_dat)
Variables
type(buffer_4_gzip), private zbuf
Detailed Description
Routine for gzipped binary doimain data IO.
      subroutine gz_mpi_check_num_of_domains(IO_param)
      subroutine gz_mpi_read_domain_info(IO_param, comm_IO)
      subroutine gz_mpi_read_import_data(IO_param, comm_IO)
      subroutine gz_mpi_read_export_data(IO_param, comm_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(communication_table), intent(inout) :: comm_IO
      subroutine gz_mpi_write_domain_info(IO_param, comm_IO)
      subroutine gz_mpi_write_import_data(IO_param, comm_IO)
      subroutine gz_mpi_write_export_data(IO_param, comm_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(communication_table), intent(in) :: comm_IO
      subroutine gz_mpi_read_int_stack(IO_param, num, istack, ntot)
      subroutine gz_mpi_read_comm_table                               &
     &         (IO_param, ncolumn, num, int_dat)
      subroutine gz_mpi_write_int_stack(IO_param, num, istack)
      subroutine gz_mpi_write_comm_table                              &
     &         (IO_param, ncolumn, num, int_dat)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
Function/Subroutine Documentation
gz_mpi_check_num_of_domains()
subroutine gz_mpi_domain_data_io::gz_mpi_check_num_of_domains (type(calypso_mpi_io_params), intent(inout) IO_param)
Definition at line 55 of file gz_MPI_domain_data_IO.f90.
References gz_mpi_ascii_data_io::gz_mpi_read_charahead(), m_error_ids::ierr_file, data_io_to_textline::len_int_txt, and data_io_to_textline::read_integer_textline().
Referenced by gz_mpi_read_domain_info().
gz_mpi_read_comm_table()
subroutine gz_mpi_domain_data_io::gz_mpi_read_comm_table (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint), intent(in) ncolumn, integer(kind = kint), intent(in) num, integer(kind=kint), dimension(num), intent(inout) int_dat)
Definition at line 277 of file gz_MPI_domain_data_IO.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), gz_mpi_ascii_data_io::gz_mpi_read_charahead(), zlib_cvt_ascii_comm_tbl::infleate_comm_table(), data_io_to_textline::len_byte_stack_textline(), data_io_to_textline::read_byte_stack_textline(), and zbuf.
Referenced by gz_mpi_read_export_data(), gz_mpi_spherical_model_io::gz_mpi_read_gl_reso_sph(), gz_mpi_groups_io::gz_mpi_read_group_data(), gz_mpi_read_import_data(), gz_mpi_spherical_model_io::gz_mpi_read_rank_4_sph(), and gz_mpi_groups_io::gz_mpi_read_surf_grp_item().
gz_mpi_read_domain_info()
subroutine gz_mpi_domain_data_io::gz_mpi_read_domain_info (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(inout) comm_IO)
Definition at line 74 of file gz_MPI_domain_data_IO.f90.
References t_comm_table::alloc_neighbouring_id(), gz_mpi_check_num_of_domains(), gz_mpi_read_int_vector(), and gz_mpi_ascii_data_io::gz_mpi_read_num_of_data().
Referenced by gz_mpi_edge_data_io::gz_mpi_read_edge_connect(), gz_mpi_element_data_io::gz_mpi_read_ele_comm_table(), gz_mpi_sph_modes_data_io::gz_mpi_read_geom_rtm_data(), gz_mpi_sph_modes_data_io::gz_mpi_read_geom_rtp_data(), gz_mpi_sph_modes_data_io::gz_mpi_read_modes_rlm_data(), gz_mpi_mesh_data_io::gz_mpi_read_num_node(), gz_mpi_sph_modes_data_io::gz_mpi_read_spectr_rj_data(), and gz_mpi_surface_data_io::gz_mpi_read_surf_connect().
gz_mpi_read_export_data()
subroutine gz_mpi_domain_data_io::gz_mpi_read_export_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(inout) comm_IO)
Definition at line 121 of file gz_MPI_domain_data_IO.f90.
References t_comm_table::alloc_export_item(), t_comm_table::alloc_export_num(), gz_mpi_read_comm_table(), gz_mpi_read_int_stack(), gz_mpi_ascii_data_io::gz_mpi_read_num_of_data(), and m_constants::ione.
Referenced by gz_mpi_edge_data_io::gz_mpi_read_edge_connect(), gz_mpi_element_data_io::gz_mpi_read_ele_comm_table(), gz_mpi_mesh_data_io::gz_mpi_read_geometry_data(), and gz_mpi_surface_data_io::gz_mpi_read_surf_connect().
gz_mpi_read_import_data()
subroutine gz_mpi_domain_data_io::gz_mpi_read_import_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(inout) comm_IO)
Definition at line 97 of file gz_MPI_domain_data_IO.f90.
References t_comm_table::alloc_import_item(), t_comm_table::alloc_import_num(), gz_mpi_read_comm_table(), gz_mpi_read_int_stack(), gz_mpi_ascii_data_io::gz_mpi_read_num_of_data(), and m_constants::ione.
Referenced by gz_mpi_edge_data_io::gz_mpi_read_edge_connect(), gz_mpi_element_data_io::gz_mpi_read_ele_comm_table(), gz_mpi_sph_modes_data_io::gz_mpi_read_geom_rtm_data(), gz_mpi_sph_modes_data_io::gz_mpi_read_geom_rtp_data(), gz_mpi_mesh_data_io::gz_mpi_read_geometry_data(), gz_mpi_sph_modes_data_io::gz_mpi_read_modes_rlm_data(), gz_mpi_sph_modes_data_io::gz_mpi_read_spectr_rj_data(), and gz_mpi_surface_data_io::gz_mpi_read_surf_connect().
gz_mpi_read_int_stack()
subroutine gz_mpi_domain_data_io::gz_mpi_read_int_stack (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) num, integer(kind=kint), dimension(0:num), intent(inout) istack, integer(kind=kint), intent(inout) ntot)
Definition at line 229 of file gz_MPI_domain_data_IO.f90.
References gz_mpi_read_int_vector().
Referenced by gz_mpi_read_export_data(), gz_mpi_groups_io::gz_mpi_read_group_data(), gz_mpi_read_import_data(), and gz_mpi_groups_io::gz_mpi_read_surf_grp_data().
gz_mpi_read_int_vector()
subroutine, private gz_mpi_domain_data_io::gz_mpi_read_int_vector (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) num, integer(kind=kint), dimension(num), intent(inout) int_dat) private
Definition at line 248 of file gz_MPI_domain_data_IO.f90.
References gz_mpi_ascii_data_io::gz_mpi_read_characters(), gz_mpi_ascii_data_io::gz_mpi_read_charahead(), data_io_to_textline::len_byte_stack_textline(), data_io_to_textline::len_multi_int_textline(), data_io_to_textline::read_byte_stack_textline(), and data_io_to_textline::read_multi_int_textline().
Referenced by gz_mpi_read_domain_info(), and gz_mpi_read_int_stack().
gz_mpi_write_comm_table()
subroutine gz_mpi_domain_data_io::gz_mpi_write_comm_table (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint), intent(in) ncolumn, integer(kind = kint), intent(in) num, integer(kind = kint), dimension(num), intent(in) int_dat)
Definition at line 319 of file gz_MPI_domain_data_IO.f90.
References t_buffer_4_gzip::dealloc_zip_buffer(), zlib_cvt_ascii_comm_tbl::defleate_comm_table(), gz_mpi_ascii_data_io::gz_mpi_write_num_of_data(), gz_mpi_ascii_data_io::gz_mpi_write_stack_over_domain(), and zbuf.
Referenced by gz_mpi_write_export_data(), gz_mpi_spherical_model_io::gz_mpi_write_gl_reso_sph(), gz_mpi_groups_io::gz_mpi_write_grp_data(), gz_mpi_write_import_data(), gz_mpi_spherical_model_io::gz_mpi_write_rank_4_sph(), and gz_mpi_groups_io::gz_mpi_write_surf_grp_item().
gz_mpi_write_domain_info()
subroutine gz_mpi_domain_data_io::gz_mpi_write_domain_info (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(in) comm_IO)
Definition at line 146 of file gz_MPI_domain_data_IO.f90.
References gz_mpi_ascii_data_io::gz_mpi_write_charahead(), gz_mpi_write_int_vector(), data_io_to_textline::integer_textline(), and data_io_to_textline::len_int_txt.
Referenced by gz_mpi_edge_data_io::gz_mpi_write_edge_connect(), gz_mpi_element_data_io::gz_mpi_write_ele_comm_table(), gz_mpi_sph_modes_data_io::gz_mpi_write_geom_rtm_data(), gz_mpi_sph_modes_data_io::gz_mpi_write_geom_rtp_data(), gz_mpi_mesh_data_io::gz_mpi_write_geometry_data(), gz_mpi_sph_modes_data_io::gz_mpi_write_modes_rlm_data(), gz_mpi_sph_modes_data_io::gz_mpi_write_spectr_rj_data(), and gz_mpi_surface_data_io::gz_mpi_write_surf_connect().
gz_mpi_write_export_data()
subroutine gz_mpi_domain_data_io::gz_mpi_write_export_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(in) comm_IO)
Definition at line 182 of file gz_MPI_domain_data_IO.f90.
References gz_mpi_write_comm_table(), gz_mpi_write_int_stack(), and m_constants::ione.
Referenced by gz_mpi_edge_data_io::gz_mpi_write_edge_connect(), gz_mpi_element_data_io::gz_mpi_write_ele_comm_table(), gz_mpi_mesh_data_io::gz_mpi_write_geometry_data(), and gz_mpi_surface_data_io::gz_mpi_write_surf_connect().
gz_mpi_write_import_data()
subroutine gz_mpi_domain_data_io::gz_mpi_write_import_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(communication_table), intent(in) comm_IO)
Definition at line 166 of file gz_MPI_domain_data_IO.f90.
References gz_mpi_write_comm_table(), gz_mpi_write_int_stack(), and m_constants::ione.
Referenced by gz_mpi_edge_data_io::gz_mpi_write_edge_connect(), gz_mpi_element_data_io::gz_mpi_write_ele_comm_table(), gz_mpi_sph_modes_data_io::gz_mpi_write_geom_rtm_data(), gz_mpi_sph_modes_data_io::gz_mpi_write_geom_rtp_data(), gz_mpi_mesh_data_io::gz_mpi_write_geometry_data(), gz_mpi_sph_modes_data_io::gz_mpi_write_modes_rlm_data(), gz_mpi_sph_modes_data_io::gz_mpi_write_spectr_rj_data(), and gz_mpi_surface_data_io::gz_mpi_write_surf_connect().
gz_mpi_write_int_stack()
subroutine gz_mpi_domain_data_io::gz_mpi_write_int_stack (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) num, integer(kind=kint), dimension(0:num), intent(in) istack)
Definition at line 198 of file gz_MPI_domain_data_IO.f90.
References gz_mpi_write_int_vector().
Referenced by gz_mpi_write_export_data(), gz_mpi_groups_io::gz_mpi_write_grp_data(), gz_mpi_write_import_data(), and gz_mpi_groups_io::gz_mpi_write_surf_grp_data().
gz_mpi_write_int_vector()
subroutine, private gz_mpi_domain_data_io::gz_mpi_write_int_vector (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) num, integer(kind=kint), dimension(num), intent(in) int_dat) private
Definition at line 212 of file gz_MPI_domain_data_IO.f90.
References gz_mpi_ascii_data_io::gz_mpi_write_characters(), gz_mpi_ascii_data_io::gz_mpi_write_num_of_data(), data_io_to_textline::len_multi_int_textline(), and data_io_to_textline::multi_int_textline().
Referenced by gz_mpi_write_domain_info(), and gz_mpi_write_int_stack().
Variable Documentation
zbuf
type(buffer_4_gzip), private gz_mpi_domain_data_io::zbuf private
Definition at line 47 of file gz_MPI_domain_data_IO.f90.
Referenced by gz_mpi_sph_gl_1d_idx_io::gz_mpi_read_1d_gl_address(), gz_mpi_read_comm_table(), gz_mpi_integer_list_io::gz_mpi_read_ele_connect(), gz_mpi_integer_list_io::gz_mpi_read_element_type(), gz_mpi_integer_list_io::gz_mpi_read_int_list(), gz_mpi_position_io::gz_mpi_read_node_position(), gz_mpi_vectors_io::gz_mpi_read_vector(), gz_mpi_sph_gl_1d_idx_io::gz_mpi_write_1d_gl_address(), gz_mpi_write_comm_table(), gz_mpi_integer_list_io::gz_mpi_write_ele_connect(), gz_mpi_integer_list_io::gz_mpi_write_element_type(), gz_mpi_integer_list_io::gz_mpi_write_int_list(), gz_mpi_position_io::gz_mpi_write_node_position(), gz_mpi_vectors_io::gz_mpi_write_vector(), gz_mpi_viewer_mesh_io::gz_mpi_write_viewer_grp_item(), and gz_mpi_viewer_mesh_io::gz_mpi_write_viewer_position().