CALYPSO: mesh_file_io Module Reference
mesh_file_io Module Reference
ASCII mesh file IO.
Functions/Subroutines
subroutine read_mesh_file (id_rank, file_name, mesh_IO, group_IO, ierr)
subroutine read_mesh_geometry (id_rank, file_name, mesh_IO, ierr)
subroutine read_node_size (id_rank, file_name, mesh_IO, ierr)
subroutine read_geometry_size (id_rank, file_name, mesh_IO, ierr)
subroutine write_mesh_file (id_rank, file_name, mesh_IO, group_IO)
subroutine write_node_position_sph (id_rank, file_prefix, mesh_IO)
subroutine write_node_position_cyl (id_rank, file_prefix, mesh_IO)
Variables
integer(kind=kint), parameter, private input_file_code = 14
Detailed Description
ASCII mesh file IO.
      subroutine read_mesh_file                                       &
     &         (id_rank, file_name, mesh_IO, group_IO, ierr)
        type(mesh_geometry), intent(inout) :: mesh_IO
        type(mesh_groups), intent(inout) ::   group_IO
      subroutine read_mesh_geometry                                   &
     &         (id_rank, file_name, mesh_IO, ierr)
      subroutine read_node_size(id_rank, file_name, mesh_IO, ierr)
      subroutine read_geometry_size                                   &
     &         (id_rank, file_name, mesh_IO, ierr)
        type(mesh_geometry), intent(inout) :: mesh_IO
      subroutine write_mesh_file                                      &
     &         (id_rank, file_name, mesh_IO, group_IO)
        type(mesh_geometry), intent(in) :: mesh_IO
        type(mesh_groups), intent(in) ::   group_IO
      subroutine write_node_position_sph                              &
     &         (id_rank, file_prefix, mesh_IO)
      subroutine write_node_position_cyl                              &
     &         (id_rank, file_prefix, mesh_IO)
        type(mesh_geometry), intent(inout) :: mesh_IO
Function/Subroutine Documentation
read_geometry_size()
subroutine mesh_file_io::read_geometry_size (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(inout) mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 129 of file mesh_file_IO.f90.
References m_machine_parameter::i_debug, input_file_code, and mesh_data_io::read_num_node_ele().
Referenced by mesh_io_select::sel_read_geometry_size().
read_mesh_file()
subroutine mesh_file_io::read_mesh_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(inout) mesh_IO, type(mesh_groups), intent(inout) group_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 54 of file mesh_file_IO.f90.
References m_machine_parameter::i_debug, input_file_code, mesh_data_io::read_geometry_data(), and mesh_data_io::read_mesh_groups().
Referenced by mesh_io_select::sel_read_mesh().
read_mesh_geometry()
subroutine mesh_file_io::read_mesh_geometry (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(inout) mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 81 of file mesh_file_IO.f90.
References m_machine_parameter::i_debug, input_file_code, and mesh_data_io::read_geometry_data().
Referenced by mesh_io_select::sel_read_mesh_geometry().
read_node_size()
subroutine mesh_file_io::read_node_size (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(inout) mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 106 of file mesh_file_IO.f90.
References m_machine_parameter::i_debug, input_file_code, and mesh_data_io::read_num_node().
Referenced by mesh_io_select::sel_read_node_size().
write_mesh_file()
subroutine mesh_file_io::write_mesh_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(mesh_geometry), intent(in) mesh_IO, type(mesh_groups), intent(in) group_IO)
Definition at line 154 of file mesh_file_IO.f90.
References m_machine_parameter::i_debug, input_file_code, mesh_data_io::write_geometry_data(), and mesh_data_io::write_mesh_groups().
Referenced by mesh_io_select::sel_write_mesh_file().
write_node_position_cyl()
subroutine mesh_file_io::write_node_position_cyl (integer, intent(in) id_rank, character(len=kchara), intent(in) file_prefix, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 209 of file mesh_file_IO.f90.
References set_parallel_file_name::add_process_id(), t_mesh_data::dealloc_node_geometry_io(), m_machine_parameter::i_debug, input_file_code, and mesh_data_io::output_node_cyl_geometry().
write_node_position_sph()
subroutine mesh_file_io::write_node_position_sph (integer, intent(in) id_rank, character(len=kchara), intent(in) file_prefix, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 179 of file mesh_file_IO.f90.
References set_parallel_file_name::add_process_id(), t_mesh_data::dealloc_node_geometry_io(), m_machine_parameter::i_debug, input_file_code, and mesh_data_io::output_node_sph_geometry().
Variable Documentation
input_file_code
integer(kind = kint), parameter, private mesh_file_io::input_file_code = 14 private
Definition at line 44 of file mesh_file_IO.f90.
Referenced by read_geometry_size(), read_mesh_file(), read_mesh_geometry(), read_node_size(), write_mesh_file(), write_node_position_cyl(), and write_node_position_sph().