CALYPSO: gz_element_connect_io Module Reference
gz_element_connect_io Module Reference
Element data IO using zlib.
Functions/Subroutines
subroutine gz_write_element_info (ele_IO, zbuf)
subroutine gz_write_surface_4_element (sfed_IO, zbuf)
subroutine gz_write_edge_4_element (sfed_IO, zbuf)
subroutine gz_read_number_of_element (ele_IO, zbuf)
subroutine gz_read_element_info (ele_IO, zbuf)
subroutine gz_read_surface_4_element (sfed_IO, zbuf)
subroutine gz_read_edge_4_element (sfed_IO, zbuf)
Variables
character(len=kchara), private fmt_txt
Detailed Description
Element data IO using zlib.
      subroutine gz_write_element_info(ele_IO, zbuf)
        type(element_data), intent(in) :: ele_IO
      subroutine gz_write_surface_4_element(sfed_IO, zbuf)
      subroutine gz_write_edge_4_element(sfed_IO, zbuf)
        type(surf_edge_IO_data), intent(in) :: sfed_IO
        type(buffer_4_gzip), intent(inout) :: zbuf
      subroutine gz_read_number_of_element(ele_IO, zbuf)
      subroutine gz_read_element_info(ele_IO, zbuf)
        type(element_data), intent(inout) :: ele_IO
      subroutine gz_read_surface_4_element(sfed_IO, zbuf)
      subroutine gz_read_edge_4_element(sfed_IO, zbuf)
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
        type(buffer_4_gzip), intent(inout) :: zbuf
Function/Subroutine Documentation
gz_read_edge_4_element()
subroutine gz_element_connect_io::gz_read_edge_4_element (type(surf_edge_io_data), intent(inout) sfed_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 194 of file gz_element_connect_IO.f90.
References t_surf_edge_io::alloc_edge_connect_io(), gzip_file_access::get_one_line_text_from_gz(), and skip_gz_comment::skip_gz_comment_int().
Referenced by gz_edge_data_io::gz_read_edge_connection().
gz_read_element_info()
subroutine gz_element_connect_io::gz_read_element_info (type(element_data), intent(inout) ele_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 135 of file gz_element_connect_IO.f90.
References t_geometry_data::alloc_ele_connectivity(), t_geometry_data::alloc_element_types(), gzip_file_access::get_one_line_text_from_gz(), gz_data_io::read_gz_multi_int(), and set_nnod_4_ele_by_type::s_set_nnod_4_ele_by_type().
Referenced by gz_edge_data_io::gz_read_edge_connection(), gz_mesh_data_io::gz_read_geometry_data(), and gz_surface_data_io::gz_read_surface_connection().
gz_read_number_of_element()
subroutine gz_element_connect_io::gz_read_number_of_element (type(element_data), intent(inout) ele_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 120 of file gz_element_connect_IO.f90.
References skip_gz_comment::skip_gz_comment_int().
Referenced by gz_edge_data_io::gz_read_edge_connection(), gz_mesh_data_io::gz_read_num_node_ele(), and gz_surface_data_io::gz_read_surface_connection().
gz_read_surface_4_element()
subroutine gz_element_connect_io::gz_read_surface_4_element (type(surf_edge_io_data), intent(inout) sfed_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 169 of file gz_element_connect_IO.f90.
References t_surf_edge_io::alloc_surface_connect_io(), gzip_file_access::get_one_line_text_from_gz(), and skip_gz_comment::skip_gz_comment_int().
Referenced by gz_edge_data_io::gz_read_edge_connection(), and gz_surface_data_io::gz_read_surface_connection().
gz_write_edge_4_element()
subroutine gz_element_connect_io::gz_write_edge_4_element (type(surf_edge_io_data), intent(in) sfed_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 95 of file gz_element_connect_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf().
Referenced by gz_edge_data_io::gz_write_edge_connection().
gz_write_element_info()
subroutine gz_element_connect_io::gz_write_element_info (type(element_data), intent(in) ele_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 44 of file gz_element_connect_IO.f90.
References fmt_txt, gzip_file_access::gz_write_textbuf_no_lf(), and gz_data_io::write_gz_multi_int_10i8().
Referenced by gz_edge_data_io::gz_write_edge_connection(), gz_mesh_data_io::gz_write_geometry_data(), and gz_surface_data_io::gz_write_surface_connection().
gz_write_surface_4_element()
subroutine gz_element_connect_io::gz_write_surface_4_element (type(surf_edge_io_data), intent(in) sfed_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 72 of file gz_element_connect_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf().
Referenced by gz_edge_data_io::gz_write_edge_connection(), and gz_surface_data_io::gz_write_surface_connection().
Variable Documentation
fmt_txt
character(len=kchara), private gz_element_connect_io::fmt_txt private
Definition at line 36 of file gz_element_connect_IO.f90.
Referenced by gz_write_element_info().