CALYPSO: normgi_by_fact Module Reference
normgi_by_fact Module Reference
Functions/Subroutines
double precision function gs_mul_fact (m1, l1, m2, l2, m3, l3)
double precision function gs_fact (m1, l1, m2, l2, m3, l3)
Function/Subroutine Documentation
gs_fact()
double precision function normgi_by_fact::gs_fact (integer(kind = kint), intent(in) m1, integer(kind = kint), intent(in) l1, integer(kind = kint), intent(in) m2, integer(kind = kint), intent(in) l2, integer(kind = kint), intent(in) m3, integer(kind = kint), intent(in) l3)
Definition at line 169 of file normgi_by_fact.f90.
References factorials::factorial(), and quicksort::quicksort_int().
gs_mul_fact()
double precision function normgi_by_fact::gs_mul_fact (integer(kind = kint), intent(in) m1, integer(kind = kint), intent(in) l1, integer(kind = kint), intent(in) m2, integer(kind = kint), intent(in) l2, integer(kind = kint), intent(in) m3, integer(kind = kint), intent(in) l3)
Definition at line 53 of file normgi_by_fact.f90.
References factorials::factorial(), and quicksort::quicksort_int().