CALYPSO: small_matmul_leg_trans_krin Module Reference
small_matmul_leg_trans_krin Module Reference
small Matrix products for Legendre transforms
Functions/Subroutines
subroutine matvec_fwd_leg_trans_pj (nkr, n_jk, V_k, P_j, S_kj)
subroutine matmul8_fwd_leg_trans_ptj (iflag_matmul, nkr, n_jk, V_kt, P_tj, S_kj)
subroutine matmul4_fwd_leg_trans_ptj (iflag_matmul, nkr, n_jk, V_kt, P_tj, S_kj)
subroutine matmul2_fwd_leg_trans_ptj (iflag_matmul, nkr, n_jk, V_kt, P_tj, S_kj)
subroutine matvec_bwd_leg_trans_pj (iflag_matmul, nkr, n_jk, S_kj, P_j, V_k)
subroutine matmul8_bwd_leg_trans_pjt (iflag_matmul, nkr, n_jk, S_kj, P_jt, V_kt)
subroutine matmul4_bwd_leg_trans_pjt (iflag_matmul, nkr, n_jk, S_kj, P_jt, V_kt)
subroutine matmul2_bwd_leg_trans_pjt (iflag_matmul, nkr, n_jk, S_kj, P_jt, V_kt)
Detailed Description
small Matrix products for Legendre transforms
      subroutine matvec_fwd_leg_trans_Pj(nkr, n_jk, V_k, P_j, S_kj)
        integer(kind = kint), intent(in) :: n_jk, nkr
        real(kind = kreal), intent(in) :: V_k(nkr)
        real(kind = kreal), intent(in) :: P_j(n_jk)
        real(kind = kreal), intent(inout) :: S_kj(nkr,n_jk)
      subroutine matmul8_fwd_leg_trans_Ptj                            &
     &         (iflag_matmul, nkr, n_jk, V_kt, P_tj, S_kj)
        integer(kind = kint), intent(in) :: n_jk, nkr
        real(kind = kreal), intent(in) :: V_kt(nkr,8)
        real(kind = kreal), intent(in) :: P_tj(8,n_jk)
        real(kind = kreal), intent(inout) :: S_kj(nkr,n_jk)
      subroutine matmul4_fwd_leg_trans_Ptj                            &
     &         (iflag_matmul, nkr, n_jk, V_kt, P_tj, S_kj)
        integer(kind = kint), intent(in) :: n_jk, nkr
        real(kind = kreal), intent(in) :: V_kt(nkr,4)
        real(kind = kreal), intent(in) :: P_tj(4,n_jk)
        real(kind = kreal), intent(inout) :: S_kj(nkr,n_jk)
      subroutine matmul2_fwd_leg_trans_Ptj                            &
     &         (iflag_matmul, nkr, n_jk, V_kt, P_tj, S_kj)
        integer(kind = kint), intent(in) :: n_jk, nkr
        real(kind = kreal), intent(in) :: V_kt(nkr,2)
        real(kind = kreal), intent(in) :: P_tj(2,n_jk)
        real(kind = kreal), intent(inout) :: S_kj(nkr,n_jk)
      subroutine matvec_bwd_leg_trans_Pj                              &
     &         (iflag_matmul, nkr, n_jk, S_kj, P_j, V_k)
        integer(kind = kint), intent(in) :: n_jk, nkr
        real(kind = kreal), intent(in) :: P_j(n_jk)
        real(kind = kreal), intent(in) :: S_kj(nkr, n_jk)
        real(kind = kreal), intent(inout) :: V_k(nkr)
      subroutine matmul8_bwd_leg_trans_Pjt                            &
     &         (iflag_matmul, nkr, n_jk, S_kj, P_jt, V_kt)
        integer(kind = kint), intent(in) :: n_jk, nkr
        real(kind = kreal), intent(in) :: P_jt(n_jk,8)
        real(kind = kreal), intent(in) :: S_kj(nkr, n_jk)
        real(kind = kreal), intent(inout) :: V_kt(nkr,8)
      subroutine matmul4_bwd_leg_trans_Pjt                            &
     &         (iflag_matmul, nkr, n_jk, S_kj, P_jt, V_kt)
        integer(kind = kint), intent(in) :: n_jk, nkr
        real(kind = kreal), intent(in) :: P_jt(n_jk,4)
        real(kind = kreal), intent(in) :: S_kj(nkr, n_jk)
        real(kind = kreal), intent(inout) :: V_kt(nkr,4)
      subroutine matmul2_bwd_leg_trans_Pjt                            &
     &         (iflag_matmul, nkr, n_jk, S_kj, P_jt, V_kt)
        integer(kind = kint), intent(in) :: n_jk, nkr
        real(kind = kreal), intent(in) :: P_jt(n_jk,2)
        real(kind = kreal), intent(in) :: S_kj(nkr, n_jk)
        real(kind = kreal), intent(inout) :: V_kt(nkr,2)
Function/Subroutine Documentation
matmul2_bwd_leg_trans_pjt()
subroutine small_matmul_leg_trans_krin::matmul2_bwd_leg_trans_pjt (integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) nkr, integer(kind = kint), intent(in) n_jk, real(kind = kreal), dimension(nkr, n_jk), intent(in) S_kj, real(kind = kreal), dimension(n_jk,2), intent(in) P_jt, real(kind = kreal), dimension(nkr,2), intent(inout) V_kt)
Definition at line 326 of file small_matmul_leg_trans_krin.F90.
References matmul_for_legendre_trans::iflag_dgemm, matmul_for_legendre_trans::iflag_intrinsic, m_constants::one, and m_constants::zero.
matmul2_fwd_leg_trans_ptj()
subroutine small_matmul_leg_trans_krin::matmul2_fwd_leg_trans_ptj (integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) nkr, integer(kind = kint), intent(in) n_jk, real(kind = kreal), dimension(nkr,2), intent(in) V_kt, real(kind = kreal), dimension(2,n_jk), intent(in) P_tj, real(kind = kreal), dimension(nkr,n_jk), intent(inout) S_kj)
Definition at line 177 of file small_matmul_leg_trans_krin.F90.
References matmul_for_legendre_trans::iflag_dgemm, matmul_for_legendre_trans::iflag_intrinsic, and m_constants::one.
Referenced by leg_fwd_trans_on_the_fly::leg_fwd_trans_2latitude(), and legendre_fwd_trans_testloop::leg_fwd_trans_2latitude().
matmul4_bwd_leg_trans_pjt()
subroutine small_matmul_leg_trans_krin::matmul4_bwd_leg_trans_pjt (integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) nkr, integer(kind = kint), intent(in) n_jk, real(kind = kreal), dimension(nkr, n_jk), intent(in) S_kj, real(kind = kreal), dimension(n_jk,4), intent(in) P_jt, real(kind = kreal), dimension(nkr,4), intent(inout) V_kt)
Definition at line 286 of file small_matmul_leg_trans_krin.F90.
References matmul_for_legendre_trans::iflag_dgemm, matmul_for_legendre_trans::iflag_intrinsic, m_constants::one, and m_constants::zero.
matmul4_fwd_leg_trans_ptj()
subroutine small_matmul_leg_trans_krin::matmul4_fwd_leg_trans_ptj (integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) nkr, integer(kind = kint), intent(in) n_jk, real(kind = kreal), dimension(nkr,4), intent(in) V_kt, real(kind = kreal), dimension(4,n_jk), intent(in) P_tj, real(kind = kreal), dimension(nkr,n_jk), intent(inout) S_kj)
Definition at line 139 of file small_matmul_leg_trans_krin.F90.
References matmul_for_legendre_trans::iflag_dgemm, matmul_for_legendre_trans::iflag_intrinsic, and m_constants::one.
Referenced by leg_fwd_trans_on_the_fly::leg_fwd_trans_4latitude(), and legendre_fwd_trans_testloop::leg_fwd_trans_4latitude().
matmul8_bwd_leg_trans_pjt()
subroutine small_matmul_leg_trans_krin::matmul8_bwd_leg_trans_pjt (integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) nkr, integer(kind = kint), intent(in) n_jk, real(kind = kreal), dimension(nkr, n_jk), intent(in) S_kj, real(kind = kreal), dimension(n_jk,8), intent(in) P_jt, real(kind = kreal), dimension(nkr,8), intent(inout) V_kt)
Definition at line 246 of file small_matmul_leg_trans_krin.F90.
References matmul_for_legendre_trans::iflag_dgemm, matmul_for_legendre_trans::iflag_intrinsic, m_constants::one, and m_constants::zero.
matmul8_fwd_leg_trans_ptj()
subroutine small_matmul_leg_trans_krin::matmul8_fwd_leg_trans_ptj (integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) nkr, integer(kind = kint), intent(in) n_jk, real(kind = kreal), dimension(nkr,8), intent(in) V_kt, real(kind = kreal), dimension(8,n_jk), intent(in) P_tj, real(kind = kreal), dimension(nkr,n_jk), intent(inout) S_kj)
Definition at line 99 of file small_matmul_leg_trans_krin.F90.
References matmul_for_legendre_trans::iflag_dgemm, matmul_for_legendre_trans::iflag_intrinsic, and m_constants::one.
Referenced by leg_fwd_trans_on_the_fly::leg_fwd_trans_8latitude(), and legendre_fwd_trans_testloop::leg_fwd_trans_8latitude().
matvec_bwd_leg_trans_pj()
subroutine small_matmul_leg_trans_krin::matvec_bwd_leg_trans_pj (integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) nkr, integer(kind = kint), intent(in) n_jk, real(kind = kreal), dimension(nkr,n_jk), intent(in) S_kj, real(kind = kreal), dimension(n_jk), intent(in) P_j, real(kind = kreal), dimension(nkr), intent(inout) V_k)
Definition at line 215 of file small_matmul_leg_trans_krin.F90.
References matmul_for_legendre_trans::iflag_intrinsic.
Referenced by leg_bwd_trans_on_the_fly::leg_bwd_trans_1latitude(), legendre_bwd_trans_testloop::leg_bwd_trans_1latitude(), leg_bwd_trans_on_the_fly::leg_bwd_trans_at_equator(), and legendre_bwd_trans_testloop::leg_bwd_trans_at_equator().
matvec_fwd_leg_trans_pj()
subroutine small_matmul_leg_trans_krin::matvec_fwd_leg_trans_pj (integer(kind = kint), intent(in) nkr, integer(kind = kint), intent(in) n_jk, real(kind = kreal), dimension(nkr), intent(in) V_k, real(kind = kreal), dimension(n_jk), intent(in) P_j, real(kind = kreal), dimension(nkr,n_jk), intent(inout) S_kj)
Definition at line 77 of file small_matmul_leg_trans_krin.F90.
Referenced by leg_fwd_trans_on_the_fly::leg_fwd_trans_1latitude(), legendre_fwd_trans_testloop::leg_fwd_trans_1latitude(), leg_fwd_trans_on_the_fly::leg_fwd_trans_at_equator(), and legendre_fwd_trans_testloop::leg_fwd_trans_at_equator().