CALYPSO: check_sph_radial_mat Module Reference
check_sph_radial_mat Module Reference
Output band matrix data to check.
Functions/Subroutines
subroutine check_radial_3band_mat_w_ctr (id_rank, nri, rr, mat00)
subroutine check_radial_3band_mat (id_rank, nri, jmax, j_sph, rr, mat)
subroutine check_radial_5band_mat (id_rank, nri, jmax, j_sph, rr, mat)
subroutine check_radial_7band_mat (id_rank, nri, jmax, j_sph, rr, mat)
subroutine check_single_radial_3band_mat (id_rank, nri, rr, mat)
subroutine check_single_radial_5band_mat (id_rank, nri, rr, mat)
subroutine check_single_radial_7band_mat (id_rank, nri, rr, mat)
Detailed Description
Output band matrix data to check.
      subroutine check_radial_3band_mat_w_ctr(id_rank, nri, rr, mat00)
      subroutine check_radial_3band_mat(id_rank, nri, jmax, j_sph,    &
    &           rr, mat)
      subroutine check_radial_5band_mat(id_rank, nri, jmax, j_sph,    &
    &           rr, mat)
      subroutine check_radial_7band_mat(id_rank, nri, jmax, j_sph,    &
    &           rr, mat)
      subroutine check_single_radial_3band_mat(id_rank, nri,  rr, mat)
      subroutine check_single_radial_5band_mat(id_rank, nri,  rr, mat)
      subroutine check_single_radial_7band_mat(id_rank, nri,  rr, mat)
Parameters
id_rank radius to three next points of ICB
nri radius to three next points of ICB
jmax radius to three next points of ICB
j_sph radius to three next points of ICB
rr radius to three next points of ICB
mat radius to three next points of ICB
Function/Subroutine Documentation
check_radial_3band_mat()
subroutine check_sph_radial_mat::check_radial_3band_mat (integer, intent(in) id_rank, integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, integer(kind = kint), dimension(jmax,3), intent(in) j_sph, real(kind = kreal), dimension(nri), intent(in) rr, real(kind = kreal), dimension(3,nri,jmax), intent(in) mat)
Definition at line 69 of file check_sph_radial_mat.f90.
References check_single_radial_3band_mat().
Referenced by t_sph_matrices::check_radial_band_mat().
check_radial_3band_mat_w_ctr()
subroutine check_sph_radial_mat::check_radial_3band_mat_w_ctr (integer, intent(in) id_rank, integer(kind = kint), intent(in) nri, real(kind = kreal), dimension(nri), intent(in) rr, real(kind = kreal), dimension(3,0:nri), intent(in) mat00)
Definition at line 44 of file check_sph_radial_mat.f90.
References m_constants::izero, and m_constants::zero.
Referenced by t_sph_center_matrix::check_center_band_matrix().
check_radial_5band_mat()
subroutine check_sph_radial_mat::check_radial_5band_mat (integer, intent(in) id_rank, integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, integer(kind = kint), dimension(jmax,3), intent(in) j_sph, real(kind = kreal), dimension(nri), intent(in) rr, real(kind = kreal), dimension(5,nri,jmax), intent(in) mat)
Definition at line 92 of file check_sph_radial_mat.f90.
References check_single_radial_5band_mat().
Referenced by t_sph_matrices::check_radial_band_mat().
check_radial_7band_mat()
subroutine check_sph_radial_mat::check_radial_7band_mat (integer, intent(in) id_rank, integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, integer(kind = kint), dimension(jmax,3), intent(in) j_sph, real(kind = kreal), dimension(nri), intent(in) rr, real(kind = kreal), dimension(7,nri,jmax), intent(in) mat)
Definition at line 115 of file check_sph_radial_mat.f90.
References check_single_radial_7band_mat().
Referenced by t_sph_matrices::check_radial_band_mat(), and t_radial_matrices_sph_mhd::check_velocity_matrices_sph().
check_single_radial_3band_mat()
subroutine check_sph_radial_mat::check_single_radial_3band_mat (integer, intent(in) id_rank, integer(kind = kint), intent(in) nri, real(kind = kreal), dimension(nri), intent(in) rr, real(kind = kreal), dimension(3,nri), intent(in) mat)
Definition at line 139 of file check_sph_radial_mat.f90.
References m_constants::ione.
Referenced by check_radial_3band_mat(), t_sph_matrix::check_radial_band_matrix(), and solve_sph_fluid_crank::solve_pressure_by_div_v().
check_single_radial_5band_mat()
subroutine check_sph_radial_mat::check_single_radial_5band_mat (integer, intent(in) id_rank, integer(kind = kint), intent(in) nri, real(kind = kreal), dimension(nri), intent(in) rr, real(kind = kreal), dimension(5,nri), intent(in) mat)
Definition at line 164 of file check_sph_radial_mat.f90.
References m_constants::ione, and m_constants::itwo.
Referenced by check_radial_5band_mat(), t_sph_matrix::check_radial_band_matrix(), and solve_sph_fluid_crank::solve_pressure_by_div_v().
check_single_radial_7band_mat()
subroutine check_sph_radial_mat::check_single_radial_7band_mat (integer, intent(in) id_rank, integer(kind = kint), intent(in) nri, real(kind = kreal), dimension(nri), intent(in) rr, real(kind = kreal), dimension(7,nri), intent(in) mat)
Definition at line 193 of file check_sph_radial_mat.f90.
References m_constants::ione, m_constants::ithree, and m_constants::itwo.
Referenced by check_radial_7band_mat(), and t_sph_matrix::check_radial_band_matrix().