CALYPSO: const_radial_forces_on_bc Module Reference
const_radial_forces_on_bc Module Reference
Evaluate radial component of forces at boundaries.
Functions/Subroutines
subroutine s_const_radial_forces_on_bc (sph_rj, g_sph_rj, fl_prop, sph_bc_U, ref_param_T, ref_param_C, ipol_base, ipol_dif, ipol_frc, ipol_div_frc, rj_fld)
subroutine cal_radial_force_on_sph (kr, is_fld, is_fr, nidx_rj, ar_1d_rj, g_sph_rj, n_point, ntot_phys_rj, d_rj)
Detailed Description
Evaluate radial component of forces at boundaries.
      subroutine s_const_radial_forces_on_bc(sph_rj, g_sph_rj,        &
     &          fl_prop, sph_bc_U, ref_param_T, ref_param_C,          &
     &          ipol_base, ipol_dif, ipol_frc, ipol_div_frc, rj_fld)
        type(fluid_property), intent(in) :: fl_prop
        type(sph_boundary_type), intent(in) :: sph_bc_U
        type(reference_scalar_param), intent(in) :: ref_param_T
        type(reference_scalar_param), intent(in) :: ref_param_C
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(phys_address), intent(in) :: ipol
        type(phys_data), intent(inout) :: rj_fld
      subroutine cal_radial_force_on_sph                              &
     &         (kr, is_fld, is_fr, nidx_rj, ar_1d_rj, g_sph_rj,       &
     &          n_point, ntot_phys_rj, d_rj)
Function/Subroutine Documentation
cal_radial_force_on_sph()
subroutine const_radial_forces_on_bc::cal_radial_force_on_sph (integer(kind = kint), intent(in) kr, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_fr, integer(kind = kint), dimension(2), intent(in) nidx_rj, real(kind = kreal), dimension(nidx_rj(1),3), intent(in) ar_1d_rj, real(kind = kreal), dimension(nidx_rj(2),13), intent(in) g_sph_rj, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 118 of file const_radial_forces_on_bc.f90.
References m_constants::half.
Referenced by s_const_radial_forces_on_bc().
s_const_radial_forces_on_bc()
subroutine const_radial_forces_on_bc::s_const_radial_forces_on_bc (type(sph_rj_grid), intent(in) sph_rj, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, type(fluid_property), intent(in) fl_prop, type(sph_boundary_type), intent(in) sph_bc_U, type(reference_scalar_param), intent(in) ref_param_T, type(reference_scalar_param), intent(in) ref_param_C, type(base_field_address), intent(in) ipol_base, type(diffusion_address), intent(in) ipol_dif, type(base_force_address), intent(in) ipol_frc, type(base_force_address), intent(in) ipol_div_frc, type(phys_data), intent(inout) rj_fld)
Definition at line 41 of file const_radial_forces_on_bc.f90.
References cal_radial_force_on_sph(), and self_buoyancy_on_sphere::r_buoyancy_on_sphere().
Referenced by lead_fields_4_sph_mhd::pressure_4_sph_mhd().