CALYPSO: set_norm_nod_4_surf_grp Module Reference
set_norm_nod_4_surf_grp Module Reference
Functions/Subroutines
subroutine allocate_work_norm_nod (numnod)
subroutine deallocate_work_norm_nod
subroutine cal_surf_grp_norm_node (numele, nnod_4_ele, nnod_4_surf, node_on_sf, ie, num_surf, num_surf_bc, surf_istack, surf_item, vnorm_sf_grp, a_area_sf_grp, ntot_node_sf_grp, inod_stack_sf_grp, inod_surf_grp, surf_norm_nod, coef_sf_nod)
Variables
integer(kind=kint), dimension(:), allocatable, private imark_nod
Function/Subroutine Documentation
allocate_work_norm_nod()
subroutine set_norm_nod_4_surf_grp::allocate_work_norm_nod (integer(kind = kint), intent(in) numnod)
Definition at line 31 of file set_norm_nod_4_surf_grp.f90.
References imark_nod.
Referenced by set_connects_4_surf_group::cal_surf_normal_at_nod().
cal_surf_grp_norm_node()
subroutine set_norm_nod_4_surf_grp::cal_surf_grp_norm_node (integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) nnod_4_ele, integer(kind = kint), intent(in) nnod_4_surf, integer(kind = kint), dimension(nnod_4_surf,nsurf_4_ele), intent(in) node_on_sf, integer(kind = kint), dimension(numele,nnod_4_ele), intent(in) ie, integer(kind = kint), intent(in) num_surf, integer(kind = kint), intent(in) num_surf_bc, integer(kind = kint), dimension(0:num_surf), intent(in) surf_istack, integer(kind = kint), dimension(2,num_surf_bc), intent(in) surf_item, real(kind = kreal), dimension(num_surf_bc,3), intent(in) vnorm_sf_grp, real(kind = kreal), dimension(num_surf_bc), intent(in) a_area_sf_grp, integer(kind = kint), intent(in) ntot_node_sf_grp, integer(kind = kint), dimension(0:num_surf), intent(in) inod_stack_sf_grp, integer(kind = kint), dimension(ntot_node_sf_grp), intent(in) inod_surf_grp, real(kind=kreal), dimension(ntot_node_sf_grp,3), intent(inout) surf_norm_nod, real(kind=kreal), dimension(ntot_node_sf_grp), intent(inout) coef_sf_nod)
Definition at line 51 of file set_norm_nod_4_surf_grp.f90.
References imark_nod, and m_geometry_constants::nsurf_4_ele.
Referenced by set_connects_4_surf_group::cal_surf_normal_at_nod().
deallocate_work_norm_nod()
subroutine set_norm_nod_4_surf_grp::deallocate_work_norm_nod
Definition at line 42 of file set_norm_nod_4_surf_grp.f90.
References imark_nod.
Referenced by set_connects_4_surf_group::cal_surf_normal_at_nod().
Variable Documentation
imark_nod
integer(kind = kint), dimension(:), allocatable, private set_norm_nod_4_surf_grp::imark_nod private
Definition at line 23 of file set_norm_nod_4_surf_grp.f90.
Referenced by allocate_work_norm_nod(), cal_surf_grp_norm_node(), and deallocate_work_norm_nod().