CALYPSO: t_time_data Module Reference
t_time_data Module Reference
Data Types
type finish_data
Structure for finish time data.
type time_data
Structure for time data.
Functions/Subroutines
subroutine reset_time_data (time_d)
subroutine evolve_time_data (time_d)
subroutine copy_time_steps_from_restart (time_IO, init_d)
subroutine copy_time_step_size_data (time_org, time_new)
subroutine copy_time_step_data (time_org, time_new)
subroutine copy_time_data (time_org, time_new)
subroutine copy_delta_t (time_org, time_new)
subroutine add_one_step (time_d)
Function/Subroutine Documentation
add_one_step()
subroutine t_time_data::add_one_step (type(time_data), intent(inout) time_d)
Definition at line 159 of file t_time_data.f90.
copy_delta_t()
subroutine t_time_data::copy_delta_t (type(time_data), intent(in) time_org, type(time_data), intent(inout) time_new)
Definition at line 146 of file t_time_data.f90.
Referenced by load_mesh_and_field_4_viz::set_control_params_4_viz().
copy_time_data()
subroutine t_time_data::copy_time_data (type(time_data), intent(in) time_org, type(time_data), intent(inout) time_new)
Definition at line 134 of file t_time_data.f90.
copy_time_step_data()
subroutine t_time_data::copy_time_step_data (type(time_data), intent(in) time_org, type(time_data), intent(inout) time_new)
Definition at line 121 of file t_time_data.f90.
Referenced by copy_time_steps_from_restart(), sph_mhd_rst_io_control::read_alloc_sph_restart_data(), sph_mhd_rst_io_control::read_alloc_sph_rst_4_snap(), sph_mhd_rst_io_control::read_alloc_sph_spectr(), and set_initial_sph_dynamo::sph_initial_data_control().
copy_time_step_size_data()
subroutine t_time_data::copy_time_step_size_data (type(time_data), intent(in) time_org, type(time_data), intent(inout) time_new)
Definition at line 107 of file t_time_data.f90.
Referenced by new_sph_restart::const_assembled_sph_data(), output_4_psf::output_isosurface(), output_4_psf::output_section_data(), sph_mhd_rst_io_control::output_spectr_4_snap(), sph_mhd_rst_io_control::output_sph_restart_control(), output_parallel_ucd_file::output_udt_one_snapshot(), and load_mesh_and_field_4_viz::set_field_data_4_viz().
copy_time_steps_from_restart()
subroutine t_time_data::copy_time_steps_from_restart (type(time_data), intent(in) time_IO, type(time_data), intent(inout) init_d)
Definition at line 92 of file t_time_data.f90.
References copy_time_step_data(), and m_constants::zero.
Referenced by new_sph_restart::load_org_sph_data().
evolve_time_data()
subroutine t_time_data::evolve_time_data (type(time_data), intent(inout) time_d)
Definition at line 79 of file t_time_data.f90.
reset_time_data()
subroutine t_time_data::reset_time_data (type(time_data), intent(inout) time_d)
Definition at line 66 of file t_time_data.f90.
References m_constants::izero, and m_constants::zero.