CALYPSO: m_work_time Module Reference
m_work_time Module Reference
routines to count elapsed time
Functions/Subroutines
subroutine allocate_elapsed_times
subroutine append_elapsed_times (num_append, iend_org, iend_new)
subroutine deallocate_elapsed_times
subroutine start_elapsed_time (iflag_elps)
subroutine end_elapsed_time (iflag_elps)
subroutine reset_elapsed_times (istart, iend)
subroutine init_elapse_time_by_total
subroutine output_elapsed_times
Variables
integer(kind=kint) iflag_time_4_each_pe = 0
integer(kind=kint), parameter id_timer_file = 13
character(len=kchara), parameter time_file_prefix = 'time_total'
type(elapsed_time_data), save elps1
logical, save iflag_tot_time = .FALSE.
integer(kind=kint), save, private ist_total_elapsed = 0
integer(kind=kint), save ied_total_elapsed = 0
Detailed Description
routines to count elapsed time
      subroutine allocate_elapsed_times
      subroutine append_elapsed_times(num_append, iend_org, iend_new)
      subroutine deallocate_elapsed_times
      subroutine start_elapsed_time(iflag_elps)
      subroutine end_elapsed_time(iflag_elps)
      subroutine reset_elapsed_times(istart, iend)
      subroutine init_elapse_time_by_TOTAL
      subroutine output_elapsed_times
@params timer ID
Function/Subroutine Documentation
allocate_elapsed_times()
subroutine m_work_time::allocate_elapsed_times
Definition at line 52 of file m_work_time.f90.
References t_work_time::alloc_elapsed_timer(), and elps1.
Referenced by init_elapse_time_by_total().
append_elapsed_times()
subroutine m_work_time::append_elapsed_times (integer(kind = kint), intent(in) num_append, integer(kind = kint), intent(inout) iend_org, integer(kind = kint), intent(inout) iend_new)
Definition at line 61 of file m_work_time.f90.
References t_work_time::append_elapsed_timer(), and elps1.
Referenced by const_element_comm_table::elapsed_label_4_ele_comm_tbl(), m_elapsed_labels_4_mhd::elapsed_label_4_fem_mhd(), m_elapsed_labels_sph_trns::elapsed_label_4_legendre_trans(), m_elapsed_labels_4_mhd::elapsed_label_4_mhd(), m_elapsed_labels_4_mhd::elapsed_label_4_sgs_model(), m_elapsed_labels_4_mhd::elapsed_label_4_sph_mhd(), m_elapsed_labels_sph_trns::elpsed_label_4_fft_detail(), m_elapsed_labels_4_viz::elpsed_label_4_iso(), m_elapsed_labels_4_viz::elpsed_label_4_lic(), m_elapsed_labels_4_viz::elpsed_label_4_psf(), m_elapsed_labels_4_viz::elpsed_label_4_pvr(), m_elapsed_labels_sph_trns::elpsed_label_4_sph_detail(), m_elapsed_labels_sph_trns::elpsed_label_4_sph_trns(), m_elapsed_labels_4_viz::elpsed_label_4_viz_outline(), m_elapsed_labels_send_recv::elpsed_label_calypso_send_recv(), m_elapsed_labels_send_recv::elpsed_label_field_send_recv(), and m_elapsed_labels_gen_sph::elpsed_label_gen_sph_grid().
deallocate_elapsed_times()
subroutine m_work_time::deallocate_elapsed_times
Definition at line 74 of file m_work_time.f90.
References t_work_time::dealloc_elapsed_timer(), and elps1.
end_elapsed_time()
subroutine m_work_time::end_elapsed_time (integer(kind = kint), intent(in) iflag_elps)
Definition at line 95 of file m_work_time.f90.
References elps1, and t_work_time::end_elapsed_timer().
Referenced by analyzer_check_sph_grids::analyze_check_sph_grids(), analyzer_gen_sph_grids::analyze_gen_sph_grids(), analyzer_psf::analyze_psf(), analyzer_vtk_convert::analyze_vtk_convert(), cal_sp_rlm_sym_mat_tsmp::cal_sp_rlm_sym_mat_rin(), spherical_srs_n::calypso_sph_to_send_n(), t_check_and_make_sph_mesh::check_and_make_sph_mesh(), t_check_and_make_sph_mesh::check_and_make_sph_rj_mode(), const_element_comm_table::const_comm_table_by_connenct(), analyzer_sph_dynamobench::evolution_sph_dynamobench(), analyzer_sph_mhd_w_psf::evolution_sph_mhd_w_psf(), analyzer_sph_snap_w_psf::evolution_sph_snap_w_psf(), fem_analyzer_sph_mhd::fem_analyze_sph_mhd(), fem_analyzer_sph_mhd::fem_initialize_sph_mhd(), t_viz_sections::init_visualize_surface(), t_sph_mhd_zonal_mean_viz::init_zonal_mean_sections(), sph_analyzer_add_initial::initialize_add_sph_initial(), sph_analyzer_const_initial::initialize_const_sph_initial(), analyzer_sph_dynamobench::initialize_sph_dynamobench(), analyzer_sph_mhd_w_psf::initialize_sph_mhd_w_psf(), analyzer_sph_snap_w_psf::initialize_sph_snap_w_psf(), t_isosurface::isosurf_visualize(), leg_bwd_trans_on_the_fly::legendre_b_trans_on_the_fly(), leg_bwd_trans_sym_mat_jt::legendre_b_trans_sym_mat_jt(), leg_bwd_trans_sym_mat_tj::legendre_b_trans_sym_mat_tj(), legendre_bwd_trans_testloop::legendre_b_trans_vector_test(), leg_fwd_trans_on_the_fly::legendre_f_trans_on_the_fly(), leg_fwd_trans_sym_mat_jt::legendre_f_trans_sym_mat_jt(), leg_fwd_trans_sym_mat_tj::legendre_f_trans_sym_mat_tj(), legendre_fwd_trans_testloop::legendre_f_trans_vector_test(), mpi_gen_sph_grids_modes::mpi_gen_sph_grids(), mpi_gen_sph_grids_modes::mpi_gen_sph_rj_mode(), cal_nonlinear::nonlinear(), cal_nonlinear::nonlinear_by_pseudo_sph(), t_parai_gen_sph_grids_modes::para_gen_sph_rlm_rj_modes(), t_parai_gen_sph_grids_modes::para_gen_sph_rtm_rtp_grids(), t_sph_transforms::pole_b_transform(), t_cross_section::sectioning_initialize(), t_cross_section::sectioning_visualize(), sel_spherical_srs::sel_calypso_from_recv_n(), sel_spherical_srs::sel_calypso_sph_comm_n(), sel_spherical_srs::sel_calypso_to_send_n(), sel_spherical_srs::sel_calypso_to_send_scalar(), sel_spherical_srs::sel_calypso_to_send_tensor(), sel_spherical_srs::sel_calypso_to_send_vector(), sel_spherical_srs::sel_sph_scalar_from_recv(), sel_spherical_srs::sel_sph_tensor_from_recv(), sel_spherical_srs::sel_sph_vector_from_recv(), solver_sr_type::solver_send_recv_1x3_type(), solver_sr_type::solver_send_recv_3_type(), solver_sr_type::solver_send_recv_3x3_type(), solver_sr_type::solver_send_recv_6_type(), solver_sr_type::solver_send_recv_int8_type(), solver_sr_type::solver_send_recv_int_type(), solver_sr_type::solver_send_recv_n_type(), solver_sr_type::solver_send_recv_num_type(), solver_sr_type::solver_send_recv_nx3_type(), solver_sr_type::solver_send_recv_type(), sph_analyzer_add_initial::sph_add_initial_field(), sph_analyzer_d_bench::sph_analyze_dbench(), sph_analyzer_mhd::sph_analyze_mhd(), sph_analyzer_snap_w_psf::sph_analyze_snap_psf(), sph_trans_w_coriols::sph_b_trans_licv(), sph_trans_w_coriols::sph_b_trans_w_coriolis(), t_sph_transforms::sph_b_trans_w_poles(), sph_transforms_4_mhd::sph_back_trans_4_mhd(), t_sph_transforms::sph_backward_transforms(), sph_analyzer_const_initial::sph_const_initial_field(), sph_trans_w_coriols::sph_f_trans_licv(), sph_trans_w_coriols::sph_f_trans_w_coriolis(), sph_transforms_4_mhd::sph_forward_trans_4_mhd(), t_sph_transforms::sph_forward_transforms(), sph_analyzer_mhd::sph_initialize_mhd(), t_sph_mhd_zonal_mean_viz::sph_mhd_zonal_mean_section(), t_sph_mhd_zonal_mean_viz::sph_mhd_zonal_rms_section(), t_viz_vtk_convert::visualize_convert_vtk(), and t_viz_sections::visualize_surface().
init_elapse_time_by_total()
subroutine m_work_time::init_elapse_time_by_total
Definition at line 120 of file m_work_time.f90.
References allocate_elapsed_times(), elps1, ied_total_elapsed, iflag_tot_time, and ist_total_elapsed.
Referenced by analyzer_psf::init_analyzer_psf(), analyzer_vtk_convert::init_analyzer_vtk_convert(), analyzer_check_sph_grids::init_check_sph_grids(), analyzer_gen_sph_grids::init_gen_sph_grids(), analyzer_test_sph::init_test_sph(), sph_analyzer_add_initial::initialize_add_sph_initial(), sph_analyzer_const_initial::initialize_const_sph_initial(), analyzer_sph_dynamobench::initialize_sph_dynamobench(), analyzer_sph_mhd_w_psf::initialize_sph_mhd_w_psf(), and analyzer_sph_snap_w_psf::initialize_sph_snap_w_psf().
output_elapsed_times()
subroutine m_work_time::output_elapsed_times
Definition at line 136 of file m_work_time.f90.
References elps1, iflag_time_4_each_pe, t_work_time::output_elapsed_log(), and time_file_prefix.
Referenced by analyzer_gen_sph_grids::analyze_gen_sph_grids(), analyzer_psf::analyze_psf(), analyzer_vtk_convert::analyze_vtk_convert(), analyzer_sph_dynamobench::evolution_sph_dynamobench(), analyzer_sph_mhd_w_psf::evolution_sph_mhd_w_psf(), and analyzer_sph_snap_w_psf::evolution_sph_snap_w_psf().
reset_elapsed_times()
subroutine m_work_time::reset_elapsed_times (integer(kind = kint), intent(in) istart, integer(kind = kint), intent(in) iend)
Definition at line 108 of file m_work_time.f90.
References elps1, and t_work_time::reset_elapsed_timer().
Referenced by m_elapsed_labels_sph_trns::reset_elapse_after_init_fft(), m_elapsed_labels_4_viz::reset_elapse_after_init_iso(), m_elapsed_labels_sph_trns::reset_elapse_after_init_leg(), m_elapsed_labels_4_viz::reset_elapse_after_init_lic(), m_elapsed_labels_4_viz::reset_elapse_after_init_psf(), m_elapsed_labels_4_viz::reset_elapse_after_init_pvr(), m_elapsed_labels_sph_trns::reset_elapse_after_init_sdt(), m_elapsed_labels_4_mhd::reset_elapse_after_init_sgs(), m_elapsed_labels_sph_trns::reset_elapse_after_init_sph(), m_elapsed_labels_4_mhd::reset_elapse_after_init_sph_mhd(), m_elapsed_labels_send_recv::reset_elapse_after_init_sr(), and m_elapsed_labels_4_viz::reset_elapse_after_init_viz_top().
start_elapsed_time()
subroutine m_work_time::start_elapsed_time (integer(kind = kint), intent(in) iflag_elps)
Definition at line 84 of file m_work_time.f90.
References elps1, and t_work_time::start_elapsed_timer().
Referenced by analyzer_check_sph_grids::analyze_check_sph_grids(), analyzer_gen_sph_grids::analyze_gen_sph_grids(), cal_sp_rlm_sym_mat_tsmp::cal_sp_rlm_sym_mat_rin(), spherical_srs_n::calypso_sph_to_send_n(), t_check_and_make_sph_mesh::check_and_make_sph_mesh(), t_check_and_make_sph_mesh::check_and_make_sph_rj_mode(), const_element_comm_table::const_comm_table_by_connenct(), analyzer_sph_dynamobench::evolution_sph_dynamobench(), analyzer_sph_mhd_w_psf::evolution_sph_mhd_w_psf(), analyzer_sph_snap_w_psf::evolution_sph_snap_w_psf(), fem_analyzer_sph_mhd::fem_analyze_sph_mhd(), fem_analyzer_sph_mhd::fem_initialize_sph_mhd(), analyzer_psf::init_analyzer_psf(), analyzer_vtk_convert::init_analyzer_vtk_convert(), analyzer_check_sph_grids::init_check_sph_grids(), analyzer_gen_sph_grids::init_gen_sph_grids(), t_viz_sections::init_visualize_surface(), t_sph_mhd_zonal_mean_viz::init_zonal_mean_sections(), sph_analyzer_add_initial::initialize_add_sph_initial(), sph_analyzer_const_initial::initialize_const_sph_initial(), analyzer_sph_dynamobench::initialize_sph_dynamobench(), analyzer_sph_mhd_w_psf::initialize_sph_mhd_w_psf(), analyzer_sph_snap_w_psf::initialize_sph_snap_w_psf(), t_isosurface::isosurf_visualize(), leg_bwd_trans_on_the_fly::legendre_b_trans_on_the_fly(), leg_bwd_trans_sym_mat_jt::legendre_b_trans_sym_mat_jt(), leg_bwd_trans_sym_mat_tj::legendre_b_trans_sym_mat_tj(), legendre_bwd_trans_testloop::legendre_b_trans_vector_test(), leg_fwd_trans_on_the_fly::legendre_f_trans_on_the_fly(), leg_fwd_trans_sym_mat_jt::legendre_f_trans_sym_mat_jt(), leg_fwd_trans_sym_mat_tj::legendre_f_trans_sym_mat_tj(), legendre_fwd_trans_testloop::legendre_f_trans_vector_test(), mpi_gen_sph_grids_modes::mpi_gen_sph_grids(), mpi_gen_sph_grids_modes::mpi_gen_sph_rj_mode(), cal_nonlinear::nonlinear(), cal_nonlinear::nonlinear_by_pseudo_sph(), t_parai_gen_sph_grids_modes::para_gen_sph_rlm_rj_modes(), t_parai_gen_sph_grids_modes::para_gen_sph_rtm_rtp_grids(), t_sph_transforms::pole_b_transform(), t_cross_section::sectioning_initialize(), t_cross_section::sectioning_visualize(), sel_spherical_srs::sel_calypso_from_recv_n(), sel_spherical_srs::sel_calypso_sph_comm_n(), sel_spherical_srs::sel_calypso_to_send_n(), sel_spherical_srs::sel_calypso_to_send_scalar(), sel_spherical_srs::sel_calypso_to_send_tensor(), sel_spherical_srs::sel_calypso_to_send_vector(), sel_spherical_srs::sel_sph_scalar_from_recv(), sel_spherical_srs::sel_sph_tensor_from_recv(), sel_spherical_srs::sel_sph_vector_from_recv(), solver_sr_type::solver_send_recv_1x3_type(), solver_sr_type::solver_send_recv_3_type(), solver_sr_type::solver_send_recv_3x3_type(), solver_sr_type::solver_send_recv_6_type(), solver_sr_type::solver_send_recv_int8_type(), solver_sr_type::solver_send_recv_int_type(), solver_sr_type::solver_send_recv_n_type(), solver_sr_type::solver_send_recv_num_type(), solver_sr_type::solver_send_recv_nx3_type(), solver_sr_type::solver_send_recv_type(), sph_analyzer_d_bench::sph_analyze_dbench(), sph_analyzer_mhd::sph_analyze_mhd(), sph_analyzer_snap_w_psf::sph_analyze_snap_psf(), sph_trans_w_coriols::sph_b_trans_licv(), sph_trans_w_coriols::sph_b_trans_w_coriolis(), t_sph_transforms::sph_b_trans_w_poles(), sph_transforms_4_mhd::sph_back_trans_4_mhd(), t_sph_transforms::sph_backward_transforms(), sph_trans_w_coriols::sph_f_trans_licv(), sph_trans_w_coriols::sph_f_trans_w_coriolis(), sph_transforms_4_mhd::sph_forward_trans_4_mhd(), t_sph_transforms::sph_forward_transforms(), sph_analyzer_mhd::sph_initialize_mhd(), t_sph_mhd_zonal_mean_viz::sph_mhd_zonal_mean_section(), t_sph_mhd_zonal_mean_viz::sph_mhd_zonal_rms_section(), t_viz_vtk_convert::visualize_convert_vtk(), and t_viz_sections::visualize_surface().
Variable Documentation
elps1
type(elapsed_time_data), save m_work_time::elps1
Definition at line 40 of file m_work_time.f90.
Referenced by allocate_elapsed_times(), append_elapsed_times(), deallocate_elapsed_times(), const_element_comm_table::elapsed_label_4_ele_comm_tbl(), m_elapsed_labels_4_mhd::elapsed_label_4_fem_mhd(), m_elapsed_labels_sph_trns::elapsed_label_4_legendre_trans(), m_elapsed_labels_4_mhd::elapsed_label_4_mhd(), m_elapsed_labels_4_mhd::elapsed_label_4_sgs_model(), m_elapsed_labels_4_mhd::elapsed_label_4_sph_mhd(), m_elapsed_labels_sph_trns::elpsed_label_4_fft_detail(), m_elapsed_labels_4_viz::elpsed_label_4_iso(), m_elapsed_labels_4_viz::elpsed_label_4_lic(), m_elapsed_labels_4_viz::elpsed_label_4_psf(), m_elapsed_labels_4_viz::elpsed_label_4_pvr(), m_elapsed_labels_sph_trns::elpsed_label_4_sph_detail(), m_elapsed_labels_sph_trns::elpsed_label_4_sph_trns(), m_elapsed_labels_4_viz::elpsed_label_4_viz_outline(), m_elapsed_labels_send_recv::elpsed_label_calypso_send_recv(), m_elapsed_labels_send_recv::elpsed_label_field_send_recv(), m_elapsed_labels_gen_sph::elpsed_label_gen_sph_grid(), end_elapsed_time(), init_elapse_time_by_total(), leg_b_trans_sym_matmul_big::leg_bwd_trans_sym_matmul_big(), leg_f_trans_sym_matmul_big::leg_fwd_trans_sym_matmul_big(), leg_bwd_trans_on_the_fly::legendre_b_trans_on_the_fly(), legendre_bwd_trans_testloop::legendre_b_trans_vector_test(), leg_fwd_trans_on_the_fly::legendre_f_trans_on_the_fly(), legendre_fwd_trans_testloop::legendre_f_trans_vector_test(), output_elapsed_times(), reset_elapsed_times(), and start_elapsed_time().
id_timer_file
integer(kind = kint), parameter m_work_time::id_timer_file = 13
Definition at line 36 of file m_work_time.f90.
Referenced by init_sph_mhd_elapsed_label::write_resolution_info().
ied_total_elapsed
integer(kind = kint), save m_work_time::ied_total_elapsed = 0
Definition at line 44 of file m_work_time.f90.
Referenced by analyzer_gen_sph_grids::analyze_gen_sph_grids(), analyzer_psf::analyze_psf(), analyzer_vtk_convert::analyze_vtk_convert(), analyzer_sph_dynamobench::evolution_sph_dynamobench(), analyzer_sph_mhd_w_psf::evolution_sph_mhd_w_psf(), analyzer_sph_snap_w_psf::evolution_sph_snap_w_psf(), analyzer_psf::init_analyzer_psf(), analyzer_vtk_convert::init_analyzer_vtk_convert(), analyzer_check_sph_grids::init_check_sph_grids(), init_elapse_time_by_total(), analyzer_gen_sph_grids::init_gen_sph_grids(), sph_analyzer_add_initial::initialize_add_sph_initial(), sph_analyzer_const_initial::initialize_const_sph_initial(), analyzer_sph_dynamobench::initialize_sph_dynamobench(), analyzer_sph_mhd_w_psf::initialize_sph_mhd_w_psf(), analyzer_sph_snap_w_psf::initialize_sph_snap_w_psf(), sph_analyzer_add_initial::sph_add_initial_field(), and sph_analyzer_const_initial::sph_const_initial_field().
iflag_time_4_each_pe
integer(kind = kint) m_work_time::iflag_time_4_each_pe = 0
Definition at line 34 of file m_work_time.f90.
Referenced by output_elapsed_times().
iflag_tot_time
logical, save m_work_time::iflag_tot_time = .FALSE.
Definition at line 42 of file m_work_time.f90.
Referenced by analyzer_psf::analyze_psf(), analyzer_vtk_convert::analyze_vtk_convert(), analyzer_sph_dynamobench::evolution_sph_dynamobench(), analyzer_sph_mhd_w_psf::evolution_sph_mhd_w_psf(), analyzer_sph_snap_w_psf::evolution_sph_snap_w_psf(), analyzer_psf::init_analyzer_psf(), analyzer_vtk_convert::init_analyzer_vtk_convert(), init_elapse_time_by_total(), sph_analyzer_add_initial::initialize_add_sph_initial(), sph_analyzer_const_initial::initialize_const_sph_initial(), analyzer_sph_dynamobench::initialize_sph_dynamobench(), analyzer_sph_mhd_w_psf::initialize_sph_mhd_w_psf(), analyzer_sph_snap_w_psf::initialize_sph_snap_w_psf(), sph_analyzer_add_initial::sph_add_initial_field(), and sph_analyzer_const_initial::sph_const_initial_field().
ist_total_elapsed
integer(kind = kint), save, private m_work_time::ist_total_elapsed = 0 private
Definition at line 43 of file m_work_time.f90.
Referenced by init_elapse_time_by_total().
time_file_prefix
character(len=kchara), parameter m_work_time::time_file_prefix = 'time_total'
Definition at line 37 of file m_work_time.f90.
Referenced by output_elapsed_times(), and init_sph_mhd_elapsed_label::write_resolution_info().