CALYPSO: /home/takumi kera/calypso/src/programs/TESTS/Gauss_point_test/compare_gauss_points.f90 File Reference
compare_gauss_points.f90 File Reference
Functions/Subroutines
program compare_gauss_points
Function/Subroutine Documentation
compare_gauss_points()
program compare_gauss_points
Definition at line 4 of file compare_gauss_points.f90.
References gauss_points_io::compare_gauss_point_data(), t_gauss_points::dealloc_gauss_colatitude(), and gauss_points_io::read_alloc_gauss_points().