CALYPSO: fill_scalar_field Module Reference
fill_scalar_field Module Reference
Functions/Subroutines
subroutine copy_degree0_comps_to_sol (nri, jmax, inod_rj_center, idx_rj_degree_zero, is_field, n_point, ntot_phys_rj, d_rj, sol_00)
subroutine copy_degree0_comps_from_sol (nri, jmax, inod_rj_center, idx_rj_degree_zero, sol_00, is_field, n_point, ntot_phys_rj, d_rj)
subroutine fill_scalar_at_external (kr_in, kr_out, inod_rj_center, idx_rj_degree_zero, nri, jmax, ipol_scalar, n_point, ntot_phys_rj, d_rj)
Function/Subroutine Documentation
copy_degree0_comps_from_sol()
subroutine fill_scalar_field::copy_degree0_comps_from_sol (integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, integer(kind = kint), intent(in) inod_rj_center, integer(kind = kint), intent(in) idx_rj_degree_zero, real(kind = kreal), dimension(0:nri), intent(in) sol_00, integer(kind = kint), intent(in) is_field, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 65 of file fill_scalar_field.f90.
Referenced by solve_sph_fluid_crank::solve_scalar_sph_crank().
copy_degree0_comps_to_sol()
subroutine fill_scalar_field::copy_degree0_comps_to_sol (integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, integer(kind = kint), intent(in) inod_rj_center, integer(kind = kint), intent(in) idx_rj_degree_zero, integer(kind = kint), intent(in) is_field, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj, real(kind = kreal), dimension(0:nri), intent(inout) sol_00)
Definition at line 32 of file fill_scalar_field.f90.
Referenced by solve_sph_fluid_crank::solve_scalar_sph_crank().
fill_scalar_at_external()
subroutine fill_scalar_field::fill_scalar_at_external (integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) kr_out, integer(kind = kint), intent(in) inod_rj_center, integer(kind = kint), intent(in) idx_rj_degree_zero, integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, integer(kind = kint), intent(in) ipol_scalar, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 97 of file fill_scalar_field.f90.
Referenced by cal_sol_sph_fluid_crank::cal_sol_scalar_sph_crank().