CALYPSO: set_sph_surf_group Module Reference
set_sph_surf_group Module Reference
Functions/Subroutines
subroutine count_sph_local_surf_group (radial_rj_grp, surf_grp)
subroutine count_sph_local_surf_grp_item (ip_r, ip_t, sph_params, radial_rj_grp, stbl, surf_grp)
subroutine set_sph_local_surf_grp_item (ip_r, ip_t, sph_params, radial_rj_grp, stbl, surf_grp)
subroutine, private count_surf_grp_item_on_sphere (ip_t, sph_params, stbl, nitem_grp)
subroutine, private set_surf_grp_item_on_sphere (ip_r, ip_t, kr, sph_params, stbl, inum, isf, surf_grp)
Function/Subroutine Documentation
count_sph_local_surf_group()
subroutine set_sph_surf_group::count_sph_local_surf_group (type(group_data), intent(in) radial_rj_grp, type(surface_group_data), intent(inout) surf_grp)
Definition at line 36 of file set_sph_surf_group.f90.
Referenced by set_fem_mesh_4_sph::const_fem_groups_for_sph().
count_sph_local_surf_grp_item()
subroutine set_sph_surf_group::count_sph_local_surf_grp_item (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, type(sph_shell_parameters), intent(in) sph_params, type(group_data), intent(in) radial_rj_grp, type(comm_table_make_sph), intent(in) stbl, type(surface_group_data), intent(inout) surf_grp)
Definition at line 57 of file set_sph_surf_group.f90.
References count_surf_grp_item_on_sphere(), t_spheric_parameter::ctr_nod_grp_name, and t_spheric_parameter::icb_nod_grp_name.
Referenced by set_fem_mesh_4_sph::const_fem_groups_for_sph().
count_surf_grp_item_on_sphere()
subroutine, private set_sph_surf_group::count_surf_grp_item_on_sphere (integer(kind = kint), intent(in) ip_t, type(sph_shell_parameters), intent(in) sph_params, type(comm_table_make_sph), intent(in) stbl, integer(kind = kint), intent(inout) nitem_grp) private
Definition at line 162 of file set_sph_surf_group.f90.
Referenced by count_sph_local_surf_grp_item().
set_sph_local_surf_grp_item()
subroutine set_sph_surf_group::set_sph_local_surf_grp_item (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, type(sph_shell_parameters), intent(in) sph_params, type(group_data), intent(in) radial_rj_grp, type(comm_table_make_sph), intent(in) stbl, type(surface_group_data), intent(inout) surf_grp)
Definition at line 108 of file set_sph_surf_group.f90.
References t_spheric_parameter::ctr_nod_grp_name, t_spheric_parameter::icb_nod_grp_name, m_constants::ifive, m_constants::isix, and set_surf_grp_item_on_sphere().
Referenced by set_fem_mesh_4_sph::const_fem_groups_for_sph().
set_surf_grp_item_on_sphere()
subroutine, private set_sph_surf_group::set_surf_grp_item_on_sphere (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, integer(kind = kint), intent(in) kr, type(sph_shell_parameters), intent(in) sph_params, type(comm_table_make_sph), intent(in) stbl, integer(kind = kint), intent(inout) inum, integer(kind = kint), intent(inout) isf, type(surface_group_data), intent(inout) surf_grp) private
Definition at line 194 of file set_sph_surf_group.f90.
References cal_sph_ele_addresses::sph_n_pole_ele_id(), cal_sph_ele_addresses::sph_s_pole_ele_id(), and cal_sph_ele_addresses::sph_shell_ele_id().
Referenced by set_sph_local_surf_grp_item().