CALYPSO: compare_indices Module Reference
compare_indices Module Reference
Functions/Subroutines
integer(kind=kint) function check_4_on_3 (i1, i2, i3, j1, j2, j3, j4)
integer(kind=kint) function check_3_on_2 (i1, i2, j1, j2, j3)
integer(kind=kint) function check_2_on_1 (i1, j1, j2)
Function/Subroutine Documentation
check_2_on_1()
integer(kind = kint) function compare_indices::check_2_on_1 (integer(kind = kint), intent(in) i1, integer(kind = kint), intent(in) j1, integer(kind = kint), intent(in) j2)
Definition at line 80 of file compare_indices.f90.
Referenced by check_3_on_2().
check_3_on_2()
integer(kind = kint) function compare_indices::check_3_on_2 (integer(kind = kint), intent(in) i1, integer(kind = kint), intent(in) i2, integer(kind = kint), intent(in) j1, integer(kind = kint), intent(in) j2, integer(kind = kint), intent(in) j3)
Definition at line 61 of file compare_indices.f90.
References check_2_on_1().
Referenced by check_4_on_3().
check_4_on_3()
integer(kind = kint) function compare_indices::check_4_on_3 (integer(kind = kint), intent(in) i1, integer(kind = kint), intent(in) i2, integer(kind = kint), intent(in) i3, integer(kind = kint), intent(in) j1, integer(kind = kint), intent(in) j2, integer(kind = kint), intent(in) j3, integer(kind = kint), intent(in) j4)
Definition at line 39 of file compare_indices.f90.
References check_3_on_2().
Referenced by mark_surf_hash::mark_all_surfaces(), and mark_surf_hash::mark_independent_surface().