CALYPSO: set_control_4_force Module Reference
set_control_4_force Module Reference
Set parameters for forces from control data.
Functions/Subroutines
subroutine s_set_control_4_force (frc_ctl, g_ctl, cor_ctl, mcv_ctl, MHD_prop)
subroutine, private set_control_force_flags (frc_ctl, fl_prop)
subroutine, private set_control_4_gravity (g_ctl, fl_prop)
subroutine, private set_control_4_coriolis_force (cor_ctl, fl_prop)
subroutine, private set_control_4_induction (mcv_ctl, cd_prop)
Variables
character(len=kchara), parameter filtered_gravity_label = 'Filtered_buoyancy'
Filtered thermal buoyancy label.
character(len=kchara), parameter filtered_gravity_e1 = 'Filtered_gravity'
character(len=kchara), parameter filtered_comp_gravity_label = 'Filtered_compositional_buoyancy'
Filtered compositional buoyancy label.
character(len=kchara), parameter filtered_comp_gravity_e1 = 'Filtered_compositional_gravity'
Detailed Description
Set parameters for forces from control data.
      subroutine s_set_control_4_force                                &
     &         (frc_ctl, g_ctl, cor_ctl, mcv_ctl, MHD_prop)
        type(forces_control), intent(in) :: frc_ctl
        type(gravity_control), intent(in) :: g_ctl
        type(coriolis_control), intent(in) :: cor_ctl
        type(magneto_convection_control), intent(in) :: mcv_ctl
        type(MHD_evolution_param), intent(inout) :: MHD_prop
Function/Subroutine Documentation
s_set_control_4_force()
subroutine set_control_4_force::s_set_control_4_force (type(forces_control), intent(in) frc_ctl, type(gravity_control), intent(in) g_ctl, type(coriolis_control), intent(in) cor_ctl, type(magneto_convection_control), intent(in) mcv_ctl, type(mhd_evolution_param), intent(inout) MHD_prop)
Definition at line 54 of file set_control_4_force.f90.
References set_control_4_coriolis_force(), set_control_4_gravity(), set_control_4_induction(), and set_control_force_flags().
Referenced by set_control_sph_mhd::set_control_4_sph_mhd().
set_control_4_coriolis_force()
subroutine, private set_control_4_force::set_control_4_coriolis_force (type(coriolis_control), intent(in) cor_ctl, type(fluid_property), intent(inout) fl_prop) private
Definition at line 248 of file set_control_4_force.f90.
References skip_comment_f::cmp_no_case(), t_physical_property::id_crank_nicolson, t_physical_property::id_crank_nicolson_cmass, t_physical_property::id_force_at_node, m_machine_parameter::iflag_debug, m_machine_parameter::iflag_routine_msg, m_constants::one, skip_comment_f::yes_flag(), and m_constants::zero.
Referenced by s_set_control_4_force().
set_control_4_gravity()
subroutine, private set_control_4_force::set_control_4_gravity (type(gravity_control), intent(in) g_ctl, type(fluid_property), intent(inout) fl_prop) private
Definition at line 176 of file set_control_4_force.f90.
References skip_comment_f::cmp_no_case(), m_machine_parameter::e_message, t_physical_property::id_crank_nicolson_cmass, t_physical_property::id_force_at_node, t_physical_property::id_force_ele_int, m_error_ids::ierr_force, t_physical_property::iflag_const_g, m_machine_parameter::iflag_debug, t_physical_property::iflag_no_gravity, t_physical_property::iflag_radial_g, m_machine_parameter::iflag_routine_msg, and t_physical_property::iflag_self_r_g.
Referenced by s_set_control_4_force().
set_control_4_induction()
subroutine, private set_control_4_force::set_control_4_induction (type(magneto_convection_control), intent(in) mcv_ctl, type(conductive_property), intent(inout) cd_prop) private
Definition at line 301 of file set_control_4_force.f90.
References skip_comment_f::cmp_no_case(), m_machine_parameter::e_message, m_constants::id_turn_off, m_constants::id_turn_on, m_error_ids::ierr_force, m_machine_parameter::iflag_debug, m_machine_parameter::iflag_routine_msg, t_physical_property::set_filtered_induction_ctl(), and skip_comment_f::yes_flag().
Referenced by s_set_control_4_force().
set_control_force_flags()
subroutine, private set_control_4_force::set_control_force_flags (type(forces_control), intent(in) frc_ctl, type(fluid_property), intent(inout) fl_prop) private
Definition at line 85 of file set_control_4_force.f90.
References t_physical_property::alloc_force_list(), skip_comment_f::cmp_no_case(), m_force_control_labels::comp_gravity_e1, m_force_control_labels::comp_gravity_e5, m_force_control_labels::comp_gravity_e6, m_force_control_labels::comp_gravity_label, filtered_comp_gravity_e1, filtered_comp_gravity_label, filtered_gravity_e1, filtered_gravity_label, m_force_control_labels::gravity_e1, m_force_control_labels::gravity_e2, m_force_control_labels::gravity_e5, m_force_control_labels::gravity_label, t_physical_property::id_no_evolution, m_machine_parameter::iflag_debug, m_machine_parameter::iflag_routine_msg, and m_force_control_labels::lorentz_label.
Referenced by s_set_control_4_force().
Variable Documentation
filtered_comp_gravity_e1
character(len=kchara), parameter set_control_4_force::filtered_comp_gravity_e1 = 'Filtered_compositional_gravity'
Definition at line 41 of file set_control_4_force.f90.
Referenced by set_control_force_flags().
filtered_comp_gravity_label
character(len=kchara), parameter set_control_4_force::filtered_comp_gravity_label = 'Filtered_compositional_buoyancy'
Filtered compositional buoyancy label.
Definition at line 37 of file set_control_4_force.f90.
Referenced by set_control_force_flags().
filtered_gravity_e1
character(len=kchara), parameter set_control_4_force::filtered_gravity_e1 = 'Filtered_gravity'
Definition at line 33 of file set_control_4_force.f90.
Referenced by set_control_force_flags().
filtered_gravity_label
character(len=kchara), parameter set_control_4_force::filtered_gravity_label = 'Filtered_buoyancy'
Filtered thermal buoyancy label.
Definition at line 30 of file set_control_4_force.f90.
Referenced by set_control_force_flags().