CALYPSO: set_to_send_buf_tri Module Reference
set_to_send_buf_tri Module Reference
Arbitrary components data communication.
Functions/Subroutines
subroutine set_to_send_buf_3x1 (nnod_org, nnod_send, inod_export, X1_org, X2_org, X3_org, WS)
subroutine set_to_send_buf_3x2 (nnod_org, nnod_send, inod_export, X1_org, X2_org, X3_org, WS)
subroutine set_to_send_buf_3x3 (nnod_org, nnod_send, inod_export, X1_org, X2_org, X3_org, WS)
subroutine set_to_send_buf_3x6 (nnod_org, nnod_send, inod_export, X1_org, X2_org, X3_org, WS)
subroutine set_to_send_buf_3xn (NB, nnod_org, nnod_send, inod_export, X1_org, X2_org, X3_org, WS)
subroutine set_to_send_buf_3xn_mod (NB, nnod_org, npe_send, nnod_send, istack_send, inod_export, X1_org, X2_org, X3_org, WS)
Detailed Description
Arbitrary components data communication.
      subroutine set_to_send_buf_3x1(nnod_org,                        &
     &          nnod_send, inod_export, X1_org, X2_org, X3_org, WS)
      subroutine set_to_send_buf_3x2(nnod_org,                        &
     &          nnod_send, inod_export, X1_org, X2_org, X3_org, WS)
      subroutine set_to_send_buf_3x3(nnod_org,                        &
     &          nnod_send, inod_export, X1_org, X2_org, X3_org, WS)
      subroutine set_to_send_buf_3x6(nnod_org,                        &
     &          nnod_send, inod_export, X1_org, X2_org, X3_org, WS)
      subroutine set_to_send_buf_3xN(NB, nnod_org,                    &
     &          nnod_send, inod_export, X1_org, X2_org, X3_org, WS)
      subroutine set_to_send_buf_3xN_mod(NB, nnod_org,                &
     &          npe_send, nnod_send, istack_send, inod_export,        &
     &          X1_org, X2_org, X3_org, WS)
Parameters
NB Number of components for communication
nnod_org Number of data points for origin
npe_send Number of processses to send
isend_self Integer flag to copy within own process
nnod_send Number of data points to send
id_pe_send(npe_send) Process ID to send
istack_send(0:npe_send) End points of send buffer for each process
inod_export(nnod_send) local node ID to copy in send buffer
X_org(NB*nnod_org) Send data
Function/Subroutine Documentation
set_to_send_buf_3x1()
subroutine set_to_send_buf_tri::set_to_send_buf_3x1 (integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) nnod_send, integer(kind = kint), dimension(nnod_send), intent(in) inod_export, real (kind=kreal), dimension(nnod_org), intent(in) X1_org, real (kind=kreal), dimension(nnod_org), intent(in) X2_org, real (kind=kreal), dimension(nnod_org), intent(in) X3_org, real (kind=kreal), dimension(3*nnod_send), intent(inout) WS)
Definition at line 51 of file set_to_send_buf_tri.f90.
Referenced by calypso_sr::calypso_send_recv_3x1().
set_to_send_buf_3x2()
subroutine set_to_send_buf_tri::set_to_send_buf_3x2 (integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) nnod_send, integer(kind = kint), dimension(nnod_send), intent(in) inod_export, real (kind=kreal), dimension(2*nnod_org), intent(in) X1_org, real (kind=kreal), dimension(2*nnod_org), intent(in) X2_org, real (kind=kreal), dimension(2*nnod_org), intent(in) X3_org, real (kind=kreal), dimension(6*nnod_send), intent(inout) WS)
Definition at line 79 of file set_to_send_buf_tri.f90.
Referenced by calypso_sr_2::calypso_send_recv_3x2().
set_to_send_buf_3x3()
subroutine set_to_send_buf_tri::set_to_send_buf_3x3 (integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) nnod_send, integer(kind = kint), dimension(nnod_send), intent(in) inod_export, real (kind=kreal), dimension(3*nnod_org), intent(in) X1_org, real (kind=kreal), dimension(3*nnod_org), intent(in) X2_org, real (kind=kreal), dimension(3*nnod_org), intent(in) X3_org, real (kind=kreal), dimension(9*nnod_send), intent(inout) WS)
Definition at line 110 of file set_to_send_buf_tri.f90.
Referenced by calypso_sr_3::calypso_send_recv_3x3().
set_to_send_buf_3x6()
subroutine set_to_send_buf_tri::set_to_send_buf_3x6 (integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) nnod_send, integer(kind = kint), dimension(nnod_send), intent(in) inod_export, real (kind=kreal), dimension(6*nnod_org), intent(in) X1_org, real (kind=kreal), dimension(6*nnod_org), intent(in) X2_org, real (kind=kreal), dimension(6*nnod_org), intent(in) X3_org, real (kind=kreal), dimension(18*nnod_send), intent(inout) WS)
Definition at line 144 of file set_to_send_buf_tri.f90.
Referenced by calypso_sr_6::calypso_send_recv_3x6().
set_to_send_buf_3xn()
subroutine set_to_send_buf_tri::set_to_send_buf_3xn (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) nnod_send, integer(kind = kint), dimension(nnod_send), intent(in) inod_export, real (kind=kreal), dimension(nb*nnod_org), intent(in) X1_org, real (kind=kreal), dimension(nb*nnod_org), intent(in) X2_org, real (kind=kreal), dimension(nb*nnod_org), intent(in) X3_org, real (kind=kreal), dimension(3*nb*nnod_send), intent(inout) WS)
Definition at line 187 of file set_to_send_buf_tri.f90.
set_to_send_buf_3xn_mod()
subroutine set_to_send_buf_tri::set_to_send_buf_3xn_mod (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) npe_send, integer(kind = kint), intent(in) nnod_send, integer(kind = kint), dimension(0:npe_send), intent(in) istack_send, integer(kind = kint), dimension(nnod_send), intent(in) inod_export, real (kind=kreal), dimension(nb*nnod_org), intent(in) X1_org, real (kind=kreal), dimension(nb*nnod_org), intent(in) X2_org, real (kind=kreal), dimension(nb*nnod_org), intent(in) X3_org, real (kind=kreal), dimension(3*nb*nnod_send), intent(inout) WS)
Definition at line 220 of file set_to_send_buf_tri.f90.
Referenced by calypso_sr_n::calypso_send_recv_3xn().