CALYPSO: t_next_node_ele_4_node Module Reference
t_next_node_ele_4_node Module Reference
Neighbouring node and element list for each node.
Data Types
type element_around_node
Structure of belonged element list for each node.
type next_nod_ele_table
Structure of neighbouring node and element list for each node.
type next_nod_id_4_nod
Structure of neighbouring node list for each node.
Functions/Subroutines
subroutine alloc_numele_belonged (numnod, neib_ele)
subroutine alloc_iele_belonged (neib_ele)
subroutine alloc_num_next_node (numnod, neib_nod)
subroutine alloc_inod_next_node (neib_nod)
subroutine dealloc_next_nod_ele_table (next_tbl)
subroutine dealloc_iele_belonged (neib_ele)
subroutine dealloc_inod_next_node (neib_nod)
subroutine check_ele_id_4_node_type (id_rank, numnod, neib_ele)
subroutine check_next_node_id_4_node (id_rank, numnod, neib_nod)
Detailed Description
Neighbouring node and element list for each node.
      subroutine alloc_numele_belonged(numnod, neib_ele)
        integer(kind= kint), intent(in) :: numnod
        type(element_around_node), intent(inout) :: neib_ele
      subroutine alloc_iele_belonged(neib_ele)
        type(element_around_node), intent(inout) :: neib_ele
      subroutine alloc_num_next_node(numnod, neib_nod)
        integer(kind= kint), intent(in) :: numnod
        type(next_nod_id_4_nod), intent(inout) :: neib_nod
      subroutine alloc_inod_next_node(neib_nod)
        type(next_nod_id_4_nod), intent(inout) :: neib_nod
      subroutine dealloc_iele_belonged(neib_ele)
        type(element_around_node), intent(inout) :: neib_ele
      subroutine dealloc_inod_next_node(neib_nod)
        type(next_nod_id_4_nod), intent(inout) :: neib_nod
      subroutine dealloc_next_nod_ele_table(next_tbl)
        type(next_nod_ele_table), intent(inout) :: next_tbl
      subroutine check_ele_id_4_node_type(id_rank, numnod, neib_ele)
        integer, intent(in) :: id_rank
        integer(kind = kint), intent(in) :: numnod
        type(element_around_node), intent(in) :: neib_ele
      subroutine check_next_node_id_4_node(id_rank, numnod, neib_nod)
        integer, intent(in) :: id_rank
        integer(kind = kint), intent(in) :: numnod
        type(next_nod_id_4_nod), intent(in) :: neib_nod
Function/Subroutine Documentation
alloc_iele_belonged()
subroutine t_next_node_ele_4_node::alloc_iele_belonged (type(element_around_node), intent(inout) neib_ele)
Definition at line 113 of file t_next_node_ele_4_node.f90.
Referenced by t_belonged_element_4_node::belonged_edge_id_4_node(), t_belonged_element_4_node::belonged_ele_id_4_node(), t_belonged_element_4_node::belonged_surf_id_4_node(), set_ele_id_4_node_type::set_edge_id_4_node(), set_ele_id_4_node_type::set_ele_id_4_node(), set_ele_id_4_node_type::set_grouped_ele_id_4_node(), set_ele_id_4_node_type::set_layerd_ele_id_4_node(), and set_ele_id_4_node_type::set_surf_id_4_node().
alloc_inod_next_node()
subroutine t_next_node_ele_4_node::alloc_inod_next_node (type(next_nod_id_4_nod), intent(inout) neib_nod)
Definition at line 147 of file t_next_node_ele_4_node.f90.
Referenced by set_ele_id_4_node_type::const_next_nod_id_4_node().
alloc_num_next_node()
subroutine t_next_node_ele_4_node::alloc_num_next_node (integer(kind= kint), intent(in) numnod, type(next_nod_id_4_nod), intent(inout) neib_nod)
Definition at line 130 of file t_next_node_ele_4_node.f90.
Referenced by set_ele_id_4_node_type::const_next_nod_id_4_node().
alloc_numele_belonged()
subroutine t_next_node_ele_4_node::alloc_numele_belonged (integer(kind= kint), intent(in) numnod, type(element_around_node), intent(inout) neib_ele)
Definition at line 98 of file t_next_node_ele_4_node.f90.
Referenced by t_belonged_element_4_node::belonged_edge_id_4_node(), t_belonged_element_4_node::belonged_ele_id_4_node(), t_belonged_element_4_node::belonged_surf_id_4_node(), set_ele_id_4_node_type::set_edge_id_4_node(), set_ele_id_4_node_type::set_ele_id_4_node(), set_ele_id_4_node_type::set_grouped_ele_id_4_node(), set_ele_id_4_node_type::set_layerd_ele_id_4_node(), and set_ele_id_4_node_type::set_surf_id_4_node().
check_ele_id_4_node_type()
subroutine t_next_node_ele_4_node::check_ele_id_4_node_type (integer, intent(in) id_rank, integer(kind = kint), intent(in) numnod, type(element_around_node), intent(in) neib_ele)
Definition at line 204 of file t_next_node_ele_4_node.f90.
check_next_node_id_4_node()
subroutine t_next_node_ele_4_node::check_next_node_id_4_node (integer, intent(in) id_rank, integer(kind = kint), intent(in) numnod, type(next_nod_id_4_nod), intent(in) neib_nod)
Definition at line 227 of file t_next_node_ele_4_node.f90.
dealloc_iele_belonged()
subroutine t_next_node_ele_4_node::dealloc_iele_belonged (type(element_around_node), intent(inout) neib_ele)
Definition at line 175 of file t_next_node_ele_4_node.f90.
Referenced by const_element_comm_tables::const_edge_comm_table(), const_element_comm_tables::const_ele_comm_tbl(), const_element_comm_tables::const_surf_comm_table(), t_belonged_element_4_node::dealloc_belonged_id_4_node(), and dealloc_next_nod_ele_table().
dealloc_inod_next_node()
subroutine t_next_node_ele_4_node::dealloc_inod_next_node (type(next_nod_id_4_nod), intent(inout) neib_nod)
Definition at line 189 of file t_next_node_ele_4_node.f90.
Referenced by dealloc_next_nod_ele_table().
dealloc_next_nod_ele_table()
subroutine t_next_node_ele_4_node::dealloc_next_nod_ele_table (type(next_nod_ele_table), intent(inout) next_tbl)
Definition at line 164 of file t_next_node_ele_4_node.f90.
References dealloc_iele_belonged(), and dealloc_inod_next_node().