CALYPSO: t_control_data_surfacings Module Reference
t_control_data_surfacings Module Reference
Control data structure for visualization controls.
Data Types
type surfacing_controls
Structures of surfacing controls.
Functions/Subroutines
subroutine read_surfacing_controls (id_control, hd_block, surfacing_ctls, c_buf)
subroutine bcast_surfacing_controls (surfacing_ctls)
subroutine dealloc_surfacing_controls (surfacing_ctls)
subroutine section_step_ctls_to_time_ctl (surfacing_ctls, tctl)
integer(kind=kint) function num_label_surfacings ()
subroutine set_label_surfacings (names)
Variables
character(len=kchara), parameter, private hd_section_ctl = 'cross_section_ctl'
character(len=kchara), parameter, private hd_isosurf_ctl = 'isosurface_ctl'
character(len=kchara), parameter, private hd_i_step_section = 'i_step_sectioning_ctl'
character(len=kchara), parameter, private hd_i_step_isosurf = 'i_step_isosurface_ctl'
character(len=kchara), parameter, private hd_i_step_ucd = 'i_step_field_ctl'
character(len=kchara), parameter, private hd_delta_t_section = 'delta_t_sectioning_ctl'
character(len=kchara), parameter, private hd_delta_t_isosurf = 'delta_t_isosurface_ctl'
character(len=kchara), parameter, private hd_delta_t_ucd = 'delta_t_field_ctl'
character(len=kchara), parameter, private hd_output_fld_file_fmt = 'output_field_file_fmt_ctl'
integer(kind=kint), parameter, private n_label_surfacings = 9
Detailed Description
Control data structure for visualization controls.
      subroutine read_surfacing_controls                              &
     &         (id_control, hd_block, surfacing_ctls, c_buf)
      subroutine bcast_surfacing_controls(surfacing_ctls)
      subroutine dealloc_surfacing_controls(surfacing_ctls)
       type(surfacing_controls), intent(inout) :: surfacing_ctls
       type(buffer_for_control), intent(inout)  :: c_buf
      subroutine section_step_ctls_to_time_ctl(surfacing_ctls, tctl)
        type(surfacing_controls), intent(in) :: surfacing_ctls
        type(time_data_control), intent(inout) :: tctl
      integer(kind = kint) function num_label_surfacings()
      subroutine set_label_surfacings(names)
  begin visual_control
    delta_t_sectioning_ctl   1.0e-3
    i_step_sectioning_ctl    400
    array  cross_section_ctl  1
      ....
    end array cross_section_ctl
    delta_t_isosurface_ctl   1.0e-3
    i_step_isosurface_ctl    400
    array  isosurface_ctl  1
      ....
    end array isosurface_ctl
    delta_t_field_ctl        1.0e-3
    i_step_field_ctl         800
    output_field_file_fmt_ctl   'VTK'
  end visual_control
Function/Subroutine Documentation
bcast_surfacing_controls()
subroutine t_control_data_surfacings::bcast_surfacing_controls (type(surfacing_controls), intent(inout) surfacing_ctls)
Definition at line 170 of file t_control_data_surfacings.f90.
References bcast_control_arrays::bcast_ctl_type_c1(), bcast_control_arrays::bcast_ctl_type_i1(), bcast_control_arrays::bcast_ctl_type_r1(), t_control_data_isosurfaces::bcast_files_4_iso_ctl(), t_control_data_sections::bcast_files_4_psf_ctl(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by t_control_data_section_only::bcast_section_control_data(), t_ctl_data_mhd::bcast_sph_mhd_ctl_w_psf(), and t_control_data_section_only::reset_section_control_data().
dealloc_surfacing_controls()
subroutine t_control_data_surfacings::dealloc_surfacing_controls (type(surfacing_controls), intent(inout) surfacing_ctls)
Definition at line 198 of file t_control_data_surfacings.f90.
References t_control_data_isosurfaces::dealloc_iso_ctl_stract(), and t_control_data_sections::dealloc_psf_ctl_stract().
Referenced by t_viz_sections::init_visualize_surface().
num_label_surfacings()
integer(kind = kint) function t_control_data_surfacings::num_label_surfacings
Definition at line 265 of file t_control_data_surfacings.f90.
References n_label_surfacings.
read_surfacing_controls()
subroutine t_control_data_surfacings::read_surfacing_controls (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(surfacing_controls), intent(inout) surfacing_ctls, type(buffer_for_control), intent(inout) c_buf)
Definition at line 117 of file t_control_data_surfacings.f90.
References t_read_control_elements::check_array_flag(), t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_delta_t_isosurf, hd_delta_t_section, hd_delta_t_ucd, hd_i_step_isosurf, hd_i_step_section, hd_i_step_ucd, t_control_data_isosurfaces::hd_isosurf_ctl, hd_output_fld_file_fmt, t_control_data_sections::hd_section_ctl, t_read_control_elements::load_one_line_from_control(), t_control_array_character::read_chara_ctl_type(), t_control_data_isosurfaces::read_files_4_iso_ctl(), t_control_data_sections::read_files_4_psf_ctl(), t_control_array_integer::read_integer_ctl_type(), and t_control_array_real::read_real_ctl_type().
Referenced by t_control_data_section_only::read_section_control_data(), and t_ctl_data_mhd::read_sph_mhd_ctl_w_psf().
section_step_ctls_to_time_ctl()
subroutine t_control_data_surfacings::section_step_ctls_to_time_ctl (type(surfacing_controls), intent(in) surfacing_ctls, type(time_data_control), intent(inout) tctl)
Definition at line 223 of file t_control_data_surfacings.f90.
References t_control_array_integer::copy_integer_ctl(), and t_control_array_real::copy_real_ctl().
Referenced by t_ctl_data_sph_mhd_psf::read_control_4_sph_mhd_w_psf(), and t_control_data_section_only::read_control_data_section_only().
set_label_surfacings()
subroutine t_control_data_surfacings::set_label_surfacings (character(len = kchara), dimension(n_label_surfacings), intent(inout) names)
Definition at line 272 of file t_control_data_surfacings.f90.
References hd_delta_t_isosurf, hd_delta_t_section, hd_delta_t_ucd, hd_i_step_isosurf, hd_i_step_section, hd_i_step_ucd, t_control_data_isosurfaces::hd_isosurf_ctl, hd_output_fld_file_fmt, and t_control_data_sections::hd_section_ctl.
Variable Documentation
hd_delta_t_isosurf
character(len=kchara), parameter, private t_control_data_surfacings::hd_delta_t_isosurf = 'delta_t_isosurface_ctl' private
Definition at line 100 of file t_control_data_surfacings.f90.
Referenced by read_surfacing_controls(), and set_label_surfacings().
hd_delta_t_section
character(len=kchara), parameter, private t_control_data_surfacings::hd_delta_t_section = 'delta_t_sectioning_ctl' private
Definition at line 98 of file t_control_data_surfacings.f90.
Referenced by read_surfacing_controls(), and set_label_surfacings().
hd_delta_t_ucd
character(len=kchara), parameter, private t_control_data_surfacings::hd_delta_t_ucd = 'delta_t_field_ctl' private
Definition at line 102 of file t_control_data_surfacings.f90.
Referenced by read_surfacing_controls(), and set_label_surfacings().
hd_i_step_isosurf
character(len=kchara), parameter, private t_control_data_surfacings::hd_i_step_isosurf = 'i_step_isosurface_ctl' private
Definition at line 93 of file t_control_data_surfacings.f90.
Referenced by read_surfacing_controls(), and set_label_surfacings().
hd_i_step_section
character(len=kchara), parameter, private t_control_data_surfacings::hd_i_step_section = 'i_step_sectioning_ctl' private
Definition at line 91 of file t_control_data_surfacings.f90.
Referenced by read_surfacing_controls(), and set_label_surfacings().
hd_i_step_ucd
character(len=kchara), parameter, private t_control_data_surfacings::hd_i_step_ucd = 'i_step_field_ctl' private
Definition at line 95 of file t_control_data_surfacings.f90.
Referenced by read_surfacing_controls(), and set_label_surfacings().
hd_isosurf_ctl
character(len=kchara), parameter, private t_control_data_surfacings::hd_isosurf_ctl = 'isosurface_ctl' private
Definition at line 88 of file t_control_data_surfacings.f90.
hd_output_fld_file_fmt
character(len=kchara), parameter, private t_control_data_surfacings::hd_output_fld_file_fmt = 'output_field_file_fmt_ctl' private
Definition at line 105 of file t_control_data_surfacings.f90.
Referenced by read_surfacing_controls(), and set_label_surfacings().
hd_section_ctl
character(len=kchara), parameter, private t_control_data_surfacings::hd_section_ctl = 'cross_section_ctl' private
Definition at line 86 of file t_control_data_surfacings.f90.
n_label_surfacings
integer(kind = kint), parameter, private t_control_data_surfacings::n_label_surfacings = 9 private
Definition at line 108 of file t_control_data_surfacings.f90.
Referenced by num_label_surfacings().