CALYPSO: t_ctl_data_sph_vol_spectr Module Reference
t_ctl_data_sph_vol_spectr Module Reference
Data Types
type layerd_spectr_control
type volume_spectr_control
Functions/Subroutines
subroutine copy_volume_spectr_ctls (num_ctl, org_vpwr, new_vpwr)
subroutine copy_volume_spectr_control (org_vpwr, new_vpwr)
subroutine read_each_vol_spectr_ctl (id_control, hd_block, iflag, v_pwr, c_buf)
subroutine read_layerd_spectr_ctl (id_control, hd_block, iflag, lp_ctl, c_buf)
subroutine reset_volume_spectr_control (v_pwr)
subroutine dealloc_num_spec_layer_ctl (lp_ctl)
Variables
character(len=kchara), parameter, private hd_vol_pwr = 'volume_pwr_spectr_prefix'
character(len=kchara), parameter, private hd_vol_ave = 'volume_average_prefix'
character(len=kchara), parameter, private hd_inner_r = 'inner_radius_ctl'
character(len=kchara), parameter, private hd_outer_r = 'outer_radius_ctl'
character(len=kchara), parameter hd_layer_rms_head = 'layered_pwr_spectr_prefix'
character(len=kchara), parameter hd_spctr_layer = 'spectr_layer_ctl'
character(len=kchara), parameter, private hd_degree_spectr_switch = 'degree_spectr_switch'
character(len=kchara), parameter, private hd_order_spectr_switch = 'order_spectr_switch'
character(len=kchara), parameter, private hd_diff_lm_spectr_switch = 'axisymmetric_spectr_switch'
character(len=kchara), parameter, private hd_axis_spectr_switch = 'diff_lm_spectr_switch'
Function/Subroutine Documentation
copy_volume_spectr_control()
subroutine t_ctl_data_sph_vol_spectr::copy_volume_spectr_control (type(volume_spectr_control), intent(in) org_vpwr, type(volume_spectr_control), intent(inout) new_vpwr)
Definition at line 176 of file t_ctl_data_sph_vol_spectr.f90.
References t_control_array_character::copy_chara_ctl(), and t_control_array_real::copy_real_ctl().
Referenced by t_ctl_data_4_sph_monitor::append_volume_spectr_ctls(), and copy_volume_spectr_ctls().
copy_volume_spectr_ctls()
subroutine t_ctl_data_sph_vol_spectr::copy_volume_spectr_ctls (integer(kind = kint), intent(in) num_ctl, type(volume_spectr_control), dimension(num_ctl), intent(in) org_vpwr, type(volume_spectr_control), dimension(num_ctl), intent(inout) new_vpwr)
Definition at line 160 of file t_ctl_data_sph_vol_spectr.f90.
References copy_volume_spectr_control().
Referenced by t_ctl_data_4_sph_monitor::append_volume_spectr_ctls().
dealloc_num_spec_layer_ctl()
subroutine t_ctl_data_sph_vol_spectr::dealloc_num_spec_layer_ctl (type(layerd_spectr_control), intent(inout) lp_ctl)
Definition at line 279 of file t_ctl_data_sph_vol_spectr.f90.
References t_control_array_integer::dealloc_control_array_int().
Referenced by t_ctl_data_4_sph_monitor::dealloc_sph_monitoring_ctl().
read_each_vol_spectr_ctl()
subroutine t_ctl_data_sph_vol_spectr::read_each_vol_spectr_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, integer(kind = kint), intent(inout) iflag, type(volume_spectr_control), intent(inout) v_pwr, type(buffer_for_control), intent(inout) c_buf)
Definition at line 195 of file t_ctl_data_sph_vol_spectr.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_inner_r, hd_outer_r, hd_vol_ave, hd_vol_pwr, t_read_control_elements::load_one_line_from_control(), t_control_array_character::read_chara_ctl_type(), and t_control_array_real::read_real_ctl_type().
Referenced by t_ctl_data_4_sph_monitor::read_volume_spectr_ctl().
read_layerd_spectr_ctl()
subroutine t_ctl_data_sph_vol_spectr::read_layerd_spectr_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, integer(kind = kint), intent(inout) iflag, type(layerd_spectr_control), intent(inout) lp_ctl, type(buffer_for_control), intent(inout) c_buf)
Definition at line 227 of file t_ctl_data_sph_vol_spectr.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_axis_spectr_switch, hd_degree_spectr_switch, hd_diff_lm_spectr_switch, hd_layer_rms_head, hd_order_spectr_switch, hd_spctr_layer, t_read_control_elements::load_one_line_from_control(), t_control_array_character::read_chara_ctl_type(), and t_control_array_integer::read_control_array_i1().
Referenced by t_ctl_data_4_sph_monitor::read_sph_monitoring_ctl().
reset_volume_spectr_control()
subroutine t_ctl_data_sph_vol_spectr::reset_volume_spectr_control (type(volume_spectr_control), intent(inout) v_pwr)
Definition at line 266 of file t_ctl_data_sph_vol_spectr.f90.
Referenced by t_ctl_data_4_sph_monitor::append_volume_spectr_ctls(), and t_ctl_data_4_sph_monitor::dealloc_sph_monitoring_ctl().
Variable Documentation
hd_axis_spectr_switch
character(len=kchara), parameter, private t_ctl_data_sph_vol_spectr::hd_axis_spectr_switch = 'diff_lm_spectr_switch' private
Definition at line 147 of file t_ctl_data_sph_vol_spectr.f90.
Referenced by read_layerd_spectr_ctl().
hd_degree_spectr_switch
character(len=kchara), parameter, private t_ctl_data_sph_vol_spectr::hd_degree_spectr_switch = 'degree_spectr_switch' private
Definition at line 140 of file t_ctl_data_sph_vol_spectr.f90.
Referenced by read_layerd_spectr_ctl().
hd_diff_lm_spectr_switch
character(len=kchara), parameter, private t_ctl_data_sph_vol_spectr::hd_diff_lm_spectr_switch = 'axisymmetric_spectr_switch' private
Definition at line 144 of file t_ctl_data_sph_vol_spectr.f90.
Referenced by read_layerd_spectr_ctl().
hd_inner_r
character(len=kchara), parameter, private t_ctl_data_sph_vol_spectr::hd_inner_r = 'inner_radius_ctl' private
Definition at line 128 of file t_ctl_data_sph_vol_spectr.f90.
Referenced by read_each_vol_spectr_ctl().
hd_layer_rms_head
character(len=kchara), parameter t_ctl_data_sph_vol_spectr::hd_layer_rms_head = 'layered_pwr_spectr_prefix'
Definition at line 134 of file t_ctl_data_sph_vol_spectr.f90.
Referenced by read_layerd_spectr_ctl().
hd_order_spectr_switch
character(len=kchara), parameter, private t_ctl_data_sph_vol_spectr::hd_order_spectr_switch = 'order_spectr_switch' private
Definition at line 142 of file t_ctl_data_sph_vol_spectr.f90.
Referenced by read_layerd_spectr_ctl().
hd_outer_r
character(len=kchara), parameter, private t_ctl_data_sph_vol_spectr::hd_outer_r = 'outer_radius_ctl' private
Definition at line 130 of file t_ctl_data_sph_vol_spectr.f90.
Referenced by read_each_vol_spectr_ctl().
hd_spctr_layer
character(len=kchara), parameter t_ctl_data_sph_vol_spectr::hd_spctr_layer = 'spectr_layer_ctl'
Definition at line 137 of file t_ctl_data_sph_vol_spectr.f90.
Referenced by read_layerd_spectr_ctl().
hd_vol_ave
character(len=kchara), parameter, private t_ctl_data_sph_vol_spectr::hd_vol_ave = 'volume_average_prefix' private
Definition at line 126 of file t_ctl_data_sph_vol_spectr.f90.
Referenced by read_each_vol_spectr_ctl().
hd_vol_pwr
character(len=kchara), parameter, private t_ctl_data_sph_vol_spectr::hd_vol_pwr = 'volume_pwr_spectr_prefix' private
Definition at line 124 of file t_ctl_data_sph_vol_spectr.f90.
Referenced by read_each_vol_spectr_ctl().