CALYPSO: copy_rtp_data_to_fftpack Module Reference
copy_rtp_data_to_fftpack Module Reference
communication table from FFTPACK5
Functions/Subroutines
subroutine copy_fftpack_to_rtp_field (nnod_rtp, nidx_rtp, irt_rtp_smp_stack, ncomp_bwd, X_FFT, X_rtp)
subroutine copy_fftpack_from_rtp_field (nnod_rtp, nidx_rtp, irt_rtp_smp_stack, ncomp_fwd, X_rtp, X_FFT)
subroutine copy_fftpack_to_rtp_comp (nnod_rtp, nidx_rtp, irt_rtp_smp_stack, X_FFT, X_rtp)
subroutine copy_fftpack_from_rtp_comp (nnod_rtp, nidx_rtp, irt_rtp_smp_stack, X_rtp, X_FFT)
subroutine copy_fftpack_to_prt_field (nnod_rtp, ncomp_bwd, X_FFT, X_prt)
subroutine copy_fftpack_from_prt_field (nnod_rtp, ncomp_fwd, X_prt, X_FFT)
subroutine copy_fftpack_to_prt_comp (nnod_rtp, X_prt, X_FFT)
Detailed Description
communication table from FFTPACK5
      subroutine copy_FFTPACK_to_rtp_field(nnod_rtp, nidx_rtp,        &
     &          irt_rtp_smp_stack, ncomp_bwd, X_FFT, X_rtp)
      subroutine copy_FFTPACK_from_rtp_field(nnod_rtp, nidx_rtp,      &
     &          irt_rtp_smp_stack, ncomp_fwd, X_rtp, X_FFT)
      subroutine copy_FFTPACK_to_rtp_comp(nnod_rtp, nidx_rtp,         &
     &          irt_rtp_smp_stack, X_FFT, X_rtp)
      subroutine copy_FFTPACK_from_rtp_comp(nnod_rtp, nidx_rtp,       &
     &          irt_rtp_smp_stack, X_rtp, X_FFT)
      subroutine copy_FFTPACK_to_prt_field                            &
     &         (nnod_rtp, ncomp_bwd, X_FFT, X_prt)
      subroutine copy_FFTPACK_from_prt_field                          &
     &         (nnod_rtp, ncomp_fwd, X_prt, X_FFT)
      subroutine copy_FFTPACK_to_prt_comp(nnod_rtp, X_prt, X_FFT)
Function/Subroutine Documentation
copy_fftpack_from_prt_field()
subroutine copy_rtp_data_to_fftpack::copy_fftpack_from_prt_field (integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) ncomp_fwd, real(kind = kreal), dimension(nnod_rtp,ncomp_fwd), intent(in) X_prt, real(kind = kreal), dimension(ncomp_fwd*nnod_rtp), intent(inout) X_FFT)
Definition at line 215 of file copy_rtp_data_to_FFTPACK.f90.
copy_fftpack_from_rtp_comp()
subroutine copy_rtp_data_to_fftpack::copy_fftpack_from_rtp_comp (integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(3), intent(in) nidx_rtp, integer(kind = kint), dimension(0:np_smp), intent(in) irt_rtp_smp_stack, real(kind = kreal), dimension(irt_rtp_smp_stack(np_smp),nidx_rtp(3)), intent(in) X_rtp, real(kind = kreal), dimension(nnod_rtp), intent(inout) X_FFT)
Definition at line 153 of file copy_rtp_data_to_FFTPACK.f90.
Referenced by sph_rtp_domain_fftpack5::rtp_domain_rfftmf_to_send(), and sph_rtp_domain_fftw::rtp_field_fwd_fftw_to_send().
copy_fftpack_from_rtp_field()
subroutine copy_rtp_data_to_fftpack::copy_fftpack_from_rtp_field (integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(3), intent(in) nidx_rtp, integer(kind = kint), dimension(0:np_smp), intent(in) irt_rtp_smp_stack, integer(kind = kint), intent(in) ncomp_fwd, real(kind = kreal), dimension(irt_rtp_smp_stack(np_smp),nidx_rtp(3),ncomp_fwd), intent(in) X_rtp, real(kind = kreal), dimension(ncomp_fwd*nnod_rtp), intent(inout) X_FFT)
Definition at line 80 of file copy_rtp_data_to_FFTPACK.f90.
Referenced by sph_rtp_fftw::rtp_fwd_fftw_to_send(), and sph_rtp_fftpack5::rtp_rfftmf_to_send().
copy_fftpack_to_prt_comp()
subroutine copy_rtp_data_to_fftpack::copy_fftpack_to_prt_comp (integer(kind = kint), intent(in) nnod_rtp, real(kind = kreal), dimension(nnod_rtp), intent(in) X_prt, real(kind = kreal), dimension(nnod_rtp), intent(inout) X_FFT)
Definition at line 240 of file copy_rtp_data_to_FFTPACK.f90.
Referenced by sph_prt_fftw::prt_back_fftw_from_recv(), sph_prt_domain_fftpack5::prt_domain_rfftmb_from_recv(), sph_prt_domain_fftpack5::prt_domain_rfftmf_to_send(), sph_prt_domain_fftw::prt_field_back_fftw_from_recv(), sph_prt_domain_fftw::prt_field_fwd_fftw_to_send(), sph_prt_fftw::prt_fwd_fftw_to_send(), sph_prt_fftpack5::prt_rfftmb_from_recv(), and sph_prt_fftpack5::prt_rfftmf_to_send().
copy_fftpack_to_prt_field()
subroutine copy_rtp_data_to_fftpack::copy_fftpack_to_prt_field (integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) ncomp_bwd, real(kind = kreal), dimension(ncomp_bwd*nnod_rtp), intent(in) X_FFT, real(kind = kreal), dimension(nnod_rtp,ncomp_bwd), intent(inout) X_prt)
Definition at line 189 of file copy_rtp_data_to_FFTPACK.f90.
copy_fftpack_to_rtp_comp()
subroutine copy_rtp_data_to_fftpack::copy_fftpack_to_rtp_comp (integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(3), intent(in) nidx_rtp, integer(kind = kint), dimension(0:np_smp), intent(in) irt_rtp_smp_stack, real(kind = kreal), dimension(nnod_rtp), intent(in) X_FFT, real(kind = kreal), dimension(irt_rtp_smp_stack(np_smp),nidx_rtp(3)), intent(inout) X_rtp)
Definition at line 118 of file copy_rtp_data_to_FFTPACK.f90.
Referenced by sph_rtp_domain_fftpack5::rtp_domain_rfftmb_from_recv(), and sph_rtp_domain_fftw::rtp_field_back_fftw_from_recv().
copy_fftpack_to_rtp_field()
subroutine copy_rtp_data_to_fftpack::copy_fftpack_to_rtp_field (integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(3), intent(in) nidx_rtp, integer(kind = kint), dimension(0:np_smp), intent(in) irt_rtp_smp_stack, integer(kind = kint), intent(in) ncomp_bwd, real(kind = kreal), dimension(ncomp_bwd*nnod_rtp), intent(in) X_FFT, real(kind = kreal), dimension(irt_rtp_smp_stack(np_smp),nidx_rtp(3),ncomp_bwd), intent(inout) X_rtp)
Definition at line 42 of file copy_rtp_data_to_FFTPACK.f90.
Referenced by sph_rtp_fftw::rtp_back_fftw_from_recv(), and sph_rtp_fftpack5::rtp_rfftmb_from_recv().