CALYPSO: set_sph_scalar_mat_bc Module Reference
set_sph_scalar_mat_bc Module Reference
Construct matrix for scalar fields at boundaries.
Functions/Subroutines
subroutine set_fix_fld_icb_poisson_mat (nri, jmax, kr_in, evo_mat)
subroutine add_fix_flux_icb_poisson_mat (nri, jmax, g_sph_rj, kr_in, r_ICB, fdm2_fix_dr_ICB, coef_p, evo_mat)
subroutine add_icb_scalar_poisson_mat (nri, jmax, g_sph_rj, kr_in, r_ICB, fdm2_fix_dr_ICB, coef_p, p_mat)
subroutine set_fix_fld_cmb_poisson_mat (nri, jmax, kr_out, evo_mat)
subroutine add_fix_flux_cmb_poisson_mat (nri, jmax, g_sph_rj, kr_out, r_CMB, fdm2_fix_dr_CMB, coef_p, evo_mat)
subroutine add_cmb_scalar_poisson_mat (nri, jmax, g_sph_rj, kr_out, r_CMB, fdm2_fix_dr_CMB, coef_p, p_mat)
Detailed Description
Construct matrix for scalar fields at boundaries.
      subroutine set_fix_fld_icb_poisson_mat(nri, jmax, kr_in,        &
     &          evo_mat)
      subroutine add_fix_flux_icb_poisson_mat(nri, jmax, g_sph_rj,    &
     &          kr_in, r_ICB, fdm2_fix_dr_ICB, coef_p, evo_mat)
      subroutine add_icb_scalar_poisson_mat(nri, jmax, g_sph_rj,      &
     &          kr_in, r_ICB, fdm2_fix_dr_ICB, coef_p, p_mat)
      subroutine set_fix_fld_cmb_poisson_mat(nri, jmax, kr_out,       &
     &          evo_mat)
      subroutine add_fix_flux_cmb_poisson_mat(nri, jmax, g_sph_rj,    &
     &          kr_out, r_CMB, fdm2_fix_dr_CMB, coef_p, evo_mat)
      subroutine add_cmb_scalar_poisson_mat(nri, jmax, g_sph_rj,      &
     &          kr_out, r_CMB, fdm2_fix_dr_CMB, coef_p, p_mat)
Parameters
nri Number of radial points
jmax Number of spherical harmonics modes
j0 Local harmonics mode address for l = m = 0
kr_in Radial ID for inner boundary
kr_out Radial ID for outer boundary
r_ICB(0:2) Radius at ICB
r_CMB(0:2) Radius at CMB
coef_d Coefficient of diffusiotn term
fdm2_fix_dr_ICB(-1:1,3) Matrix to evaluate field at ICB with fixed radial derivative
fdm2_fix_dr_CMB(-1:1,3) Matrix to evaluate field at CMB with fixed radial derivative
Parameters
evo_mat(3,nri,jmax) Band matrix for time evolution
Function/Subroutine Documentation
add_cmb_scalar_poisson_mat()
subroutine set_sph_scalar_mat_bc::add_cmb_scalar_poisson_mat (integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_out, real(kind = kreal), dimension(0:2), intent(in) r_CMB, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_fix_dr_CMB, real(kind = kreal), intent(in) coef_p, real(kind = kreal), dimension(3,nri,jmax), intent(inout) p_mat)
Definition at line 176 of file set_sph_scalar_mat_bc.f90.
References m_constants::two.
Referenced by const_r_mat_4_scalar_sph::const_radial_mat_4_press_sph().
add_fix_flux_cmb_poisson_mat()
subroutine set_sph_scalar_mat_bc::add_fix_flux_cmb_poisson_mat (integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_out, real(kind = kreal), dimension(0:2), intent(in) r_CMB, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_fix_dr_CMB, real(kind = kreal), intent(in) coef_p, real(kind = kreal), dimension(3,nri,jmax), intent(inout) evo_mat)
Definition at line 148 of file set_sph_scalar_mat_bc.f90.
Referenced by const_r_mat_4_vector_sph::const_radial_mat_4_magne_sph(), const_r_mat_4_scalar_sph::const_radial_mat_4_scalar_sph(), and const_r_mat_4_vector_sph::const_radial_mat_vort_2step().
add_fix_flux_icb_poisson_mat()
subroutine set_sph_scalar_mat_bc::add_fix_flux_icb_poisson_mat (integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(0:2), intent(in) r_ICB, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_fix_dr_ICB, real(kind = kreal), intent(in) coef_p, real(kind = kreal), dimension(3,nri,jmax), intent(inout) evo_mat)
Definition at line 72 of file set_sph_scalar_mat_bc.f90.
Referenced by const_r_mat_4_vector_sph::const_radial_mat_4_magne_sph(), const_r_mat_4_scalar_sph::const_radial_mat_4_scalar_sph(), and const_r_mat_4_vector_sph::const_radial_mat_vort_2step().
add_icb_scalar_poisson_mat()
subroutine set_sph_scalar_mat_bc::add_icb_scalar_poisson_mat (integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(0:2), intent(in) r_ICB, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_fix_dr_ICB, real(kind = kreal), intent(in) coef_p, real(kind = kreal), dimension(3,nri,jmax), intent(inout) p_mat)
Definition at line 100 of file set_sph_scalar_mat_bc.f90.
References m_constants::two.
Referenced by const_r_mat_4_scalar_sph::const_radial_mat_4_press_sph().
set_fix_fld_cmb_poisson_mat()
subroutine set_sph_scalar_mat_bc::set_fix_fld_cmb_poisson_mat (integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, integer(kind = kint), intent(in) kr_out, real(kind = kreal), dimension(3,nri,jmax), intent(inout) evo_mat)
Definition at line 129 of file set_sph_scalar_mat_bc.f90.
References m_constants::one, and m_constants::zero.
Referenced by const_r_mat_4_vector_sph::const_radial_mat_4_magne_sph(), const_r_mat_4_scalar_sph::const_radial_mat_4_scalar_sph(), and const_r_mat_4_vector_sph::const_radial_mat_vort_2step().
set_fix_fld_icb_poisson_mat()
subroutine set_sph_scalar_mat_bc::set_fix_fld_icb_poisson_mat (integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, integer(kind = kint), intent(in) kr_in, real(kind = kreal), dimension(3,nri,jmax), intent(inout) evo_mat)
Definition at line 53 of file set_sph_scalar_mat_bc.f90.
References m_constants::one, and m_constants::zero.
Referenced by const_r_mat_4_vector_sph::const_radial_mat_4_magne_sph(), const_r_mat_4_scalar_sph::const_radial_mat_4_scalar_sph(), and const_r_mat_4_vector_sph::const_radial_mat_vort_2step().