CALYPSO: set_control_4_time_steps Module Reference
set_control_4_time_steps Module Reference
set parameters for time stepping
Functions/Subroutines
subroutine s_set_control_4_time_steps (mr_ctl, tctl, MHD_step)
subroutine, private set_control_flex_time_steps (tctl, init_d, flex_p)
subroutine, private set_fixed_time_step_controls (tctl, MHD_step)
subroutine, private set_flex_time_step_controls (tctl, MHD_step)
subroutine, private set_flex_time_step_params (tctl, flex_p, init_d, finish_d, rst_step, ucd_step)
Detailed Description
set parameters for time stepping
      subroutine s_set_control_4_time_steps(mr_ctl, tctl, MHD_step)
        type(mhd_restart_control), intent(in) :: mr_ctl
        type(time_data_control), intent(in) :: tctl
        type(MHD_step_param), intent(inout) :: MHD_step
Function/Subroutine Documentation
s_set_control_4_time_steps()
subroutine set_control_4_time_steps::s_set_control_4_time_steps (type(mhd_restart_control), intent(in) mr_ctl, type(time_data_control), intent(in) tctl, type(mhd_step_param), intent(inout) MHD_step)
Definition at line 46 of file set_control_4_time_steps.f90.
References calypso_mpi::calypso_mpi_abort(), m_machine_parameter::e_message, m_error_ids::ierr_evo, m_machine_parameter::iflag_debug, t_flex_delta_t_data::iflag_fixed_step, t_flex_delta_t_data::iflag_flex_step, m_machine_parameter::iflag_routine_msg, set_control_flex_time_steps(), set_fixed_time_step_controls(), set_flex_time_step_controls(), m_initial_field_control::set_initial_field_id(), and skip_comment_f::yes_flag().
Referenced by set_control_sph_mhd::set_control_4_sph_mhd().
set_control_flex_time_steps()
subroutine, private set_control_4_time_steps::set_control_flex_time_steps (type(time_data_control), intent(in) tctl, type(time_data), intent(in) init_d, type(flexible_stepping_parameter), intent(inout) flex_p) private
Definition at line 119 of file set_control_4_time_steps.f90.
References cal_num_digits::cal_num_digit_real(), calypso_mpi::calypso_mpi_abort(), m_machine_parameter::e_message, m_error_ids::ierr_evo, and t_flex_delta_t_data::iflag_flex_step.
Referenced by s_set_control_4_time_steps().
set_fixed_time_step_controls()
subroutine, private set_control_4_time_steps::set_fixed_time_step_controls (type(time_data_control), intent(in) tctl, type(mhd_step_param), intent(inout) MHD_step) private
Definition at line 183 of file set_control_4_time_steps.f90.
References calypso_mpi::calypso_mpi_abort(), m_machine_parameter::e_message, t_step_parameter::s_set_fixed_time_step_params(), and t_viz_step_parameter::viz_fixed_time_step_params().
Referenced by s_set_control_4_time_steps().
set_flex_time_step_controls()
subroutine, private set_control_4_time_steps::set_flex_time_step_controls (type(time_data_control), intent(in) tctl, type(mhd_step_param), intent(inout) MHD_step) private
Definition at line 218 of file set_control_4_time_steps.f90.
References set_flex_time_step_params(), and t_viz_step_parameter::viz_flex_time_step_controls().
Referenced by s_set_control_4_time_steps().
set_flex_time_step_params()
subroutine, private set_control_4_time_steps::set_flex_time_step_params (type(time_data_control), intent(in) tctl, type(flexible_stepping_parameter), intent(inout) flex_p, type(time_data), intent(inout) init_d, type(finish_data), intent(inout) finish_d, type(io_step_param), intent(inout) rst_step, type(io_step_param), intent(inout) ucd_step) private
Start step for restarting file
Definition at line 251 of file set_control_4_time_steps.f90.
References calypso_mpi::calypso_mpi_abort(), m_machine_parameter::e_message, m_error_ids::ierr_evo, m_machine_parameter::iflag_debug, and m_machine_parameter::iflag_routine_msg.
Referenced by set_flex_time_step_controls().