CALYPSO: element_connect_io_b Module Reference
element_connect_io_b Module Reference
Data IO routines for element connectivity.
Functions/Subroutines
subroutine write_element_info_b (ele_IO, bbuf)
subroutine write_surface_4_element_b (sfed_IO, bbuf)
subroutine write_edge_4_element_b (sfed_IO, bbuf)
subroutine read_number_of_element_b (bbuf, ele_IO)
subroutine read_element_info_b (bbuf, ele_IO)
subroutine read_surface_4_element_b (bbuf, sfed_IO)
subroutine read_edge_4_element_b (bbuf, sfed_IO)
Detailed Description
Data IO routines for element connectivity.
      subroutine write_element_info_b(ele_IO, bbuf)
      subroutine write_surface_4_element_b(sfed_IO, bbuf)
      subroutine write_edge_4_element_b(sfed_IO, bbuf)
        type(binary_IO_buffer), intent(inout) :: bbuf
        type(element_data), intent(in) :: ele_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
      subroutine read_number_of_element_b(bbuf, ele_IO)
      subroutine read_element_info_b(bbuf, ele_IO)
      subroutine read_surface_4_element_b(bbuf, sfed_IO)
      subroutine read_edge_4_element_b(bbuf, sfed_IO)
        type(binary_IO_buffer), intent(inout) :: bbuf
        type(element_data), intent(inout) :: ele_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
Function/Subroutine Documentation
read_edge_4_element_b()
subroutine element_connect_io_b::read_edge_4_element_b (type(binary_io_buffer), intent(inout) bbuf, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 206 of file element_connect_IO_b.f90.
References t_surf_edge_io::alloc_edge_connect_io(), binary_io::read_mul_integer_b(), and binary_io::read_one_integer_b().
Referenced by edge_data_io_b::read_edge_connection_b().
read_element_info_b()
subroutine element_connect_io_b::read_element_info_b (type(binary_io_buffer), intent(inout) bbuf, type(element_data), intent(inout) ele_IO)
Definition at line 133 of file element_connect_IO_b.f90.
References t_geometry_data::alloc_ele_connectivity(), t_geometry_data::alloc_element_types(), transfer_to_long_integers::cast_long(), binary_io::read_mul_int8_b(), binary_io::read_mul_integer_b(), and set_nnod_4_ele_by_type::s_set_nnod_4_ele_by_type().
Referenced by edge_data_io_b::read_edge_connection_b(), mesh_data_io_b::read_geometry_data_b(), and surface_data_io_b::read_surface_connection_b().
read_number_of_element_b()
subroutine element_connect_io_b::read_number_of_element_b (type(binary_io_buffer), intent(inout) bbuf, type(element_data), intent(inout) ele_IO)
Definition at line 119 of file element_connect_IO_b.f90.
References binary_io::read_one_integer_b().
Referenced by edge_data_io_b::read_edge_connection_b(), mesh_data_io_b::read_num_node_ele_b(), and surface_data_io_b::read_surface_connection_b().
read_surface_4_element_b()
subroutine element_connect_io_b::read_surface_4_element_b (type(binary_io_buffer), intent(inout) bbuf, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 178 of file element_connect_IO_b.f90.
References t_surf_edge_io::alloc_surface_connect_io(), binary_io::read_mul_integer_b(), and binary_io::read_one_integer_b().
Referenced by edge_data_io_b::read_edge_connection_b(), and surface_data_io_b::read_surface_connection_b().
write_edge_4_element_b()
subroutine element_connect_io_b::write_edge_4_element_b (type(surf_edge_io_data), intent(in) sfed_IO, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 97 of file element_connect_IO_b.f90.
References binary_io::write_mul_integer_b(), and binary_io::write_one_integer_b().
Referenced by edge_data_io_b::write_edge_connection_b().
write_element_info_b()
subroutine element_connect_io_b::write_element_info_b (type(element_data), intent(in) ele_IO, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 42 of file element_connect_IO_b.f90.
References binary_io::write_mul_int8_b(), binary_io::write_mul_integer_b(), and binary_io::write_one_integer_b().
Referenced by edge_data_io_b::write_edge_connection_b(), mesh_data_io_b::write_geometry_data_b(), and surface_data_io_b::write_surface_connection_b().
write_surface_4_element_b()
subroutine element_connect_io_b::write_surface_4_element_b (type(surf_edge_io_data), intent(in) sfed_IO, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 76 of file element_connect_IO_b.f90.
References binary_io::write_mul_integer_b(), and binary_io::write_one_integer_b().
Referenced by edge_data_io_b::write_edge_connection_b(), and surface_data_io_b::write_surface_connection_b().