CALYPSO: schmidt_poly_on_meridian Module Reference
schmidt_poly_on_meridian Module Reference
Functions/Subroutines
subroutine cal_full_legendre_on_med (nth, lst, led, leg_d)
subroutine, private copy_gauss_colatitude (gauss, leg_d)
Variables
real(kind=kreal), dimension(:), allocatable dint_p
Function/Subroutine Documentation
cal_full_legendre_on_med()
subroutine schmidt_poly_on_meridian::cal_full_legendre_on_med (integer(kind = kint), intent(in) nth, integer(kind = kint), intent(in) lst, integer(kind = kint), intent(in) led, type(gauss_legendre_data), intent(inout) leg_d)
Definition at line 25 of file schmidt_poly_on_meridian.f90.
References t_schmidt_poly_on_gauss::alloc_gauss_colat_med(), t_schmidt_poly_on_gauss::alloc_legendre_med(), t_schmidt_poly_on_gauss::alloc_schmidt_poly_med(), t_gauss_points::const_gauss_colatitude(), copy_gauss_colatitude(), t_gauss_points::dealloc_gauss_colatitude(), dint_p, t_schmidt_polynomial::dlad(), t_spherical_harmonics::finalize_sph_indices(), t_schmidt_polynomial::full_norm_legendre(), and t_spherical_harmonics::init_sph_indices().
Referenced by test_schmidt_poly_med().
copy_gauss_colatitude()
subroutine, private schmidt_poly_on_meridian::copy_gauss_colatitude (type(gauss_points), intent(in) gauss, type(gauss_legendre_data), intent(inout) leg_d) private
Definition at line 99 of file schmidt_poly_on_meridian.f90.
Referenced by cal_full_legendre_on_med().
Variable Documentation
dint_p
real(kind = kreal), dimension(:), allocatable schmidt_poly_on_meridian::dint_p
Definition at line 15 of file schmidt_poly_on_meridian.f90.
Referenced by cal_full_legendre_on_med().