CALYPSO: const_r_mat_w_center_sph Module Reference
const_r_mat_w_center_sph Module Reference
Construct matrix for time evolution of scalar fields.
Functions/Subroutines
subroutine const_radial_mat_press00_sph (mat_name, sph_rj, fl_prop, sph_bc_U, fdm2_center, band_p_poisson, band_p00_poisson)
subroutine const_radial_mat_scalar00_sph (mat_name, dt, sph_rj, prop, sph_bc, fdm2_center, evo_mat, band_s00_evo)
subroutine, private const_rmat_press00_sph (sph_rj, sph_bc_U, fdm2_center, fl_prop, n_vect, n_comp, p_poisson_mat, band_p00_poisson)
subroutine, private const_rmat_scalar00_sph (sph_rj, sph_bc, fdm2_center, dt, coef_imp, coef_f, coef_d, n_vect, n_comp, evo_mat, band_s00_evo)
Detailed Description
Construct matrix for time evolution of scalar fields.
      subroutine const_radial_mat_press00_sph                         &
     &         (mat_name, sph_rj, fl_prop, sph_bc_U, fdm2_center,     &
     &          band_p_poisson, band_p00_poisson)
        type(fluid_property), intent(in) :: fl_prop
        type(sph_boundary_type), intent(in) :: sph_bc_U
        type(sph_rj_grid), intent(in) :: sph_rj
        type(fdm2_center_mat), intent(in) :: fdm2_center
        type(band_matrices_type), intent(in) :: band_p_poisson
        type(band_matrix_type), intent(inout) :: band_p00_poisson
      subroutine const_radial_mat_scalar00_sph(mat_name, sph_rj,      &
     &          prop, sph_bc, fdm2_center, evo_mat, band_s00_evo)
        type(scalar_property), intent(in) :: prop
        type(sph_boundary_type), intent(in) :: sph_bc
        type(fdm2_center_mat), intent(in) :: fdm2_center
        type(sph_rj_grid), intent(in) :: sph_rj
        type(band_matrices_type), save :: evo_mat
        type(band_matrix_type), intent(inout) :: band_s00_evo
Function/Subroutine Documentation
const_radial_mat_press00_sph()
subroutine const_r_mat_w_center_sph::const_radial_mat_press00_sph (character(len=kchara), intent(in) mat_name, type(sph_rj_grid), intent(in) sph_rj, type(fluid_property), intent(in) fl_prop, type(sph_boundary_type), intent(in) sph_bc_U, type(fdm2_center_mat), intent(in) fdm2_center, type(band_matrices_type), intent(in) band_p_poisson, type(band_matrix_type), intent(inout) band_p00_poisson)
Definition at line 53 of file const_r_mat_w_center_sph.f90.
References const_rmat_press00_sph(), m_machine_parameter::i_debug, and t_physical_property::id_crank_nicolson.
Referenced by const_radial_mat_4_sph::const_radial_mat_sph_snap(), and const_radial_mat_4_sph::const_radial_mat_sph_w_center().
const_radial_mat_scalar00_sph()
subroutine const_r_mat_w_center_sph::const_radial_mat_scalar00_sph (character(len=kchara), intent(in) mat_name, real(kind = kreal), intent(in) dt, type(sph_rj_grid), intent(in) sph_rj, type(scalar_property), intent(in) prop, type(sph_boundary_type), intent(in) sph_bc, type(fdm2_center_mat), intent(in) fdm2_center, type(band_matrices_type), intent(in) evo_mat, type(band_matrix_type), intent(inout) band_s00_evo)
Definition at line 84 of file const_r_mat_w_center_sph.f90.
References const_rmat_scalar00_sph(), m_machine_parameter::i_debug, and t_physical_property::id_crank_nicolson.
Referenced by const_radial_mat_4_sph::const_radial_mat_sph_w_center().
const_rmat_press00_sph()
subroutine, private const_r_mat_w_center_sph::const_rmat_press00_sph (type(sph_rj_grid), intent(in) sph_rj, type(sph_boundary_type), intent(in) sph_bc_U, type(fdm2_center_mat), intent(in) fdm2_center, type(fluid_property), intent(in) fl_prop, integer(kind= kint), intent(in) n_vect, integer(kind= kint), intent(in) n_comp, real(kind = kreal), dimension(3,n_vect,n_comp), intent(in) p_poisson_mat, type(band_matrix_type), intent(inout) band_p00_poisson) private
Definition at line 112 of file const_r_mat_w_center_sph.f90.
References center_sph_matrices::add_scalar_poisson_mat_fill_ctr(), center_sph_matrices::add_scalar_poisson_mat_no_fld(), t_sph_center_matrix::alloc_ctr_band_mat(), t_sph_center_matrix::check_center_band_matrix(), center_sph_matrices::copy_to_band3_mat_w_center(), m_machine_parameter::i_debug, m_machine_parameter::iflag_full_msg, t_boundary_params_sph_mhd::iflag_sph_fill_center, m_constants::ithree, t_sph_center_matrix::ludcmp_3band_ctr(), calypso_mpi::my_rank, and m_constants::zero.
Referenced by const_radial_mat_press00_sph().
const_rmat_scalar00_sph()
subroutine, private const_r_mat_w_center_sph::const_rmat_scalar00_sph (type(sph_rj_grid), intent(in) sph_rj, type(sph_boundary_type), intent(in) sph_bc, type(fdm2_center_mat), intent(in) fdm2_center, real(kind = kreal), intent(in) dt, real(kind = kreal) coef_imp, real(kind = kreal) coef_f, real(kind = kreal) coef_d, integer(kind= kint), intent(in) n_vect, integer(kind= kint), intent(in) n_comp, real(kind = kreal), dimension(3,n_vect,n_comp), intent(in) evo_mat, type(band_matrix_type), intent(inout) band_s00_evo) private
Definition at line 163 of file const_r_mat_w_center_sph.f90.
References center_sph_matrices::add_scalar_poisson_mat_fill_ctr(), center_sph_matrices::add_scalar_poisson_mat_fix_ctr(), center_sph_matrices::add_scalar_poisson_mat_no_fld(), t_sph_center_matrix::alloc_ctr_band_mat(), t_sph_center_matrix::check_center_band_matrix(), center_sph_matrices::copy_to_band3_mat_w_center(), m_machine_parameter::i_debug, m_machine_parameter::iflag_full_msg, t_boundary_params_sph_mhd::iflag_sph_fill_center, t_boundary_params_sph_mhd::iflag_sph_fix_center, m_constants::ithree, t_sph_center_matrix::ludcmp_3band_ctr(), calypso_mpi::my_rank, m_constants::one, t_sph_center_matrix::set_unit_ctr_single_mat(), and m_constants::zero.
Referenced by const_radial_mat_scalar00_sph().