CALYPSO: const_sph_initial_spectr Module Reference
const_sph_initial_spectr Module Reference
Set initial data for spectrum dynamos.
Functions/Subroutines
subroutine sph_initial_spectrum (fst_file_IO, sph_MHD_bc, SPH_MHD, rst_step, sph_fst_IO)
subroutine, private set_initial_velocity (sph_bc_U, sph, ipol, rj_fld)
subroutine, private set_initial_temperature (sph_bc_T, bcs_T, sph, ipol, rj_fld)
subroutine, private set_initial_composition (sph_bc_C, bcs_C, sph, ipol, rj_fld)
subroutine, private set_initial_magne_sph (sph_bc_B, sph, ipol, rj_fld)
subroutine, private set_initial_heat_source_sph (sph_bc_T, bcs_T, sph, ipol, rj_fld)
subroutine, private set_initial_light_source_sph (sph_bc_C, bcs_C, sph, ipol, rj_fld)
subroutine adjust_by_cmb_temp (sph_bc_T, sph, ipol, rj_fld)
subroutine, private add_outer_core_heat_source (sph_bc_T, bcs_T, sph, ipol, rj_fld)
subroutine, private add_inner_core_heat_source (sph_bc_T, bcs_T, sph, ipol, rj_fld)
subroutine, private add_whole_core_heat_source (sph_bc_T, bcs_T, sph, ipol, rj_fld)
integer function, private find_local_sph_mode_address (sph, l, m)
integer(kind=kint) function, private local_sph_data_address (sph, kr, j_lc)
real(kind=kreal) function, private radius_1d_rj_r (sph, kr)
real function r_cmb (sph)
real function, private r_icb (sph)
integer function, private nlayer_cmb (sph)
integer function, private nlayer_icb (sph)
integer(kind=kint) function, private inod_rj_center (sph)
integer(kind=kint) function, private nidx_rj (sph, nd)
integer(kind=kint) function, private nnod_rj (sph)
Detailed Description
Set initial data for spectrum dynamos.
      subroutine sph_initial_spectrum                                 &
     &        (fst_file_IO, sph_MHD_bc, SPH_MHD, rst_step, sph_fst_IO)
        type(sph_grids), intent(in) :: sph
        type(field_IO_params), intent(in) :: fst_file_IO
        type(sph_MHD_boundary_data), intent(in) :: sph_MHD_bc
        type(phys_data), intent(inout) :: rj_fld
        type(IO_step_param), intent(inout) :: rst_step
        type(field_IO), intent(inout) :: sph_fst_IO
       Sample program to generate initial field
       This program generates initial condition
        for dynamo benchmark case 1
       Temperature :: d_rj(:,ipol%base%i_temp)
       Composition :: d_rj(:,ipol%base%i_light)
       Poloidal velocity ::       d_rj(:,ipol%base%i_velo  )
       Toroidal velocity ::       d_rj(:,ipol%base%i_velo+2)
       Poloidal magnetic field :: d_rj(:,ipol%base%i_magne  )
       Toroidal magnetic field :: d_rj(:,ipol%base%i_magne+2)
       Heat source ::          d_rj(:,ipol%base%i_heat_source)
       Light element source :: d_rj(:,ipol%base%i_light_source)
       sph_bc_*%kr_in :: radial ID for inner boundary of each evolution
       sph_bc_*%kr_out :: radial ID for outer boundary
       sph_bc_*%r_ICB(0) :: radius for inner boundary of each evolution
       sph_bc_*%r_CMB(0) :: radius for outer boundary
      subroutine adjust_by_CMB_temp(sph_bc_T, sph, ipol, rj_fld)
      subroutine add_outer_core_heat_source                           &
     &         (sph_bc_T, bcs_T, sph, ipol, rj_fld)
       Set homogenious heat source at outer core
       by CMB and ICB heat flux
      subroutine add_inner_core_heat_source                           &
     &         (sph_bc_T, bcs_T, sph, ipol, rj_fld)
       Set homogenious heat source and temperature at inner core
       by CMB heat flux
         f_CMB = (dT/dr)_CMB
         f_ICB = -(dT/dr)_ICB
               = - f_CMB * (r_CMB / r_ICB)**2
             Q = - 3.0 * f_ICB / r_ICB
          T(r) = T_ICB + 0.5 * (f_ICB / r_ICB) * (r_ICB**2 - r**2)
      subroutine add_whole_core_heat_source                           &
     &         (sph_bc_T, bcs_T, sph, ipol, rj_fld)
       Set homogenious heat source for whole core
       and temperature at inner core by CMB heat flux
         f_CMB = (dT/dr)_CMB
             Q = - 3.0 * f_CMB / r_CMB
         f_ICB = -(dT/dr)_ICB
               = - f_CMB * (r_ICB / r_CMB)
          T(r) = T_ICB + 0.5 * (f_ICB / r_ICB) * (r_ICB**2 - r**2)
   Function to obtain local addresses from global mode information
     Informations are stored in structure 'sph'
      j_lc = find_local_sph_mode_address(sph, l, m) ::
         Return local spherical harmonics mode address j_lc for Y(l,m)
         If requested mode does not exist in the process, 0 is set
     inod = local_sph_data_address(sph, k, j_lc) ::
         Return address of sphectrum data
     radius_1d_rj_r(sph, k) :: Radius at global grid address k
     nlayer_ICB(sph) :: radial ID for ICB
     nlayer_CMB(sph) :: radial ID for CMB
     r_ICB(sph) :: ICB radius in grid data
     r_CMB(sph) :: CMB radius in grid data
     inod_rj_center(sph) :: Local data ID for center data
         If spectrum data does not have center
              inod_rj_center(sph) = 0
     nidx_rj(sph,1) :: Number of radial grids
     nidx_rj(sph,2) :: Number of modes in each process
     nnod_rj(sph) :: Number of local data points
Function/Subroutine Documentation
add_inner_core_heat_source()
subroutine, private const_sph_initial_spectr::add_inner_core_heat_source (type(sph_boundary_type), intent(in) sph_bc_T, type(sph_scalar_boundary_data), intent(in) bcs_T, type(sph_grids), intent(in) sph, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld) private
Definition at line 687 of file const_sph_initial_spectr.f90.
References find_local_sph_mode_address(), m_constants::half, inod_rj_center(), m_constants::izero, local_sph_data_address(), nlayer_icb(), nnod_rj(), r_icb(), radius_1d_rj_r(), m_constants::three, and m_constants::zero.
add_outer_core_heat_source()
subroutine, private const_sph_initial_spectr::add_outer_core_heat_source (type(sph_boundary_type), intent(in) sph_bc_T, type(sph_scalar_boundary_data), intent(in) bcs_T, type(sph_grids), intent(in) sph, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld) private
Definition at line 643 of file const_sph_initial_spectr.f90.
References find_local_sph_mode_address(), m_constants::izero, local_sph_data_address(), nnod_rj(), radius_1d_rj_r(), m_constants::three, and m_constants::zero.
add_whole_core_heat_source()
subroutine, private const_sph_initial_spectr::add_whole_core_heat_source (type(sph_boundary_type), intent(in) sph_bc_T, type(sph_scalar_boundary_data), intent(in) bcs_T, type(sph_grids), intent(in) sph, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld) private
Definition at line 744 of file const_sph_initial_spectr.f90.
References find_local_sph_mode_address(), m_constants::half, inod_rj_center(), m_constants::izero, local_sph_data_address(), nlayer_icb(), nnod_rj(), r_icb(), radius_1d_rj_r(), m_constants::three, and m_constants::zero.
adjust_by_cmb_temp()
subroutine const_sph_initial_spectr::adjust_by_cmb_temp (type(sph_boundary_type), intent(in) sph_bc_T, type(sph_grids), intent(in) sph, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld)
Definition at line 600 of file const_sph_initial_spectr.f90.
References find_local_sph_mode_address(), inod_rj_center(), m_constants::izero, local_sph_data_address(), and nidx_rj().
find_local_sph_mode_address()
integer function, private const_sph_initial_spectr::find_local_sph_mode_address (type(sph_grids), intent(in) sph, integer, intent(in) l, integer, intent(in) m) private
Definition at line 812 of file const_sph_initial_spectr.f90.
Referenced by add_inner_core_heat_source(), add_outer_core_heat_source(), add_whole_core_heat_source(), adjust_by_cmb_temp(), set_initial_composition(), set_initial_heat_source_sph(), set_initial_light_source_sph(), set_initial_magne_sph(), and set_initial_temperature().
inod_rj_center()
integer(kind = kint) function, private const_sph_initial_spectr::inod_rj_center (type(sph_grids), intent(in) sph) private
Definition at line 890 of file const_sph_initial_spectr.f90.
Referenced by add_inner_core_heat_source(), add_whole_core_heat_source(), adjust_by_cmb_temp(), set_initial_composition(), set_initial_heat_source_sph(), set_initial_light_source_sph(), and set_initial_temperature().
local_sph_data_address()
integer(kind = kint) function, private const_sph_initial_spectr::local_sph_data_address (type(sph_grids), intent(in) sph, integer kr, integer j_lc) private
Definition at line 825 of file const_sph_initial_spectr.f90.
Referenced by add_inner_core_heat_source(), add_outer_core_heat_source(), add_whole_core_heat_source(), adjust_by_cmb_temp(), set_initial_composition(), set_initial_heat_source_sph(), set_initial_light_source_sph(), set_initial_magne_sph(), and set_initial_temperature().
nidx_rj()
integer(kind = kint) function, private const_sph_initial_spectr::nidx_rj (type(sph_grids), intent(in) sph, integer, intent(in) nd) private
Definition at line 900 of file const_sph_initial_spectr.f90.
Referenced by adjust_by_cmb_temp(), and set_initial_magne_sph().
nlayer_cmb()
integer function, private const_sph_initial_spectr::nlayer_cmb (type(sph_grids), intent(in) sph) private
Definition at line 870 of file const_sph_initial_spectr.f90.
nlayer_icb()
integer function, private const_sph_initial_spectr::nlayer_icb (type(sph_grids), intent(in) sph) private
Definition at line 880 of file const_sph_initial_spectr.f90.
Referenced by add_inner_core_heat_source(), and add_whole_core_heat_source().
nnod_rj()
integer(kind = kint) function, private const_sph_initial_spectr::nnod_rj (type(sph_grids), intent(in) sph) private
Definition at line 911 of file const_sph_initial_spectr.f90.
Referenced by add_inner_core_heat_source(), add_outer_core_heat_source(), add_whole_core_heat_source(), set_initial_composition(), set_initial_heat_source_sph(), set_initial_light_source_sph(), set_initial_magne_sph(), set_initial_temperature(), and set_initial_velocity().
r_cmb()
real function const_sph_initial_spectr::r_cmb (type(sph_grids), intent(in) sph)
Definition at line 850 of file const_sph_initial_spectr.f90.
r_icb()
real function, private const_sph_initial_spectr::r_icb (type(sph_grids), intent(in) sph) private
Definition at line 860 of file const_sph_initial_spectr.f90.
Referenced by add_inner_core_heat_source(), and add_whole_core_heat_source().
radius_1d_rj_r()
real(kind = kreal) function, private const_sph_initial_spectr::radius_1d_rj_r (type(sph_grids), intent(in) sph, integer, intent(in) kr) private
Definition at line 839 of file const_sph_initial_spectr.f90.
Referenced by add_inner_core_heat_source(), add_outer_core_heat_source(), add_whole_core_heat_source(), set_initial_composition(), set_initial_heat_source_sph(), set_initial_magne_sph(), and set_initial_temperature().
set_initial_composition()
subroutine, private const_sph_initial_spectr::set_initial_composition (type(sph_boundary_type), intent(in) sph_bc_C, type(sph_scalar_boundary_data), intent(in) bcs_C, type(sph_grids), intent(in) sph, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld) private
Definition at line 337 of file const_sph_initial_spectr.f90.
References find_local_sph_mode_address(), m_constants::four, inod_rj_center(), m_constants::izero, local_sph_data_address(), nnod_rj(), m_constants::one, radius_1d_rj_r(), m_constants::three, m_constants::two, and m_constants::zero.
Referenced by sph_initial_spectrum().
set_initial_heat_source_sph()
subroutine, private const_sph_initial_spectr::set_initial_heat_source_sph (type(sph_boundary_type), intent(in) sph_bc_T, type(sph_scalar_boundary_data), intent(in) bcs_T, type(sph_grids), intent(in) sph, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld) private
Definition at line 502 of file const_sph_initial_spectr.f90.
References find_local_sph_mode_address(), inod_rj_center(), m_constants::izero, local_sph_data_address(), nnod_rj(), radius_1d_rj_r(), m_constants::three, and m_constants::zero.
Referenced by sph_initial_spectrum().
set_initial_light_source_sph()
subroutine, private const_sph_initial_spectr::set_initial_light_source_sph (type(sph_boundary_type), intent(in) sph_bc_C, type(sph_scalar_boundary_data), intent(in) bcs_C, type(sph_grids), intent(in) sph, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld) private
Definition at line 550 of file const_sph_initial_spectr.f90.
References find_local_sph_mode_address(), inod_rj_center(), m_constants::izero, local_sph_data_address(), nnod_rj(), and m_constants::zero.
Referenced by sph_initial_spectrum().
set_initial_magne_sph()
subroutine, private const_sph_initial_spectr::set_initial_magne_sph (type(sph_boundary_type), intent(in) sph_bc_B, type(sph_grids), intent(in) sph, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld) private
Definition at line 409 of file const_sph_initial_spectr.f90.
References find_local_sph_mode_address(), m_constants::four, m_constants::ione, m_constants::izero, local_sph_data_address(), nidx_rj(), nnod_rj(), m_constants::one, radius_1d_rj_r(), and m_constants::zero.
Referenced by sph_initial_spectrum().
set_initial_temperature()
subroutine, private const_sph_initial_spectr::set_initial_temperature (type(sph_boundary_type), intent(in) sph_bc_T, type(sph_scalar_boundary_data), intent(in) bcs_T, type(sph_grids), intent(in) sph, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld) private
Definition at line 257 of file const_sph_initial_spectr.f90.
References find_local_sph_mode_address(), m_constants::four, inod_rj_center(), m_constants::izero, local_sph_data_address(), nnod_rj(), m_constants::one, radius_1d_rj_r(), m_constants::three, m_constants::two, and m_constants::zero.
Referenced by sph_initial_spectrum().
set_initial_velocity()
subroutine, private const_sph_initial_spectr::set_initial_velocity (type(sph_boundary_type), intent(in) sph_bc_U, type(sph_grids), intent(in) sph, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld) private
Definition at line 201 of file const_sph_initial_spectr.f90.
References m_constants::four, m_constants::izero, nnod_rj(), m_constants::one, and m_constants::zero.
Referenced by sph_initial_spectrum().
sph_initial_spectrum()
subroutine const_sph_initial_spectr::sph_initial_spectrum (type(field_io_params), intent(in) fst_file_IO, type(sph_mhd_boundary_data), intent(in) sph_MHD_bc, type(sph_mesh_field_data), intent(inout) SPH_MHD, type(io_step_param), intent(inout) rst_step, type(field_io), intent(inout) sph_fst_IO)
Definition at line 128 of file const_sph_initial_spectr.f90.
References m_mhd_step_parameter::mhd_step1, sph_mhd_rst_io_control::output_sph_restart_control(), set_initial_composition(), set_initial_heat_source_sph(), set_initial_light_source_sph(), set_initial_magne_sph(), set_initial_temperature(), set_initial_velocity(), and set_sph_restart_io::set_sph_restart_num_to_io().
Referenced by sph_analyzer_add_initial::sph_add_initial_field(), and sph_analyzer_const_initial::sph_const_initial_field().