CALYPSO: skip_gz_comment Module Reference
skip_gz_comment Module Reference
Functions/Subroutines
integer function length_of_c_text (text)
subroutine open_wt_gzfile_a (gzip_name, zbuf)
subroutine open_ad_gzfile_a (gzip_name, zbuf)
subroutine open_rd_gzfile_a (gzip_name, zbuf)
subroutine close_gzfile_a (zbuf)
subroutine skip_gz_comment_int (int_input, zbuf)
subroutine skip_gz_comment_int2 (int_input, int_input2, zbuf)
subroutine skip_gz_comment_int8_int (i8_input, int_input2, zbuf)
subroutine skip_gz_comment_real (real_input, zbuf)
subroutine skip_gz_comment_real2 (real_input, real_input2, zbuf)
subroutine skip_gz_comment_chara (chara_input, zbuf)
subroutine skip_gz_comment_chara_int (chara_input, int_input, zbuf)
subroutine skip_gz_comment_chara_lint (chara_input, int8_input, zbuf)
subroutine skip_gz_comment_get_nword (zbuf)
Function/Subroutine Documentation
close_gzfile_a()
subroutine skip_gz_comment::close_gzfile_a (type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 111 of file skip_gz_comment.f90.
References gzip_file_access::close_gzfile_b(), and t_buffer_4_gzip::dealloc_fixbuffer_for_zlib().
Referenced by gz_element_file_io::gz_input_edge_file(), gz_element_file_io::gz_input_element_file(), gz_element_file_io::gz_input_surface_file(), gz_element_file_io::gz_output_edge_file(), gz_element_file_io::gz_output_element_file(), gz_element_file_io::gz_output_surface_file(), gz_ucd_field_file_io::gz_read_alloc_ucd_2_ld_file(), gz_sph_modes_grids_file_io::gz_read_geom_rtm_file(), gz_sph_modes_grids_file_io::gz_read_geom_rtp_file(), gz_mesh_file_io::gz_read_geometry_size(), gz_mesh_file_io::gz_read_mesh(), gz_mesh_file_io::gz_read_mesh_geometry(), gz_sph_modes_grids_file_io::gz_read_modes_rlm_file(), gz_mesh_file_io::gz_read_node_size(), gz_sph_modes_grids_file_io::gz_read_spectr_modes_rj_file(), gz_ucd_field_file_io::gz_read_ucd_2_fld_file(), gz_sph_modes_grids_file_io::gz_write_geom_rtm_file(), gz_sph_modes_grids_file_io::gz_write_geom_rtp_file(), gz_mesh_file_io::gz_write_mesh_file(), gz_sph_modes_grids_file_io::gz_write_modes_rlm_file(), gz_sph_modes_grids_file_io::gz_write_spectr_modes_rj_file(), gz_ucd_field_file_io::gz_write_ucd_2_fld_file(), gz_field_file_io::read_alloc_gz_field_file(), gz_field_file_io::read_alloc_gz_step_field_file(), gz_field_file_io::read_alloc_gz_step_field_head(), gz_udt_file_io::read_alloc_gz_ucd_file(), gz_udt_file_io::read_alloc_gz_ucd_grd(), gz_udt_file_io::read_alloc_gz_udt_file(), gz_udt_file_io::read_alloc_gz_udt_params(), gz_vtk_file_io::read_alloc_gz_vtk_file(), gz_vtk_file_io::read_alloc_gz_vtk_grid(), gz_vtk_file_io::read_alloc_gz_vtk_phys(), gz_rst_data_io_by_fld::read_gz_rst_comps(), gz_rst_data_io_by_fld::read_gz_rst_file(), gz_field_file_io::read_gz_step_field_file(), gz_udt_file_io::read_gz_ucd_file(), gz_udt_file_io::read_gz_ucd_grd(), gz_udt_file_io::read_gz_udt_file(), gz_vtk_file_io::read_gz_vtk_file(), gz_vtk_file_io::read_gz_vtk_grid(), gz_vtk_file_io::read_gz_vtk_phys(), gz_udt_file_io::write_gz_grd_file(), gz_vtk_file_io::write_gz_parallel_vtk_file(), gz_field_file_io::write_gz_step_field_file(), gz_udt_file_io::write_gz_ucd_file(), gz_udt_file_io::write_gz_udt_file(), gz_vtk_file_io::write_gz_vtk_file(), gz_vtk_file_io::write_gz_vtk_grid(), and gz_vtk_file_io::write_gz_vtk_phys().
length_of_c_text()
integer function skip_gz_comment::length_of_c_text (character(len=*), intent(in) text)
Definition at line 50 of file skip_gz_comment.f90.
open_ad_gzfile_a()
subroutine skip_gz_comment::open_ad_gzfile_a (character(len = kchara), intent(in) gzip_name, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 81 of file skip_gz_comment.f90.
References t_buffer_4_gzip::alloc_fixbuffer_for_zlib(), and gzip_file_access::open_ad_gzfile_f().
open_rd_gzfile_a()
subroutine skip_gz_comment::open_rd_gzfile_a (character(len = kchara), intent(in) gzip_name, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 96 of file skip_gz_comment.f90.
References t_buffer_4_gzip::alloc_fixbuffer_for_zlib(), and gzip_file_access::open_rd_gzfile_f().
Referenced by gz_element_file_io::gz_input_edge_file(), gz_element_file_io::gz_input_element_file(), gz_element_file_io::gz_input_surface_file(), gz_ucd_field_file_io::gz_read_alloc_ucd_2_ld_file(), gz_sph_modes_grids_file_io::gz_read_geom_rtm_file(), gz_sph_modes_grids_file_io::gz_read_geom_rtp_file(), gz_mesh_file_io::gz_read_geometry_size(), gz_mesh_file_io::gz_read_mesh(), gz_mesh_file_io::gz_read_mesh_geometry(), gz_sph_modes_grids_file_io::gz_read_modes_rlm_file(), gz_mesh_file_io::gz_read_node_size(), gz_sph_modes_grids_file_io::gz_read_spectr_modes_rj_file(), gz_ucd_field_file_io::gz_read_ucd_2_fld_file(), gz_field_file_io::read_alloc_gz_field_file(), gz_field_file_io::read_alloc_gz_step_field_file(), gz_field_file_io::read_alloc_gz_step_field_head(), gz_udt_file_io::read_alloc_gz_ucd_file(), gz_udt_file_io::read_alloc_gz_ucd_grd(), gz_udt_file_io::read_alloc_gz_udt_file(), gz_udt_file_io::read_alloc_gz_udt_params(), gz_vtk_file_io::read_alloc_gz_vtk_file(), gz_vtk_file_io::read_alloc_gz_vtk_grid(), gz_vtk_file_io::read_alloc_gz_vtk_phys(), gz_rst_data_io_by_fld::read_gz_rst_comps(), gz_rst_data_io_by_fld::read_gz_rst_file(), gz_field_file_io::read_gz_step_field_file(), gz_udt_file_io::read_gz_ucd_file(), gz_udt_file_io::read_gz_ucd_grd(), gz_udt_file_io::read_gz_udt_file(), gz_vtk_file_io::read_gz_vtk_file(), gz_vtk_file_io::read_gz_vtk_grid(), and gz_vtk_file_io::read_gz_vtk_phys().
open_wt_gzfile_a()
subroutine skip_gz_comment::open_wt_gzfile_a (character(len = kchara), intent(in) gzip_name, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 66 of file skip_gz_comment.f90.
References t_buffer_4_gzip::alloc_fixbuffer_for_zlib(), and gzip_file_access::open_wt_gzfile_f().
Referenced by gz_element_file_io::gz_output_edge_file(), gz_element_file_io::gz_output_element_file(), gz_element_file_io::gz_output_surface_file(), gz_sph_modes_grids_file_io::gz_write_geom_rtm_file(), gz_sph_modes_grids_file_io::gz_write_geom_rtp_file(), gz_mesh_file_io::gz_write_mesh_file(), gz_sph_modes_grids_file_io::gz_write_modes_rlm_file(), gz_sph_modes_grids_file_io::gz_write_spectr_modes_rj_file(), gz_ucd_field_file_io::gz_write_ucd_2_fld_file(), gz_udt_file_io::write_gz_grd_file(), gz_vtk_file_io::write_gz_parallel_vtk_file(), gz_field_file_io::write_gz_step_field_file(), gz_udt_file_io::write_gz_ucd_file(), gz_udt_file_io::write_gz_udt_file(), gz_vtk_file_io::write_gz_vtk_file(), gz_vtk_file_io::write_gz_vtk_grid(), and gz_vtk_file_io::write_gz_vtk_phys().
skip_gz_comment_chara()
subroutine skip_gz_comment::skip_gz_comment_chara (character(len = kchara), intent(inout) chara_input, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 189 of file skip_gz_comment.f90.
References m_precision::kchara, and skip_gz_comment_get_nword().
Referenced by gz_group_data_io::read_group_data_gz(), gz_field_data_io::read_gz_field_data(), gz_field_data_io::read_gz_field_name(), gz_rst_data_io_by_fld::read_gz_rst_field_comps(), gz_field_data_io::read_gz_step_data(), gz_vtk_data_io::read_gz_vtk_node_head(), and gz_group_data_io::read_surface_group_data_gz().
skip_gz_comment_chara_int()
subroutine skip_gz_comment::skip_gz_comment_chara_int (character(len = kchara), intent(inout) chara_input, integer(kind = kint), intent(inout) int_input, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 210 of file skip_gz_comment.f90.
References skip_gz_comment_get_nword().
skip_gz_comment_chara_lint()
subroutine skip_gz_comment::skip_gz_comment_chara_lint (character(len = kchara), intent(inout) chara_input, integer(kind = kint_gl), intent(inout) int8_input, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 225 of file skip_gz_comment.f90.
References skip_gz_comment_get_nword().
Referenced by gz_vtk_data_io::read_gz_vtk_fields_head().
skip_gz_comment_get_nword()
subroutine skip_gz_comment::skip_gz_comment_get_nword (type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 241 of file skip_gz_comment.f90.
References gzip_file_access::get_one_line_text_from_gz().
Referenced by gz_data_io::read_gz_multi_int(), gz_data_io::read_gz_multi_int8(), gz_data_io::read_gz_multi_real(), gz_data_io::read_gz_surf_group(), skip_gz_comment_chara(), skip_gz_comment_chara_int(), skip_gz_comment_chara_lint(), skip_gz_comment_int(), skip_gz_comment_int2(), skip_gz_comment_int8_int(), skip_gz_comment_real(), and skip_gz_comment_real2().
skip_gz_comment_int()
subroutine skip_gz_comment::skip_gz_comment_int (integer(kind = kint), intent(inout) int_input, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 125 of file skip_gz_comment.f90.
References skip_gz_comment_get_nword().
Referenced by gz_domain_data_io::gz_read_domain_info(), gz_element_connect_io::gz_read_edge_4_element(), gz_element_connect_io::gz_read_number_of_element(), gz_node_geometry_io::gz_read_number_of_node(), gz_node_geometry_io::gz_read_scalar_in_element(), gz_element_connect_io::gz_read_surface_4_element(), gz_node_geometry_io::gz_read_vector_in_element(), gz_spherical_model_io::read_gl_nodes_sph_gz(), gz_spherical_model_io::read_gl_resolution_sph_gz(), gz_group_data_io::read_group_data_gz(), gz_rst_data_io_by_fld::read_gz_rst_comps(), gz_rst_data_io_by_fld::read_gz_rst_file(), gz_field_data_io::read_gz_step_data(), gz_spherical_model_io::read_rank_4_sph_gz(), gz_sph_global_1d_idx_io::read_rj_gl_1d_table_gz(), gz_sph_global_1d_idx_io::read_rtp_gl_1d_table_gz(), gz_domain_data_io::read_send_recv_item_gz(), and gz_group_data_io::read_surface_group_data_gz().
skip_gz_comment_int2()
subroutine skip_gz_comment::skip_gz_comment_int2 (integer(kind = kint), intent(inout) int_input, integer(kind = kint), intent(inout) int_input2, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 138 of file skip_gz_comment.f90.
References skip_gz_comment_get_nword().
Referenced by gz_field_file_io::read_alloc_gz_field_file(), gz_field_file_io::read_alloc_gz_step_field_file(), gz_field_file_io::read_alloc_gz_step_field_head(), and gz_field_file_io::read_gz_step_field_file().
skip_gz_comment_int8_int()
subroutine skip_gz_comment::skip_gz_comment_int8_int (integer(kind = kint_gl), intent(inout) i8_input, integer(kind = kint), intent(inout) int_input2, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 151 of file skip_gz_comment.f90.
References skip_gz_comment_get_nword().
Referenced by gz_ucd_field_file_io::gz_read_alloc_ucd_2_ld_file(), and gz_ucd_field_file_io::gz_read_ucd_2_fld_file().
skip_gz_comment_real()
subroutine skip_gz_comment::skip_gz_comment_real (real(kind = kreal), intent(inout) real_input, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 165 of file skip_gz_comment.f90.
References skip_gz_comment_get_nword().
skip_gz_comment_real2()
subroutine skip_gz_comment::skip_gz_comment_real2 (real(kind = kreal), intent(inout) real_input, real(kind = kreal), intent(inout) real_input2, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 177 of file skip_gz_comment.f90.
References skip_gz_comment_get_nword().