CALYPSO: bcast_control_arrays Module Reference
bcast_control_arrays Module Reference
Subroutines to read control arrays.
Functions/Subroutines
subroutine bcast_ctl_type_r1 (real_item)
subroutine bcast_ctl_type_i1 (int_item)
subroutine bcast_ctl_type_c1 (chara_item)
subroutine bcast_ctl_type_r2 (real2_item)
subroutine bcast_ctl_type_r3 (real3_item)
subroutine bcast_ctl_type_i2 (int2_item)
subroutine bcast_ctl_type_i3 (int3_item)
subroutine bcast_ctl_type_c3 (chara3_item)
subroutine bcast_ctl_type_c_i3 (ci3_item)
subroutine bcast_ctl_array_r1 (array_real)
subroutine bcast_ctl_array_r2 (array_r2)
subroutine bcast_ctl_array_r3 (array_r3)
subroutine bcast_ctl_array_i1 (array_int)
subroutine bcast_ctl_array_i2 (array_i2)
subroutine bcast_ctl_array_i3 (array_i3)
subroutine bcast_ctl_array_c1 (array_chara)
subroutine bcast_ctl_array_c2 (array_c2)
subroutine bcast_ctl_array_c3 (array_c3)
subroutine bcast_ctl_array_cr (array_cr)
subroutine bcast_ctl_array_ci (array_ci)
subroutine bcast_ctl_array_cr2 (array_cr2)
subroutine bcast_ctl_array_c2r (array_c2r)
subroutine bcast_ctl_array_icr (array_icr)
subroutine bcast_ctl_array_ir (array_ir)
subroutine bcast_ctl_array_i2r (array_i2r)
subroutine bcast_ctl_array_i2r2 (array_i2r2)
subroutine bcast_ctl_array_ci3 (array_ci3)
Detailed Description
Subroutines to read control arrays.
      subroutine bcast_ctl_type_r1(real_item)
        type(read_real_item), intent(inout) :: real_item
      subroutine bcast_ctl_type_i1(int_item)
        type(read_integer_item), intent(inout) :: int_item
      subroutine bcast_ctl_type_c1(chara_item)
        type(read_character_item), intent(inout) :: chara_item
      subroutine bcast_ctl_type_r2(real2_item)
        type(read_real2_item), intent(inout) :: real2_item
      subroutine bcast_ctl_type_r3(real3_item)
        type(read_real3_item), intent(inout) :: real3_item
      subroutine bcast_ctl_type_i2(int2_item)
        type(read_int2_item), intent(inout) :: int2_item
      subroutine bcast_ctl_type_i3(int3_item)
        type(read_int3_item), intent(inout) :: int3_item
      subroutine bcast_ctl_type_c3(chara3_item)
        type(read_chara3_item), intent(inout) :: chara3_item
      subroutine bcast_ctl_type_c_i3(ci3_item)
        type(read_chara_int3_item), intent(inout) :: ci3_item
      subroutine bcast_ctl_array_r1(array_real)
        type(ctl_array_real), intent(inout) :: array_real
      subroutine bcast_ctl_array_r2(array_r2)
        type(ctl_array_r2), intent(inout) :: array_r2
      subroutine bcast_ctl_array_r3(array_r3)
        type(ctl_array_r3), intent(inout) :: array_r3
      subroutine bcast_ctl_array_i1(array_int)
        type(ctl_array_int), intent(inout) :: array_int
      subroutine bcast_ctl_array_i2(array_i2)
        type(ctl_array_i2), intent(inout) :: array_i2
      subroutine bcast_ctl_array_i3(array_i3)
        type(ctl_array_i3), intent(inout) :: array_i3
      subroutine bcast_ctl_array_c1(array_chara)
        type(ctl_array_chara), intent(inout) :: array_chara
      subroutine bcast_ctl_array_c2(array_c2)
        type(ctl_array_c2), intent(inout) :: array_c2
      subroutine bcast_ctl_array_c3(array_c3)
        type(ctl_array_c3), intent(inout) :: array_c3
      subroutine bcast_ctl_array_cr(array_cr)
        type(ctl_array_cr), intent(inout) :: array_cr
      subroutine bcast_ctl_array_ci(array_ci)
        type(ctl_array_ci), intent(inout) :: array_ci
      subroutine bcast_ctl_array_cr2(array_cr2)
        type(ctl_array_cr2), intent(inout) :: array_cr2
      subroutine bcast_ctl_array_c2r(array_c2r)
        type(ctl_array_c2r), intent(inout) :: array_c2r
      subroutine bcast_ctl_array_icr(array_icr)
        type(ctl_array_icr), intent(inout) :: array_icr
      subroutine bcast_ctl_array_ir(array_ir)
        type(ctl_array_ir), intent(inout) :: array_ir
      subroutine bcast_ctl_array_i2r(array_i2r)
        type(ctl_array_i2r), intent(inout) :: array_i2r
      subroutine bcast_ctl_array_i2r2(array_i2r2)
        type(ctl_array_i2r2), intent(inout) :: array_i2r2
      subroutine bcast_ctl_array_ci3(array_ci3)
        type(ctl_array_ci3), intent(inout) :: array_ci3
Parameters
label label for control items
array_real structures for array
array_r2 structures for array
array_r3 structures for array
array_int structures for array
array_i2 structures for array
array_chara structures for array
array_c2 structures for array
array_c3 structures for array
array_ci structures for array
array_cr structures for array
array_cr2 structures for array
array_c2r structures for array
array_icr structures for array
array_ir structures for array
array_i2r structures for array
array_i2r2 structures for array
array_ci3 structures for array
Function/Subroutine Documentation
bcast_ctl_array_c1()
subroutine bcast_control_arrays::bcast_ctl_array_c1 (type(ctl_array_chara), intent(inout) array_chara)
Definition at line 429 of file bcast_control_arrays.f90.
References t_control_array_character::alloc_control_array_chara(), calypso_mpi_char::calypso_mpi_bcast_character(), calypso_mpi_int::calypso_mpi_bcast_one_int(), transfer_to_long_integers::cast_long(), m_precision::kchara, calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by t_ctl_data_mhd_forces::bcast_forces_ctl(), t_control_data_4_iso_def::bcast_iso_define_control(), t_ctl_data_mhd_evolution::bcast_mhd_layer_ctl(), t_ctl_data_mhd_evolution::bcast_mhd_time_evo_ctl(), t_ctl_data_node_monitor::bcast_monitor_data_ctl(), bcast_4_field_ctl::bcast_phys_data_ctl(), and t_control_data_4_psf_def::bcast_section_def_control().
bcast_ctl_array_c2()
subroutine bcast_control_arrays::bcast_ctl_array_c2 (type(ctl_array_c2), intent(inout) array_c2)
Definition at line 453 of file bcast_control_arrays.f90.
References t_control_array_character2::alloc_control_array_c2(), calypso_mpi_char::calypso_mpi_bcast_character(), calypso_mpi_int::calypso_mpi_bcast_one_int(), transfer_to_long_integers::cast_long(), m_precision::kchara, calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by t_control_data_4_fld_on_psf::bcast_fld_on_psf_control().
bcast_ctl_array_c2r()
subroutine bcast_control_arrays::bcast_ctl_array_c2r (type(ctl_array_c2r), intent(inout) array_c2r)
Definition at line 589 of file bcast_control_arrays.f90.
References t_control_array_chara2real::alloc_control_array_c2_r(), calypso_mpi_char::calypso_mpi_bcast_character(), calypso_mpi_int::calypso_mpi_bcast_one_int(), calypso_mpi_real::calypso_mpi_bcast_real(), transfer_to_long_integers::cast_long(), m_precision::kchara, calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by t_ctl_data_node_boundary::bcast_bc_4_node_ctl(), and t_ctl_data_surf_boundary::bcast_bc_4_surf_ctl().
bcast_ctl_array_c3()
subroutine bcast_control_arrays::bcast_ctl_array_c3 (type(ctl_array_c3), intent(inout) array_c3)
Definition at line 479 of file bcast_control_arrays.f90.
References t_control_array_character3::alloc_control_array_c3(), calypso_mpi_char::calypso_mpi_bcast_character(), calypso_mpi_int::calypso_mpi_bcast_one_int(), transfer_to_long_integers::cast_long(), m_precision::kchara, calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by bcast_4_field_ctl::bcast_phys_data_ctl().
bcast_ctl_array_ci()
subroutine bcast_control_arrays::bcast_ctl_array_ci (type(ctl_array_ci), intent(inout) array_ci)
Definition at line 534 of file bcast_control_arrays.f90.
References t_control_array_charaint::alloc_control_array_c_i(), calypso_mpi_char::calypso_mpi_bcast_character(), calypso_mpi_int::calypso_mpi_bcast_int(), calypso_mpi_int::calypso_mpi_bcast_one_int(), transfer_to_long_integers::cast_long(), m_precision::kchara, calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by bcast_4_sphere_ctl::bcast_ctl_4_shell_define(), bcast_4_sphere_ctl::bcast_ctl_ndomain_4_shell(), and bcast_4_field_ctl::bcast_phys_data_ctl().
bcast_ctl_array_ci3()
subroutine bcast_control_arrays::bcast_ctl_array_ci3 (type(ctl_array_ci3), intent(inout) array_ci3)
Definition at line 731 of file bcast_control_arrays.f90.
References t_control_array_charaint3::alloc_control_array_c_i3(), calypso_mpi_char::calypso_mpi_bcast_character(), calypso_mpi_int::calypso_mpi_bcast_int(), calypso_mpi_int::calypso_mpi_bcast_one_int(), transfer_to_long_integers::cast_long(), m_precision::kchara, calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by bcast_4_field_ctl::bcast_phys_data_ctl().
bcast_ctl_array_cr()
subroutine bcast_control_arrays::bcast_ctl_array_cr (type(ctl_array_cr), intent(inout) array_cr)
Definition at line 507 of file bcast_control_arrays.f90.
References t_control_array_charareal::alloc_control_array_c_r(), calypso_mpi_char::calypso_mpi_bcast_character(), calypso_mpi_int::calypso_mpi_bcast_one_int(), calypso_mpi_real::calypso_mpi_bcast_real(), transfer_to_long_integers::cast_long(), m_precision::kchara, calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by t_ctl_data_mhd_forces::bcast_coriolis_ctl(), t_ctl_data_mhd_normalize::bcast_dimless_ctl(), t_ctl_data_mhd_forces::bcast_gravity_ctl(), t_ctl_data_induct_norm::bcast_induction_ctl(), t_ctl_data_mhd_forces::bcast_magneto_ctl(), t_ctl_data_momentum_norm::bcast_momentum_ctl(), t_control_data_4_psf_def::bcast_section_def_control(), and t_ctl_data_termal_norm::bcast_thermal_ctl().
bcast_ctl_array_cr2()
subroutine bcast_control_arrays::bcast_ctl_array_cr2 (type(ctl_array_cr2), intent(inout) array_cr2)
Definition at line 560 of file bcast_control_arrays.f90.
References t_control_array_charareal2::alloc_control_array_c_r2(), calypso_mpi_char::calypso_mpi_bcast_character(), calypso_mpi_int::calypso_mpi_bcast_one_int(), calypso_mpi_real::calypso_mpi_bcast_real(), transfer_to_long_integers::cast_long(), m_precision::kchara, calypso_mpi::my_rank, and calypso_mpi::nprocs.
bcast_ctl_array_i1()
subroutine bcast_control_arrays::bcast_ctl_array_i1 (type(ctl_array_int), intent(inout) array_int)
Definition at line 354 of file bcast_control_arrays.f90.
References t_control_array_integer::alloc_control_array_int(), calypso_mpi_int::calypso_mpi_bcast_int(), calypso_mpi_int::calypso_mpi_bcast_one_int(), transfer_to_long_integers::cast_long(), calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by bcast_4_sph_monitor_ctl::bcast_gauss_spectr_ctl(), bcast_4_sph_monitor_ctl::bcast_layerd_spectr_ctl(), and bcast_4_sph_monitor_ctl::bcast_pickup_spectr_ctl().
bcast_ctl_array_i2()
subroutine bcast_control_arrays::bcast_ctl_array_i2 (type(ctl_array_i2), intent(inout) array_i2)
Definition at line 377 of file bcast_control_arrays.f90.
References t_control_array_integer2::alloc_control_array_i2(), calypso_mpi_int::calypso_mpi_bcast_int(), calypso_mpi_int::calypso_mpi_bcast_one_int(), transfer_to_long_integers::cast_long(), calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by bcast_4_sphere_ctl::bcast_ctl_4_shell_define(), bcast_4_sph_monitor_ctl::bcast_gauss_spectr_ctl(), t_ctl_data_node_monitor::bcast_monitor_data_ctl(), and bcast_4_sph_monitor_ctl::bcast_pickup_spectr_ctl().
bcast_ctl_array_i2r()
subroutine bcast_control_arrays::bcast_ctl_array_i2r (type(ctl_array_i2r), intent(inout) array_i2r)
Definition at line 673 of file bcast_control_arrays.f90.
References t_control_array_int2real::alloc_control_array_i2_r(), calypso_mpi_int::calypso_mpi_bcast_int(), calypso_mpi_int::calypso_mpi_bcast_one_int(), calypso_mpi_real::calypso_mpi_bcast_real(), transfer_to_long_integers::cast_long(), calypso_mpi::my_rank, and calypso_mpi::nprocs.
bcast_ctl_array_i2r2()
subroutine bcast_control_arrays::bcast_ctl_array_i2r2 (type(ctl_array_i2r2), intent(inout) array_i2r2)
Definition at line 701 of file bcast_control_arrays.f90.
References t_control_array_int2real2::alloc_control_array_i2_r2(), calypso_mpi_int::calypso_mpi_bcast_int(), calypso_mpi_int::calypso_mpi_bcast_one_int(), calypso_mpi_real::calypso_mpi_bcast_real(), transfer_to_long_integers::cast_long(), calypso_mpi::my_rank, and calypso_mpi::nprocs.
bcast_ctl_array_i3()
subroutine bcast_control_arrays::bcast_ctl_array_i3 (type(ctl_array_i3), intent(inout) array_i3)
Definition at line 402 of file bcast_control_arrays.f90.
References t_control_array_integer3::alloc_control_array_i3(), calypso_mpi_int::calypso_mpi_bcast_int(), calypso_mpi_int::calypso_mpi_bcast_one_int(), transfer_to_long_integers::cast_long(), calypso_mpi::my_rank, and calypso_mpi::nprocs.
bcast_ctl_array_icr()
subroutine bcast_control_arrays::bcast_ctl_array_icr (type(ctl_array_icr), intent(inout) array_icr)
Definition at line 618 of file bcast_control_arrays.f90.
References t_control_array_intcharreal::alloc_control_array_i_c_r(), calypso_mpi_char::calypso_mpi_bcast_character(), calypso_mpi_int::calypso_mpi_bcast_int(), calypso_mpi_int::calypso_mpi_bcast_one_int(), calypso_mpi_real::calypso_mpi_bcast_real(), transfer_to_long_integers::cast_long(), m_precision::kchara, calypso_mpi::my_rank, and calypso_mpi::nprocs.
bcast_ctl_array_ir()
subroutine bcast_control_arrays::bcast_ctl_array_ir (type(ctl_array_ir), intent(inout) array_ir)
Definition at line 647 of file bcast_control_arrays.f90.
References t_control_array_intreal::alloc_control_array_i_r(), calypso_mpi_int::calypso_mpi_bcast_int(), calypso_mpi_int::calypso_mpi_bcast_one_int(), calypso_mpi_real::calypso_mpi_bcast_real(), transfer_to_long_integers::cast_long(), calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by bcast_4_sphere_ctl::bcast_ctl_4_shell_define().
bcast_ctl_array_r1()
subroutine bcast_control_arrays::bcast_ctl_array_r1 (type(ctl_array_real), intent(inout) array_real)
Definition at line 276 of file bcast_control_arrays.f90.
References t_control_array_real::alloc_control_array_real(), calypso_mpi_int::calypso_mpi_bcast_one_int(), calypso_mpi_real::calypso_mpi_bcast_real(), transfer_to_long_integers::cast_long(), calypso_mpi::my_rank, and calypso_mpi::nprocs.
bcast_ctl_array_r2()
subroutine bcast_control_arrays::bcast_ctl_array_r2 (type(ctl_array_r2), intent(inout) array_r2)
Definition at line 300 of file bcast_control_arrays.f90.
References t_control_array_real2::alloc_control_array_r2(), calypso_mpi_int::calypso_mpi_bcast_one_int(), calypso_mpi_real::calypso_mpi_bcast_real(), transfer_to_long_integers::cast_long(), calypso_mpi::my_rank, and calypso_mpi::nprocs.
bcast_ctl_array_r3()
subroutine bcast_control_arrays::bcast_ctl_array_r3 (type(ctl_array_r3), intent(inout) array_r3)
Definition at line 326 of file bcast_control_arrays.f90.
References t_control_array_real3::alloc_control_array_r3(), calypso_mpi_int::calypso_mpi_bcast_one_int(), calypso_mpi_real::calypso_mpi_bcast_real(), transfer_to_long_integers::cast_long(), calypso_mpi::my_rank, and calypso_mpi::nprocs.
Referenced by t_ctl_data_node_monitor::bcast_monitor_data_ctl().
bcast_ctl_type_c1()
subroutine bcast_control_arrays::bcast_ctl_type_c1 (type(read_character_item), intent(inout) chara_item)
Definition at line 135 of file bcast_control_arrays.f90.
References calypso_mpi_char::calypso_mpi_bcast_character(), calypso_mpi_int::calypso_mpi_bcast_one_int(), transfer_to_long_integers::cast_long(), m_precision::kchara, and calypso_mpi::nprocs.
Referenced by bcast_4_sphere_ctl::bcast_ctl_4_shell_define(), bcast_4_platform_ctl::bcast_ctl_data_4_platform(), bcast_4_time_step_ctl::bcast_ctl_data_4_time_step(), bcast_4_sphere_ctl::bcast_ctl_ndomain_4_shell(), bcast_4_sph_monitor_ctl::bcast_each_vol_spectr_ctl(), bcast_4_platform_ctl::bcast_fem_mesh_control(), t_control_data_4_fld_on_psf::bcast_fld_on_psf_control(), bcast_4_sph_monitor_ctl::bcast_gauss_spectr_ctl(), t_ctl_data_mhd_forces::bcast_gravity_ctl(), t_control_data_4_iso::bcast_iso_control_data(), t_control_data_4_iso_def::bcast_iso_define_control(), bcast_4_sph_monitor_ctl::bcast_layerd_spectr_ctl(), t_ctl_data_mhd_forces::bcast_magneto_ctl(), bcast_4_sph_monitor_ctl::bcast_mid_eq_monitor_ctl(), bcast_4_sph_monitor_ctl::bcast_pickup_spectr_ctl(), t_control_data_4_psf::bcast_psf_control_data(), t_ctl_data_temp_model::bcast_ref_scalar_ctl(), t_ctl_data_mhd_evo_scheme::bcast_restart_ctl(), t_control_data_4_psf_def::bcast_section_def_control(), bcast_4_sph_monitor_ctl::bcast_sph_monitoring_ctl(), t_control_data_surfacings::bcast_surfacing_controls(), and t_ctl_data_mhd_evo_scheme::bcast_time_loop_ctl().
bcast_ctl_type_c3()
subroutine bcast_control_arrays::bcast_ctl_type_c3 (type(read_chara3_item), intent(inout) chara3_item)
Definition at line 233 of file bcast_control_arrays.f90.
References calypso_mpi_char::calypso_mpi_bcast_character(), calypso_mpi_int::calypso_mpi_bcast_one_int(), transfer_to_long_integers::cast_long(), m_precision::kchara, and calypso_mpi::nprocs.
bcast_ctl_type_c_i3()
subroutine bcast_control_arrays::bcast_ctl_type_c_i3 (type(read_chara_int3_item), intent(inout) ci3_item)
Definition at line 253 of file bcast_control_arrays.f90.
References calypso_mpi_char::calypso_mpi_bcast_character(), calypso_mpi_int::calypso_mpi_bcast_int(), calypso_mpi_int::calypso_mpi_bcast_one_int(), transfer_to_long_integers::cast_long(), m_precision::kchara, and calypso_mpi::nprocs.
bcast_ctl_type_i1()
subroutine bcast_control_arrays::bcast_ctl_type_i1 (type(read_integer_item), intent(inout) int_item)
Definition at line 118 of file bcast_control_arrays.f90.
References calypso_mpi_int::calypso_mpi_bcast_one_int(), and calypso_mpi::nprocs.
Referenced by t_ctl_data_crust_filter::bcast_crustal_filtering_ctl(), bcast_4_sphere_ctl::bcast_ctl_4_shell_define(), bcast_4_platform_ctl::bcast_ctl_data_4_platform(), bcast_4_time_step_ctl::bcast_ctl_data_4_time_step(), bcast_4_sphere_ctl::bcast_ctl_ndomain_4_shell(), bcast_4_platform_ctl::bcast_fem_mesh_control(), bcast_4_sph_monitor_ctl::bcast_mid_eq_monitor_ctl(), t_control_data_surfacings::bcast_surfacing_controls(), and t_ctl_data_mhd_evo_scheme::bcast_time_loop_ctl().
bcast_ctl_type_i2()
subroutine bcast_control_arrays::bcast_ctl_type_i2 (type(read_int2_item), intent(inout) int2_item)
Definition at line 195 of file bcast_control_arrays.f90.
References calypso_mpi_int::calypso_mpi_bcast_int(), calypso_mpi_int::calypso_mpi_bcast_one_int(), transfer_to_long_integers::cast_long(), and calypso_mpi::nprocs.
bcast_ctl_type_i3()
subroutine bcast_control_arrays::bcast_ctl_type_i3 (type(read_int3_item), intent(inout) int3_item)
Definition at line 214 of file bcast_control_arrays.f90.
References calypso_mpi_int::calypso_mpi_bcast_int(), calypso_mpi_int::calypso_mpi_bcast_one_int(), transfer_to_long_integers::cast_long(), and calypso_mpi::nprocs.
bcast_ctl_type_r1()
subroutine bcast_control_arrays::bcast_ctl_type_r1 (type(read_real_item), intent(inout) real_item)
Definition at line 100 of file bcast_control_arrays.f90.
References calypso_mpi_int::calypso_mpi_bcast_one_int(), calypso_mpi_real::calypso_mpi_bcast_one_real(), and calypso_mpi::nprocs.
Referenced by bcast_4_sphere_ctl::bcast_ctl_4_shell_define(), bcast_4_time_step_ctl::bcast_ctl_data_4_time_step(), bcast_4_sph_monitor_ctl::bcast_each_vol_spectr_ctl(), t_control_data_4_fld_on_psf::bcast_fld_on_psf_control(), bcast_4_sph_monitor_ctl::bcast_gauss_spectr_ctl(), t_control_data_4_iso_def::bcast_iso_define_control(), bcast_4_sph_monitor_ctl::bcast_mid_eq_monitor_ctl(), bcast_4_assemble_sph_ctl::bcast_newrst_control(), t_ctl_data_temp_model::bcast_ref_value_ctl(), t_control_data_4_psf_def::bcast_section_def_control(), t_control_data_surfacings::bcast_surfacing_controls(), t_ctl_data_temp_model::bcast_takepiro_ctl(), and t_ctl_data_mhd_evo_scheme::bcast_time_loop_ctl().
bcast_ctl_type_r2()
subroutine bcast_control_arrays::bcast_ctl_type_r2 (type(read_real2_item), intent(inout) real2_item)
Definition at line 155 of file bcast_control_arrays.f90.
References calypso_mpi_int::calypso_mpi_bcast_one_int(), calypso_mpi_real::calypso_mpi_bcast_real(), transfer_to_long_integers::cast_long(), and calypso_mpi::nprocs.
bcast_ctl_type_r3()
subroutine bcast_control_arrays::bcast_ctl_type_r3 (type(read_real3_item), intent(inout) real3_item)
Definition at line 175 of file bcast_control_arrays.f90.
References calypso_mpi_int::calypso_mpi_bcast_one_int(), calypso_mpi_real::calypso_mpi_bcast_real(), transfer_to_long_integers::cast_long(), and calypso_mpi::nprocs.