CALYPSO: t_sph_single_fftw Module Reference
t_sph_single_fftw Module Reference
Fourier transform using FFTW Ver.3.
Data Types
type work_for_sgl_fftw
Structure to use SNGLE FFTW.
Functions/Subroutines
subroutine init_sph_single_fftw (sph_rtp, FFTW_t)
subroutine finalize_sph_single_fftw (FFTW_t)
subroutine verify_sph_single_fftw (sph_rtp, FFTW_t)
subroutine sph_single_fwd_fftw_to_send (sph_rtp, comm_rtp, ncomp_fwd, n_WS, X_rtp, WS, FFTW_t)
subroutine sph_single_back_fftw_from_recv (sph_rtp, comm_rtp, ncomp_bwd, n_WR, WR, X_rtp, FFTW_t)
subroutine, private alloc_fftw_plan (Ncomp, Nfft, FFTW_t)
subroutine dealloc_fftw_plan (FFTW_t)
subroutine alloc_tmp_ordering_fftw (sph_rtp, FFTW_t)
subroutine dealloc_tmp_ordering_fftw (FFTW_t)
subroutine copy_single_fftw_to_send (nd, j, nnod_rtp, irev_sr_rtp, nnod_rt, ncomp_fwd, Nfft_c, C_fft, aNfft, n_WS, WS)
subroutine copy_single_fftw_from_recv (nd, j, nnod_rtp, irev_sr_rtp, nnod_rt, ncomp_bwd, n_WR, WR, Nfft_c, C_fft)
Detailed Description
Fourier transform using FFTW Ver.3.
 ------------------------------------------------------------------
      subroutine init_sph_single_FFTW(sph_rtp, FFTW_t)
      subroutine finalize_sph_single_FFTW(FFTW_t)
      subroutine verify_sph_single_FFTW(sph_rtp, FFTW_t)
        type(sph_rtp_grid), intent(in) :: sph_rtp
      subroutine alloc_tmp_ordering_FFTW(sph_rtp, FFTW_t)
      subroutine dealloc_tmp_ordering_FFTW(FFTW_t)
        type(sph_rtp_grid), intent(in) :: sph_rtp
   wrapper subroutine for initierize FFT by FFTW
 ------------------------------------------------------------------
      subroutine sph_single_fwd_FFTW_to_send(sph_rtp, comm_rtp,       &
     &          ncomp_fwd, n_WS, X_rtp, WS, FFTW_t)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_comm_tbl), intent(in)  :: comm_rtp
 ------------------------------------------------------------------
 wrapper subroutine for forward Fourier transform by FFTW3
   a_{k} = \frac{2}{Nfft} \sum_{j=0}^{Nfft-1} x_{j} \cos (\frac{2\pi j k}{Nfft})
   b_{k} = \frac{2}{Nfft} \sum_{j=0}^{Nfft-1} x_{j} \cos (\frac{2\pi j k}{Nfft})
   a_{0} = \frac{1}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
    K = Nfft/2....
   a_{k} = \frac{1}{Nfft} \sum_{j=0}^{Nfft-1} x_{j} \cos (\frac{2\pi j k}{Nfft})
 ------------------------------------------------------------------
      subroutine sph_single_back_FFTW_from_recv(sph_rtp, comm_rtp,    &
     &          ncomp_bwd, n_WR, WR, X_rtp, FFTW_t)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_comm_tbl), intent(in)  :: comm_rtp
 ------------------------------------------------------------------
 wrapper subroutine for backward Fourier transform by FFTW3
   x_{k} = a_{0} + (-1)^{j} a_{Nfft/2} + sum_{k=1}^{Nfft/2-1}
          (a_{k} \cos(2\pijk/Nfft) + b_{k} \sin(2\pijk/Nfft))
 ------------------------------------------------------------------
       i = 1:     a_{0}
       i = 2:     a_{Nfft/2}
       i = 3:     a_{1}
       i = 4:     b_{1}
       ...
       i = 2*k+1: a_{k}
       i = 2*k+2: b_{k}
       ...
       i = Nfft-1:   a_{Nfft/2-1}
       i = Nfft:     b_{Nfft/2-1}
 ------------------------------------------------------------------
Parameters
Nsmp Number of SMP processors
Nstacksmp(0:Nsmp) End number for each SMP process
Ncomp Number of components for Fourier transforms
Nfft Data length for eadh FFT
X(Ncomp,Nfft) Data for Fourier transform
Function/Subroutine Documentation
alloc_fftw_plan()
subroutine, private t_sph_single_fftw::alloc_fftw_plan (integer(kind = kint), intent(in) Ncomp, integer(kind = kint), intent(in) Nfft, type(work_for_sgl_fftw), intent(inout) FFTW_t) private
Definition at line 326 of file t_sph_single_FFTW.F90.
Referenced by init_sph_single_fftw().
alloc_tmp_ordering_fftw()
subroutine t_sph_single_fftw::alloc_tmp_ordering_fftw (type(sph_rtp_grid), intent(in) sph_rtp, type(work_for_sgl_fftw), intent(inout) FFTW_t)
Definition at line 359 of file t_sph_single_FFTW.F90.
copy_single_fftw_from_recv()
subroutine t_sph_single_fftw::copy_single_fftw_from_recv (integer(kind = kint), intent(in) nd, integer(kind = kint), intent(in) j, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(nnod_rtp), intent(in) irev_sr_rtp, integer(kind = kint), intent(in) nnod_rt, integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(in) WR, integer(kind = kint), intent(in) Nfft_c, complex(kind = fftw_complex), dimension(nfft_c), intent(inout) C_fft)
Definition at line 421 of file t_sph_single_FFTW.F90.
References m_constants::half, and m_constants::zero.
Referenced by sph_single_back_fftw_from_recv().
copy_single_fftw_to_send()
subroutine t_sph_single_fftw::copy_single_fftw_to_send (integer(kind = kint), intent(in) nd, integer(kind = kint), intent(in) j, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(nnod_rtp), intent(in) irev_sr_rtp, integer(kind = kint), intent(in) nnod_rt, integer(kind = kint), intent(in) ncomp_fwd, integer(kind = kint), intent(in) Nfft_c, complex(kind = fftw_complex), dimension(nfft_c), intent(in) C_fft, real(kind = kreal), intent(in) aNfft, integer(kind = kint), intent(in) n_WS, real (kind = kreal), dimension(n_ws), intent(inout) WS)
Definition at line 384 of file t_sph_single_FFTW.F90.
References m_fftw_parameters::iu, and m_constants::two.
Referenced by sph_single_fwd_fftw_to_send().
dealloc_fftw_plan()
subroutine t_sph_single_fftw::dealloc_fftw_plan (type(work_for_sgl_fftw), intent(inout) FFTW_t)
Definition at line 347 of file t_sph_single_FFTW.F90.
Referenced by finalize_sph_single_fftw().
dealloc_tmp_ordering_fftw()
subroutine t_sph_single_fftw::dealloc_tmp_ordering_fftw (type(work_for_sgl_fftw), intent(inout) FFTW_t)
Definition at line 372 of file t_sph_single_FFTW.F90.
finalize_sph_single_fftw()
subroutine t_sph_single_fftw::finalize_sph_single_fftw (type(work_for_sgl_fftw), intent(inout) FFTW_t)
Definition at line 149 of file t_sph_single_FFTW.F90.
References dealloc_fftw_plan(), and m_machine_parameter::np_smp.
Referenced by t_sph_fft_selector::finalize_sph_fft_select(), and verify_sph_single_fftw().
init_sph_single_fftw()
subroutine t_sph_single_fftw::init_sph_single_fftw (type(sph_rtp_grid), intent(in) sph_rtp, type(work_for_sgl_fftw), intent(inout) FFTW_t)
Definition at line 121 of file t_sph_single_FFTW.F90.
References alloc_fftw_plan(), m_fftw_parameters::fftw_estimate, m_machine_parameter::np_smp, and m_constants::one.
Referenced by t_sph_fft_selector::init_sph_fft_select(), and verify_sph_single_fftw().
sph_single_back_fftw_from_recv()
subroutine t_sph_single_fftw::sph_single_back_fftw_from_recv (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(inout) WR, real(kind = kreal), dimension(sph_rtp%nnod_rtp,ncomp_bwd), intent(inout) X_rtp, type(work_for_sgl_fftw), intent(inout) FFTW_t)
Definition at line 258 of file t_sph_single_FFTW.F90.
References copy_single_fftw_from_recv(), m_elapsed_labels_sph_trns::iflag_fft_time, m_elapsed_labels_sph_trns::ist_elapsed_fft, m_machine_parameter::np_smp, copy_single_fft_and_rtp::sel_copy_single_fft_to_rtp(), and copy_single_fft_and_rtp::sum_omp_elapsed_4_fft().
Referenced by t_sph_fft_selector::back_fft_select_from_recv().
sph_single_fwd_fftw_to_send()
subroutine t_sph_single_fftw::sph_single_fwd_fftw_to_send (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, integer(kind = kint), intent(in) ncomp_fwd, integer(kind = kint), intent(in) n_WS, real(kind = kreal), dimension(sph_rtp%nnod_rtp,ncomp_fwd), intent(in) X_rtp, real (kind=kreal), dimension(n_ws), intent(inout) WS, type(work_for_sgl_fftw), intent(inout) FFTW_t)
Definition at line 191 of file t_sph_single_FFTW.F90.
References copy_single_fftw_to_send(), m_elapsed_labels_sph_trns::iflag_fft_time, m_elapsed_labels_sph_trns::ist_elapsed_fft, m_machine_parameter::np_smp, copy_single_fft_and_rtp::sel_copy_single_rtp_to_fft(), and copy_single_fft_and_rtp::sum_omp_elapsed_4_fft().
Referenced by t_sph_fft_selector::fwd_fft_select_to_send().
verify_sph_single_fftw()
subroutine t_sph_single_fftw::verify_sph_single_fftw (type(sph_rtp_grid), intent(in) sph_rtp, type(work_for_sgl_fftw), intent(inout) FFTW_t)
Definition at line 169 of file t_sph_single_FFTW.F90.
References finalize_sph_single_fftw(), init_sph_single_fftw(), and m_machine_parameter::np_smp.
Referenced by t_sph_fft_selector::verify_sph_fft_select().