CALYPSO: m_explicit_term_labels Module Reference
m_explicit_term_labels Module Reference
Functions/Subroutines
logical function check_vector_work_field (field_name)
logical function check_scalar_work_field (field_name)
logical function check_work_4_poisson (field_name)
logical function check_vector_check_field (field_name)
logical function check_scalar_check_field (field_name)
integer(kind=kint) function num_work_4_explicit ()
integer(kind=kint) function num_check_fields ()
subroutine set_work_4_explicit_labels (n_comps, names, maths)
subroutine set_check_fields_labels (n_comps, names, maths)
Variables
integer(kind=kint), parameter, private nexp_work = 11
integer(kind=kint), parameter, private ncheck_fld = 12
type(field_def), parameter sum_forces = field_def(n_comp = n_vector, name = 'sum_forces', math = '$ F_{i} $')
Field label for total forces.
type(field_def), parameter rot_sum_forces = field_def(n_comp = n_vector, name = 'rot_sum_forces', math = '$ e_{ijk} \partial_{j} F_{k} $')
Field label for curl of total forces.
type(field_def), parameter div_sum_forces = field_def(n_comp = n_scalar, name = 'div_sum_forces', math = '$ \partial_{i} F_{i} $')
Field label for divergence of total forces.
type(field_def), parameter previous_momentum = field_def(n_comp = n_vector, name = 'previous_momentum', math = '$ F_{u}^{N-1} $')
Field label for explicit term for momentum at previous step.
type(field_def), parameter previous_induction = field_def(n_comp = n_vector, name = 'previous_induction', math = '$ F_{B}^{N-1} $')
Field label for explicit term for induction at previous step.
type(field_def), parameter previous_heat = field_def(n_comp = n_scalar, name = 'previous_heat', math = '$ F_{T}^{N-1} $')
Field label for explicit term for heat at previous step.
type(field_def), parameter previous_composition = field_def(n_comp = n_scalar, name = 'previous_composition', math = '$ F_{C}^{N-1} $')
Field label for explicit term for composition at previous step.
type(field_def), parameter previous_pressure = field_def(n_comp = n_scalar, name = 'previous_pressure', math = '$ P^{N-1} $')
Field label for explicit term for pressure at previous step.
type(field_def), parameter previous_potential = field_def(n_comp = n_scalar, name = 'previous_potential', math = '$ \varphi^{N-1} $')
Field label for explicit term for potential at previous step.
type(field_def), parameter pressure_work = field_def(n_comp = n_scalar, name = 'pressure_work', math = '$ \varphi $')
Field label of work area for pressure \(\varphi \).
type(field_def), parameter m_potential_work = field_def(n_comp = n_scalar, name = 'm_potential_work', math = '$ \varphi $')
Field label of work area for scalar potential \(\varphi \).
type(field_def), parameter check_momentum = field_def(n_comp = n_vector, name = 'check_momentum', math = '$ u_{i}^{N-1} $')
Field label for explicit term for momentum for check.
type(field_def), parameter check_induction = field_def(n_comp = n_vector, name = 'check_induction', math = '$ B_{i}^{N-1} $')
Field label for explicit term for induction for check.
type(field_def), parameter check_heat = field_def(n_comp = n_scalar, name = 'check_heat', math = '$ T^{N-1} $')
Field label for explicit term for heat for check.
type(field_def), parameter check_composition = field_def(n_comp = n_scalar, name = 'check_composition', math = '$ C^{N-1} $')
Field label for explicit term for composition for check.
type(field_def), parameter check_pressure = field_def(n_comp = n_scalar, name = 'check_pressure', math = '$ P^{N-1} $')
Field label for explicit term for pressure for check.
type(field_def), parameter check_potential = field_def(n_comp = n_scalar, name = 'check_potential', math = '$ \varphi^{N-1} $')
Field label for explicit term for electric potential for check.
type(field_def), parameter check_momentum_2 = field_def(n_comp = n_vector, name = 'check_momentum_2', math = '$ u_{i}^{N-2} $')
Field label for explicit term for momentum for 2nd check.
type(field_def), parameter check_induction_2 = field_def(n_comp = n_vector, name = 'check_induction_2', math = '$ B_{i}^{N-2} $')
Field label for explicit term for induction for 2nd check.
type(field_def), parameter check_heat_2 = field_def(n_comp = n_scalar, name = 'check_heat_2', math = '$ T^{N-2} $')
Field label for explicit term for heat for 2nd check.
type(field_def), parameter check_composition_2 = field_def(n_comp = n_scalar, name = 'check_composition_2', math = '$ C^{N-2} $')
Field label for explicit term for composition for 2nd check.
type(field_def), parameter check_pressure_2 = field_def(n_comp = n_scalar, name = 'check_pressure_2', math = '$ P^{N-2} $')
Field label for explicit term for pressure for 2nd check.
type(field_def), parameter check_potential_2 = field_def(n_comp = n_scalar, name = 'check_potential_2', math = '$ \varphi^{N-2} $')
Field label for explicit term for electric potential for 2nd check.
Function/Subroutine Documentation
check_scalar_check_field()
logical function m_explicit_term_labels::check_scalar_check_field (character(len = kchara), intent(in) field_name)
Definition at line 277 of file m_explicit_term_labels.f90.
References check_composition, check_composition_2, check_heat, check_heat_2, check_potential, check_potential_2, check_pressure, and check_pressure_2.
Referenced by set_mhd_field_address::check_scalar_fields(), and t_explicit_term_labels::set_check_field_addresses().
check_scalar_work_field()
logical function m_explicit_term_labels::check_scalar_work_field (character(len = kchara), intent(in) field_name)
Definition at line 230 of file m_explicit_term_labels.f90.
References div_sum_forces, previous_composition, previous_heat, previous_potential, and previous_pressure.
Referenced by set_mhd_field_address::check_scalar_fields(), and t_explicit_term_labels::set_work_field_addresses().
check_vector_check_field()
logical function m_explicit_term_labels::check_vector_check_field (character(len = kchara), intent(in) field_name)
Definition at line 261 of file m_explicit_term_labels.f90.
References check_induction, check_induction_2, check_momentum, and check_momentum_2.
Referenced by set_mhd_field_address::check_vector_fields(), and t_explicit_term_labels::set_check_field_addresses().
check_vector_work_field()
logical function m_explicit_term_labels::check_vector_work_field (character(len = kchara), intent(in) field_name)
Definition at line 214 of file m_explicit_term_labels.f90.
References previous_induction, previous_momentum, rot_sum_forces, and sum_forces.
Referenced by set_mhd_field_address::check_vector_fields(), and t_explicit_term_labels::set_work_field_addresses().
check_work_4_poisson()
logical function m_explicit_term_labels::check_work_4_poisson (character(len = kchara), intent(in) field_name)
Definition at line 247 of file m_explicit_term_labels.f90.
References m_potential_work, and pressure_work.
Referenced by set_mhd_field_address::check_scalar_fields(), and t_explicit_term_labels::set_work_field_addresses().
num_check_fields()
integer(kind = kint) function m_explicit_term_labels::num_check_fields
Definition at line 305 of file m_explicit_term_labels.f90.
References ncheck_fld.
num_work_4_explicit()
integer(kind = kint) function m_explicit_term_labels::num_work_4_explicit
Definition at line 298 of file m_explicit_term_labels.f90.
References nexp_work.
set_check_fields_labels()
subroutine m_explicit_term_labels::set_check_fields_labels (integer(kind = kint_4b), dimension(ncheck_fld), intent(inout) n_comps, character(len = kchara), dimension(ncheck_fld), intent(inout) names, character(len = kchara), dimension(ncheck_fld), intent(inout) maths)
Definition at line 349 of file m_explicit_term_labels.f90.
References check_composition, check_composition_2, check_heat, check_heat_2, check_induction, check_induction_2, check_momentum, check_momentum_2, check_potential, check_potential_2, check_pressure, check_pressure_2, and t_field_labels::set_field_labels().
set_work_4_explicit_labels()
subroutine m_explicit_term_labels::set_work_4_explicit_labels (integer(kind = kint_4b), dimension(nexp_work), intent(inout) n_comps, character(len = kchara), dimension(nexp_work), intent(inout) names, character(len = kchara), dimension(nexp_work), intent(inout) maths)
Definition at line 312 of file m_explicit_term_labels.f90.
References div_sum_forces, m_potential_work, pressure_work, previous_composition, previous_heat, previous_induction, previous_momentum, previous_potential, previous_pressure, rot_sum_forces, t_field_labels::set_field_labels(), and sum_forces.
Variable Documentation
check_composition
type(field_def), parameter m_explicit_term_labels::check_composition = field_def(n_comp = n_scalar, name = 'check_composition', math = '$ C^{N-1} $')
Field label for explicit term for composition for check.
Definition at line 159 of file m_explicit_term_labels.f90.
Referenced by add_nodal_fields_4_mhd::add_data_4_check_step(), check_workarea_4_explicit::add_field_ctl_4_check_evo(), set_restart_data::check_scalar_4_fem_rst(), check_scalar_check_field(), t_explicit_term_labels::set_check_field_addresses(), and set_check_fields_labels().
check_composition_2
type(field_def), parameter m_explicit_term_labels::check_composition_2 = field_def(n_comp = n_scalar, name = 'check_composition_2', math = '$ C^{N-2} $')
Field label for explicit term for composition for 2nd check.
Definition at line 192 of file m_explicit_term_labels.f90.
Referenced by check_workarea_4_explicit::add_field_ctl_4_check_evo(), check_scalar_check_field(), t_explicit_term_labels::set_check_field_addresses(), and set_check_fields_labels().
check_heat
type(field_def), parameter m_explicit_term_labels::check_heat = field_def(n_comp = n_scalar, name = 'check_heat', math = '$ T^{N-1} $')
Field label for explicit term for heat for check.
Definition at line 153 of file m_explicit_term_labels.f90.
Referenced by add_nodal_fields_4_mhd::add_data_4_check_step(), check_workarea_4_explicit::add_field_ctl_4_check_evo(), check_scalar_check_field(), t_explicit_term_labels::set_check_field_addresses(), and set_check_fields_labels().
check_heat_2
type(field_def), parameter m_explicit_term_labels::check_heat_2 = field_def(n_comp = n_scalar, name = 'check_heat_2', math = '$ T^{N-2} $')
Field label for explicit term for heat for 2nd check.
Definition at line 186 of file m_explicit_term_labels.f90.
Referenced by check_workarea_4_explicit::add_field_ctl_4_check_evo(), check_scalar_check_field(), t_explicit_term_labels::set_check_field_addresses(), and set_check_fields_labels().
check_induction
type(field_def), parameter m_explicit_term_labels::check_induction = field_def(n_comp = n_vector, name = 'check_induction', math = '$ B_{i}^{N-1} $')
Field label for explicit term for induction for check.
Definition at line 148 of file m_explicit_term_labels.f90.
Referenced by add_nodal_fields_4_mhd::add_data_4_check_step(), check_workarea_4_explicit::add_field_ctl_4_check_evo(), add_nodal_fields_4_mhd::add_field_ctl_4_evo_magne(), set_restart_data::check_vector_4_fem_rst(), check_vector_check_field(), set_merged_restart_data::rescale_4_magne(), t_explicit_term_labels::set_check_field_addresses(), and set_check_fields_labels().
check_induction_2
type(field_def), parameter m_explicit_term_labels::check_induction_2 = field_def(n_comp = n_vector, name = 'check_induction_2', math = '$ B_{i}^{N-2} $')
Field label for explicit term for induction for 2nd check.
Definition at line 181 of file m_explicit_term_labels.f90.
Referenced by check_workarea_4_explicit::add_field_ctl_4_check_evo(), check_vector_check_field(), t_explicit_term_labels::set_check_field_addresses(), and set_check_fields_labels().
check_momentum
type(field_def), parameter m_explicit_term_labels::check_momentum = field_def(n_comp = n_vector, name = 'check_momentum', math = '$ u_{i}^{N-1} $')
Field label for explicit term for momentum for check.
Definition at line 143 of file m_explicit_term_labels.f90.
Referenced by add_nodal_fields_4_mhd::add_data_4_check_step(), check_workarea_4_explicit::add_field_ctl_4_check_evo(), set_restart_data::check_vector_4_fem_rst(), check_vector_check_field(), t_explicit_term_labels::set_check_field_addresses(), and set_check_fields_labels().
check_momentum_2
type(field_def), parameter m_explicit_term_labels::check_momentum_2 = field_def(n_comp = n_vector, name = 'check_momentum_2', math = '$ u_{i}^{N-2} $')
Field label for explicit term for momentum for 2nd check.
Definition at line 176 of file m_explicit_term_labels.f90.
Referenced by check_workarea_4_explicit::add_field_ctl_4_check_evo(), check_vector_check_field(), t_explicit_term_labels::set_check_field_addresses(), and set_check_fields_labels().
check_potential
type(field_def), parameter m_explicit_term_labels::check_potential = field_def(n_comp = n_scalar, name = 'check_potential', math = '$ \varphi^{N-1} $')
Field label for explicit term for electric potential for check.
Definition at line 170 of file m_explicit_term_labels.f90.
Referenced by add_nodal_fields_4_mhd::add_data_4_check_step(), check_workarea_4_explicit::add_field_ctl_4_check_evo(), set_restart_data::check_scalar_4_fem_rst(), check_scalar_check_field(), t_explicit_term_labels::set_check_field_addresses(), and set_check_fields_labels().
check_potential_2
type(field_def), parameter m_explicit_term_labels::check_potential_2 = field_def(n_comp = n_scalar, name = 'check_potential_2', math = '$ \varphi^{N-2} $')
Field label for explicit term for electric potential for 2nd check.
Definition at line 203 of file m_explicit_term_labels.f90.
Referenced by check_workarea_4_explicit::add_field_ctl_4_check_evo(), check_scalar_check_field(), t_explicit_term_labels::set_check_field_addresses(), and set_check_fields_labels().
check_pressure
type(field_def), parameter m_explicit_term_labels::check_pressure = field_def(n_comp = n_scalar, name = 'check_pressure', math = '$ P^{N-1} $')
Field label for explicit term for pressure for check.
Definition at line 164 of file m_explicit_term_labels.f90.
Referenced by add_nodal_fields_4_mhd::add_data_4_check_step(), check_workarea_4_explicit::add_field_ctl_4_check_evo(), set_restart_data::check_scalar_4_fem_rst(), check_scalar_check_field(), t_explicit_term_labels::set_check_field_addresses(), and set_check_fields_labels().
check_pressure_2
type(field_def), parameter m_explicit_term_labels::check_pressure_2 = field_def(n_comp = n_scalar, name = 'check_pressure_2', math = '$ P^{N-2} $')
Field label for explicit term for pressure for 2nd check.
Definition at line 197 of file m_explicit_term_labels.f90.
Referenced by check_workarea_4_explicit::add_field_ctl_4_check_evo(), check_scalar_check_field(), t_explicit_term_labels::set_check_field_addresses(), and set_check_fields_labels().
div_sum_forces
type(field_def), parameter m_explicit_term_labels::div_sum_forces = field_def(n_comp = n_scalar, name = 'div_sum_forces', math = '$ \partial_{i} F_{i} $')
Field label for divergence of total forces.
Definition at line 86 of file m_explicit_term_labels.f90.
Referenced by check_scalar_work_field(), set_work_4_explicit_labels(), and t_explicit_term_labels::set_work_field_addresses().
m_potential_work
type(field_def), parameter m_explicit_term_labels::m_potential_work = field_def(n_comp = n_scalar, name = 'm_potential_work', math = '$ \varphi $')
Field label of work area for scalar potential \(\varphi \).
Definition at line 135 of file m_explicit_term_labels.f90.
Referenced by add_nodal_fields_4_mhd::add_work_area_4_potentials(), check_work_4_poisson(), set_work_4_explicit_labels(), and t_explicit_term_labels::set_work_field_addresses().
ncheck_fld
integer(kind = kint), parameter, private m_explicit_term_labels::ncheck_fld = 12 private
Definition at line 71 of file m_explicit_term_labels.f90.
Referenced by num_check_fields().
nexp_work
integer(kind = kint), parameter, private m_explicit_term_labels::nexp_work = 11 private
Definition at line 70 of file m_explicit_term_labels.f90.
Referenced by num_work_4_explicit().
pressure_work
type(field_def), parameter m_explicit_term_labels::pressure_work = field_def(n_comp = n_scalar, name = 'pressure_work', math = '$ \varphi $')
Field label of work area for pressure \(\varphi \).
Definition at line 129 of file m_explicit_term_labels.f90.
Referenced by add_nodal_fields_4_mhd::add_work_area_4_potentials(), check_work_4_poisson(), set_work_4_explicit_labels(), and t_explicit_term_labels::set_work_field_addresses().
previous_composition
type(field_def), parameter m_explicit_term_labels::previous_composition = field_def(n_comp = n_scalar, name = 'previous_composition', math = '$ F_{C}^{N-1} $')
Field label for explicit term for composition at previous step.
Definition at line 110 of file m_explicit_term_labels.f90.
Referenced by add_nodal_fields_4_mhd::add_data_4_previous_step(), set_restart_data::check_scalar_4_fem_rst(), set_sph_restart_io::check_scalar_4_restart(), check_scalar_work_field(), r_interpolate_sph_data::r_interpolate_sph_rst_from_io(), set_work_4_explicit_labels(), and t_explicit_term_labels::set_work_field_addresses().
previous_heat
type(field_def), parameter m_explicit_term_labels::previous_heat = field_def(n_comp = n_scalar, name = 'previous_heat', math = '$ F_{T}^{N-1} $')
Field label for explicit term for heat at previous step.
Definition at line 104 of file m_explicit_term_labels.f90.
Referenced by add_nodal_fields_4_mhd::add_data_4_previous_step(), set_restart_data::check_scalar_4_fem_rst(), set_sph_restart_io::check_scalar_4_restart(), check_scalar_work_field(), convert_from_rayleigh_rst::cvt_each_field_from_rayleigh(), r_interpolate_sph_data::r_interpolate_sph_rst_from_io(), rayleigh_restart_io::set_rayleigh_restart_field(), rayleigh_restart_io::set_rayleigh_rst_file_name(), set_work_4_explicit_labels(), and t_explicit_term_labels::set_work_field_addresses().
previous_induction
type(field_def), parameter m_explicit_term_labels::previous_induction = field_def(n_comp = n_vector, name = 'previous_induction', math = '$ F_{B}^{N-1} $')
Field label for explicit term for induction at previous step.
Definition at line 99 of file m_explicit_term_labels.f90.
Referenced by add_nodal_fields_4_mhd::add_data_4_previous_step(), set_restart_data::check_vector_4_fem_rst(), set_sph_restart_io::check_vector_4_restart(), check_vector_work_field(), convert_from_rayleigh_rst::cvt_each_field_from_rayleigh(), r_interpolate_sph_data::r_interpolate_sph_rst_from_io(), set_merged_restart_data::rescale_4_magne(), rayleigh_restart_io::set_rayleigh_restart_field(), rayleigh_restart_io::set_rayleigh_rst_file_name(), set_work_4_explicit_labels(), and t_explicit_term_labels::set_work_field_addresses().
previous_momentum
type(field_def), parameter m_explicit_term_labels::previous_momentum = field_def(n_comp = n_vector, name = 'previous_momentum', math = '$ F_{u}^{N-1} $')
Field label for explicit term for momentum at previous step.
Definition at line 94 of file m_explicit_term_labels.f90.
Referenced by add_nodal_fields_4_mhd::add_data_4_previous_step(), set_restart_data::check_vector_4_fem_rst(), set_sph_restart_io::check_vector_4_restart(), check_vector_work_field(), convert_from_rayleigh_rst::cvt_each_field_from_rayleigh(), r_interpolate_sph_data::r_interpolate_sph_rst_from_io(), rayleigh_restart_io::set_rayleigh_restart_field(), rayleigh_restart_io::set_rayleigh_rst_file_name(), set_work_4_explicit_labels(), and t_explicit_term_labels::set_work_field_addresses().
previous_potential
type(field_def), parameter m_explicit_term_labels::previous_potential = field_def(n_comp = n_scalar, name = 'previous_potential', math = '$ \varphi^{N-1} $')
Field label for explicit term for potential at previous step.
Definition at line 120 of file m_explicit_term_labels.f90.
Referenced by check_scalar_work_field(), set_work_4_explicit_labels(), and t_explicit_term_labels::set_work_field_addresses().
previous_pressure
type(field_def), parameter m_explicit_term_labels::previous_pressure = field_def(n_comp = n_scalar, name = 'previous_pressure', math = '$ P^{N-1} $')
Field label for explicit term for pressure at previous step.
Definition at line 115 of file m_explicit_term_labels.f90.
Referenced by add_nodal_fields_4_mhd::add_data_4_previous_step(), check_scalar_work_field(), set_work_4_explicit_labels(), and t_explicit_term_labels::set_work_field_addresses().
rot_sum_forces
type(field_def), parameter m_explicit_term_labels::rot_sum_forces = field_def(n_comp = n_vector, name = 'rot_sum_forces', math = '$ e_{ijk} \partial_{j} F_{k} $')
Field label for curl of total forces.
Definition at line 81 of file m_explicit_term_labels.f90.
Referenced by check_vector_work_field(), set_work_4_explicit_labels(), and t_explicit_term_labels::set_work_field_addresses().
sum_forces
type(field_def), parameter m_explicit_term_labels::sum_forces = field_def(n_comp = n_vector, name = 'sum_forces', math = '$ F_{i} $')
Field label for total forces.
Definition at line 76 of file m_explicit_term_labels.f90.
Referenced by add_nodal_fields_4_mhd::add_data_4_previous_step(), check_vector_work_field(), set_work_4_explicit_labels(), and t_explicit_term_labels::set_work_field_addresses().