CALYPSO: field_data_io_b Module Reference
field_data_io_b Module Reference
Output merged binary field file using MPI-IO.
Functions/Subroutines
subroutine write_step_data_b (id_rank, t_IO, bbuf)
subroutine write_field_data_b (num_field, field_name, ncomp_field, nnod64, ntot_comp, d_nod, bbuf)
subroutine read_step_data_b (bbuf, t_IO, istack_merged, num_field)
subroutine read_field_data_b (bbuf, num_field, field_name, nnod64, ntot_comp, vect)
Detailed Description
Output merged binary field file using MPI-IO.
      subroutine write_step_data_b(id_rank, t_IO, bbuf)
      subroutine write_field_data_b(num_field, field_name,            &
     &          ncomp_field, nnod64, ntot_comp, d_nod, bbuf)
        type(time_data), intent(in) :: t_IO
        type(binary_IO_buffer), intent(inout) :: bbuf
      subroutine read_step_data_b                                     &
     &         (bbuf, t_IO, istack_merged, num_field)
      subroutine read_field_data_b                                    &
     &         (bbuf, num_field, field_name, nnod64, ntot_comp, vect)
        type(binary_IO_buffer), intent(inout) :: bbuf
        type(time_data), intent(inout) :: t_IO
Function/Subroutine Documentation
read_field_data_b()
subroutine field_data_io_b::read_field_data_b (type(binary_io_buffer), intent(inout) bbuf, integer(kind=kint), intent(in) num_field, character(len=kchara), dimension(num_field), intent(inout) field_name, integer(kind = kint_gl), intent(in) nnod64, integer(kind=kint), intent(in) ntot_comp, real(kind = kreal), dimension(nnod64,ntot_comp), intent(inout) vect)
Definition at line 133 of file field_data_IO_b.f90.
References binary_io::read_2d_vector_b(), and binary_io::read_mul_character_b().
Referenced by ucd_field_file_io_b::read_alloc_ucd_2_fld_file_b(), field_file_io_b::read_and_allocate_step_field_b(), field_file_io_b::read_step_field_file_b(), and ucd_field_file_io_b::read_ucd_2_fld_file_b().
read_step_data_b()
subroutine field_data_io_b::read_step_data_b (type(binary_io_buffer), intent(inout) bbuf, type(time_data), intent(inout) t_IO, integer(kind=kint_gl), dimension(1), intent(inout) istack_merged, integer(kind=kint), intent(inout) num_field)
Definition at line 101 of file field_data_IO_b.f90.
References binary_io::read_mul_int8_b(), binary_io::read_one_integer_b(), and binary_io::read_one_real_b().
Referenced by ucd_field_file_io_b::read_alloc_ucd_2_fld_file_b(), ucd_field_file_io_b::read_alloc_ucd_2_fld_header_b(), field_file_io_b::read_and_allocate_step_b(), field_file_io_b::read_step_field_file_b(), and ucd_field_file_io_b::read_ucd_2_fld_file_b().
write_field_data_b()
subroutine field_data_io_b::write_field_data_b (integer(kind=kint), intent(in) num_field, character(len=kchara), dimension(num_field), intent(in) field_name, integer(kind=kint), dimension(num_field), intent(in) ncomp_field, integer(kind=kint_gl), intent(in) nnod64, integer(kind=kint), intent(in) ntot_comp, real(kind = kreal), dimension(nnod64,ntot_comp), intent(in) d_nod, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 65 of file field_data_IO_b.f90.
References transfer_to_long_integers::cast_long(), binary_io::write_2d_vector_b(), binary_io::write_mul_character_b(), binary_io::write_mul_int8_b(), binary_io::write_mul_integer_b(), and binary_io::write_one_integer_b().
Referenced by field_file_io_b::write_step_field_file_b(), and ucd_field_file_io_b::write_ucd_2_fld_file_b().
write_step_data_b()
subroutine field_data_io_b::write_step_data_b (integer, intent(in) id_rank, type(time_data), intent(in) t_IO, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 42 of file field_data_IO_b.f90.
References binary_io::write_one_integer_b(), and binary_io::write_one_real_b().
Referenced by field_file_io_b::write_step_field_file_b(), and ucd_field_file_io_b::write_ucd_2_fld_file_b().