CALYPSO: set_edge_data_4_io Module Reference
set_edge_data_4_io Module Reference
Copy edge data between IO buffer.
Functions/Subroutines
subroutine copy_edge_connect_to_io (edge, nele, nsurf, ele_IO, sfed_IO)
subroutine copy_edge_geometry_to_io (edge, nod_IO, sfed_IO)
subroutine copy_edge_connect_from_io (ele_IO, sfed_IO, edge, nele, nsurf)
subroutine copy_edge_geometry_from_io (nod_IO, sfed_IO, edge)
Detailed Description
Copy edge data between IO buffer.
      subroutine copy_edge_connect_to_IO                              &
     &         (edge, nele, nsurf, ele_IO, sfed_IO)
      subroutine copy_edge_geometry_to_IO(edge, nod_IO, sfed_IO)
        type(edge_data), intent(inout) :: edge
        type(node_data), intent(inout) :: nod_IO
        type(element_data), intent(inout) :: ele_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
      subroutine copy_edge_connect_from_IO                            &
     &          (ele_IO, sfed_IO, edge, nele, nsurf)
      subroutine copy_edge_geometry_from_IO(nod_IO, sfed_IO, edge)
        type(node_data), intent(in) :: nod_IO
        type(element_data), intent(in) :: ele_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
        type(edge_data), intent(inout) :: edge
Function/Subroutine Documentation
copy_edge_connect_from_io()
subroutine set_edge_data_4_io::copy_edge_connect_from_io (type(element_data), intent(in) ele_IO, type(surf_edge_io_data), intent(in) sfed_IO, type(edge_data), intent(inout) edge, integer(kind = kint), intent(in) nele, integer(kind = kint), intent(in) nsurf)
Definition at line 135 of file set_edge_data_4_IO.f90.
References t_edge_data::alloc_edge_4_ele(), t_edge_data::alloc_edge_connect(), m_geometry_constants::nedge_4_ele, and m_geometry_constants::nedge_4_surf.
Referenced by load_element_mesh_data::set_edge_mesh_from_io().
copy_edge_connect_to_io()
subroutine set_edge_data_4_io::copy_edge_connect_to_io (type(edge_data), intent(in) edge, integer(kind = kint), intent(in) nele, integer(kind = kint), intent(in) nsurf, type(element_data), intent(inout) ele_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 46 of file set_edge_data_4_IO.f90.
References t_surf_edge_io::alloc_edge_connect_io(), t_surf_edge_io::alloc_surface_connect_io(), t_geometry_data::allocate_ele_connect_type(), m_geometry_constants::nedge_4_ele, m_geometry_constants::nedge_4_surf, m_geometry_constants::num_linear_edge, and m_geometry_constants::num_quad_edge.
Referenced by load_element_mesh_data::set_edge_mesh_to_io().
copy_edge_geometry_from_io()
subroutine set_edge_data_4_io::copy_edge_geometry_from_io (type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO, type(edge_data), intent(inout) edge)
Definition at line 172 of file set_edge_data_4_IO.f90.
References t_edge_data::alloc_edge_geometory().
copy_edge_geometry_to_io()
subroutine set_edge_data_4_io::copy_edge_geometry_to_io (type(edge_data), intent(in) edge, type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 101 of file set_edge_data_4_IO.f90.
References t_surf_edge_io::alloc_ele_scalar_io(), t_surf_edge_io::alloc_ele_vector_io(), and t_geometry_data::alloc_node_geometry_base().