CALYPSO: m_elapsed_labels_sph_trns Module Reference
m_elapsed_labels_sph_trns Module Reference
Labels for elapsed time monitor.
Functions/Subroutines
subroutine elpsed_label_4_sph_trns
subroutine elpsed_label_4_sph_detail
subroutine elpsed_label_4_fft_detail
subroutine elapsed_label_4_legendre_trans
subroutine reset_elapse_after_init_sph
subroutine reset_elapse_after_init_sdt
subroutine reset_elapse_after_init_fft
subroutine reset_elapse_after_init_leg
Variables
logical, save iflag_sph_time = .FALSE.
integer(kind=kint), save ist_elapsed_sph = 0
integer(kind=kint), save ied_elapsed_sph = 0
logical, save iflag_sdt_time = .FALSE.
integer(kind=kint), save ist_elapsed_sdt = 0
integer(kind=kint), save ied_elapsed_sdt = 0
logical, save iflag_fft_time = .FALSE.
integer(kind=kint), save ist_elapsed_fft = 0
integer(kind=kint), save ied_elapsed_fft = 0
logical, save iflag_leg_time = .FALSE.
integer(kind=kint), save ist_elapsed_leg = 0
integer(kind=kint), save ied_elapsed_leg = 0
Detailed Description
Labels for elapsed time monitor.
      subroutine elpsed_label_4_sph_trns
      subroutine elpsed_label_4_sph_detail
      subroutine elpsed_label_4_fft_detail
      subroutine elapsed_label_4_Legendre_trans
      subroutine reset_elapse_after_init_SPH
      subroutine reset_elapse_after_init_SDT
      subroutine reset_elapse_after_init_FFT
      subroutine reset_elapse_after_init_LEG
Function/Subroutine Documentation
elapsed_label_4_legendre_trans()
subroutine m_elapsed_labels_sph_trns::elapsed_label_4_legendre_trans
Definition at line 131 of file m_elapsed_labels_SPH_TRNS.f90.
References m_work_time::append_elapsed_times(), m_work_time::elps1, ied_elapsed_leg, iflag_leg_time, and ist_elapsed_leg.
elpsed_label_4_fft_detail()
subroutine m_elapsed_labels_sph_trns::elpsed_label_4_fft_detail
Definition at line 109 of file m_elapsed_labels_SPH_TRNS.f90.
References m_work_time::append_elapsed_times(), m_work_time::elps1, ied_elapsed_fft, iflag_fft_time, and ist_elapsed_fft.
Referenced by init_sph_mhd_elapsed_label::set_sph_mhd_elapsed_label().
elpsed_label_4_sph_detail()
subroutine m_elapsed_labels_sph_trns::elpsed_label_4_sph_detail
Definition at line 75 of file m_elapsed_labels_SPH_TRNS.f90.
References m_work_time::append_elapsed_times(), m_work_time::elps1, ied_elapsed_sdt, iflag_sdt_time, and ist_elapsed_sdt.
Referenced by init_sph_mhd_elapsed_label::set_sph_mhd_elapsed_label().
elpsed_label_4_sph_trns()
subroutine m_elapsed_labels_sph_trns::elpsed_label_4_sph_trns
Definition at line 51 of file m_elapsed_labels_SPH_TRNS.f90.
References m_work_time::append_elapsed_times(), m_work_time::elps1, ied_elapsed_sph, iflag_sph_time, and ist_elapsed_sph.
Referenced by init_sph_mhd_elapsed_label::set_sph_mhd_elapsed_label().
reset_elapse_after_init_fft()
subroutine m_elapsed_labels_sph_trns::reset_elapse_after_init_fft
Definition at line 187 of file m_elapsed_labels_SPH_TRNS.f90.
References ied_elapsed_fft, iflag_fft_time, ist_elapsed_fft, and m_work_time::reset_elapsed_times().
Referenced by init_sph_mhd_elapsed_label::reset_elapse_4_init_sph_mhd().
reset_elapse_after_init_leg()
subroutine m_elapsed_labels_sph_trns::reset_elapse_after_init_leg
Definition at line 197 of file m_elapsed_labels_SPH_TRNS.f90.
References iflag_leg_time, ist_elapsed_leg, and m_work_time::reset_elapsed_times().
Referenced by init_sph_mhd_elapsed_label::reset_elapse_4_init_sph_mhd().
reset_elapse_after_init_sdt()
subroutine m_elapsed_labels_sph_trns::reset_elapse_after_init_sdt
Definition at line 177 of file m_elapsed_labels_SPH_TRNS.f90.
References ied_elapsed_sdt, iflag_sdt_time, ist_elapsed_sdt, and m_work_time::reset_elapsed_times().
Referenced by init_sph_mhd_elapsed_label::reset_elapse_4_init_sph_mhd().
reset_elapse_after_init_sph()
subroutine m_elapsed_labels_sph_trns::reset_elapse_after_init_sph
Definition at line 167 of file m_elapsed_labels_SPH_TRNS.f90.
References ied_elapsed_sph, iflag_sph_time, ist_elapsed_sph, and m_work_time::reset_elapsed_times().
Referenced by init_sph_mhd_elapsed_label::reset_elapse_4_init_sph_mhd().
Variable Documentation
ied_elapsed_fft
integer(kind = kint), save m_elapsed_labels_sph_trns::ied_elapsed_fft = 0
Definition at line 39 of file m_elapsed_labels_SPH_TRNS.f90.
Referenced by elpsed_label_4_fft_detail(), and reset_elapse_after_init_fft().
ied_elapsed_leg
integer(kind = kint), save m_elapsed_labels_sph_trns::ied_elapsed_leg = 0
Definition at line 43 of file m_elapsed_labels_SPH_TRNS.f90.
Referenced by elapsed_label_4_legendre_trans().
ied_elapsed_sdt
integer(kind = kint), save m_elapsed_labels_sph_trns::ied_elapsed_sdt = 0
Definition at line 35 of file m_elapsed_labels_SPH_TRNS.f90.
Referenced by elpsed_label_4_sph_detail(), and reset_elapse_after_init_sdt().
ied_elapsed_sph
integer(kind = kint), save m_elapsed_labels_sph_trns::ied_elapsed_sph = 0
Definition at line 31 of file m_elapsed_labels_SPH_TRNS.f90.
Referenced by elpsed_label_4_sph_trns(), and reset_elapse_after_init_sph().
iflag_fft_time
logical, save m_elapsed_labels_sph_trns::iflag_fft_time = .FALSE.
Definition at line 37 of file m_elapsed_labels_SPH_TRNS.f90.
Referenced by elpsed_label_4_fft_detail(), sph_prt_fftw::prt_back_fftw_from_recv(), sph_prt_domain_fftpack5::prt_domain_rfftmb_from_recv(), sph_prt_domain_fftpack5::prt_domain_rfftmf_to_send(), sph_prt_domain_fftw::prt_field_back_fftw_from_recv(), sph_prt_domain_fftw::prt_field_fwd_fftw_to_send(), sph_prt_fftw::prt_fwd_fftw_to_send(), sph_prt_fftpack5::prt_rfftmb_from_recv(), sph_prt_fftpack5::prt_rfftmf_to_send(), reset_elapse_after_init_fft(), sph_rtp_fftw::rtp_back_fftw_from_recv(), sph_rtp_domain_fftpack5::rtp_domain_rfftmb_from_recv(), sph_rtp_domain_fftpack5::rtp_domain_rfftmf_to_send(), sph_rtp_domain_fftw::rtp_field_back_fftw_from_recv(), sph_rtp_domain_fftw::rtp_field_fwd_fftw_to_send(), sph_rtp_fftw::rtp_fwd_fftw_to_send(), sph_rtp_fftpack5::rtp_rfftmb_from_recv(), sph_rtp_fftpack5::rtp_rfftmf_to_send(), t_sph_component_fftw::sph_comp_back_fftw_from_recv(), t_sph_component_fftw::sph_comp_fwd_fftw_to_send(), t_sph_component_fftpack5::sph_comp_rfftmb_from_recv(), t_sph_component_fftpack5::sph_comp_rfftmf_to_send(), t_sph_single_fftw::sph_single_back_fftw_from_recv(), t_sph_single_fftw::sph_single_fwd_fftw_to_send(), t_sph_single_fftpack5::sph_single_rfftmb_from_recv(), and t_sph_single_fftpack5::sph_single_rfftmf_to_send().
iflag_leg_time
logical, save m_elapsed_labels_sph_trns::iflag_leg_time = .FALSE.
Definition at line 41 of file m_elapsed_labels_SPH_TRNS.f90.
Referenced by cal_sp_rlm_sym_mat_tsmp::cal_sp_rlm_sym_mat_rin(), elapsed_label_4_legendre_trans(), and reset_elapse_after_init_leg().
iflag_sdt_time
logical, save m_elapsed_labels_sph_trns::iflag_sdt_time = .FALSE.
Definition at line 33 of file m_elapsed_labels_SPH_TRNS.f90.
Referenced by elpsed_label_4_sph_detail(), leg_b_trans_sym_matmul_big::leg_bwd_trans_sym_matmul_big(), leg_f_trans_sym_matmul_big::leg_fwd_trans_sym_matmul_big(), leg_bwd_trans_on_the_fly::legendre_b_trans_on_the_fly(), leg_bwd_trans_sym_mat_jt::legendre_b_trans_sym_mat_jt(), leg_bwd_trans_sym_mat_tj::legendre_b_trans_sym_mat_tj(), legendre_bwd_trans_testloop::legendre_b_trans_vector_test(), leg_fwd_trans_on_the_fly::legendre_f_trans_on_the_fly(), leg_fwd_trans_sym_mat_jt::legendre_f_trans_sym_mat_jt(), leg_fwd_trans_sym_mat_tj::legendre_f_trans_sym_mat_tj(), legendre_fwd_trans_testloop::legendre_f_trans_vector_test(), and reset_elapse_after_init_sdt().
iflag_sph_time
logical, save m_elapsed_labels_sph_trns::iflag_sph_time = .FALSE.
Definition at line 29 of file m_elapsed_labels_SPH_TRNS.f90.
Referenced by elpsed_label_4_sph_trns(), t_sph_transforms::pole_b_transform(), reset_elapse_after_init_sph(), sph_trans_w_coriols::sph_b_trans_licv(), sph_trans_w_coriols::sph_b_trans_w_coriolis(), t_sph_transforms::sph_b_trans_w_poles(), sph_transforms_4_mhd::sph_back_trans_4_mhd(), t_sph_transforms::sph_backward_transforms(), sph_trans_w_coriols::sph_f_trans_licv(), sph_trans_w_coriols::sph_f_trans_w_coriolis(), sph_transforms_4_mhd::sph_forward_trans_4_mhd(), and t_sph_transforms::sph_forward_transforms().
ist_elapsed_fft
integer(kind = kint), save m_elapsed_labels_sph_trns::ist_elapsed_fft = 0
Definition at line 38 of file m_elapsed_labels_SPH_TRNS.f90.
Referenced by elpsed_label_4_fft_detail(), sph_prt_fftw::prt_back_fftw_from_recv(), sph_prt_domain_fftpack5::prt_domain_rfftmb_from_recv(), sph_prt_domain_fftpack5::prt_domain_rfftmf_to_send(), sph_prt_domain_fftw::prt_field_back_fftw_from_recv(), sph_prt_domain_fftw::prt_field_fwd_fftw_to_send(), sph_prt_fftw::prt_fwd_fftw_to_send(), sph_prt_fftpack5::prt_rfftmb_from_recv(), sph_prt_fftpack5::prt_rfftmf_to_send(), reset_elapse_after_init_fft(), sph_rtp_fftw::rtp_back_fftw_from_recv(), sph_rtp_domain_fftpack5::rtp_domain_rfftmb_from_recv(), sph_rtp_domain_fftpack5::rtp_domain_rfftmf_to_send(), sph_rtp_domain_fftw::rtp_field_back_fftw_from_recv(), sph_rtp_domain_fftw::rtp_field_fwd_fftw_to_send(), sph_rtp_fftw::rtp_fwd_fftw_to_send(), sph_rtp_fftpack5::rtp_rfftmb_from_recv(), sph_rtp_fftpack5::rtp_rfftmf_to_send(), t_sph_component_fftw::sph_comp_back_fftw_from_recv(), t_sph_component_fftw::sph_comp_fwd_fftw_to_send(), t_sph_component_fftpack5::sph_comp_rfftmb_from_recv(), t_sph_component_fftpack5::sph_comp_rfftmf_to_send(), t_sph_single_fftw::sph_single_back_fftw_from_recv(), t_sph_single_fftw::sph_single_fwd_fftw_to_send(), t_sph_single_fftpack5::sph_single_rfftmb_from_recv(), and t_sph_single_fftpack5::sph_single_rfftmf_to_send().
ist_elapsed_leg
integer(kind = kint), save m_elapsed_labels_sph_trns::ist_elapsed_leg = 0
Definition at line 42 of file m_elapsed_labels_SPH_TRNS.f90.
Referenced by cal_sp_rlm_sym_mat_tsmp::cal_sp_rlm_sym_mat_rin(), elapsed_label_4_legendre_trans(), and reset_elapse_after_init_leg().
ist_elapsed_sdt
integer(kind = kint), save m_elapsed_labels_sph_trns::ist_elapsed_sdt = 0
Definition at line 34 of file m_elapsed_labels_SPH_TRNS.f90.
Referenced by elpsed_label_4_sph_detail(), leg_b_trans_sym_matmul_big::leg_bwd_trans_sym_matmul_big(), leg_f_trans_sym_matmul_big::leg_fwd_trans_sym_matmul_big(), leg_bwd_trans_on_the_fly::legendre_b_trans_on_the_fly(), leg_bwd_trans_sym_mat_jt::legendre_b_trans_sym_mat_jt(), leg_bwd_trans_sym_mat_tj::legendre_b_trans_sym_mat_tj(), legendre_bwd_trans_testloop::legendre_b_trans_vector_test(), leg_fwd_trans_on_the_fly::legendre_f_trans_on_the_fly(), leg_fwd_trans_sym_mat_jt::legendre_f_trans_sym_mat_jt(), leg_fwd_trans_sym_mat_tj::legendre_f_trans_sym_mat_tj(), legendre_fwd_trans_testloop::legendre_f_trans_vector_test(), and reset_elapse_after_init_sdt().
ist_elapsed_sph
integer(kind = kint), save m_elapsed_labels_sph_trns::ist_elapsed_sph = 0
Definition at line 30 of file m_elapsed_labels_SPH_TRNS.f90.
Referenced by elpsed_label_4_sph_trns(), t_sph_transforms::pole_b_transform(), reset_elapse_after_init_sph(), sph_trans_w_coriols::sph_b_trans_licv(), sph_trans_w_coriols::sph_b_trans_w_coriolis(), t_sph_transforms::sph_b_trans_w_poles(), sph_transforms_4_mhd::sph_back_trans_4_mhd(), t_sph_transforms::sph_backward_transforms(), sph_trans_w_coriols::sph_f_trans_licv(), sph_trans_w_coriols::sph_f_trans_w_coriolis(), sph_transforms_4_mhd::sph_forward_trans_4_mhd(), and t_sph_transforms::sph_forward_transforms().