CALYPSO: compare_by_assemble_sph Module Reference
compare_by_assemble_sph Module Reference
functions to compare assembled data
Functions/Subroutines
integer(kind=kint) function compare_assembled_sph_data (my_rank, time_d, new_sph, new_phys, new_fst_IO, t_IO)
integer(kind=kint) function compare_rj_phys_data_with_io (my_rank, rj_fld, fld_IO)
integer(kind=kint) function compare_each_sph_solnid_with_io (rj_fld, fld_IO, i_fld, j_IO)
integer(kind=kint) function compare_each_sph_vector_with_io (rj_fld, fld_IO, i_fld, j_IO)
integer(kind=kint) function compare_each_sph_field_with_io (rj_fld, fld_IO, i_fld, j_IO)
integer(kind=kint) function compare_rj_phys_name_with_io (rj_fld, fld_IO)
integer(kind=kint) function compare_time_step_with_io (time_org, time_IO)
Detailed Description
functions to compare assembled data
      integer(kind = kint) function compare_assembled_sph_data        &
     &          (my_rank, time_d, new_sph, new_phys, new_fst_IO, t_IO)
        type(time_data), intent(in) :: time_d
        type(sph_grids), intent(in) :: new_sph
        type(phys_data), intent(inout) :: new_phys
        type(field_IO), intent(inout) :: new_fst_IO
        type(time_data), intent(inout) :: t_IO
Function/Subroutine Documentation
compare_assembled_sph_data()
integer(kind = kint) function compare_by_assemble_sph::compare_assembled_sph_data (integer, intent(in) my_rank, type(time_data), intent(in) time_d, type(sph_grids), intent(in) new_sph, type(phys_data), intent(inout) new_phys, type(field_io), intent(inout) new_fst_IO, type(time_data), intent(inout) t_IO)
Definition at line 38 of file compare_by_assemble_sph.f90.
References compare_rj_phys_data_with_io(), compare_rj_phys_name_with_io(), compare_time_step_with_io(), and calypso_mpi::my_rank.
Referenced by analyzer_compare_sph_rst::analyze_compare_sph_restart().
compare_each_sph_field_with_io()
integer(kind = kint) function compare_by_assemble_sph::compare_each_sph_field_with_io (type(phys_data), intent(in) rj_fld, type(field_io), intent(in) fld_IO, integer(kind = kint), intent(in) i_fld, integer(kind = kint), intent(in) j_IO)
Definition at line 171 of file compare_by_assemble_sph.f90.
Referenced by compare_rj_phys_data_with_io().
compare_each_sph_solnid_with_io()
integer(kind = kint) function compare_by_assemble_sph::compare_each_sph_solnid_with_io (type(phys_data), intent(in) rj_fld, type(field_io), intent(in) fld_IO, integer(kind = kint), intent(in) i_fld, integer(kind = kint), intent(in) j_IO)
Definition at line 115 of file compare_by_assemble_sph.f90.
compare_each_sph_vector_with_io()
integer(kind = kint) function compare_by_assemble_sph::compare_each_sph_vector_with_io (type(phys_data), intent(in) rj_fld, type(field_io), intent(in) fld_IO, integer(kind = kint), intent(in) i_fld, integer(kind = kint), intent(in) j_IO)
Definition at line 142 of file compare_by_assemble_sph.f90.
Referenced by compare_rj_phys_data_with_io().
compare_rj_phys_data_with_io()
integer(kind = kint) function compare_by_assemble_sph::compare_rj_phys_data_with_io (integer, intent(in) my_rank, type(phys_data), intent(in) rj_fld, type(field_io), intent(in) fld_IO)
Definition at line 82 of file compare_by_assemble_sph.f90.
References compare_each_sph_field_with_io(), compare_each_sph_vector_with_io(), and calypso_mpi::my_rank.
Referenced by compare_assembled_sph_data().
compare_rj_phys_name_with_io()
integer(kind = kint) function compare_by_assemble_sph::compare_rj_phys_name_with_io (type(phys_data), intent(in) rj_fld, type(field_io), intent(in) fld_IO)
Definition at line 199 of file compare_by_assemble_sph.f90.
Referenced by compare_assembled_sph_data().
compare_time_step_with_io()
integer(kind = kint) function compare_by_assemble_sph::compare_time_step_with_io (type(time_data), intent(in) time_org, type(time_data), intent(in) time_IO)
Definition at line 225 of file compare_by_assemble_sph.f90.
Referenced by compare_assembled_sph_data().