CALYPSO: t_circle_transform Module Reference
t_circle_transform Module Reference
spherical transform at a specific circle at \((r, theta)\)
Data Types
type circle_transform_spetr
type fields_on_circle
Structure to make fields on circle.
Functions/Subroutines
subroutine alloc_circle_transform (ltr, circ_spec)
subroutine alloc_circle_field (mphi_rtp, nidx_global_jmax, circle, d_circle)
subroutine dealloc_circle_transform (circ_spec)
subroutine dealloc_circle_field (circle, d_circle)
Variables
integer(kind=kint), parameter iflag_circle_sph = 1
Use spherical coordinate for circle data.
integer(kind=kint), parameter iflag_circle_cyl = 2
Use Cylindrical coordinate for circle data.
Detailed Description
spherical transform at a specific circle at \((r, theta)\)
      subroutine alloc_circle_transform(ltr, circ_spec)
      subroutine alloc_circle_field(mphi_rtp, nidx_global_jmax,       &
     &          circle, d_circle)
      subroutine dealloc_circle_transform
      subroutine dealloc_circle_field(circle, d_circle)
Parameters
ltr Truncation of spherical harmonics
jmax Number of modes for harmonincs except for 0 degree
d_rj_circle(0:jmax,3) Spectr field data
numdir Number of components of field
v_rtp_circle(mphi_circle,numdir) Field along circle
vrtm_mag(0:mphi_circle,numdir) Amplitude of spectrum data along with the circle
vrtm_phase(0:mphi_circle,numdir) Phase of spectrum data along with the circle
Function/Subroutine Documentation
alloc_circle_field()
subroutine t_circle_transform::alloc_circle_field (integer(kind = kint), intent(in) mphi_rtp, integer(kind = kint), intent(in) nidx_global_jmax, type(fields_on_circle), intent(inout) circle, type(phys_data), intent(inout) d_circle)
Definition at line 145 of file t_circle_transform.f90.
References t_phys_data::alloc_phys_data_type(), m_constants::izero, and calypso_mpi::my_rank.
Referenced by t_field_on_circle::const_circle_point_global().
alloc_circle_transform()
subroutine t_circle_transform::alloc_circle_transform (integer(kind = kint), intent(in) ltr, type(circle_transform_spetr), intent(inout) circ_spec)
Definition at line 120 of file t_circle_transform.f90.
References m_machine_parameter::np_smp, and m_constants::zero.
Referenced by t_field_on_circle::const_circle_point_global().
dealloc_circle_field()
subroutine t_circle_transform::dealloc_circle_field (type(fields_on_circle), intent(inout) circle, type(phys_data), intent(inout) d_circle)
Definition at line 201 of file t_circle_transform.f90.
References t_phys_data::dealloc_phys_data_type(), t_phys_data::dealloc_phys_name_type(), and calypso_mpi::my_rank.
dealloc_circle_transform()
subroutine t_circle_transform::dealloc_circle_transform (type(circle_transform_spetr), intent(inout) circ_spec)
Definition at line 188 of file t_circle_transform.f90.
Variable Documentation
iflag_circle_cyl
integer(kind = kint), parameter t_circle_transform::iflag_circle_cyl = 2
Use Cylindrical coordinate for circle data.
Definition at line 40 of file t_circle_transform.f90.
Referenced by circle_transform_single::circle_transfer_vector().
iflag_circle_sph
integer(kind = kint), parameter t_circle_transform::iflag_circle_sph = 1
Use spherical coordinate for circle data.
Definition at line 38 of file t_circle_transform.f90.
Referenced by input_control_dynamobench::set_ctl_params_dynamobench().