CALYPSO: t_work_4_sph_trans_spin Module Reference
t_work_4_sph_trans_spin Module Reference
Field data for Legendre transform (innermost loop is spherical harmonics)
Data Types
type leg_trns_spin_work
Work structure for Legendre trasform.
Functions/Subroutines
subroutine alloc_work_sph_trans (ncomp, nnod_rtm, nnod_rlm, WK_spin)
subroutine dealloc_work_sph_trans (WK_spin)
subroutine clear_fwd_legendre_work (ncomp, nnod_rlm, WK_spin)
subroutine clear_bwd_legendre_work (ncomp, nnod_rtm, WK_spin)
Detailed Description
Field data for Legendre transform (innermost loop is spherical harmonics)
      subroutine alloc_work_sph_trans                                 &
     &         (ncomp, nnod_rtm, nnod_rlm, WK_spin)
      subroutine dealloc_work_sph_trans(WK_spin)
      subroutine clear_fwd_legendre_work(ncomp, nnod_rlm, WK_spin)
      subroutine clear_bwd_legendre_work(ncomp, nnod_rtm, WK_spin)
    Data for single vector field
      radial component:      vr_rtm_wk(3*i_rtm-2)
      elevetional component: vr_rtm_wk(3*i_rtm-1)
      azimuthal component:   vr_rtm_wk(3*i_rtm  )
    Data for single vector spectrum
      Poloidal component:          sp_rlm_wk(3*i_rlm-2)
      diff. of Poloidal component: sp_rlm_wk(3*i_rlm-1)
      Toroidal component:          sp_rlm_wk(3*i_rlm  )
    Data for single scalar
      field: vr_rtm_wk(i_rtm)
      spectr: sp_rlm_wk(i_rlm)
Parameters
ncomp number of components for Legendre transform
icomp_st start component to clear
icomp_ed end component to clear
Function/Subroutine Documentation
alloc_work_sph_trans()
subroutine t_work_4_sph_trans_spin::alloc_work_sph_trans (integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nnod_rtm, integer(kind = kint), intent(in) nnod_rlm, type(leg_trns_spin_work), intent(inout) WK_spin)
Definition at line 62 of file t_work_4_sph_trans_spin.f90.
References clear_bwd_legendre_work(), and clear_fwd_legendre_work().
Referenced by init_spherical_srs::init_sph_send_recv_n().
clear_bwd_legendre_work()
subroutine t_work_4_sph_trans_spin::clear_bwd_legendre_work (integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nnod_rtm, type(leg_trns_spin_work), intent(inout) WK_spin)
Definition at line 109 of file t_work_4_sph_trans_spin.f90.
Referenced by alloc_work_sph_trans().
clear_fwd_legendre_work()
subroutine t_work_4_sph_trans_spin::clear_fwd_legendre_work (integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nnod_rlm, type(leg_trns_spin_work), intent(inout) WK_spin)
Definition at line 92 of file t_work_4_sph_trans_spin.f90.
Referenced by alloc_work_sph_trans().
dealloc_work_sph_trans()
subroutine t_work_4_sph_trans_spin::dealloc_work_sph_trans (type(leg_trns_spin_work), intent(inout) WK_spin)
Definition at line 81 of file t_work_4_sph_trans_spin.f90.
Referenced by init_spherical_srs::init_sph_send_recv_n().