CALYPSO: volume_average_4_sph Module Reference
volume_average_4_sph Module Reference
Output mean square of spectr data.
Functions/Subroutines
subroutine cal_volume_average_sph (sph_rj, rj_fld, pwr)
subroutine, private cal_sphere_average_sph (sph_rj, rj_fld, pwr)
subroutine, private averaging_4_sph_ave_int (ntot_rms_rj, avol, ave_sph_vol)
subroutine, private cal_ave_scalar_sph_spectr (icomp, jcomp, n_point, nidx_rj, idx_rj_degree_zero, inod_rj_center, ntot_phys_rj, d_rj, radius_1d_rj_r, nri_ave, ntot_rms_rj, ave_sph)
subroutine, private cal_ave_vector_sph_spectr (icomp, jcomp, n_point, nidx_rj, idx_rj_degree_zero, inod_rj_center, ntot_phys_rj, d_rj, radius_1d_rj_r, nri_ave, ntot_rms_rj, ave_sph)
subroutine ave_one_scalar_sph_spectr (icomp, nidx_rj, idx_rj_degree_zero, inod_rj_center, rj_fld, radius_1d_rj_r, nri_ave, nave, iave, ave)
Detailed Description
Output mean square of spectr data.
      subroutine cal_volume_average_sph(sph_rj, rj_fld, pwr)
        type(sph_rj_grid), intent(in) :: sph_rj
        type(phys_data), intent(in) :: rj_fld
        type(sph_mean_squares), intent(inout) :: pwr
      subroutine ave_one_scalar_sph_spectr                            &
     &         (icomp, nidx_rj, idx_rj_degree_zero, inod_rj_center,   &
     &          rj_fld, radius_1d_rj_r, nri_ave, nave, iave, ave)
        type(phys_data), intent(in) :: rj_fld
Parameters
istep time step number
time time
Function/Subroutine Documentation
ave_one_scalar_sph_spectr()
subroutine volume_average_4_sph::ave_one_scalar_sph_spectr (integer(kind = kint), intent(in) icomp, integer(kind = kint), dimension(2), intent(in) nidx_rj, integer(kind = kint), intent(in) idx_rj_degree_zero, integer(kind = kint), intent(in) inod_rj_center, type(phys_data), intent(in) rj_fld, real(kind = kreal), dimension(nidx_rj(1)), intent(in) radius_1d_rj_r, integer(kind = kint), intent(in) nri_ave, integer(kind = kint), intent(in) nave, integer(kind = kint), intent(in) iave, real(kind = kreal), dimension(0:nri_ave,nave), intent(inout) ave)
Definition at line 213 of file volume_average_4_sph.f90.
averaging_4_sph_ave_int()
subroutine, private volume_average_4_sph::averaging_4_sph_ave_int (integer(kind = kint), intent(in) ntot_rms_rj, real(kind = kreal), intent(in) avol, real(kind = kreal), dimension(ntot_rms_rj), intent(inout) ave_sph_vol) private
Definition at line 118 of file volume_average_4_sph.f90.
Referenced by cal_volume_average_sph().
cal_ave_scalar_sph_spectr()
subroutine, private volume_average_4_sph::cal_ave_scalar_sph_spectr (integer(kind = kint), intent(in) icomp, integer(kind = kint), intent(in) jcomp, integer(kind = kint), intent(in) n_point, integer(kind = kint), dimension(2), intent(in) nidx_rj, integer(kind = kint), intent(in) idx_rj_degree_zero, integer(kind = kint), intent(in) inod_rj_center, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(n_point,ntot_phys_rj), intent(in) d_rj, real(kind = kreal), dimension(nidx_rj(1)), intent(in) radius_1d_rj_r, integer(kind = kint), intent(in) nri_ave, integer(kind = kint), intent(in) ntot_rms_rj, real(kind = kreal), dimension(0:nri_ave,ntot_rms_rj), intent(inout) ave_sph) private
Definition at line 140 of file volume_average_4_sph.f90.
Referenced by cal_sphere_average_sph().
cal_ave_vector_sph_spectr()
subroutine, private volume_average_4_sph::cal_ave_vector_sph_spectr (integer(kind = kint), intent(in) icomp, integer(kind = kint), intent(in) jcomp, integer(kind = kint), intent(in) n_point, integer(kind = kint), dimension(2), intent(in) nidx_rj, integer(kind = kint), intent(in) idx_rj_degree_zero, integer(kind = kint), intent(in) inod_rj_center, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(n_point,ntot_phys_rj), intent(in) d_rj, real(kind = kreal), dimension(nidx_rj(1)), intent(in) radius_1d_rj_r, integer(kind = kint), intent(in) nri_ave, integer(kind = kint), intent(in) ntot_rms_rj, real(kind = kreal), dimension(0:nri_ave,ntot_rms_rj), intent(inout) ave_sph) private
Definition at line 174 of file volume_average_4_sph.f90.
References m_constants::zero.
Referenced by cal_sphere_average_sph().
cal_sphere_average_sph()
subroutine, private volume_average_4_sph::cal_sphere_average_sph (type(sph_rj_grid), intent(in) sph_rj, type(phys_data), intent(in) rj_fld, type(sph_mean_squares), intent(inout) pwr) private
Definition at line 77 of file volume_average_4_sph.f90.
References cal_ave_scalar_sph_spectr(), cal_ave_vector_sph_spectr(), m_phys_constants::n_scalar, and m_phys_constants::n_vector.
Referenced by cal_volume_average_sph().
cal_volume_average_sph()
subroutine volume_average_4_sph::cal_volume_average_sph (type(sph_rj_grid), intent(in) sph_rj, type(phys_data), intent(in) rj_fld, type(sph_mean_squares), intent(inout) pwr)
Definition at line 42 of file volume_average_4_sph.f90.
References averaging_4_sph_ave_int(), cal_sphere_average_sph(), m_constants::izero, and radial_int_for_sph_spec::radial_integration().
Referenced by cal_rms_fields_by_sph::cal_mean_squre_in_shell().