CALYPSO: m_field_file_format Module Reference
m_field_file_format Module Reference
Integer flags for field data file format.
Functions/Subroutines
integer(kind=kint) function choose_para_fld_file_format (file_fmt_ctl, i_file_fmt)
integer(kind=kint) function choose_ucd_file_format (file_fmt_ctl, i_file_fmt)
Variables
integer(kind=kint), parameter iflag_ascii = id_ascii_file_fmt
Integer flag for origianl ascii data format.
integer(kind=kint), parameter iflag_bin = id_binary_file_fmt
Integer flag for origianl binary data format.
integer(kind=kint), parameter iflag_gzip = id_gzip_txt_file_fmt
Integer flag for origianl gzipped ascii data format.
integer(kind=kint), parameter iflag_bin_gz = id_gzip_bin_file_fmt
Integer flag for gzipped binary data.
integer(kind=kint), parameter iflag_fld = 0
Integer flag for origianl ascii data format.
integer(kind=kint), parameter iflag_ucd = 10
Integer flag for UCD data.
integer(kind=kint), parameter iflag_udt = 20
Integer flag for UCD data (Separated by FEM mesh part and field part)
integer(kind=kint), parameter iflag_vtk = 30
Integer flag for VTK data.
integer(kind=kint), parameter iflag_vtd = 40
Integer flag for VTK data (Separated by FEM mesh part and field part)
integer(kind=kint), parameter iflag_ucd_bin = 70
Integer flag for binary surface data.
integer(kind=kint), parameter iflag_udt_bin = 80
Integer flag for binary section data (Separated by FEM mesh part and field part)
integer(kind=kint), parameter iflag_sgl_bin = 101
Integer flag for merged binary data.
integer(kind=kint), parameter iflag_sgl_ucd_bin = 170
Integer flag for merged binary surface data.
integer(kind=kint), parameter iflag_sgl_udt_bin = 180
Integer flag for merged binary section data.
integer(kind=kint), parameter iflag_sgl_ucd = 110
Integer flag for merged UCD data.
integer(kind=kint), parameter iflag_sgl_udt = 120
Integer flag for merged UCD data (Separated by FEM mesh part and field part)
integer(kind=kint), parameter iflag_sgl_vtk = 130
Integer flag for merged VTK data.
integer(kind=kint), parameter iflag_sgl_vtd = 140
Integer flag for merged VTK data (Separated by FEM mesh part and field part)
integer(kind=kint), parameter iflag_sgl_hdf5 = 150
Integer flag for HDF file data.
integer(kind=kint), parameter iflag_sgl_bin_gz = 102
Integer flag for merged gzipped binary data.
integer(kind=kint), parameter iflag_sgl_gz = 103
Integer flag for merged gzipped binary data.
integer(kind=kint), parameter iflag_fld_gz = 3
Integer flag for gzipped ascii original data.
integer(kind=kint), parameter iflag_ucd_gz = 13
Integer flag for gzipped UCD data.
integer(kind=kint), parameter iflag_udt_gz = 23
Integer flag for gzipped UCD data (Separated by FEM mesh part and field part)
integer(kind=kint), parameter iflag_vtk_gz = 33
Integer flag for gzipped VTK data.
integer(kind=kint), parameter iflag_vtd_gz = 43
Integer flag for gzipped VTK data (Separated by FEM mesh part and field part)
integer(kind=kint), parameter iflag_ucd_bin_gz = 73
Integer flag for gzipped binary surface data.
integer(kind=kint), parameter iflag_udt_bin_gz = 83
Integer flag for gzipped binary section data (Separated by FEM mesh part and field part)
integer(kind=kint), parameter iflag_sgl_ucd_bin_gz = 173
Integer flag for gzipped merged binary surface data.
integer(kind=kint), parameter iflag_sgl_udt_bin_gz = 183
Integer flag for gzipped merged binary section data.
integer(kind=kint), parameter iflag_sgl_ucd_gz = 113
Integer flag for merged gzipped UCD data.
integer(kind=kint), parameter iflag_sgl_udt_gz = 123
Integer flag for merged gzipped UCD data (Separated by FEM mesh part and field part)
integer(kind=kint), parameter iflag_sgl_vtk_gz = 133
Integer flag for merged amd gzipped VTK data.
integer(kind=kint), parameter iflag_sgl_vtd_gz = 143
Integer flag for merged amd gzipped VTK data (Separated by FEM mesh part and field part)
Detailed Description
Integer flags for field data file format.
      integer(kind = kint) function choose_para_fld_file_format       &
     &                            (file_fmt_ctl, i_file_fmt)
      integer(kind = kint) function choose_ucd_file_format            &
     &                            (file_fmt_ctl, i_file_fmt)
 ------------------------------------------------------------------
   flag lists for field data
  Distributed data file
   ASCII   data file
     UCD file:             ucd
     splitted UCD file:    udt
     VTK file:             vtk
     splitted VTK file:    vtd
   BINARY  data file
     splitted file:        binary
   GZIPPED data file
     UCD file:             ucd_gzip
     splitted UCD file:    udt_gzip
     VTK file:             vtk_gzip
     splitted VTK file:    vtd_gzip
  Merged data file
   ASCII   data file
     UCD file:             merged_ucd
     splitted UCD file:    merged_udt
     VTK file:             merged_vtk
     splitted VTK file:    merged_vtd
     HDF5 file:            HDF5
   GZIPPED data file
     UCD file:             merged_ucd_gzip
     splitted UCD file:    merged_udt_gzip
     VTK file:             merged_vtk_gzip
     splitted VTK file:    merged_vtd_gzip
 ------------------------------------------------------------------
Parameters
file_fmt_ctl file format name (see above)
i_file_fmt integer flag if file format is read
id_field_file_format integer flag for file format
Function/Subroutine Documentation
choose_para_fld_file_format()
integer(kind = kint) function m_field_file_format::choose_para_fld_file_format (character(len=kchara), intent(in) file_fmt_ctl, integer(kind= kint), intent(in) i_file_fmt)
Definition at line 163 of file m_field_file_format.f90.
References t_multi_flag_labels::check_mul_flags(), choose_ucd_file_format(), m_merged_field_fmt_labels::dealloc_mgd_field_type_flags(), iflag_sgl_bin, iflag_sgl_bin_gz, iflag_sgl_gz, iflag_sgl_hdf5, iflag_sgl_ucd, iflag_sgl_ucd_gz, iflag_sgl_udt, iflag_sgl_udt_gz, iflag_sgl_vtd, iflag_sgl_vtd_gz, iflag_sgl_vtk, iflag_sgl_vtk_gz, m_file_format_switch::iflag_single, m_merged_field_fmt_labels::init_mgd_field_type_flags(), m_merged_field_fmt_labels::mgd_fbin_gz_labels, m_merged_field_fmt_labels::mgd_fld_ascii_labels, m_merged_field_fmt_labels::mgd_fld_bin_labels, m_merged_field_fmt_labels::mgd_fld_gz_labels, m_merged_field_fmt_labels::mgd_hdf_labels, m_merged_field_fmt_labels::mgd_ucd_gz_labels, m_merged_field_fmt_labels::mgd_ucd_labels, m_merged_field_fmt_labels::mgd_udt_gz_labels, m_merged_field_fmt_labels::mgd_udt_labels, m_merged_field_fmt_labels::mgd_vtd_gz_labels, m_merged_field_fmt_labels::mgd_vtd_labels, m_merged_field_fmt_labels::mgd_vtk_gz_labels, and m_merged_field_fmt_labels::mgd_vtk_labels.
Referenced by t_viz_vtk_convert::init_visualize_convert_vtk(), and parallel_ucd_io_select::set_merged_ucd_file_ctl().
choose_ucd_file_format()
integer(kind = kint) function m_field_file_format::choose_ucd_file_format (character(len=kchara), intent(in) file_fmt_ctl, integer(kind= kint), intent(in) i_file_fmt)
Definition at line 236 of file m_field_file_format.f90.
References t_multi_flag_labels::check_mul_flags(), m_field_file_format_labels::fbin_gz_labels, m_field_file_format_labels::field_ascii_labels, m_field_file_format_labels::field_bin_labels, m_field_file_format_labels::field_gz_labels, iflag_bin, iflag_bin_gz, iflag_fld, iflag_gzip, iflag_ucd, iflag_udt, iflag_vtd, iflag_vtk, m_field_file_format_labels::ucd_flags, m_field_file_format_labels::ucd_gz_flags, m_field_file_format_labels::udt_flags, m_field_file_format_labels::udt_gz_flags, m_field_file_format_labels::vtd_flags, m_field_file_format_labels::vtd_gz_flags, m_field_file_format_labels::vtk_flags, and m_field_file_format_labels::vtk_gz_flags.
Referenced by choose_para_fld_file_format(), and ucd_io_select::set_ucd_file_define().
Variable Documentation
iflag_ascii
integer(kind = kint), parameter m_field_file_format::iflag_ascii = id_ascii_file_fmt
Integer flag for origianl ascii data format.
Definition at line 66 of file m_field_file_format.f90.
Referenced by ucd_io_select::sel_write_grd_file(), and set_ucd_file_names::set_parallel_ucd_file_name().
iflag_bin
integer(kind = kint), parameter m_field_file_format::iflag_bin = id_binary_file_fmt
Integer flag for origianl binary data format.
Definition at line 69 of file m_field_file_format.f90.
Referenced by choose_ucd_file_format(), ucd_io_select::sel_read_alloc_udt_file(), ucd_io_select::sel_read_udt_file(), ucd_io_select::sel_read_udt_param(), ucd_io_select::sel_write_grd_file(), ucd_io_select::sel_write_ucd_file(), ucd_io_select::sel_write_udt_file(), and set_ucd_file_names::set_parallel_ucd_file_name().
iflag_bin_gz
integer(kind = kint), parameter m_field_file_format::iflag_bin_gz = id_gzip_bin_file_fmt
Integer flag for gzipped binary data.
Definition at line 75 of file m_field_file_format.f90.
Referenced by choose_ucd_file_format(), ucd_io_select::sel_read_alloc_udt_file(), ucd_io_select::sel_read_udt_file(), ucd_io_select::sel_read_udt_param(), ucd_io_select::sel_write_grd_file(), ucd_io_select::sel_write_ucd_file(), ucd_io_select::sel_write_udt_file(), and set_ucd_file_names::set_parallel_ucd_file_name().
iflag_fld
integer(kind = kint), parameter m_field_file_format::iflag_fld = 0
Integer flag for origianl ascii data format.
Definition at line 79 of file m_field_file_format.f90.
Referenced by choose_ucd_file_format().
iflag_fld_gz
integer(kind = kint), parameter m_field_file_format::iflag_fld_gz = 3
Integer flag for gzipped ascii original data.
Definition at line 123 of file m_field_file_format.f90.
Referenced by ucd_io_select::sel_read_alloc_udt_file(), ucd_io_select::sel_read_udt_file(), ucd_io_select::sel_read_udt_param(), ucd_io_select::sel_write_grd_file(), ucd_io_select::sel_write_ucd_file(), ucd_io_select::sel_write_udt_file(), and set_ucd_file_names::set_parallel_ucd_file_name().
iflag_gzip
integer(kind = kint), parameter m_field_file_format::iflag_gzip = id_gzip_txt_file_fmt
Integer flag for origianl gzipped ascii data format.
Definition at line 72 of file m_field_file_format.f90.
Referenced by choose_ucd_file_format(), set_ucd_file_names::set_parallel_grd_file_name(), set_ucd_file_names::set_parallel_ucd_file_name(), set_ucd_file_names::set_single_grd_file_name(), and set_ucd_file_names::set_single_ucd_file_name().
iflag_sgl_bin
integer(kind = kint), parameter m_field_file_format::iflag_sgl_bin = 101
Integer flag for merged binary data.
Definition at line 98 of file m_field_file_format.f90.
Referenced by choose_para_fld_file_format(), parallel_ucd_io_select::sel_read_alloc_para_udt_file(), parallel_ucd_io_select::sel_read_parallel_udt_file(), parallel_ucd_io_select::sel_write_parallel_ucd_file(), and parallel_ucd_io_select::sel_write_parallel_ucd_mesh().
iflag_sgl_bin_gz
integer(kind = kint), parameter m_field_file_format::iflag_sgl_bin_gz = 102
Integer flag for merged gzipped binary data.
Definition at line 118 of file m_field_file_format.f90.
Referenced by choose_para_fld_file_format(), parallel_ucd_io_select::sel_read_alloc_para_udt_file(), parallel_ucd_io_select::sel_read_parallel_udt_file(), parallel_ucd_io_select::sel_write_parallel_ucd_file(), and parallel_ucd_io_select::sel_write_parallel_ucd_mesh().
iflag_sgl_gz
integer(kind = kint), parameter m_field_file_format::iflag_sgl_gz = 103
Integer flag for merged gzipped binary data.
Definition at line 120 of file m_field_file_format.f90.
Referenced by choose_para_fld_file_format(), parallel_ucd_io_select::sel_read_alloc_para_udt_file(), parallel_ucd_io_select::sel_read_parallel_udt_file(), parallel_ucd_io_select::sel_write_parallel_ucd_file(), and parallel_ucd_io_select::sel_write_parallel_ucd_mesh().
iflag_sgl_hdf5
integer(kind = kint), parameter m_field_file_format::iflag_sgl_hdf5 = 150
Integer flag for HDF file data.
Definition at line 115 of file m_field_file_format.f90.
Referenced by choose_para_fld_file_format(), merged_udt_vtk_file_io::finalize_merged_ucd(), merged_udt_vtk_file_io::init_merged_ucd(), t_viz_vtk_convert::init_visualize_convert_vtk(), parallel_ucd_io_select::sel_read_alloc_para_udt_file(), parallel_ucd_io_select::sel_read_parallel_udt_file(), parallel_ucd_io_select::sel_write_parallel_ucd_file(), and parallel_ucd_io_select::sel_write_parallel_ucd_mesh().
iflag_sgl_ucd
integer(kind = kint), parameter m_field_file_format::iflag_sgl_ucd = 110
Integer flag for merged UCD data.
Definition at line 105 of file m_field_file_format.f90.
Referenced by t_isosurface::alloc_iso_field_type(), choose_para_fld_file_format(), t_control_params_4_iso::sel_iso_file_format(), t_control_params_4_psf::sel_psf_file_format(), parallel_ucd_io_select::sel_read_alloc_para_udt_file(), parallel_ucd_io_select::sel_read_parallel_udt_file(), and parallel_ucd_io_select::sel_write_parallel_ucd_file().
iflag_sgl_ucd_bin
integer(kind = kint), parameter m_field_file_format::iflag_sgl_ucd_bin = 170
Integer flag for merged binary surface data.
Definition at line 100 of file m_field_file_format.f90.
Referenced by t_control_params_4_iso::sel_iso_file_format(), t_control_params_4_psf::sel_psf_file_format(), parallel_ucd_io_select::sel_read_alloc_para_udt_file(), parallel_ucd_io_select::sel_read_parallel_udt_file(), and parallel_ucd_io_select::sel_write_parallel_ucd_file().
iflag_sgl_ucd_bin_gz
integer(kind = kint), parameter m_field_file_format::iflag_sgl_ucd_bin_gz = 173
Integer flag for gzipped merged binary surface data.
Definition at line 142 of file m_field_file_format.f90.
Referenced by t_control_params_4_iso::sel_iso_file_format(), t_control_params_4_psf::sel_psf_file_format(), parallel_ucd_io_select::sel_read_alloc_para_udt_file(), parallel_ucd_io_select::sel_read_parallel_udt_file(), and parallel_ucd_io_select::sel_write_parallel_ucd_file().
iflag_sgl_ucd_gz
integer(kind = kint), parameter m_field_file_format::iflag_sgl_ucd_gz = 113
Integer flag for merged gzipped UCD data.
Definition at line 147 of file m_field_file_format.f90.
Referenced by choose_para_fld_file_format(), t_control_params_4_iso::sel_iso_file_format(), t_control_params_4_psf::sel_psf_file_format(), parallel_ucd_io_select::sel_read_alloc_para_udt_file(), parallel_ucd_io_select::sel_read_parallel_udt_file(), and parallel_ucd_io_select::sel_write_parallel_ucd_file().
iflag_sgl_udt
integer(kind = kint), parameter m_field_file_format::iflag_sgl_udt = 120
Integer flag for merged UCD data (Separated by FEM mesh part and field part)
Definition at line 108 of file m_field_file_format.f90.
Referenced by t_cross_section::alloc_psf_field_type(), choose_para_fld_file_format(), t_control_params_4_psf::sel_psf_file_format(), parallel_ucd_io_select::sel_write_parallel_ucd_file(), and parallel_ucd_io_select::sel_write_parallel_ucd_mesh().
iflag_sgl_udt_bin
integer(kind = kint), parameter m_field_file_format::iflag_sgl_udt_bin = 180
Integer flag for merged binary section data.
Definition at line 102 of file m_field_file_format.f90.
Referenced by t_control_params_4_psf::sel_psf_file_format(), parallel_ucd_io_select::sel_read_alloc_para_udt_file(), parallel_ucd_io_select::sel_read_parallel_udt_file(), parallel_ucd_io_select::sel_write_parallel_ucd_file(), and parallel_ucd_io_select::sel_write_parallel_ucd_mesh().
iflag_sgl_udt_bin_gz
integer(kind = kint), parameter m_field_file_format::iflag_sgl_udt_bin_gz = 183
Integer flag for gzipped merged binary section data.
Definition at line 144 of file m_field_file_format.f90.
Referenced by t_control_params_4_psf::sel_psf_file_format(), parallel_ucd_io_select::sel_read_alloc_para_udt_file(), parallel_ucd_io_select::sel_read_parallel_udt_file(), parallel_ucd_io_select::sel_write_parallel_ucd_file(), and parallel_ucd_io_select::sel_write_parallel_ucd_mesh().
iflag_sgl_udt_gz
integer(kind = kint), parameter m_field_file_format::iflag_sgl_udt_gz = 123
Integer flag for merged gzipped UCD data (Separated by FEM mesh part and field part)
Definition at line 150 of file m_field_file_format.f90.
Referenced by choose_para_fld_file_format(), t_control_params_4_psf::sel_psf_file_format(), parallel_ucd_io_select::sel_read_alloc_para_udt_file(), parallel_ucd_io_select::sel_read_parallel_udt_file(), parallel_ucd_io_select::sel_write_parallel_ucd_file(), and parallel_ucd_io_select::sel_write_parallel_ucd_mesh().
iflag_sgl_vtd
integer(kind = kint), parameter m_field_file_format::iflag_sgl_vtd = 140
Integer flag for merged VTK data (Separated by FEM mesh part and field part)
Definition at line 113 of file m_field_file_format.f90.
Referenced by choose_para_fld_file_format(), t_control_params_4_psf::sel_psf_file_format(), parallel_ucd_io_select::sel_read_alloc_para_udt_file(), parallel_ucd_io_select::sel_read_parallel_udt_file(), parallel_ucd_io_select::sel_write_parallel_ucd_file(), and parallel_ucd_io_select::sel_write_parallel_ucd_mesh().
iflag_sgl_vtd_gz
integer(kind = kint), parameter m_field_file_format::iflag_sgl_vtd_gz = 143
Integer flag for merged amd gzipped VTK data (Separated by FEM mesh part and field part)
Definition at line 155 of file m_field_file_format.f90.
Referenced by choose_para_fld_file_format(), t_control_params_4_psf::sel_psf_file_format(), parallel_ucd_io_select::sel_read_alloc_para_udt_file(), parallel_ucd_io_select::sel_read_parallel_udt_file(), parallel_ucd_io_select::sel_write_parallel_ucd_file(), and parallel_ucd_io_select::sel_write_parallel_ucd_mesh().
iflag_sgl_vtk
integer(kind = kint), parameter m_field_file_format::iflag_sgl_vtk = 130
Integer flag for merged VTK data.
Definition at line 110 of file m_field_file_format.f90.
Referenced by choose_para_fld_file_format(), t_viz_vtk_convert::init_visualize_convert_vtk(), t_control_params_4_iso::sel_iso_file_format(), t_control_params_4_psf::sel_psf_file_format(), parallel_ucd_io_select::sel_read_alloc_para_udt_file(), parallel_ucd_io_select::sel_read_parallel_udt_file(), parallel_ucd_io_select::sel_write_parallel_ucd_file(), t_control_params_4_iso::set_merged_iso_file_ctl(), and t_control_params_4_psf::set_merged_psf_file_ctl().
iflag_sgl_vtk_gz
integer(kind = kint), parameter m_field_file_format::iflag_sgl_vtk_gz = 133
Integer flag for merged amd gzipped VTK data.
Definition at line 152 of file m_field_file_format.f90.
Referenced by choose_para_fld_file_format(), t_viz_vtk_convert::init_visualize_convert_vtk(), t_control_params_4_iso::sel_iso_file_format(), t_control_params_4_psf::sel_psf_file_format(), parallel_ucd_io_select::sel_read_alloc_para_udt_file(), parallel_ucd_io_select::sel_read_parallel_udt_file(), and parallel_ucd_io_select::sel_write_parallel_ucd_file().
iflag_ucd
integer(kind = kint), parameter m_field_file_format::iflag_ucd = 10
Integer flag for UCD data.
Definition at line 81 of file m_field_file_format.f90.
Referenced by choose_ucd_file_format(), ucd_io_select::sel_read_alloc_ucd_file(), ucd_io_select::sel_read_ucd_file(), ucd_io_select::sel_write_ucd_file(), ucd_io_select::sel_write_udt_file(), set_ucd_file_names::set_parallel_ucd_file_name(), and set_ucd_file_names::set_single_ucd_file_name().
iflag_ucd_bin
integer(kind = kint), parameter m_field_file_format::iflag_ucd_bin = 70
Integer flag for binary surface data.
Definition at line 92 of file m_field_file_format.f90.
Referenced by ucd_io_select::sel_read_alloc_ucd_file(), ucd_io_select::sel_read_ucd_file(), parallel_ucd_io_select::sel_write_parallel_ucd_file(), set_ucd_file_names::set_parallel_ucd_file_name(), and set_ucd_file_names::set_single_ucd_file_name().
iflag_ucd_bin_gz
integer(kind = kint), parameter m_field_file_format::iflag_ucd_bin_gz = 73
Integer flag for gzipped binary surface data.
Definition at line 136 of file m_field_file_format.f90.
Referenced by ucd_io_select::sel_read_alloc_ucd_file(), ucd_io_select::sel_read_ucd_file(), parallel_ucd_io_select::sel_write_parallel_ucd_file(), and set_ucd_file_names::set_parallel_ucd_file_name().
iflag_ucd_gz
integer(kind = kint), parameter m_field_file_format::iflag_ucd_gz = 13
Integer flag for gzipped UCD data.
Definition at line 125 of file m_field_file_format.f90.
Referenced by ucd_io_select::sel_read_alloc_ucd_file(), ucd_io_select::sel_read_ucd_file(), ucd_io_select::sel_write_ucd_file(), ucd_io_select::sel_write_udt_file(), and set_ucd_file_names::set_parallel_ucd_file_name().
iflag_udt
integer(kind = kint), parameter m_field_file_format::iflag_udt = 20
Integer flag for UCD data (Separated by FEM mesh part and field part)
Definition at line 84 of file m_field_file_format.f90.
Referenced by choose_ucd_file_format(), output_parallel_ucd_file::link_output_grd_file(), ucd_io_select::sel_read_alloc_ucd_file(), ucd_io_select::sel_read_alloc_udt_file(), ucd_io_select::sel_read_ucd_file(), ucd_io_select::sel_read_udt_file(), ucd_io_select::sel_read_udt_param(), ucd_io_select::sel_write_grd_file(), ucd_io_select::sel_write_ucd_file(), ucd_io_select::sel_write_udt_file(), set_ucd_file_names::set_parallel_grd_file_name(), set_ucd_file_names::set_parallel_ucd_file_name(), set_ucd_file_names::set_single_grd_file_name(), and set_ucd_file_names::set_single_ucd_file_name().
iflag_udt_bin
integer(kind = kint), parameter m_field_file_format::iflag_udt_bin = 80
Integer flag for binary section data (Separated by FEM mesh part and field part)
Definition at line 95 of file m_field_file_format.f90.
Referenced by ucd_io_select::sel_read_alloc_ucd_file(), ucd_io_select::sel_read_alloc_udt_file(), ucd_io_select::sel_read_ucd_file(), ucd_io_select::sel_read_udt_file(), ucd_io_select::sel_read_udt_param(), parallel_ucd_io_select::sel_write_parallel_ucd_file(), parallel_ucd_io_select::sel_write_parallel_ucd_mesh(), set_ucd_file_names::set_parallel_grd_file_name(), set_ucd_file_names::set_parallel_ucd_file_name(), set_ucd_file_names::set_single_grd_file_name(), and set_ucd_file_names::set_single_ucd_file_name().
iflag_udt_bin_gz
integer(kind = kint), parameter m_field_file_format::iflag_udt_bin_gz = 83
Integer flag for gzipped binary section data (Separated by FEM mesh part and field part)
Definition at line 139 of file m_field_file_format.f90.
Referenced by ucd_io_select::sel_read_alloc_ucd_file(), ucd_io_select::sel_read_alloc_udt_file(), ucd_io_select::sel_read_ucd_file(), ucd_io_select::sel_read_udt_file(), ucd_io_select::sel_read_udt_param(), parallel_ucd_io_select::sel_write_parallel_ucd_file(), parallel_ucd_io_select::sel_write_parallel_ucd_mesh(), set_ucd_file_names::set_parallel_grd_file_name(), and set_ucd_file_names::set_parallel_ucd_file_name().
iflag_udt_gz
integer(kind = kint), parameter m_field_file_format::iflag_udt_gz = 23
Integer flag for gzipped UCD data (Separated by FEM mesh part and field part)
Definition at line 128 of file m_field_file_format.f90.
Referenced by ucd_io_select::sel_read_alloc_ucd_file(), ucd_io_select::sel_read_alloc_udt_file(), ucd_io_select::sel_read_ucd_file(), ucd_io_select::sel_read_udt_file(), ucd_io_select::sel_read_udt_param(), ucd_io_select::sel_write_grd_file(), ucd_io_select::sel_write_ucd_file(), ucd_io_select::sel_write_udt_file(), set_ucd_file_names::set_parallel_grd_file_name(), and set_ucd_file_names::set_parallel_ucd_file_name().
iflag_vtd
integer(kind = kint), parameter m_field_file_format::iflag_vtd = 40
Integer flag for VTK data (Separated by FEM mesh part and field part)
Definition at line 89 of file m_field_file_format.f90.
Referenced by choose_ucd_file_format(), output_parallel_ucd_file::link_output_grd_file(), ucd_io_select::sel_read_alloc_ucd_file(), ucd_io_select::sel_read_alloc_udt_file(), ucd_io_select::sel_read_ucd_file(), ucd_io_select::sel_read_udt_file(), ucd_io_select::sel_read_udt_param(), ucd_io_select::sel_write_grd_file(), parallel_ucd_io_select::sel_write_parallel_ucd_file(), ucd_io_select::sel_write_ucd_file(), ucd_io_select::sel_write_udt_file(), set_ucd_file_names::set_parallel_grd_file_name(), set_ucd_file_names::set_parallel_ucd_file_name(), set_ucd_file_names::set_single_grd_file_name(), and set_ucd_file_names::set_single_ucd_file_name().
iflag_vtd_gz
integer(kind = kint), parameter m_field_file_format::iflag_vtd_gz = 43
Integer flag for gzipped VTK data (Separated by FEM mesh part and field part)
Definition at line 133 of file m_field_file_format.f90.
Referenced by ucd_io_select::sel_read_alloc_ucd_file(), ucd_io_select::sel_read_alloc_udt_file(), ucd_io_select::sel_read_ucd_file(), ucd_io_select::sel_read_udt_file(), ucd_io_select::sel_read_udt_param(), ucd_io_select::sel_write_grd_file(), parallel_ucd_io_select::sel_write_parallel_ucd_file(), ucd_io_select::sel_write_ucd_file(), ucd_io_select::sel_write_udt_file(), set_ucd_file_names::set_parallel_grd_file_name(), and set_ucd_file_names::set_parallel_ucd_file_name().
iflag_vtk
integer(kind = kint), parameter m_field_file_format::iflag_vtk = 30
Integer flag for VTK data.
Definition at line 86 of file m_field_file_format.f90.
Referenced by choose_ucd_file_format(), t_viz_vtk_convert::init_visualize_convert_vtk(), psf_file_to_vtk(), ucd_io_select::sel_read_alloc_ucd_file(), ucd_io_select::sel_read_ucd_file(), parallel_ucd_io_select::sel_write_parallel_ucd_file(), ucd_io_select::sel_write_ucd_file(), ucd_io_select::sel_write_udt_file(), set_ucd_file_names::set_parallel_ucd_file_name(), set_ucd_file_names::set_single_ucd_file_name(), and gz_vtk_file_io::write_gz_parallel_vtk_file().
iflag_vtk_gz
integer(kind = kint), parameter m_field_file_format::iflag_vtk_gz = 33
Integer flag for gzipped VTK data.
Definition at line 130 of file m_field_file_format.f90.
Referenced by t_viz_vtk_convert::init_visualize_convert_vtk(), ucd_io_select::sel_read_alloc_ucd_file(), ucd_io_select::sel_read_ucd_file(), parallel_ucd_io_select::sel_write_parallel_ucd_file(), ucd_io_select::sel_write_ucd_file(), ucd_io_select::sel_write_udt_file(), and set_ucd_file_names::set_parallel_ucd_file_name().