CALYPSO: t_ctl_data_momentum_norm Module Reference
t_ctl_data_momentum_norm Module Reference
Data Types
type momentum_equation_control
Structure for coefficients of momentum equation.
Functions/Subroutines
subroutine read_momentum_ctl (id_control, hd_block, mom_ctl, c_buf)
subroutine bcast_momentum_ctl (mom_ctl)
subroutine dealloc_momentum_ctl (mom_ctl)
Variables
character(len=kchara), private hd_n_mom = 'coef_4_velocity_ctl'
character(len=kchara), private hd_n_press = 'coef_4_press_ctl'
character(len=kchara), private hd_n_v_diff = 'coef_4_v_diffuse_ctl'
character(len=kchara), private hd_n_buo = 'coef_4_buoyancy_ctl'
character(len=kchara), private hd_n_c_buo = 'coef_4_composit_buoyancy_ctl'
character(len=kchara), private hd_n_cor = 'coef_4_Coriolis_ctl'
character(len=kchara), private hd_n_lor = 'coef_4_Lorentz_ctl'
Function/Subroutine Documentation
bcast_momentum_ctl()
subroutine t_ctl_data_momentum_norm::bcast_momentum_ctl (type(momentum_equation_control), intent(inout) mom_ctl)
Definition at line 161 of file t_ctl_data_momentum_norm.f90.
References bcast_control_arrays::bcast_ctl_array_cr(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by t_ctl_data_mhd_normalize::bcast_coef_term_ctl().
dealloc_momentum_ctl()
subroutine t_ctl_data_momentum_norm::dealloc_momentum_ctl (type(momentum_equation_control), intent(inout) mom_ctl)
Definition at line 184 of file t_ctl_data_momentum_norm.f90.
References t_control_array_charareal::dealloc_control_array_c_r().
Referenced by t_ctl_data_mhd_normalize::dealloc_coef_term_ctl().
read_momentum_ctl()
subroutine t_ctl_data_momentum_norm::read_momentum_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(momentum_equation_control), intent(inout) mom_ctl, type(buffer_for_control), intent(inout) c_buf)
Definition at line 120 of file t_ctl_data_momentum_norm.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_n_buo, hd_n_c_buo, hd_n_cor, hd_n_lor, hd_n_mom, hd_n_press, hd_n_v_diff, t_read_control_elements::load_one_line_from_control(), and t_control_array_charareal::read_control_array_c_r().
Referenced by t_ctl_data_mhd_normalize::read_coef_term_ctl().
Variable Documentation
hd_n_buo
character(len=kchara), private t_ctl_data_momentum_norm::hd_n_buo = 'coef_4_buoyancy_ctl' private
Definition at line 104 of file t_ctl_data_momentum_norm.f90.
Referenced by read_momentum_ctl().
hd_n_c_buo
character(len=kchara), private t_ctl_data_momentum_norm::hd_n_c_buo = 'coef_4_composit_buoyancy_ctl' private
Definition at line 105 of file t_ctl_data_momentum_norm.f90.
Referenced by read_momentum_ctl().
hd_n_cor
character(len=kchara), private t_ctl_data_momentum_norm::hd_n_cor = 'coef_4_Coriolis_ctl' private
Definition at line 107 of file t_ctl_data_momentum_norm.f90.
Referenced by read_momentum_ctl().
hd_n_lor
character(len=kchara), private t_ctl_data_momentum_norm::hd_n_lor = 'coef_4_Lorentz_ctl' private
Definition at line 108 of file t_ctl_data_momentum_norm.f90.
Referenced by read_momentum_ctl().
hd_n_mom
character(len=kchara), private t_ctl_data_momentum_norm::hd_n_mom = 'coef_4_velocity_ctl' private
Definition at line 101 of file t_ctl_data_momentum_norm.f90.
Referenced by read_momentum_ctl().
hd_n_press
character(len=kchara), private t_ctl_data_momentum_norm::hd_n_press = 'coef_4_press_ctl' private
Definition at line 102 of file t_ctl_data_momentum_norm.f90.
Referenced by read_momentum_ctl().
hd_n_v_diff
character(len=kchara), private t_ctl_data_momentum_norm::hd_n_v_diff = 'coef_4_v_diffuse_ctl' private
Definition at line 103 of file t_ctl_data_momentum_norm.f90.
Referenced by read_momentum_ctl().