CALYPSO: set_local_sphere_by_global Module Reference
set_local_sphere_by_global Module Reference
Copy number of global spherical harmonics indices to local data.
Functions/Subroutines
subroutine copy_gl_2_local_rj_param (id_rank, s3d_ranks, sph_lcp, stk_lc1d, sph_rj)
subroutine copy_gl_2_local_rlm_param (id_rank, s3d_ranks, sph_lcp, stk_lc1d, sph_rlm)
subroutine copy_gl_2_local_rtm_param (id_rank, s3d_ranks, sph_lcp, stk_lc1d, sph_rtm)
subroutine copy_gl_2_local_rtp_param (id_rank, s3d_ranks, sph_lcp, stk_lc1d, sph_rtp)
Detailed Description
Copy number of global spherical harmonics indices to local data.
      subroutine copy_gl_2_local_rj_param                             &
     &         (id_rank, s3d_ranks, sph_lcp, stk_lc1d, sph_rj)
        type(sph_local_parameters), intent(in) :: sph_lcp
        type(sph_1d_index_stack), intent(in) :: stk_lc1d
        type(sph_rj_grid), intent(inout) :: sph_rj
      subroutine copy_gl_2_local_rlm_param                            &
     &         (id_rank, s3d_ranks, sph_lcp, stk_lc1d, sph_rlm)
        type(sph_local_parameters), intent(in) :: sph_lcp
        type(sph_1d_index_stack), intent(in) :: stk_lc1d
        type(sph_rlm_grid), intent(inout) :: sph_rlm
      subroutine copy_gl_2_local_rtm_param                            &
     &         (id_rank, s3d_ranks, sph_lcp, stk_lc1d, sph_rtm)
        type(sph_local_parameters), intent(in) :: sph_lcp
        type(sph_1d_index_stack), intent(in) :: stk_lc1d
        type(sph_rtm_grid), intent(inout) :: sph_rtm
      subroutine copy_gl_2_local_rtp_param                            &
     &         (id_rank, s3d_ranks, sph_lcp, stk_lc1d, sph_rtp)
        type(sph_local_parameters), intent(in) :: sph_lcp
        type(sph_1d_index_stack), intent(in) :: stk_lc1d
        type(sph_rtp_grid), intent(inout) :: sph_rtp
Function/Subroutine Documentation
copy_gl_2_local_rj_param()
subroutine set_local_sphere_by_global::copy_gl_2_local_rj_param (integer, intent(in) id_rank, type(spheric_global_rank), intent(in) s3d_ranks, type(sph_local_parameters), intent(in) sph_lcp, type(sph_1d_index_stack), intent(in) stk_lc1d, type(sph_rj_grid), intent(inout) sph_rj)
Definition at line 50 of file set_local_sphere_by_global.f90.
Referenced by set_comm_table_rtp_rj::const_sph_rj_modes().
copy_gl_2_local_rlm_param()
subroutine set_local_sphere_by_global::copy_gl_2_local_rlm_param (integer, intent(in) id_rank, type(spheric_global_rank), intent(in) s3d_ranks, type(sph_local_parameters), intent(in) sph_lcp, type(sph_1d_index_stack), intent(in) stk_lc1d, type(sph_rlm_grid), intent(inout) sph_rlm)
Definition at line 79 of file set_local_sphere_by_global.f90.
Referenced by gen_sph_grids_modes::const_sph_rlm_modes().
copy_gl_2_local_rtm_param()
subroutine set_local_sphere_by_global::copy_gl_2_local_rtm_param (integer, intent(in) id_rank, type(spheric_global_rank), intent(in) s3d_ranks, type(sph_local_parameters), intent(in) sph_lcp, type(sph_1d_index_stack), intent(in) stk_lc1d, type(sph_rtm_grid), intent(inout) sph_rtm)
Definition at line 109 of file set_local_sphere_by_global.f90.
Referenced by gen_sph_grids_modes::const_sph_rtm_grids().
copy_gl_2_local_rtp_param()
subroutine set_local_sphere_by_global::copy_gl_2_local_rtp_param (integer, intent(in) id_rank, type(spheric_global_rank), intent(in) s3d_ranks, type(sph_local_parameters), intent(in) sph_lcp, type(sph_1d_index_stack), intent(in) stk_lc1d, type(sph_rtp_grid), intent(inout) sph_rtp)
Definition at line 142 of file set_local_sphere_by_global.f90.
Referenced by set_comm_table_rtp_rj::const_sph_rtp_grids().