CALYPSO: m_solver_sr Module Reference
m_solver_sr Module Reference
Work area for data communications.
Variables
type(send_recv_status), save sr_sig1
Structure of communication flags.
type(send_recv_real_buffer), save sr_r1
Structure of communication buffer for 8-byte real.
type(send_recv_int_buffer), save sr_i1
Structure of communication buffer for 4-byte integer.
type(send_recv_int8_buffer), save sr_il1
Structure of communication buffer for 8-byte integer.
Detailed Description
Work area for data communications.
Parameters
NB Number of components
NTOT_SEND Total number of data points for export
NTOT_RECV Total number of data points for import
NPE_SEND Number of processses to receive
NPE_RECV Number of processses to send
Parameters
N_SHIFT number of shifting of the reversed import table
ITEM_IMPORT import table
REV_IMPORT reversed import table
Variable Documentation
sr_i1
type(send_recv_int_buffer), save m_solver_sr::sr_i1
Structure of communication buffer for 4-byte integer.
Definition at line 39 of file m_solver_SR.f90.
Referenced by nod_phys_send_recv::init_send_recv(), spherical_srs_n::send_recv_sph_trans_int(), and solver_sr_type::solver_send_recv_int_type().
sr_il1
type(send_recv_int8_buffer), save m_solver_sr::sr_il1
Structure of communication buffer for 8-byte integer.
Definition at line 41 of file m_solver_SR.f90.
Referenced by nod_phys_send_recv::init_send_recv(), and solver_sr_type::solver_send_recv_int8_type().
sr_r1
type(send_recv_real_buffer), save m_solver_sr::sr_r1
Structure of communication buffer for 8-byte real.
Definition at line 36 of file m_solver_SR.f90.
Referenced by sel_spherical_srs::check_calypso_sph_buf_n(), init_fft_4_mhd::init_fourier_transform_4_mhd(), init_fft_4_sph::init_fourier_transform_4_sph(), nod_phys_send_recv::init_send_recv(), sel_spherical_srs::sel_calypso_sph_comm_n(), spherical_srs_n::send_recv_sph_trans(), spherical_srs_n::send_recv_sph_trans_2(), spherical_srs_n::send_recv_sph_trans_3(), spherical_srs_n::send_recv_sph_trans_6(), spherical_srs_n::send_recv_sph_trans_n(), solver_sr_type::solver_send_recv_1x3_type(), solver_sr_type::solver_send_recv_3_type(), solver_sr_type::solver_send_recv_3x3_type(), solver_sr_type::solver_send_recv_6_type(), solver_sr_type::solver_send_recv_n_type(), solver_sr_type::solver_send_recv_nx3_type(), solver_sr_type::solver_send_recv_type(), sph_transforms_4_mhd::sph_back_trans_4_mhd(), sph_transforms_snapshot::sph_back_trans_snapshot_mhd(), sph_transforms_4_mhd::sph_forward_trans_4_mhd(), sph_transforms_snapshot::sph_forward_trans_snapshot_mhd(), sph_transforms_4_mhd::sph_pole_trans_4_mhd(), and sph_transforms_4_mhd::sph_transform_4_licv().
sr_sig1
type(send_recv_status), save m_solver_sr::sr_sig1
Structure of communication flags.
Definition at line 34 of file m_solver_SR.f90.
Referenced by sel_spherical_srs::check_calypso_sph_buf_n(), const_element_comm_table::const_comm_table_by_connenct(), make_element_comm_table_sr::element_data_reverse_sr(), spherical_srs_n::finish_send_recv_sph(), nod_phys_send_recv::init_send_recv(), sel_spherical_srs::sel_calypso_sph_comm_n(), spherical_srs_n::send_recv_sph_trans(), spherical_srs_n::send_recv_sph_trans_2(), spherical_srs_n::send_recv_sph_trans_3(), spherical_srs_n::send_recv_sph_trans_6(), spherical_srs_n::send_recv_sph_trans_int(), solver_sr_type::solver_send_recv_1x3_type(), solver_sr_type::solver_send_recv_3_type(), solver_sr_type::solver_send_recv_3x3_type(), solver_sr_type::solver_send_recv_6_type(), solver_sr_type::solver_send_recv_int8_type(), solver_sr_type::solver_send_recv_int_type(), solver_sr_type::solver_send_recv_n_type(), solver_sr_type::solver_send_recv_num_type(), solver_sr_type::solver_send_recv_nx3_type(), and solver_sr_type::solver_send_recv_type().