CALYPSO: m_rot_force_labels Module Reference
m_rot_force_labels Module Reference
Functions/Subroutines
logical function check_rot_force (field_name)
integer(kind=kint) function num_rot_forces ()
subroutine set_rot_force_labels (n_comps, names, maths)
Variables
integer(kind=kint), parameter, private nrot_force = 5
Number of field labels.
type(field_def), parameter rot_inertia = field_def(n_comp = n_vector, name = 'rot_inertia', math = '$ e_{ijk} \partial_{j}' // ' \left(e_{kkm} \omega_{l} u_{m} \right)$')
Field label for curl of advection \(-e_{ijk} \partial_{j} \left(e_{klm} \omega_{l} u_{m} \right) \).
type(field_def), parameter rot_coriolis_force = field_def(n_comp = n_vector, name = 'rot_Coriolis_force', math = '$ -2 e_{ijk} \partial_{j}' // '\left(e_{kkm} \Omega_{l} u_{m} \right) $')
Field label for curl of Lorentz force \(-2 e_{ijk} \partial_{j} \left(e_{klm} J_{l} B_{m} \right) \).
type(field_def), parameter rot_lorentz_force = field_def(n_comp = n_vector, name = 'rot_Lorentz_force', math = '$ e_{ijk} \partial_{j}' // '\left(e_{kkm} J_{l} B_{m} \right) $')
Field label for curl of Lorentz force \(e_{ijk} \partial_{j} \left(e_{klm} J_{l} B_{m}\right) \).
type(field_def), parameter rot_buoyancy = field_def(n_comp = n_vector, name = 'rot_buoyancy', math = '$-e_{ijk} \partial_{j} \alpha_{T}' // ' T g_{k}$')
Field label for curl of filtered buoyancy \(-e_{ijk} \partial_{j} \alpha_{T} T g_{k} \).
type(field_def), parameter rot_composite_buoyancy = field_def(n_comp = n_vector, name = 'rot_composite_buoyancy', math = '$-e_{ijk} \partial_{j} \alpha_{C}' // ' C g_{k}$')
Field label for curl of compositional buoyancy \(-e_{ijk} \partial_{j} \alpha_{C} C g_{k} \).
Function/Subroutine Documentation
check_rot_force()
logical function m_rot_force_labels::check_rot_force (character(len = kchara), intent(in) field_name)
Definition at line 83 of file m_rot_force_labels.f90.
References rot_buoyancy, rot_composite_buoyancy, rot_coriolis_force, rot_inertia, and rot_lorentz_force.
Referenced by set_mhd_field_address::check_vector_fields(), and t_base_force_labels::set_rot_force_addresses().
num_rot_forces()
integer(kind = kint) function m_rot_force_labels::num_rot_forces
Definition at line 100 of file m_rot_force_labels.f90.
References nrot_force.
set_rot_force_labels()
subroutine m_rot_force_labels::set_rot_force_labels (integer(kind = kint_4b), dimension(nrot_force), intent(inout) n_comps, character(len = kchara), dimension(nrot_force), intent(inout) names, character(len = kchara), dimension(nrot_force), intent(inout) maths)
Definition at line 107 of file m_rot_force_labels.f90.
References rot_buoyancy, rot_composite_buoyancy, rot_coriolis_force, rot_inertia, rot_lorentz_force, and t_field_labels::set_field_labels().
Variable Documentation
nrot_force
integer(kind = kint), parameter, private m_rot_force_labels::nrot_force = 5 private
Number of field labels.
Definition at line 35 of file m_rot_force_labels.f90.
Referenced by num_rot_forces().
rot_buoyancy
type(field_def), parameter m_rot_force_labels::rot_buoyancy = field_def(n_comp = n_vector, name = 'rot_buoyancy', math = '$-e_{ijk} \partial_{j} \alpha_{T}' // ' T g_{k}$')
Field label for curl of filtered buoyancy \(-e_{ijk} \partial_{j} \alpha_{T} T g_{k} \).
Definition at line 64 of file m_rot_force_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_rot_forces(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_rot_force(), t_base_force_labels::set_rot_force_addresses(), and set_rot_force_labels().
rot_composite_buoyancy
type(field_def), parameter m_rot_force_labels::rot_composite_buoyancy = field_def(n_comp = n_vector, name = 'rot_composite_buoyancy', math = '$-e_{ijk} \partial_{j} \alpha_{C}' // ' C g_{k}$')
Field label for curl of compositional buoyancy \(-e_{ijk} \partial_{j} \alpha_{C} C g_{k} \).
Definition at line 71 of file m_rot_force_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_rot_forces(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_rot_force(), t_base_force_labels::set_rot_force_addresses(), and set_rot_force_labels().
rot_coriolis_force
type(field_def), parameter m_rot_force_labels::rot_coriolis_force = field_def(n_comp = n_vector, name = 'rot_Coriolis_force', math = '$ -2 e_{ijk} \partial_{j}' // '\left(e_{kkm} \Omega_{l} u_{m} \right) $')
Field label for curl of Lorentz force \(-2 e_{ijk} \partial_{j} \left(e_{klm} J_{l} B_{m} \right) \).
Definition at line 49 of file m_rot_force_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_rot_forces(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_rot_force(), t_base_force_labels::set_rot_force_addresses(), and set_rot_force_labels().
rot_inertia
type(field_def), parameter m_rot_force_labels::rot_inertia = field_def(n_comp = n_vector, name = 'rot_inertia', math = '$ e_{ijk} \partial_{j}' // ' \left(e_{kkm} \omega_{l} u_{m} \right)$')
Field label for curl of advection \(-e_{ijk} \partial_{j} \left(e_{klm} \omega_{l} u_{m} \right) \).
Definition at line 41 of file m_rot_force_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_rot_forces(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_rot_force(), t_base_force_labels::set_rot_force_addresses(), and set_rot_force_labels().
rot_lorentz_force
type(field_def), parameter m_rot_force_labels::rot_lorentz_force = field_def(n_comp = n_vector, name = 'rot_Lorentz_force', math = '$ e_{ijk} \partial_{j}' // '\left(e_{kkm} J_{l} B_{m} \right) $')
Field label for curl of Lorentz force \(e_{ijk} \partial_{j} \left(e_{klm} J_{l} B_{m}\right) \).
Definition at line 56 of file m_rot_force_labels.f90.
Referenced by check_base_forces::add_field_ctl_4_rot_forces(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_rot_force(), t_base_force_labels::set_rot_force_addresses(), and set_rot_force_labels().