CALYPSO: surface_data_io Module Reference
surface_data_io Module Reference
routines for surface mesh data IO
Functions/Subroutines
subroutine read_surface_connection (id_file, id_rank, comm_IO, ele_IO, sfed_IO, ierr)
subroutine write_surface_connection (id_file, id_rank, comm_IO, ele_IO, sfed_IO)
subroutine read_surface_geometry (id_file, nod_IO, sfed_IO)
subroutine write_surface_geometry (id_file, nod_IO, sfed_IO)
subroutine write_surface_geometry_sph (id_file, nod_IO, sfed_IO)
subroutine write_surface_geometry_cyl (id_file, nod_IO, sfed_IO)
Detailed Description
routines for surface mesh data IO
      subroutine read_surface_connection                              &
     &         (id_file, id_rank, comm_IO, ele_IO, sfed_IO, ierr)
        type(communication_table), intent(inout) :: comm_IO
        type(element_data), intent(inout) :: ele_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
      subroutine write_surface_connection                             &
     &         (id_file, id_rank, comm_IO, ele_IO, sfed_IO)
        type(communication_table), intent(in) :: comm_IO
        type(element_data), intent(in) :: ele_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
      subroutine read_surface_geometry(id_file, nod_IO, sfed_IO)
        type(node_data), intent(inout) :: nod_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
      subroutine write_surface_geometry(id_file, nod_IO, sfed_IO)
      subroutine write_surface_geometry_sph(id_file, nod_IO, sfed_IO)
      subroutine write_surface_geometry_cyl(id_file, nod_IO, sfed_IO)
        type(node_data), intent(in) :: nod_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
Function/Subroutine Documentation
read_surface_connection()
subroutine surface_data_io::read_surface_connection (integer (kind = kint), intent(in) id_file, integer, intent(in) id_rank, type(communication_table), intent(inout) comm_IO, type(element_data), intent(inout) ele_IO, type(surf_edge_io_data), intent(inout) sfed_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 49 of file surface_data_IO.f90.
References domain_data_io::read_domain_info(), element_connect_io::read_element_info(), domain_data_io::read_export_data(), domain_data_io::read_import_data(), element_connect_io::read_number_of_element(), and element_connect_io::read_surface_4_element().
Referenced by element_file_io::input_surface_file().
read_surface_geometry()
subroutine surface_data_io::read_surface_geometry (integer (kind = kint), intent(in) id_file, type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 145 of file surface_data_IO.f90.
References node_geometry_io::read_geometry_info(), node_geometry_io::read_number_of_node(), node_geometry_io::read_scalar_in_element(), and node_geometry_io::read_vector_in_element().
write_surface_connection()
subroutine surface_data_io::write_surface_connection (integer (kind = kint), intent(in) id_file, integer, intent(in) id_rank, type(communication_table), intent(in) comm_IO, type(element_data), intent(in) ele_IO, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 109 of file surface_data_IO.f90.
References m_fem_mesh_labels::hd_fem_para(), m_fem_surface_labels::hd_surf_connect(), m_fem_surface_labels::hd_surf_export(), m_fem_surface_labels::hd_surf_import(), m_fem_surface_labels::hd_surf_on_ele(), m_fem_surface_labels::hd_surf_para(), domain_data_io::write_domain_info(), element_connect_io::write_element_info(), domain_data_io::write_export_data(), domain_data_io::write_import_data(), and element_connect_io::write_surface_4_element().
Referenced by element_file_io::output_surface_file().
write_surface_geometry()
subroutine surface_data_io::write_surface_geometry (integer (kind = kint), intent(in) id_file, type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 179 of file surface_data_IO.f90.
References m_fem_surface_labels::hd_surf_area(), m_fem_surface_labels::hd_surf_norm(), m_fem_surface_labels::hd_surf_point(), node_geometry_io::write_geometry_info(), node_geometry_io::write_scalar_in_element(), and node_geometry_io::write_vector_in_element().
write_surface_geometry_cyl()
subroutine surface_data_io::write_surface_geometry_cyl (integer (kind = kint), intent(in) id_file, type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 232 of file surface_data_IO.f90.
References m_fem_surface_labels::hd_surf_area(), node_geometry_io::write_geometry_info(), node_geometry_io::write_scalar_in_element(), and node_geometry_io::write_vector_in_element().
write_surface_geometry_sph()
subroutine surface_data_io::write_surface_geometry_sph (integer (kind = kint), intent(in) id_file, type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 201 of file surface_data_IO.f90.
References m_fem_surface_labels::hd_surf_area(), node_geometry_io::write_geometry_info(), node_geometry_io::write_scalar_in_element(), and node_geometry_io::write_vector_in_element().