CALYPSO: set_ucd_file_names Module Reference
set_ucd_file_names Module Reference
Append step, process, and file format suffix to UCD file prefix
(If process number is negative, process number is not appeded)
Functions/Subroutines
subroutine delete_para_ucd_file (file_prefix, itype_file, nprocs, istep_ucd)
character(len=kchara) function set_parallel_ucd_file_name (file_prefix, itype_file, id_rank, istep_ucd)
character(len=kchara) function set_parallel_grd_file_name (file_prefix, itype_file, id_rank)
character(len=kchara) function set_single_ucd_file_name (file_prefix, itype_file, istep_ucd)
character(len=kchara) function set_single_grd_file_name (file_prefix, itype_file)
character(len=kchara) function set_parallel_vtk_file_name (file_prefix, id_rank, istep_ucd)
character(len=kchara) function set_merged_hdf_mesh_file_name (file_prefix)
character(len=kchara) function set_merged_hdf_field_file_name (file_prefix, istep_ucd)
character(len=kchara) function set_merged_snap_xdmf_file_name (file_prefix, istep_ucd)
character(len=kchara) function set_merged_xdmf_file_name (file_prefix)
Detailed Description
Append step, process, and file format suffix to UCD file prefix
(If process number is negative, process number is not appeded)
      subroutine delete_para_ucd_file(file_prefix, itype_file,        &
     &          nprocs, istep_ucd)
      character(len=kchara) function set_parallel_ucd_file_name       &
     &                  (file_prefix, itype_file, id_rank, istep_ucd)
      character(len=kchara) function set_parallel_grd_file_name       &
     &                    (file_prefix, itype_file, id_rank)
      character(len=kchara) function set_single_ucd_file_name         &
     &                    (file_prefix, itype_file, istep_ucd)
      character(len=kchara) function                                  &
     &          set_single_grd_file_name(file_prefix, itype_file)
      character(len=kchara) function set_parallel_vtk_file_name       &
     &                  (file_prefix, id_rank, istep_ucd)
      character(len=kchara) function                                  &
     &          set_merged_hdf_mesh_file_name(file_prefix)
      character(len=kchara) function                                  &
     &         set_merged_hdf_field_file_name(file_prefix, istep_ucd)
      character(len=kchara) function                                  &
     &          set_merged_snap_xdmf_file_name(file_prefix, istep_ucd)
      character(len=kchara) function                                  &
     &                     set_merged_xdmf_file_name(file_prefix)
Parameters
nprocs number of subdomains
id_rank subdomain ID
istep Step number for VTK data
Function/Subroutine Documentation
delete_para_ucd_file()
subroutine set_ucd_file_names::delete_para_ucd_file (character(len=kchara), intent(in) file_prefix, integer(kind = kint), intent(in) itype_file, integer, intent(in) nprocs, integer(kind = kint), intent(in) istep_ucd)
Definition at line 57 of file set_ucd_file_names.f90.
References delete_data_files::delete_file_by_f(), and set_parallel_ucd_file_name().
set_merged_hdf_field_file_name()
character(len=kchara) function set_ucd_file_names::set_merged_hdf_field_file_name (character(len=kchara), intent(in) file_prefix, integer(kind=kint), intent(in) istep_ucd)
Definition at line 310 of file set_ucd_file_names.f90.
References set_ucd_extensions::add_field_suffix(), set_ucd_extensions::add_hdf_extension(), and set_parallel_file_name::add_int_suffix().
Referenced by hdf5_file_io::parallel_write_hdf5_field_file(), and hdf5_file_io::parallel_write_xdmf_file().
set_merged_hdf_mesh_file_name()
character(len=kchara) function set_ucd_file_names::set_merged_hdf_mesh_file_name (character(len=kchara), intent(in) file_prefix)
Definition at line 294 of file set_ucd_file_names.f90.
References set_ucd_extensions::add_hdf_extension(), and set_ucd_extensions::add_mesh_suffix().
Referenced by hdf5_file_io::parallel_write_hdf5_mesh_file(), and hdf5_file_io::parallel_write_xdmf_file().
set_merged_snap_xdmf_file_name()
character(len=kchara) function set_ucd_file_names::set_merged_snap_xdmf_file_name (character(len=kchara), intent(in) file_prefix, integer(kind=kint), intent(in) istep_ucd)
Definition at line 329 of file set_ucd_file_names.f90.
References set_parallel_file_name::add_int_suffix(), and set_ucd_extensions::add_xdmf_extension().
Referenced by hdf5_file_io::parallel_write_xdmf_snap_file().
set_merged_xdmf_file_name()
character(len=kchara) function set_ucd_file_names::set_merged_xdmf_file_name (character(len=kchara), intent(in) file_prefix)
Definition at line 348 of file set_ucd_file_names.f90.
References set_ucd_extensions::add_solution_suffix(), and set_ucd_extensions::add_xdmf_extension().
Referenced by hdf5_file_io::parallel_write_xdmf_evo_file().
set_parallel_grd_file_name()
character(len=kchara) function set_ucd_file_names::set_parallel_grd_file_name (character(len=kchara), intent(in) file_prefix, integer(kind=kint), intent(in) itype_file, integer, intent(in) id_rank)
Definition at line 148 of file set_ucd_file_names.f90.
References set_ucd_extensions::add_grd_extension(), set_parallel_file_name::add_gzip_extension(), set_parallel_file_name::add_int_suffix(), set_parallel_file_name::add_process_id(), set_ucd_extensions::add_sgd_extension(), set_ucd_extensions::add_vtg_extension(), m_constants::icent, m_field_file_format::iflag_gzip, m_field_file_format::iflag_udt, m_field_file_format::iflag_udt_bin, m_field_file_format::iflag_udt_bin_gz, m_field_file_format::iflag_udt_gz, m_field_file_format::iflag_vtd, m_field_file_format::iflag_vtd_gz, m_constants::iten, and m_constants::izero.
Referenced by ucd_io_select::sel_read_alloc_ucd_file(), ucd_io_select::sel_read_ucd_file(), and ucd_io_select::sel_write_grd_file().
set_parallel_ucd_file_name()
character(len=kchara) function set_ucd_file_names::set_parallel_ucd_file_name (character(len=kchara), intent(in) file_prefix, integer(kind=kint), intent(in) itype_file, integer, intent(in) id_rank, integer(kind=kint), intent(in) istep_ucd)
Definition at line 83 of file set_ucd_file_names.f90.
References set_mesh_extensions::add_flb_extension(), set_mesh_extensions::add_fld_extension(), set_parallel_file_name::add_gzip_extension(), set_parallel_file_name::add_int_suffix(), set_parallel_file_name::add_process_id(), set_ucd_extensions::add_sdt_extension(), set_ucd_extensions::add_sfm_extension(), set_ucd_extensions::add_ucd_extension(), set_ucd_extensions::add_udt_extension(), set_ucd_extensions::add_vtd_extension(), set_ucd_extensions::add_vtk_extension(), m_constants::icent, m_field_file_format::iflag_ascii, m_field_file_format::iflag_bin, m_field_file_format::iflag_bin_gz, m_field_file_format::iflag_fld_gz, m_field_file_format::iflag_gzip, m_field_file_format::iflag_ucd, m_field_file_format::iflag_ucd_bin, m_field_file_format::iflag_ucd_bin_gz, m_field_file_format::iflag_ucd_gz, m_field_file_format::iflag_udt, m_field_file_format::iflag_udt_bin, m_field_file_format::iflag_udt_bin_gz, m_field_file_format::iflag_udt_gz, m_field_file_format::iflag_vtd, m_field_file_format::iflag_vtd_gz, m_field_file_format::iflag_vtk, m_field_file_format::iflag_vtk_gz, and m_constants::iten.
Referenced by delete_para_ucd_file(), ucd_io_select::sel_read_alloc_ucd_file(), ucd_io_select::sel_read_alloc_udt_file(), ucd_io_select::sel_read_ucd_file(), ucd_io_select::sel_read_udt_file(), ucd_io_select::sel_read_udt_param(), ucd_io_select::sel_write_ucd_file(), ucd_io_select::sel_write_udt_file(), and gz_vtk_file_io::write_gz_parallel_vtk_file().
set_parallel_vtk_file_name()
character(len=kchara) function set_ucd_file_names::set_parallel_vtk_file_name (character(len=kchara), intent(in) file_prefix, integer, intent(in) id_rank, integer(kind=kint), intent(in) istep_ucd)
Definition at line 272 of file set_ucd_file_names.f90.
References set_parallel_file_name::add_int_suffix(), set_parallel_file_name::add_process_id(), and set_ucd_extensions::add_vtk_extension().
Referenced by vtk_file_io::write_parallel_vtk_file().
set_single_grd_file_name()
character(len=kchara) function set_ucd_file_names::set_single_grd_file_name (character(len=kchara), intent(in) file_prefix, integer(kind=kint), intent(in) itype_file)
Definition at line 237 of file set_ucd_file_names.f90.
References set_ucd_extensions::add_grd_extension(), set_parallel_file_name::add_gzip_extension(), set_parallel_file_name::add_int_suffix(), set_ucd_extensions::add_sgd_extension(), set_ucd_extensions::add_vtg_extension(), m_constants::icent, m_field_file_format::iflag_gzip, m_field_file_format::iflag_udt, m_field_file_format::iflag_udt_bin, m_field_file_format::iflag_vtd, m_constants::iten, and m_constants::izero.
set_single_ucd_file_name()
character(len=kchara) function set_ucd_file_names::set_single_ucd_file_name (character(len=kchara), intent(in) file_prefix, integer(kind=kint), intent(in) itype_file, integer(kind=kint), intent(in) istep_ucd)
Definition at line 196 of file set_ucd_file_names.f90.
References set_mesh_extensions::add_fld_extension(), set_parallel_file_name::add_gzip_extension(), set_parallel_file_name::add_int_suffix(), set_ucd_extensions::add_sdt_extension(), set_ucd_extensions::add_sfm_extension(), set_ucd_extensions::add_ucd_extension(), set_ucd_extensions::add_udt_extension(), set_ucd_extensions::add_vtd_extension(), set_ucd_extensions::add_vtk_extension(), m_constants::icent, m_field_file_format::iflag_gzip, m_field_file_format::iflag_ucd, m_field_file_format::iflag_ucd_bin, m_field_file_format::iflag_udt, m_field_file_format::iflag_udt_bin, m_field_file_format::iflag_vtd, m_field_file_format::iflag_vtk, and m_constants::iten.