CALYPSO: mpi_viewer_mesh_io Module Reference
mpi_viewer_mesh_io Module Reference
Viewer mesh file IO for ascii format.
Functions/Subroutines
subroutine mpi_write_viewer_position (IO_param, nnod, numdir, id_global, xx)
subroutine mpi_write_viewer_element_type (IO_param, ncolumn, num, int_dat)
subroutine mpi_write_viewer_connect (IO_param, nele, nnod_4_ele, id_global, ie)
subroutine mpi_write_domain_grp_data (IO_param, view_grp)
subroutine mpi_write_viewer_grp_data (IO_param, num_grp, grp_name, view_grp)
subroutine mpi_write_viewer_grp_item (IO_param, ncolumn, num, int_dat)
Detailed Description
Viewer mesh file IO for ascii format.
      subroutine mpi_write_viewer_position                            &
     &         (IO_param, nnod, numdir, id_global, xx)
      subroutine mpi_write_viewer_element_type                        &
     &         (IO_param, ncolumn, num, int_dat)
      subroutine mpi_write_viewer_connect                             &
     &         (IO_param, nele, nnod_4_ele, id_global, ie)
      subroutine mpi_write_domain_grp_data(IO_param, view_grp)
      subroutine mpi_write_viewer_grp_data                            &
     &         (IO_param, num_grp, grp_name, view_grp)
        type(viewer_group_data), intent(inout) :: view_grp
      subroutine mpi_write_viewer_grp_item                            &
     &         (IO_param, ncolumn, num, int_dat)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
Function/Subroutine Documentation
mpi_write_domain_grp_data()
subroutine mpi_viewer_mesh_io::mpi_write_domain_grp_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(viewer_group_data), intent(in) view_grp)
Definition at line 188 of file MPI_viewer_mesh_IO.f90.
References m_constants::ieight, mpi_ascii_data_io::mpi_write_charahead(), mpi_ascii_data_io::mpi_write_stack_over_domain(), and mpi_write_viewer_grp_item().
Referenced by mpi_viewer_mesh_file_io::write_viewer_mesh_infos().
mpi_write_viewer_connect()
subroutine mpi_viewer_mesh_io::mpi_write_viewer_connect (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) nele, integer(kind=kint), intent(in) nnod_4_ele, integer(kind=kint_gl), dimension(nele), intent(in) id_global, integer(kind=kint), dimension(nele,nnod_4_ele), intent(in) ie)
Definition at line 138 of file MPI_viewer_mesh_IO.f90.
References m_constants::ione, t_calypso_mpi_io_param::istack64_4_parallel_data(), and mpi_ascii_data_io::mpi_write_stack_over_domain().
Referenced by mpi_viewer_mesh_file_io::write_viewer_mesh_infos().
mpi_write_viewer_element_type()
subroutine mpi_viewer_mesh_io::mpi_write_viewer_element_type (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) ncolumn, integer(kind=kint), intent(in) num, integer(kind=kint), dimension(num), intent(in) int_dat)
Definition at line 89 of file MPI_viewer_mesh_IO.f90.
References m_constants::ione, t_calypso_mpi_io_param::istack64_4_parallel_data(), and mpi_ascii_data_io::mpi_write_stack_over_domain().
Referenced by mpi_viewer_mesh_file_io::write_viewer_mesh_infos().
mpi_write_viewer_grp_data()
subroutine mpi_viewer_mesh_io::mpi_write_viewer_grp_data (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint), intent(in) num_grp, character(len=kchara), dimension(num_grp), intent(in) grp_name, type(viewer_group_data), intent(in) view_grp)
Definition at line 210 of file MPI_viewer_mesh_IO.f90.
References calypso_mpi_int::calypso_mpi_allreduce_int(), transfer_to_long_integers::cast_long(), m_constants::ieight, mpi_ascii_data_io::mpi_write_charahead(), mpi_ascii_data_io::mpi_write_stack_over_domain(), and mpi_write_viewer_grp_item().
Referenced by mpi_viewer_mesh_file_io::write_viewer_mesh_infos().
mpi_write_viewer_grp_item()
subroutine mpi_viewer_mesh_io::mpi_write_viewer_grp_item (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) ncolumn, integer(kind=kint), intent(in) num, integer(kind=kint), dimension(num), intent(in) int_dat)
Definition at line 271 of file MPI_viewer_mesh_IO.f90.
References m_constants::ione, t_calypso_mpi_io_param::istack64_4_parallel_data(), and mpi_ascii_data_io::mpi_write_stack_over_domain().
Referenced by mpi_write_domain_grp_data(), and mpi_write_viewer_grp_data().
mpi_write_viewer_position()
subroutine mpi_viewer_mesh_io::mpi_write_viewer_position (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) nnod, integer(kind=kint), intent(in) numdir, integer(kind=kint_gl), dimension(nnod), intent(in) id_global, real(kind=kreal), dimension(nnod, numdir), intent(in) xx)
Definition at line 46 of file MPI_viewer_mesh_IO.f90.
References t_calypso_mpi_io_param::istack64_4_parallel_data(), and mpi_ascii_data_io::mpi_write_stack_over_domain().
Referenced by mpi_viewer_mesh_file_io::write_viewer_mesh_infos().