CALYPSO: gz_element_data_io Module Reference
gz_element_data_io Module Reference
Data IO routines for element data.
Functions/Subroutines
subroutine gz_read_element_comm_table (id_rank, comm_IO, zbuf, ierr)
subroutine gz_write_element_comm_table (id_rank, comm_IO, zbuf)
subroutine gz_read_element_geometry (nod_IO, sfed_IO, zbuf)
subroutine gz_write_element_geometry (nod_IO, sfed_IO, zbuf)
Detailed Description
Data IO routines for element data.
      subroutine gz_read_element_comm_table                           &
     &         (id_rank, comm_IO, zbuf, ierr)
      subroutine gz_write_element_comm_table(id_rank, comm_IO, zbuf)
        type(communication_table), intent(inout) :: comm_IO
        type(buffer_4_gzip), intent(inout) :: zbuf
      subroutine gz_read_element_geometry(nod_IO, sfed_IO, zbuf)
      subroutine gz_write_element_geometry(nod_IO, sfed_IO, zbuf)
        type(node_data), intent(inout) :: nod_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
        type(buffer_4_gzip), intent(inout) :: zbuf
Function/Subroutine Documentation
gz_read_element_comm_table()
subroutine gz_element_data_io::gz_read_element_comm_table (integer, intent(in) id_rank, type(communication_table), intent(inout) comm_IO, type(buffer_4_gzip), intent(inout) zbuf, integer(kind = kint), intent(inout) ierr)
Definition at line 42 of file gz_element_data_IO.f90.
References gz_domain_data_io::gz_read_domain_info(), gz_domain_data_io::gz_read_export_data(), and gz_domain_data_io::gz_read_import_data().
Referenced by gz_element_file_io::gz_input_element_file().
gz_read_element_geometry()
subroutine gz_element_data_io::gz_read_element_geometry (type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 104 of file gz_element_data_IO.f90.
References gz_node_geometry_io::gz_read_geometry_info(), gz_node_geometry_io::gz_read_number_of_node(), and gz_node_geometry_io::gz_read_scalar_in_element().
gz_write_element_comm_table()
subroutine gz_element_data_io::gz_write_element_comm_table (integer, intent(in) id_rank, type(communication_table), intent(in) comm_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 71 of file gz_element_data_IO.f90.
References gz_domain_data_io::gz_write_domain_info(), gz_domain_data_io::gz_write_export_data(), gz_domain_data_io::gz_write_import_data(), gzip_file_access::gz_write_textbuf_no_lf(), m_fem_surface_labels::hd_ecomm_export(), m_fem_surface_labels::hd_ecomm_import(), m_fem_surface_labels::hd_ecomm_para(), and m_fem_mesh_labels::hd_fem_para().
Referenced by gz_element_file_io::gz_output_element_file().
gz_write_element_geometry()
subroutine gz_element_data_io::gz_write_element_geometry (type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 127 of file gz_element_data_IO.f90.
References gz_node_geometry_io::gz_write_geometry_info(), gz_node_geometry_io::gz_write_scalar_in_element(), gzip_file_access::gz_write_textbuf_no_lf(), m_fem_surface_labels::hd_ecomm_point(), and m_fem_surface_labels::hd_ecomm_vol().