CALYPSO: gz_surface_data_io Module Reference
gz_surface_data_io Module Reference
routines for surface mesh data IO
Functions/Subroutines
subroutine gz_read_surface_connection (id_rank, comm_IO, ele_IO, sfed_IO, zbuf, ierr)
subroutine gz_write_surface_connection (id_rank, comm_IO, ele_IO, sfed_IO, zbuf)
subroutine gz_read_surface_geometry (nod_IO, sfed_IO, zbuf)
subroutine gz_write_surface_geometry (nod_IO, sfed_IO, zbuf)
Detailed Description
routines for surface mesh data IO
      subroutine gz_read_surface_connection                           &
     &         (id_rank, comm_IO, ele_IO, sfed_IO, zbuf, ierr)
        type(communication_table), intent(inout) :: comm_IO
        type(element_data), intent(inout) :: ele_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
        type(buffer_4_gzip), intent(inout) :: zbuf
      subroutine gz_write_surface_connection                          &
     &         (id_rank, comm_IO, ele_IO, sfed_IO, zbuf)
        type(communication_table), intent(in) :: comm_IO
        type(element_data), intent(in) :: ele_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
        type(buffer_4_gzip), intent(inout) :: zbuf
      subroutine gz_read_surface_geometry(nod_IO, sfed_IO, zbuf)
        type(node_data), intent(in) :: nod_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
      subroutine gz_write_surface_geometry(nod_IO, sfed_IO, zbuf)
        type(node_data), intent(in) :: nod_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
        type(buffer_4_gzip), intent(inout) :: zbuf
Function/Subroutine Documentation
gz_read_surface_connection()
subroutine gz_surface_data_io::gz_read_surface_connection (integer, intent(in) id_rank, type(communication_table), intent(inout) comm_IO, type(element_data), intent(inout) ele_IO, type(surf_edge_io_data), intent(inout) sfed_IO, type(buffer_4_gzip), intent(inout) zbuf, integer(kind = kint), intent(inout) ierr)
Definition at line 51 of file gz_surface_data_IO.f90.
References gz_domain_data_io::gz_read_domain_info(), gz_element_connect_io::gz_read_element_info(), gz_domain_data_io::gz_read_export_data(), gz_domain_data_io::gz_read_import_data(), gz_element_connect_io::gz_read_number_of_element(), and gz_element_connect_io::gz_read_surface_4_element().
Referenced by gz_element_file_io::gz_input_surface_file().
gz_read_surface_geometry()
subroutine gz_surface_data_io::gz_read_surface_geometry (type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 160 of file gz_surface_data_IO.f90.
References gz_node_geometry_io::gz_read_geometry_info(), gz_node_geometry_io::gz_read_number_of_node(), gz_node_geometry_io::gz_read_scalar_in_element(), and gz_node_geometry_io::gz_read_vector_in_element().
gz_write_surface_connection()
subroutine gz_surface_data_io::gz_write_surface_connection (integer, intent(in) id_rank, type(communication_table), intent(in) comm_IO, type(element_data), intent(in) ele_IO, type(surf_edge_io_data), intent(in) sfed_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 110 of file gz_surface_data_IO.f90.
References gz_domain_data_io::gz_write_domain_info(), gz_element_connect_io::gz_write_element_info(), gz_domain_data_io::gz_write_export_data(), gz_domain_data_io::gz_write_import_data(), gz_element_connect_io::gz_write_surface_4_element(), gzip_file_access::gz_write_textbuf_no_lf(), m_fem_mesh_labels::hd_fem_para(), m_fem_surface_labels::hd_surf_connect(), m_fem_surface_labels::hd_surf_export(), m_fem_surface_labels::hd_surf_import(), m_fem_surface_labels::hd_surf_on_ele(), and m_fem_surface_labels::hd_surf_para().
Referenced by gz_element_file_io::gz_output_surface_file().
gz_write_surface_geometry()
subroutine gz_surface_data_io::gz_write_surface_geometry (type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 194 of file gz_surface_data_IO.f90.
References gz_node_geometry_io::gz_write_geometry_info(), gz_node_geometry_io::gz_write_scalar_in_element(), gzip_file_access::gz_write_textbuf_no_lf(), gz_node_geometry_io::gz_write_vector_in_element(), m_fem_surface_labels::hd_surf_area(), m_fem_surface_labels::hd_surf_norm(), and m_fem_surface_labels::hd_surf_point().