CALYPSO: t_control_array_integer3 Module Reference
t_control_array_integer3 Module Reference
Data Types
type ctl_array_i3
Structure for 2 integers control array.
type read_int3_item
structure of control item with three integers
Functions/Subroutines
subroutine read_integer3_ctl_type (c_buf, label, int3_item)
subroutine write_integer3_ctl_type (id_control, level, label, int3_item)
subroutine copy_integer3_ctl (org_i3, new_i3)
subroutine alloc_control_array_i3 (array_i3)
subroutine dealloc_control_array_i3 (array_i3)
subroutine read_control_array_i3 (id_control, label, array_i3, c_buf)
subroutine write_control_array_i3 (id_control, level, label, array_i3)
subroutine append_control_array_i3 (read_i3, array_i3)
subroutine dup_control_array_i3 (org_i3, tgt_i3)
subroutine copy_control_array_i3 (num_copy, org_i3, tgt_i3)
subroutine append_control_item_i3 (read_i3, array_i3)
Function/Subroutine Documentation
alloc_control_array_i3()
subroutine t_control_array_integer3::alloc_control_array_i3 (type(ctl_array_i3), intent(inout) array_i3)
Definition at line 131 of file t_control_array_integer3.f90.
Referenced by append_control_array_i3(), bcast_control_arrays::bcast_ctl_array_i3(), dup_control_array_i3(), and read_control_array_i3().
append_control_array_i3()
subroutine t_control_array_integer3::append_control_array_i3 (type(read_int3_item), intent(inout) read_i3, type(ctl_array_i3), intent(inout) array_i3)
Definition at line 225 of file t_control_array_integer3.f90.
References alloc_control_array_i3(), append_control_item_i3(), copy_control_array_i3(), and dealloc_control_array_i3().
Referenced by read_control_array_i3().
append_control_item_i3()
subroutine t_control_array_integer3::append_control_item_i3 (type(read_int3_item), intent(in) read_i3, type(ctl_array_i3), intent(inout) array_i3)
Definition at line 281 of file t_control_array_integer3.f90.
Referenced by append_control_array_i3().
copy_control_array_i3()
subroutine t_control_array_integer3::copy_control_array_i3 (integer(kind = kint), intent(in) num_copy, type(ctl_array_i3), intent(in) org_i3, type(ctl_array_i3), intent(inout) tgt_i3)
Definition at line 264 of file t_control_array_integer3.f90.
Referenced by append_control_array_i3(), and dup_control_array_i3().
copy_integer3_ctl()
subroutine t_control_array_integer3::copy_integer3_ctl (type(read_int3_item), intent(in) org_i3, type(read_int3_item), intent(inout) new_i3)
Definition at line 118 of file t_control_array_integer3.f90.
dealloc_control_array_i3()
subroutine t_control_array_integer3::dealloc_control_array_i3 (type(ctl_array_i3), intent(inout) array_i3)
Definition at line 149 of file t_control_array_integer3.f90.
Referenced by append_control_array_i3().
dup_control_array_i3()
subroutine t_control_array_integer3::dup_control_array_i3 (type(ctl_array_i3), intent(in) org_i3, type(ctl_array_i3), intent(inout) tgt_i3)
Definition at line 250 of file t_control_array_integer3.f90.
References alloc_control_array_i3(), and copy_control_array_i3().
read_control_array_i3()
subroutine t_control_array_integer3::read_control_array_i3 (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) label, type(ctl_array_i3), intent(inout) array_i3, type(buffer_for_control), intent(inout) c_buf)
Definition at line 163 of file t_control_array_integer3.f90.
References alloc_control_array_i3(), append_control_array_i3(), t_read_control_elements::check_array_flag(), t_read_control_elements::check_end_array_flag(), t_read_control_elements::load_one_line_from_control(), and read_integer3_ctl_type().
read_integer3_ctl_type()
subroutine t_control_array_integer3::read_integer3_ctl_type (type(buffer_for_control), intent(in) c_buf, character(len=kchara), intent(in) label, type(read_int3_item), intent(inout) int3_item)
Definition at line 80 of file t_control_array_integer3.f90.
References m_machine_parameter::iflag_debug.
Referenced by read_control_array_i3().
write_control_array_i3()
subroutine t_control_array_integer3::write_control_array_i3 (integer(kind = kint), intent(in) id_control, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, type(ctl_array_i3), intent(in) array_i3)
Definition at line 197 of file t_control_array_integer3.f90.
References write_control_elements::write_array_flag_for_ctl(), write_control_elements::write_end_array_flag_for_ctl(), and write_control_elements::write_integer3_ctl_item().
write_integer3_ctl_type()
subroutine t_control_array_integer3::write_integer3_ctl_type (integer(kind = kint), intent(in) id_control, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, type(read_int3_item), intent(in) int3_item)
Definition at line 100 of file t_control_array_integer3.f90.
References write_control_elements::write_integer3_ctl_item().