CALYPSO: set_edge_hash_by_ele Module Reference
set_edge_hash_by_ele Module Reference
Hash table using sum of local node ID.
Functions/Subroutines
subroutine count_edge_hash_4_ele (numele, nnod_4_ele, ie, ntot_id, ntot_list, num_edge_hash, istack_edge_hash, iend_edge_hash)
subroutine set_edge_hash_4_ele (numele, nnod_4_ele, ie, ntot_id, ntot_list, num_edge_hash, istack_edge_hash, iedge_hash)
subroutine count_part_edge_hash_4_ele (numele, nnod_4_ele, ie, numele_part, iele_part, ntot_id, num_edge_hash, istack_edge_hash, iend_edge_hash)
subroutine set_part_edge_hash_4_ele (numele, nnod_4_ele, ie, numele_part, iele_part, ntot_id, ntot_list, num_edge_hash, istack_edge_hash, iedge_hash)
subroutine mark_all_edges_by_ele (numele, nnod_4_ele, ie, ntot_id, ntot_list, istack_edge_hash, iend_edge_hash, iedge_hash, iedge_flag)
subroutine, private set_2nodes_id_on_edge (iele, is, numele, nnod_4_ele, ie, inod)
Detailed Description
Hash table using sum of local node ID.
      subroutine count_edge_hash_4_ele                                &
     &         (numele, nnod_4_ele, ie, ntot_id, ntot_list,           &
     &          num_edge_hash, istack_edge_hash, iend_edge_hash)
      subroutine set_edge_hash_4_ele                                  &
     &         (numele, nnod_4_ele, ie, ntot_id, ntot_list,           &
     &          num_edge_hash, istack_edge_hash, iedge_hash)
      subroutine count_part_edge_hash_4_ele(numele, nnod_4_ele, ie,   &
     &          numele_part, iele_part, ntot_id, num_edge_hash,       &
     &          istack_edge_hash, iend_edge_hash)
      subroutine set_part_edge_hash_4_ele(numele, nnod_4_ele, ie,     &
     &          numele_part, iele_part, ntot_id, ntot_list,           &
     &          num_edge_hash, istack_edge_hash, iedge_hash)
      subroutine mark_all_edges_by_ele(numele, nnod_4_ele, ie,        &
     &          ntot_id, ntot_list, istack_edge_hash, iend_edge_hash, &
     &          iedge_hash, iedge_flag)
Function/Subroutine Documentation
count_edge_hash_4_ele()
subroutine set_edge_hash_by_ele::count_edge_hash_4_ele (integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) nnod_4_ele, integer(kind = kint), dimension(numele,nnod_4_ele), intent(in) ie, integer(kind = kint_gl), intent(in) ntot_id, integer(kind = kint_gl), intent(in) ntot_list, integer(kind = kint_gl), dimension(ntot_id), intent(inout) num_edge_hash, integer(kind = kint_gl), dimension(0:ntot_id), intent(inout) istack_edge_hash, integer(kind = kint_gl), intent(inout) iend_edge_hash)
Definition at line 45 of file set_edge_hash_by_ele.f90.
References m_geometry_constants::nedge_4_ele, and m_geometry_constants::node_on_edge_l.
Referenced by const_edge_data::const_edge_hash_4_ele().
count_part_edge_hash_4_ele()
subroutine set_edge_hash_by_ele::count_part_edge_hash_4_ele (integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) nnod_4_ele, integer(kind = kint), dimension(numele,nnod_4_ele), intent(in) ie, integer(kind = kint), intent(in) numele_part, integer(kind = kint), dimension(numele_part), intent(in) iele_part, integer(kind = kint_gl), intent(in) ntot_id, integer(kind = kint_gl), dimension(ntot_id), intent(inout) num_edge_hash, integer(kind = kint_gl), dimension(0:ntot_id), intent(inout) istack_edge_hash, integer(kind = kint_gl), intent(inout) iend_edge_hash)
Definition at line 126 of file set_edge_hash_by_ele.f90.
References m_geometry_constants::nedge_4_ele, and m_geometry_constants::node_on_edge_l.
Referenced by const_edge_data::const_part_edge_hash_4_ele().
mark_all_edges_by_ele()
subroutine set_edge_hash_by_ele::mark_all_edges_by_ele (integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) nnod_4_ele, integer(kind = kint), dimension(numele,nnod_4_ele), intent(in) ie, integer(kind = kint_gl), intent(in) ntot_id, integer(kind = kint_gl), intent(in) ntot_list, integer(kind = kint_gl), dimension(0:ntot_id), intent(in) istack_edge_hash, integer(kind = kint_gl), intent(in) iend_edge_hash, integer(kind = kint), dimension(ntot_list,2), intent(in) iedge_hash, integer(kind = kint_gl), dimension(ntot_list), intent(inout) iedge_flag)
Definition at line 213 of file set_edge_hash_by_ele.f90.
References set_2nodes_id_on_edge().
Referenced by const_edge_data::const_edge_hash_4_ele(), and const_edge_data::const_part_edge_hash_4_ele().
set_2nodes_id_on_edge()
subroutine, private set_edge_hash_by_ele::set_2nodes_id_on_edge (integer(kind = kint), intent(in) iele, integer(kind = kint), intent(in) is, integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) nnod_4_ele, integer(kind = kint), dimension(numele,nnod_4_ele), intent(in) ie, integer(kind = kint), dimension(2), intent(inout) inod) private
Definition at line 269 of file set_edge_hash_by_ele.f90.
References m_geometry_constants::node_on_edge_l.
Referenced by mark_all_edges_by_ele().
set_edge_hash_4_ele()
subroutine set_edge_hash_by_ele::set_edge_hash_4_ele (integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) nnod_4_ele, integer(kind = kint), dimension(numele,nnod_4_ele), intent(in) ie, integer(kind = kint_gl), intent(in) ntot_id, integer(kind = kint_gl), intent(in) ntot_list, integer(kind = kint_gl), dimension(ntot_id), intent(inout) num_edge_hash, integer(kind = kint_gl), dimension(0:ntot_id), intent(inout) istack_edge_hash, integer(kind = kint), dimension(ntot_list,2), intent(inout) iedge_hash)
Definition at line 88 of file set_edge_hash_by_ele.f90.
References m_geometry_constants::nedge_4_ele, and m_geometry_constants::node_on_edge_l.
Referenced by const_edge_data::const_edge_hash_4_ele().
set_part_edge_hash_4_ele()
subroutine set_edge_hash_by_ele::set_part_edge_hash_4_ele (integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) nnod_4_ele, integer(kind = kint), dimension(numele,nnod_4_ele), intent(in) ie, integer(kind = kint), intent(in) numele_part, integer(kind = kint), dimension(numele_part), intent(in) iele_part, integer(kind = kint_gl), intent(in) ntot_id, integer(kind = kint_gl), intent(in) ntot_list, integer(kind = kint_gl), dimension(ntot_id), intent(inout) num_edge_hash, integer(kind = kint_gl), dimension(0:ntot_id), intent(inout) istack_edge_hash, integer(kind = kint), dimension(ntot_list,2), intent(inout) iedge_hash)
Definition at line 172 of file set_edge_hash_by_ele.f90.
References m_geometry_constants::nedge_4_ele, and m_geometry_constants::node_on_edge_l.
Referenced by const_edge_data::const_part_edge_hash_4_ele().