CALYPSO: surface_data_io_b Module Reference
surface_data_io_b Module Reference
routines for surface mesh data IO
Functions/Subroutines
subroutine read_surface_connection_b (id_rank, bbuf, comm_IO, ele_IO, sfed_IO)
subroutine write_surface_connection_b (id_rank, comm_IO, ele_IO, sfed_IO, bbuf)
subroutine read_surface_geometry_b (bbuf, nod_IO, sfed_IO)
subroutine write_surface_geometry_b (nod_IO, sfed_IO, bbuf)
Detailed Description
routines for surface mesh data IO
      subroutine read_surface_connection_b                            &
     &         (id_rank, bbuf, comm_IO, ele_IO, sfed_IO)
        type(binary_IO_buffer), intent(inout) :: bbuf
        type(communication_table), intent(inout) :: comm_IO
        type(element_data), intent(inout) :: ele_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
      subroutine write_surface_connection_b                           &
     &         (id_rank, comm_IO, ele_IO, sfed_IO, bbuf)
        type(binary_IO_buffer), intent(inout) :: bbuf
        type(communication_table), intent(in) :: comm_IO
        type(element_data), intent(in) :: ele_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
      subroutine read_surface_geometry_b(bbuf, nod_IO, sfed_IO)
        type(binary_IO_buffer), intent(inout) :: bbuf
        type(node_data), intent(inout) :: nod_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
      subroutine write_surface_geometry_b(nod_IO, sfed_IO, bbuf)
        type(node_data), intent(in) :: nod_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
        type(binary_IO_buffer), intent(inout) :: bbuf
Function/Subroutine Documentation
read_surface_connection_b()
subroutine surface_data_io_b::read_surface_connection_b (integer, intent(in) id_rank, type(binary_io_buffer), intent(inout) bbuf, type(communication_table), intent(inout) comm_IO, type(element_data), intent(inout) ele_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 52 of file surface_data_IO_b.f90.
References domain_data_io_b::read_domain_info_b(), element_connect_io_b::read_element_info_b(), domain_data_io_b::read_export_data_b(), domain_data_io_b::read_import_data_b(), element_connect_io_b::read_number_of_element_b(), and element_connect_io_b::read_surface_4_element_b().
Referenced by element_file_io_b::input_surface_file_b().
read_surface_geometry_b()
subroutine surface_data_io_b::read_surface_geometry_b (type(binary_io_buffer), intent(inout) bbuf, type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 119 of file surface_data_IO_b.f90.
References node_geometry_io_b::read_geometry_info_b(), node_geometry_io_b::read_number_of_node_b(), node_geometry_io_b::read_scalar_in_element_b(), and node_geometry_io_b::read_vector_in_element_b().
write_surface_connection_b()
subroutine surface_data_io_b::write_surface_connection_b (integer, intent(in) id_rank, type(communication_table), intent(in) comm_IO, type(element_data), intent(in) ele_IO, type(surf_edge_io_data), intent(in) sfed_IO, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 88 of file surface_data_IO_b.f90.
References domain_data_io_b::write_domain_info_b(), element_connect_io_b::write_element_info_b(), domain_data_io_b::write_export_data_b(), domain_data_io_b::write_import_data_b(), and element_connect_io_b::write_surface_4_element_b().
Referenced by element_file_io_b::output_surface_file_b().
write_surface_geometry_b()
subroutine surface_data_io_b::write_surface_geometry_b (type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 144 of file surface_data_IO_b.f90.
References node_geometry_io_b::write_geometry_info_b(), node_geometry_io_b::write_scalar_in_element_b(), and node_geometry_io_b::write_vector_in_element_b().