CALYPSO: init_radial_infos_sph_mhd Module Reference
init_radial_infos_sph_mhd Module Reference
Coefficients to obtain radial derivatives by finite difference method.
Functions/Subroutines
subroutine init_r_infos_sph_mhd_evo (r_2nd, bc_IO, sph_grps, MHD_BC, ipol, sph, omega_sph, ref_temp, ref_comp, rj_fld, MHD_prop, sph_MHD_bc)
subroutine init_r_infos_sph_mhd (bc_IO, sph_grps, MHD_BC, ipol, sph, omega_sph, ref_temp, ref_comp, rj_fld, MHD_prop, sph_MHD_bc)
subroutine, private set_delta_r_4_sph_mhd (sph_params, sph_rj)
subroutine, private init_reference_temps (ref_param, takepiro, sph_params, sph_rj, i_ref, i_gref, reftemp, rj_fld, sph_bc_S, bcs_S)
Detailed Description
Coefficients to obtain radial derivatives by finite difference method.
      subroutine init_r_infos_sph_mhd_evo                             &
     &         (r_2nd, bc_IO, sph_grps, MHD_BC, ipol, sph, omega_sph, &
     &          ref_temp, ref_comp, rj_fld, MHD_prop, sph_MHD_bc)
      subroutine init_r_infos_sph_mhd                                 &
     &         (bc_IO, sph_grps, MHD_BC, ipol, sph, omega_sph,        &
     &          ref_temp, ref_comp, rj_fld, MHD_prop, sph_MHD_bc)
        type(fdm_matrices), intent(inout) :: r_2nd
        type(boundary_spectra), intent(in) :: bc_IO
        type(sph_group_data), intent(in) :: sph_grps
        type(MHD_BC_lists), intent(in) :: MHD_BC
        type(phys_address), intent(in) :: ipol
        type(sph_grids), intent(in) :: sph
        type(sph_rotation), intent(inout) :: omega_sph
        type(reference_field), intent(inout) :: ref_temp, ref_comp
        type(MHD_evolution_param), intent(inout) :: MHD_prop
        type(sph_MHD_boundary_data), intent(inout) :: sph_MHD_bc
        type(phys_data), intent(inout) :: rj_fld
Parameters
r_hot radius at highest temperature point
r_cold radius at lowest temperature point
temp_hot temperature at highest temperature point
temp_cold temperature at lowest temperature point
rotate(3) rotation vector
Function/Subroutine Documentation
init_r_infos_sph_mhd()
subroutine init_radial_infos_sph_mhd::init_r_infos_sph_mhd (type(boundary_spectra), intent(in) bc_IO, type(sph_group_data), intent(in) sph_grps, type(mhd_bc_lists), intent(in) MHD_BC, type(phys_address), intent(in) ipol, type(sph_grids), intent(in) sph, type(sph_rotation), intent(inout) omega_sph, type(reference_field), intent(inout) ref_temp, type(reference_field), intent(inout) ref_comp, type(phys_data), intent(inout) rj_fld, type(mhd_evolution_param), intent(inout) MHD_prop, type(sph_mhd_boundary_data), intent(inout) sph_MHD_bc)
Definition at line 106 of file init_radial_infos_sph_mhd.f90.
References m_machine_parameter::iflag_debug, m_machine_parameter::iflag_routine_msg, init_reference_temps(), set_bc_sph_mhd::s_set_bc_sph_mhd(), set_delta_r_4_sph_mhd(), and t_poloidal_rotation::set_rot_earth_4_sph().
Referenced by init_r_infos_sph_mhd_evo(), sph_analyzer_add_initial::sph_add_initial_field(), and sph_analyzer_const_initial::sph_const_initial_field().
init_r_infos_sph_mhd_evo()
subroutine init_radial_infos_sph_mhd::init_r_infos_sph_mhd_evo (type(fdm_matrices), intent(inout) r_2nd, type(boundary_spectra), intent(in) bc_IO, type(sph_group_data), intent(in) sph_grps, type(mhd_bc_lists), intent(in) MHD_BC, type(phys_address), intent(in) ipol, type(sph_grids), intent(in) sph, type(sph_rotation), intent(inout) omega_sph, type(reference_field), intent(inout) ref_temp, type(reference_field), intent(inout) ref_comp, type(phys_data), intent(inout) rj_fld, type(mhd_evolution_param), intent(inout) MHD_prop, type(sph_mhd_boundary_data), intent(inout) sph_MHD_bc)
Definition at line 68 of file init_radial_infos_sph_mhd.f90.
References const_fdm_coefs::const_2nd_fdm_matrices(), m_machine_parameter::iflag_debug, init_r_infos_sph_mhd(), and material_property::set_material_property().
Referenced by sph_analyzer_d_bench::sph_init_sph_dbench(), sph_analyzer_snap_w_psf::sph_init_sph_snap_psf(), and sph_analyzer_mhd::sph_initialize_mhd().
init_reference_temps()
subroutine, private init_radial_infos_sph_mhd::init_reference_temps (type(reference_scalar_param), intent(inout) ref_param, type(takepiro_model_param), intent(in) takepiro, type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, integer(kind = kint), intent(in) i_ref, integer(kind = kint), intent(in) i_gref, type(reference_field), intent(inout) reftemp, type(phys_data), intent(inout) rj_fld, type(sph_boundary_type), intent(in) sph_bc_S, type(sph_scalar_boundary_data), intent(inout) bcs_S) private
Definition at line 176 of file init_radial_infos_sph_mhd.f90.
References set_reference_sph_mhd::adjust_sph_temp_bc_by_reftemp(), t_radial_reference_temp::alloc_reft_rj_data(), t_reference_scalar_param::id_sphere_ref_temp, t_reference_scalar_param::id_takepiro_temp, m_machine_parameter::iflag_debug, set_reference_temp_sph::no_ref_temp_sph_mhd(), set_reference_temp_sph::set_ref_temp_sph_mhd(), and set_reference_temp_sph::set_stratified_sph_mhd().
Referenced by init_r_infos_sph_mhd().
set_delta_r_4_sph_mhd()
subroutine, private init_radial_infos_sph_mhd::set_delta_r_4_sph_mhd (type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj) private
Definition at line 157 of file init_radial_infos_sph_mhd.f90.
References set_radius_func_noequi::allocate_dr_rj_noequi(), m_machine_parameter::iflag_debug, m_machine_parameter::iflag_routine_msg, and set_radius_func_noequi::set_dr_for_nonequi().
Referenced by init_r_infos_sph_mhd().