CALYPSO: m_fftw_parameters Module Reference
m_fftw_parameters Module Reference
Variables
integer, parameter fftw_plan = 8
plan ID for fftw
integer, parameter fftw_complex = 8
data size of complex for FFTW3
complex(kind=fftw_complex), parameter ru = (1.0d0, 0.0d0)
Unit real number.
complex(kind=fftw_complex), parameter iu = (0.0d0, 1.0d0)
Unit imaginary number.
integer(kind=4), parameter fftw_estimate = 64
estimation flag for FFTW
integer(kind=4), parameter fftw_measure = 0
Meajor flag for FFTW.
Variable Documentation
fftw_complex
integer, parameter m_fftw_parameters::fftw_complex = 8
data size of complex for FFTW3
Definition at line 21 of file m_fftw_parameters.f90.
fftw_estimate
integer(kind = 4), parameter m_fftw_parameters::fftw_estimate = 64
estimation flag for FFTW
Definition at line 29 of file m_fftw_parameters.f90.
Referenced by fftw3_multi_wrapper::init_4_fftw_mul_smp(), fftw3_wrapper::init_4_fftw_smp(), sph_prt_fftw::init_prt_fftw(), sph_prt_domain_fftw::init_prt_field_fftw(), sph_rtp_fftw::init_rtp_fftw(), sph_rtp_domain_fftw::init_rtp_field_fftw(), t_sph_component_fftw::init_sph_component_fftw(), and t_sph_single_fftw::init_sph_single_fftw().
fftw_measure
integer(kind = 4), parameter m_fftw_parameters::fftw_measure = 0
Meajor flag for FFTW.
Definition at line 31 of file m_fftw_parameters.f90.
fftw_plan
integer, parameter m_fftw_parameters::fftw_plan = 8
plan ID for fftw
Definition at line 19 of file m_fftw_parameters.f90.
iu
complex(kind = fftw_complex), parameter m_fftw_parameters::iu = (0.0d0, 1.0d0)
Unit imaginary number.
Definition at line 26 of file m_fftw_parameters.f90.
Referenced by t_sph_component_fftw::copy_comp_fftw_to_send(), t_sph_single_fftw::copy_single_fftw_to_send(), fftw3_wrapper::fftw_forward_smp(), and fftw3_multi_wrapper::fftw_mul_forward_smp().
ru
complex(kind = fftw_complex), parameter m_fftw_parameters::ru = (1.0d0, 0.0d0)
Unit real number.
Definition at line 24 of file m_fftw_parameters.f90.