CALYPSO: cal_grad_of_sph_vectors Module Reference
cal_grad_of_sph_vectors Module Reference
Evaluate pressure and energy fluxes for snapshots.
Functions/Subroutines
subroutine overwrt_grad_of_vectors_sph (sph, r_2nd, sph_MHD_bc, leg, ipol_dv, rj_fld)
subroutine cal_grad_of_scalars_sph (sph, r_2nd, sph_MHD_bc, leg, ipol_base, ipol_grd, rj_fld)
subroutine, private overwrt_grad_of_vector_sph (sph_rj, r_2nd, sph_bc, g_sph_rj, i_grad_vx, i_grad_vy, i_grad_vz, rj_fld)
Detailed Description
Evaluate pressure and energy fluxes for snapshots.
      subroutine overwrt_grad_of_vectors_sph                          &
     &         (sph, r_2nd, sph_MHD_bc, leg, ipol_dv, rj_fld)
      subroutine cal_grad_of_scalars_sph(sph, r_2nd, sph_MHD_bc,      &
     &          leg, ipol_base, ipol_grd, rj_fld)
        type(sph_grids), intent(in) :: sph
        type(fdm_matrices), intent(in) :: r_2nd
        type(sph_MHD_boundary_data), intent(in)  :: sph_MHD_bc
        type(base_field_address), intent(in) :: ipol_base
        type(diff_vector_address), intent(in) :: ipol_dv
        type(gradient_field_address), intent(in) :: ipol_grd
        type(legendre_4_sph_trans) , intent(in) :: leg
Function/Subroutine Documentation
cal_grad_of_scalars_sph()
subroutine cal_grad_of_sph_vectors::cal_grad_of_scalars_sph (type(sph_grids), intent(in) sph, type(fdm_matrices), intent(in) r_2nd, type(sph_mhd_boundary_data), intent(in) sph_MHD_bc, type(legendre_4_sph_trans), intent(in) leg, type(base_field_address), intent(in) ipol_base, type(gradient_field_address), intent(in) ipol_grd, type(phys_data), intent(inout) rj_fld)
Definition at line 87 of file cal_grad_of_sph_vectors.f90.
References const_sph_radial_grad::const_radial_grad_scalar(), and m_machine_parameter::iflag_debug.
overwrt_grad_of_vector_sph()
subroutine, private cal_grad_of_sph_vectors::overwrt_grad_of_vector_sph (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, integer(kind = kint), intent(in) i_grad_vx, integer(kind = kint), intent(in) i_grad_vy, integer(kind = kint), intent(in) i_grad_vz, type(phys_data), intent(inout) rj_fld) private
Definition at line 129 of file cal_grad_of_sph_vectors.f90.
References const_sph_radial_grad::const_sph_gradient_no_bc().
Referenced by overwrt_grad_of_vectors_sph().
overwrt_grad_of_vectors_sph()
subroutine cal_grad_of_sph_vectors::overwrt_grad_of_vectors_sph (type(sph_grids), intent(in) sph, type(fdm_matrices), intent(in) r_2nd, type(sph_mhd_boundary_data), intent(in) sph_MHD_bc, type(legendre_4_sph_trans), intent(in) leg, type(diff_vector_address), intent(in) ipol_dv, type(phys_data), intent(inout) rj_fld)
Definition at line 48 of file cal_grad_of_sph_vectors.f90.
References overwrt_grad_of_vector_sph().
Referenced by lead_fields_4_sph_mhd::gradients_of_vectors_sph().