CALYPSO: radial_int_for_sph_spec Module Reference
radial_int_for_sph_spec Module Reference
Evaluate radial integration.
Functions/Subroutines
subroutine radial_integration (kg_st, kg_ed, nri, radius, ntot_comp, f_org, f_int)
subroutine, private radial_int_by_trapezoid (nri, kg_st, kg_ed, radius, f_org, f_ctr, f_int)
subroutine, private radial_int_by_simpson (nri, kg_st, kg_ed, radius, f_org, f_ctr, f_int)
subroutine radial_int_matrix_by_simpson (nri, kg_st, kg_ed, radius, a_int, a_ctr)
subroutine radial_int_matrix_by_trapezoid (nri, kg_st, kg_ed, radius, a_int, a_ctr)
Detailed Description
Evaluate radial integration.
      subroutine radial_integration(kg_st, kg_ed, nri, radius,        &
     &         , ntot_comp, f_org, f_int)
  Evaluate radial integration f_int =  \int f_org r^{2} dr
      subroutine radial_int_matrix_by_simpson                         &
     &         (nri, kg_st, kg_ed, radius, a_int, a_ctr)
      subroutine radial_int_by_trapezoid                              &
     &         (nri, kg_st, kg_ed, radius, a_ctr, a_int)
      subroutine radial_int_matrix_by_trapezoid                       &
     &         (nri, kg_st, kg_ed, radius, a_int, a_ctr)
      subroutine radial_int_matrix_by_simpson                         &
     &         (nri, kg_st, kg_ed, radius, a_int, a_ctr)
Parameters
ltr Truncation of spherical harmonics
Function/Subroutine Documentation
radial_int_by_simpson()
subroutine, private radial_int_for_sph_spec::radial_int_by_simpson (integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) kg_st, integer(kind = kint), intent(in) kg_ed, real(kind = kreal), dimension(nri), intent(in) radius, real(kind = kreal), dimension(nri), intent(in) f_org, real(kind = kreal), intent(in) f_ctr, real(kind = kreal), intent(inout) f_int) private
Definition at line 108 of file radial_int_for_sph_spec.f90.
References m_constants::half, and m_constants::zero.
radial_int_by_trapezoid()
subroutine, private radial_int_for_sph_spec::radial_int_by_trapezoid (integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) kg_st, integer(kind = kint), intent(in) kg_ed, real(kind = kreal), dimension(nri), intent(in) radius, real(kind = kreal), dimension(nri), intent(in) f_org, real(kind = kreal), intent(in) f_ctr, real(kind = kreal), intent(inout) f_int) private
Definition at line 76 of file radial_int_for_sph_spec.f90.
References m_constants::half, and m_constants::zero.
Referenced by radial_integration().
radial_int_matrix_by_simpson()
subroutine radial_int_for_sph_spec::radial_int_matrix_by_simpson (integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) kg_st, integer(kind = kint), intent(in) kg_ed, real(kind = kreal), dimension(nri), intent(in) radius, real(kind = kreal), dimension(nri), intent(inout) a_int, real(kind = kreal), intent(inout) a_ctr)
Definition at line 151 of file radial_int_for_sph_spec.f90.
References m_constants::half, and m_constants::zero.
radial_int_matrix_by_trapezoid()
subroutine radial_int_for_sph_spec::radial_int_matrix_by_trapezoid (integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) kg_st, integer(kind = kint), intent(in) kg_ed, real(kind = kreal), dimension(nri), intent(in) radius, real(kind = kreal), dimension(nri), intent(inout) a_int, real(kind = kreal), intent(inout) a_ctr)
Definition at line 192 of file radial_int_for_sph_spec.f90.
References m_constants::half, and m_constants::zero.
radial_integration()
subroutine radial_int_for_sph_spec::radial_integration (integer(kind = kint), intent(in) kg_st, integer(kind = kint), intent(in) kg_ed, integer(kind = kint), intent(in) nri, real(kind = kreal), dimension(nri), intent(in) radius, integer(kind = kint), intent(in) ntot_comp, real(kind = kreal), dimension(0:nri,ntot_comp), intent(in) f_org, real(kind = kreal), dimension(ntot_comp), intent(inout) f_int)
Definition at line 42 of file radial_int_for_sph_spec.f90.
References radial_int_by_trapezoid().
Referenced by volume_average_4_sph::cal_volume_average_sph(), sum_sph_rms_data::sum_sph_layerd_correlate(), and sum_sph_rms_data::sum_sph_layerd_rms().