CALYPSO: gz_mpi_node_geometry_io_b Module Reference
gz_mpi_node_geometry_io_b Module Reference
routines for ASCII data IO for mesh geometry
Functions/Subroutines
subroutine gz_mpi_write_geometry_info_b (IO_param, nod_IO)
subroutine gz_mpi_write_scl_in_ele_b (IO_param, nod_IO, sfed_IO)
subroutine gz_mpi_write_vect_in_ele_b (IO_param, nod_IO, sfed_IO)
subroutine gz_mpi_read_number_of_node_b (IO_param, nod_IO)
subroutine gz_mpi_read_geometry_info_b (IO_param, nod_IO)
subroutine gz_mpi_read_scl_in_ele_b (IO_param, nod_IO, sfed_IO)
subroutine gz_mpi_read_vect_in_ele_b (IO_param, nod_IO, sfed_IO)
Detailed Description
routines for ASCII data IO for mesh geometry
      subroutine gz_mpi_write_geometry_info_b(IO_param, nod_IO)
      subroutine gz_mpi_write_scl_in_ele_b(IO_param, nod_IO, sfed_IO)
      subroutine gz_mpi_write_vect_in_ele_b(IO_param, nod_IO, sfed_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(node_data), intent(in) :: nod_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
      subroutine gz_mpi_read_number_of_node_b(IO_param, nod_IO)
      subroutine gz_mpi_read_geometry_info_b(IO_param, nod_IO)
      subroutine gz_mpi_read_scl_in_ele_b(IO_param, nod_IO, sfed_IO)
      subroutine gz_mpi_read_vect_in_ele_b(IO_param, nod_IO, sfed_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(node_data), intent(inout) :: nod_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
Function/Subroutine Documentation
gz_mpi_read_geometry_info_b()
subroutine gz_mpi_node_geometry_io_b::gz_mpi_read_geometry_info_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(inout) nod_IO)
Definition at line 122 of file gz_MPI_node_geometry_IO_b.f90.
References t_geometry_data::alloc_node_geometry_base(), gz_mpi_binary_data_io::gz_mpi_read_2d_vector_b(), gz_mpi_binary_data_io::gz_mpi_read_int8_vector_b(), and m_phys_constants::n_vector.
Referenced by gz_mpi_edge_data_io_b::gz_mpi_read_edge_geometry_b(), gz_mpi_element_data_io_b::gz_mpi_read_ele_geometry_b(), gz_mpi_mesh_data_io_b::gz_mpi_read_num_node_ele_b(), and gz_mpi_surface_data_io_b::gz_mpi_read_surf_geometry_b().
gz_mpi_read_number_of_node_b()
subroutine gz_mpi_node_geometry_io_b::gz_mpi_read_number_of_node_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(inout) nod_IO)
Definition at line 109 of file gz_MPI_node_geometry_IO_b.f90.
References gz_mpi_binary_datum_io::gz_mpi_read_one_integer_b().
Referenced by gz_mpi_edge_data_io_b::gz_mpi_read_edge_geometry_b(), gz_mpi_element_data_io_b::gz_mpi_read_ele_geometry_b(), gz_mpi_mesh_data_io_b::gz_mpi_read_num_node_b(), gz_mpi_read_scl_in_ele_b(), gz_mpi_surface_data_io_b::gz_mpi_read_surf_geometry_b(), and gz_mpi_read_vect_in_ele_b().
gz_mpi_read_scl_in_ele_b()
subroutine gz_mpi_node_geometry_io_b::gz_mpi_read_scl_in_ele_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 142 of file gz_MPI_node_geometry_IO_b.f90.
References t_surf_edge_io::alloc_ele_scalar_io(), gz_mpi_binary_data_io::gz_mpi_read_1d_vector_b(), and gz_mpi_read_number_of_node_b().
Referenced by gz_mpi_edge_data_io_b::gz_mpi_read_edge_geometry_b(), gz_mpi_element_data_io_b::gz_mpi_read_ele_geometry_b(), and gz_mpi_surface_data_io_b::gz_mpi_read_surf_geometry_b().
gz_mpi_read_vect_in_ele_b()
subroutine gz_mpi_node_geometry_io_b::gz_mpi_read_vect_in_ele_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(inout) nod_IO, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 162 of file gz_MPI_node_geometry_IO_b.f90.
References t_surf_edge_io::alloc_ele_vector_io(), gz_mpi_binary_data_io::gz_mpi_read_2d_vector_b(), gz_mpi_read_number_of_node_b(), and m_phys_constants::n_vector.
Referenced by gz_mpi_edge_data_io_b::gz_mpi_read_edge_geometry_b(), and gz_mpi_surface_data_io_b::gz_mpi_read_surf_geometry_b().
gz_mpi_write_geometry_info_b()
subroutine gz_mpi_node_geometry_io_b::gz_mpi_write_geometry_info_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(in) nod_IO)
Definition at line 47 of file gz_MPI_node_geometry_IO_b.f90.
References gz_mpi_binary_data_io::gz_mpi_write_2d_vector_b(), gz_mpi_binary_data_io::gz_mpi_write_int8_vector_b(), gz_mpi_binary_datum_io::gz_mpi_write_one_integer_b(), and m_phys_constants::n_vector.
Referenced by gz_mpi_edge_data_io_b::gz_mpi_write_edge_geometry_b(), gz_mpi_element_data_io_b::gz_mpi_write_ele_geometry_b(), gz_mpi_mesh_data_io_b::gz_mpi_write_geometry_data_b(), and gz_mpi_surface_data_io_b::gz_mpi_write_surf_geometry_b().
gz_mpi_write_scl_in_ele_b()
subroutine gz_mpi_node_geometry_io_b::gz_mpi_write_scl_in_ele_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 68 of file gz_MPI_node_geometry_IO_b.f90.
References gz_mpi_binary_data_io::gz_mpi_write_1d_vector_b(), and gz_mpi_binary_datum_io::gz_mpi_write_one_integer_b().
Referenced by gz_mpi_edge_data_io_b::gz_mpi_write_edge_geometry_b(), gz_mpi_element_data_io_b::gz_mpi_write_ele_geometry_b(), and gz_mpi_surface_data_io_b::gz_mpi_write_surf_geometry_b().
gz_mpi_write_vect_in_ele_b()
subroutine gz_mpi_node_geometry_io_b::gz_mpi_write_vect_in_ele_b (type(calypso_mpi_io_params), intent(inout) IO_param, type(node_data), intent(in) nod_IO, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 88 of file gz_MPI_node_geometry_IO_b.f90.
References gz_mpi_binary_data_io::gz_mpi_write_2d_vector_b(), gz_mpi_binary_datum_io::gz_mpi_write_one_integer_b(), and m_phys_constants::n_vector.
Referenced by gz_mpi_edge_data_io_b::gz_mpi_write_edge_geometry_b(), and gz_mpi_surface_data_io_b::gz_mpi_write_surf_geometry_b().