CALYPSO: t_control_array_character3 Module Reference
t_control_array_character3 Module Reference
Data Types
type ctl_array_c3
Structure for three charactors control array.
type read_chara3_item
structure of control item with three characters
Functions/Subroutines
subroutine read_character3_ctl_type (c_buf, label, chara3_item)
subroutine write_character3_ctl_type (id_file, level, label, chara3_item)
subroutine copy_character3_ctl (org_c3, new_c3)
subroutine alloc_control_array_c3 (array_c3)
subroutine dealloc_control_array_c3 (array_c3)
subroutine read_control_array_c3 (id_control, label, array_c3, c_buf)
subroutine write_control_array_c3 (id_control, level, label, array_c3)
subroutine append_control_array_c3 (read_c3, array_c3)
subroutine copy_control_array_c3 (num_copy, org_c3, tgt_c3)
subroutine append_control_item_c3 (read_c3, array_c3)
Function/Subroutine Documentation
alloc_control_array_c3()
subroutine t_control_array_character3::alloc_control_array_c3 (type(ctl_array_c3), intent(inout) array_c3)
Definition at line 146 of file t_control_array_character3.f90.
Referenced by append_control_array_c3(), bcast_control_arrays::bcast_ctl_array_c3(), and read_control_array_c3().
append_control_array_c3()
subroutine t_control_array_character3::append_control_array_c3 (type(read_chara3_item), intent(inout) read_c3, type(ctl_array_c3), intent(inout) array_c3)
Definition at line 242 of file t_control_array_character3.f90.
References alloc_control_array_c3(), append_control_item_c3(), copy_control_array_c3(), and dealloc_control_array_c3().
Referenced by add_nodal_fields_ctl::add_phys_name_ctl(), and read_control_array_c3().
append_control_item_c3()
subroutine t_control_array_character3::append_control_item_c3 (type(read_chara3_item), intent(in) read_c3, type(ctl_array_c3), intent(inout) array_c3)
Definition at line 284 of file t_control_array_character3.f90.
Referenced by append_control_array_c3().
copy_character3_ctl()
subroutine t_control_array_character3::copy_character3_ctl (type(read_chara3_item), intent(in) org_c3, type(read_chara3_item), intent(inout) new_c3)
Definition at line 132 of file t_control_array_character3.f90.
copy_control_array_c3()
subroutine t_control_array_character3::copy_control_array_c3 (integer(kind = kint), intent(in) num_copy, type(ctl_array_c3), intent(in) org_c3, type(ctl_array_c3), intent(inout) tgt_c3)
Definition at line 267 of file t_control_array_character3.f90.
Referenced by append_control_array_c3().
dealloc_control_array_c3()
subroutine t_control_array_character3::dealloc_control_array_c3 (type(ctl_array_c3), intent(inout) array_c3)
Definition at line 159 of file t_control_array_character3.f90.
Referenced by append_control_array_c3(), and t_ctl_data_4_fields::dealloc_phys_control().
read_character3_ctl_type()
subroutine t_control_array_character3::read_character3_ctl_type (type(buffer_for_control), intent(in) c_buf, character(len=kchara), intent(in) label, type(read_chara3_item), intent(inout) chara3_item)
Definition at line 77 of file t_control_array_character3.f90.
References m_machine_parameter::iflag_debug.
Referenced by read_control_array_c3().
read_control_array_c3()
subroutine t_control_array_character3::read_control_array_c3 (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) label, type(ctl_array_c3), intent(inout) array_c3, type(buffer_for_control), intent(inout) c_buf)
Definition at line 173 of file t_control_array_character3.f90.
References alloc_control_array_c3(), append_control_array_c3(), t_read_control_elements::check_array_flag(), t_read_control_elements::check_end_array_flag(), t_read_control_elements::load_one_line_from_control(), and read_character3_ctl_type().
Referenced by t_ctl_data_4_fields::read_phys_data_control().
write_character3_ctl_type()
subroutine t_control_array_character3::write_character3_ctl_type (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, type(read_chara3_item), intent(in) chara3_item)
Definition at line 104 of file t_control_array_character3.f90.
References write_control_elements::write_character3_ctl_item().
write_control_array_c3()
subroutine t_control_array_character3::write_control_array_c3 (integer(kind = kint), intent(in) id_control, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, type(ctl_array_c3), intent(in) array_c3)
Definition at line 207 of file t_control_array_character3.f90.
References skip_comment_f::max_len_of_charaarray(), write_control_elements::write_array_flag_for_ctl(), write_control_elements::write_character3_ctl_item(), and write_control_elements::write_end_array_flag_for_ctl().
Referenced by t_ctl_data_4_fields::write_phys_data_control().