CALYPSO: add_base_field_4_sph_trns Module Reference
add_base_field_4_sph_trns Module Reference
Field addresses for spherical harmonics transform in MHD dynamo simulation.
Functions/Subroutines
subroutine add_base_vector_4_mhd_sph_trns (d_rj, ipol_base, iphys_base, b_trns_base, trns)
subroutine add_base_scalar_4_mhd_sph_trns (d_rj, ipol_base, iphys_base, b_trns_base, trns)
subroutine add_base_vector_sph_trns_snap (d_rj, ipol_base, iphys_base, b_trns_base, trns)
subroutine add_base_scalar_sph_trns_snap (d_rj, ipol_base, iphys_base, b_trns_base, trns)
Detailed Description
Field addresses for spherical harmonics transform in MHD dynamo simulation.
      subroutine add_base_vector_4_MHD_sph_trns                       &
     &         (d_rj, ipol_base, iphys_base, b_trns_base, trns)
      subroutine add_base_scalar_4_MHD_sph_trns                       &
     &         (d_rj, ipol_base, iphys_base, b_trns_base, trns)
        type(fluid_property), intent(in) :: fl_prop
        type(conductive_property), intent(in)  :: cd_prop
        type(scalar_property), intent(in) :: ht_prop, cp_prop
        type(phys_data), intent(in) :: d_rj
        type(phys_address), intent(in) :: ipol_base, iphys_base
        type(phys_address), intent(inout) :: b_trns_base
        type(spherical_transform_data), intent(inout) :: trns
      subroutine add_base_vector_sph_trns_snap                        &
     &         (d_rj, ipol_base, iphys_base, b_trns_base, trns)
      subroutine add_base_scalar_sph_trns_snap                        &
     &         (d_rj, ipol_base, iphys_base, b_trns_base, trns)
        type(phys_data), intent(in) :: d_rj
        type(phys_address), intent(in) :: ipol_base, iphys_base
        type(phys_address), intent(inout) :: b_trns_base
        type(spherical_transform_data), intent(inout) :: trns
Function/Subroutine Documentation
add_base_scalar_4_mhd_sph_trns()
subroutine add_base_field_4_sph_trns::add_base_scalar_4_mhd_sph_trns (type(phys_data), intent(in) d_rj, type(base_field_address), intent(in) ipol_base, type(base_field_address), intent(in) iphys_base, type(base_field_address), intent(inout) b_trns_base, type(spherical_transform_data), intent(inout) trns)
Definition at line 96 of file add_base_field_4_sph_trns.f90.
References add_field_to_sph_trans_list::add_field_4_sph_trns_by_pol().
Referenced by address_sph_trans_mhd::bwd_trans_address_mhd().
add_base_scalar_sph_trns_snap()
subroutine add_base_field_4_sph_trns::add_base_scalar_sph_trns_snap (type(phys_data), intent(in) d_rj, type(base_field_address), intent(in) ipol_base, type(base_field_address), intent(in) iphys_base, type(base_field_address), intent(inout) b_trns_base, type(spherical_transform_data), intent(inout) trns)
Definition at line 144 of file add_base_field_4_sph_trns.f90.
References add_field_to_sph_trans_list::add_field_4_sph_trns_by_pol().
Referenced by address_sph_trans_snap::bwd_trans_address_snap().
add_base_vector_4_mhd_sph_trns()
subroutine add_base_field_4_sph_trns::add_base_vector_4_mhd_sph_trns (type(phys_data), intent(in) d_rj, type(base_field_address), intent(in) ipol_base, type(base_field_address), intent(in) iphys_base, type(base_field_address), intent(inout) b_trns_base, type(spherical_transform_data), intent(inout) trns)
Definition at line 49 of file add_base_field_4_sph_trns.f90.
References add_field_to_sph_trans_list::add_field_4_sph_trns_by_pol().
Referenced by add_base_vector_sph_trns_snap(), and address_sph_trans_mhd::bwd_trans_address_mhd().
add_base_vector_sph_trns_snap()
subroutine add_base_field_4_sph_trns::add_base_vector_sph_trns_snap (type(phys_data), intent(in) d_rj, type(base_field_address), intent(in) ipol_base, type(base_field_address), intent(in) iphys_base, type(base_field_address), intent(inout) b_trns_base, type(spherical_transform_data), intent(inout) trns)
Definition at line 126 of file add_base_field_4_sph_trns.f90.
References add_base_vector_4_mhd_sph_trns().
Referenced by address_sph_trans_snap::bwd_trans_address_snap().