CALYPSO: field_block_mpi_io Module Reference
field_block_mpi_io Module Reference
Output merged field file using MPI-IO.
Functions/Subroutines
subroutine write_field_data_mpi (id_fld, ioff_gl, t_IO, nnod, num_field, ntot_comp, ncomp_field, field_name, d_nod, istack_merged)
subroutine read_field_data_mpi (id_fld, num_pe, id_rank, ioff_gl, nnod, num_field, ntot_comp, ncomp_field, field_name, d_nod, istack_merged)
subroutine read_field_names_mpi (id_fld, num_pe, id_rank, ioff_gl, num_field, ncomp_field, field_name, istack_merged)
subroutine, private write_fld_vecotr_mpi (id_fld, ioff_gl, nnod, ncomp, vector, istack_merged)
subroutine, private read_fld_vecotr_mpi (id_fld, num_pe, id_rank, ioff_gl, nnod, ncomp, vector, istack_merged)
subroutine, private skip_fld_vecotr_mpi (num_pe, id_rank, ioff_gl, ncomp, istack_merged)
Detailed Description
Output merged field file using MPI-IO.
      subroutine write_field_data_mpi(id_fld, ioff_gl,                &
     &          t_IO, nnod, num_field, ntot_comp, ncomp_field,        &
     &          field_name, d_nod, istack_merged)
      subroutine read_field_data_mpi(id_fld, num_pe, id_rank,         &
     &          ioff_gl, nnod, num_field, ntot_comp, ncomp_field,     &
     &          field_name, d_nod, istack_merged)
      subroutine read_field_names_mpi(id_fld, num_pe, id_rank,        &
     &          ioff_gl, num_field, ncomp_field, field_name,          &
     &          istack_merged)
Function/Subroutine Documentation
read_field_data_mpi()
subroutine field_block_mpi_io::read_field_data_mpi (integer, intent(in) id_fld, integer, intent(in) num_pe, integer, intent(in) id_rank, integer(kind = kint_gl), intent(inout) ioff_gl, integer(kind = kint_gl), intent(in) nnod, integer(kind = kint), intent(in) num_field, integer(kind = kint), intent(in) ntot_comp, integer(kind = kint), dimension(num_field), intent(in) ncomp_field, character(len = kchara), dimension(num_field), intent(inout) field_name, real(kind = kreal), dimension(nnod,ntot_comp), intent(inout) d_nod, integer(kind = kint_gl), dimension(0:num_pe), intent(in) istack_merged)
Definition at line 88 of file field_block_MPI_IO.f90.
References field_data_mpi_io::read_field_name_mpi(), and read_fld_vecotr_mpi().
Referenced by field_file_mpi_io::read_alloc_step_fld_file_mpi(), ucd_field_mpi_io::read_alloc_ucd_fld_file_mpi(), field_file_mpi_io::read_step_field_file_mpi(), and ucd_field_mpi_io::read_ucd_field_file_mpi().
read_field_names_mpi()
subroutine field_block_mpi_io::read_field_names_mpi (integer, intent(in) id_fld, integer, intent(in) num_pe, integer, intent(in) id_rank, integer(kind = kint_gl), intent(inout) ioff_gl, integer(kind = kint), intent(in) num_field, integer(kind = kint), dimension(num_field), intent(in) ncomp_field, character(len=kchara), dimension(num_field), intent(inout) field_name, integer(kind = kint_gl), dimension(0:num_pe), intent(in) istack_merged)
Definition at line 122 of file field_block_MPI_IO.f90.
References field_data_mpi_io::read_field_name_mpi(), and skip_fld_vecotr_mpi().
Referenced by field_file_mpi_io::read_alloc_step_fld_head_mpi().
read_fld_vecotr_mpi()
subroutine, private field_block_mpi_io::read_fld_vecotr_mpi (integer, intent(in) id_fld, integer, intent(in) num_pe, integer, intent(in) id_rank, integer(kind = kint_gl), intent(inout) ioff_gl, integer(kind = kint_gl), intent(in) nnod, integer(kind = kint), intent(in) ncomp, real(kind = kreal), dimension(nnod,ncomp), intent(inout) vector, integer(kind = kint_gl), dimension(0:num_pe), intent(in) istack_merged) private
Definition at line 193 of file field_block_MPI_IO.f90.
References field_data_io::buffer_istack_nod_buffer(), m_calypso_mpi_io::mpi_read_one_chara_b(), and data_io_to_textline::read_vector_textline().
Referenced by read_field_data_mpi().
skip_fld_vecotr_mpi()
subroutine, private field_block_mpi_io::skip_fld_vecotr_mpi (integer, intent(in) num_pe, integer, intent(in) id_rank, integer(kind = kint_gl), intent(inout) ioff_gl, integer(kind = kint), intent(in) ncomp, integer(kind = kint_gl), dimension(0:num_pe), intent(in) istack_merged) private
Definition at line 236 of file field_block_MPI_IO.f90.
References field_data_io::buffer_istack_nod_buffer().
Referenced by read_field_names_mpi().
write_field_data_mpi()
subroutine field_block_mpi_io::write_field_data_mpi (integer, intent(in) id_fld, integer(kind = kint_gl), intent(inout) ioff_gl, type(time_data), intent(in) t_IO, integer(kind = kint_gl), intent(in) nnod, integer(kind=kint), intent(in) num_field, integer(kind=kint), intent(in) ntot_comp, integer(kind=kint), dimension(num_field), intent(in) ncomp_field, character(len=kchara), dimension(num_field), intent(in) field_name, real(kind = kreal), dimension(nnod,ntot_comp), intent(in) d_nod, integer(kind = kint_gl), dimension(0:nprocs), intent(in) istack_merged)
Definition at line 41 of file field_block_MPI_IO.f90.
References m_calypso_mpi_io::calypso_mpi_seek_write_head_c(), field_data_io::field_comp_buffer(), field_data_io::field_istack_nod_buffer(), field_data_io::field_num_buffer(), time_data_io::step_data_buffer(), field_data_mpi_io::write_field_name_mpi(), and write_fld_vecotr_mpi().
Referenced by field_file_mpi_io::write_step_field_file_mpi(), and ucd_field_mpi_io::write_ucd_field_file_mpi().
write_fld_vecotr_mpi()
subroutine, private field_block_mpi_io::write_fld_vecotr_mpi (integer, intent(in) id_fld, integer(kind = kint_gl), intent(inout) ioff_gl, integer(kind = kint_gl), intent(in) nnod, integer(kind = kint), intent(in) ncomp, real(kind = kreal), dimension(nnod,ncomp), intent(in) vector, integer(kind = kint_gl), dimension(0:nprocs), intent(in) istack_merged) private
Definition at line 153 of file field_block_MPI_IO.f90.
References field_data_io::buffer_istack_nod_buffer(), m_calypso_mpi_io::calypso_mpi_seek_write_head_c(), data_io_to_textline::len_vector_textline(), m_calypso_mpi_io::mpi_write_one_chara_b(), calypso_mpi::my_rank, calypso_mpi::nprocs, and data_io_to_textline::vector_textline().
Referenced by write_field_data_mpi().