CALYPSO: cal_div_of_forces Module Reference
cal_div_of_forces Module Reference
Evaluate divergence of forces for pressure evaluation.
Functions/Subroutines
subroutine sum_div_of_forces (fl_prop, ipol_base, ipol_div_frc, rj_fld)
subroutine, private set_dmhd_terms_to_div_force (is_press, ipol_div_frc, nnod_rj, ntot_phys_rj, d_rj)
subroutine, private set_mhd_terms_to_div_force (is_press, ipol_div_frc, is_div_buo, nnod_rj, ntot_phys_rj, d_rj)
subroutine set_div_dcv_terms_to_force (is_press, ipol_div_frc, nnod_rj, ntot_phys_rj, d_rj)
subroutine, private set_div_cv_terms_to_force (is_press, ipol_div_frc, is_div_buo, nnod_rj, ntot_phys_rj, d_rj)
subroutine add_div_advection_to_force (is_press, is_div, nnod_rj, ntot_phys_rj, d_rj)
subroutine add_term_to_div_force (is_press, is_div, nnod_rj, ntot_phys_rj, d_rj)
Detailed Description
Evaluate divergence of forces for pressure evaluation.
      subroutine sum_div_of_forces                                    &
     &         (fl_prop, ipol_base, ipol_div_frc, rj_fld)
        type(fluid_property), intent(in) :: fl_prop
        type(phys_address), intent(in) :: ipol
        type(base_field_address), intent(in) :: ipol_base
        type(base_force_address), intent(in) :: ipol_div_frc
        type(phys_data), intent(inout) :: rj_fld
      subroutine add_div_advection_to_force                           &
     &         (is_press, is_div, nnod_rj, ntot_phys_rj, d_rj)
      subroutine add_term_to_div_force                                &
     &          (is_press, is_div, nnod_rj, ntot_phys_rj, d_rj)
Function/Subroutine Documentation
add_div_advection_to_force()
subroutine cal_div_of_forces::add_div_advection_to_force (integer(kind = kint), intent(in) is_press, integer(kind = kint), intent(in) is_div, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 238 of file cal_div_of_forces.f90.
add_term_to_div_force()
subroutine cal_div_of_forces::add_term_to_div_force (integer(kind = kint), intent(in) is_press, integer(kind = kint), intent(in) is_div, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 258 of file cal_div_of_forces.f90.
Referenced by sum_div_of_forces().
set_div_cv_terms_to_force()
subroutine, private cal_div_of_forces::set_div_cv_terms_to_force (integer(kind = kint), intent(in) is_press, type(base_force_address), intent(in) ipol_div_frc, integer(kind = kint), intent(in) is_div_buo, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj) private
Definition at line 213 of file cal_div_of_forces.f90.
Referenced by sum_div_of_forces().
set_div_dcv_terms_to_force()
subroutine cal_div_of_forces::set_div_dcv_terms_to_force (integer(kind = kint), intent(in) is_press, type(base_force_address), intent(in) ipol_div_frc, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj)
Definition at line 189 of file cal_div_of_forces.f90.
Referenced by sum_div_of_forces().
set_dmhd_terms_to_div_force()
subroutine, private cal_div_of_forces::set_dmhd_terms_to_div_force (integer(kind = kint), intent(in) is_press, type(base_force_address), intent(in) ipol_div_frc, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj) private
Definition at line 139 of file cal_div_of_forces.f90.
Referenced by sum_div_of_forces().
set_mhd_terms_to_div_force()
subroutine, private cal_div_of_forces::set_mhd_terms_to_div_force (integer(kind = kint), intent(in) is_press, type(base_force_address), intent(in) ipol_div_frc, integer(kind = kint), intent(in) is_div_buo, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(nnod_rj,ntot_phys_rj), intent(inout) d_rj) private
Definition at line 164 of file cal_div_of_forces.f90.
Referenced by sum_div_of_forces().
sum_div_of_forces()
subroutine cal_div_of_forces::sum_div_of_forces (type(fluid_property), intent(in) fl_prop, type(base_field_address), intent(in) ipol_base, type(base_force_address), intent(in) ipol_div_frc, type(phys_data), intent(inout) rj_fld)
Definition at line 41 of file cal_div_of_forces.f90.
References add_term_to_div_force(), copy_nodal_fields::clear_field_data(), set_div_cv_terms_to_force(), set_div_dcv_terms_to_force(), set_dmhd_terms_to_div_force(), and set_mhd_terms_to_div_force().
Referenced by lead_fields_4_sph_mhd::pressure_4_sph_mhd().