CALYPSO: m_ludcmp_band Module Reference
m_ludcmp_band Module Reference
linear solver using LU decompotion for band matrix
Functions/Subroutines
subroutine ludcmp_band (n, nband, band_a, band_lu, indx, d)
subroutine lubksb_band (n, nband, band_lu, indx, x)
subroutine lubksb_band_mul (Msmp, Msmp_stack, mcomp, n, nband, band_lu, indx, x)
subroutine set_band_mt_2_mat (n, np, nband, band_a, a)
subroutine set_mt_2_band_mat (n, np, nband, a, band_a)
Detailed Description
linear solver using LU decompotion for band matrix
---------------------------------------------------------------------
      SUBROUTINE ludcmp_band(n, nband, band_a, band_lu ,indx, d)
 Given a matrix a(1:n,1:n), with physical dimension n by n,
 this routine replaces it by the LU decomposition of a rowwise
 permutation of itself. a and n are input.
 a is output, arranged as in equation (2.3.14) above; index(1:n)
 is an output vector that records the row permutation effected by
 partial povoting; dis output as +/- 1 depending on whether
 the number of row interchanges was even or odd, respectively.
 This routine is used in combination with lubksb to solve
 linear equations or ivert a matrix.
      SUBROUTINE lubksb_band(n, nband, band_lu, indx, x)
      SUBROUTINE lubksb_band_mul(Msmp, Msmp_stack, mcomp, n, nband, &
     &          band_lu, indx, x)
 solve the set of n linear equations Ax=b. Here is a input,
 not at the matrix A but rather as its LU decompsition,
 determined by the routine ludcmp. i_pivot is input as the
 permutation vector returned by ludcmp. x(1:n) is input
 as the right-hand side vectror b, and returns with the
 solution vector x.
 a, n,  and i_pivot are not modified by this routine
 and be left in place for successive calls with different
 right hand sides b. This routine takes into account
 the possibility that b will begin with many zero elements,
 so it is efficient for use in matrix inversion.
   data converter between general matrix and band matrix
      subroutine set_band_mt_2_mat(n, np, nband, band_a, a)
      subroutine set_mt_2_band_mat(n, np, nband, a, band_a)
      Example: data format of 3-band matrix
               | a(2,1)  a(1,2)  ........     0         0     |
               | a(3,1)  a(2,2)  ........     .         .     |
               |   0     a(3,2)  ........     .         .     |
    a(i,j)  =  |   .       0     ........     0         .     |
               | ...... a(3,k-1)  a(2,k)  a(1,k+1) .......... |
               |   .       .     ........  a(1,N-2)     0     |
               |   .       .     ........  a(2,N-2)  a(1,N-1) |
               |   0       0     ........  a(3,N-2)  a(2,N-1) |
   Original band matrix (band width: nb1)
      nb1 = = (nband-1) / 2
      band_a(i-j+nb1+1,j) = a(i,j)
      band_a(k,j) = a(k+j-nb1-1,j)
      nb2 = nband-1
      band_lu(i-j+nb2+1,j) = a(i,j)
      band_lu(k,j) = a(k+j-nb2-1,j)
---------------------------------------------------------------------
Function/Subroutine Documentation
lubksb_band()
subroutine m_ludcmp_band::lubksb_band (integer (kind = kint), intent(in) n, integer (kind = kint), intent(in) nband, real(kind = kreal), dimension(2*nband-1,n), intent(inout) band_lu, integer (kind = kint), dimension(n), intent(in) indx, real(kind = kreal), dimension(n), intent(inout) x)
Definition at line 210 of file m_ludcmp_band.f90.
References m_constants::ione.
lubksb_band_mul()
subroutine m_ludcmp_band::lubksb_band_mul (integer (kind = kint), intent(in) Msmp, integer (kind = kint), dimension(0:msmp), intent(in) Msmp_stack, integer (kind = kint), intent(in) mcomp, integer (kind = kint), intent(in) n, integer (kind = kint), intent(in) nband, real(kind = kreal), dimension(2*nband-1,n,mcomp), intent(inout) band_lu, integer (kind = kint), dimension(n,mcomp), intent(in) indx, real(kind = kreal), dimension(mcomp,n), intent(inout) x)
Definition at line 263 of file m_ludcmp_band.f90.
References m_constants::ione.
ludcmp_band()
subroutine m_ludcmp_band::ludcmp_band (integer (kind = kint), intent(in) n, integer (kind = kint), intent(in) nband, real(kind = kreal), dimension(nband,n), intent(in) band_a, real(kind = kreal), dimension(2*nband-1,n), intent(inout) band_lu, integer (kind = kint), dimension(n), intent(inout) indx, real(kind = kreal), intent(inout) d)
Definition at line 83 of file m_ludcmp_band.f90.
References m_constants::ione, and m_constants::tiny.
Referenced by t_sph_center_matrix::ludcmp_5band_ctr(), ludcmp_357band_mul::ludcmp_5band_mul(), t_sph_matrix::ludcmp_5band_type(), t_sph_center_matrix::ludcmp_7band_ctr(), ludcmp_357band_mul::ludcmp_7band_mul(), and t_sph_matrix::ludcmp_7band_type().
set_band_mt_2_mat()
subroutine m_ludcmp_band::set_band_mt_2_mat (integer (kind = kint), intent(in) n, integer (kind = kint), intent(in) np, integer (kind = kint), intent(in) nband, real(kind = kreal), dimension(nband,n), intent(in) band_a, real(kind = kreal), dimension(np,np), intent(inout) a)
Definition at line 332 of file m_ludcmp_band.f90.
References m_constants::ione.
set_mt_2_band_mat()
subroutine m_ludcmp_band::set_mt_2_band_mat (integer (kind = kint), intent(in) n, integer (kind = kint), intent(in) np, integer (kind = kint), intent(in) nband, real(kind = kreal), dimension(np,np), intent(in) a, real(kind = kreal), dimension(nband,n), intent(inout) band_a)
Definition at line 354 of file m_ludcmp_band.f90.
References m_constants::ione.