CALYPSO: element_connect_io Module Reference
element_connect_io Module Reference
Data IO routines for element connectivity.
Functions/Subroutines
subroutine write_element_info (id_file, ele_IO)
subroutine write_surface_4_element (id_file, sfed_IO)
subroutine write_edge_4_element (id_file, sfed_IO)
subroutine read_number_of_element (id_file, ele_IO)
subroutine read_element_info (id_file, ele_IO)
subroutine read_surface_4_element (id_file, sfed_IO)
subroutine read_edge_4_element (id_file, sfed_IO)
Variables
character(len=255), private character_4_read
Detailed Description
Data IO routines for element connectivity.
      subroutine write_element_info(id_file, ele_IO)
        type(element_data), intent(in) :: ele_IO
      subroutine write_surface_4_element(id_file, sfed_IO)
      subroutine write_edge_4_element(id_file, sfed_IO)
        type(surf_edge_IO_data), intent(in) :: sfed_IO
      subroutine read_number_of_element(id_file, ele_IO)
      subroutine read_element_info(id_file, ele_IO)
        type(element_data), intent(inout) :: ele_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
      subroutine read_surface_4_element(id_file, sfed_IO)
      subroutine read_edge_4_element(id_file, sfed_IO)
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
Parameters
id_file File ID
Function/Subroutine Documentation
read_edge_4_element()
subroutine element_connect_io::read_edge_4_element (integer (kind = kint), intent(in) id_file, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 170 of file element_connect_IO.f90.
References t_surf_edge_io::alloc_edge_connect_io().
Referenced by edge_data_io::read_edge_connection().
read_element_info()
subroutine element_connect_io::read_element_info (integer (kind = kint), intent(in) id_file, type(element_data), intent(inout) ele_IO)
Definition at line 119 of file element_connect_IO.f90.
References t_geometry_data::alloc_ele_connectivity(), t_geometry_data::alloc_element_types(), and set_nnod_4_ele_by_type::s_set_nnod_4_ele_by_type().
Referenced by edge_data_io::read_edge_connection(), mesh_data_io::read_geometry_data(), and surface_data_io::read_surface_connection().
read_number_of_element()
subroutine element_connect_io::read_number_of_element (integer (kind = kint), intent(in) id_file, type(element_data), intent(inout) ele_IO)
Definition at line 103 of file element_connect_IO.f90.
References character_4_read, and skip_comment_f::skip_comment().
Referenced by edge_data_io::read_edge_connection(), mesh_data_io::read_num_node_ele(), and surface_data_io::read_surface_connection().
read_surface_4_element()
subroutine element_connect_io::read_surface_4_element (integer (kind = kint), intent(in) id_file, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 151 of file element_connect_IO.f90.
References t_surf_edge_io::alloc_surface_connect_io().
Referenced by edge_data_io::read_edge_connection(), and surface_data_io::read_surface_connection().
write_edge_4_element()
subroutine element_connect_io::write_edge_4_element (integer (kind = kint), intent(in) id_file, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 84 of file element_connect_IO.f90.
Referenced by edge_data_io::write_edge_connection().
write_element_info()
subroutine element_connect_io::write_element_info (integer (kind = kint), intent(in) id_file, type(element_data), intent(in) ele_IO)
Definition at line 46 of file element_connect_IO.f90.
Referenced by edge_data_io::write_edge_connection(), mesh_data_io::write_geometry_data(), and surface_data_io::write_surface_connection().
write_surface_4_element()
subroutine element_connect_io::write_surface_4_element (integer (kind = kint), intent(in) id_file, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 66 of file element_connect_IO.f90.
Referenced by edge_data_io::write_edge_connection(), and surface_data_io::write_surface_connection().
Variable Documentation
character_4_read
character(len=255), private element_connect_io::character_4_read private
Definition at line 37 of file element_connect_IO.f90.
Referenced by read_number_of_element().