CALYPSO: set_address_sph_trans_snap Module Reference
set_address_sph_trans_snap Module Reference
Field addresses for spherical harmonics transform in MHD dynamo simulation.
Functions/Subroutines
subroutine set_addresses_snapshot_trans (d_rj, ipol, iphys, trns_snap, ncomp_sph_trans, nvector_sph_trans, nscalar_sph_trans)
subroutine set_addresses_ene_flux_trans (d_rj, ipol, iphys, trns_eflux, ncomp_sph_trans, nvector_sph_trans, nscalar_sph_trans)
subroutine set_addresses_diff_vect_trans (d_rj, ipol, iphys, trns_difv, ncomp_sph_trans, nvector_sph_trans, nscalar_sph_trans)
subroutine copy_field_from_transform (sph_params, sph_rtp, backward, mesh, nod_fld)
subroutine copy_force_from_transform (sph_params, sph_rtp, forward, mesh, nod_fld)
Detailed Description
Field addresses for spherical harmonics transform in MHD dynamo simulation.
      subroutine set_addresses_snapshot_trans                         &
     &         (d_rj, ipol, iphys, trns_snap,                         &
     &          ncomp_sph_trans, nvector_sph_trans, nscalar_sph_trans)
        type(phys_data), intent(in) :: d_rj
        type(phys_address), intent(in) :: ipol, iphys
        type(address_4_sph_trans), intent(inout) :: trns_snap
      subroutine set_addresses_ene_flux_trans                         &
     &         (d_rj, ipol, iphys, trns_eflux,                        &
     &          ncomp_sph_trans, nvector_sph_trans, nscalar_sph_trans)
        type(phys_data), intent(in) :: d_rj
        type(phys_address), intent(in) :: ipol, iphys
        type(address_4_sph_trans), intent(inout) :: trns_eflux
      subroutine set_addresses_diff_vect_trans                        &
     &         (d_rj, ipol, iphys, trns_difv,                         &
     &          ncomp_sph_trans, nvector_sph_trans, nscalar_sph_trans)
        type(phys_data), intent(in) :: d_rj
        type(phys_address), intent(in) :: ipol, iphys
        type(address_4_sph_trans), intent(inout) :: trns_difv
      subroutine copy_field_from_transform                            &
     &         (sph_params, sph_rtp, backward, mesh, nod_fld)
      subroutine copy_force_from_transform                            &
     &         (sph_params, sph_rtp, forward, mesh, nod_fld)
        type(sph_shell_parameters), intent(in) :: sph_params
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(spherical_transform_data), intent(in) :: forward
        type(mesh_geometry), intent(in) :: mesh
        type(phys_data), intent(inout) :: nod_fld
Function/Subroutine Documentation
copy_field_from_transform()
subroutine set_address_sph_trans_snap::copy_field_from_transform (type(sph_shell_parameters), intent(in) sph_params, type(sph_rtp_grid), intent(in) sph_rtp, type(spherical_transform_data), intent(in) backward, type(mesh_geometry), intent(in) mesh, type(phys_data), intent(inout) nod_fld)
Definition at line 192 of file set_address_sph_trans_snap.f90.
References copy_fields_from_sph_trans::copy_scalar_from_snap_trans(), and copy_fields_from_sph_trans::copy_vector_from_snap_trans().
Referenced by fem_analyzer_sph_mhd::sph_to_fem_bridge_mhd().
copy_force_from_transform()
subroutine set_address_sph_trans_snap::copy_force_from_transform (type(sph_shell_parameters), intent(in) sph_params, type(sph_rtp_grid), intent(in) sph_rtp, type(spherical_transform_data), intent(in) forward, type(mesh_geometry), intent(in) mesh, type(phys_data), intent(inout) nod_fld)
Definition at line 223 of file set_address_sph_trans_snap.f90.
References copy_fields_from_sph_trans::copy_scalar_from_snap_force(), and copy_fields_from_sph_trans::copy_vector_from_snap_force().
Referenced by fem_analyzer_sph_mhd::sph_to_fem_bridge_mhd().
set_addresses_diff_vect_trans()
subroutine set_address_sph_trans_snap::set_addresses_diff_vect_trans (type(phys_data), intent(in) d_rj, type(phys_address), intent(in) ipol, type(phys_address), intent(in) iphys, type(address_4_sph_trans), intent(inout) trns_difv, integer(kind = kint), intent(inout) ncomp_sph_trans, integer(kind = kint), intent(inout) nvector_sph_trans, integer(kind = kint), intent(inout) nscalar_sph_trans)
Definition at line 147 of file set_address_sph_trans_snap.f90.
References address_sph_trans_snap::bwd_trans_address_diff_vect(), address_sph_trans_snap::fwd_trans_address_diff_vect(), and m_machine_parameter::iflag_debug.
Referenced by init_sphrical_transform_mhd::init_sph_transform_mhd().
set_addresses_ene_flux_trans()
subroutine set_address_sph_trans_snap::set_addresses_ene_flux_trans (type(phys_data), intent(in) d_rj, type(phys_address), intent(in) ipol, type(phys_address), intent(in) iphys, type(address_4_sph_trans), intent(inout) trns_eflux, integer(kind = kint), intent(inout) ncomp_sph_trans, integer(kind = kint), intent(inout) nvector_sph_trans, integer(kind = kint), intent(inout) nscalar_sph_trans)
Definition at line 104 of file set_address_sph_trans_snap.f90.
References address_sph_trans_snap::bwd_trans_address_ene_flux(), address_sph_trans_snap::fwd_trans_address_ene_flux(), and m_machine_parameter::iflag_debug.
Referenced by init_sphrical_transform_mhd::init_sph_transform_mhd().
set_addresses_snapshot_trans()
subroutine set_address_sph_trans_snap::set_addresses_snapshot_trans (type(phys_data), intent(in) d_rj, type(phys_address), intent(in) ipol, type(phys_address), intent(in) iphys, type(address_4_sph_trans), intent(inout) trns_snap, integer(kind = kint), intent(inout) ncomp_sph_trans, integer(kind = kint), intent(inout) nvector_sph_trans, integer(kind = kint), intent(inout) nscalar_sph_trans)
Definition at line 60 of file set_address_sph_trans_snap.f90.
References address_sph_trans_snap::bwd_trans_address_snap(), address_sph_trans_snap::fwd_trans_address_snap(), and m_machine_parameter::iflag_debug.
Referenced by init_sphrical_transform_mhd::init_sph_transform_mhd().