CALYPSO: set_element_list_for_psf Module Reference
set_element_list_for_psf Module Reference
Functions/Subroutines
subroutine allocate_work_4_mark_psf (numele)
subroutine deallocate_work_4_mark_psf
subroutine mark_element_list_4_psf (numele, interior_ele, num_ele_grp, ntot_ele_grp, istack_ele_grp, item_ele_grp, ngrp_area, id_ele_grp_psf)
subroutine count_element_list_4_psf (iele_smp_stack, ele_search)
subroutine set_element_list_4_psf (iele_smp_stack, ele_search)
Variables
integer(kind=kint), dimension(:), allocatable, private imark_ele
integer(kind=kint), dimension(:), allocatable, private nele_search_smp
Function/Subroutine Documentation
allocate_work_4_mark_psf()
subroutine set_element_list_for_psf::allocate_work_4_mark_psf (integer(kind = kint), intent(in) numele)
Definition at line 33 of file set_element_list_for_psf.f90.
References imark_ele, nele_search_smp, and m_machine_parameter::np_smp.
Referenced by search_ele_list_for_psf::set_searched_element_list_4_psf().
count_element_list_4_psf()
subroutine set_element_list_for_psf::count_element_list_4_psf (integer(kind=kint), dimension(0:np_smp), intent(in) iele_smp_stack, type(sect_search_list), intent(inout) ele_search)
Definition at line 109 of file set_element_list_for_psf.f90.
References imark_ele, and nele_search_smp.
Referenced by search_ele_list_for_psf::set_searched_element_list_4_psf().
deallocate_work_4_mark_psf()
subroutine set_element_list_for_psf::deallocate_work_4_mark_psf
Definition at line 50 of file set_element_list_for_psf.f90.
References imark_ele, and nele_search_smp.
Referenced by search_ele_list_for_psf::set_searched_element_list_4_psf().
mark_element_list_4_psf()
subroutine set_element_list_for_psf::mark_element_list_4_psf (integer(kind = kint), intent(in) numele, integer(kind = kint), dimension(numele), intent(in) interior_ele, integer(kind = kint), intent(in) num_ele_grp, integer(kind = kint), intent(in) ntot_ele_grp, integer(kind = kint), dimension(0:num_ele_grp), intent(in) istack_ele_grp, integer(kind = kint), dimension(ntot_ele_grp), intent(in) item_ele_grp, integer(kind = kint), intent(in) ngrp_area, integer(kind = kint), dimension(ngrp_area), intent(in) id_ele_grp_psf)
Definition at line 60 of file set_element_list_for_psf.f90.
References imark_ele.
Referenced by search_ele_list_for_psf::set_searched_element_list_4_psf().
set_element_list_4_psf()
subroutine set_element_list_for_psf::set_element_list_4_psf (integer(kind=kint), dimension(0:np_smp), intent(in) iele_smp_stack, type(sect_search_list), intent(inout) ele_search)
Definition at line 140 of file set_element_list_for_psf.f90.
References imark_ele.
Referenced by search_ele_list_for_psf::set_searched_element_list_4_psf().
Variable Documentation
imark_ele
integer(kind = kint), dimension(:), allocatable, private set_element_list_for_psf::imark_ele private
Definition at line 22 of file set_element_list_for_psf.f90.
Referenced by allocate_work_4_mark_psf(), count_element_list_4_psf(), deallocate_work_4_mark_psf(), mark_element_list_4_psf(), and set_element_list_4_psf().
nele_search_smp
integer(kind = kint), dimension(:), allocatable, private set_element_list_for_psf::nele_search_smp private
Definition at line 23 of file set_element_list_for_psf.f90.
Referenced by allocate_work_4_mark_psf(), count_element_list_4_psf(), and deallocate_work_4_mark_psf().