CALYPSO: t_legendre_work_sym_matmul Module Reference
t_legendre_work_sym_matmul Module Reference
Work array for forward Legendre transform useing mat multi
data are strored communication buffer.
Data Types
type leg_trns_sym_mul_work
Work structure for Legendre trasform by matmul with symmetry.
Functions/Subroutines
subroutine init_legendre_sym_matmul (sph_rtm, sph_rlm, leg, idx_trns, nvector, nscalar, WK_l_sml)
subroutine init_legendre_symmetry (sph_rtm, sph_rlm, leg, idx_trns, WK_l_sml)
subroutine finalize_legendre_sym_matmul (WK_l_sml)
subroutine, private const_symmetric_legendres (jmax_rlm, nth_rtm, mphi_rtm, leg, idx_trns, WK_l_sml)
subroutine, private alloc_hemi_schmidt_rtm (nth_rtm, jmax_rlm, WK_l_sml)
subroutine dealloc_hemi_schmidt_rtm (WK_l_sml)
subroutine, private alloc_leg_vec_sym_matmul (nth_rtm, maxidx_rtm_r_smp, nvector, idx_trns, WK_l_sml)
subroutine, private alloc_leg_scl_sym_matmul (nth_rtm, maxidx_rtm_r_smp, nscalar, idx_trns, WK_l_sml)
subroutine, private dealloc_leg_vec_sym_matmul (WK_l_sml)
subroutine, private dealloc_leg_scl_sym_matmul (WK_l_sml)
subroutine, private alloc_leg_vec_symmetry (nth_rtm, idx_trns, WK_l_sml)
subroutine, private alloc_leg_scl_symmetry (nth_rtm, idx_trns, WK_l_sml)
Detailed Description
Work array for forward Legendre transform useing mat multi
data are strored communication buffer.
      subroutine init_legendre_sym_matmul(sph_rtm, sph_rlm, leg,      &
     &          idx_trns, nvector, nscalar, WK_l_sml)
      subroutine init_legendre_symmetry                               &
     &         (sph_rtm, sph_rlm, leg, idx_trns, WK_l_sml)
        type(sph_rtm_grid), intent(in) :: sph_rtm
        type(sph_rlm_grid), intent(in) :: sph_rlm
        type(legendre_4_sph_trans), intent(in) :: leg
        type(index_4_sph_trans), intent(in) :: idx_trns
        type(leg_trns_sym_mul_work), intent(inout) :: WK_l_sml
      subroutine finalize_legendre_sym_matmul(WK_l_sml)
        type(leg_trns_sym_mul_work), intent(inout) :: WK_l_sml
      subroutine dealloc_hemi_schmidt_rtm(WK_l_sml)
     field data for Legendre transform
       original layout: vr_rtm(l_rtm,m_rtm,k_rtm,icomp)
       size: vr_rtm(nth_rtm,nidx_rtm(1)*ncomp,nidx_rtm(3))
      real(kind = kreal), allocatable :: vr_rtm(:,:,:)
     spectr data for Legendre transform
       original layout: sp_rlm(j_rlm,k_rtm,icomp)
        size: sp_rlm(nidx_rlm(2),nidx_rtm(1)*ncomp)
      real(kind = kreal), allocatable :: sp_rlm(:,:)
Parameters
ncomp Total number of components for spherical transform
nvector Number of vector for spherical transform
nscalar Number of scalar (including tensor components) for spherical transform
Function/Subroutine Documentation
alloc_hemi_schmidt_rtm()
subroutine, private t_legendre_work_sym_matmul::alloc_hemi_schmidt_rtm (integer(kind = kint), intent(in) nth_rtm, integer(kind = kint), intent(in) jmax_rlm, type(leg_trns_sym_mul_work), intent(inout) WK_l_sml) private
Definition at line 242 of file t_legendre_work_sym_matmul.f90.
Referenced by const_symmetric_legendres().
alloc_leg_scl_sym_matmul()
subroutine, private t_legendre_work_sym_matmul::alloc_leg_scl_sym_matmul (integer(kind = kint), intent(in) nth_rtm, integer(kind = kint), intent(in) maxidx_rtm_r_smp, integer(kind = kint), intent(in) nscalar, type(index_4_sph_trans), intent(in) idx_trns, type(leg_trns_sym_mul_work), intent(inout) WK_l_sml) private
Definition at line 319 of file t_legendre_work_sym_matmul.f90.
References m_machine_parameter::np_smp.
Referenced by init_legendre_sym_matmul().
alloc_leg_scl_symmetry()
subroutine, private t_legendre_work_sym_matmul::alloc_leg_scl_symmetry (integer(kind = kint), intent(in) nth_rtm, type(index_4_sph_trans), intent(in) idx_trns, type(leg_trns_sym_mul_work), intent(inout) WK_l_sml) private
Definition at line 416 of file t_legendre_work_sym_matmul.f90.
References m_machine_parameter::np_smp.
Referenced by init_legendre_symmetry().
alloc_leg_vec_sym_matmul()
subroutine, private t_legendre_work_sym_matmul::alloc_leg_vec_sym_matmul (integer(kind = kint), intent(in) nth_rtm, integer(kind = kint), intent(in) maxidx_rtm_r_smp, integer(kind = kint), intent(in) nvector, type(index_4_sph_trans), intent(in) idx_trns, type(leg_trns_sym_mul_work), intent(inout) WK_l_sml) private
Definition at line 278 of file t_legendre_work_sym_matmul.f90.
References m_machine_parameter::np_smp.
Referenced by init_legendre_sym_matmul().
alloc_leg_vec_symmetry()
subroutine, private t_legendre_work_sym_matmul::alloc_leg_vec_symmetry (integer(kind = kint), intent(in) nth_rtm, type(index_4_sph_trans), intent(in) idx_trns, type(leg_trns_sym_mul_work), intent(inout) WK_l_sml) private
Definition at line 379 of file t_legendre_work_sym_matmul.f90.
References m_machine_parameter::np_smp.
Referenced by init_legendre_symmetry().
const_symmetric_legendres()
subroutine, private t_legendre_work_sym_matmul::const_symmetric_legendres (integer(kind = kint), intent(in) jmax_rlm, integer(kind = kint), intent(in) nth_rtm, integer(kind = kint), intent(in) mphi_rtm, type(legendre_4_sph_trans), intent(in) leg, type(index_4_sph_trans), intent(in) idx_trns, type(leg_trns_sym_mul_work), intent(inout) WK_l_sml) private
Definition at line 215 of file t_legendre_work_sym_matmul.f90.
References alloc_hemi_schmidt_rtm(), set_legendre_matrices::set_symmetric_legendre_jl(), and set_legendre_matrices::set_symmetric_legendre_lj().
Referenced by init_legendre_sym_matmul(), and init_legendre_symmetry().
dealloc_hemi_schmidt_rtm()
subroutine t_legendre_work_sym_matmul::dealloc_hemi_schmidt_rtm (type(leg_trns_sym_mul_work), intent(inout) WK_l_sml)
Definition at line 266 of file t_legendre_work_sym_matmul.f90.
Referenced by finalize_legendre_sym_matmul().
dealloc_leg_scl_sym_matmul()
subroutine, private t_legendre_work_sym_matmul::dealloc_leg_scl_sym_matmul (type(leg_trns_sym_mul_work), intent(inout) WK_l_sml) private
Definition at line 366 of file t_legendre_work_sym_matmul.f90.
Referenced by finalize_legendre_sym_matmul().
dealloc_leg_vec_sym_matmul()
subroutine, private t_legendre_work_sym_matmul::dealloc_leg_vec_sym_matmul (type(leg_trns_sym_mul_work), intent(inout) WK_l_sml) private
Definition at line 343 of file t_legendre_work_sym_matmul.f90.
Referenced by finalize_legendre_sym_matmul().
finalize_legendre_sym_matmul()
subroutine t_legendre_work_sym_matmul::finalize_legendre_sym_matmul (type(leg_trns_sym_mul_work), intent(inout) WK_l_sml)
Definition at line 201 of file t_legendre_work_sym_matmul.f90.
References dealloc_hemi_schmidt_rtm(), dealloc_leg_scl_sym_matmul(), and dealloc_leg_vec_sym_matmul().
Referenced by t_legendre_trans_select::sel_finalize_legendre_trans().
init_legendre_sym_matmul()
subroutine t_legendre_work_sym_matmul::init_legendre_sym_matmul (type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(legendre_4_sph_trans), intent(in) leg, type(index_4_sph_trans), intent(in) idx_trns, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(leg_trns_sym_mul_work), intent(inout) WK_l_sml)
Definition at line 150 of file t_legendre_work_sym_matmul.f90.
References alloc_leg_scl_sym_matmul(), alloc_leg_vec_sym_matmul(), and const_symmetric_legendres().
Referenced by t_legendre_trans_select::sel_init_legendre_trans().
init_legendre_symmetry()
subroutine t_legendre_work_sym_matmul::init_legendre_symmetry (type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(legendre_4_sph_trans), intent(in) leg, type(index_4_sph_trans), intent(in) idx_trns, type(leg_trns_sym_mul_work), intent(inout) WK_l_sml)
Definition at line 177 of file t_legendre_work_sym_matmul.f90.
References alloc_leg_scl_symmetry(), alloc_leg_vec_symmetry(), and const_symmetric_legendres().
Referenced by t_legendre_trans_select::sel_init_legendre_trans().