CALYPSO: set_ucd_data_to_type Module Reference
set_ucd_data_to_type Module Reference
Link field structure data to IO structure for data IO.
Functions/Subroutines
subroutine link_local_mesh_2_ucd (node, ele, ucd)
subroutine link_global_mesh_2_ucd (node, ele, ucd)
subroutine link_node_data_2_ucd (node, ucd)
subroutine link_ele_data_2_ucd (ele, ucd)
subroutine link_num_field_2_ucd (phys_nod, ucd)
subroutine link_field_data_to_ucd (phys_nod, ucd)
subroutine link_nnod_stacks_2_ucd (num_pe, node, ucd)
subroutine link_nele_stacks_2_ucd (num_pe, ele, ucd)
subroutine alloc_phys_name_type_by_output (ucd, phys_nod)
subroutine alloc_phys_data_type_by_output (ucd, node, phys_nod)
Detailed Description
Link field structure data to IO structure for data IO.
      subroutine link_local_mesh_2_ucd(node, ele, ucd)
      subroutine link_global_mesh_2_ucd(node, ele, ucd)
      subroutine link_num_field_2_ucd(ele, ucd)
      subroutine link_node_data_2_ucd(node, ucd)
      subroutine link_ele_data_2_ucd(ele, ucd)
      subroutine link_field_data_to_ucd(node, phys_nod, ucd)
      subroutine link_nnod_stacks_2_ucd(num_pe, node, ucd)
      subroutine link_nele_stacks_2_ucd(num_pe, ele, ucd)
        type(ucd_data), intent(inout) :: ucd
      subroutine alloc_phys_name_type_by_output(ucd, phys_nod)
      subroutine alloc_phys_data_type_by_output(ucd, node, phys_nod)
        type(node_data), intent(in) :: node
        type(element_data), intent(in) :: ele
        type(phys_data), intent(in) :: nod_fld
        type(ucd_data), intent(inout) :: ucd
Function/Subroutine Documentation
alloc_phys_data_type_by_output()
subroutine set_ucd_data_to_type::alloc_phys_data_type_by_output (type(ucd_data), intent(in) ucd, type(node_data), intent(in) node, type(phys_data), intent(inout) phys_nod)
Definition at line 208 of file set_ucd_data_to_type.f90.
References t_phys_data::alloc_phys_data_type(), and alloc_phys_name_type_by_output().
Referenced by load_mesh_and_field_4_viz::mesh_setup_4_viz().
alloc_phys_name_type_by_output()
subroutine set_ucd_data_to_type::alloc_phys_name_type_by_output (type(ucd_data), intent(in) ucd, type(phys_data), intent(inout) phys_nod)
Definition at line 181 of file set_ucd_data_to_type.f90.
References t_phys_data::alloc_phys_name_type(), m_constants::izero, and cal_minmax_and_stacks::s_cal_total_and_stacks().
Referenced by alloc_phys_data_type_by_output().
link_ele_data_2_ucd()
subroutine set_ucd_data_to_type::link_ele_data_2_ucd (type(element_data), intent(in) ele, type(ucd_data), intent(inout) ucd)
Definition at line 100 of file set_ucd_data_to_type.f90.
References set_ucd_data::link_ele_data_2_output().
Referenced by output_4_psf::output_isosurface(), and output_4_psf::output_section_mesh().
link_field_data_to_ucd()
subroutine set_ucd_data_to_type::link_field_data_to_ucd (type(phys_data), intent(in) phys_nod, type(ucd_data), intent(inout) ucd)
Definition at line 130 of file set_ucd_data_to_type.f90.
References set_ucd_data::link_field_data_2_output().
Referenced by output_parallel_ucd_file::link_output_grd_file(), output_parallel_ucd_file::link_output_ucd_file_once(), output_4_psf::output_isosurface(), output_4_psf::output_section_mesh(), and output_parallel_ucd_file::output_udt_one_snapshot().
link_global_mesh_2_ucd()
subroutine set_ucd_data_to_type::link_global_mesh_2_ucd (type(node_data), intent(in) node, type(element_data), intent(in) ele, type(ucd_data), intent(inout) ucd)
Definition at line 66 of file set_ucd_data_to_type.f90.
References set_and_cal_udt_data::const_udt_global_connect(), and link_node_data_2_ucd().
link_local_mesh_2_ucd()
subroutine set_ucd_data_to_type::link_local_mesh_2_ucd (type(node_data), intent(in) node, type(element_data), intent(in) ele, type(ucd_data), intent(inout) ucd)
Definition at line 48 of file set_ucd_data_to_type.f90.
References set_and_cal_udt_data::const_udt_local_connect(), and set_and_cal_udt_data::const_udt_local_nodes().
Referenced by output_parallel_ucd_file::link_output_grd_file(), and output_parallel_ucd_file::output_udt_one_snapshot().
link_nele_stacks_2_ucd()
subroutine set_ucd_data_to_type::link_nele_stacks_2_ucd (integer, intent(in) num_pe, type(element_data), intent(in) ele, type(ucd_data), intent(inout) ucd)
Definition at line 164 of file set_ucd_data_to_type.f90.
References set_ucd_data::link_numele_stacks_2_output().
Referenced by output_4_psf::output_isosurface(), and output_4_psf::output_section_mesh().
link_nnod_stacks_2_ucd()
subroutine set_ucd_data_to_type::link_nnod_stacks_2_ucd (integer, intent(in) num_pe, type(node_data), intent(in) node, type(ucd_data), intent(inout) ucd)
Definition at line 148 of file set_ucd_data_to_type.f90.
References set_ucd_data::link_numnod_stacks_2_output().
Referenced by merged_udt_vtk_file_io::init_merged_ucd(), output_4_psf::output_isosurface(), and output_4_psf::output_section_mesh().
link_node_data_2_ucd()
subroutine set_ucd_data_to_type::link_node_data_2_ucd (type(node_data), intent(in) node, type(ucd_data), intent(inout) ucd)
Definition at line 85 of file set_ucd_data_to_type.f90.
References set_ucd_data::link_node_data_2_output().
Referenced by link_global_mesh_2_ucd(), output_4_psf::output_isosurface(), and output_4_psf::output_section_mesh().
link_num_field_2_ucd()
subroutine set_ucd_data_to_type::link_num_field_2_ucd (type(phys_data), intent(in) phys_nod, type(ucd_data), intent(inout) ucd)
Definition at line 115 of file set_ucd_data_to_type.f90.
References set_ucd_data::link_num_field_2_output().
Referenced by output_parallel_ucd_file::link_output_grd_file(), and output_parallel_ucd_file::output_udt_one_snapshot().