CALYPSO: solver_sr_int8 Module Reference
solver_sr_int8 Module Reference
Data communication for 8-byte integer.
Functions/Subroutines
subroutine calypso_send_recv_i8core (npe_send, isend_self, id_pe_send, istack_send, npe_recv, irecv_self, id_pe_recv, istack_recv, SR_sig, SR_il)
subroutine solver_send_recv_i8 (NP, NEIBPETOT, NEIBPE, STACK_IMPORT, NOD_IMPORT, STACK_EXPORT, NOD_EXPORT, SR_sig, SR_il, iX8)
Detailed Description
Data communication for 8-byte integer.
      subroutine calypso_send_recv_i8core                             &
     &         (npe_send, isend_self, id_pe_send, istack_send,        &
     &          npe_recv, irecv_self, id_pe_recv, istack_recv,        &
     &          SR_sig, SR_il)
        type(send_recv_status), intent(inout) :: SR_sig
        type(send_recv_int8_buffer), intent(inout) :: SR_il
      subroutine  solver_send_recv_i8                                 &
     &          (NP, NEIBPETOT, NEIBPE, STACK_IMPORT, NOD_IMPORT,     &
     &           STACK_EXPORT, NOD_EXPORT, SR_sig, SR_il, iX8)
        type(send_recv_status), intent(inout) :: SR_sig
        type(send_recv_int8_buffer), intent(inout) :: SR_il
Parameters
NB Number of components
NTOT_SEND Total number of data points for export
NTOT_RECV Total number of data points for import
NPE_SEND Number of processses to receive
NPE_RECV Number of processses to send
Parameters
ITEM_IMPORT import table
REV_IMPORT reversed import table
Function/Subroutine Documentation
calypso_send_recv_i8core()
subroutine solver_sr_int8::calypso_send_recv_i8core (integer(kind = kint), intent(in) npe_send, integer(kind = kint), intent(in) isend_self, integer(kind = kint), dimension(npe_send), intent(in) id_pe_send, integer(kind = kint), dimension(0:npe_send), intent(in) istack_send, integer(kind = kint), intent(in) npe_recv, integer(kind = kint), intent(in) irecv_self, integer(kind = kint), dimension(npe_recv), intent(in) id_pe_recv, integer(kind = kint), dimension(0:npe_recv), intent(in) istack_recv, type(send_recv_status), intent(inout) SR_sig, type(send_recv_int8_buffer), intent(inout) SR_il)
Definition at line 51 of file solver_SR_int8.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_global_int, and calypso_mpi::ierr_mpi.
Referenced by calypso_sr_int::calypso_send_recv_int8().
solver_send_recv_i8()
subroutine solver_sr_int8::solver_send_recv_i8 (integer(kind=kint), intent(in) NP, integer(kind=kint), intent(in) NEIBPETOT, integer(kind=kint), dimension(neibpetot) NEIBPE, integer(kind=kint), dimension(0:neibpetot) STACK_IMPORT, integer(kind=kint), dimension(stack_import(neibpetot)) NOD_IMPORT, integer(kind=kint), dimension(0:neibpetot) STACK_EXPORT, integer(kind=kint), dimension(stack_export(neibpetot)) NOD_EXPORT, type(send_recv_status), intent(inout) SR_sig, type(send_recv_int8_buffer), intent(inout) SR_il, integer (kind=kint_gl), dimension(np), intent(inout) iX8)
Parameters
[in] np number of nodes
[in] neibpetot total neighboring pe count
neibpe neighboring pe id (i-th pe)
stack_import imported node count for each neighbor pe (i-th pe)
nod_import imported node (i-th dof)
stack_export exported node count for each neighbor pe (i-th pe)
nod_export exported node (i-th dof)
[in,out] ix8 communicated result vector
[in,out] sr_sig Structure of communication flags
[in,out] sr_il Structure of communication buffer for 8-byte integer
Definition at line 116 of file solver_SR_int8.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_global_int, calypso_mpi::ierr_mpi, and t_solver_sr_int8::resize_i8work_sr().
Referenced by solver_sr_type::solver_send_recv_int8_type().