CALYPSO: copy_sph_node_4_io Module Reference
copy_sph_node_4_io Module Reference
Copy sphectr indices structure between IO buffer.
Functions/Subroutines
subroutine copy_sph_node_4_rtp_from_io (sph_IO, rtp, l_truncation)
subroutine copy_sph_node_4_rtm_from_io (sph_IO, rtm, l_truncation)
subroutine copy_sph_node_4_rlm_from_io (sph_IO, rlm, l_truncation)
subroutine copy_sph_node_4_rj_from_io (sph_IO, rj, l_truncation)
subroutine copy_sph_node_4_rtp_to_io (l_truncation, rtp, sph_IO)
subroutine copy_sph_node_4_rtm_to_io (l_truncation, rtm, sph_IO)
subroutine copy_sph_node_4_rlm_to_io (l_truncation, rlm, sph_IO)
subroutine copy_sph_node_4_rj_to_io (l_truncation, rj, sph_IO)
Detailed Description
Copy sphectr indices structure between IO buffer.
      subroutine copy_sph_node_4_rtp_from_IO(sph_IO, rtp, l_truncation)
        integer(kind = kint), intent(inout) :: l_truncation
        type(sph_rtp_grid), intent(inout) :: rtp
        type(sph_IO_data), intent(in) :: sph_IO
      subroutine copy_sph_node_4_rtm_from_IO(sph_IO, rtm, l_truncation)
        integer(kind = kint), intent(inout) :: l_truncation
        type(sph_rtm_grid), intent(inout) :: rtm
        type(sph_IO_data), intent(in) :: sph_IO
      subroutine copy_sph_node_4_rlm_from_IO(sph_IO, rlm, l_truncation)
        integer(kind = kint), intent(inout) :: l_truncation
        type(sph_rlm_grid), intent(inout) :: rlm
        type(sph_IO_data), intent(in) :: sph_IO
      subroutine copy_sph_node_4_rj_from_IO(sph_IO, rj, l_truncation)
        integer(kind = kint), intent(inout) :: l_truncation
        type(sph_rj_grid), intent(inout) :: rj
        type(sph_IO_data), intent(in) :: sph_IO
      subroutine copy_sph_node_4_rtp_to_IO(l_truncation, rtp, sph_IO)
        integer(kind = kint), intent(in) :: l_truncation
        type(sph_rtp_grid), intent(in) :: rtp
        type(sph_IO_data), intent(inout) :: sph_IO
      subroutine copy_sph_node_4_rtm_to_IO(l_truncation, rtm, sph_IO)
        integer(kind = kint), intent(in) :: l_truncation
        type(sph_rtm_grid), intent(in) :: rtm
        type(sph_IO_data), intent(inout) :: sph_IO
      subroutine copy_sph_node_4_rlm_to_IO(l_truncation, rlm, sph_IO)
        integer(kind = kint), intent(in) :: l_truncation
        type(sph_rlm_grid), intent(in) :: rlm
        type(sph_IO_data), intent(inout) :: sph_IO
      subroutine copy_sph_node_4_rj_to_IO(l_truncation, rj, sph_IO)
        integer(kind = kint), intent(in) :: l_truncation
        type(sph_rj_grid), intent(in) :: rj
        type(sph_IO_data), intent(inout) :: sph_IO
Function/Subroutine Documentation
copy_sph_node_4_rj_from_io()
subroutine copy_sph_node_4_io::copy_sph_node_4_rj_from_io (type(sph_io_data), intent(in) sph_IO, type(sph_rj_grid), intent(inout) rj, integer(kind = kint), intent(inout) l_truncation)
Definition at line 212 of file copy_sph_node_4_IO.f90.
References t_spheric_rj_data::alloc_type_sph_1d_index_rj(), t_spheric_rj_data::alloc_type_spheric_param_rj(), m_constants::itwo, and m_constants::one.
Referenced by load_data_for_sph_io::input_modes_rj_sph_trans().
copy_sph_node_4_rj_to_io()
subroutine copy_sph_node_4_io::copy_sph_node_4_rj_to_io (integer(kind = kint), intent(in) l_truncation, type(sph_rj_grid), intent(in) rj, type(sph_io_data), intent(inout) sph_IO)
Definition at line 472 of file copy_sph_node_4_IO.f90.
References t_node_id_spherical_io::alloc_idx_sph_1d1_io(), t_node_id_spherical_io::alloc_idx_sph_1d2_io(), t_node_id_spherical_io::alloc_nod_id_sph_io(), t_node_id_spherical_io::alloc_num_idx_sph_io(), m_constants::ione, m_constants::ithree, m_constants::itwo, and m_constants::izero.
Referenced by load_data_for_sph_io::output_modes_rj_sph_trans().
copy_sph_node_4_rlm_from_io()
subroutine copy_sph_node_4_io::copy_sph_node_4_rlm_from_io (type(sph_io_data), intent(in) sph_IO, type(sph_rlm_grid), intent(inout) rlm, integer(kind = kint), intent(inout) l_truncation)
Definition at line 164 of file copy_sph_node_4_IO.f90.
References t_spheric_rlm_data::alloc_type_sph_1d_index_rlm(), t_spheric_rlm_data::alloc_type_spheric_param_rlm(), and m_constants::itwo.
Referenced by load_data_for_sph_io::input_modes_rlm_sph_trans().
copy_sph_node_4_rlm_to_io()
subroutine copy_sph_node_4_io::copy_sph_node_4_rlm_to_io (integer(kind = kint), intent(in) l_truncation, type(sph_rlm_grid), intent(in) rlm, type(sph_io_data), intent(inout) sph_IO)
Definition at line 409 of file copy_sph_node_4_IO.f90.
References t_node_id_spherical_io::alloc_idx_sph_1d1_io(), t_node_id_spherical_io::alloc_idx_sph_1d2_io(), t_node_id_spherical_io::alloc_nod_id_sph_io(), t_node_id_spherical_io::alloc_num_idx_sph_io(), m_constants::ione, m_constants::ithree, and m_constants::itwo.
Referenced by load_data_for_sph_io::output_modes_rlm_sph_trans().
copy_sph_node_4_rtm_from_io()
subroutine copy_sph_node_4_io::copy_sph_node_4_rtm_from_io (type(sph_io_data), intent(in) sph_IO, type(sph_rtm_grid), intent(inout) rtm, integer(kind = kint), intent(inout) l_truncation)
Definition at line 113 of file copy_sph_node_4_IO.f90.
References t_spheric_rtm_data::alloc_type_sph_1d_index_rtm(), t_spheric_rtm_data::alloc_type_spheric_param_rtm(), and m_constants::ithree.
Referenced by load_data_for_sph_io::input_geom_rtm_sph_trans().
copy_sph_node_4_rtm_to_io()
subroutine copy_sph_node_4_io::copy_sph_node_4_rtm_to_io (integer(kind = kint), intent(in) l_truncation, type(sph_rtm_grid), intent(in) rtm, type(sph_io_data), intent(inout) sph_IO)
Definition at line 340 of file copy_sph_node_4_IO.f90.
References t_node_id_spherical_io::alloc_idx_sph_1d1_io(), t_node_id_spherical_io::alloc_idx_sph_1d2_io(), t_node_id_spherical_io::alloc_idx_sph_1d3_io(), t_node_id_spherical_io::alloc_nod_id_sph_io(), t_node_id_spherical_io::alloc_num_idx_sph_io(), m_constants::ione, m_constants::ithree, and m_constants::itwo.
Referenced by load_data_for_sph_io::output_geom_rtm_sph_trans().
copy_sph_node_4_rtp_from_io()
subroutine copy_sph_node_4_io::copy_sph_node_4_rtp_from_io (type(sph_io_data), intent(in) sph_IO, type(sph_rtp_grid), intent(inout) rtp, integer(kind = kint), intent(inout) l_truncation)
Definition at line 61 of file copy_sph_node_4_IO.f90.
References t_spheric_rtp_data::alloc_type_sph_1d_index_rtp(), t_spheric_rtp_data::alloc_type_spheric_param_rtp(), and m_constants::ithree.
Referenced by load_data_for_sph_io::input_geom_rtp_sph_trans().
copy_sph_node_4_rtp_to_io()
subroutine copy_sph_node_4_io::copy_sph_node_4_rtp_to_io (integer(kind = kint), intent(in) l_truncation, type(sph_rtp_grid), intent(in) rtp, type(sph_io_data), intent(inout) sph_IO)
Definition at line 264 of file copy_sph_node_4_IO.f90.
References t_node_id_spherical_io::alloc_idx_sph_1d1_io(), t_node_id_spherical_io::alloc_idx_sph_1d2_io(), t_node_id_spherical_io::alloc_idx_sph_1d3_io(), t_node_id_spherical_io::alloc_nod_id_sph_io(), t_node_id_spherical_io::alloc_num_idx_sph_io(), m_constants::ione, m_constants::ithree, and m_constants::itwo.
Referenced by load_data_for_sph_io::output_geom_rtp_sph_trans().