CALYPSO: const_element_comm_tables Module Reference
const_element_comm_tables Module Reference
Belonged element list for each node.
Functions/Subroutines
subroutine const_global_mesh_infos (mesh)
subroutine const_element_comm_tbl_only (mesh, ele_comm)
subroutine dealloc_ele_comm_tbls_gl_nele (mesh)
subroutine const_global_numnod_list (node)
subroutine const_global_numele_list (ele)
subroutine, private const_global_element_id (ele_comm, ele)
subroutine, private const_global_surface_id (sf_comm, surf)
subroutine, private const_global_edge_id (ed_comm, edge)
subroutine const_ele_comm_tbl (node, nod_comm, belongs, ele_comm, ele)
subroutine const_surf_comm_table (node, nod_comm, belongs, surf_comm, surf)
subroutine const_edge_comm_table (node, nod_comm, belongs, edge_comm, edge)
subroutine find_position_range (node)
Variables
type(belonged_table), save, private blng_tbl
character(len=kchara), parameter, private txt_ele = 'element'
character(len=kchara), parameter, private txt_edge = 'edge'
character(len=kchara), parameter, private txt_surf = 'surface'
Detailed Description
Belonged element list for each node.
      subroutine const_global_mesh_infos(mesh)
      subroutine const_element_comm_tbl_only(mesh, ele_comm)
        type(mesh_geometry), intent(inout) :: mesh
        type(communication_table), intent(inout) :: ele_comm
      subroutine dealloc_ele_comm_tbls_gl_nele(mesh)
        type(mesh_geometry), intent(inout) ::    mesh
      subroutine const_ele_comm_tbl                                   &
     &         (node, nod_comm, belongs, ele_comm, ele)
        type(node_data), intent(in) :: node
        type(communication_table), intent(in) :: nod_comm
        type(belonged_table), intent(inout) :: belongs
        type(communication_table), intent(inout) :: ele_comm
        type(element_data), intent(inout) :: ele
      subroutine const_surf_comm_table                                &
     &         (node, nod_comm, belongs, surf_comm, surf)
        type(node_data), intent(in) :: node
        type(communication_table), intent(in) :: nod_comm
        type(belonged_table), intent(inout) :: belongs
        type(communication_table), intent(inout) :: surf_comm
        type(surface_data), intent(inout) :: surf
      subroutine const_edge_comm_table                                &
     &         (node, nod_comm, belongs, edge_comm, edge)
        type(node_data), intent(in) :: node
        type(communication_table), intent(in) :: nod_comm
        type(belonged_table), intent(inout) :: belongs
        type(communication_table), intent(inout) :: edge_comm
        type(edge_data), intent(inout) :: edge
      subroutine const_global_numnod_list(node)
Function/Subroutine Documentation
const_edge_comm_table()
subroutine const_element_comm_tables::const_edge_comm_table (type(node_data), intent(in) node, type(communication_table), intent(in) nod_comm, type(belonged_table), intent(inout) belongs, type(communication_table), intent(inout) edge_comm, type(edge_data), intent(inout) edge)
Definition at line 297 of file const_element_comm_tables.f90.
References t_belonged_element_4_node::alloc_x_ref_edge(), t_belonged_element_4_node::belonged_edge_id_4_node(), const_element_comm_table::const_comm_table_by_connenct(), const_global_edge_id(), t_next_node_ele_4_node::dealloc_iele_belonged(), t_belonged_element_4_node::dealloc_x_ref_edge(), m_machine_parameter::iflag_debug, set_ele_id_4_node_type::set_edge_id_4_node(), t_belonged_element_4_node::sort_inod_4_ele_by_position(), and txt_edge.
Referenced by psf_global_nod_id::const_edge_comm_table_4_psf().
const_ele_comm_tbl()
subroutine const_element_comm_tables::const_ele_comm_tbl (type(node_data), intent(in) node, type(communication_table), intent(in) nod_comm, type(belonged_table), intent(inout) belongs, type(communication_table), intent(inout) ele_comm, type(element_data), intent(inout) ele)
Definition at line 229 of file const_element_comm_tables.f90.
References t_belonged_element_4_node::alloc_x_ref_ele(), t_belonged_element_4_node::belonged_ele_id_4_node(), const_element_comm_table::const_comm_table_by_connenct(), const_global_element_id(), t_next_node_ele_4_node::dealloc_iele_belonged(), t_belonged_element_4_node::dealloc_x_ref_ele(), set_ele_id_4_node_type::set_ele_id_4_node(), t_belonged_element_4_node::sort_inod_4_ele_by_position(), and txt_ele.
Referenced by const_element_comm_tbl_only().
const_element_comm_tbl_only()
subroutine const_element_comm_tables::const_element_comm_tbl_only (type(mesh_geometry), intent(inout) mesh, type(communication_table), intent(inout) ele_comm)
Definition at line 93 of file const_element_comm_tables.f90.
References blng_tbl, const_ele_comm_tbl(), and m_machine_parameter::iflag_debug.
const_global_edge_id()
subroutine, private const_element_comm_tables::const_global_edge_id (type(communication_table), intent(in) ed_comm, type(edge_data), intent(inout) edge) private
Definition at line 198 of file const_element_comm_tables.f90.
References t_edge_data::alloc_numedge_stack(), const_global_element_ids::count_number_of_node_stack(), m_machine_parameter::iflag_debug, calypso_mpi::nprocs, const_global_element_ids::set_global_ele_id(), and txt_edge.
Referenced by const_edge_comm_table().
const_global_element_id()
subroutine, private const_element_comm_tables::const_global_element_id (type(communication_table), intent(in) ele_comm, type(element_data), intent(inout) ele) private
Definition at line 157 of file const_element_comm_tables.f90.
References const_global_numele_list(), const_global_element_ids::set_global_ele_id(), and txt_ele.
Referenced by const_ele_comm_tbl().
const_global_mesh_infos()
subroutine const_element_comm_tables::const_global_mesh_infos (type(mesh_geometry), intent(inout) mesh)
Definition at line 75 of file const_element_comm_tables.f90.
References const_global_numnod_list(), find_position_range(), and m_machine_parameter::iflag_debug.
Referenced by parallel_fem_mesh_init::fem_mesh_initialization().
const_global_numele_list()
subroutine const_element_comm_tables::const_global_numele_list (type(element_data), intent(inout) ele)
Definition at line 140 of file const_element_comm_tables.f90.
References t_geometry_data::alloc_numele_stack(), const_global_element_ids::count_number_of_node_stack(), and calypso_mpi::nprocs.
Referenced by const_global_element_id(), set_patches_for_psf::set_iso_patches(), and set_patches_for_psf::set_psf_patches().
const_global_numnod_list()
subroutine const_element_comm_tables::const_global_numnod_list (type(node_data), intent(inout) node)
Definition at line 123 of file const_element_comm_tables.f90.
References t_geometry_data::alloc_numnod_stack(), const_global_element_ids::count_number_of_node_stack(), and calypso_mpi::nprocs.
Referenced by const_global_mesh_infos(), find_node_and_patch_psf::set_node_and_patch_psf(), and set_nodes_for_psf::set_nodes_4_iso().
const_global_surface_id()
subroutine, private const_element_comm_tables::const_global_surface_id (type(communication_table), intent(in) sf_comm, type(surface_data), intent(inout) surf) private
Definition at line 173 of file const_element_comm_tables.f90.
References t_surface_data::alloc_numsurf_stack(), const_global_element_ids::count_number_of_node_stack(), t_surface_data::dealloc_numsurf_stack(), calypso_mpi::nprocs, const_global_element_ids::set_global_ele_id(), and txt_surf.
Referenced by const_surf_comm_table().
const_surf_comm_table()
subroutine const_element_comm_tables::const_surf_comm_table (type(node_data), intent(in) node, type(communication_table), intent(in) nod_comm, type(belonged_table), intent(inout) belongs, type(communication_table), intent(inout) surf_comm, type(surface_data), intent(inout) surf)
Definition at line 263 of file const_element_comm_tables.f90.
References t_belonged_element_4_node::alloc_x_ref_surf(), t_belonged_element_4_node::belonged_surf_id_4_node(), const_element_comm_table::const_comm_table_by_connenct(), const_global_surface_id(), t_next_node_ele_4_node::dealloc_iele_belonged(), t_belonged_element_4_node::dealloc_x_ref_surf(), set_ele_id_4_node_type::set_surf_id_4_node(), t_belonged_element_4_node::sort_inod_4_ele_by_position(), and txt_surf.
dealloc_ele_comm_tbls_gl_nele()
subroutine const_element_comm_tables::dealloc_ele_comm_tbls_gl_nele (type(mesh_geometry), intent(inout) mesh)
Definition at line 109 of file const_element_comm_tables.f90.
References t_edge_data::dealloc_numedge_stack(), t_geometry_data::dealloc_numele_stack(), and t_geometry_data::dealloc_numnod_stack().
find_position_range()
subroutine const_element_comm_tables::find_position_range (type(node_data), intent(inout) node)
Definition at line 340 of file const_element_comm_tables.f90.
References calypso_mpi_real::calypso_mpi_allreduce_real(), transfer_to_long_integers::cast_long(), and m_machine_parameter::iflag_debug.
Referenced by const_global_mesh_infos().
Variable Documentation
blng_tbl
type(belonged_table), save, private const_element_comm_tables::blng_tbl private
Definition at line 59 of file const_element_comm_tables.f90.
Referenced by const_element_comm_tbl_only().
txt_edge
character(len=kchara), parameter, private const_element_comm_tables::txt_edge = 'edge' private
Definition at line 62 of file const_element_comm_tables.f90.
Referenced by const_edge_comm_table(), and const_global_edge_id().
txt_ele
character(len=kchara), parameter, private const_element_comm_tables::txt_ele = 'element' private
Definition at line 61 of file const_element_comm_tables.f90.
Referenced by const_ele_comm_tbl(), and const_global_element_id().
txt_surf
character(len=kchara), parameter, private const_element_comm_tables::txt_surf = 'surface' private
Definition at line 63 of file const_element_comm_tables.f90.
Referenced by const_global_surface_id(), and const_surf_comm_table().