CALYPSO: add_nodal_fields_4_mhd Module Reference
add_nodal_fields_4_mhd Module Reference
Add missing field for MHD dynamo to field list.
Functions/Subroutines
subroutine add_dependent_field (MHD_prop, field_ctl)
subroutine add_field_name_4_mhd (MHD_prop, field_ctl)
subroutine add_ctl_4_ref_temp (ref_param_T, ref_param_C, field_ctl)
subroutine, private add_ctl_4_forces (fl_prop, ref_param_T, ref_param_C, field_ctl)
subroutine, private add_work_area_4_potentials (fl_prop, cd_prop, field_ctl)
subroutine, private add_data_4_previous_step (fl_prop, cd_prop, ht_prop, cp_prop, field_ctl)
subroutine, private add_data_4_check_step (fl_prop, cd_prop, ht_prop, cp_prop, field_ctl)
subroutine, private add_field_ctl_4_evo_magne (cd_prop, field_ctl)
Detailed Description
Add missing field for MHD dynamo to field list.
      subroutine add_dependent_field(MHD_prop, field_ctl)
        type(MHD_evolution_param), intent(in) :: MHD_prop
        type(ctl_array_c3), intent(inout) :: field_ctl
      subroutine add_field_name_4_mhd(MHD_prop, field_ctl)
      subroutine add_ctl_4_ref_temp                                   &
     &         (ref_param_T, ref_param_C, field_ctl)
        type(MHD_evolution_param), intent(in) :: MHD_prop
        type(reference_scalar_param), intent(in) :: ref_param_T
        type(reference_scalar_param), intent(in) :: ref_param_C
        type(ctl_array_c3), intent(inout) :: field_ctl
Function/Subroutine Documentation
add_ctl_4_forces()
subroutine, private add_nodal_fields_4_mhd::add_ctl_4_forces (type(fluid_property), intent(in) fl_prop, type(reference_scalar_param), intent(in) ref_param_T, type(reference_scalar_param), intent(in) ref_param_C, type(ctl_array_c3), intent(inout) field_ctl) private
Definition at line 168 of file add_nodal_fields_4_MHD.f90.
References add_nodal_fields_ctl::add_phys_name_ctl(), m_base_force_labels::buoyancy, m_base_force_labels::composite_buoyancy, m_base_force_labels::coriolis_force, t_physical_property::id_force_at_node, t_reference_scalar_param::id_no_ref_temp, m_base_field_labels::perturbation_composition, and m_base_field_labels::perturbation_temp.
Referenced by add_field_name_4_mhd().
add_ctl_4_ref_temp()
subroutine add_nodal_fields_4_mhd::add_ctl_4_ref_temp (type(reference_scalar_param), intent(in) ref_param_T, type(reference_scalar_param), intent(in) ref_param_C, type(ctl_array_c3), intent(inout) field_ctl)
Definition at line 140 of file add_nodal_fields_4_MHD.f90.
References add_nodal_fields_ctl::add_phys_name_ctl(), m_grad_field_labels::grad_reference_composition, m_grad_field_labels::grad_reference_temp, t_reference_scalar_param::id_no_ref_temp, m_base_field_labels::reference_composition, and m_base_field_labels::reference_temperature.
add_data_4_check_step()
subroutine, private add_nodal_fields_4_mhd::add_data_4_check_step (type(fluid_property), intent(in) fl_prop, type(conductive_property), intent(in) cd_prop, type(scalar_property), intent(in) ht_prop, type(scalar_property), intent(in) cp_prop, type(ctl_array_c3), intent(inout) field_ctl) private
Definition at line 262 of file add_nodal_fields_4_MHD.f90.
References add_nodal_fields_ctl::add_phys_name_ctl(), m_explicit_term_labels::check_composition, m_explicit_term_labels::check_heat, m_explicit_term_labels::check_induction, m_explicit_term_labels::check_momentum, m_explicit_term_labels::check_potential, m_explicit_term_labels::check_pressure, and t_physical_property::id_no_evolution.
Referenced by add_field_name_4_mhd().
add_data_4_previous_step()
subroutine, private add_nodal_fields_4_mhd::add_data_4_previous_step (type(fluid_property), intent(in) fl_prop, type(conductive_property), intent(in) cd_prop, type(scalar_property), intent(in) ht_prop, type(scalar_property), intent(in) cp_prop, type(ctl_array_c3), intent(inout) field_ctl) private
Definition at line 228 of file add_nodal_fields_4_MHD.f90.
References add_nodal_fields_ctl::add_phys_name_ctl(), t_physical_property::id_no_evolution, m_explicit_term_labels::previous_composition, m_explicit_term_labels::previous_heat, m_explicit_term_labels::previous_induction, m_explicit_term_labels::previous_momentum, m_explicit_term_labels::previous_pressure, and m_explicit_term_labels::sum_forces.
Referenced by add_field_name_4_mhd().
add_dependent_field()
subroutine add_nodal_fields_4_mhd::add_dependent_field (type(mhd_evolution_param), intent(in) MHD_prop, type(ctl_array_c3), intent(inout) field_ctl)
Definition at line 45 of file add_nodal_fields_4_MHD.f90.
References check_base_field::add_field_ctl_4_base_field(), check_workarea_4_explicit::add_field_ctl_4_check_evo(), check_base_field::add_field_ctl_4_diff_vector(), check_base_forces::add_field_ctl_4_diffusions(), check_base_forces::add_field_ctl_4_div_forces(), check_energy_fluxes::add_field_ctl_4_ene_flux(), add_field_ctl_4_evo_magne(), check_base_forces::add_field_ctl_4_field_products(), check_base_forces::add_field_ctl_4_forces(), check_base_field::add_field_ctl_4_grad_field(), check_base_forces::add_field_ctl_4_rot_forces(), m_machine_parameter::iflag_debug, and m_machine_parameter::iflag_routine_msg.
Referenced by set_control_sph_data_mhd::set_control_sph_mhd_fields().
add_field_ctl_4_evo_magne()
subroutine, private add_nodal_fields_4_mhd::add_field_ctl_4_evo_magne (type(conductive_property), intent(in) cd_prop, type(ctl_array_c3), intent(inout) field_ctl) private
Definition at line 310 of file add_nodal_fields_4_MHD.f90.
References add_nodal_fields_ctl::add_phys_name_ctl(), add_nodal_fields_ctl::check_field_list_ctl(), m_explicit_term_labels::check_induction, t_physical_property::id_no_evolution, m_base_field_labels::magnetic_field, and m_base_field_labels::vector_potential.
Referenced by add_dependent_field().
add_field_name_4_mhd()
subroutine add_nodal_fields_4_mhd::add_field_name_4_mhd (type(mhd_evolution_param), intent(in) MHD_prop, type(ctl_array_c3), intent(inout) field_ctl)
Definition at line 100 of file add_nodal_fields_4_MHD.f90.
References add_ctl_4_forces(), add_data_4_check_step(), add_data_4_previous_step(), add_work_area_4_potentials(), and m_machine_parameter::iflag_debug.
Referenced by set_control_sph_data_mhd::set_control_sph_mhd_fields().
add_work_area_4_potentials()
subroutine, private add_nodal_fields_4_mhd::add_work_area_4_potentials (type(fluid_property), intent(in) fl_prop, type(conductive_property), intent(in) cd_prop, type(ctl_array_c3), intent(inout) field_ctl) private
Definition at line 204 of file add_nodal_fields_4_MHD.f90.
References add_nodal_fields_ctl::add_phys_name_ctl(), t_physical_property::id_no_evolution, m_explicit_term_labels::m_potential_work, and m_explicit_term_labels::pressure_work.
Referenced by add_field_name_4_mhd().