CALYPSO: copy_between_two_fields Module Reference
copy_between_two_fields Module Reference
Functions/Subroutines
subroutine copy_scalar_2_scalar_fld (ifld_org, nnod_org, ntot_org_phys, d_org, ifld_dst, nnod_dst, ntot_dst_phys, d_dst)
subroutine copy_vector_2_vector_fld (ifld_org, nnod_org, ntot_org_phys, d_org, ifld_dst, nnod_dst, ntot_dst_phys, d_dst)
subroutine copy_tensor_2_tensor_fld (ifld_org, nnod_org, ntot_org_phys, d_org, ifld_dst, nnod_dst, ntot_dst_phys, d_dst)
subroutine copy_fields_2_fields (numdir, ifld_org, nnod_org, ntot_org_phys, d_org, ifld_dst, nnod_dst, ntot_dst_phys, d_dst)
subroutine fill_rest_scalar_field (ifld_org, ist_fill, ntot_org_phys, d_org, ifld_dst, numnod, internal_node, ntot_dst_phys, d_dst)
subroutine fill_rest_vector_field (ifld_org, ist_fill, ntot_org_phys, d_org, ifld_dst, numnod, internal_node, ntot_dst_phys, d_dst)
subroutine fill_rest_tensor_field (ifld_org, ist_fill, ntot_org_phys, d_org, ifld_dst, numnod, internal_node, ntot_dst_phys, d_dst)
subroutine fill_rest_fields (numdir, ifld_org, ist_fill, ntot_org_phys, d_org, ifld_dst, numnod, internal_node, ntot_dst_phys, d_dst)
Function/Subroutine Documentation
copy_fields_2_fields()
subroutine copy_between_two_fields::copy_fields_2_fields (integer(kind = kint), intent(in) numdir, integer(kind = kint), intent(in) ifld_org, integer(kind = kint_gl), intent(in) nnod_org, integer(kind = kint), intent(in) ntot_org_phys, real(kind = kreal), dimension(nnod_org,ntot_org_phys), intent(in) d_org, integer(kind = kint), intent(in) ifld_dst, integer(kind = kint_gl), intent(in) nnod_dst, integer(kind = kint), intent(in) ntot_dst_phys, real(kind=kreal), dimension(nnod_dst,ntot_dst_phys), intent(inout) d_dst)
Definition at line 141 of file copy_between_two_fields.f90.
Referenced by t_ucd_data::append_new_ucd_field_data(), t_ucd_data::append_new_ucd_field_name(), gz_udt_to_vtk_data_io::read_gz_udt_field_from_vtk(), and udt_to_vtk_data_io::read_udt_field_from_vtk().
copy_scalar_2_scalar_fld()
subroutine copy_between_two_fields::copy_scalar_2_scalar_fld (integer(kind = kint), intent(in) ifld_org, integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) ntot_org_phys, real(kind = kreal), dimension(nnod_org,ntot_org_phys), intent(in) d_org, integer(kind = kint), intent(in) ifld_dst, integer(kind = kint), intent(in) nnod_dst, integer(kind = kint), intent(in) ntot_dst_phys, real(kind = kreal), dimension(nnod_dst,ntot_dst_phys), intent(inout) d_dst)
Definition at line 63 of file copy_between_two_fields.f90.
copy_tensor_2_tensor_fld()
subroutine copy_between_two_fields::copy_tensor_2_tensor_fld (integer(kind = kint), intent(in) ifld_org, integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) ntot_org_phys, real(kind = kreal), dimension(nnod_org,ntot_org_phys), intent(in) d_org, integer(kind = kint), intent(in) ifld_dst, integer(kind = kint), intent(in) nnod_dst, integer(kind = kint), intent(in) ntot_dst_phys, real(kind=kreal), dimension(nnod_dst,ntot_dst_phys), intent(inout) d_dst)
Definition at line 113 of file copy_between_two_fields.f90.
Referenced by cvt_nodal_and_sph_field::cvt_nod_tsr_to_sph_tsr(), and cvt_nodal_and_sph_field::cvt_sph_tsr_to_nod_tsr().
copy_vector_2_vector_fld()
subroutine copy_between_two_fields::copy_vector_2_vector_fld (integer(kind = kint), intent(in) ifld_org, integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) ntot_org_phys, real(kind=kreal), dimension(nnod_org, ntot_org_phys), intent(in) d_org, integer(kind = kint), intent(in) ifld_dst, integer(kind = kint), intent(in) nnod_dst, integer(kind = kint), intent(in) ntot_dst_phys, real(kind=kreal), dimension(nnod_dst,ntot_dst_phys), intent(inout) d_dst)
Definition at line 87 of file copy_between_two_fields.f90.
Referenced by cvt_nodal_and_sph_field::cvt_nod_vec_to_sph_vec(), and cvt_nodal_and_sph_field::cvt_sph_vec_to_nod_vec().
fill_rest_fields()
subroutine copy_between_two_fields::fill_rest_fields (integer(kind = kint), intent(in) numdir, integer(kind = kint), intent(in) ifld_org, integer(kind = kint), intent(in) ist_fill, integer(kind = kint), intent(in) ntot_org_phys, real(kind = kreal), dimension(numnod,ntot_org_phys), intent(in) d_org, integer(kind = kint), intent(in) ifld_dst, integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) internal_node, integer(kind = kint), intent(in) ntot_dst_phys, real(kind=kreal), dimension(numnod,ntot_dst_phys), intent(inout) d_dst)
Definition at line 258 of file copy_between_two_fields.f90.
fill_rest_scalar_field()
subroutine copy_between_two_fields::fill_rest_scalar_field (integer(kind = kint), intent(in) ifld_org, integer(kind = kint), intent(in) ist_fill, integer(kind = kint), intent(in) ntot_org_phys, real(kind = kreal), dimension(numnod,ntot_org_phys), intent(in) d_org, integer(kind = kint), intent(in) ifld_dst, integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) internal_node, integer(kind = kint), intent(in) ntot_dst_phys, real(kind = kreal), dimension(numnod,ntot_dst_phys), intent(inout) d_dst)
Definition at line 172 of file copy_between_two_fields.f90.
fill_rest_tensor_field()
subroutine copy_between_two_fields::fill_rest_tensor_field (integer(kind = kint), intent(in) ifld_org, integer(kind = kint), intent(in) ist_fill, integer(kind = kint), intent(in) ntot_org_phys, real(kind = kreal), dimension(numnod,ntot_org_phys), intent(in) d_org, integer(kind = kint), intent(in) ifld_dst, integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) internal_node, integer(kind = kint), intent(in) ntot_dst_phys, real(kind=kreal), dimension(numnod,ntot_dst_phys), intent(inout) d_dst)
Definition at line 227 of file copy_between_two_fields.f90.
Referenced by cvt_nodal_and_sph_field::cvt_sph_tsr_to_nod_tsr().
fill_rest_vector_field()
subroutine copy_between_two_fields::fill_rest_vector_field (integer(kind = kint), intent(in) ifld_org, integer(kind = kint), intent(in) ist_fill, integer(kind = kint), intent(in) ntot_org_phys, real(kind=kreal), dimension(numnod, ntot_org_phys), intent(in) d_org, integer(kind = kint), intent(in) ifld_dst, integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) internal_node, integer(kind = kint), intent(in) ntot_dst_phys, real(kind=kreal), dimension(numnod,ntot_dst_phys), intent(inout) d_dst)
Definition at line 199 of file copy_between_two_fields.f90.
Referenced by cvt_nodal_and_sph_field::cvt_sph_vec_to_nod_vec().