CALYPSO: select_copy_from_recv Module Reference
select_copy_from_recv Module Reference
scalar components data communication
Functions/Subroutines
subroutine sel_cppy_from_recv_buf_1 (iflag_recv, nnod_new, ntot_import, inod_import, irev_import, WR, X_new)
subroutine sel_cppy_from_recv_buf_2 (iflag_recv, nnod_new, ntot_import, inod_import, irev_import, WR, X_new)
subroutine sel_cppy_from_recv_buf_3 (iflag_recv, nnod_new, ntot_import, inod_import, irev_import, WR, X_new)
subroutine sel_cppy_from_recv_buf_6 (iflag_recv, nnod_new, ntot_import, inod_import, irev_import, WR, X_new)
subroutine sel_cppy_from_recv_buf_n (iflag_recv, NB, nnod_new, npe_recv, ntot_import, istack_recv, inod_import, irev_import, WR, X_new)
subroutine sel_cppy_to_send_buf_n (iflag_recv, NB, nnod_org, npe_send, ntot_export, istack_send, inod_export, X_org, WS)
subroutine sel_cppy_from_recv_buf_3x1 (iflag_recv, nnod_new, ntot_import, inod_import, irev_import, WR, X1_new, X2_new, X3_new)
subroutine sel_cppy_from_recv_buf_3x2 (iflag_recv, nnod_new, ntot_import, inod_import, irev_import, WR, X1_new, X2_new, X3_new)
subroutine sel_cppy_from_recv_buf_3x3 (iflag_recv, nnod_new, ntot_import, inod_import, irev_import, WR, X1_new, X2_new, X3_new)
subroutine sel_cppy_from_recv_buf_3x6 (iflag_recv, nnod_new, ntot_import, inod_import, irev_import, WR, X1_new, X2_new, X3_new)
subroutine sel_cppy_from_recv_buf_3xn (iflag_recv, NB, nnod_new, npe_recv, ntot_import, istack_recv, inod_import, irev_import, WR, X1_new, X2_new, X3_new)
subroutine sel_cppy_from_recv_buf_int (iflag_recv, nnod_new, ntot_import, inod_import, irev_import, iWR, iX_new)
subroutine sel_cppy_from_recv_buf_i8 (iflag_recv, nnod_new, ntot_import, inod_import, irev_import, i8WR, i8X_new)
Variables
integer(kind=kint), parameter iflag_import_undefined = -1
Undefined flag.
integer(kind=kint), parameter iflag_import_item = 0
Integer flag to use import table.
integer(kind=kint), parameter iflag_import_rev = 1
Integer flag to use reversed import table for data points.
integer(kind=kint), parameter iflag_import_mod = 2
Integer flag to use testroutine to import.
integer(kind=kint), parameter iflag_import_test = -10
Integer flag to use testroutine to import.
Detailed Description
scalar components data communication
      subroutine sel_cppy_from_recv_buf_1(iflag_recv, nnod_new,       &
     &                         ntot_import, inod_import, irev_import, &
     &                         WR, X_new)
      subroutine sel_cppy_from_recv_buf_2(iflag_recv, nnod_new,       &
     &                         ntot_import, inod_import, irev_import, &
     &                         WR, X_new)
      subroutine sel_cppy_from_recv_buf_3(iflag_recv, nnod_new,       &
     &                         ntot_import, inod_import, irev_import, &
     &                         WR, X_new)
      subroutine sel_cppy_from_recv_buf_6(iflag_recv, nnod_new,       &
     &                         ntot_import, inod_import, irev_import, &
     &                         WR, X_new)
      subroutine sel_cppy_from_recv_buf_N(iflag_recv, NB, nnod_new,   &
     &                         npe_recv, ntot_import, istack_recv,    &
     &                         inod_import, irev_import,              &
     &                         WR, X_new)
      subroutine sel_cppy_to_send_buf_N(iflag_recv, NB, nnod_org,     &
     &                         npe_send, ntot_export, istack_send,    &
     &                         inod_export, X_org, WS)
      subroutine sel_cppy_from_recv_buf_3x1(iflag_recv, nnod_new,     &
     &                         ntot_import, inod_import, irev_import, &
     &                         WR, X1_new, X2_new, X3_new)
      subroutine sel_cppy_from_recv_buf_3x2(iflag_recv, nnod_new,     &
     &                         ntot_import, inod_import, irev_import, &
     &                         WR, X1_new, X2_new, X3_new)
      subroutine sel_cppy_from_recv_buf_3x3(iflag_recv, nnod_new,     &
     &                         ntot_import, inod_import, irev_import, &
     &                         WR, X1_new, X2_new, X3_new)
      subroutine sel_cppy_from_recv_buf_3x6(iflag_recv, nnod_new,     &
     &                         ntot_import, inod_import, irev_import, &
     &                         WR, X1_new, X2_new, X3_new)
      subroutine sel_cppy_from_recv_buf_3xN(iflag_recv, NB, nnod_new, &
     &                         npe_recv, ntot_import, istack_recv,    &
     &                         inod_import, irev_import,              &
     &                         WR, X1_new, X2_new, X3_new)
      subroutine sel_cppy_from_recv_buf_int(iflag_recv, nnod_new,     &
     &                       ntot_import, inod_import, irev_import,   &
     &                       iWR, iX_new)
      subroutine sel_cppy_from_recv_buf_i8(iflag_recv, nnod_new,      &
     &                       ntot_import, inod_import, irev_import,   &
     &                       i8WR, i8X_new)
Parameters
iflag_recv import table mode
nnod_new Number of components for destination
ntot_import Number of import table
inod_import(ntot_import) local node ID to copy from receive buffer
irev_import(nnod_new) import buffer ID for each data point
X_new(nnod_new) Received data
Function/Subroutine Documentation
sel_cppy_from_recv_buf_1()
subroutine select_copy_from_recv::sel_cppy_from_recv_buf_1 (integer(kind = kint), intent(in) iflag_recv, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) ntot_import, integer(kind = kint), dimension(ntot_import), intent(in) inod_import, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, real (kind=kreal), dimension(ntot_import+1), intent(inout) WR, real (kind=kreal), dimension(nnod_new), intent(inout) X_new)
Definition at line 91 of file select_copy_from_recv.f90.
References iflag_import_rev, set_from_recv_buffer::set_from_recv_buf_1(), and set_from_recv_buf_rev::set_from_recv_buf_rev_1().
Referenced by calypso_sr::calypso_send_recv().
sel_cppy_from_recv_buf_2()
subroutine select_copy_from_recv::sel_cppy_from_recv_buf_2 (integer(kind = kint), intent(in) iflag_recv, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) ntot_import, integer(kind = kint), dimension(ntot_import), intent(in) inod_import, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, real (kind=kreal), dimension(2*(ntot_import+1)), intent(inout) WR, real (kind=kreal), dimension(2*nnod_new), intent(inout) X_new)
Definition at line 121 of file select_copy_from_recv.f90.
References iflag_import_rev, set_from_recv_buffer::set_from_recv_buf_2(), and set_from_recv_buf_rev::set_from_recv_buf_rev_2().
Referenced by calypso_sr_2::calypso_send_recv_2().
sel_cppy_from_recv_buf_3()
subroutine select_copy_from_recv::sel_cppy_from_recv_buf_3 (integer(kind = kint), intent(in) iflag_recv, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) ntot_import, integer(kind = kint), dimension(ntot_import), intent(in) inod_import, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, real (kind=kreal), dimension(3*(ntot_import+1)), intent(inout) WR, real (kind=kreal), dimension(3*nnod_new), intent(inout) X_new)
Definition at line 152 of file select_copy_from_recv.f90.
References iflag_import_rev, set_from_recv_buffer::set_from_recv_buf_3(), and set_from_recv_buf_rev::set_from_recv_buf_rev_3().
Referenced by calypso_sr_3::calypso_send_recv_3().
sel_cppy_from_recv_buf_3x1()
subroutine select_copy_from_recv::sel_cppy_from_recv_buf_3x1 (integer(kind = kint), intent(in) iflag_recv, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) ntot_import, integer(kind = kint), dimension(ntot_import), intent(in) inod_import, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, real (kind=kreal), dimension(3*(ntot_import+1)), intent(inout) WR, real (kind=kreal), dimension(nnod_new), intent(inout) X1_new, real (kind=kreal), dimension(nnod_new), intent(inout) X2_new, real (kind=kreal), dimension(nnod_new), intent(inout) X3_new)
Definition at line 283 of file select_copy_from_recv.f90.
References iflag_import_rev, set_from_recv_buff_tri::set_from_recv_buf_3x1(), and set_from_recv_buf_rev_tri::set_from_recv_buf_rev_3x1().
Referenced by calypso_sr::calypso_send_recv_3x1().
sel_cppy_from_recv_buf_3x2()
subroutine select_copy_from_recv::sel_cppy_from_recv_buf_3x2 (integer(kind = kint), intent(in) iflag_recv, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) ntot_import, integer(kind = kint), dimension(ntot_import), intent(in) inod_import, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, real (kind=kreal), dimension(6*(ntot_import+1)), intent(inout) WR, real (kind=kreal), dimension(2*nnod_new), intent(inout) X1_new, real (kind=kreal), dimension(2*nnod_new), intent(inout) X2_new, real (kind=kreal), dimension(2*nnod_new), intent(inout) X3_new)
Definition at line 315 of file select_copy_from_recv.f90.
References iflag_import_rev, set_from_recv_buff_tri::set_from_recv_buf_3x2(), and set_from_recv_buf_rev_tri::set_from_recv_buf_rev_3x2().
Referenced by calypso_sr_2::calypso_send_recv_3x2().
sel_cppy_from_recv_buf_3x3()
subroutine select_copy_from_recv::sel_cppy_from_recv_buf_3x3 (integer(kind = kint), intent(in) iflag_recv, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) ntot_import, integer(kind = kint), dimension(ntot_import), intent(in) inod_import, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, real (kind=kreal), dimension(9*(ntot_import+1)), intent(inout) WR, real (kind=kreal), dimension(3*nnod_new), intent(inout) X1_new, real (kind=kreal), dimension(3*nnod_new), intent(inout) X2_new, real (kind=kreal), dimension(3*nnod_new), intent(inout) X3_new)
Definition at line 348 of file select_copy_from_recv.f90.
References iflag_import_rev, set_from_recv_buff_tri::set_from_recv_buf_3x3(), and set_from_recv_buf_rev_tri::set_from_recv_buf_rev_3x3().
Referenced by calypso_sr_3::calypso_send_recv_3x3().
sel_cppy_from_recv_buf_3x6()
subroutine select_copy_from_recv::sel_cppy_from_recv_buf_3x6 (integer(kind = kint), intent(in) iflag_recv, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) ntot_import, integer(kind = kint), dimension(ntot_import), intent(in) inod_import, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, real (kind=kreal), dimension(18*(ntot_import+1)), intent(inout) WR, real (kind=kreal), dimension(isix*nnod_new), intent(inout) X1_new, real (kind=kreal), dimension(isix*nnod_new), intent(inout) X2_new, real (kind=kreal), dimension(isix*nnod_new), intent(inout) X3_new)
Definition at line 381 of file select_copy_from_recv.f90.
References iflag_import_rev, m_constants::isix, set_from_recv_buff_tri::set_from_recv_buf_3x6(), and set_from_recv_buf_rev_tri::set_from_recv_buf_rev_3x6().
Referenced by calypso_sr_6::calypso_send_recv_3x6().
sel_cppy_from_recv_buf_3xn()
subroutine select_copy_from_recv::sel_cppy_from_recv_buf_3xn (integer(kind = kint), intent(in) iflag_recv, integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) npe_recv, integer(kind = kint), intent(in) ntot_import, integer(kind = kint), dimension(0:npe_recv), intent(in) istack_recv, integer(kind = kint), dimension(ntot_import), intent(in) inod_import, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, real (kind=kreal), dimension(3*nb*(ntot_import+1)), intent(inout) WR, real (kind=kreal), dimension(nb*nnod_new), intent(inout) X1_new, real (kind=kreal), dimension(nb*nnod_new), intent(inout) X2_new, real (kind=kreal), dimension(nb*nnod_new), intent(inout) X3_new)
Definition at line 413 of file select_copy_from_recv.f90.
References iflag_import_rev, set_from_recv_buff_tri::set_from_recv_buf_3xn(), and set_from_recv_buf_rev_tri::set_from_recv_buf_rev_3xn().
Referenced by calypso_sr_n::calypso_send_recv_3xn().
sel_cppy_from_recv_buf_6()
subroutine select_copy_from_recv::sel_cppy_from_recv_buf_6 (integer(kind = kint), intent(in) iflag_recv, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) ntot_import, integer(kind = kint), dimension(ntot_import), intent(in) inod_import, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, real (kind=kreal), dimension(6*(ntot_import+1)), intent(inout) WR, real (kind=kreal), dimension(6*nnod_new), intent(inout) X_new)
Definition at line 183 of file select_copy_from_recv.f90.
References iflag_import_rev, set_from_recv_buffer::set_from_recv_buf_6(), and set_from_recv_buf_rev::set_from_recv_buf_rev_6().
Referenced by calypso_sr_6::calypso_send_recv_6().
sel_cppy_from_recv_buf_i8()
subroutine select_copy_from_recv::sel_cppy_from_recv_buf_i8 (integer(kind = kint), intent(in) iflag_recv, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) ntot_import, integer(kind = kint), dimension(ntot_import), intent(in) inod_import, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, integer(kind = kint_gl), dimension(ntot_import+1), intent(inout) i8WR, integer(kind = kint_gl), dimension(nnod_new), intent(inout) i8X_new)
Definition at line 481 of file select_copy_from_recv.f90.
References iflag_import_rev, set_from_recv_buffer::set_from_recv_buf_i8(), and set_from_recv_buf_rev::set_from_recv_buf_rev_i8().
Referenced by calypso_sr_int::calypso_send_recv_int8().
sel_cppy_from_recv_buf_int()
subroutine select_copy_from_recv::sel_cppy_from_recv_buf_int (integer(kind = kint), intent(in) iflag_recv, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) ntot_import, integer(kind = kint), dimension(ntot_import), intent(in) inod_import, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, integer (kind=kint), dimension(ntot_import+1), intent(inout) iWR, integer (kind=kint), dimension(nnod_new), intent(inout) iX_new)
Definition at line 451 of file select_copy_from_recv.f90.
References iflag_import_rev, set_from_recv_buffer::set_from_recv_buf_int(), and set_from_recv_buf_rev::set_from_recv_buf_rev_int().
Referenced by calypso_sr_int::calypso_send_recv_int().
sel_cppy_from_recv_buf_n()
subroutine select_copy_from_recv::sel_cppy_from_recv_buf_n (integer(kind = kint), intent(in) iflag_recv, integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) npe_recv, integer(kind = kint), intent(in) ntot_import, integer(kind = kint), dimension(0:npe_recv), intent(in) istack_recv, integer(kind = kint), dimension(ntot_import), intent(in) inod_import, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, real (kind=kreal), dimension(nb*(ntot_import+1)), intent(inout) WR, real (kind=kreal), dimension(nb*nnod_new), intent(inout) X_new)
Definition at line 213 of file select_copy_from_recv.f90.
References iflag_import_mod, iflag_import_rev, set_from_recv_buffer::set_from_recv_buf_n(), set_from_recv_buffer::set_from_recv_buf_n_mod(), and set_from_recv_buf_rev::set_from_recv_buf_rev_n().
Referenced by calypso_sr_n::calypso_send_recv_n().
sel_cppy_to_send_buf_n()
subroutine select_copy_from_recv::sel_cppy_to_send_buf_n (integer(kind = kint), intent(in) iflag_recv, integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_org, integer(kind = kint), intent(in) npe_send, integer(kind = kint), intent(in) ntot_export, integer(kind = kint), dimension(0:npe_send), intent(in) istack_send, integer(kind = kint), dimension(ntot_export), intent(in) inod_export, real (kind=kreal), dimension(nb*nnod_org), intent(in) X_org, real (kind=kreal), dimension(nb*(ntot_export+1)), intent(inout) WS)
Definition at line 251 of file select_copy_from_recv.f90.
References iflag_import_mod, set_to_send_buffer::set_to_send_buf_n(), and set_to_send_buffer::set_to_send_buf_n_mod().
Referenced by calypso_sr_n::calypso_send_recv_n().
Variable Documentation
iflag_import_item
integer(kind = kint), parameter select_copy_from_recv::iflag_import_item = 0
Integer flag to use import table.
Definition at line 77 of file select_copy_from_recv.f90.
Referenced by analyzer_test_sph::analyze_test_sph(), sel_spherical_srs::sel_calypso_from_recv_n(), init_spherical_srs::sel_sph_import_table(), sel_spherical_srs::sel_sph_scalar_from_recv(), sel_spherical_srs::sel_sph_tensor_from_recv(), sel_spherical_srs::sel_sph_vector_from_recv(), t_work_4_sph_trans::set_import_table_ctl(), and t_work_4_sph_trans::write_import_table_mode().
iflag_import_mod
integer(kind = kint), parameter select_copy_from_recv::iflag_import_mod = 2
Integer flag to use testroutine to import.
Definition at line 81 of file select_copy_from_recv.f90.
Referenced by sel_cppy_from_recv_buf_n(), and sel_cppy_to_send_buf_n().
iflag_import_rev
integer(kind = kint), parameter select_copy_from_recv::iflag_import_rev = 1
Integer flag to use reversed import table for data points.
Definition at line 79 of file select_copy_from_recv.f90.
Referenced by analyzer_test_sph::analyze_test_sph(), sel_cppy_from_recv_buf_1(), sel_cppy_from_recv_buf_2(), sel_cppy_from_recv_buf_3(), sel_cppy_from_recv_buf_3x1(), sel_cppy_from_recv_buf_3x2(), sel_cppy_from_recv_buf_3x3(), sel_cppy_from_recv_buf_3x6(), sel_cppy_from_recv_buf_3xn(), sel_cppy_from_recv_buf_6(), sel_cppy_from_recv_buf_i8(), sel_cppy_from_recv_buf_int(), sel_cppy_from_recv_buf_n(), init_spherical_srs::sel_sph_import_table(), t_work_4_sph_trans::set_import_table_ctl(), and t_work_4_sph_trans::write_import_table_mode().
iflag_import_test
integer(kind = kint), parameter select_copy_from_recv::iflag_import_test = -10
Integer flag to use testroutine to import.
Definition at line 83 of file select_copy_from_recv.f90.
iflag_import_undefined
integer(kind = kint), parameter select_copy_from_recv::iflag_import_undefined = -1
Undefined flag.
Definition at line 75 of file select_copy_from_recv.f90.
Referenced by init_spherical_srs::sel_sph_import_table(), and t_work_4_sph_trans::set_import_table_ctl().