CALYPSO: t_leg_trans_sym_matmul_big Module Reference
t_leg_trans_sym_matmul_big Module Reference
Work array for forward Legendre transform useing mat multi
data are strored communication buffer.
Data Types
type leg_trns_bsym_mul_work
Work structure for Legendre trasform by large matmul.
Functions/Subroutines
subroutine init_leg_sym_matmul_big (sph_rtm, sph_rlm, leg, idx_trns, nvector, nscalar, WK_l_bsm)
subroutine init_leg_sym_matmul_big2 (sph_rtm, sph_rlm, leg, idx_trns, nvector, nscalar, WK_l_bsm)
subroutine, private const_symmetric_legendre_lj (jmax_rlm, nth_rtm, mphi_rtm, leg, idx_trns, WK_l_bsm)
subroutine, private alloc_leg_sym_matmul_big (nth_rtm, maxidx_rtm_r_smp, nvector, nscalar, idx_trns, WK_l_bsm)
subroutine, private alloc_leg_sym_matmul_big2 (nri_rtm, maxidx_rtm_t_smp, nvector, nscalar, idx_trns, WK_l_bsm)
subroutine dealloc_leg_sym_matmul_big (WK_l_bsm)
Detailed Description
Work array for forward Legendre transform useing mat multi
data are strored communication buffer.
      subroutine init_leg_sym_matmul_big(sph_rtm, sph_rlm, leg,       &
     &          idx_trns, nvector, nscalar, WK_l_bsm)
      subroutine init_leg_sym_matmul_big2(sph_rtm, sph_rlm, leg,      &
     &          idx_trns, nvector, nscalar, WK_l_bsm)
        type(sph_rtm_grid), intent(in) :: sph_rtm
        type(sph_rlm_grid), intent(in) :: sph_rlm
        type(legendre_4_sph_trans), intent(in) :: leg
        type(index_4_sph_trans), intent(in) :: idx_trns
        type(leg_trns_bsym_mul_work), intent(inout) :: WK_l_bsm
      subroutine dealloc_leg_sym_matmul_big(WK_l_bsm)
        type(leg_trns_bsym_mul_work), intent(inout) :: WK_l_bsm
     field data for Legendre transform
       original layout: vr_rtm(l_rtm,m_rtm,k_rtm,icomp)
       size: vr_rtm(nth_rtm,nidx_rtm(1)*ncomp,nidx_rtm(3))
      real(kind = kreal), allocatable :: vr_rtm(:,:,:)
     spectr data for Legendre transform
       original layout: sp_rlm(j_rlm,k_rtm,icomp)
        size: sp_rlm(nidx_rlm(2),nidx_rtm(1)*ncomp)
      real(kind = kreal), allocatable :: sp_rlm(:,:)
Parameters
ncomp Total number of components for spherical transform
nvector Number of vector for spherical transform
nscalar Number of scalar (including tensor components) for spherical transform
Function/Subroutine Documentation
alloc_leg_sym_matmul_big()
subroutine, private t_leg_trans_sym_matmul_big::alloc_leg_sym_matmul_big (integer(kind = kint), intent(in) nth_rtm, integer(kind = kint), intent(in) maxidx_rtm_r_smp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(index_4_sph_trans), intent(in) idx_trns, type(leg_trns_bsym_mul_work), intent(inout) WK_l_bsm) private
Definition at line 269 of file t_leg_trans_sym_matmul_big.f90.
References m_machine_parameter::np_smp.
Referenced by init_leg_sym_matmul_big().
alloc_leg_sym_matmul_big2()
subroutine, private t_leg_trans_sym_matmul_big::alloc_leg_sym_matmul_big2 (integer(kind = kint), intent(in) nri_rtm, integer(kind = kint), intent(in) maxidx_rtm_t_smp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(index_4_sph_trans), intent(in) idx_trns, type(leg_trns_bsym_mul_work), intent(inout) WK_l_bsm) private
Definition at line 306 of file t_leg_trans_sym_matmul_big.f90.
References m_machine_parameter::np_smp.
Referenced by init_leg_sym_matmul_big2().
const_symmetric_legendre_lj()
subroutine, private t_leg_trans_sym_matmul_big::const_symmetric_legendre_lj (integer(kind = kint), intent(in) jmax_rlm, integer(kind = kint), intent(in) nth_rtm, integer(kind = kint), intent(in) mphi_rtm, type(legendre_4_sph_trans), intent(in) leg, type(index_4_sph_trans), intent(in) idx_trns, type(leg_trns_bsym_mul_work), intent(inout) WK_l_bsm) private
Definition at line 244 of file t_leg_trans_sym_matmul_big.f90.
References set_legendre_matrices::set_symmetric_legendre_lj().
Referenced by init_leg_sym_matmul_big(), and init_leg_sym_matmul_big2().
dealloc_leg_sym_matmul_big()
subroutine t_leg_trans_sym_matmul_big::dealloc_leg_sym_matmul_big (type(leg_trns_bsym_mul_work), intent(inout) WK_l_bsm)
Definition at line 344 of file t_leg_trans_sym_matmul_big.f90.
Referenced by t_legendre_trans_select::sel_finalize_legendre_trans().
init_leg_sym_matmul_big()
subroutine t_leg_trans_sym_matmul_big::init_leg_sym_matmul_big (type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(legendre_4_sph_trans), intent(in) leg, type(index_4_sph_trans), intent(in) idx_trns, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(leg_trns_bsym_mul_work), intent(inout) WK_l_bsm)
Definition at line 191 of file t_leg_trans_sym_matmul_big.f90.
References alloc_leg_sym_matmul_big(), const_symmetric_legendre_lj(), and m_machine_parameter::np_smp.
Referenced by t_legendre_trans_select::sel_init_legendre_trans().
init_leg_sym_matmul_big2()
subroutine t_leg_trans_sym_matmul_big::init_leg_sym_matmul_big2 (type(sph_rtm_grid), intent(in) sph_rtm, type(sph_rlm_grid), intent(in) sph_rlm, type(legendre_4_sph_trans), intent(in) leg, type(index_4_sph_trans), intent(in) idx_trns, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(leg_trns_bsym_mul_work), intent(inout) WK_l_bsm)
Definition at line 217 of file t_leg_trans_sym_matmul_big.f90.
References alloc_leg_sym_matmul_big2(), const_symmetric_legendre_lj(), and m_machine_parameter::np_smp.