CALYPSO: t_fft_selector Module Reference
t_fft_selector Module Reference
Selector of Fourier transform using structure.
Data Types
type working_ffts
structure for working data for FFT
Functions/Subroutines
subroutine initialize_fft_select (id_rank, iflag_FFT, Nsmp, Nstacksmp, Nfft, WKS)
subroutine finalize_fft_sel_t (iflag_FFT, Nsmp, Nstacksmp, WKS)
subroutine verify_fft_select (iflag_FFT, Nsmp, Nstacksmp, Nfft, WKS)
subroutine forward_fft_select (iflag_FFT, Nsmp, Nstacksmp, M, Nfft, X, WKS)
subroutine backward_fft_select (iflag_FFT, Nsmp, Nstacksmp, M, Nfft, X, WKS)
Detailed Description
Selector of Fourier transform using structure.
      subroutine initialize_FFT_select(id_rank, iflag_FFT,            &
     &          Nsmp, Nstacksmp, Nfft, WKS)
      subroutine finalize_FFT_sel_t(iflag_FFT, Nsmp, Nstacksmp, WKS)
      subroutine verify_FFT_select                                    &
     &         (iflag_FFT, Nsmp, Nstacksmp, Nfft, WKS)
 ------------------------------------------------------------------
   wrapper subroutine for initierize FFT for ISPACK
 ------------------------------------------------------------------
      subroutine forward_FFT_select                                   &
     &         (iflag_FFT, Nsmp, Nstacksmp, M, Nfft, X, WKS)
 ------------------------------------------------------------------
   wrapper subroutine for FFT in ISPACK
   a_{k} = \frac{2}{Nfft} \sum_{j=0}^{Nfft-1} x_{j} \cos (\frac{2\pi j k}{Nfft})
   b_{k} = \frac{2}{Nfft} \sum_{j=0}^{Nfft-1} x_{j} \cos (\frac{2\pi j k}{Nfft})
   a_{0} = \frac{1}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
    K = Nfft/2....
   a_{k} = \frac{1}{Nfft} \sum_{j=0}^{Nfft-1} x_{j} \cos (\frac{2\pi j k}{Nfft})
 ------------------------------------------------------------------
      subroutine backward_FFT_select                                  &
     &         (iflag_FFT, Nsmp, Nstacksmp, M, Nfft, X, WKS)
 ------------------------------------------------------------------
   wrapper subroutine for backward FFT
   x_{k} = a_{0} + (-1)^{j} a_{Nfft/2} + sum_{k=1}^{Nfft/2-1}
          (a_{k} \cos(2\pijk/Nfft) + b_{k} \sin(2\pijk/Nfft))
 ------------------------------------------------------------------
       i = 1:     a_{0}
       i = 2:     a_{Nfft/2}
       i = 3:     a_{1}
       i = 4:     b_{1}
       ...
       i = 2*k+1: a_{k}
       i = 2*k+2: b_{k}
       ...
       i = Nfft-1:   a_{Nfft/2-1}
       i = Nfft:     b_{Nfft/2-1}
 ------------------------------------------------------------------
Parameters
Nsmp Number of SMP processors
Nstacksmp(0:Nsmp) End number for each SMP process
M Number of components for Fourier transforms
Nfft Data length for eadh FFT
X(M,Nfft) Data for Fourier transform
WKS Work structure for ISPACK
Function/Subroutine Documentation
backward_fft_select()
subroutine t_fft_selector::backward_fft_select (integer(kind = kint), intent(in) iflag_FFT, integer(kind = kint), intent(in) Nsmp, integer(kind = kint), dimension(0:nsmp), intent(in) Nstacksmp, integer(kind = kint), intent(in) M, integer(kind = kint), intent(in) Nfft, real(kind = kreal), dimension(m,nfft), intent(inout) X, type(working_ffts), intent(inout) WKS)
Definition at line 212 of file t_FFT_selector.F90.
References t_fftpack5_wrapper::calypso_rfftmb_t(), t_fftw_wrapper::fftw_backward_type(), t_multi_fftw_wrapper::fftw_mul_backward_type(), m_fft_selector::iflag_fftw, and m_fft_selector::iflag_fftw_single.
Referenced by circle_transform_single::circle_transfer_scalar(), and circle_transform_single::circle_transfer_vector().
finalize_fft_sel_t()
subroutine t_fft_selector::finalize_fft_sel_t (integer(kind = kint), intent(in) iflag_FFT, integer(kind = kint), intent(in) Nsmp, integer(kind = kint), dimension(0:nsmp), intent(in) Nstacksmp, type(working_ffts), intent(inout) WKS)
Definition at line 125 of file t_FFT_selector.F90.
References t_multi_fftw_wrapper::finalize_fftw_mul_type(), t_fftw_wrapper::finalize_fftw_type(), t_fftpack5_wrapper::finalize_wk_fftpack_t(), m_machine_parameter::iflag_debug, m_fft_selector::iflag_fftw, and m_fft_selector::iflag_fftw_single.
forward_fft_select()
subroutine t_fft_selector::forward_fft_select (integer(kind = kint), intent(in) iflag_FFT, integer(kind = kint), intent(in) Nsmp, integer(kind = kint), dimension(0:nsmp), intent(in) Nstacksmp, integer(kind = kint), intent(in) M, integer(kind = kint), intent(in) Nfft, real(kind = kreal), dimension(m, nfft), intent(inout) X, type(working_ffts), intent(inout) WKS)
Definition at line 182 of file t_FFT_selector.F90.
References t_fftpack5_wrapper::calypso_rfftmf_t(), t_fftw_wrapper::fftw_forward_type(), t_multi_fftw_wrapper::fftw_mul_forward_type(), m_fft_selector::iflag_fftw, and m_fft_selector::iflag_fftw_single.
initialize_fft_select()
subroutine t_fft_selector::initialize_fft_select (integer, intent(in) id_rank, integer(kind = kint), intent(in) iflag_FFT, integer(kind = kint), intent(in) Nsmp, integer(kind = kint), dimension(0:nsmp), intent(in) Nstacksmp, integer(kind = kint), intent(in) Nfft, type(working_ffts), intent(inout) WKS)
Definition at line 94 of file t_FFT_selector.F90.
References m_fft_selector::iflag_fftw, m_fft_selector::iflag_fftw_single, t_multi_fftw_wrapper::init_fftw_mul_type(), t_fftw_wrapper::init_fftw_type(), and t_fftpack5_wrapper::init_wk_fftpack_t().
Referenced by circle_transform_single::initialize_circle_transform().
verify_fft_select()
subroutine t_fft_selector::verify_fft_select (integer(kind = kint), intent(in) iflag_FFT, integer(kind = kint), intent(in) Nsmp, integer(kind = kint), dimension(0:nsmp), intent(in) Nstacksmp, integer(kind = kint), intent(in) Nfft, type(working_ffts), intent(inout) WKS)
Definition at line 151 of file t_FFT_selector.F90.
References m_machine_parameter::iflag_debug, m_fft_selector::iflag_fftw, m_fft_selector::iflag_fftw_single, t_fftpack5_wrapper::verify_wk_fftpack_t(), t_multi_fftw_wrapper::verify_wk_fftw_mul_type(), and t_fftw_wrapper::verify_wk_fftw_type().