CALYPSO: lead_fields_4_sph_mhd Module Reference
lead_fields_4_sph_mhd Module Reference
Evaluate pressure and energy fluxes for snapshots.
Functions/Subroutines
subroutine s_lead_fields_4_sph_mhd (monitor, r_2nd, MHD_prop, sph_MHD_bc, trans_p, sph_MHD_mat, WK, SPH_MHD)
subroutine lead_fields_by_sph_trans (sph, comms_sph, MHD_prop, trans_p, trns_MHD, trns_snap, WK_leg, WK_FFTs, rj_fld)
subroutine, private pressure_4_sph_mhd (sph, MHD_prop, sph_MHD_bc, r_2nd, leg, band_p_poisson, ipol, rj_fld)
subroutine, private enegy_fluxes_4_sph_mhd (ltr_crust, sph, comms_sph, r_2nd, MHD_prop, sph_MHD_bc, trans_p, ipol, trns_MHD, trns_snap, trns_difv, trns_eflux, WK_leg, WK_FFTs, rj_fld)
subroutine cal_sph_enegy_fluxes (ltr_crust, sph, comms_sph, r_2nd, MHD_prop, sph_MHD_bc, trans_p, ipol, trns_MHD, trns_snap, trns_difv, trns_eflux, WK_leg, WK_FFTs, rj_fld)
subroutine gradients_of_vectors_sph (sph, comms_sph, r_2nd, sph_MHD_bc, trans_p, ipol, trns_snap, trns_difv, WK_leg, WK_FFTs, rj_fld)
Detailed Description
Evaluate pressure and energy fluxes for snapshots.
      subroutine s_lead_fields_4_sph_mhd                              &
     &         (monitor, r_2nd, MHD_prop, sph_MHD_bc, trans_p,        &
     &          sph_MHD_mat, WK, SPH_MHD)
        type(sph_mhd_monitor_data), intent(in) :: monitor
        type(fdm_matrices), intent(in) :: r_2nd
        type(MHD_evolution_param), intent(in) :: MHD_prop
        type(sph_MHD_boundary_data), intent(in) :: sph_MHD_bc
        type(parameters_4_sph_trans), intent(in) :: trans_p
        type(works_4_sph_trans_MHD), intent(inout) :: WK
        type(dynamic_SGS_data_4_sph), intent(inout) :: dynamic_SPH
        type(MHD_radial_matrices), intent(inout) :: sph_MHD_mat
        type(SPH_mesh_field_data), intent(inout) :: SPH_MHD
      subroutine lead_fields_by_sph_trans(sph, comms_sph, MHD_prop,   &
     &          trans_p, trns_MHD, trns_snap, WK_leg, WK_FFTs, rj_fld)
        type(sph_grids), intent(in) :: sph
        type(sph_comm_tables), intent(in) :: comms_sph
        type(MHD_evolution_param), intent(in) :: MHD_prop
        type(parameters_4_sph_trans), intent(in) :: trans_p
        type(address_4_sph_trans), intent(inout) :: trns_MHD
        type(phys_data), intent(inout) :: rj_fld
      subroutine cal_sph_enegy_fluxes(ltr_crust, sph, comms_sph,      &
     &          r_2nd, MHD_prop, sph_MHD_bc, trans_p,                 &
     &          ipol, trns_MHD, trns_snap, trns_difv, trns_eflux,     &
     &          WK_leg, WK_FFTs, rj_fld)
        type(sph_grids), intent(in) :: sph
        type(sph_comm_tables), intent(in) :: comms_sph
        type(fdm_matrices), intent(in) :: r_2nd
        type(MHD_evolution_param), intent(in) :: MHD_prop
        type(sph_MHD_boundary_data), intent(in) :: sph_MHD_bc
        type(parameters_4_sph_trans), intent(in) :: trans_p
        type(phys_address), intent(in) :: ipol
        type(address_4_sph_trans), intent(in) :: trns_MHD
        type(address_4_sph_trans), intent(in) :: trns_snap
        type(address_4_sph_trans), intent(in) :: trns_difv
        type(address_4_sph_trans), intent(inout) :: trns_eflux
        type(legendre_trns_works), intent(inout) :: WK_leg
        type(work_for_FFTs), intent(inout) :: WK_FFTs
        type(phys_data), intent(inout) :: rj_fld
      subroutine gradients_of_vectors_sph                             &
     &         (sph, comms_sph, r_2nd, sph_MHD_bc, trans_p,           &
     &          ipol, trns_snap, trns_difv, WK_leg, WK_FFTs, rj_fld)
        type(sph_grids), intent(in) :: sph
        type(sph_comm_tables), intent(in) :: comms_sph
        type(fdm_matrices), intent(in) :: r_2nd
        type(parameters_4_sph_trans), intent(in) :: trans_p
        type(address_4_sph_trans), intent(in) :: trns_snap
        type(sph_MHD_boundary_data), intent(in) :: sph_MHD_bc
        type(phys_address), intent(in) :: ipol
        type(address_4_sph_trans), intent(inout) :: trns_difv
        type(legendre_trns_works), intent(inout) :: WK_leg
        type(work_for_FFTs), intent(inout) :: WK_FFTs
        type(phys_data), intent(inout) :: rj_fld
Function/Subroutine Documentation
cal_sph_enegy_fluxes()
subroutine lead_fields_4_sph_mhd::cal_sph_enegy_fluxes (integer(kind = kint), intent(in) ltr_crust, type(sph_grids), intent(in) sph, type(sph_comm_tables), intent(in) comms_sph, type(fdm_matrices), intent(in) r_2nd, type(mhd_evolution_param), intent(in) MHD_prop, type(sph_mhd_boundary_data), intent(in) sph_MHD_bc, type(parameters_4_sph_trans), intent(in) trans_p, type(phys_address), intent(in) ipol, type(address_4_sph_trans), intent(in) trns_MHD, type(address_4_sph_trans), intent(in) trns_snap, type(address_4_sph_trans), intent(in) trns_difv, type(address_4_sph_trans), intent(inout) trns_eflux, type(legendre_trns_works), intent(inout) WK_leg, type(work_for_ffts), intent(inout) WK_FFTs, type(phys_data), intent(inout) rj_fld)
Definition at line 276 of file lead_fields_4_sph_mhd.f90.
References m_machine_parameter::iflag_debug, cal_energy_flux_rj::s_cal_energy_flux_rj(), cal_energy_flux_rtp::s_cal_energy_flux_rtp(), and sph_transforms_snapshot::sph_back_trans_snapshot_mhd().
Referenced by enegy_fluxes_4_sph_mhd().
enegy_fluxes_4_sph_mhd()
subroutine, private lead_fields_4_sph_mhd::enegy_fluxes_4_sph_mhd (integer(kind = kint), intent(in) ltr_crust, type(sph_grids), intent(in) sph, type(sph_comm_tables), intent(in) comms_sph, type(fdm_matrices), intent(in) r_2nd, type(mhd_evolution_param), intent(in) MHD_prop, type(sph_mhd_boundary_data), intent(in) sph_MHD_bc, type(parameters_4_sph_trans), intent(in) trans_p, type(phys_address), intent(in) ipol, type(address_4_sph_trans), intent(in) trns_MHD, type(address_4_sph_trans), intent(in) trns_snap, type(address_4_sph_trans), intent(in) trns_difv, type(address_4_sph_trans), intent(inout) trns_eflux, type(legendre_trns_works), intent(inout) WK_leg, type(work_for_ffts), intent(inout) WK_FFTs, type(phys_data), intent(inout) rj_fld) private
Definition at line 232 of file lead_fields_4_sph_mhd.f90.
References cal_sph_enegy_fluxes(), m_machine_parameter::iflag_debug, and sph_transforms_snapshot::sph_forward_trans_snapshot_mhd().
Referenced by s_lead_fields_4_sph_mhd().
gradients_of_vectors_sph()
subroutine lead_fields_4_sph_mhd::gradients_of_vectors_sph (type(sph_grids), intent(in) sph, type(sph_comm_tables), intent(in) comms_sph, type(fdm_matrices), intent(in) r_2nd, type(sph_mhd_boundary_data), intent(in) sph_MHD_bc, type(parameters_4_sph_trans), intent(in) trans_p, type(phys_address), intent(in) ipol, type(address_4_sph_trans), intent(in) trns_snap, type(address_4_sph_trans), intent(inout) trns_difv, type(legendre_trns_works), intent(inout) WK_leg, type(work_for_ffts), intent(inout) WK_FFTs, type(phys_data), intent(inout) rj_fld)
Definition at line 326 of file lead_fields_4_sph_mhd.f90.
References copy_rtp_vectors_4_grad::copy_vectors_rtp_4_grad(), m_machine_parameter::iflag_debug, cal_grad_of_sph_vectors::overwrt_grad_of_vectors_sph(), sph_transforms_snapshot::sph_back_trans_snapshot_mhd(), and sph_transforms_snapshot::sph_forward_trans_snapshot_mhd().
Referenced by s_lead_fields_4_sph_mhd().
lead_fields_by_sph_trans()
subroutine lead_fields_4_sph_mhd::lead_fields_by_sph_trans (type(sph_grids), intent(in) sph, type(sph_comm_tables), intent(in) comms_sph, type(mhd_evolution_param), intent(in) MHD_prop, type(parameters_4_sph_trans), intent(in) trans_p, type(address_4_sph_trans), intent(inout) trns_MHD, type(address_4_sph_trans), intent(inout) trns_snap, type(legendre_trns_works), intent(inout) WK_leg, type(work_for_ffts), intent(inout) WK_FFTs, type(phys_data), intent(inout) rj_fld)
Definition at line 145 of file lead_fields_4_sph_mhd.f90.
References cal_nonlinear_sph_mhd::cal_nonlinear_pole_mhd(), m_machine_parameter::iflag_debug, and sph_transforms_snapshot::sph_back_trans_snapshot_mhd().
Referenced by s_lead_fields_4_sph_mhd().
pressure_4_sph_mhd()
subroutine, private lead_fields_4_sph_mhd::pressure_4_sph_mhd (type(sph_grids), intent(in) sph, type(mhd_evolution_param), intent(in) MHD_prop, type(sph_mhd_boundary_data), intent(in) sph_MHD_bc, type(fdm_matrices), intent(in) r_2nd, type(legendre_4_sph_trans), intent(in) leg, type(band_matrices_type), intent(in) band_p_poisson, type(phys_address), intent(in) ipol, type(phys_data), intent(inout) rj_fld) private
Definition at line 180 of file lead_fields_4_sph_mhd.f90.
References cal_sph_divergence_of_force::cal_div_of_forces_sph_2(), cal_sol_sph_fluid_crank::cal_sol_pressure_by_div_v(), const_sph_radial_grad::const_pressure_gradient(), m_machine_parameter::iflag_debug, const_radial_forces_on_bc::s_const_radial_forces_on_bc(), and cal_div_of_forces::sum_div_of_forces().
Referenced by s_lead_fields_4_sph_mhd().
s_lead_fields_4_sph_mhd()
subroutine lead_fields_4_sph_mhd::s_lead_fields_4_sph_mhd (type(sph_mhd_monitor_data), intent(in) monitor, type(fdm_matrices), intent(in) r_2nd, type(mhd_evolution_param), intent(in) MHD_prop, type(sph_mhd_boundary_data), intent(in) sph_MHD_bc, type(parameters_4_sph_trans), intent(in) trans_p, type(mhd_radial_matrices), intent(inout) sph_MHD_mat, type(works_4_sph_trans_mhd), intent(inout) WK, type(sph_mesh_field_data), intent(inout) SPH_MHD)
Definition at line 98 of file lead_fields_4_sph_mhd.f90.
References enegy_fluxes_4_sph_mhd(), gradients_of_vectors_sph(), lead_fields_by_sph_trans(), pressure_4_sph_mhd(), and cal_self_buoyancies_sph::sel_buoyancies_sph_mhd().
Referenced by sph_analyzer_d_bench::sph_analyze_dbench(), sph_analyzer_mhd::sph_analyze_mhd(), and sph_analyzer_snap_w_psf::sph_analyze_snap_psf().