CALYPSO: gz_sph_modes_file_io_b Module Reference
gz_sph_modes_file_io_b Module Reference
gzipped binary spectr data IO routines
Functions/Subroutines
subroutine gz_read_geom_rtp_file_b (file_name, id_rank, sph_file, ierr)
subroutine gz_read_spectr_modes_rj_file_b (file_name, id_rank, sph_file, ierr)
subroutine gz_read_geom_rtm_file_b (file_name, id_rank, sph_file, ierr)
subroutine gz_read_modes_rlm_file_b (file_name, id_rank, sph_file, ierr)
subroutine gz_write_geom_rtp_file_b (file_name, id_rank, sph_file)
subroutine gz_write_spectr_modes_rj_file_b (file_name, id_rank, sph_file)
subroutine gz_write_geom_rtm_file_b (file_name, id_rank, sph_file)
subroutine gz_write_modes_rlm_file_b (file_name, id_rank, sph_file)
Variables
type(buffer_4_gzip), private zbuf_sph
Detailed Description
gzipped binary spectr data IO routines
      subroutine gz_read_geom_rtp_file_b                              &
     &         (file_name, id_rank, sph_file, ierr)
      subroutine gz_read_spectr_modes_rj_file_b                       &
     &         (file_name, id_rank, sph_file, ierr)
      subroutine gz_read_geom_rtm_file_b                              &
     &         (file_name, id_rank, sph_file, ierr)
      subroutine gz_read_modes_rlm_file_b                             &
     &         (file_name, id_rank, sph_file, ierr)
        type(sph_file_data_type), intent(inout) :: sph_file
      subroutine gz_write_geom_rtp_file_b                             &
     &         (file_name, id_rank, sph_file)
      subroutine gz_write_spectr_modes_rj_file_b                      &
     &         (file_name, id_rank, sph_file)
      subroutine gz_write_geom_rtm_file_b                             &
     &         (file_name, id_rank, sph_file)
      subroutine gz_write_modes_rlm_file_b                            &
     &         (file_name, id_rank, sph_file)
        type(sph_file_data_type), intent(in) :: sph_file
Parameters
id_rank Process ID
file_name file name for IO (.gz is appended in this module)
Function/Subroutine Documentation
gz_read_geom_rtm_file_b()
subroutine gz_sph_modes_file_io_b::gz_read_geom_rtm_file_b (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(sph_file_data_type), intent(inout) sph_file, integer(kind = kint), intent(inout) ierr)
Definition at line 112 of file gz_sph_modes_file_IO_b.f90.
References gzip_file_access::close_gzfile_b(), gz_sph_modes_data_io_b::gz_read_geom_rtm_data_b(), m_machine_parameter::i_debug, and zbuf_sph.
Referenced by sph_file_io_select::sel_read_geom_rtm_file().
gz_read_geom_rtp_file_b()
subroutine gz_sph_modes_file_io_b::gz_read_geom_rtp_file_b (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(sph_file_data_type), intent(inout) sph_file, integer(kind = kint), intent(inout) ierr)
Definition at line 54 of file gz_sph_modes_file_IO_b.f90.
References gzip_file_access::close_gzfile_b(), gz_sph_modes_data_io_b::gz_read_geom_rtp_data_b(), m_machine_parameter::i_debug, and zbuf_sph.
Referenced by sph_file_io_select::sel_read_geom_rtp_file().
gz_read_modes_rlm_file_b()
subroutine gz_sph_modes_file_io_b::gz_read_modes_rlm_file_b (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(sph_file_data_type), intent(inout) sph_file, integer(kind = kint), intent(inout) ierr)
Definition at line 140 of file gz_sph_modes_file_IO_b.f90.
References gzip_file_access::close_gzfile_b(), gz_sph_modes_data_io_b::gz_read_modes_rlm_data_b(), m_machine_parameter::i_debug, and zbuf_sph.
Referenced by sph_file_io_select::sel_read_modes_rlm_file().
gz_read_spectr_modes_rj_file_b()
subroutine gz_sph_modes_file_io_b::gz_read_spectr_modes_rj_file_b (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(sph_file_data_type), intent(inout) sph_file, integer(kind = kint), intent(inout) ierr)
Definition at line 83 of file gz_sph_modes_file_IO_b.f90.
References gzip_file_access::close_gzfile_b(), gz_sph_modes_data_io_b::gz_read_spectr_modes_rj_data_b(), m_machine_parameter::i_debug, and zbuf_sph.
Referenced by sph_file_io_select::sel_read_spectr_rj_file().
gz_write_geom_rtm_file_b()
subroutine gz_sph_modes_file_io_b::gz_write_geom_rtm_file_b (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(sph_file_data_type), intent(in) sph_file)
Definition at line 213 of file gz_sph_modes_file_IO_b.f90.
References gzip_file_access::close_gzfile_b(), gz_sph_modes_data_io_b::gz_write_geom_rtm_data_b(), m_machine_parameter::i_debug, and zbuf_sph.
Referenced by sph_file_io_select::sel_write_geom_rtm_file().
gz_write_geom_rtp_file_b()
subroutine gz_sph_modes_file_io_b::gz_write_geom_rtp_file_b (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(sph_file_data_type), intent(in) sph_file)
Definition at line 169 of file gz_sph_modes_file_IO_b.f90.
References gzip_file_access::close_gzfile_b(), gz_sph_modes_data_io_b::gz_write_geom_rtp_data_b(), m_machine_parameter::i_debug, and zbuf_sph.
Referenced by sph_file_io_select::sel_write_geom_rtp_file().
gz_write_modes_rlm_file_b()
subroutine gz_sph_modes_file_io_b::gz_write_modes_rlm_file_b (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(sph_file_data_type), intent(in) sph_file)
Definition at line 234 of file gz_sph_modes_file_IO_b.f90.
References gzip_file_access::close_gzfile_b(), gz_sph_modes_data_io_b::gz_write_modes_rlm_data_b(), m_machine_parameter::i_debug, and zbuf_sph.
Referenced by sph_file_io_select::sel_write_modes_rlm_file().
gz_write_spectr_modes_rj_file_b()
subroutine gz_sph_modes_file_io_b::gz_write_spectr_modes_rj_file_b (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(sph_file_data_type), intent(in) sph_file)
Definition at line 191 of file gz_sph_modes_file_IO_b.f90.
References gzip_file_access::close_gzfile_b(), gz_sph_modes_data_io_b::gz_write_spectr_modes_rj_data_b(), m_machine_parameter::i_debug, and zbuf_sph.
Referenced by sph_file_io_select::sel_write_spectr_modes_rj_file().
Variable Documentation
zbuf_sph
type(buffer_4_gzip), private gz_sph_modes_file_io_b::zbuf_sph private
Definition at line 46 of file gz_sph_modes_file_IO_b.f90.
Referenced by gz_read_geom_rtm_file_b(), gz_read_geom_rtp_file_b(), gz_read_modes_rlm_file_b(), gz_read_spectr_modes_rj_file_b(), gz_write_geom_rtm_file_b(), gz_write_geom_rtp_file_b(), gz_write_modes_rlm_file_b(), and gz_write_spectr_modes_rj_file_b().