CALYPSO: mpi_picked_sph_spectr_io Module Reference
mpi_picked_sph_spectr_io Module Reference
Data arrays to monitoring spectrum data.
Functions/Subroutines
subroutine append_picked_spectrum_file (time_d, sph_rj, rj_fld, picked)
subroutine write_picked_specr_head_mpi (IO_param, picked)
subroutine, private write_picked_specr_data_mpi (IO_param, time_d, sph_rj, rj_fld, picked, ntot_comp_rj)
character(len=len_fixed+ntot_comp_rj *25) function picked_each_mode_to_text (i_step, time, radius, kr, l, m, ntot_comp_rj, d_rj_out)
subroutine write_picked_spectr_header_only (file_name, picked)
Variables
type(calypso_mpi_io_params), save, private io_param1
integer, parameter, private len_fixed = 4*16 + 2*25 + 1
Detailed Description
Data arrays to monitoring spectrum data.
      subroutine append_picked_spectrum_file                          &
     &         (time_d, sph_rj, rj_fld, picked)
        type(time_data), intent(in) :: time_d
        type(sph_rj_grid), intent(in) :: sph_rj
        type(phys_data), intent(in) :: rj_fld
        type(picked_spectrum_data), intent(in) :: picked
      subroutine write_picked_specr_head_mpi(IO_param, picked)
        type(picked_spectrum_data), intent(in) :: picked
      function picked_each_mode_to_text                               &
     &       (i_step, time, radius, kr, l, m, ntot_comp_rj, d_rj_out)
Function/Subroutine Documentation
append_picked_spectrum_file()
subroutine mpi_picked_sph_spectr_io::append_picked_spectrum_file (type(time_data), intent(in) time_d, type(sph_rj_grid), intent(in) sph_rj, type(phys_data), intent(in) rj_fld, type(picked_spectrum_data), intent(in) picked)
Definition at line 51 of file MPI_picked_sph_spectr_IO.f90.
References set_parallel_file_name::add_dat_extension(), calypso_mpi::calypso_mpi_barrier(), mpi_ascii_data_io::close_mpi_file(), io_param1, mpi_ascii_data_io::open_append_mpi_file(), write_picked_specr_data_mpi(), and write_picked_specr_head_mpi().
Referenced by cal_write_sph_monitor_data::output_sph_monitor_data().
picked_each_mode_to_text()
character(len = len_fixed+ntot_comp_rj*25) function mpi_picked_sph_spectr_io::picked_each_mode_to_text (integer(kind = kint), intent(in) i_step, real(kind = kreal), intent(in) time, real(kind = kreal), intent(in) radius, integer(kind = kint), intent(in) kr, integer(kind = kint), intent(in) l, integer(kind = kint), intent(in) m, integer(kind = kint), intent(in) ntot_comp_rj, real(kind = kreal), dimension(ntot_comp_rj), intent(in) d_rj_out)
Definition at line 209 of file MPI_picked_sph_spectr_IO.f90.
Referenced by write_picked_specr_data_mpi().
write_picked_specr_data_mpi()
subroutine, private mpi_picked_sph_spectr_io::write_picked_specr_data_mpi (type(calypso_mpi_io_params), intent(inout) IO_param, type(time_data), intent(in) time_d, type(sph_rj_grid), intent(in) sph_rj, type(phys_data), intent(in) rj_fld, type(picked_spectrum_data), intent(in) picked, integer(kind = kint), intent(in) ntot_comp_rj) private
Definition at line 137 of file MPI_picked_sph_spectr_IO.f90.
References m_constants::izero, len_fixed, m_calypso_mpi_io::mpi_write_mul_chara_b(), calypso_mpi::my_rank, calypso_mpi::nprocs, pickup_sph_spectr_data::pick_degre0_sped_4_monitor(), pickup_sph_spectr_data::pick_single_sph_spec_4_monitor(), picked_each_mode_to_text(), and m_constants::zero.
Referenced by append_picked_spectrum_file().
write_picked_specr_head_mpi()
subroutine mpi_picked_sph_spectr_io::write_picked_specr_head_mpi (type(calypso_mpi_io_params), intent(inout) IO_param, type(picked_spectrum_data), intent(in) picked)
Definition at line 92 of file MPI_picked_sph_spectr_IO.f90.
References calypso_mpi_int4::calypso_mpi_bcast_one_int4(), m_constants::ione, m_calypso_mpi_io::mpi_write_one_chara_b(), calypso_mpi::my_rank, and t_pickup_sph_spectr_data::pick_sph_header_no_field().
Referenced by append_picked_spectrum_file().
write_picked_spectr_header_only()
subroutine mpi_picked_sph_spectr_io::write_picked_spectr_header_only (character(len=kchara), intent(in) file_name, type(picked_spectrum_data), intent(in) picked)
Definition at line 235 of file MPI_picked_sph_spectr_IO.f90.
References t_pickup_sph_spectr_data::write_pick_sph_file_header().
Variable Documentation
io_param1
type(calypso_mpi_io_params), save, private mpi_picked_sph_spectr_io::io_param1 private
Definition at line 39 of file MPI_picked_sph_spectr_IO.f90.
Referenced by append_picked_spectrum_file().
len_fixed
integer, parameter, private mpi_picked_sph_spectr_io::len_fixed = 4*16 + 2*25 + 1 private
Definition at line 41 of file MPI_picked_sph_spectr_IO.f90.
Referenced by write_picked_specr_data_mpi().