CALYPSO: gz_mpi_viewer_mesh_io Module Reference
gz_mpi_viewer_mesh_io Module Reference
Viewer mesh file IO for gxipped format.
Functions/Subroutines
subroutine gz_mpi_write_viewer_position (IO_param, nnod64, numdir, id_global, xx)
subroutine gz_mpi_write_domain_grp_data (IO_param, view_grp)
subroutine gz_mpi_write_viewer_grp_data (IO_param, num_grp, grp_name, view_grp)
subroutine gz_mpi_write_viewer_grp_item (IO_param, ncolumn, num, int_dat)
Variables
type(buffer_4_gzip) zbuf
Detailed Description
Viewer mesh file IO for gxipped format.
      subroutine gz_mpi_write_viewer_position                         &
     &         (IO_param, nnod64, numdir, id_global, xx)
      subroutine gz_mpi_write_domain_grp_data(IO_param, view_grp)
      subroutine gz_mpi_write_viewer_grp_data                         &
     &         (IO_param, num_grp, grp_name, view_grp)
        type(viewer_group_data), intent(in) :: view_grp
      subroutine gz_mpi_write_viewer_grp_item                         &
     &         (IO_param, ncolumn, num, int_dat)
      type(calypso_MPI_IO_params), intent(inout) :: IO_param
Function/Subroutine Documentation
gz_mpi_write_domain_grp_data()
subroutine gz_mpi_viewer_mesh_io::gz_mpi_write_domain_grp_data (type(calypso_mpi_io_params), intent(inout) IO_param, type(viewer_group_data), intent(in) view_grp)
Definition at line 80 of file gz_MPI_viewer_mesh_IO.f90.
References gz_mpi_ascii_data_io::gz_mpi_write_charahead(), gz_mpi_ascii_data_io::gz_mpi_write_stack_over_domain(), gz_mpi_write_viewer_grp_item(), and m_constants::ieight.
Referenced by gz_mpi_viewer_mesh_file_io::gz_write_viewer_mesh_infos().
gz_mpi_write_viewer_grp_data()
subroutine gz_mpi_viewer_mesh_io::gz_mpi_write_viewer_grp_data (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint), intent(in) num_grp, character(len=kchara), dimension(num_grp), intent(in) grp_name, type(viewer_group_data), intent(in) view_grp)
Definition at line 103 of file gz_MPI_viewer_mesh_IO.f90.
References calypso_mpi_int::calypso_mpi_allreduce_int(), transfer_to_long_integers::cast_long(), gz_mpi_ascii_data_io::gz_mpi_write_charahead(), gz_mpi_ascii_data_io::gz_mpi_write_stack_over_domain(), gz_mpi_write_viewer_grp_item(), and m_constants::ieight.
Referenced by gz_mpi_viewer_mesh_file_io::gz_write_viewer_mesh_infos().
gz_mpi_write_viewer_grp_item()
subroutine gz_mpi_viewer_mesh_io::gz_mpi_write_viewer_grp_item (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) ncolumn, integer(kind=kint), intent(in) num, integer(kind=kint), dimension(num), intent(in) int_dat)
Definition at line 165 of file gz_MPI_viewer_mesh_IO.f90.
References t_buffer_4_gzip::dealloc_zip_buffer(), zlib_cvt_ascii_comm_tbl::defleate_comm_table(), gz_mpi_ascii_data_io::gz_mpi_write_stack_over_domain(), and gz_mpi_domain_data_io::zbuf.
Referenced by gz_mpi_write_domain_grp_data(), and gz_mpi_write_viewer_grp_data().
gz_mpi_write_viewer_position()
subroutine gz_mpi_viewer_mesh_io::gz_mpi_write_viewer_position (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint_gl), intent(in) nnod64, integer(kind=kint), intent(in) numdir, integer(kind=kint_gl), dimension(nnod64), intent(in) id_global, real(kind=kreal), dimension(nnod64, numdir), intent(in) xx)
Definition at line 45 of file gz_MPI_viewer_mesh_IO.f90.
References t_buffer_4_gzip::dealloc_zip_buffer(), zlib_convert_ascii_vector::defleate_node_position(), gz_mpi_ascii_data_io::gz_mpi_write_stack_over_domain(), and gz_mpi_domain_data_io::zbuf.
Referenced by gz_mpi_viewer_mesh_file_io::gz_write_viewer_mesh_infos().
Variable Documentation
zbuf
type(buffer_4_gzip) gz_mpi_viewer_mesh_io::zbuf
Definition at line 37 of file gz_MPI_viewer_mesh_IO.f90.