CALYPSO: /home/takumi kera/calypso/src/programs/TESTS/FFT_test/test_single_FFTW3.f90 File Reference
test_single_FFTW3.f90 File Reference
Functions/Subroutines
program test_single_fftw3
Function/Subroutine Documentation
test_single_fftw3()
program test_single_fftw3
Definition at line 2 of file test_single_FFTW3.f90.
References t_fft_test_data::dealloc_fft_test_data(), t_fftw_wrapper::fftw_backward_type(), t_fftw_wrapper::fftw_forward_type(), m_machine_parameter::iflag_debug, t_fft_test_data::init_fft_test_data(), t_fftw_wrapper::init_fftw_type(), m_machine_parameter::np_smp, and t_fft_test_data::write_fft_test_data().