CALYPSO: t_ctl_data_induct_norm Module Reference
t_ctl_data_induct_norm Module Reference
Data Types
type induction_equation_control
Structure for coefficients of magnetic induction equation.
Functions/Subroutines
subroutine read_induction_ctl (id_control, hd_block, induct_ctl, c_buf)
subroutine bcast_induction_ctl (induct_ctl)
subroutine dealloc_induction_ctl (induct_ctl)
Variables
character(len=kchara), private hd_n_magne = 'coef_4_magnetic_ctl'
character(len=kchara), private hd_n_mag_p = 'coef_4_mag_p_ctl'
character(len=kchara), private hd_n_m_diff = 'coef_4_m_diffuse_ctl'
character(len=kchara), private hd_n_induct = 'coef_4_induction_ctl'
Function/Subroutine Documentation
bcast_induction_ctl()
subroutine t_ctl_data_induct_norm::bcast_induction_ctl (type(induction_equation_control), intent(inout) induct_ctl)
Definition at line 123 of file t_ctl_data_induct_norm.f90.
References bcast_control_arrays::bcast_ctl_array_cr(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by t_ctl_data_mhd_normalize::bcast_coef_term_ctl().
dealloc_induction_ctl()
subroutine t_ctl_data_induct_norm::dealloc_induction_ctl (type(induction_equation_control), intent(inout) induct_ctl)
Definition at line 142 of file t_ctl_data_induct_norm.f90.
References t_control_array_charareal::dealloc_control_array_c_r().
Referenced by t_ctl_data_mhd_normalize::dealloc_coef_term_ctl().
read_induction_ctl()
subroutine t_ctl_data_induct_norm::read_induction_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(induction_equation_control), intent(inout) induct_ctl, type(buffer_for_control), intent(inout) c_buf)
Definition at line 89 of file t_ctl_data_induct_norm.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_n_induct, hd_n_m_diff, hd_n_mag_p, hd_n_magne, t_read_control_elements::load_one_line_from_control(), and t_control_array_charareal::read_control_array_c_r().
Referenced by t_ctl_data_mhd_normalize::read_coef_term_ctl().
Variable Documentation
hd_n_induct
character(len=kchara), private t_ctl_data_induct_norm::hd_n_induct = 'coef_4_induction_ctl' private
Definition at line 78 of file t_ctl_data_induct_norm.f90.
Referenced by read_induction_ctl().
hd_n_m_diff
character(len=kchara), private t_ctl_data_induct_norm::hd_n_m_diff = 'coef_4_m_diffuse_ctl' private
Definition at line 77 of file t_ctl_data_induct_norm.f90.
Referenced by read_induction_ctl().
hd_n_mag_p
character(len=kchara), private t_ctl_data_induct_norm::hd_n_mag_p = 'coef_4_mag_p_ctl' private
Definition at line 76 of file t_ctl_data_induct_norm.f90.
Referenced by read_induction_ctl().
hd_n_magne
character(len=kchara), private t_ctl_data_induct_norm::hd_n_magne = 'coef_4_magnetic_ctl' private
Definition at line 75 of file t_ctl_data_induct_norm.f90.
Referenced by read_induction_ctl().