CALYPSO: mpi_binary_head_io Module Reference
mpi_binary_head_io Module Reference
Output merged binary field file using MPI-IO.
Functions/Subroutines
subroutine open_write_mpi_file_b (file_name, IO_param)
subroutine open_read_mpi_file_b (file_name, num_pe, id_rank, IO_param)
subroutine mpi_write_process_id_b (IO_param)
subroutine mpi_write_one_inthead_b (IO_param, int_dat)
subroutine mpi_write_one_realhead_b (IO_param, real_dat)
subroutine mpi_write_mul_inthead_b (IO_param, num, int_dat)
subroutine mpi_write_i8stack_head_b (IO_param, num, i8stack)
subroutine mpi_write_mul_int8head_b (IO_param, num, int8_dat)
subroutine mpi_write_mul_charahead_b (IO_param, num, chara_dat)
subroutine mpi_write_mul_realhead_b (IO_param, num, real_dat)
subroutine mpi_read_process_id_b (IO_param)
subroutine mpi_read_one_inthead_b (IO_param, int_dat)
subroutine mpi_read_one_realhead_b (IO_param, real_dat)
subroutine mpi_read_mul_inthead_b (IO_param, num, int_dat)
subroutine mpi_read_i8stack_head_b (IO_param, num, i8stack)
subroutine mpi_read_mul_int8head_b (IO_param, num, int8_dat)
subroutine mpi_read_mul_charahead_b (IO_param, num, chara_dat)
subroutine mpi_read_mul_realhead_b (IO_param, num, real_dat)
Detailed Description
Output merged binary field file using MPI-IO.
      subroutine open_write_mpi_file_b(file_name, IO_param)
      subroutine open_read_mpi_file_b                                 &
     &         (file_name, num_pe, id_rank, IO_param)
      subroutine mpi_write_process_id_b(IO_param)
      subroutine mpi_write_one_inthead_b(IO_param, int_dat)
      subroutine mpi_write_one_realhead_b(IO_param, real_dat)
      subroutine mpi_write_one_integer_b(IO_param, int_dat)
      subroutine mpi_write_mul_inthead_b(IO_param, num, int_dat)
        Substitution of gz_write_mul_integer_b
      subroutine mpi_write_i8stack_head_b(IO_param, num, i8stack)
      subroutine mpi_write_mul_int8head_b(IO_param, num, int8_dat)
        Substitution of gz_write_mul_int8_b
      subroutine mpi_write_mul_charahead_b(IO_param, num, chara_dat)
        Substitution of gz_write_mul_character_b
      subroutine mpi_write_mul_realhead_b(IO_param, num, real_dat)
      subroutine mpi_read_process_id_b(IO_param)
      subroutine mpi_read_one_inthead_b(IO_param, int_dat)
      subroutine mpi_read_one_realhead_b(IO_param, real_dat)
      subroutine mpi_read_mul_inthead_b(IO_param, num, int_dat)
        Substitution of gz_read_mul_integer_b
      subroutine mpi_read_i8stack_head_b(IO_param, num, i8stack)
      subroutine mpi_read_mul_int8head_b(IO_param, num, int8_dat)
        Substitution of gz_read_mul_int8_b
      subroutine mpi_read_mul_charahead_b(IO_param, num, chara_dat)
        Substitution of gz_read_mul_character_b
      subroutine mpi_read_mul_realhead_b(IO_param, num, real_dat)
Function/Subroutine Documentation
mpi_read_i8stack_head_b()
subroutine mpi_binary_head_io::mpi_read_i8stack_head_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint_gl), intent(in) num, integer(kind = kint_gl), dimension(0:num), intent(inout) i8stack)
Definition at line 312 of file MPI_binary_head_IO.f90.
References mpi_read_mul_int8head_b().
Referenced by mpi_binary_data_io::mpi_read_1d_vector_b(), mpi_binary_data_io::mpi_read_int8_vector_b(), and field_block_mpi_io_b::read_field_header_mpi_b().
mpi_read_mul_charahead_b()
subroutine mpi_binary_head_io::mpi_read_mul_charahead_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) num, character(len=kchara), dimension(num), intent(inout) chara_dat)
Definition at line 353 of file MPI_binary_head_IO.f90.
References calypso_mpi_char::calypso_mpi_bcast_character(), transfer_to_long_integers::cast_long(), m_precision::kchara, m_calypso_mpi_io::mpi_read_mul_chara_b(), and calypso_mpi::my_rank.
Referenced by mpi_groups_io_b::mpi_read_group_data_b(), mpi_groups_io_b::mpi_read_surf_grp_data_b(), field_file_mpi_io_b::read_alloc_stp_fld_file_mpi_b(), field_file_mpi_io_b::read_alloc_stp_fld_head_mpi_b(), ucd_field_mpi_io_b::read_alloc_ucd_fld_file_mpi_b(), field_file_mpi_io_b::read_step_field_file_mpi_b(), and ucd_field_mpi_io_b::read_ucd_field_file_mpi_b().
mpi_read_mul_int8head_b()
subroutine mpi_binary_head_io::mpi_read_mul_int8head_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint_gl), intent(in) num, integer(kind = kint_gl), dimension(num), intent(inout) int8_dat)
Definition at line 327 of file MPI_binary_head_IO.f90.
References calypso_mpi_int8::calypso_mpi_bcast_int8(), m_precision::kint_gl, m_calypso_mpi_io::mpi_read_int8_b(), and calypso_mpi::my_rank.
Referenced by mpi_read_i8stack_head_b(), and mpi_read_mul_inthead_b().
mpi_read_mul_inthead_b()
subroutine mpi_binary_head_io::mpi_read_mul_inthead_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint_gl), intent(in) num, integer(kind = kint), dimension(num), intent(inout) int_dat)
Definition at line 291 of file MPI_binary_head_IO.f90.
References transfer_to_long_integers::alloc_1d_i8array(), transfer_to_long_integers::dup_to_short_array(), and mpi_read_mul_int8head_b().
Referenced by mpi_spherical_model_io_b::mpi_read_gl_reso_sph_b(), mpi_read_one_inthead_b(), mpi_read_process_id_b(), field_file_mpi_io_b::read_alloc_stp_fld_file_mpi_b(), field_file_mpi_io_b::read_alloc_stp_fld_head_mpi_b(), ucd_field_mpi_io_b::read_alloc_ucd_fld_file_mpi_b(), field_file_mpi_io_b::read_step_field_file_mpi_b(), and ucd_field_mpi_io_b::read_ucd_field_file_mpi_b().
mpi_read_mul_realhead_b()
subroutine mpi_binary_head_io::mpi_read_mul_realhead_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint_gl), intent(in) num, real(kind = kreal), dimension(num), intent(inout) real_dat)
Definition at line 382 of file MPI_binary_head_IO.f90.
References calypso_mpi_real::calypso_mpi_bcast_real(), m_precision::kreal, m_calypso_mpi_io::mpi_read_real_b(), and calypso_mpi::my_rank.
Referenced by mpi_read_one_realhead_b().
mpi_read_one_inthead_b()
subroutine mpi_binary_head_io::mpi_read_one_inthead_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint), intent(inout) int_dat)
Definition at line 258 of file MPI_binary_head_IO.f90.
References mpi_read_mul_inthead_b().
Referenced by mpi_spherical_model_io_b::mpi_read_gl_reso_sph_b(), mpi_groups_io_b::mpi_read_group_data_b(), mpi_groups_io_b::mpi_read_surf_grp_data_b(), field_file_mpi_io_b::read_alloc_stp_fld_file_mpi_b(), field_file_mpi_io_b::read_alloc_stp_fld_head_mpi_b(), ucd_field_mpi_io_b::read_alloc_ucd_fld_file_mpi_b(), field_block_mpi_io_b::read_field_header_mpi_b(), field_file_mpi_io_b::read_step_field_file_mpi_b(), and ucd_field_mpi_io_b::read_ucd_field_file_mpi_b().
mpi_read_one_realhead_b()
subroutine mpi_binary_head_io::mpi_read_one_realhead_b (type(calypso_mpi_io_params), intent(inout) IO_param, real(kind = kreal), intent(inout) real_dat)
Definition at line 274 of file MPI_binary_head_IO.f90.
References mpi_read_mul_realhead_b().
Referenced by field_block_mpi_io_b::read_field_header_mpi_b().
mpi_read_process_id_b()
subroutine mpi_binary_head_io::mpi_read_process_id_b (type(calypso_mpi_io_params), intent(inout) IO_param)
Definition at line 239 of file MPI_binary_head_IO.f90.
References calypso_mpi::calypso_mpi_abort(), m_error_ids::ierr_file, and mpi_read_mul_inthead_b().
Referenced by mpi_domain_data_io_b::mpi_read_domain_info_b(), and field_block_mpi_io_b::read_field_header_mpi_b().
mpi_write_i8stack_head_b()
subroutine mpi_binary_head_io::mpi_write_i8stack_head_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint_gl), intent(in) num, integer(kind = kint_gl), dimension(0:num), intent(in) i8stack)
Definition at line 158 of file MPI_binary_head_IO.f90.
References mpi_write_mul_int8head_b().
Referenced by mpi_binary_data_io::mpi_write_1d_vector_b(), mpi_binary_data_io::mpi_write_int8_vector_b(), and field_block_mpi_io_b::write_field_data_mpi_b().
mpi_write_mul_charahead_b()
subroutine mpi_binary_head_io::mpi_write_mul_charahead_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint), intent(in) num, character(len=kchara), dimension(num), intent(in) chara_dat)
Definition at line 193 of file MPI_binary_head_IO.f90.
References m_precision::kchara, m_calypso_mpi_io::mpi_write_mul_chara_b(), and calypso_mpi::my_rank.
Referenced by mpi_groups_io_b::mpi_write_grp_data_b(), mpi_groups_io_b::mpi_write_surf_grp_data_b(), field_block_mpi_io_b::write_field_data_mpi_b(), and ucd_file_mpi_io::write_ucd_data_mpi_b().
mpi_write_mul_int8head_b()
subroutine mpi_binary_head_io::mpi_write_mul_int8head_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint_gl), intent(in) num, integer(kind = kint_gl), dimension(num), intent(in) int8_dat)
Definition at line 172 of file MPI_binary_head_IO.f90.
References m_precision::kint_gl, m_calypso_mpi_io::mpi_write_int8_b(), and calypso_mpi::my_rank.
Referenced by mpi_write_i8stack_head_b(), and mpi_write_mul_inthead_b().
mpi_write_mul_inthead_b()
subroutine mpi_binary_head_io::mpi_write_mul_inthead_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint), intent(in) num, integer(kind = kint), dimension(num), intent(in) int_dat)
Definition at line 138 of file MPI_binary_head_IO.f90.
References transfer_to_long_integers::cast_long(), transfer_to_long_integers::dealloc_1d_i8array(), transfer_to_long_integers::dup_from_short_array(), and mpi_write_mul_int8head_b().
Referenced by mpi_spherical_model_io_b::mpi_write_gl_reso_sph_b(), mpi_write_one_inthead_b(), mpi_write_process_id_b(), field_block_mpi_io_b::write_field_data_mpi_b(), and ucd_file_mpi_io::write_ucd_data_mpi_b().
mpi_write_mul_realhead_b()
subroutine mpi_binary_head_io::mpi_write_mul_realhead_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint_gl), intent(in) num, real(kind = kreal), dimension(num), intent(in) real_dat)
Definition at line 217 of file MPI_binary_head_IO.f90.
References m_precision::kreal, m_calypso_mpi_io::mpi_write_real_b(), and calypso_mpi::my_rank.
Referenced by mpi_write_one_realhead_b().
mpi_write_one_inthead_b()
subroutine mpi_binary_head_io::mpi_write_one_inthead_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint), intent(in) int_dat)
Definition at line 106 of file MPI_binary_head_IO.f90.
References m_constants::ione, and mpi_write_mul_inthead_b().
Referenced by mpi_spherical_model_io_b::mpi_write_gl_reso_sph_b(), mpi_groups_io_b::mpi_write_grp_data_b(), mpi_groups_io_b::mpi_write_surf_grp_data_b(), field_block_mpi_io_b::write_field_data_mpi_b(), field_block_mpi_io_b::write_field_time_mpi_b(), ucd_file_mpi_io::write_ucd_data_mpi_b(), and ucd_file_mpi_io::write_ucd_mesh_data_mpi_b().
mpi_write_one_realhead_b()
subroutine mpi_binary_head_io::mpi_write_one_realhead_b (type(calypso_mpi_io_params), intent(inout) IO_param, real(kind = kreal), intent(in) real_dat)
Definition at line 121 of file MPI_binary_head_IO.f90.
References mpi_write_mul_realhead_b().
Referenced by field_block_mpi_io_b::write_field_time_mpi_b().
mpi_write_process_id_b()
subroutine mpi_binary_head_io::mpi_write_process_id_b (type(calypso_mpi_io_params), intent(inout) IO_param)
Definition at line 92 of file MPI_binary_head_IO.f90.
References m_constants::ione, and mpi_write_mul_inthead_b().
Referenced by mpi_domain_data_io_b::mpi_write_domain_info_b(), field_block_mpi_io_b::write_field_time_mpi_b(), and ucd_file_mpi_io::write_ucd_mesh_data_mpi_b().
open_read_mpi_file_b()
subroutine mpi_binary_head_io::open_read_mpi_file_b (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, type(calypso_mpi_io_params), intent(inout) IO_param)
Definition at line 74 of file MPI_binary_head_IO.f90.
References m_calypso_mpi_io::mpi_read_set_endian_flag(), and mpi_ascii_data_io::open_read_mpi_file().
Referenced by field_file_mpi_io_b::read_alloc_stp_fld_file_mpi_b(), field_file_mpi_io_b::read_alloc_stp_fld_head_mpi_b(), ucd_field_mpi_io_b::read_alloc_ucd_fld_file_mpi_b(), field_file_mpi_io_b::read_step_field_file_mpi_b(), and ucd_field_mpi_io_b::read_ucd_field_file_mpi_b().
open_write_mpi_file_b()
subroutine mpi_binary_head_io::open_write_mpi_file_b (character(len=kchara), intent(in) file_name, type(calypso_mpi_io_params), intent(inout) IO_param)
Definition at line 61 of file MPI_binary_head_IO.f90.
References m_calypso_mpi_io::mpi_write_endian_flag(), and mpi_ascii_data_io::open_write_mpi_file().
Referenced by field_file_mpi_io_b::write_step_field_file_mpi_b(), ucd_field_mpi_io_b::write_ucd_field_file_mpi_b(), write_udt_file_io_b::write_ucd_file_mpi_b(), write_udt_file_io_b::write_ucd_grid_mpi_b(), and write_udt_file_io_b::write_ucd_phys_mpi_b().