CALYPSO: cvt_nodal_and_sph_field Module Reference
cvt_nodal_and_sph_field Module Reference
Functions/Subroutines
subroutine cvt_nod_vec_to_sph_vec (numnod, np_smp, inod_smp_stack, xx, radius, s_cylinder, a_radius, a_s_cylinder, i_field, ntot_phys, d_nod, i_rtp, nnod_rtp, ntot_rtp, d_rtp, d_tmp)
subroutine cvt_sph_vec_to_nod_vec (numnod, internal_node, np_smp, inod_smp_stack, colatitude, longitude, i_rtp, nnod_rtp, ntot_rtp, d_rtp, i_field, ntot_phys, d_nod, d_tmp)
subroutine cvt_nod_tsr_to_sph_tsr (numnod, np_smp, inod_smp_stack, xx, radius, s_cylinder, a_radius, a_s_cylinder, i_field, ntot_phys, d_nod, i_rtp, nnod_rtp, ntot_rtp, d_rtp, d_tmp)
subroutine cvt_sph_tsr_to_nod_tsr (numnod, internal_node, np_smp, inod_smp_stack, xx, radius, s_cylinder, a_radius, a_s_cylinder, i_rtp, nnod_rtp, ntot_rtp, d_rtp, i_field, ntot_phys, d_nod, d_tmp)
Function/Subroutine Documentation
cvt_nod_tsr_to_sph_tsr()
subroutine cvt_nodal_and_sph_field::cvt_nod_tsr_to_sph_tsr (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) np_smp, integer(kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind = kreal), dimension(numnod, 3), intent(in) xx, real(kind = kreal), dimension(numnod), intent(in) radius, real(kind = kreal), dimension(numnod), intent(in) s_cylinder, real(kind = kreal), dimension(numnod), intent(in) a_radius, real(kind = kreal), dimension(numnod), intent(in) a_s_cylinder, integer(kind = kint), intent(in) i_field, integer(kind = kint), intent(in) ntot_phys, real(kind = kreal), dimension(numnod, ntot_phys), intent(in) d_nod, integer(kind = kint), intent(in) i_rtp, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) ntot_rtp, real(kind = kreal), dimension(nnod_rtp, ntot_rtp), intent(inout) d_rtp, real(kind = kreal), dimension(numnod,6), intent(inout) d_tmp)
Definition at line 151 of file cvt_nodal_and_sph_field.f90.
References cvt_xyz_tensor_2_sph_smp::cal_sph_tensor_smp(), copy_between_two_fields::copy_tensor_2_tensor_fld(), m_constants::ione, and m_constants::isix.
cvt_nod_vec_to_sph_vec()
subroutine cvt_nodal_and_sph_field::cvt_nod_vec_to_sph_vec (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) np_smp, integer(kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind = kreal), dimension(numnod, 3), intent(in) xx, real(kind = kreal), dimension(numnod), intent(in) radius, real(kind = kreal), dimension(numnod), intent(in) s_cylinder, real(kind = kreal), dimension(numnod), intent(in) a_radius, real(kind = kreal), dimension(numnod), intent(in) a_s_cylinder, integer(kind = kint), intent(in) i_field, integer(kind = kint), intent(in) ntot_phys, real(kind = kreal), dimension(numnod, ntot_phys), intent(in) d_nod, integer(kind = kint), intent(in) i_rtp, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) ntot_rtp, real(kind = kreal), dimension(nnod_rtp, ntot_rtp), intent(inout) d_rtp, real(kind = kreal), dimension(numnod,6), intent(inout) d_tmp)
Definition at line 70 of file cvt_nodal_and_sph_field.f90.
References copy_between_two_fields::copy_vector_2_vector_fld(), cvt_xyz_vector_2_sph_smp::cvt_vector_2_sph_smp(), m_constants::ione, and m_constants::isix.
cvt_sph_tsr_to_nod_tsr()
subroutine cvt_nodal_and_sph_field::cvt_sph_tsr_to_nod_tsr (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) internal_node, integer(kind = kint), intent(in) np_smp, integer(kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind = kreal), dimension(numnod, 3), intent(in) xx, real(kind = kreal), dimension(numnod), intent(in) radius, real(kind = kreal), dimension(numnod), intent(in) s_cylinder, real(kind = kreal), dimension(numnod), intent(in) a_radius, real(kind = kreal), dimension(numnod), intent(in) a_s_cylinder, integer(kind = kint), intent(in) i_rtp, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) ntot_rtp, real(kind = kreal), dimension(nnod_rtp, ntot_rtp), intent(in) d_rtp, integer(kind = kint), intent(in) i_field, integer(kind = kint), intent(in) ntot_phys, real(kind = kreal), dimension(numnod, ntot_phys), intent(inout) d_nod, real(kind = kreal), dimension(numnod,6), intent(inout) d_tmp)
Definition at line 191 of file cvt_nodal_and_sph_field.f90.
References cvt_sph_tensor_2_xyz_smp::cal_xyz_tensor_by_sph_smp(), copy_between_two_fields::copy_tensor_2_tensor_fld(), copy_between_two_fields::fill_rest_tensor_field(), m_constants::ione, and m_constants::isix.
cvt_sph_vec_to_nod_vec()
subroutine cvt_nodal_and_sph_field::cvt_sph_vec_to_nod_vec (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) internal_node, integer(kind = kint), intent(in) np_smp, integer(kind = kint), dimension(0:np_smp), intent(in) inod_smp_stack, real(kind = kreal), dimension(numnod), intent(in) colatitude, real(kind = kreal), dimension(numnod), intent(in) longitude, integer(kind = kint), intent(in) i_rtp, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) ntot_rtp, real(kind = kreal), dimension(nnod_rtp, ntot_rtp), intent(in) d_rtp, integer(kind = kint), intent(in) i_field, integer(kind = kint), intent(in) ntot_phys, real(kind = kreal), dimension(numnod, ntot_phys), intent(inout) d_nod, real(kind = kreal), dimension(numnod,6), intent(inout) d_tmp)
Definition at line 111 of file cvt_nodal_and_sph_field.f90.
References copy_between_two_fields::copy_vector_2_vector_fld(), cvt_sph_vector_2_xyz_smp::cvt_sph_vect_2_xyz_smp(), copy_between_two_fields::fill_rest_vector_field(), m_constants::ione, and m_constants::isix.