CALYPSO: gz_field_data_mpi_io Module Reference
gz_field_data_mpi_io Module Reference
Output merged VTK file usgin MPI-IO.
Functions/Subroutines
subroutine gz_write_fld_vecotr_mpi (id_fld, ioff_gl, nnod, ndir, vector)
subroutine gz_write_fld_header_mpi (id_fld, ioff_gl, header_txt)
subroutine gz_read_fld_charhead_mpi (id_fld, ioff_gl, ilength, chara_dat)
subroutine gz_read_fld_1word_mpi (id_fld, ioff_gl, field_name)
subroutine gz_read_each_field_mpi (id_fld, num_pe, id_rank, ioff_gl, nnod, ndir, vector)
subroutine gz_skip_each_field_mpi (id_fld, num_pe, ioff_gl)
Detailed Description
Output merged VTK file usgin MPI-IO.
      subroutine gz_write_fld_vecotr_mpi                              &
     &         (id_fld, ioff_gl, nnod, ndir, vector)
      subroutine gz_write_fld_header_mpi(id_fld, ioff_gl, header_txt)
      subroutine gz_read_fld_charhead_mpi(id_fld,                     &
     &         ioff_gl, ilength, chara_dat)
      subroutine gz_read_fld_1word_mpi(id_fld, ioff_gl, field_name)
      subroutine gz_read_each_field_mpi(id_fld, num_pe, id_rank,      &
     &          ioff_gl, nnod, ndir, vector)
      subroutine gz_skip_each_field_mpi(id_fld, num_pe, ioff_gl)
Function/Subroutine Documentation
gz_read_each_field_mpi()
subroutine gz_field_data_mpi_io::gz_read_each_field_mpi (integer, intent(in) id_fld, integer, intent(in) num_pe, integer, intent(in) id_rank, integer(kind = kint_gl), intent(inout) ioff_gl, integer(kind = kint_gl), intent(in) nnod, integer(kind = kint), intent(in) ndir, real(kind = kreal), dimension(nnod,ndir), intent(inout) vector)
Definition at line 181 of file gz_field_data_MPI_IO.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), calypso_mpi_int8::calypso_mpi_bcast_int8(), m_calypso_mpi_io::calypso_mpi_seek_read_gz(), transfer_to_long_integers::cast_long(), gz_read_fld_charhead_mpi(), zlib_convert_ascii_vector::infleate_vector_txt(), m_constants::izero, calypso_mpi::my_rank, and field_data_io::read_buffer_istack_nod_buffer().
Referenced by gz_field_block_mpi_io::read_field_data_gz_mpi().
gz_read_fld_1word_mpi()
subroutine gz_field_data_mpi_io::gz_read_fld_1word_mpi (integer, intent(in) id_fld, integer(kind = kint_gl), intent(inout) ioff_gl, character(len=kchara), intent(inout) field_name)
Definition at line 147 of file gz_field_data_MPI_IO.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), calypso_mpi_int8::calypso_mpi_bcast_one_int8(), m_calypso_mpi_io::calypso_mpi_seek_read_gz(), zlib_convert_text::infleate_1word(), m_precision::kchara, calypso_mpi::my_rank, and field_data_mpi_io::sync_field_name_mpi().
Referenced by gz_mpi_groups_io::gz_mpi_read_group_data(), gz_mpi_groups_io::gz_mpi_read_surf_grp_data(), gz_field_block_mpi_io::read_field_data_gz_mpi(), and gz_field_block_mpi_io::read_field_names_gz_mpi().
gz_read_fld_charhead_mpi()
subroutine gz_field_data_mpi_io::gz_read_fld_charhead_mpi (integer, intent(in) id_fld, integer(kind = kint_gl), intent(inout) ioff_gl, integer, intent(in) ilength, character(len=ilength), intent(inout) chara_dat)
Definition at line 115 of file gz_field_data_MPI_IO.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), calypso_mpi_int8::calypso_mpi_bcast_one_int8(), m_calypso_mpi_io::calypso_mpi_seek_read_gz(), zlib_convert_text::infleate_characters(), and calypso_mpi::my_rank.
Referenced by gz_read_each_field_mpi(), gz_skip_each_field_mpi(), gz_field_block_mpi_io::read_field_header_gz_mpi(), gz_field_block_mpi_io::read_field_num_gz_mpi(), and gz_field_block_mpi_io::read_field_step_gz_mpi().
gz_skip_each_field_mpi()
subroutine gz_field_data_mpi_io::gz_skip_each_field_mpi (integer, intent(in) id_fld, integer, intent(in) num_pe, integer(kind = kint_gl), intent(inout) ioff_gl)
Definition at line 233 of file gz_field_data_MPI_IO.f90.
References calypso_mpi_int8::calypso_mpi_bcast_int8(), transfer_to_long_integers::cast_long(), gz_read_fld_charhead_mpi(), calypso_mpi::my_rank, and field_data_io::read_buffer_istack_nod_buffer().
Referenced by gz_field_block_mpi_io::read_field_names_gz_mpi().
gz_write_fld_header_mpi()
subroutine gz_field_data_mpi_io::gz_write_fld_header_mpi (integer, intent(in) id_fld, integer(kind = kint_gl), intent(inout) ioff_gl, character(len=*), intent(in) header_txt)
Definition at line 86 of file gz_field_data_MPI_IO.f90.
References calypso_mpi_int8::calypso_mpi_bcast_one_int8(), m_calypso_mpi_io::calypso_mpi_seek_write_gz(), t_buffer_4_gzip::dealloc_zip_buffer(), zlib_convert_text::defleate_characters(), and calypso_mpi::my_rank.
Referenced by gz_write_fld_vecotr_mpi(), gz_field_block_mpi_io::write_field_data_gz_mpi(), and gz_field_block_mpi_io::write_field_head_gz_mpi().
gz_write_fld_vecotr_mpi()
subroutine gz_field_data_mpi_io::gz_write_fld_vecotr_mpi (integer, intent(in) id_fld, integer(kind = kint_gl), intent(inout) ioff_gl, integer(kind = kint_gl), intent(in) nnod, integer(kind = kint), intent(in) ndir, real(kind = kreal), dimension(nnod,ndir), intent(in) vector)
Definition at line 39 of file gz_field_data_MPI_IO.f90.
References field_data_io::buffer_istack_nod_buffer(), calypso_mpi_int8::calypso_mpi_allgather_one_int8(), m_calypso_mpi_io::calypso_mpi_seek_write_gz(), t_buffer_4_gzip::dealloc_zip_buffer(), zlib_convert_ascii_vector::defleate_vector_txt(), gz_write_fld_header_mpi(), m_constants::izero, and calypso_mpi::my_rank.
Referenced by gz_field_block_mpi_io::write_field_data_gz_mpi().