CALYPSO: gz_mesh_data_io_b Module Reference
gz_mesh_data_io_b Module Reference
Routines for gzipped binary mesh data IO.
Functions/Subroutines
subroutine gz_write_geometry_data_b (id_rank, mesh_IO, zbuf)
subroutine gz_write_mesh_groups_b (mesh_group_IO, zbuf)
subroutine gz_read_num_node_b (id_rank, zbuf, mesh_IO)
subroutine gz_read_num_node_ele_b (id_rank, zbuf, mesh_IO)
subroutine gz_read_geometry_data_b (id_rank, zbuf, mesh_IO)
subroutine gz_read_mesh_groups_b (zbuf, mesh_group_IO)
Detailed Description
Routines for gzipped binary mesh data IO.
      subroutine gz_write_geometry_data_b(id_rank, mesh_IO, zbuf)
      subroutine gz_write_mesh_groups_b(mesh_group_IO, zbuf)
        type(mesh_geometry), intent(in) :: mesh_IO
        type(mesh_groups), intent(in) ::   mesh_group_IO
        type(buffer_4_gzip), intent(inout) :: zbuf
      subroutine gz_read_num_node_b(id_rank, zbuf, mesh_IO)
      subroutine gz_read_num_node_ele_b(id_rank, zbuf, mesh_IO)
      subroutine gz_read_geometry_data_b(id_rank, zbuf, mesh_IO)
      subroutine gz_read_mesh_groups_b(zbuf, mesh_group_IO)
        type(buffer_4_gzip), intent(inout) :: zbuf
        type(mesh_geometry), intent(inout) :: mesh_IO
        type(mesh_groups), intent(inout) ::   mesh_group_IO
Function/Subroutine Documentation
gz_read_geometry_data_b()
subroutine gz_mesh_data_io_b::gz_read_geometry_data_b (integer, intent(in) id_rank, type(buffer_4_gzip), intent(inout) zbuf, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 142 of file gz_mesh_data_IO_b.f90.
References gz_element_connect_io_b::gz_read_element_info_b(), gz_domain_data_io_b::gz_read_export_data_b(), gz_domain_data_io_b::gz_read_import_data_b(), and gz_read_num_node_ele_b().
Referenced by gz_mesh_file_io_b::gz_read_mesh_file_b(), and gz_mesh_file_io_b::gz_read_mesh_geometry_b().
gz_read_mesh_groups_b()
subroutine gz_mesh_data_io_b::gz_read_mesh_groups_b (type(buffer_4_gzip), intent(inout) zbuf, type(mesh_groups), intent(inout) mesh_group_IO)
Definition at line 174 of file gz_mesh_data_IO_b.f90.
References gz_groups_io_b::gz_read_group_data_b(), and gz_groups_io_b::gz_read_surf_grp_data_b().
Referenced by gz_mesh_file_io_b::gz_read_mesh_file_b().
gz_read_num_node_b()
subroutine gz_mesh_data_io_b::gz_read_num_node_b (integer, intent(in) id_rank, type(buffer_4_gzip), intent(inout) zbuf, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 95 of file gz_mesh_data_IO_b.f90.
References gz_domain_data_io_b::gz_read_domain_info_b(), and gz_node_geometry_io_b::gz_read_number_of_node_b().
Referenced by gz_mesh_file_io_b::gz_read_node_size_b(), and gz_read_num_node_ele_b().
gz_read_num_node_ele_b()
subroutine gz_mesh_data_io_b::gz_read_num_node_ele_b (integer, intent(in) id_rank, type(buffer_4_gzip), intent(inout) zbuf, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 116 of file gz_mesh_data_IO_b.f90.
References gz_node_geometry_io_b::gz_read_geometry_info_b(), gz_read_num_node_b(), and gz_element_connect_io_b::gz_read_number_of_element_b().
Referenced by gz_read_geometry_data_b(), and gz_mesh_file_io_b::gz_read_geometry_size_b().
gz_write_geometry_data_b()
subroutine gz_mesh_data_io_b::gz_write_geometry_data_b (integer, intent(in) id_rank, type(mesh_geometry), intent(in) mesh_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 45 of file gz_mesh_data_IO_b.f90.
References gz_domain_data_io_b::gz_write_domain_info_b(), gz_element_connect_io_b::gz_write_element_info_b(), gz_domain_data_io_b::gz_write_export_data_b(), gz_node_geometry_io_b::gz_write_geometry_info_b(), and gz_domain_data_io_b::gz_write_import_data_b().
Referenced by gz_mesh_file_io_b::gz_write_mesh_file_b().
gz_write_mesh_groups_b()
subroutine gz_mesh_data_io_b::gz_write_mesh_groups_b (type(mesh_groups), intent(in) mesh_group_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 73 of file gz_mesh_data_IO_b.f90.
References gz_groups_io_b::gz_write_grp_data_b(), and gz_groups_io_b::gz_write_surf_grp_data_b().
Referenced by gz_mesh_file_io_b::gz_write_mesh_file_b().