CALYPSO: sph_analyzer_mhd Module Reference
sph_analyzer_mhd Module Reference
Evolution loop for spherical MHD.
Functions/Subroutines
subroutine sph_initialize_mhd (MHD_files, SPH_model, iphys, MHD_step, sph_fst_IO, SPH_MHD, SPH_WK)
subroutine sph_analyze_mhd (i_step, MHD_files, iflag_finish, SPH_model, MHD_step, sph_fst_IO, SPH_MHD, SPH_WK)
Detailed Description
Evolution loop for spherical MHD.
      subroutine SPH_initialize_MHD(MHD_files, SPH_model,             &
     &          iphys, MHD_step, sph_fst_IO, SPH_MHD)
        type(MHD_file_IO_params), intent(in) :: MHD_files
        type(phys_address), intent(in) :: iphys
        type(SPH_MHD_model_data), intent(inout) :: SPH_model
        type(MHD_step_param), intent(inout) :: MHD_step
        type(SPH_mesh_field_data), intent(inout) :: SPH_MHD
        type(work_SPH_MHD), intent(inout) :: SPH_WK
        type(field_IO), intent(inout) :: sph_fst_IO
      subroutine SPH_analyze_MHD(i_step, MHD_files, iflag_finish,     &
     &          SPH_model, MHD_step, sph_fst_IO, SPH_MHD, SPH_WK)
        type(MHD_file_IO_params), intent(in) :: MHD_files
        type(SPH_MHD_model_data), intent(inout) :: SPH_model
        type(MHD_step_param), intent(inout) :: MHD_step
        type(SPH_mesh_field_data), intent(inout) :: SPH_MHD
        type(work_SPH_MHD), intent(inout) :: SPH_WK
        type(field_IO), intent(inout) :: sph_fst_IO
Function/Subroutine Documentation
sph_analyze_mhd()
subroutine sph_analyzer_mhd::sph_analyze_mhd (integer(kind = kint), intent(in) i_step, type(mhd_file_io_params), intent(in) MHD_files, integer(kind = kint), intent(inout) iflag_finish, type(sph_mhd_model_data), intent(inout) SPH_model, type(mhd_step_param), intent(inout) MHD_step, type(field_io), intent(inout) sph_fst_IO, type(sph_mesh_field_data), intent(inout) SPH_MHD, type(work_sph_mhd), intent(inout) SPH_WK)
Definition at line 157 of file SPH_analyzer_MHD.f90.
References calypso_mpi_real::calypso_mpi_allreduce_one_real(), m_work_time::end_elapsed_time(), m_elapsed_labels_4_mhd::iflag_mhd_time, m_elapsed_labels_4_mhd::iflag_smhd_time, m_elapsed_labels_4_mhd::ist_elapsed_mhd, m_elapsed_labels_4_mhd::ist_elapsed_smhd, output_viz_file_control::lead_field_data_flag(), cal_nonlinear::nonlinear(), sph_mhd_rst_io_control::output_sph_restart_control(), cal_sol_sph_mhd_crank::s_cal_sol_sph_mhd_crank(), lead_fields_4_sph_mhd::s_lead_fields_4_sph_mhd(), cal_momentum_eq_explicit::sel_explicit_sph(), t_boundary_data_sph_mhd::set_mhd_evolved_boundaries(), m_work_time::start_elapsed_time(), adjust_reference_fields::sync_temp_by_per_temp_sph(), and adjust_reference_fields::trans_per_temp_to_temp_sph().
Referenced by analyzer_sph_mhd_w_psf::evolution_sph_mhd_w_psf().
sph_initialize_mhd()
subroutine sph_analyzer_mhd::sph_initialize_mhd (type(mhd_file_io_params), intent(in) MHD_files, type(sph_mhd_model_data), intent(inout) SPH_model, type(phys_address), intent(in) iphys, type(mhd_step_param), intent(inout) MHD_step, type(field_io), intent(inout) sph_fst_IO, type(sph_mesh_field_data), intent(inout) SPH_MHD, type(work_sph_mhd), intent(inout) SPH_WK)
Definition at line 53 of file SPH_analyzer_MHD.f90.
References const_radial_mat_4_sph::const_radial_mat_sph_mhd(), m_work_time::end_elapsed_time(), m_machine_parameter::iflag_debug, m_elapsed_labels_4_mhd::iflag_mhd_time, init_radial_infos_sph_mhd::init_r_infos_sph_mhd_evo(), init_sphrical_transform_mhd::init_sph_transform_mhd(), m_elapsed_labels_4_mhd::ist_elapsed_mhd, cal_nonlinear::nonlinear(), t_boundary_data_sph_mhd::set_mhd_evolved_boundaries(), cal_sol_sph_mhd_crank::set_sph_field_to_start(), check_dependency_for_mhd::set_sph_mhd_sprctr_data(), set_initial_sph_dynamo::sph_initial_data_control(), m_work_time::start_elapsed_time(), and adjust_reference_fields::sync_temp_by_per_temp_sph().
Referenced by analyzer_sph_mhd_w_psf::initialize_sph_mhd_w_psf().