CALYPSO: set_control_4_pickup_sph Module Reference
set_control_4_pickup_sph Module Reference
Functions/Subroutines
subroutine set_ctl_params_sph_spectr (smonitor_ctl, pwr)
subroutine set_ctl_params_layered_spectr (lp_ctl, pwr)
subroutine set_ctl_params_pick_sph (pspec_ctl, pick_list, picked_sph)
subroutine set_ctl_params_pick_gauss (g_pwr, gauss_list, gauss_coef)
subroutine set_ctl_params_no_heat_nu (Nusselt_file_prefix, rj_fld, Nu_type)
Function/Subroutine Documentation
set_ctl_params_layered_spectr()
subroutine set_control_4_pickup_sph::set_ctl_params_layered_spectr (type(layerd_spectr_control), intent(in) lp_ctl, type(sph_mean_squares), intent(inout) pwr)
Definition at line 119 of file set_control_4_pickup_sph.f90.
References t_rms_4_sph_spectr::alloc_num_spec_layer(), and skip_comment_f::no_flag().
Referenced by set_control_sph_mhd::set_control_sph_mhd_monitors().
set_ctl_params_no_heat_nu()
subroutine set_control_4_pickup_sph::set_ctl_params_no_heat_nu (type(read_character_item), intent(in) Nusselt_file_prefix, type(phys_data), intent(in) rj_fld, type(nusselt_number_data), intent(inout) Nu_type)
Definition at line 328 of file set_control_4_pickup_sph.f90.
References m_grad_field_labels::grad_temp, and m_base_field_labels::heat_source.
Referenced by set_control_sph_mhd::set_control_sph_mhd_monitors().
set_ctl_params_pick_gauss()
subroutine set_control_4_pickup_sph::set_ctl_params_pick_gauss (type(gauss_spectr_control), intent(in) g_pwr, type(pickup_mode_list), intent(inout) gauss_list, type(picked_spectrum_data), intent(inout) gauss_coef)
Definition at line 255 of file set_control_4_pickup_sph.f90.
References t_pickup_sph_spectr_data::alloc_num_pick_layer(), t_pickup_sph_spectr_data::alloc_pick_sph_l(), t_pickup_sph_spectr_data::alloc_pick_sph_m(), and t_pickup_sph_spectr_data::alloc_pick_sph_mode().
Referenced by set_control_sph_mhd::set_control_sph_mhd_monitors().
set_ctl_params_pick_sph()
subroutine set_control_4_pickup_sph::set_ctl_params_pick_sph (type(pick_spectr_control), intent(in) pspec_ctl, type(pickup_mode_list), intent(inout) pick_list, type(picked_spectrum_data), intent(inout) picked_sph)
Definition at line 166 of file set_control_4_pickup_sph.f90.
References t_pickup_sph_spectr_data::alloc_num_pick_layer(), t_pickup_sph_spectr_data::alloc_pick_sph_l(), t_pickup_sph_spectr_data::alloc_pick_sph_m(), and t_pickup_sph_spectr_data::alloc_pick_sph_mode().
Referenced by set_control_sph_mhd::set_control_sph_mhd_monitors().
set_ctl_params_sph_spectr()
subroutine set_control_4_pickup_sph::set_ctl_params_sph_spectr (type(sph_monitor_control), intent(in) smonitor_ctl, type(sph_mean_squares), intent(inout) pwr)
Definition at line 47 of file set_control_4_pickup_sph.f90.
References t_rms_4_sph_spectr::alloc_volume_spectr_data().
Referenced by set_control_sph_mhd::set_control_sph_mhd_monitors().