CALYPSO: cal_zonal_mean_sph_spectr Module Reference
cal_zonal_mean_sph_spectr Module Reference
Subroutines to choose spewcific modes of spectrum data.
Functions/Subroutines
subroutine zonal_mean_all_sph_spectr (sph_rj, rj_fld)
subroutine take_zonal_mean_rj_field (numdir, is_fld, sph_rj, rj_fld)
subroutine delete_zonal_mean_rj_field (numdir, is_fld, sph_rj, rj_fld)
subroutine pick_order_sph_spectr (num_order, ipick_order, numdir, is_fld, sph_rj, rj_fld)
subroutine delete_order_sph_spectr (num_order, ipick_order, numdir, is_fld, sph_rj, rj_fld)
subroutine pick_degree_sph_spectr (num_degree, ipick_degree, numdir, is_fld, sph_rj, rj_fld)
subroutine delete_degree_sph_spectr (num_degree, ipick_degree, numdir, is_fld, sph_rj, rj_fld)
subroutine, private pick_del_order_sph_spectr (iswitch, num_order, ipick_order, numdir, is_fld, sph_rj, n_point, ntot_phys_rj, d_rj)
subroutine, private pick_del_degree_sph_spectr (iswitch, num_degree, ipick_degree, numdir, is_fld, sph_rj, n_point, ntot_phys_rj, d_rj)
Variables
integer(kind=kint), parameter, private iflag_pick = izero
integer(kind=kint), parameter, private iflag_delete = ione
Detailed Description
Subroutines to choose spewcific modes of spectrum data.
      subroutine zonal_mean_all_sph_spectr(sph_rj, rj_fld)
        type(phys_data), intent(inout) :: rj_fld
      subroutine take_zonal_mean_rj_field                             &
     &         (numdir, is_fld, sph_rj, rj_fld)
      subroutine delete_zonal_mean_rj_field                           &
     &         (numdir, is_fld, sph_rj, rj_fld)
      subroutine pick_order_sph_spectr(num_order, ipick_order,        &
     &          numdir, is_fld, sph_rj, rj_fld)
      subroutine delete_order_sph_spectr(num_order, ipick_order,      &
     &          numdir, is_fld, sph_rj, rj_fld)
      subroutine pick_degree_sph_spectr(num_degree, ipick_degree,     &
     &          numdir, is_fld, sph_rj, rj_fld)
      subroutine delete_degree_sph_spectr(num_degree, ipick_degree,   &
     &          numdir, is_fld, sph_rj, rj_fld)
Parameters
numdir number of component of field
is_fld field data address
num_order number of spherical harmonics order to keep (or delete)
id_order(num_order) spherical harmonics order to keep (or delete)
num_degree number of spherical harmonics degree to keep (or delete)
ipick_degree(num_degree) spherical harmonics degree to keep (or delete)
Function/Subroutine Documentation
delete_degree_sph_spectr()
subroutine cal_zonal_mean_sph_spectr::delete_degree_sph_spectr (integer(kind = kint), intent(in) num_degree, integer(kind = kint), dimension(num_degree), intent(in) ipick_degree, integer(kind = kint), intent(in) numdir, integer(kind = kint), intent(in) is_fld, type(sph_rj_grid), intent(in) sph_rj, type(phys_data), intent(inout) rj_fld)
Definition at line 168 of file cal_zonal_mean_sph_spectr.f90.
References iflag_delete, and pick_del_degree_sph_spectr().
delete_order_sph_spectr()
subroutine cal_zonal_mean_sph_spectr::delete_order_sph_spectr (integer(kind = kint), intent(in) num_order, integer(kind = kint), dimension(num_order), intent(in) ipick_order, integer(kind = kint), intent(in) numdir, integer(kind = kint), intent(in) is_fld, type(sph_rj_grid), intent(in) sph_rj, type(phys_data), intent(inout) rj_fld)
Definition at line 129 of file cal_zonal_mean_sph_spectr.f90.
References iflag_delete, and pick_del_order_sph_spectr().
Referenced by delete_zonal_mean_rj_field().
delete_zonal_mean_rj_field()
subroutine cal_zonal_mean_sph_spectr::delete_zonal_mean_rj_field (integer(kind = kint), intent(in) numdir, integer(kind = kint), intent(in) is_fld, type(sph_rj_grid), intent(in) sph_rj, type(phys_data), intent(inout) rj_fld)
Definition at line 92 of file cal_zonal_mean_sph_spectr.f90.
References delete_order_sph_spectr(), and m_constants::ione.
pick_degree_sph_spectr()
subroutine cal_zonal_mean_sph_spectr::pick_degree_sph_spectr (integer(kind = kint), intent(in) num_degree, integer(kind = kint), dimension(num_degree), intent(in) ipick_degree, integer(kind = kint), intent(in) numdir, integer(kind = kint), intent(in) is_fld, type(sph_rj_grid), intent(in) sph_rj, type(phys_data), intent(inout) rj_fld)
Definition at line 149 of file cal_zonal_mean_sph_spectr.f90.
References iflag_pick, and pick_del_degree_sph_spectr().
pick_del_degree_sph_spectr()
subroutine, private cal_zonal_mean_sph_spectr::pick_del_degree_sph_spectr (integer(kind = kint), intent(in) iswitch, integer(kind = kint), intent(in) num_degree, integer(kind = kint), dimension(num_degree), intent(in) ipick_degree, integer(kind = kint), intent(in) numdir, integer(kind = kint), intent(in) is_fld, type(sph_rj_grid), intent(in) sph_rj, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj) private
Definition at line 230 of file cal_zonal_mean_sph_spectr.f90.
References m_constants::ione, m_constants::izero, and m_constants::zero.
Referenced by delete_degree_sph_spectr(), and pick_degree_sph_spectr().
pick_del_order_sph_spectr()
subroutine, private cal_zonal_mean_sph_spectr::pick_del_order_sph_spectr (integer(kind = kint), intent(in) iswitch, integer(kind = kint), intent(in) num_order, integer(kind = kint), dimension(num_order), intent(in) ipick_order, integer(kind = kint), intent(in) numdir, integer(kind = kint), intent(in) is_fld, type(sph_rj_grid), intent(in) sph_rj, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj) private
Definition at line 188 of file cal_zonal_mean_sph_spectr.f90.
References m_constants::ione, m_constants::izero, and m_constants::zero.
Referenced by delete_order_sph_spectr(), and pick_order_sph_spectr().
pick_order_sph_spectr()
subroutine cal_zonal_mean_sph_spectr::pick_order_sph_spectr (integer(kind = kint), intent(in) num_order, integer(kind = kint), dimension(num_order), intent(in) ipick_order, integer(kind = kint), intent(in) numdir, integer(kind = kint), intent(in) is_fld, type(sph_rj_grid), intent(in) sph_rj, type(phys_data), intent(inout) rj_fld)
Definition at line 110 of file cal_zonal_mean_sph_spectr.f90.
References iflag_pick, and pick_del_order_sph_spectr().
Referenced by take_zonal_mean_rj_field(), and zonal_mean_all_sph_spectr().
take_zonal_mean_rj_field()
subroutine cal_zonal_mean_sph_spectr::take_zonal_mean_rj_field (integer(kind = kint), intent(in) numdir, integer(kind = kint), intent(in) is_fld, type(sph_rj_grid), intent(in) sph_rj, type(phys_data), intent(inout) rj_fld)
Definition at line 75 of file cal_zonal_mean_sph_spectr.f90.
References m_constants::ione, and pick_order_sph_spectr().
zonal_mean_all_sph_spectr()
subroutine cal_zonal_mean_sph_spectr::zonal_mean_all_sph_spectr (type(sph_rj_grid), intent(in) sph_rj, type(phys_data), intent(inout) rj_fld)
Definition at line 60 of file cal_zonal_mean_sph_spectr.f90.
References m_constants::ione, and pick_order_sph_spectr().
Variable Documentation
iflag_delete
integer(kind = kint), parameter, private cal_zonal_mean_sph_spectr::iflag_delete = ione private
Definition at line 50 of file cal_zonal_mean_sph_spectr.f90.
Referenced by delete_degree_sph_spectr(), and delete_order_sph_spectr().
iflag_pick
integer(kind = kint), parameter, private cal_zonal_mean_sph_spectr::iflag_pick = izero private
Definition at line 49 of file cal_zonal_mean_sph_spectr.f90.
Referenced by pick_degree_sph_spectr(), and pick_order_sph_spectr().