CALYPSO: sph_modes_grids_file_io_b Module Reference
sph_modes_grids_file_io_b Module Reference
Binary spectr data IO routines.
Functions/Subroutines
subroutine read_geom_rtp_file_b (file_name, id_rank, sph_file, ierr)
subroutine read_spectr_modes_rj_file_b (file_name, id_rank, sph_file, ierr)
subroutine read_geom_rtm_file_b (file_name, id_rank, sph_file, ierr)
subroutine read_modes_rlm_file_b (file_name, id_rank, sph_file, ierr)
subroutine write_geom_rtp_file_b (file_name, id_rank, sph_file, ierr)
subroutine write_spectr_modes_rj_file_b (file_name, id_rank, sph_file, ierr)
subroutine write_geom_rtm_file_b (file_name, id_rank, sph_file, ierr)
subroutine write_modes_rlm_file_b (file_name, id_rank, sph_file, ierr)
Variables
integer(kind=kint), parameter, private id_read_sph = 21
integer(kind=kint), parameter, private id_write_sph = 22
type(binary_io_buffer), private bbuf_sph
Detailed Description
Binary spectr data IO routines.
      subroutine read_geom_rtp_file_b                                 &
     &         (file_name, id_rank, sph_file, ierr)
      subroutine read_spectr_modes_rj_file_b                          &
     &         (file_name, id_rank, sph_file, ierr)
      subroutine read_geom_rtm_file_b                                 &
     &         (file_name, id_rank, sph_file, ierr)
      subroutine read_modes_rlm_file_b                                &
     &         (file_name, id_rank, sph_file, ierr)
        type(sph_file_data_type), intent(inout) :: sph_file
      subroutine write_geom_rtp_file_b                                &
     &         (file_name, id_rank, sph_file), ierr
      subroutine write_spectr_modes_rj_file_b                         &
     &         (file_name, id_rank, sph_file, ierr)
      subroutine write_geom_rtm_file_b                                &
     &         (file_name, id_rank, sph_file, ierr)
      subroutine write_modes_rlm_file_b                               &
     &         (file_name, id_rank, sph_file, ierr)
        type(sph_file_data_type), intent(in) :: sph_file
Parameters
id_rank Process ID
file_name file name for IO (.gz is appended in this module)
Function/Subroutine Documentation
read_geom_rtm_file_b()
subroutine sph_modes_grids_file_io_b::read_geom_rtm_file_b (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(sph_file_data_type), intent(inout) sph_file, integer(kind = kint), intent(inout) ierr)
Definition at line 113 of file sph_modes_grids_file_IO_b.f90.
References bbuf_sph, binary_io::close_binary_file(), m_machine_parameter::i_debug, id_read_sph, binary_io::open_read_binary_file(), and sph_modes_grids_data_io_b::read_geom_rtm_data_b().
Referenced by sph_file_io_select::sel_read_geom_rtm_file().
read_geom_rtp_file_b()
subroutine sph_modes_grids_file_io_b::read_geom_rtp_file_b (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(sph_file_data_type), intent(inout) sph_file, integer(kind = kint), intent(inout) ierr)
Definition at line 57 of file sph_modes_grids_file_IO_b.f90.
References bbuf_sph, binary_io::close_binary_file(), m_machine_parameter::i_debug, id_read_sph, binary_io::open_read_binary_file(), and sph_modes_grids_data_io_b::read_geom_rtp_data_b().
Referenced by sph_file_io_select::sel_read_geom_rtp_file().
read_modes_rlm_file_b()
subroutine sph_modes_grids_file_io_b::read_modes_rlm_file_b (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(sph_file_data_type), intent(inout) sph_file, integer(kind = kint), intent(inout) ierr)
Definition at line 139 of file sph_modes_grids_file_IO_b.f90.
References bbuf_sph, binary_io::close_binary_file(), m_machine_parameter::i_debug, id_read_sph, binary_io::open_read_binary_file(), and sph_modes_grids_data_io_b::read_modes_rlm_data_b().
Referenced by sph_file_io_select::sel_read_modes_rlm_file().
read_spectr_modes_rj_file_b()
subroutine sph_modes_grids_file_io_b::read_spectr_modes_rj_file_b (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(sph_file_data_type), intent(inout) sph_file, integer(kind = kint), intent(inout) ierr)
Definition at line 85 of file sph_modes_grids_file_IO_b.f90.
References bbuf_sph, binary_io::close_binary_file(), m_machine_parameter::i_debug, id_read_sph, binary_io::open_read_binary_file(), and sph_modes_grids_data_io_b::read_spectr_modes_rj_data_b().
Referenced by sph_file_io_select::sel_read_spectr_rj_file().
write_geom_rtm_file_b()
subroutine sph_modes_grids_file_io_b::write_geom_rtm_file_b (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(sph_file_data_type), intent(in) sph_file, integer(kind = kint), intent(inout) ierr)
Definition at line 220 of file sph_modes_grids_file_IO_b.f90.
References bbuf_sph, binary_io::close_binary_file(), m_machine_parameter::i_debug, id_write_sph, binary_io::open_write_binary_file(), and sph_modes_grids_data_io_b::write_geom_rtm_data_b().
Referenced by sph_file_io_select::sel_write_geom_rtm_file().
write_geom_rtp_file_b()
subroutine sph_modes_grids_file_io_b::write_geom_rtp_file_b (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(sph_file_data_type), intent(in) sph_file, integer(kind = kint), intent(inout) ierr)
Definition at line 166 of file sph_modes_grids_file_IO_b.f90.
References bbuf_sph, binary_io::close_binary_file(), m_machine_parameter::i_debug, id_write_sph, binary_io::open_write_binary_file(), and sph_modes_grids_data_io_b::write_geom_rtp_data_b().
Referenced by sph_file_io_select::sel_write_geom_rtp_file().
write_modes_rlm_file_b()
subroutine sph_modes_grids_file_io_b::write_modes_rlm_file_b (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(sph_file_data_type), intent(in) sph_file, integer(kind = kint), intent(inout) ierr)
Definition at line 245 of file sph_modes_grids_file_IO_b.f90.
References bbuf_sph, binary_io::close_binary_file(), m_machine_parameter::i_debug, id_write_sph, binary_io::open_write_binary_file(), and sph_modes_grids_data_io_b::write_modes_rlm_data_b().
Referenced by sph_file_io_select::sel_write_modes_rlm_file().
write_spectr_modes_rj_file_b()
subroutine sph_modes_grids_file_io_b::write_spectr_modes_rj_file_b (character(len=kchara), intent(in) file_name, integer, intent(in) id_rank, type(sph_file_data_type), intent(in) sph_file, integer(kind = kint), intent(inout) ierr)
Definition at line 193 of file sph_modes_grids_file_IO_b.f90.
References bbuf_sph, binary_io::close_binary_file(), m_machine_parameter::i_debug, id_write_sph, binary_io::open_write_binary_file(), and sph_modes_grids_data_io_b::write_spectr_modes_rj_data_b().
Referenced by sph_file_io_select::sel_write_spectr_modes_rj_file().
Variable Documentation
bbuf_sph
type(binary_io_buffer), private sph_modes_grids_file_io_b::bbuf_sph private
Definition at line 48 of file sph_modes_grids_file_IO_b.f90.
Referenced by read_geom_rtm_file_b(), read_geom_rtp_file_b(), read_modes_rlm_file_b(), read_spectr_modes_rj_file_b(), write_geom_rtm_file_b(), write_geom_rtp_file_b(), write_modes_rlm_file_b(), and write_spectr_modes_rj_file_b().
id_read_sph
integer(kind = kint), parameter, private sph_modes_grids_file_io_b::id_read_sph = 21 private
Definition at line 46 of file sph_modes_grids_file_IO_b.f90.
Referenced by read_geom_rtm_file_b(), read_geom_rtp_file_b(), read_modes_rlm_file_b(), and read_spectr_modes_rj_file_b().
id_write_sph
integer(kind = kint), parameter, private sph_modes_grids_file_io_b::id_write_sph = 22 private
Definition at line 47 of file sph_modes_grids_file_IO_b.f90.
Referenced by write_geom_rtm_file_b(), write_geom_rtp_file_b(), write_modes_rlm_file_b(), and write_spectr_modes_rj_file_b().