CALYPSO: t_control_array_real2 Module Reference
t_control_array_real2 Module Reference
Data Types
type ctl_array_r2
Structure for two reals control array.
type read_real2_item
structure of control item with two reals
Functions/Subroutines
subroutine read_real2_ctl_type (c_buf, label, real2_item)
subroutine write_real2_ctl_type (id_file, level, label, real2_item)
subroutine copy_real2_ctl (org_r2, new_r2)
subroutine alloc_control_array_r2 (array_r2)
subroutine dealloc_control_array_r2 (array_r2)
subroutine read_control_array_r2 (id_control, label, array_r2, c_buf)
subroutine write_control_array_r2 (id_control, level, label, array_r2)
subroutine append_control_array_r2 (read_r2, array_r2)
subroutine dup_control_array_r2 (org_r2, tgt_r2)
subroutine copy_control_array_r2 (num_copy, org_r2, tgt_r2)
subroutine append_control_item_r2 (read_r2, array_r2)
Function/Subroutine Documentation
alloc_control_array_r2()
subroutine t_control_array_real2::alloc_control_array_r2 (type(ctl_array_r2), intent(inout) array_r2)
Definition at line 130 of file t_control_array_real2.f90.
Referenced by append_control_array_r2(), bcast_control_arrays::bcast_ctl_array_r2(), dup_control_array_r2(), and read_control_array_r2().
append_control_array_r2()
subroutine t_control_array_real2::append_control_array_r2 (type(read_real2_item), intent(inout) read_r2, type(ctl_array_r2), intent(inout) array_r2)
Definition at line 223 of file t_control_array_real2.f90.
References alloc_control_array_r2(), append_control_item_r2(), copy_control_array_r2(), and dealloc_control_array_r2().
Referenced by read_control_array_r2().
append_control_item_r2()
subroutine t_control_array_real2::append_control_item_r2 (type(read_real2_item), intent(in) read_r2, type(ctl_array_r2), intent(inout) array_r2)
Definition at line 278 of file t_control_array_real2.f90.
Referenced by append_control_array_r2().
copy_control_array_r2()
subroutine t_control_array_real2::copy_control_array_r2 (integer(kind = kint), intent(in) num_copy, type(ctl_array_r2), intent(in) org_r2, type(ctl_array_r2), intent(inout) tgt_r2)
Definition at line 262 of file t_control_array_real2.f90.
Referenced by append_control_array_r2(), and dup_control_array_r2().
copy_real2_ctl()
subroutine t_control_array_real2::copy_real2_ctl (type(read_real2_item), intent(in) org_r2, type(read_real2_item), intent(inout) new_r2)
Definition at line 116 of file t_control_array_real2.f90.
dealloc_control_array_r2()
subroutine t_control_array_real2::dealloc_control_array_r2 (type(ctl_array_r2), intent(inout) array_r2)
Definition at line 146 of file t_control_array_real2.f90.
Referenced by append_control_array_r2().
dup_control_array_r2()
subroutine t_control_array_real2::dup_control_array_r2 (type(ctl_array_r2), intent(in) org_r2, type(ctl_array_r2), intent(inout) tgt_r2)
Definition at line 248 of file t_control_array_real2.f90.
References alloc_control_array_r2(), and copy_control_array_r2().
read_control_array_r2()
subroutine t_control_array_real2::read_control_array_r2 (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) label, type(ctl_array_r2), intent(inout) array_r2, type(buffer_for_control), intent(inout) c_buf)
Definition at line 160 of file t_control_array_real2.f90.
References alloc_control_array_r2(), append_control_array_r2(), t_read_control_elements::check_array_flag(), t_read_control_elements::check_end_array_flag(), t_read_control_elements::load_one_line_from_control(), and read_real2_ctl_type().
read_real2_ctl_type()
subroutine t_control_array_real2::read_real2_ctl_type (type(buffer_for_control), intent(in) c_buf, character(len=kchara), intent(in) label, type(read_real2_item), intent(inout) real2_item)
Definition at line 76 of file t_control_array_real2.f90.
References m_machine_parameter::iflag_debug.
Referenced by read_control_array_r2().
write_control_array_r2()
subroutine t_control_array_real2::write_control_array_r2 (integer(kind = kint), intent(in) id_control, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, type(ctl_array_r2), intent(in) array_r2)
Definition at line 194 of file t_control_array_real2.f90.
References write_control_elements::write_array_flag_for_ctl(), write_control_elements::write_end_array_flag_for_ctl(), and write_control_elements::write_real2_ctl_item().
write_real2_ctl_type()
subroutine t_control_array_real2::write_real2_ctl_type (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, type(read_real2_item), intent(in) real2_item)
Definition at line 98 of file t_control_array_real2.f90.
References write_control_elements::write_real2_ctl_item().