CALYPSO: t_legendre_work_testlooop Module Reference
t_legendre_work_testlooop Module Reference
Work array for forward Legendre transform useing mat multi
data are strored communication buffer.
Data Types
type leg_trns_testloop_work
Work structure for Legendre trasform by large matmul.
Functions/Subroutines
subroutine count_size_of_field_mat_test (np_smp, nri_rtm, istack_rtm_lt_smp, nvector, nscalar, lst_rtm, nle_rtm, nlo_rtm, Fmat)
subroutine init_legendre_sym_mat_both (sph_params, sph_rtm, idx_trns, nvector, nscalar, WK_l_tst)
subroutine dealloc_leg_sym_mat_both (WK_l_tst)
subroutine, private count_leg_sym_matmul_mtr (nidx_rtm, nvector, nscalar, idx_trns, WK_l_tst)
subroutine, private count_symmetric_leg_lj_omp (mphi_rtm, idx_trns, WK_l_tst)
Variables
integer(kind=kint), parameter n_sse2 = itwo
integer(kind=kint), parameter n_avx = ifour
integer(kind=kint), parameter n_avx512 = ieight
Detailed Description
Work array for forward Legendre transform useing mat multi
data are strored communication buffer.
      subroutine init_legendre_sym_mat_both(sph_params, sph_rtm,      &
     &          idx_trns, nvector, nscalar, WK_l_tst)
        type(sph_shell_parameters), intent(in) :: sph_params
        type(sph_rtm_grid), intent(in) :: sph_rtm
        type(legendre_4_sph_trans), intent(in) :: leg
        type(index_4_sph_trans), intent(in) :: idx_trns
        type(leg_trns_testloop_work), intent(inout) :: WK_l_tst
      subroutine dealloc_leg_sym_mat_both(mphi_rtm, WK_l_tst)
        type(leg_trns_testloop_work), intent(inout) :: WK_l_tst
     field data for Legendre transform
       original layout: vr_rtm(l_rtm,m_rtm,k_rtm,icomp)
       size: vr_rtm(nth_rtm,nidx_rtm(1)*ncomp,nidx_rtm(3))
      real(kind = kreal), allocatable :: vr_rtm(:,:,:)
     spectr data for Legendre transform
       original layout: sp_rlm(j_rlm,k_rtm,icomp)
        size: sp_rlm(nidx_rlm(2),nidx_rtm(1)*ncomp)
      real(kind = kreal), allocatable :: sp_rlm(:,:)
Parameters
ncomp Total number of components for spherical transform
nvector Number of vector for spherical transform
nscalar Number of scalar (including tensor components) for spherical transform
Function/Subroutine Documentation
count_leg_sym_matmul_mtr()
subroutine, private t_legendre_work_testlooop::count_leg_sym_matmul_mtr (integer(kind = kint), dimension(3), intent(in) nidx_rtm, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(index_4_sph_trans), intent(in) idx_trns, type(leg_trns_testloop_work), intent(inout) WK_l_tst) private
Definition at line 228 of file t_legendre_work_testlooop.f90.
Referenced by init_legendre_sym_mat_both().
count_size_of_field_mat_test()
subroutine t_legendre_work_testlooop::count_size_of_field_mat_test (integer(kind = kint), intent(in) np_smp, integer(kind = kint), intent(in) nri_rtm, integer(kind = kint), dimension(0:np_smp), intent(in) istack_rtm_lt_smp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, integer(kind = kint), dimension(np_smp), intent(inout) lst_rtm, integer(kind = kint), dimension(np_smp), intent(inout) nle_rtm, integer(kind = kint), dimension(np_smp), intent(inout) nlo_rtm, type(field_matrix_omp), dimension(np_smp), intent(inout) Fmat)
Definition at line 105 of file t_legendre_work_testlooop.f90.
References n_avx512, and m_machine_parameter::np_smp.
Referenced by init_legendre_sym_mat_both().
count_symmetric_leg_lj_omp()
subroutine, private t_legendre_work_testlooop::count_symmetric_leg_lj_omp (integer(kind = kint), intent(in) mphi_rtm, type(index_4_sph_trans), intent(in) idx_trns, type(leg_trns_testloop_work), intent(inout) WK_l_tst) private
Definition at line 247 of file t_legendre_work_testlooop.f90.
Referenced by init_legendre_sym_mat_both().
dealloc_leg_sym_mat_both()
subroutine t_legendre_work_testlooop::dealloc_leg_sym_mat_both (type(leg_trns_testloop_work), intent(inout) WK_l_tst)
Definition at line 201 of file t_legendre_work_testlooop.f90.
References t_set_legendre_4_sph_trans::dealloc_cal_legendre_work(), t_legendre_matrix_4_trns::dealloc_each_sym_leg_mat_jt(), t_legendre_matrix_4_trns::dealloc_each_sym_leg_mat_tj(), t_field_matrices_4_legendre::dealloc_field_mat_omp(), t_field_matrices_4_legendre::dealloc_spectr_mat_omp(), and m_machine_parameter::np_smp.
Referenced by t_legendre_trans_select::sel_finalize_legendre_trans().
init_legendre_sym_mat_both()
subroutine t_legendre_work_testlooop::init_legendre_sym_mat_both (type(sph_shell_parameters), intent(in) sph_params, type(sph_rtm_grid), intent(in) sph_rtm, type(index_4_sph_trans), intent(in) idx_trns, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(leg_trns_testloop_work), intent(inout) WK_l_tst)
Definition at line 142 of file t_legendre_work_testlooop.f90.
References t_set_legendre_4_sph_trans::alloc_cal_legendre_work(), t_legendre_matrix_4_trns::alloc_each_sym_leg_omp_mat_jt(), t_legendre_matrix_4_trns::alloc_each_sym_leg_omp_mat_tj(), t_field_matrices_4_legendre::alloc_field_mat_omp(), t_field_matrices_4_legendre::alloc_spectr_mat_omp(), count_leg_sym_matmul_mtr(), count_size_of_field_mat_test(), count_symmetric_leg_lj_omp(), n_avx512, and m_machine_parameter::np_smp.
Referenced by t_legendre_trans_select::sel_init_legendre_trans().
Variable Documentation
n_avx
integer(kind = kint), parameter t_legendre_work_testlooop::n_avx = ifour
Definition at line 59 of file t_legendre_work_testlooop.f90.
Referenced by legendre_fwd_trans_testloop::leg_fwd_trans_4latitude().
n_avx512
integer(kind = kint), parameter t_legendre_work_testlooop::n_avx512 = ieight
Definition at line 60 of file t_legendre_work_testlooop.f90.
Referenced by count_size_of_field_mat_test(), init_legendre_sym_mat_both(), and legendre_fwd_trans_testloop::leg_fwd_trans_8latitude().
n_sse2
integer(kind = kint), parameter t_legendre_work_testlooop::n_sse2 = itwo
Definition at line 58 of file t_legendre_work_testlooop.f90.
Referenced by legendre_fwd_trans_testloop::leg_fwd_trans_2latitude().