CALYPSO: t_spherical_harmonics Module Reference
t_spherical_harmonics Module Reference
Data array for spherical harmonics.
Data Types
type sph_1point_type
structure of spherical harmonics at single point
Functions/Subroutines
subroutine alloc_index_4_sph (nth, sph)
subroutine alloc_spherical_harmonics (sph)
subroutine dealloc_index_4_sph (sph)
subroutine dealloc_spherical_harmonics (sph)
subroutine init_sph_indices (nth, leg, sph)
subroutine finalize_sph_indices (leg, sph)
subroutine spheric_1point (theta, phi, leg, sph)
Detailed Description
Data array for spherical harmonics.
       subroutine alloc_index_4_sph(nth, sph)
       subroutine alloc_spherical_harmonics(sph)
       subroutine dealloc_index_4_sph(sph)
       subroutine dealloc_spherical_harmonics(sph)
      subroutine init_sph_indices(nth, leg, sph)
      subroutine finalize_sph_indices(leg, sph)
      subroutine spheric_1point(theta, phi, leg, sph)
Function/Subroutine Documentation
alloc_index_4_sph()
subroutine t_spherical_harmonics::alloc_index_4_sph (integer(kind = kint), intent(in) nth, type(sph_1point_type), intent(inout) sph)
Definition at line 51 of file t_spherical_harmonics.f90.
Referenced by init_sph_indices().
alloc_spherical_harmonics()
subroutine t_spherical_harmonics::alloc_spherical_harmonics (type(sph_1point_type), intent(inout) sph)
Definition at line 69 of file t_spherical_harmonics.f90.
dealloc_index_4_sph()
subroutine t_spherical_harmonics::dealloc_index_4_sph (type(sph_1point_type), intent(inout) sph)
Definition at line 80 of file t_spherical_harmonics.f90.
Referenced by finalize_sph_indices().
dealloc_spherical_harmonics()
subroutine t_spherical_harmonics::dealloc_spherical_harmonics (type(sph_1point_type), intent(inout) sph)
Definition at line 90 of file t_spherical_harmonics.f90.
finalize_sph_indices()
subroutine t_spherical_harmonics::finalize_sph_indices (type(legendre_polynomials), intent(inout) leg, type(sph_1point_type), intent(inout) sph)
Definition at line 119 of file t_spherical_harmonics.f90.
References dealloc_index_4_sph(), and t_schmidt_polynomial::dealloc_schmidt_polynomial().
Referenced by schmidt_poly_on_meridian::cal_full_legendre_on_med().
init_sph_indices()
subroutine t_spherical_harmonics::init_sph_indices (integer(kind = kint), intent(in) nth, type(legendre_polynomials), intent(inout) leg, type(sph_1point_type), intent(inout) sph)
Definition at line 101 of file t_spherical_harmonics.f90.
References alloc_index_4_sph(), t_schmidt_polynomial::alloc_schmidt_polynomial(), and spherical_harmonics::idx28().
Referenced by schmidt_poly_on_meridian::cal_full_legendre_on_med().
spheric_1point()
subroutine t_spherical_harmonics::spheric_1point (real(kind = kreal), intent(in) theta, real(kind = kreal), intent(in) phi, type(legendre_polynomials), intent(inout) leg, type(sph_1point_type), intent(inout) sph)
Definition at line 134 of file t_spherical_harmonics.f90.
References t_schmidt_polynomial::dschmidt(), and spherical_harmonics::spheric().