CALYPSO: t_psf_case_table Module Reference
t_psf_case_table Module Reference
List of local patch case table.
Data Types
type psf_cases
Structure of triangle patch list for each section case.
type psf_each_case
Structure of triangle patch list for each section case.
Functions/Subroutines
subroutine init_psf_case_tables (case_tbls)
subroutine dealloc_psf_case_table (case_tbls)
subroutine, private set_psf_table_4_each_case (nkind_etype, num_patch_n, iflag_psf_etype_x, iedge_4_patch_x, num_case_tbl, psf_case_tbl)
subroutine, private set_psf_table_4_each_case_0 (nkind_etype, num_patch_0, iflag_psf_etype_x, num_case_tbl, psf_case_tbl)
subroutine, private alloc_psf_case_tables (case_tbls)
subroutine, private alloc_psf_case_tbl_item (psf_case_tbl)
Detailed Description
List of local patch case table.
      subroutine init_psf_case_tables(case_tbls)
      subroutine dealloc_psf_case_table(case_tbls)
      integer(kind = kint), parameter :: num_patch(0:14)              &
     &     = (/0, 1, 2, 4, 2, 3, 5, 5, 2, 4, 4, 4, 4, 4, 4/)
      integer(kind = kint), parameter                                 &
     &   :: iflag_psf_etype_0(2) = (/0, 255/)
      integer(kind = kint), parameter                                 &
     &   :: iflag_psf_etype_1p(nkind_etype_1)                         &
     &     = (/1, 2, 4, 8, 16, 32, 64, 128/)
      integer(kind = kint), parameter                                 &
     &   :: iflag_psf_etype_1n(nkind_etype_1)                         &
     &     = (/254, 253, 251, 247, 239, 223, 191, 127/)
      integer(kind = kint), parameter                                 &
     &   :: iflag_psf_etype_2p(nkind_etype_2)                         &
     &     = (/  3,   6,  12,   9,  48,  96,                          &
     &         192, 144,  17,  34,  68, 136/)
      integer(kind = kint), parameter                                 &
     &   :: iflag_psf_etype_2n(nkind_etype_2)                         &
     &     = (/252, 249, 243, 246, 207, 159,                          &
     &          63, 111, 238, 221, 187, 119/)
      integer(kind = kint), parameter                                 &
     &   :: iflag_psf_etype_3p(nkind_etype_3)                         &
     &     = (/129,  36,  18,  72,   5, 160,                          &
     &          24,  66,  33, 132,  10,  80/)
      integer(kind = kint), parameter                                 &
     &   :: iflag_psf_etype_3n(nkind_etype_3)                         &
     &     = (/126, 219, 237, 183, 250,  95,                          &
     &         231, 189, 222, 123, 245, 175/)
      integer(kind = kint), parameter                                 &
     &   :: iflag_psf_etype_4p(nkind_etype_4) = (/ 65, 130,  20,  40/)
      integer(kind = kint), parameter                                 &
     &   :: iflag_psf_etype_4n(nkind_etype_4) = (/190, 125, 235, 215/)
      integer(kind = kint), parameter                                 &
     &   :: iflag_psf_etype_5p(nkind_etype_5)                         &
     &     = (/ 152, 137,  25,  145,   100,  98,  38,  70,            &
     &           50,  49,  19,   35,   196,  76, 140, 200,            &
     &           14,   7,  11,   13,   224, 208, 176, 112/)
      integer(kind = kint), parameter                                 &
     &   :: iflag_psf_etype_5n(nkind_etype_5)                         &
     &     = (/ 103, 118, 230, 110,    155, 157, 217, 185,            &
     &          205, 206, 236, 220,     59, 179, 115,  55,            &
     &          241, 248, 244, 242,     31,  47,  79, 143/)
      integer(kind = kint), parameter                                 &
     &   :: iflag_psf_etype_6p(nkind_etype_6)                         &
     &     = (/131,  22,  44,  73,    56,  97, 194, 148,              &
     &          21,  42,  69, 138,    67, 134,  28,  41,              &
     &          52, 104, 193, 146,    81, 162,  84, 168/)
      integer(kind = kint), parameter                                 &
     &   :: iflag_psf_etype_6n(nkind_etype_6)                         &
     &     = (/124, 233, 211, 182,   199, 158,  61, 107,              &
     &         234, 213, 186, 117,   188, 121, 227, 214,              &
     &         203, 151,  62, 109,   174,  93, 171,  87/)
      integer(kind = kint), parameter                                 &
     &   :: iflag_psf_etype_7p(nkind_etype_7)                         &
     &     = (/ 26,  37,  74, 133, 161,  82, 164,  88/)
      integer(kind = kint), parameter                                 &
     &   :: iflag_psf_etype_7n(nkind_etype_7)                         &
     &     = (/229, 218, 181, 122,  94, 173,  91, 167/)
      integer(kind = kint), parameter                                 &
     &   :: iflag_psf_etype_8(nkind_etype_8)                          &
     &     = (/153, 102,  51, 204, 15, 240/)
      integer(kind = kint), parameter                                 &
     &   :: iflag_psf_etype_9(nkind_etype_9)                          &
     &     = (/27, 39, 78, 141, 177, 114, 228, 216/)
      integer(kind = kint), parameter                                 &
     &   :: iflag_psf_etype_10(nkind_etype_10)                        &
     &     = (/195, 150, 60, 105, 85, 170/)
      integer(kind = kint), parameter                                 &
     &   :: iflag_psf_etype_11(nkind_etype_11)                        &
     &     = (/ 71, 142, 29,  43, 184, 113,                           &
     &         226, 212, 54, 108, 201, 147/)
      integer(kind = kint), parameter                                 &
     &   :: iflag_psf_etype_12(nkind_etype_12)                        &
     &     = (/154, 169,  89, 149,    101, 106, 166,  86,             &
     &          58,  53,  83, 163,    197,  92, 172, 202,             &
     &          30, 135,  75,  45,    225, 210, 180, 120/)
      integer(kind = kint), parameter                                 &
     &   :: iflag_psf_etype_12(nkind_etype_13) = (/165, 90/)
      integer(kind = kint), parameter                                 &
     &   :: iflag_psf_etype_14(nkind_etype_14)                        &
     &     = (/ 23,  46,  77, 139,    232, 209, 178, 116,             &
     &          99, 198, 156, 57/)
Function/Subroutine Documentation
alloc_psf_case_tables()
subroutine, private t_psf_case_table::alloc_psf_case_tables (type(psf_cases), intent(inout) case_tbls) private
Definition at line 349 of file t_psf_case_table.f90.
Referenced by init_psf_case_tables().
alloc_psf_case_tbl_item()
subroutine, private t_psf_case_table::alloc_psf_case_tbl_item (type(psf_each_case), intent(inout) psf_case_tbl) private
Definition at line 361 of file t_psf_case_table.f90.
Referenced by set_psf_table_4_each_case(), and set_psf_table_4_each_case_0().
dealloc_psf_case_table()
subroutine t_psf_case_table::dealloc_psf_case_table (type(psf_cases), intent(inout) case_tbls)
Definition at line 274 of file t_psf_case_table.f90.
Referenced by t_cross_section::dealloc_psf_field_type().
init_psf_case_tables()
subroutine t_psf_case_table::init_psf_case_tables (type(psf_cases), intent(inout) case_tbls)
Definition at line 143 of file t_psf_case_table.f90.
References alloc_psf_case_tables(), m_intersection_data_10::iedge_4_patch_10, m_intersection_data_11::iedge_4_patch_11, m_intersection_data_12::iedge_4_patch_12, m_intersection_data_13::iedge_4_patch_13, m_intersection_data_14::iedge_4_patch_14, m_intersection_data_1::iedge_4_patch_1n, m_intersection_data_1::iedge_4_patch_1p, m_intersection_data_2::iedge_4_patch_2n, m_intersection_data_2::iedge_4_patch_2p, m_intersection_data_3::iedge_4_patch_3n, m_intersection_data_3::iedge_4_patch_3p, m_intersection_data_4::iedge_4_patch_4n, m_intersection_data_4::iedge_4_patch_4p, m_intersection_data_5::iedge_4_patch_5n, m_intersection_data_5::iedge_4_patch_5p, m_intersection_data_6::iedge_4_patch_6n, m_intersection_data_6::iedge_4_patch_6p, m_intersection_data_7::iedge_4_patch_7n, m_intersection_data_7::iedge_4_patch_7p, m_intersection_data_8::iedge_4_patch_8, m_intersection_data_9::iedge_4_patch_9, m_intersection_data_0::iflag_psf_etype_0, m_intersection_data_10::iflag_psf_etype_10, m_intersection_data_11::iflag_psf_etype_11, m_intersection_data_12::iflag_psf_etype_12, m_intersection_data_13::iflag_psf_etype_13, m_intersection_data_14::iflag_psf_etype_14, m_intersection_data_1::iflag_psf_etype_1n, m_intersection_data_1::iflag_psf_etype_1p, m_intersection_data_2::iflag_psf_etype_2n, m_intersection_data_2::iflag_psf_etype_2p, m_intersection_data_3::iflag_psf_etype_3n, m_intersection_data_3::iflag_psf_etype_3p, m_intersection_data_4::iflag_psf_etype_4n, m_intersection_data_4::iflag_psf_etype_4p, m_intersection_data_5::iflag_psf_etype_5n, m_intersection_data_5::iflag_psf_etype_5p, m_intersection_data_6::iflag_psf_etype_6n, m_intersection_data_6::iflag_psf_etype_6p, m_intersection_data_7::iflag_psf_etype_7n, m_intersection_data_7::iflag_psf_etype_7p, m_intersection_data_8::iflag_psf_etype_8, m_intersection_data_9::iflag_psf_etype_9, m_intersection_data_0::nkind_etype_0, m_intersection_data_1::nkind_etype_1, m_intersection_data_10::nkind_etype_10, m_intersection_data_11::nkind_etype_11, m_intersection_data_12::nkind_etype_12, m_intersection_data_13::nkind_etype_13, m_intersection_data_14::nkind_etype_14, m_intersection_data_2::nkind_etype_2, m_intersection_data_3::nkind_etype_3, m_intersection_data_4::nkind_etype_4, m_intersection_data_5::nkind_etype_5, m_intersection_data_6::nkind_etype_6, m_intersection_data_7::nkind_etype_7, m_intersection_data_8::nkind_etype_8, m_intersection_data_9::nkind_etype_9, m_intersection_data_0::num_patch_0, m_intersection_data_1::num_patch_1, m_intersection_data_10::num_patch_10, m_intersection_data_11::num_patch_11, m_intersection_data_12::num_patch_12, m_intersection_data_13::num_patch_13, m_intersection_data_14::num_patch_14, m_intersection_data_2::num_patch_2, m_intersection_data_3::num_patch_3, m_intersection_data_4::num_patch_4, m_intersection_data_5::num_patch_5, m_intersection_data_6::num_patch_6, m_intersection_data_7::num_patch_7, m_intersection_data_8::num_patch_8, m_intersection_data_9::num_patch_9, set_psf_table_4_each_case(), and set_psf_table_4_each_case_0().
Referenced by t_cross_section::sectioning_initialize().
set_psf_table_4_each_case()
subroutine, private t_psf_case_table::set_psf_table_4_each_case (integer(kind=kint), intent(in) nkind_etype, integer(kind=kint), intent(in) num_patch_n, integer(kind=kint), dimension(nkind_etype), intent(in) iflag_psf_etype_x, integer(kind=kint), dimension(num_triangle,num_patch_n,nkind_etype), intent(in) iedge_4_patch_x, integer(kind=kint), intent(in) num_case_tbl, type(psf_each_case), dimension(0:num_case_tbl), intent(inout) psf_case_tbl) private
Definition at line 289 of file t_psf_case_table.f90.
References alloc_psf_case_tbl_item(), and m_geometry_constants::num_triangle.
Referenced by init_psf_case_tables().
set_psf_table_4_each_case_0()
subroutine, private t_psf_case_table::set_psf_table_4_each_case_0 (integer(kind=kint), intent(in) nkind_etype, integer(kind=kint), intent(in) num_patch_0, integer(kind=kint), dimension(nkind_etype), intent(in) iflag_psf_etype_x, integer(kind=kint), intent(in) num_case_tbl, type(psf_each_case), dimension(0:num_case_tbl), intent(inout) psf_case_tbl) private
Definition at line 323 of file t_psf_case_table.f90.
References alloc_psf_case_tbl_item().
Referenced by init_psf_case_tables().