CALYPSO: cal_write_sph_monitor_data Module Reference
cal_write_sph_monitor_data Module Reference
I/O routines for mean square and averaga data.
Functions/Subroutines
subroutine cal_sph_monitor_data (sph_params, sph_rj, sph_bc_U, leg, ipol, rj_fld, pwr, WK_pwr, Nusselt)
subroutine output_sph_monitor_data (ene_labels, time_d, sph_params, sph_rj, ipol, rj_fld, pwr, pick_coef, gauss_coef, Nusselt)
subroutine output_sph_mean_square_files (ene_labels, time_d, sph_params, sph_rj, pwr)
subroutine cal_write_no_heat_sourse_nu (time_d, sph_rj, sph_bc_U, ipol, rj_fld, Nusselt)
Detailed Description
I/O routines for mean square and averaga data.
      subroutine cal_sph_monitor_data                                 &
     &         (sph_params, sph_rj, sph_bc_U, leg, ipol, rj_fld,      &
     &          pwr, WK_pwr, Nusselt)
      subroutine output_sph_monitor_data                              &
     &         (ene_labels, time_d, sph_params, sph_rj,               &
     &          ipol, rj_fld, pwr, pick_coef, gauss_coef, Nusselt)
      subroutine output_sph_mean_square_files                         &
     &         (ene_labels, time_d, sph_params, sph_rj, pwr)
      subroutine cal_write_no_heat_sourse_Nu(time_d, sph_rj,          &
     &          sph_bc_U, ipol, rj_fld, Nusselt)
        type(energy_label_param), intent(in) :: ene_labels
        type(sph_shell_parameters), intent(in) :: sph_params
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(sph_boundary_type), intent(in) :: sph_bc_U
        type(legendre_4_sph_trans), intent(in) :: leg
        type(phys_address), intent(in) :: ipol
        type(phys_data), intent(in) :: rj_fld
        type(sph_mean_squares), intent(inout) :: pwr
        type(sph_mean_square_work), intent(inout) :: WK_pwr
        type(picked_spectrum_data), intent(inout) :: pick_coef
        type(picked_spectrum_data), intent(inout) :: gauss_coef
        type(nusselt_number_data), intent(inout) :: Nusselt
Function/Subroutine Documentation
cal_sph_monitor_data()
subroutine cal_write_sph_monitor_data::cal_sph_monitor_data (type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(sph_boundary_type), intent(in) sph_bc_U, type(legendre_4_sph_trans), intent(in) leg, type(phys_address), intent(in) ipol, type(phys_data), intent(in) rj_fld, type(sph_mean_squares), intent(inout) pwr, type(sph_mean_square_work), intent(inout) WK_pwr, type(nusselt_number_data), intent(inout) Nusselt)
Definition at line 59 of file cal_write_sph_monitor_data.f90.
References cal_rms_fields_by_sph::cal_mean_squre_in_shell(), pickup_gauss_coefficients::cal_no_heat_source_nu(), and m_machine_parameter::iflag_debug.
Referenced by t_sph_mhd_monitor_data_io::output_rms_sph_mhd_control().
cal_write_no_heat_sourse_nu()
subroutine cal_write_sph_monitor_data::cal_write_no_heat_sourse_nu (type(time_data), intent(in) time_d, type(sph_rj_grid), intent(in) sph_rj, type(sph_boundary_type), intent(in) sph_bc_U, type(phys_address), intent(in) ipol, type(phys_data), intent(in) rj_fld, type(nusselt_number_data), intent(inout) Nusselt)
Definition at line 163 of file cal_write_sph_monitor_data.f90.
References pickup_gauss_coefficients::cal_no_heat_source_nu(), and t_no_heat_nusselt::write_no_heat_source_nu().
output_sph_mean_square_files()
subroutine cal_write_sph_monitor_data::output_sph_mean_square_files (type(energy_label_param), intent(in) ene_labels, type(time_data), intent(in) time_d, type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(sph_mean_squares), intent(inout) pwr)
Definition at line 132 of file cal_write_sph_monitor_data.f90.
References calypso_mpi::my_rank, output_sph_m_square_file::write_sph_layer_ms_file(), output_sph_m_square_file::write_sph_layer_spectr_file(), output_sph_m_square_file::write_sph_vol_ave_file(), output_sph_m_square_file::write_sph_vol_ms_file(), and output_sph_m_square_file::write_sph_vol_ms_spectr_file().
Referenced by output_sph_monitor_data().
output_sph_monitor_data()
subroutine cal_write_sph_monitor_data::output_sph_monitor_data (type(energy_label_param), intent(in) ene_labels, type(time_data), intent(in) time_d, type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(phys_address), intent(in) ipol, type(phys_data), intent(in) rj_fld, type(sph_mean_squares), intent(inout) pwr, type(picked_spectrum_data), intent(inout) pick_coef, type(picked_spectrum_data), intent(inout) gauss_coef, type(nusselt_number_data), intent(inout) Nusselt)
Definition at line 93 of file cal_write_sph_monitor_data.f90.
References mpi_picked_sph_spectr_io::append_picked_spectrum_file(), mpi_sph_gauss_coefs_io::append_sph_gauss_coefs_file(), m_machine_parameter::iflag_debug, calypso_mpi::my_rank, output_sph_mean_square_files(), t_no_heat_nusselt::write_no_heat_source_nu(), and output_sph_m_square_file::write_total_energy_to_screen().
Referenced by t_sph_mhd_monitor_data_io::output_rms_sph_mhd_control().