CALYPSO: m_file_format_labels Module Reference
m_file_format_labels Module Reference
integer flags for Data file's format
Functions/Subroutines
subroutine init_file_format_flags ()
subroutine dealloc_file_format_flags ()
integer(kind=kint) function num_label_file_fmt ()
subroutine set_label_file_fmt (names)
subroutine cvt_default_field_format_flag (file_fmt_ctl)
Variables
integer(kind=kint), parameter n_label_file_fmt = 10
character(len=kchara), parameter hd_ascii = 'ascii'
flag parts for distributed ascii data
character(len=kchara), parameter hd_binary = 'binary'
flag parts for distributed binary data
character(len=kchara), parameter hd_gzip = 'gzip'
flag parts for distributed compressed ascii data
character(len=kchara), parameter hd_bin_gz = 'binary_gz'
flag parts for distributed compressed binary data
character(len=kchara), parameter hd_none = 'none'
flag parts for distributed compressed binary data
character(len=kchara), parameter hd_merged = 'merged_ascii'
flag parts for merged ascii data
character(len=kchara), parameter hd_merged_bin = 'merged_binary'
flag parts for merged binary data
character(len=kchara), parameter hd_merged_gz = 'merged_gz'
flag parts for merged compressed ascii data
character(len=kchara), parameter hd_merged_bin_gz = 'merged_bin_gz'
flag parts for merged compressed binary data
character(len=kchara), parameter hd_rayleigh = "Rayleigh"
Rayleigh data flag.
character(len=kchara), parameter hd_rayleigh99 = "Rayleigh_09"
Rayleigh Ver. 0.9 data flag.
character(len=kchara), dimension(2), parameter ascii_names = (/'ascii ', 'text '/)
flag parts for ascii data
character(len=kchara), dimension(2), parameter bin_names = (/'binary ', 'bin '/)
flag parts for binary data
character(len=kchara), dimension(2), parameter gzip_names = (/'gzip ', 'gz '/)
flag parts for compressed data
character(len=kchara), dimension(2), parameter merged_names = (/'merged ', 'single '/)
flag parts for MPI-IO usage
character(len=kchara), dimension(2), parameter none_names = (/'None ', 'No_file '/)
flag parts for MPI-IO usage
type(multi_flag_labels), save binary_flags
Character lables for compressed ASCII 'binary', 'bin'.
type(multi_flag_labels), save ascii_flags
Character lables for ASCII 'ascii', 'text'.
type(multi_flag_labels), save gzip_flags
Character lables for UCD 'gzip', 'gz'.
type(multi_flag_labels), save merged_flags
Character lables for merged data by MPI-IO 'merged', 'single'.
type(multi_flag_labels), save no_file_flags
Character lables for No file 'None', 'No_file'.
type(multi_flag_labels), save gzip_ascii_flags
Character lables for compressed ASCII 'ascii_gzip', 'ascii_gz', 'text_gzip', 'text_gz', 'gzip_ascii', 'gzip_text', 'gz_ascii', 'gz_text', 'gzip', 'gz'.
type(multi_flag_labels), save gzip_bin_flags
Character lables for compressed ASCII 'binary_gzip', 'binary_gz', 'bin_gzip', 'bin_gz', 'gzip_binary', 'gzip_bin', 'gz_binary', 'gz_bin'.
type(multi_flag_labels), save mgd_ascii_flags
Character lables for merged ASCII 'merged_ascii', 'merged_text', 'single_ascii', 'single_text', 'ascii_merged', 'ascii_single', 'text_merged', 'text_single', 'merged', 'single'.
type(multi_flag_labels), save mgd_binary_flags
Character lables for merged binary 'merged_binary', 'merged_bin', 'single_binary', 'single_bin', 'binary_merged', 'binary_single', 'bin_merged', 'bin_single'.
type(multi_flag_labels), save mgd_gzip_flags
Character lables for merged compressed ASCII 'merged_ascii_gzip', 'merged_ascii_gz', 'merged_text_gzip', 'merged_text_gz', 'merged_gzip_ascii', 'merged_gzip_text', 'merged_gz_ascii', 'merged_gz_text', 'merged_gzip', 'merged_gz', 'single_ascii_gzip', 'single_ascii_gz', 'single_text_gzip', 'single_text_gz', 'single_gzip_ascii', 'single_gzip_text', 'single_gz_ascii', 'single_gz_text', 'single_gzip', 'single_gz', 'ascii_gzip_merged', 'ascii_gzip_single', 'ascii_gz_merged', 'ascii_gz_single', 'text_gzip_merged', 'text_gzip_single', 'text_gz_merged', 'text_gz_single', 'gzip_ascii_merged', 'gzip_ascii_single', 'gzip_text_merged', 'gzip_text_single', 'gz_ascii_merged', 'gz_ascii_single', 'gz_text_merged', 'gz_text_single', 'gzip_merged', 'gzip_single', 'gz_merged', 'gz_single'.
type(multi_flag_labels), save mgd_gzip_bin_flags
Character lables for compressesd merged binary 'merged_binary_gzip', 'merged_binary_gz', 'merged_bin_gzip', 'merged_bin_gz', 'merged_gzip_binary', 'merged_gzip_bin', 'merged_gz_binary', 'merged_gz_bin', 'single_binary_gzip', 'single_binary_gz', 'single_bin_gzip', 'single_bin_gz', 'single_gzip_binary', 'single_gzip_bin', 'single_gz_binary', 'single_gz_bin', 'binary_gzip_merged', 'binary_gzip_single', 'binary_gz_merged', 'binary_gz_single', 'bin_gzip_merged', 'bin_gzip_single', 'bin_gz_merged', 'bin_gz_single', 'gzip_binary_merged', 'gzip_binary_single', 'gzip_bin_merged', 'gzip_bin_single', 'gz_binary_merged', 'gz_binary_single', 'gz_bin_merged', 'gz_bin_single'.
Detailed Description
integer flags for Data file's format
      subroutine init_file_format_flags()
      subroutine dealloc_file_format_flags()
        File format name
          'ascii':        text (formatted) data
          'gzip':         gziopped text (formatted) data
          'binary':       binary data
          'binary_gz':    gziopped binary data
          'merged_ascii': text (formatted) data in merged file
          'merged_binary': binary data in merged file
          'merged_gz':    gziopped text (formatted) data in merged file
          'merged_bin_gz': gziopped binary data in merged file
      integer(kind = kint) function num_label_file_fmt()
      subroutine set_label_file_fmt(names)
      subroutine cvt_default_field_format_flag(file_fmt_ctl)
Function/Subroutine Documentation
cvt_default_field_format_flag()
subroutine m_file_format_labels::cvt_default_field_format_flag (character(len=kchara), intent(inout) file_fmt_ctl)
Definition at line 249 of file m_file_format_labels.f90.
References ascii_flags, binary_flags, t_multi_flag_labels::check_mul_flags(), skip_comment_f::cmp_no_case(), dealloc_file_format_flags(), gzip_ascii_flags, gzip_bin_flags, hd_ascii, hd_bin_gz, hd_gzip, hd_merged, hd_merged_bin, hd_merged_bin_gz, hd_merged_gz, hd_none, hd_rayleigh, hd_rayleigh99, init_file_format_flags(), mgd_ascii_flags, mgd_binary_flags, mgd_gzip_bin_flags, mgd_gzip_flags, and no_file_flags.
dealloc_file_format_flags()
subroutine m_file_format_labels::dealloc_file_format_flags
Definition at line 194 of file m_file_format_labels.f90.
References ascii_flags, binary_flags, t_multi_flag_labels::dealloc_multi_flags(), gzip_ascii_flags, gzip_bin_flags, gzip_flags, merged_flags, mgd_ascii_flags, mgd_binary_flags, mgd_gzip_bin_flags, mgd_gzip_flags, and no_file_flags.
Referenced by m_file_format_switch::choose_file_format_array(), cvt_default_field_format_flag(), m_field_file_format_labels::dealloc_field_type_flags(), and m_file_format_switch::set_parallel_file_format().
init_file_format_flags()
subroutine m_file_format_labels::init_file_format_flags
Definition at line 158 of file m_file_format_labels.f90.
References t_multi_flag_labels::append_multi_flag_labels(), ascii_flags, ascii_names, bin_names, binary_flags, gzip_ascii_flags, gzip_bin_flags, gzip_flags, gzip_names, t_multi_flag_labels::init_from_two_kinds_flags(), t_multi_flag_labels::init_multi_flags_by_labels(), m_constants::itwo, merged_flags, merged_names, mgd_ascii_flags, mgd_binary_flags, mgd_gzip_bin_flags, mgd_gzip_flags, no_file_flags, and none_names.
Referenced by m_file_format_switch::choose_file_format_array(), cvt_default_field_format_flag(), m_field_file_format_labels::init_field_type_flags(), and m_file_format_switch::set_parallel_file_format().
num_label_file_fmt()
integer(kind = kint) function m_file_format_labels::num_label_file_fmt
Definition at line 217 of file m_file_format_labels.f90.
References n_label_file_fmt.
set_label_file_fmt()
subroutine m_file_format_labels::set_label_file_fmt (character(len = kchara), dimension(n_label_file_fmt), intent(inout) names)
Definition at line 224 of file m_file_format_labels.f90.
References hd_ascii, hd_bin_gz, hd_binary, hd_gzip, hd_merged, hd_merged_bin, hd_merged_bin_gz, hd_merged_gz, hd_rayleigh, hd_rayleigh99, and t_read_control_elements::set_control_labels().
Variable Documentation
ascii_flags
type(multi_flag_labels), save m_file_format_labels::ascii_flags
Character lables for ASCII 'ascii', 'text'.
Definition at line 91 of file m_file_format_labels.f90.
Referenced by cvt_default_field_format_flag(), dealloc_file_format_flags(), m_field_file_format_labels::init_field_type_flags(), init_file_format_flags(), and m_file_format_switch::set_file_format().
ascii_names
character(len = kchara), dimension(2), parameter m_file_format_labels::ascii_names = (/'ascii ', 'text '/)
flag parts for ascii data
Definition at line 71 of file m_file_format_labels.f90.
Referenced by init_file_format_flags().
bin_names
character(len = kchara), dimension(2), parameter m_file_format_labels::bin_names = (/'binary ', 'bin '/)
flag parts for binary data
Definition at line 74 of file m_file_format_labels.f90.
Referenced by init_file_format_flags().
binary_flags
type(multi_flag_labels), save m_file_format_labels::binary_flags
Character lables for compressed ASCII 'binary', 'bin'.
Definition at line 88 of file m_file_format_labels.f90.
Referenced by cvt_default_field_format_flag(), dealloc_file_format_flags(), m_field_file_format_labels::init_field_type_flags(), init_file_format_flags(), and m_file_format_switch::set_file_format().
gzip_ascii_flags
type(multi_flag_labels), save m_file_format_labels::gzip_ascii_flags
Character lables for compressed ASCII 'ascii_gzip', 'ascii_gz', 'text_gzip', 'text_gz', 'gzip_ascii', 'gzip_text', 'gz_ascii', 'gz_text', 'gzip', 'gz'.
Definition at line 106 of file m_file_format_labels.f90.
Referenced by cvt_default_field_format_flag(), dealloc_file_format_flags(), init_file_format_flags(), and m_file_format_switch::set_file_format().
gzip_bin_flags
type(multi_flag_labels), save m_file_format_labels::gzip_bin_flags
Character lables for compressed ASCII 'binary_gzip', 'binary_gz', 'bin_gzip', 'bin_gz', 'gzip_binary', 'gzip_bin', 'gz_binary', 'gz_bin'.
Definition at line 110 of file m_file_format_labels.f90.
Referenced by cvt_default_field_format_flag(), dealloc_file_format_flags(), m_field_file_format_labels::init_field_type_flags(), init_file_format_flags(), and m_file_format_switch::set_file_format().
gzip_flags
type(multi_flag_labels), save m_file_format_labels::gzip_flags
Character lables for UCD 'gzip', 'gz'.
Definition at line 94 of file m_file_format_labels.f90.
Referenced by dealloc_file_format_flags(), m_field_file_format_labels::init_field_type_flags(), init_file_format_flags(), and m_merged_field_fmt_labels::init_mgd_field_type_flags().
gzip_names
character(len = kchara), dimension(2), parameter m_file_format_labels::gzip_names = (/'gzip ', 'gz '/)
flag parts for compressed data
Definition at line 77 of file m_file_format_labels.f90.
Referenced by init_file_format_flags().
hd_ascii
character(len = kchara), parameter m_file_format_labels::hd_ascii = 'ascii'
flag parts for distributed ascii data
Definition at line 40 of file m_file_format_labels.f90.
Referenced by cvt_default_field_format_flag(), and set_label_file_fmt().
hd_bin_gz
character(len = kchara), parameter m_file_format_labels::hd_bin_gz = 'binary_gz'
flag parts for distributed compressed binary data
Definition at line 46 of file m_file_format_labels.f90.
Referenced by cvt_default_field_format_flag(), and set_label_file_fmt().
hd_binary
character(len = kchara), parameter m_file_format_labels::hd_binary = 'binary'
flag parts for distributed binary data
Definition at line 42 of file m_file_format_labels.f90.
Referenced by set_label_file_fmt().
hd_gzip
character(len = kchara), parameter m_file_format_labels::hd_gzip = 'gzip'
flag parts for distributed compressed ascii data
Definition at line 44 of file m_file_format_labels.f90.
Referenced by cvt_default_field_format_flag(), and set_label_file_fmt().
hd_merged
character(len = kchara), parameter m_file_format_labels::hd_merged = 'merged_ascii'
flag parts for merged ascii data
Definition at line 51 of file m_file_format_labels.f90.
Referenced by cvt_default_field_format_flag(), and set_label_file_fmt().
hd_merged_bin
character(len = kchara), parameter m_file_format_labels::hd_merged_bin = 'merged_binary'
flag parts for merged binary data
Definition at line 54 of file m_file_format_labels.f90.
Referenced by cvt_default_field_format_flag(), and set_label_file_fmt().
hd_merged_bin_gz
character(len = kchara), parameter m_file_format_labels::hd_merged_bin_gz = 'merged_bin_gz'
flag parts for merged compressed binary data
Definition at line 60 of file m_file_format_labels.f90.
Referenced by cvt_default_field_format_flag(), and set_label_file_fmt().
hd_merged_gz
character(len = kchara), parameter m_file_format_labels::hd_merged_gz = 'merged_gz'
flag parts for merged compressed ascii data
Definition at line 57 of file m_file_format_labels.f90.
Referenced by cvt_default_field_format_flag(), and set_label_file_fmt().
hd_none
character(len = kchara), parameter m_file_format_labels::hd_none = 'none'
flag parts for distributed compressed binary data
Definition at line 48 of file m_file_format_labels.f90.
Referenced by cvt_default_field_format_flag().
hd_rayleigh
character(len = kchara), parameter m_file_format_labels::hd_rayleigh = "Rayleigh"
Rayleigh data flag.
Definition at line 64 of file m_file_format_labels.f90.
Referenced by cvt_default_field_format_flag(), set_label_file_fmt(), and m_file_format_switch::set_parallel_file_format().
hd_rayleigh99
character(len = kchara), parameter m_file_format_labels::hd_rayleigh99 = "Rayleigh_09"
Rayleigh Ver. 0.9 data flag.
Definition at line 66 of file m_file_format_labels.f90.
Referenced by cvt_default_field_format_flag(), set_label_file_fmt(), and m_file_format_switch::set_parallel_file_format().
merged_flags
type(multi_flag_labels), save m_file_format_labels::merged_flags
Character lables for merged data by MPI-IO 'merged', 'single'.
Definition at line 97 of file m_file_format_labels.f90.
Referenced by dealloc_file_format_flags(), init_file_format_flags(), and m_merged_field_fmt_labels::init_mgd_field_type_flags().
merged_names
character(len = kchara), dimension(2), parameter m_file_format_labels::merged_names = (/'merged ', 'single '/)
flag parts for MPI-IO usage
Definition at line 80 of file m_file_format_labels.f90.
Referenced by init_file_format_flags().
mgd_ascii_flags
type(multi_flag_labels), save m_file_format_labels::mgd_ascii_flags
Character lables for merged ASCII 'merged_ascii', 'merged_text', 'single_ascii', 'single_text', 'ascii_merged', 'ascii_single', 'text_merged', 'text_single', 'merged', 'single'.
Definition at line 116 of file m_file_format_labels.f90.
Referenced by cvt_default_field_format_flag(), dealloc_file_format_flags(), init_file_format_flags(), and m_file_format_switch::set_parallel_file_format().
mgd_binary_flags
type(multi_flag_labels), save m_file_format_labels::mgd_binary_flags
Character lables for merged binary 'merged_binary', 'merged_bin', 'single_binary', 'single_bin', 'binary_merged', 'binary_single', 'bin_merged', 'bin_single'.
Definition at line 120 of file m_file_format_labels.f90.
Referenced by cvt_default_field_format_flag(), dealloc_file_format_flags(), init_file_format_flags(), and m_file_format_switch::set_parallel_file_format().
mgd_gzip_bin_flags
type(multi_flag_labels), save m_file_format_labels::mgd_gzip_bin_flags
Character lables for compressesd merged binary 'merged_binary_gzip', 'merged_binary_gz', 'merged_bin_gzip', 'merged_bin_gz', 'merged_gzip_binary', 'merged_gzip_bin', 'merged_gz_binary', 'merged_gz_bin', 'single_binary_gzip', 'single_binary_gz', 'single_bin_gzip', 'single_bin_gz', 'single_gzip_binary', 'single_gzip_bin', 'single_gz_binary', 'single_gz_bin', 'binary_gzip_merged', 'binary_gzip_single', 'binary_gz_merged', 'binary_gz_single', 'bin_gzip_merged', 'bin_gzip_single', 'bin_gz_merged', 'bin_gz_single', 'gzip_binary_merged', 'gzip_binary_single', 'gzip_bin_merged', 'gzip_bin_single', 'gz_binary_merged', 'gz_binary_single', 'gz_bin_merged', 'gz_bin_single'.
Definition at line 150 of file m_file_format_labels.f90.
Referenced by cvt_default_field_format_flag(), dealloc_file_format_flags(), init_file_format_flags(), and m_file_format_switch::set_parallel_file_format().
mgd_gzip_flags
type(multi_flag_labels), save m_file_format_labels::mgd_gzip_flags
Character lables for merged compressed ASCII 'merged_ascii_gzip', 'merged_ascii_gz', 'merged_text_gzip', 'merged_text_gz', 'merged_gzip_ascii', 'merged_gzip_text', 'merged_gz_ascii', 'merged_gz_text', 'merged_gzip', 'merged_gz', 'single_ascii_gzip', 'single_ascii_gz', 'single_text_gzip', 'single_text_gz', 'single_gzip_ascii', 'single_gzip_text', 'single_gz_ascii', 'single_gz_text', 'single_gzip', 'single_gz', 'ascii_gzip_merged', 'ascii_gzip_single', 'ascii_gz_merged', 'ascii_gz_single', 'text_gzip_merged', 'text_gzip_single', 'text_gz_merged', 'text_gz_single', 'gzip_ascii_merged', 'gzip_ascii_single', 'gzip_text_merged', 'gzip_text_single', 'gz_ascii_merged', 'gz_ascii_single', 'gz_text_merged', 'gz_text_single', 'gzip_merged', 'gzip_single', 'gz_merged', 'gz_single'.
Definition at line 136 of file m_file_format_labels.f90.
Referenced by cvt_default_field_format_flag(), dealloc_file_format_flags(), init_file_format_flags(), and m_file_format_switch::set_parallel_file_format().
n_label_file_fmt
integer(kind = kint), parameter m_file_format_labels::n_label_file_fmt = 10
Definition at line 37 of file m_file_format_labels.f90.
Referenced by num_label_file_fmt().
no_file_flags
type(multi_flag_labels), save m_file_format_labels::no_file_flags
Character lables for No file 'None', 'No_file'.
Definition at line 100 of file m_file_format_labels.f90.
Referenced by cvt_default_field_format_flag(), dealloc_file_format_flags(), init_file_format_flags(), and m_file_format_switch::set_file_format().
none_names
character(len = kchara), dimension(2), parameter m_file_format_labels::none_names = (/'None ', 'No_file '/)
flag parts for MPI-IO usage
Definition at line 83 of file m_file_format_labels.f90.
Referenced by init_file_format_flags().