CALYPSO: set_from_recv_buf_rev Module Reference
set_from_recv_buf_rev Module Reference
Arbitrary components data communication.
Functions/Subroutines
subroutine set_reverse_import_table (nnod_new, nnod_recv, inod_import, irev_import)
subroutine clear_addtional_sr_recv (NB, nnod_recv, WR)
subroutine set_from_recv_buf_rev_1 (nnod_new, nnod_recv, irev_import, WR, X_new)
subroutine set_from_recv_buf_rev_2 (nnod_new, nnod_recv, irev_import, WR, X_new)
subroutine set_from_recv_buf_rev_3 (nnod_new, nnod_recv, irev_import, WR, X_new)
subroutine set_from_recv_buf_rev_6 (nnod_new, nnod_recv, irev_import, WR, X_new)
subroutine set_from_recv_buf_rev_n (NB, nnod_new, nnod_recv, irev_import, WR, X_new)
subroutine set_from_recv_buf_rev_int (nnod_new, nnod_recv, irev_import, iWR, iX_new)
subroutine set_from_recv_buf_rev_i8 (nnod_new, nnod_recv, irev_import, i8WR, i8X_new)
Detailed Description
Arbitrary components data communication.
      subroutine set_reverse_import_table(nnod_new, nnod_recv,        &
     &          inod_import, irev_import)
      subroutine clear_addtional_SR_recv(NB, nnod_recv, WR)
      subroutine set_from_recv_buf_rev_1(nnod_new,                    &
     &          nnod_recv, irev_import, WR, X_new)
      subroutine set_from_recv_buf_rev_2(nnod_new,                    &
     &          nnod_recv, irev_import, WR, X_new)
      subroutine set_from_recv_buf_rev_3(nnod_new,                    &
     &          nnod_recv, irev_import, WR, X_new)
      subroutine set_from_recv_buf_rev_6(nnod_new,                    &
     &          nnod_recv, irev_import, WR, X_new)
      subroutine set_from_recv_buf_rev_N(NB, nnod_new,                &
     &          nnod_recv, irev_import, WR, X_new)
      subroutine set_from_recv_buf_rev_int(nnod_new,                  &
     &          nnod_recv, irev_import, iWR, iX_new)
      subroutine set_from_recv_buf_rev_i8(nnod_new,                   &
     &          nnod_recv, irev_import, i8WR, i8X_new)
Parameters
NB Number of components for communication
nnod_new Number of components for destination
nnod_recv Number of data points to receive
irev_import(nnod_new) import buffer ID for each data point
X_new(NB*nnod_new) Received data
Function/Subroutine Documentation
clear_addtional_sr_recv()
subroutine set_from_recv_buf_rev::clear_addtional_sr_recv (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_recv, real (kind=kreal), dimension(nb*nnod_recv+nb), intent(inout) WR)
Definition at line 79 of file set_from_recv_buf_rev.f90.
Referenced by sel_spherical_srs::sel_calypso_sph_comm_n().
set_from_recv_buf_rev_1()
subroutine set_from_recv_buf_rev::set_from_recv_buf_rev_1 (integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) nnod_recv, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, real (kind=kreal), dimension(nnod_recv+1), intent(inout) WR, real (kind=kreal), dimension(nnod_new), intent(inout) X_new)
Definition at line 94 of file set_from_recv_buf_rev.f90.
Referenced by select_copy_from_recv::sel_cppy_from_recv_buf_1().
set_from_recv_buf_rev_2()
subroutine set_from_recv_buf_rev::set_from_recv_buf_rev_2 (integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) nnod_recv, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, real (kind=kreal), dimension(2*(nnod_recv+1)), intent(inout) WR, real (kind=kreal), dimension(2*nnod_new), intent(inout) X_new)
Definition at line 120 of file set_from_recv_buf_rev.f90.
Referenced by select_copy_from_recv::sel_cppy_from_recv_buf_2().
set_from_recv_buf_rev_3()
subroutine set_from_recv_buf_rev::set_from_recv_buf_rev_3 (integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) nnod_recv, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, real (kind=kreal), dimension(3*(nnod_recv+1)), intent(inout) WR, real (kind=kreal), dimension(3*nnod_new), intent(inout) X_new)
Definition at line 148 of file set_from_recv_buf_rev.f90.
Referenced by select_copy_from_recv::sel_cppy_from_recv_buf_3().
set_from_recv_buf_rev_6()
subroutine set_from_recv_buf_rev::set_from_recv_buf_rev_6 (integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) nnod_recv, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, real (kind=kreal), dimension(6*(nnod_recv+1)), intent(inout) WR, real (kind=kreal), dimension(6*nnod_new), intent(inout) X_new)
Definition at line 178 of file set_from_recv_buf_rev.f90.
Referenced by select_copy_from_recv::sel_cppy_from_recv_buf_6().
set_from_recv_buf_rev_i8()
subroutine set_from_recv_buf_rev::set_from_recv_buf_rev_i8 (integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) nnod_recv, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, integer(kind = kint_gl), dimension(nnod_recv+1), intent(inout) i8WR, integer(kind = kint_gl), dimension(nnod_new), intent(inout) i8X_new)
Definition at line 271 of file set_from_recv_buf_rev.f90.
Referenced by select_copy_from_recv::sel_cppy_from_recv_buf_i8().
set_from_recv_buf_rev_int()
subroutine set_from_recv_buf_rev::set_from_recv_buf_rev_int (integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) nnod_recv, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, integer (kind=kint), dimension(nnod_recv+1), intent(inout) iWR, integer (kind=kint), dimension(nnod_new), intent(inout) iX_new)
Definition at line 245 of file set_from_recv_buf_rev.f90.
Referenced by select_copy_from_recv::sel_cppy_from_recv_buf_int().
set_from_recv_buf_rev_n()
subroutine set_from_recv_buf_rev::set_from_recv_buf_rev_n (integer(kind = kint), intent(in) NB, integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) nnod_recv, integer(kind = kint), dimension(nnod_new), intent(in) irev_import, real (kind=kreal), dimension(nb*(nnod_recv+1)), intent(inout) WR, real (kind=kreal), dimension(nb*nnod_new), intent(inout) X_new)
Definition at line 211 of file set_from_recv_buf_rev.f90.
Referenced by sel_spherical_srs::sel_calypso_from_recv_n(), and select_copy_from_recv::sel_cppy_from_recv_buf_n().
set_reverse_import_table()
subroutine set_from_recv_buf_rev::set_reverse_import_table (integer(kind = kint), intent(in) nnod_new, integer(kind = kint), intent(in) nnod_recv, integer(kind = kint), dimension(nnod_recv), intent(in) inod_import, integer(kind = kint), dimension(nnod_new), intent(inout) irev_import)
Definition at line 52 of file set_from_recv_buf_rev.f90.
Referenced by parallel_load_data_4_sph::sph_index_flags_and_params(), and parallel_load_data_4_sph::sph_rj_index_flags_and_params().