CALYPSO: t_sph_fftpack5 Module Reference
t_sph_fftpack5 Module Reference
Fourier transform using FFTPACK5.
Data Types
type work_for_fftpack
Structure to use ISPACK.
Functions/Subroutines
subroutine init_sph_fftpack5 (sph_rtp, comm_rtp, ncomp_bwd, ncomp_fwd, fftpack_t)
subroutine finalize_sph_fftpack5 (fftpack_t)
subroutine verify_sph_fftpack5 (sph_rtp, comm_rtp, ncomp_bwd, ncomp_fwd, fftpack_t)
subroutine, private alloc_work_4_fftpack (Ncomp, Nfft, fftpack_t)
subroutine, private alloc_const_4_fftpack (nfft, fftpack_t)
subroutine, private dealloc_work_4_fftpack (fftpack_t)
subroutine, private dealloc_const_4_fftpack (fftpack_t)
Detailed Description
Fourier transform using FFTPACK5.
      subroutine init_sph_FFTPACK5(sph_rtp, comm_rtp,                 &
     &                             ncomp_bwd, ncomp_fwd, fftpack_t)
      subroutine finalize_sph_FFTPACK5(fftpack_t)
      subroutine verify_sph_FFTPACK5(sph_rtp, comm_rtp,               &
     &                               ncomp_bwd, ncomp_fwd, fftpack_t)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_comm_tbl), intent(in) :: comm_rtp
        type(work_for_fftpack), intent(inout) :: fftpack_t
Parameters
Nsmp Number of SMP processors
Nstacksmp(0:Nsmp) End number for each SMP process
M Number of components for Fourier transforms
Nfft Data length for eadh FFT
X(M,Nfft) Data for Fourier transform
Function/Subroutine Documentation
alloc_const_4_fftpack()
subroutine, private t_sph_fftpack5::alloc_const_4_fftpack (integer(kind = kint), intent(in) nfft, type(work_for_fftpack), intent(inout) fftpack_t) private
Definition at line 167 of file t_sph_FFTPACK5.f90.
References m_constants::ifour, and m_constants::two.
Referenced by init_sph_fftpack5(), and verify_sph_fftpack5().
alloc_work_4_fftpack()
subroutine, private t_sph_fftpack5::alloc_work_4_fftpack (integer(kind = kint), intent(in) Ncomp, integer(kind = kint), intent(in) Nfft, type(work_for_fftpack), intent(inout) fftpack_t) private
Definition at line 152 of file t_sph_FFTPACK5.f90.
Referenced by init_sph_fftpack5(), and verify_sph_fftpack5().
dealloc_const_4_fftpack()
subroutine, private t_sph_fftpack5::dealloc_const_4_fftpack (type(work_for_fftpack), intent(inout) fftpack_t) private
Definition at line 196 of file t_sph_FFTPACK5.f90.
Referenced by finalize_sph_fftpack5(), and verify_sph_fftpack5().
dealloc_work_4_fftpack()
subroutine, private t_sph_fftpack5::dealloc_work_4_fftpack (type(work_for_fftpack), intent(inout) fftpack_t) private
Definition at line 185 of file t_sph_FFTPACK5.f90.
Referenced by finalize_sph_fftpack5(), and verify_sph_fftpack5().
finalize_sph_fftpack5()
subroutine t_sph_fftpack5::finalize_sph_fftpack5 (type(work_for_fftpack), intent(inout) fftpack_t)
Definition at line 96 of file t_sph_FFTPACK5.f90.
References t_sph_comm_table_from_fft::dealloc_comm_table_sph_fft(), dealloc_const_4_fftpack(), and dealloc_work_4_fftpack().
Referenced by t_sph_fft_selector::finalize_sph_fft_select().
init_sph_fftpack5()
subroutine t_sph_fftpack5::init_sph_fftpack5 (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), intent(in) ncomp_fwd, type(work_for_fftpack), intent(inout) fftpack_t)
Definition at line 70 of file t_sph_FFTPACK5.f90.
References alloc_const_4_fftpack(), alloc_work_4_fftpack(), m_machine_parameter::np_smp, and rfftmi().
Referenced by sph_prt_fftpack5::init_prt_fftpack5(), and sph_rtp_fftpack5::init_rtp_fftpack5().
verify_sph_fftpack5()
subroutine t_sph_fftpack5::verify_sph_fftpack5 (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), intent(in) ncomp_fwd, type(work_for_fftpack), intent(inout) fftpack_t)
Definition at line 109 of file t_sph_FFTPACK5.f90.
References alloc_const_4_fftpack(), alloc_work_4_fftpack(), dealloc_const_4_fftpack(), dealloc_work_4_fftpack(), m_machine_parameter::np_smp, and rfftmi().
Referenced by sph_prt_fftpack5::verify_prt_fftpack5(), and sph_rtp_fftpack5::verify_rtp_fftpack5().