CALYPSO: gz_element_file_io Module Reference
gz_element_file_io Module Reference
File IO for element communication table.
Functions/Subroutines
subroutine gz_input_element_file (id_rank, file_name, ele_mesh_IO, ierr)
subroutine gz_input_surface_file (id_rank, file_name, surf_mesh_IO, ierr)
subroutine gz_input_edge_file (id_rank, file_name, edge_mesh_IO, ierr)
subroutine gz_output_element_file (id_rank, file_name, ele_mesh_IO)
subroutine gz_output_surface_file (id_rank, file_name, surf_mesh_IO)
subroutine gz_output_edge_file (id_rank, file_name, edge_mesh_IO)
Variables
type(buffer_4_gzip), private zbuf_e
Detailed Description
File IO for element communication table.
      subroutine gz_input_element_file                                &
     &         (id_rank, file_name, ele_mesh_IO, ierr)
      subroutine gz_input_surface_file                                &
     &         (id_rank, file_name, surf_mesh_IO, ierr)
      subroutine gz_input_edge_file                                   &
     &         (id_rank, file_name, edge_mesh_IO, ierr)
        type(surf_edge_IO_file), intent(inout) :: ele_mesh_IO
        type(surf_edge_IO_file), intent(inout) :: surf_mesh_IO
        type(surf_edge_IO_file), intent(inout) :: edge_mesh_IO
      subroutine gz_output_element_file                               &
     &         (id_rank, file_name, ele_mesh_IO)
      subroutine gz_output_surface_file                               &
     &         (id_rank, file_name, surf_mesh_IO)
      subroutine gz_output_edge_file                                  &
     &         (id_rank, file_name, edge_mesh_IO)
        type(surf_edge_IO_file), intent(in) :: ele_mesh_IO
        type(surf_edge_IO_file), intent(in) :: surf_mesh_IO
        type(surf_edge_IO_file), intent(in) :: edge_mesh_IO
Parameters
id_rank MPI rank
Function/Subroutine Documentation
gz_input_edge_file()
subroutine gz_element_file_io::gz_input_edge_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(inout) edge_mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 104 of file gz_element_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), gz_edge_data_io::gz_read_edge_connection(), m_machine_parameter::i_debug, skip_gz_comment::open_rd_gzfile_a(), and zbuf_e.
Referenced by element_mesh_io_select::sel_read_edge_mesh().
gz_input_element_file()
subroutine gz_element_file_io::gz_input_element_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(inout) ele_mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 52 of file gz_element_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), gz_element_data_io::gz_read_element_comm_table(), m_machine_parameter::i_debug, skip_gz_comment::open_rd_gzfile_a(), and zbuf_e.
Referenced by element_mesh_io_select::sel_read_ele_mesh().
gz_input_surface_file()
subroutine gz_element_file_io::gz_input_surface_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(inout) surf_mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 78 of file gz_element_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), gz_surface_data_io::gz_read_surface_connection(), m_machine_parameter::i_debug, skip_gz_comment::open_rd_gzfile_a(), and zbuf_e.
Referenced by element_mesh_io_select::sel_read_surf_mesh().
gz_output_edge_file()
subroutine gz_element_file_io::gz_output_edge_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(in) edge_mesh_IO)
Definition at line 181 of file gz_element_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), gz_edge_data_io::gz_write_edge_connection(), m_machine_parameter::i_debug, skip_gz_comment::open_wt_gzfile_a(), and zbuf_e.
Referenced by element_mesh_io_select::sel_write_edge_mesh_file().
gz_output_element_file()
subroutine gz_element_file_io::gz_output_element_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(in) ele_mesh_IO)
Definition at line 131 of file gz_element_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), gz_element_data_io::gz_write_element_comm_table(), m_machine_parameter::i_debug, skip_gz_comment::open_wt_gzfile_a(), and zbuf_e.
Referenced by element_mesh_io_select::sel_write_ele_mesh_file().
gz_output_surface_file()
subroutine gz_element_file_io::gz_output_surface_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(in) surf_mesh_IO)
Definition at line 156 of file gz_element_file_IO.f90.
References skip_gz_comment::close_gzfile_a(), gz_surface_data_io::gz_write_surface_connection(), m_machine_parameter::i_debug, skip_gz_comment::open_wt_gzfile_a(), and zbuf_e.
Referenced by element_mesh_io_select::sel_write_surf_mesh_file().
Variable Documentation
zbuf_e
type(buffer_4_gzip), private gz_element_file_io::zbuf_e private
Definition at line 44 of file gz_element_file_IO.f90.
Referenced by gz_input_edge_file(), gz_input_element_file(), gz_input_surface_file(), gz_output_edge_file(), gz_output_element_file(), and gz_output_surface_file().