CALYPSO: t_viewer_ele_grp_surface Module Reference
t_viewer_ele_grp_surface Module Reference
Data Types
type viewer_ele_grp_surface
Functions/Subroutines
subroutine alloc_n_iso_surf_4_ele_grp (ele_grp, mgd_sf_grp)
subroutine alloc_iso_surf_4_egrp_m (mgd_sf_grp)
subroutine alloc_iso_surf_4_sgrp_m (surf_grp, mgd_sf_grp)
subroutine dealloc_n_iso_surf_4_ele_grp (mgd_sf_grp)
subroutine dealloc_iso_surf_4_egrp_m (mgd_sf_grp)
subroutine dealloc_iso_surf_4_sgrp_m (mgd_sf_grp)
subroutine check_viewer_isurf_4_ele_grp (ele_grp, mgd_sf_grp)
subroutine check_viewer_isuf_4_surf_grp (surf_grp, mgd_sf_grp)
Function/Subroutine Documentation
alloc_iso_surf_4_egrp_m()
subroutine t_viewer_ele_grp_surface::alloc_iso_surf_4_egrp_m (type(viewer_ele_grp_surface), intent(inout) mgd_sf_grp)
Definition at line 62 of file t_viewer_ele_grp_surface.f90.
Referenced by const_merged_surf_4_group::const_merged_surface_4_ele_grp().
alloc_iso_surf_4_sgrp_m()
subroutine t_viewer_ele_grp_surface::alloc_iso_surf_4_sgrp_m (type(surface_group_data), intent(in) surf_grp, type(viewer_ele_grp_surface), intent(inout) mgd_sf_grp)
Definition at line 76 of file t_viewer_ele_grp_surface.f90.
Referenced by const_merged_surf_4_group::const_merged_surface_4_sf_grp().
alloc_n_iso_surf_4_ele_grp()
subroutine t_viewer_ele_grp_surface::alloc_n_iso_surf_4_ele_grp (type(group_data), intent(in) ele_grp, type(viewer_ele_grp_surface), intent(inout) mgd_sf_grp)
Definition at line 44 of file t_viewer_ele_grp_surface.f90.
Referenced by const_merged_surf_4_group::const_merged_surface_4_ele_grp().
check_viewer_isuf_4_surf_grp()
subroutine t_viewer_ele_grp_surface::check_viewer_isuf_4_surf_grp (type(surface_group_data), intent(in) surf_grp, type(viewer_ele_grp_surface), intent(in) mgd_sf_grp)
Definition at line 147 of file t_viewer_ele_grp_surface.f90.
check_viewer_isurf_4_ele_grp()
subroutine t_viewer_ele_grp_surface::check_viewer_isurf_4_ele_grp (type(group_data), intent(in) ele_grp, type(viewer_ele_grp_surface), intent(in) mgd_sf_grp)
Definition at line 123 of file t_viewer_ele_grp_surface.f90.
dealloc_iso_surf_4_egrp_m()
subroutine t_viewer_ele_grp_surface::dealloc_iso_surf_4_egrp_m (type(viewer_ele_grp_surface), intent(inout) mgd_sf_grp)
Definition at line 102 of file t_viewer_ele_grp_surface.f90.
Referenced by const_merged_surf_4_group::const_merged_surface_4_ele_grp(), and const_kemoview_mesh::const_surf_mesh_4_viewer().
dealloc_iso_surf_4_sgrp_m()
subroutine t_viewer_ele_grp_surface::dealloc_iso_surf_4_sgrp_m (type(viewer_ele_grp_surface), intent(inout) mgd_sf_grp)
Definition at line 112 of file t_viewer_ele_grp_surface.f90.
Referenced by const_kemoview_mesh::const_surf_mesh_4_viewer().
dealloc_n_iso_surf_4_ele_grp()
subroutine t_viewer_ele_grp_surface::dealloc_n_iso_surf_4_ele_grp (type(viewer_ele_grp_surface), intent(inout) mgd_sf_grp)
Definition at line 91 of file t_viewer_ele_grp_surface.f90.
Referenced by const_kemoview_mesh::const_surf_mesh_4_viewer().