CALYPSO: bcast_file_io_parameter Module Reference
bcast_file_io_parameter Module Reference
Structure for file information (prefix, format, IO flag)
Functions/Subroutines
subroutine bcast_field_io_parameter (file_param)
subroutine bcast_fem_file_io_flags (FEM_mesh_flags)
Detailed Description
Structure for file information (prefix, format, IO flag)
      subroutine bcast_field_IO_parameter(file_param)
        type(field_IO_params), intent(inout) :: file_param
      subroutine bcast_FEM_file_IO_flags(FEM_mesh_flags)
        type(FEM_file_IO_flags), intent(inout) :: FEM_mesh_flags
Function/Subroutine Documentation
bcast_fem_file_io_flags()
subroutine bcast_file_io_parameter::bcast_fem_file_io_flags (type(fem_file_io_flags), intent(inout) FEM_mesh_flags)
Definition at line 48 of file bcast_file_IO_parameter.f90.
References calypso_mpi_int::calypso_mpi_bcast_one_int().
bcast_field_io_parameter()
subroutine bcast_file_io_parameter::bcast_field_io_parameter (type(field_io_params), intent(inout) file_param)
Definition at line 30 of file bcast_file_IO_parameter.f90.
References calypso_mpi_char::calypso_mpi_bcast_character(), calypso_mpi_int::calypso_mpi_bcast_one_int(), transfer_to_long_integers::cast_long(), and m_precision::kchara.
Referenced by set_control_newsph::bcast_ctl_param_newsph().