CALYPSO: t_ctl_data_mhd_forces Module Reference
t_ctl_data_mhd_forces Module Reference
Data Types
type coriolis_control
Structure for Coriolis force.
type forces_control
Structure for force list.
type gravity_control
Structure for gravity definistion.
type magneto_convection_control
Structure for Coriolis force.
Functions/Subroutines
subroutine read_forces_ctl (id_control, hd_block, frc_ctl, c_buf)
subroutine read_gravity_ctl (id_control, hd_block, g_ctl, c_buf)
subroutine read_coriolis_ctl (id_control, hd_block, cor_ctl, c_buf)
subroutine read_magneto_ctl (id_control, hd_block, mcv_ctl, c_buf)
subroutine bcast_forces_ctl (frc_ctl)
subroutine bcast_gravity_ctl (g_ctl)
subroutine bcast_coriolis_ctl (cor_ctl)
subroutine bcast_magneto_ctl (mcv_ctl)
subroutine dealloc_name_force_ctl (frc_ctl)
subroutine dealloc_gravity_ctl (g_ctl)
subroutine dealloc_coriolis_ctl (cor_ctl)
subroutine dealloc_magneto_ctl (mcv_ctl)
Variables
character(len=kchara), parameter, private hd_num_forces = 'force_ctl'
character(len=kchara), parameter, private hd_fem_gravity_mode = 'FEM_gravity_model_ctl'
character(len=kchara), parameter, private hd_gravity_type = 'gravity_type_ctl'
character(len=kchara), parameter, private hd_gravity_vect = 'gravity_vec'
character(len=kchara), parameter, private hd_fem_coriolis_model = 'FEM_Coriolis_model_ctl'
character(len=kchara), parameter, private hd_fem_coriolis_imp = 'FEM_Coriolis_implicit_ctl'
character(len=kchara), parameter hd_rotation_vec = 'rotation_vec'
character(len=kchara), parameter, private hd_filetered_induction = 'filtered_induction_ctl'
character(len=kchara), parameter, private hd_magneto_cv = 'magneto_cv_ctl'
character(len=kchara), parameter, private hd_magne_vect = 'ext_magne_vec'
Function/Subroutine Documentation
bcast_coriolis_ctl()
subroutine t_ctl_data_mhd_forces::bcast_coriolis_ctl (type(coriolis_control), intent(inout) cor_ctl)
Definition at line 357 of file t_ctl_data_mhd_forces.f90.
References bcast_control_arrays::bcast_ctl_array_cr(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by t_ctl_data_mhd_model::bcast_sph_mhd_model().
bcast_forces_ctl()
subroutine t_ctl_data_mhd_forces::bcast_forces_ctl (type(forces_control), intent(inout) frc_ctl)
Definition at line 326 of file t_ctl_data_mhd_forces.f90.
References bcast_control_arrays::bcast_ctl_array_c1(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by t_ctl_data_mhd_model::bcast_sph_mhd_model().
bcast_gravity_ctl()
subroutine t_ctl_data_mhd_forces::bcast_gravity_ctl (type(gravity_control), intent(inout) g_ctl)
Definition at line 341 of file t_ctl_data_mhd_forces.f90.
References bcast_control_arrays::bcast_ctl_array_cr(), bcast_control_arrays::bcast_ctl_type_c1(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by t_ctl_data_mhd_model::bcast_sph_mhd_model().
bcast_magneto_ctl()
subroutine t_ctl_data_mhd_forces::bcast_magneto_ctl (type(magneto_convection_control), intent(inout) mcv_ctl)
Definition at line 372 of file t_ctl_data_mhd_forces.f90.
References bcast_control_arrays::bcast_ctl_array_cr(), bcast_control_arrays::bcast_ctl_type_c1(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by t_ctl_data_mhd_model::bcast_sph_mhd_model().
dealloc_coriolis_ctl()
subroutine t_ctl_data_mhd_forces::dealloc_coriolis_ctl (type(coriolis_control), intent(inout) cor_ctl)
Definition at line 415 of file t_ctl_data_mhd_forces.f90.
References t_control_array_charareal::dealloc_control_array_c_r().
Referenced by t_ctl_data_mhd_model::dealloc_sph_mhd_model().
dealloc_gravity_ctl()
subroutine t_ctl_data_mhd_forces::dealloc_gravity_ctl (type(gravity_control), intent(inout) g_ctl)
Definition at line 402 of file t_ctl_data_mhd_forces.f90.
References t_control_array_charareal::dealloc_control_array_c_r().
Referenced by t_ctl_data_mhd_model::dealloc_sph_mhd_model().
dealloc_magneto_ctl()
subroutine t_ctl_data_mhd_forces::dealloc_magneto_ctl (type(magneto_convection_control), intent(inout) mcv_ctl)
Definition at line 427 of file t_ctl_data_mhd_forces.f90.
References t_control_array_charareal::dealloc_control_array_c_r().
Referenced by t_ctl_data_mhd_model::dealloc_sph_mhd_model().
dealloc_name_force_ctl()
subroutine t_ctl_data_mhd_forces::dealloc_name_force_ctl (type(forces_control), intent(inout) frc_ctl)
Definition at line 390 of file t_ctl_data_mhd_forces.f90.
References t_control_array_character::dealloc_control_array_chara().
Referenced by t_ctl_data_mhd_model::dealloc_sph_mhd_model().
read_coriolis_ctl()
subroutine t_ctl_data_mhd_forces::read_coriolis_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(coriolis_control), intent(inout) cor_ctl, type(buffer_for_control), intent(inout) c_buf)
Definition at line 265 of file t_ctl_data_mhd_forces.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_fem_coriolis_imp, hd_fem_coriolis_model, hd_rotation_vec, t_read_control_elements::load_one_line_from_control(), t_control_array_character::read_chara_ctl_type(), and t_control_array_charareal::read_control_array_c_r().
Referenced by t_ctl_data_mhd_model::read_sph_mhd_model().
read_forces_ctl()
subroutine t_ctl_data_mhd_forces::read_forces_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(forces_control), intent(inout) frc_ctl, type(buffer_for_control), intent(inout) c_buf)
Definition at line 212 of file t_ctl_data_mhd_forces.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_num_forces, t_read_control_elements::load_one_line_from_control(), and t_control_array_character::read_control_array_c1().
Referenced by t_ctl_data_mhd_model::read_sph_mhd_model().
read_gravity_ctl()
subroutine t_ctl_data_mhd_forces::read_gravity_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(gravity_control), intent(inout) g_ctl, type(buffer_for_control), intent(inout) c_buf)
Definition at line 236 of file t_ctl_data_mhd_forces.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_fem_gravity_mode, hd_gravity_type, hd_gravity_vect, t_read_control_elements::load_one_line_from_control(), t_control_array_character::read_chara_ctl_type(), and t_control_array_charareal::read_control_array_c_r().
Referenced by t_ctl_data_mhd_model::read_sph_mhd_model().
read_magneto_ctl()
subroutine t_ctl_data_mhd_forces::read_magneto_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(magneto_convection_control), intent(inout) mcv_ctl, type(buffer_for_control), intent(inout) c_buf)
Definition at line 295 of file t_ctl_data_mhd_forces.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_filetered_induction, hd_magne_vect, hd_magneto_cv, t_read_control_elements::load_one_line_from_control(), t_control_array_character::read_chara_ctl_type(), and t_control_array_charareal::read_control_array_c_r().
Referenced by t_ctl_data_mhd_model::read_sph_mhd_model().
Variable Documentation
hd_fem_coriolis_imp
character(len=kchara), parameter, private t_ctl_data_mhd_forces::hd_fem_coriolis_imp = 'FEM_Coriolis_implicit_ctl' private
Definition at line 184 of file t_ctl_data_mhd_forces.f90.
Referenced by read_coriolis_ctl().
hd_fem_coriolis_model
character(len=kchara), parameter, private t_ctl_data_mhd_forces::hd_fem_coriolis_model = 'FEM_Coriolis_model_ctl' private
Definition at line 182 of file t_ctl_data_mhd_forces.f90.
Referenced by read_coriolis_ctl().
hd_fem_gravity_mode
character(len=kchara), parameter, private t_ctl_data_mhd_forces::hd_fem_gravity_mode = 'FEM_gravity_model_ctl' private
Definition at line 173 of file t_ctl_data_mhd_forces.f90.
Referenced by read_gravity_ctl().
hd_filetered_induction
character(len=kchara), parameter, private t_ctl_data_mhd_forces::hd_filetered_induction = 'filtered_induction_ctl' private
Definition at line 191 of file t_ctl_data_mhd_forces.f90.
Referenced by read_magneto_ctl().
hd_gravity_type
character(len=kchara), parameter, private t_ctl_data_mhd_forces::hd_gravity_type = 'gravity_type_ctl' private
Definition at line 175 of file t_ctl_data_mhd_forces.f90.
Referenced by read_gravity_ctl().
hd_gravity_vect
character(len=kchara), parameter, private t_ctl_data_mhd_forces::hd_gravity_vect = 'gravity_vec' private
Definition at line 177 of file t_ctl_data_mhd_forces.f90.
Referenced by read_gravity_ctl().
hd_magne_vect
character(len=kchara), parameter, private t_ctl_data_mhd_forces::hd_magne_vect = 'ext_magne_vec' private
Definition at line 195 of file t_ctl_data_mhd_forces.f90.
Referenced by read_magneto_ctl().
hd_magneto_cv
character(len=kchara), parameter, private t_ctl_data_mhd_forces::hd_magneto_cv = 'magneto_cv_ctl' private
Definition at line 193 of file t_ctl_data_mhd_forces.f90.
Referenced by read_magneto_ctl().
hd_num_forces
character(len=kchara), parameter, private t_ctl_data_mhd_forces::hd_num_forces = 'force_ctl' private
Definition at line 168 of file t_ctl_data_mhd_forces.f90.
Referenced by read_forces_ctl().
hd_rotation_vec
character(len=kchara), parameter t_ctl_data_mhd_forces::hd_rotation_vec = 'rotation_vec'
Definition at line 186 of file t_ctl_data_mhd_forces.f90.
Referenced by read_coriolis_ctl().