CALYPSO: t_control_1d_layering Module Reference
t_control_1d_layering Module Reference
Set control data for domain decomposition for spherical transform.
Data Types
type layering_group_list
Structure for layering information.
Functions/Subroutines
subroutine alloc_layering_group (num_layer, layering)
subroutine dealloc_layering_group (layering)
subroutine set_group_by_layering_list (name_prefix, layer_list_ctl, layering)
subroutine set_group_by_equidivide (name_prefix, istart, iend, num_layer_ctl, layering)
Detailed Description
Set control data for domain decomposition for spherical transform.
      subroutine alloc_layering_group(num_layer, layering)
      subroutine dealloc_layering_group(layering)
      subroutine set_group_by_layering_list                         &
     &         (name_prefix, layer_list_ctl, layering)
      subroutine set_group_by_equidivide                            &
     &         (name_prefix, istart, iend, num_layer_ctl, layering)
        type(read_integer_item), intent(in) :: num_layer_ctl
        type(ctl_array_i2), intent(in) :: layer_list_ctl
        type(layering_group_list), intent(inout) :: layering
Function/Subroutine Documentation
alloc_layering_group()
subroutine t_control_1d_layering::alloc_layering_group (integer(kind = kint), intent(in) num_layer, type(layering_group_list), intent(inout) layering)
Definition at line 44 of file t_control_1D_layering.f90.
Referenced by t_ctl_params_gen_sph_shell::set_control_4_sgs_shell(), set_group_by_equidivide(), and set_group_by_layering_list().
dealloc_layering_group()
subroutine t_control_1d_layering::dealloc_layering_group (type(layering_group_list), intent(inout) layering)
Definition at line 63 of file t_control_1D_layering.f90.
Referenced by t_const_spherical_grid::dealloc_gen_mesh_params().
set_group_by_equidivide()
subroutine t_control_1d_layering::set_group_by_equidivide (character(len=kchara), intent(in) name_prefix, integer(kind = kint), intent(in) istart, integer(kind = kint), intent(in) iend, type(read_integer_item), intent(in) num_layer_ctl, type(layering_group_list), intent(inout) layering)
Definition at line 101 of file t_control_1D_layering.f90.
References set_parallel_file_name::add_index_after_name(), alloc_layering_group(), and cal_minmax_and_stacks::count_number_4_smp().
Referenced by t_ctl_params_gen_sph_shell::set_control_4_sgs_shell().
set_group_by_layering_list()
subroutine t_control_1d_layering::set_group_by_layering_list (character(len=kchara), intent(in) name_prefix, type(ctl_array_i2), intent(in) layer_list_ctl, type(layering_group_list), intent(inout) layering)
Definition at line 76 of file t_control_1D_layering.f90.
References set_parallel_file_name::add_index_after_name(), and alloc_layering_group().
Referenced by t_ctl_params_gen_sph_shell::set_control_4_sgs_shell().