CALYPSO: psf_global_nod_id Module Reference
psf_global_nod_id Module Reference
Set global node ID list for sectioning.
Functions/Subroutines
subroutine psf_global_nod_id_on_edge (numedge, istack_internod, psf_list)
subroutine psf_global_nod_id_on_node (nod_comm, numnod, istack_internod, id_n_on_n)
subroutine const_edge_comm_table_4_psf (node, nod_comm, edge, psf_list)
Detailed Description
Set global node ID list for sectioning.
      subroutine psf_global_nod_id_on_edge                            &
     &         (numedge, istack_internod, psf_list)
      subroutine psf_global_nod_id_on_node                            &
     &         (nod_comm, numnod, istack_internod, id_n_on_n)
      subroutine const_edge_comm_table_4_psf                          &
     &         (node, nod_comm, edge, psf_list)
Function/Subroutine Documentation
const_edge_comm_table_4_psf()
subroutine psf_global_nod_id::const_edge_comm_table_4_psf (type(node_data), intent(in) node, type(communication_table), intent(in) nod_comm, type(edge_data), intent(in) edge, type(sectioning_list), intent(inout) psf_list)
Definition at line 102 of file psf_global_nod_id.f90.
References t_edge_data::alloc_edge_connect(), t_edge_data::alloc_edge_geometory(), const_element_comm_tables::const_edge_comm_table(), t_edge_data::dealloc_edge_connect(), t_edge_data::dealloc_edge_geometory(), and m_geometry_constants::num_linear_edge.
Referenced by set_nodes_for_psf::set_nodes_4_iso(), and set_nodes_for_psf::set_nodes_4_psf().
psf_global_nod_id_on_edge()
subroutine psf_global_nod_id::psf_global_nod_id_on_edge (integer(kind = kint), intent(in) numedge, integer(kind = kint_gl), dimension(0:nprocs), intent(in) istack_internod, type(sectioning_list), intent(inout) psf_list)
Definition at line 32 of file psf_global_nod_id.f90.
References calypso_mpi::my_rank, and solver_sr_type::solver_send_recv_int8_type().
Referenced by set_nodes_for_psf::set_nodes_4_iso(), and set_nodes_for_psf::set_nodes_4_psf().
psf_global_nod_id_on_node()
subroutine psf_global_nod_id::psf_global_nod_id_on_node (type(communication_table), intent(in) nod_comm, integer(kind = kint), intent(in) numnod, integer(kind = kint_gl), dimension(0:nprocs), intent(in) istack_internod, integer(kind = kint_gl), dimension(numnod), intent(inout) id_n_on_n)
Definition at line 75 of file psf_global_nod_id.f90.
References calypso_mpi::my_rank, and solver_sr_type::solver_send_recv_int8_type().
Referenced by set_nodes_for_psf::set_nodes_4_psf().