CALYPSO: cal_sp_rlm_by_vecprod Module Reference
cal_sp_rlm_by_vecprod Module Reference
forward Legendre transform useing vector products
Functions/Subroutines
subroutine cal_vector_sp_rlm_dotprod (nth, g7, gm, r1_1d_rlm_r, r2_1d_rlm_r, Pvw_le, dPvw_le, symp_r, asmp_t, asmp_p, symn_t, symn_p, sp_rlm)
subroutine cal_scalar_sp_rlm_dotprod (nth, g6, Pws_le, symp, sp_rlm)
Detailed Description
forward Legendre transform useing vector products
      subroutine cal_vector_sp_rlm_dotprod(nth, g7, gm,               &
     &          r1_1d_rlm_r, r2_1d_rlm_r, Pvw_le, dPvw_le,            &
     &          symp_r, asmp_t, asmp_p, symn_t, symn_p, sp_rlm)
      subroutine cal_scalar_sp_rlm_dotprod                            &
     &          (nth, g6, Pws_le, symp, sp_rlm)
Function/Subroutine Documentation
cal_scalar_sp_rlm_dotprod()
subroutine cal_sp_rlm_by_vecprod::cal_scalar_sp_rlm_dotprod (integer(kind = kint), intent(in) nth, real (kind=kreal), intent(in) g6, real (kind=kreal), dimension(nth), intent(in) Pws_le, real (kind=kreal), dimension(nth), intent(in) symp, real (kind=kreal), intent(inout) sp_rlm)
Definition at line 70 of file cal_sp_rlm_by_vecprod.f90.
Referenced by legendre_fwd_trans_symmetry::leg_fwd_trans_scalar_sym_org(), and legendre_fwd_trans_sym_spin::leg_fwd_trans_scalar_sym_spin().
cal_vector_sp_rlm_dotprod()
subroutine cal_sp_rlm_by_vecprod::cal_vector_sp_rlm_dotprod (integer(kind = kint), intent(in) nth, real (kind=kreal), intent(in) g7, real (kind=kreal), intent(in) gm, real (kind=kreal), intent(in) r1_1d_rlm_r, real (kind=kreal), intent(in) r2_1d_rlm_r, real (kind=kreal), dimension(nth), intent(in) Pvw_le, real (kind=kreal), dimension(nth), intent(in) dPvw_le, real (kind=kreal), dimension(nth), intent(in) symp_r, real (kind=kreal), dimension(nth), intent(in) asmp_t, real (kind=kreal), dimension(nth), intent(in) asmp_p, real (kind=kreal), dimension(nth), intent(in) symn_t, real (kind=kreal), dimension(nth), intent(in) symn_p, real (kind=kreal), dimension(3), intent(inout) sp_rlm)
Definition at line 31 of file cal_sp_rlm_by_vecprod.f90.
Referenced by legendre_fwd_trans_symmetry::leg_fwd_trans_vector_sym_org(), and legendre_fwd_trans_sym_spin::leg_fwd_trans_vector_sym_spin().