CALYPSO: t_const_wz_coriolis_rtp Module Reference
t_const_wz_coriolis_rtp Module Reference
Evaluate Coriolis term on spherical grid.
Data Types
type spher_average_coriolis
Structure of sphere average of radial coriolis force.
Functions/Subroutines
subroutine alloc_sphere_ave_coriolis (sph_rj, ave_cor)
subroutine dealloc_sphere_ave_coriolis (ave_cor)
subroutine subtract_sphere_ave_coriolis (sph_rtp, sph_rj, is_coriolis, ntot_phys_rj, d_rj, coriolis_rtp, ave_cor)
subroutine ovwrt_rj_coef_prod_vect_smp (sph_rj, coef, i_r, n_point, ntot_phys_rj, d_rj)
subroutine, private clear_rj_degree0_scalar_smp (sph_rj, irj_fld, n_point, ntot_phys_rj, d_rj)
subroutine clear_rj_degree0_vector_smp (sph_rj, irj_fld, n_point, ntot_phys_rj, d_rj)
subroutine, private subtract_sph_ave_coriolis_rtp (sph_rtp, coriolis_rtp, ave_cor)
subroutine, private subtract_sph_ave_coriolis_prt (sph_rtp, coriolis_rtp, ave_cor)
Detailed Description
Evaluate Coriolis term on spherical grid.
      subroutine alloc_sphere_ave_coriolis(sph_rj, ave_cor)
      subroutine dealloc_sphere_ave_coriolis(ave_cor)
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(spher_average_coriolis), intent(inout) :: ave_cor
      subroutine subtract_sphere_ave_coriolis(sph_rtp, sph_rj,        &
     &          is_coriolis, ntot_phys_rj, d_rj, coriolis_rtp,        &
     &          ave_cor)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(spher_average_coriolis), intent(inout) :: ave_cor
      subroutine ovwrt_rj_coef_prod_vect_smp                          &
     &         (sph_rj, coef, i_r, n_point, ntot_phys_rj, d_rj)
      subroutine clear_rj_degree0_vector_smp                          &
     &         (sph_rj, irj_fld, n_point, ntot_phys_rj, d_rj)
        type(sph_rj_grid), intent(in) ::  sph_rj
Parameters
irj_fld Address for spectr data
Function/Subroutine Documentation
alloc_sphere_ave_coriolis()
subroutine t_const_wz_coriolis_rtp::alloc_sphere_ave_coriolis (type(sph_rj_grid), intent(in) sph_rj, type(spher_average_coriolis), intent(inout) ave_cor)
Definition at line 61 of file t_const_wz_coriolis_rtp.f90.
Referenced by init_sphrical_transform_mhd::init_work_4_coriolis().
clear_rj_degree0_scalar_smp()
subroutine, private t_const_wz_coriolis_rtp::clear_rj_degree0_scalar_smp (type(sph_rj_grid), intent(in) sph_rj, integer (kind = kint), intent(in) irj_fld, integer (kind = kint), intent(in) n_point, integer (kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj) private
Definition at line 161 of file t_const_wz_coriolis_rtp.f90.
References m_constants::zero.
Referenced by subtract_sphere_ave_coriolis().
clear_rj_degree0_vector_smp()
subroutine t_const_wz_coriolis_rtp::clear_rj_degree0_vector_smp (type(sph_rj_grid), intent(in) sph_rj, integer (kind = kint), intent(in) irj_fld, integer (kind = kint), intent(in) n_point, integer (kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 185 of file t_const_wz_coriolis_rtp.f90.
References m_constants::zero.
dealloc_sphere_ave_coriolis()
subroutine t_const_wz_coriolis_rtp::dealloc_sphere_ave_coriolis (type(spher_average_coriolis), intent(inout) ave_cor)
Definition at line 80 of file t_const_wz_coriolis_rtp.f90.
ovwrt_rj_coef_prod_vect_smp()
subroutine t_const_wz_coriolis_rtp::ovwrt_rj_coef_prod_vect_smp (type(sph_rj_grid), intent(in) sph_rj, real(kind = kreal), intent(in) coef, integer (kind = kint), intent(in) i_r, integer (kind = kint), intent(in) n_point, integer (kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 141 of file t_const_wz_coriolis_rtp.f90.
References m_machine_parameter::np_smp, and overwrite_prod_const_smp::ovwrt_coef_prod_vect_smp().
Referenced by const_sph_radial_grad::const_pressure_gradient().
subtract_sph_ave_coriolis_prt()
subroutine, private t_const_wz_coriolis_rtp::subtract_sph_ave_coriolis_prt (type(sph_rtp_grid), intent(in) sph_rtp, real(kind = kreal), dimension(sph_rtp%nnod_rtp,3), intent(inout) coriolis_rtp, type(spher_average_coriolis), intent(inout) ave_cor) private
Definition at line 243 of file t_const_wz_coriolis_rtp.f90.
Referenced by subtract_sphere_ave_coriolis().
subtract_sph_ave_coriolis_rtp()
subroutine, private t_const_wz_coriolis_rtp::subtract_sph_ave_coriolis_rtp (type(sph_rtp_grid), intent(in) sph_rtp, real(kind = kreal), dimension(sph_rtp%nnod_rtp,3), intent(inout) coriolis_rtp, type(spher_average_coriolis), intent(inout) ave_cor) private
Definition at line 212 of file t_const_wz_coriolis_rtp.f90.
Referenced by subtract_sphere_ave_coriolis().
subtract_sphere_ave_coriolis()
subroutine t_const_wz_coriolis_rtp::subtract_sphere_ave_coriolis (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_rj_grid), intent(in) sph_rj, integer(kind = kint), intent(in) is_coriolis, integer(kind = kint), intent(in) ntot_phys_rj, real(kind = kreal), dimension(sph_rj%nnod_rj,ntot_phys_rj), intent(inout) d_rj, real(kind = kreal), dimension(sph_rtp%nnod_rtp,3), intent(inout) coriolis_rtp, type(spher_average_coriolis), intent(inout) ave_cor)
Definition at line 91 of file t_const_wz_coriolis_rtp.f90.
References calypso_mpi_real::calypso_mpi_allreduce_real(), clear_rj_degree0_scalar_smp(), subtract_sph_ave_coriolis_prt(), subtract_sph_ave_coriolis_rtp(), and m_constants::zero.