CALYPSO: cal_sph_ele_addresses Module Reference
cal_sph_ele_addresses Module Reference
Set element connectivity for spherical shell grid.
Functions/Subroutines
subroutine reset_local_sph_ele_constants
subroutine set_nele_lc_shell (ip_r, ip_t, stbl)
subroutine set_nele_lc_spole (ip_r, stbl)
subroutine set_nele_lc_npole (ip_r, stbl)
subroutine set_nele_lc_ctr_sph (stbl)
subroutine set_nele_ext_ctr_sph (ip_t, stbl)
subroutine set_nele_center_spole (stbl)
subroutine set_nele_center_npole (stbl)
subroutine set_nele_gl_shell (stbl)
subroutine set_nele_gl_spole (stbl)
subroutine set_nele_gl_npole (stbl)
subroutine set_nele_gl_ctr_sph (stbl)
subroutine cal_sph_local_numele (numele)
integer(kind=kint) function sph_shell_ele_id (ip_r, ip_t, kr, lt, mp, stbl)
integer(kind=kint) function sph_s_pole_ele_id (ip_r, kr, mp, stbl)
integer(kind=kint) function sph_n_pole_ele_id (ip_r, kr, mp, stbl)
integer(kind=kint) function sph_inter_ctr_shell_ele_id (lt, mp, stbl)
integer(kind=kint) function sph_exter_ctr_shell_ele_id (ip_t, lt, mp, stbl)
integer(kind=kint) function sph_inter_ctr_spole_ele_id (mp)
integer(kind=kint) function sph_inter_ctr_npole_ele_id (mp)
integer(kind=kint) function sph_exter_ctr_npole_ele_id (mp)
integer(kind=kint_gl) function global_sph_shell_ele_id (kr, lt, mp, stbl)
integer(kind=kint_gl) function global_sph_s_pole_ele_id (kr, mp, stbl)
integer(kind=kint_gl) function global_sph_n_pole_ele_id (kr, mp, stbl)
integer(kind=kint_gl) function global_ctr_shell_ele_id (lt, mp, stbl)
integer(kind=kint_gl) function global_ctr_spole_ele_id (mp)
integer(kind=kint_gl) function global_ctr_npole_ele_id (mp)
Variables
integer(kind=kint), private nele_lc_shell = 0
integer(kind=kint), private nele_lc_spole = 0
integer(kind=kint), private nele_lc_npole = 0
integer(kind=kint), private nele_lc_ctr_sph = 0
integer(kind=kint), private nele_ext_ctr_sph = 0
integer(kind=kint), private nele_ctr_spole = 0
integer(kind=kint), private nele_ctr_npole = 0
integer(kind=kint_gl) nele_gl_shell = 0
integer(kind=kint_gl) nele_gl_spole = 0
integer(kind=kint_gl) nele_gl_npole = 0
integer(kind=kint_gl) nele_gl_ctr_sph = 0
integer(kind=kint_gl) nele_gl_ctr_spole = 0
integer(kind=kint_gl) nele_gl_ctr_npole = 0
Detailed Description
Set element connectivity for spherical shell grid.
      subroutine reset_local_sph_ele_constants
      subroutine set_nele_lc_shell(ip_r, ip_t, stbl)
      subroutine set_nele_lc_Spole(ip_r, stbl)
      subroutine set_nele_lc_Npole(ip_r, stbl)
      subroutine set_nele_lc_ctr_sph(stbl)
      subroutine set_nele_ext_ctr_sph(ip_t, stbl)
      subroutine set_nele_center_Spole(stbl)
      subroutine set_nele_center_Npole(stbl)
      subroutine set_nele_gl_shell(stbl)
      subroutine set_nele_gl_Spole(stbl)
      subroutine set_nele_gl_Npole(stbl)
      subroutine set_nele_gl_ctr_sph(stbl)
      subroutine cal_sph_local_numele(numele)
      integer(kind = kint) function sph_shell_ele_id                  &
     &                            (ip_r, ip_t, kr, lt, mp, stbl)
      integer(kind = kint) function sph_s_pole_ele_id                 &
     &                            (ip_r, kr, mp, stbl)
      integer(kind = kint) function sph_n_pole_ele_id                 &
     &                            (ip_r, kr, mp, stbl)
      integer(kind = kint) function sph_inter_ctr_shell_ele_id        &
     &                            (lt, mp, stbl)
      integer(kind = kint) function sph_exter_ctr_shell_ele_id        &
     &                            (ip_t, lt, mp, stbl)
      integer(kind = kint) function sph_inter_ctr_spole_ele_id(mp)
      integer(kind = kint) function sph_inter_ctr_npole_ele_id(mp)
      integer(kind = kint) function sph_exter_ctr_npole_ele_id(mp)
      integer(kind = kint_gl) function global_sph_shell_ele_id        &
                                     (kr, lt, mp, stbl)
      integer(kind = kint_gl) function global_sph_s_pole_ele_id       &
     &                               (kr, mp, stbl)
      integer(kind = kint_gl) function global_sph_n_pole_ele_id       &
     &                               (kr, mp, stbl)
      integer(kind = kint_gl) function global_ctr_shell_ele_id        &
     &                               (lt, mp, stbl)
      integer(kind = kint_gl) function global_ctr_spole_ele_id(mp)
      integer(kind = kint_gl) function global_ctr_npole_ele_id(mp)
Function/Subroutine Documentation
cal_sph_local_numele()
subroutine cal_sph_ele_addresses::cal_sph_local_numele (integer(kind = kint), intent(inout) numele)
Definition at line 246 of file cal_sph_ele_addresses.f90.
References nele_ctr_npole, nele_ctr_spole, nele_ext_ctr_sph, nele_lc_ctr_sph, nele_lc_npole, nele_lc_shell, and nele_lc_spole.
Referenced by set_sph_local_element::count_local_elements_sph_mesh().
global_ctr_npole_ele_id()
integer(kind = kint_gl) function cal_sph_ele_addresses::global_ctr_npole_ele_id (integer(kind = kint), intent(in) mp)
Definition at line 452 of file cal_sph_ele_addresses.f90.
References nele_gl_ctr_sph, nele_gl_ctr_spole, nele_gl_npole, nele_gl_shell, and nele_gl_spole.
Referenced by cal_sph_ele_connects::set_exter_center_n_pole_ele(), and cal_sph_ele_connects::set_inter_center_n_pole_ele().
global_ctr_shell_ele_id()
integer(kind = kint_gl) function cal_sph_ele_addresses::global_ctr_shell_ele_id (integer(kind = kint), intent(in) lt, integer(kind = kint), intent(in) mp, type(comm_table_make_sph), intent(in) stbl)
Definition at line 422 of file cal_sph_ele_addresses.f90.
References nele_gl_npole, nele_gl_shell, and nele_gl_spole.
Referenced by cal_sph_ele_connects::set_exter_center_shell_ele(), and cal_sph_ele_connects::set_inter_center_shell_ele().
global_ctr_spole_ele_id()
integer(kind = kint_gl) function cal_sph_ele_addresses::global_ctr_spole_ele_id (integer(kind = kint), intent(in) mp)
Definition at line 439 of file cal_sph_ele_addresses.f90.
References nele_gl_ctr_sph, nele_gl_npole, nele_gl_shell, and nele_gl_spole.
Referenced by cal_sph_ele_connects::set_inter_center_s_pole_ele().
global_sph_n_pole_ele_id()
integer(kind = kint_gl) function cal_sph_ele_addresses::global_sph_n_pole_ele_id (integer(kind = kint), intent(in) kr, integer(kind = kint), intent(in) mp, type(comm_table_make_sph), intent(in) stbl)
Definition at line 406 of file cal_sph_ele_addresses.f90.
References nele_gl_shell, and nele_gl_spole.
Referenced by cal_sph_ele_connects::set_north_pole_element().
global_sph_s_pole_ele_id()
integer(kind = kint_gl) function cal_sph_ele_addresses::global_sph_s_pole_ele_id (integer(kind = kint), intent(in) kr, integer(kind = kint), intent(in) mp, type(comm_table_make_sph), intent(in) stbl)
Definition at line 390 of file cal_sph_ele_addresses.f90.
References nele_gl_shell.
Referenced by cal_sph_ele_connects::set_south_pole_element().
global_sph_shell_ele_id()
integer(kind = kint_gl) function cal_sph_ele_addresses::global_sph_shell_ele_id (integer(kind = kint), intent(in) kr, integer(kind = kint), intent(in) lt, integer(kind = kint), intent(in) mp, type(comm_table_make_sph), intent(in) stbl)
Definition at line 374 of file cal_sph_ele_addresses.f90.
Referenced by cal_sph_ele_connects::set_spherical_shell_element().
reset_local_sph_ele_constants()
subroutine cal_sph_ele_addresses::reset_local_sph_ele_constants
Definition at line 88 of file cal_sph_ele_addresses.f90.
References nele_ctr_npole, nele_ctr_spole, nele_ext_ctr_sph, nele_gl_ctr_npole, nele_gl_ctr_sph, nele_gl_ctr_spole, nele_gl_npole, nele_gl_shell, nele_gl_spole, nele_lc_ctr_sph, nele_lc_npole, nele_lc_shell, and nele_lc_spole.
Referenced by set_sph_local_element::count_local_elements_sph_mesh().
set_nele_center_npole()
subroutine cal_sph_ele_addresses::set_nele_center_npole (type(comm_table_make_sph), intent(in) stbl)
Definition at line 180 of file cal_sph_ele_addresses.f90.
References nele_ctr_npole.
Referenced by set_sph_local_element::count_local_elements_sph_mesh().
set_nele_center_spole()
subroutine cal_sph_ele_addresses::set_nele_center_spole (type(comm_table_make_sph), intent(in) stbl)
Definition at line 170 of file cal_sph_ele_addresses.f90.
References nele_ctr_spole.
Referenced by set_sph_local_element::count_local_elements_sph_mesh().
set_nele_ext_ctr_sph()
subroutine cal_sph_ele_addresses::set_nele_ext_ctr_sph (integer(kind = kint), intent(in) ip_t, type(comm_table_make_sph), intent(in) stbl)
Definition at line 158 of file cal_sph_ele_addresses.f90.
References nele_ext_ctr_sph.
Referenced by set_sph_local_element::count_local_elements_sph_mesh().
set_nele_gl_ctr_sph()
subroutine cal_sph_ele_addresses::set_nele_gl_ctr_sph (type(comm_table_make_sph), intent(in) stbl)
Definition at line 230 of file cal_sph_ele_addresses.f90.
References nele_gl_ctr_npole, nele_gl_ctr_sph, and nele_gl_ctr_spole.
Referenced by set_sph_local_element::count_local_elements_sph_mesh().
set_nele_gl_npole()
subroutine cal_sph_ele_addresses::set_nele_gl_npole (type(comm_table_make_sph), intent(in) stbl)
Definition at line 218 of file cal_sph_ele_addresses.f90.
References nele_gl_npole.
Referenced by set_sph_local_element::count_local_elements_sph_mesh().
set_nele_gl_shell()
subroutine cal_sph_ele_addresses::set_nele_gl_shell (type(comm_table_make_sph), intent(in) stbl)
Definition at line 191 of file cal_sph_ele_addresses.f90.
References nele_gl_shell.
Referenced by set_sph_local_element::count_local_elements_sph_mesh().
set_nele_gl_spole()
subroutine cal_sph_ele_addresses::set_nele_gl_spole (type(comm_table_make_sph), intent(in) stbl)
Definition at line 205 of file cal_sph_ele_addresses.f90.
References nele_gl_spole.
Referenced by set_sph_local_element::count_local_elements_sph_mesh().
set_nele_lc_ctr_sph()
subroutine cal_sph_ele_addresses::set_nele_lc_ctr_sph (type(comm_table_make_sph), intent(in) stbl)
Definition at line 146 of file cal_sph_ele_addresses.f90.
References nele_lc_ctr_sph.
Referenced by set_sph_local_element::count_local_elements_sph_mesh().
set_nele_lc_npole()
subroutine cal_sph_ele_addresses::set_nele_lc_npole (integer(kind = kint), intent(in) ip_r, type(comm_table_make_sph), intent(in) stbl)
Definition at line 135 of file cal_sph_ele_addresses.f90.
References nele_lc_npole.
Referenced by set_sph_local_element::count_local_elements_sph_mesh().
set_nele_lc_shell()
subroutine cal_sph_ele_addresses::set_nele_lc_shell (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, type(comm_table_make_sph), intent(in) stbl)
Definition at line 111 of file cal_sph_ele_addresses.f90.
References nele_lc_shell.
Referenced by set_sph_local_element::count_local_elements_sph_mesh().
set_nele_lc_spole()
subroutine cal_sph_ele_addresses::set_nele_lc_spole (integer(kind = kint), intent(in) ip_r, type(comm_table_make_sph), intent(in) stbl)
Definition at line 123 of file cal_sph_ele_addresses.f90.
References nele_lc_spole.
Referenced by set_sph_local_element::count_local_elements_sph_mesh().
sph_exter_ctr_npole_ele_id()
integer(kind = kint) function cal_sph_ele_addresses::sph_exter_ctr_npole_ele_id (integer(kind = kint), intent(in) mp)
Definition at line 360 of file cal_sph_ele_addresses.f90.
References nele_ext_ctr_sph, nele_lc_npole, nele_lc_shell, and nele_lc_spole.
Referenced by set_sph_ele_group::set_ele_grp_item_4_center(), and cal_sph_ele_connects::set_exter_center_n_pole_ele().
sph_exter_ctr_shell_ele_id()
integer(kind = kint) function cal_sph_ele_addresses::sph_exter_ctr_shell_ele_id (integer(kind = kint), intent(in) ip_t, integer(kind = kint), intent(in) lt, integer(kind = kint), intent(in) mp, type(comm_table_make_sph), intent(in) stbl)
Definition at line 320 of file cal_sph_ele_addresses.f90.
References nele_lc_npole, nele_lc_shell, and nele_lc_spole.
Referenced by set_sph_ele_group::set_ele_grp_item_4_center(), and cal_sph_ele_connects::set_exter_center_shell_ele().
sph_inter_ctr_npole_ele_id()
integer(kind = kint) function cal_sph_ele_addresses::sph_inter_ctr_npole_ele_id (integer(kind = kint), intent(in) mp)
Definition at line 347 of file cal_sph_ele_addresses.f90.
References nele_ctr_spole, nele_lc_ctr_sph, nele_lc_npole, nele_lc_shell, and nele_lc_spole.
Referenced by set_sph_ele_group::set_ele_grp_item_4_center(), and cal_sph_ele_connects::set_inter_center_n_pole_ele().
sph_inter_ctr_shell_ele_id()
integer(kind = kint) function cal_sph_ele_addresses::sph_inter_ctr_shell_ele_id (integer(kind = kint), intent(in) lt, integer(kind = kint), intent(in) mp, type(comm_table_make_sph), intent(in) stbl)
Definition at line 305 of file cal_sph_ele_addresses.f90.
References nele_lc_npole, nele_lc_shell, and nele_lc_spole.
Referenced by set_sph_ele_group::set_ele_grp_item_4_center(), and cal_sph_ele_connects::set_inter_center_shell_ele().
sph_inter_ctr_spole_ele_id()
integer(kind = kint) function cal_sph_ele_addresses::sph_inter_ctr_spole_ele_id (integer(kind = kint), intent(in) mp)
Definition at line 334 of file cal_sph_ele_addresses.f90.
References nele_lc_ctr_sph, nele_lc_npole, nele_lc_shell, and nele_lc_spole.
Referenced by set_sph_ele_group::set_ele_grp_item_4_center(), and cal_sph_ele_connects::set_inter_center_s_pole_ele().
sph_n_pole_ele_id()
integer(kind = kint) function cal_sph_ele_addresses::sph_n_pole_ele_id (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) kr, integer(kind = kint), intent(in) mp, type(comm_table_make_sph), intent(in) stbl)
Definition at line 290 of file cal_sph_ele_addresses.f90.
References nele_lc_shell, and nele_lc_spole.
Referenced by set_sph_ele_group::set_ele_grp_item_on_sphere(), cal_sph_ele_connects::set_north_pole_element(), and set_sph_surf_group::set_surf_grp_item_on_sphere().
sph_s_pole_ele_id()
integer(kind = kint) function cal_sph_ele_addresses::sph_s_pole_ele_id (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) kr, integer(kind = kint), intent(in) mp, type(comm_table_make_sph), intent(in) stbl)
Definition at line 275 of file cal_sph_ele_addresses.f90.
References nele_lc_shell.
Referenced by set_sph_ele_group::set_ele_grp_item_on_sphere(), cal_sph_ele_connects::set_south_pole_element(), and set_sph_surf_group::set_surf_grp_item_on_sphere().
sph_shell_ele_id()
integer(kind = kint) function cal_sph_ele_addresses::sph_shell_ele_id (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, integer(kind = kint), intent(in) kr, integer(kind = kint), intent(in) lt, integer(kind = kint), intent(in) mp, type(comm_table_make_sph), intent(in) stbl)
Definition at line 260 of file cal_sph_ele_addresses.f90.
Referenced by set_sph_ele_group::set_ele_grp_item_on_sphere(), cal_sph_ele_connects::set_spherical_shell_element(), and set_sph_surf_group::set_surf_grp_item_on_sphere().
Variable Documentation
nele_ctr_npole
integer(kind = kint), private cal_sph_ele_addresses::nele_ctr_npole = 0 private
Definition at line 68 of file cal_sph_ele_addresses.f90.
Referenced by cal_sph_local_numele(), reset_local_sph_ele_constants(), and set_nele_center_npole().
nele_ctr_spole
integer(kind = kint), private cal_sph_ele_addresses::nele_ctr_spole = 0 private
Definition at line 67 of file cal_sph_ele_addresses.f90.
Referenced by cal_sph_local_numele(), reset_local_sph_ele_constants(), set_nele_center_spole(), and sph_inter_ctr_npole_ele_id().
nele_ext_ctr_sph
integer(kind = kint), private cal_sph_ele_addresses::nele_ext_ctr_sph = 0 private
Definition at line 66 of file cal_sph_ele_addresses.f90.
Referenced by cal_sph_local_numele(), reset_local_sph_ele_constants(), set_nele_ext_ctr_sph(), and sph_exter_ctr_npole_ele_id().
nele_gl_ctr_npole
integer(kind = kint_gl) cal_sph_ele_addresses::nele_gl_ctr_npole = 0
Definition at line 76 of file cal_sph_ele_addresses.f90.
Referenced by reset_local_sph_ele_constants(), and set_nele_gl_ctr_sph().
nele_gl_ctr_sph
integer(kind = kint_gl) cal_sph_ele_addresses::nele_gl_ctr_sph = 0
Definition at line 74 of file cal_sph_ele_addresses.f90.
Referenced by global_ctr_npole_ele_id(), global_ctr_spole_ele_id(), reset_local_sph_ele_constants(), and set_nele_gl_ctr_sph().
nele_gl_ctr_spole
integer(kind = kint_gl) cal_sph_ele_addresses::nele_gl_ctr_spole = 0
Definition at line 75 of file cal_sph_ele_addresses.f90.
Referenced by global_ctr_npole_ele_id(), reset_local_sph_ele_constants(), and set_nele_gl_ctr_sph().
nele_gl_npole
integer(kind = kint_gl) cal_sph_ele_addresses::nele_gl_npole = 0
Definition at line 73 of file cal_sph_ele_addresses.f90.
Referenced by global_ctr_npole_ele_id(), global_ctr_shell_ele_id(), global_ctr_spole_ele_id(), reset_local_sph_ele_constants(), and set_nele_gl_npole().
nele_gl_shell
integer(kind = kint_gl) cal_sph_ele_addresses::nele_gl_shell = 0
Definition at line 71 of file cal_sph_ele_addresses.f90.
Referenced by global_ctr_npole_ele_id(), global_ctr_shell_ele_id(), global_ctr_spole_ele_id(), global_sph_n_pole_ele_id(), global_sph_s_pole_ele_id(), reset_local_sph_ele_constants(), and set_nele_gl_shell().
nele_gl_spole
integer(kind = kint_gl) cal_sph_ele_addresses::nele_gl_spole = 0
Definition at line 72 of file cal_sph_ele_addresses.f90.
Referenced by global_ctr_npole_ele_id(), global_ctr_shell_ele_id(), global_ctr_spole_ele_id(), global_sph_n_pole_ele_id(), reset_local_sph_ele_constants(), and set_nele_gl_spole().
nele_lc_ctr_sph
integer(kind = kint), private cal_sph_ele_addresses::nele_lc_ctr_sph = 0 private
Definition at line 65 of file cal_sph_ele_addresses.f90.
Referenced by cal_sph_local_numele(), reset_local_sph_ele_constants(), set_nele_lc_ctr_sph(), sph_inter_ctr_npole_ele_id(), and sph_inter_ctr_spole_ele_id().
nele_lc_npole
integer(kind = kint), private cal_sph_ele_addresses::nele_lc_npole = 0 private
Definition at line 64 of file cal_sph_ele_addresses.f90.
Referenced by cal_sph_local_numele(), reset_local_sph_ele_constants(), set_nele_lc_npole(), sph_exter_ctr_npole_ele_id(), sph_exter_ctr_shell_ele_id(), sph_inter_ctr_npole_ele_id(), sph_inter_ctr_shell_ele_id(), and sph_inter_ctr_spole_ele_id().
nele_lc_shell
integer(kind = kint), private cal_sph_ele_addresses::nele_lc_shell = 0 private
Definition at line 62 of file cal_sph_ele_addresses.f90.
Referenced by cal_sph_local_numele(), reset_local_sph_ele_constants(), set_nele_lc_shell(), sph_exter_ctr_npole_ele_id(), sph_exter_ctr_shell_ele_id(), sph_inter_ctr_npole_ele_id(), sph_inter_ctr_shell_ele_id(), sph_inter_ctr_spole_ele_id(), sph_n_pole_ele_id(), and sph_s_pole_ele_id().
nele_lc_spole
integer(kind = kint), private cal_sph_ele_addresses::nele_lc_spole = 0 private
Definition at line 63 of file cal_sph_ele_addresses.f90.
Referenced by cal_sph_local_numele(), reset_local_sph_ele_constants(), set_nele_lc_spole(), sph_exter_ctr_npole_ele_id(), sph_exter_ctr_shell_ele_id(), sph_inter_ctr_npole_ele_id(), sph_inter_ctr_shell_ele_id(), sph_inter_ctr_spole_ele_id(), and sph_n_pole_ele_id().