CALYPSO: m_intersection_data_3 Module Reference
m_intersection_data_3 Module Reference
Variables
integer(kind=kint), parameter, private nnod_tri = 3
integer(kind=kint), parameter, private nnod_hex = 6
integer(kind=kint), parameter nkind_etype_3 = 12
integer(kind=kint), parameter num_hexa_3 = 1
integer(kind=kint), parameter num_patch_3 = 4
integer(kind=kint), dimension(12), parameter ih_2_p_3 = (/3, 2, 1, 3, 4, 1, 1, 4, 5, 1, 5, 6/)
integer(kind=kint), dimension(3, 2) ihex_2_patches_3
integer(kind=kint), dimension(nkind_etype_3), parameter iflag_psf_etype_3p = (/129, 36, 18, 72, 5, 160, 24, 66, 33, 132, 10, 80/)
integer(kind=kint), dimension(nkind_etype_3), parameter iflag_psf_etype_3n = (/126, 219, 237, 183, 250, 95, 231, 189, 222, 123, 245, 175/)
integer(kind=kint), dimension(nnod_hex, nkind_etype_3), parameter iedge_hex_3p = reshape((/ 1, 9, 8, 7, 12, 4, 3, 11, 6, 5, 10, 2, 2, 10, 5, 8, 9, 1, 4, 12, 7, 6, 11, 3, 9, 4, 3, 11, 2, 1, 10, 6, 7, 12, 8, 5, 3, 4, 9, 5, 8, 12, 1, 2, 11, 7, 6, 10, 4, 1, 10, 6, 5, 9, 2, 3, 12, 8, 7, 11, 10, 1, 4, 12, 3, 2, 9, 5, 6, 11, 7, 8 /), shape=(/nnod_hex,nkind_etype_3/))
integer(kind=kint), dimension(nnod_tri, num_patch_3, nkind_etype_3) iedge_4_patch_3p = reshape((/ 9, 8, 1, 8, 7, 1, 1, 7, 12, 1, 12, 4, 11, 6, 3, 6, 5, 3, 3, 5, 10, 3, 10, 2, 10, 5, 2, 5, 8, 2, 2, 8, 9, 2, 9, 1, 12, 7, 4, 7, 6, 4, 4, 6, 11, 4, 11, 3, 4, 3, 9, 3, 11, 9, 9, 11, 2, 9, 2, 1, 6, 7, 10, 7, 12, 10, 10, 12, 8, 10, 8, 5, 4, 9, 3, 9, 5, 3, 3, 5, 8, 3, 8, 12, 2, 11, 1, 11, 7, 1, 1, 7, 6, 1, 6, 10, 1, 10, 4, 10, 6, 4, 4, 6, 5, 4, 5, 9, 3, 12, 2, 12, 8, 2, 2, 8, 7, 2, 7, 11, 1, 4, 10, 4, 12, 10, 10, 12, 3, 10, 3, 2, 5, 6, 9, 6, 11, 9, 9, 11, 7, 9, 7, 8 /), shape=(/nnod_tri,num_patch_3,nkind_etype_3/))
integer(kind=kint), dimension(nnod_hex, nkind_etype_3), parameter iedge_hex_3n = reshape((/ 1, 4, 12, 7, 8, 9, 3, 2, 10, 5, 6, 11, 2, 1, 9, 8, 5, 10, 4, 3, 11, 6, 7, 12, 9, 1, 2, 11, 3, 4, 10, 5, 8, 12, 7, 6, 3, 12, 8, 5, 9, 4, 1, 10, 6, 7, 11, 2, 4, 9, 5, 6, 10, 1, 2, 11, 7, 8, 12, 3, 10, 2, 3, 12, 4, 1, 9, 8, 7, 11, 6, 5 /), shape=(/nnod_hex,nkind_etype_3/))
integer(kind=kint), dimension(nnod_tri, num_patch_3, nkind_etype_3) iedge_4_patch_3n = reshape((/ 4, 12, 1, 12, 7, 1, 1, 7, 8, 1, 8, 9, 2, 10, 3, 10, 5, 3, 3, 5, 6, 3, 6, 11, 1, 9, 2, 9, 8, 2, 2, 8, 5, 2, 5, 10, 3, 11, 4, 11, 6, 4, 4, 6, 7, 4, 7, 12, 1, 2, 9, 2, 11, 9, 9, 11, 3, 9, 3, 4, 5, 8, 10, 8, 12, 10, 10, 12, 7, 10, 7, 6, 12, 8, 3, 8, 5, 3, 3, 5, 9, 3, 9, 4, 10, 6, 1, 6, 7, 1, 1, 7, 11, 1, 11, 2, 9, 5, 4, 5, 6, 4, 4, 6, 10, 4, 10, 1, 11, 7, 2, 7, 8, 2, 2, 8, 12, 2, 12, 3, 2, 3, 10, 3, 12, 10, 10, 12, 4, 10, 4, 1, 8, 7, 9, 7, 11, 9, 9, 11, 6, 9, 6, 5 /), shape=(/nnod_tri,num_patch_3,nkind_etype_3/))
Variable Documentation
iedge_4_patch_3n
integer(kind = kint), dimension(nnod_tri,num_patch_3,nkind_etype_3) m_intersection_data_3::iedge_4_patch_3n = reshape((/ 4, 12, 1, 12, 7, 1, 1, 7, 8, 1, 8, 9, 2, 10, 3, 10, 5, 3, 3, 5, 6, 3, 6, 11, 1, 9, 2, 9, 8, 2, 2, 8, 5, 2, 5, 10, 3, 11, 4, 11, 6, 4, 4, 6, 7, 4, 7, 12, 1, 2, 9, 2, 11, 9, 9, 11, 3, 9, 3, 4, 5, 8, 10, 8, 12, 10, 10, 12, 7, 10, 7, 6, 12, 8, 3, 8, 5, 3, 3, 5, 9, 3, 9, 4, 10, 6, 1, 6, 7, 1, 1, 7, 11, 1, 11, 2, 9, 5, 4, 5, 6, 4, 4, 6, 10, 4, 10, 1, 11, 7, 2, 7, 8, 2, 2, 8, 12, 2, 12, 3, 2, 3, 10, 3, 12, 10, 10, 12, 4, 10, 4, 1, 8, 7, 9, 7, 11, 9, 9, 11, 6, 9, 6, 5 /), shape=(/nnod_tri,num_patch_3,nkind_etype_3/))
Definition at line 136 of file m_intersection_data_3.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
iedge_4_patch_3p
integer(kind = kint), dimension(nnod_tri,num_patch_3,nkind_etype_3) m_intersection_data_3::iedge_4_patch_3p = reshape((/ 9, 8, 1, 8, 7, 1, 1, 7, 12, 1, 12, 4, 11, 6, 3, 6, 5, 3, 3, 5, 10, 3, 10, 2, 10, 5, 2, 5, 8, 2, 2, 8, 9, 2, 9, 1, 12, 7, 4, 7, 6, 4, 4, 6, 11, 4, 11, 3, 4, 3, 9, 3, 11, 9, 9, 11, 2, 9, 2, 1, 6, 7, 10, 7, 12, 10, 10, 12, 8, 10, 8, 5, 4, 9, 3, 9, 5, 3, 3, 5, 8, 3, 8, 12, 2, 11, 1, 11, 7, 1, 1, 7, 6, 1, 6, 10, 1, 10, 4, 10, 6, 4, 4, 6, 5, 4, 5, 9, 3, 12, 2, 12, 8, 2, 2, 8, 7, 2, 7, 11, 1, 4, 10, 4, 12, 10, 10, 12, 3, 10, 3, 2, 5, 6, 9, 6, 11, 9, 9, 11, 7, 9, 7, 8 /), shape=(/nnod_tri,num_patch_3,nkind_etype_3/))
Definition at line 107 of file m_intersection_data_3.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
iedge_hex_3n
integer(kind = kint), dimension(nnod_hex,nkind_etype_3), parameter m_intersection_data_3::iedge_hex_3n = reshape((/ 1, 4, 12, 7, 8, 9, 3, 2, 10, 5, 6, 11, 2, 1, 9, 8, 5, 10, 4, 3, 11, 6, 7, 12, 9, 1, 2, 11, 3, 4, 10, 5, 8, 12, 7, 6, 3, 12, 8, 5, 9, 4, 1, 10, 6, 7, 11, 2, 4, 9, 5, 6, 10, 1, 2, 11, 7, 8, 12, 3, 10, 2, 3, 12, 4, 1, 9, 8, 7, 11, 6, 5 /), shape=(/nnod_hex,nkind_etype_3/))
Definition at line 125 of file m_intersection_data_3.f90.
iedge_hex_3p
integer(kind = kint), dimension(nnod_hex,nkind_etype_3), parameter m_intersection_data_3::iedge_hex_3p = reshape((/ 1, 9, 8, 7, 12, 4, 3, 11, 6, 5, 10, 2, 2, 10, 5, 8, 9, 1, 4, 12, 7, 6, 11, 3, 9, 4, 3, 11, 2, 1, 10, 6, 7, 12, 8, 5, 3, 4, 9, 5, 8, 12, 1, 2, 11, 7, 6, 10, 4, 1, 10, 6, 5, 9, 2, 3, 12, 8, 7, 11, 10, 1, 4, 12, 3, 2, 9, 5, 6, 11, 7, 8 /), shape=(/nnod_hex,nkind_etype_3/))
Definition at line 96 of file m_intersection_data_3.f90.
iflag_psf_etype_3n
integer(kind = kint), dimension(nkind_etype_3), parameter m_intersection_data_3::iflag_psf_etype_3n = (/126, 219, 237, 183, 250, 95, 231, 189, 222, 123, 245, 175/)
Definition at line 90 of file m_intersection_data_3.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
iflag_psf_etype_3p
integer(kind = kint), dimension(nkind_etype_3), parameter m_intersection_data_3::iflag_psf_etype_3p = (/129, 36, 18, 72, 5, 160, 24, 66, 33, 132, 10, 80/)
Definition at line 86 of file m_intersection_data_3.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
ih_2_p_3
integer(kind = kint), dimension(12), parameter m_intersection_data_3::ih_2_p_3 = (/3, 2, 1, 3, 4, 1, 1, 4, 5, 1, 5, 6/)
Definition at line 80 of file m_intersection_data_3.f90.
ihex_2_patches_3
integer(kind = kint), dimension(3,2) m_intersection_data_3::ihex_2_patches_3
Definition at line 83 of file m_intersection_data_3.f90.
nkind_etype_3
integer(kind = kint), parameter m_intersection_data_3::nkind_etype_3 = 12
Definition at line 77 of file m_intersection_data_3.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
nnod_hex
integer(kind = kint), parameter, private m_intersection_data_3::nnod_hex = 6 private
Definition at line 20 of file m_intersection_data_3.f90.
nnod_tri
integer(kind = kint), parameter, private m_intersection_data_3::nnod_tri = 3 private
Definition at line 19 of file m_intersection_data_3.f90.
num_hexa_3
integer(kind = kint), parameter m_intersection_data_3::num_hexa_3 = 1
Definition at line 78 of file m_intersection_data_3.f90.
num_patch_3
integer(kind = kint), parameter m_intersection_data_3::num_patch_3 = 4
Definition at line 79 of file m_intersection_data_3.f90.
Referenced by t_psf_case_table::init_psf_case_tables().