CALYPSO: const_data_4_dynamobench Module Reference
const_data_4_dynamobench Module Reference
Evaluate dynamo benchmark results.
Functions/Subroutines
subroutine s_const_data_4_dynamobench (time, sph_params, sph_rj, sph_MHD_bc, trans_p, ipol, rj_fld, cdat, pwr, bench, WK_pwr)
subroutine, private mid_eq_transfer_dynamobench (time, iflag_FFT, sph_rj, rj_fld, cdat, bench)
Detailed Description
Evaluate dynamo benchmark results.
      subroutine s_const_data_4_dynamobench                           &
     &         (time, sph_params, sph_rj, sph_MHD_bc, trans_p, ipol,  &
     &          rj_fld, cdat, pwr, bench, WK_pwr)
        type(sph_shell_parameters), intent(in) :: sph_params
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(sph_MHD_boundary_data), intent(in) :: sph_MHD_bc
        type(parameters_4_sph_trans), intent(in) :: trans_p
        type(phys_address), intent(in) :: ipol
        type(phys_data), intent(in) :: rj_fld
        type(circle_fld_maker), intent(inout) :: cdat
        type(dynamobench_monitor), intent(inout) :: bench
        type(sph_mean_squares), intent(inout) :: pwr
        type(sph_mean_square_work), intent(inout) :: WK_pwr
Function/Subroutine Documentation
mid_eq_transfer_dynamobench()
subroutine, private const_data_4_dynamobench::mid_eq_transfer_dynamobench (real(kind=kreal), intent(in) time, integer(kind = kint), intent(in) iflag_FFT, type(sph_rj_grid), intent(in) sph_rj, type(phys_data), intent(in) rj_fld, type(circle_fld_maker), intent(inout) cdat, type(dynamobench_monitor), intent(inout) bench) private
Definition at line 122 of file const_data_4_dynamobench.f90.
References field_at_mid_equator::cal_drift_by_v44(), field_at_mid_equator::cal_field_4_dynamobench(), m_machine_parameter::iflag_debug, calypso_mpi::my_rank, and t_field_on_circle::sph_transfer_on_circle().
Referenced by s_const_data_4_dynamobench().
s_const_data_4_dynamobench()
subroutine const_data_4_dynamobench::s_const_data_4_dynamobench (real(kind=kreal), intent(in) time, type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(sph_mhd_boundary_data), intent(in) sph_MHD_bc, type(parameters_4_sph_trans), intent(in) trans_p, type(phys_address), intent(in) ipol, type(phys_data), intent(in) rj_fld, type(circle_fld_maker), intent(inout) cdat, type(sph_mean_squares), intent(inout) pwr, type(dynamobench_monitor), intent(inout) bench, type(sph_mean_square_work), intent(inout) WK_pwr)
Definition at line 41 of file const_data_4_dynamobench.f90.
References cal_rms_fields_by_sph::cal_mean_squre_in_shell(), global_field_4_dynamobench::copy_energy_4_dynamobench(), global_field_4_dynamobench::copy_icore_energy_4_dbench(), m_machine_parameter::iflag_debug, m_constants::izero, mid_eq_transfer_dynamobench(), calypso_mpi::my_rank, global_field_4_dynamobench::pick_inner_core_rotation(), and global_field_4_dynamobench::pick_mag_torque_inner_core().
Referenced by sph_analyzer_d_bench::sph_analyze_dbench().