CALYPSO: gz_mpi_binary_data_io Module Reference
gz_mpi_binary_data_io Module Reference
Output gzipped merged binary field file using MPI-IO.
Functions/Subroutines
subroutine gz_mpi_write_integer_stack_b (IO_param, num, istack)
subroutine gz_mpi_write_int_vector_b (IO_param, num, int_dat)
subroutine gz_mpi_write_int8_vector_b (IO_param, num, int8_dat)
subroutine gz_mpi_write_1d_vector_b (IO_param, num, real_dat)
subroutine gz_mpi_write_2d_vector_b (IO_param, n1, n2, real_dat)
subroutine gz_mpi_read_integer_stack_b (IO_param, num, istack, ntot)
subroutine gz_mpi_read_int_vector_b (IO_param, num, int_dat)
subroutine gz_mpi_read_int8_vector_b (IO_param, num, int8_dat)
subroutine gz_mpi_read_1d_vector_b (IO_param, num, real_dat)
subroutine gz_mpi_read_2d_vector_b (IO_param, n1, n2, real_dat)
Variables
type(buffer_4_gzip), private zbuf
Detailed Description
Output gzipped merged binary field file using MPI-IO.
      subroutine gz_mpi_write_integer_stack_b(IO_param, num, istack)
        Substitution of gz_write_integer_stack_b
      subroutine gz_mpi_write_int_vector_b(IO_param, num, int_dat)
        Substitutio of gz_write_mul_integer_b
      subroutine gz_mpi_write_int8_vector_b(IO_param, num, int8_dat)
        Substitutio of gz_write_mul_int8_b
      subroutine gz_mpi_write_1d_vector_b(IO_param, num, real_dat)
        Substitutio of gz_write_1d_vector_b
      subroutine gz_mpi_write_2d_vector_b(IO_param, n1, n2, real_dat)
        Substitutio of gz_write_2d_vector_b
      subroutine gz_mpi_read_integer_stack_b                          &
     &         (IO_param, num, istack, ntot)
        Substittion of  gz_read_integer_stack_b
      subroutine gz_mpi_read_int_vector_b(IO_param, num, int_dat)
        Substitutio of gz_read_mul_integer_b
      subroutine gz_mpi_read_int8_vector_b(IO_param, num, int8_dat)
        Substitutio of gz_read_mul_int8_b
      subroutine gz_mpi_read_1d_vector_b(IO_param, num, real_dat)
        Substitutio of gz_read_1d_vector_b
      subroutine gz_mpi_read_2d_vector_b(IO_param, n1, n2, real_dat)
        Substitutio of gz_read_2d_vector_b
Function/Subroutine Documentation
gz_mpi_read_1d_vector_b()
subroutine gz_mpi_binary_data_io::gz_mpi_read_1d_vector_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint_gl), intent(in) num, real(kind = kreal), dimension(num), intent(inout) real_dat)
Definition at line 256 of file gz_MPI_binary_data_IO.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), byte_swap_f::byte_swap_real_f(), m_calypso_mpi_io::calypso_mpi_seek_read_gz(), t_buffer_4_gzip::dealloc_zip_buffer(), gz_mpi_binary_head_io::gz_mpi_read_merged_stack_b(), m_machine_parameter::iendian_flip, data_convert_by_zlib::infleate_1d_vector_b(), and zbuf.
Referenced by gz_mpi_read_2d_vector_b(), gz_mpi_sph_gl_1d_idx_io_b::gz_mpi_read_rj_gl_1d_table_b(), gz_mpi_sph_gl_1d_idx_io_b::gz_mpi_read_rtp_gl_1d_table_b(), and gz_mpi_node_geometry_io_b::gz_mpi_read_scl_in_ele_b().
gz_mpi_read_2d_vector_b()
subroutine gz_mpi_binary_data_io::gz_mpi_read_2d_vector_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint_gl), intent(in) n1, integer(kind = kint), intent(in) n2, real(kind = kreal), dimension(n1,n2), intent(inout) real_dat)
Definition at line 298 of file gz_MPI_binary_data_IO.f90.
References gz_mpi_read_1d_vector_b().
Referenced by gz_mpi_node_geometry_io_b::gz_mpi_read_geometry_info_b(), gz_mpi_node_geometry_io_b::gz_mpi_read_vect_in_ele_b(), gz_field_file_mpi_io_b::gz_rd_alloc_st_fld_file_mpi_b(), gz_ucd_field_mpi_io_b::gz_rd_alloc_ucd_fld_file_mpi_b(), gz_field_file_mpi_io_b::gz_read_step_field_file_mpi_b(), and gz_ucd_field_mpi_io_b::gz_read_ucd_field_file_mpi_b().
gz_mpi_read_int8_vector_b()
subroutine gz_mpi_binary_data_io::gz_mpi_read_int8_vector_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint_gl), intent(in) num, integer(kind = kint_gl), dimension(num), intent(inout) int8_dat)
Definition at line 214 of file gz_MPI_binary_data_IO.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), byte_swap_f::byte_swap_int8_f(), m_calypso_mpi_io::calypso_mpi_seek_read_gz(), t_buffer_4_gzip::dealloc_zip_buffer(), gz_mpi_binary_head_io::gz_mpi_read_merged_stack_b(), m_machine_parameter::iendian_flip, data_convert_by_zlib::infleate_int8_vector_b(), and zbuf.
Referenced by gz_mpi_element_connect_io_b::gz_mpi_read_ele_info_b(), gz_mpi_node_geometry_io_b::gz_mpi_read_geometry_info_b(), gz_mpi_spherical_model_io_b::gz_mpi_read_gl_nodes_sph_b(), and gz_mpi_read_int_vector_b().
gz_mpi_read_int_vector_b()
subroutine gz_mpi_binary_data_io::gz_mpi_read_int_vector_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint_gl), intent(in) num, integer(kind = kint), dimension(num), intent(inout) int_dat)
Definition at line 194 of file gz_MPI_binary_data_IO.f90.
References transfer_to_long_integers::alloc_1d_i8array(), transfer_to_long_integers::dup_to_short_array(), and gz_mpi_read_int8_vector_b().
Referenced by gz_mpi_domain_data_io_b::gz_mpi_read_domain_info_b(), gz_mpi_element_connect_io_b::gz_mpi_read_edge_4_element_b(), gz_mpi_element_connect_io_b::gz_mpi_read_ele_info_b(), gz_mpi_domain_data_io_b::gz_mpi_read_export_data_b(), gz_mpi_spherical_model_io_b::gz_mpi_read_gl_nodes_sph_b(), gz_mpi_groups_io_b::gz_mpi_read_group_data_b(), gz_mpi_domain_data_io_b::gz_mpi_read_import_data_b(), gz_mpi_read_integer_stack_b(), gz_mpi_binary_datum_io::gz_mpi_read_one_integer_b(), gz_mpi_spherical_model_io_b::gz_mpi_read_rank_4_sph_b(), gz_mpi_sph_gl_1d_idx_io_b::gz_mpi_read_rj_gl_1d_table_b(), gz_mpi_sph_gl_1d_idx_io_b::gz_mpi_read_rtp_gl_1d_table_b(), gz_mpi_element_connect_io_b::gz_mpi_read_surf_4_elem_b(), and gz_mpi_groups_io_b::gz_mpi_read_surf_grp_data_b().
gz_mpi_read_integer_stack_b()
subroutine gz_mpi_binary_data_io::gz_mpi_read_integer_stack_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint_gl), intent(in) num, integer(kind = kint), dimension(0:num), intent(inout) istack, integer(kind = kint), intent(inout) ntot)
Definition at line 174 of file gz_MPI_binary_data_IO.f90.
References gz_mpi_read_int_vector_b().
Referenced by gz_mpi_domain_data_io_b::gz_mpi_read_export_data_b(), gz_mpi_groups_io_b::gz_mpi_read_group_data_b(), gz_mpi_domain_data_io_b::gz_mpi_read_import_data_b(), and gz_mpi_groups_io_b::gz_mpi_read_surf_grp_data_b().
gz_mpi_write_1d_vector_b()
subroutine gz_mpi_binary_data_io::gz_mpi_write_1d_vector_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint_gl), intent(in) num, real(kind = kreal), dimension(num), intent(in) real_dat)
Definition at line 124 of file gz_MPI_binary_data_IO.f90.
References m_calypso_mpi_io::calypso_mpi_seek_write_gz(), t_buffer_4_gzip::dealloc_zip_buffer(), data_convert_by_zlib::defleate_1d_vector_b(), gz_mpi_binary_head_io::gz_mpi_write_merged_stack_b(), t_calypso_mpi_io_param::istack64_4_parallel_data(), calypso_mpi::my_rank, calypso_mpi::nprocs, and zbuf.
Referenced by gz_mpi_write_2d_vector_b(), gz_mpi_sph_gl_1d_idx_io_b::gz_mpi_write_rj_gl_1d_table_b(), gz_mpi_sph_gl_1d_idx_io_b::gz_mpi_write_rtp_gl_1d_table_b(), and gz_mpi_node_geometry_io_b::gz_mpi_write_scl_in_ele_b().
gz_mpi_write_2d_vector_b()
subroutine gz_mpi_binary_data_io::gz_mpi_write_2d_vector_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint_gl), intent(in) n1, integer(kind = kint), intent(in) n2, real(kind = kreal), dimension(n1,n2), intent(in) real_dat)
Definition at line 155 of file gz_MPI_binary_data_IO.f90.
References gz_mpi_write_1d_vector_b().
Referenced by gz_mpi_node_geometry_io_b::gz_mpi_write_geometry_info_b(), gz_mpi_node_geometry_io_b::gz_mpi_write_vect_in_ele_b(), and gz_field_block_mpi_io_b::gz_write_field_data_mpi_b().
gz_mpi_write_int8_vector_b()
subroutine gz_mpi_binary_data_io::gz_mpi_write_int8_vector_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint_gl), intent(in) num, integer(kind = kint_gl), dimension(num), intent(in) int8_dat)
Definition at line 93 of file gz_MPI_binary_data_IO.f90.
References m_calypso_mpi_io::calypso_mpi_seek_write_gz(), t_buffer_4_gzip::dealloc_zip_buffer(), data_convert_by_zlib::defleate_int8_vector_b(), gz_mpi_binary_head_io::gz_mpi_write_merged_stack_b(), t_calypso_mpi_io_param::istack64_4_parallel_data(), calypso_mpi::my_rank, calypso_mpi::nprocs, and zbuf.
Referenced by gz_mpi_element_connect_io_b::gz_mpi_write_element_info_b(), gz_mpi_node_geometry_io_b::gz_mpi_write_geometry_info_b(), gz_mpi_spherical_model_io_b::gz_mpi_write_gl_nodes_sph_b(), and gz_mpi_write_int_vector_b().
gz_mpi_write_int_vector_b()
subroutine gz_mpi_binary_data_io::gz_mpi_write_int_vector_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint_gl), intent(in) num, integer(kind = kint), dimension(num), intent(in) int_dat)
Definition at line 74 of file gz_MPI_binary_data_IO.f90.
References transfer_to_long_integers::dealloc_1d_i8array(), transfer_to_long_integers::dup_from_short_array(), and gz_mpi_write_int8_vector_b().
Referenced by gz_mpi_domain_data_io_b::gz_mpi_write_domain_info_b(), gz_mpi_element_connect_io_b::gz_mpi_write_edge_4_ele_b(), gz_mpi_element_connect_io_b::gz_mpi_write_element_info_b(), gz_mpi_domain_data_io_b::gz_mpi_write_export_data_b(), gz_mpi_spherical_model_io_b::gz_mpi_write_gl_nodes_sph_b(), gz_mpi_groups_io_b::gz_mpi_write_grp_data_b(), gz_mpi_domain_data_io_b::gz_mpi_write_import_data_b(), gz_mpi_write_integer_stack_b(), gz_mpi_binary_datum_io::gz_mpi_write_one_integer_b(), gz_mpi_spherical_model_io_b::gz_mpi_write_rank_4_sph_b(), gz_mpi_sph_gl_1d_idx_io_b::gz_mpi_write_rj_gl_1d_table_b(), gz_mpi_sph_gl_1d_idx_io_b::gz_mpi_write_rtp_gl_1d_table_b(), gz_mpi_element_connect_io_b::gz_mpi_write_surf_4_ele_b(), and gz_mpi_groups_io_b::gz_mpi_write_surf_grp_data_b().
gz_mpi_write_integer_stack_b()
subroutine gz_mpi_binary_data_io::gz_mpi_write_integer_stack_b (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint_gl), intent(in) num, integer(kind = kint), dimension(0:num), intent(in) istack)
Definition at line 58 of file gz_MPI_binary_data_IO.f90.
References gz_mpi_write_int_vector_b().
Referenced by gz_mpi_domain_data_io_b::gz_mpi_write_export_data_b(), gz_mpi_groups_io_b::gz_mpi_write_grp_data_b(), gz_mpi_domain_data_io_b::gz_mpi_write_import_data_b(), and gz_mpi_groups_io_b::gz_mpi_write_surf_grp_data_b().
Variable Documentation
zbuf
type(buffer_4_gzip), private gz_mpi_binary_data_io::zbuf private
Definition at line 50 of file gz_MPI_binary_data_IO.f90.
Referenced by gz_mpi_read_1d_vector_b(), gz_mpi_read_int8_vector_b(), gz_mpi_write_1d_vector_b(), and gz_mpi_write_int8_vector_b().