CALYPSO: set_comm_tbl_4_pole_mesh Module Reference
set_comm_tbl_4_pole_mesh Module Reference
Functions/Subroutines
subroutine count_import_4_spole_mesh (ip_r, ip_t, jp_r, jp_t, stbl, num_import)
subroutine count_import_4_npole_mesh (ip_r, ip_t, jp_r, jp_t, stbl, num_import)
subroutine set_import_rtp_spole_mesh (ip_r, ip_t, jp_r, jp_t, icou, stbl, nod_comm)
subroutine set_import_rtp_npole_mesh (ip_r, ip_t, jp_r, jp_t, icou, stbl, nod_comm)
subroutine count_export_4_spole_mesh (ip_r, ip_t, jp_r, jp_t, stbl, num_export)
subroutine count_export_4_npole_mesh (ip_r, ip_t, jp_r, jp_t, stbl, num_export)
subroutine set_export_rtp_spole_mesh (ip_r, ip_t, jp_r, jp_t, icou, stbl, nod_comm)
subroutine set_export_rtp_npole_mesh (ip_r, ip_t, jp_r, jp_t, icou, stbl, nod_comm)
Function/Subroutine Documentation
count_export_4_npole_mesh()
subroutine set_comm_tbl_4_pole_mesh::count_export_4_npole_mesh (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, integer(kind = kint), intent(in) jp_r, integer(kind = kint), intent(in) jp_t, type(comm_table_make_sph), intent(in) stbl, integer(kind = kint), intent(inout) num_export)
Definition at line 214 of file set_comm_tbl_4_pole_mesh.f90.
References m_constants::izero.
Referenced by const_comm_tbl_4_sph_mesh::count_export_4_sph_mesh().
count_export_4_spole_mesh()
subroutine set_comm_tbl_4_pole_mesh::count_export_4_spole_mesh (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, integer(kind = kint), intent(in) jp_r, integer(kind = kint), intent(in) jp_t, type(comm_table_make_sph), intent(in) stbl, integer(kind = kint), intent(inout) num_export)
Definition at line 185 of file set_comm_tbl_4_pole_mesh.f90.
References m_constants::izero.
Referenced by const_comm_tbl_4_sph_mesh::count_export_4_sph_mesh().
count_import_4_npole_mesh()
subroutine set_comm_tbl_4_pole_mesh::count_import_4_npole_mesh (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, integer(kind = kint), intent(in) jp_r, integer(kind = kint), intent(in) jp_t, type(comm_table_make_sph), intent(in) stbl, integer(kind = kint), intent(inout) num_import)
Definition at line 80 of file set_comm_tbl_4_pole_mesh.f90.
References m_constants::izero.
Referenced by const_comm_tbl_4_sph_mesh::count_import_4_sph_mesh().
count_import_4_spole_mesh()
subroutine set_comm_tbl_4_pole_mesh::count_import_4_spole_mesh (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, integer(kind = kint), intent(in) jp_r, integer(kind = kint), intent(in) jp_t, type(comm_table_make_sph), intent(in) stbl, integer(kind = kint), intent(inout) num_import)
Definition at line 51 of file set_comm_tbl_4_pole_mesh.f90.
References m_constants::izero.
Referenced by const_comm_tbl_4_sph_mesh::count_import_4_sph_mesh().
set_export_rtp_npole_mesh()
subroutine set_comm_tbl_4_pole_mesh::set_export_rtp_npole_mesh (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, integer(kind = kint), intent(in) jp_r, integer(kind = kint), intent(in) jp_t, integer(kind = kint), intent(inout) icou, type(comm_table_make_sph), intent(inout) stbl, type(communication_table), intent(inout) nod_comm)
Definition at line 280 of file set_comm_tbl_4_pole_mesh.f90.
References m_constants::izero, and cal_sph_node_addresses::sph_n_pole_node_id().
Referenced by const_comm_tbl_4_sph_mesh::set_export_rtp_sph_mesh().
set_export_rtp_spole_mesh()
subroutine set_comm_tbl_4_pole_mesh::set_export_rtp_spole_mesh (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, integer(kind = kint), intent(in) jp_r, integer(kind = kint), intent(in) jp_t, integer(kind = kint), intent(inout) icou, type(comm_table_make_sph), intent(inout) stbl, type(communication_table), intent(inout) nod_comm)
Definition at line 242 of file set_comm_tbl_4_pole_mesh.f90.
References m_constants::izero, and cal_sph_node_addresses::sph_s_pole_node_id().
Referenced by const_comm_tbl_4_sph_mesh::set_export_rtp_sph_mesh().
set_import_rtp_npole_mesh()
subroutine set_comm_tbl_4_pole_mesh::set_import_rtp_npole_mesh (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, integer(kind = kint), intent(in) jp_r, integer(kind = kint), intent(in) jp_t, integer(kind = kint), intent(inout) icou, type(comm_table_make_sph), intent(inout) stbl, type(communication_table), intent(inout) nod_comm)
Definition at line 146 of file set_comm_tbl_4_pole_mesh.f90.
References m_constants::izero, and cal_sph_node_addresses::sph_n_pole_node_id().
Referenced by const_comm_tbl_4_sph_mesh::set_import_rtp_sph_mesh().
set_import_rtp_spole_mesh()
subroutine set_comm_tbl_4_pole_mesh::set_import_rtp_spole_mesh (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, integer(kind = kint), intent(in) jp_r, integer(kind = kint), intent(in) jp_t, integer(kind = kint), intent(inout) icou, type(comm_table_make_sph), intent(inout) stbl, type(communication_table), intent(inout) nod_comm)
Definition at line 108 of file set_comm_tbl_4_pole_mesh.f90.
References m_constants::izero, and cal_sph_node_addresses::sph_s_pole_node_id().
Referenced by const_comm_tbl_4_sph_mesh::set_import_rtp_sph_mesh().