CALYPSO: sph_analyzer_d_bench Module Reference
sph_analyzer_d_bench Module Reference
spherical harmonics part of Initialzation and evolution loop for dynamo benchmark check
Functions/Subroutines
subroutine sph_init_sph_dbench (MHD_files, iphys, SPH_model, SPH_MHD, SPH_WK, cdat)
subroutine sph_analyze_dbench (i_step, MHD_files, SPH_model, SPH_MHD, SPH_WK, cdat, bench)
Detailed Description
spherical harmonics part of Initialzation and evolution loop for dynamo benchmark check
      subroutine SPH_init_sph_dbench(MHD_files, iphys,                &
     &          SPH_model, SPH_MHD, SPH_WK, cdat)
         type(MHD_file_IO_params), intent(in) :: MHD_files
         type(phys_address), intent(in) :: iphys
         type(SPH_MHD_model_data), intent(inout) :: SPH_model
        type(SPH_mesh_field_data), intent(inout) :: SPH_MHD
        type(work_SPH_MHD), intent(inout) :: SPH_WK
         type(circle_fld_maker), intent(inout) :: cdat
      subroutine SPH_analyze_dbench(i_step, MHD_files, SPH_model,     &
     &          SPH_MHD, SPH_WK, cdat, bench)
        type(MHD_file_IO_params), intent(in) :: MHD_files
         type(SPH_MHD_model_data), intent(in) :: SPH_model
        type(SPH_mesh_field_data), intent(inout) :: SPH_MHD
        type(work_SPH_MHD), intent(inout) :: SPH_WK
        type(phys_data), intent(inout) :: cdat
        type(dynamobench_monitor), intent(inout) :: bench
      subroutine SPH_finalize_dbench
Function/Subroutine Documentation
sph_analyze_dbench()
subroutine sph_analyzer_d_bench::sph_analyze_dbench (integer(kind = kint), intent(in) i_step, type(mhd_file_io_params), intent(in) MHD_files, type(sph_mhd_model_data), intent(in) SPH_model, type(sph_mesh_field_data), intent(inout) SPH_MHD, type(work_sph_mhd), intent(inout) SPH_WK, type(circle_fld_maker), intent(inout) cdat, type(dynamobench_monitor), intent(inout) bench)
Definition at line 138 of file SPH_analyzer_d_bench.f90.
References m_work_time::end_elapsed_time(), m_elapsed_labels_4_mhd::iflag_mhd_time, m_elapsed_labels_4_mhd::iflag_smhd_time, m_elapsed_labels_4_mhd::ist_elapsed_mhd, m_elapsed_labels_4_mhd::ist_elapsed_smhd, output_viz_file_control::lead_field_data_flag(), m_mhd_step_parameter::mhd_step1, t_field_4_dynamobench::output_field_4_dynamobench(), sph_mhd_rst_io_control::read_alloc_sph_rst_4_snap(), const_data_4_dynamobench::s_const_data_4_dynamobench(), lead_fields_4_sph_mhd::s_lead_fields_4_sph_mhd(), cal_sol_sph_mhd_crank::set_sph_field_to_start(), m_work_time::start_elapsed_time(), adjust_reference_fields::sync_temp_by_per_temp_sph(), and adjust_reference_fields::trans_per_temp_to_temp_sph().
Referenced by analyzer_sph_dynamobench::evolution_sph_dynamobench().
sph_init_sph_dbench()
subroutine sph_analyzer_d_bench::sph_init_sph_dbench (type(mhd_file_io_params), intent(in) MHD_files, type(phys_address), intent(in) iphys, type(sph_mhd_model_data), intent(inout) SPH_model, type(sph_mesh_field_data), intent(inout) SPH_MHD, type(work_sph_mhd), intent(inout) SPH_WK, type(circle_fld_maker), intent(inout) cdat)
Definition at line 53 of file SPH_analyzer_d_bench.f90.
References m_array_for_send_recv::allocate_vector_for_solver(), const_radial_mat_4_sph::const_radial_mat_sph_snap(), m_machine_parameter::iflag_debug, init_radial_infos_sph_mhd::init_r_infos_sph_mhd_evo(), sph_mhd_rst_io_control::init_radial_sph_interpolation(), init_sphrical_transform_mhd::init_sph_transform_mhd(), m_constants::isix, field_at_mid_equator::set_mid_equator_point_global(), and check_dependency_for_mhd::set_sph_mhd_sprctr_data().
Referenced by analyzer_sph_dynamobench::initialize_sph_dynamobench().