CALYPSO: calypso_mpi_char Module Reference
calypso_mpi_char Module Reference
MPI communication routines for characters in Calypso.
Functions/Subroutines
subroutine calypso_mpi_bcast_character (buffer, count, root)
subroutine calypso_mpi_seek_wrt_one_chara (id_mpi_file, ioffset, ilength, textbuf, sta_IO)
subroutine calypso_mpi_seek_wrt_mul_chara (id_mpi_file, ioffset, ilength, nline, textbuf, sta_IO)
subroutine calypso_mpi_seek_read_one_chara (id_mpi_file, ioffset, ilength, charabuf, sta_IO)
subroutine calypso_mpi_seek_read_mul_chara (id_mpi_file, ioffset, ilength, nline, textbuf, sta_IO)
Detailed Description
MPI communication routines for characters in Calypso.
      subroutine calypso_mpi_bcast_character(buffer, count, root)
        integer, intent(in) :: root
        integer(kind = kint_gl), intent(in) :: count
        character(len = 1), intent(inout) :: buffer(count)
      subroutine calypso_mpi_seek_wrt_one_chara                       &
     &         (id_mpi_file, ioffset, ilength, textbuf, sta_IO)
        integer, intent(in) ::  id_mpi_file
        integer, intent(in) :: ilength
        character(len=ilength), intent(in) :: textbuf
        integer(kind = MPI_OFFSET_KIND), intent(in) :: ioffset
        integer, intent(inout) :: sta_IO(MPI_STATUS_SIZE)
      subroutine calypso_mpi_seek_wrt_mul_chara                       &
     &         (id_mpi_file, ioffset, ilength, nline, textbuf, sta_IO)
        integer, intent(in) ::  id_mpi_file
        integer(kind = MPI_OFFSET_KIND), intent(in) :: ioffset
        integer, intent(in) :: ilength
        integer(kind = kint_gl), intent(in) :: nline
        character(len=ilength), intent(in) :: textbuf(nline)
        integer, intent(inout) :: sta_IO(MPI_STATUS_SIZE)
      subroutine calypso_mpi_seek_read_one_chara                      &
     &         (id_mpi_file, ioffset, ilength, charabuf, sta_IO)
        integer, intent(in) ::  id_mpi_file
        integer(kind = MPI_OFFSET_KIND), intent(in) :: ioffset
        integer, intent(in) :: ilength
        character(len=ilength), intent(inout) :: charabuf
        integer, intent(inout) :: sta_IO(MPI_STATUS_SIZE)
      subroutine calypso_mpi_seek_read_mul_chara                      &
     &         (id_mpi_file, ioffset, ilength, nline, textbuf, sta_IO)
        integer, intent(in) ::  id_mpi_file
        integer(kind = MPI_OFFSET_KIND), intent(in) :: ioffset
        integer, intent(in) :: ilength
        integer(kind = kint_gl), intent(in) :: nline
        character(len=ilength), intent(inout) :: textbuf(nline)
       integer, intent(inout) :: sta_IO(MPI_STATUS_SIZE)
Parameters
icode error code
message message to output
Function/Subroutine Documentation
calypso_mpi_bcast_character()
subroutine calypso_mpi_char::calypso_mpi_bcast_character (character(len = 1), dimension(count), intent(inout) buffer, integer(kind = kint_gl), intent(in) count, integer, intent(in) root)
Definition at line 66 of file calypso_mpi_char.f90.
References calypso_mpi::calypso_character, calypso_mpi::calypso_comm, m_constants::huge_20, and calypso_mpi::ierr_mpi.
Referenced by bcast_control_arrays::bcast_ctl_array_c1(), bcast_control_arrays::bcast_ctl_array_c2(), bcast_control_arrays::bcast_ctl_array_c2r(), bcast_control_arrays::bcast_ctl_array_c3(), bcast_control_arrays::bcast_ctl_array_ci(), bcast_control_arrays::bcast_ctl_array_ci3(), bcast_control_arrays::bcast_ctl_array_cr(), bcast_control_arrays::bcast_ctl_array_cr2(), bcast_control_arrays::bcast_ctl_array_icr(), bcast_control_arrays::bcast_ctl_type_c1(), bcast_control_arrays::bcast_ctl_type_c3(), bcast_control_arrays::bcast_ctl_type_c_i3(), t_each_sph_boundary_io_data::bcast_each_bc_item_num(), bcast_file_io_parameter::bcast_field_io_parameter(), t_control_data_isosurfaces::bcast_files_4_iso_ctl(), t_control_data_sections::bcast_files_4_psf_ctl(), t_ctl_data_gen_sph_shell::bcast_parallel_shell_ctl(), gz_mpi_ascii_data_io::gz_mpi_read_charahead(), gz_mpi_binary_head_io::gz_mpi_read_mul_charahead_b(), rayleigh_restart_io::init_rayleigh_restart_input(), mpi_ascii_data_io::mpi_read_charahead(), mpi_binary_head_io::mpi_read_mul_charahead_b(), share_field_data::share_field_io_names(), share_field_data::share_field_stack(), field_data_mpi_io::sync_field_name_mpi(), field_data_mpi_io::sync_field_names_mpi(), and mpi_load_mesh_data::sync_group_name_4_empty().
calypso_mpi_seek_read_mul_chara()
subroutine calypso_mpi_char::calypso_mpi_seek_read_mul_chara (integer, intent(in) id_mpi_file, integer(kind = mpi_offset_kind), intent(in) ioffset, integer, intent(in) ilength, integer(kind = kint_gl), intent(in) nline, character(len=ilength), dimension(nline), intent(inout) textbuf, integer, dimension(mpi_status_size), intent(inout) sta_IO)
Definition at line 161 of file calypso_mpi_char.f90.
References calypso_mpi::calypso_character, m_constants::huge_20, and calypso_mpi::ierr_mpi.
Referenced by m_calypso_mpi_io::calypso_mpi_seek_read_gz(), and m_calypso_mpi_io::mpi_read_mul_chara_b().
calypso_mpi_seek_read_one_chara()
subroutine calypso_mpi_char::calypso_mpi_seek_read_one_chara (integer, intent(in) id_mpi_file, integer(kind = mpi_offset_kind), intent(in) ioffset, integer, intent(in) ilength, character(len=ilength), intent(inout) charabuf, integer, dimension(mpi_status_size), intent(inout) sta_IO)
Definition at line 142 of file calypso_mpi_char.f90.
References calypso_mpi::calypso_character, and calypso_mpi::ierr_mpi.
Referenced by m_calypso_mpi_io::calypso_mpi_seek_read_chara(), and m_calypso_mpi_io::mpi_read_one_chara_b().
calypso_mpi_seek_wrt_mul_chara()
subroutine calypso_mpi_char::calypso_mpi_seek_wrt_mul_chara (integer, intent(in) id_mpi_file, integer(kind = mpi_offset_kind), intent(in) ioffset, integer, intent(in) ilength, integer(kind = kint_gl), intent(in) nline, character(len=ilength), dimension(nline), intent(in) textbuf, integer, dimension(mpi_status_size), intent(inout) sta_IO)
Definition at line 109 of file calypso_mpi_char.f90.
References calypso_mpi::calypso_character, m_constants::huge_20, and calypso_mpi::ierr_mpi.
Referenced by m_calypso_mpi_io::calypso_mpi_seek_write_gz(), and m_calypso_mpi_io::mpi_write_mul_chara_b().
calypso_mpi_seek_wrt_one_chara()
subroutine calypso_mpi_char::calypso_mpi_seek_wrt_one_chara (integer, intent(in) id_mpi_file, integer(kind = mpi_offset_kind), intent(in) ioffset, integer, intent(in) ilength, character(len=ilength), intent(in) textbuf, integer, dimension(mpi_status_size), intent(inout) sta_IO)
Definition at line 90 of file calypso_mpi_char.f90.
References calypso_mpi::calypso_character, and calypso_mpi::ierr_mpi.
Referenced by m_calypso_mpi_io::calypso_mpi_seek_write_head_c(), and m_calypso_mpi_io::mpi_write_one_chara_b().