CALYPSO: const_global_element_ids Module Reference
const_global_element_ids Module Reference
Construct global element IDs by number of internal elements.
Functions/Subroutines
subroutine count_number_of_node_stack (nnod, istack_nod_list)
subroutine count_number_of_node_stack4 (nnod, istack_nod_list)
subroutine set_global_ele_id (txt, nele, istack_internal_e, internal_flag, e_comm, iele_global)
subroutine check_element_position (txt, nele, x_ele, e_comm)
Detailed Description
Construct global element IDs by number of internal elements.
      subroutine count_number_of_node_stack(nnod, istack_nod_list)
      subroutine count_number_of_node_stack4(nnod, istack_nod_list)
      subroutine set_global_ele_id(txt, nele, istack_internal_e,      &
     &         internal_flag, e_comm, iele_global)
      subroutine check_element_position(txt, nele, x_ele, e_comm)
Function/Subroutine Documentation
check_element_position()
subroutine const_global_element_ids::check_element_position (character(len=kchara), intent(in) txt, integer(kind = kint), intent(in) nele, real(kind = kreal), dimension(nele,3), intent(in) x_ele, type(communication_table), intent(in) e_comm)
Definition at line 131 of file const_global_element_ids.f90.
References calypso_mpi_int::calypso_mpi_allreduce_one_int(), m_machine_parameter::i_debug, calypso_mpi::my_rank, solver_sr_type::solver_send_recv_3_type(), and m_constants::tiny.
Referenced by const_element_comm_table::const_comm_table_by_connenct().
count_number_of_node_stack()
subroutine const_global_element_ids::count_number_of_node_stack (integer(kind = kint), intent(in) nnod, integer(kind = kint_gl), dimension(0:nprocs), intent(inout) istack_nod_list)
Definition at line 32 of file const_global_element_ids.f90.
References calypso_mpi_int::calypso_mpi_allgather_one_int(), and calypso_mpi::nprocs.
Referenced by const_element_comm_tables::const_global_edge_id(), const_element_comm_tables::const_global_numele_list(), const_element_comm_tables::const_global_numnod_list(), const_element_comm_tables::const_global_surface_id(), merged_udt_vtk_file_io::init_merged_ucd(), sph_mhd_rst_io_control::output_spectr_4_snap(), and set_sph_restart_io::set_sph_restart_num_to_io().
count_number_of_node_stack4()
subroutine const_global_element_ids::count_number_of_node_stack4 (integer(kind = kint), intent(in) nnod, integer(kind = kint), dimension(0:nprocs), intent(inout) istack_nod_list)
Definition at line 61 of file const_global_element_ids.f90.
References calypso_mpi_int::calypso_mpi_allgather_one_int().
Referenced by para_const_kemoview_mesh::collect_surf_mesh_4_viewer().
set_global_ele_id()
subroutine const_global_element_ids::set_global_ele_id (character(len=kchara), intent(in) txt, integer(kind = kint), intent(in) nele, integer(kind = kint_gl), dimension(0:nprocs), intent(in) istack_internal_e, integer(kind = kint), dimension(nele), intent(in) internal_flag, type(communication_table), intent(in) e_comm, integer(kind = kint_gl), dimension(nele), intent(inout) iele_global)
Definition at line 90 of file const_global_element_ids.f90.
References calypso_mpi::my_rank, and solver_sr_type::solver_send_recv_int8_type().
Referenced by const_element_comm_tables::const_global_edge_id(), const_element_comm_tables::const_global_element_id(), and const_element_comm_tables::const_global_surface_id().