CALYPSO: m_base_field_labels Module Reference
m_base_field_labels Module Reference
Functions/Subroutines
logical function check_base_vector (field_name)
logical function check_base_scalar (field_name)
integer(kind=kint) function num_base_fields ()
subroutine set_base_field_names (n_comps, names, maths)
Variables
integer(kind=kint), parameter, private nfld_base = 25
type(field_def), parameter velocity = field_def(n_comp = n_vector, name = 'velocity', math = '$ u_{i} $')
Field label for velocity \(u_{i} \).
type(field_def), parameter vorticity = field_def(n_comp = n_vector, name = 'vorticity', math = '$ \omega_{i}' // ' = e_{ijk} \partial_{j} u_{k} $')
Field label for vorticity \(\omega_{i} = e_{ijk} \partial_{j} u_{k} \).
type(field_def), parameter pressure = field_def(n_comp = n_scalar, name = 'pressure', math = '$ u_{i} $')
Field label for pressure \(p \).
type(field_def), parameter system_rotation = field_def(n_comp = n_vector, name = 'system_Rotation', math = '$ \Omega_{i} $')
System rotation \(\Omega_{i} \).
type(field_def), parameter magnetic_field = field_def(n_comp = n_vector, name = 'magnetic_field', math = '$ B_{i} $')
Field label for magnetic field \(B_{i} \).
type(field_def), parameter vector_potential = field_def(n_comp = n_vector, name = 'vector_potential', math = '$ B_{i} = e_{ijk} \partial_{j} A_{k} $')
Field label for magnetic vector potential \(B_{i} = e_{ijk} \partial_{j} A_{k} \).
type(field_def), parameter current_density = field_def(n_comp = n_vector, name = 'current_density', math = '$ J_{i} = e_{ijk} \partial_{j} B_{k} $')
Field label for current density \(J_{i} = e_{ijk} \partial_{j} B_{k} \).
type(field_def), parameter background_b = field_def(n_comp = n_vector, name = 'background_B', math = '$ B_{0} $')
Field label of backgroupnd magnetic field \(B_{0} \).
type(field_def), parameter magnetic_potential = field_def(n_comp = n_scalar, name = 'magnetic_potential', math = '$ W $')
Field label for magnetic potential \(W \).
type(field_def), parameter scalar_potential = field_def(n_comp = n_scalar, name = 'scalar_potential', math = '$ \varphi $')
Field label for electric potential \(\varphi \).
type(field_def), parameter density = field_def(n_comp = n_scalar, name = 'density', math = '$ \rho $')
Field label for density \(\rho \).
type(field_def), parameter perturbation_density = field_def(n_comp = n_scalar, name = 'perturbation_density', math = '$ \Theta_{\rho} = \rho - \rho_{0} $')
Field label for perturbation of density \(\Theta_{\rho} = \rho - \rho_{0} \).
type(field_def), parameter reference_density = field_def(n_comp = n_scalar, name = 'reference_density', math = '$ \rho_{0} $')
Field label for reference density \(\rho_{0} \).
type(field_def), parameter temperature = field_def(n_comp = n_scalar, name = 'temperature', math = '$ T $')
Field label for temperature \(T \).
type(field_def), parameter perturbation_temp = field_def(n_comp = n_scalar, name = 'perturbation_temp', math = '$ \Theta = T - T_{0} $')
Field label for perturbation of temperature \(\Theta = T - T_{0} \).
type(field_def), parameter reference_temperature = field_def(n_comp = n_scalar, name = 'reference_temperature', math = '$ T_{0} $')
Field label for reference temperature \(T_{0} \).
type(field_def), parameter composition = field_def(n_comp = n_scalar, name = 'composition', math = '$ C $')
Field label for compostiion variation \(C \).
type(field_def), parameter perturbation_composition = field_def(n_comp = n_scalar, name = 'perturbation_composition', math = '$ \Theta_{C} = C - C_{0} $')
Field label for perturbation of composition \(C - C_{0} \).
type(field_def), parameter reference_composition = field_def(n_comp = n_scalar, name = 'reference_composition', math = '$ C_{0} $')
Field label for reference composition \(C_{0} \).
type(field_def), parameter entropy = field_def(n_comp = n_scalar, name = 'entropy', math = '$ S $')
Field label for entropy \(S \).
type(field_def), parameter perturbation_entropy = field_def(n_comp = n_scalar, name = 'perturbation_entropy', math = '$ \Theta_{S} = S - S_{0} $')
Field label for perturbation of entropy \(S - S_{0} \).
type(field_def), parameter reference_entropy = field_def(n_comp = n_scalar, name = 'reference_entropy', math = '$ S_{0} $')
Field label for reference entropy \(S_{0} \).
type(field_def), parameter heat_source = field_def(n_comp = n_scalar, name = 'heat_source', math = '$ q_{T} $')
Field label for heat source \(q_{T} \).
type(field_def), parameter composition_source = field_def(n_comp = n_scalar, name = 'composition_source', math = '$ q_{C} $')
Field label for composion source \(q_{C} \).
type(field_def), parameter entropy_source = field_def(n_comp = n_scalar, name = 'entropy_source', math = '$ q_{S} $')
Field label for entropysource \(q_{S} \).
Function/Subroutine Documentation
check_base_scalar()
logical function m_base_field_labels::check_base_scalar (character(len = kchara), intent(in) field_name)
Definition at line 249 of file m_base_field_labels.f90.
References composition, composition_source, density, entropy, entropy_source, heat_source, magnetic_potential, perturbation_composition, perturbation_density, perturbation_entropy, perturbation_temp, pressure, reference_composition, reference_density, reference_entropy, reference_temperature, scalar_potential, and temperature.
Referenced by set_mhd_field_address::check_scalar_fields(), and t_base_field_labels::set_base_scalar_addresses().
check_base_vector()
logical function m_base_field_labels::check_base_vector (character(len = kchara), intent(in) field_name)
Definition at line 231 of file m_base_field_labels.f90.
References background_b, current_density, magnetic_field, system_rotation, vector_potential, velocity, and vorticity.
Referenced by set_mhd_field_address::check_vector_fields(), and t_base_field_labels::set_base_vector_addresses().
num_base_fields()
integer(kind = kint) function m_base_field_labels::num_base_fields
Definition at line 284 of file m_base_field_labels.f90.
References nfld_base.
set_base_field_names()
subroutine m_base_field_labels::set_base_field_names (integer(kind = kint_4b), dimension(nfld_base), intent(inout) n_comps, character(len = kchara), dimension(nfld_base), intent(inout) names, character(len = kchara), dimension(nfld_base), intent(inout) maths)
Definition at line 291 of file m_base_field_labels.f90.
References background_b, composition, composition_source, current_density, density, entropy, entropy_source, heat_source, magnetic_field, magnetic_potential, perturbation_composition, perturbation_density, perturbation_entropy, perturbation_temp, pressure, reference_composition, reference_density, reference_entropy, reference_temperature, scalar_potential, t_field_labels::set_field_labels(), system_rotation, temperature, vector_potential, velocity, and vorticity.
Variable Documentation
background_b
type(field_def), parameter m_base_field_labels::background_b = field_def(n_comp = n_vector, name = 'background_B', math = '$ B_{0} $')
Field label of backgroupnd magnetic field \(B_{0} \).
Definition at line 112 of file m_base_field_labels.f90.
Referenced by check_base_vector(), set_base_field_names(), and t_base_field_labels::set_base_vector_addresses().
composition
type(field_def), parameter m_base_field_labels::composition = field_def(n_comp = n_scalar, name = 'composition', math = '$ C $')
Field label for compostiion variation \(C \).
Definition at line 170 of file m_base_field_labels.f90.
Referenced by check_base_field::add_field_ctl_4_base_field(), check_workarea_4_explicit::add_field_ctl_4_check_evo(), check_base_forces::add_field_ctl_4_diffusions(), check_energy_fluxes::add_field_ctl_4_ene_flux(), check_base_forces::add_field_ctl_4_field_products(), check_base_forces::add_field_ctl_4_forces(), check_base_field::add_field_ctl_4_grad_field(), check_base_scalar(), set_restart_data::check_scalar_4_fem_rst(), set_sph_restart_io::check_scalar_4_restart(), new_sph_restart::const_assembled_sph_data(), set_sph_boundary_from_file::find_scalar_bc_label(), set_sph_boundary_from_file::num_comp_bc_data(), r_interpolate_sph_data::r_interpolate_sph_rst_from_io(), set_bc_sph_mhd::s_set_bc_sph_mhd(), set_control_4_model::s_set_control_4_model(), set_base_field_names(), t_base_field_labels::set_base_scalar_addresses(), and set_bc_sph_scalars::set_sph_bc_composition_sph().
composition_source
type(field_def), parameter m_base_field_labels::composition_source = field_def(n_comp = n_scalar, name = 'composition_source', math = '$ q_{C} $')
Field label for composion source \(q_{C} \).
Definition at line 214 of file m_base_field_labels.f90.
Referenced by check_base_field::add_field_ctl_4_base_field(), check_base_scalar(), set_restart_data::check_scalar_4_fem_rst(), set_sph_restart_io::check_scalar_4_restart(), r_interpolate_sph_data::r_interpolate_sph_rst_from_io(), set_base_field_names(), and t_base_field_labels::set_base_scalar_addresses().
current_density
type(field_def), parameter m_base_field_labels::current_density = field_def(n_comp = n_vector, name = 'current_density', math = '$ J_{i} = e_{ijk} \partial_{j} B_{k} $')
Field label for current density \(J_{i} = e_{ijk} \partial_{j} B_{k} \).
Definition at line 106 of file m_base_field_labels.f90.
Referenced by check_base_field::add_field_ctl_4_base_field(), check_base_field::add_field_ctl_4_diff_vector(), check_energy_fluxes::add_field_ctl_4_ene_flux(), check_base_forces::add_field_ctl_4_field_products(), check_base_forces::add_field_ctl_4_forces(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_base_vector(), set_base_field_names(), and t_base_field_labels::set_base_vector_addresses().
density
type(field_def), parameter m_base_field_labels::density = field_def(n_comp = n_scalar, name = 'density', math = '$ \rho $')
Field label for density \(\rho \).
Definition at line 132 of file m_base_field_labels.f90.
Referenced by check_base_field::add_field_ctl_4_base_field(), check_base_field::add_field_ctl_4_grad_field(), check_base_scalar(), set_base_field_names(), and t_base_field_labels::set_base_scalar_addresses().
entropy
type(field_def), parameter m_base_field_labels::entropy = field_def(n_comp = n_scalar, name = 'entropy', math = '$ S $')
Field label for entropy \(S \).
Definition at line 189 of file m_base_field_labels.f90.
Referenced by check_base_field::add_field_ctl_4_base_field(), check_base_field::add_field_ctl_4_grad_field(), check_base_scalar(), set_sph_restart_io::check_scalar_4_restart(), set_sph_boundary_from_file::find_scalar_bc_label(), set_sph_boundary_from_file::num_comp_bc_data(), r_interpolate_sph_data::r_interpolate_sph_rst_from_io(), set_base_field_names(), and t_base_field_labels::set_base_scalar_addresses().
entropy_source
type(field_def), parameter m_base_field_labels::entropy_source = field_def(n_comp = n_scalar, name = 'entropy_source', math = '$ q_{S} $')
Field label for entropysource \(q_{S} \).
Definition at line 220 of file m_base_field_labels.f90.
Referenced by check_base_field::add_field_ctl_4_base_field(), check_base_scalar(), set_sph_restart_io::check_scalar_4_restart(), r_interpolate_sph_data::r_interpolate_sph_rst_from_io(), set_base_field_names(), and t_base_field_labels::set_base_scalar_addresses().
heat_source
type(field_def), parameter m_base_field_labels::heat_source = field_def(n_comp = n_scalar, name = 'heat_source', math = '$ q_{T} $')
Field label for heat source \(q_{T} \).
Definition at line 208 of file m_base_field_labels.f90.
Referenced by check_base_field::add_field_ctl_4_base_field(), check_base_scalar(), set_restart_data::check_scalar_4_fem_rst(), set_sph_restart_io::check_scalar_4_restart(), r_interpolate_sph_data::r_interpolate_sph_rst_from_io(), set_base_field_names(), t_base_field_labels::set_base_scalar_addresses(), and set_control_4_pickup_sph::set_ctl_params_no_heat_nu().
magnetic_field
type(field_def), parameter m_base_field_labels::magnetic_field = field_def(n_comp = n_vector, name = 'magnetic_field', math = '$ B_{i} $')
Field label for magnetic field \(B_{i} \).
Definition at line 94 of file m_base_field_labels.f90.
Referenced by check_base_field::add_field_ctl_4_base_field(), check_base_field::add_field_ctl_4_diff_vector(), check_base_forces::add_field_ctl_4_diffusions(), check_energy_fluxes::add_field_ctl_4_ene_flux(), add_nodal_fields_4_mhd::add_field_ctl_4_evo_magne(), check_base_forces::add_field_ctl_4_field_products(), check_base_forces::add_field_ctl_4_forces(), check_base_field::add_field_ctl_4_grad_field(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_base_vector(), set_restart_data::check_vector_4_fem_rst(), set_sph_restart_io::check_vector_4_restart(), global_field_4_dynamobench::copy_energy_4_dynamobench(), global_field_4_dynamobench::copy_icore_energy_4_dbench(), convert_from_rayleigh_rst::cvt_each_field_from_rayleigh(), assemble_sph_fields::extend_potential_magne(), set_sph_boundary_from_file::find_vector_bc_label(), t_energy_label_parameters::init_energy_labels_base(), pickup_gauss_coefficients::init_gauss_coefs_4_monitor(), set_sph_boundary_from_file::num_comp_bc_data(), r_interpolate_sph_data::r_interpolate_sph_rst_from_io(), set_merged_restart_data::rescale_4_magne(), set_bc_sph_mhd::s_set_bc_sph_mhd(), set_control_4_model::s_set_control_4_model(), set_base_field_names(), t_base_field_labels::set_base_vector_addresses(), input_control_dynamobench::set_ctl_params_dynamobench(), rayleigh_restart_io::set_rayleigh_restart_field(), rayleigh_restart_io::set_rayleigh_rst_file_name(), set_bc_sph_mhd::set_sph_bc_magne_sph(), r_interpolate_sph_data::set_sph_magne_address(), and output_sph_m_square_file::write_total_energy_to_screen().
magnetic_potential
type(field_def), parameter m_base_field_labels::magnetic_potential = field_def(n_comp = n_scalar, name = 'magnetic_potential', math = '$ W $')
Field label for magnetic potential \(W \).
Definition at line 119 of file m_base_field_labels.f90.
Referenced by check_base_field::add_field_ctl_4_base_field(), check_workarea_4_explicit::add_field_ctl_4_check_evo(), check_base_scalar(), set_restart_data::check_scalar_4_fem_rst(), r_interpolate_sph_data::r_interpolate_sph_rst_from_io(), set_merged_restart_data::rescale_4_magne(), set_base_field_names(), and t_base_field_labels::set_base_scalar_addresses().
nfld_base
integer(kind = kint), parameter, private m_base_field_labels::nfld_base = 25 private
Definition at line 65 of file m_base_field_labels.f90.
Referenced by num_base_fields().
perturbation_composition
type(field_def), parameter m_base_field_labels::perturbation_composition = field_def(n_comp = n_scalar, name = 'perturbation_composition', math = '$ \Theta_{C} = C - C_{0} $')
Field label for perturbation of composition \(C - C_{0} \).
Definition at line 176 of file m_base_field_labels.f90.
Referenced by add_nodal_fields_4_mhd::add_ctl_4_forces(), check_base_field::add_field_ctl_4_base_field(), check_energy_fluxes::add_field_ctl_4_ene_flux(), check_base_forces::add_field_ctl_4_forces(), check_base_field::add_field_ctl_4_grad_field(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_base_scalar(), set_base_field_names(), and t_base_field_labels::set_base_scalar_addresses().
perturbation_density
type(field_def), parameter m_base_field_labels::perturbation_density = field_def(n_comp = n_scalar, name = 'perturbation_density', math = '$ \Theta_{\rho} = \rho - \rho_{0} $')
Field label for perturbation of density \(\Theta_{\rho} = \rho - \rho_{0} \).
Definition at line 138 of file m_base_field_labels.f90.
Referenced by check_base_field::add_field_ctl_4_base_field(), check_base_field::add_field_ctl_4_grad_field(), check_base_scalar(), set_base_field_names(), and t_base_field_labels::set_base_scalar_addresses().
perturbation_entropy
type(field_def), parameter m_base_field_labels::perturbation_entropy = field_def(n_comp = n_scalar, name = 'perturbation_entropy', math = '$ \Theta_{S} = S - S_{0} $')
Field label for perturbation of entropy \(S - S_{0} \).
Definition at line 195 of file m_base_field_labels.f90.
Referenced by check_base_field::add_field_ctl_4_base_field(), check_base_field::add_field_ctl_4_grad_field(), check_base_scalar(), set_base_field_names(), and t_base_field_labels::set_base_scalar_addresses().
perturbation_temp
type(field_def), parameter m_base_field_labels::perturbation_temp = field_def(n_comp = n_scalar, name = 'perturbation_temp', math = '$ \Theta = T - T_{0} $')
Field label for perturbation of temperature \(\Theta = T - T_{0} \).
Definition at line 157 of file m_base_field_labels.f90.
Referenced by add_nodal_fields_4_mhd::add_ctl_4_forces(), check_base_field::add_field_ctl_4_base_field(), check_energy_fluxes::add_field_ctl_4_ene_flux(), check_base_forces::add_field_ctl_4_forces(), check_base_field::add_field_ctl_4_grad_field(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_base_scalar(), set_base_field_names(), and t_base_field_labels::set_base_scalar_addresses().
pressure
type(field_def), parameter m_base_field_labels::pressure = field_def(n_comp = n_scalar, name = 'pressure', math = '$ u_{i} $')
Field label for pressure \(p \).
Definition at line 81 of file m_base_field_labels.f90.
Referenced by check_base_field::add_field_ctl_4_base_field(), check_workarea_4_explicit::add_field_ctl_4_check_evo(), check_base_forces::add_field_ctl_4_forces(), check_base_scalar(), set_restart_data::check_scalar_4_fem_rst(), convert_from_rayleigh_rst::cvt_each_field_from_rayleigh(), r_interpolate_sph_data::r_interpolate_sph_rst_from_io(), set_base_field_names(), t_base_field_labels::set_base_scalar_addresses(), rayleigh_restart_io::set_rayleigh_restart_field(), and rayleigh_restart_io::set_rayleigh_rst_file_name().
reference_composition
type(field_def), parameter m_base_field_labels::reference_composition = field_def(n_comp = n_scalar, name = 'reference_composition', math = '$ C_{0} $')
Field label for reference composition \(C_{0} \).
Definition at line 182 of file m_base_field_labels.f90.
Referenced by add_nodal_fields_4_mhd::add_ctl_4_ref_temp(), check_base_field::add_field_ctl_4_base_field(), check_base_field::add_field_ctl_4_grad_field(), check_base_scalar(), set_base_field_names(), and t_base_field_labels::set_base_scalar_addresses().
reference_density
type(field_def), parameter m_base_field_labels::reference_density = field_def(n_comp = n_scalar, name = 'reference_density', math = '$ \rho_{0} $')
Field label for reference density \(\rho_{0} \).
Definition at line 144 of file m_base_field_labels.f90.
Referenced by check_base_field::add_field_ctl_4_base_field(), check_base_field::add_field_ctl_4_grad_field(), check_base_scalar(), set_base_field_names(), and t_base_field_labels::set_base_scalar_addresses().
reference_entropy
type(field_def), parameter m_base_field_labels::reference_entropy = field_def(n_comp = n_scalar, name = 'reference_entropy', math = '$ S_{0} $')
Field label for reference entropy \(S_{0} \).
Definition at line 201 of file m_base_field_labels.f90.
Referenced by check_base_field::add_field_ctl_4_base_field(), check_base_field::add_field_ctl_4_grad_field(), check_base_scalar(), set_base_field_names(), and t_base_field_labels::set_base_scalar_addresses().
reference_temperature
type(field_def), parameter m_base_field_labels::reference_temperature = field_def(n_comp = n_scalar, name = 'reference_temperature', math = '$ T_{0} $')
Field label for reference temperature \(T_{0} \).
Definition at line 163 of file m_base_field_labels.f90.
Referenced by add_nodal_fields_4_mhd::add_ctl_4_ref_temp(), check_base_field::add_field_ctl_4_base_field(), check_base_field::add_field_ctl_4_grad_field(), check_base_scalar(), set_base_field_names(), and t_base_field_labels::set_base_scalar_addresses().
scalar_potential
type(field_def), parameter m_base_field_labels::scalar_potential = field_def(n_comp = n_scalar, name = 'scalar_potential', math = '$ \varphi $')
Field label for electric potential \(\varphi \).
Definition at line 125 of file m_base_field_labels.f90.
Referenced by check_base_field::add_field_ctl_4_base_field(), check_base_scalar(), set_base_field_names(), and t_base_field_labels::set_base_scalar_addresses().
system_rotation
type(field_def), parameter m_base_field_labels::system_rotation = field_def(n_comp = n_vector, name = 'system_Rotation', math = '$ \Omega_{i} $')
System rotation \(\Omega_{i} \).
Definition at line 87 of file m_base_field_labels.f90.
Referenced by check_base_vector(), set_base_field_names(), and t_base_field_labels::set_base_vector_addresses().
temperature
type(field_def), parameter m_base_field_labels::temperature = field_def(n_comp = n_scalar, name = 'temperature', math = '$ T $')
Field label for temperature \(T \).
Definition at line 151 of file m_base_field_labels.f90.
Referenced by check_base_field::add_field_ctl_4_base_field(), check_workarea_4_explicit::add_field_ctl_4_check_evo(), check_base_forces::add_field_ctl_4_diffusions(), check_energy_fluxes::add_field_ctl_4_ene_flux(), check_base_forces::add_field_ctl_4_field_products(), check_base_forces::add_field_ctl_4_forces(), check_base_field::add_field_ctl_4_grad_field(), check_base_scalar(), set_restart_data::check_scalar_4_fem_rst(), set_sph_restart_io::check_scalar_4_restart(), new_sph_restart::const_assembled_sph_data(), convert_from_rayleigh_rst::cvt_each_field_from_rayleigh(), set_sph_boundary_from_file::find_scalar_bc_label(), set_sph_boundary_from_file::num_comp_bc_data(), r_interpolate_sph_data::r_interpolate_sph_rst_from_io(), set_bc_sph_mhd::s_set_bc_sph_mhd(), set_control_4_model::s_set_control_4_model(), set_base_field_names(), t_base_field_labels::set_base_scalar_addresses(), input_control_dynamobench::set_ctl_params_dynamobench(), rayleigh_restart_io::set_rayleigh_restart_field(), rayleigh_restart_io::set_rayleigh_rst_file_name(), and set_bc_sph_scalars::set_sph_bc_temp_sph().
vector_potential
type(field_def), parameter m_base_field_labels::vector_potential = field_def(n_comp = n_vector, name = 'vector_potential', math = '$ B_{i} = e_{ijk} \partial_{j} A_{k} $')
Field label for magnetic vector potential \(B_{i} = e_{ijk} \partial_{j} A_{k} \).
Definition at line 100 of file m_base_field_labels.f90.
Referenced by check_base_field::add_field_ctl_4_base_field(), check_base_field::add_field_ctl_4_diff_vector(), check_base_forces::add_field_ctl_4_diffusions(), add_nodal_fields_4_mhd::add_field_ctl_4_evo_magne(), check_base_forces::add_field_ctl_4_field_products(), check_base_field::add_field_ctl_4_grad_field(), check_base_vector(), set_restart_data::check_vector_4_fem_rst(), set_merged_restart_data::rescale_4_magne(), set_control_4_model::s_set_control_4_model(), set_base_field_names(), and t_base_field_labels::set_base_vector_addresses().
velocity
type(field_def), parameter m_base_field_labels::velocity = field_def(n_comp = n_vector, name = 'velocity', math = '$ u_{i} $')
Field label for velocity \(u_{i} \).
Definition at line 69 of file m_base_field_labels.f90.
Referenced by check_base_field::add_field_ctl_4_base_field(), check_workarea_4_explicit::add_field_ctl_4_check_evo(), check_base_field::add_field_ctl_4_diff_vector(), check_base_forces::add_field_ctl_4_diffusions(), check_energy_fluxes::add_field_ctl_4_ene_flux(), check_base_forces::add_field_ctl_4_field_products(), check_base_forces::add_field_ctl_4_forces(), check_base_field::add_field_ctl_4_grad_field(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_base_vector(), set_restart_data::check_vector_4_fem_rst(), set_sph_restart_io::check_vector_4_restart(), global_field_4_dynamobench::copy_energy_4_dynamobench(), convert_from_rayleigh_rst::cvt_each_field_from_rayleigh(), set_sph_boundary_from_file::find_vector_bc_label(), t_energy_label_parameters::init_energy_labels_base(), set_sph_boundary_from_file::num_comp_bc_data(), r_interpolate_sph_data::r_interpolate_sph_rst_from_io(), set_bc_sph_mhd::s_set_bc_sph_mhd(), set_control_4_model::s_set_control_4_model(), set_base_field_names(), t_base_field_labels::set_base_vector_addresses(), input_control_dynamobench::set_ctl_params_dynamobench(), rayleigh_restart_io::set_rayleigh_restart_field(), rayleigh_restart_io::set_rayleigh_rst_file_name(), set_bc_flag_sph_velo::set_sph_velo_cmb_flag(), set_bc_flag_sph_velo::set_sph_velo_icb_flag(), and output_sph_m_square_file::write_total_energy_to_screen().
vorticity
type(field_def), parameter m_base_field_labels::vorticity = field_def(n_comp = n_vector, name = 'vorticity', math = '$ \omega_{i}' // ' = e_{ijk} \partial_{j} u_{k} $')
Field label for vorticity \(\omega_{i} = e_{ijk} \partial_{j} u_{k} \).
Definition at line 75 of file m_base_field_labels.f90.
Referenced by check_base_field::add_field_ctl_4_base_field(), check_base_field::add_field_ctl_4_diff_vector(), check_base_forces::add_field_ctl_4_diffusions(), check_base_forces::add_field_ctl_4_field_products(), check_base_forces::add_field_ctl_4_forces(), add_sph_mhd_fields_2_ctl::add_field_name_4_sph_mhd(), check_base_vector(), set_sph_boundary_from_file::find_vector_bc_label(), set_sph_boundary_from_file::num_comp_bc_data(), r_interpolate_sph_data::r_interpolate_sph_rst_from_io(), set_base_field_names(), and t_base_field_labels::set_base_vector_addresses().