CALYPSO: select_zonal_4_legendre Module Reference
select_zonal_4_legendre Module Reference
Set order of spheherical harmonics modes.
Functions/Subroutines
subroutine sel_zonal_ordering_4_leg_trns (iflag_rlm_distribute, ndomain_m, ltr, m_folding, nth, nph, jdx_fsph, mdx_4_lgd)
subroutine, private zonal_wavenum_list_test (ndomain_m, ltr, m_folding, nth, nph, jdx_fsph, mdx_4_lgd, ip_tmp)
Variables
integer(kind=kint), parameter id_cyclic_eq_transform = 0
integer(kind=kint), parameter id_cyclic_eq_mode = 1
integer(kind=kint), parameter id_cyclic_eq_trans_neib = 2
integer(kind=kint), parameter id_cyclic_eq_mode_neib = 3
integer(kind=kint), parameter id_simple_rlm_distribute = 10
integer(kind=kint), parameter id_v1_rlm_distribute = 100
integer(kind=kint), parameter id_test_distribute = 999
Detailed Description
Set order of spheherical harmonics modes.
      subroutine sel_zonal_ordering_4_leg_trns                        &
     &         (iflag_rlm_distribute, ndomain_m,                      &
     &          ltr, m_folding, nth, nph, jdx_fsph, mdx_4_lgd)
Function/Subroutine Documentation
sel_zonal_ordering_4_leg_trns()
subroutine select_zonal_4_legendre::sel_zonal_ordering_4_leg_trns (integer(kind = kint), intent(in) iflag_rlm_distribute, integer(kind = kint), intent(in) ndomain_m, integer(kind = kint), intent(in) ltr, integer(kind = kint), intent(in) m_folding, integer(kind = kint), intent(in) nth, integer(kind = kint), intent(in) nph, integer(kind = kint), dimension(-nth:nth), intent(inout) jdx_fsph, integer(kind = kint), dimension(0:nph), intent(inout) mdx_4_lgd)
Definition at line 40 of file select_zonal_4_legendre.f90.
References id_cyclic_eq_mode, id_cyclic_eq_mode_neib, id_simple_rlm_distribute, id_test_distribute, id_v1_rlm_distribute, zonal_wavenumber_4_legendre::set_domain_by_eq_leg_modes(), zonal_wavenumber_4_legendre::set_domain_by_eq_leg_trns(), zonal_wavenumber_4_legendre::set_local_sph_back_order(), zonal_wavenumber_4_legendre::set_local_sph_fwd_order(), zonal_wavenumber_4_legendre::set_local_sph_neib_order(), and zonal_wavenum_list_test().
Referenced by const_each_global_sph_list::const_global_rlm_modes().
zonal_wavenum_list_test()
subroutine, private select_zonal_4_legendre::zonal_wavenum_list_test (integer(kind = kint), intent(in) ndomain_m, integer(kind = kint), intent(in) ltr, integer(kind = kint), intent(in) m_folding, integer(kind = kint), intent(in) nth, integer(kind = kint), intent(in) nph, integer(kind = kint), dimension(-nth:nth), intent(inout) jdx_fsph, integer(kind = kint), dimension(0:nph), intent(inout) mdx_4_lgd, integer(kind = kint), dimension(0:ltr), intent(inout) ip_tmp) private
Definition at line 105 of file select_zonal_4_legendre.f90.
References zonal_wavenumber_4_legendre::set_domain_by_eq_leg_modes(), and zonal_wavenumber_4_legendre::set_local_sph_fwd_order().
Referenced by sel_zonal_ordering_4_leg_trns().
Variable Documentation
id_cyclic_eq_mode
integer(kind = kint), parameter select_zonal_4_legendre::id_cyclic_eq_mode = 1
Definition at line 22 of file select_zonal_4_legendre.f90.
Referenced by sel_zonal_ordering_4_leg_trns(), and set_control_sph_subdomains::set_inner_loop_4_sph_shell().
id_cyclic_eq_mode_neib
integer(kind = kint), parameter select_zonal_4_legendre::id_cyclic_eq_mode_neib = 3
Definition at line 25 of file select_zonal_4_legendre.f90.
Referenced by sel_zonal_ordering_4_leg_trns(), and set_control_sph_subdomains::set_inner_loop_4_sph_shell().
id_cyclic_eq_trans_neib
integer(kind = kint), parameter select_zonal_4_legendre::id_cyclic_eq_trans_neib = 2
Definition at line 24 of file select_zonal_4_legendre.f90.
id_cyclic_eq_transform
integer(kind = kint), parameter select_zonal_4_legendre::id_cyclic_eq_transform = 0
Definition at line 21 of file select_zonal_4_legendre.f90.
id_simple_rlm_distribute
integer(kind = kint), parameter select_zonal_4_legendre::id_simple_rlm_distribute = 10
Definition at line 27 of file select_zonal_4_legendre.f90.
Referenced by sel_zonal_ordering_4_leg_trns(), and set_control_sph_subdomains::set_inner_loop_4_sph_shell().
id_test_distribute
integer(kind = kint), parameter select_zonal_4_legendre::id_test_distribute = 999
Definition at line 30 of file select_zonal_4_legendre.f90.
Referenced by sel_zonal_ordering_4_leg_trns(), and set_control_sph_subdomains::set_inner_loop_4_sph_shell().
id_v1_rlm_distribute
integer(kind = kint), parameter select_zonal_4_legendre::id_v1_rlm_distribute = 100
Definition at line 29 of file select_zonal_4_legendre.f90.
Referenced by sel_zonal_ordering_4_leg_trns(), and set_control_sph_subdomains::set_inner_loop_4_sph_shell().