CALYPSO: t_ctl_data_node_boundary Module Reference
t_ctl_data_node_boundary Module Reference
Data Types
type node_bc_control
Functions/Subroutines
subroutine read_bc_4_node_ctl (id_control, hd_block, nbc_ctl, c_buf)
subroutine bcast_bc_4_node_ctl (nbc_ctl)
subroutine dealloc_bc_4_node_ctl (nbc_ctl)
Variables
character(len=kchara), parameter, private hd_n_bc_temp = 'bc_temperature'
character(len=kchara), parameter, private hd_n_bc_velo = 'bc_velocity'
character(len=kchara), parameter, private hd_n_bc_press = 'bc_pressure'
character(len=kchara), parameter, private hd_n_bc_composit = 'bc_composition'
character(len=kchara), parameter, private hd_n_bc_magne = 'bc_magnetic_field'
character(len=kchara), parameter, private hd_n_bc_mag_p = 'bc_electric_potential'
character(len=kchara), parameter, private hd_n_bc_vect_p = 'bc_vector_potential'
character(len=kchara), parameter, private hd_n_bc_currect = 'bc_current'
Function/Subroutine Documentation
bcast_bc_4_node_ctl()
subroutine t_ctl_data_node_boundary::bcast_bc_4_node_ctl (type(node_bc_control), intent(inout) nbc_ctl)
Definition at line 244 of file t_ctl_data_node_boundary.f90.
References bcast_control_arrays::bcast_ctl_array_c2r(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by t_ctl_data_mhd_model::bcast_sph_mhd_model().
dealloc_bc_4_node_ctl()
subroutine t_ctl_data_node_boundary::dealloc_bc_4_node_ctl (type(node_bc_control), intent(inout) nbc_ctl)
Definition at line 267 of file t_ctl_data_node_boundary.f90.
References t_control_array_chara2real::dealloc_control_array_c2_r().
Referenced by t_ctl_data_mhd_model::dealloc_sph_mhd_model().
read_bc_4_node_ctl()
subroutine t_ctl_data_node_boundary::read_bc_4_node_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(node_bc_control), intent(inout) nbc_ctl, type(buffer_for_control), intent(inout) c_buf)
Definition at line 202 of file t_ctl_data_node_boundary.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_n_bc_composit, hd_n_bc_currect, hd_n_bc_mag_p, hd_n_bc_magne, hd_n_bc_press, hd_n_bc_temp, hd_n_bc_vect_p, hd_n_bc_velo, t_read_control_elements::load_one_line_from_control(), and t_control_array_chara2real::read_control_array_c2_r().
Referenced by t_ctl_data_mhd_model::read_sph_mhd_model().
Variable Documentation
hd_n_bc_composit
character(len=kchara), parameter, private t_ctl_data_node_boundary::hd_n_bc_composit = 'bc_composition' private
Definition at line 181 of file t_ctl_data_node_boundary.f90.
Referenced by read_bc_4_node_ctl().
hd_n_bc_currect
character(len=kchara), parameter, private t_ctl_data_node_boundary::hd_n_bc_currect = 'bc_current' private
Definition at line 189 of file t_ctl_data_node_boundary.f90.
Referenced by read_bc_4_node_ctl().
hd_n_bc_mag_p
character(len=kchara), parameter, private t_ctl_data_node_boundary::hd_n_bc_mag_p = 'bc_electric_potential' private
Definition at line 185 of file t_ctl_data_node_boundary.f90.
Referenced by read_bc_4_node_ctl().
hd_n_bc_magne
character(len=kchara), parameter, private t_ctl_data_node_boundary::hd_n_bc_magne = 'bc_magnetic_field' private
Definition at line 183 of file t_ctl_data_node_boundary.f90.
Referenced by read_bc_4_node_ctl().
hd_n_bc_press
character(len=kchara), parameter, private t_ctl_data_node_boundary::hd_n_bc_press = 'bc_pressure' private
Definition at line 179 of file t_ctl_data_node_boundary.f90.
Referenced by read_bc_4_node_ctl().
hd_n_bc_temp
character(len=kchara), parameter, private t_ctl_data_node_boundary::hd_n_bc_temp = 'bc_temperature' private
Definition at line 175 of file t_ctl_data_node_boundary.f90.
Referenced by read_bc_4_node_ctl().
hd_n_bc_vect_p
character(len=kchara), parameter, private t_ctl_data_node_boundary::hd_n_bc_vect_p = 'bc_vector_potential' private
Definition at line 187 of file t_ctl_data_node_boundary.f90.
Referenced by read_bc_4_node_ctl().
hd_n_bc_velo
character(len=kchara), parameter, private t_ctl_data_node_boundary::hd_n_bc_velo = 'bc_velocity' private
Definition at line 177 of file t_ctl_data_node_boundary.f90.
Referenced by read_bc_4_node_ctl().