CALYPSO: gz_mpi_integer_list_io Module Reference
gz_mpi_integer_list_io Module Reference
Data IO routines for spectrum data.
Functions/Subroutines
subroutine gz_mpi_read_ele_connect (IO_param, nele, nnod_4_ele, id_global, ie)
subroutine gz_mpi_read_element_type (IO_param, ncolumn, num, int_dat)
subroutine gz_mpi_read_int_list (IO_param, nele, ncomp, ivect)
subroutine gz_mpi_write_ele_connect (IO_param, nele, nnod_4_ele, id_global, ie)
subroutine gz_mpi_write_element_type (IO_param, ncolumn, num, int_dat)
subroutine gz_mpi_write_int_list (IO_param, nele, ncomp, ivect)
Variables
type(buffer_4_gzip) zbuf
Detailed Description
Data IO routines for spectrum data.
      subroutine gz_mpi_read_ele_connect                              &
     &         (IO_param, nele, nnod_4_ele, id_global, ie)
      subroutine gz_mpi_read_element_type                             &
     &         (IO_param, ncolumn, num, int_dat)
      subroutine gz_mpi_read_int_list(IO_param, nele, ncomp, ivect)
      subroutine gz_mpi_write_ele_connect                             &
     &         (IO_param, nele, nnod_4_ele, id_global, ie)
      subroutine gz_mpi_write_element_type                            &
     &         (IO_param, ncolumn, num, int_dat)
      subroutine gz_mpi_write_int_list(IO_param, nele, ncomp, ivect)
Function/Subroutine Documentation
gz_mpi_read_ele_connect()
subroutine gz_mpi_integer_list_io::gz_mpi_read_ele_connect (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) nele, integer(kind=kint), intent(in) nnod_4_ele, integer(kind=kint_gl), dimension(nele), intent(inout) id_global, integer(kind=kint), dimension(nele, nnod_4_ele), intent(inout) ie)
Definition at line 43 of file gz_MPI_integer_list_IO.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), gz_mpi_ascii_data_io::gz_mpi_read_charahead(), zlib_cvt_ascii_ele_connect::infleate_ele_connect(), data_io_to_textline::len_byte_stack_textline(), data_io_to_textline::read_byte_stack_textline(), and gz_mpi_domain_data_io::zbuf.
Referenced by gz_mpi_element_connect_io::gz_mpi_read_element_info(), and gz_mpi_spherical_model_io::gz_mpi_read_gl_nodes_sph().
gz_mpi_read_element_type()
subroutine gz_mpi_integer_list_io::gz_mpi_read_element_type (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) ncolumn, integer(kind=kint), intent(in) num, integer(kind=kint), dimension(num), intent(inout) int_dat)
Definition at line 83 of file gz_MPI_integer_list_IO.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), gz_mpi_ascii_data_io::gz_mpi_read_charahead(), zlib_cvt_ascii_comm_tbl::infleate_element_type(), data_io_to_textline::len_byte_stack_textline(), data_io_to_textline::read_byte_stack_textline(), and gz_mpi_domain_data_io::zbuf.
Referenced by gz_mpi_element_connect_io::gz_mpi_read_element_info().
gz_mpi_read_int_list()
subroutine gz_mpi_integer_list_io::gz_mpi_read_int_list (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) nele, integer(kind=kint), intent(in) ncomp, integer(kind=kint), dimension(nele, ncomp), intent(inout) ivect)
Definition at line 122 of file gz_MPI_integer_list_IO.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), gz_mpi_ascii_data_io::gz_mpi_read_charahead(), zlib_cvt_ascii_ele_connect::infleate_ele_int_list(), data_io_to_textline::len_byte_stack_textline(), data_io_to_textline::read_byte_stack_textline(), and gz_mpi_domain_data_io::zbuf.
Referenced by gz_mpi_element_connect_io::gz_mpi_read_edge_4_element(), and gz_mpi_element_connect_io::gz_mpi_read_surface_4_element().
gz_mpi_write_ele_connect()
subroutine gz_mpi_integer_list_io::gz_mpi_write_ele_connect (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind=kint), intent(in) nele, integer(kind=kint), intent(in) nnod_4_ele, integer(kind=kint_gl), dimension(nele), intent(in) id_global, integer(kind=kint), dimension(nele,nnod_4_ele), intent(in) ie)
Definition at line 160 of file gz_MPI_integer_list_IO.f90.
References t_buffer_4_gzip::dealloc_zip_buffer(), zlib_cvt_ascii_ele_connect::defleate_ele_connect(), gz_mpi_ascii_data_io::gz_mpi_write_stack_over_domain(), and gz_mpi_domain_data_io::zbuf.
Referenced by gz_mpi_element_connect_io::gz_mpi_write_element_info(), gz_mpi_spherical_model_io::gz_mpi_write_gl_nodes_sph(), and gz_mpi_viewer_mesh_file_io::gz_write_viewer_mesh_infos().
gz_mpi_write_element_type()
subroutine gz_mpi_integer_list_io::gz_mpi_write_element_type (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint), intent(in) ncolumn, integer(kind = kint), intent(in) num, integer(kind=kint), dimension(num), intent(in) int_dat)
Definition at line 194 of file gz_MPI_integer_list_IO.f90.
References t_buffer_4_gzip::dealloc_zip_buffer(), zlib_cvt_ascii_comm_tbl::defleate_element_type(), gz_mpi_ascii_data_io::gz_mpi_write_stack_over_domain(), and gz_mpi_domain_data_io::zbuf.
Referenced by gz_mpi_element_connect_io::gz_mpi_write_element_info(), and gz_mpi_viewer_mesh_file_io::gz_write_viewer_mesh_infos().
gz_mpi_write_int_list()
subroutine gz_mpi_integer_list_io::gz_mpi_write_int_list (type(calypso_mpi_io_params), intent(inout) IO_param, integer(kind = kint), intent(in) nele, integer(kind = kint), intent(in) ncomp, integer(kind = kint), dimension(nele,ncomp), intent(in) ivect)
Definition at line 227 of file gz_MPI_integer_list_IO.f90.
References t_buffer_4_gzip::dealloc_zip_buffer(), zlib_cvt_ascii_ele_connect::defleate_ele_int_list(), gz_mpi_ascii_data_io::gz_mpi_write_stack_over_domain(), and gz_mpi_domain_data_io::zbuf.
Referenced by gz_mpi_element_connect_io::gz_mpi_write_edge_4_element(), and gz_mpi_element_connect_io::gz_mpi_write_surface_4_element().
Variable Documentation
zbuf
type(buffer_4_gzip) gz_mpi_integer_list_io::zbuf
Definition at line 35 of file gz_MPI_integer_list_IO.f90.