CALYPSO: m_intersection_data_4 Module Reference
m_intersection_data_4 Module Reference
Variables
integer(kind=kint), parameter, private nnod_tri = 3
integer(kind=kint), parameter nkind_etype_4 = 4
integer(kind=kint), parameter num_tri_4 = 2
integer(kind=kint), parameter num_patch_4 = 2
integer(kind=kint), dimension(3), parameter itri_2_patch_3 = (/1, 2, 3/)
integer(kind=kint), dimension(nkind_etype_4), parameter iflag_psf_etype_4p = (/ 65, 130, 20, 40/)
integer(kind=kint), dimension(nkind_etype_4), parameter iflag_psf_etype_4n = (/190, 125, 235, 215/)
integer(kind=kint), dimension(nnod_tri, num_tri_4, nkind_etype_4), parameter iedge_tri_4p = reshape((/ 4, 1, 9, 7, 6, 11, 1, 2, 10, 8, 7, 12, 2, 3, 11, 5, 8, 9, 3, 4, 12, 6, 5, 10 /), shape=(/nnod_tri,num_tri_4, nkind_etype_4/))
integer(kind=kint), dimension(nnod_tri, num_tri_4, nkind_etype_4), parameter iedge_tri_4n = reshape((/ 1, 4, 9, 6, 7, 11, 2, 1, 10, 7, 8, 12, 3, 2, 11, 8, 5, 9, 4, 3, 12, 5, 6, 10/), shape=(/nnod_tri,num_tri_4, nkind_etype_4/))
integer(kind=kint), dimension(nnod_tri, num_patch_4, nkind_etype_4), parameter iedge_4_patch_4p = reshape((/ 4, 1, 9, 7, 6, 11, 1, 2, 10, 8, 7, 12, 2, 3, 11, 5, 8, 9, 3, 4, 12, 6, 5, 10 /), shape=(/nnod_tri,num_patch_4,nkind_etype_4/))
integer(kind=kint), dimension(nnod_tri, num_patch_4, nkind_etype_4), parameter iedge_4_patch_4n = reshape((/ 1, 4, 9, 6, 7, 11, 2, 1, 10, 7, 8, 12, 3, 2, 11, 8, 5, 9, 4, 3, 12, 5, 6, 10/), shape=(/nnod_tri,num_patch_4,nkind_etype_4/))
Variable Documentation
iedge_4_patch_4n
integer(kind = kint), dimension(nnod_tri,num_patch_4,nkind_etype_4), parameter m_intersection_data_4::iedge_4_patch_4n = reshape((/ 1, 4, 9, 6, 7, 11, 2, 1, 10, 7, 8, 12, 3, 2, 11, 8, 5, 9, 4, 3, 12, 5, 6, 10/), shape=(/nnod_tri,num_patch_4,nkind_etype_4/))
Definition at line 68 of file m_intersection_data_4.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
iedge_4_patch_4p
integer(kind = kint), dimension(nnod_tri,num_patch_4,nkind_etype_4), parameter m_intersection_data_4::iedge_4_patch_4p = reshape((/ 4, 1, 9, 7, 6, 11, 1, 2, 10, 8, 7, 12, 2, 3, 11, 5, 8, 9, 3, 4, 12, 6, 5, 10 /), shape=(/nnod_tri,num_patch_4,nkind_etype_4/))
Definition at line 61 of file m_intersection_data_4.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
iedge_tri_4n
integer(kind = kint), dimension(nnod_tri,num_tri_4, nkind_etype_4), parameter m_intersection_data_4::iedge_tri_4n = reshape((/ 1, 4, 9, 6, 7, 11, 2, 1, 10, 7, 8, 12, 3, 2, 11, 8, 5, 9, 4, 3, 12, 5, 6, 10/), shape=(/nnod_tri,num_tri_4, nkind_etype_4/))
Definition at line 53 of file m_intersection_data_4.f90.
iedge_tri_4p
integer(kind = kint), dimension(nnod_tri,num_tri_4, nkind_etype_4), parameter m_intersection_data_4::iedge_tri_4p = reshape((/ 4, 1, 9, 7, 6, 11, 1, 2, 10, 8, 7, 12, 2, 3, 11, 5, 8, 9, 3, 4, 12, 6, 5, 10 /), shape=(/nnod_tri,num_tri_4, nkind_etype_4/))
Definition at line 46 of file m_intersection_data_4.f90.
iflag_psf_etype_4n
integer(kind = kint), dimension(nkind_etype_4), parameter m_intersection_data_4::iflag_psf_etype_4n = (/190, 125, 235, 215/)
Definition at line 42 of file m_intersection_data_4.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
iflag_psf_etype_4p
integer(kind = kint), dimension(nkind_etype_4), parameter m_intersection_data_4::iflag_psf_etype_4p = (/ 65, 130, 20, 40/)
Definition at line 40 of file m_intersection_data_4.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
itri_2_patch_3
integer(kind = kint), dimension(3), parameter m_intersection_data_4::itri_2_patch_3 = (/1, 2, 3/)
Definition at line 37 of file m_intersection_data_4.f90.
nkind_etype_4
integer(kind = kint), parameter m_intersection_data_4::nkind_etype_4 = 4
Definition at line 34 of file m_intersection_data_4.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
nnod_tri
integer(kind = kint), parameter, private m_intersection_data_4::nnod_tri = 3 private
Definition at line 19 of file m_intersection_data_4.f90.
num_patch_4
integer(kind = kint), parameter m_intersection_data_4::num_patch_4 = 2
Definition at line 36 of file m_intersection_data_4.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
num_tri_4
integer(kind = kint), parameter m_intersection_data_4::num_tri_4 = 2
Definition at line 35 of file m_intersection_data_4.f90.