CALYPSO: gz_mpi_element_connect_io Module Reference
gz_mpi_element_connect_io Module Reference
Data IO routines for element connectivity.
Functions/Subroutines
subroutine gz_mpi_write_element_info (IO_param, ele_IO)
subroutine gz_mpi_write_surface_4_element (IO_param, sfed_IO)
subroutine gz_mpi_write_edge_4_element (IO_param, sfed_IO)
subroutine gz_mpi_read_num_element (IO_param, ele_IO)
subroutine gz_mpi_read_element_info (IO_param, ele_IO)
subroutine gz_mpi_read_surface_4_element (IO_param, sfed_IO)
subroutine gz_mpi_read_edge_4_element (IO_param, sfed_IO)
Detailed Description
Data IO routines for element connectivity.
      subroutine gz_mpi_write_element_info(IO_param, ele_IO)
      subroutine gz_mpi_write_surface_4_element(IO_param, sfed_IO)
      subroutine gz_mpi_write_edge_4_element(IO_param, sfed_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(element_data), intent(in) :: ele_IO
        type(surf_edge_IO_data), intent(in) :: sfed_IO
      subroutine gz_mpi_read_num_element(IO_param, ele_IO)
      subroutine gz_mpi_read_element_info(IO_param, ele_IO)
      subroutine gz_mpi_read_surface_4_element(IO_param, sfed_IO)
      subroutine gz_mpi_read_edge_4_element(IO_param, sfed_IO)
        type(calypso_MPI_IO_params), intent(inout) :: IO_param
        type(element_data), intent(inout) :: ele_IO
        type(surf_edge_IO_data), intent(inout) :: sfed_IO
Function/Subroutine Documentation
gz_mpi_read_edge_4_element()
subroutine gz_mpi_element_connect_io::gz_mpi_read_edge_4_element (type(calypso_mpi_io_params), intent(inout) IO_param, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 162 of file gz_MPI_element_connect_IO.f90.
References t_surf_edge_io::alloc_edge_connect_io(), gz_mpi_integer_list_io::gz_mpi_read_int_list(), and gz_mpi_ascii_data_io::gz_mpi_read_num_of_data().
Referenced by gz_mpi_edge_data_io::gz_mpi_read_edge_connect().
gz_mpi_read_element_info()
subroutine gz_mpi_element_connect_io::gz_mpi_read_element_info (type(calypso_mpi_io_params), intent(inout) IO_param, type(element_data), intent(inout) ele_IO)
Definition at line 111 of file gz_MPI_element_connect_IO.f90.
References t_geometry_data::alloc_ele_connectivity(), t_geometry_data::alloc_element_types(), gz_mpi_integer_list_io::gz_mpi_read_ele_connect(), gz_mpi_integer_list_io::gz_mpi_read_element_type(), gz_mpi_ascii_data_io::gz_mpi_read_num_of_data(), m_constants::iten, and set_nnod_4_ele_by_type::s_set_nnod_4_ele_by_type().
Referenced by gz_mpi_edge_data_io::gz_mpi_read_edge_connect(), gz_mpi_mesh_data_io::gz_mpi_read_geometry_data(), and gz_mpi_surface_data_io::gz_mpi_read_surf_connect().
gz_mpi_read_num_element()
subroutine gz_mpi_element_connect_io::gz_mpi_read_num_element (type(calypso_mpi_io_params), intent(inout) IO_param, type(element_data), intent(inout) ele_IO)
Definition at line 99 of file gz_MPI_element_connect_IO.f90.
References gz_mpi_ascii_data_io::gz_mpi_read_num_of_data().
Referenced by gz_mpi_edge_data_io::gz_mpi_read_edge_connect(), gz_mpi_mesh_data_io::gz_mpi_read_num_node_ele(), and gz_mpi_surface_data_io::gz_mpi_read_surf_connect().
gz_mpi_read_surface_4_element()
subroutine gz_mpi_element_connect_io::gz_mpi_read_surface_4_element (type(calypso_mpi_io_params), intent(inout) IO_param, type(surf_edge_io_data), intent(inout) sfed_IO)
Definition at line 143 of file gz_MPI_element_connect_IO.f90.
References t_surf_edge_io::alloc_surface_connect_io(), gz_mpi_integer_list_io::gz_mpi_read_int_list(), and gz_mpi_ascii_data_io::gz_mpi_read_num_of_data().
Referenced by gz_mpi_edge_data_io::gz_mpi_read_edge_connect(), and gz_mpi_surface_data_io::gz_mpi_read_surf_connect().
gz_mpi_write_edge_4_element()
subroutine gz_mpi_element_connect_io::gz_mpi_write_edge_4_element (type(calypso_mpi_io_params), intent(inout) IO_param, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 82 of file gz_MPI_element_connect_IO.f90.
References gz_mpi_integer_list_io::gz_mpi_write_int_list(), and gz_mpi_ascii_data_io::gz_mpi_write_num_of_data().
Referenced by gz_mpi_edge_data_io::gz_mpi_write_edge_connect().
gz_mpi_write_element_info()
subroutine gz_mpi_element_connect_io::gz_mpi_write_element_info (type(calypso_mpi_io_params), intent(inout) IO_param, type(element_data), intent(in) ele_IO)
Definition at line 47 of file gz_MPI_element_connect_IO.f90.
References gz_mpi_integer_list_io::gz_mpi_write_ele_connect(), gz_mpi_integer_list_io::gz_mpi_write_element_type(), gz_mpi_ascii_data_io::gz_mpi_write_num_of_data(), and m_constants::iten.
Referenced by gz_mpi_edge_data_io::gz_mpi_write_edge_connect(), gz_mpi_mesh_data_io::gz_mpi_write_geometry_data(), and gz_mpi_surface_data_io::gz_mpi_write_surf_connect().
gz_mpi_write_surface_4_element()
subroutine gz_mpi_element_connect_io::gz_mpi_write_surface_4_element (type(calypso_mpi_io_params), intent(inout) IO_param, type(surf_edge_io_data), intent(in) sfed_IO)
Definition at line 66 of file gz_MPI_element_connect_IO.f90.
References gz_mpi_integer_list_io::gz_mpi_write_int_list(), and gz_mpi_ascii_data_io::gz_mpi_write_num_of_data().
Referenced by gz_mpi_edge_data_io::gz_mpi_write_edge_connect(), and gz_mpi_surface_data_io::gz_mpi_write_surf_connect().