CALYPSO: cal_products_smp Module Reference
cal_products_smp Module Reference
Functions/Subroutines
subroutine cal_scalar_prod_w_coef_smp (nnod, coef, scalar1, scalar2, prod)
subroutine cal_scalar_prod_no_coef_smp (nnod, scalar1, scalar2, prod)
subroutine cal_dot_prod_w_coef_smp (nnod, coef, vect1, vect2, prod)
subroutine cal_dot_prod_no_coef_smp (nnod, vect1, vect2, prod)
subroutine cal_cross_prod_w_coef_smp (nnod, coef, vect1, vect2, prod)
subroutine cal_cross_prod_no_coef_smp (nnod, vect1, vect2, prod)
subroutine cal_vec_scalar_prod_no_coef_smp (nnod, vect1, scalar, prod)
subroutine cal_vec_scalar_prod_w_coef_smp (nnod, coef, vect1, scalar, prod)
subroutine cal_tensor_vec_prod_no_coef_smp (nnod, tensor, vector, prod)
subroutine cal_scalar_mag_vector_prod_smp (nnod, scalar, vector, prod)
subroutine cal_tri_product_w_coef_smp (nnod, coef, vect1, vect2, vect3, prod)
subroutine vector_vector_prod_smp (nnod, vect1, vect2, prod)
subroutine tensor_tensor_prod_smp (nnod, tensor1, tensor2, prod)
Function/Subroutine Documentation
cal_cross_prod_no_coef_smp()
subroutine cal_products_smp::cal_cross_prod_no_coef_smp (integer (kind=kint), intent(in) nnod, real (kind=kreal), dimension(nnod,3), intent(in) vect1, real (kind=kreal), dimension(nnod,3), intent(in) vect2, real (kind=kreal), dimension(nnod,3), intent(inout) prod)
Definition at line 176 of file cal_products_smp.f90.
cal_cross_prod_w_coef_smp()
subroutine cal_products_smp::cal_cross_prod_w_coef_smp (integer (kind=kint), intent(in) nnod, real (kind=kreal), intent(in) coef, real (kind=kreal), dimension(nnod,3), intent(in) vect1, real (kind=kreal), dimension(nnod,3), intent(in) vect2, real (kind=kreal), dimension(nnod,3), intent(inout) prod)
Definition at line 153 of file cal_products_smp.f90.
Referenced by cal_nonlinear_sph_mhd::nonlinear_terms_on_node().
cal_dot_prod_no_coef_smp()
subroutine cal_products_smp::cal_dot_prod_no_coef_smp (integer (kind=kint), intent(in) nnod, real (kind=kreal), dimension(nnod,3), intent(in) vect1, real (kind=kreal), dimension(nnod,3), intent(in) vect2, real (kind=kreal), dimension(nnod), intent(inout) prod)
Definition at line 134 of file cal_products_smp.f90.
Referenced by cal_energy_flux_rtp::cal_energy_fluxes_on_node(), and cal_energy_flux_rtp::cal_helicity_on_node().
cal_dot_prod_w_coef_smp()
subroutine cal_products_smp::cal_dot_prod_w_coef_smp (integer (kind=kint), intent(in) nnod, real (kind=kreal), intent(in) coef, real (kind=kreal), dimension(nnod,3), intent(in) vect1, real (kind=kreal), dimension(nnod,3), intent(in) vect2, real (kind=kreal), dimension(nnod), intent(inout) prod)
Definition at line 114 of file cal_products_smp.f90.
Referenced by cal_energy_flux_rtp::cal_energy_fluxes_on_node().
cal_scalar_mag_vector_prod_smp()
subroutine cal_products_smp::cal_scalar_mag_vector_prod_smp (integer (kind=kint), intent(in) nnod, real (kind=kreal), dimension(nnod), intent(in) scalar, real (kind=kreal), dimension(nnod,3), intent(in) vector, real (kind=kreal), dimension(nnod), intent(inout) prod)
Definition at line 264 of file cal_products_smp.f90.
cal_scalar_prod_no_coef_smp()
subroutine cal_products_smp::cal_scalar_prod_no_coef_smp (integer (kind=kint), intent(in) nnod, real (kind=kreal), dimension(nnod), intent(in) scalar1, real (kind=kreal), dimension(nnod), intent(in) scalar2, real (kind=kreal), dimension(nnod), intent(inout) prod)
Definition at line 96 of file cal_products_smp.f90.
Referenced by cal_energy_flux_rtp::cal_square_vector_on_node().
cal_scalar_prod_w_coef_smp()
subroutine cal_products_smp::cal_scalar_prod_w_coef_smp (integer (kind=kint), intent(in) nnod, real (kind=kreal), intent(in) coef, real (kind=kreal), dimension(nnod), intent(in) scalar1, real (kind=kreal), dimension(nnod), intent(in) scalar2, real (kind=kreal), dimension(nnod), intent(inout) prod)
Definition at line 78 of file cal_products_smp.f90.
cal_tensor_vec_prod_no_coef_smp()
subroutine cal_products_smp::cal_tensor_vec_prod_no_coef_smp (integer (kind=kint), intent(in) nnod, real (kind=kreal), dimension(nnod,6), intent(in) tensor, real (kind=kreal), dimension(nnod,3), intent(in) vector, real (kind=kreal), dimension(nnod,3), intent(inout) prod)
Definition at line 238 of file cal_products_smp.f90.
cal_tri_product_w_coef_smp()
subroutine cal_products_smp::cal_tri_product_w_coef_smp (integer (kind=kint), intent(in) nnod, real (kind = kreal), intent(in) coef, real (kind=kreal), dimension(nnod,3), intent(in) vect1, real (kind=kreal), dimension(nnod,3), intent(in) vect2, real (kind=kreal), dimension(nnod,3), intent(in) vect3, real (kind=kreal), dimension(nnod), intent(inout) prod)
Definition at line 283 of file cal_products_smp.f90.
cal_vec_scalar_prod_no_coef_smp()
subroutine cal_products_smp::cal_vec_scalar_prod_no_coef_smp (integer (kind=kint), intent(in) nnod, real (kind=kreal), dimension(nnod,3), intent(in) vect1, real (kind=kreal), dimension(nnod), intent(in) scalar, real (kind=kreal), dimension(nnod,3), intent(inout) prod)
Definition at line 199 of file cal_products_smp.f90.
cal_vec_scalar_prod_w_coef_smp()
subroutine cal_products_smp::cal_vec_scalar_prod_w_coef_smp (integer (kind=kint), intent(in) nnod, real (kind=kreal), intent(in) coef, real (kind=kreal), dimension(nnod,3), intent(in) vect1, real (kind=kreal), dimension(nnod), intent(in) scalar, real (kind=kreal), dimension(nnod,3), intent(inout) prod)
Definition at line 218 of file cal_products_smp.f90.
Referenced by cal_nonlinear_sph_mhd::nonlinear_terms_on_node().
tensor_tensor_prod_smp()
subroutine cal_products_smp::tensor_tensor_prod_smp (integer (kind=kint), intent(in) nnod, real (kind=kreal), dimension(nnod,6), intent(in) tensor1, real (kind=kreal), dimension(nnod,6), intent(in) tensor2, real (kind=kreal), dimension(nnod,6), intent(inout) prod)
Definition at line 331 of file cal_products_smp.f90.
vector_vector_prod_smp()
subroutine cal_products_smp::vector_vector_prod_smp (integer (kind=kint), intent(in) nnod, real (kind=kreal), dimension(nnod,3), intent(in) vect1, real (kind=kreal), dimension(nnod,3), intent(in) vect2, real (kind=kreal), dimension(nnod,3), intent(inout) prod)
Definition at line 313 of file cal_products_smp.f90.
Referenced by cal_energy_flux_rtp::cal_square_vector_on_node().