CALYPSO: set_control_sph_mhd Module Reference
set_control_sph_mhd Module Reference
Set control data for spherical transform MHD dynamo simulation.
Functions/Subroutines
subroutine set_control_sph_mhd_w_viz (Dmodel_ctl, psph_ctl, smonitor_ctl, zm_ctls, MHD_prop, sph, rj_fld, nod_fld, monitor)
subroutine set_control_sph_mhd_noviz (Dmodel_ctl, smonitor_ctl, MHD_prop, rj_fld, monitor)
subroutine set_control_4_sph_mhd (plt, org_plt, Dmodel_ctl, smctl_ctl, nmtr_ctl, psph_ctl, MHD_files, bc_IO, MHD_step, MHD_prop, MHD_BC, trans_p, WK, sph_maker)
subroutine set_control_sph_mhd_bcs (MHD_prop, nbc_ctl, sbc_ctl, MHD_BC)
subroutine set_control_sph_mhd_monitors (smonitor_ctl, rj_fld, monitor)
subroutine set_crustal_filtering_control (crust_c, monitor)
Detailed Description
Set control data for spherical transform MHD dynamo simulation.
      subroutine set_control_SPH_MHD_w_viz                            &
     &         (Dmodel_ctl, psph_ctl, smonitor_ctl, zm_ctls,          &
     &          MHD_prop, sph, rj_fld, nod_fld, monitor)
      subroutine set_control_SPH_MHD_noviz(Dmodel_ctl, smonitor_ctl,  &
     &          MHD_prop, rj_fld, monitor)
        type(sph_mhd_monitor_data), intent(inout) :: monitor
      subroutine set_control_4_SPH_MHD(plt, org_plt,                  &
     &          Dmodel_ctl, smctl_ctl, nmtr_ctl, psph_ctl,            &
     &          MHD_files, bc_IO, MHD_step, MHD_prop, MHD_BC,         &
     &          trans_p, WK, sph_maker)
        type(platform_data_control), intent(in) :: plt
        type(platform_data_control), intent(in) :: org_plt
        type(mhd_DNS_model_control), intent(in) :: Dmodel_ctl
        type(sph_mhd_control_control), intent(in) :: smctl_ctl
        type(sph_monitor_control), intent(in) :: smonitor_ctl
        type(node_monitor_control), intent(in) :: nmtr_ctl
        type(parallel_sph_shell_control), intent(inout) :: psph_ctl
        type(phys_data), intent(inout) :: rj_fld
        type(MHD_file_IO_params), intent(inout) :: MHD_files
        type(MHD_step_param), intent(inout) :: MHD_step
        type(MHD_evolution_param), intent(inout) :: MHD_prop
        type(MHD_BC_lists), intent(inout) :: MHD_BC
        type(parameters_4_sph_trans), intent(inout) :: trans_p
        type(works_4_sph_trans_MHD), intent(inout) :: WK
        type(sph_grid_maker_in_sim), intent(inout) :: sph_maker
      subroutine set_control_SPH_MHD_bcs                              &
     &         (MHD_prop, nbc_ctl, sbc_ctl, MHD_BC)
        type(MHD_evolution_param), intent(in) :: MHD_prop
        type(node_bc_control), intent(in) :: nbc_ctl
        type(surf_bc_control), intent(in) :: sbc_ctl
        type(MHD_BC_lists), intent(inout) :: MHD_BC
      subroutine set_control_SPH_MHD_monitors                         &
     &         (smonitor_ctl, rj_fld, monitor)
      subroutine set_crustal_filtering_control                        &
     &         (crust_truncation_c, monitor)
        type(phys_data), intent(in) :: crust_truncation_c
        type(sph_mhd_monitor_data), intent(inout) :: monitor
Function/Subroutine Documentation
set_control_4_sph_mhd()
subroutine set_control_sph_mhd::set_control_4_sph_mhd (type(platform_data_control), intent(in) plt, type(platform_data_control), intent(in) org_plt, type(mhd_dns_model_control), intent(in) Dmodel_ctl, type(sph_mhd_control_control), intent(in) smctl_ctl, type(node_monitor_control), intent(in) nmtr_ctl, type(parallel_sph_shell_control), intent(in) psph_ctl, type(mhd_file_io_params), intent(inout) MHD_files, type(boundary_spectra), intent(inout) bc_IO, type(mhd_step_param), intent(inout) MHD_step, type(mhd_evolution_param), intent(inout) MHD_prop, type(mhd_bc_lists), intent(inout) MHD_BC, type(parameters_4_sph_trans), intent(inout) trans_p, type(works_4_sph_trans_mhd), intent(inout) WK, type(sph_grid_maker_in_sim), intent(inout) sph_maker)
Definition at line 159 of file set_control_sph_mhd.f90.
References set_ctl_parallel_platform::check_control_num_domains(), m_machine_parameter::iflag_debug, calypso_mpi::my_rank, calypso_mpi::nprocs, set_control_4_model::s_set_control_4_crank(), set_control_4_force::s_set_control_4_force(), set_control_4_model::s_set_control_4_model(), set_control_4_normalize::s_set_control_4_normalize(), t_mhd_step_parameter::s_set_control_4_time_steps(), set_control_sph_data_mhd::s_set_control_sph_data_mhd(), t_ctl_params_gen_sph_shell::set_control_4_shell_grids(), t_mhd_file_parameter::set_control_org_sph_files(), set_control_platform_data::set_control_restart_file_def(), set_control_platform_data::set_control_smp_def(), set_control_platform_data::set_control_sph_mesh(), set_control_sph_mhd_bcs(), parallel_ucd_io_select::set_merged_ucd_file_define(), and set_control_platform_data::turn_off_debug_flag_by_ctl().
Referenced by input_control_sph_mhd::input_control_4_sph_make_init(), input_control_sph_mhd::input_control_4_sph_mhd_nosnap(), input_control_dynamobench::input_control_sph_dynamobench(), and input_control_sph_mhd::input_control_sph_mhd_psf().
set_control_sph_mhd_bcs()
subroutine set_control_sph_mhd::set_control_sph_mhd_bcs (type(mhd_evolution_param), intent(in) MHD_prop, type(node_bc_control), intent(in) nbc_ctl, type(surf_bc_control), intent(in) sbc_ctl, type(mhd_bc_lists), intent(inout) MHD_BC)
Definition at line 278 of file set_control_sph_mhd.f90.
References m_machine_parameter::iflag_debug, set_control_4_composition::s_set_control_4_composition(), set_control_4_magne::s_set_control_4_magne(), set_control_4_press::s_set_control_4_press(), set_control_4_temp::s_set_control_4_temp(), and set_control_4_velo::s_set_control_4_velo().
Referenced by set_control_4_sph_mhd().
set_control_sph_mhd_monitors()
subroutine set_control_sph_mhd::set_control_sph_mhd_monitors (type(sph_monitor_control), intent(in) smonitor_ctl, type(phys_data), intent(in) rj_fld, type(sph_mhd_monitor_data), intent(inout) monitor)
Definition at line 336 of file set_control_sph_mhd.f90.
References set_control_4_pickup_sph::set_ctl_params_layered_spectr(), set_control_4_pickup_sph::set_ctl_params_no_heat_nu(), set_control_4_pickup_sph::set_ctl_params_pick_gauss(), set_control_4_pickup_sph::set_ctl_params_pick_sph(), and set_control_4_pickup_sph::set_ctl_params_sph_spectr().
Referenced by set_control_sph_mhd_noviz(), and set_control_sph_mhd_w_viz().
set_control_sph_mhd_noviz()
subroutine set_control_sph_mhd::set_control_sph_mhd_noviz (type(mhd_dns_model_control), intent(inout) Dmodel_ctl, type(sph_monitor_control), intent(in) smonitor_ctl, type(mhd_evolution_param), intent(in) MHD_prop, type(phys_data), intent(inout) rj_fld, type(sph_mhd_monitor_data), intent(inout) monitor)
Definition at line 131 of file set_control_sph_mhd.f90.
References m_machine_parameter::iflag_debug, set_control_sph_data_mhd::set_control_sph_mhd_fields(), and set_control_sph_mhd_monitors().
Referenced by input_control_sph_mhd::input_control_4_sph_mhd_nosnap().
set_control_sph_mhd_w_viz()
subroutine set_control_sph_mhd::set_control_sph_mhd_w_viz (type(mhd_dns_model_control), intent(inout) Dmodel_ctl, type(parallel_sph_shell_control), intent(inout) psph_ctl, type(sph_monitor_control), intent(in) smonitor_ctl, type(sph_dynamo_viz_controls), intent(in) zm_ctls, type(mhd_evolution_param), intent(in) MHD_prop, type(sph_grids), intent(inout) sph, type(phys_data), intent(inout) rj_fld, type(phys_data), intent(inout) nod_fld, type(sph_mhd_monitor_data), intent(inout) monitor)
Definition at line 81 of file set_control_sph_mhd.f90.
References set_nodal_field_name::count_field_4_monitor(), m_machine_parameter::iflag_debug, node_monitor_io::ntot_comp_monitor, node_monitor_io::num_field_monitor, set_control_field_data::s_set_control_field_data(), set_control_sph_data_mhd::set_control_sph_mhd_fields(), set_control_sph_mhd_monitors(), set_crustal_filtering_control(), and set_controls_4_sph_shell::set_fem_mesh_mode_4_sph().
Referenced by input_control_sph_mhd::input_control_4_sph_make_init(), input_control_dynamobench::input_control_sph_dynamobench(), and input_control_sph_mhd::input_control_sph_mhd_psf().
set_crustal_filtering_control()
subroutine set_control_sph_mhd::set_crustal_filtering_control (type(clust_filtering_ctl), intent(in) crust_c, type(sph_mhd_monitor_data), intent(inout) monitor)
Definition at line 368 of file set_control_sph_mhd.f90.
Referenced by set_control_sph_mhd_w_viz().