CALYPSO: m_spheric_constants Module Reference
m_spheric_constants Module Reference
Constants for spectr data.
Variables
integer(kind=kint), parameter igrid_half_chebyshev = 3
integer(kind=kint), parameter igrid_chebyshev = 2
integer(kind=kint), parameter igrid_non_equidist = 1
integer(kind=kint), parameter igrid_equidistance = 0
integer(kind=kint), parameter iflag_no_femmesh = -1
integer(kind=kint), parameter iflag_mesh_same = 0
integer(kind=kint), parameter iflag_mesh_w_pole = 1
integer(kind=kint), parameter iflag_mesh_w_center = 2
character(len=kchara), parameter label_half_cbyv = 'half_Chebyshev'
character(len=kchara), parameter label_chebyshev = 'Chebyshev'
character(len=kchara), parameter label_explicit = 'explicit'
character(len=kchara), parameter label_equi = 'equi_distance'
character(len=kchara), parameter label_no_femmesh = 'no_mesh'
character(len=kchara), parameter label_mesh_same = 'no_pole'
character(len=kchara), parameter label_mesh_pole = 'with_pole'
character(len=kchara), parameter label_mesh_ctr = 'with_center'
Detailed Description
Constants for spectr data.
        igrid_half_Chebyshev = 3 :: half Chebyshev collocation points
        igrid_Chebyshev =      2 :: Chebyshev collocation points
        igrid_non_equidist =   1 :: non-equi-distance
        igrid_equidistance =   0 :: equi-distance
       spherical mesh type  -1: none, 0: Gauss points only
                             1: include poles
                             2: include center
Variable Documentation
iflag_mesh_same
integer(kind = kint), parameter m_spheric_constants::iflag_mesh_same = 0
Definition at line 30 of file m_spheric_constants.f90.
Referenced by t_check_and_make_sph_mesh::load_fem_mesh_4_sph(), pole_sph_transform::pole_backward_transforms(), set_loaded_data_4_sph::set_fem_center_mode_4_sph(), and set_controls_4_sph_shell::set_fem_mesh_mode_4_sph().
iflag_mesh_w_center
integer(kind = kint), parameter m_spheric_constants::iflag_mesh_w_center = 2
Definition at line 32 of file m_spheric_constants.f90.
Referenced by const_1d_ele_connect_4_sph::count_nod_ele_4_sph_radial(), const_1d_ele_connect_4_sph::count_nod_ele_4_sph_theta(), set_sph_local_node::count_numnod_local_sph_mesh(), t_check_and_make_sph_mesh::load_fem_mesh_4_sph(), pole_sph_transform::pole_backward_transforms(), t_ctl_params_gen_sph_shell::set_control_4_shell_grids(), set_loaded_data_4_sph::set_fem_center_mode_4_sph(), set_controls_4_sph_shell::set_fem_mesh_mode_4_sph(), and set_sph_local_node::set_local_nodes_sph_mesh().
iflag_mesh_w_pole
integer(kind = kint), parameter m_spheric_constants::iflag_mesh_w_pole = 1
Definition at line 31 of file m_spheric_constants.f90.
Referenced by const_1d_ele_connect_4_sph::count_nod_ele_4_sph_theta(), set_sph_local_node::count_numnod_local_sph_mesh(), t_ctl_params_gen_sph_shell::set_control_4_shell_grids(), set_loaded_data_4_sph::set_fem_center_mode_4_sph(), set_controls_4_sph_shell::set_fem_mesh_mode_4_sph(), and set_sph_local_node::set_local_nodes_sph_mesh().
iflag_no_femmesh
integer(kind = kint), parameter m_spheric_constants::iflag_no_femmesh = -1
Definition at line 29 of file m_spheric_constants.f90.
Referenced by t_check_and_make_sph_mesh::load_fem_mesh_4_sph(), pole_sph_transform::pole_backward_transforms(), and set_controls_4_sph_shell::set_fem_mesh_mode_4_sph().
igrid_chebyshev
integer(kind = kint), parameter m_spheric_constants::igrid_chebyshev = 2
Definition at line 25 of file m_spheric_constants.f90.
Referenced by const_sph_radial_grid::count_set_radial_grid(), and set_radial_grid_sph_shell::set_radial_distance_flag().
igrid_equidistance
integer(kind = kint), parameter m_spheric_constants::igrid_equidistance = 0
Definition at line 27 of file m_spheric_constants.f90.
Referenced by const_sph_radial_grid::count_set_radial_grid(), and set_radial_grid_sph_shell::set_radial_distance_flag().
igrid_half_chebyshev
integer(kind = kint), parameter m_spheric_constants::igrid_half_chebyshev = 3
Definition at line 24 of file m_spheric_constants.f90.
Referenced by const_sph_radial_grid::count_set_radial_grid(), and set_radial_grid_sph_shell::set_radial_distance_flag().
igrid_non_equidist
integer(kind = kint), parameter m_spheric_constants::igrid_non_equidist = 1
Definition at line 26 of file m_spheric_constants.f90.
Referenced by set_radial_grid_sph_shell::set_radial_distance_flag().
label_chebyshev
character(len = kchara), parameter m_spheric_constants::label_chebyshev = 'Chebyshev'
Definition at line 37 of file m_spheric_constants.f90.
label_equi
character(len = kchara), parameter m_spheric_constants::label_equi = 'equi_distance'
Definition at line 41 of file m_spheric_constants.f90.
label_explicit
character(len = kchara), parameter m_spheric_constants::label_explicit = 'explicit'
Definition at line 39 of file m_spheric_constants.f90.
label_half_cbyv
character(len = kchara), parameter m_spheric_constants::label_half_cbyv = 'half_Chebyshev'
Definition at line 35 of file m_spheric_constants.f90.
label_mesh_ctr
character(len = kchara), parameter m_spheric_constants::label_mesh_ctr = 'with_center'
Definition at line 50 of file m_spheric_constants.f90.
Referenced by set_controls_4_sph_shell::set_fem_mesh_mode_4_sph().
label_mesh_pole
character(len = kchara), parameter m_spheric_constants::label_mesh_pole = 'with_pole'
Definition at line 48 of file m_spheric_constants.f90.
Referenced by set_controls_4_sph_shell::set_fem_mesh_mode_4_sph().
label_mesh_same
character(len = kchara), parameter m_spheric_constants::label_mesh_same = 'no_pole'
Definition at line 46 of file m_spheric_constants.f90.
Referenced by set_controls_4_sph_shell::set_fem_mesh_mode_4_sph().
label_no_femmesh
character(len = kchara), parameter m_spheric_constants::label_no_femmesh = 'no_mesh'
Definition at line 44 of file m_spheric_constants.f90.
Referenced by set_controls_4_sph_shell::set_fem_mesh_mode_4_sph().