CALYPSO: t_ctl_data_surf_boundary Module Reference
t_ctl_data_surf_boundary Module Reference
Data Types
type surf_bc_control
Functions/Subroutines
subroutine read_bc_4_surf_ctl (id_control, hd_block, sbc_ctl, c_buf)
subroutine bcast_bc_4_surf_ctl (sbc_ctl)
subroutine dealloc_bc_4_surf_ctl (sbc_ctl)
Variables
character(len=kchara), parameter, private hd_n_bc_hf = 'heat_flux_surf'
character(len=kchara), parameter, private hd_n_bc_mf = 'velocity_surf'
character(len=kchara), parameter, private hd_n_bc_gradp = 'pressure_surf'
character(len=kchara), parameter, private hd_n_bc_gradb = 'magnetic_field_surf'
character(len=kchara), parameter, private hd_n_bc_grada = 'vector_potential_surf'
character(len=kchara), parameter, private hd_n_bc_gradj = 'current_surf'
character(len=kchara), parameter, private hd_n_bc_gradmp = 'electric_potential_surf'
character(len=kchara), parameter, private hd_n_bc_gradc = 'composition_flux_surf'
character(len=kchara), parameter, private hd_n_bc_infty = 'infinity_surf'
Function/Subroutine Documentation
bcast_bc_4_surf_ctl()
subroutine t_ctl_data_surf_boundary::bcast_bc_4_surf_ctl (type(surf_bc_control), intent(inout) sbc_ctl)
Definition at line 251 of file t_ctl_data_surf_boundary.f90.
References bcast_control_arrays::bcast_ctl_array_c2r(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by t_ctl_data_mhd_model::bcast_sph_mhd_model().
dealloc_bc_4_surf_ctl()
subroutine t_ctl_data_surf_boundary::dealloc_bc_4_surf_ctl (type(surf_bc_control), intent(inout) sbc_ctl)
Definition at line 275 of file t_ctl_data_surf_boundary.f90.
References t_control_array_chara2real::dealloc_control_array_c2_r().
Referenced by t_ctl_data_mhd_model::dealloc_sph_mhd_model().
read_bc_4_surf_ctl()
subroutine t_ctl_data_surf_boundary::read_bc_4_surf_ctl (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) hd_block, type(surf_bc_control), intent(inout) sbc_ctl, type(buffer_for_control), intent(inout) c_buf)
Definition at line 206 of file t_ctl_data_surf_boundary.f90.
References t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_flag(), hd_n_bc_grada, hd_n_bc_gradb, hd_n_bc_gradc, hd_n_bc_gradj, hd_n_bc_gradmp, hd_n_bc_gradp, hd_n_bc_hf, hd_n_bc_infty, hd_n_bc_mf, t_read_control_elements::load_one_line_from_control(), and t_control_array_chara2real::read_control_array_c2_r().
Referenced by t_ctl_data_mhd_model::read_sph_mhd_model().
Variable Documentation
hd_n_bc_grada
character(len=kchara), parameter, private t_ctl_data_surf_boundary::hd_n_bc_grada = 'vector_potential_surf' private
Definition at line 185 of file t_ctl_data_surf_boundary.f90.
Referenced by read_bc_4_surf_ctl().
hd_n_bc_gradb
character(len=kchara), parameter, private t_ctl_data_surf_boundary::hd_n_bc_gradb = 'magnetic_field_surf' private
Definition at line 183 of file t_ctl_data_surf_boundary.f90.
Referenced by read_bc_4_surf_ctl().
hd_n_bc_gradc
character(len=kchara), parameter, private t_ctl_data_surf_boundary::hd_n_bc_gradc = 'composition_flux_surf' private
Definition at line 191 of file t_ctl_data_surf_boundary.f90.
Referenced by read_bc_4_surf_ctl().
hd_n_bc_gradj
character(len=kchara), parameter, private t_ctl_data_surf_boundary::hd_n_bc_gradj = 'current_surf' private
Definition at line 187 of file t_ctl_data_surf_boundary.f90.
Referenced by read_bc_4_surf_ctl().
hd_n_bc_gradmp
character(len=kchara), parameter, private t_ctl_data_surf_boundary::hd_n_bc_gradmp = 'electric_potential_surf' private
Definition at line 189 of file t_ctl_data_surf_boundary.f90.
Referenced by read_bc_4_surf_ctl().
hd_n_bc_gradp
character(len=kchara), parameter, private t_ctl_data_surf_boundary::hd_n_bc_gradp = 'pressure_surf' private
Definition at line 181 of file t_ctl_data_surf_boundary.f90.
Referenced by read_bc_4_surf_ctl().
hd_n_bc_hf
character(len=kchara), parameter, private t_ctl_data_surf_boundary::hd_n_bc_hf = 'heat_flux_surf' private
Definition at line 177 of file t_ctl_data_surf_boundary.f90.
Referenced by read_bc_4_surf_ctl().
hd_n_bc_infty
character(len=kchara), parameter, private t_ctl_data_surf_boundary::hd_n_bc_infty = 'infinity_surf' private
Definition at line 193 of file t_ctl_data_surf_boundary.f90.
Referenced by read_bc_4_surf_ctl().
hd_n_bc_mf
character(len=kchara), parameter, private t_ctl_data_surf_boundary::hd_n_bc_mf = 'velocity_surf' private
Definition at line 179 of file t_ctl_data_surf_boundary.f90.
Referenced by read_bc_4_surf_ctl().