CALYPSO: set_sph_restart_io Module Reference
set_sph_restart_io Module Reference
Copy between field data and IO buffer for restarting.
Functions/Subroutines
subroutine set_sph_restart_num_to_io (rj_fld, fld_IO)
subroutine, private set_sph_restart_field_to_io (rj_fld, fld_IO)
subroutine, private set_sph_restart_comp_to_io (rj_fld, fld_IO)
subroutine set_sph_restart_data_to_io (rj_fld, fld_IO)
subroutine set_sph_restart_from_io (fld_IO, rj_fld)
logical function check_vector_4_restart (field_name)
logical function check_scalar_4_restart (field_name)
Detailed Description
Copy between field data and IO buffer for restarting.
      subroutine set_sph_restart_num_to_IO(rj_fld, fld_IO)
      subroutine set_sph_restart_data_to_IO(rj_fld, fld_IO)
        type(phys_data), intent(in) :: rj_fld
        type(field_IO), intent(inout) :: fld_IO
      subroutine set_sph_restart_from_IO(fld_IO)
        type(field_IO), intent(in) :: fld_IO
        type(phys_data), intent(inout) :: rj_fld
      logical function check_vector_4_restart(field_name)
      logical function check_scalar_4_restart(field_name)
Function/Subroutine Documentation
check_scalar_4_restart()
logical function set_sph_restart_io::check_scalar_4_restart (character(len = kchara), intent(in) field_name)
Definition at line 220 of file set_sph_restart_IO.f90.
References m_base_field_labels::composition, m_base_field_labels::composition_source, m_base_field_labels::entropy, m_base_field_labels::entropy_source, m_base_field_labels::heat_source, m_explicit_term_labels::previous_composition, m_explicit_term_labels::previous_heat, and m_base_field_labels::temperature.
Referenced by set_sph_restart_comp_to_io(), set_sph_restart_data_to_io(), set_sph_restart_field_to_io(), and set_sph_restart_from_io().
check_vector_4_restart()
logical function set_sph_restart_io::check_vector_4_restart (character(len = kchara), intent(in) field_name)
Definition at line 200 of file set_sph_restart_IO.f90.
References m_base_field_labels::magnetic_field, m_explicit_term_labels::previous_induction, m_explicit_term_labels::previous_momentum, and m_base_field_labels::velocity.
Referenced by set_sph_restart_comp_to_io(), set_sph_restart_data_to_io(), set_sph_restart_field_to_io(), and set_sph_restart_from_io().
set_sph_restart_comp_to_io()
subroutine, private set_sph_restart_io::set_sph_restart_comp_to_io (type(phys_data), intent(in) rj_fld, type(field_io), intent(inout) fld_IO) private
Definition at line 91 of file set_sph_restart_IO.f90.
References check_scalar_4_restart(), check_vector_4_restart(), m_phys_constants::n_scalar, and m_phys_constants::n_vector.
Referenced by set_sph_restart_num_to_io().
set_sph_restart_data_to_io()
subroutine set_sph_restart_io::set_sph_restart_data_to_io (type(phys_data), intent(in) rj_fld, type(field_io), intent(inout) fld_IO)
Definition at line 124 of file set_sph_restart_IO.f90.
References check_scalar_4_restart(), check_vector_4_restart(), copy_rj_phys_data_4_io::copy_each_sph_field_to_io(), and copy_rj_phys_data_4_io::copy_each_sph_vector_to_io().
Referenced by sph_mhd_rst_io_control::output_sph_restart_control().
set_sph_restart_field_to_io()
subroutine, private set_sph_restart_io::set_sph_restart_field_to_io (type(phys_data), intent(in) rj_fld, type(field_io), intent(inout) fld_IO) private
Definition at line 70 of file set_sph_restart_IO.f90.
References check_scalar_4_restart(), and check_vector_4_restart().
Referenced by set_sph_restart_num_to_io().
set_sph_restart_from_io()
subroutine set_sph_restart_io::set_sph_restart_from_io (type(field_io), intent(in) fld_IO, type(phys_data), intent(inout) rj_fld)
Definition at line 156 of file set_sph_restart_IO.f90.
References check_scalar_4_restart(), check_vector_4_restart(), copy_rj_phys_data_4_io::copy_each_sph_field_from_io(), copy_rj_phys_data_4_io::copy_each_sph_vector_from_io(), and calypso_mpi::my_rank.
Referenced by sph_mhd_rst_io_control::read_alloc_sph_restart_data(), and sph_mhd_rst_io_control::read_alloc_sph_rst_4_snap().
set_sph_restart_num_to_io()
subroutine set_sph_restart_io::set_sph_restart_num_to_io (type(phys_data), intent(in) rj_fld, type(field_io), intent(inout) fld_IO)
Definition at line 44 of file set_sph_restart_IO.f90.
References t_field_data_io::alloc_merged_field_stack(), t_field_data_io::alloc_phys_data_io(), t_field_data_io::alloc_phys_name_io(), const_global_element_ids::count_number_of_node_stack(), calypso_mpi::nprocs, set_sph_restart_comp_to_io(), and set_sph_restart_field_to_io().
Referenced by set_initial_sph_dynamo::sph_initial_data_control(), and const_sph_initial_spectr::sph_initial_spectrum().