CALYPSO: new_sph_restart Module Reference
new_sph_restart Module Reference
Construct spectrum data for new spectrum domain.
Functions/Subroutines
subroutine load_field_name_assemble_sph (istep_start, np_sph_org, org_fst_param, org_phys, new_phys, t_IO)
subroutine load_org_sph_data (id_rank, istep, np_sph_org, org_fst_param, org_sph, init_d, org_phys)
subroutine load_old_fmt_sph_data (id_rank, istep, np_sph_org, org_fst_param, org_sph, org_phys)
subroutine set_assembled_sph_data (org_sph_mesh, new_sph_mesh, j_table, r_itp, org_phys, new_phys)
subroutine const_assembled_sph_data (b_ratio, time_d, new_sph, r_itp, new_phys, new_fst_IO, t_IO)
Detailed Description
Construct spectrum data for new spectrum domain.
      subroutine alloc_sph_mesh_parallel_merge
      subroutine dealloc_sph_mesh_4_merge
      subroutine load_field_name_assemble_sph(istep_start, np_sph_org,&
     &          org_fst_param, org_phys, new_phys, t_IO)
      subroutine load_org_sph_data(id_rank, istep, np_sph_org,        &
     &          org_fst_param, org_sph, init_d, org_phys)
      subroutine load_old_fmt_sph_data(id_rank, istep, np_sph_org,    &
     &          org_fst_param, org_sph, org_phys)
        type(sph_grids), intent(in) :: org_sph
        type(time_data), intent(inout) :: time_d
        type(phys_data), intent(inout) :: org_phys
      subroutine set_assembled_sph_data                               &
     &         (org_sph_mesh, new_sph_mesh, j_table, r_itp,           &
     &          org_phys, new_phys)
      subroutine const_assembled_sph_data(b_ratio, time_d,            &
     &          new_sph, r_itp, new_phys, new_fst_IO, t_IO)
        type(time_data), intent(in) :: time_d
        type(sph_grids), intent(in) :: new_sph
        type(sph_radial_itp_data), intent(in) :: r_itp
        type(phys_data), intent(inout) :: new_phys
        type(field_IO), intent(inout) :: new_fst_IO
        type(time_data), intent(in) :: t_IO
Function/Subroutine Documentation
const_assembled_sph_data()
subroutine new_sph_restart::const_assembled_sph_data (real(kind=kreal), intent(in) b_ratio, type(time_data), intent(in) time_d, type(sph_grids), intent(in) new_sph, type(sph_radial_itp_data), intent(in) r_itp, type(phys_data), intent(inout) new_phys, type(field_io), intent(inout) new_fst_IO, type(time_data), intent(inout) t_IO)
Definition at line 212 of file new_SPH_restart.f90.
References t_field_data_io::alloc_phys_data_io(), m_base_field_labels::composition, copy_rj_phys_data_4_io::copy_rj_phys_data_to_io(), copy_rj_phys_data_4_io::copy_rj_phys_name_to_io(), t_time_data::copy_time_step_size_data(), assemble_sph_fields::extend_inner_core_scalar(), assemble_sph_fields::extend_potential_magne(), set_merged_restart_data::rescale_4_magne(), and m_base_field_labels::temperature.
Referenced by analyzer_assemble_sph::analyze_assemble_sph(), and analyzer_rayleigh_cvt_sph::analyze_cvt_rayleigh_sph().
load_field_name_assemble_sph()
subroutine new_sph_restart::load_field_name_assemble_sph (integer(kind = kint), intent(in) istep_start, integer, intent(in) np_sph_org, type(field_io_params), intent(in) org_fst_param, type(phys_data), dimension(np_sph_org), intent(inout) org_phys, type(phys_data), intent(inout) new_phys, type(time_data), intent(inout) t_IO)
Field data IO structure for original data
Definition at line 55 of file new_SPH_restart.f90.
References copy_rj_phys_data_4_io::copy_rj_phys_name_from_io(), t_field_data_io::dealloc_phys_name_io(), calypso_mpi::my_rank, and field_io_select::sel_read_alloc_sph_fld_head().
Referenced by analyzer_assemble_sph::init_assemble_sph(), and analyzer_compare_sph_rst::init_compare_sph_restart().
load_old_fmt_sph_data()
subroutine new_sph_restart::load_old_fmt_sph_data (integer, intent(in) id_rank, integer(kind = kint), intent(in) istep, integer, intent(in) np_sph_org, type(field_io_params), intent(in) org_fst_param, type(sph_grids), intent(in) org_sph, type(phys_data), intent(inout) org_phys)
Field data IO structure for original data
Definition at line 140 of file new_SPH_restart.f90.
References copy_rj_phys_data_4_io::copy_rj_phys_data_from_io(), t_field_data_io::dealloc_phys_data_io(), t_field_data_io::dealloc_phys_name_io(), and input_old_file_sel_4_zlib::sel_read_alloc_field_file().
load_org_sph_data()
subroutine new_sph_restart::load_org_sph_data (integer, intent(in) id_rank, integer(kind = kint), intent(in) istep, integer, intent(in) np_sph_org, type(field_io_params), intent(in) org_fst_param, type(sph_grids), intent(in) org_sph, type(time_data), intent(inout) init_d, type(phys_data), intent(inout) org_phys)
Field data IO structure for original data
Definition at line 102 of file new_SPH_restart.f90.
References copy_rj_phys_data_4_io::copy_rj_phys_data_from_io(), t_time_data::copy_time_steps_from_restart(), t_field_data_io::dealloc_phys_data_io(), t_field_data_io::dealloc_phys_name_io(), and field_io_select::sel_read_alloc_step_sph_file().
Referenced by analyzer_assemble_sph::analyze_assemble_sph(), and analyzer_compare_sph_rst::analyze_compare_sph_restart().
set_assembled_sph_data()
subroutine new_sph_restart::set_assembled_sph_data (type(sph_mesh_data), intent(in) org_sph_mesh, type(sph_mesh_data), intent(in) new_sph_mesh, type(rj_assemble_tbl), intent(in) j_table, type(sph_radial_itp_data), intent(in) r_itp, type(phys_data), intent(in) org_phys, type(phys_data), intent(inout) new_phys)
Definition at line 174 of file new_SPH_restart.f90.
References parallel_assemble_sph::copy_field_data_sph_assemble(), parallel_assemble_sph::copy_field_data_sph_center(), and parallel_assemble_sph::r_itp_field_data_sph_assemble().
Referenced by analyzer_assemble_sph::analyze_assemble_sph(), and analyzer_compare_sph_rst::analyze_compare_sph_restart().