CALYPSO: set_indices_4_sph_tranform Module Reference
set_indices_4_sph_tranform Module Reference
Set control parameters for spherical harmonics dynamo from IO.
Functions/Subroutines
subroutine cal_local_nums (n_div, ist, ied, num, istack)
subroutine cal_local_nums_st (n_div, ist, ied, num, ist_list)
subroutine cal_local_nums_rev (n_div, ist, ied, num, ist_list)
subroutine cal_local_num_rtm_m (ndomain_m, ltr, m_folding, num, istack)
subroutine merge_num_3_local_layers (n_div, num_1, num_2, num_3, ist, num, istack)
subroutine set_aria_id (n_div, ist, ied, n_local, ip_local)
Detailed Description
Set control parameters for spherical harmonics dynamo from IO.
      subroutine cal_local_nums(n_div, ist, ied, num, istack)
      subroutine cal_local_nums_rev(n_div, ist, ied, num, istack)
      subroutine cal_local_num_rtm_m(ndomain_m, ltr, m_folding,       &
     &          num, istack)
      subroutine merge_num_3_local_layers(n_div, num_1, num_2, num_3, &
     &          ist, num, istack)
      subroutine set_aria_id(n_div, ist, ied, n_local, ip_local)
Function/Subroutine Documentation
cal_local_num_rtm_m()
subroutine set_indices_4_sph_tranform::cal_local_num_rtm_m (integer(kind = kint), intent(in) ndomain_m, integer(kind = kint), intent(in) ltr, integer(kind = kint), intent(in) m_folding, integer(kind = kint), dimension(ndomain_m), intent(inout) num, integer(kind = kint), dimension(0:ndomain_m), intent(inout) istack)
Definition at line 120 of file set_indices_4_sph_tranform.f90.
Referenced by const_each_global_sph_list::const_global_rtm_grids().
cal_local_nums()
subroutine set_indices_4_sph_tranform::cal_local_nums (integer(kind = kint), intent(in) n_div, integer(kind = kint), intent(in) ist, integer(kind = kint), intent(in) ied, integer(kind = kint), dimension(n_div), intent(inout) num, integer(kind = kint), dimension(0:n_div), intent(inout) istack)
Definition at line 33 of file set_indices_4_sph_tranform.f90.
Referenced by const_each_global_sph_list::const_global_rj_modes_by_rlm(), const_each_global_sph_list::const_global_rtm_grids(), const_each_global_sph_list::const_global_rtp_grids(), and set_sph_tranform_ordering::set_merged_index_4_sph_rj().
cal_local_nums_rev()
subroutine set_indices_4_sph_tranform::cal_local_nums_rev (integer(kind = kint), intent(in) n_div, integer(kind = kint), intent(in) ist, integer(kind = kint), intent(in) ied, integer(kind = kint), dimension(n_div), intent(inout) num, integer(kind = kint), dimension(n_div), intent(inout) ist_list)
Definition at line 91 of file set_indices_4_sph_tranform.f90.
Referenced by const_each_global_sph_list::const_global_rtm_grids(), and const_each_global_sph_list::const_global_rtp_grids().
cal_local_nums_st()
subroutine set_indices_4_sph_tranform::cal_local_nums_st (integer(kind = kint), intent(in) n_div, integer(kind = kint), intent(in) ist, integer(kind = kint), intent(in) ied, integer(kind = kint), dimension(n_div), intent(inout) num, integer(kind = kint), dimension(n_div), intent(inout) ist_list)
Definition at line 62 of file set_indices_4_sph_tranform.f90.
Referenced by const_each_global_sph_list::const_global_rtm_grids(), and const_each_global_sph_list::const_global_rtp_grids().
merge_num_3_local_layers()
subroutine set_indices_4_sph_tranform::merge_num_3_local_layers (integer(kind = kint), intent(in) n_div, integer(kind = kint), dimension(n_div), intent(in) num_1, integer(kind = kint), dimension(n_div), intent(in) num_2, integer(kind = kint), dimension(n_div), intent(in) num_3, integer(kind = kint), intent(in) ist, integer(kind = kint), dimension(n_div), intent(inout) num, integer(kind = kint), dimension(0:n_div), intent(inout) istack)
Definition at line 183 of file set_indices_4_sph_tranform.f90.
Referenced by const_each_global_sph_list::const_global_rtm_grids(), and const_each_global_sph_list::const_global_rtp_grids().
set_aria_id()
subroutine set_indices_4_sph_tranform::set_aria_id (integer(kind = kint), intent(in) n_div, integer(kind = kint), intent(in) ist, integer(kind = kint), intent(in) ied, integer(kind = kint), dimension(n_div), intent(in) n_local, integer(kind = kint), dimension(ist:ied), intent(inout) ip_local)
Definition at line 211 of file set_indices_4_sph_tranform.f90.