CALYPSO: m_boundary_condition_ids Module Reference
m_boundary_condition_ids Module Reference
boundary condition flag list
Variables
integer(kind=kint), parameter iflag_bc_fixed = 0
base flag for fixed boundary
integer(kind=kint), parameter iflag_bc_fix_s = 1
fixed scalar defined by control data
integer(kind=kint), parameter iflag_bc_fix_x = 1
fixed x-component defined by control data
integer(kind=kint), parameter iflag_bc_fix_y = 2
fixed y-component defined by control data
integer(kind=kint), parameter iflag_bc_fix_z = 3
fixed z-component defined by control data
integer(kind=kint), parameter iflag_bc_file_s = -1
fixed scalar defined by external file
integer(kind=kint), parameter iflag_bc_file_x = -1
fixed x-component defined by external file
integer(kind=kint), parameter iflag_bc_file_y = -2
fixed y-component defined by external file
integer(kind=kint), parameter iflag_bc_file_z = -3
fixed z-component defined by external file
integer(kind=kint), parameter iflag_bc_evo_field = -50
evolved boundary defined by external file
integer(kind=kint), parameter iflag_bc_evo_flux = -51
evolved boundary defined by external file
integer(kind=kint), parameter iflag_bc_fix_flux = 11
flag for fixed flux
integer(kind=kint), parameter iflag_bc_file_flux = -11
flag for fixed flux by external file
integer(kind=kint), parameter iflag_bc_sgs = 5
base flag for fixed boundary with SGS model
integer(kind=kint), parameter iflag_bc_sgs_s = 6
fixed scalar defined by control data with SGS model
integer(kind=kint), parameter iflag_bc_sgs_x = 6
fixed x-component defined by control data with SGS model
integer(kind=kint), parameter iflag_bc_sgs_y = 7
fixed y-component defined by control data with SGS model
integer(kind=kint), parameter iflag_bc_sgs_z = 8
fixed z-component defined by control data with SGS model
integer(kind=kint), parameter iflag_bc_rot = 10
fixed rotation boundary
integer(kind=kint), parameter iflag_bc_rot_x = 11
fixed rotation around x-axis boundary
integer(kind=kint), parameter iflag_bc_rot_y = 12
fixed rotation around y-axis boundary
integer(kind=kint), parameter iflag_bc_rot_z = 13
fixed rotation around z-axis boundary
integer(kind=kint), parameter iflag_free_sph = 100
free slip boundary
integer(kind=kint), parameter iflag_non_slip_sph = 200
non slip boundary
integer(kind=kint), parameter iflag_no_vr = 201
eliminate radial flow
integer(kind=kint), parameter iflag_rotatable_icore = 301
rotatable inner core
integer(kind=kint), parameter iflag_insulator = 100
insulated magnetic boundary
integer(kind=kint), parameter iflag_sph_2_center = 501
boundary to connect center field
integer(kind=kint), parameter iflag_sph_clip_center = 502
boundary to fix center field
integer(kind=kint), parameter iflag_pseudo_vacuum = 400
pseudo vacuum boundary
integer(kind=kint), parameter iflag_bc_special = 999
flag for special boundary condition
integer(kind=kint), parameter iflag_fixed_grad = 10
base flag for fixed normal gradient
integer(kind=kint), parameter iflag_fixed_grad_s = 11
fixed normal gradient of scalar
integer(kind=kint), parameter iflag_fixed_grad_x = 11
fixed normal gradient of x-component
integer(kind=kint), parameter iflag_fixed_grad_y = 12
fixed normal gradient of y-component
integer(kind=kint), parameter iflag_fixed_grad_z = 13
fixed normal gradient of z-component
integer(kind=kint), parameter iflag_fixed_norm = 20
base flag for fixed normal field
integer(kind=kint), parameter iflag_lead_grad = 100
base flag to evaluate normal gradient
integer(kind=kint), parameter iflag_lead_grad_s = 101
evaluate normal gradient for scalar
integer(kind=kint), parameter iflag_lead_grad_x = 101
evaluate normal gradient for x-component
integer(kind=kint), parameter iflag_lead_grad_y = 102
evaluate normal gradient for y-component
integer(kind=kint), parameter iflag_lead_grad_z = 103
evaluate normal gradient for z-component
integer(kind=kint), parameter iflag_surf_wall = 70
surface flag for reflectio
integer(kind=kint), parameter iflag_surf_sph_in = 71
surface flag for inner boundary of spheical shell
integer(kind=kint), parameter iflag_surf_sph_out = 72
surface flag for outer boundary of spheical shell
integer(kind=kint), parameter iflag_surf_free_sph_in = 401
surface flag for free slip on outer spherical boundary
integer(kind=kint), parameter iflag_surf_free_sph_out = 402
surface flag for free slip on inner spherical boundary
integer(kind=kint), parameter iflag_surf_qvc_sph_in = 401
surface flag for pseudo vacuum on outer spherical boundary
integer(kind=kint), parameter iflag_surf_qvc_sph_out = 402
surface flag for pseudo vacuum on inner spherical boundary
integer(kind=kint), parameter iflag_surf_infty = 0
surface flag for infinite radius
Detailed Description
boundary condition flag list
Variable Documentation
iflag_bc_evo_field
integer(kind = kint), parameter m_boundary_condition_ids::iflag_bc_evo_field = -50
evolved boundary defined by external file
Definition at line 36 of file m_boundary_condition_IDs.f90.
Referenced by set_bc_sph_scalars::inner_sph_bc_scalar_sph(), set_bc_sph_scalars::outer_sph_bc_scalar_sph(), set_node_group_types::set_bc_group_types_scalar(), set_node_group_types::set_bc_group_types_vector(), set_bc_sph_mhd::set_sph_bc_magne_sph(), set_bc_flag_sph_velo::set_sph_velo_cmb_flag(), and set_bc_flag_sph_velo::set_sph_velo_icb_flag().
iflag_bc_evo_flux
integer(kind = kint), parameter m_boundary_condition_ids::iflag_bc_evo_flux = -51
evolved boundary defined by external file
Definition at line 38 of file m_boundary_condition_IDs.f90.
Referenced by set_bc_sph_scalars::inner_sph_bc_scalar_sph(), set_bc_sph_scalars::outer_sph_bc_scalar_sph(), and set_node_group_types::set_bc_group_types_fluxes().
iflag_bc_file_flux
integer(kind = kint), parameter m_boundary_condition_ids::iflag_bc_file_flux = -11
flag for fixed flux by external file
Definition at line 43 of file m_boundary_condition_IDs.f90.
Referenced by set_bc_sph_scalars::inner_sph_bc_scalar_sph(), set_bc_sph_scalars::outer_sph_bc_scalar_sph(), and set_node_group_types::set_bc_group_types_fluxes().
iflag_bc_file_s
integer(kind = kint), parameter m_boundary_condition_ids::iflag_bc_file_s = -1
fixed scalar defined by external file
Definition at line 27 of file m_boundary_condition_IDs.f90.
Referenced by set_bc_sph_scalars::inner_sph_bc_scalar_sph(), set_bc_sph_scalars::outer_sph_bc_scalar_sph(), set_node_group_types::set_bc_group_types_scalar(), set_node_group_types::set_bc_group_types_vector(), set_bc_sph_mhd::set_sph_bc_magne_sph(), set_bc_flag_sph_velo::set_sph_velo_cmb_flag(), and set_bc_flag_sph_velo::set_sph_velo_icb_flag().
iflag_bc_file_x
integer(kind = kint), parameter m_boundary_condition_ids::iflag_bc_file_x = -1
fixed x-component defined by external file
Definition at line 29 of file m_boundary_condition_IDs.f90.
Referenced by set_node_group_types::set_bc_group_types_vector().
iflag_bc_file_y
integer(kind = kint), parameter m_boundary_condition_ids::iflag_bc_file_y = -2
fixed y-component defined by external file
Definition at line 31 of file m_boundary_condition_IDs.f90.
Referenced by set_node_group_types::set_bc_group_types_vector().
iflag_bc_file_z
integer(kind = kint), parameter m_boundary_condition_ids::iflag_bc_file_z = -3
fixed z-component defined by external file
Definition at line 33 of file m_boundary_condition_IDs.f90.
Referenced by set_node_group_types::set_bc_group_types_vector().
iflag_bc_fix_flux
integer(kind = kint), parameter m_boundary_condition_ids::iflag_bc_fix_flux = 11
flag for fixed flux
Definition at line 41 of file m_boundary_condition_IDs.f90.
Referenced by set_bc_sph_scalars::inner_sph_bc_scalar_sph(), set_bc_sph_scalars::outer_sph_bc_scalar_sph(), and set_node_group_types::set_bc_group_types_fluxes().
iflag_bc_fix_s
integer(kind = kint), parameter m_boundary_condition_ids::iflag_bc_fix_s = 1
fixed scalar defined by control data
Definition at line 19 of file m_boundary_condition_IDs.f90.
Referenced by set_bc_sph_scalars::inner_sph_bc_scalar_sph(), set_bc_sph_scalars::outer_sph_bc_scalar_sph(), and set_node_group_types::set_bc_group_types_scalar().
iflag_bc_fix_x
integer(kind = kint), parameter m_boundary_condition_ids::iflag_bc_fix_x = 1
fixed x-component defined by control data
Definition at line 21 of file m_boundary_condition_IDs.f90.
Referenced by set_node_group_types::set_bc_group_types_vector().
iflag_bc_fix_y
integer(kind = kint), parameter m_boundary_condition_ids::iflag_bc_fix_y = 2
fixed y-component defined by control data
Definition at line 23 of file m_boundary_condition_IDs.f90.
Referenced by set_node_group_types::set_bc_group_types_vector().
iflag_bc_fix_z
integer(kind = kint), parameter m_boundary_condition_ids::iflag_bc_fix_z = 3
fixed z-component defined by control data
Definition at line 25 of file m_boundary_condition_IDs.f90.
Referenced by set_node_group_types::set_bc_group_types_vector().
iflag_bc_fixed
integer(kind = kint), parameter m_boundary_condition_ids::iflag_bc_fixed = 0
base flag for fixed boundary
Definition at line 17 of file m_boundary_condition_IDs.f90.
iflag_bc_rot
integer(kind = kint), parameter m_boundary_condition_ids::iflag_bc_rot = 10
fixed rotation boundary
Definition at line 57 of file m_boundary_condition_IDs.f90.
Referenced by set_node_group_types::set_bc_group_types_rotation(), set_bc_flag_sph_velo::set_sph_velo_cmb_flag(), and set_bc_flag_sph_velo::set_sph_velo_icb_flag().
iflag_bc_rot_x
integer(kind = kint), parameter m_boundary_condition_ids::iflag_bc_rot_x = 11
fixed rotation around x-axis boundary
Definition at line 59 of file m_boundary_condition_IDs.f90.
iflag_bc_rot_y
integer(kind = kint), parameter m_boundary_condition_ids::iflag_bc_rot_y = 12
fixed rotation around y-axis boundary
Definition at line 61 of file m_boundary_condition_IDs.f90.
iflag_bc_rot_z
integer(kind = kint), parameter m_boundary_condition_ids::iflag_bc_rot_z = 13
fixed rotation around z-axis boundary
Definition at line 63 of file m_boundary_condition_IDs.f90.
iflag_bc_sgs
integer(kind = kint), parameter m_boundary_condition_ids::iflag_bc_sgs = 5
base flag for fixed boundary with SGS model
Definition at line 46 of file m_boundary_condition_IDs.f90.
iflag_bc_sgs_s
integer(kind = kint), parameter m_boundary_condition_ids::iflag_bc_sgs_s = 6
fixed scalar defined by control data with SGS model
Definition at line 48 of file m_boundary_condition_IDs.f90.
Referenced by set_node_group_types::set_bc_group_types_sgs_scalar().
iflag_bc_sgs_x
integer(kind = kint), parameter m_boundary_condition_ids::iflag_bc_sgs_x = 6
fixed x-component defined by control data with SGS model
Definition at line 50 of file m_boundary_condition_IDs.f90.
Referenced by set_node_group_types::set_bc_group_types_sgs_vect().
iflag_bc_sgs_y
integer(kind = kint), parameter m_boundary_condition_ids::iflag_bc_sgs_y = 7
fixed y-component defined by control data with SGS model
Definition at line 52 of file m_boundary_condition_IDs.f90.
Referenced by set_node_group_types::set_bc_group_types_sgs_vect().
iflag_bc_sgs_z
integer(kind = kint), parameter m_boundary_condition_ids::iflag_bc_sgs_z = 8
fixed z-component defined by control data with SGS model
Definition at line 54 of file m_boundary_condition_IDs.f90.
Referenced by set_node_group_types::set_bc_group_types_sgs_vect().
iflag_bc_special
integer(kind = kint), parameter m_boundary_condition_ids::iflag_bc_special = 999
flag for special boundary condition
Definition at line 85 of file m_boundary_condition_IDs.f90.
iflag_fixed_grad
integer(kind = kint), parameter m_boundary_condition_ids::iflag_fixed_grad = 10
base flag for fixed normal gradient
Definition at line 89 of file m_boundary_condition_IDs.f90.
iflag_fixed_grad_s
integer(kind = kint), parameter m_boundary_condition_ids::iflag_fixed_grad_s = 11
fixed normal gradient of scalar
Definition at line 91 of file m_boundary_condition_IDs.f90.
Referenced by set_surface_group_types::set_surf_group_types_scalar().
iflag_fixed_grad_x
integer(kind = kint), parameter m_boundary_condition_ids::iflag_fixed_grad_x = 11
fixed normal gradient of x-component
Definition at line 93 of file m_boundary_condition_IDs.f90.
Referenced by set_surface_group_types::set_surf_group_types_vector().
iflag_fixed_grad_y
integer(kind = kint), parameter m_boundary_condition_ids::iflag_fixed_grad_y = 12
fixed normal gradient of y-component
Definition at line 95 of file m_boundary_condition_IDs.f90.
Referenced by set_surface_group_types::set_surf_group_types_vector().
iflag_fixed_grad_z
integer(kind = kint), parameter m_boundary_condition_ids::iflag_fixed_grad_z = 13
fixed normal gradient of z-component
Definition at line 97 of file m_boundary_condition_IDs.f90.
Referenced by set_surface_group_types::set_surf_group_types_vector().
iflag_fixed_norm
integer(kind = kint), parameter m_boundary_condition_ids::iflag_fixed_norm = 20
base flag for fixed normal field
Definition at line 100 of file m_boundary_condition_IDs.f90.
Referenced by set_surface_group_types::set_surf_group_types_vector().
iflag_free_sph
integer(kind = kint), parameter m_boundary_condition_ids::iflag_free_sph = 100
free slip boundary
Definition at line 66 of file m_boundary_condition_IDs.f90.
Referenced by set_node_group_types::set_bc_group_types_sph_velo(), set_bc_flag_sph_velo::set_sph_velo_cmb_flag(), and set_bc_flag_sph_velo::set_sph_velo_icb_flag().
iflag_insulator
integer(kind = kint), parameter m_boundary_condition_ids::iflag_insulator = 100
insulated magnetic boundary
Definition at line 75 of file m_boundary_condition_IDs.f90.
Referenced by set_node_group_types::set_bc_group_types_sph_magne().
iflag_lead_grad
integer(kind = kint), parameter m_boundary_condition_ids::iflag_lead_grad = 100
base flag to evaluate normal gradient
Definition at line 103 of file m_boundary_condition_IDs.f90.
iflag_lead_grad_s
integer(kind = kint), parameter m_boundary_condition_ids::iflag_lead_grad_s = 101
evaluate normal gradient for scalar
Definition at line 105 of file m_boundary_condition_IDs.f90.
Referenced by set_surface_group_types::set_surf_group_types_scalar().
iflag_lead_grad_x
integer(kind = kint), parameter m_boundary_condition_ids::iflag_lead_grad_x = 101
evaluate normal gradient for x-component
Definition at line 107 of file m_boundary_condition_IDs.f90.
Referenced by set_surface_group_types::set_surf_group_types_vector().
iflag_lead_grad_y
integer(kind = kint), parameter m_boundary_condition_ids::iflag_lead_grad_y = 102
evaluate normal gradient for y-component
Definition at line 109 of file m_boundary_condition_IDs.f90.
Referenced by set_surface_group_types::set_surf_group_types_vector().
iflag_lead_grad_z
integer(kind = kint), parameter m_boundary_condition_ids::iflag_lead_grad_z = 103
evaluate normal gradient for z-component
Definition at line 111 of file m_boundary_condition_IDs.f90.
Referenced by set_surface_group_types::set_surf_group_types_vector().
iflag_no_vr
integer(kind = kint), parameter m_boundary_condition_ids::iflag_no_vr = 201
eliminate radial flow
Definition at line 70 of file m_boundary_condition_IDs.f90.
iflag_non_slip_sph
integer(kind = kint), parameter m_boundary_condition_ids::iflag_non_slip_sph = 200
non slip boundary
Definition at line 68 of file m_boundary_condition_IDs.f90.
Referenced by set_node_group_types::set_bc_group_types_sph_velo(), set_bc_flag_sph_velo::set_sph_velo_cmb_flag(), and set_bc_flag_sph_velo::set_sph_velo_icb_flag().
iflag_pseudo_vacuum
integer(kind = kint), parameter m_boundary_condition_ids::iflag_pseudo_vacuum = 400
pseudo vacuum boundary
Definition at line 82 of file m_boundary_condition_IDs.f90.
Referenced by set_node_group_types::set_bc_group_types_sph_magne(), and set_bc_sph_mhd::set_sph_bc_magne_sph().
iflag_rotatable_icore
integer(kind = kint), parameter m_boundary_condition_ids::iflag_rotatable_icore = 301
rotatable inner core
Definition at line 72 of file m_boundary_condition_IDs.f90.
Referenced by set_node_group_types::set_bc_group_types_sph_velo(), and set_bc_flag_sph_velo::set_sph_velo_icb_flag().
iflag_sph_2_center
integer(kind = kint), parameter m_boundary_condition_ids::iflag_sph_2_center = 501
boundary to connect center field
Definition at line 77 of file m_boundary_condition_IDs.f90.
Referenced by set_bc_sph_scalars::inner_sph_bc_scalar_sph(), set_node_group_types::set_bc_group_types_sph_center(), set_bc_sph_mhd::set_sph_bc_magne_sph(), and set_bc_flag_sph_velo::set_sph_velo_icb_flag().
iflag_sph_clip_center
integer(kind = kint), parameter m_boundary_condition_ids::iflag_sph_clip_center = 502
boundary to fix center field
Definition at line 79 of file m_boundary_condition_IDs.f90.
Referenced by set_bc_sph_scalars::inner_sph_bc_scalar_sph(), set_node_group_types::set_bc_group_types_sph_center(), set_bc_sph_mhd::set_sph_bc_magne_sph(), and set_bc_flag_sph_velo::set_sph_velo_icb_flag().
iflag_surf_free_sph_in
integer(kind = kint), parameter m_boundary_condition_ids::iflag_surf_free_sph_in = 401
surface flag for free slip on outer spherical boundary
Definition at line 121 of file m_boundary_condition_IDs.f90.
Referenced by set_surface_group_types::set_stress_free_group_types().
iflag_surf_free_sph_out
integer(kind = kint), parameter m_boundary_condition_ids::iflag_surf_free_sph_out = 402
surface flag for free slip on inner spherical boundary
Definition at line 123 of file m_boundary_condition_IDs.f90.
Referenced by set_surface_group_types::set_stress_free_group_types().
iflag_surf_infty
integer(kind = kint), parameter m_boundary_condition_ids::iflag_surf_infty = 0
surface flag for infinite radius
Definition at line 131 of file m_boundary_condition_IDs.f90.
Referenced by set_surface_group_types::set_surf_infty_group_types().
iflag_surf_qvc_sph_in
integer(kind = kint), parameter m_boundary_condition_ids::iflag_surf_qvc_sph_in = 401
surface flag for pseudo vacuum on outer spherical boundary
Definition at line 126 of file m_boundary_condition_IDs.f90.
Referenced by set_surface_group_types::set_pseudo_vacuum_group_types().
iflag_surf_qvc_sph_out
integer(kind = kint), parameter m_boundary_condition_ids::iflag_surf_qvc_sph_out = 402
surface flag for pseudo vacuum on inner spherical boundary
Definition at line 128 of file m_boundary_condition_IDs.f90.
Referenced by set_surface_group_types::set_pseudo_vacuum_group_types().
iflag_surf_sph_in
integer(kind = kint), parameter m_boundary_condition_ids::iflag_surf_sph_in = 71
surface flag for inner boundary of spheical shell
Definition at line 116 of file m_boundary_condition_IDs.f90.
Referenced by set_surface_group_types::set_surf_wall_group_types().
iflag_surf_sph_out
integer(kind = kint), parameter m_boundary_condition_ids::iflag_surf_sph_out = 72
surface flag for outer boundary of spheical shell
Definition at line 118 of file m_boundary_condition_IDs.f90.
Referenced by set_surface_group_types::set_surf_wall_group_types().
iflag_surf_wall
integer(kind = kint), parameter m_boundary_condition_ids::iflag_surf_wall = 70
surface flag for reflectio
Definition at line 114 of file m_boundary_condition_IDs.f90.
Referenced by set_surface_group_types::set_surf_wall_group_types().