CALYPSO: gz_udt_type_data_io Module Reference
gz_udt_type_data_io Module Reference
gzipped UCD format data IO
Functions/Subroutines
subroutine write_gz_udt_type_fields (ucd, zbuf)
subroutine write_gz_ucd_type_mesh (ucd, zbuf)
subroutine read_gz_udt_field (ucd, zbuf)
subroutine read_alloc_gz_udt_field (ucd, zbuf)
subroutine read_gz_ucd_mesh_data (ucd, zbuf)
subroutine read_alloc_gz_ucd_mesh_data (ucd, zbuf)
Detailed Description
gzipped UCD format data IO
      subroutine write_gz_udt_type_fields(ucd, zbuf)
      subroutine write_gz_ucd_type_mesh(ucd, zbuf)
        type(ucd_data), intent(in) :: ucd
        type(buffer_4_gzip), intent(inout) :: zbuf
      subroutine read_gz_udt_field(ucd, zbuf)
      subroutine read_alloc_gz_udt_field(ucd, zbuf)
      subroutine read_gz_ucd_mesh_data(ucd, zbuf)
      subroutine read_alloc_gz_ucd_mesh_data(ucd, zbuf)
        type(ucd_data), intent(inout) :: ucd
        type(buffer_4_gzip), intent(inout) :: zbuf
Function/Subroutine Documentation
read_alloc_gz_ucd_mesh_data()
subroutine gz_udt_type_data_io::read_alloc_gz_ucd_mesh_data (type(ucd_data), intent(inout) ucd, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 150 of file gz_udt_type_data_IO.f90.
References t_ucd_data::allocate_ucd_ele(), t_ucd_data::allocate_ucd_node(), gzip_file_access::get_one_line_text_from_gz(), ucd_data_to_buffer::nnod_ele_by_ucd_eletype(), gz_ucd_data_io::read_gz_ucd_node_data(), and gz_ucd_data_io::read_gz_udt_mesh_header().
Referenced by gz_udt_file_io::read_alloc_gz_ucd_file(), and gz_udt_file_io::read_alloc_gz_ucd_grd().
read_alloc_gz_udt_field()
subroutine gz_udt_type_data_io::read_alloc_gz_udt_field (type(ucd_data), intent(inout) ucd, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 103 of file gz_udt_type_data_IO.f90.
References t_ucd_data::allocate_ucd_phys_data(), t_ucd_data::allocate_ucd_phys_name(), t_ucd_data::cal_istack_ucd_component(), gz_ucd_data_io::read_gz_udt_field_name(), and gz_ucd_data_io::read_gz_udt_field_num().
Referenced by gz_udt_file_io::read_alloc_gz_ucd_file(), gz_udt_file_io::read_alloc_gz_udt_file(), and gz_udt_file_io::read_alloc_gz_udt_params().
read_gz_ucd_mesh_data()
subroutine gz_udt_type_data_io::read_gz_ucd_mesh_data (type(ucd_data), intent(inout) ucd, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 125 of file gz_udt_type_data_IO.f90.
References gz_ucd_data_io::read_gz_ucd_ele_connect(), gz_ucd_data_io::read_gz_ucd_node_data(), and gz_ucd_data_io::read_gz_udt_mesh_header().
Referenced by gz_udt_file_io::read_gz_ucd_file(), and gz_udt_file_io::read_gz_ucd_grd().
read_gz_udt_field()
subroutine gz_udt_type_data_io::read_gz_udt_field (type(ucd_data), intent(inout) ucd, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 79 of file gz_udt_type_data_IO.f90.
References t_ucd_data::cal_istack_ucd_component(), gz_ucd_data_io::read_gz_udt_field_data(), gz_ucd_data_io::read_gz_udt_field_name(), and gz_ucd_data_io::read_gz_udt_field_num().
Referenced by gz_udt_file_io::read_gz_ucd_file(), and gz_udt_file_io::read_gz_udt_file().
write_gz_ucd_type_mesh()
subroutine gz_udt_type_data_io::write_gz_ucd_type_mesh (type(ucd_data), intent(in) ucd, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 60 of file gz_udt_type_data_IO.f90.
References m_constants::ithree, gz_ucd_data_io::write_gz_ucd_field_data(), gz_ucd_data_io::write_gz_ucd_mesh_connect(), and gz_ucd_data_io::write_gz_udt_mesh_header().
Referenced by gz_udt_file_io::write_gz_grd_file(), and gz_udt_file_io::write_gz_ucd_file().
write_gz_udt_type_fields()
subroutine gz_udt_type_data_io::write_gz_udt_type_fields (type(ucd_data), intent(in) ucd, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 43 of file gz_udt_type_data_IO.f90.
References gz_ucd_data_io::write_gz_ucd_field_data(), and gz_ucd_data_io::write_gz_udt_field_header().
Referenced by gz_udt_file_io::write_gz_ucd_file(), and gz_udt_file_io::write_gz_udt_file().