CALYPSO: spherical_model_io_b Module Reference
spherical_model_io_b Module Reference
Data IO routines for spectrum data.
Functions/Subroutines
subroutine read_rank_4_sph_b (bbuf, sph_IO)
subroutine read_gl_resolution_sph_b (bbuf, sph_IO)
subroutine read_gl_nodes_sph_b (bbuf, sph_IO)
subroutine write_rank_4_sph_b (sph_IO, bbuf)
subroutine write_gl_resolution_sph_b (sph_IO, bbuf)
subroutine write_gl_nodes_sph_b (sph_IO, bbuf)
Detailed Description
Data IO routines for spectrum data.
      subroutine read_rank_4_sph_b(bbuf, sph_IO)
      subroutine read_gl_resolution_sph_b(bbuf, sph_IO)
      subroutine read_gl_nodes_sph_b(bbuf, sph_IO)
        type(binary_IO_buffer), intent(inout) :: bbuf
        type(sph_IO_data), intent(inout) :: sph_IO
      subroutine write_rank_4_sph_b(sph_IO, bbuf)
      subroutine write_gl_resolution_sph_b(sph_IO, bbuf)
      subroutine write_gl_nodes_sph_b(sph_IO, bbuf)
        type(sph_IO_data), intent(in) :: sph_IO
        type(binary_IO_buffer), intent(inout) :: bbuf
Function/Subroutine Documentation
read_gl_nodes_sph_b()
subroutine spherical_model_io_b::read_gl_nodes_sph_b (type(binary_io_buffer), intent(inout) bbuf, type(sph_io_data), intent(inout) sph_IO)
Definition at line 69 of file spherical_model_IO_b.f90.
References t_node_id_spherical_io::alloc_nod_id_sph_io(), transfer_to_long_integers::cast_long(), binary_io::read_mul_int8_b(), binary_io::read_mul_integer_b(), and binary_io::read_one_integer_b().
Referenced by sph_modes_grids_data_io_b::read_geom_rtm_data_b(), sph_modes_grids_data_io_b::read_geom_rtp_data_b(), sph_modes_grids_data_io_b::read_modes_rlm_data_b(), and sph_modes_grids_data_io_b::read_spectr_modes_rj_data_b().
read_gl_resolution_sph_b()
subroutine spherical_model_io_b::read_gl_resolution_sph_b (type(binary_io_buffer), intent(inout) bbuf, type(sph_io_data), intent(inout) sph_IO)
Definition at line 53 of file spherical_model_IO_b.f90.
References transfer_to_long_integers::cast_long(), binary_io::read_mul_integer_b(), and binary_io::read_one_integer_b().
Referenced by sph_modes_grids_data_io_b::read_geom_rtm_data_b(), sph_modes_grids_data_io_b::read_geom_rtp_data_b(), sph_modes_grids_data_io_b::read_modes_rlm_data_b(), and sph_modes_grids_data_io_b::read_spectr_modes_rj_data_b().
read_rank_4_sph_b()
subroutine spherical_model_io_b::read_rank_4_sph_b (type(binary_io_buffer), intent(inout) bbuf, type(sph_io_data), intent(inout) sph_IO)
Definition at line 40 of file spherical_model_IO_b.f90.
References transfer_to_long_integers::cast_long(), and binary_io::read_mul_integer_b().
Referenced by sph_modes_grids_data_io_b::read_geom_rtm_data_b(), sph_modes_grids_data_io_b::read_geom_rtp_data_b(), sph_modes_grids_data_io_b::read_modes_rlm_data_b(), and sph_modes_grids_data_io_b::read_spectr_modes_rj_data_b().
write_gl_nodes_sph_b()
subroutine spherical_model_io_b::write_gl_nodes_sph_b (type(sph_io_data), intent(in) sph_IO, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 122 of file spherical_model_IO_b.f90.
References transfer_to_long_integers::cast_long(), binary_io::write_mul_int8_b(), binary_io::write_mul_integer_b(), and binary_io::write_one_integer_b().
Referenced by sph_modes_grids_data_io_b::write_geom_rtm_data_b(), sph_modes_grids_data_io_b::write_geom_rtp_data_b(), sph_modes_grids_data_io_b::write_modes_rlm_data_b(), and sph_modes_grids_data_io_b::write_spectr_modes_rj_data_b().
write_gl_resolution_sph_b()
subroutine spherical_model_io_b::write_gl_resolution_sph_b (type(sph_io_data), intent(in) sph_IO, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 107 of file spherical_model_IO_b.f90.
References transfer_to_long_integers::cast_long(), binary_io::write_mul_integer_b(), and binary_io::write_one_integer_b().
Referenced by sph_modes_grids_data_io_b::write_geom_rtm_data_b(), sph_modes_grids_data_io_b::write_geom_rtp_data_b(), sph_modes_grids_data_io_b::write_modes_rlm_data_b(), and sph_modes_grids_data_io_b::write_spectr_modes_rj_data_b().
write_rank_4_sph_b()
subroutine spherical_model_io_b::write_rank_4_sph_b (type(sph_io_data), intent(in) sph_IO, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 94 of file spherical_model_IO_b.f90.
References transfer_to_long_integers::cast_long(), and binary_io::write_mul_integer_b().
Referenced by sph_modes_grids_data_io_b::write_geom_rtm_data_b(), sph_modes_grids_data_io_b::write_geom_rtp_data_b(), sph_modes_grids_data_io_b::write_modes_rlm_data_b(), and sph_modes_grids_data_io_b::write_spectr_modes_rj_data_b().