CALYPSO: t_reference_scalar_param Module Reference
t_reference_scalar_param Module Reference
set reference fields for MHD simulation from control data
Data Types
type reference_scalar_param
type takepiro_model_param
Functions/Subroutines
subroutine set_reference_scalar_ctl (charaflag, ref_ctl, ref_param, takepiro)
subroutine, private set_linear_ref_scalar_ctl (ref_temp_ctl, low_temp_ctl, high_temp_ctl, ref_param)
subroutine, private set_takepiro_scalar_ctl (stratified_ctl, takepiro_ctl, iflag_ref, takepiro)
Variables
integer(kind=kint), parameter id_no_ref_temp = 0
flag for solving full temperature
integer(kind=kint), parameter id_x_ref_temp = 0
flag to use referece temperature as a function of \(x \)
integer(kind=kint), parameter id_y_ref_temp = 0
flag to use referece temperature as a function of \(y \)
integer(kind=kint), parameter id_z_ref_temp = 0
flag to use referece temperature as a function of \(z \)
integer(kind=kint), parameter id_sphere_ref_temp = 100
flag to use referece temperature as a function of \(r \)
integer(kind=kint), parameter id_linear_r_ref_temp = 200
flag to use linearly decrease referece temperature as a function of \(r \)
integer(kind=kint), parameter id_takepiro_temp = 1000
takepiro model flag
character(len=kchara), parameter label_sph_shell = 'spherical_shell'
character(len=kchara), parameter label_sph_const_heat = 'sph_constant_heat'
character(len=kchara), parameter label_takepiro = 'takepiro'
character(len=kchara), parameter label_linear_x = 'linear_x'
character(len=kchara), parameter label_linear_y = 'linear_y'
character(len=kchara), parameter label_linear_z = 'linear_z'
Detailed Description
set reference fields for MHD simulation from control data
      subroutine set_reference_scalar_ctl                             &
     &        (charaflag, ref_ctl, ref_param, takepiro)
      subroutine set_linear_ref_scalar_ctl                            &
     &         (ref_temp_ctl, low_temp_ctl, high_temp_ctl, ref_param)
      subroutine set_takepiro_scalar_ctl                              &
     &         (stratified_ctl, takepiro_ctl, takepiro)
        type(read_character_item), intent(in) :: ref_temp_ctl
        type(read_character_item), intent(in) :: stratified_ctl
        type(reference_point_control), intent(in) :: low_temp_ctl
        type(reference_point_control), intent(in) :: high_temp_ctl
        type(reference_point_control), intent(in) :: takepiro_ctl
        type(reference_scalar_param), intent(inout) :: ref_param
        type(takepiro_model_param), intent(inout) :: takepiro
Function/Subroutine Documentation
set_linear_ref_scalar_ctl()
subroutine, private t_reference_scalar_param::set_linear_ref_scalar_ctl (type(read_character_item), intent(in) ref_temp_ctl, type(reference_point_control), intent(in) low_temp_ctl, type(reference_point_control), intent(in) high_temp_ctl, type(reference_scalar_param), intent(inout) ref_param) private
Definition at line 126 of file t_reference_scalar_param.f90.
References calypso_mpi::calypso_mpi_abort(), m_machine_parameter::e_message, id_linear_r_ref_temp, id_no_ref_temp, id_sphere_ref_temp, id_takepiro_temp, id_x_ref_temp, id_y_ref_temp, id_z_ref_temp, m_error_ids::ierr_fld, m_machine_parameter::iflag_debug, m_machine_parameter::iflag_routine_msg, label_linear_x, label_linear_y, label_linear_z, label_sph_const_heat, label_sph_shell, and label_takepiro.
Referenced by set_reference_scalar_ctl().
set_reference_scalar_ctl()
subroutine t_reference_scalar_param::set_reference_scalar_ctl (character(len = kchara), intent(in) charaflag, type(reference_temperature_ctl), intent(in) ref_ctl, type(reference_scalar_param), intent(inout) ref_param, type(takepiro_model_param), intent(inout) takepiro)
Definition at line 99 of file t_reference_scalar_param.f90.
References m_machine_parameter::iflag_debug, m_machine_parameter::iflag_routine_msg, set_linear_ref_scalar_ctl(), and set_takepiro_scalar_ctl().
Referenced by set_control_4_model::s_set_control_4_model().
set_takepiro_scalar_ctl()
subroutine, private t_reference_scalar_param::set_takepiro_scalar_ctl (type(read_character_item), intent(in) stratified_ctl, type(takepiro_model_control), intent(in) takepiro_ctl, integer(kind = kint), intent(inout) iflag_ref, type(takepiro_model_param), intent(inout) takepiro) private
Definition at line 203 of file t_reference_scalar_param.f90.
References calypso_mpi::calypso_mpi_abort(), m_machine_parameter::e_message, id_takepiro_temp, m_error_ids::ierr_fld, m_machine_parameter::iflag_debug, and m_machine_parameter::iflag_routine_msg.
Referenced by set_reference_scalar_ctl().
Variable Documentation
id_linear_r_ref_temp
integer (kind=kint), parameter t_reference_scalar_param::id_linear_r_ref_temp = 200
flag to use linearly decrease referece temperature as a function of \(r \)
Definition at line 52 of file t_reference_scalar_param.f90.
Referenced by set_linear_ref_scalar_ctl().
id_no_ref_temp
integer (kind=kint), parameter t_reference_scalar_param::id_no_ref_temp = 0
flag for solving full temperature
Definition at line 41 of file t_reference_scalar_param.f90.
Referenced by add_nodal_fields_4_mhd::add_ctl_4_forces(), add_nodal_fields_4_mhd::add_ctl_4_ref_temp(), and set_linear_ref_scalar_ctl().
id_sphere_ref_temp
integer (kind=kint), parameter t_reference_scalar_param::id_sphere_ref_temp = 100
flag to use referece temperature as a function of \(r \)
Definition at line 49 of file t_reference_scalar_param.f90.
Referenced by cal_nonlinear_sph_mhd::add_reference_advect_sph(), cal_buoyancy_flux_sph::cal_buoyancy_flux_rtp(), init_radial_infos_sph_mhd::init_reference_temps(), cal_buoyancy_flux_sph::pole_buoyancy_flux_rtp(), self_buoyancy_on_sphere::r_buoyancy_on_sphere(), cal_self_buoyancies_sph::sel_buoyancies_sph_mhd(), div_self_buoyancies_sph::sel_div_buoyancies_sph_mhd(), set_initial_sph_scalars::set_ini_reference_temp_sph(), set_linear_ref_scalar_ctl(), set_initial_sph_scalars::set_noize_scalar_sph(), adjust_reference_fields::sync_scalar_by_pert_sph(), and adjust_reference_fields::trans_pert_to_scalar_sph().
id_takepiro_temp
integer (kind=kint), parameter t_reference_scalar_param::id_takepiro_temp = 1000
takepiro model flag
Definition at line 54 of file t_reference_scalar_param.f90.
Referenced by cal_buoyancy_flux_sph::cal_buoyancy_flux_rtp(), init_radial_infos_sph_mhd::init_reference_temps(), cal_buoyancy_flux_sph::pole_buoyancy_flux_rtp(), self_buoyancy_on_sphere::r_buoyancy_on_sphere(), cal_self_buoyancies_sph::sel_buoyancies_sph_mhd(), div_self_buoyancies_sph::sel_div_buoyancies_sph_mhd(), set_linear_ref_scalar_ctl(), set_takepiro_scalar_ctl(), adjust_reference_fields::sync_scalar_by_pert_sph(), and adjust_reference_fields::trans_pert_to_scalar_sph().
id_x_ref_temp
integer (kind=kint), parameter t_reference_scalar_param::id_x_ref_temp = 0
flag to use referece temperature as a function of \(x \)
Definition at line 43 of file t_reference_scalar_param.f90.
Referenced by set_linear_ref_scalar_ctl().
id_y_ref_temp
integer (kind=kint), parameter t_reference_scalar_param::id_y_ref_temp = 0
flag to use referece temperature as a function of \(y \)
Definition at line 45 of file t_reference_scalar_param.f90.
Referenced by set_linear_ref_scalar_ctl().
id_z_ref_temp
integer (kind=kint), parameter t_reference_scalar_param::id_z_ref_temp = 0
flag to use referece temperature as a function of \(z \)
Definition at line 47 of file t_reference_scalar_param.f90.
Referenced by set_linear_ref_scalar_ctl().
label_linear_x
character(len = kchara), parameter t_reference_scalar_param::label_linear_x = 'linear_x'
Definition at line 63 of file t_reference_scalar_param.f90.
Referenced by set_linear_ref_scalar_ctl().
label_linear_y
character(len = kchara), parameter t_reference_scalar_param::label_linear_y = 'linear_y'
Definition at line 64 of file t_reference_scalar_param.f90.
Referenced by set_linear_ref_scalar_ctl().
label_linear_z
character(len = kchara), parameter t_reference_scalar_param::label_linear_z = 'linear_z'
Definition at line 65 of file t_reference_scalar_param.f90.
Referenced by set_linear_ref_scalar_ctl().
label_sph_const_heat
character(len = kchara), parameter t_reference_scalar_param::label_sph_const_heat = 'sph_constant_heat'
Definition at line 59 of file t_reference_scalar_param.f90.
Referenced by set_linear_ref_scalar_ctl().
label_sph_shell
character(len = kchara), parameter t_reference_scalar_param::label_sph_shell = 'spherical_shell'
Definition at line 57 of file t_reference_scalar_param.f90.
Referenced by set_linear_ref_scalar_ctl().
label_takepiro
character(len = kchara), parameter t_reference_scalar_param::label_takepiro = 'takepiro'
Definition at line 61 of file t_reference_scalar_param.f90.
Referenced by set_linear_ref_scalar_ctl().