CALYPSO: const_sph_rotation Module Reference
const_sph_rotation Module Reference
Evaluate curl of fields.
Functions/Subroutines
subroutine const_sph_vorticity (sph_rj, r_2nd, sph_bc_U, fdm2_free_ICB, fdm2_free_CMB, g_sph_rj, is_velo, is_vort, rj_fld)
subroutine const_sph_current (sph_rj, r_2nd, sph_bc_B, g_sph_rj, is_magne, is_current, rj_fld)
subroutine const_sph_rotation_uxb (sph_rj, r_2nd, sph_bc_B, g_sph_rj, is_fld, is_rot, rj_fld)
subroutine const_sph_rotation_no_bc (sph_rj, r_2nd, sph_bc, g_sph_rj, is_fld, is_rot, rj_fld)
subroutine const_sph_force_rot2 (sph_rj, r_2nd, sph_bc_U, fdm2_free_ICB, fdm2_free_CMB, g_sph_rj, is_fld, is_rot, rj_fld)
subroutine const_sph_viscous_by_vort2 (sph_rj, r_2nd, sph_bc_U, fdm2_free_ICB, fdm2_free_CMB, g_sph_rj, coef_diffuse, is_velo, is_vort, is_viscous, rj_fld)
subroutine const_sph_mag_diffuse_by_j (sph_rj, r_2nd, sph_bc_B, g_sph_rj, coef_diffuse, is_magne, is_current, is_ohmic, rj_fld)
Detailed Description
Evaluate curl of fields.
      subroutine const_sph_vorticity(sph_rj, r_2nd, sph_bc_U,         &
     &          fdm2_free_ICB, fdm2_free_CMB, g_sph_rj,               &
     &          is_velo, is_vort, rj_fld)
        Address for input:    is_velo, is_velo+2
        Address for solution: is_vort, is_vort+2, is_vort+1
      subroutine const_sph_current(sph_rj, r_2nd, sph_bc_B, g_sph_rj, &
     &          is_magne, is_current, rj_fld)
        Address for input:    is_magne, is_magne+2
        Address for solution: is_current, is_current+2, is_current+1
      subroutine const_sph_rotation_uxb(sph_rj, r_2nd, sph_bc_B,      &
     &          g_sph_rj, is_fld, is_rot, rj_fld)
        Address for input:    is_fld, it_fld
        Address for solution: is_rot, it_rot, ids_rot
      subroutine const_sph_rotation_no_bc(sph_rj, r_2nd, sph_bc,      &
     &          g_sph_rj, is_fld, is_rot, rj_fld)
        Address for input:    is_fld, it_fld
        Address for solution: is_rot, it_rot, ids_rot
      subroutine const_sph_force_rot2(sph_rj, r_2nd,                  &
     &          sph_bc_U, fdm2_free_ICB, fdm2_free_CMB, g_sph_rj,     &
     &          is_fld, is_rot, rj_fld)
        Address for input:    is_fld, it_fld
        Address for solution: is_rot, it_rot, ids_rot
      subroutine const_sph_viscous_by_vort2                           &
     &         (sph_rj, r_2nd, sph_bc_U, fdm2_free_ICB, fdm2_free_CMB,&
     &          g_sph_rj, coef_diffuse, is_velo, is_vort, is_viscous, &
     &          rj_fld)
        Address for input:    is_velo, is_vort, is_vort+2
        Address for solution: is_viscous, is_viscous+2, is_viscous+1
      subroutine const_sph_mag_diffuse_by_j                           &
     &         (sph_rj, r_2nd, sph_bc_B, g_sph_rj, coef_diffuse,      &
     &          is_magne, is_current, is_ohmic, rj_fld)
        Address for input:    is_magne, is_current, is_current+2
        Address for solution: is_ohmic, is_ohmic+2, is_ohmic+1
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(fdm_matrices), intent(in) :: r_2nd
        type(sph_boundary_type), intent(in) :: sph_bc_U
        type(sph_boundary_type), intent(in) :: sph_bc_B
        type(fdm2_free_slip), intent(in) :: fdm2_free_ICB
        type(fdm2_free_slip), intent(in) :: fdm2_free_CMB
        type(phys_data), intent(inout) :: rj_fld
Parameters
sph_bc_U Structure for basic boundary condition parameters for velocity
sph_bc_B Structure for basic boundary condition parameters for magnetic field
sph_bc Structure for basic boundary condition parameters
kr_inside Radial ID for inner boundary
kr_outside RaAdial ID for outer boundary
coef_fdm_fix_in_2(0:2,3) Finite difference matrix for inner boundary
coef_fdm_fix_out_2(0:2,3) Finite difference matrix for outer boundary
coef_diffuse Diffusion coefficient
is_fld Input spectr field address
is_rot Address of curl of field
is_velo Spherical hermonics data address for poloidal velocity field
is_vort Spherical hermonics data address for poloidal voeticity
is_viscous Spherical hermonics data address for poloidal visous diffusion
is_magne Spherical hermonics data address for poloidal magnetic field
is_current Spherical hermonics data address for poloidal current density
is_ohmic Spherical hermonics data address for poloidal ohmic dissipation
Function/Subroutine Documentation
const_sph_current()
subroutine const_sph_rotation::const_sph_current (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc_B, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, integer(kind = kint), intent(in) is_magne, integer(kind = kint), intent(in) is_current, type(phys_data), intent(inout) rj_fld)
Definition at line 145 of file const_sph_rotation.f90.
References cal_sph_exp_rotation::cal_sph_nod_vect_rot2(), select_exp_magne_cmb::sel_cmb_sph_current(), and select_exp_magne_icb::sel_icb_sph_current().
const_sph_force_rot2()
subroutine const_sph_rotation::const_sph_force_rot2 (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc_U, type(fdm2_free_slip), intent(in) fdm2_free_ICB, type(fdm2_free_slip), intent(in) fdm2_free_CMB, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_rot, type(phys_data), intent(inout) rj_fld)
Definition at line 235 of file const_sph_rotation.f90.
References cal_sph_exp_rotation::cal_sph_nod_vect_w_div_rot2(), select_exp_velocity_cmb::sel_cmb_sph_vorticity(), and select_exp_velocity_icb::sel_icb_sph_vorticity().
Referenced by cal_sph_field_by_rotation::cal_rot_of_forces_sph_2().
const_sph_mag_diffuse_by_j()
subroutine const_sph_rotation::const_sph_mag_diffuse_by_j (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc_B, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, real(kind = kreal), intent(in) coef_diffuse, integer(kind = kint), intent(in) is_magne, integer(kind = kint), intent(in) is_current, integer(kind = kint), intent(in) is_ohmic, type(phys_data), intent(inout) rj_fld)
Definition at line 309 of file const_sph_rotation.f90.
References cal_sph_exp_rotation::cal_sph_nod_diffuse_by_rot2(), select_exp_magne_cmb::sel_cmb_sph_magnetic_diffusion(), and select_exp_magne_icb::sel_icb_sph_magnetic_diffusion().
Referenced by cal_sol_sph_mhd_crank::update_after_magne_sph().
const_sph_rotation_no_bc()
subroutine const_sph_rotation::const_sph_rotation_no_bc (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_rot, type(phys_data), intent(inout) rj_fld)
Definition at line 203 of file const_sph_rotation.f90.
References cal_sph_exp_nod_none_bc::cal_sph_nod_nobc_in_rot2(), cal_sph_exp_nod_none_bc::cal_sph_nod_nobc_out_rot2(), and cal_sph_exp_rotation::cal_sph_nod_vect_rot2().
const_sph_rotation_uxb()
subroutine const_sph_rotation::const_sph_rotation_uxb (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc_B, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_rot, type(phys_data), intent(inout) rj_fld)
Definition at line 174 of file const_sph_rotation.f90.
References cal_sph_exp_rotation::cal_sph_nod_vect_w_div_rot2(), select_exp_magne_cmb::sel_cmb_sph_rotation_uxb(), and select_exp_magne_icb::sel_icb_sph_rotation_uxb().
Referenced by cal_sph_field_by_rotation::cal_rot_of_induction_sph().
const_sph_viscous_by_vort2()
subroutine const_sph_rotation::const_sph_viscous_by_vort2 (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc_U, type(fdm2_free_slip), intent(in) fdm2_free_ICB, type(fdm2_free_slip), intent(in) fdm2_free_CMB, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, real(kind = kreal), intent(in) coef_diffuse, integer(kind = kint), intent(in) is_velo, integer(kind = kint), intent(in) is_vort, integer(kind = kint), intent(in) is_viscous, type(phys_data), intent(inout) rj_fld)
Definition at line 270 of file const_sph_rotation.f90.
References cal_sph_exp_rotation::cal_sph_nod_diffuse_by_rot2(), select_exp_velocity_cmb::sel_cmb_sph_viscous_diffusion(), and select_exp_velocity_icb::sel_icb_sph_viscous_diffusion().
Referenced by cal_sol_sph_mhd_crank::update_after_vorticity_sph().
const_sph_vorticity()
subroutine const_sph_rotation::const_sph_vorticity (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc_U, type(fdm2_free_slip), intent(in) fdm2_free_ICB, type(fdm2_free_slip), intent(in) fdm2_free_CMB, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, integer(kind = kint), intent(in) is_velo, integer(kind = kint), intent(in) is_vort, type(phys_data), intent(inout) rj_fld)
Definition at line 111 of file const_sph_rotation.f90.
References cal_sph_exp_rotation::cal_sph_nod_vect_rot2(), select_exp_velocity_cmb::sel_cmb_sph_vorticity(), and select_exp_velocity_icb::sel_icb_sph_vorticity().