CALYPSO: gz_mpi_sph_modes_file_io Module Reference
gz_mpi_sph_modes_file_io Module Reference
gzipped merged ASCII spectr data IO routines
Functions/Subroutines
subroutine gz_mpi_read_geom_rtp_file (file_name, num_pe, id_rank, sph_file)
subroutine gz_mpi_read_spectr_rj_file (file_name, num_pe, id_rank, sph_file)
subroutine gz_mpi_read_geom_rtm_file (file_name, num_pe, id_rank, sph_file)
subroutine gz_mpi_read_modes_rlm_file (file_name, num_pe, id_rank, sph_file)
subroutine gz_mpi_write_geom_rtp_file (file_name, sph_file)
subroutine gz_mpi_write_spectr_rj_file (file_name, sph_file)
subroutine gz_mpi_write_geom_rtm_file (file_name, sph_file)
subroutine gz_mpi_write_modes_rlm_file (file_name, sph_file)
Variables
type(calypso_mpi_io_params), save, private io_param
Detailed Description
gzipped merged ASCII spectr data IO routines
      subroutine gz_mpi_read_geom_rtp_file                            &
     &         (file_name, num_pe, id_rank, sph_file)
      subroutine gz_mpi_read_spectr_rj_file                           &
     &         (file_name, num_pe, id_rank, sph_file)
      subroutine gz_mpi_read_geom_rtm_file                            &
     &         (file_name, num_pe, id_rank, sph_file)
      subroutine gz_mpi_read_modes_rlm_file                           &
     &         (file_name, num_pe, id_rank, sph_file)
        type(sph_file_data_type), intent(inout) :: sph_file
      subroutine gz_mpi_write_geom_rtp_file(file_name, sph_file)
      subroutine gz_mpi_write_spectr_rj_file(file_name, sph_file)
      subroutine gz_mpi_write_geom_rtm_file(file_name, sph_file)
      subroutine gz_mpi_write_modes_rlm_file(file_name, sph_file)
        type(sph_file_data_type), intent(in) :: sph_file
Parameters
id_rank Process ID
file_name file name for IO (.gz is appended in this module)
Function/Subroutine Documentation
gz_mpi_read_geom_rtm_file()
subroutine gz_mpi_sph_modes_file_io::gz_mpi_read_geom_rtm_file (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, type(sph_file_data_type), intent(inout) sph_file)
Definition at line 95 of file gz_MPI_sph_modes_file_IO.f90.
References mpi_ascii_data_io::close_mpi_file(), gz_mpi_sph_modes_data_io::gz_mpi_read_geom_rtm_data(), m_machine_parameter::i_debug, io_param, and mpi_ascii_data_io::open_read_mpi_file().
Referenced by sph_file_mpi_io_select::sel_mpi_read_geom_rtm_file().
gz_mpi_read_geom_rtp_file()
subroutine gz_mpi_sph_modes_file_io::gz_mpi_read_geom_rtp_file (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, type(sph_file_data_type), intent(inout) sph_file)
Definition at line 50 of file gz_MPI_sph_modes_file_IO.f90.
References mpi_ascii_data_io::close_mpi_file(), gz_mpi_sph_modes_data_io::gz_mpi_read_geom_rtp_data(), m_machine_parameter::i_debug, io_param, and mpi_ascii_data_io::open_read_mpi_file().
Referenced by sph_file_mpi_io_select::sel_mpi_read_geom_rtp_file().
gz_mpi_read_modes_rlm_file()
subroutine gz_mpi_sph_modes_file_io::gz_mpi_read_modes_rlm_file (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, type(sph_file_data_type), intent(inout) sph_file)
Definition at line 117 of file gz_MPI_sph_modes_file_IO.f90.
References mpi_ascii_data_io::close_mpi_file(), gz_mpi_sph_modes_data_io::gz_mpi_read_modes_rlm_data(), m_machine_parameter::i_debug, io_param, and mpi_ascii_data_io::open_read_mpi_file().
Referenced by sph_file_mpi_io_select::sel_mpi_read_modes_rlm_file().
gz_mpi_read_spectr_rj_file()
subroutine gz_mpi_sph_modes_file_io::gz_mpi_read_spectr_rj_file (character(len=kchara), intent(in) file_name, integer, intent(in) num_pe, integer, intent(in) id_rank, type(sph_file_data_type), intent(inout) sph_file)
Definition at line 72 of file gz_MPI_sph_modes_file_IO.f90.
References mpi_ascii_data_io::close_mpi_file(), gz_mpi_sph_modes_data_io::gz_mpi_read_spectr_rj_data(), m_machine_parameter::i_debug, io_param, and mpi_ascii_data_io::open_read_mpi_file().
Referenced by sph_file_mpi_io_select::sel_mpi_read_spectr_rj_file().
gz_mpi_write_geom_rtm_file()
subroutine gz_mpi_sph_modes_file_io::gz_mpi_write_geom_rtm_file (character(len=kchara), intent(in) file_name, type(sph_file_data_type), intent(in) sph_file)
Definition at line 180 of file gz_MPI_sph_modes_file_IO.f90.
References mpi_ascii_data_io::close_mpi_file(), gz_mpi_sph_modes_data_io::gz_mpi_write_geom_rtm_data(), m_machine_parameter::i_debug, io_param, and mpi_ascii_data_io::open_write_mpi_file().
Referenced by sph_file_mpi_io_select::sel_mpi_write_geom_rtm_file().
gz_mpi_write_geom_rtp_file()
subroutine gz_mpi_sph_modes_file_io::gz_mpi_write_geom_rtp_file (character(len=kchara), intent(in) file_name, type(sph_file_data_type), intent(in) sph_file)
Definition at line 141 of file gz_MPI_sph_modes_file_IO.f90.
References mpi_ascii_data_io::close_mpi_file(), gz_mpi_sph_modes_data_io::gz_mpi_write_geom_rtp_data(), m_machine_parameter::i_debug, io_param, and mpi_ascii_data_io::open_write_mpi_file().
Referenced by sph_file_mpi_io_select::sel_mpi_write_geom_rtp_file().
gz_mpi_write_modes_rlm_file()
subroutine gz_mpi_sph_modes_file_io::gz_mpi_write_modes_rlm_file (character(len=kchara), intent(in) file_name, type(sph_file_data_type), intent(in) sph_file)
Definition at line 199 of file gz_MPI_sph_modes_file_IO.f90.
References mpi_ascii_data_io::close_mpi_file(), gz_mpi_sph_modes_data_io::gz_mpi_write_modes_rlm_data(), m_machine_parameter::i_debug, io_param, and mpi_ascii_data_io::open_write_mpi_file().
Referenced by sph_file_mpi_io_select::sel_mpi_write_modes_rlm_file().
gz_mpi_write_spectr_rj_file()
subroutine gz_mpi_sph_modes_file_io::gz_mpi_write_spectr_rj_file (character(len=kchara), intent(in) file_name, type(sph_file_data_type), intent(in) sph_file)
Definition at line 160 of file gz_MPI_sph_modes_file_IO.f90.
References mpi_ascii_data_io::close_mpi_file(), gz_mpi_sph_modes_data_io::gz_mpi_write_spectr_rj_data(), m_machine_parameter::i_debug, io_param, and mpi_ascii_data_io::open_write_mpi_file().
Referenced by sph_file_mpi_io_select::sel_mpi_write_spectr_rj_file().
Variable Documentation
io_param
type(calypso_mpi_io_params), save, private gz_mpi_sph_modes_file_io::io_param private
Definition at line 42 of file gz_MPI_sph_modes_file_IO.f90.
Referenced by gz_mpi_read_geom_rtm_file(), gz_mpi_read_geom_rtp_file(), gz_mpi_read_modes_rlm_file(), gz_mpi_read_spectr_rj_file(), gz_mpi_write_geom_rtm_file(), gz_mpi_write_geom_rtp_file(), gz_mpi_write_modes_rlm_file(), and gz_mpi_write_spectr_rj_file().