CALYPSO: copy_mesh_structures Module Reference
copy_mesh_structures Module Reference
Copy FEM mesh structures.
Functions/Subroutines
subroutine set_mesh_data_from_type (mesh, group, tgt_mesh, tgt_grp)
subroutine copy_node_geometry_types (org_node, new_node)
subroutine copy_node_sph_to_xx (org_node, new_node)
subroutine copy_node_cyl_to_xx (org_node, new_node)
subroutine copy_element_connect_types (org_ele, new_ele)
subroutine copy_comm_tbl_types (org_comm, new_comm)
subroutine copy_group_data (org_grp, new_grp)
subroutine copy_surface_group (org_sf_grp, new_sf_grp)
Detailed Description
Copy FEM mesh structures.
      subroutine set_mesh_data_from_type                              &
     &         (mesh, group, tgt_mesh, tgt_grp)
        type(mesh_geometry), intent(inout) :: mesh
        type(mesh_groups), intent(inout) :: group
        type(mesh_geometry), intent(inout) :: tgt_mesh
        type(mesh_groups), intent(inout) :: tgt_grp
      subroutine copy_node_geometry_types(org_node, new_node)
      subroutine copy_node_sph_to_xx(org_node, new_node)
      subroutine copy_node_cyl_to_xx(org_node, new_node)
        type(node_data), intent(in) :: org_node
        type(node_data), intent(in) :: new_node
      subroutine copy_element_connect_types(org_ele, new_ele)
        type(element_data), intent(in) :: org_ele
        type(element_data), intent(in) :: new_ele
      subroutine copy_comm_tbl_types(org_comm, comm_tbls)
        type(communication_table), intent(in) :: org_comm
        type(communication_table), intent(inout) :: new_comm
      subroutine copy_group_data(org_grp, new_grp)
        type(group_data), intent(in) :: org_grp
        type(group_data), intent(inout) :: new_grp
      subroutine copy_surface_group(org_sf_grp, new_sf_grp)
        type(surface_group_data), intent(in) :: org_sf_grp
        type(surface_group_data), intent(inout) :: new_sf_grp
Function/Subroutine Documentation
copy_comm_tbl_types()
subroutine copy_mesh_structures::copy_comm_tbl_types (type(communication_table), intent(in) org_comm, type(communication_table), intent(inout) new_comm)
Definition at line 221 of file copy_mesh_structures.f90.
References t_comm_table::alloc_comm_table_item(), and t_comm_table::alloc_comm_table_num().
Referenced by set_mesh_data_from_type().
copy_element_connect_types()
subroutine copy_mesh_structures::copy_element_connect_types (type(element_data), intent(in) org_ele, type(element_data), intent(inout) new_ele)
Definition at line 177 of file copy_mesh_structures.f90.
References t_geometry_data::allocate_ele_connect_type(), and set_nnod_4_ele_by_type::set_nnod_4_ele_by_eletype().
Referenced by set_mesh_data_from_type().
copy_group_data()
subroutine copy_mesh_structures::copy_group_data (type(group_data), intent(in) org_grp, type(group_data), intent(inout) new_grp)
Definition at line 263 of file copy_mesh_structures.f90.
References t_group_data::alloc_group_item(), and t_group_data::alloc_group_num().
Referenced by add_comm_table_in_node_grp::add_comm_tbl_in_node_grp_mesh(), t_const_spherical_grid::copy_sph_radial_groups(), and set_mesh_data_from_type().
copy_node_cyl_to_xx()
subroutine copy_mesh_structures::copy_node_cyl_to_xx (type(node_data), intent(in) org_node, type(node_data), intent(inout) new_node)
Definition at line 148 of file copy_mesh_structures.f90.
References t_geometry_data::alloc_node_geometry_base().
copy_node_geometry_types()
subroutine copy_mesh_structures::copy_node_geometry_types (type(node_data), intent(in) org_node, type(node_data), intent(inout) new_node)
Definition at line 92 of file copy_mesh_structures.f90.
References t_geometry_data::alloc_node_geometry_base().
Referenced by mpi_load_mesh_data::mpi_output_mesh(), load_mesh_data::output_mesh(), set_mesh_data_from_type(), load_mesh_data::set_mesh_geometry_data(), and load_mesh_data::set_node_geometry_data().
copy_node_sph_to_xx()
subroutine copy_mesh_structures::copy_node_sph_to_xx (type(node_data), intent(in) org_node, type(node_data), intent(inout) new_node)
Definition at line 120 of file copy_mesh_structures.f90.
References t_geometry_data::alloc_node_geometry_base().
copy_surface_group()
subroutine copy_mesh_structures::copy_surface_group (type(surface_group_data), intent(in) org_sf_grp, type(surface_group_data), intent(inout) new_sf_grp)
Definition at line 294 of file copy_mesh_structures.f90.
References t_group_data::alloc_sf_group_item(), and t_group_data::alloc_sf_group_num().
Referenced by set_mesh_data_from_type().
set_mesh_data_from_type()
subroutine copy_mesh_structures::set_mesh_data_from_type (type(mesh_geometry), intent(inout) mesh, type(mesh_groups), intent(inout) group, type(mesh_geometry), intent(inout) tgt_mesh, type(mesh_groups), intent(inout) tgt_grp)
Definition at line 50 of file copy_mesh_structures.f90.
References t_geometry_data::alloc_sph_node_geometry(), copy_comm_tbl_types(), copy_element_connect_types(), copy_group_data(), copy_node_geometry_types(), copy_surface_group(), t_mesh_data::dealloc_groups_data(), t_mesh_data::dealloc_mesh_geometry_base(), and set_nnod_4_ele_by_type::set_3d_nnod_4_sfed_by_ele().
Referenced by t_check_and_make_sph_mesh::load_fem_mesh_4_sph().