CALYPSO: m_intersection_data_9 Module Reference
m_intersection_data_9 Module Reference
Variables
integer(kind=kint), parameter, private nnod_tri = 3
integer(kind=kint), parameter, private nnod_hex = 6
integer(kind=kint), parameter nkind_etype_9 = 8
integer(kind=kint), parameter num_patch_9 = 4
integer(kind=kint), dimension(12), parameter itri_2_patch_9 = (/2, 3, 4, 2, 4, 5, 2, 5, 1, 1, 5, 6/)
integer(kind=kint), dimension(nkind_etype_9), parameter iflag_psf_etype_9 = (/27, 39, 78, 141, 177, 114, 228, 216/)
integer(kind=kint), dimension(nnod_hex, nkind_etype_9), parameter iedge_hex_9 = reshape((/ 2, 10, 5, 8, 12, 3, 3, 11, 6, 5, 9, 4, 4, 12, 7, 6, 10, 1, 1, 9, 8, 7, 11, 2, 7, 12, 4, 1, 10, 6, 8, 9, 1, 2, 11, 7, 5, 10, 2, 3, 12, 8, 6, 11, 3, 4, 9, 5/), shape=(/nnod_hex, nkind_etype_9/))
integer(kind=kint), dimension(nnod_tri, num_patch_9, nkind_etype_9), parameter iedge_4_patch_9 = reshape((/10, 5, 8, 10, 8, 12, 10, 12, 2, 2, 12, 3, 11, 6, 5, 11, 5, 9, 11, 9, 3, 3, 9, 4, 12, 7, 6, 12, 6, 10, 12, 10, 4, 4, 10, 1, 9, 8, 7, 9, 7, 11, 9, 11, 1, 1, 11, 2, 12, 4, 1, 12, 1, 10, 12, 10, 7, 7, 10, 6, 9, 1, 2, 9, 2, 11, 9, 11, 8, 8, 11, 7, 10, 2, 3, 10, 3, 12, 10, 12, 5, 5, 12, 8, 11, 3, 4, 11, 4, 9, 11, 9, 6, 6, 9, 5/), shape=(/nnod_tri,num_patch_9,nkind_etype_9/))
Variable Documentation
iedge_4_patch_9
integer(kind = kint), dimension(nnod_tri,num_patch_9,nkind_etype_9), parameter m_intersection_data_9::iedge_4_patch_9 = reshape((/10, 5, 8, 10, 8, 12, 10, 12, 2, 2, 12, 3, 11, 6, 5, 11, 5, 9, 11, 9, 3, 3, 9, 4, 12, 7, 6, 12, 6, 10, 12, 10, 4, 4, 10, 1, 9, 8, 7, 9, 7, 11, 9, 11, 1, 1, 11, 2, 12, 4, 1, 12, 1, 10, 12, 10, 7, 7, 10, 6, 9, 1, 2, 9, 2, 11, 9, 11, 8, 8, 11, 7, 10, 2, 3, 10, 3, 12, 10, 12, 5, 5, 12, 8, 11, 3, 4, 11, 4, 9, 11, 9, 6, 6, 9, 5/), shape=(/nnod_tri,num_patch_9,nkind_etype_9/))
Definition at line 60 of file m_intersection_data_9.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
iedge_hex_9
integer(kind = kint), dimension(nnod_hex, nkind_etype_9), parameter m_intersection_data_9::iedge_hex_9 = reshape((/ 2, 10, 5, 8, 12, 3, 3, 11, 6, 5, 9, 4, 4, 12, 7, 6, 10, 1, 1, 9, 8, 7, 11, 2, 7, 12, 4, 1, 10, 6, 8, 9, 1, 2, 11, 7, 5, 10, 2, 3, 12, 8, 6, 11, 3, 4, 9, 5/), shape=(/nnod_hex, nkind_etype_9/))
Definition at line 51 of file m_intersection_data_9.f90.
iflag_psf_etype_9
integer(kind = kint), dimension(nkind_etype_9), parameter m_intersection_data_9::iflag_psf_etype_9 = (/27, 39, 78, 141, 177, 114, 228, 216/)
Definition at line 46 of file m_intersection_data_9.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
itri_2_patch_9
integer(kind = kint), dimension(12), parameter m_intersection_data_9::itri_2_patch_9 = (/2, 3, 4, 2, 4, 5, 2, 5, 1, 1, 5, 6/)
Definition at line 43 of file m_intersection_data_9.f90.
nkind_etype_9
integer(kind = kint), parameter m_intersection_data_9::nkind_etype_9 = 8
Definition at line 41 of file m_intersection_data_9.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
nnod_hex
integer(kind = kint), parameter, private m_intersection_data_9::nnod_hex = 6 private
Definition at line 39 of file m_intersection_data_9.f90.
nnod_tri
integer(kind = kint), parameter, private m_intersection_data_9::nnod_tri = 3 private
Definition at line 38 of file m_intersection_data_9.f90.
num_patch_9
integer(kind = kint), parameter m_intersection_data_9::num_patch_9 = 4
Definition at line 42 of file m_intersection_data_9.f90.
Referenced by t_psf_case_table::init_psf_case_tables().