CALYPSO: m_intersection_data_11 Module Reference
m_intersection_data_11 Module Reference
Variables
integer(kind=kint), parameter, private nnod_tri = 3
integer(kind=kint), parameter, private nnod_hex = 6
integer(kind=kint), parameter nkind_etype_11 = 12
integer(kind=kint), parameter num_patch_11 = 4
integer(kind=kint), dimension(12), parameter itri_2_patch_11 = (/3, 1, 2, 4, 1, 3, 4, 6, 1, 4, 5, 6/)
integer(kind=kint), dimension(nkind_etype_11), parameter iflag_psf_etype_11 = (/ 71, 142, 29, 43, 184, 113, 226, 212, 54, 108, 201, 147/)
integer(kind=kint), dimension(nnod_hex, nkind_etype_11), parameter iedge_hex_11 = reshape((/ 3, 7, 6, 10, 9, 4, 4, 8, 7, 11, 10, 1, 1, 5, 8, 12, 11, 2, 2, 6, 5, 9, 12, 3, 7, 3, 4, 9, 10, 6, 8, 4, 1, 10, 11, 7, 5, 1, 2, 11, 12, 8, 6, 2, 3, 12, 9, 5, 1, 3, 11, 6, 8, 9, 2, 4, 12, 7, 5, 10, 3, 1, 9, 8, 6, 11, 4, 2, 10, 5, 7, 12/), shape=(/nnod_hex, nkind_etype_11/))
integer(kind=kint), dimension(nnod_tri, num_patch_11, nkind_etype_11), parameter iedge_4_patch_11 = reshape((/ 6, 3, 7, 10, 3, 6, 10, 4, 3, 10, 9, 4, 7, 4, 8, 11, 4, 7, 11, 1, 4, 11, 10, 1, 8, 1, 5, 12, 1, 8, 12, 2, 1, 12, 11, 2, 5, 2, 6, 9, 2, 5, 9, 3, 2, 9, 12, 3, 4, 7, 3, 9, 7, 4, 9, 6, 7, 9, 10, 6, 1, 8, 4, 10, 8, 1, 10, 7, 8, 10, 11, 7, 2, 5, 1, 11, 5, 2, 11, 8, 5, 11, 12, 8, 3, 6, 2, 12, 6, 3, 12, 5, 6, 12, 9, 5, 11, 1, 3, 6, 1, 11, 6, 9, 1, 6, 8, 9, 12, 2, 4, 7, 2, 12, 7, 10, 2, 7, 5, 10, 9, 3, 1, 8, 3, 9, 8, 11, 3, 8, 6, 11, 10, 4, 2, 5, 4, 10, 5, 12, 4, 5, 7, 12/), shape=(/nnod_tri,num_patch_11,nkind_etype_11/))
Variable Documentation
iedge_4_patch_11
integer(kind = kint), dimension(nnod_tri,num_patch_11,nkind_etype_11), parameter m_intersection_data_11::iedge_4_patch_11 = reshape((/ 6, 3, 7, 10, 3, 6, 10, 4, 3, 10, 9, 4, 7, 4, 8, 11, 4, 7, 11, 1, 4, 11, 10, 1, 8, 1, 5, 12, 1, 8, 12, 2, 1, 12, 11, 2, 5, 2, 6, 9, 2, 5, 9, 3, 2, 9, 12, 3, 4, 7, 3, 9, 7, 4, 9, 6, 7, 9, 10, 6, 1, 8, 4, 10, 8, 1, 10, 7, 8, 10, 11, 7, 2, 5, 1, 11, 5, 2, 11, 8, 5, 11, 12, 8, 3, 6, 2, 12, 6, 3, 12, 5, 6, 12, 9, 5, 11, 1, 3, 6, 1, 11, 6, 9, 1, 6, 8, 9, 12, 2, 4, 7, 2, 12, 7, 10, 2, 7, 5, 10, 9, 3, 1, 8, 3, 9, 8, 11, 3, 8, 6, 11, 10, 4, 2, 5, 4, 10, 5, 12, 4, 5, 7, 12/), shape=(/nnod_tri,num_patch_11,nkind_etype_11/))
Definition at line 74 of file m_intersection_data_11.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
iedge_hex_11
integer(kind = kint), dimension(nnod_hex, nkind_etype_11), parameter m_intersection_data_11::iedge_hex_11 = reshape((/ 3, 7, 6, 10, 9, 4, 4, 8, 7, 11, 10, 1, 1, 5, 8, 12, 11, 2, 2, 6, 5, 9, 12, 3, 7, 3, 4, 9, 10, 6, 8, 4, 1, 10, 11, 7, 5, 1, 2, 11, 12, 8, 6, 2, 3, 12, 9, 5, 1, 3, 11, 6, 8, 9, 2, 4, 12, 7, 5, 10, 3, 1, 9, 8, 6, 11, 4, 2, 10, 5, 7, 12/), shape=(/nnod_hex, nkind_etype_11/))
Definition at line 63 of file m_intersection_data_11.f90.
iflag_psf_etype_11
integer(kind = kint), dimension(nkind_etype_11), parameter m_intersection_data_11::iflag_psf_etype_11 = (/ 71, 142, 29, 43, 184, 113, 226, 212, 54, 108, 201, 147/)
Definition at line 57 of file m_intersection_data_11.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
itri_2_patch_11
integer(kind = kint), dimension(12), parameter m_intersection_data_11::itri_2_patch_11 = (/3, 1, 2, 4, 1, 3, 4, 6, 1, 4, 5, 6/)
Definition at line 54 of file m_intersection_data_11.f90.
nkind_etype_11
integer(kind = kint), parameter m_intersection_data_11::nkind_etype_11 = 12
Definition at line 52 of file m_intersection_data_11.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
nnod_hex
integer(kind = kint), parameter, private m_intersection_data_11::nnod_hex = 6 private
Definition at line 50 of file m_intersection_data_11.f90.
nnod_tri
integer(kind = kint), parameter, private m_intersection_data_11::nnod_tri = 3 private
Definition at line 49 of file m_intersection_data_11.f90.
num_patch_11
integer(kind = kint), parameter m_intersection_data_11::num_patch_11 = 4
Definition at line 53 of file m_intersection_data_11.f90.
Referenced by t_psf_case_table::init_psf_case_tables().