CALYPSO: /home/takumi kera/calypso/src/programs/data_utilities/MERGE/main_compare_sph_rst.f90 File Reference
main_compare_sph_rst.f90 File Reference
program compare_sph_restart
Functions/Subroutines
program compare_sph_restart
Main program for assemble field data.
Detailed Description
program compare_sph_restart
Author
H. Matsui
Date
Programmed by H. Matsui in July 2014
Definition in file main_compare_sph_rst.f90.
Function/Subroutine Documentation
compare_sph_restart()
program compare_sph_restart
Main program for assemble field data.
Definition at line 9 of file main_compare_sph_rst.f90.
References analyzer_compare_sph_rst::analyze_compare_sph_restart(), calypso_mpi::calypso_mpi_finalize(), calypso_mpi::calypso_mpi_init(), and analyzer_compare_sph_rst::init_compare_sph_restart().