CALYPSO: const_radial_4th_fdm_noequi Module Reference
const_radial_4th_fdm_noequi Module Reference
Coefficients to obtain radial derivatives by forth order finite difference method.
Functions/Subroutines
subroutine nod_r_4th_fdm_coefs_nonequi (nlayer_ICB, nri, radius_1d_rj_r, mat_fdm_4)
subroutine nod_r_4th_fdm_coef_noequi (kr, dr_p1, dr_n1, dr_p2, dr_n2, mat_fdm)
Detailed Description
Coefficients to obtain radial derivatives by forth order finite difference method.
subroutine nod_r_4th_fdm_coefs_nonequi & & (nlayer_ICB, nri, radius_1d_rj_r, mat_fdm_4)
Parameters
nri number of radial grid points
r(nri) radius
Function/Subroutine Documentation
nod_r_4th_fdm_coef_noequi()
subroutine const_radial_4th_fdm_noequi::nod_r_4th_fdm_coef_noequi (integer(kind = kint), intent(in) kr, real(kind = kreal), intent(in) dr_p1, real(kind = kreal), intent(in) dr_n1, real(kind = kreal), intent(in) dr_p2, real(kind = kreal), intent(in) dr_n2, real(kind = kreal), dimension(5,5), intent(inout) mat_fdm)
Definition at line 95 of file const_radial_4th_fdm_noequi.f90.
References cal_inverse_small_matrix::cal_inverse_nn_matrix(), m_constants::half, m_constants::ifive, m_constants::one, and m_constants::zero.
Referenced by nod_r_4th_fdm_coefs_nonequi().
nod_r_4th_fdm_coefs_nonequi()
subroutine const_radial_4th_fdm_noequi::nod_r_4th_fdm_coefs_nonequi (integer(kind = kint), intent(in) nlayer_ICB, integer(kind = kint), intent(in) nri, real(kind = kreal), dimension(nri), intent(in) radius_1d_rj_r, real(kind = kreal), dimension(5,5,nri), intent(inout) mat_fdm_4)
Definition at line 33 of file const_radial_4th_fdm_noequi.f90.
References m_constants::ione, m_constants::itwo, and nod_r_4th_fdm_coef_noequi().
Referenced by const_fdm_coefs::const_4th_fdm_coefs().