CALYPSO: reverse_sr_int Module Reference
reverse_sr_int Module Reference
Routines to construca element communication table.
Functions/Subroutines
subroutine element_num_reverse_sr (num_neib, id_neib, num_import, SR_sig, num_export, istack_export, ntot_export)
subroutine reverse_send_recv_int (num_neib, id_neib, istack_import, istack_export, inod_import, SR_sig, inod_export)
subroutine local_node_id_reverse_sr (numnod, num_neib, id_neib, istack_import, item_import, istack_export, item_export, SR_sig, item_local, inod_local)
Detailed Description
Routines to construca element communication table.
      subroutine element_num_reverse_SR                               &
     &         (num_neib, id_neib, num_import, SR_sig,                &
     &          num_export, istack_export, ntot_export)
      subroutine reverse_send_recv_int(num_neib, id_neib,             &
     &          istack_import, istack_export, inod_import,            &
     &          SR_sig, inod_export)
        type(send_recv_status), intent(inout) :: SR_sig
      subroutine local_node_id_reverse_SR(numnod, num_neib, id_neib,  &
     &         istack_import, item_import, istack_export, item_export,&
     &         SR_sig, item_local, inod_local)
        type(send_recv_status), intent(inout) :: SR_sig
Function/Subroutine Documentation
element_num_reverse_sr()
subroutine reverse_sr_int::element_num_reverse_sr (integer(kind = kint), intent(in) num_neib, integer(kind = kint), dimension(num_neib), intent(in) id_neib, integer(kind = kint), dimension(num_neib), intent(in) num_import, type(send_recv_status), intent(inout) SR_sig, integer(kind = kint), dimension(num_neib), intent(inout) num_export, integer(kind = kint), dimension(0:num_neib), intent(inout) istack_export, integer(kind = kint), intent(inout) ntot_export)
Definition at line 39 of file reverse_SR_int.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_integer, calypso_mpi::ierr_mpi, and t_solver_sr::resize_sr_flag().
Referenced by const_element_comm_table::const_comm_table_by_connenct().
local_node_id_reverse_sr()
subroutine reverse_sr_int::local_node_id_reverse_sr (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) num_neib, integer(kind = kint), dimension(num_neib), intent(in) id_neib, integer(kind = kint), dimension(0:num_neib), intent(in) istack_import, integer(kind = kint), dimension(istack_import(num_neib)), intent(in) item_import, integer(kind = kint), dimension(0:num_neib), intent(in) istack_export, integer(kind = kint), dimension(istack_export(num_neib)), intent(in) item_export, type(send_recv_status), intent(inout) SR_sig, integer(kind = kint), dimension(istack_export(num_neib)), intent(inout) item_local, integer(kind = kint), dimension(numnod), intent(inout) inod_local)
Definition at line 130 of file reverse_SR_int.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_integer, calypso_mpi::ierr_mpi, and t_solver_sr::resize_sr_flag().
Referenced by const_element_comm_table::const_comm_table_by_connenct().
reverse_send_recv_int()
subroutine reverse_sr_int::reverse_send_recv_int (integer(kind = kint), intent(in) num_neib, integer(kind = kint), dimension(num_neib), intent(in) id_neib, integer(kind = kint), dimension(0:num_neib), intent(in) istack_import, integer(kind = kint), dimension(0:num_neib), intent(in) istack_export, integer(kind = kint), dimension(istack_import(num_neib)), intent(in) inod_import, type(send_recv_status), intent(inout) SR_sig, integer(kind = kint), dimension(istack_export(num_neib)), intent(inout) inod_export)
Definition at line 83 of file reverse_SR_int.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_integer, calypso_mpi::ierr_mpi, and t_solver_sr::resize_sr_flag().
Referenced by make_element_comm_table_sr::element_data_reverse_sr().