CALYPSO: set_nodes_4_groups_viewer Module Reference
set_nodes_4_groups_viewer Module Reference
Functions/Subroutines
subroutine s_set_nodes_4_groups_viewer (nnod_4_surf, nnod_4_edge, view_mesh, domain_grps, view_ele_grps, view_sf_grps)
subroutine, private set_nod_4_domain_viewer (nnod_4_surf, nnod_4_edge, view_mesh, domain_grps)
subroutine, private set_nod_4_ele_group_viewer (nnod_4_surf, nnod_4_edge, view_mesh, domain_grps, view_ele_grps)
subroutine, private set_nod_4_surf_group_viewer (nnod_4_surf, nnod_4_edge, view_mesh, domain_grps, view_sf_grps)
subroutine, private allocate_ele_gp_nod_item_tmp (ele_nod_grp)
subroutine, private allocate_sf_gp_nod_item_tmp (sf_nod_grp)
subroutine, private deallocate_ele_gp_nod_item_tmp
subroutine, private deallocate_sf_gp_nod_item_tmp
Variables
integer(kind=kint), dimension(:), allocatable, private ele_nod_item_tmp
integer(kind=kint), dimension(:), allocatable, private surf_nod_item_tmp
Function/Subroutine Documentation
allocate_ele_gp_nod_item_tmp()
subroutine, private set_nodes_4_groups_viewer::allocate_ele_gp_nod_item_tmp (type(viewer_group_data), intent(in) ele_nod_grp) private
Definition at line 182 of file set_nodes_4_groups_viewer.f90.
References ele_nod_item_tmp.
Referenced by set_nod_4_ele_group_viewer().
allocate_sf_gp_nod_item_tmp()
subroutine, private set_nodes_4_groups_viewer::allocate_sf_gp_nod_item_tmp (type(viewer_group_data), intent(in) sf_nod_grp) private
Definition at line 194 of file set_nodes_4_groups_viewer.f90.
References surf_nod_item_tmp.
Referenced by set_nod_4_surf_group_viewer().
deallocate_ele_gp_nod_item_tmp()
subroutine, private set_nodes_4_groups_viewer::deallocate_ele_gp_nod_item_tmp private
Definition at line 206 of file set_nodes_4_groups_viewer.f90.
References ele_nod_item_tmp.
Referenced by set_nod_4_ele_group_viewer().
deallocate_sf_gp_nod_item_tmp()
subroutine, private set_nodes_4_groups_viewer::deallocate_sf_gp_nod_item_tmp private
Definition at line 214 of file set_nodes_4_groups_viewer.f90.
References surf_nod_item_tmp.
Referenced by set_nod_4_surf_group_viewer().
s_set_nodes_4_groups_viewer()
subroutine set_nodes_4_groups_viewer::s_set_nodes_4_groups_viewer (integer(kind = kint), intent(in) nnod_4_surf, integer(kind = kint), intent(in) nnod_4_edge, type(viewer_mesh_data), intent(in) view_mesh, type(viewer_surface_groups), intent(inout) domain_grps, type(viewer_surface_groups), intent(inout) view_ele_grps, type(viewer_surface_groups), intent(inout) view_sf_grps)
Definition at line 45 of file set_nodes_4_groups_viewer.f90.
References t_viewer_group::alloc_merged_group_item(), const_node_list_4_viewer::allocate_imark_node_4_list(), const_node_list_4_viewer::deallocate_imark_node_4_list(), m_machine_parameter::iflag_debug, set_nod_4_domain_viewer(), set_nod_4_ele_group_viewer(), and set_nod_4_surf_group_viewer().
Referenced by const_kemoview_mesh::const_surf_mesh_4_viewer().
set_nod_4_domain_viewer()
subroutine, private set_nodes_4_groups_viewer::set_nod_4_domain_viewer (integer(kind = kint), intent(in) nnod_4_surf, integer(kind = kint), intent(in) nnod_4_edge, type(viewer_mesh_data), intent(in) view_mesh, type(viewer_surface_groups), intent(inout) domain_grps) private
Definition at line 83 of file set_nodes_4_groups_viewer.f90.
References t_viewer_group::alloc_merged_group_item(), const_node_list_4_viewer::const_nod_4_ele_gp_viewer(), const_node_list_4_viewer::count_nod_stack_4_ele_gp_viewer(), m_constants::ione, and const_node_list_4_viewer::mark_node_4_domain_viewer().
Referenced by s_set_nodes_4_groups_viewer().
set_nod_4_ele_group_viewer()
subroutine, private set_nodes_4_groups_viewer::set_nod_4_ele_group_viewer (integer(kind = kint), intent(in) nnod_4_surf, integer(kind = kint), intent(in) nnod_4_edge, type(viewer_mesh_data), intent(in) view_mesh, type(viewer_surface_groups), intent(in) domain_grps, type(viewer_surface_groups), intent(inout) view_ele_grps) private
Definition at line 105 of file set_nodes_4_groups_viewer.f90.
References t_viewer_group::alloc_merged_group_item(), allocate_ele_gp_nod_item_tmp(), const_node_list_4_viewer::const_nod_4_ele_gp_viewer(), const_node_list_4_viewer::count_nod_stack_4_ele_gp_viewer(), t_viewer_group::dealloc_merged_group_item(), deallocate_ele_gp_nod_item_tmp(), ele_nod_item_tmp, and const_node_list_4_viewer::mark_node_4_ele_grp_viewer().
Referenced by s_set_nodes_4_groups_viewer().
set_nod_4_surf_group_viewer()
subroutine, private set_nodes_4_groups_viewer::set_nod_4_surf_group_viewer (integer(kind = kint), intent(in) nnod_4_surf, integer(kind = kint), intent(in) nnod_4_edge, type(viewer_mesh_data), intent(in) view_mesh, type(viewer_surface_groups), intent(in) domain_grps, type(viewer_surface_groups), intent(inout) view_sf_grps) private
Definition at line 143 of file set_nodes_4_groups_viewer.f90.
References t_viewer_group::alloc_merged_group_item(), allocate_sf_gp_nod_item_tmp(), const_node_list_4_viewer::const_nod_4_ele_gp_viewer(), const_node_list_4_viewer::count_nod_stack_4_ele_gp_viewer(), t_viewer_group::dealloc_merged_group_item(), deallocate_sf_gp_nod_item_tmp(), const_node_list_4_viewer::mark_node_4_surf_grp_viewer(), and surf_nod_item_tmp.
Referenced by s_set_nodes_4_groups_viewer().
Variable Documentation
ele_nod_item_tmp
integer(kind = kint), dimension(:), allocatable, private set_nodes_4_groups_viewer::ele_nod_item_tmp private
Definition at line 25 of file set_nodes_4_groups_viewer.f90.
Referenced by allocate_ele_gp_nod_item_tmp(), deallocate_ele_gp_nod_item_tmp(), and set_nod_4_ele_group_viewer().
surf_nod_item_tmp
integer(kind = kint), dimension(:), allocatable, private set_nodes_4_groups_viewer::surf_nod_item_tmp private
Definition at line 26 of file set_nodes_4_groups_viewer.f90.
Referenced by allocate_sf_gp_nod_item_tmp(), deallocate_sf_gp_nod_item_tmp(), and set_nod_4_surf_group_viewer().