CALYPSO: find_node_4_group Module Reference
find_node_4_group Module Reference
Functions/Subroutines
subroutine allocate_work_next_node (np_smp, numnod)
subroutine deallocate_work_next_node
subroutine count_nod_4_grp_smp (np_smp, numnod, numele, nnod_4_ele, ie, i_smp_stack, num_grp, ntot_grp, istack_grp, iele_grp, nnod_grp)
subroutine set_nod_4_grp_smp (np_smp, numnod, numele, nnod_4_ele, ie, i_smp_stack, num_grp, ntot_grp, istack_grp, iele_grp, ntot_nod_grp, inod_stack_grp, nnod_grp, inod_grp, iweight_grp)
subroutine move_myself_2_first_smp (np_smp, numnod, ntot_next, inod_smp_stack, inod_next_stack, inod_next, iweight_next)
subroutine sort_next_node_list_by_weight (np_smp, numnod, ntot_next, inod_smp_stack, inod_next_stack, inod_next, iweight_next)
Variables
integer(kind=kint), dimension(:,:), allocatable, private imark_4_node
Function/Subroutine Documentation
allocate_work_next_node()
subroutine find_node_4_group::allocate_work_next_node (integer(kind = kint), intent(in) np_smp, integer(kind = kint), intent(in) numnod)
Definition at line 45 of file find_node_4_group.f90.
References imark_4_node.
Referenced by set_ele_id_4_node_type::const_next_nod_id_4_node().
count_nod_4_grp_smp()
subroutine find_node_4_group::count_nod_4_grp_smp (integer(kind = kint), intent(in) np_smp, integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) nnod_4_ele, integer(kind = kint), dimension(numele,nnod_4_ele), intent(in) ie, integer(kind = kint), dimension(0:np_smp), intent(in) i_smp_stack, integer(kind = kint), intent(in) num_grp, integer(kind = kint), intent(in) ntot_grp, integer(kind = kint), dimension(0:num_grp), intent(in) istack_grp, integer(kind = kint), dimension(ntot_grp), intent(in) iele_grp, integer(kind = kint), dimension(num_grp), intent(inout) nnod_grp)
Definition at line 64 of file find_node_4_group.f90.
References imark_4_node.
Referenced by set_ele_id_4_node_type::const_next_nod_id_4_node().
deallocate_work_next_node()
subroutine find_node_4_group::deallocate_work_next_node
Definition at line 56 of file find_node_4_group.f90.
References imark_4_node.
Referenced by set_ele_id_4_node_type::const_next_nod_id_4_node().
move_myself_2_first_smp()
subroutine find_node_4_group::move_myself_2_first_smp (integer (kind=kint), intent(in) np_smp, integer (kind=kint), intent(in) numnod, integer (kind=kint), intent(in) ntot_next, integer (kind=kint), dimension(0:np_smp), intent(in) inod_smp_stack, integer (kind=kint), dimension(0:numnod), intent(in) inod_next_stack, integer (kind=kint), dimension(ntot_next), intent(inout) inod_next, integer (kind=kint), dimension(ntot_next), intent(inout) iweight_next)
Definition at line 182 of file find_node_4_group.f90.
Referenced by set_ele_id_4_node_type::const_next_nod_id_4_node().
set_nod_4_grp_smp()
subroutine find_node_4_group::set_nod_4_grp_smp (integer(kind = kint), intent(in) np_smp, integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) nnod_4_ele, integer(kind = kint), dimension(numele,nnod_4_ele), intent(in) ie, integer(kind = kint), dimension(0:np_smp), intent(in) i_smp_stack, integer(kind = kint), intent(in) num_grp, integer(kind = kint), intent(in) ntot_grp, integer(kind = kint), dimension(0:num_grp), intent(in) istack_grp, integer(kind = kint), dimension(ntot_grp), intent(in) iele_grp, integer(kind = kint), intent(in) ntot_nod_grp, integer(kind = kint), dimension(0:num_grp), intent(in) inod_stack_grp, integer(kind = kint), dimension(num_grp), intent(inout) nnod_grp, integer(kind = kint), dimension(ntot_nod_grp), intent(inout) inod_grp, integer(kind = kint), dimension(ntot_nod_grp), intent(inout) iweight_grp)
Definition at line 115 of file find_node_4_group.f90.
References imark_4_node.
Referenced by set_ele_id_4_node_type::const_next_nod_id_4_node().
sort_next_node_list_by_weight()
subroutine find_node_4_group::sort_next_node_list_by_weight (integer (kind=kint), intent(in) np_smp, integer (kind=kint), intent(in) numnod, integer (kind=kint), intent(in) ntot_next, integer (kind=kint), dimension(0:np_smp), intent(in) inod_smp_stack, integer (kind=kint), dimension(0:numnod), intent(in) inod_next_stack, integer (kind=kint), dimension(ntot_next), intent(inout) inod_next, integer (kind=kint), dimension(ntot_next), intent(inout) iweight_next)
Definition at line 229 of file find_node_4_group.f90.
References m_constants::ione, and quicksort::quicksort_w_index().
Referenced by set_ele_id_4_node_type::const_next_nod_id_4_node().
Variable Documentation
imark_4_node
integer (kind=kint), dimension(:,:), allocatable, private find_node_4_group::imark_4_node private
Definition at line 35 of file find_node_4_group.f90.
Referenced by allocate_work_next_node(), count_nod_4_grp_smp(), deallocate_work_next_node(), and set_nod_4_grp_smp().