CALYPSO: skip_comment_f Module Reference
skip_comment_f Module Reference
subroutines to find comment lines in data
Functions/Subroutines
subroutine skip_comment (character_4_read, id_file)
subroutine count_field_by_comma (id_file, charabuf, ncomp, field_name)
subroutine read_stack_array (character_4_read, id_file, num, istack_array)
subroutine change_2_upper_case (string)
subroutine change_2_lower_case (string)
character(len=kchara) function fill_from_null (input)
logical function cmp_no_case (cmp_chara, ref_chara)
real(kind=kreal) function compare_data (data, ref)
logical function yes_flag (control)
logical function no_flag (control)
integer(kind=kint) function iflag_divide (charaname)
integer(kind=kint) function max_len_of_charaarray (num, carray)
subroutine write_ctl_chara_cont (id_file, charaname)
subroutine write_ctl_chara_lf (id_file, charaname)
subroutine write_spaces (id_file, nspace)
subroutine write_space_4_parse (id_file, level)
Detailed Description
subroutines to find comment lines in data
      subroutine skip_comment(character_4_read,id_file)
      subroutine count_field_by_comma(id_file, charabuf,              &
     &          ncomp, field_name)
      subroutine read_stack_array(character_4_read, id_file, num,     &
     &          istack_array)
      subroutine change_2_upper_case(string)
      subroutine change_2_lower_case(string)
      character(len=kchara) function fill_from_null(input)
      real(kind = kreal) function compare_data(data, ref)
        real(kind = kreal), intent(in) :: data, ref
           Compare two reals
              if ref = 0.0 then compare_data = data
              else compare_data = abs((data - ref) / ref)
      logical function cmp_no_case(cmp_chara, ref_chara)
          if ref_chara and cmp_chara are same ignoreing case,
          returns 1, othewwise returns 0
      logical function yes_flag(control)
      logical function no_flag(control)
      integer(kind = kint) function iflag_divide(charaname)
      integer(kind = kint) function max_len_of_charaarray(num, carray)
      subroutine write_ctl_chara_cont(id_file, charaname)
      subroutine write_ctl_chara_lf(id_file, charaname)
      subroutine write_spaces(id_file, nspace)
      subroutine write_space_4_parse(id_file, level)
Function/Subroutine Documentation
change_2_lower_case()
subroutine skip_comment_f::change_2_lower_case (character(len=kchara), intent(inout) string)
Definition at line 165 of file skip_comment_f.f90.
Referenced by cmp_no_case().
change_2_upper_case()
subroutine skip_comment_f::change_2_upper_case (character(len=kchara), intent(inout) string)
Definition at line 148 of file skip_comment_f.f90.
Referenced by init_sphrical_transform_mhd::sel_sph_transform_mhd().
cmp_no_case()
logical function skip_comment_f::cmp_no_case (character(len=kchara), intent(in) cmp_chara, character(len=*), intent(in) ref_chara)
Definition at line 205 of file skip_comment_f.f90.
References change_2_lower_case().
Referenced by t_read_control_elements::check_array_flag(), t_read_control_elements::check_begin_flag(), t_read_control_elements::check_end_array_flag(), t_read_control_elements::check_end_flag(), t_read_control_elements::check_file_flag(), set_nodal_field_name::check_monitor_control_flag(), t_multi_flag_labels::check_mul_flags(), set_nodal_field_name::check_vis_control_flag(), t_field_labels::cmp_field_no_case(), construct_mhd_coefficient::construct_coefficient(), t_control_params_4_iso::count_control_4_field_on_iso(), m_file_format_labels::cvt_default_field_format_flag(), set_sph_boundary_from_file::find_bc_label(), set_control_sph_subdomains::full_subdomains_4_sph_shell(), ucd_data_to_buffer::nnod_ele_by_ucd_eletype(), no_flag(), set_sph_boundary_from_file::num_comp_bc_data(), gz_udt_to_vtk_data_io::read_gz_udt_field_from_vtk(), udt_to_vtk_data_io::read_udt_field_from_vtk(), set_control_4_velo::s_set_control_4_velo(), m_section_file_extensions::section_format_id_from_ext(), set_node_group_types::set_bc_group_types_fluxes(), set_node_group_types::set_bc_group_types_rotation(), set_node_group_types::set_bc_group_types_scalar(), set_node_group_types::set_bc_group_types_sgs_scalar(), set_node_group_types::set_bc_group_types_sgs_vect(), set_node_group_types::set_bc_group_types_sph_center(), set_node_group_types::set_bc_group_types_sph_magne(), set_node_group_types::set_bc_group_types_sph_velo(), set_node_group_types::set_bc_group_types_vector(), set_control_4_force::set_control_4_coriolis_force(), set_control_4_force::set_control_4_gravity(), set_control_4_force::set_control_4_induction(), set_control_4_force::set_control_force_flags(), t_ctl_params_gen_sph_shell::set_ctl_radius_4_shell(), m_section_coef_flags::set_each_param_2_vector(), set_sph_bc_data_by_file::set_evolved_grad_bc_by_file(), set_sph_bc_data_by_file::set_evolved_scalar_bc_by_file(), set_sph_bc_data_by_file::set_evolved_vector_bc_by_file(), set_controls_4_sph_shell::set_fem_mesh_mode_4_sph(), m_fft_selector::set_fft_library_ctl(), set_sph_bc_data_by_file::set_fixed_grad_bc_by_file(), set_sph_bc_data_by_file::set_fixed_scalar_bc_by_file(), set_sph_bc_data_by_file::set_fixed_vector_bc_by_file(), t_work_4_sph_trans::set_import_table_ctl(), m_initial_field_control::set_initial_field_id(), set_control_sph_subdomains::set_inner_loop_4_sph_shell(), m_legendre_transform_list::set_legendre_trans_mode_ctl(), m_file_format_switch::set_parallel_file_format(), set_surface_group_types::set_pseudo_vacuum_group_types(), set_radius_4_sph_dynamo::set_radius_dat_4_sph_dynamo(), r_interpolate_marged_sph::set_sph_boundary_4_merge(), set_surface_group_types::set_stress_free_group_types(), set_control_sph_subdomains::set_subdomains_4_sph_shell(), set_surface_group_types::set_surf_group_types_scalar(), set_surface_group_types::set_surf_group_types_vector(), set_surface_group_types::set_surf_infty_group_types(), set_surface_group_types::set_surf_wall_group_types(), set_control_platform_data::turn_off_debug_flag_by_ctl(), and yes_flag().
compare_data()
real(kind = kreal) function skip_comment_f::compare_data (real(kind = kreal), intent(in) data, real(kind = kreal), intent(in) ref)
Definition at line 232 of file skip_comment_f.f90.
count_field_by_comma()
subroutine skip_comment_f::count_field_by_comma (integer (kind=kint), intent(in) id_file, character(len=lengthbuf), intent(inout) charabuf, integer (kind=kint), intent(inout) ncomp, character(len=kchara), dimension(255), intent(inout) field_name)
Definition at line 68 of file skip_comment_f.f90.
fill_from_null()
character(len=kchara) function skip_comment_f::fill_from_null (character(len=*), intent(in) input)
Definition at line 182 of file skip_comment_f.f90.
iflag_divide()
integer(kind = kint) function skip_comment_f::iflag_divide (character(len=kchara), intent(in) charaname)
Definition at line 282 of file skip_comment_f.f90.
Referenced by max_len_of_charaarray(), write_control_elements::write_character2_ctl_item(), write_control_elements::write_character3_ctl_item(), write_ctl_chara_cont(), and write_ctl_chara_lf().
max_len_of_charaarray()
integer(kind = kint) function skip_comment_f::max_len_of_charaarray (integer(kind = kint), intent(in) num, character(len = kchara), dimension(num), intent(in) carray)
Definition at line 301 of file skip_comment_f.f90.
References iflag_divide().
Referenced by t_control_array_character2::write_character2_ctl_type(), t_control_array_character2::write_control_array_c2(), and t_control_array_character3::write_control_array_c3().
no_flag()
logical function skip_comment_f::no_flag (character(len=kchara), intent(in) control)
Definition at line 264 of file skip_comment_f.f90.
References cmp_no_case().
Referenced by set_control_4_pickup_sph::set_ctl_params_layered_spectr(), and set_control_platform_data::turn_off_debug_flag_by_ctl().
read_stack_array()
subroutine skip_comment_f::read_stack_array (character(len=255) character_4_read, integer (kind=kint), intent(in) id_file, integer (kind=kint), intent(in) num, integer (kind=kint), dimension(0:num), intent(inout) istack_array)
Definition at line 107 of file skip_comment_f.f90.
References skip_comment().
skip_comment()
subroutine skip_comment_f::skip_comment (character(len=255), intent(inout) character_4_read, integer (kind=kint), intent(in) id_file)
Definition at line 52 of file skip_comment_f.f90.
Referenced by mpi_sph_gauss_coefs_io::check_gauss_coefs_4_monitor(), sph_mean_spectr_header_io::check_sph_vol_mean_sq_header(), t_read_control_elements::load_one_line_from_control(), t_no_heat_nusselt::open_read_no_heat_source_nu(), t_picked_sph_spectr_data_io::open_sph_spec_read(), ucd_field_file_io::read_alloc_ucd_2_fld_file(), field_file_io::read_and_alloc_step_field(), field_file_io::read_and_allocate_field_file(), field_file_io::read_and_allocate_step_head(), field_data_io::read_arrays_for_stacks(), t_sph_boundary_input_data::read_boundary_spectr_file(), domain_data_io::read_domain_info(), t_each_sph_boundary_io_data::read_each_boundary_spectr(), field_data_io::read_field_data(), field_data_io::read_field_name(), t_global_gauss_coefs::read_gauss_global_coefs(), spherical_model_io::read_gl_nodes_sph(), spherical_model_io::read_gl_resolution_sph(), groups_io::read_group_data(), group_data_io::read_group_item(), element_connect_io::read_number_of_element(), node_geometry_io::read_number_of_node(), spherical_model_io::read_rank_4_sph(), sph_global_1d_idx_io::read_rj_gl_1d_table(), rst_data_io_by_fld::read_rst_data_comps(), rst_data_io_by_fld::read_rst_field_comps(), rst_data_io_by_fld::read_rst_file(), sph_global_1d_idx_io::read_rtp_gl_1d_table(), comm_table_io::read_send_recv_item(), comm_table_io::read_send_recv_work(), simple_sph_spectr_head_io::read_sph_pwr_layer_head(), simple_sph_spectr_head_io::read_sph_pwr_vol_head(), read_stack_array(), time_data_io::read_step_data(), field_file_io::read_step_field_file(), groups_io::read_surf_grp_data(), group_data_io::read_surface_group_item(), ucd_field_file_io::read_ucd_2_fld_file(), and vtk_data_io::read_vtk_fields_head().
write_ctl_chara_cont()
subroutine skip_comment_f::write_ctl_chara_cont (integer(kind = kint), intent(in) id_file, character(len=kchara), intent(in) charaname)
Definition at line 319 of file skip_comment_f.f90.
References iflag_divide().
Referenced by write_control_elements::write_array_flag_for_ctl(), write_control_elements::write_begin_flag_for_ctl(), write_control_elements::write_chara2_real_ctl_item(), write_control_elements::write_chara_int3_ctl_item(), write_control_elements::write_chara_int_ctl_item(), write_control_elements::write_chara_real2_ctl_item(), write_control_elements::write_chara_real_ctl_item(), write_control_elements::write_character2_ctl_item(), write_control_elements::write_character3_ctl_item(), write_control_elements::write_character_ctl_item(), write_control_elements::write_end_array_flag_for_ctl(), write_control_elements::write_end_flag_for_ctl(), write_control_elements::write_i2_r2_ctl_item(), write_control_elements::write_i2_r_ctl_item(), write_control_elements::write_i_c_r_ctl_item(), write_control_elements::write_integer_ctl_item(), and write_control_elements::write_real_ctl_item().
write_ctl_chara_lf()
subroutine skip_comment_f::write_ctl_chara_lf (integer(kind = kint), intent(in) id_file, character(len=kchara), intent(in) charaname)
Definition at line 336 of file skip_comment_f.f90.
References iflag_divide().
Referenced by write_control_elements::write_character2_ctl_item(), write_control_elements::write_character3_ctl_item(), write_control_elements::write_character_ctl_item(), write_control_elements::write_end_array_flag_for_ctl(), and write_control_elements::write_end_flag_for_ctl().
write_space_4_parse()
subroutine skip_comment_f::write_space_4_parse (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level)
Definition at line 366 of file skip_comment_f.f90.
References write_spaces().
Referenced by write_control_elements::write_array_flag_for_ctl(), write_control_elements::write_begin_flag_for_ctl(), write_control_elements::write_chara2_real_ctl_item(), write_control_elements::write_chara_int3_ctl_item(), write_control_elements::write_chara_int_ctl_item(), write_control_elements::write_chara_real2_ctl_item(), write_control_elements::write_chara_real_ctl_item(), write_control_elements::write_character2_ctl_item(), write_control_elements::write_character3_ctl_item(), write_control_elements::write_character_ctl_item(), write_control_elements::write_end_array_flag_for_ctl(), write_control_elements::write_end_flag_for_ctl(), write_control_elements::write_file_name_for_ctl_line(), write_control_elements::write_i2_r2_ctl_item(), write_control_elements::write_i2_r_ctl_item(), write_control_elements::write_i_c_r_ctl_item(), write_control_elements::write_int_real_ctl_item(), write_control_elements::write_integer2_ctl_item(), write_control_elements::write_integer3_ctl_item(), write_control_elements::write_integer_ctl_item(), write_control_elements::write_real2_ctl_item(), write_control_elements::write_real3_ctl_item(), and write_control_elements::write_real_ctl_item().
write_spaces()
subroutine skip_comment_f::write_spaces (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) nspace)
Definition at line 352 of file skip_comment_f.f90.
Referenced by write_control_elements::write_character2_ctl_item(), write_control_elements::write_character3_ctl_item(), write_control_elements::write_character_ctl_item(), write_control_elements::write_integer_ctl_item(), write_control_elements::write_real_ctl_item(), and write_space_4_parse().
yes_flag()
logical function skip_comment_f::yes_flag (character(len=kchara), intent(in) control)
Definition at line 247 of file skip_comment_f.f90.
References cmp_no_case().
Referenced by t_mhd_step_parameter::s_set_control_4_time_steps(), set_control_4_force::set_control_4_coriolis_force(), set_control_4_force::set_control_4_induction(), t_control_param_assemble::set_delete_flag_4_assemble(), set_control_platform_data::set_fem_mesh_switch_4_sph(), set_control_platform_data::set_fem_surface_output_flag(), set_control_platform_data::set_fem_viewer_output_flag(), t_physical_property::set_filtered_advection_ctl(), t_physical_property::set_filtered_induction_ctl(), and set_control_platform_data::turn_off_debug_flag_by_ctl().