CALYPSO: add_comm_table_in_node_grp Module Reference
add_comm_table_in_node_grp Module Reference
Update group data for sleeve extender.
Functions/Subroutines
subroutine add_comm_tbl_in_node_grp_mesh (num_pe, mesh, group)
subroutine add_comm_table_in_node_group (num_pe, new_comm, old_nod_grp, new_nod_grp)
Detailed Description
Update group data for sleeve extender.
      subroutine add_comm_tbl_in_node_grp_mesh(num_pe, mesh, group)
        type(mesh_geometry), intent(inout) :: mesh
        type(mesh_groups), intent(inout) ::   group
      subroutine add_comm_table_in_node_group                         &
     &         (num_pe, new_comm, old_nod_grp, new_nod_grp)
        type(communication_table), intent(in) :: new_comm
        type(group_data), intent(in) :: old_nod_grp
        type(group_data), intent(inout) :: new_nod_grp
Function/Subroutine Documentation
add_comm_table_in_node_group()
subroutine add_comm_table_in_node_grp::add_comm_table_in_node_group (integer, intent(in) num_pe, type(communication_table), intent(in) new_comm, type(group_data), intent(in) old_nod_grp, type(group_data), intent(inout) new_nod_grp)
Definition at line 62 of file add_comm_table_in_node_grp.f90.
References set_parallel_file_name::add_process_id(), t_group_data::alloc_group_item(), and t_group_data::alloc_group_num().
Referenced by add_comm_tbl_in_node_grp_mesh().
add_comm_tbl_in_node_grp_mesh()
subroutine add_comm_table_in_node_grp::add_comm_tbl_in_node_grp_mesh (integer, intent(in) num_pe, type(mesh_geometry), intent(inout) mesh, type(mesh_groups), intent(inout) group)
Definition at line 39 of file add_comm_table_in_node_grp.f90.
References add_comm_table_in_node_group(), copy_mesh_structures::copy_group_data(), and t_group_data::dealloc_group().
Referenced by para_const_kemoview_mesh::pickup_surface_mesh().