CALYPSO: m_fft_selector Module Reference
m_fft_selector Module Reference
Selector of Fourier transform.
Functions/Subroutines
integer(kind=kint) function set_fft_library_ctl (FFT_library_ctl)
subroutine write_elapsed_4_fft (i_mode, etime_fft)
character(len=kchara) function chosen_fft_name (i_mode)
Variables
character(len=kchara), parameter, private hd_fftpack = 'FFTPACK'
Character flag to use FFTPACK5.
character(len=kchara), parameter, private hd_fftpack_s = 'FFTPACK_SINGLE'
Character flag to use FFTPACK5.
character(len=kchara), parameter, private hd_fftpack_c = 'FFTPACK_COMPONENT'
Character flag to use FFTPACK5.
character(len=kchara), parameter, private hd_fftpack_d = 'FFTPACK_DOMAIN'
Character flag to use FFTPACK5.
character(len=kchara), parameter, private hd_fftw = 'FFTW'
Character flag to use FFTW3.
character(len=kchara), parameter, private hd_fftw3 = 'fftw3'
Character flag to use FFTW3.
character(len=kchara), parameter, private hd_fftw_d = 'FFTW_DOMAIN'
Character flag to use FFTW3 for each component.
character(len=kchara), parameter, private hd_fftw3_d = 'fftw3_domain'
Character flag to use FFTW3 for each component.
character(len=kchara), parameter, private hd_fftw_s = 'FFTW_SINGLE'
Character flag to use single transforms in FFTW3.
character(len=kchara), parameter, private hd_fftw3_s = 'fftw3_single'
Character flag to use single transforms in FFTW3.
character(len=kchara), parameter, private hd_fftw_c = 'FFTW_COMPONENT'
Character flag to use FFTW3 for all components.
character(len=kchara), parameter, private hd_fftw3_c = 'fftw3_component'
Character flag to use FFTW3 for all components.
character(len=kchara), parameter, private hd_omp_fftw = 'OMP_FFTW'
Character flag to use FFTW3 for each component.
character(len=kchara), parameter, private hd_omp_fftw3 = 'omp_fftw3'
Character flag to use FFTW3 for each component.
character(len=kchara), parameter, private hd_omp_fftw_d = 'OMP_FFTW_DOMAIN'
Character flag to use FFTW3 for each component.
character(len=kchara), parameter, private hd_omp_fftw3_d = 'omp_fftw3_domain'
Character flag to use FFTW3 for each component.
character(len=kchara), parameter, private hd_ispack = 'ISPACK'
Character flag to use ISPACK.
character(len=kchara), parameter, private hd_ispack_d = 'ISPACK_DOMAIN'
Character flag to use ISPACK for domain.
character(len=kchara), parameter, private hd_ispack3 = 'ISPACK3'
Character flag to use ISPACK.
character(len=kchara), parameter, private hd_ispack3_d = 'ISPACK3_DOMAIN'
Character flag to use ISPACK for domain.
character(len=kchara), parameter, private hd_ispack3_c = 'ISPACK3_COMPONENT'
Character flag to use ISPACK for component.
character(len=kchara), parameter, private hd_ispack3_s = 'ISPACK3_SINGLE'
Character flag to use ISPACK for component.
character(len=kchara), parameter, private hd_fft_test = 'TEST'
Character flag to use test FFT.
integer(kind=kint), parameter iflag_undefined_fft = 0
integer flag for undefined
integer(kind=kint), parameter iflag_fftpack = 1
integer flag to use FFTPACK5
integer(kind=kint), parameter iflag_fftpack_single = 2
integer flag to use FFTPACK5
integer(kind=kint), parameter iflag_fftpack_component = 3
integer flag to use FFTPACK5
integer(kind=kint), parameter iflag_fftpack_domain = 4
integer flag to use FFTPACK5
integer(kind=kint), parameter iflag_fftw = 11
integer flag to use FFTW3
integer(kind=kint), parameter iflag_fftw_single = 12
integer flag to use single transforms in FFTW3
integer(kind=kint), parameter iflag_fftw_component = 13
integer flag to use single transforms in FFTW3
integer(kind=kint), parameter iflag_fftw_domain = 14
integer flag to use FFTW3 for each component
integer(kind=kint), parameter iflag_omp_fftw = 41
integer flag to use FFTW3 with OopenMP at once
integer(kind=kint), parameter iflag_omp_fftw_domain = 42
integer flag to use FFTW3 with OopenMP for domain
integer(kind=kint), parameter iflag_ispack1 = 21
integer flag to use ISPACK Ver.0.93
integer(kind=kint), parameter iflag_ispack1_domain = 22
integer flag to use ISPACK Ver.0.93 for domain
integer(kind=kint), parameter iflag_ispack3 = 31
integer flag to use ISPACK Ver. 3.01
integer(kind=kint), parameter iflag_ispack3_domain = 32
integer flag to use ISPACK Ver. 3.01 for domain
integer(kind=kint), parameter iflag_ispack3_component = 33
integer flag to use ISPACK Ver. 3.01 for domain
integer(kind=kint), parameter iflag_ispack3_single = 34
integer flag to use ISPACK Ver. 3.01 for domain
integer(kind=kint), parameter iflag_fft_test = 99
integer flag to use test FFT
Detailed Description
Selector of Fourier transform.
      integer(kind = kint) function                                   &
     &                    set_fft_library_ctl(FFT_library_ctl)
      subroutine write_elapsed_4_FFT(i_mode, etime_fft)
      character(len = kchara) function chosen_fft_name(i_mode)
Function/Subroutine Documentation
chosen_fft_name()
character(len = kchara) function m_fft_selector::chosen_fft_name (integer(kind = kint), intent(in) i_mode)
Definition at line 267 of file m_FFT_selector.f90.
References hd_fft_test, hd_fftpack, hd_fftpack_c, hd_fftpack_d, hd_fftpack_s, hd_fftw, hd_fftw_c, hd_fftw_d, hd_fftw_s, hd_ispack, hd_ispack3, hd_ispack3_c, hd_ispack3_d, hd_ispack3_s, hd_ispack_d, hd_omp_fftw, hd_omp_fftw_d, iflag_fft_test, iflag_fftpack, iflag_fftpack_component, iflag_fftpack_domain, iflag_fftpack_single, iflag_fftw, iflag_fftw_component, iflag_fftw_domain, iflag_fftw_single, iflag_ispack1, iflag_ispack1_domain, iflag_ispack3, iflag_ispack3_component, iflag_ispack3_domain, iflag_ispack3_single, iflag_omp_fftw, and iflag_omp_fftw_domain.
Referenced by init_fft_4_mhd::init_fourier_transform_4_mhd(), init_fft_4_sph::init_fourier_transform_4_sph(), and write_elapsed_4_fft().
set_fft_library_ctl()
integer(kind = kint) function m_fft_selector::set_fft_library_ctl (character(len = kchara), intent(in) FFT_library_ctl)
Definition at line 142 of file m_FFT_selector.f90.
References skip_comment_f::cmp_no_case(), hd_fft_test, hd_fftpack_c, hd_fftpack_d, hd_fftpack_s, hd_fftw, hd_fftw3, hd_fftw3_c, hd_fftw3_d, hd_fftw3_s, hd_fftw_c, hd_fftw_d, hd_fftw_s, hd_ispack, hd_ispack3, hd_ispack3_c, hd_ispack3_d, hd_ispack3_s, hd_ispack_d, hd_omp_fftw, hd_omp_fftw3, hd_omp_fftw3_d, hd_omp_fftw_d, iflag_fft_test, iflag_fftpack, iflag_fftpack_component, iflag_fftpack_domain, iflag_fftpack_single, iflag_fftw, iflag_fftw_component, iflag_fftw_domain, iflag_fftw_single, iflag_ispack1, iflag_ispack1_domain, iflag_ispack3, iflag_ispack3_component, iflag_ispack3_domain, iflag_ispack3_single, iflag_omp_fftw, and iflag_omp_fftw_domain.
Referenced by set_control_sph_data_mhd::s_set_control_sph_data_mhd().
write_elapsed_4_fft()
subroutine m_fft_selector::write_elapsed_4_fft (integer(kind = kint), intent(in) i_mode, real(kind = kreal), intent(in) etime_fft)
Definition at line 204 of file m_FFT_selector.f90.
References chosen_fft_name(), iflag_fftpack, iflag_fftpack_component, iflag_fftpack_domain, iflag_fftpack_single, iflag_fftw, iflag_fftw_component, iflag_fftw_domain, iflag_fftw_single, iflag_ispack1, iflag_ispack1_domain, iflag_ispack3, iflag_ispack3_component, iflag_ispack3_domain, iflag_ispack3_single, iflag_omp_fftw, and iflag_omp_fftw_domain.
Referenced by init_fft_4_sph::s_select_fourier_transform().
Variable Documentation
hd_fft_test
character(len = kchara), parameter, private m_fft_selector::hd_fft_test = 'TEST' private
Character flag to use test FFT.
Definition at line 83 of file m_FFT_selector.f90.
Referenced by chosen_fft_name(), and set_fft_library_ctl().
hd_fftpack
character(len = kchara), parameter, private m_fft_selector::hd_fftpack = 'FFTPACK' private
Character flag to use FFTPACK5.
Definition at line 23 of file m_FFT_selector.f90.
Referenced by chosen_fft_name().
hd_fftpack_c
character(len = kchara), parameter, private m_fft_selector::hd_fftpack_c = 'FFTPACK_COMPONENT' private
Character flag to use FFTPACK5.
Definition at line 28 of file m_FFT_selector.f90.
Referenced by chosen_fft_name(), and set_fft_library_ctl().
hd_fftpack_d
character(len = kchara), parameter, private m_fft_selector::hd_fftpack_d = 'FFTPACK_DOMAIN' private
Character flag to use FFTPACK5.
Definition at line 31 of file m_FFT_selector.f90.
Referenced by chosen_fft_name(), and set_fft_library_ctl().
hd_fftpack_s
character(len = kchara), parameter, private m_fft_selector::hd_fftpack_s = 'FFTPACK_SINGLE' private
Character flag to use FFTPACK5.
Definition at line 25 of file m_FFT_selector.f90.
Referenced by chosen_fft_name(), and set_fft_library_ctl().
hd_fftw
character(len = kchara), parameter, private m_fft_selector::hd_fftw = 'FFTW' private
Character flag to use FFTW3.
Definition at line 35 of file m_FFT_selector.f90.
Referenced by chosen_fft_name(), and set_fft_library_ctl().
hd_fftw3
character(len = kchara), parameter, private m_fft_selector::hd_fftw3 = 'fftw3' private
Character flag to use FFTW3.
Definition at line 37 of file m_FFT_selector.f90.
Referenced by set_fft_library_ctl().
hd_fftw3_c
character(len = kchara), parameter, private m_fft_selector::hd_fftw3_c = 'fftw3_component' private
Character flag to use FFTW3 for all components.
Definition at line 50 of file m_FFT_selector.f90.
Referenced by set_fft_library_ctl().
hd_fftw3_d
character(len = kchara), parameter, private m_fft_selector::hd_fftw3_d = 'fftw3_domain' private
Character flag to use FFTW3 for each component.
Definition at line 41 of file m_FFT_selector.f90.
Referenced by set_fft_library_ctl().
hd_fftw3_s
character(len = kchara), parameter, private m_fft_selector::hd_fftw3_s = 'fftw3_single' private
Character flag to use single transforms in FFTW3.
Definition at line 45 of file m_FFT_selector.f90.
Referenced by set_fft_library_ctl().
hd_fftw_c
character(len = kchara), parameter, private m_fft_selector::hd_fftw_c = 'FFTW_COMPONENT' private
Character flag to use FFTW3 for all components.
Definition at line 47 of file m_FFT_selector.f90.
Referenced by chosen_fft_name(), and set_fft_library_ctl().
hd_fftw_d
character(len = kchara), parameter, private m_fft_selector::hd_fftw_d = 'FFTW_DOMAIN' private
Character flag to use FFTW3 for each component.
Definition at line 39 of file m_FFT_selector.f90.
Referenced by chosen_fft_name(), and set_fft_library_ctl().
hd_fftw_s
character(len = kchara), parameter, private m_fft_selector::hd_fftw_s = 'FFTW_SINGLE' private
Character flag to use single transforms in FFTW3.
Definition at line 43 of file m_FFT_selector.f90.
Referenced by chosen_fft_name(), and set_fft_library_ctl().
hd_ispack
character(len = kchara), parameter, private m_fft_selector::hd_ispack = 'ISPACK' private
Character flag to use ISPACK.
Definition at line 65 of file m_FFT_selector.f90.
Referenced by chosen_fft_name(), and set_fft_library_ctl().
hd_ispack3
character(len = kchara), parameter, private m_fft_selector::hd_ispack3 = 'ISPACK3' private
Character flag to use ISPACK.
Definition at line 71 of file m_FFT_selector.f90.
Referenced by chosen_fft_name(), and set_fft_library_ctl().
hd_ispack3_c
character(len = kchara), parameter, private m_fft_selector::hd_ispack3_c = 'ISPACK3_COMPONENT' private
Character flag to use ISPACK for component.
Definition at line 76 of file m_FFT_selector.f90.
Referenced by chosen_fft_name(), and set_fft_library_ctl().
hd_ispack3_d
character(len = kchara), parameter, private m_fft_selector::hd_ispack3_d = 'ISPACK3_DOMAIN' private
Character flag to use ISPACK for domain.
Definition at line 73 of file m_FFT_selector.f90.
Referenced by chosen_fft_name(), and set_fft_library_ctl().
hd_ispack3_s
character(len = kchara), parameter, private m_fft_selector::hd_ispack3_s = 'ISPACK3_SINGLE' private
Character flag to use ISPACK for component.
Definition at line 79 of file m_FFT_selector.f90.
Referenced by chosen_fft_name(), and set_fft_library_ctl().
hd_ispack_d
character(len = kchara), parameter, private m_fft_selector::hd_ispack_d = 'ISPACK_DOMAIN' private
Character flag to use ISPACK for domain.
Definition at line 67 of file m_FFT_selector.f90.
Referenced by chosen_fft_name(), and set_fft_library_ctl().
hd_omp_fftw
character(len = kchara), parameter, private m_fft_selector::hd_omp_fftw = 'OMP_FFTW' private
Character flag to use FFTW3 for each component.
Definition at line 54 of file m_FFT_selector.f90.
Referenced by chosen_fft_name(), and set_fft_library_ctl().
hd_omp_fftw3
character(len = kchara), parameter, private m_fft_selector::hd_omp_fftw3 = 'omp_fftw3' private
Character flag to use FFTW3 for each component.
Definition at line 56 of file m_FFT_selector.f90.
Referenced by set_fft_library_ctl().
hd_omp_fftw3_d
character(len = kchara), parameter, private m_fft_selector::hd_omp_fftw3_d = 'omp_fftw3_domain' private
Character flag to use FFTW3 for each component.
Definition at line 61 of file m_FFT_selector.f90.
Referenced by set_fft_library_ctl().
hd_omp_fftw_d
character(len = kchara), parameter, private m_fft_selector::hd_omp_fftw_d = 'OMP_FFTW_DOMAIN' private
Character flag to use FFTW3 for each component.
Definition at line 58 of file m_FFT_selector.f90.
Referenced by chosen_fft_name(), and set_fft_library_ctl().
iflag_fft_test
integer(kind = kint), parameter m_fft_selector::iflag_fft_test = 99
integer flag to use test FFT
Definition at line 125 of file m_FFT_selector.f90.
Referenced by chosen_fft_name(), and set_fft_library_ctl().
iflag_fftpack
integer(kind = kint), parameter m_fft_selector::iflag_fftpack = 1
integer flag to use FFTPACK5
Definition at line 88 of file m_FFT_selector.f90.
Referenced by chosen_fft_name(), set_fft_library_ctl(), and write_elapsed_4_fft().
iflag_fftpack_component
integer(kind = kint), parameter m_fft_selector::iflag_fftpack_component = 3
integer flag to use FFTPACK5
Definition at line 92 of file m_FFT_selector.f90.
Referenced by t_sph_fft_selector::back_fft_select_from_recv(), chosen_fft_name(), t_sph_fft_selector::finalize_sph_fft_select(), t_sph_fft_selector::fwd_fft_select_to_send(), t_sph_fft_selector::init_sph_fft_select(), set_fft_library_ctl(), t_sph_fft_selector::verify_sph_fft_select(), and write_elapsed_4_fft().
iflag_fftpack_domain
integer(kind = kint), parameter m_fft_selector::iflag_fftpack_domain = 4
integer flag to use FFTPACK5
Definition at line 94 of file m_FFT_selector.f90.
Referenced by t_sph_fft_selector::back_fft_select_from_recv(), chosen_fft_name(), t_sph_fft_selector::finalize_sph_fft_select(), t_sph_fft_selector::fwd_fft_select_to_send(), t_sph_fft_selector::init_sph_fft_select(), set_fft_library_ctl(), t_sph_fft_selector::verify_sph_fft_select(), and write_elapsed_4_fft().
iflag_fftpack_single
integer(kind = kint), parameter m_fft_selector::iflag_fftpack_single = 2
integer flag to use FFTPACK5
Definition at line 90 of file m_FFT_selector.f90.
Referenced by t_sph_fft_selector::back_fft_select_from_recv(), chosen_fft_name(), t_sph_fft_selector::finalize_sph_fft_select(), t_sph_fft_selector::fwd_fft_select_to_send(), t_sph_fft_selector::init_sph_fft_select(), set_fft_library_ctl(), t_sph_fft_selector::verify_sph_fft_select(), and write_elapsed_4_fft().
iflag_fftw
integer(kind = kint), parameter m_fft_selector::iflag_fftw = 11
integer flag to use FFTW3
Definition at line 97 of file m_FFT_selector.f90.
Referenced by t_sph_fft_selector::back_fft_select_from_recv(), t_fft_selector::backward_fft_select(), chosen_fft_name(), t_fft_selector::finalize_fft_sel_t(), t_sph_fft_selector::finalize_sph_fft_select(), t_fft_selector::forward_fft_select(), t_sph_fft_selector::fwd_fft_select_to_send(), t_sph_fft_selector::init_sph_fft_select(), t_fft_selector::initialize_fft_select(), set_fft_library_ctl(), init_fft_4_mhd::set_fft_mode_4_snapshot(), t_fft_selector::verify_fft_select(), t_sph_fft_selector::verify_sph_fft_select(), and write_elapsed_4_fft().
iflag_fftw_component
integer(kind = kint), parameter m_fft_selector::iflag_fftw_component = 13
integer flag to use single transforms in FFTW3
Definition at line 101 of file m_FFT_selector.f90.
Referenced by t_sph_fft_selector::back_fft_select_from_recv(), chosen_fft_name(), t_sph_fft_selector::finalize_sph_fft_select(), t_sph_fft_selector::fwd_fft_select_to_send(), t_sph_fft_selector::init_sph_fft_select(), set_fft_library_ctl(), init_fft_4_mhd::set_fft_mode_4_snapshot(), t_sph_fft_selector::verify_sph_fft_select(), and write_elapsed_4_fft().
iflag_fftw_domain
integer(kind = kint), parameter m_fft_selector::iflag_fftw_domain = 14
integer flag to use FFTW3 for each component
Definition at line 103 of file m_FFT_selector.f90.
Referenced by t_sph_fft_selector::back_fft_select_from_recv(), chosen_fft_name(), t_sph_fft_selector::finalize_sph_fft_select(), t_sph_fft_selector::fwd_fft_select_to_send(), t_sph_fft_selector::init_sph_fft_select(), set_fft_library_ctl(), init_fft_4_mhd::set_fft_mode_4_snapshot(), t_sph_fft_selector::verify_sph_fft_select(), and write_elapsed_4_fft().
iflag_fftw_single
integer(kind = kint), parameter m_fft_selector::iflag_fftw_single = 12
integer flag to use single transforms in FFTW3
Definition at line 99 of file m_FFT_selector.f90.
Referenced by t_sph_fft_selector::back_fft_select_from_recv(), t_fft_selector::backward_fft_select(), chosen_fft_name(), t_fft_selector::finalize_fft_sel_t(), t_sph_fft_selector::finalize_sph_fft_select(), t_fft_selector::forward_fft_select(), t_sph_fft_selector::fwd_fft_select_to_send(), t_sph_fft_selector::init_sph_fft_select(), t_fft_selector::initialize_fft_select(), set_fft_library_ctl(), init_fft_4_mhd::set_fft_mode_4_snapshot(), t_fft_selector::verify_fft_select(), t_sph_fft_selector::verify_sph_fft_select(), and write_elapsed_4_fft().
iflag_ispack1
integer(kind = kint), parameter m_fft_selector::iflag_ispack1 = 21
integer flag to use ISPACK Ver.0.93
Definition at line 111 of file m_FFT_selector.f90.
Referenced by chosen_fft_name(), set_fft_library_ctl(), and write_elapsed_4_fft().
iflag_ispack1_domain
integer(kind = kint), parameter m_fft_selector::iflag_ispack1_domain = 22
integer flag to use ISPACK Ver.0.93 for domain
Definition at line 113 of file m_FFT_selector.f90.
Referenced by chosen_fft_name(), set_fft_library_ctl(), and write_elapsed_4_fft().
iflag_ispack3
integer(kind = kint), parameter m_fft_selector::iflag_ispack3 = 31
integer flag to use ISPACK Ver. 3.01
Definition at line 116 of file m_FFT_selector.f90.
Referenced by chosen_fft_name(), set_fft_library_ctl(), and write_elapsed_4_fft().
iflag_ispack3_component
integer(kind = kint), parameter m_fft_selector::iflag_ispack3_component = 33
integer flag to use ISPACK Ver. 3.01 for domain
Definition at line 120 of file m_FFT_selector.f90.
Referenced by chosen_fft_name(), set_fft_library_ctl(), and write_elapsed_4_fft().
iflag_ispack3_domain
integer(kind = kint), parameter m_fft_selector::iflag_ispack3_domain = 32
integer flag to use ISPACK Ver. 3.01 for domain
Definition at line 118 of file m_FFT_selector.f90.
Referenced by chosen_fft_name(), set_fft_library_ctl(), and write_elapsed_4_fft().
iflag_ispack3_single
integer(kind = kint), parameter m_fft_selector::iflag_ispack3_single = 34
integer flag to use ISPACK Ver. 3.01 for domain
Definition at line 122 of file m_FFT_selector.f90.
Referenced by chosen_fft_name(), set_fft_library_ctl(), and write_elapsed_4_fft().
iflag_omp_fftw
integer(kind = kint), parameter m_fft_selector::iflag_omp_fftw = 41
integer flag to use FFTW3 with OopenMP at once
Definition at line 106 of file m_FFT_selector.f90.
Referenced by chosen_fft_name(), set_fft_library_ctl(), and write_elapsed_4_fft().
iflag_omp_fftw_domain
integer(kind = kint), parameter m_fft_selector::iflag_omp_fftw_domain = 42
integer flag to use FFTW3 with OopenMP for domain
Definition at line 108 of file m_FFT_selector.f90.
Referenced by chosen_fft_name(), set_fft_library_ctl(), and write_elapsed_4_fft().
iflag_undefined_fft
integer(kind = kint), parameter m_fft_selector::iflag_undefined_fft = 0
integer flag for undefined
Definition at line 86 of file m_FFT_selector.f90.
Referenced by init_fft_4_mhd::init_fourier_transform_4_mhd(), and init_fft_4_sph::init_fourier_transform_4_sph().