CALYPSO: sph_analyzer_snap_w_psf Module Reference
sph_analyzer_snap_w_psf Module Reference
Evolution loop for spherical MHD.
Functions/Subroutines
subroutine sph_init_sph_snap_psf (MHD_files, iphys, SPH_model, SPH_MHD, SPH_WK)
subroutine sph_analyze_snap_psf (i_step, MHD_files, SPH_model, MHD_step, SPH_MHD, SPH_WK)
Detailed Description
Evolution loop for spherical MHD.
      subroutine SPH_init_sph_snap_psf(MHD_files, iphys,              &
     &          SPH_model, SPH_MHD, SPH_WK)
        type(MHD_file_IO_params), intent(in) :: MHD_files
        type(phys_address), intent(in) :: iphys
        type(SPH_MHD_model_data), intent(inout) :: SPH_model
        type(SPH_mesh_field_data), intent(inout) :: SPH_MHD
        type(work_SPH_MHD), intent(inout) :: SPH_WK
      subroutine SPH_analyze_snap_psf(i_step, MHD_files, SPH_model,   &
     &          MHD_step, SPH_MHD, SPH_WK)
        type(phys_address), intent(in) :: iphys
        type(MHD_file_IO_params), intent(in) :: MHD_files
        type(SPH_MHD_model_data), intent(inout) :: SPH_model
        type(MHD_step_param), intent(inout) :: MHD_step
        type(SPH_mesh_field_data), intent(inout) :: SPH_MHD
        type(work_SPH_MHD), intent(inout) :: SPH_WK
Function/Subroutine Documentation
sph_analyze_snap_psf()
subroutine sph_analyzer_snap_w_psf::sph_analyze_snap_psf (integer(kind = kint), intent(in) i_step, type(mhd_file_io_params), intent(in) MHD_files, type(sph_mhd_model_data), intent(inout) SPH_model, type(mhd_step_param), intent(inout) MHD_step, type(sph_mesh_field_data), intent(inout) SPH_MHD, type(work_sph_mhd), intent(inout) SPH_WK)
Definition at line 121 of file SPH_analyzer_snap_w_psf.f90.
References m_work_time::end_elapsed_time(), m_elapsed_labels_4_mhd::iflag_mhd_time, m_elapsed_labels_4_mhd::iflag_smhd_time, m_elapsed_labels_4_mhd::ist_elapsed_mhd, m_elapsed_labels_4_mhd::ist_elapsed_smhd, output_viz_file_control::lead_field_data_flag(), cal_nonlinear::nonlinear(), t_sph_mhd_monitor_data_io::output_rms_sph_mhd_control(), sph_mhd_rst_io_control::output_spectr_4_snap(), sph_mhd_rst_io_control::read_alloc_sph_rst_4_snap(), lead_fields_4_sph_mhd::s_lead_fields_4_sph_mhd(), t_boundary_data_sph_mhd::set_mhd_evolved_boundaries(), cal_sol_sph_mhd_crank::set_sph_field_to_start(), m_work_time::start_elapsed_time(), adjust_reference_fields::sync_temp_by_per_temp_sph(), and adjust_reference_fields::trans_per_temp_to_temp_sph().
Referenced by analyzer_sph_snap_w_psf::evolution_sph_snap_w_psf().
sph_init_sph_snap_psf()
subroutine sph_analyzer_snap_w_psf::sph_init_sph_snap_psf (type(mhd_file_io_params), intent(in) MHD_files, type(phys_address), intent(in) iphys, type(sph_mhd_model_data), intent(inout) SPH_model, type(sph_mesh_field_data), intent(inout) SPH_MHD, type(work_sph_mhd), intent(inout) SPH_WK)
Definition at line 50 of file SPH_analyzer_snap_w_psf.f90.
References const_radial_mat_4_sph::const_radial_mat_sph_snap(), m_machine_parameter::iflag_debug, init_radial_infos_sph_mhd::init_r_infos_sph_mhd_evo(), sph_mhd_rst_io_control::init_radial_sph_interpolation(), init_sphrical_transform_mhd::init_sph_transform_mhd(), t_sph_mhd_monitor_data_io::open_sph_vol_rms_file_mhd(), and check_dependency_for_mhd::set_sph_mhd_sprctr_data().
Referenced by analyzer_sph_snap_w_psf::initialize_sph_snap_w_psf().