CALYPSO: m_intersection_data_2 Module Reference
m_intersection_data_2 Module Reference
Variables
integer(kind=kint), parameter, private nnod_tri = 3
integer(kind=kint), parameter, private nnod_quad = 4
integer(kind=kint), parameter nkind_etype_2 = 12
integer(kind=kint), parameter num_quad_2 = 1
integer(kind=kint), parameter num_patch_2 = 2
integer(kind=kint), dimension(6), parameter iq_2_p_2 = (/1, 2, 4, 3, 4, 2/)
integer(kind=kint), dimension(3, 2) iquad_2_patches_2
integer(kind=kint), dimension(nkind_etype_2), parameter iflag_psf_etype_2p = (/ 3, 6, 12, 9, 48, 96, 192, 144, 17, 34, 68, 136/)
integer(kind=kint), dimension(nkind_etype_2), parameter iflag_psf_etype_2n = (/252, 249, 243, 246, 207, 159, 63, 111, 238, 221, 187, 119/)
integer(kind=kint), dimension(nnod_quad, nkind_etype_2), parameter iedge_quad_2p = reshape((/ 4, 2,10, 9, 1, 3,11,10, 2, 4,12,11, 3, 1, 9,12, 9,10, 6, 8, 10,11, 7, 5, 11,12, 8, 6, 12, 9, 5, 7, 8, 4, 1, 5, 5, 1, 2, 6, 6, 2, 3, 7, 7, 3, 4, 8/), shape=(/nnod_quad,nkind_etype_2/))
integer(kind=kint), dimension(nnod_tri, num_patch_2, nkind_etype_2), parameter iedge_4_patch_2p = reshape((/ 4, 2, 9, 10, 9, 2, 1, 3, 10, 11, 10, 3, 2, 4, 11, 12, 11, 4, 3, 1, 12, 9, 12, 1, 9, 10, 8, 6, 8, 10, 10, 11, 5, 7, 5, 11, 11, 12, 6, 8, 6, 12, 12, 9, 7, 5, 7, 9, 8, 4, 5, 1, 5, 4, 5, 1, 6, 2, 6, 1, 6, 2, 7, 3, 7, 2, 7, 3, 8, 4, 8, 3/), shape=(/nnod_tri,num_patch_2,nkind_etype_2/))
integer(kind=kint), dimension(nnod_quad, nkind_etype_2), parameter iedge_quad_2n = reshape((/ 4, 9,10, 2, 1,10,11, 3, 2,11,12, 4, 3,12, 9, 1, 9, 8, 6,10, 10, 5, 7,11, 11, 6, 8,12, 12, 7, 5, 9, 8, 5, 1, 4, 5, 6, 2, 1, 6, 7, 3, 2, 7, 8, 4, 3/), shape=(/nnod_quad,nkind_etype_2/))
integer(kind=kint), dimension(nnod_tri, num_patch_2, nkind_etype_2), parameter iedge_4_patch_2n = reshape((/ 4, 9, 2, 10, 2, 9, 1, 10, 3, 11, 3, 10, 2, 11, 4, 12, 4, 11, 3, 12, 1, 9, 1, 12, 9, 8, 10, 6, 10, 8, 10, 5, 11, 7, 11, 5, 11, 6, 12, 8, 12, 6, 12, 7, 9, 5, 9, 7, 8, 5, 4, 1, 4, 5, 5, 6, 1, 2, 1, 6, 6, 7, 2, 3, 2, 7, 7, 8, 3, 4, 3, 8/), shape=(/nnod_tri,num_patch_2,nkind_etype_2/))
Variable Documentation
iedge_4_patch_2n
integer(kind = kint), dimension(nnod_tri,num_patch_2,nkind_etype_2), parameter m_intersection_data_2::iedge_4_patch_2n = reshape((/ 4, 9, 2, 10, 2, 9, 1, 10, 3, 11, 3, 10, 2, 11, 4, 12, 4, 11, 3, 12, 1, 9, 1, 12, 9, 8, 10, 6, 10, 8, 10, 5, 11, 7, 11, 5, 11, 6, 12, 8, 12, 6, 12, 7, 9, 5, 9, 7, 8, 5, 4, 1, 4, 5, 5, 6, 1, 2, 1, 6, 6, 7, 2, 3, 2, 7, 7, 8, 3, 4, 3, 8/), shape=(/nnod_tri,num_patch_2,nkind_etype_2/))
Definition at line 96 of file m_intersection_data_2.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
iedge_4_patch_2p
integer(kind = kint), dimension(nnod_tri,num_patch_2,nkind_etype_2), parameter m_intersection_data_2::iedge_4_patch_2p = reshape((/ 4, 2, 9, 10, 9, 2, 1, 3, 10, 11, 10, 3, 2, 4, 11, 12, 11, 4, 3, 1, 12, 9, 12, 1, 9, 10, 8, 6, 8, 10, 10, 11, 5, 7, 5, 11, 11, 12, 6, 8, 6, 12, 12, 9, 7, 5, 7, 9, 8, 4, 5, 1, 5, 4, 5, 1, 6, 2, 6, 1, 6, 2, 7, 3, 7, 2, 7, 3, 8, 4, 8, 3/), shape=(/nnod_tri,num_patch_2,nkind_etype_2/))
Definition at line 76 of file m_intersection_data_2.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
iedge_quad_2n
integer(kind = kint), dimension(nnod_quad,nkind_etype_2), parameter m_intersection_data_2::iedge_quad_2n = reshape((/ 4, 9,10, 2, 1,10,11, 3, 2,11,12, 4, 3,12, 9, 1, 9, 8, 6,10, 10, 5, 7,11, 11, 6, 8,12, 12, 7, 5, 9, 8, 5, 1, 4, 5, 6, 2, 1, 6, 7, 3, 2, 7, 8, 4, 3/), shape=(/nnod_quad,nkind_etype_2/))
Definition at line 88 of file m_intersection_data_2.f90.
iedge_quad_2p
integer(kind = kint), dimension(nnod_quad,nkind_etype_2), parameter m_intersection_data_2::iedge_quad_2p = reshape((/ 4, 2,10, 9, 1, 3,11,10, 2, 4,12,11, 3, 1, 9,12, 9,10, 6, 8, 10,11, 7, 5, 11,12, 8, 6, 12, 9, 5, 7, 8, 4, 1, 5, 5, 1, 2, 6, 6, 2, 3, 7, 7, 3, 4, 8/), shape=(/nnod_quad,nkind_etype_2/))
Definition at line 68 of file m_intersection_data_2.f90.
iflag_psf_etype_2n
integer(kind = kint), dimension(nkind_etype_2), parameter m_intersection_data_2::iflag_psf_etype_2n = (/252, 249, 243, 246, 207, 159, 63, 111, 238, 221, 187, 119/)
Definition at line 63 of file m_intersection_data_2.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
iflag_psf_etype_2p
integer(kind = kint), dimension(nkind_etype_2), parameter m_intersection_data_2::iflag_psf_etype_2p = (/ 3, 6, 12, 9, 48, 96, 192, 144, 17, 34, 68, 136/)
Definition at line 59 of file m_intersection_data_2.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
iq_2_p_2
integer(kind = kint), dimension(6), parameter m_intersection_data_2::iq_2_p_2 = (/1, 2, 4, 3, 4, 2/)
Definition at line 54 of file m_intersection_data_2.f90.
iquad_2_patches_2
integer(kind = kint), dimension(3,2) m_intersection_data_2::iquad_2_patches_2
Definition at line 57 of file m_intersection_data_2.f90.
nkind_etype_2
integer(kind = kint), parameter m_intersection_data_2::nkind_etype_2 = 12
Definition at line 51 of file m_intersection_data_2.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
nnod_quad
integer(kind = kint), parameter, private m_intersection_data_2::nnod_quad = 4 private
Definition at line 14 of file m_intersection_data_2.f90.
nnod_tri
integer(kind = kint), parameter, private m_intersection_data_2::nnod_tri = 3 private
Definition at line 13 of file m_intersection_data_2.f90.
num_patch_2
integer(kind = kint), parameter m_intersection_data_2::num_patch_2 = 2
Definition at line 53 of file m_intersection_data_2.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
num_quad_2
integer(kind = kint), parameter m_intersection_data_2::num_quad_2 = 1
Definition at line 52 of file m_intersection_data_2.f90.