CALYPSO: find_node_and_patch_psf Module Reference
find_node_and_patch_psf Module Reference
Construct surface patch.
Functions/Subroutines
subroutine dealloc_psf_node_and_patch (num_psf, psf_list, psf_mesh)
subroutine set_node_and_patch_psf (num_psf, mesh, group, psf_case_tbls, psf_def, psf_search, psf_list, psf_grp_list, psf_mesh)
subroutine set_node_and_patch_iso (num_iso, mesh, psf_case_tbls, iso_search, iso_list, iso_mesh)
Detailed Description
Construct surface patch.
      subroutine dealloc_psf_node_and_patch                           &
     &         (num_psf, psf_list, psf_mesh)
        type(sectioning_list), intent(inout) :: psf_list(num_psf)
        type(psf_local_data), intent(inout) :: psf_mesh(num_psf)
      subroutine set_node_and_patch_psf                               &
     &         (num_psf, mesh, group, psf_case_tbls,                  &
     &          psf_def, psf_search, psf_list, psf_grp_list, psf_mesh)
        type(node_data), intent(in) :: node
        type(element_data), intent(in) :: ele
        type(edge_data), intent(in) :: edge
        type(surface_group_data), intent(in) :: sf_grp
        type(surface_node_grp_data), intent(in) :: sf_grp_nod
        type(communication_table), intent(in) :: nod_comm
        type(psf_cases), intent(in) :: psf_case_tbls
        type(psf_search_lists), intent(inout) :: psf_search(num_psf)
        type(sectioning_list), intent(inout) :: psf_list(num_psf)
        type(grp_section_list), intent(inout) :: psf_grp_list(num_psf)
        type(psf_local_data), intent(inout) :: psf_mesh(num_psf)
      subroutine set_node_and_patch_iso(num_iso, mesh, psf_case_tbls, &
     &          iso_search, iso_list, iso_mesh)
        type(mesh_geometry), intent(in) :: mesh
        type(psf_cases), intent(in) :: psf_case_tbls
        type(psf_search_lists), intent(inout) :: iso_search(num_iso)
        type(sectioning_list), intent(inout):: iso_list(num_iso)
        type(psf_local_data), intent(inout) :: iso_mesh(num_iso)
Function/Subroutine Documentation
dealloc_psf_node_and_patch()
subroutine find_node_and_patch_psf::dealloc_psf_node_and_patch (integer(kind = kint), intent(in) num_psf, type(sectioning_list), dimension(num_psf), intent(inout) psf_list, type(psf_local_data), dimension(num_psf), intent(inout) psf_mesh)
Definition at line 50 of file find_node_and_patch_psf.f90.
References t_psf_geometry_list::dealloc_inod_psf(), and t_psf_geometry_list::dealloc_nnod_psf().
Referenced by t_cross_section::dealloc_psf_field_type(), and t_isosurface::isosurf_visualize().
set_node_and_patch_iso()
subroutine find_node_and_patch_psf::set_node_and_patch_iso (integer(kind = kint), intent(in) num_iso, type(mesh_geometry), intent(in) mesh, type(psf_cases), intent(in) psf_case_tbls, type(psf_search_lists), dimension(num_iso), intent(inout) iso_search, type(sectioning_list), dimension(num_iso), intent(inout) iso_list, type(psf_local_data), dimension(num_iso), intent(inout) iso_mesh)
Definition at line 167 of file find_node_and_patch_psf.f90.
References set_patches_for_psf::count_iso_patches(), set_nodes_for_psf::count_nodes_4_iso(), t_psf_geometry_list::dealloc_mark_ele_psf(), set_patches_for_psf::set_iso_patches(), and set_nodes_for_psf::set_nodes_4_iso().
Referenced by t_isosurface::isosurf_visualize().
set_node_and_patch_psf()
subroutine find_node_and_patch_psf::set_node_and_patch_psf (integer(kind = kint), intent(in) num_psf, type(mesh_geometry), intent(in) mesh, type(mesh_groups), intent(in) group, type(psf_cases), intent(in) psf_case_tbls, type(section_define), dimension(num_psf), intent(in) psf_def, type(psf_search_lists), dimension(num_psf), intent(inout) psf_search, type(sectioning_list), dimension(num_psf), intent(inout) psf_list, type(grp_section_list), dimension(num_psf), intent(inout) psf_grp_list, type(psf_local_data), dimension(num_psf), intent(inout) psf_mesh)
Definition at line 77 of file find_node_and_patch_psf.f90.
References t_psf_geometry_list::alloc_inod_grp_psf(), t_psf_geometry_list::alloc_inod_psf(), t_psf_geometry_list::alloc_nnod_grp_psf(), t_psf_geometry_list::alloc_nnod_psf(), calypso_mpi_int::calypso_mpi_allreduce_one_int(), const_element_comm_tables::const_global_numnod_list(), set_nodes_for_psf::count_nodes_4_psf(), set_patches_for_psf::count_psf_patches(), t_psf_geometry_list::dealloc_mark_ele_psf(), m_machine_parameter::i_debug, m_machine_parameter::iflag_debug, calypso_mpi::my_rank, m_machine_parameter::np_smp, set_nodes_for_psf::set_nodes_4_psf(), and set_patches_for_psf::set_psf_patches().
Referenced by t_cross_section::sectioning_initialize().