CALYPSO: t_edge_data Module Reference
t_edge_data Module Reference
Structure of edge geometry data.
Data Types
type edge_data
Structure for edge data.
Functions/Subroutines
subroutine alloc_numedge_stack (num_pe, edge)
subroutine alloc_inod_in_edge (edge)
subroutine alloc_edge_connect (edge, nsurf)
subroutine alloc_edge_4_ele (edge, nele)
subroutine alloc_isolate_edge (edge)
subroutine alloc_edge_geometory (edge)
subroutine alloc_edge_vect (edge)
subroutine alloc_edge_param_smp (edge)
subroutine dealloc_numedge_stack (edge)
subroutine dealloc_inod_in_edge (edge)
subroutine dealloc_edge_connect (edge)
subroutine dealloc_edge_4_ele (edge)
subroutine dealloc_isolate_edge (edge)
subroutine dealloc_edge_geometory (edge)
subroutine dealloc_edge_vect (edge)
subroutine dealloc_edge_param_smp (edge)
Detailed Description
Structure of edge geometry data.
      subroutine alloc_numedge_stack(num_pe, edge)
      subroutine alloc_inod_in_edge(edge)
      subroutine alloc_edge_connect(edge, nsurf)
      subroutine alloc_edge_4_ele(edge, nele)
      subroutine alloc_isolate_edge(edge)
      subroutine alloc_edge_geometory(edge)
      subroutine alloc_edge_vect(edge)
      subroutine alloc_edge_vect_sph(edge)
      subroutine alloc_edge_param_smp(edge)
        type(edge_data), intent(inout) :: edge
        type(edge_position), intent(inout) :: edge_pt
      subroutine dealloc_numedge_stack(edge)
      subroutine dealloc_inod_in_edge(edge)
      subroutine dealloc_edge_connect(edge)
      subroutine dealloc_edge_4_ele(edge)
      subroutine dealloc_isolate_edge(edge)
      subroutine dealloc_edge_geometory(edge)
      subroutine dealloc_edge_vect(edge)
        type(edge_position), intent(inout) :: edge_pt
      subroutine dealloc_edge_param_smp(edge)
        integer(kind = kint), intent(in) :: nele
        integer(kind = kint), intent(in) :: nsurf
        type(edge_data), intent(inout) :: edge
Function/Subroutine Documentation
alloc_edge_4_ele()
subroutine t_edge_data::alloc_edge_4_ele (type(edge_data), intent(inout) edge, integer(kind = kint), intent(in) nele)
Definition at line 155 of file t_edge_data.f90.
References m_geometry_constants::nedge_4_ele.
Referenced by const_edge_data::construct_edge_data(), set_edge_data_4_io::copy_edge_connect_from_io(), and const_edge_data::empty_edge_connect_type().
alloc_edge_connect()
subroutine t_edge_data::alloc_edge_connect (type(edge_data), intent(inout) edge, integer(kind = kint), intent(in) nsurf)
Definition at line 132 of file t_edge_data.f90.
References m_geometry_constants::nedge_4_surf.
Referenced by psf_global_nod_id::const_edge_comm_table_4_psf(), const_edge_data::construct_edge_data(), set_edge_data_4_io::copy_edge_connect_from_io(), and const_edge_data::empty_edge_connect_type().
alloc_edge_geometory()
subroutine t_edge_data::alloc_edge_geometory (type(edge_data), intent(inout) edge)
Definition at line 182 of file t_edge_data.f90.
Referenced by psf_global_nod_id::const_edge_comm_table_4_psf(), set_edge_data_4_io::copy_edge_geometry_from_io(), set_surf_edge_mesh::empty_surface_and_edge(), and set_surf_edge_mesh::set_edge_geometry().
alloc_edge_param_smp()
subroutine t_edge_data::alloc_edge_param_smp (type(edge_data), intent(inout) edge)
Definition at line 216 of file t_edge_data.f90.
References m_machine_parameter::np_smp.
Referenced by set_size_4_smp_types::count_edge_size_smp_type(), and const_edge_data::empty_edge_connect_type().
alloc_edge_vect()
subroutine t_edge_data::alloc_edge_vect (type(edge_data), intent(inout) edge)
Definition at line 198 of file t_edge_data.f90.
alloc_inod_in_edge()
subroutine t_edge_data::alloc_inod_in_edge (type(edge_data), intent(inout) edge)
Definition at line 118 of file t_edge_data.f90.
References m_geometry_constants::nedge_4_ele, and m_geometry_constants::nedge_4_surf.
Referenced by const_mesh_information::set_local_element_info().
alloc_isolate_edge()
subroutine t_edge_data::alloc_isolate_edge (type(edge_data), intent(inout) edge)
Definition at line 170 of file t_edge_data.f90.
alloc_numedge_stack()
subroutine t_edge_data::alloc_numedge_stack (integer, intent(in) num_pe, type(edge_data), intent(inout) edge)
Definition at line 103 of file t_edge_data.f90.
Referenced by const_element_comm_tables::const_global_edge_id().
dealloc_edge_4_ele()
subroutine t_edge_data::dealloc_edge_4_ele (type(edge_data), intent(inout) edge)
Definition at line 265 of file t_edge_data.f90.
Referenced by t_mesh_data::dealloc_ele_surf_edge_type(), and t_mesh_data::dealloc_mesh_infomations().
dealloc_edge_connect()
subroutine t_edge_data::dealloc_edge_connect (type(edge_data), intent(inout) edge)
Definition at line 252 of file t_edge_data.f90.
Referenced by psf_global_nod_id::const_edge_comm_table_4_psf(), t_mesh_data::dealloc_ele_surf_edge_type(), and t_mesh_data::dealloc_mesh_infomations().
dealloc_edge_geometory()
subroutine t_edge_data::dealloc_edge_geometory (type(edge_data), intent(inout) edge)
Definition at line 287 of file t_edge_data.f90.
Referenced by psf_global_nod_id::const_edge_comm_table_4_psf(), and t_mesh_data::dealloc_mesh_infomations().
dealloc_edge_param_smp()
subroutine t_edge_data::dealloc_edge_param_smp (type(edge_data), intent(inout) edge)
Definition at line 309 of file t_edge_data.f90.
Referenced by t_mesh_data::dealloc_mesh_infomations().
dealloc_edge_vect()
subroutine t_edge_data::dealloc_edge_vect (type(edge_data), intent(inout) edge)
Definition at line 297 of file t_edge_data.f90.
dealloc_inod_in_edge()
subroutine t_edge_data::dealloc_inod_in_edge (type(edge_data), intent(inout) edge)
Definition at line 241 of file t_edge_data.f90.
Referenced by t_mesh_data::dealloc_nod_ele_infos().
dealloc_isolate_edge()
subroutine t_edge_data::dealloc_isolate_edge (type(edge_data), intent(inout) edge)
Definition at line 276 of file t_edge_data.f90.
dealloc_numedge_stack()
subroutine t_edge_data::dealloc_numedge_stack (type(edge_data), intent(inout) edge)
Definition at line 230 of file t_edge_data.f90.
Referenced by const_element_comm_tables::dealloc_ele_comm_tbls_gl_nele().