CALYPSO: copy_communication_table Module Reference
copy_communication_table Module Reference
Copy routines of communication table.
Functions/Subroutines
subroutine copy_neighboring_pe (num_neib, id_neib_org, id_neib)
subroutine copy_num_import (num_neib, istack_import_org, istack_import, ntot_import)
subroutine copy_num_export (num_neib, istack_export_org, istack_export, ntot_export)
subroutine copy_import_item (ntot_import, item_import_org, item_import)
subroutine copy_export_item (ntot_export, item_export_org, item_export)
Detailed Description
Copy routines of communication table.
      subroutine copy_neighboring_pe(num_neib, id_neib_org, id_neib)
      subroutine copy_num_import(num_neib, istack_import_org,         &
     &          istack_import, ntot_import)
      subroutine copy_num_export(num_neib, istack_export_org,         &
     &          istack_export, ntot_export)
      subroutine copy_import_item                                     &
     &         (ntot_import, item_import_org, item_import)
      subroutine copy_export_item                                     &
     &         (ntot_export, item_export_org, item_export)
Function/Subroutine Documentation
copy_export_item()
subroutine copy_communication_table::copy_export_item (integer(kind = kint), intent(in) ntot_export, integer(kind = kint), dimension(ntot_export), intent(in) item_export_org, integer(kind = kint), dimension(ntot_export), intent(inout) item_export)
Definition at line 107 of file copy_communication_table.f90.
Referenced by t_comm_table::copy_export_table_type().
copy_import_item()
subroutine copy_communication_table::copy_import_item (integer(kind = kint), intent(in) ntot_import, integer(kind = kint), dimension(ntot_import), intent(in) item_import_org, integer(kind = kint), dimension(ntot_import), intent(inout) item_import)
Definition at line 90 of file copy_communication_table.f90.
Referenced by t_comm_table::copy_import_table_type().
copy_neighboring_pe()
subroutine copy_communication_table::copy_neighboring_pe (integer(kind = kint), intent(in) num_neib, integer(kind = kint), dimension(num_neib), intent(in) id_neib_org, integer(kind = kint), dimension(num_neib), intent(inout) id_neib)
Definition at line 34 of file copy_communication_table.f90.
Referenced by t_comm_table::copy_neib_pe_type().
copy_num_export()
subroutine copy_communication_table::copy_num_export (integer(kind = kint), intent(in) num_neib, integer(kind = kint), dimension(0:num_neib), intent(in) istack_export_org, integer(kind = kint), dimension(0:num_neib), intent(inout) istack_export, integer(kind = kint), intent(inout) ntot_export)
Definition at line 69 of file copy_communication_table.f90.
References m_constants::izero.
Referenced by t_comm_table::copy_export_table_type().
copy_num_import()
subroutine copy_communication_table::copy_num_import (integer(kind = kint), intent(in) num_neib, integer(kind = kint), dimension(0:num_neib), intent(in) istack_import_org, integer(kind = kint), dimension(0:num_neib), intent(inout) istack_import, integer(kind = kint), intent(inout) ntot_import)
Definition at line 48 of file copy_communication_table.f90.
References m_constants::izero.
Referenced by t_comm_table::copy_import_table_type().