CALYPSO: gz_sph_global_1d_idx_io Module Reference
gz_sph_global_1d_idx_io Module Reference
Data IO routines for spectrum data.
Functions/Subroutines
subroutine read_rtp_gl_1d_table_gz (sph_IO, zbuf)
subroutine read_rj_gl_1d_table_gz (sph_IO, zbuf)
subroutine write_rtp_gl_1d_table_gz (sph_IO, zbuf)
subroutine write_rj_gl_1d_table_gz (sph_IO, zbuf)
Detailed Description
Data IO routines for spectrum data.
      subroutine read_rtp_gl_1d_table_gz(sph_IO, zbuf)
      subroutine read_rj_gl_1d_table_gz(sph_IO, zbuf)
        type(sph_IO_data), intent(inout) :: sph_IO
        type(buffer_4_gzip), intent(inout) :: zbuf
      subroutine write_rtp_gl_1d_table_gz(sph_IO, zbuf)
      subroutine write_rj_gl_1d_table_gz(sph_IO, zbuf)
        type(sph_IO_data), intent(in) :: sph_IO
        type(buffer_4_gzip), intent(inout) :: zbuf
Function/Subroutine Documentation
read_rj_gl_1d_table_gz()
subroutine gz_sph_global_1d_idx_io::read_rj_gl_1d_table_gz (type(sph_io_data), intent(inout) sph_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 90 of file gz_sph_global_1d_idx_IO.f90.
References t_node_id_spherical_io::alloc_idx_sph_1d1_io(), t_node_id_spherical_io::alloc_idx_sph_1d2_io(), t_node_id_spherical_io::alloc_num_idx_sph_io(), gzip_file_access::get_one_line_text_from_gz(), and skip_gz_comment::skip_gz_comment_int().
Referenced by gz_sph_modes_grids_data_io::read_spectr_modes_rj_data_gz(), and gz_sph_modes_grids_data_io::read_spectr_modes_rlm_data_gz().
read_rtp_gl_1d_table_gz()
subroutine gz_sph_global_1d_idx_io::read_rtp_gl_1d_table_gz (type(sph_io_data), intent(inout) sph_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 36 of file gz_sph_global_1d_idx_IO.f90.
References t_node_id_spherical_io::alloc_idx_sph_1d1_io(), t_node_id_spherical_io::alloc_idx_sph_1d2_io(), t_node_id_spherical_io::alloc_idx_sph_1d3_io(), t_node_id_spherical_io::alloc_num_idx_sph_io(), gzip_file_access::get_one_line_text_from_gz(), and skip_gz_comment::skip_gz_comment_int().
Referenced by gz_sph_modes_grids_data_io::read_geom_rtm_data_gz(), and gz_sph_modes_grids_data_io::read_geom_rtp_data_gz().
write_rj_gl_1d_table_gz()
subroutine gz_sph_global_1d_idx_io::write_rj_gl_1d_table_gz (type(sph_io_data), intent(in) sph_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 197 of file gz_sph_global_1d_idx_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf(), m_sph_modes_grid_labels::hd_jmode(), and m_sph_modes_grid_labels::hd_rgrid().
Referenced by gz_sph_modes_grids_data_io::write_modes_rlm_data_gz(), and gz_sph_modes_grids_data_io::write_spectr_modes_rj_data_gz().
write_rtp_gl_1d_table_gz()
subroutine gz_sph_global_1d_idx_io::write_rtp_gl_1d_table_gz (type(sph_io_data), intent(in) sph_IO, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 133 of file gz_sph_global_1d_idx_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf(), m_sph_modes_grid_labels::hd_pgrid(), m_sph_modes_grid_labels::hd_rgrid(), and m_sph_modes_grid_labels::hd_tgrid().
Referenced by gz_sph_modes_grids_data_io::write_geom_rtm_data_gz(), and gz_sph_modes_grids_data_io::write_geom_rtp_data_gz().