CALYPSO: select_exp_magne_icb Module Reference
select_exp_magne_icb Module Reference
Select boundary condition routines for magnetic field.
Functions/Subroutines
subroutine sel_icb_grad_bp_and_current (sph_rj, r_2nd, sph_bc_B, ICB_Bspec, g_sph_rj, is_magne, is_current, rj_fld)
subroutine sel_icb_grad_poloidal_magne (sph_rj, r_2nd, sph_bc_B, ICB_Bspec, g_sph_rj, is_magne, rj_fld)
subroutine sel_icb_sph_current (sph_rj, r_2nd, sph_bc_B, g_sph_rj, is_magne, is_current, rj_fld)
subroutine sel_icb_sph_rotation_uxb (sph_rj, r_2nd, sph_bc_B, g_sph_rj, is_fld, is_rot, rj_fld)
subroutine sel_icb_sph_magnetic_diffusion (sph_rj, r_2nd, sph_bc_B, g_sph_rj, coef_diffuse, is_magne, is_ohmic, rj_fld)
Detailed Description
Select boundary condition routines for magnetic field.
      subroutine sel_ICB_grad_bp_and_current                          &
     &         (sph_rj, r_2nd, sph_bc_B, ICB_Bspec, g_sph_rj,         &
     &          is_magne, is_current, rj_fld)
        Address for input:    is_magne, is_magne+2
        Address for solution: is_magne+1,
                              is_current, is_current+2, is_current+1
      subroutine sel_ICB_grad_poloidal_magne                          &
     &         (sph_rj, r_2nd, sph_bc_B, ICB_Bspec, g_sph_rj,         &
     &          is_magne, rj_fld)
        Address for input:    is_magne, is_magne+2
        Address for solution: is_magne+1
      subroutine sel_ICB_sph_current                                  &
     &         (sph_rj, r_2nd, sph_bc_B, g_sph_rj,                    &
     &          is_magne, is_current, rj_fld)
        Address for input:    is_magne, is_magne+2
        Address for solution: is_current, is_current+2, is_current+1
      subroutine sel_ICB_sph_rotation_uxb                             &
     &         (sph_rj, r_2nd, sph_bc_B, g_sph_rj,                    &
     &          is_fld, is_rot, rj_fld)
        Address for input:    is_fld, it_fld
        Address for solution: is_rot, it_rot, ids_rot
      subroutine sel_ICB_sph_magnetic_diffusion                       &
     &         (sph_rj, r_2nd, sph_bc_B, g_sph_rj, coef_diffuse,      &
     &          is_magne, is_ohmic, rj_fld)
        Address for input:    is_magne, is_magne+2
        Address for solution: is_ohmic, is_ohmic+2, is_ohmic+1
          type(sph_boundary_type), intent(in) :: sph_bc_B
          type(sph_rj_grid), intent(in) :: sph_rj
          type(fdm_matrices), intent(in) :: r_2nd
          type(phys_data), intent(inout) :: rj_fld
Parameters
sph_bc_B Structure for basic boundary condition parameters for magnetic field
coef_diffuse Diffusion coefficient
is_magne Spherical hermonics data address for poloidal magnetic field
is_current Spherical hermonics data address for current density
is_ohmic Spherical hermonics data address for poloidal ohmic dissipation
ids_ohmic Spherical hermonics data address for radial derivative of poloidal ohmic dissipation
is_fld Spherical hermonics data address for input vector
is_rot Spherical hermonics data address for curl of field
Parameters
rj_fld Spectrum data structure
Function/Subroutine Documentation
sel_icb_grad_bp_and_current()
subroutine select_exp_magne_icb::sel_icb_grad_bp_and_current (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc_B, type(sph_vector_bc_coef), intent(in) ICB_Bspec, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, integer(kind = kint), intent(in) is_magne, integer(kind = kint), intent(in) is_current, type(phys_data), intent(inout) rj_fld)
Definition at line 85 of file select_exp_magne_ICB.f90.
References set_sph_exp_fix_vector_icb::cal_sph_nod_icb_fixed_rot2(), cal_sph_exp_nod_icb_ins::cal_sph_nod_icb_ins_b_and_j(), cal_sph_exp_nod_icb_qvac::cal_sph_nod_icb_qvc_b_and_j(), set_sph_exp_fix_vector_icb::cal_sph_nod_icb_rigid_vect(), t_boundary_params_sph_mhd::iflag_evolve_field, t_boundary_params_sph_mhd::iflag_radial_magne, t_boundary_params_sph_mhd::iflag_sph_fill_center, and set_sph_exp_nod_center::sph_center_fld_and_curl().
Referenced by const_sph_radial_grad::const_grad_bp_and_current().
sel_icb_grad_poloidal_magne()
subroutine select_exp_magne_icb::sel_icb_grad_poloidal_magne (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc_B, type(sph_vector_bc_coef), intent(in) ICB_Bspec, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, integer(kind = kint), intent(in) is_magne, type(phys_data), intent(inout) rj_fld)
Definition at line 135 of file select_exp_magne_ICB.f90.
References set_sph_exp_nod_center::cal_dsdr_sph_center_2(), cal_sph_exp_nod_icb_ins::cal_sph_nod_icb_ins_mag2(), cal_sph_exp_nod_icb_qvac::cal_sph_nod_icb_qvc_mag2(), set_sph_exp_fix_vector_icb::cal_sph_nod_icb_rigid_vect(), t_boundary_params_sph_mhd::iflag_evolve_field, t_boundary_params_sph_mhd::iflag_radial_magne, and t_boundary_params_sph_mhd::iflag_sph_fill_center.
Referenced by cal_sol_sph_fluid_crank::cal_sol_magne_sph_crank(), and const_sph_radial_grad::const_grad_poloidal_magne().
sel_icb_sph_current()
subroutine select_exp_magne_icb::sel_icb_sph_current (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc_B, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, integer(kind = kint), intent(in) is_magne, integer(kind = kint), intent(in) is_current, type(phys_data), intent(inout) rj_fld)
Definition at line 175 of file select_exp_magne_ICB.f90.
References set_sph_exp_nod_center::cal_sph_nod_center_rot2(), set_sph_exp_fix_vector_icb::cal_sph_nod_icb_fixed_rot2(), cal_sph_exp_nod_icb_ins::cal_sph_nod_icb_ins_rot2(), cal_sph_exp_nod_icb_qvac::cal_sph_nod_icb_qvc_rot2(), t_boundary_params_sph_mhd::iflag_evolve_field, t_boundary_params_sph_mhd::iflag_radial_magne, and t_boundary_params_sph_mhd::iflag_sph_fill_center.
Referenced by const_sph_rotation::const_sph_current().
sel_icb_sph_magnetic_diffusion()
subroutine select_exp_magne_icb::sel_icb_sph_magnetic_diffusion (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc_B, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, real(kind = kreal), intent(in) coef_diffuse, integer(kind = kint), intent(in) is_magne, integer(kind = kint), intent(in) is_ohmic, type(phys_data), intent(inout) rj_fld)
Definition at line 255 of file select_exp_magne_ICB.f90.
References set_sph_exp_nod_center::cal_dsdr_sph_center_2(), cal_sph_exp_fixed_scalar::cal_dsdr_sph_no_bc_in_2(), set_sph_exp_nod_center::cal_sph_nod_center_diffuse2(), set_sph_exp_fix_vector_icb::cal_sph_nod_icb_fixed_diffuse2(), cal_sph_exp_nod_icb_ins::cal_sph_nod_icb_ins_diffuse2(), cal_sph_exp_nod_icb_qvac::cal_sph_nod_icb_qvc_diffuse2(), t_boundary_params_sph_mhd::iflag_evolve_field, t_boundary_params_sph_mhd::iflag_radial_magne, and t_boundary_params_sph_mhd::iflag_sph_fill_center.
Referenced by const_sph_rotation::const_sph_mag_diffuse_by_j(), and const_sph_diffusion::const_sph_magnetic_diffusion().
sel_icb_sph_rotation_uxb()
subroutine select_exp_magne_icb::sel_icb_sph_rotation_uxb (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc_B, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_rot, type(phys_data), intent(inout) rj_fld)
Definition at line 219 of file select_exp_magne_ICB.f90.
References set_sph_exp_nod_center::cal_sph_nod_center_rot2(), cal_sph_exp_nod_icb_ins::cal_sph_nod_icb_ins_vp_rot2(), cal_sph_exp_nod_icb_qvac::cal_sph_nod_icb_qvc_vp_rot2(), t_boundary_params_sph_mhd::iflag_radial_magne, and t_boundary_params_sph_mhd::iflag_sph_fill_center.
Referenced by const_sph_rotation::const_sph_rotation_uxb().