CALYPSO: sph_global_1d_idx_io_b Module Reference
sph_global_1d_idx_io_b Module Reference
Data IO routines for spectrum data.
Functions/Subroutines
subroutine read_rtp_gl_1d_table_b (bbuf, sph_IO)
subroutine read_rj_gl_1d_table_b (bbuf, sph_IO)
subroutine write_rtp_gl_1d_table_b (sph_IO, bbuf)
subroutine write_rj_gl_1d_table_b (sph_IO, bbuf)
Detailed Description
Data IO routines for spectrum data.
      subroutine read_rtp_gl_1d_table_b(bbuf, sph_IO)
      subroutine read_rj_gl_1d_table_b(bbuf, sph_IO)
        type(binary_IO_buffer), intent(inout) :: bbuf
        type(sph_IO_data), intent(inout) :: sph_IO
      subroutine write_rtp_gl_1d_table_b(sph_IO, bbuf)
      subroutine write_rj_gl_1d_table_b(sph_IO, bbuf)
        type(sph_IO_data), intent(in) :: sph_IO
        type(binary_IO_buffer), intent(inout) :: bbuf
Function/Subroutine Documentation
read_rj_gl_1d_table_b()
subroutine sph_global_1d_idx_io_b::read_rj_gl_1d_table_b (type(binary_io_buffer), intent(inout) bbuf, type(sph_io_data), intent(inout) sph_IO)
Definition at line 82 of file sph_global_1d_idx_IO_b.f90.
References t_node_id_spherical_io::alloc_idx_sph_1d1_io(), t_node_id_spherical_io::alloc_idx_sph_1d2_io(), t_node_id_spherical_io::alloc_num_idx_sph_io(), binary_io::read_1d_vector_b(), and binary_io::read_mul_integer_b().
Referenced by sph_modes_grids_data_io_b::read_modes_rlm_data_b(), and sph_modes_grids_data_io_b::read_spectr_modes_rj_data_b().
read_rtp_gl_1d_table_b()
subroutine sph_global_1d_idx_io_b::read_rtp_gl_1d_table_b (type(binary_io_buffer), intent(inout) bbuf, type(sph_io_data), intent(inout) sph_IO)
Definition at line 37 of file sph_global_1d_idx_IO_b.f90.
References t_node_id_spherical_io::alloc_idx_sph_1d1_io(), t_node_id_spherical_io::alloc_idx_sph_1d2_io(), t_node_id_spherical_io::alloc_idx_sph_1d3_io(), t_node_id_spherical_io::alloc_num_idx_sph_io(), binary_io::read_1d_vector_b(), and binary_io::read_mul_integer_b().
Referenced by sph_modes_grids_data_io_b::read_geom_rtm_data_b(), and sph_modes_grids_data_io_b::read_geom_rtp_data_b().
write_rj_gl_1d_table_b()
subroutine sph_global_1d_idx_io_b::write_rj_gl_1d_table_b (type(sph_io_data), intent(in) sph_IO, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 155 of file sph_global_1d_idx_IO_b.f90.
References binary_io::write_1d_vector_b(), and binary_io::write_mul_integer_b().
Referenced by sph_modes_grids_data_io_b::write_modes_rlm_data_b(), and sph_modes_grids_data_io_b::write_spectr_modes_rj_data_b().
write_rtp_gl_1d_table_b()
subroutine sph_global_1d_idx_io_b::write_rtp_gl_1d_table_b (type(sph_io_data), intent(in) sph_IO, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 122 of file sph_global_1d_idx_IO_b.f90.
References binary_io::write_1d_vector_b(), and binary_io::write_mul_integer_b().
Referenced by sph_modes_grids_data_io_b::write_geom_rtm_data_b(), and sph_modes_grids_data_io_b::write_geom_rtp_data_b().