CALYPSO: r_interpolate_marged_sph Module Reference
r_interpolate_marged_sph Module Reference
Radial interpolation for assemble program.
Data Types
type sph_radial_itp_data
Functions/Subroutines
subroutine const_r_interpolate_table (org_sph_mesh, new_sph_mesh, r_itp)
subroutine const_icb_and_cmb_radius (org_sph_mesh, new_sph_mesh, nlayer_ICB_org, nlayer_CMB_org, nlayer_ICB_new, nlayer_CMB_new)
subroutine deallocate_radial_itp_tbl (r_itp)
subroutine allocate_radial_itp_tbl (nri_new, r_itp)
subroutine, private set_sph_boundary_4_merge (sph_grps, nlayer_ICB, nlayer_CMB)
subroutine, private share_r_interpolation_tbl (new_sph_mesh, r_itp)
subroutine share_icb_and_cmb_radius (nlayer_ICB_org, nlayer_CMB_org, nlayer_ICB_new, nlayer_CMB_new)
subroutine, private sph_radial_interpolation_coef (nri_org, r_org, nri_new, r_new, r_itp)
Detailed Description
Radial interpolation for assemble program.
      subroutine const_r_interpolate_table                            &
     &         (org_sph_mesh, new_sph_mesh, r_itp)
        type(sph_mesh_data), intent(in) :: org_sph_mesh
        type(sph_mesh_data), intent(inout) :: new_sph_mesh
        type(sph_radial_itp_data), intent(inout) :: r_itp
      subroutine const_ICB_and_CMB_radius(org_sph_mesh, new_sph_mesh, &
     &          nlayer_ICB_org, nlayer_CMB_org,                       &
     &          nlayer_ICB_new, nlayer_CMB_new)
      subroutine deallocate_radial_itp_tbl(nri_new)
      subroutine sph_radial_interpolation_coef                        &
     &         (nri_org, r_org, nri_new, r_new)
Parameters
nnod_org Number of spectr data for original data
nri_org Number of radial grid for original data
jmax_org Number of harmonics modes for original data
r_org Position of radial grid for original data
idx_gl_1d_j_org(jmax_org,3) List of spherical harmonics modes for original data
d_rj_IO Read harmonics data data
Function/Subroutine Documentation
allocate_radial_itp_tbl()
subroutine r_interpolate_marged_sph::allocate_radial_itp_tbl (integer(kind = kint), intent(in) nri_new, type(sph_radial_itp_data), intent(inout) r_itp)
Definition at line 131 of file r_interpolate_marged_sph.f90.
Referenced by share_r_interpolation_tbl(), and sph_radial_interpolation_coef().
const_icb_and_cmb_radius()
subroutine r_interpolate_marged_sph::const_icb_and_cmb_radius (type(sph_mesh_data), intent(in) org_sph_mesh, type(sph_mesh_data), intent(in) new_sph_mesh, integer(kind = kint), intent(inout) nlayer_ICB_org, integer(kind = kint), intent(inout) nlayer_CMB_org, integer(kind = kint), intent(inout) nlayer_ICB_new, integer(kind = kint), intent(inout) nlayer_CMB_new)
Definition at line 91 of file r_interpolate_marged_sph.f90.
References calypso_mpi::my_rank, set_sph_boundary_4_merge(), and share_icb_and_cmb_radius().
const_r_interpolate_table()
subroutine r_interpolate_marged_sph::const_r_interpolate_table (type(sph_mesh_data), intent(in) org_sph_mesh, type(sph_mesh_data), intent(inout) new_sph_mesh, type(sph_radial_itp_data), intent(inout) r_itp)
Definition at line 69 of file r_interpolate_marged_sph.f90.
References calypso_mpi::my_rank, share_r_interpolation_tbl(), and sph_radial_interpolation_coef().
Referenced by analyzer_assemble_sph::init_assemble_sph(), analyzer_compare_sph_rst::init_compare_sph_restart(), and analyzer_rayleigh_cvt_sph::init_cvt_rayleigh_sph().
deallocate_radial_itp_tbl()
subroutine r_interpolate_marged_sph::deallocate_radial_itp_tbl (type(sph_radial_itp_data), intent(inout) r_itp)
Definition at line 118 of file r_interpolate_marged_sph.f90.
set_sph_boundary_4_merge()
subroutine, private r_interpolate_marged_sph::set_sph_boundary_4_merge (type(sph_group_data), intent(in) sph_grps, integer(kind = kint), intent(inout) nlayer_ICB, integer(kind = kint), intent(inout) nlayer_CMB) private
Definition at line 150 of file r_interpolate_marged_sph.f90.
References t_spheric_parameter::cmb_nod_grp_name, skip_comment_f::cmp_no_case(), and t_spheric_parameter::icb_nod_grp_name.
Referenced by const_icb_and_cmb_radius().
share_icb_and_cmb_radius()
subroutine r_interpolate_marged_sph::share_icb_and_cmb_radius (integer(kind = kint), intent(inout) nlayer_ICB_org, integer(kind = kint), intent(inout) nlayer_CMB_org, integer(kind = kint), intent(inout) nlayer_ICB_new, integer(kind = kint), intent(inout) nlayer_CMB_new)
Definition at line 215 of file r_interpolate_marged_sph.f90.
References calypso_mpi_int::calypso_mpi_bcast_one_int(), and calypso_mpi::my_rank.
Referenced by const_icb_and_cmb_radius().
share_r_interpolation_tbl()
subroutine, private r_interpolate_marged_sph::share_r_interpolation_tbl (type(sph_mesh_data), intent(inout) new_sph_mesh, type(sph_radial_itp_data), intent(inout) r_itp) private
Definition at line 178 of file r_interpolate_marged_sph.f90.
References allocate_radial_itp_tbl(), calypso_mpi_int::calypso_mpi_bcast_int(), calypso_mpi_int::calypso_mpi_bcast_one_int(), calypso_mpi_real::calypso_mpi_bcast_real(), transfer_to_long_integers::cast_long(), and calypso_mpi::my_rank.
Referenced by const_r_interpolate_table().
sph_radial_interpolation_coef()
subroutine, private r_interpolate_marged_sph::sph_radial_interpolation_coef (integer(kind = kint), intent(in) nri_org, real(kind = kreal), dimension(nri_org), intent(in) r_org, integer(kind = kint), intent(in) nri_new, real(kind = kreal), dimension(nri_org), intent(in) r_new, type(sph_radial_itp_data), intent(inout) r_itp) private
Definition at line 241 of file r_interpolate_marged_sph.f90.
References allocate_radial_itp_tbl().
Referenced by const_r_interpolate_table().