CALYPSO: set_sph_extensions Module Reference
set_sph_extensions Module Reference
Set file extension.
Functions/Subroutines
character(len=kchara) function add_fst_extension (file_head)
character(len=kchara) function add_fsb_extension (file_head)
character(len=kchara) function add_rtp_extension (file_head)
character(len=kchara) function add_rtm_extension (file_head)
character(len=kchara) function add_rlm_extension (file_head)
character(len=kchara) function add_rj_extension (file_head)
character(len=kchara) function add_btp_extension (file_head)
character(len=kchara) function add_btm_extension (file_head)
character(len=kchara) function add_blm_extension (file_head)
character(len=kchara) function add_brj_extension (file_head)
Variables
character(len=3), parameter, private fst_ext = "fst"
character(len=3), parameter, private fsb_ext = "fsb"
character(len=3), parameter, private rtp_ext = "rtp"
character(len=3), parameter, private rtm_ext = "rtm"
character(len=3), parameter, private rlm_ext = "rlm"
character(len=2), parameter, private rj_ext = "rj"
character(len=3), parameter, private btp_ext = "btp"
character(len=3), parameter, private btm_ext = "btm"
character(len=3), parameter, private blm_ext = "blm"
character(len=3), parameter, private brj_ext = "brj"
Detailed Description
Set file extension.
      character(len=kchara) function add_fst_extension(file_head)
                put ".fst" at the end
      character(len=kchara) function add_fsb_extension(file_head)
                put ".fsb" at the end
      character(len=kchara) function add_rtp_extension(file_head)
                put ".rtp" at the end
      character(len=kchara) function add_rtm_extension(file_head)
                put ".rtm" at the end
      character(len=kchara) function add_rlm_extension(file_head)
                put ".rlm" at the end
      character(len=kchara) function add_rj_extension(file_head)
                put ".rj" at the end
      character(len=kchara) function add_btp_extension(file_head)
                put ".btp" at the end
      character(len=kchara) function add_btm_extension(file_head)
                put ".btm" at the end
      character(len=kchara) function add_blm_extension(file_head)
                put ".blm" at the end
      character(len=kchara) function add_brj_extension(file_head)
                put ".brj" at the end
Parameters
dir_file_name file name (header) including directory name
int_id integer to be added at the end of prefix
int_val integer to be tranfered to character
int_string output character
Function/Subroutine Documentation
add_blm_extension()
character(len=kchara) function set_sph_extensions::add_blm_extension (character(len=kchara), intent(in) file_head)
Definition at line 146 of file set_sph_extensions.f90.
References set_parallel_file_name::add_3chara_extension(), and blm_ext.
Referenced by set_mesh_file_names::set_sph_rlm_file_name().
add_brj_extension()
character(len=kchara) function set_sph_extensions::add_brj_extension (character(len=kchara), intent(in) file_head)
Definition at line 156 of file set_sph_extensions.f90.
References set_parallel_file_name::add_3chara_extension(), and brj_ext.
Referenced by set_mesh_file_names::set_sph_rj_file_name().
add_btm_extension()
character(len=kchara) function set_sph_extensions::add_btm_extension (character(len=kchara), intent(in) file_head)
Definition at line 136 of file set_sph_extensions.f90.
References set_parallel_file_name::add_3chara_extension(), and btm_ext.
Referenced by set_mesh_file_names::set_sph_rtm_file_name().
add_btp_extension()
character(len=kchara) function set_sph_extensions::add_btp_extension (character(len=kchara), intent(in) file_head)
Definition at line 126 of file set_sph_extensions.f90.
References set_parallel_file_name::add_3chara_extension(), and btp_ext.
Referenced by set_mesh_file_names::set_sph_rtp_file_name().
add_fsb_extension()
character(len=kchara) function set_sph_extensions::add_fsb_extension (character(len=kchara), intent(in) file_head)
Definition at line 74 of file set_sph_extensions.f90.
References set_parallel_file_name::add_3chara_extension(), and fsb_ext.
Referenced by set_field_file_names::set_sph_fld_file_name().
add_fst_extension()
character(len=kchara) function set_sph_extensions::add_fst_extension (character(len=kchara), intent(in) file_head)
Definition at line 64 of file set_sph_extensions.f90.
References set_parallel_file_name::add_3chara_extension(), and fst_ext.
Referenced by set_field_file_names::set_sph_fld_file_name().
add_rj_extension()
character(len=kchara) function set_sph_extensions::add_rj_extension (character(len=kchara), intent(in) file_head)
Definition at line 115 of file set_sph_extensions.f90.
References set_parallel_file_name::add_2chara_extension(), and rj_ext.
Referenced by set_mesh_file_names::set_sph_rj_file_name().
add_rlm_extension()
character(len=kchara) function set_sph_extensions::add_rlm_extension (character(len=kchara), intent(in) file_head)
Definition at line 105 of file set_sph_extensions.f90.
References set_parallel_file_name::add_3chara_extension(), and rlm_ext.
Referenced by set_mesh_file_names::set_sph_rlm_file_name().
add_rtm_extension()
character(len=kchara) function set_sph_extensions::add_rtm_extension (character(len=kchara), intent(in) file_head)
Definition at line 95 of file set_sph_extensions.f90.
References set_parallel_file_name::add_3chara_extension(), and rtm_ext.
Referenced by set_mesh_file_names::set_sph_rtm_file_name().
add_rtp_extension()
character(len=kchara) function set_sph_extensions::add_rtp_extension (character(len=kchara), intent(in) file_head)
Definition at line 85 of file set_sph_extensions.f90.
References set_parallel_file_name::add_3chara_extension(), and rtp_ext.
Referenced by set_mesh_file_names::set_sph_rtp_file_name().
Variable Documentation
blm_ext
character(len=3), parameter, private set_sph_extensions::blm_ext = "blm" private
Definition at line 55 of file set_sph_extensions.f90.
Referenced by add_blm_extension().
brj_ext
character(len=3), parameter, private set_sph_extensions::brj_ext = "brj" private
Definition at line 56 of file set_sph_extensions.f90.
Referenced by add_brj_extension().
btm_ext
character(len=3), parameter, private set_sph_extensions::btm_ext = "btm" private
Definition at line 54 of file set_sph_extensions.f90.
Referenced by add_btm_extension().
btp_ext
character(len=3), parameter, private set_sph_extensions::btp_ext = "btp" private
Definition at line 53 of file set_sph_extensions.f90.
Referenced by add_btp_extension().
fsb_ext
character(len=3), parameter, private set_sph_extensions::fsb_ext = "fsb" private
Definition at line 47 of file set_sph_extensions.f90.
Referenced by add_fsb_extension().
fst_ext
character(len=3), parameter, private set_sph_extensions::fst_ext = "fst" private
Definition at line 46 of file set_sph_extensions.f90.
Referenced by add_fst_extension().
rj_ext
character(len=2), parameter, private set_sph_extensions::rj_ext = "rj" private
Definition at line 52 of file set_sph_extensions.f90.
Referenced by add_rj_extension().
rlm_ext
character(len=3), parameter, private set_sph_extensions::rlm_ext = "rlm" private
Definition at line 51 of file set_sph_extensions.f90.
Referenced by add_rlm_extension().
rtm_ext
character(len=3), parameter, private set_sph_extensions::rtm_ext = "rtm" private
Definition at line 50 of file set_sph_extensions.f90.
Referenced by add_rtm_extension().
rtp_ext
character(len=3), parameter, private set_sph_extensions::rtp_ext = "rtp" private
Definition at line 49 of file set_sph_extensions.f90.
Referenced by add_rtp_extension().