CALYPSO: pickup_gauss_coefficients Module Reference
pickup_gauss_coefficients Module Reference
Pick Gauss coefficients to output
Evaluate Nusselt number without heat source.
Functions/Subroutines
subroutine init_gauss_coefs_4_monitor (sph_params, sph_rj, ipol, gauss_list, gauss_coef)
subroutine gauss_coefficients_4_write (sph_params, sph_rj, ipol, rj_fld, gauss_coef, d_rj_out)
subroutine, private set_gauss_coefs_labels (gauss)
subroutine cal_no_heat_source_nu (kr_in, kr_out, r_in, r_out, idx_rj_degree_zero, nidx_rj, ipol, nnod_rj, ntot_phys_rj, d_rj, Nu_type)
Detailed Description
Pick Gauss coefficients to output
Evaluate Nusselt number without heat source.
      subroutine init_gauss_coefs_4_monitor                           &
     &          (sph_params, sph_rj, ipol, gauss_list, gauss_coef)
      subroutine gauss_coefficients_4_write                           &
     &        (sph_params, sph_rj, ipol, rj_fld, gauss_coef, d_rj_out)
        type(sph_shell_parameters), intent(in) :: sph_params
        type(sph_rj_grid), intent(in) :: sph_rj
        type(phys_address), intent(in) :: ipol
        type(picked_spectrum_data), intent(inout) :: gauss_coef
      subroutine cal_no_heat_source_Nu(kr_in, kr_out, r_in, r_out,    &
     &          idx_rj_degree_zero, nidx_rj,                          &
     &          nnod_rj, ntot_phys_rj, d_rj, Nu_type)
        type(phys_address), intent(in) :: ipol
        type(nusselt_number_data), intent(inout) :: Nu_type
Function/Subroutine Documentation
cal_no_heat_source_nu()
subroutine pickup_gauss_coefficients::cal_no_heat_source_nu (integer(kind = kint), intent(in) kr_in, integer(kind = kint), intent(in) kr_out, real(kind = kreal), intent(in) r_in, real(kind = kreal), intent(in) r_out, integer(kind = kint), intent(in) idx_rj_degree_zero, integer(kind = kint), dimension(2), intent(in) nidx_rj, type(phys_address), intent(in) ipol, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(nnod_rj,ntot_phys_rj), intent(in) d_rj, type(nusselt_number_data), intent(inout) Nu_type)
Definition at line 186 of file pickup_gauss_coefficients.f90.
References m_constants::half, and m_constants::izero.
Referenced by cal_write_sph_monitor_data::cal_sph_monitor_data(), and cal_write_sph_monitor_data::cal_write_no_heat_sourse_nu().
gauss_coefficients_4_write()
subroutine pickup_gauss_coefficients::gauss_coefficients_4_write (type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(phys_address), intent(in) ipol, type(phys_data), intent(in) rj_fld, type(picked_spectrum_data), intent(in) gauss_coef, real(kind=kreal), dimension(gauss_coef%num_sph_mode_lc), intent(inout) d_rj_out)
Definition at line 96 of file pickup_gauss_coefficients.f90.
References m_constants::one.
Referenced by mpi_sph_gauss_coefs_io::write_sph_gauss_coefes_mpi().
init_gauss_coefs_4_monitor()
subroutine pickup_gauss_coefficients::init_gauss_coefs_4_monitor (type(sph_shell_parameters), intent(in) sph_params, type(sph_rj_grid), intent(in) sph_rj, type(phys_address), intent(in) ipol, type(pickup_mode_list), intent(inout) gauss_list, type(picked_spectrum_data), intent(inout) gauss_coef)
Definition at line 48 of file pickup_gauss_coefficients.f90.
References t_pickup_sph_spectr_data::alloc_gauss_coef_monitor_lc(), t_pickup_sph_spectr_data::alloc_pick_sph_l(), t_pickup_sph_spectr_data::alloc_pick_sph_monitor(), pickup_sph_spectr::const_picked_sph_address(), t_pickup_sph_spectr_data::dealloc_pick_sph_mode(), m_constants::izero, m_base_field_labels::magnetic_field, and set_gauss_coefs_labels().
Referenced by t_sph_mhd_monitor_data_io::open_sph_vol_rms_file_mhd().
set_gauss_coefs_labels()
subroutine, private pickup_gauss_coefficients::set_gauss_coefs_labels (type(picked_spectrum_data), intent(inout) gauss) private
Definition at line 151 of file pickup_gauss_coefficients.f90.
References set_parallel_file_name::add_index_after_name(), and m_constants::izero.
Referenced by init_gauss_coefs_4_monitor().