CALYPSO: /home/takumi kera/calypso/src/module_dependency/make_module_dependency.f90 File Reference
make_module_dependency.f90 File Reference
Modules
module module_dependency
Constract module dependency for Makefile Usage: kemo_module_dep MAKEFILE SOURCE_DIRECTORY SOURCE_FILES for single file: kemo_module_dep MAKEFILE SOURCE_FILES Output command list for source with .f90 extension -c $< Output command list for source with .F90 extension -c $<.
Functions/Subroutines
subroutine module_dependency::alloc_mod_list
subroutine module_dependency::dealloc_mod_list
subroutine, private module_dependency::extend_mod_list
subroutine module_dependency::getarg_k (i, argc)
integer function module_dependency::iargc_kemo ()
subroutine, private module_dependency::const_module_list (filename)
subroutine, private module_dependency::write_module_list (objfile, filename, dirname, iflag_cpp)
subroutine module_dependency::make_module_dependency (dirname, filename)
subroutine module_dependency::make_module_dependency_f (dirname, filename)
program make_multi_mod_dependency
Variables
integer module_dependency::ntot
integer module_dependency::num
integer, parameter module_dependency::id_makefile = 21
character(len=64), dimension(:), allocatable module_dependency::mod_name
character(len=28), parameter, private module_dependency::command = ' $(F90) -c $(F90OPTFLAGS) $<'
character(len=43), parameter, private module_dependency::command_cpp = ' $(F90) -c $(F90OPTFLAGS) $(F90CPPFLAGS) $<'
integer, parameter, private module_dependency::num_exclude = 3
character(len=31), dimension(num_exclude) module_dependency::exclude_list = (/'ISO_C_BINDING', 'hdf5 ', 'mpi '/)
Function/Subroutine Documentation
make_multi_mod_dependency()
program make_multi_mod_dependency
Definition at line 271 of file make_module_dependency.f90.
References module_dependency::alloc_mod_list(), module_dependency::getarg_k(), module_dependency::iargc_kemo(), module_dependency::id_makefile, module_dependency::make_module_dependency(), and module_dependency::ntot.