CALYPSO: calypso_mpi_logical Module Reference
calypso_mpi_logical Module Reference
MPI communication routines for 4 byte integer in Calypso.
Functions/Subroutines
subroutine calypso_mpi_bcast_one_logical (buffer, root)
subroutine calypso_mpi_bcast_logical (buffer, count, root)
Detailed Description
MPI communication routines for 4 byte integer in Calypso.
      subroutine calypso_mpi_bcast_one_logical(buffer, root)
        integer, intent(in) :: root
        logical, intent(inout) :: buffer
      subroutine calypso_mpi_bcast_logical(buffer, count, root)
        integer, intent(in) :: root
        integer(kind = kint_gl), intent(in) :: count
        logical, intent(inout) :: buffer(count)
Parameters
icode error code
message message to output
Function/Subroutine Documentation
calypso_mpi_bcast_logical()
subroutine calypso_mpi_logical::calypso_mpi_bcast_logical (logical, dimension(count), intent(inout) buffer, integer(kind = kint_gl), intent(in) count, integer, intent(in) root)
Definition at line 53 of file calypso_mpi_logical.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_logical, m_constants::huge_20, and calypso_mpi::ierr_mpi.
Referenced by share_field_data::share_phys_field_names().
calypso_mpi_bcast_one_logical()
subroutine calypso_mpi_logical::calypso_mpi_bcast_one_logical (logical, intent(inout) buffer, integer, intent(in) root)
Definition at line 36 of file calypso_mpi_logical.f90.
References calypso_mpi::calypso_comm, calypso_mpi::calypso_logical, and calypso_mpi::ierr_mpi.
Referenced by parallel_gen_sph_grids::check_and_make_para_rj_mode(), t_check_and_make_sph_mesh::check_and_make_sph_mesh(), and t_check_and_make_sph_mesh::check_and_make_sph_rj_mode().