CALYPSO: t_control_array_charareal2 Module Reference
t_control_array_charareal2 Module Reference
Data Types
type ctl_array_cr2
Structure for charactor and two reals control array.
type read_chara_real2_item
structure of control item with three characters
Functions/Subroutines
subroutine read_charreal2_ctl_type (c_buf, label, cr2_item)
subroutine write_charreal2_ctl_type (id_file, level, label, cr2_item)
subroutine copy_charreal2_ctl (org_cr2, new_cr2)
subroutine alloc_control_array_c_r2 (array_cr2)
subroutine dealloc_control_array_c_r2 (array_cr2)
subroutine read_control_array_c_r2 (id_control, label, array_cr2, c_buf)
subroutine write_control_array_c_r2 (id_control, level, label, array_cr2)
subroutine append_control_array_c_r2 (read_cr2, array_cr2)
subroutine copy_control_array_c_r2 (num_copy, org_cr2, tgt_cr2)
subroutine append_control_item_c_r2 (read_cr2, array_cr2)
Function/Subroutine Documentation
alloc_control_array_c_r2()
subroutine t_control_array_charareal2::alloc_control_array_c_r2 (type(ctl_array_cr2), intent(inout) array_cr2)
Definition at line 140 of file t_control_array_charareal2.f90.
Referenced by append_control_array_c_r2(), bcast_control_arrays::bcast_ctl_array_cr2(), and read_control_array_c_r2().
append_control_array_c_r2()
subroutine t_control_array_charareal2::append_control_array_c_r2 (type(read_chara_real2_item), intent(inout) read_cr2, type(ctl_array_cr2), intent(inout) array_cr2)
Definition at line 234 of file t_control_array_charareal2.f90.
References alloc_control_array_c_r2(), append_control_item_c_r2(), copy_control_array_c_r2(), and dealloc_control_array_c_r2().
Referenced by read_control_array_c_r2().
append_control_item_c_r2()
subroutine t_control_array_charareal2::append_control_item_c_r2 (type(read_chara_real2_item), intent(in) read_cr2, type(ctl_array_cr2), intent(inout) array_cr2)
Definition at line 276 of file t_control_array_charareal2.f90.
Referenced by append_control_array_c_r2().
copy_charreal2_ctl()
subroutine t_control_array_charareal2::copy_charreal2_ctl (type(read_chara_real2_item), intent(in) org_cr2, type(read_chara_real2_item), intent(inout) new_cr2)
Definition at line 125 of file t_control_array_charareal2.f90.
copy_control_array_c_r2()
subroutine t_control_array_charareal2::copy_control_array_c_r2 (integer(kind = kint), intent(in) num_copy, type(ctl_array_cr2), intent(in) org_cr2, type(ctl_array_cr2), intent(inout) tgt_cr2)
Definition at line 259 of file t_control_array_charareal2.f90.
Referenced by append_control_array_c_r2().
dealloc_control_array_c_r2()
subroutine t_control_array_charareal2::dealloc_control_array_c_r2 (type(ctl_array_cr2), intent(inout) array_cr2)
Definition at line 157 of file t_control_array_charareal2.f90.
Referenced by append_control_array_c_r2().
read_charreal2_ctl_type()
subroutine t_control_array_charareal2::read_charreal2_ctl_type (type(buffer_for_control), intent(in) c_buf, character(len=kchara), intent(in) label, type(read_chara_real2_item), intent(inout) cr2_item)
Definition at line 79 of file t_control_array_charareal2.f90.
References m_machine_parameter::iflag_debug.
Referenced by read_control_array_c_r2().
read_control_array_c_r2()
subroutine t_control_array_charareal2::read_control_array_c_r2 (integer(kind = kint), intent(in) id_control, character(len=kchara), intent(in) label, type(ctl_array_cr2), intent(inout) array_cr2, type(buffer_for_control), intent(inout) c_buf)
Definition at line 171 of file t_control_array_charareal2.f90.
References alloc_control_array_c_r2(), append_control_array_c_r2(), t_read_control_elements::check_array_flag(), t_read_control_elements::check_end_array_flag(), t_read_control_elements::load_one_line_from_control(), and read_charreal2_ctl_type().
write_charreal2_ctl_type()
subroutine t_control_array_charareal2::write_charreal2_ctl_type (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, type(read_chara_real2_item), intent(in) cr2_item)
Definition at line 105 of file t_control_array_charareal2.f90.
References write_control_elements::write_chara_real2_ctl_item().
write_control_array_c_r2()
subroutine t_control_array_charareal2::write_control_array_c_r2 (integer(kind = kint), intent(in) id_control, integer(kind = kint), intent(in) level, character(len=kchara), intent(in) label, type(ctl_array_cr2), intent(in) array_cr2)
Definition at line 205 of file t_control_array_charareal2.f90.
References write_control_elements::write_array_flag_for_ctl(), write_control_elements::write_chara_real2_ctl_item(), and write_control_elements::write_end_array_flag_for_ctl().