CALYPSO: set_ucd_data Module Reference
set_ucd_data Module Reference
Link field data to IO structure for data IO.
Functions/Subroutines
subroutine link_node_data_2_output (numnod, inod_gl, xx, ucd)
subroutine link_ele_data_2_output (numele, nnod_4_ele, iele_gl, ie, ucd)
subroutine link_num_field_2_output (numnod, ntot_comp_vis, ucd)
subroutine link_field_data_2_output (numnod, num_phys, ntot_comp, num_phys_vis, ntot_comp_vis, num_component, phy_name, d_nod, ucd)
subroutine link_numnod_stacks_2_output (nprocs, istack_numnod, istack_internod, ucd)
subroutine link_numele_stacks_2_output (nprocs, istack_interele, ucd)
Detailed Description
Link field data to IO structure for data IO.
      subroutine link_node_data_2_output(numnod, inod_gl, xx, ucd)
      subroutine link_ele_data_2_output(numele, nnod_4_ele,           &
     &          iele_gl, ie, ucd)
      subroutine link_num_field_2_output(numnod, ntot_comp_vis, ucd)
      subroutine link_numnod_stacks_2_output                          &
     &         (nprocs, istack_numnod, istack_internod, ucd)
      subroutine link_numele_stacks_2_output                          &
     &          (nprocs, istack_interele, ucd)
        type(ucd_data), intent(inout) :: ucd
Function/Subroutine Documentation
link_ele_data_2_output()
subroutine set_ucd_data::link_ele_data_2_output (integer(kind = kint), intent(in) numele, integer(kind = kint), intent(in) nnod_4_ele, integer(kind = kint_gl), dimension(numele), intent(in), target iele_gl, integer(kind = kint), dimension(numele,nnod_4_ele), intent(in), target ie, type(ucd_data), intent(inout) ucd)
Definition at line 54 of file set_ucd_data.f90.
References t_ucd_data::allocate_ucd_ele().
Referenced by set_ucd_data_to_type::link_ele_data_2_ucd().
link_field_data_2_output()
subroutine set_ucd_data::link_field_data_2_output (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) num_phys, integer(kind = kint), intent(in) ntot_comp, integer(kind = kint), intent(in) num_phys_vis, integer(kind = kint), intent(in) ntot_comp_vis, integer(kind = kint), dimension(num_phys), intent(in), target num_component, character(len = kchara), dimension(num_phys), intent(in), target phy_name, real(kind = kreal), dimension(numnod,ntot_comp), intent(in), target d_nod, type(ucd_data), intent(inout) ucd)
Definition at line 93 of file set_ucd_data.f90.
Referenced by set_ucd_data_to_type::link_field_data_to_ucd().
link_node_data_2_output()
subroutine set_ucd_data::link_node_data_2_output (integer(kind = kint), intent(in) numnod, integer(kind = kint_gl), dimension(numnod), intent(in), target inod_gl, real(kind = kreal), dimension(numnod,3), intent(in), target xx, type(ucd_data), intent(inout) ucd)
Definition at line 37 of file set_ucd_data.f90.
Referenced by set_ucd_data_to_type::link_node_data_2_ucd().
link_num_field_2_output()
subroutine set_ucd_data::link_num_field_2_output (integer(kind = kint), intent(in) numnod, integer(kind = kint), intent(in) ntot_comp_vis, type(ucd_data), intent(inout) ucd)
Definition at line 79 of file set_ucd_data.f90.
Referenced by set_ucd_data_to_type::link_num_field_2_ucd().
link_numele_stacks_2_output()
subroutine set_ucd_data::link_numele_stacks_2_output (integer, intent(in) nprocs, integer(kind = kint_gl), dimension(0:nprocs), intent(in), target istack_interele, type(ucd_data), intent(inout) ucd)
Definition at line 143 of file set_ucd_data.f90.
Referenced by set_ucd_data_to_type::link_nele_stacks_2_ucd().
link_numnod_stacks_2_output()
subroutine set_ucd_data::link_numnod_stacks_2_output (integer, intent(in) nprocs, integer(kind = kint_gl), dimension(0:nprocs), intent(in), target istack_numnod, integer(kind = kint_gl), dimension(0:nprocs), intent(in), target istack_internod, type(ucd_data), intent(inout) ucd)
Definition at line 124 of file set_ucd_data.f90.
Referenced by set_ucd_data_to_type::link_nnod_stacks_2_ucd().