CALYPSO: set_sph_boundary_from_file Module Reference
set_sph_boundary_from_file Module Reference
Boundary condition data from external file.
Functions/Subroutines
integer(kind=kint) function num_comp_bc_data (label)
logical function, private find_scalar_bc_label (label, postfix)
logical function, private find_vector_bc_label (label, postfix)
logical function find_bc_label (field, label, postfix)
Variables
character(len=kchara), parameter mag_label = '_magnitude'
Postfix for magnetide.
character(len=kchara), parameter freq1_label = '_freq'
Postfix for frequency.
character(len=kchara), parameter freq2_label = '_freqency'
Postfix for frequency.
character(len=kchara), parameter phase_label = '_phase'
Postfix for initial phase.
Detailed Description
Boundary condition data from external file.
      integer(kind = kint) function num_comp_bc_data(label)
      logical function find_bc_label(field, label, postfix)
        type(field_def), intent(in) :: field
Function/Subroutine Documentation
find_bc_label()
logical function set_sph_boundary_from_file::find_bc_label (type(field_def), intent(in) field, character(len = kchara), intent(in) label, character(len = kchara), intent(in) postfix)
Definition at line 111 of file set_sph_boundary_from_file.f90.
References skip_comment_f::cmp_no_case().
Referenced by find_scalar_bc_label(), find_vector_bc_label(), set_sph_bc_data_by_file::set_evolved_grad_bc_by_file(), set_sph_bc_data_by_file::set_evolved_scalar_bc_by_file(), and set_sph_bc_data_by_file::set_evolved_vector_bc_by_file().
find_scalar_bc_label()
logical function, private set_sph_boundary_from_file::find_scalar_bc_label (character(len = kchara), intent(in) label, character(len = kchara), intent(in) postfix) private
Definition at line 78 of file set_sph_boundary_from_file.f90.
References m_base_force_labels::composite_flux, m_base_field_labels::composition, m_base_field_labels::entropy, find_bc_label(), m_base_force_labels::heat_flux, and m_base_field_labels::temperature.
Referenced by num_comp_bc_data().
find_vector_bc_label()
logical function, private set_sph_boundary_from_file::find_vector_bc_label (character(len = kchara), intent(in) label, character(len = kchara), intent(in) postfix) private
Definition at line 96 of file set_sph_boundary_from_file.f90.
References find_bc_label(), m_base_field_labels::magnetic_field, m_base_field_labels::velocity, and m_base_field_labels::vorticity.
Referenced by num_comp_bc_data().
num_comp_bc_data()
integer(kind = kint) function set_sph_boundary_from_file::num_comp_bc_data (character(len = kchara), intent(in) label)
Definition at line 41 of file set_sph_boundary_from_file.f90.
References skip_comment_f::cmp_no_case(), m_base_force_labels::composite_flux, m_base_field_labels::composition, m_base_field_labels::entropy, find_scalar_bc_label(), find_vector_bc_label(), freq1_label, freq2_label, m_base_force_labels::heat_flux, mag_label, m_base_field_labels::magnetic_field, phase_label, m_base_field_labels::temperature, m_base_field_labels::velocity, and m_base_field_labels::vorticity.
Referenced by t_each_sph_boundary_io_data::read_each_boundary_spectr().
Variable Documentation
freq1_label
character(len=kchara), parameter set_sph_boundary_from_file::freq1_label = '_freq'
Postfix for frequency.
Definition at line 26 of file set_sph_boundary_from_file.f90.
Referenced by num_comp_bc_data(), set_sph_bc_data_by_file::set_evolved_grad_bc_by_file(), set_sph_bc_data_by_file::set_evolved_scalar_bc_by_file(), and set_sph_bc_data_by_file::set_evolved_vector_bc_by_file().
freq2_label
character(len=kchara), parameter set_sph_boundary_from_file::freq2_label = '_freqency'
Postfix for frequency.
Definition at line 28 of file set_sph_boundary_from_file.f90.
Referenced by num_comp_bc_data(), set_sph_bc_data_by_file::set_evolved_grad_bc_by_file(), set_sph_bc_data_by_file::set_evolved_scalar_bc_by_file(), and set_sph_bc_data_by_file::set_evolved_vector_bc_by_file().
mag_label
character(len=kchara), parameter set_sph_boundary_from_file::mag_label = '_magnitude'
Postfix for magnetide.
Definition at line 24 of file set_sph_boundary_from_file.f90.
Referenced by num_comp_bc_data(), set_sph_bc_data_by_file::set_evolved_grad_bc_by_file(), set_sph_bc_data_by_file::set_evolved_scalar_bc_by_file(), and set_sph_bc_data_by_file::set_evolved_vector_bc_by_file().
phase_label
character(len=kchara), parameter set_sph_boundary_from_file::phase_label = '_phase'
Postfix for initial phase.
Definition at line 30 of file set_sph_boundary_from_file.f90.
Referenced by num_comp_bc_data(), set_sph_bc_data_by_file::set_evolved_grad_bc_by_file(), set_sph_bc_data_by_file::set_evolved_scalar_bc_by_file(), and set_sph_bc_data_by_file::set_evolved_vector_bc_by_file().