CALYPSO: mpi_viewer_mesh_file_io Module Reference
mpi_viewer_mesh_file_io Module Reference
Viewer mesh file IO for gzipped format.
Functions/Subroutines
subroutine mpi_write_viewer_mesh_file (file_name, mgd_v_mesh, mgd_view_prm)
subroutine, private write_viewer_mesh_infos (mgd_v_mesh, mgd_view_prm, IO_param)
Detailed Description
Viewer mesh file IO for gzipped format.
      subroutine mpi_write_viewer_mesh_file(file_name,                &
     &          mgd_v_mesh, mgd_view_prm)
        type(merged_viewer_mesh), intent(in) :: mgd_v_mesh
        type(mpi_viewer_mesh_param), intent(in) :: mgd_view_prm
Function/Subroutine Documentation
mpi_write_viewer_mesh_file()
subroutine mpi_viewer_mesh_file_io::mpi_write_viewer_mesh_file (character(len=kchara), intent(in) file_name, type(merged_viewer_mesh), intent(in) mgd_v_mesh, type(mpi_viewer_mesh_param), intent(in) mgd_view_prm)
Definition at line 34 of file MPI_viewer_mesh_file_IO.f90.
References mpi_ascii_data_io::close_mpi_file(), mpi_ascii_data_io::open_write_mpi_file(), and write_viewer_mesh_infos().
Referenced by viewer_mesh_mpi_io_select::sel_mpi_output_surface_grid().
write_viewer_mesh_infos()
subroutine, private mpi_viewer_mesh_file_io::write_viewer_mesh_infos (type(merged_viewer_mesh), intent(in) mgd_v_mesh, type(mpi_viewer_mesh_param), intent(in) mgd_view_prm, type(calypso_mpi_io_params), intent(inout) IO_param) private
Definition at line 58 of file MPI_viewer_mesh_file_IO.f90.
References m_viewer_mesh_labels::hd_domain_edge_grp(), m_viewer_mesh_labels::hd_domain_nod_grp(), m_viewer_mesh_labels::hd_domain_surf_grp(), m_viewer_mesh_labels::hd_edge_on_sf_viewer(), m_viewer_mesh_labels::hd_edge_viewer(), m_viewer_mesh_labels::hd_ele_edge_grp(), m_viewer_mesh_labels::hd_ele_nod_grp(), m_viewer_mesh_labels::hd_ele_surf_grp(), m_fem_mesh_labels::hd_fem_elegrp(), m_fem_mesh_labels::hd_fem_nodgrp(), m_fem_mesh_labels::hd_fem_sfgrp(), m_viewer_mesh_labels::hd_ndomain_viewer(), m_viewer_mesh_labels::hd_node_viewer(), m_viewer_mesh_labels::hd_surf_edge_grp(), m_viewer_mesh_labels::hd_surf_nod_grp(), m_viewer_mesh_labels::hd_surf_surf_grp(), m_viewer_mesh_labels::hd_surf_viewer(), m_constants::iten, m_constants::ithree, mpi_ascii_data_io::mpi_write_charahead(), mpi_viewer_mesh_io::mpi_write_domain_grp_data(), mpi_ascii_data_io::mpi_write_stack_over_domain(), mpi_viewer_mesh_io::mpi_write_viewer_connect(), mpi_viewer_mesh_io::mpi_write_viewer_element_type(), mpi_viewer_mesh_io::mpi_write_viewer_grp_data(), and mpi_viewer_mesh_io::mpi_write_viewer_position().
Referenced by mpi_write_viewer_mesh_file().