CALYPSO: const_sph_diffusion Module Reference
const_sph_diffusion Module Reference
Evaluate diffusion terms explicitly.
Functions/Subroutines
subroutine const_sph_viscous_diffusion (sph_rj, r_2nd, sph_bc_U, fdm2_free_ICB, fdm2_free_CMB, g_sph_rj, coef_diffuse, is_velo, is_viscous, rj_fld)
subroutine const_sph_vorticirty_diffusion (sph_rj, r_2nd, sph_bc_U, fdm2_free_ICB, fdm2_free_CMB, g_sph_rj, coef_diffuse, is_vort, is_w_diffuse, rj_fld)
subroutine const_sph_magnetic_diffusion (sph_rj, r_2nd, sph_bc_B, g_sph_rj, coef_diffuse, is_magne, is_ohmic, rj_fld)
subroutine const_sph_scalar_diffusion (sph_rj, r_2nd, sph_bc, bcs_S, fdm2_center, g_sph_rj, coef_diffuse, is_fld, is_diffuse, rj_fld)
Detailed Description
Evaluate diffusion terms explicitly.
      subroutine const_sph_viscous_diffusion                          &
     &         (sph_rj, r_2nd, sph_bc_U, fdm2_free_ICB, fdm2_free_CMB,&
     &          g_sph_rj, coef_diffuse, is_velo, is_viscous, rj_fld)
        Address for input:    is_velo, is_velo+2
        Address for solution: is_viscous, is_viscous+2, is_viscous+1
      subroutine const_sph_vorticirty_diffusion                       &
     &         (sph_rj, r_2nd, sph_bc_U, fdm2_free_ICB, fdm2_free_CMB,&
     &          g_sph_rj, coef_diffuse, is_vort, is_w_diffuse, rj_fld)
     &          is_vort, is_w_diffuse, rj_fld)
        Address for input:    is_vort, is_vort+2
        Address for solution: is_w_diffuse, is_w_diffuse+2,
                              is_w_diffuse+1
      subroutine const_sph_magnetic_diffusion(sph_rj, r_2nd, sph_bc_B,&
     &          g_sph_rj, coef_diffuse, is_magne, is_ohmic, rj_fld)
        Address for input:    is_magne, is_magne+2
        Address for solution: is_ohmic, is_ohmic+2, is_ohmic+1
      subroutine const_sph_scalar_diffusion                           &
     &         (sph_rj, r_2nd, sph_bc, bcs_S, fdm2_center,            &
     &          g_sph_rj, coef_diffuse, is_fld, is_diffuse, rj_fld)
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(fdm_matrices), intent(in) :: r_2nd
        type(phys_data), intent(inout) :: rj_fld
        type(sph_boundary_type), intent(in) :: sph_bc
        type(sph_scalar_boundary_data), intent(in) :: bcs_S
        type(fdm2_center_mat), intent(in) :: fdm2_center
Parameters
sph_bc Structure for basic boundary condition parameters
sph_bc_U Structure for basic boundary condition parameters for velocity
sph_bc_B Structure for basic boundary condition parameters for magnetic field
coef_diffuse Diffusion coefficient
is_velo Spherical hermonics data address for poloidal velocity field
is_vort Spherical hermonics data address for poloidal voeticity
is_viscous Spherical hermonics data address for poloidal visous diffusion
is_w_diffuse Spherical hermonics data address for poloidal diffusion term for vorticity
is_magne Spherical hermonics data address for poloidal magnetic field
is_ohmic Spherical hermonics data address for poloidal ohmic dissipation
is_fld Input spectr field address
is_diffuse Input spectr diffusiton term address
rj_fld Structure of spectr data
Function/Subroutine Documentation
const_sph_magnetic_diffusion()
subroutine const_sph_diffusion::const_sph_magnetic_diffusion (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc_B, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, real(kind = kreal), intent(in) coef_diffuse, integer(kind = kint), intent(in) is_magne, integer(kind = kint), intent(in) is_ohmic, type(phys_data), intent(inout) rj_fld)
Definition at line 167 of file const_sph_diffusion.f90.
References cal_sph_exp_diffusion::cal_sph_nod_vect_diffuse2(), cal_sph_exp_1st_diff::cal_sph_nod_vect_dr_2(), select_exp_magne_cmb::sel_cmb_sph_magnetic_diffusion(), and select_exp_magne_icb::sel_icb_sph_magnetic_diffusion().
const_sph_scalar_diffusion()
subroutine const_sph_diffusion::const_sph_scalar_diffusion (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc, type(sph_scalar_boundary_data), intent(in) bcs_S, type(fdm2_center_mat), intent(in) fdm2_center, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, real(kind = kreal), intent(in) coef_diffuse, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_diffuse, type(phys_data), intent(inout) rj_fld)
Definition at line 203 of file const_sph_diffusion.f90.
References cal_sph_exp_diffusion::cal_sph_nod_scalar_diffuse2(), select_exp_scalar_cmb::sel_cmb_sph_scalar_diffusion(), and select_exp_scalar_icb::sel_icb_sph_scalar_diffusion().
Referenced by cal_sol_sph_mhd_crank::update_after_composit_sph(), and cal_sol_sph_mhd_crank::update_after_heat_sph().
const_sph_viscous_diffusion()
subroutine const_sph_diffusion::const_sph_viscous_diffusion (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc_U, type(fdm2_free_slip), intent(in) fdm2_free_ICB, type(fdm2_free_slip), intent(in) fdm2_free_CMB, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, real(kind = kreal), intent(in) coef_diffuse, integer(kind = kint), intent(in) is_velo, integer(kind = kint), intent(in) is_viscous, type(phys_data), intent(inout) rj_fld)
Definition at line 87 of file const_sph_diffusion.f90.
References cal_sph_exp_diffusion::cal_sph_nod_vect_diffuse2(), cal_sph_exp_1st_diff::cal_sph_nod_vect_dr_2(), select_exp_velocity_cmb::sel_cmb_sph_viscous_diffusion(), and select_exp_velocity_icb::sel_icb_sph_viscous_diffusion().
const_sph_vorticirty_diffusion()
subroutine const_sph_diffusion::const_sph_vorticirty_diffusion (type(sph_rj_grid), intent(in) sph_rj, type(fdm_matrices), intent(in) r_2nd, type(sph_boundary_type), intent(in) sph_bc_U, type(fdm2_free_slip), intent(in) fdm2_free_ICB, type(fdm2_free_slip), intent(in) fdm2_free_CMB, real(kind = kreal), dimension(sph_rj%nidx_rj(2),13), intent(in) g_sph_rj, real(kind = kreal), intent(in) coef_diffuse, integer(kind = kint), intent(in) is_vort, integer(kind = kint), intent(in) is_w_diffuse, type(phys_data), intent(inout) rj_fld)
Definition at line 127 of file const_sph_diffusion.f90.
References cal_sph_exp_diffusion::cal_sph_nod_vect_diffuse2(), cal_sph_exp_1st_diff::cal_sph_nod_vect_dr_2(), select_exp_velocity_cmb::sel_cmb_sph_vort_diffusion(), and select_exp_velocity_icb::sel_icb_sph_vort_diffusion().
Referenced by cal_sol_sph_mhd_crank::update_after_vorticity_sph().