CALYPSO: set_parallel_file_name Module Reference
set_parallel_file_name Module Reference
Set file extension.
Functions/Subroutines
character(len=kchara) function delete_directory_name (dir_file_name)
character(len=kchara) function add_process_id (id_rank, file_head)
character(len=kchara) function add_int_suffix (int_id, file_head)
character(len=kchara) function add_dat_extension (file_head)
character(len=kchara) function add_elaps_postfix (file_head)
character(len=kchara) function add_gzip_extension (file_head)
character(len=kchara) function add_null_character (file_head)
character(len=kchara) function add_2chara_extension (file_head, extension)
character(len=kchara) function add_3chara_extension (file_head, extension)
character(len=kchara) function add_left_label (file_head)
character(len=kchara) function add_right_label (file_head)
subroutine add_index_after_name (int_id, chara_head, chara_name)
subroutine int_to_str (int_val, int_string)
subroutine lint_to_str (lint_val, int_string)
subroutine real_to_str (real_val, real_string)
Variables
character(len=2), parameter gz_ext = "gz"
Detailed Description
Set file extension.
      character(len = kchara) function delete_directory_name          &
     &                               (dir_file_name)
      character(len = kchara) function add_process_id                 &
     &                               (id_rank, file_head)
      character(len = kchara) function add_int_suffix                 &
     &                               (int_id, file_head)
      character(len = kchara) function add_dat_extension(file_head)
                put ".dat" at the end
      character(len = kchara) function add_elaps_postfix(file_head)
                put ".elps" at the end
      character(len = kchara) function add_gzip_extension(file_head)
                put ".gz"
      character(len = kchara) function add_null_character(file_head)
                put null character at the end
      character(len=kchara) function                                  &
     &                     add_2chara_extension(file_head, extension)
      character(len=kchara) function                                  &
     &                     add_3chara_extension(file_head, extension)
       character(len=kchara) function add_left_label(file_head)
                put "_left" at the end
       character(len=kchara) function add_right_label(file_head)
                put "_right" at the end
      subroutine add_index_after_name(int_id, chara_head, chara_name)
      subroutine int_to_str(int_val, int_string)
      subroutine lint_to_str(lint_val, int_string)
      subroutine real_to_str(real_val, real_string)
Parameters
dir_file_name file name (header) including directory name
int_id integer to be added at the end of prefix
file_name output file name
int_val integer to be tranfered to character
int_string output character
Function/Subroutine Documentation
add_2chara_extension()
character(len=kchara) function set_parallel_file_name::add_2chara_extension (character(len=kchara), intent(in) file_head, character(len=2), intent(in) extension)
Definition at line 173 of file set_parallel_file_name.f90.
Referenced by add_gzip_extension(), and set_sph_extensions::add_rj_extension().
add_3chara_extension()
character(len=kchara) function set_parallel_file_name::add_3chara_extension (character(len=kchara), intent(in) file_head, character(len=3), intent(in) extension)
Definition at line 186 of file set_parallel_file_name.f90.
Referenced by set_sph_extensions::add_blm_extension(), set_sph_extensions::add_brj_extension(), set_sph_extensions::add_btm_extension(), set_sph_extensions::add_btp_extension(), set_mesh_extensions::add_edb_extension(), set_mesh_extensions::add_elb_extension(), set_mesh_extensions::add_flb_extension(), set_mesh_extensions::add_fld_extension(), set_sph_extensions::add_fsb_extension(), set_sph_extensions::add_fst_extension(), set_mesh_extensions::add_ged_extension(), set_mesh_extensions::add_gel_extension(), set_mesh_extensions::add_gfb_extension(), set_mesh_extensions::add_gfm_extension(), set_ucd_extensions::add_grd_extension(), set_mesh_extensions::add_gsf_extension(), set_mesh_extensions::add_itb_extension(), set_mesh_extensions::add_itp_extension(), set_mesh_extensions::add_ksm_extension(), set_sph_extensions::add_rlm_extension(), set_sph_extensions::add_rtm_extension(), set_sph_extensions::add_rtp_extension(), set_ucd_extensions::add_sdt_extension(), set_mesh_extensions::add_sfb_extension(), set_ucd_extensions::add_sfm_extension(), set_ucd_extensions::add_sgd_extension(), set_ucd_extensions::add_ucd_extension(), set_ucd_extensions::add_udt_extension(), set_ucd_extensions::add_vtd_extension(), set_ucd_extensions::add_vtg_extension(), and set_ucd_extensions::add_vtk_extension().
add_dat_extension()
character(len = kchara) function set_parallel_file_name::add_dat_extension (character(len=kchara), intent(in) file_head)
Definition at line 128 of file set_parallel_file_name.f90.
Referenced by analyzer_test_sph::analyze_test_sph(), mpi_picked_sph_spectr_io::append_picked_spectrum_file(), mpi_sph_gauss_coefs_io::append_sph_gauss_coefs_file(), mpi_sph_gauss_coefs_io::check_gauss_coefs_num(), t_no_heat_nusselt::open_no_heat_source_nu(), node_monitor_io::open_node_monitor_file(), t_no_heat_nusselt::open_read_no_heat_source_nu(), t_picked_sph_spectr_data_io::open_sph_spec_read(), t_work_time::output_elapsed_log(), t_average_sph_ene_spec(), init_sph_mhd_elapsed_label::write_resolution_info(), output_sph_m_square_file::write_sph_vol_ave_file(), and t_picked_sph_spectr_data_io::write_tave_sph_spec_monitor().
add_elaps_postfix()
character(len = kchara) function set_parallel_file_name::add_elaps_postfix (character(len=kchara), intent(in) file_head)
Definition at line 140 of file set_parallel_file_name.f90.
Referenced by input_old_file_sel_4_zlib::sel_read_rst_comps(), input_old_file_sel_4_zlib::sel_read_rst_file(), set_field_file_names::set_fem_fld_file_name(), and set_field_file_names::set_sph_fld_file_name().
add_gzip_extension()
character(len = kchara) function set_parallel_file_name::add_gzip_extension (character(len=kchara), intent(in) file_head)
Definition at line 151 of file set_parallel_file_name.f90.
References add_2chara_extension(), and gz_ext.
Referenced by delete_data_files::delete_parallel_files(), gz_mpi_viewer_mesh_file_io::gz_mpi_write_viewer_mesh_file(), gz_rst_data_io_by_fld::read_gz_rst_comps(), gz_rst_data_io_by_fld::read_gz_rst_file(), set_field_file_names::set_fem_fld_file_name(), set_mesh_file_names::set_mesh_file_name(), set_ucd_file_names::set_parallel_grd_file_name(), set_ucd_file_names::set_parallel_ucd_file_name(), set_ucd_file_names::set_single_grd_file_name(), set_ucd_file_names::set_single_ucd_file_name(), set_field_file_names::set_sph_fld_file_name(), and gz_vtk_file_io::write_gz_parallel_vtk_file().
add_index_after_name()
subroutine set_parallel_file_name::add_index_after_name (integer(kind = kint), intent(in) int_id, character(len=kchara), intent(in) chara_head, character(len=kchara), intent(inout) chara_name)
Definition at line 227 of file set_parallel_file_name.f90.
Referenced by add_int_suffix(), pickup_gauss_coefficients::set_gauss_coefs_labels(), t_control_1d_layering::set_group_by_equidivide(), and t_control_1d_layering::set_group_by_layering_list().
add_int_suffix()
character(len = kchara) function set_parallel_file_name::add_int_suffix (integer(kind = kint), intent(in) int_id, character(len=kchara), intent(in) file_head)
Definition at line 109 of file set_parallel_file_name.f90.
References add_index_after_name().
Referenced by add_process_id(), input_old_file_sel_4_zlib::sel_read_rst_comps(), input_old_file_sel_4_zlib::sel_read_rst_file(), set_field_file_names::set_fem_fld_file_name(), set_ucd_file_names::set_merged_hdf_field_file_name(), set_ucd_file_names::set_merged_snap_xdmf_file_name(), set_ucd_file_names::set_parallel_grd_file_name(), set_ucd_file_names::set_parallel_ucd_file_name(), set_ucd_file_names::set_parallel_vtk_file_name(), set_ucd_file_names::set_single_grd_file_name(), set_ucd_file_names::set_single_ucd_file_name(), set_field_file_names::set_sph_fld_file_name(), gz_vtk_file_io::write_gz_parallel_vtk_file(), and vtk_file_io::write_parallel_vtk_file().
add_left_label()
character(len=kchara) function set_parallel_file_name::add_left_label (character(len=kchara), intent(in) file_head)
Definition at line 200 of file set_parallel_file_name.f90.
add_null_character()
character(len = kchara) function set_parallel_file_name::add_null_character (character(len=kchara), intent(in) file_head)
Definition at line 161 of file set_parallel_file_name.f90.
Referenced by gzip_file_access::open_ad_gzfile_f(), binary_file_access::open_ad_rawfile_f(), gzip_file_access::open_rd_gzfile_f(), binary_file_access::open_rd_rawfile_f(), gzip_file_access::open_wt_gzfile_f(), and binary_file_access::open_wt_rawfile_f().
add_process_id()
character(len = kchara) function set_parallel_file_name::add_process_id (integer, intent(in) id_rank, character(len=kchara), intent(in) file_head)
Definition at line 93 of file set_parallel_file_name.f90.
References add_int_suffix().
Referenced by add_comm_table_in_node_grp::add_comm_table_in_node_group(), analyzer_test_sph::analyze_test_sph(), delete_data_files::delete_parallel_files(), node_monitor_io::open_node_monitor_file(), t_work_time::output_elapsed_log(), viewer_file_io::sel_output_single_surface_grid(), input_old_file_sel_4_zlib::sel_read_rst_comps(), input_old_file_sel_4_zlib::sel_read_rst_file(), set_field_file_names::set_fem_fld_file_name(), set_mesh_file_names::set_mesh_file_name(), set_ucd_file_names::set_parallel_grd_file_name(), set_ucd_file_names::set_parallel_ucd_file_name(), set_ucd_file_names::set_parallel_vtk_file_name(), set_field_file_names::set_sph_fld_file_name(), mesh_file_io::write_node_position_cyl(), and mesh_file_io::write_node_position_sph().
add_right_label()
character(len=kchara) function set_parallel_file_name::add_right_label (character(len=kchara), intent(in) file_head)
Definition at line 213 of file set_parallel_file_name.f90.
delete_directory_name()
character(len = kchara) function set_parallel_file_name::delete_directory_name (character(len=kchara), intent(in) dir_file_name)
Definition at line 65 of file set_parallel_file_name.f90.
Referenced by hdf5_file_io::parallel_write_xdmf_file(), gz_vtk_file_io::write_gz_parallel_vtk_file(), and vtk_file_io::write_parallel_vtk_file().
int_to_str()
subroutine set_parallel_file_name::int_to_str (integer(kind=kint), intent(in) int_val, character(len=kchara), intent(inout) int_string)
Definition at line 244 of file set_parallel_file_name.f90.
Referenced by hdf5_file_io::parallel_write_xdmf_file().
lint_to_str()
subroutine set_parallel_file_name::lint_to_str (integer(kind=kint_gl), intent(in) lint_val, character(len=kchara), intent(inout) int_string)
Definition at line 258 of file set_parallel_file_name.f90.
Referenced by hdf5_file_io::parallel_write_xdmf_file().
real_to_str()
subroutine set_parallel_file_name::real_to_str (real(kind=kreal), intent(in) real_val, character(len=kchara), intent(inout) real_string)
Definition at line 273 of file set_parallel_file_name.f90.
Referenced by hdf5_file_io::parallel_write_xdmf_file().
Variable Documentation
gz_ext
character(len=2), parameter set_parallel_file_name::gz_ext = "gz"
Definition at line 57 of file set_parallel_file_name.f90.
Referenced by add_gzip_extension(), and m_section_file_extensions::set_psf_extensions().