CALYPSO: set_sph_exp_nod_center Module Reference
set_sph_exp_nod_center Module Reference
Evaluate field approaching to center.
Functions/Subroutines
subroutine sph_center_fld_and_curl (nri, jmax, a2r_k1, g_sph_rj, d1nod_mat_fdm_2, d2nod_mat_fdm_2, is_fld, is_rot, n_point, ntot_phys_rj, d_rj)
subroutine cal_dsdr_sph_center_2 (nri, jmax, d1nod_mat_fdm_2, is_fld, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_nod_center_rot2 (nri, jmax, a2r_k1, g_sph_rj, d1nod_mat_fdm_2, d2nod_mat_fdm_2, is_fld, is_rot, n_point, ntot_phys_rj, d_rj)
subroutine cal_sph_nod_center_diffuse2 (nri, jmax, a2r_k1, g_sph_rj, d2nod_mat_fdm_2, coef_d, is_fld, is_diffuse, n_point, ntot_phys_rj, d_rj)
Detailed Description
Evaluate field approaching to center.
      subroutine sph_center_fld_and_curl(nri, jmax, a2r_k1, g_sph_rj, &
     &          d1nod_mat_fdm_2, d2nod_mat_fdm_2, is_fld, is_rot,     &
     &          n_point, ntot_phys_rj, d_rj)
      subroutine cal_dsdr_sph_center_2(nri, jmax, d1nod_mat_fdm_2,    &
     &          is_fld,  n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_nod_center_rot2(nri, jmax, a2r_k1, g_sph_rj, &
     &          d1nod_mat_fdm_2, d2nod_mat_fdm_2, is_fld, is_rot,     &
     &          n_point, ntot_phys_rj, d_rj)
      subroutine cal_sph_nod_center_diffuse2 (nri, jmax, a2r_k1,      &
     &          g_sph_rj, d2nod_mat_fdm_2, coef_d, is_fld, is_diffuse,&
     &          n_point, ntot_phys_rj, d_rj)
Parameters
n_point Number of points for spectrum data
coef_d Coefficient for diffusion term
is_fld Address of poloidal magnetic field (or velocity) in d_rj
is_rot Address of poloidal currentdensity (or vorticity) in d_rj
is_diffuse Address of poloidal magnetic diffusion (or viscousity) in d_rj
Parameters
ntot_phys_rj Total number of components
d_rj Spectrum data
Function/Subroutine Documentation
cal_dsdr_sph_center_2()
subroutine set_sph_exp_nod_center::cal_dsdr_sph_center_2 (integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(nri,-1:1), intent(in) d1nod_mat_fdm_2, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 91 of file set_sph_exp_nod_center.f90.
References m_constants::ione.
Referenced by select_exp_magne_icb::sel_icb_grad_poloidal_magne(), select_exp_velocity_icb::sel_icb_grad_poloidal_moment(), select_exp_magne_icb::sel_icb_sph_magnetic_diffusion(), select_exp_velocity_icb::sel_icb_sph_viscous_diffusion(), and select_exp_velocity_icb::sel_icb_sph_vort_diffusion().
cal_sph_nod_center_diffuse2()
subroutine set_sph_exp_nod_center::cal_sph_nod_center_diffuse2 (integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, real (kind=kreal), intent(in) a2r_k1, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, real(kind = kreal), dimension(nri,-1:1), intent(in) d2nod_mat_fdm_2, real(kind = kreal), intent(in) coef_d, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_diffuse, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 159 of file set_sph_exp_nod_center.f90.
References m_constants::ione.
Referenced by select_exp_magne_icb::sel_icb_sph_magnetic_diffusion(), select_exp_velocity_icb::sel_icb_sph_viscous_diffusion(), and select_exp_velocity_icb::sel_icb_sph_vort_diffusion().
cal_sph_nod_center_rot2()
subroutine set_sph_exp_nod_center::cal_sph_nod_center_rot2 (integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, real (kind=kreal), intent(in) a2r_k1, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, real(kind = kreal), dimension(nri,-1:1), intent(in) d1nod_mat_fdm_2, real(kind = kreal), dimension(nri,-1:1), intent(in) d2nod_mat_fdm_2, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_rot, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 119 of file set_sph_exp_nod_center.f90.
References m_constants::ione.
Referenced by select_exp_magne_icb::sel_icb_sph_current(), select_exp_magne_icb::sel_icb_sph_rotation_uxb(), and select_exp_velocity_icb::sel_icb_sph_vorticity().
sph_center_fld_and_curl()
subroutine set_sph_exp_nod_center::sph_center_fld_and_curl (integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, real (kind=kreal), intent(in) a2r_k1, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, real(kind = kreal), dimension(nri,-1:1), intent(in) d1nod_mat_fdm_2, real(kind = kreal), dimension(nri,-1:1), intent(in) d2nod_mat_fdm_2, integer(kind = kint), intent(in) is_fld, integer(kind = kint), intent(in) is_rot, integer(kind = kint), intent(in) n_point, integer(kind = kint), intent(in) ntot_phys_rj, real (kind=kreal), dimension(n_point,ntot_phys_rj), intent(inout) d_rj)
Definition at line 48 of file set_sph_exp_nod_center.f90.
References m_constants::ione.
Referenced by select_exp_magne_icb::sel_icb_grad_bp_and_current(), and select_exp_velocity_icb::sel_icb_grad_vp_and_vorticity().