CALYPSO: t_rms_4_sph_spectr Module Reference
t_rms_4_sph_spectr Module Reference
Mean sqare data.
Data Types
type sph_mean_squares
Structure of mean square data.
Functions/Subroutines
subroutine alloc_volume_spectr_data (n_vpower, pwr)
subroutine dealloc_volume_spectr_data (pwr)
subroutine alloc_num_spec_layer (nri_in, pwr)
subroutine alloc_rms_name_sph_spec (nfld_in, pwr)
subroutine alloc_rms_4_sph_spectr (id_rank, ltr, pwr)
subroutine alloc_ave_4_sph_spectr (idx_rj_degree_zero, nri_rj, pwr)
subroutine dealloc_rms_4_sph_spectr (pwr)
subroutine dealloc_ave_4_sph_spectr (idx_rj_degree_zero, pwr)
Detailed Description
Mean sqare data.
      subroutine alloc_volume_spectr_data(n_vpower, pwr)
      subroutine dealloc_volume_spectr_data(pwr)
      subroutine alloc_num_spec_layer(nri_in, pwr)
      subroutine alloc_rms_name_sph_spec(nfld_in, pwr)
      subroutine alloc_rms_4_sph_spectr(id_rank, ltr, pwr)
      subroutine alloc_ave_4_sph_spectr                               &
     &         (idx_rj_degree_zero, nri_rj, pwr)
      subroutine dealloc_rms_4_sph_spectr(pwr)
      subroutine dealloc_ave_4_sph_spectr(idx_rj_degree_zero, pwr)
Parameters
id_rank Process ID
Function/Subroutine Documentation
alloc_ave_4_sph_spectr()
subroutine t_rms_4_sph_spectr::alloc_ave_4_sph_spectr (integer(kind = kint), intent(in) idx_rj_degree_zero, integer(kind = kint), intent(in) nri_rj, type(sph_mean_squares), intent(inout) pwr)
Definition at line 259 of file t_rms_4_sph_spectr.f90.
References t_sph_volume_mean_square::alloc_sph_vol_ave().
Referenced by cal_rms_fields_by_sph::init_rms_4_sph_spectr().
alloc_num_spec_layer()
subroutine t_rms_4_sph_spectr::alloc_num_spec_layer (integer(kind = kint), intent(in) nri_in, type(sph_mean_squares), intent(inout) pwr)
Definition at line 159 of file t_rms_4_sph_spectr.f90.
Referenced by cal_rms_fields_by_sph::init_rms_4_sph_spectr(), and set_control_4_pickup_sph::set_ctl_params_layered_spectr().
alloc_rms_4_sph_spectr()
subroutine t_rms_4_sph_spectr::alloc_rms_4_sph_spectr (integer, intent(in) id_rank, integer(kind = kint), intent(in) ltr, type(sph_mean_squares), intent(inout) pwr)
Definition at line 200 of file t_rms_4_sph_spectr.f90.
References t_sph_volume_mean_square::alloc_sph_vol_mean_square().
Referenced by cal_rms_fields_by_sph::init_rms_4_sph_spectr().
alloc_rms_name_sph_spec()
subroutine t_rms_4_sph_spectr::alloc_rms_name_sph_spec (integer(kind = kint), intent(in) nfld_in, type(sph_mean_squares), intent(inout) pwr)
Definition at line 178 of file t_rms_4_sph_spectr.f90.
Referenced by cal_rms_fields_by_sph::init_rms_4_sph_spectr().
alloc_volume_spectr_data()
subroutine t_rms_4_sph_spectr::alloc_volume_spectr_data (integer(kind = kint), intent(in) n_vpower, type(sph_mean_squares), intent(inout) pwr)
Definition at line 114 of file t_rms_4_sph_spectr.f90.
Referenced by set_control_4_pickup_sph::set_ctl_params_sph_spectr().
dealloc_ave_4_sph_spectr()
subroutine t_rms_4_sph_spectr::dealloc_ave_4_sph_spectr (integer(kind = kint), intent(in) idx_rj_degree_zero, type(sph_mean_squares), intent(inout) pwr)
Definition at line 311 of file t_rms_4_sph_spectr.f90.
References t_sph_volume_mean_square::dealloc_sph_vol_ave().
dealloc_rms_4_sph_spectr()
subroutine t_rms_4_sph_spectr::dealloc_rms_4_sph_spectr (type(sph_mean_squares), intent(inout) pwr)
Definition at line 283 of file t_rms_4_sph_spectr.f90.
References t_sph_volume_mean_square::dealloc_sph_vol_mean_square().
dealloc_volume_spectr_data()
subroutine t_rms_4_sph_spectr::dealloc_volume_spectr_data (type(sph_mean_squares), intent(inout) pwr)
Definition at line 149 of file t_rms_4_sph_spectr.f90.