CALYPSO: mesh_mpi_io_select Module Reference
mesh_mpi_io_select Module Reference
Choose mesh file to read.
Functions/Subroutines
subroutine sel_mpi_read_mesh (num_pe, id_rank, mesh_file, mesh_IO, group_IO)
subroutine sel_mpi_read_mesh_geometry (num_pe, id_rank, mesh_file, mesh_IO)
subroutine sel_mpi_read_node_size (num_pe, id_rank, mesh_file, mesh_IO)
subroutine sel_mpi_read_geometry_size (num_pe, id_rank, mesh_file, mesh_IO)
subroutine sel_mpi_write_mesh_file (mesh_file, mesh_IO, group_IO)
Variables
character(len=kchara), private file_name
Detailed Description
Choose mesh file to read.
      subroutine sel_mpi_read_mesh                                    &
     &         (num_pe, id_rank, mesh_file, mesh_IO, group_IO)
        type(field_IO_params), intent(in) ::  mesh_file
        type(mesh_geometry), intent(inout) :: mesh_IO
        type(mesh_groups), intent(inout) ::   group_IO
      subroutine sel_mpi_read_mesh_geometry                           &
     &         (num_pe, id_rank, mesh_file, mesh_IO)
      subroutine sel_mpi_read_node_size                               &
     &         (num_pe, id_rank, mesh_file, mesh_IO)
       subroutine sel_mpi_read_geometry_size                          &
     &         (num_pe, id_rank, mesh_file, mesh_IO)
        type(field_IO_params), intent(in) ::  mesh_file
        type(mesh_geometry), intent(inout) :: mesh_IO
      subroutine sel_mpi_write_mesh_file                              &
     &         (mesh_file, mesh_IO, group_IO)
        type(field_IO_params), intent(in) ::  mesh_file
        type(mesh_geometry), intent(in) :: mesh_IO
        type(mesh_groups), intent(in) ::   group_IO
Function/Subroutine Documentation
sel_mpi_read_geometry_size()
subroutine mesh_mpi_io_select::sel_mpi_read_geometry_size (integer, intent(in) num_pe, integer, intent(in) id_rank, type(field_io_params), intent(in) mesh_file, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 202 of file mesh_MPI_IO_select.F90.
References calypso_mpi::calypso_mpi_abort(), file_name, gz_mpi_mesh_file_io::gz_mpi_read_geometry_size(), gz_mpi_mesh_file_io_b::gz_mpi_read_geometry_size_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, m_file_format_switch::iflag_single, mpi_mesh_file_io::mpi_read_geometry_size(), mpi_mesh_file_io_b::mpi_read_geometry_size_b(), mesh_io_select::sel_read_geometry_size(), and set_mesh_file_names::set_mesh_file_name().
Referenced by mpi_load_mesh_data::mpi_input_node_geometry().
sel_mpi_read_mesh()
subroutine mesh_mpi_io_select::sel_mpi_read_mesh (integer, intent(in) num_pe, integer, intent(in) id_rank, type(field_io_params), intent(in) mesh_file, type(mesh_geometry), intent(inout) mesh_IO, type(mesh_groups), intent(inout) group_IO)
Definition at line 63 of file mesh_MPI_IO_select.F90.
References calypso_mpi::calypso_mpi_abort(), file_name, gz_mpi_mesh_file_io::gz_mpi_read_mesh(), gz_mpi_mesh_file_io_b::gz_mpi_read_mesh_file_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, m_file_format_switch::iflag_single, mpi_mesh_file_io::mpi_read_mesh_file(), mpi_mesh_file_io_b::mpi_read_mesh_file_b(), mesh_io_select::sel_read_mesh(), and set_mesh_file_names::set_mesh_file_name().
Referenced by mpi_load_mesh_data::mpi_input_mesh().
sel_mpi_read_mesh_geometry()
subroutine mesh_mpi_io_select::sel_mpi_read_mesh_geometry (integer, intent(in) num_pe, integer, intent(in) id_rank, type(field_io_params), intent(in) mesh_file, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 111 of file mesh_MPI_IO_select.F90.
References calypso_mpi::calypso_mpi_abort(), file_name, gz_mpi_mesh_file_io::gz_mpi_read_mesh_geometry(), gz_mpi_mesh_file_io_b::gz_mpi_read_mesh_geometry_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, m_file_format_switch::iflag_single, mpi_mesh_file_io::mpi_read_mesh_geometry(), mpi_mesh_file_io_b::mpi_read_mesh_geometry_b(), mesh_io_select::sel_read_mesh_geometry(), and set_mesh_file_names::set_mesh_file_name().
Referenced by mpi_load_mesh_data::mpi_input_mesh_geometry().
sel_mpi_read_node_size()
subroutine mesh_mpi_io_select::sel_mpi_read_node_size (integer, intent(in) num_pe, integer, intent(in) id_rank, type(field_io_params), intent(in) mesh_file, type(mesh_geometry), intent(inout) mesh_IO)
Definition at line 157 of file mesh_MPI_IO_select.F90.
References calypso_mpi::calypso_mpi_abort(), file_name, gz_mpi_mesh_file_io::gz_mpi_read_node_size(), gz_mpi_mesh_file_io_b::gz_mpi_read_node_size_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, m_file_format_switch::iflag_single, mpi_mesh_file_io::mpi_read_node_size(), mpi_mesh_file_io_b::mpi_read_node_size_b(), mesh_io_select::sel_read_node_size(), and set_mesh_file_names::set_mesh_file_name().
sel_mpi_write_mesh_file()
subroutine mesh_mpi_io_select::sel_mpi_write_mesh_file (type(field_io_params), intent(in) mesh_file, type(mesh_geometry), intent(in) mesh_IO, type(mesh_groups), intent(in) group_IO)
Definition at line 249 of file mesh_MPI_IO_select.F90.
References file_name, gz_mpi_mesh_file_io::gz_mpi_write_mesh_file(), gz_mpi_mesh_file_io_b::gz_mpi_write_mesh_file_b(), m_file_format_switch::id_binary_file_fmt, m_file_format_switch::id_gzip_bin_file_fmt, m_file_format_switch::id_gzip_txt_file_fmt, m_file_format_switch::iflag_single, mpi_mesh_file_io::mpi_write_mesh_file(), mpi_mesh_file_io_b::mpi_write_mesh_file_b(), calypso_mpi::my_rank, calypso_mpi::nprocs, mesh_io_select::sel_write_mesh_file(), and set_mesh_file_names::set_mesh_file_name().
Referenced by mpi_load_mesh_data::mpi_output_mesh().
Variable Documentation
file_name
character(len=kchara), private mesh_mpi_io_select::file_name private
Definition at line 55 of file mesh_MPI_IO_select.F90.
Referenced by sel_mpi_read_geometry_size(), sel_mpi_read_mesh(), sel_mpi_read_mesh_geometry(), sel_mpi_read_node_size(), and sel_mpi_write_mesh_file().