CALYPSO: set_nodes_for_psf Module Reference
set_nodes_for_psf Module Reference
Check node positions to generate sections.
Functions/Subroutines
subroutine count_nodes_4_psf (num_psf, node, edge, sf_grp, sf_grp_nod, psf_def, psf_search, psf_list, psf_grp_list, psf_mesh)
subroutine count_nodes_4_iso (num_iso, edge, iso_search, iso_list, iso_mesh)
subroutine set_nodes_4_psf (num_psf, node, edge, nod_comm, sf_grp, sf_grp_nod, psf_def, psf_search, psf_list, psf_grp_list, psf_mesh)
subroutine set_nodes_4_iso (num_iso, node, edge, nod_comm, iso_search, iso_list, iso_mesh)
Detailed Description
Check node positions to generate sections.
      subroutine count_nodes_4_psf                                    &
     &         (num_psf, node, edge, sf_grp, sf_grp_nod,              &
     &          psf_def, psf_search, psf_list, psf_grp_list, psf_mesh)
        type(node_data), intent(in) :: node
        type(edge_data), intent(in) :: edge
        type(surface_group_data), intent(in) :: sf_grp
        type(surface_node_grp_data), intent(in) :: sf_grp_nod
        type(section_define), intent(in) :: psf_def(num_psf)
        type(psf_search_lists), intent(in) :: psf_search(num_psf)
        type(sectioning_list), intent(inout) :: psf_list(num_psf)
        type(grp_section_list), intent(inout) :: psf_grp_list(num_psf)
        type(psf_local_data), intent(inout) :: psf_mesh(num_psf)
      subroutine count_nodes_4_iso                                    &
     &         (num_iso, edge, iso_search, iso_list, iso_mesh)
        type(edge_data), intent(in) :: edge
        type(psf_search_lists), intent(inout) :: iso_search(num_iso)
        type(sectioning_list), intent(inout) :: iso_list(num_iso)
        type(psf_local_data), intent(inout) :: iso_mesh(num_iso)
      subroutine set_nodes_4_psf(num_psf, node, edge, nod_comm,       &
      &         sf_grp, sf_grp_nod, psf_def, psf_search,              &
      &         psf_list, psf_grp_list, psf_mesh)
        type(node_data), intent(in) :: node
        type(edge_data), intent(in) :: edge
        type(surface_group_data), intent(in) :: sf_grp
        type(surface_node_grp_data), intent(in) :: sf_grp_nod
        type(communication_table), intent(in) :: nod_comm
        type(section_define), intent(in) :: psf_def(num_psf)
        type(psf_search_lists), intent(in) :: psf_search(num_psf)
        type(sectioning_list), intent(inout) :: psf_list(num_psf)
        type(grp_section_list), intent(inout) :: psf_grp_list(num_psf)
        type(psf_local_data), intent(inout) :: psf_mesh(num_psf)
      subroutine set_nodes_4_iso(num_iso, node, edge, nod_comm,       &
     &          iso_search, iso_list, iso_mesh)
        type(node_data), intent(in) :: node
        type(edge_data), intent(in) :: edge
        type(communication_table), intent(in) :: nod_comm
        type(psf_search_lists), intent(in) :: iso_search(num_iso)
        type(sectioning_list), intent(inout) :: iso_list(num_iso)
        type(psf_local_data), intent(inout) :: iso_mesh(num_iso)
Function/Subroutine Documentation
count_nodes_4_iso()
subroutine set_nodes_for_psf::count_nodes_4_iso (integer(kind = kint), intent(in) num_iso, type(edge_data), intent(in) edge, type(psf_search_lists), dimension(num_iso), intent(inout) iso_search, type(sectioning_list), dimension(num_iso), intent(inout) iso_list, type(psf_local_data), dimension(num_iso), intent(inout) iso_mesh)
Definition at line 124 of file set_nodes_for_psf.f90.
References t_psf_geometry_list::alloc_nnod_psf(), set_node_for_sections::count_node_on_edge_4_psf(), set_nodal_field_for_psf::count_position_4_psf(), and m_machine_parameter::np_smp.
Referenced by find_node_and_patch_psf::set_node_and_patch_iso().
count_nodes_4_psf()
subroutine set_nodes_for_psf::count_nodes_4_psf (integer(kind = kint), intent(in) num_psf, type(node_data), intent(in) node, type(edge_data), intent(in) edge, type(surface_group_data), intent(in) sf_grp, type(surface_node_grp_data), intent(in) sf_grp_nod, type(section_define), dimension(num_psf), intent(in) psf_def, type(psf_search_lists), dimension(num_psf), intent(in) psf_search, type(sectioning_list), dimension(num_psf), intent(inout) psf_list, type(grp_section_list), dimension(num_psf), intent(inout) psf_grp_list, type(psf_local_data), dimension(num_psf), intent(inout) psf_mesh)
Definition at line 68 of file set_nodes_for_psf.f90.
References set_psf_nodes_4_by_surf_grp::count_node_at_node_on_grp(), set_node_for_sections::count_node_on_edge_4_psf(), set_nodal_field_for_psf::count_position_4_psf(), and set_psf_nodes_4_by_surf_grp::count_position_4_psf_grp().
Referenced by find_node_and_patch_psf::set_node_and_patch_psf().
set_nodes_4_iso()
subroutine set_nodes_for_psf::set_nodes_4_iso (integer(kind = kint), intent(in) num_iso, type(node_data), intent(in) node, type(edge_data), intent(in) edge, type(communication_table), intent(in) nod_comm, type(psf_search_lists), dimension(num_iso), intent(in) iso_search, type(sectioning_list), dimension(num_iso), intent(inout) iso_list, type(psf_local_data), dimension(num_iso), intent(inout) iso_mesh)
Definition at line 247 of file set_nodes_for_psf.f90.
References t_psf_geometry_list::alloc_iedge_global_psf(), t_psf_geometry_list::alloc_inod_psf(), t_geometry_data::alloc_node_geometry_w_sph(), psf_global_nod_id::const_edge_comm_table_4_psf(), const_element_comm_tables::const_global_numnod_list(), t_psf_geometry_list::dealloc_iedge_global_psf(), calypso_mpi::my_rank, psf_global_nod_id::psf_global_nod_id_on_edge(), set_node_for_sections::set_node_on_edge_4_psf(), set_node_on_edge_quad_psf::set_node_on_edge_int_linear_psf(), set_nodal_field_for_psf::set_position_4_psf(), and cal_mesh_position::set_spherical_position().
Referenced by find_node_and_patch_psf::set_node_and_patch_iso().
set_nodes_4_psf()
subroutine set_nodes_for_psf::set_nodes_4_psf (integer(kind = kint), intent(in) num_psf, type(node_data), intent(in) node, type(edge_data), intent(in) edge, type(communication_table), intent(in) nod_comm, type(surface_group_data), intent(in) sf_grp, type(surface_node_grp_data), intent(in) sf_grp_nod, type(section_define), dimension(num_psf), intent(in) psf_def, type(psf_search_lists), dimension(num_psf), intent(in) psf_search, type(sectioning_list), dimension(num_psf), intent(inout) psf_list, type(grp_section_list), dimension(num_psf), intent(inout) psf_grp_list, type(psf_local_data), dimension(num_psf), intent(inout) psf_mesh)
Definition at line 155 of file set_nodes_for_psf.f90.
References t_psf_geometry_list::alloc_iedge_global_psf(), psf_global_nod_id::const_edge_comm_table_4_psf(), t_psf_geometry_list::dealloc_iedge_global_psf(), calypso_mpi::my_rank, psf_global_nod_id::psf_global_nod_id_on_edge(), psf_global_nod_id::psf_global_nod_id_on_node(), set_psf_nodes_4_by_surf_grp::set_node_at_node_on_grp(), set_node_for_sections::set_node_on_edge_4_psf(), set_node_on_edge_quad_psf::set_node_on_edge_int_quad_psf(), set_nodal_field_for_psf::set_position_4_psf(), set_psf_nodes_4_by_surf_grp::set_position_psf_grp(), and cal_mesh_position::set_spherical_position().
Referenced by find_node_and_patch_psf::set_node_and_patch_psf().