CALYPSO: renumber_surface_4_viewer Module Reference
renumber_surface_4_viewer Module Reference
Functions/Subroutines
subroutine set_surf_domain_stack_viewer (nsurf_viewer, domain_surf_grp)
subroutine set_element_group_stack_viewer (nsurf_viewer, mgd_sf_grp, ngrp_ele_sf, ele_surf_grp)
subroutine set_surface_group_stack_viewer (nsurf_viewer, merged_grp, ngrp_surf_sf, sf_surf_grp)
subroutine set_node_group_stack_viewer (nnod_viewer, merged_grp, ngrp_nod_sf, nod_nod_grp)
Function/Subroutine Documentation
set_element_group_stack_viewer()
subroutine renumber_surface_4_viewer::set_element_group_stack_viewer (integer(kind = kint), intent(in) nsurf_viewer, type(viewer_ele_grp_surface), intent(in) mgd_sf_grp, integer(kind = kint), intent(in) ngrp_ele_sf, type(viewer_group_data), intent(inout) ele_surf_grp)
Definition at line 57 of file renumber_surface_4_viewer.f90.
Referenced by set_surf_connect_4_viewer::s_set_groups_4_viewer_surface().
set_node_group_stack_viewer()
subroutine renumber_surface_4_viewer::set_node_group_stack_viewer (integer(kind = kint), intent(in) nnod_viewer, type(mesh_groups), intent(in) merged_grp, integer(kind = kint), intent(in) ngrp_nod_sf, type(viewer_group_data), intent(inout) nod_nod_grp)
Definition at line 116 of file renumber_surface_4_viewer.f90.
Referenced by set_nodes_4_viewer::s_set_nod_grp_4_viewer_surface().
set_surf_domain_stack_viewer()
subroutine renumber_surface_4_viewer::set_surf_domain_stack_viewer (integer(kind = kint), intent(in) nsurf_viewer, type(viewer_group_data), intent(inout) domain_surf_grp)
Definition at line 37 of file renumber_surface_4_viewer.f90.
Referenced by set_surf_connect_4_viewer::s_set_groups_4_viewer_surface().
set_surface_group_stack_viewer()
subroutine renumber_surface_4_viewer::set_surface_group_stack_viewer (integer(kind = kint), intent(in) nsurf_viewer, type(mesh_groups), intent(in) merged_grp, integer(kind = kint), intent(in) ngrp_surf_sf, type(viewer_group_data), intent(inout) sf_surf_grp)
Definition at line 85 of file renumber_surface_4_viewer.f90.
Referenced by set_surf_connect_4_viewer::s_set_groups_4_viewer_surface().