CALYPSO: write_ucd_to_vtk_file Module Reference
write_ucd_to_vtk_file Module Reference
Output FEM field data to distributed VTK file.
Functions/Subroutines
subroutine write_parallel_vtk_file (id_rank, nprocs, istep, file_prefix)
subroutine write_udt_data_2_vtk_file (id_rank, file_name, ucd)
subroutine write_udt_data_2_vtk_phys (id_rank, file_name, ucd)
subroutine write_udt_data_2_vtk_grid (id_rank, file_name, ucd)
subroutine read_udt_data_2_vtk_file (id_rank, file_name, ucd)
subroutine read_udt_data_2_vtk_phys (id_rank, file_name, ucd)
subroutine read_udt_data_2_vtk_grid (id_rank, file_name, ucd)
subroutine, private read_ucd_mesh_by_vtk (ucd)
subroutine, private read_ucd_field_by_vtk (ucd)
Variables
integer(kind=kint), parameter, private id_vtk_file = 16
file ID for VTK file
Detailed Description
Output FEM field data to distributed VTK file.
      subroutine write_parallel_vtk_file                              &
     &         (id_rank, nprocs, istep, file_prefix)
      subroutine write_udt_data_2_vtk_file(id_rank, file_name, ucd)
      subroutine write_udt_data_2_vtk_phys(id_rank, file_name, ucd)
      subroutine write_udt_data_2_vtk_grid(id_rank, file_name, ucd)
      subroutine read_udt_data_2_vtk_file(id_rank, file_name, ucd)
      subroutine read_udt_data_2_vtk_phys(id_rank, file_name, ucd)
      subroutine read_udt_data_2_vtk_grid(id_rank, file_name, ucd)
        type(ucd_data), intent(inout) :: ucd
Parameters
id_rank subdomain ID
file_name File name
ucd Structure for FEM field data IO
Function/Subroutine Documentation
read_ucd_field_by_vtk()
subroutine, private write_ucd_to_vtk_file::read_ucd_field_by_vtk (type(ucd_data), intent(inout) ucd) private
Definition at line 245 of file write_ucd_to_vtk_file.f90.
References t_ucd_data::allocate_ucd_phys_data(), t_ucd_data::allocate_ucd_phys_name(), t_ucd_data::append_new_ucd_field_data(), t_ucd_data::append_new_ucd_field_name(), t_ucd_data::deallocate_ucd_data(), id_vtk_file, m_constants::izero, vtk_data_io::read_vtk_each_field(), vtk_data_io::read_vtk_each_field_head(), and vtk_data_io::read_vtk_fields_head().
Referenced by read_udt_data_2_vtk_file(), and read_udt_data_2_vtk_phys().
read_ucd_mesh_by_vtk()
subroutine, private write_ucd_to_vtk_file::read_ucd_mesh_by_vtk (type(ucd_data), intent(inout) ucd) private
Definition at line 211 of file write_ucd_to_vtk_file.f90.
References t_ucd_data::allocate_ucd_ele(), t_ucd_data::allocate_ucd_node(), id_vtk_file, m_constants::ithree, vtk_data_io::read_vtk_cell_type(), vtk_data_io::read_vtk_connect_data(), vtk_data_io::read_vtk_connect_head(), vtk_data_io::read_vtk_each_field(), and vtk_data_io::read_vtk_node_head().
Referenced by read_udt_data_2_vtk_file(), and read_udt_data_2_vtk_grid().
read_udt_data_2_vtk_file()
subroutine write_ucd_to_vtk_file::read_udt_data_2_vtk_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(ucd_data), intent(inout) ucd)
Definition at line 151 of file write_ucd_to_vtk_file.f90.
References m_machine_parameter::i_debug, id_vtk_file, read_ucd_field_by_vtk(), and read_ucd_mesh_by_vtk().
Referenced by ucd_io_select::sel_read_ucd_file().
read_udt_data_2_vtk_grid()
subroutine write_ucd_to_vtk_file::read_udt_data_2_vtk_grid (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(ucd_data), intent(inout) ucd)
Definition at line 191 of file write_ucd_to_vtk_file.f90.
References m_machine_parameter::i_debug, id_vtk_file, and read_ucd_mesh_by_vtk().
read_udt_data_2_vtk_phys()
subroutine write_ucd_to_vtk_file::read_udt_data_2_vtk_phys (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(ucd_data), intent(inout) ucd)
Definition at line 171 of file write_ucd_to_vtk_file.f90.
References m_machine_parameter::i_debug, id_vtk_file, and read_ucd_field_by_vtk().
Referenced by ucd_io_select::sel_read_alloc_udt_file().
write_parallel_vtk_file()
subroutine write_ucd_to_vtk_file::write_parallel_vtk_file (integer, intent(in) id_rank, integer, intent(in) nprocs, integer(kind = kint), intent(in) istep, character(len=kchara), intent(in) file_prefix)
Definition at line 52 of file write_ucd_to_vtk_file.f90.
References set_parallel_file_name::add_int_suffix(), set_ucd_extensions::add_pvtk_extension(), set_parallel_file_name::delete_directory_name(), id_vtk_file, m_field_file_format::iflag_vtk, and set_ucd_file_names::set_parallel_ucd_file_name().
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_file().
write_udt_data_2_vtk_file()
subroutine write_ucd_to_vtk_file::write_udt_data_2_vtk_file (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(ucd_data), intent(in) ucd)
Definition at line 96 of file write_ucd_to_vtk_file.f90.
References m_machine_parameter::i_debug, id_vtk_file, and vtk_file_io::write_vtk_file().
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_file(), ucd_io_select::sel_write_ucd_file(), and ucd_io_select::sel_write_udt_file().
write_udt_data_2_vtk_grid()
subroutine write_ucd_to_vtk_file::write_udt_data_2_vtk_grid (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(ucd_data), intent(in) ucd)
Definition at line 132 of file write_ucd_to_vtk_file.f90.
References m_machine_parameter::i_debug, id_vtk_file, and vtk_file_io::write_vtk_grid().
Referenced by ucd_io_select::sel_write_grd_file().
write_udt_data_2_vtk_phys()
subroutine write_ucd_to_vtk_file::write_udt_data_2_vtk_phys (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(ucd_data), intent(in) ucd)
Definition at line 114 of file write_ucd_to_vtk_file.f90.
References m_machine_parameter::i_debug, id_vtk_file, and vtk_file_io::write_vtk_phys().
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_file(), ucd_io_select::sel_write_ucd_file(), and ucd_io_select::sel_write_udt_file().
Variable Documentation
id_vtk_file
integer(kind = kint), parameter, private write_ucd_to_vtk_file::id_vtk_file = 16 private
file ID for VTK file
Definition at line 42 of file write_ucd_to_vtk_file.f90.
Referenced by read_ucd_field_by_vtk(), read_ucd_mesh_by_vtk(), read_udt_data_2_vtk_file(), read_udt_data_2_vtk_grid(), read_udt_data_2_vtk_phys(), write_parallel_vtk_file(), write_udt_data_2_vtk_file(), write_udt_data_2_vtk_grid(), and write_udt_data_2_vtk_phys().