CALYPSO: zlib_cvt_ucd_data Module Reference
zlib_cvt_ucd_data Module Reference
Output merged VTK file usgin MPI-IO.
Functions/Subroutines
subroutine defleate_ucd_vector (nnod, num, ntot_comp, vect, istack_merged_intnod, zbuf)
subroutine defleate_ucd_connect (nele, ie, nnod_ele, istack_merged_ele, zbuf)
Detailed Description
Output merged VTK file usgin MPI-IO.
      subroutine defleate_ucd_vector(nnod, num, ntot_comp, vect,      &
     &          istack_merged_intnod, zbuf)
      subroutine defleate_ucd_connect                                 &
     &         (nele, ie, nnod_ele, istack_merged_ele, zbuf)
        type(buffer_4_gzip), intent(inout) :: zbuf
Function/Subroutine Documentation
defleate_ucd_connect()
subroutine zlib_cvt_ucd_data::defleate_ucd_connect (integer(kind = kint_gl), intent(in) nele, integer(kind = kint_gl), dimension(nele,nnod_ele), intent(in) ie, integer(kind = kint), intent(in) nnod_ele, integer(kind = kint_gl), intent(in) istack_merged_ele, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 104 of file zlib_cvt_ucd_data.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), gzip_defleate::gzip_defleat_char_begin(), gzip_defleate::gzip_defleat_char_cont(), gzip_defleate::gzip_defleat_char_last(), gzip_defleate::gzip_defleat_char_once(), m_constants::huge_30, and ucd_data_to_buffer::ucd_each_connect().
Referenced by gz_ucd_file_mpi_io::gz_write_ucd_mesh_mpi().
defleate_ucd_vector()
subroutine zlib_cvt_ucd_data::defleate_ucd_vector (integer(kind = kint_gl), intent(in) nnod, integer(kind = kint_gl), intent(in) num, integer(kind=kint), intent(in) ntot_comp, real(kind = kreal), dimension(nnod,ntot_comp), intent(in) vect, integer(kind = kint_gl), intent(in) istack_merged_intnod, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 34 of file zlib_cvt_ucd_data.f90.
References t_buffer_4_gzip::alloc_zip_buffer(), gzip_defleate::gzip_defleat_char_begin(), gzip_defleate::gzip_defleat_char_cont(), gzip_defleate::gzip_defleat_char_last(), gzip_defleate::gzip_defleat_char_once(), m_constants::huge_30, ucd_data_to_buffer::ucd_each_field(), and m_constants::zero.
Referenced by gz_ucd_file_mpi_io::gz_write_ucd_vecotr_mpi().