CALYPSO: gz_mpi_element_file_io_b Module Reference
gz_mpi_element_file_io_b Module Reference
File IO for element communication table.
Functions/Subroutines
subroutine gz_mpi_input_element_file_b (num_pe, id_rank, file_name, ele_mesh_IO, ierr)
subroutine gz_mpi_input_surface_file_b (num_pe, id_rank, file_name, surf_mesh_IO, ierr)
subroutine gz_mpi_input_edge_file_b (num_pe, id_rank, file_name, edge_mesh_IO, ierr)
subroutine gz_mpi_output_element_file_b (file_name, ele_mesh_IO)
subroutine gz_mpi_output_surface_file_b (file_name, surf_mesh_IO)
subroutine gz_mpi_output_edge_file_b (file_name, edge_mesh_IO)
Variables
type(calypso_mpi_io_params), save, private io_param
Detailed Description
File IO for element communication table.
      subroutine gz_mpi_input_element_file_b                          &
     &         (num_pe, id_rank, file_name, ele_mesh_IO, ierr)
      subroutine gz_mpi_input_surface_file_b                          &
     &         (num_pe, id_rank, file_name, surf_mesh_IO, ierr)
      subroutine gz_mpi_input_edge_file_b                             &
     &         (num_pe, id_rank, file_name, edge_mesh_IO, ierr)
        type(surf_edge_IO_file), intent(in) :: ele_mesh_IO
        type(surf_edge_IO_file), intent(in) :: surf_mesh_IO
        type(surf_edge_IO_file), intent(in) :: edge_mesh_IO
      subroutine gz_mpi_output_element_file_b(file_name, ele_mesh_IO)
      subroutine gz_mpi_output_surface_file_b(file_name, surf_mesh_IO)
      subroutine gz_mpi_output_edge_file_b(file_name, edge_mesh_IO)
        type(surf_edge_IO_file), intent(inout) :: ele_mesh_IO
        type(surf_edge_IO_file), intent(inout) :: surf_mesh_IO
        type(surf_edge_IO_file), intent(inout) :: edge_mesh_IO
Parameters
id_rank MPI rank
Function/Subroutine Documentation
gz_mpi_input_edge_file_b()
subroutine gz_mpi_element_file_io_b::gz_mpi_input_edge_file_b (integer, intent(in) num_pe, integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(inout) edge_mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 104 of file gz_MPI_element_file_IO_b.f90.
References gz_mpi_edge_data_io_b::gz_mpi_read_edge_connect_b(), m_machine_parameter::i_debug, and io_param.
Referenced by element_mesh_mpi_io_select::sel_mpi_read_edge_mesh().
gz_mpi_input_element_file_b()
subroutine gz_mpi_element_file_io_b::gz_mpi_input_element_file_b (integer, intent(in) num_pe, integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(inout) ele_mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 49 of file gz_MPI_element_file_IO_b.f90.
References gz_mpi_element_data_io_b::gz_mpi_read_ele_comm_table_b(), m_machine_parameter::i_debug, and io_param.
Referenced by element_mesh_mpi_io_select::sel_mpi_read_ele_mesh().
gz_mpi_input_surface_file_b()
subroutine gz_mpi_element_file_io_b::gz_mpi_input_surface_file_b (integer, intent(in) num_pe, integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(inout) surf_mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 76 of file gz_MPI_element_file_IO_b.f90.
References gz_mpi_surface_data_io_b::gz_mpi_read_surf_connect_b(), m_machine_parameter::i_debug, and io_param.
Referenced by element_mesh_mpi_io_select::sel_mpi_read_surf_mesh().
gz_mpi_output_edge_file_b()
subroutine gz_mpi_element_file_io_b::gz_mpi_output_edge_file_b (character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(in) edge_mesh_IO)
Definition at line 179 of file gz_MPI_element_file_IO_b.f90.
References gz_mpi_edge_data_io_b::gz_mpi_write_edge_connect_b(), m_machine_parameter::i_debug, and io_param.
Referenced by element_mesh_mpi_io_select::sel_mpi_write_edge_mesh_file().
gz_mpi_output_element_file_b()
subroutine gz_mpi_element_file_io_b::gz_mpi_output_element_file_b (character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(inout) ele_mesh_IO)
Definition at line 132 of file gz_MPI_element_file_IO_b.f90.
References gz_mpi_element_data_io_b::gz_mpi_write_ele_comm_table_b(), m_machine_parameter::i_debug, and io_param.
Referenced by element_mesh_mpi_io_select::sel_mpi_write_ele_mesh_file().
gz_mpi_output_surface_file_b()
subroutine gz_mpi_element_file_io_b::gz_mpi_output_surface_file_b (character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(in) surf_mesh_IO)
Definition at line 155 of file gz_MPI_element_file_IO_b.f90.
References gz_mpi_surface_data_io_b::gz_mpi_write_surf_connect_b(), m_machine_parameter::i_debug, and io_param.
Referenced by element_mesh_mpi_io_select::sel_mpi_write_surf_mesh_file().
Variable Documentation
io_param
type(calypso_mpi_io_params), save, private gz_mpi_element_file_io_b::io_param private
Definition at line 41 of file gz_MPI_element_file_IO_b.f90.
Referenced by gz_mpi_input_edge_file_b(), gz_mpi_input_element_file_b(), gz_mpi_input_surface_file_b(), gz_mpi_output_edge_file_b(), gz_mpi_output_element_file_b(), and gz_mpi_output_surface_file_b().