CALYPSO: t_sph_matrices Module Reference
t_sph_matrices Module Reference
structures of radial matrices
Data Types
type band_matrices_type
Structure for band matrices.
Functions/Subroutines
subroutine alloc_band_mat_sph (nband, sph_rj, smat)
subroutine set_unit_on_diag (smat)
subroutine dealloc_band_mat_sph (smat)
subroutine ludcmp_3band_mul_t (Msmp, Msmp_stack, smat)
subroutine ludcmp_5band_mul_t (Msmp, Msmp_stack, smat)
subroutine ludcmp_7band_mul_t (Msmp, Msmp_stack, smat)
subroutine lubksb_3band_mul_t (Msmp, Msmp_stack, smat, x)
subroutine lubksb_5band_mul_t (Msmp, Msmp_stack, smat, x)
subroutine lubksb_7band_mul_t (Msmp, Msmp_stack, smat, x)
subroutine check_radial_band_mat (id_rank, sph_rj, smat)
Detailed Description
structures of radial matrices
      subroutine alloc_band_mat_sph(nband, sph_rj, smat)
      subroutine set_unit_on_diag(smat)
      subroutine dealloc_band_mat_sph(smat)
      subroutine ludcmp_3band_mul_t(Msmp, Msmp_stack, smat)
      subroutine ludcmp_5band_mul_t(Msmp, Msmp_stack, smat)
      subroutine ludcmp_7band_mul_t(Msmp, Msmp_stack, smat)
      subroutine lubksb_3band_mul_t(Msmp, Msmp_stack, smat, x)
      subroutine lubksb_5band_mul_t(Msmp, Msmp_stack, smat, x)
      subroutine lubksb_7band_mul_t(Msmp, Msmp_stack, smat, x)
        type(sph_rj_grid), intent(in) ::  sph_rj
        type(band_matrices_type), intent(inout) :: smat
      subroutine check_radial_band_mat(id_rank, sph_rj, smat)
Function/Subroutine Documentation
alloc_band_mat_sph()
subroutine t_sph_matrices::alloc_band_mat_sph (integer(kind = kint), intent(in) nband, type(sph_rj_grid), intent(in) sph_rj, type(band_matrices_type), intent(inout) smat)
Definition at line 70 of file t_sph_matrices.f90.
Referenced by const_r_mat_4_vector_sph::const_radial_mat_4_magne_sph(), const_r_mat_4_scalar_sph::const_radial_mat_4_press_sph(), const_r_mat_4_scalar_sph::const_radial_mat_4_scalar_sph(), and const_r_mat_4_vector_sph::const_radial_mat_vort_2step().
check_radial_band_mat()
subroutine t_sph_matrices::check_radial_band_mat (integer, intent(in) id_rank, type(sph_rj_grid), intent(in) sph_rj, type(band_matrices_type), intent(in) smat)
Definition at line 231 of file t_sph_matrices.f90.
References check_sph_radial_mat::check_radial_3band_mat(), check_sph_radial_mat::check_radial_5band_mat(), and check_sph_radial_mat::check_radial_7band_mat().
Referenced by t_radial_matrices_sph_mhd::check_velocity_matrices_sph(), const_r_mat_4_vector_sph::const_radial_mat_4_magne_sph(), const_r_mat_4_scalar_sph::const_radial_mat_4_press_sph(), const_r_mat_4_scalar_sph::const_radial_mat_4_scalar_sph(), and const_r_mat_4_vector_sph::const_radial_mat_vort_2step().
dealloc_band_mat_sph()
subroutine t_sph_matrices::dealloc_band_mat_sph (type(band_matrices_type), intent(inout) smat)
Definition at line 114 of file t_sph_matrices.f90.
lubksb_3band_mul_t()
subroutine t_sph_matrices::lubksb_3band_mul_t (integer (kind = kint), intent(in) Msmp, integer (kind = kint), dimension(0:msmp), intent(in) Msmp_stack, type(band_matrices_type), intent(in) smat, real(kind = kreal), dimension(smat%n_comp,smat%n_vect), intent(inout) x)
Definition at line 176 of file t_sph_matrices.f90.
References lubksb_357band_mul::lubksb_3band_mul().
Referenced by solve_sph_fluid_crank::solve_magne_sph_crank(), solve_sph_fluid_crank::solve_pressure_by_div_v(), solve_sph_fluid_crank::solve_scalar_sph_crank(), and solve_sph_fluid_crank::solve_velo_by_vort_sph_crank().
lubksb_5band_mul_t()
subroutine t_sph_matrices::lubksb_5band_mul_t (integer (kind = kint), intent(in) Msmp, integer (kind = kint), dimension(0:msmp), intent(in) Msmp_stack, type(band_matrices_type), intent(in) smat, real(kind = kreal), dimension(smat%n_comp,smat%n_vect), intent(inout) x)
Definition at line 194 of file t_sph_matrices.f90.
References lubksb_357band_mul::lubksb_5band_mul().
Referenced by solve_sph_fluid_crank::solve_velo_by_vort_sph_crank().
lubksb_7band_mul_t()
subroutine t_sph_matrices::lubksb_7band_mul_t (integer (kind = kint), intent(in) Msmp, integer (kind = kint), dimension(0:msmp), intent(in) Msmp_stack, type(band_matrices_type), intent(in) smat, real(kind = kreal), dimension(smat%n_comp,smat%n_vect), intent(inout) x)
Definition at line 212 of file t_sph_matrices.f90.
References lubksb_357band_mul::lubksb_7band_mul().
ludcmp_3band_mul_t()
subroutine t_sph_matrices::ludcmp_3band_mul_t (integer (kind = kint), intent(in) Msmp, integer (kind = kint), dimension(0:msmp), intent(in) Msmp_stack, type(band_matrices_type), intent(inout) smat)
Definition at line 127 of file t_sph_matrices.f90.
References ludcmp_357band_mul::ludcmp_3band_mul().
Referenced by const_r_mat_4_vector_sph::const_radial_mat_4_magne_sph(), const_r_mat_4_scalar_sph::const_radial_mat_4_press_sph(), const_r_mat_4_scalar_sph::const_radial_mat_4_scalar_sph(), and const_r_mat_4_vector_sph::const_radial_mat_vort_2step().
ludcmp_5band_mul_t()
subroutine t_sph_matrices::ludcmp_5band_mul_t (integer (kind = kint), intent(in) Msmp, integer (kind = kint), dimension(0:msmp), intent(in) Msmp_stack, type(band_matrices_type), intent(inout) smat)
Definition at line 143 of file t_sph_matrices.f90.
References ludcmp_357band_mul::ludcmp_5band_mul().
Referenced by const_r_mat_4_vector_sph::const_radial_mat_vort_2step().
ludcmp_7band_mul_t()
subroutine t_sph_matrices::ludcmp_7band_mul_t (integer (kind = kint), intent(in) Msmp, integer (kind = kint), dimension(0:msmp), intent(in) Msmp_stack, type(band_matrices_type), intent(inout) smat)
Definition at line 159 of file t_sph_matrices.f90.
References ludcmp_357band_mul::ludcmp_7band_mul().
set_unit_on_diag()
subroutine t_sph_matrices::set_unit_on_diag (type(band_matrices_type), intent(inout) smat)
Definition at line 99 of file t_sph_matrices.f90.
Referenced by const_r_mat_4_vector_sph::const_radial_mat_4_magne_sph(), const_r_mat_4_scalar_sph::const_radial_mat_4_scalar_sph(), and const_r_mat_4_vector_sph::const_radial_mat_vort_2step().