CALYPSO: primefac Module Reference
primefac Module Reference
Functions/Subroutines
subroutine prmfac (NUMBER, maxprim, nprm, iprm, iexp)
subroutine primetest (NUMBER, iflag)
subroutine countprimes (number_end, num_prime)
subroutine setprimes (number_end, num_prime, i_prime_list)
Variables
integer(kind=kint), dimension(52), parameter, private base = (/ 211, 209, 199, 197, 193, 191, 187, 181, 179, 173, 169, 167, 163, 157, 151, 149, 143, 139, 137, 131, 127, 121, 113, 109, 107, 103, 101, 97, 89, 83, 79, 73, 71, 67, 61, 59, 53, 47, 43, 41, 37, 31, 29, 23, 19, 17, 13, 11, 7, 5, 3, 2/)
Function/Subroutine Documentation
countprimes()
subroutine primefac::countprimes (integer(kind = kint), intent(in) number_end, integer(kind = kint), intent(inout) num_prime)
Definition at line 249 of file primefac.f90.
References primetest().
Referenced by normgi_by_primes::conut_prims_normgi().
primetest()
subroutine primefac::primetest (integer(kind = kint), intent(in) NUMBER, integer(kind = kint), intent(out) iflag)
Definition at line 165 of file primefac.f90.
References base.
Referenced by countprimes(), and setprimes().
prmfac()
subroutine primefac::prmfac (integer(kind = kint), intent(in) NUMBER, integer(kind = kint), intent(in) maxprim, integer(kind = kint), intent(out) nprm, integer(kind = kint), dimension(maxprim), intent(out) iprm, integer(kind = kint), dimension(maxprim), intent(out) iexp)
Definition at line 83 of file primefac.f90.
References base.
Referenced by normgi_by_primes::conut_prims_normgi().
setprimes()
subroutine primefac::setprimes (integer(kind = kint), intent(in) number_end, integer(kind = kint), intent(in) num_prime, integer(kind = kint), dimension(num_prime), intent(inout) i_prime_list)
Definition at line 267 of file primefac.f90.
References primetest().
Referenced by normgi_by_primes::conut_prims_normgi().
Variable Documentation
base
integer(kind = kint), dimension(52), parameter, private primefac::base = (/ 211, 209, 199, 197, 193, 191, 187, 181, 179, 173, 169, 167, 163, 157, 151, 149, 143, 139, 137, 131, 127, 121, 113, 109, 107, 103, 101, 97, 89, 83, 79, 73, 71, 67, 61, 59, 53, 47, 43, 41, 37, 31, 29, 23, 19, 17, 13, 11, 7, 5, 3, 2/) private
Definition at line 71 of file primefac.f90.
Referenced by primetest(), and prmfac().