CALYPSO: renumber_para_viewer_mesh Module Reference
renumber_para_viewer_mesh Module Reference
Surface mesh data generator for kemoviewer.
Functions/Subroutines
subroutine s_renumber_para_viewer_mesh (nshift_node, nshift_surf, nshift_edge, mgd_v_mesh)
subroutine set_global_node_info_4_viewer (nshift_node, view_mesh)
subroutine set_global_surf_info_4_viewer (nnod_4_surf, nshift_node, nshift_surf, view_mesh)
subroutine set_global_edge_info_4_viewer (nnod_4_edge, nshift_node, nshift_edge, view_mesh)
subroutine shift_global_surf_grps_items (nshift_node, nshift_surf, nshift_edge, view_grps)
subroutine set_global_group_items (nshift, viewer_grp)
Detailed Description
Surface mesh data generator for kemoviewer.
      subroutine s_renumber_para_viewer_mesh                          &
     &         (nshift_node, nshift_surf, nshift_edge, mgd_v_mesh)
        type(merged_viewer_mesh), intent(inout) :: mgd_v_mesh
Function/Subroutine Documentation
s_renumber_para_viewer_mesh()
subroutine renumber_para_viewer_mesh::s_renumber_para_viewer_mesh (integer(kind = kint), intent(in) nshift_node, integer(kind = kint), intent(in) nshift_surf, integer(kind = kint), intent(in) nshift_edge, type(merged_viewer_mesh), intent(inout) mgd_v_mesh)
Definition at line 33 of file renumber_para_viewer_mesh.f90.
References set_global_edge_info_4_viewer(), set_global_group_items(), set_global_node_info_4_viewer(), set_global_surf_info_4_viewer(), and shift_global_surf_grps_items().
Referenced by para_const_kemoview_mesh::collect_surf_mesh_4_viewer().
set_global_edge_info_4_viewer()
subroutine renumber_para_viewer_mesh::set_global_edge_info_4_viewer (integer(kind = kint), intent(in) nnod_4_edge, integer(kind = kint), intent(in) nshift_node, integer(kind = kint), intent(in) nshift_edge, type(viewer_mesh_data), intent(inout) view_mesh)
Definition at line 120 of file renumber_para_viewer_mesh.f90.
References m_geometry_constants::nedge_4_surf.
Referenced by s_renumber_para_viewer_mesh().
set_global_group_items()
subroutine renumber_para_viewer_mesh::set_global_group_items (integer(kind = kint), intent(in) nshift, type(viewer_group_data), intent(inout) viewer_grp)
Definition at line 180 of file renumber_para_viewer_mesh.f90.
Referenced by s_renumber_para_viewer_mesh(), and shift_global_surf_grps_items().
set_global_node_info_4_viewer()
subroutine renumber_para_viewer_mesh::set_global_node_info_4_viewer (integer(kind = kint), intent(in) nshift_node, type(viewer_mesh_data), intent(inout) view_mesh)
Definition at line 71 of file renumber_para_viewer_mesh.f90.
Referenced by s_renumber_para_viewer_mesh().
set_global_surf_info_4_viewer()
subroutine renumber_para_viewer_mesh::set_global_surf_info_4_viewer (integer(kind = kint), intent(in) nnod_4_surf, integer(kind = kint), intent(in) nshift_node, integer(kind = kint), intent(in) nshift_surf, type(viewer_mesh_data), intent(inout) view_mesh)
Definition at line 89 of file renumber_para_viewer_mesh.f90.
Referenced by s_renumber_para_viewer_mesh().
shift_global_surf_grps_items()
subroutine renumber_para_viewer_mesh::shift_global_surf_grps_items (integer(kind = kint), intent(in) nshift_node, integer(kind = kint), intent(in) nshift_surf, integer(kind = kint), intent(in) nshift_edge, type(viewer_surface_groups), intent(inout) view_grps)
Definition at line 164 of file renumber_para_viewer_mesh.f90.
References set_global_group_items().
Referenced by s_renumber_para_viewer_mesh().