CALYPSO: merged_udt_vtk_file_io Module Reference
merged_udt_vtk_file_io Module Reference
Output merged VTK file usgin MPI-IO.
Functions/Subroutines
subroutine init_merged_ucd (iflag_format, node, ele, nod_comm, ucd)
subroutine finalize_merged_ucd (iflag_format, ucd)
subroutine write_ucd_file_mpi (file_name, ucd)
subroutine write_ucd_phys_mpi (file_name, ucd)
subroutine write_ucd_grid_mpi (file_name, ucd)
subroutine write_vtk_file_mpi (file_name, ucd)
subroutine write_vtk_phys_mpi (file_name, ucd)
subroutine write_vtk_grid_mpi (file_name, ucd)
Variables
integer(kind=kint), parameter, private id_vtk_file = 16
file ID for VTK file
type(parallel_double_numbering), save, private dbl_id1
Structure of double numbering.
type(calypso_mpi_io_params), save, private io_param
Detailed Description
Output merged VTK file usgin MPI-IO.
      subroutine init_merged_ucd                                      &
     &         (iflag_format, node, ele, nod_comm, ucd)
        type(node_data), intent(in) :: node
        type(element_data), intent(in) :: ele
        type(communication_table), intent(in) :: nod_comm
        type(ucd_data), intent(inout) :: ucd
      subroutine finalize_merged_ucd(iflag_format, ucd)
        type(ucd_data), intent(inout) :: ucd
      subroutine write_ucd_file_mpi(file_name, ucd)
      subroutine write_ucd_phys_mpi(file_name, ucd)
      subroutine write_ucd_grid_mpi(file_name, ucd)
      subroutine write_vtk_file_mpi(file_name, ucd)
      subroutine write_vtk_phys_mpi(file_name, ucd)
      subroutine write_vtk_grid_mpi(file_name, ucd)
        type(ucd_data), intent(in) :: ucd
Function/Subroutine Documentation
finalize_merged_ucd()
subroutine merged_udt_vtk_file_io::finalize_merged_ucd (integer(kind = kint), intent(in) iflag_format, type(ucd_data), intent(inout) ucd)
Definition at line 106 of file merged_udt_vtk_file_IO.f90.
References t_ucd_data::dealloc_merged_ucd_ele_stack(), m_field_file_format::iflag_sgl_hdf5, hdf5_file_io::parallel_finalize_hdf5(), and t_ucd_data::unlink_merged_ucd_nod_stack().
Referenced by output_parallel_ucd_file::finalize_ucd_file_output(), and output_parallel_ucd_file::output_udt_one_snapshot().
init_merged_ucd()
subroutine merged_udt_vtk_file_io::init_merged_ucd (integer(kind = kint), intent(in) iflag_format, type(node_data), intent(in) node, type(element_data), intent(in) ele, type(communication_table), intent(in) nod_comm, type(ucd_data), intent(inout) ucd)
Definition at line 60 of file merged_udt_vtk_file_IO.f90.
References t_para_double_numbering::alloc_double_numbering(), t_ucd_data::alloc_merged_ucd_ele_stack(), t_ucd_data::allocate_ucd_ele(), const_global_element_ids::count_number_of_node_stack(), dbl_id1, t_para_double_numbering::dealloc_double_numbering(), m_field_file_format::iflag_sgl_hdf5, set_ucd_data_to_type::link_nnod_stacks_2_ucd(), calypso_mpi::nprocs, pickup_internal_element::num_internal_element_4_io(), hdf5_file_io::parallel_init_hdf5(), pickup_internal_element::set_internal_element_4_io(), and t_para_double_numbering::set_para_double_numbering().
Referenced by output_parallel_ucd_file::link_output_grd_file(), and output_parallel_ucd_file::output_udt_one_snapshot().
write_ucd_file_mpi()
subroutine merged_udt_vtk_file_io::write_ucd_file_mpi (character(len=kchara), intent(in) file_name, type(ucd_data), intent(in) ucd)
Definition at line 124 of file merged_udt_vtk_file_IO.f90.
References calypso_mpi::my_rank, calypso_mpi::nprocs, ucd_file_mpi_io::write_ucd_connect_mpi(), ucd_file_mpi_io::write_ucd_data_mpi(), and ucd_file_mpi_io::write_ucd_node_mpi().
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_file().
write_ucd_grid_mpi()
subroutine merged_udt_vtk_file_io::write_ucd_grid_mpi (character(len=kchara), intent(in) file_name, type(ucd_data), intent(in) ucd)
Definition at line 188 of file merged_udt_vtk_file_IO.f90.
References calypso_mpi::my_rank, calypso_mpi::nprocs, ucd_file_mpi_io::write_ucd_connect_mpi(), and ucd_file_mpi_io::write_ucd_node_mpi().
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_mesh().
write_ucd_phys_mpi()
subroutine merged_udt_vtk_file_io::write_ucd_phys_mpi (character(len=kchara), intent(in) file_name, type(ucd_data), intent(in) ucd)
Definition at line 159 of file merged_udt_vtk_file_IO.f90.
References calypso_mpi::my_rank, calypso_mpi::nprocs, and ucd_file_mpi_io::write_ucd_data_mpi().
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_file().
write_vtk_file_mpi()
subroutine merged_udt_vtk_file_io::write_vtk_file_mpi (character(len=kchara), intent(in) file_name, type(ucd_data), intent(in) ucd)
Definition at line 220 of file merged_udt_vtk_file_IO.f90.
References calypso_mpi::my_rank, calypso_mpi::nprocs, vtk_file_mpi_io::write_vtk_data_mpi(), and vtk_file_mpi_io::write_vtk_mesh_mpi().
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_file().
write_vtk_grid_mpi()
subroutine merged_udt_vtk_file_io::write_vtk_grid_mpi (character(len=kchara), intent(in) file_name, type(ucd_data), intent(in) ucd)
Definition at line 282 of file merged_udt_vtk_file_IO.f90.
References calypso_mpi::my_rank, calypso_mpi::nprocs, and vtk_file_mpi_io::write_vtk_mesh_mpi().
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_mesh().
write_vtk_phys_mpi()
subroutine merged_udt_vtk_file_io::write_vtk_phys_mpi (character(len=kchara), intent(in) file_name, type(ucd_data), intent(in) ucd)
Definition at line 253 of file merged_udt_vtk_file_IO.f90.
References calypso_mpi::my_rank, calypso_mpi::nprocs, and vtk_file_mpi_io::write_vtk_data_mpi().
Referenced by parallel_ucd_io_select::sel_write_parallel_ucd_file().
Variable Documentation
dbl_id1
type(parallel_double_numbering), save, private merged_udt_vtk_file_io::dbl_id1 private
Structure of double numbering.
Definition at line 50 of file merged_udt_vtk_file_IO.f90.
Referenced by init_merged_ucd().
id_vtk_file
integer(kind = kint), parameter, private merged_udt_vtk_file_io::id_vtk_file = 16 private
file ID for VTK file
Definition at line 47 of file merged_udt_vtk_file_IO.f90.
io_param
type(calypso_mpi_io_params), save, private merged_udt_vtk_file_io::io_param private
Definition at line 52 of file merged_udt_vtk_file_IO.f90.