CALYPSO: gz_mpi_viewer_mesh_file_io Module Reference
gz_mpi_viewer_mesh_file_io Module Reference
Viewer mesh file IO for gzipped format.
Functions/Subroutines
subroutine gz_mpi_write_viewer_mesh_file (file_name, mgd_v_mesh, mgd_view_prm)
subroutine, private gz_write_viewer_mesh_infos (mgd_v_mesh, mgd_view_prm, IO_param)
Detailed Description
Viewer mesh file IO for gzipped format.
      subroutine gz_mpi_write_viewer_mesh_file                        &
     &         (file_name, mgd_v_mesh, mgd_view_prm)
        type(merged_viewer_mesh), intent(in) :: mgd_v_mesh
        type(mpi_viewer_mesh_param), intent(in) :: mgd_view_prm
Function/Subroutine Documentation
gz_mpi_write_viewer_mesh_file()
subroutine gz_mpi_viewer_mesh_file_io::gz_mpi_write_viewer_mesh_file (character(len=kchara), intent(in) file_name, type(merged_viewer_mesh), intent(in) mgd_v_mesh, type(mpi_viewer_mesh_param), intent(in) mgd_view_prm)
Definition at line 34 of file gz_MPI_viewer_mesh_file_IO.f90.
References set_parallel_file_name::add_gzip_extension(), mpi_ascii_data_io::close_mpi_file(), gz_write_viewer_mesh_infos(), and mpi_ascii_data_io::open_write_mpi_file().
Referenced by viewer_mesh_mpi_io_select::sel_mpi_output_surface_grid().
gz_write_viewer_mesh_infos()
subroutine, private gz_mpi_viewer_mesh_file_io::gz_write_viewer_mesh_infos (type(merged_viewer_mesh), intent(in) mgd_v_mesh, type(mpi_viewer_mesh_param), intent(in) mgd_view_prm, type(calypso_mpi_io_params), intent(inout) IO_param) private
Definition at line 61 of file gz_MPI_viewer_mesh_file_IO.f90.
References transfer_to_long_integers::cast_long(), gz_mpi_ascii_data_io::gz_mpi_write_charahead(), gz_mpi_viewer_mesh_io::gz_mpi_write_domain_grp_data(), gz_mpi_integer_list_io::gz_mpi_write_ele_connect(), gz_mpi_integer_list_io::gz_mpi_write_element_type(), gz_mpi_ascii_data_io::gz_mpi_write_stack_over_domain(), gz_mpi_viewer_mesh_io::gz_mpi_write_viewer_grp_data(), gz_mpi_viewer_mesh_io::gz_mpi_write_viewer_position(), m_viewer_mesh_labels::hd_domain_edge_grp(), m_viewer_mesh_labels::hd_domain_nod_grp(), m_viewer_mesh_labels::hd_domain_surf_grp(), m_viewer_mesh_labels::hd_edge_on_sf_viewer(), m_viewer_mesh_labels::hd_edge_viewer(), m_viewer_mesh_labels::hd_ele_edge_grp(), m_viewer_mesh_labels::hd_ele_nod_grp(), m_viewer_mesh_labels::hd_ele_surf_grp(), m_fem_mesh_labels::hd_fem_elegrp(), m_fem_mesh_labels::hd_fem_nodgrp(), m_fem_mesh_labels::hd_fem_sfgrp(), m_viewer_mesh_labels::hd_ndomain_viewer(), m_viewer_mesh_labels::hd_node_viewer(), m_viewer_mesh_labels::hd_surf_edge_grp(), m_viewer_mesh_labels::hd_surf_nod_grp(), m_viewer_mesh_labels::hd_surf_surf_grp(), m_viewer_mesh_labels::hd_surf_viewer(), m_constants::iten, and m_phys_constants::n_vector.
Referenced by gz_mpi_write_viewer_mesh_file().