CALYPSO: spherical_harmonics Module Reference
spherical_harmonics Module Reference
Routines for spherical harmonics and normalization.
Functions/Subroutines
subroutine sph_normalizations (l, m, idx_lm, g_lm)
subroutine idx28 (ltr, jmax, idx, g)
subroutine spheric (ltr, jmax, idx, phi, p, dp, Y)
subroutine get_degree_order_by_full_j (j, l, m)
integer(kind=kint) function get_idx_by_full_degree_order (l, m)
Detailed Description
Routines for spherical harmonics and normalization.
      subroutine sph_normalizations(l, m, idx_lm, g_lm)
      subroutine idx28(ltr, jmax, idx, g)
***********************************************************************
*    subroutine for make indices for spherical harmonics
*                                     97,12,19
***********************************************************************
*
***********************************************************************
*
*   g(j,1) , idx(j,1) : index l
*   g(j,2) , idx(j,2) : index m
*   g(j,3)            : l*(l+1)
*   g(j,4)            : (l-1)*l
*   g(j,5)            : (l+1)*(l+2)
*   g(j,6)            : (2*l+1) / 4
*            g(j,6)   : (2*l+1) / 2                    (m = 0)
*   g(j,7)            : (2*l+1) / (4*l*(l+1))
*            g(j,7)   : (2*l+1) / (2*l*(l+1))        (m = 0)
*            g(j,7)   : 1                              (l=m=0)
*   g(j,8)            : (4*pi*l*(l+1)) / (2*l+1)
*   g(j,9)            : (2*l+1) / (4*pi*l*(l+1))
*            g(j,9)   : 1 / 4*pi                       (l=m=0)
*   g(j,10)           : (4*pi) / (2*l+1)
*   g(j,11)           :  1 / (2*l+1)
*   g(j,12)           :  l*(l+1) / (2*l+1)
*   g(j,13)           :  1 / (l*(l+1))
*            g(j,13)  :    1                           (l=m=0)
*   g(j,16)           : (2*l+1) / 4
*   g(j,17)           : (2*l+1) / (4*l*(l+1))
*            g(j,17)  : 0                              (l=m=0)
   Note: g(0,3) = 1/2 for spherical harmonics transform
   Note: g(0,13) = 2  for gradient of scalar
    (See g_sph_rlm in schmidt_poly_on_rtm_grid.f90)
*
***********************************************************************
*
      subroutine spheric(ltr, jmax, idx, phi, p, dp, Y)
*************************************************************
*     lead spherical harmonics
*         and differential of spherical harmonics
*************************************************************
*
*************************************************************
*
*     required subroutine
*         dschmidt
*
*************************************************************
*
*************************************************************
*
*      p(m,l,0)  : Schmidt Polynomial
*      dp(m,l,1) : diffrential of Schmidt Polynomial  dp/dtheta
*        phi      :  input longitude phi (0 =< phi <= 2*pi)
*       work  :   work area
*
*************************************************************
      subroutine get_degree_order_by_full_j(j, l, m)
      integer(kind = kint) function get_idx_by_full_degree_order(l, m)
Function/Subroutine Documentation
get_degree_order_by_full_j()
subroutine spherical_harmonics::get_degree_order_by_full_j (integer(kind = kint), intent(in) j, integer(kind = kint), intent(inout) l, integer(kind = kint), intent(inout) m)
Definition at line 221 of file spherical_harmonics.f90.
Referenced by solve_sph_fluid_crank::check_nan_temperature(), and pickup_sph_spectr::set_picked_sph_address().
get_idx_by_full_degree_order()
integer(kind = kint) function spherical_harmonics::get_idx_by_full_degree_order (integer(kind = kint), intent(in) l, integer(kind = kint), intent(in) m)
Definition at line 233 of file spherical_harmonics.f90.
Referenced by pickup_sph_spectr::count_picked_sph_adrress(), and pickup_sph_spectr::set_picked_sph_address().
idx28()
subroutine spherical_harmonics::idx28 (integer(kind = kint) ltr, integer(kind = kint) jmax, integer(kind = kint), dimension(0:jmax,2) idx, real(kind = kreal), dimension(0:jmax,17) g)
Definition at line 144 of file spherical_harmonics.f90.
References sph_normalizations().
Referenced by t_spherical_harmonics::init_sph_indices().
sph_normalizations()
subroutine spherical_harmonics::sph_normalizations (integer(kind = kint), intent(in) l, integer(kind = kint), intent(in) m, integer(kind = kint), dimension(2), intent(inout) idx_lm, real(kind = kreal), dimension(17), intent(inout) g_lm)
Definition at line 91 of file spherical_harmonics.f90.
References m_constants::four, m_constants::one, m_constants::two, and m_constants::zero.
Referenced by schmidt_poly_on_rtm_grid::copy_sph_normalization_2_rj(), schmidt_poly_on_rtm_grid::copy_sph_normalization_2_rlm(), and idx28().
spheric()
subroutine spherical_harmonics::spheric (integer(kind = kint) ltr, integer(kind = kint) jmax, integer(kind = kint), dimension(0:jmax,2) idx, real(kind= kreal), intent(in) phi, real(kind = kreal), dimension(0:ltr,0:ltr), intent(in) p, real(kind = kreal), dimension(0:ltr,0:ltr), intent(in) dp, real(kind = kreal), dimension(0:jmax,0:3), intent(inout) Y)
Definition at line 171 of file spherical_harmonics.f90.
References m_constants::one, and m_constants::zero.
Referenced by t_spherical_harmonics::spheric_1point().