CALYPSO: set_radius_func_noequi Module Reference
set_radius_func_noequi Module Reference
Functions/Subroutines
subroutine allocate_dr_rj_noequi (nri)
subroutine deallocate_dr_rj_noequi
subroutine, private check_radial_func_rj (nri, radius_1d_rj_r)
subroutine set_dr_for_equidist (nlayer_ICB, nlayer_CMB, nri, radius_1d_rj_r)
subroutine set_dr_for_nonequi (nlayer_CMB, nri, radius_1d_rj_r)
subroutine nod_r_2nd_fdm_coefs_equi (nlayer_ICB, nri, radius_1d_rj_r, mat_fdm_2)
subroutine nod_r_2nd_fdm_coefs_nonequi (nlayer_ICB, nri, radius_1d_rj_r, mat_fdm_2)
subroutine nod_r_2nd_fdm_coef_noequi (kr, dr_p1, dr_n1, mat_fdm)
Variables
real(kind=kreal), dimension(:), allocatable, private dr_1d_rj
1d \(\Delta r \) for \(f(r,j) \)
Function/Subroutine Documentation
allocate_dr_rj_noequi()
subroutine set_radius_func_noequi::allocate_dr_rj_noequi (integer(kind = kint), intent(in) nri)
Definition at line 62 of file set_radius_func_noequi.f90.
References dr_1d_rj.
Referenced by init_radial_infos_sph_mhd::set_delta_r_4_sph_mhd().
check_radial_func_rj()
subroutine, private set_radius_func_noequi::check_radial_func_rj (integer(kind = kint), intent(in) nri, real(kind = kreal), dimension(nri), intent(in) radius_1d_rj_r) private
Definition at line 83 of file set_radius_func_noequi.f90.
References dr_1d_rj.
Referenced by set_dr_for_nonequi().
deallocate_dr_rj_noequi()
subroutine set_radius_func_noequi::deallocate_dr_rj_noequi
Definition at line 74 of file set_radius_func_noequi.f90.
References dr_1d_rj.
Referenced by const_fdm_coefs::const_2nd_fdm_matrices().
nod_r_2nd_fdm_coef_noequi()
subroutine set_radius_func_noequi::nod_r_2nd_fdm_coef_noequi (integer(kind = kint), intent(in) kr, real(kind = kreal), intent(in) dr_p1, real(kind = kreal), intent(in) dr_n1, real(kind = kreal), dimension(3,3), intent(inout) mat_fdm)
Definition at line 226 of file set_radius_func_noequi.f90.
References cal_inverse_small_matrix::cal_inverse_33_matrix(), m_constants::half, m_constants::one, and m_constants::zero.
Referenced by nod_r_2nd_fdm_coefs_equi(), and nod_r_2nd_fdm_coefs_nonequi().
nod_r_2nd_fdm_coefs_equi()
subroutine set_radius_func_noequi::nod_r_2nd_fdm_coefs_equi (integer(kind = kint), intent(in) nlayer_ICB, integer(kind = kint), intent(in) nri, real(kind = kreal), dimension(nri), intent(in) radius_1d_rj_r, real(kind = kreal), dimension(3,3,nri), intent(inout) mat_fdm_2)
Definition at line 166 of file set_radius_func_noequi.f90.
References dr_1d_rj, m_constants::ione, and nod_r_2nd_fdm_coef_noequi().
nod_r_2nd_fdm_coefs_nonequi()
subroutine set_radius_func_noequi::nod_r_2nd_fdm_coefs_nonequi (integer(kind = kint), intent(in) nlayer_ICB, integer(kind = kint), intent(in) nri, real(kind = kreal), dimension(nri), intent(in) radius_1d_rj_r, real(kind = kreal), dimension(3,3,nri), intent(inout) mat_fdm_2)
Definition at line 193 of file set_radius_func_noequi.f90.
References dr_1d_rj, m_constants::ione, and nod_r_2nd_fdm_coef_noequi().
Referenced by const_fdm_coefs::const_2nd_fdm_matrices().
set_dr_for_equidist()
subroutine set_radius_func_noequi::set_dr_for_equidist (integer(kind = kint), intent(in) nlayer_ICB, integer(kind = kint), intent(in) nlayer_CMB, integer(kind = kint), intent(in) nri, real(kind = kreal), dimension(nri), intent(in) radius_1d_rj_r)
Definition at line 101 of file set_radius_func_noequi.f90.
References dr_1d_rj.
set_dr_for_nonequi()
subroutine set_radius_func_noequi::set_dr_for_nonequi (integer(kind = kint), intent(in) nlayer_CMB, integer(kind = kint), intent(in) nri, real(kind = kreal), dimension(nri), intent(in) radius_1d_rj_r)
Definition at line 130 of file set_radius_func_noequi.f90.
References check_radial_func_rj(), dr_1d_rj, m_machine_parameter::iflag_debug, and m_machine_parameter::iflag_full_msg.
Referenced by init_radial_infos_sph_mhd::set_delta_r_4_sph_mhd().
Variable Documentation
dr_1d_rj
real(kind = kreal), dimension(:), allocatable, private set_radius_func_noequi::dr_1d_rj private
1d \(\Delta r \) for \(f(r,j) \)
See also
set_radius_func_cheby or set_radius_func_cheby
Definition at line 51 of file set_radius_func_noequi.f90.
Referenced by allocate_dr_rj_noequi(), check_radial_func_rj(), deallocate_dr_rj_noequi(), nod_r_2nd_fdm_coefs_equi(), nod_r_2nd_fdm_coefs_nonequi(), set_dr_for_equidist(), and set_dr_for_nonequi().