CALYPSO: t_sph_component_fftpack5 Module Reference
t_sph_component_fftpack5 Module Reference
Fourier transform using FFTPACK5.
Data Types
type work_for_comp_fftpack
Structure to use ISPACK.
Functions/Subroutines
subroutine init_sph_comp_fftpack5 (sph_rtp, ncomp_bwd, ncomp_fwd, fftpack_t)
subroutine finalize_sph_comp_fftpack5 (fftpack_t)
subroutine verify_sph_comp_fftpack5 (sph_rtp, ncomp_bwd, ncomp_fwd, fftpack_t)
subroutine sph_comp_rfftmf_to_send (sph_rtp, comm_rtp, ncomp_fwd, n_WS, X_rtp, WS, fftpack_t)
subroutine sph_comp_rfftmb_from_recv (sph_rtp, comm_rtp, ncomp_bwd, n_WR, WR, X_rtp, fftpack_t)
subroutine, private alloc_work_comp_fftpack (Nfft, ncomp_bwd, ncomp_fwd, fftpack_t)
subroutine, private alloc_const_comp_fftpack (nfft, fftpack_t)
subroutine, private dealloc_work_comp_fftpack (fftpack_t)
subroutine, private dealloc_const_comp_fftpack (fftpack_t)
subroutine, private copy_comp_rfftmf_to_send (j, nnod_rtp, irev_sr_rtp, mphi_rtp, nnod_rt, ncomp_fwd, X_fft, n_WS, WS)
subroutine, private copy_comp_rfftmb_from_recv (j, nnod_rtp, irev_sr_rtp, mphi_rtp, nnod_rt, ncomp_bwd, n_WR, WR, X_fft)
Detailed Description
Fourier transform using FFTPACK5.
  ---------------------------------------------------------------------
      subroutine init_sph_comp_FFTPACK5                               &
     &         (sph_rtp, ncomp_bwd, ncomp_fwd, fftpack_t)
      subroutine finalize_sph_comp_FFTPACK5(fftpack_t)
      subroutine verify_sph_comp_FFTPACK5                             &
     &         (sph_rtp, ncomp_bwd, ncomp_fwd, fftpack_t)
        type(sph_rtp_grid), intent(in) :: sph_rtp
 ------------------------------------------------------------------
   wrapper subroutine for initierize FFT
 ------------------------------------------------------------------
      subroutine sph_comp_RFFTMF_to_send(sph_rtp, comm_rtp,           &
     &          ncomp_fwd, n_WS, X_rtp, WS, fftpack_t)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_comm_tbl), intent(in) :: comm_rtp
 ------------------------------------------------------------------
 wrapper subroutine for forward Fourier transform by FFTPACK5
   a_{k} = \frac{2}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
          *  \cos (\frac{2\pi j k}{Nfft})
   b_{k} = \frac{2}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
          *  \cos (\frac{2\pi j k}{Nfft})
   a_{0} = \frac{1}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
    K = Nfft/2....
   a_{k} = \frac{1}{Nfft} \sum_{j=0}^{Nfft-1} x_{j}
          * \cos (\frac{2\pi j k}{Nfft})
 ------------------------------------------------------------------
      subroutine sph_comp_RFFTMB_from_recv(sph_rtp, comm_rtp,         &
     &          ncomp_bwd, n_WR, WR, X_rtp, fftpack_t)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(sph_comm_tbl), intent(in) :: comm_rtp
 ------------------------------------------------------------------
 wrapper subroutine for backward Fourier transform by FFTPACK5
   x_{k} = a_{0} + (-1)^{j} a_{Nfft/2} + sum_{k=1}^{Nfft/2-1}
          (a_{k} \cos(2\pijk/Nfft) + b_{k} \sin(2\pijk/Nfft))
 ------------------------------------------------------------------
       i = 1:     a_{0}
       i = 2:     a_{Nfft/2}
       i = 3:     a_{1}
       i = 4:     b_{1}
       ...
       i = 2*k+1: a_{k}
       i = 2*k+2: b_{k}
       ...
       i = Nfft-1:   a_{Nfft/2-1}
       i = Nfft:     b_{Nfft/2-1}
 ------------------------------------------------------------------
Parameters
Nsmp Number of SMP processors
Nstacksmp(0:Nsmp) End number for each SMP process
M Number of components for Fourier transforms
Nfft Data length for eadh FFT
X(M,Nfft) Data for Fourier transform
Function/Subroutine Documentation
alloc_const_comp_fftpack()
subroutine, private t_sph_component_fftpack5::alloc_const_comp_fftpack (integer(kind = kint), intent(in) nfft, type(work_for_comp_fftpack), intent(inout) fftpack_t) private
Definition at line 359 of file t_sph_component_FFTPACK5.f90.
References m_constants::ifour, and m_constants::two.
Referenced by init_sph_comp_fftpack5(), and verify_sph_comp_fftpack5().
alloc_work_comp_fftpack()
subroutine, private t_sph_component_fftpack5::alloc_work_comp_fftpack (integer(kind = kint), intent(in) Nfft, integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), intent(in) ncomp_fwd, type(work_for_comp_fftpack), intent(inout) fftpack_t) private
Definition at line 340 of file t_sph_component_FFTPACK5.f90.
References m_machine_parameter::np_smp.
Referenced by init_sph_comp_fftpack5(), and verify_sph_comp_fftpack5().
copy_comp_rfftmb_from_recv()
subroutine, private t_sph_component_fftpack5::copy_comp_rfftmb_from_recv (integer(kind = kint), intent(in) j, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(nnod_rtp), intent(in) irev_sr_rtp, integer(kind = kint), intent(in) mphi_rtp, integer(kind = kint), intent(in) nnod_rt, integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(in) WR, real(kind = kreal), dimension(ncomp_bwd*mphi_rtp), intent(inout) X_fft) private
Definition at line 444 of file t_sph_component_FFTPACK5.f90.
Referenced by sph_comp_rfftmb_from_recv().
copy_comp_rfftmf_to_send()
subroutine, private t_sph_component_fftpack5::copy_comp_rfftmf_to_send (integer(kind = kint), intent(in) j, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(nnod_rtp), intent(in) irev_sr_rtp, integer(kind = kint), intent(in) mphi_rtp, integer(kind = kint), intent(in) nnod_rt, integer(kind = kint), intent(in) ncomp_fwd, real(kind = kreal), dimension(ncomp_fwd*mphi_rtp), intent(in) X_fft, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_ws), intent(inout) WS) private
Definition at line 400 of file t_sph_component_FFTPACK5.f90.
Referenced by sph_comp_rfftmf_to_send().
dealloc_const_comp_fftpack()
subroutine, private t_sph_component_fftpack5::dealloc_const_comp_fftpack (type(work_for_comp_fftpack), intent(inout) fftpack_t) private
Definition at line 388 of file t_sph_component_FFTPACK5.f90.
Referenced by finalize_sph_comp_fftpack5(), and verify_sph_comp_fftpack5().
dealloc_work_comp_fftpack()
subroutine, private t_sph_component_fftpack5::dealloc_work_comp_fftpack (type(work_for_comp_fftpack), intent(inout) fftpack_t) private
Definition at line 377 of file t_sph_component_FFTPACK5.f90.
Referenced by finalize_sph_comp_fftpack5(), and verify_sph_comp_fftpack5().
finalize_sph_comp_fftpack5()
subroutine t_sph_component_fftpack5::finalize_sph_comp_fftpack5 (type(work_for_comp_fftpack), intent(inout) fftpack_t)
Definition at line 141 of file t_sph_component_FFTPACK5.f90.
References dealloc_const_comp_fftpack(), and dealloc_work_comp_fftpack().
Referenced by t_sph_fft_selector::finalize_sph_fft_select().
init_sph_comp_fftpack5()
subroutine t_sph_component_fftpack5::init_sph_comp_fftpack5 (type(sph_rtp_grid), intent(in) sph_rtp, integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), intent(in) ncomp_fwd, type(work_for_comp_fftpack), intent(inout) fftpack_t)
Definition at line 116 of file t_sph_component_FFTPACK5.f90.
References alloc_const_comp_fftpack(), alloc_work_comp_fftpack(), m_machine_parameter::np_smp, and rfftmi().
Referenced by t_sph_fft_selector::init_sph_fft_select().
sph_comp_rfftmb_from_recv()
subroutine t_sph_component_fftpack5::sph_comp_rfftmb_from_recv (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), intent(in) n_WR, real (kind=kreal), dimension(n_wr), intent(inout) WR, real(kind = kreal), dimension(sph_rtp%nnod_rtp,ncomp_bwd), intent(inout) X_rtp, type(work_for_comp_fftpack), intent(inout) fftpack_t)
Definition at line 267 of file t_sph_component_FFTPACK5.f90.
References copy_comp_rfftmb_from_recv(), m_elapsed_labels_sph_trns::iflag_fft_time, m_constants::ione, m_elapsed_labels_sph_trns::ist_elapsed_fft, m_machine_parameter::np_smp, rfftmb(), copy_single_fft_and_rtp::sel_copy_comp_fft_to_rtp(), and copy_single_fft_and_rtp::sum_omp_elapsed_4_fft().
Referenced by t_sph_fft_selector::back_fft_select_from_recv().
sph_comp_rfftmf_to_send()
subroutine t_sph_component_fftpack5::sph_comp_rfftmf_to_send (type(sph_rtp_grid), intent(in) sph_rtp, type(sph_comm_tbl), intent(in) comm_rtp, integer(kind = kint), intent(in) ncomp_fwd, integer(kind = kint), intent(in) n_WS, real(kind = kreal), dimension(sph_rtp%nnod_rtp,ncomp_fwd), intent(in) X_rtp, real (kind=kreal), dimension(n_ws), intent(inout) WS, type(work_for_comp_fftpack), intent(inout) fftpack_t)
Definition at line 195 of file t_sph_component_FFTPACK5.f90.
References copy_comp_rfftmf_to_send(), m_elapsed_labels_sph_trns::iflag_fft_time, m_constants::ione, m_elapsed_labels_sph_trns::ist_elapsed_fft, m_machine_parameter::np_smp, rfftmf(), copy_single_fft_and_rtp::sel_copy_comp_rtp_to_fft(), and copy_single_fft_and_rtp::sum_omp_elapsed_4_fft().
Referenced by t_sph_fft_selector::fwd_fft_select_to_send().
verify_sph_comp_fftpack5()
subroutine t_sph_component_fftpack5::verify_sph_comp_fftpack5 (type(sph_rtp_grid), intent(in) sph_rtp, integer(kind = kint), intent(in) ncomp_bwd, integer(kind = kint), intent(in) ncomp_fwd, type(work_for_comp_fftpack), intent(inout) fftpack_t)
Definition at line 154 of file t_sph_component_FFTPACK5.f90.
References alloc_const_comp_fftpack(), alloc_work_comp_fftpack(), dealloc_const_comp_fftpack(), dealloc_work_comp_fftpack(), and rfftmi().
Referenced by t_sph_fft_selector::verify_sph_fft_select().