CALYPSO: cal_buoyancy_flux_sph Module Reference
cal_buoyancy_flux_sph Module Reference
Evaluate energy fluxes for MHD dynamo in physical space.
Functions/Subroutines
subroutine cal_buoyancy_flux_rtp (sph_rtp, fl_prop, ref_param_T, ref_param_C, bs_trns_base, bs_trns_scalar, fs_trns_eflux, trns_b_snap, trns_b_scl, trns_f_eflux)
subroutine pole_buoyancy_flux_rtp (sph_rtp, fl_prop, ref_param_T, ref_param_C, bs_trns_base, bs_trns_scalar, fs_trns_eflux, trns_b_snap, trns_b_scl, trns_f_eflux)
subroutine, private pole_sph_buoyancy_flux (nnod_pole, nidx_rtp_r, radius, coef, t_pole, v_pole, d_pole)
subroutine sel_buoyancy_flux_rtp (sph_rtp, coef, scalar, vr, prod)
subroutine, private cal_buoyancy_flux_rin (nnod_rtp, nidx_rtp, radius, coef, scalar, vr, prod)
subroutine, private cal_buoyancy_flux_pin (nnod_rtp, nidx_rtp, radius, coef, scalar, vr, prod)
Detailed Description
Evaluate energy fluxes for MHD dynamo in physical space.
      subroutine cal_buoyancy_flux_rtp                                &
     &         (sph_rtp, fl_prop, ref_param_T, ref_param_C,           &
     &          bs_trns_base, bs_trns_scalar, fs_trns_eflux,          &
     &          trns_b_snap, trns_b_scl, trns_f_eflux)
      subroutine pole_buoyancy_flux_rtp                               &
     &         (sph_rtp, fl_prop, ref_param_T, ref_param_C,           &
     &          bs_trns_base, bs_trns_scalar, fs_trns_eflux,          &
     &          trns_b_snap, trns_b_scl, trns_f_eflux)
        type(sph_rtp_grid), intent(in) :: sph_rtp
        type(fluid_property), intent(in) :: fl_prop
        type(reference_scalar_param), intent(in) :: ref_param_T
        type(reference_scalar_param), intent(in) :: ref_param_C
        type(base_field_address), intent(in) :: bs_trns_base
        type(base_field_address), intent(in) :: bs_trns_scalar
        type(energy_flux_address), intent(in) :: fs_trns_eflux
        type(spherical_transform_data), intent(in) :: trns_b_snap
        type(spherical_transform_data), intent(in) :: trns_b_scl
        type(spherical_transform_data), intent(inout) :: trns_f_eflux
Function/Subroutine Documentation
cal_buoyancy_flux_pin()
subroutine, private cal_buoyancy_flux_sph::cal_buoyancy_flux_pin (integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(3), intent(in) nidx_rtp, real(kind=kreal), dimension(nidx_rtp(1)), intent(in) radius, real(kind=kreal), intent(in) coef, real(kind=kreal), dimension(nnod_rtp), intent(in) scalar, real(kind=kreal), dimension(nnod_rtp), intent(in) vr, real(kind=kreal), dimension(nnod_rtp), intent(inout) prod) private
Definition at line 253 of file cal_buoyancy_flux_sph.f90.
Referenced by sel_buoyancy_flux_rtp().
cal_buoyancy_flux_rin()
subroutine, private cal_buoyancy_flux_sph::cal_buoyancy_flux_rin (integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), dimension(3), intent(in) nidx_rtp, real(kind=kreal), dimension(nidx_rtp(1)), intent(in) radius, real(kind=kreal), intent(in) coef, real(kind=kreal), dimension(nnod_rtp), intent(in) scalar, real(kind=kreal), dimension(nnod_rtp), intent(in) vr, real(kind=kreal), dimension(nnod_rtp), intent(inout) prod) private
Definition at line 226 of file cal_buoyancy_flux_sph.f90.
Referenced by sel_buoyancy_flux_rtp().
cal_buoyancy_flux_rtp()
subroutine cal_buoyancy_flux_sph::cal_buoyancy_flux_rtp (type(sph_rtp_grid), intent(in) sph_rtp, type(fluid_property), intent(in) fl_prop, type(reference_scalar_param), intent(in) ref_param_T, type(reference_scalar_param), intent(in) ref_param_C, type(base_field_address), intent(in) bs_trns_base, type(base_field_address), intent(in) bs_trns_scalar, type(energy_flux_address), intent(in) fs_trns_eflux, type(spherical_transform_data), intent(in) trns_b_snap, type(spherical_transform_data), intent(in) trns_b_scl, type(spherical_transform_data), intent(inout) trns_f_eflux)
Definition at line 56 of file cal_buoyancy_flux_sph.f90.
References t_reference_scalar_param::id_sphere_ref_temp, t_reference_scalar_param::id_takepiro_temp, and sel_buoyancy_flux_rtp().
Referenced by cal_energy_flux_rtp::s_cal_energy_flux_rtp().
pole_buoyancy_flux_rtp()
subroutine cal_buoyancy_flux_sph::pole_buoyancy_flux_rtp (type(sph_rtp_grid), intent(in) sph_rtp, type(fluid_property), intent(in) fl_prop, type(reference_scalar_param), intent(in) ref_param_T, type(reference_scalar_param), intent(in) ref_param_C, type(base_field_address), intent(in) bs_trns_base, type(base_field_address), intent(in) bs_trns_scalar, type(energy_flux_address), intent(in) fs_trns_eflux, type(spherical_transform_data), intent(in) trns_b_snap, type(spherical_transform_data), intent(in) trns_b_scl, type(spherical_transform_data), intent(inout) trns_f_eflux)
Definition at line 108 of file cal_buoyancy_flux_sph.f90.
References t_reference_scalar_param::id_sphere_ref_temp, t_reference_scalar_param::id_takepiro_temp, and pole_sph_buoyancy_flux().
Referenced by cal_energy_flux_rtp::s_cal_energy_flux_rtp().
pole_sph_buoyancy_flux()
subroutine, private cal_buoyancy_flux_sph::pole_sph_buoyancy_flux (integer(kind = kint), intent(in) nnod_pole, integer(kind = kint), intent(in) nidx_rtp_r, real(kind=kreal), dimension(nidx_rtp_r), intent(in) radius, real(kind = kreal), intent(in) coef, real(kind = kreal), dimension(nnod_pole), intent(in) t_pole, real(kind = kreal), dimension(nnod_pole,3), intent(in) v_pole, real(kind = kreal), dimension(nnod_pole), intent(inout) d_pole) private
Definition at line 171 of file cal_buoyancy_flux_sph.f90.
References m_constants::zero.
Referenced by pole_buoyancy_flux_rtp().
sel_buoyancy_flux_rtp()
subroutine cal_buoyancy_flux_sph::sel_buoyancy_flux_rtp (type(sph_rtp_grid), intent(in) sph_rtp, real(kind=kreal), intent(in) coef, real(kind=kreal), dimension(sph_rtp%nnod_rtp), intent(in) scalar, real(kind=kreal), dimension(sph_rtp%nnod_rtp), intent(in) vr, real(kind=kreal), dimension(sph_rtp%nnod_rtp), intent(inout) prod)
Definition at line 204 of file cal_buoyancy_flux_sph.f90.
References cal_buoyancy_flux_pin(), and cal_buoyancy_flux_rin().
Referenced by cal_buoyancy_flux_rtp().