CALYPSO: center_sph_matrices Module Reference
center_sph_matrices Module Reference
Construct matrix for center.
Functions/Subroutines
subroutine copy_to_band3_mat_w_center (nri, c_evo, mat3, mat00_3)
subroutine add_scalar_poisson_mat_fill_ctr (nri, r_CTR1, fdm2_fix_dr_center, fdm2_fix_fld_ctr1, coef_p, mat00_3)
subroutine add_scalar_poisson_mat_fix_ctr (nri, r_CTR1, fdm2_fix_fld_ctr1, coef_p, mat00_3)
subroutine add_scalar_poisson_mat_no_fld (nri, mat00_3)
subroutine add_vector_poisson_mat_center (nri, jmax, g_sph_rj, r_CTR1, fdm2_fix_fld_ctr1, coef_p, mat3)
subroutine add_scalar_poisson_mat_ctr1 (nri, jmax, g_sph_rj, r_CTR1, fdm2_fix_fld_ctr1, coef_p, mat3)
Detailed Description
Construct matrix for center.
      subroutine copy_to_band3_mat_w_center(nri, c_evo, mat3, mat00_3)
      subroutine add_scalar_poisson_mat_fill_ctr(nri, r_CTR1,         &
     &          fdm2_fix_dr_center, fdm2_fix_fld_ctr1, coef_p, mat00_3)
      subroutine add_scalar_poisson_mat_fix_ctr(nri, r_CTR1,          &
     &          fdm2_fix_fld_ctr1, coef_p, mat00_3)
      subroutine add_scalar_poisson_mat_no_fld(nri, mat00_3)
      subroutine add_vector_poisson_mat_center(nri, jmax, g_sph_rj,   &
     &          r_CTR1, fdm2_fix_fld_ctr1, coef_p, mat3)
      subroutine add_scalar_poisson_mat_ctr1(nri, jmax, g_sph_rj,     &
     &          r_CTR1, fdm2_fix_fld_ctr1, coef_p, mat3)
Function/Subroutine Documentation
add_scalar_poisson_mat_ctr1()
subroutine center_sph_matrices::add_scalar_poisson_mat_ctr1 (integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, real(kind = kreal), dimension(0:2), intent(in) r_CTR1, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_fix_fld_ctr1, real(kind = kreal), intent(in) coef_p, real(kind = kreal), dimension(3,nri,jmax), intent(inout) mat3)
Definition at line 172 of file center_sph_matrices.f90.
References m_constants::two.
Referenced by const_r_mat_4_scalar_sph::const_radial_mat_4_press_sph(), and const_r_mat_4_scalar_sph::const_radial_mat_4_scalar_sph().
add_scalar_poisson_mat_fill_ctr()
subroutine center_sph_matrices::add_scalar_poisson_mat_fill_ctr (integer(kind = kint), intent(in) nri, real(kind = kreal), dimension(0:2), intent(in) r_CTR1, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_fix_dr_center, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_fix_fld_ctr1, real(kind = kreal), intent(in) coef_p, real(kind = kreal), dimension(3,0:nri), intent(inout) mat00_3)
Definition at line 77 of file center_sph_matrices.f90.
References m_constants::two.
Referenced by const_r_mat_w_center_sph::const_rmat_press00_sph(), and const_r_mat_w_center_sph::const_rmat_scalar00_sph().
add_scalar_poisson_mat_fix_ctr()
subroutine center_sph_matrices::add_scalar_poisson_mat_fix_ctr (integer(kind = kint), intent(in) nri, real(kind = kreal), dimension(0:2), intent(in) r_CTR1, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_fix_fld_ctr1, real(kind = kreal), intent(in) coef_p, real(kind = kreal), dimension(3,0:nri), intent(inout) mat00_3)
Definition at line 105 of file center_sph_matrices.f90.
References m_constants::one, m_constants::two, and m_constants::zero.
Referenced by const_r_mat_w_center_sph::const_rmat_scalar00_sph().
add_scalar_poisson_mat_no_fld()
subroutine center_sph_matrices::add_scalar_poisson_mat_no_fld (integer(kind = kint), intent(in) nri, real(kind = kreal), dimension(3,0:nri), intent(inout) mat00_3)
Definition at line 130 of file center_sph_matrices.f90.
References m_constants::one, and m_constants::zero.
Referenced by const_r_mat_w_center_sph::const_rmat_press00_sph(), and const_r_mat_w_center_sph::const_rmat_scalar00_sph().
add_vector_poisson_mat_center()
subroutine center_sph_matrices::add_vector_poisson_mat_center (integer(kind = kint), intent(in) nri, integer(kind = kint), intent(in) jmax, real(kind = kreal), dimension(jmax,13), intent(in) g_sph_rj, real(kind = kreal), dimension(0:2), intent(in) r_CTR1, real(kind = kreal), dimension(-1:1,3), intent(in) fdm2_fix_fld_ctr1, real(kind = kreal), intent(in) coef_p, real(kind = kreal), dimension(3,nri,jmax), intent(inout) mat3)
Definition at line 148 of file center_sph_matrices.f90.
Referenced by const_r_mat_4_vector_sph::const_radial_mat_4_magne_sph(), and const_r_mat_4_vector_sph::const_radial_mat_vort_2step().
copy_to_band3_mat_w_center()
subroutine center_sph_matrices::copy_to_band3_mat_w_center (integer(kind = kint), intent(in) nri, real(kind = kreal), intent(in) c_evo, real(kind = kreal), dimension(3,nri), intent(in) mat3, real(kind = kreal), dimension(3,0:nri), intent(inout) mat00_3)
Definition at line 42 of file center_sph_matrices.f90.
References m_constants::one, and m_constants::zero.
Referenced by const_r_mat_w_center_sph::const_rmat_press00_sph(), and const_r_mat_w_center_sph::const_rmat_scalar00_sph().