CALYPSO: analyzer_vtk_convert Module Reference
analyzer_vtk_convert Module Reference
Functions/Subroutines
subroutine init_analyzer_vtk_convert
subroutine analyze_vtk_convert
Variables
type(time_step_param_w_viz), save t_viz5
Structure for time stepping parameters with field and visualization.
type(control_data_section_only), save sec_viz_ctl5
Structure of control data for sectioning only.
type(fem_mesh_field_4_surfacing), save sfcing5
Structure of mesh and field for sectioning only.
type(ucd_data), save vtk_out5
FEM field data to VTK.
Function/Subroutine Documentation
analyze_vtk_convert()
subroutine analyzer_vtk_convert::analyze_vtk_convert
Definition at line 75 of file analyzer_VTK_convert.f90.
References m_work_time::end_elapsed_time(), fem_analyzer_vtk_convert::fem_analyze_vtk_convert(), m_work_time::ied_total_elapsed, m_work_time::iflag_tot_time, m_work_time::output_elapsed_times(), sfcing5, t_viz5, t_viz_vtk_convert::visualize_convert_vtk(), and vtk_out5.
Referenced by kemorin_convert_to_vtk().
init_analyzer_vtk_convert()
subroutine analyzer_vtk_convert::init_analyzer_vtk_convert
Definition at line 38 of file analyzer_VTK_convert.f90.
References calypso_mpi::calypso_mpi_abort(), m_elapsed_labels_4_viz::elpsed_label_4_viz(), m_elapsed_labels_send_recv::elpsed_label_field_send_recv(), fem_analyzer_vtk_convert::fem_initialize_vtk_convert(), m_work_time::ied_total_elapsed, m_work_time::iflag_tot_time, m_work_time::init_elapse_time_by_total(), t_viz_vtk_convert::init_visualize_convert_vtk(), t_control_data_section_only::read_control_data_section_only(), sec_viz_ctl5, load_mesh_and_field_4_viz::set_control_params_4_viz(), sfcing5, m_work_time::start_elapsed_time(), t_viz5, and vtk_out5.
Referenced by kemorin_convert_to_vtk().
Variable Documentation
sec_viz_ctl5
type(control_data_section_only), save analyzer_vtk_convert::sec_viz_ctl5
Structure of control data for sectioning only.
Definition at line 26 of file analyzer_VTK_convert.f90.
Referenced by init_analyzer_vtk_convert().
sfcing5
type(fem_mesh_field_4_surfacing), save analyzer_vtk_convert::sfcing5
Structure of mesh and field for sectioning only.
Definition at line 28 of file analyzer_VTK_convert.f90.
Referenced by analyze_vtk_convert(), and init_analyzer_vtk_convert().
t_viz5
type(time_step_param_w_viz), save analyzer_vtk_convert::t_viz5
Structure for time stepping parameters with field and visualization.
Definition at line 24 of file analyzer_VTK_convert.f90.
Referenced by analyze_vtk_convert(), and init_analyzer_vtk_convert().
vtk_out5
type(ucd_data), save analyzer_vtk_convert::vtk_out5
FEM field data to VTK.
Definition at line 30 of file analyzer_VTK_convert.f90.
Referenced by analyze_vtk_convert(), and init_analyzer_vtk_convert().