CALYPSO: set_control_4_magne Module Reference
set_control_4_magne Module Reference
set boundary conditions for magnetic field from control data
Functions/Subroutines
subroutine s_set_control_4_magne (cd_prop, node_bc_B_ctl, surf_bc_BN_ctl, magne_nod, magne_surf)
Detailed Description
set boundary conditions for magnetic field from control data
      subroutine s_set_control_4_magne                                &
     &         (cd_prop, node_bc_B_ctl, surf_bc_BN_ctl,               &
     &          magne_nod, magne_surf)
        type(conductive_property), intent(in)  :: cd_prop
        type(ctl_array_c2r), intent(in) :: node_bc_B_ctl
        type(ctl_array_c2r), intent(in) :: surf_bc_BN_ctl
        type(boundary_condition_list), intent(inout) :: magne_nod
        type(boundary_condition_list), intent(inout) :: magne_surf
Function/Subroutine Documentation
s_set_control_4_magne()
subroutine set_control_4_magne::s_set_control_4_magne (type(conductive_property), intent(in) cd_prop, type(ctl_array_c2r), intent(in) node_bc_B_ctl, type(ctl_array_c2r), intent(in) surf_bc_BN_ctl, type(boundary_condition_list), intent(inout) magne_nod, type(boundary_condition_list), intent(inout) magne_surf)
Definition at line 33 of file set_control_4_magne.f90.
References t_bc_data_list::alloc_bc_type_ctl(), t_physical_property::id_no_evolution, m_machine_parameter::iflag_debug, m_machine_parameter::iflag_routine_msg, set_node_group_types::set_bc_group_types_sgs_vect(), set_node_group_types::set_bc_group_types_sph_center(), set_node_group_types::set_bc_group_types_sph_magne(), set_node_group_types::set_bc_group_types_vector(), and set_surface_group_types::set_surf_group_types_vector().
Referenced by set_control_sph_mhd::set_control_sph_mhd_bcs().