CALYPSO: gz_element_file_io_b Module Reference
gz_element_file_io_b Module Reference
File IO for element communication table.
Functions/Subroutines
subroutine gz_input_element_file_b (id_rank, file_name, ele_mesh_IO, ierr)
subroutine gz_input_surface_file_b (id_rank, file_name, surf_mesh_IO, ierr)
subroutine gz_input_edge_file_b (id_rank, file_name, edge_mesh_IO, ierr)
subroutine gz_output_element_file_b (id_rank, file_name, ele_mesh_IO)
subroutine gz_output_surface_file_b (id_rank, file_name, surf_mesh_IO)
subroutine gz_output_edge_file_b (id_rank, file_name, edge_mesh_IO)
Variables
type(buffer_4_gzip), private zbuf_ele
Detailed Description
File IO for element communication table.
      subroutine gz_input_element_file_b                              &
     &         (id_rank, file_name, ele_mesh_IO, ierr)
      subroutine gz_input_surface_file_b                              &
     &         (id_rank, file_name, surf_mesh_IO, ierr)
      subroutine gz_input_edge_file_b                                 &
     &         (id_rank, file_name, edge_mesh_IO, ierr)
        type(surf_edge_IO_file), intent(inout) :: ele_mesh_IO
        type(surf_edge_IO_file), intent(inout) :: surf_mesh_IO
        type(surf_edge_IO_file), intent(inout) :: edge_mesh_IO
      subroutine gz_output_element_file_b                             &
     &         (id_rank, ele_mesh_IO)
      subroutine gz_output_surface_file_b                             &
     &         (id_rank, file_name, surf_mesh_IO)
      subroutine gz_output_edge_file_b                                &
     &         (id_rank, file_name, edge_mesh_IO)
        type(surf_edge_IO_file), intent(in) :: ele_mesh_IO
        type(surf_edge_IO_file), intent(in) :: surf_mesh_IO
        type(surf_edge_IO_file), intent(in) :: edge_mesh_IO
Parameters
id_rank MPI rank
Function/Subroutine Documentation
gz_input_edge_file_b()
subroutine gz_element_file_io_b::gz_input_edge_file_b (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(inout) edge_mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 116 of file gz_element_file_IO_b.f90.
References gzip_file_access::close_gzfile_b(), gz_edge_data_io_b::gz_read_edge_connection_b(), m_machine_parameter::i_debug, and zbuf_ele.
Referenced by element_mesh_io_select::sel_read_edge_mesh().
gz_input_element_file_b()
subroutine gz_element_file_io_b::gz_input_element_file_b (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(inout) ele_mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 54 of file gz_element_file_IO_b.f90.
References gzip_file_access::close_gzfile_b(), gz_element_data_io_b::gz_read_element_comm_table_b(), m_machine_parameter::i_debug, and zbuf_ele.
Referenced by element_mesh_io_select::sel_read_ele_mesh().
gz_input_surface_file_b()
subroutine gz_element_file_io_b::gz_input_surface_file_b (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(inout) surf_mesh_IO, integer(kind = kint), intent(inout) ierr)
Definition at line 85 of file gz_element_file_IO_b.f90.
References gzip_file_access::close_gzfile_b(), gz_surface_data_io_b::gz_read_surface_connection_b(), m_machine_parameter::i_debug, and zbuf_ele.
Referenced by element_mesh_io_select::sel_read_surf_mesh().
gz_output_edge_file_b()
subroutine gz_element_file_io_b::gz_output_edge_file_b (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(in) edge_mesh_IO)
Definition at line 198 of file gz_element_file_IO_b.f90.
References gzip_file_access::close_gzfile_b(), gz_edge_data_io_b::gz_write_edge_connection_b(), m_machine_parameter::i_debug, and zbuf_ele.
Referenced by element_mesh_io_select::sel_write_edge_mesh_file().
gz_output_element_file_b()
subroutine gz_element_file_io_b::gz_output_element_file_b (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(in) ele_mesh_IO)
Definition at line 148 of file gz_element_file_IO_b.f90.
References gzip_file_access::close_gzfile_b(), gz_element_data_io_b::gz_write_element_comm_table_b(), m_machine_parameter::i_debug, and zbuf_ele.
Referenced by element_mesh_io_select::sel_write_ele_mesh_file().
gz_output_surface_file_b()
subroutine gz_element_file_io_b::gz_output_surface_file_b (integer, intent(in) id_rank, character(len=kchara), intent(in) file_name, type(surf_edge_io_file), intent(in) surf_mesh_IO)
Definition at line 173 of file gz_element_file_IO_b.f90.
References gzip_file_access::close_gzfile_b(), gz_surface_data_io_b::gz_write_surface_connection_b(), m_machine_parameter::i_debug, and zbuf_ele.
Referenced by element_mesh_io_select::sel_write_surf_mesh_file().
Variable Documentation
zbuf_ele
type(buffer_4_gzip), private gz_element_file_io_b::zbuf_ele private
Definition at line 46 of file gz_element_file_IO_b.f90.
Referenced by gz_input_edge_file_b(), gz_input_element_file_b(), gz_input_surface_file_b(), gz_output_edge_file_b(), gz_output_element_file_b(), and gz_output_surface_file_b().