CALYPSO: leg_b_trans_sym_matmul_big Module Reference
leg_b_trans_sym_matmul_big Module Reference
backward Legendre transform (Blocked loop version)
Functions/Subroutines
subroutine leg_bwd_trans_sym_matmul_big (iflag_matmul, ncomp, nvector, nscalar, sph_rlm, sph_rtm, comm_rlm, comm_rtm, idx_trns, asin_theta_1d_rtm, g_sph_rlm, n_WR, n_WS, WR, WS, WK_l_bsm)
Variables
integer, external omp_get_max_threads
Detailed Description
backward Legendre transform (Blocked loop version)
      subroutine leg_bwd_trans_sym_matmul_big(ncomp, nvector,         &
     &          sph_rlm, sph_rtm, comm_rlm, comm_rtm, idx_trns,       &
     &          asin_theta_1d_rtm, g_sph_rlm,                         &
     &          n_WR, n_WS, WR, WS, WK_l_bsm)
        type(sph_rlm_grid), intent(in) :: sph_rlm
        type(sph_rtm_grid), intent(in) :: sph_rtm
        type(sph_comm_tbl), intent(in) :: comm_rlm, comm_rtm
        type(index_4_sph_trans), intent(in) :: idx_trns
        type(leg_trns_bsym_mul_work), intent(inout) :: WK_l_bsm
        Input:  vr_rtm   (Order: radius,theta,phi)
        Output: sp_rlm   (Order: poloidal,diff_poloidal,toroidal)
Parameters
ncomp Total number of components for spherical transform
nvector Number of vector for spherical transform
nscalar Number of scalar (including tensor components) for spherical transform
Function/Subroutine Documentation
leg_bwd_trans_sym_matmul_big()
subroutine leg_b_trans_sym_matmul_big::leg_bwd_trans_sym_matmul_big (integer(kind = kint), intent(in) iflag_matmul, integer(kind = kint), intent(in) ncomp, integer(kind = kint), intent(in) nvector, integer(kind = kint), intent(in) nscalar, type(sph_rlm_grid), intent(in) sph_rlm, type(sph_rtm_grid), intent(in) sph_rtm, type(sph_comm_tbl), intent(in) comm_rlm, type(sph_comm_tbl), intent(in) comm_rtm, type(index_4_sph_trans), intent(in) idx_trns, real(kind = kreal), dimension(sph_rtm%nidx_rtm(2)), intent(in) asin_theta_1d_rtm, real(kind = kreal), dimension(sph_rlm%nidx_rlm(2),17), intent(in) g_sph_rlm, integer(kind = kint), intent(in) n_WR, integer(kind = kint), intent(in) n_WS, real (kind=kreal), dimension(n_wr), intent(inout) WR, real (kind=kreal), dimension(n_ws), intent(inout) WS, type(leg_trns_bsym_mul_work), intent(inout) WK_l_bsm)
Definition at line 59 of file leg_b_trans_sym_matmul_big.f90.
References set_vr_rtm_leg_matmul_big::cal_vr_rtm_scl_sym_matmul_big(), set_vr_rtm_leg_matmul_big::cal_vr_rtm_vec_sym_matmul_big(), m_work_time::elps1, m_elapsed_labels_sph_trns::iflag_sdt_time, m_elapsed_labels_sph_trns::ist_elapsed_sdt, matmul_for_legendre_trans::matmul_bwd_leg_trans(), set_sp_rlm_leg_matmul_big::set_sp_rlm_scl_sym_matmul_big(), and set_sp_rlm_leg_matmul_big::set_sp_rlm_vec_sym_matmul_big().
Referenced by legendre_trans_matmul_big::leg_backward_trans_matmul_big().
Variable Documentation
omp_get_max_threads
integer, external leg_b_trans_sym_matmul_big::omp_get_max_threads
Definition at line 51 of file leg_b_trans_sym_matmul_big.f90.