CALYPSO: bcast_4_time_step_ctl Module Reference
bcast_4_time_step_ctl Module Reference
Bloardcast for time step parameters.
Functions/Subroutines
subroutine bcast_ctl_data_4_time_step (tctl)
Detailed Description
Bloardcast for time step parameters.
      subroutine bcast_ctl_data_4_time_step(tctl)
        type(time_data_control), intent(inout) :: tctl
Function/Subroutine Documentation
bcast_ctl_data_4_time_step()
subroutine bcast_4_time_step_ctl::bcast_ctl_data_4_time_step (type(time_data_control), intent(inout) tctl)
Definition at line 28 of file bcast_4_time_step_ctl.f90.
References bcast_control_arrays::bcast_ctl_type_c1(), bcast_control_arrays::bcast_ctl_type_i1(), bcast_control_arrays::bcast_ctl_type_r1(), and calypso_mpi_int::calypso_mpi_bcast_one_int().
Referenced by bcast_4_assemble_sph_ctl::bcast_merge_step_data(), t_control_data_section_only::bcast_section_control_data(), and t_ctl_data_sph_mhd_control::bcast_sph_mhd_control().