CALYPSO: copy_para_sph_global_params Module Reference
copy_para_sph_global_params Module Reference
Set control data for domain decomposition for spherical transform.
Functions/Subroutines
subroutine copy_para_sph_param_from_ctl (sph_org, num_pe, sph_mesh)
subroutine copy_para_global_sph_resolution (sph_org, num_pe, sph_mesh)
subroutine copy_each_sph_param_from_ctl (sph_org, sph_params, sph_rtp, sph_rj)
subroutine copy_each_global_sph_resolution (sph_org, sph_rtp, sph_rtm, sph_rlm, sph_rj)
Detailed Description
Set control data for domain decomposition for spherical transform.
      subroutine copy_para_sph_param_from_ctl                         &
     &         (sph_org, num_pe, sph_mesh)
      subroutine copy_para_global_sph_resolution                      &
     &         (sph_org, num_pe, sph_mesh)
        integer(kind = kint), intent(in) :: num_pe
        type(sph_grids), intent(in) :: sph_org
        type(sph_mesh_data), intent(inout) :: sph_mesh(num_pe)
Function/Subroutine Documentation
copy_each_global_sph_resolution()
subroutine copy_para_sph_global_params::copy_each_global_sph_resolution (type(sph_grids), intent(in) sph_org, type(sph_rtp_grid), intent(inout) sph_rtp, type(sph_rtm_grid), intent(inout) sph_rtm, type(sph_rlm_grid), intent(inout) sph_rlm, type(sph_rj_grid), intent(inout) sph_rj)
Definition at line 115 of file copy_para_sph_global_params.f90.
Referenced by copy_para_global_sph_resolution(), mpi_gen_sph_grids_modes::mpi_gen_sph_grids(), and mpi_gen_sph_grids_modes::mpi_gen_sph_rj_mode().
copy_each_sph_param_from_ctl()
subroutine copy_para_sph_global_params::copy_each_sph_param_from_ctl (type(sph_grids), intent(in) sph_org, type(sph_shell_parameters), intent(inout) sph_params, type(sph_rtp_grid), intent(inout) sph_rtp, type(sph_rj_grid), intent(inout) sph_rj)
Definition at line 80 of file copy_para_sph_global_params.f90.
Referenced by copy_para_sph_param_from_ctl(), mpi_gen_sph_grids_modes::mpi_gen_sph_grids(), and mpi_gen_sph_grids_modes::mpi_gen_sph_rj_mode().
copy_para_global_sph_resolution()
subroutine copy_para_sph_global_params::copy_para_global_sph_resolution (type(sph_grids), intent(in) sph_org, integer(kind = kint), intent(in) num_pe, type(sph_mesh_data), dimension(num_pe), intent(inout) sph_mesh)
Definition at line 57 of file copy_para_sph_global_params.f90.
References copy_each_global_sph_resolution().
Referenced by parallel_gen_sph_grids::para_gen_sph_grids(), and parallel_gen_sph_grids::para_gen_sph_rj_mode().
copy_para_sph_param_from_ctl()
subroutine copy_para_sph_global_params::copy_para_sph_param_from_ctl (type(sph_grids), intent(in) sph_org, integer(kind = kint), intent(in) num_pe, type(sph_mesh_data), dimension(num_pe), intent(inout) sph_mesh)
Definition at line 34 of file copy_para_sph_global_params.f90.
References copy_each_sph_param_from_ctl().
Referenced by parallel_gen_sph_grids::para_gen_sph_grids(), and parallel_gen_sph_grids::para_gen_sph_rj_mode().