CALYPSO: gz_ucd_data_io Module Reference
gz_ucd_data_io Module Reference
Output routine for gzipped UCD data segments.
Functions/Subroutines
subroutine write_gz_udt_field_header (num_output, ncomp_out, name_out, zbuf)
subroutine write_gz_ucd_field_data (ntot_nod, ncomp_dat, nnod, inod_out, dat_out, zbuf)
subroutine write_gz_udt_mesh_header (nnod_output, nele_out, ncomp_output, zbuf)
subroutine write_gz_ucd_mesh_connect (ntot_ele, nnod_ele, nele, iele_gl, ie_gl, zbuf)
subroutine read_gz_udt_field_num (num_input, zbuf)
subroutine read_gz_udt_field_name (num_input, ncomp_in, name_in, zbuf)
subroutine read_gz_udt_field_data (nnod_in, ncomp_dat, dat_in, zbuf)
subroutine read_gz_udt_mesh_header (nnod_input, nele_in, ncomptot_in, zbuf)
subroutine read_gz_ucd_node_data (nnod_in, inod_gl, xx_in, zbuf)
subroutine read_gz_ucd_ele_connect (nele_in, nnod_ele, iele_gl, ie_in, zbuf)
Detailed Description
Output routine for gzipped UCD data segments.
      subroutine write_gz_udt_field_header(num_output,                &
     &          ncomp_out, name_out, zbuf)
      subroutine write_gz_ucd_field_data(ntot_nod, ncomp_dat, nnod,   &
     &          inod_out, dat_out, zbuf)
      subroutine write_gz_udt_mesh_header                             &
     &         (nnod_output, nele_out, ncomp_output, zbuf)
      subroutine write_gz_ucd_mesh_connect                            &
     &         (ntot_ele, nnod_ele, nele, iele_gl, ie_gl, zbuf)
        type(buffer_4_gzip), intent(inout) :: zbuf
      subroutine read_gz_udt_field_num(num_input, zbuf)
      subroutine read_gz_udt_field_name                               &
     &         (num_input, ncomp_in, name_in, zbuf)
      subroutine read_gz_udt_field_data                               &
     &         (nnod_in, ncomp_dat, dat_in, zbuf)
      subroutine read_gz_udt_mesh_header                              &
     &         (nnod_input, nele_in, ncomptot_in, zbuf)
      subroutine read_gz_ucd_node_data(nnod_in, inod_gl, xx_in, zbuf)
      subroutine read_gz_ucd_ele_connect                              &
     &         (nele_in, nnod_ele, iele_gl, ie_in, zbuf)
        type(buffer_4_gzip), intent(inout) :: zbuf
Function/Subroutine Documentation
read_gz_ucd_ele_connect()
subroutine gz_ucd_data_io::read_gz_ucd_ele_connect (integer(kind=kint_gl), intent(in) nele_in, integer(kind=kint), intent(in) nnod_ele, integer(kind=kint_gl), dimension(nele_in), intent(inout) iele_gl, integer(kind=kint_gl), dimension(nele_in,nnod_ele), intent(inout) ie_in, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 285 of file gz_ucd_data_IO.f90.
References gzip_file_access::get_one_line_text_from_gz(), and ucd_data_to_buffer::nnod_ele_by_ucd_eletype().
Referenced by gz_udt_type_data_io::read_gz_ucd_mesh_data().
read_gz_ucd_node_data()
subroutine gz_ucd_data_io::read_gz_ucd_node_data (integer(kind=kint_gl), intent(in) nnod_in, integer(kind=kint_gl), dimension(nnod_in), intent(inout) inod_gl, real(kind = kreal), dimension(nnod_in,3), intent(inout) xx_in, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 263 of file gz_ucd_data_IO.f90.
References gzip_file_access::get_one_line_text_from_gz().
Referenced by gz_udt_type_data_io::read_alloc_gz_ucd_mesh_data(), and gz_udt_type_data_io::read_gz_ucd_mesh_data().
read_gz_udt_field_data()
subroutine gz_ucd_data_io::read_gz_udt_field_data (integer(kind = kint_gl), intent(in) nnod_in, integer(kind = kint), intent(in) ncomp_dat, real(kind = kreal), dimension(nnod_in, ncomp_dat), intent(inout) dat_in, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 209 of file gz_ucd_data_IO.f90.
References gzip_file_access::get_one_line_text_from_gz().
Referenced by gz_udt_file_io::read_alloc_gz_ucd_file(), gz_udt_file_io::read_alloc_gz_udt_file(), and gz_udt_type_data_io::read_gz_udt_field().
read_gz_udt_field_name()
subroutine gz_ucd_data_io::read_gz_udt_field_name (integer(kind = kint), intent(inout) num_input, integer(kind = kint), dimension(num_input), intent(inout) ncomp_in, character(len = kchara), dimension(num_input), intent(inout) name_in, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 175 of file gz_ucd_data_IO.f90.
References gzip_file_access::get_one_line_text_from_gz().
Referenced by gz_udt_type_data_io::read_alloc_gz_udt_field(), and gz_udt_type_data_io::read_gz_udt_field().
read_gz_udt_field_num()
subroutine gz_ucd_data_io::read_gz_udt_field_num (integer(kind = kint), intent(inout) num_input, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 160 of file gz_ucd_data_IO.f90.
References gzip_file_access::get_one_line_text_from_gz().
Referenced by gz_udt_type_data_io::read_alloc_gz_udt_field(), and gz_udt_type_data_io::read_gz_udt_field().
read_gz_udt_mesh_header()
subroutine gz_ucd_data_io::read_gz_udt_mesh_header (integer(kind = kint_gl), intent(inout) nnod_input, integer(kind = kint_gl), intent(inout) nele_in, integer(kind = kint), intent(inout) ncomptot_in, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 243 of file gz_ucd_data_IO.f90.
References gzip_file_access::get_one_line_text_from_gz().
Referenced by gz_udt_type_data_io::read_alloc_gz_ucd_mesh_data(), and gz_udt_type_data_io::read_gz_ucd_mesh_data().
write_gz_ucd_field_data()
subroutine gz_ucd_data_io::write_gz_ucd_field_data (integer(kind = kint_gl), intent(in) ntot_nod, integer(kind = kint), intent(in) ncomp_dat, integer(kind = kint_gl), intent(in) nnod, integer(kind = kint_gl), dimension(ntot_nod), intent(in) inod_out, real(kind = kreal), dimension(ntot_nod, ncomp_dat), intent(in) dat_out, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 81 of file gz_ucd_data_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf(), and ucd_data_to_buffer::ucd_each_field().
Referenced by gz_udt_type_data_io::write_gz_ucd_type_mesh(), and gz_udt_type_data_io::write_gz_udt_type_fields().
write_gz_ucd_mesh_connect()
subroutine gz_ucd_data_io::write_gz_ucd_mesh_connect (integer(kind=kint_gl), intent(in) ntot_ele, integer(kind=kint), intent(in) nnod_ele, integer(kind=kint_gl), intent(in) nele, integer(kind=kint_gl), dimension(ntot_ele), intent(in) iele_gl, integer(kind=kint_gl), dimension(ntot_ele,nnod_ele), intent(in) ie_gl, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 130 of file gz_ucd_data_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf(), and ucd_data_to_buffer::ucd_each_connect().
Referenced by gz_udt_type_data_io::write_gz_ucd_type_mesh().
write_gz_udt_field_header()
subroutine gz_ucd_data_io::write_gz_udt_field_header (integer(kind = kint), intent(in) num_output, integer(kind = kint), dimension(num_output), intent(in) ncomp_out, character(len = kchara), dimension(num_output), intent(in) name_out, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 49 of file gz_ucd_data_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf().
Referenced by gz_udt_type_data_io::write_gz_udt_type_fields().
write_gz_udt_mesh_header()
subroutine gz_ucd_data_io::write_gz_udt_mesh_header (integer(kind = kint_gl), intent(in) nnod_output, integer(kind = kint_gl), intent(in) nele_out, integer(kind = kint), intent(in) ncomp_output, type(buffer_4_gzip), intent(inout) zbuf)
Definition at line 109 of file gz_ucd_data_IO.f90.
References gzip_file_access::gz_write_textbuf_no_lf(), and ucd_data_to_buffer::ucd_connect_head().
Referenced by gz_udt_type_data_io::write_gz_ucd_type_mesh().