CALYPSO: cmp_trans_sph_indices Module Reference
cmp_trans_sph_indices Module Reference
Functions/Subroutines
subroutine allocate_idx_sph_recieve (nnod_rtp, nnod_rtm, nnod_rlm, nnod_rj)
subroutine deallocate_idx_sph_recieve
subroutine sph_type_indices_transfer (iflag_recv, sph, comms_sph)
subroutine, private sph_indices_transfer (iflag_recv, comms_sph, nnod_rtp, nnod_rtm, nnod_rlm, nnod_rj, idx_global_rtp, idx_global_rtm, idx_global_rlm, idx_global_rj)
integer(kind=kint) function compare_transfer_sph_indices (id_check, sph)
integer(kind=kint) function check_missing_sph_indices (id_file, sph)
Variables
integer(kind=kint), dimension(:,:), allocatable idx_rtp_recieve
integer(kind=kint), dimension(:,:), allocatable idx_rtm_recieve
integer(kind=kint), dimension(:,:), allocatable idx_rlm_recieve
integer(kind=kint), dimension(:,:), allocatable idx_rj_recieve
Function/Subroutine Documentation
allocate_idx_sph_recieve()
subroutine cmp_trans_sph_indices::allocate_idx_sph_recieve (integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) nnod_rtm, integer(kind = kint), intent(in) nnod_rlm, integer(kind = kint), intent(in) nnod_rj)
Definition at line 39 of file cmp_trans_sph_indices.f90.
References idx_rj_recieve, idx_rlm_recieve, idx_rtm_recieve, and idx_rtp_recieve.
Referenced by analyzer_test_sph::analyze_test_sph().
check_missing_sph_indices()
integer(kind = kint) function cmp_trans_sph_indices::check_missing_sph_indices (integer(kind = kint), intent(in) id_file, type(sph_grids), intent(in) sph)
Definition at line 251 of file cmp_trans_sph_indices.f90.
References idx_rj_recieve, idx_rlm_recieve, idx_rtm_recieve, idx_rtp_recieve, and calypso_mpi::my_rank.
Referenced by analyzer_test_sph::analyze_test_sph().
compare_transfer_sph_indices()
integer(kind = kint) function cmp_trans_sph_indices::compare_transfer_sph_indices (integer(kind = kint), intent(in) id_check, type(sph_grids), intent(in) sph)
Definition at line 157 of file cmp_trans_sph_indices.f90.
References idx_rj_recieve, idx_rlm_recieve, idx_rtm_recieve, idx_rtp_recieve, and calypso_mpi::my_rank.
Referenced by analyzer_test_sph::analyze_test_sph().
deallocate_idx_sph_recieve()
subroutine cmp_trans_sph_indices::deallocate_idx_sph_recieve
Definition at line 59 of file cmp_trans_sph_indices.f90.
References idx_rj_recieve, idx_rlm_recieve, idx_rtm_recieve, and idx_rtp_recieve.
Referenced by analyzer_test_sph::analyze_test_sph().
sph_indices_transfer()
subroutine, private cmp_trans_sph_indices::sph_indices_transfer (integer(kind = kint), intent(in) iflag_recv, type(sph_comm_tables), intent(in) comms_sph, integer(kind = kint), intent(in) nnod_rtp, integer(kind = kint), intent(in) nnod_rtm, integer(kind = kint), intent(in) nnod_rlm, integer(kind = kint), intent(in) nnod_rj, integer(kind = kint), dimension(nnod_rtp,3), intent(in) idx_global_rtp, integer(kind = kint), dimension(nnod_rtm,3), intent(in) idx_global_rtm, integer(kind = kint), dimension(nnod_rlm,2), intent(in) idx_global_rlm, integer(kind = kint), dimension(nnod_rj,2), intent(in) idx_global_rj) private
Definition at line 93 of file cmp_trans_sph_indices.f90.
References idx_rj_recieve, idx_rlm_recieve, idx_rtm_recieve, idx_rtp_recieve, calypso_mpi::my_rank, and spherical_srs_n::send_recv_sph_trans_int().
Referenced by sph_type_indices_transfer().
sph_type_indices_transfer()
subroutine cmp_trans_sph_indices::sph_type_indices_transfer (integer(kind = kint), intent(in) iflag_recv, type(sph_grids), intent(in) sph, type(sph_comm_tables), intent(in) comms_sph)
Definition at line 71 of file cmp_trans_sph_indices.f90.
References sph_indices_transfer().
Referenced by analyzer_test_sph::analyze_test_sph().
Variable Documentation
idx_rj_recieve
integer(kind = kint), dimension(:,:), allocatable cmp_trans_sph_indices::idx_rj_recieve
Definition at line 29 of file cmp_trans_sph_indices.f90.
Referenced by allocate_idx_sph_recieve(), check_missing_sph_indices(), compare_transfer_sph_indices(), cmp_trans_sph_tests::compare_transfer_sph_reals(), deallocate_idx_sph_recieve(), and sph_indices_transfer().
idx_rlm_recieve
integer(kind = kint), dimension(:,:), allocatable cmp_trans_sph_indices::idx_rlm_recieve
Definition at line 28 of file cmp_trans_sph_indices.f90.
Referenced by allocate_idx_sph_recieve(), check_missing_sph_indices(), compare_transfer_sph_indices(), cmp_trans_sph_tests::compare_transfer_sph_reals(), deallocate_idx_sph_recieve(), and sph_indices_transfer().
idx_rtm_recieve
integer(kind = kint), dimension(:,:), allocatable cmp_trans_sph_indices::idx_rtm_recieve
Definition at line 27 of file cmp_trans_sph_indices.f90.
Referenced by allocate_idx_sph_recieve(), check_missing_sph_indices(), compare_transfer_sph_indices(), cmp_trans_sph_tests::compare_transfer_sph_reals(), deallocate_idx_sph_recieve(), and sph_indices_transfer().
idx_rtp_recieve
integer(kind = kint), dimension(:,:), allocatable cmp_trans_sph_indices::idx_rtp_recieve
Definition at line 26 of file cmp_trans_sph_indices.f90.
Referenced by allocate_idx_sph_recieve(), check_missing_sph_indices(), compare_transfer_sph_indices(), cmp_trans_sph_tests::compare_transfer_sph_reals(), deallocate_idx_sph_recieve(), and sph_indices_transfer().