CALYPSO: m_intersection_data_14 Module Reference
m_intersection_data_14 Module Reference
Variables
integer(kind=kint), parameter, private nnod_tri = 3
integer(kind=kint), parameter, private nnod_hex = 6
integer(kind=kint), parameter nkind_etype_14 = 12
integer(kind=kint), parameter num_patch_14 = 4
integer(kind=kint), dimension(12), parameter itri_2_patch_14 = (/3, 1, 2, 4, 1, 3, 4, 6, 1, 4, 5, 6/)
integer(kind=kint), dimension(nkind_etype_14), parameter iflag_psf_etype_14 = (/ 23, 46, 77, 139, 232, 209, 178, 116, 99, 198, 156, 57/)
integer(kind=kint), dimension(nnod_hex, nkind_etype_14), parameter iedge_hex_14 = reshape((/ 8, 4, 3, 11, 10, 5, 5, 1, 4, 12, 11, 6, 6, 2, 1, 9, 12, 7, 7, 3, 2, 10, 9, 8, 4, 8, 5, 10, 11, 3, 1, 5, 6, 11, 12, 4, 2, 6, 7, 12, 9, 1, 3, 7, 8, 9, 10, 2, 4, 2, 11, 7, 5, 9, 1, 3, 12, 8, 6, 10, 2, 4, 9, 5, 7, 11, 3, 1, 10, 6, 8, 12/), shape=(/nnod_hex,nkind_etype_14/))
integer(kind=kint), dimension(nnod_tri, num_patch_14, nkind_etype_14), parameter iedge_4_patch_14 = reshape((/ 3, 8, 4, 11, 8, 3, 11, 5, 8, 11, 10, 5, 4, 5, 1, 12, 5, 4, 12, 6, 5, 12, 11, 6, 1, 6, 2, 9, 6, 1, 9, 7, 6, 9, 12, 7, 2, 7, 3, 10, 7, 2, 10, 8, 7, 10, 9, 8, 5, 4, 8, 10, 4, 5, 10, 3, 4, 10, 11, 3, 6, 1, 5, 11, 1, 6, 11, 4, 1, 11, 12, 4, 7, 2, 6, 12, 2, 7, 12, 1, 2, 12, 9, 1, 8, 3, 7, 9, 3, 8, 9, 2, 3, 9, 10, 2, 11, 4, 2, 7, 4, 11, 7, 9, 4, 7, 5, 9, 12, 1, 3, 8, 1, 12, 8, 10, 1, 8, 6, 10, 9, 2, 4, 5, 2, 9, 5, 11, 2, 5, 7, 11, 10, 3, 1, 6, 3, 10, 6, 12, 3, 6, 8, 12/), shape=(/nnod_tri,num_patch_14,nkind_etype_14/))
Variable Documentation
iedge_4_patch_14
integer(kind = kint), dimension(nnod_tri,num_patch_14,nkind_etype_14), parameter m_intersection_data_14::iedge_4_patch_14 = reshape((/ 3, 8, 4, 11, 8, 3, 11, 5, 8, 11, 10, 5, 4, 5, 1, 12, 5, 4, 12, 6, 5, 12, 11, 6, 1, 6, 2, 9, 6, 1, 9, 7, 6, 9, 12, 7, 2, 7, 3, 10, 7, 2, 10, 8, 7, 10, 9, 8, 5, 4, 8, 10, 4, 5, 10, 3, 4, 10, 11, 3, 6, 1, 5, 11, 1, 6, 11, 4, 1, 11, 12, 4, 7, 2, 6, 12, 2, 7, 12, 1, 2, 12, 9, 1, 8, 3, 7, 9, 3, 8, 9, 2, 3, 9, 10, 2, 11, 4, 2, 7, 4, 11, 7, 9, 4, 7, 5, 9, 12, 1, 3, 8, 1, 12, 8, 10, 1, 8, 6, 10, 9, 2, 4, 5, 2, 9, 5, 11, 2, 5, 7, 11, 10, 3, 1, 6, 3, 10, 6, 12, 3, 6, 8, 12/), shape=(/nnod_tri,num_patch_14,nkind_etype_14/))
Definition at line 73 of file m_intersection_data_14.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
iedge_hex_14
integer(kind = kint), dimension(nnod_hex,nkind_etype_14), parameter m_intersection_data_14::iedge_hex_14 = reshape((/ 8, 4, 3, 11, 10, 5, 5, 1, 4, 12, 11, 6, 6, 2, 1, 9, 12, 7, 7, 3, 2, 10, 9, 8, 4, 8, 5, 10, 11, 3, 1, 5, 6, 11, 12, 4, 2, 6, 7, 12, 9, 1, 3, 7, 8, 9, 10, 2, 4, 2, 11, 7, 5, 9, 1, 3, 12, 8, 6, 10, 2, 4, 9, 5, 7, 11, 3, 1, 10, 6, 8, 12/), shape=(/nnod_hex,nkind_etype_14/))
Definition at line 62 of file m_intersection_data_14.f90.
iflag_psf_etype_14
integer(kind = kint), dimension(nkind_etype_14), parameter m_intersection_data_14::iflag_psf_etype_14 = (/ 23, 46, 77, 139, 232, 209, 178, 116, 99, 198, 156, 57/)
Definition at line 57 of file m_intersection_data_14.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
itri_2_patch_14
integer(kind = kint), dimension(12), parameter m_intersection_data_14::itri_2_patch_14 = (/3, 1, 2, 4, 1, 3, 4, 6, 1, 4, 5, 6/)
Definition at line 54 of file m_intersection_data_14.f90.
nkind_etype_14
integer(kind = kint), parameter m_intersection_data_14::nkind_etype_14 = 12
Definition at line 52 of file m_intersection_data_14.f90.
Referenced by t_psf_case_table::init_psf_case_tables().
nnod_hex
integer(kind = kint), parameter, private m_intersection_data_14::nnod_hex = 6 private
Definition at line 50 of file m_intersection_data_14.f90.
nnod_tri
integer(kind = kint), parameter, private m_intersection_data_14::nnod_tri = 3 private
Definition at line 49 of file m_intersection_data_14.f90.
num_patch_14
integer(kind = kint), parameter m_intersection_data_14::num_patch_14 = 4
Definition at line 53 of file m_intersection_data_14.f90.
Referenced by t_psf_case_table::init_psf_case_tables().