CALYPSO: coordinate_converter Module Reference
coordinate_converter Module Reference
Functions/Subroutines
subroutine position_2_sph (n, xx, r, theta, phi, a_r, rs, a_rs)
subroutine position_2_xyz (n, rr, theta, phi, xx, yy, zz)
subroutine position_cyl_2_xyz (n, ss, phi, xx, yy)
subroutine position_sph_2_cyl_radius (n, r, theta, rs, a_rs, a_r)
subroutine position_cyl_2_sph (n, zz, rs, r, theta, a_r, a_rs)
Function/Subroutine Documentation
position_2_sph()
subroutine coordinate_converter::position_2_sph (integer (kind = kint), intent(in) n, real (kind = kreal), dimension(n,3), intent(in) xx, real (kind = kreal), dimension(n), intent(inout) r, real (kind = kreal), dimension(n), intent(inout) theta, real (kind = kreal), dimension(n), intent(inout) phi, real (kind = kreal), dimension(n), intent(inout) a_r, real (kind = kreal), dimension(n), intent(inout) rs, real (kind = kreal), dimension(n), intent(inout) a_rs)
Definition at line 82 of file coordinate_converter.f90.
References m_constants::four, and m_constants::one.
Referenced by cal_mesh_position::set_center_of_element(), and cal_mesh_position::set_spherical_position().
position_2_xyz()
subroutine coordinate_converter::position_2_xyz (integer (kind = kint) n, real(kind = kreal), dimension(n), intent(in) rr, real(kind = kreal), dimension(n), intent(in) theta, real(kind = kreal), dimension(n), intent(in) phi, real(kind = kreal), dimension(n), intent(inout) xx, real(kind = kreal), dimension(n), intent(inout) yy, real(kind = kreal), dimension(n), intent(inout) zz)
Definition at line 159 of file coordinate_converter.f90.
Referenced by set_fem_mesh_4_sph::s_const_fem_mesh_for_sph().
position_cyl_2_sph()
subroutine coordinate_converter::position_cyl_2_sph (integer (kind = kint), intent(in) n, real (kind = kreal), dimension(n), intent(in) zz, real (kind = kreal), dimension(n), intent(in) rs, real (kind = kreal), dimension(n), intent(inout) r, real (kind = kreal), dimension(n), intent(inout) theta, real (kind = kreal), dimension(n), intent(inout) a_r, real (kind = kreal), dimension(n), intent(inout) a_rs)
Definition at line 237 of file coordinate_converter.f90.
References m_constants::four, m_constants::one, and m_constants::zero.
position_cyl_2_xyz()
subroutine coordinate_converter::position_cyl_2_xyz (integer (kind = kint) n, real(kind = kreal), dimension(n), intent(in) ss, real(kind = kreal), dimension(n), intent(in) phi, real(kind = kreal), dimension(n), intent(inout) xx, real(kind = kreal), dimension(n), intent(inout) yy)
Definition at line 181 of file coordinate_converter.f90.
position_sph_2_cyl_radius()
subroutine coordinate_converter::position_sph_2_cyl_radius (integer (kind = kint), intent(in) n, real (kind = kreal), dimension(n), intent(in) r, real (kind = kreal), dimension(n), intent(in) theta, real (kind = kreal), dimension(n), intent(inout) rs, real (kind = kreal), dimension(n), intent(inout) a_rs, real (kind = kreal), dimension(n), intent(inout) a_r)
Definition at line 201 of file coordinate_converter.f90.
References m_constants::one.