CALYPSO: group_data_io Module Reference
group_data_io Module Reference
Routines for ASCII group data IO.
Functions/Subroutines
subroutine read_group_stack (id_file, ngrp, ntot, istack)
subroutine read_group_item (id_file, ngrp, ntot, istack, name, item)
subroutine read_surface_group_item (id_file, ngrp, ntot, istack, name, item_sf)
subroutine write_group_data (id_file, ngrp, ntot, istack, name, item)
subroutine write_surf_group_data (id_file, ngrp, ntot, istack, name, item_sf)
Variables
character(len=255), private character_4_read = ''
Detailed Description
Routines for ASCII group data IO.
      subroutine read_group_stack(id_file, ngrp, ntot, istack)
      subroutine read_group_item(id_file, ngrp, ntot, istack, name,   &
     &          item)
      subroutine read_surface_group_item(id_file, ngrp, ntot,         &
     &          istack, name, item_sf)
      subroutine write_group_data(id_file, ngrp, ntot, istack, name,  &
     &          item)
      subroutine write_surf_group_data(id_file, ngrp, ntot,           &
@verbatim
Function/Subroutine Documentation
read_group_item()
subroutine group_data_io::read_group_item (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) ngrp, integer(kind = kint), intent(in) ntot, integer(kind = kint), dimension(0:ngrp), intent(in) istack, character(len = kchara), dimension(ngrp), intent(inout) name, integer(kind = kint), dimension(ntot), intent(inout) item)
Definition at line 53 of file group_data_IO.f90.
References character_4_read, and skip_comment_f::skip_comment().
Referenced by groups_io::read_group_data().
read_group_stack()
subroutine group_data_io::read_group_stack (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) ngrp, integer(kind = kint), intent(inout) ntot, integer(kind = kint), dimension(0:ngrp), intent(inout) istack)
Definition at line 37 of file group_data_IO.f90.
References m_constants::izero, and field_data_io::read_arrays_for_stacks().
Referenced by groups_io::read_group_data(), and groups_io::read_surf_grp_data().
read_surface_group_item()
subroutine group_data_io::read_surface_group_item (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) ngrp, integer(kind = kint), intent(in) ntot, integer(kind = kint), dimension(0:ngrp), intent(in) istack, character(len = kchara), dimension(ngrp), intent(inout) name, integer(kind = kint), dimension(2,ntot), intent(inout) item_sf)
Definition at line 82 of file group_data_IO.f90.
References character_4_read, and skip_comment_f::skip_comment().
Referenced by groups_io::read_surf_grp_data().
write_group_data()
subroutine group_data_io::write_group_data (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) ngrp, integer(kind = kint), intent(in) ntot, integer(kind = kint), dimension(0:ngrp), intent(in) istack, character(len = kchara), dimension(ngrp), intent(in) name, integer(kind = kint), dimension(ntot), intent(in) item)
Definition at line 113 of file group_data_IO.f90.
Referenced by groups_io::write_grp_data().
write_surf_group_data()
subroutine group_data_io::write_surf_group_data (integer(kind = kint), intent(in) id_file, integer(kind = kint), intent(in) ngrp, integer(kind = kint), intent(in) ntot, integer(kind = kint), dimension(0:ngrp), intent(in) istack, character(len = kchara), dimension(ngrp), intent(in) name, integer(kind = kint), dimension(2,ntot), intent(in) item_sf)
Definition at line 142 of file group_data_IO.f90.
Referenced by groups_io::write_surf_grp_data().
Variable Documentation
character_4_read
character(len=255), private group_data_io::character_4_read = '' private
Definition at line 28 of file group_data_IO.f90.
Referenced by groups_io::read_group_data(), read_group_item(), groups_io::read_surf_grp_data(), and read_surface_group_item().