CALYPSO: const_comm_tbl_4_sph_mesh Module Reference
const_comm_tbl_4_sph_mesh Module Reference
Functions/Subroutines
subroutine count_neib_4_sph_mesh (id_rank, ip_r, ip_t, s3d_ranks, stbl, nod_comm)
subroutine count_neib_4_sph_center_mesh (id_rank, ip_r, ip_t, s3d_ranks, stbl, nod_comm)
subroutine set_neib_4_sph_mesh (id_rank, ip_r, ip_t, s3d_ranks, stbl, nod_comm)
subroutine set_neib_4_sph_center_mesh (id_rank, ip_r, ip_t, s3d_ranks, stbl, nod_comm)
subroutine count_import_4_sph_mesh (ip_r, ip_t, s3d_ranks, stbl, nod_comm)
subroutine set_import_rtp_sph_mesh (ip_r, ip_t, s3d_ranks, stbl, nod_comm)
subroutine count_export_4_sph_mesh (ip_r, ip_t, s3d_ranks, stbl, nod_comm)
subroutine set_export_rtp_sph_mesh (ip_r, ip_t, s3d_ranks, stbl, nod_comm)
Function/Subroutine Documentation
count_export_4_sph_mesh()
subroutine const_comm_tbl_4_sph_mesh::count_export_4_sph_mesh (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, type(spheric_global_rank), intent(in) s3d_ranks, type(comm_table_make_sph), intent(in) stbl, type(communication_table), intent(inout) nod_comm)
Definition at line 275 of file const_comm_tbl_4_sph_mesh.f90.
References set_export_sph_center_mesh::count_export_4_center_mesh(), set_export_sph_center_mesh::count_export_4_ctr_npole_mesh(), set_export_sph_center_mesh::count_export_4_ctr_shell_mesh(), set_comm_tbl_4_pole_mesh::count_export_4_npole_mesh(), set_comm_tbl_4_sph_mesh::count_export_4_shell_mesh(), set_comm_tbl_4_pole_mesh::count_export_4_spole_mesh(), m_constants::izero, and cal_minmax_and_stacks::s_cal_total_and_stacks().
Referenced by set_fem_mesh_4_sph::const_nod_comm_table_for_sph().
count_import_4_sph_mesh()
subroutine const_comm_tbl_4_sph_mesh::count_import_4_sph_mesh (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, type(spheric_global_rank), intent(in) s3d_ranks, type(comm_table_make_sph), intent(in) stbl, type(communication_table), intent(inout) nod_comm)
Definition at line 186 of file const_comm_tbl_4_sph_mesh.f90.
References set_import_sph_center_mesh::count_import_4_center_mesh(), set_import_sph_center_mesh::count_import_4_ctr_npole_mesh(), set_import_sph_center_mesh::count_import_4_ctr_shell_mesh(), set_comm_tbl_4_pole_mesh::count_import_4_npole_mesh(), set_comm_tbl_4_sph_mesh::count_import_4_shell_mesh(), set_comm_tbl_4_pole_mesh::count_import_4_spole_mesh(), m_constants::izero, and cal_minmax_and_stacks::s_cal_total_and_stacks().
Referenced by set_fem_mesh_4_sph::const_nod_comm_table_for_sph().
count_neib_4_sph_center_mesh()
subroutine const_comm_tbl_4_sph_mesh::count_neib_4_sph_center_mesh (integer, intent(in) id_rank, integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, type(spheric_global_rank), intent(in) s3d_ranks, type(comm_table_make_sph), intent(in) stbl, type(communication_table), intent(inout) nod_comm)
Definition at line 88 of file const_comm_tbl_4_sph_mesh.f90.
References m_constants::izero.
Referenced by set_fem_mesh_4_sph::const_nod_comm_table_for_sph().
count_neib_4_sph_mesh()
subroutine const_comm_tbl_4_sph_mesh::count_neib_4_sph_mesh (integer, intent(in) id_rank, integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, type(spheric_global_rank), intent(in) s3d_ranks, type(comm_table_make_sph), intent(in) stbl, type(communication_table), intent(inout) nod_comm)
Definition at line 59 of file const_comm_tbl_4_sph_mesh.f90.
References m_constants::izero.
Referenced by set_fem_mesh_4_sph::const_nod_comm_table_for_sph().
set_export_rtp_sph_mesh()
subroutine const_comm_tbl_4_sph_mesh::set_export_rtp_sph_mesh (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, type(spheric_global_rank), intent(in) s3d_ranks, type(comm_table_make_sph), intent(inout) stbl, type(communication_table), intent(inout) nod_comm)
Definition at line 321 of file const_comm_tbl_4_sph_mesh.f90.
References set_export_sph_center_mesh::set_export_rtp_center_mesh(), set_export_sph_center_mesh::set_export_rtp_ctr_npole_mesh(), set_export_sph_center_mesh::set_export_rtp_ctr_shell_mesh(), set_comm_tbl_4_pole_mesh::set_export_rtp_npole_mesh(), set_comm_tbl_4_sph_mesh::set_export_rtp_shell_mesh(), and set_comm_tbl_4_pole_mesh::set_export_rtp_spole_mesh().
Referenced by set_fem_mesh_4_sph::const_nod_comm_table_for_sph().
set_import_rtp_sph_mesh()
subroutine const_comm_tbl_4_sph_mesh::set_import_rtp_sph_mesh (integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, type(spheric_global_rank), intent(in) s3d_ranks, type(comm_table_make_sph), intent(inout) stbl, type(communication_table), intent(inout) nod_comm)
Definition at line 232 of file const_comm_tbl_4_sph_mesh.f90.
References set_import_sph_center_mesh::set_import_rtp_center_mesh(), set_import_sph_center_mesh::set_import_rtp_ctr_npole_mesh(), set_import_sph_center_mesh::set_import_rtp_ctr_shell_mesh(), set_comm_tbl_4_pole_mesh::set_import_rtp_npole_mesh(), set_comm_tbl_4_sph_mesh::set_import_rtp_shell_mesh(), and set_comm_tbl_4_pole_mesh::set_import_rtp_spole_mesh().
Referenced by set_fem_mesh_4_sph::const_nod_comm_table_for_sph().
set_neib_4_sph_center_mesh()
subroutine const_comm_tbl_4_sph_mesh::set_neib_4_sph_center_mesh (integer, intent(in) id_rank, integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, type(spheric_global_rank), intent(in) s3d_ranks, type(comm_table_make_sph), intent(in) stbl, type(communication_table), intent(inout) nod_comm)
Definition at line 151 of file const_comm_tbl_4_sph_mesh.f90.
References m_constants::izero.
Referenced by set_fem_mesh_4_sph::const_nod_comm_table_for_sph().
set_neib_4_sph_mesh()
subroutine const_comm_tbl_4_sph_mesh::set_neib_4_sph_mesh (integer, intent(in) id_rank, integer(kind = kint), intent(in) ip_r, integer(kind = kint), intent(in) ip_t, type(spheric_global_rank), intent(in) s3d_ranks, type(comm_table_make_sph), intent(in) stbl, type(communication_table), intent(inout) nod_comm)
Definition at line 119 of file const_comm_tbl_4_sph_mesh.f90.
References m_constants::izero.
Referenced by set_fem_mesh_4_sph::const_nod_comm_table_for_sph().