CALYPSO: sph_modes_grids_data_io_b Module Reference
sph_modes_grids_data_io_b Module Reference
Binary spectr data IO routines.
Functions/Subroutines
subroutine read_geom_rtp_data_b (id_rank, bbuf, comm_IO, sph_IO, sph_grps_IO)
subroutine read_spectr_modes_rj_data_b (id_rank, bbuf, comm_IO, sph_IO, sph_grps_IO)
subroutine read_geom_rtm_data_b (id_rank, bbuf, comm_IO, sph_IO)
subroutine read_modes_rlm_data_b (id_rank, bbuf, comm_IO, sph_IO)
subroutine write_geom_rtp_data_b (id_rank, comm_IO, sph_IO, sph_grps_IO, bbuf)
subroutine write_spectr_modes_rj_data_b (id_rank, comm_IO, sph_IO, sph_grps_IO, bbuf)
subroutine write_geom_rtm_data_b (id_rank, comm_IO, sph_IO, bbuf)
subroutine write_modes_rlm_data_b (id_rank, comm_IO, sph_IO, bbuf)
Detailed Description
Binary spectr data IO routines.
      subroutine read_geom_rtp_data_b                                 &
     &         (id_rank, bbuf, comm_IO, sph_IO, sph_grps_IO)
      subroutine read_spectr_modes_rj_data_b                          &
     &         (id_rank, bbuf, comm_IO, sph_IO, sph_grps_IO)
      subroutine read_geom_rtm_data_b                                 &
     &         (id_rank, bbuf, comm_IO, sph_IO)
      subroutine read_modes_rlm_data_b                                &
     &         (id_rank, bbuf, comm_IO, sph_IO)
        type(binary_IO_buffer), intent(inout) :: bbuf
        type(communication_table), intent(inout) :: comm_IO
        type(sph_IO_data), intent(inout) :: sph_IO
        type(sph_group_data), intent(inout) :: sph_grps_IO
      subroutine write_geom_rtp_data_b                                &
     &         (id_rank, comm_IO, sph_IO, sph_grps_IO, bbuf)
      subroutine write_spectr_modes_rj_data_b                         &
     &         (id_rank, comm_IO, sph_IO, sph_grps_IO, bbuf)
      subroutine write_geom_rtm_data_b                                &
     &         (id_rank, comm_IO, sph_IO, bbuf)
      subroutine write_modes_rlm_data_b                               &
     &         (id_rank, comm_IO, sph_IO, bbuf)
        type(communication_table), intent(in) :: comm_IO
        type(sph_IO_data), intent(in) :: sph_IO
        type(sph_group_data), intent(in) :: sph_grps_IO
Parameters
file_name file name for IO (.gz is appended in this module)
Function/Subroutine Documentation
read_geom_rtm_data_b()
subroutine sph_modes_grids_data_io_b::read_geom_rtm_data_b (integer, intent(in) id_rank, type(binary_io_buffer), intent(inout) bbuf, type(communication_table), intent(inout) comm_IO, type(sph_io_data), intent(inout) sph_IO)
Definition at line 165 of file sph_modes_grids_data_IO_b.f90.
References domain_data_io_b::read_domain_info_b(), spherical_model_io_b::read_gl_nodes_sph_b(), spherical_model_io_b::read_gl_resolution_sph_b(), domain_data_io_b::read_import_data_b(), spherical_model_io_b::read_rank_4_sph_b(), and sph_global_1d_idx_io_b::read_rtp_gl_1d_table_b().
Referenced by sph_modes_grids_file_io_b::read_geom_rtm_file_b().
read_geom_rtp_data_b()
subroutine sph_modes_grids_data_io_b::read_geom_rtp_data_b (integer, intent(in) id_rank, type(binary_io_buffer), intent(inout) bbuf, type(communication_table), intent(inout) comm_IO, type(sph_io_data), intent(inout) sph_IO, type(sph_group_data), intent(inout) sph_grps_IO)
Definition at line 61 of file sph_modes_grids_data_IO_b.f90.
References domain_data_io_b::read_domain_info_b(), spherical_model_io_b::read_gl_nodes_sph_b(), spherical_model_io_b::read_gl_resolution_sph_b(), groups_io_b::read_group_data_b(), domain_data_io_b::read_import_data_b(), spherical_model_io_b::read_rank_4_sph_b(), and sph_global_1d_idx_io_b::read_rtp_gl_1d_table_b().
Referenced by sph_modes_grids_file_io_b::read_geom_rtp_file_b().
read_modes_rlm_data_b()
subroutine sph_modes_grids_data_io_b::read_modes_rlm_data_b (integer, intent(in) id_rank, type(binary_io_buffer), intent(inout) bbuf, type(communication_table), intent(inout) comm_IO, type(sph_io_data), intent(inout) sph_IO)
Definition at line 198 of file sph_modes_grids_data_IO_b.f90.
References domain_data_io_b::read_domain_info_b(), spherical_model_io_b::read_gl_nodes_sph_b(), spherical_model_io_b::read_gl_resolution_sph_b(), domain_data_io_b::read_import_data_b(), spherical_model_io_b::read_rank_4_sph_b(), and sph_global_1d_idx_io_b::read_rj_gl_1d_table_b().
Referenced by sph_modes_grids_file_io_b::read_modes_rlm_file_b().
read_spectr_modes_rj_data_b()
subroutine sph_modes_grids_data_io_b::read_spectr_modes_rj_data_b (integer, intent(in) id_rank, type(binary_io_buffer), intent(inout) bbuf, type(communication_table), intent(inout) comm_IO, type(sph_io_data), intent(inout) sph_IO, type(sph_group_data), intent(inout) sph_grps_IO)
Definition at line 116 of file sph_modes_grids_data_IO_b.f90.
References domain_data_io_b::read_domain_info_b(), spherical_model_io_b::read_gl_nodes_sph_b(), spherical_model_io_b::read_gl_resolution_sph_b(), groups_io_b::read_group_data_b(), domain_data_io_b::read_import_data_b(), spherical_model_io_b::read_rank_4_sph_b(), and sph_global_1d_idx_io_b::read_rj_gl_1d_table_b().
Referenced by sph_modes_grids_file_io_b::read_spectr_modes_rj_file_b().
write_geom_rtm_data_b()
subroutine sph_modes_grids_data_io_b::write_geom_rtm_data_b (integer, intent(in) id_rank, type(communication_table), intent(in) comm_IO, type(sph_io_data), intent(in) sph_IO, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 326 of file sph_modes_grids_data_IO_b.f90.
References domain_data_io_b::write_domain_info_b(), spherical_model_io_b::write_gl_nodes_sph_b(), spherical_model_io_b::write_gl_resolution_sph_b(), domain_data_io_b::write_import_data_b(), spherical_model_io_b::write_rank_4_sph_b(), and sph_global_1d_idx_io_b::write_rtp_gl_1d_table_b().
Referenced by sph_modes_grids_file_io_b::write_geom_rtm_file_b().
write_geom_rtp_data_b()
subroutine sph_modes_grids_data_io_b::write_geom_rtp_data_b (integer, intent(in) id_rank, type(communication_table), intent(in) comm_IO, type(sph_io_data), intent(in) sph_IO, type(sph_group_data), intent(in) sph_grps_IO, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 234 of file sph_modes_grids_data_IO_b.f90.
References domain_data_io_b::write_domain_info_b(), spherical_model_io_b::write_gl_nodes_sph_b(), spherical_model_io_b::write_gl_resolution_sph_b(), groups_io_b::write_grp_data_b(), domain_data_io_b::write_import_data_b(), spherical_model_io_b::write_rank_4_sph_b(), and sph_global_1d_idx_io_b::write_rtp_gl_1d_table_b().
Referenced by sph_modes_grids_file_io_b::write_geom_rtp_file_b().
write_modes_rlm_data_b()
subroutine sph_modes_grids_data_io_b::write_modes_rlm_data_b (integer, intent(in) id_rank, type(communication_table), intent(in) comm_IO, type(sph_io_data), intent(in) sph_IO, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 353 of file sph_modes_grids_data_IO_b.f90.
References domain_data_io_b::write_domain_info_b(), spherical_model_io_b::write_gl_nodes_sph_b(), spherical_model_io_b::write_gl_resolution_sph_b(), domain_data_io_b::write_import_data_b(), spherical_model_io_b::write_rank_4_sph_b(), and sph_global_1d_idx_io_b::write_rj_gl_1d_table_b().
Referenced by sph_modes_grids_file_io_b::write_modes_rlm_file_b().
write_spectr_modes_rj_data_b()
subroutine sph_modes_grids_data_io_b::write_spectr_modes_rj_data_b (integer, intent(in) id_rank, type(communication_table), intent(in) comm_IO, type(sph_io_data), intent(in) sph_IO, type(sph_group_data), intent(in) sph_grps_IO, type(binary_io_buffer), intent(inout) bbuf)
Definition at line 282 of file sph_modes_grids_data_IO_b.f90.
References domain_data_io_b::write_domain_info_b(), spherical_model_io_b::write_gl_nodes_sph_b(), spherical_model_io_b::write_gl_resolution_sph_b(), groups_io_b::write_grp_data_b(), domain_data_io_b::write_import_data_b(), spherical_model_io_b::write_rank_4_sph_b(), and sph_global_1d_idx_io_b::write_rj_gl_1d_table_b().
Referenced by sph_modes_grids_file_io_b::write_spectr_modes_rj_file_b().