CALYPSO: add_direction_labels Module Reference
add_direction_labels Module Reference
put direction labels at the end of a field label
Functions/Subroutines
subroutine add_vector_direction_label_xyz (field_label, label_x, label_y, label_z)
subroutine add_vector_direction_label_rtp (field_label, label_r, label_t, label_p)
subroutine add_vector_direction_label_cyl (field_label, label_s, label_p, label_z)
subroutine add_tensor_direction_label_xyz (field_label, label_xx, label_xy, label_xz, label_yy, label_yz, label_zz)
subroutine add_tensor_direction_label_rtp (field_label, label_rr, label_rt, label_rp, label_tt, label_tp, label_pp)
subroutine add_tensor_direction_label_cyl (field_label, label_ss, label_sp, label_sz, label_pp, label_pz, label_zz)
subroutine add_asym_tensor_dir_label_xyz (field_label, label_xy, label_xz, label_yz)
subroutine add_asym_tensor_dir_label_rtp (field_label, label_rt, label_rp, label_tp)
subroutine add_asym_tensor_dir_label_cyl (field_label, label_sp, label_sz, label_pz)
subroutine add_vector_sph_spectr_label (field_label, label_pol, label_tor, label_dpol)
subroutine add_vector_power_sph_label (field_label, label_pol, label_tor, label_tot)
Variables
character(len=kchara), parameter, private x_label = '_x'
character(len=kchara), parameter, private y_label = '_y'
character(len=kchara), parameter, private z_label = '_z'
character(len=kchara), parameter, private xx_label = '_xx'
character(len=kchara), parameter, private xy_label = '_xy'
character(len=kchara), parameter, private xz_label = '_xz'
character(len=kchara), parameter, private yy_label = '_yy'
character(len=kchara), parameter, private yz_label = '_yz'
character(len=kchara), parameter, private zz_label = '_zz'
character(len=kchara), parameter, private r_label = '_r'
character(len=kchara), parameter, private t_label = '_theta'
character(len=kchara), parameter, private p_label = '_phi'
character(len=kchara), parameter, private rr_label = '_rr'
character(len=kchara), parameter, private rt_label = '_rt'
character(len=kchara), parameter, private rp_label = '_rp'
character(len=kchara), parameter, private tt_label = '_tt'
character(len=kchara), parameter, private tp_label = '_tp'
character(len=kchara), parameter, private pp_label = '_pp'
character(len=kchara), parameter, private s_label = '_s'
character(len=kchara), parameter, private ss_label = '_ss'
character(len=kchara), parameter, private sp_label = '_sp'
character(len=kchara), parameter, private sz_label = '_sz'
character(len=kchara), parameter, private pz_label = '_pz'
character(len=kchara), parameter, private pol_label = '_pol'
character(len=kchara), parameter, private dr_pol_label = '_pol_dr'
character(len=kchara), parameter, private tor_label = '_tor'
Detailed Description
put direction labels at the end of a field label
      subroutine add_vector_direction_label_xyz(field_label,          &
     &           label_x, label_y, label_z)
      subroutine add_vector_direction_label_rtp(field_label,          &
     &           label_r, label_t, label_p)
      subroutine add_vector_direction_label_cyl(field_label,          &
     &           label_s, label_p, label_z)
      subroutine add_tensor_direction_label_xyz(field_label,          &
     &           label_xx, label_xy, label_xz, label_yy, label_yz,    &
     &           label_zz)
      subroutine add_tensor_direction_label_rtp(field_label,          &
     &           label_rr, label_rt, label_rp, label_tt, label_tp,    &
     &           label_pp)
      subroutine add_tensor_direction_label_cyl(field_label,          &
     &           label_ss, label_sp, label_sz, label_pp, label_pz,    &
     &           label_zz)
      subroutine add_asym_tensor_dir_label_xyz(field_label,           &
     &           label_xy, label_xz, label_yz)
      subroutine add_asym_tensor_dir_label_rtp(field_label,           &
     &           label_rt, label_rp, label_tp)
      subroutine add_asym_tensor_dir_label_cyl(field_label,           &
     &           label_sp, label_sz, label_pz)
      subroutine add_vector_sph_spectr_label(field_label,             &
     &           label_pol, label_tor, label_dpol)
      subroutine add_vector_power_sph_label(field_label,              &
     &           label_pol, label_tor, label_tot)
Function/Subroutine Documentation
add_asym_tensor_dir_label_cyl()
subroutine add_direction_labels::add_asym_tensor_dir_label_cyl (character(len=kchara), intent(in) field_label, character(len=kchara), intent(inout) label_sp, character(len=kchara), intent(inout) label_sz, character(len=kchara), intent(inout) label_pz)
Definition at line 284 of file add_direction_labels.f90.
References pz_label, sp_label, and sz_label.
add_asym_tensor_dir_label_rtp()
subroutine add_direction_labels::add_asym_tensor_dir_label_rtp (character(len=kchara), intent(in) field_label, character(len=kchara), intent(inout) label_rt, character(len=kchara), intent(inout) label_rp, character(len=kchara), intent(inout) label_tp)
Definition at line 267 of file add_direction_labels.f90.
References rp_label, rt_label, and tp_label.
add_asym_tensor_dir_label_xyz()
subroutine add_direction_labels::add_asym_tensor_dir_label_xyz (character(len=kchara), intent(in) field_label, character(len=kchara), intent(inout) label_xy, character(len=kchara), intent(inout) label_xz, character(len=kchara), intent(inout) label_yz)
Definition at line 250 of file add_direction_labels.f90.
References xy_label, xz_label, and yz_label.
add_tensor_direction_label_cyl()
subroutine add_direction_labels::add_tensor_direction_label_cyl (character(len=kchara), intent(in) field_label, character(len=kchara), intent(inout) label_ss, character(len=kchara), intent(inout) label_sp, character(len=kchara), intent(inout) label_sz, character(len=kchara), intent(inout) label_pp, character(len=kchara), intent(inout) label_pz, character(len=kchara), intent(inout) label_zz)
Definition at line 225 of file add_direction_labels.f90.
References pp_label, pz_label, sp_label, ss_label, sz_label, and zz_label.
Referenced by sel_comp_labels_by_coord::sel_coord_tensor_comp_labels().
add_tensor_direction_label_rtp()
subroutine add_direction_labels::add_tensor_direction_label_rtp (character(len=kchara), intent(in) field_label, character(len=kchara), intent(inout) label_rr, character(len=kchara), intent(inout) label_rt, character(len=kchara), intent(inout) label_rp, character(len=kchara), intent(inout) label_tt, character(len=kchara), intent(inout) label_tp, character(len=kchara), intent(inout) label_pp)
Definition at line 201 of file add_direction_labels.f90.
References pp_label, rp_label, rr_label, rt_label, tp_label, and tt_label.
Referenced by sel_comp_labels_by_coord::sel_coord_tensor_comp_labels(), pickup_sph_coefs::set_sph_labels_4_monitor(), and t_energy_label_parameters::set_sph_rms_labels().
add_tensor_direction_label_xyz()
subroutine add_direction_labels::add_tensor_direction_label_xyz (character(len=kchara), intent(in) field_label, character(len=kchara), intent(inout) label_xx, character(len=kchara), intent(inout) label_xy, character(len=kchara), intent(inout) label_xz, character(len=kchara), intent(inout) label_yy, character(len=kchara), intent(inout) label_yz, character(len=kchara), intent(inout) label_zz)
Definition at line 177 of file add_direction_labels.f90.
References xx_label, xy_label, xz_label, yy_label, yz_label, and zz_label.
Referenced by sel_comp_labels_by_coord::sel_coord_tensor_comp_labels().
add_vector_direction_label_cyl()
subroutine add_direction_labels::add_vector_direction_label_cyl (character(len=kchara), intent(in) field_label, character(len=kchara), intent(inout) label_s, character(len=kchara), intent(inout) label_p, character(len=kchara), intent(inout) label_z)
Definition at line 159 of file add_direction_labels.f90.
References p_label, s_label, and z_label.
Referenced by sel_comp_labels_by_coord::sel_coord_vector_comp_labels().
add_vector_direction_label_rtp()
subroutine add_direction_labels::add_vector_direction_label_rtp (character(len=kchara), intent(in) field_label, character(len=kchara), intent(inout) label_r, character(len=kchara), intent(inout) label_t, character(len=kchara), intent(inout) label_p)
Definition at line 142 of file add_direction_labels.f90.
References p_label, r_label, and t_label.
Referenced by sel_comp_labels_by_coord::sel_coord_vector_comp_labels().
add_vector_direction_label_xyz()
subroutine add_direction_labels::add_vector_direction_label_xyz (character(len=kchara), intent(in) field_label, character(len=kchara), intent(inout) label_x, character(len=kchara), intent(inout) label_y, character(len=kchara), intent(inout) label_z)
Definition at line 125 of file add_direction_labels.f90.
References x_label, y_label, and z_label.
Referenced by sel_comp_labels_by_coord::sel_coord_vector_comp_labels().
add_vector_power_sph_label()
subroutine add_direction_labels::add_vector_power_sph_label (character(len=kchara), intent(in) field_label, character(len=kchara), intent(inout) label_pol, character(len=kchara), intent(inout) label_tor, character(len=kchara), intent(inout) label_tot)
Definition at line 319 of file add_direction_labels.f90.
References pol_label, and tor_label.
Referenced by t_energy_label_parameters::init_energy_labels_base(), and t_energy_label_parameters::set_sph_rms_labels().
add_vector_sph_spectr_label()
subroutine add_direction_labels::add_vector_sph_spectr_label (character(len=kchara), intent(in) field_label, character(len=kchara), intent(inout) label_pol, character(len=kchara), intent(inout) label_tor, character(len=kchara), intent(inout) label_dpol)
Definition at line 302 of file add_direction_labels.f90.
References dr_pol_label, pol_label, and tor_label.
Referenced by pickup_sph_coefs::set_sph_labels_4_monitor().
Variable Documentation
dr_pol_label
character(len=kchara), parameter, private add_direction_labels::dr_pol_label = '_pol_dr' private
Definition at line 105 of file add_direction_labels.f90.
Referenced by add_vector_sph_spectr_label().
p_label
character(len=kchara), parameter, private add_direction_labels::p_label = '_phi' private
Definition at line 90 of file add_direction_labels.f90.
Referenced by add_vector_direction_label_cyl(), and add_vector_direction_label_rtp().
pol_label
character(len=kchara), parameter, private add_direction_labels::pol_label = '_pol' private
Definition at line 104 of file add_direction_labels.f90.
Referenced by add_vector_power_sph_label(), and add_vector_sph_spectr_label().
pp_label
character(len=kchara), parameter, private add_direction_labels::pp_label = '_pp' private
Definition at line 96 of file add_direction_labels.f90.
Referenced by add_tensor_direction_label_cyl(), and add_tensor_direction_label_rtp().
pz_label
character(len=kchara), parameter, private add_direction_labels::pz_label = '_pz' private
Definition at line 102 of file add_direction_labels.f90.
Referenced by add_asym_tensor_dir_label_cyl(), and add_tensor_direction_label_cyl().
r_label
character(len=kchara), parameter, private add_direction_labels::r_label = '_r' private
Definition at line 88 of file add_direction_labels.f90.
Referenced by add_vector_direction_label_rtp().
rp_label
character(len=kchara), parameter, private add_direction_labels::rp_label = '_rp' private
Definition at line 93 of file add_direction_labels.f90.
Referenced by add_asym_tensor_dir_label_rtp(), and add_tensor_direction_label_rtp().
rr_label
character(len=kchara), parameter, private add_direction_labels::rr_label = '_rr' private
Definition at line 91 of file add_direction_labels.f90.
Referenced by add_tensor_direction_label_rtp().
rt_label
character(len=kchara), parameter, private add_direction_labels::rt_label = '_rt' private
Definition at line 92 of file add_direction_labels.f90.
Referenced by add_asym_tensor_dir_label_rtp(), and add_tensor_direction_label_rtp().
s_label
character(len=kchara), parameter, private add_direction_labels::s_label = '_s' private
Definition at line 98 of file add_direction_labels.f90.
Referenced by add_vector_direction_label_cyl().
sp_label
character(len=kchara), parameter, private add_direction_labels::sp_label = '_sp' private
Definition at line 100 of file add_direction_labels.f90.
Referenced by add_asym_tensor_dir_label_cyl(), and add_tensor_direction_label_cyl().
ss_label
character(len=kchara), parameter, private add_direction_labels::ss_label = '_ss' private
Definition at line 99 of file add_direction_labels.f90.
Referenced by add_tensor_direction_label_cyl().
sz_label
character(len=kchara), parameter, private add_direction_labels::sz_label = '_sz' private
Definition at line 101 of file add_direction_labels.f90.
Referenced by add_asym_tensor_dir_label_cyl(), and add_tensor_direction_label_cyl().
t_label
character(len=kchara), parameter, private add_direction_labels::t_label = '_theta' private
Definition at line 89 of file add_direction_labels.f90.
Referenced by add_vector_direction_label_rtp().
tor_label
character(len=kchara), parameter, private add_direction_labels::tor_label = '_tor' private
Definition at line 106 of file add_direction_labels.f90.
Referenced by add_vector_power_sph_label(), and add_vector_sph_spectr_label().
tp_label
character(len=kchara), parameter, private add_direction_labels::tp_label = '_tp' private
Definition at line 95 of file add_direction_labels.f90.
Referenced by add_asym_tensor_dir_label_rtp(), and add_tensor_direction_label_rtp().
tt_label
character(len=kchara), parameter, private add_direction_labels::tt_label = '_tt' private
Definition at line 94 of file add_direction_labels.f90.
Referenced by add_tensor_direction_label_rtp().
x_label
character(len=kchara), parameter, private add_direction_labels::x_label = '_x' private
Definition at line 78 of file add_direction_labels.f90.
Referenced by add_vector_direction_label_xyz().
xx_label
character(len=kchara), parameter, private add_direction_labels::xx_label = '_xx' private
Definition at line 81 of file add_direction_labels.f90.
Referenced by add_tensor_direction_label_xyz().
xy_label
character(len=kchara), parameter, private add_direction_labels::xy_label = '_xy' private
Definition at line 82 of file add_direction_labels.f90.
Referenced by add_asym_tensor_dir_label_xyz(), and add_tensor_direction_label_xyz().
xz_label
character(len=kchara), parameter, private add_direction_labels::xz_label = '_xz' private
Definition at line 83 of file add_direction_labels.f90.
Referenced by add_asym_tensor_dir_label_xyz(), and add_tensor_direction_label_xyz().
y_label
character(len=kchara), parameter, private add_direction_labels::y_label = '_y' private
Definition at line 79 of file add_direction_labels.f90.
Referenced by add_vector_direction_label_xyz().
yy_label
character(len=kchara), parameter, private add_direction_labels::yy_label = '_yy' private
Definition at line 84 of file add_direction_labels.f90.
Referenced by add_tensor_direction_label_xyz().
yz_label
character(len=kchara), parameter, private add_direction_labels::yz_label = '_yz' private
Definition at line 85 of file add_direction_labels.f90.
Referenced by add_asym_tensor_dir_label_xyz(), and add_tensor_direction_label_xyz().
z_label
character(len=kchara), parameter, private add_direction_labels::z_label = '_z' private
Definition at line 80 of file add_direction_labels.f90.
Referenced by add_vector_direction_label_cyl(), and add_vector_direction_label_xyz().
zz_label
character(len=kchara), parameter, private add_direction_labels::zz_label = '_zz' private
Definition at line 86 of file add_direction_labels.f90.
Referenced by add_tensor_direction_label_cyl(), and add_tensor_direction_label_xyz().