CALYPSO: set_controls_4_sph_shell Module Reference
set_controls_4_sph_shell Module Reference
Constants for spectr data.
Functions/Subroutines
subroutine set_fem_mesh_mode_4_sph (spctl, sph_params)
Detailed Description
Constants for spectr data.
      subroutine set_FEM_mesh_mode_4_SPH(spctl, sph_params)
        type(sphere_data_control), intent(in) :: spctl
        type(sph_shell_parameters), intent(inout) :: sph_params
Function/Subroutine Documentation
set_fem_mesh_mode_4_sph()
subroutine set_controls_4_sph_shell::set_fem_mesh_mode_4_sph (type(sphere_data_control), intent(in) spctl, type(sph_shell_parameters), intent(inout) sph_params)
Definition at line 31 of file set_controls_4_sph_shell.f90.
References skip_comment_f::cmp_no_case(), m_machine_parameter::iflag_debug, m_spheric_constants::iflag_mesh_same, m_spheric_constants::iflag_mesh_w_center, m_spheric_constants::iflag_mesh_w_pole, m_spheric_constants::iflag_no_femmesh, m_spheric_constants::label_mesh_ctr, m_spheric_constants::label_mesh_pole, m_spheric_constants::label_mesh_same, and m_spheric_constants::label_no_femmesh.
Referenced by t_ctl_params_gen_sph_shell::set_control_4_shell_grids(), and set_control_sph_mhd::set_control_sph_mhd_w_viz().